### ISSUE TITLE
rAthena adds null to already null-terminated chat

### ISSUE THREAD

**Issue by secretdataz** [rathena/rathena#1000]
the bug causes this code in `clif_process_message` to trigger and prevent the chat message from displaying.
```
	// the declared length must match real length
	if( messagelen != strnlen(message, messagelen)+1 ) {
		ShowWarning("clif_process_message: Received malformed packet from player '%s' (length is incorrect)!\n", sd->status.name);
		return false;
	}
```

**Comment by Lemongrass3110** [comment]
Could you tell us how to reproduce this?

**Comment by secretdataz** [comment]
Use Frost Joke skill. I think Scream is also affected.

**Comment by Playtester** [comment]
It's because the message is too long. Maybe we should just allow longer messages? Not sure how many the client allows, though.
I noticed this too, just spam Frost Joke/Dazzler and you'll eventually get warnings in map server log.
