### ISSUE TITLE
Monster transformation issues

### ISSUE THREAD

**Issue by Darkelfen** [rathena/rathena#1006]
Monster transform for items 5497 and 18856 doesn't not give ATK+25 per refine level:
5497: Eddga Doll
18856: White King Tiger Hat.

Item code:

`5497,King_Tiger_Doll_Hat,King Tiger Doll Hat,4,20,,400,,6,,1,0xFFFFFFFE,63,2,256,,1,1,495,{ bonus bStr,2; bonus bDex,2; bonus2 bAddRace,RC_Brute,10; bonus2 bMagicAddRace,RC_Brute,10; .@r = getrefine(); autobonus "{ bonus2 bSPLossRate,5,1000; bonus bBaseAtk,25*.@r; }",3*.@r,3000,BF_NORMAL,"{ transform 1115,3000; specialeffect2 EF_POTION_BERSERK; showscript \"Eddga Power !\"; }"; autobonus2 "{ bonus2 bSPLossRate,5,1000; bonus bBaseAtk,25*.@r; }",.@r,3000,BF_NORMAL,"{ transform 1115,3000; specialeffect2 EF_POTION_BERSERK; showscript \"Eddga Power !\"; }"; },{},{}
`
The problem is in this part of the code:

`autobonus "{ bonus2 bSPLossRate,5,1000; bonus bBaseAtk,25@r; }",3*.@r,3000,BF_NORMAL,"{ transform 1115,3000; specialeffect2 EF_POTION_BERSERK; showscript \"Eddga Power !\"; }";`

`.@r = getrefine();` is calculated outside the autobonus and when inside the autobonus `.@r` becomes zeroed, so the ATK bonus doesn't activate no matter how many times you transform because 25*0 = 0.

I've tested changing `.@r;` to getrefine(); and the bonus worked.

How to replicate:
Equip either 5497 or 18856, hit dummies until you transform into eddga.

Also I've tested how monster transforming bonuses with equips and consumables are working in rA, after this video made by Ziu.

https://www.youtube.com/watch?v=sFOc7W5QY1Q&feature=share

In kRo:
Equip triggered monster transformation then use monster transform scroll:  Both bonuses stack.
Scroll monster transformation then equip triggered monster transform: Both bonuses stack.
Scroll monster transform then use another monster scroll: Last used transformation bonus stack.
Equip triggered monster transform then another equip triggered transformation: Last triggered transformation bonus stack.

In rA:
Equip triggered monster transformation then use monster transform scroll: Bonuses stack, but if you transform again the scroll transformation bonus is cancelled.
Scroll monster transform then equip triggered transform: Bonuses doesn't stack, scroll bonus is overwritten by the equip triggered transformation. 
Scroll monster transform then other monster transforming scroll: Working as intented.
Equip triggered monster transform then another equip triggered transformation: Bugged, both bonuses stack.

The last scenario is possible with a Faceworm dagger equipped + Any transforming hat; since I don't have any Faceworm Dagger coded, I've replicated it by modifying a Naga Armor autobonus to transform in Naga upon activation as the hats mentioned above do.

How to replicate item triggered + scroll transformation test:
I've used shadow chaser, but any ranged auto-attacker would suffice.
Equip item 18934 Fox Ear Ribbon - Moonlight Flower Transform - Increases, crit by 100, 5% range damage bonus.
When transformed into moonlight use Any +30% range scroll ie: Raydric Archer/Gazetti.
Normal attack: Dmg 199.
W/ Moonlight Bonus: Dmg 295.
W/ Kobold Archer Transformation: Dmg 273.
Moonlight + Kobold Archer: Dmg 403.

How to replicate 2 items triggered bonus:
Equip item 18934 Fox Ear Ribbon - Moonlight Flower Transform - Increases, crit by 100, 5% range damage bonus.
Armor of Naga autobonus is +20 Base Attack
I've equipped a modified Armor_of_Naga, but a coded Faceworm Dagger should suffice to replicate.
Normal attack: Dmg 199.
W/ Moonlight Bonus: Dmg 295.
W/Armor of Naga: 216.
Naga + Moonlight: 319.
Extra: Naga + Moonlight + Kobold Archer: 435

Tests done running in renewal mode, emulator updated up to yesterday (02-03-2016).

**Comment by aleos89** [comment]
Seems the autobonus script command has its own scope on variables. Thanks for the very detailed report!

**Comment by cydh** [comment]
Well, gonna review again the Status change for Transformation.
current transformation on rAthena doesn't stack each other, not like the Ziu's test for Transformation Scrolls x Transformation Equipments.

**Comment by Darkelfen** [comment]
Yes, apparently in Aegis, they got 2 "kinds" of transformation, one for equipment based transformations, and one for consumable based transformations.

I think that "transformations" are quite similar to "autobonus", they gives a certain buff/debuff, for a certain period of time, with certain effect, triggered on certain conditions, they transform you into a mob and depending on the transformation, they either stack or are overwritten. 

The only difference with autobonus that I can see is that autobonus bonuses do stack whereas transformation bonuses stack or are overwritten.

Funny fact I've forgot to normalize the Naga Armor...

**Comment by cydh** [comment]
> Scroll monster transform then use another monster scroll: Last used transformation bonus stack.
Equip triggered monster transform then another equip triggered transformation: Last triggered transformation bonus stack.


Ziu's subtitle
> Consumables + Consumables only add the bonus to active transformacion.
Consumables + Equipment add both bonus.
Equipment + Equipment only add the bonus to active transformacion


yours & Ziu's statements are hard to understand.

But as Aegis script use 2 different commands, and mostly sends to client as 2 EFSTs:
* `EFST_MONSTER_TRANSFORM` for scrolls, instant transformation. That also calls `EFST_MTF_` (bonus details are listed in BuffSpecial.sc)
* `EFST_ACTIVE_MONSTER_TRANSFORM` for equipment bonus, (for sure) adapted as `autobonus`

Then, what we need just to split `transform` script command for different transformation SC/EFST

Actually, for further transformation bonus from equipment + equipment, I'm afraid can be tested on Aegis, all of transformation equipments are upper headgear.

**Comment by Darkelfen** [comment]
By "active transformation" Ziu and I intended to convey the meaning of last activated (triggered) transformation, sorry if sounded a bit obscure. Spanish do interfere a lot.

According to Ziu's vid, equipment + equipment bonus behaves the same as consumable + consumable, keeping the last triggered bonus; deleting the previous one.

In Ziu's vid (minute 2:44 onwards) it is exemplified what would happen if Queen Faceworm Leg bonus is triggered whilst Piamette's transformation bonus is still active.
