### ISSUE TITLE
Leap distance

### ISSUE THREAD

**Issue by Playtester** [rathena/rathena#1007]
When using leap diagonally, the distance is much smaller:
Level 1: (1,1)
Level 2: (2,2)
Level 3: (4,4)
Level 4: (5,5)
Level 5: (6,6)

Confirmed for both pre-re and renewal.

**Comment by reigneil** [comment]
how about sprint+leap=long distance jump

**Comment by Playtester** [comment]
Um, I don't think there's such a thing? If I use Leap while running, it just makes me stop.

**Comment by Drakys** [comment]
About the sprint+leap=long distance jump, I think he means this:

https://www.youtube.com/watch?v=sGOUG8xEiag

So when you use Leap while in Running, it's like your char is still running forward, but is actually not moving, thus making you jump further than usual, but if you were jumping in an invalid cell, you'd still be in the same spot you were when you tried to jump. And also, while it's still "running" towards a wall, if you reach the wall before the jump is done, you stay next to the wall until the jump occurs.

Hope that makes sense. And that was tested in Dawn of Midgard just now, not sure if there was another commit that happened to fix this.
