### ISSUE TITLE
pointshop error

### ISSUE THREAD

**Issue by Tearbytes** [rathena/rathena#1008]
I'm having errors on my pointshop after I updated to Hash: '543d2c361e0740d4e76665c37ccefc24809cffdc'

The shop isn't even opening. The only thing it's showing is the dispbottom.

`[Error]: no such shop npc : 110007538`

NPC SCRIPT:
```
prontera,177,145,4	script	Vote for Points Shop	506,{
dispbottom "You currently have "+#VOTEPOINTS+" Vote Points.";
callshop "v4p_shop",1;
end;
}
-	pointshop	v4p_shop	-1,#VOTEPOINTS,678:5,607:5,608:1
```

**Comment by julia40124009** [comment]
confirm 
itemshop same error

**Comment by Playtester** [comment]
Tracked it down to this commit: https://github.com/rathena/rathena/commit/a16fb7c1760039cbea1b7513ce1ba807abbc0b05

From what I understand you now need to use pointshop like cashshop and itemshop, but you are using it like a normal shop, that's why the error occurs.

Though if @aleos89 does changes that require different script usage he should probably post an explanation somewhere. Let's see what he says.

**Comment by Tearbytes** [comment]
Yeah. I tried to put it like this and it works.

`prontera,177,145,4	pointshop	v4p_shop	506,#VOTEPOINTS,678:5,607:5,608:1`

The thing is, it's not being specific of what item or point it is when you have insufficient item or point required. It always says 'You do not have enough Kafra Credit Points'.

**Comment by Lemongrass3110** [comment]
Don't worry we are already at it. :-)

**Comment by aleos89** [comment]
Sorry about that. I never use the callshop script command and completely forgot about it!

**Comment by Tearbytes** [comment]
Thanks for the quick fix :)

**Comment by Tearbytes** [comment]
Btw what about this "it's not being specific of what item or point it is when you have insufficient item or point required. It always says 'You do not have enough Kafra Credit Points'." part. It's not working well.

**Comment by aleos89** [comment]
I saw that yesterday while debugging some stuff. I need to figure out which packet is being sent for that so we can make it send the proper message. :)
