### ISSUE TITLE
Item_DB Problem: 2989

### ISSUE THREAD

**Issue by Vomaito** [rathena/rathena#1012]
`2989,Bloody_Floral_Decoration_Bracelet,Bloody Floral Decoration Bracelet,4,20,,100,,0,,1,0xFFFFFFFF,63,2,136,,130,,,{ bonus bVariableCastrate,-25; },{},{}
`
according to divine pride is only for Wanderer
http://www.divine-pride.net/database/item/2989
Should be:
`2989,Bloody_Floral_Decoration_Bracelet,Bloody Floral Decoration Bracelet,4,20,,100,,0,,1,0x00080000,24,0,136,,130,,,{ bonus bVariableCastrate,-25; },{},{}`

**Comment by jezznar** [comment]
I think rAthena is based off on RMS. Please check http://ratemyserver.net/index.php?iname=2989&page=re_item_db&quick=1&isearch=Search

**Comment by cydh** [comment]
@jezznar, there is no chance rAthena based on RMS! RMS that based on us, OSS Emulator

**Comment by Paoly28** [comment]
yeah i was also able to equip oz's necklace which is the counter part for aigu's floral decoration on other job. it technically doesn't exist as of now since it is part of jitterbug instance.

**Comment by jezznar** [comment]
@cydh I stand corrected. Sorry for that.
