### ISSUE TITLE
EXP problem

### ISSUE THREAD

**Issue by Sweet520** [rathena/rathena#1013]
Under the premise of discontinuous upgrade, there are something wrong in residual experience after upgrade.

For example, when I killed a monster, my experience upgrade from 0% to 90%. Then I killed another, I was promoted, but the experience displayed as 0%.

**Comment by reunite-ro** [comment]
i think related to https://github.com/rathena/rathena/issues/1010

**Comment by Lemongrass3110** [comment]
I think what you explained is related to what @cydh implemented in 20588ab

You can read the explanation on the mentioned commit and additional information is provided on #942 

If I understood you wrong, feel free to create a new ticket with more detailed information.
Thank you!

**Comment by Sweet520** [comment]
I update to ae8ba78, my problem still exists.
I think it is diffent from #942

for instance, my character’s LV is 6, the EXP displays 0%. when I kill a monster the EXP displays 90%. Than I went on to kill a same monster so that I LV up, but the EXP displays 0%. where dose the rest of the EXP go?

**Comment by reunite-ro** [comment]
@Sweet520 did u enable multi level up?

**Comment by Sweet520** [comment]
@reunite-ro
multi_level_up: no

**Comment by reunite-ro** [comment]
i think u should try enable it and tell us is it the same?

**Comment by Playtester** [comment]
@Lemongrass3110 might not have realized that you just mean the displayed exp amount on the client. I'll tell him.

**Comment by Lemongrass3110** [comment]
I just tested this on fb4cf3e again. Works totally fine.

I use a 2015-10-29 client to test. Which client are you using?

Any configurations which you think could be causing this issue?

**Comment by Sweet520** [comment]
@reunite-ro
So I tried
Yes, I think it is the same.

@Lemongrass3110
I also use 2015-10-29 client.
You don't upgrade directly, try to kill 2 or more monsters.

**Comment by Lemongrass3110** [comment]
Still working fine for me using default options:
https://youtu.be/kLDKf5LQUV4

Mind sharing your configuration/changes with us? If you want you can send them to me via PM on the board. Please do not include inter_athena.conf for security reasons. :-)

**Comment by Sweet520** [comment]
@Lemongrass3110
Please do this test:

base_exp_rate: 10000
Base level:11
EXP: 0%
JOB: Job_Novice

After I has killed a 1002,PORING, the EXP displays 46.6%.
After that, I killed a 1002,PORING, the EXP displays 93.2%.
and the last I kill a 1002,PORING, my character level up to 12, but the EXP displays 0%.
If this time, your EXP not displayed 0%, that might be my mistake. I don't think you won't display 0%.
In fact, most of my settings are default except exp_rate.
Please do not kill many monsters simultaneously.

Thank you for your test. :)
