### ISSUE TITLE
Hex colored text in NPC missing leading ^.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [rathena/rathena#1017]
![image](https://cloud.githubusercontent.com/assets/1968109/13553416/7c5d9a1e-e3ed-11e5-8caa-53dfbbc93c73.png)

**Comment by LiamKarlMitchell** [comment]
Ill take a look at fixing this and see if I can grep for where else it might be :)

**Comment by jezznar** [comment]
Hi @LiamKarlMitchell, can you giveus the script line for it? I'm thinking that it has a missing** ^** at the beginning of the hex string

**Comment by LiamKarlMitchell** [comment]
npc\re\quests\eden\eden_tutorial.txt: Line 493

![image](https://cloud.githubusercontent.com/assets/1968109/13562964/851bdaa2-e4a2-11e5-950f-5d40cc847c04.png)

**Comment by Lemongrass3110** [comment]
That one was already fixed with 614a010
