### ISSUE TITLE
Latest Version Problem.

### ISSUE THREAD

**Issue by RadianFord** [rathena/rathena#102]
Hello, currently I am using the latest revision of rAthena. I am running/testing it on Localhost.

I was testing a Daily quest script then this problem happened. I can show you how to produce this problem of mine.

here's the link..
https://www.youtube.com/watch?v=471NBwncnNo&feature=youtu.be

**Comment by Akkarinage** [comment]
@RadianFord is there any update on this issue?

**Comment by RadianFord** [comment]
@Akkarinage please close this one. It seems that its a modification problem.
