### ISSUE TITLE
Tiger Cannon splash

### ISSUE THREAD

**Issue by aleos89** [rathena/rathena#1020]
The current setup as of 80e0264 is damaging splash targets without checking for resistances.

For example: Targets who are in Safety Wall or Man Hole are being damaged when they shouldn't be.

**Comment by Vomaito** [comment]
Hi, also is drain 100% of SP.
and In http://irowiki.org/wiki/Tiger_Cannon says than drain 10% sp of de damage.

**Comment by aleos89** [comment]
Keep in mind, the user of Tiger Cannon has SP drain based on the level of the skill used while the target gets SP drain based on the damage they receive.
