### ISSUE TITLE
bHPVanishRaceRate & bSPVanishRaceRate problem on Vellum Weapons

### ISSUE THREAD

**Issue by Darkelfen** [rathena/rathena#1021]
According to item description (taken from divine-pride's korean descripts), the HP/SP vanish effect of these weapons shouldn't be activated on skills, only on normal melee/ranged attacks. 

Regarding videos from official, the Vellum weapons with HP/SP vanish effect didn't cause **any damage**, appart from the Vanished HP (displayed in red) and Vanished SP (displayed in blue) when auto-attacking. Whereas when using skills they cause damage "normally". Criticals from Vellum Scale cause 1-3 damage.

pRo Vellum Katzbalger RK.
[Link to the video](https://www.youtube.com/watch?v=8sxqkZyFiN0).

iRo Vellum Arbalest Ranger.
[Link to the video](https://www.youtube.com/watch?v=x5oRK3yOG5Q)

Vellum Scale (taken from #900 report).
[Link to the video](https://www.youtube.com/watch?v=ws1t08aUGYo)

In official:
Normal attack: HP/SP % is vanished without causing any further damage appart from that. SP damage is displayed in blue and it doesn't cause "HP" damage.
Skill attack: HP/SP % is not vanished, damage is caused normally.
Critical attack: Haven't seen vids of criticals with Vellum Katzbalger. Apparently, crits from Vellum Scale proc causing 1-3 dmg, but I couldn't determine whether the SP have been vanished from those attacks.

In rA:
SP damage is not displayed.
Normal attack: HP/SP vanishes and causes damage - Buggy.
Skill attack: HP/SP vanishes and causes damage - Buggy.
Critical damage: Test pending.

Test for Vellum Scale - ID: 1294.
on GX.
-- Only "Soul Destroyer" didn't Vanish the target's SP when hit.

Test for Vellum Buster - ID: 1395:
Test for Vellum Katzbalger - ID: 21002:
on Genetic.
-- "Hell's Plant", "Blood Sucker", "Thorns Trap", "Demonic Fire", "Acid Demonstration" didn't Vanish the target's HP/SP when hit.
on Mechanic.
-- All skills vanish target's HP/SP.

Test for Vellum Arbalest - ID: 18113
on Ranger:
-- "Blitz Beat", didn't Vanish the target's SP.
-- Ranger's "Icebound trap", "Firing trap" and "Cluster bomb" zap SP from target but Sniper's "Blast Mine" and "Claymore Trap" doesn't.
on Shadow Chaser:
-- Shadow Chaser's plagiarized and reproduced magic skills (tested: Cold Bolt, Frost Diver, Heaven's Drive and Diamond Dust) don't zap target's SP, but "Triangle Shot" Stalker's "Back stab" and "Raid" do.

Tests done on player in a pvp area.

How to reproduce:
Warp to a PvP area or activate pvp vía command.
Equip any of the weapons mentioned above on an eligible job.
Use any offensive skill on a Player Target since bonus is activated on RC_Player.
related to #618 
related to #900

**Comment by aleos89** [comment]
Also, there are reports of the actual physical damage of the Vellum weapons shouldn't do anything. You should only see the "red" damage which is the HP Vanish from the weapon.

Would also like to know if the number shows up for SP Vanish weapons!

**Comment by secretdataz** [comment]
Also, according to this [video](https://www.youtube.com/watch?v=f2RGKXAga1w), Vellum weapons with SP vanishing effect shouldn't damage target's HP at all.

**Comment by Darkelfen** [comment]
What about skill damage in official when wearing vanish-type vellums?
I got curious since on the tests I've seen, only auto-attack is used.
Do skills actually cause some damage when wearing vanish-class Vellums?

**Comment by Darkelfen** [comment]
What puzzles me is that crits do proc and cause damage 1-3 dmg, as in [this video](https://www.youtube.com/watch?v=ws1t08aUGYo) taken from #900 . 

I will add more details to the issue descript.

**Comment by Playtester** [comment]
The damage is simply 1-2, so the crit is 1-3.

**Comment by Darkelfen** [comment]
But the problem is that v-arballest only caused SP damage, but the ranger from the vid didn't land a single crit. 

The test from the v-scale was so fast that I couldn't determine if on crits the SP were taken or the crit cancelled the SP vanish or if the crit and SP damage proc together.

v-katzbalger, is what puzzles me the most, do crits from it cause 1~3 damage? is HP vanished on crits? do crits cancel HP vanish effect?
