### ISSUE TITLE
Map-server crashes when trying to change mercenary parameter

### ISSUE THREAD

**Issue by Racaae** [rathena/rathena#1024]
Script:
`.@i = getmercinfo(8);`
`setunitdata .@i,UMER_LIFETIME,9999;`

Tried with UMER_HP and UMER_MAXHP too.
It just crashes with no error.

**Comment by julia40124009** [comment]
confirm
seems to be caused by
`clif_mercenary_info(map_charid2sd(md->master_id));`

**Comment by Playtester** [comment]
At which line does it crash?

**Comment by julia40124009** [comment]
sorry 
I compiler get error
mc no master_id column

**Comment by aleos89** [comment]
Sorry about that. Fixed in 709424a.
