### ISSUE TITLE
Map-server crashes when trying to use unitkill on mercenary

### ISSUE THREAD

**Issue by Racaae** [rathena/rathena#1027]
Script:
`unitkill getmercinfo(8);`

Homunculus and elementals are working fine.
It just crashes with no error when mercenary.

**Comment by julia40124009** [comment]
confirm .

status.c
`int time = skill_get_time2(SL_KAIZEL,sc->data[SC_KAIZEL]->val1);`
https://github.com/rathena/rathena/blob/master/src/map/status.c#L1626

`return status_damage(src, target, hp, sp, 0, (!src||src==target?5:1));`
https://github.com/rathena/rathena/blob/master/src/map/status.c#L1827

version : https://github.com/rathena/rathena/commit/709424a75f344a395ff255c8960bc1bf6f0f34e6
mode : renewal

**Comment by aleos89** [comment]
It could be that it came from this commit dd67f9d at this line:
https://github.com/rathena/rathena/commit/dd67f9de968f0f69d96ae2dc6687a4c54c9381de#diff-c8e904bbc30aa59d21b9f064002805cbL363

It was adjusted from returning 0 to returning 1. That whole function is just full of craziness. So many different return values for all different object deaths. @_@

**Comment by Playtester** [comment]
Or rather, the function mercenary_dead is missing all the different checks that it should do. Should only return 1 when it's a normal respawning dead.

Also return bool on an int is generally a bad idea. Why would someone do this? =/

**Comment by aleos89** [comment]
In the *Athena world of programming, false is 0, and true is 1. So it doesn't really matter about that part.
