### ISSUE TITLE
ClaymoreTrap and BlastMine Renewal Skill_DB error

### ISSUE THREAD

**Issue by alxalmora** [rathena/rathena#1028]
Well they have this code:
`122,3,6,2,4,0xC2,1,5,1,no,0,0x80,0,misc,0,0x3800,  HT_BLASTMINE,Blast Mine
123,3,6,2,3,0xC2,2,5,1,no,0,0x40080,0,misc,0,0x3800,    HT_CLAYMORETRAP,Claymore Trap`

and accoding to that:
//    0x02 - Has splash area
//    0x40 - Skill ignores target's flee (magic type always ignores)
//    0x80 - Skill ignores target's def cards

But: in iro wiki says:
This trap will bypass Guard, Parry and Weapon Blocking.
This trap will bypass DEF and Flee.
This trap will bypass Race, Element and Size damage effects like Thara Frog, Tatacho and Ogretooth Card in PvP and WoE.
http://irowiki.org/wiki/Claymore_Trap

This trap will bypass DEF and Flee.
This trap will bypass Race, Element and Size damage effects like Thara Frog, Tatacho and Ogretooth Card in PvP and WoE.
This trap will bypass Element resistance effects like Hornet Card in PvP and WoE.
http://irowiki.org/wiki/Blast_Mine

So I think should be:
0xF2

//    0x02 - Has splash area
//    0x10 - Skill ignores elemental adjustments
//    0x20 - Skill ignores target's defense (misc type always ignores)
//    0x40 - Skill ignores target's flee (magic type always ignores)
//    0x80 - Skill ignores target's def cards

**Comment by secretdataz** [comment]
Confirmed for renewal mode.
Still needs info for pre-re.

**Comment by Playtester** [comment]
Reopening this as this change broke the skills.

Adding 0x20 isn't needed because it automatically applies for MISC skills.
Adding 0x10 makes the whole skill non-elemental, which is bad for those two traps as they actually ARE elemental.

So I say this change should be reverted.

**Comment by Playtester** [comment]
How it works in Aegis:
1. Dustiness Card does NOT reduce the damage of Blast Mine.
2. Water Armor increases the damage of Blast Mine.

So the true solution would require some coding. Maybe 0x10 should only make the skill non-elemental when the element is defined as neutral?

**Comment by cydh** [comment]
split the flag, defines what are 'elemental' mean?
- elemental from attr_fix table (eh?)
- elemental from target's armor
- elemental from target's reduction card
- elemental from caster's atk card
- .............

**Comment by Playtester** [comment]
Splitting the flag would work but it would be a lot of effort (need to update all skills). Just changing the code to say "Only ignore attr_fix table if element is neutral AND NO_ELEFIX is set" would be easier as it's just a change in the source code.
