### ISSUE TITLE
[Genetic Skill] Hell’s Plant

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#1029]
Recently I have been some problems with the skill Hell's Plant , as science of all skill should not hit Ghost property monsters and , according to the IRO , has the damage reduced by 75% for players who are equipped with Ghostring letter , tried find the same information on KRO but had trouble finding information there. In my test , the Hell's Plant is hitting ghost monsters and also hitting 100% damage on user Ghostring Card.

Links ref:

https://rathena.org/board/tracker/issue-5850-hell-plant-genetic/

https://forums.warpportal.com/index.php?/topic/131453-ghostring-vs-deviling-which-redux-is-better-for-first-purchase/

http://irowiki.org/wiki/Hell_Plant

**Comment by stealth62** [comment]
ghostring -35% neutral reduction not 75% please see the element table
http://irowiki.org/wiki/Element
note: A player's defending element is always Level 1  on table lvl1 ghost -35% neutral reduction.

**Comment by stealth62** [comment]
hells plant on player with ghost property(ghostring card) reduced to 35% not miss iro pointing on monster like iro said on there forum(Plants cannot hit Ghost property enemies. )  tried tested on iro :)

**Comment by stealth62** [comment]
i did test on my server not working  ghost property should reduced hells plant

**Comment by stealth62** [comment]
try this fix in your /db/renewal/skill_db.txt replace your old line to this new line
find this line
2491,0,6,1,0,144,0,5,1,no,0,0,0,misc,0,0x0,	GN_HELLS_PLANT_ATK,Hell's Plant Attack

then replace  to this new line
2491,0,6,1,0,128,0,5,1,no,0,0,0,misc,0,0x0,	GN_HELLS_PLANT_ATK,Hell's Plant Attack
hells plant damage reduced on ghost property enemy(gr card).

**Comment by Badarosk0** [comment]
Well, I apologize for having quoted 75 % reduction actually meant that the plant only would hit 75 % of the damage because of Ghostring that , so I know the KRO also decreases only 25 % of the damage in LVL1 property , according your table level 1 reduces only 30 % in the IRO instead informed by you that was 35% , thank you for having informed me that in any way reduces the damage is. Oh , one more thing , I mentioned that errs Ghost owned by MONSTERS and not players , anyway thanks for the information .

**Comment by stealth62** [comment]
Its ok. Your welcome

**Comment by Jeybla** [comment]
Recapped TODO:
- [ ] Hells Plant cannot target ghost property monsters.
- [ ] Hells Plant damage is reduced by 30% when the target is wearing a Ghostring Card

Can someone else confirm that?

**Comment by aleos89** [comment]
Behavior changed in #3284.
