### ISSUE TITLE
rentitem -> any box = unlimited items from box

### ISSUE THREAD

**Issue by anacondaqq** [rathena/rathena#1030]
Hello i'm talking about rentitem, sure i know about this part

> This command can not be used to rent stackable items. Rental items cannot be 
dropped, traded, sold to NPCs, or placed in guild storage. (i.e. trade mask 75)
Note: 'delitem' in an NPC script can still remove rental items.

But try to make item with rentitem for example any box, which gives an items inside this box. And you can open this box unlimited times. I think, this is very big problem, even of mistake using this command, and one fail from game master can totally destroy game server because of this bug. 

How reproduce:

1. rentitem any box which give items after destroying.
2. Destroy this box which have expire timer.
3. You will get the item from this box, but the box wont be destroyed.
4. You can destroy this box again and again.

revision: d4488d6889467936d8ce1d31e54b6ddeefc2dd48
client date: 2012-04-10
pre-re, no source edits.

**Comment by jezznar** [comment]
Hi, I think it is expected to be like that. Because rentitem is supposed to give you the script functions of an item until it expires and goes out of your inventory.

**Comment by aleos89** [comment]
So you are using rentitem on the actual Box Item, not the contents of the Box Item, correct?

**Comment by cydh** [comment]
Don't do this then. Let's say, It's working as intended.
See the rental box for 'Infinity Giant Fly Wing' (17314,Infinite_Giant_Fly_Wing_Box), the rental box gives 1 'Giant Fly Wing' (12212,Giant_Fly_Wing), and u can use it until it expired.

**Comment by anacondaqq** [comment]
got you, so it's official behavior?

**Comment by Everade** [comment]
I don't think that there's a way to tell if it's an official behavior.
Why?

Because you're not supposed to make any **box** a rental item.
I don't think that Gravity is ever going to do that,** as it doesn't make any sense to do so**.

**Comment by aleos89** [comment]
If you are renting the box item, then expect this behavior.
