### ISSUE TITLE
New mounts do not unmount player after rental reins of mount expires while logged off

### ISSUE THREAD

**Issue by jezznar** [rathena/rathena#1035]
Git Hash: b98ba7a
Client: 20141022
No Modifications
How to reproduce:
1. use this script to get a rental halter lead/ reins_of_mount
> - script HalterTest 700,{ rentitem 2262, 10; end;}
2. use the item
3. logout until the item expires
4. login
5. item removal shows but the player is left mounted

Screenshot:
before getting the item.
http://prntscr.com/acxy9
while in usage. Item not expired:
http://prntscr.com/acxymk
after expiry:
http://prntscr.com/acxyaj

workaround:
1. OnPCLoginEvent:
> - script HalterFix -1, { OnPCLoginEvent: if(ismounting()) setmounting(); end; }

**Comment by stealth62** [comment]
In my case its okay because they cant be in mounted forever.  On mounted state they can't attack.

**Comment by jezznar** [comment]
@stealth62 the problem here is that when players use a rental reins of mount then logs out, if the reins of mount expires before they login, the moment they login the item disappears but they are left mounted. which is a big problem because they can't go down anymore because if you press alt+q, you don't see any "off" button

**Comment by aleos89** [comment]
Want to give this a try? We should remove the mount on log out, then when the player logs back in we can re-apply the SC.

```
 src/map/map.c | 1 +
 1 file changed, 1 insertion(+)

diff --git a/src/map/map.c b/src/map/map.c
index 986b224..4aa67bc 100644
--- a/src/map/map.c
+++ b/src/map/map.c
@@ -2018,6 +2018,7 @@ int map_quit(struct map_session_data *sd) {
 		status_change_end(&sd->bl, SC_SUPER_STAR, INVALID_TIMER); 
 		status_change_end(&sd->bl, SC_STRANGELIGHTS, INVALID_TIMER); 
 		status_change_end(&sd->bl, SC_DECORATION_OF_MUSIC, INVALID_TIMER); 
+		status_change_end(&sd->bl, SC_ALL_RIDING, INVALID_TIMER);
 		if (battle_config.debuff_on_logout&1) { //Remove negative buffs
 			status_change_end(&sd->bl, SC_ORCISH, INVALID_TIMER);
 			status_change_end(&sd->bl, SC_STRIPWEAPON, INVALID_TIMER);
```

**Comment by stealth62** [comment]
oops my mistake yes a big problem they cant unmount if the item disappear
thank you sir aleos89 for fix :+1:

**Comment by jezznar** [comment]
@aleos89 will test this asap.

**Comment by aleos89** [comment]
Well, that diff above does resolve the problem of players getting stuck, but do official servers keep the Halter active on log out? Can someone test this and confirm?

**Comment by aleos89** [comment]
Confirmed on official servers that the mount should stay on, even after relog.

**Comment by jezznar** [comment]
so how does it go off?

**Comment by Darkelfen** [comment]
@jezznar If the item expires and you are still mounted, the only way to worn it off is via atcommand mount2. 

Some time ago, one of my players' halter lead expired while he was still mounted, the riding creature state didn't worn off with the lead so I have to manually remove the mount using that atcommand.

I dunno if in official the mounting state is removed once the halter lead expires.

**Comment by jezznar** [comment]
I see because it doesn't really make sense to remain mounted when you cant go off of it when the only "legit" way without sing any atcommand would be to unmount when logging in/off.

**Comment by Playtester** [comment]
It's official behavior actually. You have to contact support to make you unmount of buy the cash shop item again. xD

**Comment by jezznar** [comment]
@Playtester HOLY WHAT?! XDDDDDDDDDDDDD /tableflip

**Comment by Playtester** [comment]
Actually, dying also removes it, so you can also die:
https://forums.warpportal.com/index.php?/topic/144910-mount-bug/

**Comment by jezznar** [comment]
rofl. the hassle dazzle. anyway,trying out aleos' fix in a few mins. I'm implementing it. I dont really mind if it's not official behavior. It's too much of a hassle to go suicide to take it off.

**Comment by jezznar** [comment]
works.

**Comment by jezznar** [comment]
thanks @aleos89

**Comment by aleos89** [comment]
Hm, wait so if the rental expires on officials it will still not remove the mount?

**Comment by jezznar** [comment]
@aleos89 well I'm not sure about that..

**Comment by Darkelfen** [comment]
According to @Playtester yes, you need to contact technical support or buy a new halter lead if yours expires when you are still mounting.

I've tested going suicide, but death doesn't worn off the riding status in rA. Neither @mount2 nor Halter Lead based.
Githash: https://github.com/rathena/rathena/commit/b70b25945e697b3b5e6e637ac096430490ee17c5
Client: 2015-10-29.
No major modifications.

I suggest removing SC_ALL_RIDING from function status_change_clear in status.c instead. As @Playtester pointed out, death is removing SC_ALL_RIDING status.
`//Type 0: PC killed -> Place here statuses that do not dispel on death.`
https://github.com/rathena/rathena/blob/master/src/map/status.c#L10911

**Comment by Playtester** [comment]
I'm reopening this as the dispell on death should be implemented.

Note that only mounts from Halter are dispelled on death. A normal mount that you can remove with the "Off" button stays on death.
