### ISSUE TITLE
The problem of the view of Garment

### ISSUE THREAD

**Issue by Sweet520** [rathena/rathena#1036]
We need two characters to do the test.

Two characters walk into the same field of vision, and the first character logout the game after equipped the 2573, than the one log in again and move one step in any direction. 

Now we switch to the second chatacter, we will find that we can not see the view of the 2573 which the first character had equipped.

> 2573,Archangel_Wing,Archangel Wings,4,0,,200,,18,,1,0xFFFFFFFF,63,2,4,,0,1,1,{},{},{}

my Client is 2015-10-29.

**Comment by RagnarokNova** [comment]
Can confirm I've experienced this. I imagine there might be a packet not being sent? 
Generally using @refresh will make the sprite show.
