### ISSUE TITLE
Is bonus bVariableCastrate stack?

### ISSUE THREAD

**Issue by Vomaito** [rathena/rathena#1037]
Hi i was check function skill_vfcastfix
and I saw that bVariable Castrate
isnt taking all items, maybe only one.
And in iRO says that:
Sum_VCTReduc = Sum of reductions for Variable Cast Time, like Suffragium, Magic Strings, Isilla Card effect or Kathrene Keyon Card.
And I only saw one, maybe we need a for cycle instead of simple if.
http://irowiki.org/wiki/Skill#Cast_Time

**Comment by cydh** [comment]
varcast reduction is stackable

**Comment by aleos89** [comment]
As @cydh stated, it is stackable. Can you provide some skills that you were testing that made you come to this assumption? Thanks.

**Comment by Vomaito** [comment]
Example: 2 Berzebub Card + Vellum Arc Wand(+10).
(30% * 2) + 50% = 110%
And cast storm gust.
For best results change stormgust fixed cast to 0 in skill_cast_db

What I mean:

`if (sd && !(flag&4)) {
		if (sd->bonus.varcastrate != 0)
			reduce_cast_rate += sd->bonus.varcastrate; // bonus bVariableCastrate
		if (sd->bonus.fixcastrate != 0)
			fixcast_r -= sd->bonus.fixcastrate; // bonus bFixedCastrate
		if (sd->bonus.add_varcast != 0)
			time += sd->bonus.add_varcast; // bonus bVariableCast
		if (sd->bonus.add_fixcast != 0)
			fixed += sd->bonus.add_fixcast; // bonus bFixedCast
		for (i = 0; i < ARRAYLENGTH(sd->skillfixcast) && sd->skillfixcast[i].id; i++) {
			if (sd->skillfixcast[i].id == skill_id) { // bonus2 bSkillFixedCast
				fixed += sd->skillfixcast[i].val;
				break;
			}
		}
		for (i = 0; i < ARRAYLENGTH(sd->skillvarcast) && sd->skillvarcast[i].id; i++) {
			if (sd->skillvarcast[i].id == skill_id) { // bonus2 bSkillVariableCast
				time += sd->skillvarcast[i].val;
				break;
			}
		}
		for (i = 0; i < ARRAYLENGTH(sd->skillcastrate) && sd->skillcastrate[i].id; i++) {
			if (sd->skillcastrate[i].id == skill_id) { // bonus2 bVariableCastrate
				reduce_cast_rate += sd->skillcastrate[i].val;
				break;
			}
		}
		for (i = 0; i < ARRAYLENGTH(sd->skillfixcastrate) && sd->skillfixcastrate[i].id; i++) {
			if (sd->skillfixcastrate[i].id == skill_id) { // bonus2 bFixedCastrate
				fixcast_r = max(fixcast_r, sd->skillfixcastrate[i].val);
				break;
			}
		}
	}`

There is
`if (sd->bonus.varcastrate != 0)
			reduce_cast_rate += sd->bonus.varcastrate; // bonus bVariableCastrate`
I think there should be a for like:
`for (i = 0; i < ARRAYLENGTH(sd->skillcastrate) && sd->skillcastrate[i].id; i++) {
			if (sd->skillcastrate[i].id == skill_id) { // bonus2 bVariableCastrate
				reduce_cast_rate += sd->skillcastrate[i].val;
				break;
			}`

**Comment by Vomaito** [comment]
Ok, thanks, Sorry for this, I'm starting to try to understand rAthena.
