### ISSUE TITLE
royal guard's hesper lit

### ISSUE THREAD

**Issue by joelolopez** [rathena/rathena#1039]
i try hesper lit but its not working... i have 3 royal guards in banding state but it not working weird... did i miss something?

**Comment by stealth62** [comment]
Must be in party to work with hesper :) mine working

**Comment by joelolopez** [comment]
yep im in a party of 2 royal guards but i cant use hesper weird

**Comment by Paoly28** [comment]
banding requires you to be at least within 7x7 aoe from your banded party members, they also have to be within the 7x7 AoE to count. tried this and it is working

**Comment by Darkelfen** [comment]
I've tested Hesperus Lit and Genesis Ray on 3 Banded Royal Guards in party and on an Inspiration buffed RG surrounding a target in a 3x3 area centered on the target.

The results were as follows:

3 Banded RGs
--Couldn't Trigger Hesperus Lit. @stealth62  how did you manage to trigger it?.
-- Genesis Ray working.

Inspiration buff'd RG 
-- Hesperus working.
-- Genesis working.

I'm not at last hash though.

**Comment by stealth62** [comment]
ill check my src in 3 banded rgs. In inspiration buff rg hesperous and genesis ray should work.
Im using latest revision renewal mode 20130807 client .

**Comment by stealth62** [comment]
Hello this will fix hesperus lit on 3 rgs party in banding state
in skill.c
bool skill_check_condition_castbegin(struct map_session_data* sd, uint16 skill_id, uint16 skill_lv)

find this line
case LG_HESPERUSLIT:
			if (sc && sc->data[SC_INSPIRATION])
				return true; // Don't check for partner.
			if (!(sc && sc->data[SC_BANDING])) {
				clif_skill_fail(sd,skill_id,USESKILL_FAIL,0);
				return false;
			}
			if (sc->data[SC_BANDING] && sc->data[SC_BANDING]->val2 < (skill_id == LG_RAYOFGENESIS ? 2 : 3))
				return false; // Just fails, no msg here.
			break;

then replace to this line
case LG_HESPERUSLIT:
			if (sc && sc->data[SC_INSPIRATION])
				return true; // Don't check for partner.
			if (sc && sc->data[SC_BANDING] && sc->data[SC_BANDING]->val2 == 2) //myself banding +2 banding in party= 3 banding rgs
				return true;
			if (!(sc && sc->data[SC_BANDING])) {
				clif_skill_fail(sd,skill_id,USESKILL_FAIL,0);
				return false;
			}
			if (sc->data[SC_BANDING] && sc->data[SC_BANDING]->val2 < (skill_id == LG_RAYOFGENESIS ? 2 : 3))
				return false; // Just fails, no msg here.
			break;

3 rgs banding activated (party)
![screenpsychoticro000](https://cloud.githubusercontent.com/assets/14282189/13901939/066df042-edf2-11e5-8efd-a4036f562a40.jpg)

2 rgs banding activated 1 rg banding deactivated(party)
![screenpsychoticro006](https://cloud.githubusercontent.com/assets/14282189/13901945/2a185fc8-edf2-11e5-9304-39addb9578f0.jpg)

**Comment by stealth62** [comment]
thank you sir @aleos89 for fix :+1:
