### ISSUE TITLE
inspiration skill

### ISSUE THREAD

**Issue by joelolopez** [rathena/rathena#1040]
inspiration is totally useless when you already in max level? cant use inspiration in max lvl...

**Comment by stealth62** [comment]
inspiration requires 1% exp on select character screen 1000000

**Comment by joelolopez** [comment]
its not working for me when im in max base level

**Comment by Darkelfen** [comment]
I've made 2 tests.

Max level RG, leveled through quest/mob: Inspiration works as intended.
Max level RG, leveled through atcommand blvl: Inspiration fails, as exp is 0.

Also I've asked some maxed RGs from my server to use inspiration and they reported that it was buffing them.

By any chance, have you used inspiration on a levelled through commands RG?

**Comment by cydh** [comment]
I hate this issue. Why? Please read again [GitHub Issues and rAthena Bug Reporting](https://rathena.org/board/topic/104361-github-issues-and-rathena-bug-reporting/) (u aren't new in issue reporting)
And please read again 20588abcd83fab53f9e52deafc08bfcddfe1658a

**Comment by stealth62** [comment]
thank you sir cydh for the link.

**Comment by stealth62** [comment]
@Darkelfen as far as i know @blvl will jump you into a new lvl not giving  exp.

**Comment by Darkelfen** [comment]
@stealth62 Yes, I know, that's why I thought that could be the problem. I've tried to reproduce the issue, but I could only replicate it on "@blvl" RGs. Obviously, they lack the necessary amount of exp needed to cast inspiration, therefore the skill failed.

**Comment by cydh** [comment]
so @joelolopez, please recheck again your rAthena. :D
