### ISSUE TITLE
unexpected state in unit_remove_map

### ISSUE THREAD

**Issue by stealth62** [rathena/rathena#1041]
I got this error on map logs
unit_remove_map: unexpected state when removing player AID/CID:2000000/4 (active=1 connect_new=0 rewarp=0 changemap=1 debug_remove_map=1) from map=prt_in (users=0). Previous call from c:\users\kenshin\desktop\ragnarok dev\rathena-master\src\map\unit.c:3089(), current call from c:\users\kenshin\desktop\ragnarok dev\rathena-master\src\map\unit.c:3089(). Please report this!!!

![error](https://cloud.githubusercontent.com/assets/14282189/13669953/c133ff08-e67b-11e5-8551-d8bb09681391.png)

**Comment by stealth62** [comment]
i remember after i warp inside of pvpinn suddenly im outside on prontera and stuck on obstacle then im relogging in im on pvpin. I encounter this problem once only.. Ireported this because the contex said (Please report this!!!).

**Comment by Lemongrass3110** [comment]
Please try to use better titles for future issue reports.
Additionally we would need some more information about your rAthena setup like git hash and mode(prerenewal/renewal).
Thank you.

**Comment by stealth62** [comment]
Ok. Sorry sir @Lemongrass3110

**Comment by stealth62** [comment]
Im using latest revision renewal mode  20130807 client. i encounter this problem once only you can close this issue sir @Lemongrass3110.. Seems not a critical condition in IRO i also encounter that problem once in a year.
