### ISSUE TITLE
Dragon Breath

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#1042]
Hello good evening, the ability Dragon Breath is a problem if you caste the ability to distance the character the ability simply does not cause any effect, according to the iro wiki skill should hit the target to 10 cell away.

Link: http://irowiki.org/wiki/Dragon_Breath

Image: http://i.imgur.com/f7SxIAx.png

**Comment by stealth62** [comment]
maybe you're having problem in your skill database specially range of your dragon breath. 
in your db/renewal/skill_db.txt.  Try this line (mine working)
2008,9,6,2,3,0x42,1:1:1:2:2:2:3:3:4:4,10,1,no,0,0x40000,0,weapon,0,0x0,	RK_DRAGONBREATH,Dragon Breath.

**Comment by Playtester** [comment]
Did you already have updated to this commit: https://github.com/rathena/rathena/commit/7906f0a3ff3742bb519b19b0cadbca9db0d35b32?
Before that, it wasn't working.

**Comment by admkakaroto** [comment]
omg, I applied again this commit https://github.com/rathena/rathena/commit/7906f0a3ff3742bb519b19b0cadbca9db0d35b32 and it worked, apparently missed some small things, thank you very much indeed.
