### ISSUE TITLE
GX's Poisons

### ISSUE THREAD

**Issue by cydh** [rathena/rathena#1044]
All jobs should can consume them.
Currently, our `pc_isUseitem` prevents those items can be consumed.

While player consumes it, doesn't receive any status change directly by consuming it.
Mostly on Aegis, it works like
1. GX use Poisoning weapon
2. Choose the poison
3. Run the script on item

**Comment by Playtester** [comment]
Additional: Using the poison skills should require a dagger or a katar equipped.
