### ISSUE TITLE
killedrid with no id.

### ISSUE THREAD

**Issue by Daniel4rt** [rathena/rathena#1047]
I was I trying in many ways an OnNPCKillEvent and variable killedrid always appeared as 'null', I checked in every possible way, why it is happend :C?

**Comment by Darkelfen** [comment]
Are you retrieving killedrid with rid2name or with strmobinfo?

**Comment by Lemongrass3110** [comment]
Working as intended for me:
![screenrathena020](https://cloud.githubusercontent.com/assets/3517879/13726234/9bfd9ad8-e8be-11e5-841a-37b1a0c4bb86.jpg)

Test snippet:
```
-	script	Test	-1,{
	end;

OnNPCKillEvent:
	announce strcharinfo(0) + " just killed a " + strmobinfo(1,killedrid), bc_all;
	end;
}
```
