### ISSUE TITLE
skill_castend_pos and pc related

### ISSUE THREAD

**Issue by Spenon** [rathena/rathena#1051]
[Click here to view Error Image](http://tinypic.com/r/302sab5/9)

Hi, i just want to ask regarding this error. could you explain this further?

I tried understanding the gdb result but i'm having a hard time. thanks in advance

**Comment by Playtester** [comment]
Hmm, doesn't really match up well with current rAthena sources. What do you have in skill.c around line 11748 and in pc.c around line 8617?

Probably a custom modification? Don't see skill.c calling pc_readreg at all...

**Comment by aleos89** [comment]
As @Playtester stated, looks like a custom modification. There is no call of `pc_readreg` in `skill.c`.
