### ISSUE TITLE
RA_WUGDASH x Wight

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#1053]
Hello good evening, the skill: RA_WUGDASH is not increasing the damage according to the weight of the character.

No weight: http://i.imgur.com/czhSI47.jpg

Weight: http://i.imgur.com/oeCVVLM.jpg

Following link: http://irowiki.org/wiki/Warg_Dash

**Comment by RagnarokNova** [comment]
The iRO description is outdated. Weight affecting damage was personally tested by me on both iRO and on Aegis. Weight did not affect the damage.

**Comment by Lemongrass3110** [comment]
@RagnarokNova I guess you meant to say you tested on "kRO" and Aegis, right?

**Comment by aleos89** [comment]
This is working as intended. As @RagnarokNova stated, it was confirmed on officials that weight doesn't affect damage anymore.
