### ISSUE TITLE
bone_drop set

### ISSUE THREAD

**Issue by julia40124009** [rathena/rathena#1062]
player.conf
bone_drop no effect
set `bone_drop: 2`
player die not drop Skull
version : https://github.com/rathena/rathena/commit/f31475d5e32f0edcb7db252c2184697c460ae911
model : renewal

**Comment by icxbb-xx** [comment]
make sure check in item_trade.txt files

search item id skull again

**Comment by julia40124009** [comment]
sorry item_trade.txt .............
`7420,499,100	// Skull_`

**Comment by aleos89** [comment]
Maybe it would be wise to add a note to the `bone_drop` config.
