### ISSUE TITLE
Fire Expansion lvl 3 bugged since 'fix'

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#1064]
https://rathena.org/board/tracker/issue-9056-demonic-fire-fire-expansion-damage-to-players/

Only lvl4 was affected by this issue!
Skill lvl3 is supposed to be a buff, with your fix you can only buff your enemies rather than yourself or your teammates.

skill_unit_db.txt
Revert
`2487,0xe8,    ,  2, 0,  -1,enemy, 0x2000 //GN_FIRE_EXPANSION_SMOKE_POWDER`
to
`2487,0xe8,    ,  2, 0,  -1,all, 0x2000 //GN_FIRE_EXPANSION_SMOKE_POWDER`

**Comment by Lemongrass3110** [comment]
This was changed on 237579c by @aleos89.

**Comment by aleos89** [comment]
I did some tests again and it seems even Tear Gas (level 4) deals damage to party members as well.
