### ISSUE TITLE
Defending Aura Bypass Acid Demo

### ISSUE THREAD

**Issue by reunite-ro** [rathena/rathena#1065]
One of my players said that Acid Demo cannot bypass Defending Aura.

Im using iRowiki about acid demo : [http://irowiki.org/wiki/Acid_Bomb](http://irowiki.org/wiki/Acid_Bomb
)

Mode : Renewal
Server Git Hash : https://github.com/rathena/rathena/commit/f31475d5e32f0edcb7db252c2184697c460ae911

**Comment by Darkelfen** [comment]
That wiki explicitly says that AD BYPASSES defending aura, send your player to read the wiki.

**Comment by Paoly28** [comment]
#803 there's a full report about this =3

**Comment by stealth62** [comment]
try this in battle.c find this line
if (sc->data[SC_DEFENDER] && (flag&(BF_LONG|BF_WEAPON)) == (BF_LONG|BF_WEAPON) || skill_id == CR_ACIDDEMONSTRATION)
			damage -= damage * sc->data[SC_DEFENDER]->val2 / 100;

		if(sc->data[SC_ADJUSTMENT] && (flag&(BF_LONG|BF_WEAPON)) == (BF_LONG|BF_WEAPON))
			damage -= damage * 20 / 100;

and change to this line
if (sc->data[SC_DEFENDER] &&
#ifdef RENEWAL
			((flag&(BF_LONG | BF_WEAPON)) == (BF_LONG | BF_WEAPON) || skill_id == CR_ACIDDEMONSTRATION))
#else
			(flag&(BF_LONG | BF_WEAPON)) == (BF_LONG | BF_WEAPON)) // In pre-re Defender doesn't reduce damage from Acid Demonstration
#endif
			damage = damage * (100 - sc->data[SC_DEFENDER]->val2) / 100;

#ifndef RENEWAL
		if (sc->data[SC_GS_ADJUSTMENT] &&
			(flag&(BF_LONG | BF_WEAPON)) == (BF_LONG | BF_WEAPON))
			damage -= damage * 20 / 100;
#endif

this will prevent acid demo bypassing defending aura

**Comment by stealth62** [comment]
im using latest revision renewal mode 20130807 client i found out acid demo damage not reduced on defender state royal guard the code above will fix issue.

**Comment by stealth62** [comment]
without defending
![screenpsychoticro002](https://cloud.githubusercontent.com/assets/14282189/13900628/dd78fdd2-edc7-11e5-881f-36e8d6791c1a.jpg)

with defending
![screenpsychoticro003](https://cloud.githubusercontent.com/assets/14282189/13900634/f191ab48-edc7-11e5-8e77-a784b8a35241.jpg)

**Comment by stealth62** [comment]
Additional acid demonstration should miss on neutral barrier state
in battle.c
int64 battle_calc_damage(struct block_list *src,struct block_list *bl,struct Damage *d,int64 damage,uint16 skill_id,uint16 skill_lv)

find this
#ifndef RENEWAL
		if(sc->data[SC_GS_ADJUSTMENT] &&
			(flag&(BF_LONG|BF_WEAPON)) == (BF_LONG|BF_WEAPON))
			damage -= damage * 20 / 100;
#endif

then replace to this
#ifndef RENEWAL
		if(sc->data[SC_GS_ADJUSTMENT] &&
			(flag&(BF_LONG|BF_WEAPON)) == (BF_LONG|BF_WEAPON))
			damage -= damage * 20 / 100;
#endif

		if (sc->data[SC_NEUTRALBARRIER] && (d->flag&(BF_MAGIC | BF_LONG)) == BF_LONG && skill_id == CR_ACIDDEMONSTRATION) {
			d->dmg_lv = ATK_BLOCK;
			return 0;
		}

this will fix accid bomb bypassing neutral barrier
![screenpsychoticro005](https://cloud.githubusercontent.com/assets/14282189/13901064/48769ade-edd4-11e5-91dc-789895ed1a00.jpg)

with neutral barrier
![screenpsychoticro004](https://cloud.githubusercontent.com/assets/14282189/13901067/5ba40e34-edd4-11e5-8fa2-9d5f7a67f35a.jpg)

**Comment by stealth62** [comment]
additional forcing acid demonstration to neutral property
in db\re\skill_db.txt
find this line
490,9,8,1,-1,0x60,0,10,1:2:3:4:5:6:7:8:9:10,yes,0,0,0,misc,0,0x0,	CR_ACIDDEMONSTRATION,Acid Demonstration

then replace to this
490,9,8,1,0,0x60,0,10,1:2:3:4:5:6:7:8:9:10,yes,0,0,0,misc,0,0x0,	CR_ACIDDEMONSTRATION,Acid Demonstration

**Comment by secretdataz** [comment]
I can confirm this.
Acid Demonstration does not bypass Defending Aura anymore according to my test result on tRO.

**Comment by MrAntares** [comment]
It this true on kRo as well?
