### ISSUE TITLE
[BUG] Skill King's Grace - RoyalGuard

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#1068]
![image](https://cloud.githubusercontent.com/assets/13624462/13896811/369a3d44-ed79-11e5-8da9-29558a20f532.png)
The ability to be used the user and the group can not attack and is still. Currently the group is able to  attack normally. They should not move, much less attack .

Link: http://irowiki.org/wiki/King%27s_Grace

Note the line: "Players with the status however will not be able to do anything. No moving, no attacking, no skills, no item using, nothing except talk and sit until the duration ends. Land Protector can prevent the AoE from being placed, as well as remove it, but removing the AoE will not remove the status."

Hexed: 2015-05-13aRagexe

Vídeo (5:12 use skill)
https://www.youtube.com/watch?v=4y3nH-bH_ag

**Comment by stealth62** [comment]
Im also produced the bug on Kings Grace skill on my test server
mode: Renewal
git hash: daa9e01
![screenpsychicro000](https://cloud.githubusercontent.com/assets/14282189/14047287/4417f2c8-f264-11e5-8a17-6087e748cb6c.jpg)

**Comment by stealth62** [comment]
i test in iro my rg cant attack while kings grace active

**Comment by Badarosk0** [comment]
Well, add characters in your group and use the skill. All party members can attack . It can be something serious when you have classes as Ranger without saying that in a WOE hinders well .

**Comment by aleos89** [comment]
Tested on kRO and confirmed.
