### ISSUE TITLE
vending_max_value setting deprecated?

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#1069]
The setting
vending_max_value:

Does not take any effect anymore on the latest clients if you go above 1billion zeny.
**I guess it's a client side issue** as you get a pop up window saying that you've reached max amount of 1billion ?!

Not sure though.

If it's client side issue only, i know the setting might be still working by increasing the server side limit, yet _i just want to make sure i'm not waiting for a client side solution while it's bugged on serverside._

Thanks anyways

**Comment by aleos89** [comment]
Well since the banking system has been implemented one of the client messages is:
`You cannot hold more than 2,147,483,647 Zeny#`

Seems our `MAX_ZENY` is still limited to 1 billion while the bank is capped to SINT32_MAX = 7FFFFFFF = 2147483647.

**Comment by Everade** [comment]
**Currently set to:**
`#define MAX_ZENY 2000000000 ///Max zeny`

I haven't set it to SINT32_MAX but it's doubled.

So that shouldn't the the issue.
Please note that this issue is bound to the fact that you're opening a vending shop, add an item and try to set a price above 1billion.

**Comment by Everade** [comment]
@aleos89 Any news on this?

**Comment by secretdataz** [comment]
![image](https://cloud.githubusercontent.com/assets/2021243/15773983/2a7216ec-29a4-11e6-9971-dab73412289c.png)
Tested with NEMO patch, seems to be client-side limit. Re-open if you still have the issue on latest git.
