### ISSUE TITLE
Knuckle Arrow Bug

### ISSUE THREAD

**Issue by stealth62** [rathena/rathena#1071]
im using latest revision renewal mode and 20130807 client  and i found this bug on knuckle arrow. 

In my test when i use knuckle arrow on player(pvp) my character position stack with the targeted player like body relocation(snap) behavior i test in iro it shouldnt
edit: server git hash  daa9e01

**Comment by stealth62** [comment]
Any one having this issue i made a fix
in skill.c
int skill_castend_damage_id (struct block_list* src, struct block_list *bl, uint16 skill_id, uint16 skill_lv, unsigned int tick, int flag)
find this line
case SR_KNUCKLEARROW:
		// Holds current direction of bl/target to src/attacker before the src is moved to bl location
		dir_ka = map_calc_dir(bl, src->x, src->y);
		// Has slide effect
		if (skill_check_unit_movepos(5, src, bl->x, bl->y, 1, 1))
			clif_blown(src);

		if( flag&1 )
			skill_attack(BF_WEAPON, src, src, bl, skill_id, skill_lv, tick, flag|SD_LEVEL);
		else
			skill_addtimerskill(src, tick + 300, bl->id, 0, 0, skill_id, skill_lv, BF_WEAPON, flag|SD_LEVEL|2);
		break;

and replace to this line
case SR_KNUCKLEARROW:
	{
		bool path = path_search_long(NULL, src->m, src->x, src->y, bl->x, bl->y, CELL_CHKWALL);
		uint8 dir = map_calc_dir(bl, src->x, src->y);

		// teleport to target (if not on WoE grounds)
		if (skill_check_unit_movepos(3, src, bl->x, bl->y, 0, 1))
			skill_blown(src, src, 1, (dir + 4) % 8, 0); //Target position is actually one cell next to the target

		// cause damage and knockback if the path to target was a straight one
		if (path) {
			if (skill_attack(BF_WEAPON, src, src, bl, skill_id, skill_lv, tick, 1))
				skill_blown(src, bl, 1, dir, 0);
			//HACK: since knockback officially defaults to the left, the client also turns to the left... therefore,
			// make the caster look in the direction of the target
			unit_setdir(src, (dir + 4) % 8);
		}

	}
	break;

**Comment by stealth62** [comment]
im using latest revision renewal mode and 20130807 client no modification yet and i found this bug on knuckle arrow.

**Comment by stealth62** [comment]
you can see replay video here 1vs1 shura using knuckle arrow.

[knuckle arrow replay.zip](https://github.com/rathena/rathena/files/180949/knuckle.arrow.replay.zip)

**Comment by Playtester** [comment]
There's also a bug that it currently uses source weight rather than target weight for wall hit damage.

**Comment by stealth62** [comment]
The code above i get the idea from charge attack of knight. if you have a better coding sir please help. Thank you

**Comment by stealth62** [comment]
No im not asking applying my diff thats for temporary while we wait for your commit sir

**Comment by stealth62** [comment]
The double hit only works when the targeted player is in wall. if open area no double damage.

**Comment by stealth62** [comment]
in my  knuckle arrow reply.zip  the behavior is same on my mod. In near wall double damage i dont know im limited to test in iro because our internet is very slow. hard to connect on there server.

**Comment by stealth62** [comment]
single damage on open area
![screenpsychicro001](https://cloud.githubusercontent.com/assets/14282189/13906657/4285267a-ee99-11e5-8373-495240aaefd3.jpg)

double damage if targeted hits wall
![screenpsychicro002](https://cloud.githubusercontent.com/assets/14282189/13906659/5808680e-ee99-11e5-8d8e-da591b6a4dc4.jpg)

**Comment by Paoly28** [comment]
can you test it on someone wearing bryns or strong shield just for the sake of fully testing it , since currently being walled and getting hit by KA does not do 2 hits

**Comment by stealth62** [comment]
wearing brynhild targeted player can't knockback but double damage applied.
![screenpsychicro001](https://cloud.githubusercontent.com/assets/14282189/13911842/5c325ade-eef3-11e5-97b4-815f703c0e05.jpg)


wearing strong shield trageted player can't knockback but double damage applied
![screenpsychicro003](https://cloud.githubusercontent.com/assets/14282189/13911848/777dc792-eef3-11e5-8a14-ff099997e091.jpg)

**Comment by Paoly28** [comment]
now that one is weird, cause from what i know kRO removed the double hit against knockback immune or boss flagged monsters but this iRO test proved otherwise, also at Forums people say knockback immunity should prevent 2 hits at against players ofcourse getting walled still does 2 hit ? KA Snap effect also should not work on gvgflag i just tested it on my server and it has snap effect at woe.

**Comment by stealth62** [comment]
no. its my test server im in difficulty to connect on there server  icant test on my shura

**Comment by stealth62** [comment]
maybe next week if my internet speed back to normal ill test knuckle arrow

**Comment by Playtester** [comment]
Strange that the movement work on WoE for you, because skill_check_unit_movepos actually checks for it!

**Comment by Paoly28** [comment]
i mistakenly used @pvpon instead of @gvgon sorry bout that x))

**Comment by aleos89** [comment]
Confirmed on Aegis.

1) Caster should jump next to the target, not on top.
2) Knock back immune players are not pushed (and don't receive bonus damage).
3) Boss are not pushed (and don't receive bonus damage).
4) Players in Basilica are not pushed (and don't receive bonus damage).
