### ISSUE TITLE
Divest FAW not consuming Wrench?

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#1075]
The skill Divest FAW works just fine.
It checks for the item 6186 yet does **NOT **consume it.

I'm really curious... is that official?

_**What's the point in selling the Monkey Wrench for 500 Zeny at the Black Marketeer shops if you only require 1 piece for the rest of your life?!**_

The official description does not tell much of a story either...
설치된 FAW 를 해제한다. 다른 플레이어의 FAW 도 해제시킬 수 있다. 사정거리 5 셀.
Dismantles the installed FAW. It can be used to disable other players FAW's. Range 5 cells.

Only change it would require:
skill_require_db.txt
from
`2283,0,0,15,0,0,0,99,0,0,none,0,0,6186,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0							//NC_DISJOINT`
to
`2283,0,0,15,0,0,0,99,0,0,none,0,0,6186,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0							//NC_DISJOINT`

**Comment by aleos89** [comment]
Confirmed on officials that it should indeed consume a Monkey Wrench.
