### ISSUE TITLE
Silence Status Duration not reduced

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#1078]
I've seen that something has been addressed here already:
https://github.com/rathena/rathena/commit/b3b3e9cc7120e8da0c52242eb186f364d2a1e001

But i'm not sure if this issue has been addressed with it as well.

_From what i know, Silence Status DURATION caused by Lex Divina should be affected by VIT, INT and LUK._
The chance is being reduced just fine, **however the duration is not being affected at all**. Duration is always at max.

**Comment by Playtester** [comment]
Pre-renewal or renewal?

**Comment by Everade** [comment]
Renewal

**Comment by Playtester** [comment]
In renewal the chance and duration are affected by INT. And that's working fine against Lex Divina already (there are few other updates that still need to be done, though).

Tested on rAthena:
Lex Divina Level 10 vs 1 Int = 60 seconds
Lex Divina Level 10 vs 50 Int = 30 seconds

Already working.

**Comment by Everade** [comment]
Tested as well
It never reduced the duration for me...
It only reduced the chance that the skill works.

But well, if it works for you, i guess i've no clue what's wrong.

**Comment by Playtester** [comment]
Just debug it in status_get_sc_def.
