### ISSUE TITLE
Power Swing - Auto Cast Issue

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#1079]
Auto casting Axe Boomerang should only be triggered if the caster is wearing an Axe weapon.
Yet it does always cast Axe Boomerang (by a small chance) even if you don't even wear a weapon at all.

http://irowiki.org/wiki/Power_Swing

**Comment by stealth62** [comment]
Hi Everade in your db\re\skill_require_db.txt
find this line
2279,0,0,20:22:24:26:28,0,0,0,99,0,0,none,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0					//NC_POWERSWING

then replace to this line
2279,0,0,20:22:24:26:28,0,0,0,6:7,0,0,none,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0					//NC_POWERSWING

**Comment by stealth62** [comment]
this will prohibit powerswing using other weapon .

**Comment by aleos89** [comment]
It would be nice to know if this is true on kRO, not just iRO.

**Comment by Paoly28** [comment]
also seems like lvl1~4 Auto Axeboomerang doesn't work you need 5 , at least last time i tested it on rA.

**Comment by Everade** [comment]
It would make sense that it requires an axe, as the skill Axe Boomerang also requires an Axe to be used at all.

**Comment by stealth62** [comment]
The mod above will require an axe to be able to use power swing

**Comment by stealth62** [comment]
Hi Sir @aleos89 i feel iRO follows kro updates. I remember kro implements unfreezing shadow gears and iRO suddenly added freezing shadow gears. which ruin game mechanics . On that time we cant use frost driver on enemy pvp/woe its difficult to combo our enemy . Player bypasses our storm gusts they can easily infiltrate our castle.specially to shadow chaser wearing unfreezing shadow gear hard to catch.

**Comment by aleos89** [comment]
Confirmed on officials that it does indeed need an Axe type weapon to work.
