### ISSUE TITLE
Doram Patch Bug

### ISSUE THREAD

**Issue by reunite-ro** [rathena/rathena#1080]
Renewal Server 

1. WFIFOSET buffer size, i revert https://github.com/rathena/rathena/commit/aea025eca29350d2a38a3c10885bcf7286d6a1c9 and its ok already.

2. job level doram to level up so low 

3. high novice seems like having basic skills up automatically, so they cant change job (have 9 skill points left)

@aleos89  @Playtester

**Comment by secretdataz** [comment]
For job level issue, the server is using 3rd class's max jExp for summoner.

**Comment by aleos89** [comment]
1. The packet issue is because the 99d packet is not being properly calculated. I believe @Lemongrass3110 told me he was aware of it and is looking into the resolution.

2. As I stated in the forum post, there is still information missing, and EXP gain is one of the bits of information that's missing still.

3. I'll check out the issue.

**Comment by reunite-ro** [comment]
i hope its changed to priority high since high novice cannot change job for now

**Comment by Darkelfen** [comment]
Using Adv First Classes job Cap sounds reasonable at least until we got official values, as for example in [this video](https://www.youtube.com/watch?v=dZ14cbclSz4) the DoRam has it's base job already maxed out without having its base lv any nearly to max.

Other thing, using 3rd job cap, leads to DoRams max job lv cap = 60, when it should be 50, at least according to that video.

**Comment by Lemongrass3110** [comment]
Actually neither @aleos89 nor I can get our client to crash or get the character server to output the WFIFO overflow.
I created a seperate issue for this here: #1082

**Comment by Playtester** [comment]
Job Exp of Doram required is the same as Taekwon: 60, 130, 260, 460, 780, 1060, 1300, etc.

Base Exp seems to be a bit more complicated, it is much lower than all other classes: 55, 90, 150, 220, 320, 380, 420
At level 39 you need 13500 for next level.
At level 106 you need 5610000 for next level (calculated based on the video above, assuming our exp values on Venatu and Dimik and level exp bonuses are correct).

Not easy to find a pattern there. 420 would be the same as what trans classes need at level 1. And 5610000 is what 3rd job needs at level 106 minus 4000000 or what trans classes need at level 98.
