### ISSUE TITLE
WFIFO Overflow 99d in character server

### ISSUE THREAD

**Issue by Lemongrass3110** [rathena/rathena#1082]
Since I fixed the error message with the page size for clients after 2015-10-01 with aea025e some users have problems with their client crashing and their character server outputting a WFIFO overflow for the packet 99d.

From my calculations to get a WFIFO overflow(WFIFO_MAX = 1 * 1024 * 1024) you would need at least 6990 characters(150 Byte buffer per character). This also does not conform with the error messages showing something with length being about 500 bytes, which is far far below that...

Since I cannot get my client to crash nor am I able to run into that WFIFO overflow I would need detailed information and help from the users which are facing these problems.

What do I need?

1. MAX_CHARS
1. Packet Encryption enabled or disabled
1. Your clientinfo.xml(I read something on the board, that changing the servertype fixed it for some users)
1. Your client exe

Feel free to send the exe and the clientinfo via PM on the board to me.

Thanks  for your help.

**Comment by secretdataz** [comment]
1. My MAX_CHARS is 9
2. I have packet obfuscation enabled.
3. [clientinfo.xml](https://gist.github.com/secretdataz/fca4f36c8966efa1fea4)
4. My exe is the 2015-10-29aRagexe on the forum.

**Comment by julia40124009** [comment]
1. #define MAX_CHARS 24
2. Packet Encryption enabled
3. send PM
4. send PM

**Comment by reunite-ro** [comment]
1.My MAX_CHARS is 12
2.I have packet obfuscation enabled.
3. clientinfo.xml
4. My exe is the 2015-10-29aRagexe on the forum.
5. VIP Enable (not increasing max chars, only drop rate)

**Comment by admkakaroto** [comment]
1. MAX_CHARS is 18
2. I have packet obfuscation enabled.
3. clientinfo.xml. (mine is equal to the secretdataz)
4. My exe is the 2015-10-29aRagexeRE on the forum.

**Comment by reunite-ro** [comment]
@admkakaroto  are u sure u using RE or Ragexe only?

**Comment by Freyja-Folkvangr** [comment]
1 MAX_CHARS default
2 encryption enabled
3 https://www.dropbox.com/s/hmpi1i0gsn3llsg/clientinfo.xml?dl=0
4 https://www.dropbox.com/sh/h8myv0ker4mgrx9/AABOwgnOZ2lVaAwS4mC7bGiWa?dl=0
4.1 Im using beta profile.log in NEMO: https://www.dropbox.com/sh/s2mzkxhgt83fsy8/AABkzYGly9fSSCeIIqEZbczqa?dl=0

I have a virtual machine at microsoft's datacenter with git and rA, you can create a branch to fix this issue and I can help you testing
