### ISSUE TITLE
Summoner EXP

### ISSUE THREAD

**Issue by aleos89** [rathena/rathena#1083]
As of 41ed114, we are still needing official values for Summoner base experience. We have data from specific levels but a lot of data is still missing.

Also need to know if base level is capped at 150, 160, or 175.

**Comment by RagnarokNova** [comment]
Max base level is definitely 175.

**Comment by Playtester** [comment]
Exp known so far: 55, 90, 150, 220, 320, 380, 420, ???, 500, 600, 700
Exp at level 39: 13500
Exp at level 106: 5610000

**Comment by Playtester** [comment]
Got official exp for level 1-59 now! Here's the file, please test.

[job_exp.txt](https://github.com/rathena/rathena/files/183004/job_exp.txt)

**Comment by Playtester** [comment]
Reopening this as our values are only official up to base level 59 and job level 29 due to lack of data.

Let's look at this video:
https://www.youtube.com/watch?v=xvP36nZrRk0

I counted the number of kills done here calculated the total exp (exp per kill can be seen in chatlog). From that I know that 150915 base exp was earned during the video. Exp went from 50.9% to 55.0% during that time. That means 150915 base exp is equal to 4.1%. Which would lead to an estimated required base exp of 3680000.

Also important to note that even at this level, only job level 45 was reached. The required job level exp must be in the millions at this point.

As we know that the required job exp at level 29 is 68800 that means that the curve must become really steep starting at level 30.

**Comment by Playtester** [comment]
So what we really need now is the exp required at base level around 70, around 80 and around 90.
And job exp at around 35 and around 40.

Also the base level/job level relation is helpful too!

So far the relations we know is:
30/14
50/25
53/27
97/45
106/50

**Comment by Playtester** [comment]
Yikes! Turn out our pattern for job exp is not actually correct yet. I found another pattern that would fit to our results and let @RagnarokNova test some more levels for me.

Job 16: 21000
Job 27: 55000 (more accurate than previous result)

**Comment by Seth401** [comment]
I'm not 100% sure what the official values would be but it feels like there is a rather hard imbalance between the different classes. While maybe not 100% ideal it feels like summoner might be a bit low in comparison to the other classes as you level up. Generally XP in comparison to at least iRO seems somewhat low?

Extended & Third classes are included to show that level 100 seems to be more in sync. Past level 100 there is still a slight difference but it's not as pronounced. Needing half or even less than what the base classes need feels a bit ... odd.


Level | Base - Normal and Baby Jobs | Base - Trans classes | Base - Summoner | Extended classes | Third classes | % Difference Base (100%) &   Summoner
-- | -- | -- | -- | -- | -- | --
90 | 1.000.000,00 | 1.700.000,00 | 561.129,00 | 1.000.000,00 | 1.700.000,00 | 56%
91 | 1.200.000,00 | 2.040.000,00 | 606.019,00 | 1.200.000,00 | 2.040.000,00 | 51%
92 | 1.500.000,00 | 2.550.000,00 | 654.500,00 | 1.500.000,00 | 2.550.000,00 | 44%
93 | 1.800.000,00 | 3.060.000,00 | 706.860,00 | 1.800.000,00 | 3.060.000,00 | 39%
94 | 2.100.000,00 | 3.570.000,00 | 763.408,00 | 2.100.000,00 | 3.570.000,00 | 36%
95 | 2.400.000,00 | 4.080.000,00 | 824.480,00 | 2.400.000,00 | 4.080.000,00 | 34%
96 | 2.800.000,00 | 4.760.000,00 | 890.438,00 | 2.800.000,00 | 4.760.000,00 | 32%
97 | 3.300.000,00 | 5.610.000,00 | 961.673,00 | 3.300.000,00 | 5.610.000,00 | 29%
98 | 4.000.000,00 | 6.800.000,00 | 1.038.606,00 | 4.000.000,00 | 6.800.000,00 | 26%
99 | 99.999.999,00 | 99.999.999,00 | 1.121.694,00 | 1.272.747,00 | 1.272.747,00 | 88%

If you look at the Summoner table that way it's odd as there are even levels where it needs more than the XP of the base class.

**Comment by aleos89** [comment]
This should have been closed with #4377. We are currently using the table given by Gravity. You can find the table [here](https://ro.gnjoy.com/guide/ragstart/play3.asp).

**Comment by Seth401** [comment]
As mentioned in the pull request that table has been updated at some point. Back in October 2019 it was still correct but now it's somewhat off. I don't know what kind "version" rAthena is following so I can't really tell whenever it should be updated or not. I'm just going to point out the difference just in case.

For Doram there is a weird quirk from level 11 to 18:

Base- Summoner | Level | 도람족 (1-99 Level)
-- | -- | --
550 | 11 | 600
600 | 12 | 700
700 | 13 | 800
800 | 14 | 900
900 | 15 | 1000
1000 | 16 | 1100
1100 | 17 | 1200
1200 | 18 | 1300

In addition the tables for base and transcendent classes are entirely different.

Base - Trans classes | Level | 전승 직업 (1-99 Level) |   | Base - Normal and Baby Jobs | Level | 비전승 직업 (1-99 Level)
-- | -- | -- | -- | -- | -- | --
1.700.000 | 91 | 1.297.218 |   | 1.000.000 | 91 | 763.069
2.040.000 | 92 | 1.551.992 |   | 1.200.000 | 92 | 912.936
2.550.000 | 93 | 1.934.170 |   | 1.500.000 | 93 | 1.137.747
3.060.000 | 94 | 2.314.041 |   | 1.800.000 | 94 | 1.361.200
3.570.000 | 95 | 2.691.615 |   | 2.100.000 | 95 | 1.583.303
4.080.000 | 96 | 3.066.904 |   | 2.400.000 | 96 | 1.804.061
4.760.000 | 97 | 3.567.320 |   | 2.800.000 | 97 | 2.098.423
5.610.000 | 98 | 4.191.729 |   | 3.300.000 | 98 | 2.465.723
6.800.000 | 99 | 5.065.641 |   | 4.000.000 | 99 | 2.979.788

For the normal base it comes out to 1.020.212 XP and for transcendent classes it's a 1.734.359 XP difference just for the last level. In both cases it's a ~25% difference. I didn't check the level 100+ tables.

**Comment by Balferian** [comment]
@Seth401 Exp table for doram that rAthena use is correct.
You can see it in this RRF replay from kRo from 2020-09-13.
https://drive.google.com/file/d/1BK4gpH8fdeMhk1m_AjvWoe0v_sBoMjdn/view?usp=sharing

**Comment by Seth401** [comment]
Oh I don't doubt it. You guys are more knowledgeable about how to dig up that information (which seems to be a pain). I already guessed that the table isn't really authoritative, but just in case I still wanted to mention that the table and the Athena files don't match. Thanks for going through that trouble for the replay and thanks for caring for the project so much.
