### ISSUE TITLE
Moonlight Serenade - No MATK

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#1085]
Skill **Moonlight Serenade **does **not apply any MATK bonus**.

At the beginning it thought Symphony of Lovers is broken as well, but Symphony of Lovers only increases your MDEF2, so you need to wear something that increased your MDEF2 first (+25) and then ones you use Symphony of Lovers the bonus will be applied to it.

However Skill Monlight Serenade simply does not give any MATK bonus at all as it's supposed to do.
Also not MATK2 !

(no idea which one it's supposed to add)

Tested on **RENEWAL**

Has also been reported right here:
https://rathena.org/board/topic/102288-moonlight-serenade-skill-not-working-no-matk-given/

**Comment by Darkelfen** [comment]
Working in 33f397c

Tested with Cold Bolt Scroll items.

DMG before Moonlight Serenade: 48.
DMG after Moonlight Serenade: 140.

Nevertheless the Matk increase isn't reflected on your Stats window.

**Comment by Everade** [comment]
Sry, actually tested that on Lovers, but totally forgot to test it on Moonlight as well >_>

**Comment by aleos89** [comment]
As @Darkelfen stated, it's because the status window isn't properly showing the correct stuff. There's another report for that already.
