### ISSUE TITLE
@item 2168 "Immune Shield [1]" is using outdated stats

### ISSUE THREAD

**Issue by Paoly28** [rathena/rathena#1088]
http://forums.irowiki.org/showthread.php?p=1158980#post1158980

old kRO Patchnotes posted by Doddler on iro forums, we never got the update regarding the item.

current script
`{ .@r = getrefine(); if (.@r>5) bonus2 bSubEle,Ele_Neutral,((.@r>12)?12:.@r)-5; },{},{}`
total = 7% neutral resist

**Comment by secretdataz** [comment]
Avoid using @ symbol without encapsulating it in a code block as it can mention a random github user :P
```
{ .@r = getrefine(); if (.@r>5) bonus2 bSubEle,Ele_Neutral,((.@r>12)?12:.@r)-5; if(.@r>6) bonus2 bSubEle,Ele_Neutral,5; if(.@r>8) { bonus2 bSubEle,Ele_Fire,5; bonus2 bSubEle,Ele_Water,5; bonus2 bSubEle,Ele_Wind,5; bonus2 bSubEle,Ele_Earth,5; } }
```

**Comment by Paoly28** [comment]
sorry about that xD thx
