### ISSUE TITLE
doram skills wont accept skill points and messed up 

### ISSUE THREAD

**Issue by joelolopez** [rathena/rathena#1093]
i notice that after gaining a job level using doram i can't spend my skill points in my dorams skill tree.. and i notice that i got basic skills in "etc. tab"

**Comment by secretdataz** [comment]
this issue is fixed in 41ed1144930fea97f6f3b5a84ec97f1826682f35.

**Comment by joelolopez** [comment]
thanks secretdataz! please close this issue
