### ISSUE TITLE
Warmer

### ISSUE THREAD

**Issue by aleos89** [rathena/rathena#1097]
Hash: c6720b2
Mode: Both

Warmer should not start the status again every 3 seconds while players are standing in the AoE. Also when a player walks out of the AoE the status should end.

**Comment by Playtester** [comment]
Sounds like interval should be -1.

**Comment by aleos89** [comment]
Warmer has a healing property that triggers every 3 seconds, but the status `SC_WARMER`, while active, keeps you being Frozen, Freezing, and Crystallized.

The problem right now is that we apply `SC_WARMER`  every 3 seconds so the duration for `SC_WARMER` keeps updating itself until the unit ends. Then players have a status immunity from those three statuses above for 30 seconds.

**Comment by Playtester** [comment]
Ah I see. Could do it like Apple of Idun then?

**Comment by RagnarokNova** [comment]
That sounds like it'd be spot on Playtester, save for the additional 20 (Or was it 30?) seconds of the HP boost effect after you leave the area.

**Comment by aleos89** [comment]
The effect isn't being removed properly when leaving the AoE. I will rework this.
