### ISSUE TITLE
request page popping up again

### ISSUE THREAD

**Issue by joelolopez** [rathena/rathena#1103]
the request page problem is back after the doram release xo, this issue has been fixed but now its back again popping out on the character creation screen

**Comment by secretdataz** [comment]
That's the price you pay for reverting aea025eca29350d2a38a3c10885bcf7286d6a1c9 to fix the WFIFO bug on char server. Either move to 2015-10-29aRagexe or wait for the devs to fix the issue.

**Comment by Playtester** [comment]
If client supports it you can just change "false" to "true", no?

https://github.com/rathena/rathena/commit/33f397c025ac07518a48c2dfccdf28ac544555d3

Not sure why it was done like that. Some client work with it and others don't?

**Comment by secretdataz** [comment]
That part of code cause some clients to crash and WFIFO errors.

**Comment by aleos89** [comment]
This is part of a larger issue that the whole char-server is sending the wrong packets. Lemongrass has the packet structure and will resolve it when he's free again.

**Comment by Lemongrass3110** [comment]
Just do as playtester said and everything will be fine. The packet structure is different for kro main and kro sakray from this point on.
Everything is working as intended.
