### ISSUE TITLE
Warning on Linux

### ISSUE THREAD

**Issue by RadianFord** [rathena/rathena#1105]
unit.c:In function 'unit_stop_walking' : 
unit.c:1248: warning: 'td' may be used uninitialized in this function
`const struct TimerData* td;` 

script.c: In function 'buildin_clone' : 
script.c:9960: warning: 'mode' may be used uninitialized in this function
`enum e_mode mode;`

battle.c: In function 'battle_calc_skill_constant_addition'
battle.c:4254: warning: unused variable 'sc' : 
`struct status_change *sc = status_get_sc(src);`

I did compile this one one VB and no warnings but after on linux the warning show up.

My trunk date is March 19 2016

**Comment by Playtester** [comment]
Nothing critical and easy to fix, will do it quick. :-)

**Comment by RadianFord** [comment]
Thanks! @Playtester
