### ISSUE TITLE
bug:skill : the skills of sommer not attack in pre-re

### ISSUE THREAD

**Issue by OmarAcero** [rathena/rathena#1106]
the skills of Doram, are not working in pre - Renewal ... You can't attack with the skills ... But nevertheless.. I can raise the level Skill...

Note:  [http://imgur.com/a/DJuJf](url)

**Comment by Darkelfen** [comment]
Maybe it is because DoRam is a renewal feature, I guess you might import the DoRam skills from re folder.

**Comment by OmarAcero** [comment]
i am using new  version of rathena, in renewall work fine, the problem is in pre-re.. update all /db/pre-re
with the commits [#1095]https://github.com/rathena/rathena/commit/c6720b21a6d8296f1978ec0f7be2736abc0d9ea0) 
-------
Note: I think it's something in the db/pre-re/skill_stree.txt (I'm using the same that renewal)

**Comment by Playtester** [comment]
New renewal classes are not support in pre-renewal. You'll have to compile on renewal to use them.

**Comment by aleos89** [comment]
I only put placeholders in the pre-renewal skill databases. Meaning the skills are just passive, unusable skills. If you want to use it for pre-renewal then you'll have to copy the data to your import files.

**Comment by OmarAcero** [comment]
Solved ty :dancers: 
<a href="https://rathena.org/board/topic/105295-jobdbredesign-rathena-can-add-this-commit/#entry300213 ">Solution</a>
