### ISSUE TITLE
DoRam equipment - Wrong Combos and more equipments

### ISSUE THREAD

**Issue by Darkelfen** [rathena/rathena#1107]
On https://github.com/rathena/rathena/commit/107a724ed9dfd97778ba29b997cbf61aeb56073b, there is a small problem with DoRam combos: Lines 385, 386 & 389.

The bonus per refinement is increasing the fixed cast rate whilst it should decrease the fixed cast rate.

Just replacing
```
15126:20788:22083,{ ...  bonus bFixedCastrate,15+.@r; }
```
to 
```
15126:20788:22083,{ ...  bonus bFixedCastrate,15-.@r; }
```

will do.

Also, I've corrected some items posted on 107a724 but I'm not sure with price and weight.

Items:
```
28413,Lesser_Mackerel_Talisman,Lesser Mackerel Talisman,4,0,,100,,1,,1,0x80000000,63,2,136,,100,0,,{ bonus bVit,1; },{},{}
28414,Intermediate_Mackerel_Talisman,Intermediate Mackerel Talisman,4,0,,100,,1,,1,0x80000000,63,2,136,,140,0,,{ bonus bVit,2; },{},{}
28415,Greater_Mackerel_Talisman,Greater Mackerel Talisman,4,0,,100,,1,,1,0x80000000,63,2,136,,175,0,,{ bonus bVit,3; },{},{}
28416,Lesser_Leaf_Talisman,Lesser Leaf Talisman,4,0,,100,,1,,1,0x80000000,63,2,136,,100,0,,{ bonus bInt,1; },{},{}
28417,Intermediate_Lesser_Leaf_Talisman,Intermediate Leaf Talisman,4,0,,100,,1,,1,0x80000000,63,2,136,,140,0,,{ bonus bInt,2; },{},{}
28418,Greater_Leaf_Talisman,Greater Leaf Talisman,4,0,,100,,1,,1,0x80000000,63,2,136,,175,0,,{ bonus bInt,3; },{},{}
28419,Lesser_Rabbit_Talisman,Lesser Leaf Talisman,4,0,,100,,1,,1,0x80000000,63,2,136,,100,0,,{ bonus bDex,1; },{},{}
28420,Intermediate_Rabbit_Talisman,Intermediate Leaf Talisman,4,0,,100,,1,,1,0x80000000,63,2,136,,140,0,,{ bonus bDex,2; },{},{}
28421,Greater_Rabbit_Talisman,Greater Rabbit Talisman,4,0,,100,,1,,1,0x80000000,63,2,136,,175,0,,{ bonus bDex,3; },{},{}
28422,Shiny_Branch_Talisman,Shiny Branch Talisman,4,0,,100,,1,,1,0x80000000,63,2,136,,100,0,,{ bonus2 bVariableCastrate,"SU_SV_STEMSPEAR",-50; bonus2 bSkillAtk,"SU_SV_STEMSPEAR",readparam(bInt) + 20 * getskilllv("SU_SV_STEMSPEAR"); },{},{}
28423,Fresh_Tuna_Talisman,Fresh Tuna Talisman,4,0,,100,,1,,1,0x80000000,63,2,136,,100,0,,{ bonus bMaxHP,100; bonus2 bSkillCooldown,"SU_TUNAPARTY",-7000; bonus3 bAutoSpellWhenHit,"SU_TUNAPARTY",getskilllv("SU_TUNAPARTY")?getskilllv("SU_TUNAPARTY"):1,10; },{},{}
28424,Chubby_Worm_Talisman,Chubby Worm Talisman,4,0,,100,,1,,1,0x80000000,63,2,136,,100,0,,{ bonus2 bVariableCastrate,"SU_PICKYPECK",-50; bonus2 bSkillAtk,"SU_PICKYPECK",readparam(bDex) + 20 * getskilllv("SU_PICKYPECK"); },{},{}
```
Combos:
```
28413:28381:15129:20789:22084,{ bonus bMaxHPrate,15; bonus bMaxSPrate,5; bonus bHealPower,10; skill "AC_HEAL",5; }
28414:28381:15129:20789:22084,{ bonus bMaxHPrate,20; bonus bMaxSPrate,10; bonus bHealPower,20; skill "AC_HEAL",7; }
28415:28381:15129:20789:22084,{ bonus bMaxHPrate,25; bonus bMaxSPrate,15; bonus bHealPower,30; skill "AC_HEAL",9; }
28416:28380:15156:20790:22085,{ bonus bMaxHPrate,10; bonus bMaxSPrate,10; bonus2 bSkillAtk,"SU_CN_METEOR",100; }
28417:28380:15156:20790:22085,{ bonus bMaxHPrate,15; bonus bMaxSPrate,15; bonus2 bSkillAtk,"SU_CN_METEOR",150; }
28418:28380:15156:20790:22085,{ bonus bMaxHPrate,20; bonus bMaxSPrate,20; bonus2 bSkillAtk,"SU_CN_METEOR",200; }
28419:28382:15126:20788:22083,{ bonus bMaxHPrate,20; bonus bMaxSPrate,3; bonus2 bSkillAtk,"SU_LUNATICCARROTBEAT",100; }
28420:28382:15126:20788:22083,{ bonus bMaxHPrate,25; bonus bMaxSPrate,6; bonus2 bSkillAtk,"SU_LUNATICCARROTBEAT",150; }
28421:28382:15126:20788:22083,{ bonus bMaxHPrate,30; bonus bMaxSPrate,9; bonus2 bSkillAtk,"SU_LUNATICCARROTBEAT",200; }
```

Thanks to @Daniel4rt for providing the items and combos.

**Comment by secretdataz** [comment]
Yeah, I made some typos. But your fix isn't correct either.
```
15126:20788:22083,{ ...  bonus bFixedCastrate,15+.@r; }
```
must be
```
15126:20788:22083,{ ...  bonus bFixedCastrate,-(15+.@r); }
```

**Comment by Darkelfen** [comment]
Oopsies sorry 'bout that, my Korean is at g-translate level which is less than sh*t, so I've messed up with fixed cast and the statement in parenthesis. I've assumed +15% increase then decrease with gear refinement level. 

Apologies.

**Comment by Daniel4rt** [comment]
Some fixes:
28413,Lesser_Mackerel_Talisman,Lesser Mackerel Talisman,4,0,,100,,1,,1,0x80000000,63,2,136,1,1,1,,{ bonus bVit,1; },{},{}
28414,Intermediate_Mackerel_Talisman,Intermediate Mackerel Talisman,4,0,,100,,1,,1,0x80000000,63,2,136,1,1,1,,{ bonus bVit,2; },{},{}
28415,Greater_Mackerel_Talisman,Greater Mackerel Talisman,4,0,,100,,1,,1,0x80000000,63,2,136,1,1,1,,{ bonus bVit,3; },{},{}
28416,Lesser_Leaf_Talisman,Lesser Leaf Talisman,4,0,,100,,1,,1,0x80000000,63,2,136,1,1,1,,{ bonus bInt,1; },{},{}
28417,Intermediate_Leaf_Talisman,Intermediate Leaf Talisman,4,0,,100,,1,,1,0x80000000,63,2,136,1,1,1,,{ bonus bInt,2; },{},{}
28418,Greater_Leaf_Talisman,Greater Leaf Talisman,4,0,,100,,1,,1,0x80000000,63,2,136,1,1,1,,{ bonus bInt,3; },{},{}
28419,Lesser_Rabbit_Talisman,Lesser Rabbit Talisman,4,0,,100,,1,,1,0x80000000,63,2,136,1,1,1,,{ bonus bDex,1; },{},{}
28420,Intermediate_Rabbit_Talisman,Intermediate Rabbit Talisman,4,0,,100,,1,,1,0x80000000,63,2,136,1,1,1,,{ bonus bDex,2; },{},{}
28421,Greater_Rabbit_Talisman,Greater Rabbit Talisman,4,0,,100,,1,,1,0x80000000,63,2,136,1,1,1,,{ bonus bDex,3; },{},{}
28422,Shiny_Branch_Talisman,Shiny Branch Talisman,4,0,,100,,1,,1,0x80000000,63,2,136,1,1,1,,{ bonus2 bVariableCastrate,"SU_SV_STEMSPEAR",-50; bonus2 bSkillAtk,"SU_SV_STEMSPEAR",(20 * getskilllv("SU_SV_STEMSPEAR")); bonus2 bSkillAtk,"SU_SV_STEMSPEAR",(readparam(bInt)/2); },{},{}
28423,Fresh_Tuna_Talisman,Fresh Tuna Talisman,4,0,,100,,1,,1,0x80000000,63,2,136,1,1,1,,{ bonus bMaxHP,100; bonus2 bSkillCooldown,"SU_TUNAPARTY",-7000; .@lv = getskilllv("SU_TUNAPARTY"); bonus3 bAutoSpellWhenHit,"SU_TUNAPARTY",(.@lv ? .@lv : 1),10; },{},{}
28424,Chubby_Worm_Talisman,Chubby Worm Talisman,4,0,,100,,1,,1,0x80000000,63,2,136,1,1,1,,{ bonus2 bVariableCastrate,"SU_PICKYPECK",-50; bonus2 bSkillAtk,"SU_PICKYPECK",(20 * getskilllv("SU_PICKYPECK")); bonus2 bSkillAtk,"SU_PICKYPECK",(readparam(bDex)/2); },{},{}
// Doram Token
25142,Doram_Token,Doram Token,3,,0,0,,,,,,,,,,,,,{},{},{}


// Combos Doram
15156:20790:22085,{ bonus bMaxHP,4000; bonus bNoCastCancel,0; bonus bFixedCastrate,-25; }
36026:36039,{ bonus bAllStats,2; bonus2 bAddMonsterDropItem,11552,2; }
15126:20788:22083,{ bonus bMaxHP,2000; bonus bNoCastCancel,0; bonus bFixedCastrate,-15; }
28413:28381:20788:22083,{ bonus bMaxHPrate,15; bonus bMaxSPrate,5; bonus bHealPower,10; skill "AL_HEAL",5,1; }
28414:28381:20789:22084,{ bonus bMaxHPrate,20; bonus bMaxSPrate,10; bonus bHealPower,20; skill "AL_HEAL",7,1; }
28415:28381:20790:22085,{ bonus bMaxHPrate,25; bonus bMaxSPrate,15; bonus bHealPower,30; skill "AL_HEAL",9,1; }
28416:28380:20788:22083,{ bonus bMaxHPrate,10; bonus bMaxSPrate,10; bonus2 bSkillAtk,"SU_CN_METEOR",100; }
28417:28380:20789:22084,{ bonus bMaxHPrate,15; bonus bMaxSPrate,15; bonus2 bSkillAtk,"SU_CN_METEOR",150; }
28418:28380:20790:22085,{ bonus bMaxHPrate,20; bonus bMaxSPrate,20; bonus2 bSkillAtk,"SU_CN_METEOR",200; }
28419:28382:20788:22083,{ bonus bMaxHPrate,20; bonus bMaxSPrate,3; bonus2 bSkillAtk,"SU_LUNATICCARROTBEAT",100; }
28420:28382:20789:22084,{ bonus bMaxHPrate,25; bonus bMaxSPrate,6; bonus2 bSkillAtk,"SU_LUNATICCARROTBEAT",150; }
28421:28382:20790:22085,{ bonus bMaxHPrate,30; bonus bMaxSPrate,9; bonus2 bSkillAtk,"SU_LUNATICCARROTBEAT",200; }

**Comment by Lemongrass3110** [comment]
Could someone of @rathena/rathena-script-db-developers have a look at this please?
If it was already done please close this issue.
Thanks!

**Comment by nanakiwurtz** [comment]
Done in a85a907d
