### ISSUE TITLE
Lux Anima Runestone

### ISSUE THREAD

**Issue by aleos89** [rathena/rathena#1110]
Hash: ba640cf
Mode: Both

The entire function of Lux Anima is all wrong.

The skill should function as:
- Only transfers the most recent rune buff.
- The caster loses the rune buff that is passed.
- There is a stack cap of 20 of Lux Anima Runestones.

The current setup:
- Transfers all active rune buffs.
- The caster is not losing the rune buff that is passed.
- There is no stack cap of 20 Lux Anima Runestones.

**Comment by admkakaroto** [comment]
Just to complement, taking I would report a problem if the rk is to buff Bragi poem, when using the rune animates it crash in map_server.

Note: only the server crash if it is with a group and other players are close, do not play the way players did in the war empeirum, but they overthrew a server 3 times until I found out.

**Comment by aleos89** [comment]
Can you explain how to cause the crash? I just used Poem of Bragi next to a character that used Lux Anima and it didn't crash.

**Comment by admkakaroto** [comment]
I honestly do not know reproduce fully, but the players shot down the map_server as follows:
During the war emperium, RK took Bragi, wore rune with all the members of the group next to it, and the server ready to fall.

**Comment by admkakaroto** [comment]
The player down the server is using the following runes before using Lux Anima:

Skin of Stone = Hagalas Runestone
Millenium Shield = Verkana Runestone

When he used the Lux Anima to pass the runes to their group members, the server crashed ... more than once, I opened the server, when he used the runes the server go down.
