### ISSUE TITLE
Offertorium not removing guillotine cross poisons and blind

### ISSUE THREAD

**Issue by Darkelfen** [rathena/rathena#1111]
In rA the skill is not removing GXs poisons and blind.

According to skill description, offertorium should end the following statuses:

Blind, Curse, Poison, Illusion, Chaos, Bleeding, Burning, Frezzing, Howling of Madragora, Every Guillotine Cross New Poison but Oblivion Curse.

Korean extract from divine-pride
> 치유가능한 상태이상 : 암흑, 저주, 독, 환각, 혼란, 출혈, 발화, 빙결, 만드라고라하울링, 길크신독(오블리비언 커즈 제외)
힐 효율 증가로 영향받는 스킬 : 힐, 생츄어리, 콜루세오 힐, 하이네스 힐 

This can be solved adding the missing statuses in skill.c Line 9247 at the time of checking (hash: ba640cf).

```
	case AB_OFFERTORIUM:{
		struct status_change *sc = status_get_sc(src);
		clif_skill_nodamage(src,bl,skill_id,skill_lv,sc_start(src,bl,type,100,skill_lv,skill_get_time(skill_id,skill_lv)));
		if( sc ) {
			int sc_toend[] = {SC_BLIND, SC_CURSE, SC_POISON, SC_HALLUCINATION, SC_CONFUSION, SC_BLEEDING, SC_BURNING, SC_FREEZING, SC_MANDRAGORA, SC_PARALYSE, SC_PYREXIA, SC_DEATHHURT, SC_LEECHESEND, SC_VENOMBLEED, SC_TOXIN, SC_MAGICMUSHROOM};
			for( i = 0; i < ARRAYLENGTH(sc_toend); i++) {
				status_change_end(bl, (sc_type)sc_toend[i], INVALID_TIMER);
				}
			}
		}
		break;
```

Even if I'm a couple of hashes behind, in ba640cf that part of the code is the same as in the one I'm at.

What I'm missing if info from officials, have anyone tested this in officials?

**Comment by aleos89** [comment]
Could use a cleanup in general. Seems useless that we create an array to remove all of the statuses when we can end them in `status_change_start()` overlap checks.

**Comment by Darkelfen** [comment]
Asked Ziu about that, removes every GX poison but Oblivion Curse.
