### ISSUE TITLE
Watery Evasion X Aqua Benedicta, Water Ball

### ISSUE THREAD

**Issue by cydh** [rathena/rathena#1119]
As I experienced in idRO, Priestess only can cast Aqua Benedicta (AL_HOLYWATER) once in same cell of Ninja's Watery Evasion (NJ_SUITON) area. The 2nd attempts (and so) will be failed. Except the Ninja recast the Watery Evasion.

[As iRO Wiki notes](http://irowiki.org/wiki/Watery_Evasion#Notes)
> This skill acts as shallow water for Water Ball and Aqua Benedicta skills, though any cells used for these skills will be removed after casting.

Maybe different on kRO?

**Comment by Playtester** [comment]
Just tested and can confirm. The cell is completely used up just like water ball.

**Comment by Playtester** [comment]
Further testing:
1. When using Aqua Benedicta on LP on water, then the skill will fail at castbegin. It won't even start casting. Waterball is the same except its search area is larger. No error message. This must happen before any units are deployed.
2. Using Aqua Benedicta on Water Evasion will only remove the Watery Evasion cell at castend. This happens even when standing on water.
3. Aqua Benedicta does NOT remove Deluge. You can cast it unlimited while standing on a Deluge cell without it being used up.
4. Aqua Benedicta does NOT fail at castend when standing on LP (Waterball does!). This is the proof that it's not a unit skill like Waterball even though it checks for LP at castbegin.

**Comment by cydh** [comment]
Well, it's fail on LP area. I didn't test it yet, I just realized that I don't have enough Mage classes on idRO.

**Comment by Playtester** [comment]
Yeah but you are correct it's not a unit skill, because it does NOT fail if you place LP during cast of Aqua Benedicta. So at castend, it doesn't need to place any unit to be successful.

The castbegin check for water simply includes checking for LP.
