### ISSUE TITLE
char login show error!!

### ISSUE THREAD

**Issue by Kemiro** [rathena/rathena#1123]
![qq 20160401042055](https://cloud.githubusercontent.com/assets/15216392/14189864/2de7522e-f7c2-11e5-8965-7a6adb31a861.png)
use 2015-10-29 client.

**Comment by anacondaqq** [comment]
Please, if you new at rathena isssue, provide extra important information:
* git hash
* mode
* client-date
* modifications
* packet obf. on / off

P.S. this issue is not new, check issues around, and you will find a solution how to fix it (https://github.com/rathena/rathena/issues/1103)
