### ISSUE TITLE
Doram: Power of Life

### ISSUE THREAD

**Issue by RagnarokNova** [rathena/rathena#1138]
There's a few issues with this status effect.
Flee is properly being raised by 20.
Issue number one is that Crit is being raised by 2, not 20. I remember a previous issue related to this and all that's missing is an extra 0 on the crit stat boost.
The second issue is Hit, which does not seem to be affected visually in the status window at all by the skill. Still looking into this one.

The ranged attack modifier also does not seem to be applying.

**Comment by SusanoSprites** [comment]
src/map/Status.C
Crit
Change this:
```
	base_status->cri = cap_value(base_status->cri * sd->critical_rate/100,SHRT_MIN,SHRT_MAX);
	if (pc_checkskill(sd, SU_POWEROFLIFE) > 0)
		base_status->cri += 20;
```
For this:
```
	base_status->cri = cap_value(base_status->cri * sd->critical_rate/100,SHRT_MIN,SHRT_MAX);
	if (pc_checkskill(sd, SU_POWEROFLIFE) > 0)
		base_status->cri += 200;
```
