### ISSUE TITLE
Silver Vine Root Twist

### ISSUE THREAD

**Issue by aleos89** [rathena/rathena#1139]
Hash: 8a3c672
Mode: Renewal

SV Root Twist is now removable by Earth Shaker ([source](http://forums.irowiki.org/showpost.php?p=1413073&postcount=2))
SV Root Twist can be placed more than once. **But for how many instances?** ([source](http://forums.irowiki.org/showpost.php?p=1413003&postcount=4))

**Comment by Darkelfen** [comment]
Asked Ziu, it's 3 times with limitations. Nevertheless, I dunno what those limitations could be but my best guess is that the skill behaviour is probably similar to geneticist's thorny trap.

**Comment by aleos89** [comment]
From what @RagnarokNova and I can tell is that the limitations Ziu is referring to are the cast time and cooldown.
