### ISSUE TITLE
Cannon Spear AoE

### ISSUE THREAD

**Issue by Paoly28** [rathena/rathena#1142]
2307,11,8,1,-1,0,1,5,1,no,0,0,11,weapon,0,0x0,	LG_CANNONSPEAR,Cannon Spear

is 11x1

is supposed to be

2307,11,8,1,-1,0,2,5,1,no,0,0,11,weapon,0,0x0,	LG_CANNONSPEAR,Cannon Spear

so it becomes 11x3

same with FAS having 13x1 aoe instead

**Comment by Playtester** [comment]
It's already correct.

0 splash is 1 width
1 splash is 3 width = correct
2 splash is 5 width

**Comment by Paoly28** [comment]
diagonally it doesn't follow the aoe and has very hard aoe , very different with my herc test server and output from iRO

**Comment by Paoly28** [comment]
here's the correct aoe right ? following the algorithm that was implemented 
diagonal radius is buggy
https://www.youtube.com/watch?v=FghdRrj7Pvs


![screenjealousyro030](https://cloud.githubusercontent.com/assets/8035101/15627311/99714860-2512-11e6-9837-a1d56495c542.jpg)

12,3,6,9 o'clock are correct only diagonal are wrong
