### ISSUE TITLE
getunitdata issue

### ISSUE THREAD

**Issue by Yuchinin** [rathena/rathena#1143]
getunitdata will always log a warning message below when the unit is dead

`[Warning]: buildin_getunitdata: Error in finding object with game id xx`

Is there any other method to get the unit alive or not?

Mode: Renewal
Hash: https://github.com/rathena/rathena/commit/397728c

**Comment by aleos89** [comment]
It's not really a bug. When a unit is freed we remove the unit's ID from the `id_db`. You can always just save the values of the unit in an array while it's alive. Not sure what the reason would be for you to get a unit's information when it's dead.

**Comment by Yuchinin** [comment]
I hope to keep track of the unit when it is still alive or not, if it is dead, clear it from the array.

**Comment by Yuchinin** [comment]
Let say I have a player variable GID_MOB = monster(...);

After some time, I will check whether the mob assign to GID_MOB is still alive or not for future use.

**Comment by aleos89** [comment]
Then I guess the best solution in this case, if you know the unit was a valid unit ID before, would be to have `getunitdata` return -1 when it can't find the unit in `id_db`.

**Comment by Yuchinin** [comment]
yeah, I hope at least the getunitdata can return an information of unit not found instead of just log a warning at the server.
