### ISSUE TITLE
WolfchevLaboratory Quest 4th Floor Restriction

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#1150]
There's an issue on the Warp Portal check.
_At the current state, a newly created character can enter Lighthalzen Dungeon lvl4 by simply entering the warp portal without doing the quest._

**npc/re//instances/WolfchevLaboratory.txt**
```
// Warp portal to the 4th Fl.
//============================================================
lhz_dun03,239,78,1	script	lhz_dun03_lhz_dun04	WARPNPC,1,1,{
	end;

OnTouch:
	if (lght_duk01 > 0 && lght_duk01 < 6) {
		mes "In order to investigate human experimentation, I had to go down whilst I didn't want to because of gruesome sound.";
		close2;
		if (lght_duk01 < 3) {
			warp "que_lhz", 245, 56;
		} else if (lght_duk01 == 3) {
			warp "que_lhz", 96, 136;
		} else {
			warp "que_lhz", 148, 215;
		}
	} else {
		if (lhz_boss < 31) {
			mes "- Whistling sound -";
			mes "From below, there comes a gruesome sound mingling with the wind.";
			close2;
		}
		warp "lhz_dun04", 245, 56;
	}
	end;
}
```

**Comment by Everade** [comment]
Shouldn't there be an end; after close2?

```
        if (lhz_boss < 31) {
            mes "- Whistling sound -";
            mes "From below, there comes a gruesome sound mingling with the wind.";
            close2;
            end;
        }
```

**Comment by Everade** [comment]
I mean close instead of close2
Sry was about to go to bed.

**Comment by Atemo** [comment]
Maybe they didn't expect that but it's working officially like that.

**Comment by Everade** [comment]
Maybe they didn't expect that xD
Seriously?

It IS actually bugged.
So priority 1 is to stay official even if it's an actual bug?
This is the dumbest shit i've ever heard.

Letme tell you how it is:
There's a freaking **2 days long quest**, and you're telling me, the quest is nonsense, you know why?
Because it's an official bug, and we need to implement that.


That's the main reason why i stopped reporting bugs on eAthena, and now you guys are trying to continue this nonsense.

**Comment by Playtester** [comment]
rAthena has the same "only official kRO" philosophy as eAthena. Removing official bugs is something left to server owners. You could also release a quest package with quest fixes like that on the forums.

**Comment by Atemo** [comment]
> "The quest is nonsense, because it's an official bug, and we need to implement official bugs. You know... because we keep things 100% official"

That exactly what I wanted to say thanks you. Seriously I'm glad you made a report but no need to cry for something like that.

**Comment by Everade** [comment]
Hilarious

"Up to server owners" Ok, if you wish so. But...
**As if everyone is aware of your extra super special hidden easter egg bugs.**

Your policy deserves a _medal of honor_.

I think the best idea is i learn korean, report it directly to gravity so 3 years later... it actually gets fixed.
Yes that's a plan.


Oh wait, i forgot the cry initiation
/cry
