### ISSUE TITLE
Summoner eden group quest

### ISSUE THREAD

**Issue by MysticFurur0RE** [rathena/rathena#1151]
Summoner no weapons are obtained when you complete the quest

**Comment by feltenc** [comment]
I have tested the pull request https://github.com/rathena/rathena/pull/1152 and works fine here, i think it can be closed.

**Comment by Jeybla** [comment]
Fixed in 08338e0a64e863d1e579f145b4dc3f99ac66034f .

Thanks @MysticFurur0RE and @feltenc !
