### ISSUE TITLE
Some sage skill provoke a error : pc_checkskill: Invalid skill id 0

### ISSUE THREAD

**Issue by anacondaqq** [rathena/rathena#1154]
Okay, this issue related to all revisions, maybe since last 2 years (i'm already noticed that bug time to time showed at map-server log).

The problem (map-server log output)
> [Error]: pc_checkskill: Invalid skill id 0 (char_id=150001).

I did search the same errors to get all char_id's and find the similar things on each account.
I found that error triggered ONLY at sage-based classes: Sage / Professor.

Learned skills: 
![image](https://cloud.githubusercontent.com/assets/9905636/14402866/33c2f98a-fe4a-11e5-8aaf-61e73a38b005.png)
![image](https://cloud.githubusercontent.com/assets/9905636/14402884/8b5a4ee6-fe4a-11e5-8f64-027431ccd205.png)

#### another guy, who time to time trigger this error:
![image](https://cloud.githubusercontent.com/assets/9905636/14402871/505683dc-fe4a-11e5-84df-9867f0ccb769.png)
![image](https://cloud.githubusercontent.com/assets/9905636/14402887/974d81aa-fe4a-11e5-9db3-2a71c116b843.png)

Possible scenarios of the error:
1. Freecast skill usage
2. monter elemental change
3. weapon enchant. (usually such profs used only for weapon enchant).

I will add extra information, if i will have it. 

## Technical Details:
mode: pre-re
client-date: 2012-04-10
packet_ver: 30
packt obf.: disabled
hash: 5e58149bbc3c616f51349a0a8d7c6f1719491ea4 (but this problem exist maybe for 1 year)

**Comment by Playtester** [comment]
If you know a way to create the bug often you could put a breakpoint where it brings the error message then run map server on debug mode and if it stops at the breakpoint check the call stack.

**Comment by stealth62** [comment]
I reproduce this error by using auto spell skill and i got in map server pc_checkskill: Invalid skill id 0 (char_id=13). this error only occur if you click cancel butto

**Comment by Playtester** [comment]
Nice find! Thanks!

**Comment by Playtester** [comment]
Actually, the problem is even bigger if you click the "Ok" button without selecting anything. Then you access some random memory to it returns a random skill id...

**Comment by anacondaqq** [comment]
@Playtester yep, skill id 0 triggered time to time, but not only skill id 0, sometimes it's can be 65535 (or something like that), sometimes another different random skill.

**Comment by stealth62** [comment]
Thank you sir @Playtester

**Comment by secretdataz** [comment]
@Playtester 
> access some random memory to it returns a random skill id...
That's some intern coding level by Gravity right there.
