### ISSUE TITLE
Arrow equip

### ISSUE THREAD

**Issue by Atemo** [rathena/rathena#1155]
Hash 2305a6610103b1b475017bef516b53268cdd825e
On official renewal you can't equip arrow without bow equipped (so on rArthena you can. Assassin class can't equip them ; skill fail for ranger if no bow equipped).
Also on official if you unequip the bow the arrow is automatically unequipped

**Comment by cydh** [comment]
Depends on which official server u refers to :P

But maybe, this behavior was added in the MT when Assassin cannot equip an arrow any longer.

**Comment by Atemo** [comment]
lol you're right, I refer to iro we need to test on kro

**Comment by RagnarokNova** [comment]
Confirmed on kRO. Unequipping a bow removes your arrows. It's really uncomfortable.

**Comment by secretdataz** [comment]
This should be made optional with official behavior as default imo.

**Comment by Playtester** [comment]
If we made an option for that please make also one for ammo of gunslingers. There the official behavior is that you can't even equip weapons when the ammo doesn't match, very annoying. I'd rather have that auto-unequip that arrows have lol.

**Comment by MrAntares** [comment]
What happens on bow switch? Will it de-equip the arrows?

**Comment by Atemo** [comment]
No it doesn't unequip the arrow when you switch the bow.

**Comment by stealth62** [comment]
this will break pvp mechanics when you switch bow and arrow automatically unequip i remember iro revert this changes a lot of player complain switching bow will unequip arrow.

**Comment by Playtester** [comment]
Even more reason to make it optional.

**Comment by MrAntares** [comment]
And default off ;)

**Comment by Playtester** [comment]
Default is always kRO. =3

**Comment by joelolopez** [comment]
i cant equip new type of guns coz the bullets is still equipped, such a hassle

**Comment by Playtester** [comment]
Yeah that's official behavior though. I'd like to see it configurable. Should just automatically unequip the bullets and arrows when no suitable weapon equipped.

**Comment by joelolopez** [comment]
oh i see , lets keep it like that ahahha i love official behaviors , always keep messing ur game ahaha xo

**Comment by MrAntares** [comment]
Much work for a feature that will rarely be used <3

**Comment by benching** [comment]
On assasin , baby and parent jobs,
is venom knife(1771) can be equipped even without weapon?
