### ISSUE TITLE
[Wizard] Heaven Drive

### ISSUE THREAD

**Issue by exneval** [rathena/rathena#1156]
Hash 6dfdc45
In UNT_DUMMYSKILL, case WZ_HEAVENDRIVE break the skill_attack that defined in default case, so there's no damage done with the skill, we need to move the Heaven Drive to the default case using if statement
[report in rA forum](https://rathena.org/board/topic/105437-heaven-drive-no-damage)

**Comment by Playtester** [comment]
```c
				case WZ_HEAVENDRIVE:
					status_change_end(bl, SC_SV_ROOTTWIST, INVALID_TIMER);
					break;
```
Err... lol.

I'm surprised it actually works for anyone.

This shouldn't be in that function at all. It belongs to skill_additional_effect unless it should override all global battle checks. Like, should this happen even though the attack misses because of 100% earth resist? Or target is completely skill immune?

**Comment by exneval** [comment]
i guess it shouldn't happen if the attack missed

**Comment by Playtester** [comment]
I think so too, so better remove that code and instead put it into skill_additional_effect. Then it goes through skill_attack, does damage and then removes status change.

**Comment by exneval** [comment]
Great :+1:

**Comment by stevenahoy** [comment]
i have this bug too

**Comment by aleos89** [comment]
Thanks for the report! I'll fix this up. :)

**Comment by stevenahoy** [comment]
tq aleos89 , exneval and playtester!!
i will share it in my post on rathena for other people

**Comment by stevenahoy** [comment]
@aleos89 sorry sir i got report for diamond dust not working too , can you fixed that?

Thanks @aleos89 

https://rathena.org/board/topic/105437-heaven-drive-no-damage/ ( Dissidia  [ Member rAthena ] )
