### ISSUE TITLE
Diamond Dust Not Working

### ISSUE THREAD

**Issue by stevenahoy** [rathena/rathena#1158]
Dear All,

i got some report from my post in rAthena website , Diamont Dust Not Working too , can someone fixed that?

thanks 

[rA Forums] (https://rathena.org/board/topic/105437-heaven-drive-no-damage/)

**Comment by stealth62** [comment]
Hi @stevenahoy a little info would be nice

**Comment by stevenahoy** [comment]
hi @stealth62 oke , diamond dust is not working same like heaven drive , diamond dust doesn't give damage to all monsters too , sorry for my bad english i hope you can help me , thanks

you can reply on my post in rAthena if i not interrupt you , [rA Forums Topic](https://rathena.org/board/topic/105437-heaven-drive-no-damage/) ( Dissidia [ Members ] )


verry big thanks @stealth62

**Comment by aleos89** [comment]
I just tested and was able to damage monsters. What monster are you fighting against?

**Comment by stevenahoy** [comment]
really?
hmm oke @aleos89 i will check my source again ,

thanks for helping me :+1:

**Comment by anjotabios** [comment]
same as mine. cant hit the monsters. need many diamond dust use to hit.. its not 100% to hit. latest GIT, pre-renewal mode

**Comment by Playtester** [comment]
```2447,9,6,2,1,0,0,5,-5,yes,0,0,0,magic,0,0x0,	SO_DIAMONDDUST,Diamond Dust```
Strange, because it's defined as magic so it should hit regardless of flee. Maybe damage was reduced to 0? It also can't hit plants.

**Comment by aleos89** [comment]
Damage reduction versus plants for this skill is from 0bd337d. Confirmed on Aegis. Plants do not receive damage from Diamond Dust.
