### ISSUE TITLE
Leap towards a wall

### ISSUE THREAD

**Issue by Playtester** [rathena/rathena#1159]
On official servers, Leap checks for a wall not only on the target cell, but also on the cell behind the target cell. If one of those two cells have a wall, leap will fail.

**Comment by reigneil** [comment]
which skills are you referring to? taekwon, ninja, rebellion or doram?
leap of taekwon i think is different from others. correct me if im wrong

**Comment by reigneil** [comment]
which skills are you referring to? taekwon, ninja, rebellion or doram?
leap of taekwon i think is different from others. correct me if im wrong

**Comment by Playtester** [comment]
Taekwon/Linker Leap. Didn't know there were other skills with that name.

**Comment by Rolfxx** [comment]
@Lemongrass3110 
Lope skill (from summoner) should be checking for the same right?

this is a question, idk if this is intended

**Comment by aleos89** [comment]
I don't believe so. Leap is unique compared to the other "jumping" skills. I can give it a test just to confirm.

**Comment by Lemongrass3110** [comment]
We will go with Taekwon only for now. If you find another skill that needs this, just open a new issue.
