### ISSUE TITLE
Really Really Weird Item ID Bug

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#1160]
```
OnTimer4000:
	if (.inUse) {
		set .curLockT, .curLockT + 1;
		if (.curLockT > .maxLock) set .inUse, 0;
	}
	else {
		getmapxy .map$,.x,.y,1;
		set .curX, callsub(NPCWalk,.minX, .maxX,.minD,.maxD,.x);
		set .curY, callsub(NPCWalk,.minY, .maxY,.minD,.maxD,.y);
		npcwalkto .curX, .curY;

		set .chance, rand(1,500);
		if ( (.chance >= 1) && (.chance <= 10) ) {
		makeitem 61607,1,.map$,.curX,.curY;
		}
			
	}
	stopnpctimer;
	initnpctimer;
	end;

```

I have a quest where a Walking NPC drops Cat Footprints (item id 61607) every few minutes.

I was wondering now for several weeks, what's wrong with the map server telling me that the item id 3929 does not exist!
### So it's actually dropping ID 3929 instead of 61607!!!!

It's actually caused by this part of the script!
What the hell is wrong?
`		makeitem 61607,1,.map$,.curX,.curY;`

The item ID should still be in the allowed range, and i'm able to create the item id 61607 without any issues.
However this npc is still dropping unknown items (item id 3929)

**Comment by Playtester** [comment]
Number overflow. That command only works with numbers up to 32767.
