### ISSUE TITLE
 Bonus Source nonexistent for items Doram

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#1161]
The problem is that it has a script that increases the attack / M Attack % based on the equipment.
The atkrate we have is based on the general attack.
an implementation based on weapon attack would be possible?

**Problem:**
			"-------------------------",
			"Refine level +7: increases base weapon's ATK and MATK by 40%.",
			"For every refine level higher than +7: increases base weapon's ATK and MATK by 20%.",
			"(Limited to +10 refine level)",
			"-------------------------",

**kRO description:**
[1691] = {
		unidentifiedDisplayName = "One-Handed Staff",
		unidentifiedResourceName = "·Ôµå",
		unidentifiedDescriptionName = {
			"Unknown Item, can be identified by using a ^6666CCMagnifier^000000."
		},
		identifiedDisplayName = "Strange God Foxtail Wand",
		identifiedResourceName = "ÀáÀÚ¸®¾ÉÀº°­¾ÆÁöÇ®",
		identifiedDescriptionName = {
			"This dragonfly and the foxtail has completly become one.",
			"-------------------------",
			"MATK +240",
			"MaxSP +100",
			"For every 3 refine level: MATK +2%, MaxSP +1%.",
			"-------------------------",
			"Refine level +7: increases base weapon's ATK and MATK by 40%.",
			"For every refine level higher than +7: increases base weapon's ATK and MATK by 20%.",
			"(Limited to +10 refine level)",
			"-------------------------",
			"Class:^6666CC One-Handed Staff^000000",
			"Attack:^CC0000 100^000000",
			"Weight:^009900 50^000000",
			"Weapon Level:^009900 3^000000",
			"Level Requirement:^009900 100^000000",
			"Jobs:^6666CC Doram race^000000"
		},
		slotCount = 2,
		ClassNum = 100
	},

**Item script:**

`1691,Strange_God_Foxtail_Wand,Strange God Foxtail Wand,5,20,,300,100:240,,1,2,0x80000000,7,2,2,3,100,1,10,{.@r = getrefine(); bonus bMatkRate,2*(.@r/3); bonus bMaxSPrate,1*(.@r/3); bonus bMaxSP,100; if(.@r >= 7){xxxxx} },{},{}`

**Comment by nanakiwurtz** [comment]
Ah I guess you're right, Doram's items are increasing the M/ATK from the value of item's M/ATK, not increasing from the char's
