### ISSUE TITLE
WFIFOSET issue. everyday DC.

### ISSUE THREAD

**Issue by anjotabios** [rathena/rathena#1163]
![bug](https://cloud.githubusercontent.com/assets/18420396/14460034/ddd5cdbc-00ed-11e6-9b83-3772da5ddae4.png)

please help. my player always DC. this happen after i update my server into the latest GIT. tnx

Pre-Renewal

Latest GIT (Zip download)

Client date: 20130807

**Comment by anjotabios** [comment]
Latest GIT (Zip download)

Client date: 20130807

**Comment by Playtester** [comment]
Maybe wrong PACKETVER set?

Otherwise I'd need a way to reproduce it. I use the 20130807 client too and don't get that error.

Relevant packets are:
```/// 02e1 <src ID>.L <dst ID>.L <server tick>.L <src speed>.L <dst speed>.L <damage>.L <div>.W <type>.B <damage2>.L (ZC_NOTIFY_ACT2)```
and
```/// 009c <id>.L <head dir>.W <dir>.B```

Strange, the latter one was never changed?

**Comment by anjotabios** [comment]
im using:

packet_db_ver: 45
packet_keys_use: default

and I disable packet key. in compile and client..

**Comment by stevenahoy** [comment]
[rAthena Error Wfifoser maximum write buffer](https://rathena.org/board/topic/103722-rathena-error-wfifoset-maximum-write-buffer/)

[rAthena Wfifoset dropped too large client packet](https://rathena.org/board/topic/59014-wfifoset-dropped-too-large-client-packet/)

maybe that link can help you :+1:

**Comment by anjotabios** [comment]
thanks steven. but still not fix. anyway im using skill no delay on my server.. may its a problem?

**Comment by stevenahoy** [comment]
maybe , you can try to disable it 

good luck :)

**Comment by anjotabios** [comment]
and I think it's only trigger in RK.. all RK in my server is the reason of  map server down

**Comment by stevenahoy** [comment]
maybe you can try to ask with chat [ rAthena Discord Chat #support ](https://discordapp.com/channels/96459614895226880/141470902016671744)

**Comment by Playtester** [comment]
If you give me a reliable way to reproduce this error I can look into it.

**Comment by anjotabios** [comment]
here is my map src sir:
http://www.mediafire.com/download/21hkqw3pddcwp33/map.rar

all edit is with // anjo comment.

**Comment by anjotabios** [comment]
and change the cooldown of all skill to 0. all skills are no cooldown..

**Comment by anjotabios** [comment]
I found the problem. When other class using inspiration skill it will crash the map by a chance. most of RK using inspiration in my server. and we got DC. hoping this help to solve the packet issue. thanks

**Comment by Playtester** [comment]
The server crashes completely or just print error messages?

**Comment by anjotabios** [comment]
Hi, it's Rune Knight, I have an item with Inspiration Skill, print an error + map server down, I t show offline in website.

**Comment by Playtester** [comment]
I see, so what's the item script?

**Comment by anjotabios** [comment]
> /*skill "LG_INSPIRATION",5;*/ bonus bMaxHPrate,20; bonus bMaxHPrate,readparam(bVit)/5; bonus2 bAddClass,Class_All,10; bonus2 bSubRace,RC_DemiHuman,10; bonus2 bSubRace,RC_Player,10; if(countitem(28970)) { bonus bDefRate,-50; bonus bDef2Rate,-50; }


I temporary disable it and the skill inspiration, since yesterday no map crash or error happen.

**Comment by Playtester** [comment]
Put the script into code tags instead of quote tags please, because oherwise it removes all the special characters.

**Comment by majimboo** [comment]
This most likely is a script problem.

**Comment by aleos89** [comment]
I use this client daily when testing and I have none of the issues you described above.
