### ISSUE TITLE
Royal Guard : Shield Press delayed hit 

### ISSUE THREAD

**Issue by Paoly28** [rathena/rathena#1165]
Shield press is supposed to have a 1 second delay before the actual damage, currently it deals damage instantly as you cast it.

**Comment by aleos89** [comment]
There might be some other things that need to be updated for this skill as well. The stun duration seems to be off for it.

**Comment by Playtester** [comment]
I have already fixed the stun duration a while ago: https://github.com/rathena/rathena/commit/80e026433f61aaa43b6ef061537c2ef34443662a
