### ISSUE TITLE
delete char problem

### ISSUE THREAD

**Issue by joelolopez** [rathena/rathena#1167]
using rathena 17017 and 2015-11-04aRagexe.
how to produce
-delete a character
-wait for the character deletion date 
-click the delete button
-msg will pop up and nothing will happen
-you can login the character eventhough the character is sitting in character selection screen 
-after loggin in, logout
-after logout.. you can finally delete the character xp

**Comment by Lemongrass3110** [comment]
SVN revision 17017 is GIT hash 17685a3

This one might be related to #1133(also your bug report) and 7a0b628. Could you please try to change the line from that commit to this:
```
#if PACKETVER > 20130000 && PACKETVER < 20141016 || PACKETVER >= 20150826 && PACKETVER < 20151001 || PACKETVER >= 20151104
```

Thank you.

**Comment by Darkelfen** [comment]
I was also having problems while trying to delete chars, I've changed the line (I'm at 9a3afff) and it worked.

**Comment by Playtester** [comment]
What did you change the line to so it worked? Removed the PACKETVER >= 20151104 ?

**Comment by Darkelfen** [comment]
Replaced L1807 at char.c with the code @Lemongrass3110 provided.

**Comment by Playtester** [comment]
Ah okay, misread that.

**Comment by Darkelfen** [comment]
I will edit it, that parenthesis obscured the meaning.

**Comment by M45T3Ryu** [comment]
this happens too with 2015 10 29 with latest revision
