### ISSUE TITLE
Failed to use @loadnpc on same script multiple time.

### ISSUE THREAD

**Issue by emistry** [rathena/rathena#117]
As title mentioned, the script failed to load when using @loadnpc to load same script.
Example : 
@loadnpc npc/custom.txt

then I unload the script/npc using @unloadnpc or @unloadnpcfile

when I try load load back the same file npc/custom.txt using @loadnpc 
it doesnt work and tell me that script couldn't be loaded.
I am sure that there are no mistake or type when I try to load it.

However, it will still work when I load it in this way : 
@loadnpc npc//custom.txt
@loadnpc npc///custom.txt
this also apply to all directory and subdirectory depend on your script.  
Multiple "/" will be treat as single "/"
and yes, each of this command only work once, after @unloadnpc again, then wont be able to load it back using the same "path/directory".

The last update of revision I am using 16 November

**Comment by cydh** [comment]
this #203 is more alive xD
