### ISSUE TITLE
WARNING Shows in map-console (Kettle Hat and Ring of Resonance + Ring of Flame Lord)

### ISSUE THREAD

**Issue by Keysito** [rathena/rathena#1173]
Hello, i just notice at my map-console there many WARNING's shows in console which is it triggers with this 3 items which Kettle Hat, Ring of Flame Lord and Ring of Resonance.

`http://i.imgur.com/ft75MKs.jpg`

For some reasons, maybe it was trigger since it uses a lot of skills.

Can anyone confirm me this matter?

**Comment by secretdataz** [comment]
You can raise `MAX_PC_BONUS` limit in `map/pc.h` to avoid this issue.

**Comment by Keysito** [comment]
Thank you :D

**Comment by Everade** [comment]
Raising max_pc_bonus is not just "_avoiding_" the issue.
It will simply raise the max amount of auto spells allowed coming from one source.
