### ISSUE TITLE
Pet Skill Bonuses broken

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#1178]
### Unloyal Pet effects
`pet_script`
is- entirely broken / not working / taking no effect

Only the bonuses when the pet reached loyal status are working
`loyal_script`

Tested on Renewal
rAthena SVN rev 16273

**Comment by Lemongrass3110** [comment]
Could this be related to #849?

**Comment by Everade** [comment]
Yes **very likely,** as the mentioned
`petloot 10;`

is written in the
`pet_script`
Which is currently not taking any effect.

**Comment by Everade** [comment]
By the way
**pet_status_support: yes**

**My setting is/was already set to yes,** so also your temporary solution does not fix the issue.

**Comment by Darkelfen** [comment]
Weird, bonuses are working on mine.

I'm at https://github.com/rathena/rathena/commit/7264099fb9b7ec50bac438e57ddd60906c782fc3 .

I've created a poring to check whether it loots or not and he was looting as usual.

**Comment by Everade** [comment]
I haven't tested the looting, only the pet bonuses as stats for example. (Picky, Lunatic and some more)

**Comment by aleos89** [comment]
This is working as normal. You need to adjust your battle config to properly support this like @Lemongrass3110 stated. You'll need to adjust `pet_status_support` to yes. For the attack type skills, just as the config says:
```
// When the master attacks a monster, whether or not the pet will also attack. (Note 1)
pet_attack_support: yes

// When the master receives damage from the monster, whether or not the pet attacks back. (Note 1)
pet_damage_support: yes
```
Need to be adjusted to yes as well. Also make sure you have the pet equip on if you have that config set to yes as well.

Another note, you need to adjust this config for their support skills to be used:
```
// Minimum intimacy necessary for a pet to support their master. Default is 900 
// (intimacy goes from 0 to 1000). At this minimum, support rate is 50% of pet's normal value.
// At max (1000) support rate is 150%.
pet_support_min_friendly: 900
```

**Comment by Everade** [comment]
Uhm....

My settings unchanged since.... 2008 or so ?!?!?!

```
//pet.conf
pet_catch_rate: 60
pet_friendly_rate: 200
pet_attack_support: yes
pet_damage_support: yes
pet_support_min_friendly: 700
pet_equip_min_friendly: 700
pet_status_support: yes
```
