### ISSUE TITLE
Bug at char deletion - Ragexe 2015-10-29

### ISSUE THREAD

**Issue by Weskercorp** [rathena/rathena#1179]
When I tried to delete the character, it shows the delete time correctly.
But when I relog, the date shows 12/31 22:0:0 on every character for deletion.

Screenshot of the character's [https://s9.postimg.org/6ersxmtin/char+deletion+20151029.png](url)

I tried to delete **a different character** after fix with the commit a41ba12->[https://github.com/rathena/rathena/commit/a41ba12cf2b60bfb3d86f10934bb568da91b2f9a](url)

The same thing persist. I wait the correct time (Wich was 24 hours). And it didn't delete. It ask to Log out and when I log out, the character still there. I changed the time of deletion, and now I can delete correctly.

Thank you

**Comment by Lemongrass3110** [comment]
Sorry we do not support 2015-10-29 anymore.
That client is most obviously broken.
Consider upgrading to 2015-11-04.

Thanks for understanding.
