### ISSUE TITLE
Skill Highness Heal cooldown won't reduce by using CureLv1 enchant rune

### ISSUE THREAD

**Issue by hazimjauhari90** [rathena/rathena#1182]
hi dev. i try to use mora affection set on my arch bishop. i equip light of cure accessory, enchanted with curelvl1 enchant rune. suppose to be highness heal skill no longer in cooldown as curelv1 rune description decreases cooldown time for highness heal by 3 seconds. however the cooldown time for highness heal remain the same without reduce in time.

seems to be this item bonus effect script only having problem reduces cooldown on rune only. the equipments with cooldown bonus (example giant lance, item id 1490) do show changes in cooldown. perhaps some missing function.?

![screenrathena000](https://cloud.githubusercontent.com/assets/16514357/14584067/4ca36b5a-0468-11e6-80e9-6663082478bb.jpg)
![screenrathena001](https://cloud.githubusercontent.com/assets/16514357/14584068/4ca94fca-0468-11e6-81d2-d7e23a4e5c3c.jpg)

**Comment by secretdataz** [comment]
I can't reproduce this. Can you try reproduce this issue on clean rAthena with only the item in question equipped/unequipped?

My result and settings:
Git hash: 33efbd0869e564f7a796314727045ef880b2afd6
Mode: Renewal
[Before equipping item with 4803 slotted](https://gfycat.com/GraciousGreatBustard)
[After](https://gfycat.com/PowerfulSmoothAlpinegoat)

**Comment by hazimjauhari90** [comment]
i try on clean rAthena.. somehow i got error in compiling.. i never change anything yet in itemdb.c

![rathena error](https://cloud.githubusercontent.com/assets/16514357/14585735/cc80fd9e-04b1-11e6-905f-6e2fac58a40f.png)

**Comment by hazimjauhari90** [comment]
i just go check into skill_cast_db.txt. the cooldown time for highness heal is 3 seconds. suppose to be that when equip any accesory with CureLv1 enchant rune, it should be this skill has no cooldown as its effect reduce the cooldown time of highness heal by 3 seconds. below is the detail of the skill cast of highness heal skill.

//-- AB_HIGHNESSHEAL
2051,1000,1000,0,0,0,3000,-1

meanwhile, based of the video you uploaded, after equipping item with 4803 slotted, there's still got 1 seconds cooldown.. are the item bonus skill cooldown don't work properly on enchant rune.?

**Comment by secretdataz** [comment]
@hazimjauhari90 That's working as intended.
That 1 second timer is "AfterCastActDelay" which prevent you from casting any skills (see how Heal also has the timer in both videos) while "Cool down" prevent you from casting a specific skill.

**Comment by hazimjauhari90** [comment]
okokok.. understood already.. i got it.. i guess, i could say sorry for my mistakes. xD.
