### ISSUE TITLE
[BUG] MvP Drops

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#1187]
Whatever MvP there is a chance of receiving different items to eliminate . ( Example: http://www.divine-pride.net/database/monster/2249/pyuriel )
- Note that this example there is 3 items with 50% Drop award MvP . The problem that occurs today is that if you give @mobinfo 2249 will see only one drop and not 3 .
This practice occurs when the MvP is dead. Dropped only one type of item. Do not drop any of the other three types . This occurs problems with whatever MvP .

**Comment by Playtester** [comment]
Did you by any chance put a rate higher than 1x on MVP drops?

drops.conf
```// The rate adjustment for the MVP items that the MVP gets directly in their inventory
// Mode: 0 - official order, 1 - random order, 2 - all items
item_rate_mvp: 100
item_drop_mvp_min: 1
item_drop_mvp_max: 10000
item_drop_mvp_mode: 0```

**Comment by Badarosk0** [comment]
In fact , my file was missing this line , on the issue that I ended up deleting . I added :
item_drop_mvp_mode: 1
Solved the problem. Sorry , thank you.
