### ISSUE TITLE
Character Deletion Not Working After Relogging

### ISSUE THREAD

**Issue by niknokseyer** [rathena/rathena#1189]
![image](https://cloud.githubusercontent.com/assets/2403463/14629025/12957038-05b8-11e6-8a27-5323abb0b74c.png)

Client Version: **20150916**.

char_athena.conf is set to **30** seconds.
Screen will display the correct time.. but when tried logging in and out deletion time will be set to 12/31 with a weird time.

_note: Char deletion is possible if you wait for 30 seconds on your screen and click the char deletion again._

**Comment by spinzaku** [comment]
same problem here.. Client Version: 20150916

**Comment by Jeybla** [comment]
I can confirm this, too.

**Comment by aleos89** [comment]
I just tested deleting a character with 2015-10-29 and it deleted just fine. I waited on screen for 30 seconds and I logged in another character and out, and the deletion worked normally and displayed normally.

I reverted the two commits above and tested with 2015-10-29 again. I clicked the delete button and then proceeded to login on another character until the delete time passed. I logged off and went over to delete the character and was presented with the issue @niknokseyer said above (having a date of 12/31 - 19:0:0). If I wait at the character screen for the delete time to pass it also showed the same error.

**Comment by Jeybla** [comment]
Just retested it and I'm not quite sure why my test results differs completely from yours. Maybe some more informations about my settings will help to make this clear:
Client: 2015-10-29
mmo.h PACKETVER: 20151029
pincode_enabled: no
char_del_option: tested both, no difference
char_del_delay: 30
packet_db_ver: 54

On current master I get two issues:
- After pressing "delete" and logging in and out the time is shown wrong (1/1 - 1:0:0)
- If I try to delete a character which delete time hasn't passed a pop shows with the message "Now logging out". Screen: 
![timenotpassed](https://cloud.githubusercontent.com/assets/6203894/14894796/bac8acba-0d75-11e6-93f8-1caf0854f8a2.png)

If the time has passed it's possible to delete the character:
![timepassed](https://cloud.githubusercontent.com/assets/6203894/14894850/f6c014ec-0d75-11e6-98b3-ff9e95d05f61.png)

With the above two commits reverted (branch [fix_1189](https://github.com/Jeybla/rathena/tree/fix_1189)) I doesn't encounter any of these bugs. The time is shown correctly (even with the colors blue & red). And the deletion button is hidden if the time hasn't passed already.

**Comment by cydh** [comment]
hmm, so who added this packet, please review the char deletion packet (sent/received) also each char info detail. :D @rathena/rathena-core-developers

**Comment by cydh** [comment]
OK, got it. we just need to confirm which clients that send `delete_time` as **full delete_time** or **delete_time - current_time** (time remain).

The codes are originally as
```c++
#if PACKETVER >= 20100803
	WBUFL(buf,124) = (p->delete_date?TOL(p->delete_date-time(NULL)):0);
	offset += 4;
#endif
```
then changed in 7a9aa7fbcfe40080c1b743137fc68aebb596e632 (a type the followed up by 27d270d641a78d4222a0d22035acf8fb2d617aac)
```c++
#if PACKETVER >= 20100803
#if PACKETVER > 201300000
	WBUFL(buf,124) = (p->delete_date?TOL(p->delete_date-time(NULL)):0);
#else
	WBUFL(buf,124) = TOL(p->delete_date);
#endif
	offset += 4;
#endif
```

Then it's constantly changed for `PACKETVER` check in 0042fe5bb64127f72e04001f87be780ebbfbef69, 118fa28ae9ac832e89968ce214c27b17d780027d, 7a0b628acbbf52c35831f60ed2943e6eb2d07c4d, a41ba12cf2b60bfb3d86f10934bb568da91b2f9a

If based on very first codes, I think for another 'new' clients should use the `WBUFL(buf,124) = TOL(p->delete_date);` (so the changes on 7a9aa7fbcfe40080c1b743137fc68aebb596e632 was reversed)

Well, need to check other clients, I can confirm for now client that use **full delete_time**
* [ ] ~~2012-04-10~~
* [ ] ~~2012-04-18a~~
* [ ] ~~2012-06-18~~
* [ ] ~~2012-07-02aRagexeRE~~
* [ ] 2013-03-20Ragexe
* [ ] 2013-05-15aRagexe
* [ ] 2013-05-22Ragexe
* [ ] 2013-05-29Ragexe
* [ ] 2013-06-05Ragexe
* [ ] 2013-06-12Ragexe
* [ ] 2013-06-18Ragexe
* [ ] 2013-06-26Ragexe
* [ ] 2013-07-03Ragexe
* [ ] 2013-07-10Ragexe
* [ ] 2013-07-17Ragexe
* [x] **2013-08-07Ragexe**
* [ ] **2013-12-23Ragexe**
* [ ] **2014-10-16Ragexe**
* [ ] **2014-10-22bRagexe**
* [ ] **2015-05-13aRagexe**
* [ ] **2015-09-16Ragexe**
* [ ] **2015-10-01bRagexeRE**
* [ ] **2015-11-04aRagexe**

**Comment by aleos89** [comment]
I did some more tests as well with 2015-10-29aRagexe. The client I had before was the RE version which is why I couldn't reproduce the issue. Testing with the non-RE version I was able to reproduce the issue.

**Comment by M45T3Ryu** [comment]
An easier way to reproduce is just loggin out when the deletion time is running then when you enter you'll have a bugged character wich you cant delete, and the SQL sets "delete_time" in char table to "1463223513" when the char is bugged, my way to bypass this is set that value to 0, and the character will be standing again then I can delete it, but I need to wait untill it turns blue to delete it without loggin out or in

**Comment by cydh** [comment]
Damnit!!
* I tested all clients that are supported by rAthena, **got no issue** except what I mentioned above (if you have more than 1 `<connection></connection>` and the way you *log out* is press cancel then try to login back, it'll fail you because client uses the first `<connection></connection>` block)
* No one respond what I said
* Why the hell you guys test using non supported client in rAthena? 2015-10-29aRagexe for 54? No joke please!

**Comment by Jeybla** [comment]
Sry, can't proofe this currently. Or do you know any GRF-Tool which works well on linux?

All I can say, is: I just ran into this issue (yes with a client with more than one <connection> and with an unsupported client) solved it and tried to share my results. Even for a non supported client ;>

**Comment by spinzaku** [comment]
Well i am running on a live server and using 2015-11-04a (which is supported by rAthena) and have same issues as @Jeybla here: https://github.com/rathena/rathena/issues/1189#issuecomment-215504373 

my clientsideinfo is `<version>55</version>  <langtype>1</langtype>`
`packetdb is also 55`
