### ISSUE TITLE
Flash Combo not reflecting Official Behaviour

### ISSUE THREAD

**Issue by Inzanity99** [rathena/rathena#119]
Right now Flash combo gives you a global delay. During this Delay you cannot use any Items. I also dont seem to get any ATK bonus. Flash Combo consumes your HP/SP from Tiger cannon. Its very slow in its execution.

On Official: You can use items after the skill has been cast. It gives the proper amount of ATK. It doesnt consume any HP/SP. Also the skill has a single cool down. It does not give any global delay. It executes much faster on official. It cancels its execution mid-animation if the target gets out of range. Skills can be chained into and after it. It might very well scale with attack speed for execution speed. The skill cool down is 3 seconds.

Proof: https://www.youtube.com/watch?v=ibQimfXKyVQ
Proof: https://www.youtube.com/watch?v=-jfk1jXtVFg

Official kRO changelog:
"- Sura Modified Skill: The ability [Flash Combo] even if the person you are addressing the attack dies, this will be held until the end.
- Sura Skill Corrected: The ability [Flash Combo] now allowed to be attacked by the enemy when running.
- Sura Modified Skill: The ability [Flash Combo] is executed on an enemy and this is more than 3 cells away from you the skill is modified to be canceled ."
http://eathena.ws/forum/topic/1609-04102013-kro-maintenance/

He is also using Gentle Touch - Energy Gain to get back spheres for each attack in the combo.

Sadly i dont know his equipment effects. Point still stands tho.

**Comment by aleos89** [comment]
The person here states otherwise about using items/skills during Flash Combo: http://forums.irowiki.org/showpost.php?p=1345005&postcount=249

**Comment by RagnarokNova** [comment]
I'm pretty sure the SC_FLASHCOMBO status effect is not applying when you cast FC. But thanks for the rest of the update! KG is great.
