### ISSUE TITLE
make server error

### ISSUE THREAD

**Issue by jgfeliz** [rathena/rathena#1190]
I have the following error when I try to compile centos 7

`make[1]: Entering directory `/home/shinigami/rAthena/src/map'
            CC      itemdb.c
itemdb.c: In function 'itemdb_read_itemgroup_sub':
itemdb.c:618:4: error: incompatible type for argument 3 of 'itemdb_group_free'
    itemdb_group_free(db_ui2key(group_id), &data, NULL);
    ^
itemdb.c:546:12: note: expected 'va_list' but argument is of type 'void *'
 static int itemdb_group_free(DBKey key, DBData *data, va_list ap);
             ^
make[1]: *** [obj/itemdb.o] Error 1
make[1]: Leaving directory `/home/shinigami/rAthena/src/map'
make: *** [map] Error 2
`

**Comment by Lemongrass3110** [comment]
This must have been broken since November then.
This line was changed by me here: https://github.com/rathena/rathena/commit/86d6113801db3c18d78d437f54ad623ccf5230df#diff-a77bb0f27e703467040fcc353196222fR616

For the time being you could try to add a cast to va_list for the NULL parameter.

**Comment by jgfeliz** [comment]
I can not understand , what would be the solution?

**Comment by jgfeliz** [comment]
again
![2016-04-20 23_12_35-new notification](https://cloud.githubusercontent.com/assets/18557926/14696938/8b03428e-074d-11e6-90fe-6e22dcae6da7.jpg)

**Comment by Playtester** [comment]
Apparently centos doesn't like if you send NULL instead of a va_list (and it's really bad to do this because there's no memory allocated for it then).

Try to undo that part and see if that helps I'd say:

Replace:
```+			itemdb_group_free(db_ui2key(group_id), &data, NULL);```

With:
```
-			va_list ap;
-			itemdb_group_free(db_ui2key(group_id), &data, ap);
```

**Comment by hazimjauhari90** [comment]
this not happen only in centos. also happen too in debian.. perhaps happen in linux OS i think..i've got this error too in debian.

![ra error](https://cloud.githubusercontent.com/assets/16514357/14729747/302e1182-0873-11e6-8c8b-af22f46eeaa1.png)
.

**Comment by theoriginalspre** [comment]
Spre is back!

Anywho, This compiled beautifully without using va_list on ubuntu, which is a debian derivitive. I dont have centos to test need to get vmware reinstalled, but from what I gather changing NULL to 0 should work, should being the operative word

**Comment by jgfeliz** [comment]
I am using a raspberry pi2 with centos 7, hazimjauhari90 you are using a cubieboard, we are using ARMv7 platforms .....

replace the line as mentioned Playtester worked for me ...

I recommend you download centos 7 for cubieboard so you can compile without problems ...

im use google translate...

**Comment by hazimjauhari90** [comment]
i see.. i gues it happen only error in compiling in arm board..

by the way, i've fixed it already like playtester example.. but, i'm sticking in debian.. ^-^. i prefer more debian compared to centos.. here's the reason why.

http://herc.ws/board/topic/12435-centos-vs-debian/#entry72208
