### ISSUE TITLE
Guild Name not shown on 20151029RE Client

### ISSUE THREAD

**Issue by esu1214** [rathena/rathena#1191]
Guild Name not shown on 20151029RE Client.
Is that an officail change?

**Comment by admkakaroto** [comment]
type /showname in the chat.

**Comment by Darkelfen** [comment]
Use 2015-11-04

**Comment by RagnarokNova** [comment]
Definitely invalid. I run the client and guild names show fine. 
It's most likely either /showname or a refresh.

**Comment by aleos89** [comment]
As others have stated, you probably forgot to toggle /showname.
