### ISSUE TITLE
Bonus in equipment after cutin don't count

### ISSUE THREAD

**Issue by Weskercorp** [rathena/rathena#1193]
Let's say you add Aspd in a random weapon [Event purpose for example] and you want to show some badge of that event for a period of time:

`1705,Composite_Bow_,Composite Bow,5,2500,,600,29,,5,4,0x000A0848,63,2,34,1,4,1,11,{cutin "Badge",2; sleep2 4000; cutin "",255; bonus bAspdRate,3;},{},{}`

The Aspd bonus will not count. However, if you invert the order of the script

`1705,Composite_Bow_,Composite Bow,5,2500,,600,29,,5,4,0x000A0848,63,2,34,1,4,1,11,{bonus bAspdRate,3; cutin "Badge",2; sleep2 4000; cutin "",255; },{},{}`

The Aspd will count. I don't know if it's a bug, but I think this should not happen

See ya

Edit: Could be the sleep2 too... I'll test it.

**Comment by secretdataz** [comment]
Any non-stat scripts should be in OnEquip (second bracket) script instead of the first bracket.
In your case it should be
```
1705,Composite_Bow_,Composite Bow,5,2500,,600,29,,5,4,0x000A0848,63,2,34,1,4,1,11,{ bonus bAspdRate,3; },{ cutin "Badge",2; sleep2 4000; cuton "",255;  },{}
```

**Comment by aleos89** [comment]
As @secretdataz stated, not all script commands work in each of the item script fields.
