### ISSUE TITLE
GN_MAKEBOMB does not produce Black Lump

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#1194]
- The **Black Lump** ID(13265) pump is not being created when the failure occurs.
  The fault message displayed, but is not receives the pump.

Link: http://irowiki.org/wiki/Bomb_Creation

Black Lump
Bomb Creation failure.

Recent rA version
client 20151104

**Comment by Lemongrass3110** [comment]
Confirmed this issue on de8c0b7.

While confirming this issue I additionally found out, that we do not calculate the chance seperately for each creation as stated on iRO Wiki's description. I guess this should be done just like the soul link potion creations. This part needs kRO confirmation though and maybe we should create another issue on it.

**Comment by aleos89** [comment]
It has been confirmed that Black Lump is not created during the failure of Make Bomb.
