### ISSUE TITLE
r17068 compilation error

### ISSUE THREAD

**Issue by keitenai** [rathena/rathena#1196]
i got this compilation errors after updating rathena:

1>..\src\map\pc.c(503): warning C4133: 'function' : incompatible types - from 'bool (__cdecl *)(int,unsigned int,int,intptr_t)' to 'TimerFunc'
1>..\src\map\pc.c(536): warning C4133: 'function' : incompatible types - from 'bool (__cdecl *)(int,unsigned int,int,intptr_t)' to 'TimerFunc'
1>..\src\map\pc.c(559): warning C4133: 'function' : incompatible types - from 'bool (__cdecl *)(int,unsigned int,int,intptr_t)' to 'TimerFunc'
1>..\src\map\pc.c(562): warning C4133: 'function' : incompatible types - from 'bool (__cdecl *)(int,unsigned int,int,intptr_t)' to 'TimerFunc'
1>..\src\map\pc.c(12062): warning C4133: 'function' : incompatible types - from 'bool (__cdecl *)(int,unsigned int,int,intptr_t)' to 'TimerFunc'

**Comment by aleos89** [comment]
This was fixed in 94840b1.
