### ISSUE TITLE
@recall doesn't work if player is in vending while @autotrade

### ISSUE THREAD

**Issue by spinzaku** [rathena/rathena#1198]
Latest GIT download.

`@recall` doesn't work if the player is in vending while `@autotrade`
When the person logs in he has to wait 10 minutes before he can login again.

Tested another player who wasn't in `@autotrade` but was vending. Worked.

**Comment by aleos89** [comment]
We were unable to confirm this.

From what you stated, `@recall` should not even move autotrading players as there is this check in `pc_setpos`:
```
	if ( sd->state.autotrade && (sd->vender_id || sd->buyer_id) ) // Player with autotrade just causes clif glitch! @ FIXME
		return 1;
```

**Comment by spinzaku** [comment]
Oh. So this is normal? Just so weird you cant @recall a vendor thats on @autotrade. Since players sometimes dont follow side vending rules and vend and autotrade without caring. I wanted to move that person to the side using @recall . So only way is to dc them? Works normally on vendors without autotrade thou. Anyway please close if this is intended/normal, thank you
