### ISSUE TITLE
Memory leak (script engine)

### ISSUE THREAD

**Issue by Jeybla** [rathena/rathena#1205]
**Problem**
Returning NPC Variables in functions will cause memory leaks.

**Reproduce**
Add this script:

``` C
prontera,150,150,5  script  ScriptEngMemLeakBug 899,{
end;
function TestFunc {
    return .NPCVar;
}
OnInit:
    set .NPCVar,1;
    TestFunc();
    end;
}
```

After closing the server it will cause the following error:

> 0001 : script.c line 5381 size 16 address 0x0x7fde05f47584

Code Snippet from script.c:

``` C
 else if( name[0] == '.' && !data->ref ) { // script variable, link to current script
                data->ref = (struct reg_db *)aCalloc(sizeof(struct reg_db), 1);
                data->ref->vars = st->script->local.vars;

                if (!st->script->local.arrays)
                    st->script->local.arrays = idb_alloc(DB_OPT_BASE);
                data->ref->arrays = st->script->local.arrays;
            }
```

As you can see it's just a problem with permanent NPC variables by returning them. You can simply use a workaround by using scope variables. So it's kind of low priority.

**Affected versions**
Since 0696125b (Script engine update form hercules).

**Fix**
So I've looked in hercules if there's the same problem:

```
else if( name[0] == '.' ) {
                // npc variable
                if( !data->ref ) {
                    // npc variable without a reference set, link to current script
                    data->ref = (struct reg_db *)aCalloc(sizeof(struct reg_db), 1);
                    script->add_pending_ref(st, data->ref);
                    data->ref->vars = st->script->local.vars;
                    if( !st->script->local.arrays )
                        st->script->local.arrays = idb_alloc(DB_OPT_BASE);
                    data->ref->arrays = st->script->local.arrays;
                } else if( data->ref->vars == st->stack->stack_data[st->stack->defsp-1].u.ri->script->local.vars ) {
                    data->ref = NULL; // Reference to the parent scope's script, remove reference pointer.
                }
            }
```

Hercules uses another script state for returning NPC Variables. The returning Script is set in a "pending" state so the calling script can access it's variables.

**But I'd suggest another approach by just returning the value**. I can't imagine a useful case when you should access a returned variable by returning it's reference. It will just cause side effects, isn't it? :D

Thanks for other suggestions!

**Comment by lighta** [comment]
@Jeybla, if we return by value any complex type will be an issue, like array or string. This will be much slower then transferring a pointer.
What I'm wondering is why do we need to reallocate, we probably don't. Or something like a Fake_Stack state. (Dunno if pending will be the good term, I prefer seeing it as a Stack, pending could mean waiting for stuff etc where here is clearly a temporary state for execution.)
