### ISSUE TITLE
setnpcdisplay problem

### ISSUE THREAD

**Issue by RadianFord** [rathena/rathena#1206]
Hash : 1ca9fb58f21bd7ea3a5ea1b6f6de1b22cc086a60
Client ver : 2015 05 13 ragexe
Mode: Pre renewal

I did follow what the wiki said, but its not working or maybe im just wrong with this.

Example
`setnpcdisplay("Wandering Spirit","Knight of Glastheim","657");`
into
`setnpcdisplay("Knight of Glastheim","Wandering Spirit","802");`

**Comment by Jeybla** [comment]
Maybe your NPC has a hidden suffix in his name? (i.e. Kafra#prt01)

Also could you please provide your git hash and the head declaration of your NPC, thanks.

**Comment by RadianFord** [comment]
No no suffix.

> prontera,150,150,4	script	Wandering Spirit	805,{

mes "......";
setnpcdisplay("Wandering Spirit","Knight of Glastheim","657");
next;
mes ",,,,,,";
setnpcdisplay("Knight of Glastheim","Wandering Spirit","802");
end; }

**Comment by dastgir** [comment]
setnpcdisplay("Wandering Spirit","Knight of Glastheim","657");
Should be
setnpcdisplay("Wandering Spirit","Knight of Glastheim",657);

ViewID should not be in quotes

**Comment by RadianFord** [comment]
@dastgir still the same.

**Comment by Lemongrass3110** [comment]
Any error messages on your mapserver?

**Comment by RadianFord** [comment]
@Lemongrass3110 no errors shown in map.

**Comment by RadianFord** [comment]
Oh. what i did was
	```
mes "[Wandering Spirit]";
	mes "Welcome back!";
	next;
	setnpcdisplay("Wandering Spirit","Knight of Glastheim",657);
	mes "[Knight]";
	mes "Schmitz Von Walter was first very strong and kind hearted ruler and by his kind heart that the valkyries themselves offered him wisdom";
	next;
	mes "[Knight]";
	mes "About the development of his own forces which made them strong... However Schmitz Von Walter became corrupted with the power he attained and soon did horrible things to his people which corrupted";
	next;
	mes "[Knight]";
	mes "him even more, He was eventually overthrown and then he became what is known as the Dark Lord...";
	next;
	mes "[Knight]";
	mes "Young warrior that is all I can tell you, Here's the reward for coming this far, Maybe in the future we will see each other again.";
	getitem 32018,1;
	announce "congratulations "+strcharinfo(0)+" "+(Sex?"he":"she")+" accomplished the Memory Of Glastheim.",bc_all,0xffccff;
	next;
	mes "[Wandering Spirit]";
	mes ".........";
	setnpcdisplay("Knight of Glastheim","Wandering Spirit",802);
```

**Comment by RadianFord** [comment]
So it should be separated?

**Comment by RadianFord** [comment]
Ok fixed thanks @Atemo
