### ISSUE TITLE
Woe Issue

### ISSUE THREAD

**Issue by Yuchinin** [rathena/rathena#1207]
Issue found:
- Emperium only respawn on guildless castle on server reload, that mean when the castle has owner, it will not spawn an emperium on server reload.

revision: latest rAthena

**Comment by Playtester** [comment]
Yes, could be, the update definitely affects Emperium and Guardians.
I'll let @aleos89 take a look at it..

**Comment by aleos89** [comment]
Thanks for the report, I'll start looking into this.

**Comment by Yuchinin** [comment]
I just notice even MVP no longer wandering.

**Comment by aleos89** [comment]
Hm, well if your MVP aren't moving then it sounds like you have conflicts with your mob_db or something in source.

Could you paste your guardian and some MVP here so I can see if their modes are good.

**Comment by Yuchinin** [comment]
What should I paste here? They are all official rAthena script@@

**Comment by Playtester** [comment]
What you are describing would happen if you applied the mob mode update without updating the mob_db. I assume you are using SQL and didn't do a full update on the database since the update.

**Comment by Yuchinin** [comment]
Opps mob wandering issue is solved now, but the emperium issue still there

**Comment by Yuchinin** [comment]
Emperium issue get solve when I add below this line on Gld_Agit_Manager:
donpcevent "Agit#"+.@hiddenname$+"::OnStartArena";// this line
// And load purchased Guardian in castles.
donpcevent "Guardian#"+.@hiddenname$+"::OnSpawnGuardians";

**Comment by aleos89** [comment]
Glad you solved the walk issue. As for the Emperium issue, please use quotes when using code, especially any code with @ before it so we don't tag random users in GitHub. I adjusted your comment.

I searched for the bit of code you pasted and I can't find it exactly to what you put. Are you using an older version of WoE? Is this the FE or SE?

**Comment by Yuchinin** [comment]
FE on latest rA..
 
OnAgitInit:
OnRecvCastle:
if (.@GID == 0) {
...
}else{
                donpcevent "Agit#"+.@hiddenname$+"::OnStartArena";          // <------------ this line
                // And load purchased Guardian in castles.
		donpcevent "Guardian#"+strnpcinfo(2)+"::OnSpawnGuardians";
		// And display Kafra if purchased.
		if (GetCastleData(strnpcinfo(2),9) < 1) disablenpc "Kafra Staff#"+strnpcinfo(2);
}

**Comment by aleos89** [comment]
I finally got some free time to test. I started WoE:FE through `@agitstart` and broke the Emperium. After breaking I couldn't attack it myself. I restarted the server and went back in the castle and attempted to attack the Emperium with the same results, I did no damage.

Attached is a screen shot of me trying to attack the Emperium and not being able to:
![emp](https://cloud.githubusercontent.com/assets/3521753/14871533/058442d4-0cb1-11e6-8486-f7c9cfd9085a.png)

These tests were done on on a clean pull from 7a3b3e5.

**Comment by spinzaku** [comment]
I have encountered sort of similar issue. WOE = Turned off  But Emperium was in castle. Players in my server attacked, broke the emp and got the castle w/ WOE turned off. I even tried to do the @agitend/@agitend2 and it just says " "War of Emperium is currently not in progress."

**Comment by aleos89** [comment]
That is also intended behavior of guild castles that have no owners.

**Comment by spinzaku** [comment]
So new servers must go in castle_db and add // to stop this issue for now?

**Comment by aleos89** [comment]
Or just completely comment out the guild scripts from the NPC directory.

**Comment by spinzaku** [comment]
i chatted with secret, he/she said just to add // in castle_db.. is there a @reloadcastle_db?  also how do you remove a captured castle? since this guild got w/ woe off. haha

**Comment by Yuchinin** [comment]
Way to reproduce:
I let the agit start on Init;
OnInit:
AgitStart;
end;
![just break an emperium](https://cloud.githubusercontent.com/assets/6026415/14896541/d9209cc8-0db0-11e6-9dbd-28a8584e4e35.png)
After break the emperium, I close the server and restart it, I still owner of the castle, but it spawned a neutral emperium, which everyone can attack.
![after restart the server](https://cloud.githubusercontent.com/assets/6026415/14896692/6d4efe26-0db1-11e6-94ec-13afca2672a1.png)

**Comment by Yuchinin** [comment]
Opps aleo you can forget about my upper 2 pic, I solve the issue by adding a sleep 5000; below OnInit, so after the server init, sleep for 5 sec and start Init, it don't spawn the neutral emperium anymore.

But about the server reload emperium not spawn issue:

OnAgitInit:
OnRecvCastle:
if (.@GID == 0) {
...
}else{
donpcevent "Agit#"+.@hiddenname$+"::OnStartArena"; // <------------ this line
// And load purchased Guardian in castles.
donpcevent "Guardian#"+strnpcinfo(2)+"::OnSpawnGuardians";
// And display Kafra if purchased.
if (GetCastleData(strnpcinfo(2),9) < 1) disablenpc "Kafra Staff#"+strnpcinfo(2);
}

emperium will not spawn on server reload if don't have below line added:
- donpcevent "Agit#"+.@hiddenname$+"::OnStartArena"; // <------------ this line
