### ISSUE TITLE
[BUG] getequipid(EQI_HAND_R) failed script and CONST

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#1211]
Currently there is a serious BUG in the test script items, any script that uses CheckItem is working. 

EQI_ constants are not working.

example:

=========================================
- Does not work*
if(getequipid(4) == 1368) 

- Does not work*
if(getequipid(EQI_HAND_R) == 1368)

=========================================

None of the cases is recognizing. The same is true for refinements tests among others.

rA: Recent version
client: 20151104

**Comment by Lemongrass3110** [comment]
Please provide a git hash.
Also make sure that your const_db.txt does not contain the EQI_ constants anymore.
This could be a merge conflict.

**Comment by Jeybla** [comment]
I think @Lemongrass3110 is right.
Can't confirm this. Tested on 62271358da41cfc3f6239d73af964ce79b5a909b

**Comment by aleos89** [comment]
I was also unable to reproduce this. Make sure your merge has no conflicts from the update on 2bf64c9.
