### ISSUE TITLE
Script engine

### ISSUE THREAD

**Issue by Tokeiburu** [rathena/rathena#1212]
I'm having some trouble with the following script (simplified example). The issue appears to be related to the += operator. (Couldn't figure out how to format the code tags without breaking the tabs, so here: http://pastebin.com/v2a3RqSH ) :

```
function	script	AMethodWithReturn	{
	return ((.@anything$ == "") ? 1 : 0 );
}

prontera,150,150,0	script	TestNPC	77,{
	.@value += callfunc("AMethodWithReturn", 1);
	
	mes "" + .@value;
	end;
}
```

Which gives me:
```
[Warning]: Unexpected type for argument 1. Expected variable, got C_STR.
[Debug]: Data: string value="0"
[Debug]: Function: set
[Debug]: Source (NPC): TestNPC at prontera (150,150)
[Error]: script:set: not a variable
[Debug]: Data: string value="0"
[Debug]: Source (NPC): TestNPC at prontera (150,150)`
```

This issue also appears in the following scenario:

```
function	script	AMethodWithReturn	{
	.@input$ = "test";
	if (.@input$ == getarg(0))
		return 1;
	return 0;
}

prontera,150,150,0	script	TestNPC	77,{
	.@value += callfunc("AMethodWithReturn", "test");
	.@value += callfunc("AMethodWithReturn", "test");
	.@value += callfunc("AMethodWithReturn", "test");
	
	mes "" + .@value;
	end;
}
```

With the following output:
```
[Warning]: Unexpected type for argument 1. Expected number.
[Debug]: Data: variable name='.@input$' index=0
[Warning]: Unexpected type for argument 2. Expected label, got C_INT
[Debug]: Data: number value=0
[Warning]: Found more arguments than necessary. unexpected arg type C_POS
[Debug]: Function: jump_zero
[Debug]: Source (NPC): TestNPC at prontera (150,150)
[Error]: script: jump_zero: not label !
[Debug]: Source (NPC): TestNPC at prontera (150,150)
```

This currently breaks the following quest: npc/quests/quests_moscovia.txt > the S_Question subfunction in the script brings out similar errors.

Git version: 62271358da41cfc3f6239d73af964ce79b5a909b

**Comment by majimboo** [comment]
Hello, I have a suggestion. Would be better if you can provide a more complete code of the issue.

Try this, (untested code)

```
function    script  AMethodWithReturn   {
	if .@anything$ == ""
		return 1;
	
	return 0;
}

prontera,150,150,0  script  TestNPC 77,{
    .@value = callfunc("AMethodWithReturn", 1);

    mes sprintf("%d", .@value)
    end;
}
```

**Comment by Tokeiburu** [comment]
callfunc should not return a string, but an integer value. These two scripts should be enough to show and debug the error ;x. The issue isn't with callfunc anyway, it appears to be a combination of +=, -=/, etc operators with the ternary operator. For instance, the following code will not work:

```
prontera,150,150,0	script	TestNPC	77,{
	.@value += (.@test$ == "") ? 1 : 0;
	.@value += (.@test$ == "") ? 1 : 0;
	.@value += (.@test$ == "") ? 1 : 0;
	
	mes "" + .@value;
	end;
}
```

The value of `.@value` is 1, but it should be 3.
The following line should be enough to make the script engine bug as well:

```
prontera,150,150,0	script	TestNPC	77,{
	.@value += ("" == "") ? 1 : 0;
	
	mes "" + .@value;
	end;
}
```

Which gives the following output:
```
[Warning]: Unexpected type for argument 1. Expected variable, got C_INT.
[Debug]: Data: number value=1
[Debug]: Function: set
[Debug]: Source (NPC): TestNPC at prontera (150,150)
[Error]: script:set: not a variable
[Debug]: Data: number value=1
[Debug]: Source (NPC): TestNPC at prontera (150,150)
```

**Comment by majimboo** [comment]
Okay, I guess I was wrong. I can't test it too because I don't have a server. One last thing, shouldn't this be `.@value += (("" == "") ? 1 : 0);`?

**Comment by Tokeiburu** [comment]
Makes no difference ;P.

**Comment by majimboo** [comment]
Aaah,  :+1:  must be some bug then.

**Comment by Jeybla** [comment]
Thanks for the fix <3
