### ISSUE TITLE
Stat Points messed up

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#1213]
https://rathena.org/board/topic/105501-status-point-anti-cheat/

I've calculated it through, everything should be just fine.
But something is messing up the status point calculation (original script by brian)

I have condesed the script, yet not changed any of the main functions (which are all directly from the source code)

What's wrong with the calculation? Were there any bigger stat code changes in the source code?

**Comment by majimboo** [comment]
Which source file did you reference for your calculations?

**Comment by Atemo** [comment]
Core issue
```
	.@t = 13;
	dispbottom bStr;// is 13
	dispbottom readparam(.@t);// return 13
	dispbottom readparam(13);// return str value
```

**Comment by majimboo** [comment]
Just saw the `pc_need_status_point` [here](https://github.com/rathena/rathena/blob/62271358da41cfc3f6239d73af964ce79b5a909b/src/map/pc.c#L6681)

**Comment by Lemongrass3110** [comment]
Well I do not really know why we do this, but it seems like intended behaviour:

```
	if (data->type == C_NAME) { // If using constant name, just get the val
		get_val_(st, data, sd);
		script_pushint(st, (int)data->u.num);
		return SCRIPT_CMD_SUCCESS;
	}
```

**Comment by Atemo** [comment]
For reference [https://github.com/rathena/rathena/issues/647](url)

**Comment by Everade** [comment]
Is there any work-around script wise or do i have to wait for a core fix?

**Comment by majimboo** [comment]
You can check the script I added (first comment), and look at this:

    function pc_getstat {
        switch( getarg(0) ) {
            case bStr: return readparam(bStr);
            case bAgi: return readparam(bAgi);
            case bVit: return readparam(bVit);
            case bInt: return readparam(bInt);
            case bDex: return readparam(bDex);
            case bLuk: return readparam(bLuk);
        }

        return;
    }

**Comment by Everade** [comment]
Didn't manage to get your untested script to work.
Even it's format is messed up, and working through the entire script is a lot of work if i'm not even sure if it's going to workout at all.

**Comment by majimboo** [comment]
You don't have to use my script. Its just there to give some points. Just
change the part on my last comment. The point is, instead of passing the
@type to getparams, pass the bStr constant and others. Use a switch
statement.

-- 
Careers <http://careers.stackoverflow.com/majimboo> | StackOverflow
<http://stackoverflow.com/users/3134069/majimboo> | Github
<https://github.com/majimboo> | NPM <https://www.npmjs.org/~majidarif> |
LinkedIn <http://www.linkedin.com/pub/majid-arif-siddiqui/73/73/527> | oDesk
<https://www.odesk.com/users/~0145927bd962297734> | ePVP
<http://www.elitepvpers.com/forum/members/694517-majidemo.html>

**Comment by majimboo** [comment]
I'll patch your script once I get home. Although my script shows the point
pretty well. (Taken like a psuedocode)

-- 
Careers <http://careers.stackoverflow.com/majimboo> | StackOverflow
<http://stackoverflow.com/users/3134069/majimboo> | Github
<https://github.com/majimboo> | NPM <https://www.npmjs.org/~majidarif> |
LinkedIn <http://www.linkedin.com/pub/majid-arif-siddiqui/73/73/527> | oDesk
<https://www.odesk.com/users/~0145927bd962297734> | ePVP
<http://www.elitepvpers.com/forum/members/694517-majidemo.html>

**Comment by majimboo** [comment]
I'm guessing you are not a programmer,

Anyway change this:

    set .@low, readparam(.@type);

To

    switch( .@type ) {
        case bStr: set .@low, readparam(bStr);
        case bAgi: set .@low, readparam(bAgi);
        case bVit: set .@low, readparam(bVit);
        case bInt: set .@low, readparam(bInt);
        case bDex: set .@low, readparam(bDex);
        case bLuk: set .@low, readparam(bLuk);
    }

**Comment by Everade** [comment]
[Error]: script:run_script_main: infinity loop !
[Debug]: Source (NPC): Total_Stat_Points at prontera (155,180)

And no i'm not, i only know C# basics and can understand scripts if i read them through because i didn't fell on my head when i was born xD

**Comment by Everade** [comment]
@Lemongrass3110 any update on this matter?

**Comment by Keysito** [comment]
@majimboo  bay? active pa ghpon kag RO? please PM ME sa forum.
