### ISSUE TITLE
transform disguise icon time 

### ISSUE THREAD

**Issue by julia40124009** [rathena/rathena#1215]
test item id 12658

when not warp , show time work fine
<a href="http://imgur.com/Uy9AcJF"><img src="http://i.imgur.com/Uy9AcJF.png" title="source: imgur.com" /></a>

after warp , time is disappear
<a href="http://imgur.com/4z4YdNm"><img src="http://i.imgur.com/4z4YdNm.png" title="source: imgur.com" /></a> 

version : 55e4df1
mode : renewal
client : 20151104

**Comment by aleos89** [comment]
I think this has to do with us sending 9999 to the client for unlimited time. It shows fine at start but then we call `clif_spawn()` which in turns calls `clif_status_change2()` which sends the 9999.
