### ISSUE TITLE
Lunatic Carrot Beat

### ISSUE THREAD

**Issue by Playtester** [rathena/rathena#1219]
Investigating this skill currently, this is what we've found so far:

1. Damage per skill is 200%+100%*level. The damage is calculated as if it was one hit, rather than per-hit, yet the skill still manages to hit plants, so it behaves different from all pre-renewal skills.

2. Base cast time seems to be 1500ms (~1000ms with 30% reduction) and cooldown seems to be 6000ms. This is quite different from our last tests, we assume it was a balance update.

TODO:
- Check if Catnip Meteor behaves the same in terms of damage
- Check if cast times and cooldowns have changed for all physical doram skills
- Check stun chance and duration and carrot consumption
- Check if skill can miss

**Comment by RagnarokNova** [comment]
I got 8/34 stuns (Testing this was a huge hassle) which is making me believe it's either 20% or 25% stun duration. The stuns lasted ~4 seconds, which if you account for stats reducing the duration and delay from me starting my stopwatch, it's likely the default 5. Carrot Consumption is on cast if a Carrot exists. If it does not, it casts anyway with no stun chance.

**Comment by Playtester** [comment]
Catnip Meteor uses the same damage style of Lunatic Carrot Beat. Single damage calculation, but still can hit plants. Need to implement a special case for it.
