### ISSUE TITLE
Amon Ra = Bugged = Easy Kill

### ISSUE THREAD

**Issue by spinzaku** [rathena/rathena#1221]
My player describe it easily. 
"Amon ra summons and mobs do nothing, and just stand"
"If you attack the summon, it will fight back.. but if you don't attack, it does nothing"
"The mobs also don't die after u kill amon ra.. they just stay there"
"killed him 7 times yesterday, basement 2 all filled with his summon stuck"

Attached screenshot

![amon ra](https://cloud.githubusercontent.com/assets/18629476/14893105/acc2a2ee-0da0-11e6-90d4-da592f02813a.jpg)

latest updated git

**Comment by aleos89** [comment]
Thanks, it has been confirmed.

**Comment by Playtester** [comment]
It's correct that they don't die when Amon Ra is killed. They aren't slaves, they are summoned monsters that should behave 100% like normal monsters.
