### ISSUE TITLE
RE Map Cache needs an update, it uses old Prontera.gat

### ISSUE THREAD

**Issue by spinzaku** [rathena/rathena#1222]
I am running latest git update, with renewal. my korean ragnarok is fully patched.
I noticed when i walked around Prontera their were many invisible walls. I had to update the map_cache.dat and replaced the Prontera.gat with the new one from latest kRO. After that all invisible walls are gone.. but npc's and warps all need an update..

![screenandzro019](https://cloud.githubusercontent.com/assets/18629476/14894045/532e22a4-0da4-11e6-9371-94d36732a2e0.jpg)

other people already reported this issue:
https://rathena.org/board/topic/105231-update-map-cache-in-re-for-new-prontera-gat/
https://rathena.org/board/topic/105309-new-prontera-invisible-wall/

**Comment by Playtester** [comment]
Can't support all versions. The default supported version is still 20130807 (as that's the packetver that is used by default). It's not only that, you also need to move all the warps, NPCs, etc.

So it would be global emulator decision which version to support.

**Comment by Jeybla** [comment]
@Playtester is right.

If someone is interestest in warp positions for new prontera, here is a small patch:
```
diff --git a/npc/warps/cities/prontera.txt b/npc/warps/cities/prontera.txt
index 01add8c..3236923 100755
--- a/npc/warps/cities/prontera.txt
+++ b/npc/warps/cities/prontera.txt
@@ -16,28 +16,28 @@
 //============================================================
 
 //= Prontera City ============================================
-prontera,107,215,0	warp	prt01	2,2,prt_in,240,139
+prontera,105,215,0	warp	prt01	2,2,prt_in,240,139
 prontera,120,267,0	warp	prt02	2,2,prt_in,180,97
 prontera,133,183,0	warp	prt03	2,2,prt_in,50,105
 prontera,134,221,0	warp	prt04	1,1,prt_in,131,71
 prontera,156,22,0	warp	prt001	3,2,prt_fild08,170,375
 prontera,156,360,0	warp	prt005	4,2,prt_castle,102,20
-prontera,177,221,0	warp	prt05	2,2,prt_in,168,128
-prontera,179,184,0	warp	prt06	2,2,prt_in,60,73
+prontera,178,225,0	warp	prt05	2,2,prt_in,168,128
+prontera,178,186,0	warp	prt06	2,2,prt_in,60,73
 prontera,192,267,0	warp	prt07	2,2,prt_in,178,55
-prontera,204,192,0	warp	prt08	2,2,prt_in,68,134
-prontera,208,154,0	warp	prt09	2,2,prt_in,172,29
+prontera,207,192,0	warp	prt08	2,2,prt_in,68,134
+prontera,208,151,0	warp	prt09	2,2,prt_in,172,29
 prontera,22,203,0	warp	prt002	2,3,prt_fild05,367,205
 prontera,237,317,0	warp	prt004	2,2,prt_church,100,60
 prontera,289,203,0	warp	prt003	2,3,prt_fild06,27,193
-prontera,42,67,0	warp	prt10	2,2,prt_in,44,29
+prontera,41,62,0	warp	prt10	2,2,prt_in,44,29
 prontera,45,346,0	warp	prt11	2,2,prt_in,80,110
 prontera,73,100,0	warp	prt12	1,1,prt_in,208,176
 prontera,74,90,0	warp	prt13	2,2,prt_in,248,170
 prontera,84,89,0	warp	prt14-1	1,1,prt_in,282,176
-prontera,263,279,0	warp	prt15-2	2,2,prt_in,227,18
+prontera,263,280,0	warp	prt15-2	2,2,prt_in,227,18
 prt_in,135,71,0	warp	prt04-1	1,2,prontera,136,219
-prt_in,168,124,0	warp	prt05-1	2,1,prontera,174,218
+prt_in,168,124,0	warp	prt05-1	2,1,prontera,174,222
 prt_in,172,33,0	warp	prt09-1	2,1,prontera,205,157
 prt_in,181,55,0	warp	prt07-1	1,2,prontera,192,264
 prt_in,183,97,0	warp	prt02-1	1,2,prontera,120,264
```

**Comment by spinzaku** [comment]
Thank you for this @Jeybla .. but i suggest adding this in as seperate in the git? since there are servers that use latest updates.

**Comment by zackdreaver** [comment]
it's part of episode update 15 or so,
but ra still in episode 13.x i believe

**Comment by darknessfmy** [comment]
hey Thank you @Jeybla

**Comment by darknessfmy** [comment]
Have errors the patch of @Jeybla 
This work correctly
`Index: prontera.txt
===================================================================
diff --git a/npc/warps/cities/prontera.txt b/npc/warps/cities/prontera.txt
--- a/npc/warps/cities/prontera.txt	(revision 245)
+++ b/npc/warps/cities/prontera.txt	(working copy)
@@ -4,7 +4,7 @@
 //= Athena (1.0)
 //= Nana (1.2)
 //===== Current Version: =====================================
-//= 1.5
+//= 1.6
 //===== Compatible With: =====================================
 //= rAthena Project
 //===== Description: =========================================
@@ -13,31 +13,32 @@
 //= 1.3 prt19 warp fix [shadow]
 //= 1.4 Added warps for the sign quest [MasterOfMuppets]
 //= 1.5 Corrected NPC names to fall within proper restrictions. [L0ne_W0lf]
+//= 1.6 Update to new oficial Prontera map (Renewal). [Jeybla]
 //============================================================
 
 //= Prontera City ============================================
-prontera,107,215,0	warp	prt01	2,2,prt_in,240,139
+prontera,105,215,0	warp	prt01	2,2,prt_in,240,139
 prontera,120,267,0	warp	prt02	2,2,prt_in,180,97
 prontera,133,183,0	warp	prt03	2,2,prt_in,50,105
 prontera,134,221,0	warp	prt04	1,1,prt_in,131,71
 prontera,156,22,0	warp	prt001	3,2,prt_fild08,170,375
 prontera,156,360,0	warp	prt005	4,2,prt_castle,102,20
-prontera,177,221,0	warp	prt05	2,2,prt_in,168,128
-prontera,179,184,0	warp	prt06	2,2,prt_in,60,73
+prontera,178,225,0	warp	prt05	2,2,prt_in,168,128
+prontera,178,186,0	warp	prt06	2,2,prt_in,60,73
 prontera,192,267,0	warp	prt07	2,2,prt_in,178,55
-prontera,204,192,0	warp	prt08	2,2,prt_in,68,134
-prontera,208,154,0	warp	prt09	2,2,prt_in,172,29
+prontera,207,192,0	warp	prt08	2,2,prt_in,68,134
+prontera,208,151,0	warp	prt09	2,2,prt_in,172,29
 prontera,22,203,0	warp	prt002	2,3,prt_fild05,367,205
 prontera,237,317,0	warp	prt004	2,2,prt_church,100,60
 prontera,289,203,0	warp	prt003	2,3,prt_fild06,27,193
-prontera,42,67,0	warp	prt10	2,2,prt_in,44,29
+prontera,41,62,0	warp	prt10	2,2,prt_in,44,29
 prontera,45,346,0	warp	prt11	2,2,prt_in,80,110
 prontera,73,100,0	warp	prt12	1,1,prt_in,208,176
 prontera,74,90,0	warp	prt13	2,2,prt_in,248,170
 prontera,84,89,0	warp	prt14-1	1,1,prt_in,282,176
-prontera,263,279,0	warp	prt15-2	2,2,prt_in,227,18
+prontera,263,280,0	warp	prt15-2	2,2,prt_in,227,18
 prt_in,135,71,0	warp	prt04-1	1,2,prontera,136,219
-prt_in,168,124,0	warp	prt05-1	2,1,prontera,174,218
+prt_in,168,124,0	warp	prt05-1	2,1,prontera,174,222
 prt_in,172,33,0	warp	prt09-1	2,1,prontera,205,157
 prt_in,181,55,0	warp	prt07-1	1,2,prontera,192,264
 prt_in,183,97,0	warp	prt02-1	1,2,prontera,120,264
`

**Comment by aleos89** [comment]
According to the latest Sakray patch from kRO (November 30, 2016), they just reverted Prontera to it's old state.
