### ISSUE TITLE
Last letter in party chat get cut when using 2015-11-04

### ISSUE THREAD

**Issue by VXPlay** [rathena/rathena#1223]
The words or phrases entered by a player are not completely seen by another player. Independent player put a whole phrase or just one word, the last letter is always cut.

Player says:
http://i.imgur.com/Tb47Fgr.jpg

Another Player see:
http://i.imgur.com/0NngPoC.jpg

I'm using EXE 04/11/2015

My Clif.c is this :

#if PACKETVER >= 20151001
	if (message[messagelen-1] != '\0')
	{
		message[messagelen++] = '\0';
	}
#endif

----------------------------------------------------------------------------------
#if PACKETVER >= 20151001
	message_len++;
#endif

----------------------------------------------------------------------------------------
#if PACKETVER >= 20151001
	textlen++;
#endif

**Comment by admkakaroto** [comment]
You use eAmod?

**Comment by VXPlay** [comment]
Yes, I use a diff applied to rathena emulator.

**Comment by admkakaroto** [comment]
the rAthena bug has not it, look for support in eamod forum.

**Comment by esu1214** [comment]
Could give a eamod forum link?

**Comment by spinzaku** [comment]
tested this last night, no bug for rAthena

**Comment by aleos89** [comment]
Fixed in a89ab2f.
