### ISSUE TITLE
Juno Remedy Quest

### ISSUE THREAD

**Issue by RadianFord** [rathena/rathena#1224]
Hash: 1ca9fb58f21bd7ea3a5ea1b6f6de1b22cc086a60
Pre Renewal

It says that in iRO wiki http://irowiki.org/wiki/Juno_Remedy_Quest

> Playing Bingo is no longer necessary for completing the quest.

**Comment by zackdreaver** [comment]
That's renewal page,
use prerenewal one
http://irowiki.org/classic/Juno_Remedy_Quest

**Comment by RadianFord** [comment]
Oh i see thanks
