### ISSUE TITLE
Assassin Quest Bugged? (can't get necklace of oblivion)

### ISSUE THREAD

**Issue by spinzaku** [rathena/rathena#1228]
Assassin Quest Bugged? my player just experienced this..

If a player alt+tabs for a minute when the npc is asking him what weapon he wants. like the Katar.. server assumes he accepted.. but he doesn't get the Necklace of oblivion item nor the katar. He is stuck as thief until i come in and give him the required items.. 

![13123419_1400882433270628_7477122987561775373_o](https://cloud.githubusercontent.com/assets/18629476/14940101/d121d098-0f98-11e6-9291-dfa61facfb5e.jpg)

This bug also exists in official servers...  https://forums.warpportal.com/index.php?/topic/130060-didnt-receive-necklace-of-oblivion-when-changing-assassin/

The player needs to contact a GM, or wait for the next server maintenance, or try asking for another player to get the oblivion.. if not stuck as thief.

Please fix this? It would be so annoying if you are managing a big server and this happens.. you have to manually intervene in order to fix? some players alt+tab because they research on the internet before choosing. hahaha

**Comment by MrAntares** [comment]
Nice catch. I suppose we only need to move the quest value change to the end of the discussion where the player gets the items.

set ASSIN_Q....
on lines 2059, 2060 and 2097.


Something like this would fix it:
`		if (ASSIN_Q3 == 1 && BaseJob == Job_Thief && ASSIN_Q > 6 && ASSIN_Q < 17) {
			mes "[Guildmaster]";
			mes "Well, I've said too much. Please choose a weapon as a present.";
			next;
			mes "[Guildmaster]";
			mes "You can choose a Jur, Katar, Main Gauche, or a Gladius. As a master, I love them all.";
			next;
			switch(select("Jur:Katar:Main Gauche:Gladius")) {
			case 1:
				mes "[Guildmaster]";
				mes "A Jur...";
				mes "Good choice. There you are. I hope it will serve you well.";
				getitem 1251,1; //Jur_
				break;
			case 2:
				mes "[Guildmaster]";
				mes "A Katar...";
				mes "Here you are.";
				mes "Although it's used,";
				mes "I know it will";
				mes "serve you well.";
				getitem 1253,1; //Katar_
				break;
			case 3:
				mes "[Guildmaster]";
				mes "I see. You want to use both hands. Here, take your Main Gauche.";
				getitem 1208,1; //Main_Gauche_
				break;
			case 4:
				mes "[Guildmaster]";
				mes "A Gladius...";
				mes "It used to rule over the Assassin weapon market. Please take care of my gladius.";
				getitem 1220,1; //Gladius_
			}
			set ASSIN_Q,17;
			set ASSIN_Q3,2;
			next;
		}
		else {
			mes "[Guildmaster]";
			mes "Well, I talked too much.";
			mes "Please take this first.";
			next;
			switch(rand(1,5)) {
			case 1:
				getitem 1207,1; //Main_Gauche
				break;
			case 2:
				getitem 1250,1; //Jur
				break;
			case 3:
				getitem 1216,1; //Stiletto
				break;
			case 4:
				getitem 1201,1; //Knife
				break;
			case 5:
				getitem 1252,1; //Katar
			}
			set ASSIN_Q,17;
		}`

**Comment by spinzaku** [comment]
will you guys make an official commit for this?

**Comment by MrAntares** [comment]
I had to edit the first line because for some reasin some characters got URL encoded (&gt; &lt; etc..) Now it's ok.

**Comment by spinzaku** [comment]
i haven't edited yet. did you test this in-game? thank you btw

**Comment by MrAntares** [comment]
Nop. I only changed the code.

**Comment by spinzaku** [comment]
=o i am running on a live server thou. i was going to do a @unloadnpc and @loadnpc haha

**Comment by MrAntares** [comment]
You can always test it but I only moved the quest progress change command nothing else. It will work. And even if it's not ok you can reload the previous code if you make a backup so it's not a big deal. Btw the guys from the dev team are still looking into the official thing to see how it works, but since you said that it's officially bugged, I don't expect much.

**Comment by secretdataz** [comment]
From looking at the staff's reply in this [thread](https://forums.warpportal.com/index.php?/topic/130060-didnt-receive-necklace-of-oblivion-when-changing-assassin/), I think they fixed it on iRO.
Should we just fix this or wait for confirmation on kRO?
