### ISSUE TITLE
Missing Cash Shop Feature: Special Tab "Update Quantity"

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#1229]
The current official (new) Cash Shop interface and it's used item_cash_db.txt gives us **0** possibilities to make anything dynamic at all.

Maybe i'm unaware about some specific features, but as of now i wasn't able to find anything even related to the cash shop system that could be usefull.

So the only settings we've got are:
_// Type,ItemID,Price_

**But there's no way we could possibly set a time limited offer nor anything "Special" about the special section itself such as limited quantities or whatever it has been created for.**

It would be more than great to be able to dynamicaly change/update the cash shop without the need to reload the item database.
So we can "per script" set special prices, limited offers and update the shop on the fly without accessing the server itself.

At the current state, using the old cash shop system gives us way more possibilities on updating the shops itself.
There, it's limited to our scripting skills.

But the "new" Cash Shop Button / Interface Shop **is lacking it's very core features.**

**Comment by Lemongrass3110** [comment]
Hey Everade,
this is a feature suggestion rather than a bug report/issue.
So it would be nice if you could post your ideas in this forum section https://rathena.org/board/forum/104-source-discussion/ before creating an issue here in github.
In there you can suggest what features and script commands you would like to see and give others the chance to discuss it with you.
From our current knowledge it is not possible to update the cash shop data after it was sent to the client, so if you update the shop data you would have to force a relog on all (non autotrading) players.
Thank you for understanding.

**Comment by Everade** [comment]
I would see it as a bug as i can't imagine that it has ever been fully implemented.
Is it really official like this? i doubt so...

**Comment by Darkelfen** [comment]
In our imaginations many things can happen, don't be so cross and do as @Lemongrass3110  says, actually it would be a rather nice and useful suggestion for a custom mod.

**Comment by Everade** [comment]
@Darkelfen 
I've done as @Lemongrass3110 requested, i was never cross, but it seems there's happening a lot of things in our imaginations.

_One example_ for an entire missing official feature is the **UPDATE QUANTITY** button which is used on limited sales offered through the **official** kRO Shops. But who knows, maybe that button is just in my insane imagination.

It might not be a bug, the official cash shop simply has not been properly implemented (not entirely)

**Comment by MrAntares** [comment]
Wat. O_O
I just don't understand. What is missing and why are you mad at us? If there is something missing plz provide screenshots/videos/links to sources/smoke signs/anything, based on which we can start to work.
More details, less quarrel.

Thanks.

**Comment by Everade** [comment]
And all information required is stated above.
The update button is available on 2015 clients, i don't know if it was available before but very likely... yes.

![cashshop](https://cloud.githubusercontent.com/assets/12261601/15046589/db7003ee-12e0-11e6-8f6b-2a132d7cf671.png)



Like usualy, proper reports get closed before it's even being reviewed or being read entirely through.
I'm used to that and in some cases i can even understand it. It usualy happens if you don't write official in the biggest font available.

This time around i gave a normal answer after it has been closed (my second post)
And then a random person shows up and blames on me that i'm cross.

That's the point where i can become rude, because it's pissing me off.
So i'm not mad at the majority of people, just single persons as mister Darkelfen perfect above.


So please note:
I'm not the kind of person who adds a smilie after each smaller portion of text.

Wait a second
:D

See i'm a happy person now.

**Comment by cydh** [comment]
2015 client. makes sense if most of us don't know it (I'm still sticking with 2013-08-07).
So then, for u can get into kRO, can u see the cash item with quantity?

@Everade, that button, u're using GM account & sprites?

> @Lemongrass3110 , it is not possible to update the cash shop data after it was sent to the client

I think depends on client, other official clients 'resend' the cash list every you click it.
(but since we're using kRO, it doesn't matter :P)

**Comment by Everade** [comment]
@cydh 
It doesn't matter if you use a game master account, nor if your account id (clientinfo.xml) is set to game master sprite.

Also normal players (accounts) see the Update Quantity button.

**Comment by cydh** [comment]
Yeah, we only have 8 slots yet. Well, need more info for this... on official servers that implement this.

for 'weird' card slots, here's the SS from idRO. Client's oddity maybe. xDD
![screenmidgard033e](https://cloud.githubusercontent.com/assets/4016864/15092703/fec2b1ea-149b-11e6-9a7b-a3d19cea0b0c.jpg)

**Comment by psyzerkski** [comment]
Perhaps this is a missing feature on current cash shop system that's been causing random unknown packets?

**Comment by aleos89** [comment]
@psyzerkski: No. The disconnects have been boiled down to the messaging system and is being worked on. It's not related to this at all. If you notice the packet_db line @cydh quoted above we send 'dull' which is null info to keep the client from crashing.

**Comment by Everade** [comment]
Just noticed the following buttons inside the data.grf from KRO which are most likely used on a GM/Admin interface for the Cash Shop system?!

btn_additem.bmp
btn_deleteitem.bmp
![btn_additem](https://cloud.githubusercontent.com/assets/12261601/16265430/9d49395e-387f-11e6-913f-97d9d3e0b8e0.png)
![btn_deleteitem](https://cloud.githubusercontent.com/assets/12261601/16265424/9099750c-387f-11e6-9038-1011bea45f39.png)
