### ISSUE TITLE
Monster Target Change Crash Server

### ISSUE THREAD

**Issue by Vomaito** [rathena/rathena#1235]
Hi, well Testing with doram I Found an error when Doram get damage (or fight against some Mobs).
then server crash, how to reproduce? Use a Doram and spawn one ifrit (idk why only with ifrit get crash).
I already use a non-doram against ifrit and not crash. Thanks.
Please use a Doram with lot of HP or ahura mazda and wait the crash. I use the latest rA (30/april), thanks.

Edit:
Ifrit cast one skill, when bar cast is 100% green, server crash. Thanks.

Edit2: Testing I Think is Change Target, because only crash when two players are near to ifrit. Also this isn't a Doram Bug, is Mob Bug.

**Comment by Vomaito** [comment]
How to reproduce:
Need 2 players, attack ifrit at same time, or try that Change Target, only crash when change target and inmediatly use a Single Target Skill. Thanks

**Comment by Playtester** [comment]
So when the monster starts casting a skill you attack it with another character so it changes target during cast and then it crashes?

**Comment by Vomaito** [comment]
Yes, something like that! I don't know if cast first and then change or if change and then cast the only thing that I see is this:
Monster attack melee and skill player A, player B attacks monster, then monster stop fight with player A and start cast then map server crash.

I think is this because I use other mobs, like Kasa (thinking was a skill...) then BioLab 3 MvP.

It's hard to reproduce by only one person, if you need a Video I can upload tomorrow.

**Comment by aleos89** [comment]
I can't get it to crash. I've tried making Ifrit change targets and he did several times with 2 players on screen. I saw him cast multiple skills (with cast bars) and I didn't crash at any point.

If you could provide an accurate detail of how to cause the crash or provide a video that would be great!

**Comment by Vomaito** [comment]
@aleos89  @Playtester 
Link: 1 Player against ifrit
https://mega.nz/#!G59jwZCY!SIjX8jEF0otNACEz62pFpuurBvFmtuOePewCN3rbyF4

Link: 2 players against ifrit
https://mega.nz/#!T1s3FLIJ!DTzV7TOrFcfVdxrjIeWmvI_VF0WJVN4kwEry7qN9Q3M

I Hope you can helpme, also I quit my src formulas of Casting ( SRC conflicts were solve when update).

Log error:

> [Info]: @spawn monster='ifrit' name='--ja--' id=1832 count=1 (169,138)
[Error]: Server received crash signal! Attempting to save all online characters!
[Info]: Saved char 169124 - AlexMon: inventory status skills.
[Info]: Saved char 169201 - exp Doram: status status2 skills.

**Comment by Playtester** [comment]
Can you get the trace of the crash so we know at which line it crashes? Usually helps more than anything else.

**Comment by Vomaito** [comment]
@Playtester yes, how can I do? Sorry my ignorance.

**Comment by aleos89** [comment]
You'll need to install GDB if you're using Linux (https://rathena.org/wiki/GDB).

Once you've installed it, configure your rAthena with it:
```
./configure --enable-debug=gdb
make server
ulimit -c unlimited
```
You can then go and crash your server. You'll now see a core file in your rAthena directory.
```
gdb map-server map-server.core
```
It will load the core and present you with:
```
gdb>
```
From where you enter:
```
gdb> bt full
```
You will now get a print out of where the crash occurred. We need that bit of text.

**Comment by Vomaito** [comment]
Ok I try again (I have tried before send this commit following rA forum tutorial) but I have this error.

https://www.dropbox.com/s/7793afwp2vegcno/Archivo%2004-05-16%2011%2059%2020.jpeg?dl=0

Another way to download? I Use CentOs, maybe a mirror repository. And so thanks for the help.

**Comment by aleos89** [comment]
You need to update your mirrors. Just do that by:
`apt-get update`

**Comment by Vomaito** [comment]
@aleos89 yes I notice that but I get other error (same not found)
https://www.dropbox.com/s/unq71lfdepzb6xx/Archivo%2004-05-16%2012%2019%2015.jpeg?dl=0

**Comment by aleos89** [comment]
Make sure you are running with root privileges.

**Comment by Vomaito** [comment]
@aleos89 I have root access, but I think, it  is problem of debian.
http://http.debian.net/debian/pool/main/g/gdb/gdb-minimal_7.0.1-2+b1_i386.deb (doesn't exist 404)
and http://http.debian.net/debian/pool/main/g/gdb/gdb_7.0.1-2+b1_i386.deb
