### ISSUE TITLE
<ITEM> with 20151029 and 20151104

### ISSUE THREAD

**Issue by julia40124009** [rathena/rathena#1236]
client date 20151029
<a href="http://imgur.com/jobaDik"><img src="http://i.imgur.com/jobaDik.png" title="source: imgur.com" /></a>

client date 20151104
<a href="http://imgur.com/h58nHkF"><img src="http://i.imgur.com/h58nHkF.png" title="source: imgur.com" /></a>

idk is a client problen or core packet problem 

mode : renewal

**Comment by Lemongrass3110** [comment]
Looks like a clientside issue to me.
If it does not get better with a newer client we will have to look deeper into it.

Here's the script if someone wants to try:
```
prontera,116,252,4	script	testscript	430,{
	mes "show item link<ITEM>Yggdrasilberry<INFO>607</INFO></ITEM>";
	close;
}
```

**Comment by admkakaroto** [comment]
It worked ... but ... looks like it was strange: http://i.imgur.com/zT3KTYC.png

**Comment by darknessfmy** [comment]
Yes, have error.
I confirm this issue.

**Comment by darknessfmy** [comment]
@aleos89

**Comment by aleos89** [comment]
This isn't something related to rAthena. I just tested as well and I got the same results. I would probably think maybe Nemo could possibly make a diff to resolve this.

**Comment by darknessfmy** [comment]
Ok
