### ISSUE TITLE
Battlegrounds Cursor Problem

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#1240]
There's an issue with the mouseover enemy in battlegrounds.
**You can only attack the enemy if you hold Shift or activate /noshift**

I know there was a fix related to this back in 2014, and i'm not sure if this may be related to it.

Can anyone confirm this?

**Comment by Everade** [comment]
bump

**Comment by aleos89** [comment]
What is your client date?

**Comment by icxbb-xx** [comment]
@aleos89 i can confirm this

please read old issues, that same problem

https://rathena.org/board/tracker/issue-9350-allied-guilds-attacksword-cursor-in-gvg/

problem with clif_maptypeproperty2

**Comment by aleos89** [comment]
Ah, ok thanks Napster!

**Comment by Everade** [comment]
Using 2015-09-16aRagexe

**Comment by Everade** [comment]
@aleos89 

Looking forward to a fix.
Battlegrounds is kind of a core end-content feature (repeatable and for max level players very interesting)

Not being able to attack your opponents is kind of a big deal.
As a lot of players are simply not aware or being annoyed to be forced to hold shift.

**Comment by aleos89** [comment]
So I did some testing using 2015-10-29aRagexe (Non-RE client). I enabled and disabled the /ns command and in both instances I got the sword to attack the enemy team. I didn't have to enable /ns and hold shift to attack the enemy team.

**Comment by Everade** [comment]
@icxbb-xx 
Are you **also** using the Battlegrounds Mod from Zephyrus?

I've re-tested everything today, the problem still persists.

**Comment by secretdataz** [comment]
I've tested the BG on various exes. I don't have to hold hold shift or enable /ns to get the sword cursor.
@Everade custom BG mod is not supported by us.

**Comment by Everade** [comment]
@secretdataz 
I know, that's why i'm asking so i know the actual cause for my issue.
