### ISSUE TITLE
map crashed - Skill ID 368  PA_SACRIFICE, Martyr's Reckoning  [ Sacrifice ]

### ISSUE THREAD

**Issue by lelouchzx** [rathena/rathena#1244]
Use skill in the mob and map-server crash.

git hash: 55165ac0bfce710399ffea9b0c62aefc4904cd3c
Client: 2015-11-04
mode: Renewal

![sacrifice](https://cloud.githubusercontent.com/assets/19214049/15058295/c86967fc-12f1-11e6-8974-62c2fc91ed42.JPG)

**Comment by Lemongrass3110** [comment]
Could you please give us your git hash?
Also please share the monster and monster skill entries you are crashing on.
By default no monster has this skill.
Thank you.

**Comment by lelouchzx** [comment]
git hash: 55165ac0bfce710399ffea9b0c62aefc4904cd3c
Client: 2015-11-04
mode: Rathena

It is when using the skill sacrifice, no matter the monster.

*sorry my bad english X.X

**Comment by Lemongrass3110** [comment]
@aleos89 and I could not reproduce your issue on the hash you specified.

Please provide your monster code and or more details. Might even be due to certain equipment you are wearing.

**Comment by lelouchzx** [comment]
I'm not using any equipment.

Ex: @monster poring

when I used the skill in poring happened crash map.

![sacrifice2](https://cloud.githubusercontent.com/assets/19214049/15060140/50bf53ee-12fe-11e6-88b6-c66cab18f378.JPG)

**Comment by admkakaroto** [comment]
Sure you had no errors when downloaded rathena? or when compiled? I tested and could not reproduce this problem too.

**Comment by spinzaku** [comment]
Can't reproduce.. works for me.. used sacrifice many times then attacked a poring no crash..

**Comment by lelouchzx** [comment]
was a a problem on my compilie, solved, thanks
