### ISSUE TITLE
signum crusis not working

### ISSUE THREAD

**Issue by joelolopez** [rathena/rathena#1246]
signum crusis not working..im using 17071, and 2015-11-04aRagexe

tested on zombie monster
physical attack isnt improving on undead (undead monster's def isnt decreasing) after casting signum crusis

**Comment by RadianFord** [comment]
works wiith this hash : 0c09928dd3ea75f7be745da9e87fec0cfb4b87f1 running it pre renewal mode.

This images is without Signum Crusis
![screenrathena004](https://cloud.githubusercontent.com/assets/9658425/15079938/52de1698-1370-11e6-9949-c2ee318e73c9.jpg)

this one is with Signum Crusis
![screenrathena005](https://cloud.githubusercontent.com/assets/9658425/15079944/5df338b0-1370-11e6-813b-e72780d6c35b.jpg)

**Comment by Playtester** [comment]
If you tested with "Zombie" monster, it is worth noting that Zombie has 0 DEF in the first place.

**Comment by joelolopez** [comment]
0 def,... well if thats the case lets close this aheheh sorry
