### ISSUE TITLE
devotion behavior

### ISSUE THREAD

**Issue by joelolopez** [rathena/rathena#1247]
when in devotion with the party , party doesnt receive any damage from physical attacks, but they receive damage from magic spells..does the behvior correct? if not please fix. im using 17071, and 2015-11-04aRagexe

**Comment by RadianFord** [comment]
You must be referring into this?

> // Using 'old' behavior for devotion vs reflect damage? (Note 2)
> // Default is 0 (official). If 'devotion_rdamage' is > 0 (chance to devote the reflected damage),
> // when player with devotion attacks player with reflect damage ability (item bonus or skill),
> // the damage will be taken by the person who provides devotion instead the attacker.
> devotion_rdamage: 0
> 
> // Officially, reflecting shield (SC_REFLECTDAMAGE) reflects physical damage by skill or normal attack.
> // But if the target is being devoted, it ONLY reflects the damage for melee skill. (Note 1)
> devotion_rdamage_skill_only: yes

**Comment by aleos89** [comment]
As @RadianFord quoted from the configurations.
