### ISSUE TITLE
compile error 17121 - 2010 expres

### ISSUE THREAD

**Issue by iriyoka** [rathena/rathena#1254]
please help i'm using 17121 and compile with 2010 expres 

`1>G:\SVN\Ra17121\src\map\path.c(336): error C2143: syntax error : missing ';' before 'type'
1>G:\SVN\Ra17121\src\map\path.c(337): error C2143: syntax error : missing ';' before 'type'
1>G:\SVN\Ra17121\src\map\path.c(338): error C2143: syntax error : missing ';' before 'type'
1>G:\SVN\Ra17121\src\map\path.c(339): error C2143: syntax error : missing ';' before 'type'
1>G:\SVN\Ra17121\src\map\path.c(340): error C2143: syntax error : missing ';' before 'type'
1>G:\SVN\Ra17121\src\map\path.c(341): error C2143: syntax error : missing ';' before 'type'
1>G:\SVN\Ra17121\src\map\path.c(343): error C2065: 'tp' : undeclared identifier

1>G:\SVN\Ra17121\src\map\path.c(343): warning C4022: 'memset' : pointer mismatch for actual parameter 1
1>G:\SVN\Ra17121\src\map\path.c(343): error C2065: 'tp' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(347): error C2065: 'tp' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(347): error C2109: subscript requires array or pointer type
1>G:\SVN\Ra17121\src\map\path.c(348): error C2065: 'tp' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(348): error C2109: subscript requires array or pointer type
1>G:\SVN\Ra17121\src\map\path.c(349): error C2065: 'tp' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(349): error C2109: subscript requires array or pointer type
1>G:\SVN\Ra17121\src\map\path.c(350): error C2065: 'tp' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(350): error C2109: subscript requires array or pointer type
1>G:\SVN\Ra17121\src\map\path.c(351): error C2065: 'tp' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(351): error C2109: subscript requires array or pointer type
1>G:\SVN\Ra17121\src\map\path.c(352): error C2065: 'tp' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(352): error C2109: subscript requires array or pointer type
1>G:\SVN\Ra17121\src\map\path.c(354): error C2065: 'tp' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(354): error C2109: subscript requires array or pointer type
1>G:\SVN\Ra17121\src\map\path.c(354): error C2198: 'heap_push_node' : too few arguments for call
1>G:\SVN\Ra17121\src\map\path.c(373): error C2065: 'current' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(373): warning C4047: '=' : 'int' differs in levels of indirection from 'path_node *'
1>G:\SVN\Ra17121\src\map\path.c(376): error C2065: 'current' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(376): error C2223: left of '->x' must point to struct/union
1>G:\SVN\Ra17121\src\map\path.c(377): error C2065: 'current' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(377): error C2223: left of '->y' must point to struct/union
1>G:\SVN\Ra17121\src\map\path.c(378): error C2065: 'current' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(378): error C2223: left of '->g_cost' must point to struct/union
1>G:\SVN\Ra17121\src\map\path.c(380): error C2065: 'current' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(380): error C2223: left of '->flag' must point to struct/union
1>G:\SVN\Ra17121\src\map\path.c(386): error C2065: 'ys' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(388): error C2065: 'xs' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(394): error C2065: 'tp' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(394): warning C4047: 'function' : 'path_node *' differs in levels of indirection from 'int'
1>G:\SVN\Ra17121\src\map\path.c(394): warning C4024: 'add_path' : different types for formal and actual parameter 2
1>G:\SVN\Ra17121\src\map\path.c(394): error C2065: 'current' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(394): warning C4047: 'function' : 'path_node *' differs in levels of indirection from 'int'
1>G:\SVN\Ra17121\src\map\path.c(394): warning C4024: 'add_path' : different types for formal and actual parameter 6
1>G:\SVN\Ra17121\src\map\path.c(396): error C2065: 'tp' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(396): warning C4047: 'function' : 'path_node *' differs in levels of indirection from 'int'
1>G:\SVN\Ra17121\src\map\path.c(396): warning C4024: 'add_path' : different types for formal and actual parameter 2
1>G:\SVN\Ra17121\src\map\path.c(396): error C2065: 'current' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(396): warning C4047: 'function' : 'path_node *' differs in levels of indirection from 'int'
1>G:\SVN\Ra17121\src\map\path.c(396): warning C4024: 'add_path' : different types for formal and actual parameter 6
1>G:\SVN\Ra17121\src\map\path.c(398): error C2065: 'tp' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(398): warning C4047: 'function' : 'path_node *' differs in levels of indirection from 'int'
1>G:\SVN\Ra17121\src\map\path.c(398): warning C4024: 'add_path' : different types for formal and actual parameter 2
1>G:\SVN\Ra17121\src\map\path.c(398): error C2065: 'current' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(398): warning C4047: 'function' : 'path_node *' differs in levels of indirection from 'int'
1>G:\SVN\Ra17121\src\map\path.c(398): warning C4024: 'add_path' : different types for formal and actual parameter 6
1>G:\SVN\Ra17121\src\map\path.c(400): error C2065: 'tp' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(400): warning C4047: 'function' : 'path_node *' differs in levels of indirection from 'int'
1>G:\SVN\Ra17121\src\map\path.c(400): warning C4024: 'add_path' : different types for formal and actual parameter 2
1>G:\SVN\Ra17121\src\map\path.c(400): error C2065: 'current' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(400): warning C4047: 'function' : 'path_node *' differs in levels of indirection from 'int'
1>G:\SVN\Ra17121\src\map\path.c(400): warning C4024: 'add_path' : different types for formal and actual parameter 6
1>G:\SVN\Ra17121\src\map\path.c(402): error C2065: 'tp' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(402): warning C4047: 'function' : 'path_node *' differs in levels of indirection from 'int'
1>G:\SVN\Ra17121\src\map\path.c(402): warning C4024: 'add_path' : different types for formal and actual parameter 2
1>G:\SVN\Ra17121\src\map\path.c(402): error C2065: 'current' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(402): warning C4047: 'function' : 'path_node *' differs in levels of indirection from 'int'
1>G:\SVN\Ra17121\src\map\path.c(402): warning C4024: 'add_path' : different types for formal and actual parameter 6
1>G:\SVN\Ra17121\src\map\path.c(404): error C2065: 'tp' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(404): warning C4047: 'function' : 'path_node *' differs in levels of indirection from 'int'
1>G:\SVN\Ra17121\src\map\path.c(404): warning C4024: 'add_path' : different types for formal and actual parameter 2
1>G:\SVN\Ra17121\src\map\path.c(404): error C2065: 'current' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(404): warning C4047: 'function' : 'path_node *' differs in levels of indirection from 'int'
1>G:\SVN\Ra17121\src\map\path.c(404): warning C4024: 'add_path' : different types for formal and actual parameter 6
1>G:\SVN\Ra17121\src\map\path.c(406): error C2065: 'tp' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(406): warning C4047: 'function' : 'path_node *' differs in levels of indirection from 'int'
1>G:\SVN\Ra17121\src\map\path.c(406): warning C4024: 'add_path' : different types for formal and actual parameter 2
1>G:\SVN\Ra17121\src\map\path.c(406): error C2065: 'current' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(406): warning C4047: 'function' : 'path_node *' differs in levels of indirection from 'int'
1>G:\SVN\Ra17121\src\map\path.c(406): warning C4024: 'add_path' : different types for formal and actual parameter 6
1>G:\SVN\Ra17121\src\map\path.c(408): error C2065: 'tp' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(408): warning C4047: 'function' : 'path_node *' differs in levels of indirection from 'int'
1>G:\SVN\Ra17121\src\map\path.c(408): warning C4024: 'add_path' : different types for formal and actual parameter 2
1>G:\SVN\Ra17121\src\map\path.c(408): error C2065: 'current' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(408): warning C4047: 'function' : 'path_node *' differs in levels of indirection from 'int'
1>G:\SVN\Ra17121\src\map\path.c(408): warning C4024: 'add_path' : different types for formal and actual parameter 6
1>G:\SVN\Ra17121\src\map\path.c(415): error C2065: 'it' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(415): error C2065: 'current' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(415): error C2065: 'it' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(415): error C2223: left of '->parent' must point to struct/union
1>G:\SVN\Ra17121\src\map\path.c(415): error C2065: 'it' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(415): error C2065: 'it' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(415): error C2223: left of '->parent' must point to struct/union
1>G:\SVN\Ra17121\src\map\path.c(415): error C2065: 'len' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(416): error C2065: 'len' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(420): error C2065: 'len' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(423): error C2065: 'it' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(423): error C2065: 'current' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(423): error C2065: 'j' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(423): error C2065: 'len' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(423): error C2065: 'j' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(423): error C2065: 'it' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(423): error C2065: 'it' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(423): error C2223: left of '->parent' must point to struct/union
1>G:\SVN\Ra17121\src\map\path.c(423): error C2065: 'j' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(424): error C2065: 'it' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(424): error C2223: left of '->x' must point to struct/union
1>G:\SVN\Ra17121\src\map\path.c(424): error C2065: 'it' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(424): error C2223: left of '->parent' must point to struct/union
1>G:\SVN\Ra17121\src\map\path.c(425): error C2065: 'it' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(425): error C2223: left of '->y' must point to struct/union
1>G:\SVN\Ra17121\src\map\path.c(425): error C2065: 'it' : undeclared identifier
1>G:\SVN\Ra17121\src\map\path.c(425): error C2223: left of '->parent' must point to struct/union
1>G:\SVN\Ra17121\src\map\path.c(426): error C2065: 'j' : undeclared identifier`

**Comment by exneval** [comment]
because of 0da7136

**Comment by secretdataz** [comment]
tbh older versions of Visual Studio support should be dropped.

**Comment by Lemongrass3110** [comment]
Fixed in c4390e5.
Messed up the commit message, sorry.

**Comment by keitenai** [comment]
@secretdataz i hope not. comparing with newer VS versions, i would still use 2010. It's faster to compile and recompile with 2010.
