### ISSUE TITLE
char.c (max_started_items) iterator bug? 

### ISSUE THREAD

**Issue by anacondaqq** [rathena/rathena#1256]
Look:  https://github.com/rathena/rathena/blob/master/src/char/char.c#L1534
Is it wrong? 

> for (k = 0; k <= MAX_STARTITEM && tmp_start_items[k].nameid != 0; k ++) {

as you see **"k ++"**

**Comment by secretdataz** [comment]
Uh well, it does work but the whitespace annoys me too.

**Comment by Lemongrass3110** [comment]
This is not really a bug, but as @secretdataz said I totally understand you too, so I will fix it up.
