### ISSUE TITLE
Server Crashing

### ISSUE THREAD

**Issue by GaChittolina** [rathena/rathena#1258]
My server is crashing constantly. It looks like it happens when anyone receives a debuff (a player receiving Hallucination, for example), but I can't tell if that's the main reason.
I'm using pre-renewal, packetver 20100730.
GDB output:
> Program received signal SIGSEGV, Segmentation fault.
> 0x0816dde1 in battle_calc_damage (src=0xaa76f9ac, bl=0xcde1968, d=0xbffff434,
>     damage=1, skill_num=0, skill_lv=0) at battle.c:573
> 573                                                     if(sce->val2)//Checagem de Mvps[Sicks]
> Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.149.el6.i686 keyutils-libs-1.4-5.el6.i686 krb5-libs-1.10.3-33.el6.i686 libcom_err-1.41.12-21.el6.i686 libselinux-2.0.94-5.8.el6.i686 mysql-libs-5.1.73-3.el6_5.i686 nss-softokn-freebl-3.14.3-18.el6_6.i686 openssl-1.0.1e-30.el6_6.4.i686 pcre-7.8-6.el6.i686 zlib-1.2.3-29.el6.i686
> [Error]: Server received crash signal! Attempting to save all online characters!
> [Info]: Saved char 150002 - Gabriel: status.
> (gdb) continue
> Continuing.
> Program received signal SIGSEGV, Segmentation fault.
> 0x0816dde1 in battle_calc_damage (src=0xaa76f9ac, bl=0xcde1968, d=0xbffff434,
>     damage=1, skill_num=0, skill_lv=0) at battle.c:573
> 573                                                     if(sce->val2)//Checagem de Mvps[Sicks]
>

**Comment by aleos89** [comment]
Looking through your dump I see this:
`573 if(sce->val2)//Checagem de Mvps[Sicks]`

That doesn't exist in rAthena, so it looks like you have custom code that is causing the crash.

**Comment by GaChittolina** [comment]
@aleos89 I found out that I had to disable renewal at src/config/renewal.h, so It's working now, but I've got some error reports about mobs and items:

> [Error]: npc_parse_mob: Unknown mob ID 2198 (file 'npc/monstros/cavernas/iz_dun.txt', line '101').
[Error]: npc_parse_mob: Unknown mob ID 2201 (file 'npc/monstros/cavernas/iz_dun.txt', line '102').
[Error]: npc_parse_mob: Unknown mob ID 2203 (file 'npc/monstros/cavernas/iz_dun.txt', line '103').
[Error]: npc_parse_mob: Unknown mob ID 2204 (file 'npc/monstros/cavernas/iz_dun.txt', line '104').
[Error]: npc_parse_mob: Unknown mob ID 2202 (file 'npc/monstros/cavernas/iz_dun.txt', line '105').
[Warning]: npc_parse_shop: Invalid sell item in file 'npc/comerciantes/shops.txt', line '326' (id '2139').
[Warning]: npc_parse_shop: Invalid sell item in file 'npc/comerciantes/shops.txt', line '326' (id '2800').
[Warning]: npc_parse_shop: Invalid sell item in file 'npc/comerciantes/shops.txt', line '326' (id '2801').
[Warning]: npc_parse_shop: Invalid sell item in file 'npc/comerciantes/shops.txt', line '326' (id '2802').
[Warning]: npc_parse_shop: Invalid sell item in file 'npc/comerciantes/shops.txt', line '326' (id '2803').
[Warning]: npc_parse_shop: Invalid sell item in file 'npc/comerciantes/shops.txt', line '326' (id '2804').
[Warning]: npc_parse_shop: Invalid sell item in file 'npc/comerciantes/shops.txt', line '326' (id '2805').
[Warning]: npc_parse_shop: Invalid sell item in file 'npc/comerciantes/shops.txt', line '326' (id '2806').
[Warning]: npc_parse_shop: Invalid sell item in file 'npc/comerciantes/shops.txt', line '326' (id '2807').
[Warning]: npc_parse_shop: Invalid sell item in file 'npc/comerciantes/shops.txt', line '326' (id '2808').

**Comment by aleos89** [comment]
Those errors are because you're using renewal monster spawns/item scripts while using pre-renewal monster/item databases which don't contain those IDs.
