### ISSUE TITLE
create deadly poison

### ISSUE THREAD

**Issue by joelolopez** [rathena/rathena#1260]
when making deadly poison (EDP), creation cool down is very long  for each bottle is it normal? .im using 17071, and 2015-11-04aRagexe

**Comment by RadianFord** [comment]
I am using r 17117 and it is working fine for me.

**Comment by aleos89** [comment]
On hash ca049a6, these are the values for EDP:
RE:
```
378,0,2000,0,40000:45000:50000:55000:60000,20000:30000:40000:50000:60000,0,0
```
Pre-re:
```
378,0,2000,0,40000:45000:50000:55000:60000,20000:30000:40000:50000:60000,0
```

There is no cooldown set for either mode.

**Comment by joelolopez** [comment]
no cool down? but why doest it taking too long to reuse the skill, i think 3~4 secs before you can use it again if im not mistaken.

**Comment by aleos89** [comment]
There is a 2 second after cast act delay, which means no cast of any skills. Not sure where you are getting 3-4 seconds.

**Comment by aleos89** [comment]
Sorry, I just realized you meant Create Deadly Poison:
```
407,0,5000,0,0,0,0,0
```
This is the official delay of the skill.
