### ISSUE TITLE
Exceed break + Vellum kabz drain 100% HP

### ISSUE THREAD

**Issue by Vomaito** [rathena/rathena#1262]
vellum kabz has a bug when use Exceed break, how to reproduce:
Go pvp with Royal Guard with vellum kabz.
Using: lastest version renewal and 20151029 client.

**Comment by aleos89** [comment]
I've confirmed it on rA but I just need to get some info from officials to make sure it's ignored (which it most likely is).

**Comment by RagnarokNova** [comment]
Confirmed. An autoattack uses up the Exceed Break buff, but the damage remains the same.
Exceed Break should not affect Vellum Katz damage.
