### ISSUE TITLE
Some items on item_db updates.

### ISSUE THREAD

**Issue by Vomaito** [rathena/rathena#1265]
Hi, well I notice that some items, have a wrong script according to divine-pride:

2979:StrawBerry Decoration (http://www.divine-pride.net/database/item/2979/strawberry-decoration)
Works in combo with Tasty_Strawberry_Hat (ID: 18852)
In item_db.txt
`-2979,Strawberry_Decoration,Strawberry Decoration,4,0,,500,,1,,1,0xFFFFFFFF,63,2,136,,,0,,{ bonus bAllStats,1; bonus2 bSubEle,Ele_Fire,10; bonus bLongAtkRate,30; bonus3 bAutoSpellWhenHit,"WZ_FROSTNOVA",3,10; /* Confirm: Frost Nova cast chance */ },{},{}
+2979,Strawberry_Decoration,Strawberry Decoration,4,0,,500,,1,,0,0xFFFFFFFF,63,2,136,,,0,,{ bonus bAllStats,1;},{},{}
`
Then add:
`+18852,Tasty_Strawberry_Hat,Tasty Strawberry Hat,4,20,,1500,,4,,0,0xFFFFFFFF,63,2,256,,30,1,968,{ bonus bAllStats,1; if(getrefine()>=10){ bonus bAspd,2;}},{},{}
`

on item_combo_db.txt
`+18852:2979,{ bonus2 bSubEle,Ele_Fire,10; bonus bLongAtkRate,30; bonus3 bAutoSpellWhenHit,"WZ_FROSTNOVA",3,10; /* Confirm: Frost Nova cast chance */ }
`
Acording to Description pattern is:
This: Item Efect,
when equiped with X:
Combo effect, combo effect,...

More info: https://forums.warpportal.com/index.php?/topic/175998-pro-items-in-april-27-patch/page-2

2190 Ancient Shield of Aeon:
On item Db has 1 slot but http://www.divine-pride.net/database/item/2190/ancient-shield-of-aeon
so 
`-2190,Ancient_Shield_Of_Aeon,Ancient Shield Of Aeon,4,0,,200,,5,,1,0x000FDF80,63,2,32,,130,1,2,{ bonus2 bSubEle,Ele_Neutral,10; bonus2 bSubEle,Ele_Fire,10; bonus2 bSubEle,Ele_Water,10; bonus2 bSubEle,Ele_Wind,10; bonus2 bSubEle,Ele_Earth,10; bonus2 bSubEle,Ele_Dark,10; bonus2 bSubEle,Ele_Holy,10; bonus2 bSubEle,Ele_Ghost,10; bonus bMaxHP,500; bonus bMaxSP,50; if(getrefine()>=14) skill "MG_STONECURSE",5; },{},{}
`

`+2190,Ancient_Shield_Of_Aeon,Ancient Shield Of Aeon,4,0,,200,,5,,0,0x000FDF80,63,2,32,,130,1,2,{ bonus2 bSubEle,Ele_Neutral,10; bonus2 bSubEle,Ele_Fire,10; bonus2 bSubEle,Ele_Water,10; bonus2 bSubEle,Ele_Wind,10; bonus2 bSubEle,Ele_Earth,10; bonus2 bSubEle,Ele_Dark,10; bonus2 bSubEle,Ele_Holy,10; bonus2 bSubEle,Ele_Ghost,10; bonus bMaxHP,500; bonus bMaxSP,50; if(getrefine()>=14) skill "MG_STONECURSE",5; },{},{}
`
same with 2176: http://www.divine-pride.net/database/item/2176/dark-book

`-2176,Dark_Book,Black Book,4,20,,500,,80,,1,0xFFFFFFFF,63,2,32,,65,1,5,{ bonus bMdef,5; .@r = getrefine(); bonus3 bAutoSpellWhenHit,"NPC_DRAGONFEAR",1,(.@r<=6)?(10):((.@r<=8)?(20):(30)); },{},{}`

`+2176,Dark_Book,Black Book,4,20,,500,,80,,0,0xFFFFFFFF,63,2,32,,65,1,5,{ bonus bMdef,5; .@r = getrefine(); bonus3 bAutoSpellWhenHit,"NPC_WIDESTUN",(.@r<=6)?(1):((.@r<=8)?(2):(3)),(.@r<=6)?(10):((.@r<=8)?(20):(30)); },{},{}
`

Thanks

**Comment by spinzaku** [comment]
also http://www.divine-pride.net/database/item/18934

current re/item db doesn't have card slot.

**Comment by secretdataz** [comment]
Reopen for the Shield of Aeon issue
