### ISSUE TITLE
Hide Related Skill on dispel

### ISSUE THREAD

**Issue by breaker7** [rathena/rathena#1266]
Cloaking/Chasewalk/Invisibility/CloakExceed and other related to hide skills:
On official server, the Cloaking/Chasewalk and other related to hide skills is immune to Dispel, meaning the character being targeted will not unhide when Dispel is casted upon.

Hide Skill - Dispel:
In official server, the Hide skill is immune to Dispel, but even if you have successfully use HIDE before the cast time of DISPEL ended, your buffs or you will still be dispelled.
 
Official dispell
http://youtube.com/watch?v=GHUf82caj40

rAthena dispell
http://youtube.com/watch?v=K9BF1h8XUlI

**Comment by anacondaqq** [comment]
@breaker7 Hi! Where did you test it? I mean on which official server?

**Comment by breaker7** [comment]
@anacondaqq im not tested, because i`m not playing official server
but many player in my server tell me like that

**Comment by aleos89** [comment]
Confirmed it not clearing statuses while hidden on rAthena and confirmed that it should be removed on kRO.
