### ISSUE TITLE
Damage dealing status effects

### ISSUE THREAD

**Issue by MrAntares** [rathena/rathena#1267]
This issue was fixed several times, but it's still broken.

**How it should work:**
Damage dealing status effects like poison, bleeding, burning, pertification, etc should be considered the player's damage who dealt it, so it should give full exp after the mob dies. Damage dealt this way, should not trigger party/attacker exp bonus.

**How it is now:**
Monsters killed by Leech End don't give any exp at all. (It should give 100%)
Monsters damaged by Leech End, but finished by player give partial exp. (It should give 100%)

Monster affected by poison, and killed after poison ends give 100% exp (this is okay)

Monster affected by poison, and killed while poisoned give 100%exp + attacker bonus exp (there shouldn't be attacker exp bonus, since this should be your damage)

Burning also triggers attacker bonus exp

Renewal
Version 2016-May-15
717eb225ba17f5841df2d12d7ff0ca7ce20450cd

**Comment by Playtester** [comment]
Invalid report. It now works as on official servers.

Read here: https://github.com/rathena/rathena/commit/a6f73a6227bc9158127a7544acdb27acbfdc9651
