### ISSUE TITLE
[BUG]  Champions Monster OnNPCKillEvent: erro check

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#1271]
No monster champion is working with the script: ( OnNPCKillEvent: ).

- Example:

-	script	killevent	-1,{
end;
OnNPCKillEvent:
announce "----Test----",0;
end;
}

- By eliminating type monsters champion is not working the check instruction.
- Test ID monster:  (2603 ~ 2903)

It does not work with any of these IDs.

**Comment by aleos89** [comment]
There's no reason that the label would just not work for a specific range of mobs. There are no mob ID checks for labels.

It's probably wise to check and make sure you have no other scripts running OnNPCKillEvent. Your server should only need 1 and you can run the checks you need within that one event. It's likely you have an event already defined and it's restricting you.
