### ISSUE TITLE
Rebellion weapon bug

### ISSUE THREAD

**Issue by Yuchinin** [rathena/rathena#1272]
* Item 28201 28202(Southern Cross) cant be worn by Rebellion even with baselevel 160
* item 13190 13195(RAG203) used decrease agility on self instead of attacking target(should set the target bitmask to 1 [Enemy] instead of 0 [Self])

**Comment by secretdataz** [comment]
- Item 28201 28202(Southern Cross) cant be worn by Rebellion even with baselevel 160  
     Can't reproduce on renewal mode.
- Item 13190 13195(RAG203) used decrease agility on self instead of attacking target(should set the target bitmask to 1 [Enemy] instead of 0 [Self])  
     Confirmed.

**Comment by Yuchinin** [comment]
- Item 28201 28202(Southern Cross) cant be worn by Rebellion even with baselevel 160
I can't worn it in renewal.

**Comment by secretdataz** [comment]
I can't really reproduce this. I even imitated your condition (GM99, Female, Rebel, Lv.160).
Git hash : 19f2bc597
![image](https://cloud.githubusercontent.com/assets/2021243/15446488/d9d1095c-1f4c-11e6-9f90-7ca6ac1bb296.png)
![image](https://cloud.githubusercontent.com/assets/2021243/15446511/7eb876bc-1f4d-11e6-9954-97421ec4a9b4.png)

**Comment by spinzaku** [comment]
Works for m
![rebel160](https://cloud.githubusercontent.com/assets/18629476/15446543/be6c2084-1f56-11e6-8d63-853541ba55b8.png)
e also

**Comment by Yuchinin** [comment]
I am using latest rA
Strange...for me it keep saying 
'Forbidden to wear the state can not be worn.'
Hmm...I wonder what can cause this

**Comment by RadianFord** [comment]
@Yuchinin its a grenade launcher weapons use bullet sphere's
