### ISSUE TITLE
CD in Mouth Item #18666 Fix

### ISSUE THREAD

**Issue by spinzaku** [rathena/rathena#1274]
Currently CD in Mouth ability doesn't work:
Item #18666 
`While attacking has a 6% chance of activating for 5 seconds a random level 1-5 [Fire Bolt] [Cold Bolt] [Lightning Bolt] [Earth Spike] or [Soul Strike] on your target.`

http://www.divine-pride.net/database/item/18666/cd-in-mouth

Just add this code to make it work:
`bonus4 bAutoSpell,"MG_FIREBOLT",5,60,3; bonus4 bAutoSpell,"MG_COLDBOLT",5,60,3;  bonus4 bAutoSpell,"MG_LIGHTNINGBOLT",5,60,3; bonus4 bAutoSpell,"WZ_EARTHSPIKE",5,60,3;  bonus4 bAutoSpell,"MG_SOULSTRIKE",5,60,3;`

Thank you to @secretdataz

**Comment by secretdataz** [comment]
**Disclaimer** : The script that I provided is not official behavior and should not be merged into the project.

**Comment by spinzaku** [comment]
@secretdataz its better compared to the current "blank" script. but that's my opinion thou.

**Comment by Darkelfen** [comment]
That effect does not apply to all official servers, if am not mistaken kRo one doesn't work like that,

**Comment by spinzaku** [comment]
Item also needs to be equipped by everyone. Current ITEM DB RE -> Super Novices can't equip it.

**Comment by reigneil** [comment]
well if we look at it on kRO iteminfo.lub it doesn't exist.
also judging it using that item description tells us that all bolts must be inside the autobonus script.
using this on iRO feels like autobonus script.

**Comment by reigneil** [comment]
also noted that it is random level of bolts to cast.

**Comment by Akkarinage** [comment]
This still doesn't exist in kRO's itemInfo - perhaps we could give it iRO's item effect but leave it commented out in the db?

**Comment by aleos89** [comment]
This was added in a599264.
