### ISSUE TITLE
About some Bow´s

### ISSUE THREAD

**Issue by darknessfmy** [rathena/rathena#1276]
Hi there, i was checking some items when i notice that i cant equip some bow, no just one, there are some of them, i start checking the Ixion Bow:
i try modify the Job but that isnt work: 0x00000800 this is for hunter.
1737,Ixion_Wing,Ixion Wings,5,20,,300,135,,5,1,0x00000800,18,2,34,4,70,1,11,{},{},{}
then just for check, i but the code of other bow that i can equip:
1742,N_Composite_Bow,Novice Composite Bow,5,1,,0,49,,5,3,0x000A0848,63,2,34,1,4,0,11,{},{},{}

And yup thats work, how i said is not the only one, these are a few i found with the same error:
1745,Falken_Blitz,Falken Blitz
1741,Cursed_Lyre,Cursed Lyre
1740,Nepenthes_Bow,Nepenthes Bow
1736,Double_Bound,Double Bound
1737,Ixion_Wing,Ixion Wings

well thats all, by the way i try changing my job and that isnt work to, thank you.

**Comment by cydh** [comment]
Those bows are correct, `0x00000800,18` means for Trans-Hunter jobs.
1736,Double_Bound -> Sniper (Ranger as well)
1737,Ixion_Wing -> Sniper (Ranger as well)
1740,Nepenthes_Bow -> Sniper (Ranger as well)
1741,Cursed_Lyre -> ~~High Archer,~~ Sniper, Clown, Gypsy  (Ranger, Minstrel, and Wanderer as well)
1745,Falken_Blitz -> Sniper (Ranger as well)
