### ISSUE TITLE
Killedrid on special Labels

### ISSUE THREAD

**Issue by Stolao** [rathena/rathena#1278]
recently i was making a script that needed had many monsters with on death event label, trying to reduce server needs i didn't use OnNPCKillEvent but instead made the mobs use OnKillTestEvent: which i attached to every mob manually.

when killing the mob it i notice the check for killedrid was not working

so i tested with

```
OnKillTestEvent:
	message strcharinfo(0),"Target "+ Target +" vs Killed "+killedrid;
end;
```

and it returned 

`Target 1002 vs Killed 0`

then when i killed a BigFoot then killed a special mob again i revived this

`Target 1002 vs Killed 1060`

**Comment by Yuchinin** [comment]
Hmm... to what I know, monster spawn with event label attached on it will not get registered on the killedrid when it get killed, only monster with no event label attached will get registered on the killedrid.

**Comment by Stolao** [comment]
Yes in my eyes i see that as a bug, it makes the creation of dynamic on kill labels impractical or overly server intensive by using OnNpcKillEvent:

While there are workaround by making different labels per mobid then returning the mobid to a call function to the original intended label that impractical for truly dynamic effects. Its kinda like before implementing pointshop we can do a work around its more of why not just improve the code to allow more flexibility.

Unless there is a reason we don't want to retun killedrid on special labels i don't see why we shouldnt

**Comment by Jeybla** [comment]
I think this isn't implemented due to the fact that you mostly spawn a certain monstertype or just use another event label for different monster types.

But I think it's a good idea, Stolao.
