### ISSUE TITLE
Issue with job_db1.txt

### ISSUE THREAD

**Issue by RadianFord** [rathena/rathena#1280]
Rev : 17117
Mode : Pre renewal
Max Base Level : 300 expanded / 255 for trans

Hi please correct me if im wrong but I did try to change the settings on my job_db1.txt

I tried changing this
`24,	28000,89   ,  0  ,469  ,500  ,2000, 2000, 2000, 2000, 2000, 2000 ,2000 ,2000 ,2000 ,2000 ,2000 ,2000 ,2000 ,2000 ,2000 ,2000 , 700 , 750 , 700 ,1500 ,1500 ,2000 ,2000`

into this
`24,	28000,89   ,500  ,469  ,500  ,2000, 2000, 2000, 2000, 2000, 2000 ,2000 ,2000 ,2000 ,2000 ,2000 ,2000 ,2000 ,2000 ,2000 ,2000 , 700 , 750 , 700 ,1500 ,1500 ,2000 ,2000`

@reloadpcdb character select and nothing happens

**Comment by Playtester** [comment]
The only think you changed was the already custom feature to simulate Gunslinger HP via a formula rather than fixed tables. By default the official values from the tables are used.

**Comment by RadianFord** [comment]
Im sorry i dont get it so this means
`HPFactor,HPMultiplicator` wont help change the hp of gunslinger?

**Comment by Playtester** [comment]
What is your goal? Multiply the HP by 5?

**Comment by RadianFord** [comment]
Yea i want to multiply it by 3.

nope I didn't comment that.

**Comment by Playtester** [comment]
Yeah so either need to modify job_basehpsp_db.txt instead or you comment the official system out and use a custom, but be aware it changes HP/SP of all classes to an estimation.

Also HPMultiplicator is just how much HP you get per 100 levels. So 500 is 5 HP per level.

**Comment by RadianFord** [comment]
Thank you for the information. :+1:
