### ISSUE TITLE
active_transform bug and no +10% ASPD for item#18934 Fox Ears Bell Ribbon

### ISSUE THREAD

**Issue by spinzaku** [rathena/rathena#1282]
http://www.divine-pride.net/database/item/18934

`"Adds a chance of transforming wearer into moonlight Flower for 5 seconds when attacked by physical attacks."`

The wearer doesn't change back to normal. Stuck as moonlight.. Even thou it states it only transforms to 5 seconds. waited for 5 minutes still didn't change back to normal. needed to relog to fix this.

another of my players reported that.. "I can see myself as moonlight, but other players said i changed back to normal, had lo relog to fix"

another player: "the crit bonus works but i don't change to moonlight sometimes"

stats bonuses are working like Crit. Only the transformation is bugged.

Relog or moonlight forever!

+10% ASPD also wasn't implemented. script should be:
`bonus bAgi,2; bonus bAspdRate,10; .@r = getrefine(); autobonus "{ .@r = getrefine(); bonus bCritical,100; bonus bLongAtkRate,5+(.@r > 6 ? .@r : 0); }",50+(.@r*2),5000,BF_NORMAL,"{ active_transform 1150,5000; }";`

**Comment by secretdataz** [comment]
10% ASPD bug is fixed in 8e0dff7acb385ee91e3bfd2b88f4e3e871bc71e1.

**Comment by spinzaku** [comment]
Aspd is fixed on latest. But "Adds a chance of transforming wearer into moonlight Flower for 5 seconds when attacked by physical attacks." Still buggy

**Comment by Vomaito** [comment]
Yes, confirm this with Eddga_Hat, have to relog to take pj sprite back when transforms active you never return to normal state but script bonus ends.
