### ISSUE TITLE
12684  ASPD Intensifying Potion not working fine

### ISSUE THREAD

**Issue by darknessfmy** [rathena/rathena#1285]
The item say that:

> The Bonus ASPD is affected by character's AGI point
> If this potion is used with those other ASPD up potion, the effect will be maximized.
> Increases ASPD for 15 minutes.
> Follow the NPC below to make Gin ASPD Enhanced Potion.

```
But, the item is giving this:
12684,ASPD_Potion,ASPD Potion,2,0,,10,,,,,0xFFFFFFFF,63,2,,,,,,{ sc_start SC_HASTEATTACK_CASH,900000,3; },{},{}
```

So we get Stone Curce by all that time

**Comment by cydh** [comment]
Becasue it was defined in const.txt as `SC_HASTEATTACK_CASH	608`
Then after constants clean up, *someone* missed it while checking all used constants.
So change it to `SC_ATTHASTE_CASH` will fix.
(meh, I use it as `SC_HASTEATTACK_CASH` to follow Aegis `EFFECTHasteAttack_Cash` so we can screw on converting Aegis -> rA in future)
