### ISSUE TITLE
Over 65k unknown instances!

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#1287]
[Error]: Over 65k instances of 'unknown' script are being run!

Map server spams this right now, and i can't imagine how this could possibly happen.

Server is online since 11days 21 hours
Average players of 90
No custom instance scripts

Is this actually related to the instance system, or is this something a normal script could also cause?
I've seriously no clue what's this all about.

**Comment by Jeybla** [comment]
I think it's not related to the instance system.

Looks like one or more Scripts can't be freed, I'd recommend to restart your server.

From struct script_state* script_alloc_state:
```C
	if( st->script->instances != USHRT_MAX )
		st->script->instances++;
	else {
		struct npc_data *nd = map_id2nd(oid);

		ShowError("Over 65k instances of '%s' script are being run!\n",nd ? nd->name : "unknown");
	}
```

From void script_free_state(struct script_state* st):
```C
if (st->script && st->script->instances != USHRT_MAX && --st->script->instances == 0) {
```

Looks like the error will never disappear if it's triggered just once.

**Comment by Everade** [comment]
ok thank you for the information
