### ISSUE TITLE
Party Scroll Buffing

### ISSUE THREAD

**Issue by darknessfmy** [rathena/rathena#1288]
This items in fisrt cant be consumed with  double click or skill bar, i test it having a party of course:

```
14588,Pty_Blessing_Scroll,Party Blessing 10 Scroll,11,10,,10,,,,,0xFFFFFFFF,63,2,,,,,,{ itemskill "CASH_BLESSING",10; },{},{}
14589,Pty_Inc_Agi_Scroll,Party Increase Agi 10 Scroll,11,10,,10,,,,,0xFFFFFFFF,63,2,,,,,,{ itemskill "CASH_INCAGI",10; },{},{}
14590,Pty_Assumptio_Scroll,Party Assumptio 5 Scroll,11,10,,10,,,,,0xFFFFFFFF,63,2,,,,,,{ itemskill "CASH_ASSUMPTIO",5; },{},{}
14593,Magic_Power_Scroll,Mystical Amplification Scroll,11,0,,10,,,,,0xFFFFFFFF,63,2,,,,,,{ itemskill "HW_MAGICPOWER",10; },{},{}
 
```
Just to try i change the type of the item from 11 to 2 to see if the skill works and yes it get consumed but there is no skill effect. Thank you have a nice day.

**Comment by secretdataz** [comment]
All listed items are working fine for me in both pre-re and renewal modes.

**Comment by Lemongrass3110** [comment]
This is working as intended.
This is additionally a client limitation.
