### ISSUE TITLE
NPC Earthquake

### ISSUE THREAD

**Issue by aleos89** [rathena/rathena#1289]
Hash: 37b3644
Mode: Both

The NPC skill, Earthquake, is not properly implemented. It is officially an unit skill and rAthena is not utilizing this effect of it.

The damage calculation is off and also has a possible attempt of dividing by 0.

Related: HerculesWS/Hercules@21b72c4

**Comment by Playtester** [comment]
Doesn't it deal damage on LP?

**Comment by aleos89** [comment]
It has a unique case of ignoring LP.

**Comment by reigneil** [comment]
Earthquake skill is unique and complicated skill... more damage you do onto yourself the more it hit hard.
this is why no Ghost monster has this skill.
https://github.com/rathena/rathena/issues/1450
