### ISSUE TITLE
 Gentle Touch - Cure  can heal Emperium or Barricades

### ISSUE THREAD

**Issue by playpsro** [rathena/rathena#1290]
i want to ask, as i know, Emperium its plant type and can't healed.
but in game, my player can heal emperium use Gentle touch Cure (Sura) / Silent Breeze (Homun S Eira)
it is bug need to fixed or not?

**Comment by secretdataz** [comment]
Issue with Gentle Touch - Cure is fixed on 63e7729.
Probably want to check Eira skill.

**Comment by secretdataz** [comment]
Can't reproduce on latest Git.
