### ISSUE TITLE
about bonus bLongWeaponDamageReturn

### ISSUE THREAD

**Issue by whupdo** [rathena/rathena#1292]
"bonus bLongWeaponDamageReturn" Will be long-distance attacks can cause invalid reflection skills

e.g. NJ_TATAMIGAESHI & AL_PNEUMA

**Comment by secretdataz** [comment]
Sorry, I can't understand what you are trying to report.
If you can explain these I'd be appreciated.

- How to create the bug (reproduction steps)
- What is expected when you do that?
- What happen instead of above?

**Comment by secretdataz** [comment]
Tested on official server. This is official behavior.
The damage will still be reflected back to to the attacker even if the attack got blocked by blocking skills suck as Safety Wall, Pneuma and Flip Tatami.
