### ISSUE TITLE
Skill "Ankle Snare" bug

### ISSUE THREAD

**Issue by keitenai** [rathena/rathena#1295]
Player can walk right pass through "Ankle Snare" until reaching the end point of the player's walk path coordinate before getting trapped.

Player can even walk pass through layers of "Ankle Snare" until reaching the end point of the player's walk path coordinate before getting trapped.

*bug has been tested from clean rathena git.*
*- Server setting : renewal / pre-re*
*- Packet obfuscation disabled*
*- Client ver: 20151029*

**Comment by Playtester** [comment]
This is official behavior if you are talking about targets that are knockback immune like e.g. in WoE.

**Comment by anacondaqq** [comment]
https://github.com/rathena/rathena/blob/cb871865785e26548fcc70b1e01f5d9b924941b1/conf/battle/skill.conf#L295
set to 3
