### ISSUE TITLE
Client Closes when MVP dies

### ISSUE THREAD

**Issue by GaChittolina** [rathena/rathena#1297]
Client simply closes everytime a normally spawned MVP dies (using command to spawn the MVP and then killing it does not close the client, as well as killing the normally spawned MVP using commands does not close it). I get no server or client errors.
OBS: It also closes the client of all players on screen.

**Comment by aleos89** [comment]
The only thing I can possibly thing of is the MVP Tomb that spawns is causing you to crash. MVP monsters spawned through the atcommand don't get the MVP Tomb which is possibly why you aren't crashing that way.

We'd need more info from you though (from the labels marked on this issue).

**Comment by GaChittolina** [comment]
Solved. Removing MVP Tomb from conf/battle/monster.conf worked. I believe I forgot to set an view ID to the tombstone, but I wasn't going to use it anyways, so thanks for the help!
