### ISSUE TITLE
Swirling Petal Bug

### ISSUE THREAD

**Issue by spinzaku** [rathena/rathena#1300]
swirling petal doing only 2 hits instead of 5 hits.
edit: will be fixed by @secretdataz

**Comment by secretdataz** [comment]
From [Rytech's data](http://forums.irowiki.org/showthread.php?t=100518) and [this video](https://www.youtube.com/watch?v=OMVSQnUdj4E) seems like the skill is a single hit divided into 5.
I imitated my stats to somewhat close to the video above and got pretty close damage.
