### ISSUE TITLE
Episode 14.2: Eclage

### ISSUE THREAD

**Issue by secretdataz** [rathena/rathena#1301]
To do list for episode 14.2 (Eclage).

- [ ] Battlegrounds Queue System
- [ ] WoE : Training Edition
- [ ] WoE:TE Mini God Item quest
- [ ] Heroes' Trails : Part 1
- [ ] Heroes' Trails : Part 2
- [ ] Wave Mode Memorial Dungeon
- [ ] Horror Toy Factory Memorial Dungeon

**Comment by anacondaqq** [comment]
Just suggestion before implementing episodes. Please keep each episode in specific branch for easier management. Thx

**Comment by secretdataz** [comment]
closing this. move to episode based milestones instead.
