### ISSUE TITLE
sc_start on item_combo_db.txt (or { script } field)

### ISSUE THREAD

**Issue by c0nflicts** [rathena/rathena#131]
As reported by a user on this post; http://rathena.org/board/topic/99223-whats-problem/
I've personally had this problem before, putting any kind of sc_start on the { script } field will cause your stats to go haywire. Fixed it by moving the sc_start to { OnEquip } field. But I don't see that being possible with effects that are on item_combo_db.txt

**Comment by jezznar** [comment]
Problem Confirmed. 
client-sided. can be worked around by using @refresh command in-game.

Pull Request #1009 made. Awaiting approval.
