### ISSUE TITLE
Battleground Queue System

### ISSUE THREAD

**Issue by secretdataz** [rathena/rathena#1310]

**Comment by admkakaroto** [comment]
similar to that eAmod?

**Comment by anacondaqq** [comment]
I guess he means battleground button in alt+v interface, and all system related to it.

**Comment by Everade** [comment]
Would be better to get BG fixed in the first place, before implementing the queue system.
https://github.com/rathena/rathena/issues/1240

**Comment by iubantot** [comment]
any news on this feature? <3

**Comment by reigneil** [comment]
info extracted in msgstring:
`Entering the battleground registering system#
Not possible to register entering and move to the battleground#
1. It is not possible to register several battlegrounds at the same time.#
2. You cannot register the battleground for Solo / Party / Guild at the same time.#
3. Party battleground is only available for registration from the party leader,#
the party members who are offline will miss the queue.#
4. Registering the battleground is possible from everywhere except the battleground map,#
if the entering location is not a town, field or normal dungeon, character will be transferred to saved coordinates when returning.#
5. the rewards of battleground or other services can be found from battleground waiting room through the recruiting officer.#
Entering the battleground registering Help word#`

other info related to battleground queue system:
https://github.com/zackdreaver/ROenglishRE/blob/master/data/luafiles514/lua%20files/battlefield/battlefieldinfo.lub

**Comment by iubantot** [comment]
up

**Comment by Daegaladh** [comment]
Any news on this? I'd like to help, to speed things up

**Comment by aleos89** [comment]
This was on hold because we wanted to utilize the C++ queue class rather than implementing another common library that we have to maintain. It requires a bit more work to convert `script.c` to `script.cpp`. Once that's done it should be relatively easy to implement the rest of the feature.

**Comment by luan122** [comment]
@aleos89 will this come back? i think you guys already converted script.c to script.cpp right?

**Comment by playpsro** [comment]
Any update for this bg?
