### ISSUE TITLE
Heroes' Trails part 1

### ISSUE THREAD

**Issue by secretdataz** [rathena/rathena#1312]
- [x] Faceworm Nest instance
- [x] Sarah's Memory instance

**Comment by admkakaroto** [comment]
I have Sara's Memory, mob_db, quest_db, instance_db everything complete and running, but translated into Portuguese, how can I help?

**Comment by secretdataz** [comment]
@admkakaroto PM me any information to me on rAthena forum.

**Comment by Vexillio** [comment]
Updates on Faceworm?

**Comment by Lemongrass3110** [comment]
Faceworm was merged in 1e1d7e5
