### ISSUE TITLE
Horror Toy Factory

### ISSUE THREAD

**Issue by secretdataz** [rathena/rathena#1314]
wip

TODO:
- [ ]  Implement NPC_HELLBURNING

**Comment by Darkelfen** [comment]
How can we help?

**Comment by secretdataz** [comment]
@Darkelfen if you play on official server, you can record and send us replay of instances that need official info.

**Comment by Darkelfen** [comment]
What if hypothetically, got the instance from let's say Auriga, then converted it to rA and translate the Japanesse dialogues?

**Comment by secretdataz** [comment]
Any kind of help is appreciated.

**Comment by admkakaroto** [comment]
The idea will be updated rAthena as much as possible?

**Comment by Darkelfen** [comment]
I will share it as soon as I got access to my server files.

**Comment by admkakaroto** [comment]
I can also share two: Sara's Memory, Nightmarish Jitterbug

**Comment by admkakaroto** [comment]
@Darkelfen which your nickname in the forum?

**Comment by Darkelfen** [comment]
I've already shared them through discord.

**Comment by Ryuhorox** [comment]
You have nothing official yet?

**Comment by Vexillio** [comment]
Any news here?

**Comment by aleos89** [comment]
Related to #1813.

**Comment by Atemo** [comment]
https://github.com/rathena/rathena/issues/1893 for  NPC_HELLBURNING
