### ISSUE TITLE
@skilltree seems broken in some case

### ISSUE THREAD

**Issue by CairoLee** [rathena/rathena#1320]
The `@skilltree` command is not very important, but still hope it can work... 

### Information
rAthena Git hash: 38155a625eb30b7f85edeb9c68a0bb70f0559eaa
Client version: 20150916
Mode: Renewal

### Reproduce
Make a character, set the char name is GM01.
Change character's job to 5 (Merchant) and exec `@skilltree 38 GM01` ----> Worked
Change character's job to 18 (Alchemist) and exec `@skilltree 38 GM01` ----> Worked
Change character's job to 4006 (Merchant High) and exec `@skilltree 38 GM01` ----> `Broken`
Change character's job to 4019 (Creator) and exec `@skilltree 38 GM01` ----> `Broken`
Change character's job to 4071 (Genetic) and exec `@skilltree 38 GM01` ----> `Broken`
Change character's job to 4078 (Transcendent  Genetic) and exec `@skilltree 38 GM01` ----> `Broken`

**Comment by anacondaqq** [comment]
I can confirm for pre-renewal too. + Time to time it's provoke a map-server crash, but i don't know how reproduce, because i got it randomly few times.
