### ISSUE TITLE
Odin's Power

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#1323]
Skill Odin's Power is not increasing magic attack, follow the link with description and images:

Descrip: http://www.divine-pride.net/database/skill/2537

Aft: http://i.imgur.com/EHsy5GZ.jpg

Bfr: http://i.imgur.com/SqlMhFq.png

**Comment by julia40124009** [comment]
https://github.com/rathena/rathena/issues/976

**Comment by admkakaroto** [comment]
sorry u.u

**Comment by admkakaroto** [comment]
There is bug in ability but in view of the status, sorry, you can close.
