### ISSUE TITLE
Delete_date is red but when I delete char, nothing happen.

### ISSUE THREAD

**Issue by Vomaito** [rathena/rathena#1325]
Well I have some chars with delete date: 12/31 18:0:0 in red.
If I click delete, a pop-up appears saying "Now Logging Out.", but when I login, the char is sit with same date.
Using latest version. I think is because I change delay times and they get bug.

How to fix this? Is emulator problem or I need to reset delete_date from char db?

**Comment by aleos89** [comment]
Duplicate of #1189.
