### ISSUE TITLE
SQL Database entries

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#1328]
I found some really weird sql database entries, which i'm kind of curious about.

Is this normal?
Like some kind of temporary entries?

Or are these really messed up savings?
I've noticed these in all item based sql savings.

And no, such high account_ids nor item names do not exist in my case.

![rent](https://cloud.githubusercontent.com/assets/12261601/15682372/a0f4018e-275d-11e6-8931-ec2108f000dc.png)

**Comment by dastgir** [comment]
Someone messed up your SQL?

**Comment by aleos89** [comment]
It's hard to say. You have multiple columns that are representing corrupted/incorrect values.

Also, please watch your language. Lets try to keep the tracker somewhat decent. :)

**Comment by Everade** [comment]
Ok so it's actually corrupt.
Thanks

No idea when/how this happened.

I will clean it up and create a new issue in case this problem appears again.

And i'm watching my language, how was that supposed to be bad...

**Comment by LiamKarlMitchell** [comment]
Hmm, my IP Addresses in login table are corrupted as well.
I'll see about making an issue later :)

**Comment by Everade** [comment]
It's kinda weird as this is the first time i've seen it like this (running this database since 11+ years)

**Comment by LiamKarlMitchell** [comment]
crud that does seem scary. 
Value can be increased or use 64bit data type?
Either that or DB clean up to remove no longer used items and move all the keys closer together.... horrid.

_btw, 11 years I would say well done_
