### ISSUE TITLE
Guillotine Cross Job Change Quest: Missing Timers

### ISSUE THREAD

**Issue by rubie123** [rathena/rathena#1331]
The quests in Guillotine Cross job change text are all missing the timers.
Not sure if this is how it's supposed to be now in official servers, but the current script is still looking for the 'playtime' on these quests (although you are able to finish the quest without a prob.)

`7101,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"Special task of an assassin guild  1"
7102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"Special task of an assassin guild  2"
7103,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"Special task of an assassin guild  3"
7104,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"Special task of an assassin guild  4"
7105,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"Special task of an assassin guild  4"
7106,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"Special task of an assassin guild  5"
7107,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"Special task of an assassin guild  6"
7108,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"Special task of an assassin guild  7"
7109,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"Special task of an assassin guild  8"
7110,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"Special task of an assassin guild  9"
7111,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"Special task of an assassin guild  10"`

**Comment by secretdataz** [comment]
Fixed in 25c4334
