### ISSUE TITLE
homunculus S and teleport issue

### ISSUE THREAD

**Issue by joelolopez** [rathena/rathena#1332]
how to produce
-fight mistress(boss)
-whenever the mob of mistress teleports the homunculus S get teleported to0.
-the homunculus S will be seperated with the owner xp

using 17017 , 2015-11-04aRagexe

**Comment by aleos89** [comment]
SVN ID 17017 translates to Git Hash 39a6e86.

I highly suggest your first step to be to upgrade. Not sure how you're using a 2015 client with such an old revision. Also, rAthena no longer supports SVN so I suggest you switch over to Git.

**Comment by joelolopez** [comment]
sir aleos im using git not svn

**Comment by secretdataz** [comment]
@joelolopez what did you mean by "using 17017"?

**Comment by joelolopez** [comment]
rathena svn revision 17071

**Comment by secretdataz** [comment]
@joelolopez try updating to latest version and test if reported issue happen or not.

**Comment by secretdataz** [comment]
I can't reproduce the issue on my test server. My homun didn't get teleported with the boss.

**Comment by joelolopez** [comment]
when mistress is trying to escape all of his bugs get teleported in a random area and your homunulus will get teleported too

**Comment by aleos89** [comment]
I can't reproduce this either. Mistress teleported several times and my homunculus always stuck by my side.
