### ISSUE TITLE
Instance Mode Expansion Crashed map-server

### ISSUE THREAD

**Issue by VXPlay** [rathena/rathena#1333]
//English
Hello guys! Testing instantiates Old Glast Heim , I realized that to undo the group the map-server closes alone, someone is going through it ?
Img: http://prntscr.com/bbb3lr

//Português
Olá pessoal! Testando a instancia Old Glast Heim, percebi que ao desfazer o grupo o map-server fecha sozinho, alguém está passando por isso?
Img: http://prntscr.com/bbb3lr

**Comment by secretdataz** [comment]
We need more info on the crash like, what happened before the crash,
what are you doing before the crash to identify the cause.
