### ISSUE TITLE
Client just completely stop when using atcommand on a char w/ grp id 99

### ISSUE THREAD

**Issue by technoken** [rathena/rathena#1335]
Git Hash: 'e39293f1294df0a500fcbc984f6fdbd9d20b8c26'
Mode: Pre-renewal
Client: 2013-12-23
No src modification

Here's the issue:
When I start my server it doesn't show any errors or warnings. Then I login a normal character with grp id 0 and it works well. Now I logged-in an admin account with grp id 99, the character can login but whenever I used atcommand the client just completely stop without showing any errors on client and server side. I can't even use character select to logout so I use alt-f4 to close the client. Then I try to relogin. I can still login until character select but when I loaded my character it just says 'Please wait...' until it says 'Failed to connect to server'.

**Comment by technoken** [comment]
Update: I experienced it again today even when not using an admin account and not using atcommand. I just keep using skills..

**Comment by Lemongrass3110** [comment]
Unable to reproduce this.

Which atcommands are you using?
Are you sure you have compiled your server for 2013-12-23? Compiling it for > october 2015 and using a 2013 client would break chat/atcommand support for your server.

**Comment by technoken** [comment]
Yes it is compiled for 2013-12-23 in mmo.h and using the right packets in packet_db.txt..
I didn't encounter it before I updated my git to hash: 'e39293f1294df0a500fcbc984f6fdbd9d20b8c26'.

My previous hash is 'f0b093f0fd9ac955da88c01f26b4c6acdcd7ec6e'

**Comment by aleos89** [comment]
I couldn't replicate this on 2015-10-29. I didn't have enough time to test for 2013, so I'll try to test later.

**Comment by technoken** [comment]
@aleos89 I think it's also working fine with 2013-08-07. Try 2013-12-23 client and see if you can replicate it.

**Comment by 15peaces** [comment]
For me the client is working completely fine, even with GM-Level 99 and @item2 etc... (Using 3ceam, not rAthena, so I guess it's related to rA?)

**Comment by secretdataz** [comment]
@15peaces well, we can't even reproduce the issue on rA using the steps provided by the issue creator. :o

**Comment by 15peaces** [comment]
I only wanted to mention that it's not a client-problem directly xD
Then I guess he diffed the client wrong or something like that xD

**Comment by aleos89** [comment]
I just tested with 2013-12-23 using the `@item2` command again and didn't crash. I completely forgot, but when diffing, make sure you select the `@ Bug Fix (Recommended)`.

Either way, this is totally client related and not related to rAthena. The diff option should resolve your issue. If not, please take this to the client support section in the forum!

**Comment by technoken** [comment]
I diffed it with @ Bug Fix and I still experienced it. I remember I just diffed my client before I experienced this. I'll try again to figure out what's causing this.

Well anways thank you for your time figuring it out.
