### ISSUE TITLE
Enchanting Item NPC doesnt work any more

### ISSUE THREAD

**Issue by maczekie** [rathena/rathena#1337]
this Affects Enchantment like FAW enchanter
here is the code
	delitem2 2589, 1, 1, getarg(3), 0, @card1, @card2, @card3, @card4;
	getitem2 2589, 1, 1, getarg(3) , 0, @card1, getarg(0), getarg(1), getarg(2);

or 

	delitem2 2589, 1, 1, .@refeq, 0, @card1, @card2, @card3, @card4;
	getitem2 2589, 1, 1, .@refeq, 0, @card1, 0, 0, 0;

**Comment by secretdataz** [comment]
`getitem2` and `delitem2` are still working fine.
If these two commands don't work, please describe how and re-open this issue.

**Comment by Yami-CNMXVI** [comment]
I just had the same issue. How can we resolve this?
This appears on my console everytime I try to enchant my FAW for the 2nd time.
![faw error1](https://cloud.githubusercontent.com/assets/20726883/17465941/fec86ac2-5cb7-11e6-8a3c-a5bf5eabcf2c.png)

**Comment by cydh** [comment]
Afaik we don't have FAW Enchanter (official name: Dark Luhir)

**Comment by secretdataz** [comment]
Anyways, if you believe your script doesn't work because of a bug in rAthena, provide us a simple test case that we can test the bug.
