### ISSUE TITLE
EARTHQUAKE

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#1338]
skill of Monsters: EARTHQUAKE is not causing any damage to players ...

rAthena latest version of git.

Print: http://i.imgur.com/sLMBkAO.png

**Comment by CairoLee** [comment]
how many your vit?

**Comment by julia40124009** [comment]
video : https://youtu.be/WhvNfTAAlcU
version : https://github.com/rathena/rathena/commit/46f1a6f6951e29b99d7c0e5e73c0a851ddba922e

**Comment by aleos89** [comment]
I couldn't reproduce this on a clean rA (using 323bd72).

Did you happen to apply the revert in e39293f? I am able to get hit all 3 times.
