### ISSUE TITLE
channel system crash

### ISSUE THREAD

**Issue by julia40124009** [rathena/rathena#1342]
sometimes crash , idk how to explanation
after speak sometimes crash

<a href="http://imgur.com/N0q8ntH"><img src="http://i.imgur.com/N0q8ntH.png" title="source: imgur.com" /></a>

test script

```
-	script	channelInit	-1,{
	end;
OnInterIfInit:
	atcommand "@channel create #testchannel";	
	atcommand "@channel setcolor #testchannel costume1";
	end;
}

```
and channels.conf
```
default_channels: {
}
```
```
colors: {
costume1: "0xFF9224"
}
```
```
	allow_user_channel_creation: true
```
```
	map_local_channel: false
	map_local_channel_name: "map"
	map_local_channel_color: "Yellow"
	map_local_channel_autojoin: true 
```
```
	ally_channel_enabled: true
	ally_channel_name: "ally"
	ally_channel_color: "Green"
	ally_channel_autojoin: true
```

stackdump is give me cause some info 
https://github.com/rathena/rathena/blob/master/src/map/clif.c#L6075
https://github.com/rathena/rathena/blob/master/src/map/clif.c#L6082

version : https://github.com/rathena/rathena/commit/323bd72907597d1e4af25119db7985760d95884d
client : 20151104

--------------------------------------------
other suggest
support chinese channel name in channels.conf

**Comment by lighta** [comment]
it's because that atcommand for channel creation shouldn't be available for script, since the owner of the channel created by atcommand should be the invoking char. 
Here with OnInterIfInit it's no one, (well to be exact it's a dummy_player, that why when talking afterward he try to send the message to the dummy and bim boum)

Use conf/channel.conf instead for server channel initialisation.

**Comment by julia40124009** [comment]
but channel.conf not support chinese language

**Comment by secretdataz** [comment]
@julia40124009 that's another unrelated issue.

**Comment by julia40124009** [comment]
That's why I use script to do it , not use channel.conf
Here I focus on the script causes crash

**Comment by secretdataz** [comment]
@julia40124009 try changing
```
if( user->fd == sd->fd )
			continue;
```
to
```
if(!user->fd || user->fd == sd->fd )
			continue;
```

**Comment by secretdataz** [comment]
Marked this issue as wontfix because `@channel` is never intended to be used in scripts.

**Comment by cydh** [comment]
@julia40124009 do u still with us? can u try this too https://rathena.org/board/topic/107823-channel-system-expanded/ for other native language

**Comment by julia40124009** [comment]
@cydh 
I will test it in my free time

**Comment by cydh** [comment]
@julia40124009 well, for Chinese in config maybe just same issue like before.
but the script commands are working? for creating, sending message?

**Comment by julia40124009** [comment]
look good

<a href="http://imgur.com/BsGNc9l"><img src="http://i.imgur.com/BsGNc9l.png" title="source: imgur.com" /></a>

**Comment by cydh** [comment]
Thank you :D
If u have any suggestion (or even issue), please tell me on my topic.
