### ISSUE TITLE
Cast Sensor Issue

### ISSUE THREAD

**Issue by Porink** [rathena/rathena#1344]
For every monster that has cast sensor flag, everytime a magic spell is casted on them they will attack the caster regardless there is a cast time or not. The cast sensor flag is supposed to be triggered only by magic spells that has cast time (i.e. Firebolt), not magic without cast time (i.e. Lex Aeterna).

**Comment by aleos89** [comment]
I remember adjusting this back from this report: https://rathena.org/board/tracker/issue-8555-cast-sensor/

**Comment by Playtester** [comment]
Definitely invalid. Lex Aeterna and Cure trigger aggro on cast sensor mobs on official servers. Just tested.
