### ISSUE TITLE
Guillotine Quest Bugged?

### ISSUE THREAD

**Issue by spinzaku** [rathena/rathena#1346]
git hash:
![githash](https://cloud.githubusercontent.com/assets/18629476/15824944/4355fdf8-2c34-11e6-969e-9c7412b15d74.png)

4 hours ago reported by my player 
screenshot:
![guilotquest](https://cloud.githubusercontent.com/assets/18629476/15824930/3aad6d30-2c34-11e6-8770-8ea7b505ae85.png)

**Comment by Lemongrass3110** [comment]
Maybe related to 25c4334?

**Comment by spinzaku** [comment]
checking the script its this part:

```
veins,206,56,0	script	#3rdgc_battleroom01	139,1,1,{
	end;
OnInit:
	set $@3rdgc_room01, 0;
	end;
OnTouch:
	if (job_3rd_gc == 12) {
		if (checkquest(7107,PLAYTIME) == 2) {
			mes "This must be the place Estillda told me about.";
			next;
			switch(select("Go inside.:Observe the situation.")) {
			case 1:
				if ($@3rdgc_room01 == 0) {
					warp "job3_guil02",34,44;
					set $@3rdgc_room01, 1;
				} else {
					mes "You tried to open the door but it's locked.";
					mes "It doesn't show any signs of life.";
					next;
					mes "Come back here later.";
				}
				close;
			case 2:
				mes "I back up to watch the situation unfold.";
				close;
			}
		} else if (checkquest(7107,PLAYTIME) == 1) {
			mes "This must be the place Estillda told me about.";
			mes "I have enough time for meeting.";
			close;
		} else {
			mes "An error has occurred.";
			mes "Contact the GM team to resolve the situation.";
			close;
		}
	}
	end;
}
```

**Comment by Lemongrass3110** [comment]
Okay this might really come from the commit i mentioned.
Since this quest now has a time supplied the checks need to be adjusted.

```
*checkquest(<ID>{,PLAYTIME|HUNTING{,<char_id>}})
...
If parameter "PLAYTIME" is supplied:
	-1 = Quest not started (not in quest log)
	0  = the time limit has not yet been reached
	1  = the time limit has not been reached but the quest is marked as complete
	2  = the time limit has been reached
```

The checks we have now are exactly as the ones done in the AEGIS leak we have, but we are missing the case for 0. Maybe we need to add it to the second check as if state 1 or 0.

**Comment by spinzaku** [comment]
Ahhh.. so it got bugged ? So the only way to fix this for now is to manually job change via @ command to the player?

**Comment by Lemongrass3110** [comment]
Hmm no I think the player just has to wait until the time has passed and the quest is marked as time limit reached. I remember it was like that on officials with the GX quest.

**Comment by spinzaku** [comment]
I have checked via google in official servers people have reported with same issue.. they had to file ticket or wait 24 hours or next maintenance to get this fixed..

**Comment by Lemongrass3110** [comment]
From the entry @secretdataz made it should be 3 hours the player would have to wait.

**Comment by spinzaku** [comment]
So if another player changes to guillotine he also needs to wait for 3 hours? isn't that bad? x_x

**Comment by Lemongrass3110** [comment]
It will happen to anyone who takes the quest.
I believe it is online playtime, so it will not count if he plays on another character in the meantime. But I am not totally sure about it and I can not test it at the moment.

**Comment by spinzaku** [comment]
So a quest where you need to be online for 3 hours? that's insane.. X_X Previous players before didn't encounter or reported a problem thou ( i used a version before the 25c4334 )

**Comment by Lemongrass3110** [comment]
Well one thing is for sure the scripts need to be fixed, but if you do not like the way it will be, you should just put the old entries without the quest time into your import folder and overwrite it.

**Comment by Playtester** [comment]
Playing an MMORPG 3 hours is insane? Oh my, what have I done with my life.

**Comment by Lemongrass3110** [comment]
So finally found time to confirm this.

Your players can see when they can continue here:
![gx](https://cloud.githubusercontent.com/assets/3517879/15838617/432626fe-2c3f-11e6-80db-718f932f55a9.PNG)

Nevertheless the error message is wrong and should be fixed.

**Comment by spinzaku** [comment]
thank you @Lemongrass3110

**Comment by spinzaku** [comment]
Any updates? Every player in my server changing to GX is getting this contact gm message. I just tell them to stay online for minimum 3 hours.
