### ISSUE TITLE
List of Costumes not working properly

### ISSUE THREAD

**Issue by spinzaku** [rathena/rathena#1349]
git:
![githash](https://cloud.githubusercontent.com/assets/18629476/15866682/42cd80c0-2d12-11e6-8b9f-d9e8d3f0434d.png)

Tested using Latest fully patched Korean Ragnarok Online:

no item effects/graphics:
`20246,C_Decoration_Time,Costume Decoration Time,4,0,,0,,,,0,0xFFFFFFFF,63,2,2048,,1,1,1309,{},{},{}`
`20154,C_Maple_Which_Falls,Costume Maple Which Falls,4,0,,0,,,,0,0xFFFFFFFF,63,2,2048,,,1,1275,{},{},{}`
`20439,C_New_Year_Shine,Costume New Year Shine,4,0,,0,,,,0,0xFFFFFFFF,63,2,2048,,1,0,0,{},{},{}`
`20323,C_Sparkling_Sound,Costume Sparkling Sound,4,0,,0,,,,0,0xFFFFFFFF,63,2,4096,,1,1,1074,{},{},{}`

obvious ones that don't work:
`20240,C_Gift_of_Snow,Costume Gift of Snow,4,0,,0,,,,0,0xFFFFFFFF,63,2,4096,,1,1,,{/*TODO: ViewID*/},{},{}`
`20062,C_Angel_Stair,Costume Angel Stair,4,0,,0,,,,0,0xFFFFFFFF,63,2,1024,,1,1,,{/*TODO: ViewID*/},{},{}`

weird result:
`20285,C_Dancing_Fallen_Sakura,Costume Dancing Fallen Sakura,4,0,,0,,,,0,0xFFFFFFFF,63,2,4096,,1,1,1331,{},{},{}`
![sakura](https://cloud.githubusercontent.com/assets/18629476/15867079/1a1eee5a-2d14-11e6-9a3a-3f42dd852a33.png)

causes sprite error even w/ latest kRO patched client:
`20209,C_Mermaid_Bubbles,Costume Mermaid Bubbles,4,0,,0,,,,0,0xFFFFFFFF,63,2,1024,,1,1,1299,{},{},{}`
`Cannot find File : sprite\¾Ç¼¼»ç¸®\³²\³²_ÀÎ¾î°øÁÖÀÇ±×¸®¿ò.act`

**Comment by secretdataz** [comment]
note:
```
causes sprite error even w/ latest kRO patched client:
20209,C_Mermaid_Bubbles,Costume Mermaid Bubbles,4,0,,0,,,,0,0xFFFFFFFF,63,2,1024,,1,1,1299,{},{},{}
Cannot find File : sprite\¾Ç¼¼»ç¸®\³²\³²_ÀÎ¾î°øÁÖÀÇ±×¸®¿ò.act
```
is not our fault and we won't fix it.

**Comment by Darkelfen** [comment]
Those hats are supposed to work with effects as for example Moon ans Stars or Twillight. 
```
18742,C_MoonStar_Accessory,Moon and Stars,4,20,,0,,0,,0,0xFFFFFFFF,63,2,2048,,0,0,881,{},{ sc_start SC_MOONSTAR,-1,0; },{ sc_end SC_MOONSTAR; }
```

Though I dunno how to make them "display" the effects.

**Comment by julia40124009** [comment]
not support sc yet
u can add sc status it

**Comment by Darkelfen** [comment]
Tried; failed hopelessly.

**Comment by cydh** [comment]
and the fact, kRO introduced some new items with effects (hateffectinfo.lua) that sends the info with new packet.

**Comment by cydh** [comment]
I'll try to find out which kRO client that support this hateffectinfo.

**Comment by jgoog999** [comment]
Please be remind that some of the reported items here are still not implemented in my PR.
