### ISSUE TITLE
Skill Cooldown script and Castdelay ??

### ISSUE THREAD

**Issue by Paoly28** [rathena/rathena#1351]
skillcooldown reduction affected cast delay reduction they are separate right ?

**Comment by secretdataz** [comment]
yes.

**Comment by Paoly28** [comment]
it shouldn't interact with each other right ? since global cooldown and skill reuse are two different things much like fix cast time and variable cast time,  this is the case with kRO's new item old hg's even with total removal of most CDs on skill the global cast delay still remain, it's also the case with the new Dexterity complement device, iirc that's why mechs preffered knuckle boost for solo DPS instead of dex
