### ISSUE TITLE
@autoloot

### ISSUE THREAD

**Issue by ElsaEve** [rathena/rathena#1354]
Seem like `@autoloot` is not working properly.
When you `@autoloot`, some of item did not loot. Same goes if we are `@autoloot` 10.
When you turn off the `@autoloot`, It will loot items.

Using the latest GIT.

Kindly, can you guys check on this?

edited by @secretdataz : Use \`\` to encase `@` mention.

**Comment by Akkarinage** [comment]
'Latest' is not a git hash. Any custom src modifications? Renewal or Pre?

**Comment by ElsaEve** [comment]
im using renewal, src modification only @afk. which is im add it at the custom folder in src. :)

**Comment by secretdataz** [comment]
@ElsaEve Please don't use the `@` symbol or please use \`\` to encase it so it won't mention random github users.

**Comment by Playtester** [comment]
Did you perchance increase the maximum drop rate to above 100%?

**Comment by ElsaEve** [comment]
@secretdataz , Im sorry.
This is my Git Hash: '5ef2000bd9695c59bb8a34ca4e6b420c152bcbd9'

@Playtester , yes i do modified the drop rate, does it effect? Because i am using the same rates from my previous server.

**Comment by Playtester** [comment]
I think autoloot only works for drop rates up to 100%.

**Comment by ElsaEve** [comment]
Thats really odd or does official working like that? Because we do not have any issues with `@autoloot`.

@secretdataz , what more info do you need for this?

**Comment by Playtester** [comment]
Officially there is no autoloot.

Also, there's no reason to put the maximum drop rate above 100%.

**Comment by secretdataz** [comment]
We'd like to see your conf/battle/drops.conf.

**Comment by ElsaEve** [comment]
@secretdataz , this is my [drop.conf](http://pastebin.com/KqxqeqPp)

**Comment by ElsaEve** [comment]
@secretdataz , @Playtester , i have found where the problem started. Its here
`https://github.com/rathena/rathena/commit/55e4df14c2141f291a985c391408a045ec1b25c4`

Ive done try both before and after the commit, `@autoloot` is working fine before the commit.

**Comment by Playtester** [comment]
Okay, but how to reproduce? How do you enable autoloot? What monster do you kill? Which item isn't looted automatically?

**Comment by ElsaEve** [comment]
1. Monster - all monster (tested with poring, dokebi, poporing, MVP Valk and more)
2. All items - examp = Sometime it loot apple, sometime not. Same goes like other items.

With normal physical attack, sometime its loot sometime its not. But with AOE skills, it will not loot 1 item at all even you `@monster 1750 100/50/10/1`.

**Comment by Playtester** [comment]
I can't confirm this. I used your drop.conf, used `@autoloot` and then spawned 10 porings and all the drops were looted automatically, none dropped to the ground.

Maybe your inventory is full?

**Comment by ElsaEve** [comment]
@Playtester , can you try kill the poring with AOE skills, use different jobs and skills.

1 of the method for tested that i am use like below.
Ranger 
- Skill Arrow Storm = its do loot everything.
- Skill Aimed Bolt = its do not loot.

**Comment by aleos89** [comment]
Do you happen to have `AUTOLOOT_DISTANCE` defined?

**Comment by ElsaEve** [comment]
@aleos89 , by default.

`//This is the distance at which @autoloot works,
//if the item drops farther from the player than this,
//it will not be autolooted. [Skotlex]
//Note: The range is unlimited unless this define is set.
//#define AUTOLOOT_DISTANCE AREA_SIZE`

**Comment by ElsaEve** [comment]
@aleos89 , @secretdataz , @Playtester , i have solved the issues by using this [gat hish version](https://github.com/rathena/rathena/tree/ca049a66f4b14ada84f235951f23f3b989292cc2).
I do not know where is the problem, but using this gat hash everything is fine now.
