### ISSUE TITLE
input in NPCs with sprite -1

### ISSUE THREAD

**Issue by Weskercorp** [rathena/rathena#1355]
When creating a NPC with the sprite -1, the 'input' command din't work.
I test it utilizing OnTouch (Because you can't click in a -1 NPC) and it didn't work

**Comment by aleos89** [comment]
What happens when you make it clickable through a duplicate NPC?

**Comment by Atemo** [comment]
```
izlude,130,145,4	script	test	-1,2,2,{
OnTouch:
	input .@id;
	end;
}
```
With the script above the character is stucked (can't move, can't use skill, input doesn't appear).

```
-	script	test	-1,{
OnTouch:
	input .@id;
	end;
}
izlude,130,145,4	duplicate(test)	test ddd	4_F_CRU,2,2
```
With the script above everything is working as intended

**Comment by secretdataz** [comment]
Seems like client behavior. If source npc isn't on screen, the input box won't appear.
We do send fake NPC to client though iirc. Needs further debugging.

**Comment by aleos89** [comment]
According to the documentation:
```
** Define a 'floating' NPC object.

-%TAB%script%TAB%<NPC Name>%TAB%-1,{<code>}

This will define an NPC object not triggerable by normal means. This would 
normally mean it's pointless since it can't do anything, but there are 
exceptions, mostly related to running scripts at specified time, which is what 
these floating NPC objects are for. More on that below.
```
I would say this is working as intended.
