### ISSUE TITLE
Reflect Damage 1 hit emperium

### ISSUE THREAD

**Issue by iubantot** [rathena/rathena#1356]
have a RG and any character

have the RG use reflect damage and place him near the emperium

have the other character attack the RG.

now the emperium will be hit with the reflect damage.

also applicable to other monster that recieve 1 damage per hit

**Comment by maczekie** [comment]
yes , is there a way to fix this?

**Comment by Jeybla** [comment]
Quickfix:

```diff
diff --git a/src/map/battle.c b/src/map/battle.c
index 2ade937..8634050 100644
--- a/src/map/battle.c
+++ b/src/map/battle.c
@@ -6958,7 +6958,7 @@ void battle_drain(struct map_session_data *sd, struct block_list *tbl, int64 rda
 int battle_damage_area(struct block_list *bl, va_list ap) {
 	unsigned int tick;
 	int64 damage;
-	int amotion, dmotion;
+	int amotion, dmotion, flag;
 	struct block_list *src;
 
 	nullpo_ret(bl);
@@ -6968,9 +6968,14 @@ int battle_damage_area(struct block_list *bl, va_list ap) {
 	amotion = va_arg(ap,int);
 	dmotion = va_arg(ap,int);
 	damage = va_arg(ap,int);
+	flag = va_arg(ap,int);
 
 	if (status_bl_has_mode(bl,MD_SKILL_IMMUNE))
 		return 0;
+		
+	if( is_infinite_defense(bl,flag) )
+		damage = 1;
+	
 	if( bl != src && battle_check_target(src,bl,BCT_ENEMY) > 0 ) {
 		map_freeblock_lock();
 		if( src->type == BL_PC )
```

I'm not quite sure about the official behavior. This will damage all plants with 1 damage on battle damage area. But imo the Emperium should have Skill Immune Mode, so it won't get any damage. Or am I wrong?

**Comment by maczekie** [comment]
yeah but i checked the src script and no immune in reflect , , morbid_emperium but let me test this if this will work thanks

**Comment by Atemo** [comment]
Note : on official plant monster take all damage.
