### ISSUE TITLE
Item : Level Up Box

### ISSUE THREAD

**Issue by ElsaEve** [rathena/rathena#1357]
Renewal

Item Level Up Box. Can't click in-game.

`22522,Level_Up_Box100,Level Up Box(100),18,10,,0,,,,0,0xFFFFFFFF,63,2,,,100,,,{ getgroupitem(IG_Level_Up_Box100); },{},{}
22523,Level_Up_Box120,Level Up Box(120),18,10,,0,,,,0,0xFFFFFFFF,63,2,,,120,,,{ getgroupitem(IG_Level_Up_Box120); },{},{}
22524,Level_Up_Box130,Level Up Box(130),18,10,,0,,,,0,0xFFFFFFFF,63,2,,,130,,,{ getgroupitem(IG_Level_Up_Box130); },{},{}
22525,Level_Up_Box140,Level Up Box(140),18,10,,0,,,,0,0xFFFFFFFF,63,2,,,140,,,{ getgroupitem(IG_Level_Up_Box140); },{},{}
22526,Level_Up_Box150,Level Up Box(150),18,10,,0,,,,0,0xFFFFFFFF,63,2,,,150,,,{ getgroupitem(IG_Level_Up_Box150); },{},{}
22527,Level_Up_Box160,Level Up Box(160),18,10,,0,,,,0,0xFFFFFFFF,63,2,,,160,,,{ getgroupitem(IG_Level_Up_Box160); },{},{}`

**Comment by secretdataz** [comment]
Working fine on latest version.
