### ISSUE TITLE
Manual Combo sura not working

### ISSUE THREAD

**Issue by bhily** [rathena/rathena#1358]
maybe there's a link how to fix this issue?
I try to find it but I still didnt get it

a lot of ppl at my server wanna use manual combo

manual combo issue at my server : after use Dragon Combo, we need to click the mob while use Fallen empire to get combo

sorry for my noob language and knowledge :(

**Comment by aleos89** [comment]
Fallen Empire is a self-skill. So after using Dragon Combo you use Fallen Empire and it will cast the skill on "yourself" without you having to select the target. Please make sure you have an updated rAthena.

**Comment by secretdataz** [comment]
[Video](https://www.youtube.com/watch?v=X949YaB1M-8) of it working in version 26aa69d6ef07a885f3bee0207d5386ec6a355944 on 2015-10-29aRagexe with renewal enabled.
