### ISSUE TITLE
Reload script inside Instance *changed title

### ISSUE THREAD

**Issue by iubantot** [rathena/rathena#1359]
![image](https://cloud.githubusercontent.com/assets/13269331/15987887/ac11e7b6-306d-11e6-90b0-123cc910511a.png)

before after reloading script the character will be moved to the beginning of the instance but now it throws this error.

happens to all instance

**Comment by secretdataz** [comment]
Can we have a look at your instance db?

**Comment by iubantot** [comment]
`// Instance Database
//
// Structure of Database:
// ID,Name,LimitTime,IdleTimeOut,EnterMap,EnterX,EnterY,Map2,...,Map255
//
// EnterMap is considered as Map1

1,Endless Tower,14400,300,1@tower,50,355,2@tower,3@tower,4@tower,5@tower,6@tower
2,Sealed Catacomb,7200,300,1@cata,100,224,2@cata
3,Orc's Memory,3600,300,1@orcs,179,15,2@orcs
4,Nidhoggur's Nest,14400,300,1@nyd,32,36,2@nyd
5,Mistwood Maze,7200,300,1@mist,89,29
6,Culvert,3600,300,1@pump,63,98,2@pump
7,Octopus Cave,3600,300,1@cash,199,99
8,Bangungot Hospital 2F,3600,300,1@ma_h,40,157
9,Buwaya Cave,3600,300,1@ma_c,35,57
10,Bakonawa Lake,7200,300,1@ma_b,64,51
11,Wolfchev's Laboratory,14400,300,1@lhz,45,148
12,Old Glast Heim,3600,300,1@gl_k,150,20,2@gl_k
13,Eclage Interior,1200,300,1@ecl,60,50
16,Bios Island,7200,300,1@dth1,19,94,1@dth2,1@dth3

`

**Comment by secretdataz** [comment]
Thank you for the information.
