### ISSUE TITLE
653:NPC_EARTHQUAKE, divide per 0 avoided!

### ISSUE THREAD

**Issue by Keysito** [rathena/rathena#1362]
So, i was notice there was something pop-up in my map-console, and yes i'm running as 'DEBUG-MODE' for test purposes. i would like to report this issue.
![casspture](https://cloud.githubusercontent.com/assets/18493882/15998674/d8864808-3105-11e6-9173-4fc08bd16433.PNG)

**Comment by secretdataz** [comment]
Please provide missing information.

**Comment by RadianFord** [comment]
Was this fixed already? https://github.com/rathena/rathena/commit/19f2bc597ca19b445a989c7ab1e897a351c99e41

**Comment by Keysito** [comment]
Sorry. it is Git Has: 055ee42 Date: 6-12-2016

**Comment by Lemongrass3110** [comment]
Do you use renewal or prerenewal?

**Comment by aleos89** [comment]
Well, it's obvious from the error message, that the skill was used around no targets, thus causing a divide by 0 attempt.

But like Secret and Lemon said, it would be nice to know what monster/player caused this and how.

**Comment by Playtester** [comment]
So I tested Earthquake a little:

1. The graphical effect is wrong, it right now shows multiple times if there is a target hit, but not at all when there's no target hit. Official it shows the effect exactly once regardless of if something is hit or not.

2. Even if Earthquake doesn't hit any target, I won't get the error message in the console.

**Comment by Lemongrass3110** [comment]
No further input from reporter for 4 months.
Closing this.
