### ISSUE TITLE
Old Glass Heim can't go to previous floor bug and missing npcs

### ISSUE THREAD

**Issue by spinzaku** [rathena/rathena#1363]
git:
![gitlatest](https://cloud.githubusercontent.com/assets/18629476/16037755/8e0bac82-3254-11e6-9e87-27e568f16629.png)

my players have reported they can't seem to go to previous floors of Old Glass Geim.
![gate](https://cloud.githubusercontent.com/assets/18629476/16037725/63002c70-3254-11e6-87a8-712ef5f7477f.jpg)

in iRO you can: https://youtu.be/WWitkQ44kLo?t=1381

missing npcs also reported:
![huginnpc](https://cloud.githubusercontent.com/assets/18629476/16037790/b479ddb2-3254-11e6-868d-e05a24fced19.jpg)

**Comment by secretdataz** [comment]
Confirmed on tRO and iRO, so not iRO's custom.
