### ISSUE TITLE
Instance System map server crash upon deletion of the Party leader's character.

### ISSUE THREAD

**Issue by Uruniz** [rathena/rathena#1366]
Running the latest rAthena, it seems the new instance system causes a segmentation fault (core dump) crash of the map server if the leader of a Party's character is deleted via the login creation window -- with the instance ID still attached.

**Comment by aleos89** [comment]
Could you provide the dump?

Also, can you provide a specific hash please. Thanks.

**Comment by Atemo** [comment]
Using 195a5254a76488890e008c915eeb976cc9c54be9 I can't reproduce this issue.
Sample:
```izlude,130,140,4	script	ghbhggg	45,{
	instance_create("Endless Tower");
	instance_enter("Endless Tower");
	end;
}
```
I created a party of 2 members, one is warped in the instance, the leader is deleted via login creation window.

**Comment by Lemongrass3110** [comment]
Try to merge 5ef2000 this is most obviously related to the issue @aleos89 fixed back then.

**Comment by Uruniz** [comment]
@Lemongrass3110 Thank you!

Please consider this issue resolved. I apologize for the lack of details in this report.  @aleos89 I'll be sure to include git hash, and core dump logs the next time, should I run into any segmentation crashes.

Thank you for the prompt reply.
