### ISSUE TITLE
KG_KAGEHUMI Skill Bug

### ISSUE THREAD

**Issue by alxalmora** [rathena/rathena#1367]
https://www.youtube.com/watch?v=0Mr88F3jW-U Minute 1:25
A player can move with this skill enable, and actually I can't move, works fine but player gets static position like hidding.
Using Last version or rA.

**Comment by benching** [comment]
when under shadow trampling effect, movement is restricted,
but movement skill like backsliding should do.

**Comment by aleos89** [comment]
You're confusing Kagehumi with Shadow Jump. Two different skills.
