### ISSUE TITLE
command @ii crash server

### ISSUE THREAD

**Issue by nykuz85** [rathena/rathena#1368]
on the latest rathena when using `@ii` or `@iteminfo` + item name the server send a crash signal.

**Comment by tlacson7** [comment]
it didn't crash my map but it shows double info
@ii Fire_Arrow
Item: Fire_Arrow /"Fire Arrow[0]" (1752) Type: Arrow | Extra Effect With script
NPC Buy: 3z Sell 1z | Weight 0.2
NPC Buy: 3z Sell 1z | Weight 0.2  <-doubled

**Comment by nykuz85** [comment]
i am using renewal system, no custom items on db. so No idea XD

**Comment by Lemongrass3110** [comment]
Latest is not a valid git hash. Please provide the one you used.

Is this happening on all items or just certain ones?
Are you using sql tables or txt tables?

**Comment by nykuz85** [comment]
client 2015-11-04 , it happen with ll items, if i write ii or iteminfo alone nothing happend but if i write ii poring card or iteminfo poring card it sends a crash signal. i tryed with both, txt and sql.

**Comment by secretdataz** [comment]
@nykuz85 What about the Git hash of rAthena you are using?
The server outputs Git hash at start.

**Comment by technoken** [comment]
Hash: 30ca9135588747bde05745b41994b093154fb223
Mode: Pre-renewal
Client 2013-12-23
No custom item
No src mods

it's also showing double info.

**Comment by cydh** [comment]
The double info appears since "someone commit" more than weeks, months I
think. (Just too lazy cleanup that one's mess)

**Comment by Atemo** [comment]
I can't reproduce the crash, maybe a client/packet issue?

**Comment by Lemongrass3110** [comment]
Sorry I mistook @technoken for the author.
We are still missing the hash for the crash. The duplicate message should be solved by now.

**Comment by aleos89** [comment]
Using b2fedb8 I was unable to reproduce this issue using 2015-11-04.
