### ISSUE TITLE
pc_bonus2: unknowk type 0 2 10

### ISSUE THREAD

**Issue by bhily** [rathena/rathena#1369]
https://s31.postimg.org/pw2xo27x7/error.png

What should I do? this warning always makes map server crash...

**Comment by secretdataz** [comment]
Please provide needed information about your mode (pre-re or renewal) and git hash.
This probably is an error in your database.

**Comment by dragonis1701** [comment]
That has to do with items using the incorrect bonus script command. Usually it is SP related commands and a few with box related drops.

**Comment by Lemongrass3110** [comment]
One of your item scripts is wrong.
Please use the board for getting help.
Thank you.
