### ISSUE TITLE
NPC_PROVOCATION wrong effect?

### ISSUE THREAD

**Issue by dragonis1701** [rathena/rathena#1373]
According to iRO, the page for this skill calls the skill Self Destruction and is provoke but without the atk increase and vit-def being reduced to 0. On rAthena, the skill only makes mobs drop target. 

http://irowiki.org/classic/NPC_PROVOCATION

**Comment by secretdataz** [comment]
I don't see anything related to Self Destruction on the page, or I'm just blind.

**Comment by dragonis1701** [comment]
It's in big bold text underneath "Description"

**Comment by secretdataz** [comment]
Ok, I'm blind. 
Though, we don't consider as a credible source. This needs further official info, because that naming can be just a copy-paste mistake from the wiki author. Its behavior also needs more testing.

**Comment by dragonis1701** [comment]
I'll see what I can do.

**Comment by secretdataz** [comment]
We have the correct behavior. Closed.
