### ISSUE TITLE
Experience Bug

### ISSUE THREAD

**Issue by rubie123** [rathena/rathena#1374]
My revision is: 18387  
Emulator: Rathena

Experience gained from monsters seem to be bugged.
My base and job exp rates are set to 25x in battle/exp.conf

```
// Rate at which exp. is given. (Note 2)
base_exp_rate: 2500

// Rate at which job exp. is given. (Note 2)
job_exp_rate: 2500
```

A poporing (ID 1031) should be giving 198 x 25 = 4950 exp, but it only gives 1980 (which is x10).
When I type @rates it shows the correct rates 25x 25x, but the monsters are giving experience worth x10.

I tried setting the exp rates to higher rates, and faced the same issue depending on the rates.

**Comment by Atemo** [comment]
Renewal ? Level penalty enabled ?

**Comment by rubie123** [comment]
Yes and yes.
