### ISSUE TITLE
Errors/Warnings: Latest revision 

### ISSUE THREAD

**Issue by rubie123** [rathena/rathena#1375]
After updating my server to revision 18387, I got the following errors/warnings:

> [Error]: pc_readdb_job_exp: Number of columns 53 defined is too low for max level 60.
> [Error]: sv_readdb: Could not process contents of line 45 of "db/re/job_exp.txt".
> [Warning]: Class Expanded Super Novice (4190) does not have a job exp table.
> [Warning]: Class Expanded Super Baby (4191) does not have a job exp table.
> [Warning]: Class Kagerou (4211) does not have a job exp table.
> [Warning]: Class Oboro (4212) does not have a job exp table.
> [Warning]: Class Rebellion (4215) does not have a job exp table.

**Comment by aleos89** [comment]
Renewal: https://travis-ci.org/rathena/rathena/jobs/138589017
Pre-Renewal: https://travis-ci.org/rathena/rathena/jobs/138589018

I don't see those errors.
