### ISSUE TITLE
0 EXP Oddities

### ISSUE THREAD

**Issue by dragonis1701** [rathena/rathena#1383]
* [x] If a mob gives 1 base exp and 0 job exp, like the novice fabre, the player who kills the mob will gain 1 base exp and 1 job exp.

* [x] If a mob gives 0 base exp and 0 job exp, like a mushroom, the player will gain 0 base exp and 0 job exp.

* [x] If a mob gives 0 base exp and 0 job exp, like a mushroom, and the player is in a party with even share exp, everyone in the party will gain 1 base exp and 1 job exp.

**Comment by cydh** [comment]
Point 1 & 2, seems invalid, the 3rd is confirmed.
