### ISSUE TITLE
ALL_FULL_THROTTLE icon time

### ISSUE THREAD

**Issue by julia40124009** [rathena/rathena#1384]
ALL_FULL_THROTTLE skill status icon not show 30s Countdown time

version : https://github.com/rathena/rathena/commit/6412c82d5939dfd60cc17c3e2a8364b6282c92f8
mode : renewal
client : 20151104

**Comment by Lemongrass3110** [comment]
Hey @julia40124009 thanks for your report.
We need official confirmation, that this status displays the rest of the time though, before we can fix it though.
If you want to fix it for your server in the meantime, you can do so by commenting this line:
https://github.com/rathena/rathena/blob/master/src/map/status.c#L10331
