### ISSUE TITLE
Cash Shop Blank Image

### ISSUE THREAD

**Issue by dragonis1701** [rathena/rathena#1386]
For some reason, at (supposedly) random intervals in the menu, items have their image missing from the Cash Shop item list. For example, in the screenshot, you can see that the item "Snow Cone Hat" has no image but you can see the item itself does have the collection.bmp image in the grf.
http://i207.photobucket.com/albums/bb64/Evensean021502/screenDecentRO006_zpsnm5hpoa3.jpg
If I add a random item afterwards, you can see the "blank" space is now taken up by another item, so it seems to be the cash shop itself rather than a specific item.
http://i207.photobucket.com/albums/bb64/Evensean021502/screenDecentRO007_zps1ceuku4f.jpg

**Comment by secretdataz** [comment]
Seems to be a client bug.
