### ISSUE TITLE
No NPCs in training ground

### ISSUE THREAD

**Issue by zackdreaver** [rathena/rathena#1387]
Mode: PreRenewal
Hash: bea47eac42e89217c194f3a08391796d6945ab90
Client: 2010-04-20

There are no NPCs on these maps, just warp portals:
new_2-1
new_3-1
new_4-1
new_5-1

**Comment by LiamKarlMitchell** [comment]
Yeah, wrong training ground maps.
Just use the 1 map for pre-renewal, No need for so many...
You will want to change the map in your config for login or char i think? i forget which :).
