### ISSUE TITLE
Poison status icon

### ISSUE THREAD

**Issue by zackdreaver** [rathena/rathena#1388]
Mode: PreRenewal and Renewal
Hash: bea47eac42e89217c194f3a08391796d6945ab90
Client: 2010-04-20 and 2015-11-04aRagexe

based on my issue:
http://herc.ws/board/tracker/issue-8585-poison-status-icon/

This issue also exists in ra
my quote from issue page
"I've checked this with openkore, Herc use "EFST_CLOUD_KILL" on Poison state, intended?"

**Comment by zackdreaver** [comment]
yeah look like its related.

btw, kRO uses these for poison state:
EFST_HEALTHSTATE_POISON

not EFST_CLOUD_KILL

**Comment by Lemongrass3110** [comment]
This comes from https://github.com/rathena/rathena/blob/master/src/map/status.c#L756 which calls set_sc and sets the icon on https://github.com/rathena/rathena/blob/master/src/map/status.c#L175 because it does not have a status icon yet.

**Comment by Lemongrass3110** [comment]
This was fixed in e5a197ad70d650d1532d196e198d9e5738f78031
