### ISSUE TITLE
Equipments aren't directly equipped when clicked

### ISSUE THREAD

**Issue by zackdreaver** [rathena/rathena#1389]
Mode: PreRenewal
Hash: bea47eac42e89217c194f3a08391796d6945ab90
Client: 2010-04-20

You have to relog or change map to see equipped items.
Apply to all equipments : Head, armor, weapons, etc

**Comment by zackdreaver** [comment]
I got this when testing with openkore
"Unknown Packet 08D0"

**Comment by jgoog999** [comment]
I got this same problem, using 2010-06-16aRagexeRE client, maybe @Lemongrass3110 can check this?

**Comment by Lemongrass3110** [comment]
@zackdreaver please make sure to have the correct version in your clientinfo.xml

Since our packet version 25 starts with 2008-09-10aRagexeRE and ends with 2010-11-24aRagexeRE the problem could be caused from there.
All clients in this range are forced to send out the following structure, since it is set for this version:
```
//2010-06-29aRagexeRE
0x00AA,9,ZC_WEAR_EQUIP_ACK,2:4:6:8
```

**Comment by jgoog999** [comment]
@Lemongrass3110 @aleos89 @cydh Help? :+1:

**Comment by cydh** [comment]
@jgoog999 
* I don't even have the client
* Not a recommended client for rA

**Comment by zackdreaver** [comment]
I have the correct stuff, and have tried some workarounds, nothing work.
no problem with the other emu, only rA has the issue.

**Comment by Lemongrass3110** [comment]
hey @zackdreaver 
I dont have any 2010 client at hand anymore, but could you test this for me:
https://github.com/rathena/rathena/commit/3f96d97e2dcebe3ccd44b2052fffee99163338de
Thanks.

**Comment by zackdreaver** [comment]
It's only fixes the equipment window,
you still need to relog to see both headgear and weapon sprite.
The client: [2010-04-20aRagexeRE.zip](https://github.com/rathena/rathena/files/412647/2010-04-20aRagexeRE.zip)

**Comment by feltenc** [comment]
Works fine on 2010-07-30 tested here. I dont have a older client so i cant reproduce, but its working fine on 2010-7-30.

**Comment by zackdreaver** [comment]
@feltenc 
I've provided the client in my comment above.

**Comment by Akkarinage** [comment]
Since this pertains to an unsupported client, i'm not sure if this needs to stay open or not.

**Comment by Lemongrass3110** [comment]
@zackdreaver could confirm if this issue has been fixed by f0ab8d2.
Judging from the code it should be fixed now, but that client does not run on my system anymore. Seems to be incompatible with Windows 7 x64. Or i'll probably do not have a required VC++ redistributable installed?

**Comment by zackdreaver** [comment]
Yes, it has already been fixed.
Thanks

**Comment by Lemongrass3110** [comment]
Thanks for testing and confiming that it is working. 👍
