### ISSUE TITLE
Vacum extreme

### ISSUE THREAD

**Issue by MrAntares** [rathena/rathena#139]
Git Version: **12628 - 2014-12-04 05:04:30 (luciar)**
Client Date: **2012-04-10**
Src Mods: **NONE**
General settings: 
- **Full Renewal**
- **1/1/1/1/1 rate**
- **PK server (not in towns, above lvl 30)**
- **PVP ATK/Skill modifers: 100%**
- **WOE ATK/Skill modifers: rA default**
- **Official walk path and stacking**
- **Exp and drop penalty table values below 100% set to 100%**
- **Party and attacker exp bonus: +40%**
- More at (Hungarian, use translate): http://wiki.ragna.ro/

How to reproduce: **Use the skill**
Description:

The recurring issue has returned once again. Latest vers, re, pk server, 20140410 client, vacuum extreme does not stop monsters. Neither moving ones, nor static ones from starting to move.

**Comment by MrAntares** [comment]
Actually, the suck-in effect doesn't work either. Mobs don't get pulled in the middle, they are just pulled back to the cell where they first encountered the AoE. That is the only thing that is working in this skill right now.

**Comment by Lemongrass3110** [comment]
I just wanted to report this one too.
As @MrAntares stated neither the suck in takes place nor does the movement blocking.

**Comment by cydh** [comment]
I have the diff to fix this :P

**Comment by MrAntares** [comment]
Uhm, is this gonna make into master?

**Comment by raynra** [comment]
I will be applying this fix and the followup:
https://github.com/rathena/rathena/commit/1970921f31705982f784bf7b48075b3b3f415302
to my live server. It tested well on my test server. Will see if there are any issues on live :+1:

**Comment by aleos89** [comment]
Fixed in ed9dcb8.
