### ISSUE TITLE
[BUG] Vellum Katzbalger high damage

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#1390]
The BUG is easy to be generated. With the Royal Guard class, use the sword 21002, Velum_Katzbalger.

Use the ability Exeed break. The damage is very high. It can be tested on another player in PvP or GvG.
- The bonus: bonus3 bHPVanishRaceRate, RC_Player, 10000.8; 

It is affecting the abilities as Exeed Break.

If damage with a strong sword reaches 8k, with this bug damage exceeds 100k.

**Comment by aleos89** [comment]
Duplicate of #1262. This was fixed in db0f231.
