### ISSUE TITLE
Cart is not shown after relog on 2012-04-10

### ISSUE THREAD

**Issue by paecantalup** [rathena/rathena#1391]
latest rAthena
Mode: PreRenewal - Renewal
Client: 2012-04-10

![untitled](https://cloud.githubusercontent.com/assets/12905780/16411078/90fd273a-3d4f-11e6-8918-35886da3a3ce.png)

i can rent a cart but after i logout and login again no cart dislay
then i can't get another cart because kafra said i already have cart 
when i press alt + Q can't off cart but still can vending shop

![untitled3](https://cloud.githubusercontent.com/assets/12905780/16411386/fee1996a-3d50-11e6-9d0a-06dec219f4e8.png)

sry for my bad english

**Comment by paecantalup** [comment]
updated

**Comment by secretdataz** [comment]
to English-speaking readers: I just tell him to check some settings.

ลองเช็คดูว่า `packet_db_ver` ใน `db/packet_db.txt` ว่าเป็น 30 หรือไม่
ลองเช็คค่า `PACKETVER` ใน `src/common/mmo.h` ว่าตรงกับวันที่ของ client หรือไม่
ถ้าทำสองอย่างนี้แล้วยังเป็นอีก ลองเช็คดาต้าให้แน่ใจว่าดาต้าไม่มีอะไรผิดปกติครับ

**Comment by paecantalup** [comment]
src/common/mmo.h
#define PACKETVER 20120410

db/packet_db.txt
packet_db_ver: 30

ดาต้าตัวนี้ใช้อยู่กับ SVN 17696 ไม่มีปัญหาครับคิดว่าไม่น่าจะเกี่ยวกับดาต้าครับลองดูในบอร์ดมีคนเป็นอยู่ 2 คนเหมือนกันครับ อาการเดียวกันเลย exe 20120410 เหมือนกัน
https://rathena.org/board/topic/106232-help-cart-wont-show-20120410-latest-rathena/?hl=cart
https://rathena.org/board/topic/106331-help-new-svn-version-copy-from-github-error-on-cart/?hl=cart

**Comment by secretdataz** [comment]
ก่อนอื่นก็ขอแจ้งให้ทราบก่อนว่า rAthena เลิกใช้ SVN แล้วครับ เวอร์ชั่น 17696 นี่เก่ามากเลย
แนะนำให้โหลดตัวใหม่จาก Github ไปลองคอมไพล์ดูครับ ได้ผลยังไงแจ้งด้วยนะ

**Comment by paecantalup** [comment]
ตัวที่บัคคือตัวที่ผมโหลดจาก github ล่าสุดเลยครับแล้วก็แก้แค่ PACKETVER  กับ packet_db_ver
ส่วน SVN 17696 คือตัวที่ผมเคยใช้พอดีผมอยากได้ตัวล่าสุดผมเลยโหลดจาก github มา แล้วก็บัคอย่างที่แจ้งครับผม

**Comment by secretdataz** [comment]
ลองเปลี่ยนตัว client ดูได้ไหมครับ

**Comment by paecantalup** [comment]
เมื่อกี้ลอง client  2013-08-07
ไม่มีอาการบัคครับ ออกเกมเข้าใหม่รถเข็นขึ้นปกติครับ

**Comment by Lemongrass3110** [comment]
Confirmed on 1ea0e3899c3716c38648492b77c4fa0808300d66 with 2012-04-10.

**Comment by anacondaqq** [comment]
confirmed too... Are there was any cart related updates? O.O

**Comment by anacondaqq** [comment]
The problem somewhere with ****OPTION_CART****.

```
@cart 1 - do not work
@cart 2 - works fine, but give cart 1
@cart 3 - do not work
@cart 4 - do not work
```

**Comment by anacondaqq** [comment]
Dear Developers, i want to upgrade rAthena to latest revision, but because of this bug i can't to do that. This is very critical for my players to not see cart on 2012-04-10 game client. Can you please fix the issue? Thank you very much.

**Comment by cydh** [comment]
Ok, I got it

**Comment by anacondaqq** [comment]
Hi, i will implement this fix and will notify you about results.

**Comment by anacondaqq** [comment]
Hi, i do not know technical details how it works now, but it's works now fine. Maybe need to close it? (i do not know)

**Comment by Lemongrass3110** [comment]
Did you test it with cydh's fix applied or on master?

**Comment by anacondaqq** [comment]
2 days after cydh made a fix: https://github.com/rathena/rathena/commit/0647b159a8c6e96024deb72e63b1ce9e9a23320a
i merge latest commits to my master branch. So i have not latest rAthena, but <cydh commit + 2 days> commit. And for around 7-8 days it was in my server under player tests. Nobody said anything bad against it. I can wait more, and try to test manually by myself if it needed.

**Comment by pachupappy** [comment]
guys how can I apply Cydh's Fix? I copied status.c pc.c clif.c in my server and I'm receiving errors. anyone knows? sorry I'm a newbie.
