### ISSUE TITLE
Client Freezing

### ISSUE THREAD

**Issue by technoken** [rathena/rathena#1393]
Im using Git Hash: 562a1a7b61e81b66de2a7896a2589d357164e8f0
Mode: Pre-renewal
Client: 2013-12-23
No src modification
Running my test server on windows 7 w/ xampp v.3.2.2

Somehow it is related to this issue https://github.com/rathena/rathena/issues/1335

My client still freezes whenever I spawn a monster(I spawned a poring) and hit it. No errors shown.
While frozen, I access my database(localhost/phpmyadmin) and go to log db.
After clicking the log db, this error appear on my mapserver.
```
[SQL]: DB error - Table '.\log\picklog' is marked as crashed and should be repai
red
[Debug]: at ..\src\map\log.c:228 - INSERT DELAYED INTO `picklog` (`time`, `char_
id`, `type`, `nameid`, `amount`, `refine`, `card0`, `card1`, `card2`, `card3`, `
map`, `unique_id`, `bound`) VALUES (NOW(), '1002', 'M', '909', '-1', '0', '0', '
0', '0', '0', 'prontera', '0', '0')
```
When the error appeared, the client is back to normal and I can already move my character.
 
This always happen whenever I restart my xammp.
 
So what do you think? Is it because of the xammp? or rA files?
 
Thank you!

**Comment by secretdataz** [comment]
You have to repair your database as shown in the error.
This is not related to rA.

**Comment by technoken** [comment]
@secretdataz can you tell me how should I repair it? I already deleted the whole log db and import the logs.sql provided by rathena. And this error is still showing up.

**Comment by lighta** [comment]
try this:
http://dev.mysql.com/doc/refman/5.5/en/repair-table.html
So : REPAIR Table picklog;

**Comment by technoken** [comment]
@lighta Thanks! :+1:
