### ISSUE TITLE
0 Exp Display In Even Share Party

### ISSUE THREAD

**Issue by dragonis1701** [rathena/rathena#1394]
If you are in a party that has Each Take EXP or just solo, the player will not see the "You have gained X EXP" if the monster gives 0 exp, like Mushrooms but if a player is in a party that has Even Share EXP, it will show the "You have gained 0 EXP" every time, for all the players in the party.

**Comment by cydh** [comment]
actually u already mentioned them here #1383 and I replied and fixed.

if monster gives no EXP, there's no EXP message, so what u said is intended.
> but if a player is in a party that has Even Share EXP, it will show the "You have gained 0 EXP" every time, for all the players in the party.

I can't confirm this. I tested.
