### ISSUE TITLE
NPC_Metamorphosis Makes Infinite Mobs

### ISSUE THREAD

**Issue by dragonis1701** [rathena/rathena#1395]
If you have mob_ai 20 active so that all mobs are active on a map, any mob with NPC_Metamorphosis will use the skill and change from X mob to Y mob but then X mob respawns, so if a player stays on a map long enough, it keeps adding mobs. For example, after sitting for a day on a map with Thief Bugs, it got to the point where there were over 3000 thief bugs.

**Comment by Playtester** [comment]
A monster should not respawn after metamorphosis. It keeps the same ID.

**Comment by dragonis1701** [comment]
Mmm... I figured out what it was. Nevermind, this is invalid.
