### ISSUE TITLE
Buying Store Crashing Map Server

### ISSUE THREAD

**Issue by dragonis1701** [rathena/rathena#1398]
If you have a message_size higher than default, 79 + 1, opening a buying store will crash the map server.

**Comment by Lemongrass3110** [comment]
Hey @dragonis1701,
which client date are you using?

**Comment by dragonis1701** [comment]
2013-08-07 but it doesn't crash my client, only the map server~

**Comment by Lemongrass3110** [comment]
Confirmed on b8a221f.

As a temporary fix you can go into your packet db and edit the following line:
```
...
//2013-08-07Ragexe
packet_ver: 45
...
0x0815,-1,reqopenbuyingstore,2:4:8:9:89
...
```
You need to adjust the 89 to fit your MESSAGE_SIZE. It should be MESSAGE_SIZE + 9.

**Comment by dragonis1701** [comment]
I just changed the Message_size to 79 + 1 in clif_buyingstore_entry and clif_buyingstore_entry_single. Then changed the Message_Size in clif_parse_ReqOpenBuyingStore to 36 + 1. That has been working fine for me.

**Comment by lighta** [comment]
If MESSAGE_SIZE>original, I suppose you would need to edit this as well ```uint8 buf[86];```
```void clif_buyingstore_entry(struct map_session_data* sd)
{
//uint8 buf[86];
uint8 buf = (uint8) aMalloc(6+MESSAGE_SIZE)

WBUFW(buf,0) = 0x814;
WBUFL(buf,2) = sd->bl.id;
memcpy(WBUFP(buf,6), sd->message, MESSAGE_SIZE);

clif_send(buf, packet_len(0x814), &sd->bl, AREA_WOS);
aFree(buf);
} 

So into something like this :

**Comment by Lemongrass3110** [comment]
@lighta that actually might be a problem, since it is a fixed size packet. This means that the client will possibly not be able to parse it correctly, since it will be compiled with 80 bytes in there.
So I guess we should cap the size to a constant maximum of 80 for the buyingstore and not support any longer names.
