### ISSUE TITLE
Thanatos Hammer can't be equipped

### ISSUE THREAD

**Issue by spinzaku** [rathena/rathena#1399]
git hash:

![githash](https://cloud.githubusercontent.com/assets/18629476/16388865/b4244888-3ccd-11e6-97da-c9a370de876c.png)

Players in my server couldn't equip Thanatos hammer.. found culprit.. and its named Tanos Axe ? 

`16028,Tanos_Axe,Tanos Axe,5,10,,3000,180:120,,,1,0x000654E3,63,2,2,4,120,1,6,{ bonus bInt,6; bonus bVit,6; bonus bLuk,-6; bonus bAtkRate,5; bonus2 bHPLossRate,100,10000; },{},{}`

i think it should be:

`16028,Thanatos_Hammer,Thanatos Hammer,5,20,,3000,180:120,,1,1,0x0004C5B2,63,2,2,4,120,1,8,{ bonus bInt,6; bonus bVit,6; bonus bLuk,-6; bonus2 bHPDrainRate,50,5; bonus2 bSPDrainRate,10,5; bonus2 bHPLossRate,100,10000; },{},{ heal -1000,0; }`

source:
http://www.divine-pride.net/database/item/16028/thanatos-hammer-1

**Comment by cydh** [comment]
except the `63` must be `56`
> Job : Swordsman, Merchant, and Acolyte 3rd Classes

**Comment by Playtester** [comment]
Make sure the aegis name really is Thanatos_Hammer before changing it, though.

**Comment by secretdataz** [comment]
kRO desc
```
	[16028] = {
		unidentifiedDisplayName = "둔기",
		unidentifiedResourceName = "해머",
		unidentifiedDescriptionName = { "감정되지 않음. [돋보기] 를 사용하여 감정할 수 있다." },
		identifiedDisplayName = "타노스의 망치",
		identifiedResourceName = "타노스의망치",
		identifiedDescriptionName = {
			"마검 타르타노스에 맞서기 위해 흙빛의 조각으로 빚어낸 마력을 지닌 망치.",
			"강력하지만 대가가 따르는 힘과 마력을 지니고 있다.",
			"",
			"INT + 6 / VIT + 6 / LUK -6",
			"물리 공격 시, 낮은 확률로 데미지의 5% 를 HP, SP 로 흡수.",
			"10 초 당 HP 100 감소.",
			"장비 해제 시, HP 1000 감소.",
			"MATK + 120",
			"",
			"계열 : ^777777둔기^000000",
			"공격 : ^777777180^000000",
			"무게 : ^777777300^000000",
			"무기 레벨 : ^7777774^000000",
			"요구 레벨 : ^777777120^000000",
			"장착 : ^7777773차 검사/상인/복사계열^000000"
		},
		slotCount = 1,
		ClassNum = 8
	},
```

**Comment by secretdataz** [comment]
타노스의 망치 = Thanos's Hammer
I'll keep the old name and only change the job and class field.

**Comment by reigneil** [comment]
@secretdataz
if you look again the item description it say ClassNum = 8 so this must be Mace not Axe.
