### ISSUE TITLE
GTB should bypass

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#1400]
GTB should bypass these skills:

White Imprison
Masquarade skills
Genetic skills

Source: pRO and iRO according to other bug reports and forum entries
http://forums.irowiki.org/index.php?topic=106953.0

**Would be great if this could be tested and fixed accordingly.**

**Comment by RagnarokNova** [comment]
Checked on Aegis:
White Imprison was blocked by GTB.
Masquerades were NOT blocked by GTB.
Hallucination Drug was blocked by GTB.
Hell Plant was blocked by GTB.
Fire Expansion was blocked by GTB.
All other Genetic skills were not blocked by GTB.
