### ISSUE TITLE
Follow up to #1394 @cydh

### ISSUE THREAD

**Issue by dragonis1701** [rathena/rathena#1401]
Downloaded fresh rAthena, no edits other than turning off Packet_Obfuscation and switching from renewal to pre-renewal. This happens on both Renewal and Pre-renewal. **It only happens if you are in a party and the party has even share enabled.** Also make sure you have atcommandshowexp enabled. Please look at the screenshots below and you will see the proof of it.

Killing a mushroom with Each Take Experience Party:
http://i207.photobucket.com/albums/bb64/Evensean021502/screenDecentRO015_zpscaly9chj.jpg
Notice you don't see the text after that mushroom died.

Kill a mushroom with Even Share Experience Party:
http://i207.photobucket.com/albums/bb64/Evensean021502/screenDecentRO016_zpsyumo0qpr.jpg
Now notice you can see the Experience Gained Base:0 (0.00%) Job:0 (0.00%)

As I mentioned above, I have edited nothing with these server files other than packet_obfuscation and downloaded the most up to date rAthena.

**Comment by aleos89** [comment]
That's the one bit of crucial information you left out in your other 2 reports. You never stated it was from `@showexp` so we were all assuming it was the client's exp display packet.

**Comment by Lemongrass3110** [comment]
Also please try to use github for your photos in the future.
You just need to drag and drop them into your browser and they will be uploaded and stored on github.
