### ISSUE TITLE
Bugs: bioethics skill loss after reborn

### ISSUE THREAD

**Issue by AbuGosok** [rathena/rathena#1408]
**How to reproduce:**
Latest rAthena. Do not use custom jobmaster. Let's do normal official quest. Make a Novice > Merchant > Alchemist. Then you take Bioethics skill quest http://irowiki.org/wiki/Alchemist_Skill_Quest

You will get bioethics quest (necessary to make homunculus). Then you went reborn > High Novice > High Merchant. When you talk with the biochemist NPC in valkyrie maps, you will become Creator and still does not get your bioethics skill. You are supposed to get this skill back by talking with the NPC again, but unfortunately it does not.

**Why does this happened?**
There is a logic flaw in npc/jobs/2-2a/Creator.txt

```
if (ADVJOB == 0 || Upper != 1) {
	//Will get triggered if your ADVJOB char_reg_num is not set OR you are advanced (not normal and baby)
}
else if (ADVJOB == Job_Creator && Class == Job_Merchant_High && JobLevel > 39) {
	//This get triggered when you change from Merchant high to Creator
	jobchange Job_Creator;
	set ADVJOB,0; //Wait whut?
	//blablabla
}	
else {
	if (Class == Job_Creator && bioeth == 13 && getskilllv("AM_BIOETHICS") == 0) {
		//This is supposed to trigger if you are creator && already finished bioethics quest && does not have your skill back due to reborn
		skill "AM_BIOETHICS",1,SKILL_PERM;
		//blablabla
	}
}
```

The last IF statement will never get triggered because the first IF statement of "ADVJOB == 0" will always fulfilled after you change job to creator (look at set ADVJOB,0; on second IF statement).

Same problem in Hercules as well because the script is the same: http://herc.ws/board/tracker/issue-8154-platinum-skill-loss-upon-rebirth/

**Comment by Lemongrass3110** [comment]
On AEGIS the variable does not get reset, this is why it does not have this problem.
This goes for all the npcs in valkyrie.
It only seems to be problematic with the homunculus skills though.
