### ISSUE TITLE
Assassin Guildmaster NPC should be on touch event

### ISSUE THREAD

**Issue by zackdreaver** [rathena/rathena#1409]
Mode: Renewal and Prerenewal
Hash: b1b43bb0dfd4bb533a7334dcba7928126389a5c2

Assassin Guildmaster NPC should be "on touch event" NPC, not "on click event" NPC.

**Comment by cydh** [comment]
The NPC on last room that will turn the thief becomes assassin? yes it must be ontouch event.

**Comment by zackdreaver** [comment]
yes

**Comment by Atemo** [comment]
You mean [Guildsman](./rathena/blob/master/npc/jobs/2-1/assassin.txt#L56) NPC ?

**Comment by zackdreaver** [comment]
but it's clickable

**Comment by Atemo** [comment]
From our leak  [this NPC](../blob/master/npc/jobs/2-1/assassin.txt#L56) is only clickable and [this one](../blob/master/npc/jobs/2-1/assassin.txt#L297) is clickable + work with OnTouch. If it's not about these NPC please provide the name or screenshot/video of your issue thanks !

**Comment by cydh** [comment]
The `Guildmaster#ASN2` has `OnTouch` but sine it has no `end;` in the first
line, Thieves who are insight, can complete the quest by clicking it.
Thieves **supposed to** walk over him so they can complete the quest.
