### ISSUE TITLE
Instance Sealed Shrine Bugs

### ISSUE THREAD

**Issue by spinzaku** [rathena/rathena#1410]
Reported by my players and tried myself

git hash:
![screenandzro071](https://cloud.githubusercontent.com/assets/18629476/16518303/b9805742-3fb4-11e6-988d-f66134b66c1b.jpg)

Talked to the NPC as Party Leader.. then Activate Torches..

Went to the torches.. Can't Click any of the Torches.. can't get Essence Of Fire... oh yes i tried clicking everywhere, fire, and even the ground near it.
![screenandzro070](https://cloud.githubusercontent.com/assets/18629476/16518333/d4da1550-3fb4-11e6-8df0-05d2b8744bca.jpg)

Can't also find any mobs that drop Token of Apostle.. which is dropped by apostles.. but none are spawned?

Am i doing something wrong? someone could give me a guide or how should it work?

**Comment by Paoly28** [comment]
you should read ALL the options not just one or two, you can't skip, then after reading all the options, select ready or something like that, it should trigger the next step.

**Comment by spinzaku** [comment]
I read all options.. and nothing worked. my players also. Is there like a correct order?

**Comment by Paoly28** [comment]
1,2,3 then proceed

**Comment by spinzaku** [comment]
will inform my players again. can't test myself now

**Comment by Paoly28** [comment]
you shouldn't close the selection menu.

**Comment by Atemo** [comment]
Invalid. I just tested the instance working fine. Please read a guide, for example [http://irowiki.org/wiki/Sealed_Shrine_Quest](url)
