### ISSUE TITLE
Fenrir Card

### ISSUE THREAD

**Issue by Jeybla** [rathena/rathena#1414]
> 4556,Fenrir_Card,Fenrir Card,6,10,,10,,,,,,,,769,,,,,{ bonus bMatk,50+getrefine()*5; bonus bFixedCast,-70; },{},{}

Should have bFixedCastRate instead of bFixedCast:
```
bonus bFixedCastrate,n;        		Increases fixed cast time of all skills by n% (has effect in RENEWAL_CAST only)
bonus bFixedCast,t;            		Increases fixed cast time of all skills by t milliseconds (has effect in RENEWAL_CAST only)
```

http://db.irowiki.org/db/item-info/4556/
http://ratemyserver.net/re_item_db.php?item_id=4556&ird=0&small=1&back=1

> 4556,Fenrir_Card,Fenrir Card,6,10,,10,,,,,,,,769,,,,,{ bonus bMatk,50+getrefine()*5; bonus bFixedCastrate,-70; },{},{}

**Comment by secretdataz** [comment]
Fixed in 15c382e
