### ISSUE TITLE
Gypsy skill makes mapserver crash

### ISSUE THREAD

**Issue by Rory12** [rathena/rathena#1416]
Hello,
I am using the lastest rathena, and my map server crashed. Before the crash, i've got this error:

```
[Debug]: status_change_end: SC_DANCING is missing skill unit group (val1=655690, val2=4142, val3=138, val4=0, timer=272, tid=-1, char_id=150390, map=louyang, x=216, y=98, prev=:0, from=skill.c:7064). Please report this! (#3504)
[Debug]: skill_delunitgroup: group is NULL (source=status.c:11362, status_change_end_)! Please report this! (#3504)
```

I am using the 2013-08-07 client and on Pre-RE mode. Any fix?
Thank you.

**Comment by aleos89** [comment]
Can you explain the scenario you used to reproduce the crash?

Also, can you please provide a specific Git hash? Thanks.

**Comment by Rory12** [comment]
Hello,
Well there is no predefined scenario, it just happen sometimes when some players on my server (always Clowns or Gypsy) launch one of their songs/dances. Then everyone is disconnected and the mapserver crashes. It doesn't happen all the time, just sometimes. To solve the issue and avoid other crashes I do "TRUNCATE TABLE sc_data;" to prevent it, until it happens another time.

Thank you.

**Comment by aleos89** [comment]
If you are able to find a way to successfully reproduce this then this can be reopened. Until then, I forced a null group at status_change_end with SC_DANCING and got the two debugs you did above but the map server doesn't crash.
