### ISSUE TITLE
Emergency Call Scrolls

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#1421]
Are these supposed to be usable by anyone?
I mean... normal players can actually abuse it to e-call an entire guild outside of the castle at the time they're trying to break the emp for instance.

I've had cases were opposite guilds joined their enemy guild at the last minute just to hold them back from breaking their emp.

**A Guild Leader only restriction would make sense**
_But who knows if that's official >_>_

**Comment by aleos89** [comment]
According to the castbegin checks, there is a guild master check:
```
		case GD_EMERGENCYCALL:
		case GD_ITEMEMERGENCYCALL:
			// other checks were already done in skill_isNotOk()
			if (!sd->status.guild_id || !sd->state.gmaster_flag)
				return false;
			break;
```
