### ISSUE TITLE
RG’s skill Overbrand does not due the third damge on the enemy those who cannot be knockback

### ISSUE THREAD

**Issue by skybook888** [rathena/rathena#1424]
the iro's wiki
http://irowiki.org/wiki/Overbrand

**Comment by Paoly28** [comment]
the wiki is outdated, boss flagged , woe flags ( noknockback from items to replicate woe no knockback mechanic ) doesn't proc the 3rd hit, the only way to get hit is by getting knockbacked into the wall, being hit by overbrand behind a wall will produce the same conditions as no knockback hence why it won't do 3 hits against targets directly behind a wall

**Comment by aleos89** [comment]
Related to an old bug report in [rAthena's Old Bug Tracker](https://rathena.org/board/tracker/issue-9096-sura-knuckle-arrow-knockback-bonus/).
