### ISSUE TITLE
the monster attack diagonally doesn't work. (character stopped and do not attack)

### ISSUE THREAD

**Issue by anacondaqq** [rathena/rathena#1427]
Mxxxxx
xxxxxxx
xxxxxxY

M = mob
Y = you

If you will use any skill to the target -> it will fail. (i'm talking not about AoE spells)
Horizontal / vertical aiming works fine. Only diagonal make some troubles.
#### How reproduce

```
Mxxxxx
xxxxxxx
xxxxxxY

```

Try like at ASCII table above, where Y = your character, and M = mob character (corner not nessesary).
Try to attack mob with for example Bash skill.
You will walk to the target, and then, you will stop and will NOT hit the mob.
### Technical Info
- Client-date: 2012-04-10
- Pre-renewal
- //// #define OFFICIAL_WALKPATH (disabled) / enabled - doesnot matter i have tried with and without walkpatch - > the same problem
- packet obf. disabled
- Revision: e771472042e1d83fefe4581b51ecdf554d8276bc  (latest (2016-07-14)
### How it looks like (20-30 MB of your traffic)

https://vgy.me/ZMRNdu.gif
### Very funny gif with really awesome explaining where is a bug:

TX
XX
XY

Where T = Target
Where Y = You
Where X = cells between you.

Try it, and you will see, that you will NOT attack enemy by skill. 

Extra info:

**Comment by anacondaqq** [comment]
Dear @Playtester please take a look. This bug related somehow to next lines of code:

**unit.c** unit_skilluse_id2

```
	// New action request received, delete previous action request if not executed yet
	if(ud->stepaction || ud->steptimer != INVALID_TIMER)
		unit_stop_stepaction(src);
	// Remember the skill request from the client while walking to the next cell
	if(src->type == BL_PC && ud->walktimer != INVALID_TIMER && !battle_check_range(src, target, range-1)) {
		ud->stepaction = true;
		ud->target_to = target_id;
		ud->stepskill_id = skill_id;
		ud->stepskill_lv = skill_lv;
		return 0; // Attacking will be handled by unit_walktoxy_timer in this case
	}

	// Check range when not using skill on yourself or is a combo-skill during attack
	// (these are supposed to always have the same range as your attack)
	if( src->id != target_id && (!combo || ud->attacktimer == INVALID_TIMER) ) {
		if( skill_get_state(ud->skill_id) == ST_MOVE_ENABLE ) {
			if( !unit_can_reach_bl(src, target, range + 1, 1, NULL, NULL) )
				return 0; // Walk-path check failed.
		} else if( src->type == BL_MER && skill_id == MA_REMOVETRAP ) {
			if( !battle_check_range(battle_get_master(src), target, range + 1) )
				return 0; // Aegis calc remove trap based on Master position, ignoring mercenary O.O
		} else if( !battle_check_range(src, target, range) )
			return 0; // Arrow-path check failed.
	}
```

### How reproduce bug:
![](http://i.imgur.com/58qTrfQ.png)
Please stand on the cells like me, and try to hit flower with any skill, and you can't do that.
Y C
C C
C M

Where Y = you, C = empty cell, MOB

**Comment by anacondaqq** [comment]
### Problem found: 

```
unit_skilluse_id()
int unit_skilluse_id2()
{
...

	// Check range when not using skill on yourself or is a combo-skill during attack
	// (these are supposed to always have the same range as your attack)
	if( src->id != target_id && (!combo || ud->attacktimer == INVALID_TIMER) ) {
		if( skill_get_state(ud->skill_id) == ST_MOVE_ENABLE ) {
			if( !unit_can_reach_bl(src, target, range + 1, 1, NULL, NULL) )
				return 0; // Walk-path check failed.
		} else if( src->type == BL_MER && skill_id == MA_REMOVETRAP ) {
			if( !battle_check_range(battle_get_master(src), target, range + 1) )
				return 0; // Aegis calc remove trap based on Master position, ignoring mercenary O.O
		} else if( !battle_check_range(src, target, range) )			// <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<-------------- Problem here
		 	return 0; // Arrow-path check failed.						// <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<-------------- Problem Here
	}

...
}
```

If remove these lines from code, EVERYTHING going to be OK.
But i guess this is not good solution, and need somehow optimize battle_check_range.

**Comment by Playtester** [comment]
The problem doesn't happen on my machine, but it could be a timing issue.

I could revert the range checks to +1, but it allows hacking for longer range again.

What I wonder is though, does it not trigger the step action?
```   if(src->type == BL_PC && ud->walktimer != INVALID_TIMER && !battle_check_range(src, target, range-1)) {```
Can you check why it doesn't go in here?

It's a player, he is currently walking and is not within range-1, so it should go in here first and then call the function again once the player is in range for the skill.

**Comment by KrokusPokus** [comment]
You mention a player currently walking, but isn't the PC standing still at the moment this happens? Or would he always already have started walking at the time we hit that part of the code?

For example, when I let a standing PC cast a skill on another PC/NPC who is exactly 1 cell out of range it hit's the line of code you mentioned in unit_skilluse_id2() always with these results:
(src->type == BL_PC) would be true
(ud->walktimer = INVALID_TIMER) would be false
(!battle_check_range) would be true.
The PC stands still not casting the skill nor does he start walking towards the target no matter how many times one clicks.

On the other hand, if the PC stands more than one cell out of range, it's always:
ud->walktimer != INVALID_TIMER
so the character starts walking closer, but weirdly not every click of the mouse even hits unit_skilluse_id2(). I often have to click several times for unit_skilluse_id2 to be called and the walking into range to begin.

**Comment by Playtester** [comment]
My client definitely sends a move request when I'm 2 cells north 1 cell west and use a range 1 skill like Bash. I move right next to the target and then use the skill.

How do you make it not send a move request?

**Comment by KrokusPokus** [comment]
I found out the cause, but the results are somewhat puzzling. Last time, I had compiled with CIRCULAR_AREA enabled, and as I said, my priest did not walk into casting range when he was situated exactly one step out of range.  Today I recompiled with CIRCULAR_AREA disabled, and casting worked ok again. The puzzling thing to me is what's going on package with (checked with wpe pro):

With CIRCULAR_AREA off, these packages were send/received by the client:
0x00a7,9,walktoxy,6			// Cliends sends request WalkToXY. Server executes clif_parse_WalkToXY()
0x0087,12				// Server notifies the client, that it is walking (ZC_NOTIFY_PLAYERMOVE).
0x0438,10,useskilltoid,2:4:6	// Client sends request for useskilltoid

With CIRCULAR_AREA on, only this package was send by the client (repeatedly too, when clicking repeatedly):
0x0438,10,useskilltoid,2:4:6	// Client sends request for useskilltoid

So, why would the client not send a walk request (0x00a7) in this case? Maybe the client thinks it's within casting range, but why would it assume that without asking the server? If there is something wrong with the distance check used with CIRCULAR_AREA, how would that influence the client without the client at this moment even asing the server for its opinion on the situation and jumping to the comclusion that it is in range, and so therefore should be able to use the skill without walking somewhere else first? The area the client thinks to be be "in range" and so won't try to WalkToXY doesn't seem to be congruent with the one the server is using, so the server dismisses the request for useskilltoid.

**Comment by anacondaqq** [comment]
@KrokusPokus my friend, are you kidding? I have tested it on clear rA and spent around 12 hours on debugging everything before posting any messages here at issue tracker. This issue exists, and this bug inside rAthena.
I haven't even said any criticism why this happened, I just showed the reason why it happened, and I leave current contributors which call they self "developers" to fix the issue. I already know how to fix it, and i wrote about it several times, but I hope someone in someday will develop a clear normal adequate fix, not dirty one like I did.

**Comment by KrokusPokus** [comment]
Problem is, I seem unable to cause the specific bug you showed to happen on my own server, so there's little I can do about it myself. You could try placing some sprintf() and OutputDebugString() in battle_check_range() and have a tool like DebugView running to find out which of the functions called there cause the range check to fail and for which input values.

**Comment by Playtester** [comment]
@anacondaqq 
Nobody from our devs can reproduce this bug, though. Increasing the range of all skills server-sided by "1" isn't really a fix, it's just going around the real problem (though I personally do recommend this change anyway, because while it allows hacking in WoE, it makes PVM a lot more smooth because if you have position lag you simply get more attack range).

I really wish I could reproduce this bug though, so I could run some tests on it.

@KrokusPokus 
To explain what you were wondering about: The client doesn't ask the server if a target is in range at all. Instead, the client knows the range of each skill and then decides itself if something is in range or not. So if you enable CIRCULAR_AREA, you change the ranges server-sided, but it doesn't make a difference on the client. So yeah, with that define it's very well possible that the client thinks it's in range while the server doesn't.

**Comment by anacondaqq** [comment]
this is not critical and urgent for now, i will try sometime soon to test everything on the latest revision, maybe something has been changed since posting issue. Anyway, thank you very much for your time.

**Comment by KrokusPokus** [comment]
@Playtester 
I did some more testing and think I know what was happening in my case (not being able to cast a skill at a certain distance but PC not walking in range either when using CIRCULAR_AREA). Obviously, what the client considered in range, and what the server thought legit was different, and the way the circular distance is calculated when CIRCULAR_AREA is disabled is closer to what the client does than with CIRCULAR_AREA enabled.

With CIRCULAR_AREA off and a PC, a code path is used that goes battle_check_range() -> check_distance_client_bl() -> distance_client().
distance_client() does sqrt((double)(dx*dx + dy*dy)), then unconditionally substracts 0.0625 to give some  then rounds down.
When dx=10 and dy=0 (a position the client considers in range and doesn't send a walktoxy package for), that would be floor((sqrt(100+0))-0.0625), so floor(9.9375), so the rounded down distance from casting to INT in this case will be 9, which equals this PC's maximum range for the skill I was trying. So the server allowed the skill.

With CIRCULAR_AREA on, the code path is used is battle_check_range() -> check_distance_bl() -> check_distance().
check_distance() does (dx*dx + dy*dy <= range*range + (dx&&dy?1:0). So for dx=10 and dy=0, it would be (100 + 0 <= 91 + 0), which would be false, so out of range, so the server ignores the client's request.

So two questions:
- Shouldn't the server's check_distance() with CIRCULAR_AREA enabled use the same way of calculating the circular distance as distance_client() does, which has slightly more leeway from rounding down the distance - something at least my 2010-07-30aRagexeRE client seems to expect.
- How come we use two slightly different approaches for circular distance anyway? Does the client expect different ways of calculating distance in diffent situations or are these just remnants of code restructuring?

**Comment by Playtester** [comment]
That's simply because CIRCULAR_AREA is an old custom eAthena mod. There's nobody in the staff left that has time tend custom features. But it's still left in for those that want to use it.

The official client formula for ranges I only figured out some years ago and implemented properly.

**Comment by KrokusPokus** [comment]
Then wouldn't it make sense to simplify check_distance() and distance() this way to get consistent behaviour:

```
bool check_distance(int dx, int dy, int distance)
{
#ifdef CIRCULAR_AREA
	return check_distance_client(dx, dy, distance);
#else
	if (dx < 0) dx = -dx;
	if (dy < 0) dy = -dy;
	return ((dx<dy?dy:dx) <= distance);
#endif
}

unsigned int distance(int dx, int dy)
{
#ifdef CIRCULAR_AREA
	return distance_client(dx, dy);
#else
	if (dx < 0) dx = -dx;
	if (dy < 0) dy = -dy;
	return (dx<dy?dy:dx);
#endif
}

```
Or, even neater, renaming
check_distance_client() -> check_distance_circular()
distance_client() -> distance_circular()
and adding an equivalent to distance_circular() called distance_square().
```
bool check_distance(int dx, int dy, int distance)
{
#ifdef CIRCULAR_AREA
	return check_distance_circular(dx, dy, distance);
#else
	return check_distance_square(dx, dy, distance);
#endif
}

unsigned int distance(int dx, int dy)
{
#ifdef CIRCULAR_AREA
	return distance_circular(dx, dy);
#else
	return distance_square(dx, dy, distance);
#endif
}

int distance_square(int dx, int dy)
{
	if (dx < 0) dx = -dx;
	if (dy < 0) dy = -dy;
	return (dx<dy?dy:dx);
}
```

**Comment by anacondaqq** [comment]
#Tested on latest revision

**hash**: 196017c9c4fec0226daae3cf36f4ed37e101270c
**client:** 2015-11-04aRagexe
All settings -> default, no source mods, no source changes.
Packet Obf. disabled. packet_ver: 55

# Results
Works fine, no issues at all like it was at first post.
I do not have 2012-04-11 game client for now to test it with latest revision, maybe it's client-based issue (this issue happened not only to me, but to different server developers at different RO servers, and yes, they are using mostly 2011-2012 game clients)

# Conclusion
Closing issue. If someone will experience it, that can be 2012-04-10 client problem.
