### ISSUE TITLE
MvP Tomb Spawntime

### ISSUE THREAD

**Issue by Jeybla** [rathena/rathena#1429]
On official servers MvP Tombs spawn a few seconds after the MvP is killed.

On rathena the MvP Tomb spawns immediately. So sometimes it's kinda hard to loot dropped Items near the tomb.

**Comment by cydh** [comment]
Yes, it's delayed. I was wondering what the delay for, like waiting reply
from server or just simply delay.
Just like the emper destroyed, the announcement (local and server wide) is
also delay.

**Comment by aleos89** [comment]
I've timed it to be about 9~ seconds.
