### ISSUE TITLE
Flying Galapago

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#1430]
Some effects are currently missing or simply wrong.
It's current effect does not match to the latest official jRO description.
Since it's quite a powerful gear, it would be great to have this working properly.

I can't read japanese but taken from the google translation +  a mix with the latest english translation this is what i come up with (should be pretty accurate)

5967 Flying Galapago

> increase the chance of auto casting Blitz Beat depending on your current lvl of Blitz Beat itself.
> On top of that LUK also increases it's chance however only up to 120 base luk.
> 
> ```
> If Steel Crow is learned, it increases Blitz Beat damage by 40% **(currently increases by 400%)!!!**
> ```
> 
> If equipped with Galapago Card: Increase apple, banana and carrot juice healing amount by 1000%
> 
> ```
> If equipped with Gryphon Card: Reduces after attack delay by 3%, ASPD+1, Physical ATK-5%
> If additionaly used with a bow and it's refining level reached 10 ~ Adds ASPD+1
> ```
> 
> If equipped with Condor Card
> Reduces damage taken from all elemental attacks -10%
> 
> ```
> If equipped with Cendrawasih Card
> INT+1
> Critical damage +5%
> If additionaly equipped by archer class increases critical damage additionaly by +15%
> ```
> 
> If equipped with Falconer Claw
> Reduces damage of Blitz Beat by -200%
> 
> ```
> Class: Headgear
> Defense: 0
> Location: Lower
> Weight; 50
> Level Requirement: 110
> Jobs: All classes
> 
> 
> ```

Official latest jRO description

> 5967#
> 空を飛ぶことに成功した
> ガラパゴ。
> いつの日か自力で空を
> 飛ぶ事を夢見ている。
> ―――――――――――――
> Agi + 1
> ―――――――――――――
> 物理攻撃命中時、
> 一定確率でオートスペル
> [ブリッツビート]が
> 習得Lvで発動
> [ブリッツビート]の
> 習得Lvが高い程、
> 発動率が上昇
> ―――――――――――――
> 純粋なLukが高い程、
> [ブリッツビート]の
> 発動率が上昇
> ただし、発動率に影響する
> 純粋なLukは最大120まで
> ―――――――――――――
> [スチールクロウ]の
> 習得Lvが1上がる度に追加で
> [ブリッツビート]で
> 与えるダメージ + 40%
> ―――――――――――――
> [ガラパゴカード]と
> 共に装備時、追加で
> [ニンジンジュース]、
> [バナナジュース]、
> [リンゴジュース]
> の回復量 + 1000%
> ―――――――――――――
> [グリフォンカード]と
> 共に装備時、追加で
> 攻撃速度 + 3%
> Aspd + 1
> 物理攻撃で
> 与えるダメージ - 5%
> 弓の場合で、
> かつ精錬値が10の場合、
> 追加でAspd + 1
> ―――――――――――――
> [コンドルカード]と
> 共に装備時、追加で
> 全ての属性攻撃で
> 受けるダメージ - 10%
> ―――――――――――――
> [極楽鳥カード]と
> 共に装備時、追加で
> Int + 1
> クリティカル攻撃で
> 与えるダメージ + 5%
> アーチャー系が装備時、
> 追加でクリティカル攻撃で
> 与えるダメージ + 15%
> ―――――――――――――
> [鳥狩の鉤爪]と
> 共に装備時、追加で
> [ブリッツビート]で
> 与えるダメージ - 200%
> ―――――――――――――
> 系列 : ^777777兜^000000
> 防御 : ^7777770^000000
> 位置 : ^777777下段^000000
> 重量 : ^77777750^000000
> 要求レベル : ^777777110^000000
> 装備 : ^777777全ての職業^000000
> #

**Comment by cydh** [comment]
idRO has this item

**Comment by Everade** [comment]
Which means?
I guess idRO isn't in english either, next to that, their website is extremly slow for me and on top of that looks extremly unprofessional.

And no idea if they are using the same effects, but from what i've seen, it's original release was on jRO.

**Comment by cydh** [comment]
I mean, it's better than "I can't read Japanese".
The bonuses are just missing
* Luk and Steel Crow level to increase 'auto' blitz beat
* Cendrawasih Card combo bonus
* Falconer Claw combo bonus

**Comment by Everade** [comment]
Blitz beat damage is currently being increased by **400% rather than 40%** if Steel Crow is learned (tested ingame)

**Missing:**
- Increase the chance of auto casting Blitz Beat depending on your current lvl of Blitz Beat
Additionaly LUK also increases it's chance

- If equipped with Galapago Card: Increase apple, banana and carrot juice healing amount by 1000%

- If equipped with Gryphon Card: Reduces after attack delay by 3%, ASPD+1, Physical ATK-5%
If additionaly used with a bow and it's refining level reached 10 ~ Adds ASPD+1

- If equipped with Condor Card
Reduces damage taken from all elemental attacks -10%

- If equipped with Cendrawasih Card
INT+1
Critical damage +5%
If additionaly equipped by archer class increases critical damage additionaly by +15%

- If equipped with Falconer Claw
Reduces damage of Blitz Beat by -200%

**Comment by zackdreaver** [comment]
I'm indonesian, and I'm not going to recommend idro as base for itemdb.
no offense, but idRO sucks, both in game mechanic and translation.

**Comment by cydh** [comment]
yea yea guys, u're so cute, do it yourself. :D

**Comment by Everade** [comment]
@cydh What was that for?
Indonesian isn't any better because i can't read it either.
So why should i base something on idRO if rA is based on kRO?

I've done the freaking translation already.
Directly from latest kRO description.

_There's no need for idRO, as i've never asked for a translation_

I'm trying to help here and do my part for the community.
It's not a lot, but more than the majority ever did.

**Comment by Everade** [comment]
bump

**Comment by Everade** [comment]
needs official info????

**I've already written down all required information.
It's directly translated from the latest official kRO description which is also included right above.**

**Comment by Darkelfen** [comment]
I guess there are some problems regarding how it is implemented; for example, is there a way to increase Blitz Beat proc from item script? Is it "increased" by autocasting the skill? Is it directly increased? If you don't have blitz beat, does it proc anyway?

I guess that's part of the "needs official" info.

Also [falconer's claw](http://www.divine-pride.net/database/item/28321) is missing.

**Comment by Everade** [comment]
`5967,Flying Galapago,Flying Galapago,4,0,,500,,,,0,0xFFFFFFFF,63,2,1,1,110,1,1358,{ bonus bAgi,1; if(readparam(bLuk)>120){bonus3 bAutoSpell,HT_BLITZBEAT,getskilllv(129),getskilllv(129)*10 + 120 /2;}else{bonus3 bAutoSpell,HT_BLITZBEAT,getskilllv(129),getskilllv(129)*10 + readparam(bLuk) /2;} if(getskilllv(128)>=1){bonus2 bSkillAtk,"HT_BLITZBEAT",getskilllv("HT_STEELCROW")*4;} if(checkequipedcard(4152)){bonus2 bAddItemHealRate,531,1000; bonus2 bAddItemHealRate,532,1000; bonus2 bAddItemHealRate,534,1000;} if(checkequipedcard(4163)){bonus bAspdRate,3; bonus bAspd,1; bonus2 bAddClass,Class_All,-5; if((getiteminfo(getequipid(EQI_HAND_R),11)==W_BOW) && (getequiprefinerycnt(EQI_HAND_R)>=10)){ bonus bAspd,1;}} if(checkequipedcard(4015)){bonus2 bSubEle,Ele_All,10;} if(checkequipedcard(4517)){bonus bInt,1; bonus bCritAtkRate,5; if(BaseClass==Job_Archer){bonus bCritAtkRate,15;}} if(isequipped(28321)){bonus2 bSkillAtk,"HT_BLITZBEAT",-200;}},{},{} 
`

**Comment by Everade** [comment]
Thanks for the fixes @aleos89 

But could you check on these 3 things again?

**1.**
I think the item_combo.txt does not support cards?!
My solution with checkequipedcard(4517) worked just fine.

At least the
`4152:5967,{ bonus2 bAddItemGroupHealRate,IG_Juice,1000; }`
does not seem to work at all.

Haven't tested the other effects but i guess those also don't work if the issue is related to cards in item_combo.

**2.**
This one is also still too strong and should only be active if Steel Crow is learned:
`	bonus2 bSkillAtk,"HT_BLITZBEAT",getskilllv("HT_STEELCROW") * 40;`
Should be:
```
	if(getskilllv(128)>=1){
		bonus2 bSkillAtk,"HT_BLITZBEAT",getskilllv("HT_STEELCROW")*4;
	}
```
**3.**
Item should be refinable, according to the description there's nothing that says you can't.
