### ISSUE TITLE
Latest Revision: AB_Renovatio not listed in skill_copyable_db.txt

### ISSUE THREAD

**Issue by Rayvis** [rathena/rathena#1432]
Your txt file that lists all the skills copyable by Shadow Chaser does not include AB_RENOVATIO although iRO wiki states that it can be copied by Shadow Chasers via Reproduce (when wearing Evil Druid Card). Since you state that IRO wiki is your source for copyable skills at the top of your text file I figured it somehow got removed from the list by accident (I used to be able to copy Renovatio on older revisions).

**Comment by Everade** [comment]
http://irowiki.org/wiki/Reproduce/List_of_reproducible_skills

However irowiki page update was back in august 2014.
Would be great if someone could test this on kRO.

I wasn't able to find any statement in the rathena changelogs that it has been removed.
Yet it's gone.

**Comment by Everade** [comment]
Source: http://irowiki.org/wiki/Reproduce/List_of_reproducible_skills
This page was last modified on **1 December 2016, at 14:33.**

**Missing in our list:**
**Renovatio** ~ Arch Bishop


**Not listed on irowiki but we have them active:**
GC_DARKCROW,2      // Dark Claw

WL_TETRAVORTEX,2    // Tetra Vortex
WL_SUMMONFB,2       // Summon Fire Ball
WL_SUMMONBL,2       // Summon Lightning Ball
WL_SUMMONWB,2       // Summon Water Ball
WL_SUMMONSTONE,2    // Summon Stone

NC_MAGMA_ERUPTION,2 // Magma Eruption

LG_EXEEDBREAK,2  // Exceed Break
LG_MOONSLASHER,2 // Moon Slasher

SR_SKYNETBLOW,2     // Sky Net Blow

GN_ILLUSIONDOPING,2  // Illusion Doping

**Comment by secretdataz** [comment]
iROWiki isn't the source we generally consider valid.

**Comment by Everade** [comment]
@secretdataz I'm well aware about that, but there have been a lot of updates during the past year where you considered irowiki to be good enough.

I don't have a kRO test account to test things myself.
So i use what's available at my disposal.

And the fact that the page has just been recently been updated isn't that bad.

**Comment by Playtester** [comment]
Tested and confirmed: Can be copied if Stalker wears Undead armor.

**Comment by Atemo** [comment]
Can Renovatio be auto-cast?

**Comment by Playtester** [comment]
How to test?

**Comment by secretdataz** [comment]
@Playtester Use SC_SHADOWSPELL (Auto Shadow Spell) and see if it's on the list.

**Comment by Akkarinage** [comment]
@Everade When citing a resource as being "recently updated", you should probably check to see what was changed: http://irowiki.org/w/index.php?title=Reproduce%2FList_of_reproducible_skills&diff=49457&oldid=43667

**Comment by Playtester** [comment]
@Atemo @secretdataz 
If I use Shadow Spell (while having Renovatio copied), it gives the error "There exists no usable imitation skill".

**Comment by Everade** [comment]
@Akkarinage No time for such a little details  ;)

**Comment by secretdataz** [comment]
Fixed in 16d8abb.

**Comment by Jeybla** [comment]
`AB_RENOVATIO` is fixed now. But what about the other stuff discussed here? Shouldn't we create another issue summarizing this discussion?
