### ISSUE TITLE
Increase Cash Shop Type.

### ISSUE THREAD

**Issue by ElsaEve** [rathena/rathena#1436]
Currently we have 7 type of Cash Shop. 
// Type:
//    0: New
//    1: Hot
//    2: Limited
//    3: Rental
//    4: Gear
//    5: Buff
//    6: Heal
//    7: Other

With the newer client there is another type of cash shop and its called 'Special'.

// 8: Special

Thanks!

**Comment by Everade** [comment]
https://github.com/rathena/rathena/issues/1229
