### ISSUE TITLE
OnSellItem Event Bug

### ISSUE THREAD

**Issue by Yuchinin** [rathena/rathena#1439]
The OnSellItem event not store the details of non equipment, it will always return 0 on variable other than @sold_nameid and @sold_quantity.

That mean if I sell an item which is not equipment  (potion, card, etc) on selling windows,
	@sold_refine     - refine count
	@sold_attribute  - if the item is broken (1) or not (0)
	@sold_identify   - if the item is identified (1) or not (0)
	@sold_card1      - card slot 1
	@sold_card2      - card slot 2
	@sold_card3      - card slot 3
	@sold_card4      - card slot 4
this 7 temporary variable will always be 0

revision: latest

**Comment by secretdataz** [comment]
It's intended behavior.
```
		if( itemdb_isequip(sd->status.inventory[idx].nameid) )
		{// process equipment based information into the arrays
			script_setarray_pc(sd, "@sold_refine", i, (void*)(intptr_t)sd->status.inventory[idx].refine, &key_refine);
			script_setarray_pc(sd, "@sold_attribute", i, (void*)(intptr_t)sd->status.inventory[idx].attribute, &key_attribute);
			script_setarray_pc(sd, "@sold_identify", i, (void*)(intptr_t)sd->status.inventory[idx].identify, &key_identify);

			for( j = 0; j < MAX_SLOTS; j++ )
			{// store each of the cards from the equipment in the array
				snprintf(card_slot, sizeof(card_slot), "@sold_card%d", j + 1);
				script_setarray_pc(sd, card_slot, i, (void*)(intptr_t)sd->status.inventory[idx].card[j], &key_card[j]);
			}
		}
```

**Comment by Yuchinin** [comment]
Since if someone use the selling windows as a item registration method, the countitem2() will always not work on non equipment since the identify field will never get setted and always be 0. Don't you think that it should atleast set the identify value?

**Comment by Yuchinin** [comment]
I know that normally non equipment will not have details item info but I think that it really should atleast return the identify value of it. Or maybe just set the identify value to 1 if its not equipment.
If this is really intend to not get fix then atleast it should be properly comment in the document to avoid mislead.
