### ISSUE TITLE
getitembound not binding

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#1440]
getitembound  512, 1, Bound_Account;

Does not make the item account bound on the latest rA revision.
This is kind of a big issue as it mainly leads to bug abuse.

Also if used by `@item` 512 1 Bound_Account
It does not create an account bound item.

**Comment by anacondaqq** [comment]
For GM? Or for normal players too?  Please check. Is it create normal items?

**Comment by Everade** [comment]
Ah ok, my mistake.
Thanks for pointing out ^^
