### ISSUE TITLE
ECL_PEONYMAMY

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#1441]
Hello good afternoon, the effect of itemscript ECL_PEONYMAMY is not working as it should, since you can not use items while frozen, and also is not removing all the negative effects it should.

Ref: http://www.divine-pride.net/database/item/12813/peony-mommy

**Comment by secretdataz** [comment]
It is working as intended. Frozen player can't use any item.
ECL_PEONYMAMY removes Frozen, Freezing, Crystalization status as shown in this snippet from skill.c.
```
		case ECL_PEONYMAMY:
			status_change_end(bl, SC_FREEZE, INVALID_TIMER);
			status_change_end(bl, SC_FREEZING, INVALID_TIMER);
			status_change_end(bl, SC_CRYSTALIZE, INVALID_TIMER);
			break;
```
