### ISSUE TITLE
Skill Earth Shaker ignores Walls

### ISSUE THREAD

**Issue by Jeybla** [rathena/rathena#1447]
With the Sura skill Earth Shaker it's possible to hit targets behind walls. I don't think this is official behavior and it may opens various other problems.

**Comment by Playtester** [comment]
I can confirm this. It can not hit through walls on Aegis. Should use "foreachinshootrange" instead of "foreachinrange".

**Comment by Jeybla** [comment]
Thanks for the quick fix. I'll have a look for other skills like these.
They can be used to effectively farm with cards like Plasma Card on specific spots where many mobs are re-spawning quickly behind a wall. I know one spot by now. Maybe we should set mapflag "nomobloot" there?

**Comment by aleos89** [comment]
If the map doesn't have that mapflag set then we can add it, as long as that's how it is on kRO.

**Comment by Jeybla** [comment]
Sorry I can't tell anything about the official behavior :/

But i'd recommend to add this mapflag on job3_gen01 (Poison Spore).
And maybe on in_rogue which has nothing to do with this bug but can also be used to quickly spawn and kill many monsters.

But this is simply my suggestion from a "secure" kind of perspective.

**Comment by Jeybla** [comment]
Just tested some other damage skills with "map_foreachinarea".

Problematic Skills ignoring walls:
- Genetic: Spore Explosion
- Sura: Tiger Cannon
- Maestro: Reverberation
- Sorcerer: Elemental Spirit Skills (not tested)
- Homunculus S: Magma Flow/Holy Pole (not tested)
- Rebellion: Howling Mine, Hammer of God
- Rouge: Raid
- Royal Guard: Earth Drive, Shield Spell
- Guillotine Cross: Rolling Cutter, Phantom Menace
- Ranger: Keen Nose
- Homunculus Vanilmirth: Self Destruction
- Gunslinger: Ground Dift
- Shadow Chaser: Feint Bomb

And there seems to be even more Skills ignoring walls like Desperado (Gunslinger) which seems to use "map_foreachincell" instead of "map_foreachinarea" :/
Does anyone have an idea how to fix these skills?
I'll open a pull request this evening for the above skills.
