### ISSUE TITLE
Rebellion skill Binding trap does 1 damage when using  Flicker

### ISSUE THREAD

**Issue by shushusao** [rathena/rathena#1449]
I think the title pretty much explains it. I'm using rAthena latest version. 

Steps to reproduce: Use binding trap, someone else steps on it, use Flicker and it does 1 HP damage. Also it slows down the caster (but i don't know if this is the correct behavior or not) and it seems like you can't cast on the same cell of someone else or yourself.

**Comment by cydh** [comment]
Misplaced since ce090ce916e567444f223894d47ecd3a39dd77ef

**Comment by feltenc** [comment]
I can confirm, but it was fixed on the new PR of rebellion. Thanks @cydh

**Comment by Akkarinage** [comment]
@feltenc do you mean #1692 ?
