### ISSUE TITLE
Skill **  Frigg's Song (Skill ID# 5007) ***

### ISSUE THREAD

**Issue by SakrayRO** [rathena/rathena#145]
when i use...is write 60 sec,but 16 sec the skill is finish..
isit that is bug or ???

**Comment by reigneil** [comment]
info about the skill
http://irowiki.org/wiki/Frigg%27s_Song
Duration: 	60 Seconds <-indeed 60secs
the problem here is in status.c
tick_time must be 1000 not 10000
