### ISSUE TITLE
NPC_EARTHQUAKE

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#1450]
The NPC_EARTHQUAKE skill is with very low damage, following image:

Img: http://imgur.com/a/tdHNs

Mode: Renewal
Latest version available on github.
Client: 2015-11-04

**Comment by Vomaito** [comment]
According on http://irowiki.org/wiki/NPC_EARTHQUAKE
Earthquake is magic but is ATK based(?) can you check using str?

**Comment by secretdataz** [comment]
EQ at level 10 has 1800% ATK ratio.
With ATK as low as yours 1.9k damage seems like it is working as intended.
Please re-open the issue if you still believe that we have wrong damage calculation.

**Comment by reigneil** [comment]
Earthquake skill is self targeted physical attack then splash magically to the surrounding .
info taken: https://forums.warpportal.com/index.php?/topic/159488-help-me-about-weapon-card/page-2
