### ISSUE TITLE
Mora Quest Crash Client.

### ISSUE THREAD

**Issue by Vomaito** [rathena/rathena#1451]
Hi Using latest rAthena on 2015-11-04a, and Mora Quest (On quest Window) Crash client, I came here because I Think is a Package problem since I use ragnarok grf full updated and I change client (2015-10-29aRagexe before but got char deletion problem).

I can see other quest on Quest Window but Mora crash, other useful information I Use RO-Translation-Proyect data.

Thanks.

**Comment by aleos89** [comment]
This sounds like a local client/GRF problem. Please use the [Client Support](https://rathena.org/board/forum/19-client-side-support/) section in the rAthena forum to get help on your issue.
