### ISSUE TITLE
unknown item ID 2428

### ISSUE THREAD

**Issue by technoken** [rathena/rathena#1455]
Hash: bec9845
Mode: Pre-renewal

`[Error]: itemdb_read_combos: line 69 of "db/pre-re/item_combo_db.txt" contains unknown item ID 2428`

**Comment by cydh** [comment]
Last changed, 9d730f3ba93a74a41e4b6b4fb8e98e64470b2877
Freyja Boots is still commented in db/pre-re/item_db.txt
````
//2428,Freyja_Boots,Freyja Boots,4,0,,300,,10,,0,0xFFFFFFFE,7,2,64,,0,0,0,{ bonus2 bSubRace,RC_DemiHuman,5; bonus2 bSubRace,RC_Player,5; },{},{}
````
