### ISSUE TITLE
Monocell

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#1456]
Hello!
The skill Monocell! promoted by skill hocus pocus is not having the desired effect.
I tested over and over again.

Mode: renewal.
Latest version.
Client: 2015-11-04

**Comment by Lemongrass3110** [comment]
What is the desired effect?
Latest is not a valid git hash.

**Comment by admkakaroto** [comment]
Well ... the ability should do some things, such as capture some monsters, or transmute monsters, something that is not happening, you cast ocus pocus, when it appears the indication of the skill with several questions '?????' you use a monster and she performs 'Monocell', but never does anything.

**Comment by aleos89** [comment]
Monocell just changes the class of the target to a Poring.

**Comment by admkakaroto** [comment]
I know, if you want I make a short video with the skill tests.

**Comment by aleos89** [comment]
I just tested this using ccd5584 and was able to perform Monocell just fine.

The monster was immediately turned into a Poring and walking around.
