### ISSUE TITLE
18575 Wunderkammer Missing Effect

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#1457]
Wunderkammer is still missing its main effects such as
	"Melee physical attacks has a chance to trigger a random skill.",

The other part is talking about specific equipment which triggers a hidden fire power as long as it's not refined.

Official latest Description:
18575#
驚異の部屋と
名づけられた箱。
その中には謎と神秘が
つめこまれている。
―――――――――――――
Mdef + 10
―――――――――――――
物理攻撃時、
一定確率で様々なスキルが
オートスペルで発動
―――――――――――――
精錬不可
―――――――――――――
特定の装備と
組み合わせる事により
隠された力が発動する
―――――――――――――
系列 : ^777777兜^000000
防御 : ^77777710^000000
位置 : ^777777上中下段^000000
重量 : ^77777750^000000
要求レベル : ^77777720^000000
装備 : ^777777全ての職業^000000
#

**Comment by Jeybla** [comment]
http://db.irowiki.org/db/item-info/18575/
 >    When performing a close-range physical attack, has a change to cast certain skills at a low chance:
>         [Sonic Acceleration] Lv 1 at a 2% rate.
>         [Smite] Lv 1 at a 1% rate.
>         [Pneuma] Lv 1 at a 1% rate.
>         [Summon Spirit Sphere] Lv 5 at a 0.5% rate.
>         [Kyrie Eleison] Lv 1 at a 0.5% rate.
>         [Fury] Lv 3 at a 0.5% rate.
>         [Meteor Assault] Lv 1 at a 0.5% rate.
>         [Grand Cross] Lv 1 at a 0.5% rate.
>         [Quagmire] Lv 1 at a 0.3% rate.
>         [Improve Concentration] Lv 5 at a 0.1% rate.
> 
> Special Notes:
> 
>     Obtained via temporary cash shop sale events.

So the itemscript would look like:


```
18575,Wunderkammer,Wunderkammer,4,20,,500,,10,,1,0xFFFFFFFF,63,2,769,,20,0,743,{ bonus bMdef,10; bonus3 bAutoSpell,"AS_SONICACCEL",1,20; bonus3 bAutoSpell,"CR_SHIELDCHARGE",1,10; bonus3 bAutoSpell,"AL_PNEUMA",1,10; bonus3 bAutoSpell,"MO_CALLSPIRITS",5,5; bonus3 bAutoSpell,"PR_KYRIE",1,5; bonus3 bAutoSpell,"MO_EXPLOSIONSPIRITS",3,5; bonus3 bAutoSpell,"ASC_METEORASSAULT",1,5; bonus3 bAutoSpell,"CR_GRANDCROSS",1,5; bonus3 bAutoSpell,"WZ_QUAGMIRE",1,3; bonus3 bAutoSpell,"AC_CONCENTRATION",5,1; },{},{}
```
