### ISSUE TITLE
18597 Mercury Riser Refineable

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#1458]
At no point, the official description is talking about that it can't be refined.
In rAthena, it cannot be refined.
Could be possible that it's just missing in the description, i don't have a kRO test account.

**Official latest description:**
수성을 관장하는 신 머큐리의 화려한 투구.
CRI + 3, 공격속도 증가 (공격 후 딜레이 3% 감소)
7제련 시, CRI + 2, 공격속도 증가(공격 후 딜레이 2% 감소)추가.
9제련 시, CRI + 2, 공격속도 증가(공격 후 딜레이 2% 감소)추가.
계열 : ^777777투구^000000 방어 : ^77777710^000000
위치 : ^777777상단 ^000000 무게 : ^77777740^000000
요구 레벨 : ^77777770^000000
장착 : ^777777전직업^000000

**Comment by Lemongrass3110** [comment]
You are totally right. It does not even make sense to have an refine depending effect and make the item not refinable.
