### ISSUE TITLE
Manhole

### ISSUE THREAD

**Issue by Jeybla** [rathena/rathena#1459]
http://irowiki.org/wiki/Manhole:
```
A manhole cannot be cast directly under a target, but can be placed beside one, effectively trapping them instantly. Doing so will also shift the player 1 cell towards the center of the manhole. Manholes can no longer be placed adjacent current manholes, which prevents the "infinite trapping" that used to take place.
```
Both is possible in rathena. Even infinite trapping (example: https://www.youtube.com/watch?v=SLAV3Uu7c54)

```
Manholes cannot be placed in tows.
```

https://forums.warpportal.com/index.php?/topic/47580-manhole/:
```
manhole is now the strongest move in the game cause there is NO way to counter it, unless you have a gtb that is
```

So we should change the current behavior to the following:

- [ ] Manhole cannot be casted underneath enemies
- [ ] Manholes cannot be casted near other manholes (prevent infinite trapping)
- [ ] Manhole cannot be placed in towns
- [ ] GTB blocks Manhole

**Comment by Barigas** [comment]
Manhole on officials has 2 durations - of manhole as trap itself, and the manhole status. So, if you put manhole at second 0, then target is caught in it on, lets say, the last second, then the target will still be trapped for the whole manhole status duration, though manhole itself will disappear. In this case you can cast another manhole near target.

**Comment by Jeybla** [comment]
So placing manhole near another manhole is possible after the first duration expired? 
Maybe this should be tested in detail on an aegis server :/

**Comment by Barigas** [comment]
The situation that I have discribed can only happen if a manhole was on the ground for a long time. I'd say manhole status has a bit shorter duration than Manhole itself, though, when status duration ends, manhole ends also. But if manhole ends, the status still remains. So, basically it is just like trap behaviour.
1)It is never possible to place Manhole on the same cell where there is a target.
2)It is possible to place in the cell next to the target. So you instantly manhole the target.
3)Manhole is 3x3 cells size. When target a target is caught, it is moved to the center of this 3x3. You can not place another Manhole in this 3x3 cells.
Though, on officials you can just spam Manhole(very fast cast time, 0 cooldown on skillfail) skill in the cell next to the player while he is manholed. So you manage to manhole him right after the first one(if he does not spam Backsliding or smth like that).

**Comment by benching** [comment]
(Please confirm this)
be aware that using the cleaner skill might remove the manhole ground skill,
while leaving the player with manhole(status),
it is possible that it can bypass the manhole ground skill limit.

**Comment by aleos89** [comment]
Confirmed on Aegis:
- Manhole **can not** be casted underneath enemies.
- Manholes **can** be casted near other manholes.
- Manhole **can not** be placed in towns.
- GTB **does not** block Manhole.

This is how it's working on rAthena already.
