### ISSUE TITLE
mob_item_ratio.txt in import folder (still) not working

### ISSUE THREAD

**Issue by nerfwood** [rathena/rathena#146]
6 months ago: https://github.com/rathena/rathena/commit/6c5d4a730f82afa9367ec0b29d8509ec95e420c5

mob_item_ratio.txt in the main db folder works, but not the one in the import folder.

**Comment by cydh** [comment]
this is also related with the conversation from [this point](https://rathena.org/board/tracker/issue-8880-dbimport-files/?gopid=26503#entry26503) forward
