### ISSUE TITLE
Map Crash caused by SC_CLOUD_KILL

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#1462]
rAthena revision **19518** (yes i use SVN, so i never have this total random githash)

**Call Stack**
>	map-server.exe!status_change_timer(int tid=6226, unsigned int tick=46625156, int id=110224391, int data=639)  Line 12675 + 0x37 bytes	C

**status.c** crash at line
			sc_timer_next(500 + tick, status_change_timer, bl->id, data);

```
	case SC_CLOUD_KILL: {
			struct block_list *src = map_id2bl(sce->val2), *unit_bl = map_id2bl(sce->val3);

			if (src && unit_bl)
				skill_attack(skill_get_type(status_sc2skill(type)), src, unit_bl, bl, SO_CLOUD_KILL, sce->val1, tick, 0);
			sc_timer_next(500 + tick, status_change_timer, bl->id, data);
		}
		break;
```

**Comment by aleos89** [comment]
Can you explain the case in which the crash is caused?

**Comment by Everade** [comment]
No i'm sorry but i can't.

I've had 2 crashes in total before i blocked the skill.
It was during a big team boss event, so there was a lot of chaos with a lot of players going on.
