### ISSUE TITLE
Map Crash caused by Party HP

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#1466]
rAthena revision **19518** (yes i use SVN, so i never have this total random githash)

**Call Stack:**
>	map-server.exe!clif_party_hp(map_session_data * sd=0x18faa528)  Line 7906 + 0xd bytes	C

**clif.c** crashes at this part:
`	if( map[sd->bl.m].flag.fvf ) return;`

few lines before #if PACKETVER < 20100126

**Comment by aleos89** [comment]
What is mapflag fvf? That doesn't exist on rAthena.

**Comment by Everade** [comment]
Didn't notice that...
Faction vs Faction included in the rAMod from zephyrus.
However i don't even use it.

I guess it's up to me then.
