### ISSUE TITLE
athena-start not working properly

### ISSUE THREAD

**Issue by Daegaladh** [rathena/rathena#1467]
When running  athena-start start on ubuntu server 16.04 works really weird, says it's reading the conf files but act as if all the configurations where by default (for example s1/p1).

However, it works fine if I directly run the server binaries...

(I'm using the lastest rathena)

**Comment by secretdataz** [comment]
I can't reproduce this issue on my Ubuntu 14.04 server and Bash on my Windows 10 PC (which also use Ubuntu 14.04 as base).

**Comment by aleos89** [comment]
I tested with Ubuntu 16.04.1 and was unable to reproduce this as well.
