### ISSUE TITLE
eA Job Mask broken aka EAJ_MASK

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#1468]
`if (eaclass()&EAJ_THIRDMASK==EAJ_RUNE_KNIGHT){ mes"This will never trigger";}`

**All eaclass checks do not trigger anymore since the latest updates.**

**Comment by Lemongrass3110** [comment]
This is no recent change and is due to operator precendence.
http://www.tutorialspoint.com/cprogramming/c_operators_precedence.htm
Unary operators are processed before equality operators.
Add some parenthesis to your script and everything will work out like intended:

```
if( (eaclass()&EAJ_THIRDMASK) == EAJ_RUNE_KNIGHT ){
	mes "This will never trigger";
}
```

**Comment by Everade** [comment]
Thank you very much

**Comment by Jeybla** [comment]
Good thing.

But could you please link the commit where the operator precedence has been changed?

I think some Scripts are bugged now like:
```
re/other/adven_boards.txt:  if (MISC_QUEST & 8192 == 0) {
re/other/adven_boards.txt:      if (MISC_QUEST & 8 == 0) {
custom/breeder.txt: } else if ((eaclass()&EAJ_THIRDMASK==EAJ_RANGER) && !countitem(6124)) {
custom/breeder.txt: } else if ((eaclass()&EAJ_THIRDMASK==EAJ_MECHANIC) && !checkcart() && getskilllv("MC_PUSHCART")) {
custom/breeder.txt:     if (eaclass()&EAJ_THIRDMASK==EAJ_RUNE_KNIGHT) setdragon;
other/Global_Functions.txt:     if(ADV_QSK|pow(2,.@i) == ADV_QSK) skill 144+.@i,1,0;
other/Global_Functions.txt:     if(ADV_QSK2|pow(2,.@i) == ADV_QSK2) skill 1001+.@i,1,0;
```

**Comment by Everade** [comment]
Yea i hope it didn't break to much.
Also when it comes to custom scripts.

**Comment by Jeybla** [comment]
@Everade:
I searched via grep. You should check your scripts too :)
 grep -Er "[^&]&[^&]" and  grep -Er "[^\|]\|[^\|]"

Or specific for == / !=:
 grep -Er "[^&]&[^&]" | grep "==" and  grep -Er "[^&]&[^&]" | grep "!="
 grep -Er "[^\|]\|[^\|]" | grep "==" and  grep -Er "[^\|]\|[^\|]" | grep "!="

**Comment by Lemongrass3110** [comment]
It could have been that one:
https://github.com/rathena/rathena/commit/fd48238
I did not have time to try it yet though. Would be nice if someone could confirm this, so we could write a newsletter about it @aleos89?
