### ISSUE TITLE
Script Command progressbar on targets

### ISSUE THREAD

**Issue by aleos89** [rathena/rathena#1473]
As described by @Hope8888 in #1425:

> and NPC isn't supported yet
> 
> sample:
> 
> ```
> *progressbar "<color>",<seconds>{,"<NPC name>"};
> ```
> 
> or attached npc
> 
> ```
> *progressbar2 "<color>",<seconds>;
> ```
> 
> Information source: Instance - **Sarah and Fenrir** 
> 
> [iRO video](https://youtu.be/fvHrlSpE1RM?t=13) 0:15~
> ![w3kvbat](https://cloud.githubusercontent.com/assets/19237837/16899246/48fb4ea0-4c2f-11e6-8400-966356a0c5d9.png)
> 
> [twRO video](https://youtu.be/cjecXO7LL3I?t=25) 0:25~
> ![muyinmn](https://cloud.githubusercontent.com/assets/19237837/16899243/376eca90-4c2f-11e6-96f3-98f2e6d7f502.png)

**Comment by cydh** [comment]
is it using different packet?

**Comment by Lemongrass3110** [comment]
Judging from my tests I would say **yes**. But we do not have any replays or packet captures of it yet.

**Comment by Tokeiburu** [comment]
The packet in question is:
```
/// Displays cast-like progress bar on an NPC.
/// 09d1 <id>.L <color>.L <time>.L
void clif_progressbar2(struct npc_data * nd, unsigned long color, unsigned int second)
{
	unsigned char buf[14];

	WBUFW(buf,0) = 0x9d1;
	WBUFL(buf,2) = nd->bl.id;
	WBUFL(buf,6) = color;
	WBUFL(buf,10) = second;
	clif_send(buf, packet_len(0x9d1), &nd->bl, AREA);	// Length is 14
}
```

It only works for NPC from what I remember, I haven't played with it much though. I do not know the client date for this packet either.

**Comment by idamonli** [comment]
aegis：npcprogress_bar

**Comment by kukuasir1** [comment]
```

clif.c

void clif_progressbar2(struct block_list *bl, unsigned long color, unsigned int second)
{
	unsigned char buf[14];
	nullpo_retv(bl);

	WBUFW(buf,0) = 0x9d1;
	WBUFL(buf,2) = bl->id;
	WBUFL(buf,6) = color;
	WBUFL(buf,10) = second;
	//clif_send(buf,packet_len(0x9d1),bl,AREA);//Length is 14
	clif_send(buf, 14, bl, AREA);
}

//=====================================================

script.c

BUILDIN_DEF(progressbar2,"ssi"),

BUILDIN_FUNC(progressbar2)
{
	struct npc_data* nd = NULL;
	const char * color;
	unsigned int second;

	nd = npc_name2id(script_getstr(st, 2));
	color = script_getstr(st,3);
	second = script_getnum(st,4);

	if( !st->sleep.tick ) {
		// sleep for the target amount of time
		st->state = RERUNLINE;
		st->sleep.tick = second*1000;
		if (nd != NULL) {
			clif_progressbar2(&nd->bl,strtol(color, (char **)NULL, 0), second);
		}
	} else {
		// sleep time is over
		st->state = RUN;
		st->sleep.tick = 0;
		script_pushint(st, (map_id2sd(st->rid)!=NULL));
	}

	return SCRIPT_CMD_SUCCESS;
}
```

**Comment by Lemongrass3110** [comment]
The required packet should be available from 2013-08-21bRagexe onwards.
