### ISSUE TITLE
Arch bishop skill Clearance not working on monsters

### ISSUE THREAD

**Issue by shushusao** [rathena/rathena#1476]
http://irowiki.org/wiki/Clearance

It should work on monsters but if you try to cast on monsters the skill fails. It works normally on party members.

I'm using rathena's latest version.

**Comment by Playtester** [comment]
Against which monster did you test and which buff did you try to remove?

**Comment by shushusao** [comment]
I poisoned an Hode and tried to remove it.

also mode is renewal and client is 2015-11-04

**Comment by Playtester** [comment]
```		// Still can be casted to party member in normal map
		case RK_PHANTOMTHRUST:
		case AB_CLEARANCE:
			if (target->type != BL_MOB && !map_flag_vs(src->m) && battle_check_target(src,target,BCT_PARTY) <= 0)
				return USESKILL_FAIL_MAX;
			inf |= BCT_PARTY;
			break;```
This is the reason it doesn't work on monsters I think. If target type is monster then it checks if the monster has a party, but monsters never have a party, so...

**Comment by lucasoli** [comment]
Hey Playtester, what about changing this entry in **db/re/skill_db.txt**:

`2052,11,6,1,0,0x1,0,5,1,yes,0,0x00400,0,magic,0,0x10020,	AB_CLEARANCE,Clearance //CHECK Also shows this as a magic attack. Why?`

I have changed **inf** from 16 to 1 and **inf2** from 0 to 0x00400.

Can anybody test it for me?

**Comment by Playtester** [comment]
The check for party is hardcoded, it needs to be fixed in the code I think. @aleos89 already looked into it too, he just didn't post here.

**Comment by lucasoli** [comment]
Hmm, got it. I thought that maybe it was related to a missing flag or something. I'm gonna wait @aleos89 analysis. Thank you!

**Comment by Playtester** [comment]
If you want to test around you could try to change the code I quoted above to this:
`
        // Still can be casted to party member in normal map
        case RK_PHANTOMTHRUST:
        case AB_CLEARANCE:
            if (target->type != BL_MOB)
                inf |= BCT_PARTY;
            break;
`
