### ISSUE TITLE
Mechanic skill Lava Flow is working while riding Mado Gear

### ISSUE THREAD

**Issue by shushusao** [rathena/rathena#1478]
http://irowiki.org/wiki/Lava_flow

> Cannot be casted while riding Mado Gear. 

I'm using rAthena's latest version.

**Comment by lucasoli** [comment]
Pretty easy to fix.

You should replace this entry in your db/re/skill_cast_db.txt with the following code:

`5006,1,6,2,3,0x2,3,5,1,no,0,0,3,misc,0,0x04000, NC_MAGMA_ERUPTION,Magma Eruption`

**Comment by Rayvis** [comment]
Maybe this will help:

Lava Flow should be possible in Mado on kRO as is discussed and confirmed with kRO client screenshots here:

https://forums.warpportal.com/index.php?/topic/166514-chaos17560-update-bug-thread-archive-mode/

See the post by "AlmrOfAtlas"
