### ISSUE TITLE
Scholar skill Blinding Mist is not blinding players that go inside the mist

### ISSUE THREAD

**Issue by shushusao** [rathena/rathena#1479]
this is also not working :

> Ranged attacks and skills will have their damage reduced by 75% and their hit rate reduced by 50. 

I'm pretty sure this is not working either:

> Aggressive monsters affected by this skill will be unable to attack anyone unless they are adjacent to them.

source here : http://irowiki.org/wiki/Blinding_Mist

I'm using rAthena's latest version.

**Comment by shushusao** [comment]
I did a few more tests and the ranged attacks are fine and the monster part it seems to be working fine too.

but as seem here, sometimes you get blinded and sometimes you don't http://prnt.sc/c1cqfv

**Comment by aleos89** [comment]
```
	case PF_FOGWALL:
		if (src != bl && !tsc->data[SC_DELUGE])
			sc_start(src,bl,SC_BLIND,100,skill_lv,skill_get_time2(skill_id,skill_lv));
		break;
```
The success chance of Blind is 100%, but this does not mean it is truly 100%. Meaning, you can still avoid it if you have high INT/VIT/LUK.
