### ISSUE TITLE
Skill bug: King's Grace

### ISSUE THREAD

**Issue by raynra** [rathena/rathena#148]
http://forums.warpportal.com/index.php?/topic/109539-kro-update-job-60-skills-short-translations-with-source/

This source claims that the kRO version (and subsequently, the Sakray test server version) of the skill is supposed to behave in the following manner:

"Bestow royal blessings to the caster and allies around the caster to recover HP and protect against status effects and damage.
If used in a PVP or Siege area, only affects the caster and party members, and all targets under the skill's protection will be unable to take any actions for the skill's duration.
Removes the following statuses: Poison, Blind, Frozen, Stone Curse, Stun, Sleep, Bleeding, Curse, Chaos, Hallucination, Silence, Burning, Crystalize, Freezing, Deep Sleep, Fear, Mandragora Howling"

Tested on latest GIT  - the skill always prevent targets from casting in status.c regardless of map mode.

**Comment by aleos89** [comment]
@Inzanity99 
Sorry, my second line was reflected towards Aegis. I can't remember now if I fully tested it on Aegis or not since it's been a hectic month. @_@ I'll go back and test it again. :)

**Comment by reigneil** [comment]
watching this video give something a little info about it...
http://youtu.be/xFJeUxULtx4
credit: to the uploader
