### ISSUE TITLE
Bullet and Megazine Dealer

### ISSUE THREAD

**Issue by ElsaEve** [rathena/rathena#1482]
Hello rA Devs,

I found that Rebellion cannot use this shop. As the scripts only check if you are Gunslinger Class. I do not know if this official behavior or not. But if we think of the way of logic, it should have Rebellion check since Rebellion still need the bullet and megazine. 

https://github.com/rathena/rathena/blob/master/npc/merchants/ammo_boxes.txt
https://github.com/rathena/rathena/blob/master/npc/merchants/ammo_dealer.txt

**Comment by cydh** [comment]
> I do not know if this official behavior or not

Then for now, u can adjust it for yourself first unti we confirm on official

**Comment by ElsaEve** [comment]
Yeap already done that :)

**Comment by jgoog999** [comment]
@cydh, confirmed this on kRO. I'll create a pull for this.

**Comment by jgoog999** [comment]
This issue is now fixed. Thanks for reporting.
