### ISSUE TITLE
NoKnockBack preventing Knuckle Arrow

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#1483]
Related to https://github.com/rathena/rathena/issues/1227

The effect bonus bNoKnockback,0;
(Used by Brynhild 2383 for example)

**Which means if you wear Brynhild yourself:**
Prevents the the player to move to the enemy when using the skill Knuckle Arrow.
The skill is being recognized as a knockback, and that's the problem.

**Comment by vstumpf** [comment]
Well it seems like a pretty easy fix, 
`case SR_KNUCKLEARROW:
	// Ignore knockback damage bonus if in WOE (player cannot be knocked in WOE)
	// Boss & Immune Knockback stay in place and don't get bonus damage
	// Give knockback damage bonus only hits the wall. (bugreport:9096)
	if (skill_blown(dsrc, target, blewcount, dir_ka, 0x2|0x04|0x08|0x10|0x20) < blewcount)
		skill_addtimerskill(src, tick + 300 * ((flag&2) ? 1 : 2), target->id, 0, 0, skill_id, skill_lv, BF_WEAPON, flag|4);
	dir_ka = -1;
	break;`
in skill_attack_blow.
But I don't have a way to test this in Aegis.

**Comment by secretdataz** [comment]
Confirmed
Aegis: Sura with Brynhild "slides" in front after using Knuckle Arrow.
rA: Sura with Brynhild stands still after using Knuckle Arrow.
