### ISSUE TITLE
GX Poison Duration

### ISSUE THREAD

**Issue by RagnarokNova** [rathena/rathena#1486]
On Aegis, all GX poisons have a default duration of 5 minutes. (300 seconds)
This duration should be reduced by the target's (VIT + LUK) / 2
I.E. a target with 50 vit and 50 luck, would get a 250 second poison duration.

**Comment by Playtester** [comment]
Tested:
1+4 VIT, 1+1 LUK = 4 minutes 57 seconds
51+4 VIT, 1+1 LUK = 4 minutes 32 seconds
51+4 VIT, 51+1 LUK = 4 minutes 7 seconds
101+4 VIT, 51+1 LUK = 3 minutes 42 seconds
101+54 VIT, 51+51 LUK = 2 minutes 52 seconds

Confirmed.
