### ISSUE TITLE
Manage Skill Damage skill_damage_db.txt (mapflag "bug")

### ISSUE THREAD

**Issue by faicciruz** [rathena/rathena#1487]
Hello, guys...

I don't know if this is intended but I'm trying to make a certain skill have different damage on different mapflags.

Example:
// SkillName,Caster,**Map**,Damage against Players{,Damage against Mobs{,Damage against Bosses{,Damage against Other}}}
AS_SONICBLOW,1,**1024**,100,100,100            //+100%
AS_SONICBLOW,1,**2048**,50,50,50                // +50%

The problem is that only the second line is read, the first one is ignored. I need them both to be in effect at the same time (on different maps). Is this possible?

Thank you

**Comment by cydh** [comment]
It's intended if u put them on db. For specific maps, use the mapflag. (See
doc/mapflags.txt)
