### ISSUE TITLE
MAX_MAP_SKILL_MODIFIER adjustment limit

### ISSUE THREAD

**Issue by Grantea** [rathena/rathena#1489]
Hey, guys!

I need to overwrite the damage of some skills in my skill_damage_db and the only solution I found was using the mapflag skill_damage, but each map can only contain up to 5 adjustments.

Is there a problem if I change the adjustment limit from 5 to 100?

Thank you.

**Comment by secretdataz** [comment]
Our issue tracker is not a place to ask questions.
