### ISSUE TITLE
bonus Status Effect bug on Enchantment

### ISSUE THREAD

**Issue by psyzerkski** [rathena/rathena#1490]
"sc_start" is not working when applying the bonus to an item for Enchantment or on a Non-slot card area.

It's working fine if the effect is used on an item compounded on a "Slotted" Card area.

![bug1](https://cloud.githubusercontent.com/assets/12017317/17513576/a3dbe0d6-5de2-11e6-9e2c-9102093d853a.JPG)

**Comment by Lemongrass3110** [comment]
Tested on 2cbc9ac and was working without any problems:
![invalid](https://cloud.githubusercontent.com/assets/3517879/17645421/1b74a616-61a6-11e6-8c77-f962fb93a312.PNG)

**Comment by cydh** [comment]
@psyzerkski how many items equipped at that time?

**Comment by secretdataz** [comment]
No further input.
