### ISSUE TITLE
item_combo_db crash

### ISSUE THREAD

**Issue by julia40124009** [rathena/rathena#1493]
item_combo_db:
`20819:19162,{ bonus bAspdRat,1; }` // set wrong bonus 

cause code:
https://github.com/rathena/rathena/blob/master/src/map/pc.c#L3056

because "current_equip_item_index" variable values is -1

version : https://github.com/rathena/rathena/commit/8857ff6279923743284b68e8d79e94fe3f468396

**Comment by Playtester** [comment]
Isn't it because there's an "e" missing there?

**Comment by julia40124009** [comment]
on purpose set bonus error , result in server crash
