### ISSUE TITLE
[Feature request] Stat reduction potion script

### ISSUE THREAD

**Issue by zackdreaver** [rathena/rathena#1494]
In 2015,
kRO implemented some potions that allow reducing BASE STAT by 1 point and give STAT POINT according the stat calculation. (eg: You have 10 base str, then use 1 Reduction Potion, it will reduce your stat by 1, then give you back 2 stat points, now you have 9 str)
Some items that have this script: 22702 ~ 22707

**Comment by secretdataz** [comment]
@zackdreaver What if the user already has 1 base stat?

**Comment by zackdreaver** [comment]
@secretdataz 
it's self explained in item description:
Cannot be used when STR is 1.

**Comment by Lemongrass3110** [comment]
@zackdreaver 
Cannot be used like the item will not be consumed or cannot be used like the item will be removed without having any efffect?

**Comment by zackdreaver** [comment]
same mechanism like neuralizer.
But the requirement is different, instead not equipping cart,mount,etc.
It's requires you to at least have 2 or higher the required stat that need to be reduced.

**Comment by Lemongrass3110** [comment]
Hey zack,

@secretdataz implemented the required command in pull request #1509. Would be nice if you could test if it is working as intended, then we could merge it into master for further usage.

**Comment by secretdataz** [comment]
Implemented in 51ef911.
