### ISSUE TITLE
Manhole & Bloodlust without PvP

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#1496]
I'm really not sure if this is official, so if someone could check that... would be appreciated.
The thing is that Manhole & Bloodlust can be used on players **without the need of PvP mode on**.

So players can abuse it to trap other MVP hunters or keep them away **from even entering** the WoE Castles. Even though these maps have no PvP nor GvG activated?!

Is this really normal?

**Comment by zackdreaver** [comment]
yes, iirc in 2011 when played idRO and iRO and if kRo haven't fix it, then the current effect is right.

**Comment by Everade** [comment]
I mean sure, you can restrict it using mapflags on specific maps.
But the fact that you can use them without the PvP flag is kinda weird.

**Comment by aleos89** [comment]
Here are the tests I made while on Aegis:
SC_MANHOLE - Only in PvP
SC_DIMENSIONDOOR - Worked in town but didn't work in field or PvP
SC_CHAOSPANIC - Worked in town, field, and PvP
SC_BLOODYLUST - Worked in town and PvP but didn't work in field

**Comment by Jeybla** [comment]
Thanks for the report @Everade . Thanks for the tests @aleos89 !

I added a commit which fixes the behavior of:
```
SC_MANHOLE - Only in PvP
SC_DIMENSIONDOOR - Worked in town and field but didn't work in PvP
SC_CHAOSPANIC - Worked in town, field, and PvP
```

We currently don't have a flag for field restrictions in the `skill_nocast_db`. And SC_BLOODYLUST may be disabled on every PvE map. So I'd prefer to push it, or also test SC_BLOODYLUST in dungeons.
