### ISSUE TITLE
Random Option System expansion

### ISSUE THREAD

**Issue by secretdataz** [rathena/rathena#1498]
- [x] Creating items with random options
- [x] Random option drops definition
- [ ] TBA

**Comment by cydh** [comment]
In here: f296409ada211a0aa89863db4d9603054845cf65
I think, you forgot to update doc/script_commands.txt for `getrandomoptinfo`

**Comment by secretdataz** [comment]
@cydh Thanks. It's done and will be pushed with the new commands.

**Comment by iubantot** [comment]
will you be implementing an option/script command like 'makeitem' for randomopt?

**Comment by cydh** [comment]
@iubantot `makeitem`? did u mean create-item command-like to add option directly?

**Comment by iubantot** [comment]
for instance i want to make the script that will drop an item w/ random options.. like the treasure chest in faceworm instance.  to not require the player to hold the item to be able to put random option on the item, like making the item with random option already.(sorry for the weird explanation)

for example  : makeitemrandomopt //gives player item with random option.

**Comment by cydh** [comment]
let's say add optional params for `getitem2`, `makeitem2`.
`....{<opt1_id>,<opt1_value>,<opt1_param>,...,<opt5_id>,<opt5_value>,<opt5_param>}`

**Comment by Darkelfen** [comment]
There is no way to clear a set random option; zeroing everything just doesn't work, an script let's say `clearrandomoption EQI_,index` is needed.

Also, `getinventorylist`should be expanded to retrieve the random option data of items:
```
@inventorylist_randopt1[]
@inventorylist_randopt1_value[]

@inventorylist_randopt2[]
@inventorylist_randopt2_value[]
...
```
Also, what is ROA_PARAM or what is it used for? I've tested changing the param and index values and only changing the index produced noticeable changes on the item.

**Comment by Lemongrass3110** [comment]
Additional features were added in:
e59cdff (monster databases)
a15661e (script commands)
