### ISSUE TITLE
about item_db new items

### ISSUE THREAD

**Issue by LiMoon** [rathena/rathena#1501]
I can add new items in GRAVITY Taiwan and pull requests?

them AegisName and Name, I dont know how to translate Chinese to English.
If use the translation tool is not possible?

headgear name can refer to accname and accessoryId.

**Comment by cydh** [comment]
can, but the issue is the item names must be translated to English. For previous case, when Ziu gave info for new items from kRO, he translated it to English.

**Comment by aleos89** [comment]
This isn't really an issue but more of a forum question.

If the item is on kRO and differs from tRO then the PR wouldn't be approved. We have implemented specific server items though in the past that doesn't exist on kRO.

**Comment by LiMoon** [comment]
@cydh ok, ty.
@aleos89 if twRO item from jRO, pull requests is ok?
twRO most new cash items come from jRO.

**Comment by aleos89** [comment]
Yeah, that's fine.
