### ISSUE TITLE
Status ATK problem. Damage of melee attack without a weapon is getting reduced by Raydric Card

### ISSUE THREAD

**Issue by shushusao** [rathena/rathena#1502]
Mode: Renewal
Client : 2015-11-04

http://irowiki.org/wiki/ATK

> Ignores element resistance effects such as _Raydric Card_ or Asprika. 

So i did a few tests, and if the attacker has nothing equipped and the defender has a raydric card, the melee attack does less damage. Is this the correct behaviour?

This topic has a few screenshots to explain a little better https://rathena.org/board/topic/106830-about-melee-attack/

**Comment by Jeybla** [comment]
Simply from a logical view:
Why shouldn't normal neutral attacks without weapons be reduces by neutral reduce?

To your board topic:
You complete took of your garment. Maybe the damage is reduced just by its defence. (I don't think so)

If you're able to test this on an official server, we'd very appreciate more screens. The description of irowiki sounds weird to me :)

**Comment by Playtester** [comment]
It's actually true that in renewal various resistances don't really work anymore or only work against certain parts of the ATK calculation. I don't think iROwiki is fully correct and I saw Herc already tried to implement it too, but it was also not fully correct (they have wrong rounding and stuff). rA isn't correct either though.

It's a larger project to rework. First need to test each bonus against all types of attack and calculate which ATK types are affected. Then need to recode the functions in rAthena to simulate this while making sure it still works for pre-renewal.

**Comment by shushusao** [comment]
Hey guys, thanks for answering! So it's not correct then? I wasn't really sure, it's just that the players on my server were complaining about the damage of builds for jobs that use physical attacks like Guillotine Cross. I thought that unequipped attacks were neutral and should be reduced by neutral reduce, like Jeybla said.

**Comment by Playtester** [comment]
It is semi-correct, but there is more to it that needs to be checked.
