### ISSUE TITLE
Nurse in Port Malaya / Bangungot Hospital bug

### ISSUE THREAD

**Issue by Indigo000** [rathena/rathena#1504]
Hi there,

I've been going through the scripts of Port Malaya before implementing them on our server. I've been running into something that I can't quite figure out and seems to be a bug. Let me elaborate.

Upon doing the Nurse in Port Malaya quest, at the end you are told to kill Bangungot. Variables set:
- malaya_bang to 42
- questlog set to 11309 (hunting mission for MobID 2327)

Upon talking to the instance entry NPC, it checks if quests 9223 and 9222 are -not- set. These quests are, I assume, for the repeating part of the instance. As only questID 11309 is set and those two are not, it continues in the quest. It then checks for 11309,HUNTING. If you did not kill the mob, it will continue to let you go into the instance. QuestID 9224 is set (time limit of 1 hour) and you are warped inside.

Now, in order to finish the Nurse in Port Malaya Quest, you have to kill Bangungot. So MobID 2327 is killed and 11309 is set to 2 when checked on HUNTING. If you were to talk to the Instance entrance NPC again, it would tell you:
`mes "[Nurse Maenne]";
                mes "You got rid of Bangungot!"; //?
                mes "The nurse might be waiting for you";
                mes "in front of the hospital!";
                close;`

Because (checkquest(11309,HUNTING) < 2) is false. So you go back to the quest NPC. It sees that 11309 is set to 2, then does a completequest on that and sets malaya_bang to 41.

Now the problem. 11309 is set to 2 and the questlogs for the repeatable entrance to the instance, 9222 and 9223 are -not- set anywhere. How do you start doing the instance now? It will keep giving the above message that you got rid of Bangungot and you have to talk to the nurse in front of the hospital. You can never do the repeatable part of the instance this way.

There is a bit of code that does set these, but that only triggers if you did -not- kill Bangungot and the time limit of 9224 ran out. That hardly seems to be intentional though.

I hope this makes a bit of sense. I've been staring at the code and trying it out for hours now but it really does seem like a bug.

**Comment by Indigo000** [comment]
So, I've been thinking about the situation for a bit. The easiest solution, I think, would be to add one line of code to **quests_malaya.txt**.

`if (malaya_bang == 42) {
			if (checkquest(11309,HUNTING) == 2) {
				callsub L_Complete;
				set malaya_bang,41;
				completequest 11309;
				callsub L_Warp, getarg(0), 1;
			} else {
				callsub L_Incomplete;
				callsub L_Warp, getarg(0);
			}
		}`

In this piece of code, behind **completequest 11309**, simply add: **setquest 9223**

This is the part where you complete the quest portion of the instance. We then set quest 9223, which is the cooldown of the instance. I'm assuming it needs this anyway after completing the quest portion.

With the cooldown quest being set and eventually the time being reached, the script in BangungotHospital.txt will let you enter properly and will set all other necessary questIDs as it should.

Not sure if this is the official way of handling it, but it will fix the problems. Frankly, I'm not sure how any server out there has the existing script running and did not notice that it currently does not work at all after one attempt =/

**Comment by Atemo** [comment]
Enter in the instance -> set 9222
[https://github.com/rathena/rathena/blob/master/npc/re/instances/BangungotHospital.txt#L320](url)
Kill Bangungot -> 9222 HUNTING completed -> set 9223 PLAYTIME
[https://github.com/rathena/rathena/blob/master/npc/re/instances/BangungotHospital.txt#L162](url)
-> erasequest/setquest 9222 : repeatable part

**Comment by Indigo000** [comment]
How does 9222 get set the first time after you do the quest though?

1. You talk to NPC
2. 9222 and 9223 are not set at this point.
3. It will check for 11309 HUNTING, which is not completed, thus it executes that piece of code.
4. It checks 9224 PLAYTIME, which is not set yet, so it will execute that piece of code.
5. It lets you enter the instance through **callsub L_Enter,(getcharid(0) == getpartyleader(.@party_id,2))?1:0,0,0;**
6. getarg(1) and getarg(2) are both set to 0.
7. It only sets 9222 when getarg(1) is set. Seeing that the callsub gives that a value of 0, 9222 will not be set.

**Comment by Indigo000** [comment]
Quick other, unrelated thing I noticed regarding to this instance.

After killing Bangungot, certain timers will still keep running, causing it to still spawn mobs and announce various things. Think about **#Summon Ward Mob_time** and **#Boss Room Entry_time**

I think I've solved it by calling an **OnStopTimer** label for the **#Boss Room Entry_time** NPC after killing the Pillar of Spirit.
