### ISSUE TITLE
[SQL]: DB error - Column 'bound' specified twice

### ISSUE THREAD

**Issue by technoken** [rathena/rathena#1510]
Hash: 04ffafa5fdc4009823c82e2bdfe1f353c8a9279c
Client: 2013-12-23
Mode: Pre-renewal
NO src edits

After killing any monster's this db error appears
```
[SQL]: DB error - Column 'bound' specified twice
[Debug]: at ..\src\map\log.c:228 - INSERT DELAYED INTO `picklog` (`time`, `char_
id`, `type`, `nameid`, `amount`, `refine`, `card0`, `card1`, `card2`, `card3`, `
map`, `unique_id`, `bound`) VALUES (NOW(), '1002', 'M', '512', '-1', '0', '0', '
0', '0', '0', 'prontera', '0', '0')
```

**Comment by Lemongrass3110** [comment]
Unable to reproduce this on 3678fca with a clean database.

**Comment by aleos89** [comment]
I'm unable to reproduce this as well. Make sure you have a clean compile and the proper SQL updates.
