### ISSUE TITLE
Catnip Powdering

### ISSUE THREAD

**Issue by Vomaito** [rathena/rathena#1512]
Hi, well I wanna notify one bug.
Skill Catnip Powdering in PvP dont reduce ATK or MATK.
Status icon  appear on target but I dont see difference (either window stats or attacking).

Thanks.

**Comment by Playtester** [comment]
Did you try with a weapon equipped? Seems it only affects weapon ATK and MATK.

**Comment by aleos89** [comment]
As Playtester stated, it's a weapon MATK and equip MATK, not status MATK.
