### ISSUE TITLE
Spiritual Sphere Absorption

### ISSUE THREAD

**Issue by ernestfegarido** [rathena/rathena#1514]
link: http://irowiki.org/wiki/Spiritual_Sphere_Absorption

This skill will not disrupt the execution of any skill in mid-cast that requires Spirit Spheres.

another bug (how to reproduce):

for example 2 sura in pvp:
1. sura1 has spheres also sura2
2. sura 1 casted slow cast absorb spirit to sura 2
3. while sura 1 casting absorb spirit sura 2 cast cursed circle to sura 1
4. the bug there is that absorb sprit cancel out when sura 2 use CC the absorb must continue casting and must continue absorb the spirit of sura 2.

**Comment by ernestfegarido** [comment]
my vido from iro official server
https://drive.google.com/open?id=0BzdeBCNzrkknbFNzY0pXSkFaNlk

**Comment by Paoly28** [comment]
hide also cancels absorption at least last time i checked on pRO if it's like that until now.

**Comment by Akaineko-astasi** [comment]
I think on rusRO a successful absorbtion on monster did disrupted its casting. Though I've got no evidence.

**Comment by ernestfegarido** [comment]
This skill will not disrupt the execution of any skill in mid-cast that requires Spirit Spheres.

**Comment by aleos89** [comment]
I just tested this again on Aegis and when Cursed Circle hits the other Sura casting Absorb, Absorb is cancelled.
