### ISSUE TITLE
Enable VIP system is error by rAthena r20072

### ISSUE THREAD

**Issue by TesLA-Git** [rathena/rathena#1515]
IF Enable VIP system and change these.

core.h
# define VIP_ENABLE
# define MIN_STORAGE 600 // Default number of storage slots.

mmo.h
# define MAX_STORAGE 850 ///Max number of storage slots a player can have, (up to ~850 tested)

player.conf
vip_storage_increase: 250

V10: Compile error and can't run properly. Please check. THX!

**Comment by cydh** [comment]
what's the error?

btw the `///Max number of storage slots a player can have, (up to ~850 tested)`, must be wrong now since after random option added, the size of item struct in increased

**Comment by TesLA-Git** [comment]
Thank for Added packet version checks for random options #1524
Find mmo.h use #define PACKETVER 20151104 still go wrong...

**Comment by anacondaqq** [comment]
If you don't planning to use random option, you can decrease a little bit item struct by changing this value from 5 to 1

https://github.com/rathena/rathena/blob/master/src/common/mmo.h#L81

Try please.

**Comment by Lemongrass3110** [comment]
Should be working again on ade1b17.
Feel free to open another issue if there are still problems after you updated.
