### ISSUE TITLE
Random option not saving after relog

### ISSUE THREAD

**Issue by mimishi** [rathena/rathena#1527]
_**Hi rAthena**_,
i try to use randomoption feature when i try to relog the bonus are gone.

# Look at this post :
https://rathena.org/board/topic/107200-random-option-not-saving-after-relog/

# This is how to reproduce this bug
**step 1** :	create "`@item shoes`" [ or any item ]
**step 2** :	equip that shoes
**step 3** :	relog [ to save the shoes state to sql ]
**step 4** :	login again
**step 5** :	put setrandomoption to that item
**script used** :	setrandomoption(2,0,1,10,0); <- use equipslot footgear
**step 6** :	relog
**step 7** :	login again 
### and the item don't have randomoption

**Comment by cydh** [comment]
https://github.com/rathena/rathena/blob/master/sql-files/upgrades/upgrade_20160814_log.sql

**Comment by Lemongrass3110** [comment]
Please use code tags if you write any atcommand. Otherwise you will link other users here on github.

**Comment by mimishi** [comment]
thank you @cydh for your replay sir but i already apply upgrade_20160814_log.sql but the randomoption still not save to the item

**Comment by cydh** [comment]
OK, I just read the source, and I confirm the keyword that this fail to save.
the item that used for `setrandomoption` is an old item (`@item Shoes` -> relog).
I know the culprit, but the entire code to check "the item is need to be saved or not" is kinda ...

**Comment by cydh** [comment]
@mimishi Try this, I wonder if this can be solution for now
```diff
diff --git a/src/char/char.c b/src/char/char.c
index b47c54c..dcd719b 100644
--- a/src/char/char.c
+++ b/src/char/char.c
@@ -626,8 +626,15 @@ int char_memitemdata_to_sql(const struct item items[], int max, int id, int tabl
 			&&  items[i].card[2] == item.card[2]
 			&&  items[i].card[3] == item.card[3]
 			) {	//They are the same item.
+				int k = 0, l = 0, m = 0;
 				ARR_FIND( 0, MAX_SLOTS, j, items[i].card[j] != item.card[j] );
+				ARR_FIND( 0, MAX_ITEM_RDM_OPT, k, items[i].option[k].id != item.option[k].id );
+				ARR_FIND( 0, MAX_ITEM_RDM_OPT, l, items[i].option[l].param != item.option[l].param );
+				ARR_FIND( 0, MAX_ITEM_RDM_OPT, m, items[i].option[m].value != item.option[m].value );
 				if( j == MAX_SLOTS &&
+				    k == MAX_ITEM_RDM_OPT &&
+				    l == MAX_ITEM_RDM_OPT &&
+				    m == MAX_ITEM_RDM_OPT &&
 				    items[i].amount == item.amount &&
 				    items[i].equip == item.equip &&
 				    items[i].identify == item.identify &&
@@ -794,8 +801,15 @@ int char_inventory_to_sql(const struct item items[], int max, int id) {
 			   &&  items[i].card[2] == item.card[2]
 			   &&  items[i].card[3] == item.card[3]
 			   ) {	//They are the same item.
+				int k = 0, l = 0, m = 0;
 				ARR_FIND( 0, MAX_SLOTS, j, items[i].card[j] != item.card[j] );
+				ARR_FIND( 0, MAX_ITEM_RDM_OPT, k, items[i].option[k].id != item.option[k].id );
+				ARR_FIND( 0, MAX_ITEM_RDM_OPT, l, items[i].option[l].param != item.option[l].param );
+				ARR_FIND( 0, MAX_ITEM_RDM_OPT, m, items[i].option[m].value != item.option[m].value );
 				if( j == MAX_SLOTS &&
+					k == MAX_ITEM_RDM_OPT &&
+					l == MAX_ITEM_RDM_OPT &&
+					m == MAX_ITEM_RDM_OPT &&
 					items[i].amount == item.amount &&
 					items[i].equip == item.equip &&
 					items[i].identify == item.identify &&
```

**Comment by mimishi** [comment]
@cydh wow thank you
i hope this may fix the randomoption feature
thank you again sir
