### ISSUE TITLE
Theore's Request wrong variable check

### ISSUE THREAD

**Issue by Indigo000** [rathena/rathena#1533]
In quests_mora.txt, there's a problem with the Theore's Request quest.

After talking to one of the Bushes, it sets:
ep14_1_bs from 3 to 4-9
ep14_1_bs2 to 1-3
quest from 11183 to 11184

Then, you're supposed to get the Pouch:
ep14_1_bs is still 4-9
ep14_1_bs2 gets updated to 4-6
quest from 11184 to 11185

Next, you're supposed to go back to Theore:
ep14_1_bs  is still 4-9
ep14_1_bs2 gets updated to 7-9
quest from 11185 to 11186

Now, the next step would be to talk to the Tired-looking Fairy. You'll find this piece of code:

`if (ep14_1_bs < 4) {
		mes "[Tired-looking Fairy]";
		mes "I'm tired, don't talk to me.";
		close;
	} else if (ep14_1_bs < 10) {
		if (checkquest(11187) == -1) {
			mes "[Tired-looking Fairy]";
			mes "I'm tired, don't talk to me.";
			next;
			select("Show the pouch.");
			mes "[Tired-looking Fairy]";
			mes "Huh?!";
			mes "Where did you get this from?!";
			next;
			select("I found it in the bushes.");
			mes "[Tired-looking Fairy]";
			mes "It may not look like much, but it is an important object for us. I suppose I should say thanks.";
			next;
			mes "[Tired-looking Fairy]";
			mes "But it won't be easy to find its owner with just the pouch...";
			changequest 11186,11187;
			next;
			if(select("I think I saw a fairy that might be the owner.:I'll think about it.") == 2) {
				mes "[Tired-looking Fairy]";
				mes "Then tell me if you remember anything.";
				close;
			}
		} else if (checkquest(11187) == 2) {
			mes "[Tired-looking Fairy]";
			mes "I hope you can find the owner.";
			close;
		}
		mes "[Tired-looking Fairy]";
		mes "Do you remember how the fairy looked?";
next;`

The problem here is that it merely checks if **ep14_1_bs** is lower than 10, which is the case even after only talking to the Bush, before even doing the Pouch or going back to Theore.

It then checks if QuestID **11187** is set, which it obviously is not. Then it wants to change quest 11186 to 11187. However, 11186 is not set if you, for whatever reason, did not get the Pouch or talk to Theore before going to this NPC, resulting in the questID not being found.

Probably the Tired-looking Fairy NPC needs some additional checks, perhaps if 11186 is set, before it tries to change it to 11187.

**Comment by Indigo000** [comment]
Also, I might be missing an update that rA had some time ago, but:

`if (BaseLevel > 99)
getexp 0, ((JobLevel < 50)?JobLevel * JobLevel * (110/100) * 50:0);
else
getexp 0, ((JobLevel < 70)?JobLevel * JobLevel * (110/100) * 10:0);`

110/100 will always result in 1, won't it?

**Comment by secretdataz** [comment]
@Indigo000 I've corrected the job exp formula. I'll look into the variable issue.
