### ISSUE TITLE
Script command unitwalk

### ISSUE THREAD

**Issue by aleos89** [rathena/rathena#1535]
Hash: fb85ce2
Mode: Both

The script command `unitwalk` is not triggering the event label when the player has reached the destination. Here is a sample script:
```
prontera,150,150,3	script	WalkTest	100,{
	sleep2 1000;
	unitwalk getcharid(3),150,155,"WalkTest::OnDoneWalk";
	end;

OnDoneWalk:
	dispbottom "You reached your destination!";
	end;
}
```

**Comment by anacondaqq** [comment]
Extra question: is it possible somehow make unitwalk for high distances?  I want for example make my mob walk from bottom to top warpportal in 1 command. Is it possible to do? If yes,  how? Or here is limitations? If yes -> where?

**Comment by aleos89** [comment]
It doesn't work over long distances. The `setunitdata` script command will attempt this already. If the distance is too far it will just warp the unit to that destination instead.
