### ISSUE TITLE
How to join the development team

### ISSUE THREAD

**Issue by invxp** [rathena/rathena#1540]
I'd like to commit & push some code.
How to join your team>.<
Thanks~

**Comment by secretdataz** [comment]
You can contribute your code without being a member of the team via pull requests. ([See details here](https://rathena.org/board/topic/86913-pull-request-qa/))
You can fill the staff application form in the forum. It's in the "community" menu.

**Comment by secretdataz** [comment]
I'll close this issue since this is not really a bug report or feature suggestion.
