### ISSUE TITLE
rental timer overflow for long rentals (over 49 days)

### ISSUE THREAD

**Issue by mrjnumber1** [rathena/rathena#1542]
for example, let us say we rent an item for 60 days. this comes out to 5.184.000 seconds from now!

when `pc_inventory_rentals` is run, the rental time is clobbered by type overflow because of this line

`expire_tick = (unsigned int)(sd->status.inventory[i].expire_time - time(NULL)) * 1000;
clif_rental_time(sd->fd, sd->status.inventory[i].nameid, (int)(expire_tick / 1000);`

the client sees this as, instead of the proper 86400 minutes to expire, it comes out to a much lower value, like 16000 or so, because a few bits overflow.

the exact point at which it overflows is when there is a rental time of around `INT32_MAX/1000` seconds

server side it is fine, but for the client side it appears quite weird. the way to fix it is to just not use `expire_tick/1000` and instead do `(sd->status.inventory[i].expire_time - time(NULL)` (or put a variable in its place that holds that value and use it for calculating `expire_tick`)

**Comment by mrjnumber1** [comment]
why the confusion @anacondaqq ?
please let me know. i am notorious for being incapable of clarifying my meaning, forgive me! i can clean up the post if necessary

**Comment by anacondaqq** [comment]
i'm sorry, nothing against your report, i'm a little bit confused because of founded by you overflow with rental expire tick.

**Comment by mrjnumber1** [comment]
ah okay.

better fix would be to move to int64 and get rid of that thing too i suppose. i dont expect it to be an issue in the future to be handing out items with several times the human life span as UINT64_MAX/1000 rental times.  anyways if it exceeds the year 2038 the client wont show it properly anyways, most likely
