### ISSUE TITLE
Hidden part of NPC name is shown when using mob_avail'd sprite ID

### ISSUE THREAD

**Issue by Weskercorp** [rathena/rathena#1543]
I use the **ID** of **mobs** in the Sprite ID of some NPCs. Those mob IDs is **disguised as a player** in mob_avail. The problem is that the Unique Name of NPCs is not hiding ( Which is the name after "#" )
Normal IDs is working fine.

Thank you
![npc](https://cloud.githubusercontent.com/assets/4960977/18257951/c6746732-73a2-11e6-94de-bc1421b0077f.png)

**Comment by Lemongrass3110** [comment]
Could you give us some samples for better understanding/easier testing?
Which client version are you on?
Git hash?

**Comment by Weskercorp** [comment]
The GIT I couldn't found ( Even if I mark 'display_version : yes' It shows "Cannot Determine SVN/GIT" ) but the last **update** was in **_november-december 2015._** The **hexed** that I'm currently using is **_2015-11-04._**
The samples that you ask, I didn't understand. You mean videos and/or gifs or scripts?

I'll interpretate as Scripts and the Mob_Avail:

**_NPC:_**
`example,87,23,6	script	Orc#0	4000,{
....
}`

_**mob_avail**_
`// To disguise a mob as a player:
// MobID,SpriteID,Sex,Hair_Style,Hair_Color,Weapon,Shield,Head_Top,Head_Middle,Head_Bottom,Option,Dye_Color
4000,4020,1,8,269,1900,0,86,0,383,0,559`

If you need anything else just ask.

**Comment by Lemongrass3110** [comment]
This is a clientside limitation. The client does not strip the `#0` if it is a job sprite.
We would have to strip it on server side in this case, if  we want to fix this issue.

**Comment by secretdataz** [comment]
We agreed that this special case should be solved by using `setnpcdisplay` in OnInit.
