### ISSUE TITLE
Mobs Using Attack Skills When Out Of Attack Range

### ISSUE THREAD

**Issue by dragonis1701** [rathena/rathena#1547]
Here is how, to my understanding, of how the battle takes place in terms of skill use. 

Player walks into attack range of monster.
Monster attacks once and then gambles for attack skill. If succeed, use skill.
Player moves out of monster's attack range.
Monster gambles for chase skill. If succeed, use skill.

Now, that is all fine and good but the gamble does not take into account the delay inbetween the monsters attacks. A monster does not use the skill immediately, as they sometimes have to wait for delays but this does not stop the skill gamble.

For example, Player moves in front of a monster for half a second and then moves out of range. Monster will attack once and gamble for attack skill even if player is no longer in range, while monster is still in attack delay, which should not happen. Try it with Orc Zombies. You'll see they will attack once and then after the player is already three or four cells away, use their 'attack' skill even though the delay should have prohibited the use of the skill.

**Comment by Playtester** [comment]
Official behavior, depending on skill. But most monster skills have a range of 9.
```
1153,Orc Zombie@NPC_CRITICALSLASH,attack,170,1,500,500,5000,no,target,always,0,,,,,,9,
1153,Orc Zombie@NPC_CRITICALSLASH,angry,170,1,500,500,5000,no,target,always,0,,,,,,9,
1153,Orc Zombie@NPC_UNDEADATTACK,attack,347,1,2000,0,5000,yes,target,always,0,,,,,,,
1153,Orc Zombie@NPC_UNDEADATTACK,angry,347,1,2000,0,5000,yes,target,always,0,,,,,,,
```
Orc Zombie has Critical Slash and Undead Attack:
```
170,-9,6,1,-1,0x20,0,10,1,no,0,0x2,0,weapon,0,0x0,	NPC_CRITICALSLASH,Defense disregard attack
347,-9,6,1,9,0,0,10,1,no,0,0x2,0,weapon,0,0x0,	NPC_UNDEADATTACK,Undead Element Attack
```
If you are more than 9 cells away, the monster should no longer be able to target you with the skill.
