### ISSUE TITLE
[skill_cast_db] Fire Dance

### ISSUE THREAD

**Issue by Jeybla** [rathena/rathena#1557]
http://irowiki.org/wiki/Fire_Dance

Should have a 500ms Cooldown.In rA it has 5s:
```
// SkillID,CastingTime,AfterCastActDelay,AfterCastWalkDelay,Duration1,Duration2,Cool Down,Fixed Casting Time
2561,0,2000,0,0,0,5000,-1
```

I'm not quite sure about this.Thx <3

**Comment by aleos89** [comment]
This is fixed in #1552. Also, maybe you meant cast delay instead of cooldown?

**Comment by Jeybla** [comment]
Yessorry I'm not really a DB-Guy.
Thanks I'll wait for the PR and close this issue.

Also thanks to @RagnarokNova and Fyrus :)

**Comment by Playtester** [comment]
Cooldown is skill-dependent time. The time to recast the same skill again.
Cast delay affects all skills. Can't use any skill during that time.
