### ISSUE TITLE
delete_timer error when use UnitKill

### ISSUE THREAD

**Issue by chadn4u** [rathena/rathena#1560]
Client Date: 2015-09-16a, preRenewal

hi...
I use unitwalkto script commands with mob , when mob has Reached the targeted unit ... mob will die.
the mob is dead. but It show the following messages on mapserv

> [Error]: delete_timer error : no such timer -33686019 <005A490E(unit_step_timer)>`
> [Error]: Memory manager: freed-data is changed. (freed in (folder path)\src\map\map.c line 214)

> 

and this the script
 

>prontera,146,194,3	script	UnitKillTest	100,{
>	.@mob_id = 2004;
>	monster	"prontera", 146, 194, "testing", .@mob_id, 1, strnpcinfo(1)+"::OnUnitDies";
>	.mob_gid = $@mobid[0];
>	setunitdata .mob_gid, 9, 131;
>  unitwalkto .mob_gid, getcharid(3),strnpcinfo(1)+"::OnFinish";
>	
>   end;
>OnUnitDies:
>end;
>OnFinish:
>	//unitblockmove .mob_gid,1;
>	//unitstopwalk .mob_gid;
>    unitkill .mob_gid;
>    end;
>}

> 

sorry for my bad english

**Comment by Hope8888** [comment]
```
prontera,146,190,3	script	UnitKillTest	100,{
	.@mob_id = 2004;
	monster "prontera", 146, 194, "testing", .@mob_id, 1, strnpcinfo(1)+"::OnUnitDies";
	.mob_gid = $@mobid[0];
	setunitdata .mob_gid, 9, 131;
	unitwalkto .mob_gid, getcharid(3),strnpcinfo(1)+"::OnFinish";
	end;
	
OnUnitDies:
	end;
	
OnFinish:
	sleep 1; // Add this
	unitkill .mob_gid;
	end;
}
```

**Comment by chadn4u** [comment]
wow its work dude...thanks...
