### ISSUE TITLE
Random Options going haywire

### ISSUE THREAD

**Issue by Darkelfen** [rathena/rathena#1561]
So not so long ago I've decided to update my live server to "latest" (hash: https://github.com/rathena/rathena/commit/e820ef9090a02e8483ef672147e159210dd09c16) and updated the SQL tables.

I'm using a storage size of 850 and a guild storage size of 999, consequently having the mmo_charstatus issue, so I've reduced the number of random options to 1 in order to avoid that issue.

So far everything was ok, but I've noticed that items with random options were appearing out of the blue. Some of my players reported having items with 4 zeroed options. What scared me the most was that I've created an item through `@item ` and it came with 4 random options but one of them were not zeroed, it was SP recovery + -3261%, then I've relogged and the options disapeared as they came.

**Edit**: Every single armor/weapon on storage got 4 zeroed options.

I dunno how this issue is generated or how it can be replicated.

**Comment by admkakaroto** [comment]
I'm having the same problem , I could solve this by using a patch in rathena , but I'm afraid it is likely to cause problems in the emulator, see about it in the link:

link: https://github.com/rathena/rathena/issues/1523

**Comment by Darkelfen** [comment]
What is concerning me is that items with random options are appearing at random without a pattern or whatsoever.... Today I've found this and it really freaked me out.

![image](https://cloud.githubusercontent.com/assets/7315177/18624007/f31759d0-7e19-11e6-8b0d-3ad669e9931d.png)

Hopefully it's just a "visual" problem, because on the SQL everything is zeroed. So, my best guess is that maybe the client isn't properly showing the items with/without random options.
 
As a side note, I've set random options to 1 on mmo.h so I'm not having the mmo_charstatus size issue.

**Comment by Lemongrass3110** [comment]
If you reduce the define to 1 you have to make sure that all of the clif functions still send out 4, because this is the packet size the client expects. The rest will possibly cause visual glitches like the ones you describe because of uninitialized memory on clientside or parts of the packets after the item packets being read into your random options.

**Comment by admkakaroto** [comment]
@Lemongrass3110 
You advised not to use this diff ?

Diff; https://raw.githubusercontent.com/vstumpf/ragnarok/master/mmo_charstatuspacketlength.diff

**Comment by Darkelfen** [comment]
@Lemongrass3110  Thank you, it was indeed solved. I'll be monitoring if an item apears but I doubt so.
