### ISSUE TITLE
Madogear (Mechanic) doesn't able to receive supportive skills like Power-Thrust and Canto Candidus

### ISSUE THREAD

**Issue by Felleonel** [rathena/rathena#1564]
Sorry for the mistakes in the title, I was thinking about how to describe my problem and it's the first time that i'm doing it here. Mechanics can't get Agi Up from Canto Candidus while being in their madogear. Same for Power-Thrust,

According to iROWiki:

> Receiving skills:
When wearing madogear, the player is unable to receive certain supportive skills, such as:
Increase Agility
Heal
Adrenaline Rush
Coluseo Heal**
Renovatio

> **However,  the player can receive Increase Agility from Cantocandidus.**

http://irowiki.org/wiki/Madogear

I'm using rAthena's latest version (Renewal).

**Comment by aleos89** [comment]
As per patch 0677347, the info you have is wrong. It was a bug on Aegis and was fixed on kRO.
