### ISSUE TITLE
Sorcerer skill Warmer doesn't work.

### ISSUE THREAD

**Issue by Felleonel** [rathena/rathena#1565]
Warmer doesn't cure and prevent negative status like Frozen, Freezing and Crystallization, even if staying a while on it. And also, doesn't recover HP every 3 seconds too.

I'm using rAthena's latest version (Renewal).

**Comment by aleos89** [comment]
Can you provide which hash you are on rather than "latest"? Thanks!

**Comment by Felleonel** [comment]
hash: f296409

**Comment by aleos89** [comment]
Tested on 8e3da7f and was unable to reproduce any issue. The statuses were removed while the player was in Warmer.
