### ISSUE TITLE
Update item_buyingstore?

### ISSUE THREAD

**Issue by zackdreaver** [rathena/rathena#1566]
Can we update item_buyingstore for both PreRenewal and Renewal?
I hope the prerenewal item_buyingstore can adapt the items from Renewal item_buyingstore.
I want to buy Alcohol (not irl ofc) through buying store, but I can't.

**Comment by aleos89** [comment]
I can understand updating renewal, but pre-renewal? This feature didn't exist for pre-renewal, correct?

**Comment by zackdreaver** [comment]
If this feature isn't exist in prerenewal then no point including item_buyingstore in prerenewal db.
Heh.

It just suggestion from me, to include Renewal item in item_buyingstore that present in prerenewal db.
