### ISSUE TITLE
RODEX completely unsupported !

### ISSUE THREAD

**Issue by mrjnumber1** [rathena/rathena#1567]
NOTE TO SERVER OWNERS: this means when you use 2015+ clients, there is no mail support available. if you're not a dev or using 2014- the rest of this msg probably doesn't pertain to you. :)

Not sure why it's been so long without touch (over 2 years now!) but RODEX is completely unsupported and looked at, curious why ?

We have at least info in packet_db about how mail works, here's some info on packets!!

`0x09E7,3       // ZC_NOTIFY_UNREADMAIL`
`@send 9e7`
B1 ==>  RODEX icon appears

`0x09ED,3       // ZC_ACK_WRITE_MAIL`
`@send 9ed`
B0 ==> Msg: Your mail has been sent.
B1 -> Msg: Mail delivery failed. (some unknown message ?)
B2 -> Msg: Sending mail count exceeded. (dest mailbox full?)
B3 -> Msg: Transmission has failed to inappropriate items. (tried to send untradeable item?)
B4 -> Msg: Information of the recipient does not exist. (Bad dest user?)
`0x0A12,27  // ZC_ACK_OPEN_WRITE_MAIL`
`@send a12`
(with no data) ==> Msg: You can not open the mail.
I believe users need a global variable stating how many mails they have available to send. Because by default they start 99 stamps?
..and much much more to be looked at :D

i will dig more later on. hopefully there's more info out there

**Comment by secretdataz** [comment]
Please use `@command` inside a code block or you gonna mention a GitHub user.

**Comment by wilkemeyer** [comment]
```c++
  HEADER_ZC_NOTIFY_UNREADMAIL = 0x9E7
  HEADER_CZ_OPEN_MAILBOX = 0x9E8
  HEADER_CZ_CLOSE_MAILBOX = 0x9E9
  HEADER_CZ_REQ_READ_MAIL = 0x9EA
  HEADER_ZC_ACK_READ_MAIL = 0x9EB
  HEADER_CZ_REQ_WRITE_MAIL = 0x9EC
  HEADER_ZC_ACK_WRITE_MAIL = 0x9ED
  HEADER_CZ_REQ_NEXT_MAIL_LIST = 0x9EE
  HEADER_CZ_REQ_REFRESH_MAIL_LIST = 0x9EF
  HEADER_ZC_ACK_MAIL_LIST = 0x9F0
  HEADER_CZ_REQ_ZENY_FROM_MAIL = 0x9F1
  HEADER_ZC_ACK_ZENY_FROM_MAIL = 0x9F2
  HEADER_CZ_REQ_ITEM_FROM_MAIL = 0x9F3
  HEADER_ZC_ACK_ITEM_FROM_MAIL = 0x9F4
  HEADER_CZ_REQ_DELETE_MAIL = 0x9F5
  HEADER_ZC_ACK_DELETE_MAIL = 0x9F6
  HEADER_CZ_REQ_CANCEL_WRITE_MAIL = 0xA03
  HEADER_CZ_REQ_ADD_ITEM_TO_MAIL = 0xA04
  HEADER_ZC_ACK_ADD_ITEM_TO_MAIL = 0xA05
  HEADER_CZ_REQ_REMOVE_ITEM_MAIL = 0xA06
  HEADER_ZC_ACK_REMOVE_ITEM_MAIL = 0xA07
  HEADER_CZ_REQ_OPEN_WRITE_MAIL = 0xA08
  HEADER_ZC_ACK_OPEN_WRITE_MAIL = 0xA12

#pragma pack(push, 1)

struct PACKET_ZC_NOTIFY_UNREADMAIL
{
  short PacketType;
  bool result;
};

struct PACKET_CZ_OPEN_MAILBOX
{
  short PacketType;
  char opentype;
  __int64 Upper_MailID;
};

struct PACKET_CZ_CLOSE_MAILBOX
{
  short PacketType;
};

struct PACKET_CZ_REQ_READ_MAIL
{
  short PacketType;
  char opentype;
  __int64 MailID;
};

struct PACKET_ZC_ACK_READ_MAIL
{
  short PacketType;
  short PacketLength;
  char opentype;
  __int64 MailID;
  short TextcontentsLength;
  __int64 zeny;
  char ItemCnt;
};

struct PACKET_CZ_REQ_WRITE_MAIL
{
  short PacketType;
  short PacketLength;
  char receiveName[24];
  char senderName[24];
  __int64 zeny;
  short Titlelength;
  short TextcontentsLength;
};

struct PACKET_CZ_REQ_NEXT_MAIL_LIST
{
  short PacketType;
  char opentype;
  __int64 Lower_MailID;
};

struct PACKET_CZ_REQ_REFRESH_MAIL_LIST
{
  short PacketType;
  char opentype;
  __int64 Upper_MailID;
};

struct PACKET_ZC_ACK_MAIL_LIST
{
  short PacketType;
  short PacketLength;
  char opentype;
  char cnt;
  bool IsEnd;
};

struct PACKET_CZ_REQ_ZENY_FROM_MAIL
{
  short PacketType;
  __int64 MailID;
  char opentype;
};

struct PACKET_ZC_ACK_ZENY_FROM_MAIL
{
  short PacketType;
  __int64 MailID;
  char opentype;
  char result;
};

struct PACKET_CZ_REQ_ITEM_FROM_MAIL
{
  short PacketType;
  __int64 MailID;
  char opentype;
};

struct PACKET_ZC_ACK_ITEM_FROM_MAIL
{
  short PacketType;
  __int64 MailID;
  char opentype;
  char result;
};

struct PACKET_CZ_REQ_DELETE_MAIL
{
  short PacketType;
  char opentype;
  __int64 MailID;
};

struct PACKET_ZC_ACK_DELETE_MAIL
{
  short PacketType;
  char opentype;
  __int64 MailID;
};

struct PACKET_CZ_REQ_CANCEL_WRITE_MAIL
{
  short PacketType;
};

struct PACKET_CZ_REQ_ADD_ITEM_TO_MAIL
{
  short PacketType;
  short index;
  short count;
};

struct PACKET_ZC_ACK_ADD_ITEM_TO_MAIL
{
  short PacketType;
  char result;
  short index;
  short count;
  unsigned short ITID;
  char type;
  bool IsIdentified;
  bool IsDamaged;
  char refiningLevel;
  EQUIPSLOTINFO slot;
  ITEM_RDM_OPT optionData;
  short weight;
};

struct PACKET_CZ_REQ_REMOVE_ITEM_MAIL
{
  short PacketType;
  short index;
  unsigned short cnt;
};

struct PACKET_ZC_ACK_REMOVE_ITEM_MAIL
{
  short PacketType;
  bool result;
  short index;
  unsigned short cnt;
  short weight;
};

struct PACKET_CZ_REQ_OPEN_WRITE_MAIL
{
  short PacketType;
  char receiveName[24];
};

struct PACKET_ZC_ACK_OPEN_WRITE_MAIL
{
  short PacketType;
  char receiveName[24];
  bool result;
};




// 
struct ITEM_RDM_OPT_DATA
{
  short OptIndex;
  short Value;
  char Parm1;
};

struct ITEM_RDM_OPT
{
  ITEM_RDM_OPT_DATA data[5];
};

struct EQUIPSLOTINFO
{
  unsigned short info[4];
};

#pragma pack(pop)
```

hf 👍

**Comment by cydh** [comment]
@wilkemeyer no `PACKET_ZC_ACK_WRITE_MAIL`? or just be
```c++
struct PACKET_ZC_ACK_WRITE_MAIL
{
  short PacketType;
  char result;
};
```

**Comment by wilkemeyer** [comment]
@cydh  oh damn :D i missed it. & yup it's
```c++
struct PACKET_ZC_ACK_WRITE_MAIL
{
  short PacketType;
  char result;
};
```

**Comment by cydh** [comment]
Thank you very much

**Comment by mrjnumber1** [comment]
thanks @wilkemeyer there was some stuff i had missing still. here is the info on item flags i had as well, also there were updates to the add item to mail packet

`ZC_NOTIFY_UNREADMAIL` flag > `
1= send rodex icon `
`ZC_ACK_WRITE_MAIL` flag > `
		1 = delivery fail, 
		2 = too much mail? 
		3 = cant send some item 
		4 = bad dest user ?`
`ZC_ACK_ZENY_FROM_MAIL` flag >`
		0 = zeny received
		1 = failed to get zeny
		2 = you have too much zeny`
`ZC_ACK_ITEM_FROM_MAIL` flag >`
		0 = moved to inventory
		1 = failed to get items (over 100?)
		2 = please empty your inventory (not enough weight?)
`ZC_ACK_ADD_ITEM_TO_MAIL` length is 53, it has also B favorite tab and L for expire time or maybe `pc_equippoint` result
`ZC_ACK_REMOVE_ITEM_MAIL` flag >`
	0 = failed remove 
	1 = removed`
ZC_ACK_OPEN_WRITE_MAIL flag > `
		1= opens write message`

**Comment by wilkemeyer** [comment]
@mrjnumber1 
Enum for ZC_ACK_WRITE_MAIL 
{
  WRITE_MAIL_SUCCESS = 0,
  WRITE_MAIL_FAILED,
  WRITE_MAIL_FAILED_CNT,
  WRITE_MAIL_FAILED_ITEM,
  WRITE_MAIL_FAILED_CHECK_CHARACTER_NAME,
  WRITE_MAIL_FAILED_WHISPEREXREGISTER
}


struct for ack_mail_list is:

struct maillistinfo
{
  __int64 MailID;
  bool Isread;
  char type;
  char SenderName[24];
  int regDateTime;
  int expireDateTime;
  short Titlelength;
};

i'm a bit busy right now, i'll add more structs/enums later (if you've any specific problem just write a comment) 

the type is a mask, i'll check client-specific implementation later, the client may ignore it.. 
enum MAIL_TYPE {
  MAIL_TYPE_TEXT = 0x0,
  MAIL_TYPE_ZENY = 0x2,
  MAIL_TYPE_ITEM = 0x4,
  MAIL_TYPE_NPC = 0x8
}

**Comment by Everade** [comment]
Sidenote:
RoDex has been redesigned from what i've seen.
So a few things might have changed already.

So in case it's being worked on, i wonder which client version will be required.

**Comment by TrueNoir** [comment]
We have any updates on the status of this o_O?

**Comment by daisyanne1380** [comment]
was the old packets from the original mail system removed? is it possible to just use the old mail system in 2015 client ?

**Comment by anacondaqq** [comment]
@daisyanne1380 no, it's not possible to use old mail system in new client, because new client do not know about old mail system (another packets)

**Comment by V0rr** [comment]
I'm using **2016-02-03a** and it works perfectly. Thank you Lemon
