### ISSUE TITLE
Sohee Pet Script Command Discrepancies

### ISSUE THREAD

**Issue by Akkarinage** [rathena/rathena#1576]
In (pre-)re/pet_db.txt, Sohee uses a pet command that is labelled as deprecated and no longer used in script_commands.txt.

`'petheal' is deprecated and is no longer used in the default pet scripts.`

`1170,SOHEE,Sohee,63 ... ,200,{ petheal 400,60,33,100; },{ bonus bStr,1; bonus bDex,1; }`

This should be changed to petskillsupport "AL_HEAL",.. to match the others, and we may as well remove the petheal command altogether.

**Comment by secretdataz** [comment]
Our pet scripts are just outdated in general.
