### ISSUE TITLE
Test in Aegis

### ISSUE THREAD

**Issue by esu1214** [rathena/rathena#1578]
I have setup an Aegis Server of EP15.2.
Hope it will be helpful to rA.
Now, the test way is here:
http://bbs.ro250.com...ewthread&tid=15

I will apply an English patch in a few days.

**Comment by secretdataz** [comment]
Your link isn't accessible.

**Comment by Lemongrass3110** [comment]
http://bbs.ro250.com/forum.php?mod=viewthread&tid=15

**Comment by lucasoli** [comment]
@esu1214 thanks for setting up this Aegis environment. Also, do you have the raw script for enchanting the AW and FAW in this Aegis package?
@Lemongrass3110 thanks for the corrected link.

**Comment by Lemongrass3110** [comment]
https://github.com/rathena/rathena/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3Aneeds+official+info%22 waiting for your comments guys :+1:

**Comment by lucasoli** [comment]
Hey Lemmon, recently (actually, yesterday) the brazilian server (bRO) received an update regarding the Final Battle Episode. You guys consider bRO information as official info? Cause I'm playing there since 2012 and I'm able to test some stuffs for you guys... I know that our Aegis have a lot of customizations on the database, but base content (npc scripts, features etc) may be original.

**Comment by secretdataz** [comment]
@lucasoli We do accept bRO as a source of info. However, whether to accept or reject certain piece of info is still up to the team.

**Comment by lucasoli** [comment]
@secretdataz Wow, this is amazing! I'm able to test and share some informations... I'm gonna look at all the bugs that I'm able to reproduce under bRO server, I'll be updating those issues as soon as I get a solid information.

Thanks!!

**Comment by cydh** [comment]
恭喜您，您的游戏帐号已经注册成功．
is Aegis that used by twRO?

**Comment by esu1214** [comment]
Yes, it's from twro.
I will upload a simple client in a few days.

**Comment by cydh** [comment]
@esu1214 done with lite client?

**Comment by esu1214** [comment]
Hi, I will share the lite patch for kro client on ra board.

**Comment by Akkarinage** [comment]
Closure of non-issue.
