### ISSUE TITLE
Kill monster in group = close NPC chat window = char stuck

### ISSUE THREAD

**Issue by AtomixRO** [rathena/rathena#158]
Hi,
I've got several reports and have experienced this myself today that when you are in a party and that one of your member (or party leader) kills a monster anywhere in the world (let's say you are in prontera and he's in toy factory) and that you have a NPC chat windows (like warper), the windows will close and your char will be stuck. The only way to fix this is to use @go or relog.
This bug occurs all the time.
Is there a way to fix this ?

Thanks

PS: there is no error in map/char server

**Comment by cydh** [comment]
someone need make something like `getvariableofpc` to get rid the `addrid` usages that will deattach other player while talking with NPC because of the Hunting Mission.
