### ISSUE TITLE
Frigg's Song

### ISSUE THREAD

**Issue by Felleonel** [rathena/rathena#1583]
> As of the Hero's Trial III patch, Frigg's will no longer replace other Group A Songs such as Swing Dance, Moonlight Serenade, and Windmill Rush. This means that Frigg's Song can now independently stack with these other buffs, as well as with Group B Songs.
> 
> Can no longer be used to remove and be removed by other performer
> 
> Can now be cast at the same time as 2nd class songs with Voice lessons at level 5 and up.

Ref: http://irowiki.org/wiki/Frigg%27s_Song
Ref 2: https://forums.warpportal.com/index.php?/topic/193598-group-a-b-songs/

**Comment by aleos89** [comment]
We need to confirm if this is a iRO only fix.

**Comment by aleos89** [comment]
Seems like it was related to the Hero's Trail patch. Since iRO got it recently that's why the change on iRO Wiki happened.

Sources:
https://www.youtube.com/watch?v=Jzsa70SP3PQ
https://www.youtube.com/watch?v=tczZ-YlZ0dE
