### ISSUE TITLE
Essence of Evil

### ISSUE THREAD

**Issue by sader1992** [rathena/rathena#1586]
right now it's for Example
`4908,Essence_of_Evil_STR1,Essence of Evil STR1,6,20,,10,,,,,,,,,,,,,{ bonus bStr,1; bonus bBaseAtk,3; bonus bInt,-1;},{},{}`

and it must be
`4908,Essence_of_Evil_STR1,Essence of Evil STR1,6,20,,10,,,,,,,,1023,,,,,{ bonus bStr,1; bonus bBaseAtk,3; bonus bInt,-1;},{},{}`

the card place is 1023 
can put in any item type

the items id is : 4908 , 4909 , 4910 , 4911 , 4912 , 4913 , 4914 , 4915 , 4916 , 4917 , 4918 , 4919 , 4920 , 4921 , 4922 , 4923 , 4924 , 4925 .

in db/re/item_db.txt

i think the same in the sql files but not sure cuz i don't use them .

**Comment by cydh** [comment]
Any info for those item position?
Afaik at first place, players are never can obtain enhancement stones (ID from 4700). So on Aegis server, if u force to get the item, yes, you can double-click it and compound in any items

**Comment by sader1992** [comment]
they can be obtained through
http://irowiki.org/wiki/Temple_of_Demon_God
http://www.novaragnarok.com/wiki/Temple_of_the_Demon_God
and if the loc is null you can not double-click them
