### ISSUE TITLE
Random Option gets removed upon de-carding the item

### ISSUE THREAD

**Issue by keitenai** [rathena/rathena#1587]
Random Option that's been applied to an item gets removed upon de-carding.

**Comment by Lemongrass3110** [comment]
Which npc or commands are you using for card removal?

**Comment by cydh** [comment]
confirmed by source.
@Lemongrass3110, u can check the
```c++
BUILDIN_FUNC(failedremovecards)
BUILDIN_FUNC(successremovecards)
```
don't remap the random options.
