### ISSUE TITLE
Pierce skill bug, won't increase after lvl 3

### ISSUE THREAD

**Issue by hendra814** [rathena/rathena#1588]
here my SS in game using lastest rathena and client 2015-11-04

![screenapel ro016](https://cloud.githubusercontent.com/assets/9587609/19034343/1bd420a0-898d-11e6-888b-be91a2763c8a.jpg)
![screenapel ro017](https://cloud.githubusercontent.com/assets/9587609/19034344/1bd99b0c-898d-11e6-938d-9a2bd431a086.jpg)
![screenapel ro018](https://cloud.githubusercontent.com/assets/9587609/19034342/1bccb4c8-898d-11e6-8f38-28644cf498f0.jpg)

**Comment by cydh** [comment]
check your client lua related with skill, check the max level there

**Comment by cydh** [comment]
U cant level up skills when u wearing equip with bonus skill. Intended

**Comment by hendra814** [comment]
it's right the problem because i'm wearing Battle Hook.
Thanks.
