### ISSUE TITLE
Old Glast Heim Instance Bugs

### ISSUE THREAD

**Issue by AbuGosok** [rathena/rathena#1591]
latest rev of rAthena. This is script bugs based on npc/re/instances/OldGlastHeim.txt
Based on http://irowiki.org/wiki/Old_Glast_Heim

Number 18, after doing A part:
B) Go to the Treasure Room on the 2nd Floor to collect 7 Coagulated Spells and other loots. Click on the fountain in the top right corner of the 2nd Floor to be warped to the Treasure Room in the middle.

After we kill the last boss (MVP Amdarais) the portal to go back to first floor did not open.

Also, these NPC does not exist: Hugin's Butler (glast_01 210, 273), Hugin's Craftsman (glast_01 210, 270), Hugin's Magic Master (glast_01 212, 273)

**Comment by Atemo** [comment]
Related to #1554
