### ISSUE TITLE
AutoSpellWhenHit wrong source in range check

### ISSUE THREAD

**Issue by chriser-** [rathena/rathena#1593]
When checking the range of a skill in `autospell2` ([skill.c:2386](https://github.com/rathena/rathena/blob/master/src/map/skill.c#L2386)), the wrong source is taken.
`src` needs to be changed to `bl`, because the range of the skill should be calculated from the carrier of the card and not from the attacker.

Currently: 
- Wearing a High Priest Card will not cast Assumptio when the attacker is out of range for Assumptio (meaning more then 9 cells away), even though Assumptio will be cast on yourself.
- Wearing a card that targets the attacker will check the range from attacker to attacker (which is 0)

Intended: 
- Assumptio should not check the range to the caster, but the range to yourself (which is 0)
- Wearing a card that targets the attacker should check the range from yourself to attacker.

**Comment by aleos89** [comment]
I wasn't able to confirm this. I enabled the battle_config and went to testing. I use the Ramen Hat during my tests and the target received Decrease Agility just fine at a range (using with Ranger).

**Comment by chriser-** [comment]
decrease agi has a range of 9. how far away have you been with your ranger? if you were more than 9 cells away and you still got decrease agi, that is wrong behavior. you should not be able to auto cast decrease agi on someone who is further away than the range of the spell.

we noticed this wrong behavior when giving a full heal effect on self when getting attacked. the full heal only triggered when the attacker was right beside you.

**Comment by Playtester** [comment]
Can't confirm either. I tried with High Priest Card and I attacked at 14 cell range and autocast still works. So it's working fine in default rAthena.

Closing this.

**Comment by Playtester** [comment]
Reopening this as @aleos89 pointed out to me that I need to activated the battle config to test this properly. Indeed the way this feature is coded is wrong and src needs to be replaced with bl.
