### ISSUE TITLE
 Rand attack in nonfunctional refinement

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#1596]
Currently I checked the equipment refining system with random bonus ATK is not working.

A weapons LV4 for example, after the fifth refining should add in a weapons attack rand (0 ~ 14), which now appears to be constant. In refine_db.txt have the correct information, but does not appear to work. 

In the right situation an armament for example, +12 refining could have difference in the damage other equal also +12.

Link: http://irowiki.org/wiki/Refinement_System   **(Effects Gained)**
NOTE: The link follows a model similar to the refine_db the rAthena, but the end result is strange. There is no difference between weapons refinements.

**Comment by secretdataz** [comment]
@cydh Should this also be closed?

**Comment by aleos89** [comment]
Fixed in 105cc3a.
