### ISSUE TITLE
Malangdo Costume Enchants

### ISSUE THREAD

**Issue by zackdreaver** [rathena/rathena#1599]
* **rAthena Hash**: f2413307cf4667d4c9f130f75c8905e33db10735

* **Client Date**: n/a

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Malangdo costume enchanter isn't presents
  * Expected Result: Should be present to fill official costume feature.
  * How to Reproduce: check NPC script
  * Official Information:
http://irowiki.org/wiki/Malangdo_Costume_Enchants
https://forums.warpportal.com/index.php?/topic/130315-unofficial-ragnarok-what-to-look-forward-to-thread/
https://www.youtube.com/watch?v=GUjpLZvN8WQ

* **Modifications that may affect results**: n/a

**Comment by mazvi** [comment]
yes i also ask like you Is there any plan on implementing this NPCs?

http://irowiki.org/wiki/Malangdo_Costume_Enchants

**Comment by CyberDevil75** [comment]
there is a custom script here to start an official release: https://rathena.org/board/topic/117210-malangdo-costume-enchant-npc/

**Comment by tddupree7** [comment]
> there is a custom script here to start an official release: https://rathena.org/board/topic/117210-malangdo-costume-enchant-npc/

This link died, anyone working on this project?

**Comment by Atemo** [comment]
https://github.com/rathena/rathena/commit/ee111cdef22d6856a6e0b489268466ee9d9a26ef
