### ISSUE TITLE
Manhole & Emperium

### ISSUE THREAD

**Issue by ignizh** [rathena/rathena#1601]
The emperium and guardian stones at bg are target-able by Manhole making impossible to kill

**Comment by aleos89** [comment]
Do official servers disable the placement of Manhole under those target types (non-aggressive ones)?

**Comment by ignizh** [comment]
Yes

http://en.kafra.ru/t250466.html
http://forums.irowiki.org/index.php?PHPSESSID=jm06n5elikna44vca2qm9eoda0&topic=33450.msg826901#msg826901
http://forums.irowiki.org/index.php?topic=66556.msg1007303#msg1007303
