### ISSUE TITLE
HD Refiner Mighty Hammer

### ISSUE THREAD

**Issue by Jeybla** [rathena/rathena#1626]
Should be able to **continue** refining if the equipment drops below +7.

>  HD Oridicon/Elunium and Mighty Hammer

> HD Oridicon and HD Elunium can be used by talking to Mighty Hammer ( /navi moc_paraup 38/185 ) on the second floor of the Eden Group. Your gear must be +7 or higher in order to begin upgrading it with HD ore. However, if it subsequently falls below +7, as long as you do not exit the conversation with the NPC or run out of HD ore, you can continue to use HD ore to upgrade it without chance of breakage. It is recommended to have over 100 HD ore before you start trying to upgrade, and if you fall below 100 HD ore, you should stop upgrading once you get the gear back to +7, and go buy more HD ore before resuming upgrading attempts. 

http://irowiki.org/wiki/Refinement_System

(I don't like this behavior since it looks like a bug, but seems to be official...)

**Comment by Atemo** [comment]
iro feature. The current hd refiner npc is [https://github.com/rathena/rathena/blob/master/npc/re/merchants/hd_refiner.txt](url)
