### ISSUE TITLE
Error when using commands.

### ISSUE THREAD

**Issue by Triedge** [rathena/rathena#1629]
**Rathena build**: last!
**Client**: 2015-11-04a
**Type server**: Pre-renewal.

**Q: How reproduce the error?**
**R**: Write command: `"@go 0"`

**Result**:
- In the game **nothing** happens.
- the following message appears **on the console**.
![screenshot_12](https://cloud.githubusercontent.com/assets/5862340/19446309/d2be2146-945d-11e6-9144-63865ceceb7e.png)

**Comment by Lemongrass3110** [comment]
Please use code quotes when writing the `@` symbol, because it is used for linking other github users.

I'm unable to reproduce this on 55c5627. Could you please give us your real hash(last! is not valid) and tell us which source changes you did?

**Comment by Lemongrass3110** [comment]
Make sure you at least have a89ab2f, because before this one 2015-11-04 was a little broken when it came down to chatting.

**Comment by Triedge** [comment]
my revision:
![screenshot_13](https://cloud.githubusercontent.com/assets/5862340/19451464/f5e9cd9a-9472-11e6-99f6-d172c3aa0557.png)

**Comment by Triedge** [comment]
This bug occurs in PRE-RE and RE.

**Comment by Lemongrass3110** [comment]
![rathena svn](https://cloud.githubusercontent.com/assets/3517879/19454713/836d249a-94ba-11e6-8ab3-f7437138b03e.png)

I do not know where you got that revision from, but somehow you seem to be more up to date than we are.

**Comment by Triedge** [comment]
Oh, my mistake, had misconfigured the mmo.h
sorry so much >_<
