### ISSUE TITLE
card remover script error

### ISSUE THREAD

**Issue by iubantot** [rathena/rathena#1631]
![capture](https://cloud.githubusercontent.com/assets/13269331/19489704/dd2a87fe-959e-11e6-8738-9424b740175e.PNG)

using latest git of rathena

**Comment by Lemongrass3110** [comment]
npc/rox_script/card_remover is not part of rAthena. So your report is invalid.

From guessing I would say you are missing npc/other/Global_Functions.txt and the function F_getpositionname in there.

**Comment by iubantot** [comment]
oh actually i just renamed the folder still exists even if i dont rename it

**Comment by Lemongrass3110** [comment]
https://travis-ci.org/rathena/rathena/jobs/168745636#L617

As you can see in our CI build there are no errors in the script on rAthena itself, so please see if you have any local changes that might cause this.
