### ISSUE TITLE
Insufficent information about skill state

### ISSUE THREAD

**Issue by Temtaime** [rathena/rathena#1636]
Sometimes i see
[Warning]: mob_parse_row_mobskilldb: Unrecognized state

But it can't figure where it comes from.

**Comment by Lemongrass3110** [comment]
You can merge the changes from my pull request to get the line number that is causing this error.

**Comment by Akkarinage** [comment]
@Temtaime can we close this off?

**Comment by Temtaime** [comment]
Yes seems to be OK.
Merge it, guys !
