### ISSUE TITLE
Kiel Hyre Quest Exp

### ISSUE THREAD

**Issue by juanfus** [rathena/rathena#1639]
acording irowiki , when you get the taming gift set you should get 700,000Base Exp (renewal)

line 4045 getexp (checkre(3))?70000:700000,0;

and when you bring the ring to kiel hyre  should be 2,000,000 Base EXP (3,000,000 VIP) (in 2 increments), and 500,000 Job EXP (750,000 VIP)

line 4672 getexp (checkre(3))?100000:1000000,0;

http://irowiki.org/wiki/Kiel_Hyre_Quest (last modified on 20 May 2016)

**Comment by Akkarinage** [comment]
@rathena/rathena-script-db-developers any of you guys want to provide any input?

**Comment by Atemo** [comment]
It's 'invalid' according to our datas. However idk if kro made change / irowiki is wrong (probably) / it's iro customization... need more infos.

**Comment by Akkarinage** [comment]
I've double checked through the scripts we have and it matches rA's. Marking as invalid.
