### ISSUE TITLE
Occult Impaction damage

### ISSUE THREAD

**Issue by Playtester** [rathena/rathena#1641]
Some players pointed out that Occult Impaction deals way too much damage against Sleepers on rAthena based servers in pre-renewal and so I investigated why.

I figured it's because we double the damage twice. Once by putting the damage formulas as `200%+150%*level` (instead of `100%+75%*level`) and a second time by returning "2" when calling `is_attack_piercing` here:
```
	if (skill_id == MO_INVESTIGATE || skill_id == RL_MASS_SPIRAL)
		return 2;
```
Because it returns "2" instead of "1" the damage is doubled a second time.

iROwiki lists damage as: `(200%+150%*level)*(DEF+VITDEF)/100`
jROwiki lists damage as: `(100%+75%*level)*(DEF+VITDEF)/50`
Our formula: `(200%+150%*level)*(DEF+VITDEF)/50`

The damage going by iROwiki and jROwiki is actually equal if you do the math, only our damage is double as high.

Now I have no way to test pre-renewal myself, so I can't confirm, but it's worth investigating (intended innuendo).

**Comment by Lemongrass3110** [comment]
Since ours seems to be a mix of both i'd say follow whichever of these two you like better, because as you pointed out if you do the math the output will be the same. The problem is that our first part comes from iRO and the end from jRO.

**Comment by Playtester** [comment]
Better test the renewal damage since ice pick effect is different there, so it actually matters which of the two parts we modify. If renewal damage is already correct like this, we need to make an ifdef.

**Comment by Playtester** [comment]
Renewal test: Occult Impaction Level 5, 99 STR, Stunner vs. Sleeper = 2700 damage

**Comment by Playtester** [comment]
Result: The damage is 475% on both pre-renewal and renewal on level 5.

In pre-renewal the damage is multiplied with `(DEF+VITDEF)/50`.
In renewal the damage is increased by `(DEF*RATIO)/2`.

Technically in renewal it's probably so that the ice pick effect is applied even before the ratio, but I'm not sure to which of the 4 attack types it should apply to and I don't want to restructure everything, so I'll simply apply RATIO in the def calculation as above.
