### ISSUE TITLE
Bind Trap explosion dmg formula is wrong

### ISSUE THREAD

**Issue by limitro** [rathena/rathena#1643]
According to iRO wiki formula, the Bind trap formula should be reducing monster HP by %...
![image](https://cloud.githubusercontent.com/assets/9300961/19556985/05abb772-96c4-11e6-8449-7938cc4aed23.png)

Tested with rAthena latest 40430d6
The dmg is not reducing by % stated on iRO wiki.

Even in jRO, the image shows 250k HP evil druid
![image](https://cloud.githubusercontent.com/assets/9300961/19557030/39ea584a-96c4-11e6-819a-edd016e74d6c.png)

So... at level 5 bind trap it should take 15% of monster's hp 
Dmg not affected by Lex.
- Dex bonus ofcourse.

More details:

![image](https://cloud.githubusercontent.com/assets/9300961/19557566/a6cda230-96c6-11e6-9888-d9ebfbd11299.png)
and
![image](https://cloud.githubusercontent.com/assets/9300961/19557574/acb0fbca-96c6-11e6-861a-0740de56b56f.png)

**Comment by limitro** [comment]
Also the Bound Trap cast behavior is wrong in rA...
**It should be 1 click and auto cast under the player's position.**

But right now, it works like other traps where you have to select an empty ground.

**Comment by Lemongrass3110** [comment]
Could you redo your tests on #1552 bind trap was adjusted there.

**Comment by limitro** [comment]
@Lemongrass3110 , I'm using the latest rA 2016.10.20 git.. hm... isn't #1552 included in there?

**Comment by Lemongrass3110** [comment]
No it's still under testing. If we get your feedback for bind trap on it with official tests/comparissons that is a big plus for us. :+1:

**Comment by exneval** [comment]
some iRO players said Bind Trap damage affected by lex, and also have a doubt about the formula
where did you get the source information @limitro

**Comment by limitro** [comment]
@exneval I haven't got any leaks from official servers.
It's all community contributions by those players who aim for a perfect working rebellion class.

They have been digging for information and have provided me with videos which I take guesses from by watching.

The Bound Trap cast behavior is for sure a bug in current rA git, as there are clear jRO video and kRO video that shows the trap is castes directly under the player and not like other trap casting behavior.

About the damage formula, for now there are detailed wiki from LeikaRo (ofcourse not official) and a little from iRO wiki which the main report content has screen.

**Comment by aleos89** [comment]
Fixed in #1692.
