### ISSUE TITLE
new item bonus repost

### ISSUE THREAD

**Issue by joelolopez** [rathena/rathena#1647]
"Def + 30, Mdef + 10.";
"Adds a high chance of inflicting the silence status to enemy when receiving physical and magical attack.",
"When compounded on Royal Guard Ring, Atk + 5% and Matk + 5%.",
"When dealing physical or magical attack. **Has a low chance to transform into Dead Monarch (Lich Lord) for 7 seconds.",**
"**While under Lich Lord form, ignore target Def and Mdef by 100%.**",
this description also from translated iteminfo 

this bonus is the same with the 3rd job bio lab monsters, but transformed into seyren,trentini,randel etc

-i tried mixing some of bonuses and transformation script but no luck, my server crash

more info:
http://www.divine-pride.net/database/item/27025/

im using 20151104 client

**Comment by aleos89** [comment]
Fixed in 887efa4ea45fb498ca4d95f73703925efc5752fa.
