### ISSUE TITLE
RK's aspd penalty when mounting a dragon

### ISSUE THREAD

**Issue by zackdreaver** [rathena/rathena#1653]
Mode: Renewal
Hash: 1c74af7b1fe04b6e66f34d252eda874985d3ee92

In rA you will get aspd penalty when Cavalier mastery isn't learned to level 5,
Even though I have level 5 dragon training.
Cavalier mastery should be only a prerequisite and not affecting aspd penalty.

RK stat: 60 agi and 120 dex
equipment: Any weapons with or w/o shield

Source: idRO and iRO exp.

**Comment by aleos89** [comment]
In accordance to this:
```
	if(pc_isriding(sd))
		base_status->aspd_rate -= 500-100*pc_checkskill(sd,KN_CAVALIERMASTERY);
	else if(pc_isridingdragon(sd))
		base_status->aspd_rate -= 250-50*pc_checkskill(sd,RK_DRAGONTRAINING);
```
Cavalier Mastery has no effect on players who are riding a Dragon.

**Comment by aleos89** [comment]
Here's the step I took to try and test this issue on hash 481a730 in renewal mode:
1) I leveled up as many skills as I could to enter into the RK branch; In the end I had to get level 3 Cavalier
2) I then put a skill point into Dragon Training
3) I mounted a Dragon and my ASPD became 124
4) I put another point into Dragon Training making it level 2 and my ASPD became 132
5) Then I went to Cavalier and put another point making it level 4 and my ASPD didn't change

I would say this is working as intended.
