### ISSUE TITLE
Client with packetver 20110225 is broken

### ISSUE THREAD

**Issue by Temtaime** [rathena/rathena#1657]
Just upgraded from eathena and when i equip something client hangs and then disconnects, server shows random invalid packets ids.

**Comment by aleos89** [comment]
Can you please provide more information. This is very vague.

Your rAthena hash is the first helpful bit of information. Also any screen shots or text output from the console. Are you using pre-renewal or renewal mode? The more information, the better.

**Comment by Temtaime** [comment]
Pre-renewal, eathena revision was 15085, git hash f4f4367c522825735f7f3dc6f1ddb7a409ef6444

**Comment by aleos89** [comment]
Keep in mind the client version you are using is not supported by rAthena. The only 2011 clients are 2011-10-05aRagexeRE and 2011-11-02aRagexe.

**Comment by Lemongrass3110** [comment]
src/config/core.h:
```
/// Comment to disable the official packet obfuscation support.
/// When enabled, make sure there is value for 'packet_keys' of used packet version or
/// defined 'packet_keys_use' in db/[import/]packet_db.txt.
/// This requires PACKETVER 2011-08-17 or newer.
#define PACKET_OBFUSCATION
```
