### ISSUE TITLE
unit_remove_map: unexpected state when removing player...

### ISSUE THREAD

**Issue by mgksrt8** [rathena/rathena#1658]
[Debug]: unit_remove_map: unexpected state when removing player AID/CID:******_/**_***\* (active=1 connect_new=0 rewarp=0 changemap=0 debug_remove_map=1) from map=mid_camp (users=1). Previous call from unit.c:3107(unit_remove_map_pc), current call from unit.c:3107(unit_remove_map_pc). **Please report this!!!**

According to this message - reporting, thank you.

**Comment by aleos89** [comment]
If you can provide any more info on how this can be reproduced, that would be great. We have tons of reports but no ways to reproduce it. Thanks.

**Comment by cydh** [comment]
It happened to me when played with sc_config branch when I double force `status_change_end` for Cloaking.
