### ISSUE TITLE
Guild Title Position

### ISSUE THREAD

**Issue by ghul3** [rathena/rathena#1662]
The guild title position did not update on the character except guild master after being change the name and the title position for guild member. Log out and log in back or do simple `@refresh` commands will produce this bugs.
Tested on client 2015 11 04a.

**Comment by ghul3** [comment]
Git Hash: https://github.com/rathena/rathena/commit/e9c5dc6e167f15cbfb1b8b0f565e857806de2f78

**Comment by Lemongrass3110** [comment]
Everything works fine for me. Could you give us a step by step guide what you are doing so we are able to reproduce your issue?

**Comment by Lemongrass3110** [comment]
Everything works fine for me. Could you give us a step by step guide what you are doing so we are able to reproduce your issue?

**Comment by ghul3** [comment]
It's only happen for other guild member. If u change the title position into random position number and having it's own title, it's will not get update correctly after being doing map warp or a simple @refresh command. 

How to reproduce:
Create new guild. Invite player to guild which should be in the last position title in default. It's show correctly on guild windows but when doing simple @refresh command it's will show Position 2 title on the other character itself.

**Comment by ghul3** [comment]
![GitHub Logo](http://i67.tinypic.com/2m6nas1.jpg)
