### ISSUE TITLE
 Last cell's ability to Magnetic Earth is not working.

### ISSUE THREAD

**Issue by VXPlay** [rathena/rathena#1666]
Last cell's ability to Magnetic Earth (SA_LANDPROTECTOR) is not working. The following image:
http://prntscr.com/d0gy1p

**Comment by Akkarinage** [comment]
What skill is being used on top of Magnetic Earth? Some skills aren't blocked, and some aren't affected by the outside ring (the outside cells) of the skill.

More info in future please.

**Comment by Akkarinage** [comment]
If that skill is Lord of Vermilion, (which google translator says so.....) then this report is invalid.

http://irowiki.org/wiki/Magnetic_Earth
> The cells on the effect's rim do not block area spells due to their splashing nature.
