### ISSUE TITLE
Last cell's ability to Magnetic Earth (SA_LANDPROTECTOR) is not working.

### ISSUE THREAD

**Issue by VXPlay** [rathena/rathena#1667]
Last cell's ability to Magnetic Earth (SA_LANDPROTECTOR) is not working. The following image:

I tested Storm Gust skill (WZ_STORMGUST).

Usually works in the center:
http://prntscr.com/d0hh27

Last: cell's:
http://prntscr.com/d0hi2c

**Comment by VXPlay** [comment]
Replay add:

https://mega.nz/#!A59zjTxB!0ciZT_N5oj7UJrbfhorrtL7BWZa7CK-i4t_pbr5CWNA

**Comment by Akkarinage** [comment]
As i stated in #1666 Magnetic Earth doesn't block AoE skills on the outter cells.

**Comment by Playtester** [comment]
Magnetic Earth only stops from units being placed on it, it does not protect from damage from units that are placed outside of it.

**Comment by secretdataz** [comment]
This is an intended behavior.
