### ISSUE TITLE
Dragon Breath skill

### ISSUE THREAD

**Issue by julia40124009** [rathena/rathena#167]
link:
http://forums.irowiki.org/showpost.php?p=1165399&postcount=130
Dragon Breath in rAthena no support Archer_Skeleton_Card (bLongAtkRate)

In Twro seems support (Expert_Archer . Archer_Skeleton_Card)
Some people have the Kro Iro information?

**Comment by reigneil** [comment]
Additional info: revised formula 175/60 cap
http://irowiki.org/wiki/Dragon_Breath
Damage = [(CurrHP ÷ 50) + (MaxSP ÷ 4)] × (SkillLv × BaseLv ÷ 150) × (95 + DragonTraining_Lv × 5)% × (100 + Ranged Damage Modifers)% x (Elemental Modifiers)% x (100 - Target Racial Reduction Modifiers)%
