### ISSUE TITLE
packet_ver_flag & packet_ver_flag2: Required?

### ISSUE THREAD

**Issue by Akkarinage** [rathena/rathena#1671]
With my limited understanding of how pretty much anything works, i was wondering what these are for.

Doing a search on these in the source returns only the support for them to be defined, but do we still need them if we're stating the packet version in /db/packet_db.txt and the client date in /src/mmo.h ?

**Comment by Lemongrass3110** [comment]
Akkarin is a bad baby

**Comment by Akkarinage** [comment]
/src/map/clif.c:9992
`if( packet_ver < 5 || // reject really old client versions
	    (packet_ver <= 9 && (battle_config.packet_ver_flag & 1) == 0) || // older than 6sept04
	    (packet_ver > 9 && packet_ver <40 && (battle_config.packet_ver_flag & 1<<(packet_ver-9)) == 0) || // version not allowed
	    (packet_ver >= 40 && packet_ver <=72 && (battle_config.packet_ver_flag2 & 1<<(packet_ver-40)) == 0)		)`

Wouldn't a simpler if(connectingversion != packetversion) do exactly the same thing?

**Comment by Akkarinage** [comment]
Ties in with #2263

**Comment by Lemongrass3110** [comment]
Fixed in  f0ab8d2
