### ISSUE TITLE
Party Bug

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#1674]
**Mode:** Renewal.
**Client:** 2015-11-04.
**Latest version available on GitHub.**

Well, there is a bug in group system, I will try to explain how showing step by step with pictures.
1. Take 2 characters, A and B.
2. Create a party with the character A.
   http://imgur.com/iBLS1SE
3. Invite the character B to the party, but did not accept the invitation, instead, create a party with B.
   http://imgur.com/m0XUZ2c
4. Now, accept the invitation to join the party A.
   http://imgur.com/cFnqZdS

Result B does not display that is any party, and still appears in a standing, and A can not see B in the party.
http://imgur.com/AA3y8x3

**Comment by admkakaroto** [comment]
**Mode:** Renewal.
**Client:** 2015-11-04.
**Latest version available on github.**

**Comment by admkakaroto** [comment]
Sorry, update.

**Comment by Grantea** [comment]
This is really broken.

Mode: Pre-re
Client: 2015-11-04a
Hash: [6510d41](https://github.com/rathena/rathena/commit/6510d41)

I followed these steps:
- Character **A** creates a party called **party1**
- Character **A** invites Character **B** to **party1**
- Character **B** leaves the invite window open and creates a party called **party2** instead
- ~ Everything's good so far. Character **A** is in **party1** and Character **B** is in **party2**
- Character **B** accepts Character's  **A** invite to **party1**
- Character **B** is now in **party1** (what happened to **party2**? )
- Character **A** can't see Character **B** in **party1**
- Character **B** can see both in **party1**
- Character **B**  disconnects
- Character **B** comes back online
- Character **B** is not in a party anymore
- Character **B** attempts to create **party2** again
- Result of Character's **B** attempt: **party2** already exists

**Comment by Lemongrass3110** [comment]
If you want to find the broken parties you can look them up with this query:
```
select
	*
from `party`
left join `char`
on `party`.`leader_char` = `char`.`char_id`
where
	`char`.`char_id` is null
or
	`char`.`party_id` <> `party`.`party_id`
```
