### ISSUE TITLE
@mobinfo doesnt display correct info?

### ISSUE THREAD

**Issue by reigneil** [rathena/rathena#1675]
im using git: 8f3599b0
client: 2015_11_04aRagexe
@mobinfo it display reduce drop rate by half if you compare it to re/mob_db.txt
can anyone reproduce this issue?

**Comment by secretdataz** [comment]
Is the level gap between the mob you are trying to `@mi` too wide? Level gap with more than 16 level will have 50% drop rate penalty.

**Comment by reigneil** [comment]
@secretdataz
nevermind what i have reported... i found the culprit. it is corrupt repository... i tried to download fresh.
