### ISSUE TITLE
Incorrect slave (summon) monsters behavior

### ISSUE THREAD

**Issue by mgksrt8** [rathena/rathena#1676]
Mode: Pre-Renewal
Git Hash: Latest
Bug: Core
Issue:
According to rAthena monster behavior system of all slaves has incorect AI ( behavior ) in next situations:

Example: Knight of Abyss / Abysmal Knight has Khalitzburg slaves.
After Abysmal Knight got traped the slaves stop thinking and chasing. They stoped attack the target. The Abysmal Knight status changeing from Attack / Chase to Idle ( ???, maybe to nothing... ) and this monster with slaves losing their target.
The same situation with MVPs, other monster with slaves.

Source: ruRO ( Closed Official Russian Ragnarok Online, Pre-Renewal, from ruRO Game Master #05 ).
Check it please. This issue makes the monsters more abusive, expecially MVPs.
Thank you.

**Comment by Playtester** [comment]
Tested on official: Slaves will continue following their target if their master is trapped, however once they lose their target, they won't resume attacking until their master is free.

Will need to check how it works on rAthena.

**Comment by Playtester** [comment]
Hmm, generally the behavior seems to be correct on rAthena already, but I think the core difference is that on rAthena the slaves only get the master's target when the master attacks. On Aegis, the slaves get the target already when the master starts chasing.

So on rAthena, as long as you aren't actually attacked by the master, the slaves won't do anything.
