### ISSUE TITLE
Acid Demonstration vs VIT MVP

### ISSUE THREAD

**Issue by mgksrt8** [rathena/rathena#1677]
Mode: Pre-Renewal
Git Hash: Latest
Bug: Core
Issue:
kRO did a special balanced fix for prevent abusing MVP with high VIT with Acid Demonstration skill. For now, Creator in Pre-Renewal with Sniper in 2 can kill every MVP, for example Detaler, with high VIT so easy. The damage should be fixed.

Source: ruRO ( Closed Official Russian Ragnarok Online, Pre-Renewal, from ruRO Game Master #5 ). Thank you.

**Comment by Playtester** [comment]
The kRO balance fix set all the VIT of MVPs to 30.

This is already the case in rAthena:
1719,DETALE,Detale,Detardeurus,90,960000,0,291850,123304,3,4560,5548,66,59,100,90,*30*,136,140,56

It's already 30 for Detale.

You mean something else?

**Comment by Playtester** [comment]
If there are no further clarifications on this one I'm going to close it.
