### ISSUE TITLE
Change Quest State with Job Change quests

### ISSUE THREAD

**Issue by mgksrt8** [rathena/rathena#1678]
Mode: Pre-Renewal
Git Hash: Latest
Bug: Script
Issue:
Almost 90% of all quests has problem with script behavior:

[Error]: quest_add: Character 152548 already has quest 1005.
[Error]: quest_add: Character 152349 already has quest 1005.
[Error]: quest_add: Character 152598 already has quest 1008.
[Error]: quest_add: Character 152604 already has quest 1006.
[Error]: quest_update_status: Character 150925 doesn't have quest 18120.
[Error]: quest_update_status: Character 152536 doesn't have quest 4013.
[Error]: quest_update_status: Character 151825 doesn't have quest 4013.
[Error]: quest_update_status: Character 152616 doesn't have quest 1008.
[Error]: quest_update_status: Character 152622 doesn't have quest 1008.

And it's just a 0.1% of all quests. Thank you.

**Comment by mgksrt8** [comment]
More Info:
[Error]: quest_change: Character 151694 already has quest 8133.
[Debug]: Source (NPC): Kouji#ama at amatsu (189,166)
[Debug]: Function: changequest (2 parameters):
[Debug]: Data: number value=8132
[Debug]: Data: number value=8133

**Comment by Atemo** [comment]
>And it's just a 0.1% of all quests. Thank you.

Please post the others if any, thanks !

**Comment by Atemo** [comment]
- [ ] [Error]: quest_add: Character - already has quest 1005.
- [ ] [Error]: quest_add: Character - already has quest 1008.
- [ ] [Error]: quest_add: Character - already has quest 1006.
- [ ] [Error]: quest_update_status: Character - doesn't have quest 18120.
- [ ] [Error]: quest_update_status: Character - doesn't have quest 4013.
- [ ] [Error]: quest_update_status: Character - doesn't have quest 1008.
- [ ] [Error]: quest_change: Character - already has quest 8133.

**Comment by anacondaqq** [comment]
This issue related to: https://github.com/rathena/rathena/issues/1385
Please check my solution. You will do the same for all of these scripts like me. I talking about 1000+ matches in around 50 or 60 script files. @mgksrt8 totally right here, and i support his message about 90% of such errors in map-server on live project.

**Comment by Atemo** [comment]
Your solution prevents to get errors/warnings from (*)quest command indeed but it hide others issues. For example you will hide a missing quest ID breaking the "chain quest log".

**Comment by anacondaqq** [comment]
@Atemo any example of: 

> Your solution prevents to get errors/warnings from (*)quest command indeed but it hide others issues. For example you will hide a missing quest ID breaking the "chain quest log".

Which broken by my solution? I just wish to know it, and maybe i will resolve it. Can you if it is not hard for you tell me ANY example of code which broken by my code?

**Comment by Lemongrass3110** [comment]
@anacondaqq if we would have any example we would fix it. But not by putting a workaround for a error message in the server log into the npc code, since this is the only way we can get to know these issues.

**Comment by Atemo** [comment]
@anacondaqq Please breath. My comment doesn't deserve an aggressive reply. Please care.
>I just wish to know it, and maybe i will resolve it.

Thanks you but it's my job. I don't want to search a sample but you may check some commits about quest log in the last 2 years.

**Comment by Lemongrass3110** [comment]
@Atemo could you check if something is left in here and otherwise close this issue please?
Thanks a lot.

**Comment by Atemo** [comment]
The warning for the quest listed should be fixed
