### ISSUE TITLE
Siren's Voice blocks non-target AoE skills like Self Destruction, Ignition Break, Windmill and etc

### ISSUE THREAD

**Issue by Felleonel** [rathena/rathena#1680]
Mode: Renewal
Hash: 8e3da7f

Siren's Song (Maestro and Wanderer)  unable to attack or **target** the caster with skills, but **non-targeted** AoE stuff will still work. I don't know if currently that skill changed in official servers, so I would like to confirm that this is a bug or not.

**Comment by aleos89** [comment]
I've confirmed that this is intended behavior. I did find one small issue though about the traps not being avoided.
