### ISSUE TITLE
Old card album question

### ISSUE THREAD

**Issue by zackdreaver** [rathena/rathena#1681]
Mode: renewal

So, I've been playing iRO again recently, and notice something about oca on iRO and rA.
On iRO oca has chance of giving miniboss card such as deviling, angeling or ghostring.
In rA's item_cardalbum.txt there are no such cards.
Can't test myself due short of funds.
Source:
https://forums.warpportal.com/index.php?/topic/155964-oca-is-45m-right-now-time-to-open-it/

I've question regarding this, is the leaked db that rA developer have, has this miniboss cards added?

**Comment by Playtester** [comment]
No those cards don't drop from OCA by default.

As it's a script file, iRO staff could easily modify it to drop those cards, though.

**Comment by lucasoli** [comment]
JFYI, on bRO we have the same behavior.

I know that we have differences between each server but I've also found some information at Divine-Pride that confirms those drops from Oca. However, I don't know if it's reliable of not.

http://www.divine-pride.net/database/item/616/old-card-album

**Comment by reigneil** [comment]
afaik in pre-re you can get mini boss card from OCA... and MCA is not exist before.

**Comment by Atemo** [comment]
>afaik in pre-re you can get mini boss card from OCA...
On iro? I read on their forum it's a customization. I don't know on renewal.

**Comment by reigneil** [comment]
@Atemo
no pRO before it close...

**Comment by reigneil** [comment]
@Atemo
no pRO before it close...

**Comment by Jeybla** [comment]
OCA fRO (euRO) Video:
Owl Duke & Cat O' Nine Tail: https://youtu.be/WLteyGpTRWM?t=135
Arc Angeling: https://youtu.be/WLteyGpTRWM?t=197
Angeling: https://youtu.be/WLteyGpTRWM?t=276

**Comment by cydh** [comment]
OK guys, we're in process to confirm the OCA's contents.
in my AEGIS leak for 2013 (re) or older ep (pre-re), OCA contains no boss cards **somehow** in DP -kRO server- contains some boss cards.

**Comment by Akkarinage** [comment]
Does anyone have any newer sources of information, or anything they can use to confirm this on kRO?

The files I have also indicate that this is a per server customisation. If there's no further updates, i'll dismiss this issue.

**Comment by zackdreaver** [comment]
Not from official site, but I found this
http://www.inven.co.kr/board/powerbbs.php?come_idx=1951&l=2736
Last updated 2015.

No miniboss cards are listed there.
