### ISSUE TITLE
change(char)sex after unsaved job change

### ISSUE THREAD

**Issue by Grantea** [rathena/rathena#1684]
If you use the command `@changecharsex` with Kagerou or Oboro you'll get an eternal sprite error on your next login because these jobs don't have gender option.

Hash: [6510d41](https://github.com/rathena/rathena/commit/6510d41)

**Comment by Lemongrass3110** [comment]
The command gets passed on to the char-server which already has a gender switch for these jobs.
The real problem your report brought up is that the current job in the char table might not be the one which is currently set to the character on the map-server.
