### ISSUE TITLE
Dragon Breath crashes map server

### ISSUE THREAD

**Issue by Darkelfen** [rathena/rathena#1687]
Mode: Renewal.
Githash: https://github.com/rathena/rathena/commit/9f888077c1a91572eacd6a108f1d24e4bbb97a41
Client: 20151104

GDB data;
Program received signal SIGSEGV, Segmentation fault.
skill_castend_damage_id (flag=131073, tick=816093, skill_lv=10, skill_id=2008,
    bl=0xa6d16254, src=0xbfc1cd8) at skill.c:5074
5074                    if( tsc->data[SC_HIDING] )
(gdb)

And on skill.c:

	case RK_DRAGONBREATH_WATER:
	case RK_DRAGONBREATH:
		if( tsc->data[SC_HIDING] )
			clif_skill_nodamage(src,src,skill_id,skill_lv,1);
		else
			skill_attack(BF_WEAPON,src,src,bl,skill_id,skill_lv,tick,flag);
		break;

I've manually patched Rebellion Awakening pr.

**Comment by Playtester** [comment]
Yeah, it's bad coding. "tsc" is NULL in that function when there the target has no status change at all, so it always should check for tsc before accessing it.

NPC_SELFDESTRUCTION would also make the map server crash.

```	case RK_DRAGONBREATH_WATER:
	case RK_DRAGONBREATH:
		if( tsc->data[SC_HIDING] )
			clif_skill_nodamage(src,src,skill_id,skill_lv,1);
		else
			skill_attack(BF_WEAPON,src,src,bl,skill_id,skill_lv,tick,flag);
		break;

	case NPC_SELFDESTRUCTION:
		if( tsc->data[SC_HIDING] )
			break;```

Should be:
```	case RK_DRAGONBREATH_WATER:
	case RK_DRAGONBREATH:
		if(tsc && tsc->data[SC_HIDING])
			clif_skill_nodamage(src,src,skill_id,skill_lv,1);
		else
			skill_attack(BF_WEAPON,src,src,bl,skill_id,skill_lv,tick,flag);
		break;

	case NPC_SELFDESTRUCTION:
		if(tsc && tsc->data[SC_HIDING])
			break;```

**Comment by keitenai** [comment]
lol so this was the cause of the crashing.
thanks @Playtester
