### ISSUE TITLE
Crazy Vines isn't removing ground traps from Rangers

### ISSUE THREAD

**Issue by Felleonel** [rathena/rathena#1689]
According to the iROWiki in General Trap information:

> Traps can be removed by Ganbantein, Earth Drive and Crazy Vines.

Link: http://irowiki.org/wiki/Fire_Trap

Mode: Renewal
Hash: 8e3da7f

Thanks.

**Comment by lucasoli** [comment]
I have some friends that are playing with the biochemist job. I'm able to ask them to confirm this issue.

According to the general traps information found on [iROWiki's page](http://irowiki.org/wiki/Fire_Trap) we have this:
> General Trap information
> - ...
> - Traps can be removed by Ganbantein, Earth Drive and Crazy Vines.
> - ...

All those things are normally handle in [skill_unit_db.txt](https://github.com/rathena/rathena/blob/master/db/re/skill_unit_db.txt). However, some skills needs harcoded behaviors on source and honestly I don't know if those traps already have it or not.

As per skill_unit_db.txt we have this for Hunter & Ranger traps:
> - 115,0x90,    ,  0, 1,1000,enemy, 0x28006	//HT_SKIDTRAP
> - 116,0x93,    ,  0, 1,1000,enemy, 0x28006	//HT_LANDMINE
> - 117,0x91,    ,  0, 1,1000,enemy, 0x29006	//HT_ANKLESNARE
> - 118,0x94,    ,  0, 1,1000,enemy, 0x28006	//HT_SHOCKWAVE
> - 119,0x95,    ,  0, 1,1000,enemy, 0x28006	//HT_SANDMAN
> - 120,0x96,    ,  0, 1,1000,enemy, 0x28006	//HT_FLASHER
> - 121,0x97,    ,  0, 1,1000,enemy, 0x28006	//HT_FREEZINGTRAP
> - 122,0x8f,    ,  0, 1,1000,enemy, 0x8006	//HT_BLASTMINE
> - 123,0x98,    ,  0, 1,1000,enemy, 0x8006	//HT_CLAYMORETRAP
> - 125,0x99,    ,  0, 1,1000,all,   0x28040	//HT_TALKIEBOX
> - 2238,0xd8,    ,  0, 1,1000,enemy, 0x8006	//RA_ELECTRICSHOCKER
> - 2239,0xd9,    ,  0, 1,1000,enemy, 0x8006	//RA_CLUSTERBOMB
> - 2249,0xd2,    ,  0, 1,1000,enemy, 0x8022	//RA_MAGENTATRAP
> - 2250,0xd3,    ,  0, 1,1000,enemy, 0x8022	//RA_COBALTTRAP
> - 2251,0xd4,    ,  0, 1,1000,enemy, 0x8022	//RA_MAIZETRAP
> - 2252,0xd5,    ,  0, 1,1000,enemy, 0x8022	//RA_VERDURETRAP
> - 2253,0xd6,    ,  0, 1,1000,enemy, 0x8002	//RA_FIRINGTRAP
> - 2254,0xd7,    ,  0, 1,1000,enemy, 0x8002	//RA_ICEBOUNDTRAP

RA_FIRINGTRAP skill flags (0x8002):
> - 0x00002(UF_NOREITERATION)	Spell cannot be stacked
> - 0x08000(UF_REM_FIRERAIN)	Removed if be overlapped by RL_FIRE_RAIN

Note that all those traps are missing the 0x04000(UF_REM_CRAZYWEED) flag. I don't know but maybe all the trap units needs that fix.

If you want to fix by now you can just change from 0x8002 to 0xC002.

**Comment by Felleonel** [comment]
The same happens for Extreme Vacumm, as mentioned in #1522

**Comment by aleos89** [comment]
I did some more testing and this skill literally removes EVERY ground skill!
