### ISSUE TITLE
warning after compiling with VS 2013

### ISSUE THREAD

**Issue by ernestfegarido** [rathena/rathena#169]
Warning	1	warning C4996: 'gethostbyname': Use getaddrinfo() or GetAddrInfoW() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings	d:\program files (x86)\rathena\src\common\socket.c	1260	1	map-server
Warning	2	warning C4996: 'gethostbyname': Use getaddrinfo() or GetAddrInfoW() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings	d:\program files (x86)\rathena\src\common\socket.c	1411	1	map-server
Warning	3	warning C4996: 'inet_ntoa': Use inet_ntop() or InetNtop() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings	d:\program files (x86)\rathena\src\common\socket.c	1421	1	map-server
Warning	4	warning C4996: 'inet_addr': Use inet_pton() or InetPton() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings	d:\program files (x86)\rathena\src\common\socket.c	1427	1	map-server
Warning	5	warning C4996: 'gethostbyname': Use getaddrinfo() or GetAddrInfoW() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings	d:\program files (x86)\rathena\src\common\socket.c	1260	1	char-server
Warning	6	warning C4996: 'gethostbyname': Use getaddrinfo() or GetAddrInfoW() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings	d:\program files (x86)\rathena\src\common\socket.c	1411	1	char-server
Warning	7	warning C4996: 'inet_ntoa': Use inet_ntop() or InetNtop() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings	d:\program files (x86)\rathena\src\common\socket.c	1421	1	char-server
Warning	8	warning C4996: 'inet_addr': Use inet_pton() or InetPton() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings	d:\program files (x86)\rathena\src\common\socket.c	1427	1	char-server
Warning	9	warning C4996: 'gethostbyname': Use getaddrinfo() or GetAddrInfoW() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings	d:\program files (x86)\rathena\src\common\socket.c	1260	1	login-server
Warning	10	warning C4996: 'gethostbyname': Use getaddrinfo() or GetAddrInfoW() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings	d:\program files (x86)\rathena\src\common\socket.c	1411	1	login-server
Warning	11	warning C4996: 'inet_ntoa': Use inet_ntop() or InetNtop() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings	d:\program files (x86)\rathena\src\common\socket.c	1421	1	login-server
Warning	12	warning C4996: 'inet_addr': Use inet_pton() or InetPton() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings	d:\program files (x86)\rathena\src\common\socket.c	1427	1	login-server

**Comment by cydh** [comment]
I'm not using 2013 :(

(an excuse submitted)

**Comment by lighta** [comment]
that my be my mistake by removing some #include. I'll try to work on it
