### ISSUE TITLE
Feature Request: atcommand moveitem

### ISSUE THREAD

**Issue by MegamiNoBisho** [rathena/rathena#1690]
moves the item from one place to another
`@moveitem <item name/ID/all>,<current location of item>,<destined location>`
-1 =all items on specific storage
1=inventory
2=storage
3=cart
example: i want to move all items from inventory to cart
 
`@moveitem -1,1,3`

**Comment by Lemongrass3110** [comment]
You can discuss feature request on our board here:
https://rathena.org/board/forum/62-rathena-forum-suggestions-bugs/

GitHub should only be used for real issues.
