### ISSUE TITLE
Sura's Cursed Circle isn't preventing the target from using /sit

### ISSUE THREAD

**Issue by Felleonel** [rathena/rathena#1691]
The same doesn't happens with Monk's Root, which has a similar effect. I would like to confirm if this is a bug or not.

iROWiki:
> Creates an area around the caster where all enemies **cannot move** or attack...

Mode: Renewal
Hash: 6e97762 

Thanks.

**Comment by Playtester** [comment]
Strangely this is official behavior. You can still sit while being under this status effect on official servers too.
