### ISSUE TITLE
Casting Skill knockback when walking  

### ISSUE THREAD

**Issue by BringerxD** [rathena/rathena#1695]
I dont know if its a problem or not but i detected a knockback when the character walks and inmmediatly you cast or use a skill, the character backs to the last cell

Client using : 20120410

here is a video of the problem
https://www.youtube.com/watch?v=9jDozZF5f1Q&feature=youtu.be

**Comment by Playtester** [comment]
Technically this also happens on official servers but official servers don't display that you've been pulled back to the previous cell, instead they will show you casting the spell from the next cell, creating one-cell position lag.

To simulate official behavior the fixpos packet needs be removed in certain situation but I'm afraid it might create more position lag. Alternatively could also use my steptimer system for it, but it would be a more complex project I don't have time to look into right now...
