### ISSUE TITLE
HT_ANKLESNARE doesn't pushed like other traps

### ISSUE THREAD

**Issue by mgksrt8** [rathena/rathena#1698]
Git: https://github.com/rathena/rathena/commit/cbc365d0f2f02ebceece4b6de7d58c8fe487f88f

Mode: pre-re
Bug: skill_unit_db.txt

Other trap skills in PvM/PvP ( except WoE ) can be pushed by for example Arrow Snower.

Current skill_unit_db array:
117,0x91,    ,  0, 1,1000,enemy, 0x9006	//HT_ANKLESNARE

Should be:
117,0x91,    ,  0, 1,1000,enemy, 0x8006	//HT_ANKLESNARE

Check and confirm please.

**Comment by Playtester** [comment]
I've never heard of ankle snare being possible to knock back ever. Any source?

**Comment by mgksrt8** [comment]
Source for now only my GM from closed raggame and closed raggame. I have no more windows server, but I still have source of pre-renewal leaked 11.3 russian server. I can give it to use for pre-renewal purposes.

**Comment by anacondaqq** [comment]
For example: https://www.youtube.com/watch?v=bISTeYdhiXk

**Comment by Playtester** [comment]
Hmm, that video seems a bit fake. It says kRO for example but all the text that appears is actually Japanese. Also going by the boss monster skills, the footage must have been from way before 2009. MVPs don't have their new skills yet.
I'd feel more convinced if there was an old discussion about it on official forums.

**Comment by mgksrt8** [comment]
Please, stop checking on the Renewal and install 11.3 pre-renewal. Tons of people tell you that you wrong and your "investigation" fake. Omg, you, as authority dev. member died in my eyes.

**Comment by MrAntares** [comment]
I played for a while on pre-re and ankle snare was never pushable. Ofc it could have been bugged as well, but honestly, I have never seen anyone push ankle snare on iRo/kRo. Russian and other Asian servers use custom rules, so it might have happened there, but we don't follow customs.

And plz try to remain professional.

**Comment by Darkelfen** [comment]
Shouldn't be iRo classic a valid source for this?

**Comment by Playtester** [comment]
Yes, I'd accept iRO classic as source. I just don't have a hunter on it to check, so I have to ask around.

**Comment by Playtester** [comment]
Okay, tested this on iRO classic now thanks to a friend: Ankle Snare can't be knocked back, so report is invalid.
