### ISSUE TITLE
Compilation error with latest commit

### ISSUE THREAD

**Issue by AtomixRO** [rathena/rathena#170]
Updated with commit https://github.com/rathena/rathena/commit/070565621f58b3b17c88f75c356b3904dd988489

I first had to install yacc and then i'm getting the following error:

yacc  grammar.y
yacc: e - line 24 of "grammar.y", syntax error
%defines
^
<builtin>: recipe for target 'grammar.c' failed
make[1]: *** [grammar.c] Error 1
make[1]: Leaving directory '/home/niktout/nro/rathena/3rdparty/libconfig'
Makefile:57: recipe for target 'libconfig' failed

Any idea on how to fix this please ?

Edit: I've removed grammar.y and i can compile fine but my question, is this file really necessary to run the latest revision without any issue ?

**Comment by lighta** [comment]
K closing this as everything seem fine.
