### ISSUE TITLE
Monsters using chase skills

### ISSUE THREAD

**Issue by Playtester** [rathena/rathena#1700]
On official servers, monsters use their chase skills while chasing every 1000ms. The time starts counting when they start chasing, so it gets reset each time.

On rAthena, we check for chase skills every 10 steps instead.

(I assume the 1000ms intervals is actually for all skill checking of monsters.)

**Comment by mgksrt8** [comment]
Sorry, but maybe you mean 3 steps ( 10 was typo)? Is it in conf/battle/monster.conf ?

**Comment by Playtester** [comment]
It's actually 5 steps and it's a define in skill.c.
```/// Walk intervals at which chase-skills are attempted to be triggered.
/// If you change this, make sure it's an odd value (for icewall block behavior).
#define WALK_SKILL_INTERVAL 5```
So I guess right now monsters faster than 200ms/tile use skills too often and monster slower than 200ms/tile use skills too seldom.

**Comment by Playtester** [comment]
After detailed test:
1. Monsters check for IDLE, WALK and CHASE skills 1000ms after the last skill check.
2. When a monster uses any skill, it won't use an IDLE or WALK skill for 2000ms.

**Comment by Playtester** [comment]
Some update. The above is not fully correct. Did some more in-depth tests:

So on almost all states: Move, Moveitem, Walk, Chase, Follow -> Skill is checked every 1000ms.

On states: Attack, Angry -> Skill is checked every max(ADelay,AMotion)

If a monster has 100% on a Attack/Angry skill it will never do a normal attack.

Also interesting, a monster can't move for "AMotion" so if "AMotion" is larger than "ADelay" and there's a 100% skill, then the monster becomes immobile and will never get out of the Attack/Angry state until its target moves out of sight.

----------------------------------------------------------

Different topic but also noticed when testing:

When a monster has a skill that fulfills the conditions, it will try to cast it regardless of range, but if the skill fails because the target it too far, then it doesn't get a delay and next time it will try to cast it again. So even if it might have longer range skills further down the list, it will never use those unless the target it in range of its first skill (or the first skill's chance is below 100%).

That's the reason why Greatest General for example never uses Earth Spike at range 8-9 even though its range is 9. It will always try to cast Blind Attack instead of fail because its range is 7.

**Comment by Playtester** [comment]
One more update to this: If there's a trigger condition for a skill, this skill will be used at the next 1000ms interval instead of immediately. So on official servers there's a 0-999ms delay from the trigger to the skill usage. On rAthena it's currently instant.

**Comment by Playtester** [comment]
Could confirm against that skills are checked every 1000ms.

Even on Idle we have a small delay in rAthena. After a skill was used we don't process the monster's AI for ~200ms, making a monster use Idle skills every 1200ms at most.

Monsters also shouldn't randomly walk when they have used a skill until it decided to not use a skill. So with a 100% idle skill, the monster won't move randomly at all if there is a valid target (tried with TF_THROWSTONE).

**Comment by Playtester** [comment]
Measured how often Novus used NPC_COMBOATTACK 10 times:
1. 2 minutes 40 seconds
2. 2 minutes 30 seconds
3. 1 minutes 50 seconds

**Comment by Playtester** [comment]
Still want to check:
- Does a monster randomly walk randomly if its aDelay / aMotion is below 1 second?
- Does a monster only use attack skills when they are at 100% chance when the aDelay / aMotion is below 1 second?
- Does the one spell per second rule apply to offensive skills?

**Comment by Playtester** [comment]
Investigating Zombie again:
- When you escape after an attack of a Zombie in "Angry" state, it will use a follow-up angry skill (~4 in 30 times)
- When you escape after an attack of a Zombie in "Attack" state (after hitting it), it will never use a follow-up attack skill (0 in 100 times)

**Comment by Playtester** [comment]
Furthere tests:
- Icewall blocked monsters definitely drop target (lose angry mode)
- Angry skills are used if the previous action was a normal attack and aMotion time has passed, they reset the "attackabletime" (using aDelay)
- 100% Angry Skill: (Attack) --aMotion--> (Skill) --aDelay--> (Attack) --aMotion--> (Skill) --aDelay--> (Attack)
- Berserk skills replace the normal attack but are never used as first attack
- 100% Berserk Skill: (Attack) --aDelay--> (Skill) --aDelay--> (Skill) --aDelay--> (Skill) --aDelay--> (Skill)

**Comment by Playtester** [comment]
Todo:
- Monsters that are able to use an offensive Berserk on their target skill will not start chasing
- Check how Angry mode works when aMotion is higher than aDelay
