### ISSUE TITLE
some sql syntax error

### ISSUE THREAD

**Issue by adty3094** [rathena/rathena#1705]
when i run SQL syntax to database i have error at item_db, item_db2, item_db2_re, mob_db2, mob_db2_re, mob_skill_db2, and mob_skill_db2_re sql.
![item_db](https://cloud.githubusercontent.com/assets/6906597/20134710/05547be8-a69f-11e6-8894-d7875433bc1f.PNG)
![item_db2](https://cloud.githubusercontent.com/assets/6906597/20134711/0555d65a-a69f-11e6-90a1-280cce018742.PNG)
![item_db2_re](https://cloud.githubusercontent.com/assets/6906597/20134709/055318c0-a69f-11e6-8746-ed4b6f738315.PNG)
![mob_db2](https://cloud.githubusercontent.com/assets/6906597/20134713/055b95e0-a69f-11e6-9a4e-999ac3ff5dde.PNG)
![mob_db2_re](https://cloud.githubusercontent.com/assets/6906597/20134714/055e1234-a69f-11e6-8a1a-05422101bbd2.PNG)
![mob_skill_db2](https://cloud.githubusercontent.com/assets/6906597/20134712/055af82e-a69f-11e6-9b28-abb15cc5cf22.PNG)
![mob_skill_db2_re](https://cloud.githubusercontent.com/assets/6906597/20134715/057fee54-a69f-11e6-9971-c6f5cb3a75c5.PNG)

**Comment by anacondaqq** [comment]
I can reproduce it, and i can reproduce it for very long time. But the problem not really in rAthena, the problem in web interface which do not know how to properly convert symbols, or escape them. With simple `mysql -uroot -ppass db < my_db.sql` or with sypex dumper (php script) it's very easy to import any data. What about phpmyadmin, and sqladminer there are many issues related to `\' symbol` in item names. So, if summarize everything above: try to use console application and avoid phpmyadmin usage for your database.

**Comment by secretdataz** [comment]
Hmm, so this issue isn't related to rA.

**Comment by adty3094** [comment]
thx for the solution. i'll try it :D
