### ISSUE TITLE
[Feature request] bonus2 bSubDefMagicEle,e,x; 

### ISSUE THREAD

**Issue by Darkelfen** [rathena/rathena#1706]
Question.
Does bSubDefEle reduce both magic and physical? if so, please close this as it should be invalid.

+x% magic damage reduction from enemy with defense element e.

This is needed for kRo 2016 - 11 - 02 [new cards](http://www.divine-pride.net/forum/topic/29767/kro-update-2016-11-02).
- [Fire Golem](http://www.divine-pride.net/database/item/27029). 
- [Fire Sandman](http://www.divine-pride.net/database/item/27027).

**Comment by Lemongrass3110** [comment]
As far as I've seen it should reduce both, but did not confirm it yet.
One thing for sure though is that you can implemented it by using the bonus3 version of it and supply the battle flag accordingly:
```
bonus2 bSubEle,e,x;       		+x% damage reduction against attack element e
bonus3 bSubEle,e,x,bf;    		+x% damage reduction against attack element e with trigger criteria bf

* Trigger criteria (bf)
	BF_SHORT	= Trigger on melee attacks
	BF_LONG		= Trigger on ranged attacks
	(Default: BF_SHORT+BF_LONG)
   
	BF_WEAPON	= Trigger on weapon skills 
	BF_MAGIC	= Trigger on magic skills 
	BF_MISC		= Trigger on misc skills
	(Default: BF_WEAPON)
   
	BF_NORMAL	= Trigger on normal attacks
	BF_SKILL	= Trigger on skills
	(Default: BF_SKILL if type is BF_MISC or BF_MAGIC, BF_NORMAL if type is BF_WEAPON)
```

**Comment by reigneil** [comment]
base on the description of fire golem card it is the same concept of tatacho card.
bSubDefEle fits to that description... (note that it is not working on player)

**Comment by Darkelfen** [comment]
Yes, indeed that one is the fire version of tatacho, but I've got curious whether specific "magic" reduction should occur, but as @Lemongrass3110  stated and you confirmed, it should reduce both, which works for those 2 cards.

**Comment by cydh** [comment]
> base on the description of fire golem card it is the same concept of tatacho card.

if like Tatacho (`bSubDefEle`), then `bSubEle` is not the choice. `bSubEle` based on attack/skill element, while `bSubDefEle` works based on the attacker's defense element.

> Does bSubDefEle reduce both magic and physical? if so, please close this as it should be invalid.

yes, that bonus works for all attack types.

**Comment by cydh** [comment]
I will re-open this since there's separated bonus that reduce magic.
The name will be `bMagicSubDefEle` to make it consistent with `bAddEle` x `bMagicAddEle`
some items are confirmed with this bonus
