### ISSUE TITLE
Genetic HP/SP Increase potions (Small/Medium/Large) in WoE:TE

### ISSUE THREAD

**Issue by Darkelfen** [rathena/rathena#1713]
Hi guys, question, does anyone knows if Genetic's HP/SP Increase potions (Small/Medium/Large) works in WoE:TE?

Mode: Renewal.
Githash: Can't provide but it should be present in current.

If they aren'r supossed to work then those 2 SC_ should be added to status_disabled.txt
```
//Genetic HP/SP Potions
SC_PROMOTE_HEALTH_RESERCH,16
SC_ENERGY_DRINK_RESERCH,16
```

**Comment by Atemo** [comment]
On iRo the HP/SP Increase potions items can't be used inside the castles but the SC aren't disabled.
