### ISSUE TITLE
Pets

### ISSUE THREAD

**Issue by akabo123** [rathena/rathena#172]
Pets do not act the way they are supposed to.

They only attack/use skills when they are loyal, but they should be doing that without having to be loyal. 
For example, this is one of my custom pets:

1013,WOLF,Wolf,619,25109,0,537,80,60,50,50,200,20,500,150,0,0,5000,4000,3500,{ petskillattack "NPC_GROUNDATTACK",2,1000,2000; },{ bonus bDef,2; bonus bMdef,2; }

In my server it is set so the pet attacks when the master attacks/receives damage. So according to the script above, wolf should have a 50% chance of attacking the enemy and use NPC_GROUNDATTACK to a 10% chance, If loyal to a 20% chance. But Wolf only does these things ONLY if he is loyal, when I tested it out + he uses the skills 100% (all the time).

Also, disabling the following does nothing.
// 16. S_Performance		Special Performance. (Yes = 1, No = 0)
// 17. talk_convert_class	Disables pet talk (instead of talking they emote  with /!.)

**Comment by cydh** [comment]
tested, everything is working fine. u just need to understand some stuffs in
* db/pet_db.txt
* conf/battle/pet.conf
