### ISSUE TITLE
shadow chaser skill vs gtb

### ISSUE THREAD

**Issue by jamon18** [rathena/rathena#1721]
bloody lust vs gtb ? is debuff?
manhole vs rsx card ?
vellum katz vs shadow form ? --- http://forum.ragnarokeurope.com/ro/index.php?%2Ftopic%2F79166-bypassing-shadow-formation%2F ---- in idathena vellum katz  bypass shadow form!

**Comment by Playtester** [comment]
Officially GTB card only protects from debuff that come from magical sources.

Manhole vs. RSX Card, I'd assume protects you from the suck-in effect but not from the stop effect, as that's what happens with bosses, but didn't test.

And yeah I guess Vellum Damage should bypass shadow form as confirmed in the linked thread.

Not sure how any of these currently work in rAthena.

**Comment by aleos89** [comment]
Did some tests on Aegis:
Target wearing a GTB Card is still affected by Bloody Lust.
Target wearing a RSX Card is still affected by Manhole.
