### ISSUE TITLE
bonus2 bDropAddRace & bonus2 bDropAddClass there are bug!

### ISSUE THREAD

**Issue by whupdo** [rathena/rathena#1722]
bonus2 bDropAddRace & bonus2 bDropAddClass there are bug!

Repeated switching equipment effect base plus

**Comment by Lemongrass3110** [comment]
Could you possibly add a better description?
Please also provide your githash and client-date.
Thank you.

**Comment by lucasoli** [comment]
@Lemongrass3110 I think he's telling you that when he was playing he did lots of switchings with another equipments and by doing this the bonus effect was summed.

By saying 'switching' I think he meant change his equipments while doing / receiving damage to take some advantages.

Hope this helps you guys.

**Comment by aleos89** [comment]
```c
		+ sizeof(sd->dropaddrace)
		+ sizeof(sd->dropaddclass)
```
The block here shows that the two bonuses are zeroed every time `status_calc_pc_` is called which is every time a player removes or equips something.

So if the issue is how @lucasoli described, this issue is invalid.

**Comment by aleos89** [comment]
I did some further digging and found the cause of the problem.
