### ISSUE TITLE
PK Server Mode Invalid setting!

### ISSUE THREAD

**Issue by whupdo** [rathena/rathena#1724]
I said misc.conf pk_mode: 1 in the wild map will not open pk mode!

**Comment by Lemongrass3110** [comment]
Could you possibly add a better description?
I do not understand at all which problem you are facing nor on which maps you are having a problem on.
Please also provide your githash, client-date and tell us if you are using renewal or not.
Thank you.

**Comment by lucasoli** [comment]
@Lemongrass3110 In the battle/misc.conf there is an option to enable a pk mode in the server except by the town maps. He's telling us that this option is not working for him.

> // PK Server Mode.  Turns entire server pvp(excluding towns). Experience loss is doubled if killed by another player.
> // When players hunt monsters over 20 levels higher, they will receive 15% additional exp., and 25% chance of receiving more items. 
> // There is a nopvp.txt for setting up maps not to have pk on in this mode.  Novices cannot be attacked and cannot attack.
> // Normal pvp counter and rank display are disabled as well.
> // Note: If pk_mode is set to 2 instead of 1 (yes), players will receive a 
> //   manner penalty of 5 each time they kill another player (see manner_system 
> //   config to adjust how this will affect players)
> pk_mode: 0

@whupdo Did you setup the bellow options?

> // For PK Server Mode. Change this to define the minimum level players can start PK-ing
> pk_min_level: 55
> 
> // For PK Server Mode. It specifies the maximum level difference between
> // players to let them attack each other. 0 disables said limit.
> pk_level_range: 0

Hope it helps you both.

**Comment by secretdataz** [comment]
Just saying "x doesn't work" isn't helpful at all,

**Comment by keitenai** [comment]
@whupdo  is this what you are trying to say:

"You've set < misc.conf > < pk_mode: 1 >"
But you don't want to set PK ( pvpoff ) in "Wild Maps" ( Field Maps? ) ?

**Comment by Lemongrass3110** [comment]
Could this by any chance be related to #1736?

**Comment by Lemongrass3110** [comment]
No further input from the user within 14 days. Closing this.
