### ISSUE TITLE
Question of hideonnpc

### ISSUE THREAD

**Issue by kukuasir1** [rathena/rathena#1725]
when I try to convert the Aegis script to ra script
I found the Aegis's **disablenpc** script command is different with the
ra's one. it more like the **hideonnpc**, except don't trigger the **OnTouch**
and **OnTouch2** event
Is anyone can make a new script command (e.g: hideonnpc2)
can hide the npc and don't trigger the **OnTouch** and **OnTouch2** event

**Comment by Lemongrass3110** [comment]
I guess what you are looking for is also called disablenpc in Athena:
```
*disablenpc "<NPC object name>";
*enablenpc "<NPC object name>";

These two commands will disable and enable, respectively, an NPC object 
specified by name. The disabled NPC will disappear from sight and will no longer 
be triggerable in the normal way. It is not clear whether it will still be 
accessible through 'donpcevent' and other triggering commands, but it probably 
will be. You can disable even warp NPCs if you know their object names, which is 
an easy way to make a map only accessible through walking half the time. Then 
you 'enablenpc' them back.

You can also use these commands to create the illusion of an NPC switching 
between several locations, which is often better than actually moving the NPC -
create one NPC object with a visible and a hidden part to their name, make a few 
copies, and then disable all except one.
```

If these fit your use, please close the issue.

**Comment by kukuasir1** [comment]
I know disablenpc and hideonnpc command, I mean they are different with Aegis.
```
Aegis
	disablenpc: hide the npc
				show the EF_BASH effect
				can do the ShowEffect(like specialeffect) script
				can't trigger OnTouch and OnTouch2 event
				can do the event with cmdothernpc
				can do the OnMyMobDead event
				
ra
	disablenpc: make the npc invisible
				don't show the EF_BASH effect
				can't do the specialeffect script
				trigger OnTouch and OnTouch_ event
				can do the event with cmdothernpc, donpcevent or doevent
				can't do the OnMyMobDead event
				
	hideonnpc:	hide the npc
				show the EF_BASH effect
				can do the specialeffect script
				trigger OnTouch and OnTouch2 event
				can do the event with cmdothernpc, donpcevent or doevent
				can do the OnMyMobDead event
```

**Comment by aleos89** [comment]
The special effects don't work because, I'm assuming really, that the `clif_specialeffect` packet doesn't work with OPTION_INVISIBLE. The OnMyMobDead event is an easy fix though on our side.

**Comment by Atemo** [comment]
I can't see disabled npc on aegis with box on sunlight. Seems like :
Aegis
    disablenpc: ~~hide the npc~~ make the npc invisible

**Comment by kukuasir1** [comment]
I think the hideonnpc is not necessary to trigger OnTouch and OnTouch_ event.
if u want a hide npc can trigger OnTouch and OnTouch_, You can make npc with sprite id -1(can't do specialeffect) or HIDDEN_WARP_NPC(can do specialeffect).

make hideonnpc don't trigger OnTouch and OnTouch_, the hideonnpc is almost the same with the Aegis's disablenpc script command.

**Comment by kukuasir1** [comment]
Maybe I need a script command to enable OnTouch and disable OnTOuch event

**Comment by Lemongrass3110** [comment]
@Atemo are we still missing a feature here or was this fixed with the latest ontouch changes etc?
If yes, please close this.

**Comment by Atemo** [comment]
Nothing has been changed for disablenpc and hideonnpc command on rAthena, however the command cloakonnpc introduced in https://github.com/rathena/rathena/commit/de80c5aab61eff6996a5e4c94d4a5a868eb18ca4 should fit what he expected
```
ra
    cloaonnpc : make the npc invisible
                show the EF_BASH effect
                can do the ShowEffect(like specialeffect) script
                can't trigger OnTouch and OnTouch2 event
                can do the event with cmdothernpc, donpcevent or doevent
                can do the OnMyMobDead event
```
