### ISSUE TITLE
Amulet (usable item)

### ISSUE THREAD

**Issue by MrAntares** [rathena/rathena#173]
Looks like the script is missing for this item. (This is an ages old thing)

It should summon random undead monsters (weak?), somewhat like dead branch.

Item id is 609

http://forums.warpportal.com/index.php?/topic/142777-amulet/
http://forums.roempire.com/showthread.php?t=7062

**Comment by MrAntares** [comment]
So how about us? Will we leave it to be useless?

**Comment by Playtester** [comment]
Well I always thought we are based on kRO. And it's not hard for server-owner to add that effect themselves, just look how it was done for Dead Branches.
