### ISSUE TITLE
Error upon running runserver.bat

### ISSUE THREAD

**Issue by vicros92** [rathena/rathena#1731]
Hi. I just recently started using rAthena to try and setup an offline private server for a test run, and following the instructions from the wiki as well as from the rAthena forum (https://rathena.org/board/topic/104452-tutorial-how-to-create-ragnarok-offline-2015-client/?page=1), I ran into a problem.

When I ran the runserver.bat, all 3 servers showed an error (picture included): 
[SQL]: Access denied for user 'ragnarok'@'localhost' (using password=YES)
[Error]: Couldn't connect with uname='ragnarok', passwd='ragnarok', host='127.0.0.1', port='3306', database='ragnarok'
![error](https://cloud.githubusercontent.com/assets/23609587/20460923/f917e4fa-af2c-11e6-8666-ca8cef0effc4.png)

How should I proceed? Any help would be appreciated. Thanks in advance.

**Comment by secretdataz** [comment]
This should be posted in our forums instead of issue tracker.
