### ISSUE TITLE
About SA_LANDPROTECTOR effects!

### ISSUE THREAD

**Issue by whupdo** [rathena/rathena#1735]
SA_LANDPROTECTOR special effects into only one small cell!

http://i.imgur.com/70H0h1a.jpg

**Comment by Hope8888** [comment]
same issue for me

hash:https://github.com/rathena/rathena/commit/633a642e5a37f10441477cf043c6c19e71e34297
mode:re
client:20151029

**Comment by Playtester** [comment]
Confirmed, but it's only bugged in renewal for some reason.
Bug is not client related, must be a server-sided issue.
