### ISSUE TITLE
Pre-Renewal 1st Job Change Quest Errors

### ISSUE THREAD

**Issue by dragonis1701** [rathena/rathena#1737]
In three job change quests: Acolyte, Mage, and Merchant, the game chooses between several different quests to give to the player, which works fine, but when it comes to completing the quests, it will spit out an error to the console because of the way it is coded.

```
		if(checkquest(1005) != -1) {
			completequest 1005;
		}
		else if(checkquest(1006) != -1) {
			completequest 1006;
		}
		else if(checkquest(1007) != -1) {
			completequest 1007;
		}
		else {
			completequest 1008;
		}
```

This code is from the mage job change quest. If the player has received any quest, other than 1008, the console will spit out an error because the script tries to complete a quest the player does not have. This only occurs in the three aforementioned job change quests.

**Comment by Atemo** [comment]
>If the player has received any quest, other than 1008, the console will spit out an error because the script tries to complete a quest the player does not have.

I don't understand the logic here. Can you reformulate ?

**Comment by dragonis1701** [comment]
Let's say you have quest 1006. It will check if you have 1005 and the check will fail, thus skipping that portion of code. It will then check if you have 1006 and the check will succeed, thus completing the quest. Then it will check if the player has 1007 and it'll repeat the part at 1005. Then it will run the completequest 1008 line and spit out an error that the player does not have quest 1008.

**Comment by Playtester** [comment]
That can't be.

What you describe would be rather an indication that `!= -1` is always false, so it will always go into the else and if you don't have quest 1008, it will give an error.

**Comment by Atemo** [comment]
>Then it will check if the player has 1007 and it'll repeat the part at 1005. Then it will run the completequest 1008 line and spit out an error that the player does not have quest 1008.

This part is skipped when the condition is true.
However a warning may appears when player exchange solution without asking for the requirements.
