### ISSUE TITLE
About rentitem!

### ISSUE THREAD

**Issue by whupdo** [rathena/rathena#1745]
On rentitem this directive
Suppose I create an item rentitem 601,60;
If the role of re-login will be washed version of the situation
http://i.imgur.com/FmjPgxs.jpg
http://i.imgur.com/JkfQpfK.jpg

Current hash: https://github.com/rathena/rathena/commit/9b1b7b1a2b7a83f9789506f879d58f6d0a91b761
Client: 20151104

**Comment by whupdo** [comment]
Can solve this problem? Can tell me how to amend? thank!

**Comment by aleos89** [comment]
The `rentitem` script command does not support stackable items. You can find this information in the script_commands document.

```
This command can not be used to rent stackable items. Rental items cannot be 
dropped, traded, sold to NPCs, or placed in guild storage. (i.e. trade mask 75)
Note: 'delitem' in an NPC script can still remove rental items.
```

**Comment by whupdo** [comment]
I create the same non-stackable items will have such a situation and when the goods time sooner than the frequency of washing more serious

E.g

12767,Passion_FB_Hat_Box,Passion FB Hat Box,2,0,,0,,,,,0xFFFFFFFF,63,2,,,,,,{ /*getgroupitem(IG_Passion_FB_Hat_Box);*/ rentitem 5856,3600; },{},{}
http://i.imgur.com/wU8sWC6.jpg
