### ISSUE TITLE
2 things about item group

### ISSUE THREAD

**Issue by cydh** [rathena/rathena#1746]
These are some stuff from idRO when I opened the [Shining Blue Lucky Egg](https://pservero.com/db/rathena/index.php/item/23196-Shining_Blue_Lucky_Egg)

* [ ] The gained equipment is unidentified.
Can see in this SS below, when I got the items, those are unidentified names.
* [ ] Maybe add this mode
Makes the last 2 chars of char name become asterisk `*` (as optional config).

![screenshot_101](https://cloud.githubusercontent.com/assets/4016864/20621868/d3e4c34c-b332-11e6-853b-e993e538f049.png)

poke @Atemo, can you confirm something on iRO?

**Comment by aleos89** [comment]
If this holds true, then we need to set a flag for #1741 so those item groups we use in rA to remove hard coded groups aren't given as unidentified.

**Comment by Atemo** [comment]
>The gained equipment is unidentified.

I confirm. But I don't know if all the items in the group give unidentified equip.

**Comment by cydh** [comment]
@aleos89 I don't understand what u say. xD

@Atemo hmm just assume all are unidentified. lol (need to check at least for available item groups in current Aegis)

**Comment by cydh** [comment]
There are 2 option
1. Add new param `isIdentified` in item group list, the default is `0 = unidentified`
2. Add new param for `getgroupitem` becomes `getgroupitem <group_id>{,identified{,<char_id>}}`. Default is `0`.

**Comment by secretdataz** [comment]
First one is more flexible imo

**Comment by Atemo** [comment]
It's not 'useful' (or logical?) to have one item identified and another unidentified in the same group. /me vote 2

**Comment by cydh** [comment]
1. so, just the `getgroupitem` is wrong, doesn't check `itemdb_isidentified` (but somehow the Costume will be identified by default)
2. config `broadcast_hide_name` ?
