### ISSUE TITLE
Warning pc_show_questinfo_sub

### ISSUE THREAD

**Issue by juanfus** [rathena/rathena#1749]
mode: pre renewal
git version : i dowloaded the git today and updated to this 
https://github.com/rathena/rathena/commit/82675d86d0838f6386dc686caadb33260b302617

![nuevowarning](https://cloud.githubusercontent.com/assets/12463722/20642688/f0754a72-b3eb-11e6-8977-685199baca81.jpg)

i only modified this
//quick option to disable all renewal option, used by ./configure
#define PRERE
#ifndef PRERE

**Comment by Lemongrass3110** [comment]
Sorry but I am unable to reproduce this. Also the variable `qi` is used in this function.
As you can see here:
https://travis-ci.org/rathena/rathena/jobs/179085172#L1199
The last warning in pc.c that is issued by clang is line 11485.

Please make sure you try it on a clean repository.

**Comment by juanfus** [comment]
i dowloaded again the pc.c and now it work maybe my file got corrupted, thank
