### ISSUE TITLE
Autotrade merchant not loading

### ISSUE THREAD

**Issue by Zeloss** [rathena/rathena#175]
When I restart the next warning is shown and the autotrade merchants are not loaded:
It's happening on Ubuntu 12.04
Commit: 9021cb6349

EDIT: I bought a VPS and the error it's not occurring with the same configuration

Error:

Memory manager: Memory leaks found at 2014/12/23 22h20m49s (Revision ).
0001 : vending.c line 620 size 193212 address 0x0xfd3c2f8
[Warning]: Memory manager: Memory leaks found and fixed.

**Comment by MrAntares** [comment]
I have Ubuntu as well, but it is working fine for me.
You have to use @mapexit to stop the mapserver properly. Otherwise this won't work. Are you sure you are stopping the server like this?

**Comment by anacondaqq** [comment]
same here, why are you closing it?

**Comment by cydh** [comment]
line 620? currently is
````
				while (SQL_SUCCESS == Sql_NextRow(mmysql_handle) && j < at->count) {
````
in which hash/rev ur emu is?

**Comment by anacondaqq** [comment]
Dear cydh, i dunno why, but sometimes when i close char-server -> table vendings/ flushed on the server start.

I dunno why, really... when it will be again,  iwill provide detailed logs from map/ char/ login servers, and mysql output

**Comment by Zeloss** [comment]
@anacondaqq I closed the issue because it's not happening in a VPS with the same emulator and the same configuration, it's happening only on a local server and probably it's a problem of my connection.
@cydh I don't have this problem actually using a VPS, when this happened I tested on differents versions of the emulator and this error ocurred on all the revs.

**Comment by anacondaqq** [comment]
@Zeloss https://github.com/rathena/rathena/issues/330
It's happened rarely. Not everytime. But only today i got output from map server.

**Comment by MrAntares** [comment]
I had many restarts and it always worked so far. Just use @mapexit with admin ingame to stop ste server before restarting....

**Comment by cydh** [comment]
well, just make new issue if something happen again
