### ISSUE TITLE
NPC Kellasus doesn't give again the Bioetics skill after getting Creator's job

### ISSUE THREAD

**Issue by Temtaime** [rathena/rathena#1752]
Suggest we were an alchemist and then became a creator. When we talk to he, he doesn't give the skill back.

**Comment by Lemongrass3110** [comment]
Is this possibly related to #1408?

**Comment by Temtaime** [comment]
Seems so.
Can't find an official behavior : is this skill is back when we get a creator or we should talk to the npc once more.

**Comment by Atemo** [comment]
Thanks.
