### ISSUE TITLE
Item Bonus Not Working

### ISSUE THREAD

**Issue by rofasindo** [rathena/rathena#1755]
**Mode:** Renewal
**Client:** 2015-11-04
**rA Ver.:** Latest Git.

Item bonus "AddMaxWeight" dosn't work, not increase max weight but on the previus rA ver. its work. this my custom item.

`50007,Holy_Orb_Nacles,Holy Orb Nacles,4,30000,,20,,0,,0,0xFFFFFFFE,63,2,136,,20,0,1,{ bonus bStr,2; bonus bAddMaxWeight,12000; },{},{}`

![screenrathena008_li](https://cloud.githubusercontent.com/assets/24239587/20695907/240f82e8-b622-11e6-969c-b8e356173260.jpg)
![screenrathena007_li](https://cloud.githubusercontent.com/assets/24239587/20695908/2416cb0c-b622-11e6-82b6-cbfcdfd02d90.jpg)

**Comment by aleos89** [comment]
Sorry, I completely forgot this report was open for this. This was fixed in c05808a. Thanks again!
