### ISSUE TITLE
Octopus Cave

### ISSUE THREAD

**Issue by gmsour** [rathena/rathena#1758]
No mobs spawned

**Comment by anacondaqq** [comment]
Hi, if you wish to fix the issue, please spend a few more minutes and provider better information about the issue like:

1. Your git hash
2. How reproduce
3. Do you have any custom source edits at your server?
4. If yes, have you tried to reproduce the bug on clean rAthena?
5. Optional: client date / packet version / server mechanic

This is important for developers to have exact the same emulator like you have, to reproduce the bug.

**Comment by Darkelfen** [comment]
I've got the same problem.

Mode: Renewal.
Githash: Approximately https://github.com/rathena/rathena/commit/561a874833ae0aac0301667447d144071ca76afc but maybe is present on current.
Client: 2015-11-04

As @gmsour reported when the instance is created no mobs are spawned.

**Comment by Atemo** [comment]
Thanks!
