### ISSUE TITLE
Cursed Spirit Quest (Wolfchev prerequisite) 

### ISSUE THREAD

**Issue by gmsour** [rathena/rathena#1759]
No dialog box appeared at lhz_in01,206,129

http://irowiki.org/wiki/Cursed_Spirit_Quest

> Head to the room on the far right, and walk towards the middle of the room (/navi lhz_in01 206/129). A dialogue box will appear and you will be taken back in time.

**Comment by Atemo** [comment]
I can't reproduce on c88ca4432d17ee3ca84ced78df79b5f7f94ffc09 I was able to continue the quest.
You probably miss a step !
