### ISSUE TITLE
Stealth Field effect on mobs

### ISSUE THREAD

**Issue by RagnarokNova** [rathena/rathena#176]
This skill is working just fine on players, but the status effects is not being applied on monsters.

**Comment by cydh** [comment]
which part og Stealth Field that doesn't work?
* _"Consumes 3% of the caster's Max SP every 3 seconds"_
* _"reduces movement speed by 30%, but the caster does not receive any effects."_

**Comment by RagnarokNova** [comment]
I believe it should be working on monsters as well.

**Comment by cydh** [comment]
and now idk what did u mean _"should be working on monsters as well"_
the effect when mobs around or the mobs cast the skills /swt

**Comment by RagnarokNova** [comment]
Sorry. I meant the effect should affect allied mobs, making them invisible as well when a mechanic with stealth field is around them.

**Comment by cydh** [comment]
the effect target was changed in 26afd769cea7b17bb5dd337488346ab4b82a4379 commit, from `all` to `friend`, for now we're rely the effect only for allies only.
you can change the effect yourself for now.
