### ISSUE TITLE
attachrid on player with running npc

### ISSUE THREAD

**Issue by Lemongrass3110** [rathena/rathena#1763]
Currently attachrid has no checks to see whether the target account id has a npc open at the moment or not.
This will end up in a real mess for the player getting attached.

**Comment by MysticFurur0RE** [comment]
s. . Q

**Comment by Lemongrass3110** [comment]
???

**Comment by Jeybla** [comment]
Attachrid just returns 0 if it doesn't work, is it?

So I'd recommend to alway check the return value of attachrid.

**Comment by Lemongrass3110** [comment]
Not working is currently only if the player is not online. Otherwise it always forces the attachment process.
Which is not always what you want. Or at least it was not for my usecase.
