### ISSUE TITLE
display_hallucination turn off no effect

### ISSUE THREAD

**Issue by hnomkeng** [rathena/rathena#1765]
// When affected with the "Hallucination" status effect, send the effect to client? (Note 1)
// NOTE: Set to 'no' if the client lags due to the "Wavy" screen effect.
display_hallucination: no

githash : c88ca44
client : 2015-09-16

**Comment by Playtester** [comment]
The 2015 client has a new, fixed hallucination effect that doesn't lag the client anymore.

**Comment by hnomkeng** [comment]
I want to close effect.

**Comment by Playtester** [comment]
Just remove the skill then? Apparently it's no longer possible to remove it just by setting the icon to blank. The effect is now hardcoded for the status change. If you don't want the effect, you can't tell the client that you have the status change. Easiest to accomplish this is to change the skills that give this status change to give a different status change instead (or none).

But that's a customization and not an issue, so I'll be closing this one.

**Comment by aleos89** [comment]
Or just use the diff provided by NEMO to disable the effect.

**Comment by hnomkeng** [comment]
@aleos89 no have Disable on NEMO.

**Comment by Lemongrass3110** [comment]
@hnomkeng did you reload your configuration by `@reloadbattleconf` or did you restart your server?
