### ISSUE TITLE
Autospell SO_CLOUD_KILL Bug

### ISSUE THREAD

**Issue by esu1214** [rathena/rathena#1766]
Mode: Renewal
When I write a item bonus like "bonus5 bAutoSpell,"SO_CLOUD_KILL",5,100,BF_MAGIC,1;"
The bug occoured that the skill SO_CLOUD_KILL will be trigged again and again each time the UNT attack the enemy.

**Comment by aleos89** [comment]
Should be resolved in #3127.

**Comment by aleos89** [comment]
Fixed in f3eab9d.
