### ISSUE TITLE
showdigit with high values and diffent timing

### ISSUE THREAD

**Issue by Weskercorp** [rathena/rathena#1769]
If you use, for example:
`showdigit 10,1;`
it will show
https://s16.postimg.org/7oqlfs6np/image.png
for 10 seconds, and then changes to zero
But if you change to
`showdigit 4294966,1;`
it will start at 01 right away.

Using:
`showdigit 10,2;`
It will show the same as before but it will not go at zero after 10 seconds, but it will stay that way, each second decount.

And:
`showdigit 10,3;`
It will decrease 2 times faster: 1 Tick/(Half Second)

Edit:
Hexed: 2015-11-04a
GIT: The Last One (2016/12/02)

**Comment by Lemongrass3110** [comment]
Well I totally agree with you that this is looking strange, but I have to point you at our documentation:
```
For type 1 and 2 the start value is set by using negative number of
the one intended to set (ex. -10 starts the counter at 10 seconds).
Except for type 3 the value is interpreted as seconds and formatted
as time in days, hours, minutes and seconds. Note, that the official
script command does not have the optional parameter.
```

So in your case you would want it to be -10 instead of 10 etc.

The only thing that I really could confirm was that type 3 really is 2 ticks per second.
