### ISSUE TITLE
Warning on Unit.c latest revision

### ISSUE THREAD

**Issue by RadianFord** [rathena/rathena#177]
unit.c: In function ‘unit_can_reach_bl’:
unit.c:2338: warning: array subscript is above array bounds
unit.c:2338: warning: array subscript is above array bounds

Revision '12666'

**Comment by Lemongrass3110** [comment]
When does this happen?

**Comment by RadianFord** [comment]
As far as i know this shows on the 12666 revision.

**Comment by Lemongrass3110** [comment]
Which OS? 32/64 bit?
Which tool + version is used for compiling?

**Comment by RadianFord** [comment]
I am using CentOS 6.6 and configure it with 64bit

**Comment by Lemongrass3110** [comment]
Could this be somehow related to this?

@cydh 
https://rathena.org/board/blog/23/entry-72-issue-for-ur-holidays-o/

**Comment by RadianFord** [comment]
@Lemongrass3110 No its not. the warnings show up on the revision of 12666. i am using an old one right now..

**Comment by cydh** [comment]
the `for` when use `dirx` and `diry` should use `ARRAYLENGTH(dirx)` or `ARRAYLENGTH(diry)`
but somehow the variable for `dirx` & `diry` can be wrapped by a struct such
````
struct s_direction {
    uint8 x, y;
};
static struct s_direction dir[] = {
    {0 , 1},
    {-1, 1},
    {-1 , 0},
    {-1 , -1},
    {0 , -1},
    {1 , -1},
    {1 , 0},
    {1 , 1},
};
````
so the array check in `for` in `unit_can_reach_bl` can be `ARRAYLENGTH(dir)`

**Comment by cydh** [comment]
errr, too much bullshit I wrote. lol

because the check is `i < 9` that means `0 ~ 8` that `8` is out-of-range for the dirx/diry len. 8 len means 0 ~ 7
