### ISSUE TITLE
Opening OBB / OPB / Gift Box

### ISSUE THREAD

**Issue by XombiexD** [rathena/rathena#1770]
When opening OBBs with a full inventory, it wont let me open unless I free up a slot. Its a hassle to do if you want to open a lot of OBB. Items should just naturally drop on the map if you have a full inventory.

**Comment by secretdataz** [comment]
I think it is working as intended.

**Comment by XombiexD** [comment]
i want to revert the setting so my players can still opening the boxs how ?
