### ISSUE TITLE
getvar script command causing mapcrash on Zeny variable

### ISSUE THREAD

**Issue by technoken** [rathena/rathena#1772]
I've been using this script `getvar(Zeny,.@char_id);` to check the zeny of player A using player B.

After I updated my hash from 8f3599b0e3c7b8ec95bfb4cf26a1a24c684919aa to fec4d7b0cff3ddf8a3a5f2dde0a21d6cff6a2f22 I have experienced the mapcrash.

I tried using different variable and it's working fine except the Zeny variable.

**Comment by Atemo** [comment]
I'm unable to reproduce.
However ```Zeny``` is a constant please use ```readparam``` instead.
https://github.com/rathena/rathena/blob/master/doc/script_commands.txt#L2321

**Comment by Lemongrass3110** [comment]
Confirmed this right now - though it has nothing to do with you updating your git version.
