### ISSUE TITLE
Request feature : noatk command

### ISSUE THREAD

**Issue by Temtaime** [rathena/rathena#1781]
So there's a feature : @noatk command.
It simply disables all attack possibility : weapon attack and skill use.
For example it can be used by gm when he observes the players in hide while woe is on.

**Comment by Atemo** [comment]
Please use the forum for request / support.

**Comment by Darkelfen** [comment]
Suggestion: if you are a GM and have access to command use` @mount2`, it will disable your attacks and skill usage.
