### ISSUE TITLE
lightning spear of ice

### ISSUE THREAD

**Issue by joelolopez** [rathena/rathena#1783]
lightning spear of ice should increase its damage while in Water Escape Technique thats skill description says in my english translation, whats the real behavior of this skill? if this is true  ,Water Escape Technique isnt boosting lightning spear of ice  damage ATM, 20151104 client, rathena = no label , all i know is this revision is the first release of clan system

**Comment by Playtester** [comment]
This only appears in the description but does not actually have any effect on official servers. So it's working as intended.
