### ISSUE TITLE
npc loading bug

### ISSUE THREAD

**Issue by anacondaqq** [rathena/rathena#179]
Hi, i wanna report about next bug, here is examle how reproduce it:

We have next file (for example) to load NPC:

npc: npc/path/npc1.txt
npc: npc/path2/baba.txt
npc: npc/path3/fadsfsdaf.txt
npc: npc/path/fajkfadjfajkfjk.txt

If for example file /npc/path2/baba.txt will be UNAVIABLE the rest files (npc/path3/fadsfsdaf.txt and npc: npc/path/fajkfadjfajkfjk.txt) WONT load.

**Comment by Akkarinage** [comment]
I can't reproduce this either, using abc78e51f7de938c881d45720da67e3fef3450a5 and renamed 5-6 filenames in the .conf's. The rest of the files listed after them were all loaded correctly.

**Comment by reigneil** [comment]
I also experience this... just like what @raynra said. If one of the file is missing or corrupt or bad script then next to it will not be loaded.

**Comment by aleos89** [comment]
@anacondaqq and @reigneil : Are you guys using Windows or Linux?

**Comment by anacondaqq** [comment]
linux (ubuntu 14.04)

**Comment by reigneil** [comment]
i'm using the ancient Windows... "XP SP3"

**Comment by SkittleNugget** [comment]
Happens to me on latest revision - windows 8

Took me quite a bit of time to realise why this was happening when I first encountered by making a typo on scripts custom and everything after that line didn't load.. never use to do this, has done for a while now though.

**Comment by Akkarinage** [comment]
Can we have an update on this please?

**Comment by aleos89** [comment]
This has to do with the check @lighta implemented a few months ago to check for invalid files/folders when loading NPC. It seems that this check depends on the environment that is used. For Windows 7 (when I was helping lighta) ran fine but all the documentation said it would be the same for all Windows.

It can temporarily be fixed by commenting out the "check_filepath()" function in npc.c.

**Comment by anacondaqq** [comment]
any updates about this?)
