### ISSUE TITLE
bMDefRatioAtk feature

### ISSUE THREAD

**Issue by MegamiNoBisho** [rathena/rathena#1790]
im not sure with my code can you check if im right?
![capture](https://cloud.githubusercontent.com/assets/22912274/21102968/695ea56a-c0bb-11e6-96dd-a1eb1eddda52.PNG)
![capturea](https://cloud.githubusercontent.com/assets/22912274/21102969/6962672c-c0bb-11e6-8484-b29da0126397.PNG)
![captureb](https://cloud.githubusercontent.com/assets/22912274/21102970/6968a3e4-c0bb-11e6-8fba-e4ae457f8440.PNG)
![capturec](https://cloud.githubusercontent.com/assets/22912274/21102971/696c7e4c-c0bb-11e6-9ed7-4055b8f62f8a.PNG)
![captured](https://cloud.githubusercontent.com/assets/22912274/21102972/6972e4f8-c0bb-11e6-932b-8fa15d52c711.PNG)
![capturee](https://cloud.githubusercontent.com/assets/22912274/21102973/6977066e-c0bb-11e6-8745-cf791ac3178f.PNG)

**Comment by Lemongrass3110** [comment]
Please use our board if you need help.
Thank you!
