### ISSUE TITLE
sleep2 and instances

### ISSUE THREAD

**Issue by Tokeiburu** [rathena/rathena#1791]
If an instance is destroyed and a sleep2 timer is still running, the remaining code will still be executed. This behavior doesn't apply for regular NPCs. For example:

```
prontera,156,188,3	script	pronte2	77,{
	instance_create("Endless Tower");
	end;
}

1@tower,0,0,0	script	#test_script	-1,{
	end;
OnInstanceInit:
	sleep2 3000;
	// Break your party before this can be called
	announce "This should not be called", 0;
	end;
}
```

It is caused by the following code, which ignores freeing/stopping the script on purpose (npc.c, npc_unload): 
```
		if (nd->src_id == 0) {
			if(nd->u.scr.script) {
				script_free_code(nd->u.scr.script);
				nd->u.scr.script = NULL;
			}
			if (nd->u.scr.label_list) {
				aFree(nd->u.scr.label_list);
				nd->u.scr.label_list = NULL;
				nd->u.scr.label_list_num = 0;
			}
		}
```

This never gets called: script_free_state, and... more specifically: delete_timer(st->sleep.timer, run_script_timer). This isn't limited to sleep2, any instance script keeps running when an NPC is unloaded, but it's easier to notice with sleep.

Git hash: fec4d7b0cff3ddf8a3a5f2dde0a21d6cff6a2f22 (although this issue has been there for quite some time now)

**Comment by Tokeiburu** [comment]
I would also like to add that the OnTimer triggers aren't stopped either with instances; so if you reload a script (while an instance is running), it will execute code that it isn't meant to be executed. You'll end up with errors such as:

```
[Error]: script:run_script_main:unknown command : 70464 @ 56
[Error]: script:run_script_main:unknown command : 70464 @ 56
[Error]: script:run_script_main:unknown command : 70464 @ 56
[Error]: script:run_script_main:unknown command : 70464 @ 56
[Error]: script:run_script_main:unknown command : 70464 @ 56
[Error]: script:run_script_main:unknown command : 70464 @ 56
[Error]: script:op_2: invalid data for operator C_LT
[Debug]: script_op2name: unexpected op=233992
[Debug]: Data: ???
[Debug]: script_op2name: unexpected op=-842150451
[Debug]: Data: ???
[Debug]: Source (NPC):  at 0011@tower (145,12)
[Error]: script:run_script_main:unknown command : 70464 @ 56
[Error]: script:op_2: invalid data for operator C_LT
[Debug]: script_op2name: unexpected op=233992
[Debug]: Data: ???
[Debug]: script_op2name: unexpected op=-842150451
[Debug]: Data: ???
[Debug]: Source (NPC):  at 0011@tower (133,16)
```

Although usually it's simply a map-server crash.

**Comment by vstumpf** [comment]
This also happens if a script is running while an instance is destroyed. For example, if a player has a message box open from an instanced npc and the instance is destroyed, upon hitting next, the map server crashes.

**Comment by aleos89** [comment]
It would be safe to assume that these timers should not exist if the NPC is unloaded from memory.

**Comment by Lemongrass3110** [comment]
@vstumpf if an instance is destroyed all players should be warped out. So I do not really know how to reproduce this.
