### ISSUE TITLE
Scripting guide links are broken.

### ISSUE THREAD

**Issue by Dragonnnn** [rathena/rathena#1794]
Looking to learn how to do npc scripting but it seems that the links are broken. https://github.com/rathena/rathena/wiki/scripting

**Comment by srhmike** [comment]
On the right side, you can select pages, and find it.  But on the main git wiki, it doesnt work for me either.

**Comment by Dragonnnn** [comment]
Upon viewing it, some documentations seems to be cut off. Thanks though!

Hopefully someone will fix it. I'd do it if only I know how to.

**Comment by Jeybla** [comment]
@Akkarinage you can use mine:
https://github.com/jeybla/rathena/wiki/scripting

Or use the small script I also mentioned in the forum:
```
git clone https://github.com/rathena/rathena.wiki.git wiki; cd wiki
find ./ -type f -iname "*.md" -exec sed -i -E "s|\(/([^\)]+)\s\"wikilink\"\)|\(\1\)|" {} \;
#git push
```

I also can offer my help in editing the wiki. Maybe rathena should give more members/friends edit rights in the wiki :)

**Comment by Akkarinage** [comment]
The wiki is a git repo so can be cloned and have PR's. Direct access requires write privileges, which also allows users to edit the rathena master branch.

**Comment by Jeybla** [comment]
Here we go:

Preview: https://github.com/Jeybla/rathena/wiki
Branch: https://github.com/Jeybla/rawiki/commits/FixLinks
