### ISSUE TITLE
Script hanging up

### ISSUE THREAD

**Issue by MrAntares** [rathena/rathena#1797]
Hi!

If I talk to an npc, but in the middle of the texts I wait for a few minutes (1~5) and then I click the next button to continue, the window simply closes and even the image of the npc remains on the screen. This happened to me with various vanilla npcs, for example with frostyfrost, the snowman in Luite.

Also, a while ago it was common that if I was in party with someone and that someone killed a mob anywhere in the game and I was talking to an npc, the next button just vanished from the dialog or the window just simply closed. This happened with Ripped Cabbus pretty frequently. Don't know if it was fixed. (Note: we use onmobkill script to announce MVP kills and give some event drops on some maps. Also, we have the custom hunting quest enabled which takes in account party kills and I think it also uses onmobkill. These might have to do something with this, or nothing. Just to let you know.) I'm not sure if this was fixed or not. The first issue is recent tho.

Mode: Renewal
GIT Hash: https://github.com/rathena/rathena/commit/79e9afaff03568175597573662f0df6897eeb873
Client: 2012-04-10 (+- 5 days, can't remember the exact day)

**Comment by secretdataz** [comment]
```
If I talk to an npc, but in the middle of the texts I wait for a few minutes (1~5) and then I click the next button to continue, the window simply closes and even the image of the npc remains on the screen. This happened to me with various vanilla npcs, for example with frostyfrost, the snowman in Luite.
```
I think this one is intended. (npc timeout feature)

**Comment by hurtsky** [comment]
https://github.com/rathena/rathena/issues/1763

**Comment by Lemongrass3110** [comment]
@hurtsky how is this one related to attachrid?

This "issue" comes from /src/config/secure.h which has a predefined value of 3 minutes.
Change it to whatever you like or comment the define as whole to disable it.
