### ISSUE TITLE
clan system updates!!

### ISSUE THREAD

**Issue by mrjnumber1** [rathena/rathena#1798]
** using client version 20151104a

clif_clan_basicinfo doesnt seem to care about the length? it probably just uses a static length of however long that buffer will be.i say this because the first value expected is rather a DWORD of the clan id, rather than a WORD containing the packet length. it's strange because looking at the disassembly it seems like it does take in that first dword at buf+4 .. i dunno it's weird!

`@ send 98a L2 S24"sword bros" S24"leader man" S16"prt_castle.gat" B1 B0 S24"wizards" ` will give me the expected output https://i.imgur.com/ya2u9u8.png i assume it populates the ally box as many times as the ally count byte is read and the same for enemy count byte, and the rest is discarded. but i can't confirm this right now.

i feel the clan table should store (and load on the servers) the sc numerically for each clan, so it knows what status to give to players when calling clan_member_joined.  ex `sc_start2(bl,bl,clan->sc_type, 100, 0, clan->id, -1)`. 

just wanted to report here so yeah hope the info drop helps

edit: lol... wow apparently i should have used the npcs to investigate, im very dumb forgive me.

however i still dont like that every player is going to store their clan as a status effect in addition to their clan_id in the status table, seems very wrong.

**Comment by Lemongrass3110** [comment]
This is how gravity implemented things. There is nothing we can change about it.
Additionally you want to get the correct effect icon and status changes so I do not really get what's the problem behind all this.

As for the packet length issue:
```
struct PACKET_ZC_CLANINFO {
  /* this+0x0 */ short PacketType
  /* this+0x2 */ short PacketLength
  /* this+0x4 */ int EmblemNum
  /* this+0x8 */ char[0x18] ClanName
  /* this+0x20 */ char[0x18] Mastername
  /* this+0x38 */ char[0x10] ManageMap
  /* this+0x48 */ unsigned char Num_AllyClan
  /* this+0x49 */ unsigned char Num_HostileClan
}
```
If the client ignores the length field and calculates it based on those alliance counts that's fine by me, but I do not think we should change anything here.

Do you mind sending me a PM on our board or in discord so we can discuss a few other things?

**Comment by mrjnumber1** [comment]
it's not that it's ignoring that packet length field - it's that for some reason it wants what's at buf+0x2 to be a dword containing the clan id, otherwise you'll get errors about illust_clan(96 <<16 | clan_id)
