### ISSUE TITLE
Serverwide variables + query_sql

### ISSUE THREAD

**Issue by Lemongrass3110** [rathena/rathena#180]
Hey guys,

today I found a problem when I was trying to write a warper NPC. Everything worked fine as long as I pushed my data into NPC/character variables, but when I tried to use global ones I noticed that I cancels after row number 5(every time!).

Here is a sample script and the data required by it.
```
-	script	WarperInit	-1,{
	end;
	
OnInit:
	query_sql( "select `id`, `name`, `map`, `x`, `y` from `warper_towns` order by `name` ASC;", $townids, $towns$, $townmaps$, $townx, $towny );
	
	debugmes( "arraysize: " + getarraysize( $townids ) );
	
	for( set .@i, 0; .@i < getarraysize( $townids ); set .@i, .@i + 1 ){
		debugmes( "townid: " + $townids[.@i] );
	}
}
```

Data:
```
6	Alberta	alberta	116	55
8	Aldebaran	aldebaran	140	124
11	Amatsu	amatsu	198	84
16	Ayothaya	ayothaya	150	68
27	Brasilis	brasilis	195	214
35	Comodo	comodo	209	143
30	Dewata	dewata	200	179
33	Eclage	eclage	107	36
19	Einbech	einbech	178	128
17	Einbroch	einbroch	238	200
28	El Dicastes	dicastes01	197	191
4	Geffen	geffen	119	39
```

![preview](https://cloud.githubusercontent.com/assets/3517879/5561258/89613a32-8dcb-11e4-8cc8-0d15612abf78.PNG)

The message "Found 34 rows" is a debug message I added locally to query_sql. I added this line before the data loop:
```
ShowDebug( "Found %u rows.\n", Sql_NumRows(handle) );
```

**Comment by cydh** [comment]
and let's say the map-server is closed, all records are stored completely or not?

**Comment by cydh** [comment]
and then, it's more weird for me. xD
it only give me 1 result (I have 41 records)

**Comment by cydh** [comment]
well, idk the best solution, but this is working https://gist.github.com/cydh/520329dff6a9b7c3015d
![screenshot_15](https://cloud.githubusercontent.com/assets/4016864/5601035/2b89ca62-931d-11e4-906c-4c934189a207.png)

![screenshot_16](https://cloud.githubusercontent.com/assets/4016864/5601047/80c2fb98-931d-11e4-9b04-f8de8798b28f.png)

_another solution maybe_, change the way `mapreg_setreg` to stores the reg. Don't `INSERT...` new value there, but just save them in memory first, and use `INSERT...` for new reg in `script_save_mapreg`

**Comment by cydh** [comment]
then? -.-a
