### ISSUE TITLE
<iteml></iteml> Can this function be turned off?

### ISSUE THREAD

**Issue by whupdo** [rathena/rathena#1802]
<iteml></iteml> Can this function be turned off?

http://i.imgur.com/qzJVB1I.jpg

**Comment by CairoLee** [comment]
Item Link is a client feature, it can't be turn off.
Or, you can use the older client before 2015, the older client no have Item Link feature.

**Comment by Lemongrass3110** [comment]
As CairoLee said this is a clientside issue and not a serverside one.
