### ISSUE TITLE
nullpo in pc_readparam

### ISSUE THREAD

**Issue by Darkelfen** [rathena/rathena#1804]
Mode: renewal
Githash: https://github.com/rathena/rathena/commit/7df9962a72cc51d826e01d3ff0265069da62ac17
Client: 20151104

My map server is crashing out of the blue. I've run GDB and these are the results:

GDB info:
```
--- nullpo info --------------------------------------------
pc.c:7859: in func `pc_readparam'
--- nullpo info --------------------------------------------
pc.c:7859: in func `pc_readparam'
--- nullpo info --------------------------------------------
pc.c:7859: in func `pc_readparam'
Program received signal SIGINT, Interrupt.
```
https://github.com/rathena/rathena/blob/master/src/map/pc.c#L7860

**Comment by Lemongrass3110** [comment]
Did you apply 7df9962 for sure? If you are on the hash just before that one your issue would make sense, but like this it doesnt... At least to me.

**Comment by Darkelfen** [comment]
I've patched and it said it was applied, but checking manually it wasn't there, I've did the changed manually and GDB throws no errors so far.

This is invalid then.
