### ISSUE TITLE
No dump is generated, How do I know the reason for the crash?

### ISSUE THREAD

**Issue by whupdo** [rathena/rathena#1806]
No dump is generated, How do I know the reason for the crash?
http://i.imgur.com/ikmjuNB.png

**Comment by anacondaqq** [comment]
recompile with gdb
then:

```
gdb map-server
press r
wait for crash
gdb will show output of crash with details
your server will not disconect anybody, but the server will be totally frozen (it's like crash, until you will exit from gdb)
```

**Comment by whupdo** [comment]
@anacondaqq
Will gdb Windows system can be used?
Can you give me some relevant teaching articles
Thank you!

**Comment by Lemongrass3110** [comment]
Does it crash randomly or does it crash instantly?
You could run it in visual studio in debug mode to see where it crashes.
