### ISSUE TITLE
@marry doesn't work with all char names

### ISSUE THREAD

**Issue by Tokeiburu** [rathena/rathena#1809]
The atcommand marry currently uses "%23s" instead of "%23[^\n]", making character names with spaces not work.

git a4a6dd896fc39b7d7ac3c160e486847a94f3cf6f

**Comment by Lemongrass3110** [comment]
Actually found another "issue" while trying this:
Since the atcommand does not require users to be on the same map(like the npc), it is not sufficient to display the wedding effect only on one of the two players.
