### ISSUE TITLE
@mute and partial names

### ISSUE THREAD

**Issue by Tokeiburu** [rathena/rathena#1810]
The partial_name_scan feature has pros and cons. If you want to mute a player who just logged off, it will try to mute someone else instead. For instance, you have a player named `Sonic` and another player named `Sonic Red`, muting `Sonic` (assuming he logged off) will end up muting `Sonic Red` instead.

I'm aware this isn't an actual bug, it's what the feature is meant to do, but it's rather inconvenient for some atcommands (I've had to explain why a player was muted, when... it wasn't that player to begin with >.<).

This affects other commands such as marry/jail/jailfor/unjail/mute/unmute

I'd also like to mention that getcharid should most likely not use partial names either. You can't know if getcharid returned the actual player you were looking for unless you compare the name afterwards, since it also uses partial names.

(The feature is enabled by default in conf/battle/gm.conf)

**Comment by Lemongrass3110** [comment]
`@item` might be another good candidate 👍
