### ISSUE TITLE
NoKnockBack preventing Feint Bomb - Back Slide

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#1814]
The effect bonus **bNoKnockback,0;**
(Used by Brynhild 2383 for example)

Prevents the skill Feint Bomb back slide effect to be working properly.

related to:
https://github.com/rathena/rathena/issues/1227
https://github.com/rathena/rathena/issues/1483

rAthena revision 20087 _(as seen with tortoise SVN)_

**Comment by aleos89** [comment]
Confirmed on Aegis that I am able to backslide with Brynhild equipped.

**Comment by Everade** [comment]
@aleos89 
This fix does not seem to take effect.
Feint Bomb back slide still doesn't work.

Tested on rA GIT 03ffd99

**Comment by aleos89** [comment]
Try this 3d71160.

**Comment by Everade** [comment]
Worked, thank you!

But the same issue persists for the skill **Escape** from Shadow Chaser.
