### ISSUE TITLE
About itemID 22508

### ISSUE THREAD

**Issue by zackdreaver** [rathena/rathena#1820]
Mode: Renewal
Hash: d5357c3e9f91bdbad055bc77266a9563bede5f07

According kRO description
http://www.divine-pride.net/database/item/22508/kRO
This item will teleport you back to Eden Group,
but currently it will teleport you back to save point.
If we following iRO then it has the correct behavior.

Can someone test this item on kRO?

**Comment by srhmike** [comment]
Emblem only for Eden Group members. It is made to be easy to carry. 
Warps you back to your savepoint when used. 
Reuse waiting time: 120 minutes 
Weight : 0

**Comment by aleos89** [comment]
@zackdreaver is referring to:
> 낙원단의 일원임을 증명하는 단원 전용 증표. 휴대하기 편하게끔 제작되었다.
> 기능을 업그레이드하여 사용 시, 낙원단으로 되돌아갈 수 있게 되었다.
> 재사용 대기시간 : 20분
> 무게 : 0

**Comment by srhmike** [comment]
Oh I misread it, sorry about that, I misunderstood.

**Comment by secretdataz** [comment]
I'll test for the correct teleport position in kRO when it's up again. (It's currently down for maintenance)
