### ISSUE TITLE
bragis poem

### ISSUE THREAD

**Issue by Vexillio** [rathena/rathena#1824]
bragis poem and other songs should not  be able to dispelled by a sorce or prof and the count of bragi buff into a user should be fix to 21 seconds not when a player go inside the bragi the timer reset and it is overlapping.

**Comment by Playtester** [comment]
Hmm, can confirm that it's not possible to dispell songs on official servers even if the character has left the song area. Strange it hasn't been reported before.

The songs on rAthena are implement quite differently from official songs so it's not very easy to replicate the timer behavior. I won't fix that as I don't have the large amount of time needed for that.
