### ISSUE TITLE
Chase Walk/Stealth unhide behavior

### ISSUE THREAD

**Issue by zackdreaver** [rathena/rathena#1826]
Test Mode: Renewal
Hash: eb142883c268953dc89286625b4629e9440886c0
Test server: iRO and idRO

Currently on official server, Chase Walk has a cast time when stalker unhide himself.
On rAthena, chase walk has the same behavior as Hiding when stalker unhide himself.

Replay file from iRO:
[Stalker Stealth.zip](https://github.com/rathena/rathena/files/671933/Stalker.Stealth.zip)

additional note:
iirc prerenewal Chase walk has the same behavior too like renewal.

**Comment by Playtester** [comment]
You can't unhide yourself when in chase walk, it persists until your SP run out. How would you unhide?

**Comment by zackdreaver** [comment]
By pressing the skill shortcut of Chase Walk.
Have you check the replay file? you will find the differences between iRO and rA

**Comment by Playtester** [comment]
Hmm, I don't see a skill shortcut for Chase Walk. But what that video shows is not possible on official servers because Chase Walk has a delay of 60 seconds so you can't cast it again while in stealth. I checked on rAthena and the delay was 60 seconds there already.

**Comment by zackdreaver** [comment]
Wha, but it showing on me.
Alright, let me explain the behaviour then

iRO Chase Walk:
1 Press skill shortcut
2 Begin casting by spinning around
3 Hiding state
4 Press skill shortcut again
5 Begin casting by spinning around in hiding state
6 Unhide state

rA Chase Walk:
1 Press skill shortcut
2 Begin casting by spinning around
3 Hiding state
4 Press skill shortcut again
5 No casting, it quickly unhide your char like Hiding skill behaviour.

**Comment by Playtester** [comment]
Hmm, sorry I can't confirm this at all. The skill has a cooldown of 60 seconds if you click it again nothing happens, because the skill is on cooldown. You can not unhide. You only unhide if your SP runs out and that is definitely instant. We are talking about the Shadow Chaser skill, right?

```//-- SC_INVISIBILITY
2290,1000,1000,0,0,0,20000:30000:40000:50000:60000,-1```

As you can see the cooldown is so high that you will always run out of SP before the delay ends.

**Comment by Playtester** [comment]
Tested on iRO classic: No cast time. So apparently it's a renewal-only thing.

**Comment by zackdreaver** [comment]
Thanks for the fix
