### ISSUE TITLE
Help me about clearance skill...

### ISSUE THREAD

**Issue by saovarott159** [rathena/rathena#1830]
Hello.. help me

   How to modify clearance skill same as VDO on linke below
https://www.youtube.com/watch?v=HlGCCRxKkGc

Picture below in my server not work because is single target.
https://www.mx7.com/view2/zzvk3w3xyPqzmWkl

skill.c

`case AB_CLEARANCE:
		if( flag&1 || (i = skill_get_splash(skill_id, skill_lv)) < 1 )
		{ //As of the behavior in official server Clearance is just a super version of Dispell skill. [Jobbie]

//			if( bl->type != BL_MOB && battle_check_target(src,bl,BCT_PARTY) <= 0 ) // Only affect mob or party.
//				break;

			clif_skill_nodamage(src,bl,skill_id,skill_lv,1);

			if((dstsd && (dstsd->class_&MAPID_UPPERMASK) == MAPID_SOUL_LINKER) || rnd()%100 >= 60 + 8 * skill_lv) {
				if (sd)
					clif_skill_fail(sd,skill_id,USESKILL_FAIL_LEVEL,0);
				break;
			}
			
			if(status_isimmune(bl))
				break;`

`		case RK_PHANTOMTHRUST:
		case AB_CLEARANCE:
			if (target->type != BL_MOB && !map_flag_vs(src->m) && battle_check_target(src,target,BCT_PARTY) <= 0)
				return USESKILL_FAIL_MAX;
			inf |= BCT_PARTY;
			break;
	}

	if (inf && battle_check_target(src, target, inf) <= 0)
		return USESKILL_FAIL_LEVEL;
`

skill_db
`2052,11,8,1,0,0x1,0,5,1,yes,0,0x00400,0,magic,0,0x10020, AB_CLEARANCE,Clearance //CHECK Also shows this as a magic attack. Why?
`

rAthena SVN 17726
packet_db_ver: 30
2012-04-10aRagexeRE

**Comment by aleos89** [comment]
This is a bug tracker. Please use the forum for support on a customization.
