### ISSUE TITLE
Items suddenly disappearing

### ISSUE THREAD

**Issue by ryonzito** [rathena/rathena#184]
I have problem on my server. Some people are being dropped without giving any error and when they connect the last character connected without this item / zenny some in inventory. What's this?

**Comment by cydh** [comment]
let's say, ur server compiled & running for 2013-08-07 but u're using 2012-04-10 client :P

**Comment by Akkarinage** [comment]
@ryonzito - "latest rev" is not a GIT Hash. Please provide more information. Also, if you logout of a character that has no items/zeny and log back in, do they reappear? What's your client version, and what packerver have you got in mmo.h?

**Comment by aleos89** [comment]
It has been quite some time and no report back.
