### ISSUE TITLE
mob_db_re.sql

### ISSUE THREAD

**Issue by srhmike** [rathena/rathena#1842]
I updated today (12/30) Got sql query error.

Error
SQL query:
#REPLACE INTO `mob_db_re` VALUES (2058,'M_MIMIC','Mimic','Mimic',51,6120,182,0,0,1,800,950,10,40,44,121,1,60,75,110,10,12,1,0,60,0x120,100,972,500,288,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
#REPLACE INTO `mob_db_re` VALUES (2059,'M_DISGUISE','Disguise','Disguise',55,7543,180,0,0,2,526,693,18,29,0,72,45,35,48,65,10,12,1,6,82,0x120,147,516,768,384,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
#REPLACE INTO `mob_db_re` VALUES (2060,'M_ALICE','Alice','Alice',62,10000,221,0,0,1,700,850,5,5,64,64,42,85,100,130,10,12,1,7,60,0x120,200,502,1999,480,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0);
#REPLACE INTO `mob_db_re` VALUES (2061,'E_STAPO','Stapo','Stapo',23,666,0,299,199,1,135,370,90,5,12,11,15,12,23,1,10,12,0,0,42,0x83,300,936,792,432,0,0,0,0,0,0,0,909,1000,7312,1000,512,1000,7126,100,993,10,1821,3,7956,5000,0,0,0,0,4424,1);
#REPLACE INTO `mob_db_re` VALUES (2062,'E_POPORING','Poporing','poporing',14,344,0,73,40,1,59,72,0,10,1,14,14,0,19,15,10,12,1[...]

MySQL said: Documentation
#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'REPLACE INTO `mob_db_re` VALUES (2067,'E_ANOPHELES_','Anopheles','Anopheles',3,5' at line 10

**Comment by aleos89** [comment]
It may be dependent on your import tool. According to master as of now (396b5c3) the imports are just fine for mob_db_re (See [here](https://travis-ci.org/rathena/rathena/jobs/187773193#L157)).
