### ISSUE TITLE
Limited Sale Window not opening

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#1843]
_/limitedsale_ doesn't open the window.
However there's **no** message given out that the command was wrong, so that's a good thing.
Although other than that, nothing happens at all.

rAthena GIT **a9faab8**
Client used: **2015-09-16aRagexe**

Just a client oddity or what could it be?

**Comment by Lemongrass3110** [comment]
See #1825. it is not in master yet. On master the packet for it is mapped to dull(ignore).

**Comment by Everade** [comment]
ups, sry about that ^^
