### ISSUE TITLE
VIP - No Gemstone Requirement

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#1846]
rAthena Git: 396b5c3
Client used: 2015-09-16aRagexe
Renewal

_VIP has been activated_ in the source code, other features tested are working as expected.
// Gemstone requirement. Setting to false will disable.
// Can the VIP Group ignore Gemstone requirement for skills?
// Default: yes
vip_gemstone: yes

**I have tested both, yes and no on this setting, due the fact that the description is a little bit missleading.**

The No Gemstone Requirement does not take effect.

Tested with **Warlock T** - by using the skill - **Gravitational Field**

After the cast time, the skill fails with the message "Blue Gemstone required."

**Comment by Akkarinage** [comment]
Are there any other skills you've tested that this has no effect on? GF shouldn't be affected by Mistress Card which makes me think the flag is being ignored, as the flags used with VIP and Mistress Card are the same.

**Comment by Lemongrass3110** [comment]
We actually have quite a few checks that respect the VIP state(sd->special_state.no_gemstone == 2).
Probably this one was missed out?

**Comment by Everade** [comment]
No i haven't tested any other skills.
I also don't know how the official system works.

**Comment by Everade** [comment]
Just tested with Killing Cloud.
Mistress Card removes 1 out of the 2 Red Gemstone requirements.

The VIP System still requires both gemstones to be casted, so doesn't take any effect.

Also doesn't work for Elemental Shield
Flame Launcher also doesn't work
Dispell also doesn't work

**Comment by aleos89** [comment]
The reason is because the special_state values get reset on each `status_calc_pc` and it's not getting set back if the config and VIP are enabled.
