### ISSUE TITLE
Urgent: Low hp y sp in character

### ISSUE THREAD

**Issue by darknessfmy** [rathena/rathena#1853]
hp and sp have a bug in the last rev of rAthena:
![image](https://cloud.githubusercontent.com/assets/7623682/21664074/0a4c5b02-d2c3-11e6-9440-a8a860e2a956.png)

**Comment by Lemongrass3110** [comment]
With current master the maximum level of rebellion is 160.
Even in @aleos89 pull request #1692 you can not go any higher.
Make sure you supplied all the required hp and sp tables if you customize this.
