### ISSUE TITLE
setwall script command limits

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#1854]
```
OnInit:
	setwall "guild_vs2",46,85,8,6,0,"wall_a";
	setwall "guild_vs2",42,73,20,6,0,"wall_a2";
	setwall "guild_vs2",14,46,8,0,0,"wall_b";
	setwall "guild_vs2",26,59,20,0,0,"wall_b2";
	setwall "guild_vs2",85,46,8,0,0,"wall_c";
	setwall "guild_vs2",73,40,20,0,0,"wall_c2";
```

The ones with length set at **20** do not work / do not appear.
No error on the map server log.
The ones with a length of 6 work just fine.

The script documentation says nothing about a max length.

**Comment by Lemongrass3110** [comment]
`setwall "<map name>",<x>,<y>,<size>,<dir>,<shootable>,"<name>";`

Documentation also has no parameter length. If you are referring to `size` then you do not have a sample with length of 6, but rather with `dir` 6.
Could you make it a little clearer?

**Comment by Everade** [comment]
i meant those with 8 work, my mistake.

size 8 works
size 20 doesn't
