### ISSUE TITLE
dispbottom uses the Guild Chat Display option

### ISSUE THREAD

**Issue by Tokeiburu** [rathena/rathena#1855]
If you turn off the Guild Display Option (from the ingame chatbox), you will no longer receive the messages by the 0x17f packet. This is used by `clif_disp_message` and `clif_disp_onlyself`, and therefore affects dispbottom and duel messages.

I'm using the 20151029 client,
git a06028bb48385e32364fd309d068d52be5f43615

**Comment by aleos89** [comment]
The only solution then is to use `clif_colormes`.

**Comment by Lemongrass3110** [comment]
Of course with this fix you will also not see the messages if you filter the global messages on clientside.
So it made things better, but we cannot prevent all clientside possibilities to filter messages.
