### ISSUE TITLE
Biolab 4F slaves don't clear on master's death

### ISSUE THREAD

**Issue by raynra** [rathena/rathena#186]
When doing Biolabs 4F instance dungeon, MVP spawns slave mobs. When MVP is killed, slave mobs remain. Seems like a bug.

**Comment by cydh** [comment]
@_@
I have pending instance tests

**Comment by Akkarinage** [comment]
@raynra is this still ongoing?

**Comment by raynra** [comment]
I haven't updated to recent revisions of rA, so I am uncertain if this is still an issue.
I'll see if I can reproduce issue on latest git.

**Comment by cydh** [comment]
* 1 how to do the instance
* 2 can I bypass the sequence, I just want to test the instance spawn for the issue directly
* 3 I hate doing NPC/quest sequence

or can u accompany me on test server? xD

**Comment by raynra** [comment]
Hi Cydh,

I'll see if I can allow you to bypass the whole sequence and go straight to testing the instance spawn. :+1:

**Comment by cydh** [comment]
mkay.

**Comment by Lemongrass3110** [comment]
@cydh @raynra
Did you two get to test this? If yes what was the outcome?

**Comment by cydh** [comment]
he didn't give me a clue. But I tried some instances (even customs like ET just with 1 floor with 1 MVP with its slaves), MVP killed, slaves are killed/removed too. /hmm

**Comment by raynra** [comment]
Hi there. Sorry for the absence - away on travel and not much internet connectivity (yay, Asia).
I have not heard of any other reports of this bug, so I guess we can go ahead and close this out and reopen if I get future reports.
