### ISSUE TITLE
Adding support for the new doram skills

### ISSUE THREAD

**Issue by grass0916** [rathena/rathena#1865]
Excuse me.

For current version, still not support the latest Doram's skills? I don't see them in [skill.h](https://github.com/rathena/rathena/blob/master/src/map/skill.h).

![skill tree](https://camo.githubusercontent.com/505335ff716ee7bbd2594dba09618b5f97ae8f0c/68747470733a2f2f726f2e676e6a6f792e636f6d2e74772f6576656e742f32303137303130345f646f72616d2f696d672f736b696c6c547265652e706e67)

**Comment by Lemongrass3110** [comment]
No not all skills are supported yet.
Also the new baby classes are not supported yet.
