### ISSUE TITLE
setiteminfo no work 100%, need reloadscript...

### ISSUE THREAD

**Issue by Triedge** [rathena/rathena#1867]
I have a script that modifies the sales value of the objects.
It's something like ...

setiteminfo(501,0, 50000);

The problem is that it does not change the price of the sale of the item in normal stores.
prt_in,172,130,0	shop	Weapon Dealer#prt	54,1750:-1,1751:-1,1701:-1,1201:-1,1204:-1,1207:-1,1601:-1,1101:-1,1104:-1,1107:-1,1110:-1,1113:-1,1122:-1,1119:-1,1123:-1,1126:-1,1129:-1,1116:-1,1301:-1

The official price is maintained ...

To make the new price work, I need to use reloadscript.
Should not this work automatically?

**Comment by secretdataz** [comment]
Item selling/buying price is set at the time of NPC creation. This is working as intended.

**Comment by Triedge** [comment]
> setiteminfo(<item id>,<type>,<value>)
> 
> This function will set some value of an item.
> Returns the new value on success, or -1 on fail (item_id not found or invalid type).

I think the objective of setiteminfo is just to change the values of an object during the execution of the server.

Although the value change in the DB (verified with @ii 501) does indeed work, normal stores maintain the Default price.

And I need to use @reloadscript for stores to detect the new price.

**Comment by secretdataz** [comment]
The documentation never imply that `setiteminfo` will immediately take effect on everything that references the information in question.
We may reconsider about this again in C++ branch, or maybe as a plugin in the future.

**Comment by Triedge** [comment]
In fact all effects work instantly.
For example ... change the weight, and even the value of buy or sell are recorded instantly.
The only problem is that the Shops do not record these changes. I have even left the server active for 1 hour waiting for the change to be "registered", but it never happens.
The only "solution" is to use the reloadscript command.

**Comment by aleos89** [comment]
As @secretdataz stated and you have seen, it does update the item information. The reason the shop doesn't show this change is because the shop stores it's own values for that item, as you can see here:
```c
/// Item list for NPC sell/buy list
struct npc_item_list {
	unsigned short nameid;
	unsigned int value;
#if PACKETVER >= 20131223
	unsigned short qty; ///< Stock counter (Market shop)
	uint8 flag; ///< 1: Item added by npcshopitem/npcshopadditem, force load! (Market shop)
#endif
};
```
This is the reason why you have to run `@reloadscript` so it can re-parse the item data value.

**Comment by Triedge** [comment]
Temp fix(?)
find in npc.c
`
		amount = item_list[i].qty;
		nameid = item_list[i].nameid = shop[j].nameid; //item_avail replacement

		value = shop[j].value;

		if( !itemdb_exists(nameid) )
			return 3; // item no longer in itemdb
`

change for:
`
		amount = item_list[i].qty;
		nameid = item_list[i].nameid = shop[j].nameid; //item_avail replacement

		value = itemdb_value_buy(nameid) > shop[j].value ? itemdb_value_buy(nameid) : shop[j].value;

		if( !itemdb_exists(nameid) )
			return 3; // item no longer in itemdb
`
Doing this causes the NPC to cover the new value (only if it is higher than the official), BUT ... the default price is still displayed in the store.
I try to update it in a similar way, but it sends me many Warnings.

**Comment by Triedge** [comment]
Fixed.
In **clif_buylist** of **clif.c**

Search:
`		int val = nd->u.shop.shop_item[i].value;
		if( id == NULL )
			continue;
`

Change for:
`
		if( id == NULL )
			continue;
		int val = id->value_buy > nd->u.shop.shop_item[i].value ? id->value_buy : nd->u.shop.shop_item[i].value;
`

**These changes only work if the new price is higher than the official price.**

**Comment by Akkarinage** [comment]
The feature works as intended and won't be changed. You've now been told by three staff members.

**Comment by Triedge** [comment]
No, it does not currently work as a HOPE that works.

What good is a function that supposedly changes the sale value of the objects and in practice it turns out that it does not?

**Comment by Akkarinage** [comment]
The script command changes the base values of an item. The script command works.

There is no built-in way to alter the sale prices of an item once a shop has been created through the generic shop system. To achieve what you want, you should use the npcshopitem command in order to manipulate the shop. Please read the documentation.

Script commands will not be altered in functionality to suit your needs when other methods already exist.

**Comment by Triedge** [comment]
Did not you see the code I made? I already corrected it!
I just shared the solution ... -_-
Although in my solution only works if the price of the item is higher than the original price of the store.

"There is no built-in way to alter the sale prices of an item once a shop has been created through the generic shop system"
FIX:
`int val = id->value_buy > nd->u.shop.shop_item[i].value ? id->value_buy : nd->u.shop.shop_item[i].value`

**Comment by Triedge** [comment]
Other fix...

`int val = id->value_buy != nd->u.shop.shop_item[i].value ? id->value_buy : nd->u.shop.shop_item[i].value`

**Comment by Akkarinage** [comment]
I did see the code. There is no fix needed as this script command is not for modifying code in NPCs.. I've already said that other methods already exist.

**Comment by Triedge** [comment]
And what is that other method?
I need to change the price of all the stores in the game ... not just 1.
And this price changes every day.

**Comment by Atemo** [comment]
You still can contribute by submitting a PR. Thanks !

**Comment by sigtus** [comment]
Thank you very much! This is really useful.

**Comment by Triedge** [comment]
your welcome @sigtus n_n
