### ISSUE TITLE
Mora - Guardian of Power

### ISSUE THREAD

**Issue by MrAntares** [rathena/rathena#187]
The guardians gives only a portion of the equipments he should. Eg: 4 out of 8 for rangers.
/npc/re/merchants/enchan_mora.txt
http://irowiki.org/wiki/Mora_Village#Mora_Equips

**Comment by MrAntares** [comment]
Then remove the rest of the npc as well and explain to all of the players why they can't get it... -.-

**Comment by euphyy** [comment]
Look at the dates.  Half the items were removed in a later episode and added as monster drops.  The rest of the items were not.
