### ISSUE TITLE
Reproduce Skill List

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#1871]
Source: http://irowiki.org/wiki/Reproduce/List_of_reproducible_skills
This page was last modified on **1 December 2016, at 14:33.**

**Missing in our list:**
**Renovatio** ~ Arch Bishop

**Not listed on irowiki but we have them active:**
GC_DARKCROW,2      // Dark Claw

WL_TETRAVORTEX,2    // Tetra Vortex
WL_SUMMONFB,2       // Summon Fire Ball
WL_SUMMONBL,2       // Summon Lightning Ball
WL_SUMMONWB,2       // Summon Water Ball
WL_SUMMONSTONE,2    // Summon Stone

NC_MAGMA_ERUPTION,2 // Magma Eruption

LG_EXEEDBREAK,2  // Exceed Break
LG_MOONSLASHER,2 // Moon Slasher

SR_SKYNETBLOW,2     // Sky Net Blow

GN_ILLUSIONDOPING,2  // Illusion Doping

**Comment by Lemongrass3110** [comment]
#1432
