### ISSUE TITLE
Celine Kimi Card - Critical Wound

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#1875]
According to kRO item description seen here:
http://ro.gnjoy.com/guide/runemidgarts/itemview.asp?itemSeq=5&ID=31023

Celine Kimi Card officialy casts Critical Wound on all ENEMIES seen on screen rather than on SELF as it's currently in the Horror Toy Factory branch #1813 
And lvl 3, not 5

**Correct item script would be:**
`31023,Celine_Kimi_Card,Celine Kimi Card,6,20,,10,,,,,,,,2,,,,,{ bonus bMatkRate,10; bonus5 bAutoSpell,"NPC_CRITICALWOUND",3,200+(50*getrefine()),BF_MAGIC,1; },{},{}`

And Celine Kimi MVP HP and Experience
http://ro.gnjoy.com/guide/runemidgarts/popup/monsterview.asp?monsterID=XM_CELINE_KIMI

**Should be:**
`2996,XM_CELINE_KIMI,Xm Celine Kimi,Celine Kimi,160,66666700,1,4444440,3666670,2,5636,8303,479,444,144,166,44,444,166,166,10,12,2,1,28,0x6283695,100,768,1056,480,444444,616,10000,617,10000,22534,10000,22534,4000,18549,4000,7642,4000,19701,100,13442,100,712,10000,0,,0,0,0,0,0,`

**Comment by Atemo** [comment]
Note : we took EXP and HP from https://forums.warpportal.com/index.php?/topic/168763-fansitedb-information-distribution-and-request-station/?p=2522697
https://www.dropbox.com/s/kczowkm0h9o5p6l/Nightmare%20Toy%20Factory.xlsx?dl=0

**Comment by Everade** [comment]
Note: I'm usualy being told that iRO isn't a reliable source because you base anything on kRO / Aegis. So there you go.

**Comment by Atemo** [comment]
Some kro datas from their website aren't up-to-date. irowiki isn't a reliable source but datas given by iro CM are pretty reliable. We are data dependent btw

**Comment by Everade** [comment]
@Atemo 
How can you possibly say that iRO data is pretty reliable when they base their information on **iRO**.
**iRO has a lot of customizations when compared to kRO**. Your link leads to **fan created data**... c'mon.

I'm not willing to start a flame war here, really not. But it's really ridiculous when i'm always being told that i can throw my iRO links into the bin.

And when i deliver actual kRO database information (even though it might not be fully up to date (as if any Athena project ever was lol))
You're telling me the exact opposite. Like WT*

I'm running in circles here.

I'm not pointing with my finger on the guy who decided to use iRO fan gathered data.
The only thing i did here was, i've noticed some differences between the rA database on a pull request compared to actual kRO, officialy released data.

Thank you

**Comment by Akkarinage** [comment]
> i've noticed some differences between the rA database on a pull request compared to actual kRO, officialy released data

We'll happily accept kRO data. 😄 

irowiki isn't updated by staff from iRO, thus the data can't be verified as true. Data from the iRO forums given by the CMs can be taken as red as we don't expect them to be giving duff into to their players. irowiki is like getting data from RMS. No one knows how the data is gathered, how long it's been there, who is updating it, etc etc.
