### ISSUE TITLE
Cannot logout

### ISSUE THREAD

**Issue by Tokeiburu** [rathena/rathena#1877]
Since the 'logout update', it is no longer possible to log out. sd->canlog_tick is never set; you'd need to add 
```
	sd->canlog_tick = gettick();

	if (!(battle_config.prevent_logout_trigger&PLT_LOGIN))
		sd->canlog_tick -= battle_config.prevent_logout;
```
somewhere in the login process (in pc_reg_received?).

git 6de7aa88e8571cb56d91c0d706babe0467f414ed

**Comment by Everade** [comment]
Just wanted to report this.

For now, set prevent_logout battle conf to 0
That allows you to logout again.
