### ISSUE TITLE
Aqua Bunny Band - Bonus

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#1881]
According to item description, the fixed cast rate should be reduced, not variable.

**Correct item bonus would be:**
`18887,Aqua_Bunny_Band,Aqua Bunny Band,4,0,,100,,2,,1,0xFFFFFFFF,63,2,256,,0,1,1012,{ bonus bVit,3; bonus bMdef,5; bonus bMatkRate,2; .@r = getrefine(); if(.@r>11) bonus bFixedCastrate,-10; else if(.@r>8) { bonus bMatkRate,4; bonus bMdef,5; } },{},{}
`

http://www.divine-pride.net/database/item/18887/aqua-bunny-band
and
http://db.irowiki.org/db/item-info/18887/

**Comment by zackdreaver** [comment]
According AEGIS and twRO's description, the item script is correct.
Aegis:

> event OnStartEquip:
	AddExtParam User VAR_MAGICATKPERCENT 2
	if GetRefineLevel [LOCATION_HEAD2] > 11
		SubSpellCastTime 10
	elseif GetRefineLevel [LOCATION_HEAD2] > 8
		AddExtParam User VAR_MAGICATKPERCENT 4
		AddExtParam User VAR_MDEFPOWER 5
	endif
return

twRO: 素質詠唱時間

iRO and euRO description isn't reliable

**Comment by Everade** [comment]
Thanks for the info.
I guess this can be closed then.
