### ISSUE TITLE
Sp regen crash

### ISSUE THREAD

**Issue by Tokeiburu** [rathena/rathena#1882]
I'm aware there are similar issues to this, but they seem slightly different (unrelated to the HP values). I'm unable to reproduce this issue with the same character more than once, so it's really hard to pinpoint.

The loading order of a character must always be:
- pc_reg_received > asks for intif_storage_request
- intif_parse_StorageReceived > status_calc_bl_(SCO_FIRST|SCO_FORCE)
- clif_parse_LoadEndAck > status_calc_pc(sd, SCO_NONE)

However sometimes the char-server doesn't send the inventory quick enough and clif_parse_LoadEndAck (requested by the client) gets called before intif_parse_StorageReceived is received (tested multiple times). So you get:
- pc_reg_received > asks for intif_storage_request
- clif_parse_LoadEndAck > status_calc_pc(sd, SCO_NONE)

This will always crash the map-server on `sregen = regen->ssregen;` because SCO_FIRST wasn't called yet. It is hard to reproduce, I'm guessing it's because the SQL query to load the character's inventory is slightly slower the first time than a previously loaded character (could be completely wrong on that)? Anyway, it's just missing a protection of some sort to delay clif_parse_LoadEndAck, something such as:

```
//pc_reg_received
	sd->state.active = 1;
	sd->state.inventory_loaded = 0; // New variable to ensure the order is respected

	intif_storage_request(sd,TABLE_STORAGE, 0, STOR_MODE_ALL); // Request storage data
	intif_storage_request(sd,TABLE_CART, 0, STOR_MODE_ALL); // Request cart data
	intif_storage_request(sd,TABLE_INVENTORY, 0, STOR_MODE_ALL); // Request inventory data
```

```
//clif_parse_LoadEndAck
	// Autotraders should ignore this entirely, clif_parse_LoadEndAck is always invoked manually for them
	if (!sd->state.active || (!sd->state.autotrade && !sd->state.inventory_loaded)) { //Character loading is not complete yet!
		//Let pc_reg_received or intif_parse_StorageReceived reinvoke this when ready.
		sd->state.connect_new = 0;
		return;
	}
```

```
//intif_parse_StorageReceived
			status_calc_pc(sd, (enum e_status_calc_opt)(SCO_FIRST|SCO_FORCE));
			status_calc_weight(sd, CALCWT_ITEM|CALCWT_MAXBONUS); // Refresh weight data
			chrif_scdata_request(sd->status.account_id, sd->status.char_id);
			sd->state.inventory_loaded = 1;

			if (sd->state.connect_new == 0 && sd->fd) { //Character already loaded map! Gotta trigger LoadEndAck manually.
				sd->state.connect_new = 1;
				clif_parse_LoadEndAck(sd->fd, sd);
			}

			break;
```

git 06c40e6cb412cd02428d4bc326b298849c2058d7

**Comment by Everade** [comment]
I've already mentioned that it's not related to the HP.
And yes it's extremely hard to reproduce. Especialy since the same character will never crash the server twice.

The crashes seem feel really random and are usualy caused by Royal Guards or Rune Knights.

**Comment by MrAntares** [comment]
I suspected the same issue in my HP map crash as well. Possibly all 3 issues are because something loading too slowly and a calculation is not getting the values it needs. That is why when my server crashed on login, the character had 0 stats and values and other players only saw the default female novice sprite.
