### ISSUE TITLE
OnPCLoginEvent doesn't work

### ISSUE THREAD

**Issue by johnfercher** [rathena/rathena#1883]
My rAthena is up-to-date and, doesn't matters how I call this label (OnPCLoginEvent), it's never works.

```
-	script	login_player_cmd	-1,{
	OnPCLoginEvent:
		dispbottom "test";
	end;
}
```

**Comment by Lemongrass3110** [comment]
Just tested it and could not reproduce it.

```
-	script	LoginEvent	-1,{
	end;

OnPCLoginEvent:
	dispbottom "Test";
	end;
}
```

Do you possibly have any errors on your mapserver console?

**Comment by Akkarinage** [comment]
Also unable to reproduce. 5 days with no further update, assuming user resolution.
