### ISSUE TITLE
Meteor Assault With EDP on Renewal

### ISSUE THREAD

**Issue by alxalmora** [rathena/rathena#1885]
According to iRO: Meteor Assault skill is unaffected by Enchant Deadly Poison (http://irowiki.org/wiki/Meteor_Assault)

https://github.com/rathena/rathena/blob/eb47d74f08a2ee481497da263be62725fdd70c89/src/map/battle.c#L4413

**Comment by Playtester** [comment]
Can confirm this. Just tested and Meteor Assault damage is NOT increased when EDP is active.

**Comment by MrAntares** [comment]
I also saw some forum discussions back then stating the same not being affected by EDP. A pity tho. It is already underpowered.
