### ISSUE TITLE
Calling 'reloadscript' using a process signal

### ISSUE THREAD

**Issue by Ricardonacif** [rathena/rathena#1891]
Guys,

I think it totally makes sense to add a way of reloading scripts thru terminal (command line). Something like ./athena-start reloadscript . On the following PR, I've added a listener for the USR1 signal, which is specific used for custom behaviors. 

What do you think about the ./athena-start reloadscript ? Should I add it to the script?

**Comment by Lemongrass3110** [comment]
I do not know if it makes sense to assign reloadscript to one of the two available USR signals.
We have tons of atcommands or possibilities that could be bound to those signals.

I think using the existing console commands would be better. I do not know your usecase though.
```
// Console Commands
// Allow for console commands to be used on/off
// This prevents usage of >& log.file
console: off
```

Output of the help command:
```
admin:@<atcommand> => Uses an atcommand. Do NOT use commands requiring an attached player.
admin:map:<map> <x> <y> => Changes the map from which console commands are executed.
server:shutdown => Stops the server.
ers_report => Displays database usage.
```

**Comment by Ricardonacif** [comment]
I see, @Lemongrass3110 I'm not aware about the console commands. How an I access this console?

**Comment by Lemongrass3110** [comment]
Well you just have to turn it on in the mapserver configuration. Then it behaves like a standard command line application and you can enter commands on the spawned shell window.

**Comment by Ricardonacif** [comment]
@Lemongrass3110 not sure I understand it. I'm sshing the server and in the rathena folder. How can I open this console?

**Comment by anacondaqq** [comment]
hi @Ricardonacif , let me help you. Look.

This console it's your map-server.
use screen to run each server in seperate process which you can easly manage:

apt-get install screen -y
screen -amdS mymapserver ./folder_to_map_server/map-server
screen -amdS mycharserver ./folder_to_char_server/char-server
screen -amdS myloginserver ./folder_to_login_server/login-server

Then try screen -ls to see your running in background screens.
Then join to one of the screen for example for map-server

screen -X mymapserver
Then, you will see console with outputs from map-server like
[Info] : bla bla bla
or
[Debug] : bla bla bla
or
[Status]: bla bla bla

just try to type any command inside it end press enter. You can do it, map-server will understand it (if you will enable it like @Lemongrass3110 said above).

**Comment by Lemongrass3110** [comment]
Sorry I thought you would know how to use STDIN if you actually know how to send USR signals to a process. Might have been my fault for not explaining it with enough details.

I am closing this now. You should still be able to comment on the issue for further input.

**Comment by Ricardonacif** [comment]
Thanks for the explanation guys!

**Comment by Ricardonacif** [comment]
@anacondaqq any other way of sending inputs to the process without all this screen stuff? Like if I wanna the announce thru the cronjob every 10 min, would there be a way? (I know I should use NPC for that, just an example)
