### ISSUE TITLE
Whosell not working since storage change

### ISSUE THREAD

**Issue by DapvhirGaming** [rathena/rathena#1896]
* **rAthena Hash**: 

https://github.com/rathena/rathena/commit/9c552ca2566f8682d5fa1e602bc9e522f90cc1e9

* **Client Date**: 

20151104

* **Server Mode**: 

Renewal

* **Description of Issue**: 
Formerly working '@whosell' command is no longer functional since this hash.
Error is as follows:
``Error: 'struct mmo_charstatus' has no member named 'cart'
          ,pl_sd->status.cart[pl_sd->vending[j].index].card[0]``

(there are multiple instances of this down the line, but they all point to the status.cart)
Not really sure what adjustments need made here to make this functional again.

**Comment by Lemongrass3110** [comment]
Whosell is not part of rAthena. You might want to contact the eAmod/rAmod developers or whoever created that command and tell them to update it to the latest syntax.
