### ISSUE TITLE
Berserk shouldn't overwrite Two Hand Quicken

### ISSUE THREAD

**Issue by zackdreaver** [rathena/rathena#1899]
Hash: https://github.com/rathena/rathena/commit/047ef1263b0b23fd200e6c736147ed88f9fd7ece
Mode: Renewal

Iirc, Lord Knight's Berserk shouldn't rewrite Knight's Two Hand Quicken
Haven't tested on prerenewal, but the effect should be like a renewal one.

**Comment by Playtester** [comment]
In renewal you can only gain ASPD from one source (always the strongest).
So Berserk and Two-Hand Quicken do NOT stack with each other.

For example on kRO:
Lord Knight 99 Agi Katana - 161 ASPD
Two-Hand Quciken - 164 ASPD
Berserk - 168 ASPD
Two-Hand Quicken + Berserk - 168 ASPD

So this one is invalid.

Note that we go by kRO ASPD. On other official servers the ASPD formula is different.

**Comment by zackdreaver** [comment]
Oh yeah, I forgot we use kRO formula
