### ISSUE TITLE
RK_CRUSHSTRIKE wrong duration

### ISSUE THREAD

**Issue by zackdreaver** [rathena/rathena#1900]
Hash: https://github.com/rathena/rathena/commit/047ef1263b0b23fd200e6c736147ed88f9fd7ece
Mode: Renewal

Rune Knight's Crush Strike duration should be 30 seconds instead 3 minutes.
Because I don't have RK to test, I dug some old thread on iRO.
https://forums.warpportal.com/index.php?/topic/57906-post-balance-crushing-strike-damage/

**Comment by aleos89** [comment]
Confirmed on kRO.
