### ISSUE TITLE
GTB card and Masquerade skills

### ISSUE THREAD

**Issue by zackdreaver** [rathena/rathena#1901]
Hash: https://github.com/rathena/rathena/commit/047ef1263b0b23fd200e6c736147ed88f9fd7ece
Mode: Renewal

GTB card shouldn't bloking Shadow Chaser's Masquerade skills.
Source:
https://forums.warpportal.com/index.php?/topic/131020-pvp-how-to-defend-masquerade/

**Comment by Jeybla** [comment]
Confirmed by Nova here: #1400
