### ISSUE TITLE
Bug in <ITEM>

### ISSUE THREAD

**Issue by Triedge** [rathena/rathena#1902]
* **rAthena Hash**: 

Please specify the rAthena [GitHub hash](https://help.github.com/articles/autolinked-references-and-urls/#commit-shas) on which you encountered this issue.

* **Client Date**: 

2015-11-04

* **Server Mode**: 

Pre-Renewal

* **Description of Issue**: 
  * Result - Describe the issue that you experienced in detail.
The Link of items is overexposed in other lines of the dialog box. Does not respect position.
  * Expected Result - Describe what you would expect to happen in detail.
  * How to Reproduce - 

Create a simple NPC and add sample text from doc / script_commands.txt
in the code...
`
mes "Hello..."
mes "Did you ever consume a <ITEM>Red Potion<INFO>501</INFO></ITEM>?";
mes "See ya";
`

![screenshot_77](https://cloud.githubusercontent.com/assets/5862340/22172244/1747dbdc-df67-11e6-8ac0-949bc75a827d.png)

**Comment by secretdataz** [comment]
Please see #1236.
