### ISSUE TITLE
Modified mobs using Unit Controller scripts can be dispelled

### ISSUE THREAD

**Issue by technoken** [rathena/rathena#1903]
* **rAthena Hash**: 047ef1263b0b23fd200e6c736147ed88f9fd7ece
* **Client Date**: 2013-12-23
* **Server Mode**: Pre-renewal

Can the modification of the mobs using unit controller scripts be dispelled?

After spawning the mob I cast Deluge, Volcano, or Violent Gale.
If the mob is inside those skills when I cast dispel, the modification is also dispelled.
```
prontera,153,178,4	script	monstertest	52,{
	monster "prontera",155,178,"--ja--",1002,1,"monstertest::OnKill";
	.@mobid = $@mobid[0];
	setunitdata .@mobid,UMOB_MAXHP,100000000;
	setunitdata .@mobid,UMOB_ATKMIN,10000;
	setunitdata .@mobid,UMOB_ATKMAX,21000;
	setunitdata .@mobid,UMOB_MATKMIN,10000;
	setunitdata .@mobid,UMOB_MATKMAX,21000;
	setunitdata .@mobid,UMOB_HIT,10000;
	setunitdata .@mobid,UMOB_ATKRANGE,5;
	setunitdata .@mobid,UMOB_ADELAY,100;
	getunitdata .@mobid,.@param;
	setunitdata .@mobid,UMOB_HP,.@param[UMOB_MAXHP];
	end;
}
```

EDIT:
even when not using dispel. I just recast Deluge, Volcano, or Violent Gale to the mob. Then the modifications are gone.

EDIT2:
looks like even when the mob goes back and forth inside those skills the modification will be gone. maybe because of the ground enchantment?

**Comment by Lemongrass3110** [comment]
Probably because their status is being recalculated and those changes will be lost? @aleos89

**Comment by technoken** [comment]
thanks for the quick fix @aleos89 :+1:
