### ISSUE TITLE
Inventory and Cart save requests

### ISSUE THREAD

**Issue by aleos89** [rathena/rathena#1910]
* **rAthena Hash**: 08d55d8

* **Client Date**: Any

* **Server Mode**: Both

* **Description of Issue**: 
When a character is saved, a request is also sent for the inventory and cart data of that character. While this is good, not all instances of a player requesting to be saved needs their inventory and cart data to be saved as well. This results in a bit more server and network activity than what is needed.

* **Modifications that may affect results**: None

**Comment by RadianFord** [comment]
Sorry if im wrong about this, Is this related to the issue?
[http://i.imgur.com/adpF1Uk.png](url)

**Comment by aleos89** [comment]
Yes, exactly that.
