### ISSUE TITLE
Backslide animation vs wall

### ISSUE THREAD

**Issue by zackdreaver** [rathena/rathena#1914]
Hash: 0b2e0cc3fd74325fd8a5590dc93e3129ce20f7b6
Test client: 2016-02-03aRagexeRE
Mode: Renewal
Test Server: iRO renewal
Bug description: in official Thief's Backslide skill have no animation when it hit a wall, but in rA it does have. Can't confirm this on prerenewal, I don't have thief on iro classic.

Replay file:
[Backslide.zip](https://github.com/rathena/rathena/files/730711/Backslide.zip)

**Comment by zackdreaver** [comment]
@aleos89 
New bug after your fixes,
the animation is applied when there is no wall.

Hash: https://github.com/rathena/rathena/commit/d99c91418ac671ca8a46d53d226f40164f7139d7

**Comment by zackdreaver** [comment]
@aleos89 
Sorry to ask again, have you check it?

**Comment by Playtester** [comment]
Why is it a bug that it shows the animation when there is no wall?

**Comment by zackdreaver** [comment]
It is official behavior and there is no animation before this fix applied either.

**Comment by Playtester** [comment]
Ah I see, probably because you now move first and then show animation and before you showed the animation and then moved.
But removing the animation call would also stop making you shout the skill name...

**Comment by aleos89** [comment]
@zackdreaver: Sorry I thought I had responded to this. As @Playtester stated, that's the predicament we are in right now. If we remove the clif call then the name of the skill won't be "shouted" when used.

**Comment by Playtester** [comment]
@zackdreaver Basically what you are saying is that in all cases Backslide does not show an animation, no matter whether you hit a wall or not, right? It just shows the name.

**Comment by zackdreaver** [comment]
yes, you're correct @Playtester 

@aleos89 
Nah it's ok, Its not like I'm pushing you guys to quickly fix it,
it just that guys are really dependable on fixing bugs here.
