### ISSUE TITLE
Pet keeps on attacking even when master is already dead

### ISSUE THREAD

**Issue by technoken** [rathena/rathena#1916]
* **rAthena Hash**: 10c4bacab506ef37dc384ac9afc57783301c0076
* **Client Date**: 2013-12-23
* **Server Mode**:  Pre-renewal
No source modification

when **pet_attack_support** and **pet_damage_support** is enabled then the master of a pet died(died by suicide), the pet still keeps on attacking the mob that the master last attacked

How to reproduce:
- enable pet_attack_support and pet_damage_support
- edit a pet that will support the master
e.g `1113,DROPS,Drops,620,9002,10013,508,80,60,10,100,1000,50,1,110,1,0,10000,10000,10000,{ petskillattack "NPC_EARTHQUAKE",1,5,10; },{}`
- use a paladin as a master and hatch the pet
- try to reach lower HP on the paladin (around 50 hp) then use sacrifice and try to kill a mob. when the paladin died first before the mob. the pet will keep attacking the mob even when the master is dead.

**Comment by aleos89** [comment]
The question that comes to my mind is, is this a bug? Considering this feature isn't official at all, how do we determine if this is what the original creators intended or not.

**Comment by lucasoli** [comment]
I totally agree with you Aleos. However, by adding an extra config just to determine if they should stop attacking or not would be nice as well. What do you think?

**Comment by Playtester** [comment]
Adding additional options for custom features while you could work on something official instead seems meh...

**Comment by lucasoli** [comment]
What do I need to do to assign this issue to me? As I'm not working on any official feature or bugs I think I could help you guys with this issue. I'd be glad to help you guys at least once.

**Comment by Playtester** [comment]
Only devs can be assigned, but you can always create a pull request.

**Comment by lucasoli** [comment]
Thanks!

**Comment by aleos89** [comment]
```diff
 conf/battle/pet.conf |  3 +++
 src/map/battle.c     |  1 +
 src/map/battle.h     |  1 +
 src/map/pet.c        | 11 ++++++++---
 4 files changed, 13 insertions(+), 3 deletions(-)

diff --git a/conf/battle/pet.conf b/conf/battle/pet.conf
index 45745b140..aab8f49eb 100644
--- a/conf/battle/pet.conf
+++ b/conf/battle/pet.conf
@@ -78,3 +78,6 @@ pet_disable_in_gvg: no
 
 // Will does petskillattack2 fixed damage ignore plant infnite defense? (Note 1)
 pet_ignore_infinite_def: yes
+
+// Whether or not the pet will continue to attack when the master is dead. (Note 1)
+pet_master_state: 0
diff --git a/src/map/battle.c b/src/map/battle.c
index aa878b13f..a59197a2c 100644
--- a/src/map/battle.c
+++ b/src/map/battle.c
@@ -8020,6 +8020,7 @@ static const struct _battle_data {
 	{ "pet_max_atk1",                       &battle_config.pet_max_atk1,                    750,    0,      INT_MAX,        },
 	{ "pet_max_atk2",                       &battle_config.pet_max_atk2,                    1000,   0,      INT_MAX,        },
 	{ "pet_disable_in_gvg",                 &battle_config.pet_no_gvg,                      0,      0,      1,              },
+	{ "pet_master_state",                   &battle_config.pet_master_state,                0,      0,      1,              },
 	{ "skill_min_damage",                   &battle_config.skill_min_damage,                2|4,    0,      1|2|4,          },
 	{ "finger_offensive_type",              &battle_config.finger_offensive_type,           0,      0,      1,              },
 	{ "heal_exp",                           &battle_config.heal_exp,                        0,      0,      INT_MAX,        },
diff --git a/src/map/battle.h b/src/map/battle.h
index e4c08a3d3..41fffd1dd 100644
--- a/src/map/battle.h
+++ b/src/map/battle.h
@@ -232,6 +232,7 @@ extern struct Battle_Config
 	int pet_max_atk2; //[Skotlex]
 	int pet_no_gvg; //Disables pets in gvg. [Skotlex]
 	int pet_equip_required;
+	int pet_master_state;
 
 	int skill_min_damage;
 	int finger_offensive_type;
diff --git a/src/map/pet.c b/src/map/pet.c
index 5f1ee4542..e016d745c 100644
--- a/src/map/pet.c
+++ b/src/map/pet.c
@@ -151,9 +151,9 @@ int pet_attackskill(struct pet_data *pd, int target_id)
 
 /**
  * Make sure pet can attack from given config values.
- * @param sd : player requesting (owner)
- * @param bl : target
- * @param type : pet's attack rate type
+ * @param pd: pet data
+ * @param bl: target
+ * @param type: pet's attack rate type
  * @return 0
  */
 int pet_target_check(struct pet_data *pd,struct block_list *bl,int type)
@@ -174,6 +174,11 @@ int pet_target_check(struct pet_data *pd,struct block_list *bl,int type)
 		!check_distance_bl(&pd->bl, bl, pd->db->range2))
 		return 0;
 
+	if (!battle_config.pet_master_state && pc_isdead(pd->master) && pd->target_id) {
+		pd->target_id = 0;
+		return 0;
+	}
+
 	if (!status_check_skilluse(&pd->bl, bl, 0, 0))
 		return 0;
 ```
Just quickly wrote that up. I haven't tested it, so let me know if it works out fine.

**Comment by technoken** [comment]
Thanks @aleos89 . I'll try it later when I got home. Anyway I just saw this thing as abusable regardless of not being official. Btw thanks for writing a patch. :+1:

**Comment by aleos89** [comment]
I updated the above code. Try it now and let me know.

**Comment by technoken** [comment]
@aleos89 it's still attacking the mob when master is dead. I double checked it and recompiled.

Anyway I edit the source and somehow it's working now. But i don't know if it has a potential mapcrash.
FROM
```
+	if (!battle_config.pet_master_state && pc_isdead(pd->master) && pd->target_id) {
+		pet_unlocktarget(pd);
+		return 0;
+	}
```
TO
```
+	if (!battle_config.pet_master_state && pc_isdead(pd->master)) {
+		pet_unlocktarget(pd);
+		return 0;
+	}
```
