### ISSUE TITLE
can not duel after use command

### ISSUE THREAD

**Issue by cold-hr** [rathena/rathena#1919]
* **rAthena Hash**: 

[GitHub hash](https://github.com/rathena/rathena/tree/940c473c8824685042c28e851351541d5ee4e1f8) 

* **Client Date**: 

2015-10-29

* **Server Mode**: 

use: Pre-Renewal

* **Description of Issue**: 
  * After the duel, then
  * can not show sword 

* ***pic**:
  * Previous updates
![image](https://cloud.githubusercontent.com/assets/13975637/22363479/381ba9de-e49d-11e6-98cb-4d97ace741f5.png)

  * after update
![image](https://cloud.githubusercontent.com/assets/13975637/22363523/76cbfcec-e49d-11e6-89da-15fcd5c5c4f9.png)

**Comment by technoken** [comment]
Try /ns ?

**Comment by Lemongrass3110** [comment]
Update your server.

**Comment by cold-hr** [comment]
@Lemongrass3110 
I tested the last git remains the same.

**Comment by anacondaqq** [comment]
@cold-hr try @pvpon, @pvpoff on the map, then try to make duel, is issue fixed? Some time ago i saw similar issues, but it were because of map_type first loading on fresh server, pvpon / pvpoff forces to change map_type.

**Comment by hnomkeng** [comment]
Same issue.
Use /ns or shift to attack only

VDO : https://youtu.be/izLYfHUSpDg

Git Version : 19795

**Comment by secretdataz** [comment]
@hnomkeng Please reproduce this bug on latest Git hash before reporting again.
