### ISSUE TITLE
Novice Academy - Cooking Quest Item

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#1923]
* **rAthena Hash**: 
6e9cd44

* **Client Date**: 
20151104

* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result - Item Script of ItemID 12849 Combination Kit is missing.
  * Expected Result - Item should be usable which then cooks something within your inventory.
  * How to Reproduce - Run through the novice academy quest and talk to the NPC
Therapist located at iz_ac01 59 43
He will give out the 10x item **Combination Kit** itemID 12849.
Or buy them at General Store Owner located at iz_ac01 68 49

**Comment by aleos89** [comment]
Duplicate of #1571.
