### ISSUE TITLE
party leave and devotion

### ISSUE THREAD

**Issue by anacondaqq** [rathena/rathena#1926]
* **rAthena Hash**: 
595d9b743d6e2401525c7fd4c4e2fa2a8c110841

* **Client Date**: 
2015-11-04aRagexe

* **Server Mode**: 
Renewal, but i guess pre-re will be affected too

* **Description of Issue**: 

  * Result - Leaving party while you are palladin and have someone under your devotion do not break devotion effect, and you can protect and receive damage from target which not in your party.
  * Expected Result - when you leave party, devotion should be stopped too.

  * How to Reproduce - Create party between 2 chars, 1 paladin, 1 for example Whitesmith. Whitesmith is party leader. Cast Devotion on Whitesmith, then go to Paladin, open party window and leave party. You will see that devotion effect not removed.

![](http://i.imgur.com/kZKI0hL.png)
P.S. 550 it's damage from Paladin removed, because i hitting via Assasin Whitesmith. And Paladin keep continue to support via devotion Whitesmith, while party has been removed. 

  * Official Information - i do not know how it should be at kRO. But if follow logic of devotion, this spell affect only party members. So if player not in party -> player should not be devoted (?)

![](http://i.imgur.com/uqlZBtW.png)

Extra important notes: i do not use latest hash for now, if someone can confirm it on latest revision it will be great. I can confirm it on latest revision and how it should be after few weeks only (sorry), but just not forgetting about the issue i have created it. If something will be wrong with it, or everything works like it should -> i will close the issue.

**Comment by aleos89** [comment]
Tested on Aegis:
Party and Devotion
![devo1](https://cloud.githubusercontent.com/assets/3521753/22405529/2bfb6682-e612-11e6-8ac1-e00039011f5f.PNG)
Left party and Devotion continues
![devo2](https://cloud.githubusercontent.com/assets/3521753/22405536/466aac9e-e612-11e6-80bb-fc294d2bea2f.PNG)
