### ISSUE TITLE
Sitting issue for devoted players

### ISSUE THREAD

**Issue by anacondaq** [rathena/rathena#1927]
* **rAthena Hash**: 

595d9b743d6e2401525c7fd4c4e2fa2a8c110841

* **Client Date**: 

2015-11-04aRagexe

* **Server Mode**: 

Renewal

## Description of Issue

* Paladin and Assasin Cross in party
* Assasin Cross under devotion casted by Paladin
* Enabled pvp on map (izlude)
* Assasin Cross is sitting
* Champion casting Asura strike on Assasin Cross and deal damage
* Assasin Cross Stand up (animation like he received a hit)
* At the same time Assasin Cross can't walk, or do anything, he still sitting (at 2015-11-04a we have status icons which show to use that we are sitting, and we are already sitting, even we received damage from Champion which transfered (damage) to Paladin). But we have triggered animation.
* If do `@refresh` we will see that Assasin Cross still sitting after receiving damage.

### Result

1. ![Assasin Cross is sitting with deovtion effect](http://i.imgur.com/MdSkvSV.png)
2. ![Champion hit Assasin Cross via Asura Strike](http://i.imgur.com/Y7nLsiR.png)
3. ![shredinger cat, i'm standing or sitting?](http://i.imgur.com/XgBNqV1.png)
4. ![Sitting while standing xD](http://i.imgur.com/3LeQujk.png)

### Expected Result

Champion deals damage on Assasin Cross which under Devotion.

**in my opinion the correct behaviors:**
1. Or Assasin cross must stand-up even if he don't received damage to him.
2. Or Assasin Cross still sitting, and he not stand up and change animation.

### How to Reproduce
1. Create 3 characters:
* Paladin
* Assasin Cross
* Champion

2. Create party between Assasin Cross and Paladin.
3. Go to Paladin and cast Devotion on Assasin Cross
4. Go to Assasin Cross and press Insert button (sit)
5. Enable `pvp` on map (in my case i'm at izlude)
6. Go to Champion and cast Asura Strike against Assasin Cross while Asssasin Cross Sitting
7. You will hit Paladin (because damage will be trasfered to Paladin)
8. Assasin Cross will stand up.
9. Do `@refresh` on Champion to confirm that Assasin Cross is sitting
10. Go to Assasin Cross and try to move -> you will see "animation after receiving damage", but at the same time you are in sitting state, so you can't walk or do anything. But at the same time your animation in stand-up mode

### Official Information
I do not know how it should be at official server. I don't have account at kRO to confirm or reject current issue

### Important notes
* I do not use yet latest hash (soon will), so i do not know how it on latest revision, maybe soneone has time to confirm it on latest revision, i will be appreciated. Anyway, soon i will test it on latest revision too.

**Comment by aleos89** [comment]
I was able to reproduce the same effect on Aegis.

**Comment by Jeybla** [comment]
Nice issue description!

I just wonder if this effect applies to other single target spells as well?
