### ISSUE TITLE
sql_files import in db

### ISSUE THREAD

**Issue by Somans13** [rathena/rathena#1931]
* **Client Date**: 

latest

* **Description of Issue**: 

Hey,
I've some trouble for importing all my sql files into my local phpmyadmin database. 
When i donwload the rAthena ressources, i've 3 files full of sql. "sql_files", "tools" and "upgrades".

I can import all the sql from sql_files easily, except the trouble with the name of some item like "Gentleman\'s Pipe", than i've too convert in "Gentleman''s Pipe". But that's a solved point. The real problem is about the "tools" and "upgrades" content files.

This files are suppose to manage some table in my db, like the "upgrade_20140627.sql", who use the command "ALTER TABLE `pet` CHANGE `incuvate` `incubate` int(11) unsigned NOT NULL default '0';
"
The problem is that my db didn't content the "pet" table, even if of course i first import all the sql_files main files before "upgrades" and "tools"
And this trouble is repeating for a lot of sql files, i've a total 30 .sql files who can't use their commands because the table doesn't exist, of because the collumn doesn't exist, etc...

![sans titre](https://cloud.githubusercontent.com/assets/25436815/22432318/ca80513e-e714-11e6-98c1-6b65596bdf01.jpg)

It is normal ? Maybe i don't need too import all the sql files in my db ? I search a lot, but didn't see anything about thirs. For my local server, i use the guide from the rAtheno Board of mister Einjerin in the topic "[Tutorial] How to Create Ragnarok Offline 2015 client ", and he say : 

_Execute all SQL scripts in rathena

1. In phpmyadmin, click the ragnarok database

2. Click SQL

3. Open rathena\sql-files folder

4. **Open .sql files(one by one, including ,sql files in subfolders)** and copy paste it in the SQL phpmyadmin textarea

5. Click Go

6. Repeat step 4 until all .sql files are executed._

Ty for helping, and sorry, i think my english is a bit hard to understand :p

**Comment by Lemongrass3110** [comment]
You only need main.sql all other are optional.
GitHub is not for support but rather for issues. Please use our board to get support for your problems.

**Comment by Somans13** [comment]
Ty for you help !
