### ISSUE TITLE
mob_db2_re

### ISSUE THREAD

**Issue by daisyanne1380** [rathena/rathena#1934]
I notice that when the server is compiled for RE it still looks for custom mobs in mob_db2 Instead of mob_db2_re . normally i just rename the table and no problem but Flux cp when set to Renewal it looks for the database mob_db2_re.

I think this also happens with itemdb2

**Comment by aleos89** [comment]
It's just a config adjustment that changes this.
conf/inter_athena.conf:
```
// Map Database Tables
buyingstore_db: buyingstores
buyingstore_items_db: buyingstore_items
item_db_db: item_db
item_db_re_db: item_db_re
item_db2_db: item_db2
//item_db2_db: item_db2_re
item_cash_db_db: item_cash_db
item_cash_db2_db: item_cash_db2
mob_db_db: mob_db
mob_db_re_db: mob_db_re
mob_db2_db: mob_db2
//mob_db2_db: mob_db2_re
```

**Comment by daisyanne1380** [comment]
ahh ok  i get why then. Thanks for reply ill take a look at the config you posted.
