### ISSUE TITLE
Eden Warp

### ISSUE THREAD

**Issue by Joy-Ro** [rathena/rathena#1939]
I noticed when i went into a room a part of the warps dident work.
is about this part i linked below.

```
moc_para01,49,86,0	script	#warp_2_pass_1	WARPNPC,1,1,{
OnTouch:
	warp "moc_para01",103,27;
	end;
}
```

https://github.com/rathena/rathena/blob/master/npc/re/warps/other/paradise.txt

The Fix what i did is replace the ontouch just for warp.

```
moc_para01,57,27,0	warp	#warp_2_pub	1,1,moc_para01,162,26
moc_para01,158,26,0	warp	#warp_2_din_1	1,1,moc_para01,55,27
moc_para01,48,16,0	warp	#warp_2_2f	1,1,moc_para01,48,164
moc_para01,47,161,0	warp	#warp_2_1f	1,1,moc_para01,47,18
moc_para01,107,12,0	warp	#warp_2_din_2	1,1,moc_para01,47,37
moc_para01,100,27,0	warp	#warp_2_gym	1,1,moc_para01,47,85
moc_para01,49,86,0	warp	#warp_2_pass_1	1,1,moc_para01,103,27
moc_para01,113,32,0	warp	#warp_2_ware	1,1,moc_para01,105,92
moc_para01,102,92,0	warp	#warp_2_pass_2	1,1,moc_para01,109,33
moc_para01,41,187,0	warp	#warp_2_room2	1,1,moc_para01,179,93
moc_para01,179,90,0	warp	#warp_2_2fhall_3	1,1,moc_para01,41,185
```

Kind Regards Henry

**Comment by Lemongrass3110** [comment]
Strange enough I was able to confirm this with `#warp_2_pass_1`, but most of the others are working.
Why did we not use warp type npcs here anyway?

**Comment by RDash21** [comment]
Hello there,

This issue also reflects to HazeyForest & OGH which causes the warp portals not to work over there.

Yours Faithfully,
RDash

**Comment by reigneil** [comment]
i'm about to report this... but then i saw this.

**Comment by Atemo** [comment]
On rAthena every player's step, **npc_touch_areanpc** triggers the first npc load by server in the area, others npcs in range won't be triggered (except defined warp) https://github.com/rathena/rathena/blob/master/src/map/npc.c#L983

For example loading **#warp_2_pass_1** before https://github.com/rathena/rathena/blob/master/npc/re/quests/eden/eden_121_130.txt#L555 will solve the issue for this case.

Differences rathena / aegis : 
- queue event system on aegis (trigger the second script after the end of the first under conditions). On rathena it run only the first script in range load by the server
- on rathena players stop walking when a script is triggered, not on aegis

![aegis_ontouch](https://cloud.githubusercontent.com/assets/5231893/23532106/0cc66fc6-ffaa-11e6-90fe-e2918f7bb53c.png)

**Comment by daisyanne1380** [comment]
same i came across it as well. I can confirm

**Comment by TrueNoir** [comment]
Yeah me as well
