### ISSUE TITLE
Conf directory not found

### ISSUE THREAD

**Issue by ksallberg** [rathena/rathena#194]
Hey guys,

Ubuntu 14.04 here.

After building and installing (using make install, in turn running install.sh), I had the problem that rathena could not find conf/inter_athena.conf

Issue:
Symlink "/opt/rathena/conf" was pointing to a folder with another conf folder in it:
/opt/rathena/etc/rathena/conf/ _instead of_:
/opt/rathena/etc/rathena/conf/conf

Fix:
On my system I just re-pointed /opt/rathena/conf to /opt/rathena/etc/rathena/conf/conf

**Comment by lighta** [comment]
Ye not really a tools but it's system script. (Which is same as our tool).
Thanks for reporting I'll try it right but if you wish you could submit a pull request for install.sh script.

**Comment by ksallberg** [comment]
I went with Hercules instead because it just worked for me.

However, I believe the issue is line 27 and line 33 in https://github.com/rathena/rathena/blob/master/install.sh.

Line 27: Not necessary to create a new conf folder in $PKG_PATH, delete this line, instead just:

Line 33: cp -r conf/ $PKG_PATH/etc/$PKG/

The modified line 33 would copy the conf file from the repo to the place rathena seems to expect.

Do you agree or not? :)

**Comment by Akkarinage** [comment]
@lighta are you still taking care of this issue?

**Comment by lighta** [comment]
To be fair not really.
The name install.sh was depreciated with autotools and such so I wanted to changed it all at once.
But ye I could give a quick fix meanwhile.

**Comment by Lemongrass3110** [comment]
Bumping this for you lighta ;)
