### ISSUE TITLE
GX Skill Rolling Cutter

### ISSUE THREAD

**Issue by Joy-Ro** [rathena/rathena#1940]
Fix for AoE level 1,2,3,4 3x3 and level 5 5x5 Cell Rolling Cutter GX

Old
2036,0,6,4,-1,0x2,1:1:1:1:3,5,1,no,0,0,0,weapon,0,0x0,	GC_ROLLINGCUTTER,Rolling Cutter
New
2036,0,6,4,-1,0x2,3:3:3:3:5,5,1,no,0,0,0,weapon,0,0x0,	GC_ROLLINGCUTTER,Rolling Cutter

**Comment by aleos89** [comment]
The range is already correct, here are the values:
```
layout = -1:special, 0:1*1, 1:3*3, 2:5*5, up to 5:11*11
```

**Comment by Joy-Ro** [comment]
Yes that could be but when i use the default one its not working..
It is not using 3x and 5x aoe cells

**Comment by Lemongrass3110** [comment]
The database entries are a bit misleading, but they are already correct.
![rollingcutter](https://cloud.githubusercontent.com/assets/3517879/22670730/d832f2e4-ecca-11e6-94b5-1e9448842242.png)

We will commit some documentation to clear things up for the future shortly though.

**Comment by RagnarokNova** [comment]
To JoyRO: Note that both of your values are incorrect, you can find the correct ones in rA's git though.
It should be 1:1:1:1:2, not 1:1:1:1:3 and certainly not 3:3:3:3:5
