### ISSUE TITLE
OGH Level Req ISSUE

### ISSUE THREAD

**Issue by Vexillio** [rathena/rathena#1941]
Old Glast Heim Instance

The said instance does not have Level Requirement

Requirements
Base Level:	130

and Treasure room inside the said instance is not usable i mean you cannot enter, after doing right quests.

Source: iRO Wiki

**Comment by Lemongrass3110** [comment]
Could you please check if your issues were fixed in #1554?

**Comment by Lemongrass3110** [comment]
Base Level requirement is fixed in it:
https://github.com/rathena/rathena/pull/1554/files#diff-877efde6bb80b5e4ec8c8d71ce8b2181R23

And treasure room was also added in there:
https://github.com/rathena/rathena/pull/1554/files#diff-877efde6bb80b5e4ec8c8d71ce8b2181R1784

**Comment by Vexillio** [comment]
@Lemongrass3110 look at the old glast heim inside rA's branch in re/instances it only has 

`glast_01,204,273,6	script	Hugin#ghinstance	755,{
	mes "^ff0000This isn't considered a normal progression dungeon. Please note this point.^000000";
	next;
	mes "[Hugin]";
	mes "Huh? You feel like you have seen me in different places? I see. What can I say?";
	next;
	set .@ghins_time, checkquest(12317,PLAYTIME);
	if (.@ghins_time == -1) {`

I will check treasure room later.

**Comment by Lemongrass3110** [comment]
You have to switch to the branch of that pull request.
It is not yet part of master since nobody bothers to give us feedback or test it. :-)
Please also use code tags if you post scripts.

Here's a link to the correct branch containing the changes you want:
https://github.com/rathena/rathena/tree/cleanup/old_glast_heim

**Comment by Vexillio** [comment]
Thank you @Lemongrass3110 
Well the level requirements seems to be official right? im just asking xD btw thank you again!

**Comment by Vexillio** [comment]
And @Lemongrass3110 i have a question regarding the implementation of OGH Hard Mode do i need to make a new issue or can i state the said concern here?

**Comment by Lemongrass3110** [comment]
If you have questions you might refer to the board or our discord channel.
If it really is an issue and it has not been covered by the linked pull request or any other existing issue you can open up a new one. Please try to stick to our issue template though.
