### ISSUE TITLE
Character rename does not refresh clientside name

### ISSUE THREAD

**Issue by Lemongrass3110** [rathena/rathena#1942]
* **rAthena Hash**: 
4623d37

* **Client Date**: 
2011-11-01 and later

* **Server Mode**:
Both

* **Description of Issue**: 
  * Result
     After a successful server side character rename, the name was not refreshed on client side.
![01](https://cloud.githubusercontent.com/assets/3517879/22630779/1828a95a-ec00-11e6-99e7-7a93d5d1ec1c.PNG)
![02](https://cloud.githubusercontent.com/assets/3517879/22630785/20126b24-ec00-11e6-9032-d52c44ddafe8.PNG)
  * Expected Result
      The name should be refreshed in the window.
  * How to Reproduce
      Use some Character Name Change Coupon(12790) items on one of your characters.
      Go back into the character select.
      Rightclick the character and use the rename option.
      Type in a name and submit it.
  * Official Information
      None.

* **Modifications that may affect results**: 
None.

**Comment by RadianFord** [comment]
Works fine!

**Comment by Lemongrass3110** [comment]
Fixed in 7cf081c
