### ISSUE TITLE
setbattleflag no effect

### ISSUE THREAD

**Issue by kukuasir1** [rathena/rathena#1945]
* **rAthena Hash**: 

https://github.com/rathena/rathena/commit/4623d376d064a8f9de2df971e1969379a87476a3

* **Client Date**: 

2015-11-04

* **Server Mode**: 

Renewal

* **Description of Issue**: 
  * Result
server's exp rate not change. 
  * Expected Result
change the server's exp rate.
  * How to Reproduce
when I use `setbattleflag "base_exp_rate",6000;` to change the exp rate, the value was changed( use `getbattleflag("base_exp_rate")`), but server's actual exp rate not change. 
  * Official Information
In Aegis provide a script command `ProvideExp` to change the server exp rate(EP14.3 ep14_3_lastcamp.sc).may be ra can make a new script command for this.
  * _NOTE: none
* **Modifications that may affect results**: 
  none

**Comment by RagnarokNova** [comment]
I believe the exp is calculated when the mob_db is loaded, which would mean you need to do @reloadmobdb for the changes in base_exp_rate to take effect.

**Comment by Lemongrass3110** [comment]
You can see a sample in https://github.com/rathena/rathena/blob/master/npc/custom/etc/floating_rates.txt
It issues a reloadmobdb call after changing the config as @RagnarokNova said.

If this is required by one of the newer scripts we might need to change the behavior though.
