### ISSUE TITLE
Killing Cloud against GTB. Poison Status bypass GTB protection.

### ISSUE THREAD

**Issue by alxalmora** [rathena/rathena#1948]
* **rAthena Hash**: https://github.com/rathena/rathena/blob/e31428df64e6619489d7f3b89a89ac910e73b6dd/src/map/skill.c#L13342

* **Client Date**: 2015-10-29

* **Server Mode**:  Renewal
* **Description of Issue**: 
  * Poison status inflicted by Killing Cloud (Sorcerer Skill) bypass GTB and "bResEff,Eff_Poison,10000";
  * Use GTB or item (2614) go PvP against Sorcerer.

**Comment by aleos89** [comment]
```c
	// Status that are blocked by Golden Thief Bug card or Wand of Hermod
	if (status_isimmune(bl)) {
		switch (type) {
			case SC_DECREASEAGI:
			case SC_SILENCE:
			case SC_COMA:
			case SC_INCREASEAGI:
			case SC_BLESSING:
			case SC_SLOWPOISON:
			case SC_IMPOSITIO:
			case SC_AETERNA:
			case SC_SUFFRAGIUM:
			case SC_BENEDICTIO:
			case SC_PROVIDENCE:
			case SC_KYRIE:
			case SC_ASSUMPTIO:
			case SC_ANGELUS:
			case SC_MAGNIFICAT:
			case SC_GLORIA:
			case SC_WINDWALK:
			case SC_MAGICROD:
			case SC_HALLUCINATION:
			case SC_STONE:
			case SC_QUAGMIRE:
			case SC_SUITON:
			case SC_SWINGDANCE:
				return 0;
		}
	}
```
According to that block of code, SC_POISON is not blocked by GTB.

```c
status_change_start(ss, bl, SC_POISON, 10000, sg->skill_lv, ss->id, 0, 0, skill_get_time2(sg->skill_id, sg->skill_lv), SCSTART_NOTICKDEF|SCSTART_NORATEDEF);
```
According to that block of code, the status rate and duration is not reduced. Last I tested on kRO it wasn't reduced by anything. When I get a chance I'll try to test again.

**Comment by aleos89** [comment]
![gtb_ck](https://cloud.githubusercontent.com/assets/3521753/22710711/685601dc-ed4c-11e6-91d1-3c8118551efc.PNG)
Cloud Kill versus Golden Thief Bug card. I was poisoned.

![reseff_ck](https://cloud.githubusercontent.com/assets/3521753/22710736/7a2fdd1a-ed4c-11e6-81ae-a24054b9fba6.PNG)
Cloud Kill versus An Eye of Dullahan. I was not poisoned.

Result: GTB is working as intended but it seems rate can be reduced for other items versus Cloud Kill poison effect!
