### ISSUE TITLE
Battle damage report over 500,000,00

### ISSUE THREAD

**Issue by keitenai** [rathena/rathena#1951]
* **rAthena Hash**:  e8b9cf0

* **Client Date**:  20151104

* **Server Mode**:  PRE-RE

Issue: 
  * Battle damage report shows over 500,000,00 damage on WoE map.

Configuration:
   hide_woe_damage: yes

Is it even possible to do 500m damage???
Here's a screenshot : 

![Image](https://s27.postimg.org/onaica0hv/Capture.jpg)

**Comment by Darkelfen** [comment]
Nope, it is caused by hide_woe_damage, as a form of "hiding" the damage. I can't tell the exact mechanism because I don't know exactly how the hidding damage part works at all, but that's it.

**Comment by anacondaqq** [comment]
How reproduce the issue? What steps need to follow?

**Comment by Darkelfen** [comment]
Hiding woe damage then receiving damage, some of the numbers displayed are "weird".
