### ISSUE TITLE
Arrullo + Stone Curse

### ISSUE THREAD

**Issue by FrFrMako** [rathena/rathena#1955]
On iRo it's possible put to sleep (arrullo) + stone curse at same time in pvp. 
In rA is impossible.
Is intended or is a iRo custom thing?

**Comment by Playtester** [comment]
I can confirm this.

Basically there are status changes of the type "BODY". You can only have one "BODY" status change at the same time.

Body status changes are: IMPRISON, STONECURSE, FREEZING, STUN, SLEEP and BURNING

Arrullo gives the status change "DEEPSLEEP" however, which is of the type "HANDICAPSTATE". Those can be freely stacked on top and don't block other status changes.
