### ISSUE TITLE
Skills not working

### ISSUE THREAD

**Issue by Vexillio** [rathena/rathena#1957]
Speak Quicken (RG/Paladin) - Not working ( Does'nt give ASPD )
Imposito Manus - Not Working ( Does'nt give ATK )

MODE: RENEWAL

**Comment by Playtester** [comment]
Make sure that you have high AGI when testing, have no other ASPD buff and have a 2-handed spear equipped.

ATK increase from Imposito Manus is not visible in status screen. It gets added during damage calculation.

**Comment by Vexillio** [comment]
Okay will check this later.

**Comment by Akkarinage** [comment]
Can you also please use the Issue template in future.

**Comment by Vexillio** [comment]
@Akkarinage Okay sorry.

**Comment by aleos89** [comment]
As @Playtester suggested. In renewal you need high agility before you see any noticeable bonuses for ASPD. Also the ATK bonus from Impositio Manus does not show in the status window.
