### ISSUE TITLE
Player sitting position

### ISSUE THREAD

**Issue by RadianFord** [rathena/rathena#1958]
* **rAthena Hash**: ce1429d4ff16684451869a961b8c09f692d303ac

* **Client Date**: 2013-12-23cRagexe

* **Server Mode**: Pre Renewal

* **Description of Issue**: Scenario Player 1 sitting while Player 2 cast Bowling Bash but miss so player 1 is on Stand up position.
  * Result - Player 1 should be able to walk because its not sitting mode anymore right? but it seems the sitting icon is still showing up for Player 1.

* **Modifications that may affect results**: No modifications applied.

**Comment by anacondaqq** [comment]
Hi @RadianFord your problem is totally the same like mine: https://github.com/rathena/rathena/issues/1927
