### ISSUE TITLE
Wrong Information about whodrops command

### ISSUE THREAD

**Issue by RadianFord** [rathena/rathena#1959]
* **rAthena Hash**: ca051d185eae2b2f3a62684af1926be3b369b304

* **Client Date**: 2013-12-23cRagexe

* **Server Mode**: Pre renewal

* **Description of Issue**: Wrong Information given.
  * How to Reproduce - I use whodrops (7513) Pocket Watch which is dropped by Kiel D-01 but the command prompts `Kiel D-01 (1734). 30%` which is `Orc Archer Bow`

**Comment by RadianFord** [comment]
Ops sorry about this hahaha!

**Comment by Lemongrass3110** [comment]
For closing it? Or for what?

**Comment by RadianFord** [comment]
@Lemongrass3110 there was no problem with the whodrops command it was correct i thought `MonsterName`+` Item#`+`Chance`
