### ISSUE TITLE
Fear status

### ISSUE THREAD

**Issue by MrAntares** [rathena/rathena#196]
Git Version: **12628 - 2014-12-04 05:04:30 (luciar)**
Client Date: **2012-04-10**
Src Mods: **NONE**
General settings: 
- **Full Renewal**
- **1/1/1/1/1 rate**
- **PK server (not in towns, above lvl 30)**
- **PVP ATK/Skill modifers: 100%**
- **WOE ATK/Skill modifers: rA default**
- **Official walk path and stacking**
- **Exp and drop penalty table values below 100% set to 100%**
- **Party and attacker exp bonus: +40%**
- More at (Hungarian, use translate): http://wiki.ragna.ro/

How to reproduce: **Use a skill that deals the status**
Description:

I'm not sure if it's the status or the skills inflicting it, but I am unable to cause fear status to anyone. Dragon Howling and Wind Cutter is what I tried, but no success even against a 1st class low stat player or any monster.

**Comment by cydh** [comment]
just tested, it's work
2 secs can't move, and 15 secs HIT & FLEE reduced. no status resist calculation.

**Comment by MrAntares** [comment]
Do you see the status icon as well? :O

**Comment by cydh** [comment]
how can I see blank icon?
````
set_sc( RK_DRAGONHOWLING	, SC_FEAR		, SI_BLANK			, SCB_FLEE|SCB_HIT );
....
set_sc( RK_WINDCUTTER		, SC_FEAR		, SI_BLANK			, SCB_FLEE|SCB_HIT );
````

**Comment by MrAntares** [comment]
http://irowiki.org/wiki/File:I_Fear.png ?

**Comment by cydh** [comment]
it's a pleasure if u can get the icon name or ID for implementation. Cna check for lua efstid, or the client files. xD
or try use in-game to try each Icon. :P
`@send 0x043f  W<SI_ID> L<account_id> B1 L5000 L1 L1 L1`
or this for 20120618
`@send 0x0983  W<SI_ID> L<account_id> B1 L5000 L5000 L1 L1 L1`
