### ISSUE TITLE
Enchant Deadly Poison and weapon swap.

### ISSUE THREAD

**Issue by Barigas** [rathena/rathena#1960]
I have played NovaRO, and found out that EDP does not get dispelled on weapon swap. As I remember, in renewal it is getting dispelled. Please, confirm someone.

**Comment by Akkarinage** [comment]
We don't check the validity of of private server configurations - as your question isn't quite an issue it should be directed to the forums. You're as capable as anyone else to check what happens.
Please use the provided Issue template in future.
