### ISSUE TITLE
[ADDING CUSTOM]After fixing Unknown Item, Now items are not showing. 

### ISSUE THREAD

**Issue by Kissesss** [rathena/rathena#1961]
![screenmyth001](https://cloud.githubusercontent.com/assets/25754469/22903977/86ce9424-f1ef-11e6-9f3d-74cca154aaee.jpg)
* **Client Date**: 2012-10-04

Which mode does your server use:  Renewal

* **Description of Issue**:  Item not showing
  - As I was done fixing "Unkown Items" another one came in. Item now is not showing.

Hope you guys can help me! Thanks! xoxo

**Comment by aleos89** [comment]
Sorry, but this isn't an issue with rAthena. Please use the forum for support with adding items.
