### ISSUE TITLE
Missing ITEMID_YELLOW_GEMSTONE in itemdb.h

### ISSUE THREAD

**Issue by anacondaqq** [rathena/rathena#1962]
https://github.com/rathena/rathena/blob/master/src/map/itemdb.h#L56

*Please add to itemdb.h*
after 
`ITEMID_EMPERIUM						= 714,` 
line:
`ITEMID_YELLOW_GEMSTONE				= 715,`

```
	ITEMID_EMPERIUM						= 714,
	ITEMID_YELLOW_GEMSTONE				= 715,
	ITEMID_RED_GEMSTONE					= 716,
	ITEMID_BLUE_GEMSTONE				= 717,
	ITEMID_ORIDECON_STONE				= 756,
```

**Comment by Akkarinage** [comment]
Issue template is there for a reason. You could always submit the change yourself as a PR and list what it fixes (currently open issues).

**Comment by Lemongrass3110** [comment]
Any reason for it? You know that we removed it for a reason do you?

**Comment by aleos89** [comment]
As @Lemongrass3110 stated, it was removed in d095fe7.

**Comment by anacondaqq** [comment]
ah, i see, thank you very much for information, as i understand it's replaced via `IG_Gemstone`, i will know. I'm just updating the rAthena at my local branch, and i found something very interesting and missing (some warnings appears, and then i checked lines around and found it. Closing then. It's not a problem, and no errors or warnings on latest rAthena hash. Thank you again for deep detailed information and time for searching patch.
