### ISSUE TITLE
Homunculus Delete Button

### ISSUE THREAD

**Issue by Hactus** [rathena/rathena#1963]
* **rAthena Hash**: ce1429d4ff16684451869a961b8c09f692d303ac
* **Client Date**:  2015-10-29-RE
* **Server Mode**: RE

* **Description of Issue**:   The delete homunculus button just don't appear. The mercenary despension appear, but the homunculus delete button no.
I changed the Client to 2015 11 04 and the packet version to 55 to test and the error persist

![screenragnarokgo002 jpg 2a8f3ff64f2aeeb441564a093082befd](https://cloud.githubusercontent.com/assets/25515009/22940620/4bcd7fd4-f2c1-11e6-8d1d-c0e491f7c21b.jpg)

**Comment by aleos89** [comment]
Can you check to make sure you have the button image in your GRF? Since you are translating the images to another language, I can only think of you missing that button image.

**Comment by Hactus** [comment]
Yes I have the images, the del button don't need translation in this situation.

**Comment by aleos89** [comment]
How about the "Hab." button. Is that the correct size and not pushing the Delete button off?

**Comment by Hactus** [comment]
I just deleted what was written in photoshop and I wrote over, I did not make a new button for it, so I did not change the sizes

**Comment by Hactus** [comment]
Look, I go back the buttons and the error persist:

![screenragnarokgo011](https://cloud.githubusercontent.com/assets/25515009/22942087/cbc74e86-f2c6-11e6-830d-dd3c93e8c9cf.jpg)

**Comment by anacondaqq** [comment]
My hash:  196017c9c4fec0226daae3cf36f4ed37e101270c
Mechanic: pre-re
Client: 2015-11-04aRagexe, packet obf disabled, client data from translation project.
**Can't confirm...**
![default](https://cloud.githubusercontent.com/assets/9905636/22942890/0c871c30-f2f4-11e6-86e4-98643ba05549.png)

**Comment by Hactus** [comment]
I re-diff my hexed in nemo with the same cofings and the button appear again, I can't explain the why, but are functional again.. Thanks for the support.
