### ISSUE TITLE
Wrong skill effect from Shoes of Valor (IDRO item)

### ISSUE THREAD

**Issue by hendra814** [rathena/rathena#1966]
client date 2015-11-04
Server Mode Renewal

Item Shoes of Valor (2482) have wrong skill effect.
it's give heal lvl 1, it's suppose increase agi lvl 1

**Comment by aleos89** [comment]
Maybe @cydh can confirm this since he was the one who implemented it.

**Comment by cydh** [comment]
yes it must be AL_INCAGI Lv 1
