### ISSUE TITLE
Monster check box not showing mob name on map

### ISSUE THREAD

**Issue by hendra814** [rathena/rathena#1967]
Client date 2015-11-04
Server Mode Renewal

when click on monster check box, it's only show map name, not showing monster name like client 2014 or 2013, already tried with 2015-10-29, still the same.

![screenrathena000](https://cloud.githubusercontent.com/assets/9587609/23005121/1531456a-f42d-11e6-81c7-af1a8f830f6f.jpg)

here from 2013-08-07
![screenrathena001](https://cloud.githubusercontent.com/assets/9587609/23005625/c8eec062-f42f-11e6-8245-d18ddc82d22a.jpg)

**Comment by aleos89** [comment]
This feature is totally client-sided, and is dependent upon any bugs/changes in the client that may break it. Check your LUA too and images to make sure you have them in your data properly. Other than that, this doesn't relate to rAthena.

**Comment by hendra814** [comment]
Ok, thanks
and i'm already found it.
at this folder data\luafiles514\lua files\worldviewdata\
file worldviewdata_language.lub
> WORLD_MSGID = {
	MSI_1_THA_T01 = "Thanatos Tower - Lower Level Museum Entrance",
	MSI_1_THA_T02 = "Thanatos Tower - Lower Level Museum",
	MSI_1_THA_T03 = "Thanatos Tower - Lower Level Abandoned",
	MSI_1_THA_T04 = "Thanatos Tower - Lower Level Abandoned",
	MSI_1_THA_T05 = "Thanatos Tower - Upper Level",
	MSI_1_THA_T06 = "Thanatos Tower - Upper Level",
	MSI_1_THA_T07 = "Thanatos Tower - Upper Level Angel",
	MSI_1_THA_T08 = "Thanatos Tower - Upper Level Angel",
	MSI_1_THA_T09 = "Thanatos Tower - Upper Level Agony",
	MSI_1_THA_T10 = "Thanatos Tower - Upper Level Sadness",
	MSI_1_THA_T11 = "Thanatos Tower - Upper Level Despair",
	MSI_1_THA_T12 = "Thanatos Tower - Upper Level Hatred",
	MSI_2_MAG_DUN01 = "Nogg Road 1F",
	MSI_2_MAG_DUN02 = "Nogg Road 2F",
	MSI_3_ICE_DUN01 = "Ice Cave 1F",
	MSI_3_ICE_DUN02 = "Ice Cave 2F",
	MSI_3_ICE_DUN03 = "Ice Cave 3F",
	MSI_4_RA_SAN01 = "Holy Ground 1F North",
	MSI_4_RA_SAN02 = "Holy Ground 1F West",
	MSI_4_RA_SAN03 = "Holy Ground 1F East",
	MSI_4_RA_SAN04 = "Holy Ground 1F South",
	MSI_4_RA_SAN05 = "Holy Ground 2F Center",
	MSI_5_ABYSS_01 = "Abyss Lake Underground Cave 1F",
	MSI_5_ABYSS_02 = "Abyss Lake Underground Cave 2F",
	MSI_5_ABYSS_03 = "Abyss Lake Underground Cave 3F",
	MSI_6_JUPEROS_01 = "Ruins of Juperos Outside",
	MSI_6_JUPEROS_02 = "Ruins of Juperos Inside",
	MSI_6_JUPE_CORE = "Center of Juperos",
	MSI_6_VER_EJU = "Juperos Eastern Ruin",
	MSI_6_VER_TUNN = "Verus Outskirts Tunnel",
	MSI_6_VERUS03 = "Verus Central Square",
	MSI_6_VERUS04 = "Verus Excavation Site",
	MSI_7_KH_DUN01 = "Robot Doll Factory 1F",
	MSI_7_KH_DUN02 = "Robot Doll Factory 2F",
	MSI_8_ALDE_DUN01 = "Clock Tower B 1F",
	MSI_8_ALDE_DUN02 = "Clock Tower B 2F",
	MSI_8_ALDE_DUN03 = "Clock Tower B 3F",
	MSI_8_ALDE_DUN04 = "Clock Tower B 4F",
	MSI_8_C_TOWER1 = "Clock Tower 1F",
	MSI_8_C_TOWER2 = "Clock Tower 2F",
	MSI_8_C_TOWER3 = "Clock Tower 3F",
	MSI_8_C_TOWER4 = "Clock Tower 4F",
	MSI_9_EIN_DUN01 = "Mine Dungeon 1F",
	MSI_9_EIN_DUN02 = "Mine Dungeon 2F",
	MSI_10_MJO_DUN01 = "Mjolnir Dead Pit 1F",
	MSI_10_MJO_DUN02 = "Mjolnir Dead Pit 2F",
	MSI_10_MJO_DUN03 = "Mjolnir Dead Pit 3F",
	MSI_11_LHZ_DUN01 = "Somatology Laboratory B 1F",
	MSI_11_LHZ_DUN02 = "Somatology Laboratory B 2F",
	MSI_11_LHZ_DUN03 = "Somatology Laboratory B 3F",
	MSI_12_THOR_V01 = "Thor Volcano Dungeon 1F",
	MSI_12_THOR_V02 = "Thor Volcano Dungeon 2F",
	MSI_12_THOR_V03 = "Thor Volcano Dungeon 3F",
	MSI_13_GL_CAS01 = "Glast Heim Castle 1F",
	MSI_13_GL_CAS02 = "Glast Heim Castle 2F",
	MSI_13_GL_CHURCH = "Glast Heim St. Abbey",
	MSI_13_GL_CHYARD = "Glast Heim Churchyard",
	MSI_13_GL_DUN01 = "Glast Heim Underground Cave 1F",
	MSI_13_GL_DUN02 = "Glast Heim Underground Cave 2F",
	MSI_13_GL_IN01 = "Glast Heim Inside",
	MSI_13_GL_KNT01 = "Inside Glast Heim Chivalry 1F",
	MSI_13_GL_KNT02 = "Inside Glast Heim Chivalry 2F",
	MSI_13_GL_PRISON = "Glast Heim Underground Prison 1F",
	MSI_13_GL_PRISON1 = "Glast Heim Underground Prison 2F",
	MSI_13_GL_SEW01 = "Glast Heim Culvert 1F",
	MSI_13_GL_SEW02 = "Glast Heim Culvert 2F",
	MSI_13_GL_SEW03 = "Glast Heim Culvert 3F",
	MSI_13_GL_SEW04 = "Glast Heim Culvert 4F",
	MSI_13_GL_STEP = "Glast Heim Staircase Dungeon",
	MSI_14_GEF_DUN00 = "Geffen Dungeon 1F",
	MSI_14_GEF_DUN01 = "Geffen Dungeon 2F",
	MSI_14_GEF_DUN02 = "Geffen Dungeon 3F",
	MSI_15_GEF_DUN03 = "Geffenia",
	MSI_16_NIFLHEIM = "Nifflheim, Realm of the Dead",
	MSI_16_NIF_FILD01 = "Skellington, a Solitary Village in Nifflheim",
	MSI_16_NIF_FILD02 = "Vally of Gyoll",
	MSI_17_ORCSDUN01 = "Underground Orc Dungeon  1F",
	MSI_17_ORCSDUN02 = "Underground Orc Dungeon  2F",
	MSI_18_MOC_PRYD01 = "Inside Pyramid 1F",
	MSI_18_MOC_PRYD02 = "Inside Pyramid 2F",
	MSI_18_MOC_PRYD03 = "Inside Pyramid 3F",
	MSI_18_MOC_PRYD04 = "Inside Pyramid 4F",
	MSI_18_MOC_PRYD05 = "Inside Pyramid B 1F",
	MSI_18_MOC_PRYD06 = "Inside Pyramid B 2F",
	MSI_19_IN_SPHINX1 = "Sphinx B 1F",
	MSI_19_IN_SPHINX2 = "Sphinx B 2F",
	MSI_19_IN_SPHINX3 = "Sphinx B 3F",
	MSI_19_IN_SPHINX4 = "Sphinx B 4F",
	MSI_19_IN_SPHINX5 = "Sphinx B 5F",
	MSI_20_PRT_SEWB1 = "Prontera Culvert 1F",
	MSI_20_PRT_SEWB2 = "Prontera Culvert 2F",
	MSI_20_PRT_SEWB3 = "Prontera Culvert 3F",
	MSI_20_PRT_SEWB4 = "Prontera Culvert 4F",
	MSI_21_IZ_DUN00 = "Izlude Undersea Tunnel 1F",
	MSI_21_IZ_DUN01 = "Izlude Undersea Tunnel 2F",
	MSI_21_IZ_DUN02 = "Izlude Undersea Tunnel 3F",
	MSI_21_IZ_DUN03 = "Izlude Undersea Tunnel 4F",
	MSI_21_IZ_DUN04 = "Izlude Undersea Tunnel 5F",
	MSI_21_IZ_DUN05 = "Izlude Undersea Tunnel 6F",
	MSI_22_PAY_DUN00 = "Payon Cave 1F",
	MSI_22_PAY_DUN01 = "Payon Cave 2F",
	MSI_22_PAY_DUN02 = "Payon Cave 3F",
	MSI_22_PAY_DUN03 = "Payon Cave 4F",
	MSI_22_PAY_DUN04 = "Payon Cave 5F",
	MSI_23_TREASURE01 = "Alberta Sunken Ship 1F",
	MSI_23_TREASURE02 = "Alberta Sunken Ship 2F",
	MSI_24_TUR_DUN02 = "Turtle Island Dungeon",
	MSI_24_TUR_DUN03 = "Good Turtles Village",
	MSI_24_TUR_DUN04 = "Turtle Palace",
	MSI_24_TUR_DUN05 = "Underground swamp zone",
	MSI_25_BEACH_DUN = "Karu, the West cave",
	MSI_26_BEACH_DUN2 = "Ruande the northern cave",
	MSI_27_BEACH_DUN3 = "Mao, the East Cave",
	MSI_28_ANTHELL01 = "Morocc Ant Hell Dungeon 1F",
	MSI_28_ANTHELL02 = "Morocc Ant Hell Dungeon 2F",
	MSI_29_ABBEY01 = "Cursed Monastery 1F",
	MSI_29_ABBEY02 = "Cursed Monastery B 1F",
	MSI_29_ABBEY03 = "Cursed Monastery B 2F",
	MSI_30_PRT_MAZE01 = "Labyrinth Forest 1F",
	MSI_30_PRT_MAZE02 = "Labyrinth Forest 2F",
	MSI_30_PRT_MAZE03 = "Labyrinth Forest 3F",
	MSI_100_HUGEL = "Hugel, the Quaint Garden Village",
	MSI_100_HU_FILD01 = "Novus",
	MSI_100_HU_FILD02 = "Novus",
	MSI_100_HU_FILD04 = "Novus",
	MSI_100_HU_FILD05 = "Novus",
	MSI_100_HU_FILD06 = "Shellfish",
	MSI_100_EIN_FILD01 = "Einbroch",
	MSI_100_YUNO_FILD02 = "Sleeper",
	MSI_100_YUNO_FILD03 = "Harpy",
	MSI_100_YUNO_FILD04 = "Harpy",
	MSI_100_YUNO_FILD06 = "Sleeper",
	MSI_100_YUNO = "Juno, the capital of Schwarzwald Republic",
	MSI_101_RACHEL = "Capital of Arunafeltz States, Rachel",
	MSI_101_RA_TEMPLE = "Freya Grand Temple - Cheshrumnir",
	MSI_101_RA_FILD01 = "Desert Wolf",
	MSI_101_RA_FILD03 = "Hill Wind",
	MSI_101_RA_FILD04 = "Hill Wind",
	MSI_101_RA_FILD05 = "Kobold",
	MSI_101_RA_FILD08 = "Anacondaq",
	MSI_101_RA_FILD12 = "Roween",
	MSI_102_RA_FILD06 = "Kobold Archer",
	MSI_102_LIGHTHALZEN = "Lightharlzen, the City-State of Prosperity",
	MSI_102_LHZ_FILD01 = "Rafflesia",
	MSI_102_LHZ_FILD02 = "Stem Worm",
	MSI_102_LHZ_FILD03 = "Breeze",
	MSI_102_EIN_FILD03 = "Metaling",
	MSI_102_EIN_FILD04 = "Venomous",
	MSI_102_EIN_FILD05 = "Einbroch Field",
	MSI_102_EIN_FILD06 = "Einbroch Field",
	MSI_102_EIN_FILD07 = "Metaling",
	MSI_102_EIN_FILD08 = "Breeze",
	MSI_102_EIN_FILD09 = "Metaling",
	MSI_102_EINBECH = "Einbech, the mining village",
	MSI_102_EINBROCH = "Einbroch, the city of steel",
	MSI_103_YUNO_FILD01 = "Geographer",
	MSI_103_YUNO_FILD07 = "Goat",
	MSI_103_YUNO_FILD08 = "Grand Peco",
	MSI_103_YUNO_FILD09 = "Grand Peco",
	MSI_103_YUNO_FILD11 = "Goat",
	MSI_103_YUNO_FILD12 = "Geographer",
	MSI_103_ALDE_GLD = "Luina the satellite of Al De Baran",
	MSI_103_ALDEBARAN = "Al De Baran",
	MSI_103_MJOLNIR_12 = "Dustiness",
	MSI_104_ODIN_TEM01 = "Plasma",
	MSI_104_ODIN_TEM02 = "Frus",
	MSI_104_ODIN_TEM03 = "Skeggiold",
	MSI_105_ARU_GLD = "Valfreyja",
	MSI_105_VEINS = "Veins, the Canyon Village",
	MSI_105_VE_FILD01 = "Galion",
	MSI_105_VE_FILD02 = "Drosera",
	MSI_105_VE_FILD03 = "Magmaring",
	MSI_105_VE_FILD04 = "Muscipular",
	MSI_105_VE_FILD06 = "Veins Field",
	MSI_105_VE_FILD07 = "Stapo",
	MSI_106_MJOLNIR_01 = "Caramel",
	MSI_106_GLAST_01 = "Glast Heim",
	MSI_106_GEF_FILD04 = "Madragora",
	MSI_106_GEF_FILD05 = "Creamy",
	MSI_106_GEF_FILD06 = "Petit",
	MSI_106_GEF_FILD07 = "Pupa",
	MSI_106_GEF_FILD08 = "Petit",
	MSI_106_GEF_FILD09 = "Coco",
	MSI_106_GEF_FILD10 = "Orc Warrior",
	MSI_106_GEF_FILD11 = "Goblin",
	MSI_106_GEF_FILD13 = "Britoniah",
	MSI_106_GEFFEN = "Geffen",
	MSI_107_MJOLNIR_02 = "ELDER_WILOW",
	MSI_107_MJOLNIR_03 = "Side Winder",
	MSI_107_MJOLNIR_04 = "Driller",
	MSI_107_MJOLNIR_05 = "Argiope",
	MSI_107_MJOLNIR_06 = "Poison Spore",
	MSI_107_MJOLNIR_07 = "Savage",
	MSI_107_MJOLNIR_08 = "Beetle",
	MSI_107_MJOLNIR_09 = "Savage Babe",
	MSI_107_MJOLNIR_10 = "Argos",
	MSI_107_MJOLNIR_11 = "Argiope",
	MSI_107_PRT_FILD00 = "Roda Frog",
	MSI_107_PRT_FILD01 = "Lunatic",
	MSI_107_PRT_FILD02 = "Stainer",
	MSI_107_PRT_FILD03 = "YoYo",
	MSI_107_PRT_MONK = "St. Capitolina Abbey",
	MSI_107_GEF_FILD00 = "Chon Chon",
	MSI_108_PRT_FILD04 = "Ambernite",
	MSI_108_PRT_FILD05 = "Hornet",
	MSI_108_PRT_FILD06 = "Fabre",
	MSI_108_PRT_FILD07 = "Rocker",
	MSI_108_PRT_FILD08 = "Poring",
	MSI_108_PRT_FILD09 = "Magnolia",
	MSI_108_PRT_FILD10 = "Elder Willow",
	MSI_108_PRT_FILD11 = "Goblin Archer",
	MSI_108_PRONTERA = "Prontera City, Capitol of Rune-Midgard",
	MSI_108_IZLUDE = "Izlude Town",
	MSI_108_IZLU2DUN = "Byalan Island",
	MSI_108_GEF_FILD01 = "Roda Frog",
	MSI_108_GEF_FILD02 = "Coco",
	MSI_108_GEF_FILD03 = "Orc Lady",
	MSI_108_MOC_FILD01 = "Muka",
	MSI_108_PAY_ARCHE = "Archer Village",
	MSI_108_PAY_FILD04 = "Poporing",
	MSI_109_NAMELESS_N = "Hell Poodle",
	MSI_109_UM_FILD01 = "Drayad",
	MSI_109_UM_FILD02 = "Wootan Fighter",
	MSI_109_UM_FILD03 = "Parasite",
	MSI_109_UM_FILD04 = "Wild Rose",
	MSI_109_UMBALA = "Wootan Tribe's Village, Umbala",
	MSI_109_COMODO = "Beach town,Comodo",
	MSI_109_CMD_FILD01 = "Grobe",
	MSI_109_CMD_FILD02 = "Seal",
	MSI_109_CMD_FILD03 = "Alligator",
	MSI_109_CMD_FILD04 = "Sea Otter",
	MSI_110_CMD_FILD06 = "Golem",
	MSI_110_CMD_FILD07 = "Raggler",
	MSI_110_CMD_FILD08 = "Andre",
	MSI_110_CMD_FILD09 = "Metaller",
	MSI_110_MOC_FILD07 = "Drops",
	MSI_110_MOC_FILD11 = "Baby Desert Wolf",
	MSI_110_MOC_FILD12 = "Picky",
	MSI_110_MOC_FILD16 = "Sandman",
	MSI_110_MOC_FILD17 = "Hode",
	MSI_110_MOC_FILD18 = "Scorpion",
	MSI_110_MOC_FILD19 = "Sograt Desert",
	MSI_110_MOC_RUINS = "Morroc Ruins",
	MSI_110_MOROCC = "Morroc Town",
	MSI_111_MOC_FILD02 = "Peco Peco",
	MSI_111_MOC_FILD03 = "Wolf",
	MSI_111_MOC_FILD13 = "Steel Chonchon",
	MSI_111_PAYON = "Payon Town",
	MSI_111_PAY_FILD01 = "Willow",
	MSI_111_PAY_FILD02 = "Snake",
	MSI_111_PAY_FILD03 = "Fabre",
	MSI_111_PAY_FILD06 = "Wormtail",
	MSI_111_PAY_FILD07 = "Bigfoot",
	MSI_111_PAY_FILD08 = "Spore",
	MSI_111_PAY_FILD09 = "Horn",
	MSI_111_PAY_FILD10 = "Greatest General",
	MSI_111_ALBERTA = "Alberta",
	MSI_111_ALB2TREA = "Alberta Island",
	MSI_111_TUR_DUN01 = "Lunar Rabbit",
	MSI_1_ECL_TDUN01 = "Bifrost Floor 1F",
	MSI_1_ECL_TDUN02 = "Bifrost Floor 2F",
	MSI_1_ECL_TDUN03 = "Bifrost Floor 3F",
	MSI_2_DIC_DUN01 = "Kamidal Tunnel",
	MSI_2_DIC_DUN02 = "Scaraba Hall",
	MSI_3_DIC_DUN03 = "Scaraba Hall 2F",
	MSI_3_MORA = "Mora Village",
	MSI_4_MORO_CAV = "Flame cave",
	MSI_4_MORO_VOL = "Flame Basin",
	MSI_100_ECLAGE = "Eclage",
	MSI_100_ECL_FILD01 = "Manblite",
	MSI_100_BIF_FILD02 = "Little Fatum",
	MSI_100_BIF_FILD01 = "Miming",
	MSI_100_SPLENDIDE = "Splendide",
	MSI_100_SPL_FILD01 = "Dark Pinguicula",
	MSI_100_SPL_FILD02 = "Pinguicula",
	MSI_100_SPL_FILD03 = "Luciola Vespa",
	MSI_100_MID_CAMP = "Rune Midgard Allied Forces Post",
	MSI_100_MAN_FILD01 = "Nepenthes",
	MSI_100_MAN_FILD03 = "Hillslion",
	MSI_100_MAN_FILD02 = "Bradium Golem",
	MSI_100_MANUK = "Manuk",
	MSI_100_DICASTES02 = "Dicastes Diel",
	MSI_100_DICASTES01 = "El Dicastes, the Sapha Capital",
	MSI_100_DIC_FILD01 = "Centipede",
	MSI_100_DIC_FILD02 = "Dolomedes",
	MSI_DUN1 = "Thanatos Tower",
	MSI_DUN2 = "Lava Dungeon",
	MSI_DUN3 = "Ice Dungeon",
	MSI_DUN4 = "Sacred Place",
	MSI_DUN5 = "Abys Lake",
	MSI_DUN6 = "Yuperos",
	MSI_DUN7 = "Kill Hire Academy",
	MSI_DUN8 = "Clock Tower Dungeon",
	MSI_DUN9 = "Mine Dungeon",
	MSI_DUN10 = "Abandoned Mine Dungeon",
	MSI_DUN11 = "Biolab Dungeon",
	MSI_DUN12 = "Thor Volcano",
	MSI_DUN13 = "Glastheim",
	MSI_DUN14 = "Geffen Dungeon",
	MSI_DUN15 = "Geffenia Dungeon",
	MSI_DUN16 = "Niffelheim Dungeon",
	MSI_DUN17 = "Orc Dungeon",
	MSI_DUN18 = "Pyramid Dungeon",
	MSI_DUN19 = "Sphinx Dungeon",
	MSI_DUN20 = "Undergound Canal Dungeon",
	MSI_DUN21 = "Izlude Dungeon",
	MSI_DUN22 = "Payon Dungeon",
	MSI_DUN23 = "Lost Ship",
	MSI_DUN24 = "Turtle Island",
	MSI_DUN25 = "Comodo Dungeon",
	MSI_DUN26 = "Comodo Dungeon",
	MSI_DUN27 = "Comodo Dungeon",
	MSI_DUN28 = "Ant Hell Dungeon",
	MSI_DUN29 = "Namelese",
	MSI_DUN30 = "Prontera Maze",
	MSI_DUN38 = "Bifrost Tower",
	MSI_DUN39 = "Scaraba Dungeon",
	MSI_DUN40 = "Mora Village",
	MSI_DUN41 = "Flame Cave",
	MSI_100_AMATSU = "Amatsu, the Land of Destiny",
	MSI_100_AMA_FILD01 = "Amatsu Field",
	MSI_1_AMA_DUN01 = "Tatami Maze",
	MSI_1_AMA_DUN02 = "Battle Field in the Underground Forest",
	MSI_1_AMA_DUN03 = "Amatsu Underground Shrine",
	MSI_101_GONRYUN = "Gonryun, the Hermit Land",
	MSI_101_GON_FILD01 = "Gonryun Field",
	MSI_101_GON_DUN02 = "Hermit's Checkers",
	MSI_2_GON_DUN01 = "Shrine of Gonryun Queen",
	MSI_3_GON_DUN03 = "Arcadia",
	MSI_102_LOUYANG = "Louyang, the highland",
	MSI_102_LOU_FILD01 = "Louyang Field",
	MSI_102_DUN01 = "The Royal Tomb",
	MSI_4_LOU_DUN02 = "Inside the Royal Tomb",
	MSI_4_LOU_DUN03 = "Suei Long Gon",
	MSI_103_AYOTHAYA = "Ayotaya",
	MSI_103_AYO_FILD01 = "Ayotaya Field",
	MSI_5_AYO_DUN01 = "Ancient Shrine Maze",
	MSI_5_AYO_DUN02 = "Inside Ancient Shrine",
	MSI_DUN31 = "Amatsu Dungeon",
	MSI_DUN32 = "Gonryun Dungeon",
	MSI_DUN33 = "Louyang Dungeon",
	MSI_DUN34 = "Ayothaya Dungeon",
	MSI_100_MOSCOVIA = "Moscovia",
	MSI_100_MOSK_FILD02 = "Okrestnosti of Moscovia",
	MSI_100_MOSK_DUN01 = "Les Forest",
	MSI_100_MOSK_DUN02 = "Temny Forest",
	MSI_100_MOSK_DUN03 = "Dremuci Forest",
	MSI_101_BRASILIS = "Brasilis",
	MSI_101_BRA_FILD01 = "Tukan",
	MSI_1_BRA_DUN01 = "Beyond the Waterfall",
	MSI_1_BRA_DUN02 = "Beyond the Waterfall Inside",
	MSI_102_DEWATA = "Village",
	MSI_102_DEW_FILD01 = "Raplesia Anoldi",
	MSI_102_DEW_DUN01 = "Comodo",
	MSI_2_DEW_DUN02 = "Eastana Cave",
	MSI_103_MALAYA = "Port Malaya",
	MSI_103_MA_FILD01 = "Baryo Mahiwaga",
	MSI_103_MA_FILD02 = "Forest",
	MSI_103_MA_SCENE01 = "Bakonawa Lake",
	MSI_3_MA_DUN01 = "Bangungot Hospital 1F",
	MSI_DUN35 = "Brasilis Dungeon",
	MSI_DUN36 = "Dewata Dungeon",
	MSI_DUN37 = "Port Malaya Dungeon",
	MSI_100_DALI = "Dimension Crack",
	MSI_100_DALI02 = "Dimension Crack",
	MSI_DUN42 = "Dragon's Nest",
	MSI_100_LASAGNA = "Village",
	MSI_100_LASA_FILD01 = "Eggring",
	MSI_100_LASA_FILD02 = "Sweet Roda Frog",
	MSI_1_LASA_DUN01 = "Dragon's Nest 1F",
	MSI_1_LASA_DUN02 = "Dragon's Nest 2F",
	MSI_1_LASA_DUN03 = "Dragon's Nest 3F",
	MSI_112_MALANGDO = "Malangdo",
	MSI_DUN43 = "Starry Coral Area",
	MSI_43_MAL_DUN01 = "Starry Coral Area"
}
