### ISSUE TITLE
Cash Shop Issue

### ISSUE THREAD

**Issue by RadianFord** [rathena/rathena#1971]
* **rAthena Hash**: 93f74cf567b0ce949d3853e528c71b2be7374c62

* **Client Date**: 2013-12-23cRagexe

* **Server Mode**: Pre Renewal

* **Description of Issue**: Item delete on Cash Shop or /limitedsale will auto disconnect or crash the server.
  * Result: I manually added the patch and check everything i might be wrong or miss something.
  * Expected Result: Item should be seen in the limited category right? or im wrong with this one?
  * How to Reproduce: Okay so adding item on limited was succesful it was stated in the message that registration was successful, now dont close the window and click the Item Delete button it will shut down the server and will result this error `[Error]: Server received crash signal! Attempting to save all online characters!`

  

* **Modifications that may affect results**: No modification related with this issue.

**Comment by Lemongrass3110** [comment]
You should only be able to add sales in the future and the items will be added to the cashshop limited tab as soon as that point of time in the future arrives. Until then you cannot see them anywhere except looking in the database. I know this sucks, but this is how Gravity's client works.

**Comment by RadianFord** [comment]
Thanks @Lemongrass3110 for the fast fix for this!
