### ISSUE TITLE
Pet_db to sql

### ISSUE THREAD

**Issue by daisyanne1380** [rathena/rathena#1972]
I remember like 4 years ago it was suggested that pet_db would be moved to sql. What ever happen to that idea. Since pet_db has so many fields, wouldn't it be more convenient to have it as SQL rather than text file. I mean even for future updates where new Pets need to be added, i would assume it be easier to update as an sql.

**Comment by Akkarinage** [comment]
Please use the forums for suggestions: https://rathena.org/board/forum/102-database-discussion/
The Github Issues system is for bug reports.
