### ISSUE TITLE
Unnecessary Permanent Variable: The Sign Quest

### ISSUE THREAD

**Issue by cydh** [rathena/rathena#1976]
* **rAthena Hash**: d20c6b508055fc313a5271d3a26cebe6b67d4c70
* **Client Date**: Anything
* **Server Mode**: Both
* **Description of Issue**: 
At https://github.com/rathena/rathena/blob/master/npc/quests/the_sign_quest.txt#L12243
```OnTouch_:
	set geffenia_warp,rand(1,4);
	if (geffenia_warp == 1) warp "gefenia01",58,169;
	else if (geffenia_warp == 2) warp "gefenia02",116,115;
	else if (geffenia_warp == 3) warp "gefenia03",130,206;
	else if (geffenia_warp == 4) warp "gefenia04",133,88;
	else warp "geffen",116,115;
	end;
```
Doesn't need that `geffenia_warp` permanent variable I guess.

**Comment by Lemongrass3110** [comment]
Besides the useless variable the else case can never be reached since rand(1,4) will only return 1-4 and nothing else.
