### ISSUE TITLE
Manhole Skill against Emperium and Crystals

### ISSUE THREAD

**Issue by alxalmora** [rathena/rathena#1977]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/e93c8880b33333bb549b1e088c844393478bbc33

* **Client Date**: 2015-10-29a

* **Server Mode**: Renewal

* **Description of Issue**: 
I think I found and Issue about this. With these diff (and of course adding the miss if(target && ...) you can't cast manhole in Emperium or BG Crystals but if you cast in the cell next-to, they still get in Manhole, I mean I can't see the visual effect but I can't attack the Crystal and Players doesnt seem to be affected by the Manhole (but visual is an active manhole). I put this "issue" here because, maybe was fixed. I apply manual diffs since RndOpt (that crash my server and I make a revert, then I make manual commits only for SRC skills bugs).

* **Modifications that may affect results**: Nope.

**Comment by aleos89** [comment]
We'd need to confirm to see what the range is when casting these skills around the Emperium.

**Comment by crazystorm2017** [comment]
@aleos89 Manhole can be casted beside an emperium in kRO :))

**Comment by aleos89** [comment]
Unless this was changed on a newer version, my tests proved that I couldn't cast on top of any GvG/Battleground mob target.

**Comment by crazystorm2017** [comment]
Im not sure on the battleground but after watching this guy WOE Videos just proves that you can manhole guys next to the emperium. this is a WOE Video 9 Days Ago. kRO Baphomet Server. Im not sure if this is a reliable source though just correct me if im wrong :))
https://www.youtube.com/watch?v=Cgh05uopu-U

**Comment by Everade** [comment]
@crazystorm2017 would be helpful to post the youtube link where it starts at the proper time so the devs do not have to watch through 7:46 minutes of gameplay.

In case someone still needs to see it:
https://www.youtube.com/watch?v=Cgh05uopu-U&feature=youtu.be&t=385

**Comment by Jeybla** [comment]
This is fixed since e93c8880b33333bb549b1e088c844393478bbc33
Just retested it on the current head (8a93b120207c216711e8e7db4d2442ae97e232d0)
