### ISSUE TITLE
Evil Druid Card / OPT1 Status

### ISSUE THREAD

**Issue by gcbucci** [rathena/rathena#1978]
rAthena Hash: https://github.com/rathena/rathena/commit/2931b76b7b826a30c3af65f00c900c722b259be2

On this commit:
https://github.com/rathena/rathena/commit/ca051d185eae2b2f3a62684af1926be3b369b304
When the crystalize and freezing has removed from opt1, evil druid card dont works anymore with ele_undead and her defenses. The card grants immunity to freeze and not working anymore.

* **Server Mode**:  Renewal

i not found any official link about that but have link from iro forum: https://forums.warpportal.com/index.php?/topic/81041-evil-druid-card/

@edit
i make a few source modifications to install others systems but i think that its not the problem.
ps: sorry bad english.
Tomorrow i will made a maintenance on my server and try to reverse those changes of commit https://github.com/rathena/rathena/commit/ca051d185eae2b2f3a62684af1926be3b369b304 to make a test.

**Comment by Playtester** [comment]
With freeze they mean the freeze status change from e.g. Storm Gust. That code doesn't seem to be touched at all?

**Comment by reigneil** [comment]
@gcbucci 
undead armor doesn't guaranteed immune to freezing(Frost Misty).
http://irowiki.org/wiki/Status_Effects#Freezing
maybe your talking to this:
http://irowiki.org/wiki/Status_Effects#Frozen
as @Playtester  mentioned.

**Comment by aleos89** [comment]
I can't confirm this on 800f22b. The target player wearing an Evil Druid Card was never frozen.
