### ISSUE TITLE
Earth Strain strip bypass dex difference

### ISSUE THREAD

**Issue by alxalmora** [rathena/rathena#1979]
* **rAthena Hash**: https://github.com/rathena/rathena/blob/master/

* **Client Date**: All Versions.

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Strip bypass dex difference between caster and target
  * Expected Result: Should work like other strips skills
  * How to Reproduce: Use Earth Strain with out dex vs player with full dex.
Add in this line:
https://github.cotm/rathena/rathena/blob/master/src/map/skill.c#L1474
`
int rate = 5*skill_lv;
if (sstatus->dex > tstatus->dex)
			rate += (sstatus->dex - tstatus->dex)/5;
			for (i = 0; i < skill_lv; i++)
					skill_strip_equip(src, bl, pos[i], rate, skill_lv, skill_get_time2(skill_id, skill_lv));`
* **Modifications that may affect results**:  Is a master code error.

**Comment by aleos89** [comment]
Where did you get the formula for this? I can't seem to find anywhere about it except on iRO, but the problem is we don't follow iRO or iRO Wiki values.

**Comment by Atemo** [comment]
Divest effect was removed in an update https://github.com/rathena/rathena/commit/36195d157d6eef99056926190468bf2e25f4dbed
