### ISSUE TITLE
Clearchus Mercenary Npc

### ISSUE THREAD

**Issue by Joy-Ro** [rathena/rathena#1981]
rAthena Hash: https://github.com/rathena/rathena/blob/master/npc/re/quests/eden/eden_iro.txt
Client Date: All Versions.
Server Mode: Renewal
Description of Issue: The ViP players can keep getting a new mercenary and cost nothing.

`[Error]: quest_add: Character 150267 already has quest 62238.
[Debug]: Source (NPC): Clearchus at moc_para01 (53,30)
[Debug]: Function: setquest (1 parameter):
[Debug]: Data: number value=62238`

Result: Unlimited VIP mercenary rentals and no costs
Expected Result: 3 hour cooldown on VIP mercenary rentals and 10k zeny withdrawn
How to Reproduce: Talk to the npc Clearchus moc_para01,53,30

**Comment by Atemo** [comment]
Note the mercenary is supposed to be free.

**Comment by Joy-Ro** [comment]
Hello Atemo,

The problem with the error is solved now.
New problem hass occured when you take a new Mercenary The quests gets deleted and a new 1 is given.
There is no cooldown now.

This should solve it please take a look.

`if (checkquest(62238,PLAYTIME) > -1 && checkquest(62238,PLAYTIME) < 1) {`

**Comment by Atemo** [comment]
I can't reproduce (my character had a cooldown). Please try with a fresh copy.
