### ISSUE TITLE
add cashshop button support for 2012-04-10aRagexe

### ISSUE THREAD

**Issue by anacondaqq** [rathena/rathena#1982]
Hi, this is very strange that rAthena do not support cashshop button feature for 2012-04-10aRagexe game client (which is mega popular client for pre-re servers and works pretty smooth for years without any issues) 

This client uses packet_ver: 30
So add below:

```
0x08cb,10,ZC_PERSONAL_INFOMATION,2:4:6:8:10:11:13:15 //Still need further information
// Merge Item
0x096D,-1,ZC_MERGE_ITEM_OPEN,2:4 // ZC_MERGE_ITEM_OPEN
0x096E,-1,mergeitem_req,2:4 // CZ_REQ_MERGE_ITEM
0x096F,7,ZC_ACK_MERGE_ITEM,2:4:6 // ZC_ACK_MERGE_ITEM
0x0974,2,mergeitem_cancel,0 // CZ_CANCEL_MERGE_ITEM
```

Next packets for support cashshop button for the client.

```
0x0844,2,cashshopopen,0
0x0849,16 //clif_cashshop_result
0x0848,-1,cashshopbuy,2:6:4:10
0x084a,2,cashshopclose,0
0x08c9,2,cashshopitemlist,0
```

## Why do need to do it?
First of all, it's totally on your decision and opinion. I just making the suggestion, but making decision is at your side. But it's very funny to see rAthena without cashshop support for the client which totally support cashshop feature but not added packets for the feature yet. And I see a lot of [requests](https://rathena.org/board/topic/98611-quick-fix-2012-04-10aragexe-cash-shop/) / [suggestions](https://rathena.org/board/topic/82928-2010-04-10-ragexe-cash-shop/) / [topics](https://rathena.org/board/topic/83259-2012-04-10ragexe/) at rAthena board related to the problem. So, why not just add this feature and forgot about it forever? And yes, personally me motivated to have such packets in rAthena base code, because to be clear i tired to everytime when i work with 2012-04-10aRagexe client adding the packets by myself.

## Is it safe? Is it work like it should?
I'm totally based on my own experience with my own servers with many players in background, and i can say -> yes, it's works fine for years (at least since 2013 year up to now with this game client). Tested a lot on different servers very many times. And yes, these is not affect itemshops, itemshops works just fine too.

**If you need 2012-04-10aRagexe client: [Here is download Link](https://mega.nz/#!jtdW0ADB!XDiP6gWNHKydERHLX-fMRXv6cuUjc9OxTguCYL-Ig9I)** (patched with Nemo)

# Proofs?

![](https://i.imgur.com/r1YkF7s.png)

![](https://i.imgur.com/L1xTnwY.png)

![](https://i.imgur.com/MYMvBGA.png)

**Comment by Lemongrass3110** [comment]
The client you provided uses custom keys. :P
Mine gets stuck right at login, so I guess there is some other issues beside having cash shop support with it.
I see three choices now:
1) give us your custom keys
2) apply the original keys and share the client afterwards
3) tell us what we need to fix beside the cash shop

From what I've seen those packets have been in far longer than 2012.
