### ISSUE TITLE
Oblivion Curse GX Issue

### ISSUE THREAD

**Issue by Vexillio** [rathena/rathena#1983]
rAthena Hash:
Client: 2015-11-04
Mode: Renewal

My players are reporting that GX Poisoning Weapon ( Oblivion Cursed ) is not working it should be debuffing monster/players and deal an extra damage like poison/envenom does right?

and i already tested it seems true

**Comment by Playtester** [comment]
I thought Oblivion Curse gives Silence which can't be healed with Green Potions.

**Comment by Vexillio** [comment]
@Playtester yes thats true but when i tried to attack for almost 5 minutes with 193 aspd on my test server it seems not using the silence effect i mean theres no chance of it to inflict silence on enemy

**Comment by reigneil** [comment]
I think this part isn't working
`sc_def = max(sc_def, 500);`
is your dummy enemy have high INT and also not MVP type?

**Comment by aleos89** [comment]
![image](https://cloud.githubusercontent.com/assets/3521753/23579516/273e9ffe-00bd-11e7-920e-80b71ecd9dda.png)
Works fine for me on 800f22b.
