### ISSUE TITLE
Can't equip edited itens

### ISSUE THREAD

**Issue by johnfercher** [rathena/rathena#1984]
rAthena is up-to-date, client 2015-11-04a, renewal, SQL mode: ON.

Valkyrian Armor: [ http://ratemyserver.net/index.php?page=item_db&item_id=2357](url) 
Enhanced Variant Shoes [http://ratemyserver.net/index.php?page=re_item_db&item_id=22014&iname=&itype=-1&islot_sign=-1&islot=-1&ij%5B+%5D=-1&iju=-1&idesc=&iscript=&i_ele=-1&i_status=-1&i_race=-1&i_bonus=-1&icfix=&sort_r=0&sort_o=0&isearch=Search](url)

The **Valkyrian Armor**, initially works for: **Every Rebirth Job except High Novice (equip_jobs=4294967294)**, I put the configs of **Enhanced Variant Shoes (equip_jobs=2093997952)** in the **Valkyrian Armor** which can be used by **Rebellion**. The thing is, I can use the Enhanced Variant Shoe with Rebellion but the Valkyrian Armor no.

**Comment by keitenai** [comment]
You may refer to this:

https://github.com/rathena/rathena/blob/master/doc/item_db.txt

Also this is not a help support board.
