### ISSUE TITLE
Renewal Acid Demonstration

### ISSUE THREAD

**Issue by MrAntares** [rathena/rathena#199]
Git Version: **12628 - 2014-12-04 05:04:30 (luciar)**
Client Date: **2012-04-10**
Src Mods: **NONE**
General settings: 
- **Full Renewal**
- **1/1/1/1/1 rate**
- **PK server (not in towns, above lvl 30)**
- **PVP ATK/Skill modifers: 100%**
- **WOE ATK/Skill modifers: rA default**
- **Official walk path and stacking**
- **Exp and drop penalty table values below 100% set to 100%**
- **Party and attacker exp bonus: +40%**
- More at (Hungarian, use translate): http://wiki.ragna.ro/

How to reproduce: **Use the skill on MVP**
Description:

I think the versus MVP part is not implemented, since it deals the same damage against mvps and non-mvps, which is incredibly overpowered. I'm not sure what is the correct reduction, but some info states that the skill should deal half damage against mvps (skill description says the same). Can someone backup this info?

iW http://irowiki.org/wiki/Acid_Bomb#Information says:
Boss monsters receive less damage compared to prebalance (however, it is becouse for reduction of the mob VIT, or reduction of the damage in boss monsters; the factor of reduction is approx. 25%). (This may be inaccurate - Certainly boss-type non-MVP take same damage as normal monsters, as of 12/2012)

**Comment by cydh** [comment]
still waiting for other someone if can provide the reduction.

**Comment by MrAntares** [comment]
Can anyone test this on an official server?

**Comment by cydh** [comment]
how can we test? how can we confirm? how can we compare?

**Comment by MrAntares** [comment]
Throw Acid Demo on regular mob, throw acid on a MVP with similar stats. Compare damage. 
Ex:
Aliot and Eddga has almost the same VIT (that is what matters)

**Comment by MrAntares** [comment]
Client: 2012-04-10

Revision: 14739
Last Changed Author: cydh.ramdh
Last Changed Rev: 14739
Last Changed Date: 2015-10-29 06:16:10 +0100 (Thu, 29 Oct 2015)

Mode: RENEWAL

**Comment by RagnarokNova** [comment]
Aliot and Eddga do not have similar vits. If someone can find me an MvP and a regular mob with very similar Vit/DEF I can test this on Aegis.

http://i.imgur.com/oIhsETd.png

But Eddga has way more vit.

**Comment by Akaineko-astasi** [comment]
for example 
Lady Tanee (88 vit, 104 def) and Dracula (88 vit, 146 def); Red Eruma (88 vit, 102 def).

**Comment by cydh** [comment]
stop joking around, if u have Aegis server, u jcan edit the mob db to make same stats between normal and Boss/MVP. /swt

**Comment by RagnarokNova** [comment]
I was using the one rA devs get access to and I do not have the control over the mob dbs. |: If you could set mobs to have the same stats for me I'd love to run the test again.

**Comment by cydh** [comment]
Edited BIGFOOT for same EDDGA's LV, int, vit, agi, luk, def, mdef.
The result is http://prntscr.com/94dy3c

**Comment by MrAntares** [comment]
@cydh LOL that battle log!!! I was right afterall... the actor names are switched, or the text is wrong. Eddga did not gave anyone any damage, lol :D

**Comment by MrAntares** [comment]
Continued in #803
