### ISSUE TITLE
Extra Storage Close button

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#1990]
* **rAthena Hash**: 
03ffd99

* **Client Date**: 
2015-09-16aRagexe

* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result: Close button does not close the extended storage window which means you're forced to relog to get rid of it.
  * Expected Result: Close the window
  * How to Reproduce: Create a VIP extra storage with the official new system from iRO. Open it, and try to click the close button.
  * Official Information: Official servers close button closes the window (jesus i hate this template...)
  

* **Modifications that may affect results**: 
 Extra storage size is 300 and it was empty while testing.
 Shown name is VIP Storage

**Comment by Lemongrass3110** [comment]
Works fine on an unmodified rAthena on 43ba736.

**Comment by Jeybla** [comment]
Can't reproduce this, too.

Tested with openstorage2 1,STOR_MODE_GET|STOR_MODE_PUT;
and openstorage2 1,STOR_MODE_GET;

**Comment by aleos89** [comment]
I'm unable to reproduce as well on 800f22b.
