### ISSUE TITLE
Shadow Chaser receiving permanent buffs after Perfect hide from Feint Skill

### ISSUE THREAD

**Issue by feltenc** [rathena/rathena#1999]
GIT Hash: 8f82d046c0ce769c4ee1ceffe0c6ae8eaeb6ffd1
Mode: Renewall
Client: 2017-01-25RagexeRE

As the title says, Shadow Chaser is receiving the buffs in the area being enemies, until everything happens well and as it should be, the problem occurs that after leaving the state of perfect hide caused by the Feint Bomb ability, the buffs are not removed. After leaving the state of Perfect Hide and getting out of the area buffs, the player still continues with the effects of the buffs.

Examples:

If the Shadow Chaser uses Feint bomb on the Neutral Barrier skill of MECHA, after leaving the Perfect hide that the Feint Bomb skill causes on the user, the Neutral Barrier buff should end. Which does not happen. While the Shadow chaser is in the MECHAN screen the buff is still active, even if it is not on the field.

The same happens with the Pneuma and Stealth Field skills

Important Note: This glitch only happens if the Shadow Chaser uses Feint Bomb out of the enemy or allied buff skill, and at the "end" of the skill it falls exactly over the area that has a buff.

I ask for special attention as this is a huge problem, which can turn a class into something immortal.

Please @Playtester  could confirm that for me? Thanks

File Scan: https://www.virustotal.com/pt/file/61404ba7fbef52a346d201f1cd7cb69dfd5f40ef009338dc864522475f2097fa/analysis/1489118758/

Attached File: Replay directly from my server, simulating and showing the glitch. http://www.filedropper.com/report_5

**Comment by Joskinho** [comment]
I've tested this, and the bug is really happening.

**Comment by jamon18** [comment]
hiden perfect in bloody lust / killing cloud (aoe) /preneuma/  Stealth Field / neutral barrier

**Comment by feltenc** [comment]
@jamon18 what do you mean? The problem is not the hidden, check the replay file if is possible.

**Comment by feltenc** [comment]
@aleos89 please could you check this issue? Shadow chaser's keep getting immortal. I think it is a big issue and should be looked at carefully.

Thanks in advance and sorry to bother.

**Comment by aleos89** [comment]
I did some quick testing on this and I couldn't get anything to stick like you are saying.
1) Player A (Mechanic) activates Neutral Barrier.
2) Player B (Shadow Chaser) moves into the NB area and then uses Feint Bomb to slide out of it.
3) Player B is returned to normal state and has no permanent effects attached.

**Comment by feltenc** [comment]
Aleos, you did the reverse process, instead of using Feint bomb to get out of the neutral barrier, you must use feint bomb to "drop" on the neutral barrier. Your character must be out of the Neutral Barrier when you use Feint Bomb, and should fall on the neutral barrier. Were you able to see the replay?

**Comment by aleos89** [comment]
The replay file URL doesn't work.

I tested again doing the reverse, where the Shadow Chaser moves out of the Neutral Barrier AoE with Feint Bomb. After the SC moved out, I was able to cast Axe Boomerang on the SC.

**Comment by feltenc** [comment]
There  is another link for the replay.

https://mega.nz/#!8cR3gSBR!aoRewt8qkv6DqVLUJ8STz7msRBLIi6jaaJvgKWKp-og

I will try to show with screenshots too.

*Here is before the glitch. Genetic can hit me and the SC normally.
![image](https://cloud.githubusercontent.com/assets/22537929/24873793/9b490aa8-1df8-11e7-9dbd-84fbd5aaa62a.png)

* Where i am with Neutral Barrier On and i receive miss(OK, it works as intented).
![image](https://cloud.githubusercontent.com/assets/22537929/24873846/ccf5a778-1df8-11e7-8e95-ed266942c21c.png)

* Here the Shadow Chaser is out of Neutral Barrier area preparing to use Feint Bomb
![image](https://cloud.githubusercontent.com/assets/22537929/24873934/23cace8e-1df9-11e7-8127-f186278fea83.png)

*And then he uses Feint Bomb to fall into the Neutral Barrier area
![image](https://cloud.githubusercontent.com/assets/22537929/24873951/3d5f036a-1df9-11e7-9606-fa9c409de576.png)

*He move out the Neutral Barrier area and the Feint Bomb perfect hide is gone
![image](https://cloud.githubusercontent.com/assets/22537929/24873988/66f2b9ba-1df9-11e7-94c1-bc403f94b102.png)

*The effect of Neutral Barrier keeps on the SC permanent when its on the Mechanics Area.
![image](https://cloud.githubusercontent.com/assets/22537929/24874011/7e95e77c-1df9-11e7-9dd6-c403c9c8fd5c.png)

*Another proof
![image](https://cloud.githubusercontent.com/assets/22537929/24874045/9847d874-1df9-11e7-8e04-fca64667cbec.png)
![image](https://cloud.githubusercontent.com/assets/22537929/24874051/9fe8b03a-1df9-11e7-81a0-88b10b7c4861.png)

* Stealth Field(On Same party of Mecha)
![image](https://cloud.githubusercontent.com/assets/22537929/24874090/bd7c1f42-1df9-11e7-8e70-9dcca6fe3a9e.png)
![image](https://cloud.githubusercontent.com/assets/22537929/24874092/c455121a-1df9-11e7-894b-deeb4524e605.png)
![image](https://cloud.githubusercontent.com/assets/22537929/24874150/013553a2-1dfa-11e7-9d68-e773b5e2830e.png)
![image](https://cloud.githubusercontent.com/assets/22537929/24874161/0b2f8aee-1dfa-11e7-9a6b-620573f026f1.png)

Notes: All the tests are made on pvp.

**Comment by aleos89** [comment]
![1](https://cloud.githubusercontent.com/assets/3521753/24929949/c2e32692-1ed5-11e7-97a2-fe4b12ad562e.png)
![2](https://cloud.githubusercontent.com/assets/3521753/24929963/caebc2a4-1ed5-11e7-89c8-1d16733c5371.png)
I still can't reproduce this.

**Comment by feltenc** [comment]
Wow, thanks, I was starting to think I was going crazy hahaha
@Jeybla @aleos89 its a powerfull glitch that can make people immortal.
