### ISSUE TITLE
Modifiers are not working on Shields

### ISSUE THREAD

**Issue by Paoly28** [rathena/rathena#2000]
As title says, tested on Mad Bunny which increase atk rate by 5% and Tournament Shield which has 1% modifier against all races.

Version : Renewal

43ba736

**Comment by Paoly28** [comment]
#1406 a reconfirmation for his bug.

**Comment by Jeybla** [comment]
> Please read #718 (comment)
(From #1406 by Atemo)
> In renewal, all race/size and other % cards affect only the **equipment part** of atk.
If you're firm you tested everything correctly, please provide some screens and more informations (git hash, mode, etc.). Thanks

By the way Mad Bunny isn't even a shield?

**Comment by Paoly28** [comment]
on the report i changed shield of death to deal 20% more damage.

i used +20 grimtooth with power maximize to eliminate variance results showed that modifiers from shield didn't work. and mad bunny has two type of shield.

One is Mad Bunny Special and the Other is Mad Bunny.

**Comment by Paoly28** [comment]
using latest git hash client wasn't so sure but its 2014 client.

**Comment by Jeybla** [comment]
Just want to repeat it, since I did the same mistake like you:
> **In renewal, all race/size and other % cards affect only the equipment part of atk.**

Anyway please provide concrete informations. "Latest git hash" seams wrong, since the hash changed since you created this issue. Also are you on renewal or pre-renewal mode? If you're on renewal you must'nt compare the actual damage output, like i said above. It just affects the equip atk.

**Comment by Paoly28** [comment]
Regardless of where the modifier is, The modifier should affect the equipment attack portion of your attack.

Version is Renewal.

**Comment by Paoly28** [comment]
If that's the case then modifiers from costumes and accessories wouldn't work.

**Comment by aleos89** [comment]
Unable to reproduce on 9991b09. When adding `bonus2 bAddClass` to Mad Bunny, my damage increased as it should.
