### ISSUE TITLE
can use novice butterfly wing at map mapflag noreturn

### ISSUE THREAD

**Issue by hendra814** [rathena/rathena#2001]
* **rAthena Hash**:  lastest version

* **Client Date**: 2015-11-04

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result:  used novice butterfly wing at map with noretun mapflag, still can make character back into save point
  * Expected Result:  can't back to save point
  * How to Reproduce:  Move into map with noreturn mapflag,after that use novice butterfly wing.
  * Official Information:
   

* **Modifications that may affect results**: 
  
  

PS: for noteleport it's block character for teleport in map with noteleport mapflag using novice fly wing, so for noreturn it's suppose to be same wtih novice butterfly wing item.

Thanks

**Comment by lucasoli** [comment]
Hello @hendra814 ,

I don't know if this is the correct behavior neither if I've done the fix the right way, but here is what you want:

1) open your itemdb.h and find this text '**enum item_itemid**'.
2) add 2 new entrys bellow the '**ITEMID_THICK_BATTLE_MANUAL**'.
`	ITEMID_NOVICE_WING_OF_FLY			= 12323,`
`	ITEMID_NOVICE_WING_OF_BUTTERFLY     = 12324,`
3) open your pc.c and find this text '**case ITEMID_WING_OF_BUTTERFLY:**'
4) add 1 new entry bellow that case.
`		case ITEMID_NOVICE_WING_OF_BUTTERFLY:`
5) find this text '**case ITEMID_WING_OF_FLY:**'.
6) add 1 new entry bellow that case.
`		case ITEMID_NOVICE_WING_OF_FLY:`

I know the dev team has cleaned up some item constants for some purposes and I don't feel comfortable inserting new constants there... If I've done something wrong can someone point me out what I did, please.

**Comment by cydh** [comment]
Confirmed. Novice Butterfly Wings & Novice Fly Wings must have same restriction
