### ISSUE TITLE
multiple npc errors

### ISSUE THREAD

**Issue by srhmike** [rathena/rathena#2002]
* **rAthena Hash**: 8f82d

* **Client Date**: 20151104

* **Server Mode**: renewal

* **Description of Issue**: 
  

[Warning]: Incorrect use of 'close' command! (source:#ep14_2Bridge / path:npc/re/quests/quests_eclage.txt)

[Debug]: npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Geffen Coin Operator#g (id=110104530).

[Error]: script:op_2: invalid data for operator C_SUB
[Debug]: Data: string value="Why are doing this job?:General Culvert Daily Service:^990000Hard Culvert Daily Service^000000:General Culvert Weekly Service:^990000Hard Culvert Weekly Service^000000:"
[Debug]: Data: number value=1
[Debug]: Source (NPC): Albo#mal at mal_in01 (172,28)

[Warning]: script:get_val: cannot access instance variable ''ins_nyd2', defaulting to 0

[Debug]: Source (NPC): Hugin#ghinstance at glast_01 (204,273)

I only noticed it pop up on the server, wasn't around when it happened.  sorry i cant provide more info.
OGH is the cleanup/old_glast_heim
* **Modifications that may affect results**:

**Comment by Jeybla** [comment]
```
[Error]: script:op_2: invalid data for operator C_SUB
[Debug]: Data: string value="Why are doing this job?:General Culvert Daily Service:^990000Hard Culvert Daily Service^000000:General Culvert Weekly Service:^990000Hard Culvert Weekly Service^000000:"
[Debug]: Data: number value=1
[Debug]: Source (NPC): Albo#mal at mal_in01 (172,28)
```
This is a common error I encountered several times on multiple. it comes from these script structures:
```
.@selected = select(MenuEntry1:MenuEntry2")-1;
```
And it seems (from the error message) `select` doesn't return the selected index, but it returns just the whole string. I sadly couldn't reproduce this error, but maybe it has something to do with the script timeout. Would be nice to hear if someone has an idea.

```
[Debug]: npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Geffen Coin Operator#g (id=110104530).
```
This error occurs equally rare (depending on player count). Maybe it has also something to do with the script timeout. @srhmike do you use an server-wide `addrid/attachrid` in any npc?

**Comment by srhmike** [comment]
What you mean by server-wide?
I do see attachrid in a few npcs.  (iRO Weekly Quest by Stolao, MVP Team Speed Run by Stolao, Infinite Space by Emistry, )
And dont see any addrid in any of the custom npcs.

**Comment by Jeybla** [comment]
Nevermind then, it was just a quick thought

**Comment by srhmike** [comment]
I did just seen this error pop up, it could be related to the GMT posted above,
(03/25/2017 21:05:39) [ Error ] : buildin_instance_npcname: Invalid instance NPC (instance_id: 1, NPC name: "#GMTcontroller::OnTimeout2".)
(03/25/2017 21:05:39) [ Debug ] : Source (NPC): #GMTcontroller at 0011@ge_st (1,1)
(03/25/2017 21:06:10) [ Error ] : 

**Comment by Atemo** [comment]
I can't reproduce
>[Error]: script:op_2: invalid data for operator C_SUB
[Debug]: Data: string value="Why are doing this job?:General Culvert Daily Service:^990000Hard Culvert Daily Service^000000:General Culvert Weekly Service:^990000Hard Culvert Weekly Service^000000:"
[Debug]: Data: number value=1
[Debug]: Source (NPC): Albo#mal at mal_in01 (172,28)

and 

>[Debug]: Source (NPC): Hugin#ghinstance at glast_01 (204,273)

Can you give us more infos?

**Comment by srhmike** [comment]
I haven't received the errors since.... so I cant even reproduce them.

**Comment by srhmike** [comment]
I just got the same C_SUB error on another npc, I tried everything to reproduce it, and I cant get it to reproduce....
```
(04/08/2017 23:01:06) [ Error ] : script:op_2: invalid data for operator C_SUB
(04/08/2017 23:01:06) [ Debug ] : Data: string value="New Black Fairy Wings:New Blue Fairy Wings:New Cyan Fairy Wings:New Dark Blue Fairy Wings:New Dark Cyan Fairy Wings:New Dark Gold Fairy Wings:New Dark Green Fairy Wings:New Dark Purple Fairy Wings:New Dark Red Fairy Wings:New Gold Fairy Wings:New Green Fairy Wings:New Purple Fairy Wings:New Red Fairy Wings:New White Fairy Wings"
(04/08/2017 23:01:06) [ Debug ] : Data: number value=1
(04/08/2017 23:01:06) [ Debug ] : Source (NPC): VoteForPoints at prontera (147,166)


```

**Comment by Lemongrass3110** [comment]
User was unable to reproduce the issue anymore. Assuming this was fixed.
