### ISSUE TITLE
warning clif_Globalmessage

### ISSUE THREAD

**Issue by cold-hr** [rathena/rathena#2005]
* **rAthena Hash**: 

[GitHub hash](https://github.com/rathena/rathena/commit/8f82d046c0ce769c4ee1ceffe0c6ae8eaeb6ffd1)

* **Client Date**: 
2012-04-10 and 2015-10-29

* **Server Mode**: 
 Pre-Renewal / Renewal

* **Description of Issue**: 
  * Clown using skill  Frost Joke

  * sorry my bad english

* **Img**: 
  
  
![image](https://cloud.githubusercontent.com/assets/13975637/23895034/eca47d88-08d6-11e7-97ff-f7a7824ad1d5.png)
![image](https://cloud.githubusercontent.com/assets/13975637/23895140/50aa9ace-08d7-11e7-8557-46143babb7dc.png)
![image](https://cloud.githubusercontent.com/assets/13975637/23895300/de7352d8-08d7-11e7-9c69-3a67c03ba6d4.png)

**Comment by daisyanne1380** [comment]
yea i get that also, tho it doesnt do anything negative to the server that i can tell. or maybe its to long for logs im not really sure but i get the same warning on mapserver

**Comment by Everade** [comment]
Confirm. Although this has been present since quite some while already.
It will simply not show the entire message to everyone else if it's a global message.

But i also get this a lot when normaly writing in chat.
While it displays the message to myself, other players will never see that i've said anything.
And the map server always shows the warning of "truncating too long message" as shown above.

**Comment by RadianFord** [comment]
Yea, this has been present for a long time I dont know if this is a real problem lets wait what developers can say about this.

**Comment by anacondaqq** [comment]
> // char buf[100];

to

> // char buf[CHAT_SIZE_MAX];

will fix the problem, And i don't know why they do not want to increase buffer, and why they changed the value...

**Comment by Lemongrass3110** [comment]
@anacondaqq I do not know what makes you think we do not want to change the buffer size.
That line of code simply was not touched since 2012(a2bdc47).

Thanks for providing the fix nevertheless. We'll try it out and merge it if it fixes the issue.
