### ISSUE TITLE
Quest Number 11205 is missing

### ISSUE THREAD

**Issue by spangler88** [rathena/rathena#2012]
* **rAthena Hash**: 

* **Client Date**: 2015-11-04a

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Quest Number 11205 is missing
  * Attached Imaged from script ep 14_1
![tes](https://cloud.githubusercontent.com/assets/26497788/24069204/f2c3c394-0bd4-11e7-9194-62b6964e2b01.JPG)

* **Modifications that may affect results**: 
  No modification

**Comment by Jeybla** [comment]
Dummy Data for the quest_db.txt:
```
//Mora Quests
11204,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"Mora Village..."
11205,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"Pauchon's Friend"
```
