### ISSUE TITLE
bonus4 bAutoSpell,"NPC_EARTHQUAKE" missing arguement

### ISSUE THREAD

**Issue by srhmike** [rathena/rathena#2014]
* **rAthena Hash**:  61ff251  

* **Client Date**: 20151104

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: (03/19/2017 13:17:48) [ Error ] : 
script error on autobonus line 0
    parse_callfunc: not enough arguments, expected ','
     0 : { bonus4 bAutoSpell,"NPC_EARTHQUAKE",1,200';' }
  
  * How to Reproduce: Ring of Flame Lord, Ring of Resonance
  *

**Comment by aleos89** [comment]
Neither of those items contain that bonus. The only items that use NPC_EARTHQUAKE are Ifrit Card and Sealed Ifrit Card.

The error is right there in your item script. `bonus4` means 4 options, while `bonus3` is 3 options.

**Comment by srhmike** [comment]
Sorry, when I was searching the few players on, that's all I could come up with.  I didn't check the item database before.

And as you said, Here's the 2 items you said.  Which is exactly what you said.  Now what I dont understand it that the error I got, doesn't match with the items in my database.  There is nothing in the import on anything with NPC EARTHQUAKE, and as you said, these two were the only ones.  Got any other ideas where I could look?

4487,Sealed_Ifrit_Card,Sealed Ifrit Card,6,20,,10,,,,,,,,136,,,,,{ bonus bBaseAtk,(JobLevel/20); bonus bCritical,(JobLevel/20); bonus bHit,(JobLevel/20); bonus3 bAutoSpellWhenHit,"NPC_EARTHQUAKE",5,1; },{},{}

4430,Ifrit_Card,Ifrit Card,6,20,,10,,,,,,,,136,,,,,{ bonus bBaseAtk,(JobLevel/10); bonus bCritical,(JobLevel/10); bonus bHit,(JobLevel/10); bonus3 bAutoSpellWhenHit,"NPC_EARTHQUAKE",10,1; },{},{}

**Comment by srhmike** [comment]
Nevermind Found it, Updating first post.

**Comment by aleos89** [comment]
I've pushed a fix to that branch. Since the Faceworm Instance isn't pushed to master yet I'll leave this closed.
