### ISSUE TITLE
Ranger, Warlock and Wanderer/Minstrel Alternate Body styles

### ISSUE THREAD

**Issue by RadianFord** [rathena/rathena#2019]
* **rAthena Hash**: 09cbf2dfa61e3eed34936e7cd2e312c02d20a211

* **Client Date**: 2015-05-13 <- it didnt work here
* **Client Date**: 2015-11-04 <- it worked here

* **Server Mode**: Pre Renewal

* **Description of Issue**: 
* **Issue**: new 3rd jobs alternate body style's are not supported by this client date 2015-05-13, which was stated here https://rathena.org/board/topic/104205-2015-client-support/ that it was, now I cant say this is client related issue or maybe im wrong with this. Now as you can see I did use 2 different client dates just to test it and see it for my self.

* **Expected Result**: it should work on this client date 2015-05-13 since it was implemented specifically on that date.

* **Another Info**: This (Guillotine Cross & Genetic & Mechanic & Royal Guard & Arch Bishop Outfit) works perfectly on this date 2015-05-13.

**Comment by Lemongrass3110** [comment]
Works fine for me on 2015-05-13 if I provide the correct luas and sprites, which can be found at the bottom of the topic you linked.

**Comment by RadianFord** [comment]
@Lemongrass3110 can you give me what you use? if you dont mind?

**Comment by Lemongrass3110** [comment]
AB for example:
![grafik](https://cloud.githubusercontent.com/assets/3517879/24632347/1a85264c-18c4-11e7-9e4d-ad417d885d1e.png)

**Comment by RadianFord** [comment]
@Lemongrass3110 yes AB works fine for me but these jobs Ranger, Warlock and Wanderer/Minstrel Alternate Body did you try it?

**Comment by Lemongrass3110** [comment]
You have to add the luas for them. They were only added recently. It's quite logical that they do not work if you do not provide the correct luas and sprites by yourself.
Please try to ask @AetherHaziel via PM on board or discord.

**Comment by RadianFord** [comment]
I read this information from hercules http://herc.ws/board/topic/11531-dress-pack/?p=67778 is this a client related or its also a source?
