### ISSUE TITLE
Renewal Piercing Shot

### ISSUE THREAD

**Issue by MrAntares** [rathena/rathena#202]
Git Version: **12628 - 2014-12-04 05:04:30 (luciar)**
Client Date: **2012-04-10**
Src Mods: **NONE**
General settings: 
- **Full Renewal**
- **1/1/1/1/1 rate**
- **PK server (not in towns, above lvl 30)**
- **PVP ATK/Skill modifers: 100%**
- **WOE ATK/Skill modifers: rA default**
- **Official walk path and stacking**
- **Exp and drop penalty table values below 100% set to 100%**
- **Party and attacker exp bonus: +40%**
- More at (Hungarian, use translate): http://wiki.ragna.ro/

How to reproduce: **Use the skill**
Description:

In renewal, this gunslinger skill should deal more damage when used with rifles. On max, 200% with revolvers, 300% with rifles.

http://ro.doddlercon.com/wiki/index.php?title=Renewal_Skill_Changes#Piercing_Shot
Deals increased damage when cast with a Rifle.

http://irowiki.org/wiki/Wounding_Shot
This skill inflicts additional damage with a Rifle class weapon.

http://irowiki.org/wiki/Gunslinger
The skill's description shows that it deals 200% damage which sounds horrible but , when used with a rifle , actualy deals an extera 100% damage for a total of 300% . Because of this , the skill's damage formula is similar to that of an Archer's Double Strafe and even has the powerful bonus of ignoring a target's defence.

**Comment by cydh** [comment]
then need more info, is the +100% only when lvl 5 or each level +20% if using riffle.

**Comment by MrAntares** [comment]
I think it is +20% / lvl, but since there is no formula posted anywhere, it needs testing. (But every time someone says it's +x% on max lvl it turns out to be distributed for all levels.)
