### ISSUE TITLE
Storage Full

### ISSUE THREAD

**Issue by Joy-Ro** [rathena/rathena#2022]
Latest rAthena
Renewal Mode.

When the Storage is Full 300/300 you cant put items in the storage that are already inside.
Like there are 10 Red Herbs in my storage when its full 300/300 i cant increase the 10 red herbs inside.

I need to remove 1 item to put the herbs in and after i have done that i can make the storage full.

**Comment by Jeybla** [comment]
I can confirm this on 8f82d046c0ce769c4ee1ceffe0c6ae8eaeb6ffd1
