### ISSUE TITLE
delete timer error function mismatch

### ISSUE THREAD

**Issue by srhmike** [rathena/rathena#2024]
* **rAthena Hash**: 
 6eb4cc4

* **Client Date**: 
20151104

* **Server Mode**: 
renewal

* **Description of Issue**: 
  * Result: 
[Error]: delete_timer error : function mismatch 0x56cc00(skill_castend_pos) != 0x578f20(skill_castend_id)
[Error]: delete timer error : skill_id : -2
[Error]: skill_castend_pos: Timer mismatch -1!=968
[Error]: delete_timer error : function mismatch 0x56cc00(skill_castend_pos) != 0x578f20(skill_castend_id)
[Error]: delete timer error : skill_id : -2
[Error]: skill_castend_pos: Timer mismatch -1!=1509
[Error]: delete_timer error : function mismatch 0x56cc00(skill_castend_pos) != 0x578f20(skill_castend_id)
[Error]: delete timer error : skill_id : -2
[Error]: skill_castend_pos: Timer mismatch -1!=200
  * Expected Result: 
  * How to Reproduce: 

  * Official Information:
  

* **Modifications that may affect results**: 
  
  
Renewal Cast is disabled in source.
faceworm branch merged
summoner branch merged

**Comment by aleos89** [comment]
It's hard to tell the cause of this without any known reproduction methods. If this is still active (as this is a few months old now) we can reopen this.
