### ISSUE TITLE
Acid Demonstration should be neutral (and other Forced Element Skills)

### ISSUE THREAD

**Issue by Jeybla** [rathena/rathena#2025]
* **rAthena Hash**: 0b5687db1360f393d053dfed5503615dc8c7e5dd

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Acid Demonstration is affected by the weapon element.
![screentotoro039](https://cloud.githubusercontent.com/assets/6203894/24374064/cc2689cc-1333-11e7-8e1d-727e874a70af.jpg)
![screentotoro048](https://cloud.githubusercontent.com/assets/6203894/24374069/d1088594-1333-11e7-937f-db4a2979ce8b.jpg)

  * Expected Result: Acid Demonstration should always be neutral element as far as i know.
  * Related Source: http://irowiki.org/wiki/Acid_Bomb

db/re/skill_db.txt
```C
490,9,8,1,-1,0x60,0,10,1:2:3:4:5:6:7:8:9:10,yes,0,0,0,misc,0,0x0, CR_ACIDDEMONSTRATION,Acid Demonstration
```
should be changed to:
```C
490,9,8,1,0,0x60,0,10,1:2:3:4:5:6:7:8:9:10,yes,0,0,0,misc,0,0x0, CR_ACIDDEMONSTRATION,Acid Demonstration
```

Header:
```C
//id,range,hit,inf,element,nk,splash,max,list_num,castcancel,cast_defence_rate,inf2,maxcount,skill_type,blow_count,inf3,name,description
// 01 ID
// 02 range (combo skills do not check for range when used,
//           if range is < 5, the skill is considered melee-range)
// 03 hit (8- repeated hitting, 6- single-hit)
// 04 inf (0- passive, 1- enemy, 2- place, 4- self, 16- friend, 32- trap)
// 05 element (0 - neutral, 1 - water, 2 - earth, 3 - fire, 4 - wind, 5 - poison,
//             6 - holy, 7 - dark, 8 - ghost, 9 - undead, -1 - use weapon element
//             -2 - use endowed element, -3 - use random element.)
```

**Comment by feltenc** [comment]
i have confirmed that with Ziu, in kRO AD forces neutral damage.

**Comment by Playtester** [comment]
I'm surprised this doesn't work because according to the code in battle.c:
```
#ifdef RENEWAL
	// forced to neutral skills [helvetica]
	// skills forced to neutral gain benefits from weapon element
	// but final damage is considered "neutral" and resistances are applied again
	switch (skill_id) {
		case MC_CARTREVOLUTION:
		case MO_INVESTIGATE:
		case CR_ACIDDEMONSTRATION:
		case SR_GATEOFHELL:
		case GN_FIRE_EXPANSION_ACID:
		case KO_BAKURETSU:
			// Forced to neutral element
			wd.damage = battle_attr_fix(src, target, wd.damage, ELE_NEUTRAL, tstatus->def_ele, tstatus->ele_lv);
			break;
```
It would already be forced neutral.

Changing it in the database would result in the weapon element no longer affecting the damage. Guess I'll need to test on rA myself.

**Comment by Jeybla** [comment]
```
Changing it in the database would result in the weapon element no longer affecting the damage.
```
Isn't this exactly what we want here? I didn't even know, that there is a neutral force possibility in the source. Why is this not in the database?

**Comment by Atemo** [comment]
See also issue https://github.com/rathena/rathena/issues/803

**Comment by Jeybla** [comment]
Oh I didn't see this comment:
```
	// skills forced to neutral gain benefits from weapon element
	// but final damage is considered "neutral" and resistances are applied again
```
Nevermind this issue then.

**Comment by Playtester** [comment]
Yeah but according to your screenshot it's still bug because it definitely looks like the final damage is increased by lightning loader and that doesn't happen on Aegis at all.

**Comment by Jeybla** [comment]
A friend of mine will retest this in aegis

**Comment by Playtester** [comment]
From my Aegis tests all skills like that are always just normal neutral damage.

**Comment by Jeybla** [comment]
`From my Aegis tests all skills like that are always just normal neutral damage.`
He confirmed it, too. It's always neutral.

So this issue should be updated: #803
And maybe we can fix this kinda related issue, too: #965

**Comment by julia40124009** [comment]
can confirm with twro

**Comment by alxalmora** [comment]
Maybe Dragon Breath have same issue, is forced water.

**Comment by Jeybla** [comment]
I'll have a closer look on these skills:
```
 		case CR_SHIELDBOOMERANG:
 		case LK_SPIRALPIERCE:
 		case ML_SPIRALPIERCE:
 		case PA_SHIELDCHAIN:
 		case PA_SACRIFICE:
 		case RK_DRAGONBREATH:
 		case RK_DRAGONBREATH_WATER:
 		case NC_SELFDESTRUCTION:
 		case KO_HAPPOKUNAI:
```

**Comment by keitenai** [comment]
Possibility that it is surely being forced neutral after elemental damage modifier is applied?

**Comment by Jeybla** [comment]
Also have a check for the skill `Metallic Sound`. Bug report from @jamon18 :

> Metal sound in pseudo elemental neutral - with the element wind endowing in the weapon (no arrow) / taking element metal sound damage
ej: best weapon + scroll endow element wind + gioia card = 55k per hit
this is bug?
http://irowiki.org/wiki/Metallic_Sound
http://irowiki.org/wiki/Category:Forced_Element_Skills
