### ISSUE TITLE
Character Delete 2015-05-13

### ISSUE THREAD

**Issue by RadianFord** [rathena/rathena#2027]
* **rAthena Hash**: 09cbf2dfa61e3eed34936e7cd2e312c02d20a211

* **Client Date**: 2015-05-13

* **Server Mode**: Pre Renewal

* **Description of Issue**: I am having issue with deleting characters using the said client date I can still login the character if i already pressed the delete button.

A sample images
http://imgur.com/kFcerga
http://imgur.com/UvfIrnX

my settings
```
// Restrict character deletion by BaseLevel
// 0: no restriction (players can delete characters of any level)
// -X: you can't delete chars with BaseLevel <= X
// Y: you can't delete chars with BaseLevel >= Y
// e.g. char_del_level: 80 (players can't delete characters with 80+ BaseLevel)
char_del_level: 0

// Amount of time in seconds by which the character deletion is delayed.
// Default: 86400 (24 hours)
// NOTE: Requires client 2010-08-03aragexeRE or newer.
char_del_delay: 0

// Restrict character deletion by email address or birthdate.
// This restricts players from changing the langtype and deleting characters.
// Defaults based on client date.
// 1: Email address
// 2: Birthdate
// 3: Email address or Birthdate
// IMPORTANT!
// - This config only works for clients that send 0x0068 or 0x01fb for delete request.
// - Use langtype 1 for newer clients (2013+), to use 0x01fb.
// - Clients that are not using 0x0068 or 0x01fb, only use birthdate (YYMMDD) as default.
char_del_option: 3

// Restrict character deletion as long as he is still in a party or guild
// 0: No restriction is applied
// 1: Character cannot be deleted as long as he remains in a party
// 2: Character cannot be deleted as long as he remains in a guild
// 3: Character cannot be deleted as long as he remains in a party or guild(default)
char_del_restriction: 3
```

**Comment by Lemongrass3110** [comment]
What is your problem?
I do not see the displayed date because of the hat, so I do not know if that one is wrong.

**Comment by RadianFord** [comment]
@Lemongrass3110 
here I'll attach a new images

![screenwickedro005](https://cloud.githubusercontent.com/assets/9658425/24413893/d5df4586-13aa-11e7-884d-44c0b71ec4c7.jpg)

![screenwickedro006](https://cloud.githubusercontent.com/assets/9658425/24413905/dbe24258-13aa-11e7-8dc9-2e8ed07642cb.jpg)

**Comment by Lemongrass3110** [comment]
Is it really too much to ask for you to describe your problem in a few sentences?
Sorry but this is getting ridiculous.

**Comment by RadianFord** [comment]
I tried to delete a character so in the first picture i tried to delete that character with the `char_del_delay: 0` now when i enter the i can still use it. is that normal?

**Comment by RadianFord** [comment]
I'll create another issue with a clear explanation about this issue.

**Comment by Lemongrass3110** [comment]
This is related to #1189, 2015-05-13 was one of the untested clients back then.
