### ISSUE TITLE
skill_damage_db NOT WORKING

### ISSUE THREAD

**Issue by Lilori** [rathena/rathena#2031]
* **rAthena Hash**: Latest

* **Client Date**: 2015-09-16

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: No damage changed
  * Expected Result: Damage changed after edit db/skill_damage_db.txt
  * How to Reproduce: 1. Uncomment the '//' in src/config/core.h > 2. RECOMPILE > 3. add HT_BLASTMINE,2,1,100 in db/skill_damage_db.txt > 4. Viola~ the damage still same.
  * Official Information: Nope.
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Did you add the mapflag for it as well? Please see [here](https://github.com/rathena/rathena/blob/master/doc/mapflags.txt#L298).

**Comment by Lilori** [comment]
Hi aleos89, thankyou for replying this issue.

Nope, i do not setting mapflag (because i was setting '15' in db/skill_damage_db.txt) which is mean that i set for Normal Maps, PVP, GVG, and Battlegrounds.

**Comment by Lemongrass3110** [comment]
What do you want to achieve?
The snippet from your database would mean:
Add 100% damage if a monster attacks a player with blast mine on a normal map.
Please bear in mind that towns for example are no "normal" maps - they use restricted zone 7.

**Comment by aleos89** [comment]
I'm also unable to reproduce this.
