### ISSUE TITLE
Sara's Memory Instance

### ISSUE THREAD

**Issue by Vexillio** [rathena/rathena#2032]
![image](https://cloud.githubusercontent.com/assets/24485186/24583090/ccd3748a-16fc-11e7-8de3-98df3992860a.png)

I'm receiving this error in my test emulator when i try to run.

**Comment by Jeybla** [comment]
I guess you killed these monsters with `@killmonster`?

Workaround:
```diff
1@sara,1,1,4	script	#MobsSara01	-1,{
[...]
OnMyMobDead:
[...]
+		if( getattachedrid() )
+			viewpoint 1,208,250,1,0x00FF00;
```

Anyway usually OnMyMobDead-Events are triggered with an attached rid. So this isn't really necessary to fix I think.

**Comment by Atemo** [comment]
For not we just add an additionnal check in the script. Thanks for the report @Vexillio
