### ISSUE TITLE
OBB/OPB Dropping 0 ea Items

### ISSUE THREAD

**Issue by dragonis1701** [rathena/rathena#2035]
In order to be able to produce this very easily:

Fill up on items until you have about 400 or so weight left.
Set the probability of acquiring a Legion Plate Armor to much higher than everything else from OBB.
Open OBB and receive a Legion Plate Armor.

The Legion Plate Armor will say there is 0 of it on the floor. No error in the console, it consumes the OBB and the player cannot acquire the item by any means.

**Comment by Lemongrass3110** [comment]
I just tested this on 4369b47 with 2015-11-04 and got this error message instead dropping 0ea of the legion plate:
![violet](https://cloud.githubusercontent.com/assets/3517879/24629586/d2a7d2f2-18b9-11e7-9c7b-56fe5924cd36.PNG)

This was my db/re/item_violetbox.txt:
```
// Old Violet Box Obtainable Items Database
//
// Structure of Database:
// GroupID,ItemID,Rate

IG_VioletBox,501,14 // Red Potion
IG_VioletBox,2341,99 // Full_Plate_Armor
```

**Comment by dragonis1701** [comment]
You cannot open Old Blue Box/Old Purple Box while you are 90% overweight. You have to be just below 90% when you do this. 
![screendecentro080](https://cloud.githubusercontent.com/assets/9850054/24629795/9db3ae12-18ba-11e7-9722-5458058b7f46.jpg)
![screendecentro081](https://cloud.githubusercontent.com/assets/9850054/24629805/a3cb906c-18ba-11e7-8b11-29cb701291d2.jpg)

**Comment by Lemongrass3110** [comment]
Still unable to reproduce it.
![violet2](https://cloud.githubusercontent.com/assets/3517879/24630001/4768ec9c-18bb-11e7-99ca-6f94817ea42b.PNG)
Which client version are you using?
Git Hash?
Modifications?

**Comment by aleos89** [comment]
I got the same exact results as @Lemongrass3110. The item dropped on to the ground and gave the message that I could not carry any more items because I am overweight. This is with 50% weight, not 90%.
