### ISSUE TITLE
Skill and Status lot of errors.

### ISSUE THREAD

**Issue by Lilori** [rathena/rathena#2036]
* **rAthena Hash**: latest rAthena

* **Client Date**: 2015-09-16

* **Server Mode**: RENEWAL

* **Description of Issue**: 
  * Result: Tiny damage all magic skill (exclude 3rd job) | wrong Hunter trap mechanic
  * Expected Result: Normal damage
  * How to Reproduce:
FOR MAGIC SKILL THAT HAS VERY LITTLE TINY DAMAGE :
1. Create mage/wiz/sage/high wiz/prof job.
2. Set it to level 99 | allstat 99 | no equipment.
3. Go pvp with any jobs lv99 | allstat 99 | no equipment
4. See the funny damage.
___________________________________________________________________

FOR HUNTER TRAP SKILL MECHANICSM :
1. Go with hunter trap with allstat 99 | use blastmine / claymore trap
2. First, we know that our renewal skill db is set by 0xF2 (which is mean split damage) let say we dealt 5k damage 1 monster. -->this is totally wrong
3. Now, set it the skill db by 0x42 (which is mean no split damage). we dealt 10k damage to 1 monster. --> true!
4. Correct mechanic: that should be 0x42 to 1 monster, and 0xF2 to 2 or more monster (because blastmine/claymore has splash arena dmg).

  * Official Information: 1 monster = normal damage of blastmine/claymore | 2 or more monsters(stick) = split area damage.

**Comment by walkietalkie89** [comment]
> 2. First, we know that our renewal skill db is set by 0xF2 (which is mean split damage) let say we dealt 5k damage 1 monster. -->this is totally wrong

from the description
```
// 06 nk (skill damage properties):
//    0x01 - No damage skill
//    0x02 - Has splash area
//    0x04 - Damage should be split among targets
//    0x08 - Skill ignores caster's % damage cards (misc type always ignores)
//    0x10 - Skill ignores elemental adjustments
//    0x20 - Skill ignores target's defense (misc type always ignores)
//    0x40 - Skill ignores target's flee (magic type always ignores)
// 0x80 - Skill ignores target's def cards
```
`0xF2` is from `0x80 + 0x40 + 0x20 + 0x10 + 0x02` ? or something?
can you try to change to 0xF6? so traps should be split, and if damage is half need to multiple damage by 2? official behavior is hard to understand (like women)

**Comment by Lilori** [comment]
0xF2 is from our beloved rAthena,

`122,3,6,2,4,0xF2,1,5,1,no,0,0x80,0,misc,0,0x3800,	HT_BLASTMINE,Blast Mine`

i have tried 0xF6, also that hex one by one. (0x02, 0x04, etc etc) and nothing changed.
You better try it by yourself, and then comment here you can reproduce or not, So i got support and this issue bumping.

**Comment by Playtester** [comment]
0xF2 does not even include split damage.

If you change 0xF2 to 0x42 you remove "Skill ignores elemental adjustments", "Skill ignores target's defense" and "Skill ignores target's def cards". So if anything, the damage difference comes from that.

I can run a few tests and compare damage on rAthena with damage on Aegis though. Any magical spells you want me to test?
Is the damage only low in PVP or also in PVM?

**Comment by Lilori** [comment]
If 0xF2 doesn't even include split damage, so what hex to include split damage?
I had already input 0x04 but the damage still not split to 2 or more mob. and my map-server show this
`[Error]: 0 enemies targeted by 122:HT_BLASTMINE, divide per 0 avoided!`
-------------------
For magical skills (mage,wiz,sage class), you can try it with fresh rAthena latest, no modification,
and as i said before, with allstat 99, magical skills are very very low (hit @10 damage).
![error](https://cloud.githubusercontent.com/assets/18497742/24604600/9a1b8bd8-188f-11e7-9380-6d8687937c6e.jpg)
does it make sense to you?
wiz 99 no equip, allstat 99 vs swordman 99 no equip, allstat 99.

**Comment by Lemongrass3110** [comment]
Which monster are you attacking?
"stats" does not sound like a monster name with "no modification" like you said.
Best would be if you paste the mob db entry for it.

**Comment by Lilori** [comment]
"stats" is not mob, its a player, i already explain it .__.

even it mob or player, does dealt same case, weird magic skill damage, and trap.

**Comment by Playtester** [comment]
The magic damage is official for renewal. Jupitel Thunder Level 10 with int 99, luk 99 vs. int 99, vit 99 deals around 80 HP damage per hit.

The trap damage is really bugged, however, something is completely off about our formula.

**Comment by Playtester** [comment]
Okay, after further testing, the problem in our formula is that we round down while Aegis uses float for the calculation. Easy to fix.
