### ISSUE TITLE
moc_ruins Kafra Voting Staff wrong NPC id.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [rathena/rathena#2037]
* **rAthena Hash**: 
Pass?

* **Client Date**: 
Any.

* **Server Mode**: 
Pre-Renewal

* **Description of Issue**: 
  * Result: Kafra Voting Staff has wrong NPC id, looks like Cool Event voting staff.
  * Expected Result: Should look like kafra girl npc. NPC ID: 112
![image](https://cloud.githubusercontent.com/assets/1968109/24594096/a7f22508-187d-11e7-94de-58d0e8f24039.png)

![image](https://cloud.githubusercontent.com/assets/1968109/24594060/4f19535c-187d-11e7-9a3d-9020bcf4d532.png)

But should look like this.

![image](https://cloud.githubusercontent.com/assets/1968109/24594787/a45d137e-1884-11e7-987b-0a1c5606385a.png)

* **Modifications**: 
```
moc_ruins,97,133,4	script	Kafra Voting Staff#moc	4_M_ZONDAMAN,{
	callfunc "F_VoteKafra",2;
}
```

Change to
```
moc_ruins,97,133,4	script	Kafra Voting Staff#moc	112,{
	callfunc "F_VoteKafra",2;
}
```

in the file ```npc/kafras/dts_warper.txt```

Just thought I would pass this on.
I'm actually moving this NPC

**Comment by Lemongrass3110** [comment]
From the AEGIS leak we have:
`npc "moc_ruins" "Huai Ta Vote Publicity Staff#morocc" 4_M_ZONDAMAN 97 133 6 0 0`

Did you confirm this on an official server? It might have been fixed since the last leak we got.

**Comment by Atemo** [comment]
Wrong aegis conversion, it should be
``` npc/kafras/dts_warper.txt | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/npc/kafras/dts_warper.txt b/npc/kafras/dts_warper.txt
index e822d18..c859650 100644
--- a/npc/kafras/dts_warper.txt
+++ b/npc/kafras/dts_warper.txt
@@ -690,7 +690,7 @@ yuno,162,191,4	script	Kafra Voting Staff#yuno	861,{
 prontera,164,125,4	script	Kafra Voting Staff#prt	116,{
 	callfunc "F_VoteKafra",2;
 }
-moc_ruins,97,133,4	script	Kafra Voting Staff#moc	4_M_ZONDAMAN,{
+moc_ruins,104,133,4	script	Kafra Voting Staff#moc	116,{
 	callfunc "F_VoteKafra",2;
 }
 geffen,122,37,4	script	Kafra Voting Staff#gef	116,{
@@ -1103,7 +1103,7 @@ lighthalzen,163,60,4	script	Kafra Voting Staff#lght	861,{
 
 yuno,153,191,6	duplicate(VotingStaffCCE)	Cool Event Staff#yuno	874
 prontera,147,125,6	duplicate(VotingStaffCCE)	Cool Event Staff#prt	874
-moc_ruins,104,133,6	duplicate(VotingStaffCCE)	Cool Event Staff#moc	874
+moc_ruins,97,133,6	duplicate(VotingStaffCCE)	Cool Event Staff#moc	874
 geffen,117,37,6	duplicate(VotingStaffCCE)	Cool Event Staff#gef	874
 payon,153,182,6	duplicate(VotingStaffCCE)	Cool Event Staff#pay	874
 alberta,114,70,6	duplicate(VotingStaffCCE)	Cool Event Staff#alb	874
```
Can you edit your PR please ?

**Comment by LiamKarlMitchell** [comment]
Ah I was not aware of any AEGIS info.
btw, where can I see that kind of stuff?

116 and Kafra vote 2?

**Comment by Akkarinage** [comment]
I think it depends on the region, as iRO's Chaos server uses the zondaman sprite and cutin.


![image](https://cloud.githubusercontent.com/assets/4101952/24884673/705ed68e-1e42-11e7-9295-babed6246175.png)

Anyone been on kRO recently to check?
