### ISSUE TITLE
[Critical] Emulator didn't load Renewal Db in Renewal mode

### ISSUE THREAD

**Issue by Yuchinin** [rathena/rathena#2040]
* **rAthena Hash**: a6b252c

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: The emulator only load pre-renewal item and monster db (item_db,monster_db) instead of renewal (item_db_re, monster_db_re)

  * Expected Result: I believe what only controlling the game mode are renewal.h which 'Renewal' are enable by default and I didn't modify that. It should be loading renewal database in renewal mode.

  * How to Reproduce: Update to latest and try to run the emulator.
* **Screenshot**: http://imgur.com/a/AZnRd

**Comment by Lemongrass3110** [comment]
Please take a look at 5d22e1c.
You probably have the wrong name in `renewal-item_table: item_db_re`

**Comment by Yuchinin** [comment]
My inter_athena.conf are in official state and are same as latest rAthena commit. 
The only problem is the emulator didn't read the renewal db.
I even download a fresh latest built and still getting the same result.
