### ISSUE TITLE
script_stop_sleeptimers uses already freed script state, can cause memory leak

### ISSUE THREAD

**Issue by Encon21** [rathena/rathena#2042]
* **rAthena Hash**: Probably everything since afa880e, confirmed on 8f82d04 and a6b252c.

* **Client Date**: Irrelevant (login not required)

* **Server Mode**: Pre-Renewal (shouldn't matter)

* **Description of Issue**: 
  * Result: script_stop_sleeptimers does nothing, because script state has already been freed in npc_unload by the time it's called. This _may_ result in a memory leak in specific cases (described below). 
  * Expected Result: script_free_state is not called if script state has already been freed
  * How to Reproduce: Unload any NPC that has a currently running sleep timer. Checking st->stack, st->oid, or any other part of st will show 0/null in script_stop_sleeptimers. **If (st->id == 0) exists in st_db when script_stop_sleeptimers is called, a memory leak can occur.** script_free_state will think the st is valid and proceed to "free" it, resulting in a delete_timer error (function mismatch) and the stack not being freed (because it's a null pointer from script_stop_sleeptimers). Nevertheless, it will still remove the entry from st_db. If the server later tries to free the actual st->id 0, it will fail because it no longer exists in st_db, and the memory will not be freed. 
  * Official Information:
  

* **Modifications that may affect results**: Confirmed on a vanilla rAthena.
  
  

Hopefully my description made sense, but if not it's fairly easy to see what I'm referring to by adding this to script_stop_sleeptimers before the script_free_state call:
`ShowError("script_stop_sleeptimers: %d 0x%08X %s %d\n", id, st->stack ? (void*)st->stack->stack_data : NULL, map_id2nd(st->oid) ? map_id2nd(st->oid)->name : "NULL", st->oid);`

Easiest way to get some console output is to start the server and shut it down immediately after map server is loaded (Ctrl+C on console). The error should happen every time, even on a completely unmodified rAthena, as some of the Gonryun quest scripts have a 10 second sleep in OnInit.

I think this can be fixed by simply adding a check for `(st->oid == id)` inside script_stop_sleeptimers, though I haven't tested it thoroughly to make sure it's stable (it should be though, as far as I can tell). @aleos89 would probably have some insight into this.

**Comment by aleos89** [comment]
Tested on a clean clone:
![image](https://cloud.githubusercontent.com/assets/3521753/24777247/7770bcec-1af2-11e7-8347-4bf85c7be4f2.png)

**Comment by Encon21** [comment]
I just tested on a clean copy as well, only modification being my error message, and got this output:
![script_stop_sleeptimers](https://cloud.githubusercontent.com/assets/17752219/24777401/0e5c5d64-1ada-11e7-9aca-a28f892a047c.png)

Did you add the ShowError call I mentioned in the bug report to script_stop_sleeptimers? The memory leak only occurs when specific conditions are met (st->id 0 exists in st_db), but the invalid script_state being sent to script_free_state will always happen. The ShowError call shows what I'm referring to - the script_state has already been freed before script_stop_sleeptimers is called.

If you did add the error output, the only other thing I can think of is that the server would have to shut down within 10 seconds of OnInit running for those 3 Gonryun quest NPCs (start01#gnbs, start02#gnbs, and start03#gnbs). If the sleep call ends before shutting down, everything will be cleaned up properly since script_stop_sleeptimers isn't called in that case.


Here's an example of the memory leak, tested on a clean copy as well - the only additional modification was adding an NPC named "GoldRoom" with a sleep call in OnInit.
![script_stop_sleeptimers_memoryleak](https://cloud.githubusercontent.com/assets/17752219/24777644/28383bc6-1adb-11e7-8fc6-7f09c382b2bf.png)

You can see in the last script_stop_sleeptimers output, the script state is actually valid because it hasn't actually been freed in npc_unload. This is because script_stop_sleeptimers was called with a freed script state first, which removed st->id 0 (GoldRoom in this case) from st_db. 

It fails to free the script state again when it's called from script_stop_sleeptimers, so the script state for GoldRoom is never freed.

**Comment by aleos89** [comment]
Ok, you are right. I was able to reproduce this. I had to trigger the termination a second earlier for the errors to display for me. Will fix this!
