### ISSUE TITLE
unitskillusepos cast time argument not working for NPCs

### ISSUE THREAD

**Issue by feltenc** [rathena/rathena#2045]
* **rAthena Hash**:https://github.com/rathena/rathena/commit/72fe4cd51591b917e9ae6654879b9275c405188c 

* **Client Date**: 2017-01-25RagexeRE

* **Server Mode**: Renewall

* **Description of Issue**: The cast time argument is not working as I believe should work.

  * Result: All skills gets Instant Cast
  * Expected Result: I believe the cast time argument is to add a cast time to the desired skill. I tested it with several values, 1, 100, 1000 and 10000 and the skills always get instant cast.

  * How to Reproduce: 
Use the script below
```
prontera,150,150,4	script	UnitSkillUsePos	54,{
	unitskillusepos getnpcid(0),83,1,152,152,10000;
	end;
}
```

Click on it and the npc will cast Meteor Storm Instant Cast.

  * Official Information: *
`unitskillusepos <GID>,"<skill name>",<skill lvl>,<x>,<y>{,<casttime>};`

`Skill ID is the ID of the skill, skill level is the level of the skill.
Cast time is the amount of seconds to add or remove from the skill. Use a positive value to
add and negative value to subtract. Using 0 or no value will use the default skill cast time.
For the position, the x and y are given in the UnitSkillUsePos.`

**Comment by Lemongrass3110** [comment]
Well I can confirm this, but nevertheless this looks like intended behavior, as you can see here:
https://github.com/rathena/rathena/blob/master/src/map/unit.c#L2038

Additionally the argument is very unreliable in renewal, since it also goes through all the variable and fixed cast time calculations and you probably will end up with an other cast time than you actually expected.

**Comment by feltenc** [comment]
Hey @Lemongrass3110 thanks,

What I'm trying to do is to put a "progressbar" on top of a npc like it's casting a skill, but I can not. Until I found the unituseskillpos that gave me the cast time argument. I thought he would be the solution to my problems. Whatever, I need to make npcs cast skills, this is used in official instances of ragnarok, or at least put a progressbar on top of NPC's where currently it is only possible to use progressbar in players.

**Comment by Lemongrass3110** [comment]
I know what you are referring to. :-) The npc progressbar feature will be implemented shortly.

**Comment by feltenc** [comment]
Thanks, waiting anxious for this implementation.

**Comment by kukuasir1** [comment]
@feltenc about the npc progressbar you can see 
https://github.com/rathena/rathena/issues/1473

**Comment by feltenc** [comment]
Thanks @kukuasir1 ! I will look into it.

btw, waiting the fix for cast time on unitskillusepos.
