### ISSUE TITLE
[Critical] Walk after IC Skill cast or NPC interaction

### ISSUE THREAD

**Issue by guippiccoli** [rathena/rathena#2046]
* **rAthena Hash**: 4b9ade33ee4f89bc65b3ec272eb5c5e6a5966838

* **Client Date**: tested with 2014-02-05bRagexe, 2015-05-13aRagexe, 2015-11-04aRagexe

* **Server Mode**: Both

### Description of Issue:

**Before anything: It bodered me that no one has talked about that before. The NPC bug is anoying at most, but the Skill bug is game breaking. Thats FAR from official interaction and impossible to run a serious server with that.**

Unwanted player movement after NPC or Skill interaction. Tested with Hercules also, same bug. Characters is moving to the mouse location after cast an instant skill or talk with an npc that has no mes() function.

**Prints**
- [NPC Bug](https://media.giphy.com/media/xUPGck4N4wytK97GLu/giphy.gif)
![NPC Bug](https://media.giphy.com/media/xUPGck4N4wytK97GLu/giphy.gif)
- [Skill Bug](https://media.giphy.com/media/xUPGcr7rZkvrxZWRJC/giphy.gif)
![Skill Bug](https://media.giphy.com/media/3ohzdX8zORtTbbK7Is/giphy.gif)

### Result:
- **When clicking a NPC that have no mes() function**: The npc click event is triggered but the player also walks to the mouse position.
- **When using intant casts skill (150 dex SG, arrow shower, etc) (only one click)**: The skill is evoked but the player also walks to the mouse position

### Expected Result:
- **When clicking a NPC that have no mes() function**: Trigger the NPC and not move the character.
- **When using intant casts skill (150 dex SG, arrow shower, etc) (only one click)**: Evoke the skill and not move after cast.

### How to Reproduce: 
1. Download rAthena-> Compile
2. Cast an instant skill (usualy preRE since RE has fixed cast formula)
3. The character will cast the skill then walk to the mouse location as if the skill cast click had also the interaction of a normal click (walk). See the pictures of test for yourself to understand better.

**Comment by Playtester** [comment]
I tested this on both renewal and pre-renewal and it works fine on both. Must probably be a bug on your client or some mouse mod that causes clicks to register twice.

**Comment by sader1992** [comment]
unchecking 
Change Walk To Delay
Disable Walk To Delay
in nemo would fix this problem

**Comment by LiamKarlMitchell** [comment]
Hmm, well that is awkward if its the cause.
If wanting to, modify the delay till you find one that does not act like above maybe it could be the new default...

**Comment by VeilsideGX** [comment]
Is there a way to fix this without disabling the "Change Walk Delay" in nemo? I find this diff really helpful specially in low latency hosts.

**Comment by LiamKarlMitchell** [comment]
Thanks @VeilsideGX , just increase the delay a little bit or tell people to click faster or extend the patch somehow to make it configurable.
Or you could have the game load a DLL which then applies the patch runtime based on the setting from an ini and add the setting into one of the open source setups.
