### ISSUE TITLE
SU_PICKYPECK_DOUBLE_ATK

### ISSUE THREAD

**Issue by hartonox** [rathena/rathena#2047]
* **rAthena Hash**: 

* **Client Date**: 

* **Server Mode**: 

* **Description of Issue**: 
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**: 
  
  

Picky Peck Double Attack not effect when enemy hp <50%

**Comment by Atemo** [comment]
This issue will be solved later in https://github.com/rathena/rathena/pull/1965
