### ISSUE TITLE
Unisex client regarding Taekwon

### ISSUE THREAD

**Issue by sapquer** [rathena/rathena#2048]
* **rAthena Hash**: Latest

* **Client Date**: 20151104

* **Server Mode**: 

* **Description of Issue**: Creating a female Taekwon character on a male account displays Taekwon Boy and Taekwon Girl on a Female account, while kagerou and oboro works fine. also `@changesex` crashes the client
  * Result: 
  * Expected Result: 
  * How to Reproduce: username_m / create a female char / `@job` taekwon
  * Official Information: iRO's renewal client show the right job (not really a reliable source)
  

* **Modifications that may affect results**:

**Comment by Daegaladh** [comment]
I can confirm the same issue using 2015-05-13aRagexe, but I'm not sure if this is really a server issue but the client or the lua files

**Comment by Lemongrass3110** [comment]
Please use quotes when you refer to atcommands. You link people that are not related to rAthena in any kind. job is a valid username in this case.

**Comment by Lemongrass3110** [comment]
Client shows the opposite sex for me too, but this is most certainly a data(lua) or diff problem.
It does not cause any crashes for me to use `@changesex` though.

**Comment by secretdataz** [comment]
No further input from the issue owner, closing the issue.
