### ISSUE TITLE
Latest Version Rathena cant use extended vending

### ISSUE THREAD

**Issue by mjonrest** [rathena/rathena#2049]
* **rAthena Hash**: 

* **Client Date**: 

* **Server Mode**: 

* **Description of Issue**: 
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**: 
  
  

> vending.c: In function 'vending_vendinglistreq':
vending.c:95: warning: implicit declaration of function 'clif_colormes'
vending.c: In function 'vending_purchasereq':
vending.c:197: error: 'struct mmo_charstatus' has no member named 'inventory'
vending.c:198: error: 'struct mmo_charstatus' has no member named 'inventory'
vending.c:286: error: 'struct mmo_charstatus' has no member named 'inventory'
vending.c:289: error: 'struct mmo_charstatus' has no member named 'inventory'
vending.c:334: error: 'struct mmo_charstatus' has no member named 'cart'
vending.c:342: warning: implicit declaration of function 'clif_disp_onlyself'
vending.c: In function 'vending_openvending':
vending.c:478: error: 'vendings_db' undeclared (first use in this function)
vending.c:478: error: (Each undeclared identifier is reported only once
vending.c:478: error: for each function it appears in.)
make[1]: *** [obj/vending.o] Error 1
make[1]: Leaving directory `/root/Trunk/src/map'
make: *** [map] Error 2

what happen to this error? using latest extended vending and latest rathena git.
can anybody help me to solve this?

thanks

**Comment by Akkarinage** [comment]
Can you fill in the information that you're asked for please?

**Comment by RadianFord** [comment]
This is not related on rAthena, the source that you are using is not compatible anymore.

**Comment by Lemongrass3110** [comment]
This is not an rAthena feature. You are talking about rAthenaMod which is outdated. You are free to contact the person that provided the diff/patch for you.
