### ISSUE TITLE
Shield Boomerang Bug.

### ISSUE THREAD

**Issue by anacondaqq** [rathena/rathena#205]
Shield Boomerang work the same like Shield Charge. (repels)

Information:

pre-renewal
clean and latest (06.01.2015) rAthena
20100730

How to reproduce:
1. Login in game
2. Create Paladin
3. @monster Alice
4. Use Shield Boomerand on Alice
5. Alice will be repel very very far from you.

Shield Boomerand must NOT REPEL!

**Comment by anacondaqq** [comment]
I found problem:

The problem in missed "0x" before number

251,3:5:7:9:11,6,1,0,0,0,5,1,no,0,0,0,weapon,20000,0x0,	CR_SHIELDBOOMERANG,Shield Boomerang

Must be:

251,3:5:7:9:11,6,1,0,0,0,5,1,no,0,0,0,weapon,0x20000,0x0,	CR_SHIELDBOOMERANG,Shield Boomerang

**Comment by Playtester** [comment]
Not really, that field is Blewcount and should be 0.

Correct would be: 
251,3:5:7:9:11,6,1,0,0,0,5,1,no,0,0,0,weapon,0,0x20000, CR_SHIELDBOOMERANG,Shield Boomerang

**Comment by cydh** [comment]
@aleos89 done?

**Comment by aleos89** [comment]
I have a diff of a few things.
