### ISSUE TITLE
setiteminfo issue

### ISSUE THREAD

**Issue by Yuchinin** [rathena/rathena#2050]
* **rAthena Hash**: latest

* **Client Date**: 20151029

* **Server Mode**: RENEWAL

* **Description of Issue**: 
  * Result: Item set with script command setiteminfo <id>,2,11 (delayed consumption) set item type to equipment instead of delayed consumption item and fail to execute the script.
  * Expected Result: It should change it to type 11 (delayed consumption) and read the script on used but it change it's type to equipment instead.
  * How to Reproduce: Set and item to type 11 with this command and figure it out.
 
* **Modifications that may affect results**: -

**Comment by Lemongrass3110** [comment]
Could you post a sample script and tell us how you noticed it was set to "equip" instead?

For me it was working perfectly fine(item type and the effect did not trigger anymore):
![screenrathena027](https://cloud.githubusercontent.com/assets/3517879/24840933/fae950c0-1d77-11e7-8c26-eeb4e6a0ac18.jpg)

I used this script:
```
-	script	OnInit	-1,{
	end;

OnInit:
	setiteminfo 607,2,11;
}
```

**Comment by Yuchinin** [comment]
It will appear just fine if you check it with atcommand '@ii'.
I noticed it been change to equip because it show the changed item in Equipment tab in my inventory.

**Comment by Lemongrass3110** [comment]
This did not happen for me. As I said please post your sample. My sample did work without problems maybe it is caused by some item attributes.
Could you try if your issue is reproduceable with my script?
Thank you.

**Comment by Yuchinin** [comment]
Script I use:

`-	script	OnInit	-1,{
	end;

OnInit:
	setiteminfo 607,2,11;
}`

Same result.
http://imgur.com/a/6Dv7q

**Comment by Akkarinage** [comment]
Confirmed working as intended. Hash c6c8d0bc8884f683f7d66c31e741e0a3031c5e12 RE mode client 20151104.

Script used: 
```
prontera,156,174,5	script	OnInitTest	123,{
	setiteminfo 607,2,11;
	end;
}
```
Result:
![ss 2017-07-11 at 06 28 10](https://user-images.githubusercontent.com/4101952/28081341-d517bdea-6666-11e7-9d09-62a850b594f3.jpg)
