### ISSUE TITLE
error

### ISSUE THREAD

**Issue by heeroyuy180** [rathena/rathena#2053]
char.c: In function ‘char_read_fame_list’:
char.c:1976:203: error: ‘JOB_BABY_TAEKWON’ undeclared (first use in this function)
  if( SQL_ERROR == Sql_Query(sql_handle, "SELECT `char_id`,`fame`,`name` FROM `%s` WHERE `fame`>0 AND (`class`='%d' OR `class`='%d') ORDER BY `fame` DESC LIMIT 0,%d", schema_config.char_db, JOB_TAEKWON, JOB_BABY_TAEKWON, fame_list_size_taekwon) )

**Comment by heeroyuy180** [comment]
New baby jobs errors on clean rAthena

[Status]: Done reading '0' entries in 'db/import/skill_tree.txt'.
[Debug]: Message #699 not found for langtype 0.
[Debug]: Selected langtype 0 not loaded, trying fallback...
[Warning]: Class ?? (4220) does not have a base exp table.
[Debug]: Message #699 not found for langtype 0.
[Debug]: Selected langtype 0 not loaded, trying fallback...
[Warning]: Class ?? (4220) does not have a job exp table.
[Warning]: Class Invalid time for VIP command. (4222) does not have a base exp t       able.
[Warning]: Class Invalid time for VIP command. (4222) does not have a job exp ta       ble.
[Debug]: Message #753 not found for langtype 0.
[Debug]: Selected langtype 0 not loaded, trying fallback...
[Warning]: Class ?? (4223) does not have a base exp table.
[Debug]: Message #753 not found for langtype 0.
[Debug]: Selected langtype 0 not loaded, trying fallback...
[Warning]: Class ?? (4223) does not have a job exp table.
[Debug]: Message #754 not found for langtype 0.
[Debug]: Selected langtype 0 not loaded, trying fallback...
[Warning]: Class ?? (4224) does not have a base exp table.
[Debug]: Message #754 not found for langtype 0.
[Debug]: Selected langtype 0 not loaded, trying fallback...
[Warning]: Class ?? (4224) does not have a job exp table.
[Debug]: Message #755 not found for langtype 0.
[Debug]: Selected langtype 0 not loaded, trying fallback...
[Warning]: Class ?? (4225) does not have a base exp table.
[Debug]: Message #755 not found for langtype 0.
[Debug]: Selected langtype 0 not loaded, trying fallback...
[Warning]: Class ?? (4225) does not have a job exp table.
[Debug]: Message #756 not found for langtype 0.
[Debug]: Selected langtype 0 not loaded, trying fallback...
[Warning]: Class ?? (4226) does not have a base exp table.
[Debug]: Message #756 not found for langtype 0.
[Debug]: Selected langtype 0 not loaded, trying fallback...
[Warning]: Class ?? (4226) does not have a job exp table.
[Debug]: Message #757 not found for langtype 0.
[Debug]: Selected langtype 0 not loaded, trying fallback...
[Warning]: Class ?? (4227) does not have a base exp table.
[Debug]: Message #757 not found for langtype 0.
[Debug]: Selected langtype 0 not loaded, trying fallback...
[Warning]: Class ?? (4227) does not have a job exp table.
[Debug]: Message #758 not found for langtype 0.
[Debug]: Selected langtype 0 not loaded, trying fallback...
[Warning]: Class ?? (4228) does not have a base exp table.
[Debug]: Message #758 not found for langtype 0.
[Debug]: Selected langtype 0 not loaded, trying fallback...
[Warning]: Class ?? (4228) does not have a job exp table.
[Debug]: Message #759 not found for langtype 0.
[Debug]: Selected langtype 0 not loaded, trying fallback...
[Warning]: Class ?? (4229) does not have a base exp table.
[Debug]: Message #759 not found for langtype 0.
[Debug]: Selected langtype 0 not loaded, trying fallback...
[Warning]: Class ?? (4229) does not have a job exp table.
[Debug]: Message #756 not found for langtype 0.
[Debug]: Selected langtype 0 not loaded, trying fallback...
[Warning]: Class ?? (4238) does not have a base exp table.
[Debug]: Message #756 not found for langtype 0.
[Debug]: Selected langtype 0 not loaded, trying fallback...
[Warning]: Class ?? (4238) does not have a job exp table.

**Comment by Lemongrass3110** [comment]
You merged 39e54d6 badly.
