### ISSUE TITLE
Homunculus Eleanor Combo Insta Kill All Mobs

### ISSUE THREAD

**Issue by feltenc** [rathena/rathena#2058]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/3cce333fc69766a04823eb3bd8bc7bc86061bab6 

* **Client Date**: 2017-01-25RagexeRE

* **Server Mode**: Renewall

* **Description of Issue**: Eleanor Homunculus is causing instakill in any monster, be it boss or even the prontera dummys. We tested with the prontera dummies and it killed them in less than 5 seconds, we also tested with some mvps like Ifrit and some other mvp's.

  * Result: Game Broken
  * Expected Result: Normal hits/damage
  * How to Reproduce: Summon a Eleanor with Biochemist/Creator and use the Eleanor Combo on bosses or dummies.
  * Official Information: None

* **Modifications that may affect results**: None

Replay Link: https://mega.nz/#!1IJBVA7b!gHHty6ttgUGQn9k1EskQ6OVhDVHjemUCJZrWYUuFz0A

**Comment by admkakaroto** [comment]
In the map_server also some error messages appear when changing the mode of the homunculus.

http://imgur.com/TQTGhRQ


I also confirm the bug using Eternal Quick Combo.

**Comment by Jeybla** [comment]
I can confirm this bug. Damage is over 9m!

I'll have a closer look into it.

**Comment by Jeybla** [comment]
Seems to be a wrong skill formula for `Eternal Quick Combo`.

I can confirm this bug report. But I don't get any error message.
> In the map_server also some error messages appear when changing the mode of the homunculus.

**Comment by Jeybla** [comment]
Thanks to @aleos89 for testing the skill on aegis! The damage formula is correct.

We'll just disable the skill on boss type monster.

**Comment by feltenc** [comment]
Nice! congratulations for your job guys, you are all amazing!
