### ISSUE TITLE
Empe hitting problem and custom problem

### ISSUE THREAD

**Issue by kmilo623** [rathena/rathena#2059]
20150513.exe client diffed on ClassiIncfo.lua
Pre-Renewal 

Im getting two error.

The first one it's easier to explain. Whenever i summon an empe i cant hit'im every single time, 0% missing. However when i actitave woe and go there for killing the empe i just can't hit'im. Every single strike miss, idk why...even if it's a summoned empe inside the castle...

The second one it's that i can't see my custom items, all of them are apples, unknown items... I've been doing every step i find in guides and that stuff but it just don't work.

I eddited the ACCESORYID.LUA and ACCNAME.LUA with the exact sprite name, also copy the .spr and .act inside \data\sprite\¾Ç¼¼»ç¸®\¿© and \data\sprite\¾Ç¼¼»ç¸®\³² and ofc the .bmp inside collection, drop and item. Also eddited iteminfo and created new GRF....everything seems to be right. But when i use @item to get it....just don't show off. HELP PLEASE!

**Comment by srhmike** [comment]
You should go ask in the forums.  Those are bugs, more likely user error.

**Comment by kmilo623** [comment]
I'm sorry i'm new in here. Going to the forum right now, my bad,
