### ISSUE TITLE
Update Crimson Weapon drop from monster

### ISSUE THREAD

**Issue by hendra814** [rathena/rathena#2060]
* **rAthena Hash**: lastest

* **Client Date**: 2015-11-04

* **Server Mode**: Renewal

* **Description of Issue**: monster not drop Crimson Weapons
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**: 
  
  

for referal monster drop crimson weapon
https://www.novaragnarok.com/forum/news/crimson-weapons-r78/

**Comment by Lemongrass3110** [comment]
#1743

**Comment by feltenc** [comment]
I suggest you start taking a look at the pull requests tab before reporting on an official feature that has not yet been implemented .. There are a number of features waiting for testing / reviews to be released.

https://github.com/rathena/rathena/pull/1708
https://github.com/rathena/rathena/pull/1743

**Comment by hendra814** [comment]
@Lemongrass3110 @feltenc 
sorry, but thanks for the information.

**Comment by Lemongrass3110** [comment]
Implemented in e59cdff
