### ISSUE TITLE
Firecracker item 12018 and 12326 do not show effect on pre-renewal.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [rathena/rathena#2069]
* **rAthena Hash**: 
Recentish.
948e2bdc0a70174c76fd303dfa2cee376c2d639d

* **Client Date**: 
2015-09-16a

* **Server Mode**: 
Pre-re

* **Description of Issue**: 
  * Result: Firecracker items not showing the effect.
  * Expected Result: The items effect happens.
  * How to Reproduce: Login with pre-renewal 2015 client.

Give your self item 12018 or 12326.
Use it.
No effect and item stays?

Solution: Needs to have end; in the item script.

-- Fix Firecracker and Large Firecracker. (Un-useable as script does not have anything in it...)
UPDATE item_db SET script = 'end;' WHERE id = 12018 OR id = 12326;

I tried to fix this in the item_db.txt but github gives an error that its to big to submit in post.
I guess need to do it by using git client instead.

**Comment by Jeybla** [comment]
Confirmed. Thanks for the report @LiamKarlMitchell !

Current DB entries (re & pre-re):
```
12018,Fire_Cracker,Firecracker,2,2,,20,,,,,0xFFFFFFFF,7,2,,,,,,{},{},{}
12018,Fire_Cracker,Firecracker,2,2,,20,,,,,0xFFFFFFFF,63,2,,,,,,{},{},{}
12326,J_Firecracker,Large Firecracker,2,2,,20,,,,,0xFFFFFFFF,7,2,,,,,,{},{},{}
12326,J_Firecracker,Large Firecracker,2,2,,20,,,,,0xFFFFFFFF,63,2,,,,,,{},{},{}
```

Adding an `end;` seems like a workaround for me. There likely is a condition checking for empty scripts in usable items and just disables them. We should evaluate if we want to keep this condition and add this "workaround" or just drop the condition.

**Comment by LiamKarlMitchell** [comment]
I suppose it depends maybe an item can be mistakenly added as usable and it is there to prevent that?
But seems silly to me.

Why would such a condition exist?

Where might I find the item use function so I can see if there are any comments or commit history as to why that would be put in?

> I also generally always have to modify the wedding dress/tuxedo as well so that they apply costume/can be equiped and worn. (This is in the past i have not checked yet).

**Comment by aleos89** [comment]
It's from `pc_isUseitem`:
```c
	if( !item->script ) //if it has no script, you can't really consume it!
		return false;
```
I'm not sure of the intent on this check. If the item is already usable, not sure why we would stop it from executing, even if it has no script.
