### ISSUE TITLE
 /memo to moscovia fild02

### ISSUE THREAD

**Issue by TheNoobCompany** [rathena/rathena#2071]
* **rAthena Hash**: 
a75133eb4d8976c1c890d5420665e7a76349e226

* **Client Date**: 
all

* **Server Mode**: 
pre-renewal AND renewal

* **Description of Issue**: 
  * Result: I cannot /memo on map mosk_fild02 and I can use the warp from fild02 to dun01 without the quest.
Also, if I teleport on map mosk_fild02, I shouldn't be able to use the warp to mosk_dun01 without having the quest completed.

  * Expected Result: I can /memo on the mosk_fild02 map and if I warp someone there that doesn't have the quest, he wont be able to enter the dungeon. 
  * How to Reproduce: try to /memo on mosk_fild02
  * Official Information: 
http://irowiki.org/classic/Moscovia 
http://irowiki.org/wiki/Moscovia

 (the map with dungeon entrance can be memo-ed).

  

* **Modifications that may affect results**: 
npc\warps\dungeons\mosk_dun.txt

mosk_fild02,190,257,0	warp	moscoviawarp0401	1,1,mosk_dun01,189,45

We must add the following check 
`if(!mos_whale_edq || mos_whale_edq < 35) {means no access}`
on the warp "moscoviawarp0401" to prevent user without the quest from warping to there.
also must remove the "nomemo" on the map mosk_fild02

I have no official info about the refusal message in itself tho

**Comment by TheNoobCompany** [comment]
After further research, seems to be iRO only and not kRO.

**Comment by aleos89** [comment]
I just had a look and the Aegis script for the warp from the field to the dungeon you referenced above does not have any checks. I can do some tests later to confirm the memo-able states.

**Comment by aleos89** [comment]
Tests on Aegis proved that I can not memo the Moscovia fields or dungeons. So the current setup of rAthena blocking those maps from being memo-able is valid. The information you referenced must be specifically what iRO allowed.
