### ISSUE TITLE
Homunculus default config doesn't match official server

### ISSUE THREAD

**Issue by TheNoobCompany** [rathena/rathena#2073]
* **rAthena Hash**:  a75133eb4d8976c1c890d5420665e7a76349e226

* **Client Date**: ALL

* **Server Mode**: BOTH

Explanations:

The default config available here: https://github.com/rathena/rathena/blob/5f20c0ce0cbe4bc22b8bf1df9c36c0ef9a480ef3/conf/battle/homunc.conf

States that you can `@autoloot` by default when the homunculus killed the monster 100% without any interact from the player, this is not like that on official server so the default value should be changed.
It's server admin choice to turn it on if they want that, right?

Also, about Vaporize, it's more complicated than just "vaporize if alchemist is dead".

Here the official server algo:
Whenever the player dies, if the homunculus is above 80% HP, it will automatically be Vaporized. If it is below 80%, it will not vaporize and is able to continue to fight, and the player continues to receive EXP from Homunculus, but manual commands cannot be used.

Impossibilities:
Auto Looting

Link:
http://irowiki.org/classic/Homunculus_System
http://irowiki.org/wiki/Homunculus_System

**Comment by aleos89** [comment]
As for the autolooting, yes that should be off by default and the server owner should adjust that setting as needed.

As for Vaporize, I would have to confirm that as I haven't played around with a homunculus on official servers before.
