### ISSUE TITLE
Royal Guard Kings Grace 

### ISSUE THREAD

**Issue by sikiro** [rathena/rathena#2078]
* **rAthena Hash**: Latest

* **Client Date**: 20151104

* **Server Mode**: Renewal 

* **Description of Issue**:  Royal Guard Kings grace will teleport a low hp mvp upon casting it no modifications to the src has been made. this may be official behavior i am not sure.
  * Result: 
  * Expected Result: 
  * How to Reproduce: attack an mvp and use kings grace when hp is bellow 30%  
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Jeybla** [comment]
iRo Wiki: http://irowiki.org/wiki/King%27s_Grace
> Places a temporary buff on the user and all players nearby that **blocks all damage**.

Monsters usually teleport away if they get damage from a source they can't attack. I think that's the case here.

**Comment by aleos89** [comment]
As @Jeybla stated, the monster probably thinks they are being rude-attacked and flee (Teleport) which is official behavior.
