### ISSUE TITLE
autobonuses on the same equipment block each other

### ISSUE THREAD

**Issue by Tokeiburu** [rathena/rathena#2079]
* **rAthena Hash**: 97f989f7d8a156edbd636342923d4898c20f715f

* **Description of Issue**: If you have multiple autobonuses in the same equipment, you will not be able to proc the other ones once any of them triggers.

This issue happens when the character is recalculating its statuses after executing the autobonus script by calling `status_calc_pc(sd,SCO_FORCE);`. It then parses the equipment (and cards) in `status_calc_pc_` and the autobonuses get recaculated in script.c > BUILDIN_FUNC(autobonus2):
```
	if (current_equip_combo_pos)
		pos = current_equip_combo_pos;
	else
		pos = sd->inventory.u.items_inventory[current_equip_item_index].equip;

	if((sd->state.autobonus&pos) == pos)
		return SCRIPT_CMD_SUCCESS;
```

Since the equipment is already being used in an autobonus, it skips this part and doesn't add the autobonuses back (they are removed at the beginning of status_calc_pc_).

This also causes more problems when the autobonus that procs is not the first one in the lists of sd->autobonus(2). All autobonuses of that type will be blocked because of
```
	//Autobonus when attacked
	if( dstsd && !status_isdead(bl) && dstsd->autobonus2[0].rate && !(skill_id && skill_get_nk(skill_id)&NK_NO_DAMAGE) ) {
		int i;
		for( i = 0; i < ARRAYLENGTH(dstsd->autobonus2); i++ ) {
			if( rnd()%1000 >= dstsd->autobonus2[i].rate )
```
since it checks if dstsd->autobonus2[0].rate is non-zero and it was never added back. (Then again, that's just a side-effect of the first issue.) This fixes itself once the autobonus' timer runs out and does another `status_calc_pc(sd,SCO_FORCE);`.
  * Expected Result: Aubonuses should be independent of each other.
  * How to Reproduce: It's tricky to reproduce. The bug was initially reported to me with a Temporal Dex Boots[27014,0,0,4878]. It is impossible to trigger the recovery effect of Green Cenere Card + Muscular Endurance at the same time.

* **Modifications that may affect results**: None.

**Comment by Stolao** [comment]
Can Confirm this.

**Comment by Playtester** [comment]
Yes, it's basically "intentional" because it was too complex to code something that allows for this.

**Comment by aleos89** [comment]
Just ran across this issue. This should be retested against PR #3235 (from [here](https://github.com/rathena/rathena/pull/3235/files#diff-3d4be49d2aa3e8a08452d63564ba70aaL2510)) since now the autobonus is checked against the vector size rather than the array[0]'s rate value.
