### ISSUE TITLE
Quagmire slow should work on MVP on pre-renewal

### ISSUE THREAD

**Issue by TheNoobCompany** [rathena/rathena#2084]
* **rAthena Hash**: 

33c31ca3686b25205acb4e6ddb719b564831ae02

* **Client Date**: 

20130807

* **Server Mode**: 

Pre-renewal

* **Description of Issue**: 
  * Result: 
Even tho the skill tooltip says it doesn't work on MVP, it's only valid for the agi/dex, not for the slow.

  * Expected Result: Quagmire should slow boss type as well.
  * How to Reproduce: Kite a MVP inside a quagmire.
  * Official Information:
http://forums.irowiki.org/index.php?topic=50009.0
renewal wiki confirm it: http://irowiki.org/wiki/Quagmire

I can't find it, but an update from 2008~ allowed quagmire to work on mvp pre-renewal if I'm not mistaken.

**Comment by Playtester** [comment]
Are you referring to this? https://github.com/rathena/rathena/issues/904

**Comment by TheNoobCompany** [comment]
No, unless all MVP have agi up ? (not sure)

**Comment by Playtester** [comment]
Okay, in that case I have to consider this report invalid, because Quagmire already works on MVPs just fine. Just tested it again to make sure.

It only doesn't work if the MVP used NPC_AGIUP as already mentioned in the other issue.
