### ISSUE TITLE
Shield Press 

### ISSUE THREAD

**Issue by jamon18** [rathena/rathena#2085]
shield press Stun duration is not reduced by stats. However, it is reduced by Base Level (unconfirmed).
http://irowiki.org/wiki/Shield_Press
server renewal

**Comment by Playtester** [comment]
Tested:

Level 1 Shield Press vs Level 150 Sura: 5.5 sec
Level 5 Shield Press vs Level 150 Sura: 7.5 sec
Level 5 Shield Press vs Level 150 Sura with 40 Vit: 7.5 sec

Level 1 Shield Press vs Level 17 Acolyte: 5.5 sec
Level 5 Shield Press vs Level 17 Acolyte: 7.5 sec

Seems that the duration is completely unreducable?

**Comment by jamon18** [comment]
According to iro is completely unreducable to stats , but with equipment and baselvl 
i nid more oficial information 
u can help me @Playtester

**Comment by Playtester** [comment]
Do you want me to do another test? The test above already proves base level does not reduce the duration. What equipment?
