### ISSUE TITLE
Fallen Angel skill bug

### ISSUE THREAD

**Issue by TrueNoir** [rathena/rathena#2086]
* **rAthena Hash**: 7bf0667c78ca67854ff9d63024c46dda9e8605ce

* **Client Date**: 2015-11-04aRagexe

* **Server Mode**: Renewal

* **Description of Issue**: Fallen Angel skill jumps to the target but after it should cast Desperado equal to the level learned but all it does is jump to the target. We checked to make sure it wasn't blocked by a wall so that wasn't the issue and used revolver and made sure we had coin. 
  * Result:  Character jumps to target but doesn't trigger Desperado
  * Expected Result:  Desperado of characters level should be cast
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**: N/A

**Comment by aleos89** [comment]
Can you test #1692?

**Comment by TrueNoir** [comment]
Tested with #1692 and the issue is still happening fallen angel skill jumps to the target but doesn't cast  Desperado.

**Comment by aleos89** [comment]
Ah, sorry. This is actually the previous behavior of the skill. In the Rebel Awakening patch (the PR I linked) the skill was changed to just a snap-like skill. The after-cast of Desperado was removed. So this is working as intended.
