### ISSUE TITLE
Metallic Sould

### ISSUE THREAD

**Issue by jamon18** [rathena/rathena#2088]
server renewal 
Metal sound in pseudo elemental neutral - with the element wind endowing in the weapon (no arrow) / taking element metal sound damage
ej: best weapon + scroll endow element wind + gioia card = 55k per hit
this is bug?
http://irowiki.org/wiki/Metallic_Sound
http://irowiki.org/wiki/Category:Forced_Element_Skills

**Comment by Jeybla** [comment]
I'll have a look at it but close this issue anyway, because it is very related to #2025 .
