### ISSUE TITLE
rapid throw bypass royal guard defender

### ISSUE THREAD

**Issue by jamon18** [rathena/rathena#2090]
rAthena Hash:
Client Date: 2015-10-29
Renewal:
Description of Issue:
Throws a lot of money at a targeted location, which has a chance to inflict massive piercing damage to all enemies within the area of effect. But preneuma blocked Rapid Throw and Neutral Barrier becasue bypass defend?
This is in category Ranged Skills (defender blocked to long attack)
this is bug in bypass defender skill royal guard?

**Comment by aleos89** [comment]
Works the same as Throw Zeny.
