### ISSUE TITLE
Shadow Chaser Maelstrom + Feint Bomb Combo crash the server

### ISSUE THREAD

**Issue by spangler88** [rathena/rathena#2094]
* **rAthena Hash**: Git Hash: '4f99567e41935987a99ac729104557c77a7d137b'

* **Client Date**: 2015-11-04a

* **Server Mode**:  Renewal

* **Description of Issue**: 
  * Result: Map Server Crash. [Error]: Server received crash signal! Attempting to save all online characters!
  * Expected Result: It works fine and no crash. This happens after Feint Bomb Behaviour Update
  * How to Reproduce: Use of skill Maelstrom followed by Feint Bomb while Maelstrom is active will crash the server. If it's not, you may want to try Maelstrom followed by Reject Sword and then Feint Bomb.

* **Modifications that may affect results**: 
It start happening after I am updating my server with Shadow Chasers Commit. It work perfectly fine before. Possible broken commits
https://github.com/rathena/rathena/commit/caed38927ac6edd327a63488ec5d3a0fe1fedb9f
https://github.com/rathena/rathena/commit/1261d92c43f0e410333f9c48c6bc0dd4f2274968

**Comment by Playtester** [comment]
https://github.com/rathena/rathena/commit/caed38927ac6edd327a63488ec5d3a0fe1fedb9f

This issue is probably:
```
			struct skill_unit_group *group = skill_unitsetting(src,skill_id,skill_lv,x,y,0); // Set bomb on current Position

			map_foreachinrange(skill_mob_releasetarget, src, AREA_SIZE, BL_MOB, src, &group->unit->bl); // Release all targets against the caster.
```
If the pointer on group is NULL (which is the case when unitsetting failed), it will crash.
