### ISSUE TITLE
Dragon Breath | Dragon Breath Wather CoolDown, Reset

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#2096]
* **rAthena Hash: https://github.com/rathena/rathena/commit/cbc3b260c849d3101ee5cda72206a803d8cdb470** 
* **Mode**: Renewal
* **Description of Issue**: If the player receives damage after casting these abilities, their cooldown is reset, thus allowing them to use the skill an absurd amount of times.
  * Result: The player can repeatedly cast the ability by completely ignoring the cooldown.
  * Expected Result: The expected result can be seen in the video below.
  * How to Reproduce: The way to play can be seen in the video below.
  * Video: https://www.youtube.com/watch?v=sCnngXwgN0M

**Comment by aleos89** [comment]
In the video you're standing in Braggi, shouldn't that be the reason you're able to cast Dragon Breath so fast?

**Comment by chne024** [comment]
I can confirm this, in my old server (closed). When player stuck at "received damage" sprite, they will cast skill with a shorter cooldown.
I jailed one of them and ask how to produce. They showed me.
I very confused and accept as the legal.

**Comment by admkakaroto** [comment]
ASPD: 186

**Comment by mrjnumber1** [comment]
this is normal behavior for delays that are super low. the client itself refuses to send a new skill if it's in another animation. with nodelay grf, a player can do this without being flinched.

it was normal to see on skills that are being reflected, because they'd get immediately flinched.
