### ISSUE TITLE
Rates with Enriched metals are wrong

### ISSUE THREAD

**Issue by feltenc** [rathena/rathena#2097]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/caed38927ac6edd327a63488ec5d3a0fe1fedb9f

* **Client Date**: 2017-04-26RagexeRE

* **Server Mode**: Renewall

* **Description of Issue**: 
  * Result: The rate with Enriched Elunium/Oridecon are the same as normal Elunium or Oridecon.
  * Expected Result: The rates should be increase when you use a Enriched metal
  * How to Reproduce: At the moment i can reproduce and see it using the New Refining Ui
  * Official Information: Ill post bellow
  

* **Modifications that may affect results**:  None

Refining Rate with Oridecon(ID: 984)
![image](https://cloud.githubusercontent.com/assets/22537929/25462477/ab704688-2ac5-11e7-8d1f-d48362fc911f.png)

Refining Rate with Enriched Oridecon(ID: 7620)
![image](https://cloud.githubusercontent.com/assets/22537929/25462495/d1c996ea-2ac5-11e7-8642-18aedf4fe8fe.png)

As you can see, the rates are the same using diffrent versions of the Oridecon. Thats Wrong.

*Official information
![image](https://cloud.githubusercontent.com/assets/22537929/25462528/fdc3ea3e-2ac5-11e7-83e9-233372a0937e.png)

![image](https://cloud.githubusercontent.com/assets/22537929/25462542/035ae7ae-2ac6-11e7-93ae-73e44eb74c27.png)

**Comment by mrjnumber1** [comment]
what you have doesn't match release2013_zone, and for that matter neither does db/re/refine_db.txt, so i'll put that info here.

(for reference i'll drop the list i pulled in case i made a mistake in this post on here https://gist.github.com/mrjnumber1/02327e065d8541095b50d742befe56ff
armor is correct as in db/re/refine_db.txt 
for lv1 weapon, +19-20 should be 16%, not 15%
for lv2 weapon, +19-20 should be 16%, not 15%
for lv3 weapon, +19-20 should be 16% not 15%
lv4 is correct as in db/re/refine_db.txt 

furthermore, enriched metals refine is using the same chance repeated twice (so for example if it was a 60% chance it'd be an 84% chance, and so on) in both re and pre-re. this is not the behavior expected in any zone. 11.3 zone also has the exact same behavior (refer to the table below or advancedRefTable_base)

for pre-re _and_ re, the enriched refine table should be as such:
```
(arm) 100 100 100 100 090 060 060 030 030 010
(lv1) 100 100 100 100 100 100 100 090 060 020
(lv2) 100 100 100 100 100 100 090 060 030 020
(lv3) 100 100 100 100 100 090 075 030 030 020
(lv4) 100 100 100 100 090 060 060 030 030 010
```


i didn't quite follow all of the code for mastersmith weapon refine (forgive me!), it's 5*(jlv-50) bonus (per 100), so i'm not sure (lazy on the math, yet okay with looking through a disassembly for some reason okay) if that matches exactly with our current (jlv-50)/2 per 10 setup (at least at j70 it does).  also, only trans mechanic gets the bonus 10% refine, not non-trans mechanic.

**Comment by feltenc** [comment]
Why you closed my issue? @secretdataz

**Comment by secretdataz** [comment]
@felten it's a duplicate.

**Comment by feltenc** [comment]
where is the other? @secretdataz

**Comment by tuxico** [comment]
How you open this UI? ;o
