### ISSUE TITLE
Madogear Updates

### ISSUE THREAD

**Issue by Felleonel** [rathena/rathena#2099]
Recent updates from kRO increased Movement speed of Madogear when is equipped, similar with peco or gryphon riding. Also the Weight Limit was increased by 1500, and HP Recovery too. Madogear is able to use [Teleportation] skills and now, receive all chemical protection skills.

Ref:

https://translate.google.com.ph/translate?hl=en&sl=ko&u=http://ro.gnjoy.com/news/devnote/View.asp%3Fcategory%3D1%26seq%3D3652742%26curpage%3D1&prev=search

http://ziu-ro.blogspot.com.br/2016/11/mechanic-madogear-update-future-update.html

**Comment by aleos89** [comment]
Quoted from Ziu:

> - Madogear is getting better.
> -> The natural HP recovery is increased.
> -> The base walking speed of the machine is increased.
> -> Increases the maximum weight you can carry.
> -> The [Teleport] ability can be used.
> -> Several coatings are added with effects.
> -> The limit (visible now by means of an icon) is added before reaching the overheat state.
