### ISSUE TITLE
Last Commits, Compile Errors.

### ISSUE THREAD

**Issue by Lilori** [rathena/rathena#2100]
* **rAthena Hash**: cbc3b260c849d3101ee5cda72206a803d8cdb470

* **Client Date**: -

* **Server Mode**: -

* **Description of Issue**: 
`
In file included from script.c:2354:
script_constants.h: In function 'script_hardcoded_constants':
script_constants.h:284: error: 'MAPID_BABY_TAEKWON' undeclared (first use in this function)
script_constants.h:284: error: (Each undeclared identifier is reported only once
script_constants.h:284: error: for each function it appears in.)
script_constants.h:285: error: 'MAPID_BABY_GUNSLINGER' undeclared (first use in this function)
script_constants.h:286: error: 'MAPID_BABY_NINJA' undeclared (first use in this function)
script_constants.h:287: error: 'MAPID_BABY_SUMMONER' undeclared (first use in this function)
script_constants.h:295: error: 'MAPID_BABY_STAR_GLADIATOR' undeclared (first use in this function)
script_constants.h:296: error: 'MAPID_BABY_REBELLION' undeclared (first use in this function)
script_constants.h:297: error: 'MAPID_BABY_KAGEROUOBORO' undeclared (first use in this function)
script_constants.h:305: error: 'MAPID_BABY_SOUL_LINKER' undeclared (first use in this function)
make[1]: *** [obj/script.o] Error 1
make[1]: Leaving directory /root/rathena/src/map'
make: *** [map] Error 2
`

**Comment by spangler88** [comment]
Did u manually update it ?,

seems like you are missing this update 
https://github.com/rathena/rathena/commit/ed24be16254fd60c1c0734a313793d65b56e21a5
