### ISSUE TITLE
Arrow Creation with Emp and warlock Reading Spell.

### ISSUE THREAD

**Issue by sikiro** [rathena/rathena#2101]
* **rAthena Hash**: 
Latest

* **Client Date**: 
20151104

* **Server Mode**: 
Renewal

* **Description of Issue**:  Create Arrow with Emperium not working on latest revision and cannot use spell book reading on warlock is not detecting the books either
  * Result: 
  * Expected Result: 
  * How to Reproduce: Use Emp to Create Arrow interface shows but no arrow option
     Using Reading skill will not detect the book even if you have it in your inventory.
  * Official Information:
  

* **Modifications that may affect results**: 
Currently using both Achievement system and random opt system but they dont make anny changes to any skill related source files.

**Comment by Stolao** [comment]
Tested  in cbc3b26 (currently latest) in 20130807a (to lazy to update atm) 
Arrow Craftingusing Emperium (714) and worked fine
Reading Spellbook worked fine as well.

**Comment by sikiro** [comment]
will do  maybe my issue resides with using random option system.

**Comment by crazystorm2017** [comment]
Good Day I Have tested this in [https://github.com/rathena/rathena/commit/4f99567e41935987a99ac729104557c77a7d137b](4f99567)
Using 2015-11-04a Client and Both Create arrow with emperium and reading spell book works fine. :))

**Comment by aleos89** [comment]
I tested on a clean rAthena (master) and the random drop system (feature/mobdrop_randomopt). Both resulted in both of your cases working fine. Make sure your databases are being properly parsed.
