### ISSUE TITLE
Rathena re-opened after the guild flag will disappear

### ISSUE THREAD

**Issue by whupdo** [rathena/rathena#2102]
Rathena re-opened after the guild flag will disappear

rAthena Hash: https://github.com/rathena/rathena/commit/cbc3b260c849d3101ee5cda72206a803d8cdb470

![1493306214056](https://cloud.githubusercontent.com/assets/17958968/25563439/06bc1498-2dcf-11e7-90aa-e2313fe899a7.jpg)
![1493306196736](https://cloud.githubusercontent.com/assets/17958968/25563438/06b8c928-2dcf-11e7-9cbe-dad2a2b19022.jpg)

**Comment by Jeybla** [comment]
Can you explain your issue in more detail? What did you re-open?

**Comment by Atemo** [comment]
He probably means the emblem is missing when he connects to char server.
We could probably add something similiar to ```guild_npc_request_info``` into flagemblem, or add ```requestguildinfo``` in npcs scripts to load the guild data.

**Comment by srhmike** [comment]
I agree with Atemo, 
When you restart the server the guild flags don't show the emblem.  But I think when either the guild leader or member logs in, the maps will get the emblem.  or something of the sort, I know after doing server restart, the emblems wont show, then sometime later, they appear. (Most of the time)

**Comment by psyzerkski** [comment]
I can confirm this bug. Flags will show up again once you reload the script. Either you reload the npc flags script one by one or simply @reloadscript.

**Comment by Lemongrass3110** [comment]
That bug is rather tricky, but I confirmed it just now and found where it is coming from.
