### ISSUE TITLE
Help - my attack not increase by skill ex: striking

### ISSUE THREAD

**Issue by mjonrest** [rathena/rathena#2108]
Please look at this picture

i m not sure what error, but i just renew my src file but not everything.

is there any file i missed?

![error1](https://cloud.githubusercontent.com/assets/21119685/25565557/fbb2b7a4-2df2-11e7-8435-b26f62c35d4e.JPG)
![error2](https://cloud.githubusercontent.com/assets/21119685/25565559/ffed54c8-2df2-11e7-9e85-fb7b09abf1a0.JPG)

**Comment by feltenc** [comment]
I think you must provide more informations. it's not possible to start to analyze your error without knowing what's your client version, git hash and server mode.

**Comment by secretdataz** [comment]
Striking only increase equipment ATK. Since you do not have any weapon equipped it won't have any effect.

**Comment by mjonrest** [comment]
sorry @feltenc my client version 20151104, about git hash i dont get it. server mode is renewal

@secretdataz still not working
![error3](https://cloud.githubusercontent.com/assets/21119685/25565831/488fb8be-2df9-11e7-9ebb-e8e0b7c8568d.JPG)
![error4](https://cloud.githubusercontent.com/assets/21119685/25565833/4d6746fe-2df9-11e7-80ab-37e082b24e6b.JPG)

**Comment by feltenc** [comment]
@mjonrest 
i have noticed that on mine server too, but look at my report, they could fix this issue cause i send more information's and explain what's happening with details.

Keep reporting your issue but follow the sample issue text.
https://github.com/rathena/rathena/issues/2118

Thanks!

**Comment by Playtester** [comment]
Before reporting again, make sure you have the latest rAthena version.
