### ISSUE TITLE
bellum glaive

### ISSUE THREAD

**Issue by jamon18** [rathena/rathena#2109]
{ bonus2 bSkillAtk,"LK_SPIRALPIERCE",100; bonus2 bSkillAtk,"KN_SPEARBOOMERANG",50; } 
why kn_spearboomerang? 
Increases physical damage on Player protocol targets by 80%.
_
If upgrade level is +6 or higher,
Increases the damage of Clashing Spiral by 100%.
Increases the damage of Overbrand by 50%.

correct me please
{ bonus2 bSkillAtk,"LK_SPIRALPIERCE",100; bonus2 bSkillAtk,"LG_OVERBRAND",50; } 
bonus2 bSkillAtk,"LG_OVERBRAND"
https://raw.githubusercontent.com/rathena/rathena/master/db/re/item_db.txt item 1492

**Comment by Jeybla** [comment]
Yes, Item description and our effect are not identical. Would be good if we find another reliable source confirming it should be `LG_OVERBRAND` instead of `KN_SPEARBOOMERANG`.

**Comment by Atemo** [comment]
kro description : `오버 브랜드의 데미지 50% 증가.`
