### ISSUE TITLE
Drop Rates

### ISSUE THREAD

**Issue by panko11** [rathena/rathena#211]
I put 10 million drop in the rates of normal monsters items (Etc, Consumables and Equipment) and the drop is only 50%, but Miniboss and MvP works. What's this? It would be a Bug?

**Comment by raynra** [comment]
You're probably using the Renewal Drop system (in renewal.h #define RENEWAL_DROP)

Information here:
https://rathena.org/wiki/Category:Configuration#RENEWAL_DROP

Your level difference is creating a drop rate penalty.

**Comment by cydh** [comment]
ur 10 mil is out of range. :P max rate is `1000000`

**Comment by MrAntares** [comment]
@cydh even 10000 would be enough, wouldn't it? 0.01% * 10000 = 100% :D

**Comment by cydh** [comment]
> I put 10 million drop in the __rates__ of normal monsters items

@MrAntares 
`*_rate_*`,100 = 1x
`*_min`, 100 = 0.01%
`*_max`, 100 = 0.01%
