### ISSUE TITLE
gigantic blade

### ISSUE THREAD

**Issue by jamon18** [rathena/rathena#2110]
21011,Gigantic_Blade,Gigantic Blade,5,10,,5000,300,,1,1,0x00004082,56,2,34,4,130,1,3,{ bonus bUnbreakableWeapon,1; bonus bAspdRate,-5; if(readparam(bStr)<=110){ bonus bBaseAtk,-250; } },{},{}
u can view this item 
Equip Swords of 2 hands and equip with guard and readparam bstr dont baseatk
Sorry for the little information
Can you try please

**Comment by admkakaroto** [comment]
Use this:

`21011,Giant_Blade,Gigantic Blade,5,20,,5000,300,,1,1,0x00004082,63,2,34,4,130,1,3,{ bonus bAspdRate,-5; if(readparam(bStr)<=110) bonus bBaseAtk,-250; bonus bCritAtkRate,getrefine(); bonus bUnbreakableWeapon,0; },{},{}`

**Comment by jamon18** [comment]
https://raw.githubusercontent.com/rathena/rathena/master/db/re/item_db.txt item 21011 
this is bug?https://raw.githubusercontent.com/rathena/rathena/master/db/re/item_db.txt item 21011 
this is bug?

**Comment by admkakaroto** [comment]
It is just the structure of the item that is incorrect, the script is working perfectly, only trigger the part of the structure that resolves.

This:
`,5,10,,5000,300,,1,1,0x00004082,56,2,34,4,130,1,3,`

For:
`,5,20,,5000,300,,1,1,0x00004082,63,2,34,4,130,1,3,`
