### ISSUE TITLE
Land Mine Renewal Skill_DB error

### ISSUE THREAD

**Issue by jamon18** [rathena/rathena#2113]
rAthena Hash https://github.com/rathena/rathena/blob/master/db/re/skill_db.txt#L227
Well they have this code:
116,3,6,2,2,0xC0,0,5,1,no,0,0x80,0,misc,0,0x3800,	HT_LANDMINE,Land Mine
122,3,6,2,4,0xF2,1,5,1,no,0,0x80,0,misc,0,0x3800,	HT_BLASTMINE,Blast Mine
123,3,6,2,3,0xF2,2,5,1,no,0,0x40080,0,misc,0,0x3800,	HT_CLAYMORETRAP,Claymore Trap

why land mine dont 0xF2 ? 
ej: use land mine 20k atk + armor wind = 30~35k atk 

This trap will bypass Guard, Parry and Weapon Blocking.
This trap will bypass DEF and Flee.
This trap will bypass Race, Element and Size damage effects like Thara Frog, Tatacho and Ogretooth Card in PvP and WoE.
http://irowiki.org/wiki/Claymore_Trap

This trap will bypass DEF and Flee.
This trap will bypass Race, Element and Size damage effects like Thara Frog, Tatacho and Ogretooth Card in PvP and WoE.
This trap will bypass Element resistance effects like Hornet Card in PvP and WoE.
http://irowiki.org/wiki/Blast_Mine

This trap will bypass DEF and Flee.
This trap will bypass Race, Element and Size damage effects like Thara Frog, Tatacho and Ogretooth Card in PvP and WoE.
This trap will bypass Element resistance effects like Hornet Card in PvP and WoE.
http://irowiki.org/wiki/Land_Mine

Land Mine Is taking element armor

**Comment by Playtester** [comment]
Land Mine is not a splash skill so there should be no 0x02. It can only hit one enemy.

Also, 0xC2 is the same as 0xF2 because MISC skills automatically ignore DEF.

**Comment by jamon18** [comment]
https://mega.nz/#!NgdUAYLR!lWhItTU9b0SLfLtKc-Hu3Wd3OP0s-LvzlToI99JIcuc
u can view rff please

**Comment by Playtester** [comment]
Okay I got it now. The bug is actually the other way around. Blast Mine and Claymore Trap are bugged that they don't take the element of the armor into account. Land Mine is already correct.
