### ISSUE TITLE
Project nemo patcher is dead?

### ISSUE THREAD

**Issue by manut93** [rathena/rathena#2116]
Hello good afternoon from spain,
Maybe i dont have to post this here, i posted in issues of nemo but ppl say nemo project is dead, and maybe someone from here can help me.
I have a rathena emulator but nemo patcher can patch 2016 ragexes but i cant enable aura over level 99 some one fixed it? Or can explain me how to do hexadecimal editon to fix? Please help.
Thanks in advanced.

**Comment by Jeybla** [comment]
These questions belong to our forum, this is for rathena issue tracking only. Thanks for understanding.
