### ISSUE TITLE
Some skills are not increasing the ATK and MATK

### ISSUE THREAD

**Issue by feltenc** [rathena/rathena#2118]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/a75133eb4d8976c1c890d5420665e7a76349e226

* **Client Date**: 2017-01-25RagexeRE

* **Server Mode**: Renewall

* **Description of Issue**: Some skills are not increasing the character ATK or the damage.
  * Result: When i use skills like Odin's Power, Pyroclastic or Striking my ATK doesn't increase and the final damage is not affected too.
  * Expected Result: I think the damage should be increased or the ATK should be increased on the status window.
  * How to Reproduce: Create a Archbishop, type ``@item 2156``, use the skill that the book's provide on yourself(Odin's Power). You can test with Genetic too using the Dieter Pyroclastic.

  * Official Information: I don't have official information from kRO but there is a link from iRO wiki. The description of the item is the same on kRO so i think is the same as iRO.
  

* **Modifications that may affect results**: Maybe it start happens after this commit https://github.com/rathena/rathena/commit/a75133eb4d8976c1c890d5420665e7a76349e226

My tests:

*Odin's Power Skill ~ Not increasing ATK and MATK
![image](https://cloud.githubusercontent.com/assets/22537929/25680565/aacd5056-3027-11e7-8e63-b4ff8aa981cc.png)
![image](https://cloud.githubusercontent.com/assets/22537929/25680593/ca51c4f2-3027-11e7-9a77-d2c7ed316c32.png)

*Pyroclastic ~ Not increasing the ATK
![image](https://cloud.githubusercontent.com/assets/22537929/25681031/418e918e-3029-11e7-92d3-fd4d6f9aa9f5.png)
![image](https://cloud.githubusercontent.com/assets/22537929/25681056/5653aca8-3029-11e7-94b0-049571a0ae06.png)

**Comment by aleos89** [comment]
Fixed in 9ba2513 and 4bb6aa1.
