### ISSUE TITLE
Blank screen on renewal starting point of new character

### ISSUE THREAD

**Issue by Mikegyver** [rathena/rathena#2119]
* **rAthena Hash**: cc59048d86bab8689b2e0039759861c1cfaa6036

* **Client Date**: 2015-11-04aRagexe.exe

* **Server Mode**: Renewal

Renewal

* **Description of Issue**: Starting point of new character (for human race) / Novice Academy at Criatura Academy gone blank. Seems to be rathena is using old map for this starting point. However in 2017 kRO Full Client, it is using new map for this starting point.
  * Result:  
![screen1asiaro025](https://cloud.githubusercontent.com/assets/16514357/25697600/310cfc54-30ee-11e7-9681-55c90a88d853.jpg)

  * Expected Result: 
![screenhercules004](https://cloud.githubusercontent.com/assets/16514357/25697696/8c0dd4fc-30ee-11e7-92c0-88137305c89e.jpg)

  * How to Reproduce:  Just create a new novice character & enter the game (map server). 
  * Official Information: http://herc.ws/board/topic/13483-2016-10-02-update-to-the-intro/?hl=%2Bcriatura+%2Bacademy
  

* **Modifications that may affect results**:

**Comment by mimishi** [comment]
i think that because of that map itself i already fix that by downloading new izlude map here the link [http://herc.ws/board/topic/10579-2015-09-05-142-criatura-academy/page-2#entry66294]

**Comment by Akkarinage** [comment]
When using a 20151104 client with the translation pack by zackdreaver it all works fine because his repo includes the iz_int maps so you appear on the boat, which would be correct for this client.

It'd be nice if we could get some official sources for this instead of a link to a post on Herc that only contains more links to other Herc posts. Info from kRO would be marvellous so we can add the academy updates in the preparation for 2017 clients.

**Comment by hazimjauhari90** [comment]
@mimishi well.. it is a simple fix.. instead i know about it already.. but, for me it is already outdated.. that's is what i mean & that is my intention..

@Akkarinage, not all people use zackdreaver translation.. but as the old iz_int map can be download separately & put inside grf, i think this method, is not so practical & efficient.. and this new iz_int map if i'm not mistaken being introduced in december 2015.. just seing most of kRO full client already patched up to 2017, for those who are not using zackdreaver translation + using 2017 kRO full client (new iz_int map), i'm so sure for those people will be having this kind of issue..

so i think it is valid for me to post this issue.. cheers.

**Comment by Everade** [comment]
This is a duplicate.
Reported already over a year ago:
https://github.com/rathena/rathena/issues/946
