### ISSUE TITLE
Gunslinger Mine

### ISSUE THREAD

**Issue by MrAntares** [rathena/rathena#212]
Git Version: **12628 - 2014-12-04 05:04:30 (luciar)**
Client Date: **2012-04-10**
Src Mods: **NONE**
General settings: 
- **Full Renewal**
- **1/1/1/1/1 rate**
- **PK server (not in towns, above lvl 30)**
- **PVP ATK/Skill modifers: 100%**
- **WOE ATK/Skill modifers: rA default**
- **Official walk path and stacking**
- **Exp and drop penalty table values below 100% set to 100%**
- **Party and attacker exp bonus: +40%**
- More at (Hungarian, use translate): http://wiki.ragna.ro/

How to reproduce: **Use the skill**
Description:

The skill only deals the bonus damage, which is +500 on lvl 10. It should work somewhat like Evenom, so the bonus should be added to a 100% rate attack as a straight increase: atk+500.

**Comment by cydh** [comment]
Gunslinger Mine? Grounddrift?
````
		case GS_GROUNDDRIFT:
			// Official formula [helvetica]
			// damage = 50 * skill level
			// fixed damage, ignores DEF and benefits from weapon +%ATK cards
			md.damage = 50*skill_lv;
			md.damage += battle_calc_cardfix(BF_WEAPON, src, target, nk, s_ele, 0, md.damage, 0, md.flag|NK_NO_CARDFIX_DEF); // ground drift benefits from weapon atk cards, ignore DEF cards so we don't apply twice
			break;
````

**Comment by MrAntares** [comment]
Yep. I never know which one is the iRo/kRo name, especially since ppl started mixing them in the client translation project. ^^

**Comment by Playtester** [comment]
jRO wiki: http://nyanslinger.sakura.ne.jp/Gunslinger/index.php?%A5%B9%A5%AD%A5%EB

Quite hard to understand with autotranslate, though. Better be read by someone who knows Japanese better than me.

**Comment by cydh** [comment]
wow cool, that Desperado mapping

**Comment by MrAntares** [comment]
It says:
Damage 100% + level * 50 (fixed value). The fixed part DEF ignored non-attribute.
Exactly what I said.

I also notice that there is another missing part:
Knock-back effect with Fire Sphere (100%).
Stun effect with Wind Sphere.
Freezing effect with ice sphere.
(Poisoning effect with Poison Sphere.
Darkness effect with dark sphere.) <-- this is coming from the sphere so it is working

**Comment by reigneil** [comment]
i've reported this issue long long time ago... but no one care about. /sob
that it is always deal 500 damage at level 10 as if there is no other way to increase it.
@admin
can i request to close this old report.
https://rathena.org/board/tracker/issue-8470-gs-grounddrift-gunslinger-mine-damage-formula/

**Comment by MrAntares** [comment]
Bump me, right?
