### ISSUE TITLE
Problem With Pet system Erroring

### ISSUE THREAD

**Issue by TrueNoir** [rathena/rathena#2121]
* **rAthena Hash**: a3282c17305c7f0311d056a2eb6e4c85029b8ae9

* **Client Date**: 2015-11-04aRagexe

* **Server Mode**: 

Renewal
* **Description of Issue**: 
  * Result: 
When trying to add custom pets keep getting the database error below about pets being out of range. 
SQL]: DB error - Out of range value for column 'egg_id' at row 1
[Debug]: at ***[censored by @Lemongrass3110]***\rathena\src\char\int_pet.c:36 - INSERT INTO `pet` (`class`,`name`,`account_id`,`char_id`,`level`,`egg_id`,`equip`,`intimate`,`hungry`,`rename_flag`,`incubate`) VALUES ('3971', 'sapling', '0', '0', '50', '-22936', '0', '250', '100', '0', '1')
  * Expected Result: 
Since the monster works fine in game I'd expect that the taming capture would too but it doesn't. 
  * How to Reproduce: 
Adding a custom pet 
  * Official Information:
  

* **Modifications that may affect results**: 
  
  

Asked about it on the forums but seems like no one seems to have any idea's how to fix the problem. The server should support up to 64k id's' but something is wrong.

**Comment by hurtsky** [comment]
is that -22936? lol

**Comment by Lemongrass3110** [comment]
I censored your path a little.
Could you give us your custom entries to item_db, mob_db and pet_db so we can try to reproduce it with your data?
Thank you.

**Comment by daisyanne1380** [comment]
im having the same exact issue here what i used
item_db2_re--------------------------------------------------
42600, 'Sapling_Egg', 'Sapling_Egg', 7, , 10, 0, , , , , , , , , , , , , '', '', ''
42700, 'Flashlight_', 'Flashlight_', 2, 20000, 20, 50, , , , , 4294967295, 63, 2, , , , , , ' pet 3971;  ', '', ''
-----------------------------------------------------------
mob_db2_re
3971, 'sapling', 'sapring', 'sapring', 50, 15000, 0, 8000, 5000, 2, 1010, 1044, 20, 20, 15, 75, 33, 40, 70, 20, 10, 12, 0, 0, 20, 131, 120, 360, 480, 360, 0, 0, 0, 0, 0, 0, 0, 1026, 1500, 42700, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

db/re/pet.db.txt
3971,sapring,sapring,42700,42600,0,6108,80,60,20,100,250,20,100,150,1,0,350,500,500,{},{ bonus bStr,5; bonus bInt,5; }

**Comment by srhmike** [comment]
I can also reproduce this error on same Git.

Support topics in the forum suggest using an egg id lower than 32000.

But its kinda hard when other custom items take up to 32000 xD.
