### ISSUE TITLE
Goblin Leader Loyal Script Pet DB Issue PRE-RE

### ISSUE THREAD

**Issue by marcelorp** [rathena/rathena#2124]
I see an issue on the **loyal script** of the **Goblien Leader** pet, on the **pet_db.txt**

The actual script is:

> 1299,GOBLIN_LEADER,Goblin Leader,12364,9046,10028,6104,80,60,10,100,250,20,50,150,0,0,300,300,800,{},{ bonus2 **bAddRace**,RC_DemiHuman,3; }

But shouldn't be that?

> 1299,GOBLIN_LEADER,Goblin Leader,12364,9046,10028,6104,80,60,10,100,250,20,50,150,0,0,300,300,800,{},{ bonus2 **bSubRace**,RC_DemiHuman,3; }

See my reference site:
[http://irowiki.org/wiki/Cute_Pet_System](url)

In that wiki is saying that this pet do this:

> **Demi Human Resistance +3%**

Sorry if that is a mistake and is the website error not the emulator, can you review that for me?

**Comment by Jeybla** [comment]
Iro wiki seems to be wrong here:
http://www.divine-pride.net/database/item/9046/kRO
`Increase damage dealt to Demi-Human monsters by 3%.`

Anyway thanks for mentioning it!
