### ISSUE TITLE
Linux Compile Error

### ISSUE THREAD

**Issue by rofasindo** [rathena/rathena#2127]
Compile error, I'm using Linux Centos 6 32Bit with latest git rAthena today 2017/05/08 (svn 19694), error _./configure_ and cannot command _make server_

> checking whether byte ordering is bigendian... yes
configure: error: bigendian is not supported... stopping

> [root@vultr server]# make server
make: *** No rule to make target `server'.  Stop.

![error compile 1](https://cloud.githubusercontent.com/assets/24239587/25788896/adff951a-33d6-11e7-841e-5530b678210b.jpg)
![error compile 2](https://cloud.githubusercontent.com/assets/24239587/25788897/ae2c5884-33d6-11e7-96fa-3f13a4e35ce9.jpg)

**Comment by Jeybla** [comment]
Please retry it by using `./configure --disable-64bit `

**Comment by rofasindo** [comment]
@Jeybla it same problem on here

> checking whether byte ordering is bigendian... yes
configure: error: bigendian is not supported... stopping

**Comment by Jeybla** [comment]
Mh.. This eventually is caused by 4a004ad4b83d2b46f56b4e57a8a6f3e487372ea6 .
Related: `https://github.com/bitcoin/bitcoin/issues/5177`

@secretdataz may has more info about this issue. You could try to checkout a3282c17305c7f0311d056a2eb6e4c85029b8ae9 .

**Comment by secretdataz** [comment]
Adding `-fpermissive` to the `CXXFLAG` define in src/common/Makefile.in could be a workaround.

**Comment by rofasindo** [comment]
adding like this?
> CXXFLAG =-std=c++11-fpermissive

still not work, while I have try to _**./configure --disable-64bit** or **./configure**_ and same error on 
> configure: error: bigendian is not supported... stopping

**Comment by secretdataz** [comment]
CXXFLAG =-std=c++11 -fpermissive

**Comment by rofasindo** [comment]
@secretdataz still same, configure not working.

**Comment by secretdataz** [comment]
@rofasindo Can you try installing g++ package?

**Comment by rofasindo** [comment]
@secretdataz thank you, just missing g++ package. Now fix, I can configure and make server. thanks again.

**Comment by yerunkar11** [comment]
I am facing the same on centos, this time i have an gcc-c++ package installed.

**Comment by NandoPrates** [comment]
i too same error in centos 6 but have Package gcc-c++-4.4.7-18.el6.x86_64 already installed and latest version

**Comment by NandoPrates** [comment]
$ cat /etc/centos-release
CentOS release 6.7 (Final)

$ sudo yum install centos-release-scl
$ sudo yum install devtoolset-3-toolchain
$ scl enable devtoolset-3 bash

$ gcc --version
gcc (GCC) 4.9.2 20150212 (Red Hat 4.9.2-6)
...

$ g++ --version
g++ (GCC) 4.9.2 20150212 (Red Hat 4.9.2-6)
...

$ gfortran --version
GNU Fortran (GCC) 4.9.2 20150212 (Red Hat 4.9.2-6)
...

**Comment by NandoPrates** [comment]
sudo yum install centos-release-scl
sudo yum install devtoolset-4-gcc*
scl enable devtoolset-4 bash
which gcc
gcc --version

**Comment by lighta** [comment]
Did you manage to fix it @NandoPrates ?
Please try to rebuild the configure scripts. ie:
`
mv ./configure ./configure.bkp
autoconf ./configure.in > ./configure && chmod +x ./configure
./configure
`
Let me know the result.

**Comment by Lemongrass3110** [comment]
@lighta use three ticks. ```

**Comment by Akkarinage** [comment]
I mean.. for starters, tell users to install GCC5 and G++5, like to we do on the forums for similar issues. CentOS 6 is unable to install version 5 of these tools as their repo doesn't have access to them by default, and there's no reason why users shouldn't be upgrading to CentOS 7 in order to access these packages anyway. We have these guides on the wiki.
