### ISSUE TITLE
VS2013 with v120_xp platform toolset issue

### ISSUE THREAD

**Issue by zackdreaver** [rathena/rathena#2137]
* **rAthena Hash**: ea4d192aaad76a417e88c38894310a8644625647

* **Client Date**: 2014-10-22bRagexe

* **Server Mode**: Renewal

* **Description of Issue**: Compiling failed when using v120_xp as platform toolset
  * Result: Error log

> 3>mempool.c(124): warning C4013: 'InterlockedIncrement64' undefined; assuming extern returning int
3>mempool.c(298): warning C4013: 'InterlockedExchangeAdd64' undefined; assuming extern returning int
3>mempool.c(460): warning C4013: 'InterlockedExchange64' undefined; assuming extern returning int
3>mempool.c(498): warning C4013: 'InterlockedDecrement64' undefined; assuming extern returning int
6>common.lib(mempool.obj) : error LNK2001: unresolved external symbol _InterlockedDecrement64
6>common.lib(mempool.obj) : error LNK2001: unresolved external symbol _InterlockedExchangeAdd64
6>common.lib(mempool.obj) : error LNK2001: unresolved external symbol _InterlockedExchange64
6>common.lib(mempool.obj) : error LNK2001: unresolved external symbol _InterlockedIncrement64

  * Expected Result: Succeed when compiling
  * How to Reproduce: Compile using v120_xp as platform toolset
  * Official Information: none
  

* **Modifications that may affect results**: none

**Comment by anacondaqq** [comment]
About issues like this, i was cry in my previous posts, but the issues are solvable by using another version of VS. I spent around 1 hour just to find VS2013 free anywhere on the internet (except torrent trackers), at the official website there are no more any VS2013 Community/Free, all pages are dead or redirect to the new version.

**Comment by secretdataz** [comment]
Please keep the conversation relevant to the topic, thanks.

**Comment by zackdreaver** [comment]
what?

**Comment by secretdataz** [comment]
@zackdreaver there was an irrelevant comment.

**Comment by zackdreaver** [comment]
New warnings from https://github.com/rathena/rathena/commit/6748ff7e1712b7bcb189dd191bb3cfd74dc5db44
`7>LINK : warning C4744: 'agit3_flag' has different type in 'E:\rAthena\src\map\map.cpp' and 'E:\rAthena\src\map\battle.c': 'unsigned char' and 'signed char' 
7>LINK : warning C4744: 'agit_flag' has different type in 'E:\rAthena\src\map\map.cpp' and 'E:\rAthena\src\map\battle.c': 'unsigned char' and 'signed char' 
7>LINK : warning C4744: 'agit2_flag' has different type in 'E:\rAthena\src\map\map.cpp' and 'E:\rAthena\src\map\battle.c': 'unsigned char' and 'signed char' 
7>LINK : warning C4744: 'agit3_flag' has different type in 'E:\rAthena\src\map\script.c' and 'E:\rAthena\src\map\map.cpp': 'signed char' and 'unsigned char' 
7>LINK : warning C4744: 'agit_flag' has different type in 'E:\rAthena\src\map\script.c' and 'E:\rAthena\src\map\map.cpp': 'signed char' and 'unsigned char' 
7>LINK : warning C4744: 'agit2_flag' has different type in 'E:\rAthena\src\map\script.c' and 'E:\rAthena\src\map\map.cpp': 'signed char' and 'unsigned char' 
7>LINK : warning C4744: 'agit3_flag' has different type in 'E:\rAthena\src\map\skill.c' and 'E:\rAthena\src\map\map.cpp': 'signed char' and 'unsigned char' 
7>LINK : warning C4744: 'agit_flag' has different type in 'E:\rAthena\src\map\skill.c' and 'E:\rAthena\src\map\map.cpp': 'signed char' and 'unsigned char' 
7>LINK : warning C4744: 'agit2_flag' has different type in 'E:\rAthena\src\map\skill.c' and 'E:\rAthena\src\map\map.cpp': 'signed char' and 'unsigned char' 
7>LINK : warning C4744: 'agit3_flag' has different type in 'E:\rAthena\src\map\status.c' and 'E:\rAthena\src\map\map.cpp': 'signed char' and 'unsigned char' 
7>LINK : warning C4744: 'agit_flag' has different type in 'E:\rAthena\src\map\status.c' and 'E:\rAthena\src\map\map.cpp': 'signed char' and 'unsigned char' 
7>LINK : warning C4744: 'agit2_flag' has different type in 'E:\rAthena\src\map\status.c' and 'E:\rAthena\src\map\map.cpp': 'signed char' and 'unsigned char' `

Can't find the old warnings from first post, maybe it was fixed in some commits.
