### ISSUE TITLE
skill '65535' is undefined!

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#2138]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/562d6d1e343d61620ebe4f4f60896a84132d231c

* **Client Date**: 2016-12-28

* **Server Mode**: Renewal
* **Description of Issue**: I do not know what the reason or what may be causing, but I'm getting several error messages on the server terminal.
  * Expected Result: No error message!
  * How to Reproduce: Do not know!
  * Obs: This problem also happens with the client 2015-11-04 or any other version, so I'll dial the chance of it being on the client or anything related to it. I wanted to know if this could cause some problem and how to solve it.

Print: http://imgur.com/BZxfdnm

**Comment by Jeybla** [comment]
Related to #1341 .
