### ISSUE TITLE
SQL Files Bug

### ISSUE THREAD

**Issue by OverLordDev** [rathena/rathena#214]
File: item_db.sql

Error
Command SQL:

#REPLACE INTO `item_db` VALUES (5606,'Campume_Hat','Champune Hat',4,500,NULL,1200,NULL,4,NULL,1,0xFFFFFFFF,7,2,256,NULL,3,1,580,'bonus bAllStats,1;',NULL,NULL);
#REPLACE INTO `item_db` VALUES (5607,'Lyria_Doll_Hat','Lyria Doll Hat',4,0,NULL,500,NULL,0,NULL,1,0xFFFFFFFF,7,2,256,NULL,60,0,581,NULL,NULL,NULL);
#REPLACE INTO `item_db` VALUES (5608,'Dorothy_Doll_Hat','Dorothy Doll Hat',4,0,NULL,500,NULL,0,NULL,1,0xFFFFFFFF,7,2,256,NULL,60,0,582,NULL,NULL,NULL);
#REPLACE INTO `item_db` VALUES (5609,'Chung_Hairband','Chung Hairband',4,0,NULL,500,NULL,5,NULL,1,0xFFFFFFFF,7,2,256,NULL,60,0,583,'bonus bLuk,3; bonus bMdef,4;',NULL,NULL);
#REPLACE INTO `item_db` VALUES (5610,'Ice_Wing_Ear','Ice Wing Ear',4,0,NULL,100,NULL,0,NULL,0,0xFFFFFFFF,7,2,512,NULL,10,0,584,'bonus bLuk,1;',NULL,NULL);
#REPLACE INTO `item_db` VALUES (5611,'Turtle_Hat','Turtle_Hat',4,0,NULL,300,NULL,0,NULL,0,0xFFFFFFFF,7,2,256,NULL,10,1,585,'bonus bAgi,1;',NULL,NULL);
#REPLACE INTO `item_db` VALUES (5612,'F_Blue_Droopi[...]
Mensagens do MySQL : Documentação

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'REPLACE INTO `item_db` VALUES (5654,'Holy_Marching_Hat_J','Holy Marching Hat',4,' at line 49 

File: mob_skill_db.sql

Error
Command SQL:

#REPLACE INTO `mob_skill_db` VALUES (1395,'Wind Crystal@WZ_EARTHSPIKE','chase',90,5,4000,0,0,'no','target','always','0',NULL,NULL,NULL,NULL,NULL,'0',NULL);
#REPLACE INTO `mob_skill_db` VALUES (1395,'Wind Crystal@WZ_EARTHSPIKE','chase',90,5,10000,0,0,'no','target','skillused','18',NULL,NULL,NULL,NULL,NULL,'0',NULL);
#REPLACE INTO `mob_skill_db` VALUES (1395,'Wind Crystal@WZ_EARTHSPIKE','attack',90,5,4000,0,0,'no','target','always','0',NULL,NULL,NULL,NULL,NULL,'0',NULL);
#REPLACE INTO `mob_skill_db` VALUES (1395,'Wind Crystal@WZ_HEAVENDRIVE','chase',91,5,2000,0,5000,'no','target','always','0',NULL,NULL,NULL,NULL,NULL,'21',NULL);
#REPLACE INTO `mob_skill_db` VALUES (1395,'Wind Crystal@WZ_HEAVENDRIVE','chase',91,5,10000,0,5000,'no','target','skillused','18',NULL,NULL,NULL,NULL,NULL,'21',NULL);
#REPLACE INTO `mob_skill_db` VALUES (1395,'Wind Crystal@WZ_HEAVENDRIVE','attack',91,5,2000,0,5000,'no','target','always','0',NULL,NULL,NULL,NULL,NULL,'21',NULL);
#REPLACE INTO `mob_skill_db` [...]
Mensagens do MySQL : Documentação

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'REPLACE INTO `mob_skill_db` VALUES (1399,'Event Baphomet@AL_TELEPORT','idle',26,' at line 86 

File: mob_skill_db_re.sql

Error
Command SQL:

#REPLACE INTO `mob_skill_db_re` VALUES (1395,'Wind Crystal@WZ_EARTHSPIKE','chase',90,5,4000,0,0,'no','target','always','0',NULL,NULL,NULL,NULL,NULL,'0',NULL);
#REPLACE INTO `mob_skill_db_re` VALUES (1395,'Wind Crystal@WZ_EARTHSPIKE','chase',90,5,10000,0,0,'no','target','skillused','18',NULL,NULL,NULL,NULL,NULL,'0',NULL);
#REPLACE INTO `mob_skill_db_re` VALUES (1395,'Wind Crystal@WZ_EARTHSPIKE','attack',90,5,4000,0,0,'no','target','always','0',NULL,NULL,NULL,NULL,NULL,'0',NULL);
#REPLACE INTO `mob_skill_db_re` VALUES (1395,'Wind Crystal@WZ_HEAVENDRIVE','chase',91,5,2000,0,5000,'no','target','always','0',NULL,NULL,NULL,NULL,NULL,'21',NULL);
#REPLACE INTO `mob_skill_db_re` VALUES (1395,'Wind Crystal@WZ_HEAVENDRIVE','chase',91,5,10000,0,5000,'no','target','skillused','18',NULL,NULL,NULL,NULL,NULL,'21',NULL);
#REPLACE INTO `mob_skill_db_re` VALUES (1395,'Wind Crystal@WZ_HEAVENDRIVE','attack',91,5,2000,0,5000,'no','target','always','0',NULL,NULL,NULL,NULL,NULL,'21',NULL);
#REPLACE IN[...]
Mensagens do MySQL : Documentação

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'REPLACE INTO `mob_skill_db_re` VALUES (1399,'Event Baphomet@AL_TELEPORT','idle',' at line 86

**Comment by cydh** [comment]
how u import the file? using phpmyadmin? then ur php default timeout is ur problem when the query is being executed (related with execution, iteration timeout)
