### ISSUE TITLE
Autotrade Issue

### ISSUE THREAD

**Issue by RadianFord** [rathena/rathena#2141]
* **rAthena Hash**: 09cbf2dfa61e3eed34936e7cd2e312c02d20a211

* **Client Date**: 2015 05 13

* **Server Mode**: Pre Renewal

* **Description of Issue**: Something is trying to connect to the server while server is shutdown.
  * Result 1: `make_connection: connect failed (socket #7, error 111: Connection refused)!`
  * Result 2: Then when I tried to login the account that is on autotrade state the server rejects.
```
[Info]: Char load request (2)
[Info]: Loaded char (2 - Oasis):  status memo 33 skills friends hotkeys mercenary
[Info]: 'Oasis' logged in. (AID/CID: '2000001/2', Packet Ver: '0', IP: '0.0.0.0', Group '0').
[Info]: Loaded Storage data from table storage for account_id: 2000001 (total: 7)
[Info]: Loaded Cart data from table cart_inventory for char_id: 2 (total: 2)
[Info]: Loaded Inventory data from table inventory for char_id: 2 (total: 0)
[Info]: mail load complete from DB - id: 2 (total: 0)
```
```
[Status]: Request for connection of Beta (ip: ) version=52
[Notice]: Authentication accepted (account: Beta, id: 2000001, ip: )
[Notice]: User 'Beta' is already online - Rejected.
[Info]: Closed connection from ''.
[Status]: Request for connection of Beta (ip: ) version=52
[Notice]: Authentication accepted (account: Beta, id: 2000001, ip: )
[Status]: Connection of the account 'Beta' accepted.
[Info]: Closed connection from ''.
```
  * Expected Result: It should stop all line from connecting when its shutdown.
  * How to Reproduce: Autotrade 1 merchant/whitesmith then shutdown the server.
  * Official Information: No Official Information.
  

* **Modifications that may affect results**: There are some modifications but most of it are custom commands.

**Comment by hazimjauhari90** [comment]
This issue happen too on Renewal.

**Comment by jezznar** [comment]
make_connection is an operation wherein each server component (Login-server, Char-server, Map-server) connects to each other. I think it is natural to see that it is reconnecting to a server component that it lost connection with.

**Comment by RadianFord** [comment]
@jezznar yea which is not normal, because when there is no autotrade state server is doing fine.

**Comment by hazimjauhari90** [comment]
@jezznar i don't think this is normal.

![connection refuse](https://cloud.githubusercontent.com/assets/16514357/25999085/5ee142e8-3756-11e7-9a81-e0f192b833dc.png)

**Comment by hurtsky** [comment]
i already told @Lemongrass3110 about this around 3 month ago. this happen because map-server is still running. the ./athena-start stop wont terminate map-server normally.. for workaround, you need do `@mapexit` in game, and ./athena-start stop in terminal.

**Comment by Jeybla** [comment]
@hurtsky yes! I'm not quite sure if this is related to autotrade.

**Comment by RadianFord** [comment]
@Jeybla It happens when there's someone using autotrade.

**Comment by hazimjauhari90** [comment]
@Jeybla but it happen only in autotrade command..

**Comment by jezznar** [comment]
@hazimjauhari90 oh sorry bout that. now that you showed the whole screenshot, it makes more sense.
