### ISSUE TITLE
Compile warnings, cant determine hash

### ISSUE THREAD

**Issue by Aerstme** [rathena/rathena#2142]
- **Client Date:** 20150513
- **Server Mode:**  Renewal
- **OS:** Ubuntu  16.04.2 -32 bits
- **gcc:** 5.4.0
Cant determine hash version, but I updated this day: 12-05-2017

**Result:**  I updated the emulator and the database, but while compiling the script.c gives me errors
**Modifications that may affect results:** no important modifications

```
script.c: In function ‘script_getitem_randomoption’:
script.c:6730:22: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
   it->option[i].id = (short)__64BPRTSIZE(get_val2(st,reference_uid(opt_id_id,opt_id_idx+i),opt_id_ref));
                      ^
script.c:6732:25: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
   it->option[i].value = (short)__64BPRTSIZE(get_val2(st,reference_uid(opt_val_id,opt_val_idx+i),opt_val_ref));
                         ^
script.c:6734:25: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
   it->option[i].param = (char)__64BPRTSIZE(get_val2(st,reference_uid(opt_param_id,opt_param_idx+i),opt_param_ref));
```

`

**Comment by Aerstme** [comment]
This issue is a 32 bit system related. I tested on a 64 bit and 32 system (Ubuntu 16.04), but only on 32 bit the error appears.

**Comment by danielbernard** [comment]
This is likely this version of the file:
https://github.com/rathena/rathena/blob/a3282c17305c7f0311d056a2eb6e4c85029b8ae9/src/map/script.c#L6730

Current version points to this line:
https://github.com/rathena/rathena/blob/71421a4268f730d5f899873cd978a12e20e5f3a3/src/map/script.c#L6767

**Comment by Lemongrass3110** [comment]
This seems to have been fixed meanwhile.
Unable to reproduce this on the same machine settings and with script.cpp anymore.
