### ISSUE TITLE
can't attack&use skill after marry 

### ISSUE THREAD

**Issue by sanny1128** [rathena/rathena#2150]
rAthena Hash:  79ad0a1
Client Date: 2017-01-25RagexeRE
Server Mode: Renewall
Description of Issue: can't attack&use any skill after marry 
Result: click monster or use any skill is nothing happened at any map When i get marry in the prt_church with wedding ceremony and the char still wear wedding dress after 1hour...

How to Reproduce: go to the prt_church and process wedding ceremony with wedding staff&Bishop then get wedding ring and wear wedding dress then the char can't attack&use any skill..

**Comment by zackdreaver** [comment]
Isn't that is how its works?
http://irowiki.org/wiki/Marriage_System

**Comment by sanny1128** [comment]
my issue is i can't attack or use skills over an hour

**Comment by aleos89** [comment]
As @zackdreaver stated, it's official. I believe it's the SC_Wedding effect that is in the script. It is not removed on log out.
