### ISSUE TITLE
Script command "equip" not trigger bonus on OnPCStatCalcEvent

### ISSUE THREAD

**Issue by Yuchinin** [rathena/rathena#2159]
* **rAthena Hash**: 79ad0a1902009b7509e0b2a97ecb2571fd0af6f1

* **Client Date**: -

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: As title.
  * Expected Result: Command "equip" should work same as manual equip (double click equipment).
  * How to Reproduce: Add bonus in OnPCStatCalcEvent: and try to run equip command, you will notice that the bonus in OnPCStatCalcEvent: label not get apply. If you equip the equipment manually (aka double click), the bonus get applied normally.

**Comment by Lemongrass3110** [comment]
Just tried this and was unable to reproduce it.

Please go to conf\battle\misc.conf and set `etc_log` to `on`.

You should find an output like this in your mapserver if you start it afterwards:
```
[Info]: Done loading '17116' NPCs:
        -'3650' Warps
        -'233' Shops
        -'13233' Scripts
        -'3396' Spawn sets
        -'49545' Mobs Cached
        -'0' Mobs Not Cached
[Info]: Login Event: 0 'OnPCLoginEvent' events.
[Info]: Logout Event: 1 'OnPCLogoutEvent' events.
[Info]: Load Map Event: 0 'OnPCLoadMapEvent' events.
[Info]: Base LV Up Event: 0 'OnPCBaseLvUpEvent' events.
[Info]: Job LV Up Event: 0 'OnPCJobLvUpEvent' events.
[Info]: Die Event: 1 'OnPCDieEvent' events.
[Info]: Kill PC Event: 1 'OnPCKillEvent' events.
[Info]: Kill NPC Event: 0 'OnNPCKillEvent' events.
[Info]: Stat Calc Event: 2 'OnPCStatCalcEvent' events.
[Status]: Event 'OnInit' executed with '2090' NPCs.
```

Please try and check if the amount is the amount you would expect.

**Comment by jezznar** [comment]
@Yuchinin Please provide your item script.

**Comment by Yuchinin** [comment]
@Lemongrass3110 @jezznar Thanks but maybe you two don't get what I mean. But I notice that when I still attached to a npc, the OnPCStatCalcEvent will not get trigger immediately but it will get trigger when I no longer attach to any npc. It should be because we can't have more than 1 script attach to a character at the same time. Since this is not a big problem, I will just close this issue.

**Comment by secretdataz** [comment]
You can also force stat calculation with `recalculatestat;`

**Comment by Yuchinin** [comment]
Here is the simple example script that show all of the above are not working. @Lemongrass3110
@jezznar @secretdataz

izlude,116,158,5	script	equipnotwork	500,{
	equip .itemid;
	mes "equip "+.itemid+": I am attaching to npc atm.";
	mes "Since I already equip "+getitemname(.itemid)+" with this equip command I should get str bonus now but it didn't!";
	next;
	mes "recalculatestat: I am still attaching to npc atm.";
	recalculatestat;
	mes "If recalculatestat are working then I should get the bonus str but it didn't too!";
	mes "Instead If I have bonus in OnPCStatCalcEvent this command will it wipe out and will not reapply it.";
	next;
	mes "Since end is here I am no longer attaching to npc.";
	mes "Even I no longer attaching to any npc and the OnPCStatCalcEvent get trigger because I call recalculatestat before, the bonus still not get apply. You may see that manually equip with double click don't have this problem.";
	end;
	
OnInit:
	.itemid = 1201;
	end;

OnPCStatCalcEvent:
	dispbottom strnpcinfo(3)+" OnPCStatCalcEvent";
	if(getequipid(EQI_HAND_R)==.itemid){
		dispbottom strnpcinfo(3)+" OnPCStatCalcEvent: Is "+getitemname(.itemid);
		bonus bStr,10000;
	}
}

**Comment by Yuchinin** [comment]
Here is the simple example script that show all of the above are not working. @Lemongrass3110
@jezznar @secretdataz

izlude,116,158,5	script	equipnotwork	500,{
	equip .itemid;
	mes "equip "+.itemid+": I am attaching to npc atm.";
	mes "Since I already equip "+getitemname(.itemid)+" with this equip command I should get str bonus now but it didn't!";
	next;
	mes "recalculatestat: I am still attaching to npc atm.";
	recalculatestat;
	mes "If recalculatestat are working then I should get the bonus str but it didn't too!";
	mes "Instead If I have bonus in OnPCStatCalcEvent this command will it wipe out and will not reapply it.";
	next;
	mes "Since end is here I am no longer attaching to npc.";
	mes "Even I no longer attaching to any npc and the OnPCStatCalcEvent get trigger because I call recalculatestat before, the bonus still not get apply. You may see that manually equip with double click don't have this problem.";
	end;
	
OnInit:
	.itemid = 1201;
	end;

OnPCStatCalcEvent:
	dispbottom strnpcinfo(3)+" OnPCStatCalcEvent";
	if(getequipid(EQI_HAND_R)==.itemid){
		dispbottom strnpcinfo(3)+" OnPCStatCalcEvent: Is "+getitemname(.itemid);
		bonus bStr,10000;
	}
}
