### ISSUE TITLE
Clan & Clan Alliance DB

### ISSUE THREAD

**Issue by miraclez6** [rathena/rathena#2160]
* **rAthena Hash**: 

* **Client Date**: 

* **Server Mode**: 

* **Description of Issue**:  clan db error from source

i think the problem is the "clan" table is not connected or detect from src file .

im trying to change Sql_Query(sql_handle, "SELECT `name`, `master`, `mapname`, `max_member` FROM `%s` WHERE `clan_id`='%d'", schema_config.clan_

%s > clan 

the problem is clear but other DB error again with the same problem .
%s = clan_alliance tabble not clan table.

how to make the %s read clan table ? not the clan_alliance table.
nb : file downloaded from rathena & db from rathena ( download date : 20/05/2017 )

![untitled](https://cloud.githubusercontent.com/assets/28828723/26278051/2f35ab98-3dbd-11e7-8d37-0d82e3d37edb.png)

**Comment by Lemongrass3110** [comment]
conf/inter_athena.conf:
```
clan_table: clan
clan_alliance_table: clan_alliance
```
