### ISSUE TITLE
Dieter's Pyroclastic Bug

### ISSUE THREAD

**Issue by ilovelemon** [rathena/rathena#2162]
* **rAthena Hash**: I really do not know where I can see this. But my Git was downloaded on 04-25-2017

* **Client Date**: 2015-11-04

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: It only increases the attack of the Homunculus but not of the Genetic.
  * Expected Result: Pyroclastic should increase the attack of both homunculus and Genetic.
  * How to Reproduce: 
  * Official Information:Attack Boost (Homun_Level + 50) http://irowiki.org/wiki/Pyroclastic
  

* **Modifications that may affect results**: No modifications

**Comment by feltenc** [comment]
update your emulator, it was fixed on..

https://github.com/rathena/rathena/commit/4bb6aa13a057d20159028634e65ef0219e9a6472
https://github.com/rathena/rathena/commit/9ba2513ff4ea85a05722151bea4bdda49582ab04
