### ISSUE TITLE
[SQL]: DB error - Unknown column 'last_login' in 'field list'

### ISSUE THREAD

**Issue by Alkaryan** [rathena/rathena#2168]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/562d6d1e343d61620ebe4f4f60896a84132d231c

* **Client Date**: 2017-04-11

* **Server Mode**: Renewal

* **Description of Issue**: After the sicronization of the forlder, i've recopiled the Server and updated the DB. When I started the Runserver.bat i've got this...
  * Result: See the file Below
  * Expected Result: Server Runs Without Problem
  * How to Reproduce: Recompile the Server after this update
  * Official Information:
  

* **Modifications that may affect results**: 
  About the .SQL; in the Table 'char' this istruction:
<b>`last_login` datetime DEFAULT NULL,</b>
got me a sintax error. i've resolved in this way:
<b>`lastlogin` datetime NOT NULL default '0000-00-00 00:00:00',</b>
I know that's awfull but works.
<br>
[20170504_562d6d1.txt](https://github.com/rathena/rathena/files/1025619/20170504_562d6d1.txt)

**Comment by Jeybla** [comment]
> `last_login` datetime DEFAULT NULL,
> got me a sintax error.
Can you paste your syntax error here? Which mysql version are you using? Are you using mysql in STRICT-Mode?

**Comment by Lemongrass3110** [comment]
Please execute these sql commands and post the result:
```
SELECT version();
SELECT @@GLOBAL.sql_mode;
SELECT @@SESSION.sql_mode;
```

Thank you.

**Comment by Tokeiburu** [comment]
I can't help but notice a typo with `lastlogin` and `last_login`, the char table uses `last_login` (while the login table uses `lastlogin`). Could that be your issue?

**Comment by Lemongrass3110** [comment]
Oh wow thanks for noticing that Tokei.
With this it seems like a user problem.

**Comment by kukuasir1** [comment]
With this update I have a new problem , in the login table the `birthdate`  default is null, when I want
delete character with birthday is always faild.

**Comment by Lemongrass3110** [comment]
Why should that be a problem?
`delete from login where birthdate is not null;`

**Comment by kukuasir1** [comment]
I mean delete character with client.
![image](https://cloud.githubusercontent.com/assets/6629093/26587435/fd116038-4584-11e7-96d7-6525fc08a24e.png)

**Comment by Lemongrass3110** [comment]
Works correctly for me with and without having the birthdate set.
What clientversion are you using and which langtype do you use?

**Comment by Lemongrass3110** [comment]
You do not have to enter anything at all!

**Comment by anacondaqq** [comment]
Works for me fine too. No problems at all. MySQL 5.6
@Alkaryan try
`describe `char`;` and post it here
then
`describe `login`;` and post it here
then please add information about your MySQL-server version.

**Comment by kukuasir1** [comment]
@Lemongrass3110 Thank you! So I don't need to enter anything :D

**Comment by anacondaqq** [comment]
Okay, I found out where is a problem. And the issue can be closed because of this not problem of rAthena.
This is related to the commit: https://github.com/rathena/rathena/commit/799f781ac25bf7bf52061f973d72a3a9ff06281d

But not really to the commit, but by missing part of the commit which were not applied manually by server administrators. 

I'm talk about next .sql patches:

- upgrade_20170417.sql
- upgrade_20170417_logs.sql

After applying these patches from sql-files/upgrade/ folder the issue has been solved. 

### Before:
![problem printed](https://i.imgur.com/FMCnnbZ.png)

### After
![problem solved](https://i.imgur.com/75XNlVn.png)
