### ISSUE TITLE
Guild Info Error

### ISSUE THREAD

**Issue by Lilori** [rathena/rathena#2175]
* **rAthena Hash**: Latest

* **Client Date**: 2015

* **Server Mode**: RE

* **Description of Issue**: 
  * Result: Got this error message in my server.
`
[Error]: intif: guild info : data size error Gid: 10 recv size: 11020 Expected size: 11948
[Error]: intif: guild info : data size error Gid: 10 recv size: 11020 Expected size: 11948
[Error]: intif: guild info : data size error Gid: 10 recv size: 11020 Expected size: 11948
`
  * Expected Result: In previous rA hash (3 may 2017), that was fine.
  * How to Reproduce: How can this error message comes up?
  

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment]
Did you recompile ALL servers with the same packetversion after updating?

**Comment by Lilori** [comment]
Yes.

Reproduce : Create a guild with special character.

In Server version 3 May 2017 result : It's working fine. My server can create a guild with special character such as (tm), Black dots, etc. Without any problem.

In latest rA Git : The errors above comes up. The guild name become blank (no name)

**Comment by aleos89** [comment]
Whenever I use a special character the client tells me "That Guild Name already exists." and keeps me from creating the guild. I tested with hash 6c5faba and client 2015-11-04.
