### ISSUE TITLE
SC_MANHOLE not stopping players correctly

### ISSUE THREAD

**Issue by raynra** [rathena/rathena#219]
Characters are able to walk right through Manhole in many instances. When they stop walking, then the manhole effect kicks in (so they are in manhole effect though they are not on top of the manhole itself).

**Comment by cydh** [comment]
tested last night, seems working properly, not like ur issue. /hmm

**Comment by raynra** [comment]
Re-tested on latest GIT.
Only occurs in GvG maps, not PvP/normal maps.

**Comment by cydh** [comment]
somehow when on GVG/BG maps, knockback is disable and there's check for the manhole too (but need to check on official server)

**Comment by cydh** [comment]
sounds ridiculous but it's the official ways. every skill effects that make u stop, won't stop u immediately if at GVG/BG maps. Pointing https://github.com/rathena/rathena/commit/902c920b734cdaa0a13650528a6075937edfb95c#diff-1

**Comment by cydh** [comment]
confirm, but exception for this Manhole. xD
going to fix it soon
