### ISSUE TITLE
Fatal Error 10@infi

### ISSUE THREAD

**Issue by ilovelemon** [rathena/rathena#2192]
* **rAthena Hash**: 65fa130

* **Client Date**: 2015-11-04

* **Server Mode**: PreRenewal

* **Description of Issue**: 
  * Result: [Fatal Error]: map_setipport : received info that this map-server SHOULD have map '10@infi', but it is not loaded.

* **Modifications that may affect results**: none (fresh download)

**Comment by aleos89** [comment]
That map is not cached into the map_cache.dat for pre-renewal. You will need to update your map cache if you want to use that instance map.
