### ISSUE TITLE
Sword Stick [2] (Item ID : 1668) wrong view type

### ISSUE THREAD

**Issue by uddevil** [rathena/rathena#2193]
* **3e625dfdf9868690e36677701cbebe1b379a7485**: 

* **Client Date**: 2015-11-04aRagexe

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: ASPD Drop because item 'view' is 8 (Mace type)
  * Expected Result: Normal ASPD as other one-handed staff type (item view 10)
  * How to Reproduce: Equip sword stich [2] (Item ID 1668)
  * Official Information: RMS and irowiki data says that item id 1668 is One-Handed Staff class, instead of mace.
  

* **Modifications that may affect results**: 

db/re/item_db.txt data :
1668,Sword_Stick,Sword Stick,5,10,,500,120:150,,,2,0x800200,63,2,2,4,80,1,**_8_**,{ bonus bAspdRate,10; },{},{}

should it be (?) :
1668,Sword_Stick,Sword Stick,5,10,,500,120:150,,,2,0x800200,63,2,2,4,80,1,**_10_**,{ bonus bAspdRate,10; },{},{}

because afaik, on https://raw.githubusercontent.com/rathena/rathena/master/doc/item_db.txt says that View 8 is for maces, while data on RMS and irowiki says that the class is one-handed staff.

**Comment by Atemo** [comment]
According to itemInfo from kro client **ClassNum = 10**. You're right
