### ISSUE TITLE
bonus2  bAddRace,RC_DemiHuman & bonus2 bAddRace,RC_Player on headgear no effect

### ISSUE THREAD

**Issue by hartonox** [rathena/rathena#2196]
* **rAthena Hash**: Latest

* **Client Date**: 2015-11-04

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**: 
  
  

i try to use alice doll hat, and hit player / demi human monster but damage still same
5137,Alice_Doll,Alice Doll,4,20,,500,,1,,1,0xFFFFFFFE,63,2,256,,30,0,208,{ bonus2 bAddRace,RC_DemiHuman,10; bonus2 bAddRace,RC_Player,10; },{},{}
![err1](https://user-images.githubusercontent.com/18364089/27220118-32356346-52ae-11e7-8656-249d49e5184a.jpg)
![err11](https://user-images.githubusercontent.com/18364089/27220117-32336960-52ae-11e7-9636-5291cb9c22fc.jpg)

**Comment by jezznar** [comment]
Can you please check if you're only battling an "Eremes Guile" or an "Assassin Cross Eremes" ?
Because in the database, "Eremes Guile" is a Demon while an "Assassin Cross Eremes" is a Demi-human.
This is consistent with divine-pride.net.

**Comment by secretdataz** [comment]
Racial bonuses don't affect status ATK in renewal, and you don't have any items equipped :)
Equip a weapon and you'll notice a change.

**Comment by hartonox** [comment]
@secretdataz
