### ISSUE TITLE
Removal of bAtkRate from renewal items

### ISSUE THREAD

**Issue by aleos89** [rathena/rathena#2198]
* **rAthena Hash**: f52e4b6

* **Client Date**: 2015-11-04

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: In renewal attack is divided into bAtk, wAtk, and eAtk. When items are given the bonus `bAtkRate` it is then applied to all of these of these attacks when the actual bonus should not be applied to all but to wAtk and eAtk respectively.
  * Expected Result: Adjust all `bAtkRate` in the renewal item database to `bAddClass`.
  * How to Reproduce: Equip any item with a `bAtkRate` bonus and noticed how the damage increases for all types of attack when it shouldn't.
```
I'm testing on iRO Sakray with 120 str/120 dex (so my bAtk is high) and I use a knife with 17 attack.
That way, I should be seeing a big increase if the bonus is bAtkRate and no damage boost at all if it's using bAddClass.
And so far, my damage is jumping from 376 to 378 using items that are supposed to be bAtkRate.
```
  * Official Information: Tested on Aegis and iRO.

* **Modifications that may affect results**: None, tested on a clean rAthena.

Thanks to @Tokeiburu for bringing it to my attention!

**Comment by Tokeiburu** [comment]
For further reference, these are my tests on iRO (I ended up maxing my stats on the attacker 2):
![image](https://user-images.githubusercontent.com/8761658/27239873-b8fcaf64-52a0-11e7-8348-a717063af189.png)
With the following results:
![image](https://user-images.githubusercontent.com/8761658/27239889-c61f7924-52a0-11e7-9425-0b39e95454f4.png)
