### ISSUE TITLE
SC_FIGHTINGSPIRIT - ASPD bonus not applied for RK_RUNEMASTERY level 1-9

### ISSUE THREAD

**Issue by raynra** [rathena/rathena#220]
SC_FIGHTINGSPIRIT's ASPD bonus only works at Rune Mastery level 10. Smaller bonuses should apply at lower levels but currently does not.
````
if (sc->data[SC_FIGHTINGSPIRIT] && sc->data[SC_FIGHTINGSPIRIT]->val2)
                aspd -= (bl->type==BL_PC?pc_checkskill((TBL_PC *)bl, RK_RUNEMASTERY):10) / 10 * 40;
````
http://irowiki.org/wiki/Rune_Mastery

**Comment by cydh** [comment]
> ASPD Boost: `(RuneMasteryLv ÷ 10 × 4)`
in our source if the bonus is fixed value, that's mean the ASPD bonus just around
* level 5 = 5*4/10 = 2
* level 6 = 6*4/10 = 2
* level 7 = 7*4/10 = 2
* level 8 = 8*4/10 = 3
* level 9 = 9*4/10 = 3
* level 10 = 10*4/10 = 4

**Comment by cydh** [comment]
calling @aleos89
