### ISSUE TITLE
 Client has stopped working

### ISSUE THREAD

**Issue by Triedge** [rathena/rathena#2201]
* **rAthena Hash**: 1005b46735ef9b00b86faf62e6badc6a37df23ff

* **Client Date**:  2015-09-16a

* **Server Mode**: Pre-Renewal

* **Description of Issue**: 
  * Result: Client has stop working
  * Expected Result: Client work 
  * How to Reproduce: I currently have no idea. The problem started 3 or 4 days ago. At first I thought it was an error of lack of sprite of my users, but ... every time was more generalized. It seems to happen when a player is teleported out of a GvG or BG map. But it does not happen all the time ... as if missing some extra data that causes the error. I am currently making a .log file from the console to try to find out what happens. Again I clarify that this bug started this week.

**Comment by Triedge** [comment]
More information.
A player when using their SN with carton causes the error "Client stop working"
Remove all equipped items... The error continues.
Then remove the cart from the SN by means of the SQL. The error of the character was **solved**.
But ... I try to recreate the problem again and I can not do it.

I feel a bit confused, I do not understand what conditions are the ones that can cause the error.

**Comment by hazimjauhari90** [comment]
I don't think revision 21321 is the rathena git hash. U are most likely run rA on svn. Not using git...

**Comment by Triedge** [comment]
Update **rAthena Hash**....

**Comment by hazimjauhari90** [comment]
This guide might help u to update ur rathena hash

https://rathena.org/board/topic/87120-transitioning-from-svn-to-git

**Comment by hazimjauhari90** [comment]
Do u have try to use another client? How about trying 2015-11-04aRagexe client? U can use this client on pre-renewal, but u need to disable doram race creation in src/char/char.c

**Comment by Triedge** [comment]
why the client 2015-11-04 have doran creation windows.

**Comment by hazimjauhari90** [comment]
try to follow this guide.

https://rathena.org/board/topic/105147-doram-support/?do=findComment&comment=299793

**Comment by Akkarinage** [comment]
Client issues can be discussed on the forums.

**Comment by Lemongrass3110** [comment]
Give us the hash which you used before and after the update and maybe we can see something that might be related to this issue.
Also we need to know which changes or modifications to the source you are using, because it is most certainly related to something like this and not rathena itself, because then someone else would have approved your issue or would have commented that he/she has the same issue.

**Comment by Triedge** [comment]
I have no idea what my version was before the updated one. I just know that after updating, the problems started.
![screenshot_195](https://user-images.githubusercontent.com/5862340/27263946-88734ef2-543a-11e7-9804-daf2b79c20cb.png)
