### ISSUE TITLE
SC_ITEMBOOST Not work in server

### ISSUE THREAD

**Issue by playpsro** [rathena/rathena#2203]
* **rAthena Hash**:  a75133eb4d8976c1c890d5420665e7a76349e226
* **Client Date**: 2015-11-04
* **Server Mode**: Pre Renewal

* **Description of Issue**: SC_ITEMBOOST function is not work in the server. i try use bubble gum. and want to get the item with drop 50%, if use bubble gum the drops is increase 100%, so the result is 100%. and if i use @autoloot 50 . the drop item must not get it because the drop result is 100%. But after test, player still get a item with 50% drop when use command @autoloot 50
  * Result: Player still get the item with 100% Drop
  * Expected Result: Player must not get the item because he have used a bubble gum to increase drop item from 50% to 100% and the DROP must be 100%, but in real check the DROP still 50% because player still can get the item with command @autoloot 50
  * How to Reproduce: use bubble gum, check 1 item with have 50% drop like "Apple" from "Poring" , and then use command @autoloot 50
  * Official Information: Item must have a double drop if use bubble gum .

* **Modifications that may affect results**:  Just use a Gepard Shield,  nothing changed other source.
![bubblegumerror](https://user-images.githubusercontent.com/15665450/27270481-a560e304-54e8-11e7-8abf-108a9c98023d.jpg)

**Comment by Jeybla** [comment]
> but in real check the DROP still 50% because player still can get the item with command @autoloot 50

`@autoloot` and `@mobinfo` are intentionally not affected by `SC_ITEMBOOST`. You will always autoloot the "original" items. Also it's not possible to get a loot chance of 100% (if it's not original) with `SC_ITEMBOOST` the maximum is 90%.

Try it again, by just counting your loot with and without `SC_ITEMBOOST`. You should see the effect.

**Comment by jezznar** [comment]
Just a little addition to what @Jeybla said, "increased by" is different from "increased to"
https://www.divine-pride.net/database/item/12210/bubble-gum
What I mean is that "Item drop rate
increases by 100%" is not really raising the drop to 100% but instead it adds 100% of the current drop rate. In mathematical terms, if item1 currently has 1% chance of dropping, when you use bubble gum, it will be increased by another 1%
Hence,
Final drop rate = (100 + bubblegum_drop_mod)/100 x 1%
Final drop rate = (100 + 100)/100 x 1%
Final drop rate = 2 x 1%
Final drop rate = 2%

It's a different story when you say "Item drop rate is increased TO 100%" as  sets the Final drop rate directly to 100%.

Just my 2 cents for future references.

**Comment by playpsro** [comment]
hello, please open this issue again.
@Lemongrass3110 .

@jezznar have a give you full information about my bug / issue.
please check again about this.

sorry i'm using gepard / custom patch so i can't auto update rathena . if any change pls tell me what git hash so i will patch manually.

**Comment by playpsro** [comment]
sorry for my bad english so can give a good description about my issue .
pls help me

**Comment by aleos89** [comment]
There's nothing wrong with SC_ITEMBOOST as @Jeybla and @jezznar already stated above. This is how it behaves on official servers.
