### ISSUE TITLE
Cant get the reward on achievement when refining weapon

### ISSUE THREAD

**Issue by NeonRO2035** [rathena/rathena#2204]
When I do the achievement to refine a weapon, I cant get the reward, I just cant click on collect

**Comment by Lemongrass3110** [comment]
Please follow the issue template.

Is this an issue for #2044 or are you trying this on master?

**Comment by NeonRO2035** [comment]
Its an issue for #2044

**Comment by aleos89** [comment]
There are no rewards by default for the refining achievements.
