### ISSUE TITLE
Call Function Check errors

### ISSUE THREAD

**Issue by keitenai** [rathena/rathena#2205]
* **rAthena Hash**: 1005b46

* **Client Date**: Any
* **Server Mode**: Any

* **Description of Issue**: 
massive script Errors of non-existing function called if "#define SCRIPT_CALLFUNC_CHECK" is disabled.

**Comment by Jeybla** [comment]
Confirmed.

Example errors:
```[Error]:  Loading NPC file: npc/re/warps/guildcastles.txt
script error on npc/re/warps/guildcastles.txt line 95
    parse_simpleexpr: unmatched ')'
    90 : 	if (.@guild_id && .@guild_id == .@my_guild_id) {
    91 : 		warp .@castle$,getarg(1),getarg(2);
    92 : 		end;
    93 : 	}
    94 : 
*   95 : 	if (WoeTETimeStart'('3600) == 1) {
    96 : 		if (!.@guild_id || !.@my_guild_id) {
    97 : 			mes "It's time for preparing to WoE. Only Alliance guild is able to enter.";
    98 : 			close;
    99 : 		}
   100 : 		if (getguildalliance(.@my_guild_id,.@guild_id) != 1) {
[Error]:  Loading NPC file: npc/re/jobs/novice/academy.txt
script error on npc/re/jobs/novice/academy.txt line 12668
    parse_simpleexpr: unmatched ')'
  12663 : 	mes "Checking the user.. Completed.";
  12664 : 	mes "Select the refining equipment.";
  12665 : 	next;
  12666 : 	setarray .@indices[1], EQI_HEAD_TOP, EQI_ARMOR, EQI_HAND_L, EQI_HAND_R, EQI_GARMENT, EQI_SHOES, EQI_ACC_L, EQI_ACC_R, EQI_HEAD_MID, EQI_HEAD_LOW;
  12667 : 	for(set .@i,1; .@i<=10; set .@i,.@i+1)
* 12668 : 		.@menu$ = .@menu$ + ( getequipisequiped(.@indices[.@i]) ? getequipname(.@indices[.@i]): F_getpositionname'('.@indices[.@i]) +" - [Unarmed]" ) +":";
  12669 : 	.@part = .@indices[ select(.@menu$) ];
  12670 : 	if (!getequipisequiped(.@part)) {
  12671 : 		mes "[Refining Machine Wagjak]";
  12672 : 		mes "^ff0000- Error number 000"+.@part+" -^000000";
  12673 : 		mes "Item is not equipped.";
```

We should either remove the `SCRIPT_CALLFUNC_CHECK` option or always use callfunc. Without standard compiled warnings/mentions this issue will reoccur. I'd suggest a counter printed in the mapserver on script initialisation like.

**Comment by aleos89** [comment]
Honestly, I had no clue this existed. Is this even a widely used feature that people want to not use "callfunc" for calling a script function? If it's not really used I'd lean towards removing it.

**Comment by keitenai** [comment]
the note for this also says "this CAN affect performance".

**Comment by Atemo** [comment]
I used this feature on official script (it's convenient), but we can convert them to callfunc.
How does this feature really affect performance?

**Comment by keitenai** [comment]
i don't really know how it affects performance but it is indicated on the note:
`/// leave this line uncommented to enable callfunc checks when processing scripts.
/// while allowed, the script engine will attempt to match user-defined functions
/// in scripts allowing direct function callback (without the use of callfunc.)
/// this CAN affect performance, so if you find scripts running slower or find
/// your map-server using more resources while this is active, comment the line
//#define SCRIPT_CALLFUNC_CHECK`
