### ISSUE TITLE
When you die by monster while you talking with NPC you are not dead:) 

### ISSUE THREAD

**Issue by anacondaqq** [rathena/rathena#221]
![rathena_bug_monster](https://cloud.githubusercontent.com/assets/9905636/5700088/76cff3e2-9a3f-11e4-8828-e04ebe1e5b42.png)

pre-re, 2010-07-30 mmo.h
[git hash](https://github.com/rathena/rathena/commit/9021cb634910f8113c311921fb239eb7e0d1c5ca)

Nothing crytical.

**Comment by cydh** [comment]
at least tested on 2013-08-07 is invalid. /hmm

**Comment by Playtester** [comment]
Maybe because GM?

**Comment by Atemo** [comment]
Tested with 2013-07-17 pre-re with GM. I can't reproduce

**Comment by brianluau** [comment]
Unable to reproduce on e06b041d7d6ab53f912a404c03ec21a7b3f23bc3 
Any open NPC windows are closed when you die.

**Comment by anacondaqq** [comment]
@brianluau which packet version, and client date? It's related for 2010-*
