### ISSUE TITLE
Kagerou animation skill lost

### ISSUE THREAD

**Issue by blancoymoreno** [rathena/rathena#2213]
Client Date: 2017-06-23
Server Mode: Renewall

Description of Issue: Kagerou's shadow leap / shadow jump skill does not show its animation.
Result: When the user casts the "shadow leap", this skill works fine, it means kagerou jumps the cells, but the typical asociated animation after skill (kagerou should get down on his knees) dissapears, so Kagerou just ends the skill standing
How to Play: Activating "shadow hiding" and then "shadow leap" skill.

**Comment by keitenai** [comment]
2017 clients are not yet "officially" supported by rAthena.

https://rathena.org/board/topic/86650-officially-supported-client-versions/

**Comment by Lemongrass3110** [comment]
The client date you wrote does not exist.
Please give us the correct date and also add the git hash which you tried this on.

**Comment by ClayJensen** [comment]
Tried in 2015-11-04aRagexe. The animation is missing, after casting the skill Shadow Leap the Kagerou is standing.

**Comment by aleos89** [comment]
This is controlled by the client.
