### ISSUE TITLE
group.conf user command problem

### ISSUE THREAD

**Issue by dsskh** [rathena/rathena#2214]
* **rAthena Hash**: 6fc2399

* **Client Date**:  2015-09-16

* **Server Mode**: Pre-re

* **Description of Issue**: 
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**: 
  
  

groups: (
{
    id: 0 /* group 0 is the default group for every new account */
    name: "Player"
    level: 0
    inherit: ( /*empty list*/ )
    commands: {
        /* no commands by default */
        load: true
        storage: true
        whereis: true
        autoloot: true
    }
    permissions: {
        /* without this basic permissions regular players could not 
        trade or party */
        can_trade: true
        can_party: true
        storage: true
        guildstorage: true
        mobinfo: true
        autotrade: true
        iteminfo: true
        whodrops: true
        autoloot: true    
        view_equipment: true 
    }
},

I added this way.
However, users only apply whereis, autoloot, and view_equipment
The rest is not applicable. Also, all users
We will wear equipment regardless of item limit (occupation, level). But
If conf is initialized, it returns to normal.

rathena

**Comment by aleos89** [comment]
You put atcommands in the `permissions` section. Please read the [permissions documentation](https://github.com/rathena/rathena/blob/master/doc/permissions.txt) for what goes into the `permissions` section.

Also, please use the [forums](https://rathena.org/board/) for support on things like this. Thanks.
