### ISSUE TITLE
Error compiling #define ADJUST_SKILL_DAMAGE

### ISSUE THREAD

**Issue by keitenai** [rathena/rathena#2218]
* **rAthena Hash**: 20908ee
* **Client Date**: Any
* **Server Mode**: Any

* **Description of Issue**: 
Compilation error:

"Error	1	error C2086: 'eri *map_skill_damage_ers' : redefinition	C:\rAthena\src\map\map.cpp	132	1	map-server"

when `#define ADJUST_SKILL_DAMAGE` is enabled

**Comment by Xkipper** [comment]
`map.cpp:132:13: error: redefinition of ‘eri* map_skill_damage_ers’
 struct eri *map_skill_damage_ers = NULL;
             ^
In file included from map.cpp:18:0:
map.h:593:13: error: ‘eri* map_skill_damage_ers’ previously declared here
 struct eri *map_skill_damage_ers;
             ^
map.cpp: In function ‘int do_init(int, char**)’:
map.cpp:4699:106: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
  map_skill_damage_ers = ers_new(sizeof(struct s_skill_damage), "map.c:map_skill_damage_ers", ERS_OPT_NONE);
                                                                                                          ^
`

**Comment by secretdataz** [comment]
Fixed in e87626c. Thank you

**Comment by Xkipper** [comment]
> map.cpp: In function ‘int do_init(int, char**)’:
> map.cpp:4699:106: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
>   map_skill_damage_ers = ers_new(sizeof(struct s_skill_damage), "map.c:map_skill_damage_ers", ERS_OPT_NONE);

                                                                                                          ^
Now show a Warning()

**Comment by secretdataz** [comment]
@Xkipper That's unrelated to this issue.
