### ISSUE TITLE
Compilation warnings on VS2013

### ISSUE THREAD

**Issue by keitenai** [rathena/rathena#2219]
* **rAthena Hash**: 20908ee
* **Client Date**: Any
* **Server Mode**: Any

* **Description of Issue**: 

Having compilation warnings:

`7>LINK : warning C4744: 'agit3_flag' has different type in 'C:\rathena-github\src\map\map.cpp' and 'C:\rathena-github\src\map\battle.c': 'unsigned char' and 'signed char'
7>LINK : warning C4744: 'agit_flag' has different type in 'C:\rathena-github\src\map\map.cpp' and 'C:\rathena-github\src\map\battle.c': 'unsigned char' and 'signed char'
7>LINK : warning C4744: 'reg_load' has different type in 'C:\rathena-github\src\map\map.cpp' and 'C:\rathena-github\src\map\atcommand.c': 'unsigned char' and 'signed char'
7>LINK : warning C4744: 'agit2_flag' has different type in 'C:\rathena-github\src\map\map.cpp' and 'C:\rathena-github\src\map\battle.c': 'unsigned char' and 'signed char'
7>LINK : warning C4744: 'reg_load' has different type in 'C:\rathena-github\src\map\mercenary.c' and 'C:\rathena-github\src\map\map.cpp': 'signed char' and 'unsigned char'
7>LINK : warning C4744: 'reg_load' has different type in 'C:\rathena-github\src\map\mob.c' and 'C:\rathena-github\src\map\map.cpp': 'signed char' and 'unsigned char'
7>LINK : warning C4744: 'reg_load' has different type in 'C:\rathena-github\src\map\npc.c' and 'C:\rathena-github\src\map\map.cpp': 'signed char' and 'unsigned char'
7>LINK : warning C4744: 'reg_load' has different type in 'C:\rathena-github\src\map\npc_chat.c' and 'C:\rathena-github\src\map\map.cpp': 'signed char' and 'unsigned char'
7>LINK : warning C4744: 'reg_load' has different type in 'C:\rathena-github\src\map\party.c' and 'C:\rathena-github\src\map\map.cpp': 'signed char' and 'unsigned char'
7>LINK : warning C4744: 'reg_load' has different type in 'C:\rathena-github\src\map\pc.c' and 'C:\rathena-github\src\map\map.cpp': 'signed char' and 'unsigned char'
7>LINK : warning C4744: 'reg_load' has different type in 'C:\rathena-github\src\map\pc_groups.c' and 'C:\rathena-github\src\map\map.cpp': 'signed char' and 'unsigned char'
7>LINK : warning C4744: 'reg_load' has different type in 'C:\rathena-github\src\map\pet.c' and 'C:\rathena-github\src\map\map.cpp': 'signed char' and 'unsigned char'
7>LINK : warning C4744: 'reg_load' has different type in 'C:\rathena-github\src\map\quest.c' and 'C:\rathena-github\src\map\map.cpp': 'signed char' and 'unsigned char'
7>LINK : warning C4744: 'agit3_flag' has different type in 'C:\rathena-github\src\map\script.c' and 'C:\rathena-github\src\map\map.cpp': 'signed char' and 'unsigned char'
7>LINK : warning C4744: 'agit_flag' has different type in 'C:\rathena-github\src\map\script.c' and 'C:\rathena-github\src\map\map.cpp': 'signed char' and 'unsigned char'
7>LINK : warning C4744: 'reg_load' has different type in 'C:\rathena-github\src\map\script.c' and 'C:\rathena-github\src\map\map.cpp': 'signed char' and 'unsigned char'
7>LINK : warning C4744: 'agit2_flag' has different type in 'C:\rathena-github\src\map\script.c' and 'C:\rathena-github\src\map\map.cpp': 'signed char' and 'unsigned char'
7>LINK : warning C4744: 'reg_load' has different type in 'C:\rathena-github\src\map\searchstore.c' and 'C:\rathena-github\src\map\map.cpp': 'signed char' and 'unsigned char'
7>LINK : warning C4744: 'agit3_flag' has different type in 'C:\rathena-github\src\map\skill.c' and 'C:\rathena-github\src\map\map.cpp': 'signed char' and 'unsigned char'
7>LINK : warning C4744: 'agit_flag' has different type in 'C:\rathena-github\src\map\skill.c' and 'C:\rathena-github\src\map\map.cpp': 'signed char' and 'unsigned char'
7>LINK : warning C4744: 'reg_load' has different type in 'C:\rathena-github\src\map\skill.c' and 'C:\rathena-github\src\map\map.cpp': 'signed char' and 'unsigned char'
7>LINK : warning C4744: 'agit2_flag' has different type in 'C:\rathena-github\src\map\skill.c' and 'C:\rathena-github\src\map\map.cpp': 'signed char' and 'unsigned char'
7>LINK : warning C4744: 'agit3_flag' has different type in 'C:\rathena-github\src\map\status.c' and 'C:\rathena-github\src\map\map.cpp': 'signed char' and 'unsigned char'
7>LINK : warning C4744: 'agit_flag' has different type in 'C:\rathena-github\src\map\status.c' and 'C:\rathena-github\src\map\map.cpp': 'signed char' and 'unsigned char'
7>LINK : warning C4744: 'reg_load' has different type in 'C:\rathena-github\src\map\status.c' and 'C:\rathena-github\src\map\map.cpp': 'signed char' and 'unsigned char'
7>LINK : warning C4744: 'agit2_flag' has different type in 'C:\rathena-github\src\map\status.c' and 'C:\rathena-github\src\map\map.cpp': 'signed char' and 'unsigned char'
7>LINK : warning C4744: 'reg_load' has different type in 'C:\rathena-github\src\map\storage.c' and 'C:\rathena-github\src\map\map.cpp': 'signed char' and 'unsigned char'
7>LINK : warning C4744: 'reg_load' has different type in 'C:\rathena-github\src\map\trade.c' and 'C:\rathena-github\src\map\map.cpp': 'signed char' and 'unsigned char'
7>LINK : warning C4744: 'reg_load' has different type in 'C:\rathena-github\src\map\unit.c' and 'C:\rathena-github\src\map\map.cpp': 'signed char' and 'unsigned char'
7>LINK : warning C4744: 'reg_load' has different type in 'C:\rathena-github\src\map\vending.c' and 'C:\rathena-github\src\map\map.cpp': 'signed char' and 'unsigned char'
7>  Generating code`

on Visual Studio 2013

**Comment by CairoLee** [comment]
i have the same problem

**Comment by kukuasir1** [comment]
me too!!

**Comment by gengstergile** [comment]
me too..

**Comment by kukuasir1** [comment]
I find the reason...
because I use the release mode  compile the code!
use debug mode  everything will be OK!

**Comment by aleos89** [comment]
@Lemongrass3110 just fixed this in 1e63f89. Give it a whirl and see if it resolves your issue.

**Comment by kukuasir1** [comment]
@aleos89 https://github.com/rathena/rathena/commit/1e63f892d9b7a6fc82acf2dfc67c3eff92d26d72 only fixed yaml compilation error, these warnings still exist.

**Comment by kukuasir1** [comment]
@Lemongrass3110


```
9>LINK : warning C4744: “agit3_flag”在“E:\ro\rathena2\src\map\map.cpp”和“E:\ro\rathena2\src\map\battle.c”中具有不同的类型: “unsigned char”和“signed char”
9>LINK : warning C4744: “agit_flag”在“E:\ro\rathena2\src\map\map.cpp”和“E:\ro\rathena2\src\map\battle.c”中具有不同的类型: “unsigned char”和“signed char”
9>LINK : warning C4744: “agit2_flag”在“E:\ro\rathena2\src\map\map.cpp”和“E:\ro\rathena2\src\map\battle.c”中具有不同的类型: “unsigned char”和“signed char”
9>LINK : warning C4744: “agit3_flag”在“E:\ro\rathena2\src\map\script.c”和“E:\ro\rathena2\src\map\map.cpp”中具有不同的类型: “signed char”和“unsigned char”
9>LINK : warning C4744: “agit_flag”在“E:\ro\rathena2\src\map\script.c”和“E:\ro\rathena2\src\map\map.cpp”中具有不同的类型: “signed char”和“unsigned char”
9>LINK : warning C4744: “agit2_flag”在“E:\ro\rathena2\src\map\script.c”和“E:\ro\rathena2\src\map\map.cpp”中具有不同的类型: “signed char”和“unsigned char”
9>LINK : warning C4744: “agit3_flag”在“E:\ro\rathena2\src\map\skill.c”和“E:\ro\rathena2\src\map\map.cpp”中具有不同的类型: “signed char”和“unsigned char”
9>LINK : warning C4744: “agit_flag”在“E:\ro\rathena2\src\map\skill.c”和“E:\ro\rathena2\src\map\map.cpp”中具有不同的类型: “signed char”和“unsigned char”
9>LINK : warning C4744: “agit2_flag”在“E:\ro\rathena2\src\map\skill.c”和“E:\ro\rathena2\src\map\map.cpp”中具有不同的类型: “signed char”和“unsigned char”
9>LINK : warning C4744: “agit3_flag”在“E:\ro\rathena2\src\map\status.c”和“E:\ro\rathena2\src\map\map.cpp”中具有不同的类型: “signed char”和“unsigned char”
9>LINK : warning C4744: “agit_flag”在“E:\ro\rathena2\src\map\status.c”和“E:\ro\rathena2\src\map\map.cpp”中具有不同的类型: “signed char”和“unsigned char”
9>LINK : warning C4744: “agit2_flag”在“E:\ro\rathena2\src\map\status.c”和“E:\ro\rathena2\src\map\map.cpp”中具有不同的类型: “signed char”和“unsigned char”
```

......
these warnings still exist

**Comment by Lemongrass3110** [comment]
@kukuasir1 please check your source. I moved all agit_flags into guild.c a while ago and they are only accessed with functions from guild.c now. I can't reproduce those warnings with a fresh clone.

**Comment by Yuchinin** [comment]
I just compile it with latest hash and have no error at all.

**Comment by kukuasir1** [comment]
I re-test it
Use VS2013 release mode compile the fresh clone these warnings still exist...
Use VS2015 release mode have no warnings .
