### ISSUE TITLE
unitwalk and unitwalkto event label looping

### ISSUE THREAD

**Issue by zellkennedy** [rathena/rathena#2222]
- rAthena Hash: 20908ee
- Client Date: Any
- Server Mode: Any
- Description of Issue:

When using unitwalk or unitwalkto with event when reach, the event still are attach to player when he walks.

How to reproduce:
	
```
prontera,150,150,5	script	TEST	90,{

	unitwalk getcharid(3),150,150,"TEST::OnReach";
	end;
	
	OnReach:
	announce "Now stay walking near the npc randomly. This will appear every time!",0;
	end;
}
```

Even if I use "@reloadscript" the player are still attached with this event label. The unique way to detach this label is loggin out.

Probably a problem with timer in source?

**Comment by LQyr** [comment]
+1

I can reproduce this.

**Comment by Yuchinin** [comment]
I can confirm this too.
