### ISSUE TITLE
getequipid() is given 0 instead of -1 when nothings equipped.

### ISSUE THREAD

**Issue by talesvalente** [rathena/rathena#2228]
* **rAthena Hash**: 9827bf615379aa0780095331f96ddfff682bda84 (latest)

* **Client Date**: 2015-11-04a

* **Server Mode**: Renewal

* **Description of Issue**: getequipid() is not return -1 like rathena/doc/scripts_commands.txt says.
  * Result: if nothings on getequipid(position) this returns 0 instead -1
  * Expected Result: returns -1 when nothing is equipped
  * How to Reproduce: 
```
for (.@i = 0; .@i <= 20; .@i++) {
		dispbottom "DEBBUG: "+.@i+" "+getequipid(.@i)+"";
}
```

**Comment by aleos89** [comment]
Please make sure to use code blocks so you don't tag inadvertent GitHub users through the `@` tag.

Will check out the issue.
