### ISSUE TITLE
Looting Monster's Random Problem

### ISSUE THREAD

**Issue by Lemongrass3110** [rathena/rathena#223]
It seems like all the monsters get the same "random" item as target.

Little video:
http://youtu.be/2TrOY-Dghmo

**Comment by cydh** [comment]
afaik there's random logic was changed, to get the first item dropped. if there are 10 items and 10 mobs of course the mobs will targets same item

**Comment by Playtester** [comment]
Yes this is working as intended. I tested on Aegis in different scenarios and looters will always go for the oldest item in their view range, so if there are multiple looters they are likely to go to the same item.

Properly implemented here: https://github.com/rathena/rathena/commit/e6caa9569b62eec5093954a4298ff0d2632cdb53
