### ISSUE TITLE
Taekwon Mission in the top ten list

### ISSUE THREAD

**Issue by sanny1128** [rathena/rathena#2232]
rAthena Hash: eaeec3973
Client Date: 2017-01-25RagexeRE
Server Mode: Renewall

Description of Issue:  TaeKwon Kids are in the top ten list and are over Level 90 will be able to use all of the TaeKwon Kid skills but when after a few minutes the buff will invalid 

Result: TaeKwon Kids are in the top ten list and are over Level 90 will learn all of the TaeKwon Kid skills but 
after a few minutes all of the TaeKwon Kid skills can't use except original learn skills

How to Reproduce:change job to Taekwon then use Taekwon Mission and get TaeKwon ranks in the top ten list and over Level 90

**Comment by Lemongrass3110** [comment]
I just tried this and everything worked correctly.
Did you possibly get a job level up? Because this only works as long as you do not have any skill points left.

**Comment by sanny1128** [comment]
@Lemongrass3110 yes i get a job level up...sorry for i don't know this rule
 kindly close this issue tks
