### ISSUE TITLE
Thorn Wall

### ISSUE THREAD

**Issue by Felleonel** [rathena/rathena#2233]
* **rAthena Hash**: ba242eb

* **Client Date**:  2017-01-25RagexeRE

* **Server Mode**: Renewal

* **Description of Issue**: 
 * Result: The skill doesn't deal damage or push back 2 cells when used. It is possible to cross the wall.
 * Expected Result: On contact, the wall should deal damage and knockback 2 cells.
 * How to Reproduce: Use Thorn Wall with a Geneticist and try walking through it. 
 * Official Information: Thorn Wall: Produces a wall of thorns around a single target, which will inflict damage in contact and push 2 cells backwards. (http://irowiki.org/wiki/Thorn_Wall)

**Comment by aleos89** [comment]
I'm unable to reproduce this using 5462b08.
![2017-07-06_16-51-05](https://user-images.githubusercontent.com/3521753/27932326-63ef9fba-626b-11e7-9f34-2279f4c20801.gif)

**Comment by Felleonel** [comment]
I've done more tests and it's working properly. Thanks.
