### ISSUE TITLE
Hell Inferno just inflict fire element

### ISSUE THREAD

**Issue by hartonox** [rathena/rathena#2236]
* **rAthena Hash**:  -

* **Client Date**:  2015-11-04

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**: 
  
  
Hell Inferno just inflict fire element, i have try it to pasana, it must be Fire & Shadow element right?
http://irowiki.org/wiki/Hell_Inferno

**Comment by aleos89** [comment]
Cast:
```c
	case WL_HELLINFERNO:
		skill_attack(BF_MAGIC,src,src,bl,skill_id,skill_lv,tick,flag);
		skill_attack(BF_MAGIC,src,src,bl,skill_id,skill_lv,tick,flag|ELE_DARK);
		break;
```
Damage calculations:
```c
					case WL_HELLINFERNO:
						skillratio += -100 + 300 * skill_lv;
						RE_LVL_DMOD(100);
						// Shadow: MATK [{( Skill Level x 300 ) x ( Caster Base Level / 100 ) x 4/5 }] %
						// Fire : MATK [{( Skill Level x 300 ) x ( Caster Base Level / 100 ) /5 }] %
						if (mflag&ELE_DARK)
							skillratio *= 4;
						skillratio /= 5;
						break;
```
Looks fine to me. The skill issues damage twice but it doesn't actually do Fire or Shadow elemental damage. It does have a chance of giving Burning to the target though.

**Comment by aleos89** [comment]
Further inspection I just realized that the ELE_DARK flag is not checked later on.

**Comment by hartonox** [comment]
okay thanks

**Comment by Badarosk0** [comment]
This problem still happens in the current version of the emulator. It is not gegrando second shadow damage and yes only fire.
