### ISSUE TITLE
Possible wrong Homunculi starving intimacy decrease rate

### ISSUE THREAD

**Issue by mmalka** [rathena/rathena#2242]
* **rAthena Hash**: 
https://github.com/rathena/rathena/commit/7351b88c1423c60768ba1cc0c7f4d79c8969dc5a

* **Client Date**: 20130807

* **Server Mode**: pre-renewal

* **Description of Issue**: 
  * Result: Currently losing intimacy at a rate of 1 per minute when starving
  * Expected Result: Lose  intimacy at a rate of 1 every 200 seconds when starving
  * How to Reproduce: get an homunculus, let it starve and check with @hominfo
  * Official Information: http://irowiki.org/classic/Homunculus_System

```
Each hour of starving cause 18 Intimacy loss (3600 seconds per hour / 200 seconds per loss).

If the player is away from the computer for a full 24 hours of starving, the Homunculus loses 432 Intimacy 18*24=432
```
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
It would be great to figure out if this is the same on kRO.

**Comment by aleos89** [comment]
It's been confirmed on kRO it's every 60 seconds but when the homunculus' hunger is between 0-10, the delay becomes 20 seconds.
