### ISSUE TITLE
cc1plus: error: unrecognized command line option "-std=c++11"

### ISSUE THREAD

**Issue by reunite-ro** [rathena/rathena#2243]
* **https://github.com/rathena/rathena/commit/27a30ffa51e346f813ac27b4642ffb33a55eccc1**: 

* **20150916**: 

* **Pre-Renewal**: 

* **Description of Issue**: 
  * Result: `make[1]: Entering directory `/root/rathena/src/common'
        MKDIR   obj
        CXX     core.cpp
cc1plus: error: unrecognized command line option "-std=c++11"
cc1plus: warning: unrecognized command line option "-Wno-maybe-uninitialized"
make[1]: *** [obj/core.o] Error 1
make[1]: Leaving directory `/root/rathena/src/common'
make: *** [common] Error 2
` 
  * How to Reproduce: ./configure using CentOS 6
 
  

* **https://github.com/rathena/rathena/commit/4a2574c5994ef203ea35c69526a681b34bb97c3d**:

**Comment by aleos89** [comment]
Did you make sure you installed C++? `yum install gcc-c++`

**Comment by reunite-ro** [comment]
yup i already install that

`Package gcc-c++-4.4.7-18.el6.x86_64 already installed and latest version
Nothing to do`

**Comment by Lemongrass3110** [comment]
Try this:
https://rathena.org/board/topic/110898-rathena-now-requires-g-to-compile-on-linux/?do=findComment&comment=325988

**Comment by Lemongrass3110** [comment]
No further input so you probably solved your problem.
