### ISSUE TITLE
VS 2017, compiling warning: '=': conversion from 'time_t' to 'uint32', possible loss of data

### ISSUE THREAD

**Issue by anacondaqq** [rathena/rathena#2246]
hash: 073927550802ede3ddad907d1a86a51642d521d5
VS 2017 Community.

### Warning details:
```
Warning	C4244	'=': conversion from 'time_t' to 'uint32', possible loss of data	char-server	c:\rathena\src\char\int_guild.c	1099	

```
The warning crying about next code: https://github.com/rathena/rathena/blob/master/src/char/int_guild.c#L1099

### Extra Info

Clean rAthena. No modifications. 

![](https://i.imgur.com/wf0gP9f.png)

**Comment by CairoLee** [comment]
same problem in visual studio 2013
