### ISSUE TITLE
Math Error and low priorite bugs

### ISSUE THREAD

**Issue by talesvalente** [rathena/rathena#2247]
* **rAthena Hash**: 073927550802ede3ddad907d1a86a51642d521d5

* **Client Date**: Default 2015

* **Server Mode**: Renewal (Vip Enable)

If you set **VIP_DROP_INCREASE** (conf/battle/player.conf) to **100** itens with more than 50% default chance will shows on **monsterinfo** more than 100%. E.g Tentacle of Hydra Default 55%, with this set, drop gets 110%

How to Fix: may add a self check to define everyting that pass max value(100%) to 100%?

**You must be wondering, WHY THA'HELL bother about it !? I suffer from obsessive compulsive disorder, and my server's rates are based on multiple of 5, 10, 15... its hurt me...**

**UPDATE:**
This is not important. I'm just saying a finding.

**Comment by Akkarinage** [comment]
Please fill out the template correctly. "Latest" is not a git hash. Please also submit one bug per Issue. My OCD goes skitz when users can't follow instructions.

**Comment by talesvalente** [comment]
Forgive-me, master! @Akkarinage
