### ISSUE TITLE
Drop system with math calc error

### ISSUE THREAD

**Issue by talesvalente** [rathena/rathena#2248]
* **rAthena Hash**: 073927550802ede3ddad907d1a86a51642d521d5

* **Client Date**: Default 2015

* **Server Mode**: Renewal (Vip Enable)

If you set **item_rate_card**: 250, the **monsterinfo** will shows only 0,02% instead of 0,025%... 

Setting the **VIP Configuration** to increase the rate of all possibilites to 100% ([like the first bug](https://github.com/rathena/rathena/issues/2247)), the drop will increase to 0,04% instead of 0,05%

How to Fix: increase the float point to .3f instead of .2f?

**UPDATE**
This is not important. I'm just saying a finding.

**Comment by aleos89** [comment]
*Athena has always been two decimal places, not three.

**Comment by Lemongrass3110** [comment]
The Athena engine has always used values from 0(0,00%) to 10.000(100,00%).
All other values are neither supported by the Athena nor AEGIS itself.
This is working as intended.
