### ISSUE TITLE
Character Delete Issue

### ISSUE THREAD

**Issue by lelouch22** [rathena/rathena#2251]
* **rAthena Hash**: c6c8d0b

* **Client Date**: 2014-10-22bRagexe

* **Description of Issue**: 
  * Result: 

After i set the char_del_delay to 0 and click the Delete button on Character Select this happens
![screenacadiaro004](https://user-images.githubusercontent.com/4976551/28099771-fda7f6a0-66f0-11e7-9f1f-30887b771958.jpg)

Then after a few sec the delete date and time became red and turned into 1/1 - 8:0:0, after that you cannot press the del button. Also even i reconnect my account its still the same.
![screenacadiaro005](https://user-images.githubusercontent.com/4976551/28099803-2d420356-66f1-11e7-9d96-5fc3c9353787.jpg)

[Note]: I tryed changing the langtype from 0 to 1 but its all the same.

**Comment by anacondaqq** [comment]
something wrong with time at all, already saw many functions where `time` is broken (my issue report, some other guys report about even crashes because of time).  https://github.com/rathena/rathena/issues/2246 
https://github.com/rathena/rathena/issues/2250

**Comment by Lemongrass3110** [comment]
@anacondaqq your issue is a simple warning from a missing cast. This is not really an issue.
This issue instead is probably related to some packets we send to the client. From my guess we send out the time as zero instead of sending the current one(the point of time that has to be passed so you can send the second delete request).
I will have to set up a 2014 client to confirm this though.

**Comment by Lemongrass3110** [comment]
Time will work until 2038. If rAthena still exists at that point we hopefully migrated away from unix timestamp though. :-)

**Comment by Lemongrass3110** [comment]
@lelouch22 sorry I do not have that client anymore.
Could you open mmo.h and find that line:
``` 
/// Check if the client needs delete_date as remaining time and not the actual delete_date (actually it was tested for clients since 2013)
#define PACKETVER_CHAR_DELETEDATE (PACKETVER > 20130000 && PACKETVER < 20141016) || PACKETVER >= 20150513
```
As you can see it's set to 2014-10-16. Could you change this to this:
``` 
/// Check if the client needs delete_date as remaining time and not the actual delete_date (actually it was tested for clients since 2013)
#define PACKETVER_CHAR_DELETEDATE (PACKETVER > 20130000 && PACKETVER <= 20141022) || PACKETVER >= 20150513
```

This issue is somewhat related to #2027

**Comment by lelouch22** [comment]
@Lemongrass3110 It works fine now...
![screenacadiaro006](https://user-images.githubusercontent.com/4976551/28144854-96ee1286-67a0-11e7-86c5-49650dc38bf4.jpg)

Maybe you should set its date to rA latest client date so that this will not happen again to others besides that deletion func is in 2013+ clients, just a suggestion.

**Comment by Akkarinage** [comment]
@lelouch22 
```|| PACKETVER >= 20150513``` it's already set to all latest clients.
