### ISSUE TITLE
My map server crash

### ISSUE THREAD

**Issue by chuchpong** [rathena/rathena#2252]
- rAthena Hash: I can not get my hash I may delete git file in my server folder but I think I have checked it out arount Septerber 2016
- Client Date: 2016-01-06aRagexe_DP
- Server Mode: Renewal Mode

- More information
I don't know why my map is crash but my core dump show this below result.

Core was generated by `./map-server'.
Program terminated with signal 11, Segmentation fault.
#0  0x0000000000487dc3 in clif_elemental_updatestatus (
    sd=<value optimized out>, type=5) at clif.c:16850
16850                           WFIFOL(fd,4) = status->hp;
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.209.el6_9.1.x86_64 keyutils-libs-1.4-5.el6.x86_64 krb5-libs-1.10.3-65.el6.x86_64 libcom_err-1.41.12-23.el6.x86_64 libselinux-2.0.94-7.el6.x86_64 mysql-libs-5.1.73-8.el6_8.x86_64 nss-softokn-freebl-3.14.3-17.el6.x86_64 openssl-1.0.1e-57.el6.x86_64 pcre-7.8-7.el6.x86_64 zlib-1.2.3-29.el6.x86_64
(gdb) bt full
#0  0x0000000000487dc3 in clif_elemental_updatestatus (
    sd=<value optimized out>, type=5) at clif.c:16850
        ed = 0xcdcdcdcdcdcdcdcd
        status = 0xcdcdcdcdcdcdd22d
        fd = 10
#1  0x00000000004be90e in elemental_heal (ed=0x7f92f6af8e6c,
    hp=<value optimized out>, sp=<value optimized out>) at elemental.c:535
No locals.
#2  0x00000000005e171d in status_heal (bl=0x7f92f6af8e6c,
    hhp=<value optimized out>, hsp=<value optimized out>, flag=1)
    at status.c:1843
        status = 0x7f92f6af92cc
        sc = 0x0
        hp = 6
        sp = <value optimized out>
#3  0x00000000005e1f3f in status_natural_heal (bl=0x7f92f6af8e6c,
    args=<value optimized out>) at status.c:13520
        val = <value optimized out>
        regen = 0x7f92f6afa7ec
        status = <value optimized out>
        sc = 0x0
        ud = <value optimized out>
        vd = <value optimized out>
---Type <return> to continue, or q <return> to quit---

How can I fix this issue?
Thank you in advance Sir

**Comment by Lemongrass3110** [comment]
Please update your emulator and try to reproduce the issue.
Thank you
