### ISSUE TITLE
Dragon Breath increase damage with racial card

### ISSUE THREAD

**Issue by FrFrMako** [rathena/rathena#2253]
- Server Mode: Renewal

- Description of Issue:
  * Result: Racial Card (Hydra, Caramel, Abysmal Knight....) increase damage.
  * Expected Result: Only increased by ranged damage (Archer Skeleton card, expert archer..)
  * How to Reproduce: Make a mace [4] with 4 hydra card and hit a player.
  * Official Information: Test made by Ziu on kRO oficial server https://www.youtube.com/watch?v=LRWv0wtg2qE

**Comment by FrFrMako** [comment]
-Hash: 0739275
-Client Date: 2015-11-04

**Comment by cydh** [comment]
@FrFrMako if you want a custom https://rathena.org/board/topic/105379-expanded-skill_dbsnk-flags-added-race-range-class-elemental-size-filter/

**Comment by ecdarreola** [comment]
@cydh Sorry to revive this old issue.  I don't understand this line "If you want to this flag works better, remove the 0x08 and 0x10 first". Can you enlighten me about it. Thanks!

**Comment by secretdataz** [comment]
No longer valid
