### ISSUE TITLE
unitstopwalk not working

### ISSUE THREAD

**Issue by Yuchinin** [rathena/rathena#2254]
* **rAthena Hash**: eaeec3973e2889c5f0f0a9b26cb329775e8f2a1a

* **Client Date**: Server side issue

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Unit not stopping immediately when calling this command.
  * Expected Result: Unit should stop immediately when calling this command.

  * How to Reproduce: -
  

* **Modifications that may affect results**: -

**Comment by Lemongrass3110** [comment]
unitstopwalk does not force a immediate stop of the unit.
We could offer the flags that are inside unit.c::unit_stop_walking to the script engine though.
We call it with flag=0 right now. What you would want it to would be:
`&0x8: Force stop moving, even if walktimer is currently INVALID_TIMER`

@Atemo @aleos89 thoughts?

**Comment by aleos89** [comment]
Agreed, we could add optional flags on how people want the unit to stop walking.
