### ISSUE TITLE
Homunculus Error :  "unknown menu choice : 114" when Feeding

### ISSUE THREAD

**Issue by keitenai** [rathena/rathena#2256]
* **rAthena Hash**:  d9d9042
* **Client Date**: 20160203
* **Server Mode**:  Renewal

* **Description of Issue**: 
  * Nothing's happening when feeding Homunculus in-game
  * Getting Error "hom_menu : unknown menu choice : 114" on server console.

No Modification

**Comment by Lemongrass3110** [comment]
First of all that client is not officially supported yet.
Make sure you use the correct packet db entries. This sound like your hommenu entry could be wrong.
Please copy your packet db entries into this issue.

**Comment by keitenai** [comment]
I see, well here's my packetdb:

//Add new packets here
packet_ver: 56
packet_keys: 0x3E1411AF,0x6C744497,0x7CFA1BDE // [Winnie]

0x0369,7,actionrequest,2:6
0x083C,10,useskilltoid,2:4:6
0x0940,5,walktoxy,2
0x0437,6,ticksend,2
0x0811,5,changedir,2:4
0x095A,6,takeitem,2
0x0947,6,dropitem,2:4
0x095D,8,movetokafra,2:4
0x0954,8,movefromkafra,2:4
0x0438,10,useskilltopos,2:4:6:8
0x0366,90,useskilltoposmoreinfo,2:4:6:8:10
0x096A,6,getcharnamerequest,2
0x0368,6,solvecharname,2
0x0838,12,searchstoreinfolistitemclick,2:6:10
0x07E4,2,searchstoreinfonextpage,0
0x0436,-1,searchstoreinfo,2:4:5:9:13:14:15
0x0202,-1,reqtradebuyingstore,2:4:8:12
0x0360,6,reqclickbuyingstore,2
0x0817,2,reqclosebuyingstore,0
0x0815,-1,reqopenbuyingstore,2:4:8:9:89
0x086C,18,partybookingregisterreq,2:4
0x0918,8
0x0835,-1,itemlistwindowselected,2:4:8
0x0819,19,wanttoconnection,2:6:10:14:18
0x093E,26,partyinvite2,2
0x088C,4
0x0361,26,friendslistadd,2
0x0872,5,hommenu,4
0x0873,36,storagepassword,0

0x0a38,3//
0x0a46,14//
0x0a47,3//
0x0a48,2//

**Comment by keitenai** [comment]
Ohhh! I got it! thanks for giving me the idea.

Fixed by changing:
   0x0872,5,hommenu,4
into:
   0x0872,5,hommenu,2:4


(^_^)
