### ISSUE TITLE
Compile with Centos , How to fix

### ISSUE THREAD

**Issue by tonfubu** [rathena/rathena#2257]
How to fix compile

![1500018752639](https://user-images.githubusercontent.com/18319180/28205815-d50e5054-68ad-11e7-8cf1-d67032fa6e8e.jpg)

thank you.

**Comment by tonfubu** [comment]
next error
![1500029422668](https://user-images.githubusercontent.com/18319180/28209519-ff255338-68bc-11e7-83b3-8193c9faa3e1.jpg)

**Comment by Akkarinage** [comment]
Thank you for your unhelpful Issue submission.

Can you provide the OS dist/version you're using? Can you tell us the version of gcc you have installed? Can you give us your Git hash? Can you use the correct template that appears when you first begin Issue submission?
