### ISSUE TITLE
Doram Issue

### ISSUE THREAD

**Issue by AsiaGenius** [rathena/rathena#2259]
try to grab these lua files & put into ur skillinfoz folder inside ur grf

https://github.com/zackdreaver/ROenglishRE/tree/master/data/luafiles514/lua%20files/skillinfoz/RebellionRE

it not works for those expanded summoner skills with 2015-11-04aRagexe Client. below are the screenshots..

![](https://cloud.githubusercontent.com/assets/16514357/25930870/49d5302e-363b-11e7-9867-c6bb34e65c9d.jpg)

**Comment by admkakaroto** [comment]
Work Perfect: http://imgur.com/2IzfZ8P

**Comment by AsiaGenius** [comment]
What is your lua files? Could you tell me how I can get it?

**Comment by admkakaroto** [comment]
https://github.com/zackdreaver/ROenglishRE

**Comment by Lemongrass3110** [comment]
Please use the forum for client related questions.
