### ISSUE TITLE
Bug in the all effects skills ex; Stoned

### ISSUE THREAD

**Issue by ruarez** [rathena/rathena#226]
Well, in my server, effects skills when used in mob cause crash on map-server, WTF ?

example
Masquerade Weakness, I put in the status,.c this line

if ( bl->type == BL_MOB) {
return 1;
}

and this worked!!
can someone help me ?

**Comment by aleos89** [comment]
You gave a mob the skill Masquerade Weakness? Many player skills are not setup to be used by monsters.

I have no issues casting the skill on a monster.
