### ISSUE TITLE
partylock Bug

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#2260]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/6e2ab60016ad4518bd38103d9b137ad325e4b90c
* **Client Date**: 2017-03-15 | 2015-11-04
* **Server Mode**: Renewal
* **Description of Issue**: The mapflag partylock is not blocking the party's leadership change in any way.
  * Result: You can change the leadership of the party's even with the mapflag set to block.
  * Expected Result: Do not allow leadership change if you have active mapflag.
  * How to Reproduce: Add the mapflag, enter the map and you're done, you can change the lead.

* **Prints:**:
 * Img1: http://imgur.com/0APISa6
 * Img2: http://imgur.com/6yWyzCp
 * Img3: http://imgur.com/LtswV2J

**Comment by Lemongrass3110** [comment]
![grafik](https://user-images.githubusercontent.com/3517879/28242392-93b36952-69aa-11e7-90f2-e04eb621b21b.png)

**Comment by admkakaroto** [comment]
It seems that something is happening in my emulator, because if I set the direct mapflag in the file /npc/mapflag/partylock.txt it does not appear in the list of active mapflags on the map, however if I use within the game '@mapflag partylock 1 'it works.

**Comment by Lemongrass3110** [comment]
I set it by npc and by atcommand and both worked correctly.
Please try to check your modifications.
