### ISSUE TITLE
No mod rights after creating a Channel

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#2261]
* **rAthena Hash**: 
b564b2

* **Client Date**: 
2015-09-16aRagexe

* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result: I've been testing the channel system with a normal player account (group id 0) and noticed that i wasn't able to change colors or ban players using the specific channel commands.
You get the response that you are not the creator of the channel.
  * Expected Result: After creating a channel i'm expecting to be the creator of it. And with that expecting to have the rights to modify colors and so on.
  * How to Reproduce: 
1. Use a normal player account (group id 0) for this scenario.
2. Enable the channel command in the group.conf for group id 0 so that you're able to use the channel commands.

3. Use the following commands to first create the channel and then try to use mod commands which are available for custom channels.
``` `@channel create #me` ```

``` `@channel banlist #me` ```

You should now get the answer that you can't use the command because you're not the creator of the channel called ME

  * Official Information:
  

* **Modifications that may affect results**: 
enable channel command for group id 0 or test using Super Player with group id 1 where it is enabled already.

**Comment by Lemongrass3110** [comment]
Fixed in 9eaabd5
