### ISSUE TITLE
Devotion animation Glitch

### ISSUE THREAD

**Issue by Shizuke** [rathena/rathena#2264]
Hi, when spamming devotion and receiving damage at the same time (from the character you devoted) you got stuck and can't spamm any targetted skill until you move/refresh/do self-skill (like first aid, endure, etc).

**Comment by Paoly28** [comment]
This is official, whenever devoted target is hit you'd get animation locked and had to break the lock by either moving or using skills that are self target

**Comment by Shizuke** [comment]
Oh then it is intended? i didn't know that. I don't want to play paladin anymore.
