### ISSUE TITLE
Rebelion base lvl 160 not showing aura on 2017 client

### ISSUE THREAD

**Issue by hendra814** [rathena/rathena#2267]
* **rAthena Hash**: lastest

* **Client Date**: 2017-01-25

* **Server Mode**: Renewal

* **Description of Issue**: Aura not showed on job Rebelion base lvl 160 using 2017 client , but showed at 2015 client
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**: 
  
  

client 2015
![screenrathena005](https://user-images.githubusercontent.com/9587609/28247057-68e8aa62-6a53-11e7-90f6-b2c371d5783c.jpg)

client 2017
![screenrathena004](https://user-images.githubusercontent.com/9587609/28247059-749c5f0c-6a53-11e7-96b6-3421a548f7ce.jpg)

And why when i turn ON aura at window command list, but it's show aura turn OFF at chat window.

**Comment by Lemongrass3110** [comment]
Confirmed on 2017-05-31, but I do not know yet if this is a client or server side issue.

**Comment by hendra814** [comment]
@Lemongrass3110 

I think this is because of KRO udpate this class into base 175 and job 60 with kaegoro dan oboro too
here the link ot news http://ro.gnjoy.com/news/devnote/View.asp?category=3&seq=2956632&curpage=1
![image](https://user-images.githubusercontent.com/9587609/28359991-45b71c48-6c9e-11e7-8da4-0640b0f4529c.png)

**Comment by Lemongrass3110** [comment]
Hmm so actually it should be related to #1692?
We are still missing the EXP table for the new level it seems.

**Comment by Mikegyver** [comment]
@lemongrass.. i think on 3ceam, kagerou & oboro max base & job level are 175/60..

**Comment by mazvi** [comment]
Yes on 2017 client me not showing aura job rebelion.. when rathena increase rebelion to 175?

**Comment by Jeybla** [comment]
Closing this for now. The new max level will be edited in that pull request, when we have the new exp values.
