### ISSUE TITLE
Unit appearance data get replaced

### ISSUE THREAD

**Issue by Yuchinin** [rathena/rathena#2269]
* **rAthena Hash**: d324cd1e255367a8ec3654167b90062e6c07c80f

* **Client Date**: 20170125

* **Server Mode**: Both

* **Description of Issue**: 
  * Result: Old unit appearance data get replace by new data.
  * Expected Result: Since every mob unit got individual mob data, they should keep their own appearance data instead get replace by newest appearance data.
  * How to Reproduce: 
```
izlude,111,126,5	script	unitspritebug	100,{
	if(select("Spawn","Reset")==2){
		for(.@i=0;.@i<getarraysize(.gidlist);.@i++){
			unitkill .gidlist[.@i];
		}
		deletearray .gidlist,getarraysize(.gidlist);
		.count = 0;
		npctalk "Setting Reset!";
		end;
	}
	.count++;
	monster("izlude",111,126,"Unit "+.count,4900,1);	// mobid 4900 is just a dummy mob which I set mob_avail to novice sprite
	.gid = $@mobid;
	arradd(".gidlist",.gid);							// custom function (add .gid into .gidlist array)
	setunitdata .gid,UMOB_HAIRSTYLE,.count;				// set unit hairstyle ascending
	setunitdata .gid,UMOB_HEADTOP,0;					// remove unit hatgear to have better look of hairstyle
	setmobmode(.gid,"remove",4);	//MD_AGGRESSIVE		// custom function (remove mob aggressive mode)
	setmobmode(.gid,"set",32);		//MD_NORANDOM_WALK	// custom function (set mob norandomwalk mode)
	unitwalk .gid,107+.count,123;
	end;
}
```
  * Official Information:-
  

* **Modifications that may affect results**: -
  
  
* **Additional Info**: 
Begin to spawn novice unit with hairstyle 1
![logo](http://i.imgur.com/qhtXLWl.jpg)
First novice unit spawned
![logo](http://i.imgur.com/e8dJMS8.png)
Spawn another novice unit with hairstyle 2
![logo](http://i.imgur.com/ixYQ22s.png)
Do a '@refresh' atcommand
![logo](http://i.imgur.com/SEEr2gQ.png)
The first novice appearance get replace by second novice appearance
![logo](http://i.imgur.com/mDawFMi.png)

**Comment by Lemongrass3110** [comment]
script(taken from yuchiyin and modified so it does not use custom functions):
```
prontera,155,184,5	script	unitspritebug	100,{
	.count++;
	monster("prontera",147+.count,181,"Unit "+.count,4900,1);	// mobid 4900 is just a dummy mob which I set mob_avail to novice sprite
	.gid = $@mobid;
	setunitdata .gid,UMOB_HAIRSTYLE,.count;				// set unit hairstyle ascending
	setunitdata .gid,UMOB_HEADTOP,0;					// remove unit hatgear to have better look of hairstyle
	setunitdata .gid,UMOB_LOOKDIR,DIR_SOUTH;
	end;
}
```
mob_db:
```
4900,PORING,Poring,Poring,1,60,1,27,20,1,8,9,2,5,6,1,1,0,6,5,10,12,1,3,21,0x0,400,1872,672,480,0,0,0,0,0,0,0,909,7000,1202,100,938,400,512,1000,713,1500,512,150,619,20,0,0,0,0,4001,1
```

mob_avail:
```
4900,0
```

The root of the issue is that each spawned monster points to the view data of the mob_db entry and if you modify it for one unit you actually refresh it for all of them. This is no problem for monsters, but only for monsters that are actually player jobs(mob_avail entries).
