### ISSUE TITLE
Deleting a char with an email has no time check

### ISSUE THREAD

**Issue by Tokeiburu** [rathena/rathena#2271]
* **rAthena Hash**: f0aed89

* **Client Date**: 20151029

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: When deleting a character, you have to wait 24 hours by default. After waiting this amount of time, you have to either put in your email or your birthday. The birthday version (chclif_parse_char_delete2_accept) is working fine, the email version (chclif_parse_delchar) has some issues. It doesn't check for the delete_date in the char table. This is a problem when a player changes his local date one day ahead, as he's now able to skip the waiting period entirely.
  * Expected Result: Adjusting the local time on the client-side shouldn't allow you to bypass the deletion timer.
  * How to Reproduce: It's a bit annoying to reproduce on a local test server since changing your time will affect both the server and the client, so you'd need two machines. Simply delete a character, change your local time by a day or two, then go back to the selection screen and attempt to delete the character. After entering the email, it will be deleted.
  * Official Information:
  

* **Modifications that may affect results**: None.

**Comment by Lemongrass3110** [comment]
Looked into this. Both functions should share the basic logic in a common function I guess. Also chclif_parse_delchar could be updated to use the newer answer packet chclif_char_delete2_accept_ack. I tried it and it worked. That way we could deliver correct error messages instead of only being able to reply with "your mail is not correct".

**Comment by Lemongrass3110** [comment]
It's actually easy to reproduce:
1) Mark your character for deletion
2) Log into another character or exit to Windows
3) Remember the date value and set the date to a value in the past in the database
4) Log in with your client and stay in the character selection screen
5) Restore the date value from before
6) The client still thinks the date has been reached -> send a deletion request now
