### ISSUE TITLE
Ontouch cells can overlap

### ISSUE THREAD

**Issue by Tokeiburu** [rathena/rathena#2274]
* **rAthena Hash**: f0aed89

* **Client Date**: Any

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: It is currently not possible to have overlapping ontouch zones.
  * Expected Result:
  * How to Reproduce: Simply make two NPCs with an OnTouch zone that overlaps.
  * Official Information: These are Rock Ridge NPCs on kRO (I've also seen this from the Sarah and Fenrir instance with the Gargoyles):
![ontouch1](https://user-images.githubusercontent.com/8761658/28430345-2f5aaaa4-6d4e-11e7-9248-7c43b4bfc915.png)
![ontouch2](https://user-images.githubusercontent.com/8761658/28430346-310efe36-6d4e-11e7-80cf-e3a128cfed01.png)
![ontouch3](https://user-images.githubusercontent.com/8761658/28430348-3233c814-6d4e-11e7-92f5-b938fb6bbe13.png)
![ontouch4](https://user-images.githubusercontent.com/8761658/28430350-33149b50-6d4e-11e7-9d11-b6943e7deba9.png)

From the last picture, walking from...
Black to yellow: triggers the yellow NPC.
Black to red: triggers the red NPC.
Black to orange: triggers both NPCs.
Orange to yellow: triggers none.
Orange to red: triggers none.
Red to orange: triggers the yellow NPC.
Yellow to orange: triggers the red NPC.
  

* **Modifications that may affect results**:

**Comment by Atemo** [comment]
I made some test on aegis too, related to issue https://github.com/rathena/rathena/issues/1939#issuecomment-283819431
