### ISSUE TITLE
Issue on hunting mission

### ISSUE THREAD

**Issue by madarao16** [rathena/rathena#2276]
* **rAthena Hash**: 9827bf6

* **Client Date**: 2015/11/04

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result:  Sometimes, the monster kill won't count. On random players and newly refreshed ones. After the delay time, when retaking the mission, kills won't count.
  * Expected Result:  It's suppose to count the kill every time the timer on delay refreshes.
  * How to Reproduce:  Just try and put the timer anywhere within an hour.
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by kukuasir1** [comment]
I have the same problem!

**Comment by Atemo** [comment]
Any error on mapserv after 9d6b3d06a9d75345d6802087d587a4521a1c3fae ?
