### ISSUE TITLE
Warning compile cmd2 

### ISSUE THREAD

**Issue by Valorro** [rathena/rathena#2286]
* **rAthena Hash**: 97f989f

* **Client Date**: 20151104

* **Server Mode**: Renewal
enabled PACKET_OBFUSCATION, use custom keys and client diffed nemo. 

* **Description of Issue**: 'cmd2' and 'type' may be use uninitialized in function
  * Result:  warning compile in clif.c after applying Overhaul #2263 
warning complie in intif.c after applying Rodex #2186 
![warning](https://user-images.githubusercontent.com/29807950/28600263-20495af6-71db-11e7-94ca-7163cda5eaa5.png)

  * Expected Result:  
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**: the source part related to PACKET_OBFUSCATION, does change `cmd2` into `cmd` fix it?
also on rodex, does commenting `enum mail_inbox_type type;` will give another problem?

**Comment by secretdataz** [comment]
Are you sure this is not caused by your bad merge? Build 4990 as of today doesn't have the warning emitted.

**Comment by Valorro** [comment]
im gonna re-check it... re-merge

**Comment by Lemongrass3110** [comment]
Can't reproduce the cmd2 one, but i'll fix up the RODEX related ones.
