### ISSUE TITLE
Item Bullet, silver bullet and bloody shell problem

### ISSUE THREAD

**Issue by hendra814** [rathena/rathena#2289]
* **rAthena Hash**: lastest

* **Client Date**: 2017-06-14

* **Server Mode**: Renewal

* **Description of Issue**:  Rebellion Job can't equip bullet, silver bullet, and bloody shell amunition
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**: 
  
  

here ss result
![screenrathena011](https://user-images.githubusercontent.com/9587609/28607074-5a05a816-7204-11e7-81d0-6d13cec99b8d.jpg)
![screenrathena012](https://user-images.githubusercontent.com/9587609/28607075-5a0a07a8-7204-11e7-973a-73e20777a38c.jpg)
![screenrathena013](https://user-images.githubusercontent.com/9587609/28607076-5a1a741c-7204-11e7-9215-47939b679931.jpg)

**Comment by aleos89** [comment]
What action are you doing to equip the bullets? You should be able to drag and drop them onto the equipment window.

**Comment by hendra814** [comment]
I already tried with drag and drop, but same with put in the shortcut key it's not working

**Comment by aleos89** [comment]
Do you get any warnings or messages from the client as to why you can't equip them?

**Comment by hendra814** [comment]
yes it show "can't equip this item because you don't meet the requirements"

**Comment by aleos89** [comment]
This is from the source:
```c
		/** Failing condition:
		 * 1. Always failed to equip ammo if no weapon equipped yet
		 * 2. Grenade only can be equipped if weapon is Grenade Launcher
		 * 3. Bullet cannot be equipped if the weapon is Grenade Launcher
		 * (4. The rest is relying on item job/class restriction).
		 **/
```
You're wearing a grenade launcher (Southern Cross) so you are unable to equip bullets.

**Comment by hendra814** [comment]
@aleos89 
i don't know gunslinger job had fail condition like this.
even when i'm equip sphere bullet i can't change weapon into revolver.
but thanks for this information. is there any documentation for other job like this, where can i found it?

**Comment by aleos89** [comment]
Not sure about documentation, but it's in `pc.c::pc_equipitem`.
