### ISSUE TITLE
Compile Failure

### ISSUE THREAD

**Issue by keitenai** [rathena/rathena#2294]
* **rAthena Hash**: fdbdcb2
* **Client Date**: Any
* **Server Mode**: Renewal

* **Description of Issue**: 
These Lines of errors appear when trying to compile the latest git. Till it fails.
I'm using VS2017

> 7>yaml-cpp.lib(parse.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in common.lib(yamlwrapper.obj)
7>yaml-cpp.lib(parse.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MT_StaticRelease' in common.lib(yamlwrapper.obj)
7>yaml-cpp.lib(exceptions.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in common.lib(yamlwrapper.obj)
7>yaml-cpp.lib(exceptions.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MT_StaticRelease' in common.lib(yamlwrapper.obj)
7>yaml-cpp.lib(convert.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in common.lib(yamlwrapper.obj)
7>yaml-cpp.lib(convert.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MT_StaticRelease' in common.lib(yamlwrapper.obj)
7>yaml-cpp.lib(memory.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in common.lib(yamlwrapper.obj)
7>yaml-cpp.lib(memory.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MT_StaticRelease' in common.lib(yamlwrapper.obj)
7>yaml-cpp.lib(node_data.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in common.lib(yamlwrapper.obj)
7>yaml-cpp.lib(node_data.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MT_StaticRelease' in common.lib(yamlwrapper.obj)
7>yaml-cpp.lib(nodebuilder.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in common.lib(yamlwrapper.obj)
7>yaml-cpp.lib(nodebuilder.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MT_StaticRelease' in common.lib(yamlwrapper.obj)
7>yaml-cpp.lib(parser.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in common.lib(yamlwrapper.obj)
7>yaml-cpp.lib(parser.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MT_StaticRelease' in common.lib(yamlwrapper.obj)
7>yaml-cpp.lib(singledocparser.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in common.lib(yamlwrapper.obj)
7>yaml-cpp.lib(singledocparser.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MT_StaticRelease' in common.lib(yamlwrapper.obj)
7>yaml-cpp.lib(scanner.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in common.lib(yamlwrapper.obj)
7>yaml-cpp.lib(scanner.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MT_StaticRelease' in common.lib(yamlwrapper.obj)
7>yaml-cpp.lib(directives.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in common.lib(yamlwrapper.obj)
7>yaml-cpp.lib(directives.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MT_StaticRelease' in common.lib(yamlwrapper.obj)
7>yaml-cpp.lib(tag.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in common.lib(yamlwrapper.obj)
7>yaml-cpp.lib(tag.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MT_StaticRelease' in common.lib(yamlwrapper.obj)
7>yaml-cpp.lib(null.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in common.lib(yamlwrapper.obj)
7>yaml-cpp.lib(null.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MT_StaticRelease' in common.lib(yamlwrapper.obj)
7>yaml-cpp.lib(regex_yaml.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in common.lib(yamlwrapper.obj)
7>yaml-cpp.lib(regex_yaml.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MT_StaticRelease' in common.lib(yamlwrapper.obj)
7>yaml-cpp.lib(scantoken.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in common.lib(yamlwrapper.obj)
7>yaml-cpp.lib(scantoken.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MT_StaticRelease' in common.lib(yamlwrapper.obj)
7>yaml-cpp.lib(simplekey.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in common.lib(yamlwrapper.obj)
7>yaml-cpp.lib(simplekey.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MT_StaticRelease' in common.lib(yamlwrapper.obj)
7>yaml-cpp.lib(stream.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in common.lib(yamlwrapper.obj)
7>yaml-cpp.lib(stream.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MT_StaticRelease' in common.lib(yamlwrapper.obj)
7>yaml-cpp.lib(scanscalar.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in common.lib(yamlwrapper.obj)
7>yaml-cpp.lib(scanscalar.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MT_StaticRelease' in common.lib(yamlwrapper.obj)
7>yaml-cpp.lib(scantag.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in common.lib(yamlwrapper.obj)
7>yaml-cpp.lib(scantag.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MT_StaticRelease' in common.lib(yamlwrapper.obj)
7>yaml-cpp.lib(exp.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in common.lib(yamlwrapper.obj)
7>yaml-cpp.lib(exp.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MT_StaticRelease' in common.lib(yamlwrapper.obj)
7>libcpmtd.lib(stdthrow.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in common.lib(yamlwrapper.obj)
7>libcpmtd.lib(stdthrow.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MT_StaticRelease' in common.lib(yamlwrapper.obj)
7>achievement.obj : error LNK2001: unresolved external symbol _yaml_as_int
7>yaml-cpp.lib(parse.obj) : error LNK2001: unresolved external symbol __calloc_dbg
7>yaml-cpp.lib(parse.obj) : error LNK2001: unresolved external symbol __malloc_dbg
7>yaml-cpp.lib(parse.obj) : error LNK2001: unresolved external symbol __CrtDbgReportW
7>libcpmtd.lib(stdthrow.obj) : error LNK2001: unresolved external symbol __CrtDbgReportW
7>yaml-cpp.lib(parse.obj) : error LNK2001: unresolved external symbol __free_dbg
7>C:\rAthena\map-server.exe : fatal error LNK1120: 5 unresolved externals
7>Done building project "map-server.vcxproj" -- FAILED.

//======================================================

UPDATE:
I test it on Centos and this is the errors that im getting till it Fails.

> src/ostream_wrapper.cpp: In member function 'void YAML::ostream_wrapper::write(con                                                 st string&)':
src/ostream_wrapper.cpp:21:51: warning: declaration of 'str' shadows a member of '                                                 this' [-Wshadow]
 void ostream_wrapper::write(const std::string& str) {
                                                   ^
src/ostream_wrapper.cpp: In member function 'void YAML::ostream_wrapper::write(con                                                 st char*, std::size_t)':
src/ostream_wrapper.cpp:34:62: warning: declaration of 'str' shadows a member of '                                                 this' [-Wshadow]
 void ostream_wrapper::write(const char* str, std::size_t size) {
                                                              ^
        CXX     src/contrib/graphbuilderadapter.cpp
In file included from src/contrib/graphbuilderadapter.cpp:1:0:
src/contrib/graphbuilderadapter.h:16:43: fatal error: yaml-cpp/contrib/graphbuilde                                                 r.h: No such file or directory
 #include "yaml-cpp/contrib/graphbuilder.h"
                                           ^
compilation terminated.
make[1]: *** [obj/src/contrib/graphbuilderadapter.o] Error 1
make[1]: Leaving directory `/home/trunk/rathena/3rdparty/yaml-cpp'
make: *** [yaml-cpp] Error 2

**Comment by Lemongrass3110** [comment]
For your visual studio problem:
Make sure to clean and build the whole solution. 
@admkakaroto had a similar issue. Maybe he can help you. If nothing helps: try to delete the hidden ".vs" directory in your rathena directory.

As for centos:
This totally has to be a problem on your end, because the file it says that it is missing is there on master. 
https://github.com/rathena/rathena/blob/master/3rdparty/yaml-cpp/include/yaml-cpp/contrib/graphbuilder.h

**Comment by keitenai** [comment]
I just install yaml-cpp-devel on centos 7, now i'm getting this errors till it fails.


> In file included from include/yaml-cpp/node/detail/node.h:14:0,
                 from src/nodeevents.cpp:4:
/usr/include/yaml-cpp/node/detail/node_ref.h: In member function 'YAML::detail::node& YAML::detail::node_ref::get(YAML::detail::node&, YAML::detail::shared_memory_holder) const':
/usr/include/yaml-cpp/node/detail/node_ref.h:55:126: error: invalid initialization of non-const reference of type 'YAML::detail::node&' from an rvalue of type 'YAML::detail::node*'
    node& get(node& key, shared_memory_holder pMemory) const { return static_cast<const node_data&>(*m_pData).get(key, pMemory); }
                                                                                                                              ^
In file included from src/nodeevents.cpp:4:0:
include/yaml-cpp/node/detail/node.h: In member function 'const YAML::Mark& YAML::detail::node::mark() const':
include/yaml-cpp/node/detail/node.h:29:45: error: 'class YAML::detail::node_ref' has no member named 'mark'
   const Mark& mark() const { return m_pRef->mark(); }
                                             ^
include/yaml-cpp/node/detail/node.h: In member function 'YAML::EmitterStyle::value YAML::detail::node::style() const':
include/yaml-cpp/node/detail/node.h:34:54: error: 'class YAML::detail::node_ref' has no member named 'style'
   EmitterStyle::value style() const { return m_pRef->style(); }
                                                      ^
include/yaml-cpp/node/detail/node.h: In member function 'void YAML::detail::node::set_mark(const YAML::Mark&)':
include/yaml-cpp/node/detail/node.h:69:35: warning: declaration of 'mark' shadows a member of 'this' [-Wshadow]
   void set_mark(const Mark& mark) { m_pRef->set_mark(mark); }
                                   ^
include/yaml-cpp/node/detail/node.h:69:45: error: 'class YAML::detail::node_ref' has no member named 'set_mark'
   void set_mark(const Mark& mark) { m_pRef->set_mark(mark); }
                                             ^
include/yaml-cpp/node/detail/node.h: In member function 'void YAML::detail::node::set_type(YAML::NodeType::value)':
include/yaml-cpp/node/detail/node.h:71:39: warning: declaration of 'type' shadows a member of 'this' [-Wshadow]
   void set_type(NodeType::value type) {
                                       ^
include/yaml-cpp/node/detail/node.h: In member function 'void YAML::detail::node::set_scalar(const string&)':
include/yaml-cpp/node/detail/node.h:80:46: warning: declaration of 'scalar' shadows a member of 'this' [-Wshadow]
   void set_scalar(const std::string& scalar) {
                                              ^
include/yaml-cpp/node/detail/node.h: In member function 'void YAML::detail::node::set_tag(const string&)':
include/yaml-cpp/node/detail/node.h:84:40: warning: declaration of 'tag' shadows a member of 'this' [-Wshadow]
   void set_tag(const std::string& tag) {
                                        ^
include/yaml-cpp/node/detail/node.h: In member function 'void YAML::detail::node::set_style(YAML::EmitterStyle::value)':
include/yaml-cpp/node/detail/node.h:90:45: warning: declaration of 'style' shadows a member of 'this' [-Wshadow]
   void set_style(EmitterStyle::value style) {
                                             ^
include/yaml-cpp/node/detail/node.h:92:13: error: 'class YAML::detail::node_ref' has no member named 'set_style'
     m_pRef->set_style(style);
             ^
include/yaml-cpp/node/detail/node.h: In member function 'YAML::detail::node* YAML::detail::node::get(YAML::detail::node&, YAML::detail::shared_memory_holder) const':
include/yaml-cpp/node/detail/node.h:142:66: error: cannot convert 'YAML::detail::node' to 'YAML::detail::node*' in return
     return static_cast<const node_ref&>(*m_pRef).get(key, pMemory);
                                                                  ^
include/yaml-cpp/node/detail/node.h: In member function 'YAML::EmitterStyle::value YAML::detail::node::style() const':
include/yaml-cpp/node/detail/node.h:34:63: warning: control reaches end of non-void function [-Wreturn-type]
   EmitterStyle::value style() const { return m_pRef->style(); }

**Comment by secretdataz** [comment]
We already provided our version of yaml-cpp library that has some bug fixes applied. You don't have to install an additional package.

**Comment by keitenai** [comment]
how to install the included yaml-cpp?

**Comment by secretdataz** [comment]
It is already included in the project

**Comment by keitenai** [comment]
i was getting this errors before I install yaml-cpp-devel : 

>        MKDIR   obj/src/contrib
        CXX     src/tag.cpp
        CXX     src/node.cpp
        CXX     src/ostream_wrapper.cpp
src/ostream_wrapper.cpp: In member function 'void YAML::ostream_wrapper::write(const string&)':
src/ostream_wrapper.cpp:21:51: warning: declaration of 'str' shadows a member of 'this' [-Wshadow]
 void ostream_wrapper::write(const std::string& str) {
                                                   ^
src/ostream_wrapper.cpp: In member function 'void YAML::ostream_wrapper::write(const char*, std::size_t)':
src/ostream_wrapper.cpp:34:62: warning: declaration of 'str' shadows a member of 'this' [-Wshadow]
 void ostream_wrapper::write(const char* str, std::size_t size) {
                                                              ^
        CXX     src/contrib/graphbuilderadapter.cpp
In file included from src/contrib/graphbuilderadapter.cpp:1:0:
src/contrib/graphbuilderadapter.h:16:43: fatal error: yaml-cpp/contrib/graphbuilder.h: No such file or directory
 #include "yaml-cpp/contrib/graphbuilder.h"
                                           ^
compilation terminated.
make[1]: *** [obj/src/contrib/graphbuilderadapter.o] Error 1

**Comment by keitenai** [comment]
I finally understand what's causing this issue!

"graphbuilder.h" is not included when i checkout a fresh clean copy from github.
