### ISSUE TITLE
yamlwrapper.cpp line 78 size 45 address

### ISSUE THREAD

**Issue by sader1992** [rathena/rathena#2298]
i don't have the git hash it's from 24 July
no errors just for reporting cuz i don't know if there is error or not :p

 
![screenshot from 2017-07-30 00-32-17](https://user-images.githubusercontent.com/5981261/28749199-af86a76e-74bf-11e7-8a97-c6486cd3984f.png)
![screenshot from 2017-07-30 00-32-58](https://user-images.githubusercontent.com/5981261/28749197-af8300fa-74bf-11e7-91e3-15eca22cfadd.png)
![screenshot from 2017-07-30 00-33-28](https://user-images.githubusercontent.com/5981261/28749198-af859162-74bf-11e7-8b62-f1f07dbdc121.png)
 this happen after stoping the server

**Comment by Lemongrass3110** [comment]
Was this when the feature was still resting in a pull request? We fixed something similar at the end before merging it to master.

**Comment by sader1992** [comment]
test the last rathena no more from this lines thanks
![screenshot from 2017-07-30 04-32-34](https://user-images.githubusercontent.com/5981261/28750145-a7c2ede6-74e0-11e7-96cd-9cb0927a0ff6.png)
