### ISSUE TITLE
Homunculus do not walk onto the same cell with #cellnostack turned off.

### ISSUE THREAD

**Issue by dragonis1701** [rathena/rathena#2299]
Similar to #1950, Homunculus will not walk onto cells that the master is already on, even with cellnostack turned off. Having Homunculus walk onto the same cell, with cellnostack disabled, will also fix #1950.

**Comment by Lemongrass3110** [comment]
This is a clientside limitation. The client(probably because of the AI code) will not send a walk-request to the server. So we cannot fix this issue.
