### ISSUE TITLE
about Round Trip 

### ISSUE THREAD

**Issue by iubantot** [rathena/rathena#2301]
* **rAthena Hash**: fdbdcb266

* **Client Date**: 2016-12-28Re

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Round trip not affected by Long range modifiers 
  * Expected Result: to be affected by long range modifiers
  * How to Reproduce: 
  * Official Information:https://forums.warpportal.com/index.php?/topic/189968-rebellion-skill-formulas-updated-1216/
  

* **Modifications that may affect results**: none

**Comment by aleos89** [comment]
Are you using #1692?

**Comment by iubantot** [comment]
oh i see its already on the process thank you! will test the PR soon thank you!

**Comment by aleos89** [comment]
Closing as this is addressed in the PR linked above.
