### ISSUE TITLE
atcommand reloadmobdb does not reload whodrops on custom mob_drop

### ISSUE THREAD

**Issue by uddevil** [rathena/rathena#2304]
* **rAthena Hash**: 1e71d50cb4903235bdff707c4f17fc683d6ec3ef

* **Client Date**: 2015-11-04aRagexe

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: 
Changing rates for custom drop on db/import/mob_drop.txt, and reload using ``` `@reloadmobdb` ``` does not reload information on ``` `@whodrops` ``` (it appends).
  * Expected Result: 
Information on ``` `@whodrops` ``` should not be appended, instead it should be changed to latest rate update
  * How to Reproduce: 
1. Add custom mob drop on db/import/mob_drop.txt for example, Valkyrie Shield (2115) at 15% rate on Mummy (1041)
`1041,2115,1500,RDMOPTG_None`
2. Reload using ``` `@reloadmobdb` ```
3. Using ``` `@whodrops` ``` 2115, Valkyrie Shield will be shown drops from Mummy at 15% rate
4. Change rates to for example 50%
`1041,2115,5000,RDMOPTG_None`
5. Reload using ``` `@reloadmobdb` ```
6. Using ``` `@whodrops` ``` 2115, Valkyrie Shield will be shown twice on Mummy at 15% and 50% rate
7. Should it be only once? (last rate update only)
8. Using ``` `@mi` ``` will show that only 1 Valkyrie Shield drops from Mummy at 50% rate (correct).

_Sorry for my bad english._

  * Official Information:
  

* **Modifications that may affect results**:

**Comment by anacondaqq** [comment]
Can confirm.
