### ISSUE TITLE
Warning Compilation

### ISSUE THREAD

**Issue by VXPlay** [rathena/rathena#2306]
* **rAthena Hash**: 4c62f58

* **Client Date**: 20151104

* **Server Mode**: PRE-RE

* **Description of Issue**:  Lots of warnings during compilation.
  * Result: I am using CentOS 7 and when compiling I have many warnings.
  * Expected Result: A clean compilation.
  * How to Reproduce: I set up the machine and installed everything I needed to run the emulator.
  

* **Modifications that may affect results**: I did not make any changes to the emulator, just downloaded it and started compiling it.
![screenshot_1](https://user-images.githubusercontent.com/17849495/28885288-bf830b2a-778b-11e7-8bbd-1773038cba25.png)

**Comment by vstumpf** [comment]
What version of g++ are you using?

When was the last time you ran `./configure`?

**Comment by VXPlay** [comment]
I'm using version 4.8.5
I use ./configure every time before starting a build.

print: http://prntscr.com/g3l9ic

**Comment by vstumpf** [comment]
Since the achievement update, you need to use at least version 5.

**Comment by VXPlay** [comment]
I will update here for version 5 and see if it will resolve.

**Comment by Lemongrass3110** [comment]
As @vstumpf already mentioned correctly gcc 5 is not required. If you do not have it you might have compiler warnings or even errors in the near future.

**Comment by VXPlay** [comment]
Thank's!
