### ISSUE TITLE
BG Flavius: Crystals can be attacked at any time

### ISSUE THREAD

**Issue by raynra** [rathena/rathena#231]
Git Hash/Date: 4d5fc9604cea533f7d927dd41526bbbad3c800b2 / Dec-17-2014
Client Date: 2013-08-07a
Description: 

http://irowiki.org/wiki/Battlegrounds#Flavius
The Crystals should not be attackable until the Crystal Guardians are killed.
Currently, this is not the case.

How to reproduce:

In BG Flavius 1 or 2, do not kill Crystal Guardians. You can attack Crystal using ranged physical (arrows, bullets, etc). Sometimes, if positioned correctly, you can use melee attacks. Sometimes, skills would also hit the Crystal which leads to it being able to be attacked using melee.

**Comment by emistry** [comment]
hmm ?? custom script ?? or you refer the Battleground script in the npc/custom/ folder ??

**Comment by raynra** [comment]
Sorry for the confusion.
I am using official BG scripts in npc/battlegrounds folder.
Flavius scripts are in
npc/battleground/flavius/flavius01.txt
npc/battleground/flavius/flavius02.txt

**Comment by cydh** [comment]
interesting, this diff able to set a mob cannot be attacked `mobimmuneattack`. https://www.dropbox.com/s/c35001f8985yju7/script_mobimmuneattack.diff?dl=0
and try apply this this for Flavius script, only for 01 now (not tested) https://gist.github.com/cydh/0cf95ee68bcea1aff94f
but I tested that new script command with this simple script https://gist.github.com/cydh/63816a2e6441f918a32a

**Comment by raynra** [comment]
mobimmuneattack command and script changes are good.
Found unrelated Flavius bugs, but will submit fixes to those at a later time +1:

**Comment by linkineox** [comment]
anybody test royal guard's reflect damage with crystal? 

the dmg is not reduced to 1.

**Comment by cydh** [comment]
@linkineox I hate to say, but don't mix a issue with other issue. open new issue, please

**Comment by Luciar** [comment]
What is the status of this report? Is it confirmed to be a variation from the official sources?

**Comment by raynra** [comment]
I'm fairly certain that the Crystals aren't supposed to be attackable unless the Guardians are destroyed. I'm using Cydh's patches, and they are working well.

**Comment by aleos89** [comment]
I would agree that it doesn't seem right that the crystal can be taken prior to defeating the guardians. I know iROWiki isn't always a direct source to go straight for, but their battlegrounds page does state that they should be defeated first as well: http://irowiki.org/wiki/Battlegrounds#Flavius
