### ISSUE TITLE
Taekwondo Flying KIck not working

### ISSUE THREAD

**Issue by keitenai** [rathena/rathena#2312]
* **rAthena Hash**:  93cf197
* **Client Date**:  20170517
* **Server Mode**:  Renewal (haven't tested on Pre-Re)

* **Description of Issue**: 
     Skill Flying kick will only show "Skill has failed" message. But no error / warning on console.

**Comment by secretdataz** [comment]
Do you have CELL_NOSTACK enabled?

**Comment by keitenai** [comment]
@secretdataz  yes #define CELL_NOSTACK enabled

**Comment by secretdataz** [comment]
It should have something to do with CELL_NOSTACK as this skill place the user in the same cell with the target.

**Comment by keitenai** [comment]
my misc.conf setting is:
official_cell_stack_limit: 3
custom_cell_stack_limit: 3

**Comment by Playtester** [comment]
If you just want the official no cell stacking, as in, the character will move to the closest free cell, then you can disable CELL_NOSTACK as that's only needed for the custom feature that makes players act like walls.

**Comment by keitenai** [comment]
yeah, i guess better to disable CELL_NOSTACK thanks.
