### ISSUE TITLE
Malangdo Coin Exchanger

### ISSUE THREAD

**Issue by RadianFord** [rathena/rathena#232]
1. Coin Exchanger CX-1
2. Special Vending Machine
3. Dark Machine TX100

Every time I talk to the 3 npc above. Im stack with the first message..

for example Coin Exchanger CX-1 you will be stack on this message.. the same with the other two npc..

	mes "[Coin Exchanger CX-1]";
	mes "Welcome to CX-1. If you have coins, you can exchange them to high or low grade coins.";

can be found at .../.../re/merchants/coin_exchange.txt

**Comment by cydh** [comment]
stack or stuck?

**Comment by Skormie** [comment]
The problem with += was fixed right?

**Comment by RadianFord** [comment]
@cydh Stuck Im sorry.. xD

@Skormie hmm just like this one?
.@menu$ += getitemname(.@coins[.@i])+":";

**Comment by Skormie** [comment]
Based on Cydh's post which I think he may of made in the wrong section... It hasn't yet... Damn I knew I should've change it when I had the chance... Bleh.

**Comment by cydh** [comment]
lol wrong issue to comment

> somehow, `+=` for a string in iteration is fail. /hmm
> temp fix is `.@foo$ = .@foo$+"bar";`
