### ISSUE TITLE
Mob Sprite changes when using @reloadmobdb

### ISSUE THREAD

**Issue by karlseven** [rathena/rathena#2326]
I have a floating rates by Stolao, it was working before until i updated today. whenever the @reloadmobdb is fired mob changes to another mob, ex kobol will change to another mob same as drop.

* **Client Date**: 
2015-11-04aRagexe

* **rAthena Hash**: 
ac1cf04

* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result: Mob Changes when you use @reloadmobdb (ex. Pupa turned into Alarm) 
  * Expected Result : Should not change any mobs appearance or drop just reload their data
  * How to Reproduce: Just Type@reloadmobdb while in a field some monster will change

**Comment by aleos89** [comment]
Can you please provide us with the information that is in the template that you removed when creating this issue.

**Comment by karlseven** [comment]
sorry, updated.

**Comment by Jeybla** [comment]
I can confirm this issue on a clean clone ( ac1cf04 ).

**Comment by Lemongrass3110** [comment]
Confirmed that I broke it as well.
