### ISSUE TITLE
VIP Status for Expire date and Time left buggy

### ISSUE THREAD

**Issue by hendra814** [rathena/rathena#2328]
* **rAthena Hash**: lastest

* **Client Date**: 20170614

* **Server Mode**: Renewal

* **Description of Issue**: Can't understand for Expire date and time left for VIP Status, please see the SS
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**: 
  
  

![image](https://user-images.githubusercontent.com/9587609/29154511-4bd60fb2-7dbf-11e7-91c6-5677fc3098e2.png)

i hope could show like this
![image](https://user-images.githubusercontent.com/9587609/29154555-782da6a6-7dbf-11e7-9816-5096690ed5b6.png)

**Comment by playpsro** [comment]
And then, if VIP Time is expired . I've suggest to make user automatically disconnect for make sure they will back to normal account.

**Comment by aleos89** [comment]
Could you please provide a valid hash?

The script command `vip_status` was changed in #2184. Seems we overlooked the script command that allows for users to convert it back to a readable format.

@playpsro there's no need as we remove all the VIP effects without having to kick the player.

**Comment by hendra814** [comment]
@aleos89

Sorry but it's not solve the problem, here my screen shoot after lastest update
![screenrathena025](https://user-images.githubusercontent.com/9587609/29300162-0534ba3a-819e-11e7-93fb-1df96e2db6e5.jpg)

**Comment by Akkarinage** [comment]
@hendra814 can you paste your script that displays the dispbottom values please?

**Comment by hendra814** [comment]
[accountsystem.txt](https://github.com/rathena/rathena/files/1224095/accountsystem.txt)

**Comment by secretdataz** [comment]
Your script won't magically display formatted time. You can use the newly adjusted `gettimestr` script command to convert a timestamp to a human-readable string.

**Comment by hendra814** [comment]
@secretdataz,

ok i'll try to put it in my other script like sampe in the doc script_command

**Comment by Jeybla** [comment]
You could use `Time2Str` from `npc/other/Global_Functions.txt`
```C
//////////////////////////////////////////////////////////////////////////////////
// Returns time remaining in a readable format.
// The argument is subtracted from UNIX epoch time, or 'gettimetick(2)'.
// -- callfunc "Time2Str",<tick in UNIX epoch time>
// Example:
//    // Displays "Time left: 1 day, 1 hour, 8 minutes, 20 seconds"
//    set .@Timer, gettimetick(2) + 90500;
//    mes "Time left: " + callfunc("Time2Str",.@Timer);
//////////////////////////////////////////////////////////////////////////////////
```
Anyway please ask in the forums for those questions. Thank you.
