### ISSUE TITLE
Memory Leak on Char Server in strlib.c

### ISSUE THREAD

**Issue by Morjador** [rathena/rathena#2330]
* **rAthena Hash**: dce6ff1beac4ebb426b2578296e49dddb49767d8

* **Client Date**: 2015-11-04aRagexe

* **Server Mode**: Renewal

* **Description of Issue**: After Setting up a new Server, playing online a bit and shutting down the charserv the following message appears:
  * Result:
Memory manager: Memory leaks found at 2017/08/12 09h04m45s (Revision ).
0001 : strlib.c line 1083 size 1025 address 0x01C51D34
0002 : strlib.c line 1083 size 1025 address 0x01C52154
0003 : strlib.c line 1083 size 1025 address 0x01C52574
![error](https://user-images.githubusercontent.com/30948637/29238939-bb3d455a-7f40-11e7-84cc-1ac8cd3fee0e.PNG)
![error2](https://user-images.githubusercontent.com/30948637/29238946-0d4f42bc-7f41-11e7-8b04-ebf12fd3c049.PNG)

  * Expected Result: No Memory Leaks
  * How to Reproduce: Download the latest git and set up a completely fresh server

  

* **Modifications that may affect results**: None

**Comment by Everade** [comment]
Confirmed

**Comment by Litro** [comment]
confirmed it too in pre-renewal server mode
