### ISSUE TITLE
VIP - Additional Character Slots behaviour

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#2333]
* **rAthena Hash**: 
6b18ea5

* **Client Date**: 
2016-02-03aRagexeRE

* **Server Mode**: 
Renewal

* **Description of Issue**: 
Lets assume you have 1 month of VIP time.
During this period, you use up all of your character slots, INCLUDING the VIP slots.

Once the VIP time runs out, and you delete a NORMAL character slot!
You can NOT create a new character on that NORMAL character slot.

You would have to delete enough characters first (however regardless of which slot) before you can create new ones again.

  * Result:
Character Creation Denied.

  * Expected Result:
I'm able to use all normal slots regardless of whether i have used up my vip slots or not.

  * How to Reproduce:
VIP time active
At least 1 Character VIP slot required
Let 1 normal character slot free (use up all the others) but use up the vip slot instead

  * Official Information:
Sadly i have no idea how it officialy works

* **Modifications that may affect results**: 
None

* **Additional Thoughts**: 
I'm really not sure what's the best solution here.
Maybe you want to have it like this, so players need to re-purchase vip time.

But the problem here is that:
Players do not understand what's going on, and i have to admit it's extremly confusing if you approach this issue at first glance.

The default error message says zero to nothing (Character creation denied) although i guess we could modify that.
And the actual cause of the problem is hard to catch.

Would be great to hear your own thoughts about this.

**Sidenote:**
If it stays this way. The User Interface showing VIP SLOTS is as useless as it gets.
Because there's no actual use for it then other than promoting a VIP feature.

**Comment by Lemongrass3110** [comment]
Screens from euRO:
![01](https://user-images.githubusercontent.com/3517879/29360257-67882872-8282-11e7-9d4b-f72fd812dcdf.PNG)
![02](https://user-images.githubusercontent.com/3517879/29360261-6f11712a-8282-11e7-89fa-8c014aefe0f4.PNG)
![03](https://user-images.githubusercontent.com/3517879/29360265-71fa166c-8282-11e7-9c2f-522e70696fce.PNG)
