### ISSUE TITLE
Map Crash When Using Custom Battlegrounds

### ISSUE THREAD

**Issue by ClayJensen** [rathena/rathena#2334]
* **rAthena Hash**: fcc4936

* **Client Date**: 2015-11-04aRagexe

* **Server Mode**: Renewal

* **Description of Issue**: Tried to use the bg_pvp in custom/battleground folder and after the two teams was fulfilled by players, the map server crashed when the last player enters the npc pub.
  * Result: Map Crash after entering last player in the npc pub.

  * Expected Result: Will be warped to bg and start the battle.

  * How to Reproduce: Add the bg_pvp.txt in athena_custom.conf and enter players in npc waiting room. After the last player enters, the map server will crash.

  * Official Information:
  

* **Modifications that may affect results**: Tested in clean fcc4936 git hash. No modification made.

**Comment by Akkarinage** [comment]
A crash message/core dump would be helpful..

**Comment by Atemo** [comment]
mapserver seems to crash with `delwaitingroom` when there is player inside the waitingroom

**Comment by Atemo** [comment]
Test scripts:

1. Crash
```
prontera,158,178,5	script	Test delwaitingroom	734,{
	end;
OnInit:
	waitingroom "Blue Team", 2, "Test delwaitingroom::OnStart1", 1;
	end;
OnStart:
	delwaitingroom;
	end;
}
```

2. Don't crash
```
prontera,158,178,5	script	Test delwaitingroom	734,{
	end;
OnInit:
	waitingroom "Blue Team", 2, "Test delwaitingroom::OnStart1", 1;
	end;
OnStart:
	sleep 10;
	delwaitingroom;
	end;
}
```
