### ISSUE TITLE
Map Crash stdio.h

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#2336]
* **rAthena Hash**: 
6b18ea5

* **Client Date**: 
2016-02-03aRagexeRE

* **Server Mode**: 
Renewal

* **Description of Issue**: 
stdio.h line 1438
`>        int const _Result = __stdio_common_vsprintf(`

  * Exception Unhandled
`Unhandled exception thrown: read access violation.
**it** was 0x8. occurred`

  * Autos:
`		Name:_Result	Value: -858993460	Type:const int`

  * Call Stack
` 	map-server.exe!common_strnlen_c<0,unsigned char>(const unsigned char * const string, const unsigned int maximum_count) Line 72	C++
 	map-server.exe!common_strnlen_simd<0,0,unsigned char>(const unsigned char * const string, const unsigned int maximum_count) Line 130	C++
 	map-server.exe!common_strnlen<0,unsigned char>(const unsigned char * const string, const unsigned int maximum_count) Line 189	C++
 	map-server.exe!strnlen(const char * string, unsigned int maximum_count) Line 201	C++
 	map-server.exe!__crt_stdio_output::output_processor<char,__crt_stdio_output::string_output_adapter<char>,__crt_stdio_output::standard_base<char,__crt_stdio_output::string_output_adapter<char> > >::type_case_s_compute_narrow_string_length(const int maximum_length, char __formal) Line 2286	C++
 	map-server.exe!__crt_stdio_output::output_processor<char,__crt_stdio_output::string_output_adapter<char>,__crt_stdio_output::standard_base<char,__crt_stdio_output::string_output_adapter<char> > >::type_case_s() Line 2273	C++
 	map-server.exe!__crt_stdio_output::output_processor<char,__crt_stdio_output::string_output_adapter<char>,__crt_stdio_output::standard_base<char,__crt_stdio_output::string_output_adapter<char> > >::state_case_type() Line 2017	C++
 	map-server.exe!__crt_stdio_output::output_processor<char,__crt_stdio_output::string_output_adapter<char>,__crt_stdio_output::standard_base<char,__crt_stdio_output::string_output_adapter<char> > >::process() Line 1662	C++
 	map-server.exe!common_vsprintf<__crt_stdio_output::standard_base,char>(const unsigned __int64 options, char * const buffer, const unsigned int buffer_count, const char * const format, __crt_locale_pointers * const locale, char * const arglist) Line 163	C++
 	map-server.exe!__stdio_common_vsprintf(unsigned __int64 options, char * buffer, unsigned int buffer_count, const char * format, __crt_locale_pointers * locale, char * arglist) Line 235	C++`
`>	map-server.exe!vsnprintf(char * const _Buffer, const unsigned int _BufferCount, const char * const _Format, char * _ArgList) Line 1438	C
 	map-server.exe!snprintf(char * const _Buffer, const unsigned int _BufferCount, const char * const _Format, ...) Line 1951	C
 	map-server.exe!mobskill_use(mob_data * md, unsigned int tick, int event) Line 3844	C
 	map-server.exe!mob_ai_sub_lazy(mob_data * md, char * args) Line 2135	C
 	map-server.exe!map_foreachmob(int(*)(mob_data *, char *) func, ...) Line 2357	C++
 	map-server.exe!mob_ai_lazy(int tid, unsigned int tick, int id, int data) Line 2146	C
 	map-server.exe!do_timer(unsigned int tick) Line 369	C
 	map-server.exe!main(int argc, char * * argv) Line 366	C++
 	[External Code]	
 	[Frames below may be incorrect and/or missing, no symbols loaded for kernel32.dll]	
`

  * How to Reproduce: Exact cause unknown

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment]
Probably related to d673d25.
Closing this until it happens again.
