### ISSUE TITLE
unitwalk <Event Label> issue

### ISSUE THREAD

**Issue by Atemo** [rathena/rathena#2341]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/0126759d0078190d07f954a63c0551b7ba70cf43

* **Client Date**: 

* **Server Mode**: Renewal

* **Description of Issue**: The system is running all walking event at once when the unit reachs the first event label.
Test script:
```
izlude,128,124,0	script	unitwalk test A	4_F_01,{
	monster "izlude",128,124, "todo", 1002,1;
	.@mob_id = $@mobid[0];
	setunitdata .@mob_id, UMOB_MODE, 0x0000001|0x0000020;
	sleep 1000;
	unitwalk .@mob_id,132,120, strnpcinfo(0) + "::OnSpotA";
	end;
OnSpotA:
	unittalk 0,"A";
	unitwalk 0,132,116, strnpcinfo(0) + "::OnSpotB";
	end;
OnSpotB:
	unittalk 0,"B";
	unitwalk 0,128,112, strnpcinfo(0) + "::OnSpotC";
	end;
OnSpotC:
	unittalk 0,"C";
	unitwalk 0,124,116, strnpcinfo(0) + "::OnSpotD";
	end;
OnSpotD:
	unittalk 0,"D";
	unitwalk 0,124,120, strnpcinfo(0) + "::OnSpotE";
	end;
OnSpotE:
	unittalk 0,"E";
	unitkill 0;
	end;
}

izlude,132,120,0	script	#A	1582,{ end; }
izlude,132,116,0	duplicate(#A)	#B	1582
izlude,128,112,0	duplicate(#A)	#C	1582
izlude,124,116,0	duplicate(#A)	#D	1582
izlude,124,120,0	duplicate(#A)	#E	1582
```
Expected : 
![screenrathena006](https://user-images.githubusercontent.com/5231893/29336825-78acc720-820f-11e7-959f-807af53cbf21.jpg)
Result : 
![screenrathena007](https://user-images.githubusercontent.com/5231893/29336832-7d72575c-820f-11e7-8ff7-adac399dc35d.jpg)

When the unit is killed mapserv throw the error
![unitwalk_error](https://user-images.githubusercontent.com/5231893/29336889-adfe0cea-820f-11e7-885d-6b89c3dfcdca.png)

Note: the issue doesn't occur if we added a `sleep2` within the _OnSpot_ labels.

**Comment by Lemongrass3110** [comment]
The culprit is this loop:
https://github.com/rathena/rathena/blob/master/src/map/npc.c#L421
