### ISSUE TITLE
npcskill script command, <cast time>

### ISSUE THREAD

**Issue by Atemo** [rathena/rathena#2342]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/0126759d0078190d07f954a63c0551b7ba70cf43

* **Client Date**: 

* **Server Mode**: Renewal

* **Description of Issue**: 
From the docs : 
```
*npcskill <skill id>,<skill lvl>,<stat point>,<NPC level>;
*npcskill "<skill name>",<skill lvl>,<stat point>,<NPC level>;

This command causes the attached NPC object to cast a skill on the attached
player. The skill will have no cast time or cooldown. The player must be
within the default skill range or the command will fail silently.
```
__The skill will have no cast time or cooldown__

Current result:
![screenrathena012](https://user-images.githubusercontent.com/5231893/29337274-06852028-8211-11e7-8ae9-f48da2447ffb.jpg)

**Comment by Lemongrass3110** [comment]
Related to 2a6277a and #2045.
