### ISSUE TITLE
Some little errors on lastest rAthena version.

### ISSUE THREAD

**Issue by kaninhot004** [rathena/rathena#2344]
* **rAthena Hash**: 

374ecd0c997bfdf7055b89ae7c7e5d1a83d10ef5

* **Client Date**: 

Just run server.

* **Server Mode**: 

Renewal

* **Description of Issue**: 
Little error on map-server.

* **Modifications that may affect results**: 
-

![image](https://user-images.githubusercontent.com/9493525/29349852-342c2e16-8286-11e7-91d3-5ea302924102.png)

**Comment by Lemongrass3110** [comment]
Seems to be a local problem for you.
Everything is fine on master:
https://travis-ci.org/rathena/rathena/jobs/264849702#L1072

**Comment by kaninhot004** [comment]
Oops sorry. I had missing provided description about database.
I using SQL Database. ( conf > inter_athena.conf > use_sql_db : yes )

**Comment by Lemongrass3110** [comment]
Then upgrade your sql database. We keep it synchronized.
Whenever we add something to a txt file it gets auto-synced with the sql file.
The item you are missing was last touched in c7d77bb, which was over a year ago.
So just re-import the sql-files/item_db_re.sql file and you should be fine(if you have used item_db2_re for your custom changes).
