### ISSUE TITLE
The Sign Quest Error : Dancing Tile

### ISSUE THREAD

**Issue by Lilori** [rathena/rathena#2347]
* **rAthena Hash**: Latest

* **Client Date**: 2015

* **Server Mode**: RE

* **Description of Issue**: 
  * Result: If we stand to Down Right (s_dance#down) at last part, the NPC didn't trigger for next player who quest.
  * Expected Result: It should be trigger for next player
  * How to Reproduce: 
>. Follow instruction and stay to down right at last part, and NPC messed up if i go to re-dance.

NPC can normally running if:
>. Follow instruction and go stay at the center after last part (down right). so me and everyone who quest can dance.

many people makes mistake, it's so hard to wait until re-loading the NPC.

**Comment by Lilori** [comment]
Up. no one can confirm it? @aleos89 @Lemongrass3110

**Comment by anacondaqq** [comment]
@Lilori 

```
OnTouch:

This label will be executed if a trigger area is defined for the NPC object it's
in. If it isn't present, the execution will start from the beginning of the NPC
code. The RID of the triggering character object will be attached.

OnTouch_:

Similar to OnTouch, but will only run one instance. Another character is
chosen once the triggering character leaves the area.
```

https://github.com/rathena/rathena/blob/master/npc/quests/the_sign_quest.txt#L5372

Try to change it to OnTouch:
is it solve your problem?

**Comment by Lilori** [comment]
@anacondaqq 

Thanks for your reply. I'll check it soon. Anyway, is that rA follows official quest for this? because in my official is not run one instance.

**Comment by Everade** [comment]
@Lilori 
Not sure if it may be related to this but:
Did you decrease the official walkdelay by using the walkdelay diff using Nemo on your client ?

Because i noticed that if the walkdelay is set too low, it affects the amount of times the script triggers your walks.

So the script means that you've walked wrong and you aren't able to finish it that way.
So if the walkdelay is too low, the only way to finish the dance part properly is to do really short 1-clicks to the right spots.
Holding the mouse button while doing it always fails.

So in case you've modified the walkdelay on your client, i recommend to re-test it with the official walkdelay settings.

**Comment by aleos89** [comment]
According to #1548, these should be `OnTouch_` and only trigger for one person at a time.

**Comment by Lilori** [comment]
@Everade 
Nope, in the first (after reload the script), you will 100% success in dancing. But 2nd players, etc, cannot passing that because 2 missing dance. Try it by yourself,

@aleos89 
Yes, that's it! only trigger one person at a time, so if players want to quest, they must be waiting for maintenance or GM must be reload the sign script.
I found no official information about trigger one person. Correction?

**Comment by aleos89** [comment]
`OnTouch_` only allows one player to utilize the NPC at a time. So once that player is out of the room the next player coming in should be able to use the dance part just fine.

From what I can see on the official script is that there are no checks at all. Honestly it's a problem with the official server as they should turn this part into an instance or add some check to avoid multiple people entering the room at the same time.

**Comment by Atemo** [comment]
Without going into too much detail the issue is related to https://github.com/rathena/rathena/issues/2274
`Examiner#sd` overlap others npcs after being enabled

**Comment by Atemo** [comment]
https://github.com/rathena/rathena/commit/c977558cfdc170be51e86a39d6b3426b8b3f677c should have fixed the issue.
