### ISSUE TITLE
Request to add Show Katar Crit Bonus option on conf/battle/player.txt

### ISSUE THREAD

**Issue by ngek202** [rathena/rathena#2349]
* **rAthena Hash**: 374ecd0c997bfdf7055b89ae7c7e5d1a83d10ef5

* **Client Date**: 2014-10-22bRagexe, 2015-09-16aRagexe

* **Server Mode**: Pre-Renewal

* **Description of Issue**:  X2 Katar Crit Bonus is showing on Status Window
  * Result:  Thread: https://rathena.org/board/topic/112297-weird-crit-status-display/
  * Expected Result:  In official Server it should be hidden in Status Window
  * How to Reproduce:  Compare with Katar with Knife added with 3x Soldier Skeleton Card.
  * Official Information: https://forums.warpportal.com/index.php?/topic/46729-katar-crit-rate/
Official Information also provided by zackdreaver on hercules https://github.com/HerculesWS/Hercules/issues/573
If possible can we also apply a Battle config so it will be displayed or not.
like they did on hercules:
https://github.com/HerculesWS/Hercules/commit/83301cc59a75f14bea4b73136e7dffc396f37fc3
  

* **Modifications that may affect results**: 
  
   No modification done on Source that could affect the Status window

**Comment by zackdreaver** [comment]
https://github.com/rathena/rathena/pull/1481
https://github.com/rathena/rathena/issues/2349
