### ISSUE TITLE
Multi Server IP needed

### ISSUE THREAD

**Issue by esu1214** [rathena/rathena#2350]
I have a reuqest.
I have 2 ipaddress in my server.
But Char and Map Server can only set 1 public ip.
I need clients connect Char and Map Server use the same ip they connect Login Server, not that Char told Login, Map told Char their IP.

**Comment by Lemongrass3110** [comment]
I tried to understand what you are writing, but I simply cant. Sorry.

Could you give us an example?
Best would be some thumbsketch with the IPs(dont have to be yours, can be any if you do not want anybody to know them) on it.

**Comment by esu1214** [comment]
It seemed that Client diff(Enable Proxy) not work in new RE client.

**Comment by Lemongrass3110** [comment]
So you are complaining about a clientside problem?

**Comment by esu1214** [comment]
No. We have no client src.
So we can only change it in server side.

**Comment by esu1214** [comment]
The problem is that if we set ip1 in clientinfo.xml
We will connect the certain Login Server whose ip is ip1.
But we will connect to Char Server whose ip is that Char Server told Login Server.

**Comment by esu1214** [comment]
// Character Server IP
// The IP address which clients will use to connect.
// Set this to what your server's public IP address is.
//char_ip: 127.0.0.1

**Comment by esu1214** [comment]
I want the client will connect to Char Server whose ip is the same as Login Server, but not the ip Char Server told Login Server.

**Comment by Akkarinage** [comment]
This is a configuration issue, not an actual bug.

There is only one way to set an ip, if you want them all to be the same then simply set them all the same..

**Comment by secretdataz** [comment]
@esu1214 Can't you just use the NEMO patch that does exactly what you described?

**Comment by esu1214** [comment]
Hi all. Tks a lot.
But the problem is that REClient diff: Enable Proxy Support not work by using NEMO Patch

**Comment by esu1214** [comment]
So I can only modify server src to resolve it.

**Comment by esu1214** [comment]
@Akkarinage 
The problem is my server has 2 ipaddress, ip1 and ip2.
Something will occour as below if I set ip1 as my Char and Map Server public ip.
Client -> Login(ip1) -> Char(ip1) -> Map(ip1)
Client -> Login(ip2) -> Char(ip1) -> Map(ip1)

**Comment by esu1214** [comment]
It will occour as below if Client Diff: Enable Proxy Support.
Client -> Login(ip1) -> Char(ip1) -> Map(ip1)
Client -> Login(ip2) -> Char(ip2) -> Map(ip2)
I think the problem will be resolved if Login tell Client that Char ip is the same ip as that Client connect to Login.

**Comment by Akkarinage** [comment]
No..

If you have an additional IP, just set them in your second server's config files. What you've just described is having two servers running on one machine with two IPs. As I said before, this is a configuration issue, not a bug.

**Comment by esu1214** [comment]
No. I have only 1 server in a machine.
But I really need clients to connect both 2 ips.

**Comment by Akkarinage** [comment]
That's not how proxys work.. the machine will receive connections regardless of location and still point them in the right direction. Proxy setups are client side - please use the forums.

**Comment by esu1214** [comment]
So I need to point them to which ip they connect to Login, but not the ip Char told.

**Comment by Lemongrass3110** [comment]
Please use the forum as @Akkarinage told you.
Locking this issue now.

**Comment by Akkarinage** [comment]
But having 2 IPs on the same machine is a pointless exercise. That's not how a proxy works.

As I've said, you can obtain better support for your needs (with better explanations of why what you're doing is pointless) on the forums.
