### ISSUE TITLE
BOSS after death and respawn. BOSS view has changed.

### ISSUE THREAD

**Issue by TesLA-Git** [rathena/rathena#2351]
* **rAthena Hash**: 2d31bc3

* **Client Date**: 20160203

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: It might be associated with #2326. I've used the @reloadmobdb.
  * Expected Result: Part shapes change, not all. For example: Eddga (Mob_ID:1115)
  * How to Reproduce: Kill some BOSS, when they respawn, some BOSS view has changed. 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment]
Today does not seem to be my day. Could you explain it a bit better?
What happens? When does it happen? Etc.?
What is part shape changing?

**Comment by Valorro** [comment]
same... renewal 20160203, everything normal at athena-start, but when they respawn, some MVP Amon Ra, Eddga, and Boitata view changed, mob skill seems stay the same.
![amon1](https://user-images.githubusercontent.com/29807950/29437921-d2ec9286-83dd-11e7-9839-23b9ccd15fd7.jpg)
![amon2](https://user-images.githubusercontent.com/29807950/29437938-e7dd5dba-83dd-11e7-97be-0a2dff08068c.jpg)
