### ISSUE TITLE
Wrong Crimson Drop

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#2353]
* **rAthena Hash**: 
6b18ea5

* **Client Date**: 
2016-02-03aRagexeRE

* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result: Owl Duke, Owl Duke Ringleader, Anacondaq, Furious Anacondaw and Gryphon are dropping Longious Spear [2] rather than Crimson Lance
  * Expected Result: https://www.divine-pride.net/database/item/1498
  * How to Reproduce: Check Monster Database
  * Official Information: https://www.divine-pride.net/database/item/1498

* **Modifications that may affect results**: 
None

**Comment by Lemongrass3110** [comment]
Correct in the mob_drop.txt:
```
1320,1498,50,RDMOPTG_Crimson_Weapon // OWL_DUKE
2721,1498,250,RDMOPTG_Crimson_Weapon // C3_OWL_DUKE
1030,1498,50,RDMOPTG_Crimson_Weapon // ANACONDAQ
2904,1498,250,RDMOPTG_Crimson_Weapon // C4_ANACONDAQ
1259,1498,250,RDMOPTG_Crimson_Weapon // GRYPHON
```

It seems to be a clientside data side issue from his server.
