### ISSUE TITLE
Achievement Titles do not stay

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#2354]
* **rAthena Hash**: 
6b18ea5

* **Client Date**: 
2016-02-03aRagexeRE

* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result: Titles gained from Achievement system are not being saved upon logout. You have to re-apply them every single time you re-log
  * Expected Result: Selected Titles should stay
  * How to Reproduce: Select Title gained from achievement system, relog, take a look at it.
  * Official Information: -

* **Modifications that may affect results**: 
None

**Comment by Lemongrass3110** [comment]
Merge fail on his end.
