### ISSUE TITLE
Party

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#2356]
* **rAthena Hash**: 6f985080a8b071e5869679e430274a4b166971c2
* **Client Date**: 2017-05-31
* **Server Mode**: Renewal
* **Description of Issue**: Well, there is a small problem with the client party system 2017-05-17 or higher, when dying the icon in the groups window does not change to show that the character is dead.
  
Prints:

http://imgur.com/xX7jUmp

http://imgur.com/rw9pugX

**Comment by Lemongrass3110** [comment]
Easily explained:
1HP is not dead.
Need to resolve that though.

**Comment by Daegaladh** [comment]
But on official severs you have 1hp when you die ._.

**Comment by Atemo** [comment]
Players pass away when 0 hp in battle.
Players can be alive with 0 hp in some cases.
Dead players (lying on the ground) have 1 hp (except novices).

**Comment by mrjnumber1** [comment]
want to add that the lone party icon will show as dead, however in party window itself, the death state does not show up. however, use of ``@refresh`` will update the party window.
this applies to the -self- only, i didn't check it for a foreign bl.

**Comment by Daegaladh** [comment]
Then test it with the lastest client. If still doesn't work it's obvious we're missing some packet.

**Comment by Lemongrass3110** [comment]
I do not have the latest client unpacked. If you can give it to me I will. :-P

**Comment by Daegaladh** [comment]
Nah, I just have the one you gave me, 2017-06-14, but try it, at least is newer than 2017-05-31.

**Comment by Daegaladh** [comment]
Tested on 2017-06-14 and yep, the same happens, the icon doesn't refresh. Just by closing and re-opening the party window, or changing to friend window and back, it shows the dead icon, show there's some packet missing.
I noticed the icon in the small window does refresh correctly though.

**Comment by Lemongrass3110** [comment]
This seems to be our fault. It works on officials and does not work correctly on rA.
It is still broken with rA on 2017-09-20 so this means that it was not a client fault that has been fixed meanwhile.
