### ISSUE TITLE
Cannot get SVN revision number if checkout URL is not pointed to root folder

### ISSUE THREAD

**Issue by ngoclong19** [rathena/rathena#2358]
* **rAthena Hash**:  6f98508

* **Client Date**: 2015-11-04

* **Server Mode**: Renewal

* **Description of Issue**: Server executable files cannot get SVN revision number if the checkout URL is not pointed to root folder (e.g.: https://github.com/rathena/rathena/trunk). SVN version: 1.9.7 (works with SVN 1.6 and earlier).
  * Result: `Can't get bin name`, `Can't get entries kind` 
  * Expected Result: `SVN Revision: 22821` (working copy revision) 
  * How to Reproduce: Start the server, after initializing memory manager, the server checks and displays SVN revision number. 
  * Official Information: N/A. 
  

* **Modifications that may affect results**: N/A
  
  
* **More infos**: The server assumes the data in _NODES.dav_cache_ column (database file _.svn/wc.db_) ends with `!svn/ver/<revision>/<path>)`. But in this case, when _repos_path_ is _trunk_, _dav_cache_ is set to _NULL_.

**Comment by secretdataz** [comment]
Currently, rAthena's SVN support is being phased out. As a result, this issue won't be fixed.
