### ISSUE TITLE
Item database issues.

### ISSUE THREAD

**Issue by trickyloki3** [rathena/rathena#236]
These are mostly consistency issues from referencing item id or group that does not exist:
* Item ID 15657 does not exist in item database, but Item ID 12538 uses getitem on 15657.
* Item ID 7804 is commented out in item database, but Item ID 13765 uses getitem on 7804.
* IG_MYSTERIOUS_TRAVEL_SACK4 does not have entries in item_package.txt
* IG_UNLIMITED_BOX10 does not have entries in item_package.txt
* Item ID 28183 does not exist in item database, but Item ID 22813 does a callfunc("F_Rand") with the item 28183 in the list.

Compiler have trouble searching for the following constants:
32 - item group related.
255 - item related, but searches all constants tables and databases.
```
[warn]: failed to map constant 15657 in item 12538 on flag 255
[warn]: failed to map constant 7804 in item 13765 on flag 255
[warn]: failed to map constant 182 in item 13848 on flag 32
[warn]: failed to map constant 405 in item 17278 on flag 32
[warn]: failed to map constant 28183 in item 22813 on flag 255
```

**Comment by nanakiwurtz** [comment]
1,2,6 = Done
3. It exists on const.txt: IG_Pet_Egg_Scroll_Box5 = 99
4. Mysterious_Travel_Sack4 (#13848) = No information yet
5. Unlimited_Box(10) (#17278) = No information yet

**Comment by trickyloki3** [comment]
I made a mistake with IG_Pet_Egg_Scroll_Box5, it has zero entries in item_package.txt just like 4 and 5, which I assume no information is available yet.
