### ISSUE TITLE
Shield Spell Level 1 not give Additional Attack Buff.

### ISSUE THREAD

**Issue by playpsro** [rathena/rathena#2362]
* **rAthena Hash**: a75133e

* **Client Date**: 2015-11-04aRagexe

* **Server Mode**: Renewal

* **Description of Issue**: User try use Royal Guard to skill Shield Spell Level 1 to get additional attack.
  * Result: When user get a the Spell to additional attack, Attack on increase anymore .
  * Expected Result: User must get additional attack when use shield spell level 1 and get spell 3.
  * How to Reproduce: Just try use shield spell 1, and see the icon duration. when duration is Shield Def x 3, it must get additional attack
  * Official Information: http://irowiki.org/wiki/Shield_Spell

* **Modifications that may affect results**: No use modifications, just use gepard shield.
Before use shield spell..
![screenloki144](https://user-images.githubusercontent.com/15665450/29549733-0e2c2e52-8734-11e7-9eb6-5f017bb516c0.jpg)

After use, damage is same, no attack increase in status coloumn.

![screenloki146](https://user-images.githubusercontent.com/15665450/29549732-0e1d8ac8-8734-11e7-8da9-01b6359d4e43.jpg)

**Comment by aleos89** [comment]
The attack bonus from Shield Spell is flagged as Weapon Attack. From your screen shots it looks like you're not wearing a weapon. Try equipping a weapon and then see what the result yields.

**Comment by playpsro** [comment]
![screenloki147](https://user-images.githubusercontent.com/15665450/29596809-062b87f6-87e9-11e7-8cbe-6863b16353dc.jpg)
![screenloki148](https://user-images.githubusercontent.com/15665450/29596811-06743b72-87e9-11e7-83c0-c3e93fb6b383.jpg)


Added screenshot with Weapon.
The result is same, Shield Spell Skill level 1 doesn't give any additional attack.

**Comment by aleos89** [comment]
Can you try updating your server to a newer version? The hash you quoted above is quite old and probably has the status issue that was introduced in that hash.

**Comment by aleos89** [comment]
Pre Shield Spell:
![screenrathena002](https://user-images.githubusercontent.com/3521753/29735167-da653efe-89c4-11e7-9bda-7eb8be5ec0f3.jpg)
Post Shield Spell:
![screenrathena003](https://user-images.githubusercontent.com/3521753/29735172-dfb2f266-89c4-11e7-84e2-d4c19459c5a3.jpg)

Works fine for me.
