### ISSUE TITLE
Item combo database issues.

### ISSUE THREAD

**Issue by trickyloki3** [rathena/rathena#237]
A few issues I found with the item combo database:

 * 15138:19026 duplicates **bonus2 bSubRace,RC_Fish,(10+getequiprefinerycnt(EQI_ARMOR));**, twice which could be succinctly written as **bonus2 bSubRace,RC_Fish,(10+getequiprefinerycnt(EQI_ARMOR)) * 2;**.  
 * 18997:28326:28327 uses bonus bSpeed,25; but should be either **bonus bSpeedRate,25;** or **bonus bSpeedAddRate,25;**.

```
[warn]: bonus duplicated on item id 15138; in block 1 and 2; see dump.txt.
script_compile_raw;952; translator failed; invalid blocks in { bonus bSpeed,25; bonus bBaseAtk,50; bonus bMatk,50; } for item id 18997
```

The problem with this one is that val4 is set to 1 meaning infinite Endure according to status.c:
 * 24180:24181:24182:24183:24184:24185 contains **sc_start4 SC_ENDURE,1,10,0,0,1;** without corresponding **sc_end SC_ENDURE;** or does this get handle automatically when the combo breaks?

**Comment by cydh** [comment]
that SC_ENDURE should be worked at all. xD duration = 1 sec.
I was playing with a little rewrite item_combo to sv_readdb
`24180:24181:24182:24183:24184:24185#{ .@refine = getequiprefinerycnt(EQI_SHADOW_ARMOR)+getequiprefinerycnt(EQI_SHADOW_WEAPON)+getequiprefinerycnt(EQI_SHADOW_SHIELD)+getequiprefinerycnt(EQI_SHADOW_SHOES)+getequiprefinerycnt(EQI_SHADOW_ACC_R)+getequiprefinerycnt(EQI_SHADOW_ACC_L); bonus bAllStats,1; if(.@refine>=45) { bonus bMaxHPrate,(.@refine-60); sc_start4 SC_ENDURE,-1,10,0,0,1;} }#{ sc_end SC_ENDURE; }`

**Comment by trickyloki3** [comment]
After tweaking my compiler I got this to output:
```
All Stats: +1
 -> Increase -60% ~ +30% (based on Shadow Weapon's Refine Level) maximum HP.
 -> Enable the effect of Endure Skill for 0 seconds.
```
1 millisecond would have definitely not work. >.>

**Comment by trickyloki3** [comment]
I didn't notice that; 1 millisecond would definitely not work.

Script for 24180:24181:24182:24183:24184:24185 was difficult to compile correctly. Q.Q

**Comment by nanakiwurtz** [comment]
If the amount of the entire set of refine is equal or superior 45 provides the user with the [Endure] effect, that's why the SC_ENDURE was made to be permanent
