### ISSUE TITLE
Syntax shadow error on make server

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#2380]
CXX     src/nodeevents.cpp
In file included from include/yaml-cpp/node/detail/node.h:14:0,
                 from src/nodeevents.cpp:4:
include/yaml-cpp/node/detail/node_ref.h: Dalam anggota fungsi ‘void YAML::detail::node_ref::set_mark(const YAML::Mark&)’:
include/yaml-cpp/node/detail/node_ref.h:33:35: peringatan: deklarasi dari ‘mark’ membayangi sebuah anggota dari 'this' [-Wshadow]
   void set_mark(const Mark& mark) { m_pData->set_mark(mark); }
                                   ^

I think this error appears since the August update, I did not find this error in July. I've done clean git reset remain the same.

Screenshot: http://i.imgur.com/G2yYz29.png

* **rAthena Hash**: 7a1b2e0

* **Client Date**: 

* **Server Mode**: 

* **Description of Issue**: 
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
You need to update GCC/G++ to version 5.

**Comment by mazvi** [comment]
How to update it?

**Comment by mazvi** [comment]
Solved this solution to update on centos 7 64 bit

sudo yum install centos-release-scl
sudo yum install devtoolset-4-gcc*
scl enable devtoolset-4 bash
which gcc
gcc --version

**Comment by mazvi** [comment]
Solved this solution to update on centos 7 64 bit

sudo yum install centos-release-scl
sudo yum install devtoolset-4-gcc*
scl enable devtoolset-4 bash
which gcc
gcc --version

special thanks to @aleos89
