### ISSUE TITLE
SlowGrace/DontForgetMe Bug

### ISSUE THREAD

**Issue by ridabbq** [rathena/rathena#2385]
Hello, I figured out on my server that when you are under SC_SPEEDUP1 ( Speed Potion ), there is no way to get slowed : no aspd/movementspeed decrease .

i'd like to know if anyone has a solution to fix this problem

**Comment by Playtester** [comment]
Hmm according to this issue: https://github.com/rathena/rathena/issues/904
I think this might be worked as intended.

The code I quoted there also shows you how you can change it, if you want to change it for your server. You simply need to remove "SC_DONTFORGETME" from the list.

**Comment by ridabbq** [comment]
Didn't see the #904 issue before asking my bad.
All working fine now, thank you !
