### ISSUE TITLE
Increase SQL max_hp, etc?

### ISSUE THREAD

**Issue by M45T3Ryu** [rathena/rathena#2387]
This is easily repairable by just editing the SQL max longitude for those columns, but I think its fine to post it here because it creates a lot of errors with high status values by default

![zkweywt](https://user-images.githubusercontent.com/2993425/29870734-a5df50b0-8d4e-11e7-9df5-3482a027997b.png)

**Comment by anacondaqq** [comment]
GitHub issues tracker is an incorrect place for such things. Please use the forum.

**Comment by M45T3Ryu** [comment]
Im not looking for support, the values are incorrect

**Comment by Lemongrass3110** [comment]
@anacondaqq it's ok. It is partially a bug report(with not much information) and partially a feature request.

@M45T3Ryu please stick to the issue template next time and try to provide a bit more information and/or steps to easily reproduce your issue.

**Comment by M45T3Ryu** [comment]
ok, sorry I tought I didn't need a lot of information..

**Comment by Jeybla** [comment]
@M45T3Ryu Even if those informations aren't necessary; it's often helpful to track down the cause of a problem or to reproduce the issue. The more info, the better. Unless it's useless spam :)
