### ISSUE TITLE
Pet Duplication

### ISSUE THREAD

**Issue by RadianFord** [rathena/rathena#239]
After adding this https://github.com/rathena/rathena/commit/62bdc99f05120c81b6d5a64dd572bae1715f1976
in to this revision
https://github.com/rathena/rathena/tree/1e6e3f4df36bd85d1c411a38a3e4d8c319240b1d

Now I am having this issue... (please view the images)
1. http://i.imgur.com/gQiC1p3.jpg
2. http://i.imgur.com/aXoZ0du.jpg
3. http://i.imgur.com/xA42GP0.jpg

If you return it to the egg you will be given 2 poring eggs. it can also be drop.

Update 1: after i restart the server this error shows
[Error]: pet_recv_petdata: Hatching pet (3:Poring) aborted, couldn't find egg in inventory for removal!

Update 2: Same thing happens on the latest revision. example using @makeegg command then @hatch after that restart the server (./athena-start restart) then you can produce this  one...

**Comment by Lemongrass3110** [comment]
Any feedback in why this was closed?
Is the problem resolved in the current version?

**Comment by anacondaqq** [comment]
Sorry, i did have the same issue with 2010-07-30 game exe, and packet ver 25 with the same hash... 
Maybe it's a problem with packet_db? Or packet version?

**Comment by aleos89** [comment]
Did you happen to run the upgrade_20140612.sql? Also run the upgrade_20140616.sql to make sure. You can check by going to all the pet eggs in the tables and make sure the value is 256 instead of some arbitrary number for card0. This was when we did the push for 64k item support.
