### ISSUE TITLE
probably error in skill or bonus4 bAutoSpell

### ISSUE THREAD

**Issue by luan122** [rathena/rathena#2391]
* **rAthena Hash**: 3e51f68
* **Client Date**: 207-06-16b
* **Server Mode**: Renewal
* **Description of Issue**: 
  * Result: When the item use the skill it is used in the caster not in the enemy
  * Expected Result: Should use in enemy
  * How to Reproduce: Equip the item with id: 
  * Official Information: item description is:
A hat with High-performance laser shooter.
Dex +2.
Long ranged physical attack +10%.
When dealing physical attacks, has a chance for 5 seconds transform wearer into Cecil Damon (Shecil). Higher refine level increases the chance of transformation. 
During transformation you will gain:
Skill delay -100%.
Adds certain chance when dealing physical attacks to auto cast True Sight Level 2 (or cast at the learnt level).
When attacking with long range physical attack, has a chance to autocast Level 1 Lex Aeterna.

* **Modifications that may affect results**: none

**Comment by aleos89** [comment]
The bonus should be:
```
bonus5 bAutoSpell,"PR_LEXAETERNA",1,50,BF_LONG,1;
```

**Comment by aleos89** [comment]
Fixed in https://github.com/rathena/rathena/commit/734ec22577b1045aae3633bc6fd285f76121c25d
