### ISSUE TITLE
" Incubus " pet_script is not working. And SQL " item_db_re " 1 missing item while execute sql files.

### ISSUE THREAD

**Issue by kaninhot004** [rathena/rathena#2393]
* **rAthena Hash**: 

3e51f68570a471086d18e248aa8a7113b9db0cdc

* **Client Date**: 

20170614

* **Server Mode**: 

Renewal

* **Description of Issue**: 
  * Result: " Incubus " pet_script is not working. And SQL " item_db_re " 1 missing item while execute sql files.
  * Expected Result: -
  * How to Reproduce:

It's here db > re > pet_db

```
1374,INCUBUS,Incubus,12370,9052,10034,6110,80,60,10,100,250,20,50,150,0,0,300,300,800,{ bonus bMaxSPRate,3; bonus2 bSPDrainRate,10,1; },{ bonus bMaxSPRate,5; bonus2 bSPDrainRate,30,1; }

TO

1374,INCUBUS,Incubus,12370,9052,10034,6110,80,60,10,100,250,20,50,150,0,0,300,300,800,{ petskillbonus bMaxSPRate,3,10,5; bonus2 bSPDrainRate,10,1; },{ bonus bMaxSPRate,5; bonus2 bSPDrainRate,30,1; }
```

and

sql-files\item_db_re.sql 

line 11507 ( There are 2 same name of " Shining Holy Water " )

```
REPLACE INTO `item_db_re` VALUES (28355,'Shining_Holy_Water','Shining Holy Water',4,0,NULL,100,NULL,0,NULL,1,0xFFFFFFFF,63,2,136,NULL,'1',0,0,'/* todo */',NULL,NULL);

TO

REPLACE INTO `item_db_re` VALUES (28355,'Shining_Holy_Water_','Shining Holy Water_',4,0,NULL,100,NULL,0,NULL,1,0xFFFFFFFF,63,2,136,NULL,'1',0,0,'/* todo */',NULL,NULL);
```

  * Official Information: -

* **Modifications that may affect results**: -

**Comment by Lemongrass3110** [comment]
As you can see here https://travis-ci.org/rathena/rathena/jobs/270532658#L1073 the buyingstore problem is probably your own fault.

Also your pet issue sounds pretty much like #849.

**Comment by aleos89** [comment]
The pet support feature is completely custom and is not a kRO feature.

**Comment by kaninhot004** [comment]
My friends found the solution.
It's here db > re > pet_db

```
1374,INCUBUS,Incubus,12370,9052,10034,6110,80,60,10,100,250,20,50,150,0,0,300,300,800,{ bonus bMaxSPRate,3; bonus2 bSPDrainRate,10,1; },{ bonus bMaxSPRate,5; bonus2 bSPDrainRate,30,1; }

TO

1374,INCUBUS,Incubus,12370,9052,10034,6110,80,60,10,100,250,20,50,150,0,0,300,300,800,{ petskillbonus bonus bMaxSPRate,3; petskillbonus bonus2 bSPDrainRate,10,1; },{ bonus bMaxSPRate,5; bonus2 bSPDrainRate,30,1; }
```

**Comment by aleos89** [comment]
This was refactored some in ac558d7. The battle configuration still requires enabling for the custom features.
