### ISSUE TITLE
[Error]: quest_add: Character %somename% already has quest %some_id%

### ISSUE THREAD

**Issue by anacondaqq** [rathena/rathena#241]
##### I have many different errors with rAthena at map server. Here is a couple of them

[Friendship Quest](http://irowiki.org/wiki/Friendship_Quest)
> [Error]: quest_add: Character 150000 already has quest 12000

**How Reproduce**
1. Talk to _Maki_
2. Talk again and again.
3. Check your map-server for errors.

Not cool code cause this error
>		mes "[Maku]";
		mes "Eh, forget about it.";
		mes "Why am I even talking";
		mes "about my personal life";
		mes "to someone I just met";
		mes "anyway? Sure, we all";
		mes "do it, but still...";
		set friendship,1;
		setquest 12000;

#### How to fix: 
>		mes "[Maku]";
		mes "Eh, forget about it.";
		mes "Why am I even talking";
		mes "about my personal life";
		mes "to someone I just met";
		mes "anyway? Sure, we all";
		mes "do it, but still...";
		set friendship,1;
		if( !isbegin_quest(12000) == 0 )
			setquest 12000;

##### To be continued...

**Comment by Atemo** [comment]
Please post all your quest error
> [Error]: quest_add: Character 150000 already has quest 12000

or make a PR !

**Comment by anacondaqq** [comment]
> To be continued...

I will update this topic, cause need to find map-server logs first.

**Comment by anacondaqq** [comment]
#### Okay, i was found old file with many different errors from map server.

##### Here is it:
> [Error]: quest_change: Character 150000 doesn't have quest 18043.
[Error]: quest_change: Character 150000 doesn't have quest 18046.
[Error]: quest_change: Character 150000 doesn't have quest 18047.
[Error]: quest_change: Character 150000 doesn't have quest 18041.
[Error]: quest_change: Character 150000 doesn't have quest 18040.
[Error]: quest_change: Character 150000 doesn't have quest 18039.
[Error]: quest_change: Character 150000 doesn't have quest 18038.
[Error]: quest_change: Character 150000 doesn't have quest 18037.
[Error]: quest_change: Character 150000 doesn't have quest 18036.
[Error]: quest_change: Character 150000 doesn't have quest 18035.
[Error]: quest_change: Character 150000 doesn't have quest 18034.
[Error]: quest_change: Character 150000 doesn't have quest 18033.
[Error]: quest_change: Character 150000 doesn't have quest 18032.
[Error]: quest_change: Character 150000 doesn't have quest 18031.

**Comment by Lemongrass3110** [comment]
Regarding the friendship quest.

There might be another issue, because if you look for "set friendship,1;" in npc/quests/quests_lighthalzen.txt you will see, that it is set to this value more than once.

I will do further investigations on this.

**Comment by Lemongrass3110** [comment]
I fixed the friendship quest, but the other one looks fine to me.

I will leave this issue closed for the time being, feel free to open a new issue if you face the "quest_change" problems again. These outputs could have been from testing: for example if you used ``@set`` to skip some parts of the quest, that way your questlog would not have the required quests.

**Comment by anacondaqq** [comment]
@Lemongrass3110 no no, it's players doing. This means they playing and mapserver recieve it.
Sure, thx for fixing it. I will report about other quests errors to map-server when i will collect to much information. Thank you for fixing it.
