### ISSUE TITLE
SC_VACUUM_EXTREME map server crash.

### ISSUE THREAD

**Issue by whupdo** [rathena/rathena#2414]
visual studio debug map server crash.

Thx!

![1505141195409](https://user-images.githubusercontent.com/17958968/30281422-f29862c0-9744-11e7-8710-79989488806f.jpg)
![1505141213016](https://user-images.githubusercontent.com/17958968/30281423-f2be9bac-9744-11e7-9738-583f3adc2cb4.jpg)

**Comment by aleos89** [comment]
Can you give a scenario as to how you were able to crash the server? Can you also provide he information that was presented in the template for the issue?

**Comment by Jeybla** [comment]
@whupdo can you provide more informations?

The crash above makes not really sense. If sce is a null pointer, why doesn't it crash in line 13433 already?

**Comment by Jeybla** [comment]
No further input.
