### ISSUE TITLE
Passing/Taking arrays variables from NPC/Function to NPC/Function does not work

### ISSUE THREAD

**Issue by jezznar** [rathena/rathena#2417]
* **rAthena Hash**:  5fda4f0 

* **Client Date**:  20151015. Not relevant.

* **Server Mode**:  Pre-re/Re. Not relevant

* **Description of Issue**:  Passing an array variable to a function does not work. It could be very beneficial to simplify passing/handling of variables.
  * Result: NPCs only display "0" as results
  * Expected Result: Get full passed/gotten array variable by/from NPC
  * How to Reproduce: 

> prontera,100,100,5`<tab>`script`<tab>`ArrayPassingTest`<tab>`150,{
> setarray .Array[0], 1,2,3,4,5,6,7;
> callfunc "ArrayPassFunc", .Array;
> close;
> }
>
> function`<tab>`script`<tab>`ArrayPassFunc`<tab>`{
>     setarray .Array[0], getarg(0);
>      for(set .@x, 0; .@x < getarraysize(.Array); set .@x, .@x + 1) {
>     mes "Index["+.@x+"]: "+.Array[.@x];
>     return;
> }
>
> }
> prontera,100,101,5`<tab>`script`<tab>`ArrayGetTest`<tab>`150,{
> setarray .Array[0], getvariableofnpc(.Array,"ArrayPassingTest");
> for(set .@x, 0; .@x < getarraysize(.Array); set .@x, .@x + 1) {
>     mes "Index["+.@x+"]: "+.Array[.@x];
> }
> close;
> }

  * Official Information: N/A

* **Modifications that may affect results**:  N/A

**Comment by Atemo** [comment]
Sample to pass an array
```
function	script	ArrayPassFunc	{
	.@size = getarraysize( getarg(0) );
	for ( .@i = 0; .@i < .@size; .@i++ )
		debugmes "Index[" + .@i + "]: " + getelementofarray( getarg(0), .@i );
	return;
}

prontera,93,112,5	script	ArrayPassingTest	56,{
	end;
OnInit:
	setarray .array[0], 1,2,3,4,5,6,7;
	callfunc "ArrayPassFunc", .array;
	end;
}
```

**Comment by jezznar** [comment]
I'm aware of this workaround. I just thought of it for simplification purposes.
Thanks though @Atemo
