### ISSUE TITLE
callshop, itemshop broken: not displayed sell window at all

### ISSUE THREAD

**Issue by anacondaqq** [rathena/rathena#2419]
* **rAthena Hash**: 82222084216468bae966ee6a8106bdcce00f29d0, clean no mods.

* **Client Date**: 2015-11-04aRagexe

* **Server Mode**: PRE-RE / RE doesn't matter

## The Problem explained

![](https://i.imgur.com/sD0HVDf.gif)

**Test Script**
```c
-	itemshop	BROOOO	89,5169,505:10,506:15
amatsu,199,99,5	script	ItemShopbrroo	89,{

	callshop "BROOOO",0;
	end;

}
```

### Text details

sell window does not work at all for itemshops. Not tested variableshops and normal shops, maybe someone can do it, but for itemshops 100% sell dialogue or dialogue where you can select buy / sell not working at all.

raw shops without using any NPC does not works too. I mean impossible to select sell window because there are no sell window, or call dialogue where you can buy or sell.

## How reproduce?

Take script above, and try to run it.

Don't forget about script command description.

```
*callshop "<name>",<option>;

These are a series of commands used to create dynamic shops.
The 'callshop' function calls an invisible shop (view -1) as if the player clicked on it.

The options are:
	0 = The normal window (buy, sell and cancel)
	1 = The buy window
	2 = The sell window
```

## How it must work?

itemshop, cashshop, pointshop, shop must works fine with and without callshop.
callshop must works fine too.

What does means "fine"? Fine means like it explained in script commands and how it was work for years.
Right now possible to open only BUY window.

## Extra information

allow_bound_sell does not work fine too.
![](https://i.imgur.com/PmkztE0.png)

**Comment by Lemongrass3110** [comment]
Related to #843 and #1008.
Related commits: a16fb7c, 4eb3a9e
Since these changes in April 2016 the item and point shops use the cash shop interface instead of the normal one.
