### ISSUE TITLE
Fatal Menace

### ISSUE THREAD

**Issue by MrAntares** [rathena/rathena#242]
Git Version: **12628 - 2014-12-04 05:04:30 (luciar)**
Client Date: **2012-04-10**
Src Mods: **NONE**
General settings: 
- **Full Renewal**
- **1/1/1/1/1 rate**
- **PK server (not in towns, above lvl 30)**
- **PVP ATK/Skill modifers: 100%**
- **WOE ATK/Skill modifers: rA default**
- **Official walk path and stacking**
- **Exp and drop penalty table values below 100% set to 100%**
- **Party and attacker exp bonus: +40%**
- More at (Hungarian, use translate): http://wiki.ragna.ro/

How to reproduce: **Use the skill**
Description:

The skill does not teleport hit monsters with the player. It should work like an AoE Intimidate/Snatch.

**Comment by aleos89** [comment]
Are you casting this skill on a map that doesn't allow teleport?

**Comment by aleos89** [comment]
Just tested on a clean pull and it worked just fine for me. Make sure the map you use it on allows teleportation.
