### ISSUE TITLE
pc_bonus: ShowWarning in rare cases will provoke map-server crash

### ISSUE THREAD

**Issue by anacondaqq** [rathena/rathena#2420]
### Technical Information
**hash:** 82222084216468bae966ee6a8106bdcce00f29d0
**mode:** PRERE / RE does not matter
**client:** 2015-11-04aRagexe

### Problem

pc.c
`pc_bonus()`, `pc_bonus2()`, and others which use the same `ShowWarning` below:

```c
ShowWarning("pc_bonus: unknown bonus type %d %d in item #%d\n", type, val, current_equip_card_id ? current_equip_card_id : sd->inventory_data[current_equip_item_index]->nameid);
```

Please take look on `sd->inventory_data[current_equip_item_index]->nameid`.
What if current_equip_item_index will be -1? It will provoke map-server crash.
I think there must be an extra check that the pointer really exists to avoid issues.
In other words, better to have something like that (complicated and very stupid, but works).

### How reproduce?
Sorry, but there are no steps to reproduce the issue yet. Only if you will manually set it (current_equip_item_index) to -1.
But please try to understand, this happened very rare and I forgot what provoke it on clean rAthena.
Even without steps how to reproduce such constructions with two totally different parameters and without extra checks such ShowEvents unacceptable because can provoke map-server crash at a stage, when they must help administrator to debug an issue.
**P.S.** can happen in systems with bonuses without items. 

### What is expected?

Something like this (this is mega stupid check, and should be avoided, but it will work)
```c
ShowWarning("pc_bonus: unknown bonus type %d %d in item #%d\n", type, val, current_equip_card_id ? current_equip_card_id : (current_equip_item_index >= 0) ? sd->inventory_data[current_equip_item_index]->nameid : 0);
```

Must be changed ShowWarning to safer, with checking parameters before using them for avoiding map-server crashes in very rare situations from some bugs.

**Comment by vstumpf** [comment]
I can only reproduce this when using `bonus` in an NPC script with a non-existent bonus-type. `bonus 2092, 9` will cause the map server to crash.

People really shouldn't be using the `bonus` script command in npc scripts though.
