### ISSUE TITLE
4853 Fixedcastrate not work

### ISSUE THREAD

**Issue by esu1214** [rathena/rathena#2422]
itemid 4853
if(.@r>11) { bonus bAspd,1; bonus bFixedCastrate,-7; }

bonus bFixedCastrate,-7; not work.

**Comment by secretdataz** [comment]
Can you not remove the issue template?

**Comment by esu1214** [comment]
Sorry.

**Comment by Playtester** [comment]
Most important, did you compile on renewal?

**Comment by esu1214** [comment]
yes，of course

**Comment by aleos89** [comment]
Can you provide what Git hash you are on?

**Comment by Playtester** [comment]
-7 is really hard to test with, try putting something like -70.
Make sure the equip is refined to +12 or higher.
Also check if the skill you are testing it with actually has any fixed cast time.

**Comment by esu1214** [comment]
I've located the error. It is because of a itemdb error of id 2907.
It should be Fixedcastrate but it now is variablecastrate.

**Comment by esu1214** [comment]
I've located the error. It is because of a itemdb error of id 2907.
It should be Fixedcastrate but it now is variablecastrate.
