### ISSUE TITLE
Character variable lengths and char-server

### ISSUE THREAD

**Issue by Tokeiburu** [rathena/rathena#2425]
* **rAthena Hash**: 8222208
* **Client Date**: Any
* **Server Mode**: Renewal
* **Description of Issue**: 
  * Result: When saving long character variable strings, the char-server can easily crash.
  * Expected Result: No crash.
  * How to Reproduce: I've used the following script to reproduce the issue:
```
prontera,155,176,3	script	Pront Test	77,{
	test$ = "0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345";
	test2$ = "anything really, doesn't matter at this point";
	end;
}
```
  * Other Information: There are no size checks for these variables in intif_saveregistry, it just truncates the size to 
```
WFIFOB(inter_fd, plen) = (unsigned char)len;
```
and past 254, the problems start (the max size of the char array is 254 in the char-server). The same issue also happens with variables having a name length above 32. What I've personally done is
```
		len = strlen(varname)+1;

		if (len > 32) {
			ShowError("intif_saveregistry: Variable name length is too long (aid: %d, cid: %d): %s\n", sd->status.account_id, sd->status.char_id, varname);
			continue;
		}

and ...

			if( p->value ) {
				len = strlen(p->value)+1;

				if (len > 254) {
					ShowError("intif_saveregistry: Variable content length is too long (aid: %d, cid: %d): %s, content: %s\n", sd->status.account_id, sd->status.char_id, varname, p->value);
					len = 254;
					p->value[len - 1] = '\0';
				}
```
But it would probably be best to do those checks when the values are set, not when they're saved.

* **Modifications that may affect results**:

**Comment by anacondaqq** [comment]
can confirm, I though this is mine custom mods do that and did not report about it earlier.
