### ISSUE TITLE
marketshop BUG in 2017-06-14bRagexeRE Client.

### ISSUE THREAD

**Issue by whupdo** [rathena/rathena#2426]
rAthena Hash: 557cccac9c987ba28c3d6fd906dc9633e1e60eb7

![777777](https://user-images.githubusercontent.com/17958968/30550042-ec9deadc-9cc8-11e7-8061-eb03519712eb.gif)
test script
```
prontera,156,151,4	marketshop	test#prt	123,601:1000:1000,602:500:1000,603:100:1000,604:50:1000,605:30:1000
```

2017-06-14bRagexeRE Client

Edit Jey: Quoted the test script.

**Comment by admkakaroto** [comment]
Client 2017-05-31, I confirm the same problem.

**Comment by admkakaroto** [comment]
Client 2017-05-31, I confirm the same problem.

My hash: 6f985080a8b071e5869679e430274a4b166971c2
Mode: Renewal

**Comment by tuxico** [comment]
the discounted price is according to the amount?

**Comment by jezznar** [comment]
@tuxico he's trying to buy other items but instead of adding new items to the buy list, it updates the amount of the current item that is in it.

**Comment by Lemongrass3110** [comment]
This is a client only behaviour. No packets are sent to or from the server when you add items to your buy list. Seems like gravity changed this.
Maybe @mrjnumber1 can help us and create a diff for it.
