### ISSUE TITLE
ERROR COMPILATION

### ISSUE THREAD

**Issue by papcimpt** [rathena/rathena#2427]
WHY?

make[1]: Leaving directory `/home/emulador/rAthena/src/char'
make[1]: Entering directory `/home/emulador/rAthena/src/map'
        CC      status.c
status.c: In function ‘status_yaml_readdb_refine_sub’:
status.c:14239:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (yamlwrapper* type = yaml_iterator_first(it); yaml_iterator_has_next(it); type = yaml_iterator_next(it)) {
   ^
status.c:14239:3: note: use option -std=c99 or -std=gnu99 to compile your code
status.c:14273:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (yamlwrapper* level = yaml_iterator_first(it); yaml_iterator_has_next(it); level = yaml_iterator_next(it)) {
   ^
status.c: In function ‘status_yaml_readdb_refine’:
status.c:14323:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
  for (int i = 0; i < ARRAYLENGTH(labels); i++) {
  ^
make[1]: *** [obj/status.o] Error 1
make[1]: Leaving directory `/home/emulador/rAthena/src/map'
make: *** [map] Error 2

**Comment by papcimpt** [comment]
OBS: last release

**Comment by secretdataz** [comment]
Install g++ version 5 or later
