### ISSUE TITLE
int -> bool cast warning in getequiprefinecost

### ISSUE THREAD

**Issue by vstumpf** [rathena/rathena#2428]
* **rAthena Hash**:  https://github.com/rathena/rathena/commit/e24d30a7113835f9c33f0fb51b89acfb7e00882f

* **Client Date**: any

* **Server Mode**: Both

* **Description of Issue**: MSVC displays a warning, casting int to bool. Can either be fixed by changing the function definition or the argument.

* **Modifications that may affect results**:  None

**Comment by Daegaladh** [comment]
I think is the same as https://github.com/rathena/rathena/commit/e24d30a7113835f9c33f0fb51b89acfb7e00882f#commitcomment-24385785

**Comment by vstumpf** [comment]
It is, I just didn't know how to reference it in the PR.
