### ISSUE TITLE
Rebellion issue

### ISSUE THREAD

**Issue by linkineox** [rathena/rathena#243]
When i configure a item on item_db with this

All Classes               : 0xFFFFFFFF
Every Job Except Novice   : 0xFFFFFFFE

the rebellion class can't use the item.

sorry for my bad english.

any idea? D:

**Comment by Atemo** [comment]
Did you check the class field ?
> 0xFFFFFFFF,1
Class bitmask 1

**Comment by nanakiwurtz** [comment]
No more reply by poster in more than 1.5 months already.
