### ISSUE TITLE
Attr_Fix

### ISSUE THREAD

**Issue by tuxico** [rathena/rathena#2432]
Renewal Server
2017-05-17aRagexeRE

I tried change values on tables for ghost property nv 1, but values on damage keep same.

1	// lv1 Attribute table
//Neut Watr Erth Fire Wind Pois Holy Shdw Gho  Und
  100, 100, 100, 100, 100, 100, 100, 100,  70, 100,  // Neutral
  100,  25, 100, 150,  90, 100,  75, 100, 100, 100,  // Water
  100, 100,  25,  90, 150, 100,  75, 100, 100, 100,  // Earth
  100,  90, 150,  25, 100, 100,  75, 100, 100, 125,  // Fire
  100, 175,  90, 100,  25, 100,  75, 100, 100, 100,  // Wind
  100, 100, 125, 125, 125,   0,  75,  50, 100, -25,  // Poison
  100, 100, 100, 100, 100, 100,   0, 125, 100, 150,  // Holy
  100, 100, 100, 100, 100,  50, 125,   0, 100, -25,  // Shadow
  10, 100, 100, 100, 100, 100,  75,  75, 125, 100,  // Ghost
  100, 100, 100, 100, 100,  50, 100,   0, 100,   0,  // Undead

--------------------------------------------------------------------------

i tried in re\pre-re folders.

**Comment by Jeybla** [comment]
How did you test the damage?

**Comment by tuxico** [comment]
Asure Strike in other player.

**Comment by Jeybla** [comment]
Did you read the description?
```
// Structure of Database:
// Columns - attacker's weapon element
// Rows    - target's defense element
```

**Comment by tuxico** [comment]
Yep.. and where is the error?
i tried with finger offensive, normal hit... sonic blow, ever all neutral atk.

**Comment by Jeybla** [comment]
Was the target player wearing a ghost ring?

**Comment by tuxico** [comment]
...

**Comment by tuxico** [comment]
man, try reproduce it in your branch.
equip ghostring, go to attr_fix, change value to 1 our 200 and watch if had changes...

**Comment by Jeybla** [comment]
![image](https://user-images.githubusercontent.com/6203894/30647917-034bf6ca-9e1d-11e7-89a6-556e501b84a5.png)
Works as intended (First is Asura vs without GR, Second is Asura vs with GR and attr_fix set to 1%)

**Comment by Akkarinage** [comment]
In future, use the template or we'll have our bot just auto close issues where users can't follow instructions.

**Comment by tuxico** [comment]
Thank you for closing this, I found another alternative.

**Comment by tuxico** [comment]
I have expressed myself a bit wrong, not that the values ​​are not being changed .. they are simply not being read, let's see an example: an asura against enchated ghost armor, this is reducing 30% of the damage as in ragnarok, but even though I change in the level 1 table, the fixed 30% continues ... and as if there was a phantom attr_fix being overlapped or as if the data were acquired from another source.
I will share with you my ghostring itemdb, my attr_fix.
my version of rathena is almost the last.

**Comment by Playtester** [comment]
Sounds like you either mixed up /db/pre-re/ and /db/re/ folders or you have a file in your /db/import folder that overwrites all your changes.

**Comment by tuxico** [comment]
I also raised this hypothesis, but my folder Import is exactly like the branch of rAthena, with an attr_fix of 1kb.

**Comment by tuxico** [comment]
It simply does not make sense.

**Comment by tuxico** [comment]
I just tested with fire element and the values are actually being read, the problem is in asura with the ghost element ...

**Comment by Playtester** [comment]
Does it only affect Asura Strike or normal attacks as well?

**Comment by tuxico** [comment]
Both

**Comment by Jeybla** [comment]
Did you try it on a clean rathena version? Maybe some other modifications are causing problems.

**Comment by Jeybla** [comment]
No further input. @tuxico if you have detailed instructions to reproduce the issue, just reopen it. Thanks
