### ISSUE TITLE
Transcendent NPC Issue

### ISSUE THREAD

**Issue by reunite-ro** [rathena/rathena#2434]
* **https://github.com/rathena/rathena/commit/70f1d864046027327ea1c316bddb835e2d6478bf**: 

* **20150411**: 

* **Renewal**: 

* **Need to remove all items from Inventory, how about Eden Group Mark ? Originally people have Eden Group Mark cannot trans or is it excluded ?**: 
  * Result: Cannot Trans 
  * Expected Result: Can Trans or exception for Eden Mark Group item ?
  * How to Reproduce: Try Rebirth in https://github.com/rathena/rathena/blob/2896d894d1ac343fba91e90c11ca53fb392b9618/npc/jobs/valkyrie.txt script
  * Official Information:
  

* **Maybe add exception for Eden Mark Group? Or is it originally blocked since inventory need to be empty.**:

**Comment by reunite-ro** [comment]
have you tried ? 
ive tried and i need to drop eden mark group (yes, I edit in item_trade.txt to make it droppable),if not, I cannot trans

**Comment by Atemo** [comment]
hmm no I didn't try yet, my answer was based on what you said

**Comment by reunite-ro** [comment]
that eden cannot be in inventory else cannot rebirth/trans
maybe check it first before label it as invalid ?

**Comment by aleos89** [comment]
Does your Eden Group Mark have a weight value? The line @Atemo linked to needs to be met for you to transcend.

**Comment by reunite-ro** [comment]
there is no weight value.. 0

**Comment by Atemo** [comment]
I can't reproduce using https://github.com/rathena/rathena/commit/c71f10508325fdd8a97a1b07ba28b845950c51b0
![screenrathena002](https://user-images.githubusercontent.com/5231893/30661993-ef407a88-9e45-11e7-91cf-18024d1c34b0.jpg)
