### ISSUE TITLE
Attack diagonally wrong position

### ISSUE THREAD

**Issue by MrAntares** [rathena/rathena#2437]
* **rAthena Hash**: 

c87dba5

* **Client Date**: 

2012-04-10

* **Server Mode**: 

RE

* **Description of Issue**: 

Scenario: Attack a target with basic attack, that is 2+ cells away (outside range).

If I attack a target from a horizontal/vertical starting position (straight line), the character moves correctly to the cell next to the target, and starts attacking it. This is working correctly.

If I attack from a diagonal starting position, the character on the client side moves to the correct position, but the server thinks it moved to a different position and sends range error messages and the character will try again to attack but again error and it will be stuck in this endless loop until we break it manually.

Here is the console log of a successful straight line attack:
https://ibb.co/iTm7g5

And here is the log of a failed attack:
https://ibb.co/kCKFZQ

As you can see, on the failed attempt, the server sent a completely wrong move data notification, it is not the same what we requested, and thus the character on the server side moved to the wrong position, while on the client side it moved to the correct position, which is quite strange.

So far it looks like the server side "moveToXY" calculation mishandles diagonal attack patterns and returns a wrong path/target cell, and thus desyncs with the client. (The client does it's own path calculation and movement) This results in not being to attack correctly from a diagonal starting point, and the player has to click on or near the target multiple times to make the attack happen.

This issue was fixed already 5 years ago, and I wrote the same issue back then. Please look into it.
(I found the old issue post in hercules's archives, since they migrated all our old issues when they forked
http://herc.ws/oldboard/tracker/issue-5688-player-movement-issue/)

**Comment by Playtester** [comment]
It's really interesting to see that already the movement info sent to the client is wrong. The movement executed on the server-side is actually correct because at the time of the attack the attacker really is at 253,75.

Is there any way to reproduce this or does this only happen randomly?

**Comment by Akkarinage** [comment]
The above screenshots can't be used for sufficient evidence as these are packet outputs from roBrowser. The sending data would be different than the official client and a great number of factors can weigh-in for this to be inaccurate.

**Comment by Playtester** [comment]
So this whole diagonal attack issue is a roBrowser thing? That would explain why none of the devs could reproduce it.
