### ISSUE TITLE
Warning Yaml

### ISSUE THREAD

**Issue by SoulBlaker** [rathena/rathena#2439]
Various warnings in Centos 7:

![image](https://user-images.githubusercontent.com/2164617/30726607-46213df6-9f22-11e7-9589-f437df3fce32.png)

**Comment by aleos89** [comment]
Please update your g++ to version 5.

**Comment by SoulBlaker** [comment]
You can send me an idea how to do this, mine is in version 4, but even I giving update does not leave it.

**Comment by aleos89** [comment]
It's in our [CentOS wiki](https://github.com/rathena/rathena/wiki/Install-on-Centos).
