### ISSUE TITLE
Sorcerer's Elemental Cure should heal for casters HP/SP%

### ISSUE THREAD

**Issue by Barigas** [rathena/rathena#2440]
I know, wording here is a bit unclear, but on officials Sorcerer's Elemental Cure removes 10% of caster's hp and sp, and gives this amount to the summoned spirit. So, if caster has 20000 hp and 1500sp, it should give 2000hp and 150sp to the elemental.
Here is not mine video from iRO, look at 7:40 timing at Agua sp, it becomes full in 2-3 casts.
https://www.youtube.com/watch?v=KCXxPMcSIXQ&feature=youtu.be&t=7m40s
To fix this, it is enough to change:
Line 10332 in skill.c 
status_heal(&ed->bl,e_hp,e_sp,3);
change to
status_heal(&ed->bl,s_hp,s_sp,3);
or somehow like this.
Revision: any

**Comment by aleos89** [comment]
For future reports, could you try to fill in the template that's provided when you open your issue. Thanks.
