### ISSUE TITLE
Shadow Refiner Cannot click

### ISSUE THREAD

**Issue by Questune09** [rathena/rathena#2444]
* **rAthena Hash**: 

rathena/npc/re/merchants/shadow_refiner.txt

* **Client Date**: 

2015

* **Server Mode**: 

Renewal

* **Description of Issue**: 
  * Result: cannot click the npc
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by crazystorm2017** [comment]
cant reproduce this error
