### ISSUE TITLE
Error Complie with gcc 4.8.5

### ISSUE THREAD

**Issue by hnomkeng** [rathena/rathena#2449]
* **rAthena Hash**: 052b9bc81976d2cd3c3930b92bcbaeb4ab5e0938
* **Client Date**: -
* **Server Mode**: Renewal
* **Description of Issue**: Complie error
* **OS**: Centos 7.x
![untitled](https://user-images.githubusercontent.com/9112684/30779085-4b406f60-a110-11e7-8f80-80920c580833.jpg)

**Comment by Daegaladh** [comment]
You just need to update to gcc 5.

**Comment by Mikegyver** [comment]
since yaml is implemented, u require gcc 5 to compile..

**Comment by hnomkeng** [comment]
I can guide update to 5.x

**Comment by Mikegyver** [comment]
u can refer on this guide.

https://github.com/rathena/rathena/wiki/Install-on-Centos
