### ISSUE TITLE
OnPCStatCalcEvent does not add stat bonuses after clicking buffer NPC

### ISSUE THREAD

**Issue by uddevil** [rathena/rathena#2450]
* **rAthena Hash**: 052b9bc81976d2cd3c3930b92bcbaeb4ab5e0938

* **Client Date**: 2015-11-04a RagexeRE

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: 
Stat bonus added with OnPCStatCalcEvent does not re-add after clicking buffer NPC (sc_start)
  * Expected Result: 
It should've re-add the bonus stat
  * How to Reproduce: 
1. Create new npc with `OnPCStatCalcEvent`
2. Add for example `bonus bAllStats,100;` on it.
3. Create buffer npc with percentheal and sc_start (I'm using default euphy's healer NPC in `npc/custom/healer.txt`)
4. Character should have all stat +100
5. Click the buffer NPC
6. Bonus stats are gone.
7. Re-Equipping any equipment will trigger `OnPCStatCalcEvent` and will give you bonus stats

Example for NPC script that i use can be seen here : [https://pastebin.com/raw/cm9asXZm](https://pastebin.com/raw/cm9asXZm)
  * Official Information:
  
None as its custom.
* **Modifications that may affect results**:

**Comment by idamonli** [comment]
This is because the player is associated with the NPC.
The OnPCStatCalcEvent failed.
This event needs to be implemented in a different way.

**Comment by Lemongrass3110** [comment]
Feature was removed in b65443d
