### ISSUE TITLE
getguildname / getguildmaster / getguildmasterid

### ISSUE THREAD

**Issue by mgksrt8** [rathena/rathena#2453]
* **d770de8015afd31be89e1b125a8c3615a0453f88**: 

* **2015/09/16**

* **Pre_Renewal**: 

* **This commands will return "null" in scripts if guild with guild ID is offline.**: 
  * Result: return "null" in script while guild is offline
  * Expected Result: return proper guild ID or guildmaster name/id
  * How to Reproduce:  create any kind of .txt file with " + getguildname( Guild_ID ) + " while guild is offline ( @reloadscript.... );

* **Modifications that may affect results**: 
  Non possible modifications may be applied to this issue.

**Comment by vstumpf** [comment]
This is because Guilds are dynamically loaded/unloaded when guild members log on/off.

As a current work-around, you could query the database directly.

**Comment by mgksrt8** [comment]
That what currently happening, will use your method instead of mine, thank you, sir.

**Comment by Lemongrass3110** [comment]
```
*requestguildinfo <guild id>{,"<event label>"};

This command requests the guild data from the char server and merrily continues
with the execution. Whenever the guild information becomes available (which
happens instantly if the guild information is already in memory, or later, if it
isn't and the map server has to wait for the char server to reply) it will run
the specified event as in a 'donpcevent' call.
```

**Comment by mgksrt8** [comment]
Thank you @Lemongrass3110 I will try to use it instead of query.
