### ISSUE TITLE
Server Randomly Crashes

### ISSUE THREAD

**Issue by mgksrt8** [rathena/rathena#2454]
* **d770de8015afd31be89e1b125a8c3615a0453f88**

* **Client Date**: 2016/09/16

* **Server Mode**: Pre-Renewal

* **Description of Issue**: bt full attached below.
  * Result: Server Crash
  * Expected Result: Long life w/o crashes
  * How to Reproduce: No information
  

* **Modifications that may affect results**: 
  extended vending system.... maybe...
Notice: ``#0  0x000055555562a161 in mob_dead () at mob.c:2736`` is already fixed ( @norare ) command.
[bt full(1).txt](https://github.com/rathena/rathena/files/1331803/bt.full.1.txt)

**Comment by vstumpf** [comment]
This program crashed in mob_dead () at mob.c:2736. If you said it's fixed, then it either isn't fixed or this is the wrong stack trace

**Comment by mgksrt8** [comment]
I fixed this line after receive this log. Let's see what will happen next. Just want to make sure that other #numbers and files like timer.c works fine.

**Comment by aleos89** [comment]
Your line doesn't match up to the current master (d9a2bdb) or [your hash](https://github.com/rathena/rathena/blob/d770de8015afd31be89e1b125a8c3615a0453f88/src/map/mob.c#L2736). I'm under the assumption it's something you've added.

**Comment by mgksrt8** [comment]
The problem was in custom commands. Sorry.
