### ISSUE TITLE
Storage become 0/0 after using new rathena folder

### ISSUE THREAD

**Issue by Questune09** [rathena/rathena#2455]
* **rAthena Hash**:  https://github.com/rathena/rathena

* **Client Date**: 20150411

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result:  after i download rathena master folder to get all new git updates and make new fresh folder i check all inventories and storages.. on inventory all works fine but when i check storage i sa image said 0 / 0 it must be 0/900 or 0/600 if empty
  * Expected Result:  must be storage 0/600 or 0/900
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment]
Check conf/inter_athena.yml which was introduced in cc1d26f. This sound like you should have some configuration error in your server log.

**Comment by aleos89** [comment]
Unable to reproduce as well.

**Comment by Questune09** [comment]
fixed thank you lemongrass

**Comment by yagami005** [comment]
> fixed thank you lemongrass

could you say how you solved the problem ??? please

**Comment by brybry022412** [comment]
how to solve?
