### ISSUE TITLE
yaml error in compiling

### ISSUE THREAD

**Issue by VCSNDBX** [rathena/rathena#2463]
rAthena: Latest
Yaml error compiling. Using Debian 7.
g++5 is not available in wheezy how to fix this

**Comment by Akkarinage** [comment]
'Latest' is not a git hash.
Use the template.
Upgrade your distribution. 
Search the Internet. 
Compile warnings are not errors.

Closing issue.

**Comment by anacondaqq** [comment]
2 minute at google: https://stackoverflow.com/questions/25147363/how-to-install-g-4-9-on-debian-wheezy-armel/3051647
