### ISSUE TITLE
Even Share Party EXP BUG after modification in inter_athena

### ISSUE THREAD

**Issue by ecdarreola** [rathena/rathena#2471]
* **rAthena Hash**:  215aa15

* **Client Date**:  2017-01-25 RagexeRE

* **Server Mode**:  Renewal

* **Description of Issue**: 
  * Result: No exp gained whenever party mates kill any monster.
  * Expected Result: There should be exp gained to other members
  * How to Reproduce: Change party_level_share to: 100 or default value 15
  * Official Information: 
  

* **Modifications that may affect results**: Modifications is moderate only. @go, max character slot, and max zeny was the only edited on this set-up. @go modified to add some maps.

**Comment by Jeybla** [comment]
`How to Reproduce: Change party_level_share to: 100 or default value 15`
The correct name for this config is `party_share_level`. Maybe you changed the name by mistake?

Also please recheck your `idle_no_share` settings.
`
// Is exp/item sharing disabled for idle members in the party?
// Set to no, or the amount of seconds (NOT milliseconds) that need to pass before considering
// a character idle.
// Characters in a chat/vending are always considered idle.
// A character's idle status is reset upon item use/skill use/attack (auto attack counts too)/movement.
idle_no_share: no `

Make sure both options belong to the correct file `party_share_level` -> `inter_athena.conf` and `idle_no_share` -> `battle/party.conf`. Thanks

**Comment by ecdarreola** [comment]
Hi Jeybla,

I changed it by mistake! Holy shiznit. Thanks!

Closed
