### ISSUE TITLE
Try Compile 64 Bit (on VS2017) got loss of data

### ISSUE THREAD

**Issue by eathenath** [rathena/rathena#2472]
Hi i tried to compile 64 bit server on vs 2017 and then i got this message

1>------ Rebuild All started: Project: libconfig, Configuration: Debug x64 ------
2>------ Rebuild All started: Project: mt19937ar, Configuration: Debug x64 ------
3>------ Rebuild All started: Project: yaml-cpp, Configuration: Debug x64 ------
2>mt19937ar.c
2>mt19937ar.vcxproj -> E:\Ragnarok Developer\Servers\rathena-mapcache\.vs\build\mt19937ar.lib
3>tag.cpp
3>stream.cpp
1>strbuf.c
1>scanner.c
1>scanner.c(941): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
1>scanner.l(182): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
1>scanner.c(1452): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
1>scanner.c(1461): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
1>scanner.c(1416): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
1>scanner.c(1430): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
1>scanner.c(1907): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
1>scanner.c(1945): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
1>scanner.c(1967): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
1>scanctx.c
1>libconfig.c
1>grammar.c
1>Generating Code...
1>libconfig.vcxproj -> E:\Ragnarok Developer\Servers\rathena-mapcache\.vs\build\libconfig.lib
1>Done building project "libconfig.vcxproj".
3>singledocparser.cpp
3>simplekey.cpp
3>scantoken.cpp
3>scantag.cpp
3>scanscalar.cpp
3>scanner.cpp
3>regex_yaml.cpp
3>parser.cpp
3>parse.cpp
3>ostream_wrapper.cpp
3>null.cpp
3>node_data.cpp
3>nodeevents.cpp
3>nodebuilder.cpp
3>node.cpp
3>memory.cpp
3>exp.cpp
3>exceptions.cpp
3>Generating Code...
3>Compiling...
3>emitterutils.cpp
3>emitterstate.cpp
3>emitter.cpp
3>emitfromevents.cpp
3>emit.cpp
3>directives.cpp
3>convert.cpp
3>graphbuilderadapter.cpp
3>graphbuilder.cpp
3>binary.cpp
3>Generating Code...
3>yaml-cpp.vcxproj -> E:\Ragnarok Developer\Servers\rathena-mapcache\.vs\build\yaml-cpp.lib
4>------ Rebuild All started: Project: common, Configuration: Debug x64 ------
4>utils.c
4>e:\ragnarok developer\servers\rathena-mapcache\src\common\utils.c(390): warning C4267: '=': conversion from 'size_t' to 'unsigned int', possible loss of data
4>e:\ragnarok developer\servers\rathena-mapcache\src\common\utils.c(391): warning C4267: '=': conversion from 'size_t' to 'unsigned int', possible loss of data
4>timer.c
4>thread.c
4>e:\ragnarok developer\servers\rathena-mapcache\src\common\thread.c(73): warning C4312: 'type cast': conversion from 'unsigned int' to 'rAthreadProc' of greater size
4>e:\ragnarok developer\servers\rathena-mapcache\src\common\thread.c(146): warning C4311: 'type cast': pointer truncation from 'void *' to 'DWORD'
4>strlib.c
4>e:\ragnarok developer\servers\rathena-mapcache\src\common\strlib.c(1025): warning C4267: 'function': conversion from 'size_t' to 'int', possible loss of data
4>e:\ragnarok developer\servers\rathena-mapcache\src\common\strlib.c(1107): warning C4244: '=': conversion from '__int64' to 'int', possible loss of data
4>e:\ragnarok developer\servers\rathena-mapcache\src\common\strlib.c(1128): warning C4244: 'initializing': conversion from '__int64' to 'int', possible loss of data
4>e:\ragnarok developer\servers\rathena-mapcache\src\common\strlib.c(1147): warning C4244: 'initializing': conversion from '__int64' to 'int', possible loss of data
4>sql.c
4>socket.c
4>showmsg.c
4>random.c
4>raconf.c
4>nullpo.c
4>mutex.c
4>msg_conf.c
4>mempool.c
4>md5calc.c
4>mapindex.c
4>malloc.c
4>grfio.c
4>ers.c
4>des.c
4>db.c
4>Generating Code...
4>Compiling...
4>conf.c
4>cli.c
4>Generating Code...
4>yamlwrapper.cpp
4>core.cpp
4>e:\ragnarok developer\servers\rathena-mapcache\src\common\core.cpp(324): warning C4244: '=': conversion from '__int64' to 'int', possible loss of data
4>Generating Code...
4>common.vcxproj -> E:\Ragnarok Developer\Servers\rathena-mapcache\.vs\build\common.lib
4>Done building project "common.vcxproj".
5>------ Rebuild All started: Project: char-server, Configuration: Debug x64 ------
5>int_storage.cpp
5>inter.cpp
5>e:\ragnarok developer\servers\rathena-mapcache\src\char\inter.cpp(653): warning C4267: '+=': conversion from 'size_t' to 'unsigned int', possible loss of data
5>e:\ragnarok developer\servers\rathena-mapcache\src\char\inter.cpp(667): warning C4267: '+=': conversion from 'size_t' to 'unsigned int', possible loss of data
5>e:\ragnarok developer\servers\rathena-mapcache\src\char\inter.cpp(733): warning C4267: '+=': conversion from 'size_t' to 'unsigned int', possible loss of data
5>e:\ragnarok developer\servers\rathena-mapcache\src\char\inter.cpp(1002): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
5>char.cpp
5>e:\ragnarok developer\servers\rathena-mapcache\src\char\char.cpp(2789): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
5>e:\ragnarok developer\servers\rathena-mapcache\src\char\char.cpp(2832): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
5>Generating Code...
5>int_quest.c
5>e:\ragnarok developer\servers\rathena-mapcache\src\char\int_quest.c(197): warning C4267: '=': conversion from 'size_t' to 'uint16', possible loss of data
5>int_pet.c
5>int_party.c
5>int_mercenary.c
5>int_mail.c
5>int_homun.c
5>int_guild.c
5>int_elemental.c
5>int_clan.c
5>int_auction.c
5>int_achievement.c
5>e:\ragnarok developer\servers\rathena-mapcache\src\char\int_achievement.c(259): warning C4267: '=': conversion from 'size_t' to 'uint16', possible loss of data
5>char_mapif.c
5>e:\ragnarok developer\servers\rathena-mapcache\src\char\char_mapif.c(316): warning C4267: '=': conversion from 'size_t' to 'uint16', possible loss of data
5>e:\ragnarok developer\servers\rathena-mapcache\src\char\char_mapif.c(566): warning C4267: '=': conversion from 'size_t' to 'uint16', possible loss of data
5>char_logif.c
5>e:\ragnarok developer\servers\rathena-mapcache\src\char\char_logif.c(192): warning C4267: '+=': conversion from 'size_t' to 'int', possible loss of data
5>e:\ragnarok developer\servers\rathena-mapcache\src\char\char_logif.c(209): warning C4267: '+=': conversion from 'size_t' to 'int', possible loss of data
5>char_cnslif.c
5>char_clif.c
5>Generating Code...
5>char-server.vcxproj -> E:\Ragnarok Developer\Servers\rathena-mapcache\char-server.exe
5>char-server.vcxproj -> E:\Ragnarok Developer\Servers\rathena-mapcache\char-server.pdb (Partial PDB)
5>Done building project "char-server.vcxproj".
========== Rebuild All: 5 succeeded, 0 failed, 0 skipped ==========

For now i can't compile that with 64 bit ?

**Comment by Jeybla** [comment]
` ========== Rebuild All: 5 succeeded, 0 failed, 0 skipped ==========`
Your build should be successful, you can safely ignore these warning for now.

**Comment by eathenath** [comment]
oh glad to hear that thankyou
