### ISSUE TITLE
[Discussion] Removing mobdb.txt (and itemdb.txt)

### ISSUE THREAD

**Issue by Jeybla** [rathena/rathena#2476]
Pasted discussion from Github and Discord:

Daegaladh:
What's the point on keeping mob and item DBs in both txt and SQL formats? I think txt support should be dropped for good.

Jey:
personally I would not go for sql files only. Simply because it's easier to read and edit yaml configurations than insert statements. But yes you are right, the current mobdb has no real benefit in comparison to its sql format.

The only benefit I can currently think of is that you can update your rathena branch without executing sql scripts every single time (since the mobdb and itemdb are changed very often).

Daegaladh:
Since txt mode was dropped, there's no real reason to mantain the 2 formats, so you should decide what format is the best and go for it.

Jey:
What is the actual downside of keeping txt and sql?

Daegaladh:
yep , that's for the rest of devs to read

Daegaladh:
well, you have to mantain the code for the 2 systems when we don't really need 2

Daegaladh:
also it could be confusing for newbies

Jey:
true, but the converter script isn't really big work. If we can save this work in maintaining headaches during reading sql statements, it's worth xD

Daegaladh:
but it would be easier for all of us to have a single system, with good performance and easy to read

Daegaladh:
sql or yaml, I don't know what's best, but just a single one please XD

Jey:
how would you make the sql version easier to read?

Daegaladh:
dunno, i think it's already pretty easy

Daegaladh:
also it would be the best for fluxcp compatibility

Jey:
exactly that's why I'd keep the sql version. For accessibility from other tools

Daegaladh:
then drop the txt XD, you need SQL to run rAthena anyways

Daegaladh:
there's no point on keeping it

Daegaladh:
what are the advantages?

Jey:
I actually dislike editing comma separated lists. And sql would be even worse :/

Daegaladh:
you can import the tables on your sql server and edit with Heidi

Jey:
Like I said: 
- Yaml would be easier to read and modify (just have a look at hercules)
- It's easy to update your rathena copy since you don't need to do a mysql query every time.

Jey:
`you can import the tables on your sql server and edit with Heidi`
This argument is invalid when it comes to merge conflicts or viewing diffs ;>

Daegaladh:
right

Akkarin:
Oh.. i didn't see you were discussing it in here. I left my two cents on the matter elsewhere lol @.@

Daegaladh:
Akky, sql alone or both? XD

Akkarin:
My two cents on https://github.com/rathena/rathena/pull/2475

Honestly, i agree with daegaladh, i don't see a reason to keep both flatfile and sql databases. We should use one or the other, and i'd prefer to keep sql. 

We get asked too often "sir gm how 2 convert txt to sql" and many idiots are making mistakes because they're adding extra/removing columns because they can't even copy/paste correctly. Using SQL also allows people to display their actual mobs via flux instead of the version they first installed and then left because "i dun no how 2 update sir gm". The mob db (and eventually the item db, i guess) moving to yaml makes it far larger in file size, albeit easier to manage, potentially more difficult to parse/convert to sql in the future, aids spoonfeeding... and i'm assuming no real gain in performance over the style we currently have in place.

Daegaladh:
:thumbsup:

Jey:
Honestly I'm not really editing the mobdb/itemdb very often. So why don't we let it decide the ppl who are actually doing that on a regular basis?

Akkarin:
About 3 years ago i posted a topic in the staff area suggesting to drop /db/ and go full MySQL, which is how most of the stuff in aegis is saved, and we're an emulator, so that's how it should be done.

Akkarin:
Needless to say, i was almost removed from the staff team lol

Daegaladh:
well I was NPC/DB dev in the past, and I'd keep the SQL only XD

Jey:
damn xD

Akkarin:
There's also no reason why we can't have the mapserver capable of running the mob/item_db.sql files, then no one needs to mysql -h -u root -p ech time they update, or load up phpmyadmin. a simple ./map-server --mergesql switch or something would suffice..

Daegaladh:
i don't think going full SQL will be a great idea in terms of performance...

Akkarin:
Most of it is just loaded and stored in memory anyway, so it makes little difference

Daegaladh:
hum, right

TheDerpySupport:
I'd like to see txt removed as well. It will remove quite a few people from using the emulator as well because the txt versions were so simple to set up and dozens of RO servers would pop up a day

Daegaladh:
txt support was removed years ago D:

Akkarin:
I'm sure he means txt dbs

TheDerpySupport:
Kinda both; I wasnt aware it was fully removed however other than lazy people being unable to work their sql tables itemDB and mobDB are sometimes outdated compared to the sql tables anyhow

Daegaladh:
yep, that's one of the points on why txt item and mob tables should be dropped

Daegaladh:
also there are lots of people in the forums and #support every day asking how to convert their tables to sql

TheDerpySupport:
They usually want to do that because a script they got needs sql tables

Daegaladh:
or to keep their fluxcp mob and item db up to date

Akkarin:
Or because they figured out the columns in phpmyadmin make it far easier to edit

**Comment by hurtsky** [comment]
this just my opinion (sorry for my grammar), i'm more prefer using txt because txt changes can do commit with git revision. while, if with sql table, you need to import to mysql each time have any changes from rathena and if someone directly changes something in sql, you will pretty hard to track it back, while with txt, we can just revert the commit.. for me it is better, to keep both txt and sql db both have good side and bad side.

**Comment by Daegaladh** [comment]
@Jeybla you forgot one last comment from @Akkarinage related to what @hurtsky says:

Akkarin:
There's also no reason why we can't have the mapserver capable of running the mob/item_db.sql files, then no one needs to mysql -h -u root -p ech time they update, or load up phpmyadmin. a simple ./map-server --mergesql switch or something would suffice..

**Comment by secretdataz** [comment]
Pasted from Discord
Secret - Today at 11:00 AM
Ok I just did a backread on the conversation here
A group of user's failure to read or their inability to execute a perl script shouldn't affect our decision
Especially when guides on how do do that is Google-able with simple keywords
If the support requests are too much for you to handle, ignore it. I'm sure most of us already do.
I'm not really sure if instead of moving over to pure SQL is better than just document the tools we provide more clearly.
For example, I got called out a day or two days ago for not providing SQL version for my item_db PR.
This means the person didn't even know our converter existed

**Comment by secretdataz** [comment]
By storing monster and item database purely in SQL, we face the same problem again.
Any changes incapable of storing in a single column have to be stored in a new table (mob_drops.txt scenario yeah?). That's counterproductive compared to converting them to YAML format and merge their property into a single file.
Also 

> Akkarin: About 3 years ago i posted a topic in the staff area suggesting to drop /db/ and go full MySQL, which is how most of the stuff in aegis is saved, and we're an emulator, so that's how it should be done.

I think that's rAthena's goal misinterpreted. We aim to emulate official server's behavior, but emulating a backend behavior that won't even affect any player shouldn't be our goal. Should we duplicate script codes like official servers do too? No?

**Comment by Jeybla** [comment]
So I think we all agreed on dropping the txt format and either use SQL, YAML or both. The following comparison does not include our current txt format. If I'm missing some major arguments, please just add/edit them.

**SQL only:**

| Pro | Contra |
|-----|:------:|
| + Nearly nothing needs to be done, just remove the txt code from rathena. | - The database isn't that nice to review/merge. Creating a tool for that would likely be a hard task. |
| + We could use database editors to maintain the the db. | - Using Editors isn't that handy and not all db editors are available on every system and setting up fluxcp for that, takes a bit time. |
|  | -- Bad when you often change branches. |


**SQL only, but with a autoconverter script from YAML:**

| Pro | Contra |
|-----|:------:|
| ++ Easy to read, modify, merge, review without any additional software | -- Bad when you often change branches. |


**Both with a converter YAML to SQL:**

| Pro | Contra |
|-----|:------:|
| ++ Easy to read, modify, merge, review without any additional software | - rathena needs to maintain both formats. |

**YAML only:**

| Pro | Contra |
|-----|:------:|
| ++ Easy to read, modify, merge, review without any additional software | - Worse accessibility from other tools like FluxCP |

The following could be avoided if we offer a converter to SQL:
(The converter doesn't need to push to the master)
- FluxCP needs to be adjusted
- FluxCP would have two connections with rathena. One SQL and another YAML reader. We should avoid that redundancy.

---------------------------------------
I removed some arguments belonging to unexperienced users like "SQL isn't updated properly" or "there are many questions about how to convert custom monsters". I think these problems can be solved with better documentation and easy-to-use scripts.

**Comment by Playtester** [comment]
Well, I personally like the CSV format still the most. Once you know how to set up your spreadsheet programs properly you can edit and overview stuff fastest with it.

I honestly would rather drop those SQL insert files and make the code automatically create SQL statements from the txt file.

But since I'm not working on the DB anymore, I guess I shouldn't care. Better ask those that have to update DB files frequently.

**Comment by Jeybla** [comment]
@Playtester is right. It mostly depends on personal preference. Maybe we should provide csv, yaml and sql!

Jokes aside, if we'd go for automatically fetching infos from divine pride: What would be the best format to view differences?

**Comment by anity99** [comment]
I think YAML is the best way

**Comment by Jeybla** [comment]
It seems like there is no real benefit in changing the current system. Any option is disliked either way. SQL-Only is disliked because of the branch-changing issue. YAML would break with a lot old stuff and backward compatibility for personal preferences of a few. So the best way is to just stick with the good old csv and sql system.
