### ISSUE TITLE
Script command "setunitdata" output unproper warning that halt the script

### ISSUE THREAD

**Issue by Yuchinin** [rathena/rathena#2489]
* **rAthena Hash**: ba7a766472396c046d1e42c675910707845a97f6

* **Client Date**: -

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: setunitdata output invalid object type warning that halt the script
  * Expected Result: It shouldn't output the error since monster is a valid object type.
  * How to Reproduce: try spawn a monster and use setunitdata on it
  * Official Information:-
  

* **Modifications that may affect results**: 
  There is missing object type case in line 18153 of script.cpp that should be BL_MOB, this warning introduce on this commit. 
https://github.com/rathena/rathena/commit/fb882c4aa09af17992f5073f1f32566d9ff7e21f
Which claim to fix a couple warning but actually doing the opposite. @rpdigos Sorry bro. ^^"

**Comment by Jeybla** [comment]
`case BL_MOB:  md = map_id2md(bl->id); break;`
BL_MOB is in this switch case. I'll retest it. Thanks for the report!
