### ISSUE TITLE
doevent + npc_checknear

### ISSUE THREAD

**Issue by Lemongrass3110** [rathena/rathena#249]
I tried to trigger a NPC(normal) from another NPC(hidden: -1) by doing doevent "UnhiddenNPC::Label".
But after the first dialog showed up the NPC hangs up and the mapserver tells me:
"[Warning]: npc_scriptcont: failed npc_checknear test."

I guess this check should not be run, if you are talking to another NPC in reality.

**Comment by Luciar** [comment]
This is purely a source issue. I removed the script tag to keep core and actual script issues separate

**Comment by LingLingYang** [comment]
failed npc_checknear

**Comment by Lemongrass3110** [comment]
Cant remember the exact script anymore, but worked fine with my test today.
Closing this for now.

**Comment by anacondaqq** [comment]
Hmm, as i remember this issue happened when you try to call any NPC with doevent while monster hitting you.
