### ISSUE TITLE
rathena fresh install make server error

### ISSUE THREAD

**Issue by Rin-EirServers** [rathena/rathena#2491]
Hash: ff6722c

When trying to make server, this occured (fresh install)

`status.c:14241:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (yamlwrapper* type = yaml_iterator_first(it); yaml_iterator_has_next(it); type = yaml_iterator_next(it)) {
   ^
status.c:14241:3: note: use option -std=c99 or -std=gnu99 to compile your code
status.c:14275:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (yamlwrapper* level = yaml_iterator_first(it); yaml_iterator_has_next(it); level = yaml_iterator_next(it)) {
   ^
status.c:14298:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int refine_level = 0; refine_level < MAX_REFINE; ++refine_level) {
   ^
status.c: In function ‘status_yaml_readdb_refine’:
status.c:14327:2: error: ‘for’ loop initial declarations are only allowed in C99 mode
  for (int i = 0; i < ARRAYLENGTH(labels); i++) {
`

**Comment by Jeybla** [comment]
`Install g++ version 5 or later`
