### ISSUE TITLE
Wrong database equip location of Sarah's Left Earring and Right Earring 

### ISSUE THREAD

**Issue by Yuchinin** [rathena/rathena#2493]
* **rAthena Hash**: ba7a766472396c046d1e42c675910707845a97f6

* **Client Date**: -

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result:  [Sarah's Left Earring](http://db.irowiki.org/db/item-info/28310/) become false when use (getequipid(EQI_ACC_L)==28310) and true when (getequipid(EQI_ACC_R)==28310)
  * Expected Result: (getequipid(EQI_ACC_L)==28310) should return true
  * How to Reproduce: Just equip the Sarah's Left Earring and run -->(getequipid(EQI_ACC_L)==28310?"Left Equipped":"Not Equip")
  * Official Information: I assume that iro db should be true so I think maybe the constant value of EQI_ACC_L
and EQI_ACC_R are getting reversed or equip location of this two item are reversed in item db
  

* **Modifications that may affect results**: -

**Comment by Jeybla** [comment]
![image](https://user-images.githubusercontent.com/6203894/31325301-c799438c-acbb-11e7-9c2d-8689393624d7.png)

Considering the `right hand` is on the left side of the equipment window, I'd say the `left accessory` should be on the right side of the equipment window. Therefore we just should change the items position.
