### ISSUE TITLE
SO_VACUUM_EXTREME behavior not correct

### ISSUE THREAD

**Issue by esu1214** [rathena/rathena#2497]
rAthena Hash:
7351b88
Client Date: 20170125
Server Mode: renewal
Description of Issue:
Players will be sucked to the center of UNT_VACUUM_EXTREME if nearby in Aegis server.
But players only stop walk instead in rA.

**Comment by aleos89** [comment]
Confirmed also that players with no knock back items (IE: Strong Shield) are still sucked into the center.
