### ISSUE TITLE
SC_BOSSMAPINFO behavior not correct

### ISSUE THREAD

**Issue by esu1214** [rathena/rathena#2498]
rAthena Hash:
7351b88
Client Date: 20170125
Server Mode: renewal
Description of Issue:
Players will be see boss location in minimap when the tomb disappeared in Aegis server if they have used 12214 and SC_BOSSMAPINFO not time out.
But players cannot see boss location when the tomb disappeared in rA.

**Comment by aleos89** [comment]
Confirmed. I remember this being a bug from the old forum bug tracker.

Essentially the issue is that if you use a Convex Mirror before an MVP respawns, it won't show the Boss Icon on the minimap. You have to consume another Convex Mirror to make it show up.

**Comment by esu1214** [comment]
Yes, correct.
