### ISSUE TITLE
Group Level 0 can't buy from itemshop. Group Level 99 can

### ISSUE THREAD

**Issue by Mickosis** [rathena/rathena#2503]
* **rAthena Hash**: fa425b834

* **Client Date**: 2012-04-10a

* **Server Mode**: Pre-Renewal

* **Description of Issue**: GM Level 99 are allowed to get items from the itemshop. It displays the item amount properly on [PlayerName]'s Points. While level 0 accounts only display 0 points even if they have the right items.

* **Modifications that may affect results**: I am using the Extended Vending System.

**Comment by aleos89** [comment]
Is your sell item a bound item type?

**Comment by Mickosis** [comment]
@aleos89 I tried item 7179 and 7539 already. If bound = untradable it is not bound to account. I also played around with the setting as well, there was no change

**Comment by Mickosis** [comment]
Here are screenshots of a group level 99 and a 0
![test](https://user-images.githubusercontent.com/9798878/31576134-839f2b36-b127-11e7-8578-31e50e7268b0.png)
![test2](https://user-images.githubusercontent.com/9798878/31576133-83805e18-b127-11e7-869c-dfb8a13d6b6a.png)

**Comment by cydh** [comment]
I just tested item shop by using Poring Coin (6480) and the cash always be 0, because it send cannot be sold to NPC.
Then changed the item to Jellopy (909) and Proof of Donation (7179), working properly.
Tested by using lv 0 and 99.

**Comment by Mickosis** [comment]
Do we expect the "cannot be sold to NPCs" flag on item_trade to affect itemshops?

**Comment by cydh** [comment]
Yes, cannot be sold to NPC will prevent the item from itemshop. Just remove that flag, and you are free to set it as account bound (by item_trade flags not by getitembound if by bound you need change the config)

but well, u have the point. In case "I want to set Jellopy for itemshop buying, but I don't want to player sell it to NPC". (because set to the item cannot be sold to NPC will ignore the item listing when open sell list to NPC, I need that).

**Comment by Mickosis** [comment]
I'd want the currency to be tradable, but cannot be sold to NPCs though. Do we have a way for that?

**Comment by aleos89** [comment]
Well, I guess since this is a custom feature, we can adjust this to how we want. I could add another config (or combine it with the bound one) for sell-able items.

**Comment by Mickosis** [comment]
That would be nice, @aleos89. That way we can set it to cannot be sold to NPCs and still be a redemption currency.
