### ISSUE TITLE
advanced_refiner issues

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#2505]
i was test 

why i can refine without VIP, without item need like oridecon,., just need equip and FREE up to +7 safe why?

shinubi on payon, can refine without any item needed and without zeny.. any item can refine FREE up to +7...

* **rAthena Hash**: 57113d1

* **Client Date**: 20170517

* **Server Mode**: RENEWAL

* **Description of Issue**: 
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Can you please provide the information in the form that you skipped? It's impossible for us to just guess these things.

**Comment by mazvi** [comment]
client date 20170514 the issue is shinubi on payon

**Comment by crazystorm2017** [comment]
I can confirm that suhnbi from payon does refine even without the necessary stones for refining. :)

**Comment by mazvi** [comment]
i was try on my server with lates revision. there was sinubi payon refine without item like enrich stone or zeny and safe upto +7 include headgear.. i dont know why.. but refine RE on malangdo is normal...

**Comment by cydh** [comment]
yes totally confirmed just by reading the script.

**Comment by cydh** [comment]
lol stupid low, abuse it player!!!

**Comment by cydh** [comment]
lol stupid low.

@mazvi @crazystorm2017 can you test this?
```Diff
diff --git a/npc/merchants/advanced_refiner.txt b/npc/merchants/advanced_refiner.txt
index 63f01c8..7b2572e 100644
--- a/npc/merchants/advanced_refiner.txt
+++ b/npc/merchants/advanced_refiner.txt
@@ -58,6 +58,8 @@ payon,157,146,6	script	Suhnbi#cash	85,{
 	.@price = getequiprefinecost(.@part, REFINE_COST_ENRICHED, REFINE_ZENY_COST);
 	.@material = getequiprefinecost(.@part, REFINE_COST_ENRICHED, REFINE_MATERIAL_ID);
 
+	callsub S_RefineValidate,getequipweaponlv(.@part),.@price,.@price,.@part;
+
 	mes "[Suhnbi]";
 	mes "Clang! Clang! Clang!";
 	if (getequippercentrefinery(.@part, true) > rand(100)) {
```

**Comment by secretdataz** [comment]
@cydh In case you didn't read [Contributing.md](https://github.com/rathena/rathena/blob/master/.github/CONTRIBUTING.mdl). This bug doesn't make rAthena unusable or unstable.

**Comment by cydh** [comment]
then I must questioning ur sense of unstable.

**Comment by mazvi** [comment]
thanks very much @cydh you hero of all private server, because all player can use this bug to get rich, and make unbalance on game system...

**Comment by cydh** [comment]
edited, I double write `.@price` that must be `.@material`

**Comment by mazvi** [comment]
![screenchaos617](https://user-images.githubusercontent.com/8316103/31575346-9d846322-b10e-11e7-9fed-51440511d58d.jpg)

thanks very much @cydh i can confirm your script work on my vps
