### ISSUE TITLE
merchants/refine.txt can't determine safety level of equipment

### ISSUE THREAD

**Issue by Mickosis** [rathena/rathena#2507]
* **rAthena Hash**: fa425b834

* **Client Date**: 2012-04-10a

* **Server Mode**: Pre-Renewal

* **Description of Issue**: Refiner (Pront refiner for example) can't determine the safety limits of equipments. Repro steps:

1. Set callfunc of Refiners to condition 1 (multiple refiner)
2. Talk to the NPC, refine a +0 Armor to +4

Expected: NPC will confirm if refine to safe limit or refine how many times
Actual: NPC asks how many times to refine, putting 4 times will warn the user that 4 times there will be a chance to break the armor (where in reality it is 100% refine rate)

* **Modifications that may affect results**: N/A

**Comment by cydh** [comment]
The `.@safe` set were removed since this updates, idk if it was dev decision or maybe there was idea to make auto-get-safe refine value on that update (but forgot to add), idk.
https://github.com/rathena/rathena/commit/e24d30a7113835f9c33f0fb51b89acfb7e00882f#diff-f04dee36a98c3d36b1faa3666691fb46L616

but in case you need quick fix, try this.
```Diff
diff --git a/npc/merchants/refine.txt b/npc/merchants/refine.txt
index 176b8ac..231fa45 100644
--- a/npc/merchants/refine.txt
+++ b/npc/merchants/refine.txt
@@ -611,10 +611,19 @@ function	script	refinemain	{
 	.@refinerycnt = getequiprefinerycnt(.@part); //save refinery count
 	.@price = getequiprefinecost(.@part, REFINE_COST_NORMAL, REFINE_ZENY_COST);
 	.@material = getequiprefinecost(.@part, REFINE_COST_NORMAL, REFINE_MATERIAL_ID);
+	.@wlvl = getequipweaponlv(.@part);
+
+	.@safe = 4;
+	switch (.@wlvl) {
+		case 1: .@safe = 7; break;
+		case 2: .@safe = 6; break;
+		case 3: .@safe = 5; break;
+		case 4: .@safe = 4; break;
+	}
 
 	// If the VIP system is enabled, the prices for non-VIP players are considerably higher.
 	if (VIP_SCRIPT && !vip_status(VIP_STATUS_ACTIVE)) {
-		switch(getequipweaponlv(.@part)) {
+		switch(.@wlvl) {
 			case 0: .@price = .@price * 10; break;
 			case 1: .@price = .@price * 40; break;
 			case 2: .@price = .@price * 50; break;
```

**Comment by Mickosis** [comment]
Thank you @cydh. Looping in @secretdataz to confirm if intended.

Will try the fix as soon as I can, I do not have a test server currently.
