### ISSUE TITLE
SC_BOSSMAPINFO cause mapserver crash

### ISSUE THREAD

**Issue by esu1214** [rathena/rathena#2509]
Mapserver crash as I just update SC_BOSSMAPINFO Issue.
Breakpoint callstack at status.c
clif_bossmapinfo(sd, map_id2boss(sce->val1), BOSS_INFO_ALIVE_WITHMSG);

**Comment by aleos89** [comment]
Once again, please follow the template provided.

Your clif function is missing a parameter compared to the recent update (951ff55). I would highly suspect it's something on your end.

**Comment by Jeybla** [comment]
I'm unable to reproduce it, can you provide more informations? Thanks

**Comment by esu1214** [comment]
Maybe is the msg_conf miss updating.

**Comment by esu1214** [comment]
Maybe is the msg_conf miss updating.

**Comment by esu1214** [comment]
Maybe is the msg_conf miss updating.
