### ISSUE TITLE
Wagjak Refine

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#2510]
* **rAthena Hash**: db37fc7

* **Client Date**: 20170517

* **Server Mode**: RENEWAL

* **Description of Issue**: 

This is not issue but this is a suggestion. 

how to refine wagjak connected with refine_db.yml. is this necessary or not? because surely there will be inequality if the general refine using refine_db.yml and wagjak not.

for example price of wagjak vs normal refine in prontera in.

refine in prontera in use refine_db.yml

thank you

  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by cydh** [comment]
Wagjak from Novice academy? It's still 'hardscripted' and if the suggestion to move them to refine_db.yml, well it's somewhat possible.
Just like Malangdo's Hollink (against Suhnbi), the different is the prices. But well, if the idea to remove 'hardcsripted' prices & materials from scripts, can be added.

**Comment by mazvi** [comment]
Yes, make wagjak become one with refine_db.yml I think is an efficient thing. But this is not too important or urgent, just a suggestion :)
