### ISSUE TITLE
bindatcmd Abuse

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#2513]
* **rAthena Hash**: 48fcc92

* **Client Date**: 20170517RE

* **Server Mode**: RENEWAL

* **Description of Issue**: 
  * Result: 
When a player uses the npc bindatcmd script. they can use the # sign to disturb other players. For example player A can be disturbing player B using # command from bindatcmd NPC script.
  * Expected Result: 
bindatcmd, as its name AT should be only with @, players are not allowed to use # to minimize disturbing other players.
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Daegaladh** [comment]
That's up to you to set the levels correctly, for instance:
`bindatcmd "security",strnpcinfo(3)+"::OnAtcommand",0,100;`
level 0 for @ and 100 to disable #

**Comment by Lemongrass3110** [comment]
@Daegaladh since char command level is optional and default value is 0 it might be better to optimize it by setting default to 100. At least for char command.

**Comment by mazvi** [comment]
I make command for all player.. but the problem is user can use # to disturbing other people

**Comment by mazvi** [comment]
Oh thx vvery much @daegaladh i will try
