### ISSUE TITLE
Elemental Converter does not display the icon

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#2516]
* **rAthena Hash**: 48fcc92

* **Client Date**: 20170517RE

* **Server Mode**: RENEWAL

* **Description of Issue**: 
  * Result: 

Elemental Converter Work but does not display the icon

12114,Elemental_Fire,Elemental Converter,11,2,,10,,,,,0xFFFFFFFF,63,2,,,,,,{ itemskill "ITEM_ENCHANTARMS",4; },{},{}
12115,Elemental_Water,Elemental Converter,11,2,,10,,,,,0xFFFFFFFF,63,2,,,,,,{ itemskill "ITEM_ENCHANTARMS",2; },{},{}
12116,Elemental_Earth,Elemental Converter,11,2,,10,,,,,0xFFFFFFFF,63,2,,,,,,{ itemskill "ITEM_ENCHANTARMS",3; },{},{}
12117,Elemental_Wind,Elemental Converter,11,2,,10,,,,,0xFFFFFFFF,63,2,,,,,,{ itemskill "ITEM_ENCHANTARMS",5; },{},{}
  * Expected Result: 

Elemental Converter Work and display the icon

i think this item db below is solutions

12114,Elemental_Fire,Elemental Converter,2,2,,10,,,,,0xFFFFFFFF,63,2,,,,,,{ sc_start SC_FIREWEAPON,600000,1; },{},{}
12115,Elemental_Water,Elemental Converter,2,2,,10,,,,,0xFFFFFFFF,63,2,,,,,,{ sc_start SC_WATERWEAPON,600000,1; },{},{}
12116,Elemental_Earth,Elemental Converter,2,2,,10,,,,,0xFFFFFFFF,63,2,,,,,,{ sc_start SC_EARTHWEAPON,600000,1; },{},{}
12117,Elemental_Wind,Elemental Converter,2,2,,10,,,,,0xFFFFFFFF,63,2,,,,,,{ sc_start SC_WINDWEAPON,600000,1; },{},{}

  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by anacondaqq** [comment]
These statutes do not have status icons. If you saw it on some server, this is totally custom modification.

**Comment by mazvi** [comment]
thanks very much, so on the official server like iRO there was no icon?

**Comment by aleos89** [comment]
Correct. These status icons were removed years ago.
