### ISSUE TITLE
Mora Enchant - Gear Break Bug

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#2519]
* **rAthena Hash**: 
e92fc96

* **Client Date**: 
2016-02-03aRagexeRE

* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result: Gear can break during the second enchantment process.
  * Expected Result: Failure during second enchantment process shall only erase all enchantments and not break the gear.
  * How to Reproduce: Following NPC is affected: mora,152,97,5	script	Guardian of Power#pa082

I'm not sure but it looks to me as if the script falls into the 		delequip .part;
Even though the enchantment was a success?!
If i'm not mistaken then delequip will delete the gear.

  * Official Information:
http://irowiki.org/wiki/Mora_Enchants#Artifact_Researcher_.28Ranger.2C_Guillotine_Cross_.26_Rune_Knight.29
  

* **Modifications that may affect results**: 
None

**Comment by Atemo** [comment]
The rates for all 2nd enchants seem fine.
I don't have any issue enchanting White_Wing_Suits for 2nd time.

Which gear are you trying to enchant?

**Comment by Everade** [comment]
@Atemo 
White Wing Suit

**Comment by Everade** [comment]
re-tested, can not confirm, must have been failing during the third attempt.
closed
