### ISSUE TITLE
SG_FUSION is missing spirit skill label in db/skill_db.txt

### ISSUE THREAD

**Issue by Akaineko-astasi** [rathena/rathena#2520]
* **rAthena Hash**: b4106eb

* **Client Date**: 

* **Server Mode**: Both Re and Pre-Re

* **Description of Issue**: 
  * Result:  
`444,0,6,4,0,0x1,0,1,1,no,0,0,0,misc,0,0x0,		SG_FUSION,Union of the Sun Moon and Stars`
There is no way to obtain the skill now.

  * Expected Result:  
`444,0,6,4,0,0x1,0,1,1,no,0,0x8,0,misc,0,0x0,		SG_FUSION,Union of the Sun Moon and Stars` 
Union should be a Spirit skill.

  
* **Modifications that may affect results**: none

**Comment by sader1992** [comment]
as i know Union need 1 skill point if you didn't put 1 skill point in it it wont work
to it's usable but it requirement is spirit (like the gemstones for other skills)

example :
496,0,6,4,0,0x1,0,1,0,no,0,0x8,0,none,0,0x0,		AM_TWILIGHT1,Twilight Alchemy 1

459,0,6,4,0,0x3,-1,1,1,no,0,0x8,0,weapon,0 ,0x4000,	BS_ADRENALINE2,Advanced Adrenaline Rush

those skill will be open as soon as you meet the requirement no need for skill points but the spirit will make them usable

this what i think the (0x00008 - spirit skill) part is which i maybe wrong

**Comment by aleos89** [comment]
According to the source for Union, there's a spirit check while casting the skill. As @sader1992 stated, there's a unique case for this skill where it requires the player to put a skill point into the skill and then be Soul Linked for it to work.

**Comment by aleos89** [comment]
Confirmed on b4106eb that it matches Aegis behavior.
