### ISSUE TITLE
Suggestion: Floating Tax Vending

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#2528]
* **rAthena Hash**: b4106eb

* **Client Date**: 20170517RE

* **Server Mode**: RENEWAL

* **Description of Issue**: 
  * Result: The tax vending on rAthena is STATIC can set by 2% for example
  * Expected Result: The tax vending is floating like 20170517 Client side view please check screenshot
  * How to Reproduce: 
  * Official Information: Check screenshot
  

* **Modifications that may affect results**: 
  
  

![screenchaos806](https://user-images.githubusercontent.com/8316103/31725000-79cee514-b44d-11e7-9432-a48ce07c24da.jpg)
![screenchaos803](https://user-images.githubusercontent.com/8316103/31724562-4f41d28a-b44c-11e7-8fa6-e2f778786db7.jpg)
![screenchaos804](https://user-images.githubusercontent.com/8316103/31724563-4f9327ca-b44c-11e7-83a1-583d510c6bbd.jpg)
![screenchaos805](https://user-images.githubusercontent.com/8316103/31724564-4fda6b3a-b44c-11e7-8913-e148a6d9e0df.jpg)
![screenchaos807](https://user-images.githubusercontent.com/8316103/31725012-829618a2-b44d-11e7-8561-b07eadb6c3b4.jpg)
![screenchaos808](https://user-images.githubusercontent.com/8316103/31725014-82d92318-b44d-11e7-9a28-c67a647003fd.jpg)

**Comment by anacondaqq** [comment]
```c
if(price >= 900000000) tax = 10;
else if(price >= 100000000) tax = 8;
else if(price >= 10000000) tax = 6;
else if(price >= 1000000) tax = 4;
else if(price >= 100000) tax = 2;
else if(price >= 10000) tax = 0;

```

interesting,..

**Comment by aleos89** [comment]
Here are my tests on kRO:
![100000](https://user-images.githubusercontent.com/3521753/33042504-1a9eb48e-ce10-11e7-9259-414eb319900e.PNG)
![1000000](https://user-images.githubusercontent.com/3521753/33042518-1e02590a-ce10-11e7-9126-c6fbbe3f86cf.PNG)
![10000000](https://user-images.githubusercontent.com/3521753/33042522-1fe320d8-ce10-11e7-8cfd-fefe59a39642.PNG)
![100000000](https://user-images.githubusercontent.com/3521753/33042526-22037e44-ce10-11e7-80e2-37e47c01cba4.PNG)
Seems like there's no taxes until you reach 100,000,000 Zeny which incurs a 5% tax.

**Comment by mazvi** [comment]
where to find this modified on client side?

**Comment by aleos89** [comment]
I'm not sure. I don't use a newer client (still on 2015) so I wasn't even aware that new GUI existed in the vending window.

**Comment by mazvi** [comment]
iam using 2017-05-17 client on above,
