### ISSUE TITLE
Cart Termination: Race Cards

### ISSUE THREAD

**Issue by raynra** [rathena/rathena#253]
Git Hash/Date: 1f147f207d0f323cd6dcfe6f8fc36ea99fdd5fa7 / Jan-26-2015
Client Date: 2013-08-07a
Description:

http://irowiki.org/wiki/High_Speed_Cart_Ram
http://ragnarok.wikia.com/wiki/Cart_Termination
http://forums.warpportal.com/index.php?/topic/169843-cart-termination-and-cards/

Cart Termination, according to iRO Wiki, is not supposed to be affected by race cards.
However, Wikia page, and WarpPortal forum posts states that it is affected by race cards.
Tested on AEGIS 13.3 - affected by race cards. Not sure if this changed in newer episodes

**Comment by anacondaqq** [comment]
> Tested on AEGIS 13.3
Give me a link where i can get AEGIS 13.3?)

**Comment by cydh** [comment]
well, if that skill is "ignore Race & Size" adjustment, I think if there are skills like that, better we add skill flag (inf2/3), if not, hardcoded is fair enough

**Comment by cydh** [comment]
>**Only items and cards that increase ATK directly affect the damage of this skill**. Percent items and cards like Racial and Size cards (ignoring the ATK gained from Size cards), The Sign, Zealotus Mask and the Turtle General card do not affect this skill.

only additive value that increase the damage?

**Comment by darhylism** [comment]
Turtle general card affect cart termination damage on Git Hash: [e7e9cf6](https://github.com/rathena/rathena/commit/e7e9cf6d7333345d0e11d9f0bf9f1badb6ff3cd9)

it should not

**Comment by flamefury** [comment]
There was a recent test on kRO Sakray which in my opinion proves that it is supposed to be affected:
https://imgur.com/a/6oD92

Results

- No carded Knife - consistently 2 damage.
- Triple Scorpion Carded Knife - consistently 3 damage.

You can see the exact same cart weight, stats and equipment other than the knife between each image.
