### ISSUE TITLE
Warning on status.c

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#2532]
* **rAthena Hash**: caf3152

* **Client Date**: 20170517RE

* **Server Mode**: RENEWAL

* **Description of Issue**: Please check Screenshot
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**: 
  
  

![warning](https://user-images.githubusercontent.com/8316103/31805402-a1843954-b58a-11e7-82ae-2acca476e636.PNG)

**Comment by ecdarreola** [comment]
Remove the ";" to avoid warning.

e.g. 	change below
```
if(sc->data[SC_CHEERUP]);
		vit += 3;
```
to
```
if(sc->data[SC_CHEERUP])
		vit += 3;
```

See if it works.
