### ISSUE TITLE
 [URGENT] BUG (PLEASE HELP ME!)

### ISSUE THREAD

**Issue by felgate11** [rathena/rathena#2536]
**Good day everyone!** I'm new here and I have this problem. I ran the **server** and the **scripts** successfully. On the first launch - **both** Ragnarok clients' characters can be **played together**, after i logged out the other account and tried to create a new one but it seems that i **can't** make them together again even how many times i tried and logged back the other account, but no chance. Why is that? Please help me.

![screenshot 729](https://user-images.githubusercontent.com/23493289/31852769-6b3cdeba-b6b0-11e7-8481-fc6b864b22eb.png)
![screenshot 730](https://user-images.githubusercontent.com/23493289/31852771-6ccea6fa-b6b0-11e7-857c-8c850cda3fa5.png)
![screenshot 731](https://user-images.githubusercontent.com/23493289/31852772-6d36ef8a-b6b0-11e7-9f81-6ee4dd1e7402.png)

**Comment by Daegaladh** [comment]
Please write a proper title and follow the issue template.

**Comment by felgate11** [comment]
Can't you see? I'm new here and I'm asking. How rude.

**Comment by aleos89** [comment]
You're on a novice map. As it works on official, players have a chance of starting on a different map.

**conf/char_athena.conf**
```
// Starting point for new characters
// Format: <map_name>,<x>,<y>{:<map_name>,<x>,<y>...}
// Max number of start points is MAX_STARTPOINT in char.h (default 5)
// Location is randomly picked on character creation.
// NOTE: For Doram, this requires client 20151001 or newer.
start_point: iz_int,18,26:iz_int01,18,26:iz_int02,18,26:iz_int03,18,26:iz_int04,18,26
start_point_pre: new_1-1,53,111:new_2-1,53,111:new_3-1,53,111:new_4-1,53,111:new_5-1,53,111
start_point_doram: lasa_fild01,48,297
```
If you don't want your players starting on different maps just remove these down to 1 map.

**Comment by Questune09** [comment]
if you want to make all players spawn only on 1 map just choose one of this maps

start_point: iz_int,18,26:iz_int01,18,26:iz_int02,18,26:iz_int03,18,26:iz_int04,18,26

example change it to

start_point: iz_int,18,26

the player when join the server they will be warp only at iz_int,18,26 location

dont forget to recompile

**Comment by secretdataz** [comment]
You don't have to recompile after you change the spawn config.

**Comment by Questune09** [comment]
ooops sorry hahahah i forgot its not src configuration XD
