### ISSUE TITLE
How to make all my Ragnarok game clients/characters on the same map?

### ISSUE THREAD

**Issue by felgate11** [rathena/rathena#2538]
* **rAthena Hash**: I don't know what to put, I'm a total newbie here. So please don't be rude and close my issue.

* **Client Date**: 

* **Server Mode**: 

* **Description of Issue**: Characters are on the different maps.
![screenshot 729](https://user-images.githubusercontent.com/23493289/31853038-c3a5a2ea-b6b4-11e7-8465-a521e53aee05.png)
![screenshot 730](https://user-images.githubusercontent.com/23493289/31853039-c3f93f72-b6b4-11e7-8395-225f59c9b9e5.png)
![screenshot 731](https://user-images.githubusercontent.com/23493289/31853040-c43c49e8-b6b4-11e7-9992-ae95a770d861.png)

  * Result: I ran the server and the scripts successfully. On the first launch - both Ragnarok clients' characters can be played together, after i logged out the other account and tried to create a new one but it seems that i can't make them together again even how many times i tried and logged back the other account, but no chance. Why is that? Please help me. They are on the different maps.
  * Expected Result: I want my characters to be on the same map, start point, channel or what you called it.
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by secretdataz** [comment]
Use the forum for this kind of question.
