### ISSUE TITLE
Mapflag Teleport Problem

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#2543]
* **rAthena Hash**: cb760a0

* **Client Date**: 20170517RE

* **Server Mode**: RENEWAL

* **Description of Issue**: 

Iam usng seting mapflag like below
prt_prison	mapflag	nomemo
prt_prison	mapflag noteleport
prt_prison	mapflag nowarpto
prt_prison	mapflag nowarp

i think the problem is iam using multi mapflag on here

  * Result:  the character can flywing
  * Expected Result: the character canot flywing
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment]
Any info why you closed this?

**Comment by mazvi** [comment]
i dont know, i copy paste the mapflag again and work normaly i think the problem is tab or space iam sorry
