### ISSUE TITLE
St Patrick Hat (18565) & Green Ale (12135) possible bug

### ISSUE THREAD

**Issue by uddevil** [rathena/rathena#2547]
* **rAthena Hash**: c7d5b61409377d5b9e094f2c95326dad1fe0a85b

* **Client Date**: 2015-11-04aRagexeRE

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: 

1. St Patrick Hat (18565) Script :
`bonus bStr,1; bonus bInt,1; bonus bMdef,4; `**if(getrefine()>6)**`{ bonus2 bAddMonsterDropItem,12135,50;`

2. Item delay missing on Green Ale (12135)

  * Expected Result: 
1. For St Patrick Hat, from divine-pride description, it should be +8 minimum to drops Green Ale
![chrome_2017-10-26_21-53-42](https://user-images.githubusercontent.com/10105610/32060405-da18d1fe-ba98-11e7-95cd-4466e6237c27.png)
[https://www.divine-pride.net/database/item/18565/st-patricks-hat-1](https://www.divine-pride.net/database/item/18565/st-patricks-hat-1)

2. For Green Ale, from divine-pride description, it should have 3 seconds delay
![chrome_2017-10-26_21-53-49](https://user-images.githubusercontent.com/10105610/32060569-4c38c280-ba99-11e7-9885-d951e971f0b0.png)
[https://www.divine-pride.net/database/item/12135/green-ale](https://www.divine-pride.net/database/item/12135/green-ale)

  * How to Reproduce:  Check with `@item` 18565, and 12135
  * Official Information: I don't know in kRO or iRO, i'm using divine-pride as source.
  

* **Modifications that may affect results**: 
  
  
1. db/(pre)-re/item_db.txt
Change St Patrick Hat (18565) script to :
`bonus bStr,1; bonus bInt,1; bonus bMdef,4; `**if(getrefine()>7)**`{ bonus2 bAddMonsterDropItem,12135,50;`

2. Add delay for Green Ale (12135) in db/(pre)-re/item_delay.txt

**Comment by aleos89** [comment]
According to the itemInfo.lua, it says the delay for the Green Ale is 10 seconds:
```lua
		identifiedDescriptionName = {
			"A wonderfully",
			"refreshing drink that",
			"may cause stumbling",
			"and regrettably hazy",
			"memories of the night",
			"before when drank in",
			"excess. Recovers 50%",
			"of MaxHP and SP, but",
			"has a 10% chance of",
			"casting the Confuse",
			"effect on its user.",
			"This can be consumed 10 seconds after each use.",
			"^FFFFFF_^000000",
			"Weight:^006600 25^000000"
		},
```
