### ISSUE TITLE
Equipment doesn't show

### ISSUE THREAD

**Issue by Garkor** [rathena/rathena#255]
Hello rAthena,

there is a big problem. I've checkout the new version of rAthena and have a big problem. I click on an item but it doesn't equiped. After I refresh I've equiped it. On my other server (5 days old) I don't have any problem.

Best regards,
Garkor

**Comment by aleos89** [comment]
Can you please provide some more information?

Git Hash/Date:
Client Date:
Source Code Modifications?:
Description of Issue:
How to Reproduce:

I'm using a clean version of rA and am able to equip items just fine. Do you get any warnings or error messages on the map server?

**Comment by Garkor** [comment]
Date of rAthena Version/Date of checkout: 27.01.2015
Client date: Tested on 2013-08-07 and 2012-05-15a.
No Source modification(Only define Pre-Re).
No error or warnings on the rA console.

On my other server(checkout at 10.01.2015) I've no problem. With the same exe.

The ways you can reproduce it: Checkout newest version of rA and use the 2012-05-15 exe.

Best regards,
Garkor

**Comment by lighta** [comment]
What is the 'version' you have put in the clientinfo ? Check the map
console log see to wich version he has mapped you

**Comment by Garkor** [comment]
I've already sayed that I've setup the different rAthena versions to the same. The only different is the checkout date. Same client, same clientinfo, same configuration etc.

Best regards,
Garkor

**Comment by anacondaqq** [comment]
hahaha same here!
The problem happened on 2010-07-** clients.

The problem in packet_db.txt. I was change packet_ver from default to 25, and the problem gone...

**Comment by lighta** [comment]
Well that info is needed to reproduce it

**Comment by anacondaqq** [comment]
@lighta i will make gif animations for you. Just give me some time i will show... (after 1-2 hours)

**Comment by anacondaqq** [comment]
@lighta @aleos89 here is a video with bug: https://www.youtube.com/watch?v=NjZrkJ9odQM

**Comment by cydh** [comment]
> Same client, same clientinfo, same configuration etc.
that's ur problem, u use 2 different clients with SAME clientinfo.
@lighta 's question us left unanswered, "what is <version> on your clientinfo?"
look at packet_db and check "is ur client listed there? if yes use the date there and put the version on clientinfo, if not, so no guarantee if it will work"

**Comment by anacondaqq** [comment]
Dear @cydh, can you explait how work this line in **packet_db.txt**
> packet_ver: default

Which **client date** it will use if it setted **default**?

**Comment by nanakiwurtz** [comment]
*< A wild nanakiwurtz appeared! >*
If it's set to default, then it will use the highest date available which is supported by rAthena.
Currently it's **2013-12-23Ragexe** (or version 46)

*< The wild nanakiwurtz ran away! >*

**Comment by Garkor** [comment]
It's not my first server and I've already setup the server(Including pakets,clientinfo and mmo.h). I use 2013-08-07 exe. On other server(Older revision) I've no problem with the same server settings.

Best regards,
Garkor~

**Comment by reigneil** [comment]
@Garkor
Maybe you forgot to update your SQL you can find this... 
https://github.com/rathena/rathena/tree/master/sql-files/upgrades

**Comment by custodis** [comment]
Same problem here 
Any solution yet ?

**Comment by Garkor** [comment]
No.I've setted up the server complete new and always the sql table too. I don't think that the problem is my responsible.

Best regards,
Garkor~

**Comment by custodis** [comment]
I gave up and downloaded older revision 
its working just fine now

**Comment by cydh** [comment]
Seems just setting fault
* Check ur `packet_db_ver: ` value in `db/packet_db.txt`
* Check ur `PACKETVER` in `mmo.h`
* Check ur `<version>` in ur `clientinfo.xml`
Match them

**Comment by hvitoreti** [comment]
I got the same problem, every time I try to equip something.
Basically what happens is:
1- I double click an item on my inventory
2- The item I had equipped shows up on my inventory, but the one I just tried to equip is still showing up on my inventory while the equivalent slot on my char Info is now empty, as if I had nothing equipped there.

Everything else aside from a few text glitches is working fine, except for this.
My packet_db_ver in db/packet_db.txt is 45. Same value on both mmo.h and clientinfo.xml.

I tried diffing with both xDiffPatcher and Nemo with the same result.

Currently using 2013-08-07aRagexe and playing with Renewal on.

**Comment by iraciz** [comment]
TO FIX THIS ISSUE:
 
OPEN:
 
SCR / CONFIG / CORE.H
 
COMMENT THE  define PACKET_OBFUSCATION
 
 
/// Comment to disable the official packet obfuscation support.
/// When enabled, make sure there is value for 'packet_keys' of used packet version or
/// defined 'packet_keys_use' in db/[import/]packet_db.txt.
/// This requires PACKETVER 2011-08-17 or newer.
//#define PACKET_OBFUSCATION
