### ISSUE TITLE
Delete Character Without Email

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#2550]
* **rAthena Hash**: 18e0f0a

* **Client Date**: 20170517RE

* **Server Mode**: RENEWAL

* **Description of Issue**: Delete Character Can Without Email
  * Result: If you input email and wrong, the caracter unable to delete.. BUT, if you delete character with blank email the caracter will deleted.
  * Expected Result: caracter canot delete if wrong email and blank email.
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by psychonaut04** [comment]
Can you try a@a.com to see if it will delete too?

**Comment by mazvi** [comment]
For example account with email a@a.com

Wrong Email = Cannot Delete (ab@a,com)
True Email = Delete (a@a.com)
Blank Email = Delete

**Comment by psychonaut04** [comment]
No, i mean, doesn't create account with a@a.com, just put it in any account and try.

**Comment by mazvi** [comment]
Yes i was test withmy email

**Comment by mazvi** [comment]
thanks @psychonaut04 this is my invalid

**Comment by Jeybla** [comment]
a@a.com is a special case which allows deletions without verification or what was the actual issue?
