### ISSUE TITLE
Card Drop Rate Cannot Zero 0

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#2551]
* **rAthena Hash**: 18e0f0a

* **Client Date**: 20170517RE

* **Server Mode**: RENEWAL

* **Description of Issue**: Drop rate MVP Card cannot zero
  * Result: 

// The rate at which cards are dropped
item_rate_card: 500
item_rate_card_boss: 100
item_rate_card_mvp: 0
item_drop_card_min: 0
item_drop_card_max: 10000

// Can the monster's drop rate become 0? (Note 1)
// Default: no (as in official servers).
drop_rate0item: yes

but if i using @mi the card is 0.01%
  * Expected Result: 
using @mi the card must be 0.00%
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by anacondaqq** [comment]
I can confirm, very old thing, but not sure if it a bug.

**Comment by Jeybla** [comment]
```C
map/battle.cpp:	{ "item_drop_common_min",               &battle_config.item_drop_common_min,            1,      1,      10000,          },
map/battle.cpp:	{ "item_drop_equip_min",                &battle_config.item_drop_equip_min,             1,      1,      10000,          },
map/battle.cpp:	{ "item_drop_card_min",                 &battle_config.item_drop_card_min,              1,      1,      10000,          },
map/battle.cpp:	{ "item_drop_mvp_min",                  &battle_config.item_drop_mvp_min,               1,      1,      10000,          },
map/battle.cpp:	{ "item_drop_heal_min",                 &battle_config.item_drop_heal_min,              1,      1,      10000,          },
map/battle.cpp:	{ "item_drop_use_min",                  &battle_config.item_drop_use_min,               1,      1,      10000,          },
map/battle.cpp:	{ "item_drop_add_min",                  &battle_config.item_drop_adddrop_min,           1,      1,      10000,          },
map/battle.cpp:	{ "item_drop_treasure_min",             &battle_config.item_drop_treasure_min,          1,      1,      10000,          },
```
Looks the minimum value for all drops is 1. We should recheck if it is intention?

**Comment by anacondaqq** [comment]
if I remember correctly if you will set it to 0, you will have division by zero in some code parts (= crash), that's why these settings start from 1.

**Comment by mazvi** [comment]
So if from my config use drop_rate0item yes.. there was card drop actualy is 0? But only @mi output wrong?

**Comment by aleos89** [comment]
For this case, using 0 should be fine for all the *_min item drop cases that @Jeybla quoted:
https://github.com/rathena/rathena/search?utf8=✓&q=item_drop_common_min&type=
