### ISSUE TITLE
Soul Link Wizard (Gemstone Requirement not working)

### ISSUE THREAD

**Issue by ecdarreola** [rathena/rathena#2556]
* **rAthena Hash**: 09519f3

* **Client Date**: 2017-01-25

* **Server Mode**: Renewal

* **Description of Issue**: After Soul Linked, gemstone requirements should be bypassed.
  * Result: Gemstone requirement still required when using skill that needs it.
  * Expected Result: No gemstone requirement or gemstone should not be used.
  * How to Reproduce: 
1. Use Soul Linker to Link Wizard with Wizard Spirit.
2. Wizard/Warlock now on Spirit Mode.
3. Ganbantein (Edited to Ganbantein Only)
4. It says gemstone required.
  * Official Information: As per RMS, http://ratemyserver.net/index.php?page=skill_db&skid=453 it should not require gemstone anymore except for those who have duration. (Not sure if RMS still reliable)
  

* **Modifications that may affect results**: None

**Comment by Jeybla** [comment]
`Gemstones are checked, but not substracted from inventory.`
From: https://github.com/rathena/rathena/blob/master/src/map/skill.cpp#L15988

Looks like this issue is invalid. Please recheck your informations.

**Comment by ecdarreola** [comment]
@jeybla: From actual testing gemstone are still substracted. Ill provide actual results later.

**Comment by ecdarreola** [comment]
@Jeybla : Would image be enough? Please see below.

No Soul Link:
![screenchaos005](https://user-images.githubusercontent.com/5693492/32171057-07fd38dc-bdb2-11e7-8149-a6929640da8b.jpg)

With Soul Link:
![screenchaos006](https://user-images.githubusercontent.com/5693492/32171064-0d0e262e-bdb2-11e7-80e8-73a236c56038.jpg)

**Comment by Jeybla** [comment]
Can you retest it with Gemstones in your inventory? From the comment, you need to have at least one gemstone, the soul link just disables the subtraction.

**Comment by ecdarreola** [comment]
@jeybla Please see results below.

Soul Linked:
![screenchaos010](https://user-images.githubusercontent.com/5693492/32172428-82e3f7da-bdb6-11e7-8d33-88146e75fe55.jpg)

Using Ganbantein: (Still consumed the gemstones)
![screenchaos011](https://user-images.githubusercontent.com/5693492/32172449-90459cbc-bdb6-11e7-9582-ca57759939e4.jpg)

**Comment by Lemongrass3110** [comment]
Wasnt gantabein the skill that uses 2 gemstones and it only reduced the costs by 1?
Somehow github does not let me search for text in issues right now. I think there has been an issue for this already. I could remember wrong though.

**Comment by Atemo** [comment]
Officially SL_WIZARD does not remove the gemstone cost from Ganbantein.

**Comment by ecdarreola** [comment]
@Atemo I'm confused with "does not remove the gemstone cost". Thus this mean my report is valid? Since after using link, the gemstone are being used/removed.

**Comment by Atemo** [comment]
Did any skill except Ganbantein consume a gemstone under SL_WIZARD ? Yes -> valid, No -> Invalid

**Comment by ecdarreola** [comment]
@Atemo Yes, even safety wall consumes gemstone after soul link. From the 1st post rather screenshot.

**Comment by Akaineko-astasi** [comment]
@ecdarreola Consumes does not mean requires 1 in your inventory >_< 
![screenrathena000](https://user-images.githubusercontent.com/12430338/32179662-08a48350-bda1-11e7-93fc-336586345d48.jpg)
![screenrathena002](https://user-images.githubusercontent.com/12430338/32179667-0c6b4686-bda1-11e7-8119-2cecdde596b0.jpg)

**Comment by ecdarreola** [comment]
@Lemongrass3110 Okay thanks. So my understanding for ganbantein skill is wrong when being soul linked. Silly me. I wonder why its "!=" on skill_id. 

Thanks for the prompt response.
