### ISSUE TITLE
Error Skills Class Alchemist

### ISSUE THREAD

**Issue by Haikenz** [rathena/rathena#2559]
* **rAthena Hash**: 611dee0

* **Client Date**: 2017-06-14b and 2017-10-18a

* **Server Mode**: RENEWAL

* **Description of Issue**: Error in class Alchemist/Creator/Biochemist, when using skill that needs item
  * Result: In the image below I used the Hallucinogenic ability, which needs Alcohol
<a href='https://s1.postimg.org/6ssj0hhr1r/Sem_t_tulo.png' target='_blank'><img src='https://s1.postimg.org/6ssj0hhr1r/Sem_t_tulo.png' border='0' width='100%'/></a>
  * PS: I also tested compile a clean emulator without modification, and presented the same error.

**Comment by aleos89** [comment]
I was unable to reproduce this with the 2015-11-04 and 2017-06-14 clients using the same hash as you. All I did was spawn a few mobs and casted the skill. Damage was giving appropriately, Alcohol was consumed, and no crash happened.

**Comment by Haikenz** [comment]
the error occurs when you use the skill when you do not have the item in inventory

**Comment by aleos89** [comment]
![image](https://user-images.githubusercontent.com/3521753/32196930-ba3ece08-bd98-11e7-9010-ae5f8ee6c354.png)
I get prompted about the requirement.

**Comment by Haikenz** [comment]
Ops... Error in **msgstringtable.txt** because it caused crush because it does not show the item name

Close!
