### ISSUE TITLE
Problem OnCentos not compiled

### ISSUE THREAD

**Issue by BruSantato** [rathena/rathena#2564]
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking whether make sets $(MAKE)... yes
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether g++ accepts -g... (cached) yes
checking for ar... /usr/bin/ar
checking whether byte ordering is bigendian... yes
configure: error: bigendian is not supported... stopping

**Comment by Lemongrass3110** [comment]
Please follow the issue template and give us the required information. Otherwise noone can help you.

CentOS version?
gcc version?
g++ version?
rAthena hash?

**Comment by Jeybla** [comment]
Likely related: #2127

> Can you try installing g++ package?

**Comment by Jeybla** [comment]
No further input, closing the issue.
