### ISSUE TITLE
Just Sugestion: Disable Monster Drop Log

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#2568]
Just Sugestion: Disable Monster Drop Log

Log any item, on player for example player pick item from monster drop, transaction, refine, storage and other all activities about character player not monster .. But disable all monster log ... can it?

* **rAthena Hash**: 

* **Client Date**: 

* **Server Mode**: 

* **Description of Issue**: 
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by anacondaqq** [comment]
You can disable it manually, or select special flags what you wish to log. There is nothing to disable at all, and I do not recommend to turning it off. Lets people manually check how memory eats mob logs, and tune it for their own needs.

**Comment by mazvi** [comment]
@anacondaqq thx very much i only need remove this // 0x000008 - (L) Log items drop/looted by monsters

 0xFFFFFF - (MINUS) 0x000008

how to SUM hexadecimal?

**Comment by anacondaqq** [comment]
just type your hexes to google like at line above, and google will print an answer

**Comment by Lemongrass3110** [comment]
you can also use windows calculator in programmer mode.
0xFFFFFF - 0x000008 = 0xFFFFF7

Please tell us if this setting achieved what you wanted to do or if there is still an "issue" for you. Otherwise we could close this.

**Comment by mazvi** [comment]
For now I think this seems to be true.. I will try it when server maintenance tomorrow monday.. Thank you very much and apologize for my stupidity. it already has this facility :D
