### ISSUE TITLE
Broken "status" command

### ISSUE THREAD

**Issue by vehona** [rathena/rathena#257]
When you try to check status of running server, it doesn't work because it can't access correct PIDs. Probably it should be changed in **get_status()** to use **print $1** instead of **print substr( $0, 0, 7)**.

**Comment by Lemongrass3110** [comment]
Are you talking about flux CP?

**Comment by vehona** [comment]
Hm, not sure what is "flux CP".

When the server is running, if you try to get its status with **./athena-start status**, you will get something like this:
```
└ $ ./athena-start status
./athena-start: 155: [: 5935: unexpected operator
'login-server' seem down
./athena-start: 155: [: 5937: unexpected operator
'char-server' seem down
./athena-start: 155: [: 5939: unexpected operator
'map-server' seem down
```

So, I was suggesting a fix for **athena-start** file.

**Comment by aleos89** [comment]
Adjusting it to "print $1" should resolve the issue.

**Comment by Lemongrass3110** [comment]
@aleos89 this sounds like a problem that can be fixed quickly :+1:
