### ISSUE TITLE
Make Clean Warning after Map Server Move to CPP

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#2570]
Make Clean Warning after Map Server Move to CPP

![warning make clean](https://user-images.githubusercontent.com/8316103/32385972-56a0f634-c0f2-11e7-82e8-c89d47e75158.PNG)

* **rAthena Hash**: e7e9cf6

* **Client Date**: 20170517RE

* **Server Mode**: RENEWAL

* **Description of Issue**: 
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Jeybla** [comment]
Did you re-run your `configure` script?

**Comment by mazvi** [comment]
thx sir this isue solved with using configure script
