### ISSUE TITLE
Homunculus System Update

### ISSUE THREAD

**Issue by aleos89** [rathena/rathena#2571]
* **rAthena Hash**: e7e9cf6

* **Client Date**: N/A

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: kRO updated several homunculi skills.
  * Expected Result: Match new kRO behavior.
  * How to Reproduce: Use given hash above.
  * Official Information:

- [x] The base level is increased from 150 to 175.
- [x] The experience tables are modified to low levels, less experience is needed at high levels, you will need more experience.
- [x] The global cooldown of all the abilities of standard homages is modified [Lif, Amistr, Filir, Vanilmirth].
- [x] The maximum level of some skills of the homunculus S is increased and their formulas are balanced.
- [x] All the experience when the homunculus kills a target is given to the Genetic (including JEXP).
- [x] 10% of the experience obtained by the Genetic is given to the homunculus adjusted to its base level.
- [x] The auto-feed function is added to the homunculus. (#3007)

-> Eira:
- [x] Eraser Cutter: Maximum level is increased from 5 to 10, its damage is increased, the wind property of the skill is eliminated.
- [x] Xeno Slasher: Maximum level is increased from 5 to 10, its damage is increased, the wind property is added to the skill, its global cooldown is eliminated.

-> Eleanor:
- [x] Style Change: Cast time is removed.
- [x] Sonic Claw: The global cooldown is changed by skill cooldown.
- [x] Silvervein Rush: Maximum level is increased from 5 to 10, its damage is increased, skill cooldown is reduced slightly.
- [x] Midnight Frenzy: Maximum level is increased from 5 to 10, its damage is increased, skill cooldown is reduced slightly.

-> Bayeri:
- [x] Angriffs Modus: The reduction of DEF / FLEE is lower.
- [x] Stahl Horn: Maximum level is increased from 5 to 10, its damage is increased, its global cooldown is eliminated.
- [x] Heilige Stange: Maximum level is increased from 5 to 10, its damage is increased, its global cooldown is eliminated, the range is increased.

-> Sera:
- [x] Pain Killer: Maximum level increases from 5 to 10, the cast can be made up to 5 cells away from the genetic. (maximum 2333,3333)
- [x] Needle of Paralyze: Maximum level is increased from 5 to 10, its damage is increased, its global cooldown is eliminated

-> Dieter:
- [x] Pyroclastic: Maximum level is increased from 5 to 10, the debuff break weapon is eliminated.
- [x] Lava Slide: Maximum level increases from 5 to 10, the maximum area range increases.

Thanks to [Ziu](http://ziu-ro.blogspot.com/2017/10/homunculus-system-update-ragnarok-online.html)! [(kRO Source)](http://ro.gnjoy.com/news/event/View.asp?Seq=784&kind=A&curpage=1)

TODO:
- [ ] The formulas of physical and magical damage are changed, now the damage of both is increased. (Is this just referring to the damage adjustments of the individual skills or the overall ATK/MATK for the homunculus?)
- [x] Confirm the cast time adjustments of the skills that were increased to max level 10.

* **Modifications that may affect results**: 
  * None

**Comment by admkakaroto** [comment]
Any new here?
