### ISSUE TITLE
Heal formulas

### ISSUE THREAD

**Issue by Tokeiburu** [rathena/rathena#2575]
* **rAthena Hash**: ab01424

* **Client Date**: any

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: The heal bonuses should be additive instead of multiplicative.
  * Expected Result: The heal bonuses should match with kRO.
  * How to Reproduce: Heal yourself.
  * Official Information:

### Base healing for the next formulas (the AB has Meditation here):
![image](https://user-images.githubusercontent.com/8761658/32401673-4ea961d0-c0ea-11e7-87cc-c9456bb3030c.png)

Heal Level 10
```
floor((level + int) / 5) * 30 * percent_heal_bonus + matk
= floor((113 + 104) / 5) * 30 * (1 + 0.2) + 204
= 1752
```

### Testing two Diabolus Rings (+5% heal bonus each)
![image](https://user-images.githubusercontent.com/8761658/32401694-ccaf709c-c0ea-11e7-970a-c85763478d6e.png)
Heal Level 10
```
floor((level + int) / 5) * 30 * percent_heal_bonus + matk
= floor((113 + 104) / 5) * 30 * (1 + 0.2 + 0.05 + 0.05) + 204
= 1881
```
On that one, you can see that the +20% Meditation bonus and the +10% heal bonus are not multiplied together, their bonuses are added together.

### Testing Offertorium at level 2 (+60% heal) + two Diabolus Rings (+10% heal)
![image](https://user-images.githubusercontent.com/8761658/32401723-411616b6-c0eb-11e7-916e-9dc9eea6429b.png)
Heal Level 10
```
floor((level + int) / 5) * 30 * percent_heal_bonus + matk
= floor((113 + 104) / 5) * 30 * (1 + 0.2 + 0.05 + 0.05 + 0.6) + 204
= 2655
```
Here we can see that again, the +60% heal bonus is added, not multiplied.

### Testing with Highness Heal level 5 with Offertorium at level 2 (+60% heal) + two Diabolus Rings (+10% heal)
![image](https://user-images.githubusercontent.com/8761658/32401736-8dd780d4-c0eb-11e7-8660-77219436fcf9.png)
Highness Heal Level 5
```
(floor((level + int) / 5) * 30 * percent_heal_bonus + matk) * high_heal_bonus
= (floor((113 + 104) / 5) * 30 * (1 + 0.2 + 0.05 + 0.05 + 0.6) + 204) * 3.2
= 8496
```
The Highness Heal multiplier is applied at the complete end of the formula, after the matk calculation.

### Testing back with Heal, with Water Insignia (+ all of the above):
![image](https://user-images.githubusercontent.com/8761658/32401746-b3e82ec2-c0eb-11e7-99ca-5d73d82f5d28.png)
Heal Level 10
```
(floor((level + int) / 5) * 30 * percent_heal_bonus + matk) * 1.1
= (floor((113 + 104) / 5) * 30 * (1 + 0.9) + 204) * 1.1
= 2920
```
Water Insignia is also a global multiplier.

### Testing the same as above, but with Highness heal:
![image](https://user-images.githubusercontent.com/8761658/32401769-3674c08a-c0ec-11e7-8c8c-adef576f97d0.png)
Highness Heal Level 5
```
(floor((level + int) / 5) * 30 * percent_heal_bonus + matk) * 1.1
= (floor((113 + 104) / 5) * 30 * (1 + 0.9) + 204) * (1.1 * 3.2)
= 9345
```
The global multipliers are multiplied together first, otherwise it would have rounded down to 9344.

### It isn't showed in this screenshot, but the AB currently has Critical Wound level 3 which gives a 60% reduction (so it heals for 40% of the current amount).
![image](https://user-images.githubusercontent.com/8761658/32401775-5a8cd192-c0ec-11e7-944d-7d888ead916c.png)
Highness Heal Level
```
(floor((level + int) / 5) * 30 * percent_heal_bonus + matk) * high_heal_bonus
= (floor((113 + 104) / 5) * 30 * (1 + 0.9) + 204) * (3.2 * 0.4)
= 3398
```
Welp, there's a rounding error somewhere along the line of 1 heal amount (screenshot shows 3399), but I don't think it matters at this point. So the critical wound multiplier is also calculated together at the complete end of the formula.

**Comment by cydh** [comment]
a cool neat research
