### ISSUE TITLE
src/map/mob.hpp : No error when setting MAX_MOB_DB too high

### ISSUE THREAD

**Issue by uddevil** [rathena/rathena#2579]
* **rAthena Hash**: e7e9cf6d7333345d0e11d9f0bf9f1badb6ff3cd9

* **Client Date**: 2015-11-04a RagexeRE

* **Server Mode**: renewal

* **Description of Issue**: 
  * Result: 
    - map-server compilation finished without any error when setting `MAX_MOB_DB` too high (i'm using 81000)
    - then, when `map-server.exe` executed, it stops after loading `import/mob_drop.txt` without any error (i don't know if its really stopped, but i've waited about 5 minutes and still no response)
  * Expected Result: 
    - it should warn or error when `MAX_MOB_DB` is set too high
    - or at least there's error when `map-server.exe` executed
  * How to Reproduce: 
    - set `MAX_MOB_DB` on `src/map/mob.hpp` to 81000
    - recompile the server (I'm using vs 2015 CE)
    - execute `map-server.exe`
  * Official Information:
    - None as its custom
  

* **Modifications that may affect results**: 
    - So far i'm using `MAX_MOB_DB` 51000 and there's no problem.

**Comment by psychonaut04** [comment]
Can you try this:

[src/map/mob.cpp](https://github.com/psychonaut04/rathena/commit/70fd19b93bddcca530f3f7c3a575fa8324f4dfa6)
[src/map/mob.hpp](https://github.com/psychonaut04/rathena/commit/b52d74cbf4936f3091b379313259bcb6cb3c6299
)
So it should be 51000 and anything more than that: error?

**Comment by uddevil** [comment]
@psychonaut04 
It worked, and the compilation failed with error when i set the MAX_MOB_DB with 81000.
I don't really have / implement that many mobs though.

But that makes me wondering, what is the real maximum MAX_MOB_DB ? is it USHRT_MAX ?

**Comment by psychonaut04** [comment]
I'm really not sure about that, can be something to try, but it can have a exact size.

**Comment by psychonaut04** [comment]
If your USHRT_MAX is 51000(and if you can't put anything more than 51000) it can be that, so i can try to get the maximum value instead of 51000(cause it would be able change for another user). But i'm not sure from where that max comes.

**Comment by Lemongrass3110** [comment]
As of b2ab972 MAX_MOB_DB is only used for ID checks and should not be touched anymore.
If you still think you need to adjust it, we will assume you know what you are doing and ignore any issues that result from it.
So please upgrade your emulator to have your issue fixed.
