### ISSUE TITLE
blaze shield Skill Bug

### ISSUE THREAD

**Issue by Darkpurple** [rathena/rathena#258]
blaze shield skill should be had knockback effect in official like the video showed:

https://www.youtube.com/watch?v=1MQM2eskVPU

But in rahtena, the knockback effect loss, the monster rush to the player quickly..!!

**Comment by aleos89** [comment]
I don't see any knockback in the video from the skill. It's just the animation of being damaged which is stopping the monster.

**Comment by Playtester** [comment]
I actually had this fixed a while ago. There's no knockback, but monsters shouldn't be able to move through the fire either (which was the case before I had fixed it).

Fix: https://github.com/rathena/rathena/commit/2c3cb602dc918020ec4f448b955669f9b7e88479
