### ISSUE TITLE
int_elemental.cpp

### ISSUE THREAD

**Issue by Questune09** [rathena/rathena#2584]
* **rAthena Hash**: #2567 

* **Client Date**: 

* **Server Mode**: 

* **Description of Issue**: 
  * Result:  after i recompile i got this errors 

`int_elemental.cpp: In function 'bool mapif_elemental_load(int, uint32, s_elemental*)':
int_elemental.cpp:66:57: error: 'e_mode' was not declared in this scope
  Sql_GetData(sql_handle,  1, &data, NULL); ele->mode = (e_mode)atoi(data);
`

already update my version to devtools -7

`gcc (GCC) 7.2.1 20170829 (Red Hat 7.2.1-1)
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.`

  * Expected Result:  shouldn't get this error because i dont get any conflict on it also i do fresh rathena source
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
I'll mark this as invalid per our discussion [here](https://github.com/rathena/rathena/commit/24b3509e537fe26d0856968864bfdc598a7874a4#commitcomment-25455680).
