### ISSUE TITLE
configure no working

### ISSUE THREAD

**Issue by RagOfZodiac** [rathena/rathena#2589]
i download latest rathena gitclone at linux. 
install
chmod a+x athena-start
chmod a+x configure

try to ./configure
error: c++ compiler cannot create executables.
and my rathena file dont have any login.char.map server
been long time never create server.need a help for this latest version and rathena update.

kindly assist me.thanks you.

**Comment by Lemongrass3110** [comment]
This is not a support platform.
Use the forum or the discord support channel.
Thanks for understanding.
