### ISSUE TITLE
Free Cast Skill Issue

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#2599]
* **rAthena Hash**: c6fe9e9

* **Client Date**: 20170517RE

* **Server Mode**: RENEWAL

* **Server Operating System**: CentOS 7 Minimal 64bit

* **GCC Version**: 5.3.1

* **Description of Issue**: FREE CAST ISSUE
  * Result: CAST -> SLOW WALK/MOVEMENT -> FINISH CAST -> SLOW WALK/MOVEMENT
  * Expected Result: CAST -> SLOW WALK/MOVEMENT -> FINISH CAST -> NORMAL WALK/MOVEMENT
  * How to Reproduce: This issue apear using skill like: Psychic Wave, Cold Bolt, Fire Bolt, Lightening Bolt, must relog or warp to other map this issue will disapear...
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by uddevil** [comment]
Can confirm.

using hash : c6fe9e9cde4003bd7842afccca1eb6f0471a933c 
client date : 2015-11-04a RE
server type : renewal
OS : debian 9 64 bit
GCC Version : gcc version 6.3.0 20170516 (Debian 6.3.0-18)

Tested with firebolt lvl 10 and Free Cast lvl 1
- `@die` then `@alive` does not remove slow walk / movement
- teleporting on the same map does not remove slow walk / movement
- relog or teleporting / warp to other map remove slow walk / movement
