### ISSUE TITLE
item id 19134 missing effect status

### ISSUE THREAD

**Issue by hendra814** [rathena/rathena#2601]
* **rAthena Hash**: lastest

* **Client Date**: 2015-11-04

* **Server Mode**: renewal

* **Description of Issue**: item Wickebine's Black Cat Ears with slot but not have effect like item 5360
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by admkakaroto** [comment]
the least you can do for the emulator and your server is to create the script of the items, if you do not know you can ask for help in the forum instead of git.

**Comment by Lemongrass3110** [comment]
From reading the item description on divine pride [5360](https://www.divine-pride.net/database/item/5360), [19134](https://www.divine-pride.net/database/item/19134) I think this items are also having some mistakes in their script:
`Adds a 5% chance to bypass 25% of magical defense on normal monsters and players for 5 seconds when performing a magical attack.`

**Comment by SirHaziel** [comment]
I've made a research already, got the official effects for both, just waiting having more items to fix to pull.

**Comment by aleos89** [comment]
Fixed in 50ef565.
