### ISSUE TITLE
Cash Log Issue

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#2603]
* **rAthena Hash**: c6fe9e9

* **Client Date**: 20170517RE

* **Server Mode**: RENEWAL

* **Server Operating System**: CentOS 7 Minimal 64bit

* **GCC Version**: 5.3.1

* **Description of Issue**: Cash Log Issue
  * Result: Cash Log not log NPC Script set #KAFRAPOINTS
  * Expected Result: Cash Log log NPC Script set #KAFRAPOINTS
  * How to Reproduce:
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Technically a duplicate of #2169.
