### ISSUE TITLE
Log Filter not work properly

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#2608]
* **rAthena Hash**: c20d1cc

* **Client Date**: 20170517RE

* **Server Mode**: RENEWAL

* **Description of Issue**: 
  * Result: 
I remove this from filter so i get enable_logs: 0xFFFFA7
0x000008 - (L) Log items drop/looted by monsters
0x000080 - (C) Log player-used items (consumables/pet&hom&merc food/items used for skills&attacks)

but the consumables like potion there was logging on database, arrow using for attack also logging from database... there is shouldnt logging on database.. 

by the way i also need logging for item like gift box, purple box, old blue box, and old card album.. this item is also type consumable

i do not need log item using like potion and arrow

how to set it properly?

  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
15 (F) - 8 is not 10 (A). Your final result to remove those two options would be 0xFFFF77. If you want to split those boxes you'll have to create a new log type and adjust for each case in source.

**Comment by mazvi** [comment]
0x000008 and 0x000080 that is 0x000088?

so 0xFFFFFF - 0x000088 i got 0xFFFFA7

**Comment by aleos89** [comment]
Hexadecimal is solved per column, not a total value.

**Comment by mazvi** [comment]
thx very much this is my fault...

**Comment by Atemo** [comment]
Adjust `log_filter` to 8
`// 0008 - Usable Items(2) + Lures,Scrolls(11) + Usable Cash Items(18)`
