### ISSUE TITLE
Sorcerer's Elemental Shield.

### ISSUE THREAD

**Issue by Barigas** [rathena/rathena#261]
On rAthena - it has cast time, some delay, sets only Pneuma 1x1 size. Does nothing if there is already a safey wall or smth under the party member.
On officials it sets both ordinary Pneuma(3x3) and Safety Wall lvl 10(at any skillvl lvl). Sets both of them no mater if there are already Pneumas or SWs near(or under) the caster or party members. Has 0 cooldown, 0 delay, 0 cast time at any lvls. AoE is 27x27, not fullscreen as it is shown in the description. the only difference in skillvl was found to be Safety Walls duration about 20sec on ES lvl1 and about 45 at lvl5. Here's my video from ruRO with this skill:
https://www.youtube.com/watch?v=ntk68l8KF7k

**Comment by reigneil** [comment]
nice video very detail. looking forward to see this on rAthena... /no1

**Comment by cydh** [comment]
/me is reminding this to @aleos89 *winks*

**Comment by RagnarokNova** [comment]
Functionality is looking great, but there's one detail. If there's no party, the skill doesn't cast. Shouldn't it at least cast on self?
