### ISSUE TITLE
autobonus script (itemscript)

### ISSUE THREAD

**Issue by ecdarreola** [rathena/rathena#2612]
* **rAthena Hash**: a49a1a5

* **Client Date**: 20170125

* **Server Mode**: Renewal

* **Description of Issue**: itemscript autobonus giving unwanted result such as negative values or +/- values
  * Result: should be based on itemscript such as increase agi + 44 for autobonus
  * Expected Result: No negative values
  * How to Reproduce: Use autobonus itemscript to any items. Best example is in cards like Rudo Card.
1. Equip Rudo Card to any boots slotted
2. Equip boots
3. Use @allstats
4. Attach any monster melee or not. Skill or not.
5. See status once card is activated.
6. Value has negative value or sometimes +/- (see attached image)
![ss](https://user-images.githubusercontent.com/5693492/32988059-96007836-cd36-11e7-92da-c9f2f31c22fc.JPG)

  * Official Information: No links as of now.
  

* **Modifications that may affect results**: none

**Comment by Jeybla** [comment]
Confirmed, even though it looks like it's just a display issue. Therefore I set it to priority low.

**Comment by ecdarreola** [comment]
@Jeybla : Upon testing it's not a display issue only. But also status issue, cause from testing, my HP went from 230k to 113k due to the +/- status.

It got resolved or back to normal when I relogged. So if it is activated and received the negative value all calculations are affected.

**Comment by aleos89** [comment]
Probably somehow related to #2450?

**Comment by ecdarreola** [comment]
@aleos89 : Will try to replicate the said item in #2450 with using autobonus script.

**Comment by ecdarreola** [comment]
Tried #2450 , it's not giving negative values though.

**Comment by ecdarreola** [comment]
@Jeybla @aleos89 just an update. I think all autobonus script in rA are having problems. Even with some enchants.

E.G. 4877,Speed_Of_Light,Speed of Light,6,10,,0,,,,,,,,,,,,,{ autobonus "{ bonus bAspdRate,100; bonus bFlee2,100; bonus2 bHPLossRate,400,1000; bonus2 bSPLossRate,40,1000; }",10,5000,BF_WEAPON,"{ specialeffect2 EF_FLASHER; callfunc \"F_4877\"; }"; },{},{ itemheal 0,-300; }

Once activated aspd dropped drastically.

It also happens in Hawk Eyes, some of the no cast skills have cast when it is activated.

**Comment by Jeybla** [comment]
Could be related to the compiler optimizations? @lighta

**Comment by ecdarreola** [comment]
Which optimization is this? Is it available for pull request?

**Comment by secretdataz** [comment]
Related: #131

**Comment by secretdataz** [comment]
Closing this issue since autobonus is working fine as is. sc_start is the real culprit.
![image](https://user-images.githubusercontent.com/2021243/36161744-06a4deb4-1117-11e8-9226-fa1f041187ce.png)
