### ISSUE TITLE
Super Novice Chant

### ISSUE THREAD

**Issue by ecdarreola** [rathena/rathena#2615]
* **rAthena Hash**: 4de727e

* **Client Date**: 20170125

* **Server Mode**: Renewal

* **Description of Issue**: Super Novice Chant doesn't work when exp is at 10.XX where XX has a value. It works only at 10.00, 20.00 and so on. Also Super Novice Chant doesn't work on max level.
  * Result: Explosion Spirit is not being casted once the exp value is 10.XX
As for the max level, it doesn't work. (Please see attached iRO reference)
  * Expected Result: Should be able to cast explosion spirit at 10.XX or experience divisible by 10 including its decimal.
And Super Novice Chant should be able to be casted when max level.
  * How to Reproduce: You need to do the Super Novice Chant
1. The Chant: (Type in chat)
Dear angel, can you hear my voice?
I am "Insert IGN" Super Novice~
Help me out~ Please~ T_T
"Addtional Text"
(Chant should be casted after Additional Text)
2. After completing the chant, nothing will happen.
  * Official Information: As for the Exp, it only says it should be divisible by 10 so I assume decimal is included.
As for the max level chant, http://irowiki.org/wiki/Super_Novice (See life after level 99, and 
  

* **Modifications that may affect results**: None

**Comment by Jeybla** [comment]
>  To Fury, you must gain `n × 10.0x` million EXP (where n = 1,2,3,...).

```C
void clif_parse_NoviceExplosionSpirits(int fd, struct map_session_data *sd)
{
	if( (sd->class_&MAPID_UPPERMASK) == MAPID_SUPER_NOVICE ) {
		unsigned int next = pc_nextbaseexp(sd);

		if( next ) {
			int percent = (int)( ( (float)sd->status.base_exp/(float)next )*1000. );

			if( percent && ( percent%100 ) == 0 ) {// 10.0%, 20.0%, ..., 90.0%
				sc_start(&sd->bl,&sd->bl, status_skill2sc(MO_EXPLOSIONSPIRITS), 100, 17, skill_get_time(MO_EXPLOSIONSPIRITS, 5)); //Lv17-> +50 critical (noted by Poki) [Skotlex]
				clif_skill_nodamage(&sd->bl, &sd->bl, MO_EXPLOSIONSPIRITS, 5, 1);  // prayer always shows successful Lv5 cast and disregards noskill restrictions
			}
		}
	}
}
```
The decimal behavior seems to be correct. Though I'm not really sure about `million EXP` because `pc_nextbaseexp(sd);` likely isn't a million?

**Comment by ecdarreola** [comment]
@Jeybla : Should it be 10.XX instead of 10.0X?

**Comment by Jeybla** [comment]
From your wiki source, it should be 10.0X and that's the current behavior.

**Comment by ecdarreola** [comment]
@jeybla: thanks got it. But as for the max level it isnt triggering though. What could be the problem of it?

**Comment by Jeybla** [comment]
` The two Super Novice Secrets which depend on your current % of Base EXP can still be used, but you must continue leveling to gain the EXP required. `
I'm not sure about that :/
I don't think the max level case have been considered by now.

We may could add it to the above quoted code by changing next to something like `next = baseexpfor99+1m*x | x e uint that next > playerexp`. But what happens if the super novice reaches MAX_LEVEL_BASE_EXP (99999999)?

**Comment by ecdarreola** [comment]
@jeybla let me check on other sources if there is
