### ISSUE TITLE
Weapons Expert BK Issue

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#2619]
* **rAthena Hash**: ca1b980

* **Client Date**: 20170517RE

* **Server Mode**: RENEWAL

* **Description of Issue**: https://github.com/rathena/rathena/blob/master/npc/re/quests/eden/eden_quests.txt | line 4256 | for ( .@i = 0; .@i < 15; .@i++ )
  * Result:  Player with completed 90 eden mission but not complete 80 eden mission, they cannot second enchant to this NPC BK.. 

![gambar](https://user-images.githubusercontent.com/8316103/33041804-25959b52-ce72-11e7-9467-c371a655c22d.png)

  * Expected Result:  on iro wiki there is clue mission 80 or higher this people was finished 90 eden mission without 80 mission...

![gambar](https://user-images.githubusercontent.com/8316103/33041688-c5bdc25e-ce71-11e7-87ff-0441aaca8805.png)

  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Atemo** [comment]
We didn't update the size of the menu in https://github.com/rathena/rathena/commit/08338e0a64e863d1e579f145b4dc3f99ac66034f#diff-2b9b79c7ee5796ba7f5073001e69aa06
