### ISSUE TITLE
@whereis on Custom Mob only Shows its SpriteID's spawn

### ISSUE THREAD

**Issue by uddevil** [rathena/rathena#2621]
* **rAthena Hash**: a49a1a52a3e0036c9cad3794c4db5628f088b443

* **Client Date**:  2015-11-04a RagexeRE

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Atcommand `@whereis` on custom mob only Shows its SpriteID's spawn location
  * Expected Result: It should show custom mob's spawn location
  * How to Reproduce: 
     - Create custom mob, for example with ID 30029 in `db/import/mob_db.txt`
     - Alias it with for example 1977 (Heavy Metaling) in `db/import/mob_avail.txt`
     - Spawn it in some maps (example : prt_fild08)
     - Use atcommand `@whereis 30029`
     - It should be showing prt_fild08, but instead it shows where mob id 1977 spawn location (schg_dun01).
  * For copy paste testing :
     - Create new file : `npc/custom/custom_spawn30029.txt`
     - Add to `db/import/mob_db.txt` : 
`30029,C_EXP_PORING,Poring Tercacad,Poring Tercacad,160,1000000,1,10000000,10000000,1,8,9,2,5,6,1,1,0,6,5,10,12,1,3,61,0x83,400,1872,672,480,0,0,0,0,0,0,0,512,10,0,10,0,10,0,10,0,10,0,10,0,10,969,5,512,1,0,0`
     - Add to `db/import/mob_avail.txt` : 
`30029,1977`
     - Add to `npc/scripts_custom.conf` : 
`npc: npc/custom/custom_spawn30029.txt`
     - Add to `npc/custom/custom_spawn30029.txt` : 
`prt_fild08,0,0,0,0	monster	Poring Tercacad	30029,3,0,0`
     - Restart / Reload server
     - Try using `@whereis 30029`
     - It only shows schg_dun01
![cacad bin_2017-11-21_09-37-29](https://user-images.githubusercontent.com/10105610/33052075-ab7986d4-ce9f-11e7-9f99-c90d4584ddc5.png)

  * Official Information: None since its custom.

**Comment by Jeybla** [comment]
Thank you very much for the detailed issue description. It really helps to track down the problem quickly. Keep it up! :+1:
