### ISSUE TITLE
KRO Weight Limit update

### ISSUE THREAD

**Issue by hendra814** [rathena/rathena#2622]
* **rAthena Hash**: lastest

* **Client Date**:  2015-11-04

* **Server Mode**: Renewal

* **Description of Issue**: KRO has changed weight limit into 70%
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**: 
  
  

For more information please check from Ziu Youtube link
https://www.youtube.com/watch?v=tjzPn3-P4Dg

**Comment by aleos89** [comment]
Actually, while testing something else yesterday, when I became overweight at 50%, the icon showed up but it was the 70% icon. So it seems Gravity replaced the 50% icon completely rather than making a new SI for it.
IE:
![unknown](https://user-images.githubusercontent.com/3521753/33078220-fc367d20-ce9f-11e7-8fa5-c7545fe730de.png)

**Comment by mazvi** [comment]
Its because @aleos89 client is 2015.. and the translate not update.. but icon on grf updated 2017 latest..

**Comment by mazvi** [comment]
what mean of SI and IE? @aleos89

**Comment by aleos89** [comment]
SI: status icon
IE: Latin for id est. Which means ”In other words”.

**Comment by syracuase** [comment]
In battle/player.conf
// The maximum weight for a character to carry when the character stops healing naturally. (in %)
natural_heal_weight_rate: 50

Change to -> 70

**Comment by hendra814** [comment]
@syracuase

Thanks for the info.
I don't know as long as this rathena supports weight limit changes

**Comment by Haikenz** [comment]
> In battle/player.conf
// The maximum weight for a character to carry when the character stops healing naturally. (in %)
natural_heal_weight_rate: 50
Change to -> 70

not work, It is necessary to change in source Also
![screenaegir006](https://user-images.githubusercontent.com/17690412/34563290-3f79a15a-f139-11e7-9824-cd9cbc1ed525.jpg)

**Comment by mazvi** [comment]
Its about client server effect.. if your server set to 70% you also must using client support 70% weight limit.. for example 2017 05 17 RE

**Comment by Haikenz** [comment]
i'm use 2017-09-13

**Comment by AzarthMZintos** [comment]
Was this reversed on KRO? anynews on this?

**Comment by hendra814** [comment]
@AzarthMZintos I think not, last update still using 70% weight limit

**Comment by hendra814** [comment]
Any one if you want try modif your src to enable this feature. you could edit like this
at src/map.cpp
line 2006
`status_change_end(&sd->bl, SC_WEIGHT50, INVALID_TIMER);`
change into
`status_change_end(&sd->bl, SC_WEIGHT70, INVALID_TIMER);`

at src/pc.cpp
line 2010
`old_overweight = (sd->sc.data[SC_WEIGHT90]) ? 2 : (sd->sc.data[SC_WEIGHT50]) ? 1 : 0;`
change into
`old_overweight = (sd->sc.data[SC_WEIGHT90]) ? 2 : (sd->sc.data[SC_WEIGHT70]) ? 1 : 0;`

line 2018
`status_change_end(&sd->bl, SC_WEIGHT50, INVALID_TIMER);`
change into
`status_change_end(&sd->bl, SC_WEIGHT70, INVALID_TIMER);`

line 2024
`sc_start(&sd->bl,&sd->bl, SC_WEIGHT50, 100, 0, 0);`
change into
`sc_start(&sd->bl,&sd->bl, SC_WEIGHT70, 100, 0, 0);`

at src/script.cpp
line 11288
`case SC_WEIGHT50:`
change into
`case SC_WEIGHT70:`

at src/script_constants.hpp
line 871
`export_constant(SC_WEIGHT50);`
change into
`export_constant(SC_WEIGHT70);`

line 1552
`export_deprecated_constant(SI_WEIGHT50);`
change into
`export_deprecated_constant(SI_WEIGHT70);`

at src/skill.cpp
line 1860
`case SC_WEIGHT50:		case SC_WEIGHT90:		case SC_HALLUCINATION:`
change into
`case SC_WEIGHT70:		case SC_WEIGHT90:		case SC_HALLUCINATION:`

line 7860
`case SC_WEIGHT50:		case SC_WEIGHT90:		case SC_HALLUCINATION:`
change into
`case SC_WEIGHT70:		case SC_WEIGHT90:		case SC_HALLUCINATION:`

line 9339
`case SC_WEIGHT50:		case SC_WEIGHT90:		case SC_HALLUCINATION:`
change into
`case SC_WEIGHT70:		case SC_WEIGHT90:		case SC_HALLUCINATION:`

at src/status.cpp
line 918
`StatusIconChangeTable[SC_WEIGHT50] = EFST_WEIGHTOVER50;`
change into
`StatusIconChangeTable[SC_WEIGHT70] = EFST_WEIGHTOVER70;`

line 4623
`if (sc->data[SC_WEIGHT50] || sc->data[SC_WEIGHT90])`
change into
`if (sc->data[SC_WEIGHT70] || sc->data[SC_WEIGHT90])`

line 9422
`case SC_WEIGHT50:`
change into
`case SC_WEIGHT70:`

line 11775
`case SC_WEIGHT50:`
change into
`case SC_WEIGHT70:`

line 11889
`case SC_WEIGHT50:`
change into
`case SC_WEIGHT70:`

line 12303
`if (sc && (sc->data[SC_WEIGHT50] || sc->data[SC_WEIGHT90]))`
change into
`if (sc && (sc->data[SC_WEIGHT70] || sc->data[SC_WEIGHT90]))`

line 13787
`case SC_WEIGHT50:`
change into 
`case SC_WEIGHT70:`

at src/status.hpp
line 114
`SC_WEIGHT50,`
change into
`SC_WEIGHT70,`

line 889
`SI_WEIGHT50 		= 35,`
change into
`SI_WEIGHT70 		= 35,`

change data\luafiles514\lua files\stateicon\efstids.lub
`EFST_WEIGHTOVER50 = 35,`
change into
`EFST_WEIGHTOVER70 = 35,`

change data\luafiles514\lua files\stateicon\stateiconinfo.lub
`StateIconList[EFST_IDs.EFST_WEIGHTOVER50] = {`
change into
`StateIconList[EFST_IDs.EFST_WEIGHTOVER70] = {`

and

`{ "Weight over 50%", COLOR_TITLE_DEBUFF },`
change into
`{ "Weight over 70%", COLOR_TITLE_DEBUFF },`

at conf\battle\player.conf
`// The maximum weight for a character to carry when the character stops healing naturally. (in %)
natural_heal_weight_rate: 50`
change into
`// The maximum weight for a character to carry when the character stops healing naturally. (in %)
natural_heal_weight_rate: 70`

at data\texture\effect
replace with this file https://cdn.discordapp.com/attachments/379481697315586048/466174384919281665/1O50AIo.tga
rename it into ¹«°Ô50ÀÌ»ó.tga

**Comment by Haikenz** [comment]
the problem now is that when it reaches 50% of the weight, it turns red already and appears the 50% message that the HP and SP will not be restored.
