### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by Balferian** [rathena/rathena#2626]
* **rAthena Hash**: 3ce3bc3
* **Client Date**: 20170614
* **Server Mode**: Renewal
* **Description of Issue**: error when compile (Debian).
`mob.cpp: In function Б─≤mob_db* mob_db(int)Б─≥:`
`mob.cpp:82:10: error: expected type-specifier`
`mob.cpp:82:28: error: expected unqualified-id before Б─≤)Б─≥ token`
`mob.cpp: In function Б─≤mob_chat* mob_chat(short int)Б─≥:`
`mob.cpp:95:10: error: expected type-specifier`
`mob.cpp:95:28: error: expected unqualified-id before Б─≤)Б─≥ token`
`make[1]: *** [obj/mob.o] Error 1`
`make[1]: Leaving directory /root/test/src/map`
`make: *** [map] Error 2`

* **Modifications that may affect results**: no

**Comment by Jeybla** [comment]
Are you sure you're on a clean rathena copy? These `Б─≤` symbols seem wrong

**Comment by Balferian** [comment]
Yes.
I use clean copy.
`git clone https://github.com/rathena/rathena.git ~/test`
`./configure`
`#define PACKETVER 20170614`
then
`make server`
and i have this error.

**Comment by Jeybla** [comment]
Interesting issue, can you try to include `#include <stdexcept>` in mob.cpp? Unfortunately I'm unable to reproduce it :/

**Comment by Balferian** [comment]
I checked the compilation (_clean rathena_) on another VPS, and there are no errors.
Looks like I need to update the lib on my vps... (=_=)
