### ISSUE TITLE
Dummy at Prontera prevents critical attack from being displayed

### ISSUE THREAD

**Issue by zackdreaver** [rathena/rathena#2629]
* **rAthena Hash**: b2d904b764f43137547e5ed689af2b5983b8b234

* **Client Date**: any

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Dummy at Prontera prevents criitical attack from being displayed
  * Expected Result: Critical attack should be displayed (the red bg + yellow font)
  * How to Reproduce: attack it with char that has high Crit rate
  * Official Information: Replay file
[kro0005.zip](https://github.com/rathena/rathena/files/1497193/kro0005.zip)

  

* **Modifications that may affect results**: n/a

**Comment by Lemongrass3110** [comment]
Dummys on kRO simply are bosses. They also display that icon when you hover them
