### ISSUE TITLE
Insignia Sorcerer Bug

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#2630]
* **rAthena Hash**: 6f985080a8b071e5869679e430274a4b166971c2
* **Client Date**: 2017-05-31
* **Server Mode**: Renewal
* **Description of Issue**: The sorcerer class insignia on level 3 should increase the damage of the elements, but this is not happening.
  * Result: Even within the area of effect of the insignia of the earth, my damage does not increase.
  * Expected Result: Receipt of 25% damage bonus for Land Level 3 insignia.
  * How to Reproduce: use any of the sorcerer class insignia on level 3 on the ground, go up the area of effect, your damage with the respective insignia element will not increase.
  * Official Information: http://irowiki.org/wiki/Water_Insignia
  * Official Information: http://irowiki.org/wiki/Fire_Insignia
  * Official Information: http://irowiki.org/wiki/Earth_Insignia
  * Official Information: http://irowiki.org/wiki/Wind_Insignia
Boost "element" property magic damage by 25%.

Prints:
  * Img1: https://i.imgur.com/h9GQNup.jpg
  * Img2: https://i.imgur.com/ZyRb0Qp.jpg

**Comment by aleos89** [comment]
I tested with 114beba and it worked just fine. I casted Fire Insignia and used Fire Bolt and my damage was increased.

**Comment by Atemo** [comment]
+25% or +25 ?
http://irowiki.org/wiki/Water_Insignia
`The +25 damage increase at Level 3 is a fixed amount.`

**Comment by admkakaroto** [comment]
@Atemo I do not think it only increases 25 damage, it's an insignificant value, I'll look at the translations made by zackdreaver.

**Comment by admkakaroto** [comment]
```
	[SKID.SO_WATER_INSIGNIA] = {
		"Water Insignia",
		"Max Level: 3",
		"^CC3399Requirement: Summon Aqua 3^000000",
		"Skill Form: ^000099Active / Ground^000000",
		"Description: ^777777Draw a water insignia on the",
		"ground within 3 x 3 cells. Recover 1% of",
		"HP per 5 seconds, if the target is equipped",
		"water element armor or it is a water",
		"element monster. Conversely, decrease 1% of",
		"HP per 5 seconds, if the target is equipped",
		"fire element armor or it is a fire element",
		"monster. But all the targets that are inside",
		"of skill range get 1.5 times more damage from",
		"wind element attack.",
		"Consume Indigo Point depend on the skill level.^000000",
		"[Lv 1]: ^777777AQUA ATK +20%, Doubled HP and SP recovery per 3 sec^000000",
		"[Lv 2]: ^777777Recovery effect +10%, Grant weapon with water element. ATK +10%.^000000",
		"[Lv 3]: ^777777Cast delay -30%, ATK +25% in specific water element magic spell.^000000"
	},


Here:
ATK +25% in specific water element magic spell
```

**Comment by Atemo** [comment]
Yeah I just looked at kRO description. It seems to be %.

**Comment by Paoly28** [comment]
that was wrong. the added elemental bonus is mastery type and the amplified magic is bonus damage when taking the type of element.

**Comment by aleos89** [comment]
Could you elaborate on this? Which part is wrong, the skill description or the way it's implemented currently in rAthena?

Check out the PR and let me know.

**Comment by Paoly28** [comment]
// Insignia's increases the damage of offensive magic by a fixed percentage depending on the element.

should add flat MATK not percentage. the percentage portion is damage received.

**Comment by aleos89** [comment]
Ok, to your first comment above when I was confused: The level one Elemental ATK bonus is 20% (not 25) and it was added in this PR to only affect the Elemental, not the master, as the skill description states.

To your current comment: Here is the description of Water Insignia in Korean:
```
[Level 3] : 일부 수속성 마법의 변동 캐스팅이 30% 감소. 일부의 수속성 마법 사용시 공격력이 25% 증가. 
```
It specifically has a `%` symbol.
