### ISSUE TITLE
Suggestion: update instances

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#2631]
* **rAthena Hash**: ca1b980

* **Client Date**: 20170517RE

* **Server Mode**: RENEWAL

This is not issue, but just suggesstion need update instances like below

Nightmarish Jitterbug:
https://github.com/idathena/trunk/blob/master/npc/re/instances/NightmarishJitterbug.txt

Old Glast Heim with Temporal Enchant:
https://github.com/idathena/trunk/blob/master/npc/re/instances/OldGlastHeim.txt

* **Description of Issue**: 
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Atemo** [comment]
We already opened a PR for OGH : https://github.com/rathena/rathena/pull/1554
kRO made some change on Jitterbug instance (instance removed/ replaced?). Also we try to follow ragnarok episode, posterius videbimus.

**Comment by mazvi** [comment]
thanks very much ^^

**Comment by aleos89** [comment]
I'll go ahead and close this since one is in a PR and Atemo is progressing through others.
