### ISSUE TITLE
Skill Cooldown Bug

### ISSUE THREAD

**Issue by Myrdin** [rathena/rathena#2632]
* **rAthena Hash**: 03da2f6854677a0266aaae8d498fa71ddf41a666

* **Client Date**: 2017-10-25

* **Server Mode**: RENEWAL

* **Description of Issue**: Skill Cooldown bypassed when skill bar hidden
  * Result: Skill does not have any cooldown when casting the same/other skill when skill bar is hidden
  * Expected Result: Skill cooldown should not be able to bypass regardless hidden skill bar.
  * How to Reproduce: 
1. Put any skill (eg: Comet) at any location in the skill bar.
2. Hide the skill bar (thru F12).
3. Now press the shortcut key for the skill.
4. Also if double click thru skill tree interface will also result no cooldown at all.
5. If the skill bar is not hidden, the skill will have cooldown.

* **Modifications that may affect results**: No mod at all.

**Comment by sader1992** [comment]
i must say it's hard to believe this bug is possible XD
i will test this

**Comment by sader1992** [comment]
PRE-RE on a49a1a5 ( 19 / 11 / 2017)
no bug like that
didn't test it on the renewal
however did you test that on normal char or gm ? maybe the gm account have something bypass the cooldown

**Comment by Myrdin** [comment]
@sader1992 : Thanks for highlighting it to me. Gosh I didnt realize group.conf got messed up where 
"skill_unconditional: true" would bypass the skill cooldown.

I believe it's working as intended then. Sorry for the sudden shocking invalid bug report.
