### ISSUE TITLE
Magical Ring (ID : 28377) Wrong Script (?)

### ISSUE THREAD

**Issue by uddevil** [rathena/rathena#2635]
* **rAthena Hash**: a49a1a52a3e0036c9cad3794c4db5628f088b443

* **Client Date**: 2015-11-04a RagexeRE

* **Server Mode**: Tested on Renewal

* **Description of Issue**: 
  * Result: 
     Magical Ring (Item ID 28377) Script : `bonus2 bMagicAddEle,Ele_Fire,5; bonus2 bMagicAddEle,Ele_Water,5; bonus2 bMagicAddEle,Ele_Earth,5; bonus2 bMagicAddEle,Ele_Wind,5; if (BaseLevel > 4) { bonus2 bSkillAtk,"MG_FIREBOLT",BaseLevel/5; bonus2 bSkillAtk,"MG_COLDBOLT",BaseLevel/5; bonus2 bSkillAtk,"MG_LIGHTNINGBOLT",BaseLevel/5; bonus2 bSkillAtk,"WZ_EARTHSPIKE",BaseLevel/5;`
  * Expected Result: 
    Should it be `bonus2 bMagicAtkEle,Ele_Fire,5; bonus2 bMagicAtkEle,Ele_Water,5; bonus2 bMagicAtkEle,Ele_Earth,5; bonus2 bMagicAtkEle,Ele_Wind,5; if (BaseLevel > 4) { bonus2 bSkillAtk,"MG_FIREBOLT",BaseLevel/5; bonus2 bSkillAtk,"MG_COLDBOLT",BaseLevel/5; bonus2 bSkillAtk,"MG_LIGHTNINGBOLT",BaseLevel/5; bonus2 bSkillAtk,"WZ_EARTHSPIKE",BaseLevel/5;` (?)
  * Official Information:
     I don't know about official, but from irowiki and divine pride's description :
     

> Increases the damage of Water property magical attacks on targets by 5%.
Increases the damage of Earth property magical attacks on targets by 5%.
Increases the damage of Fire property magical attacks on targets by 5%.
Increases the damage of Wind property magical attacks on targets by 5%.
Increases the damage of Cold Bolt by 1% for every 5 base levels.
Increases the damage of Earth Spike by 1% for every 5 base levels.
Increases the damage of Fire Bolt by 1% for every 5 base levels.
Increases the damage of Lightning Bolt by 1% for every 5 base levels.

![chrome_2017-11-24_23-07-40](https://user-images.githubusercontent.com/10105610/33218052-699c207a-d16d-11e7-9394-915b134a65d8.png)
![chrome_2017-11-24_23-07-34](https://user-images.githubusercontent.com/10105610/33218053-69e2804c-d16d-11e7-87e8-d05bb0382873.png)

Divine-pride source : [https://www.divine-pride.net/database/item/28377/magical-ring-1](https://www.divine-pride.net/database/item/28377/magical-ring-1)
Irowiki source : [http://db.irowiki.org/db/item-info/28377/](http://db.irowiki.org/db/item-info/28377/)

* **Modifications that may affect results**: 
   Change **bMagicAddEle** to **bMagicAtkEle**

**Comment by Jeybla** [comment]
@uddevil please leave the issues open until the fix is merged to the master.

**Comment by uddevil** [comment]
@Jeybla sorry, i don't realize that is not merged yet.
