### ISSUE TITLE
[Suggestion] Case "String":

### ISSUE THREAD

**Issue by sader1992** [rathena/rathena#2649]
Edit:
or Case Var:
hooking the case to the option not count to it

by any chance that rAthena can support case string ?

Example:

`switch(select("Yes:No")){`
     `Case "Yes": mes"passed"; break;`
     `Case "No": end;`
`}`
or
`switch(select("Yes","No")){`

the reason

`.@string$ = "Option0";`
`if(.option1)`
     `.@string$ += ":Option1";`
`if(.oprion2)`
     `.@string$ += ":Option2";`
`switch(select(.@string$)){`
     `Case "Option0": mes"Option0"; break;`
     `Case "Option1": mes"Option1"; break;`
     `Case "Option2": mes"Option2"; break;`
`}`

while now

`switch(select(.@string$)){`
     `Case 1: mes"Option0 = always true"; break;`
     `Case 2: mes"it's Option1 if .option1 is true and Option2 if .option1 is false "; break;`
     `Case 3: mes"Option2"; break;`
`}`

i am sure you can imagine a lot of usage for it since it's used in a lot of languages

**Comment by thegreatpeon** [comment]
C++ does not support switch statements based on strings.

Here's a decent read on alternatives, though:
https://stackoverflow.com/questions/650162/why-switch-statement-cannot-be-applied-on-strings

**Comment by sader1992** [comment]
i am not talking about the source am talking about the command scripts see the example above

**Comment by thegreatpeon** [comment]
Ah, not sure about the command scripts. I'm a newbie around here and don't know much about them yet.

I do know C++, though, and, while C++ does have switch statements, they don't work with strings. Only on ints, enums, and chars. But I suppose that's not really what you're asking about.

**Comment by sader1992** [comment]
i did find (not perfect) way to do that so i think 

`.@string$[0] = "Option0";`
`if(.option1)`
`	.@string$[1] = "Option1";`
`if(.oprion2)`
`	.@string$[2] = "Option2";`
`menu .@string$[0],-,.@string$[1],L_Option1,.@string$[2],L_Option2;	`
	`mes"Option0"; end;`
	`L_Option1: mes"Option1"; end;`
	`L_Option2: mes"Option2"; end;`

but i will leave this open maybe rathena would like the idea to make case string:

**Comment by Stolao** [comment]
This would be a unnecessary addition to the code base as what your try to achieve can be done with the current system using something along these lines. (On phone so hard to type)



Setarray .menus$,"option 1","option 2","option 3";
Switch(select (implode(.menus$))){


}
 
Among other ways I won't list here



That said I did find a possible decent solution in 
https://stackoverflow.com/questions/4165131/c-c-switch-for-non-integers

**Comment by lighta** [comment]
Yeah to switch to non integer you just have to hash your other type. (The hash is now an int and you can switch) that what they do in most langage anyway..
About the original idea:
Perhpas yeah, even if @Stolao gave how you should do it currently it's always nice to have more option plus more direct solution from src are more efficient. My concern tough is that if we do that I think that imply of introducing an escape character as well. As in your case ":" is the delimiter. But how what if I want an entry like. "Opt1:fu","be:bop". Entry that i wanted : as part of it..

**Comment by Jeybla** [comment]
```C
setarray .@menu$[0] = "Option0";
if(.option1)
  setarray .@menu$[getarraysize(.@menu$)] += ":Option1";
if(.option2)
  .@string$[getarraysize(.@menu$)] += ":Option2";

.@selected = select(.@string$)-1;
if( .@selected < 0 || .@selected >= getarraysize(.@menu$) )
  close;
mes "Selected option: "+.@menu$[.@selected]; break;
```
I see no need for switch-case supporting strings. I know it can be handy, but with a little effort you can work around it, and get a script which likely performs much better.
Implementing something like that could become complicated, especially when the hash algorithm has collisions. @lighta which hash would be applicable in that scenario?

**Comment by Lemongrass3110** [comment]
Each hash has possible collisions, otherwise it would not be hashing but encryption.
Having touched that hash table before I can tell you that inside each entry it is holding all of the values with the same hash so you could still do a string compare on those, not that it would be very likely to have two of those in one switch statement(which we could even validate at parsing time).

Nevertheless I think this feature would use too much time for it's small benefits in readability. Knowing the current implementation of the script engine I can tell you that this would be a horrible task to do.

**Comment by lighta** [comment]
If we want to do a switch string, I'd for FNV. 
https://en.wikipedia.org/wiki/Fowler%E2%80%93Noll%E2%80%93Vo_hash_function
https://stackoverflow.com/questions/114085/fast-string-hashing-algorithm-with-low-collision-rates-with-32-bit-integer
