### ISSUE TITLE
[Suggestion] Implement Dual Dagger Double Attack Critical Guillotine Cross

### ISSUE THREAD

**Issue by reymarbc** [rathena/rathena#2652]
In this GX Guide [LimitRO GX Guide](https://www.limitro.com/forums/topic/4567-mvp-guillotine-cross-dual-dagger-da-critical-build/) the OP said that since 2016 kRO implemented this already, 
I just thought that implementing this to our GX makes a huge impact in this class
Thank you for the devs specially @aleos89

**Comment by admkakaroto** [comment]
NovaRO has already implemented that too.

**Comment by Atemo** [comment]
Duplicate of https://github.com/rathena/rathena/issues/1788
