### ISSUE TITLE
Taekwon skill tree

### ISSUE THREAD

**Issue by lelouch22** [rathena/rathena#2653]
* **rAthena Hash**: 02044c0

* **Client Date**: 2015-11-04

* **Server Mode**: Pre-Renewal

* **Description of Issue**: Taekwon skill tree won't add skills just the basic skills only i also tryed using @skillall command but its no use.

![screenrathena000](https://user-images.githubusercontent.com/4976551/33369747-7d8e8746-d530-11e7-8ec3-5f14d3f847a1.jpg)

**Comment by Daegaladh** [comment]
I can't reproduce this bug on a fresh rathena. You have lv255/120 maybe you broke something with your customs.

**Comment by lelouch22** [comment]
Solved thanks :D
