### ISSUE TITLE
Opendressroom second costume not showing

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#2655]
* **rAthena Hash**: ca1b980

* **Client Date**: 20170517RE

* **Server Mode**: RENEWAL

* **Description of Issue**: Opendressroom second costume not showing.
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment]
Insufficient error description.

Ps: LUA problem.
