### ISSUE TITLE
Can't enable title on title UI.

### ISSUE THREAD

**Issue by hnomkeng** [rathena/rathena#2660]
* **rAthena Hash**: 02044c0
* **Client Date**: 2017-06-14b
* **Server Mode**: Pre-renewal
* **GCC**: 5.3.1
* **Description of Issue**: Can't enable title on title UI.
Vdo : https://youtu.be/fTlabDAS-WE

**Comment by sader1992** [comment]
open your database char table
in your char add a title id let's say 1034
relogin into the server and see your char does it have title 1034 = [VIP] ?

**Comment by hnomkeng** [comment]
@sader1992  add on char table is show.

**Comment by hnomkeng** [comment]
I can disable title on GUI. I can't enable title on GUI.

**Comment by sader1992** [comment]
do you get any message about unknown packet in the terminal ?

**Comment by hnomkeng** [comment]
@sader1992 No have error or warning msg on console.

**Comment by sader1992** [comment]
i did test it now i can confirm this it's the same on 2015-11
i am not sure it's from rAathena but it seems to

**Comment by hnomkeng** [comment]
@sader1992  after hash c5ceda0 not working ?

**Comment by sader1992** [comment]
in between

**Comment by sader1992** [comment]
i think maybe the issue here > 1c66035761d256474bde7df703eb406255514d8c 
this is the only update that edit the title system (in between the hashs )
not sure it's better to wait for rAthena developers
