### ISSUE TITLE
Can 2 login server => 1 char server?

### ISSUE THREAD

**Issue by hotspicy945** [rathena/rathena#2664]
* **Client Date**: 
<20160203>

* **Server Mode**: 
<Renewal>

Hello
Can Rathena 2 login server to 1 char server?
like this image

![2login](https://user-images.githubusercontent.com/27738134/33515192-9fac3e10-d79a-11e7-83e0-1f8690f20aad.jpg)

Now I only can use login server(publice_ip_1)  => char server(public_ip_3) => map server (public_ip_3)
Because I want protection my server.
If attacker attack my  login server(publice_ip_1) , my online player (map server) still can play.
Just can't login untill attack finish.

If I had 2 login server, then he attack my login server_public_ip_1,
the player can use my login server_2(public_ip_2) to login in my server. 

Thank you

**Comment by Lemongrass3110** [comment]
This is not a support platform - **again**.
Please use our forum.
