### ISSUE TITLE
Ingame Browser

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#2665]
* **rAthena Hash**: 7c1a882

* **Client Date**: 20170517RE

* **Server Mode**: RENEWAL

* **Description of Issue**: Iam using nova search from https://rathena.org/board/topic/102885-novas-script-collection/
  * Result:  Link ingame browser online open once, must relog/select character to open link again.
  * Expected Result:  Link ingame browser can open many time without relog/select character.
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
This is not an rAthena bug as this is a pure client feature.
