### ISSUE TITLE
Limited Power Booster (Item ID 14766) Script Error

### ISSUE THREAD

**Issue by uddevil** [rathena/rathena#2666]
* **rAthena Hash**: 4128740a1a2d3e1836a48a3f298a13c73c98afd1

* **Client Date**: 2015-11-04a RagexeRE

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: 
     Error when consuming Limited Power Booster (Item ID 14766)
     ![putty_2017-12-02_23-39-03](https://user-images.githubusercontent.com/10105610/33517633-1c7d15b2-d7ba-11e7-9c1e-2d65be531845.png)
     Its because of `bonus bAddClass,Class_All,1`

  * How to Reproduce:  
     Use Item ID 14766
  * Official Information:
     I don't know if its available in official.
  

* **Modifications that may affect results**: 
  
  
    On Item ID 14766, change `bonus bAddClass,Class_All,1` to `bonus2 bAddClass,Class_All,1`
    Reference : https://github.com/rathena/rathena/blob/master/doc/item_bonus.txt Line 232

**Comment by Jeybla** [comment]
https://www.divine-pride.net/database/item/14766
> divine pride: ATK, MATK + 1%,
> setting: bonus2 bAddClass,Class_All,1; bonus bMatkRate,1;

Just wondering: is `bAddClass` correct, or would be `bAtkRate` more suitable in this case?

**Comment by uddevil** [comment]
This actually confusing me too, a lot of other items has description of "increase atk" but the script uses bAddClass, what is the difference?

**Comment by aleos89** [comment]
Aegis applies item bonuses based on [Class/Race](https://rathena.org/board/topic/91023-item-bonuses-updated). So it would be beneficial for us to continue following this method.

**Comment by aleos89** [comment]
Fixed in f639c00.
