### ISSUE TITLE
Bug - Enchant bonus

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#2668]
* **rAthena Hash**: 6f985080a8b071e5869679e430274a4b166971c2
* **Client Date**: 2017-05-31
* **Server Mode**: Renewal
* **Description of Issue**: The bonus given when removing the item is not being activated if the script is on an enchantment stone.

EXP: Enchant item 4876 Runaway Magic | heal 0,-2000;

  * Result: when the item is removed it does not remove the SP from the user.
  * How to Reproduce: The problem can be reproduced with any enchantment stone that has a bonus of when the item is removed.

**Comment by mrjnumber1** [comment]
Youre right~
the relevant code in pc_unequipitem checks only up to sd->inventory_data[n]->slot cards, rather than every slot when unequipping. It should instead iterate to MAX_SLOTS amount of times.

**Comment by mrjnumber1** [comment]
ahh.. github won't let me edit, but the same thing applies for pc_equip as well! it only iterates up to id->slot times
