### ISSUE TITLE
Issue in Ragna exe

### ISSUE THREAD

**Issue by crimson-sky** [rathena/rathena#2669]
* **rAthena Hash**: 

* **Client Date**: 12/3/17

* **Server Mode**: renewal

* **Description of Issue**: 
  * Result:  When i click on the ragna patch a pop messages appear about skidrow and grannynewmeshdeformer not being found. I tried following steps the internet in them but nothing works. I don't have an idea about how this works and this is my first time doing this. I hope you can check out this issue guys. I dont have clue what to do with it.
  * Expected Result: I'm really need some help in setting the game up in my pc.
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**: 
  
  
![image](https://user-images.githubusercontent.com/34201500/33521917-c8475fb4-d81a-11e7-9dfa-b3de53097fab.png)
![image](https://user-images.githubusercontent.com/34201500/33521941-3600cb94-d81b-11e7-9096-7055816f99ba.png)

**Comment by sader1992** [comment]
this is not rathena issue 
i would suggest ask for support in the forum
https://rathena.org/board/forum/19-client-side-support/
or as i see you use those files 
https://rathena.org/board/topic/109823-ragnarok-online-complete-offline-pack-2017-make-your-ro-server-in-less-then-5-minutes/
so ask there
