### ISSUE TITLE
Unable to Start rAthena

### ISSUE THREAD

**Issue by keitenai** [rathena/rathena#2670]
* **rAthena Hash**: 4dde4c6

* **Client Date**:  Any

* **Server Mode**: Any

* **Description of Issue**: 
Unable to run rAthena after compiling on VS2017 with fresh clean rathena copy.
OS: Windows 7

Upon testing the updates i found out that this issue started with 53db435

* **Modifications that may affect results**:  None

![capture](https://user-images.githubusercontent.com/11855571/33524597-f2e3fbac-d85a-11e7-910a-912c79bf7885.PNG)

**Comment by sader1992** [comment]
I think this from your system not from rAthena 
however it's better to give more info like
system/version
compiler
did you follow any guide ?
I would suggest you ask in the forum it's more likely that is system issue

**Comment by keitenai** [comment]
System/Version? do you mean OS?
I'm using windows 7. Compiler is VS2017.

the last rAthena version i was using that worked fine was f59298a .
I just updated the clean trunk, compile then it suddenly failed to run.

**Comment by sader1992** [comment]
how did you update rathena ?
this `with fresh clean rathena` you mean you try to download new rathena and the same error ?

**Comment by aleos89** [comment]
How are you running the servers? From the individual server batch file (logserv.bat, charserv.bat, mapserv.bat) or from runserver.bat? I tested all 4 batch files and was able to run them just fine using the same hash as you.

**Comment by keitenai** [comment]
i run the server using runserver.bat.
i even tried to run the individual for charserv, logserv, and mapserv but it wont run. cmd window will just appear for about 100ms then it will shut itself instantly.

**Comment by lighta** [comment]
can I see you runserver.bat, serv.bat, charserv.bat loginserv.bat mapserv.bat. 
could do a github gist to show them : https://gist.github.com/
If you in hurry just revert : https://github.com/rathena/rathena/commit/53db4358b7279beaf22b4e9e6a1c44a42a622c66 in meantime.

**Comment by keitenai** [comment]
https://gist.github.com/keitenai/67a6c291fbd577fd4c3dd614d3e0c7d5

**Comment by sader1992** [comment]
can you try
run the cmd as admin >navigate to rathena folder > run runserver.bat from the cmd

**Comment by keitenai** [comment]
@sader1992  already tried that and still thesame

**Comment by lighta** [comment]
can you try to edit. in serv.bat
goto START
to
goto :START

why does this issue appear now ?

**Comment by keitenai** [comment]
https://github.com/rathena/rathena/commit/53db4358b7279beaf22b4e9e6a1c44a42a622c66#diff-669de2a7329a405d36615537e944cf83R47

is this supposed to be "resart_mode" or should this be "restart_mode"?

**Comment by lighta** [comment]
should be "restart_mode" the variable was badly named (cuz I'm a bt dislexsic and don't always take time to review).
But the variable name is coherent in the file so that not your issue. (if that bother you rename all the resart_mode to restart_mode).

**Comment by keitenai** [comment]
i did change "goto START" to "goto :START", and even renamed "resart_mode" to "restart_mode" but still thesame.

**Comment by keitenai** [comment]
I moved the location of ":START" after the ":EXIT1" and it made it run the server.
I also tried moving it to other positions and it works fine. But placing it on its default position fails to run the server.... weird...

![capture](https://user-images.githubusercontent.com/11855571/33527504-20576696-d88d-11e7-8ee6-db74918c5b51.PNG)

**Comment by lighta** [comment]
I suspect this as to do with some encoding that went wrong.

**Comment by hendra814** [comment]
i'm still got this problem after lastest update

**Comment by Atemo** [comment]
"lastest" is not a valid hash.
"i'm still got this problem" is not a valid description of your issue.
Unless you provide more information this issue is considered fixed.

**Comment by keitenai** [comment]
he probably meant that he's having same issue as i did
