### ISSUE TITLE
Magic Intensifier Ring not adding MATK

### ISSUE THREAD

**Issue by reymarbc** [rathena/rathena#2672]
* **rAthena Hash**: 4dde4c664b66a814ecf01fbb27afcf539e7eaa0d

* **Client Date**: 2015-11-05

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Magic Intensifier Ring not adding MATK
  * Expected Result: Magic Intensifier Ring add +5% MATK
  * How to Reproduce: equip
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by admkakaroto** [comment]
Works perfectly, however the bonus on attack in percentage does not add in its attributes window, test the damage before reporting.

**Comment by aleos89** [comment]
Works for me as well.
