### ISSUE TITLE
Chain Lightning vs icewall

### ISSUE THREAD

**Issue by Sweet520** [rathena/rathena#2674]
* **rAthena Hash**: [b2d904b](https://github.com/rathena/rathena/commit/b2d904b764f43137547e5ed689af2b5983b8b234)

* **Client Date**: 20170614

* **Server Mode**: Renewal

Skill information : [Chain Lightning](http://irowiki.org/wiki/Chain_Lightning)

* **Description of Issue**: 
  * Result: Chain Lightning will hit the ice wall
  * Expected Result: Chain Lightning will not hit the ice wall. If you choose the ice wall as the first target, chain lightning will hit ice wall once then jump to other targets except the ice wall

  * How to Reproduce: 
  * Official Information: This can not be confirmed without futher information. But i thing i m right. Hope someone can advise
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Chain Lightning should not bounce on Ice Wall.
