### ISSUE TITLE
The @where command doesn't work with names having spaces

### ISSUE THREAD

**Issue by Tokeiburu** [rathena/rathena#2675]
* **rAthena Hash**: ab01424

* **Client Date**: Any

* **Server Mode**: Any

* **Description of Issue**: When using `@where` for a character with spaces, it will cut off the name with the first string instead.
  * Result: 
  * Expected Result: 
  * How to Reproduce: Type `@where Test Player`.

In atcommand.cpp, I'd simply replace:
```
if (!message || !*message || sscanf(message, "%23s[^\n]", atcmd_player_name) < 1) {
```
with
```
if (!message || !*message || sscanf(message, "%23[^\n]", atcmd_player_name) < 1) {
```

**Comment by Jeybla** [comment]
We should check that for other atcommands, too

**Comment by aleos89** [comment]
A quick search reveals this is the only command.
