### ISSUE TITLE
Evil Spirit Bones not dropping for Purified Bones quest

### ISSUE THREAD

**Issue by Indigo000** [rathena/rathena#2677]
* **rAthena Hash**: c5b7850

* **Client Date**: Irrelevant

* **Server Mode**: Irrelevant

* **Description of Issue**: 
  * Result: The Purified Bones (http://irowiki.org/wiki/Purified_Bones) quest currently does not work. The Evil Spirit Bones item (6507) cannot be obtained in any way.
  * Expected Result: Various mobs to drop the Evil Spirit Bone (6507) item. Possibly in a similar way to the malaya_ma_fild01_mon NPC?
  * Official Information: http://irowiki.org/wiki/Purified_Bones

**Comment by aleos89** [comment]
db/re/quest_db.txt
```
// The MobID*, NameID*, and Rate* reflect special values for quests that can drop an item at given rate from given mob.
// If no MobID* is given, then any mob has a chance to drop the given ItemID*.

7406,0,0,0,0,0,0,0,2309,6507,5000,2313,6507,5000,2314,6507,5000,"Agree to Collecting Bones!"
```
According to this: 2309 (Bungisngis), 2313 (Tikbalang), and 2314 (Tiyanak) drop the bones.

**Comment by Lemongrass3110** [comment]
@Indigo000 any feedback to what aleos said?
Please note that this quest is renewal only and is not existant in pre-renewal(because you wrote: server mode irrelevant).

**Comment by Indigo000** [comment]
Ah, he is totally correct. My fault entirely.

Thanks for clearing that up!
