### ISSUE TITLE
chain lightning chain damage problem

### ISSUE THREAD

**Issue by Sweet520** [rathena/rathena#2678]
* **rAthena Hash**: [b2d904b](https://github.com/rathena/rathena/commit/b2d904b764f43137547e5ed689af2b5983b8b234)

* **Client Date**: 20170614

* **Server Mode**: Renewal

Each damage of chain lightning always be the same. I thing maybe there is something wrong with the chain damage bonus

[Chain Lightning](http://irowiki.org/wiki/Chain_Lightning)

* **Description of Issue**: 
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by admkakaroto** [comment]
@aleos89 Where is this PR? I can not find it ... has it already been applied to the emulator?

**Comment by aleos89** [comment]
Done, sorry I seemed to have forgotten about creating the PR.
