### ISSUE TITLE
cannot start 'runserver.bat' windows 10

### ISSUE THREAD

**Issue by gusjungsza** [rathena/rathena#2679]
**Hash** : https://github.com/rathena/rathena/commit/0fa57e2bbe38f56ce247b23e611144a4076ef150

**show message**
"restart_mode=on"
The system cannot find the batch label specified - START

I change name label 'START' to 'others name' in serv.bat, it work!

**Comment by wabbuwabbu** [comment]
Not sure why this issue was closed.
In 2022 this error still prevails:
![Untitled](https://user-images.githubusercontent.com/45298589/197336811-dc91bdb0-15ba-491d-b0b0-74ce0d17df45.png)

**Comment by wabbuwabbu** [comment]
> Not sure why this issue was closed. In 2022 this error still prevails: ![Untitled](https://user-images.githubusercontent.com/45298589/197336811-dc91bdb0-15ba-491d-b0b0-74ce0d17df45.png)

Might be an encoding problem.
Fix:
serv.bat

From:
`
REM Windows 2000, XP, Vista, 7
:RESTART_NT
REM There is no CHOICE in 2000 and XP, but you get asked whether to
REM abort the batch file, when pressing Ctrl+C in PING.
IF "%1"=="mapcache.exe" GOTO END
if "%restart_mode%" == "off" GOTO END
ECHO Restarting in 15 seconds, press Ctrl+C to cancel.
PING -n 15 127.0.0.1 > NUL

:START_RA
%1
ECHO.
REM Return value 1 is EXIT_FAILURE
IF ERRORLEVEL 1 GOTO EXIT1
REM Return value is not 0 the process has crashed
IF NOT ERRORLEVEL 0 GOTO CRASHED
REM Return value 0 is EXIT_SUCCESS
ECHO %2 has shutdown successfully.
GOTO RESTART_NT

:EXIT1
ECHO %2 has terminated abnormally.
GOTO RESTART_NT
`

Move the :EXIT1 in between :RESTART_NT & :START_RA, like so:
` 
REM Windows 2000, XP, Vista, 7
:RESTART_NT
REM There is no CHOICE in 2000 and XP, but you get asked whether to
REM abort the batch file, when pressing Ctrl+C in PING.
IF "%1"=="mapcache.exe" GOTO END
if "%restart_mode%" == "off" GOTO END
ECHO Restarting in 15 seconds, press Ctrl+C to cancel.
PING -n 15 127.0.0.1 > NUL

:EXIT1
ECHO %2 has terminated abnormally.
GOTO RESTART_NT

:START_RA
%1
ECHO.
REM Return value 1 is EXIT_FAILURE
IF ERRORLEVEL 1 GOTO EXIT1
REM Return value is not 0 the process has crashed
IF NOT ERRORLEVEL 0 GOTO CRASHED
REM Return value 0 is EXIT_SUCCESS
ECHO %2 has shutdown successfully.
GOTO RESTART_NT 
`

**Comment by vstumpf** [comment]
After 5 years, you can probably create a new issue.

That being said, It works on my machine, and on all of our ci
Are you sure you didn't download it with the wrong line endings? When you modify the script and save it, maybe your editor sees LF and converts the file to CRLF

**Comment by wabbuwabbu** [comment]
> After 5 years, you can probably create a new issue.
> 
> That being said, It works on my machine, and on all of our ci Are you sure you didn't download it with the wrong line endings? When you modify the script and save it, maybe your editor sees LF and converts the file to CRLF

After 5 years, there was no solution to this issue.
Where would I have downloaded the wrong line endings? https://github.com/rathena/rathena/wiki/Install-on-Windows
Did a fresh install using:

Edition    Windows 10 Home
Version    21H2
Installed on    ‎21/‎03/‎2021
OS build    19044.2130
Experience    Windows Feature Experience Pack 120.2212.4180.0


**Found a solution that works for me by the way:**
> > Not sure why this issue was closed. In 2022 this error still prevails: ![Untitled](https://user-images.githubusercontent.com/45298589/197336811-dc91bdb0-15ba-491d-b0b0-74ce0d17df45.png)
> 
> Might be an encoding problem. Fix: serv.bat
> 
> From:
> 
> ```
> REM Windows 2000, XP, Vista, 7
> :RESTART_NT
> REM There is no CHOICE in 2000 and XP, but you get asked whether to
> REM abort the batch file, when pressing Ctrl+C in PING.
> IF "%1"=="mapcache.exe" GOTO END
> if "%restart_mode%" == "off" GOTO END
> ECHO Restarting in 15 seconds, press Ctrl+C to cancel.
> PING -n 15 127.0.0.1 > NUL
> 
> :START_RA
> %1
> ECHO.
> REM Return value 1 is EXIT_FAILURE
> IF ERRORLEVEL 1 GOTO EXIT1
> REM Return value is not 0 the process has crashed
> IF NOT ERRORLEVEL 0 GOTO CRASHED
> REM Return value 0 is EXIT_SUCCESS
> ECHO %2 has shutdown successfully.
> GOTO RESTART_NT
> 
> :EXIT1
> ECHO %2 has terminated abnormally.
> GOTO RESTART_NT
> ```
> 
> Move the :EXIT1 in between :RESTART_NT & :START_RA, like so:
> 
> ```
> REM Windows 2000, XP, Vista, 7
> :RESTART_NT
> REM There is no CHOICE in 2000 and XP, but you get asked whether to
> REM abort the batch file, when pressing Ctrl+C in PING.
> IF "%1"=="mapcache.exe" GOTO END
> if "%restart_mode%" == "off" GOTO END
> ECHO Restarting in 15 seconds, press Ctrl+C to cancel.
> PING -n 15 127.0.0.1 > NUL
> 
> :EXIT1
> ECHO %2 has terminated abnormally.
> GOTO RESTART_NT
> 
> :START_RA
> %1
> ECHO.
> REM Return value 1 is EXIT_FAILURE
> IF ERRORLEVEL 1 GOTO EXIT1
> REM Return value is not 0 the process has crashed
> IF NOT ERRORLEVEL 0 GOTO CRASHED
> REM Return value 0 is EXIT_SUCCESS
> ECHO %2 has shutdown successfully.
> GOTO RESTART_NT 
> ```
