### ISSUE TITLE
script commands: getitem3 and delitem3 not work

### ISSUE THREAD

**Issue by rAthenaCN** [rathena/rathena#2682]
* **rAthena Hash**: 3f88826

* **Client Date**: 20170517

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: In use, getitem3 and delitem3 will map-server crash.
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**: 
  
  
Can anyone fix it? thanks!

**Comment by Lemongrass3110** [comment]
Please follow the issue template.
Provide the missing info and any further helpful information.

**Comment by rAthenaCN** [comment]
I'm sorry, I now reedit issues with PC.

**Comment by secretdataz** [comment]
Please post your script that caused the crash, if possible

**Comment by Lemongrass3110** [comment]
Could you post your script please? Or at least the part around the getitem3 call.

**Comment by cydh** [comment]
somehow confirmed. I want to blame @aleos89 for this 900548f34ba90634b5c601efcf40cd34c6937b7e xD
I never mean to check the value's & param's array and those vars supposed to be removed but I forgot LOL
