### ISSUE TITLE
[BUG] Giant Growth atk-based physical damage by 250%

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#2684]
* **rAthena Hash**: 

https://github.com/rathena/rathena/commit/6afc36255be1c166a77539a90d927e084264c162

* **Client Date**: 

20170614

* **Server Mode**: 

Renewal

* **Description of Issue**: 

  * Result:
  
  After using the Turisus Runestone rune, it should increase melee physical damage by 250% and is not increasing.
  
  
  * Expected Result: 
  
Increases atk-based physical damage by 250% and has a 15% chance to deal a bonus damage of 200% over the amplified damage
  
  
  * How to Reproduce: 
  
  Use the rune item id: 12731. Melee physical attack and you will see that it is not increasing atk by 250%.
  
  
  * Official Information: 
  https://forums.warpportal.com/index.php?/topic/208595-kro-runestones-improvement/
  http://ro.gnjoy.com/news/devnote/View.asp?category=1&seq=3708477&curpage=1

* **Modifications that may affect results**: 
 
 The emulator rA is virgin, with no source modification.

**Comment by Paoly28** [comment]
also crush strike sometimes bugs out dealing more the 5x the intended damage

**Comment by Badarosk0** [comment]
I tested and still did not increase the damage by 250%. Even with the changes still not working. @aleos89

**Comment by aleos89** [comment]
How are you testing it?

**Comment by Badarosk0** [comment]
I use the rune and attack with melee. The damage must be increased by 250% with melee attacks.

**Comment by aleos89** [comment]
Do you have a weapon equipped?

**Comment by Badarosk0** [comment]
With weapon and without weapon, nothing changes.

**Comment by aleos89** [comment]
I just tested this and it increased my melee damage just fine after consuming a Thurisaz Rune.

**Comment by Paoly28** [comment]
maybe you are pertaining to crushing strike cause it doesn't work anymore with giant growth, only melee skills work.

**Comment by Badarosk0** [comment]
Don't work for me.
https://www.youtube.com/watch?v=9wCYhQpZoPI

**Comment by aleos89** [comment]
My results: https://imgur.com/a/7Qk1n

**Comment by Badarosk0** [comment]
It's working, yes! Somehow tortoise did not update the script file. Weird... Thank you! @aleos89
