### ISSUE TITLE
[suggestion] Generate client files

### ISSUE THREAD

**Issue by sader1992** [rathena/rathena#2687]
SO this started from this post [
[Suggestion] NAVI generator for prere and renewal for actual coordinates at navigation system.](https://rathena.org/board/topic/112642-suggestion-navi-generator-for-prere-and-renewal-for-actual-coordinates-at-navigation-system/)
i did try to make it in c# >> it take a lot of processing time [A Lot] to generate the files and the result is not perfect

so here the suggestion
making a new config in conf/map_athena.conf on/off [off by default]
when it's on
every time after starting/restarting rAthena it will [delete/create] new folder named data inside rathena folder
and generate the files

- Navigation
navi_link_krpri.lub
navi_linkdistance_krpri.lub
navi_map_krpri.lub
navi_mob_krpri.lub
navi_npc_krpri.lub
navi_npcdistance_krpri.lub

- Item Trade
ItemMoveInfoV5.txt

and if there is any other file like this we add it here

the files would be created inside folders that the same folders they are in [in the data.grf]

the reason why i did say config not tool
those files may need to be updated every time some one add new npcs or monsters
same for the item trade
and also as i thing it's faster if we let rAthena write those files while it read the server files i think also this would be more efficiency rather then writing a new tool for that

the starting will take longer but the server owner can disable the option in the conf
also it would be disabled by default
if not a config maybe something like .bat
or maybe you would like it to be a tool
anyway it would be very good to have this in rathena

**Comment by Lemongrass3110** [comment]
I thought of this a lot of times as well already, but I came to the conclusion that it would be better to keep this separated from the main rAthena repository.
Might be a good idea to get this back onto the plate once we have modules/plugins as well. :-)

**Comment by RagnaWay** [comment]
Any news?

**Comment by OptimusM** [comment]
I think this is the best ocation to support rA devs by crowdfunding, im pretty sure that will be a good motivation to focus on this project, that as Lemon said, is not directly related to rA, but alot of people are intrested in.
Good work~!

**Comment by sader1992** [comment]
I started it but i stop cuz It's a little hard for me to follow what rathena need , for me is to create an external program that is self dependent easier , but as the dev mentioned before it's better to make it work like `mapcache` and `csv2yaml`
will give it another try soon.

**Comment by alisonrag** [comment]
Hercules use a plug-in to generate all navigation files, how much harder this can be to port from herc to rA?

Reference:
https://github.com/HerculesWS/StaffPlugins/tree/master/Haru/naviluagenerator
