### ISSUE TITLE
Show Monster HP

### ISSUE THREAD

**Issue by RadianFord** [rathena/rathena#269]
I was looking for this and i saw it but it didn't work.
// Display some mob info next to their name? (add as needed)
// (does not works on guardian or Emperium)
// 1: Display mob HP (Hp/MaxHp format)
// 2: Display mob HP (Percent of full life format)
// 4: Display mob's level
show_mob_info: 0

I tried to change it to 4 / 2 / 1 and do @reloadbattleconf but nothing happens. can someone check this one?

**Comment by Playtester** [comment]
But when restarting it works?

**Comment by RadianFord** [comment]
Still nothing happens @Playtester

**Comment by anacondaqq** [comment]
@RadianFord i can't confirm it. With latest (06.02.2015) rAthena i can see monsters HP on 2010-07-30 Exe

**Comment by RadianFord** [comment]
@anacondaqq mine is not far from that date by the way how or where can you see the code for that thing? I need to compare the latest and my revision.


I am using 2013 12 23c client.

**Comment by anacondaqq** [comment]
@RadianFord (latest rAthena), with 
>  show_mob_info: 0

![  show_mob_info: 0 ](http://i6.5cm.ru/i/6IKL.png)

After changing to 
> show_mob_info: 1

![show_mob_info 1](http://i6.5cm.ru/i/qJU3.png)

But! You need to do next:

1. @reloadbattleconf
2. @reloadmobdb
3. @killmonsters

Try it, i think you understand.

**Comment by RadianFord** [comment]
yea i actually did that but mine don't work like that i don't know why.

**Comment by anacondaqq** [comment]
@RadianFord the post above is the LATEST (today downloaded from github) revision.

**Comment by RadianFord** [comment]
@anacondaqq i mean i need to check the latest and my revision to see if there is something wrong with mine.

**Comment by anacondaqq** [comment]
@RadianFord Monster can't their name to show HP after only one 
@reloadbattleconf.

You need to kill previously spawned monsters with OLD names without showing HP

**Comment by RadianFord** [comment]
@anacondaqq I did all of that I even restart the whole server just to make sure.

**Comment by aleos89** [comment]
I can't reproduce with 2013-08-07 using 7e997bf.

**Comment by RadianFord** [comment]
@aleos89 can you show me or teach me where can i see the source for this? i will compare mine and the latest revision. thanks

**Comment by aleos89** [comment]
The source? You can view the link I posted above to see the source for that revision. I'm using a clean clone of rA. I use the /showname on my client (enabled by default where the font is bold) and you have to type /showname (disable to where the font is thin) to make the HP info show.

**Comment by RadianFord** [comment]
@aleos89  lol xD haha please closed this its not a bug.. all i need to do is to use the /showname type 2.
