### ISSUE TITLE
winapi.cpp(164): warning C4800: 

### ISSUE THREAD

**Issue by reymarbc** [rathena/rathena#2697]
* **rAthena Hash**: 336a475dba18e755b6eb7be1cffb8b8ee3120449

* **Client Date**: 

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: winapi.cpp(164): warning C4800: 'BOOL': forcing value to bool 'true' or 'false' (performance warning)
  * Expected Result: 
  * How to Reproduce: Clean and Rebuild in Visual Studio
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by keitenai** [comment]
this issue has already been reported.
https://github.com/rathena/rathena/issues/2690

**Comment by reymarbc** [comment]
@keitenai  is there any possible way to delete this issue , thank you for confirmation
