### ISSUE TITLE
Item Combo 24180-24185 Bug

### ISSUE THREAD

**Issue by esu1214** [rathena/rathena#2699]
rAthena Hash:
7351b88
Client Date: 20170125
Server Mode: renewal
Description of Issue:
You will get unnormal HP/MaxHP if you change map(such as go 0 go 1) when you equip 24180-24185(refined cnt totally >= 60)

**Comment by aleos89** [comment]
That's quite an old version. Are you able to reproduce it on a more recent version of rAthena?

**Comment by esu1214** [comment]
It also occoured on most recent version of rA.

**Comment by Lemongrass3110** [comment]
Unable to reproduce this.
My HP stay normal even with all of them being +20.
Why are you sure this is related to this combo?

**Comment by esu1214** [comment]
You should change map, then HP/MaxHP will become unormal.
Try go 1-10 when you equip 24180-24185.

**Comment by Lemongrass3110** [comment]
I did. And as I wrote I was unable to reproduce the issue.

**Comment by esu1214** [comment]
Try to add your vit to 100, you will find the error.

**Comment by esu1214** [comment]
@Lemongrass3110 Have you tried to add states?

**Comment by esu1214** [comment]
@aleos89 @Lemongrass3110 @Skormie @scriptord3 @wilkemeyer 
I found it is because sc_start4 SC_ENDURE,1,10,0,0,1;
It will cause your Str, Agi, Vit, Int, Luk to 0 if you equip 24180-24185 as a combo when you change map.
It become no error if I comment endure status.

**Comment by Daegaladh** [comment]
Related to #131
