### ISSUE TITLE
npc_checknear warning on floating npc

### ISSUE THREAD

**Issue by Yuchinin** [rathena/rathena#2701]
* **rAthena Hash**: 7113743

* **Client Date**: -

* **Server Mode**: Pre-Re

* **Description of Issue**: 
  * Result: Calling bind command on floating npc show npc_checknear error and halt the script.
  * Expected Result: It shouldn't show this error when calling floating npc which not on any map.
  * How to Reproduce: bind any command on the floating npc and call it, it will stop the script execution and show the error on console. I don't know which version break it but atleast c6fe9e9cde4003bd7842afccca1eb6f0471a933c still working fine.
  * Official Information:
  

* **Modifications that may affect results**: -

**Comment by Yuchinin** [comment]
```
-	script	MVP Of The Week::MVP_Of_The_Week	-1,{
OnAtcommand:
mes "blabla";
	select("Leave","A","B");
end;

OnInit:
	bindatcmd "mvpotw",strnpcinfo(3) + "::OnAtcommand";
}
```

**Comment by roSBK** [comment]
the end command after the interface interaction commands does not quit the script correctly, close command should be used.

**Comment by Yuchinin** [comment]
I just notice when use next command with floating npc on newer version will make the system do npc distance check which this kind of issue are not exists on older version. And yeah doing distance check with floating npc here is pointless and will always failed. (atleast https://github.com/rathena/rathena/commit/c6fe9e9cde4003bd7842afccca1eb6f0471a933c still work fine)

```
-	script	MVP Of The Week::MVP_Of_The_Week	-1,{
OnAtcommand:
mes "blabla";
      next;    // <---- should be the issue
     // after the next it will do the npc check near which is impossible on floating npc
     // so the select menu will not appear and halt the script on next command.
	select("Leave","A","B");
mes "blabla2";
end;

OnInit:
	bindatcmd "mvpotw",strnpcinfo(3) + "::OnAtcommand";
}
```
@roSBK End command will work just fine since it will always terminate the script execution and create a close button if there is a message box there. And yeah so in this situation even change the end to close the issue still there and solve nothing.

**Comment by hurtsky** [comment]
@Yuchinin confirm, i also have this warning, you can't use mes after next or after select the menu, but if you use dispbottom or message after select menu, the warning not appear..

**Comment by Yuchinin** [comment]
@hurtsky Yeah since the message and dispbottom won't need to use next command, but it will be quite inconvenient to let GM to configure the setting or whatever. Since this is still fine on https://github.com/rathena/rathena/commit/c6fe9e9cde4003bd7842afccca1eb6f0471a933c which is not that old to the current version, so I think it must be break somewhere on recent version.

**Comment by Lemongrass3110** [comment]
I am unable to reproduce this with any of the NPC scripts you guys supplied here.
Tested on 88e48ed with 2015-11-04 and no changes.

**Comment by hurtsky** [comment]
@Lemongrass3110 no more warning in 5ad35eb66bc12f492789c13169e3303a37c804ea 
@Yuchinin you can test it too for confirmation

**Comment by aleos89** [comment]
I'm unable to reproduce this as well using e385e16.
