### ISSUE TITLE
new script like pet <pet_id>;

### ISSUE THREAD

**Issue by mjonrest** [rathena/rathena#2703]
* **rAthena Hash**: 

* **Client Date**: 

* **Server Mode**: 

* **Description of Issue**: 
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**: 
  
  

can we have this kind of script, so we could catch many mob by using 1 taming item

by example:

unripe apple can catch poring or drops, or poporing

**Comment by Lemongrass3110** [comment]
```
*makepet <pet id>;

This command will create a pet egg and put it in the invoking character's
inventory. The kind of pet is specified by pet ID numbers listed in
'db/pet_db.txt'. The egg is created exactly as if the character just successfully
caught a pet in the normal way.

	// This will make you a poring:
	makepet 1002;

Notice that you absolutely have to create pet eggs with this command. If you try
to give a pet egg with 'getitem', pet data will not be created by the char
server and the egg will disappear when anyone tries to hatch it.
```

**Comment by Lemongrass3110** [comment]
Sorry I misread this issue.

**Comment by sader1992** [comment]
pet 0; well tame all the monsters in pet db
i don't know if this is a bug
i can't find the *pet in the script.cpp

**Comment by aleos89** [comment]
```c
	//catch_target_class == 0 is used for universal lures (except bosses for now). [Skotlex]
	if (sd->catch_target_class == 0 && !status_has_mode(&md->status,MD_STATUS_IMMUNE))
		sd->catch_target_class = md->mob_id;
```
Intended behavior.

**Comment by sader1992** [comment]
@aleos89 thanks for the info!

**Comment by mjonrest** [comment]
if i use pet 0; it will catch all mob in pet_db.. but how if we need to catch several mobs only.. can we add more command just like pet <pet_id>; command?

**Comment by aleos89** [comment]
@mjonrest : Honestly I haven't tried that. You could try specifying multiple mobs ie: `pet 1001; pet 1002;` and see how that works.

**Comment by mjonrest** [comment]
#2705 fixed

**Comment by sader1992** [comment]
@aleos89 the problem with using `{ pet 1002; pet 1113; pet 1004; }`
that only process the last command ,so in this example it will only catch 1004 and if you try it on 1002 and 1113 it will always fail

**Comment by Everade** [comment]
Huh?
`{ itemskill 297,1; }`
This worked for over a decade xD
