### ISSUE TITLE
Tinder Breaker

### ISSUE THREAD

**Issue by MrAntares** [rathena/rathena#271]
Git Version: **12628 - 2014-12-04 05:04:30 (luciar)**
Client Date: **2012-04-10**
Src Mods: **NONE**
General settings: 
- **Full Renewal**
- **1/1/1/1/1 rate**
- **PK server (not in towns, above lvl 30)**
- **PVP ATK/Skill modifers: 100%**
- **WOE ATK/Skill modifers: rA default**
- **Official walk path and stacking**
- **Exp and drop penalty table values below 100% set to 100%**
- **Party and attacker exp bonus: +40%**
- More at (Hungarian, use translate): http://wiki.ragna.ro/

How to reproduce & Description:

The skill only deals damage, but does not lock (like blade stop) the target as it's supposed to.

**Comment by cydh** [comment]
>The skill only deals damage, but does not lock (like blade stop) the target as it's supposed to.

try check it again, target still able to "move" until it done the walkpath, and stopped

**Comment by aleos89** [comment]
Like Cydh said, are you sure the target doesn't stop after it gets to his destination?

**Comment by MrAntares** [comment]
Okay, probably I misunderstood the skill. Sorry about that :)
