### ISSUE TITLE
Can't use some mapflag [found in doc folder]

### ISSUE THREAD

**Issue by hendra814** [rathena/rathena#2710]
* **rAthena Hash**: lastest

* **Client Date**: 2015-11-04  and 2017-06-14

* **Server Mode**: Renewal

* **Description of Issue**: can't use mapflag noitemconsumption, notrade, nodrop. But this mapflag i'm found it at doc folder at mapflag.txt, is this mapflag already can't be used in Rathena?
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**: 
  
  

![1](https://user-images.githubusercontent.com/9587609/34026177-d3d99bf6-e186-11e7-8f11-536e78e281ed.jpg)
![2](https://user-images.githubusercontent.com/9587609/34026178-d40acaf0-e186-11e7-9590-0f4a7d24be48.jpg)
![3](https://user-images.githubusercontent.com/9587609/34026179-d43a202a-e186-11e7-8acd-d30153ce3aec.jpg)

**Comment by sader1992** [comment]
i see in the errors you are using `<space>` instead of `<tab>`

**Comment by hendra814** [comment]
I'm currently using tab instead of space
but i'm already try change it into space but same error still appear

**Comment by sader1992** [comment]
can you try to put the mapflags in stand alone file ? and try again

**Comment by hendra814** [comment]
sorry, already solve it. I found the problem
before
map<tab>mapflag<space>mapflag_name === got error
after
map<tab>mapflag<tab>mapflag_name === working
sorry for my error. I will close this ticket.
