### ISSUE TITLE
Map server keep restarting

### ISSUE THREAD

**Issue by gegewu85** [rathena/rathena#2711]
rAthena Hash: latest
Client Date: 2017-06-14
Server Mode: Renewal
Description of Issue: 
- My map server keep shutdown it self and if you let it run without play, the map server not restart

**Comment by Jeybla** [comment]
Please try to debug your issue, your provided informations are very incomplete.

https://github.com/rathena/rathena/wiki/GDB
https://github.com/rathena/rathena/wiki/Crash_Logging

**Comment by aleos89** [comment]
Can you provide any more information or if you were able to resolve this?
