### ISSUE TITLE
ATK% Bonus not working on Headgears

### ISSUE THREAD

**Issue by RyeDE** [rathena/rathena#2714]
rAthena Hash: Latest
Client Date:  2017-01-25aRagexeRE + 2017-06-14bRagexeRE
Server Mode:  Renewal
Description of Issue:  bAddClass,Class_All doesnt add ATK%

  Expected Result: add 5% atk

  How to Reproduce:  ID 18600 (Cat Ear Beret) tested on dummy and monsters doesnt work doesn't add any damage. tested with Evil Marching Hat aswell = adds damage but the damage comes from 2 str not +2% atk. I believe all items that have bAddClass,Class_All are affected

AddRace + SubRace after refining the item doesn't work aswell

![1](https://user-images.githubusercontent.com/34604710/34072412-7242e878-e287-11e7-886d-6896972141cc.png) ![2](https://user-images.githubusercontent.com/34604710/34072413-725dc2ba-e287-11e7-82b0-7f35fa8fab83.png)

our script for cat ear beret = 
bonus2 bAddClass,Class_All,5; .@r = getrefine(); if(.@r < 5) .@r = 5; bonus2 bSubRace,RC_DemiHuman,(.@r - 5); bonus2 bAddRace,RC_DemiHuman,(.@r - 5);

RMS script for cat ear beret =
{ bonus bAtkRate,5; if(getrefine() > 5 && getrefine() <= 12) { bonus2 bAddRace,RC_DemiHuman,(getrefine() - 5); bonus2 bSubRace,RC_DemiHuman,(getrefine() - 5); bonus2 bAddRace,RC_Player,(getrefine() - 5); bonus2 bSubRace,RC_Player,(getrefine() - 5); } if(getrefine() > 12) { bonus2 bAddRace,RC_DemiHuman,7; bonus2 bAddRace,RC_Player,7; bonus2 bSubRace,RC_DemiHuman,7; bonus2 bSubRace,RC_Player,7; } },{},{}

rms one is working

**Comment by uddevil** [comment]
Same issue in : f0686828e72f19588f3fc59c4959c0211058059f

1. I'm using trans Rune Knight, with all stat 130
2. Testing normally item id 18600 on raydric, no change on normal attack or skill (I'm testing using Bash)
3. Changed `bonus2 bAddClass,Class_All,5` to `bonus2 bAddClass,Class_All,500` still no change (normal atk and skill)
4. Changed `bonus2 bAddClass,Class_All,500` to `bonus2 bAddClass,Class_Normal,500` still no change (normal atk and skill)

Another Note :
* Using the same item (18600), i try to change the bonuses to below :
* Tested bonus2 bAddRace,RC_Formless,500 against Ice Titan, there is no damage change whether i'm using normal attack or skill (Bash).
* Tested bonus2 bAddRace,RC_ALL,500 against Ice Titan, there is no damage change whether i'm using normal attack or skill (Bash).
* `bonus2 bAddClass` and `bonus2 bAddRace` working normally when placed on Weapon Card, but not working when placed on Headgear (Haven't tested anything else other than Weapon Card and Headgear Equipment)

Unrelated but working as intended :
* bonus2 bMagicAddClass is not affected (Working Normally / As Intended)
* bonus2 bMagicAddRace is not affected (Working Normally / As Intended)

**Comment by RyeDE** [comment]
Heya .. just tested it on prontera dummies. used a simple sword[3]. no change

**Comment by secretdataz** [comment]
This is intended behavior.

**Comment by aleos89** [comment]
Related to #718.
