### ISSUE TITLE
About skill SC_FEINTBOMB

### ISSUE THREAD

**Issue by redlightliu** [rathena/rathena#2720]
* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: After using skill SC_FEINTBOMB , Shadow Chaser can't use other skills in SC_FEINTBOMB hiding time. 
  * Expected Result: It's should be able to use skill in Feint Bomb's hiding. 

 
  

* **Modifications that may affect results**:

**Comment by admkakaroto** [comment]
This is the official behavior of the skill, search a little about it before.

**Comment by ecdarreola** [comment]
@admkakaroto : Can you link me source for the official behavior?

**Comment by redlightliu** [comment]
@admkakaroto KRO film. 
https://www.youtube.com/watch?time_continue=11&v=RzvgHe_YiP0

**Comment by aleos89** [comment]
Related to #2163. There's a `pc_isinvisible` check within skill usage and the Feint Bomb status change uses the `OPTION_INVISIBLE` flag.

**Comment by ecdarreola** [comment]
To make it able to use skill while in perfect hide state: comment the line

`StatusChangeStateTable[SC__FEINTBOMB]			|= SCS_NOCAST;`

to

`//StatusChangeStateTable[SC__FEINTBOMB]			|= SCS_NOCAST;`

Not sure if this is the proper way though.
