### ISSUE TITLE
mapserver crash with mobsearch

### ISSUE THREAD

**Issue by TournamentRO** [rathena/rathena#2724]
- rAthena hash: eb8f33e40f091c915c68ad946d6f5df93335a7e5
- client date: 2015-09-16 / 2015-11-04
- Server Mode: PRE RE
- Description of issue:

map server crash when inputing wrong mob name
eg. '@mobsearch poringg'

**Comment by lighta** [comment]
in ACMD_FUNC(mobsearch)
if(mob_id == atoi(mob_name) && mob_db(mob_id)->jname) // <= here mob_db(mob_id) could return null wich cause the crash.
Dirty workarround : 
if(mob_id == atoi(mob_name) && mob_db(mob_id) && mob_db(mob_id)->jname)

I must say I don't understand why we redoing atoi here...

**Comment by Jeybla** [comment]
> I must say I don't understand why we redoing atoi here...

It's to recheck if the mob_id is from `mob_id = atoi(mob_name)`; not from `mob_id = mobdb_searchname(mob_name);` since the name then already is in `mob_name`. Anyway your fix is fine. Push it @lighta

**Comment by Lemongrass3110** [comment]
@Jeybla it seems there was some dirty magic to show all mobs on a map before.
If you look at the code -1 would have displayed all of the mobs in the loop.
I'll clean this up a bit more and merge it.
