### ISSUE TITLE
Disable effect skill still show spirit ball.

### ISSUE THREAD

**Issue by hnomkeng** [rathena/rathena#2729]
* **rAthena Hash**: a0c8961
* **Client Date**: 20170607
* **Server Mode**: Pre-renewal
* **Description of Issue**:  Disable effect skill still show spirit ball.

**Comment by Lemongrass3110** [comment]
This is a clientside feature.

**Comment by hnomkeng** [comment]
What feature ?

**Comment by Lemongrass3110** [comment]
/effect is a client feature which only disables clientside rendering

**Comment by hnomkeng** [comment]
@Lemongrass3110  I can disable on nemo diff ?
