### ISSUE TITLE
About skill  SO_CLOUD_KILL

### ISSUE THREAD

**Issue by redlightliu** [rathena/rathena#2731]
* **Client Date**: 20160203

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: If the player on the SO_CLOUD_KILL , when the Sorcerer use Dispell with this player and this player not move. Killing Cloud will not have damage. 
  * Expected Result: If player be affectd by dispell on the Killing Cloud,Killing Cloud skill damage should be continue.
  * How to Reproduce: https://www.youtube.com/watch?v=tE5xk57yduA&feature=youtu.be 
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
My Aegis info shows it as being able to be removed. Unless it has changed, I'll leave this open for a bit longer to see if someone can confirm on kRO.
