### ISSUE TITLE
KvM Double Event

### ISSUE THREAD

**Issue by roSBK** [rathena/rathena#2733]
Well there is a bug in the KvM when the player dies is taken a point in the score, so far so good, more when he dies and resolves to disconnect from the server is removed another point in the score, this causing a second invalid removal in the score.

A character variable will probably fix this bug for example:

```
OnGuillaumeQuit:
	//set BG_Delay_Tick, gettimetick(2) + 1200;
OnGuillaumeDie:
	if( $@KvM01BG == 2 )
	{
		if( KVM_EV_FLAG <= 0 ) {
				set KVM_EV_FLAG,1;
				set .Guillaume_Count, .Guillaume_Count - 1;
				bg_updatescore "bat_c01",.Guillaume_Count,.Croix_Count;
		}
		if( .Guillaume_Count < 1 ) donpcevent "KvM01_BG::OnCroixWin";
		else {
			mapannounce "bat_c01", "The number of Guillaumes is "+.Guillaume_Count+".",bc_map,"0x00ff00";
			mapannounce "bat_c01", "The number of Croixes is "+.Croix_Count+".",bc_map,"0x00ff00";
		}
	}
	end;
```

It would also have to be added a reset on this variable when a player joins a team.

**Comment by sader1992** [comment]
the example you used is not an rathena official script
what script you used ?
is this the same for every script ? 
see there
rathena\npc\battleground\kvm
or
rathena\npc\custom\battleground\unofficial

also if you edit the script then i suggest you post in the forum not here

**Comment by roSBK** [comment]
Not in the official itself, it is a double event, it even has two events one when it displaces that it removes 1 of score and one when it dies that also does the same thing, now you die and disconnect without leaving the team causes the double event.

**Comment by aleos89** [comment]
This is how the official script behaves.
