### ISSUE TITLE
RODEX Bypasses Item Restrictions

### ISSUE THREAD

**Issue by syracuase** [rathena/rathena#2736]
* **rAthena Hash**: Latest Commit

* **Client Date**: 2015-04-02

* **Server Mode**: Renewal

* **Description of Issue**: You can mail and attach item with restrictions [eg nomail, notrade] by sending through RODEX
  * Result:  Players are able to send items with restrictions
  * Expected Result:  An error should appear not allowing mailing of untradable items
  * How to Reproduce:  Just send item restricted contents through RODEX
  * Official Information:
  

* **Modifications that may affect results**: No modifications on rAthena copy

**Comment by RyeDE** [comment]
try on non gm account

**Comment by syracuase** [comment]
Ah.. My Bad. This was an embarassing mistake. Tq..
