### ISSUE TITLE
Compile warning clif.cpp(6213)

### ISSUE THREAD

**Issue by sader1992** [rathena/rathena#2738]
* **rAthena Hash**: d19ba918aea07639a0ffc03a4f935f9df5e44e34
* **Client Date**: 2015-11-04
* **Server Mode**: both
* **Description of Issue**: 
repos\rathena\src\map\clif.cpp(6213): warning C4267: '=': conversion from 'size_t' to 'uint16', possible loss of data

![image](https://user-images.githubusercontent.com/5981261/34406573-79c11aae-ebc2-11e7-8f91-ad050329cffa.png)

**Comment by aleos89** [comment]
Are you building on the 64bit version of MSVS?

**Comment by sader1992** [comment]
this warning on 32bit

**Comment by Haikenz** [comment]
with me is with the same error, I use the VS2015 64bit
