### ISSUE TITLE
About skill GC_COUNTERSLASH

### ISSUE THREAD

**Issue by redlightliu** [rathena/rathena#2739]
* **Client Date**: 20160203

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Before using GC_COUNTERSLASH skill(Guillotine Cross), you had to designate the monster. If you not designate the monster , this skill will be very difficult to use
  * Expected Result: This GC_COUNTERSLASH skill should be like SM_MAGNUM ,and need use GC_WEAPONBLOCKING skill first . But this skill should not need to designate the monster first.
  * How to Reproduce: Using GC_WEAPONBLOCKING and be attacked by monster . And don't designate the monster. 

  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
What is your revision? From the current master (9c531b0) the skill is listed as `inf` 4 which is a self skill.

**Comment by aleos89** [comment]
Using the revision I posted in the comment above: I casted Counter Slash and the client showed an error saying I needed to activate Weapon Blocking. Once I activated Weapon Blocking I let mobs attack me. My character shouted "Weapon Blocking !!" at which point I used Counter Slash and proceeded to do an AoE damage around myself.

I would say this is working as intended.

**Comment by redlightliu** [comment]
@aleos89 In skill.cpp line 2744~2775


  Checks whether a skill can be used in combos or not
  param skill_id: **Target skill**
  return　0: Skill is not a combo
 　　　　1: Skill is a normal combo
 　　　　2: Skill is combo that prioritizes auto-target even if val2 is set 
 author Panikon
 
int skill_is_combo(uint16 skill_id) {
　　switch(skill_id) {
　　　case MO_CHAINCOMBO:
　　　case MO_COMBOFINISH:
　　　case CH_TIGERFIST:
　　　case CH_CHAINCRUSH:
　　　case MO_EXTREMITYFIST:
　　　case TK_TURNKICK:
　　　case TK_STORMKICK:
　　　case TK_DOWNKICK:
　　　case TK_COUNTER:
　　　case TK_JUMPKICK:
　　　case HT_POWER:
　　　**case GC_COUNTERSLASH:** <-----
　　　case GC_WEAPONCRUSH:
　　　case SR_DRAGONCOMBO:
　　　　　return 1;
　　　case SR_FALLENEMPIRE:
　　　case SR_TIGERCANNON:
　　　case SR_GATEOFHELL:
　　　　　return 2;
　　　}
　　　return 0;
}

Charcater could use GC_COUNTERSLASH only if charcater selected target.
GC_COUNTERSLASH is not a **Target skill**.
