### ISSUE TITLE
Castling mob count overflow

### ISSUE THREAD

**Issue by MrAntares** [rathena/rathena#274]
Git Version: **12628 - 2014-12-04 05:04:30 (luciar)**
Client Date: **2012-04-10**
Src Mods: **NONE**
General settings: 
- **Full Renewal**
- **1/1/1/1/1 rate**
- **PK server (not in towns, above lvl 30)**
- **PVP ATK/Skill modifers: 100%**
- **WOE ATK/Skill modifers: rA default**
- **Official walk path and stacking**
- **Exp and drop penalty table values below 100% set to 100%**
- **Party and attacker exp bonus: +40%**
- More at (Hungarian, use translate): http://wiki.ragna.ro/

How to reproduce & Description:

~~I was farming Mi Gaos, and I got hit multiple times, which caused my garment (Uflheiden) to activate NPC_STONESKIN. Looks like the bonus got totally glitched, because I ended up receiving 1000%+++ more damage from monsters, while others were not affected. When I removed all my equips I received a lot less damage, but it was still ridiculously high. When I re-equipped my stuff I received even much more damage. Even my raydric card effect got reversed and when I equipped my garment I got more damage.~~

~~I'm not entirely sure if this was the result of the NPC_STONESKIN, but it is my only suspect. Something is pretty messed up here.....~~

Just watch, this is a simple hunter fly hitting me:
http://youtu.be/JMPH6rYvDDg

Okay, I figured it out. It's Castling. Every time I use Castling the mobs that were hitting me starts to target the homunculus, but still they count in my character's mob count like they were hitting me, and if I use castling many times I will end up hundreds of virtual mobs "targeting" me, thus greatly increasing my defense penalty, but really none of those are attacking me, and if one mob hits me, it will take the bonus damage.

**Comment by MrAntares** [comment]
I confirmed fully. It is castling. Every time I use it, tem mob count freezes and every monster that were hitting me and got switched to the homunculus still counts towards me as if they were actually attacking me. Even If I die or kill every mob, or fight completely different ones, the penalty towards me remains.  Only relogging removed it.

**Comment by raynra** [comment]
I can also confirm this. Needs to be fixed :(

**Comment by cydh** [comment]
it's something~

**Comment by MrAntares** [comment]
Can we expect this to be fixed in the near future?

**Comment by cydh** [comment]
looking into...
Castling is HAMI_CASTLE, right?

**Comment by raynra** [comment]
Yes, that is correct.

**Comment by cydh** [comment]
https://www.dropbox.com/s/6wnjuuovqgf2gc0/hami_castle-fix.diff?dl=0
test pliz
