### ISSUE TITLE
Evil Marching Hat script is not complete

### ISSUE THREAD

**Issue by flamefury** [rathena/rathena#2741]
* **rAthena Hash**: 

e385e167ab479868ead8276f017b31aec90b5219
* **Client Date**: 

2015-11-04
* **Server Mode**: 

Renewal
* **Description of Issue**: 
  * Result:  Evil Marching Hat is missing its ATK, Critical Damage and Ranged Damage bonuses.
  * Expected Result:  Evil Marching Hat should be giving its bonuses.
  * How to Reproduce:  Try equipping it.
  * Official Information:
  
http://ro.gnjoy.com/guide/runemidgarts/itemview.asp?itemSeq=2&ID=18522

* **Modifications that may affect results**:

**Comment by redlightliu** [comment]
18522,Evil_Marcher_Hat,Evil Marching Hat,4,20,,500,,10,,1,0xFFFFFFFF,63,2,256,,0,1,687,{ .@r = getrefine(); bonus bStr,2; bonus bMdef,1; bonus bAtkRate,2; if(.@r>6){ bonus bCritAtkRate,10; }; if(.@r>8){ bonus bAtkRate,5; bonus bLongAtkRate,5; }; },{},{}
