### ISSUE TITLE
Gunslinger & Rebellion after official awakening patch

### ISSUE THREAD

**Issue by cydh** [rathena/rathena#2745]
* **rAthena Hash**: e88785b181f800189c9d5db662ab0f2555d0d203

* **Client Date**: -
* **Server Mode**: Renewal
* **Modifications that may affect results**: NONE
* **Description of Issue**: 

So here's the summary I can bring to here

What | Before | After
------------- | ------------- | -------------
Shotguns | Can have Bullets or Spheres as ammo | Only Bullets
Grenade Launchers | Only have Spheres as ammo | Only Bullets
Other guns | Bullets only | same, now all guns are using Bullets
Gunslinger's Mine | Need Spheres as ammo | Need Bullet as ammo
Gunslinger's Mine | Has effects based on ammos| No additional effects, only for element endowing
Slug Shot | Needs Slug Bullets 1-5 | Need Bullet as ammo, and [Slug Bullet](https://www.divine-pride.net/database/item/25187/) as catalyst in inventory
Spheres | There are spheres | Removed entirely, also with the Sphere Packages
Silver Bullet & Bloody Shell | - | Attack increased, weight reduced
Cartridges | - | The above changes about silver & Bloody Shell, the ammo items are technically changed, not modified the attack & weight only, so it also affects to the cartridge

**Comment by cydh** [comment]
About Slug Bullets -> Slug Bullet, tomorrow idRO will add NPC for that bullet to replace Slug Bullets (1-5)

**Comment by cydh** [comment]
seems I can change this topic for Awakening research.

I got new discover about Gunslinger's Mine
* Doesn't need Spheres equipped
* Bullets can be equipped even using Grenade launcher
* It always summon the Flare mine's sprite
* Seems the damage is force/default to Neutral (tested against Fire element monster such Greatest General, no miss)

**Comment by AzarthMZintos** [comment]
> rAthena Hash: 3cd7717
Client Date: 2018-06-21a
Server Mode: Renewal
Description of Issue:
Result: The item 13200 have wrong attack it 10 and wrong weight 0,2
Expected Result: The item should have attack 25 and weight 0,1
How to Reproduce: Look at db rathena renewal
Official Information:
Look at kro version NOT iro version : https://www.divine-pride.net/database/item/13200
And you can look at Korean Ragnarok Online\System\itemInfo_true.lub id: 13200
금속을 주재료로 하였으며 관통력으로 살상 및 파괴효과를 낸다.
계열 : 총알 공격 : 25
무게 : 0.1 속성 : 무

Modifications that may affect results:

>

**Comment by AzarthMZintos** [comment]
@cydh any update on this?

**Comment by cydh** [comment]
@AzarthMZintos all will be done in #3459
