### ISSUE TITLE
Heart Wing Hairband bonus gets worse as it is refined

### ISSUE THREAD

**Issue by im-mi** [rathena/rathena#2748]
* **rAthena Hash**:  My build is based on 5602bb0, with a few small changes that shouldn't affect this issue (I set the platform toolset so it would actually compile, disabled packet obfuscation, etc.). Its actual hash is 4dcd510, if that matters.

* **Client Date**: 2015-11-04a

* **Server Mode**: Renewal

* **Description of Issue**: Heart Wing Hairband (Item ID# 18563) bonus gets worse as it is upgraded
  * Result:  SP consumption and after-cast delay are increased every 3 refine levels
  * Expected Result:  SP consumption and after-cast delay are supposed to get reduced every 3 refine levels
  * How to Reproduce:  Create a Heart Wing Hairband and try using it with multiple refine levels. For every 3 refine levels, sp consumption will go up. Less noticeably, after-cast delay will also go up.
  * Official Information: [Heart Wing Hairband [1] (iW Database)](http://db.irowiki.org/db/item-info/18563/) 
  

* **Modifications that may affect results**: None, as far as I'm aware.

**Comment by secretdataz** [comment]
Fixed in #2752
