### ISSUE TITLE
Magnificat skill effect is overpowered

### ISSUE THREAD

**Issue by nanakiwurtz** [rathena/rathena#275]
Source: kRO
Original Descriptions:

Skill Name: 마니피캇 (Magnificat)
MAX Lv: 5
계열 : 찬송계 (
내용 : 술자와 술자가 속해있는 파티 멤버들의 SP 회복속도를 두배로 빠르게 한다.

Our Magnificat skill is wrong all this time, it shouldn't double the HP regeneration speed.
It should only doubles the speed of **SP Regeneration rate**, not HP + SP...

**Comment by Playtester** [comment]
Tested on Aegis:

HP regeneration delay:
Normal: 6 seconds
Sitting : 3 seconds
Magnificat: 6 seconds
Sitting+Magnificat: 3 seconds

SP regeneration delay:
Normal: 8 seconds
Sitting: 4 seconds
Magnificat: 4 seconds
Sitting+Magnificat: 2 seconds

So yes, I can confirm, HP regen shouldn't be affected by Magnificat.
