### ISSUE TITLE
Combo Correction 1618-2509

### ISSUE THREAD

**Issue by BrOgBr** [rathena/rathena#2751]
* **rAthena Hash**:  All

* **Client Date**: Doesn't matter

* **Server Mode**:  Both

 Renewal but Pre-Re is already wrong.

* **Description of Issue**:  I found a Combo Error (1618:2509), even in RateMyServer (and other emulators) is wrong but I corrected it!

* **Modifications that may affect results**: 
  
  

db\re
[item_combo_db.txt](https://github.com/rathena/rathena/files/1595293/item_combo_db.txt)

db\pre-re
[item_combo_db.txt](https://github.com/rathena/rathena/files/1595294/item_combo_db.txt)

Sorry for any mistake.
It's the first time that I'm using Github to report, I want only help.

**Comment by BrOgBr** [comment]
Sorry secretdataz I searched for 1618 and 2509, I forgot that try the item names...

**Comment by aleos89** [comment]
This will close when the PR is pushed to master.

**Comment by secretdataz** [comment]
Fixed in #2753
