### ISSUE TITLE
Creeper Bow [ Bug ]

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#2754]
* **rAthena Hash**: ae69e506263f9b183c945f49b1d88c5fc2b73a6a
* **Client Date**: 20170531
* **Server Mode**: Renewal
* **Description of Issue**: When using the Spider Web skill you should consume the item from the inventory item, but that is not happening, you can use Spider Web without having any webs in inventory.
  * Official Information: https://www.divine-pride.net/database/item/18111/creeper-bow-2

Print: https://imgur.com/87x8ok9

**Comment by secretdataz** [comment]
Autospell from item bonuses ignore the spell's cost.

**Comment by sader1992** [comment]
I don't think this is a bug
like the staff that auto cast safety wall , i think it's intended that the auto-cast ignore the skill requirement

**Comment by secretdataz** [comment]
I'm closing this issue until anyone has an official source that shows the 'special behavior' mentioned in the OP.
