### ISSUE TITLE
script warp between map-servers

### ISSUE THREAD

**Issue by LunarSHINING** [rathena/rathena#2765]
rAthena Hash: 32950ec
Client Date: 2017-01-24 and any other
Server Mode: Both
Description of Issue:
When using a script to warp between 2 map servers it automatically crashes the current map-server.
Using atcommand "\@"warp inside a script will also crash the map server but teleport the character.
However using "\@"warp in the chat will work perfectly.

Expected Result: It should teleport between the two servers without crashing one.
How to Reproduce:
Have 2 map-servers and use a script with warp "map" or atcommand "\@"warp mapname";
Official Information: None
Modifications that may affect results:

**Comment by MrAntares** [comment]
There was and old rAthena bug tracker post, that might be worth to check as well. I only found it in hercules's archives when they migrated our issues.
http://herc.ws/oldboard/tracker/issue-5410-moving-across-multiple-map-servers-is-a-one-way-ticket-with-loads-of-errors/?sevfilter=2

Shortly:
Try if you can warp back and forth between mapservers without issues, also try it with autotrading players.
