### ISSUE TITLE
Quest Skill Randomly Lost

### ISSUE THREAD

**Issue by uddevil** [rathena/rathena#277]
So here's my problem, last commit that i used is this : 
https://github.com/rathena/rathena/commit/b43b855d210c627f06863c50a817ba8797a7db55
(no big problem, working as intended)

Then i pull this one
https://github.com/rathena/rathena/commit/90d9da18e1d1980c52e70b5baeaa9bcd9e769390

And quest skills (such as Lord Exclamation, Cart Change, etc) are randomly lost when re-log, or using healer npc (the one with SC_START blablabla).

First i thought it was my customization that cause it, but then i tried again on my other server that has no customization at all (i'm only using custom npc from rA default like healer, reset, etc), but the skills keeps randomly lost everytime i logout. Lord exclamation was worse, it acts like scroll-based skills, one time usage then its lost.

So, i switch to this commit : 
https://github.com/rathena/rathena/commit/a427dbf5132de1351caa8c337389a92e3072df3a

And all the problems are gone. Is it because of the skill db clean up?

**Comment by aleos89** [comment]
This was my fault. I didn't mean to apply this when testing. Let me look back through this.
