### ISSUE TITLE
OGH buffs

### ISSUE THREAD

**Issue by Atemo** [rathena/rathena#2772]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/c04c2e7ef1830474d9d4cd9c5404a6374d987f19

* **Client Date**: irrevelant

* **Server Mode**: renewal

* **Description of Issue**: 
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  
Following https://github.com/rathena/rathena/pull/1554 we need more infos on some OGH effects
EFST_GLASTHEIM_ATK
EFST_GLASTHEIM_DEF
EFST_GLASTHEIM_HEAL
EFST_GLASTHEIM_HIDDEN
EFST_GLASTHEIM_STATE
EFST_GLASTHEIM_ITEMDEF
EFST_GLASTHEIM_HPSP

* **Modifications that may affect results**: none

**Comment by mrjnumber1** [comment]
these are only in OGH beginner mode on kRO, so for what we have now (which is only normal mode), it's not needed.
that said there are probably some instance variables and duplicates we need to make to account for the beginner and hard modes ..

**Comment by Atemo** [comment]
https://github.com/rathena/rathena/blob/master/npc/re/instances/OldGlastHeim.txt#L1553
Theses npcs give buffs as well in normal mode depending on boss remaining hp.

**Comment by mrjnumber1** [comment]
okay.. i guess it was changed since i last saw it. sorry about that.

**Comment by mrjnumber1** [comment]
from 15.2 episode zone
EFST_GLASTHEIM_ATK
+100% damage to corruption root and amdarais (same as Orc Lady for those),
+100% MDEF ignore against undead/demon

EFST_GLASTHEIM_DEF
-100% dmg from corruption root and amdarais (as increase soil card does)

EFST_GLASTHEIM_HEAL
+100% heal power (like recov staff)
+50% received healing (As in sprint mail)

EFST_GLASTHEIM_HIDDEN
-90% damage from the HIDDEN_MOB HIDDEN_MOB2 and HIDDEN_MOB_W - presumably, this means you take less damage from the boss's summon spells

EFST_GLASTHEIM_STATE
+20 str/agi/dex/vit/int/luk

EFST_GLASTHEIM_ITEMDEF
+200 def, +50 mdef (as in arclouse card!)

EFST_GLASTHEIM_HPSP
+10.000 HP
+1.000 SP
