### ISSUE TITLE
Drops from monster ID:1815 Hot Ricecake change

### ISSUE THREAD

**Issue by AzarthMZintos** [rathena/rathena#2773]
https://www.divine-pride.net/database/monster/1815/hot-ricecake-event
drop changes
* **rAthena Hash**: 

* **Client Date**: 

* **Server Mode**: 

* **Description of Issue**: 
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment]
See secret's comment on #2774
