### ISSUE TITLE
Hunter Quest Job Change quest stuck after finish it at the quest window

### ISSUE THREAD

**Issue by AzarthMZintos** [rathena/rathena#2779]
* **rAthena Hash**: 

* **Client Date**: 

* **Server Mode**: 

* **Description of Issue**: 
  * Result: The quest after I finished its still there at the Quest Window, Title: Quest Changes to Hunter Description: Report to the Guild Master that you've passed the exam. Im already a Hunter!
  * Expected Result: The quest should disapear after I finish it
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Fixed in df9bac9.
