### ISSUE TITLE
Item 673 Bronze Coin and 675 Platinum Coin drop...

### ISSUE THREAD

**Issue by AzarthMZintos** [rathena/rathena#2786]
* **rAthena Hash**: 

* **Client Date**: 

* **Server Mode**: 

* **Description of Issue**: 
I din't find any place saying that those item have some monster who drop them, anyone can confirm they drop from the monster at rathena database still? Ty
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment]
Please use our forum for questions.
