### ISSUE TITLE
Beach Clothers

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#2788]
* **rAthena Hash**: Any
* **Client Date**: Any
* **Server Mode**: Any
* **Description of Issue**: In the KRO it is possible to wear beach clothes, it also has the sprites in the kRO folder, however in rathena it is not available.
* **Divine**: https://www.divine-pride.net/database/item/22822/
* **Print**: https://imgur.com/jTKIqm3

**Comment by aleos89** [comment]
Is it the same effect as 2776?
