### ISSUE TITLE
Laphine Shield can't be used to all skill that required shield

### ISSUE THREAD

**Issue by laziem** [rathena/rathena#2797]
* **rAthena Hash**: e385e167a

* **Client Date**: 2017-05-17

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: [Laphine Shield](https://www.divine-pride.net/database/item/2198) can't be used to all skill that required shield
  * Expected Result: Laphine Shield should can be used to all related shield skill
  * How to Reproduce: Equip Laphine Shield and try to use all related skill
  * Official Information: -
  

* **Modifications that may affect results**: none

**Comment by Atemo** [comment]
I don't understand your issue please elaborate.

**Comment by laziem** [comment]
When I equip Laphine Shield, I can't use skill like Auto Guard, Shield Chain, Shield Boomerang, etc. It shows _Skill has failed_
