### ISSUE TITLE
Lunatic ID1063 now drop sword[4]

### ISSUE THREAD

**Issue by AzarthMZintos** [rathena/rathena#2802]
* **rAthena Hash**: 

* **Client Date**: 

* **Server Mode**: 

* **Description of Issue**: 
  * Result: The database of divine say that lunatic now drop sword[4]

https://www.divine-pride.net/database/monster/1063/
https://www.divine-pride.net/database/monster/2770/
https://www.divine-pride.net/database/monster/2771/

  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Atemo** [comment]
Missing githash.
