### ISSUE TITLE
Monster Lunatic ID 1063 Drop Sword[4] 1102

### ISSUE THREAD

**Issue by AzarthMZintos** [rathena/rathena#2803]
* **rAthena Hash**:

* **Client Date**: 

* **Server Mode**: 

* **Description of Issue**:The monster Lunatic(1063) don't drop sword[4] (1102)
  * Result:  The monster Lunatic(1063)don't have  drop sword[4] (1102) at drops
  * Expected Result: The monster Lunatic(1063) should drop sword[4] (1102)
  * How to Reproduce: Look at 1063 drop tablet
  * Official Information:Not official information I dont play there divine pride: https://www.divine-pride.net/database/monster/1063/
  

* **Modifications that may affect results**:

**Comment by vstumpf** [comment]
Its in mob_drop.txt

**Comment by AzarthMZintos** [comment]
OMG i dint even know abou that file ty =) 
anyone can close it ty
