### ISSUE TITLE
Wrong message on skills

### ISSUE THREAD

**Issue by Daegaladh** [rathena/rathena#2804]
* **rAthena Hash**: a6a2c4301bcf295b1769411a9123fd6a39ba613f

* **Client Date**: 2015-05-13

* **Server Mode**: Both

* **Description of Issue**: 
  * Result: When using Aura Blade without a weapon a white message appears "[Revolver] weapon class must be equipped."
  * Expected Result: Red message "The skill cannot be used with this weapon."
  * How to Reproduce: Just use Aura Blade without a weapon.
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Artuvazro** [comment]
Confirmed on clean installation:

https://i.imgur.com/dTkPhHQ.jpg

**Comment by sader1992** [comment]
![image](https://user-images.githubusercontent.com/5981261/34920905-219a52b8-f983-11e7-95c1-6a1b06a2949e.png)

however i don't know what the Expected Result

**Comment by Daegaladh** [comment]
Futher testing revealed it happens with all skills that include revolver as required weapon in the skill_require_db.
