### ISSUE TITLE
Achievement System Incomplete Rewards

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#2806]
* **rAthena Hash**: 
ae69e50

* **Client Date**: 
2016-02-03aRagexeRE

* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result: A few achievements reward you with the items:
```
12817,Old_Card_Album_,Old Card Album,2,0,,0,,,,,0xFFFFFFFF,63,2,,,80,,,{},{},{}
22808,Special_Gift_Box,Special Gift Box,2,10,,100,,,,,,,,,,,,,{},{},{}
```
Achievement rewards are account bound. Due the fact that these usables have no current effect, these items stay stucked in the players inventory forever.
  * Expected Result: Implement official rewards for the box and album.
  * Official Information: I wasn't able to find any official information on the content of these items. Any help is appreciated.

* **Modifications that may affect results**: 
None

**Comment by aleos89** [comment]
I took all the rewards from achievements out of the LUA shipped by the client. Unless there was an update recently, I didn't particularly look through each item, but they should all be official ones.

**Comment by im-mi** [comment]
I've noticed this same problem with the same two achievement rewards.

The issue is that, while the achievements give (correct?) reward items, some of them don't function properly when used. In this case, the Old Card Album (\#12817) disappears and give you nothing and the Special Gift Box (\#22808) can't be used and just takes up inventory/storage space.

**Comment by Everade** [comment]
@aleos89 Yea the rewards might be official, no idea about that.
The problem here is as described in my initial report and in the comment from im-mi that the rewards themselfs can't be used due **missing item scripts** / content.

**Comment by aleos89** [comment]
The Old Card Album should be:
```
12817,Old_Card_Album_,Old Card Album,2,0,,50,,,,,0xFFFFFFFF,63,2,,,80,,,{ getrandgroupitem(IG_CardAlbum,1); getitem 12818,1; },{},{}
```
I haven't found anything yet for Special Gift Box.

**Comment by Everade** [comment]
I'm closing this issue because reward ID 22808 (with the unknown rewards) has been removed in the latest rAthena achievement db update SHA-1: ef046159d6dc1567a512af55f76bd1cc06afee84 (Updated Achievement database (#3165))

**Comment by aleos89** [comment]
Wouldn't this still be applicable since Old Card Album has no script?
