### ISSUE TITLE
Ninja Gear Enchantment discrepancies

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#2807]
* **rAthena Hash**: 
ae69e50

* **Client Date**: 
2016-02-03aRagexeRE

* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result:
There are several discrepancies between the information given from the iRO wiki and the script we have currently in use.
I have no kRO details at my disposal, but compared to iRO it's way off.

_Affected Script:_
**npc/re/merchants/enchan_ko.txt     line 290-504**
```
	// Enchantment
	     if (.@equip_refine <= 4)  set .@ko_type01,1;
	else if (.@equip_refine <= 7)  set .@ko_type01,2;
	else if (.@equip_refine <= 9)  set .@ko_type01,3;
	else if (.@equip_refine <= 12) set .@ko_type01,4;
	else                           set .@ko_type01,5;
```
I found the problem because it initialy starts with lvl 2 enchantments with refinement lvl 13+ rather than 12+. But there are also several other differences between the wiki and the script.
  * Official Information:
https://irowiki.org/wiki/Ninja_Gear_Enchants#Enchants_per_Upgrade_Level

* **Modifications that may affect results**: 
None

**Comment by aleos89** [comment]
```
  if ((wa_ko_cnt >= 0) & (wa_ko_cnt <= 4))
    var ko_type01 = 1
  elseif ((wa_ko_cnt >= 5) & (wa_ko_cnt <= 7))
    var ko_type01 = 2
  elseif ((wa_ko_cnt >= 8) & (wa_ko_cnt <= 9))
    var ko_type01 = 3
  elseif ((wa_ko_cnt >= 10) & (wa_ko_cnt <= 12))
    var ko_type01 = 4
  else
    var ko_type01 = 5
  endif
```
From the kRO script. Seems iRO customized it.
