### ISSUE TITLE
SC_MIRACLE Status Effect never called

### ISSUE THREAD

**Issue by Dakado** [rathena/rathena#2809]
* **rAthena Hash**: Downloaded 2 days ago

* **Client Date**: 2015 10 29 a

* **Server Mode**:  RENEWAL

* **Description of Issue**: 
The problem is that the function (skill_counter_additional_effect) that is activating Miracle skill for Star Gladiators is never called, even if I have set 100% chance of activating in my skill.conf, someone probably forgot about that it is even written in the description that it is called only after certains skill and non of the skill is a gladiator's one so Miracle effect cannot be activated.

Line 2364:
`status_change_start(src,src,SC_MIRACLE,battle_config.sg_miracle_skill_ratio,1,0,0,0,battle_config.sg_miracle_skill_duration,SCSTART_NONE);`

This works fine but but the function is probably never called.

**Comment by aleos89** [comment]
From the description of `skill_counter_additional_effect`, it should be triggered from all BF_WEAPON based skill attacks.

**Comment by Dakado** [comment]
Yes, but the miracle effect should be activated regardles of the weapon or skill.

**Comment by Dakado** [comment]
Well even with 100% chance the spell is never activated, please fix that,

**Comment by aleos89** [comment]
Can you tell me the exact steps you are going through? What map is it on? Does the map have the No Sun, Moon, Star Miracle mapflag set? How are you attacking the monster? The more details the better.

**Comment by Dakado** [comment]
I just warp on map and do basic attacks to mobs.

My equip:
https://i.gyazo.com/4c865b03abd5aa832ea875f4e7039992.png

Tried on different maps: lou_fild01, thor_v01, thor_v02

**Comment by aleos89** [comment]
![image](https://user-images.githubusercontent.com/3521753/35016035-f59be5d8-fae4-11e7-9483-7a0de214efc9.png)
I tested with d306f17 and it seems to work fine for me. The only thing I did was adjust the config to activate at 100% chance. The status was triggered on normal attacks and skills.

**Comment by Dakado** [comment]
Yes I can see my char turn blue but I have no bonus damage at all, doing exactly the same damage as without it.

**Comment by Akaineko-astasi** [comment]
@Dakado Miracle does not give any additional damage itself. It only lets you use map and date specific skills without meeting those requirements. In Miracle state, it's always the place and the time and the enemy. Damage increases because one of those skills, SG_*_ANGER (actually, there are 3 of them), normally applied only to those who are targets of SG_HATE, now is applied to all enemies. That means, to get a damage addition you have to have your Anger passives learned and your `( BaseLV + LUK + DEX )` high enough to notice the difference.

**Comment by Dakado** [comment]
I do base attack to my enemy (Mi Gao) and I do 870 dmg per attack, after a few hits, my chracters turns blue like during the soul link (Miracle activation I guess) but I still do 870 base damage to my enemy.

**Comment by Dakado** [comment]
@Akaineko-astasi & @aleos89  Here it is:
https://youtu.be/9inpzP-GEUk - without miracle 850 dmg per hit, 1200 per critical, to prove that I have not enabled miracle see in chat - Skill has failed when I try to use Protection skills.

https://www.youtube.com/watch?v=WgXR-ARq-2I - here I have activated miracle which is proven by casting all 3 Solar, Lunar a Stellar protection but my damage has not changed at all

**Comment by secretdataz** [comment]
Have you marked the monster with hatred skills?

**Comment by secretdataz** [comment]
Working as intended.
All mobs will be treated as stellar-marked mob.
The damage increased is porportional to the character's STR.

Snippet taken from battle.cpp

```
			if (sc->data[SC_MIRACLE])
				i = 2; //Star anger
			else
				ARR_FIND(0, MAX_PC_FEELHATE, i, t_class == sd->hate_mob[i]);

			if (i < MAX_PC_FEELHATE && (skill=pc_checkskill(sd,sg_info[i].anger_id))) {
				int skillratio = sd->status.base_level + sstatus->dex + sstatus->luk;

				if (i == 2)
					skillratio += sstatus->str; //Star Anger
```
