### ISSUE TITLE
Over Thrust skill effect

### ISSUE THREAD

**Issue by nanakiwurtz** [rathena/rathena#281]
Skill ID: 113
Skill Name: BS_OVERTHRUST
Description: The skill shouldn't break axes, maces, and some explicitly unbreakable weapons.
Currently it will break any equipped weapons.

**Comment by Playtester** [comment]
Really? I remember it working from when I still played. Are the unbreakable weapon types broken or the skill, though?

**Comment by aleos89** [comment]
This is already fine. The skill_break_equip() checks for weapon types and Axe/Mace is in the list. :)
