### ISSUE TITLE
Rune Knight Runes missing stacking limit

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#2820]
* **rAthena Hash**: 
ae69e50

* **Client Date**: 
2016-02-03aRagexeRE

* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result: Some Rune Knight runes have no stacking limit.
Missing limits for:
**db\re\item_stack.txt**
```
12729,60,1  // Othila Rune
12731,60,1  // Thurisaz Rune
12732,60,1  // Wyrd RUne
```
  * Expected Result: All runes should have a stacking limit of 60 only
  * How to Reproduce: Stack the items in your inventory
  * Official Information: https://irowiki.org/wiki/Rune_Mastery#Notes

* **Modifications that may affect results**: 
none

**Comment by Lemongrass3110** [comment]
#2181
