### ISSUE TITLE
pcblockmove and pcblockskill not blocking player from move or cast spell if using  sleep2 after it

### ISSUE THREAD

**Issue by hurtsky** [rathena/rathena#2821]
* **rAthena Hash**: fe9f1ace66ead23abe64d1d45833c40e87552fbe

* **Client Date**: 20170517

* **Server Mode**: renewal

* **Description of Issue**: 
  * Result:  player still able to move, or cast a spell
  * Expected Result: should stop player from moving or cast a spell
  * How to Reproduce: 
```
-	script	Test	-1,{
	end;
OnFly:
	pcblockmove getcharid(0) , 1;
	pcblockskill getcharid(0) , 1;
	message strcharinfo(0) , "Starting to fly!!!!";
	sleep2 2000;
	message strcharinfo(0) , "Flyinggggg!!!!";
	sleep2 2000;
	message strcharinfo(0) , "Argghhh!!!!";
	sleep2 2000;
	message strcharinfo(0) , "Atlastt!!!!";
	sleep2 500;
	pcblockmove getcharid(0) , 0;
	pcblockskill getcharid(0) , 0;
	atcommand "@warp " + .@atcmd_parameters$[0];
	end;

OnInit:
	bindatcmd ( "fly" , strnpcinfo(3) + "::OnFly" );
	end;
}
```
  * Official Information: none
   

* **Modifications that may affect results**: 
  
   none

**Comment by aleos89** [comment]
```
But what about GID?
-------------------

GID stands for the Game ID of something, this can either be the GID obtained
through mobspawn (mob control commands) or the account ID of a character.
```
From the script command documentation. Your `getcharid` should be using option 3, not 0.

**Comment by hurtsky** [comment]
@aleos89 thanks, sorry for not reading the GID part.. issue not valid
