### ISSUE TITLE
More Items Correction (In general Equips) And new item 1835

### ISSUE THREAD

**Issue by BrOgBr** [rathena/rathena#2825]
* **rAthena Hash**: idk

* **Client Date**:  irrelevant

* **Server Mode**: irrelevant

* **Description of Issue**: 
  * Result: Most errors in Item's Script. _(but in some items, Weight and ATK/MATK rate too)_ **And new item _"1835"_ Spartacus [2]**.
  * Official Information: I've used **DivinePride** _(Using All Servers to compare)_ and sometimes the iRO DB.
  

* **Modifications that may affect results**: 
  
  

Here the list:
_**(Already corrected)**_

```
1173,Muramasa_C,Muramasa,5,1,,0,204,,1,0,0x00004082,63,2,34,4,1,0,3,{ bonus bCritical,30; bonus bAspdRate,8; bonus2 bAddEff,Eff_Curse,10; },{},{}
1317,Academy_Axe,Academy Axe,5,0,,1600,130,,1,1,0x00040420,63,2,2,1,1,1,6,{ bonus bMaxHP,200; bonus bAspdRate,5; bonus bAspdRate,BaseLevel/10; bonus bMaxHP,(-40*(BaseLevel/10)); },{},{}
1383,Holy_Celestial_Axe,Celestial Axe,5,20,,1500,200,,1,0,0x000444A2,63,2,34,4,60,1,7,{ bonus bAtkEle,Ele_Holy; bonus bUnbreakableWeapon,1; bonus2 bAddRace,RC_Undead,10; bonus3 bAutoSpell,"AL_BLESSING",5,30; },{},{}
1415,Skewer,Brocca,5,20,,850,85,,3,0,0x00004082,63,2,2,4,48,1,4,{ bonus bIgnoreDefClass,Class_Normal; bonus2 bAddEle,Ele_Neutral,25; },{},{}
1581,F_Diary_Of_Great_Sage_C,Diary Of Great Sage,5,1,,0,135,,1,2,0x00410100,63,2,2,3,1,0,15,{ bonus bMatkRate,20; bonus bAspdRate,5; },{},{}
1653,Staff_Of_Healing_C,Staff of Healing,5,20,,0,10:100,,1,0,0x00008110,63,2,2,3,1,0,10,{ bonus bAtkEle,Ele_Holy; bonus bHealPower,18; },{},{}
//1655,Adventure_Staff,Adventure Staff,5,0,,0,60,,1,0,0x00810204,63,2,2,1,1,0,10,{ bonus bUnbreakableWeapon,1; },{},{}
1671,Staff_Of_Evil_Slayer,Devil Won Staff,5,10,,800,30:155,,,1,0x00818315,63,2,2,3,100,1,10,{ bonus2 bAddRace,RC_Undead,10; bonus2 bAddRace,RC_Demon,10; .@r = getrefine(); if(.@r>=9) bonus bMatkRate,5; if(.@r>=12) bonus bMatkRate,7; },{},{}
1677,Ru_Blue_Wand,Blue Wand,5,10,,0,50,,1,1,0x00000200,56,2,2,3,100,1,10,{ bonus bDex,5; bonus bInt,5; },{},{}
1835,Spartacus,Spartacus,5,0,,600,100,,1,0,0x00008100,63,2,2,4,50,2,12,{ .@r = getrefine(); bonus bAtkRate,.@r*1; if(.@r>9) { bonus bNoSizeFix,0; } },{},{}
```

Special thanks to @sader1992 and **Haruka Mayumi**. _(helped with some script)_

**Comment by Atemo** [comment]
Thanks! But can you submit your change in a PR?

**Comment by BrOgBr** [comment]
@Atemo Sorry, but what does "PR" mean?

**Comment by Lemongrass3110** [comment]
Try to read [Contributing.md](https://github.com/rathena/rathena/blob/master/.github/CONTRIBUTING.md#how-to-create-pull-requests-pencil) :-)

**Comment by BrOgBr** [comment]
This step **"fork rAthena"** seems very hard for me :-D
I've never used Git Bash.

**Comment by Lemongrass3110** [comment]
Ah you do not need git bash for this.
Just go on rAthena's github [page](https://github.com/rathena/rathena).
And then click here:
![grafik](https://user-images.githubusercontent.com/3517879/35299425-8f38e1fa-0085-11e8-840f-203df3df86f0.png)
GitHub will do the rest for you! If you need any further help you can also get in touch with us via Discord!

**Comment by BrOgBr** [comment]
@Lemongrass3110 
I think that I did it.
It was hard, sorry for any mistake.

**Comment by Lemongrass3110** [comment]
Yes it worked!
You can see the result here #2826
