### ISSUE TITLE
Euphy's Quest Shop

### ISSUE THREAD

**Issue by RadianFord** [rathena/rathena#283]
If there's a same ID# of an Item but in different shop number.

for example
Add(1,501,1,1,1) and
Add(2,501,1,0,0,503,10)

the first shop " 1 " info will be copied by the " 2 " the result will be on Shop 2

You need 1 Cash Points + 503 10x to receive 1x of 501.

**Comment by Lemongrass3110** [comment]
``// -----------------------------------------------------------
//  Quest items -- do NOT use a reward item more than once!
//	Add(<shop ID>,<reward ID>,<reward amount>,
//	    <Zeny cost>,<point cost>,
//	    <required item ID>,<required item amount>{,...});
// -----------------------------------------------------------``

As you can see it clearly says in the description, that this is not supported.
Feel free to commit a PR that adds support for this.

**Comment by Atemo** [comment]
9849945756664ffa7fd810b69ef48c98e7592a0a
