### ISSUE TITLE
bug hairstyle

### ISSUE THREAD

**Issue by AtemAigami** [rathena/rathena#2830]
I'm using hexed 2017-06-14 and when I put the hairstyle in the number 30 of the error. I tested the hairstyle in the Hercules emulator and there was no error. This hairstyle error is in the rathena emulator. I tested the female hairstyle in the rathena emulator and had no error. Conclusion The error is in the male character's hairstyles of the emulator.

**Comment by Lemongrass3110** [comment]
Follow the issue template please.

If female works I would assume this is a client side issue.

**Comment by AtemAigami** [comment]
![sem titulo](https://user-images.githubusercontent.com/35803024/35389007-2aafb8f6-01bd-11e8-8089-77b22b2472d6.png)
![sem titulo1](https://user-images.githubusercontent.com/35803024/35389008-2ad310bc-01bd-11e8-8e88-d63b6f7afd2a.png)

**Comment by AtemAigami** [comment]
tested on hercules

**Comment by AtemAigami** [comment]
Now I'm going to test on rathena.

**Comment by AtemAigami** [comment]
I tested it on rathena now and there was no error. more I swear that the first time I tested bugou in hstyle 30 and the feminine character did not bugou.
