### ISSUE TITLE
Rebellion skills gender bug

### ISSUE THREAD

**Issue by rye305** [rathena/rathena#2831]
rAthena Hash:   eb1635f

Client Date:  25.Jan.2017

Server Mode:  Renwal

Result: Quick Draw Shot works as intended on Male Rebels but on Females, Quick Draw Shot does trigger but doesn't deal any damage. This issue happens with and without Eternal Chain. Didn't test with other skills yet.

Expected Result: Both genders deal the same damage.

How to Reproduce: Go to Prontera dummies -> put QDS on your skill bar -> auto attack the dummy and spam QDS

**Comment by aleos89** [comment]
I'm not aware of any gender restrictions source side that would disable this specific skill.

**Comment by rye305** [comment]
Alright we just figured out that its job level related. higher job = more hits = more damage. can be closed
