### ISSUE TITLE
unknown debug message in ipban.cpp, mapreg.cpp, and int_mail.cpp during server idle

### ISSUE THREAD

**Issue by hurtsky** [rathena/rathena#2834]
* **rAthena Hash**: ec59e95520d81c70f6c673f164ffb8f91ccd5d14

* **Client Date**: 20170517

* **Server Mode**: renewal

* **Description of Issue**: 
  * Result: throwing debug during idle
  * Expected Result: i think should not have this kind of debug message during idle
  * How to Reproduce: this log i get when my test server in idle, for some reason its keep throwing out this debug.  I thought the db connection is disconnected but it is not. 
```
[Info]: Pinging SQL server to keep connection alive...
[Info]: Pinging SQL server to keep connection alive...
[Info]: Pinging SQL server to keep connection alive...
[SQL]: DB error - Can't connect to MySQL server on '127.0.0.1' (111)
[Debug]: at ipban.cpp:110 - DELETE FROM `ipbanlist` WHERE `rtime` <= NOW()
[SQL]: DB error - Can't connect to MySQL server on '127.0.0.1' (111)
[Debug]: at mapreg.cpp:247 - UPDATE `mapreg` SET `value`='809' WHERE `varname`='$DTS_Time' AND `index`='0' LIMIT 1
[SQL]: DB error - Can't connect to MySQL server on '127.0.0.1' (111)
[Debug]: at int_mail.cpp:254 - SELECT `id`,`char_id`,`account_id` FROM `mail` `m` INNER JOIN `char` `c` ON `c`.`char_id`=`m`.`dest_id` WHERE `type` = '2' AND `time` <= UNIX_TIMESTAMP( NOW() - INTERVAL 15 DAY ) ORDER BY `id` LIMIT 31
[Info]: Pinging SQL server to keep connection alive...
[Info]: Pinging SQL server to keep connection alive...
[Info]: Pinging SQL server to keep connection alive...
[Info]: Pinging SQL server to keep connection alive...
[Info]: Pinging SQL server to keep connection alive...
[Info]: Pinging SQL server to keep connection alive...
[Info]: Pinging SQL server to keep connection alive...
[Status]: Request for connection of hurtsky (ip: x.x.x.x)
[Notice]: Authentication accepted (account: hurtsky, id: 2000000, ip: x.x.x.x)
[Status]: Connection of the account 'hurtsky' accepted.
```

  * Official Information: none
  

* **Modifications that may affect results**: none

**Comment by Lemongrass3110** [comment]
Could you at least tell us which server‘s output this is? I see messages for tables from all three of them.
And what makes you think that the connection is still open?
The only issue I see is that you can not connect to MySQL(see error code 111) and that surely is no rAthena problem.

**Comment by hurtsky** [comment]
@Lemongrass3110  server output?, 
see the last status, `[Status]: Connection of the account 'hurtsky' accepted.`  i able to login normally, and start play.. this only happen when the server is idle.. im reporting this because i got like 3 times something like this while its idle.. if its not related, you can close this..

**Comment by Lemongrass3110** [comment]
The problem is that you have mixed all three servers(login,char,map) according to what I see here.
It's possible that your connection simply is unstable and that's the issue.

**Comment by hurtsky** [comment]
okay, just checked the whole log, nothing disconnection happen. the connection between map, char, and login is between localhost, i dont think that the issue.. btw i will close first this issue..

**Comment by Lemongrass3110** [comment]
Its not the connection between the servers I am talking about, but the connection from the servers to the MySQL service. It could even be the MySQL service itself that is unstable and/or not responding.

**Comment by hurtsky** [comment]
okay, i will recheck.. thanks for your suggestion.
