### ISSUE TITLE
Rolling Cutter GX

### ISSUE THREAD

**Issue by ecdarreola** [rathena/rathena#2835]
* **rAthena Hash**: ec59e95

* **Client Date**: 20170125

* **Server Mode**: Renewal

* **Description of Issue**: Rolling Counter Resets immediately after using Back Slide or Dark Illusion skills
  * Result: Rolling Counter Resets immediately back to 1 after using backslide or Dark illusion skills
  * Expected Result: Should not reset immediately there should be atleast a cooldown or timer
  * How to Reproduce: Use rolling cutter lock at 1 cell, complete the count to 10 or even not. Use Backslide or Dark Illusion after using the said skill. Counter is reset.
  * Official Information: The Spin Count will wear off either after three seconds, moving or using another skill except the Back Slide or Dark Illusion skills.

https://irowiki.org/wiki/Rolling_Cutter
  

* **Modifications that may affect results**: Gepard

**Comment by aleos89** [comment]
Would be good to confirm if this is how kRO behaves as well.

**Comment by secretdataz** [comment]
My test result from kRO shows that no thief and assassin(cross) skill reset rolling cutter stacks.

**Comment by hederod** [comment]
teleport not reset de spin count too

**Comment by ecdarreola** [comment]
Will check pull later

**Comment by Lelouzh** [comment]
@secretdataz  it still reset after using blackslide my fri.
