### ISSUE TITLE
[SQL] Strange messages in achievement

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#2836]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/ae69e506263f9b183c945f49b1d88c5fc2b73a6a
* **Client Date**: 20170531
* **Server Mode**: Renewal
* **Description of Issue**: I have been observing the terminal of the server and I came across these messages, I believe they should not exist, because in the structure of the table does not have these fields.

PRINT: https://imgur.com/oNbivzK

**Comment by aleos89** [comment]
Your line 51 doesn't seem to match mine on a clean rAthena.

Either way, the values source side are all in the `achievement` SQL table (even from your screenshot they match). See [here](https://github.com/rathena/rathena/blob/master/sql-files/main.sql#L31)

**Comment by admkakaroto** [comment]
Here the tables are correct too, I'm running the latest version of rathena, the only heavy modification in source is Gepard.

Print0: https://imgur.com/yBLuufT
Print1: https://imgur.com/Z9wLcQS

**Comment by aleos89** [comment]
Are you still receiving these errors? I haven't been able to reproduce this. From your initial screen shot you had another SQL error. You seem to have a second query trying to run before you freed the first one.

**Comment by admkakaroto** [comment]
I did not watch the terminal anymore, but I'll do it today.

**Comment by admkakaroto** [comment]
I am 1 hour observing the terminal and I was able to get this message:
![123](https://user-images.githubusercontent.com/6227618/38589520-ca5b587c-3d01-11e8-9b70-67a4c42ba2a0.png)

**Comment by aleos89** [comment]
That error doesn't apply to rAthena. That's a custom field and just means you're trying to store a larger value than what the SQL DB can store.

I'll go ahead and close this for now. If it happens again we can reopen.
