### ISSUE TITLE
[HARD ISSUE] src/config/renewal.h

### ISSUE THREAD

**Issue by tmav94** [rathena/rathena#284]
If you comment the "//#define RENEWAL_ASPD" the server will get the error:

status.c: In function ‘status_calc_bl_main’:
status.c:4514: warning: implicit declaration of function ‘status_calc_aspd’
        CC      storage.c
        CC      trade.c
        CC      unit.c
        CC      vending.c
        LD      map-server
obj/status.o: In function `status_calc_bl_main':
/home/src/map/status.c:4514: undefined reference to `status_calc_aspd'
/home/src/map/status.c:4514: undefined reference to `status_calc_aspd'
collect2: ld returned 1 exit status
make[1]: *** [map-server] Error 1
make[1]: Leaving directory `/home/src/map'
make: *** [map] Error 2

**Comment by tmav94** [comment]
its not fixed, i'm use the latest git. '-'

**Comment by Lemongrass3110** [comment]
Works for me now on Windows with VS2012.
What do you use?

**Comment by aleos89** [comment]
Works fine for me on MSVS2013.

**Comment by tmav94** [comment]
Oh god... I'll try to re-update my git.
After that, i'll post the result.

**Comment by anacondaqq** [comment]
### can't confirm...
@tmav94 you are somewhere wrong.... check again renewal.h....
