### ISSUE TITLE
Card Seller sells Boss cards

### ISSUE THREAD

**Issue by vstumpf** [rathena/rathena#2844]
* **rAthena Hash**: de9b4ef

* **Client Date**: N/A

* **Server Mode**: N/A

* **Description of Issue**: The card seller sells boss cards.
  * Result: The Card Seller in rathena/npc/custom/card_seller.txt sells Boss Cards
  * Expected Result: It should not sell boss cards
  * How to Reproduce: Run the card seller.
  * Official Information: None, this is in the custom folder.

* **Modifications that may affect results**: N/A

Seems like an easy fix. The MD_BOSS mode was removed over a year ago, but this script was never updated.

**Comment by Lemongrass3110** [comment]
Card seller also has a problem with latest mysql default settings(only full group by setting).

**Comment by VeilsideGX** [comment]
This issue is occuring again on the latest svn. MVP boss cards still showing on this npc
