### ISSUE TITLE
Battle calc attack with unknow attack type.

### ISSUE THREAD

**Issue by tmav94** [rathena/rathena#285]
[Error]: battle_calc_attack: unknown attack type! 0 (skill_id=2414, skill_lv=5)
[Error]: battle_calc_attack: unknown attack type! 0 (skill_id=2414, skill_lv=5)

**Comment by Playtester** [comment]
Additional info: 2414 is the skill REVERBATION.

**Comment by cydh** [comment]
didn't test this yet, but I sense there's way this can be happen. when Reverberation expired then trigger `skill_trap_splash()`

**Comment by cydh** [comment]
if it's still, and easy to reproduce, try apply this first https://gist.github.com/cydh/f31bd1ae24aa167db774

**Comment by aleos89** [comment]
Reverberation issues should have been resolved in 9f6f55c. I haven't seen any warnings since.
