### ISSUE TITLE
Flywing opens teleport menue during aspd-based CD and creamy card equipped

### ISSUE THREAD

**Issue by Fraterna** [rathena/rathena#2850]
* **rAthena Hash**:  ec59e95

* **Client Date**: 2017-05-17

* **Server Mode**: Renewal

* **Description of Issue**: When using a Flywing during an aspd-based cooldown it opens the teleport lvl 1 menue when a creamy card is also equipped (doesn't happen when no creamy card is present, and even when it's present it doesn't happen always). 
tested on hunter/sniper with slow aspd, imidiately use flywing during Doublestrafe-CD and on a RG during Vanishing Point CD. haven't tested on other skills yet.
skill.conf setting: "skip_teleport_lv1_menu: no"

  * Result: TP lvl 1 menue pops out even when teleport isn't in the skillbar.
  * Expected Result: instant teleport without menue.
  * How to Reproduce: see description
  * Official Information: well, we all should know how a flywing works xD
  

* **Modifications that may affect results**: none so far.

**Comment by aleos89** [comment]
I'm unable to reproduce this, testing on 913cf87. I increased Double Strafe's delay from 1 second, equipped a Clip + Creamy Card, and `skip_teleport_lv1_menu` set to no.

I use DS, consume a Fly Wing, and I'm teleported without being prompted with the menu. If I use the Teleport skill granted from Creamy Card, it shows the window.
