### ISSUE TITLE
AL_HOLYWATER casting on water without bottles

### ISSUE THREAD

**Issue by Daegaladh** [rathena/rathena#2853]
* **rAthena Hash**: 31988abd1919a42e7ccedaf597fa13d4a7308865

* **Client Date**: Not relevant

* **Server Mode**: Both

* **Description of Issue**: AL_HOLYWATER should not cast or consume SP on water when not having empty bottles.
  * Result: It casts and consume SP despite showing the skill fail message.
  * Expected Result: AL_HOLYWATER should not cast or consume SP when not having empty bottles, both in water (and water skills) and outside water.
  * How to Reproduce: 
  * Official Information: See "Expected Result", tested on iRO.
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Holy Water uses this state check from `skill_require_db`:
```
31,0,0,10,0,0,0,99,0,0,water,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0								//AL_HOLYWATER
```

**Comment by Lemongrass3110** [comment]
Hmm I think I remember @Playtester was saying something like this once?

**Comment by Playtester** [comment]
I think you are referring to "Further testing" post I made here: https://github.com/rathena/rathena/issues/1119

**Comment by Daegaladh** [comment]
Apparently euRO never shows "skill has failed" messages, even if you have the chat option active.
Tested again on iRO, it shows "skill has failed" when requirements aren't met, the rest remains the same.

**Comment by Daegaladh** [comment]
Ok after more testing i've confirmed WZ_WATERBALL is working correctly, and AL_HOLYWATER just needs a little fix.

**Comment by mrjnumber1** [comment]
MG_FIREWALL has similar behavior. the player has its own internal firewall count variable. once they've got 3 used already, the skill will instantly fail to cast. on rathena, it tries to cast, and then checks that if the player has maxcount after cast completion, rather than before starting.

**Comment by Daegaladh** [comment]
@mrjnumber1 You're right, I've just tested it on iRO Classic
