### ISSUE TITLE
Rebellion Skill Heat Barrel ASPD

### ISSUE THREAD

**Issue by rye305** [rathena/rathena#2857]
One of my players reported it. It's supposed to add 5 ASPD but gives only 3.

* **rAthena Hash**:  4171cd1

* **Client Date**:  25 jan 2017

* **Server Mode**:  Renewal

  * Result: Adds 3 ASPD
  * Expected Result: Adds 5 ASPD

**Comment by Lemongrass3110** [comment]
According to [status.cpp](https://github.com/rathena/rathena/blob/master/src/map/status.cpp#L6837) it should increase your aspd by val1.
According to [skill.cpp](https://github.com/rathena/rathena/blob/master/src/map/skill.cpp#L6686) val1 should match the skill level.
It was changed from val3 to val1 in 6a2c122 by @aleos89

**Comment by rye305** [comment]
![grafik](https://user-images.githubusercontent.com/33780589/35628448-378b1794-069c-11e8-9eea-dd1f0c0b267a.png)

same here in my status.cpp - just tested it myself and can confirm it adds only 3 ASPD instead of flat 5

**Comment by aleos89** [comment]
Correct, the skill adds a fixed amount of ASPD based on the used skill level. This was part of the Rebellion Awakening patch.

**Comment by rye305** [comment]
![grafik](https://user-images.githubusercontent.com/33780589/35631215-9eca305a-06a3-11e8-9a5a-6ed6b12756c6.png)
Here it says +5 ASPD at level 5, correct?

![grafik](https://user-images.githubusercontent.com/33780589/35631469-408bb076-06a4-11e8-80c0-2a411830c4d5.png)
No Heat Barrel = 172 ASPD

![grafik](https://user-images.githubusercontent.com/33780589/35631528-6770e7d8-06a4-11e8-93c3-165cade0d3d6.png)
with Heat Barrel LEVEL 5 = 174

thats +2 ASPD and not +5?

**Comment by Akaineko-astasi** [comment]
Its bonus is calculated as `sc` bonus ( bonus value * AGI / 200 ) and then gets summed with the agi-dex part and floored. So it depends on AGI twice.
