### ISSUE TITLE
compilation warnings at x64 version of the emulator on Windows from Visual Studio: size_t, strlen(), and so on

### ISSUE THREAD

**Issue by anacondaq** [rathena/rathena#2859]
## Just table to clear where is the problems (Win10x64 VS2017)

Release x32 | Release x64 | Debug x32 | Debug x64
------------ | ------------- | ------------ | -------------
_No Warnings_ | **Many Warnings** | _No Warnings_ | **Many Warnings**
| | strlen() (size_t to different types), and different type conversions warnings | | same as release x64 (strlen() conversions) and different type  conversions warnings
Success Compilation | Success Compilation with warnings | Success Compilation | Success Compilation with Warnings

### Example
![Just check highlighted text](https://user-images.githubusercontent.com/9905636/35649308-5b4a2c7a-06e1-11e8-8cef-93a519c00c41.png)

As you remember, strlen() return expected type is size_t, and the function used a lot of in the code in different things. At x64 releases / debug versions of rAthena it is provoke a lot of warnings in the code.

![image](https://user-images.githubusercontent.com/9905636/35649435-bfa62c8c-06e1-11e8-9bae-0c864b4f44e0.png)

### Few important notes:
I do not publish ALL warnings (there are dozens of them), the best thing what you can do it is spent some time for fixing all warnings in one PR. Why in one PR? because all of these work is complex and by fixing it in single commit single warnings very bad idea, because can provoke warnings at different architecture, need to fix it in one PR to be sure there is no issues on all platforms for different code release architectures (x32/x64 debug/release). For now there is no issues at windows VS2017 with x32 version, but a lot of warnings at x64..

### Suggestion

1. Need to spent some time to recompile at Release x32/x64, Debug x32/x64 at windows 10 and any linux distro to fix common warnings in the code. 
2. Please do not add these warnings to ignoring list, this is very bad practice (already saw very critical warnings just added to be ignored via compiler, this is not okay)

### How reproduce?
Recompile your server at x64 mode at Visual Studio 2017 (both, release and debug, and you will see it)

**Comment by Lemongrass3110** [comment]
This is not windows specific to be fair. It's simply x86 vs x64.
