### ISSUE TITLE
Shadow Chasers 'Feint Bomb' skill

### ISSUE THREAD

**Issue by rye305** [rathena/rathena#2862]
* **rAthena Hash**: c5789f1

* **Client Date**: 25.Jan.2017

* **Server Mode**: Renewal

  * Result: Can't use skills during Feint Bomb

  * Expected Result: Should be able using skills once u use feintbomb and "hide" and not after the skill has ended.

  * How to Reproduce: Use Feint Bomb and try to use a skill while you're hidden. While you're hidden it won't let you use skills.

**Comment by ecdarreola** [comment]
Comment this line in status.cpp 

StatusChangeStateTable[SC__FEINTBOMB]			|= SCS_NOCAST

Try

**Comment by rye305** [comment]
works. tyvm
