### ISSUE TITLE
egg on storage incorrect location

### ISSUE THREAD

**Issue by talesofragnarok** [rathena/rathena#2864]
* **rAthena Hash**: 

* **Client Date**:  20170614

* **Server Mode**:  renewal

* **Description of Issue**: 
  * Result:  Egg located at weapon slot on storage after inserting it on storage
  * Expected Result:  it must be on Misc
  * How to Reproduce:  get a pet egg and use storage then put the egg on storage and then close the storage and open it again click misc the egg is not there and click weapon you will see that the egg is there
  * Official Information:
  

* **Modifications that may affect results**: 
  
  

![image](https://user-images.githubusercontent.com/34671929/35767929-9d2b8008-092f-11e8-8415-ef884081e049.png)

**Comment by BrOgBr** [comment]
Confirmed.

**Comment by vstumpf** [comment]
What happens on officials?

**Comment by aleos89** [comment]
Aegis:
![image](https://user-images.githubusercontent.com/3521753/36231029-90acc0de-11aa-11e8-8de3-7fe9dae1d712.png)
rAthena (b48f0e8):
![image](https://user-images.githubusercontent.com/3521753/36231037-9e7c8d34-11aa-11e8-87ea-167017d32823.png)
