### ISSUE TITLE
Level 11 fire, cold, thunder bolts skill range issue

### ISSUE THREAD

**Issue by pajodex** [rathena/rathena#2865]
* **rAthena Hash**: 
0f33de9b4dfb88368dd841ddf53285fc066f0f4e

* **Client Date**: 
2017-05-14

* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result: At level 11 and up on skills fire/cold/thunder the caster's skill range becomes 1. Literally the caster gets near the target.
  * Expected Result: No changes in skill range upon level becomes more than 10
  * How to Reproduce: I set an item which give the skills 1 more extra levels. which means level 10 bot = 11 bolts when the certain item is worn
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by pajodex** [comment]
Skill at level 10
![screenrathena039](https://user-images.githubusercontent.com/36108172/35768813-c6e3b070-093c-11e8-8dba-7a877ebd81e6.jpg)
Range = ok
![screenrathena041](https://user-images.githubusercontent.com/36108172/35768814-c71d038e-093c-11e8-80d1-87181ebfba61.jpg)
Skill at level 11
![screenrathena037](https://user-images.githubusercontent.com/36108172/35768815-c757b60a-093c-11e8-820c-9de380c49517.jpg)
caster comes close to target
![screenrathena038](https://user-images.githubusercontent.com/36108172/35768816-c7a0016c-093c-11e8-9596-5d214bc83b06.jpg)

**Comment by pajodex** [comment]
Skill at level 10
![screenrathena037](https://user-images.githubusercontent.com/36108172/35768830-f46361e4-093c-11e8-9031-5501451bfbd3.jpg)
![screenrathena038](https://user-images.githubusercontent.com/36108172/35768834-fdd77c88-093c-11e8-993d-67585c49b8ec.jpg)
---------------------------------------------------
skill at level 11
![screenrathena039](https://user-images.githubusercontent.com/36108172/35768839-08df5ef2-093d-
![screenrathena041](https://user-images.githubusercontent.com/36108172/35768841-0e2b73b4-093d-11e8-8ecb-4cbc2daa44c8.jpg)
11e8-9c6a-f151056e1747.jpg)

**Comment by aleos89** [comment]
We don't support level 11 for players so it's default to 1 range. You have to modify your database files to support this.

**Comment by Playtester** [comment]
Also to add to that you also need to modify the client otherwise it thinks the range is 0 and always tries to move next to the target before even sending a skill request.
