### ISSUE TITLE
renewal mob atk/matk is all wrong!

### ISSUE THREAD

**Issue by mrjnumber1** [rathena/rathena#2866]
* **rAthena Hash**: current
* **Server Mode**: Renewal ONLY
* **Description of Issue**: 
  * Result: Currently mob MATK and ATK is completely inaccurate values!
  * Official Information: 
having extracted more information from aegis zone, i've determined how off mob atk/matk has been for many years (seems hercules noticed as well, based on what they've done with mob/hom/merc matk).
now in aegis, mobs' atk1/atk2 parameters are in fact atk/matk base values. all of the values in our db need completely changed unfortunately..

said succinctly, it appears that mob MATK should be `blevel+int+70~130%atk2` ... right now it is using the same formula as players'
```
int CNPC::GetMagicAttPower()
{
  atk2 = m_characterInfo.atk2;
  minmatk = 7 * atk2 / 10;
  maxmatk = 13 * atk2 / 10;
  if ( !minmatk )
    minmatk = 1;
  if ( !maxmatk )
    maxmatk = 1;
  blevel = m_characterInfo.clevel;
  _int = m_characterInfo.Int;
  return blevel + _int + GetServerRandom(minmatk, maxmatk) + m_fvarshistory_ItemMATK_Amount.m_Value;
}
```

the MATK is harder to prove unfortunately.. it seems like merc matk is still `int_ + int_ / 5 * (int_ / 5)`, 
```
int CNPC::GetItemAttPower()
{
  int atk1 = m_characterInfo.atk1;
  int minbonus = 8 * atk1 / 10;
  int maxbonus = 12 * atk1 / 10;
  if ( !GetEffective(EFST_MAXIMIZE, 0) )
    minbonus = maxbonus;
  dmg = m_characterInfo.Str + m_characterInfo.clevel + GetServerRandom(minbonus, maxbonus);
  return ((dmg * m_fvarshistory_INC_ItemATK_Percent.m_Value) / 100.0
        + (dmg + m_fvarshistory_ItemATK_Amount.m_Value));
}
```
so atk is 80%-120% atk + lv+str

you can verify (the ATK values, at least...) by checking what gnjoy website lists.
http://ro.gnjoy.com/guide/runemidgarts/popup/monsterview.asp?monsterID=BAPHOMET
http://ro.gnjoy.com/guide/runemidgarts/popup/monsterview.asp?monsterID=BAPHOMET_

so we need to adjust mob_parse_dbrow. then, of course, it leaves the hard part - going back and fixing every single DB entry... orz

**Comment by mrjnumber1** [comment]
here's a gist to fix it in mob_db.txts

https://gist.github.com/mrjnumber1/a144485934b7b1af74e7df2201252613

of course, it outputs both at once but oh well. it can be adjusted more for later.

**Comment by cydh** [comment]
how about on pre-renewal for atk & matk. any info? now I doubt current mob matk formula after knowing atk2 (in renewal) for base matk,

**Comment by mrjnumber1** [comment]
it's the same as for players, where it's base int + (base int/7)^2~(base int/5)^2. the only exception is there's a special case below 10 int, where the matk power is always `int+(int/5)^2` (because the max and min are the same in these cases),

**Comment by cydh** [comment]
I meant
1. in pre-re, mobs (+pet, merc, elem) has min matk uses `(some_base_stat) + db_atk2 * 70 / 100`?
2. in pre-re, mobs (+pet, merc, elem) has max matk uses `(some_base_stat) + db_atk2 * 130 / 100`?
3. in pre-re, mobs (+pet, merc, elem) has min atk uses `(some_base_stat) + db_atk1 * 80 / 100`?
4. in pre-re, mobs (+pet, merc, elem) has max atk uses `(some_base_stat) + db_atk1 * 120 / 100`?

**Comment by mrjnumber1** [comment]
1-4 are not true at all for pre-re.. everyone in pre-re is just fine, don't worry about them

**Comment by shadowofdoom** [comment]
Hello, sorry for necroin this thread.
Is the issue with magic damage has been fixed?
Right now I'm facing similar issue. The problem is not only monster's magic damage is being too low, but player's magic damage as well.
Every single skill of Warlock is really having too low damage. Even at full equip setup Warlock's magics only do about tens of thousands of damage. While any other physical job/skill can do about hundreds of thousands to millions damage at the same caliber equipments.
My server is high rate settings with players having around 300 base level. Is there something I'm missing or it is an unintended bug?
Thank you.
