### ISSUE TITLE
Gates of Hell damage still affected by range modifier

### ISSUE THREAD

**Issue by laziem** [rathena/rathena#2867]
* **rAthena Hash**: e385e167a

* **Client Date**: 2017-05-17

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: **Gates of Hell** damage still affected by range modifier   
  * Expected Result: Range modifier should not increase Gates of Hell damage
  * How to Reproduce: Use any card / enchant with Expert Archer / increase range damage
  * Official Information: _I don't have official information from kRO, but from iRoWiki:_ **_Ranged Atk modifier will not give any effects to this skill._**
* **Modifications that may affect results**: none

![goh_bug](https://user-images.githubusercontent.com/31171415/35777651-4027f75a-09e4-11e8-81c2-ee35ab74ba97.jpg)

**Comment by vstumpf** [comment]
iROWiki is not the greatest place for information on mechanics. Usually you need to test on officials.

**Comment by Paoly28** [comment]
atk portion is affected by ranged modifiers , hp portion isnt though id prolly expect in the long run for goh to interact the same way as dragon breath.

**Comment by laziem** [comment]
Please check bug report on NovaRO, this link have GOH tested on kRO [ this ](https://www.novaragnarok.com/forum/bug-tracker/fixed-bugs/gate-of-hell-should-not-take-ranged-damage-multipliers-r1104) & [ this ](https://www.novaragnarok.com/forum/bug-tracker/fixed-bugs/gate-of-hell-hpsp-damage-portion-should-ignore-all-external-modifiers-r1106/)

**Comment by aleos89** [comment]
Related to #771.
