### ISSUE TITLE
Elemental Spirit System Damage

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#2869]
* **rAthena Hash**: 

https://github.com/rathena/rathena/commit/ef651df6a49187dc9e7ace48511918e98e955668

* **Client Date**: 

2017

* **Server Mode**: 

Renewal

* **Description of Issue**: 

  * Result: 
There is currently some error in the damage increase of sorcerer's spirit abilities. An observed problem was in the elemental bonus to increase skill damage according to the level of job level. Currently the increase is insignificant and does not meet the required percentage. Currently the damage increases about 40%. I performed 15k tests for 20k damage with the elemental buff.

  * Expected Result: 
SO_DIAMONDDUST should increase its damage by (job_lvl * 5)% or 300%. 

  * How to Reproduce: 
Get item 991. Use the skill Summon Aqua lv2. Use the Elemental Control skill lv1. Test the damage with and without the elemental. You will observe the problem. This is also true of others like Varetyr Spear skill.
  * Official Information:
https://irowiki.org/wiki/Elemental_Spirit_System

Currently the formula exists in battle.cpp, but something prevents it from working properly. 
Example:

					case SO_DIAMONDDUST:
						skillratio = ( 200 * ((sd) ? pc_checkskill(sd, SA_FROSTWEAPON) : 0) + sstatus->int_ * skill_lv );
						RE_LVL_DMOD(100);
						if( sc && sc->data[SC_COOLER_OPTION] )
							skillratio += (sd ? sd->status.job_level * 5 : 0);
						break;

  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Working as intended on 620e397. My damage went from 93 a hit to 345 at job level 60 vs a Barricade (1905). Make sure you adjust your Elemental's mode (Elemental Control skill) so your bonus is properly given.
