### ISSUE TITLE
The flag for Fixed item drop

### ISSUE THREAD

**Issue by teededung** [rathena/rathena#2870]
* **rAthena Hash**: 
I downloaded latest zip from rathena github

* **Client Date**: 
2017-06-14b

* **Server Mode**: 
Renewal

Issue:
I don't know how to describe this issue, but here is the link:
https://rathena.org/board/topic/98173-server-database-editor/?do=findComment&comment=341443

**Comment by Lemongrass3110** [comment]
How did you notice that it was still affected?

**Comment by aleos89** [comment]
Do you have RENEWAL_DROP disabled?

**Comment by mrjnumber1** [comment]
this.. is reporting an error in SDE and not rathena.

i guess SDE isn't updated for the mods to the monster md system

**Comment by teededung** [comment]
@Lemongrass3110 I use @mi to check the monster drops

**Comment by teededung** [comment]
@aleos89 Yes, I did

**Comment by teededung** [comment]
@aleos89 I was misunderstood. Thanks
