### ISSUE TITLE
Sarah & Fenrir Instance free Sarah's Earring

### ISSUE THREAD

**Issue by rye305** [rathena/rathena#2871]
attention: im not sure if this is intended!

* **rAthena Hash**: c5789f1

* **Client Date**: 25  jan 2018

* **Server Mode**:  renewal

  * Result: get free earring for no effort

  * Expected Result: not sure if its intended but if not = get no earring until really completing the instance
  
* How to Reproduce: create party -> create instance -> go inside -> walk a lil bit down until the sequence starts -> @go 0 ( i pressed alt + 1 for @go 0 to teleport back to prontera while the blank dialogue box was there )-> go back to the instance entrance -> talk to professor and get a free earring

**Comment by Atemo** [comment]
This is strange but official behaviour.
