### ISSUE TITLE
Rebellion Skill Flicker

### ISSUE THREAD

**Issue by rye305** [rathena/rathena#2874]
rAthena Hash: 4171cd1

Client Date: 25 jan 2017

Server Mode: Renewal

Result: Flicker/Bound Trap deals around 1.5% current health when triggered on targets that are on top of a bound trap. MVP or not.

Expected Result: Flicker/Bound Trap should deal around 15% current health instead.

Source: https://irowiki.org/wiki/Binding_Trap

**Comment by aleos89** [comment]
I just tested on a Poring with 130 DEX using level 5 Bind Trap and it produced the correct amount of damage using b48f0e8.
