### ISSUE TITLE
Rebellion Skill 'Heat Barrel'

### ISSUE THREAD

**Issue by rye305** [rathena/rathena#2875]
rAthena Hash: 4171cd1

Client Date: 25 jan 2017

Server Mode: Renewal

Result: Heat Barrel consumes all coins but only considers that one coin is used no matter what the amount of coins consumed was. Thus, giving minimal ATK and ASPD bonus.

Expected Result: Heat Barrel should consumes all coins and scale according to the amount of coins consumed. Namely, 16% ATK per coin for a maximum of 160%

Source: https://irowiki.org/wiki/Hit_Barrel

This bug along with the Crimson Marker bug (https://github.com/rathena/rathena/issues/2863) and the Bound Trap bug (https://github.com/rathena/rathena/issues/2874) Is crippling the rebel class on my server and causing a high number of complaints.

**Comment by admkakaroto** [comment]
is missing ASPD bonus:
```
	[SKID.RL_HEAT_BARREL] = {
		"Heat Barrel (Acceleration Bullet)",
		"Max Level: 5",
		"^CC3399Requirement: Rich's Coin 1^000000",
		"Skill Form: ^339900Buff^000000",
		"Description: ^777777Consumes all coins to",
		"increase ASPD and ATK, reduces fixed cast",
		"time at the cost of HIT. Skill's level",
		"affect ASPD, ATK and fixed cast time bonus",
		"and HIT reducement. If the caster",
		"switches equipment during the duration,",
		"the skill's effect will dissapear. This skill",
		"can't be used with Madness Canceller or",
		"Platinum Alter. Skill duration is 60 sec.^000000",
		"[Lv 1]: ^777777ASPD +1, HIT -30^000000",
		"[Lv 2]: ^777777ASPD +2, HIT -35^000000",
		"[Lv 3]: ^777777ASPD +3, HIT -40^000000",
		"[Lv 4]: ^777777ASPD +4, HIT -45^000000",
		"[Lv 5]: ^777777ASPD +5, HIT -50^000000"
	},
```


Font: Zackdreaver GitHUB!

**Comment by rye305** [comment]
according to https://github.com/rathena/rathena/issues/2857 the ASPD part is working as intended. everything else isnt tho and this is one of the core skills of rebel

**Comment by admkakaroto** [comment]
test:

after:
https://imgur.com/IWI1n05

before:
https://imgur.com/vfw1705

no change, I use the latest version of rathena.

**Comment by aleos89** [comment]
@admkakaroto: Add agility. Agility plays a vital role in renewal ASPD.

@rye305: Please check out the PR and let me know if that fixes your damage issue.

**Comment by admkakaroto** [comment]
I figured it was independent of the agi, I'm going to look at it calmly at night, sorry.

**Comment by rye305** [comment]
@aleos89 will check this thoroughly in about 14-15 hours. thanks!

**Comment by redlightliu** [comment]
From 75a8f52
@aleos89 
I'm test the 'Heat Barrel' skill damage.
This skill damage is too high.
Is this formula really?

**Comment by redlightliu** [comment]
@rye305 
Ok,Thanks. I See.~

**Comment by talesofragnarok** [comment]
heat barrel doesn't show any additional aspd on my side im using latest rathena rev.

![image](https://user-images.githubusercontent.com/34671929/37636931-e52f285e-2c3f-11e8-9148-72a0c9fcbcd0.png)

normal with out heat barrel

when i cast heat barrel

![image](https://user-images.githubusercontent.com/34671929/37636942-019ecf4e-2c40-11e8-8923-7a7dccb20eeb.png)


heat reduced but the aspd still not moving?
