### ISSUE TITLE
Card Trader

### ISSUE THREAD

**Issue by rye305** [rathena/rathena#2896]
* **rAthena Hash**: c5789f1

* **Client Date**: 25.jan.2018

* **Server Mode**: Renewal

  * Result: Euphys Card Trader (\npc\other\card_trader.txt) doesn't recognize newer cards like all moscovia cards or charleston crisis cards like kickstep card etc.

  * Expected Result: recognize all cards

**Comment by Lemongrass3110** [comment]
Should be fixed in afab80f

**Comment by rye305** [comment]
thanks i will update tonight

**Comment by Atemo** [comment]
@Lemongrass3110 misread we updated [card_seller](https://github.com/rathena/rathena/blob/master/npc/custom/card_seller.txt) in https://github.com/rathena/rathena/commit/afab80fb6e3129102767624604d248ad37c03e91.
[card_trader](https://github.com/rathena/rathena/blob/master/npc/other/card_trader.txt) is an official script disabled by default containing a list of card to exchange. We won't change the list of card without official update.

**Comment by Lemongrass3110** [comment]
I thought he was talking about it because he wrote „Euphys“.

**Comment by rye305** [comment]
can you guys tell me where that "list" is? its not in the script..

it is by euphy @Lemongrass3110 

//===== rAthena Script =======================================

//= Card Trader

//===== By: ==================================================

//= Euphy

//===== Current Version: =====================================

//= 1.1 

//===== Compatible With: =====================================

//= rAthena SVN

//===== Description: =========================================

//= Exchange cards for points.

//============================================================
