### ISSUE TITLE
Rankings Bug

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#2898]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/ae69e506263f9b183c945f49b1d88c5fc2b73a6a
* **Client Date**: Any
* **Server Mode**: Renewal
* **Description of Issue**: The rankings that are displayed for some classes are buggy.
  * How to Reproduce: type in chat: /blacksmith | /taekwon or /alchemist

Refe: https://github.com/rathena/rathena/issues/2872
Print: https://imgur.com/jKmVWWf

**Comment by Daegaladh** [comment]
Works fine for me on b48f0e8896e318e1f3cc75aee4bfeace957d7f19, at least in pre-renewal mode.

**Comment by admkakaroto** [comment]
need to see no renewal.

**Comment by Akaineko-astasi** [comment]
![default](https://user-images.githubusercontent.com/12430338/36078818-a4d8d1e4-0f8c-11e8-83be-5a283cc9fec6.png)
Mode: Renewal 
Modifications: no

**Comment by aleos89** [comment]
I was unable to reproduce this as well using b48f0e8.
