### ISSUE TITLE
[BUG] Power Swing Restriction

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#2904]
* **rAthena Hash**: 
https://github.com/rathena/rathena/commit/41dbb30f6483d08fe4fc9a79bf36b0e66674e495

* **Client Date**: 

2017

* **Server Mode**: 

Renewal

* **Description of Issue**: 
  * Result: Mechanic Power Swing Skill is only working with Axe.
  * Expected Result: The ability should work with any type of weapon. Just to get out Axe Bomerang must be using Axe.
  * How to Reproduce: kRO vídeo 2017: https://www.youtube.com/watch?v=vdfX2apxtdQ
  * Official Information: https://www.youtube.com/watch?v=vdfX2apxtdQ

A change was made in the past, but it was in 2016. The 2017 video shows how it works.
https://github.com/rathena/rathena/issues/1079

**Comment by aleos89** [comment]
I went back and did some testing. Not sure how I came up with only Axe type is required.
