### ISSUE TITLE
rune knight quest update(or only TwRo)

### ISSUE THREAD

**Issue by XDXDMAN** [rathena/rathena#291]
rune knight quest step."Rune Knight Lunarea" test need not kill monster to next step now.
but I don't know other official server have this update or or only Twro...

My English is "poor(bad)", sorry...
thx.

**Comment by XDXDMAN** [comment]
Hello, everbody~
I find this, post "소울이터쵝오" is Korean :
http://ro.inven.co.kr/dataninfo/quest/detail.php?code=263

가이드 보고 막막하신분들 간단히 설명해드리면

엔피시 찾아가다가 룬나이트 집결지도착해서 시험보라는데[5분버티기] 캔슬나서

패스 시켜줘고 , 그다음 룬에대해서 책장가서 책읽고 그다음, 니플헤임가서 몹 10마리씩잡고

그다음, 돌아와서 룬에대해 보충공부할겸 룬을 20번 만들라는데 가이드보고 하시면데고

마지막 시험치라구하지만 역시 캔슬 나서 [룬나이트 대장]한테 가면 전직시켜주는데

대장에게 말걸기전에 페코 내리고 옆에 카프라한테 창고열어서 무게 0으로 마추시고

대장한테 말걸면 전직시켜 줍니다 물론 돈은 상관없구요 무게만 0이면 됩니다.

I don't understand Korean, so I use Google translate:

Briefly touch those who reported makmak Guide

I found the test to look enpisi Katakana Rune Knight gets ave [5 min prop] cancellation after

Hook and pass, then go for a rune reading book bookcase Then, go to Niflheim monsters holding 10 rats

Then, come back and make a rune rune 20 times for president and supplementary study, called. 

Dego you looking Guide

Chi La canceled after the last test, but also juneunde go to my ex - Rune Knight colon]

Open warehouse next to the captain to make him Capra Chapeco I should mechanism to Machu he weighs 0

Calls if told by a former captain will eopguyo matter of course, money is only the weight is zero.

Maybe mean this quest update.
Can find somebody who understand Korean translate to English.
 
If who understands chinese, you can read this:
我在韓國的大型討論區中的轉職任務文章中，找到下面某篇留言，有可能是指盧恩/符文騎士的轉職任務更新。
但由於我不懂韓文只能使用Google翻譯來翻譯。
你可以找懂韓文的人來翻譯這篇留言來確定是否證實這個任務的更新。

thx u~

**Comment by Lemongrass3110** [comment]
@rathena/rathena-script-db-developers could anyone look into this if we already have this now or if this issue still exists?

**Comment by Atemo** [comment]
According to the guide from the link above and the quote the character still need to kill the monsters.
```
13) [니플헤임 필드]에서 [듀라한] x10, [디스가이즈] x10, [큐브] x10, [하이로조이스트] x10 처치
* 이동 방법 : [움발라] → 북쪽 → 북쪽 → [니플헤임 필드]
```
```
패스 시켜줘고 , 그다음 룬에대해서 책장가서 책읽고 그다음, 니플헤임가서 몹 10마리씩잡고
```
