### ISSUE TITLE
Mob not Aggressive

### ISSUE THREAD

**Issue by cawogeek** [rathena/rathena#292]
After updating my server from 8897ad72ac70e4482176261d3a1214ff3c6d1168 to latest git i experienced all aggressive mobs are not aggressive anymore in pre-re i don't have any mob related modifications and i didnt recieve any errors, warnings and memory leaks.

Please help, thank you in advance! :dancer:

**Comment by anacondaqq** [comment]
can't confirm. 
-----------------

Check your options at monster.conf and import/battle.conf

**Comment by aleos89** [comment]
Unable to reproduce on clean pull.

**Comment by cawogeek** [comment]
got this fixed already its because of my modification. :) so i removed that and now its fixed!
