### ISSUE TITLE
Double effect ShortWeaponDamageReturn item bonus

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#2920]
* **rAthena Hash**: 
https://github.com/rathena/rathena/commit/11dc0f68526857de5daf628b46ca7be2fd282a13

* **Client Date**: 
2017

* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result: 
When using any item that has the bonus (bShortWeaponDamageReturn) the reflect comes out 2x. It will be possible to observe the reflected damage affect 2x the char.
The reflect exits 2 times.

  * Expected Result: 
The reflect should only affect 1x instead of 2x. The problem only exists with used items. The skill is normal.
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
This sounds like it's related to #2685.

**Comment by Badarosk0** [comment]
Even with the modification the problem continues for me. Double reflect.

**Comment by aleos89** [comment]
Tested on d4c1a57:
![image](https://user-images.githubusercontent.com/3521753/36567871-e96bd11e-17f5-11e8-9fbd-07602554e4eb.png)

I'm unable to reproduce this. I wore Ahura Mazda (removed all bonuses except `bonus bShortWeaponDamageReturn,100;`).

**Comment by Badarosk0** [comment]
It shows in the char only 1 reflect. But watch your HP and the chat bar. The damage is doubled.

  Received '1' of damage.
  Received '1' of damage.

**Comment by aleos89** [comment]
I just checked and it was 1 for 1 on both sides.
