### ISSUE TITLE
Hidden traps always invisible on renewal

### ISSUE THREAD

**Issue by Daegaladh** [rathena/rathena#2934]
* **rAthena Hash**: 71886193255c16cea240119a3a7dececba3271e6

* **Client Date**: 

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Currently hidden traps are visible on renewal.
  * Expected Result: Should be invisble an all maps.
  * How to Reproduce: 
  * Official Information: Hidden traps are always visible on pre-re, but always invisible on renewal. Tested on iRO Classic, iRO and Aegis 15.2.
  

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment]
Related to #892
