### ISSUE TITLE
Full Blast (GS_FULLBUSTER) delay on attack and using items

### ISSUE THREAD

**Issue by Daegaladh** [rathena/rathena#2936]
* **rAthena Hash**: 71886193255c16cea240119a3a7dececba3271e6

* **Client Date**: 

* **Server Mode**: Both

* **Description of Issue**: 
  * Result: You can't attack or use items after using the Full Blast
  * Expected Result: You should be able to do so
  * How to Reproduce: 
  * Official Information: After a lot of research and testing I found out that there was an iRO customization on Pre-renewal that did that, but I've tested on Aegis EP15.2 and 13.2, and you can attack and use items during the delay on both of them.
  

* **Modifications that may affect results**:

**Comment by Daegaladh** [comment]
Need to confirm that is the same for pre-renewal.

**Comment by aleos89** [comment]
All Aegis files I have say that the skill has a SkillGlobalPostDelay (aftercast act delay) and no SkillSinglePostDelay (cooldown). Could this just be an iRO customization?
