### ISSUE TITLE
Can't navigate to target when using some melee based skills

### ISSUE THREAD

**Issue by zackdreaver** [rathena/rathena#2937]
* **rAthena Hash**: f6e0a0a3442d6bebcab6fbbfb35bd381a7ff386c
* **Client Date**: 2015-11-04aRagexe
* **Server Mode**: Pre-Renewal
* **Description of Issue**: 
  * Result:
Can't navigate to target when using some melee based skills if more than 2 cells (3 cells if using spear) away from target.
Confirmed skills: Bash, Mammonite, Holy Cross, Bowling Bash, Spear based skils (Maybe there are more)
  * Expected Result: No issue on Renewal, so i guess it's only happens on pre-renewal
  * How to Reproduce: Target an easy monster that can help reproduce this issue, eg: Dragon egg, and use confirmed skills above from 3 cells away, can be easily reproduced through DIAGONAL movements.
  * Official Information: n/a
* **Modifications that may affect results**: n/a

**Comment by anacondaqq** [comment]
Is the https://github.com/rathena/rathena/issues/1427 issue somehow related?

**Comment by zackdreaver** [comment]
Some parts yes,
except not just diagonally and you said 2015-11-04aRagexe is fine.

**Comment by LiamKarlMitchell** [comment]
After reading comments on #1423 I wonder if it might be related/caused by skillinfoz.lua.
Just as an idea to test if possible could someone try using the renewal skillinfo but with pre-renewal compiled/configured server?

**Comment by zackdreaver** [comment]
hmm perhaps, i'll check this later.

Nice catch btw

**Comment by zackdreaver** [comment]
Alright, i've tested it with renewal skillinfolist.lub,
and it does fix this issue, I guess i have to fix the prerenewal skillinfolist.lub now.

Thanks @LiamKarlMitchell

**Comment by LiamKarlMitchell** [comment]
@zackdreaver Thanks this has been confusing me for some time, fixing it there was gonna be my next try but it got backlogged. Out of curiosity, would you be able to share how you fix it up?

Is it to do with the range in that file compared to the range in the servers skill txt? Do you have some script to auto export and fix it up?

**Comment by zackdreaver** [comment]
Like I posted before, i uses remewal skillinfolist.lub,
just reminder, it isn't compatible with prerenewal skill tree,
especially for gunsliger, and some classes that got renewal skill rebalance some years ago.

Yes, the skill range that causes this issue.
No, I don't have an automatic script that can fix this.
