### ISSUE TITLE
Select Character's Screens in New Clients (New UI) Error When Click At "X"

### ISSUE THREAD

**Issue by BrOgBr** [rathena/rathena#2939]
* **rAthena Hash**:  

* **Client Date**:  2018+ with _(New UI)_

* **Server Mode**: indifferent

* **Description of Issue**: 
  * Result: When clicking in the **"X"** at select character's screen the **client crash.**
  * Official Information: It should works as if pressing **"Esc"** at keyboard.

_Screens from the herc's users to show whats happening:_

https://s18.postimg.org/ne5rsydeh/error.png

![screenrevelesticro000 jpg f4b17e89018676f87bbf5a1a0257a798](https://user-images.githubusercontent.com/34192842/36810463-8a79b938-1ca9-11e8-8f86-b6ef1c6e2ff4.jpg)

As you can see, there looks works perfectly.

**Comment by Lemongrass3110** [comment]
Crashes on Hercules too.
This is probably a client side issue from the "Restore login window" diff.

**Comment by BrOgBr** [comment]
Thanks for the info I didn't know... :)
