### ISSUE TITLE
Malangdo Culvert Hard Mode Warp Bug

### ISSUE THREAD

**Issue by llchrisll** [rathena/rathena#2950]
* **rAthena Hash**: 
f6e0a0a3442d6bebcab6fbbfb35bd381a7ff386c

* **Client Date**: 
20170613
* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result: When you enter the Hard Mode of the Malangdo Culvert and walk a bit north, you'll get warped out, like you have stepped on the warp portal in the near.
  * Expected Result: Walking north without warp out
  * How to Reproduce: Just enter Hard Mode and walk north.

* **Modifications that may affect results**: 
npc/re/instances/MalangdoCulvert.txt - Line 1034:
`2@pump,38,100,0	duplicate(Culvert Entrance#n)	Culvert Entrance#h	45,3,3`

Solved the issue by removing the "45," at "45,3,3":
`2@pump,38,100,0	duplicate(Culvert Entrance#n)	Culvert Entrance#h	3,3`

**Comment by BrOgBr** [comment]
Confirmed, I'll make the PR, ok?
Thank you for the report <3
