### ISSUE TITLE
Slotted Temporal Boots has less ATK on refine, than unslotted

### ISSUE THREAD

**Issue by llchrisll** [rathena/rathena#2953]
* **rAthena Hash**: 
f6e0a0a3442d6bebcab6fbbfb35bd381a7ff386c
* **Client Date**: 
20170613
* **Server Mode**: 
Renewal
* **Description of Issue**: 
  * Result: When an slotted temporal boots is refined, than it has less ATK bonus than the unslotted version with the same refine.
  * Expected Result: To give exactly the same ATK bonus
  * How to Reproduce: Generate both shoes (22000 & 22006), refine them to +9 as example.

* **Modifications that may affect results**: 
db/re/item_db.txt - Line 10869:
`22006,Temporal_Str_Boots_,Temporal Boots Of Strength,4,20,,600,,25,,1,0xFFFFFFFF,56,2,64,,99,1,,{ .@r = getrefine(); bonus bMaxHP,300+(100*(.@r/3)); bonus bMaxSP,30+(10*(.@r/3)); bonus bBaseAtk,7*(.@r/3); if(readparam(bStr)>=120) bonus bBaseAtk,50; },{},{}`

Solved the issue by exchanging bonus bBaseAtk bonus bAtk like in the unslotted version:
`22006,Temporal_Str_Boots_,Temporal Boots Of Strength,4,20,,600,,25,,1,0xFFFFFFFF,56,2,64,,99,1,,{ .@r = getrefine(); bonus bMaxHP,300+(100*(.@r/3)); bonus bMaxSP,30+(10*(.@r/3)); bonus bAtk,7*(.@r/3); if(readparam(bStr)>=120) bonus bBaseAtk,50; },{},{}`

**Comment by BrOgBr** [comment]
Confirmed.
The slotted is getting Base ATK instead ATK, but at DP it's saying online ATK for two "versions".
