### ISSUE TITLE
Item missing Heart Card in Mouth ID:19306 and combo with ID:5918

### ISSUE THREAD

**Issue by AzarthMZintos** [rathena/rathena#2958]
* **rAthena Hash**: 

* **Client Date**: 

* **Server Mode**: 

* **Description of Issue**: 
  * Result: Item missing
  * Expected Result: Item exist
  * How to Reproduce: Look at DB
  * Official Information: Not official information: https://www.divine-pride.net/database/item/19306/heart-card-in-mouth combo with https://www.divine-pride.net/database/item/5918/
  

* **Modifications that may affect results**:

**Comment by BrOgBr** [comment]
I think that 19306 is from jRO.

**Comment by attackjom** [comment]
It's an item in oversea care packages box that import from JRO.
