### ISSUE TITLE
Warg Strike: Does not trigger on melee attack with daggers

### ISSUE THREAD

**Issue by raynra** [rathena/rathena#296]
Git Hash/Date: 9849945756664ffa7fd810b69ef48c98e7592a0a / Feb-16-2015
Client Date: 2013-08-07a
Description:

http://irowiki.org/wiki/Warg_Strike
"Auto-strike on all type of attack."
Tested this on Aegis. Warg Strike triggers on all attacks, including fist melee and dagger melee. However, in latest rAthena, it triggers for ranged and fist melee, but not for dagger melee.

How to reproduce:
Stab stuff with a dagger, Warg Strike will never trigger.

**Comment by reigneil** [comment]
the way it is written... confirmed.
if( pc_iswug(sd) && (sd->status.weapon == W_BOW || sd->status.weapon == W_FIST) && (skill=pc_checkskill(sd,RA_WUGSTRIKE)) > 0 && rnd()%1000 <= sstatus->luk*10/3+1 )
skill_castend_damage_id(src,bl,RA_WUGSTRIKE,skill,tick,0);

**Comment by Playtester** [comment]
So basically just remove the requirements?
