### ISSUE TITLE
Overweight Drop Issue

### ISSUE THREAD

**Issue by ghost** [rathena/rathena#2960]
* **rAthena Hash**: 40d9d5a

* **Client Date**: 20170125

* **Server Mode**: Renewal

* **Description of Issue**: Item Drops when opening at 50-90%
  * Result: Siege Potions Drop when opening at 50-90% depending on the weight.
  * Expected Result: It should not drop or you should not be able to open the Potion Box (14003)
  * How to Reproduce:
1. Use normal character not an admin or GM
2. Open Elite Siege Box (14003)
3. Notice that if you are almost 80 to 90% and opened another ESB all potions will be dropped and will return a value of 0. Please see images below:
1st Open of Box (Normal)
![image](https://user-images.githubusercontent.com/5693492/37128865-0198d8ec-22b7-11e8-8311-2cc0e2667e23.png)
2nd Open of Box (Not Normal)
![image](https://user-images.githubusercontent.com/5693492/37128878-1a41285e-22b7-11e8-958e-9d6705edc6ef.png)

If you can notice the 1st image I still have 1 box of ESB left to open. And on the 2nd image I opened it and the potions dropped to the floor and become 0 value.

  * Official Information: Don't have a source but AFAIK it should not drop or should not open. If it drops It should not be 0.
  

* **Modifications that may affect results**: None

**Comment by admkakaroto** [comment]
You updated with this? https://github.com/rathena/rathena/commit/3c41d4eeb06858ee34929bd99eaac4d44a3303ae

**Comment by ecdarreola** [comment]
@admkakaroto I always use latest emulator so yes. I have that one.

**Comment by Daegaladh** [comment]
3c41d4e is just for skills, I'll check the official behavior for this case.

**Comment by ecdarreola** [comment]
Thanks @Daegaladh

**Comment by Daegaladh** [comment]
Ok, i've tested both having too much weight and having 100 different items, and for both cases, when you try to open a box or something, it shows the message "You cannot carry more items because you are overweight." and the item is not consumed at all.

**Comment by Daegaladh** [comment]
Maybe related to map_addflooritem on getitem and some other script commands. I'll check on aegis for item drop on npcs too.

btw `clif_msg(sd, ITEM_CANT_OBTAIN_WEIGHT);` should be red

**Comment by admkakaroto** [comment]
use 'getgroupitem' that you can reproduce..
![1](https://user-images.githubusercontent.com/6227618/37559454-572051d2-2a05-11e8-913f-a9f5ca6b366e.png)

**Comment by Daegaladh** [comment]
Still cannot reproduce it, but it's a bug anyways.
Items never should drop on the floor when weight or other requirements don't met, so i'll get rid of all those damn map_flooritem on script commands and other functions.
