### ISSUE TITLE
Pets loyal cordial bonus system and more, pet db, e evolution

### ISSUE THREAD

**Issue by AzarthMZintos** [rathena/rathena#2962]
* **rAthena Hash**: 

Any

* **Client Date**: Any

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: the pet bonus only work for loyal, no option for cordial and bonus missing at those pets db
  * Expected Result: Pet Loyal and Cordial Bonuses db and working system(besides some have awkaward and neutral bonus) pet evolution system
  * How to Reproduce: Using pets and look at db
  * Official Information:https://www.divine-pride.net/database/item/9069/mastering-egg (not official info) mastering is evolution pet and have 4 intimacy diferente lvl bonus I look at the forum for info and only found this: https://rathena.org/board/topic/105838-renewal-pet-bonus-implementation/?tab=comments#comment-342885
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Can you please provide the hash you're using.

**Comment by AzarthMZintos** [comment]
I use Github desktop i have no ideia how to get that info, i just update if that tell you something, if you know how to see let me know

**Comment by aleos89** [comment]
The new pet evolution system has already been started on. I'll just adjust some labels for now.

**Comment by OptimusM** [comment]
Any updates on this?

**Comment by aleos89** [comment]
Implemented in ac558d7.
