### ISSUE TITLE
About KG_KAGEMUSYA skill problem

### ISSUE THREAD

**Issue by redlightliu** [rathena/rathena#2968]
* **rAthena Hash**: bc02c4e

* **Client Date**: 20160203

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: When I use skill KG_KAGEMUSYA Lv5 to my charater.I get skill TF_DOUBLE Lv2.
  * Expected Result: This skill should be get TF_DOUBLE Lv2 -> Lv4 -> Lv6 -> Lv8 -> Lv10 by KG_KAGEMUSYA Lv1 -> Lv2 -> Lv3 -> Lv4 -> Lv5.
  * How to Reproduce: Use skill KG_KAGEMUSYA in you self.

  
http://www.inven.co.kr/board/ro/1939/17871
https://www.youtube.com/watch?time_continue=28&v=LKcXm_p8rCc

**Comment by admkakaroto** [comment]
Where did you read that the skill level duble goes up according to the skill level KAGEMUSYA?

```
	[SKID.KG_KAGEMUSYA] = {
		"Shadow Warrior",
		"Max Level: 5",
		"^CC3399Requirement: Empty Shadow 3^000000",
		"Description: ^777777Imbues Double Attack skill",
		"to a target for a period of time.",
		"Consumes 1 SP per second while active.",
		"Consumes 1 Shadow Orb.^000000",
		"[LV 1]: ^777777Duration 60 seconds^000000",
		"[LV 2]: ^777777Duration 90 seconds^000000",
		"[LV 3]: ^777777Duration 120 seconds^000000",
		"[LV 4]: ^777777Duration 150 seconds^000000",
		"[LV 5]: ^777777Duration 180 seconds^000000"
},
```

https://irowiki.org/wiki/Shadow_Warrior

**Comment by redlightliu** [comment]
http://www.inven.co.kr/board/ro/1939/17871

**Comment by redlightliu** [comment]
And this film show the skill RA_FEARBREEZE and TF_DOUBLE can use together.
But rAthena only trigger the skill TF_DOUBLE. It will not trigger RA_FEARBREEZE.
