### ISSUE TITLE
2nd Language fail

### ISSUE THREAD

**Issue by is94ns13** [rathena/rathena#297]
Hello
i just added 2nd language its Russian and its not working 100%
if you chat to another player it works it shows in russian but when you @langtype rus it shows some weird language but nut russian
and when i open map_msg_rus.conf its in weird language too. Is that means my server not supporting russian language?

**Comment by anacondaqq** [comment]
map_msg_rus.conf in cp1251, non in UTF-8.
Use Notepad++

    <servicetype>russia</servicetype>
    <servertype>sakray</servertype>
     <langtype>14</langtype>

It's not a problem of rAthena.
So close it.

**Comment by is94ns13** [comment]
i did changed all that
<servicetype>russia</servicetype>
<servertype>sakray</servertype>
 <langtype>14</langtype>
but if i set to  <langtype>14</langtype> i cant even chat in russian and when its set to  <langtype>10</langtype>chat works just great!
can you tell me where is next place too look?

**Comment by anacondaqq** [comment]
dininput.dll and dininput.ini -> remove it from the game folder.
and redownload map_msg_rus.conf from rathena and replace it your own.

If you will do it, you will have correct language at your server

**Comment by is94ns13** [comment]
i do not have those files in my game folder i did downloaded new map_msg_rus.config
no changes 
may be its because of my computer it may not support russian or something but chat works in russian no problems

**Comment by anacondaqq** [comment]
i don't know. For me any language (and russian) works fine. I can show proofs if it need.

**Comment by aleos89** [comment]
As @anacondaqq said, this is client side. You need to make sure you have the correct language package installed on your computer. :)
