### ISSUE TITLE
Luitie Kafra Missing

### ISSUE THREAD

**Issue by AzarthMZintos** [rathena/rathena#2976]
* **rAthena Hash**: Last Update

* **Client Date**: 2017-05-17aRagexeRE

* **Server Mode**: Renewal

* **Description of Issue**: 
https://ibb.co/mYKrf7
  * Result: The npc have icon where is suposte to be and the icon at the mini map, but its not there
  * Expected Result: Kafra should be at Lutie spot
  * How to Reproduce: Go to Lutie see the icon and the mini map
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by zackdreaver** [comment]
Not only this NPC,
other Renewal NPC locations and availability are need to be updated and adjusted according
kRO. Towninfo.lub, signboardlist.lub and navi_npc_krpri.lub can be used as reference.
This PR https://github.com/rathena/rathena/pull/2977 is using those files as reference.

**Comment by Akkarinage** [comment]
Actually, I can find no information anywhere to suggest that there **should** be a Kafra in Lutie.

Gravity is notorious for only doing half a job, so it's possible that they just haven't removed the lines in the client files.

I'm happy for us to add one if you can grab me a replay/video/screenshot from kRO's servers though.

**Comment by Lemongrass3110** [comment]
Confirmed on kRO:
![grafik](https://user-images.githubusercontent.com/3517879/44254820-4c642300-a204-11e8-82fe-0d4293ee21a2.png)
