### ISSUE TITLE
@reloadnpc

### ISSUE THREAD

**Issue by iubantot** [rathena/rathena#2979]
* **rAthena Hash**: 

 39ba3d6

* **Client Date**: 

2017-06-14

* **Server Mode**: 

Renewal

* **Description of Issue**: 
  * Result:  `@reloadnpc` , removes all the npc while inside the instance.
  * Expected Result:  it would be better if it will  function like `@reloadscript`, when you use `@reloadscript` it will restart your instance from the beginning.
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**: 
  
   none

**Comment by aleos89** [comment]
`@reloadnpc` is an alias to `@reloadnpcfile`. This is working as intended.

**Comment by iubantot** [comment]
does it trigger OnInit: too?

**Comment by sader1992** [comment]
nope , `OnInit:` does not trigger by reloading a script

if you the variables you have inside the `OnInit:` not change inside the script you can put above it `OnWhisperGlobal:` and than when using `@reloadnpc` it will run

**Comment by aleos89** [comment]
OnInit is triggered through this atcommand. OnInstanceInit is not triggered because instances are treated differently.
