### ISSUE TITLE
Homunculus Aspd

### ISSUE THREAD

**Issue by RagnarokNova** [rathena/rathena#298]
All genetic homunculi achieve maximum ASPD with little to no effort at levels 115~120. 
I imagine the formula is a bit off?

**Comment by reigneil** [comment]
i've also notice this even the damage of homunculus is insane. Confirmed there is bug going on here... using git c92915b6cd and client 2014-06-13aRagexe

**Comment by reigneil** [comment]
added Screenshot.
![screenrathena000](https://cloud.githubusercontent.com/assets/9740000/6401335/a013365a-be3a-11e4-870d-eec96796c6d8.jpg)

**Comment by MrAntares** [comment]
Confirmed here as well.
I blame https://github.com/rathena/rathena/commit/083cf5d9

I noticed that magic attack is fine, only physical attack is off the scale.

**Comment by aleos89** [comment]
Confirmed, looking into it.
