### ISSUE TITLE
Missing NPCs in Izlude channel maps

### ISSUE THREAD

**Issue by zackdreaver** [rathena/rathena#2987]
* **rAthena Hash**: a16fe436e34c52a981c6d1c0898ac605ae5af89d

* **Client Date**: n/a

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Missing NPC in Izlude channel maps: Vigilante Penne and Con-Cliina Crewman
  * Expected Result: These NPCs should be there
  * How to Reproduce: Change map to izlude channel 2~5
  * Official Information: n/a
  

* **Modifications that may affect results**: n/a

**Comment by BrOgBr** [comment]
I would like to do the commits separately but it ended up staying together.
I'm still a noob at GitHub. :'(

**Comment by Atemo** [comment]
They duplicated `Con-Cliina Crewman` and they didn't duplicate `Vigilante Penne` on iRO. Need to check on kRO.
