### ISSUE TITLE
Warning: WFIFOSET 0x09f9

### ISSUE THREAD

**Issue by ecdarreola** [rathena/rathena#2989]
* **rAthena Hash**: a16fe43

* **Client Date**: 20170125

* **Server Mode**: Renewal

* **Description of Issue**: [Warning]: WFIFOSET: Attempted to send zero-length packet, most likely 0x09f9 (please report this).
![image](https://user-images.githubusercontent.com/5693492/37497076-14ef0fd4-28f1-11e8-867f-c82f65e4c9f9.png)

  * Result: A warning in console.
  * Expected Result: Should have no warning.
  * How to Reproduce: The tricky part here is that I don't know how to reproduce it. It just showed.
  * Official Information: N/A
  

* **Modifications that may affect results**: Gepard

**Comment by Lemongrass3110** [comment]
I think you probably had a merge issue.
Check if your clif_packetdb is correctly set to 143.
