### ISSUE TITLE
TXT item db parsing error

### ISSUE THREAD

**Issue by Darkelfen** [rathena/rathena#2991]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/d7f226a66bcdee7865702451da3e692de2685cd7

* **Client Date**:  Unrelated

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result:  Every single item of item_db and import/item_db is reported as having mismatched curly braces, therefore they aren't loaded.
  * Expected Result:  Only items with mismatched curly braces should be reported and not loaded.
  * How to Reproduce:  Not sure how since I've used a clean latest rA ( https://github.com/rathena/rathena/commit/9bbb4cb5b92f39422b152a4221c0a70f815f2fe1 ) but manually reverting https://github.com/rathena/rathena/commit/d7f226a66bcdee7865702451da3e692de2685cd7 allows the item_db to be properly loaded, albeit mismatched curly braces aren't properly reported.
  * Official Information: None.
  

* **Modifications that may affect results**: None

**Comment by Lemongrass3110** [comment]
Which operation system and version are you using?
Which compiler and version did you use?

Did you see #2964? I think it is most likely a duplicate of it.

**Comment by Darkelfen** [comment]
Yes duplicate indeed. Sorry.

Centos ver: centos-release-6-9.el6.12.3.x86_64
gcc ver: gcc (GCC) 7.2.1 20170829 (Red Hat 7.2.1-1)
