### ISSUE TITLE
Cross Impact Spam

### ISSUE THREAD

**Issue by iubantot** [rathena/rathena#2994]
* **rAthena Hash**: 

db8234b

* **Client Date**: 

20170614

* **Server Mode**: 

Renewal

* **Description of Issue**: Cross Impact can be casted/spam 2x when your ASPD is low but when you get your ASPD higher you can only cast it once.
  * Result: 
  * Expected Result:  It can be spammed/casted 2x.
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**: 
  
   none

**Comment by secretdataz** [comment]
I believe Cross Impact is only ASPD-gated in a certain way by the client. This behavior is also present in Aegis.

**Comment by iubantot** [comment]
so should i change my client?
