### ISSUE TITLE
Map-server crash in @showmobs

### ISSUE THREAD

**Issue by Valacobino** [rathena/rathena#2996]
* **rAthena Hash**: db8234b9eec2323eccf2da4703a1751058e11de1

* **Client Date**: -

* **Server Mode**: Both Renewal and Pre-Renewal

* **Description of Issue**: If someone use the command showmobs with a nonexistent monster name the map-server will crash
  * Result: map-server crash
  * Expected Result: display a message that the mob does not exists
  * How to Reproduce: `@showmobs zzzz`
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment]
Fixed in bde3aeb
