### ISSUE TITLE
unloadnpc Command Script

### ISSUE THREAD

**Issue by sader1992** [rathena/rathena#2999]
* **rAthena Hash**: a16fe436e34c52a981c6d1c0898ac605ae5af89d

* **Client Date**: 2015-11-04

* **Server Mode**: both

* **Description of Issue**: 
  * Result: [Error]: Server received crash signal! Attempting to save all online characters!
  * Expected Result: no crash
  * How to Reproduce: 
```
prontera,156,186,3	script	test	701,{
	unloadnpc strnpcinfo(3);
	end;
}
```

**Comment by secretdataz** [comment]
Addressed in 41ea153.
