### ISSUE TITLE
Stat Biscuits effects

### ISSUE THREAD

**Issue by iubantot** [rathena/rathena#3004]
* **rAthena Hash**: 

db8234b

* **Client Date**: 

20170614

* **Server Mode**: 

Renewal

* **Description of Issue**: 
  * Result:  Bar Cookie or biscuits SC_STRFOOD effects are gone upon death
  * Expected Result:  the effect should remain
  * How to Reproduce:  they should be included on type = 0 that should remain after death
  * Official Information:
  

* **Modifications that may affect results**: 
  
   none

**Comment by talesofragnarok** [comment]
confirm please update

**Comment by aleos89** [comment]
These should probably be using the cash version of the food since the normal foods don't stick after death. Need to confirm on kRO.
