### ISSUE TITLE
Issue of Last Git -> percentheal of yggdrasil seed 

### ISSUE THREAD

**Issue by tmav94** [rathena/rathena#301]
We got a possible problem with the last git, in this case, with percentheal values of yggdrasil seed.

The problem is the 608 yggdrasilseed give cure based on user current hp, this means that if you have 10HP you will receive a cure with value 5 because 50% of 10 is 5 *.* 

this is right but, the ygg drasil berry, that uses the same function, (100%) cure all bar without uses user current hp as reference...

How can i proceed?

item_db.txt
607,Yggdrasilberry,Yggdrasil Berry,0,5000,,300,,,,,0xFFFFFFFF,63,2,,,,,,{ percentheal 100,100; },{},{}
608,Seed_Of_Yggdrasil,Yggdrasil Seed,0,5000,,300,,,,,0xFFFFFFFF,63,2,,,,,,{ percentheal 50,50; },{},{}

**Comment by nanakiwurtz** [comment]
I think it uses percentage of your Max HP instead of your current HP?

**Comment by tmav94** [comment]
I think that original Seed cure 1/2 of your HP, but this is uses the percentage (50%) of your current Max HP.

**Comment by nanakiwurtz** [comment]
Source: iRO
Item ID: 608
Item Name: Yggdrasil Seed
Description:
HP Recovery Item
SP Recovery Item
Seed from the Yggdrasil tree which holds our world together. It has a weird, energizing pungence. 
Restores one **half of maximum HP and SP**.

**Comment by aleos89** [comment]
I've noticed this to be an issue with a few skills as well. The issue is here:
```objective-c
	if (hp_rate > 99)
		hp = status->hp;
	else if (hp_rate > 0)
		hp = apply_rate(status->hp, hp_rate);
	else if (hp_rate < -99)
		hp = status->max_hp;
	else if (hp_rate < 0)
		hp = (apply_rate(status->hp, -hp_rate));
	if (hp_rate && !hp)
		hp = 1;

	if (flag == 2 && hp >= status->hp)
		hp = status->hp-1; // Must not kill target.

	if (sp_rate > 99)
		sp = status->sp;
	else if (sp_rate > 0)
		sp = apply_rate(status->sp, sp_rate);
	else if (sp_rate < -99)
		sp = status->max_sp;
	else if (sp_rate < 0)
		sp = (apply_rate(status->sp, -sp_rate));
	if (sp_rate && !sp)
		sp = 1;
```
Should be:
```objective-c
	if (hp_rate > 99)
		hp = status->hp;
	else if (hp_rate > 0)
		hp = apply_rate(status->hp, hp_rate);
	else if (hp_rate < -99)
		hp = status->max_hp;
	else if (hp_rate < 0)
		hp = (apply_rate(status->max_hp, -hp_rate));
	if (hp_rate && !hp)
		hp = 1;

	if (flag == 2 && hp >= status->hp)
		hp = status->hp-1; // Must not kill target.

	if (sp_rate > 99)
		sp = status->sp;
	else if (sp_rate > 0)
		sp = apply_rate(status->sp, sp_rate);
	else if (sp_rate < -99)
		sp = status->max_sp;
	else if (sp_rate < 0)
		sp = (apply_rate(status->max_sp, -sp_rate));
	if (sp_rate && !sp)
		sp = 1;
```
