### ISSUE TITLE
Throw Huuma Shuriken damage split

### ISSUE THREAD

**Issue by zackdreaver** [rathena/rathena#3016]
* **rAthena Hash**: 40d9d5ab7399c75b21e2038e728044620cc4d42d

* **Client Date**: n/a

* **Server Mode**: Renewal (Haven't tested prerenewal)

* **Description of Issue**: 
  * Result: Throw Huuma Shuriken deals full damage to all targets within AoE
  * Expected Result: Throw Huuma Shuriken deals split damage to all targets within AoE
  * How to Reproduce: Use the skill on pack of mobs
  * Official Information: kRO skilldescript, http://ro.doddlercon.com/guides/ninja.html

* **Modifications that may affect results**: n/a

**Comment by Playtester** [comment]
The guide from Doddler is for pre-renewal where the damage is indeed split. Not sure about renewal, pretty sure there were a lot of changes to it.

**Comment by zackdreaver** [comment]
I read this
http://www.inven.co.kr/board/ro/1950/1297?iskin=ro
a kRO player says, this skill's damage split has been removed in renewal.
I guess this issue is invalid, i'll close this now.
