### ISSUE TITLE
Rebellion Class - Skill

### ISSUE THREAD

**Issue by kbacoto** [rathena/rathena#302]
Rebellion Class:
I've noticed that whenever I use either "Banishing Buster" or "Shatter Storm" - my character doesn't move at all. It casts the skills and hurt other characters/mobs but my character stand still when shooting. It doesn't make a single action.

Any solution for this?
Thank you.

**Comment by cydh** [comment]
Client? Re or Pre? rev?

Just tested, RE, 2013-08-07. Nothing wrong (even from long time ago)

**Comment by kbacoto** [comment]
Client: 2013-08-07
Pre-Renewal

**Comment by joelolopez** [comment]
@cydh sir maybe his trying to say that rebellion isnt showing any skill animation while casting a skill, like changing pose and some specialeffects

**Comment by cydh** [comment]
then it's client files fault :P
use that client version is not enough without updated files.

I'll close this case
