### ISSUE TITLE
Baby Dragon Hat [1]

### ISSUE THREAD

**Issue by MrAntares** [rathena/rathena#3020]
The item has wrong script and the double attack part is not working at all:

Current script:
bonus bDex,2; skill "TF_DOUBLE",max(getskilllv("TF_DOUBLE"),5);

Correct script:
bonus bDex,2; skill "TF_DOUBLE",5; bonus bDoubleRate,25;

**Comment by Daegaladh** [comment]
Right, besides that max(getskilllv("TF_DOUBLE") doesn't make sense, because if you have this skill at a higher level, will already be triggered at that level.
Btw this item is commented out from the pre-re db for no reason.

**Comment by BrOgBr** [comment]
I think that according to the DP _(kRO)_, the correct script is:

`bonus bDex,2; skill "TF_DOUBLE",max(5,getskilllv("TF_DOUBLE"));`

> Enable Double Attack level 5, if a higher level of this skill is learned then that level will be enable.

But how Daegaladh said, it doesn't make sense.

**Comment by Mystou** [comment]
@BrOgBr 
What's the diffrence between 
max(getskilllv("TF_DOUBLE"),5)
and
max(5,getskilllv("TF_DOUBLE"))
?

For me, the command is the same. It will always get the highest value between the two.

*max(<number or array>{,<number or array>,...})
Returns the smallest (or biggest) from the set of given parameters.
.@maximum = max( 0, 5, 10, 4 ); // .@maximum will be equal to 10

So the current script is correct, no?

**Comment by BrOgBr** [comment]
I really don't know the difference, but I did so and it's working perfectly here.
I always do it that way.

**Comment by Daegaladh** [comment]
skill "TF_DOUBLE" gives you the skill in your skill tree, but does nothing, bDoubleRate is what really does the effect (yeah we should fix that, has been like this for years D:)
Also, as I said, there's no point on using max, since if you already have the skill at a higher level, it will do the higher effect.

**Comment by Mystou** [comment]
Dumb question : so if I have the skill at level 7, the "skill "TF_DOUBLE",5" in the item will change the skill to level 5 or keep it to level 7 (in my skill tree) ?

**Comment by Daegaladh** [comment]
I've already answered that question in my previous comment: "if you already have the skill at a higher level, it will do the higher effect" so yeah, it will keep the level 7 one.
But now I've realized i don't know how it would work, 7 for daggers only and 5 for the rest? 7 for all weapons? Need to test this on official servers.

**Comment by BrOgBr** [comment]
@Daegaladh it should be so then:

`bonus bDex,2; skill "TF_DOUBLE",max(5,getskilllv("TF_DOUBLE")); bonus bDoubleRate,(5*getskilllv("TF_DOUBLE"));`

I tried with other weapons and its working perfectly now.
