### ISSUE TITLE
[ Suggestion ] getinventorylist should return random option

### ISSUE THREAD

**Issue by Yuchinin** [rathena/rathena#3021]
* **rAthena Hash**: -

* **Client Date**: -

* **Server Mode**: -

* **Description of Issue**: 
  * Result: This command lack of the ability to return random option which is introduced for quite a long time.
  * Expected Result: Expect it return the random option value.
  * How to Reproduce: -
  * Official Information:-
  

* **Modifications that may affect results**:

**Comment by Daegaladh** [comment]
I don't get it, this command just gets your whole inventory data into several arrays, what do you mean by a random option?

**Comment by vstumpf** [comment]
He wants the command to make arrays for random options as well.

**Comment by Daegaladh** [comment]
Oh I didn't remember that system exists lol, never used it.

**Comment by Yuchinin** [comment]
Suggestion code if need (dizzy)
```
for (k = 0; k < MAX_SLOTS+1; k++)
			{
				sprintf(card_var, "@inventorylist_random_id%d",k+1);
				pc_setreg(sd,reference_uid(add_str(card_var), j),sd->inventory.u.items_inventory[i].option[k].id);
				sprintf(card_var, "@inventorylist_random_val%d",k+1);
				pc_setreg(sd,reference_uid(add_str(card_var), j),sd->inventory.u.items_inventory[i].option[k].value);
				sprintf(card_var, "@inventorylist_randomi_par%d",k+1);
				pc_setreg(sd,reference_uid(add_str(card_var), j),sd->inventory.u.items_inventory[i].option[k].param);
			}
```

**Comment by sader1992** [comment]
@Yuchinin `for (k = 0; k < MAX_SLOTS+1; k++)` should be `for (k = 0; k < MAX_ITEM_RDM_OPT; k++)` 

also nice i was trying to do it but didn't realize should be .id >> so it return int
with .id i think it work but i did not test it xD

```
for (k = 0; k < MAX_ITEM_RDM_OPT; k++)
			{
				sprintf(option_var, "@inventorylist_option%d", k + 1);
				pc_setreg(sd, reference_uid(add_str(option_var), j), sd->inventory.u.items_inventory[i].option[k].id);
			}
```

**Comment by Yuchinin** [comment]
@sader1992 Thanks for pointing out but my code are just suggestion haha, too lazy to search for that constant but it won't hurt since I think card and random option number won't get change XD

**Comment by mrjnumber1** [comment]
been using this for a while and it worked fine. looks about 1:1 to saber1992's
```

			for (k = 0; k < MAX_ITEM_RDM_OPT; k++)
			{
				sprintf(tmp_var, "@inventorylist_optid%d",k+1);
				pc_setreg(sd,reference_uid(add_str(tmp_var), j),sd->inventory.u.items_inventory[i].option[k].id);
				sprintf(tmp_var, "@inventorylist_optval%d",k+1);
				pc_setreg(sd,reference_uid(add_str(tmp_var), j),sd->inventory.u.items_inventory[i].option[k].value);
				sprintf(tmp_var, "@inventorylist_optpar%d",k+1);
				pc_setreg(sd,reference_uid(add_str(tmp_var), j),sd->inventory.u.items_inventory[i].option[k].param);
			}
```
