### ISSUE TITLE
Rune Knight - ASPD

### ISSUE THREAD

**Issue by Nathalino** [rathena/rathena#303]
I am using the version of the emulator: r12921 and hexed: 2012-04-10aRagexeRE_J.
Was checking the attack speed value (ASPD) based on iROwiki site (http://calc.irowiki.org/)
and the values do not match. Attached images! Thank you for your attention.

![en2](https://cloud.githubusercontent.com/assets/8324590/6320870/ff0dc668-bac8-11e4-9c8a-216fa6000b6c.jpg)
![en3](https://cloud.githubusercontent.com/assets/8324590/6320903/95ee1592-bac9-11e4-9099-dc83f4e70b95.jpg)

Note: standard attack speed Formula, was not changed.

**Comment by Playtester** [comment]
Is rune knight the only class that has wrong ASPD (which would indicate wrong base ASPD values for said class) or does this affect all classes?

**Comment by MrAntares** [comment]
__IROWIKI HAS COMPLETELY DIFFERENT ASPD CALCULATION, DON'T COMPARE TO IT. WE USE KRO ASPD.__

Sorry, but this is a recurring thing, and we must advertise the above on the highest possible volume.

**Comment by Nathalino** [comment]
I apologize for what happened and I thank you for your attention.

**Comment by arthurpessoa** [comment]
If you really want to use the iRO aspd, just disable the renewal ASPD formula, the classic formula is very close to iRO Renewal ;)

**Comment by Nathalino** [comment]
Thanks for the tip arthurpessoa.

**Comment by Nathalino** [comment]
Can I See! Thanks for the clarification MrAntares.
