### ISSUE TITLE
missing bSkillDelayrate & NearAtkRate

### ISSUE THREAD

**Issue by iubantot** [rathena/rathena#3031]
* **rAthena Hash**: 

662aa4f

* **Client Date**: 

2017 06 14

* **Server Mode**: 

 Renewal

* **Description of Issue**: 
  * Result:  Missing item bonus for bSkillDelayrate or bDelayrate for certain skills bSkillDelayrate,k,n; theres an item that needs this item bonus Imperial Feather & Imperial Gloves combo effect from iRO.

  * Expected Result: 
  * How to Reproduce: 
  * Official Information:[Imperial Glove]( https://www.divine-pride.net/database/item/28551) & [Imperial Feather](https://www.divine-pride.net/database/item/18823/imperial-feather)
  

* **Modifications that may affect results**:

**Comment by iubantot** [comment]
![image](https://user-images.githubusercontent.com/13269331/38232229-bde35e5a-3748-11e8-869c-72d44ef36347.png)

this is snipped from the iteminfo of iRO

**Comment by Lemongrass3110** [comment]
Could you please specify the item id next time?
Also please link to divine-pride for item information as long as it is there.
As you can see [here](https://www.divine-pride.net/database/item/18823/imperial-feather). You need to switch the server in the top right to "English / iRO" for the iRO description.

**Comment by iubantot** [comment]
My apologies...
