### ISSUE TITLE
Attendance System

### ISSUE THREAD

**Issue by xEasycore** [rathena/rathena#3035]
* **rAthena Hash**: 

* **Client Date**: 2018-03-07bRagexeRE

* **Server Mode**: Renewal

* **Description of Issue**: 
Gravity has released a new UI interface for a new feature: Attendance System (like a Daily Reward)

![image](https://user-images.githubusercontent.com/15817480/38394803-4504f04c-3906-11e8-8c24-cc15fed860f0.png)

This feature is available for 2018-03-07 client or above (2018-04-04)

There's a pull request for the implementation of this system in Hercules:
https://github.com/HerculesWS/Hercules/pull/1990

**Comment by Lemongrass3110** [comment]
Woopsie...
Forgot to reference it from the commit.

Implemented in a5588dd
