### ISSUE TITLE
Lauda + Angeling Card

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#3036]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/ae69e506263f9b183c945f49b1d88c5fc2b73a6a
* **Client Date**: 2017-06-07
* **Server Mode**: RE
* **Description of Issue**: If the player has the equipped Angeling card, he does not receive the 'Lauda Ramus and Lauda Agnus' abilities effect.
  * Expected Result: Player receives the effect even though the cards are equipped.
  * How to Reproduce: Just place an angeling card on any outfit and cast the ability on yourself.

**Comment by aleos89** [comment]
Quick assumption would be since the card is giving a Holy effect, those skills must have the Holy element applied to them. Need to confirm on kRO, unless you have sources on kRO.

**Comment by admkakaroto** [comment]
unfortunately I have no concrete information from the KRO ... but I'll try to get it.

**Comment by aleos89** [comment]
```
SetSkill AB_LAUDAAGNUS //라우다아그누스-아크비숍
OnInit:
	SkillMaxLv 4
	SkillProperty PROPERTY_Saint //성속성을 부여한다.

SetSkill AB_LAUDARAMUS //라우다라무스-아크비숍
OnInit:
	SkillMaxLv 4
	SkillProperty PROPERTY_Saint //성속성을 부여한다.
```
According to Aegis data, both are Holy element.
