### ISSUE TITLE
Stylist Shop (Stylist UI)

### ISSUE THREAD

**Issue by BrOgBr** [rathena/rathena#3037]
* **rAthena Hash**: 

* **Client Date**: 2015+

* **Server Mode**: Renewal

* **Description of Issue**: 
 This is a very nice Ui for the Stylist _(Stylist Shop)_.

<img width="298" alt="zzz" src="https://user-images.githubusercontent.com/34192842/38410369-c21dce06-395a-11e8-8101-6a28eefcd5f5.png">

More Info:
https://forums.warpportal.com/index.php?/topic/191935-kro-styling-shop-renovation-jan-27th-2016/

Preview:
https://youtu.be/kbCa5qefWMg

It was released about six days ago in herc by the Asheraf at this PR:
HerculesWS/Hercules#2004

**Comment by Angelic234** [comment]
[https://github.com/idathena/trunk/commit/4bdd552e65a710d0347247aa7c6affe76fc1159a](https://github.com/idathena/trunk/commit/4bdd552e65a710d0347247aa7c6affe76fc1159a)

**Comment by Haikenz** [comment]
Thanks @Angelic234

**Comment by RagnaWay** [comment]
Any news ???

**Comment by dimasshotta** [comment]
this is how i fix in rathena. Please check if it has something wrong:

static void pc_readdb_stylist_libconfig_sub(struct config_setting_t *it, int16 count, const char *source) {
	int i32, Id = 0, zeny = 0, itemID = 0, boxItemID = 0;
	bool allow_doram = false;
	const char *name;
	int64 type;
	int16 idx;	

	nullpo_retv(it);
	nullpo_retv(source);

	if (!config_setting_lookup_string(it, "Type", &name)) {
		ShowWarning("pc_readdb_stylist_libconfig_sub: Missing Type in \"%s\", entry #%d.\n", source, count);
		return;
	}
	if (!script_get_constant(name, &type)) {
		ShowWarning("pc_readdb_stylist_libconfig_sub: Invalid Type '%s' in \"%s\", entry #%d.\n", name, source, count);
		return;
	}
	if (type < 0 || type >= MAX_STYLIST_TYPE) {
		ShowWarning("pc_readdb_stylist_libconfig_sub: Out of range Type '%s' in \"%s\", entry #%d.\n", name, source, count);
		return;
	}
	if (!config_setting_lookup_int(it, "Id", &i32) || i32 < 0) {
		ShowWarning("pc_readdb_stylist_libconfig_sub: Missing or invalid Id %d in \"%s\", entry #%d.\n", i32, source, count);
		return;
	}
	Id = i32;
	if (config_setting_lookup_int(it, "Index", &i32))
		idx = i32;
	else
		idx = Id;
	if (config_setting_lookup_int(it, "Zeny", &i32))
		zeny = i32;
	if (config_setting_lookup_int(it, "ItemID", &i32))
		itemID = i32;
	if (config_setting_lookup_int(it, "BoxItemID", &i32))
		boxItemID = i32;
	if (config_setting_lookup_bool(it, "AllowDoram", &i32))
		allow_doram = (i32 != 0);
	if (!stylist_datas[type])
		CREATE(stylist_datas[type], struct s_stylist_data, 1);
	else
		RECREATE(stylist_datas[type], struct s_stylist_data, stylist_data_count + 1);
	stylist_datas[type][idx - 1].id = Id;
	stylist_datas[type][idx - 1].zeny = zeny;
	stylist_datas[type][idx - 1].itemid = itemID;
	stylist_datas[type][idx - 1].boxid = boxItemID;
	stylist_datas[type][idx - 1].allow_doram = allow_doram;
	stylist_data_count++;
}

**Comment by dimasshotta** [comment]
and this is for the stylist.conf:

//=========================================================================
//= Stylist Database
//=========================================================================

/**************************************************************************
 ************* Entry structure ********************************************
 **************************************************************************
{
	Type: (string)             // Type of the Id
	Id: (int)                  // Id of the Style
	Index: (int)               // (optional, defaults to 0) Index for the Type
	Zeny: (int)                // (optional, defaults to 0) Zeny Requirement to change the look
	ItemID: (int)              // (optional, defaults to 0) ItemID Requirement to change the look
	BoxItemID: (int)           // (optional, deafults to 0) BoxItemID Requirement to change the look
	AllowDoram: (boolean)      // (optional, defaults to false) Check if Doram is allowed to change the look
},
**************************************************************************/

stylist_db: (
{
	Type: "LOOK_HAIR_COLOR"
	Id: 1
	Zeny: 100000
	AllowDoram: true
},
{
	Type: "LOOK_HAIR_COLOR"
	Id: 2
	Zeny: 100000
	AllowDoram: true
},
{
	Type: "LOOK_HAIR_COLOR"
	Id: 3
	Zeny: 100000
	AllowDoram: true
},
{
	Type: "LOOK_HAIR_COLOR"
	Id: 4
	Zeny: 100000
	AllowDoram: true
},
{
	Type: "LOOK_HAIR_COLOR"
	Id: 5
	Zeny: 100000
	AllowDoram: true
},
{
	Type: "LOOK_HAIR_COLOR"
	Id: 6
	Zeny: 100000
	AllowDoram: true
},
{
	Type: "LOOK_HAIR_COLOR"
	Id: 7
	Zeny: 100000
	AllowDoram: true
},
{
	Type: "LOOK_HAIR_COLOR"
	Id: 8
	Zeny: 100000
	AllowDoram: true
},
{
	Type: "LOOK_HAIR"
	Id: 1
	Zeny: 100000
	AllowDoram: true
},
{
	Type: "LOOK_HAIR"
	Id: 2
	Zeny: 100000
	AllowDoram: true
},
{
	Type: "LOOK_HAIR"
	Id: 3
	Zeny: 100000
	AllowDoram: true
},
{
	Type: "LOOK_HAIR"
	Id: 4
	Zeny: 100000
	AllowDoram: true
},
{
	Type: "LOOK_HAIR"
	Id: 5
	Zeny: 100000
	AllowDoram: true
},
{
	Type: "LOOK_HAIR"
	Id: 6
	Zeny: 100000
	AllowDoram: true
},
{
	Type: "LOOK_HAIR"
	Id: 7
	Zeny: 100000
},
{
	Type: "LOOK_HAIR"
	Id: 8
	Zeny: 100000
},
{
	Type: "LOOK_HAIR"
	Id: 9
	Zeny: 100000
},
{
	Type: "LOOK_HAIR"
	Id: 10
	Zeny: 100000
},
{
	Type: "LOOK_HAIR"
	Id: 11
	Zeny: 100000
},
{
	Type: "LOOK_HAIR"
	Id: 12
	Zeny: 100000
},
{
	Type: "LOOK_HAIR"
	Id: 13
	Zeny: 100000
},
{
	Type: "LOOK_HAIR"
	Id: 14
	Zeny: 100000
},
{
	Type: "LOOK_HAIR"
	Id: 15
	Zeny: 100000
},
{
	Type: "LOOK_HAIR"
	Id: 16
	Zeny: 100000
},
{
	Type: "LOOK_HAIR"
	Id: 17
	Zeny: 100000
},
{
	Type: "LOOK_HAIR"
	Id: 18
	Zeny: 100000
},
{
	Type: "LOOK_HAIR"
	Id: 19
	Zeny: 100000
},
{
	Type: "LOOK_HAIR"
	Id: 20
	Zeny: 100000
},
{
	Type: "LOOK_HAIR"
	Id: 21
	Zeny: 100000
},
{
	Type: "LOOK_HAIR"
	Id: 22
	Zeny: 100000
},
{
	Type: "LOOK_HAIR"
	Id: 23
	Zeny: 100000
},
{
	Type: "LOOK_HAIR"
	Id: 24
	ItemID: 7622
	BoxItemID: 16843
},
{
	Type: "LOOK_HAIR"
	Id: 25
	ItemID: 7622
	BoxItemID: 16843
},
{
	Type: "LOOK_HAIR"
	Id: 26
	ItemID: 7622
	BoxItemID: 16843
},
{
	Type: "LOOK_HAIR"
	Id: 27
	ItemID: 7622
	BoxItemID: 16843
},
{
	Type: "LOOK_HAIR"
	Id: 28
	ItemID: 6707
	BoxItemID: 17336
},
{
	Type: "LOOK_HAIR"
	Id: 29
	ItemID: 6707
	BoxItemID: 17336
},
{
	Type: "LOOK_HAIR"
	Id: 30
	ItemID: 25736
	BoxItemID: 25736
},
{
	Type: "LOOK_HAIR"
	Id: 31
	ItemID: 25736
	BoxItemID: 25736
},
{
	Type: "LOOK_HAIR"
	Id: 32
	Zeny: 100000
},
{
	Type: "LOOK_CLOTHES_COLOR"
	Id: 0
	Index: 1
	ItemID: 6047
	BoxItemID: 16855
	AllowDoram: true
},
{
	Type: "LOOK_CLOTHES_COLOR"
	Id: 1
	Index: 2
	ItemID: 6046
	BoxItemID: 16854
	AllowDoram: true
},
{
	Type: "LOOK_CLOTHES_COLOR"
	Id: 2
	Index: 3
	ItemID: 6046
	BoxItemID: 16854
	AllowDoram: true
},
{
	Type: "LOOK_CLOTHES_COLOR"
	Id: 3
	Index: 4
	ItemID: 6046
	BoxItemID: 16854
	AllowDoram: true
},
{
	Type: "LOOK_CLOTHES_COLOR"
	Id: 4
	Index: 5
	ItemID: 6046
	BoxItemID: 16854
	AllowDoram: true
},
{
	Type: "LOOK_HEAD_TOP"
	Id: 2220
	Index: 1
	Zeny: 1000
	AllowDoram: true
},
{
	Type: "LOOK_HEAD_TOP"
	Id: 2208
	Index: 2
	Zeny: 800
	AllowDoram: true
},
{
	Type: "LOOK_HEAD_TOP"
	Id: 2211
	Index: 3
	Zeny: 400
	AllowDoram: true
},
{
	Type: "LOOK_HEAD_TOP"
	Id: 5909
	Index: 4
	Zeny: 50000
	AllowDoram: true
},
{
	Type: "LOOK_HEAD_TOP"
	Id: 19986
	Index: 5
	Zeny: 100000
	AllowDoram: true
},
{
	Type: "LOOK_HEAD_MID"
	Id: 2239
	Index: 1
	Zeny: 10000
	AllowDoram: true
},
{
	Type: "LOOK_HEAD_MID"
	Id: 2201
	Index: 2
	Zeny: 5000
	AllowDoram: true
},
{
	Type: "LOOK_HEAD_MID"
	Id: 2242
	Index: 3
	Zeny: 24000
	AllowDoram: true
},
{
	Type: "LOOK_HEAD_MID"
	Id: 2243
	Index: 4
	Zeny: 20000
	AllowDoram: true
},
{
	Type: "LOOK_HEAD_MID"
	Id: 2205
	Index: 5
	Zeny: 3500
	AllowDoram: true
},
{
	Type: "LOOK_HEAD_MID"
	Id: 19989
	Index: 6
	Zeny: 100000
	AllowDoram: true
},
{
	Type: "LOOK_HEAD_MID"
	Id: 20010
	Index: 7
	Zeny: 70000
	AllowDoram: true
},
{
	Type: "LOOK_HEAD_MID"
	Id: 5966
	Index: 8
	Zeny: 700000
	AllowDoram: true
},
{
	Type: "LOOK_HEAD_BOTTOM"
	Id: 2241
	Index: 1
	Zeny: 5000
	AllowDoram: true
},
{
	Type: "LOOK_HEAD_BOTTOM"
	Id: 20015
	Index: 2
	Zeny: 50000
	AllowDoram: true
},
{
	Type: "LOOK_HEAD_BOTTOM"
	Id: 20022
	Index: 3
	Zeny: 60000
	AllowDoram: true
},
{
	Type: "LOOK_BODY2"
	Id: 0
	Index: 1
	ItemID: 6959
	BoxItemID: 6959
	AllowDoram: true
},
{
	Type: "LOOK_BODY2"
	Id: 1
	Index: 2
	ItemID: 6959
	BoxItemID: 6959
	AllowDoram: true
},
)

**Comment by gravity-ro** [comment]
> this is how i fix in rathena. Please check if it has something wrong:
> 
> static void pc_readdb_stylist_libconfig_sub(struct config_setting_t *it, int16 count, const char *source) { int i32, Id = 0, zeny = 0, itemID = 0, boxItemID = 0; bool allow_doram = false; const char *name; int64 type; int16 idx;
> 
> ```
> nullpo_retv(it);
> nullpo_retv(source);
> 
> if (!config_setting_lookup_string(it, "Type", &name)) {
> 	ShowWarning("pc_readdb_stylist_libconfig_sub: Missing Type in \"%s\", entry #%d.\n", source, count);
> 	return;
> }
> if (!script_get_constant(name, &type)) {
> 	ShowWarning("pc_readdb_stylist_libconfig_sub: Invalid Type '%s' in \"%s\", entry #%d.\n", name, source, count);
> 	return;
> }
> if (type < 0 || type >= MAX_STYLIST_TYPE) {
> 	ShowWarning("pc_readdb_stylist_libconfig_sub: Out of range Type '%s' in \"%s\", entry #%d.\n", name, source, count);
> 	return;
> }
> if (!config_setting_lookup_int(it, "Id", &i32) || i32 < 0) {
> 	ShowWarning("pc_readdb_stylist_libconfig_sub: Missing or invalid Id %d in \"%s\", entry #%d.\n", i32, source, count);
> 	return;
> }
> Id = i32;
> if (config_setting_lookup_int(it, "Index", &i32))
> 	idx = i32;
> else
> 	idx = Id;
> if (config_setting_lookup_int(it, "Zeny", &i32))
> 	zeny = i32;
> if (config_setting_lookup_int(it, "ItemID", &i32))
> 	itemID = i32;
> if (config_setting_lookup_int(it, "BoxItemID", &i32))
> 	boxItemID = i32;
> if (config_setting_lookup_bool(it, "AllowDoram", &i32))
> 	allow_doram = (i32 != 0);
> if (!stylist_datas[type])
> 	CREATE(stylist_datas[type], struct s_stylist_data, 1);
> else
> 	RECREATE(stylist_datas[type], struct s_stylist_data, stylist_data_count + 1);
> stylist_datas[type][idx - 1].id = Id;
> stylist_datas[type][idx - 1].zeny = zeny;
> stylist_datas[type][idx - 1].itemid = itemID;
> stylist_datas[type][idx - 1].boxid = boxItemID;
> stylist_datas[type][idx - 1].allow_doram = allow_doram;
> stylist_data_count++;
> ```
> 
> }

Thank you.
This script fix it's works

But i think i found some bug maybe last bug please look in the pictures

![Screenshot_10](https://user-images.githubusercontent.com/80197766/154793923-12ab7c75-a6cb-4245-922e-7026c005d868.png)

![Screenshot_9](https://user-images.githubusercontent.com/80197766/154793924-37c88030-9b7b-4ec8-9af6-6166d9beba9b.png)

**Comment by gravity-ro** [comment]
Now i found way out to fix this error.
Thank you.

**Comment by gravity-ro** [comment]
Encountered an error The color of the dress does not change The change card has been deducted.

**Comment by dimasshotta** [comment]
@gravity-ro just use this instead https://github.com/rathena/rathena/commit/c22ef3f5476cee0f79bf8dfe6e390bcb5a23728d

**Comment by dimasshotta** [comment]
> Encountered an error The color of the dress does not change The change card has been deducted. And how to add item in list.
> 
> Thank advance.

if you want to add item, dont forget to edit stylingshopinfo.lub too, located in client folder data/luafiles514/luafiles/stylingshop. If you don't find it, try to look for it in your grf file using grf editor.

**Comment by Lemongrass3110** [comment]
This is not a support section.
