### ISSUE TITLE
Map-Server has crashed by rAthena r12931

### ISSUE THREAD

**Issue by TesLA-Git** [rathena/rathena#304]
Please see the problem.THX！
![20150223104630](https://cloud.githubusercontent.com/assets/7490388/6322200/7cfbf12c-bb4a-11e4-8741-aa4d0a48f90c.jpg)

**Comment by reigneil** [comment]
Confirmed!

**Comment by Playtester** [comment]
Yeah, I have the same issue too.

**Comment by julia40124009** [comment]
same issue ..

**Comment by aleos89** [comment]
Is this for pre-renewal or renewal mode? I was testing around on Windows last night in renewal mode and had no such issues. Just saw this bug report so I didn't test pre-renewal yet to see if I could reproduce.

**Comment by julia40124009** [comment]
renewal mode
Windows 7(64)
Visual studio 2010
no change source code 
just edit inter_athena.conf Sql setting

**Comment by reigneil** [comment]
i'm also using renewal mode and Visual Studio 2010.

**Comment by aleos89** [comment]
Can you run MSVS and run the map-server in debug mode and see where it fails at for me? Also, which Git hash are you at? Thanks.

**Comment by julia40124009** [comment]
complier no error
http://i.imgur.com/58korxw.png

version 
https://github.com/rathena/rathena/commit/5ce17c80a7ee20a39c9d984153d4f5853ef208db

**Comment by reigneil** [comment]
I'm using the latest one. 5ce17c80a7ee20a to be exact... this doesnt happen between 537fb42a4bbafd75e6 maybe there is something left when you cleanup the code. But not sure if i release debug mode right now because of the current build i have now.

**Comment by reigneil** [comment]
@aleos89 i do have now a test server to debug what would you like to see?
![untitled](https://cloud.githubusercontent.com/assets/9740000/6376753/e2d45360-bd5a-11e4-9ade-85acf9457e21.PNG)

**Comment by Playtester** [comment]
It also happens in pre-renewal.
