### ISSUE TITLE
Cast time of MG_FIREBOLT and MG_LIGHTNINGBOLT level 7 seems wrong.

### ISSUE THREAD

**Issue by BrOgBr** [rathena/rathena#3042]
* **rAthena Hash**: 

* **Client Date**: 

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Cast Time of skill **MG_FIREBOLT** and **MG_LIGHTNINGBOLT** _level 7_ seems wrong.
  * Official Information: I can't confirm, but it seems wrong.
  

Someone can check this in the official?

> 19,640:960:1280:1600:1920:2100:**1560**:2880:3200:3520,1000:1200:1400:1600:1800:2000:2200:2400:2600:2800,0,0,0,0,160:240:320:400:480:700:640:720:800:880

2100,"1560", 2880

WTF, level 7 lower than level 6, 5 and 4?

I didn't fix it, because I don't have the official information, but I believe that it's wrong.

**Comment by mrjnumber1** [comment]
VCT:
```
MG_COLDBOLT	640	960	1280	1600	1920	2100	1560	2880	3200	3520
MG_FIREBOLT	640	960	1280	1600	1920	2100	1560	2880	3200	3520
MG_LIGHTNINGBOLT	640	960	1280	1600	1920	2100	1560	2880	3200	3520
```
FCT:
```
MG_COLDBOLT	160	240	320	400	480	700	640	720	800	880
MG_FIREBOLT	160	240	320	400	480	700	640	720	800	880
MG_LIGHTNINGBOLT	160	240	320	400	480	700	640	720	800	880
```

**Comment by BrOgBr** [comment]
Nice, I didn't know about it.

**Comment by aleos89** [comment]
As shown by @mrjnumber1, this is how Aegis has it.
