### ISSUE TITLE
Missing Kimi Possession Item Bonuses

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#3051]
* **rAthena Hash**: 
d21e4df

* **Client Date**: 
Doesn't matter

* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result:
Missing the "possession of Kimi" bonus for the Heart Set bonus, and on the Evil Spirit Glove

  * Expected Result:
Hurt Mind[1] + Kind Heart[1] used in combination triggers the additional bonuses by being posseded by Kimi.
The Kimi Possession bonus effects consists of:
Adds a 1% chance of casting Level 10 [Frost Nova] on the target when performing a physical or magical attack.
Adds a 0.1% chance of casting Level 1 [Mystical Amplification] on the user when performing a magical attack.
Adds a 0.1% chance of casting Level 1 [Psychic Wave] on the target when performing a physical attack.
Adds a 0.1% chance of casting Level 1 [Scream] on the attacker when receiving a short-ranged or magical attack.

**I prepared the script already:**
`{ bonus3 bAutoSpell,"SO_PSYCHIC_WAVE",1,1; bonus5 bAutoSpell,"HW_MAGICPOWER",1,1,BF_MAGIC,0; bonus3 bAutoSpell,"WZ_FROSTNOVA",10,10; bonus5 bAutoSpell,"WZ_FROSTNOVA",10,10,BF_MAGIC,1; bonus4 bAutoSpellWhenHit,"DC_SCREAM",1,1,0; bonus5 bAutoSpellWhenHit,"DC_SCREAM",1,1,BF_MAGIC,0; }`

  * How to Reproduce:
There's no combo script nor anything that triggers a special kimi possession bonus.

  * Official Information:
The korean text only refers to triggering the possession, but iRO and other translations include the actual effects.
https://www.divine-pride.net/database/item/2977/hurt-mind-1
https://www.divine-pride.net/database/item/2978/kind-heart-1

https://www.divine-pride.net/database/item/2980/1

* **Modifications that may affect results**: 
None

**Comment by BrOgBr** [comment]
**bRO** is 1% for all skills and frost nova is only in physical attacks.
**iRO** is how you did.
**jRO** doesn't show the chance, but frost nova is only in physical attacks too.
**kRO** doesn't have sufficient information.
Need confirm in the **Aegis**.

http://ro.gnjoy.com/guide/runemidgarts/itemview.asp?itemSeq=2&ID=2978

**Comment by aleos89** [comment]
Looks pretty good from your description. Although the Scream part is wrong. It says when _receiving_ damage, not dealing. So it'd need to be:
`bonus5 bAutoSpellWhenHit,"DC_SCREAM",1,1,BF_WEAPON|BF_MAGIC,1;`

**Comment by Everade** [comment]
@aleos89 
I used  **bAutoSpellWhenHit**, so that should be correct?!
And shouldn't scream be cast on yourself rather than on the enemy?
`bonus4 bAutoSpellWhenHit,sk,y,n,i;   	Adds a n/10% chance to cast skill sk of level y when being hit by a direct attack
bonus5 bAutoSpellWhenHit,sk,y,n,bf,i;	Adds a n/10% chance to cast skill sk of level y when being hit by a direct attack with trigger criteria bf`

**I still think mine is correct, please explain ^^**
Btw: I've been testing it ingame and it worked just fine.

And yes, kRO information would be nice.
But i don't have a kRO account for testing purposes.

**Comment by aleos89** [comment]
You’re right, sorry. I must have looked at the other skill while tabbing between files. But it should still cast on the attacker as the description states. Scream causes stun, so I don’t see that as a bonus for the wearer to be stunned. :P

**Comment by Everade** [comment]
No, **you cast Scream**, which then stuns enemies ;)

**Comment by kukuasir1** [comment]
In twRO
Aegis:
```
item  Evilspirit_Gloves
	event OnStartEquip:
		AddExtParam User VAR_MAXHPAMOUNT 500
		AddExtParam User VAR_MAXSPAMOUNT 200
		SetAutoSpell2 Target SO_PSYCHIC_WAVE 1 20
		SetAutoSpellMagic HW_MAGICPOWER 1 User 10
		SetAutoSpell2 User WZ_FROSTNOVA 10 20
		SetAutoSpellMagic WZ_FROSTNOVA 10 User 10
		SetAutoSpell2_MLEATKED User DC_SCREAM 1 50
		SetAutoSpell2_MAGATKED User DC_SCREAM 1 50
		EnableSkill PF_SPIDERWEB 1
	return
	event OnFinishEquip:
		SubExtParam User VAR_MAXHPAMOUNT 500
		SubExtParam User VAR_MAXSPAMOUNT 200
		ResetAutoSpell2 Target SO_PSYCHIC_WAVE
		ResetAutoSpellMagic HW_MAGICPOWER 1 User 10
		ResetAutoSpell2 User WZ_FROSTNOVA
		ResetAutoSpellMagic WZ_FROSTNOVA 10 User 10
		ResetAutoSpell2_MLEATKED User DC_SCREAM
		ResetAutoSpell2_MAGATKED User DC_SCREAM
		DisableSkill PF_SPIDERWEB 1
	return

-----------------------------------------------------------------------------
item COMBIITEM_Heartset
	event OnStartEquip:
		SetAutoSpell2 Target SO_PSYCHIC_WAVE 1 10
		SetAutoSpellMagic HW_MAGICPOWER 1 User 10
		SetAutoSpell2 User WZ_FROSTNOVA 10 10
		SetAutoSpellMagic WZ_FROSTNOVA 10 User 10
		SetAutoSpell2_MLEATKED User DC_SCREAM 1 10
		SetAutoSpell2_MAGATKED User DC_SCREAM 1 10
	return
	event OnFinishEquip:
		ResetAutoSpell2 Target SO_PSYCHIC_WAVE
		ResetAutoSpellMagic HW_MAGICPOWER 1 User 10
		ResetAutoSpell2 User WZ_FROSTNOVA
		ResetAutoSpellMagic WZ_FROSTNOVA 10 User 10
		ResetAutoSpell2_MLEATKED User DC_SCREAM
		ResetAutoSpell2_MAGATKED User DC_SCREAM
	return


```

convert to ra 
item db:
`
2980,Evilspirit_Gloves,Evil Spirit Glove,4,10,,100,,,,1,0xFFFFFFFF,63,2,136,,110,1,,{ bonus bMaxHP,500; bonus bMaxSP,200; skill "PF_SPIDERWEB",1; bonus4 bAutoSpell,"SO_PSYCHIC_WAVE",1,20,1; bonus5 bAutoSpell,"HW_MAGICPOWER",1,10,BF_MAGIC,0; bonus4 bAutoSpell,"WZ_FROSTNOVA",10,20,0; bonus5 bAutoSpell,"WZ_FROSTNOVA",10,10,BF_MAGIC,0; bonus5 bAutoSpellWhenHit,"DC_SCREAM",1,50,BF_WEAPON|BF_MAGIC,0; },{},{}
`

combo db:
`
2977:2978,{ bonus4 bAutoSpell,"SO_PSYCHIC_WAVE",1,10,1; bonus5 bAutoSpell,"HW_MAGICPOWER",1,10,BF_MAGIC,0; bonus5 bAutoSpell,"WZ_FROSTNOVA",10,10,BF_WEAPON|BF_MAGIC,0; bonus5 bAutoSpellWhenHit,"DC_SCREAM",1,10,BF_WEAPON|BF_MAGIC,0; }
`


`
