### ISSUE TITLE
Update Cartridges

### ISSUE THREAD

**Issue by Questune09** [rathena/rathena#3052]
* **rAthena Hash**: 

* **Client Date**:  20170905

* **Server Mode**:  renewal

* **Description of Issue**:  some cartridges are missing all i can see if im not wrong only 4 - 5 catridges
  * Result:  check database about cartridge of rebellions
  * Expected Result:  i think lots of it is available on KRO
  * How to Reproduce: 
  * Official Information: 
Please see attach image 
![image](https://user-images.githubusercontent.com/29746866/38768672-f69dfb3a-4029-11e8-957b-9d816a7851a1.png)
![image](https://user-images.githubusercontent.com/29746866/38768673-fc9a894a-4029-11e8-9747-ab3276b203df.png)

  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Seems like Flare, Lightning, Ice, Poison, and Blind are missing.

**Comment by cydh** [comment]
guess it's part of Awakening patch
