### ISSUE TITLE
Mechanic Job problem

### ISSUE THREAD

**Issue by Questune09** [rathena/rathena#3057]
* **rAthena Hash**: 

* **Client Date**:  20170509

* **Server Mode**:  renewal

* **Description of Issue**:  Mado Equipments before you can use the skill you must equip the item first? is it default on official KRO or is this a bug since mado have a lots of item to use so its messy to switch and switch lots of item before using the skills

also Accelerator skill should be same as cart boost effect i mean when you use Accelerator skill it should same with cart boost the casting rate or same as when you use it

last thing is when you use Accelerator skill and you have a Increase Agi it should be gone but as i tested it the increase agi doesn't disappeared

sorry for noob english little hard to explain XD
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Questune09** [comment]
Another information

Skill can be use even the items are not equip

Same as other server have...

If im missing something kindly point it please thank you

**Comment by secretdataz** [comment]
This is how it works on kRO

**Comment by Questune09** [comment]
thank you for information @secretdataz 

is it possible to revert it back to unequip item of mado gear?

where? thank you again for confirmation
