### ISSUE TITLE
Missing Excellion Suit item bonus

### ISSUE THREAD

**Issue by Questune09** [rathena/rathena#3066]
* **rAthena Hash**: 

* **Client Date**:  20170507

* **Server Mode**:  renewal

* **Description of Issue**:  Excellion Suit should be not bonus Unbreakable base on item description
![image](https://user-images.githubusercontent.com/29746866/39097089-35868a68-468a-11e8-9cb2-53d81960ad6b.png)
  * Result:  Item is possible to be broke
  * Expected Result:  it should have bonus bUnbreakableArmor;
  * How to Reproduce: 
  * Official Information:
Divine pride : https://www.divine-pride.net/database/item/15128/excelion-suit
  

* **Modifications that may affect results**:

**Comment by admkakaroto** [comment]
Just add: 
`bonus bUnbreakableArmor,1;`

**Comment by BrOgBr** [comment]
`bonus bUnbreakableArmor;` **

**Comment by aleos89** [comment]
No rAthena has provided? This item isn't even in our database, unless I'm missing something.

**Comment by Questune09** [comment]
@aleos89  i think its already available since i dont make any custom items

**Comment by secretdataz** [comment]
```
rag@rag:~/ra$ cat db/re/item_db.txt | grep 15128
rag@rag:~/ra$ cat db/pre-re/item_db.txt | grep 15128
```
No it isn't provided by rA

**Comment by BrOgBr** [comment]
rAthena doesn't have it, I was planning to do a PR about it in the future. xD
