### ISSUE TITLE
Wrong bonus on Hunting Arrow item

### ISSUE THREAD

**Issue by teededung** [rathena/rathena#3067]
* **rAthena Hash**: c4d3f0f

* **Client Date**: 20170614

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: bonus bLongAtkRate,50;
  * Expected Result: no long range bonus

1774,Hunting_Arrow,Hunting Arrow,10,5,,1,35,,,,0x000A1848,63,2,32768,,1,,1,{ bonus bLongAtkRate,50; },{},{}

**Comment by aleos89** [comment]
Can you provide where/when this was removed on officials?

**Comment by cydh** [comment]
he's right,  because the 50% bonus long range atk is for combo with Hunter Bow [0]/[1]. not the arrow itself
