### ISSUE TITLE
ASPD problem

### ISSUE THREAD

**Issue by iubantot** [rathena/rathena#3076]
* **rAthena Hash**: 

23d20f6

* **Client Date**: 

 2017-06-14

* **Server Mode**: 

 Renewal

* **Description of Issue**: 
  * Result:  Attack speed penalty for two handed gear seems to be wrong.
no weapon equipped
![image](https://user-images.githubusercontent.com/13269331/39227837-63401492-488d-11e8-9dea-18f29a061585.png)
w/ two handed axe equipped
![image](https://user-images.githubusercontent.com/13269331/39227843-70d53132-488d-11e8-97c8-ca63642439b3.png)
w/ two handed axe equipped & adrenaline rush
![image](https://user-images.githubusercontent.com/13269331/39227903-b727552a-488d-11e8-8e3c-1b45c37f6e65.png)

  * Expected Result: 
w/ Two handed Axe equipped 
![image](https://user-images.githubusercontent.com/13269331/39227882-a5873088-488d-11e8-9119-e2b5f574521a.png)
w/ Adrenaline Rush Buffs
![image](https://user-images.githubusercontent.com/13269331/39227919-d31d85c4-488d-11e8-9afd-333a314ddfbf.png)

  * How to Reproduce: 
  * Official Information: https://calc.irowiki.org/
  

* **Modifications that may affect results**:

**Comment by admkakaroto** [comment]
There are at least 20 topics in the forum that say: THE EMULATOR USA KRO FORMULA, NOT IRO, USE THE SEARCH BUTTON.

**Comment by aleos89** [comment]
As @admkakaroto stated, we aren't using iRO formulas, so your calculator is completely wrong.

**Comment by iubantot** [comment]
two handed axe equipped & adrenaline rush is it really like that in kRO?

**Comment by Playtester** [comment]
It doesn't have much to do with the weapon. At 100 AGI, Adrenaline Rush should give about +4 ASPD, and according to your screenshot that's exactly what happens.

In renewal ASPD bonuses are no longer a percentual bonuses. Those had a stronger impact on your ASPD value when it was lower. Instead now, the bonus is higher the higher your AGI is and it's fixed, so the faster the weapon, the better the bonus.

**Comment by PipeDeveloper** [comment]
How we can change it to iRO formulas? is any documentation about it?
