### ISSUE TITLE
NEW UI  CASH SHOP is bug~

### ISSUE THREAD

**Issue by idamonli** [rathena/rathena#3077]
![qq 20180425155416](https://user-images.githubusercontent.com/13962741/39232650-8f5013f8-48a0-11e8-8070-957e7cfbdebb.png)
item_cash_db.txt
0-2 show~~
but
3-7 don't show

**Comment by Lemongrass3110** [comment]
Follow the template and provide better info.

**Comment by idamonli** [comment]
![qq 20180425160932](https://user-images.githubusercontent.com/13962741/39233347-aeaf5cf2-48a2-11e8-859c-dd403b81da02.png)
![qq 20180425160851](https://user-images.githubusercontent.com/13962741/39233350-afe40a00-48a2-11e8-84c4-389403ecf1ec.png)
