### ISSUE TITLE
miss some shadow equipment should can be refineable in rA's DB

### ISSUE THREAD

**Issue by Angelic234** [rathena/rathena#3078]
* **rAthena Hash**: 94e6893

* **Client Date**: 

* **Server Mode**: RE

* **Description of Issue**: 
  * Result:  here is the list of shadow item should can be refineable in rA's DB
ITEM_ID: 24000,24001,24002,24003,24004,24005,24006,24007,24008,24009,24010,24011,24012,24013,24014,24015,24016,24017,24240,24241,24242,24250,24251,24252,24253,24254,24255,24330
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment]
Why do you think those should be refineable?

**Comment by Angelic234** [comment]
like item id 24254 24255 , item script .@r = getrefine(); but in rA's DB those cant be refineable

**Comment by Lemongrass3110** [comment]
But not all of the items you have on your list have getrefine() in their script.
