### ISSUE TITLE
Random option group database rework

### ISSUE THREAD

**Issue by secretdataz** [rathena/rathena#3084]
* **rAthena Hash**: 10782d83e
* **Client Date**: Irrelevant
* **Server Mode**: Both
* **Description of Issue**: 
    The random option group database (item_randomopt_group.txt) is impractical to use in scenarios with multiple, random randopt_value and multiple option slots because you have to list all the permutations of the random options.
*  ** To-do list**:
- [ ] Support unweighted randopt_value range instead of specific value per entry
- [ ] Support per-slot random option specification instead of listing whole combination in an entry
Additional suggestions are welcome.
- [ ] Use YAML format instead of CSV

**Comment by secretdataz** [comment]
Your suggestions are welcome.

**Comment by Atemo** [comment]
What about to create subgroups of RDMOPTG for each option slot in item_randomopt_group? The subgroups could be called independently in mob_drop file afterward.

A sample to get the idea
item_randomopt_group :  https://gist.github.com/Atemo/1692b1dc308c27505eaac6cb3807de90
mob_drop : https://gist.github.com/Atemo/34d6459467c50c65724b0895c9fcda3f
