### ISSUE TITLE
Memory leak detected at ERS

### ISSUE THREAD

**Issue by keishirogane** [rathena/rathena#3087]
* **rAthena Hash**: 8c7cd293e
* **Client Date**: 2017-06-14
* **Server Mode**: Renewal
* **Description of Issue**: Memory leak detected at ERS 'instance.cpp::instance_maps_ers', 1 objects not freed.
  * Result: Nothing was experienced. This warning has shown up when I was shutting down the map server with CTRL+C.
  * Expected Result: There shouldn't be a memory leak.
  * How to Reproduce: I was doing the Faceworm instance and finished it then I exit the instance and was teleported back to prontera and I exit the ragnarok client then I pressed CTRL+C on the mapserver and this warning has shown up.
  * Official Information: None
* **Modifications that may affect results**: No modifications.

**Comment by aleos89** [comment]
I would like to clean this up again and move away from ERS and use C++ features.
