### ISSUE TITLE
Warning in latest revision

### ISSUE THREAD

**Issue by RadianFord** [rathena/rathena#309]
pc.c: In function 'pc_checkskill':
pc.c:5526: warning: unused variable 'i'
        CC      pc_groups.c
        CC      pet.c
        CC      quest.c
        CC      script.c
        CC      searchstore.c
        CC      skill.c
skill.c: In function 'skill_parse_row_requiredb':
skill.c:19989: warning: unused variable 'skill_id'
skill.c: At top level:
skill.c:222: warning: 'skill_chk2' defined but not used
skill.c: In function 'skill_unitsetting':
skill.c:12083: warning: array subscript is above array bounds

Its running on pre renewal mechanics.

**Comment by anacondaqq** [comment]
same, confirm. Using latest (28.02.2015)

**Comment by RadianFord** [comment]
Thanks! @aleos89
