### ISSUE TITLE
Sura combo

### ISSUE THREAD

**Issue by redlightliu** [rathena/rathena#3090]
* **rAthena Hash**: 258069d

* **Client Date**: 20160203

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Sura use Dragon Combo can't combo Fallen Empire and Tiger Cannon.And Raging Trifecta Blow can't combo Quadruple Blows , The way of the dragon and Asura Strike. 
  * Expected Result:It should easy to combo 
  * How to Reproduce: Try to use Dragon Combo and combo Fallen Empire and Tiger Cannon.
Try to trigger Raging Trifecta Blow and combo Quadruple Blows , The way of the dragon and Asura Strike. 

  

* **Modifications that may affect results**:

**Comment by LolyAll** [comment]
This is custom, is not official behavior...

**Comment by redlightliu** [comment]
@LolyAll But in official server,Sura use Dragon Combo after can use Fallen Empire. My old rAthena version can use too. But the new rAthena can't combo.
