### ISSUE TITLE
instance script command update

### ISSUE THREAD

**Issue by pajodex** [rathena/rathena#3095]
Hi.. I've been doing instanced script for quite sometimes now.. This isn't any issue at all but rather suggestions.. I've encountered a lot of mistakes while making script, but making an instance script _challenged_ me the most.. when debugging a bugged instanced script, the error in console doesn't really help.. Here are some of the troubles I've encountered so far:

1. If you implement an instanced script and forgot to put it instance_db.txt, the console error just says something like this:
```
--- nullpo info --------------------------------------------
h:\...\rathena\src\map\instance.cpp:373: in func `unknown'
```
I admit that its my fault for forgetting to put the data in instance_db but a better console debug would really save time.

2. Getting this error:
```
[Error]: Memory manager: args of aFree 0x1DF0EA2C is invalid pointer h:\...\rathena\src\map\map.cpp line 241
```
This one is really tricky.. its just because you need to put `sleep 1` before `instance_destroy()` to prevent this error.

3. Having a duplicate instance id entry on `instance_db.txt`. Example:
```
**23,TEST1,3600,300,prt_are01,150,160
24,TEST2,3600,300,prt_are01,150,160
25,TEST3,3600,300,prt_are01,150,160
**23,TEST4,3600,300,prt_are01,150,160
```
Ive recently encountered this.. Console didn't give any errors.. I accidentally put duplicate instance ID `23` entry on `instance_db.txt`.. Maybe something to detect duplicate entry like in item_db.txt

Again, this is not an issue but rather a suggestion. As a new scripter like me, took me around 2 hours to figure that I had issue 3 xD.. Anyways, I hope Dev Team consider this suggestion. Thanks and have a good day!

**Comment by aleos89** [comment]
1. Should be easy to fix.
2. Would need to look into it deeper.
3. The reason you didn't get a warning is because the parser is setup to interpret this as an import entry and override the previously parsed values. Could possibly be adjusted a bit in the C++ refactor.
