### ISSUE TITLE
Archer [Improve Concentration] and [Arrow Shower] bug? RE

### ISSUE THREAD

**Issue by reigneil** [rathena/rathena#310]
what i've notice is our Improve Concentration has a larger AoE for detecting enemy its 7x7 and Arrow Shower AoE is 5x5 at 1~5 and 7x7 at 6~10.
what irowiki info's are different... which is true then?
http://irowiki.org/wiki/Improve_Concentration
This skill will also reveal any hidden enemies in a 3x3 area around the user.
http://irowiki.org/wiki/Arrow_Shower
Area of Effect: 	3x3 ~ 5x5

**Comment by Playtester** [comment]
According to jRO wiki, AoE of Improve Concentration detect is 7x7.

AoE of Arrow Shower should be 3x3 on Level 1~5 and 5x5 on level 6~10.

Source: http://hunter.rowiki.jp/index.php?%E3%82%A2%E3%83%BC%E3%83%81%E3%83%A3%E3%83%BC%2F%E3%82%B9%E3%82%AD%E3%83%AB&usg=ALkJrhgj0Cw9d-TlFWgmZdroi7gPzlQ3pQ?%E3%82%A2%E3%83%BC%E3%83%81%E3%83%A3%E3%83%BC%2F%E3%82%B9%E3%82%AD%E3%83%AB

**Comment by reigneil** [comment]
about the Improved Concentration well maybe it is true that it is 7x7 and not 3x3 as Gravity sometimes do Ninja update. And for the Arrow Shower it is also mention in iROwiki kRO forum that this skill were nerf to be 3x3 ~ 5x5 changelog notice.

**Comment by Playtester** [comment]
Even more critical what I noticed when testing: Arrow Shower actually hits all targets twice.
