### ISSUE TITLE
Mage [Skills Casting Time] doubts and Fireball damage formula bug. RE

### ISSUE THREAD

**Issue by reigneil** [rathena/rathena#311]
1.most of the Magician skills in our Db's are not derive from 20% fixed casting time and 80% variable casting time are those data is correct? i.e Cold Bolt level 6 and 7 casting are different from the other 2100:1560 variable and 700:640 fixed versus 2240:2560 variable and 560:640 fixed if you calculate it using the formula.
source: http://irowiki.org/wiki/Mage
2. our formula for Fireball is different from what i see in irowiki
http://irowiki.org/wiki/Fire_Ball
what i've notice is there is missing +40 in our formula
skillratio += 20*skill_lv;
and also the splash damage must be 3/4 only
please enlighten me here...

**Comment by Playtester** [comment]
1. Cast times are available information which I could check if forums weren't down 24/7 these days.

2. Can confirm this. jRO wiki says the same: http://wizard.rowiki.jp/index.php?SkillMagician#l9548e26
It doesn't include the exact periphery damage, but in the notes it says that it's lower. I assume it's exactly like Magnum Break, dealing more damage in the center.

**Comment by reigneil** [comment]
looks like the number 2 problem has been fixed here: 583d079b0f0b

**Comment by Playtester** [comment]
Since forums are back up, I can also check cast times on Aegis...

Cold Bolt Fixed cast time: 160:240:320:400:480:700:640:720:800:880
Cold Bolt Variable cast time: 640:960:1280:1600:1920:2100:1560:2880:3200:3520

Kinda strange, but they are already like that in rAthena. So working as intended.

**Comment by reigneil** [comment]
I tested this recently and i found out that it is working as intended.
