### ISSUE TITLE
Map-server crash by skill Howling Mine(RL_H_MINE) and Flicker(RL_FLICKER)

### ISSUE THREAD

**Issue by redlightliu** [rathena/rathena#3114]
* **rAthena Hash**: 5242601

* **Client Date**: 20160203

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Use skill Howling Mine and Flicker in map gld2_ald then crash.
  * Expected Result: Sholud not crash.
An access violation occurred while writing to location 0x0000000C.
<img src="https://i.imgur.com/36uyy8F.png" alt="1" style="max-width:100%;">

**Comment by redlightliu** [comment]
rAthena Hash：339e6c6
Client Date: 20180620
Server Mode: Renewal

![Twice](https://user-images.githubusercontent.com/21969424/58057501-a6c95000-7b97-11e9-9374-59d8042bb654.png)

**Comment by aleos89** [comment]
I couldn't reproduce this crash.
