### ISSUE TITLE
Vicious Weapon item bonus missing?

### ISSUE THREAD

**Issue by GMSarah** [rathena/rathena#3118]
* **rAthena Hash**: 

* **Client Date**:  20170614b

* **Server Mode**:  renewal

* **Description of Issue**:  Vicious Weapons item bonus are missing while monster drop the item or by using GM command @item
  * Result:  when i killed a monster that drops a vivious weapons and use magnifier the vicious weapons dont have any bonus on it?
  * Expected Result:  it should have a item bonus if im not wrong base on item description and screenshot
![image](https://user-images.githubusercontent.com/29746866/40094828-b7d757b2-58fb-11e8-9a19-b0f87829862a.png)
  * How to Reproduce: 
  * Official Information: on KRO they already provide / released the vicious weapons have a random option bonus
  

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment]
Related to #3084

**Comment by Atemo** [comment]
https://github.com/rathena/rathena/commit/be9babee3213ba8b19ef3fa42b4a4ecafd6680c4
