### ISSUE TITLE
Latest Git Report (Skills, Variables and Functions)

### ISSUE THREAD

**Issue by tmav94** [rathena/rathena#313]
After Start the Server

[Warning]: skill_parse_row_requiredb: Skill '385' isn't created in 'skill_db.txt' yet. Creating dummy value...
[Warning]: skill_parse_row_requiredb: Skill '386' isn't created in 'skill_db.txt' yet. Creating dummy value...
[Warning]: skill_parse_row_requiredb: Skill '388' isn't created in 'skill_db.txt' yet. Creating dummy value...
[Status]: Done reading '865' entries in 'db/re/skill_require_db.txt'.
[Warning]: skill_parse_row_castdb: Skill '360' isn't created in 'skill_db.txt' yet. Creating dummy value...
[Warning]: skill_parse_row_castdb: Skill '572' isn't created in 'skill_db.txt' yet. Creating dummy value...
[Warning]: skill_parse_row_castdb: Skill '573' isn't created in 'skill_db.txt' yet. Creating dummy value...
[Warning]: skill_parse_row_castdb: Skill '574' isn't created in 'skill_db.txt' yet. Creating dummy value...
[Warning]: skill_parse_row_castdb: Skill '575' isn't created in 'skill_db.txt' yet. Creating dummy value...
[Warning]: skill_parse_row_castdb: Skill '692' isn't created in 'skill_db.txt' yet. Creating dummy value...
[Warning]: skill_parse_row_castdb: Skill '694' isn't created in 'skill_db.txt' yet. Creating dummy value...
[Warning]: skill_parse_row_castdb: Skill '695' isn't created in 'skill_db.txt' yet. Creating dummy value...

While Compilation:

skill.c: In function ‘skill_parse_row_requiredb’:
skill.c:19989: warning: unused variable ‘skill_id’
skill.c: At top level:
skill.c:222: warning: ‘skill_chk2’ defined but not used
skill.c: In function ‘skill_unitsetting’:
skill.c:12083: warning: array subscript is above array bounds

pc.c: In function ‘pc_checkskill’:
pc.c:5526: warning: unused variable ‘i’

**Comment by reigneil** [comment]
duplicate report: https://github.com/rathena/rathena/issues/309

**Comment by tmav94** [comment]
i'm using renewal server...

**Comment by cydh** [comment]
````
[Warning]: skill_parse_row_requiredb: Skill '385' isn't created in 'skill_db.txt' yet. Creating dummy value...
[Warning]: skill_parse_row_requiredb: Skill '386' isn't created in 'skill_db.txt' yet. Creating dummy value...
[Warning]: skill_parse_row_requiredb: Skill '388' isn't created in 'skill_db.txt' yet. Creating dummy value...
[Status]: Done reading '865' entries in 'db/re/skill_require_db.txt'.
[Warning]: skill_parse_row_castdb: Skill '360' isn't created in 'skill_db.txt' yet. Creating dummy value...
[Warning]: skill_parse_row_castdb: Skill '572' isn't created in 'skill_db.txt' yet. Creating dummy value...
[Warning]: skill_parse_row_castdb: Skill '573' isn't created in 'skill_db.txt' yet. Creating dummy value...
[Warning]: skill_parse_row_castdb: Skill '574' isn't created in 'skill_db.txt' yet. Creating dummy value...
[Warning]: skill_parse_row_castdb: Skill '575' isn't created in 'skill_db.txt' yet. Creating dummy value...
[Warning]: skill_parse_row_castdb: Skill '692' isn't created in 'skill_db.txt' yet. Creating dummy value...
[Warning]: skill_parse_row_castdb: Skill '694' isn't created in 'skill_db.txt' yet. Creating dummy value...
[Warning]: skill_parse_row_castdb: Skill '695' isn't created in 'skill_db.txt' yet. Creating dummy value...
````
Just uncomment those skills on ur skill_db
