### ISSUE TITLE
Character bound instances do not persist on logout

### ISSUE THREAD

**Issue by ghTravis** [rathena/rathena#3132]
* **rAthena Hash**: 9aa406e4069ea470fbe19b30fba949acc9de3f2f (latest)

* **Client Date**: 2015-11-04

* **Server Mode**: Pre-renewal

* **Description of Issue**: 
  * Result: When creating a character-bound instance using instance_create(IM_CHAR), if the character disconencts, logs out, or changes character the instance is no longer attached to the character upon logging in, but the server still appears to hold onto the instance until the instance expiry timer ends. This is displayed by the console showing [Info]: [Instance] Created: <instance_name> (1). and not showing a destroy informational message. The client also does not show the instance window in game.
  * Expected Result: I would expect the user to be able to rejoin their instance if they disconnected during an IM_CHAR bound instance.
  * How to Reproduce: Create a short script that creates an instance for a character using IM_CHAR, enter the instance, disconnect, log back in, you will see there is no instance popup in game and if you script supports re-entering, you will find there is no attached instance.

* **Modifications that may affect results**: None

I am unsure about what official behavior is, but I feel like the instance should be attached to the character still after a disconenct and relog. Using IM_PARTY, the behavior works as expected. The character logs back on and will find that they have an attached instance if they are still belonging to that party.

**Comment by Akaineko-astasi** [comment]
[Here](https://youtu.be/0_BMbhNhXbU?t=4311) the player creates a solo party to join OGH. And [here](https://youtu.be/0_BMbhNhXbU?t=4416) he logs out to another character and logs in back safely O_O

**Comment by Lemongrass3110** [comment]
@Akaineko-astasi this is exactly what he said. Since all official instances use IM_PARTY.
