### ISSUE TITLE
Homunculus_S attack damage value anomaly(skill) by rAthena r12951

### ISSUE THREAD

**Issue by TesLA-Git** [rathena/rathena#314]
------------------------------
The test environment:
------------------------------
rAthena Version SVN: 12951
Homunculus ID / Name: 6052 / Eleanor
Homunculus Level: 150
Homunculus skill ID / Name / Description: 8028 / MH_SONIC_CRAW / Sonic Claw
Report: attack damage value anomaly (160000+)

Is it right? Too much damage?
Please see the problem.THX！

![1](https://cloud.githubusercontent.com/assets/7490388/6431553/e44d46fa-c06d-11e4-99f5-e253bcbb490a.png)

**Comment by reigneil** [comment]
releted report: https://github.com/rathena/rathena/issues/298

**Comment by MrAntares** [comment]
+1
