### ISSUE TITLE
Cached Event Silent Crash

### ISSUE THREAD

**Issue by ignizh** [rathena/rathena#3143]
* **rAthena Hash**: 1d1a179b722dba4b938473b4e6eaa056bd912f0d

* **Client Date**: 20180207

* **Server Mode**:  RE

* **Description of Issue**: 
  * Result: As before, it crashes but now I can't get the crash log or the ash for gdb, it just kills the server.

* **Modifications that may affect results**: 
For more info see Issue #3108, just a lot of scripts loaded at Init. Again, lowering the number of instances or scripts with "OnInit" or "OnLoadMap" flags fixes this problem.

**Comment by Lemongrass3110** [comment]
Could you be running out of RAM?

**Comment by Lemongrass3110** [comment]
No user input for over a month.
