### ISSUE TITLE
Custom Scripts (ResetNPC.txt) Reset Skills error by rAthena r12951  

### ISSUE THREAD

**Issue by TesLA-Git** [rathena/rathena#315]
First I use custom scripts (JobMaster.txt) and job changge to Genetic (175 / 60).
After that I use custom scripts (ResetNPC.txt) reset skills.
Report: skill points to increase and Map Sever error.

Please see the problem.THX！

![2](https://cloud.githubusercontent.com/assets/7490388/6431667/3c459890-c072-11e4-9274-251d456edc14.png)

**Comment by aleos89** [comment]
This should be fixed in 6472425.

**Comment by reigneil** [comment]
@TesLA-Git  are you still have this error? feedback please...

**Comment by TesLA-Git** [comment]
After aleos89`s fix is normal.THX:)
