### ISSUE TITLE
Destroy Instance Button

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#3150]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/e06781594709c24b53f258ec887c5dc5763f6556
* **Client Date**: 2018-05-16c
* **Server Mode**: Renewal
* **Description of Issue**: With the new client came the function of destroying the current instance, however it does not work in the current rathena.
  * Result: Nothing happens when I click the button.
  * Expected Result: The instance is destroyed.
  * How to Reproduce: Just click the button to destroy the instance after you have generated the dungeon.

![123](https://user-images.githubusercontent.com/6227618/40460439-1c5e772e-5edd-11e8-86e5-9ef04f333876.png)

LINK: https://github.com/zackdreaver/ROenglishRE/blob/master/data/msgstringtable.txt#L3271

**Comment by aleos89** [comment]
This has been tagged in the instance cleanup.
