### ISSUE TITLE
About Skill Feint Bomb(SC_FEINTBOMB) damage

### ISSUE THREAD

**Issue by redlightliu** [rathena/rathena#3154]
* **rAthena Hash**: e067815

* **Client Date**: 20160203

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: If use skill Feint Bomb Lv3 to attack any monster , the monster got only 1 damage.
  * Expected Result: The skill Feint Bomb Lv3 damage should not only 1 damage.
  * How to Reproduce: Use skill Feint Bomb Lv3.
  * Official Information: https://www.youtube.com/watch?v=HLDF-UHp37I&t=

**Comment by aleos89** [comment]
Make sure your job level is high enough. A normal Shadow Chaser player won't have a job level < 10.
