### ISSUE TITLE
Zaha Doll Hat (id: 5464) transformation

### ISSUE THREAD

**Issue by laziem** [rathena/rathena#3158]
* **rAthena Hash**: 1d1a179b7

* **Client Date**: 2017-05-17

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Transformation duration did not refreshed until the current transformation ended
  * Expected Result: The transform duration should able to refreshed during the transformation if the effect procs
  * How to Reproduce: 
  * Official Information: [https://www.youtube.com/watch?v=PnC9sVS6hgY](url)

* **Modifications that may affect results**: -

**Comment by cydh** [comment]
This is related with autobonus #3039

**Comment by Lemongrass3110** [comment]
Fixed in e7fd6aa
