### ISSUE TITLE
Script command that retrieves RID of all players  in a map

### ISSUE THREAD

**Issue by pajodex** [rathena/rathena#3159]
Hi, 

So, I just want to suggest once again if this idea is good for implementation in rAthena..
I searched out the `script_commands.txt` and cannot find any commands that does this.. the closest one I can get is `addrid()` but that command will `attach` the players in a map(or whatever type you choose) which causes the script to run as many times as the players attached in the command.. as much as I know, this can cause a lot of memory because it multiplies the script processing (if im not mistaken).

So I came up to an idea (a new script command) which could be really helpful in a way or two..
```
*getmaprid(<type>,<flag>,{,<parameters>}});

This command will retrieve RIDs to a temporary global array "$@getmapridaid[] / $@getmapridcid[]" from specific <type>.

<flag> determins what type of RID are retrieved:
 0: Account ID
1: Character ID

<type> determines what RIDs are retrieved:
 0: All players in the map.
    [ Parameters: "<map name>" ]
 1: All players in a specified area of the map of the invoking player (or NPC).
    [ Parameters: <x0>,<y0>,<x1>,<y1> ]


```

I don't know much in src mod.. so I cant do any of these xD.. well, if this idea is not good.. just close this topic.. thanks :)

**Comment by hurtsky** [comment]
i believe this?
*addrid
 https://github.com/rathena/rathena/blob/master/doc/script_commands.txt#L3862

**Comment by pajodex** [comment]
As I've said, addrid will attach the player not just retrieve. The idea in my mind is just retrieving the RIDs and nothing more.

**Comment by hurtsky** [comment]
@pajodex owh okay, sorry for not reading it thoroughly.

**Comment by aleos89** [comment]
What would be your intent of having all of the RIDs in an array? You'd still need to attach them to the script, right? `addrid` should work just fine unless you plan on attaching several hundreds of players on an intensive script. If it's a basic script with no serious loops or timers you should be fine with `addrid` in my opinion.

**Comment by pajodex** [comment]
`addrid` works very confusing..  here is an [example](https://rathena.org/board/topic/115483-detaching-rid/#comment-345121) 
also `addrid(0)` seems to fetch `all` players in the server.. it sounds so heavy.. maybe a new command is not needed but an enhancement to `addrid`? Personally, I think its better to retrieve RIDs first before attaching them using `attachrid`.. works lighter and neat.. easier to understand and eliminates confusion when tryin to make some scripts. 

Well, these are my personal sents.. I don't know if I even make sense xD I hope you get my point xD

**Comment by technoken** [comment]
I’ve seen a custom mod for that. Retrieving rid’s without a need to attach a player before executing the command. Not sure if it would work though on the latest rA. Might need an update

https://rathena.org/board/topic/98070-extended-cell-pvp-17/?do=findComment&comment=268981
