### ISSUE TITLE
POEM OF BRAGI PROBLEM!

### ISSUE THREAD

**Issue by momolandzxc** [rathena/rathena#3169]
Hi,

I need help My skill POEM OF BRAGI not working on any skill on my server
my server is pre-renewal server please anyone help me!

case BA_POEMBRAGI:
		val1 = 3 * skill_lv + status->dex / 10; // Casting time reduction
												//For some reason at level 10 the base delay reduction is 50%.
		val2 = (skill_lv<10 ? 3 * skill_lv : 50) + status->int_ / 5; // After-cast delay reduction
		if (sd) {
			val1 += pc_checkskill(sd, BA_MUSICALLESSON);
			val2 += 2 * pc_checkskill(sd, BA_MUSICALLESSON);
		}
		break;

**Comment by Lemongrass3110** [comment]
You have been banned for the next 3 days.
