### ISSUE TITLE
Takekwons Can't Learn Skills (crytical)

### ISSUE THREAD

**Issue by anacondaqq** [rathena/rathena#317]
[Debug]: Skill Level up failed. ID:449 idx:439 (CID=157682. AID=2000000)
[Debug]: Skill Level up failed. ID:453 idx:443 (CID=157682. AID=2000000)
[Debug]: Skill Level up failed. ID:468 idx:458 (CID=157682. AID=2000000)

You can't learn any skill. Error above... This happened only for soul linkers, taekwons, star gladiators.
Some of skill do not work at Taekwon.
![](http://i6.5cm.ru/i/TCCh.png)

### Technical Information
rAthena clear, pre-re, mmo.h 20100730
Revision: (last) https://github.com/rathena/rathena/commit/d4aa4c70a7ec51781109d27c9a7041e0a37d488f

## I think problem is here:
> https://github.com/rathena/rathena/commit/9d3d34205fdb424e4a9281c3e6a951a1f0cdbdc1#diff-08420bab8271f3965304fee42cf4b865R1697

**Comment by TesLA-Git** [comment]
I also have this problem.

**Comment by samurairukasu** [comment]
I confirm this bug!! It must be fixed assap!

**Comment by cydh** [comment]
thank you, should be fixed now
