### ISSUE TITLE
item_db and mob_db name mismatch

### ISSUE THREAD

**Issue by MrAntares** [rathena/rathena#3171]
RE and PRE
https://github.com/rathena/rathena/commit/d060ff79dc60a28192906dccee09c19bb9860fab

The names in the mob_dbs and the item_dbs are pretty confusing and are half correct.
Mob_db was already somewhat cleared up, so it has 2 columns for the names, kname and iname. This is ok. On the other hand, items still use the old structure:
name_english and name_japanese. The problem is that, the name_japanese is actually the iro name, which is english, and the name_english is a semi-kro based code for the items, since it only uses alphanumerical and underscore characters. This is pretty wrong. I know that names are mainly appear based on the grfs the clients use, but in some cases this can result in npcs calling the items on other names that actually appear, and also when summoning items by name, you have to use the pretty badly translated codenames, that are completely misleading sometimes. 

Current example:
Mob (this looks good):
    ID: 1628, Sprite: MOLE, kName: Mole,iName: Holden
Item (not that clear):
    id: 4343, name_english: Mole_Card, name_japanese: Holden Card

The problem with the example from above is that mobs use their kName by default, while items use their name_japanese for display, and name_english for commands. This results in Moles dropping Holden cards while you have to use ``` `@item` ``` mole_card to summon the item.... And there are many similar mobs and items. I think these should be cleared up and made selectable which to use (if they are not already)..

**Comment by cydh** [comment]
it is disaster for me for ages. I wanted to change that `name_english` to `AegisName` and `name_japanese` to `displayname` (maybe). so does with `--ja--` in monster spawning

but really damnit, u should read what we put on issue template.

**Comment by MrAntares** [comment]
If you are referring to the tagging thing, sorry I don't write many issue reports on git, so I have to learn all the stupid signs all over again whenever drop a post. /#blame_github/ Otherwise TL/DR. Templates don't match the problem many times. I always try to provide every **relevant** info.

On the issue itself: I strongly support any change that fixes this name mixup. ;)

**Comment by Bonamil0512** [comment]
how to remove union skill reduce 2% HP any help please
