### ISSUE TITLE
Unable to create instances ( Airship Assault )

### ISSUE THREAD

**Issue by gegewu85** [rathena/rathena#3175]
rAthena Hash: Latest
Client Date: Unknown
Server Mode: Both Server

Description of Issue:
Cannot create instances, according to information in iro wiki the min level must be 125 ( https://irowiki.org/wiki/Airship_Raid ), and my character level is 144.

Attached screenshot of it.

![screenrathena006](https://user-images.githubusercontent.com/34573590/40697709-c07f4b72-63f5-11e8-9a69-836fd4c1a9c6.jpg)

**Comment by Atemo** [comment]
I can't reproduce, bad merge ?
Check your instance_db maybe
