### ISSUE TITLE
Dragon Tail and Howling Mine Skill Rebellion Cannot Added

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#3177]
* **rAthena Hash**: 1b6aab3

* **Client Date**: 20170517

* **Server Mode**: RENEWAL

* **Description of Issue**: 
  * Result: Dragon Tail and Howling Mine cannot added, i was test using skill simulator build and reset build but not work. Cannot add dragon tail skill.
  * Expected Result: skill Dragon Tail and Howling Mine can add
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by admkakaroto** [comment]
if it is referring to the projectile, it can only be equipped with the specific weapon. This is not a bug, it's a behavior, post this kind of thing in the forum, not git.

**Comment by aleos89** [comment]
Dragon Tail only works on targets that are flagged with Crimson Marker.
