### ISSUE TITLE
bAutoSpellOnSkill Generating high damages

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#3185]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/ad5416e2719e6d5685a468daf987d86e510eca36

* **Client Date**: 2018

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: 

Use this combo: 
```
32204:28010,{ .@r = getequiprefinerycnt(EQI_HAND_R); bonus bAtkRate,5*.@r; if(.@r >= 9) bonus4 bAutoSpellOnSkill,"GC_ROLLINGCUTTER","AB_ORATIO",1000,1; }

32204,Immortal_Dog_Tag,Immortal Dog Tag,4,0,0,100,,0,,1,0xFFFFFFFF,63,2,136,,100,0,0,{},{},{}	
```
Use now to generate Oratio. Get a Mechanic and use Ax bomerang. The damage is almost 20X the damage it should be. It also affects other abilities. The problem is that there is something wrong with bAutoSpellOnSkill.
 
* **Expected Result**: bAutoSpellOnSkill should only reproduce the skill as it is. It is affecting the damage greatly.
 
* **How to Reproduce**: 
* **Official Information:** 
  

* **Modifications that may affect results**:

**Comment by BrOgBr** [comment]
bonus4 bAutoSpellOnSkill,sk,x,y,n;

when use skill "sk"
spell skill "x"
level "y"
chance "n" /10%

**Comment by Badarosk0** [comment]
The 'x' skill is undergoing autospell influences.

**Comment by BrOgBr** [comment]
bonus4 bAutoSpellOnSkill,sk,x,y,n;

when use skill "sk"
spell skill "x"
level "y"
chance "n" /10%

You put Oration level 1000 and chance 0,1% (1/10%)

Try this:

`bonus4 bAutoSpellOnSkill,"GC_ROLLINGCUTTER","AB_ORATIO",1,1000;`

**Comment by Atemo** [comment]
Like @BrOgBr said your player will cast AB_ORATIO at level 1000
