### ISSUE TITLE
SC_FREEZING effects update

### ISSUE THREAD

**Issue by flamefury** [rathena/rathena#3191]
* **rAthena Hash**: 046d2e6c440083d868d0f89a86d6463e586afac1
* **Client Date**: Doesn't matter
* **Server Mode**: Renewal
* **Description of Issue**: 
  * Result: Freezing status as is currently coded matches iRO Wiki's results. That is:
Movement Speed - 50%, Attack Speed - 15%, Physical Defence - 10%, Variable Cast Time + 15%.
Minimum duration of 6 seconds.
  * Expected Result: Effects should instead be:
Movement Speed to 70%, Attack Speed - 30%, Physical DEF - 30%, Fixed Cast Time + 50%.
Minimum duration of 10 seconds.
  * How to Reproduce: Become affected by Freezing (Frost Misty, Dragon Breath - Water, Ice Bound Trap).
  * Official Information: http://ro.gnjoy.com/news/notice/View.asp?BBSMode=10001&seq=5352
Specifically, this section:
** 빙결 상태이상의 효과가 변경되었습니다.
--
  | 이동속도 70% 감소 / 공격 속도 30% 감소 / 고정 캐스팅 시간 50% 증가
  | 방어력이 30% 감소합니다.
  | 화속성 몬스터 및 화속성 갑옷을 입은 플레이어도 빙결 효과의 영향을 받도록 변경됩니다.
  | - 빙결 효과의 지속시간이 최소 10 초가 되도록 변경되었습니다.
  | - 빙결 효과의 기본 지속시간이 늘어났습니다.

Please note that this newspost is newer than the following one, which lists effects closer to the iRO Wiki written effects (though not an exact match):
http://ro.gnjoy.com/news/notice/View.asp?BBSMode=10001&seq=5123

Note that monsters only receive a DEF drop of 10%: https://github.com/rathena/rathena/issues/3191#issuecomment-397362050

* **Modifications that may affect results**: None

**Comment by aleos89** [comment]
Do you have anything newer? That source is from 2009 which is prior to Renewal release. It's possible it has changed from then as well.

**Comment by danielbernard** [comment]
I tried to do some digging, and found that irowiki switched **from** the "newer" values mentioned above, to what we currently use.
[2011.12.25](https://irowiki.org/w/index.php?title=Status_Effects&oldid=34727#Freezing) → [2012.09.28](https://irowiki.org/w/index.php?title=Status_Effects&oldid=37091#Freezing)
[diff](https://irowiki.org/w/index.php?title=Status_Effects&type=revision&diff=37091&oldid=34727)
I've not had any luck finding other mentions of this change beyond a warpportal forum post from [June 28th, 2011](https://forums.warpportal.com/index.php?/topic/41119-frozen-freezing-one-should-be-changed/) that mentions the values mentioned above.

It might be safe to assume this change was reverted at some point.

**Comment by flamefury** [comment]
The effect text of the Freezing status says Fixed Casting Time, not Stats-based or Variable as iRO Wiki claims:
https://www.novaragnarok.com/forum/uploads/monthly_2018_05/FrostMistyDurationMinimal.gif.d1a502edb8e2760d7018f2bcdf137359.gif

What's more, the duration formula of Frost Misty on iRO wiki is entirely wrong. I don't think we can rely on that information whatsoever.

This will require testing since there are no later newsposts from kRO that mention changes to Freezing status in as much detail.

**Comment by flamefury** [comment]
Come to think of it, that GIF right there proves the ASPD drop is 30%, not 15%.
ASPD is 156, then drops to 145 under when Freezing hits.

Using kRO ASPD formula the drop is calculated as
(156 - 145) = FLOOR(195 - 156) * X%
11 = FLOOR ( 39 * X% )

Where 30% for X is far closer than 15%.

I've been playing around with the movement speed decrease but it does not appear to be as drastic as either 70% or 50%. I believe it may actually be a 30% drop (as in, a drop TO 70%). I'll make some GIFs when to compare against Marsh of Abyss Lv3 (30%) and Lv5 (50%).

I'm not sure the best method of going about the DEF test.

And I'll get around to Fixed Casting Time vs Variable Casting Time test when I think of non-damaging or low damage FCT skills.

**Comment by flamefury** [comment]
Confirming Freezing affects Fixed Casting Time. A simple Energy Coat test comparing the two cast times.
https://streamable.com/tamv1

First cast, 5 seconds. Second cast, 7.5 seconds, which lines up exactly with the FCT +50% I found in the newspost.

**Comment by flamefury** [comment]
Confirming speed drop of Freezing is 30%. Matches Marsh of Abyss Lv3's movement speed drop exactly:
https://streamable.com/hc3op

Unedited video / replay available if necessary in case you want to look over stats and active status effects.

**Comment by flamefury** [comment]
Freezing DEF drop may be 10% instead of 30%.
https://streamable.com/qgo33

Naked WL with 67 status ATK against a Freezer (127 hDEF, (94+50)/2 = 72 sDEF)
Damage was 35 with Freezing, 32 without.
32 = FLOOR(134 * [(4000+127)/(4000 + 10*127)] - (94+50)/2)
35 = FLOOR(134 * [(4000+X)/(4000 + 10*X)] - (94+50)/2)

Solving for X yields a possible range of 110 (~13% down) to 115 (~9% down). The only nice, divisible by 5 number in that range is 10%. This is assuming Freezing does nothing to soft DEF.

Someone should double check that the formulas I used were correct.

The last thing is the minimum duration increase to 10 seconds. Assuming the Freezing duration formula is correct:
Source duration - [ (VIT + DEX) ÷ 20 ] sec
The lowest requirement for this (assuming rAthena has the effect durations correct) is to have VIT+DEX > 200 and then trigger an Icebound Trap (20s), or have VIT+DEX > 100 and survive Tetra Vortex [Water] (15s). All other player sources of Freezing last 40s, which would require an astronomical VIT+DEX > 600.
This may take me a bit to do since I'm not sure if I have a Ranger handy.

**Comment by flamefury** [comment]
Scratch that, Tetra Vortex's Freezing duration is also 40 seconds base. That means every resistable player source of Freezing requires VIT+DEX > 600 assuming the minimum is 10 seconds and VIT+DEX > 680 if the currently coded 6 seconds is correct. Barring some insane manipulation, this is impossible to test on official.

**Comment by flamefury** [comment]
Just to be sure the interaction was right, I tested Sacrament + Freezing. It appears to stack additively on top of FCT reductions:
https://streamable.com/w9yp1

Energy Coat, first cast under Sacrament = 2.5s, second cast under Sacrament + Freezing = 5s

**Comment by aleos89** [comment]
Could you test to see the DEF reduction versus a player? I'm curious if that's -30% while mobs are -10%.

**Comment by flamefury** [comment]
Good call.
https://streamable.com/a9qyb
Warlock stats: https://i.imgur.com/5DHy7bT.png
Warlock status ATK = 158
Rebellion hDEF = 130, sDEF = 81
`FLOOR(158 * 2 * [ (4000 + 130) / (4000 + 130 * 10) ] ) - 81 = 165`
`182 = 158 * 2 * [ (4000 + 130 * X) / (4000 + 130 * 10 * X) ] - 81`

Solving for X gives ~0.70474. An hDEF drop of 30% works perfectly here.
I will amend my PR to do a player check and drop by 30%, else, drop by 10%.
