### ISSUE TITLE
Over refine bug

### ISSUE THREAD

**Issue by cydh** [rathena/rathena#3193]
* **rAthena Hash**: f4e8dee5d686efb1701518c04128b74e83096f15
* **Client Date**: 2015-11-04 (doesn't matter)
* **Server Mode**: Renewal
* **Description of Issue**: 
  * Result: Doesn't matter the `RandomBonusValue`, it gives nothing
  * Expected Result: Of course the damage will be higher!
  * How to Reproduce: 
    1. Run server
    2. Get a weapon with high refine, make sure it gains over refine bonus
    3. Kill any mob (better try with using BS/WS with power maximize and critical)
    4. Try edit refine_db.yml file, especially the `RandomBonusValue` part then `@reloadstatusdb` or restart map-server
    5. Try kill monster again
  * Official Information: -

* **Modifications that may affect results**: None

iirc I ever read same issue before :thinking: 
1. Overrefine in battle.cpp only called in `battle_calc_base_damage` that is never be called for player in renewal mode.
```cpp
/*==========================================
 * Calculates the standard damage of a normal attack assuming it hits,
 * it calculates nothing extra fancy, is needed for magnum break's WATK_ELEMENT bonus. [Skotlex]
 * This applies to pre-renewal and non-sd in renewal
 *------------------------------------------
 * Pass damage2 as NULL to not calc it.
 * Flag values:
 * &1 : Critical hit
 * &2 : Arrow attack
 * &4 : Skill is Magic Crasher
 * &8 : Skip target size adjustment (Extremity Fist?)
 * &16: Arrow attack but BOW, REVOLVER, RIFLE, SHOTGUN, GATLING or GRENADE type weapon not equipped (i.e. shuriken, kunai and venom knives not affected by DEX)
 *
 * Credits:
 *	Original coder Skotlex
 *	Initial refactoring by Baalberith
 *	Refined and optimized by helvetica
 */
static int64 battle_calc_base_damage(struct block_list *src, struct status_data *status, struct weapon_atk *wa, struct status_change *sc, unsigned short t_size, int flag)
```
2. In renewal, the battle.cpp will calls `battle_calc_damage_parts` then calls `battle_calc_base_weapon_attack` where `wa->atk` is used.
3. ~~Also, `wa->atk2` that stores the refine bonus also only called in `battle_calc_base_damage`. Seems something off with refine too?~~ was moved to watk2 on status_calc. only overrefine that has issue.

**Comment by aleos89** [comment]
Related to #1596?

**Comment by cydh** [comment]
yes
