### ISSUE TITLE
Item 1265(Bloody_Roar) and 1273(Bloody_Roar_C) some wrong bonuses

### ISSUE THREAD

**Issue by AzarthMZintos** [rathena/rathena#3197]
* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Some wrongs bonus
  * Expected Result: 
The right bonus, 1265 should have Flee - (Agi + Base Level) not what it is now the two flee bonus;
The right bonus, 1273 should have Restores 3 HP every 5 seconds; and not have any negative flee bonus
  * How to Reproduce: Look at the script
  * Official Information: 
https://www.divine-pride.net/database/item/1265
https://www.divine-pride.net/database/item/1273

  

* **Modifications that may affect results**:

**Comment by danielbernard** [comment]
I only did a little bit of digging on this. RMS, rA, and Hercules all use the -160 flee. iRO, divine-pride, and some others all reference flee - (agi + blvl).
I'm also not having good luck finding whether or not this is the case for pre-renewal as well as renewal.
Regardless, if someone else gives the go-ahead, I'll make the change for re and/or pre-re and make a pull request with the following scripts

Bloody_Roar (1265):  `{ bonus bIgnoreDefRace,RC_DemiHuman; bonus bIgnoreDefRace,RC_Player; bonus bFlee,-(readparam(bAgi)+BaseLevel); bonus bHPrecovRate,-100; bonus bSPrecovRate,-100; }`
Bloody_Roar_C (1273): `{ bonus bIgnoreDefRace,RC_DemiHuman; bonus bIgnoreDefRace,RC_Player; bonus2 bHPRegenRate,3,5000; }`

Patch diffs if someone else wants to make the changes.
[issue3197_re.txt](https://github.com/rathena/rathena/files/2092519/issue3197_re.txt)
[issue3197_pre-re.txt](https://github.com/rathena/rathena/files/2092520/issue3197_pre-re.txt)

**Comment by aleos89** [comment]
```
item Bloody_Roar
	event OnStartEquip:
		var temp = get[VAR_STANDARD_AGI]+get[VAR_CLEVEL]
		SubExtParam User VAR_AVOIDSUCCESSVALUE temp
		SetIgnoreDEFRace RACE_Human
    		SetIgnoreDEFRace RACE_Player
		SubExtParam User VAR_HPACCELERATION 100
		SubExtParam User VAR_SPACCELERATION 100
	return
```
```
item Bloody_Roar_C					
	event OnStartEquip:				
		SetIgnoreDEFRace RACE_Human
		SetIgnoreDEFRace RACE_Player					
		SetHPAmountTime Bloody_Roar_C 5000 3			
	return	
```

**Comment by Atemo** [comment]
I wonder if the previous `-160` was from pre-renewal datas..

**Comment by aleos89** [comment]
http://db.irowiki.org/olddb/item-info/1265/

I know it's iRO Wiki DB (not super reliable) but even their description states it's based on the player's stats.

**Comment by cydh** [comment]
> I wonder if the previous -160 was from pre-renewal datas..

I was looking for older aegis file, the 11 I had, it's AGI-Level. maybe older than *that* pre-renewal (first generation of Gremlin summoned xD)
