### ISSUE TITLE
Kaahi activation and duration

### ISSUE THREAD

**Issue by Playtester** [rathena/rathena#320]
Kaahi should activate instantly at the start of being attacked, long before the damage is applied. There shouldn't be any timer at all, no healings should be "swallowed".
It should only activate on normal attacks and only when HP is not full (already working). It should activate even if the attack misses (most likely working, didn't check).

The duration of kaahi should be 350 seconds. This is true for both pre-renewal and renewal.

**Comment by reigneil** [comment]
AFAIK the faster the enemies ASPD the faster the recovery rate. this is noticeable in a large packed of mobs that every hit counts but it drains your SP faster thou... and skill doesn't trigger this at all.
source: http://irowiki.org/wiki/Kaahi

**Comment by Playtester** [comment]
Healing triggers on every normal attack you receive, whether it hits or not, so of course faster ASPD means more heals.

**Comment by reigneil** [comment]
uhm yeah i forgot to mention even if the attack miss. although my example does not reflect to it as it is because of a large pack of mob where fleeing is not an option. XD

**Comment by Playtester** [comment]
I tested everything now, the only thing that was not working on rAthena already was that there was a timer which shouldn't be there and that the duration should be 350 seconds and not 1800 seconds. Will be fixed shortly.
