### ISSUE TITLE
Failure to Compile - Edited to remove potentially useless info

### ISSUE THREAD

**Issue by bentheexo** [rathena/rathena#3205]
* **rAthena Hash**: 
43513e9

* **Client Date**: 
Not to that point

* **Server Mode**: 
Not to that point

* **Description of Issue**: 
Compilation issue
  * Result: 
Failure to Compile

[v1gro@CentOS-75-64-minimal build]$ cmake3 -G"Unix Makefiles" -DINSTALL_TO_SOURCE=ON ..
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Found git : /usr/bin/git version (1.8.3.1)
-- git Version: 43513e9ba5f56f9fd6c64a34f6a5a2164c83a5ff, 43513e9ba5f56f9fd6c64a34f6a5a2164c83a5ff
-- Adding global library: /usr/lib64/libm.so
-- Adding global library: /usr/lib64/libdl.so
-- Found MYSQL: /usr/lib64/mysql/libmysqlclient.so (found version "8.0.11")
-- Found PCRE: /usr/lib64/libpcre.so (found version "8.32")
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7")
-- Available targets:
--      common_base
--      common
--      login-server
--      char-server
--      map-server
--      mapcache
-- Configuring done
-- Generating done
-- Build files have been written to: /home/v1gro/rathena/build

[v1gro@CentOS-75-64-minimal build]$ make install

[ 25%] Building CXX object src/common/CMakeFiles/common_base.dir/db.cpp.o
/home/v1gro/rathena/src/common/db.cpp:2777:19: warning: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wliteral-suffix]
  ShowInfo(CL_WHITE"Database nodes"CL_RESET":\n"
                   ^
/home/v1gro/rathena/src/common/db.cpp:2780:19: warning: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wliteral-suffix]
  ShowInfo(CL_WHITE"Database types"CL_RESET":\n"
                   ^
/home/v1gro/rathena/src/common/db.cpp:2793:19: warning: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wliteral-suffix]
  ShowInfo(CL_WHITE"Database function counters"CL_RESET":\n"
                   ^
[ 31%] Building CXX object src/common/CMakeFiles/common_base.dir/showmsg.cpp.o
/home/v1gro/rathena/src/common/showmsg.cpp:778:26: warning: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wliteral-suffix]
    FPRINTF(STDERR, CL_RED"[ERROR]"CL_RESET": Could not open '"CL_WHITE"%s"CL_RESET"', access denied.\n", DEBUGLOGPATH);
                          ^
/home/v1gro/rathena/src/common/showmsg.cpp:778:43: warning: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wliteral-suffix]
    FPRINTF(STDERR, CL_RED"[ERROR]"CL_RESET": Could not open '"CL_WHITE"%s"CL_RESET"', access denied.\n", DEBUGLOGPATH);
                                           ^
/home/v1gro/rathena/src/common/showmsg.cpp:778:71: warning: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wliteral-suffix]
    FPRINTF(STDERR, CL_RED"[ERROR]"CL_RESET": Could not open '"CL_WHITE"%s"CL_RESET"', access denied.\n", DEBUGLOGPATH);
                                                                       ^
/home/v1gro/rathena/src/common/showmsg.cpp:788:25: warning: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wliteral-suffix]
   FPRINTF(STDERR, CL_RED"[ERROR]"CL_RESET": DEBUGLOGPATH not defined!\n");
                         ^
[ 40%] Linking CXX static library ../../../lib/libcommon_base.a
[ 40%] Built target common_base
Scanning dependencies of target common
[ 41%] Building CXX object src/common/CMakeFiles/common.dir/sql.cpp.o
/home/v1gro/rathena/src/common/sql.cpp: In function ‘Sql* Sql_Malloc()’:
/home/v1gro/rathena/src/common/sql.cpp:81:2: error: ‘my_bool’ was not declared in this scope
  my_bool reconnect = 1;
  ^
/home/v1gro/rathena/src/common/sql.cpp:81:10: error: expected ‘;’ before ‘reconnect’
  my_bool reconnect = 1;
          ^
/home/v1gro/rathena/src/common/sql.cpp:82:53: error: ‘reconnect’ was not declared in this scope
  mysql_options(&self->handle, MYSQL_OPT_RECONNECT, &reconnect);
                                                     ^
/home/v1gro/rathena/src/common/sql.cpp: In function ‘int Sql_P_BindSqlDataType(MYSQL_BIND*, SqlDataType, void*, size_t, long unsigned int*, int8*)’:
/home/v1gro/rathena/src/common/sql.cpp:543:19: error: ‘my_bool’ was not declared in this scope
  bind->is_null = (my_bool*)out_is_null;
                   ^
/home/v1gro/rathena/src/common/sql.cpp:543:27: error: expected primary-expression before ‘)’ token
  bind->is_null = (my_bool*)out_is_null;
                           ^
/home/v1gro/rathena/src/common/sql.cpp:543:28: error: expected ‘;’ before ‘out_is_null’
  bind->is_null = (my_bool*)out_is_null;
                            ^
/home/v1gro/rathena/src/common/sql.cpp: In function ‘int SqlStmt_NextRow(SqlStmt*)’:
/home/v1gro/rathena/src/common/sql.cpp:872:3: error: ‘my_bool’ was not declared in this scope
   my_bool truncated;
   ^
/home/v1gro/rathena/src/common/sql.cpp:872:11: error: expected ‘;’ before ‘truncated’
   my_bool truncated;
           ^
/home/v1gro/rathena/src/common/sql.cpp:885:21: error: ‘truncated’ was not declared in this scope
    column->error = &truncated;
                     ^
make[2]: *** [src/common/CMakeFiles/common.dir/sql.cpp.o] Error 1
make[1]: *** [src/common/CMakeFiles/common.dir/all] Error 2
make: *** [all] Error 2

  * Expected Result: 
Not this.
  * How to Reproduce:
Compile it with the same environment, but it seems to be a global issue and not a local one. 
  * Official Information:
  

* **Modifications that may affect results**: 
No modifications
  
  
* **System Spec**:
[v1gro@CentOS-75-64-minimal ~]# free -g
              total        used        free      shared  buff/cache   available
Mem:            125           9           1           0         114         115
Swap:             3           0           3
[v1gro@CentOS-75-64-minimal rathena]$ cat /proc/cpuinfo
processor       : 0
vendor_id       : AuthenticAMD
cpu family      : 23
model           : 1
model name      : AMD EPYC 7401P 24-Core Processor
stepping        : 2
microcode       : 0x8001227
cpu MHz         : 2000.000

power management: ts ttp tm hwpstate cpb eff_freq_ro [13] [14]
[v1gro@CentOS-75-64-minimal rathena]$ df
Filesystem      1K-blocks      Used  Available Use% Mounted on
/dev/md2       1840115912 140217140 1606356256   9% /
/dev/md1           498980    201551     271244  43% /boot

2 2TB SSDs in Raid 1

**Comment by aleos89** [comment]
Looks like `my_bool` was removed in MySQL 8.x. You can read up [here](https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-1.html#mysqld-8-0-1-compiling).

**Comment by aleos89** [comment]
Further digging I found [this](https://bugs.mysql.com/bug.php?id=87337) article. You need to update your MySQL to 8.0.2 or newer to support backwards compatibility of the `my_bool` variable type.

**Comment by aleos89** [comment]
Yeah I checked the comment section which stated it was reverted in 8.0.3. @secretdataz has pushed a version check which should resolve your issue.
