### ISSUE TITLE
Error WFIFOSET: maximum write buffer

### ISSUE THREAD

**Issue by userid0** [rathena/rathena#3219]
* **rAthena Hash**: 
105cc3a
* **Client Date**: 
20170614
* **Server Mode**: 
Renewal
* **Description of Issue**: 
Can't create character
 " [Error]: WFIFOSET: Maximum write buffer size for client connection 4 exceeded, most likely caused by packet 0x006e (len=3, ip=""). "
![image](https://user-images.githubusercontent.com/5185035/41506249-8219a7b2-7244-11e8-9439-c922ea1dedb6.png)

**Comment by vstumpf** [comment]
What is your packetver defined as?

**Comment by userid0** [comment]
#define PACKETVER 20170614

**Comment by userid0** [comment]
Firewall block create packet
