### ISSUE TITLE
Wrong name in renters.txt

### ISSUE THREAD

**Issue by zackdreaver** [rathena/rathena#3221]
* **rAthena Hash**: 524260183e6369cc2a4bc9441fd73a169e63915b

* **Client Date**: n/a

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Magic Gear Master
  * Expected Result: Mado Gear Armourer (마도기어관리병)
  * How to Reproduce: Check script
  * Official Information: kRO navi_npc_krpri.lub
  

* **Modifications that may affect results**: n/a

**Comment by zackdreaver** [comment]
navi_npc_krpri.lub

**Comment by danielbernard** [comment]
I created a pull request if we want to enact this change. Note that there are still many references to Magic Gear instead of Mado Gear. I'm not sure if we want to go through the effort to pull everything over to "Mado Gear" instead.

**Comment by zackdreaver** [comment]
Magic gear is iRO translation,
And i don't see any magic being used by mado gear.

We shouldn't rely on iRO translation too much if we can translate it ourself, just my opinion.
