### ISSUE TITLE
use skills in dead players in woe/bg/pvp should not cost any sp/hp/or itens

### ISSUE THREAD

**Issue by Raf4h** [rathena/rathena#3227]
* **rAthena Hash**: ae69e506263f9b183c945f49b1d88c5fc2b73a6a

* **Client Date**: Client Date: 2017-06-07

* **Server Mode**:  RE

* **Description of Issue**: in rathena its possible to target and cast skill in dead players in woe/pvp/bg and its costing mana/hp/itens and putting skill on cd. 
Its a big problem in woe/bg scenario where people spam alot of skill with high cd and cost mana and hp...

  * Result:  even players are dead the skill goes to cd and cost sp/hp or pre-req like spheres or itens such as spider weeb
  * Expected Result:  do not able to cast skill on dead players, with exception Resurrection...
  * How to Reproduce: https://www.youtube.com/watch?v=nm4pnU1tMok
  
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by crazystorm2017** [comment]
First of all this isn't possible in neither WOE nor BG and this behavior is the same in official.
That's why there is the /noshift in the client.

**Comment by aleos89** [comment]
See #1118 and #1218.
