### ISSUE TITLE
BaseJob and Super Nono

### ISSUE THREAD

**Issue by Atemo** [rathena/rathena#324]
BaseJob NPC script command return the default value -1 for Super novice, super baby, super novice ex super baby ex class. I think in map.h
>	MAPID_SUPER_NOVICE = JOBL_SUPER_NOVICE|JOBL_2_1|0x0,
>	MAPID_SUPER_BABY = JOBL_SUPER_NOVICE|JOBL_BABY|JOBL_2_1|0x0,
>	MAPID_SUPER_NOVICE_E = JOBL_SUPER_NOVICE|JOBL_THIRD|JOBL_2_1|0x0,
>	MAPID_SUPER_BABY_E = JOBL_SUPER_NOVICE|JOBL_THIRD|JOBL_BABY|JOBL_2_1|0x0,

should be
>	MAPID_SUPER_NOVICE = JOBL_2_1|0x0,
>	MAPID_SUPER_BABY = JOBL_BABY|JOBL_2_1|0x0,
>	MAPID_SUPER_NOVICE_E = JOBL_THIRD|JOBL_2_1|0x0,
>	MAPID_SUPER_BABY_E = JOBL_THIRD|JOBL_BABY|JOBL_2_1|0x0,

**Comment by cydh** [comment]
blurgh those exceed int limit @_@
the idea was we can do fast lookup for Sunov using bitwise `&JOBL_SUPER_NOVICE`

**Comment by Atemo** [comment]
Ha I get it
>then what's BasJob of Super Novices? Novice? like this
The BaseJob should be Super nono for the 4 Super nono
JOB_SUPER_NOVICE

https://github.com/rathena/rathena/blob/master/src/map/map.h#L131
>//Super Novices are considered the 2-1 version of the novice! Novices are considered a first class type, too...
