### ISSUE TITLE
Test Reagent should be a consumable

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#3241]
* **rAthena Hash**: 
4633ab5

* **Client Date**: 
2018-02-21bRagexeRE

* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result: 
Item ID 22699 Test Reagent can't be used as it is considered an etc. item by rAthena.

  * Expected Result: 
Should be a consumable item with the following effects
Flee + 100 for 0 minutes
Adds a 1000% chance of inflicting Blind for 5 seconds to the user when using this item

  * How to Reproduce:
This is an item drop from the boss monster T_W_O which spawns within the instance The Last Room.

  * Official Information:
https://www.divine-pride.net/database/item/22699

* **Modifications that may affect results**: 
none

**Comment by Lemongrass3110** [comment]
Well I think this is a usable item, but the buff description seems wrong(0 minutes and 1000%) and I have no idea which SC/SI this would be.

I will put the basics here, just in case someone knows the status change for this.
`22699,Test_Reagent,Test Reagent,2,,,30,,,,,0xFFFFFFFF,63,2,,,,,,{ /* TODO */ },{},{}`

**Comment by Everade** [comment]
**Information is now known:**
Flee + 100 for **5 seconds**.
Adds a 1000% chance of inflicting Blind on the user for 5 seconds when using this item.

**Comment by Lemongrass3110** [comment]
Fixed in 4a5ab68
