### ISSUE TITLE
Steelbody didn't reduce damage ashura strike

### ISSUE THREAD

**Issue by cahya1992** [rathena/rathena#3242]
* **rAthena Hash**: 

7113743
* **Client Date**: 

20151104
* **Server Mode**: 
Pre Renewal

* **Description of Issue**: 
  * Result: Ashura have fix damage to enemy when enemy use Steelbody
  * Expected Result: it's Should reduce damage ashura when use steel body
  * How to Reproduce: use Steel body and another player ashura
  * Official Information:
  

* **Modifications that may affect results**: 
Use Gepard

**Comment by Atemo** [comment]
On pre-re STEELBODY change the def/mdef of the user, bypassed by asura strike.
