### ISSUE TITLE
Item DB | Bunker Shield | Item Bonus not working.

### ISSUE THREAD

**Issue by kaninhot004** [rathena/rathena#3249]
* **rAthena Hash**: 37330448586ad909de7feae75c5e507646ca6619

* **Client Date**: 20151104

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Item Id : 28915 `{ bonus2 bAddRace,RC_All,4; bonus bAspdRate,5; .@r = getrefine(); if(.@r>=5) { bonus2 bAddRace,RC_All,.@r; } }` It's not provide more damage.
  * Expected Result: It's provide more damage.
  * How to Reproduce: -
  * Official Information: -

**Comment by aleos89** [comment]
Fixed in 8c4be8d (#3250).
