### ISSUE TITLE
Cannot Enter WOE TE Castle

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#3251]
* **rAthena Hash**: 23f7b94

* **Client Date**: 20170517RE

* **Server Mode**: RENEWAL

* **Description of Issue**: 
  * Result:  Can not enter woe te castle. in fact, I use novice or job 1 and job 2 without rebirth.
  * Expected Result:  Can Enter Castle
  * How to Reproduce:  Disable hall of abyss, disable guild mission. I think this warp script not work https://github.com/rathena/rathena/blob/master/npc/re/warps/guildcastles.txt
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by admkakaroto** [comment]
I can not reproduce.

For me it works 100%.

**Comment by Atemo** [comment]
Even with the mistake when converting `strnpcinfo(2)` jobs allowed can enter for me. Check your mapserver, I bet you disabled `WoeTETimeStart` function.
