### ISSUE TITLE
Gates of Hell bonus damage should not be affect by any external modifiers

### ISSUE THREAD

**Issue by Raf4h** [rathena/rathena#3254]
* **rAthena Hash**: ae69e50

* **Client Date**: 2017-06-07

* **Server Mode**: RE

* **Description of Issue**:

rathena's goh formula is the same from aegir, but in aegir servers ranged modifiers does not aply to the skill. Beside that, the bonus damge, the part of goh's damage that scale with hpmax-current hp and sp, ignores race and size modifiers, this part of the dmg is always neutral and it is only reduced by ghostring,deviling, energy coat, and woe reduction.

Ranged modifier test:

Kro test no cards:
https://i.imgur.com/iKWb17t.jpg

kRO Test 2x Enchanted Archer Skeleton (+24% ranged damage):
https://i.imgur.com/W03itVn.jpg

Rathena test:

Goh vs valk shield = 0% de ranged dmg reduction
https://i.imgur.com/qH7Av2R.png

Goh vs Rectangular shield = 35% ranged dmg reduction
https://i.imgur.com/QK8NX2v.png

Goh Bonus damage test:

In this case, the sura used to test it was with low atk, so all the damage is from hp bonus...

Gate of hell vs poring:
https://i.imgur.com/3It9ONx.jpg

Gates of hell +4x card scorpion vs poring
https://i.imgur.com/VfkNd7L.jpg

Goh vs Ghostring:
https://i.imgur.com/ecDSTaw.jpg
Goh vs No ghostring:
https://i.imgur.com/40mBEs4.jpg

Goh vs energy coat:
https://i.imgur.com/CrkooyF.jpg

No energy Coat:
https://i.imgur.com/cuN35XN.jpg
  * Result:  Goh in rathena server have a very diferent behavior from aegir, with ranged modifiers affecting all skill and other external modfiers affeting the bonus damage
  * Expected Result:  ranged modfiers should not affect the skill at all and other external modifiers should not affect the bonus damage
  * How to Reproduce: 
  * Official Information: https://irowiki.org/wiki/Gates_of_Hell
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Related to #771.
