### ISSUE TITLE
Adding atcommand reloadcashdb

### ISSUE THREAD

**Issue by gengstergile** [rathena/rathena#3256]
* **rAthena Hash**: 
f196304f0

* **Client Date**: 
20151104

* **Server Mode**: 
Both

* **Description of Issue**: 
No ability to switch either to use cashdb sql only.

  * Result: -
  * Expected Result: -
  * How to Reproduce: -
  * Official Information:-
  

* **Modifications that may affect results**: 
separating cash shop from other itemdb and reloading only cashdb when updating cash shop to reduce loading time.
adding function to use txt itemdb while using sql cashdb

**Comment by gengstergile** [comment]
yes i noticed the issue, for logged in user need to update the cash shop they need to relog for the changes to take effect, but this issue also exist with the reloaditemdb. adding this functionality can separate the need to use all db either sql or txt since cash shop need to be update much regularly.

**Comment by sader1992** [comment]
i don't think its a need as `@reloaditemdb` work they way you want the command to work

also rAthena is moving to yaml so i think we better not care a lot about how these things work for now ,Because this may be changed soon , however this is only my opinion.

**Comment by cydh** [comment]
1. about this issue & PR, yeah separate to reload cashdb from itemdb is reasonable
2. @Lemongrass3110 force to send or resend cash shop list in **kRO clients** will cause the client crash. iirc the client request to get cash shop list on player first login (until client reopened). (uhh sorry it was years ago, I noticed when play with openkore). So as long as after reloading then (I guess our code is safe) then we do some check on buy request, it's ok.
3. (i don't want to mention) implementing and worry about yml conversion will bring you nowhere.

**Comment by Akkarinage** [comment]
Merged in fd9b475
