### ISSUE TITLE
Gate of Hell

### ISSUE THREAD

**Issue by Tokeiburu** [rathena/rathena#3259]
* **rAthena Hash**: f196304
* **Client Date**: Any
* **Server Mode**: Renewal
* **Description of Issue**: 
  * Result: Gate of Hell's damage doesn't match kRO.
  * Expected Result: Matches kRO.
  * How to Reproduce: 
  * Official Information: The tests below were done on kRO Sakray server.

### SP consumption issue
* On kRO, Gate of Hell requires 30% of your SP to be casted on **any skill level**. On rAthena, it requires 20% + 20 SP and it varies depending of your skill level.
* On kRO, the skill does not consume a fixed SP value, it consumes 11% ~ 20% of your SP and nothing else (even though it does indeed display Sp : 30 on the skill bar, that's probably meant as the 30% SP requirement). On rAthena, 11 ~ 20 SP is consumed when casting the skill and then a 11% ~ 20% SP is consumed.

### SP damage bonus
* The formula currently used is ```ATK_ADD(wd.damage, wd.damage2, (sstatus->sp * (1 + skill_lv * 2 / 10)) + 10 * status_get_lv(src));```. This formula only works for skill_lv 5 and 10:
```
1 + 1 * 2 / 10 = 1 (should be 1.2)
1 + 2 * 2 / 10 = 1 (should be 1.4)
1 + 3 * 2 / 10 = 1 (should be 1.6)
1 + 4 * 2 / 10 = 1 (should be 1.8)
1 + 5 * 2 / 10 = 2
...
```
... you get the idea! This is not intended and I tested it on kRO as well.

### Long range modifiers
* Gate of Hell's damage is not reduced by long range modifiers (long_attack_def_rate).

### The HP/SP damage part
* On kRO, this damage is not affected by card modifiers (but it is reduced by def). Currently on rAthena, the damage is combined to wd.damage and then a battle_calc_cardfix is applied on the whole thing.

### Card modifiers
(The tests below were done without a weapon to remove the variance.)
![image](https://user-images.githubusercontent.com/8761658/41991100-5bea5368-7a12-11e8-8a9e-871c1158244d.png)

![image](https://user-images.githubusercontent.com/8761658/41991039-298eee6a-7a12-11e8-8eb4-5912ee6a6040.png) ![image](https://user-images.githubusercontent.com/8761658/41991056-35fb9fcc-7a12-11e8-804f-24ee06d579c6.png)

This one is tad more complex. Card fixes are applied before the damage parts are combined (so before `wd.damage = wd.statusAtk + wd.weaponAtk + wd.equipAtk + wd.masteryAtk;`) because each one is treated differently.
* The statusAtk and the masteryAtk are not affected by elemental modifers (such as Deviling). They have the 'NK_NO_ELEFIX' flag. Currently on rAthena, the modifiers are applied on the whole damage instead.
* The weaponAtk and the equipAtk are affected by elemental modifiers (which is the current behavior on rAthena). These tests were not shown on screenshots though.

I believe that covers most of it! I do have plenty of screenshots (or could take more), but there would be too many to post. If one's required, I don't mind adding them though.

**Comment by Raf4h** [comment]
rathena git have reports from 2015 about that and untill today nothing was made, prety sad

**Comment by Atemo** [comment]
Who are you? Where is your contribution to the software?
