### ISSUE TITLE
Heat Barrel - Rebellion Skill - Possible Bug?

### ISSUE THREAD

**Issue by samurairukasu** [rathena/rathena#326]
Server Instance: Renewal
Exe: 20141022
Rathena Git: Last revision.
Issue: Skill doesn´t works as description say

Descrition (IRO WIKI):
Consume all coins to increase caster's ASPD and ATK at the cost of accuracy. Higher skill level increases ASPD and ATK increase as well as accuracy decrease. After the duration, the caster will not be able to attack or use skills/items for 10 seconds. This skill cannot be used with Last Stand. If the caster switches equipment during the duration, the skill will end and activate the 10 second penalty. Buff lasts for 60 seconds.

In testing ASPD increase and Flee Decrease, like it must do it, but ATK not increase at all.
Status Icon of the skill does not show in screen.

**Comment by cydh** [comment]
ATK increased not displayed on window, no icon means ur client side files have missing like lua for EFST lookup or the tga file.
