### ISSUE TITLE
display warlock elemental ball bug on using fly wings

### ISSUE THREAD

**Issue by nornane** [rathena/rathena#3264]
- rAthena Hash: 105cc3a
- Client Date: 2016-02-03
- Server Mode: Renewal

On player summon elemental ball and `@jump` or wing
elemental ball will display double amount.

sample way to fix this

[https://drive.google.com/open?id=1poLwMDi6399j_zkWO_Ur14ltwv57FmYx](https://drive.google.com/open?id=1poLwMDi6399j_zkWO_Ur14ltwv57FmYx)

**Comment by Lemongrass3110** [comment]
Could you retry this with 796a67b.
This sounds almost like this problem.
