### ISSUE TITLE
bAddDamageClass and bAddMagicDamageClass not working

### ISSUE THREAD

**Issue by uddevil** [rathena/rathena#3265]
* **rAthena Hash**: 4633ab5ca1c70074df9392afdb2b1da2c60636dc

* **Client Date**: 2015-11-04 RE

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result:  `bonus2 bAddDamageClass` and `bonus2 bAddMagicDamageClass` does not increase physical and magical damage against specific Mob ID

  * Expected Result: As in description documentation, `bonus2 bAddDamageClass` and `bonus2 bAddMagicDamageClass` should increase physical and magical damage against specific Mob ID (source : https://raw.githubusercontent.com/rathena/rathena/master/doc/item_bonus.txt )
![image](https://user-images.githubusercontent.com/10105610/42093757-b243fa68-7bd7-11e8-8fa1-db88abf6d1fb.png)

  * How to Reproduce: 
   * Add `bonus2 bAddDamageClass` and `bonus2 bAddMagicDamageClass` on any Item
   * Here i'm using Poring Card (Item ID 4001) as example
   * Here's the edited script :
     ```4001,Poring_Card,Poring Card,6,20,,10,,,,,,,,16,,,,,{ bonus bLuk,2; bonus bFlee2,1; bonus2 bAddDamageClass,1002,100; bonus2 bAddMagicDamageClass,1002,100; },{},{}```
   * Note : I've tried using 100 and 10000 for the x value
   * Tried using normal attack, lightning bolt, and asura strike, damage does not increase

  * Official Information: I don't know since i can't found any of these scripts in the item db, so i'm guessing it must be custom

  

* **Modifications that may affect results**: There's no other modification other than the poring card above.

**Comment by aleos89** [comment]
Are you wearing a weapon while attacking or bare handed?

**Comment by uddevil** [comment]
@aleos89 tried both, bare handed and with knife

**Comment by Tokeiburu** [comment]
That's a problem with the documentation. It should be:

```
bonus2 bAddDamageClass,c,x;     	+x% physical damage against class c
bonus2 bAddMagicDamageClass,c,x;	+x% magical damage against class c
```

These are class bonuses, not mob ID bonuses.

**Comment by attackjom** [comment]
test on Crab card. and it also not working against "Aster"
