### ISSUE TITLE
Script (disable_items;) duplicating items

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#3277]
* **rAthena Hash**: 
https://github.com/rathena/rathena/commit/e4eddc3e617bd5702f5ce29f605ee66207fe66b4

* **Client Date**: 
2018

* **Server Mode**: 
Renewal

* **Description of Issue**: 

  * Result: Currently scripts using disable_itens; are not safe. Depending on the script's to cheat and remove items or duplicate. I've seen players doing this in privates. This is a sad thing.

  * Expected Result: Can not remove any item when the script exists in the disable_itens code; even using any skill with the NPC chat open.

  * How to Reproduce: Open an enchanting NPC or quest. Here's an option before you enchant. Use any skill to break the disable_itens; script. Ready now you can remove your item, add another one among others. I got NPCs that the staff provides here on rAthena and to remove an item before enchanting, you will get a new item then due to getitem2.
In my opinion it is a serious problem.

  * Official Information: You can not remove any item from the char when it is in NPCs, especially spells.

* **Modifications that may affect results**:

**Comment by ecdarreola** [comment]
Try this setting in conf/battle/items.conf

Find line:
`// Allow changing of equipment while interacting with NPCs? (Note 1)
// Default: yes
item_enabled_npc: yes
`

and change to:
`// Allow changing of equipment while interacting with NPCs? (Note 1)
// Default: yes
item_enabled_npc: no
`

Should fix the changing part.

**Comment by Badarosk0** [comment]
This solves the problem, but the script would be mocking when using disable_itens;

**Comment by petrecci** [comment]
Fix, by lemon
--- a/src/map/clif.cpp
+++ b/src/map/clif.cpp
@@ -12160,10 +12160,9 @@ void clif_parse_UseSkillToId(int fd, struct map_session_data *sd)
 			clif_msg(sd, WORK_IN_PROGRESS);
 			return;
 		}
-#else
+#endif
 		if (!sd->npc_item_flag || !(inf&INF_SELF_SKILL))
 			return;
-#endif
