### ISSUE TITLE
Shadow Chaser job quest issue

### ISSUE THREAD

**Issue by gladio78** [rathena/rathena#3278]
https://github.com/rathena/rathena/blob/e4eddc3e617bd5702f5ce29f605ee66207fe66b4/npc/re/jobs/3-2/shadow_chaser.txt#L1686-L1687

It should be "Blue Fire **on** Turtle Island third floor" instead of "Blue Fire **in** Turtle Island third floor" as reported [here on iRO](https://irowiki.org/wiki/Shadow_Chaser_Job_Change_Guide) and as for the solution of the enigma: 
e.g. 7 17 26 10 / 11 14 23 10 / 20 19 / 25 26 23 25 17 10 / 14 24 17 6 19 9 / 25 13 14 23 9 / 11 17 20 20 23] 
Where the key 5 (is random) so you have to subtract 5 from all number and find the letter based on the number

**Comment by Atemo** [comment]
https://github.com/rathena/rathena/blob/e4eddc3e617bd5702f5ce29f605ee66207fe66b4/npc/re/jobs/3-2/shadow_chaser.txt#L598
`set .@i, 9 + .@key01;`
`mes "" + .@i + " " + .@n + " ";` is 'in'
The sentence required match to the info given to the player
