### ISSUE TITLE
Cash points

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#3285]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/1b72f727b818e5ef6938ce6e1cd15ebe35b0e69c
* **Client Date**: Irrelevant
* **Server Mode**: RE
* **Description of Issue**: when you use the @cash + command with a very high value an overflow appears in the map_server, if you use @cash - with a very large value too.

@cash 11000000000000000000000000000000000000000000000
```
[Warning]: pc_getcash: Cash point overflow (cash=2147483647, have cash=2750, account_id=2000017, char_id=169091).
[Warning]: pc_getcash: Cash point overflow (cash=2147483647, have cash=2147483647, account_id=2000017, char_id=169091).
[Warning]: pc_getcash: Cash point overflow (cash=2147483647, have cash=2147483647, account_id=2000017, char_id=169091).
[Warning]: pc_getcash: Cash point overflow (cash=2147483647, have cash=2147483647, account_id=2000017, char_id=169091).
[Warning]: pc_getcash: Cash point overflow (cash=2147483647, have cash=2147483647, account_id=2000017, char_id=169091).
[Warning]: pc_getcash: Cash point overflow (cash=2147483647, have cash=2147483647, account_id=2000017, char_id=169091).
```
@cash -1000000000000000000000000000000000000000000000000000000
`[Error]: pc_paycash: Paying negative points (price=-2147483648, points=0, account_id=2000017, char_id=169091).`

**Comment by Lemongrass3110** [comment]
Intended behavior.

**Comment by admkakaroto** [comment]
ok '-'

**Comment by Lemongrass3110** [comment]
Since cash points are script variables they are bound to a limit of INT32_MAX(2147483647) when you add cash and INT32_MIN(-2147483648) when you remove cash.
Also they should never go below zero.

**Comment by admkakaroto** [comment]
Okay, I was just afraid that would cause some problem, but if you do not take that risk, then you're calm!
