### ISSUE TITLE
setitemscript bAllstats,99 = allstats -1

### ISSUE THREAD

**Issue by anacondaqq** [rathena/rathena#329]
## Technical Information
rAthena, pre-re, mmo.h 2010-07-30
latest git: (07 march 2015)

## Problem in screenshots:

![](http://i6.5cm.ru/i/cAjX.png)

1. I have accessory without bonuses (empty clip)
2. I have setup via script command next for this item:
>  .bonus$ =  "{ bonus bAllStats,99; }";
    setitemscript(2607,.bonus$,1);
    getitem 2607;
    equip 2607;
   
3. I equip this accessory, and i have next problem:
![](http://i6.5cm.ru/i/X93D.png)

4. I do @refresh, and i have good values
![](http://i6.5cm.ru/i/nGFN.png)

**Comment by nanakiwurtz** [comment]
But your ATK and Crit value are already correct, only the '-1' part which is incorrectly displayed.

**Comment by aleos89** [comment]
Tested and it worked just fine. The issue you have is that you are trying to set it to the OnEquip script. Not all script bonuses work here which is where your issue arises. Just make it:
```
setitemscript(2607,.bonus$);
```
This way it gets applied to the actual item's bonus part and it gets applied just fine. :)
