### ISSUE TITLE
Suggestion : What about Lapine System?

### ISSUE THREAD

**Issue by Sweet520** [rathena/rathena#3302]
Hi Guys

twRO and kRO have a Lapine system for item transformation, 
i.e. using 5 shadow equipment to get a random shadow equipment.

More information : 
twRO : https://ro.gnjoy.com.tw/notice/notice_view.aspx?id=1154
kRO : http://ro.gnjoy.com/news/update/View.asp?seq=184

I think it is a useful one to recycle costume, shadow equipment, enchant stones etc. random items.
It is more explicit and simple than the script.

**Comment by cydh** [comment]
I like this feature too, just like other RPG xd

**Comment by Everade** [comment]
Looking forward to it.
Probably one of the most requested features amongst a lot of players.

**Comment by M45T3Ryu** [comment]
Im bad translating but this is what I understand from the image.. yeah looks official to me


Collectibles box.
If you put 10 kinds of collectibles or 10 items into a box, you can get random consumables.
Only items marked 'sold to merchant merchants' are accepted as materials.
There may be occasional pretty good items coming out.
caution! - Only different kinds of items are received as materials.

Costume Enchant Stone Stone Box.
Costume Enchantment Stone is made of 3 pieces and receives 1 random enchantment stone.
Low chances that an enchanted stone can come out of an enchanted stone box.
caution! - Only different kinds of Costume Enchant Stone are received as materials.

Shadow box.
Use 3 or more shadows or random shadows.
Shadows that can not be obtained from a shadow cube may come out with a low probability.
Promotional shadows can not be used as a combination material.

Square below; 
Extension Box
One of the list below is added randomly!
Additional components

Box 1
```
 Deductive x1
[For sale]
Yellow Butterfly's Wings x3
DEX Decrement Potion X3
Remaining Card Concert (Two) x1
Remaining card concubine x1
[Non-boiling
Magical Candy x3
```
Box 2
```
White Slim Potion Box x1
Combat Manual × 2
INT Reduction Potion X3
Day card chip (armor) x1
Wide Card Chip (Weapon) x1
[Supplies]
Toxic candy x3
```

Box 3
```
[For sale]
Blue butterfly wings × 3
[For sale]
Bubble gum x2
STR Reduction Potion X3
Wide guard (shield) x1
Infinite Greed Scroll
1 hour box × 1
```

Box 4
```
[Non-fading]
Red Butterfly's Wings x3
Wings of Infinite Paris
1 day box x1
VIT Reduction Potion X3
Remaining card chip (hanging) x1
Jeremy's Beauty Coupon x1
```

Box 5
```
[For sale]
Abstract butterfly wings × 3
LUK Decrement Potion x3
AGI Reduction Potion X3
Remaining cardboard (shoes) x1
Life insurance certificate x3
```

**Comment by Lemongrass3110** [comment]
The problem is where to get them... i have no clue where to find them on kRO. 😐

**Comment by Sweet520** [comment]
@Lemongrass3110 

this clue?

[https://github.com/zackdreaver/ROenglishRE/blob/master/data/luafiles514/lua%20files/datainfo/lapineddukddakbox.lub](url)

**Comment by Everade** [comment]
If i'm not mistaken then there are premium versions from the cash shop.

**Comment by Lemongrass3110** [comment]
@Sweet520 it doesnt help. I need to get the items on kRO so I can trace the packets for it. And since I do not know where or how to get wny of them I cant start on this feature.

**Comment by Angelic234** [comment]
[https://github.com/HerculesWS/Hercules/pull/2336](url)
this one?

**Comment by Hope8888** [comment]
> 
> 
> [HerculesWS/Hercules#2336](https://github.com/HerculesWS/Hercules/pull/2336)
> this one?

@Lemongrass3110 👍

**Comment by sianromantic** [comment]
@Lemongrass3110 
@aleos89 
how to translation [HerculesWS / Hercules＃2336](https://github.com/HerculesWS/Hercules/pull/2336) for rAthena use ?
