### ISSUE TITLE
Extended Vending system

### ISSUE THREAD

**Issue by ryuma1922** [rathena/rathena#3304]
rAthena Hash: Latest (will check when i get home)
Client Date: 2017-06-14
Server Mode: Renewal
Description of Issue:
I set up Set up two system stores Zeny and Cash Shop and tested the items and searched for  ID items When to buy the end of the item.

`[Warning]: itembd_search: Item id 0 does not exists in the item_db. Using dummy data.`

**Comment by cydh** [comment]
This place is not for custom support. Please post your issue in forum section [SUPPORT & RELEASES > Source > Source Support](https://rathena.org/board/forum/35-source-support/)
