### ISSUE TITLE
EventNormalChance Weapon dont work

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#3305]
* **rAthena Hash**: 
https://github.com/rathena/rathena/commit/006efe11edf412eef6c07b2b20db84ed1da4f20e

* **Client Date**: 
2018

* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result: 
When you configure refine_db.yml for EventNormalChance the extra chance is not affecting or affecting it incorrectly.
1- Edit [event_refine_chance: yes] in item.conf.
2- Set up an extra chance for a weapon of any level.
3 - Restart the server.
4- Open the refineui refine your weapon to +15.
5- Get bradium and check the chance it will show.
6- It will not show the chance configured as Event.
 
  * Expected Result: 
It should show the same chance set at refining time.

  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment]
Refine UI is not in master yet. So this can't be an issue of 006efe1
