### ISSUE TITLE
Epiclesis Behavior

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#3308]
* **rAthena Hash**: Any
* **Client Date**: Irrelevant
* **Server Mode**: RE
* **Description of Issue**: the ability should relive dead players that are over effect area effect, but this is not happening.
  * Official Information: https://www.ragnaplace.com/iRO/skill/2044/Epiclesis
* Reproduce: Just use Epiclesis in a dead player.

kRO should have the same behavior.

**Comment by aleos89** [comment]
Tested on e832eb7, and unable to reproduce. The player was revived just fine. Keep in mind it doesn't revive players who die after it has been placed.

**Comment by admkakaroto** [comment]
ohhh, sorry man...sorry for this.
