### ISSUE TITLE
Shadow Chaser -> Skill: Auto shadow spell not working

### ISSUE THREAD

**Issue by vubach2912** [rathena/rathena#331]
After buff skill "Auto Shadow Spell", icon status this skill don't show in right bar & it not working when i attack player and monster

**Comment by reigneil** [comment]
Confirmed using git https://github.com/rathena/rathena/commit/ad8e22139f84323ec18addc0e51ac8849f965f30 Renewal, Client 2014-06-13

**Comment by cydh** [comment]
@reigneil don't confirm if u're using unsupported client @_@

**Comment by cydh** [comment]
should be fixed in 46f010cb28d3785d0c89e394b382a7e39f01a188
