### ISSUE TITLE
Map Crashed after clicking Title Achievement

### ISSUE THREAD

**Issue by bgamez23** [rathena/rathena#3315]
rAthena Hash: ec1d6d28d7dab2fce3c824c0c651f16c03ab79a1
Client Date: 2015-11-04aRagexe
Server Mode: 
Description of Issue: 
![image](https://user-images.githubusercontent.com/1854368/43366893-2cd0d3e4-9377-11e8-97af-05bbf7373bc2.png)

Result: Map Crashed after clicking Title.
Expected Result:
How to Reproduce: Adjust your base level to 99. then click the Title available on Title Tab. and map server will crashed.
Official Information:
Modifications that may affect results:

**Comment by JohnnyPlayy** [comment]
@bgamez23 Update your Visual studio, For the latest

**Comment by aleos89** [comment]
![image](https://user-images.githubusercontent.com/3521753/42789840-7b692d9a-8935-11e8-904d-6d19690c2bf0.png)
Tested on f85dc57. If you can give us a more appropriate crash log it could help. That scree shot doesn't really tell us the exact fault.

**Comment by anacondaqq** [comment]
Dear Aleos, you have a small name. Try to make any long name (20 characters)
for example abcdefghijklmnopqrstuv

**Comment by aleos89** [comment]
![image](https://user-images.githubusercontent.com/3521753/42792228-5a8f1dd4-8942-11e8-80d2-6b24cbf29bf3.png)
23 character name.

**Comment by admkakaroto** [comment]
I tested with custom title with a name of more than 20 characters and worked perfectly too.

**Comment by sader1992** [comment]
i did test it too and i have no problem
this maybe for the fact that he use vs2012 maybe he have some missing libraries but i don't know how vs could compile the server is there is something missing in his version

**Comment by bgamez23** [comment]
i use visual studio ultimate 2013 compiler

**Comment by bgamez23** [comment]
[
![ee](https://user-images.githubusercontent.com/1854368/43144201-1ee8fe32-8f8f-11e8-8f0b-724079ded5ce.jpg)
](url)

**Comment by aleos89** [comment]
That still isn't enough. This is just where it's crashing within the vector library. You need to view the call stack and go back to the last rAthena function it called. If you run in debug mode and crash, click the Retry button and it will take you to the call stack within MSVS.

**Comment by bgamez23** [comment]
up for this. im using this [Lightweight compiler for Windows](https://rathena.org/board/topic/111269-guide-lightweight-compiler-for-windows-for-replacement-heavy-visual-studio-ide-compile-rathena-faster-save-your-bandwidth-and-disk-space/) as compiler but still having same issue.

**Comment by bgamez23** [comment]
i just made a crashed dump files.
map-server.exe_180729_215610.dmp
![image](https://user-images.githubusercontent.com/1854368/43367113-8f9d4310-937a-11e8-997f-7e9c1c6134f3.png)

**Comment by aleos89** [comment]
So which is it? You're using the MSVS package or @anacondaqq's lightweight guide? If you're using the lightweight compiler it could be that you are missing a package or aren't pointing to the correct package.

**Comment by bgamez23** [comment]
Using VS2013 compiler and lightweight compiler the map crashee occured.but using the VS2017 there is no issue about it.

**Comment by aleos89** [comment]
```diff
 src/map/clif.cpp | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)

diff --git a/src/map/clif.cpp b/src/map/clif.cpp
index f3c3bca6f..a8cdc8596 100644
--- a/src/map/clif.cpp
+++ b/src/map/clif.cpp
@@ -19233,12 +19233,12 @@ void clif_parse_change_title(int fd, struct map_session_data *sd)
 	}else if( title_id <= 0 ){
 		sd->status.title_id = 0;
 	}else{
-		if (std::find(sd->titles.begin(), sd->titles.end(), title_id) == sd->titles.end()) {
+		if (std::find(sd->titles.begin(), sd->titles.end(), title_id) != sd->titles.end())
+			sd->status.title_id = title_id;
+		else {
 			clif_change_title_ack(sd, 1, title_id);
 			return;
 		}
-
-		sd->status.title_id = title_id;
 	}
 	
 	clif_name_area(&sd->bl);
```

Can you try this and let me know how it works for you?

**Comment by bgamez23** [comment]
nope. its not working. still got map crashed.

**Comment by aleos89** [comment]
At this point then it's something with your lightweight setup. You might need to go back and make sure you have the proper libraries installed and that you're pointing the installer to the appropriate location.

**Comment by anacondaqq** [comment]
The problem is not with lightweight setup. The problem exactly with something, which I don't know. I tried to help, and the bgamez23 has VS Studio 2013 on which he has the problems. On VS2017 he said to me that no problems at all, and when I was helping him to understand where is the problem, we got no crashes at all on VS2017. Lightweight setup (BuildTools) works perfectly fine.

**Comment by aleos89** [comment]
I use 2015 at home (the results I posted above). I'm not sure of anyone dev who is using 2013. Might have to create a VM to test then.

**Comment by Lemongrass3110** [comment]
Make sure you use the latest update of 2013. From what I can remember at least 2013 SP3 is required to build rA.
