### ISSUE TITLE
Guild Expansion Saving Level

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#3317]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/7a8ac464211d53bd11725d30d909a139db39e307
* **Client Date**: 2018-05-30
* **Server Mode**: RE
* **Description of Issue**: the problem is simple, if the player puts only 1 point or more, but do not put the 5 points and open the warehouse, the guild saves the amount of spaces and does not increase even more placing the rest of the points...
  * How to Reproduce:
1. Create a guild.
2. Level UP the guild.
3. Put 4 points expansion skill of guild storage, but it has to be less than 5, 4 or any value lower than that.
4. Now open the guild warehouse.
5. Close the warehouse.
6. Put remaining dots in the expansion ability.

**Players can not take items out of the warehouse.**

**Comment by BrOgBr** [comment]
Already fixed. oO

**Comment by admkakaroto** [comment]
The problem is caused by this commit.

**Comment by xTakami** [comment]
The same thing is happening to me, thanks for generating the report @admkakaroto
