### ISSUE TITLE
Homunculus Auto Feed 

### ISSUE THREAD

**Issue by yoonjunho72** [rathena/rathena#3318]
* **rAthena Hash**: ec1d6d28d7dab2fce3c824c0c651f16c03ab79a1

* **Client Date**: 2018-05-30

* **Server Mode**: Renewal

* **Description of Issue**: Homunculus Auto Feed seems not work
  * Result: 
  * Expected Result: 
  * How to Reproduce: Turn on `feature.homunculus_autofeed` (_conf/battle/feature.conf_) 
  * Official Information:
  

* **Modifications that may affect results**: But before this changes from https://github.com/rathena/rathena/blob/15f404e39cd137638bf840c3e26543872d5ba96b/src/map/homunculus.cpp about remove `feature.homunculus_autofeed_rate` look like fine
so i just add it back before **if (hd->homunculus.hunger < 0) {** (_homunculus.cpp_)
```
	if( battle_config.feature_homunculus_autofeed && hd->homunculus.autofeed && hd->homunculus.hunger <= 10 ){
		hom_food( sd, hd );
	}
```
value `10` if Homun Hunger bar below 11 will auto auto trigger autofeed or can add this feature back `feature.homunculus_autofeed_rate:` to easy config.

**Comment by admkakaroto** [comment]
I reversed this commit: https://github.com/rathena/rathena/commit/15f404e39cd137638bf840c3e26543872d5ba96b

and now it works, if I apply it stops working.

**Comment by Lemongrass3110** [comment]
I still could not fully reproduce this, but this is client related and is caused by some wrong/missing luas.
Nevertheless I will add the logic back, since it will not hurt anyone.
