### ISSUE TITLE
Ranger[Camouflage] vs Targeted Skills

### ISSUE THREAD

**Issue by reigneil** [rathena/rathena#332]
is this intended that you are not immune to monster targeted skill? i'm mean monster will not see you but can use targeted skill like Fire Bolt if you are in its range of attack.
based on this video kRO server you cannot be targeted if you are in Camouflage unless you are targeted before Camouflage take effect:
https://www.youtube.com/watch?v=QLzXzDhb2xA
credit to Ziu

**Comment by aleos89** [comment]
So you're saying that when Camouflage is active, you are being targeted by skills still?

**Comment by reigneil** [comment]
yes it is.
how to reproduce:
just use camouflage skill then summon monster id 1716 which is Acidus with Lightning Bolt skill for about 10 of it then see this monster targeting you with Lightning Bolt. what i know is only player can target you while using it but not monster.

**Comment by reigneil** [comment]
to fixed this there must be separate code for BL_MOB and BL_PC skill_id here:
if (tsc->data[SC_CAMOUFLAGE] && !(is_boss || is_detect) && !skill_id)

**Comment by reigneil** [comment]
further investigation shows that this behavior is not intended in the first place. /facepalm
http://forums.irowiki.org/showthread.php?t=95899
quote "Camouflage - Fixed a bug where a ranger in camouflage state could be targeted by single target skills." so... you may now remove !skill_id check now.
 if (tsc->data[SC_CAMOUFLAGE] && !(is_boss || is_detect))
return false;
or better to merge this code with the same behavior. BTW this fixed is not yet implemented in iRO...
http://forums.warpportal.com/index.php?/topic/130315-unofficial-ragnarok-what-to-look-forward-to-thread/

**Comment by aleos89** [comment]
Thanks for the confirmation. Was looking for that!

**Comment by RagnarokNova** [comment]
From what I can read on the skill, it's basically supposed to work like cloaking, but right now the skill is also making you immune to AoE damage.

**Comment by reigneil** [comment]
yeah @aleos89  forgot to change the property of it like cloaking... something like this.
case SC_CAMOUFLAGE:
	sc->option |= OPTION_CLOAK;
	opt_flag = 2;
	break;
