### ISSUE TITLE
Initial Release of Attendance Feature (error when enabled)

### ISSUE THREAD

**Issue by AzarthMZintos** [rathena/rathena#3323]
* **rAthena Hash**: 

* **Client Date**: 

* **Server Mode**: 

* **Description of Issue**: 
  * Result: after enable attendeance feature i try to start the server and login got this error: 
[Error]: make_listen_bind: bind failed (socket #1, error 10048: unknown error)!  
  * Expected Result: ...shoul work? i guess
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by AzarthMZintos** [comment]
Note: i try to serach for the erro and people talk about ports and stuffy but the server is offline and IF i turn the feature off it works

**Comment by Lemongrass3110** [comment]
The endpoint you are trying to use is already in use.
