### ISSUE TITLE
Boss Damage Update

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#3324]
* **rAthena Hash**: Any
* **Client Date**: Any
* **Server Mode**: RE
* **Description of Issue**: Now in the kRO the mvp's only receive 10% of the player's damage.
  * Official Information: http://ro.gnjoy.com/news/devnote/View.asp?category=2&seq=3891525&curpage=1

https://media.giphy.com/media/7zSzFATT4pVbJFpv6M/giphy.gif

**Comment by aleos89** [comment]
The Korean translation says _some MVP_. It says the ones who are reduced have a green aura, so I would assume this doesn't apply to all MVP then. We'll need info on which ones are affected.

**Comment by admkakaroto** [comment]
hmmm is now what i saw really seems to be, the mvp's get an icon with a different color to indicate this, i will try to get information and update here.

**Comment by aleos89** [comment]
Interesting. Thanks for the info!

**Comment by Asheraf** [comment]
This is still a sakray only patch I don't think it will pass at least in the current format (I tried to kill an mvp.. it's ridiculous) but who knows maybe they want to kill solo mvp farming or make it very end game.

**Comment by Lemongrass3110** [comment]
Maybe they just try it on more MVPs now and then only put it on special instances or hard modes etc.

**Comment by bruno199** [comment]
https://www.divine-pride.net/forum/index.php?/topic/3318-kro-mvp-bosses-adjustment/

**Comment by Lemongrass3110** [comment]
Putting this on hold until it gets merged from sakray to main.

**Comment by BrOgBr** [comment]
@Asheraf I was thinking that it can have a good side and a very bad one.
Transclasses will a very hard difficult to kill this MVPs, but it could "balance" the high 3rd's damage.
Unless I did misunderstood how it'll work. xD

@Lemongrass3110 On instances would be very nice.

**Comment by MrAntares** [comment]
If this gets implemented we will need an off scwitch for it, otherwise low player count and rate servers will rebel, starting with me :)

**Comment by AzarthMZintos** [comment]
Comment about what MrAntares, if possible will be nice to have a on/off switch and a way to include/turn off all/more mvp/boss, but that maybe be custom feature...

**Comment by admkakaroto** [comment]
@Atemo Let the boys dream!

**Comment by MrAntares** [comment]
We are only discussing the possibilities. It's nice to have a plan, in case this gets implemented ;)

**Comment by Lemongrass3110** [comment]
You know that **some** people get notifications for each comment you add or edit you do, do you?
It is nice that you are following recent kRO updates and raise our attention to it, but as Atemo said you might want to consider waiting until we address this issue in a pull request and tell us your wishes/give us your feedback when time comes.

Thanks for understanding.

**Comment by admkakaroto** [comment]
Here a little info:

https://www.youtube.com/watch?v=0vsKS6HeS9E


Credits: Ziu.

**Comment by cahya1992** [comment]
info :
https://www.divine-pride.net/forum/index.php?/topic/3318-kro-mvp-bosses-adjustment/

**Comment by qwerty7vp** [comment]
is this feature still on progress ?

**Comment by Surefirer** [comment]
I would love to see this feature to be implemented, please consider, Thank you.

**Comment by LordWhiplash** [comment]
The damage reduction effect from
SonaSonaSona PR was working fine in the last time I've checked... Lapine system is been developed by Cydh in other PR (did not testes ter)... But would be really great to see the new skills for MVPs...
