### ISSUE TITLE
Can't access attendance UI feature

### ISSUE THREAD

**Issue by hendra814** [rathena/rathena#3326]
* **rAthena Hash**: lastest

* **Client Date**: 20180307 and 20180530

* **Server Mode**: renewal

* **Description of Issue**: I already enable it via feature.conf (already tried use import folder too) and edit start date and end date in attendance.yml (already tried use import folder too) but attendance UI can't be access
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**: 
  
  
![image](https://user-images.githubusercontent.com/9587609/42867196-0a42f2f8-8a99-11e8-9ce6-c7134967c2fd.png)

![image](https://user-images.githubusercontent.com/9587609/42867215-188c84e6-8a99-11e8-82bc-20ab59c30a08.png)

![screenrathena076](https://user-images.githubusercontent.com/9587609/42867084-b3906756-8a98-11e8-9dec-bba0f0b05753.jpg)

**Comment by BrOgBr** [comment]
Change groups.conf
attendance = true

**Comment by Lemongrass3110** [comment]
Attendance is disabled for any GM level group by default. Please review your groups.conf as @BrOgBr already said.

**Comment by hendra814** [comment]
@BrOgBr 
Already for group 0, but it's make all character with group 0 can't access into game.
![image](https://user-images.githubusercontent.com/9587609/42868144-c534875a-8a9b-11e8-8ed8-a683dc518e03.png)

but for GM account can't be access and i think for GM all permission already true
`id: 99
	name: "Admin"
	level: 99
	inherit: ( "Support", "Law Enforcement" )
	commands: {
		/* not necessary due to all_commands: true */
	}
	log_commands: true
	permissions: {
		can_trade: true
		can_party: true
		all_skill: false
		all_equipment: false
		skill_unconditional: false
		use_check: true
		use_changemaptype: true
		all_commands: true
		channel_admin: true
		can_trade_bounded: true
		item_unconditional: false
		bypass_stat_onclone: true
		bypass_max_stat: true
		/* all_permission: true */
`
@Lemongrass3110 
wait don't close my issue. T_T

**Comment by secretdataz** [comment]
It's likely that you broke the file's formatting so the whole file didn't get parsed.

**Comment by hendra814** [comment]
@secretdataz 
I think it's not. here my group.conf
https://pastebin.com/CHqMhwKK

**Comment by secretdataz** [comment]
Please use other channels to get support when it comes to user errors~
