### ISSUE TITLE
Rosário da Guarda Real(ID:19318) item missing from db and the combo with Imperial Feather(18823)

### ISSUE THREAD

**Issue by AzarthMZintos** [rathena/rathena#3327]
* **rAthena Hash**: 

* **Client Date**: 

* **Server Mode**: 

* **Description of Issue**: 
  * Result: The item and combo are missing
  * Expected Result: The item should existing in the db and the combo
  * How to Reproduce: Look at the DB
  * Official Information: https://www.divine-pride.net/database/item/19318 I dont play official server so... NOTE: The item is from BRO with you change your server at divine to kro or iro nothing shows up, but the item dont erase any item so i think it should exist in the db, and the combo
  

* **Modifications that may affect results**:

**Comment by Atemo** [comment]
This item doesn't exist in kRO, client side.

**Comment by AzarthMZintos** [comment]
anyone one to explain why JRO ITEm and twro itens are avaible but BRO items will not be in the database? ty

**Comment by Daegaladh** [comment]
rAthena is based on kRO an iRO.
Some jRO and twRO items are available because they're also on kRO.
If you want your server to have bRO items you can add them by yourself on import files, or just move to brAthena.
