### ISSUE TITLE
MVP walking logic problem.

### ISSUE THREAD

**Issue by anacondaqq** [rathena/rathena#333]
![](http://i6.5cm.ru/i/NTqv.jpg)

Red = map borders
Blue = MVP
Green = Player

when a monster is in the corner, it is not possible to deduce therefrom back.

The problem appeared after the last 20 updates.
I will try to gather more information about this issue, and confirm this topic.

**Comment by Playtester** [comment]
I'm not sure what you mean with "not possbible to deduce there from back".

**Comment by anacondaqq** [comment]
@Playtester mvp can't move. Imposible to move our from this place. MVP not follow player.

**Comment by anacondaqq** [comment]
okay, i'm closing this issue, because i think this is the same problem like this one: https://github.com/rathena/rathena/issues/224
