### ISSUE TITLE
[비매품]전투교범&풍선껌 (ID:22979) Item missing script

### ISSUE THREAD

**Issue by AzarthMZintos** [rathena/rathena#3331]
* **rAthena Hash**: Last

* **Client Date**: 2018-05-30b

* **Server Mode**: Renewal

* **Description of Issue**: The item exist in the server side(db) but is without script
  * Result: You can use the item and get it from attendance feature but it dont work
  * Expected Result: The item should  work/exist complete in the DB
  * How to Reproduce: check db or get the item in the game using `@item`
  * Official Information: https://www.divine-pride.net/database/item/22979
  

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment]
Almost all of the items I added for attendance are like this.
That's why I wrote dummy data in the pull request.
