### ISSUE TITLE
Server crash after destroying the party

### ISSUE THREAD

**Issue by teededung** [rathena/rathena#3336]
hash: 1d88575f90b5f572cffba4a361f3028003008ffb
client date: 20170614

clif.cpp

The lines provoke map-server crash:

```
		if( (battle_config.bg_flee_penalty != 100 || battle_config.gvg_flee_penalty != 100) &&
			(map_flag_gvg(sd->state.pmap) || map_flag_gvg(sd->bl.m) || map_getmapflag(sd->state.pmap, MF_BATTLEGROUND) || map_getmapflag(sd->bl.m, MF_BATTLEGROUND)) )
			status_calc_bl(&sd->bl, SCB_FLEE); //Refresh flee penalty
```

when commented, no crash happen.

Extra info:

```

		/**
		 * Get a key-value pair and return the key value
		 * @param map: Map to search through
		 * @param key: Key wanted
		 * @param defaultValue: Value returned if key doesn't exist
		 * @return Key value on success or defaultValue on failure
		 */
		template <typename K, typename V> V map_get(std::map<K, V>& map, K key, V defaultValue) {
			auto it = map.find(key); //  <-------------------- this one

			if (it != map.end())
				return it->second;
			else
				return defaultValue;
		}

```

When key = MF_GVG on line above.

```

How to reproduce

1.) Create any char
2.) "`@warp bif_fild01,158,340`"
3.) create party (`@party fsdfsd`)
4.) create instance and login to the instance
5.) inside instance do /leave to leave party
6.) boom map-server crash

Which is provoked by line below:
```
		if( (battle_config.bg_flee_penalty != 100 || battle_config.gvg_flee_penalty != 100) &&
			(map_flag_gvg(sd->state.pmap) || map_flag_gvg(sd->bl.m) || map_getmapflag(sd->state.pmap, MF_BATTLEGROUND) || map_getmapflag(sd->bl.m, MF_BATTLEGROUND)) )
			status_calc_bl(&sd->bl, SCB_FLEE); //Refresh flee penalty

```


When the line above is commented in clif.cpp, no crash happen.

### Also, please note:
- clean rAthena without any modifications
- tested on ranger

**Comment by yoonjunho72** [comment]
tested on 20170614 and 20180620, hmm there is no crash i create an instance and leave party with **/leave** command inside the instance.

**Comment by teededung** [comment]
@yoonjunho72 Did you go into the map of instance?

**Comment by Lemongrass3110** [comment]
Fixed your hash.

**Comment by teededung** [comment]
![2018-07-20_16-36-22](https://user-images.githubusercontent.com/9781158/42995434-0f8fdbf6-8c3b-11e8-8be3-be0b6d28d76b.png)
It does not really crash, but it disconnects the server

**Comment by anacondaqq** [comment]
check atccommand log, maybe someone using `@mapexit`?

**Comment by teededung** [comment]
@anacondaqq I tested in localhost. 
Before I pull this https://github.com/rathena/rathena/commit/a942853d55dd0e96ff98e6c352e2c2a9e000ea86, it works fine.

**Comment by anacondaqq** [comment]
Are you using Windows, right? Compile it in debug mod, and run it via map-server.exe, char-server.exe, login-server.exe, and if map-server will crash, it will ask you to open it in Visual Studio. Do it, and then post information about what you will see from Visual Studio output if the crash will happen (line what exactly provoke the crash).

**Comment by teededung** [comment]
@anacondaqq Thanks. This is what I see on Visual Studio
![2018-07-20_21-56-48](https://user-images.githubusercontent.com/9781158/43009508-1eb3be18-8c68-11e8-8023-aa2fdda4c03c.png)

**Comment by anacondaqq** [comment]
@teededung now, click break. And on right pane (at top) you will see a menu of functions which provoke the crash (callback), click on it, and posts here which function were called before this one, and which before function before, and extra. Plus add lines of code too. It will be very useful. Current information not bad, but not give a lot of information, because hard to understand inside what file it is, what exactly did the problem, so on, (you cutted too much your VS Studio Window) just hide your username/pass with [sharex](https://getsharex.com) tool

**Comment by teededung** [comment]
Sorry I'm not familiar with this stuff. Here is my attempts :(

![2018-07-20_22-43-31](https://user-images.githubusercontent.com/9781158/43011745-8cf65420-8c6e-11e8-843c-253b1d0aa971.png)
![2018-07-20_22-44-06](https://user-images.githubusercontent.com/9781158/43011749-8eabe942-8c6e-11e8-9171-47eaf5fff1fa.png)
![2018-07-20_22-44-36](https://user-images.githubusercontent.com/9781158/43011753-905c5786-8c6e-11e8-9e96-90c8cea18bfd.png)

**Comment by anacondaqq** [comment]
@teededung do you have discord? Contact me here: anacondaqqq#5637
If you will contact me in less then 60 hours before I'll go sleep, I maybe will help you to solve the issue.

**Comment by teededung** [comment]
pew pew pew

**Comment by anacondaqq** [comment]
Topic updated. Please read above. tested on clean rAthena.
