### ISSUE TITLE
Airship Assault Mob wrong stat

### ISSUE THREAD

**Issue by gladio78** [rathena/rathena#3337]
Hi,
the following mobs seems to not have any stats in the database/tx, plus other wrong attributes this is result in the instance to be really easy to be completed , especially for the lack of hit from the enemy.
3175, 3176, 3177, 3178, 3179, 3180, 3181
Double checked with divine-pride database

**Comment by Atemo** [comment]
Fixed in https://github.com/rathena/rathena/commit/7717c1e6bc8f067625bbf588a1b07c58f9f8ebaf

**Comment by CyberDevil75** [comment]
I noticed that all the skills of the mobs are also missing. at least the bosses 3180 and 3181...

3180 | GreatDragon@FIREBALL | chase | 17 | 5 | 10000 | 0 | 30000 | yes | target | always | 0 | NULL | NULL | NULL | NULL | NULL | 6 | NULL
3180 | GreatDragon@FIREBALL | attack | 17 | 5 | 10000 | 0 | 30000 | yes | target | always | 0 | NULL | NULL | NULL | NULL | NULL | 6 | NULL
3181 | CaptainFelock@DOUBLESTRAFF | chase | 46 | 10 | 2000 | 0 | 30000 | yes | target | always | 0 | NULL | NULL | NULL | NULL | NULL | 6 | NULL
3181 | CaptainFelock@DOUBLESTRAFF | attack | 46 | 10 | 2000 | 0 | 30000 | yes | target | always | 0 | NULL | NULL | NULL | NULL | NULL | 6 | NULL
3181 | CaptainFelock@NPC_COMBOATTACK | chase | 171 | 5 | 2000 | 2500 | 30000 | yes | target | always | 0 | NULL | NULL | NULL | NULL | NULL | 6 | NULL
3181 | CaptainFelock@NPC_COMBOATTACK | attack | 171 | 5 | 2000 | 2500 | 30000 | yes | target | always | 0 | NULL | NULL | NULL | NULL | NULL | 6 | NULL
3181 | CaptainFelock@ARROWREPEL | chase | 148 | 1 | 500 | 1500 | 5000 | yes | target | always | 0 | NULL | NULL | NULL | NULL | NULL | 6 | NULL
3181 | CaptainFelock@ARROWREPEL | attack | 148 | 1 | 500 | 1500 | 5000 | yes | target | always | 0 | NULL | NULL | NULL | NULL | NULL | 6 | NUL

**Comment by Atemo** [comment]
Where did you get the monsters skills? Theses monsters don't have skills according to aegis.
