### ISSUE TITLE
Slaves appear in a larger amount than it should be.

### ISSUE THREAD

**Issue by anacondaqq** [rathena/rathena#334]
Problem
=======
Slaves appear in a larger amount than it should be.

Video
=====
https://www.youtube.com/watch?v=hTcXFkbj1tE&feature=youtu.be

More Details
==========
1. This problem appeared after the February updates. (I do not know because of what it is)
2. applicable for All monsters who have skills: summon and follow, and call slave
3. Imposible to reproduce by @monster or @spawn commands. (it's happened after some time)

Technical Information
=================
* rAthena with updates (15.03.2015)
* Pre-renewal
* 2010-07-30 game client, packet_ver: 25
* > // Dynamic Mobs Options
// Use dynamic mobs? (recommended for small-medium sized servers)
dynamic_mobs: no

**Comment by anacondaqq** [comment]
Video Proof: https://www.youtube.com/watch?v=e_zCcMhCGbU

**Comment by anacondaqq** [comment]
i did reopen this issue. I did add extra information and video about the problem.

**Comment by aleos89** [comment]
I'm going to do some testing on this, but I haven't noticed this issue yet and I've had a server running for a few days. I'd say the only difference is I don't have dynamic mobs turned off.

**Comment by anacondaqq** [comment]
i'm closing it now, i can't reproduce this too. If i will have problems again , i will reopen this issue.
