### ISSUE TITLE
Dimensional Travel Bug

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#3341]
* **rAthena Hash**: ec1d6d2

* **Client Date**: 20170517RE

* **Server Mode**: RENEWAL

* **Description of Issue**: 
  * Result:  Sonia and Firepit Does not appear on the map moro_vol
  * Expected Result:  Sonia and Firepit appear on the map moro_vol https://irowiki.org/wiki/Dimensional_Travel
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by doroteh** [comment]
i can't finish dimensional travel quest, cz i can't find any monster in the map
https://imgur.com/z5mSHQ7
https://imgur.com/DMom5AE
@Atemo

**Comment by Atemo** [comment]
Implemented in https://github.com/rathena/rathena/pull/3002
