### ISSUE TITLE
Memory manager: args of aFree

### ISSUE THREAD

**Issue by botka4aet** [rathena/rathena#335]
Rev. 17717

[Error]: Memory manager: args of aFree 0x053A06C8 is invalid pointer server\src\map\script.c line 3160

void script_free_code(struct script_code* code)
{
	script_free_vars( code->script_vars );
------>	aFree( code->script_buf );
	aFree( code );
}

What i do - enable only PRE, write script with lang menu and translate 1 script

Here src, db and npc - https://drive.google.com/file/d/0B_AO3jZJUz81bjhfZmlpVG13NEE/view?usp=sharing

Trying to create git hash but...

upd. [Error]: Memory manager: args of aFree 0x053A08D8 is invalid pointer server\src\map\script.c line 3160

**Comment by aleos89** [comment]
The only thing I can think of right now is to add a check to make sure the variable code has valid data before we free it.
