### ISSUE TITLE
SC_MAXIMIZEPOWER Bug

### ISSUE THREAD

**Issue by LolyAll** [rathena/rathena#3355]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/dc413a3c572a421406159f70cf070a39f8f28824
* **Client Date**: 2017-05-30
* **Server Mode**: RE
* **Description of Issue**: the skill bonus is not working.
  * How to Reproduce: Just activate the skill and attack the monsters, you will note that your damage will not increase.

**Comment by LolyAll** [comment]
Yes, the weapon is not refined, if you want I can post test with images.

**Comment by admkakaroto** [comment]
@cydh I confirm the problem.
The problem started after this commit. https://github.com/rathena/rathena/commit/dc413a3c572a421406159f70cf070a39f8f28824

To reproduce, it's simple, equip an Axe, start attacking a monster, activate 'Power Maximize' skill.

Your damage will not change.

![bs_maximize_0](https://user-images.githubusercontent.com/6227618/44950566-6ff0b580-ae21-11e8-8b0d-48bd5616194d.png)


![bs_maximize_1](https://user-images.githubusercontent.com/6227618/44950569-7ed76800-ae21-11e8-8330-aeef67671205.png)

**Comment by cydh** [comment]
Tested and this is invalid. Maximize power makes the attack to its atkmax.
The atkmin to atkmax is specified by weapon base attack and weapon level and the range is gettings lower for lv 1 weapon and lower weapon base dmg.

So I'd like to ask u to test using different weapon level with lowest and and highest weapon base dmg, and set low ur str to 1

**Comment by jezznar** [comment]
@cydh id rather test it with 1 dex and add 4 phreeonis for hitrate. This bec min and max atk difference will be higher with lower dex

**Comment by aleos89** [comment]
Unable to reproduce on b211d84. As @cydh stated, the atk_min = atk_max. After using Maximize Power my damage didn't fluctuate and was always at the peak of my normal attacks prior to using the skill.
