### ISSUE TITLE
Acquired achievements lost

### ISSUE THREAD

**Issue by teededung** [rathena/rathena#3356]
* **rAthena Hash**: 584fcac43a13381d74374cf8835b2d2b077913b6

* **Client Date**: 20170614

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Acquired achievements lost
  * Expected Result: No lost achievements 
  * How to Reproduce: Open the achievements dialog and check those achievements in attached an image below

![2018-07-27_16-44-30](https://user-images.githubusercontent.com/9781158/43314485-44c9057c-91bd-11e8-9fcc-6d3f967d008b.jpg)

My current zeny of my char is 1 billion and all of achievements are not completed. 
I also use custom achievements in imported folder and they are lost either.

**Comment by Lemongrass3110** [comment]
Uhm I dont know if you actually read what is standing there, but it is not about your character's zeny, but about the item price.

**Comment by aleos89** [comment]
As @Lemongrass3110 stated, those achievements are based on the value of the item the player gains, not how much Zeny the player has on them.
