### ISSUE TITLE
instance make map-server error or crash and character cant move or move smooth after enter instances

### ISSUE THREAD

**Issue by Angelic234** [rathena/rathena#3359]
* **rAthena Hash**: 584fcac

* **Client Date**: 20180621

* **Server Mode**: RE

* **Description of Issue**: 
  * Result: 
instance make map-server error or crash and character cant move or move smooth after enter instances
  * Expected Result: 
  * How to Reproduce: 
1. create an instance
2. enter instance
3. instance make map-server error or crash and character cant move or move smooth after enter instances
4. @mapexit
5. map-server [Warning]: Memory leak detected at ERS 'instance.cpp::instance_maps_ers', 1 objects not freed.
rAthena Hash 62ac5be had no this bug
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by sader1992** [comment]
what the instance you are using ?
why i feel like you added a custom instance script without adding the instance it self into the db files xD ?

**Comment by Angelic234** [comment]
I test it using Old Glast Heim instance.
