### ISSUE TITLE
Compiling warning

### ISSUE THREAD

**Issue by lelouch22** [rathena/rathena#336]
pc.c: In function ‘pc_checkskill’:
pc.c:5524: warning: unused variable ‘i’
        CC      pc_groups.c
        CC      pet.c
        CC      quest.c
        CC      script.c
        CC      searchstore.c
        CC      skill.c
skill.c: In function ‘skill_parse_row_requiredb’:
skill.c:19989: warning: unused variable ‘skill_id’
skill.c: At top level:
skill.c:222: warning: ‘skill_chk2’ defined but not used
skill.c: In function ‘skill_unitsetting’:
skill.c:12083: warning: array subscript is above array bounds

**Comment by reigneil** [comment]
Duplicate report: https://github.com/rathena/rathena/issues/309
