### ISSUE TITLE
[Error] Skill '%d' is undefined! (skill list inside)

### ISSUE THREAD

**Issue by anacondaqq** [rathena/rathena#337]
> [Error]: Skill '1542' is undefined! skill.c:219::skill_chk
[Error]: Skill '1542' is undefined! skill.c:219::skill_chk
[Error]: Skill '1028' is undefined! skill.c:219::skill_chk
[Error]: Skill '1542' is undefined! skill.c:219::skill_chk
[Error]: Skill '1285' is undefined! skill.c:219::skill_chk
[Error]: Skill '1542' is undefined! skill.c:219::skill_chk
[Error]: Skill '1285' is undefined! skill.c:219::skill_chk
[Error]: Skill '1542' is undefined! skill.c:219::skill_chk
[Error]: Skill '1029' is undefined! skill.c:219::skill_chk
[Error]: Skill '1542' is undefined! skill.c:219::skill_chk

Skill.c 219 line
------------------

> 217: /// out of bounds error checking [celest]
218: static void skill_chk(uint16 *skill_id) {
219: 	*skill_id = skill_get_index(*skill_id); // checks/adjusts id
220: }

**Comment by aleos89** [comment]
Do you have any custom skills? Do you know what item (that gives a skill) or skill would be causing this?

**Comment by Playtester** [comment]
Yeah, those skills don't seem to exist and neither in mob_skill_db nor in item_db I can find any reference to them.

**Comment by anacondaqq** [comment]
I can't find them too. That's why i did make a report.
But if this is NOT for example skill, and this is for example mobid?) That will be very funny

**Comment by cydh** [comment]
> But if this is NOT for example skill, and this is for example mobid?) That will be very funny

I wonder u reply the question that __u have custom skill or not__. If it's not custom skill, what are u use? pre-re or re? If not custom, and it's error because there's function that skill_index instead of skill id in any `skill_get_****` function, so if it's not custom, I can simply check that number is index of which skill.

well, seems, better we change the `skill_get_*****` function first for fetching the real function who use it (since `skill_chk` is used by ``skill_get_*****`), when skill_get_index is failed, should throw the function that use `skill_get_*****` instead of `skill_chk` location.

**Comment by anacondaqq** [comment]
Please sorry, my english very bad.
I want say:

1.  I do not have any CUSTOM skills
2. I do NOT find any skills with these ID's in skill_db, mob_skill_db, etc files.

**Comment by cydh** [comment]
I did this
````
ShowDebug("idx:1542 id:%d %s %s\n", skill_idx2id(1542), skill_get_name(skill_idx2id(1542)), skill_get_name(1542));
ShowDebug("idx:1028 id:%d %s %s\n", skill_idx2id(1028), skill_get_name(skill_idx2id(1028)), skill_get_name(1028));
ShowDebug("idx:1285 id:%d %s %s\n", skill_idx2id(1285), skill_get_name(skill_idx2id(1285)), skill_get_name(1285));
ShowDebug("idx:1029 id:%d %s %s\n", skill_idx2id(1029), skill_get_name(skill_idx2id(1029)), skill_get_name(1029));
````

resulted
````
(03/23/2015 23:32:15) [ Error ] : Skill '1542' is undefined! g:\game\ro\ro-server-rathena\!rathenaupdatedgit\#1\src\map\skill.c:205::skill_get_name
(03/23/2015 23:32:15) [ Debug ] : idx:1542 id:0  
(03/23/2015 23:32:15) [ Error ] : Skill '1028' is undefined! g:\game\ro\ro-server-rathena\!rathenaupdatedgit\#1\src\map\skill.c:205::skill_get_name
(03/23/2015 23:32:15) [ Debug ] : idx:1028 id:8218 ML_SPIRALPIERCE 
(03/23/2015 23:32:15) [ Error ] : Skill '1285' is undefined! g:\game\ro\ro-server-rathena\!rathenaupdatedgit\#1\src\map\skill.c:205::skill_get_name
(03/23/2015 23:32:15) [ Debug ] : idx:1285 id:0  
(03/23/2015 23:32:15) [ Error ] : Skill '1029' is undefined! g:\game\ro\ro-server-rathena\!rathenaupdatedgit\#1\src\map\skill.c:205::skill_get_name
(03/23/2015 23:32:15) [ Debug ] : idx:1029 id:8219 ML_DEFENDER 
````
placed in the end of `skill.c::skill_readdb()`

**Comment by anacondaqq** [comment]
i do not see it anymore, if i will again find this error in map-server log, i will reopen this issue.
For now, i'm closing that.

**Comment by hnomkeng** [comment]
same issue.
![untitled](https://cloud.githubusercontent.com/assets/9112684/15426046/37f4899c-1eb6-11e6-8c6e-b4424e1b0f91.jpg)
