### ISSUE TITLE
Unable moving character and keeping lag after using @spawn command

### ISSUE THREAD

**Issue by teededung** [rathena/rathena#3370]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/3165e521237c50e8053723639e2a74c8353f36e1

* **Client Date**: 20170614

* **Server Mode**: Both

* **Description of Issue**: 
  * Result: Unable moving character and keeping lag after using ```@spawn``` command
  * Expected Result: No lag
  * How to Reproduce: ```@spawn orc_lady 100```
 
Test on clean rAthena. When I switch back to https://github.com/rathena/rathena/commit/7717c1e6bc8f067625bbf588a1b07c58f9f8ebaf it turns to normal.

**Comment by aleos89** [comment]
What environment are you testing this on?

**Comment by teededung** [comment]
I tested on Windows  @aleos89
