### ISSUE TITLE
Instruments don't get wATK from DEX

### ISSUE THREAD

**Issue by Rayvis** [rathena/rathena#3371]
* **rAthena Hash**: current

* **Client Date**: any

* **Server Mode**: Renewal

* **Description of Issue**: DEX status points do not increase weapon attack for Instruments/whips, because their range is < 4
  * Result: Minstel/Wanderer have to invest points in STR to raise their wATK
  * Expected Result: Instruments should behave like Bows/Guns and increase wATK through DEX
  * How to Reproduce: 
Put on a musical instrument and invest points into DEX, your status atk will go up by 1 for each point﻿,﻿ your wATK will not change. Put some points into STR, your status attack will change by 1 for every 5 points of STR but (!) your wATK will also increase by 1﻿ for every 2﻿-﻿﻿3 points of STR﻿.

  * Official Information: I only know about iRO wiki stating instruments rely on DEX for wATK:

https://irowiki.org/wiki/Stats#Primary_Stats

Check out the "DEX" part.

Playtester has already pointed out in the support section (https://rathena.org/board/topic/114664-instruments-dont-get-watk-from-dex/#comment-342119) that the reason is this check:

**if (wa.﻿﻿﻿range > 3** && !pc_checkskill(sd, SU_SOULATTACK))
		str = sd->﻿base_status.dex;﻿

If someone can confirm iRO info, you may want to add an exception for instruments/whips, as their range is not > 3 and thus fails the check.

**Comment by aleos89** [comment]
Might be best to do a weapon type check instead.
