### ISSUE TITLE
Add packet support for 2018-07-XX

### ISSUE THREAD

**Issue by Haikenz** [rathena/rathena#3376]
rA does not work with clients above 2018-06-21, if you try to use a client that is newer than this one, npcs, warps, and mobs disappear.

I had been commenting on the Discord channel on the rA, and **4141** mentioned that rA needs this update in order to run the new clients.

Pull 1: https://github.com/HerculesWS/Hercules/pull/2095
Pull 2: https://github.com/HerculesWS/Hercules/pull/2126
Pull 3: https://github.com/HerculesWS/Hercules/pull/2139

**Comment by Lemongrass3110** [comment]
Why have I known that this issue will come up after reading your chat today? :-D

**Comment by sctnightcore** [comment]
use **ISSUE_TEMPLATE**

**Comment by JohnnyPlayy** [comment]
You're going to have to make some changes in rathena.

**Comment by Haikenz** [comment]
No news yet about adding new packets to new clients?
