### ISSUE TITLE
Mail Notification

### ISSUE THREAD

**Issue by bgamez23** [rathena/rathena#3377]
* **rAthena Hash**: 68fccf447b3c9a2aa90a3de7bdc10856400635bd

* **Client Date**: 2017-06-14bRagexeRE

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: The N notification for mail is not remove even you open the email or even you already get the item.
  * Expected Result: N icon for mail
  * How to Reproduce: send an email to your self using RodEx. you will get the N icon on your email. close the RodEx interface. use `@refresh` you will get the notification N icon. open the email. and get the item. the N icon still there.
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by AzarthMZintos** [comment]
use refresh at the mail window

**Comment by anacondaqq** [comment]
Any progress with this?

**Comment by aleos89** [comment]
As of b211d84, I was unable to reproduce this. It most likely got fixed at some point during the packet updates.
