### ISSUE TITLE
ClaymoreTrap / BlastMine in pre-renewal divide by 0

### ISSUE THREAD

**Issue by alastaire61** [rathena/rathena#3379]
* **Client Date**: 2013-08-07

* **Server Mode**: Pre-Renewal

* **Description of Issue**: 
  * Result: Map server: [Error]: 0 enemies targeted by 123:HT_CLAYMORETRAP, divide per 0 avoided!
  * Expected Result: No error
  * How to Reproduce: Use claymore trap when packing many monsters. I tried changing my pre-renewal formula adapting to float numbers:

case HT_CLAYMORETRAP:
			md.damage = (int64)(skill_lv * ((float)sstatus->dex / 2.0 + 75.0) * (100.0 + (float)sstatus->int_) / 100.0);
			break;

But it did not work, I don't really know where the dividing by zero comes.

I am using the fixed line for skill_db:

122,3,6,2,4,0xC6,1,5,1,no,0,0x80,0,misc,0,0x3800,	HT_BLASTMINE,Blast Mine
123,3,6,2,3,0xC6,2,5,1,no,0,0x40080,0,misc,0,0x3800,	HT_CLAYMORETRAP,Claymore Trap

**Comment by cydh** [comment]
if you're reviewing/testing still-opened PR, please give the report there. :D
#3373

**Comment by alastaire61** [comment]
@cydh  done
