### ISSUE TITLE
Mapflag warning after enabling PK Mode

### ISSUE THREAD

**Issue by lelouch22** [rathena/rathena#3382]
* **rAthena Hash**: 68fccf447b3c9a2aa90a3de7bdc10856400635bd

* **Client Date**: 2014-10-22bRagexe

* **Server Mode**: Pre-Renewal

* **Description of Issue**: After i enable the PK Mode this warning message shows up on the map server
  * Result: 
> [Warning]: npc_parse_mapflag: Unable to set PvP and GvG(null) Castle flags for the same map! Removing PvP flag from aldeg_cas01.
[Warning]: npc_parse_mapflag: Unable to set PvP and GvG(null) Castle flags for the same map! Removing PvP flag from aldeg_cas02.
[Warning]: npc_parse_mapflag: Unable to set PvP and GvG(null) Castle flags for the same map! Removing PvP flag from aldeg_cas03.
[Warning]: npc_parse_mapflag: Unable to set PvP and GvG(null) Castle flags for the same map! Removing PvP flag from aldeg_cas04.
[Warning]: npc_parse_mapflag: Unable to set PvP and GvG(null) Castle flags for the same map! Removing PvP flag from aldeg_cas05.
[Warning]: npc_parse_mapflag: Unable to set PvP and GvG(null) Castle flags for the same map! Removing PvP flag from gefg_cas01.
[Warning]: npc_parse_mapflag: Unable to set PvP and GvG(null) Castle flags for the same map! Removing PvP flag from gefg_cas02.
[Warning]: npc_parse_mapflag: Unable to set PvP and GvG(null) Castle flags for the same map! Removing PvP flag from gefg_cas03.
[Warning]: npc_parse_mapflag: Unable to set PvP and GvG(null) Castle flags for the same map! Removing PvP flag from gefg_cas04.
[Warning]: npc_parse_mapflag: Unable to set PvP and GvG(null) Castle flags for the same map! Removing PvP flag from gefg_cas05.
[Warning]: npc_parse_mapflag: Unable to set PvP and GvG(null) Castle flags for the same map! Removing PvP flag from payg_cas01.
[Warning]: npc_parse_mapflag: Unable to set PvP and GvG(null) Castle flags for the same map! Removing PvP flag from payg_cas02.
[Warning]: npc_parse_mapflag: Unable to set PvP and GvG(null) Castle flags for the same map! Removing PvP flag from payg_cas03.
[Warning]: npc_parse_mapflag: Unable to set PvP and GvG(null) Castle flags for the same map! Removing PvP flag from payg_cas04.
[Warning]: npc_parse_mapflag: Unable to set PvP and GvG(null) Castle flags for the same map! Removing PvP flag from payg_cas05.
[Warning]: npc_parse_mapflag: Unable to set PvP and GvG(null) Castle flags for the same map! Removing PvP flag from prtg_cas01.
[Warning]: npc_parse_mapflag: Unable to set PvP and GvG(null) Castle flags for the same map! Removing PvP flag from prtg_cas02.
[Warning]: npc_parse_mapflag: Unable to set PvP and GvG(null) Castle flags for the same map! Removing PvP flag from prtg_cas03.
[Warning]: npc_parse_mapflag: Unable to set PvP and GvG(null) Castle flags for the same map! Removing PvP flag from prtg_cas04.
[Warning]: npc_parse_mapflag: Unable to set PvP and GvG(null) Castle flags for the same map! Removing PvP flag from prtg_cas05.
[Warning]: npc_parse_mapflag: Unable to set PvP and GvG(null) Castle flags for the same map! Removing PvP flag from schg_cas01.
[Warning]: npc_parse_mapflag: Unable to set PvP and GvG(null) Castle flags for the same map! Removing PvP flag from schg_cas02.
[Warning]: npc_parse_mapflag: Unable to set PvP and GvG(null) Castle flags for the same map! Removing PvP flag from schg_cas03.
[Warning]: npc_parse_mapflag: Unable to set PvP and GvG(null) Castle flags for the same map! Removing PvP flag from schg_cas04.
[Warning]: npc_parse_mapflag: Unable to set PvP and GvG(null) Castle flags for the same map! Removing PvP flag from schg_cas05.
[Warning]: npc_parse_mapflag: Unable to set PvP and GvG(null) Castle flags for the same map! Removing PvP flag from arug_cas01.
[Warning]: npc_parse_mapflag: Unable to set PvP and GvG(null) Castle flags for the same map! Removing PvP flag from arug_cas02.
[Warning]: npc_parse_mapflag: Unable to set PvP and GvG(null) Castle flags for the same map! Removing PvP flag from arug_cas03.
[Warning]: npc_parse_mapflag: Unable to set PvP and GvG(null) Castle flags for the same map! Removing PvP flag from arug_cas04.
[Warning]: npc_parse_mapflag: Unable to set PvP and GvG(null) Castle flags for the same map! Removing PvP flag from arug_cas05.
[Warning]: npc_parse_mapflag: Unable to set PvP and GvG(null) Castle flags for the same map! Removing PvP flag from nguild_alde.
[Warning]: npc_parse_mapflag: Unable to set PvP and GvG(null) Castle flags for the same map! Removing PvP flag from nguild_gef.
[Warning]: npc_parse_mapflag: Unable to set PvP and GvG(null) Castle flags for the same map! Removing PvP flag from nguild_pay.
[Warning]: npc_parse_mapflag: Unable to set PvP and GvG(null) Castle flags for the same map! Removing PvP flag from nguild_prt.
[Warning]: map_setmapflag: Unable to set PvP and GvG Dungeon flags for the same map! Removing PvP flag from arug_dun01.
[Warning]: map_setmapflag: Unable to set PvP and GvG Dungeon flags for the same map! Removing PvP flag from schg_dun01.
[Warning]: map_setmapflag: Unable to set PvP and GvG flags for the same map! Removing PvP flag from 2009rwc_01.
[Warning]: map_setmapflag: Unable to set PvP and GvG flags for the same map! Removing PvP flag from 2009rwc_02.
[Warning]: map_setmapflag: Unable to set PvP and GvG flags for the same map! Removing PvP flag from 2009rwc_03.
[Warning]: map_setmapflag: Unable to set PvP and GvG flags for the same map! Removing PvP flag from 2009rwc_04.
[Warning]: map_setmapflag: Unable to set PvP and GvG flags for the same map! Removing PvP flag from 2009rwc_05.
[Warning]: map_setmapflag: Unable to set PvP and GvG flags for the same map! Removing PvP flag from 2009rwc_06.
[Warning]: map_setmapflag: Unable to set PvP and GvG flags for the same map! Removing PvP flag from 2009rwc_07.
[Warning]: map_setmapflag: Unable to set PvP and GvG flags for the same map! Removing PvP flag from 2009rwc_08.
[Warning]: map_setmapflag: Unable to set PvP and GvG flags for the same map! Removing PvP flag from 2009rwc_f01.
[Warning]: map_setmapflag: Unable to set PvP and GvG flags for the same map! Removing PvP flag from 2012rwc_01.
[Warning]: map_setmapflag: Unable to set PvP and GvG flags for the same map! Removing PvP flag from 2012rwc_02.
[Warning]: map_setmapflag: Unable to set PvP and GvG flags for the same map! Removing PvP flag from 2012rwc_03.
[Warning]: map_setmapflag: Unable to set PvP and GvG flags for the same map! Removing PvP flag from 2012rwc_04.
[Warning]: map_setmapflag: Unable to set PvP and GvG flags for the same map! Removing PvP flag from 2012rwc_05.
[Warning]: map_setmapflag: Unable to set PvP and GvG flags for the same map! Removing PvP flag from 2012rwc_06.
[Warning]: map_setmapflag: Unable to set PvP and GvG flags for the same map! Removing PvP flag from 2012rwc_07.
[Warning]: map_setmapflag: Unable to set PvP and GvG flags for the same map! Removing PvP flag from 2012rwc_08.
[Warning]: map_setmapflag: Unable to set PvP and GvG Dungeon flags for the same map! Removing PvP flag from gld_dun01.
[Warning]: map_setmapflag: Unable to set PvP and GvG Dungeon flags for the same map! Removing PvP flag from gld_dun02.
[Warning]: map_setmapflag: Unable to set PvP and GvG Dungeon flags for the same map! Removing PvP flag from gld_dun03.
[Warning]: map_setmapflag: Unable to set PvP and GvG Dungeon flags for the same map! Removing PvP flag from gld_dun04.

**Comment by cydh** [comment]
well this is since map refactor, the pk_mode will set pvp silently, but we set the flag in "noisy" mode

**Comment by LiamKarlMitchell** [comment]
```
        if( battle_config.pk_mode && (map[i].flag.gvg == 0 && map[i].flag.gvg_dungeon == 0 && map[i].flag.gvg_castle && map[i].flag.battleground == 0))
            map[i].flag.pvp = 1; // make all maps pvp for pk_mode that are allowed to be.
```

map.cpp map_flags_init should only set pvp on when pk_mode is set for maps that allow it.
Some flags do not allow pvp to be set concurrently seemingly gvg and battlegrounds.

Reopen issue?
