### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by lelouch22** [rathena/rathena#3383]
* **rAthena Hash**: 68fccf447b3c9a2aa90a3de7bdc10856400635bd

* **Client Date**: 2014-10-22bRagexe

* **Server Mode**: Pre-Renewal

* **Description of Issue**: This only happend everytime i shutdown the server
  * Result: 
 
> Memory manager: Memory leaks found at 2018/08/03 12h09m18s (Git Hash 68fccf447b3c9a2aa90a3de7bdc10856400635bd).
0001 : script.cpp line 2468 size 512 address 0x0x7faf63bce26c
0002 : script.cpp line 2468 size 512 address 0x0x7faf63bce48c
0003 : script.cpp line 2468 size 512 address 0x0x7faf63bce6ac
0004 : script.cpp line 2468 size 512 address 0x0x7faf63bce8cc
0005 : script.cpp line 2468 size 512 address 0x0x7faf63bceaec
0006 : script.cpp line 2468 size 512 address 0x0x7faf63bced0c
0007 : script.cpp line 2468 size 512 address 0x0x7faf63bcef2c
0008 : script.cpp line 2468 size 512 address 0x0x7faf63bcf14c
0009 : script.cpp line 2468 size 512 address 0x0x7faf63bcf36c
0010 : script.cpp line 2468 size 512 address 0x0x7faf63bcf58c
0011 : script.cpp line 2468 size 512 address 0x0x7faf63bcf7ac
0012 : script.cpp line 2468 size 512 address 0x0x7faf63bcf9cc
0013 : script.cpp line 2468 size 512 address 0x0x7faf63bcfbec
0014 : script.cpp line 2468 size 512 address 0x0x7faf63bcfe0c
0015 : script.cpp line 2468 size 512 address 0x0x7faf63bd002c
0016 : script.cpp line 2632 size 40 address 0x0x7faf63c26ef4
0017 : script.cpp line 2632 size 40 address 0x0x7faf63c26f44
0018 : script.cpp line 2632 size 40 address 0x0x7faf63c26f94
0019 : script.cpp line 2632 size 40 address 0x0x7faf63c26fe4
0020 : script.cpp line 2632 size 40 address 0x0x7faf63c27034
0021 : script.cpp line 2632 size 40 address 0x0x7faf63c27084
0022 : script.cpp line 2632 size 40 address 0x0x7faf63c270d4
0023 : script.cpp line 2632 size 40 address 0x0x7faf63c27124
0024 : script.cpp line 2632 size 40 address 0x0x7faf63c27174
0025 : script.cpp line 2632 size 40 address 0x0x7faf63c271c4
0026 : script.cpp line 2632 size 40 address 0x0x7faf63c27214
0027 : script.cpp line 2632 size 40 address 0x0x7faf63c27264
0028 : script.cpp line 2632 size 40 address 0x0x7faf63c272b4
0029 : script.cpp line 2632 size 40 address 0x0x7faf63c27304
0030 : script.cpp line 2632 size 40 address 0x0x7faf63c27354
0031 : map.cpp line 3473 size 273600 address 0x0x7faf63f8a040
[Warning]: Memory manager: Memory leaks found and fixed.

It was pointing to this...
script.cpp line 2468
> script_buf=(unsigned char *)aMalloc(SCRIPT_BLOCK_SIZE*sizeof(unsigned char));

script.cpp line 2632
> CREATE(code,struct script_code,1);

map.cpp line 3473
> CREATE(m->cell, struct mapcell, size);

**Comment by mmjgold** [comment]
if ur ram is low make swapfile

**Comment by anacondaqq** [comment]
This is not about ram low, it's about memory leaks.

**Comment by aleos89** [comment]
Does #3384 fix these issues for you? I'm unable to see any memleaks using that PR.

**Comment by lelouch22** [comment]
Yea i think its gone now after updating it.
