### ISSUE TITLE
Tool Dealer Morroc 146/103 and 151/241

### ISSUE THREAD

**Issue by AzarthMZintos** [rathena/rathena#3392]
* **rAthena Hash**: Update at the time of posting

* **Client Date**: 2018-05-30b

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: The navigation system tell me there is a 2 tool dealer at morroc but no npc there, the icon of tool dealer is there too
  * Expected Result: Should be a tool dealer npc there
  * How to Reproduce: Go to morroc at 146/103 and 151/241
  * Official Information:No official acess
  

* **Modifications that may affect results**: 
  
  

<a href="https://imgbb.com/"><img src="https://image.ibb.co/jnxedz/morroctool.png" alt="morroctool" border="0"></a>

<a href="https://ibb.co/cUx1rK"><img src="https://preview.ibb.co/e1XZBK/morroctool2.png" alt="morroctool2" border="0"></a>

**Comment by BrOgBr** [comment]
https://github.com/rathena/rathena/pull/2977/files#diff-460f3f31c9c9c82d4d5ebde0f6c699a5R101

**Comment by AzarthMZintos** [comment]
wow march...well maybe one day ty
