### ISSUE TITLE
Metallic Sound should be Neutral

### ISSUE THREAD

**Issue by flamefury** [rathena/rathena#3397]
* **rAthena Hash**: 11b255e0e9cd2541ddd0e7c314b440f59627d07d
* **Client Date**: Doesn't matter
* **Server Mode**: Renewal
* **Description of Issue**: 
  * Result: Metallic Sound is changing properties with weapon property.
  * Expected Result: Metallic Sound should always be Neutral.
  * How to Reproduce: Endow a Minstrel / Wanderer and use Metallic Sound
  * Official Information: 

https://www.divine-pride.net/database/skill/2413
kRO skill description says 무속성 (Neutral attribute) explicitly.

* **Modifications that may affect results**: None

**Comment by mrjnumber1** [comment]
i can't confirm 100% if this happens in aegis, but the code does seem to imply that it does.

wm_metalicsound also needs coded to explicitly increase dmg for players in sleep or deepsleep. i doubt the multipliers from deep sleep and for the skill's bonus against deep sleep are stacked, so we'd just need to add an extra check for SC_SLEEP for that skid).

**Comment by aleos89** [comment]
I'll link this with #2025.
