### ISSUE TITLE
Insignia Are not increasing MATK.

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#3403]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/4befcf747fa0c6eb22c6c1dcc31c5f55486dcf91
* **Client Date**: 2018-06-07
* **Server Mode**: RE
* **Description of Issue**: The magic attack bonus is not being applied to 3rd class spells properly.

**Comment by aleos89** [comment]
What skills are you using to test this? The bonus is added in `battle_calc_magic_attack` instead of `status_calc_matk` so your PR won't work.

**Comment by aleos89** [comment]
Are you using a level 3 insignia?

**Comment by admkakaroto** [comment]
Yes, i will post a test for you..just a minute.

**Comment by admkakaroto** [comment]
Here:

Without the insignia:
![b1](https://user-images.githubusercontent.com/6227618/44118466-9bd85330-9fec-11e8-879f-0e69b9ecc97a.png)


With the status:
![b2](https://user-images.githubusercontent.com/6227618/44118480-a98d8df6-9fec-11e8-94d9-042ecc81c7cd.png)
