### ISSUE TITLE
Not able to steal itens from mob_drop.txt

### ISSUE THREAD

**Issue by AzarthMZintos** [rathena/rathena#3407]
* **rAthena Hash**: Update in the moment of this issue

* **Client Date**: 2018-05-30b

* **Server Mode**: renewal

* **Description of Issue**: 
  * Result: If you use steal skill from thief in a mob without any itens from regular mob db it will stole nothing even if the item you put in the mob_drop.txt is 100% chance of dropping
  * Expected Result: the skill should be able to steal mob_drop.txt itens
  * How to Reproduce: take out all itens of a mob_db and put one item 100% at mob_drop.txt you will not be able to steal it
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by sader1992** [comment]
please add an example line
```
// <mobid>,<itemid>,<rate>{,<randopt_groupid>,<flag>}
// <flag>            : 1 - The item is protected from steal.
 //                     2 - As MVP Reward
```

**Comment by AzarthMZintos** [comment]
1014,2220,10000,RDMOPTG_EQHEAD

**Comment by sader1992** [comment]
add the hash
and i can't reproduce

```
1002,PORING,Poring,Poring,1,60,1,27,20,1,8,9,2,5,6,1,1,0,6,5,10,12,1,3,21,0x83,400,1872,672,480,0,0,0,0,0,0,0,,,,,,,,,,,,,,,,,,,,

1002,2220,10000,RDMOPTG_Crimson_Weapon
```
and i can steal it

**Comment by AzarthMZintos** [comment]
maybe dont work without "official" rdmoptg?

**Comment by sader1992** [comment]
try to test with the official , however i don't think it would make a difference, but it's better to test

**Comment by Lemongrass3110** [comment]
"Update in the moment of this issue" is not a valid hash.
I think there was an issue with this which was fixes a few months ago so please make sure you are really up to date.
I agree with sader that it is unlikely to be related to official groups or not.

**Comment by AzarthMZintos** [comment]
never mind i kinda tired(still not work but in in my end somehow) but ty guys

**Comment by aleos89** [comment]
Make sure you have [this](https://github.com/rathena/rathena/pull/1743/commits/201e25cfe4fae92d4255d8218ee6775a7c1cac64) properly applied.
