### ISSUE TITLE
Offertorium with Magnificat skill problem

### ISSUE THREAD

**Issue by julia40124009** [rathena/rathena#341]
Offertorium and Magnificat can interrupt other effects

Ziu video
https://www.youtube.com/watch?v=QmMnDfqeHus

version https://github.com/rathena/rathena/commit/bae469e6c6e45a7a08db9c27f31e249eaa52207d

client 2013-12-23

**Comment by reigneil** [comment]
Confirmed. so this must be like the version of Kyrie Eleison and Assumptio.
