### ISSUE TITLE
Drops from Solid Lunatic(2770) and Pupa(1008)

### ISSUE THREAD

**Issue by AzarthMZintos** [rathena/rathena#3410]
* **rAthena Hash**: ef2bf5b0e

* **Client Date**: 2018-05-30b

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Drop of Pupa(1008) Item Guard [1] = (2102) is 0,02% and Drop of Solid Lunatic(2770) Item Clown Nose (2262) is 11%
  * Expected Result: The Guard[1] from Pupa should be 0,20% And the Clown Nose from Solid Lunatic 0,20%
  * How to Reproduce: Look at DB
  * Official Information:
  

Pupa: https://www.divine-pride.net/database/monster/1008/pupa
Solid Lunatic: https://www.divine-pride.net/database/monster/2770/solid-lunatic

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
This kinda stretches into a much broader issue. There are several cases of incorrect drops/drop rates on lots of monsters since we haven't updated the overall database in quite some time.

**Comment by BrOgBr** [comment]
I'll try update all Renewal drops.

**Comment by AzarthMZintos** [comment]
rAthena Hash: 79766cdClient Date: 2015-04-11aServer Mode: RenewalDescription of Issue:Result: the drop of 2301 is wrong from the mob Baby Desert Wolf(id:1107) = 2%, Baby Desert Wolf Ringleader(id:2855) = 2% and Furious Baby Desert Wolf(id:2856) =2%Expected Result: the droups of 2301 should be Baby Desert Wolf(id:1107) = 1%, Baby Desert Wolf Ringleader(id:2855) = 5% and Furious Baby Desert Wolf(id:2856) = 5%How to Reproduce: Look at the mobinfo databaseOfficial Information:Dont have acess to official information link to divine pride database:https://www.divine-pride.net/database/item/2301Modifications that may affect results:
--

**Comment by AzarthMZintos** [comment]
rAthena Hash: 79766cdClient Date: 2015-11-04aServer Mode: RenewalDescription of Issue:Result: The drop from 1002 has empty bottle(id:713) at 15% it should exist.Expected Result: The drop from 1002 should have fly wing(id:601) at 5% and the card rate(id:4001) should be change to 0,01% to 0,20%How to Reproduce: Look at mobinfo databaseOfficial Information:dont have acess to official info divine pride link:https://www.divine-pride.net/database/monster/1002/Modifications that may affect results:
--

**Comment by sader1992** [comment]
please organize your reply so it would be more readable

**Comment by Atemo** [comment]
We already know that ours datas are outdated. Do you plan to open an issue for each mob ID?
Honestly I'm not interested to update the mob one by one.. but if you really want to update an ID you still can submit a pull request

**Comment by AzarthMZintos** [comment]
Do you plan to open an issue for each mob ID? yes but since it got "duplicate" every time no

**Comment by AzarthMZintos** [comment]
Honestly I'm not interested to update the mob one by one

well what are you waiting to do all of it? istead of posting here?

**Comment by sader1992** [comment]
Well , if you want to open an issue for the mos/items database you could just open 1 issue add the monsters/items in the same post (edit your first post)
and when there is a lot of it we can just open a pr for them all

or if you know how it work you can just open a pr your self and fix the issues and we would check it

anyway this is only my opinion

**Comment by AzarthMZintos** [comment]
dont worry i will not be posting in here anymore is just not worth it

**Comment by aleos89** [comment]
@AzarthMZintos: The point was that the issues were related as a lot of monsters need to be updated. You could continue to list them in the same issue. When you tag issues with others it creates a symlink so we can see related issues down the road. These are still valid issues, I'm just trying to keep the place tidy so we don't get overwhelmed with similar reports.

**Comment by vakhet** [comment]
@aleos89: I can develop simple tool for comparing rAthena DB against Divine Pride DB, using their public API.
It will provide detailed report about any discrepancies between them, and ready-to-apply SQL updates. (Any feature requests would be nice)

Please tell me if some kind of such tool already exists .) If it is not - I'm eager to help

**Comment by Lemongrass3110** [comment]
The tool is not the problem here. We will only touch that after converting the database to yaml probably.

**Comment by vakhet** [comment]
@Lemongrass3110, can you please point me directions about this convertion routine? Maybe I can help

**Comment by aleos89** [comment]
#4335

**Comment by Atemo** [comment]
Fixed in https://github.com/rathena/rathena/commit/dea08407853d72b89c4599d618c687c47a15857f
