### ISSUE TITLE
Frost Lock Issue

### ISSUE THREAD

**Issue by vexillio1993** [rathena/rathena#342]
Hi, if you guys dont mind i wanna ask something regarding frost lock issues im using a default rathena from my host and there seems some problem here it is " i'm using Mjolnir in my champ then i will switch to 4sk card weapon to use finger offensive in other server that switching can frost your enemies when the timing is good, in sonic blow too of assassin cross, and asura strike of champion those switchings wont work, im new in making a server sorry for this question, i hope theres a good answer here haha thanks in advance.

FYI, I know when enemies are using unfrozen lol we ady try it in monsters that is frozenable.

**Comment by reigneil** [comment]
so what you want is to have two effect in one? i though this is not possible in official server... btw this is the commit that prohibit you to do that. FYI https://github.com/rathena/rathena/commit/2732176

**Comment by vexillio1993** [comment]
No i mean is in normal servers when your using mjolnir and switch to 4SK Card weapon the enemy will be frozen right ?

**Comment by vexillio1993** [comment]
Then what would i do to make it work in my server?

**Comment by reigneil** [comment]
ok i get it now... so your using mjolnir for fast cast then switch to 4SK Card weapon for Frosting but this switching ignore mjolnir right? what the bug before is just like having 4SK+mjolnir weapon in one attack.

**Comment by vexillio1993** [comment]
yes your right, thats what im talking about why is the effect of 4sk card weapon is missing. im wondering why :(

**Comment by cydh** [comment]
what's "4SK"?

**Comment by Playtester** [comment]
Going by the context I think he means a weapon carded with 4 stormy knight cards.

**Comment by paulbits** [comment]
Up for this i need this too

**Comment by Playtester** [comment]
I can't confirm this. I tried it like 50 times but never got the enemy frozen when I switched the weapon after casting Sonic Blow on official servers.

This was intentionally fixed, see here:
http://herc.ws/board/index.php?app=tracker&showissue=7307

Kyeme is a very reliable source, so I believe that "trick" working was just an emulator bug. 

Working as intended.

**Comment by paulbits** [comment]
I found a way how to bring it back, i should post a thread about it for some user's who want to make it back.

**Comment by Vexillio** [comment]
oh god my topic was too long already haha yes i still need that @paulbits im still looking for answers here
