### ISSUE TITLE
unit_remove_map issue

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#3420]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/2e133ed07f4ef6ac2ed4b33964caa3b05f8149e0
* **Client Date**: 2018-06-07
* **Server Mode**: RE
* **Description of Issue**: unfortunately I do not know how to reproduce, I was just watching the terminal on my server when I came across this message.
* **Modifications that may affect results**: I have several modifications in the SRC, but passing the line number to the current rA would be: 3101

IMG: 
![sem titulo5](https://user-images.githubusercontent.com/6227618/44440644-66ed2200-a59f-11e8-9807-1bae36c88fc9.png)

**Comment by aleos89** [comment]
Most likely when the instance was destroyed. Somehow the user was left behind on the map (you can see the `debug_remove_map` value is 1) and it attempted to remove them again.

Without any steps to reproduce it would be hard to determine what the player was doing.

**Comment by admkakaroto** [comment]
Well, I'm going to close this Issue, if I find out how to reproduce this, I'll open a new report, thank you!
