### ISSUE TITLE
Hard laggs on Map Server when mobbing

### ISSUE THREAD

**Issue by Andras1992** [rathena/rathena#3421]
* **rAthena Hash**: 429541fb8

* **Client Date**: 
20151104a

* **Server Mode**: 

Pre Renewal
* **Description of Issue**: 
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

Issue: Extrem serverwide laggs when Mobbing 15 or more Monsters in Orc Dungon, Veins Map or any map where you can mob

Result: Serverwide laggs but without any error in console. As well the Root himself has in Monitoring no provlems with cpu or ram

How to Reproduce: Compile Server as Pre Renewal and mobb hard. If you Need I can send you my compiled Server.

Offical Information: No informations about this.

* **Modifications that may affect results**:

**Comment by admkakaroto** [comment]
It's some problem with your emulator or with your machine, I have a map with more than 600 monsters and I do not have this problem.

**Comment by Andras1992** [comment]
When I recompile as Renewal Server I have no lags. I almost changed the root beacuase I thought it's the Server himself. I and the Server are botn in Central Europe. Normal Ping is around 27ms. Everything works fine. RO isn't the only gameserver I run there - Everyone except RO works. And Renewal RO works, too. So no Problem with my machine.

**Comment by aleos89** [comment]
What's your hash?

**Comment by Andras1992** [comment]
Added, sorry Hash was between the <-- -->

**Comment by AzarthMZintos** [comment]
I have the same problem but I was think as only me, if i try to kill more than 10+ mobs at once they got hit and the take some seconds to die and drop stuffy @Andras1992 is like that or diferent?

**Comment by jezznar** [comment]
@Andras1992 do you have any source modifications done in your server? how about battle config files? can you share them? also what OS distro are you using?

**Comment by Andras1992** [comment]
I have no modifications in the SRC. Battle Config you get here: https://github.com/Andras1992/battleconfs

OS is Windows 2016 Server Standart

**Comment by aleos89** [comment]
Are you using a clean rAthena? I'm unable to reproduce any lags with the latest (bde33e7). Pre-renewal or Renewal should not matter in a lag like this. Make sure you applied 48ae1a1 properly.

**Comment by uddevil** [comment]
@aleos89 uh i forgot to mention that there's also a bit lag before bde33e762c044506deeb7a69b92837ad4a040091 

The scenario is i'm using Illusion Doping with 20k stats in the instance to clear the mobs, and the mobs had a fraction of second lag before the damage showed up and died. But after implementing the hash mentioned above, everything went fine (e.g the damage showed up instantly and the died). Maybe @Andras1992 can try to test again using the latest commit?
