### ISSUE TITLE
A mess with ep13_start variable

### ISSUE THREAD

**Issue by Akaineko-astasi** [rathena/rathena#3427]
* **rAthena Hash**: 
429541fb

* **Client Date**: 

20170614
* **Server Mode**: 

renewal

* **Description of Issue**: 
Ep 16.1 quests' prerequisite is none of `BaseLevel < 100 || (ep13_ryu < 100 && ep13_start < 100)`
https://github.com/rathena/rathena/blob/master/npc/re/quests/quests_16_1.txt#L40
  * Result: 
`ep13_ryu > 99 && ep13_start > 99` condition is impossible to meet
`ep13_ryu` is an *Onward to the New World* variable, it's set to `100` when the quest is finished;
`ep13_start` is not assigned anywhere. Currently it is being used to match the official script only in prereq checks: 
https://github.com/rathena/rathena/search?q=ep13_start&unscoped_q=ep13_start
  * Expected Result: 

  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**: 
  
  
none

**Comment by Atemo** [comment]
>ep13_ryu > 99 && ep13_start > 99 condition is impossible to meet

The player need to be `BaseLevel >= 100` and `ep13_ryu >= 100 ` or  `ep13_start >= 100` to start the quest, `BaseLevel >= 99 && (ep13_ryu > 99 || ep13_start > 99)`
