### ISSUE TITLE
Gym Pass

### ISSUE THREAD

**Issue by vexillio1993** [rathena/rathena#343]
My GYM PASS npc is not giving its extra weight and when i look at the misc tab of the skills theres no enlarge weight limit skill like in other servers when they use gympass theres a skill saying that you ady have the gympass thank you in your reply.

**Comment by anacondaqq** [comment]
Totally confirm!
--------------------
https://github.com/rathena/rathena/issues/318


Extra important information:
1. This bug appers only for people who already had these skills, and after applying update (skill update at februrary) this skill got damaged in database too.
2. If you try to increase level of ALL_INCRARRY by Gym Pass, you can do it without problem for old skills
3. If you was have this skill before update for example lvl 10, after applying update database got damaged, and players have only lvl 1.
4. I will provide more information if someone need.
5. resetskills, and other default things for reseting parameters do not help

6. The same issue for all Taekwon Skills (peopl who have not learned skills
7. All Taekwon skills got damaged after some of update in february.
8. Then, after issues at bugtracker here at github, the cydh did solve the problem of leveling skills from first job
9. BUT ALL REST PLAYERS WHO DID HAVE THIS SKILL BEFORE APPLING UPDATE, they totally lost them. 
10. Only one way to back skills again for players with lost skills -> delete character and level it manually.

**Comment by reigneil** [comment]
@anacondaqq so in other words... this is already been fixed with the latest commit?

**Comment by vexillio1993** [comment]
What can i do to make gympass working >.< im already frustrated

**Comment by cydh** [comment]
user who exchange the Gympass (Max_Weight_Up_Scroll, 7776) has **permanent character variable** about how many the Pass is used `gympassmemory`.
````
				delitem 7776,1; //Max_Weight_Up_Scroll
				set gympassmemory,.@add_carry;
				skill "ALL_INCCARRY",.@add_carry,SKILL_PERM_GRANT;
				close;
````

talk back to the NPC, with the 3rd option
> Um, my workouts wore off

it'll sets the skill level back
````
			mes "wimp out again, okay?";
			skill "ALL_INCCARRY",gympassmemory,SKILL_PERM_GRANT;
			close;
````

**Comment by vexillio1993** [comment]
Its still the same >.<

**Comment by MrAntares** [comment]
Dudes, calm down. Go to the npc, and select "The effect wore off", and he will giv the skill back to those who had it before..

**Comment by anacondaqq** [comment]
Close this issue. The problem solved by cydh message. But there are interesting thing... Why this happened?) I did't notice since 2010 any problem with this skill :D This is very strange.

Btw, thx @cydh!
