### ISSUE TITLE
Mysql 8 error 1071 max key length is 1000 bytes

### ISSUE THREAD

**Issue by fuzzyfreak** [rathena/rathena#3430]
* **rAthena Hash**: 

* **Client Date**: 

* **Server Mode**: 

* **Description of Issue**: 
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**: 
  
  
When importing main.sql the error occurs.  The engine is MyISAM

**Comment by aleos89** [comment]
Duplicate of #3093.
