### ISSUE TITLE
VIP Display Rate show wrong calculation for base EXP

### ISSUE THREAD

**Issue by hendra814** [rathena/rathena#3431]
* **rAthena Hash**: Lastest

* **Client Date**:  2013-08-07

* **Server Mode**: renewal

* **Description of Issue**:  using base EXP 1000 and 50% bonus EXP for base EXP it 's show 1050 not 1500
using command `@rates` it's show the right calculation
detail in ss
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**: 
  
  

![screenrathena040](https://user-images.githubusercontent.com/9587609/44625649-a5386780-a938-11e8-9e2e-bb7a3fb8e884.jpg)

![screenrathena041](https://user-images.githubusercontent.com/9587609/44625656-cac57100-a938-11e8-9233-8fd94b44151e.jpg)

**Comment by mazvi** [comment]
Confirmed by me
