### ISSUE TITLE
Memleak on public channel

### ISSUE THREAD

**Issue by cydh** [rathena/rathena#3443]
* **rAthena Hash**: f14885bc9b04f96d04c1d7d1ea9449628c5cfba5
* **Client Date**: -
* **Server Mode**: Both
* **Description of Issue**: 
  * Result: Memleak on closing map-server if public channel server was created
  * Expected Result: no memleak, channel free'd in `channel_delete`
  * How to Reproduce: create/join **public** channel
  * Official Information: -
* **Modifications that may affect results**: -

__Memleak result__
```
Memory manager: Memory leaks found at 2018/08/29 13h28m19s (Git Hash f14885bc9b04f96d04c1d7d1ea9449628c5cfba5).
0001 : ...2\src\map\channel.cpp line 45 size 100 address 0x0D28981C

Memory manager: Memory leaks found at 2018/08/29 13h34m58s (Git Hash f14885bc9b04f96d04c1d7d1ea9449628c5cfba5).
0001 : ...2\src\map\channel.cpp line 45 size 100 address 0x0D6B981C
```

**Comment by cydh** [comment]
hmmm I can't recall how to reproduce this :rofl:

**Comment by thanna** [comment]
I encounter this memory only if there is an autotrade active. I checked the channel.cpp and found that there are filters for autotraders but seems that I can only reproduce this if an autotrader is active.
