### ISSUE TITLE
Longer map loading time for characters at later slots 

### ISSUE THREAD

**Issue by AtomixRO** [rathena/rathena#345]
When I use my characters at 7th or later slots, they always take noticeably longer time to move between maps and such. Sometimes it got bad enough that I disconnected while trying to enter a shop with my character at 8th slot. I've tried switching back and forth between this character and the one at 1st slot, the problem remains even tho the transition time is almost instant for the character at 1st slot. My connection was perfect when I tried this.

**Comment by aleos89** [comment]
Sorry, but there are no checks for anything of this sort. I've never experienced this in my RO history and can't say I've ever seen it reported before.
