### ISSUE TITLE
OldGlastHeim Temporal Boots enchants

### ISSUE THREAD

**Issue by XDXDMAN** [rathena/rathena#346]
OldGlastHeim Temporal Boots enchants NPC not exist
http://irowiki.org/wiki/Old_Glast_Heim

**Comment by Barigas** [comment]
What else info is needed here? The information stated on irowiki is correct. The only thing worth to add are that the random chants have 2% to proc and are dispelled on boots switch, and that the dex temporal boots -0.5fixed cast time bonus at 120 and more base dex works before Sacramenti buff. The last change made on kro was that the 1000def bonus is changed to 200vit.

**Comment by XDXDMAN** [comment]
bug:script [ status:needs more info ]
enchants NPC?

**Comment by Atemo** [comment]
Duplicate of #493
