### ISSUE TITLE
bAddClass & bAddRace not working on Shield

### ISSUE THREAD

**Issue by laziem** [rathena/rathena#3465]
* **rAthena Hash**: 758097720
* **Client Date**: 2017
* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: bAddClass,Class_All & bAddRace,Race_All on shield did not working, no increase in damage
  * Expected Result: should be working on shield
  * How to Reproduce: Add `bonus2 bAddClass,Class_All,100;` or `bonus2 bAddRace,RC_All,100;` on any shield script. I did test on Headgear (U, M, L), Armor, Accessory (L, R), Weapon, Garment, Shoes all working except for shield
  * Official Information: -
  

* **Modifications that may affect results**: -

**Comment by aleos89** [comment]
That's because the bonus is stored directly in `weapon_data` only:
```cpp
struct weapon_data right_weapon, left_weapon;
```
