### ISSUE TITLE
invalid sql in item_db_re.sql line 2949

### ISSUE THREAD

**Issue by carl820912** [rathena/rathena#347]
in item_db_re.sql line 2949

5011,Antenna,Aerial,4,20,,100,5,,0,0xFFFFFFFF,63,2,256,,0,1,97,{},{},{}

I guess this line should be

REPLACE INTO `item_db_re` VALUES (5011,'Antenna','Aerial',4,20,NULL,100,NULL,5,NULL,0,0xFFFFFFFF,63,2,256,NULL,'0',1,97,NULL,NULL,NULL);

**Comment by nanakiwurtz** [comment]
Fixed in https://github.com/rathena/rathena/commit/8d47306f18d35abacdb11675a63c00346aefc53f
