### ISSUE TITLE
Stack getgroupitem items

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#3470]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/d17ddf41fe3f1a4eb0fcb75d82888ea89dc697ef
* **Client Date**: 2018-06-05
* **Server Mode**: RE
* **Description of Issue**: The items obtained through the getgroupitem script command, are not staking, this also happens with the item itself that generates the others.
  * Result: Items occupying new spaces in inventory and also in storage.
  * Expected Result: Items add up in the same position in the inventory and also in the storage.
  * How to Reproduce: Create item 16562 through the '@item 16562' command, if you use just this way several times without setting the amount of the default item will come to 1, if you repeat several times each time the item will come to a different slot of the inventory. After opening the item the items obtained also do not stake.

  * IMG:
![a1](https://user-images.githubusercontent.com/6227618/45126151-44830900-b148-11e8-9283-7283721ae8d1.png)

![a2](https://user-images.githubusercontent.com/6227618/45126153-4f3d9e00-b148-11e8-93ce-73f583612faf.png)

![a3](https://user-images.githubusercontent.com/6227618/45126159-56fd4280-b148-11e8-8b9d-62478e8eb345.png)

**Comment by cydh** [comment]
1. read the item_group headers
2. read https://github.com/rathena/rathena/blob/master/doc/item_group.txt
