### ISSUE TITLE
Please Don't Forget me!!

### ISSUE THREAD

**Issue by earnestinence** [rathena/rathena#3471]
* **rAthena Hash**: 10b5965d1

* **Client Date**: 20151104 

* **Server Mode**: Pre-Renewal

* **Description of Issue**: Please Don't Forget Me skill's effect doesn't go away after death
  * Result:  When Dancer class use Please Don't Forget me skill; and affected players still gets slow movements even after death.
  * Expected Result:  When player dies all effects goes away.
  * How to Reproduce:  With dancer use Please Don't Forget Me, next, with another character get on PDFM skill's AOE then die. After you respawn, tryo to walk.
* **Video**: https://www.youtube.com/watch?v=z-4aMuJxZYA
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Would be great to get a confirmation on kRO.

**Comment by mrjnumber1** [comment]
default config of EFST_DONTFORGETME (and all bard/dancer songs, at that!) has no CBuffInfo entry on pre-re and re, so there will be no checking of the status during ResetAllEffectives. 

What that may as well mean is that ResetDead/ResetDispel/Save/Send/IgnorePretendDead (and later gc_newpoison/ResetClearance/Debuff) is false.

I dont believe this report is valid, but I can't be sure, aegis is finnicky!

**Comment by sader1992** [comment]
in the meantime if you don't want it in your server i think this should do it for you
```
-	script	RemoveDancerStatus	-1,{
OnPCDieEvent:
	sc_end_class getcharid(0),20;
end;
}
```

**Comment by earnestinence** [comment]
Ok, thanks guys. Sorry i thought it was bugged!
