### ISSUE TITLE
TF_STEAL incorrect setup for renewal 

### ISSUE THREAD

**Issue by mrjnumber1** [rathena/rathena#3473]
* **rAthena Hash**:  current
* **Client Date**: x
* **Server Mode**: renewal
* **Description of Issue**: 
  * Result: RE steal works the same as Pre-RE steal. PreRE steal multiplies the droprate of the items based on the user's TF_STEAL success rate. 
  * Expected Result: In Renewal, TF_STEAL only checks the user's Steal success rate, then checks every item one by one per 10000 to compare against (until one drops). The change means that the user's success rate doesn't really matter at all, and likely will be able to get other items more often. hooray.
  * How to Reproduce: use TF_STEAL
  * Official Information: you can see the breakdown between 13.2 (pre-re) and 14.2 (re) code here https://paste2.org/csDxgz68

* **Modifications that may affect results**: x

**Comment by sader1992** [comment]
`only checks the user's Steal success rate` i don't have a lot information about renewal's skills in general
but if that is true than the card drop rate more with steal skill ?
mean to steal = 8/1 you will get the card while in the normal drop is 10000/1
or i understood wrong ?

**Comment by AzarthMZintos** [comment]
cards are blocked to be steal from mobs

**Comment by mrjnumber1** [comment]
Please look at the code if you still do not understand, I'm quite bad at explaining!

Proper Behavior in Renewal (rAthena lacks this):
1. PC steals from mob
2. PC has 75% steal **success** rate.
3. If Random(0,100) is below 75, so we continue (if it's above, we fail and cancel now)
4. First item drop is Jellopy/5500 (55.00%)
5. If Random(0,10000) is (0-5500], PC earns the Jellopy. (if it was above, continue to the next item in the list)

Current behavior (which is correct for Pre-Renewal):
1. PC steals from mob
2. PC has 75% steal **modify** rate. 
3. First item drop is Jellopy/5500 (55.00%)
4. If Random(0, 10000) is (0-4125] (`4125=5500*.75`), PC earns the Jellopy (If it was above, continue to the next item in the list)

**Comment by Playtester** [comment]
But Aegis also has MAX_STEAL_DROP and I'm pretty sure that doesn't include the 8th slot.

It's interesting because in renewal you cannot ever steal an item that comes after a 100% drop item. I'm questioning that any private server with rates above 1x will want that behavior.

**Comment by mrjnumber1** [comment]
it was a mistake to write MAX_STEAL_DROP, i should have left it alone. because it checks all 8 members of the monparameter items.

i don't have an opinion on what setup options are used, most players don't even use gank rogues (aside from bots). i just was droppin off what i saw in the exe.

**Comment by Playtester** [comment]
Maybe the reason cards don't drop is that stealRate is below 100? At least in pre-renewal the dropRate of cards would drop to 0 then due to the rounding down when converting to int.

**Comment by sader1992** [comment]
for the card , anything at the 8th place (and more) can not be stolen `#define MAX_STEAL_DROP 7`
however what i meant by my comment as rare item's rate = common item's rate in this calculation for steal

**Comment by mrjnumber1** [comment]
no. please see my previous post.
