### ISSUE TITLE
Weapon Refine Level do not applied to Asura Strike.

### ISSUE THREAD

**Issue by anacondaqq** [rathena/rathena#348]
Weapon Upgrade level do not applied to final damage for skills like Asura Strike, and others.

How reproduce?
---------------------

1. Make monk with any weapon (mace or claw, doesnot mater) +0 level
2. Deal damage to any monster with Asura Strike, and notice dealed damage.
3. Refine your weapon +10, and you will got extra atk
4. Deal damage to same monster again -> You will see the same damage.

Technical Information:
---------------------------
* Pre-renewal
* 99 / 70
* Mmo.h 2010-07-30
* packet_ver: 25
* latest rAthena (17.03.2015)

This problem since ~ 1-2-3 month.

**Comment by cydh** [comment]
same answer as https://github.com/rathena/rathena/issues/349#issuecomment-110090872

**Comment by anacondaqq** [comment]
Tested! This bug not actual anymore, and already fixed in rAthena but i don't know when.
Right now rAthena already calculate in correct way damage for asura strike. So, there are no bugs at all. Closing it.
