### ISSUE TITLE
Map crashed 

### ISSUE THREAD

**Issue by kenzffr** [rathena/rathena#3482]
Client  date: 2015-05-13
Renewal Mode

![unknown](https://user-images.githubusercontent.com/15853210/45279565-ba49f480-b4fb-11e8-9ad9-38a3d40bdbc0.png)

**Comment by sader1992** [comment]
follow the issue template please!

**Comment by chuchpong** [comment]
I got the error same as you.

Now you can fix it?
Thank you in Advance!

#0  0x00000000004ff318 in npc_selllist (sd=0x7a42fb0, n=25,
    item_list=<value optimized out>) at npc.c:1951
1951                    if( sd->inventory_data[idx]->type == IT_PETEGG && sd->status.inventory[idx].card[0] == CARD0_PET )


#0  0x00000000004ff318 in npc_selllist (sd=0x7a42fb0, n=25,
    item_list=<value optimized out>) at npc.c:1951
        amount = 1
        idx = 82
        z = <value optimized out>
        i = <value optimized out>
        skill = <value optimized out>
        nd = <value optimized out>
        __FUNCTION__ = "npc_selllist"
#1  0x00000000004a35dc in clif_parse_NpcSellListSend (
    fd=<value optimized out>, sd=0x7a42fb0) at clif.c:11481
        fail = 0
        n = <value optimized out>
        item_list = <value optimized out>
        info = <value optimized out>
#2  0x00000000004b8649 in clif_parse (fd=49) at clif.c:19065
        cmd = <value optimized out>
        packet_ver = <value optimized out>
        packet_len = <value optimized out>
        err = -1
        sd = 0x7a42fb0
        pnum = <value optimized out>
#3  0x00000000005f4f36 in do_sockets (next=<value optimized out>)
---Type <return> to continue, or q <return> to quit---
    at socket.c:1236
        rfd = {__fds_bits = {562949953421312, 0 <repeats 15 times>}}
        timeout = {tv_sec = 0, tv_usec = 13109}
        ret = <value optimized out>
        i = <value optimized out>
#4  0x00000000005f2f93 in main (argc=1, argv=<value optimized out>)
    at core.c:371
        next = <value optimized out>

**Comment by aleos89** [comment]
Possibly related to #3505?
