### ISSUE TITLE
Yaml error didn't know what line it occurred

### ISSUE THREAD

**Issue by Litro** [rathena/rathena#3483]
* **rAthena Hash**: d17ddf41fe3f1a4eb0fcb75d82888ea89dc697ef

* **Client Date**: 2018-05-30bRagexeRE

* **Server Mode**: pre-re or re

* **Description of Issue**: 
  * Result: Error in db file type yaml didn't show what line error occurred
  * Expected Result: it should show, for ease of debug
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
The node at fault should be printing to the console. Which database are you having issues with?

**Comment by Litro** [comment]
`[Error]: Cannot read 'db/import/achievement_db.yml'.`

it is because of tab when parsing. shouldn't it show where the line can't be parsed, to show like txt's
