### ISSUE TITLE
Autoguard, Cicada Skin Shed, and Mirror Image blocking

### ISSUE THREAD

**Issue by cydh** [rathena/rathena#3487]
* **rAthena Hash**: ca83d3528529a9dd4364f29113e965ff4b4df29e
* **Client Date**: -
* **Server Mode**: Both
* **Description of Issue**: 
  * Result: Skill with `nk` 0x8 / `NK_NO_CARDFIX_ATK` are not blocked by Autoguard (SC_AUTOGUARD), Cicada Skin Shed (SC_UTSUSEMI), and Mirror Image (SC_BUNSINJYUTSU)
  * Expected Result: To take as example, Acid Terror has 0x8 which is correct that the atk is not modified by card (isn't range card is affected?), but the nk makes it cannot be blocked by those 3 SCs while it should be blocked by Autoguard or Kyrie's barrier
    > Kyrie Eleison and Guard **block** both the damage and the chance of breaking armor

    > 230,9,6,1,0,0x4**8**,0,5,1,yes,0,0,0,weapon,0,0x0,	AM_ACIDTERROR,Acid Terror`
  * How to Reproduce: 
  * Official Information: need to be confirmed again actually. I just want to separated that NK to INF3 :rofl: (and will be followed by Defending Aura flag)
* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Fixed in b614092b75e9cb63892a88de7321fd0640aaee4d.
