### ISSUE TITLE
Iron Hand (passive skill) do not applied to Asura Srike final damage (from knuckets)

### ISSUE THREAD

**Issue by anacondaqq** [rathena/rathena#349]
How reproduce:
--------------------
1. Make monk any level and any job
2. Make some Knuckle (doesnot matter which one)
3. Level 2 Iron Hand (passive skill) (+6 atk for attacks from Knuckles)
4. Deal Asura Strike damage to any monster
5. Level 10 Iron Hand (passive skill) (+30 atk from Knuckles)
6. Do asura to Monster, and you will NOT see any difference.

So, this is doesnot work.
Technical Information:
---------------------------
* Pre-renewal
* 99 / 70
* Mmo.h 2010-07-30
* packet_ver: 25
* latest rAthena (17.03.2015)

**Comment by cydh** [comment]
the source itself skip the Asura from mastery bonuses
