### ISSUE TITLE
NPC Ticket Exchange Pet Missing in the npc folder

### ISSUE THREAD

**Issue by AzarthMZintos** [rathena/rathena#3498]
* **rAthena Hash**: 3cd7717

* **Client Date**: 2018-06-21a

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: The npc is missing in the folders of npcs, we have other like ticket refine and etc but not this one
  * Expected Result: should have a npc to use ticket pet exchange
  * How to Reproduce: `@item 22764` open it and you cant use the tickets because there no npc for it in rathena
  * Official Information:

* **Modifications that may affect results**: 
  
  

  Edit from @Atemo: _Make sure you quote ``` `@atcommands` ``` just like this so that you do not tag uninvolved GitHub users!_

**Comment by cydh** [comment]
because can't found any info about it

**Comment by AzarthMZintos** [comment]
alot of npc say custom dialog custom npc custom quest why this will be any diferent?

**Comment by cydh** [comment]
I said couldn't find, not "don't want to", please learn. As a custom, official server's implementation is need as references, if not, users can simply make custom script themselves :rofl:

**Comment by aleos89** [comment]
Is this part of the Pet Evolution system? #2962

**Comment by AzarthMZintos** [comment]
No...

**Comment by AzarthMZintos** [comment]
@aleos89 reopen this please is not fix and no metion in the pet evolution system not the same thing

**Comment by cydh** [comment]
All u give are bRO info, please if really want to add it (because u don't know how to script and cannot pay someone to script it) capture & translate all info from that bRO, I don't read symbols and I can write symbols to NPC script.

I know how it works, idRO has itself exchange NPC. But I just simply don't want to add it to rAthena

**Comment by AzarthMZintos** [comment]
The npc is official and missing that what the issue is about, not about you gonna or not gonna do

**Comment by AzarthMZintos** [comment]
@aleos89 reopenit ty

**Comment by Questune09** [comment]
confirmed i use another item ( 17317 October Spooky Crate ) and i get Cute pet Loli Ruri Exchange Coupon

but dont know where does the npc located also when i check the database i cant see anything related to this item

gonna search to more to help for this
