### ISSUE TITLE
Managing Skill Damage

### ISSUE THREAD

**Issue by cawogeek** [rathena/rathena#350]
"Managing Skill Damage" system is not working in latest pull 8d47306.

-clean rathena git pull
-Pre Renewal
-uncomment #define ADJUST_SKILL_DAMAGE in src/config/core.h
-SN_SHARPSHOOTING,1,15,1000 in skill_damage_db.txt 
-@pvpon in new_1-1 and tested sharpshooting and adjusting it in skill_damage_db from -100 up to 1000 damage ratio

Still no changes in the damage. :(

Thanks in advance! ;)

**Comment by cawogeek** [comment]
can i follow up on this?

**Comment by aleos89** [comment]
Did you set the mapflag for the skill to be affected by it in new_1-1?
See 'npc/mapflag/skill_damage.txt'

**Comment by cawogeek** [comment]
Hey aleos, yep i tried doing that and still not working :(. Try to do it the settings are just Pre-Renewal and pk_mode: 1. thats the only modifications i do.

**Comment by cawogeek** [comment]
Can i BUMP for this???

**Comment by cydh** [comment]
thank u for reporting :D
