### ISSUE TITLE
Monster summon by dead branch are able to move

### ISSUE THREAD

**Issue by AzarthMZintos** [rathena/rathena#3508]
* **rAthena Hash**: dont matter

* **Client Date**: dont matter

* **Server Mode**: dont matter

* **Description of Issue**: 
  * Result: monster like white plant 1082 became mobile and attack if summon by dead branch
  * Expected Result: monster how cant move should be able to move just because they are summon by dead branch
  * How to Reproduce: use dead branch until gor a imobile monster he will move and attack you
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by cydh** [comment]
not a bug, it's how the dead branch works
