### ISSUE TITLE
error script in item_db.txt

### ISSUE THREAD

**Issue by carl820912** [rathena/rathena#351]
syntax error in line 3214

(.@r>=7?10,5)

need change to

(.@r>=7?10:5)

5307,Carmen_Miranda's_Hat,Carmen Miranda's Hat,4,20,,400,,10,,1,0xFFFFFFFF,63,2,256,,0,1,329,{ .@r = getrefine(); bonus2 bSubEle,Ele_Fire,(.@r>=7?10:5); if(.@r>=7){ bonus bBaseAtk,15; bonus bMatk,15; } bonus3 bAddMonsterDropItem,512,RC_All,10; bonus3 bAddMonsterDropItem,513,RC_All,10; bonus3 bAddMonsterDropItem,514,RC_All,10; bonus3 bAddMonsterDropItem,578,RC_All,10; },{},{}

**Comment by nanakiwurtz** [comment]
Fixed in 17213cabe3a764816df29db3f890288ebf545ae4
