### ISSUE TITLE
[ Enhancement ] Script function / Mapflag to set ignore "map_removemobs".

### ISSUE THREAD

**Issue by keitenai** [rathena/rathena#3511]
* **rAthena Hash**: ANY

* **Client Date**: ANY

* **Server Mode**: ANY

* **Description of Issue**: 
Currently while using function "monster" to spawn a mob/mvp for custom events, the remove mob timer still applies.
If no one is in the map before the remove mob timer is triggered, the mob will disappear ignoring the event label.

  * Result:
This results to a missing monster even when a player decides to go into the event location unless we use a permanent monster spawn and use `OnNPCKillEvent` along with `if (killedrid == MobID)` 

  * Expected Result:
Perhaps an option of mapflag  `monster_noremove`  or a new script function to ignore "map_removemobs" when using script "monster" to spawn a mob.

  * How to Reproduce: 
set mob_remove_delay: 60000 ( set 1 min for testing purpose  )
Run this script:
-	script	monster	-1,{
OnInit:
monster "jupe_core","Poring", 1002, 1, strnpcinfo(0) + "::OnPoringKill";
end;

OnPoringKill:
announce "Poring Killed!",
end;
}

Wait for 2 minutes before going to map "jupe_core".
After 2 minutes, there will be no monster in jupe_core.

* **Modifications that may affect results**:  None

**Comment by aleos89** [comment]
```cpp
	//When not to remove mob:
	// doesn't respawn and is not a slave
	if( !md->spawn && !md->master_id )
		return 0;
	// respawn data is not in cache
	if( md->spawn && !md->spawn->state.dynamic )
		return 0;
	// hasn't spawned yet
	if( md->spawn_timer != INVALID_TIMER )
		return 0;
	// is damaged and mob_remove_damaged is off
	if( !battle_config.mob_remove_damaged && md->status.hp < md->status.max_hp )
		return 0;
	// is a mvp
	if( md->db->mexp > 0 )
		return 0;
```
These checks are made to prevent certain monsters from being removed by the Dynamic Mobs battle config.

**Comment by keitenai** [comment]
oooh cool.
i rest my case =) thanks
