### ISSUE TITLE
Power Swing's auto skill Axe Boomerang

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#3515]
rAthena Hash:
41dbb30

Client Date:
2018

Server Mode:
Renewal

Description of Issue: 
Result: Power Swing's autocasting of the skill Axe Boomerang is activating with any type of weapon.

Expected Result: Autocasting of the skill Axe Boomerang should only work when using Axe-type weapons.

How to Reproduce: kRO vídeo 2017: https://www.youtube.com/watch?v=vdfX2apxtdQ
Official Information: https://www.youtube.com/watch?v=vdfX2apxtdQ

* In the video the player is not using an ax and the skill does not come out automatically.

**Comment by aleos89** [comment]
Didn't notice this was originally reported. It was reported again in #5109 and fixed in #5123.
