### ISSUE TITLE
clif_instance_changewait what is this ?

### ISSUE THREAD

**Issue by Litro** [rathena/rathena#3517]
* **rAthena Hash**: 3cd7717

* **Client Date**: 2018-05-30bRagexeRE

* **Server Mode**: Pre-re

* **Description of Issue**: Instance creation is success but it fall into `clif_instance_changewait` and what its do? it seem the created instance before didn't destroyed cleanly, i have some instance script but i dont know if this script was the cause.
  * Result: instance creation success but, didn't enter
  * Expected Result: enter instance if it was success
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**: 
  
  
please check this script if it was the cause
https://pastebin.com/Li3XmfpM
https://pastebin.com/XVMYwL8H

**Comment by aleos89** [comment]
Are you referring to #3412?

**Comment by Litro** [comment]
i got this message on map server console, this happen after about one day server running and every instance even the official one, when created popin up error message like this... 
```
(09/24/2018 05:39:27) [ Error ] : instance_addmap: Failed to create initial map for instance 'Private MVP Room' (2).
(09/24/2018 05:46:25) [ Error ] : map_addinstancemap failed. map_num(1500) > map_max(1500)
```

**Comment by Litro** [comment]
is it `map_num` is the culprit? i didn't see it reduced when deleting isntance

**Comment by cydh** [comment]
@Litro can you try this
```diff
 src/map/map.cpp | 9 +++++++--
 1 file changed, 7 insertions(+), 2 deletions(-)

diff --git a/src/map/map.cpp b/src/map/map.cpp
index 3baa0aa80..2869ef4ba 100644
--- a/src/map/map.cpp
+++ b/src/map/map.cpp
@@ -2670,6 +2670,8 @@ int map_addinstancemap(const char *name, unsigned short instance_id)
 	dst_map->instance_src_map = src_m;
 	dst_map->users = 0;
 
+	ShowInfo("Created instance map '%s' from '%s' at num '%d'\n", dst_map->name, name, dst_m);
+
 	memset(dst_map->npc, 0, sizeof(dst_map->npc));
 	dst_map->npc_num = 0;
 
@@ -2760,10 +2762,13 @@ int map_delinstancemap(int m)
 	aFree(mapdata->block);
 	aFree(mapdata->block_mob);
 	map_free_questinfo(m);
-	mapdata->damage_adjust = {};
 
-	mapindex_removemap( mapdata->index );
+	mapindex_removemap(mapdata->index);
 	map_removemapdb(mapdata);
+
+	memset(&map[m], 0x00, sizeof(map[0]));
+	// Make delete timers invalid to avoid errors
+	map[m].mob_delete_timer = INVALID_TIMER;
 	return 1;
 }
 
```
