### ISSUE TITLE
Cotton Shirt[0] (ID:2301) drop need to be correct

### ISSUE THREAD

**Issue by AzarthMZintos** [rathena/rathena#3525]
* **rAthena Hash**: 79766cd

* **Client Date**: 2015-04-11a

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: the drop of 2301 is wrong from the mob Baby Desert Wolf(id:1107) = 2%, Baby Desert Wolf Ringleader(id:2855) = 2% and Furious Baby Desert Wolf(id:2856) =2%
  * Expected Result: the droups of 2301 should be Baby Desert Wolf(id:1107) = 1%, Baby Desert Wolf Ringleader(id:2855) = 5% and Furious Baby Desert Wolf(id:2856) = 5%
  * How to Reproduce: Look at the mobinfo database
  * Official Information:

Dont have acess to official information link to divine pride database:

https://www.divine-pride.net/database/item/2301

  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Related to #3410.
