### ISSUE TITLE
Poring(ID:1002) drops changes

### ISSUE THREAD

**Issue by AzarthMZintos** [rathena/rathena#3526]
* **rAthena Hash**: 79766cd99

* **Client Date**: 2015-11-04a

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: The drop from 1002 has empty bottle(id:713) at 15% it should exist.
  * Expected Result: The drop from 1002 should have fly wing(id:601) at 5% and the card rate(id:4001) should be change to 0,01% to 0,20%
  * How to Reproduce: Look at mobinfo database
  * Official Information:

dont have acess to official info divine pride link:

https://www.divine-pride.net/database/monster/1002/

  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Related to #3410.
