### ISSUE TITLE
Repeated items in item_trade.txt

### ISSUE THREAD

**Issue by BraisGabin** [rathena/rathena#353]
I was writting a parser for [`db/re/item_trade.txt`][item_trade] and I found that there are repeated items in it. Those repeated items are:

> 6039
6048
6674
6713
12514
12515
12516
12522
12523
14696
16481
16483
16505
16506
17338
17339
22525
22540

I wanted to make a PR to fix it but I found some repeated items with different flags. I don't know which flags are correct:
>6039
6048
6713
17338
17339
22540

[item_trade]: https://github.com/rathena/rathena/blob/master/db/re/item_trade.txt

**Comment by nanakiwurtz** [comment]
Okay thank you, I'll look into the flags tomorrow :)
