### ISSUE TITLE
Cancel in SG_FEEL does not work correctly

### ISSUE THREAD

**Issue by anacondaq** [rathena/rathena#3535]
hash: f16fc6c5df661a81b6e10c487660a835dfbdbd6a

### Problem

The video which demonstrates the problem: https://mega.nz/#!XE5GGICR!Swb4nvVv9WKwth-M_xDfBC1ziBw_yXljxGbZKeiFiYk

#### Details:
**Affected Skill:** Solar, Lunar and Stellar Perception (ID: 427 SG_FEEL)

#### What actually happens:
When you use the skill (cast it) and click on the cancel button instead of confirmation one, you will not be able to use skills anymore, and many other things locked too. Refresh command does not help. The only relog helps or warping to another map.

#### Expected result:
When you click on the cancel button, you must just cancel it, and be able to use any skills, and do other stuff like it always. Looks like some packet which unlocks skill usage is not sent.

#### How reproduce
1. `@job  Star Gladiator`
2. `@allskills`
3. `@blvl 99`
4. `@jlvl 99`
5. Open Skill WIndow
6. Select Skill Solar, Lunar, ... bla bla bla (see screenshot) ![](https://i.imgur.com/q3NWTt7.png)
7. In the message, dialogue clicks the cancel button. ![](https://i.imgur.com/M7uWRDa.png)
8. Now try to use any other skill, you will not be able to do it, which is not correct.

The function which is looks like a broken (does not have cancel button processing) (just my opinion): 
```cpp
/// Star Gladiator's Feeling map confirmation prompt (ZC_STARPLACE).
/// 0253 <which>.B
/// which:
///     0 = sun
///     1 = moon
///     2 = star
void clif_feel_req(int fd, struct map_session_data *sd, uint16 skill_lv)
{
	WFIFOHEAD(fd,packet_len(0x253));
	WFIFOW(fd,0)=0x253;
	WFIFOB(fd,2)=TOB(skill_lv-1);
	WFIFOSET(fd, packet_len(0x253));
	sd->menuskill_id = SG_FEEL;
	sd->menuskill_val = skill_lv;
}
```

**Comment by Lemongrass3110** [comment]
First of all: Thanks for reporting.

It would be nice if you could follow our template though. I know you kept all the info but in another structure.

The only thing I can confirm is that I am unable to use any skills after this. I can walk just normally. Could this be due to some other changes you made on your server or some configurations?
