### ISSUE TITLE
Crazy Uproar

### ISSUE THREAD

**Issue by Questune09** [rathena/rathena#3547]
* **rAthena Hash**:  Latest rathena rev.

* **Client Date**:  

 2017-06-14bRagexeRE.exe

* **Server Mode**: 

 Renewal

* **Description of Issue**: 
  * Result:  cant use Crazy Uproar while on mado
  * Expected Result:  i think you can use it also while on madogear
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
It was updated in #2103 for the Mechanic class update. If something changed or is incorrect from that patch then we can fix it.

**Comment by aleos89** [comment]
Fixed in fd91ab6.
