### ISSUE TITLE
Soul Linker skills.

### ISSUE THREAD

**Issue by linkineox** [rathena/rathena#355]
The skills of soul linker, have a automatic reset and the skillpoints dont back again.

reproduce:
Make a new character, up to soul linker.
up any skill and wait a moment.

last revision D:

**Comment by cydh** [comment]
let's see

**Comment by anacondaqq** [comment]
Confirm... it's related to this issue: https://github.com/rathena/rathena/issues/317

**Comment by cydh** [comment]
well, let's say, ur **\'last revision\'** is not the real last.
