### ISSUE TITLE
Crash on map server 3 time in the row

### ISSUE THREAD

**Issue by van84** [rathena/rathena#3558]
* **rAthena Hash**: 

474cb7d

* **Client Date**: 

2015

* **Server Mode**: 

Pre-renewal

* **Description of Issue**: 
crash

```
#0  status_calc_pc_sub (sd=sd@entry=0x55555fdaa6d0, opt=opt@entry=SCO_NONE) at status.cpp:3371
#1  0x0000555555750f21 in status_calc_pc_ (sd=sd@entry=0x55555fdaa6d0, opt=opt@entry=SCO_NONE) at status.cpp:4274
#2  0x0000555555751f59 in status_calc_bl_ (bl=0x55555fdaa6d0, flag=SCB_ALL, opt=SCO_NONE) at status.cpp:5322
#3  0x0000555555747402 in status_change_start (src=src@entry=0x55555fdaa6d0, bl=bl@entry=0x55555fdaa6d0, type=<optimized out>, rate=rate@entry=10000, val1=<optimized out>, val1@entry=5, va$
#4  0x00005555556bc10b in buildin_sc_start (st=0x7fffc28c2884) at script.cpp:11270
#5  0x00005555556ae0ec in run_func (st=st@entry=0x7fffc28c2884) at script.cpp:3996
#6  0x00005555556b2e00 in run_script_main (st=0x7fffc28c2884) at script.cpp:4271
#7  0x00005555556b3055 in run_script (rootscript=<optimized out>, pos=<optimized out>, rid=<optimized out>, oid=<optimized out>) at script.cpp:4056
#8  0x00005555556b310f in run_script (oid=0, rid=<optimized out>, pos=0, rootscript=<optimized out>) at script.cpp:4451
#9  script_run_autobonus (autobonus=<optimized out>, sd=<optimized out>, pos=<optimized out>) at script.cpp:4449
#10 0x000055555565bdf3 in pc_delautobonus (sd=0x55555fdd9ef8, sd@entry=0x55555fdaa6d0, autobonus=autobonus@entry=0x55555fdd9db8, max=max@entry=10 '\n', restore=false, restore@entry=true) a$
#11 0x000055555574ee6d in status_calc_pc_sub (sd=sd@entry=0x55555fdaa6d0, opt=opt@entry=SCO_NONE) at status.cpp:3522
#12 0x0000555555750f21 in status_calc_pc_ (sd=sd@entry=0x55555fdaa6d0, opt=opt@entry=SCO_NONE) at status.cpp:4274
#13 0x0000555555751f59 in status_calc_bl_ (bl=0x55555fdaa6d0, flag=SCB_ALL, opt=SCO_NONE) at status.cpp:5322
#14 0x0000555555747402 in status_change_start (src=src@entry=0x55555fdaa6d0, bl=bl@entry=0x55555fdaa6d0, type=<optimized out>, rate=rate@entry=10000, val1=<optimized out>, val1@entry=5, va$
#15 0x00005555556bc10b in buildin_sc_start (st=0x7fffc28c2144) at script.cpp:11270
#16 0x00005555556ae0ec in run_func (st=st@entry=0x7fffc28c2144) at script.cpp:3996
#17 0x00005555556b2e00 in run_script_main (st=0x7fffc28c2144) at script.cpp:4271
#18 0x00005555556b3055 in run_script (rootscript=<optimized out>, pos=<optimized out>, rid=<optimized out>, oid=<optimized out>) at script.cpp:4056
#19 0x00005555556b310f in run_script (oid=0, rid=<optimized out>, pos=0, rootscript=<optimized out>) at script.cpp:4451
#20 script_run_autobonus (autobonus=<optimized out>, sd=<optimized out>, pos=<optimized out>) at script.cpp:4449
#21 0x000055555565bdf3 in pc_delautobonus (sd=0x55555fdd9ef8, sd@entry=0x55555fdaa6d0, autobonus=autobonus@entry=0x55555fdd9db8, max=max@entry=10 '\n', restore=false, restore@entry=true) a$
#22 0x000055555574ee6d in status_calc_pc_sub (sd=sd@entry=0x55555fdaa6d0, opt=opt@entry=SCO_NONE) at status.cpp:3522
#23 0x0000555555750f21 in status_calc_pc_ (sd=sd@entry=0x55555fdaa6d0, opt=opt@entry=SCO_NONE) at status.cpp:4274
#24 0x0000555555751f59 in status_calc_bl_ (bl=0x55555fdaa6d0, flag=SCB_ALL, opt=SCO_NONE) at status.cpp:5322
#25 0x0000555555747402 in status_change_start (src=src@entry=0x55555fdaa6d0, bl=bl@entry=0x55555fdaa6d0, type=<optimized out>, rate=rate@entry=10000, val1=<optimized out>, val1@entry=5, va$
#26 0x00005555556bc10b in buildin_sc_start (st=0x7fffc28c21a4) at script.cpp:11270
#27 0x00005555556ae0ec in run_func (st=st@entry=0x7fffc28c21a4) at script.cpp:3996
#28 0x00005555556b2e00 in run_script_main (st=0x7fffc28c21a4) at script.cpp:4271
#29 0x00005555556b3055 in run_script (rootscript=<optimized out>, pos=<optimized out>, rid=<optimized out>, oid=<optimized out>) at script.cpp:4056
#30 0x00005555556b310f in run_script (oid=0, rid=<optimized out>, pos=0, rootscript=<optimized out>) at script.cpp:4451
#31 script_run_autobonus (autobonus=<optimized out>, sd=<optimized out>, pos=<optimized out>) at script.cpp:4449
#32 0x000055555565bdf3 in pc_delautobonus (sd=0x55555fdd9ef8, sd@entry=0x55555fdaa6d0, autobonus=autobonus@entry=0x55555fdd9db8, max=max@entry=10 '\n', restore=false, restore@entry=true) a$
#33 0x000055555574ee6d in status_calc_pc_sub (sd=sd@entry=0x55555fdaa6d0, opt=opt@entry=SCO_NONE) at status.cpp:3522
#34 0x0000555555750f21 in status_calc_pc_ (sd=sd@entry=0x55555fdaa6d0, opt=opt@entry=SCO_NONE) at status.cpp:4274
#35 0x0000555555751f59 in status_calc_bl_ (bl=0x55555fdaa6d0, flag=SCB_ALL, opt=SCO_NONE) at status.cpp:5322
#36 0x0000555555747402 in status_change_start (src=src@entry=0x55555fdaa6d0, bl=bl@entry=0x55555fdaa6d0, type=<optimized out>, rate=rate@entry=10000, val1=<optimized out>, val1@entry=5, va$
#37 0x00005555556bc10b in buildin_sc_start (st=0x7fffc28c2204) at script.cpp:11270
```

**Comment by van84** [comment]
its actually start here then it does a unfinited loop until it crash



#13368 0x0000555555747402 in status_change_start (src=src@entry=0x55555fdaa6d0, bl=bl@entry=0x55555fdaa6d0, type=<optimized out>, rate=rate@entry=10000, val1=<optimized out>, val1@entry=5, val2=<optimized out>, val3=<optimized out>, val$
#13369 0x00005555556bc10b in buildin_sc_start (st=0x7fffef8fa914) at script.cpp:11270
#13370 0x00005555556ae0ec in run_func (st=st@entry=0x7fffef8fa914) at script.cpp:3996
#13371 0x00005555556b2e00 in run_script_main (st=0x7fffef8fa914) at script.cpp:4271
#13372 0x00005555556b3055 in run_script (rootscript=<optimized out>, pos=<optimized out>, rid=<optimized out>, oid=<optimized out>) at script.cpp:4056
#13373 0x00005555556b310f in run_script (oid=0, rid=<optimized out>, pos=0, rootscript=<optimized out>) at script.cpp:4451
#13374 script_run_autobonus (autobonus=<optimized out>, sd=<optimized out>, pos=<optimized out>) at script.cpp:4449
#13375 0x000055555565bdf3 in pc_delautobonus (sd=0x55555fdd9ef8, sd@entry=0x55555fdaa6d0, autobonus=autobonus@entry=0x55555fdd9db8, max=max@entry=10 '\n', restore=false, restore@entry=true) at pc.cpp:2363
#13376 0x000055555574ee6d in status_calc_pc_sub (sd=sd@entry=0x55555fdaa6d0, opt=opt@entry=SCO_NONE) at status.cpp:3522
#13377 0x0000555555750f21 in status_calc_pc_ (sd=sd@entry=0x55555fdaa6d0, opt=opt@entry=SCO_NONE) at status.cpp:4274
#13378 0x0000555555751f59 in status_calc_bl_ (bl=0x55555fdaa6d0, flag=SCB_ALL, opt=SCO_NONE) at status.cpp:5322
#13379 0x0000555555747402 in status_change_start (src=src@entry=0x55555fdaa6d0, bl=bl@entry=0x55555fdaa6d0, type=<optimized out>, rate=rate@entry=10000, val1=<optimized out>, val1@entry=5, val2=<optimized out>, val3=<optimized out>, val$
#13380 0x00005555556bc10b in buildin_sc_start (st=0x7fffef8fa854) at script.cpp:11270
#13381 0x00005555556ae0ec in run_func (st=st@entry=0x7fffef8fa854) at script.cpp:3996
#13382 0x00005555556b2e00 in run_script_main (st=0x7fffef8fa854) at script.cpp:4271
#13383 0x00005555556b3055 in run_script (rootscript=<optimized out>, pos=<optimized out>, rid=<optimized out>, oid=<optimized out>) at script.cpp:4056
#13384 0x00005555556b310f in run_script (oid=0, rid=<optimized out>, pos=0, rootscript=<optimized out>) at script.cpp:4451
#13385 script_run_autobonus (autobonus=<optimized out>, sd=<optimized out>, pos=<optimized out>) at script.cpp:4449
#13386 0x000055555565bdf3 in pc_delautobonus (sd=0x55555fdd9ef8, sd@entry=0x55555fdaa6d0, autobonus=autobonus@entry=0x55555fdd9db8, max=max@entry=10 '\n', restore=false, restore@entry=true) at pc.cpp:2363
#13387 0x000055555574ee6d in status_calc_pc_sub (sd=sd@entry=0x55555fdaa6d0, opt=opt@entry=SCO_NONE) at status.cpp:3522
#13388 0x0000555555750f21 in status_calc_pc_ (sd=sd@entry=0x55555fdaa6d0, opt=opt@entry=SCO_NONE) at status.cpp:4274
#13389 0x0000555555751f59 in status_calc_bl_ (bl=0x55555fdaa6d0, flag=SCB_ALL, opt=SCO_NONE) at status.cpp:5322
#13390 0x0000555555747402 in status_change_start (src=src@entry=0x55555fdaa6d0, bl=bl@entry=0x55555fdaa6d0, type=<optimized out>, rate=rate@entry=10000, val1=<optimized out>, val1@entry=5, val2=<optimized out>, val3=<optimized out>, val$
#13391 0x00005555556bc10b in buildin_sc_start (st=0x7fffef8fa6d4) at script.cpp:11270
#13392 0x00005555556ae0ec in run_func (st=st@entry=0x7fffef8fa6d4) at script.cpp:3996
#13393 0x00005555556b2e00 in run_script_main (st=0x7fffef8fa6d4) at script.cpp:4271
#13394 0x00005555556b3055 in run_script (rootscript=<optimized out>, pos=<optimized out>, rid=<optimized out>, oid=<optimized out>) at script.cpp:4056
#13395 0x00005555556b310f in run_script (oid=0, rid=<optimized out>, pos=0, rootscript=<optimized out>) at script.cpp:4451
#13396 script_run_autobonus (autobonus=<optimized out>, sd=<optimized out>, pos=<optimized out>) at script.cpp:4449
#13397 0x000055555565bdf3 in pc_delautobonus (sd=0x55555fdd9ef8, sd@entry=0x55555fdaa6d0, autobonus=autobonus@entry=0x55555fdd9db8, max=max@entry=10 '\n', restore=false, restore@entry=true) at pc.cpp:2363
#13398 0x000055555574ee6d in status_calc_pc_sub (sd=sd@entry=0x55555fdaa6d0, opt=opt@entry=SCO_FORCE) at status.cpp:3522
#13399 0x0000555555750f21 in status_calc_pc_ (sd=sd@entry=0x55555fdaa6d0, opt=opt@entry=SCO_FORCE) at status.cpp:4274
#13400 0x0000555555751f59 in status_calc_bl_ (bl=0x55555fdaa6d0, flag=SCB_ALL, opt=SCO_FORCE) at status.cpp:5322
#13401 0x00005a166b in battle_delay_damage_sub (tid=<optimized out>, tick=1173140459, id=<optimized out>, data=93825157716136) at battle.cpp:335
#13402 0x0000572f3a in main ()

**Comment by aleos89** [comment]
Are you using #3235?

**Comment by admkakaroto** [comment]
@aleos89  here too:

```
Core was generated by `./map-server'.
Program terminated with signal 11, Segmentation fault.
#0  0x00000000005598f7 in run_script_main (st=0x7bea96011764) at script.cpp:4316
4316                    enum c_op c = get_com(st->script->script_buf,&st->pos);
Missing separate debuginfos, use: debuginfo-install glibc-2.17-106.el7_2.8.x86_64 libgcc-4.8.5-11.el7.x86_64 libstdc++-4.8.5-11.el7.x86_64 pcre-8.32-15.el7_2.1.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb) bt full
#0  0x00000000005598f7 in run_script_main (st=0x7bea96011764) at script.cpp:4316
        c = <optimized out>
        cmdcount = 655348
        gotocount = 2048
        sd = <optimized out>
        stack = 0x7bea91f721d4
#1  0x0000000000559efd in run_script_timer (tid=<optimized out>, tick=<optimized out>,
    id=<optimized out>, data=<optimized out>) at script.cpp:4183
        st = <optimized out>
        node = 0x7bea8261cd04
#2  0x00000000006153aa in do_timer (tick=<optimized out>) at timer.c:369
        tid = 7706
        diff = -3
        __FUNCTION__.4296 = "do_timer"
#3  0x00000000004077ac in main (argc=1, argv=0x7d40228d7738) at core.cpp:370
        next = <optimized out>
```

**Comment by Lemongrass3110** [comment]
This is probably caused by one of your item scripts and causes an infinite autobonus loading.

**Comment by Playtester** [comment]
Note: I accidentally linked the commit to the wrong issue, just ignore it.
