### ISSUE TITLE
transform  sc  problem

### ISSUE THREAD

**Issue by julia40124009** [rathena/rathena#356]
SC_MTF_MHP
SC_MTF_MSP
SC_MTF_PUMPKIN
SC_MTF_HITFLEE
SC_JP_EVENT04
const.txt no see

https://github.com/rathena/rathena/commit/231710c0fa9c2f9f3d150417e4ca2392850dd41b#diff-7ae9828022505142aeffdca7376c4412

**Comment by cydh** [comment]
and SI_*

**Comment by cydh** [comment]
forgot mention this @d951fab876ecd29dc2e700d385018dc0c54bb341
