### ISSUE TITLE
Lauda Ramus with holy armor bug (party member Howling Mandragora status didn't get removed)

### ISSUE THREAD

**Issue by laziem** [rathena/rathena#3560]
* **rAthena Hash**: 67139f590

* **Client Date**: 2017

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Lauda Ramus didn't remove Howling Mandragora status party member when wear holy armor
  * Expected Result: All party member Howling Mandragora status should be removed too even with Holy armor
  * How to Reproduce: Cast Lauda Ramus, party member with holy armor will not get Howling Mandragora status removed, only the caster who got removed
  * Official Information: Confirmed at kRO https://github.com/rathena/rathena/pull/3258#issuecomment-404361892

* **Modifications that may affect results**: -

**Comment by admkakaroto** [comment]
https://github.com/rathena/rathena/issues/3036
