### ISSUE TITLE
3rd Jobs max lvl 175 doesn't show aura

### ISSUE THREAD

**Issue by hendra814** [rathena/rathena#3561]
* **rAthena Hash**:  lastest

* **Client Date**:  20180307 and 20180621

* **Server Mode**: Renewal

* **Description of Issue**: When character reach 175 base lvl, yellow aura doesn't appear
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by admkakaroto** [comment]
This is the problem of the Lua File, client side problem.

![a1](https://user-images.githubusercontent.com/6227618/46835149-bbcd3d80-cd83-11e8-8cca-02eddc3580c2.png)


I use 2018-06-21 and works.

**Comment by hendra814** [comment]
@admkakaroto
could you tell me what lua files need to be edit?
cause i'm using lastest zack translation files

**Comment by flamefury** [comment]
The level limit was raised some time this year (though the date is later than your version of the clients). It's possible your client comes after the 175 aura was removed in favour of the 185 one.

**Comment by admkakaroto** [comment]
@flamefury Did you at least look at the lua files? do not speak what you do not know, there are different auras now, search a little before.

**Comment by admkakaroto** [comment]
@hendra814 zack files are the best but they are outdated.

**Comment by anacondaqq** [comment]
@hendra814 
`lua files/service_korea/ExternalSettings_kr.lub`

**Comment by hendra814** [comment]
@admkakaroto i think zack files always update, but his files support too for client before 2018

@anacondaqq thanks already found the problem
