### ISSUE TITLE
Pet Evolution BUG

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#3564]
* **rAthena Hash**: 
* **Client Date**: 2018-06-21
* **Server Mode**: RE
* **Description of Issue**: Well, they closed the PR because of fights so I can not comment there, I'll report right here then.

If you have the material to evolve the pet in a larger amount than necessary all the material is consumed the moment you evolution your pet.

  * Result: Consuming more than enough material to evolve.
   * How to Reproduce: 
1.Take any pet, as an example I'm using Isis, PetEggID: 9021
2.Take the material for evolution you need: 639 = 3, 732 = 6, 10006 = 1, 954 = 300.
3.Take the necessary items to evolve in larger quantity, only item 10006.
4.Now evolve your isis.
5.She will have consumed the entire amount of item 10006 you have in inventory.

Obs: The problem only occurs when it is to consume equipment, does not include ETC or usable items. 

* **Modifications that may affect results**: https://github.com/rathena/rathena/pull/3544

**Comment by technoken** [comment]
Found minor issue too. Little isis egg has the same item id as choco egg.

**Comment by AzarthMZintos** [comment]
Some itens have bonus base on the pet intimacy/friendly this PR will make this avaible too? I mean the script  not necessary this item? https://www.divine-pride.net/database/item/19163/catherina-von-blood-1

**Comment by secretdataz** [comment]
@AzarthMZintos It's not related to my PR.

**Comment by AzarthMZintos** [comment]
Im not the only one who comment something unrelated to this issue but both of us is relate to the PR, read people comment first.

**Comment by Lemongrass3110** [comment]
@secretdataz can this be closed, since you already fixed it in your pull request?
