### ISSUE TITLE
Script/bonus for equip base on the pet intimacy level

### ISSUE THREAD

**Issue by AzarthMZintos** [rathena/rathena#3565]
* **rAthena Hash**: 441e8f965

* **Client Date**: 2018-06-21a

* **Server Mode**: Renewal

* **Description of Issue**:
  * Result:  Some itens "now" give bonus base on the pet intimacy level, but I don't see any mention of this in the bonus doc file 
  * Expected Result: "new" script for this kind of bonus to work
  * How to Reproduce: Look at this item at divine pride: https://www.divine-pride.net/database/item/19163/catherina-von-blood-1
  * Official Information:Only the divine pride link sorry
  

* **Modifications that may affect results**: Problably need to wait for the PR for pet evolution and stuffy to do this but just let anyone who know how to do it know =)

**Comment by secretdataz** [comment]
Can already be done with `getpetinfo`
```
if(getpetinfo(PETINFO_INTIMATE)) {
bonus bXXXX,Y;
} else {
bonus bXXXX,Z;
}
```
