### ISSUE TITLE
GS_DISARM dont strip weapon anymore.

### ISSUE THREAD

**Issue by RadianFord** [rathena/rathena#3567]
* **rAthena Hash**: 79766cd99eebbc507c82f1900df60e909e46a23e

* **Client Date**: 20170125

* **Server Mode**: Pre-renewal

* **Description of Issue**: The skill does not stripped the weapon anymore.
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**: Modification does not affect on the skill.
  
  

I made some checking from my old trunk files and I found this one.
```
OLD TRUNK:
	case GS_DISARM:
		rate = sstatus->dex / (4 * (7 - skill_lv)) + sstatus->luk / (4 * (6 - skill_lv));
		rate = rate + status_get_lv(src) - (tstatus->agi * rate / 100) - tstatus->luk - status_get_lv(bl);
		skill_strip_equip(src,bl, EQP_WEAPON, rate, skill_lv, skill_get_time(skill_id,skill_lv));
		clif_skill_nodamage(src,bl,skill_id,skill_lv,1);
		break;
```
and
```
NEW TRUNK:
	case GS_DISARM:
		skill_strip_equip(src, bl, skill_id, skill_lv);
		clif_skill_nodamage(src,bl,skill_id,skill_lv,1);
		break;
```

**Comment by aleos89** [comment]
This was cleaned up in #3493. Keep in mind there is still a success chance for the skill to strip the equipment.
