### ISSUE TITLE
KO_JYUMONJIKIRI (Kagerou Cross Slash) - does not work with huuma or dagger/shield

### ISSUE THREAD

**Issue by raynra** [rathena/rathena#357]
Git Hash/Date: d951fab876ecd29dc2e700d385018dc0c54bb341 / Mar-22-2015
Client Date: 2013-08-07a
Renewal
No source mods

Description:
Either this was not fixed, or is broken again recently:
https://rathena.org/board/tracker/issue-8797-cross-slash-of-ninja/

Same issue - Cross Slash only works with 2 daggers. It should also work with huuma type weapons or a dagger + shield.

**Comment by reigneil** [comment]
Confirmed.
naturally Ninja and KO cannot used 1 hand sword.
(sd->status.shield && !sd->weapontype2 && (sd->weapontype1 == W_DAGGER || sd->weapontype1 == W_1HSWORD))
so this check must be remove and also in skill_required_db replace it with Fuuma Shurikens
status.shield must be partnered with weapontype1 to make it work.
