### ISSUE TITLE
warning: large integer implicitly truncated to unsigned type [-Woverflow]

### ISSUE THREAD

**Issue by ghost** [rathena/rathena#3570]
* **rAthena Hash**: 308dc27

* **Client Date**: 20180620 (Not Affected)

* **Server Mode**: Renewal

* **Description of Issue**:  See image below.
![image](https://user-images.githubusercontent.com/5693492/46913981-aba69f80-cfc9-11e8-9a0e-fefea0ddd02f.png)

  * Result: Warning -Woverflow
  * Expected Result: No warning
  * How to Reproduce: Pull latest revision and recompile using CentOs7 using devtoolset-7
  * Official Information: N/A
  

* **Modifications that may affect results**: mmo.hpp MAX_STORAGE = 900

**Comment by lighta** [comment]
just need to replace by a static_cast<uint16>(sizeof(struct s_storage)).
But actually a static_assert might be good as well to ensure sizeof(struct s_storage) < uint16_max.
