### ISSUE TITLE
Devil's Tower Instance Error on NPC lucile

### ISSUE THREAD

**Issue by cahya1992** [rathena/rathena#3587]
* **rAthena Hash**: 

19d376cff
* **Client Date**: 
20180621

* **Server Mode**:  Renewal

* **Description of Issue**: 
  * Result: Talk to NPC Lucile and she did nothing
http://prntscr.com/l6x7dg
  * Expected Result: its Should like this
Talk to Lucille on the center, you will need to activate a machine. A cast bar will appear above your head and it is really long. While you're at it, mob of evil shadow will attack and intterupt your cast time. Make sure to kill all of them. Then do activate the machine again. Once done, talk to Huey to move to next room. 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**: 
  
  
Clean server

**Comment by Atemo** [comment]
The cast bar has been disabled for now because of some issue.
