### ISSUE TITLE
Medal of Honor (Merchant) 2725

### ISSUE THREAD

**Issue by Questune09** [rathena/rathena#3590]
* **rAthena Hash**: 

* **Client Date**: 

 20170614

* **Server Mode**: 

 Renewal

* **Description of Issue**: 
  * Result:  Medal of Honor (Merchant) 2725 doesnt give me %5 atk+matk and reduce delay %10 but it gives def and aspd

  * Expected Result:  Item should gives 5% atk+matk and reduce delay 10% also give def and aspd
  * How to Reproduce:  use Medal of Honor and equip it
  * Official Information: https://www.divine-pride.net/database/item/2725/medal-of-honor-merchant
   

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
```
2725,Medal_Merchant,Medal of Honor,4,20,,0,,1,,0,0x00040420,63,2,136,,70,0,0,{ bonus2 bAddClass,Class_All,5; bonus bMatkRate,5; bonus bAspdRate,10; bonus bMaxHP,500; bonus bMaxSP,50; bonus3 bAddEff,Eff_Curse,100,ATF_SHORT; },{},{}
```
Looks like it matches the kRO description from DP.
