### ISSUE TITLE
MAX_GUILD_STORAGE dont work (Limited to 500).

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#3591]
rAthena Hash: https://github.com/rathena/rathena/commit/fece0abe5c2df9092fefa261fd1351ba42045cfb

Client Date: 2018-06-20

Server Mode: RE

Description of Issue: The size of the storage guild is only 500. The value in mmo.cpp is 600 but within the game is 500.

Result: It should be 600 according to the mmo.cpp setting.

How to Reproduce:

**Comment by aleos89** [comment]
Did you comment out the `OFFICIAL_GUILD_STORAGE` define as well?

**Comment by Badarosk0** [comment]
No I just noticed the setup on mmo.

#define MAX_STORAGE 600 /// Max number of storage slots a player can have
#define MAX_GUILD_STORAGE 600 /// Max number of storage slots a guild

Now is this comment required?

**Comment by aleos89** [comment]
Actually, did you rebuild both your char-server and map-server after this change?

**Comment by Badarosk0** [comment]
Yes. Even commenting on this line the mapserver crash still continues.

#0  0x0000000000505680 in guild_checkskill (g=0x0, id=6) at guild.cpp:113
No locals.
#1  0x0000000000500db8 in clif_parse_LoadEndAck (fd=Unhandled dwarf expression opcode 0xf3
) at clif.cpp:10932
        guild_notice = false
        mapdata = 0xd938e0
#2  0x00000000004c9088 in clif_parse (fd=Unhandled dwarf expression opcode 0xf3
) at clif.cpp:21868
        cmd = 125
        packet_len = 2
        sd = 0x7fa8340
        pnum = 0
#3  0x000000000068e365 in do_sockets (next=Unhandled dwarf expression opcode 0xf3
) at socket.cpp:1304
        rfd = {fds_bits = {8192, 0 <repeats 15 times>}}
        timeout = {tv_sec = 0, tv_usec = 15077}
        ret = 0
        i = 13
#4  0x0000000000465963 in main (argc=1, argv=0x7fffffffde28) at core.cpp:368
        next = <value optimized out>
(gdb)
