### ISSUE TITLE
Channel System Delay Issue

### ISSUE THREAD

**Issue by RadianFord** [rathena/rathena#3596]
* **rAthena Hash**: 79766cd99eebbc507c82f1900df60e909e46a23e

* **Client Date**: 20170125

* **Server Mode**:  Pre-renewal

* **Description of Issue**: I'm still having issue with this channel delay the 1st time its working now its happening again even tho player is not spamming. After changing my timezone the issue show up.
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Same as #3017. The ticks are only 32bit so after a certain amount of time (24~ days or so) the 32bit limit will be met. The only reason we haven't adjusted this yet is because all of the client packets are still limited to 32bit for tick we don't have a graceful solution for this yet.
