### ISSUE TITLE
[RE] New Heal value of restorative items

### ISSUE THREAD

**Issue by zackdreaver** [rathena/rathena#3598]
* **rAthena Hash**: 474cb7d900a7f2e1b570a823127905def9a7bc0a

* **Client Date**: N/A

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Old heal value of restorative items
  * Expected Result: New Heal value of restorative items to match current kRO's
  * How to Reproduce: Use it
  * Official Information: kRO item_info

* **Modifications that may affect results**: N/A

List of affected items, from what I check:
501 = from 45-65 HP to 90 HP
502 = from 105-145 HP to 210 HP
503 = from 175-235 HP to 350 HP
504 = from 325-405 HP to 650 HP
598 = from 45-65 HP to 90 HP
599 = from 105-145 HP to 210 HP
11522 = from 400-800 HP to 800 HP AND reduced cooldown to 1 sec
11523 = from 600-1000 HP to 1200 HP AND reduced cooldown to 1 sec
11524 = from 800-1200 HP to 1600 HP AND reduced cooldown to 1 sec
11547 = from 500-700 HP to 1000 HP , from 60-85  SP to 120 SP
11565 = from 325-405 HP to 650 HP
11566 = from 175-235 HP to 350 HP
11569 = from 105-145 HP to 210 HP
11570 = from 45-65 HP to 90 HP

**Comment by aleos89** [comment]
I think the potions are no longer a range/"about" heal but a static heal. IE: Red Potion should heal a flat 90 HP.

kRO description states: "HP 를 90 가량 회복 시켜 준다" which translates to "Restores 90 HP". Unless G Translate failed me again, that's what I'm assuming has come from it.

**Comment by zackdreaver** [comment]
Ugh, yes I only saw the numbers with gibberish texts without checking the translation.
my bad

**Comment by AzarthMZintos** [comment]
If you use http://kafra.kr/#!/en/KRO/itemdetail/501 i dont know if the site is good but i have see some user metion it here, there KRO 501 red potion still is 45 something but SAK is 90 something, the status confirmed come from KRO or SAK?

**Comment by zackdreaver** [comment]
Just use divinepride site, if you don't want check the iteminfo,
it parsed all item desc if there an update for an item.

**Comment by AzarthMZintos** [comment]
Any update?

**Comment by aleos89** [comment]
I had started on this but stopped. This issue doesn't list all of the changes. When I looked through Divine-Pride there were several other healing items that were also changed. I think there were other things I ran into as well but can't quite remember now.

**Comment by aleos89** [comment]
This has been resolved in previous item database updates.
