### ISSUE TITLE
cart cannon 119 and 120 int

### ISSUE THREAD

**Issue by MrAntares** [rathena/rathena#360]
I'd like to forward a report from a player of my server:

"There is a gap in the cart cannon damage formula caused by the (int/40) part. Since we use only integer numbers, this causes severe anomalies in the damage of cart cannon, like at 120 INT the skill deals 33% more damage than on 119 INT. With these calculations any INT value besides 40, 80, 120 and 160 are pretty much pointless, since they don't improve the skill's damage. 
I doubt this is official, but I don't have enough evidence other than it just seem's stupid."

Any thoughts?

**Comment by Playtester** [comment]
Well Aegis often rounds down. Like only every 10 STR are relevant for Spiral Pierce damage. But it requires some testing.

**Comment by anacondaqq** [comment]
Dear @Playtester i planning to make a very big project to compare mechanic for pre-re and re on AEGIS for skills and formulas. How can i contact with you and talk about it?

**Comment by Playtester** [comment]
Send me a PM on forums with your Skype ID then I add you.

**Comment by cydh** [comment]
@MrAntares test this please
````
 src/map/battle.c | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/src/map/battle.c b/src/map/battle.c
index beef1e1..98d0ca1 100644
--- a/src/map/battle.c
+++ b/src/map/battle.c
@@ -3861,13 +3861,13 @@ static int battle_calc_attack_skill_ratio(struct Damage wd, struct block_list *s
 					strbonus = 130;
 				skillratio = 50 * skill_lv;
 				if(sd && sd->cart_weight)
-					skillratio += sd->cart_weight / 10 / (150 - strbonus) + pc_checkskill(sd,GN_REMODELING_CART) * 50;
+					skillratio += (int)(sd->cart_weight / 10. / (150. - strbonus)) + pc_checkskill(sd,GN_REMODELING_CART) * 50;
 			}
 			break;
 		case GN_CARTCANNON:
 			// ATK [{( Cart Remodeling Skill Level x 50 ) x ( INT / 40 )} + ( Cart Cannon Skill Level x 60 )] %
 			skillratio = 60 * skill_lv;
-			if( sd ) skillratio += (pc_checkskill(sd, GN_REMODELING_CART) * 50) * (status_get_int(src) / 40);
+			if( sd ) skillratio += pc_checkskill(sd, GN_REMODELING_CART) * 50 * status_get_int(src) / 40;
 			break;
 		case GN_SPORE_EXPLOSION:
 			skillratio = (100 * skill_lv) + (200 + status_get_int(src));

````

**Comment by reigneil** [comment]
it looks like another parenthesis disaster

**Comment by Playtester** [comment]
But as said, should first be verified if the parenthesis are also there on Aegis before removing them.

**Comment by cydh** [comment]
it's parenthesis disaster.
Aegis always did round down, but for float/double, not for int. :P

but, confirmed, every `int` gives different ratio. *fixing*
