### ISSUE TITLE
[RE] Feint Bomb and Fatal Menace skill updates

### ISSUE THREAD

**Issue by zackdreaver** [rathena/rathena#3602]
* **rAthena Hash**: 474cb7d900a7f2e1b570a823127905def9a7bc0a

* **Client Date**: N/A

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Feint Bomb and Fatal Menace on rA has Max Level of 5 and 3
  * Expected Result: Feint Bomb and Fatal Menace Max Level should be 10 and updated formula
  * How to Reproduce: use it
  * Official Information: kRO skillinfolist and https://www.divine-pride.net/forum/index.php?/topic/3280-16th-anniversary-update-note-part-1/

* **Modifications that may affect results**: N/A
  
  

Fatal Menace:
- Increases max level from 5 to 10.
- Removes teleport effect.
- When uses skill while dagger is equipped. Damage will be doubled.
- From level 7. Increases Hit rate.

Feint Bomb:
- Increases max level from 3 to 10.
- Increases travel distance depends on skill level.

**Comment by aleos89** [comment]
Are you sure Feint Bomb should be that high of a level? I think you're confusing the skill with another. I don't see Feint Bomb being adjusted in the kRO Dev Notes for the Shadow Chaser class update.

**Comment by zackdreaver** [comment]
It's from kRO skillinfolist.lub,
there are many 3rd classes skill rebalanced by kRO months ago,
maybe the news was mixed with those, sorry don't have the linl

**Comment by admkakaroto** [comment]
Ziu has the link, in addition he posted on his page the information of everything that was changed.

**Comment by aleos89** [comment]
Do you happen to have the link @admkakaroto? I can only find Ziu's Shadow Chaser Improvement post but it only states what @zackdreaver linked to the previous PR.

**Comment by admkakaroto** [comment]
@aleos89 i'm at work now, but in a few hours will put here if i find.

**Comment by FrFrMako** [comment]
https://www.divine-pride.net/forum/index.php?/topic/3280-16th-anniversary-update-note-part-1/

**Comment by zackdreaver** [comment]
Ah yes, not only Feint Bomb i see.

Fatal Menace:
- Increases max level from 5 to 10.
- Removes teleport effect.
- When uses skill while dagger is equipped. Damage will be doubled.
- From level 7. Increases Hit rate.
