### ISSUE TITLE
Costumes display in WoE map

### ISSUE THREAD

**Issue by zackdreaver** [rathena/rathena#3604]
* **rAthena Hash**: 3b7fbb0d5fc92bcc3701d7cdd30ad2623305d5aa

* **Client Date**: Any client that support costume headgears/garment

* **Server Mode**: Both

* **Description of Issue**: 
  * Result: In WoE area costume headgears/garment are displayed
  * Expected Result: In WoE area costume headgears/garment shouldn't be displayed
  * How to Reproduce: Go to WoE map with costume equipped
  * Official Information: Self test in iRO WoE map
  

* **Modifications that may affect results**: n/a
  
  

No idea with kRO, maybe only iRO thing.

**Comment by admkakaroto** [comment]
Is not this just in WOE TE? in the others they work yes.

**Comment by zackdreaver** [comment]
There are no WoE 1st edition maps?

**Comment by RadianFord** [comment]
Maybe its an iRO thing that they hide those costume headgears during WoE times.

**Comment by aleos89** [comment]
```
//ADD_PROPERTY(DISABLE_COSTUMEITEM,TRUE);
```
These are all commented out of the PvP/Agit/Agit 1.5 maps.
