### ISSUE TITLE
[RE-kRo Main] Drop with random option & light effect

### ISSUE THREAD

**Issue by Balferian** [rathena/rathena#3610]
* **rAthena Hash**: 

* **Client Date**: 2018+

* **Server Mode**: Renewal

* **Description of Issue**: Weapons & Equipment (not at all items) with random options.
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: I`m starting to play at kRo-renewal server (not zero) and i see that drops (weapons/equips) from monster have a random options and light effect (weapon/equip/card) when it droped on the ground.
  

* **Modifications that may affect results**: 
  
  
![screen 000](https://user-images.githubusercontent.com/16213511/47377006-ccbf6c80-d6fc-11e8-95f0-f78cdb352a73.jpg)
![screen 003](https://user-images.githubusercontent.com/16213511/47376869-72bea700-d6fc-11e8-955a-ef1454b0420f.jpg)
![screen 046](https://user-images.githubusercontent.com/16213511/47376954-a994bd00-d6fc-11e8-90d3-a5bcb287dcf4.jpg)
![screen 047](https://user-images.githubusercontent.com/16213511/47376955-a994bd00-d6fc-11e8-8644-bec89b13136d.jpg)

**Comment by admkakaroto** [comment]
Light effect is this: https://github.com/HerculesWS/Hercules/pull/1939/files

Packet: 0xadd

https://github.com/HerculesWS/Hercules/blob/stable/doc/item_db.txt#L374-L381

`DropEffectMode: Set attribute for ShowDropEffect. [ZERO client or PACKETVER >= 20180418]`

**Comment by OptimusM** [comment]
the low grade items, like knife and shirt (really low lvl stuff) seems ok to me to have that option (actually didn´t hear any about thath patch), but im pretty sure that, the Tornade Axe is from Charleston instance enchants (those one from charleston update) i know u can enchant those whit [option2] enchant, but enchanting outside the instance by NPC.

**Comment by Balferian** [comment]
> the low grade items, like knife and shirt (really low lvl stuff) seems ok to me to have that option (actually didn´t hear any about thath patch), but im pretty sure that, the Tornade Axe is from Charleston instance enchants (those one from charleston update) i know u can enchant those whit [option2] enchant, but enchanting outside the instance by NPC.

Yes you are right about Tornado Axe, my mistake.
But low grade equips have random options when it drop from monsters.

**Comment by zackdreaver** [comment]
@Balferian
If you don't mind,
Would it be possible for you to record your gameplay when opening vended items by players and share it with us?
It's **For research purposes**

**Comment by Balferian** [comment]
> @Balferian
> If you don't mind,
> Would it be possible for you to record your gameplay when opening vended items by players and share it with us?
> It's **For research purposes**

This is a small part of the entire market.
I can record more if necessary.
What type of item are you more interested in?
https://youtu.be/RIKlDG6kP-4

**Comment by zackdreaver** [comment]
Thanks, but you misunderstood what I mean,
Can you record it with a **Built-in Record Feature** of ragnarok client, not in video format.
More vendors that you record the better.

**Comment by Balferian** [comment]
> Thanks, but you misunderstood what I mean,
> Can you record it with a **Built-in Record Feature** of ragnarok client, not in video format.
> More vendors that you record the better.

Prontera merchants ~4/5:
https://www.dropbox.com/s/c040sf4cf5x2wgn/2018-11-05.rrf?dl=0

**Comment by Balferian** [comment]
I accidentally closed the issue >_<

**Comment by zackdreaver** [comment]
The link is disabled because of too many request,
can you upload it through github in zip/rar package instead?
Just click **Attach files by dragging & dropping or selecting them.** to upload your file.

**Comment by Balferian** [comment]
> The link is disabled because of too many request,
> can you upload it through github in zip/rar package instead?
> Just click **Attach files by dragging & dropping or selecting them.** to upload your file.

[2018-11-05.zip](https://github.com/rathena/rathena/files/2547547/2018-11-05.zip)
