### ISSUE TITLE
Functions calls do not always keep the current instances count of a script

### ISSUE THREAD

**Issue by Tokeiburu** [rathena/rathena#3613]
* **rAthena Hash**: b38b56f4d

* **Client Date**: Any

* **Server Mode**: Both

* **Description of Issue**: 
  * Result: If you run a user function inside a script, and that the function is terminated with `st->state = END;` (from close, select/menu or script errors), the original script's instances count will keep increasing until it reaches 65k and triggers the warning below. There aren't actually the amount of scripts being ran and the script instances counter doesn't have a strong purpose from what I could see.
```
Over 65k instances of 'Test' script are being run!
Over 65k instances of 'Test' script are being run!
Over 65k instances of 'Test' script are being run!
```

It's worth mentionning that the `end` statement has a "special" code that properly terminates the script if it's executed from a function call. It sets the stack's script back to the original caller.
```
BUILDIN_FUNC(end)
{
	TBL_PC* sd;

	sd = map_id2sd(st->rid);

	st->state = END;

	if (st->stack->defsp >= 1 && st->stack->stack_data[st->stack->defsp-1].type == C_RETINFO) {
		int i;

		for(i = 0; i < st->stack->sp; i++) {
			if (st->stack->stack_data[i].type == C_RETINFO) { // Grab the first, aka the original
				struct script_retinfo *ri = st->stack->stack_data[i].u.ri;
				st->script = ri->script;
				break;
			}
		}
	}
```
  * Expected Result: Not trigger the warning.
  * How to Reproduce: Well, it will take a long time to reproduce (as you'd need to click that NPC 65k times, but you can use this:
```
function	script	Test_Function	{
	mes "...";
	
	switch(select("Ok")) {
		case 1:
			mes "Ok";
			close;
	}
	
	return;
}

prontera,150,188,6	script	Test	77,{
	//dispbottom "Script count = " + script_getinstancescount(getnpcid(0));
	callfunc("Test_Function");
	end;
}
```
  * Official Information:
  

I'd personally simply fetch the original script in the stack, in run_script_main, before calling script_free_state (and remove the code from the end's command). Something like this:
```
	} else {
		if (st->stack && st->stack->defsp >= 1 && st->stack->stack_data[st->stack->defsp-1].type == C_RETINFO) {
			int i;
		
			for (i = 0; i < st->stack->sp; i++) {
				if (st->stack->stack_data[i].type == C_RETINFO) { // Grab the first, aka the original
					struct script_retinfo *ri = st->stack->stack_data[i].u.ri;
					st->script = ri->script;
					break;
				}
			}
		}

		//Dispose of script.
		if ((sd = map_id2sd(st->rid))!=NULL)
		{	//Restore previous stack and save char.
			if(sd->state.using_fake_npc){
				clif_clearunit_single(sd->npc_id, CLR_OUTSIGHT, sd->fd);
				sd->state.using_fake_npc = 0;
			}
			//Restore previous script if any.
			script_detach_state(st, true);
			if (sd->vars_dirty)
				intif_saveregistry(sd);
		}
		script_free_state(st);
	}
```

**Comment by xDarp** [comment]
this actually are crashing my server, how can fix it?
thanks!
