### ISSUE TITLE
Reins Of Mount + Camouflage and Others

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#3614]
* **rAthena Hash**: Any
* **Client Date**: Irrelevant
* **Server Mode**: Irrelevant
* **Description of Issue**: It is possible to use the Reins Of Mount item right after using Camouflage.
  * Expected Result: When using Rein, you should cancel Camouflage effect.
  * How to Reproduce: Use the skill and then use the item.

**Comment by aleos89** [comment]
Guess I'm confused here. The description of Fear Breeze says if a weapon is unequipped the status is cancelled. Is there supposed to be some restriction of using Reins of Mount after Fear Breeze?

**Comment by admkakaroto** [comment]
@aleos89 sorry skill name is 'Camouflage' hehe, and others similar skills, has Stealth...
