### ISSUE TITLE
Skill Water Evasion + Freezing Spear

### ISSUE THREAD

**Issue by Balferian** [rathena/rathena#3615]
* **rAthena Hash**: b549e0f

* **Client Date**: -

* **Server Mode**: RE

* **Description of Issue**: In description watery evasion skill says:
The area targeted by Watery Evasion will incrase the damage of Freezing Spear skill.
  * Result: Watery Evasion don`t affect to power of Freeezing Spear.
  * Expected Result: Watery Evasion must increase power of Freeezing Spear.
  * How to Reproduce: 
  * Official Information: I am test it on kRo - RE (sakray)
[iRoWiki Classic](https://irowiki.org/classic/Watery_Evasion) - don't say about it.
[iRoWiki Renewal](https://irowiki.org/wiki/Watery_Evasion) - incrase power of Freezing Spear.

  
![watery evasion](https://user-images.githubusercontent.com/16213511/47496566-df05eb80-d85f-11e8-9271-764f9a25d770.png)

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Is this a renewal specific thing or also pre-renewal? Not sure if this was something that was missed in pre-renewal as well.

**Comment by Balferian** [comment]
> Is this a renewal specific thing or also pre-renewal? Not sure if this was something that was missed in pre-renewal as well.

I can't confirm it on pre-re official servers.
But on [iRoWiki Classic](https://irowiki.org/classic/Watery_Evasion) don't say about it.
[iRoWiki Renewal](https://irowiki.org/wiki/Watery_Evasion) - incrase power of Freezing Spear.

**Comment by Playtester** [comment]
It was by the way originally intended to be 70% damage without watery evasion and 100% with watery evasion, but there was an "official bug" in pre-re that caused the skill to always do 100% damage. It was only fixed after the renewal update.
