### ISSUE TITLE
Shield Buffs Removed When Switches Shield

### ISSUE THREAD

**Issue by khnkhymkh** [rathena/rathena#3619]
* **rAthena Hash**: 926e37c
* **Client Date**:  2015-11-04
* **Server Mode**: Pre-Renewal

* **Description of Issue**:  Paladin casts Auto-Guard and Reflect Shield. Then, switches shield.
  * Result: The Auto-Guard and Reflect Shield was removed.
  * Expected Result: The Auto-Guard and Reflect Shield will stay unless I manually removed the shield. (I tested it in Hercules, and its working fine.)

**Comment by secretdataz** [comment]
Hercules is not a valid source of information

**Comment by aleos89** [comment]
Both of these skills require shields to be active.
