### ISSUE TITLE
unit_remove_map: unexpected state when removing player

### ISSUE THREAD

**Issue by Zeloss** [rathena/rathena#3620]
* **rAthena Hash**:  b549e0fed585cac75206447d05db36da18bd28d0

* **Client Date**: 20180620, 20151104

* **Server Mode**: Renewal

* **Description of Issue**: When you enter to some warps with camouflage the client map doesn't change but you are really changing to the warped map.

`(10/25/2018 11:01:33) [ Debug ] : unit_remove_map: unexpected state when removing player AID/CID:2000000/150000 (active=1 connect_new=0 rewarp=0 changemap=1 debug_remove_map=1) from map=ver_tunn (users=0). Previous call from unit.cpp:3121(unit_remove_map_pc), current call from unit.cpp:3121(unit_remove_map_pc). Please report this!!!`

  * Result: The map does't change (no loading time), but you can see the npcs and monsters from the map you warped.
  * Expected Result: No activating warp while in camouflage.
  * How to Reproduce: 
1.  ` @warp verus04 201 166`
2. Use Camouflage
3. Walk to the warp

**Comment by admkakaroto** [comment]
This: https://github.com/rathena/rathena/issues/3420
