### ISSUE TITLE
NPC_RUN don`t work

### ISSUE THREAD

**Issue by Balferian** [rathena/rathena#3622]
* **rAthena Hash**: 84b4f09

* **Client Date**: 

* **Server Mode**: Pre-Re/Re

* **Description of Issue**: monsters when using the skill (NPC_RUN) does not run away from the target.
For example monster Antonio (id 1247).
  * Result: When skill used it only show HELP emotion and don`t run away from target.
  * Expected Result: When monsters use skill NPC_RUN they must run away from the target (players)
  * How to Reproduce: 
  * Official Information: Skill must work like at that video from kRo (Skill id: 354)
[YouTube link](https://youtu.be/Z9NTpwdCmy8) - Halloween Event 2018

  

* **Modifications that may affect results**:

**Comment by vykimo** [comment]
What is the message sent by the monster in English?

**Comment by aleos89** [comment]
I think it's something along the lines of "Jack isn't going to stay here!".

**Comment by vykimo** [comment]
Ok so it isnt related to the skill.
