### ISSUE TITLE
pre-re ATK for PC types is now wrong!!

### ISSUE THREAD

**Issue by mrjnumber1** [rathena/rathena#3623]
* **rAthena Hash**: current

* **Client Date**: x

* **Server Mode**: pre-renewal

* **Description of Issue**: 
  * Result: ATK boost for every 10 str(or dex for guns/whips/instruments/bows) is no longer being granted for BL_PC
  * Expected Result: with 100 STR, a melee char will have 100 + (100/10)^2=200 atk. on rAthena now, we only have 100 ATK!
  * How to Reproduce: get every 10 str/dex values
  * Official Information: see expected result
  

* **Modifications that may affect results**: i believe this was a recent bug addition, when modifications to status_calc_base_atk were done

**Comment by lelouch22** [comment]
I was thinking if this was related to commit https://github.com/rathena/rathena/commit/fe197bfa120aef5fd31c6896122b35fdc06774b4
