### ISSUE TITLE
Feint Bomb BUG

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#3625]
* **rAthena Hash**: 

https://github.com/rathena/rathena/commit/aa275c57c939ef94d83dc3d2b1cbf34d59115d96

* **Client Date**: 

20180620

* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result: The skill is not hiding the player after use. Sometimes it hides and sometimes it does not hide. You're failing.
  * Expected Result: Should always hide the player after using the skill.
  * How to Reproduce: Just use the skill (Feint Bomb) the player will be hidden for a few seconds.

  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
I guess I'm confused here. I don't see why it would sometimes hide and sometimes not. The hidden state doesn't last very long and ends when the bomb explodes.

**Comment by Badarosk0** [comment]
I checked and it works in the current rathena commit. I will close this issue.
