### ISSUE TITLE
Guild skill code duplication

### ISSUE THREAD

**Issue by vykimo** [rathena/rathena#3628]
* **rAthena Hash**: 594d95f14
* **Client Date**: no importance
* **Server Mode**: both
* **Description of Issue**: Code duplication for skills :  GD_BATTLEORDER, GD_REGENERATION, GD_RESTORE in skill.cpp
* **Modifications that may affect results**: Code reduction

**Comment by aleos89** [comment]
Fixed in 98ba549022f6b72a41363788d6aeb52451a5aa0a.
