### ISSUE TITLE
No flying angel wing shown in Equipment Window

### ISSUE THREAD

**Issue by donkeyg** [rathena/rathena#363]
No item shown in Equipment Window but my character has flying angel wing

https://rathena.org/board/uploads/monthly_03_2015/post-2303-0-94021100-1427097510.png

whats the problem sir? anyone pls help me

im only able to show when i type @refresh / @go 0 

hi anyone has solution? need to fix it badly..

i tried it even my manteau/shoes/armor also same.

**Comment by aleos89** [comment]
I have no problem equipping items using ee24f5c and the 2013-08-07 client.

What client and pull of rA are you using?

**Comment by nanakiwurtz** [comment]
Maybe it's your grf problem
And can you upload your screenshot somewhere else? Because currently it doesn't allow hotlinking

**Comment by aleos89** [comment]
Closing as this is a client related issue, not server.
