### ISSUE TITLE
new specialeffect2 don't work with variable

### ISSUE THREAD

**Issue by luizragna** [rathena/rathena#3632]
**Don't Work:**
```
.@Effect = 234;
specialeffect2 (.@Effect, AREA, strcharinfo(PC_NAME)); 

```

**Work:**

` specialeffect2 (234, AREA, strcharinfo(PC_NAME));`

**Comment by aleos89** [comment]
Next time, please follow the issue template and fill it out.

**Comment by aleos89** [comment]
Went back and tested this. The `script_getnum` function should already be checking for variables:
`#define script_getnum(st,val) conv_num(st, script_getdata(st,val))`

My tests concluded that the current master usage works just fine with variables.

**Comment by Lemongrass3110** [comment]
PC_NAME is a hercules script constant. If you want to use this on rAthena please convert your script correctly.
