### ISSUE TITLE
White Imprison + Reflect

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#3634]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/7066cac9a4df30851a31a717bc6635313b006489
* **Client Date**: 2018-06-21
* **Server Mode**: RE
* **Description of Issue**: Reflecting is working on targets that are over White Imprison effect.
  * How to Reproduce: Use White Imprison on a target with any item to reflect and attack this target.

![a1](https://user-images.githubusercontent.com/6227618/47621393-de768a80-dad5-11e8-85b5-9ed8ee3a17f0.png)

**Comment by admkakaroto** [comment]
kro blocked the connections of many countries and unfortunately mine was also blocked, I can not access the kro again.

**Comment by aleos89** [comment]
Confirmed. Reflect damage should not be triggering.
