### ISSUE TITLE
NPC dialog don't close and clear when use @reloadscript

### ISSUE THREAD

**Issue by kukuasir1** [rathena/rathena#3637]
* **rAthena Hash**: 
a5c3785
* **Client Date**: 
20180621

* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result: when use @reloadscript, NPC dialog do not show the close button.  when script reloaded, the dialog could not close..
  * Expected Result: show close button and can close the dialog.
  * How to Reproduce: open any NPC dialog and use the shortcut execute @reloadscript command.
  * Official Information:none
  
* **Modifications that may affect results**: 
pc.cpp
void pc_close_npc(struct map_session_data *sd,int flag)
when set 'sd->st->state = END;' 
but dont execute 
clif_scriptclose(sd, sd->npc_id);
clif_scriptclear(sd, sd->npc_id);

**Comment by aleos89** [comment]
There shouldn't be any reason to send those two functions on END because there should be no dialog open when the script state is set to END. `@reloadscript` should forcefully send the close button to the player:
```cpp
		iter = mapit_getallusers();
		for( pl_sd = (TBL_PC*)mapit_first(iter); mapit_exists(iter); pl_sd = (TBL_PC*)mapit_next(iter) )
			pc_close_npc(pl_sd,2);
		mapit_free(iter);
```

**Comment by kukuasir1** [comment]
@aleos89 
In this loop, the ```pc_close_npc``` 2nd param the flag is 2,
when execute ```sd->st->state = ((flag==1 && sd->st->mes_active)?CLOSE:END);```
```st->state``` always be set to ```END```
so, whatever dialog open or not open, the ```clif_scriptclose``` and ```clif_scriptclear``` didn't execute

**Comment by aleos89** [comment]
You're right. Was in a meeting and miss-read the `pc_close_npc` comment.
