### ISSUE TITLE
Baby Summoner cant use some of Summoner skills

### ISSUE THREAD

**Issue by aDwCarrazzone** [rathena/rathena#3641]
rAthena Hash:
456d9584523fd27b82db18900bef76a946613233

Client Date:
20180620

Server Mode:
Renewal

Description of Issue:

    Result: Baby Summoner cant use all skills Summoner skills.
    Expected Result: Baby Summoner can use all Summoner skills.
    How to Reproduce: Simply use @job 4220 and use @allskills.
    Official Information:none

Modifications that may affect results:
adding these to trunk\db\re\skill_tree.txt

4220,5044,1,5024,1,0,0,0,0,0,0,0,0 //SU_SOULATTACK##
4220,5045,5,100,0,5047,5,0,0,0,0,0,0,0,0 //SU_POWEROFFLOCK##
4220,5046,5,100,0,5045,5,0,0,0,0,0,0,0,0 //SU_SVG_SPIRIT##
4220,5047,5,100,0,5031,1,0,0,0,0,0,0,0,0 //SU_HISS##
4220,5048,5,100,0,5053,5,0,0,0,0,0,0,0,0 //SU_NYANGGRASS##
4220,5049,5,100,0,5037,1,0,0,0,0,0,0,0,0 //SU_GROOMING##
4220,5050,5,100,0,5049,5,0,0,0,0,0,0,0,0 //SU_PURRING##
4220,5051,5,100,0,5050,5,0,0,0,0,0,0,0,0 //SU_SHRIMPARTY##
4220,5052,1,100,0,5046,5,0,0,0,0,0,0,0,0 //SU_SPIRITOFLIFE##
4220,5053,5,100,0,5025,1,0,0,0,0,0,0,0,0 //SU_MEOWMEOW##
4220,5054,1,100,0,5048,5,0,0,0,0,0,0,0,0 //SU_SPIRITOFLAND##
4220,5055,5,100,0,5025,1,0,0,0,0,0,0,0,0 //SU_CHATTERING##
4220,5056,1,100,0,5051,5,0,0,0,0,0,0,0,0 //SU_SPIRITOFSEA##

**Comment by admkakaroto** [comment]
Here is official info of this?
