### ISSUE TITLE
Crash client (disablenpc()/enablenpc() + delay timer)

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#3645]
* **rAthena Hash**: 

https://github.com/rathena/rathena/commit/aa275c57c939ef94d83dc3d2b1cbf34d59115d96

* **Client Date**: 

20180621

* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result: 
If you add any delay between disablenpc and enablenpc there is a chance of random crash client generation.

**Example 01 reproduce:**
```
prontera,106,242,3	script	Teste bau BUG#1	4_TREASURE_BOX,{
specialeffect EF_COIN;
disablenpc( strnpcinfo(0) );
sleep 100;
enablenpc( strnpcinfo(0) );
end;
}

```
**Example 02 reproduce:**
```
prontera,106,242,3	script	Teste bau BUG#1	4_TREASURE_BOX,2,2,{
OnTouch:
specialeffect EF_COIN;
disablenpc( strnpcinfo(0) );
end;
}
-	script	#timeteste	-1,{
end;

	OnTimer100:
		stopnpctimer;
		setnpctimer 0;
		startnpctimer;

			enablenpc "Teste bau BUG#1";

	end;

OnInit:
initnpctimer;
end;
}
```

**In this example below the crash client does not occur:**
```
prontera,106,242,3	script	Teste bau BUG#1	4_TREASURE_BOX,{
specialeffect EF_COIN;
disablenpc( strnpcinfo(0) );
//sleep 100;
enablenpc( strnpcinfo(0) );
end;
}
```

  * Expected Result: 
Do not generate crash client when clicking NPC in disablenpc + delay script.

**Comment by vykimo** [comment]
Not confirmed with latest rAthena and 20180620.

**Comment by zellkennedy** [comment]
Can't reprocue in 20180620 too.

**Comment by Badarosk0** [comment]
It is not a simple problem to reproduce but it does exist. It seems to me that it is linked to the disable script effect along with the NPC hide. This has existed for some years now. For those of you who use rAthena as an emulator you should have noticed a report of players reporting that the game closed in the middle of some instance for example. It is not constant but there is.
Try to use the script I provided above and try to play as if you were a player. Click the chests repeatedly until the problem occurs.

**Comment by vykimo** [comment]
If its such a random problem. It should exist on official server too and maybe its clientside more than server side...

**Comment by cydh** [comment]
^depends, if the server sends wrong packet -> client crash

**Comment by Badarosk0** [comment]
The problem only occurs with the 'disablenpc(x)' script.

**Comment by Badarosk0** [comment]
Check the PR @siriousb
