### ISSUE TITLE
Ray Genesis Skill no effect on MATK

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#3653]
* **rAthena Hash**: 

https://github.com/rathena/rathena/commit/13006e19a6bb447848f8357946c69be30a84dc54

* **Client Date**: 

20180620

* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result: 
RG's Genesis Ray MATK's portion it's not affecting skill's final damage as it's supposed to.

https://irowiki.org/wiki/Genesis_Ray

  * Expected Result: 
Increases damage based on MATK:
lvl1: 300%
lvl2: 600%
lvl3: 900%
lvl4: 1200%
lvl5: 1500%

**Comment by aleos89** [comment]
The 16th Anniversary Update updated Ray of Genesis:
```
 4.2.2 Genesis Ray

- Increases max level from 5 to 10.
- Changes damage type from holy (physical + magical) damage to holy magical damage.
- Reduces skill cooldown and delay.
- Changes SP consumption per level.
- Removes requirement of Banding party members and also removes increased damage from Banding party members too. 
```

This is somewhat part of #3602 (technically) but I have already started these and have pretty much completed it and will make a PR soon.

**Comment by zackdreaver** [comment]
Magic skills are weak in renewal mode,
But kRO revamped them with better gears+enchants,
so you need a very good gear to get higher damage.

Can't say anything about the formula.

**Comment by Badarosk0** [comment]
Look this:
https://cdn.discordapp.com/attachments/287455414042361863/511526184404910110/unknown.png

**Comment by aleos89** [comment]
The ATK part of the skill is gone and is only MATK now, so keep that in mind.
