### ISSUE TITLE
[RE] Platinum Shotel and Curved Sword class bitmask

### ISSUE THREAD

**Issue by zackdreaver** [rathena/rathena#3655]
* **rAthena Hash**: 13006e19a6bb447848f8357946c69be30a84dc54

* **Client Date**: N/A

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: itemID 13404 and 13405 use class bitmask 63
  * Expected Result: itemID 13404 and 13405 use class bitmask 18
  * How to Reproduce: check item_db
  * Official Information: kRO itemInfo

* **Modifications that may affect results**: N/A

**Comment by Atemo** [comment]
I guess the items include 3rd classes, 58.
