### ISSUE TITLE
SC_GT_CHANGE: map server crash (?)

### ISSUE THREAD

**Issue by raynra** [rathena/rathena#366]
Git Hash/Date: 4d5fc9604cea533f7d927dd41526bbbad3c800b2 / Dec-17-2014
Client Date: 2013-08-07a
Renewal
Source Mods: a few recent skills fixes backported to older revsion

Description:
Gentle Touch Change map server crash - not sure what the cause is, cannot test on current revision.

```
Core was generated by `./map-server'.
Program terminated with signal 8, Arithmetic exception.
#0  0x000000000059608c in status_change_start (src=0xbfb11c0, bl=0x7f081c6cc204, 
    type=SC_GT_CHANGE, rate=5, val1=5, val2=<value optimized out>, 
    val3=<value optimized out>, val4=0, tick=240000, flag=0 '\000') at status.c:9622
9622                                            val4 = ( 200/status_get_int(src2) ) * val1; // MDEF decrease: MDEF [(200 / Caster INT) x Skill Level]
Missing separate debuginfos, use: debuginfo-install keyutils-libs-1.4-4.el6.x86_64 krb5-libs-1.10.3-15.el6_5.1.x86_64 libcom_err-1.41.12-18.el6_5.1.x86_64 libselinux-2.0.94-5.3.el6_4.1.x86_64 mysql-libs-5.1.73-3.el6_5.x86_64 openssl-1.0.1e-16.el6_5.15.x86_64 zlib-1.2.3-29.el6.x86_64
(gdb) bt full
#0  0x000000000059608c in status_change_start (src=0xbfb11c0, bl=0x7f081c6cc204, 
    type=SC_GT_CHANGE, rate=5, val1=5, val2=<value optimized out>, 
    val3=<value optimized out>, val4=0, tick=240000, flag=0 '\000') at status.c:9622
        src2 = <value optimized out>
        sd = 0x0
        sc = 0x7f081c6cc584
        sce = <value optimized out>
        status = 0x7f081c6cc51c
        vd = 0x1bbd984
        opt_flag = <value optimized out>
        calc_flag = 590850
        undead_flag = 0
        val_flag = 0
        tick_time = 0
        sc_isnew = 1 '\001'
#1  0x0000000000562e9d in skill_castend_nodamage_id (src=0xbfb11c0, bl=0x0, 
    skill_id=2347, skill_lv=5, tick=443352067, flag=0) at skill.c:9462
        sd = <value optimized out>
        dstsd = <value optimized out>
        md = <value optimized out>
        dstmd = 0x0
        hd = <value optimized out>
        mer = 0x0
        sstatus = 0xbfb14e8
        tstatus = 0x7f081c6cc51c
        tsc = 0x7f081c6cc584
        tsce = 0x0
        chorusbonus = 0
        i = <value optimized out>
        type = SC_GT_CHANGE
#2  0x000000000058043a in skill_castend_id (tid=<value optimized out>, 
    tick=443352067, id=<value optimized out>, data=0) at skill.c:10625
        target = <value optimized out>
        src = 0xbfb11c0
        sd = <value optimized out>
        md = <value optimized out>
        ud = 0xbfb11e0
        sc = <value optimized out>
        inf = <value optimized out>
        inf2 = <value optimized out>
        flag = 0
#3  0x00000000005b1a3f in do_timer (tick=443352069) at timer.c:373
        tid = 5748
        diff = -2
        __FUNCTION__ = "do_timer"
#4  0x00000000005ae90c in main (argc=1, argv=<value optimized out>) at core.c:375
        next = <value optimized out>
```
status.c:9662 : val4 = ( 200/status_get_int(src2) ) * val1; // MDEF decrease: MDEF [(200 / Caster INT) x Skill Level]

skill.c:9462: clif_skill_nodamage(src,bl,skill_id,skill_lv, 
sc_start2(src,bl,type,100,skill_lv,bl->id,skill_get_time(skill_id,skill_lv)));

skill.c:10625: skill_castend_nodamage_id(src,target,ud->skill_id,ud->skill_lv,tick,flag);

timer.c:373: timer_data[tid].func(tid, timer_data[tid].tick, timer_data[tid].id, timer_data[tid].data);

core.c:375: int next = do_timer(gettick_nocache());

**Comment by anacondaqq** [comment]
oh...  Dec-17-2014
i think there are were so many changes at rAthena.... So, upgrade maybe will be painfull.

**Comment by theultramage** [comment]
> Program terminated with signal 8, Arithmetic exception.
>`val4 = ( 200/status_get_int(src2) ) * val1;`

This is an arithmetic divide-by-zero mistake. It happens when the casting player lowers their int to 0 and performs "Gentle Touch - Change". Please undo all that ?: operator juggling in SC_GT_CHANGE and SC_GT_REVITALIZE if it's not needed.

On an unrelated note, the behavior of SC_GT_CHANGE is not consistent with the info on [irowiki](http://irowiki.org/wiki/Gentle_Touch-Convert) - the calc for aspd and hpcost is different, and there is no mdef penalty mentioned. Please check.

**Comment by aleos89** [comment]
Follow up in 01a9372. Thanks!

And about the information. iROWiki is wrong. They don't have the post balance formulas posted for GT:
> **Gentle Touch: Change**
> Fixed Cast Time: 1 second
> Variable Cast Time: 1 second
> Skill re-use Delay: (220 - 20 * Skill Level) seconds
> Global Skill Delay: 1 second
> Duration: 240 seconds
> ATK increase: ATK [{(Caster’s DEX / 4) + (Caster’s STR / 2)} x Skill Level / 5]
> ASPD increase: [(Target’s AGI x Skill Level) / 60] %
> MDEF decrease: MDEF [(200 / Caster’s INT) x Skill Level]
> Max HP decrease: [Skill Level x 4] %
