### ISSUE TITLE
Question About ASPD RENEWAL

### ISSUE THREAD

**Issue by persuez23** [rathena/rathena#3662]
* **rAthena Hash**: 

* **Client Date**:  11/06/2018

* **Server Mode**: Renewal

* **Description of Issue**: I Would like To Ask How To Increase The ASPD in Renewal it seems its to low
![big diff](https://user-images.githubusercontent.com/30340017/48035711-937d0700-e1a8-11e8-9b1b-9cec71d63145.jpg)

  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by secretdataz** [comment]
Here is not where you ask this kind of question.
Use our forums or Discord server.
