### ISSUE TITLE
Thanatos Card BdefRatioClass fix the damage

### ISSUE THREAD

**Issue by kiezha29** [rathena/rathena#3663]
def1+vit_def 100-def

GR / DEVI LOW DAMAGE 50k 60k 500VIT THANATOS CARD
TAO / RAYDRIC HIGH DAMAGE THANATOS CARD 200k 500VIT

PRE RENEWAL 999 LEVEL 500STATS

YOU NEED TO ENCHANT ELEMENT FIRST BEFORE IS WORKING ? IN OTHER SERVER NO ENCHANT ELEMENT GR DEVI HIGH DAMAGE IN THANATOS CARD

ACID DEMO NOT WORKING IN THANATOS CARD WHY ????
SPIRAL PIERCE NOT WORKING IN THANATOS CARD ??? 

WHAT IS THE EXACT DAMAGE FORMULA ?

pm me thank you

**Comment by aleos89** [comment]
Please ask these questions on the forum. Thank you.
