### ISSUE TITLE
Ignition Break [Outdated animation packet]

### ISSUE THREAD

**Issue by syracuase** [rathena/rathena#3664]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/0bcd29931127816a8e2417c8cd8d0b8c02daf6eb
* **Client Date**:  2018
* **Server Mode**:  Renewal

* **Description of Issue**: 
Ignition Break not showing on using new clients. The packet used to trigger the skill animation changed at some point guessing around in 2018 to use the no damage packet instead of a fake damage one on the user.

* **Modifications that may affect results**: None

**Comment by admkakaroto** [comment]
i can confirm this, client 2018-06-21.

**Comment by jaidsa90** [comment]
sir how u managed to fix this? i really not understand
