### ISSUE TITLE
Casting Time When Dex Higher Or Lower

### ISSUE THREAD

**Issue by reunite-ro** [rathena/rathena#367]
You can check my post here : 
https://rathena.org/board/topic/101233-vellum-arc-wand-effect-impossible/#entry281918

im using this week revision of rathena (svn up) from github.

Using renewal cast, what happen : 
1. Low Dex (example 1 dex) ,faster cast
2. High Fex (Example 130 dex) ,slower cast.

Conf
// The rate of time it takes to cast a spell (Note 2, 0 = No casting time)
casting_rate: 100

// Delay time after casting (Note 2)
delay_rate: 100

// Does the delay time depend on the caster's DEX and/or AGI? (Note 1)
// Note: On Official servers, neither Dex nor Agi affect delay time
delay_dependon_dex: no
delay_dependon_agi: no

#define RENEWAL_CAST

i think higher dex could give caster cast right ?

Can anyone confirm this issue ?
![1](https://cloud.githubusercontent.com/assets/11705163/6885149/ffd610fe-d644-11e4-8713-7c079ac70053.jpg)
![2](https://cloud.githubusercontent.com/assets/11705163/6885150/ffe82406-d644-11e4-9ee5-88e296d28ccb.jpg)
![3](https://cloud.githubusercontent.com/assets/11705163/6885151/000cd328-d645-11e4-8ace-b53c0d6c0e0f.jpg)

**Comment by cydh** [comment]
if u compare high vs low dex, shouldn't u try between 1 dex + 1 int and 130 dex + 1 int? /hmm

renewal cast time is
````
// How much (dex*2+int) does variable cast turns zero?
vcast_stat_scale: 530
````

**Comment by reunite-ro** [comment]
ive tried. thats why i open this thread. i know about that formula

**Comment by reunite-ro** [comment]
int 1, dex 1 and int 1 dex 130
ive tried to compare. dex 1 is better in casting compare to dex 130
tried with frost joker, storm gust
