### ISSUE TITLE
Madogear can use more Merchant/Blacksmith/Whitesmith skills

### ISSUE THREAD

**Issue by flamefury** [rathena/rathena#3671]
* **rAthena Hash**: 75d24ad1adaced7e2d4fdb5d5459269a1533e2ec
* **Client Date**: Doesn't matter
* **Server Mode**: Renewal
* **Description of Issue**: 
  * Result: While in a Madogear, Mechanic cannot use a lot of skills.
  * Expected Result: Madogear riding Mechanics can use a lot more skills.
  * How to Reproduce: Be in a Madogear and try to use the listed skills.
  * Official Information: 

kRO update which occurred on live servers earlier today:
http://ro.gnjoy.com/news/notice/View.asp?seq=7034

- 마도기어 상태에서 사용 가능한 스킬이 추가됩니다.
　→ 사용 가능 추가 스킬: 노점개설, 아이템 감정, 체인지 카트, 체인지 카트 2, 카트 레볼루션, 
　　매머나이트, 고성방가, 카트 부스트, 무기수리, 멜트다운, 무기제련, 해머폴, 아드레날린 러쉬, 
　　풀 아드레날린 러쉬, 웨폰 퍼펙션, 맥시마이즈 파워, 오버 트러스트, 오버 트러스트 맥스, 
　　카트 터미네이션, 용암 분출

Translated, line-broken for ease of reading:
Added the following skills to be usable while in Madogear state:
→ Available additional skills:
- Vending
- Item Appraisal
- Change Cart
- Change Cart 2
- Cart Revolution
- Mammonite
- Crazy Uproar
- Cart Boost
- Weapon Repair
- Meltdown
- Weapon Refine
- Hammerfall
- Adrenaline Rush
- Full Adrenaline Rush
- Weapon Perfection
- Maximize Power
- Overthrust
- Overthrust Maximum
- Cart Termination
- Lava Flow

* **Modifications that may affect results**: None

**Comment by aleos89** [comment]
Fixed in fd91ab6.
