### ISSUE TITLE
Modo PK

### ISSUE THREAD

**Issue by SocietyRo** [rathena/rathena#3678]
Olá
Estou tendo dificuldade em restringir itens em um mapa. 
estou usando noequipe.txt para retirar o uso de itens que dão cura dentro do pvp/  PVP pvp_n_1-5
porem quando eu ativo o PK no servidor pelo misc.conf
todo o servidor é afetado a não usar os itens que eu proibi em mapas normais exemplo: campos e cavernas

Já tentei retirar o PK e ativar os mapas que quero manualmente pelo pvp.txt mas o mapa não fica PVP. 
o que fazer?

**Comment by Lemongrass3110** [comment]
Only English.

**Comment by SocietyRo** [comment]
a
little difficulty in restricting items on a map.
I am using noequipment.txt to remove the use of items that do healing within pvp / PVP pvp_n_1-5
however when I activate the PK on the server by misc.conf
the entire server is affected by not using the items I banned in the normal map example: fields and caves

I have already tried to remove the PK and activate the maps that are manually by pvp.txt but the map is not PVP.
what to do?
