### ISSUE TITLE
Problemas de itens no PK

### ISSUE THREAD

**Issue by SocietyRo** [rathena/rathena#3679]
a
little difficulty in restricting items on a map.
I am using noequipment.txt to remove the use of items that do healing within pvp / PVP pvp_n_1-5
however when I activate the PK on the server by misc.conf
the entire server is affected by not using the items I banned in the normal map example: fields and caves

I have already tried to remove the PK and activate the maps that are manually by pvp.txt but the map is not PVP.
what to do?

**Comment by aleos89** [comment]
This is because PK mode sets MF_PVP on all of the maps. You should create a new restricted zone and block the items you want on the specific maps you want.

**Comment by SocietyRo** [comment]
I already tried to create a restricted area and it did not work. Can you explain to me in detail whether I'm doing it the right way?

Because I tried to put pvp_n_1-5 as a restricted area and even then it continued to affect use in other maps.

**Comment by aleos89** [comment]
Based on the current master, you'll have to create a new zone (8192) and assign what skills/items you want disabled on it. Then add it to the restricted mapflag as zone 9. If you have more questions for support, please use the forum or Discord.
