### ISSUE TITLE
cashshop

### ISSUE THREAD

**Issue by julia40124009** [rathena/rathena#368]
link 
https://rathena.org/board/topic/101276-cashshop-warnimg/
I think it not normal

use
-%TAB%cashshop%TAB%<NPC Name>%TAB%<sprite id>,<itemid>:<price>{,<itemid>:<price>...}
same situation
 I missed the update?

version 
https://github.com/rathena/rathena/commit/3c920759fa90332626297639cb9d0138ae77cdaa

20131223

**Comment by cydh** [comment]
this is should be confirmed. silly me, I was following certain someone's diff without check it by 120% xD
https://github.com/rathena/rathena/pull/364/files#diff-99781bd55b5e6f8ddb73b35bbf423dbeL2476
