### ISSUE TITLE
[RE] New NPC vendors

### ISSUE THREAD

**Issue by zackdreaver** [rathena/rathena#3681]
* **rAthena Hash**: 78cda50e3b5cfb3d053c7d08181345418e5a83a1
* **Client Date**: N/A
* **Server Mode**: Renewal
* **Description of Issue**: 
  * Result: Missing 2 kinds of new NPC vendor **초보자용 자판기** (Vending Machine for Novice) and **상급 포션 상인** (Advanced Potion Dealer)
  * Expected Result: These NPCs should present
  * How to Reproduce: Check live rA server and compare with kRO navigation (or actual kRO server would be better if anyone would help with replay file)
  * Official Information: kRO navigation and...

**상급 포션 상인** (Advanced Potion Dealer), spriteID 558
(No idea what it sells)
http://ro.gnjoy.com/news/notice/View.asp?BBSMode=10001&seq=7015&curpage=1
Location based on navi file:
alberta_in,176, 97
aldeba_in,99, 56
geffen_in,78, 169
izlude_in,59, 113
morocc,149, 245
morocc,170, 84
payon,157, 96
payon_in01,12, 53
payon_in02,85, 38
prt_in,129, 68

**초보자용 자판기** (Vending Machine for Novice), spriteID 564
I can't find official renewal link, but I got one that came from zeRO
http://roz.gnjoy.com/community/tip/View.asp?seq=252&curpage=10
Location based on navi file:
alberta_in,60,52
geffen_in,158,107
izlude_in,69,177
moc_para01,17,37
moc_prydb1,38,124
payon_in01,59,20
payon_in02,71,75
prt_church,187,27
que_ng,28,73
que_ng,168,39

* **Modifications that may affect results**: N/A

**Comment by Balferian** [comment]
Advanced Potion Dealer:
![screen 009](https://user-images.githubusercontent.com/16213511/48365953-74590a80-e6bd-11e8-8e00-8578fd0bf7c5.jpg)

**Comment by zackdreaver** [comment]
11621: Red Syrup
Restores about 325 HP
Weight: 7
Requires Level: 60
Cooldown: 1 second

11622: Yellow Syrup
Restores about 900 HP
Weight: 10
Requires Level: 60
Cooldown: 1 second

11623: White Syrup
Restores about 1800 HP
Weight: 14
Requires Level: 60
Cooldown: 1 second

11624: Blue Syrup
Restores about 180 SP
Weight: 10
Requires Level: 60
Cooldown time: 10 seconds

**Comment by Balferian** [comment]
Vending Machine for Novice: [Novice Vending Machine.zip](https://github.com/rathena/rathena/files/2573236/Novice.Vending.Machine.zip)
Before we can use Novice Vendimg Machine we need to talk with Instructors.
I will record dialogs of another instructors later.
![image](https://user-images.githubusercontent.com/16213511/48369086-960abf80-e6c6-11e8-9c17-3077b56c4520.png)
Swordsman instructor: [Swordsman Instructor.zip]
(https://github.com/rathena/rathena/files/2573253/Swordsman.Instructor.zip)

**Comment by Lemongrass3110** [comment]
Advanced potion dealer sample:
`morocc,170,84,1	shop	상급 포션 상인	558,11621:800,11622:1200,11623:1500,11624:7000`

Would need to gather the directions and locations for all of them still though.

The novice machine is a full script with quest it seems.

**Comment by Balferian** [comment]
> Advanced potion dealer sample:
> `morocc,170,84,1	shop	상급 포션 상인	558,11621:800,11622:1200,11623:1500,11624:7000`
> 
> Would need to gather the directions and locations for all of them still though.
> 
> The novice machine is a full script with quest it seems.

Advanced potion dealers:
`alberta_in,176,97,**5**	shop	상급 포션 상인#alb	558,11621:800,11622:1200,11623:1500,11624:7000`
`aldeba_in,99,56,**5**	shop	상급 포션 상인#alde	558,11621:800,11622:1200,11623:1500,11624:7000`
`geffen_in,78,169,**3**	shop	상급 포션 상인#gef	**68**,11621:800,11622:1200,11623:1500,11624:7000`
`izlude_in,59,113,**5**	shop	상급 포션 상인#iz	558,11621:800,11622:1200,11623:1500,11624:7000`
`morocc,149,245,**7**	shop	상급 포션 상인#moc1	558,11621:800,11622:1200,11623:1500,11624:7000`
`morocc,170,84,**1**	shop	상급 포션 상인#moc2	558,11621:800,11622:1200,11623:1500,11624:7000`
`payon,157,96,**3**	shop	상급 포션 상인#pay1	558,11621:800,11622:1200,11623:1500,11624:7000`
`payon_in01,12,53,**5**	shop	상급 포션 상인#pay2	558,11621:800,11622:1200,11623:1500,11624:7000`
`payon_in02,85,38,**3**	shop	상급 포션 상인#pay3	558,11621:800,11622:1200,11623:1500,11624:7000`
`prt_in,129,68,**3**	shop	상급 포션 상인#prt	558,11621:800,11622:1200,11623:1500,11624:7000`

And one missed shop with hats:
`prt_in,117,79,5	shop	장난감상인#prt	715,2239:-1,2201:-1,2243:-1,2212:-1,2242:-1,2241:-1`
![screen 040](https://user-images.githubusercontent.com/16213511/52035821-6ee0c300-253c-11e9-92bf-04db32a86c48.jpg)

**Comment by aleos89** [comment]
Added the Advanced Potion Dealers in 998a99f.
