### ISSUE TITLE
Map server crashes when warping to invalid/missing map

### ISSUE THREAD

**Issue by lelouch22** [rathena/rathena#3687]
* **rAthena Hash**: 78cda50e3b5cfb3d053c7d08181345418e5a83a1

* **Client Date**: 2018-06-20eRagexeRE

* **Server Mode**: Pre-Renewal

* **Description of Issue**: 
  * Result: After warping to a invalid/missing map the map server crashes for example `@warp lasa_sea` then the map server crashes.
`[Warning]: map_getmapflag: Invalid map ID -1.`
`[Error]: Server received crash signal! Attempting to save all online characters!`
  * Expected Result: The server will just say to you "Map not found".
  * How to Reproduce: 
on **conf/maps_athena.conf** add
`map: TestMap`
on **db/import/map_index.txt** add
`TestMap`
save the changes then start your server and type `@warp TestMap` ingame.

**Comment by vykimo** [comment]
Not confirmed, 2018-06-20, latest rAthena.

Btw, this message : `[Warning]: map_getmapflag: Invalid map ID -1.`
is related to script cmd : getmapflag and atcommand : mapflag.
It can't appear with @warp without custom modifications.

**Comment by lelouch22** [comment]
The first time i detected it is on our live server so i tryed testing a clean copy of rA via git clone on my pc but the results are the same.

**Comment by RadianFord** [comment]
I can confirm this one.
