### ISSUE TITLE
[RE] Gunslinger job change reward

### ISSUE THREAD

**Issue by zackdreaver** [rathena/rathena#3690]
* **rAthena Hash**: 78cda50e3b5cfb3d053c7d08181345418e5a83a1
* **Client Date**: N/A
* **Server Mode**: Renewal
* **Description of Issue**: 
  * Result: Missing renewal reward items from changing Novice to Gunslinger, preventing gunslinger changing Novice Revolver into other guns by talking to Sharp Snake's Fang in academy
  * Expected Result: Renewal reward items need to be updated to follow official
  * How to Reproduce: Check script
  * Official Information: https://irowiki.org/wiki/First_Expanded_Job_Change_Guides#Gunslinger

I don't have Gunslinger in iRO to test, but the reward should be same as wiki.
Reward items: 1 Novice Rifle [3], 2 Cartridge and 1 Silver Cartridge
* **Modifications that may affect results**: N/A

**Comment by Balferian** [comment]
Checked on kRo server.
**Changed req.items for Wise Bull Horn:**
	_[6021] = {
		Title = "Wise Bull Horn's voucher",
		Description = {
			"I can make a voucher that will demonstrate your desire to become a warrior of the earth for you to present to Gunslinger drillmasters."
		},
		Summary = "3 Zargons, 10 Shells, 3 Fluffs, 1 Trunk, 3 Rainbow Shells, 3 Green Herbs"
	},_
=>
	[6021] = {
		Title = "황소 뿔이 말하는 징표",
		Description = { "자네의 바람을 계속 이어가려면 내게 징표의 재료를 가져와야 할 것일세." },
		Summary = "버섯포자3개, 초록허브 3개" 
	},
**Change (3 Zargons, 10 Shells, 3 Fluffs, 1 Trunk, 3 Rainbow Shells, 3 Green Herbs)  to (3 Mushroom Spore ID - 921 & 3 Green Herb ID - 511)**
**Reward items:** 1 Novice Rifle [3] (13180), 2 Cartridge (12149) and 1 Silver Cartridge (22738) - **true**

Replay from kRo: [Gunslinger Quest.zip](https://github.com/rathena/rathena/files/2580426/Gunslinger.Quest.zip)

**Comment by Akkarinage** [comment]
Has anyone tested this on kRO recently? The files I have for the Gunslinger Quest provide a `Six_Shooter` **or** a `Branch` when talking to Master Miller and completing quest 6024 and gives no other items.. which I guess means it's a very early version of the script.
