### ISSUE TITLE
[RE] New coordinate for Taekwon job change NPC

### ISSUE THREAD

**Issue by zackdreaver** [rathena/rathena#3691]
* **rAthena Hash**: 78cda50e3b5cfb3d053c7d08181345418e5a83a1

* **Client Date**: N/A

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: NPC for Taekwon job change, **Phoenix**, has prerenewal coordinate in Renewal
  * Expected Result: NPC for Taekwon job change, **Phoenix**, has new coordinate in Renewal
  * How to Reproduce: check script
  * Official Information: kRO navigation file

	{ "payon_in01", 23002, 101, 753, "Phoenix", "", 62, 10 },
  

* **Modifications that may affect results**: N/A

**Comment by zackdreaver** [comment]
I have issue with replay from Sakray server, all NPCs and other players cannot be seen in replay.
No issue with main server.

**Comment by zackdreaver** [comment]
Btw, who is the Girl NPC in the first screenshot?
I don't recall any other NPC beside Phoenix.

**Comment by Balferian** [comment]
> Btw, who is the Girl NPC in the first screenshot?
> I don't recall any other NPC beside Phoenix.
Seem like it is job instructor: [TaekwonInstructor.zip](https://github.com/rathena/rathena/files/2580519/TaekwonInstructor.zip)

**Comment by zackdreaver** [comment]
Cool

**Comment by Lemongrass3110** [comment]
Confirmed this on kRO.
