### ISSUE TITLE
Flying Kick can't be copied

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#3707]
* **rAthena Hash**: 
d7d012c

* **Client Date**: 
2018-02-21bRagexeRE

* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result: Flying Kick **TK_JUMPKICK** can't be copied using the Reproduce Skill.
  * Expected Result: Can be copied because it is included in the skill_copyable_db.txt
  * How to Reproduce: Try to copy the skill using Reproduce Skill

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Tested on 348acd1.

![image](https://user-images.githubusercontent.com/3521753/49042817-2a7d2380-f197-11e8-8c6b-5737679020a8.png)

**Comment by Everade** [comment]
Reproduce is a Shadow Chaser skill, and you are using Stalker Class. 

To save Flying Kick on Reproduce:

1. Have any skill saved on Plagiarism (Except Flying Kick).
2. Have any skill saved on Reproduce.
3. Make sure you have Preserve active.
4. Activate Reproduce.
5. Get hit by Flying Kick.
6. Deactivate Reproduce.

**Comment by aleos89** [comment]
Yeah, I realized after talking with the staff that you meant the Shadow Chaser's Reproduce skill. I went ahead and followed your steps:
![image](https://user-images.githubusercontent.com/3521753/49116649-4acae200-f26c-11e8-8254-9bc816b2bddb.png)
Cold Bolt is from Plagiarism and Flying Kick is from Reproduce.
