### ISSUE TITLE
Level 1 Call Tera

### ISSUE THREAD

**Issue by julia40124009** [rathena/rathena#371]
Solid Skin no add DEF (def*2)
http://irowiki.org/wiki/Call_Tera

version 
https://github.com/rathena/rathena/commit/3028c871e306ac2c137585f1afd84e2b0518b9a1

**Comment by cydh** [comment]
need info for that def bonus
>Solid Skin
>* Boost Max HP by 2,000.
>* __Boost DEF.__

**Comment by julia40124009** [comment]
I only Chinese information website
https://rs.fharr.com/class/sox.php

**Comment by cydh** [comment]
err only if those description can be selected xD

**Comment by aleos89** [comment]
This skill already grants a 33% DEF bonus. Unless you find otherwise, that's what it is right now.

**Comment by Barigas** [comment]
The info stated here http://irowiki.org/wiki/Call_Tera is correct. It should add +25 hard def. I play sorcerer on ruRO and can confirm this. Though, the defence bonus is actually useless.

**Comment by aleos89** [comment]
@Barigas: I think you're confusing yourself. The ATK and DEF bonus you are referring to goes to the Tera. @julia40124009 is referring to Solid Skin's DEF bonus, which is what I stated above, is given to the player.

@cydh: Translated for you. :) We need to test on AEGIS to confirm if it is DEF*2.
```
Summons to elements of the wizard (Call Tera)
Type: Active (maximum skill level 3)
Front: manipulation Elf Lv1, earth Cemetery Lv3
Description: Summons to Elf Tyra
Fixed chant two seconds
Changes chant (1x skill level) seconds
After the skills to use a separate delay 60 seconds
[Lv1]: 600 seconds duration, Summoner MaxHP + 5%, every 10 seconds consumes SP 5, and consume three ore Hope
Increase magic damage [petrochemical surgery] increased risk, [earthquake surgery], [crack surgery] - rocky areas (secondary)
Skin cure (defense) - Summoner MaxHP + 200, 2-fold increase in defense
Stone Hammer (attack) - magic damage caused to the property for a specified object, the probability of additional [stun] state
[Lv2]: 900 seconds duration, Summoner MaxHP + 10%, every 10 seconds consumes 8 SP, consumes 6 Spirit Ore ground
Blasted Lands (auxiliary) - [cloud kill], [toxic Slam] increase [earth Cemetery] magic damage [supernatural wave] additionally property
Rock shield (defense) - reduced from [land belongs to (physical and magic attacks)] 100% damage taken
Is an additional 100% damage when [fire is (physical and magic attacks)] Attack
Gravel (Attack) - magic damage caused to the property for a specified object, and reduces target defense
[Lv3]: continued 1200 seconds, Summoner MaxHP + 15%, every 10 seconds consumes 11 SP, consume an original stone of Hope
Earth shattering (Auxiliary) - Summoner physical attack, the chances of the enemy cast [earthquake surgery]
Cast [to the elements in the field], [to property attached], the (50%) chance of magic ore Needless Mao
Avatar (defense) - Summoner around 3x3 range settings enchantment, will not fall into [petrochemical], [bleeding] state
The duration of the call by MaxHP + 20%, defense +100
Rock Storm (attack) - causing damage to the property of the specified object, the probability of additional [stun] state Sp: 100 150 200
```

**Comment by cydh** [comment]
then it say increase 2x the def. gonna test on Aegis later

**Comment by cydh** [comment]
oh, just because we don't listed the skill effect duration for Solid Skin in (EL_SOLID_SKIN) in `skill_cast_db.txt`

**Comment by cydh** [comment]
the rest is just the formula, I found the def is kinda ~~A7X~~ 2x
damage from 162 dropped to 62. I leave this for @aleos89
