### ISSUE TITLE
Implement the MAC in rAthena

### ISSUE THREAD

**Issue by Haikenz** [rathena/rathena#3711]
the brAthena emulator already has this active function in the emulator, it would be great if they also added in rAthena

Mac Adress - https://github.com/brAthena/brAthena20180924/commit/51dd5f2cc2fa9967cc65e681d71038ef34e6cd6c
Mac Mapflag (mapflag block_dual_mac ) - https://github.com/brAthena/brAthena20180924/commit/8da8f42761ce5ee2155052213fe6302bfd0890a7
Ban and Unban Mac - https://github.com/brAthena/brAthena20180924/commit/6a11f7ee21cc7ec13c45ad9cc783f54a7d0183d5

**Comment by pigati23** [comment]
very good suggestion!

**Comment by Lemongrass3110** [comment]
Nothing to add to what @anacondaqq said. Learn how networking works
