### ISSUE TITLE
Rebalancing of 1st/2nd/Transcendent class skills

### ISSUE THREAD

**Issue by flamefury** [rathena/rathena#3715]
* **rAthena Hash**: eafb1cb7f9c0f7d696c2ab8ec6ab098ee55ad0be
* **Client Date**: Doesn't matter
* **Server Mode**: Renewal
* **Description of Issue**: 
Gravity performed a massive rebalance of several of 1st, 2nd and Transcendent class skills that hit live today after being on Sakray for about a month. Many (but not all) changes match the skill behaviours on RO Zero.

I am not a fluent Korean reader, so some translations may be off. I'd advise having someone double-check my work in case I misread anything.

1. First Job
    1. Swordsman
        1. Magnum Break
            * After skill delay reduced from 2 seconds to 0.5 seconds, and 2 second cool down added. 
    2. Merchant
        1. Crazy Uproar
            * 0.3s fixed cast time and 1s variable cast time added.
            * Changed to increase STR by 4 and ATK by 30 for you and party members around you.
            * 30s skill cool down added.
    3. Mage
        1. Fire Bolt / Cold Bolt / Lightning Bolt
            * Fixed cast time moves from 0.88s to 1.2s at level 10
            * Variable cast time moves from 3.52s to 3.2s at level 10
            * Greatly reduce the after skill delay.
        2. Thunderstorm
            * Fixed cast time moves from 1.6s to 1.5s at level 10.
            * Variable cast time moves from 6.4s to 4.5s at level 10.
        3. Fire Ball
            * Level 1-5 fixed and variable cast time will change to match Lv6-10's values of 0.2s/0.8s.
            * After skill delay decreases to 0.7 seconds regardless of skill level.
        4. Soul Strike
            * After skill delay unified to 1.4s regardless of level (formerly would go from 2.5s to 1.4s across the 10 levels).
        5. Frost Diver
            * After skill delay reduced from 1.5s to 0.5s.
    4. Acolyte
        1. Blessing
            * Added additional effect of increasing HIT, and Arch Bishop's Clementia skill will also increase the amount granted based on Job Level.
        2. Increase Agility
            * Added ASPD increase effect based on skill level.
        3. Angelus
            * Added MHP increase effect based on skill level.
        4. Holy Light
            * Fixed and variable cast time are reduced by 50%.

2. Second Job
    1. Knight
        1. Bowling Bash
            * Hits twice against a target and a 5x5 area around them as well as knocking targets back.
            * When used with a Two-handed Sword equipped, deals damage up to 4 times, depending on the number of targets in the 5x5 area.
            * Cast delay reduced, 1s skill cool down added.
        2. Brandish Spear
            * Changed to deal ranged physical damage to targets within the area of effect.
            * Damage formula changed to increase based on the caster's STR.
            * Cast delay reduced and 0.5s after skill delay added.
            * 1s skill cool down added.
            * SP consumption increased to 24.
        3. Two-Handed Quicken
            * ASPD +10% effect added.
            * Critical rate and HIT increase effects added based on skill level, up to CRI +12 and HIT +20 at Lv10.
        4. Charge Attack
            * Fixed and variable cast time of 0.25s is removed.
            * 0.5s skill cool down added.
    2. Blacksmith
        1. Adrenaline Rush
            * ASPD +10% effect added.
            * HIT increases based on skill level, up to HIT +20 at Lv5
        2. Over Thrust
            * Weapon breaking chance removed.
            * Damage increase to party members is increased.
    3. Assassin
        1. Sonic Blow
            * Forced animation delay is removed.
            * Damage increases, also for targets below 50% of their max HP, damage is increased by 50%.
            * After skill delay removed, and 1s skill cool down added.
        2. Venom Splasher
            * Skill cool down is reduced from 12s to 2s at Lv10.
            * Red Gemstone consumption removed, damage slightly increased.
    4. Wizard
        1. Lord of Vermillion
            * Fixed cast time changed from 1.68s to 1.5s at Lv10.
            * Variable cast time changed from 6.72s to 4.5s at Lv10.
            * After skill delay reduced from 5 seconds to 1 second, and 5s skill cool down added.
            * Now deals damage as 1 attack divided into 20 hits, instead of the old method of 4 attacks each divided into 10 hits.
            * Damage is slightly increased.
        2. Meteor Storm
            * Fixed cast time changed from 2.4s to 1.5s at Lv10.
            * Variable cast time changed from 9.6s to 6.3s at Lv10.
            * After skill delay reduced from 7 seconds to 1 second, and 7s skill cool down added.
        3. Storm Gust
            * Fixed cast time changed from 2.4s to 1.5s at Lv10.
            * Variable cast time changed from 9.6s to 6.3s at Lv10.
            * After skill delay reduced from 5 seconds to 1 second, and 6s skill cool down added.
        4. Jupitel Thunder
            * Fixed cast time changed from 1.12s to 0.5s at Lv10.
            * Variable cast time changed from 4.48s to 3.8s at Lv10.
        5. Earth Spike
            * Fixed cast time changed from 0.56s to 1.2s at Lv5.
            * Variable cast time changed from 2.24s to 3.2s at Lv5.
            * After skill delay changed from 1.8s to 1.4s at Lv5.
            * Damage per hit is changed from 100% MATK to 200% MATK.
        6. Heaven's Drive
            * Fixed cast time changed from 0.64s to 0.8s at Lv5.
            * Variable cast time changed from 3.2s to 1.9s at Lv5.
            * After skill delay changed from 1s to 0.5s at Lv5.
    5. Priest
        1. Magnus Exorcismus
            * Fixed cast time changed from 3s to 1s.
            * Variable cast time changed from 12s to 4s.
            * After skill delay changed from 1.5s to 1s.
            * Added skill cool down of 6s.
            * Changed to deal damage to all enemies.  Demon, undead race and dark, undead property take additional damage.
        2. Mace Training
            * Add a critical rate bonus, CRI +10 at Lv10.
        3. Suffragium
            * Reduce the variable cast time of yourself and all party members around you for the full duration.
            * 0.5s fixed cast time added, 1s variable cast time added.
            * After skill delay reduced from 2s to 1s, added 30s skill cool down.
        4. Impositio Manus
            * Increase ATK and MATK of yourself and nearby party members.
            * 0.5s fixed cast time added, 1s variable cast time added.
            * After skill delay reduced from 3s to 1s, added 30s skill cool down.
    6. Hunter
        1. Landmine
            * Fixed cast time reduced from 1s to 0.3s
            * Added variable cast time of 0.5s.
        2. Claymore Trap
            * Fixed cast time reduced from 1s to 0.3s
            * Added variable cast time of 0.5s.
        3. Blast Mine
            * Fixed cast time reduced from 1s to 0.3s
            * Added variable cast time of 0.5s.
        4. Blitz Beat
            * Damage formula changed to use the caster's AGI and DEX.
            * When auto Blitz Beat is triggered, damage splitting effect is removed.
    7. Crusader
        1. Grand Cross
            * Fixed cast time reduced from 1.5s to 0.5s.
            * Variable cast time reduced from 1.5s to 1s.
            * After skill delay reduced from 1.5s to 0.5s.
            * Added 1s skill cool down.
            * Recoil damage removed.
        2. Shield Boomerang
            * Damage formula changed.
        3. Spear Quicken
            * Added a +10% ASPD effect.
    8. Alchemist
        1. Demonstration
            * Chance of weapon break increased.
            * Damage type changed from special physical to melee physical. 
            * Damage formula changed, and damage is further increased based on the level of Learning Potion.
        2. Acid Terror
            * Chance of armour break increased.
            * Damage type changed from special ranged physical to ranged physical.
            * Damage formula changed, and damage is further increased based on the level of Learning Potion.
    9. Rogue
        1. Raid
            * SP consumption reduced to 15.
            * Damage increased, and targets hit by Raid will receive 30% more damage for 10 seconds (15% for bosses)
        2. Back Stab
            * Now teleports the user behind the target, and no longer requires hiding state.
            * When casted with a Dagger equipped, damage is doubled.
            * Grant an accuracy correction effect based on skill level.
            * Added 0.5s skill cool down.
        3. Plagiarism
            * Depending on skill level, ASPD increase effect added.
    10. Sage
        1. Deluge / Violent Gale / Volcano
            * Changed catalyst consumption from Yellow Gemstone to Blue Gemstone.
            * Volcano damage increase effect changed from additive effect to an ATK/MATK increase.
        2. Frost Weapon / Lightning Loader / Seismic Weapon / Flame Launcher
            * Fixed cast time reduced from 3s to 1s.
            * Added 1s of variable cast time.
            * Changed catalyst consumption to Indigo Point / Yellow Wish Point / Lime Green Point / Scarlet Point.
            * Added a magic damage increase effect for each specific element.
            * Skill failure chance is removed, and the duration of Lv1~4 is changed.
        3. Autospell
            * The activated skill levels are now half of the Autospell skill level and no longer activated with random level values. (However, if the skill level known of the selected spell is lower, it will be activated only at the level known)
            * Probability of activation is changed.
            * Depending on skill level, the types of magic that can be used is changed as shown:
                * Lv1~3: Fire Bolt / Cold Bolt / Lightning Bolt
                * Lv4~6: Soul Strike / Fire Ball
                * Lv7~9: Earth Spike / Frost Diver
                * Lv10: Thunderstorm / Heaven's Drive
    11. Monk
        1. Knuckle size mods are changed to small 100% / medium 100% / large 75% (old: 100 / 75 / 50)
        2. Raging Trifecta Blow
            * Activation chance fixed at 30% regardless of skill level.
        3. Raging Quadruple Blow
            * When used with Knuckle weapons, damage is increased and SP consumed is reduced.
        4. Raging Thrust
            * Damage formula changed, and damage is increased based on the caster's STR.
            * Reduced SP consumption.
        5. Guillotine Fist
            * When used within a combo, this skill can be used if there is more than one Spirit Sphere left.
            * If there are 6 or more Spirit Spheres active at the time of casting, damage is increased by about 100%.
            * After use, the non-recoverable SP period is reduced from 10 seconds to 3 seconds.
        6. Root
            * Effect duration changed to 10s.
            * Can be used against boss monsters, and when used against boss monsters the duration is changed to 2 seconds.
        7. Occult Impaction
            * Damage slightly increased and deals additional damage to an enemy that is caught by Root.
        8. Throw Spirit Sphere
            * Regardless of skill level, it will consume only 1 sphere.
            * Damage increased, and deals additional damage to an enemy that is caught by Root.
            * Fixed cast time and variable cast time changed to 0.5s each, regardless of skill level.
        9. Spirit Sphere Absorption
            * Fixed cast time reduced from 1s to 0.5s.
            * Variable cast time removed.
    12. Bard&Dancer
        1. Songs and dance buffs are no longer a 9x9 AoE field, but instead a screenwide party member buff. In addition, for Ensemble skill casts, the movement speed, ASPD reductions and skill disabling effect is changed to being unable to move for 10 seconds. The Ensemble drawback can be removed by using the new skill Skilled Special Singer which replaces Longing for Freedom.
        2. Melody Strike / Slinging Arrow
            * Variable cast time reduced from 1.5s to 0.5s.
            * Added 0.3s after skill delay.
            * Damage increased.
        3. Instrument Training
            * Added ASPD and MSP % increase effects.
        4. Dance Practice
            * Added critical rate and MSP % increase effects.
        5. Frost Joke / Scream
            * Added 4s skill cool down.
            * After skill delay reduced from 4s to 0.3s.
        6. Adaptation to Circumstances
            * When using a song, dance or ensemble skill, the SP consumed is reduced.
            * Added 0.3s after skill delay and 300s skill cool down.
        7. Encore
            * Added 0.3s after skill delay and 10s skill cool down.
        8. Dissonance
            * Deal Neutral property magic damage to enemies in a 9x9 area around you.
            * Damage increased by job level.
            * This skill can only be used in PVP areas.
        9. A Poem of Bragi
            * Affects yourself and party members in a 31x31 area around you
            * Reduce variable cast time and after skill delay.
        10. Assassin Cross of Sunset
            * Affects yourself and party members in a 31x31 area around you
            * Increase ASPD.
        11. The Apple of Idun
            * Affects yourself and party members in a 31x31 area around you
            * Increase MHP% and healing recovery.
        12. A Whistle
            * Affects yourself and party members in a 31x31 area around you
            * Increases FLEE and perfect dodge.
        13. Ugly Dance
            * Reduce the SP of targets in a 9x9 area around you at a certain chance.
            * SP reduction affected by the caster's DEX and AGI.
            * This skill can only be used in PVP areas.
        14. Please Don't Forget Me
            * Decrease the attack speed and movement speed of targets in a 9x9 area around you.
            * Speed reduction affected by teh caster's DEX and AGI.
            * This skill can only be used in PVP areas.
        15. Service For You
            * Affects yourself and party members in a 31x31 area around you
            * Increases MSP% and SP consumption is reduced.
        16. Fortune's Kiss
            * Affects yourself and party members in a 31x31 area around you
            * Increases critical rate and critical damage.
        17. Humming
            * Give yourself and party members within 31x31 of you a increase to HIT rate.
        18. Mr. Kim A Rich Man
            * Affects yourself and party members in a 31x31 area around you
            * Increases the amount of experience gained during monster hunting.
        19. The Ring of Nibelungen
            * Give yourself and party members in a 31x31 area around you random beneficial effects.
        20. Invulnerable Siegfried
            * Affects yourself and party members in a 31x31 area around you
            * Grant Earth / Water / Fire / Wind property resistance
            * Grant increased resistance to Blind / Petrification / Frozen / Stun / Curse / Sleep / Slience status conditions.
        21. Into The Abyss
            * Grant yourself and party members in a 31x31 area around you the ability to cast spells without consuming gemstones.
        22. Eternal Chaos
            * Set DEF to 0 for targets in a 9x9 area around the caster.
            * This skill can only be used in PVP areas.
        23. Loki's Wail
            * Make it impossible to use skills for targets in a 9x9 area around you.
            * This skill can only be used in PVP areas.
        24. Lullaby
            * Make enemies fall asleep in a 9x9 area around you.
        25. Drum on the Battlefield
            * Grant yourself and party members in a 31x31 area around you ATK and DEF increases.

3. Transcendent
    1. Lord Knight
        1. Spiral Pierce
            * Fixed cast time reduced from 0.5s to 0.3s at Lv5.
            * Variable cast time reduced from 0.5s to 0.25s at Lv5.
            * After skill delay reduced from 5s to 2s at Lv5.
            * Damage values according to target size is increased.
            * Damage increased from 350% ATK to 400% ATK at Lv5.
            * Damage is further increased based on the caster's base level.
        2. Aura Blade
            * Damage bonus is increased based on the caster's base level.
        3. Concentration
            * Will retain the buff even if equipment is removed or changed.
            * Damage bonus reduced from 25% ATK to 15% ATK at Lv5.
            * Armor reduction penalty reduced from 25% drop to 15% at Lv5.
            * Duration increased from 45s to 60s at Lv5.
    2. Whitesmith
        1. Overthrust Max
            * Weapon break chance removed.
    3. Assassin Cross
        1. Meteor Assault
            * After skill delay of 0.5s is removed, and added skill cool down of 0.5s.
            * Damage formula changed, and depending on the caster's STR and base level, damage is increased further.
        2. Enchant Deadly Poison
            * When active, the 50% damage penalty to Cross Impact, Counter Slash, Soul Destroyer, Sonic Blow is removed.
            * Weapon damage bonus is reduced from 400% to 300%.
            * After skill delay of 2s is removed, and skill cool down of 2s is added.
            * The duration is increased from 60s to 120s at Lv5.
    4. High Wizard
        1. Gravitation Field
            * Fixed cast time is reduced from 5s to 1s and added variable cast time of 5s.
            * After skill delay is reduced from 9s to 1s.
            * Added skill cool down of 5s, and the SP consumed between Lv1~4 will be changed.
            * Changed from fixed damage to Neutral property magic damage, and damage is further increased by the caster's base level.
        2. Napalm Vulcan
            * The damage formula is changed, and damage is further increased by the caster's base level.
            * Damage will no longer be split amongst targets, the after skill delay is reduced from 1s to 0.5s and added a skill cool down of 1s.
    5. High Priest
        1. Basilica
            * Fixed cast time reduced from 9s to 5s at Lv5 and added variable cast time of 3s.
            * After skill delay reduced from 6s to 5s, and added skill cool down of 30s.
            * SP consumed is reduced from 120 to 80 at Lv5.
            * The effect of the skill changed to increase the damage of Holy magic attacks and increasing physical damage against Dark property and Undead race enemies.
        2. Assumptio
            * After skill delay reduced from 1.5s to 0.5s at Lv5.
            * The effect of the skill changed to give an increase to DEF and also increased heal recovery amount.
            * Can now be used alongside Kyrie Eleison.
    6. Sniper
        1. Sharp Shooting
            * After skill delay reduced from 2.5s to 0.5s.
            * Fixed cast time and variable cast time both changed from 1s to 0.5s each.
            * Critical chance increased, damage formula changed, and damage increases depending on the caster's base level.
        2. Falcon Assault
            * Damage formula changed.
    7. Paladin
        1. Shield Chain
            * Range is increased from 4 cells to 11 cells at Lv5.
            * Damage formula changed, and damage increases depending on the caster's base level.
        2. Pressure
            * SP reduction effect on the target is removed.
            * Skill effect changed from fixed damage to Holy property magic damage.
            * Damage increases depending on the caster's base level.
            * Variable cast time reduced from 1.6s to 1s.
            * After skill delay reduced from 4s to 1s at Lv5.
    8. Professor
        1. Memorize
            * Fixed cast time reduced from 5s to 2.5s.
        2. Life Change
            * After skill delay reduced from 1.8s to 0.5s at Lv5.
    9. Champion
        1. Zen
            * Fixed cast time reduced from 2s to 1s.
        2. Raging Palm Strike
            * Damage formula changed, and damage increases depending on the caster's STR and base level.
        3. Glacier Fist
            * Damage formula changed, and damage increases depending on the caster's base level.
        4. Chain Crush Combo
            * Spheres consumed reduced from 2 to 1.
            * Damage formula changed, and damage increases depending on the caster's base level.
    10. Clown&Gypsy
        1. Arrow Vulcan
            * Fixed cast time reduced from 0.76s to 0.5s at Lv10.
            * Variable cast time reduced from 3.04s to 1.5s at Lv10.
            * After skill delay reduced from 2s to 0.5s, and added skill cool down of 1.5s.
            * Damage formula changed, and damage increases depending on the caster's base level.
            * Forced attack animation is removed.
        2. Skilled Special Singer (formerly Longing for Freedom)
            * Immediately remove the movement penalty when you use an Ensemble.
            * Added skill cool down of 60s.

* **Official Information**:
Live release: http://ro.gnjoy.com/news/notice/View.asp?seq=7040
Sakray release: http://ro.gnjoy.com/news/notice/View.asp?seq=7033
Dev notes:
    * Pre-Sakray Release: http://ro.gnjoy.com/news/devnote/View.asp?seq=3908051
    * Initial breakdown: http://ro.gnjoy.com/news/devnote/View.asp?seq=3903893
    * Reasoning: http://ro.gnjoy.com/news/devnote/View.asp?seq=3901749
    * Initial teaser announcement: http://ro.gnjoy.com/news/devnote/View.asp?seq=3898433

Divine-Pride changelogs

Live: https://www.divine-pride.net/forum/index.php?/topic/3555-kro-changelog-november-28-2018/
Sakray: https://www.divine-pride.net/forum/index.php?/topic/3505-kro-changelog-october-31-2018/

I expect they'll create an event poster later. If they make one, I'll add it here.

**Comment by vykimo** [comment]
Question to rA devs 
How will you manage these changes? Will you add a global variable to let the choice for the rAthena user to get old/new skill behaviors? Or will you change all the skill infos as it?

**Comment by aleos89** [comment]
I’m pretty much done with this aside from some data that is missing in the changes. I didn’t do anything with preserving old behavior. We haven’t really done that in the past with skills and it’s simple enough to revert or not apply one commit for people who don’t want this update.

**Comment by vykimo** [comment]
Ok fair choice

**Comment by vykimo** [comment]
Not really @anacondaqq because it will require some extra files in db/ folder (skill_db.txt etc)

**Comment by anacondaqq** [comment]
Agree
