### ISSUE TITLE
[Request] Enable build artifacts from appveyor

### ISSUE THREAD

**Issue by zackdreaver** [rathena/rathena#3722]
* **rAthena Hash**: n/a

* **Client Date**: n/a

* **Server Mode**: n/a

* **Description of Issue**: 
Like the tittle says, is it be possible to enable build artifacts from appveyor?
https://ci.appveyor.com/project/rAthenaAPI/rathena

**Comment by zackdreaver** [comment]
Yes, just the exes.

Well I'm just thinking that with huge size of VS on windows,
by having autobuild will help non-PS owner/developer on using rA.

I'm fine with rA developer's decision if they decline this.

**Comment by Lemongrass3110** [comment]
As I remembered the team does not want this. So I am sorry but I have to decline this suggestion.

But there are guides from @anacondaqq in the forum how to compile on windows with a smaller VS package. Maybe these can help you.
