### ISSUE TITLE
server still recognizes your last login

### ISSUE THREAD

**Issue by rook1es** [rathena/rathena#3724]
Client Date: 2018-06-20
Server Mode: Pre-Renewal
Description of Issue:
server still recognizes your last login

when i try to use my another character and i use again my main character it says server still recognizes your last login in short my account stuck in a few minutes. but it can connect again after 3-5minutes.

**Comment by Akaineko-astasi** [comment]
@rook1es to login with another character, you need it to be on another account. You can't login into the same account with two windows at once. None of the characters of the same account can be online together, including vendors in the autotrade mode.

**Comment by aleos89** [comment]
Can you provide the hash you are using? I just tested with 32c68c7 and was unable to reproduce.
