### ISSUE TITLE
Autotrade error vending_reopen

### ISSUE THREAD

**Issue by Chlas** [rathena/rathena#3726]
Last version Rathena master 03/12

https://github.com/rathena/rathena

* **Client Date**: 2018
* **Server Mode**: Pre-Renewal
When a guys are in autotrade and i restart my server , he can't reopen (screen 1)
![sans titre](https://user-images.githubusercontent.com/44482380/49418769-1089a500-f784-11e8-9b1d-18b21702ec3e.png)
thx for your repply =p

**Comment by Lemongrass3110** [comment]
```
// skill level and cart check
	if( !vending_skill_lvl || !pc_iscarton(sd) ) {
		clif_skill_fail(sd, MC_VENDING, USESKILL_FAIL_LEVEL, 0);
		return 2;
	}
```

Player does not have a cart or does not have the skill to open vending.
