### ISSUE TITLE
Wrong Item Restriction ID 31140 and 31141

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#3727]
Official Item restriction for Guild Storage according to kRO client file:
```
// ItemID | Drop | Trade | Storage | Cart | SelltoNPC | Mail | Auction | Guild Storage
31140	1	1	0	1	0	1	1	1	//C검은색카우보이모자
31141	1	1	0	1	0	1	1	1	//C선인장꽃코르사쥬
```

Should not be able to be stored into guild storage.

<<_Divine Pride information is wrong!_>>

Account bound items should never be possible to be stored to the guild storage.
It renders all other restrictions basically useless.

**Comment by Lemongrass3110** [comment]
Guild storage info on divine pride is taken from the lua file. It has been confirmed that the guild storage flag is not being set correctly by gravity.

**Comment by Everade** [comment]
I'm not aware about a redundant lua file?!
Teach me senpai 😸 

Client side item restrictions are stored here:
`data.grf -> data\itemmoveinfov5.txt`
// ItemID | Drop | Trade | Storage | Cart | SelltoNPC | Mail | Auction | Guild Storage
31140	1	1	0	1	0	1	1	**1**	//C검은색카우보이모자
31141	1	1	0	1	0	1	1	**1**	//C선인장꽃코르사쥬

That's what's officialy being displayed on the item description.
![image](https://user-images.githubusercontent.com/12261601/49552050-2917cd80-f8f2-11e8-875f-aa66b2ab9766.png)

Which displays it as **Guild Storage NO**NONONO.
It's clearly a server-side bug and this is a bug tracker for bugs.


The *keep official bugs* policy is driving me nuts.
Just because some korean db developer fucked up doesn't mean that we have to knowingly repeat his mistake.


But please close it as *working as intended* if this is going nowhere.
I fixed it for me, i won't bother any further if rAthena does not even try to be better than that.

**Comment by Atemo** [comment]
Fixed in https://github.com/rathena/rathena/commit/54b2cf3215e6f2eeeb6ff304be11dd9ee3e13b3f
