### ISSUE TITLE
Map Server Crash (Clone usinng Gravitational Field Skill)

### ISSUE THREAD

**Issue by lordganja** [rathena/rathena#373]
Can someone reproduce this one? Whenever a character clone
casts Gravitational Field skill, it causes map server to crash..

I'm using the latest git..

**Comment by Playtester** [comment]
Sorry my hand slipped.

Due to Gravitational Field's unique nature, it probably only works when cast by players. Clones are like monsters I guess?

**Comment by lordganja** [comment]
Yeah. afaik clones are considered as mobs.

**Comment by raynra** [comment]
In all my years of using RO emulators - I've always had issues with clones cause map server crashes. So much so that I stopped using clones a few years back. The only clones I would recommend using are clones with mode set to move only (which makes them quite useless).

**Comment by lordganja** [comment]
So isn't there any way to fix this? :/

**Comment by cydh** [comment]
> Due to Gravitational Field's unique nature, it probably only works when cast by players.

so it's a feature :d
