### ISSUE TITLE
CN Meteor and Lunatic CB too weak

### ISSUE THREAD

**Issue by teededung** [rathena/rathena#3734]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/9758a38f0772942c7004ea233b47f926337c5913

* **Client Date**: 20170614

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Damage is too weak
  * How to Reproduce: After pulling https://github.com/rathena/rathena/commit/9758a38f0772942c7004ea233b47f926337c5913 the damage of these skills is reduced.

**Comment by aleos89** [comment]
I'm not exactly sure how damage would have reduced. The two skills that were added only check for items in your inventory to give the extra Curse/Stun effect for Catnip Meteor/Lunatic Carrot Beat.

**Comment by teededung** [comment]
Hi @aleos89 
Here is a result of Lunatic Carrot Beat after using the hash: https://github.com/rathena/rathena/commit/eafb1cb7f9c0f7d696c2ab8ec6ab098ee55ad0be
![2018-12-11_10-22-57](https://user-images.githubusercontent.com/9781158/49777614-dac05f80-fd33-11e8-806f-8c2a7db5ecf9.jpg)

Here is another result after using the hash: https://github.com/rathena/rathena/commit/9758a38f0772942c7004ea233b47f926337c5913
![2018-12-11_10-29-24](https://user-images.githubusercontent.com/9781158/49777626-e2800400-fd33-11e8-9503-e9c45f6f4e25.jpg)

Both cases have Carrots (515) in my char inventory.
This result is tested on the clean rAthena.

**Comment by Playtester** [comment]
If I understand it correctly you use the new versions of the skill if you cast it with the required item. However, half of the code is still missing for them, for example no mention of these skills in battle.cpp, so they just deal 100% default damage.
