### ISSUE TITLE
NPC do not allowed me to sell itens for FREE

### ISSUE THREAD

**Issue by AzarthMZintos** [rathena/rathena#3745]
* **rAthena Hash**: 6fb680d5e6f9e87c115446de9d41da99202c1363

* **Client Date**: 2018-06-21a

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: when you put item in the db to be sold by 0 and use npc like to sell like xxxx:-1 the emulator will give a warning "npc_parse_shop: Item N_Fly_Wing_ [23280] is being sold for FREE in file _________________________ " and change automatic the buy price to one like in the npc will be "0 -> 1" so you cant not get for free
  * Expected Result: should be able to stay 0, so the people can buy for this value
  * How to Reproduce: make a item/change a item to be buy for 0 put in na npc like xxxx:-1 will get a warning and would be possible to buy the item for 0
  * Official Information:https://www.divine-pride.net/database/item/23280 even this is not official and i cannot confirm in case is official ou we just want as a custom the price is not possible
  

* **Modifications that may affect results**:

**Comment by secretdataz** [comment]
Intended behavior
