### ISSUE TITLE
Map crash when using Ranger skills

### ISSUE THREAD

**Issue by teededung** [rathena/rathena#3750]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/9f880768a8b860db27b65c7504f783e2ae0044f3

* **Client Date**: 20170614

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Map crash when using Ranger skills
  * Expected Result: No crash
  * How to Reproduce: 
1. Job change to Ranger
2. Use any skill
3. Map Crash

Tested on clean rA

**Comment by Lemongrass3110** [comment]
![2018-12-17_00-41-13](https://user-images.githubusercontent.com/3517879/50060453-77e82180-0194-11e9-83d0-45f90586594c.gif)

Provide better information about your equipment, status, etc.
Best would be a stack trace of your crash.

**Comment by teededung** [comment]
Map-server crashed if I using equip has bonus `bSkillUseSP` or `bAutoSpellWhenHit`

`bSkillUseSP` -> use any skill then crash
`bAutoSpellWhenHit` -> monster hits you

Please check this git hash: https://github.com/rathena/rathena/commit/c71ef92fb0aa50119484d5576853eb0c79baa397

**Comment by Lemongrass3110** [comment]
This issue is coming from Visual Studio. Especially if you run rAthena in Debug mode with SDK for 2015 or earlier. 2017 does not seem to have this problem, which was why I was not able to reproduce this.
