### ISSUE TITLE
Server crash pc_endautobonus

### ISSUE THREAD

**Issue by laziem** [rathena/rathena#3751]
* **rAthena Hash**: 9f88076

* **Client Date**: 20180621

* **Server Mode**: RE

* **Description of Issue**: 
  * Result: server crash
  * Expected Result: no crash
  * How to Reproduce: -
  * Official Information: -
* **Modifications that may affect results**: -
```
Program received signal SIGSEGV, Segmentation fault.
0x081338e0 in pc_endautobonus (tid=4664, tick=384559643,
    id=2011629, data=205680720) at pc.cpp:2466
2466            sd->state.autobonus &= ~autobonus->pos;
(gdb)
(gdb) bt full
#0  0x081338e0 in pc_endautobonus (tid=4664, tick=384559643, id=2011629, data=205680720) at pc.cpp:2466
        sd = 0x0
        autobonus = 0xc427050
#1  0x08051871 in main ()
No symbol table info available.
```

**Comment by Lemongrass3110** [comment]
This seems to be a problem on your end.
Player session is a nullpointer.

Also your call stack seems to be missing, because there are no direct calls from main to pc_endautobonus.

**Comment by laziem** [comment]
Before updating my rAthena, I never got this crash before. I think because it somewhat related to https://github.com/rathena/rathena/issues/3739 since autobonus/bonus4 bAutoSpellOnSkill isn't working after the update, but I'm not sure.
