### ISSUE TITLE
Siren's Voice - needs updating? (revisited)

### ISSUE THREAD

**Issue by raynra** [rathena/rathena#376]
Regarding this issue:
https://rathena.org/board/tracker/issue-9289-sirens-voice-needs-updating/

Not sure if it wasn't properly fixed, or if it broke again. Tested on latest GIT. Same issue -  Siren's Voice is useless against high base/job level characters. Not sure if there is an updated formula or not...

http://irowiki.org/wiki/Siren%27s_Voice

**Comment by cydh** [comment]
hmm, I found the resistance are calculated twice, first in the `skill_castend_nodamage_id` and the 2nd in the `status_get_sc_def`
