### ISSUE TITLE
Some BS/WS skill doesn't give effect while in Madogear

### ISSUE THREAD

**Issue by laziem** [rathena/rathena#3774]
* **rAthena Hash**: f4442fd
* **Client Date**: 20180621
* **Server Mode**: RE
* **Description of Issue**: 
  * Result: Adrenaline Rush, Power Thrust, Maximum Power Thrust, Cart Boost, Full Adrenaline Rush give no effect while using Madogear
  * Expected Result: working
  * How to Reproduce: The skill can be cast but didn't give any effect
* **Modifications that may affect results**: -

**Comment by maqubeks** [comment]
Is this really fixed? The latest revision still doesn't give any effect.
