### ISSUE TITLE
Guild Issue

### ISSUE THREAD

**Issue by bgamez23** [rathena/rathena#3777]
* **rAthena Hash**: 01f61cfa4f750ff74be54fa5793ea9df921da181

* **Client Date**: 2018-06-20

* **Server Mode**: Pre-Renewal

* **Description of Issue**: Failed to send email and Failed to kick guild member when not online.
  * Result: you need to wait for your member to get online before he got kicked from the guild
  * Expected Result: the bug is what if your guild member doesn't goes online anymore. you wont able to kick him.
  * How to Reproduce: create guild. invite guild member. offline the character then send email or kick that member.
  * Official Information: Guild Master are allowed to kick or expel guild member even his/her not online.
  

* **Modifications that may affect results**: Pre-Renewal using 2018-06-20 client.
![screeneternalro010](https://user-images.githubusercontent.com/1854368/50339094-74b4b300-0551-11e9-860b-9d9c4d501b02.jpg)

**Comment by Lemongrass3110** [comment]
As you can see in your chat box your client is still loading the name of the guild player. Thus he displays it as "nameless". This happens because Gravity made the loading of names asynchronous.

Reopen your guild window and you will be able to kick him.
