### ISSUE TITLE
Wrong name item quest

### ISSUE THREAD

**Issue by Desground** [rathena/rathena#378]
rathena\npc\re\quests\eden\eden_quests.txt
mace and staff swap.
}
			if (Class == Job_Acolyte || Class == Job_Acolyte_High || Class == Job_Priest || Class == Job_Monk) {
				callsub S_Select,"We have a mace and a staff",
					1651,"Eden Mace II","Mace","Attack 163","", //P_Staff2
					16005,"Eden Staff II","Staff","INT+3, MATK+150, attack 60",""; //P_Mace2
and
}
			if (Class == Job_Acolyte || Class == Job_Acolyte_High || Class == Job_Priest || Class == Job_Monk) {
				callsub S_Select,"We have a mace and a staff",
					1650,"Eden Mace I","Mace","Attack 142","", //P_Staff1
					16004,"Eden Staff I","Staff","INT+2, MATK+125, attack 60",""; //P_Mace1

Git Hash: '86e856596e1a5706088e072efbf11604e1b42945'

**Comment by nanakiwurtz** [comment]
Thank you :+1: 
Fixed in 36462526a9830267ee0ede78f2834b84133311e9
