### ISSUE TITLE
Earth Strain - Strip Equipment Types

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#3786]
* **rAthena Hash**: 
01f61cf

* **Client Date**: 
not relevant

* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result: 
Since the stripping code overhaul, Earth Strain seems to be stripping all kinds of equipment types, rather than checking for the skill lvl and then strip accordingly to that.
Current source code says: Strip Shield, Armor and Helm on all Skill Levels
Additionaly strip Weapon on lvl 4 and lvl 5 strips simply everything.

**Was this change really intended and is that official or did something went wrong during the strip system overhaul?**

Before it was only stripping 1 gear depending on the chosen skill lvl.
So you had to pick what you're willing to strip.

**New code:**
```
		case WL_EARTHSTRAIN:
			location = EQP_SHIELD|EQP_ARMOR|EQP_HELM;
			if (skill_lv >= 4)
				location |= EQP_WEAPON;
			if (skill_lv >= 5)
				location |= EQP_ACC;
			break;
	}
```

**Old code:**
```
	case WL_EARTHSTRAIN:
		{
			uint16 i;
			const int pos[5] = { EQP_WEAPON, EQP_HELM, EQP_SHIELD, EQP_ARMOR, EQP_ACC };

			if (dmg_lv != ATK_DEF) // Only strip if we make a successful hit.
				break;
			for (i = 0; i < skill_lv; i++)
					skill_strip_equip(src, bl, pos[i], 5 * skill_lv, skill_lv, skill_get_time2(skill_id, skill_lv));
		}
```

  * Expected Result: 
However this is official information i've found (source below)
Difference here is lvl1 and lvl2 were armor is not being stripped but rAthena does so.
But i'm not sure if that's truly official.

[Lv 1] : 70 SP / 15x5 AoE (LengthxWidth) / 6 Hits
Divest **Shield** and **Helm** 6%.
[Lv 2] : 78 SP / 15x6 AoE (LengthxWidth) / 7 Hits
Divest **Shield** and **Helm** 14%.
[Lv 3] : 86 SP / 15x7 AoE (LengthxWidth) / 8 Hits
Divest **Shield**, **Helm** and **Armor** 24%.
[Lv 4] : 94 SP / 15x8 AoE (LengthxWidth) / 9 Hits
Divest **Shield**, **Helm**, **Armor** and **Weapon** 36%. / 10 Hits
[Lv 5] : 102 SP / 15x9 AoE (LengthxWidth)
Divest **Shield**, **Helm**, **Armor**, **Weapon** and **Accessory** 50%.

  * How to Reproduce: 
Use Earth Strain on some players and destroy them while being naked ^^

  * Official Information:
http://kafra.kr/#!/en/IRO/skillinfo/2216

* **Modifications that may affect results**: 
none

**Comment by aleos89** [comment]
I discussed with @mrjnumber1 again and he said that how it currently is on master is correct. This is from his Aegis data he posted in #3476.
