### ISSUE TITLE
Added support for 64bit ticks bug sc_data

### ISSUE THREAD

**Issue by Mateuus** [rathena/rathena#3787]
rAthena Hash:
#3768 (Added support for 64bit ticks)
Client Date:
20180620

Server Mode:
Renewal
Description of Issue: Found a bug where some players were doing max dmg even if they didn't have any item equiped or status point
Result:
![sem titulo](https://user-images.githubusercontent.com/5893666/50379007-9a12f100-0625-11e9-9535-1ae724697e1e.png)

**Comment by Mateuus** [comment]
Compile in Debug x64

now it's negative
![fdassadasdasdasdasdsadasd](https://user-images.githubusercontent.com/5893666/50379756-5de98b80-0639-11e9-8e0a-eb43174a6d8a.png)

**Comment by Lemongrass3110** [comment]
Are you sure you do not have any merge issue?
Have you confirmed this on a clean copy of rAthena?
Did you run the sql upgrade file? Run `describe sc_data;` and post it here.

What operating system and version do you use?
If Windows: Which Visual Studio version and which platform toolset?

Make sure you have recompiled ALL components of the server.
Linux: make clean && make server
Windows: rebuild solution

Generally it looks strange that you have 13021848 in a lot of columns that should be 0.

**Comment by Lemongrass3110** [comment]
No further input from user within 8 days.
