### ISSUE TITLE
Kagerou Pure Soul: Formulas incorrect?

### ISSUE THREAD

**Issue by raynra** [rathena/rathena#380]
Tested GIT from Dec and yesterday with same results.
Renewal server.

http://irowiki.org/wiki/Pure_Soul

I tested Pure Soul at level 5. It appears to give 6% HP instead of 10% HP. Is this intended?

**Comment by cydh** [comment]
what is THE_SKILL_NAME? xD

**Comment by nanakiwurtz** [comment]
3011 (KO_MEIKYOUSISUI)

**Comment by cydh** [comment]
tq.
yes then, the HP & SP are wrong
