### ISSUE TITLE
LG_REFLECTDAMAGE Error

### ISSUE THREAD

**Issue by Angelic234** [rathena/rathena#3801]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/f5f377a7c984148847e11525e85b7254f6d7234a

* **Client Date**: 20180620 RE

* **Server Mode**: RE

* **Description of Issue**: 
  * Result: 
--- nullpo info --------------------------------------------
d:\rathena\rathena\src\map\battle.cpp:7632: in func `unknown'
  * Expected Result: 
  * How to Reproduce: 
When skill "LG_REFLECTDAMAGE" reflect damage , map server display 
--- nullpo info --------------------------------------------
d:\rathena\rathena\src\map\battle.cpp:7632: in func `unknown'
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by rAthenaCN** [comment]
Yes, I have this problem, too.
