### ISSUE TITLE
Cannonspear not working properly

### ISSUE THREAD

**Issue by attackjom** [rathena/rathena#3806]
* **rAthena Hash**: 

<https://github.com/rathena/rathena/commit/f5f377a7c984148847e11525e85b7254f6d7234a>

* **Client Date**: 

2018-05-30

* **Server Mode**: 

RE

* **Description of Issue**: 
  * Result: 
  1. Cannonspear not deal damage when use in range above 9.
  2. Cannonspear do damge single target only.
  * Expected Result:
  1. Cannonspear can deal damage when useskill in 11 range.
  2. do damage in 3x11 area toward a single target.
  * How to Reproduce: 
  Use skill in range in distance from 9 to 11
  Use skill against group of mob that walk toward caster.
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Can you confirm if this works after applying #3848?

**Comment by aleos89** [comment]
Actually, this seems to be related to 6ad062f. I was able to hit targets up to 10 cells away. You can adjust the config to your liking.
