### ISSUE TITLE
Slug Shot - New Slug Behavior

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#3809]
* **rAthena Hash**: 
01f61cf

* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result: Right now, the only slug ammo that works is item id 25187 (the new Shotgun Slug). According to @cydh he said in his original issue that shotguns now require this new slug ammo, however you still can equip the normal bullets?!?!? no idea how that's supposed to work.

At the current state, even though you can equip ammo, they are NOT actually required nor used for thee the skill.
It only uses the item id 25187 if it's in your inventory.

**The new slugs which are offered in all the shops:**
`		case 1: callsub S_Slug_Exchange,13210,24;
		case 2: callsub S_Slug_Exchange,13211,12;
		case 3: callsub S_Slug_Exchange,13212,8;
		case 4: callsub S_Slug_Exchange,13213,6;
		case 5: callsub S_Slug_Exchange,13214,5;`

**do not work for the Slug skill.**

**And the only slug that works is not being sold.**

The exchange NPC exchanges the old slugs, which are being sold in shots (which are not usable) which can only be exchanged in Alberta. And he tells you to *not have the old slugs equipped, even though you can't equip them in the first place*

This is really confusing, and now i'm wondering how it's supposed to work officialy.
Or if there only went something wrong with the shop or the skill update.
 
  * Expected Result: I have no idea how it's supposed to work. Due the limited information from cydh, and the lack of a detailed changelog, i have no idea.... but the not-working slugs and not sold slug that would work... well.

  * How to Reproduce: Use the skill and test out all the available slugs from the shops (prontera 94 207)

* **Modifications that may affect results**: 
none

I'm sorry if i may be stealing your time and maybe, everything is working as it should.
But this update couldn't have been more confusing.

Please enlighten me.
Thank you

**Comment by aleos89** [comment]
kRO changed the Slug Bullets in a patch a couple months ago now. They got rid of the different types and just made it into a single slug (25187).

The `S_Slug_Exchange` takes the old slugs and converts them to the new one. The NPC asks that you don't have any ammo equipped. Don't ask me why Gravity wrote the NPC like this. It's a horrible, horrible, yet again, horrible NPC written by them to exchange these bullets. I scratched my head for over a week dealing with this NPC.

As for the new slug being sold in shops, I'm not sure where these are being sold officially. If you can find the shop it should be in then we can add them.

**Comment by Everade** [comment]
So you're telling me that, the **OLD, useless slugs, are still being sold?**
So the only way to get the slug ammo is to:
Buy old slugs and exchange them for the new one?

Isn't the NPC only there to exchange the old slugs in case you still have them but you can't actually buy them anymore?
That, at least, would make some sense.

I don't have a kRO account.
But it would be a pleasure to have one for testing and checking things out in case you got one.

**Comment by Everade** [comment]
Here's the official updated shop. Enjoy.
`prontera,96,209,4	shop	Rebellion Accessories	564,25187:-1,7663:-1,7664:-1,7665:-1,7940:300,13200:-1,13221:-1,13222:-1,13215:-1,13216:-1,13217:-1,13218:-1,13219:-1,13221:-1,13228:-1,13229:-1,13231:-1,13232:-1,13230:-1
`
