### ISSUE TITLE
Item_trade.txt

### ISSUE THREAD

**Issue by Desground** [rathena/rathena#382]
rathena\db\re\item_trade.txt
// kRO 2013-09-13
1243,475,100	//Novice_Knife
2112,475,100	//Novice_Guard
2352,475,100	//Novice_Plate
2414,475,100	//Novice_Boots
2510,475,100	//Novice_Hood
most likely
1243,499,100	//Novice_Knife
2112,499,100	//Novice_Guard
2352,499,100	//Novice_Plate
2414,499,100	//Novice_Boots
2510,499,100	//Novice_Hood
and
rathena\db\pre-re\item_trade.txt
// New Novice Training Grounds Equipment
1381,499,100	// Novice Battle Axe
1545,499,100	// Novice Mace
1639,499,100	// Novice Rod
1742,499,100	// Novice Composite Bow
2393,499,100	// Novice Adventurer's Suit
2819,499,100	// Swordsman Manual
2820,499,100	// Thief Manual
2821,499,100	// Acolyte Manual
2822,499,100	// Archer Manual
2823,499,100	// Merchant Manual
2824,499,100	// Mage Manual
12323,507,100	// Novice Fly Wing
12324,507,100	// Novice Butterfly Wing
12325,507,100	// Novice Magnifier
13040,499,100	// Novice Cutter
13041,499,100	// Novice Main Gauche
13415,499,100	// Novice Falchion
It seems that not enough 569, Novice_Potion
Git Hash: '36462526a9830267ee0ede78f2834b84133311e9'

**Comment by cydh** [comment]
those need for?
````
// 8   - item can't be sold to npcs
// 16  - item can't be placed in the cart
````

**Comment by Desground** [comment]
1243,475,100 //Novice_Knife
2112,475,100 //Novice_Guard
2352,475,100 //Novice_Plate
2414,475,100 //Novice_Boots
2510,475,100 //Novice_Hood
no trade. can be put in storage only

**Comment by reigneil** [comment]
the last time i remembered when i played on pRO Valkyrie those Novice freebies are droppable but not quite sure about manuals... are these thing changes on kRO?

**Comment by nanakiwurtz** [comment]
Anyone have more info about this one? :smile_cat:

**Comment by reigneil** [comment]
@nanakiwurtz @cydh here's the info from kRO itself https://github.com/ROClientSide/Translation/blob/master/data/itemmoveinfov5.txt or look into your grf files

**Comment by MrAntares** [comment]
1243,475,100 //Novice_Knife
2112,475,100 //Novice_Guard
2352,475,100 //Novice_Plate
2414,475,100 //Novice_Boots
2510,475,100 //Novice_Hood
can't be sold to npc and dropped. can be put in storage only

"Hey bro, U started a new character? Let me show you kafra storage *shows*. See? It has 600 capacity. Guess what? Here take these items! See? Now you can only store 595 items in your storage. YAAAAY!!!!"

THIS IS BULLSHIT

**Comment by Akkarinage** [comment]
@MrAntares let's keep it professional, huh? Rant about Gravity somewhere else.

**Comment by MrAntares** [comment]
I just wanted to point out that even if this is official, it is POINTLESS. Restrictions are made to prevent abusing quest and extra items, like giving access items to others and using multiple reward items on one character. Everyone gets the novice stuffs, and they only take valuable space once you switch to 1st, and there is absolutely no need for them to be restricted, but whatever. I always protested against blindly following official nonsenses, and I get upsed by seeing these. Sorry if that's not acceptable.

Anyways, I made my own item remover NPC to counter these absurd restrictions, so it's solved for me. It's just annoying that I always have to fight useless changes. 
(I'm also surprised that useless restrictions and status icons how swiftly can be fixed, while major skill and core issues remain untouched for months/years.)

Sorry, I have a bad day, and this just came out. No offense tho :)

**Comment by Akkarinage** [comment]
Feel free to commit fixes for things that have been broken for months/years. Also as a temporary solution, perhaps your novice item remover could find its way to the custom npc scripts folder via pull request to counter this official behaviour, like many of those custom scripts do.

**Comment by reigneil** [comment]
@MrAntares
based on what you quoted above there are items occupying your kafra storage that cannot be remove if you update your old server with this commit e06b041 right? or am I thinking different from yours...

**Comment by MrAntares** [comment]
@reigneil 
If I make a new character, the novice items will stick with me forever. They will either waste my inventory or storage capacity, since they can't be dropped/traded/sold (nor used if you are not a novice).

**Comment by reigneil** [comment]
ok... so good for us that kRO leak its item restriction table to debunk the old databases.


so we now use Authoritative Badge without restriction finally... /clap

**Comment by nanakiwurtz** [comment]
@MrAntares: Maybe that's officially intended, so people would consider to upgrade as a VIP.
But you could also make a custom NPC to delete such useless items, since those kind of items can't be used anymore unless you're a Novice forever...
Feel free to submit a Pull Request for an 'item remover' script on /npc/custom/etc

**Comment by nanakiwurtz** [comment]
Too bad the 'getiteminfo' script command can't get the item trade restrictions :frog:

**Comment by reigneil** [comment]
@nanakiwurtz 
looks like you did it reverse...
1 means you can't
17314,32,100	// Infinite_Giant_Fly_Wing_Box (wrong)
7314	1	1	1	1	1	1	1	1	// ´õ»çÀÎ event
while 0 means can
7025,32,100	// Lucifer's_Lament (wrong)
7025	1	1	0	1	1	1	1	1	// ¸¶¿ÕÀÇ ´«¹°

**Comment by nanakiwurtz** [comment]
@reigneil: In the source they used a header like this
Item ID, Candrop, CanTrade, StorageAble, CanPutOnCart etc
7025	1	1	0	1	1	1	1	1
CanDrop 1 would mean that it "can" be dropped
StorageAble 0 means "can't" be put into storage, yes?
Or maybe I misunderstood the header on the source text :thought_balloon: 

But yes, it seems strange though, for example:
547,499,100	// White_Slim_Potion
603,499,100	// Old_Blue_Box
617,499,100	// Old_Violet_Box
Can't be traded + can't be put into storage + can't be put into cart, etc :confounded:

**Comment by zackdreaver** [comment]
@nanakiwurtz 
Not just @Dastgir fail on it.. hehe

**Comment by nanakiwurtz** [comment]
@zackdreaver: So what should I use as a reliable source then? Or just take @reigneil advice, that is to reverse 1 <-> 0 :crocodile:

**Comment by zackdreaver** [comment]
1 mean CANNOT
0 mean CAN

@nanakiwurtz 
kebalik na, dastgir juga salah kemaren, kalo ga gue ingetin

**Comment by nanakiwurtz** [comment]
@zackdreaver: Okelah kalau begichu~ :+1:

**Comment by reigneil** [comment]
(default kRO header via google translate)
// Item ID, drop, posting exchange windows, warehouses, shopping cart, NPC selling, mail, auction, guild warehouse
// Lee Hyung Sik does not recognize blank lines. Be careful.
there is an explanation why they use 0 so... be careful. XD

**Comment by nanakiwurtz** [comment]
1243	1	1	1	1	0	1	1	1	// Novice_Knife
Would be: 1243,499,100 right?
If yes, then I could commit the fix for the items

**Comment by reigneil** [comment]
if we convert it to bitmask used by rAthena well i guess it is true... only bothers me is the number 4 which is wedded partner can override restriction 2
ID,1,2,32,16,8,128,256,64
1243 1 1 1 1 0 1 1 1 // Novice_Knife
1243,449,100 // Novice_Knife
