### ISSUE TITLE
Duplicate lines in item_package

### ISSUE THREAD

**Issue by DriwFS** [rathena/rathena#383]
Well, one more think that I found in my aplication to parse database tables, this time is about item_package.

The below lines, is duplicate one time.

IG_Br_SwordPackage,Clip,0,1,0,0,0,1
IG_Br_MagePackage,Clip,0,1,0,0,0,1
IG_Br_AcolPackage,Clip,0,1,0,0,0,1
IG_Br_ArcherPackage,Clip,0,1,0,0,0,1
IG_Br_MerPackage,Clip,0,1,0,0,0,1
IG_Br_ThiefPackage,Clip,0,1,0,0,0,1

And those have some duplicates.

IG_Sagittarius_Scr_Box,Sagittarius_Scroll,0,1,0,0,0,1
IG_Sagittar_Di_Scroll_Box,Sagittar_Diadem_Scroll,0,1,0,0,0,1
IG_Capri_Crown_Scroll_Box,Capri_Crown_Scroll,0,1,0,0,0,1
IG_Capricon_Di_Scroll_Box,Capricon_Di_Scroll,0,1,0,0,0,1
IG_Aquarius_Di_Scroll_Box,Aquarius_Diadem_Scroll,0,1,0,0,0,1
IG_Lovely_Aquarius_Box,Lovely_Aquarius_Scroll,0,1,0,0,0,1
IG_Pisces_Diadem_Box,Pisces_Diadem_Scroll,0,1,0,0,0,1
IG_Energetic_Pisces_Box,Energetic_Pisces_Scroll,0,1,0,0,0,1
IG_Aries_Scroll_Box,Aries_Scroll,0,1,0,0,0,1
IG_Taurus_Di_Scroll_Box,Taurus_Diadem_Scroll,0,1,0,0,0,1
IG_Taurus_Crown_Scroll_Box,Taurus_Crown_Scroll,0,1,0,0,0,1
IG_Gemi_Diadem_Scroll_Box,Gemi_Diadem_Scroll,0,1,0,0,0,1
IG_Gemi_Crown_Scroll_Box,Gemi_Crown_Scroll,0,1,0,0,0,1

I thinks this is not right, but maybe i'm wrong.

**Comment by cydh** [comment]
those are repeated as intended
