### ISSUE TITLE
WarpPortal(acolyte skill) duration not working even if change

### ISSUE THREAD

**Issue by AzarthMZintos** [rathena/rathena#3833]
* **rAthena Hash**: f5f377a7c

* **Client Date**: 2018-06-21a

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: WarpPortal too fast even if you change it duration, all lvls feel the same duration
  * Expected Result: Should be able to change it duration
  * How to Reproduce: change the duration skills at skill_cast_db and nothing will change, even using the dirente skills levels
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Same as #3807. Make sure you have that fix applied.

**Comment by AzarthMZintos** [comment]
Ops my bad Ty @aleos89 is working now
