### ISSUE TITLE
Madogear - Skill Requirements

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#3834]
* **rAthena Hash**: 
01f61cf

* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result: 
 This has been an ongoing topic back in the days. And i was already saying back then that the gear must not be equipped, but only be in your inventory instead. I have no idea why this has been changed so many times, even though it has been clarified many times (it was also fixed for a short period of time and has then been reverted). Maybe i'm remembering 3ceam, i'm not sure, but people kept blaming me for being accurate how it is today on rAthena.
Well, here i am again trying to get this straight. ^^

**How it is:**
```
2257,0,0,50,0,0,0,99,0,0,mado,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1549:16030:16031:16032		//NC_PILEBUNKER

2262,0,0,20:40:60,0,0,0,99,0,0,mado,0,0,6146,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2800					//NC_ACCELERATION

2267,0,0,200,0,0,0,99,0,0,mado,0,0,6146,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2802						//NC_SELFDESTRUCTION
2268,0,0,100,0,0,0,99,0,0,mado,0,0,6360,3,6363,3,6362,3,6361,3,0,0,0,0,0,0,0,0,0,0,6146,2,2803			//NC_SHAPESHIFT
2269,0,0,20,0,0,0,99,0,0,mado,0,0,6146,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2804:2809:2810				//NC_EMERGENCYCOOL

2272,0,0,60:70:80,0,0,0,99,0,0,mado,0,0,6146,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2805					//NC_MAGNETICFIELD
2273,0,0,80:90:100,0,0,0,99,0,0,mado,0,0,6146,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2806				//NC_NEUTRALBARRIER
2274,0,0,80:100:120,0,0,0,99,0,0,mado,0,0,6146,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2808				//NC_STEALTHFIELD
```

  * Expected Result: 
 You should be able to cast all these skills without actually having the gear requirements equipped. They only need to be in your inventory instead!

```
2257,0,0,50,0,0,0,99,0,0,mado,0,0,1549:16030:16031:16032,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0		//NC_PILEBUNKER

2262,0,0,20:40:60,0,0,0,99,0,0,mado,0,0,2800,0,6146,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0					//NC_ACCELERATION

2267,0,0,200,0,0,0,99,0,0,mado,0,0,2802,0,6146,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0						//NC_SELFDESTRUCTION
2268,0,0,100,0,0,0,99,0,0,mado,0,0,2803,0,6360,3,6363,3,6362,3,6361,3,0,0,0,0,0,0,0,0,6146,2,0			//NC_SHAPESHIFT
2269,0,0,20,0,0,0,99,0,0,mado,0,0,2804:2809:2810,0,6146,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0				//NC_EMERGENCYCOOL

2272,0,0,60:70:80,0,0,0,99,0,0,mado,0,0,2805,0,6146,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0					//NC_MAGNETICFIELD
2273,0,0,80:90:100,0,0,0,99,0,0,mado,0,0,2806,0,6146,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0				//NC_NEUTRALBARRIER
2274,0,0,80:100:120,0,0,0,99,0,0,mado,0,0,2808,0,6146,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0				//NC_STEALTHFIELD
```

  * Official Information:
**kRO Skill Description:**
 > 스킬 사용 시 마도 기어 전용 장비 <셰이프 쉬프터> 를 장비 혹은 소지하고 있어야 하며
**It clearly says:**
 Equipped OR in Possession (Inventory).

**iROwiki also states:**
 > All of the skills can only be cast when the required gear is in your inventory. Exception: Hover skill requires you to equip the Hovering Booster.

https://irowiki.org/wiki/Madogear

* **Modifications that may affect results**: 
 None

**Comment by aleos89** [comment]
This was fixed in dc413a3.

**Comment by Everade** [comment]
@aleos89 
![image](https://user-images.githubusercontent.com/12261601/55269612-b1512280-5295-11e9-94d5-b633491e202e.png)
![image](https://user-images.githubusercontent.com/12261601/55269644-3dfbe080-5296-11e9-8056-58568699b701.png)

**No it has never been fixed, that's why i'm reporting it.**
I clearly stated it above that it's not working as intended.

Another proper report effort for nothing.

**Comment by aleos89** [comment]
Please see [here](https://github.com/rathena/rathena/blob/master/src/map/skill.cpp#L15785). There are source checks to look in the inventory as well for these skills.
