### ISSUE TITLE
Guildstorage Duplicate Issue

### ISSUE THREAD

**Issue by Zarbony** [rathena/rathena#3836]
* **rAthena Hash**: 

* **Client Date**: 2018 06 20

* **Server Mode**: Pre-Renewal 

* **Description of Issue**: 
  * Result: Players can Duplicate some Items, a Player makes from 3 Tao Gunka Cards, 2256 pieces and he dont do anything to invoke this. I tested by myself i placed some equipparts in Guild Storage and after i reopen them i put them out, then i reopen them again and the Items are in storage aswell and in my inventory so i can duplicate them endless in SQL the Items are still available and wont deleted.
  * Expected Result: FIx the Guild Storage SQL Duplicate Issue and use guild storage log sql
  * How to Reproduce: open the Guild Storage with ""`@gstorage`"" and put items there, then reopen and put them out look at the sql and do this again so you can duplicate them
  * Official Information: I Dont know
  

* **Modifications that may affect results**:

**Comment by anacondaqq** [comment]
Please add hash, and proper steps how to reproduce.

**Comment by Zarbony** [comment]
> Please add hash, and proper steps how to reproduce.

How i add the Hash from my Version?
I loaded it from 30.12.2018 and have done some source edits too.
Where i can find the Hash? 

Hmm how i explain it exactly? :X 

- Open Guild Storage with atcommand "`@gstorage`"
- Put Equip Items in the Storage
- Close the Storage and open it again
- Just Move the Equipparts out of the Storage and close it
- Then Open the Storage again and the items are still there

i watched at my SQL Database and the Items will be added but wont be removed from my SQL.
But the Guild Storage Log shows of course that i removed an item.
My Item ID was Custom at 22828 and 22829 thats my Santa Items.

But this Issue was with an armor on ID 22012 aswell and someone got from 3 Tao Gunka Cards, 2253 Cardsbut he wasnt online for about 4 Days after Putting this 3 Cards into the storage.

Another Player lost a big amount of Items, Randomly from Aloe to Custom IDs at 21000 and higher.
I just added the datas to an new SQL File with the new Structure from main.sql out of the rAthena SQL Folder after git pull them and Updated it to the newest one from updates folder...

But the Issue are still there, in my Version from 2016 i dont have an error and this one works without an issue but then i Updated the Whole Server to the newest version and added an new Guild Storage sql, i deleted the old one and the players added new items in the SQL.

At First the Case "ID" was broken, so it wasnt an primarykey and i has to added this one new and this wont helped anyways...

**Comment by Everade** [comment]
Sounds like you've made some mistakes while merging the updates.
Please test on a clean rAthena test server and a clean/new rAthena sql database without any modifications.

If the problem does not persist there, then i recommend starting to compare the test server database and source code with that you've currently in place.

**Comment by aleos89** [comment]
Tested with 7eed88c and was unable to reproduce this. As @Everade stated, it sounds like while merging the guild storage update you may have created some issues. If you check out from Git it will allow you to easily see the differences you make with your custom changes so you can easily track down the issue.
