### ISSUE TITLE
Two itens not add item_db/item_trade

### ISSUE THREAD

**Issue by DriwFS** [rathena/rathena#384]
17491,475,100        //Refinement_Ore_Box_VII
17492,475,100        //Refinement_Ore_Box_VII(10)

Is this.

**Comment by nanakiwurtz** [comment]
Sorry, I don't understand what you mean...

**Comment by DriwFS** [comment]
This items don't exist in item_db (17491 and 17492)

17490,Time_Travel_Lucky_Egg,Time Travel Lucky Egg,2,10,,10,,,,0,0xFFFFFFFF,63,2,,,,,,{ getitem callfunc("F_Rand",4486,4488,4498,6238,6239,6228,6232,2190,19661,5822,18832,18754),1; },{},{}

?????????????????????

17494,Rise_Midgard_Lucky_Egg,Rise Midgard Lucky Egg,18,10,,10,,,,,,,,,,,,,{/*TODO*/},{},{}

I serch by ctrl+f in last revision and in my revision, both revision dont have this items...

**Comment by cydh** [comment]
the title is something. xD
but yeah, those items aren't in item_db yet
