### ISSUE TITLE
Guild Storage Expansion on Pre-renewal

### ISSUE THREAD

**Issue by Daegaladh** [rathena/rathena#3840]
* **rAthena Hash**: 93a7a20f6805770c9d3476fcd6f74329a5f4c5fc

* **Client Date**: Irrelevant

* **Server Mode**: Pre-renewal

* **Description of Issue**: 
  * Result: The skill Guild Storage Expansion is avalaible on pre-renewal
  * Expected Result: It shouldn't be there
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Fixed in cbe0d6b.
