### ISSUE TITLE
OGH OnTouch trigger area

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#3842]
* **rAthena Hash**: 
01f61cf

* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result: 
**npc/re/instances/OldGlastHeim.txt ~line 1110**
`2@gl_k,171,120,0	duplicate(#ogh_2-1)	#ogh_3-1	HIDDEN_WARP_NPC,20,20`
This OnTouch Event is so big, that it overlaps with the small walking area at the top.

That means that it's possible to trigger the event before even being able to enter the right area of the map.
 Please note that in accordance to enter the right side of the map, you first have to enter the left side and kill all the monsters, which then spawns a boss "based on luck ~ random", and only enables the right side portal after killing the mentioned boss monster.

Since this OnTouch Event spawns monsters, and the left map events include "Kill all monsters on Map".
This will also kill all the too early spawned monsters on the right side, in case you walked into the trigger area shown on the picture. **This possibly creates some issues as the monsters are bound to OnMyMobDead events since no player will be attached?!**

![eventtrigger_right png b32dee998d30ae6a2f22529f82490721](https://user-images.githubusercontent.com/12261601/50748199-744a3680-1238-11e9-853c-26babf4ea4a9.png)

  * Expected Result:
This OnTouch Event should be smaller in size or replaced so it does not overlap with the corridor area.

  * How to Reproduce: 
Play the Old Glast Heim instance until you reach the second map, then walk into the red marked area as shown on the screenshot.

  * Official Information:
Don't have any.

* **Modifications that may affect results**: 
none

**Comment by Atemo** [comment]
>That means that it's possible to trigger the event before even being able to enter the right area of the map.

No. `2@gl_k,171,120,0 duplicate(#ogh_2-1) #ogh_3-1 HIDDEN_WARP_NPC,20,20` is disabled by default. The npc is only enabled after the dead of the boss left side.

>Since this OnTouch Event spawns monsters, and the left map events include "Kill all monsters on Map".

There is none event that "Kill all monsters on Map" after the dead of the boss left side.
