### ISSUE TITLE
RA_WUGSTRIKE is possible to attack the player.

### ISSUE THREAD

**Issue by evehour** [rathena/rathena#385]
RA_WUGSTRIKE that despite this attack is possible for the player to not a pvp map. (ex. prontera)

**Comment by reigneil** [comment]
confirmed.
i dont see skill fail in skill.c maybe we can use jumpkick skill code here something like this
	case RA_WUGSTRIKE:
		if( battle_check_target(src, bl, BCT_ENEMY) > 0 ) {
			if( sd && pc_isridingwug(sd) ){
				short x[8]={0,-1,-1,-1,0,1,1,1};
				short y[8]={1,1,0,-1,-1,-1,0,1};
				uint8 dir = map_calc_dir(bl, src->x, src->y);
					if( unit_movepos(src, bl->x+x[dir], bl->y+y[dir], 1, 1) ) {
						clif_blown(src);
						skill_attack(BF_WEAPON, src, src, bl, skill_id, skill_lv, tick, flag);
					}
			}else if( path_search(NULL,src->m,src->x,src->y,bl->x,bl->y,1,CELL_CHKNOREACH) )
				skill_attack(BF_WEAPON,src,src,bl,skill_id,skill_lv,tick,flag);
		} else
			clif_skill_fail(sd, skill_id, USESKILL_FAIL_LEVEL, 0);
		break;
