### ISSUE TITLE
Fire Dance + SC_POEMBRAGI

### ISSUE THREAD

**Issue by siriousb** [rathena/rathena#3858]
* **rAthena Hash**: Any
* **Client Date**: 2018-06-20
* **Server Mode**: RE
* **Description of Issue**: The Fire Dance skill is not being affected by SC_POEMBRAGI.

It should happen.

https://www.youtube.com/watch?v=11FF6AenBFE

**Comment by aleos89** [comment]
Can you give a little more detail to the report? What level Poem of Bragi were you using? What was the INT of the song caster?

There are no restrictions of what skills are affected or not by Poem of Bragi so this report doesn't make sense.

**Comment by siriousb** [comment]
I'm using INT 130, yet the Poem is not having any effect on the ability, please watch the video above, then try to spam the skill, it does not work.
