### ISSUE TITLE
[RE] Royal messenger ep 16.1 OnTouch dialogue 

### ISSUE THREAD

**Issue by zackdreaver** [rathena/rathena#3860]
* **rAthena Hash**: 6bea2da34d19e9c6d6d1e9d2af2a36d772c129ba

* **Client Date**: n/a

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Line "I am looking for the hero who returned from the expedition...", isn't triggered on player without requirement needed (New world quest?)
  * Expected Result: Should be triggered
  * How to Reproduce: Check it with character without the quest requirement
  * Official Information: I've checked it with my SC level 116 on iRO and it's triggered
  

* **Modifications that may affect results**: n/a

**Comment by siriousb** [comment]
my quests are with many bugs, always lock the dialogues.

**Comment by Atemo** [comment]
@siriousb please open a new thread and explain your issue.
