### ISSUE TITLE
item_cash_db does not show last tab 8: Sale

### ISSUE THREAD

**Issue by zeffen** [rathena/rathena#3863]
* **rAthena Hash**: 

* **2018-11-04**: 

* **RE**: 

* **Description of Issue**: 
  * Result: My Rops Store is set up and it works, but on the last tab, no matter what I put on it, it does not show any items. 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Balferian** [comment]
Did you add item in sale table?
Try to use command @limitedsale and add item to sale.
1)add your item in iteb_cash_db to group 8.
2)add your item to sale.

**Comment by Lemongrass3110** [comment]
As @Balferian said this tab is special. You need to add the items in the cash db to tab 8 and then add times for the sale for each item.
