### ISSUE TITLE
Unlimited Spam of skills before cooldown triggers

### ISSUE THREAD

**Issue by darhylism** [rathena/rathena#3864]
* **rAthena Hash**:  444d7394c2ea53e4875acc4bbac957cdd6fe99de

* **Client Date**: 2018-05-30b

* **Server Mode**: Renewal

* **Description of Issue**:  Skills can be spammed before the cooldown/delay triggers

  * Result: Skill can be spammed even if you have Cooldown / low attackspeed

  * Expected Result: 1 Skill per cast regardless of spamming the button
  * How to Reproduce: Example , Set your character to be low aspd like 170 to 180 then cast skill "Double Strafe" spam it as fast as you can, you can get about 2 to 4 Double Strafe casted. This work on all skills
  * Official Information: 

* **Modifications that may affect results**: NONE

**Comment by darhylism** [comment]
update: i found out that this bug only occurs on my VPS live server and not on my Test Server on laptop. is it because of the compiler version? devtoolset, or other things?

**Comment by Daegaladh** [comment]
Same happened to me on Ubuntu 18.04

**Comment by Lemongrass3110** [comment]
Let me make things clear:
This only happens if your system was running too long. This is not related to any specific OS or compiler.
We might still find some leftovers from before adding support for 64 bit ticks. So keep that in mind!
