### ISSUE TITLE
Item Combo Ammo - not triggering

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#3865]
* **rAthena Hash**: 
01f61cf

* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result: 
Item combo script of Gust Bow using Arrow of Wind does not trigger.

  * Expected Result:
Effect should work as given within the item_combo.txt database.
`1733:1755﻿,{ bonus bLongAtkRate,25; bonus3 bAutoSpell,"NJ_HUUJIN﻿",5,(readparam(bInt)>39) ? 300 : 100; }`

  * How to Reproduce: 
Wear item id 1733 and equip the arrows item id 1755.
Attack a monster of your choice.

  * Official Information:
Item combo is existant officialy and in rAthena.

* **Modifications that may affect results**: 
Custom Battleconfig
`ammo_unequip: no
`

**Comment by aleos89** [comment]
Did you happen to apply [this](6bea2da) fix from the other day?

**Comment by Everade** [comment]
No, but he mentioned in the report that the effects work if you equip it freshly and the issue only come sup when you relog with the equipment on.

So i thought it might not be directly related since it didn't work at all.

**Comment by aleos89** [comment]
Tested on fc7e46e and I was casting Wind Blade during my attacks.

![image](https://user-images.githubusercontent.com/3521753/52451882-cec40480-2b0e-11e9-92c5-7f44b850ecc5.png)

**Comment by Everade** [comment]
@aleos89 
Issue was related to **import**/item_combo.txt

I think after successfully loading the db/re/item_combo.txt
it started to load import/item_combo.txt from ID 0 and basically deleted all official combos.

I have moved my custom combos to the re/item_combo file instead, **now with an empty import file, everything works just fine.**

**Sidenote:**
This bug was NOT persistent before as i've been using the import file version since > 1 year

**Comment by Lemongrass3110** [comment]
Related to #1922
