### ISSUE TITLE
@points command not working with negative values

### ISSUE THREAD

**Issue by Daegaladh** [rathena/rathena#3866]
* **rAthena Hash**: 6bea2da34d19e9c6d6d1e9d2af2a36d772c129ba

* **Client Date**: 

* **Server Mode**: Both

* **Description of Issue**: 
  * Result: e.g. having 50 kafra points and using `@points` -10 will return "Removed 0 kafra points. Total 50 points."
  * Expected Result: Actually removing the points
  * How to Reproduce: Just use the command with a negative value
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by anacondaqq** [comment]
https://github.com/rathena/rathena/pull/3252/files might be related to
