### ISSUE TITLE
Battle config is missing documentation

### ISSUE THREAD

**Issue by Kezzo** [rathena/rathena#3869]
The value `enable_baseatk` in the [battle.conf](https://github.com/rathena/rathena/blob/master/conf/battle/battle.conf) file which has a default value set to 0x29F is represented in bit like this: `0010 1001 1111`.
The bit fields in the "Note 3" documentation only includes a description for the bit fields from 1 to 16. As we see from the code and from the default value this field can affect more unit types but are not documented there.

* **rAthena Hash**: 
6bea2da34

**Comment by Kezzo** [comment]
After a discussion in discord we found that it might be good to add this too all config files that contain the "Note 3" documentation entry. Does anyone have any thoughts on this?

**Comment by aleos89** [comment]
I was about to comment the same thing. Might as well sync it across the other files. There are instances where a BL may not even be considered for a battle config, but it's still a valid documentation value.

**Comment by Kezzo** [comment]
I updated the pull request so all config files have the proper documentation:
https://github.com/rathena/rathena/pull/3870
