### ISSUE TITLE
Item Group aren't random bug?

### ISSUE THREAD

**Issue by reigneil** [rathena/rathena#387]
everytime i start my server then i use old blue boxes i always get the following items
You got Gift Box (1).
You got Claw of Monkey (1).
You got Armlet of Obedience (1).
You got Spore Doll (1).
You got Giant Butterfly Wing (1).
You got Horseshoe (1).
You got Single Cell (1).
You got Gift Box (1).
You got Broken Needle (1).
You got Accessory (1).
this is also happen in other item groups like OCA's, OVB's, Gift Box's etc... is this intended?
i'm using dd3e7e17
how to reproduce:
1.just start a fresh server with only you ingame so that no one is using boxes other than yourself.
2.get old blue boxes for example and start opening 10 pieces of it.
3.logout your char then close your server.
4.start again your server then go online and start opening old blue boxes again which you will notice that you get the same items.

**Comment by cydh** [comment]
something D:
