### ISSUE TITLE
nk - 0x08 - Skill ignores caster's % damage cards not working

### ISSUE THREAD

**Issue by tanlor** [rathena/rathena#3871]
* **rAthena Hash**: 40a4edc

* **Client Date**: 2015-11-04

* **Server Mode**: Pre-Renewal

* **Description of Issue**: Skills that are set with nk 0x08 - Skill ignores caster's % damage cards on db/(pre-)re/skill_db.txt still scales damage with Race Type/Turtle General cards.
  * Result: Even with 0x8 set, skills like Cart Termination and Soul Breaker scales with % damage cards.
  * Expected Result: With 0x8 set, skills shoudn't scale with % damage cards.
  * How to Reproduce: Set nk to 0x8 on db/(pre-)re/skill_db.txt, reload skill configuration, than equip an Axe [4] with General Turtle Card and an Axe [4] without any cards - the damage should be the same with both axes, but the Axe with General Turtle Card deals more damage.
  * Official Information: On Pre-Renewal formulas, the damage of Cart Termination, for example, don't scale with % Damage cards, only with Flat Attack provided by cards like Zipper, for example.
  

* **Modifications that may affect results**: Some fix on battle.cpp, I guess?

**Comment by tanlor** [comment]
#2577

**Comment by celestearike** [comment]
apparently missing this stuff ::
battle_calc_cardfix
NK_NO_CARDFIX_ATK
which I am not able to code in
