### ISSUE TITLE
the latest emualtor git pull origin gave an error in charserv.bat (error is below) and preventing mapserv.bat from connecting. this did not occure before doing git pull origin

### ISSUE THREAD

**Issue by kaosoflightanddark** [rathena/rathena#3875]
* **rAthena Hash**: 

* **Client Date**: has nothing to do with client but its the latest

* **Server Mode**:  renewal

* **Description of Issue**: 
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**: 
  
  

the white area is my directory if you are wondering
![capture](https://user-images.githubusercontent.com/46796132/51346391-36ee7000-1aa6-11e9-8569-2b5dcb16649f.JPG)

**Comment by aleos89** [comment]
That debug error is on your behalf. You need to upgrade your SQL table by importing `sql-files/upgrade/upgrade_20181224.sql`.

**Comment by kaosoflightanddark** [comment]
> 
> 
> That debug error is on your behalf. You need to upgrade your SQL table by importing `sql-files/upgrade/upgrade_20181224.sql`.

THANK YOU SO SO MUCH
