### ISSUE TITLE
everything working great, i press ctrl+c to close the 3 cmds and type Y and press enter. If i open the server AGAIN, an error in charserv.bat occurs. it says connection to login server lost. please help. picture is attached

### ISSUE THREAD

**Issue by kaosoflightanddark** [rathena/rathena#3879]
Everything was working fine and great. i played in game and everything. If i close the command promots that appear when i run runserver.bat and then open runserver.bat AGAIN, charserv.bat gives an error of 'connection to login server lost'
it was working fine though :/
by the way, if i restart my computer then the error won't appear until the next time i close the server after i open it. but i dont wanna keep restarting my computer. please help.

* **rAthena Hash**: 

* **Client Date**:  kro clean client
![515](https://user-images.githubusercontent.com/46796132/51415983-65d91480-1b80-11e9-94ee-afa22a46610a.JPG)

* **Server Mode**:  renewal

* **Description of Issue**: 
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Please submit support questions on he forum.
