### ISSUE TITLE
custom currency shop

### ISSUE THREAD

**Issue by joelolopez** [rathena/rathena#388]
custom currency shop still displays not enough zeny message , and then not enough 'gold' on the dispbottom msg

**Comment by anacondaqq** [comment]
because you have not enough zeny on character (check zeny)
when you have enough zeny on character, you will not have this warning.

**Comment by aleos89** [comment]
That's because the client is setup only for Zeny. We just send the "fail" message back to the client which is setup to tell the player that they don't have enough Zeny, even though we are checking for a specific item or variable.

**Comment by joelolopez** [comment]
i guess theres no solution to remove the zeny msg when using custom currency shops, its more on the client side

**Comment by aleos89** [comment]
Correct, there's nothing we can do with it because of client limitations.
