### ISSUE TITLE
MvP Ladder Warper Map Crashed

### ISSUE THREAD

**Issue by bgamez23** [rathena/rathena#3881]
* **rAthena Hash**: 79dffbd789da4e65c5109c0bbd6015b1c11f5937

* **Client Date**: 2018-06-20dRagexeRE

* **Server Mode**: Renewal

* **Description of Issue**: [Warning]: Unable to restore stack! Double continuation!
[Debug]: Previous script (lost):
[Debug]: Source (NPC): MvP Ladder Warper at prontera (164,171)
[Debug]: Current script:
[Debug]: Source (NPC): FAKE_NPC (invisible/not on a map)
[Error]: Server received crash signal! Attempting to save all online characters!

![image](https://user-images.githubusercontent.com/1854368/51443442-e7b57300-1d23-11e9-9dfb-6c4f4a42258e.png)

  * Result: Map Crashed
  * Expected Result: 
  * How to Reproduce: Finish MVP Ladder event
  * Official Information:
  

* **Modifications that may affect results**: Disable Renewal Cast

**Comment by RadianFord** [comment]
https://github.com/rathena/rathena/commit/ec4f03109d50ac2b8f8f99767aa3a628bb10b68c

**Comment by aleos89** [comment]
At what point in the script are you getting this warning?
