### ISSUE TITLE
Please Don't Forget me

### ISSUE THREAD

**Issue by maxtorohell** [rathena/rathena#3882]
* **rAthena Hash**: 129812d

* **Client Date**: 20151104

* **Server Mode**: Pre-Renewal

* **Description of Issue**: Please Don't Forget me!! Skill has no effect while using Speed Potion.
  * Result: When walking on the song with speed potion the character does not slow down or reduce his aspd.
  * Expected Result: Have the effect while using speed potion.
  * How to Reproduce: Sing and run on the song.
  * Official Information: Decreases ASPD by 3% per SkillLV and Movement rate by 2% per SkillLV of all enemies in the area of effect. 
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
```cpp
	case SC_DECREASEAGI:
	case SC_QUAGMIRE:
	case SC_DONTFORGETME:
		if(sc->data[SC_SPEEDUP1])
			return 0;
		break;
```
According to this here, it's saying that Speed Potions ignore these skills.
