### ISSUE TITLE
Quick Draw Shot will no longer be activated when the attack speed is 193

### ISSUE THREAD

**Issue by teededung** [rathena/rathena#3883]
* **rAthena Hash**: Not related
* **Client Date**: Not related
* **Server Mode**: Renewal
* **Description of Issue**: 
  * Expected Result: The Quick Draw Shot skill will no longer be activated when the attack speed is 193
  * Official Information: 
http://ro.gnjoy.com/news/notice/View.asp?BBSMode=10001&seq=6686&curpage=14
https://ragnarok.gamepedia.com/Quick_Draw_Shot

**Comment by aleos89** [comment]
This is actually a mistranslation. It should read “Fixed a problem where Quick Draw Shot was not activating at 193 ASPD".
