### ISSUE TITLE
Shield View ID

### ISSUE THREAD

**Issue by Vennren** [rathena/rathena#389]
To make custom shields working outside of the range of shield ID's, a view ID has to be inserted.
Tested on paladins to be able to use shield buffs without a View ID set (0) and with a View ID set (2), the former would not allow me to use paladin buffs, the latter would.

I assume this isn't as intended due to a lot of people not bothering with custom shield sprites.

**Comment by reigneil** [comment]
all shields have a classnum more than 0 if you look at it on iteminfo.lub. and also based on this https://github.com/rathena/rathena/blob/master/doc/item_db.txt zero is considered bare fist

**Comment by Akkarinage** [comment]
Essentially, emulating Ragnarok Online means that we don't need to build in code for custom eventualities. Perhaps this should be a src request rather than a bug report.
