### ISSUE TITLE
Party Skills not working

### ISSUE THREAD

**Issue by LyndisRain** [rathena/rathena#390]
Skills that target a party, only while in a party, no longer work as of today. It took me a while but I've discovered the problem in skill.c skill_area_sub. The fix for WM_VOICEOFSIREN & WM_LULLABY_DEEPSLEEP causes all skills that use this function (Angelus, Wind Walk, etc), to not work when they hit this part:
if (src == bl && !(flag&BCT_SELF))
return 0;
Because those skills don't have the BCT_SELF flag it just ends without doing anything, and there's no error because technically it's working properly. Commenting out those two lines fixes the problem, but brings back the original issue with WM_VOICEOFSIREN & WM_LULLABY_DEEPSLEEP.

**Comment by cydh** [comment]
I did it wrong, I think better make new flag for BCT_WOS

**Comment by cydh** [comment]
thank you :D
