### ISSUE TITLE
Wrong ASPD

### ISSUE THREAD

**Issue by zeffen** [rathena/rathena#3900]
* **rAthena Hash**: 

* **Client Date**: 

* **Server Mode**: 

Renewal 

* **Description of Issue**: 
  * Result:  Royal Guard: (Base 175) (Job 60) (STR 120) (AGI 120) (VIT 90) (INT 1) (DEX 100) (LUK 1) = ASPD 180
  * Expected Result: Royal Guard: (Base 175) (Job 60) (STR 120) (AGI 120) (VIT 90) (INT 1) (DEX 100) (LUK 1) = ASPD 182.42
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by secretdataz** [comment]
No source of expected result provided.
