### ISSUE TITLE
[suggestion] announce to array group of players gid

### ISSUE THREAD

**Issue by sader1992** [rathena/rathena#3901]
the idea is to have another announcement command
`*announce "<text>",<flag>{,<fontColor>{,<fontType>{,<fontSize>{,<fontAlign>{,<fontY>}}}}};`
where the falg would be .@GID_Array

this would be helpful in a lot of things
for example like the eamod bgannounce send the announce to players who have sd->state.bg_listen = true

but this way is very limited
instead we can do something like this
example for how it would look:

```cs
bindatcmd("listenbg",strnpcinfo(3)+"::Onlistenbg",0,99);
bindatcmd("listenpvp",strnpcinfo(3)+"::Onlistenpvp",0,99);
bindatcmd("listengvg",strnpcinfo(3)+"::Onlistengvg",0,99);

Onlistenbg:
	.@ndx = inarray($BG_Group,getcharid(3));
	if(.@ndx == -1){
		$BG_Group[getarraysize($BG_Group)] = getcharid(3);
		message "<character name>","BattleGround announcement ON";
	}else{
		message "<character name>","BattleGround announcement OFF";
		$BG_Group[.@ndx] = 0;
	}
end;

OnEvent_Somthing_Happen_In_Bg:
	announce "Somthing Happen In Bg!!!",$BG_Group;
end;
```
same code for the other commands above
this would expand the announce
ofc it would be another name

_____________________________________________________
while typing the suggestion
I thought why not making the list of players in the server and in each map as an array and we can then edit the command to work on everything ,this would need full edit on the clif_broadcast<< I won't add any info as it just got me , so just saying
something like GID_GROUP
```cs
*announce "<text>",<flag>{,<fontColor>{,<fontType>{,<fontSize>{,<fontAlign>{,<fontY>{,.@array}}}}}};
announce "Somthing Happen In Bg!!!",GID_GROUP,0,0,0,0,0,$BG_Group;
```

I will try to work on the idea above if no one did and if rathena devs are OK with it

**Comment by luan122** [comment]
Hey sader not rushing anything, just curious and excited about it, how is the progress of this feature? :D
