### ISSUE TITLE
[suggestion] array to vector

### ISSUE THREAD

**Issue by sader1992** [rathena/rathena#3902]
a function in the src ofc
to convert the array data to vector
example:
```cs
std::vector<int> my_vector{};
struct script_data *data = script_getdata(st, 0);
int_array_to_vector(data, my_vector);
or
string_array_to_vector(data, my_vector);

bool string_array_to_vector(struct script_data *data, std::vector<std::string> &my_vector);
bool int_array_to_vector(struct script_data *data, std::vector<int> &my_vector);


```
however I don't know what the best place to put it in

also it might be a good idea to do vector to array at the same time

**Comment by aleos89** [comment]
I know in the long term we want to eventually utilize C++ utils as much as we can, but I'm not sure this rests too high in priority right now with what we have in queue.

**Comment by Lemongrass3110** [comment]
Will be added eventually whenever we need it during further C++ improvements.
As there is no need for it right now, we will close this issue, as we most likely would not think about linking it whenever we would add this functionality anyway.

Feel free to open a PR if you want to, but please with at least one usage in rAthena itself and not only for customizations.

Thank you for the idea though!
