### ISSUE TITLE
Holy Cross

### ISSUE THREAD

**Issue by zeffen** [rathena/rathena#3904]
* **rAthena Hash**: 

* **Client Date**:  2018-11-07

* **Server Mode**:  Renewal

* **Description of Issue**:  The ability of the Holy Cross works without having a weapon equipped.
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Daegaladh** [comment]
That's how it works

**Comment by sader1992** [comment]
Dam Boy !!! don't launch a lot of rocket on people xD
