### ISSUE TITLE
ASPD of incorrect characters

### ISSUE THREAD

**Issue by zeffen** [rathena/rathena#3905]
* **rAthena Hash**: 

* **Client Date**:  2018-11-07

* **Server Mode**:  Renewal

* **Description of Issue**:  The Royal Guard with (Base 175) (Job 60) (STR 120) (VIT 90) (INT 1) (DEX 100) (LUK 1) must have ASPD 182.42 as in official, however in rAthena it stays with ASPD 180. Not only does the Royal Guard have the incorrect ASPD, but all the characters.
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by secretdataz** [comment]
Please provide more evidences other than the text you provided.

**Comment by Daegaladh** [comment]
iROwiki calculator doesn't count as evidence, but you're kinda right.
I've tested it on aegis, it's capped to 150/50 but the total stats are the same.
![image](https://i.imgur.com/IfQs0ZM.png)

**Comment by flamefury** [comment]
kRO ASPD formula is different from iRO, and rAthena defaults to kRO based mechanics.
I expect that copy of AEGIS is from iRO.

For kRO, unarmed, unequipped, buffless ASPD is calculated as
`JobBaseAspd + StatBonus
`
Where JobBaseAspd for a Royal Guard is 156, and StatBonus is
`FLOOR( √(DEX²/5 + AGI²/2) / 4 )
= FLOOR( √(107²/5 + 123²/2) / 4 )
= 24
`
So we get:
`156+24 = 180`

**Comment by Daegaladh** [comment]
The aegis I tested it is from a leak from twRO, and should be closer to kRO.
I think we need to check this directly on kRO.

**Comment by aleos89** [comment]
Base stat on kRO:
![image](https://user-images.githubusercontent.com/3521753/52972722-c0d17780-3389-11e9-92b5-87cbf38f1038.png)
![image](https://user-images.githubusercontent.com/3521753/52973388-f6776000-338b-11e9-9653-900bea10c9ee.png)
I don't have enough stats, but going off what @flamefury stated above:
```
FLOOR( √(DEX²/5 + AGI²/2) / 4 )
= FLOOR( √(100²/5 + 102²/2) / 4 )
= 21

156 + 21 = 177
```
