### ISSUE TITLE
Hair Styling / Styling Shop

### ISSUE THREAD

**Issue by zeffen** [rathena/rathena#3915]
* **rAthena Hash**: 

* **Client Date**: 

* **Server Mode**: Renewal

* **Description of Issue**:  It is lacking in Alberta, Lighthanlzen, Juno/Yuno, Rachel
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment]
Duplicate of #3037
