### ISSUE TITLE
Non-english letters on names

### ISSUE THREAD

**Issue by Daegaladh** [rathena/rathena#3917]
* **rAthena Hash**: 91e3cf73fba90782a151bbe36129556f8041820b

* **Client Date**: 

* **Server Mode**: Both

* **Description of Issue**: 
  * Result: Using non-english letters on names doesn't work anymore.
  * Expected Result: 
  * How to Reproduce: 
Setting `char_name_option: 1` and `char_name_letters: abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890ñÑ-_áéíóúÁÉÍÓÚäëïöüÄËÏÖÜ` on char_athena.conf, and naming a character with one or more of those letters.

I've added debug to check the output of charserv_config.char_config.char_name_letters and the name array in char.cpp.
`charserv_config.char_config.char_name_letters: abcdefghijklmnopqrstuvwxyz ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890├▒├æ-_├í├®├¡├│├║├ü├ë├ì├ô├Ü├ñ├½├»├Â├╝├ä├ï├Å├û├£`

The output on the name array for `ñ` is `±`, while in `char_name_letters` is `├▒`
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by RadianFord** [comment]
https://github.com/rathena/rathena/issues/1953

**Comment by Daegaladh** [comment]
> 
> 
> Similar issues? #1953

No, but might be related

**Comment by Daegaladh** [comment]
It was notepad++ fault, it works fine saving the file as ANSI
