### ISSUE TITLE
getmapxy doesn't work with variable

### ISSUE THREAD

**Issue by teededung** [rathena/rathena#3918]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/26720f041a3cd0edbaa975bfc70345a30e9bf706#diff-72efe615f092af2b8eec7289b4e2f159
* **Client Date**: does not matter
* **Server Mode**: both
* **Description of Issue**: 
  * Result: getmapxy doesn't work with variable
  * Expected Result: getmapxy works with variable
  * How to Reproduce: 
try this script
`
.@name$ = "You";
`
`
getmapxy(.@map$,.@x,.@y,BL_PC,.@name$);
`
You will see error from console `[Error]: buildin_getmapxy: Player with map id '0' is not found.`
Many script files use `getmapxy` with variable like
`npc/re/instances/IsleOfBios.txt`
`npc/re/quests/quests_15_2.txt`
`npc/quests/partyrelay.txt`
`npc/events/halloween_2009.txt`
`npc/custom/quests/hunting_missions.txt`
doesn't work with variable.

**Comment by aleos89** [comment]
This was fixed in 1f97bea.
