### ISSUE TITLE
MER_INVINCIBLEOFF2 skill

### ISSUE THREAD

**Issue by julia40124009** [rathena/rathena#392]
this skill is //

Can support to use this instance (Elemental Summons Skill)  ?
seem need to new sc ?
// https://www.youtube.com/watch?v=OxteKgJdHhs
https://www.youtube.com/watch?v=0croBO719kQ

**Comment by cydh** [comment]
in which part that use `MER_INVINCIBLEOFF2`?

**Comment by julia40124009** [comment]
https://www.youtube.com/watch?v=0croBO719kQ
start 9.28

**Comment by cydh** [comment]
uhh well, I hard to understand. Maybe because don't know when the skill used (even u mention from 9.28)

if according to the skill name, it's toggle to make Mercenary is invincible or not. xD

**Comment by julia40124009** [comment]
I use the movie mercenary skills name , search luafiles514 files(skilldescript.lub), find the corresponding skill english name

can find other country ragnaok look skilldescript.lub (skill descript)  

need to others kro or jro video to prove that
premise kro jro instance process same twro
