### ISSUE TITLE
Client 2019

### ISSUE THREAD

**Issue by zeffen** [rathena/rathena#3925]
* **rAthena Hash**: 

* **Client Date**: 

* **Server Mode**: 

* **Description of Issue**: Excuse me if this is not the correct place for this, but I would ask for compatibility with Client 2019 Ragexe please.
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment]
I would love to say „rejected“. Just for the reactions 😂

**Comment by keitenai** [comment]
2019 renewal client is now available.
http://nemo.herc.ws/downloads/

im lookin forward for 2019-02-13IRagexeRE compatibility on rathena 😄

**Comment by Haikenz** [comment]
rA is only compatible until the version of client **2018-09-19aRagexe** After that date it will give error in the Storage, and if using the **2018-11-xx** will not be able to log in the login screen

**Comment by Balferian** [comment]
Any update?

**Comment by zeffen** [comment]
rA is only compatible until the version of client 2018-11-07aRagexe.

**Comment by tkporreta** [comment]
I would love to be able to help with this update so that I can use the new hexed in rathena, that someone has willing to teach I help quietly.

**Comment by OptimusM** [comment]
would be great to have newer clients on rA, maybe a crowfounding for this? i will surely support.

**Comment by attackjom** [comment]
> would be great to have newer clients on rA, maybe a crowfounding for this? i will surely support.

me too.

**Comment by DepTrai92** [comment]
> > would be great to have newer clients on rA, maybe a crowfounding for this? i will surely support.
> 
> me too.

me three

**Comment by Surefirer** [comment]
Can't wait to see ra support 2019 client. I have seen several private server support 2019 client already. I would love to support if its a crowfounding.

**Comment by Lemongrass3110** [comment]
Fixed in 45cd580
