### ISSUE TITLE
Implementation of LapineDdukDdak System

### ISSUE THREAD

**Issue by Haikenz** [rathena/rathena#3926]
* **Information**: 
Recently Herc has already developed the System Lapine, it would be very good if rAthena had it too.

* **Client Date**: 
2016-03-02 

* **Server Mode**: 
Pre-Renewal ~ Renewal

* **Pull**: 
  https://github.com/HerculesWS/Hercules/pull/2336

**Comment by aleos89** [comment]
Duplicate of #3302.
