### ISSUE TITLE
Rune Knight Skills

### ISSUE THREAD

**Issue by zeffen** [rathena/rathena#3931]
* **rAthena Hash**: 

* **Client Date**: 

* **Server Mode**: 

* **Description of Issue**: Enchant Blade and Sonic Wave have 10 levels, but in rAthena there are 5 levels
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Please check out #3659.
