### ISSUE TITLE
Ice Wall wrong unit duration

### ISSUE THREAD

**Issue by Daegaladh** [rathena/rathena#3934]
* **rAthena Hash**: fc7e46e890b2a7e006ee90d9e53be4732666c26e

* **Client Date**: 

* **Server Mode**: Both

* **Description of Issue**: 
  * Result: Ice Wall units duration and HP are completely wrong, and weirdly coded
  * Expected Result: Match the official behavior
  * How to Reproduce: 
  * Official Information: Ice Wall units duration should decrease 50HP per second, and their HP should be 400HP at level 1, +200 each level.
  

* **Modifications that may affect results**:

**Comment by anacondaqq** [comment]
from where is this source from? What episode? What about 13.2 I remember completely different behavior on official servers. Is it new changes to the emulator? What source?

**Comment by Daegaladh** [comment]
> 
> 
> from where is this source from? What episode? What about 13.2 I remember completely different behavior on official servers. Is it new changes to the emulator? What source?

It's been always the same behavior for both 13.2 and renewal. I noticed this bug years ago and I forgot about it until I found an old report from my server. I tested it on iRO before renewal at that time, and I've just tested it again on aegis 15.2 and euRO.
Also @mrjnumber1 confirmed this.

**Comment by mrjnumber1** [comment]
goodness, i'm glad i was able to help track down an ANCIENT bug.
