### ISSUE TITLE
Quest exp for homuncul

### ISSUE THREAD

**Issue by Balferian** [rathena/rathena#3938]
* **rAthena Hash**: c5a5c54
* **Client Date**: -

* **Server Mode**: Pre/Re

* **Description of Issue**: 
  * Result: now homuncul don`t receive base exp from quests
  * Expected Result: homuncul should receive 10% exp from char when you complete quests (getexp _,_;)
  * How to Reproduce: 
  * Official Information: see my [video from kRo (sakray)](https://www.youtube.com/watch?v=YJF1QpVVqBA&feature=youtu.be) 
  

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment]
Reserve = receive?

**Comment by Balferian** [comment]
> Reserve = receive?

yes >_<

**Comment by aleos89** [comment]
Is this part of #2571? Experience shared has changed: "10% of the experience obtained by the Genetic is given to the homunculus adjusted to its base level.".

**Comment by Balferian** [comment]
> Is this part of #2571? Experience share has changed: "10% of the experience obtained by the Genetic is given to the homunculus adjusted to its base level.".

Yes, it is.

**Comment by aleos89** [comment]
I've already gone ahead and applied the fix in the PR here: https://github.com/rathena/rathena/pull/3284/commits/fc095253e907aa17f73db266223fe77f92ea79b0

I'll close this issue. If you have any other things to report, feel free to reply in #3284.
