### ISSUE TITLE
Need update to support Storage Systems

### ISSUE THREAD

**Issue by ghost** [rathena/rathena#3939]
* **rAthena Hash**: c5a5c545181bcb1dae9b33131acf137f5033a59f
Client Date: 2018-10-02bRagexe to 2018-11-07aRagexe
Mode: Renewal

![snapshot_2019-2-11_15-48-24](https://user-images.githubusercontent.com/45366675/52553969-e9042800-2e17-11e9-80f4-e87dcf25ed80.jpg)

Storage System can't display items but can click only itemtype icon at bottom

**Comment by aleos89** [comment]
We don't support this client as of yet.

**Comment by hunterxjapan** [comment]
Thank for answer aleos89

**Comment by Haikenz** [comment]
Has anyone found a solution yet?

**Comment by lelouch22** [comment]
Maybe we can apply the fix from herc?

https://github.com/HerculesWS/Hercules/commit/3e6199fd739d811fdc15139ce4743fa4596c5473
https://github.com/HerculesWS/Hercules/commit/fbbc7f4dec0c7301a0ee3547675a2fba6c62a34c

**Comment by hunterxjapan** [comment]
I'm testing on Hercules with 2018-11-07aRagexe has this same probleme like rA

**Comment by Lemongrass3110** [comment]
Fixed in 45cd580
