### ISSUE TITLE
TK_RUN has an invalid fixed casting time

### ISSUE THREAD

**Issue by Epoque1** [rathena/rathena#3943]
* **rAthena Hash**: 8e325e411

* **Client Date**: N/A
* **Server Mode**: Renewal
* **Description of Issue**: 

The `skill_cast_db.txt` entry for `TK_RUN` has an invalid fixed casting time:

`411,3000:2500:2000:1500:1000:500:0:0:0:0,300,0,1000,150000,0,3000:2500:2000:1500:1000:500:-1-1-1-1`

I suspect the last values should be:

`411,3000:2500:2000:1500:1000:500:0:0:0:0,300,0,1000,150000,0,3000:2500:2000:1500:1000:500:-1:-1:-1:-1`

* **Modifications that may affect results**:  None

**Comment by Lemongrass3110** [comment]
Are you the real Epoque? :)

**Comment by Epoque1** [comment]
Haha, I am! Unfortunately my usual username was taken on here when it came around to registering so I had to stick a 1 on the end.

**Comment by Lemongrass3110** [comment]
Mind telling us the email of one of your two accounts?
Preferrably the one you use more often. ;-)

https://github.com/rathena/rathena/blob/master/.mailmap#L136

If you dont know, here is how to get your real one hidden(search for "Keep my email address private").
https://help.github.com/articles/about-commit-email-addresses/

This way we can link your old svn commits to your new account. At least in the git repository itself. GitHub does not fully support it yet sadly.

**Comment by Epoque1** [comment]
Sure, I'll fire you a private message across on the forums with my email. Ta!
