### ISSUE TITLE
npc_scriptcont: unexpected state '2' for continue call.

### ISSUE THREAD

**Issue by teededung** [rathena/rathena#3944]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/25aaeec135409c735554f973a5c271c6be5acee6

* **Client Date**: 20180621
* **Server Mode**: Both
* **Description of Issue**: 
  * Result: Error in console, npc_scriptcont: unexpected state '2' for continue call
  * Expected Result: no error
  * How to Reproduce: 
1. Create a new script
`prontera,156,184,4	script	stest	10005,{
	progressbar "FFFFFF",5;
	getitem "Apple",1;
	end;
}`
2. Click to move the character when you see the bar running
3. You see the error in console

Tested in clean rA.

**Comment by cahya1992** [comment]
same issue with this 
https://rathena.org/board/topic/118266-npcscriptcont-unexpected-state-2-for-continue-call/
