### ISSUE TITLE
Getmapxy script errors

### ISSUE THREAD

**Issue by SeravySensei** [rathena/rathena#3947]
* **rAthena Hash**: 

708fbf067
* **Client Date**: 

not relevant
* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result: Map server reports error on poring_war.txt and  Horrortoyfactory.txt on this line :
   getmapxy .@map$,.@x,.@y';'
Furthermore, these warnings appear :
[Warning]: script: buildin_getmapxy: Invalid type 128.
[Debug]: Source (NPC): #poring1 at p_track02 (30,38)
[Warning]: script: buildin_getmapxy: Invalid type 128.
[Debug]: Source (NPC): #lunatic1 at p_track02 (30,36)
[Warning]: script: buildin_getmapxy: Invalid type 128.
[Debug]: Source (NPC): #savagebebe1 at p_track02 (30,34)
[Warning]: script: buildin_getmapxy: Invalid type 128.
[Debug]: Source (NPC): #desertwolf1 at p_track02 (30,32)
[Warning]: script: buildin_getmapxy: Invalid type 128.
[Debug]: Source (NPC): #deviruchi1 at p_track02 (30,30)
[Warning]: script: buildin_getmapxy: Invalid type 128.
[Debug]: Source (NPC): #baphomet1 at p_track02 (30,28)
[Warning]: script: buildin_getmapxy: Invalid type 128.
[Debug]: Source (NPC): Runner No. 1#1 at p_track01 (30,38)
[Warning]: script: buildin_getmapxy: Invalid type 128.
[Debug]: Source (NPC): Runner No. 2#2 at p_track01 (30,36)
[Warning]: script: buildin_getmapxy: Invalid type 128.
[Debug]: Source (NPC): Runner No. 3#3 at p_track01 (30,34)
[Warning]: script: buildin_getmapxy: Invalid type 128.
[Debug]: Source (NPC): Runner No. 4#4 at p_track01 (30,32)
[Warning]: script: buildin_getmapxy: Invalid type 128.
[Debug]: Source (NPC): Runner No. 5#5 at p_track01 (30,30)
[Warning]: script: buildin_getmapxy: Invalid type 128.
[Debug]: Source (NPC): Runner No. 6#6 at p_track01 (30,28)
  * Expected Result:  Map server should start without errors
  * How to Reproduce:  Start map server...
  * Official Information:
  

* **Modifications that may affect results**: 
  
  
Merged newest commits to my files (roughly 1-2 week's worth). I haven't changed those scripts or getmapxy so problem should be coming from the merge, I don't think anything on my side should be affecting it.

**Comment by secretdataz** [comment]
Looks like you pulled the changes without recompiling.

**Comment by SeravySensei** [comment]
Indeed, sorry about that.
