### ISSUE TITLE
bonus2 bMagicAddEle dont work

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#3948]
* **rAthena Hash**: 
https://github.com/rathena/rathena/commit/47866f60652d745e57cf3adca68b8dfc59aecc69

* **Client Date**: 
20180620

* **Server Mode**: 
RE

* **Description of Issue**: 
  * Result: 
Bonus2 (bMagicAddEle) is not working. The magical damage of the item is not increasing.
  * Expected Result: 
  * How to Reproduce: 

Take for example a Warlock and use the water element skill.
Use this script to test:
```
27362,Contaminated Spider Queen Card,Contaminated Spider Queen Card,6,20,,10,,,,,,,,4,,,,,{ bonus2 bSubEle,Ele_All,-30; bonus2 bMagicAddEle,Ele_Earth,100; bonus2 bMagicAddEle,Ele_Water,100; },{},{}
```
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Atemo** [comment]
You're confusing 
```
bonus2 bMagicAddEle,e,x;  		+x% magical damage against element e
```
vs
```
bonus2 bMagicAtkEle,e,x;  		Increases damage of e element magic by x%
```
`bMagicAddEle` increase the damage vs e element monsters.
`bMagicAtkEle` increase the damage of your e element spells.

**Comment by Badarosk0** [comment]
Sorry for the inconvenience and shame.
@Atemo

**Comment by Atemo** [comment]
No problem, everyone can make mistakes ;)
