### ISSUE TITLE
Incomplete Item Script

### ISSUE THREAD

**Issue by JohnnyPlayy** [rathena/rathena#3949]
- According to Divine-Pride this item is wrong [585](https://www.divine-pride.net/database/item/585)

- Correct would be

 `585,Wurst,Brusti,11,1,,40,,,,,0xFFFFFFFF,63,2,,,,,,{ itemheal rand(15,20),0; itemskill "PR_MAGNIFICAT",3; },{},{}`

**Comment by secretdataz** [comment]
Confirmed in both pre-renewal and renewal leaks.

**Comment by aleos89** [comment]
Fixed in 214573e.
