### ISSUE TITLE
Card Effect wont Work Correctly Like Turtle general or Abyssmal Knight Card

### ISSUE THREAD

**Issue by Zarbony** [rathena/rathena#3955]
* **rAthena Hash**:  1e8a17d

* **Client Date**:  2018-06-22

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result:  The Issue is that Effects Like Abyssmal Knight Card and other ones dont work. They wont Higher the DMG.
Please Excuse my bad English.
  * Expected Result:  Working Effects like class MvP
  * How to Reproduce:  Since the last pull Request these one wont Work, i just wrote in Germany my Test Result:

- Turtle General add +20% more ATK on AnySize
- Mine Jobclass: Mechanic+
- Level 300 | 61
- Damage without Cards but with Weapon: +20 Mjolnir with ~9,6k dmg without any card
- Mine ATK Stats are at 2128 + 2156 (= 4284)
-In Case of that every Turtle General(TG) Card Should add 856,8 Atk

That Sounds like every  card should Higher my DMG with ~1,92k.

These seems like that:
9,6k + 1,92 +1,92 +1,92 +1,92 = 17,28k 

or in ATK:
4284 +856,8 +856,8 +856,8 + 856,8 = 7711,2

Without Mjolnir or any other Weapon:  5,9k
With Mjolnir but without Cards: 9,6 ~ 9,9k
OneTG Card in Mjolnir: 10,2 ~ 10,8k 
Two TG Cards in Mjolnir:  11,1 ~ 11,5k
Three TG Cards in Mjolnir: 11,9 ~ 12,4k
Four TG Cards in Mjolnir: 12,9 ~ 13,4k

that seems like every Card gives an DMG between 750 ~ 825.
That is Only 6% and 10%.
But with the Effect of the Card, the Value has to be way more Higher.
i Think it Should be doubled.

Then i tested other Cards and my Result is scary:
Not Only the TG Card wont work Correctly, this one is at other cards like Abyssmal Knight aswell, but Abyss wont Higher ANY Dmg, its still the same as i dont use any card.
tested at Atroce, Tao Gunka, Time Holder and an Custom Test Dummy with MVP Flag, Size Large, Race Dragon and Ele Neutral level 1.
if i give the card bonus bAtkRate,20;
The effect work, but with AnySize it wont work correctly and other Effects that Higher Monster Related Damage like Elemental oder Flag like MVP and so on.

  * Official Information: /
  

* **Modifications that may affect results**: 
  
  Nothing whish will Effect this one. Just parse some other Pull Requests but this work in past well.

**Comment by secretdataz** [comment]
![image](https://user-images.githubusercontent.com/2021243/53786746-32dfba00-3f4f-11e9-8de0-bbc68af26e7b.png)
![image](https://user-images.githubusercontent.com/2021243/53786802-63bfef00-3f4f-11e9-8cbe-09fe52b3f4ca.png)
As I just tested, TG increases slightly more damage than The Paper on crit GX with Maximize Power to minimize damage swing, as indicated in the chat. This matches the [test done on tRO in 2013](https://youtu.be/uMfeSq5LgUs).

**Comment by Zarbony** [comment]
But the class_boss wont Work If i want to use it as Bonus2 bAddclass,Class_boss,25; but subclass wont Work too. Thats why abyssmal Knight ans byellungum wont Work and now i need an solution

**Comment by aleos89** [comment]
As @secretdataz showed in his screen shots on rAthena and his video, the bAddClass bonus is only applied to weapon attack and not status attack. So taking your final damage output and trying to calculate the bonus is wrong. You should be calculating it based of the left hand side of your ATK in the status window.
