### ISSUE TITLE
How can I edit skill 1st/2nd/Transcendent skill

### ISSUE THREAD

**Issue by ikarngraphic** [rathena/rathena#3965]
* **rAthena Hash**: 39033

* **Client Date**: 2018

* **Server Mode**: RENEWAL

* **Description of Issue**: 
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**: 
  
  

I'm Beginner i want to know.
how to edit skill : https://www.divine-pride.net/forum/index.php?/topic/3453-kro-mass-skills-balance-1st-2nd-and-transcendent-classes-skills/

**Comment by aleos89** [comment]
Please ask these types of support questions on the forum.
