### ISSUE TITLE
Events get duplicated

### ISSUE THREAD

**Issue by sader1992** [rathena/rathena#3976]
* **rAthena Hash**: the same issue tested from fc7e46e89 to ec6c36983c5f050f0655565cf0df8e813e5155a6
ofc i don't know when this started
and not sure if it's intended or not

* **Client Date**: 2018

* **Server Mode**: renewal

* **Description of Issue**: 
  * Result: when duplicating npc , the event get duplicated too (tested only on `OnPCKillEvent` and `OnPCDieEvent`
  * Expected Result: some events should not be duplicated or even the duplicated npc should only redirect to the original npc ? not sure how it work in rAthena
  * How to Reproduce: 
```cs
-	script	test_event	-1,{
OnPCKillEvent:
	debugmes "kill: " + ++k;
end;
OnPCDieEvent:
	debugmes "die: " + ++d;
end;
}
prontera	mapflag	pvp

prontera,1,1,4	duplicate(test_event)	test_event#1	-1
prontera,1,1,4	duplicate(test_event)	test_event#2	-1
prontera,1,1,4	duplicate(test_event)	test_event#3	-1
prontera,1,1,4	duplicate(test_event)	test_event#4	-1
prontera,1,1,4	duplicate(test_event)	test_event#5	-1
prontera,1,1,4	duplicate(test_event)	test_event#6	-1
prontera,1,1,4	duplicate(test_event)	test_event#7	-1
prontera,1,1,4	duplicate(test_event)	test_event#8	-1
prontera,1,1,4	duplicate(test_event)	test_event#9	-1
```
this the result
![image](https://user-images.githubusercontent.com/5981261/53294724-03190f80-37f5-11e9-997b-2016a4d9d594.png)

* **Modifications that may affect results**: 
  non i am aware of , no src edit

**Comment by Atemo** [comment]
It has always been like that as far as I remember.

**Comment by secretdataz** [comment]
This is an intended behavior. A major example is the agit_main.txt script which extensively utilize the duplication issue of events.
