### ISSUE TITLE
error job system please check.

### ISSUE THREAD

**Issue by hnomkeng** [rathena/rathena#398]
no job and skill, will have novice job only.

version 13094.

**Comment by lelouch22** [comment]
Yup same here this only occur when i updated my trunk to the latest github version.

Example: @job 4060 = Novice

**Comment by hnomkeng** [comment]
I can not change jobs and up skill.

**Comment by lelouch22** [comment]
i guess this is related to this commit
https://github.com/rathena/rathena/commit/177ea6c779579dff146d5e21f6dcffe17fe3ae9f

**Comment by hnomkeng** [comment]
Thank you, Tomorrow is check again.

**Comment by lelouch22** [comment]
I hope this will be fixed soon becuase of this issue our server is currently down -_-. Ciao :P

**Comment by Desground** [comment]
confirm. Jobs and skills do not work.

**Comment by aleos89** [comment]
Should be resolved in 2fdcd92.

**Comment by lelouch22** [comment]
Yup its fixed :P, Thanks Aleos :3
