### ISSUE TITLE
Event on timeout

### ISSUE THREAD

**Issue by Atemo** [rathena/rathena#3982]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/757a4593201195a91440b83a9fe6dafa89e22cb8

* **Client Date**: -

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: The system doesn't run the next event when a dialog is timeout.
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: No idea how they handle this on official.
  

* **Modifications that may affect results**: 
  
  

## Test script
```
izlude,100,100,1	script	test	55,{
	addtimer 2000, strnpcinfo(3) + "::OnEvent";
	mes "Wait for the timeout.";
	next;
	mes "You didn't wait.";
	close;
OnEvent:
	dispbottom "The event is running.";
	end;
}
```
Click on the npc and press close after the timeout, `OnEvent` is still on queue and will run later.

**Comment by Lemongrass3110** [comment]
Reading the documentation:
```
*addtimer <ticks>,"NPC::OnLabel";
*deltimer "NPC::OnLabel";
*addtimercount <ticks>,"NPC::OnLabel";

These commands will create, destroy, and delay a countdown timer - 'addtimer' to
create, 'deltimer' to destroy and 'addtimercount' to delay it by the specified
number of ticks. For all three cases, the event label given is the identifier of
that timer. The timer runs on the character object that is attached to the script,
and can have multiple instances. When the label is run, it is run as if the player that
the timer runs on has clicked the NPC.

When this timer runs out, a new execution thread will start in the specified NPC
object at the specified label.

The ticks are given in 1/1000ths of a second.

One more thing. These timers are stored as part of player data. If the player
logs out, all of these get immediately deleted, without executing the script.
If this behavior is undesirable, use some other timer mechanism (like 'sleep').

Example:
<NPC Header> {
	dispbottom "Starting a 5 second timer...";
	addtimer 5000, strnpcinfo(3) + "::On5secs";
	end;
On5secs:
	dispbottom "5 seconds have passed!";
	end;
}
```

I kind of think that this is the intended behavior. Because in your fix you detach the player before running the timer event. Which is not the way these commands are described right now.

Possible solutions from my side:
1. Create a OnSecureTimeout Event
1. Add a additional flag to addtimer, if you want to trigger your new behavior or not.

In any case the documentation needs an update.

**Comment by Atemo** [comment]
I'm closing this, as you mentionned the 'issue' can be handled by `ignoretimeout` command
```
*ignoretimeout <flag>{,<char_id>};

Disables the SECURE_NPCTIMEOUT function on the character invoking the script,
or by the given character ID/character name.

Valid flag:
 0 - Enabled SECURE_NPCTIMEOUT.
 1 - Disable SECURE_NPCTIMEOUT.

Note: SECURE_NPCTIMEOUT must be enabled for this to work.
```
Sorry for the inconvenience.
