### ISSUE TITLE
Intel Compiler C++

### ISSUE THREAD

**Issue by Alpha018** [rathena/rathena#3998]
just out of curiosity, it is possible to compile the files with the ICC (intel compiler C++), would it help at all? Is it possible?

**Comment by anacondaqq** [comment]
Please use [https://rathena.org/board/](https://rathena.org/board) for such questions.

**Comment by Lemongrass3110** [comment]
It is probably supported from compiler version 15 and above. But as @anacondaqq said please use the forum for questions and not the issue ticker.
