### ISSUE TITLE
Not aggressive familiar

### ISSUE THREAD

**Issue by Desground** [rathena/rathena#400]
http://db.irowiki.org/db/monster-info/1005/
tested only on renewal
 rathena/db/re/mob_db.txt
1005,FARMILIAR,Familiar,Familiar,24,427,1,144,162,1,68,77,26,5,15,19,20,5,20,1,10,12,0,2,27,0x3881,150,1276,576,384,0,0,0,0,0,0,0,913,5500,1105,20,2209,15,601,50,514,100,507,700,645,50,0,0,0,0,4
020,1
Git Hash: '2fdcd9233640eaebb350eee0cb706b08d21842f6'

**Comment by reigneil** [comment]
it is working as intended. renewal mode change this to passive check it out heres the topic: http://forums.irowiki.org/showthread.php?t=90980&highlight=Familiar
