### ISSUE TITLE
Cannot Build, vs2017

### ISSUE THREAD

**Issue by Laicure** [rathena/rathena#4001]
What am I missing? Please help and thanks in advance! :D

* **rAthena Hash**: 
f5e8af0d9

* **Client Date**: 
none

* **Server Mode**: 
none

* **Description of Issue**: 
  * Result: compilation errors
  * Expected Result: successful build
  * How to Reproduce: rebuild with the hash above using vs2017Pro (edition doesn't matter)
  * Official Information: none
  

* **Modifications that may affect results**: 
none

  
  

Screenshot:
![image](https://user-images.githubusercontent.com/8619566/53790537-2153dd80-3f62-11e9-96f1-9f77286c9bf7.png)

**Comment by vstumpf** [comment]
Your CRT is not set up correctly:
https://stackoverflow.com/a/43905001/8390887

You might need to retarget the projects to version of the CRT you have.

**Comment by Laicure** [comment]
Thanks! I'll be checking those.
I thought that I can build without doing anything like from VS2013 :D
