### ISSUE TITLE
Iterator Security Check Debug Mode

### ISSUE THREAD

**Issue by teerawutdir** [rathena/rathena#4004]
strcut with the constructor class needs to use new instead of CREATE, such as vector

example:
struct map_session_data {
	std::vector<data> list;
}

map_sesion_data need to use new instead of CREATE because the vector constructor doesn't work, which will cause many problems later
such as

it = list.begin();
data = *it  // mycount within vector is nullptr

sorry, i'm not good english.

**Comment by Lemongrass3110** [comment]
Please follow the issue template.

Depending on the hash on we might have disabled iterator security already for the time being. This is a known issue and we are trying to replace more and more from the old memory manager with C++ features.

**Comment by Lemongrass3110** [comment]
No further input since March.
