### ISSUE TITLE
Pet Evolution. 

### ISSUE THREAD

**Issue by AlternisRhodes** [rathena/rathena#4005]
* **rAthena Hash**: 
202e5c4

* **Client Date**: 
2018-06-20

* **Server Mode**: 
Renewal.

* **Description of Issue**: 
  * Result: 
I can not evolve the pet.
  * Expected Result: 
  * How to Reproduce: 
I downloaded the pet evolution feature in zip without changing anything, I compiled it and the problem continues.
  * Official Information:
  
* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment]
As you might have noticed #3544 is still in progress.
@aleos89 reopened it for commenting again.
