### ISSUE TITLE
Bonus ATK stack and overwrite with Bonus atk from refine weapon

### ISSUE THREAD

**Issue by cahya1992** [rathena/rathena#4007]
* **rAthena Hash**: 

757a45932

* **Client Date**: 
20180621

* **Server Mode**: 
RE

* **Description of Issue**: 
  * Result: 
Bonus ATK not affect
  * Expected Result: 
Should Increase
  * How to Reproduce: 
Try to create Some Headgear which is have Bonus ATK Ex: 18980
And Create 2 rod
1 have refine weapon
1 without refine weapon
try to refine this item 18980 to +10
If use Old Wind Whisper(18980)+10 without weapon or with weapon no refine is work perfeclty get bonus atk +40
see this SS below : 
http://prntscr.com/mwkczq
http://prntscr.com/mwkdfn
If i try to refine rod to +4 Above bonus atk from HG didn't working
See this SS Below:
http://prntscr.com/mwkdzq
See this if use HG and weapon refine+4
http://prntscr.com/mwke44
Only increase affect from alltstat+1 and increase 1 atk ist, should have bonus atk 25+41(From HG)
Or You can see my video 
  * Official Information:
  

* **Modifications that may affect results**: 
  
  
No custom

See this Video :
https://youtu.be/i3eToJiheY4

**Comment by SeravySensei** [comment]
I tried equipping a Novice Poring carded Criatura Hat (+5 atk together) and a +5 Staff and it worked.
I do have https://github.com/rathena/rathena/pull/3968/files implemented, which might make a difference but probably not.
Most importantly, that item has script bonus bAtk2 while other atk increasing items have bonus bBaseAtk instead. I'm not entirely sure what bonus bATk2 is even supposed to do, which of these is it supposed to increase : https://irowiki.org/wiki/ATK ? I suspect neither, it's probably an obsolete script only applicable to prerenewal mechanics which actually has atk and atk2 stats. If that's true, this is an item script bug and renewal items should not use batk2, ever.

**Comment by luan122** [comment]
@cahya1992 do you have the Refine UI from @cydh in your src?

**Comment by cahya1992** [comment]
> I tried equipping a Novice Poring carded Criatura Hat (+5 atk together) and a +5 Staff and it worked.
> I do have https://github.com/rathena/rathena/pull/3968/files implemented, which might make a difference but probably not.
> Most importantly, that item has script bonus bAtk2 while other atk increasing items have bonus bBaseAtk instead. I'm not entirely sure what bonus bATk2 is even supposed to do, which of these is it supposed to increase : https://irowiki.org/wiki/ATK ? I suspect neither, it's probably an obsolete script only applicable to prerenewal mechanics which actually has atk and atk2 stats. If that's true, this is an item script bug and renewal items should not use batk2, ever.

try to use headgear with script Bonus bAtk2. for card its working but if the script in Headgear item not working :(
or you can try what item i use on video..
try reproduce same ways what i give example video :D



> @cahya1992 do you have the Refine UI from @cydh in your src?

I don't

**Comment by cydh** [comment]
tested and seems confirmed

**Comment by cahya1992** [comment]
any news about this?
