### ISSUE TITLE
Kunai Splash and Swirling Petal

### ISSUE THREAD

**Issue by pajoder** [rathena/rathena#401]
I saw several videos of jro and note that the delay of kunai splash and swirling petal is based on aspd.
Also, the damage of kunai splash is slightly lower on rathena.

Excuse my English!

**Comment by Barigas** [comment]
Wrong. Swirling Petal on officials has 3 seconds re-use delay and 0 seconds aftercast. Kunai Splash has only 0.5 seconds aftercast delay.

**Comment by cydh** [comment]
can I close this issue? I sense no accuracy at all.

the delays are fine, **'lower'** is perfectly 'gray' word for me.
