### ISSUE TITLE
Achievement target crash

### ISSUE THREAD

**Issue by Atemo** [rathena/rathena#4015]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/46d04269fde020362577e2409aa91f571724e972

* **Client Date**: 

* **Server Mode**: pre-renewal

* **Description of Issue**: 
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
Summon and kill a poring in pre-renewal mode, mapserv crash.
https://github.com/rathena/rathena/blob/46d04269fde020362577e2409aa91f571724e972/db/pre-re/achievement_db.yml#L2454
nullptr
https://github.com/rathena/rathena/blob/46d04269fde020362577e2409aa91f571724e972/src/map/achievement.cpp#L897

  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Haikenz** [comment]
I had shown this to @Lemongrass3110, even on video call, reporting on that error.

**Comment by teededung** [comment]
#4006

**Comment by Haikenz** [comment]
Not work, In my already have this and still crash, I tried to use a clean emulator (Pre-Renewal) and give the same error.

**Comment by Stingor** [comment]
i had the issue, in achievement_db, seek "Exploring Poring's life (1)", then uncomment the id 1 achiev, because it create a null between id:0 and id:2

**Comment by CairoLee** [comment]
i have same issue
