### ISSUE TITLE
HP/SP Table Warnings @ b7431ef

### ISSUE THREAD

**Issue by cydh** [rathena/rathena#402]
:stuck_out_tongue: 
just forward from @reigneil https://github.com/rathena/rathena/commit/b7431efa03cd6d735956320f20582df120ba3952#commitcomment-10792952

>i do have warnings on re/job_basehpsp_db.txt gunslingers HP and Novices SP i think there is typo here. would you double check it... thanks

````
[Warning]: pc_readdb_job_basehpsp: HP value at line 33 col 98 is lower than previous level (job=24,lvl=95,oldval=3834,val=3806).
[Warning]: pc_readdb_job_basehpsp: HP value at line 33 col 98 is lower than previous level (job=4215,lvl=95,oldval=3834,val=3806).
[Warning]: pc_readdb_job_basehpsp: SP value at line 41 col 103 is lower than previous level (job=4190,lvl=100,oldval=109,val=100).
[Warning]: pc_readdb_job_basehpsp: SP value at line 41 col 103 is lower than previous level (job=4191,lvl=100,oldval=109,val=100).
````

**Comment by Playtester** [comment]
Well the values are official, but I guess I should remove that warning?

**Comment by cydh** [comment]
I was suspecting Gunslinger/Rebellion HP must be same with Star Gladiator (3834 > 3734).
And those Super Novices SP, lv 99 is 109, lv 100 is 100. Looks ridiculous.

imho, change that HP for Gunslinger/Rebellion, keep the Super Novice SP like that, commenting the warning lines.
If u say "but the values are official", yes they're, but it is __old__ Aegis version

**Comment by Playtester** [comment]
Well can you link me to a changelog that says that the Gunslinger HP values were corrected?

Naturally it makes more sense if it doesn't decrease and the gunslinger HP is most likely an "official typo", but we want to emulate officials by default, don't we?

I have no problem fixing it, though.
