### ISSUE TITLE
bonus3 bSubEle and bonus3 bAddEle's flag is overwritting

### ISSUE THREAD

**Issue by cydh** [rathena/rathena#4026]
* **rAthena Hash**: d1b35db768469b8db2d1cd46a1cb4ab94e7c8a56

* **Client Date**: -

* **Server Mode**: Both

* **Description of Issue**: 
  * Result: If 2 or more items with `bonus3 bSubEle,e,x,bf;` and the flag is differrent, the first loaded bonus will be overwritten by the next loaded bonus. Not literally overwriten, just the first loaded bonus will be taken by the next loaded bonus with different flag as long as the element is same. Also same with `bonus3 bAddEle,e,x,bf;`
  * Expected Result: Asprika's bonus shouldn't be overwritten
  * How to Reproduce:
    * Prepare Asprika `2541` for BF_MAGIC, and Shaman Hat `5841` for BF_SHORT
    * Asprika's bonus will be loaded first to reduce melee (elemental) damage, then after Shaman Hat's bonus that reduce magic damage by element will 'takes' the reduction from Asprika while Asprika 'loses' the bonus
    * or simply make custom scrpit as and you will get as like `bonus3 bSubEle,Ele_Water,100,BF_MAGIC;`
```
2541,Asprika,Asprika,4,20,,400,,40,,0,0xFFFFFFFF,63,2,4,,94,0,0,{ bonus3 bSubEle,Ele_Neutral,50,BF_SHORT; bonus3 bSubEle,Ele_Water,50,BF_SHORT;  },{},{}
5841,Shaman_Hat_,Shaman Hat,4,20,,100,,1,,1,0xFFFFFFFF,63,2,256,,30,1,596,{ bonus3 bSubEle,Ele_Water,50,BF_MAGIC; },{},{}
```
  * Official Information: -

* **Modifications that may affect results**: -

No Ragexe client test

![image](https://user-images.githubusercontent.com/4016864/54662751-a23dd800-4b11-11e9-98ad-64e76e47423e.png)

**Comment by keitenai** [comment]
lol openkore? =D
