### ISSUE TITLE
wrong item script for item id 24115~24149

### ISSUE THREAD

**Issue by reigneil** [rathena/rathena#403]
it is supposed to increase your SP consumption not decrease and also about the every refinement of item 24138~24143 i think it must be teleport not cloaking.

**Comment by nanakiwurtz** [comment]
Hmm.. I think there's something weird with this 'Grid Combo Set', it's so unlikely that every shadow items grants the same skill.
And on the description: "Each refine decrease SP consumption of skill by 10", which skill? All skills or only the Greed? :full_moon_with_face:

This Grid Combo Set consists of 6 items, if all equipment are refined to +20, then the total will be 120 refinement.
Do you think it's normal to decrease SP consumption of (all/Greed) skill by 1200 points? :hatching_chick:

I still have no clue about this one actually...
:banana:

**Comment by reigneil** [comment]
i think the script is fine what you should do here is insert negative value like this... -100+(getrefine()*10)

**Comment by reigneil** [comment]
btw here's the topic about it http://forums.irowiki.org/showthread.php?p=1386662&highlight=consumption#post1386662 there is info that you cannot refine shadow equipment beyond +10
