### ISSUE TITLE
failure of  0a98 ,0a9a  isn't bool value ?

### ISSUE THREAD

**Issue by sctnightcore** [rathena/rathena#4031]
* **rAthena Hash**:  i dont have it .

* **Client Date**:  iRO / kRO 

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**: 
  
  

I have check from iRO and kRO 

```
0 = success
1 = fail
2 = item level is too high /  item of human != doram / item of doram != human
```
iRO /if i use doram item ./
![image](https://user-images.githubusercontent.com/23263315/54862329-df9da200-4d6b-11e9-91f7-eba571a52013.png)

kRO 
https://github.com/sctnightcore/Ragnarok_system_in_openkore_by_me/blob/master/eq_sw/packet.txt#L17-L20

**btw, I'm not good  English. I hope you understand**

**Comment by mrjnumber1** [comment]
Well, you didn't follow the report template (as expected), but the information required is mostly there. 

pc_isequip will need to return `ITEM_EQUIP_ACK_FAILLEVEL` in such cases. I'm not sure there are any items that are Human only, but I haven't kept up. should be a quick PR.
