### ISSUE TITLE
lucky roulette coin issue

### ISSUE THREAD

**Issue by daisyanne1380** [rathena/rathena#4033]
* **rAthena Hash**: 
im using desktop github not sure how to get this. but its a clean rathena from 3 weeks ago. ill ask my friend to help me get the hash when i see him

* **Client Date**: 
2018-06-20e

* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result: When using bronze coins and you dont select "Get  Prize" and continue with "START" it goes further than the 2 rows. I t can go all the way to the top row if you decline the selection and keep selecting "START".

  * Expected Result: Bronze coin unlocks only the first 2 rows, silver unlocks row 3/4/5 and gold unlocks final 2.

  * How to Reproduce:  
I notice if you play the game 1 time it work if you continue to play then it glitches and will result in the above issue.
At the time i has 20 bronze and 20 silver coins and 4 gold.
and the game was taking 1 bronze coin only per game even if it went up to the last row.

  * Official Information:I dont have official info beside whats posted in rathena on how it suppose to work

* **Modifications that may affect results**: 
  Havent made any modifications

Please note i did use search and saw 1 closed topic about bugged coins but it was slightly different and was closed 2 years ago.

**Comment by aleos89** [comment]
https://youtu.be/H7IDWEXNRgM?t=149

Ziu's video shows how we have it implemented (how you explained it). He used a Bronze point and went up through the ranks with no other points. My interpretation is that the other point types (Silver/Gold) lets you skip the lower levels.

**Comment by daisyanne1380** [comment]
that implementation is different from the one i read BUT  in this implementation they use a jellopy as a lose and stop to the game. in the one i tried it has a coin and it doesnt stop the game the second time around.

**Comment by Lemongrass3110** [comment]
Since this feature has been removed we need good reliable sources if you question the current behavior.

**Comment by daisyanne1380** [comment]
i guess there really isnt much to go on, but its kinda odd that silver and gold require 10 just for one round when bronze can easily take you up. unless the chance to lose is higher with bronze.  But i just tried to look for information and your right there isnt much to go by. thanks

**Comment by aleos89** [comment]
That's because kRO updated the items later on. Here's another video from Ziu: https://www.youtube.com/watch?v=u-_45Addgh0
