### ISSUE TITLE
Several atcommands uses atoi on itemdb_exists which accepts unsigned short

### ISSUE THREAD

**Issue by secretdataz** [rathena/rathena#4035]
* **rAthena Hash**: 972a14e
* **Client Date**: Irrelevant
* **Server Mode**: Irrelevant
* **Description of Issue**: 
  * Result: For example, using `@item 70000` will results in the user getting an Aunoe Card (4464) which resulted from the unsigned short overflowing. There are also other occurrences of `itemdb_exists(atoi(someint))` in atcommand.cpp.
  * Expected Result: We should discuss the desired behavior here.
  * How to Reproduce: Use `@item 70000`. You'll get an Aunoe Card (4464).
* **Modifications that may affect results**: None

**Comment by aleos89** [comment]
Related to #1609. But in these cases might be best to `stroul`.

**Comment by aleos89** [comment]
Being fixed in #5141.
