### ISSUE TITLE
wrong item script for item id 4442~4449

### ISSUE THREAD

**Issue by reigneil** [rathena/rathena#404]
i think this cards must act like racial card., instead of race, the element of monster is considered. it seem that it is not yet implemented here.

**Comment by nanakiwurtz** [comment]
> @reigneil said:
> i think this cards must act like racial card

Well, there's no RC_Neutral, so it must be Ele_Neutral
So I guess current codes are correct, what do you think?

**Comment by reigneil** [comment]
what the current script do is reduce damage only for the property of attack i.e Ele_Neutral like Asura Strike and not reduce damage from the attribute of the monster so if the attribute of the monster is a water property and i use Aqua Elemental Card all of his attack must be reduce even if he uses Ele_Neutral or Ele_Fire attack. see this chart about defense element https://github.com/rathena/rathena/blob/master/db/re/attr_fix.txt and how player change their element to water attribute using Swordfish Card.

**Comment by nanakiwurtz** [comment]
Ohh.. now I get your point... :thought_balloon:

**Comment by cydh** [comment]
they're working like that. "Reduce damage from x element and add damage to x element"
if u got attacked from skill with x element and it's reduced. so it's the advantage. but when user change the element to attack, that means the user beats u in tactic /gg

**Comment by reigneil** [comment]
@cydh why did you closed this issue? it is obvious that we emulate this differently... if we look at the data from aegis they are different. what we use here are add/sub ATTR_TOLERACE_X in aegis server we see add/sub DAMAGE_PROPERTY_X_USER and DAMAGE_PROPERTY_X_TARGET where X is the attribute

**Comment by reigneil** [comment]
@cydh yet another written statement shows that this is different from the typical element tolerance http://irowiki.org/wiki/Card_Reference "The following shield cards reduce received damage by 20% based on the enemy's element and increase inflicted damage against enemies of the same respective element by 5%. Please note that these cards do NOT reduce a certain element; they reduce damage based on what element the MONSTER is."

**Comment by Playtester** [comment]
I'll reopen this as I can confirm it. It depends on the element of the monster and doesn't work on players at all. Unlike out "SubEle" bonus, it does NOT refer to the element of the skill used. We have no such bonus as of now.

**Comment by cydh** [comment]
oh now I got ur point.. hmm

**Comment by cydh** [comment]
I can add `bonus2 bSubDefEle,e,n;`

and, any bonus that for 'adding +n or +n% damage of e attack/skill'?
Like Volcano, Deluge, Water Violent Gale, Telekinesis Intense.
