### ISSUE TITLE
token of Siegfried not working. Roulette version.

### ISSUE THREAD

**Issue by daisyanne1380** [rathena/rathena#4041]
* **rAthena Hash**: 

* **Client Date**: 
2018-06-20e

* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result: 
i get the resurrect menu but when i click on it, it does nothing. I'm using client 2018-0620e.  I didn't diff skip resurrect button either. And im using a svn from about 2 weeks ago so fairly new.

  * Expected Result:
to revive.

  * How to Reproduce:  
Ok i figured out whats wrong, svn is set to revive if you have token of Siegfried id 7621 But roulette give you a non trade-able version id 6316. I think both id should be added to the src.

  * Official Information:

* **Modifications that may affect results**: 
  Havent made any modifications

**Comment by Normynator** [comment]
Solved: https://rathena.org/board/topic/118604-is-token-of-siegfried-not-working/

**Comment by daisyanne1380** [comment]
hello, i apply this fix and now it does work BUT i notice that it doesn't take the token away from you when you revive. thanks

**Comment by daisyanne1380** [comment]
hello did anyone else verify that the item isnt removed from inventory upon death and revival

**Comment by aleos89** [comment]
I was unable to reproduce your issue. Make sure you pulled the latest version from the PR.

**Comment by daisyanne1380** [comment]
yea thats odd it does work but doesn't delete the token for me upon use.
