### ISSUE TITLE
status_get_sc_def rate drop below 0

### ISSUE THREAD

**Issue by Litro** [rathena/rathena#4046]
* **rAthena Hash**: fded1aa114e5cb0e321d4ace4a374440bcb07122

* **Client Date**: any

* **Server Mode**: any

* **Description of Issue**: 
  `t_tick status_get_sc_def(struct block_list *src,struct block_list *bl, enum sc_type type, int rate, t_tick tick, unsigned char flag);`
is rate supposed to or there is a need to drop below 0, when src base level is lower than bl the rate drop below 0

* **Modifications that may affect results**: 
  
  
- Max Level 250
- Edited sc_def for SC_STUN to vit * 50 (need 200 vit to become imune)
- attacker level 99
- target level 250, vit 250

**Comment by aleos89** [comment]
Can you provide a little more information? Most notably your hash.

The `rate` value is an int, so it can go reach negative values programmatically. All documentation states is it's a range of `0~10000`. We could add some capping checks so it stays between this range as we don't care about anything beyond it.

**Comment by Litro** [comment]
updated the issue info, in my case it was happen around here, notably in reduction from sc_def2
```
	if (!(flag&SCSTART_NORATEDEF)) {
		rate -= rate*sc_def/10000;
		rate -= sc_def2;**
		// Minimum chances
		switch (type) {
			case SC_BITE:
				rate = max(rate, 5000); // Minimum of 50%
				break;
		}
		// Item resistance (only applies to rate%)
		if (sd) {
			for (const auto &it : sd->reseff) {
				if (it.id == type)
					rate -= rate * it.val / 10000;
			}
			if (sd->sc.data[SC_COMMONSC_RESIST] && SC_COMMON_MIN <= type && type <= SC_COMMON_MAX)
				rate -= rate*sd->sc.data[SC_COMMONSC_RESIST]->val1/100;
		}
		// Aegis accuracy
		if(rate > 0 && rate%10 != 0) rate += (10 - rate%10);
	}
	if (!(rnd()%10000 < rate))
		return 0;
```
