### ISSUE TITLE
About SC_ENERVATION SC_GROOMY

### ISSUE THREAD

**Issue by whupdo** [rathena/rathena#4049]
SC_ENERVATION:
SC_GROOMY:
SC_LAZINESS:
SC_UNLUCKY:
SC_WEAKNESS:
SC_IGNORANCE:

Using these skills, how to modify it, if the use fails, will not fall into 2 seconds of cooling time?

**Comment by secretdataz** [comment]
Please use the forum for non-bug reports or non-feature suggestions
