### ISSUE TITLE
rAthena vs Hercules @warp, @go and warp portal character position

### ISSUE THREAD

**Issue by lelouch22** [rathena/rathena#4058]
* **rAthena Hash**: 06c8e0b

* **Client Date**: 2018-06-21aRagexeRE

* **Server Mode**: Pre-Renewal

* **Description of Issue**: In rAthena everytime you use warp, go and warp portal the character will always face in the north meanwhile in Hercules when you use warp or go the character will face on the same position when you used that command and using warp portal always follow when the character position if he/she enters on south the character will be facing on the south same goes in north, east and west position.
  * Result: 

rAthena: using warp and go command.
![screenYourRO004](https://user-images.githubusercontent.com/4976551/55168307-91deca80-51ad-11e9-9b28-3621068bb338.jpg)
![screenYourRO005](https://user-images.githubusercontent.com/4976551/55168320-94d9bb00-51ad-11e9-83a0-ebe354453027.jpg)

Hercules: using warp and go command.
![screenHercules015](https://user-images.githubusercontent.com/4976551/55168921-c30bca80-51ae-11e9-8039-510d4f6aeab3.jpg)
![screenHercules016](https://user-images.githubusercontent.com/4976551/55169036-fb130d80-51ae-11e9-8d8f-e91c036d22ea.jpg)

rAthena: entering and exiting the map using warp portal.
![screenYourRO006](https://user-images.githubusercontent.com/4976551/55168337-9b683280-51ad-11e9-9a93-c45c30e641cb.jpg)
![screenYourRO007](https://user-images.githubusercontent.com/4976551/55168622-1893a780-51ae-11e9-99a2-fdb14b62eece.jpg)

Hercules: entering and exiting the map using warp portal.
![screenHercules010](https://user-images.githubusercontent.com/4976551/55168386-b044c600-51ad-11e9-9684-03e10ba5ab63.jpg)
![screenHercules011](https://user-images.githubusercontent.com/4976551/55168391-b20e8980-51ad-11e9-8232-3fa1cb053234.jpg)

**Comment by Stingor** [comment]
client.conf

// When a player teleports, changes maps, or logs in, will they face the direction they were facing before warped?
// Official: Disabled, players always face North.
spawn_direction: no
