### ISSUE TITLE
Autofeed for pet not working for Old pet, Poring, Drops, Imp, etc

### ISSUE THREAD

**Issue by cahya1992** [rathena/rathena#4063]
* **rAthena Hash**: 

06c8e0b49

* **Client Date**:  20180621

* **Server Mode**: re

* **Description of Issue**: 
  * Result: normal player doesnt have menu autofeed on pet status
  * Expected Result:  should have
  * How to Reproduce: try hacth some pet with normal account and then see pet status doesnt have autofeed feature
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment]
Make sure you have the correct lua files.

**Comment by siriousb** [comment]
to me works very fine!

**Comment by cahya1992** [comment]
@Lemongrass3110 If i use wrong Lua files its should GM account can't use that feature rigtht?

@siriousb Did you try with normal player or GM lv 0?

**Comment by cahya1992** [comment]
Update :
For Pet poring , drops, imp or old pet by deafult not allowed autofeed

`AllowAutoFeed: False`
and then i try to add this code on poring_egg
`AllowAutoFeed: true`
and @reloadmobdb
Still doesnt work

**Comment by Lemongrass3110** [comment]
It does not help to only add this server side. You need to add the correct code in the lua as well.
