### ISSUE TITLE
Sorcerer[Cloud Kill] Status Icon issue

### ISSUE THREAD

**Issue by reigneil** [rathena/rathena#407]
is it SI_CLOUDKILL officially implemented in kRO? what the issue here is that all SC_POISON do have SI_CLOUDKILL icon where in other official client like iRO dont have...
set_sc( NPC_POISON		, SC_POISON		, SI_BLANK		, SCB_DEF2|SCB_REGEN );
add_sc( TF_POISON		, SC_POISON		);
add_sc( AS_VENOMDUST		, SC_POISON		);
set_sc( SO_CLOUD_KILL   , SC_POISON         , SI_CLOUDKILL      , SCB_NONE );

**Comment by aleos89** [comment]
What you're saying is, is that Cloud Kill should have an icon? Since it's using SC_POISON (which doesn't have an icon), nothing is being shown.

Do you have any screenshots or video of it having an icon on kRO?

**Comment by reigneil** [comment]
no it isn't on official server. i.e iRO, pRO
thats why i ask if it is officially implemented on kRO... what i think is this SI_CLOUDKILL should be blank so that it cannot affect other skill that has SC_POISON.

**Comment by reigneil** [comment]
now it looks like kRO is attempting to implement new status icon. XD
http://forums.irowiki.org/showthread.php?s=ff060ea6e0588cbc200229f7f0780a32&t=107075
http://www.divine-pride.net/gallery/27

**Comment by aleos89** [comment]
iRO Wiki changed their forum so all their old links don't work. Here's the new one:
http://forums.irowiki.org/index.php?topic=107075.0
