### ISSUE TITLE
pet_hungry_delay_rate

### ISSUE THREAD

**Issue by sader1992** [rathena/rathena#4073]
* **rAthena Hash**: 7dde174c832266a96c9ce7a4b92af87c2a929d10

* **Client Date**: 2018-06-21a

* **Server Mode**: Pre-Renewal

* **Description of Issue**: 
  * Result: pet hungry rate jump from 100% to 10% to 0%
  * Expected Result: i don't know how it should go down but not that fast
  * How to Reproduce: disable petautofeed feature > get pet > feed it to fill > wait a min
  * Official Information:

* **Modifications that may affect results**: 
none

![image](https://user-images.githubusercontent.com/5981261/55468597-02e60e00-5604-11e9-8f9b-13f56b798e7f.png)
![image](https://user-images.githubusercontent.com/5981261/55468771-64a67800-5604-11e9-8c6b-496e4deadb6f.png)

after 1 min
![image](https://user-images.githubusercontent.com/5981261/55468636-198c6500-5604-11e9-8763-0a3bdc419add.png)
![image](https://user-images.githubusercontent.com/5981261/55468803-77b94800-5604-11e9-9625-9d0853b3332a.png)

after 1 min
![image](https://user-images.githubusercontent.com/5981261/55468698-3c1e7e00-5604-11e9-8179-18fbdb96be12.png)

![image](https://user-images.githubusercontent.com/5981261/55468722-450f4f80-5604-11e9-8eed-523311b1c27a.png)

**Comment by Playtester** [comment]
Yes, I can confirm this by looking at the source code and the YAML files:

The problem is the variable "Fullness":

> #   Fullness                 The amount of hunger is decreased every [HungryDelay] seconds.

> Fullness: 80

By default the fill level decreases by 80% every 60 seconds. I'm fairly sure this should be 1 instead of 80 by default.
