### ISSUE TITLE
Pet Can't Return to Egg

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#4075]
* **rAthena Hash**: c977558

* **GCC Version**: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)

* **Client Date**: 20170517RE

* **Server Mode**: RENEWAL

* **Description of Issue**: Pet/Pet Evo Cannot return to Egg
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by cahya1992** [comment]
you must deleted the old petdatabase because before you update pet evo you already have pet

**Comment by Lemongrass3110** [comment]
I think i need to offer an update script for this
