### ISSUE TITLE
Cannot Exchange Bullet Pack

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#4076]
* **rAthena Hash**: c977558

* **GCC Version**: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)

* **Client Date**: 20170517RE

* **Server Mode**: Cannot Exchange Bullet Pack check screenshot

* **Description of Issue**: 
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**: 
  
  

![screenRENEWAL004](https://user-images.githubusercontent.com/8316103/55544437-453b4800-56f5-11e9-94f6-7b373a98bd85.jpg)

**Comment by aleos89** [comment]
What's the item ID of your Silver Bullet? 13201 or 13221? Judging from the response you're getting, you have 13201 but you need 13221.

**Comment by cahya1992** [comment]
Bullet rebell have 2 bullet version
OLD and new and for that npc only accept the new one

**Comment by mazvi** [comment]
So why are there two items sold with different IDs with the same name here?

Are there not two different shops for pre-re and 1 for renewal?

because 13201 is needed for pre-re while 13221 is needed for renewal?

**Comment by zackdreaver** [comment]
It's called "Surplus Silver Bullet" on iRO
http://db.irowiki.org/db/item-info/13201/
