### ISSUE TITLE
follow up about spawn_direction

### ISSUE THREAD

**Issue by reigneil** [rathena/rathena#408]
when you use teleport and your view point facing south it must revert back to facing north not just your character.

**Comment by Playtester** [comment]
You mean for example teleport and then use backslide and then it should always go into "south" direction because you face north?

**Comment by reigneil** [comment]
what I am referring to is this commit
https://rathena.org/board/tracker/issue-8754-character-position-issue/?gopid=25644#entry25644
the addition i want to add is make your viewing(right click changing viewing) revert back to original position as if you were login your character using teleport/changing map etc... see the SS of blacksmith viewing(facing east) before i respawn to alberta(facing north sync to my character facing north also)

**Comment by reigneil** [comment]
looks like this addition is not official behavior. although i'm testing it in iRO... marked this as invalid /sry
