### ISSUE TITLE
Map Crash killing monster

### ISSUE THREAD

**Issue by M4karov** [rathena/rathena#4085]
* **rAthena Hash**: 1504507e7199fc163f64d7b84829067ee052d8d0

* **Client Date**: 20180620

* **Server Mode**: Pre-Renewal

* **Description of Issue**: By killing a map crash monster. When using the visual studio debug the following line is suggested as where the problem arose.
![Screenshot_1](https://user-images.githubusercontent.com/17849495/55648113-cce88b80-57b5-11e9-89d2-4a26e2c0ff53.png)
  * Result: 
  * Expected Result: 
  * How to Reproduce: I tried to kill a monster.
  * Official Information:
  

* **Modifications that may affect results**: None

**Comment by pigati23** [comment]
https://github.com/rathena/rathena/pull/4065
