### ISSUE TITLE
Lua Files/DataInfo/TB_Layer_Priority [string "buf"]:14: table index is nil

### ISSUE THREAD

**Issue by SojaIntegral** [rathena/rathena#4095]
* **rAthena Hash**: didn't understand this part... I'm kinda new here ._.

* **Client Date**: 2018-05-30

* **Server Mode**: renew

* **Description of Issue**: Every time I open my ragnarok I get the error "Lua Files/DataInfo/TB_Layer_Priority [string "buf"]:14: table index is nil"
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**: I was just translating my db with the Server DB Editor and after I save the files I get this error. I tryed to delete the line, change the file with other grfs and nothing. Same error.
  
  
Here the file:
![Screenshot_1](https://user-images.githubusercontent.com/45701855/55832112-1d7c2380-5aeb-11e9-94d1-4ec5034be8a2.png)

**Comment by aleos89** [comment]
Please use the forum for client issues like this. Thanks!
