### ISSUE TITLE
Throw Kunai Renewal Damage

### ISSUE THREAD

**Issue by SeravySensei** [rathena/rathena#4105]
This seems to be an issue for renewal too : https://github.com/rathena/rathena/issues/860
I couldn't find any source on the internet that states Renewal should be doing 3 times 300% damage instead of a total of 300% damage displayed as 3 hits. Divine Pride doesn't seem to mention the amount of damage whatsoever. Other sources I found all say "total of 300% damage in 3 hits".
If this is true and not outdated information, in the renewal skill_db.txt
524,9,8,1,-1,0x40,0,5,3,no,0,0,0,weapon,0,0x0, NJ_KUNAI,Throw Kunai
should be
524,9,8,1,-1,0x40,0,5,-3,no,0,0,0,weapon,0,0x0, NJ_KUNAI,Throw Kunai
instead, please check.

**Comment by Playtester** [comment]
Pretty sure it was one of those renewal updates that updated it to do 3 times 300% damage, but not familiar enough with renewal to confirm.

**Comment by SeravySensei** [comment]
It seems this is actually no longer relevant in this form. There is a new patch that changes most of the Ninja skills, including Throw Kunai's damage formula : https://ragnarok.gamepedia.com/RO_Patch_(2019_Mar._06)

**Comment by aleos89** [comment]
I'll close this since you detailed it in #4114.
