### ISSUE TITLE
Floating NPC & logmes crash due to command requiring map for logfile/table insertion

### ISSUE THREAD

**Issue by Akkarinage** [rathena/rathena#4109]
* **rAthena Hash**: c772262469361d1e76b3e15c00c35cc3285aa5c8

* **Client Date**: 20180620, but affects any.

* **Server Mode**: Renewal, but affects both.

* **Description of Issue**: 
  * Result: 
![ss (2019-04-12 at 05 36 58)](https://user-images.githubusercontent.com/4101952/56148378-1600c280-5fa2-11e9-9100-2315a032716b.png)

  * Expected Result: logmes should save to file/table without needing to be attached to NPC on map.
  * How to Reproduce: Create floating NPC and add a logmes command. 

  * Official Information: None

* **Modifications that may affect results**: None

**Comment by Atemo** [comment]
Current PR https://github.com/rathena/rathena/pull/4103

**Comment by aleos89** [comment]
Fixed in c264d3e.
