### ISSUE TITLE
Costume refineability

### ISSUE THREAD

**Issue by crazystorm2017** [rathena/rathena#4111]
* **rAthena Hash**: 3057af7

* **Client Date**: N/A

* **Server Mode**: Renewal

* **Description of Issue**: Almost all of the costumes in 20k ID range is refineable.
  * Result:  
  * Expected Result:  Should not be refineable.
  * How to Reproduce: 
  * Official Information: Tested some costumes in jRO, iRO and some cheap costumes in kRO.
  

* **Modifications that may affect results**:

**Comment by cydh** [comment]
> Should not be refineable.

SS/vid please
