### ISSUE TITLE
Elemental Manteau Warlock or Socerer?

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#4112]
* **rAthena Hash**: a348016

* **Client Date**: 20170517RE

* **Server Mode**: RENEWAL

* **Description of Issue**: Elemental Manteau Warlock or Socerer? because on description for Socerer but on database for warlock :)
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Can you provide the item ID?

**Comment by mazvi** [comment]
15177
20820

Please check between desc and database :) i dont know how to change job on db
