### ISSUE TITLE
rental item doubt

### ISSUE THREAD

**Issue by Litro** [rathena/rathena#4117]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/4d05e09ef3057262c0bef87071a056c7908f91ef

* **Client Date**: 20180530

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Rental item can be storaged or put into cart
  * Expected Result: Should not can be put into storage or cart
  * How to Reproduce: make a rental item.
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
I believe personal storages are permitted for rental items. Do you have any kRO info that says otherwise?

**Comment by Litro** [comment]
as long as I remember it shouldn't can be put into storage or cart and going by script doc

```
*rentitem <item id>,<time>{,<account_id>};
*rentitem "<item name>",<time>{,<account_id>};

Creates a rental item in the attached character's inventory. The item will expire
in <time> seconds and be automatically deleted. When receiving a rental item,
the character will receive a message in their chat window. The character will
also receive warning messages in their chat window before the item disappears.

When rentals expire it will call the OnUnequip Script of the item. This can be used
for special cases such as removing a status change or resetting a variable or state
of the player.

This command can not be used to rent stackable items. Rental items cannot be
dropped, traded, sold to NPCs, or placed in guild storage. (i.e. trade mask 75)
Note: 'delitem' in an NPC script can still remove rental items.
```

and it seem check of rental timer only happen when rental time is on the inventory of player.

**Comment by cydh** [comment]
I told this already, we forced rental item to cannot be moved. It shouldn't, all rental items are different item with non-rental items, and they have their own item move restriction

**Comment by aleos89** [comment]
I'll close this in-lieu of Cydh's previous report.
