### ISSUE TITLE
Unitwalk event cannot be repeated

### ISSUE THREAD

**Issue by sader1992** [rathena/rathena#4118]
* **rAthena Hash**: tested in 9f4a569ecc0af179e6926c2b31062b2fff3bd771 and  ce1508a01c68dee80544242b470987742f3b3ece

* **Client Date**: 20180620

* **Server Mode**: renewal

* **Description of Issue**: 
  * Result: unitwalk event does not run twice while in it self
  * Expected Result: the event should be repeatable if the script tell it to be
  * How to Reproduce: 
```cs
prontera,155,174,0	script	unitwalk	444,{
	if(select("1:2") == 1){
		monster "prontera",155,170,"poring",1002,1;
		.gid = $@mobid[0];
	}
OnMove:
	debugmes "" + ++.i;
	getunitdata .gid,.@data;
	unitwalk .gid,.@data[UMOB_X],(.@data[UMOB_Y] - 15), strnpcinfo(0) + "::OnMove";
end;
}
```
result
```cs
[Debug]: script debug : 2000000 110000026 : 1
[Debug]: script debug : 110000028 110000026 : 2
```
the first line is when the command run without the event
the 2nd one when the event run
there is no 3rd

also tested it (with the option 2 in the script) it just tell the already spawned mob to move and it's the same result
the event should be called anytime time the script tell it

  * Official Information: none

* **Modifications that may affect results**: 
none

**Comment by sader1992** [comment]
Update:
this happen only when the event is the same name as the last event
if event `OnMove` called `OnMove` >> wont work
if event `OnMove` called `OnMove2` >> work

**Comment by Atemo** [comment]
If I'm not wrong the self event on `unitwalk` is limited by the system timer. A delay in the npc script is probably necessary.

**Comment by sader1992** [comment]
i wrote the delay part , but than i removed it before posting xD
how did you know o.O

for the event problem
removing
```cs
			// Check if another event was set
			if( !strcmp(ud->walk_done_event,walk_done_event) ){
				// If not remove it
				ud->walk_done_event[0] = 0;
			}
```
and adding 
```cs
			ud->walk_done_event[0] = 0;
```
after
```cs
			// Copying is required in case someone uses unitwalkto inside the event code
			safestrncpy(walk_done_event, ud->walk_done_event, EVENT_NAME_LENGTH);
```
fixed the problem
however not sure if this will effect other things too , so i will look more into it

**Comment by sader1992** [comment]
for the delay , i think the server should check for the event before it do anything with the monster , but i can imagine if the script was too complex what would happen to the server xD
i don't know if it would be good idea , for that i removed the delay part
but it would be cool if it happen , making the monster/unit moves as we say without delay/unwanted movment
