### ISSUE TITLE
bBaseAtk with negative value issue

### ISSUE THREAD

**Issue by reigneil** [rathena/rathena#412]
it seems that this bBaseAtk if you insert negative value wont work. i.e
equipping item id 4339 "Mineral Card" wont reduce your Atk. can anyone confirmed this?

OT btw what is bAtk and bAtk2., is this the version of weapon attack and status attack?

**Comment by Playtester** [comment]
Probably a renewal-only issue because there are different types of ATK in renewal. BaseATK can't go below 0, and if it's always 0 on renewal, that would explain why negative values wouldn't work.

**Comment by reigneil** [comment]
if it is the case then why it not set to zero or reduce only? i.e weapon attack = 150 then i use bBaseAtk -50 it must be set to 100 weapon attack right... or if i have weapon attack = 150 then i use bBaseAtk -200 it must be set to 0 right or do i miss something?

**Comment by Playtester** [comment]
You are probably right, but I'm not familiar enough with the renewal damage code, it's quite complex and different from pre-renewal. There are 4 attack types rather than just 2.
http://irowiki.org/wiki/ATK

But in pre-renewal it was as you said. Like if you have 10 ATK and equip a -20 ATK item it goes to 0 ATK.

**Comment by jezznar** [comment]
* **rAthena Hash**: c212b2ed053d60855ce584a0368d98cff94c5059

* **Client Date**: 2015-11-04

* **Server Mode**: both

* **Description of Issue**: Issue is still visible in the latest git commit. https://gaming.youtube.com/watch?v=xvEGvxol27U&feature=share
  * Result: bBaseAtk is not working when negative values are used. No updates in status window. No reduction in actual damage output. Doesn't work even if it is moved from script field to equip_script field in the database. Works correctly when positive values are used
  * Expected Result: 

- [ ] bBaseAtk should work when negative values are used
- [ ] Status window should be updated
- [ ] Actualamage output should be reduced

  * How to Reproduce: Use an item with negative bBaseAtk bonus.
  * Official Information: N/A

* **Modifications that may affect results**:  N/A
