### ISSUE TITLE
Duplicated NPCs can not be loaded properly

### ISSUE THREAD

**Issue by teededung** [rathena/rathena#4125]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/ce1508a01c68dee80544242b470987742f3b3ece

* **Client Date**: 20180621

* **Server Mode**: Both

* **Description of Issue**: 
  * Result: Duplicated NPCs can not be loaded properly after using `@reloadnpc`
  * Expected Result: Duplicated NPCs can be loaded
  * How to Reproduce: 

1. Write `npc: npc/custom/test.txt` to npc/scripts_custom.txt

2. Create a new npc file `test.txt`
```
prontera,151,176,0	script	Tree#main	HIDDEN_NPC,{
end;
OnInit:
	waitingroom strnpcinfo(0),0;
	end;
}

prontera,151,173,0	duplicate(Tree#main)	Tree#1	HIDDEN_NPC
prontera,151,170,0	duplicate(Tree#main)	Tree#2	HIDDEN_NPC
```

Using `@reloadscript`
![reloadscript](https://user-images.githubusercontent.com/9781158/56566202-4b2d9600-65dc-11e9-83c2-a8067c15d711.jpg)

Using `@reloadnpc npc/custom/test.txt` 
![reloadnpc](https://user-images.githubusercontent.com/9781158/56566214-5254a400-65dc-11e9-8ef4-14b8350343ec.jpg)

**Comment by Litro** [comment]
Oninit isn't triggered when using `@reloadnpc` and `@reloadnpcfiles`
