### ISSUE TITLE
Focus arrow damage should increase when crit.

### ISSUE THREAD

**Issue by attackjom** [rathena/rathena#4128]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/53cedb72af3c1ffd863c02cd716566b50cfe999d

* **Client Date**:  ragexe2018-09-19a

* **Server Mode**: Renewal

* **Description of Issue**: 
Focus arrow strike skill of Sniper class not do more damage when critical and can't take critical damage bonus from item.

  * Result: 
  * Expected Result: 
   - It should deal critical damage and gain CritAtkrate itembonus
  * How to Reproduce: 

  * Official Information:
  

Today I have test Focus arrow strike skill in KRO server, and found these information

1. Focus arrow will improve damage when do critical damage around 1.4x as you can see in the picture

// Not critical //
![screen»çÅ©¶óÀÌ010](https://user-images.githubusercontent.com/35770095/56668976-a2b22b80-66da-11e9-88dd-10c23d156a7c.jpg)

// Critical //
![screen»çÅ©¶óÀÌ009](https://user-images.githubusercontent.com/35770095/56668995-a80f7600-66da-11e9-81c3-fbce543433ba.jpg)

2. Focus arrow  have a bonus from criticaldamage itembonus ex. The Paper card
![screen»çÅ©¶óÀÌ012](https://user-images.githubusercontent.com/35770095/56669089-cf664300-66da-11e9-8f41-ae155f06cf45.jpg)

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
The Paper Card bonus is currently implemented to only give a bonus on physical attacks. Guess this proves it applies to skills, at least in renewal.

**Comment by aleos89** [comment]
This is part of #4072.
