### ISSUE TITLE
Drop Rates - something its very wrong

### ISSUE THREAD

**Issue by samurairukasu** [rathena/rathena#413]
Rathena: Last Git
Config: Drops.conf not changed, same like git repo
exe: 20141022
intance: Renewal.

Guys, some thing is very strange about Drop rates, why if no changes was made in Drops config they are not the same has official?

For example, take mob Scorpion (1001), drop items in (http://db.irowiki.org/db/monster-info/1001/)
Say that Red Blood has 0.71% of drop, but when u use @mi or @mobinfo and read Red Blood drop is 0.35%, includded all it drops. This happend for all mobs drops, they are not the same.

I check mob_db.sql, mob_db_re.sql, mob_db.txt and the drop for Red Blood is set for 0.7 (value = 70)

Something is wrong with Drop Rates formulas in SRC?

Regards

**Comment by Playtester** [comment]
Maybe you are using renewal?

**Comment by samurairukasu** [comment]
Indeed, but how this change with the drop rate?

**Comment by aleos89** [comment]
Found in conf/gm.conf:
```
// requires RENEWAL_EXP or RENEWAL_DROP to be enabled (src/config/renewal.h)
// modifies @mobinfo to display the users' real drop rate as per renewal_drop formula
// modifies @iteminfo to not display the minimum item drop rate (since it can't tell the mob level)
// modifies @whodrops to display the users' real drop rate as per renewal_drop formula
atcommand_mobinfo_type: 1
```
Because you have RENEWAL_EXP or RENEWAL_DROP active, the command is adjusting the rates to display what they would be based on the player's level compared to the monster's level.

Working as intended.

**Comment by Playtester** [comment]
To answer your question: Comment RENEWAL_DROP in src/config/renewal.h if you don't want renewal drop rate adjustments.

**Comment by samurairukasu** [comment]
No problem, i didn't remember about the level punishment in Renewal affect Drops too beside exp rates.

Sorry for the issue.

Regards!!
