### ISSUE TITLE
achievement system not working as intended

### ISSUE THREAD

**Issue by daisyanne1380** [rathena/rathena#4131]
* **rAthena Hash**: 

a34801605

* **Client Date**: 
2018-06-20

* **Server Mode**: 

renewal

* **Description of Issue**: 
 i gained 1 job level and it gave me achievement for level 1/2/3 and 4. then the other wont work and become broken.

i notice this happen in last month to a few member but it wasn't really look at cause it was a level 1 achievement. It was then look at more closely when the title "Persistent" could not be gained due to the fact that after 4 its glitched and you wont get credit.

i noticed that other titles in other tabs like Master and Grand Master are not affected and all work, This seem isolated to the Feat tab and its achivments

![glitch](https://user-images.githubusercontent.com/25291258/56880329-40cf2a00-6a2a-11e9-8017-70d643eabe3b.jpg)

**Comment by daisyanne1380** [comment]
this is who i did it:

1. i made a level 1 novice
2. attacked a  mob that gave me 1 job level
3. and it gave me achievement for gaining level 1, level 2, level 3, and level 4, like the image shows.

When this happen, achievement gain level 6, level 7, level 8, level 9, and level 10, will not work. Making it impossible to gain the title "Persistent". 

This only happens in "Feat" tabs,  all other achievements in other tabs work fine.

**Comment by aleos89** [comment]
Do you have any custom achievements? I would have to debug to follow, but there are only 2 job level achievements, one for level 50 and the other 70.

**Comment by daisyanne1380** [comment]
no i dont have customs. They in rathena achievement _db.yml in RE folder.
here is the seciton:
`  - ID: 240000
    Group: "AG_GOAL_LEVEL"
    Name: "Complete challenges after first introduction"
    Score: 10
  - ID: 240001
    Group: "AG_GOAL_ACHIEVE"
    Name: "Reaching Level 1"
    Reward:
      ItemID: 644
      Script: " specialeffect2 EF_INCAGILITY; sc_start SC_INCREASEAGI,30000,10; "
    Score: 10
  - ID: 240002
    Group: "AG_GOAL_ACHIEVE"
    Name: "Reaching Level 2"
    Dependent:
      - Id: 240001
    Reward:
      ItemID: 644
      Script: " specialeffect2 EF_INCAGILITY; sc_start SC_INCREASEAGI,30000,10; "
    Score: 10
  - ID: 240003
    Group: "AG_GOAL_ACHIEVE"
    Name: "Reaching Level 3"
    Dependent:
      - Id: 240002
    Reward:
      ItemID: 644
      Script: " specialeffect2 EF_INCAGILITY; sc_start SC_INCREASEAGI,30000,10; "
    Score: 10
  - ID: 240004
    Group: "AG_GOAL_ACHIEVE"
    Name: "Reaching Level 4"
    Dependent:
      - Id: 240003
    Reward:
      ItemID: 644
      Script: " specialeffect2 EF_INCAGILITY; sc_start SC_INCREASEAGI,30000,10; "
    Score: 10
  - ID: 240005
    Group: "AG_GOAL_ACHIEVE"
    Name: "Reaching Level 5"
    Dependent:
      - Id: 240004
    Reward:
      ItemID: 644
      Script: " specialeffect2 EF_INCAGILITY; sc_start SC_INCREASEAGI,30000,10; "
    Score: 10
  - ID: 240006
    Group: "AG_GOAL_ACHIEVE"
    Name: "Reaching Level 6"
    Dependent:
      - Id: 240005
    Reward:
      ItemID: 644
      Script: " specialeffect2 EF_INCAGILITY; sc_start SC_INCREASEAGI,30000,10; "
    Score: 10
  - ID: 240007
    Group: "AG_GOAL_ACHIEVE"
    Name: "Reaching Level 7"
    Dependent:
      - Id: 240006
    Reward:
      ItemID: 644
      Script: " specialeffect2 EF_INCAGILITY; sc_start SC_INCREASEAGI,30000,10; "
    Score: 10
  - ID: 240008
    Group: "AG_GOAL_ACHIEVE"
    Name: "Reaching Level 8"
    Dependent:
      - Id: 240007
    Reward:
      ItemID: 644
      Script: " specialeffect2 EF_INCAGILITY; sc_start SC_INCREASEAGI,30000,10; "
    Score: 10
  - ID: 240009
    Group: "AG_GOAL_ACHIEVE"
    Name: "Reaching Level 9"
    Dependent:
      - Id: 240008
    Reward:
      ItemID: 644
      Script: " specialeffect2 EF_INCAGILITY; sc_start SC_INCREASEAGI,30000,10; "
    Score: 10
  - ID: 240010
    Group: "AG_GOAL_ACHIEVE"
    Name: "Reaching Level 10"
    Dependent:
      - Id: 240009
    Reward:
      ItemID: 644
      Script: " specialeffect2 EF_INCAGILITY; sc_start SC_INCREASEAGI,30000,10; "
      TitleID: 1023
    Score: 10`

**Comment by SeravySensei** [comment]
I merged the last 2 months worth of commits into my fork today and now I'm getting map server errors :
[Error]: Database type mismatch: ATTENDANCE_DB != ATTENDANCE_CONF.
[Error]: Failed to verify compatibility with ATTENDANCE_DB database file from 'db/import/attendance.yml'.[Error]: No database "Header" was found.
[Error]: Failed to verify compatibility with ACHIEVEMENT_DB database file from 'db/import/achievement_db.yml'.
 
Might be related? The related files didn't have a merge conflict and I don't think I ever changed them. Does everyone get these errors or just me?

**Comment by Akkarinage** [comment]
@SeravySensei Would you like to keep your issues separate, and in your own issue reports, please? Your issues are basically user-error. Please use the forums for this.

**Comment by SeravySensei** [comment]
Whatever, I deleted the comment, enjoy. The error referenced an achievement file after updating so I thought it might be related.

**Comment by aleos89** [comment]
So the issue at hand is that kRO only carries over your total points to the next level rather than it being a cumulative value.
