### ISSUE TITLE
花妖精卡片

### ISSUE THREAD

**Issue by cdndy20164014** [rathena/rathena#4133]
花妖精卡片玩家反應無效果 幫檢查是否不正常

**Comment by secretdataz** [comment]
Please file your report in English

**Comment by UniverseCodes** [comment]
Used google translator, this is what i got from his statement though.
`
Flower Leprechaun card player reaction has no effect. Check if it is not normal.`

**Comment by secretdataz** [comment]
If a bug report takes 15 minutes to find out about the nature of the bug and 5 minutes to fix. The reporter should spend those 15 minutes, not us, who have to deal with a lot of reports. Especially with this case, Google translator doesn't really help with `Flower Leprechaun`.

And yes, I know how to use Google translator. Thanks anyways :)

**Comment by UniverseCodes** [comment]
No Problem, just trying to help :smile:
