### ISSUE TITLE
Item Bonus Limit -10000 ~ +10000

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#4135]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/ce1508a01c68dee80544242b470987742f3b3ece

* **Client Date**: 20180621

* **Server Mode**: RE

* **Description of Issue**: 
  * Result:  
Some items need values greater than this set range. For examples:
https://www.divine-pride.net/database/item/29584
https://www.divine-pride.net/database/item/2582

[Warning]: pc_bonus_itembonus: Item bonus val 30000 exceeds -10000~10000 range, capping.
  * Expected Result: 
The problem begins after this:
https://github.com/rathena/rathena/commit/a0bcb92b8a39a45005d111f21697af380aa6f1a1
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by cahya1992** [comment]
confirmed this issue

**Comment by Badarosk0** [comment]
This correction made some bonuses have problems reducing damage in some skills and the cooldown of some became very high @aleos89

**Comment by Badarosk0** [comment]
Solved with this PR:
https://github.com/rathena/rathena/pull/4137
