### ISSUE TITLE
Fire expansion lv 3 didn't reduce damage acid

### ISSUE THREAD

**Issue by cahya1992** [rathena/rathena#4140]
* **rAthena Hash**: 

06c8e0b49

* **Client Date**: 20180621

* **Server Mode**:  Renewal

* **Description of Issue**:  Fire expansion lv 3 have effect reduce range damage 50% But damage acid didn't reduce 
  * Result:  Should Reduce
  * Expected Result: 
  * How to Reproduce:  Use Skill Demonic Fire
Use Skill fire expansion lv 3
Try Your enemy acid to you and damage acid didn't reduce although player inside demonic fire effect
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Unable to reproduce on b211d84. My damage from Acid Demonstration was decreased while inside of Fire Expansion Smoke Powder.
