### ISSUE TITLE
Item number of eggs, pet problems

### ISSUE THREAD

**Issue by Pringle012** [rathena/rathena#4144]
* **rAthena Hash**: 7f772c32d3be201861946bb64720c231828465ac

* **Client Date**:  2015-11-04aRagexe

* **Server Mode**: Pre-Renewal

* **Description of Issue**: Add new pet eggs By which the item number of pet eggs 15000+ When hatched, eggs are damaged items. And eggs not hidden Normally, the original pet eggs will be hidden.
![image](https://user-images.githubusercontent.com/50212919/57096705-163de380-6d40-11e9-9dd2-7670847c80d5.png)
![image](https://user-images.githubusercontent.com/50212919/57096757-2bb30d80-6d40-11e9-8f7b-f5084b3912b4.png)

  * Result: 
  * Expected Result: add the item number of pet eggs more than 15000+
  * How to Reproduce:  How to make pet items to be able to use numbers more than 15000

**Comment by aleos89** [comment]
Did you happen to add the custom pets you created to the client's LUA files?

**Comment by Pringle012** [comment]
> Did you happen to add the custom pets you created to the client's LUA files?

I have added LUA files
petinfo
npcidentity
jobname

**Comment by Lemongrass3110** [comment]
Please copy your custom pet egg item db entries and custom pet db entries into here so we can verify if you have everything correctly.

I could imagine that Gravity has hardcoded the pet egg range into their client and that some client side functionality is limited to a certain item id range by them.

**Comment by Lemongrass3110** [comment]
No further input.
