### ISSUE TITLE
compiling warning

### ISSUE THREAD

**Issue by Miraakol** [rathena/rathena#4145]
* **rAthena Hash**: 

* **Client Date**: 

* **Server Mode**: 

* **Description of Issue**: 
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**: 
  
  
Client Date: 2018-08-31aRagexe_patched
Server Mode: Renewal
Description of Issue:
Result: when compiling on centos 64 bit i received this warning im using clean and updated trunk.
![error compiling](https://user-images.githubusercontent.com/4651777/57175590-720f8600-6e80-11e9-984d-14b23e911dc6.JPG)

How to Reproduce: donwload latest trunk, then compile

**Comment by Miraakol** [comment]
@secretdataz hi im sorry but is this normal?

**Comment by secretdataz** [comment]
yes

**Comment by anacondaq** [comment]
no, this is not normal. Upgrade your libconfig to latest version and fix all conflicts, and there will be no such problems.

**Comment by secretdataz** [comment]
A pull request is welcome
