### ISSUE TITLE
Multi hit critical not working

### ISSUE THREAD

**Issue by Miraakol** [rathena/rathena#4147]
* **rAthena Hash**: 

* **Client Date**: 2018-08-31aRagexe

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: critical damage must affect with double attack skills just like with the other server (sample server is official servers and novaro)
  * Expected Result: https://youtu.be/siwoq_-iYVg and https://youtu.be/MSdkeYNzNtk
  * How to Reproduce: use job with double attack skill or item that has double attack skill
  * Official Information:
  

* **Modifications that may affect results**: none

**Comment by aleos89** [comment]
Reported in #1788 and provided through #2982. You're welcome to provide input on it!
