### ISSUE TITLE
Minimap player icon disappearing at the edge

### ISSUE THREAD

**Issue by dragonis1701** [rathena/rathena#415]
As the abnormally long title states: when a player moves to the edge of a map, their reticle disappears from the mini-map. Pictures will show what I mean.
http://i207.photobucket.com/albums/bb64/Evensean021502/screenDecentRO003_zpsaoloehwy.jpg
http://i207.photobucket.com/albums/bb64/Evensean021502/screenDecentRO004_zpsvqr3qiyp.jpg

**Comment by aleos89** [comment]
This has to do with the map itself, nothing server side. It has been bugged like this since the inception of that map. Gravity just doesn't care about fixing bugs in their maps.
