### ISSUE TITLE
Steal Skill getting item not avaible in the monster database

### ISSUE THREAD

**Issue by AzarthMZintos** [rathena/rathena#4151]
* **rAthena Hash**: 7f772c3

* **Client Date**: 2018-06-21aRE

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Im using a thief char using the steal skill I get a item im not suposte to be able to steal, the mob is id 1077 poison spore, and the item id is 14469 Cow Tail Scroll
  * Expected Result: Should not be able to steal a item not avaible in the monster database
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**: 
  
  

rathena\src\map\pc.cpp =

rate = (sd_status->dex - md_status->dex)/2 + skill_lv*6 + 4;

CHANGE TO

rate = (sd_status->dex - md_status->dex)/4 + skill_lv*12 + 8;

rathena\src\map\mob.hpp =

#define MAX_STEAL_DROP 7

CHANGE TO

#define MAX_STEAL_DROP 30

PS: it happen only 2 times most of the time I get regular items.

It happen NOW also with Warrior Orc Id mob 1023

**Comment by AzarthMZintos** [comment]
PS: it happen to 2 only most of the time I get regular items

**Comment by secretdataz** [comment]
This is caused by you changing the MAX_STEAL_DROP value
