### ISSUE TITLE
Item script 13192

### ISSUE THREAD

**Issue by SeravySensei** [rathena/rathena#4153]
https://www.divine-pride.net/database/item/13192/death-fire-1
13192,DEATHFIRE,Death Fire,5,1250000,,2000,400,,9,1,0x40000000,63,2,34,3,108,1,20,{ bonus bLongAtkRate,5; bonus bHit,-50; bonus bDelayrate,-10; },{},{}

Should be range +5 but script adds 5% long range damage instead. Should be ASPD-10% but script has Skill Delay-10%. Probably needs investigation on the official server as the listed abilities vary a lot on each website.
Edit : Same problem with item 13193, has script for less cast delay instead of slower ASPD.

**Comment by aleos89** [comment]
Could you try to follow the issue template. It helps with tracking. Thanks.
