### ISSUE TITLE
Rake and Antler Scaraba

### ISSUE THREAD

**Issue by dragonis1701** [rathena/rathena#416]
These two scarabas do not start using skills until after they take damage. They will only normal attack until they are damaged. This effects both of them but does not apply to the scarabas on the first floor.

**Comment by Playtester** [comment]
Rake and Antler Scaraba are angry mode monster without angry skills. So it's working as intended. Angry mode monsters behave exactly like this. They only use normal skills once they are hit.

In Nightmare Mode they have a different mode, however. :
