### ISSUE TITLE
Knight[Charge Attack] skill issue

### ISSUE THREAD

**Issue by reigneil** [rathena/rathena#417]
the damage cap of this skill aren't official if we look at the data provided by irowiki.
http://irowiki.org/wiki/Charge_Attack
and the range of this skill is set to 14 cell and it is the same data we can see at ...\data\luafiles514\lua files\skillinfoz\data\luafiles514\lua files\skillinfoz\skillinfolist.lub
if we compare this to jRO
http://mohige.sakura.ne.jp/knight/
[quote]Charge Attack
    Active
    Conditions: acquired by Quest progression
    Abbreviation: CA
At once approached the enemy who is in long distance, to attack. Distance becomes higher the attack power is far away, but the casting time will be longer.

The object distance 	0-3 cell 	4-6 cell 	7-9 cell 	10-12 cell 	13 to cell
Offensive power 	100% 	200% 	300% 	400% 	500%
Casting time 	0.5 seconds 	1.0 seconds 	1.5 seconds 	1.5 seconds 	1.5 seconds
Consumption SP 	40

[Learn Quest 40 fixed: consumption SP Quest see]
    Instantly move to one cell adjacent the target to provide the same time constant amount of damage when. Cell adjacent this time, direction close to chant point is selected.
    To knock back the target at the same time. Knock-back moving distance + 1 cells, the direction to push the cell opposite that adjacent to the enemy.
    Attribute, C, a star hitting the target effect ride. MISS Then knock back does not occur.
    Perhaps the biggest is 1.5 seconds with respect to chant
    Although casting time is determined at the moment that you target, power and knock back is determined by the distance of the moment to trigger the skills and chanting completed.
    Rays but are through does not occur even what appears to be a state in which the obstacle is sandwiched between the "skill use failure"
    If the ray is interrupted by, for example, cast after the enemy moves, move it but do not attack carried out by ignoring the obstacles. Enemy while casting it is possible to catch up to even warp destination to teleport.
    No transfer effect in seeds mode.
    It is canceled when attacked while casting.
    Because it is long-range attack is prevented by pneumatic.

Comment
     Range is longer by far. Distance is also possible to push the enemy from the active range if. It has interesting properties as a cut. but disappear from the skills list when incarnated in the learning state, re-mastered without the quest item if Hanashikakere to quest NPC from getting to LK.
      There is a scene to use in PVP.
      The only long-distance casting skills of non-incarnated knight. 50 There is a before and after DEX, and can also be used to Tage up in nameless 3 and Thor If you understand the characteristics.
       From knock back distance adjacent one cell, invisible damage displayed when fly off the screen to be variable until about fly out of the screen at maximum distance[/quote]
same info...is this different from kRO?

question: is this "int k = (wd.miscflag-1)/3;" rounding off its value?

**Comment by Playtester** [comment]
Ultramage originally did a test with Charge Attack and noticed that this skill is super useless on Aegis and updated the skill on eAthena accordingly.

See his test here: https://rathena.org/board/tracker/issue-67-test-skill-charge-attack/?gopid=67#entry67

Probably should be tested again, though.

**Comment by Playtester** [comment]
I can confirm this issue. At least in renewal the skill has a high range (as far as you can see) and can deal up to 500% damage. Also, it seems the casting time is 500ms even at the largest distance.

**Comment by Playtester** [comment]
This didn't actually fix it as you added a dist cap of 9, so damage still can't go higher than 300%. Also the current implementation makes it so that the first damage increase is at 6 cells rather than 4 cells as in the table above. I will do some more tests and try a slightly better implementation.

**Comment by Playtester** [comment]
Tests:
- *Damage*: 0-3 cells 100%, 4-6 cells 200%, 7-9 cells 300%, 10-12 cells 400%, 13 cells 500%
- *Cast Time Renewal*: 250 variable 250 fixed
- *Cast Time Pre-Renewal*: Casttime increases with higher range
- *Knockback*: The caster will actually land one cell next to the target, then applies knockback away from him, knockback is the distance between caster and target before the move
- *Pneuma*: Blocks skill completely
