### ISSUE TITLE
Invalid Position MAP_DEFAULT

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#4171]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/9aa5f7d8345d9d89ec9e8b44060e92703f3d43b8

* **Client Date**: 20180621

* **Server Mode**: RE

* **Description of Issue**: 

Default position x, y does not exist on the map:
https://github.com/rathena/rathena/blob/2ab298076c4eeb506aef156e24c835c31d417490/src/config/const.hpp#L104

Change to:
18,26
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Everade** [comment]
Isn't that the new~old coordinates?
I think they've changed the map a long time ago (yet again).
So it's no longer inside the ship if i'm not mistaken.

**Comment by aleos89** [comment]
Unless it changed after May, you are still started inside the ship.
