### ISSUE TITLE
Script error in item 31056 & 31089

### ISSUE THREAD

**Issue by CyberDevil75** [rathena/rathena#4177]
There are 2 comments in the file sql-files/item_db_re.sql with this ate the end of the script:
`} /* Need to confirm this *`

This cause 2 errors in console:
```
[Error]:
script error on item_db_re line 12022
    parse_curly_close: unexpected string
* 12022 : hateffect(HAT_EF_DOUBLEGUMGANG,false); '}' /* Need to confirm this *
[Error]:
script error on item_db_re line 12055
    parse_curly_close: unexpected string
* 12055 : hateffect(HAT_EF_BAKURETSU_HADOU,false); '}' /* Need to confirm this *
```

**Comment by sianromantic** [comment]
These two items are just the opposite(hateffect)

**Comment by aleos89** [comment]
According to the LUA, 31089's view ID is correct: `ACCESSORY_C_Exploding_Wave_Red = 1500,`
