### ISSUE TITLE
Bug Pet Egg (@storeall)

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#4178]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/9aa5f7d8345d9d89ec9e8b44060e92703f3d43b8

* **Client Date**: 20180621

* **Server Mode**: RE

* **Description of Issue**: 
  * Result: If you are with a Pet and use the @storeall command the Pet will not go back to Egg.
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by sader1992** [comment]
well not go back to Egg ?
what do you mean ?
the pet when you hatch it = the egg no longer in your inventory , so do you mean that after you do the command , than you are trying to get the pet back to an egg , you can't do it ?

it would be much better if you fill the **How to Reproduce** point

**Comment by Badarosk0** [comment]
1- Create an egg with the command @item 9003
2- Use an incubator to hatch an egg. @Item command 643
3. Try to return the pet to the egg after colliding. (It will work perfectly.)
4- Hatch the egg again.
5- Use the @storeall command
6- Try to turn the pet to the egg. (It will not work and the egg will not go back to the egg and will be stuck in your char)
@sader1992

**Comment by pigati23** [comment]
have you tried to create the egg with @makeegg?

**Comment by sader1992** [comment]
i can confirm the issue with PRE-RE 4ba54838fe78d86fd5e03ebe5ffcd650e092cac9
