### ISSUE TITLE
Mechanic[Magma Eruption] skill issue

### ISSUE THREAD

**Issue by reigneil** [rathena/rathena#418]
what i know about this skill is it suffer from the re-balance of new 3rd skills if we look at the skill description itself(default kRO) its duration is 5sec at any level, 1800 fixed damage now at level 5 and 0.5sec damage interval at any level.
more info about this new skills... big thanks to Rytech and all who help him.
http://forums.irowiki.org/showthread.php?t=107014
credit: Rytech

**Comment by cydh** [comment]
so,
deals 1800 damage in each 0.5 seconds for 5 seconds.

**Comment by raynra** [comment]
Stun and Burning effects don't appear to trigger.
Damage formulas are correct.

**Comment by OscarScorp** [comment]
Can confirm with raynra, no Stun or Burning effects are applied on targets.
Is it possible to just copy and paste lines of code from Dragon Breath / Hammerfall?

**Comment by RagnarokNova** [comment]
Gotta learn how to navigate git :[ But here: https://github.com/rathena/rathena/pull/661/files
