### ISSUE TITLE
Swordsman[Magnum Break] skill can damage hidden target?

### ISSUE THREAD

**Issue by reigneil** [rathena/rathena#419]
on official server pRO, you cannot hit hidden(SC_HIDING) target using this skill. is this behavior change on kRO?

**Comment by joelolopez** [comment]
i notice that too, i can detect phreeoni using magnum break

**Comment by Playtester** [comment]
From what I know on officials only all earth-elemental skills can hit hidden targets (though some skills are defined earth-elemental and still do unique damage because they are misc skills).
I'll run a test, though.

**Comment by Playtester** [comment]
Confirmed the issue. Magnum Break does NOT hit hidden targets on officials.

**Comment by reigneil** [comment]
if we add here SD_ANIMATION fix the can hit target as well as the animation problem something like this...
	case SM_MAGNUM:
	case MS_MAGNUM:
		if( flag&1 ) {
			//Damage depends on distance, so add it to flag if it is > 1
			skill_attack(skill_get_type(skill_id), src, src, bl, skill_id, skill_lv, tick, flag|SD_ANIMATION|distance_bl(src, bl)); //must not hit hidden target
		}
		break
