### ISSUE TITLE
Hatch Pet

### ISSUE THREAD

**Issue by siriousb** [rathena/rathena#4190]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/a3fc44ef8aecf55789165b18dd64aa36ad8ecbac
* **Client Date**: 2018-09-19aRagexe
* **Server Mode**: RE
* **Description of Issue**: simply the window hatching the pets eggs does not close after you select the pet's egg.

if using a client RE it works normally.

  * Expected Result: Hatch window close after select pet egg do hatch.
  * How to Reproduce: 
Use `@item 9001`.
Use `@hatch`.
Select pet egg, click 'ok' to hatch.

If you use hatch and selecting but not pressing 'ok', can you drop pet egg, causing error on map_server too.

**Comment by sader1992** [comment]
please show us the error in the map-server

**Comment by siriousb** [comment]
@sader1992 Yes know, but i said 2018-09-19aRagexe, 20180620RE are working, but in 2018-09-19aRagexe are buged.

**Comment by Hope8888** [comment]
I have same issue.
**Client Date**: 2018-09-19aRagexe
