### ISSUE TITLE
Genetic Homunculus S[Summon Legion] skill issue

### ISSUE THREAD

**Issue by reigneil** [rathena/rathena#420]
the issue here are its summons are useless which cannot hit monsters.
which then i realize that there are not much data of it in mob_db.txt /sob
// Homunculus S Summons
2158, 2159, 2160

**Comment by joelolopez** [comment]
confirm

**Comment by aleos89** [comment]
Many monsters need to be updated, including those 3.

**Comment by aleos89** [comment]
Not so much a skill issue, but a mob_db issue. :)
