### ISSUE TITLE
Royal Cooking Kit

### ISSUE THREAD

**Issue by Questune09** [rathena/rathena#4206]
* **rAthena Hash**: 

* **Client Date**:  2018-09-19a

* **Server Mode**:  Renewal

* **Description of Issue**: 
  * Result:  When you use the Royal Cooking kit item with all the requirements on your bag it doen't show any items on the list. 
![image](https://user-images.githubusercontent.com/29746866/59155148-ae548880-8ab5-11e9-960a-a800eaf278b9.png)

  * Expected Result:  it should be appeared something inside the list.
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Playtester** [comment]
Do you have the corresponding cookbook?

**Comment by Questune09** [comment]
Thank you i forgot that book.
