### ISSUE TITLE
About addrid and warp crash

### ISSUE THREAD

**Issue by chishen912** [rathena/rathena#4208]
* **rAthena Hash**: 339e6c6

* **Client Date**: 20180620e

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: When addrid party character and warp the other map, the map-server will possibly crash. 
Those are four times crash dump record. About once a day.
I don't know why warp party character will make map-server crash. 
![image](https://user-images.githubusercontent.com/51664122/59206389-6b8ad180-8bd7-11e9-9240-92e0e50502c9.png)
![image](https://user-images.githubusercontent.com/51664122/59206467-8cebbd80-8bd7-11e9-8539-8bd0df5f33dd.png)
![image](https://user-images.githubusercontent.com/51664122/59206505-a2f97e00-8bd7-11e9-9a5e-d208fd15400e.png)
![image](https://user-images.githubusercontent.com/51664122/59206549-bdcbf280-8bd7-11e9-903a-5cd2c67fab0f.png)

* **Modifications that may affect results**:

**Comment by Atemo** [comment]
Do you have a npc script sample to reproduce the crash?

**Comment by chishen912** [comment]
@Atemo 

Map-server will crash when addrid party character to instance_enter or warp the other map.
But not always crash. About once a day.

My OctopusCave script:
instance_enter
mal_dun01,153,237,5	script	Weird Entrance	844,{
	set .@party_id,getcharid(1);
	set .@md_name$,"Octopus Cave";
	if (!.@party_id) {
		mes "[Starfish]";
		mes "You alone is powerless, hehe!";
		mes "Better get someone to help you out.";
		mes "Make a party, and come back later.";
		close;
	}
	if (is_party_leader() == false) {
		mes "[Starfish]";
		mes "Where is your leader, hehe.";
		mes "I don't talk to some random people.";
		mes "Bring your boss to me.";
		close;
	}
	if (instance_create(.@md_name$) < 0) {
		mes "[Starfish]";
		mes "Party name is... "+getpartyname(.@party_id)+".";
		mes "Party leader is... "+strcharinfo(0)+".";
		mes "^0000ff"+.@md_name$+"^000000, I cannot open now, hehe.";
		mes "Now is not the time, please wait.";
		close;
	}
	sleep2 1000;
	addrid(2,0,.@party_id);
	set .@playtime, checkquest(4197,PLAYTIME);
	if (.@playtime == 0 || .@playtime == 1) {
		end;
	}
	if (BaseLevel < 100) {
		end;
	}
	if (.@playtime == 2) erasequest 4197;
	switch(instance_enter("Octopus Cave")) {
	case IE_OTHER:
	case IE_NOINSTANCE:
	case IE_NOMEMBER:
	case IE_OK:
		close;
	default:
		mes "[Starfish]";
		mes "Shhh... Weird aura is";
		mes "coming from that entrance.";
		mes "Big trouble is waiting, if you go in now.";
		close;
	}
}

Character kill the Disgusting Octopus and addrid party character to warp map "mal_dun01".
1@cash,2,2,0	script	oct_boss_con	-1,{
	end;
OnInstanceInit:
	donpcevent instance_npcname("oct_boss_con")+"::OnDisable";
	end;
OnDisable:
	disablenpc instance_npcname("oct_boss_con");
	end;
OnEnable:
	enablenpc instance_npcname("oct_boss_con");
	donpcevent instance_npcname("oct_boss_foot")+"::OnEnable";
	monster instance_mapname("1@cash"),199,188,"Disgusting Octopus",2194,1,instance_npcname("oct_boss_con")+"::OnMyMobDead";
	end;
OnMyMobDead:
	set .@map$, instance_mapname("1@cash");
	if (mobcount(.@map$,instance_npcname("oct_boss_con")+"::OnMyMobDead") < 1) {
		mapannounce .@map$,"Disgusting Octopus : That's it for the today! Next time, I will play with you badly!",bc_map,"0xFFFF00";
		donpcevent instance_npcname("oct_boss_foot")+"::OnDisable";
		donpcevent instance_npcname("oct_boss_con")+"::OnDisable";
		addrid(2,0,getcharid(1));
		getmapxy(.@ipmapname$,.@ipmapx,.@ipmapy,BL_PC,strcharinfo(0));
		explode(.@exp_ipmapname$,.@ipmapname$,"@");
		if (.@exp_ipmapname$[1]=="cash") {
			sleep2 3000;
			warp "mal_dun01",153,233;
			sleep2 1000;
			if (instance_id()) instance_destroy instance_id();
		}
		end;
	}
	end;
}

**Comment by Atemo** [comment]
Did you find the culprit? I couldn't reproduce
