### ISSUE TITLE
Suggestion Make setrandomoption accept array.

### ISSUE THREAD

**Issue by Litro** [rathena/rathena#4209]
* **rAthena Hash**: -
* **Client Date**: -
* **Server Mode**: -
* **Description of Issue**: -
  * Result: -
  * Expected Result: -
  * How to Reproduce: -
  * Official Information: -

* **Modifications that may affect results**: -
```
for (.@i = 0; .@i < MAX_RAND_OPT; .@i++)
	setrandomoption(.@part, .@i, .@opt, .@val, .@param);
```

into

```
setarray .@opt, RDMOPT_VAR_STRAMOUNT, RDMOPT_VAR_AGIAMOUNT, RDMOPT_VAR_INTAMOUNT;
setarray .@val, 1, 10, rand(9)+3;
setarray .@param, 0,0,0;
setrandomoption(.@part, .@i, .@opt, .@val, .@param);
```

**Comment by Atemo** [comment]
I'm afraid that the changes on the command would broke the old compatibility for the same results. I will go ahead and close this.
