### ISSUE TITLE
tension relax buff icon

### ISSUE THREAD

**Issue by joelolopez** [rathena/rathena#421]
tension relax icon buff disappears even you're still sitting.

**Comment by reigneil** [comment]
irowiki state that the duration last, as long as you don't standup and receive damage
http://irowiki.org/wiki/Relax
while in jRO additional condition are use skill, equipment change and use item.
http://mohige.sakura.ne.jp/knight/
Tension relax (Tension Relax)
    Prerequisite skills: HP recovery improvement Lv10, endure Lv3
    Type: Active / auxiliary
    Abbreviation: TR 

By easing the muscle tension, to increase the recovery rate of HP.

    And consume SP15 at the time of use, to sit with the shout of "tension relax !!"
    HPR invocation is three times (every 3.33 seconds) and natural recovery become every S1.55 seconds, SP recovery as usual
    Overweight during any possible recovery in the normal sitting the same effect, but SP does not recover
    Weight normal recovery rate is 50% or more (natural recovery, HPR together) because it is, there is no too much meaning to the type of man to gain the recovery agent to basically overweight.
    Item use, it is released, and equipment change, stand, or attacked
        When used in endure state, while it has the effect of sitting even under attack disappear 
    It is not effective in the poison state 

Comment

        Feeling can be about 9% recover HP in 10 seconds, 110 seconds to complete recovery from HP1 (usually sits 3% / 10s, falling about 2.5% / 10s)
        When the spear vit to the AB hunting, and extensible significantly the stay time if diligently so as to restore the HP up to 25% last minute in TR
        Not required if the pair and 2PC environment often.
and also both of them saying it is useable while you are overweight but in normal regen.
