### ISSUE TITLE
Aspercio Scroll not working

### ISSUE THREAD

**Issue by Questune09** [rathena/rathena#4216]
* **rAthena Hash**: 

* **Client Date**: 20180620

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result:  Aspercio scroll is not working even you have an holy water on your bag.
  * Expected Result:  it should be when you click the aspecio scroll it will trigger a skill and you need to target it to your self after using.
  * How to Reproduce:  get an aspecio scroll and a holy water, then use the aspercio scroll
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Questune09** [comment]
sorry i forgot the item is this > https://www.divine-pride.net/database/item/12217/lv5-aspersio-scroll

**Comment by yoonjunho1994** [comment]
`12217,Aspersio_5_Scroll,LV5 Aspersio Scroll,11,2,,10,,,,,0xFFFFFFFF,63,2,,,,,,{ if(countitem(523)>0) { skilleffect "PR_ASPERSIO",0; sc_start SC_ASPERSIO,180000,5; delitem 523,1; } else dispbottom "You dont have any Holy Water.",0xff0000; },{},{}
` just test its working good i just change the item type and add some text

**Comment by Questune09** [comment]
thank you not working on my side when i click the item nothing happens

**Comment by sader1992** [comment]
![image](https://user-images.githubusercontent.com/5981261/59887698-a4d7f400-93c4-11e9-9d3f-7328e48b3ed9.png)

so the issue is invalid
however if you want to edit it to work as a skill on others
change the item type to 11 and edit the item script to
```cs
---------------------------------------

*itemskill <skill id>,<skill level>{,<keep requirement>};
*itemskill "<skill name>",<skill level>{,<keep requirement>};

This command is meant for item scripts to replicate single-use skills in usable
items. It will not work properly if there is a visible dialog window or menu.
If the skill is self or auto-targeting, it will be used immediately; otherwise a
target cursor is shown.

If <keep requirement> parameter is set to true, the skill's requirements will be checked.
By default, the requirements for item skills are not checked, and therefore the default value is false.

// When Anodyne is used, it will cast Endure (8), Level 1, as if the actual
// skill has been used from skill tree.
605,Anodyne,Anodyne,11,2000,0,100,,,,,10477567,2,,,,,{ itemskill 8,1; },{}

// When Sienna_Execrate_Scroll_1_5 is used, it will cast Sienna Execrate Level 5 and consume 2 Red_Gemstones.
23194,Sienna_Execrate_Scroll_1_5,Level 5 Sienna Execrate,11,10,,10,,,,,0xFFFFFFFF,63,2,,,,,,{ itemskill "WL_SIENNAEXECRATE",5,true; },{},{}

---------------------------------------
```

**Comment by Questune09** [comment]
Thank you so much sader, i got it. the item script should be
```12217,Aspersio_5_Scroll,LV5 Aspersio Scroll,11,2,,10,,,,,0xFFFFFFFF,63,2,,,,,,{ if(countitem(523)>0) { skilleffect "PR_ASPERSIO",0; sc_start SC_ASPERSIO,180000,5; delitem 12217,1; delitem 523,1; } else dispbottom "You dont have any Holy Water.",0xff0000; },{},{}```

there is missing ,1; at delitem 12217; before
