### ISSUE TITLE
Overed Boost

### ISSUE THREAD

**Issue by Questune09** [rathena/rathena#4217]
* **rAthena Hash**: 

* **Client Date**:  20180609

* **Server Mode**:  Renewal

* **Description of Issue**: 
  * Result:  When i Used Overed Boost My Homunculus Hunger Become 0
  * Expected Result:  should not affect the hunger of homunculus
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
The skill should take 50% of max hunger, which is 100. It is currently capping it to 1 to keep it falling below. If this has changed on kRO, can you give me a video or change log?
