### ISSUE TITLE
lord knight berserk/frenzy

### ISSUE THREAD

**Issue by joelolopez** [rathena/rathena#422]
berserk or frenzy skill removes 2hand quicken buff.

**Comment by reigneil** [comment]
if it is renewal. i think it doesn't stack.
renewal frenzy info:
http://irowiki.org/wiki/Frenzy
pre-renewal frenzy info:
http://irowiki.org/classic/Frenzy

**Comment by aleos89** [comment]
Correct, Two Hand Quicken does not stack in renewal.
