### ISSUE TITLE
Divine guard effect not working

### ISSUE THREAD

**Issue by Questune09** [rathena/rathena#4222]
* **rAthena Hash**: 

* **Client Date**:  20180619

* **Server Mode**:  renewal
 

* **Description of Issue**: 
  * Result:   The item doesnt follow the description below
![image](https://user-images.githubusercontent.com/29746866/59967695-4d6e8b00-9560-11e9-9295-3e61f965fa5e.png)
  * Expected Result:  Adds a 100% chance of casting Level 2 Tuna Belly on the user when using Genesis Ray.
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Questune09** [comment]
anyone can confirm this?

**Comment by teededung** [comment]
@Questune09 this effect only for iRO, kRO does not have this effect at this time

**Comment by aleos89** [comment]
As @teededung stated, this is an iRO buff. Since this item isn't iRO exclusive, the behavior will follow kRO's.
