### ISSUE TITLE
Improvement for Battleground On Death Event

### ISSUE THREAD

**Issue by akiyamamio16** [rathena/rathena#4233]
* **rAthena Hash**:  32525bad55cc5b715f2ad259b6310560089028ed

* **Client Date**:  2018-06-20eRE

* **Server Mode**:  both

* **Description of Issue**:  Improve On Death Event for Battlegrounds
  * Result:  OnDeathEvent doesnt have killerrid which makes player abuse suicide to trigger On Death Event.
  * Expected Result: Same as OnPCDieEvent, should give killerrid so that we can track suicides.
  * How to Reproduce: Use Poison Bottle to kill yourself.
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by Atemo** [comment]
`killerrid` is called when the player dies whatever the event. `killerrid` is 0 when there is no source object - so check it's 0 when the player suicides, for example.
