### ISSUE TITLE
Euphy's WoE controller sql queries aren't compatible with current schema

### ISSUE THREAD

**Issue by burningFlower74** [rathena/rathena#4235]
* **rAthena Hash**: 

not important
* **Client Date**: 
not important

not important
* **Server Mode**: 
not important

not important
* **Description of Issue**: 

 as you can see here https://github.com/rathena/rathena/blob/master/npc/custom/woe_controller.txt#L178 the npc queries the mail table and tries to insert a nameid name to the mail table, but the problem is that items are now stored in mail_attachments.

  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment]
Actually using sql queries for something like this is a bad idea anyway and should be refactored to the newly introduced `mail` script command.
