### ISSUE TITLE
Achievement amount reward

### ISSUE THREAD

**Issue by RadianFord** [rathena/rathena#4236]
* **rAthena Hash**: 32525bad55cc5b715f2ad259b6310560089028ed

* **Client Date**: 

* **Server Mode**: Pre-renewal

* **Description of Issue**: If you put an exact amount or change the value of the amount of the reward item in achievementdb.
  * Result: It should work as it is implemented, as official.
  * Expected Result: It didn't work, the item that players are getting an apple.
  * How to Reproduce: Simply add a specific amount on
```
Reward:
  ItemID: 501
  Amount: 50
```
  * Official Information:
  

* **Modifications that may affect results**: 
  
  
![Untitled](https://user-images.githubusercontent.com/9658425/60756470-5cb6f500-9fb2-11e9-8463-cb79028581dd.png)

**Comment by Lemongrass3110** [comment]
Could you maybe update your issue a little, I am having a hard time trying to understand what you are saying. In some parts you are talking about the amount being a problem, in others you talk about people getting apples(which is simply what you put into the database).

**Comment by RadianFord** [comment]
@Lemongrass3110 the issue is when Amount is more than 1. Im getting warnings saying that there's no ID# of which was the amount I put.

for example:
```
ItemID: 501
Amount: 50
```
when achievement completed. warning will show up like this
```
[Warning]: itemdb_search: Item ID 50 does not exists in the item_db. Using dummy data.
```
![screenWickedRO039](https://user-images.githubusercontent.com/9658425/60774282-f079e580-a0c6-11e9-956f-cb88437ec5f7.jpg)

**Comment by Lemongrass3110** [comment]
Thanks for making it clear now!
