### ISSUE TITLE
Overbrand skill (As well as walls)

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#4237]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/9aa5f7d8345d9d89ec9e8b44060e92703f3d43b8

* **Client Date**: 20180621

* **Server Mode**: RE

* **Description of Issue**: Affecting targets beyond the wall.

  * Result: 
  * Expected Result: It should not affect targets other than walls.
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Overbrand's behavior changed in #5517. It no longer attacks through walls.
