### ISSUE TITLE
Map Server Crash

### ISSUE THREAD

**Issue by Anjuts** [rathena/rathena#4238]
![cra](https://user-images.githubusercontent.com/13416489/60762889-813acc00-a09b-11e9-9f54-6d819562f3f0.png)

[skill.zip](https://github.com/rathena/rathena/files/3365209/skill.zip)

crashed please help

**Comment by yashimwong** [comment]
Please edit your issue to follow the template.

**Comment by Lemongrass3110** [comment]
No input for 7 days.
