### ISSUE TITLE
bug homunculo hlif

### ISSUE THREAD

**Issue by Miengo2** [rathena/rathena#424]
primero disculparme, por mi inglés

un usuario me reporto un bug con uno de los homunculo
ID del homunculo: 6013
El bug consiste es que la skill HLIF_CHANGE no funciona de manera correcta
se supone que la skill deberia pasar el daño normal[atk], por el daño magico[matk[, pero al usar la skill se reduce el daño que produce
server mode all renewal

first apologize for my English

a user reported a bug to me one of the homunculus
Homunculus ID: 6013
The bug is that the skill is HLIF_CHANGE not work properly
it is assumed that the skill should pass the normal damage [ATK], by magic damage [matK [, but when using the skill the damage caused is reduced
server mode all renewal

**Comment by Miengo2** [comment]
You need information

The error occurs in the following circumstances, I am with my homunculus killing my homunculus takes 700 damage, with stats, 70 ATK, MATK 120 [for example, are not 100% accurate figures] uses the skill, mental charge, this skill should use MATK [120MATK] the damage done is lower

**Comment by Akkarinage** [comment]
I need official source info, not more info on your error.

**Comment by cydh** [comment]
my test with ATK 86, MATK 322.
before using the skill, the damage is 260~, after the skill is 600~

**Comment by Miengo2** [comment]
that's the Hercules emulator, I also perform the test on
