### ISSUE TITLE
Homun Mental Charge skill

### ISSUE THREAD

**Issue by Questune09** [rathena/rathena#4241]
* **rAthena Hash**: 

* **Client Date**:  20190602

* **Server Mode**:  Renewal

* **Description of Issue**: 
  * Result:  Homun doesn't learn the last skill mental charge skill.
  * Expected Result:  It supposed to be at evolve lif, The homun already evolve and reach level 99 and the mental charge skill doesn't learned.
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
According to the database it requires 910 intimacy. What is your intimacy level?

**Comment by aleos89** [comment]
I'll assume this was resolved through the intimacy level.
