### ISSUE TITLE
Assassin ASPD BUG

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#4244]
* **rAthena Hash**: d80e111

* **Client Date**: 20170517RE

* **Server Mode**: RENEWAL

* **Description of Issue**: 
  * Result:  Negative Value Using Angra Manyu
  * Expected Result:  Stuck on Maximal ASPD
  * How to Reproduce:  Using Equiped Angra Manyu check Screnshot

![screenRENEWAL104](https://user-images.githubusercontent.com/8316103/61178307-bc497c00-a614-11e9-94d0-27e0a24226a9.jpg)
![screenRENEWAL105](https://user-images.githubusercontent.com/8316103/61178308-bc497c00-a614-11e9-826d-df641177ad94.jpg)
![screenRENEWAL106](https://user-images.githubusercontent.com/8316103/61178309-bce21280-a614-11e9-82a8-12caf326c189.jpg)

  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Stingor** [comment]
it's because of is weapon type.

**Comment by Playtester** [comment]
Not a bug, all GMs in RO are High Priests. Equipping Angra Manyu on an Assassin on Aegis has the same effect.
