### ISSUE TITLE
Name UTF8(Thai) to ???? 

### ISSUE THREAD

**Issue by hnomkeng** [rathena/rathena#425]
i need help please.
![untitled-7](https://cloud.githubusercontent.com/assets/9112684/7516438/7c22f2bc-f4f9-11e4-98d4-d42f369fbee7.jpg)
![untitled-5](https://cloud.githubusercontent.com/assets/9112684/7516382/20072ce6-f4f9-11e4-85d7-55945f891f3d.jpg)
![untitled-3](https://cloud.githubusercontent.com/assets/9112684/7516409/45b4e60e-f4f9-11e4-8f55-4bd3757c0d44.jpg)
![untitled-1](https://cloud.githubusercontent.com/assets/9112684/7516412/4f145fcc-f4f9-11e4-8389-d5eb85d13cd4.jpg)

**Comment by anacondaqq** [comment]
look at the type of table and the database connection.
+ some langtype / servicetype usually works with 1251 / 1252, not with UTF-8

**Comment by reigneil** [comment]
did you try changing the servicetype to your native language?
https://rathena.org/wiki/Clientinfo.xml

**Comment by hnomkeng** [comment]
i using langtype 5
![untitled-10](https://cloud.githubusercontent.com/assets/9112684/7517443/3b31bc4c-f4ff-11e4-9f94-585a324b255e.jpg)

**Comment by reigneil** [comment]
try what @anacondaqq said edit your table then go to table option and change charset from utf-8 to cp1251 or cp1252

**Comment by anacondaqq** [comment]
@hnomkeng
1. Make backup first (beacuse these changes can damage your database)
2. https://github.com/rathena/rathena/blob/master/conf/inter_athena.conf#L17 uncomment, and change to 
> default_codepage: cp1252
> <servicetype>thai</servicetype>
> <servertype>sakray</servertype> if you use game exe <= 2010, or ragray if  > 2010
> <langtype>5</langtype>
3. create new account on these settings
4. ???? 
5. all must works.

**Comment by aleos89** [comment]
This isn't a server bug, it's just a configuration issue.
