### ISSUE TITLE
General Helmet item script not working

### ISSUE THREAD

**Issue by Questune09** [rathena/rathena#4252]
* **rAthena Hash**: 

* **Client Date**: 

* **Server Mode**:  Renewal
 

* **Description of Issue**: 
  * Result:  General Helmet item script not working even on by dropping Treasure chest when equipped
  * Expected Result:  it should drop treasure chest when killing dragon type monsters
  * How to Reproduce:  Equip General Helmet and kill more dragon monsters
  * Official Information: https://www.divine-pride.net/database/item/18555/general-helmet
  

* **Modifications that may affect results**:

**Comment by cahya1992** [comment]
already tested it and working

Just increase rate drop 

> bonus3 bAddMonsterDropItem,7444,RC_Dragon,2; 

to

bonus3 bAddMonsterDropItem,7444,RC_Dragon,200;

**Comment by Questune09** [comment]
weird things i already set it to 500 to make sure that the rate is high. but still the same.

**Comment by cahya1992** [comment]
i try with monster zhu po long (Mob-ID#1514) and working

**Comment by Questune09** [comment]
Thanks the rate it self is very low, thats why. i confirmed it after killing 200 of that monster
