### ISSUE TITLE
Safe to 10 Certificate

### ISSUE THREAD

**Issue by Questune09** [rathena/rathena#4253]
* **rAthena Hash**: 

* **Client Date**: 

* **Server Mode**:  Renewal

* **Description of Issue**: 
  * Result:  When using `@item 6457` it gives +5 safe refine instead of +10 safe refine ticket
  * Expected Result:  This should be +10 safe refine ticket not +5
  * How to Reproduce: 
  * Official Information: https://www.divine-pride.net/database/item/6457/safe-to-10-certificate
  

* **Modifications that may affect results**:

**Comment by secretdataz** [comment]
It's +5 ticket on kRO
```lua
	[6457] = {
		unidentifiedDisplayName = "방어구 5 제련 보장권",
		unidentifiedResourceName = "쿠폰",
		unidentifiedDescriptionName = {
			"^8B4513프론테라^000000의 ^0000FF제련 연구가^000000를 통해 ^006400착용한 방어구의 제련도를 5단계로 강화^000000할 수 있습니다. -1회 한정-",
			"무게 : ^7777770^000000"
		},
		identifiedDisplayName = "방어구 5 제련 보장권",
		identifiedResourceName = "쿠폰",
		identifiedDescriptionName = {
			"^8B4513프론테라^000000의 ^0000FF제련 연구가^000000를 통해 ^006400착용한 방어구의 제련도를 5단계로 강화^000000할 수 있습니다. -1회 한정-",
			"무게 : ^7777770^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false
	},
```
