### ISSUE TITLE
HP bonuses formula incorrect for pre-Renewal

### ISSUE THREAD

**Issue by Indigo000** [rathena/rathena#4264]
* **rAthena Hash**: Latest

* **Client Date**: 2017-06-14

* **Server Mode**: Pre-Renewal

* **Description of Issue**: 
  * Result:  In a similar fashion to the Heal formula, the HP bonuses formula is also wrong for pre-RE. In 96443cd71073ad752c65d4d6705a61ec1747735f some changes were made which resulted in a combination such as Tao Gunka with Berserk/Frenzy not working correctly anymore. On rAthena, it applies one of them on the Base HP only.

As reported by one of our players, Base HP = 10969. With only Berserk = 32907. With only Tao Gunka = 21938. With both = 43878. This should be 65814.

We confirmed this on our 11.3 Aegis server. Base HP was 10670. With Berserk = 32010. With only Tao Gunka = 21340. With both = 64020.
  * Expected Result: Berserk applies to HP including bonuses, not on base.
  * How to Reproduce:  Test Tao Gunka + Berserk/Frenzy on Pre-Renewal Aegis.
  * Official Information: Aegis 11.3.
  

* **Modifications that may affect results**:

**Comment by Daegaladh** [comment]
Posting my own tests so we have everything in the same place.
```MaxHP: 10869
MaxHP + Tao Gunka card: 21738
MaxHP + Frenzy: 32607
MaxHP + Gold Pill: 11412
MaxHP + Tao Gunka card + Gold Pill: 22281
MaxHP + Frenzy + Gold Pill: 34237
MaxHP + Tao Gunka card + Frenzy: 65214
MaxHP + Tao Gunka card + Gold Pill + Frenzy: 66844```

So it should work like this:
```((basehp + STATUS_BONUS_FIX %) + (bMaxHPrate of basehp )) + STATUS_BONUS_RATE %```
MaxHP + Tao Gunka card + Gold Pill + Frenzy
````((10869 + 100%) + (5% of 10869)) + 200%```
