### ISSUE TITLE
Ninja's Shadow Slash should always be melee (pre-RE)

### ISSUE THREAD

**Issue by Indigo000** [rathena/rathena#4265]
* **rAthena Hash**: Latest

* **Client Date**: 2017-06-14

* **Server Mode**: Pre-Renewal

* **Description of Issue**: 
  * Result: Not sure if this is also the case for Renewal, but in pre-Renewal Aegis, Shadow Slash is always considered melee while on rAthena it's always considered ranged. Tested on Aegis 11.3, so either the ranged attack is a late pre-RE change or it's just wrongly implemented on rA right now. On our test, no matter the distance, Shadow Slash would miss a Plant monster when it was in Safety Wall and it would hit the Plant when it was in Pneuma.
  * Expected Result: Shadow Slash should always be melee instead of ranged.
  * How to Reproduce:  Test on latest pre-RE Aegis.
  * Official Information:Aegis 11.3
  

* **Modifications that may affect results**:

**Comment by Playtester** [comment]
Keep in mind that range behavior depends on if a player or monster uses the skill and the actual range of the skill defined in Aegis. So if it's considered melee it's likely that its range is lower in Aegis than it is defined in rAthena.

Right now its range is 7-15 depending on skill level so it's considered ranged, but it's likely that its range is 3 or lower server-side and the range of 7-15 is only defined in the client (assuming you can really use it at range). As using the skill first makes you teleport to the target, the range check for the actual attack wouldn't fail, which might be how it works on Aegis.

Of course we could also just hardcode an exception (I can't test it myself so can't confirm report).
