### ISSUE TITLE
Issue on Achievement

### ISSUE THREAD

**Issue by RadianFord** [rathena/rathena#4266]
* **rAthena Hash**: 17f32a175629929cd66602683b8e1a8f60d9e100

* **Client Date**: 2017-06-14bRagexeRE

* **Server Mode**: Pre-renewal

* **Description of Issue**: this message shows up `[Error]: intif_parse_achievementsave: Failed to save achievement(s)` and `[Error]: achievement_add: Character 129 already has achievement 240004.`
Randomly, Its not supposed to trigger when player got that achievement already. It didn't happen before this update https://github.com/rathena/rathena/commit/ac46920e73819662811573253d9b22592e8ad985

**Comment by RadianFord** [comment]
Update: (07/29/2019 20:38:21) [ Error ] : achievement_add: Character 5 already has achievement 240004. it repeats even the player finished the achievement.

**Comment by aleos89** [comment]
Fixed in 783009d.
