### ISSUE TITLE
Crusader[Auto Guard] skill issue

### ISSUE THREAD

**Issue by reigneil** [rathena/rathena#427]
1. when you are sitting and then suddenly activated auto guard by damage you are still remain sitting this is also happen to devoted party member who are sitting and struck by damage with or without auto guard.
2. when you are already in auto guard and then cast devotion to party member, auto guard will not transfer its status to party member but when you are devoted to your party member first and then cast auto guard this time it will transfer its status.

are this things intended?

**Comment by hnomkeng** [comment]
check range skill devotion a to b 11 range ?

**Comment by aleos89** [comment]
1. Seems like we should force stand when the player is hit.
2. We pass the SCSTART_NOAVOID and SCSTART_NOICON flags for Auto Guard, Defender, Reflect Shield, and Endure when Devotion is enabled on a player. So when Devotion is enabled, we force those skills (the noavoid) onto the player but they don't get the icon of the skill (the noicon).
