### ISSUE TITLE
MDEF2

### ISSUE THREAD

**Issue by dragonis1701** [rathena/rathena#4271]
* **Server Mode**:  Pre-Renewal
* **Description of Issue**: While messing around in the src, I noticed this bit of code for MDEF2 calculations done for Pre-renewal:
// Mdef2
	stat = status->mdef2;
	stat += status->int_ + (status->vit>>1);
	status->mdef2 = cap_value(stat, 0, SHRT_MAX);

I can't find anywhere that vit is supposed to influence MDEF2. Is this a mistake?

**Comment by Playtester** [comment]
Pretty sure this is correct. Vit reduced magic damage in pre-re at least.

**Comment by mrjnumber1** [comment]
It is correct. Both from memory and even a double check that it does 

```
__int16 CPC::GetStatusMagicDef()
{
  if (GetEffective(EFST_BERSERK, 0) <= 0)
    return 0;
  return (GetIntValue() + GetVitValue() / 2) * m_characterInfo.extMDEFPercent / 100;
}
```
