### ISSUE TITLE
Compile warning for lastest git version

### ISSUE THREAD

**Issue by pigati23** [rathena/rathena#4274]
* **rAthena Hash**: 3dd388ac66580e72f56826d142ef69d2525188b7

* **Client Date**:  Irrelevant

* **Server Mode**:  pre-re

* **Description of Issue**: 
After setting the emulator to pre-re, i deactivated the Pincode system and i deactivated some features, such as privateairship, attendance, achievement & roulette.
Then I compiled the emulator for the first time and this strange warning appears.
![unknown](https://user-images.githubusercontent.com/39913847/62072164-ac7c8b00-b203-11e9-8817-dc4a9fbd3e4e.png)

  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Fixed in 90d603d.
