### ISSUE TITLE
int_storage.cpp issue

### ISSUE THREAD

**Issue by RadianFord** [rathena/rathena#4286]
* **rAthena Hash**: 3dd388ac66580e72f56826d142ef69d2525188b7

* **Client Date**: 2017-06-14bRagexeRE

* **Server Mode**: Pre-renewal

* **Description of Issue**: at int_storage.cpp:440 - `robe`='0'
  * Result: [ SQL Error ] : DB error - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '`robe`='0'' at line 1
  * Expected Result: It only happens 1 time, im still checking the logs each day.
  * How to Reproduce: Im not sure how to re-produced it, i just saw it on my char-server.log
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment]
Could you please run this on your database and post the result?
```
describe `char`;
```

**Comment by RadianFord** [comment]
Here you go @Lemongrass3110 
![Untitled](https://user-images.githubusercontent.com/9658425/73132129-888bdd80-3fcb-11ea-953c-b30b302efe74.png)

**Comment by aleos89** [comment]
I'm assuming this issue is no longer present? The structure of your `char` table looks fine.

**Comment by RadianFord** [comment]
> I'm assuming this issue is no longer present? The structure of your `char` table looks fine.

I never encounter this issue on my latest trunk. I'll close this and create new if the same thing happens in the future.
