### ISSUE TITLE
class 3rd cann't aura

### ISSUE THREAD

**Issue by ideaclub** [rathena/rathena#429]
Sorry. I can speak easy.

**Comment by Miengo2** [comment]
? 3rd class si tiene aura

**Comment by ideaclub** [comment]
Sorry. My Class 2 have aura. Class 3rd don't have aura in Client 2013-15-22
rAthenaSVN17723

**Comment by hnomkeng** [comment]
Class 3rd system rewenal ?

**Comment by ideaclub** [comment]
PreRe

**Comment by aleos89** [comment]
2013-15-22 isn't even a real date (assuming typo). Please read this topic: https://rathena.org/board/topic/86650-officially-supported-client-versions/ on supported clients by rAthena.

You will need to adjust the max_lv and aura_lv configs in conf/battle/client.conf to reflect your max level in your server.
