### ISSUE TITLE
Geffen Magic tournament Error

### ISSUE THREAD

**Issue by Questune09** [rathena/rathena#4293]
* **rAthena Hash**: 

* **Client Date**:  2019

* **Server Mode**:  Renewal

* **Description of Issue**: 
  * Result:  Geffen Magic tournament crashed after register on the receptionist NPC. and some NPC getting some errors on console, im using rAthena latest revision.

![image](https://user-images.githubusercontent.com/29746866/62592133-9ad26c00-b904-11e9-8ab5-dcfb494dd8fe.png)

  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Questune09** [comment]
after registration.
![image](https://user-images.githubusercontent.com/29746866/62592166-c05f7580-b904-11e9-9304-a0e28a6a6e72.png)

**Comment by Atemo** [comment]
Not able to reproduce.
At `1@gef`
Source `Receptionist#1_0et`
`NPC not in an instance`
someone warped on the original map  `1@gef` and triggered the NPCs
