### ISSUE TITLE
ASPD renewal

### ISSUE THREAD

**Issue by Miengo2** [rathena/rathena#430]
the ASPD obtained in Server [ rathena ] is smaller than is the official , the we have tested under the same conditions
the conditions were , in comparison aspd server and officer with unequipping char, result in greater official aspd

**Comment by zackdreaver** [comment]
https://rathena.org/board/topic/63256-renewal-aspdkro-based-need-help/

**Comment by MrAntares** [comment]
iRo, euRo, pRo, jRo, ruRo, bRo is NOT official. If you have kRo evidence of a different ASPD, then show us, otherwise, invalid.

**Comment by Miengo2** [comment]
OK, I thought it was part of what iro called " Official Server," on my server I reported that aspd official server was different iro
Informs users of this my question
Thanks for the help
