### ISSUE TITLE
Cannon Spear - Bresenham's line pattern

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#4303]
* **rAthena Hash**: 
d80e111

* **Client Date**: 
2018-02-21bRagexeRE

* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result: Bresenham's line pattern is not aligned to the target, but always triggers facing the same way as shown on the image. That means that if you stand in a certain way to your target, it's impossible to hit it since the pattern is aligned wrong.
![CS](https://user-images.githubusercontent.com/12261601/63107983-30659f80-bf86-11e9-8f9f-e95fdf8d3f9b.png)

  * Expected Result: Bresenham's line pattern should be aligned accordingly to the target as being triggered and calculate the pattern accordingly around you with the facing-target direction instead.

  * How to Reproduce: Stand to the target as shown here for example: (basically within the white area of the Bresenham's line pattern)
![image png 901d8558b109965af3f1687922bdf192](https://user-images.githubusercontent.com/12261601/63108178-8df9ec00-bf86-11e9-9ab4-c7342fbd79f5.png)

  * Official Information:
https://irowiki.org/wiki/Cannon_Spear

* **Modifications that may affect results**: 
  none

**Comment by Playtester** [comment]
Irowiki is not really reliable information. When I last tested all "line" skills it worked exactly as it is implemented now.

See here: https://github.com/rathena/rathena/issues/658

**Comment by Everade** [comment]
Well... if it's aligned to the target, then it should always hit.
I checked your explanation but i still don't understand how it's possible that an aligned pattern isn't able to hit the target?!

You said
> Instead, they determine an AoE effect based on the direction between you and the target.

You also said
> It's interesting, because the monster you target might actually be on a cell that you can't even hit.

Are you talking about it being blocked by gat field setting or are you saying that the pattern can actualy be miss-aligned so the target is outside of the pattern?

Take a look at my screenshot:
- How could the pattern possibly miss the target if it has been aligned between you and the target?

**Comment by Playtester** [comment]
It's 8 directional, and there are cells that can never be in the AoE, you need to place yourself either horizontally, vertically or diagonally towards the target to hit it. Look at the linked issue, I actually showed Cannon Spear's AoE in a spreadsheet grid to visualize it.

**Comment by Everade** [comment]
@Playtester 
That's what my report was all about.

With aligning i understand that one of the 8 directions actualy points to the target your aiming at. **And the pattern then rotates accordingly around you.**

But if you say, not aligning the pattern to anything at all but always pointing to north, south, west, east, south-east, south-west, north-west, north-east.
Wtf Gravity... alright.

I just couldn't find a single person saying that you have to align your character with the fixed pattern to the target.  But good to know.

**Comment by Playtester** [comment]
Yeah, I found it strange too, but I literally tested every single cell on Aegis to see which ones are hit and which ones are not.
