### ISSUE TITLE
Cursed Spirit Quest

### ISSUE THREAD

**Issue by AzuraSkyy** [rathena/rathena#431]
The coordinates lhz_dun02 60 298 should be 60 293. Otherwise this step is not possible through that duplicate. Nothing major, but still a bug. Line 3443 I believe.

lhz_dun02,60,293,0	duplicate(#kiz02-1)	#kiz02-2	-1,3,3
lhz_dun02,267,278,0	duplicate(#kiz02-1)	#kiz02-3	-1,3,3
lhz_dun02,94,199,0	duplicate(#kiz02-1)	#kiz02-4	-1,3,3

**Comment by exneval** [comment]
well in Aegis itself, the coordinate is correct (60,298)

hiddenwarp "lhz_dun02" "#kiz02-2" 60 298 3 3

don't know if it's an official bug or not..
