### ISSUE TITLE
RODEX weight bug

### ISSUE THREAD

**Issue by voyfmyuh** [rathena/rathena#4316]
- rAthena Hash: Latest

- Client Date: 20180621

- Server Mode: Renewal

As in the case of video, when the weight of the item has exceeded 2000, it can be added without limit.

mail_attachment_weight: 2000

![u6y4c-k5gvu](https://user-images.githubusercontent.com/54499336/63649136-74b62400-c76c-11e9-8f02-ff3437acf6a8.gif)

https://youtu.be/K8Ijhr44QYU

**Comment by Lemongrass3110** [comment]
This limit is hardcoded into the client.
The message also comes from the client. The server would allow you to send more.
