### ISSUE TITLE
Instance Sarah and Fenrir Problem

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#4323]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/9aa5f7d8345d9d89ec9e8b44060e92703f3d43b8

* **Client Date**: 20180621

* **Server Mode**: RE

* **Description of Issue**: If you do the instance following the common model killing the side giants works fine. But if you go straight to Fenris on the top left without killing the giants, the instance can't continue.

  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**: 
  
  
maybe it's something related to this part:

```
// Fenrir left side, entrance
1@glast,47,270,0	script	#glast_event_7	HIDDEN_WARP_NPC,5,5,{
	end;
OnTouch:
	if (is_party_leader() == false)
		npctalk "Fenrith Fenrir: I would like your party leader to come and help me!", 'fenrir_3$;
	else {
		setpcblock PCBLOCK_NPC, true;
		disablenpc instance_npcname("#glast_event_7");
		npctalk "Fenrith Fenrir: You came! I was waiting!", 'fenrir_3$;
		sleep2 2000;
		npctalk "Fenrith Fenrir: We don't have much time! We have to go search for it now! Let's go in!", 'fenrir_3$;
		sleep2 2000;
		setpcblock PCBLOCK_NPC, false;
		if ('skip_left_part == 0) {// 5 mins have passed?
			donpcevent instance_npcname("#fenrir_left_final_2") + "::OnStop";
			disablenpc 'fenrir_3$;
			enablenpc 'fenrir_4$;
			enablenpc instance_npcname("#glast_event_9");
			warpparty 'map_glast$,41,348, getcharid(1), 'map_glast$,1,1;
		}
	}
	end;
}
```

**Comment by Atemo** [comment]
May you elaborate the steps to reproduce?

**Comment by Badarosk0** [comment]
The problem is in the command script "warpparty". It does not work the way it is in the script. Has there been a change in the command recently? @Atemo

**Comment by Atemo** [comment]
Do you still have the issue @Badarosk0 ? I didn't have a problem on the left part, using 2 characters. The characters were warped when the leader triggered the npc
`1@glast,47,270,0	script	#glast_event_7	HIDDEN_WARP_NPC,5,5,{`

**Comment by Badarosk0** [comment]
https://paste.in/raw/si7M5G
I modified it to work @Atemo
