### ISSUE TITLE
Mercenary Kill Count does not increase with player kills

### ISSUE THREAD

**Issue by Indigo000** [rathena/rathena#4329]
* **rAthena Hash**: 9b11301

* **Client Date**: 2017-06-14

* **Server Mode**: Pre-Renewal

* **Description of Issue**: 
  * Result:  Ever since 0f2dd7fcf0e498aec2d281b80e31fa5b0c6c68ec (from 2013!) when the Mercenary kill count was "cleaned up", kills by the Player no longer increase the kill count of the mercenary. According to several official sources, it should also count on player kills.
  * Expected Result:  Make mercenary kill count also increase on player kills.
  * How to Reproduce:  Kill a monster within the correct level range as a player.
  * Official Information: Could be something that was fixed later on on Aegis of course, but at least in 11.3 this was announced to work. http://www.playragnarok.com/news/updatedetail.aspx?id=85&p=8 https://irowiki.org/wiki/Mercenary_System
  

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment]
No idea why you blame 0f2dd7f, since this has nothing to do with the killing target. It only changes the attacker(src).
Did you confirm this on AEGIS or kRO? Or are you only quoting unreliable iRO?

**Comment by GMBoreas** [comment]
> No idea why you blame [0f2dd7f](https://github.com/rathena/rathena/commit/0f2dd7fcf0e498aec2d281b80e31fa5b0c6c68ec), since this has nothing to do with the killing target. It only changes the attacker(src).

Did you even bother checking the commit?

src->type != BL_HOM was changed into src->type == BL_MER

Let me explaion this for you: before this commit every kill counted that was not done by a Homunculus. Now only Mercenary kills count, basically nixing Player kills.

If this change was based on Aegis then please tell me the source, thanks!

**Comment by Lemongrass3110** [comment]
> > No idea why you blame [0f2dd7f](https://github.com/rathena/rathena/commit/0f2dd7fcf0e498aec2d281b80e31fa5b0c6c68ec), since this has nothing to do with the killing target. It only changes the attacker(src).
> 
> Did you even bother checking the commit?
> 
> src->type != BL_HOM was changed into src->type == BL_MER
> 
> Let me explaion this for you: before this commit every kill counted that was not done by a Homunculus. Now only Mercenary kills count, basically nixing Player kills.
> 
> If this change was based on Aegis then please tell me the source, thanks!
Oh no I did not check the commit thanks for telling me. 🤦‍♂️ Did you even bother reading my explanation? If you are that good than I do not understand why I have to bother looking at it rather than you solving the problem and providing a solution. But all you do is posting your narrow opinion everywhere.

**Comment by GMBoreas** [comment]
Narrow opinion everywhere = one issue and one pull request. You said the commit wasn't related as it had nothing to do. I just showed you that you are wrong. No need to get defensive. Solution: change it back to what it was. There you go! :)

**Comment by Lemongrass3110** [comment]
You still havent understood the difference between source and target it seems. Even after I told you to reread my comment. Maybe we can give it one more try?

**Comment by Lemongrass3110** [comment]
If you need me to I can even explain it more precisely to you:
The function call to mercenary_kills comes from within the mob_dead function, `<sarcasm>which of course is always called for players...</sarcasm>`
So yeah changing that block type check will solve this issue for sure. 😅

**Comment by GMBoreas** [comment]
Okay okay, let me explain this to you then:

int mob_dead(struct mob_data *md, struct block_list *src, int type)

list *src, holds the "source" of whoever killed the monster, correct?

Before the change:

`if( sd->md && src && src->type != BL_HOM && mob_db(md->class_)->lv > sd->status.base_level/2 )
				mercenary_kills(sd->md);`

Any source != Homunculus (Players and Mercenary) would trigger mercenary_kills(sd->md).

After the change:

`if( sd->md && src && src->type == BL_MER && mob_db(md->class_)->lv > sd->status.base_level/2 )
				mercenary_kills(sd->md);`

Only source == Mercenary triggers mercenary_kills(sd->md).

Thzat is the whole issue. We went from Players + Mercenary to only Mercenary. We booted an Aegis 11.3 server and tested this, result was that Player kills do count, hence this bug report. Now I was asking which source did rAth9ena use to determin that the killing behavior should be changed like that.

I hope it is clear now. Thanks!

**Comment by Lemongrass3110** [comment]
Ok seems like this was a misunderstanding from my side. I thought the report was referring to mercenaries killing players and not players killing monsters. The title and some of the sentences were misleading for me. Maybe you understand why my answers made no sense for you as well.

Thanks for clearing this up. Now we should be able to confirm and fix this without problems.

**Comment by GMBoreas** [comment]
Perfect, I will tell Indigo to be more specific in the future. There are stilll lots and lots of pre-renewal bugs and missmatches in the sources, we just haven't had the time yet to report them all.
Anyway, thanks for investigating this, much appreciated.

**Comment by aleos89** [comment]
I was able to confirm on officials that players who land the kill also counts towards the total.
