### ISSUE TITLE
Sura [Tiger Cannon] - main dmg is random

### ISSUE THREAD

**Issue by firecroll** [rathena/rathena#433]
I looked up at the page but coudnt find any solution. Well the issue is that tiger cannon. when used as combo, still does random main dmg to one monster instead of doing total dmg to the main target and then distribute splash dmg to the ones in a 5x5 area. The one you target should always get full dmg.

http://3.1m.yt/IPGRmMWBd.png (there i target the one on top and did full dmg on bot)
http://4.1m.yt/7xxV_8c_o.png (target left one and did full dmg on right one)
http://2.1m.yt/8187pNIhk.png (target left one and correcly hit left one with full dmg, showing its random)

For this SS i used more mob and target one egg to show the dmg distribution is not wrong, it just have a random main dmg instead of doing it always to the one you target.
It can be seen in the battle log. (the target was the egg and did full dmg on an aqua element)
http://4.1m.yt/BiuAG_wSG.png

**Comment by reigneil** [comment]
maybe splash and direct attack treated separately thats why it happen what i think about this it should be in one bundle of attack.

**Comment by firecroll** [comment]
Yeah main the problem about this is applied in pvp, cause someone recalls you root them all and try to TC combo them, so you focus the squishy one, example Ranger, to you get the maximun splash dmg posible. But the main dmg goes to the RG or Chaser, which are full resistance, and therefore splash dmg gets diminished.

**Comment by firecroll** [comment]
When you put status:needs more info that means you are going to test, or you need me to give more info, sry im new in this. I just try to post bugs but i dont know so much about coding. If you need me to test something more in some aspect ill try to do it.

**Comment by Akkarinage** [comment]
[status: needs more info] is a label we use to flag that an issue requires dev testing, or we need to find information from official sources to backup the original report.

**Comment by cydh** [comment]
ehhh I'm confused. what's the issue here?
the damages for splash targets aren't 100% with the main target?
> The damage will be equal for all enemies affected depending on the damage received by the target

need to force the damage. /hmm let's find other source/pics/vids from official tests

**Comment by cydh** [comment]
wow creepy skills. xD
![screentest server056](https://cloud.githubusercontent.com/assets/4016864/8042343/ea0a80e8-0e48-11e5-980f-b9d5a4cee508.jpg)
![screentest server057](https://cloud.githubusercontent.com/assets/4016864/8042344/eabfa090-0e48-11e5-8fa1-d001cbc48b8d.jpg)
![screentest server058](https://cloud.githubusercontent.com/assets/4016864/8042345/eac2ff10-0e48-11e5-9247-ea94e65b5cba.jpg)
![screentest server059](https://cloud.githubusercontent.com/assets/4016864/8042346/eacdd34a-0e48-11e5-8886-be02ad68c784.jpg)

**Comment by cydh** [comment]
but I wonder that Aegis how can deal that damage insanely. even that Sura stats are below normal xD

anyway, I have the temporary fix, but this case can't be solved yet, If the plan as main target. My pic show when hit the plant, plant got 1 but the surrounding gets full damage like it assumed that plant isn't 'plant'.

**Comment by firecroll** [comment]
You got the whole idea wrong i think. I never talked about the splash dmg being wrong. The main issue about this post is the Main Damage of the COMBO, not the tiger cannon cast alone as i can see in your SS (you dont have fallen empire in your tabs). When you use the combo which is Dragon Combo - Fallen Empire - Tiger Cannon, TC auto cast and does a bonus dmg.
http://irowiki.org/wiki/Tiger_Cannon (level 10 - Via normal 2400 - Via Combo 5000.)
The problem i said was that the damage done by the combo which should be in the equation modified by 5000 goes random to the mob instead of the one you targeted.
I dont know if the splash damage should also apply the bonus 5000 in the equation as i dont have the data to compare that. But the one you target should get the bonus for sure. Instead of random as i showed in my SS,
PD: never use plants as main target as you will never be sure the real dmg. To test something you should have complete control of all aspects you want to test. But thats another thing. NVM this, just a suggestion.
Write me again if i wasnt clear.

**Comment by cydh** [comment]
well, actually as I said. The behavior of Tiger Cannon itself is incorrect, the damage MUST be same among all targets. say if the damage if 10k on main target, so do with the area target.
in ur pics, it deals 14k and 7k, because the current behavior is 'calculate damage for each targets', it that makes the damage is 'random'.
and the damage bonus via combo, of course if the 'main' target receive the combo bonus, the 'sub' targets receive same value.
