### ISSUE TITLE
Pet egg Bug

### ISSUE THREAD

**Issue by samurairukasu** [rathena/rathena#434]
Rathena GIT: Last Rev
Server instance: Renewal.
Exe: 20141022.

I know if this was already fixed in old dates, but its very strange.
https://rathena.org/board/topic/85067-egg-shop/
https://rathena.org/board/tracker/issue-6472-about-pet-item-data/

The problem comes when u sell a pet egg with npc shop and tray to hach it with command or pet incubator and when u try it, pet egg turns RED and shall not hach it, no matter with what egg u try, all going to turn red, BUT! And here is the strange part, if i try to hach "Loli Rury egg" or "Marionette egg" with command or pet incubator they hach and pet appear O_o

Why this happend with this pet egg selling them with npc and they hach with no problem, but the others turn red??

**Comment by reigneil** [comment]
i cannot reproduce using this procedure:
1. I add "Loli Rury egg" and "Marionette egg" to itemmall npc "Sheepy Gonzales" for the prize of 100z
prontera,157,284,4	shop	Sheepy Gonzales 895,12028:1000,12262:500,12016:750,9042:100,9043:100
2. I add "Loli Rury egg" and "Marionette egg" to item_cash_db.txt for the prize of 1C
0,9042,1
0,9043,1
then I try buy these items and hatch it but fails me to turn it RED.
can you tell what how?

**Comment by samurairukasu** [comment]
In my case (i forgot put it in first place, sorry), the pet eggs are sell by points, like vote points, users change their points for rewards from NPC, inside rewards are in arrays, items id, amount and price in separeted arrays, i share with you the example of NPC en SQL table.

SQL TABLE:
https://mega.co.nz/#!sk4WUAzB!SK-4ISEN3xw9sCJVnQyty-bkWt9rJRiU1gDaqgaKGDo
NPC SCRIPT:
https://mega.co.nz/#!5gZxEIQL!B1HG-bYcHv2xDPfQPoweEe9RpK5RjISAj3wQKtIxSvc

**Comment by samurairukasu** [comment]
Akkarinage, what info do you need?

**Comment by aleos89** [comment]
For pets eggs, you need to use the *makepet* script command instead of the *getitem* script command.
