### ISSUE TITLE
default_fixed_castrate option

### ISSUE THREAD

**Issue by SeravySensei** [rathena/rathena#4340]
`// By default skill that has '0' value for Fixed Casting Time will use 20% of cast time
// as Fixed Casting Time, and the rest (80%) as Variable Casting Time.
// Put it 0 to disable default Fixed Casting Time (just like -1 is the skill_cast_db.txt).
default_fixed_castrate: 20
`
This doesn't work like advertised. Instead setting it to 0 will force all skills to have 0 fixed cast time, even if they had a greater than zero set in the db. I assume instead this should, when set to 0, make all skills retain their fixed casting time from the DB - 0 if it was already zero, and whichever amount otherwise.

The bug is in PC.CPP, this
`
	if (fixed < 0 || !battle_config.default_fixed_castrate) // no fixed cast time
		fixed = 0;
	else if (fixed == 0) {
		fixed = (int)time * battle_config.default_fixed_castrate / 100; // fixed time
		time = time * (100 - battle_config.default_fixed_castrate) / 100; // variable time
	}` 
The comment here clearly contradicts the one in the CFG file (no fixed cast time vs no DEFAULT fixed cast time, that means two entirely different things.), not sure which is the original intention but I suspect the code is wrong and the comment is correct here.
Correct would be I believe :
`if (fixed < 0) 
		fixed = 0;
	else if (fixed == 0) {
		fixed = (int)time * battle_config.default_fixed_castrate / 100; // fixed time
		time = time * (100 - battle_config.default_fixed_castrate) / 100; // variable time
	}`

**Comment by aleos89** [comment]
Fixed in fb6dbc3.
