### ISSUE TITLE
Cloaking Movement Speed with Cart Boost

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#4345]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/9aa5f7d8345d9d89ec9e8b44060e92703f3d43b8

* **Client Date**: 20180621

* **Server Mode**: RE

* **Description of Issue**: 

By using the card Assassin Cross (ID: 4359) you will receive the Cloaking skill. If you use the Cloaking skill with the Genetic class you can use the Cart Boost skill and use Cloaking with high movement speed.

  * Result: 

Movement speed remains high when the Cart Boost skill is used in the Genetic class with Cloaking skill.
  * Expected Result:

Should slow movement speed to normal when in Cloaking skill status along with Cart Boost.
  * How to Reproduce: 

Use the Assassin Cross card (ID: 4359) on Genetic and use the Cart Boost skill. Use the Cloaking skill after using the Cart Boost skill.
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Would need to confirm on kRO if Cloaking movespeed overrides other bonuses. I would lean towards no.

**Comment by Badarosk0** [comment]
Confirmed in kRO. This behavior is correct. I will close this issue.
