### ISSUE TITLE
Minor NPC location

### ISSUE THREAD

**Issue by bgamez23** [rathena/rathena#4349]
![image](https://user-images.githubusercontent.com/1854368/64976404-c6714a80-d8e3-11e9-96b1-df5cd7ff5688.png)

**Comment by bgamez23** [comment]
located in brasilis map

**Comment by JohnnyPlayy** [comment]
It's not just the wrong location, this card has text that can only be seen once

**Comment by JohnnyPlayy** [comment]
This is the correct position 

> brasilis,191,239,3	script	안내표지판#bra	858,{

I also noticed that brasilis, There are rats in place of Hydra

`KRO`
![image](https://user-images.githubusercontent.com/17951544/65000166-06730600-d8c1-11e9-9025-ccdc8a38d0f4.png)

`Rathena`
![image](https://user-images.githubusercontent.com/17951544/65000332-91540080-d8c1-11e9-969e-32a4bb74b6e0.png)
