### ISSUE TITLE
bug in battlegroud scripts

### ISSUE THREAD

**Issue by Miengo2** [rathena/rathena#435]
[Error]:  Loading NPC file: npc/battleground/flavius/flavius01.txt
script error on npc/battleground/flavius/flavius01.txt line 157
    parse_line: expect command, missing function name or calling undeclared function
   154 : {
   155 : OnEnable:
   156 :        $@FlavBG1_C1_ID = bg_monster($@FlaviusBG1_id1,"bat_b01",61,150,"Pink Crystal",1915,"OBJ#bat_b01_a::OnMyMobDead");
*  157 :        's'etunitdata $@FlavBG1_C1_ID,30,1; // Make Crystal immune to damage until Guardians are defeated
   158 :        end;
   159 :
   160 : OnKill:
   161 :        killmonster "bat_b01","OBJ#bat_b01_a::OnMyMobDead";
   162 :        end;
[Error]:
script error on npc/battleground/flavius/flavius01.txt line 191
    parse_line: expect command, missing function name or calling undeclared function
   188 : {
   189 : OnEnable:
   190 :        $@FlavBG1_C2_ID = bg_monster($@FlaviusBG1_id2,"bat_b01",328,150,"Blue Crystal",1914,"OBJ#bat_b01_b::OnMyMobDead");
*  191 :        's'etunitdata $@FlavBG1_C2_ID,30,1; // Make Crystal immune to damage until Guardians are defeated
   192 :        end;
   193 :
   194 : OnKill:
   195 :        killmonster "bat_b01","OBJ#bat_b01_b::OnMyMobDead";
   196 :        end;
[Error]:
script error on npc/battleground/flavius/flavius01.txt line 236
    parse_line: expect command, missing function name or calling undeclared function
   231 :
   232 : OnMyMobDead:
   233 :        if (mobcount("bat_b01","guardian#bat_b01_a::OnMyMobDead") < 1) {
   234 :                donpcevent "cell#bat_b01_a::OnGreen";
   235 :                mapannounce "bat_b01", "The Guardian protecting Guillaume's Crystal has been slain.",bc_map,"0xFFCE00";
*  236 :                's'etunitdata $@FlavBG1_C1_ID,30,0; // Make Crystal damageable again
   237 :        }
   238 :        end;
   239 : }
   240 :
   241 : bat_b01,1,3,3  script  guardian#bat_b01_b      844,{
[Error]:
script error on npc/battleground/flavius/flavius01.txt line 255
    parse_line: expect command, missing function name or calling undeclared function
   250 :
   251 : OnMyMobDead:
   252 :        if (mobcount("bat_b01","guardian#bat_b01_b::OnMyMobDead") < 1) {
   253 :                donpcevent "cell#bat_b01_b::OnGreen";
   254 :                mapannounce "bat_b01", "The Guardian protecting Croix's Crystal has been slain.",bc_map,"0xFFCE00";
*  255 :                's'etunitdata $@FlavBG1_C2_ID,30,0; // Make Crystal damageable again
   256 :        }
   257 :        end;
   258 : }
   259 :
   260 : bat_b01,1,4,3  script  cell#bat_b01_a  844,{
[Error]:  Loading NPC file: npc/battleground/flavius/flavius02.txt
script error on npc/battleground/flavius/flavius02.txt line 158
    parse_line: expect command, missing function name or calling undeclared function
   155 : {
   156 : OnEnable:
   157 :        $@FlavBG2_C1_ID = bg_monster($@FlaviusBG2_id1,"bat_b02",61,150,"Pink Crystal",1915,"OBJ#bat_b02_a::OnMyMobDead");
*  158 :        's'etunitdata $@FlavBG2_C1_ID,30,1; // Make Crystal immune to damage until Guardians are defeated
   159 :        end;
   160 :
   161 : OnKill:
   162 :        killmonster "bat_b02","OBJ#bat_b02_a::OnMyMobDead";
   163 :        end;
[Error]:
script error on npc/battleground/flavius/flavius02.txt line 192
    parse_line: expect command, missing function name or calling undeclared function
   189 : {
   190 : OnEnable:
   191 :        $@FlavBG2_C2_ID = bg_monster($@FlaviusBG2_id2,"bat_b02",328,150,"Blue Crystal",1914,"OBJ#bat_b02_b::OnMyMobDead");
*  192 :        's'etunitdata $@FlavBG2_C2_ID,30,1; // Make Crystal immune to damage until Guardians are defeated
   193 :        end;
   194 :
   195 : OnKill:
   196 :        killmonster "bat_b02","OBJ#bat_b02_b::OnMyMobDead";
   197 :        end;
[Error]:
script error on npc/battleground/flavius/flavius02.txt line 237
    parse_line: expect command, missing function name or calling undeclared function
   232 :
   233 : OnMyMobDead:
   234 :        if (mobcount("bat_b02","guardian#bat_b02_a::OnMyMobDead") < 1) {
   235 :                donpcevent "cell#bat_b02_a::OnGreen";
   236 :                mapannounce "bat_b02", "The Guardian protecting Guillaume's Crystal has been slain.",bc_map,"0xFFCE00";
*  237 :                's'etunitdata $@FlavBG2_C1_ID,30,0; // Make Crystal damageable again
   238 :        }
   239 :        end;
   240 : }
   241 :
   242 : bat_b02,1,3,3  script  guardian#bat_b02_b      844,{
[Error]:
script error on npc/battleground/flavius/flavius02.txt line 256
    parse_line: expect command, missing function name or calling undeclared function
   251 :
   252 : OnMyMobDead:
   253 :        if (mobcount("bat_b02","guardian#bat_b02_b::OnMyMobDead") < 1) {
   254 :                donpcevent "cell#bat_b02_b::OnGreen";
   255 :                mapannounce "bat_b02", "The Guardian protecting Croix's Crystal has been slain.",bc_map,"0xFFCE00";
*  256 :                's'etunitdata $@FlavBG2_C2_ID,30,0; // Make Crystal damageable again
   257 :        }
   258 :        end;
   259 : }
   260 :
   261 : bat_b02,1,4,3  script  cell#bat_b02_a  844,{
[Info]: Done loading '16320' NPCs:
        -'3466' Warps
        -'237' Shops
        -'12610' Scripts
        -'3298' Spawn sets
        -'47947' Mobs Cached
        -'0' Mobs Not Cached
[Status]: Event 'OnInit' executed with '1942' NPCs.
[Status]: Event 'OnInterIfInit' executed with '0' NPCs.

**Comment by aleos89** [comment]
You didn't update your source or didn't compile your server after updating. Just make sure you have the latest clone of rA and compile it depending on your OS. You can find helpful guides in the wiki (https://rathena.org/wiki/).

**Comment by Miengo2** [comment]
It is not a source error is an error in the script
The server is in ubuntu, the revision of RA, is the last
This is the error that displays the script out of your github battleground
The error is shown by map-server

**Comment by aleos89** [comment]
> parse_line: expect command, missing function name or calling undeclared function
That line right there states that "setunitdata" is undeclared. It has been implemented since 2cee5b6.

I run my server tests in Ubuntu and haven't received this error nor any other bug report of it. So it must mean that you don't have the latest version of rA (or at least your source isn't the latest). I suggest you make a new clean clone of rA and then start from there as you could have a few other things missing.
