### ISSUE TITLE
Super Novice Spirit

### ISSUE THREAD

**Issue by juanfus** [rathena/rathena#436]
Super novice spirit dont allow to equip any hat (upper , mid , lower), also when you link a super novice and change map all hats are taken off.

here is more detailed and confirmed by reigneil in the last git
https://rathena.org/board/topic/101792-super-novice-spirit/

edit: weapons are only lv 4 so weapons works fine the bug is only on hats

**Comment by reigneil** [comment]
is this intended to be FAIL in pc.c?
			if (sd->status.base_level > 90 && item->equip & EQP_HELM)
				return ITEM_EQUIP_ACK_FAIL; //Can equip all helms
