### ISSUE TITLE
Super Novice / Super baby cant change to expanded in job master

### ISSUE THREAD

**Issue by juanfus** [rathena/rathena#437]
npc rute
npc/custom/jobmaster.txt

super novice and super baby cant change to expanded super novice/baby class

npc say : no more jobs are available

**Comment by juanfus** [comment]
y tested today this script to check

with supernovice , super baby , super novice Ex , Super Baby ex all say the same (readparam(19) works fine) but BaseJob say -1

aldebaran.gat,71,227,6	script	probjo	70,{
	mes "you basejob is : " + readparam(19); //this say 23 with super novice so this is ok
	if (BaseJob == Job_SuperNovice) //this return false
	mes "sieres supernovi";
	if (BaseJob == 23) //this return false too
	mes "eres supernovi23";
	mes "you base job is  " + BaseJob; //basejob with supernovice say -1
	close;
}

with other jobs works fine,
example magician say in readparam = 2 and basejob = 2

i check const db but I saw nothing unusual
Job_SuperNovice	23

**Comment by aleos89** [comment]
I haven't tested, but I thought @cydh fixed this back in 2fdcd92.

**Comment by juanfus** [comment]
oh i see, i will update, my mistake , thanks

**Comment by Atemo** [comment]
I guess it's because we change the EAJ const for novice after JOBL_SUPER_NOVICE change
> EAJ_SUPER_NOVICE	0x8100
EAJ_SUPER_BABY	0xA100
EAJ_SUPER_NOVICE_E	0xC100
EAJ_SUPER_BABY_E	0xE100

should be
> EAJ_SUPER_NOVICE	0x100
and co
