### ISSUE TITLE
Redemptio Bug

### ISSUE THREAD

**Issue by kiri02** [rathena/rathena#4372]
-  RAthena Hash : Latest

- Client Date : 2017-06-14

- Server Mode : Pre-Renewal

- Description of Issue : Cannot cast redemptio skill after certain number of uses even with a max level 99/70 HP. Starting max level, exp shouldn't be lost, therefore the skill should be cast successfully everytime.

**Comment by aleos89** [comment]
Did you level up by normal means (grinding like a normal player) or did you use `@blvl`?

**Comment by kiri02** [comment]
I leveled it up months ago as a normal player.

**Comment by aleos89** [comment]
If I'm not mistaken, you still lose EXP when using this skill, whether you are max level or not. You are just prevented from dropping down a level.

**Comment by andoys** [comment]
I also have this issue.
