### ISSUE TITLE
DISH Problem

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#4374]
* **rAthena Hash**: 752d314

* **Client Date**: 20170517RE

* **Server Mode**: RENEWAL

* **Description of Issue**: dish cannot be eaten after eating the dish, must relog beforehand or wait a while.

12202 //Steamed Tongue
12203 //Steamed Scorpion
12204 //Dragon Breath Cocktail
12205 //Hwergelmir's Tonic
12206 //Cooked Nine Tail's Tails 
12207 //Stew Of Immortality

and the biscuits don't have an animation effect

14616 //STR_Biscuit_Stick
14617 //VIT_Biscuit_Stick
14618 //AGI_Biscuit_Stick
14619 //INT_Biscuit_Stick
14620 //DEX_Biscuit_Stick
14621 //LUK_Biscuit_Stick

  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
```
//12202,60000	//Str_Dish10_
//12203,60000	//Agi_Dish10_
//12204,60000	//Int_Dish10_
//12205,60000	//Dex_Dish10_
//12206,60000	//Luk_Dish10_
//12207,60000	//Vit_Dish10_
```
These dishes are commented out in the item_delay database. Make sure you didn't enable them.

The Biscuit Stick item animation is probably handled by the client, just like the normal Potion animations.

**Comment by mazvi** [comment]
I fix this issue with cashfood_use_interval: 100

because on item delay database using // not work...
