### ISSUE TITLE
Wizard[Sightrasher] can hit hidden target?

### ISSUE THREAD

**Issue by reigneil** [rathena/rathena#439]
irowiki did not state that it can hit hidden target(SC_HIDING) so possibly cannot hit
http://irowiki.org/wiki/Sightrasher
another information from jRO mention that it cannot release hidden target using sightrasher itself.
http://wizard.rowiki.jp/index.php?SkillMagician
The user I damage the range of 15 * 15, center.
Due to the damage, and to two cells knocked back the attack radially.
Sight must use himself, the sight is cleared when the sightrasher is triggered.
There is no effect of releasing the hiding state to the sightrasher itself.
Gutter-line (*4) to double hit and allowed to knock back the target is like crossing the it (seems).
Some seems to be processing of proximity physical in judgment, you can recover HP in the Sky Deleter Card.
Sightrasher used by the Monster, it and specifications used by the players to ignore the shaded difference. Therefore, damage occurs over the wall.

so in a conclusion it must be cannot hit hidden target.

**Comment by Playtester** [comment]
Probably related to: https://github.com/rathena/rathena/issues/419
Removing the "earth element" requirement was a pretty bad idea.

**Comment by reigneil** [comment]
well i guess we can copy the code used by Dragon Breath just like this....
	case WZ_SIGHTRASHER: {
		struct status_change *tsc2 = NULL;
		if( (tsc2 = status_get_sc(bl)) && (tsc2->data[SC_HIDING] )) {
			clif_skill_nodamage(src,src,skill_id,skill_lv,1);
		} else
			skill_attack(BF_MAGIC,src,src,bl,skill_id,skill_lv,tick,flag|SD_ANIMATION);
		}
		break;
btw this is also fixed the animation problem: related topic https://github.com/rathena/rathena/issues/147 i'm adding SD_ANIMATION here...

**Comment by cydh** [comment]
add `SD_ANIMATION` for skill area that has `NK_SPLASH` will does the check on `skill_attack`
````
		//Note that splash attacks often only check versus the targetted mob, those around the splash area normally don't get checked for being hidden/cloaked/etc. [Skotlex]
		if (!status_check_skilluse(src, bl, skill_id, 2))
			return 0;
````
on that function, there's my flag for
````
 	// Skill that can hit hidden target
	if( skill_get_inf3(skill_id)&INF3_HIT_HIDING )
		hide_flag &= ~OPTION_HIDE;
````
well, at least `SD_ANIMATION` will fix that issue like Magnum Break case.
