### ISSUE TITLE
Attendance System "has already passed, skipping"

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#4391]
* **rAthena Hash**: ce42168b0d2d25f66ab8a5fc5e2ef24d988274ae
* **Client Date**: Irrelevant
* **Server Mode**: RE
* **Description of Issue**: If you set attendance and pass the date, it will give map_server error.

> [Error]: Node "End" date 20190529 has already passed, skipping.
> [Error]: Occurred in file 'db/re/attendance.yml' on line 6 and column 4.

**Comment by JohnnyPlayy** [comment]
Hash is correct?

**Comment by Lemongrass3110** [comment]
This is not about achievement system, but about the attendance feature.

**Comment by admkakaroto** [comment]
> This is not about achievement system, but about the attendance feature.

Oh yes, sorry, i was sleepy.

**Comment by admkakaroto** [comment]
> Hash is correct?

Yes.

**Comment by Lemongrass3110** [comment]
Are you only referring to the error message btw or a real crash?
Because this message is intended, because it does not make sense to load outdated event data and this is just so you notice and can remove/comment it or in case needed to adjust the date sequence to the next month/period.

**Comment by admkakaroto** [comment]
> 
> 
> Are you only referring to the error message btw or a real crash?
> Because this message is intended, because it does not make sense to load outdated event data and this is just so you notice and can remove/comment it or in case needed to adjust the date sequence to the next month/period.

Not a problem, just the same error message, it doesn't crash map_server or something, I just reported it as an error message.
