### ISSUE TITLE
SC_SPEEDUP1 & SC_SPEEDUP0 damaged

### ISSUE THREAD

**Issue by anacondaqq** [rathena/rathena#440]
All items with these statuses do not give any speed increase.
![](http://i.imgur.com/dO540dw.png)

## Technical Information
rAthena: latest, pre-re, 2010-07-30

**Comment by reigneil** [comment]
most of the val1 = skill level right?

**Comment by anacondaqq** [comment]
yea

**Comment by iamnxt** [comment]
confirm.
This problem very cryitical.
All speed up / down spells (and not only) damaged + speedup potions too.

**Comment by cydh** [comment]
of pre-re. means I forgot to check it up. /swt gomen~

**Comment by RagnarokNova** [comment]
Is it intended behavior that some mobs with lower levels of NPC_AGIUP don't get a noticeable movement increase as well as they used to before?

**Comment by cydh** [comment]
hmm, I never noticed which monster that use skill. I'm only aware of offensive skills. xD

**Comment by RagnarokNova** [comment]
Sorry! It was my mistake, it seems to be fine. :]

**Comment by cydh** [comment]
D: ok
