### ISSUE TITLE
SG_DEVIL - wrong bonus

### ISSUE THREAD

**Issue by Balferian** [rathena/rathena#4402]
* **rAthena Hash**: 995fb2a
* **Client Date**: -
* **Server Mode**: Renewal

* **Description of Issue**: 
Star Gladiator aspd with SG_DEVIL 10 lv should be lower and changed from 30% to 11% at 10 skill lv.
It must be working like (for example "Awakening Potion") SCB_ASPD.
I found simmilar issue: https://github.com/rathena/rathena/issues/3735
  * Result: Now SG_DEVIL increase aspd to 193 with 1 agi.
  * Expected Result: SG_DEVIL bonuse must be working like on the screenshots from kRo.
  * How to Reproduce: learn SG_DEVIL to 10 lv.
  * Official Information:
![image](https://user-images.githubusercontent.com/16213511/66586864-0ac5d280-eb92-11e9-8165-3a7a926969d5.png)
![image](https://user-images.githubusercontent.com/16213511/66586882-11544a00-eb92-11e9-98b6-01674b779a1f.png)
[SKID.SG_DEVIL] = {
"태양과 달과 별의 악마",
"MAX Lv : 10",
"^777777습득조건 : 잡레벨 50^000000",
"계열 : ^777777패시브^000000",
"내용 : ^777777잡렙50이 됐을때만 발동하는 패시브 스킬입니다.",
"자신의 시력을 영원히 희생하는 대신에 공속을 향상시킵니다.",
"시력이 상실되면 주변이 안보여서 불편하니 가능하면 않찍는걸 권장합니다.^000000",
" [Lv 1] ^777777공속 2% 향상^000000",
" [Lv 2] ^777777공속 3% 향상^000000",
" [Lv 3] ^777777공속 4% 향상^000000",
" [Lv 4] ^777777공속 5% 향상^000000",
" [Lv 5] ^777777공속 6% 향상^000000",
" [Lv 6] ^777777공속 7% 향상^000000",
" [Lv 7] ^777777공속 8% 향상^000000",
" [Lv 8] ^777777공속 9% 향상^000000",
" [Lv 9] ^777777공속 10% 향상^000000",
"[Lv 10] ^777777공속 11% 향상^000000"
},

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Since this is related to the issue you linked, I'll go ahead and mark this as duplicate and go along with the info you provided here! Thanks!
