### ISSUE TITLE
Pet bugs

### ISSUE THREAD

**Issue by teededung** [rathena/rathena#4406]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/783009d642ecb29b0b11447167cc36cf736045ee

* **Client Date**: 20180621
* **Server Mode**: Pre-renewal, Renewal
* **Description of Issue**: 
  * Result: Pet egg bugs
  
  * How to Reproduce:
Bug 1:  No pet egg in inventory but you still have the pet
1. Hatch an egg to show Pet list menu (just showing the menu, do not choose the egg yet)
2. Request trading with another character
3. Complete the trading with the egg that you are going to incubate
4. Select the egg still displays in the pet menu and ...!!

Bug 2: You still have egg in your inventory when the pet leaves you (Intimate = 0). This will make the next incubation you will see pet name with red color in the menu list.

**Comment by Badarosk0** [comment]
This problem has also happened to me.

**Comment by sader1992** [comment]
i could not reproduce the issue of the trade
and in the server side , it check for the egg after selection
so even if you trade , if the `item['index'] != egg` you will get an error in the server side `wrong egg item inventory 'index'`
the client glitches if you get back that egg again , but it works fine .

maybe you have another way to reproduce the issue?

**Comment by teededung** [comment]
@sader1992 Please check this video https://www.youtube.com/watch?v=sFXZgfLsSqU

**Comment by sader1992** [comment]
Ok thanks , i see what you mean now.
I can confirm both issues.
