### ISSUE TITLE
Cart Items need be saved before vending

### ISSUE THREAD

**Issue by hnomkeng** [rathena/rathena#441]
![11251288_820368931372402_74167565396148733_n 1](https://cloud.githubusercontent.com/assets/9112684/7680446/df632424-fd90-11e4-8e78-abda7b6db9c9.jpg)

**Comment by reigneil** [comment]
is this supposed to be happen on official server., that it reminds you to relog?

**Comment by Akkarinage** [comment]
A little more information would be great..

**Comment by hnomkeng** [comment]
every vending is show text by picture.

**Comment by aleos89** [comment]
That was something implemented a while ago. When you add or remove items from a cart before the character is saved to the server, you get that warning. It's to prevent any issues when opening a Vending Shop.

#50 - The warning that was added.

To avoid the warning we should probably add a *clif_cartlist(sd);* to refresh the index of the items in the cart.

**Comment by hnomkeng** [comment]
aleos89 ,thank you.

**Comment by michaelforge** [comment]
@aleos89 
As I understand, cart items receiving their `id` in `cart_inventory` as `AUTO_INCREMENT`, so there is no way to get id for those items until char has being saved.

**Comment by aleos89** [comment]
I can play around with this when I get a little more free time.

**Comment by michaelforge** [comment]
@aleos89 
Would be awesome =]
This message annoys lots of players.

**Comment by joelolopez** [comment]
i confirm this

**Comment by cydh** [comment]
this is because when saving process for new items on cart, server only ask to save. the id (not item id) for items in cart_inventory are not updated although the cart items are saved.

something like `map-server asks save -> char-server -> save process -> save by UPDATE or INSERT to SQL -> char-server only tells to map-server that cart items are saved without fetch the ids of latest records`.
this happened since dinosaur era doomed, also for storage, inventory, and guild storage.

**Comment by julia40124009** [comment]
why closed it !
it bothers me

**Comment by Kemiro** [comment]
As troubled me!

**Comment by cydh** [comment]
## This is the 'price' that u pay for Autotrade Persistency, disable it and you don't need to 'do something that makes your char data will be saved'

**Comment by cydh** [comment]
certainly related to #50 and #813
fixed for https://github.com/rathena/rathena/tree/cleanup/storages_optimization at ~~#1551~~ 800714abfe7b6e665d6997c314fc26a0ae519a7f
