### ISSUE TITLE
Land Protector area effect

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#4412]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/9aa5f7d8345d9d89ec9e8b44060e92703f3d43b8

* **Client Date**: 20180621

* **Server Mode**: RE

* **Description of Issue**: 

If the player uses land protector and another player uses an area skill outside the land protector area the effect still occurs. Protection will not happen.

* **Result**: 

Players using land protection will not be protected in this case.

* **Expected Result**: 

Land Protector should protect against any area skills, even if the skill is used outside and the area range affects anyone in the land protector.

* **How to Reproduce**: 
Below the images showing the problem how to reproduce:

https://ibb.co/kSkC9dC
https://ibb.co/gWVbYf4

* **Official Information**: 
  

* **Modifications that may affect results**:

**Comment by vstumpf** [comment]
This is because the center of the skill is outside the lp and it splashes inwards. I think it has been confirmed like this on kro? This is not the first time it's come up.

**Comment by secretdataz** [comment]
This is an official behavior.
