### ISSUE TITLE
Menu limitation of questboard.txt

### ISSUE THREAD

**Issue by lelouch22** [rathena/rathena#4414]
* **rAthena Hash**: 995fb2a0a19fee574dd72c1f2ea61870f973b18a

* **Client Date**: 2018-09-19aRagexe

* **Server Mode**: Pre-Renewal

* **Description of Issue**: 
  * Result: [Warning]: buildin_select: NPC Menu too long! (source:Questboard / length:2498)

**Comment by Lemongrass3110** [comment]
Clientside limit
