### ISSUE TITLE
RL_SLUGSHOT required item

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#4421]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/375aea6b86ce9fb158ee1f968717be1d49438417
* **Client Date**: 20180620

* **Server Mode**: RE
* **Description of Issue**: Even with the ammo equipped, it is not possible to use the ability, returns the message saying that you must have the ammunition, even if you already have it.
  * How to Reproduce: Just try using this skill with the ammo in inventory, or equipped with it.

**Comment by attackjom** [comment]
Did you have Slug bullet inventory ?

**Comment by attackjom** [comment]
https://github.com/rathena/rathena/commit/87032fc95a4cf82ef87d488f35e7af247cfe16ec
 
Read this update

**Comment by admkakaroto** [comment]
yeah but, i'm having a little problem, sorry.
