### ISSUE TITLE
quests_morocc.txt

### ISSUE THREAD

**Issue by Miengo2** [rathena/rathena#443]
quest \ quests_morocc.txt
No reset time, the script indicates a time of 4 minutes after someone in and out, but this time is not reset

The part of the script is this

if ($ @ maobar_room == 0) {
set $ @ maobar_room, 1;
donpcevent "# room1timer OnEnable ::";
donpcevent "Marjana # poison :: OnEnable";
mes "[Tao]";
mes "Ah, that place is protected";
mes "security by magic, so you'll";
mes "^ 4D4DFF4 Only Have To Remain minutes ^ 000000";
mes "Do not waste time there, meow.";
Close2;
warp "que_job01", 11.7;
end;

**Comment by Atemo** [comment]
https://github.com/rathena/rathena/blob/master/npc/quests/quests_morocc.txt#L168
This part is disabled
