### ISSUE TITLE
Itemdb

### ISSUE THREAD

**Issue by oiacrasec** [rathena/rathena#4431]
* **rAthena Hash**: abec31f32

* **Client Date**: 2018-04-18bRagexeRE

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result:
 gm command ``` `@item 31025` ``` (Immortal Wind Ghost Card) only return ``` `@item failed` ```
  * Expected Result: Receive the item inside the inventory
 
  

* **Modifications that may affect results**: There is no modification

* **Bonus**:
I have investigated the file db/re/item_db.txt and result was:

31019,Creepy_Demon_Card
31020,Malicious_Baby_Ghost_Card
31021,Dancing_Marionette_Card
31022,Abandoned_Teddy_Bear_Card
31023,Celine_Kimi_Card
//===================================================================
// More Costumes
//===================================================================
31027,C_Pretty_Bear
31028,C_Black_Cat_Hood

Look that item ID 31024, 31025 and 31026 isnt inside the file.

I have investigated the SQL files and the problem occurs too.

**Comment by Atemo** [comment]
Added in https://github.com/rathena/rathena/commit/99e75b07bca299123be4fd8b2ac5f22849993252
