### ISSUE TITLE
Update to #1602

### ISSUE THREAD

**Issue by dragonis1701** [rathena/rathena#4435]
I made the topic #1602 but it never got looked into too much because it was on official behavior but I found out that it actually does occur on official_walkpath. Drop a piece of loot out of range but around a corner, like in Pyramids. When you click on it the player will walk around the corner and a little passed the item and then pick it up. It just seems that the target cell formula is a bit wonky when it comes to things directly around corners.

**Comment by cydh** [comment]
really I want to close this, can't you just follow the format?
if it's really related and still and same issue for you, just update there and follow the instruction, thanks
