### ISSUE TITLE
Right-click view player's equipment is crazy

### ISSUE THREAD

**Issue by cydh** [rathena/rathena#4449]
* **rAthena Hash**: ef81cefd5663445c4da745ce9bcb4e06ea3677e4
* **Client Date**: -
* **Server Mode**: Both
* **Description of Issue**: 
  * Result: 
     1. (technically) when player ask to view other's equipment, the server will sends all equip-type items, not only the equipped items only. (even in player's window will show the correct equipment, but the data was sent are everything)
     2. there's no range limit, as long as the target and who request  in same map-server, it's possible to view target's equipments
  * Expected Result: 
     1. Only send necessary item to the player who requested
     2. Limited to player in view area
  * How to Reproduce: 
    1. By using debug-mode and make breakpoints or use packet sniffer, then right-click to view other player's equipment, read the number of items were sent or the read the packet by sniffer.
    2. Use packet forger, only need to send the target's AID
  * Official Information: I believe official servers do it right, if no, we should prevent this. 
* **Modifications that may affect results**: -

**Comment by mazvi** [comment]
Nice

**Comment by Lemongrass3110** [comment]
Fixed in 5bcbed5
