### ISSUE TITLE
Professor [Health Conversion] -- Skill Cooldown and Casttime seems to be reversed

### ISSUE THREAD

**Issue by Akaineko-astasi** [rathena/rathena#445]
Now we have casting time ~= 1.5 sec and cooldown = 0 -> attack delay. 
There should be casting time = 0 and cool down = (0.8 + (Skill level*0.2)) seconds, acccording iROWiki and my ru-Off playing expierience.

**Comment by Playtester** [comment]
Confirmed. It's already correct in pre-renewal, but renewal should be the same, exactly as you stated. 0ms cast time and 800ms+200ms*level global aftercast delay.
