### ISSUE TITLE
Star Gladiator day calculation

### ISSUE THREAD

**Issue by nubspixel** [rathena/rathena#4452]
* **rAthena Hash**: ea5467004a16584281edb475479bc5c648e489c0
* **Client Date**:  n/a
* **Server Mode**: both
* **Description of Issue**: 
I received a report saying that the Lunar/Sol Protection are not working properly. Upon checking I found that that the skill checked using date of year. However, the code did not compensate for January-1 or day-0.
  * Result: Lunar/Solar Protection are active in reversed, while Star Protection active 1 day earlier (if my calculation are correct)
  * Expected Result: today is day 320, it should allows the use of Solar Protection. However, instead it allows the Lunar protection. Current day of year: https://www.epochconverter.com/daynumbers
  * How to Reproduce: just use Luna/Solar Protection, and check if the day of year is even or odd.
  * Official Information: err.. coding error, i have no source.

* **Modifications that may affect results**: 
src/map/date.cpp
```c++
/*
 * Get the day of the year
 */
int date_get_dayofyear(void)
{
	time_t t;
	struct tm * lt;
	t = time(NULL);
	lt = localtime(&t);
	return lt->tm_yday+1;
}
```

**Comment by Lemongrass3110** [comment]
The code only uses the the day of the year as base.
The real calculation is done here:
```
/*
 * Is today a day of the Sun for Star Gladiators?
 */
bool is_day_of_sun(void)
{
	return date_get_dayofyear()%2 == 0;
}

/*
 * Is today a day of the Moon for Star Gladiators?
 */
bool is_day_of_moon(void)
{
	return date_get_dayofyear()%2 == 1;
}

/*
 * Is today a day of the Star for Star Gladiators?
 */
bool is_day_of_star(void)
{
	return date_get_dayofyear()%5 == 0;
}
```

**Comment by nubspixel** [comment]
Yes, but since 1st of January outputs 0 when you use `lt->tm_yday`, it affects other things such as the SG skills.

It should logically, counts 
1st January as day 1, 
2nd anuary as day 2, 
.. so forth

However, tm_yday outputs it as
1st January as day 0, 
2nd January as day 1, 
.. and so forth.

**Comment by cydh** [comment]
`tm_yday` values is range between 0-364 (365 in leap years)

Real date | date_get_dayofyear() | result
-------- | -------- |--------
1 January| 0 | even
2 January| 1 | odd
3 January| 2 | even
4 January| 3 | odd
5 January| 4 | even, not Stellar day
6 January| 5 | odd, Stellar day

so, confirmed
