### ISSUE TITLE
Reflect damage and GVG/BG damage rate

### ISSUE THREAD

**Issue by cydh** [rathena/rathena#4455]
* **rAthena Hash**: 9389b7d425e048872c853f3c040bc5d20a7b1a40
* **Client Date**: -
* **Server Mode**: Both
* **Description of Issue**: 
  * Result: On GVG/BG/PK maps player A hit player B with reflect damage bonuses, player B received damage based on GVG/BG/PK `*_attack_damage_rate` on config but player A received reflected damage from 100% damage rate.
  * Expected Result: Player A received damage after `*_attack_damage_rate` calculation
  * How to Reproduce: Player A attack player B at GVG/BG/PK maps while player B have reflect damage bonuses
  * Official Information: -
* **Modifications that may affect results**: -

**Comment by nabraas2022** [comment]
هلا

**Comment by nabraas2022** [comment]
جميل جدا

**Comment by prehiro** [comment]
nice

**Comment by Wind-source** [comment]
这个。。 #

**Comment by lshtiaksaad157** [comment]
Ki

**Comment by lshtiaksaad157** [comment]
Holli

**Comment by micosanityyy** [comment]
This fixed almost all reflect damage correctly however a Paladin using Reflect Shield is still inflicting 100% of original damage compared to the inflicted adjusted damage through skill_damage_db. Ex. I'm only dealing 80k damage to Paladin but I'm getting 190k reflect damage
