### ISSUE TITLE
NydhoggsNest Instance Variable Error

### ISSUE THREAD

**Issue by DaemonSpade** [rathena/rathena#4461]
Error Message From Nydhogs Instance Script

[Warning]: script:get_val: cannot access instance variable ''ins_nyd2', defaulting to 0
[Error]: script_set_reg: cannot write instance variable ''ins_nyd2', NPC not in a instance!
[Debug]: Source (NPC): Murdered Yggdrasilid#1F at 1@nyd (213,277)
[Error]: buildin_instance_npcname: Invalid instance NPC (instance_id: 0, NPC name: "ins_nyd_1f_timer".)
[Debug]: Source (NPC): Murdered Yggdrasilid#1F at 1@nyd (213,277)

Part of the script that give the error

if (is_party_leader() == true) {
mes "The path to the Guardian's Nest is just past the waterfall by the large World Tree Yggdrasil to the North. The defensive mechanisms of the Sanctuary will start immediately.";
			next;
			mes "[World Tree Yggdrasil]";
			mes "Defeat all of Nidhoggur's guardians and go through the waterfall into the nest... and stop Nidhoggur's Shadow there.";
			next;
			mes "[World Tree Yggdrasil]";
			mes "The gate will open soon. Go defeat all of the guardians... you must kill them all in 30 minutes before the gate opens...";
			next;
			mes "[World Tree Yggdrasil]";
			mes "30 minutes... that's the limit of my powers. Please hurry.";
			next;
			mes "[World Tree Yggdrasil]";
			mes "And... Be careful... Be careful of the shadow's power.";
			'ins_nyd2 = ins_nyd2 = 1;
			donpcevent instance_npcname("ins_nyd_1f_timer")+"::OnEnable";
			donpcevent instance_npcname("nyd_call_mon_1")+"::OnEnable";
			close;

link of the script - https://github.com/rathena/rathena/blob/master/npc/instances/NydhoggsNest.txt

**Comment by sader1992** [comment]
if that what you encounter , i would guess you are speaking to the npc outside the instance (in the man map)
maybe you used @warp or something to back to the map?
the instance map is generated map
this error will appear if you go to the instance map without really opening an instance m and tried to talk to the npcs there
i didn;t test but the variable of the instance should only be edited within the instance npc , even if you can edit it out side it wouldn't be a good idea

ofc i am not sure if that is the case
but i see `instance_id: 0` and `1@nyd (213,277)` [this not a name for instance map the instance map name would be like `1@nyd0001` or something like that]

**Comment by DaemonSpade** [comment]
solved  thank you sader

**Comment by DaemonSpade** [comment]
solved avoid using @warp inside instance
