### ISSUE TITLE
Char Creation Denied on 2015 Client

### ISSUE THREAD

**Issue by rofasindo** [rathena/rathena#4462]
* **rAthena Hash**: bf9e97b4f0481f2996dcd7fe0ffeed179df4913e

* **Client Date**: 2015-11-04aRagexe

* **Server Mode**: Renewal

* **Description of Issue**:
  * Result: Cannot create new character and get notice "Character creation is denied".
  * Expected Result: should be fine and normaly to crate new character
  * How to Reproduce: Just create new character using client 2015 with disable packet encryption
  * Official Information:
  

* **Modifications that may affect results**: 
  
  
![screenMyRO  RE 000](https://user-images.githubusercontent.com/24239587/69523840-6b20a000-0f97-11ea-96cb-c2235d1fe47b.jpg)

**Comment by Daegaladh** [comment]
Cannot reproduce this bug, is it a fresh rAthena copy?

**Comment by Lemongrass3110** [comment]
What name did you use?
What langtype?
Any errors in character server window?

**Comment by rofasindo** [comment]
First I use on Linux Server and I compiled with fresh copy of rathena.  I use client 20151104 with langtype 1. But now its working fine after I try to re-diffpatch the client with different selection.
