### ISSUE TITLE
BUG on Card Separation

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#4468]
* **rAthena Hash**: bf9e97b

* **Client Date**: 20180620RE

* **Server Mode**: RENEWAL

* **Description of Issue**: 

Card separation using https://github.com/rathena/rathena/blob/master/npc/re/merchants/card_separation.txt is potentialy BUG, Get the rental equip item, then enter the card. after that, separate the card with this NPC, the equipment will become permanent.

different from a custom card remover https://github.com/rathena/rathena/blob/master/npc/custom/card_remover.txt. rental equipment when separated from the card, equip will still be a rental.

  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
The NPC should use the `successremovecards` / `failedremovecards` script commands.

**Comment by mazvi** [comment]
are there any other card remover/card separation services besides this (other npc)? if there is a need to check too

**Comment by aleos89** [comment]
Now that I look back at this, no official rental item should have any slots so this case should not happen. If you're passing out rental items on your server with slots then you will probably want to use `getinventorylist` and check for `@inventorylist_expire[] > 0`.
