### ISSUE TITLE
unitstopwalk

### ISSUE THREAD

**Issue by julia40124009** [rathena/rathena#447]
I test unitstopwalk script command but seems no work for me .

prt_fild08,160,360,4	script	test	641,2,2,{
OnTouch:
	unitstopwalk getcharid(3);
	end;
}
version :  https://github.com/rathena/rathena/commit/8083ff987d70bafa4f4da1cc13d84ea73b724303

**Comment by aleos89** [comment]
If the target is not stopping then that means there's no walk timer attached to the target. Maybe I can modify it a bit more to make sure it always stops the target.

**Comment by aleos89** [comment]
Did a little more searching since I had some free time. It looks like when OnTouch is triggered, we force the object to stop (we remove the walktimer). This would be the reason 'unitstopwalk' doesn't work.

**Comment by julia40124009** [comment]
Look need to add timer ?
