### ISSUE TITLE
status_skill2sc: Unsupported skill id 65535

### ISSUE THREAD

**Issue by sgsilva** [rathena/rathena#4470]
rAthena Hash: 662a3e5
Client Date: 2018-05-30bRagexeRE
Server Mode: RENEWAL or PRE
Description of Issue:

[https://www.youtube.com/watch?v=6z_uP752mVs&feature=youtu.be](url)
Bard Skills : 
[Error]: status_skill2sc: Unsupported skill id 65535
[Error]: Skill '65535' is undefined! C:\Users\Joker\Desktop\rathena-master\src\map\status.cpp:125::status_skill2sc
[Error]: status_skill2sc: Unsupported skill id 65535
[Error]: Skill '65535' is undefined! C:\Users\Joker\Desktop\rathena-master\src\map\status.cpp:125::status_skill2sc

**Comment by RagnaWay** [comment]
False, Tested here with the most current version of the emulator and gave no error.
https://youtu.be/TpTCw661t74

**Comment by sgsilva** [comment]
In second char use skill and walk with first char

**Comment by RagnaWay** [comment]
hmm is true, 
![image](https://user-images.githubusercontent.com/53480357/70022175-06a2a980-1572-11ea-88b0-0f4e1653f1d4.png)

**Comment by sgsilva** [comment]
see in video, friend is true.
https://www.youtube.com/watch?v=6z_uP752mVs&feature=youtu.be

**Comment by eduardorovani** [comment]
Also tested and the problem is real.

**Comment by Playtester** [comment]
It's a known issue, see here: https://github.com/rathena/rathena/issues/1341

Song code is a bit messy and nobody dares to fix it.
