### ISSUE TITLE
Job Master NPC

### ISSUE THREAD

**Issue by RadianFord** [rathena/rathena#4476]
* **rAthena Hash**: N/A

* **Client Date**: 2017+

* **Server Mode**: Pre Renewal

* **Description of Issue**: Cannot put 2nd job skill points.
  * Result: When i use the npc job master and change from baby taekwon into baby star glad, I cant put or use the skill points on my 2nd job skills. but if i use the command @jobchange and level it up thats when everything works fine.
  * Expected Result: It's not about the lua because, I can use the points when i use the command.
  * How to Reproduce: 
  * Official Information:
  

Here's my script https://pastebin.com/D7BzAecn

**Comment by mazvi** [comment]
You must clear skillpoint job 1 skill first.. if using gm acount there is no restriction skillpoint use.. so you can use it

**Comment by RadianFord** [comment]
Tested it from using a novice level 1 never use a command to level up or job level.

**Comment by Akkarinage** [comment]
Can we have an update on this? Since no one else is having an issue with the default Job Changer script (and you're using a customised version) I'm assuming we can close this?

**Comment by Lemongrass3110** [comment]
No further input from user
