### ISSUE TITLE
Ghost Palace Bug

### ISSUE THREAD

**Issue by kyurejl** [rathena/rathena#4494]
* **rAthena Hash**: 464fd4060711136f0c417cf0bbcdf6fa8ff76ded

* **Client Date**: 2018-06-21aRagexeRE

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: after finishing the ghost palace instance I click on "Destroy instance" and nothing happens.
  * Expected Result: after clicking "Destroy instance", the frame would close
  * How to Reproduce: ending the instance
  * Official Information: N/A

* **Modifications that may affect results**: N/A

**Comment by aleos89** [comment]
Duplicate of #3150.
