### ISSUE TITLE
Sacrifice should be blocked by Cicada Skin Shed & Auto Guard

### ISSUE THREAD

**Issue by NeutralDev** [rathena/rathena#4498]
* **rAthena Hash**: 34e5f537b73440589ba50532357b3bb7c9977cc5

* **Client Date**: 2017-06-14bRagexeRE

* **Server Mode**: pre-renewal

* **Description of Issue**: Sacrifice is going through Cicada Skin Shedding & Auto Guard which should not be possible. Cicada is a skill that is modified by ATK%. Only magic and +ATK should go through. Additionally, Auto Guard should also block this skill's damage as well. This appears to be the case ever since the [b614092](https://github.com/rathena/rathena/commit/b614092b75e9cb63892a88de7321fd0640aaee4d) commit. This seems like an accident unless this was officially confirmed and was not described in the commit.
  * Result: Sacrifice goes through Cicada & Auto Guard.
  * Expected Result: Sacrifice should be blocked by Cicada as a result of it being ATK%. Auto Guard should block Sacrifice's damage as well.
  * How to Reproduce: Activate Sacrifice on a Crusader/Paladin, have a Ninja use Cicada Skin Shed, enable PvP, attack the Ninja during Cicada Skin Shed. Then do the same test this time with Auto Guard on.
  * Official Information: N/A
  

* **Modifications that may affect results**: N/A

**Comment by BeWann** [comment]
@NeutralDev you can fix this by declaring cicada and sacrifice skill == atk miss on battle.c

**Comment by NeutralDev** [comment]
@BeWann Actually, you don't even need to modify the source at all. All we need to do to fix this is go to rathena/db/pre-re/skill_db.txt and simply remove these bits:
```
//    0x100000 - skill is not blocked by SC_AUTOGUARD (physical-skill only)
//    0x200000 - skill is not blocked by SC_UTSUSEMI or SC_BUNSINJYUTSU (physical-skill only)
```
At this entry:
https://github.com/rathena/rathena/blob/9993639177955cf9cd82035421e8c9a54921c13b/db/pre-re/skill_db.txt#L536

**Comment by BeWann** [comment]
i did on what you said but still not working.

what i did is i declare sacrifice on the cicada on battle.c 

can you tell me what did you do on skill_db? thanks
