### ISSUE TITLE
Asura strike & Wall of Fog, bug, or official befavior?  (videos)

### ISSUE THREAD

**Issue by iamnxt** [rathena/rathena#450]
Description
=========

Asura Strike Video
-----------------------
https://youtu.be/447Mp3Ft0Wk

**Description about asura**
Asura strike -> Enemy -> FOG Effect triggered -> Asura Strike miss.
Is it correct? Because i think (eathena proofs) it's not, and i want to ask. Maybe i'm somewhere wrong. (i think dangerous soul collect (spheres) and crytical explosion must be exist after skill fail, and there must be no "Miss" Attack. Maybe i'm wrong, (i'm testing for now too, if i will be wrong, i will close this bugreport)

Fire bolt example video
------------------------------
https://youtu.be/yMAvQIf-9Ko

1. Aim enemy
2. Cast spell
3. Triggered FOG effect
4. Skill failed.

Technical info
===========
pre-re, rAthena last, packet ver 25 (2010-07-21) (https://github.com/rathena/rathena/commit/348fbc6c93edc671b3f3871612f185f67a26b969)

**Comment by aleos89** [comment]
According to this thread (http://forums.irowiki.org/showthread.php?t=31051) all ranged skills have a 75% chance of failing. I don't think anything has changed since the topic was started, unless you can find anything else.

**Comment by firecroll** [comment]
http://irowiki.org/wiki/Blinding_Mist
"Characters inside the mist will have a 75% chance to completely avoid target skills (both magical and physical)," 
Asura strike is a targeted skill, it works correctly. Its just OP and not balanced, but thats a gravity issue, they used to do that with many skills. Change them once and leave them OP.
