### ISSUE TITLE
Mob Avail with Sprite Job It is not walking.

### ISSUE THREAD

**Issue by RagnaWay** [rathena/rathena#4505]
* **rAthena Hash**: c52b3b7

* **Client Date**: 2018-09-19aRagexe

* **Server Mode**: Renewal

* **Description of Issue**: The monster created with class sprite doesn't walk, it just stands still and spinning, but when I use the command to talk to the npc, we see that it is walking invisibly.
![mob_avail](https://user-images.githubusercontent.com/53480357/71665851-28dc4280-2d3d-11ea-869c-9c66a1b69cf8.jpg)
```
  - Mob: G_SIDE_WINDER_
    Sprite: JOB_ARCH_BISHOP
    Sex: Female
    HairStyle: 1
    HairColor: 20
    ClothColor: 500
    HeadTop: Angelic_Chain
    HeadMid: Ear_Of_Angel's_Wing
```

**Comment by Lemongrass3110** [comment]
It is working fine for me. Any modifications on your side?
What does the mob avail have to do with NPC commands?
Do you use the mob avail sprite in combination with an npc that uses this sprite + npcwalk?

**Comment by RagnaWay** [comment]
> It is working fine for me. Any modifications on your side?
> What does the mob avail have to do with NPC commands?
> Do you use the mob avail sprite in combination with an npc that uses this sprite + npcwalk?
I use a mob, with a job sprite to walk around town. Then he becomes an NPC and can talk to him. Example. If you speak Buff, Warp, Heal he will execute the command automatically.
The command works as shown in the picture, but the mob_avail with sprite job does not walk, is stopped spinning.
```
OnTimer5000:
	npcwalkto 156+rand(-6,6),168+rand(-4,4);
	end;

OnInit:
	defpattern 1, "([^:]+):.*cura.*", "toHeal";
	defpattern 1, "([^:]+):.*curar.*", "toHeal";
	defpattern 1, "([^:]+):.*bufs.*", "toBuff";
	defpattern 1, "([^:]+):.*buff.*", "toBuff";
	defpattern 1, "([^:]+):.*buffs.*", "toBuff";
	defpattern 1, "([^:]+):.*heal.*", "toHeal";
	defpattern 1, "([^:]+):.*healer.*", "toHeal";
	defpattern 1, "([^:]+):.*portal\\s+(.*)", "toPortal";
	defpattern 1, "([^:]+):.*teleporte\\s+(.*)", "toPortal";
	defpattern 1, "([^:]+):.*teleportar\\s+(.*)", "toPortal";
	activatepset 1;
	npcspeed 220;
	initnpctimer;
	end;
```

**Comment by theOptimistic** [comment]
That script will only walk once.
Test this one:
`OnTimer5000:
	npcwalkto 156+rand(-6,6),168+rand(-4,4);
	initnpctimer;
	end;

OnInit:
	defpattern 1, "([^:]+):.*cura.*", "toHeal";
	defpattern 1, "([^:]+):.*curar.*", "toHeal";
	defpattern 1, "([^:]+):.*bufs.*", "toBuff";
	defpattern 1, "([^:]+):.*buff.*", "toBuff";
	defpattern 1, "([^:]+):.*buffs.*", "toBuff";
	defpattern 1, "([^:]+):.*heal.*", "toHeal";
	defpattern 1, "([^:]+):.*healer.*", "toHeal";
	defpattern 1, "([^:]+):.*portal\\s+(.*)", "toPortal";
	defpattern 1, "([^:]+):.*teleporte\\s+(.*)", "toPortal";
	defpattern 1, "([^:]+):.*teleportar\\s+(.*)", "toPortal";
	activatepset 1;
	npcspeed 220;
	initnpctimer;
	end;`

**Comment by RagnaWay** [comment]
Video Preview: https://youtu.be/rjVuALyQ9dM

**Comment by RagnaWay** [comment]
Video Preview 2: https://youtu.be/kpvih1_5jVs
In this other video, it shows that mob npc is walking but not using the job sprite look.
```
#  - Mob: G_SIDE_WINDER_
#    Sprite: JOB_ARCH_BISHOP
#    Sex: Female
#    HairStyle: 1
#    HairColor: 20
#    ClothColor: 500
#    HeadTop: Angelic_Chain
#    HeadMid: Ear_Of_Angel's_Wing
```

**Comment by Akkarinage** [comment]
I'm having a similar issue where the mob with a job sprite no longer walks as it should - it just stays in one place.

After fingering it for a while, i noticed that if i move my char so the npc leaves my view area and go back, the npc is indeed where it's supposed to be. The walk animation isn't displaying, nor is the npc moving while in view, but it does change direction. Once the mob is loaded i can `debugmes` the current location at intervals and they are correct.

**Comment by Lemongrass3110** [comment]
@Akkarinage sample npc / db entry?

**Comment by Everade** [comment]
https://github.com/rathena/rathena/issues/1370
Possibly related?!

**Comment by RagnaWay** [comment]
@Lemongrass3110 new video. https://youtu.be/CSdMqZh2dl0
I found that when you leave the npc's view and come back the npc changes its location, but as long as it is in view, it doesn't just keep spinning.

**Comment by RagnaWay** [comment]
No news to fix this bug?

**Comment by Lemongrass3110** [comment]
Was finally able to reproduce this:
```
prontera,150,150,5	script	Bob#jones	1843,{
    npcwalkto 156+rand(-6,6),168+rand(-4,4);
    end;
}
```

**Comment by biali** [comment]
Hi guys! Is this problem back?  I just tried to use some mobs with a JOB_KNIGHT sprite and they are again "teleporting" to their destination and won't show attack animations.
