### ISSUE TITLE
get_svn_revision or get_git_version bug

### ISSUE THREAD

**Issue by bgamez23** [rathena/rathena#451]
on the latest version of rathena. there is no SVN Revision or Git Version unlike before.

**Comment by Akkarinage** [comment]
None of the "latest versions" of rAthena have touched the version code. The get_git_hash function will only work if  ".git/refs/remotes/origin/master" exists. If it's not displaying, then you've hit the download button instead of cloning the repository.

**Comment by bgamez23** [comment]
i just lower the version of my svn and it works fine again.

**Comment by Akkarinage** [comment]
You should've made a comparison between your version and the version you were using when this feature was "broken". It would be interesting to see what was changed in order to cause this.
