### ISSUE TITLE
RE: Sura Gate of hell + Forged Starcrumbed Weapons

### ISSUE THREAD

**Issue by Fraterna** [rathena/rathena#452]
yo. 
there's some weird issue with Gate of hell i cannot comprehend:
when i use a "very very very strong" forged weapon (3 star crumbs), damage of GoH is halved. tested with several weapons (dragon combo -> fallen empire -> Gate of Hell):
+0 Luna Kahleet : ~44k damage
+6 Luna Kahleet : ~45k damage
+0 Erde Mace: ~45k damage
+0 Red Ether Bag: ~44k damage
+7 Stunner: 46k damage
+4 Ice Stunner: 44k damage (forged weapon,  n°1ranked smith)
+0 Stunner: 42k damage (forged weapon, n°2 ranked smith)
+6 VVVS Stunner:   22k (!!!)  damage (forged weapon, n°2 ranked smith)

it seems the star crumbs (or at least 3 crumbs, can't test due lack of smithing-mats xD) mess up with GoH calculation.
the other skills, TSS, tiger cannon, etc  seem not to be affected from this, only GoH

anyone some idea?

**Comment by cydh** [comment]
hmm.. where's again the damage modifier for forged weapon :question:
