### ISSUE TITLE
Job Improvement Project

### ISSUE THREAD

**Issue by ghost** [rathena/rathena#4523]
* **rAthena Hash**: N/A

* **Client Date**: N/A

* **Server Mode**: Renewal

* **Description of Issue**: Need Job Improvement Project to Rune Knight, Guillotine Cross, Warlock, Performers, Archbishop, Genetic, Shadow Chaser, Mechanic
Divine-Pride: https://www.divine-pride.net/forum/index.php?/topic/3723-kro-classes-improvement-project/

Timeline: https://www.divine-pride.net/forum/index.php?/topic/4203-kro-skill-adjustment-timeline/

* **Modifications that may affect results**: N/A

**Comment by secretdataz** [comment]
#3659

**Comment by OptimusM** [comment]
sorry @secretdataz  but i think @kyurejl are not talking about 16 aniversary skills, i think it means about new recent updates that Gravity updated just few months ago.
In any case, the issue should be more complete than that.

**Comment by aleos89** [comment]
Rune Knight is done.
Arch Bishop is done.
Shadow Chaser is done.
Mechanic is done.
Genetic - #3284.

**Comment by attackjom** [comment]
Genetics has second rebalance about offensive , pharmacy and homunculus skills too.

https://www.divine-pride.net/forum/index.php?/topic/3723-kro-classes-improvement-project/&do=findComment&comment=6399

**Comment by OptimusM** [comment]
i think there is a confusion about this.

Genetic has 2 huge updates recently, the last one was on october 1st, alot of homunculus skills changed, some new item creation was added 
This is the last one
http://ro.gnjoy.com/news/devnote/View.asp?category=1&seq=3987555&curpage=1

The same goes for Rune Knight, Guillotine Cros, Minstrel/wanderer

**Comment by kyurejl** [comment]
Classes Improvement Project : 7th
5.1. Rune Knight

- Some skill will has a chance to trigger critical damage.

- Hundred Spear will deal more damage as heavier weapon.

- Changes some of Runestone effects.

- Dragon Breath and Dragon Breath - Water gain new effect depending on active Runestone, such as changing their property.

 

5.2. Guillotine Cross

- Dark Claw will remove reflect buff on target.

- Improves area of effect of Rolling Cutter and casting condition of Cross Ripper Slasher after rotating.

- Poisonous Weapon will give the user new effect on weapon depends on type of Guillotine Cross's poison which is endowing.

- Adjusts attack motion and cast range of Cross Impact.

 

5.3. Genetic

- Improves some skills of Sera, Bayeri, Eira and Eleanor.

- Improves combat mode of Homunculus.

- Improves Cart Cannon damage formula.

- Improves efficiency of skills which consume item.

https://www.divine-pride.net/forum/index.php?/topic/3999-note-new-contents-that-will-be-updated-within-2019/

**Comment by aleos89** [comment]
I’d like to get the 3rd class PR implemented first then since some of these skills overlap with changes from that PR.

**Comment by aleos89** [comment]
I'll go ahead and close this now as the other related issues/pull requests have been created and or committed.
