### ISSUE TITLE
New Madogear alternative appearance

### ISSUE THREAD

**Issue by ghost** [rathena/rathena#4524]
* **rAthena Hash**: N/A

* **Client Date**: N/A

* **Server Mode**: Renewal

* **Description of Issue**: https://www.divine-pride.net/forum/index.php?/topic/3999-note-new-contents-that-will-be-updated-within-2019/

* **Modifications that may affect results**: N/A

**Comment by aleos89** [comment]
Isn't this just a client related patch?

**Comment by kyurejl** [comment]
https://github.com/rathena/rathena/pull/2021

**Comment by OptimusM** [comment]
Actually not, There is 2 items to call mado gear, normal and the "yellow box"
On kRo you can choose what Madogear u want to ride, having exact same skills and everything just a different sprite.

I did a custom implementation of that if u want to check it, bc i think that would need client updates to use it properly, until then, here:
https://rathena.org/board/topic/121644-mechanic-new-sprite-custom-implementation/?tab=comments#comment-369222

**Comment by aleos89** [comment]
I re-read the dev note and skipped the line about choosing between the styles.

**Comment by Balferian** [comment]
@aleos89 maybe it helps: https://github.com/HerculesWS/Hercules/pull/2586/files
But before we need to add support for client 2019+
