### ISSUE TITLE
Charleston Crisis

### ISSUE THREAD

**Issue by ghost** [rathena/rathena#4526]
* **rAthena Hash**: N/A

* **Client Date**: N/A

* **Server Mode**: Renewal

* **Description of Issue**: Phantasmagorica - Charleston Crisis
#2215
Custom Charleston Crisis by Alayne: https://rathena.org/board/files/file/3663-charleston-crisis/
https://www.novaragnarok.com/wiki/King%27s_Heels

  * Official Information: https://irowiki.org/wiki/Charleston_Crisis
https://www.divine-pride.net/forum/index.php?/topic/3119-kro-charleston-crisis-revamp/
http://ro.gnjoy.com/news/update/View.asp?seq=220
http://ro.gnjoy.com/news/devnote/View.asp?category=3&seq=3851614&curpage=1

* **Modifications that may affect results**: N/A

**Comment by Everade** [comment]
https://github.com/rathena/rathena/issues/1303

**Comment by kyurejl** [comment]
https://github.com/rathena/rathena/pull/2215

**Comment by kyurejl** [comment]
Custom Charleston Crisis by Alayne
https://rathena.org/board/files/file/3663-charleston-crisis/

**Comment by kyurejl** [comment]
I'm really tired of using the bugged custom

**Comment by OptimusM** [comment]
Well, in addition to that, Charleston was revamp completely long time ago, so, i dont think that script it´s correct even if is not bugged or something.

The instance now it´s called "Royal Shoes Heel" or something like that.
The instance mechanic itself it´s completely different, here´s a video of the new charleston instance:
https://www.youtube.com/watch?v=jGex0CbsCA8&t=207s

**Comment by kyurejl** [comment]
http://ro.gnjoy.com/news/event/View.asp?Seq=806

**Comment by kyurejl** [comment]
and have the Dreams and Shadows the Nightmarish Jitterbug renewed

**Comment by kyurejl** [comment]
https://www.novaragnarok.com/wiki/King%27s_Heels

**Comment by kyurejl** [comment]
https://www.novaragnarok.com/wiki/Dreams_and_Shadows

**Comment by Everade** [comment]
@kyurejl 
Would be helpful if you could fill out the issue in the first place rather than commenting all over the place. Much appreciated.

There are people who get notified about every single comment.
At least use the edit function.

Thank you.

**Comment by Lemongrass3110** [comment]
Fixed in d67a5e1
