### ISSUE TITLE
Temple Of Demon God

### ISSUE THREAD

**Issue by ghost** [rathena/rathena#4528]
* **rAthena Hash**: N/A

* **Client Date**: N/A

* **Server Mode**: Renewal

* **Description of Issue**: Decisive Battle Part II - Temple Of Demon God
Custom by Alayne - https://rathena.org/board/files/file/3669-temple-of-demon-god/
#2431

  * Official Information: https://irowiki.org/wiki/Temple_of_Demon_God

* **Modifications that may affect results**: N/A

**Comment by kyurejl** [comment]
https://github.com/rathena/rathena/pull/2431

**Comment by kyurejl** [comment]
Custom by Alayne - https://rathena.org/board/files/file/3669-temple-of-demon-god/

**Comment by Everade** [comment]
https://github.com/rathena/rathena/issues/1313

**Comment by kyurejl** [comment]
This is decisive battle, not heroes trails

**Comment by Atemo** [comment]
https://github.com/rathena/rathena/commit/5933ab830459069f9bb3cdb199451d39960ff0ad
