### ISSUE TITLE
Title and Groups for mobs/npcs

### ISSUE THREAD

**Issue by Balferian** [rathena/rathena#4529]
* **rAthena Hash**: fb8a752
* **Client Date**: 2017-11-29+
* **Server Mode**: Pre/Re
* **Description of Issue**: 
  * Result: -
  * Expected Result: Add new parametrs to unit_data (title & groupId).
  * How to Reproduce: -
  * Official Information: kRo use this in some events and dungeons (for mobs/npc) like Luanda.
![image](https://user-images.githubusercontent.com/16213511/72111524-17ea8d00-334c-11ea-9ba5-4c0fbb4e24ab.png)
_Icons for group reads from texture/유저인터페이스/group/..._
Links: https://github.com/HerculesWS/Hercules/commit/cf28f0002c46e9c23e752b7e4b351de1e947f830

* **Modifications that may affect results**: -

**Comment by JohnnyPlayy** [comment]
Many scripts need this
