### ISSUE TITLE
Map Server Crash: cash_shop_items[tab].item[j]->nameid;

### ISSUE THREAD

**Issue by AbuGosok** [rathena/rathena#453]
>	map-server.exe!cashshop_buylist(map_session_data * sd, unsigned int kafrapoints, int n, unsigned short * item_list) Line 227	C
 	map-server.exe!clif_parse_cashshop_buy(int fd, map_session_data * sd) Line 15248	C
 	map-server.exe!clif_parse(int fd) Line 17724	C
 	map-server.exe!do_sockets(int next) Line 849	C
 	map-server.exe!main(int argc, char * * argv) Line 364	C

When I look at line 1-3 from above:
The root of crash in cashshop.c:
>	nameid = *( item_list + i * 5 ) = cash_shop_items[tab].item[j]->nameid; //item_avail replacement
Traced up to clif.c:
>	if (cashshop_buylist( sd, points, count, item_list))
Traced up to clif.c:
>	packet_db[packet_ver][cmd].func(fd, sd);

When I look at the data (??? means pointer null):
>	-		cash_shop_items	0x023bc2c0 {{item=0x00000000 {???} count=0 }, {item=0x00000000 {???} count=0 }, {item=0x00000000 {???} ...}, ...}	cash_item_db[8]
>	-		cash_shop_items[tab].item	0x00000000 {???}	cash_item_data * * UNABLE TO READ MEMORY

**Comment by AbuGosok** [comment]
sd contains a data, and one of it is char id so I manage to find out the one who did it. Now asking what's his last action before everyone get disconnected.

**Comment by cydh** [comment]
guess...
ur cash shop is empty, someone just try to buy something?

**Comment by AbuGosok** [comment]
Yes that's right. We sell cash items via NPC instead.

**Comment by hnomkeng** [comment]
npc not found
