### ISSUE TITLE
Update Item_db new equipment and enchant info.

### ISSUE THREAD

**Issue by ghost** [rathena/rathena#4532]
* **rAthena Hash**: N/A

* **Client Date**: N/A

* **Server Mode**: Renewal

* **Description of Issue**: KRO : EP 16.1/16.2/17.1 new equipment and enchant info.
KRO : Episode 17.2 enchant info : Automatic equipment and Sin weapons.
KRO : new gears from 200/70 patch dungeons.
JRO : Zodiac Set
KRO : Cash shop items updates

  * Official Information: https://www.divine-pride.net/forum/index.php?/topic/3981-kro-ep-161162171-new-equipment-and-enchant-info/
https://www.divine-pride.net/forum/index.php?/topic/4176-kro-episode-172-enchant-info-automatic-equipment-and-sin-weapons/
https://www.divine-pride.net/forum/index.php?/topic/4028-kro-new-gears-from-20070-patch-dungeons/
https://www.divine-pride.net/forum/index.php?/topic/3920-jro-zodiac-set/
https://www.divine-pride.net/forum/index.php?/topic/3281-kro-cash-shop-items-updates/

* **Modifications that may affect results**: N/A

**Comment by Atemo** [comment]
Only the JRO items are missing https://www.divine-pride.net/forum/index.php?/topic/3920-jro-zodiac-set/
and the enchants from lapine system

**Comment by Lemongrass3110** [comment]
@Atemo can this be closed?

**Comment by Atemo** [comment]
The JRO items are still missing in our DB, nop

**Comment by Atemo** [comment]
All items have been implemented.
