### ISSUE TITLE
Renovatio Skill incorrect behavior

### ISSUE THREAD

**Issue by darhylism** [rathena/rathena#4534]
* **rAthena Hash**:  939761a02d983e5f4ca3927c934ae1be0b9f94d1

* **Client Date**:  2018-05-30bRagexeRE

* **Server Mode**:  Renewal

* **Description of Issue**: 
  * Result: Renovatio behaves like Angelus / Gloria skill
  * Expected Result: Renovatio should behave like Heal that can target allies or enemies.
  * How to Reproduce: Use the skill renovatio
  * Official Information:  https://irowiki.org/wiki/Renovatio

* **Modifications that may affect results**: none

**Comment by aleos89** [comment]
The skill changed in #3258. Also, keep in mind that iRO is not a good source for skill information as it differs a lot from kRO.
