### ISSUE TITLE
Feature pet auto feed don't work

### ISSUE THREAD

**Issue by kyurejl** [rathena/rathena#4535]
* **rAthena Hash**: 939761a02d983e5f4ca3927c934ae1be0b9f94d1

* **Client Date**: 2018-06-20e

* **Server Mode**: Renewal

* **Description of Issue**: Feature pet auto feed don't work rathena\conf\battle\feature.conf

* **Modifications that may affect results**: N/A

**Comment by Lemongrass3110** [comment]
Better description of the problem, otherwise the issue will be closed

**Comment by kyurejl** [comment]
the pet doesn't eat your food that's in my inventory
