### ISSUE TITLE
Incorrect menu offset in Eclage quest

### ISSUE THREAD

**Issue by Indigo000** [rathena/rathena#4539]
* **rAthena Hash**: bf9e97b4f0481f2996dcd7fe0ffeed179df4913e

* **Client Date**: 2017-06-14

* **Server Mode**: Pre-Renewal

* **Description of Issue**: 
  * Result:  In line 5312 (https://github.com/rathena/rathena/blob/master/npc/re/quests/quests_eclage.txt#L5312) the menu variable is reduced by 1. This results in a wrong offset for both the quest ID assignment as well as the switch.
  * Expected Result:  Remove the -1 and it should work properly.
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Fixed in 148519b.
