### ISSUE TITLE
bHPVanishRaceRate is not working properly

### ISSUE THREAD

**Issue by jeanroyce** [rathena/rathena#454]
I realized that bHPVanishRaceRate (effect of Vellum Katzbalger) is not working properly, instead of removing the percentage of MaxHP, it removes a percentage of the current HP.

TESTING:

I set the bHPVanishRaceRate at 50% to make it more visible
(bonus3 bHPVanishRaceRate,RC_Player,10000,50;)
1st Hit - Removed 50% HP
![screennemuri003](https://cloud.githubusercontent.com/assets/8617825/8044320/3e94b954-0e02-11e5-9175-d0e8ed72d10b.jpg)

2nd Hit -
Removed only 25%
![screennemuri004](https://cloud.githubusercontent.com/assets/8617825/8044443/fbac8cf6-0e02-11e5-8e01-c21c544b36be.jpg)

3rd Hit
![screennemuri005](https://cloud.githubusercontent.com/assets/8617825/8044455/21f7f4c2-0e03-11e5-9c4f-87865eb731bb.jpg)

Here's a video of how it should work
https://www.youtube.com/watch?v=JDwEjuMsOFY
(Vellum Katzbalger - bonus3 bHPVanishRaceRate,RC_Player,10000,8;)

I believe bSPVanishRaceRate be with the same problem

Sorry for my bad english, i used Google Translate

**Comment by cydh** [comment]
there's 'missing' documentation on the source make it wrong implementation. xD

**Comment by jeanroyce** [comment]
Well, I do not know anything about c ++, but I made this quick fix, the vellum's again "work".
OLD:STATUS.C
	// It's safe now [MarkZD]
	if (hp_rate > 99)
		hp = status->hp;
	else if (hp_rate > 0)
		hp = apply_rate(status->hp, hp_rate);
	else if (hp_rate < -99)
		hp = status->max_hp;
	else if (hp_rate < 0)
		hp = (apply_rate(status->max_hp, -hp_rate));
	if (hp_rate && !hp)
		hp = 1;

	if (flag == 2 && hp >= status->hp)
		hp = status->hp-1; // Must not kill target.

	if (sp_rate > 99)
		sp = status->sp;
	else if (sp_rate > 0)
		sp = apply_rate(status->sp, sp_rate);
	else if (sp_rate < -99)
		sp = status->max_sp;
	else if (sp_rate < 0)
		sp = (apply_rate(status->max_sp, -sp_rate));
	if (sp_rate && !sp)
		sp = 1;
NEW:STATUS.C
	// It's safe now [MarkZD]
	if (hp_rate > 99)
		hp = status->max_hp;
	else if (hp_rate > 0)
		hp = apply_rate(status->max_hp, hp_rate);
	else if (hp_rate < -99)
		hp = status->hp;
	else if (hp_rate < 0)
		hp = (apply_rate(status->hp, -hp_rate));
	if (hp_rate && !hp)
		hp = 1;

	if (flag == 2 && hp >= status->hp)
		hp = status->hp-1; // Must not kill target.

	if (sp_rate > 99)
		sp = status->max_sp;
	else if (sp_rate > 0)
		sp = apply_rate(status->max_sp, sp_rate);
	else if (sp_rate < -99)
		sp = status->sp;
	else if (sp_rate < 0)
		sp = (apply_rate(status->sp, -sp_rate));
	if (sp_rate && !sp)
		sp = 1;

**Comment by jeanroyce** [comment]
But one thing, the vellum I feel should give only the effect, for example, Vellum Katzbalger, should give only 8% damage of the User maximum life without any damage to more influenced by ATK

**Comment by aleos89** [comment]
You inverted the meaning of passing negative values to status_percent_change() which will break lots of other skills/items that use this function.
```
 * @param hp_rate: Percentage of HP to modify. If > 0:percent is of current HP, if < 0:percent is of max HP
 * @param sp_rate: Percentage of SP to modify. If > 0:percent is of current SP, if < 0:percent is of max SP
```

**Comment by cydh** [comment]
as I said, not the code that was wrong, just the **confirmation** that needed for that bonus is vanish the SP/HP based on current values or the Max.

**Comment by jeanroyce** [comment]
This issue needs more information or has not been confirmed?

**Comment by aleos89** [comment]
It needs more information/to be confirmed on how it works on officials.

**Comment by cydh** [comment]
at least the `bonus2 bSPVanishRate,x,n;` is confirmed, reduce the % of MaxSP.
sample for `4171,Dark_Priest_Card` tested on Aegis.

tried to change `AddDestroySP_Attack Target 5 10` to `AddDestroySP_Attack Target 100 50`
