### ISSUE TITLE
Incorrect CheckBurglary function in Eclage quests

### ISSUE THREAD

**Issue by Indigo000** [rathena/rathena#4540]
* **rAthena Hash**: bf9e97b

* **Client Date**: 2017-06-14

* **Server Mode**: Pre-Renewal

* **Description of Issue**: 
  * Result:  The CheckBurglary function at line 4600 (https://github.com/rathena/rathena/blob/master/npc/re/quests/quests_eclage.txt#L4600) returns without any closing statements, resulting in the error message falling through to other text. 
  * Expected Result: There should be a close; statement after the message from the function.
  * How to Reproduce:  Set ep14_2_detect to 4 and talk to Damaged book#eclage.
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Fixed in 79a5a5b.
