### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by P4RC7110** [rathena/rathena#4544]
![image](https://user-images.githubusercontent.com/48139401/72644621-36561700-3950-11ea-8565-a581246d62c7.png)
Last Release

**Comment by Lemongrass3110** [comment]
Please follow the issue template.
What OS(and version) and which compiler(and version) are you using?

**Comment by xlChaoslx** [comment]
I am using CentOS 7 and C++ and getting same error

**Comment by xlChaoslx** [comment]
Solved, doing these:

`mv ./configure ./configure.bkp
autoconf ./configure.in > ./configure && chmod +x ./configure
./configure`

**Comment by Lemongrass3110** [comment]
Which compiler? C++ is not a compiler.

**Comment by xlChaoslx** [comment]
gcc



Enviado do meu smartphone Samsung Galaxy.



-------- Mensagem original --------
De : Lemongrass3110 <notifications@github.com>
Data: 21/01/2020 20:28 (GMT-03:00)
Para: rathena/rathena <rathena@noreply.github.com>
Cc: xlChaoslx <undeadshadow@hotmail.com>, Comment <comment@noreply.github.com>
Assunto: Re: [rathena/rathena] Compilation Error (#4544)


Which compiler? C++ is not a compiler.

**Comment by Lemongrass3110** [comment]
Version?

**Comment by xlChaoslx** [comment]
4.8.5



Enviado do meu smartphone Samsung Galaxy.



-------- Mensagem original --------
De : Lemongrass3110 <notifications@github.com>
Data: 21/01/2020 20:39 (GMT-03:00)
Para: rathena/rathena <rathena@noreply.github.com>
Cc: xlChaoslx <undeadshadow@hotmail.com>, Comment <comment@noreply.github.com>
Assunto: Re: [rathena/rathena] Compilation Error (#4544)


Version?

**Comment by Lemongrass3110** [comment]
Could you try the code in #4552?

**Comment by xlChaoslx** [comment]
doing it atm



Enviado do meu smartphone Samsung Galaxy.



-------- Mensagem original --------
De : Lemongrass3110 <notifications@github.com>
Data: 21/01/2020 21:25 (GMT-03:00)
Para: rathena/rathena <rathena@noreply.github.com>
Cc: xlChaoslx <undeadshadow@hotmail.com>, Comment <comment@noreply.github.com>
Assunto: Re: [rathena/rathena] Compilation Error (#4544)


Could you try the code in #4552<https://github.com/rathena/rathena/pull/4552>?

**Comment by Lemongrass3110** [comment]
@xlChaoslx did compilation finish already? ;-)

**Comment by xlChaoslx** [comment]
it did, ty



Enviado do meu smartphone Samsung Galaxy.



-------- Mensagem original --------
De : Lemongrass3110 <notifications@github.com>
Data: 22/01/2020 11:37 (GMT-03:00)
Para: rathena/rathena <rathena@noreply.github.com>
Cc: xlChaoslx <undeadshadow@hotmail.com>, Mention <mention@noreply.github.com>
Assunto: Re: [rathena/rathena] Compilation Error (#4544)


@xlChaoslx<https://github.com/xlChaoslx> did compilation finish already? ;-)

**Comment by xlChaoslx** [comment]
Could you also make it be compilable under older visual studios express ? I needed it over for Windows 2008 server (and visual Studio 2015 express doesnt work on it)

Em 22/01/2020 12:07, Lemongrass3110 escreveu:

Closed #4544<https://github.com/rathena/rathena/issues/4544> via a4c75d4<https://github.com/rathena/rathena/commit/a4c75d4771b92aab68bd3e8714a9a6d2e96b917e>.
