### ISSUE TITLE
getmapxy lack  the type BL_MOB

### ISSUE THREAD

**Issue by luizragna** [rathena/rathena#4545]
Hello,the script command **getmapxy** is lack the type **BL_MOB**
```
*getmapxy("<variable for map name>",<variable for x>,<variable for y>{,<type>,"<search value>"})

...

	BL_PC   - Character object (default)
	BL_NPC  - NPC object
	BL_PET  - Pet object
	BL_HOM  - Homunculus object
	BL_MER  - Mercenary object
	BL_ELEM - Elemental object
```

**Comment by aleos89** [comment]
Next time, please use the Issue Template.

You need to use `getunitdata` to get a specific monster's related information. `getmapxy` won't work because if you attempt to search for any monster it will return all of them on the map, so you won't get an accurate result.
