### ISSUE TITLE
Abracadabra (skill id 290) crashing map server

### ISSUE THREAD

**Issue by biali** [rathena/rathena#4553]
Maybe someone could do a better job here on reporting this but latest versions of rA have broken hocus pocus (abracadabra). It will crash map-server on usage.

* **rAthena Hash**: 

* **Client Date**: 

* **Server Mode**: 

* **Description of Issue**: 
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Can you give us the Git hash you are on?

**Comment by laziem** [comment]
I got this too when I try to manually apply #4480. But when I finally decide to update my rAthena (now I'm at ef9cbc345), it work without crash.

**Comment by biali** [comment]
> I got this too when I try to manually apply #4480. But when I finally decide to update my rAthena (now I'm at [ef9cbc3](https://github.com/rathena/rathena/commit/ef9cbc34590d50404d51b2591354f3b53757b3d1)), it work without crash.

thank you very much!! I will have to update it too then lol 
thank you a million for the feedback, mate!

**Comment by Lemongrass3110** [comment]
This has been fixed in deb0615
