### ISSUE TITLE
Cashshop error : not found npc

### ISSUE THREAD

**Issue by hnomkeng** [rathena/rathena#456]
Where to buy not found npc cashshop.

last version date 10/6/15.

**Comment by aleos89** [comment]
By default there is no cash shop created.

I know @cydh created the cash shop that are available in idRO (npc/re/merchants/cash_trader-idRO.txt). Other than that you can probably find ones created on the forum that are lying around or just create your own.

**Comment by hnomkeng** [comment]
dispbottom "no found npc" is cashshop

**Comment by hnomkeng** [comment]
@aleos89  check again please.

**Comment by Akkarinage** [comment]
@hnomkeng which NPC can't be found? Can you be a little more specific?

**Comment by hnomkeng** [comment]
#453 src/map/clif.c
info = &packet_db[sd->packet_ver][cmd];
 
-	if( sd->state.trading || !sd->npc_shopid ) {
+	if( sd->state.trading || !sd->npc_shopid || !cash_shop_defined) {
 		clif_cashshop_ack(sd,1);
 		return;
 	} else {

cashshop bug
