### ISSUE TITLE
Skill_damage_db.txt database doesn't seem to be working for renewal classes on pre-renewal server.

### ISSUE THREAD

**Issue by Skormie** [rathena/rathena#4574]
* **rAthena Hash**: 
5bcbed556

* **Client Date**: 
2018-06-20

* **Server Mode**: 
Pre-Renewal

* **Description of Issue**: 
  * Result: skill_damage_db.txt doesn't seem to work... At least when I tested it from the pre-renewal db with negative values for percentages.
  * Expected Result: I would be able to adjust damage of skills from that table.
  * How to Reproduce: Enter values into the txt file. With a server configured to pre-renewal. I was specifically trying to decrease the damage on Rebellion skills in a pre-renewal server. So a renewal class on a pre-renewal server. I think because they are enabled they should still be affected by the skill_damage_db.txt right?
  * Official Information: None.

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Can you give an example of an entry from your database?

**Comment by devLOOLP** [comment]
If the server is set to pre-renew and you try to use skill_damage ...
- you will use pre-re / skill_db, so you will not find the skills to be reduced by skill_damage.

**Comment by Skormie** [comment]
@devLOOLP The skills seem to exist within the pre-re skill_db.

@aleos89 
`// Rebellion Class Nerfs
RL_D_TAIL,BL_PC,‭4095‬,-56,-56,-56,-56 // Dragon Tail 56% Reduction
RL_BANISHING_BUSTER,BL_PC,‭4095‬,-56,-56,-56,-56 // 56% Reduction
RL_S_STORM,BL_PC,‭4095‬,-56,-56,-56,-56 // Shatter Storm 56% Reduction
RL_FIRE_RAIN,BL_PC,‭4095‬,-50,-50,-50,-50 // Fire Rain 50% Reduction
RL_R_TRIP,BL_PC,‭4095‬,-20,-20,-20,-20 // Round Trip 20% Reduction
RL_HAMMER_OF_GOD,BL_PC,‭4095‬,-56,-56,-56,-56 // Hammer of god -56%
RL_AM_BLAST,BL_PC,‭4095,-20,-20,-20,-20 // Anti-Material Blast -20%
//RL_SLUGSHOT,BL_PC,‭4095‬,-56,-56,-56,-56 // Slug Shot 56% Reduction

RL_SLUGSHOT,BL_PC,‭4095‬,-100,-100,-100,-100 // Slug Shot 56% Reduction`

**Comment by aleos89** [comment]
Technically, the fault as in your code. Your map values seem to be wrapped in bad characters.

![](https://cdn.discordapp.com/attachments/120596466661195778/682243965386621213/unknown.png)

The PR related to this will now print warnings if it fails to convert since atoi just returns 0 when it can’t convert.

**Comment by Skormie** [comment]
@aleos89 Thanks for clearing that up.
