### ISSUE TITLE
bonus3 bStateNoRecoverRace seems not working

### ISSUE THREAD

**Issue by reunite-ro** [rathena/rathena#4579]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/de9f667d2f6e3272e6eca27fd2074142f379531d

* **Client Date**: 20180620

* **Server Mode**: Renewal

* **Description of Issue**:  bStateNoRecoverRace is not working.
  * Result: Vellum Flail [0]   [One Hand]   Item ID# 16021 (Velum_Flail) should have chance remove all healing effects of target
  * Expected Result: Target healing effects will not effective
  * How to Reproduce: Use Vellum Flail and attack another player. Try to use any recovery items.

**Comment by hederod** [comment]
find u item on db/re/item_db.txt
and try change it: bonus3 bStateNoRecoverRace,RC_DemiHuman,10000,10000;
for it: bonus3 bStateNoRecoverRace,RC_Player,10000,10000;

**Comment by aleos89** [comment]
```
item Velum_Flail
	event OnStartEquip:
		var temp = GetRefineLevel [LOCATION_RARM]
		AddExtParam User VAR_HITSUCCESSVALUE temp/2
		AddExtParam User VAR_CRITICALSUCCESSVALUE 10*temp
		AddHandicapState_Race RACE_Player HANDICAPSTATE_NORECOVER 1000 0
	return
```
Confirmed it should be RC_Player instead of RC_DemiHuman.

**Comment by Atemo** [comment]
Fixed in https://github.com/rathena/rathena/commit/468d6f4d96c647e71d776e4f2a80161c085f9039
