### ISSUE TITLE
New skill sura "Flash Combo" wrong

### ISSUE THREAD

**Issue by jeanroyce** [rathena/rathena#458]
The skill "Flash Combo" of the sura is wrong, the skill is consuming HP and SP in "Tiger Cannon", something that should not, and the "Tiger Cannon" is with the combo damage bonus (Dragon Combo / Fallen EmpireTiger Cannon), it also should not happen.

http://irowiki.org/wiki/Flash_Combo

###### Before Flash Combo
http://i.imgur.com/RMU8RcS.png
###### After Flash Combo
http://i.imgur.com/bx54ogh.png

###### Before Flash Combo
http://i.imgur.com/unW2iJI.png
###### After Flash Combo
http://i.imgur.com/Mo6R4JI.png

**Comment by cydh** [comment]
I hard to understand this part. xD
> and the "Tiger Cannon" is with the combo damage bonus (Dragon Combo / Fallen EmpireTiger Cannon), it also should not happen.

**Comment by SuezoSilver** [comment]
The HP and SP should not be drained by skill (2330,SR_TIGERCANNON) Tiger Cannon under the (5009,SR_FLASHCOMBO) Flash Combo state, but in emulator happens

Source: https://www.youtube.com/watch?v=muj1RHJrYHI

**Comment by cydh** [comment]
ok

**Comment by jeanroyce** [comment]
Sorry for my bad english, i use google translate.
I meant to say that the damage "tiger cannon" in "flash combo" this like a manual combo (Dragon Combo / Fallen Empire / Tiger Cannon). but in fact it would be that, even with this sequence of skill, the damage is like a tiger cannon alone
If you have the IRO installed there, see this replay and try to repeat it in rathena you see the error:
https://mega.co.nz/#!iVQVQa6b!xTn95tu7M628itRDr0yyLrMchyy9SuQk-UfK5aDVAtg

**Comment by cydh** [comment]
dun hev iRO (some please mirror the installed files in parts for me please~)

well, Tiger Cannon in Flash Combo should be:
* NO consume HP and SP
* Deal damage without Combo Bonus from Fallen Empire after-skill effect
right?

**Comment by jeanroyce** [comment]
That's it!
