### ISSUE TITLE
elemental shield

### ISSUE THREAD

**Issue by joelolopez** [rathena/rathena#459]
elemental shield isnt casting safety wall, only pneuma.

**Comment by aleos89** [comment]
Are you sure? What revision are you using? Did you manually apply the patch and forget something?

**Comment by joelolopez** [comment]
yes sir aleos ,

**Comment by cydh** [comment]
invalid

**Comment by joelolopez** [comment]
sir cydh why did u mark this as invalid

**Comment by aleos89** [comment]
It was tested and proven to work just fine in the latest pull. Make sure you don't have any conflicts with your clone.

**Comment by joelolopez** [comment]
ok sir !! :>
