### ISSUE TITLE
Endow Skill Not Work Properly

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#4596]
* **rAthena Hash**: a3234744

* **Client Date**: 20180620

* **Server Mode**: RENEWAL

* **Description of Issue**: endow skill not work properly
  * Result: 
  * Expected Result: 
  * How to Reproduce:  using converter scroll, then using endow water to attack monster fire damage must be 200%

the problem is after and before endow damage is same...
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by yashimwong** [comment]
In Renewal, endow only change weapon attack to element. So if u r calculating the endow damage only multiply the weapon atk

**Comment by mazvi** [comment]
I think i was wrong on this issue.. iam sorry my fault...
