### ISSUE TITLE
cant connect to char server debian 10

### ISSUE THREAD

**Issue by Miraakol** [rathena/rathena#4597]
* **rAthena Hash**: a32347443

* **Client Date**: rAthena default

* **Server Mode**: Renewal

* **Description of Issue**: cant connect char server  when i updated my rathena to latest version. operating system is debian 10
  * Result: cant connect to char server
  * Expected Result: 
  * How to Reproduce: update new rev and recompile. after recompiling got error from terminal
  * Official Information: NA
  

* **Modifications that may affect results**: NA
  
  

![image](https://user-images.githubusercontent.com/4651777/73655248-8101be00-46c8-11ea-8f3d-221902cb9364.png)

![image](https://user-images.githubusercontent.com/4651777/73655330-c2926900-46c8-11ea-9e98-4ba0e17fe5e2.png)

![image](https://user-images.githubusercontent.com/4651777/73655353-d1791b80-46c8-11ea-9242-3b8966cc6859.png)

**Comment by yashimwong** [comment]
High probability your IP is set wrong. Just leave it uncommented, let rAthena configure it for u and try again.

**Comment by Lemongrass3110** [comment]
Please try to get support in our forum or on our discord channel. This is no development issue.
