### ISSUE TITLE
Incorrect View ID for Wizardry Staff & Soul Staff in pre-re

### ISSUE THREAD

**Issue by NeutralDev** [rathena/rathena#4599]
* **rAthena Hash**: 34e5f53

* **Client Date**: 2017-06-14bRagexeRE

* **Server Mode**: pre-renewal

* **Description of Issue**: The View ID for Wizardry Staff (1473) and Soul Staff (1472) are incorrectly labeled as view id 10 (staves) when it should be 23 (two-handed staves). The IDs are correctly labeled as 23 in the renewal item_db. This only appears to be a problem in pre-renewal. If left unfixed this can cause problems with NPCs such as the Malangdo Enchanter which rely on View ID to tell what the item type is.

**Comment by Lemongrass3110** [comment]
How would Malango Enchanter have effect on pre-renewal?

**Comment by NeutralDev** [comment]
There's actually nothing stopping you from using it technically speaking. Just load the npc file pre-re folder instead of the re folder. Regardless, anything similar to that NPC will not work with those staves checking for view id.
