### ISSUE TITLE
Erde Mace possibly not accurate to officials.

### ISSUE THREAD

**Issue by NeutralDev** [rathena/rathena#4600]
* **rAthena Hash**: 34e5f53

* **Client Date**: 2017-06-14bRagexeRE

* **Server Mode**: Both

* **Description of Issue**: The heal portion of Erde Mace's script is possibly inaccurate to officials. The Rate My Server description description reads as **"Increases healing effectiveness by 10% (when you are healed)."** (which oddly seems to imply it should be bonus bHealPower2 or bonus2 bSkillHeal2 instead? /hmm) whereas on Divine Pride it reads as **"Every potion's recovery amount increases by 10%."** where it then goes on to say there **"increases the effect of the Heal, Sanctuary, and Potion Pitcher skills by 10%"**. Meanwhile our bonus bHealPower script does what it's supposed to do, but the default for **skill_heal_power_rate** in **skill.conf** is currently set to **7**:
https://github.com/rathena/rathena/blob/0b3430c7774c9810a3ee4ee73ad66c6d085858df/conf/battle/skill.conf#L276-L278
This means all scripts that use bonus bHealPower exclude **Slim Potion Pitcher** but includes **Potion Pitcher** by rAthena default. However, Erde Mace appears to imply that it should work for all potion healing skills and not just Potion Pitcher itself. I don't have an aegis server to fact check this myself, so I made an issue to see if this could be fact checked by somebody else.

**Comment by secretdataz** [comment]
On Aegis, Erde calls AddHealValue in its item script, which is the same function as other items that increase heal power. So it should function the same as those items.

**Comment by NeutralDev** [comment]
Hm interesting, alright then. So I'm making the assumption that slim pitcher is purposely left out in AddHealValue and that's why we have it set at 7? Makes sense if that's the case.

**Comment by aleos89** [comment]
Correct. Since Slim Pitcher is a quest skill, Gravity usually doesn't go back and add new skills to previous item bonuses, they usually make new bonuses.

But as @secretdataz stated, the script for this item uses the same item bonus.
