### ISSUE TITLE
SKILL Remove Trap Crash server

### ISSUE THREAD

**Issue by Angelic234** [rathena/rathena#4605]
* **rAthena Hash**: 

 404e9f8

* **Client Date**: 
20180620

* **Server Mode**: 
Renew

* **Description of Issue**: 
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
1. use any trap skill to trap settings
2. Remove Trap
3. server crash
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by mazvi** [comment]
Confirmed

**Comment by behelit2** [comment]
This happened to me as well, the code fix resolves the issue.

**Comment by marky291** [comment]
Still occuring here.
