### ISSUE TITLE
Compiler redirects import [warning]

### ISSUE THREAD

**Issue by vakhet** [rathena/rathena#4612]
* **rAthena Hash**: 55e1a54ce

* **Server Mode**: Both

* **Description of Issue**: 
Every build, compiler redirecting import in common/cli.cpp: sys/poll.h --> poll.h
Not much of a trouble, just annoying

![image](https://user-images.githubusercontent.com/12441520/74055323-d7d10580-49f0-11ea-8bcd-7a0f7728282a.png)

* **Modifications that may affect results**: 
Compiling on Alpine Linux v3.11.3 @ Docker 19.03.5, installed packages: [alpine-packages.txt](https://github.com/rathena/rathena/files/4172385/alpine-packages.txt)

**Comment by Lemongrass3110** [comment]
Fixed in cdce4cd

Thanks for your contribution!
