### ISSUE TITLE
ITEM FLAG with the special broadcast 16

### ISSUE THREAD

**Issue by RadianFord** [rathena/rathena#4615]
* **rAthena Hash**: Older / Newer

* **Client Date**: 2017-06-14bRE

* **Server Mode**: Pre Renewal

* **Description of Issue**: I noticed in the announcement, the complete name of the player did not display correctly like this screen shot.
![Untitled](https://user-images.githubusercontent.com/9658425/74090222-c70aa900-4a5d-11ea-9e8b-77dc617a5c52.png)

  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Atemo** [comment]
https://github.com/rathena/rathena/blob/cdce4cd7941d0e057e2f584cf807b9b90cdcbb66/conf/battle/items.conf#L132
Reference https://github.com/rathena/rathena/pull/2692

**Comment by RadianFord** [comment]
@Atemo thank you, i thought its a bug. <3
