### ISSUE TITLE
Spiritual Ring item combo

### ISSUE THREAD

**Issue by SeravySensei** [rathena/rathena#4617]
https://www.divine-pride.net/database/item/1473/wizardry-staff

bonus bVariableCastrate,-getequiprefinerycnt(EQI_HEAD_TOP);
should be EQI_HAND_R for both wizardry staff and soul staff combo. Combo has nothing to do with the upper headgear.

**Comment by SeravySensei** [comment]
Nevermind, there are two spiritual rings in the db

**Comment by SeravySensei** [comment]
Wait, but 2766 IS the correct Spiritual Ring. Besides, at least in the client description, all 3 rings say "upgrade rate of staff", not headgear.

**Comment by aleos89** [comment]
Fixed in b3e85eb.
