### ISSUE TITLE
WOE CONTROLLER dont give the Reward

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#4619]
* **rAthena Hash**: b0ac171

* **Client Date**: 20200620RE

* **Server Mode**: RENEWAL

* **Description of Issue**: WOE CONTROLLER dont give the Reward
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment]
This is a result of 0b3430c.
I am on it. :-)
