### ISSUE TITLE
setunitdata

### ISSUE THREAD

**Issue by julia40124009** [rathena/rathena#462]
test script

prt_fild08,149,360,4	script	npcname	47,{
	setarray .init,0;
	setunitdata getnpcid(0,"npcname"),2,1111;  // set HP 1111
	setunitdata getnpcid(0,"npcname"),3,1024;  // set max HP 1024
	setunitdata getnpcid(0,"npcname"),8,9999;  // set STR 9999
	setunitdata getnpcid(0,"npcname"),9,9999;   // set AGI 9999
	setunitdata getnpcid(0,"npcname"),10,9999;  // set VIT 9999
	setunitdata getnpcid(0,"npcname"),11,9999;  // set INT 9999
	setunitdata getnpcid(0,"npcname"),12,9999;  // set DEX 9999
	setunitdata getnpcid(0,"npcname"),13,9999;  // set LUK 9999
	
// show info
	getunitdata getnpcid(0,"npcname"),.init;    // get npc data
	for(set .@i,0; .@i<getarraysize(.init); .@i++)
		mes ""+.init[.@i];
	close;
}

npc parameter (indexes)
2,3,8,9,10,11,12,13
Seem not work 

version : https://github.com/rathena/rathena/commit/5a4cd7426ee67bc87a845651bedc55bce2ff4487

**Comment by cydh** [comment]
I'm worried that `getunitdata` isn't working properly

**Comment by julia40124009** [comment]
https://rathena.org/board/topic/70561-mob-control-commands/?p=285891
If such a change
npc Max HP work fine

**Comment by julia40124009** [comment]
and setunitdata  to mob 

set .gid,bg_monster(1,"prt_fild08",152,357,"--ja--",1002,"npcname"+"::OnEventMobDead");
setunitdata .gid,2,99999;
setunitdata .gid,3,99999;

not work for monster ...

this command seem many problem

**Comment by cydh** [comment]
thank you for reporting..
needs some trick to make this perfect.
