### ISSUE TITLE
missing ^ before 000000

### ISSUE THREAD

**Issue by ElinhoPP** [rathena/rathena#4620]
https://github.com/rathena/rathena/blob/658d4207a4cbbae629e90cb247148a295cc0e2b6/npc/re/jobs/novice/academy.txt#L14191

**Comment by JohnnyPlayy** [comment]
This script has to be completely redone, as many things have been changed in KRO.

**Comment by JohnnyPlayy** [comment]
If time comes up I update this script along with the new quest and item.
