### ISSUE TITLE
RL_HEAT_BARREL didnt add ASPD

### ISSUE THREAD

**Issue by reunite-ro** [rathena/rathena#4629]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/47131b4585d97ef93e50b6af13b6074c29a8f600

* **Client Date**: 20180620

* **Server Mode**: Renewal

* **Description of Issue**: RL_HEAT_BARREL didnt show ASPD increment
  * Result: RL_HEAT_BARREL should reduce fixed cast time, ATK Boost (as I know Damage increase is not factored into skill damage calculations, it is added to the skill damage after other calculations are complete) and ASPD increment depends on skill level.

Before Heat Barrel:
![image](https://user-images.githubusercontent.com/11705163/74213111-b57e0700-4cd2-11ea-9d16-c7b1fe9233a7.png)

After Heat Barrel:
![image](https://user-images.githubusercontent.com/11705163/74213135-d3e40280-4cd2-11ea-8246-bbddac637527.png)

  * Expected Result: ASPD increment and damage increment check
  * How to Reproduce: Use Fortune of the Rich for the coins, and use Heat Barrel skill full level.

**Comment by teededung** [comment]
@reunite-ro After pull this https://github.com/rathena/rathena/commit/a74978b2586c938549c72fb41e15971f7e092d24 I fixed this error

**Comment by reunite-ro** [comment]
Okay so I should close this.
