### ISSUE TITLE
Diabolus Robe + Diabolus Ring Item Combo Does not work

### ISSUE THREAD

**Issue by AbuGosok** [rathena/rathena#463]
In item_combo_db.txt:
2374:2729,{ bonus2 bAddClass,Class_All,3; bonus bMatkRate,3; }
2375:2729,{ bonus2 bAddClass,Class_All,3; bonus bMatkRate,3; }

2375 + 2729 combo is working, but 2374+2729 combo does not work. Might be because duplicate records ever since rathena ignoring duplicate ids in item_db + import item_db.

**Comment by firecroll** [comment]
How did you test the 3% on 2375:2729 to confirm that its working, so i can test that too. Cause its not shown in basic atk and matk at alt+q and the % is too low to test it through skills dmg variation make that imposible with low % of atk/matk.

**Comment by anacondaqq** [comment]
Can't confirm (pre-re), last clear rAthena, 20100730
![](http://i.imgur.com/qm2b6RN.png)
There i was change 

> 2374:2729,{ bonus2 bAddClass,Class_All,3; bonus bMatkRate,3; }
(damage ~ 3.4 - 5.5k)
TO 

> 2374:2729,{ bonus2 bAddClass,Class_All,3; bonus bMatkRate,300; }
(damage 20+k)
