### ISSUE TITLE
Elemental Control doesn't give effect

### ISSUE THREAD

**Issue by reunite-ro** [rathena/rathena#4630]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/47131b4585d97ef93e50b6af13b6074c29a8f600

* **Client Date**: 20180620

* **Server Mode**: Renewal

* **Description of Issue**: The elemental control doesn't give effect at all for all Spirit.
  * Result: The elemental control doesn't give effect at all for all Spirit, for example if i use ventus lvl 1 and elemental control lvl 2 the movement speed should increase like using speed pot, Ventus lvl 2 and Elemental Control lvl 1 for Increases Attack Speed by 5 and shortens FCT by 1 second, but it doesn't. And that's apply for another spirit also, like Aqua lvl 2 and Elemental Control lvl 1 for increase Diamond Dust damage.
  * Expected Result: The elemental control give effect for all spirit.
  * How to Reproduce: As stated in result.

**Comment by teededung** [comment]
@reunite-ro Have you applied this? https://github.com/rathena/rathena/commit/e4046f9d18fcce6551d6aad6417550f519bd2b51

**Comment by reunite-ro** [comment]
Sorry, this gonna be fixed with that commit ? Sorry I didnt applied it yet. Will check about this later. Thanks .

**Comment by teededung** [comment]
I used to get this error and this commit will work

**Comment by reunite-ro** [comment]
ok Ill closed this one. Thanks for the clarification.
