### ISSUE TITLE
ERROR Build Using GCC7

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#4635]
* **rAthena Hash**: LATEST

* **Client Date**: irelevent

* **Server Mode**: RENEWAL

* **Description of Issue**: 

battle.cpp: In function ‘damage_lv battle_weapon_attack(block_list*, block_list*, t_tick, int)’:
battle.cpp:7532:31: error: ‘EFST_POSTDELAY’ was not declared in this scope
       clif_status_change(src, EFST_POSTDELAY, 1, autospell_tick, 0, 0, 0);
                               ^~~~~~~~~~~~~~
battle.cpp:7532:31: note: suggested alternative: ‘EF_PORTAL5’
       clif_status_change(src, EFST_POSTDELAY, 1, autospell_tick, 0, 0, 0);
                               ^~~~~~~~~~~~~~
                               EF_PORTAL5
battle.cpp:7594:29: error: ‘EFST_POSTDELAY’ was not declared in this scope
     clif_status_change(src, EFST_POSTDELAY, 1, skill_delayfix(src, r_skill, r_lv), 0, 0, 1);
                             ^~~~~~~~~~~~~~
battle.cpp:7594:29: note: suggested alternative: ‘EF_PORTAL5’
     clif_status_change(src, EFST_POSTDELAY, 1, skill_delayfix(src, r_skill, r_lv), 0, 0, 1);
                             ^~~~~~~~~~~~~~
                             EF_PORTAL5
make[1]: *** [obj/battle.o] Error 1
make[1]: Leaving directory `/root/rathena/src/map'
make: *** [map] Error 2

i think is related 2931c00bd483e823250c224a8b7738b4d7f260d6#diff-d260e334e876fa5d753c7d6ca45a8e39

  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by pigati23** [comment]
https://github.com/rathena/rathena/commit/cee7242623c2e5572bfe5b74a57543939587df49

**Comment by mazvi** [comment]
so what should i do?

**Comment by pigati23** [comment]
Just add the deleted.

**Comment by mazvi** [comment]
thx
