### ISSUE TITLE
COMPILING ERROR DEBIAN

### ISSUE THREAD

**Issue by Miraakol** [rathena/rathena#4639]
* **rAthena Hash**: 1e091cd58

* **Client Date**: RATHENA DEFAULT

* **Server Mode**: RENEWAL

* **Description of Issue**: 
  * Result: updated rathena to latest rev. here is the result after compiling:
![debian compile error](https://user-images.githubusercontent.com/4651777/74498012-2e22d480-4f1a-11ea-9dfb-b05960d8151a.PNG)

  * Expected Result: must no error in compiling
  * How to Reproduce: update your rathena to latest rev and compile
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by ecdarreola** [comment]
Just apply this patch again. Latest rathena commit reverts the patch below which produces the error.

https://github.com/rathena/rathena/commit/b68133952953caec69a7ee520e1d46826f3acf4b

**Comment by Miraakol** [comment]
thank you but how to apply it?

**Comment by ecdarreola** [comment]
Just copy paste what has been removed on the latest commit to the affected files and recompile it.

**Comment by Miraakol** [comment]
im sorry do you have a guide? im not familiar with git commands in debian.

**Comment by keitenai** [comment]
This issue should still be open cause the issue still exist.

**Comment by llchrisll** [comment]
Well the API re-commited the same again, so the reverted commit has been overwritten lol.

**Comment by Litro** [comment]
its all not only debian, rathena API github bot is getting fever, stay calm safe your self, just revert to this git hash https://github.com/rathena/rathena/commit/b68133952953caec69a7ee520e1d46826f3acf4b
