### ISSUE TITLE
Kagerou/oboro Charms

### ISSUE THREAD

**Issue by juanfus** [rathena/rathena#464]
how to reproduce:
1)buff a kagerou or oboro with fire charm x10
2)a second kagerou or oboro hit the buffed kagerou with flaming petal
the damage will be 999.999

or

1)buff a kagerou or oboro with wind charm x10
2) a second kagerou or oboro hit the buffed kagerou with wind blade
the damage will be 999.999

this dont happen with ice charm x10  and lighting spear of ice

![screenvakitasro582](https://cloud.githubusercontent.com/assets/12463722/8146735/e42df984-1217-11e5-93b4-87608dae5b13.jpg)
![screenvakitasro583](https://cloud.githubusercontent.com/assets/12463722/8146736/e42ee39e-1217-11e5-9b3c-2b8841270cb0.jpg)

**Comment by cydh** [comment]
awesome~ :sunglasses:

**Comment by MStr3am** [comment]
who knows maybe its more than that in reality since 999999 is the default limit
