### ISSUE TITLE
map server crashes after getting tons of "map_foreachincell: block count too many!" warnings

### ISSUE THREAD

**Issue by mizuki04** [rathena/rathena#4640]
* **rAthena Hash**: 2714899

* **Client Date**:  20180620

* **Server Mode**:  pre-renewal

* **Description of Issue**:  map server crashes after receiving tons of "map_foreachincell: block count too many!"
  * Result: map server crashes. When logging in, you get 'server closed'
  * Expected Result: map server crashes. When logging in, you get 'server closed'
  * How to Reproduce: unidentified. I am not sure what caused this and how it is being done.
  * Official Information: n/a
  

* **Modifications that may affect results**: n/a

**Comment by aleos89** [comment]
Do you have any source modifications? I have never experience this, especially as of recent.

**Comment by mizuki04** [comment]
My apologies. Turns out there was really a continuous network abuse going on with the provider resulting for the server to lag and then eventually get the char server crash... Ill close this down.
