### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by keitenai** [rathena/rathena#4643]
* **rAthena Hash**:  1e091cd

* **Client Date**: 20180621

* **Server Mode**:  renewal

* **Description of Issue**: 

Error below when compiling:

`battle.cpp: In function 'damage_lv battle_weapon_attack(block_list*, block_list*, t_tick, int)':
battle.cpp:7532:31: error: 'EFST_POSTDELAY' was not declared in this scope
       clif_status_change(src, EFST_POSTDELAY, 1, autospell_tick, 0, 0, 0);
                               ^~~~~~~~~~~~~~
battle.cpp:7594:29: error: 'EFST_POSTDELAY' was not declared in this scope
     clif_status_change(src, EFST_POSTDELAY, 1, skill_delayfix(src, r_skill, r_lv), 0, 0, 1);
                             ^~~~~~~~~~~~~~
`

* **Modifications that may affect results**: none

**Comment by keitenai** [comment]
![compile_error](https://user-images.githubusercontent.com/11855571/74505449-1a836800-4f32-11ea-8839-70c097db47ac.PNG)

**Comment by mazvi** [comment]
Heloo you must add back the deleted line on this hash 1e091cd58aef6b7a87d88cede8ba806cb6e44dcf

**Comment by Ritchiee** [comment]
same as the tittle, compiling is perfect spotted warning on compile 
4>C:\rathena-master\src\tool\mapcache.cpp(55,23): warning C4101: 'rsw': unreferenced local variable
this is normal?

**Comment by aleos89** [comment]
Resolved in 390eb977.
