### ISSUE TITLE
Battleground #3995 - crash map server

### ISSUE THREAD

**Issue by Balferian** [rathena/rathena#4644]
* **rAthena Hash**: 1e091cd
* **Client Date**:  2018-06-20
* **Server Mode**: Re

* **Description of Issue**: when all char register at any BG map server crashed
  * Result: when all chars register at any BG after they confirm start bg - map server crashed
  * Expected Result: start BG
  * How to Reproduce: register 10-12 chars to BG

> *** Error in `./server-map': free(): invalid pointer: 0x00000000073feb58 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x81609)[0x7f3d5447f609]
./server-map[0x40f8e9]
./server-map[0x456254]
./server-map[0x656b62]
./server-map[0x407c65]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f3d54420495]
./server-map[0x408faf]
======= Memory map: ========
00400000-00775000 r-xp 00000000 08:01 802126                             /home/Server/renewal/server-map
00975000-00976000 r--p 00375000 08:01 802126                             /home/Server/renewal/server-map
00976000-0097c000 rw-p 00376000 08:01 802126                             /home/Server/renewal/server-map
0097c000-024fe000 rw-p 00000000 00:00 0
0403e000-09c28000 rw-p 00000000 00:00 0                                  [heap]
7f3d34000000-7f3d34021000 rw-p 00000000 00:00 0
7f3d34021000-7f3d38000000 ---p 00000000 00:00 0
7f3d3be93000-7f3d53b92000 rw-p 00000000 00:00 0
7f3d53dd9000-7f3d53de5000 r-xp 00000000 08:01 24027                      /usr/lib64/libnss_files-2.17.so
7f3d53de5000-7f3d53fe4000 ---p 0000c000 08:01 24027                      /usr/lib64/libnss_files-2.17.so
7f3d53fe4000-7f3d53fe5000 r--p 0000b000 08:01 24027                      /usr/lib64/libnss_files-2.17.so
7f3d53fe5000-7f3d53fe6000 rw-p 0000c000 08:01 24027                      /usr/lib64/libnss_files-2.17.so
7f3d53fe6000-7f3d543fe000 rw-p 00000000 00:00 0
7f3d543fe000-7f3d545c0000 r-xp 00000000 08:01 5010                       /usr/lib64/libc-2.17.so
7f3d545c0000-7f3d547c0000 ---p 001c2000 08:01 5010                       /usr/lib64/libc-2.17.so
7f3d547c0000-7f3d547c4000 r--p 001c2000 08:01 5010                       /usr/lib64/libc-2.17.so
7f3d547c4000-7f3d547c6000 rw-p 001c6000 08:01 5010                       /usr/lib64/libc-2.17.so
7f3d547c6000-7f3d547cb000 rw-p 00000000 00:00 0
7f3d547cb000-7f3d547e0000 r-xp 00000000 08:01 23559                      /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f3d547e0000-7f3d549df000 ---p 00015000 08:01 23559                      /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f3d549df000-7f3d549e0000 r--p 00014000 08:01 23559                      /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f3d549e0000-7f3d549e1000 rw-p 00015000 08:01 23559                      /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f3d549e1000-7f3d54ae2000 r-xp 00000000 08:01 24023                      /usr/lib64/libm-2.17.so
7f3d54ae2000-7f3d54ce1000 ---p 00101000 08:01 24023                      /usr/lib64/libm-2.17.so
7f3d54ce1000-7f3d54ce2000 r--p 00100000 08:01 24023                      /usr/lib64/libm-2.17.so
7f3d54ce2000-7f3d54ce3000 rw-p 00101000 08:01 24023                      /usr/lib64/libm-2.17.so
7f3d54ce3000-7f3d54dcc000 r-xp 00000000 08:01 26546                      /usr/lib64/libstdc++.so.6.0.19
7f3d54dcc000-7f3d54fcb000 ---p 000e9000 08:01 26546                      /usr/lib64/libstdc++.so.6.0.19
7f3d54fcb000-7f3d54fd3000 r--p 000e8000 08:01 26546                      /usr/lib64/libstdc++.so.6.0.19
7f3d54fd3000-7f3d54fd5000 rw-p 000f0000 08:01 26546                      /usr/lib64/libstdc++.so.6.0.19
7f3d54fd5000-7f3d54fea000 rw-p 00000000 00:00 0
7f3d54fea000-7f3d54ff1000 r-xp 00000000 08:01 24033                      /usr/lib64/librt-2.17.so
7f3d54ff1000-7f3d551f0000 ---p 00007000 08:01 24033                      /usr/lib64/librt-2.17.so
7f3d551f0000-7f3d551f1000 r--p 00006000 08:01 24033                      /usr/lib64/librt-2.17.so
7f3d551f1000-7f3d551f2000 rw-p 00007000 08:01 24033                      /usr/lib64/librt-2.17.so
7f3d551f2000-7f3d55594000 r-xp 00000000 08:01 20509                      /usr/lib64/mysql/libmysqlclient.so.20.3.14
7f3d55594000-7f3d55793000 ---p 003a2000 08:01 20509                      /usr/lib64/mysql/libmysqlclient.so.20.3.14
7f3d55793000-7f3d55799000 r--p 003a1000 08:01 20509                      /usr/lib64/mysql/libmysqlclient.so.20.3.14
7f3d55799000-7f3d5580c000 rw-p 003a7000 08:01 20509                      /usr/lib64/mysql/libmysqlclient.so.20.3.14
7f3d5580c000-7f3d55811000 rw-p 00000000 00:00 0
7f3d55811000-7f3d55813000 r-xp 00000000 08:01 24021                      /usr/lib64/libdl-2.17.so
7f3d55813000-7f3d55a13000 ---p 00002000 08:01 24021                      /usr/lib64/libdl-2.17.so
7f3d55a13000-7f3d55a14000 r--p 00002000 08:01 24021                      /usr/lib64/libdl-2.17.so
7f3d55a14000-7f3d55a15000 rw-p 00003000 08:01 24021                      /usr/lib64/libdl-2.17.so
7f3d55a15000-7f3d55a2a000 r-xp 00000000 08:01 5303                       /usr/lib64/libz.so.1.2.7
7f3d55a2a000-7f3d55c29000 ---p 00015000 08:01 5303                       /usr/lib64/libz.so.1.2.7
7f3d55c29000-7f3d55c2a000 r--p 00014000 08:01 5303                       /usr/lib64/libz.so.1.2.7
7f3d55c2a000-7f3d55c2b000 rw-p 00015000 08:01 5303                       /usr/lib64/libz.so.1.2.7
7f3d55c2b000-7f3d55c42000 r-xp 00000000 08:01 5036                       /usr/lib64/libpthread-2.17.so
7f3d55c42000-7f3d55e41000 ---p 00017000 08:01 5036                       /usr/lib64/libpthread-2.17.so
7f3d55e41000-7f3d55e42000 r--p 00016000 08:01 5036                       /usr/lib64/libpthread-2.17.so
7f3d55e42000-7f3d55e43000 rw-p 00017000 08:01 5036                       /usr/lib64/libpthread-2.17.so
7f3d55e43000-7f3d55e47000 rw-p 00000000 00:00 0
7f3d55e47000-7f3d55ea7000 r-xp 00000000 08:01 5516                       /usr/lib64/libpcre.so.1.2.0
7f3d55ea7000-7f3d560a7000 ---p 00060000 08:01 5516                       /usr/lib64/libpcre.so.1.2.0
7f3d560a7000-7f3d560a8000 r--p 00060000 08:01 5516                       /usr/lib64/libpcre.so.1.2.0
7f3d560a8000-7f3d560a9000 rw-p 00061000 08:01 5516                       /usr/lib64/libpcre.so.1.2.0
7f3d560a9000-7f3d560cb000 r-xp 00000000 08:01 3828                       /usr/lib64/ld-2.17.so
7f3d560ec000-7f3d562c0000 rw-p 00000000 00:00 0
7f3d562c7000-7f3d562ca000 rw-p 00000000 00:00 0
7f3d562ca000-7f3d562cb000 r--p 00021000 08:01 3828                       /usr/lib64/ld-2.17.so
7f3d562cb000-7f3d562cc000 rw-p 00022000 08:01 3828                       /usr/lib64/ld-2.17.so
7f3d562cc000-7f3d562cd000 rw-p 00000000 00:00 0
7ffe4d71a000-7ffe4d75c000 rw-p 00000000 00:00 0                          [stack]
7ffe4d7bb000-7ffe4d7bd000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
[Status]: Map-server #0 has disconnected.

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Can you show the [call stack](https://github.com/rathena/rathena/wiki/Visual-Studio-Debugger)? The log you provided isn't descriptive enough.

**Comment by Balferian** [comment]
`#0  0x00007ffff61662c7 in raise () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007ffff61679b8 in abort () from /lib64/libc.so.6
No symbol table info available.
#2  0x00007ffff61a8e17 in __libc_message () from /lib64/libc.so.6
No symbol table info available.
#3  0x00007ffff61b1609 in _int_free () from /lib64/libc.so.6
No symbol table info available.
#4  0x000000000040f8e9 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x6a511a0) at /usr/include/c++/4.8.2/bits/shared_ptr_base.h:144
No locals.
#5  0x0000000000456254 in ~__shared_count (this=0x7fffffffe478,
    __in_chrg=<optimized out>)
    at /usr/include/c++/4.8.2/bits/shared_ptr_base.h:546
No locals.
#6  ~__shared_ptr (this=0x7fffffffe470, __in_chrg=<optimized out>)
    at /usr/include/c++/4.8.2/bits/shared_ptr_base.h:781
No locals.
#7  ~shared_ptr (this=0x7fffffffe470, __in_chrg=<optimized out>)
    at /usr/include/c++/4.8.2/bits/shared_ptr.h:93
No locals.
#8  bg_on_ready_start (tid=<optimized out>, tick=<optimized out>,
    id=<optimized out>, data=111481048) at battleground.cpp:684
        queue = 0x6a510d8
#9  0x0000000000656b62 in do_timer (tick=<optimized out>) at timer.cpp:374
        tid = 108
        diff = <optimized out>
        do_timer(long)::__FUNCTION__ = "do_timer"
#10 0x0000000000407c65 in main (argc=1, argv=0x7fffffffe5f8) at core.cpp:368
        next = <optimized out>
`

**Comment by Balferian** [comment]
First BG working fine.
1) scripts:
When bg end players don`t warp outside and can take unlimited badges.
> 	if ($@FlaviusBG1_id1 == getcharid(4)) {
		if ($@FlaviusBG1_Victory == 1)
			callfunc "F_BG_Badge",1,"Guillaume","Flavius";
		else
			callfunc "F_BG_Badge",0,"Guillaume","Flavius";
	}
	bg_leave;
	if (!getbattleflag("feature.bgqueue")) <- Need to invert check
		warp "bat_room",154,150;
	end;
2) After battle end, if you register at the same BG, map-server crashed.
`#0  0x00007ffff61662c7 in raise () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007ffff61679b8 in abort () from /lib64/libc.so.6
No symbol table info available.
#2  0x00007ffff61a8e17 in __libc_message () from /lib64/libc.so.6
No symbol table info available.
#3  0x00007ffff61b1609 in _int_free () from /lib64/libc.so.6
No symbol table info available.
#4  0x000000000040f8e9 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x258f100) at /usr/include/c++/4.8.2/bits/shared_ptr_base.h:144
No locals.
#5  0x00000000004562b6 in ~__shared_count (this=0x7fffffffe468,
    __in_chrg=<optimized out>)
    at /usr/include/c++/4.8.2/bits/shared_ptr_base.h:546
No locals.
#6  ~__shared_ptr (this=0x7fffffffe460, __in_chrg=<optimized out>)
    at /usr/include/c++/4.8.2/bits/shared_ptr_base.h:781
No locals.
#7  ~shared_ptr (this=0x7fffffffe460, __in_chrg=<optimized out>)
    at /usr/include/c++/4.8.2/bits/shared_ptr.h:93
No locals.
#8  bg_on_ready_loopback (tid=<optimized out>, tick=<optimized out>,
    id=<optimized out>, data=39385000) at battleground.cpp:631
        queue = 0x258f7a8
        bg = std::shared_ptr (count 2, weak 0) 0x57405c8
#9  0x0000000000656d12 in do_timer (tick=<optimized out>) at timer.cpp:374
        tid = 58
        diff = <optimized out>
        do_timer(long)::__FUNCTION__ = "do_timer"
#10 0x0000000000407c65 in main (argc=1, argv=0x7fffffffe5f8) at core.cpp:368
        next = <optimized out>`

**Comment by Balferian** [comment]
- After first battle can`t create same BG.
- Always showed msg <2107> "After reconnecting, please re-apply.".
- After relogin nothing happen.
- Other players can`t create this BG too.

**Comment by Balferian** [comment]
When register at BG and click "Cansel" map-server crashed.
exe: 2018-05-30

> #0  bg_queue_clear (queue=0x4256d38) at battleground.cpp:1063
No locals.
#1  0x0000000000452fff in bg_queue_leave_sub (sd=sd@entry=0x6510db0,
    lista=std::vector of length 0, capacity 1,
    listb=std::vector of length 0, capacity 0) at battleground.cpp:1097
        __for_range = std::vector of length 2, capacity 2 = {
          std::shared_ptr (count 1, weak 0) 0x7893258,
          std::shared_ptr (count 2, weak 0) 0x4256d38}
        player = <optimized out>
        list_it = <optimized out>
#2  0x000000000045312f in bg_queue_leave (sd=sd@entry=0x6510db0)
    at battleground.cpp:1122
No locals.
#3  0x0000000000485940 in clif_parse_bg_queue_cancel_request (fd=16,
    sd=0x6510db0) at clif.cpp:17838
        success = false
        name = "}\000\000\000\000\000\000\000\300`F\002\000\000\000\000\003\000\000\000\000\000\000"
#4  0x000000000047133d in clif_parse (fd=16) at clif.cpp:22269
        cmd = <optimized out>
        packet_len = 26
        sd = 0x6510db0
        pnum = 0

**Comment by Balferian** [comment]
Now everything is working well, for now I did`t find any problems.
