### ISSUE TITLE
Wall Of Thorn [ BUG ]

### ISSUE THREAD

**Issue by devLOOLP** [rathena/rathena#4645]
Hash: 1e091cd
Version Hexed: 2018-06-20
Mode: Renewal

Description: When you are hit by the wall of thorn and try to leave, you are pushed through the walls until you leave the prison.

Result: If you are out of the trap and trying to get into the trap, it works perfectly by pushing you to 2 cells behind.
But if you are in and want to get out, you are sent to the side and you are receiving constant giving.

Expected Result:In both situations, you are sent to 2 cells behind.
If you are inside and touch the wall, you return 2 cells back, that is, you return to the center of the trap.

How to Reproduce: Throwing wall of thorn at the enemy and trying to get out of the trap.

**Comment by devLOOLP** [comment]
bump

**Comment by devLOOLP** [comment]
bump

**Comment by aleos89** [comment]
Do you have a video or something of how it behaves on kRO when a target tries to escape from the center?

**Comment by devLOOLP** [comment]
https://www.youtube.com/watch?v=KIBBL30HoIo   [ 3:50 ]

This video is about Brazil Ragnarok, but it behaves the same way.

When the player is inside the wall and touches the walls, 2 cells are thrown back, that is, returning to the center.

Currently, if you hit the wall of the wall OUTSIDE, you are thrown 2 cells back ... but if so, hit the wall from the inside, you are thrown out of the wall not into the center.

**Comment by aleos89** [comment]
Ok, so you're saying that the player who is trapped inside should stay inside. I understand your report now.

**Comment by devLOOLP** [comment]
@aleos89 The knockback, however much the correct format is [2] ... If you test after pushing the first time, it will be thrown against another wall and sent out again.

For 100% correct formatting of this skill, the knockback must be changed in skill_db from 2 to 1.

Kind regards.
