### ISSUE TITLE
skill "AL_TELEPORT" and "TF_POISON" invalid.

### ISSUE THREAD

**Issue by TesLA-Git** [rathena/rathena#4646]
* **rAthena Hash**: cee7242

* **Client Date**: 20180620

* **Server Mode**: RE

* **Description of Issue**: 

![02](https://user-images.githubusercontent.com/7490388/74609743-de195d00-5127-11ea-85e5-beb11c26d5a8.png)

![01](https://user-images.githubusercontent.com/7490388/74609744-e1144d80-5127-11ea-80c8-eb2fc00bae0c.png)

  * Result: 
  * Expected Result: 
  * How to Reproduce: An error occurred using itemID: 601 or 602, and skill "AL_TELEPORT" invalid.
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
I was unable to reproduce this.

Can you please provide a little more detail?

**Comment by TesLA-Git** [comment]
OK. I will provide a little more detail.

**Comment by aleos89** [comment]
Do you have any warnings or errors during the parse of the skill_db? Do you have a correct count of skills being loaded? You should have 1205 skills load by default.

**Comment by TesLA-Git** [comment]
No warnings or errors. Read 1205 pieces of data.

![1](https://user-images.githubusercontent.com/7490388/74613688-61987580-514b-11ea-8070-71ccfb539c64.png)

**Comment by aleos89** [comment]
You must have some modification to AL_TELEPORT because it shouldn't exist in `skill_castend_pos2`. It's a self skill, not a placement skill.

**Comment by reigneil** [comment]
weird though that i can replicate this issue.. some 1st job skill aren't working either like endure, teleport, cold bolt, etc

**Comment by TesLA-Git** [comment]
Yes, for example, if a Thief uses TF_POISON skill, there will be a [Unknown Item] required 0 amount in chat window.

**Comment by TesLA-Git** [comment]
[Debug] model compile.
Warning after map-server startup completed.
![1](https://user-images.githubusercontent.com/7490388/74735896-8fd19e80-528c-11ea-8832-95a013c8f532.png)

**Comment by aleos89** [comment]
@reigneil Are you using VS2013?

**Comment by reigneil** [comment]
yes. I'm also suspecting it has something to do with vs2013 but i have no time to prove this... all that he say also happen to me that debug stuff, [Unknown Item] required xxx amount, skill_castend_pos2 etc.

**Comment by aleos89** [comment]
@TesLA-Git and I were talking last night and it does have to do with the VS2013 tool. It would seem there’s a bug that is fixed in VS2015+. I haven’t had time to look into the specifics of it yet.

**Comment by reigneil** [comment]
well i guess it was a cased close and rAthena must abandon vs2013 stuff and move to higher version...
