### ISSUE TITLE
bonus3 bAddEff  & bonus3 bAddEffWhenHit Questions or maybe bugreport.

### ISSUE THREAD

**Issue by iamnxt** [rathena/rathena#465]
***Bonus Effect description***

> bonus3 bAddEff,eff,n,y;       		Adds a n/100% chance to cause status eff on the target when attacking

***Bonus Effect Description***
> bonus3 bAddEffWhenHit,eff,n,y;		Adds a n/100% chance to cause status eff on the enemy when being hit by physical damage
                              		y is the trigger criteria:
                              		  ATF_SELF   = trigger effect on self
                              		  ATF_TARGET = trigger effect on target (default)
                              		  ATF_SHORT  = trigger on melee attacks
                              		  ATF_LONG   = trigger on ranged attacks (default: trigger on all attacks)

Problem
=======
bonus3 bAddEff,eff,n,y;  seems works like bAddEffWhenHit (the enemy when being hit by physical damage)

What does it means?
=================
bonus3 bAddEff,eff,n,y; do not work from any magic attack, only from direct physical attack.
Maybe i'm wrong, but my players report to me about many issues about this bonus. Because it's must work with spells too. And i do not see any restriction description about this autobonus at docs.

As about  bonus3 bAddEffWhenHit,eff,n,y, we have precise description about autobonus. (works only from physical attacks)

Regarding to this, i want ask next questions:
===================================
1. Is bonus3 bAddEff,eff,n,y; should work if you use any skill (except physical attacks)? Or explain, how this bonus must works. Because for me, it's works **ONLY** with direct phyisical attacks, and its 100% the same like ***bonus3 bAddEffWhenHit,eff,n,y;***

Bugreport
========
bonus3 bAddEff,eff,n,y; works the same like bonus3 bAddEffWhenHit,eff,n,y; (when hit with direct phyisical attack)

How reproduce
=============
1. Create any class and spawn any monster (for example @spawn 1935)
2. Change 
> 4238,Owl_Baron_Card,Owl Baron Card,6,20,,10,,,,,,,,136,,,,,{ bonus3 bAutoSpell,"PR_LEXAETERNA",1,30; },{},{}

**TO**
> 4238,Owl_Baron_Card,Owl Baron Card,6,20,,10,,,,,,,,136,,,,,{ bonus3 bAutoSpell,"PR_LEXAETERNA",1,1000; },{},{}

*** For 100% chance ***

3. Try to use any different spells and autobonus will not be triggered. 
4. But when you attack target by clear phisical attack without using any spell, you will autocast Lex Aeterna.

### Please Guys, confirm, or or disprove. Because I'm not sure.

**Comment by Playtester** [comment]
Your "how to reproduce" example doesn't even use bAddEff!

Normal autospells only trigger on normal physical attacks and reflect damage.
Normal status effect trigger on any physical damage (also from skills), though some are limited to melee or ranged only.

There are a few more modern items that trigger on spells but then they specifically say so in the description.

See also: http://irowiki.org/wiki/Autocast (for autocasts)

**Comment by nanakiwurtz** [comment]
Summoning @iamnxt, if you don't reply to this issue with additional explanation in the next 2 days, I'll mark this issue as 'Invalid'.

**Comment by iamnxt** [comment]
@nanakiwurtz i'm trust to @Playtester 
So, need to close this issue, and mark it invalid.
I do not have a way to test it on Aegis.
