### ISSUE TITLE
Cannot use Flash Combo at Ghost 3 and above

### ISSUE THREAD

**Issue by reunite-ro** [rathena/rathena#4661]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/1fc4b8de2063c90b74b7da95e3b105306a825c21

* **Client Date**: 20180620

* **Server Mode**: Renewal

* **Description of Issue**: I dont know this is intended or not. But after 16th anniversary patch, Flash Combo isnt working anymore at Ghost 3 element and above mob.

I think because of Tiger Canon code here ? https://github.com/rathena/rathena/blob/1fc4b8de2063c90b74b7da95e3b105306a825c21/src/map/skill.cpp#L3754

If this actually intended, so let me know, ill close this issue.
  * Result: Flash Combo didnt do anything, but the skill will be in cooldown.
  * Expected Result: Can hit mob element Ghost 3 before. I dont know if this is intended or as it should be now.
  * How to Reproduce:  Try to use Flash Combo at Evil Snake Lord or mob element Ghost 3 in Biolab Nightmare Dungeon.

* **Modifications that may affect results**: https://github.com/rathena/rathena/commit/e6a6c0533cf8a232a890e85d702417d3463c0dd1

**Comment by attackjom** [comment]
This bug happen to every  castend_nodamage skill.  with Ghost 3-4 monster
