### ISSUE TITLE
Seem missing mob_avail.yml in db directory

### ISSUE THREAD

**Issue by CairoLee** [rathena/rathena#4662]
* **rAthena Hash**:  97372ff42352cdfbe7bbe6031ab5008e4ec419c4  (master branch)

* **Client Date**: not matter...

* **Server Mode**: Both

* **Description of Issue**: 

Can not find `db/{pre-re}/mob_avail.yml` database, after we change the `mob_avail.txt` to `mob_avail.yml`.

**Comment by CairoLee** [comment]
So far, it's only exists in db/import directory...

**Comment by attackjom** [comment]
mob_avail is a custom feature by default.

So they move its to import folder. You can edit mob_avail.yml in that folder.

**Comment by aleos89** [comment]
As @attackjom stated, since it's a custom feature rAthena won't be supplying data to it. This is why we decided to just have a version live in import as having a main db/ copy will just be redundant.

**Comment by CairoLee** [comment]
thanks for @attackjom  and @aleos89 . i get it now.
