### ISSUE TITLE
Battleground Dual Team

### ISSUE THREAD

**Issue by roSBK** [rathena/rathena#4665]
Well the following, I thought that the BattleGround would have some kind of expansiveness if the max player is activated in the db, but no, I made a test entering with 1x1 and when starting the Battle I entered two more characters, and the other 2 characters entered the field. Battle, duplicating the BattleGround.

These tests were done in KvM and ended up making the former two players stuck, respawn or even being teleported to the battle area.

**Comment by aleos89** [comment]
Fixed in 14c388b.
