### ISSUE TITLE
RE_LVL_MOD

### ISSUE THREAD

**Issue by SeravySensei** [rathena/rathena#4666]
Close this if I'm wrong but...
```
#define RE_LVL_DMOD(val) \
	if( status_get_lv(src) > 100 && val > 0 ) \
		skillratio = skillratio * status_get_lv(src) / val;
```
I think this is incorrect. If val=100 it works as expected but on val=150 for example, it means level 100 will be exempt from the modifier, in other words, on exactly level 100 Mechanic's Flame Launcher deals 1.5 times more damage than intended. I think this should be {level/val} for 3rd job skills and the whole level>=100 business is applicable for transcendent skills available below level 100 only, Same for RE_LVL_MDMOD.
Note : I haven't tested this, only noticed the problem while reading the source.

**Comment by aleos89** [comment]
Correct me if I'm wrong, but I don't recall any non-3rd class skill getting the level bonus modifier.

**Comment by SeravySensei** [comment]
Gravity field and Napalm Vulcan are two examples but there were several transcendent class skills that had this modifier.
Also, while I don't know if any official items grant or autocast 3rd class skills, it's best if the formula does work below level 100 correctly for all skills, just in case Gravity adds any.

**Comment by aleos89** [comment]
I just remembered @flamefury had already confirm [this](https://github.com/rathena/rathena/issues/3715#issuecomment-458775701).
