### ISSUE TITLE
Land Protector behavior option possible broken

### ISSUE THREAD

**Issue by Tydus1** [rathena/rathena#4668]
* **rAthena Hash**: 
1fc4b8de2063c90b74b7da95e3b105306a825c21

* **Client Date**: 
2018-06-21RE

* **Server Mode**: 
Pre-renewal

* **Description of Issue**: 

  * Result: Land Protector Behavior Option is not working
  * Expected Result: Land Protector Behavior Option should be working
  * How to Reproduce: Change land protector behavior option into conf/battle/skill.conf and test. Both values ( 0 or 1 ) will have same effect ( renewal behavior )

  * Official Information: Land protector official behavior do not display AEO skills into LP but players inside it may still take damage if they are in the borders of the LP. The pre-renewal LP behavior blocks completely any AOE damage.

* **Modifications that may affect results**: 
  Skill db conversion to YAML maybe?

**Comment by aleos89** [comment]
Is this the same as #4412?

**Comment by Tydus1** [comment]
Seems like #4412 is about the official behavior from kRO on renewal. https://github.com/cydh/rathena/commit/6de800aea19c99aba5b88a14bfb625a1cf870c85

Back on pre-renewal days, Land protector behavior was different. It used to completely block any AOE if a player stand into LP area. 

Cydh added a 'conf/battle/skill.conf' allowing to change Land Protector Behavior and now it seems to be broken

**Also, I did notice that this implementation was not commited into the rAthena master branch so... you can close this issue if it does count as custom implementation.**

**Comment by aleos89** [comment]
Yeah this is a custom implementation that doesn't exist on the current master. You're welcome to create a Pull Request with the changes needed to add the battle config.
