### ISSUE TITLE
Drops Rate

### ISSUE THREAD

**Issue by alvinlee92** [rathena/rathena#467]
How to Setting As @mi and @rates is the same

Original Setting :

// The rate the common items are dropped (Items that are in the ETC tab, besides card)
item_rate_common: 100
item_rate_common_boss: 100
item_drop_common_min: 1
item_drop_common_max: 10000

// The rate healing items are dropped (items that restore HP or SP)
item_rate_heal: 100
item_rate_heal_boss: 100
item_drop_heal_min: 1
item_drop_heal_max: 10000

// The rate at which usable items (in the item tab) other then healing items are dropped.
item_rate_use: 100
item_rate_use_boss: 100
item_drop_use_min: 1
item_drop_use_max: 10000

// The rate at which equipment is dropped.
item_rate_equip: 100
item_rate_equip_boss: 100
item_drop_equip_min: 1
item_drop_equip_max: 10000

// The rate at which cards are dropped
item_rate_card: 100
item_rate_card_boss: 100
item_drop_card_min: 1
item_drop_card_max: 10000

// The rate adjustment for the MVP items that the MVP gets directly in their inventory
// Mode: 0 - official order, 1 - random order, 2 - all items
item_rate_mvp: 100
item_drop_mvp_min: 1
item_drop_mvp_max: 10000
item_drop_mvp_mode: 0

// The rate adjustment for card-granted item drops.
item_rate_adddrop: 100
item_drop_add_min: 1
item_drop_add_max: 10000

// Rate adjustment for Treasure Box drops (these override all other modifiers)
item_rate_treasure: 100
item_drop_treasure_min: 1
item_drop_treasure_max: 10000

I Wan Setting :

Normal Monster Drops All Item And Card: 60%

MVP Monster Drops EQ/ETC/Common = 40%
MVP Card : 1.00%

can help me about this?
How to Setting As @mi and @rates is the same

**Comment by samurairukasu** [comment]
This is not a bug.

**Comment by alvinlee92** [comment]
ya..i know not a bug..can someone teach me or help me setting that?because i setting keep no diffent with @rates and @mi

**Comment by samurairukasu** [comment]
Make a post in forum for this. 
Any way, @rates only work for base of exp rates and general drop, @mi only for mob drops.

**Comment by alvinlee92** [comment]
ok then..thanks.
anyway hope someone can teach me at here :( 
i am long time never work about ro..just come back to refresh and hope can learn more about rAthena update

**Comment by nanakiwurtz** [comment]
Sorry, this place is for bug report only, you should ask for help on the forum.
Thank you for your cooperation.
Closed.
