### ISSUE TITLE
NPC Outside Instance didn't have Instance ID

### ISSUE THREAD

**Issue by Litro** [rathena/rathena#4670]
* **rAthena Hash**: 968b43c

* **Client Date**: N/A

* **Server Mode**: Both

* **Description of Issue**: 
  * Result: 
  * Expected Result: 
  * How to Reproduce: Use the script on sample folder https://github.com/rathena/rathena/blob/master/doc/sample/instancing.txt, reentering will be skipped because `instance_id()` script command always get 0
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by sader1992** [comment]
that because it was made to be attached to the characters , the doc folder is not up to date with the last changes to the instance system
in the sample script , try to change the `instance_id()` to `instance_id(IM_PARTY)` and the script should work

**Comment by Litro** [comment]
true, but the script not defaulted to the player when it was run by npc with player attached, i was thinking the script should check if there is player attached if not then set npc as default

**Comment by Atemo** [comment]
In the case of multi instances type (instance type `IM_PARTY` and `IM_GUILD` running at the same time for example) `instance_id()` could return a wrong instance ID before https://github.com/rathena/rathena/pull/4090

So the 'auto check of the instance ID attached to the player' part has been removed, now you need to provide the instance type in `instance_id` command.
```
// IM_PARTY and IM_GUILD instance type are running
mes "Your instance ID of instance type party is " + instance_id(IM_PARTY);
mes "Your instance ID of instance type guild is " + instance_id(IM_GUILD);
close;
```

**Comment by OptimusM** [comment]
I dont know if it is related but, on kRO when u log off or disconnect or something, u still logged inside the instance map for 5 minutes, u can change character and send u stuff by rodex from other character on the account if u ned something and re conect to your instance map within 5 minutes.
