### ISSUE TITLE
ShowEvent

### ISSUE THREAD

**Issue by alvinlee92** [rathena/rathena#468]
arza,148,135,6	script	Freebie	671,{

if(##sorry == 2) goto L_1;
mes "Welcome to Test Ragnarok Online " + strcharinfo(0) + " !!";
next;
mes "So You Is A New Player Here Right?";
next;
mes "Enjoy playing at Test Ragnarok Online. We hope you can invite more player's to here.";
// next;
	getitem 12210,5;
       zeny += 500000;
announce "[Server] We have wew player joining our server. His name is [ "+strcharinfo(0)+" ] take this item go leveling! Enjoy Your Self!",2;
emotion e_thx;
set ##sorry,2;
close;

L_1:
mes "Hey! you Already Get Reward From Me.";
mes "Sorry I cant give you anymore again more than 1 times or Administrator will kill me and removed me from GM Team.";
next;
mes "Please do not press me unless you are new player here!";

	message strcharinfo(0), "QTYPE_EVENT2 ("+ QTYPE_EVENT2 +")";
	showevent QTYPE_EVENT2, 3;	// 0x05, ? event icon, purple mark
	end;

}

when touch then have emotion.
how i can do it even i never touch..still have emotion at showing.
looking someone help..

**Comment by jeanroyce** [comment]
Hey bro, I think this is not a bug, you'd better ask that kind of support to the forum.
https://rathena.org/board/

**Comment by cydh** [comment]
what is this? a support question?
