### ISSUE TITLE
Script command INPUT always 0 value

### ISSUE THREAD

**Issue by rofasindo** [rathena/rathena#4681]
* **rAthena Hash**: 91c9c6f8272a5d296d51c98e7a38bd385c8fa82e

* **Client Date**: 2018-08-29

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: 
  * Expected Result: 
  * How to Reproduce: Go to refine place and buy some materials on Vurewell (Phracon or Emveretarcon). input any value and you will see that the value  return to 0.
![screenRO1 - Expertise000](https://user-images.githubusercontent.com/24239587/75798861-c689d780-5da9-11ea-8342-9b73d2dd3a23.jpg)
![screenRO1 - Expertise001](https://user-images.githubusercontent.com/24239587/75798868-c984c800-5da9-11ea-91b3-e878b32aa726.jpg)

  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Daegaladh** [comment]
Cannot reproduce this, at least on pre-re

**Comment by Lemongrass3110** [comment]
Still unable to reproduce and no further comments in over a month.

**Comment by pwahono** [comment]
error on Merchant Buying Store Trader on Alberta, 
but not phracon npc,

almost same script 
input .@input;
