### ISSUE TITLE
ItemID 4529 (Cruel_Coelacanth_Card) No Effect (Physical Damage/Atk)

### ISSUE THREAD

**Issue by reunite-ro** [rathena/rathena#4683]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/35b2f69530ca609721322266a057aa8bcbd0be53

* **Client Date**: 20180620

* **Server Mode**: Renewal

* **Description of Issue**: ItemID 4529 (Cruel_Coelacanth_Card) No Effect on additional physical damage even for high refine item.
  * Result: Physical Damage is not increasing.
  * Expected Result: Physical Damage increasing.
  * How to Reproduce: Slot ItemID 4529 (Cruel_Coelacanth_Card) at +20 refine headgears and see the physical damage difference.

**Comment by Atemo** [comment]
The additional physical damage only affects the equipment attack on renewal. If you tried only with bare hand you won't see any change, otherwise it will depend of your equipment.

**Comment by reunite-ro** [comment]
Ive tried using Sword [3] and attack dummy, mostly damage 401~403
![screenReunite Ragnarok On207](https://user-images.githubusercontent.com/11705163/75893463-cce18780-5e6d-11ea-90b2-2025a4657423.jpg)

When equip +20 Cap [ItemID 4529 (Cruel_Coelacanth_Card)], the damage 405~408.
![screenReunite Ragnarok On209](https://user-images.githubusercontent.com/11705163/75893651-1df17b80-5e6e-11ea-912e-bc39ee4a310f.jpg)

Is it true about the increment damage ?

**Comment by Atemo** [comment]
The weapon attack of Sword [3] is 50. To resume and simplify, your damage increases of (12 x 50) % = 6 with the card in a equipment refine at +20. The calcul matchs with your test.

**Comment by reunite-ro** [comment]
I see, ill close this issue.
