### ISSUE TITLE
[Error] skill_damage_db.txt

### ISSUE THREAD

**Issue by Tutankhaten** [rathena/rathena#4690]
* **rAthena Hash**: 5c35ec7d69ccbe1c3cc7b77997ab016858ea156c

* **Client Date**: 

* **Server Mode**: Pre-renewal and Renewal

* **Description of Issue**: 
  * Result: "skill_parse_row_skilldamage: Invalid damage   given for skill 523, defaulting to 0."
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by secretdataz** [comment]
You missed the "How to Reproduce".

**Comment by Tutankhaten** [comment]
How to Reproduce: NJ_SYURIKEN,BL_PC,1,50 // Throw Shuriken
