### ISSUE TITLE
Devotion + autoguard/defender

### ISSUE THREAD

**Issue by kiri02** [rathena/rathena#4691]
RAthena Hash : Latest
Client Date : 2017-06-14

Server Mode : Pre-Renewal
Description of Issue: After our server has gone from eAthena to rAthena, some people believes that autoguard no longer transmit through devotion from a paladin to a party member. but I think there are some potentially buggy reasons for why this is believed. The main thing is that, the autoguard effect does not display on the devo'd target, but displays on the paladin, and indeed does transmit and blocks incoming physical attacks as expected. This in itself is not an issue, really.

I have noticed, however, if the paladin has autoguard cast before casting devotion, the autoguard effect is not transmitted, which may lead to why people believe autoguard no longer transmits to party members. I believe this may be a bug, and my reasoning for believing that is because defender does not operate this way. If you have defender active prior to devotion, it still transmits to a fresh devotion target and does not need to be canceled and reactivated.
Our server owners have not have not touched that part of the source, and they suspect it's an rAthena issue.

**Comment by Daegaladh** [comment]
> The main thing is that, the autoguard effect does not display on the devo'd target, but displays on the paladin

> If you have defender active prior to devotion, it still transmits to a fresh devotion target and does not need to be canceled and reactivated.

I'm not sure about this, specially the second. We would need some kind of proof (official server videos or something) to check this out

**Comment by kiri02** [comment]
Video : https://puu.sh/Fi96E.mp4
This is from our server, running in rAthena. Demonstrating that either way, there is an issue, because autoguard and defender operate differently and autoguard definitely does not display on the devotioned target but only on the paladin but it still procs.

**Comment by aleos89** [comment]
This is related to #722.
