### ISSUE TITLE
Class Re-balancing Update for Bowling Bash Knight

### ISSUE THREAD

**Issue by violent01** [rathena/rathena#4693]
* **rAthena Hash**:  Latest Release.

* **Client Date**: Doesn't Matter.

* **Server Mode**: Renewal

* **Description of Issue**: Bowling Bash damage doesn't match what kRO did with their update. 
  * Result:  The damage dealt with one-hand sword or spears should be 2 hits only regarding of how many enemies within 5x5 cells of the target monster but instead the damage result is like 4 hits because of the stacked damage of the skill, likewise if you equip two-handed swords the damage can soar up to 8 hits (because of stacked damage) if there are 4+ monsters in the 5x5 cell of the target monster which i believe should be 4 hits only at max.
  * Expected Result: One-hand sword, Dagger, Spear or Two-handed Spear = maximum of 2 hits within 5x5 cells of the target monster. Two-handed sword = maximum of 4 hits if there are 4+ monsters in the 5x5 cell of the target monster. Check the kRO GIF so you can understand much better what I'm trying to say here. See the white numbers in the GIF it has no stacked damage unlike what you can see if you test it on your own server.
![T0SU3XXWLNB8DCLQ9PLK](https://user-images.githubusercontent.com/30449376/76147455-60ed6200-60ad-11ea-9684-6c4960f85416.gif)

Here is an example of what i mean.
![for github](https://user-images.githubusercontent.com/30449376/76150091-9a2acf80-60b7-11ea-993a-d341368fca3a.jpg)

  * How to Reproduce:  Just run rAthena and then test it.
  * Official Information:
  

* **Modifications that may affect results**: None modified.

**Comment by reigneil** [comment]
https://youtu.be/JOE9qMZvHu4
