### ISSUE TITLE
Songs & Ensembles does not have any visual skill effect

### ISSUE THREAD

**Issue by violent01** [rathena/rathena#4698]
* **rAthena Hash**: Latest

* **Client Date**: 20180621 below

* **Server Mode**: Renewal

* **Description of Issue**: Songs, Dances and Ensemble Skills has no visual animation.
 
My question is, is there any chance that i can revert the old songs, ensemble skill visual animation while keeping the new update?

**Comment by aleos89** [comment]
This is a client limitation, not rAthena. Once the newer clients are supported they will show up just fine.
