### ISSUE TITLE
Ankle Snares

### ISSUE THREAD

**Issue by kiri02** [rathena/rathena#4699]
RAthena Hash : Latest
Client Date :  2017-06-14

Server Mode : Pre-Renewal
Description of the issue : Ankle snares can often trap you even when you don't click on cells that should trap you, and you're also allowed to move far beyond them without ever knowing you were trapped. This isn't just a visual bug either, as you actually are in the position very far beyond where the trap was laid and can potentially be completely out of range or view of the trap with no way of knowing you were ever caught.

The video shows a hw spam clicking trying to move in any direction and remove the trap with sightrasher. One sightrasher under normal conditions and this only being position lag/a visual bug would normally destroy an ankle snare, but none can even connect. Ganbantein is also not an option as the hw is actually completely out of range to the trap. It's only apparent the hw was ever trapped once it despawns and movement is restored.

Video : https://imgur.com/X0PICNs

**Comment by Playtester** [comment]
In WoE this is official behavior because there's no knockback in WoE, the trap won't stop you, it will just make you immobile. You will still walk to the target cell you clicked on, unless you are stopped by taking damage.
