### ISSUE TITLE
MVP Rewards Drop Missing But Data Listed in Mobdb

### ISSUE THREAD

**Issue by reunite-ro** [rathena/rathena#4700]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/f8d5d45b9b71c0a6e0b2bc48d134196e97e98c0d

* **Client Date**: 20180620

* **Server Mode**: Renewal

* **Description of Issue**: MVP Rewards Drop Missing from @monsterinfo + @whodrops. I dont know if its happen to any other MVP, didnt check it yet properly but the data is at the mobdb.
  * Result: Tried @mi 1650 or @whodrops 1723 its not listed but its shown in mobdb

`1650,B_SHECIL,Sniper Shecil,Sniper Cecil,160,4140000,1,4106880,3080160,14,4155,1550,178,135,176,258,155,132,309,95,10,12,1,7,84,0x6283695,100,76,384,288,2053440,617,5500,603,5000,1723,2000,1228,3500,6471,10000,617,9000,12623,10000,1237,3500,1720,1500,1724,2500,0,0,0,0,4367,1` 
  * Expected Result: Luna Bow (ItemID 1723) and any other items (if any) will be shown too.

**Comment by aleos89** [comment]
`@mi` will show the normal drops and MVP prizes as long as the mob has MVP EXP. `@whodrops` only lists normal monster drops, not MVP prizes.

**Comment by reunite-ro** [comment]
So does it means that it wont show the MVP prizes even its stated as MVP prizes in mobdb (when the mob doesnt have MVP EXP ?

It shows only Old Purple Box meanwhile 617,5500,603,5000,1723,2000 also there in mobdb. Only 1 items shown as in the picture.

![image](https://user-images.githubusercontent.com/11705163/76316304-53d2ac00-6315-11ea-9d43-47209e76bb8b.png)

**Comment by Angelic234** [comment]
Because if there are 3 MVP drops at 50%, the first has a chance of 50%, the second 25% and the third 12.5%.
If the first has a chance of 100%, the second will be 0%(in your picture).

**Comment by reunite-ro** [comment]
So it wont be droppped or it wont be list in @mi only ?

**Comment by aleos89** [comment]
You can find a detailed explanation in the commit here: 5110ddbaf47c358a4a656c32043eb9973b3cd0ab

This is working as intended.
