### ISSUE TITLE
Class Re-Balancing Update Back stab skill [Rogue]

### ISSUE THREAD

**Issue by violent01** [rathena/rathena#4702]
* **rAthena Hash**: Latest

* **Client Date**: 20180621

* **Server Mode**: Renewal

* **Description of Issue**: Back stab behavior do not match the current update.
  * Result: Back stab behavior is currently old.
  * Expected Result:  Back stab skill should do double hit if equipped with a dagger class weapon.  Back stab should not be usable if the player is in the hiding state.
  * How to Reproduce:  
  * Official Information:  https://www.divine-pride.net/forum/index.php?/topic/3453-kro-mass-skills-balance-1st-2nd-and-transcendent-classes-skills/

9.2 Back Stab
- Changes skill mechanism, moves to target's back immediately and deals damage. Can't be used while under Hiding state.
- If user equips dagger, increases number of hit to twice.

![github](https://user-images.githubusercontent.com/30449376/76267043-8380a600-627a-11ea-9c92-966f3dedddd6.gif)

  

* **Modifications that may affect results**: None

**Comment by hangovernice** [comment]
d
