### ISSUE TITLE
Job Improvement Project - Warlock

### ISSUE THREAD

**Issue by OptimusM** [rathena/rathena#4706]
* **rAthena Hash**: N/A

* **Client Date**: N/A

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result:  Several skill effects were updated for Warlock.
  * Expected Result:  Update these to comply with kRO.
  * How to Reproduce:  Usage of any Warlock skill.
  * Official Information: http://ro.gnjoy.com/news/update/View.asp?seq=239&curpage=1  https://www.divine-pride.net/forum/index.php?/topic/3723-kro-classes-improvement-project/&do=findComment&comment=5902
  

* **Modifications that may affect results**: 
  
   None

This Warlock Update was way back than GX update, it was on 2019.07.17 so, it would be great to have that before future updates.
Thx for the grat work ~!

**Comment by aleos89** [comment]
It's on my list. Warlock came out 2 months before the Guillotine Cross update but the Warlock changes are in much more detail. I just chose the lesser of two evils for now.

**Comment by LordWhiplash** [comment]
is there some preview about the warlock improvement?

**Comment by aleos89** [comment]
I'm done with it but it's being held up because of the item ID limit. The new Warlock Spellbooks are in the 100k range.

**Comment by Haydrich** [comment]
> I'm done with it but it's being held up because of the item ID limit. The new Warlock Spellbooks are in the 100k range.

rAthena still not support more than 65k id ?
when will rAthena support?

**Comment by LordWhiplash** [comment]
got it, thanks!

**Comment by LordWhiplash** [comment]
Hi aleos, is it possible to have a provisional release of warlock updates and genetic potions, where we use IDs lower than 65k that are not being used? and after rathena is adjusted to support the right ids we would simply put the items in the right place... i'm kinda anxious to use warlock changes haha

**Comment by Masao87** [comment]
Will this be released once the 2020 client support is available?

**Comment by LordWhiplash** [comment]
I believe It is more related tô ultra high ID supports than tô client 2020 itself
