### ISSUE TITLE
bHPDrainValue damages plant monster more than 1

### ISSUE THREAD

**Issue by AbuGosok** [rathena/rathena#471]
I do not know why it's happened.

Basically, I create an item/weapon with bonus bHPDrainValue,25 for example.

This will cause Emperium to break really fast, as if it damages more than 1, but the damage would not show.

Normally whatever the effect, the plant should not take damage more than 1 right?

**Comment by cydh** [comment]
seems this is true, in battle_drain there's no check if the target 'is_infinite_defense' or not. maybe can be happened with Drain & Gain
