### ISSUE TITLE
Arrow Vulcan Action Delay Issue

### ISSUE THREAD

**Issue by reigneil** [rathena/rathena#472]
I've tested it in iRO and compare their behavior and what i see is...
Arrow Vulcan has a minimal to no action delay instead you are prevented to use damaging skill similar to what @Playtester did at Gravitational Field. that is if you try another Arrow Vulcan within the duration of the skill nothing happen.

**Comment by Playtester** [comment]
If it's like Gravitational Field, that means you can still use another skill, they just won't deal damage. Does that mean you can heal / buff while using Arrow Vulcan?

**Comment by anacondaqq** [comment]
I can't confirm. I do not know how at iRO, but Arrow Vulcan looks works like it must.
1 second action delay (you can remove delays from sprite, and delay will be removed)
I think, imposible to make it smaller, then 1 second without editing game client files.
![](http://i.imgur.com/utO83Qv.png)

**Comment by reigneil** [comment]
![screenthor016](https://cloud.githubusercontent.com/assets/9740000/8282149/12010422-1921-11e5-9cc9-6460604eb7a0.jpg)

this is my SS from iRO i can use heal right after arrow vulcan

**Comment by Playtester** [comment]
This is invalid.

In fact, this is a iRO customization: http://forums.warpportal.com/index.php?/topic/37452-maintenance-may-26/
(That only some spells can be cast is simply client sided and can easily be hacked.)

On kRO the skill has a normal 2 second aftercast delay.

**Comment by reigneil** [comment]
i compare this on a test server.. and it proves that it is invalid.
