### ISSUE TITLE
Skill points are gone when changing from trans to gunslinger to trans class again.

### ISSUE THREAD

**Issue by RadianFord** [rathena/rathena#4720]
* **rAthena Hash**: 930f52e31f465b574502b8037cf11ba6dc39b2ba

* **Client Date**: 2017-06-14bRagexeRE

* **Server Mode**: Pre renewal

* **Description of Issue**: Skill points are missing when you switched from Clown into Gunslinger and switched again to Clown class.
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by RadianFord** [comment]
Is there any related issues like this? did anyone somehow encounter this problem?

**Comment by aleos89** [comment]
That's because you're changing to a job that doesn't share a similar skill tree. You need to reset skills before changing to a different job class.
