### ISSUE TITLE
Hell's gate and Throw Spirit Spheres consume incorrect amount of spheres and sp

### ISSUE THREAD

**Issue by someonenoone11** [rathena/rathena#4721]
rAthena download date: 03/10/2020
I think the SHA is 36a02685d50fae4d4203498a953dd0b318315b7b

* **Client Date**: Unknown. rAthena did not have a decent updated client tutorial so I had to copy and paste a client from a Hercules repack and copied/paste the data and rdata from a 01/24/2020 client. I doubt client is the issue.

* **Server Mode**: Renewal

* **Description of Issue**: 
Hell's Gate only consumes 2 Spirit Spheres instead of 5.
Hell's Gate does not consume 30% of SP upon use. It uses a significantly less amount.
Throw Spirit Spheres consume only 1 Spirit Spheres regardless of level. It should consume 5.
Throw Spirit Spheres hits 5 times despite consuming only 1 spirit sphere. It should only do 1 hit per spirit sphere consumed.

**Comment by OptimusM** [comment]
https://github.com/rathena/rathena/pull/4256

Try to look a little before open an issue about it.

**Comment by aleos89** [comment]
As @OptimusM stated, this was a change in the Sura Job Improvement update from kRO.
