### ISSUE TITLE
Sonic Blow and Cross Impact do not prevent auto attacks.

### ISSUE THREAD

**Issue by someonenoone11** [rathena/rathena#4722]
rAthena download date: 03/10/2020
I think the SHA is 36a02685d50fae4d4203498a953dd0b318315b7b

* **Client Date**: Unknown. rAthena did not have a decent updated client tutorial so I had to copy and paste a client from a Hercules repack and copied/paste the data and rdata from a 01/24/2020 client. I doubt client is the issue.

* **Server Mode**: Renewal

* **Description of Issue**: 
When casting Sonic Blow or Cross Impact, the correct behavior is that I must wait until the animation finishes before resuming auto attacks.
What is actually happening is that I can attack immediately after casting, resulting in the attacks and the Sonic Blow/Cross Impact animation both happening simultaneously side by side.

**Comment by aleos89** [comment]
In recent updates, Sonic Blow and Cross Impact no longer have server side after cast delays. If you are still seeing a delay then there is a client patch you are missing for that specific skill/animation.
