### ISSUE TITLE
Custom config for NPC EMOTION skill

### ISSUE THREAD

**Issue by victorgawk** [rathena/rathena#4727]
* **rAthena Hash**: 14d2686cf

* **Client Date**: 2015-11-04aRagexe

* **Server Mode**: Pre-Renewal

* **Description of Issue**: Add a custom config for NPC EMOTION skill
  * Result: On official servers, certain mobs cast NPC EMOTION skill which displays an emoticon and change their mode from Aggressive to Passive for a certain time.
  * Expected Result: The old Athena behavior do not change their mode to Passive.
  * How to Reproduce: Try mob a few High Orcs in `gef_fild14` map. You notice that they will completely drop the aggro, and even though you go back to them they will ignore you for a certain time.
  * Official Information: The current result is working like official. This issue is intended to create a custom battle config option which allows to modify NPC EMOTION skill to work like Athena behavior.

  

* **Modifications that may affect results**: 
Create a config which allows to change NPC EMOTION to work like Athena behavior.

**Comment by SeravySensei** [comment]
Agreed, such an option would be extremely useful.
I had to remove that NPC_EMOTION from all my mobs one at a time.

**Comment by Lemongrass3110** [comment]
Fixed in 044aceb
