### ISSUE TITLE
memleak by channel_create

### ISSUE THREAD

**Issue by cydh** [rathena/rathena#473]
Just noticed, if more than 2 autotrader join in same guild. each autotrade will attempt to create ally channel.
yes, there is a check before creating a new channel in `guild.c::channel_gjoin`. but it'll makes guild channel more than once, that makes the *last* created channel is the valid channel and will be freed, the rest aren't.

````
	/* "ally_channel" is a channel shared by all your guild allies. */
	ally_channel_enabled: true
	ally_channel_name: "ally"
	ally_channel_color: "Green"
	ally_channel_autojoin: true
````

**Comment by aleos89** [comment]
Maybe we should make it so autotraders don't join/create a channel since they can't be read anyways.

**Comment by RadianFord** [comment]
@aleos89 its true autotrades cant see what is going on in the channels.
