### ISSUE TITLE
Lv. 5&Lv.4 NC_ARMSCANNON skill no cast time

### ISSUE THREAD

**Issue by Surefirer** [rathena/rathena#4730]
* **1dd95bcce0e42bc62865a20b6174dcca75f4a88c**: 

* **20180831**: 

* **Renewal**: 

* **SKID.NC_ARMSCANNON skill no cast time. Not sure about KRO official behavior, but it has cast time before I updated to the lastest version of ra.**: 
  * Result: 
  * Expected Result: 
  * How to Reproduce: try use NC_ARMSCANNON level 5 and level 4, you can use the skill with no cast time, and delay.
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by OptimusM** [comment]
This is the oficial update of Arms Cannon Cooldown.
https://ragnarok.gamepedia.com/RO_Patch_(2018_Oct._17)

**Comment by flamefury** [comment]
https://replay.divine-pride.net/Replay/d3e47f30
Made a recording for each level on a Mech.

Skill cool down added Oct17, as noted by above patch link (verifiable using HEADER_ZC_SKILL_POSTDELAY packets):

> - 암즈 캐논 스킬의 쿨타임이 추가됩니다.
> 　1레벨 > 0.15초
> 　2레벨 > 0.20초
> 　3레벨 > 0.30초
> 　4레벨 > 0.45초
> 　5레벨 > 0.65초

After cast delay appears to be 1s for every level, can be verified by HEADER_ZC_MSG_STATE_CHANGE3 packets.

HEADER_ZC_USESKILL_ACK2's delaytime value appears to be the cast time (variable+fixed), but it's rather confusing to me. The Mech I used for that recording was 2 DEX, 3 INT. Yielded the following cast times:

1. 1839ms
2. 1816ms
3. 1993ms
4. 1970ms
5. 2147ms

https://replay.divine-pride.net/Replay/c77e63ad
Contains a replay after I upped my DEX to 131 and INT to 37. Delaytime values became:

1. 948ms
2. 798ms
3. 848ms
4. 697ms
5. 747ms

Dunno if that's enough to figure out the Fixed+Variable of each level. I'll try to math it out later.

**Comment by flamefury** [comment]
Scratch later, couldn't sleep until I solved it. I abused WolframAlpha by plugging in my cast times and stats as so:
`F+V*(1-sqrt(7/530)=result1,  F+V*(1-sqrt(299/530)=result2`
Where F is fixed cast time, V is variable cast time
sqrt(7/530) was my stat-based cast time reduction on the first trial, while sqrt(299/530) was the stat reduction for the second trial.
result1 is the first trial result for that level, result2 is the second trial result for that level.

eg, [my Lv5 calculation](https://www.wolframalpha.com/input/?i=F%2BV*%281-sqrt%287%2F530%29%29%3D2147%2CF%2BV*%281-sqrt%28299%2F530%29%29%3D747)

Doing that for all levels gave me the following cast time results:
1. F=600,V=1400
2. F=400,V=1600
3. F=400,V=1800
4. F=200,V=2000
5. F=200,V=2200
