### ISSUE TITLE
New Special Pharmacy Potions

### ISSUE THREAD

**Issue by aleos89** [rathena/rathena#4732]
* **rAthena Hash**: 652d77e

* **Client Date**: N/A

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Need new potions for Special Pharmacy.
  * Expected Result: Add new potions. Requires item ID expansion.
  * How to Reproduce: Unable to craft these items.
  * Official Information: http://ro.gnjoy.com/news/update/View.asp?seq=246&curpage=1
* **Modifications that may affect results**: None

```
Adds new 3 buff potions and 3 recovery potions.

Golden X (ID: 100231)
Reduces damage taken from melee reflect damage by 100% for 30 seconds.
Weight : 3

Red Herb Activator (ID: 100232)
Increases melee physical damage and long ranged physical damage by 15% for 500 seconds.
Weight : 3

Blue Herb Activator (ID: 100233)
Increases all property magical damage by 15% for 500 seconds.
Weight : 3

Concentrated Red Syrup Potion (ID: 1100004)
Recovers about 675 HP
Require Level : 120
Weight : 0.2

Concentrated Blue Syrup Potion (ID: 1100003)
Recovers about 360 SP
Require Level : 120
Weight : 0.2

Concentrated Golden Syrup Potion (ID: 1100005)
Recovers about 2750 HP
Require Level : 180
Weight : 0.2
```

**Comment by Haydrich** [comment]
this items need to add in item db?
or edit on src?

**Comment by aleos89** [comment]
They need to be added to the item database, but rAthena currently doesn't support item IDs over 65k. Once the support is there these can be added.
