### ISSUE TITLE
Job Master Issue

### ISSUE THREAD

**Issue by reunite-ro** [rathena/rathena#4735]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/652d77eb0287a13fca25d47eb5317de1b538fe87

* **Client Date**: 20180620

* **Server Mode**: Renewal

* **Description of Issue**: Since I saw this issue in forum and experience this issue a lot, I think we should make some changes about it.

The option for rebirth and 3rd job : 
Players sometimes confused why they stuck at High First job, its because of they didnt rebirth and choose to change to 3rd job early. It will results to 'Change to Unknown Job class' at the end.
![screenReunite Ragnarok On222](https://user-images.githubusercontent.com/11705163/77646091-d8bcf700-6f9e-11ea-990c-2f85c79eeab2.jpg)

I dont know in official either they cant rebirth or should stuck there but if yes, then we should remove the 'Unknown Job class' option then. 

Since they stuck there, they can keep talking to NPC to change to Unknown Job class and redeem any freegifts set in the NPC multiple times.
![screenReunite Ragnarok On223](https://user-images.githubusercontent.com/11705163/77646642-e626b100-6f9f-11ea-9936-166884e93bed.jpg)

  * How to Reproduce: Change job using Jobmaster NPC

**Comment by 0n3G** [comment]
###
