### ISSUE TITLE
Minor doc missing and db wrong function.

### ISSUE THREAD

**Issue by kaninhot004** [rathena/rathena#4746]
* **rAthena Hash**: bdd63022a

* **Client Date**: 20180620

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Missing some doc, Some item had wrong bonus type, Some item missing semicolon.
  * Expected Result: -
  * How to Reproduce: I had create pull request of fix in pull requests.
  * Official Information: -

* **Modifications that may affect results**: -

**Comment by 0n3G** [comment]
@dtf

**Comment by kaninhot004** [comment]
Closed. (8368ce20c)
