### ISSUE TITLE
Roulette Warning:

### ISSUE THREAD

**Issue by samurairukasu** [rathena/rathena#475]
@aleos89 , i find another warning for roulette:
![roulette](https://cloud.githubusercontent.com/assets/9656445/8267801/f7c07946-1743-11e5-9598-a38e6733abf5.JPG)

And when u click on roulette icon in game 
![icon](https://cloud.githubusercontent.com/assets/9656445/8267815/8eb0bffa-1744-11e5-9778-04acdef19365.JPG)
:
![roulette2](https://cloud.githubusercontent.com/assets/9656445/8267812/5f28d5e2-1744-11e5-8821-d1d6281e3837.JPG)

Regards

**Comment by joelolopez** [comment]
confirmed

**Comment by lelouch22** [comment]
I confirm this also

itemdb.c: In function 'itemdb_roulette_free':
itemdb.c:1158: warning: unused variable 'j'
