### ISSUE TITLE
Pillar of Spirit Killing Time - Bangungot Hospital Instance

### ISSUE THREAD

**Issue by reunite-ro** [rathena/rathena#4755]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/6edcf4a3a1112393a96129422050974663e39a3c

* **Client Date**: 20180620

* **Server Mode**: Renewal

* **Description of Issue**: Confusion regarding Bangungot Hospital Killing Time
  * Result: If Pillar of Spirit is not killed within 30 seconds, it will respawn with full HP. 
  * Expected Result: I dont have any exact information about this, but most guides are saying that the time limit is 1 minute, not 30 seconds. 
Source : NovaRO, iRO, Limit RO guides. 
If its should be in 30 seconds originally, tell me and Ill close this issue. 
  * How to Reproduce: Try to walkthrough Bangungot Hospital Instance.

```
OnTimer30000:
	donpcevent instance_npcname("#Summon Pillar") + "::OnReset";
	end;
OnTimer31000:
	mapannounce 'map_name$, "Bangungot: Hahahahaha!! I'm back with the power from the pillar of spirit!!!",bc_map,"0xFF82FF";
	donpcevent instance_npcname("#Summon Pillar") + "::OnReset";
```

**Comment by Atemo** [comment]
Unless it has been changed in later version the time limit is 30s on this part of the instance, according to the leak.
