### ISSUE TITLE
Autoloot commands not working correctly.

### ISSUE THREAD

**Issue by ecdarreola** [rathena/rathena#4756]
* **rAthena Hash**:  6edcf4a

* **Client Date**: 20180621a or 20180919

* **Server Mode**: Renewal

* **Description of Issue**: When using `@autoloot`, `@alootid` or `@aloottype` sometimes the items are not going to the inventory directly. It is shown on the floor.
  * Result: e.g. at autoloot 100, there's an instance that items are not being looted and just appear on the ground.
  * Expected Result: be looted immediately. 
  * How to Reproduce: Use the command.
  * Official Information: N/A
  

* **Modifications that may affect results**: PR requests (Class Improvements - RK, GX, Wanderer, Kagerou/Oboro, Rebellion, Achievements) - I don't see this as conflict since it doesn't touch any of the autoloot code.

**Comment by Daegaladh** [comment]
Do you have homunculus_autoloot and hom_idle_no_share enabled?

**Comment by ecdarreola** [comment]
@Daegaladh I have them both disabled.

**Comment by aleos89** [comment]
Are you the one making the kill or are you using some support (pet, homunculus, mercenary) to make the kill?

**Comment by ecdarreola** [comment]
@aleos89 character making the kill no support from mobs, mercenary or homunculus.

Caveat: haven't tried autoloot using homunculus, or mercenary.

**Comment by Daegaladh** [comment]
@ecdarreola have you tried my PR #4761 ?

**Comment by ecdarreola** [comment]
Haven't tried yet. Just saw the PR. Will try later. Thank you.

**Comment by ecdarreola** [comment]
@Daegaladh : PR didn't work or didn't solve the issue.

Additional findings.. both tested with or without renewal drop.
- Loots are not going directly to the inventory if the difference between the mob and player level is 30.

I assume that the autoloot is being affected by penalty table even it is commented or not.

Testing scenario:
Job Rune Knight at level 1 allstats 25000 and uses @autoloot 100
Summon Raydric which is level 115
Kill monster until level 85 - it will not automatically loot. At level 86. it works pefectly.

**Comment by ecdarreola** [comment]
Additional findings:
Which invalidates above, even at same level with raydric there are instance that the item are not being autolooted to the inventory.

Not sure if drop rate is the culprit, I've tested drop rate of 10x - 100x and 1000x

**Comment by ecdarreola** [comment]
I uploaded a video of what is happening lol. See link below.

https://youtu.be/6NJ4lT7OMq0

**Comment by aleos89** [comment]
Was this closed because it was something on your end?

**Comment by ecdarreola** [comment]
@aleos89 unfortunately yes. An error on my end. Apologies and thanks for initially checking it.
