### ISSUE TITLE
Skill Undefined (pc validate skill issues)

### ISSUE THREAD

**Issue by reunite-ro** [rathena/rathena#4757]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/ad820c168b167ec71fb69472fc5e6e93bc826ae6

* **Client Date**: 20180620

* **Server Mode**: Renewal

* **Description of Issue**:  Im having map server crash issue. I didnt check throughly yet using GDB, but from logs that I saw, its regarding genetic skills that have been added in the few last commit.
  * Result: I have map crash issue and I saw 'pc validate skill undefine' issue a few lines before it happens.

![image](https://user-images.githubusercontent.com/11705163/78168064-f64bfe00-7481-11ea-9fae-5fa10120818e.png)

  * Expected Result: No map server crash/error issue or the skills should be use or not, sorry I dont have much information about this.

* **Modifications that may affect results**: https://github.com/rathena/rathena/commit/652d77eb0287a13fca25d47eb5317de1b538fe87

**Comment by aleos89** [comment]
It's from the few skills that are getting removed from the 3rd classes. They shouldn't cause a map server crash. I forgot to provide a SQL update to dump the skills.

It's not really a threat as the first login will show that and after the player data saves it will be fine after. A skill reset will also give the skill points back.

**Comment by reunite-ro** [comment]
I see. Then should close this issue after this warning gone for the next commit.

About the map crash Issue ill check throughly later on.

**Comment by reunite-ro** [comment]
@aleos89  I have reports said that the skill reset will not give the skill points back.

For example, Job level 65, but will require 59 skillpoints available to up genetic skills (need to fill up 1st job, 2nd job skill first). Should be 64 available skill points should be able to up genetic skills already.

**Comment by reunite-ro** [comment]
Confirmed it. They should have 182 skill points (49+69+64)after reset (for 65 job level 3rd trans), but they have around 177~180 only.

**Comment by aleos89** [comment]
A quick fix for characters that have already logged in:
1. Make sure their skills are reset and they are offline.
2. Run this query:
```sql
UPDATE `char` c SET `c`.skill_point = (SELECT `value` FROM `char_reg_num` crn WHERE `c`.char_id = `crn`.char_id AND `key` = 'jobchange_level') + (SELECT `value` FROM `char_reg_num` crn WHERE `c`.char_id = `crn`.char_id AND `key` = 'jobchange_level_3rd') + `c`.job_level - 1;
```

I'll commit a SQL Update for players who haven't logged in.
