### ISSUE TITLE
wrong values in Sura skill_tree

### ISSUE THREAD

**Issue by le0shadow** [rathena/rathena#4760]
* **rAthena Hash**: ad820c168

* **Client Date**: 2018-10-31

* **Server Mode**: Renewal

* **Description of Issue**:
Some skills in the Sura skill tree have either wrong values of Skill-IDs or Skill levels as pre-requisite (all 3 classes - regular, trans and baby)
 * Result: 

(Using the lines for transclass)
Fallen Empire has level 3 of Dragon combo as pre-requisite:
`4077,2329,10,2326,3,0,0,0,0,0,0,0,0 //SR_FALLENEMPIRE#Fallen Empire#`

Gate of Hell has level 1 Rampage Blaster as pre-requisite:
`4077,2343,10,2332,1,2330,5,0,0,0,0,0,0 //SR_GATEOFHELL#Gate Of Hell#`

Rising Dragon has level 1 Power Velocity as pre-requisite:
`4077,2338,10,2341,1,0,0,0,0,0,0,0,0 //SR_RAISINGDRAGON#Raising Dragon#`

Gentle Touch - Quiet has no pre-requisites:
`4077,2344,5,0,0,0,0,0,0,0,0,0,0 //SR_GENTLETOUCH_QUIET#Gentle Touch - Quiet#`

Gentle Touch - Cure has level 1 Gentle Touch Quiet as pre-requisite:
`4077,2345,5,2344,1,0,0,0,0,0,0,0,0 //SR_GENTLETOUCH_CURE#Gentle Touch - Cure#`

Gentle Touch - Change has level 3 Gentle Touch - Energy Gain as pre-requisite:
`4077,2347,5,2346,3,0,0,0,0,0,0,0,0 //SR_GENTLETOUCH_CHANGE#Gentle Touch - Change#`

Gentle Touch - Revitalize has level 3 Gentle Touch-Energy Gain as pre-requisite:
`4077,2348,5,2346,3,0,0,0,0,0,0,0,0 //SR_GENTLETOUCH_REVITALIZE#Gentle Touch - Revitalize#`

Gentle Touch - Energy Gain has level 1 Gentle Touch - Cure as pre-requisite:
`4077,2346,5,2345,1,0,0,0,0,0,0,0,0 //SR_GENTLETOUCH_ENERGYGAIN#Gentle Touch - Energy Gain#`

Cursed Circle has only level 2 Root as prerequisite:
`4077,2334,5,269,2,0,0,0,0,0,0,0,0 //SR_CURSEDCIRCLE#Cursed Circle#`

Knuckle Arrow has only Lv 1 Lightning Walk as prerequisite:
`4077,2336,10,2335,1,0,0,0,0,0,0,0,0 //SR_KNUCKLEARROW#Knuckle Arrow#`

Earth Shaker has level 3 Dragon Combo as prerequisite:
`4077,2328,5,2326,3,0,0,0,0,0,0,0,0 //SR_EARTHSHAKER#Earth Shaker#`

Crescent Elbow has level 1 Windmill as prerequisite:
`4077,2333,5,2337,1,0,0,0,0,0,0,0,0 //SR_CRESCENTELBOW#Crescent Elbow#`

Flash Combo has level 5 Tiger Cannon as prequisite
`4077,5009,5,2326,3,2329,3,2330,5,2327,1,0,0 //SR_FLASHCOMBO#Flash Combo#`

  * Expected Result: 

prerequisite for Fallen Empire should be Lv 1 Dragon Combo:
`4077,2329,10,2326,1,0,0,0,0,0,0,0,0 //SR_FALLENEMPIRE#Fallen Empire#`

prerequisites for Gate of Hell should be Lv 5 Rising Dragon and Tiger Cannon:
`4077,2343,10,2338,5,2330,5,0,0,0,0,0,0 //SR_GATEOFHELL#Gate Of Hell#`

prerequisites for Rising Dragon should be Lv.3 Rampage Blaster and Gentle Touch - Energy Gain:
`4106,2338,10,2332,2,2346,3,0,0,0,0,0,0 //SR_RAISINGDRAGON#Raising Dragon#`

prerequisite for Gentle Touch - Quiet should be Lv.1 Power Velocity:
`4077,2344,5,2341,1,0,0,0,0,0,0,0,0 //SR_GENTLETOUCH_QUIET#Gentle Touch - Quiet#`

prerequisite for Gentle Touch - Cure should be Lv.1 Power Velocity:
`4077,2345,5,2341,1,0,0,0,0,0,0,0,0 //SR_GENTLETOUCH_CURE#Gentle Touch - Cure#`

prerequisite for Gentle Touch - Change should be Lv.4 Gentle Touch - Cure:
`4077,2347,5,2345,4,0,0,0,0,0,0,0,0 //SR_GENTLETOUCH_CHANGE#Gentle Touch - Change#`

prerequisite for Gentle Touch - Revitalize should be Lv.5 Gentle Touch - Change:
`4077,2348,5,2347,5,0,0,0,0,0,0,0,0 //SR_GENTLETOUCH_REVITALIZE#Gentle Touch - Revitalize#`

prerequisite for Gentle Touch - Energy Gain should be Lv.3 Gentle Touch - Quiet:
`4077,2346,5,2344,3,0,0,0,0,0,0,0,0 //SR_GENTLETOUCH_ENERGYGAIN#Gentle Touch - Energy Gain#`

prerequisites for Cursed Circle should be Lv.2 Root and Gentle Touch - Quiet:
`4077,2334,5,269,2,2344,2,0,0,0,0,0,0 //SR_CURSEDCIRCLE#Cursed Circle#`

prerequisites for Knuckle Arrow should be Lv.3 Rampage Blaster and Lightning Walk:
`4077,2336,10,2335,3,2332,3,0,0,0,0,0,0 //SR_KNUCKLEARROW#Knuckle Arrow#`

prerequisite for Earth Shaker should be Lv.1 Dragon Combo and Cursed Circle:
`4077,2328,5,2326,1,2334,1,0,0,0,0,0,0 //SR_EARTHSHAKER#Earth Shaker#`

prerequisite for Crescent Elbow should be Lv.1 Sky Net Blow:
`4077,2333,5,2327,1,0,0,0,0,0,0,0,0 //SR_CRESCENTELBOW#Crescent Elbow#`

The correct level for Tiger Cannon as prerequisite of Flash Combo is 1:
`4077,5009,5,2326,3,2329,3,2330,1,2327,1,0,0 //SR_FLASHCOMBO#Flash Combo#`

  * How to Reproduce:  Distributing points on Sura skill tree can't be done properly because the client has different values on data/lua files/skillinfoz/skillinfolist.lub
  * Official Information:
> http://ro.gnjoy.com/guide/runemidgarts/jobview.asp?lineseq=6&jobgamecode=4070

> https://ragnarok.gamepedia.com/Sura (translations for official patches)

  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
As of #4256 the skill tree changed.
