### ISSUE TITLE
Star Gladiator Warm's Damage Calculation

### ISSUE THREAD

**Issue by Tydus1** [rathena/rathena#4765]
* **rAthena Hash**: 
412d90048d8a1d84e72d23e7e00e30c05278e203

* **Client Date**: 
2018-06-21RE

* **Server Mode**: 
Pre-Renewal

* **Description of Issue**: 
  * Result: Experienced damage variation
  * Expected Result: The Star Gladiator Warm's should deal constant damage
  * How to Reproduce: Meet all the requirements to use the skill such as marking the map and monster with correctly skills and then use SG_Warm's

  * Official Information:
  
* **Modifications that may affect results**: 

* **Screenshot**: 
 
![image](https://user-images.githubusercontent.com/16859064/78316956-64063180-7537-11ea-81f7-380e58f094e4.png)
![image](https://user-images.githubusercontent.com/16859064/78316978-6f595d00-7537-11ea-9d6a-8874fd023a16.png)

**Comment by Tydus1** [comment]
Update: I updated a clear rAthena base and sometimes it also happens:

![image](https://user-images.githubusercontent.com/16859064/78362932-51204b00-7591-11ea-8387-7b3bd1aa387a.png)
![image](https://user-images.githubusercontent.com/16859064/78362956-58475900-7591-11ea-8ea9-7359d7e49c6e.png)

Note that the SP keeps getting drained but no damage is dealed at all.

**Comment by aleos89** [comment]
I tested on c94bae7 and was unable to reproduce. My damage was always constant and gave damage to all enemies around me.

Sometimes damage could seem like it's not being done if there's a client desync between you and the monster or if the monster is just a long ranged monster.

**Comment by Tydus1** [comment]
I will be checking again now on c94bae73593d81cf085600d17064a906192d63d5

**Comment by Tydus1** [comment]
This issue can now be closed.

I've tested on the latest commit and it's working fine. I have no more clue about what had caused the issue but seens to be fixed.
