### ISSUE TITLE
12514,E_Abrasive,E_Abrasive Not Work

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#4767]
* **rAthena Hash**: bdd6302

* **Client Date**: 20180620

* **Server Mode**: RENEWAL

* **Description of Issue**:
  * Result:  12514,E_Abrasive,E_Abrasive Not Work Properly
  * Expected Result:  12514,E_Abrasive,E_Abrasive work like 14536,Abrasive,Abrasive
  * How to Reproduce:  just use that item
  * Official Information: the function is same but i dont know 12514,E_Abrasive,E_Abrasive not work
  

* **Modifications that may affect results**:

**Comment by reunite-ro** [comment]
I use it right now and its working.

Are you sure u already merge this commit because Im the one who reported about this item before.

https://github.com/rathena/rathena/commit/e37267b74770aa95ce3518a4ffb987e08c170330

**Comment by mazvi** [comment]
Yes, it's the same. but it still doesn't work on my server, I use centos, but I don't know where the problem is. there's only animation coming out.

**Comment by mazvi** [comment]
This is my fault, apparently I have db import. closed now
