### ISSUE TITLE
Acid Demonstration dealing no damage on PRE-RE

### ISSUE THREAD

**Issue by danieljorge17** [rathena/rathena#4770]
Even after trying to set the acid demonstration case outside of Renewal ifdef on battle.cpp (which I believe was not supposed to be there) the error continues.

**Comment by aleos89** [comment]
Appreciate the report, but please try to stick to the template when making bug reports. Thanks!

**Comment by shirofuji** [comment]
I've just cloned rathena a few days ago and I'm also experiencing this issue, I've applied the #4775 fixes and it works on monsters. However it still deals no damage on players when on PvP maps.

**Comment by mizuki04** [comment]
just made another pull right now and still it won't work. misses at everything.

**Comment by aleos89** [comment]
Versus monster:
![mon](https://user-images.githubusercontent.com/3521753/78668860-5d661a00-78a9-11ea-843f-cf976d814a6a.PNG)

Versus player in PvP:
![player](https://user-images.githubusercontent.com/3521753/78668876-622ace00-78a9-11ea-8247-96453442d78d.PNG)

**Comment by shirofuji** [comment]
> Versus monster:
> ![mon](https://user-images.githubusercontent.com/3521753/78668860-5d661a00-78a9-11ea-843f-cf976d814a6a.PNG)
> 
> Versus player in PvP:
> ![player](https://user-images.githubusercontent.com/3521753/78668876-622ace00-78a9-11ea-8247-96453442d78d.PNG)

Is this from #4775 ? That's exactly how it's suppose to work, though having doram suggest you're using renewal, I have disabled renewal on my server.

**Comment by aleos89** [comment]
This was in pre-renewal mode. I just happened to choose a preexisting character at login.

**Comment by shirofuji** [comment]
> This was in pre-renewal mode. I just happened to choose a preexisting character at login. And yes, it's after applying that PR.

Fixed, works on my end now aside from commenting `#define RENEWAL` I had to uncomment `#define PRERE` on `config/renewal.hpp`
