### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by Cainho** [rathena/rathena#4773]
Error to compile when I change the packet to 2010-30-07. Below is the error line.

Before
`WFIFOL(fd, offset) = qi->objectives[i].mob_id;`

After
`WFIFOL(fd, offset) = qi->objectives[i]->mob_id;`

https://github.com/rathena/rathena/blob/a67f5c5d6a732db511d0484e55189fc742fcde14/src/map/clif.cpp#L17137

**Comment by aleos89** [comment]
Appreciate the report, but please try to stick to the template when making bug reports. Thanks!
