### ISSUE TITLE
acid demonstration skill miss on every element using very latest rA

### ISSUE THREAD

**Issue by mizuki04** [rathena/rathena#4777]
* **rAthena Hash**:  a67f5c5

* **Client Date**:  20180620

* **Server Mode**:  Pre Renewal

  * How to Reproduce: recompile latest rA that I specifically pulled about 11 hours ago from when this post was made

* **Modifications that may affect results**:  i simply disabled renewal in renewal.hpp, and removed condition of sonic blow skill to stop attacking after being casted in skill in skill.cpp

**Comment by aleos89** [comment]
Duplicate of #4770.
