### ISSUE TITLE
Vending problem

### ISSUE THREAD

**Issue by blipblopblip** [rathena/rathena#4778]
* **rAthena Hash**: ce42168b0d2d25f66ab8a5fc5e2ef24d988274ae

* **Client Date**: 20151104

* **Server Mode**: Pre-Renewal ( running with epoll, debug, with 4096 max concurrent connection )

* **Description of Issue**: 
  * Result: The vendor put up the item for 1,500,000z but only sold for 10,000z 
  * Expected Result: The vendor should received the amount he put up
  * How to Reproduce: I can't reproduce this it doesn't show any problems in the server side :( 
  * Official Information: This issue started when I tried to enable epoll in my server to increase the max capacity of my concurrent connections. I don't know if this is related to that or not but this problem occurs when I have more than 1.5k players in-game... 
  

* **Modifications that may affect results**: 
  
  

Please check the video here : https://www.youtube.com/watch?v=DLZydLH3YD0

**Comment by aleos89** [comment]
What is your vending tax config set to?

**Comment by blipblopblip** [comment]
> What is your vending tax config set to?

Hi, I'm using the default setting from items.conf

**Comment by blipblopblip** [comment]
bump, anyone care to help? :(

**Comment by aleos89** [comment]
Does this happen consistently or is this a one-off type of event? I was unable to reproduce this, although I'm just testing on a local server, not one with 1,500 players. There's just no way for me to test for that kind of edge case.
Vendor:
![image](https://user-images.githubusercontent.com/3521753/79021470-9ae8d280-7b49-11ea-8b31-ef8422e9cde9.png)
Buyer went from 10 million Zeny to 8.5 million as expected.
