### ISSUE TITLE
Knuckles aspd bug on Priests

### ISSUE THREAD

**Issue by rubie123** [rathena/rathena#478]
When priests wear knuckle type weapons, their ASPD is brought down to 1. Looked everywhere for this, but seems like this issue hasn't been fixed yet?

**Comment by cydh** [comment]
I wear Waghnak (1801), ASPD not dropped to 1.

**Comment by rubie123** [comment]
My revision is not the latest.
This is my revision: 0d8a7c0313ebba3ebc11fe65906759fcc40fc41f
So I'm not sure if this was fixed?
If it is fixed, could you tell me at which revision you fixed this?

**Comment by aleos89** [comment]
@cydh tested on renewal. I'm assuming you're using pre-renewal?

**Comment by rubie123** [comment]
Yes I am using pre-renewal

**Comment by cydh** [comment]
if in pre-renewal, Priest ASPD drop to 1 when use knuckle, then it's working as intended. this is from 'old' Aegis
````
//JobClass	Unarmed	Dagger	Sword	2HSword	Spear	2hSpear	Axe	2hAxe	Mace	2hMace	Rod	Bow	Knuckle	Instrum	Whip	Book	Katar	Pistol	Rifle	Gatling	Shotgun	Grenade		Huuma	2hRod
PRIEST		400	2000	2000	2000	2000	2000	2000	2000	600	600	600	2000	2000	2000	2000	600	2000	2000	2000	2000	2000	2000		2000	600
````

**Comment by rubie123** [comment]
How can I make it like in renewal? where is the code for this? does it require a src edit?

**Comment by rubie123** [comment]
Got it, thanks. You can close this.
