### ISSUE TITLE
skill SP_SPA Lv10 miss SpiritSphereCost

### ISSUE THREAD

**Issue by Angelic234** [rathena/rathena#4781]
* **rAthena Hash**: 03fa1af

* **Client Date**: 

* **Server Mode**: RE

* **Description of Issue**: 
  * Result:  skill SP_SPA Lv10 miss label SpiritSphereCost set to 0, in game test now it cost 1 SpiritSphere.
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
에스파
MAX Lv : 10
습득조건 : 에스하 1
계열 : 공격 / 특수
내용 : 영혼에너지 1개 소모.
대상에게 마법 피해를 입힌다.
베이스 레벨에 따라 공격력이 증가되며,사용 후 5초간 에스후를 사용할 수 있다.
기본적으로 영혼 에너지 1개를 소모하며, 10레벨의 경우 영혼 에너지를 소모하지 않는다.
단, 플레이어에게는 사용 및 영향을 줄 수 없다.
[Level 1] : 마법 데미지 750%
[Level 2] : 마법 데미지 1000%
[Level 3] : 마법 데미지 1250%
[Level 4] : 마법 데미지 1500%
[Level 5] : 마법 데미지 1750%
[Level 6] : 마법 데미지 2000%
[Level 7] : 마법 데미지 2250%
[Level 8] : 마법 데미지 2500%
[Level 9] : 마법 데미지 2750%
[Level 10] : 마법 데미지 3000%, 영혼 에너지 소모 없음

  

* **Modifications that may affect results**:

**Comment by Akaineko-astasi** [comment]
Actually this is official behaviour. 
Even the skill description says 
[Level 10] : 영혼 에너지 소모 없음
