### ISSUE TITLE
storage problem for 2018-11-07aRagexe

### ISSUE THREAD

**Issue by bgamez23** [rathena/rathena#4785]
* **rAthena Hash**: 9db44eca7d78c57b8073af6b4d72832b85299c60

* **Client Date**: 2018-11-07aRagexe

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Stored item not showing properly.
  * Expected Result: the item will be stored but will not display on proper tab.
  * How to Reproduce: use @storage then put your item there. it will not display properly but when you click the mini icons below it will display your stored item.
  * Official Information: the item should be display on proper tab even without clicking the small icons below.

![screenrAthena003](https://user-images.githubusercontent.com/1854368/79007294-71519a80-7b8d-11ea-83b3-7a5b661f220d.jpg)
![screenrAthena004](https://user-images.githubusercontent.com/1854368/79007297-73b3f480-7b8d-11ea-8f59-e6de5e052f05.jpg)
![screenrAthena005](https://user-images.githubusercontent.com/1854368/79007298-744c8b00-7b8d-11ea-9c2b-cee2e24bfb87.jpg)

 
* **Modifications that may affect results**: default

**Comment by OptimusM** [comment]
rAthena has support "officialy" until client date 20180620, if u use any client date superior to that, it will not be fully supported.

pd: come on guys, crowdfunding at least? *wink wink*

**Comment by Akkarinage** [comment]
I believe support for newer clients is being worked on, but there's no ETA at the moment.
