### ISSUE TITLE
Bodystyle with unsupported (third) classes

### ISSUE THREAD

**Issue by reunite-ro** [rathena/rathena#4787]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/9db44eca7d78c57b8073af6b4d72832b85299c60

* **Client Date**: 20180620

* **Server Mode**: Renewal

* **Description of Issue**: Since Super Novice Expanded, Star Emperor and Soul Reaper (including baby) are set as 3rd job, they can use the function too. But as I know, theres no altenate styles yet for this class.
  * Result: Client will crash since no altenate styles file and rAthena emulator didnt blocked it from being used by those classes.
  * Expected Result: If those jobs didnt have altenate styles, we need to exclude them from using @bodystyles.
  * How to Reproduce: Change job to Star Emperor/Soul Reaper or Novice Expanded classes, then use '@bodystyle 1'.

**Comment by admkakaroto** [comment]
Go to: src/map/atcommand.cpp.

Find:
```
	if (!(sd->class_&JOBL_THIRD)) {
		clif_displaymessage(fd, msg_txt(sd,740));	// This job has no alternate body styles.
		return -1;
	}
```

Change to:
```
	if (!((sd->class_&MAPID_THIRDMASK) == MAPID_GUILLOTINE_CROSS || (sd->class_&MAPID_THIRDMASK) == MAPID_SHADOW_CHASER
		|| (sd->class_&MAPID_THIRDMASK) == MAPID_MECHANIC || (sd->class_&MAPID_THIRDMASK) == MAPID_GENETIC
		|| (sd->class_&MAPID_THIRDMASK) == MAPID_ARCH_BISHOP || (sd->class_&MAPID_THIRDMASK) == MAPID_SURA
		|| (sd->class_&MAPID_THIRDMASK) == MAPID_WARLOCK || (sd->class_&MAPID_THIRDMASK) == MAPID_SORCERER
	    || (sd->class_&MAPID_THIRDMASK) == MAPID_MINSTRELWANDERER || (sd->class_&MAPID_THIRDMASK) == MAPID_RANGER
		|| (sd->class_&MAPID_THIRDMASK) == MAPID_ROYAL_GUARD || (sd->class_&MAPID_THIRDMASK) == MAPID_RUNE_KNIGHT)) {
		clif_displaymessage(fd, msg_txt(sd,740));
		return -1;
}
```

It is not the best fix but it prevents any other class that does not have alternative clothing from crashing.
