### ISSUE TITLE
Level 10 Water Ball has inconsistent cast range

### ISSUE THREAD

**Issue by NeutralDev** [rathena/rathena#4789]
* **rAthena Hash**: 9db44ec

* **Client Date**: **2018-06-21aRagexeRE**

* **Server Mode**: **pre-renewal**

* **Description of Issue**: When using Water Ball level 10 on a player character (in this case a Stalker with copied Water Ball) it forces you to cast the skill within 2 cells of the target. If you're not close enough you will walk up to the target within 2 cells before casting it.
  * **Expected Result:** Water Ball level 10 should still use the same casting range as levels 1~5, aka 9, like it says in skill_db; but for all I know this might be how level 10 Water Ball is intended officially (doubt it but who knows).
  * **How to Reproduce:** Copy level 10 Water Ball on a Rogue/Stalker or add level 10 Water Ball on an item through the skill function and cast it.

**Comment by reigneil** [comment]
iirc it is clientside issue. last time i play iRO this is also an issue. need to edit skillinfolist.lub https://rathena.org/board/tracker/issue-8402-waterball-above-level-5-with-wrong-attack-range/ if only dev add config on this...
