### ISSUE TITLE
unique_id do not work.

### ISSUE THREAD

**Issue by anacondaqq** [rathena/rathena#479]
### Problem
unique_id field in inventory / storage / cart_inventory do not work anymore.
What does it means? That means -> unique_id always 0 in table.

![](http://i.imgur.com/LJTOGnf.png)
On the screenshot above, i'm using next script:

> prontera,155,180,5	script	uniqueid	89,{
	for( .@i = 0; .@i < 21; .@i++ )
		mes getequipuniqueid(.@i);
	close;
}

![](http://i.imgur.com/64vJPdE.png)
On screenshot above, as you see our unique_id row in table do not work too

### Technical Details
1. Clear rAthena 21.06.2015 (revision: 1b3d5e5c55e67cd7fbc79c86b20b71b1347991dc)
2. pre-re, mmo.h - > 20100730, packet_ver: 25
3. packet obsification disabled
4. no more changes.

### How reproduce
1. hunt items, or make them though @item command
2. logout and check your inventory unique_id row for these items
3. you can check unique_id of items by scriptcommands (getequipuniqueid) but you will see errors.

Dear developers, if you need more information, please tell me, i will provide as maximum as i can.
But for now, i think it's enough to reproduce and get enough data to fix this problem.
I hope, you will fix it, because unique_id row very critical for me, and for security purposes.

**Comment by anacondaqq** [comment]
dear friends and developers, how can i help to find reason of the bug? 
I just want to fix it ASAP, because without unique_id very dangerous to run game server.

**Comment by anacondaqq** [comment]
Live test: 
Commit: d4aa4c70a7ec51781109d27c9a7041e0a37d488f - unique_id do not working.

**Comment by icxbb-xx** [comment]
Wait for fixed soon aleos found problem

**Comment by anacondaqq** [comment]
This is cryitical. Please take attention to this. ~ 6 month without unique_id = very bad for live servers.

**Comment by anacondaqq** [comment]
Dear @aleos89 
Thank you very much for update. This is working for new items like it must.
Is the old items with unique_id = 0 must get a unique_id or not?

**Comment by aleos89** [comment]
Enable the 'item_check' config and it should give unique IDs to older items just fine.

**Comment by anacondaqq** [comment]
Dear @aleos89 i was try different settings:

item_check: 1
item_check: 2
item_check: 3
item_check: 4
item_check: 5
item_check: 7

same result - nothing. The items with empty (0) unique_id placed at inventory / storage / cart do not recieve their unique_id :)

Is it possible somehow to fix? Do i need create new issue about this problem? 

btw, unique_id working fine for new items recieved from commands, monsters, npc.
