### ISSUE TITLE
skill_db.yml  skill level over 10

### ISSUE THREAD

**Issue by idk-whoami** [rathena/rathena#4800]
* **rAthena Hash**: 44b80448df07bec285b1a5056ceae519265bd19b

* **Client Date**: 20180620

* **Server Mode**: both

* **Description of Issue**: skill_db.yml   skill level 11  find ctrl+f Level: 11    9 count 
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
These are valid. Please read [here](https://github.com/rathena/rathena/blob/master/doc/mob_skill_db_powerskill.txt) for an explanation as to why levels 11, 12, and 13 exist for some skills.
