### ISSUE TITLE
Soul Link for Bard/Dancer doesn't enable the linked skill

### ISSUE THREAD

**Issue by ihernandeza** [rathena/rathena#4801]
* **rAthena Hash:**: 404e9f8

* **Client Date**: 20150513

* **Server Mode**: Pre_renewal

* **Description of Issue**: 
  * Result: Can't use bonus skills 
![image](https://user-images.githubusercontent.com/5288207/79285417-83805100-7e8b-11ea-881d-bab5ad8159b6.png)

  * Expected Result: Allow to use linked skills, based on Mastered ones as Dancer [explained here](https://ratemyserver.net/index.php?sk_name=bard&page=skill_db&sk_search=Search)
  * How to Reproduce:  
- Master any of this skills as a dancer: Humming, Dont Forget Me, Fortune Kiss, Service for you
- Trow Bard and Dancer spirit skill to the Dancer using a Soul Linker on Doble Login
- Check the "Other Tab" on the skill window of the dancer, Bard skills will appear grayed.
- If you have some skill points, and change the window mode to the small one, you could add some points to every skill, but if you press the "Reset" button, your skill points will be restored but not the skill level, causing an infinite skill level up (Fortunally, this is only visual)
![image](https://user-images.githubusercontent.com/5288207/79285769-7fa0fe80-7e8c-11ea-9c5e-c1a3e78a56cb.png)

  

* **Modifications that may affect results**: 
  none

**Comment by BotGigo** [comment]
Same at 20180620 client.

**Comment by pigati23** [comment]
I just tried it and it works perfectly. I think your problem is on the client side.
I just tried it on Dancer and Gypsy.
![123](https://user-images.githubusercontent.com/57366433/79287798-8cbcee00-7e8a-11ea-8e67-b6e046a72e59.png)

**Comment by reunite-ro** [comment]
Yeah I wanna said the same think as pigati23 stated. 
Since limitation of Level in Client Side = in lub files.

**Comment by BotGigo** [comment]
@pigati23 Can you leve me your skillinfoz folder? cus im trying with many diferent folders and its not working. if its possible :D

**Comment by BotGigo** [comment]
@reunite-ro Actually i have been reading those files and i didnt find anything.

**Comment by pigati23** [comment]
Im using this git. https://github.com/llchrisll/ROenglishRE/tree/b1dbec84c3049e6632a4e73724765d1d2762b390

**Comment by reunite-ro** [comment]
Btw chriss only translates Renewal, maybe You can use zackdreaver for Pre-Renewal (as I read the issues related pre-re) but he didnt update the files for it since last year.

**Comment by pigati23** [comment]
> Btw chriss only translates Renewal, maybe You can use zackdreaver for Pre-Renewal (as I read the issues related pre-re) but he didnt update the files for it since last year.
I haven't reviewed it in detail, but I think that may work for what he is needing. If you find many differences, you can correct it with Zack's translation for pre-renewal.

**Comment by BotGigo** [comment]
Already try those two, ill try Chirs :D

**Comment by victorrod** [comment]
same here, the problem it's only with gypsy, clwon it's ok
https://rathena.org/board/topic/122697-gypsy-skill-three-etc3rd-tab-still-disabled-after-soul-linked-help/

**Comment by aleos89** [comment]
![image](https://user-images.githubusercontent.com/3521753/79692783-065f2e00-8235-11ea-9162-2c1ee75eaecb.png)
I'm unable to reproduce this issue as well on the current master (dd9b6d3). Make sure your client data is accurate.

**Comment by gidzdlcrz** [comment]
I see its already reported 25 days ago. @ihernandeza i assume you are testing it in your live server? Because the local ones doesnt have this problem(assumingly your local is running windows OS).

In windows VPS i confirm its working as intended.
in Linux based OS i confirm its not working.

**Comment by ihernandeza** [comment]
live server at google comppute engine, centos 7

**Comment by gidzdlcrz** [comment]
@ihernandeza i knew it. Lets wait for the fix. ♥

**Comment by Kreustoo** [comment]
Same problem here, live server: grayed
Local server using the same lub: not grayed

But using gepard on live and not a local? Anyone else?

**Comment by Akaineko-astasi** [comment]
Did you try with an actual Soul Linker character, not self buff?

**Comment by gidzdlcrz** [comment]
@Akaineko-astasi yes. It really doesnt work. Like i said for you to reproduce this. You have to have live server. As ive mentioned here https://github.com/rathena/rathena/issues/4909

@Kreustoo My local server have gepard. And it works. My live has gepard as well but it doesnt work.

**Comment by Kreustoo** [comment]
Yeah both time I tried with a real SL character using the spell.

**Comment by gidzdlcrz** [comment]
As for me. ive tried everything. Even updating my compiler in my vps. https://github.com/rathena/rathena/issues/4909

**Comment by Stingor** [comment]
having same issue here, but actually if you put clown card (armor) you normaly get poem of bragi in you skills, so its not client side i guess ?

**Comment by BotGigo** [comment]
> 
> 
> having same issue here, but actually if you put clown card (armor) you normaly get poem of bragi in you skills, so its not client side i guess ?

yeah, aparently it is a problem in the OS

>
>
>In windows VPS i confirm its working as intended.
in Linux based OS i confirm its not working.

**Comment by cahya1992** [comment]
Im get same issue but only for gypsy.
for Clown everything its okay
my rathena version
[https://github.com/rathena/rathena/commit/157392cd1a3174abf2051907126aba4617f8ffbc](url)

**Comment by gidzdlcrz** [comment]
any news from this?

**Comment by aleos89** [comment]
What version of gcc are you all using?

**Comment by ihernandeza** [comment]
> What version of gcc are you all using?

7

**Comment by gidzdlcrz** [comment]
Yes me too 7. As per my vps provider. Is there a way to check the current version?

**Comment by aleos89** [comment]
```
$ gcc --version
$ g++ --version
```
These should return the versions.

**Comment by gidzdlcrz** [comment]
here ya go. 
![image](https://user-images.githubusercontent.com/62187272/83904010-b3fcb100-a791-11ea-8672-b39352e4c1b9.png)

The only way to fix this issue is to use SECRET's diff regarding soul linker. However. That diff will give you memory leaks.

**Comment by Stingor** [comment]
gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
g++ (Debian 6.3.0-18+deb9u1) 6.3.0 20170516

**Comment by aleos89** [comment]
Are you referring to [this](https://rathena.org/board/files/file/3749-soul-link-modification-script-based/) diff?

**Comment by gidzdlcrz** [comment]
Yes @aleos89. That is the solution for this problem. I never want to use it in the first place but it was forced me to because of this bug. Anyhow its a good feature indeed. The only concern is it does give me and everybody else memory leak.
