### ISSUE TITLE
Forging

### ISSUE THREAD

**Issue by trinitynetworks** [rathena/rathena#4802]
* **rAthena Hash**: 6edcf4a

* **Client Date**: 2018-06-21Ragexere

 May 15, 2020

* **Server Mode**: Pre-Renewal

* **Description of Issue**: 
  * Result: 
  * Expected Result:  No Console Errors
  * How to Reproduce: 

No Source Edits No Skill Database edits, using, result I get from forging using my mastersmith

https://gyazo.com/493ae269ccd05c4a14db49512df3d319

[Error]: pc_checkskill: Invalid skill id 2496 (char_id=150001).
[Error]: Skill '2496' is undefined! pc.cpp:6164::pc_checkskill

  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment]
Are you by any chance using Visual Studio 2013?
Because I think this might be related to #4646

**Comment by Lemongrass3110** [comment]
Also the skill id 2496 is a genetic skill that was removed from kRO.
Maybe you simply forgot to run the part of upgrade_20200402.sql for pre-renewal?

**Comment by trinitynetworks** [comment]
No I am not using visual studio 2013, thats why im wondering im using forging by a master smith. how come the error is showing and yes i have runned the upgrade sql.

-- AB_EUCHARISTICA
UPDATE `char` c, `skill` s SET `c`.skill_point = `c`.skill_point + `s`.lv WHERE `s`.id = 2049 AND `c`.char_id = `s`.char_id;
DELETE FROM `skill` WHERE `id` = 2049;

-- GN_SLINGITEM
UPDATE `char` c, `skill` s SET `c`.skill_point = `c`.skill_point + `s`.lv WHERE `s`.id = 2493 AND `c`.char_id = `s`.char_id;
DELETE FROM `skill` WHERE `id` = 2493;

-- GN_MAKEBOMB
UPDATE `char` c, `skill` s SET `c`.skill_point = `c`.skill_point + `s`.lv WHERE `s`.id = 2496 AND `c`.char_id = `s`.char_id;
DELETE FROM `skill` WHERE `id` = 2496;

-- ONLY RUN THE BELOW QUERIES IF YOU ARE ON RENEWAL
-- CR_CULTIVATION
UPDATE `char` c, `skill` s SET `c`.skill_point = `c`.skill_point + `s`.lv WHERE `s`.id = 491 AND `c`.char_id = `s`.char_id;
DELETE FROM `skill` WHERE `id` = 491;

**Comment by trinitynetworks** [comment]
is that connected to this? because im trying to forge and its not updating.

https://rathena.org/board/topic/122696-taekwon-blacksmith-alchemist-famepoints-not-updating/

**Comment by trinitynetworks** [comment]
Checked on alchemist its the same

[Error]: Skill '2496' is undefined! pc.cpp:6167::pc_checkskill
[Error]: pc_checkskill: Invalid skill id 2496 (char_id=150001).

**Comment by aleos89** [comment]
It's because the Make Bomb values are still defined in the pre-re database. It's nothing serious and I'll fix it shortly.

**Comment by trinitynetworks** [comment]
try running the server afterwards the skills wont work since it’ll spit out errors like skill isn’t defined in pc.cpp and and something about pccheckskill

**Comment by darking12345** [comment]
This error occurs also when ever I press the Pharmacy Skill from my alchemist


[Error]: Skill '2496' is undefined! pc.cpp:6178::pc_checkskill
[Error]: pc_checkskill: Invalid skill id 2496 (char_id=150002).

**Comment by aleos89** [comment]
The PR linked above will fix the issues and is available for testing.
