### ISSUE TITLE
Solar Heat SG not working when using @reloadskilldb

### ISSUE THREAD

**Issue by rook1es** [rathena/rathena#4804]
rAthena Version Git Hash : 1fc4b8de2063c90b74b7da95e3b105306a825c21

* **Client Date**:  20150513

* **Server Mode**:  Pre-Renewal

* **Description of Issue**: 
  * Result: Solar Heat not working
  * Expected Result: when im using @reloadskilldb 
  * How to Reproduce: Solar Heat , Solar Protection , Lunar Heat , Lunar Protection , Stellar Heat , Stellar Protection

* **Modifications that may affect results**:  Soul Link Modification and Gepard

**Comment by aleos89** [comment]
Skill database reloading was fixed in 496f362. There are several other fixes here and there regarding skills so I'd suggest just updating to master.
