### ISSUE TITLE
Fusion of Sun Moon Star Bug

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#4807]
* **rAthena Hash**: 44b8044

* **Client Date**: 20180620RE

* **Server Mode**: RENEWAL

* **Description of Issue**: Fusion of Sun Moon Star Does not work as it should, when it is run it opens a warp portal.
  * Result: 
  * Expected Result: 
  * How to Reproduce:  iam using GM witth allskill enable, First run skill Lord of Vermilion than run Fusion of Sun Moon Star
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
I wasn't able to reproduce this. Using Union worked fine and didn't create a "warp portal".

**Comment by mazvi** [comment]
Iam using centos 7 with gcc 7 i think different compiler will different result

**Comment by aleos89** [comment]
Is this still an issue?

**Comment by Lemongrass3110** [comment]
No user comment for over 2 years.
