### ISSUE TITLE
Map Server Crash: clif_elemental_updatestatus

### ISSUE THREAD

**Issue by AbuGosok** [rathena/rathena#481]
Related to https://github.com/rathena/rathena/commit/c1c85ad2e843fc70e812479fcc0577f65945bee1

and https://github.com/rathena/rathena/issues/455

>	map-server.exe!clif_session_isValid(map_session_data * sd) Line 289	C
 	map-server.exe!clif_elemental_updatestatus(map_session_data * sd, int type) Line 16338	C
 	map-server.exe!elemental_heal(elemental_data * ed, int hp, int sp) Line 530	C
 	map-server.exe!status_heal(block_list * bl, __int64 hhp, __int64 hsp, int flag) Line 1715	C
 	map-server.exe!status_natural_heal(block_list * bl, char * args) Line 12955	C
 	map-server.exe!map_foreachregen(int (block_list *, char *) * func, ...) Line 2119	C
 	map-server.exe!status_natural_heal_timer(int tid, unsigned int tick, int id, int data) Line 13037	C
 	map-server.exe!do_timer(unsigned int tick) Line 367	C
 	map-server.exe!main(int argc, char * * argv) Line 363	C

	clif.c		if (sd != NULL && sd->packet_ver <= MAX_PACKET_VER && session_isActive(sd->fd))
	clif.c		if( !clif_session_isValid(sd) || (ed = sd->ed) == NULL )
	elemental.c	clif_elemental_updatestatus(ed->master, SP_HP);
	status.c	case BL_ELEM: elemental_heal((TBL_ELEM*)bl,hp,sp); break;
	status.c	if (status_heal(bl, val, 0, 1) < val)

data view: sd available, but sd->fd cannot read from memory.

**Comment by cydh** [comment]
I added some check somewhere on recent commits. Can u update ur server, please? And bump this 'again' if it's still crash

**Comment by aleos89** [comment]
Assuming resolved since no other reports have been submitted or no response since.
