### ISSUE TITLE
OnPCStatCalcEvent is broken

### ISSUE THREAD

**Issue by Artuvazro** [rathena/rathena#4812]
* **rAthena Hash**:  Anyone after 18 Jan

* **Description of Issue**: 
  * Result:  OnPCStatCalcEvent is broken at least since 18 Jan (This commit: https://github.com/rathena/rathena/commit/bf9a3b47fea465fba3f09a132c3069ee74dcb931)
  * Expected Result: This event should trigger when a character stat is recalculated, for instance, when receiving a blessing, increase agi, etc. But after that commit it only fires on login.
  * How to Reproduce: Do anything that forces recalculation of stats through skills like using blessing and check that the event is never triggered. It was working until this was committed: https://github.com/rathena/rathena/commit/bf9a3b47fea465fba3f09a132c3069ee74dcb931 I reverted my rAthena back to this point and it worked perfectly!

**Comment by aleos89** [comment]
I think this was more of a bug in that it shouldn't have been triggering from `status_change_start` calls. The documentation for the event as well as looking at the initial implementation of the event shows that it wasn't setup to trigger during SC start events.

A new NPC event would need to be created if we want to trigger for SC start/end or skill usage.

**Comment by Artuvazro** [comment]
Thank you for answering, @aleos89 We will probably try an implementation of a new event such as on pc skill usage, which I think suits better my initial puprose and will be more fun for writing custom events.

**Comment by aleos89** [comment]
The staff discussed this script event and decided it's best we drop support of it. People are welcome to ignore the drop.

The other various script events can do what this event already does. The only feature this one had that the other events don't have is being triggered on player equipment switching. This actually causes issues in various other parts of source if a script were to pause or take too long during this StatEvent.
