### ISSUE TITLE
Mob Card Drops & ItemDB Recheck For Flame Basin, Isle of Bios, Morse's Cave and Temple of Demon God

### ISSUE THREAD

**Issue by reunite-ro** [rathena/rathena#4814]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/dd9b6d30e2785fd9d6f665e89af8c614a8364fe5

* **Client Date**: 20180620

* **Server Mode**: Renewal.

* **Description of Issue**: Card drops are not added in itemdb. Ill list it below :

=>Flame Basin [moro_vol]
-Fire Condor Card [27026]
-Fire Sandman Card [27027]
-Fire Frilldora Card [27028]
-Fire Golem Card [27029]
-Fulbuk Card [27030]

=>Isle of Bios
-Corrupt Life Card [27328] - Dropped by Fallen Orc Zombie [3016]
-Grim Reaper Ankou Card [27327]

=>Morse's Cave
-Morocc's Minion Card [27326]

=>Temple of Demon God
-Demon God's Apostle Ahat Card [27322]
-Demon God's Apostle Shnaim Card [27323]
-Brinaranea Card [27324]
-Muspellskoll Card [27325]
-Lord Morocc Card [4559]
-Despair God Morocc Card [27321]

  * Result: Some monsters didnt drop anything.
  * Expected Result: Add in itemdb.
  * How to Reproduce: Check in itemdb or use monsterinfo commands.
  * Official Information: https://www.divine-pride.net/forum/index.php?/topic/3403-kro-changelog-september-05-2018/

**Comment by mazvi** [comment]
This issue is open?

**Comment by reunite-ro** [comment]
Ill close it then.
