### ISSUE TITLE
Bug still remains on mob_avail with job sprite

### ISSUE THREAD

**Issue by RagnaWay** [rathena/rathena#4815]
* **rAthena Hash**: 

dd9b6d3

Pull: https://github.com/rathena/rathena/pull/4782

* **Client Date**: 

2018-09-19aRagexe

* **Server Mode**: 

Renewal

* **Description of Issue**: 
mob_avail with sprite is working, but when you walk it is teleporting (effect) when the npc walks the name of the npc is right (as a player name) but when it stops (it is like npc, to click)

https://youtu.be/RQHGhrD0IlQ

**Comment by Lemongrass3110** [comment]
This is the only way the newer clients support this. The other options is always sending them out as "player" sprites as it was before 2017-xx.

**Comment by RagnaWay** [comment]
@Lemongrass3110 But it was working fine, even though I was using 2018 clients, this mob_avail bug only happened after I changed it to yml https://github.com/rathena/rathena/pull/4385
