### ISSUE TITLE
npc_event: event not found [1234]

### ISSUE THREAD

**Issue by will21** [rathena/rathena#4816]
I found error  on killing Phen  mobs in Jawaii town!

[Error]: npc_event: event not found [1234]
[Error]: npc_event: event not found [1234]
[Error]: npc_event: event not found [1234]

Im using latest rA (dd9b6d30e2785fd9d6f665e89af8c614a8364fe5)

![Capture](https://user-images.githubusercontent.com/5248429/79683563-9618d280-825d-11ea-956f-5ee5eb37d1f4.PNG)

**Comment by aleos89** [comment]
Please try to follow the issue template when reporting bugs, thanks.

**Comment by will21** [comment]
Thank you very much
