### ISSUE TITLE
[BUG] MVP Rewards (items that were automatically given to the player if he/she is the MVP)

### ISSUE THREAD

**Issue by violent01** [rathena/rathena#4817]
* **rAthena Hash**:  Latest

* **Client Date**: 20180620

* **Server Mode**: Pre-renewal or Renewal

* **Description of Issue**: command @monsterinfo or @mi mvp rewards calculation bugged. I've checked MobID 1115 (Eddga) and saw that the monsterinfo is giving wrong information. Rewards should be displayed like these: Tiger Skin 50%, Tiger Footskin 10% Flame Heart 30% but the server displays the 2nd & 3rd reward like these: 5% and 12.50% which is wrong. Upon checking it all the MVP rewards are like that, feels like the 2nd drop rate was reduced by half and the 3rd drop rate is reduced by like 3/4 of the supposed be drop rate.
  * Result: Get the latest rAthena, run it and then check the monsterinfo of any MVP then compare it to divine pride database or ratemyserver
  * Expected Result:  Should be the same on divine pride database or ratemyserver
  * Official Information: https://www.divine-pride.net/database/monster/1115/eddga
  

* **Modifications that may affect results**:  None
  
  

![github rathena](https://user-images.githubusercontent.com/30449376/79687521-79c26900-8250-11ea-804d-e631b6984b7d.png)

**Comment by Daegaladh** [comment]
monsterinfo command is correct, the drop rate are just like that in both pre-re and renewal mob_db, maybe our renewal database is outdated, idk

**Comment by violent01** [comment]
@Daegaladh  i did not do any edit about this and the my monsterinfo is telling me a different information.

**Comment by aleos89** [comment]
Duplicate of #4700.
