### ISSUE TITLE
THQ Quest NPC Unknown item ID

### ISSUE THREAD

**Issue by darking12345** [rathena/rathena#4819]
Upon checking. item ID 1988 from the quest on the links below doesn't exist from item_db on pre-re.  Thank you!

https://github.com/rathena/rathena/blob/master/npc/custom/quests/thq/THQS_Quests.txt
https://github.com/rathena/rathena/blob/master/npc/custom/quests/thq/THQS_QuestNPC.txt

**Comment by aleos89** [comment]
Please use the template when reporting bugs, it makes things easier to parse for staff.

As for your issue, THQ items live in the db/import/item_db.txt.
