### ISSUE TITLE
bowling bash + play dead bug

### ISSUE THREAD

**Issue by Questune09** [rathena/rathena#4820]
* **rAthena Hash**:  

* **Client Date**:  

 2018 client (i forgot what is it)

* **Server Mode**: 

 Renewal

* **Description of Issue**: 
  * Result:   Bowling bash can be abused while using play dead.
  * Expected Result:  skills can't be used together maybe need to increase or change play dead behavior.
  * How to Reproduce:  Use play dead while using bowling bash
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
The first question is, how does a class other than Novice have Play Dead? In the skill tree calculation the skill is removed from classes who aren't a Novice. This would be one reason there are no skill checks since Novices only have First Aid as a usable skill aside from Play Dead.

**Comment by Questune09** [comment]
After a novice get play dead on the academy and change job the skill play dead is still on its tab, maybe its because of the job changer?

**Comment by aleos89** [comment]
I just tested to confirm, but even if I `@questskill 143` to get Play Dead, I get it, but once I change maps it's removed. This is evidently official behavior when a player changes jobs, once they switch maps the skill is removed from their skill tree.
