### ISSUE TITLE
Jumping Janeway Event IRO NPC/Event missing

### ISSUE THREAD

**Issue by NoharaSuzuki** [rathena/rathena#4822]
* **rAthena Hash**: Not relevant

* **Client Date**: Not relevant

* **Server Mode**: Not relevant

* **Description of Issue**: 
  * Result: Npc/event is missing in the rathena files
  * Expected Result: The npc/event should be there
  * How to Reproduce: Looking at youtube videos, irowiki and look at rathena folder is not there
  * Official Information:https://irowiki.org/wiki/Jumping_Janeway there some videos at youtube but i dont know if okay to post here
  

* **Modifications that may affect results**:

**Comment by Atemo** [comment]
This event is only available on IRO. It could optionally be added if we had the original file (but it does not).
