### ISSUE TITLE
Adrenaline Rush remove after switch Axe/2 Hand Axe/Mace

### ISSUE THREAD

**Issue by poporing** [rathena/rathena#4824]
* **rAthena Hash**: 663d2eb3b4c8cc0d184ebc6e86e79a302422718b

* **Client Date**: 2018-06-20

* **Server Mode**: Pre-Renewal

* **Description of Issue**: 
  * Result: When you use Adrenaline Rush and switch with a Axe/2 hand Axe/Mace it's remove the status
  * Expected Result: In aegis 13.2 and 11.3 adrenaline rush is not suposed to be remove when switch with Axe/2 hand Axe/Mace but should be remove by other type of weapoin

  * Official Information:
This is a record of Aegis 13.2
https://cdn.discordapp.com/attachments/688028666952810592/701583547454062602/2020-04-20_01-58-08.gif

**Comment by Daegaladh** [comment]
Is your server updated? Because this was fixed in 058ad2c67e2662cee113af47caf4aff861d02e02

**Comment by poporing** [comment]
Thanks @Daegaladh it's works.
