### ISSUE TITLE
KN_BRANDISHSPEAR dealing 3x full dmg hits.

### ISSUE THREAD

**Issue by Masao87** [rathena/rathena#4826]
* **rAthena Hash**: 

* **Client Date**: 20180621

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: When you use the skill KN_BRANDISHSPEAR right now it deals 3hits and each hit deals the total damage resulting in normal mobs and MvP's dealing up to 60k ~ 80k dmg in total instead of the total damage being split across the 3 hits. 
  * Expected Result: The skills total damage should be split among the 3 hits it does to then show the full dmg displayed at the end instead of delaing 3 hits with each hit dealing the full dmg.
  * How to Reproduce: Just use the skill KN_BRANDISHSPEAR on any target and you'll see it dealing 3 hits each hit dealing the skills final dmg instead of being split among the 3 hits.
  * Official Information: http://imgc.gnjoy.com/ufile/common/2018/08/16/045153_KKaeA3MC.gif
  

* **Modifications that may affect results**: If you change the HitCount: 3 in the skill_db.yml to HitCount: -3 the skill should then work properly.

**Comment by wdivet** [comment]
I can confirm this. too large damage.
