### ISSUE TITLE
Item_DB Sql Script Accentuation Won't Work

### ISSUE THREAD

**Issue by walterneto** [rathena/rathena#483]
If you use item_db sql, and try for example to put this on a item script:
dispbottom "ãõíáé";

it won't work, all characters will be transformed, even though you set 
char default_codepage[32] = "utf8"; in map.c and transform the script column of the table in utf8.

My workaround so far is to use callfunc, but this is a issue that should be fixed.

Thanks.

**Comment by anacondaqq** [comment]
tell me steps how reproduce.

**Comment by walterneto** [comment]
It's simple, configure your emulator to run item_db on sql.
Import itens tables, create a custom item on item_db2 table.
On item script put a dispbottom with a message including accentuation. 
Use the item ingame.

**Comment by aleos89** [comment]
Why don't you adjust the codepage in the conf/inter_athena.conf rather than directly in source?

**Comment by walterneto** [comment]
Cause I didn't know it was there till now hahahaha.
If there was a comment explaining what is codepage, it would help. When I was searching where to change it, there is no article in the wiki nor in the docs, so I went straight to Source.

Anyway, this is not the issue haha

**Comment by aleos89** [comment]
So this ended up working out of you? I haven't tested this in a while but it should set the name to UTF-8 for you when you define it in the config.

**Comment by walterneto** [comment]
No, the issue remains.
http://puu.sh/iCeJ2/1fed122b2e.jpg

**Comment by walterneto** [comment]
Ups, closed by accident.

**Comment by aleos89** [comment]
So it worked on storing it correctly in MySQL just fine from your image. The only issue you're having is getting it to display correctly in the client. This isn't a server issue, this is a langtype issue in your clientinfo.xml (https://rathena.org/wiki/Clientinfo.xml). I would try setting it to 18 or something and see how that goes.

**Comment by walterneto** [comment]
Of course not o.O accentuation from every where else works fine, just from item script doesn't work.
http://puu.sh/iChvK/d0c0e26166.PNG
As I said before, if I use callfunction on item script, and put the dispbottom on the npc function, it work's.
