### ISSUE TITLE
Instances are not working, for example Sealed Shrine

### ISSUE THREAD

**Issue by Artuvazro** [rathena/rathena#4836]
* **rAthena Hash**: any from this year

* **Client Date**:  not relevant, but tried with 2015 and 2018 clients

* **Server Mode**: not relevant, but pre-renewal

* **Description of Issue**: 
  * Result:  Instances are not working.
  * Expected Result:  Instances should be working.
  * How to Reproduce:  Go to Sealed Shrine and try to enter. You can't. The script always falls here:
`if (instance_create("Sealed Catacomb") < 0) {
                        mes "Umm... But it seems that there is a problem here... I'll check quickly. Please wait.";
                    }`

**Comment by akiyamamio16** [comment]
I'm using the latest rAthena. it's working. First talk to Friar and tell him you want to enter and must have a party, the instance will be generated. Then for you to enter. you will talk to "Grave of Baphomet". 

![screenCelestiaRO005](https://user-images.githubusercontent.com/29175107/80155386-37a07b00-85f4-11ea-8cde-5a32c3a2bbf7.jpg)

**Comment by Artuvazro** [comment]
Thanks @akiyamamio16  I was misusing the NPC. I will close this issue.
