### ISSUE TITLE
Instance destroy causing error in the next instance creation

### ISSUE THREAD

**Issue by Artuvazro** [rathena/rathena#4841]
* **rAthena Hash**: latest

* **Client Date**: non-relevant

* **Server Mode**: pre-renewal

* **Description of Issue**: 
  * Result: If an instance is destroyed by using instance_destroy(), when the next instance of the same type is created, the following error is thrown in the console: 
`[24/Apr 19:38][Error]: Memory manager: freed-data is changed. (freed in npc.cpp line 2444)
`
  * Expected Result:  No error should appear when generating the instance again after it's been destroyed. In fact, if the instance was destroyed by breaking the party, there is no error later on when creating a new one.
  * How to Reproduce:  Use instance_destroy() in a NPC of your instance. Then try to generate a new instance, the previously mentioned error will appear in the console.

**Comment by aleos89** [comment]
I was unable to reproduce this on 5154e07, in Windows.

```
[Info]: [Instance] Created map '001prontera' ('995') from map 'prontera' ('171')
[Info]: [Instance] Created: prontera-test (1).
[Info]: [Instance] Destroyed 1.
[Info]: [Instance] Created map '002prontera' ('995') from map 'prontera' ('171')
[Info]: [Instance] Created: prontera-test (2).
[Info]: [Instance] Destroyed 2.
[Info]: [Instance] Created map '003prontera' ('995') from map 'prontera' ('171')
[Info]: [Instance] Created: prontera-test (3).
[Info]: [Instance] Destroyed 3.
```
I used the following script to test:
```
  - Id: 100
    Name: prontera-test
    TimeLimit: 7200
    Enter:
      Map: prontera
      X: 150
      Y: 150

prontera,150,150,5	script	instance create	1_F_MARIA,{
	instance_create("prontera-test");
	instance_enter("prontera-test");
	end;
}

prontera,155,150,4	script	instance destroy	1_F_MARIA,{
	instance_destroy(instance_id(IM_PARTY));
	end;
}
```
I attempted destruction from inside the instance and outside the instance, neither posted a memory error.

**Comment by Artuvazro** [comment]
Hi aleos, 

To reproduce the issue, instead of using instance_id(IM_PARTY) inside instance_destroy, use the ID of the instance saved in a var .@create which should be setted like this:
.@create = instance_create(.@instance$);

Your option is working fine on my end too, but before knowing that it should be done like that, I was passing to instance_destroy the .@create variable which should have the ID inside. I thought that it should work too because instance_create returns the ID of the instance and it should be saved in .@create. However, it doesn't work well with instance_destroy, apparently.

**Comment by aleos89** [comment]
Keep in mind, that `.@` variables are scope and will be destroyed when the script reaches an `end`. You need to use another variable type that's more permanent, like a global variable or a temporary global variable.

I guess I need to know the full structure of your usage to understand your case.

**Comment by Artuvazro** [comment]
Hi aleos, I believe you can close the issue. If the variable shouldn't be used like that, then it was my issue after all and no fixing is needed. I could do the same thing I wanted to do in the first place by using instance_id(IM_PARTY) :)
