### ISSUE TITLE
Aimed Bolt, wrong fixed cast time

### ISSUE THREAD

**Issue by CyberDevil75** [rathena/rathena#4848]
Hi,
on other servers this bug has already been discussed as you can read here:
https://www.limitro.com/forums/reportcenter/sourcebugs/ranger-aimed-bolt-fixed-cast-time-r934/

I believe that the "FixedCastTime" value of the Aimed Bolt skill in "/db/re/skill_db.yml" should not be 1000 but perhaps it must be 500:
https://github.com/rathena/rathena/blob/master/db/re/skill_db.yml#L20505

I'm not quite sure of this but I think it needs to be corrected.
Is what I say right?

**Comment by aleos89** [comment]
For future reports, please try to follow the template.

Also it’s official how it is currently implemented. Your link is from 2016 and the skill has changed since then. Please see #3659.
