### ISSUE TITLE
Target monster bug near walls

### ISSUE THREAD

**Issue by rubie123** [rathena/rathena#485]
There is an issue happening with targeting monsters near walls. When you target a monster near a wall the user moves to the cell where the monster is, instead of attacking it or doesn't attack at all.

You need to move the camera angle to be able to attack the monster.

The best map to test this out is gl_sew02

**Comment by Playtester** [comment]
Was there a line of sight available?

**Comment by rubie123** [comment]
Sorry, I don't understand your question..

**Comment by Playtester** [comment]
If you target someone and there is no clear line of side to it, like a wall tile in between, then you will walk towards the monster.

I'm not sure what you mean with move camera angle. If that fixes the problem it seems more like a client issue.

**Comment by rubie123** [comment]
The line is clear. This happens with most maps with walls. May be it is the client, I will try a new client out and update this.

**Comment by cydh** [comment]
can u tell me the detail?
1. Pic of the monster location on the map, and its coordinates.
2. ur char to attack it, normal attack or skill? ranged or melee?

**Comment by Playtester** [comment]
Yeah I think we need exact location data. Some maps have some invisible walls that block the line of sight and could cause such behavior (I know it happens in clock tower F3), but other than that I haven't observed this behavior before.

You could spawn an immobile map to see if you can find a 100% way to reproduce it and get the exact coordinates.

**Comment by aleos89** [comment]
It has been almost a year and no information was given on how to reproduce the issue.
