### ISSUE TITLE
Elemental arrows not matching elemental damage tables

### ISSUE THREAD

**Issue by LordWhiplash** [rathena/rathena#4857]
* **rAthena Hash**: not sure

* **Client Date**: 20180621

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Arrows damage seems to not work well
  * Expected Result: Arrows damage follow the element table 
  * How to Reproduce: hit with elemental arrow and compare to elemental % damage it should have done

For exemple: Kaho (ID1072 is fire 4, -50% Fire Damage, 75% Holy Damage) , he should not recieve any damage from a fire arrow, and recieve 25% reduction from a holy arrow, but comparing both arrow's hit he does recieve almost the same damage from a fire arrow.

![image](https://user-images.githubusercontent.com/62680611/80441793-040a6d00-88e2-11ea-98e8-0686301f9047.png)
(Reverberation Skill with Bow)

![image](https://user-images.githubusercontent.com/62680611/80441928-4d5abc80-88e2-11ea-9363-4724d2843eb7.png)
(Basic Normal Attack with Bow)

This seems to apply only when using bows... since when i've tried using the reverberation skill (up to date with Minstrel Improvement Project) this problems just show up using bow... (When using instrument, the elemental table was followed correctly).

![image](https://user-images.githubusercontent.com/62680611/80441828-1be1f100-88e2-11ea-9a20-bc7652efe838.png)
(Reverberation Skill with Instrument)

This problem is not related just to fire arrows (immaterial arrow is hitting Neutral 4 monsters, Megalith ID 1274 for exemple, he should recieve 0% damage from Ghost).

I apologize if I am making a mistake, either in the way I come to report this problem of mine, or if the fault of being this way is mine, thank you very much to everyone in the community, and thanks in advance for supporting this problem.

**Comment by aleos89** [comment]
I saw that when working Reverberation that AtkEle has a few weapons where even with ammo equipped, it forces to the weapons element.

You can find it here: https://github.com/rathena/rathena/blob/master/src/map/pc.cpp#L3061

**Comment by LordWhiplash** [comment]
Thanks for fast reply! And WOW, it involves more than just bows... this is supposed to work this way so? is the official behavior?

**Comment by aleos89** [comment]
I’m not sure about any of this behavior. Would have to test to confirm.

**Comment by LordWhiplash** [comment]
Ok, I will try to test and search for any information on the official servers and report here! Thanks!

**Comment by attackjom** [comment]
I have test in KRO sakray and found 
when Endow weapon with Curse Water it will force element to Dark despite equip with Holy arrow
please wait my picture.

**Comment by attackjom** [comment]
1st = silver arrow + no endow
![screenป็ลฉถ๓ภฬ008](https://user-images.githubusercontent.com/35770095/80447931-09e56a00-8945-11ea-9233-adcce56df754.jpg)

2nd = Dark arrow + no endow
![screenป็ลฉถ๓ภฬ009](https://user-images.githubusercontent.com/35770095/80447955-1c5fa380-8945-11ea-8db2-9c5378559409.jpg)

3rd = Dark arrow + Endow Holy Property (Sacred scroll)
![screenป็ลฉถ๓ภฬ011](https://user-images.githubusercontent.com/35770095/80447980-2c778300-8945-11ea-8c47-ac270c8ae609.jpg)

**Comment by aleos89** [comment]
How about with a Bow instead of an Instrument?

**Comment by attackjom** [comment]
Reverberation can't use with other weapon except Musical instrument and Whip

**Comment by aleos89** [comment]
Was that part of the Minstrel/Wanderer update? I don't see any reference or restriction to weapon for that skill.

**Comment by attackjom** [comment]
It didn't mention in patch note

But I have play in sakray few minutes ago.

**Comment by LordWhiplash** [comment]
Thanks for the screenshots, but the problem is not related with reverberation itself (good to know it works only with instrument and whip), and if can't use bow, reverberation cannot be used to see the behavior i've talked about... is it possible to test if your basic attack with bow do get the arrow's property?

I have accounts only in bRO and Ragnarok Transcendence, don't know if worths using these servers as parameters for testing, since they are outdated compared to kRO

**Comment by LordWhiplash** [comment]
Seems the damage is applying even on oficial servers, this test is with Magmaring (Fire 2 - 0% damage from fire / 100% damage from neutral)
![image](https://user-images.githubusercontent.com/62680611/80524668-5f7e3e80-8966-11ea-825a-195cdef837bb.png)
(bRO with Fire Arrow)
![image](https://user-images.githubusercontent.com/62680611/80524725-77ee5900-8966-11ea-9e2f-8c081c5696ba.png)
(bRO with Iron Arrow)

Now, in rAthena, using the same stats, level, equipment, monster and arrows:
![image](https://user-images.githubusercontent.com/62680611/80527428-b7b73f80-896a-11ea-9b4e-07f5a490b7f4.png)
(rAthena with Fire Arrow)

![image](https://user-images.githubusercontent.com/62680611/80527766-462bc100-896b-11ea-8167-ce9d623877c7.png)
(rAthena with Iron Arrow)

Looks like i've messed up, this is working as intented

**Comment by LordWhiplash** [comment]
Thanks for all the help! Closing
