### ISSUE TITLE
*BG_AREA command crashes map server

### ISSUE THREAD

**Issue by voyfmyuh** [rathena/rathena#4858]
* rAthena Hash: https://github.com/rathena/rathena/commit/4f11020a4e59704f1909ec615857b6af098b3683

* Client Date: 20180621

* Server Mode: Renewal

* Description of Issue: 

This code will also cause a crash!
for( i = 0; i < bg->members.size(); i++ )

![1588083126513](https://user-images.githubusercontent.com/54499336/80517883-5027e100-89b8-11ea-9f11-e72b80e4ef1a.jpg)

**Comment by aleos89** [comment]
I've applied the fix to #4725.

**Comment by aleos89** [comment]
Fixed in 14c388b.
