### ISSUE TITLE
Item_DB Sql Script Accentuation Won't Work

### ISSUE THREAD

**Issue by walterneto** [rathena/rathena#486]
Reposting from here: https://github.com/rathena/rathena/issues/483 as it was wrongly closed.

**Comment by anacondaqq** [comment]
no, it's not.
What do you want? 
Sorry, pleae try explain, i will try to help you.
Because there are many things which you must to know about langtype / servertype / encoding /database encoding / mysql connection.

**Comment by walterneto** [comment]
http://puu.sh/iCBqk/d4cc6f421a.png
Hope you understand now...

"Because there are many things which you must to know about langtype / servertype / encoding /database encoding / mysql connection."
What the hell is servertype?

Thanks for the attention.

**Comment by walterneto** [comment]
Dafuck, fixed it by removing all codepage configurations o.O

**Comment by anacondaqq** [comment]
i think, you have codepage latin1

/etc/mysql/my.conf

to 
[client]
default-character-set = utf8

to 
[mysqld]
init_connect='SET collation_connection = utf8_general_ci'
character-set-server=utf8
