### ISSUE TITLE
Fix bg_emp (again)  Adjust L_EmpDown

### ISSUE THREAD

**Issue by iraciz** [rathena/rathena#4861]
* **rAthena Hash**: 53ad415

* **Client Date**: 20180621

* **Server Mode**: Pre-Renewal

* **Description of Issue**: 
  * Result: Map server crashes when destroying emperium
  * Expected Result: Announce winner team and get rewards
  * How to Reproduce: Destroy any team emperium --- here: https://youtu.be/1UlOKi1jsbs
  * Official Information: https://github.com/rathena/rathena/blob/master/npc/custom/battleground/bg_emp.txt Line 75

* **Modifications that may affect results**: None, clean version.

**Comment by aleos89** [comment]
I'm unable to reproduce this on 73140bd (in Windows). Can you please provide the gdb crash or VS call stack?

**Comment by aleos89** [comment]
Were you able to identify the cause to this? I haven't had a chance to test on Linux.

**Comment by iraciz** [comment]
Seems fixed in the head revision, is not crashing anymore.
