### ISSUE TITLE
NPC_DARKBREATH

### ISSUE THREAD

**Issue by Masao87** [rathena/rathena#4864]
* **rAthena Hash**: 

* **Client Date**: 20180621

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Currently this skill always does damage depending on the max_hp of the target ( See battle.c NPC_DARKBREATH: md.damage = tstatus->max_hp * skill_lv * 10 / 100; ) instead of using the targets current HP not max HP. 
  * Expected Result: The skills dmg calculation should be done based on the targets current hp not max hp.
  * How to Reproduce: Spawn a Evil Snake Lord and let him hit you with the skill, he consistently does high dmg numbers because he always uses the max_hp. 
  * Official Information: Only from experience fighting Evil Snake Lord on official servers and him not hitting my RK with a constant 35k+ single hit dmg.
  

* **Modifications that may affect results**: Possible fix: Change tstatus->max_hp to tstatus->hp in battle.c

**Comment by Masao87** [comment]
https://irowiki.org/wiki/NPC_DARKBREATH At Lvl. 5 it should always do 50% dmg of HP.

**Comment by qwerty7vp** [comment]
it's Max HP
![image](https://user-images.githubusercontent.com/64515036/80738297-fa317580-8b3e-11ea-9093-13dfbb989dd1.png)

**Comment by Masao87** [comment]
It onlys says Max HP there because that's literally the title of the wiki page about HP in general on iRO Wiki. But I guarantee you 1000% the skill is not supposed to be calculated on max hp of the target.

**Comment by Masao87** [comment]
It's even pretty much impossible to level / mob old glastheim churchyard because the Dark Priest do so much dmg with the skill constantly.

**Comment by Masao87** [comment]
[https://cdn.discordapp.com/attachments/620648027878719498/710642904879857714/screenLotusRO092.jpg](url) But hey, lvl. 187 RK with royal guard sould definitly get one shot by ghostring :D @aleos89

**Comment by aleos89** [comment]
If we have a kRO source that says it should be current HP vs Max HP, then it’s an easy fix. I checked my current docs and it’s an older skill so it’s hard coded to the zone.

**Comment by Masao87** [comment]
Unfortunatly I couldn't find the skill or any info about the skill anywhere all you really can do is log in to a official server / kRO and let yourself get hit by Dark Priest, Ghostring or whatever other mob that has the skill and see how it affects your HP when hit.

As I said from experience from the euRO server before it closed like 1 year ago the skill was dealing dmg based on current HP displaying 9999 in red numbers above your head.

And I know it's super old and probably outdated but back in eAthena the skill was:

	case NPC_DARKBREATH:
		md.damage = 500 + (skill_lv-1)*1000 + rand()%1000;
		if(md.damage > 9999) md.damage = 9999;
		break;

////////////////////

	case NPC_DARKBREATH:
		{
			struct status_change *sc_data = status_get_sc_data(target);
			int hitrate=status_get_hit(bl) - status_get_flee(target) + 80;
			hitrate = ( (hitrate>95)?95: ((hitrate<5)?5:hitrate) );
			if(sc_data && (sc_data[SC_SLEEP].timer!=-1 || sc_data[SC_STAN].timer!=-1 ||
				sc_data[SC_FREEZE].timer!=-1 || (sc_data[SC_STONE].timer!=-1 && sc_data[SC_STONE].val2==0) ) )
				hitrate = 1000000;
			if(rand()%100 < hitrate) {
				damage = 500 + (skill_lv-1)*1000 + rand()%1000;
				if(damage > 9999) damage = 9999;
			}
		}
		break;

And I don't know when or why or if at all the skill actually got an update in formula?

**Comment by mrjnumber1** [comment]
in episode 15.2 
(skLevel <= 5) ? (100 / (2*6-skLevel)) : 50

the skill needs to be magic type, also it has a 50% success/fail chance on hit.  it is based on current HP, as well

**Comment by aleos89** [comment]
Looks like this was changed in fc76336.

**Comment by Masao87** [comment]
Well, I don't know how trustworthy NymphRO was or still is if the server is still around but the pictures he refered to seem to have been from that server, while my information is based on experience from the official euRO server stand episode 16.1 before it closed.

He also didn't cite any other official info. or sources to warrant that "fix" from back then as far as I can see.
