### ISSUE TITLE
SA_FREECAST - ASPD bug

### ISSUE THREAD

**Issue by Balferian** [rathena/rathena#4870]
* **rAthena Hash**: da523d9
* **Client Date**: -
* **Server Mode**: Pre/Re

* **Description of Issue**: 
  * Result: aspd up to 193.
  * Expected Result: aspd should be redused like in skill description.
https://github.com/rathena/rathena/blob/be0c0efe40db74b67b5d2b26d14bfc46977309b9/src/map/status.cpp#L5668
change **amotion += (2000 - amotion) * ( 55 - 5 * ( skill_lv + 1 ) ) / 100;**
to **amotion = amotion * 5 * (pc->checkskill(sd, SA_FREECAST) + 10) / 100;**
  * How to Reproduce: learn  low level skill (~1) SA_FREECAST, while casting spell aspd up to 193.
  * Official Information:
> 	[SKID.SA_FREECAST] = {
		"프리 캐스트 (Free Cast)",
		"MAX Lv : 10",
		"^777777습득조건 : 캐스트 캔슬 1^000000",
		"계열 : ^000099패시브^000000",
		"내용 : ^777777마법 캐스팅 중에도 이동과 공격이 가능해지는 대신 이동속도와 공격속도가 감소된다.",
		"이동속도와 공격속도는 스킬 레벨에 따라 달라진다.^000000",
		"^ffffff_^000000",
		"[Lv 1] : ^777777이동속도:30%, 공격속도: 55%^000000",
		"[Lv 2] : ^777777이동속도:35%, 공격속도: 60%^000000",
		"[Lv 3] : ^777777이동속도:40%, 공격속도: 65%^000000",
		"[Lv 4] : ^777777이동속도:45%, 공격속도: 70%^000000",
		"[Lv 5] : ^777777이동속도:50%, 공격속도: 75%^000000",
		"[Lv 6] : ^777777이동속도:55%, 공격속도: 80%^000000",
		"[Lv 7] : ^777777이동속도:60%, 공격속도: 85%^000000",
		"[Lv 8] : ^777777이동속도:65%, 공격속도: 90%^000000",
		"[Lv 9] : ^777777이동속도:70%, 공격속도: 95%^000000",
		"[Lv10] : ^777777이동속도:75%, 공격속도:100%^000000"
	},

* **Modifications that may affect results**: -

**Comment by aleos89** [comment]
It was changed here #4570.

**Comment by Daegaladh** [comment]
I don't understand what's the bug, currently ASPD is reduced to 55% when casting on level 1, to 60% on level 2, etc...
If you revert my fix, it goes up instead (because ASPD is calculated based on amotion)

**Comment by Daegaladh** [comment]
Fixed on 40c776340f7548c42046f4c4cca8d5bd73078cca
