### ISSUE TITLE
Need to update: Adoramus won’t work on targets standing inside Land Protector

### ISSUE THREAD

**Issue by teededung** [rathena/rathena#4876]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/e92f88a030dc6a2fb8a0ffe6bf1c1d2d1a977e26
* **Client Date**:  2018
* **Server Mode**:  Renewal

* **Description of Issue**: 
  * Result: Adoramus can cast on players inside Land Protector
  * Expected Result: Can't damage targets on Land Protector
  * Official Information: They described in skill description

**Comment by Tokeiburu** [comment]
Confirmed:
![archer4](https://user-images.githubusercontent.com/8761658/80837192-5db1b680-8bc4-11ea-8423-0b48d84d450b.gif)
