### ISSUE TITLE
bonus bMagicAddEle doesn't work.

### ISSUE THREAD

**Issue by ecdarreola** [rathena/rathena#4878]
* **rAthena Hash**: 2e4ec1d

* **Client Date**: 20180621

* **Server Mode**: Renewal

* **Description of Issue**: specific case or scenario wherein bonus2 bMagicAddEle,Ele_Holy,<value>; doesn't work on skills that has Holy Element (e.g. AB_ADORAMUS)
  * Result: Same damage output if the item or card is equipped with the said bonus
  * Expected Result: Should have additional damage with regards to Magic as the skill itself is magic and in holy property
  * How to Reproduce: Change class to AB -> modify any card to have the bonus "bonus2 bMagicAddEle,Ele_Holy,100; (Testing Purpose) -> use skill AB_ADORAMUS -> damage isn't increased

  * Official Information: Should increase damage
  

* **Modifications that may affect results**: None

**Comment by Tokeiburu** [comment]
bonus2 bMagicAddEle,e,x;  		+x% magical damage against element e
bonus2 bMagicAtkEle,e,x;  		Increases damage of e element magic by x%

bMagicAddEle is to increase damage on monsters with the specified element (ex: Angeling would take more damage). bMagicAtkEle is to increase the magical attack damage of a skill having the specified property, such as Adoramus.

You have to use bMagicAtkEle in your case, this behavior is the intended one.
