### ISSUE TITLE
PACKETVER 2019 - 2020 

### ISSUE THREAD

**Issue by tkporreta** [rathena/rathena#4879]
* **rAthena Hash**: 2e4ec1d1f656daaad832033c31a8b6939cb8d266

* **Client Date**: 2019 - 2020

* **Server Mode**: Pre-Renewal end Renewal

* **Description of Issue**: Added and organized the PACKETVER 2019 and 2020
**https://github.com/tkporreta/rathena/commit/163aa34b7807a588cf531c0baaa75e3175798175**

**Comment by aleos89** [comment]
I'll close this per #4944.
