### ISSUE TITLE
13.1 Guards display twice a message window OnTouch and get frozen

### ISSUE THREAD

**Issue by Artuvazro** [rathena/rathena#4881]
* **rAthena Hash**: 2e4ec1d

* **Client Date**: 2018-06-21

* **Server Mode**: pre-renewal

* **Description of Issue**: 
  * Result: Guard NPCs in lhz_b01 have a duplicate with an OnTouch label and a x,y area defined that makes the OnTouch trigger twice. When ep13_ryu > 19 the OnTouch triggered twice makes the message window appear twice, the second one without any NEXT button, so the NPC is frozen and the player has to foce-close the client.
  * How to Reproduce: Try to walk **between** two of the guards located at lhz_b01, for example, the ones at lhz_b01 147,252.

**Comment by Daegaladh** [comment]
This will be fixed with #4725

**Comment by Atemo** [comment]
Fixed in https://github.com/rathena/rathena/commit/7efd696af7da0f46bf291a3ed25509dbb9e164d2
