### ISSUE TITLE
Auto Spell Window, skill error message

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#4883]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/2e4ec1d1f656daaad832033c31a8b6939cb8d266
* **Client Date**: 20180921
* **Server Mode**: RE
* **Description of Issue**: When you 'cancel' the skill selection window returns an error message on the map_server, saying that the skill is invalid.

`[Error]: pc_checkskill: Invalid skill id 0 (char_id=150006).`

If you press 'OK' without selecting any of the skills listed in the window, it is generating random skill_id:
```
[Error]: pc_checkskill: Invalid skill id 0 (char_id=150006).
[Error]: Skill '13568' is undefined! E:\rathena\src\map\pc.cpp:6149::pc_checkskill
[Error]: pc_checkskill: Invalid skill id 13568 (char_id=150006).
[Error]: Skill '17664' is undefined! E:\rathena\src\map\pc.cpp:6149::pc_checkskill
[Error]: pc_checkskill: Invalid skill id 17664 (char_id=150006).
[Error]: Skill '23552' is undefined! E:\rathena\src\map\pc.cpp:6149::pc_checkskill
[Error]: pc_checkskill: Invalid skill id 23552 (char_id=150006).
```

Line: https://github.com/rathena/rathena/blob/master/src/map/pc.cpp#L6149

If you select the skill everything works correctly, but if you click 'cancel' or 'Ok' button the message appears on the map_server.

**Comment by admkakaroto** [comment]
If you press 'OK' it is generating random skill_id:

```
[Error]: pc_checkskill: Invalid skill id 7936 (char_id=150006).
[Error]: pc_checkskill: Invalid skill id 7680 (char_id=150006).
```

**Comment by Kreustoo** [comment]
Just for information, it goes through: https://github.com/rathena/rathena/blob/master/src/map/clif.cpp#L12929
And it is this check that is throwing the error:
https://github.com/rathena/rathena/blob/master/src/map/skill.cpp#L17750
But I dunno how the guidelines are for that kind of fix.

**Comment by admkakaroto** [comment]
Problem have started after this commit: https://github.com/rathena/rathena/commit/ea8da71cdda5cddbc05cdc736683487e5c14bf08
