### ISSUE TITLE
Peuz Greaves Gives Negative Status

### ISSUE THREAD

**Issue by Questune09** [rathena/rathena#4889]
* **rAthena Hash**:  e764fdd

* **Client Date**:  

* **Server Mode**:  Renewal

* **Description of Issue**: 
  * Result:  Peuz Greaves give negative and positive status after using.
![image](https://user-images.githubusercontent.com/29746866/80933779-92598400-8df7-11ea-928f-84ce7df016d1.png)
  * Expected Result:  i believed this should only give agi base on the item description.
  * How to Reproduce:  use at item 2496 and wear it.
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by admkakaroto** [comment]
Server mode? Hash?

**Comment by Questune09** [comment]
It works perfectly thank you.
