### ISSUE TITLE
Changecharsex - Bug

### ISSUE THREAD

**Issue by samurairukasu** [rathena/rathena#489]
Rathena: Last GIT Rev.
Exe: 20151022
Instance: Renewal

@aleos89 , i fund a new issue with command @changecharsex.
The command works perfect with new characters, but its seem not work well with pre exist characters created before the implementation of this.

If u use the command with new char, this change sex from Male to Female, u can see the sprite change from character selection and ingame sprite.
BUT
If u use the command with old character (before the implementation) it not change IN game, the sprite in game don´t  change from Male to Female and viceversa, but it change in character selection screen.

Regards

**Comment by julia40124009** [comment]
confirm in https://github.com/rathena/rathena/commit/58c2b773a287dd35de3b1a5ed2d62cc4d3cd42fc
clinet : 2014-10-22
re

**Comment by renniw** [comment]
thank you so much for very fast correct
