### ISSUE TITLE
mob chat not displaying

### ISSUE THREAD

**Issue by iraciz** [rathena/rathena#4901]
* **rAthena Hash**: 

* **Client Date**: 20180620

* **Server Mode**: pre-renewal

* **Description of Issue**: mobs are not displaying the chat associated to mob_chat_db
  * Result: not sending the chat in their associated skill
  * Expected Result: Monster talk with the color text after casting the skill with the mob_chat line_id
  * How to Reproduce: Summon any of this monsters: 1916,  1929,  2022
  * Official Information: they should talk.

  

* **Modifications that may affect results**: tested in a new clean rathena version

**Comment by Kreustoo** [comment]
Ok, I have the same problem, and while testing things, the ONLY changment I had was that line of useless code.
And SM just started talking (1916).
![wtf](https://user-images.githubusercontent.com/14162419/81226100-97325980-8fea-11ea-8dab-b7a1564333ea.JPG)

If I removes it, he doesn't talk anymore, it makes no sense to me but maybe it may help someone.
Or just if someone can tell me they have the same behaviour.

**Comment by iraciz** [comment]
> Ok, I have the same problem, and while testing things, the ONLY changment I had was that line of useless code.
> And SM just started talking (1916).
> ![wtf](https://user-images.githubusercontent.com/14162419/81226100-97325980-8fea-11ea-8dab-b7a1564333ea.JPG)
> 
> If I removes it, he doesn't talk anymore, it makes no sense to me but maybe it may help someone.
> Or just if someone can tell me they have the same behaviour.

Thank you Sir, I made that change it the problem was fixed.
![mobchatfix](https://user-images.githubusercontent.com/15825408/81237485-64c23580-8fc5-11ea-9422-9ec07f5f3e7c.png)

Now my question is? WHY WAS REMOVED THAT LINE?

**Comment by Daegaladh** [comment]
Please, don't close the issue until is fixed
