### ISSUE TITLE
Roulette 20151022 - Don´t Work

### ISSUE THREAD

**Issue by samurairukasu** [rathena/rathena#491]
@aleos89 Roulette for client 20151022 won´t work if the packets are not added to packet_db.txt for packet_ver 51.

Solution, add this to the end of //2014-10-22bRagexe packets in packet_db.txt:

// Roulette System [Yommy]
0x0A19,2,rouletteopen,0 // HEADER_CZ_REQ_OPEN_ROULETTE
0x0A1A,23 // HEADER_ZC_ACK_OPEN_ROULETTE
0x0A1B,2,rouletteinfo,0 // HEADER_CZ_REQ_ROULETTE_INFO
0x0A1C,-1 // HEADER_ZC_ACK_ROULETTE_INFO
0x0A1D,2,rouletteclose,0 // HEADER_CZ_REQ_CLOSE_ROULETTE
0x0A1E,3 // HEADER_ZC_ACK_CLOSE_ROULETTE
0x0A1F,2,roulettegenerate,0 // HEADER_CZ_REQ_GENERATE_ROULETTE
0x0A20,21 // HEADER_ZC_ACK_GENERATE_ROULETTE
0x0A21,3,rouletterecvitem,2 // HEADER_CZ_RECV_ROULETTE_ITEM
0x0A22,5 // HEADER_ZC_RECV_ROULETTE_ITEM

Regards!

**Comment by cydh** [comment]
1st, it's not 2015-10-22
2nd, it's work even those packets are not added to the ver 51, since 'newer' packets will use 'older' packets first as long as the 'older' packets are not overwritten in 'newer' version.

**Comment by samurairukasu** [comment]
1st: Sorry, it was a miss when i wrote the number to the post.
2nd: Without that packets roulette not let u spin even if u have coins, because the mouse arrow don´t change to a "Hand arrow" and u can click on button for spin.

The packets for roulette in packet_db are only for packet_ver: 50, but not added for 51.

If u test it u will see what i mean. Try to spin without roulette packets for 51 and with them.
