### ISSUE TITLE
Pre Renewal Genetic's Hell Plant

### ISSUE THREAD

**Issue by gidzdlcrz** [rathena/rathena#4911]
![image](https://user-images.githubusercontent.com/62187272/81402209-8ce79b00-9163-11ea-9f41-93855fdc6f3b.png)

* **rAthena Hash**: ca56c060c (manually updated to latest)

* **Client Date**: 20151104a

* **Server Mode**: PRE RENEWAL

* **Description of Issue**: This is about Hell's Plant by genetic using pre renewal. The new behavior is that skill is not ground type anymore. Once you casts it, it will stick to you auto damaging foes/mobs near you.
  * Result: It misses in PRE RENEWAL. Also, the skill is still ground type when you look into skill_db.yml.
  * Expected Result:  It should work accordingly.
  * How to Reproduce:  Set your server into PRE RE mode. And try the genetic's Hell Plant skill.

  * Official Information:
  

* **Modifications that may affect results**: N/A (Did some test in fresh clean rathena as well)

**Comment by Akkarinage** [comment]
Genetic is a Renewal Job Class. I'm not really sure why you think we'll be implementing fixes for Renewal content in Pre-Renewal databases.

**Comment by gidzdlcrz** [comment]
because it does work before in pre re setup.
