### ISSUE TITLE
instance_count will start to error at 1000

### ISSUE THREAD

**Issue by voyfmyuh** [rathena/rathena#4915]
* rAthena Hash: https://github.com/rathena/rathena/commit/d1719f670ffa77b6849bc97817b4d047c6970afd

* Client Date: 20180621

* Server Mode: Renewal

* Description of Issue: 
![1588974143821](https://user-images.githubusercontent.com/54499336/81452097-92230500-91b8-11ea-9eb1-1be82892b469.jpg)

**Comment by Atemo** [comment]
You're right
 https://github.com/rathena/rathena/blob/d1719f670ffa77b6849bc97817b4d047c6970afd/src/map/map.cpp#L2737
Missing changes in
https://github.com/rathena/rathena/blob/d1719f670ffa77b6849bc97817b4d047c6970afd/src/map/instance.cpp#L733
