### ISSUE TITLE
Missing Creamy Fear Item Drop.

### ISSUE THREAD

**Issue by AsurielRO** [rathena/rathena#4917]
* **rAthena Hash**: 

* **Client Date**:  20180621a

* **Server Mode**:  Renewal

* **Description of Issue**: 
  * Result:  Creamy Fear Doesn't show sound amplifier using at mi.
  * Expected Result:  Creamy Fear Should be drop Sound Amplifier if in Renewal Mode.
  * How to Reproduce: 
  * Official Information: https://www.divine-pride.net/database/item/2899/sound-amplifier-1
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Resolved in #4981.
