### ISSUE TITLE
New Super Novice skills cant be learnt

### ISSUE THREAD

**Issue by qwerty7vp** [rathena/rathena#4918]
* **rAthena Hash**: d1719f67

* **Client Date**: 20180919Ragexe , 20180620RagexeRE

* **Server Mode**: Renewal

* **Description of Issue**: Due to new commit of rA for Super Novice Job Improvement there are 3 new skills for it. Tried with latest clean rA no error showed in console just cant learn all new skills.

  * Result:  Skill cant be learnt
  * Expected Result:  Should work normally
  * How to Reproduce:  Create char with Job 4190 ( Super Novice ) and use `@allskills` 

![image](https://user-images.githubusercontent.com/64515036/81465166-1645ae80-91f2-11ea-98b8-d2aa9e5d1d46.png)

* **Modifications that may affect results**: Nothing

**Comment by reunite-ro** [comment]
have you check your Lua files is it exist in your data folder/GRF ?

**Comment by qwerty7vp** [comment]
> have you check your Lua files is it exist in your data folder/GRF ?

yup I checked
other skills that added in same commit like Zen, Fury, Storm Gust, etc. working normally
only these 3 skills that it didnt work as it should be

Is it working normally for you ?

**Comment by llchrisll** [comment]
As far as I know you need at least 2019 March client for these skills to kinda work

**Comment by Balferian** [comment]
@qwerty7vp After you use command **@allskills** check you sql table `skill` if your char have this skills in db then your exe doesn`t support this skills.
Also you can check that skills are working in game **@useskill <id>**

**Comment by qwerty7vp** [comment]
> @qwerty7vp After you use command **@allskills** check you sql table `skill` if your char have this skills in db then your exe (or LUA files) doesn`t support this skills.
> Also you can check that skills are working in game **@useskill **

it does have skills in skill table and skill popup when use **@useskill** (even if it's passive skill)

![image](https://user-images.githubusercontent.com/64515036/81476753-bc6ad600-923d-11ea-8a15-a96aa1318663.png)

![image](https://user-images.githubusercontent.com/64515036/81476798-00f67180-923e-11ea-8c95-78ddca15a954.png)

but still cant learn skills

did you try this ? is it work for you ?

**Comment by Balferian** [comment]
I have the same problem (exe 2018-05-20), but i think it`s client side problem, not server side.

**Comment by aleos89** [comment]
As @Balferian stated, this is a client limitation, not rAthena. Support of newer clients is coming soon.

**Comment by Stann0xus** [comment]
Was this fixed? Client 20211103 also has the issue (kRO updated till Feb 2024)
