### ISSUE TITLE
map_msg.conf

### ISSUE THREAD

**Issue by julia40124009** [rathena/rathena#492]
client : 2014-10-22 
version : https://github.com/rathena/rathena/commit/58c2b773a287dd35de3b1a5ed2d62cc4d3cd42fc

The last word of the message become "?"
must be in the final with a blank to display correctly

**Comment by julia40124009** [comment]
I found cause 
https://github.com/rathena/rathena/commit/58c2b773a287dd35de3b1a5ed2d62cc4d3cd42fc

safestrncpy((char*)WFIFOP(fd, 12), mes, len);

**Comment by icxbb-xx** [comment]
you can post screen shot with problem or command or message

**Comment by julia40124009** [comment]
http://i.imgur.com/35Un9ir.png
chinese
client 2014-10-22
