### ISSUE TITLE
S.A New Skills bug

### ISSUE THREAD

**Issue by LolyAll** [rathena/rathena#4922]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/d1719f670ffa77b6849bc97817b4d047c6970afd
* **Client Date**: 20180921
* **Server Mode**: Renewall
* **Description of Issue**: I just can't put points on the new skills in the class.
* **Modifications that may affect results**: RE drop disabled
![a111](https://user-images.githubusercontent.com/38357266/81482259-1652a800-920c-11ea-9410-da77ebb35f3a.png)

I used @allskills but it didn't work.

**Comment by pigati23** [comment]
https://github.com/rathena/rathena/pull/4919

**Comment by LolyAll** [comment]
this PR it is for PRE_RE, i have cited: RENEWALL

**Comment by aleos89** [comment]
Duplicate of #4918.

This is a client restriction, not rAthena.
