### ISSUE TITLE
Sonic Blow Forced Attack Animation

### ISSUE THREAD

**Issue by yashimwong** [rathena/rathena#4925]
* **rAthena Hash**: 49c4ddf8f904a3dde22b092adc41da3fb1438968

* **Client Date**: -

* **Server Mode**:  Renewal

* **Description of Issue**: 
  * Result: Using Assassin's Sonic Blow still causes forced attack animation, users have to wait for the animation to end before attacking
  * Expected Result: Sonic Blow should not force attack animation
  * How to Reproduce: Use sonic blow on assassin and equip items that give sonic blow auto cast
  * Official Information:
GIF here:
https://www.divine-pride.net/forum/index.php?/topic/3453-kro-mass-skills-balance-1st-2nd-and-transcendent-classes-skills/

* **Modifications that may affect results**: -

**Comment by aleos89** [comment]
Fixed in 8d2c26d with a follow up in 48fd0e8.

**Comment by hillbertbuen** [comment]
https://user-images.githubusercontent.com/81776650/130410932-075236c5-e9f6-4ad4-a12a-190ce87a8df9.mp4

Was this issue related to this? animation has been remove even on normal SB

**Comment by hillbertbuen** [comment]
how to solve this issue animation not working

**Comment by Daegaladh** [comment]
> 
> 2021-08-15.02-47-16.mp4
> 
> Was this issue related to this? animation has been remove even on normal SB

That's how it's supposed to work in renewal mode, there's no attack animation anymore since kRO's skill balance patch

**Comment by hillbertbuen** [comment]
Hi @Daegaladh but this is on prere mode.

**Comment by Daegaladh** [comment]
> Hi @Daegaladh but this is on prere mode.
I've just tested it in the lastest rathena on pre-re mode and works fine, so you must be doing something wrong
