### ISSUE TITLE
Error in SQL mob skill DB 05-10-2020

### ISSUE THREAD

**Issue by gmchatterboy** [rathena/rathena#4928]
[Status]: Done reading '25' entries in 'db/mob_classchange.txt'.
[Status]: Done reading '0' entries in 'db/pre-re/mob_drop.txt'.
[Status]: Done reading '0' entries in 'db/import/mob_chat_db.txt'.
[Error]: mob_parse_row_mobskilldb: Too many skills for monster 1150[MOONLIGHT]
[Error]: mob_parse_row_mobskilldb: Too many skills for monster 1511[AMON_RA]
[Error]: mob_parse_row_mobskilldb: Too many skills for monster 1637[MAGALETA]
[Error]: mob_parse_row_mobskilldb: Too many skills for monster 1639[KATRINN]
[Error]: mob_parse_row_mobskilldb: Too many skills for monster 1643[G_MAGALETA]
[Error]: mob_parse_row_mobskilldb: Too many skills for monster 1646[B_SEYREN]
[Error]: mob_parse_row_mobskilldb: Too many skills for monster 1647[B_EREMES]
[Error]: mob_parse_row_mobskilldb: Too many skills for monster 1649[B_MAGALETA]
[Error]: mob_parse_row_mobskilldb: Too many skills for monster 1650[B_SHECIL]
[Error]: mob_parse_row_mobskilldb: Too many skills for monster 1651[B_KATRINN]
[Error]: mob_parse_row_mobskilldb: Too many skills for monster 1719[DETALE]
[Error]: mob_parse_row_mobskilldb: Too many skills for monster 1734[KIEL_]
[Error]: mob_parse_row_mobskilldb: Too many skills for monster 1751[RANDGRIS]
[Error]: mob_parse_row_mobskilldb: Too many skills for monster 1779[KTULLANUX]
[Error]: mob_parse_row_mobskilldb: Too many skills for monster 1870[NECROMANCER]
[Error]: mob_parse_row_mobskilldb: Too many skills for monster 1871[FALLINGBISHOP]
[Error]: mob_parse_row_mobskilldb: Too many skills for monster 1874[BEELZEBUB_]
[Error]: mob_parse_row_mobskilldb: Too many skills for monster 1916[MOROCC]
[Error]: mob_parse_row_mobskilldb: Too many skills for monster 1917[MOROCC_]
[Error]: mob_parse_row_mobskilldb: Too many skills for monster 1929[BAPHOMET_I]
[Error]: mob_parse_row_mobskilldb: Too many skills for monster 1947[PIAMETTE_]
[Error]: mob_parse_row_mobskilldb: Too many skills for monster 1956[NAGHT_SIEGER]
[Error]: mob_parse_row_mobskilldb: Too many skills for monster 1990[HARDROCK_MOMMOTH]
[Error]: mob_parse_row_mobskilldb: Too many skills for monster 2009[WOOMAWANG_]
[Error]: mob_parse_row_mobskilldb: Too many skills for monster 2022[S_NYDHOG]
[Status]: Done reading '5173' entries in 'mob_skill_db'.

**Comment by Stingor** [comment]
confirm after fixing #4908

**Comment by RagnaWay** [comment]
This error is also with me.

**Comment by CyberDevil75** [comment]
error confirmed also in my server

**Comment by Daegaladh** [comment]
Fixed in 5154e078999ea8b0ae8680126933fe11a2506dd9

**Comment by gmchatterboy** [comment]
Thanks, sir Daegaladh ^_^ Amazing!!!
