### ISSUE TITLE
[Error]: pc_checkskill

### ISSUE THREAD

**Issue by gmchatterboy** [rathena/rathena#4929]
* **rAthena Hash**: 

 
48fd0e8
* **Client Date**: 
2018-06-20eRagexeRE

* **Server Mode**: 
 SQL

Pre-RE
* **Description of Issue**: 
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**: 
  
  

[Info]: achievement load complete from DB - id: 150000 (total: 2)
[Error]: Skill '5075' is undefined! pc.cpp:6149::pc_checkskill
[Error]: pc_checkskill: Invalid skill id 5075 (char_id=150000).
[Error]: Skill '5077' is undefined! pc.cpp:6149::pc_checkskill
[Error]: pc_checkskill: Invalid skill id 5077 (char_id=150000).
[Error]: Skill '5075' is undefined! pc.cpp:6149::pc_checkskill
[Error]: pc_checkskill: Invalid skill id 5075 (char_id=150000).
[Error]: Skill '5077' is undefined! pc.cpp:6149::pc_checkskill
[Error]: pc_checkskill: Invalid skill id 5077 (char_id=150000).
[Error]: Skill '5075' is undefined! pc.cpp:6149::pc_checkskill
[Error]: pc_checkskill: Invalid skill id 5075 (char_id=150000).
[Error]: Skill '5077' is undefined! pc.cpp:6149::pc_checkskill
[Error]: pc_checkskill: Invalid skill id 5077 (char_id=150000).
[Error]: Skill '5075' is undefined! pc.cpp:6149::pc_checkskill
[Error]: pc_checkskill: Invalid skill id 5075 (char_id=150000).
[Error]: Skill '5077' is undefined! pc.cpp:6149::pc_checkskill
[Error]: pc_checkskill: Invalid skill id 5077 (char_id=150000).
[Error]: Skill '5075' is undefined! pc.cpp:6149::pc_checkskill
[Error]: pc_checkskill: Invalid skill id 5075 (char_id=150000).
[Error]: Skill '5077' is undefined! pc.cpp:6149::pc_checkskill
[Error]: pc_checkskill: Invalid skill id 5077 (char_id=150000).
[Error]: Skill '5075' is undefined! pc.cpp:6149::pc_checkskill
[Error]: pc_checkskill: Invalid skill id 5075 (char_id=150000).
[Error]: Skill '5077' is undefined! pc.cpp:6149::pc_checkskill
[Error]: pc_checkskill: Invalid skill id 5077 (char_id=150000).
[Error]: Skill '5075' is undefined! pc.cpp:6149::pc_checkskill
[Error]: pc_checkskill: Invalid skill id 5075 (char_id=150000).
[Error]: Skill '5077' is undefined! pc.cpp:6149::pc_checkskill
[Error]: pc_checkskill: Invalid skill id 5077 (char_id=150000).
[Error]: Skill '5075' is undefined! pc.cpp:6149::pc_checkskill
[Error]: pc_checkskill: Invalid skill id 5075 (char_id=150000).
[Error]: Skill '5077' is undefined! pc.cpp:6149::pc_checkskill
[Error]: pc_checkskill: Invalid skill id 5077 (char_id=150000).

Modification: No
Installation: Fresh 
after I update using git pull today 05102020 that happens.

**Comment by qwerty7vp** [comment]
try this PR #4919

**Comment by gmchatterboy** [comment]
Thanks for the help Sir Qwerty7vp
