### ISSUE TITLE
[Error]: Skill 

### ISSUE THREAD

**Issue by bgamez23** [rathena/rathena#4936]
* **rAthena Hash**: 48fd0e859b7ae3b640700b7b7c82e1b239805562

* **Client Date**: 2018-11-07aRagexe

* **Server Mode**: Pre-re

* **Description of Issue**: Just run the fresh pre-re server make a novice.
  * Result:  [Error]: Skill '5075' is undefined! D:\Ragnarok\rathena\src\map\pc.cpp:6149::pc_checkskill
[Error]: pc_checkskill: Invalid skill id 5075 (char_id=150001).
[Error]: Skill '5077' is undefined! D:\Ragnarok\rathena\src\map\pc.cpp:6149::pc_checkskill
[Error]: pc_checkskill: Invalid skill id 5077 (char_id=150001).
[Error]: Skill '5075' is undefined! D:\Ragnarok\rathena\src\map\pc.cpp:6149::pc_checkskill
[Error]: pc_checkskill: Invalid skill id 5075 (char_id=150001).
[Error]: Skill '5077' is undefined! D:\Ragnarok\rathena\src\map\pc.cpp:6149::pc_checkskill
[Error]: pc_checkskill: Invalid skill id 5077 (char_id=150001).
[Error]: Skill '5075' is undefined! D:\Ragnarok\rathena\src\map\pc.cpp:6149::pc_checkskill
[Error]: pc_checkskill: Invalid skill id 5075 (char_id=150001).
[Error]: Skill '5077' is undefined! D:\Ragnarok\rathena\src\map\pc.cpp:6149::pc_checkskill
[Error]: pc_checkskill: Invalid skill id 5077 (char_id=150001).
[Error]: Skill '5075' is undefined! D:\Ragnarok\rathena\src\map\pc.cpp:6149::pc_checkskill
[Error]: pc_checkskill: Invalid skill id 5075 (char_id=150001).
[Error]: Skill '5077' is undefined! D:\Ragnarok\rathena\src\map\pc.cpp:6149::pc_checkskill
[Error]: pc_checkskill: Invalid skill id 5077 (char_id=150001).
[Error]: Skill '5075' is undefined! D:\Ragnarok\rathena\src\map\pc.cpp:6149::pc_checkskill
[Error]: pc_checkskill: Invalid skill id 5075 (char_id=150001).
[Error]: Skill '5077' is undefined! D:\Ragnarok\rathena\src\map\pc.cpp:6149::pc_checkskill
[Error]: pc_checkskill: Invalid skill id 5077 (char_id=150001).
[Error]: Skill '5075' is undefined! D:\Ragnarok\rathena\src\map\pc.cpp:6149::pc_checkskill
[Error]: pc_checkskill: Invalid skill id 5075 (char_id=150001).
[Error]: Skill '5077' is undefined! D:\Ragnarok\rathena\src\map\pc.cpp:6149::pc_checkskill
[Error]: pc_checkskill: Invalid skill id 5077 (char_id=150001).
[Error]: Skill '5075' is undefined! D:\Ragnarok\rathena\src\map\pc.cpp:6149::pc_checkskill
[Error]: pc_checkskill: Invalid skill id 5075 (char_id=150001).
[Error]: Skill '5077' is undefined! D:\Ragnarok\rathena\src\map\pc.cpp:6149::pc_checkskill
[Error]: pc_checkskill: Invalid skill id 5077 (char_id=150001).
[Error]: Skill '5075' is undefined! D:\Ragnarok\rathena\src\map\pc.cpp:6149::pc_checkskill
[Error]: pc_checkskill: Invalid skill id 5075 (char_id=150001).
[Error]: Skill '5077' is undefined! D:\Ragnarok\rathena\src\map\pc.cpp:6149::pc_checkskill
[Error]: pc_checkskill: Invalid skill id 5077 (char_id=150001).

  * Expected Result: 
  * How to Reproduce: Make a full pre-re server then login a newly created char.

* **Modifications that may affect results**: Full Pre-re config

**Comment by qwerty7vp** [comment]
#4919

**Comment by aleos89** [comment]
Pushed to master in c5a0279.
