### ISSUE TITLE
Skill "Xeno Slasher" of the homunculus "Eira" not work 

### ISSUE THREAD

**Issue by CyberDevil75** [rathena/rathena#4938]
* **rAthena Hash**: 48fd0e859

* **Client Date**: 2018-06-21aRagexeRE (GRFs updates with "RO Patcher Lite" today)

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: The skill of the homunculus "Eira" called "Xeno Slasher", fails with this message "There is no target in attack range vicinity... etc" when in reality the enemies are there. I tried with both the skill at level 1 and at level 10 and it still doesn't work, always giving that message you see in the screenshot below.
  * Expected Result: That at least once in 1000 attempts worked
  * How to Reproduce: updating rathena
  * Official Information:n/a
  

* **Modifications that may affect results**: I have had this bug on my server for some time and I think it started when there was the update of the conversion of DB files from TXT to YAML, but I am not 100% sure
![screenINFINITY001](https://user-images.githubusercontent.com/19527283/81689062-468f8600-945a-11ea-894e-16a40cff040f.jpg)

**Comment by SeravySensei** [comment]
I noticed the same thing today, both of the attack skills on that homunculus do not work until you alt-right click any enemy first before using the skill - not even the single target skill. Afterwards they both work fine. Haven't tested other types of homunculus S.

**Comment by aleos89** [comment]
Is this from a homunculus AI change by Gravity, rather than rAthena? I don't recall anything that would have changed homunculus behavior like this.

**Comment by TakeROo123** [comment]
I have the same problem with Dieter Lava Slide

**Comment by attackjom** [comment]
Gravity has remove AI from homunculus and every AOE-ground skill  need to order your homunculus to attack target before cast those skill.

Anyway, HomunAI and Freely-AOE cast  has comeback in  2020-03-04ragexeRE

**Comment by aleos89** [comment]
As I thought, will chalk this up as a client "feature".
