### ISSUE TITLE
Map Crash - NPC_METAMORPHOSIS

### ISSUE THREAD

**Issue by Zeloss** [rathena/rathena#494]
When someone is killing a monster with Metamorphosis and he starts to transform, the map server crashes.

-Latest Revision (Renewal) Client: 20130807
How reproduce: In abbey03 fight with Beelzebub until 50% HP, and wait to the progress bar to end.

And i'm receiving this errors only on WoE (screen 1), crashes the map server when this happens continously (screen 2).
![crash](https://cloud.githubusercontent.com/assets/10086618/8399190/a68ac7e0-1e08-11e5-812c-0af72896192b.png)

![crash2](https://cloud.githubusercontent.com/assets/10086618/8399207/3b9c59ca-1e09-11e5-8152-7b4c315c3f7f.png)

**Comment by anacondaqq** [comment]
can you provide a little bit more information? 
1. prere? re?
client date?
how reproduce?

**Comment by Zeloss** [comment]
Added more info, i can't reproduce, now it's a random crash, not only in WoE.
I enabled gdb but I don't know how works.

**Comment by reunite-ro** [comment]
yes.. random crash.. just on server for 2 minutes and crash

**Comment by Zeloss** [comment]
If you have the same trouble, remove all NPC_METAMORPHOSIS from mob_skill DB.
Since I did this my server didn't crash.

**Comment by reunite-ro** [comment]
Even i remove all NPC_METAMORPHOSIS, its still happen. wew
random crash.. no logs for this crash
![capture](https://cloud.githubusercontent.com/assets/11705163/8489088/9a89822a-214a-11e5-9e5a-91328b004024.JPG)

**Comment by Zeloss** [comment]
Are you sure you removed all NPC_METAMORPHOSIS? mob_skill_db_re and mob_skill_db2?
Removing it solved the crash for me.

**Comment by reunite-ro** [comment]
yes  im using search and replace function, replacing all NPC_METAMORPHOSIS?. and also VIP not worked.

**Comment by Playtester** [comment]
Did you replace the skill id as well?

**Comment by reunite-ro** [comment]
i just removing all NPC_METAMORPHOSIS in mob_skill_db

**Comment by Canoe** [comment]
For me, I managed to track down this crash to this change: https://github.com/rathena/rathena/commit/9b87ca2b7cd826b42d9a1753da055e2c9e7adf33#diff-d7fbb44006c719dd72b243469e4f80e0L2855

In this same commit mobdb is added but is never set to anything other than null. I reverted line 2880 back to `md->db = mob_db(mob_id)` and the crashes stopped. You don't have to remove NPC_METAMORPHOSIS then.

**Comment by renniw** [comment]
thank you so much Canoe  for solve the problem
