### ISSUE TITLE
Equip Restriction Bug

### ISSUE THREAD

**Issue by reunite-ro** [rathena/rathena#4940]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/8d2c26d115f0c44fb2d53efb5409c43ad0103946

* **Client Date**: 20180620

* **Server Mode**: Renewal

* **Description of Issue**: Equip restriction bug for example high novice can equip whip, katar, and so on. Sorry for the picture, its not mine and he asking why hunter bow isnt unequipped, here where this issue was found.
![image](https://user-images.githubusercontent.com/11705163/81728938-c7cc3480-94bd-11ea-8766-3fa37138e7ac.png)

  * Result: Seems like the equip restriction are gone, not only after using jobmaster. 
  * Expected Result: Only required jobs can equip certain equipments depends on job requirements.
  * How to Reproduce: Actually I cannot reproduce it yet. ive tried recompile, restart server and the issue still persist. Until I tried to use reloaditemdb commands and this bug fixed (weird it didnt fixed even I restart server) . Btw, theres no changes in itemdb so it comes from original rathena files.

![image](https://user-images.githubusercontent.com/11705163/81729683-f26abd00-94be-11ea-9498-d1b4ea6bea04.png)

**Comment by aleos89** [comment]
Did you give a player group the `all_equipment` permission? I was unable to reproduce this on 7004fe3.

![image](https://user-images.githubusercontent.com/3521753/82005670-f53aee80-9633-11ea-9be9-021cd87dd6d8.png)

**Comment by reunite-ro** [comment]
Ive check all_equipment permission too. The weird thing is, restart server also didnt solve that.
1. ive check the groups.conf to check about the permission/commands.
2. ive restart server and its still occur.
3. ive tried to reloaditemdb and suddenly this issue fixed and I cant reproduce again after that.
itemdb related files isnt touched yet as shown above.

So far until now I cannot reproduce this again.
