### ISSUE TITLE
ATK display in the player's status window.

### ISSUE THREAD

**Issue by Aruar** [rathena/rathena#4943]
rAthena Hash: last
Client Date: 2018-06-21aRagexe
Server Mode: Pre-Renewal
Description of Issue: All items that use bAtkRate do not show the attack being increased in the window (ALT + A). Is there any fix for this?

**Comment by qwerty7vp** [comment]
I think this is a normal behavior for bAtkRate item script

**Comment by secretdataz** [comment]
Intended behavior

**Comment by Aruar** [comment]
I modified the client.conf and it worked. (I never imagined it was that lol)

It was like this: min_body_style: 1
max_body_style: 5

Correct: min_body_style: 0
max_body_style: 1

Sorry for the inconvenience.

**Comment by Aruar** [comment]
> I think this is a normal behavior for bAtkRate item script

I understand that it can be normal. But is it possible to be implemented? MatkRate appears normally, only bAtkRate does not
