### ISSUE TITLE
Valkyrie Knife

### ISSUE THREAD

**Issue by Questune09** [rathena/rathena#4946]
* **rAthena Hash**: 

* **Client Date**: 

 20180620a

* **Server Mode**: 

 Renewal

* **Description of Issue**: 
  * Result:  After equipping the valkyrie knife some effects are missing using super novice job
  * Expected Result:  it should have the other effects base on the item description
  * How to Reproduce: 
  * Official Information: https://www.divine-pride.net/database/item/28717/valkyrie-knife-4
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Fixed in bb5fd45.
