### ISSUE TITLE
Back Slide bug

### ISSUE THREAD

**Issue by Aruar** [rathena/rathena#4950]
**rAthena Hash**: lastest (2 days ago)
**Client Date**: 2018-06-21aRagexe
**Server Mode**: Pre-Renewal
Description of Issue: Cell bugging in classes Assassin and Stalker
GIF: https://gyazo.com/805a546744155369aca8a44710dc5387

**Comment by Daegaladh** [comment]
My mistake, fixed in 132e74bd13629898c0d1f0c16be5a6a33607c734

**Comment by Aruar** [comment]
> My mistake, fixed in [132e74b](https://github.com/rathena/rathena/commit/132e74bd13629898c0d1f0c16be5a6a33607c734)

ty!
