### ISSUE TITLE
Dungeon Teleport Servicee

### ISSUE THREAD

**Issue by trinitynetworks** [rathena/rathena#4952]
* **rAthena Hash**: cb21220

* **Client Date**:  2018-06-21

* **Server Mode**: Pre-re

* **Description of Issue**: Errors in the console

[Error]: buildin_announce: fatal error ! player not attached!
[Debug]: Function: announce (3 parameters):
[Debug]: Data: string value="Currently, the Dungeon Teleport Service Provider Election is being held in all major cities. Your participation is appreciated."
[Debug]: Data: number value=1
[Debug]: Data: string value="0x70dbdb"
[Debug]: Source (NPC): Scrutiny Association#5 at yuno (103,225)

  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

Just have the npc of dungeon teleport service running.

* **Modifications that may affect results**: 
  
  

I have no modifications

**Comment by Atemo** [comment]
Unable to reproduce on renewal and prerenewal on https://github.com/rathena/rathena/commit/03fa1af7a802565a1f5e12401ff7f98d2ca8031f

**Comment by trinitynetworks** [comment]
I don't know it just showed in my console. Please look into it.

**Comment by aleos89** [comment]
Can you please provide a valid hash? That line of the NPC looks to be normal and working as intended.
