### ISSUE TITLE
GN_HELL_PLANT

### ISSUE THREAD

**Issue by ecdarreola** [rathena/rathena#4959]
* **rAthena Hash**: 7004fe3

* **Client Date**: 20180621

* **Server Mode**: Renewal

* **Description of Issue**: Hell Plant skill still being removed upon map change.
  * Result: Upon map change hell plant skill unit is being removed however status icon remains on the player.
  * Expected Result: Unit should still be attached on the player?
  * How to Reproduce: Cast hell plant to map A with mobs to see damage and move to different map.
  * Official Information: 
It was discussed here https://github.com/rathena/rathena/pull/4813#issuecomment-623208057
and was changed in https://github.com/rathena/rathena/pull/4813/commits/62822e1949c29b3ac74f9cc7c4c497622029a768
  

* **Modifications that may affect results**: Several PR but should not affect GN_HELL_PLANT.

**Comment by Badarosk0** [comment]
This should be the official behavior of the skill in kRO, please note: https://www.youtube.com/watch?v=qYPSy0EX4J8&t
@ecdarreola

**Comment by ecdarreola** [comment]
> This should be the official behavior of the skill in kRO, please note: https://www.youtube.com/watch?v=qYPSy0EX4J8&t
> @ecdarreola

Yeah I noticed that the animation is removed but still damage is still there. What's missing is the damage after changing map.

**Comment by attackjom** [comment]
If you use 2020 client
Plant effect is a vfx attach to EFST_HELL_PLANT  not a Unit_id.

So, specialeffect will remove when changing map but attack's mechanism is still.
