### ISSUE TITLE
[Fatal Error]: File not found: conf/inter_athena.conf

### ISSUE THREAD

**Issue by lks45** [rathena/rathena#496]
Hey guys,
 
Im using ubuntu 15.04 and i follow the guide from the wiki to install in Debian OS.
 
Well, i got a "[Fatal Error]: File not found: conf/inter_athena.conf" when i start the emulator. But im 100% sure the files exist in conf folder.

My compilation result: http://s12.postimg.org/5ebe6w9rh/install.jpg

OS: Ubuntu 15.04 x64 (system is uptodate).
 
Thanks for any help.

**Comment by aleos89** [comment]
This isn't a bug. Please create a topic in the General Support section of the forum.
