### ISSUE TITLE
atcommand_servertime Program received signal SIGSEGV

### ISSUE THREAD

**Issue by marky291** [rathena/rathena#4960]
using the @atcommand servertime produces this log, and is dependant on time requested.

**I am using pre-renewal mode, with github date 20th April 2020.**

atcommand_servertime (fd=11, sd=0x55555a6f37c0, command=<optimized out>, message=<optimized out>) at atcommand.cpp:4896
4896                            sprintf(temp, msg_txt(sd,233), txt_time(DIFF_TICK(timer_data->tick,gettick())/1000)); // Game time: The game is in night for %s.

[servertime.txt](https://github.com/rathena/rathena/files/4636256/servertime.txt)

**Comment by zellkennedy** [comment]
I can't reproduce this error.

![image](https://user-images.githubusercontent.com/28408973/82083106-8a36f980-96bf-11ea-88a9-cdeba42ffaa0.png)

**Comment by marky291** [comment]
Dependent on time, it works and sometimes crashes.

**Comment by prathon** [comment]
help..

got the same problem

anyone know how to fix this?

will highly appreciate any help

ASAP :)

**Comment by aleos89** [comment]
From the looks of your crash dump your timer_data is null, so when it tries to access the tick it’s crashing. Would have to see why day_timer_tid is not returning a valid timer.

**Comment by aleos89** [comment]
I was unable to reproduce this on 7004fe3, on Windows.

![image](https://user-images.githubusercontent.com/3521753/82135463-0d944000-97d1-11ea-9f68-e0e4d38e2f9d.png)

What are your night configs?

**Comment by marky291** [comment]
![FDA85B9F-5BDB-4678-8278-45105EE3774B](https://user-images.githubusercontent.com/5384515/82422835-dea0f700-9a7a-11ea-9840-be927ea16a1c.png)
![CE53387D-A13C-4B4A-AC47-91E76952EE3F](https://user-images.githubusercontent.com/5384515/82422845-e365ab00-9a7a-11ea-903e-815e1f325f11.png)

**Comment by aleos89** [comment]
Thank you for your config settings, because that is exactly what it is. You're defining a day time value but not a night time value. You might as well keep your configs 0 and 0.

But the reason this is happening is because the server is attempting to create a night time timer ID since you defined a day value. The end is result is that there is no defined night time timer ID since your config is 0 -- which means the server is in permanent night time.

**Comment by marky291** [comment]
@aleos89 noticed this too when I took some time to actually find it was using configs. Thanks :)
