### ISSUE TITLE
SC Plagiarism & Reproduce

### ISSUE THREAD

**Issue by ecdarreola** [rathena/rathena#4962]
* **rAthena Hash**: 7004fe3

* **Client Date**: 20180621

* **Server Mode**: Renewal

* **Description of Issue**: Not sure if this is an issue but worth the try (Had uploaded a video so that it's easy to follow. Link: https://youtu.be/4dIQWpmCk00 )
  * **Main Issues**:
-- Plagiarism is copying 2 skills when being hit and additional skill when the skill reproduce is on.
-- When reproduce is one, the preserve skill are being overwritten (not sure if this is intended)
-- Napalm beat being casted many times will remove all and just retain the skill itself.
  * **Result**: As shown in the video or described above.
  * **Expected Result**: 
Not quite sure what should be the result but I think it should be:
-- Max of 1 skill if only plagiarism is used and preserved
-- Additional skill if reproduce is used and should not overwrite the preserved skill
  * **How to Reproduce**: Create 2 character of different account. Just use @allskill for easy testing.
  * **Official Information**: I based it from the description of the skill and some website like DP, RMS and etc.
  

* **Modifications that may affect results**: Several PR but it doesn't touch the code for the said skill.

**Comment by aleos89** [comment]
Plagiarism is copying one skill while Reproduce is copying another, that's why you see 2 skills. I've confirmed that this is intended behavior on Aegis:
![image](https://user-images.githubusercontent.com/3521753/83152673-15ef5380-a0cc-11ea-8ced-c0f3e03ce330.png)

I didn't have to use Preserve to hold the skill to get the second.

**Comment by ecdarreola** [comment]
Is it normal that even you are using preserve the skill is being changed like on the video?
