### ISSUE TITLE
Segmentation fault on FreeBSD

### ISSUE THREAD

**Issue by Edduaardo** [rathena/rathena#4965]
* **rAthena Hash**: 7004fe3d9

* **Client Date**: 2018-06-20

* **Server Mode**: Renewal

* **Description of Issue**: It seems that I am unable to run both map-server and char-server on FreeBSD (login-server runs fine). They both give me the error "Segmentation fault (core dumped)". Is FreeBSD still supported by rA or it's a know issue?
  * Result: Both map-server and char-server gives Segmentation fault error on launch
  * Expected Result: Both map-server and char-server launch without problems
  * How to Reproduce: Compile and try to run on FreeBSD 12 Release
  * Official Information:
  

* **Modifications that may affect results**: None, the source was not modified in any way.

**Comment by aleos89** [comment]
Can you post the gdb?

**Comment by Edduaardo** [comment]
I don't know how to use gdb very much, but I think you mean this

map-server:
![image](https://user-images.githubusercontent.com/41928360/82132288-9ea8ee00-97b4-11ea-9f0b-b5db13e0fb30.png)

char-server:
![image](https://user-images.githubusercontent.com/41928360/82132310-c39d6100-97b4-11ea-9a30-7d3eda8e696e.png)

**Comment by aleos89** [comment]
You can find the guide on our [wiki](https://github.com/rathena/rathena/wiki/GDB).

**Comment by Edduaardo** [comment]
I generated the core files but the full stack is not being saved on them, only when I run with gdb I can use bt full command.

https://pastebin.com/ef33nsba

**Comment by aleos89** [comment]
I see you're using gcc9. Our Travis is currently only testing up to 8. I'm not sure of any changes that have happened that far ahead. What happens if you try with an older version of gcc?

**Comment by Edduaardo** [comment]
The same error occurs. I installed gcc8 and passed to the configure script like this:

`./configure CC=/path/to/gcc8 CXX=/path/to/g++8`

It compiled succesfully but with some warnings:

`scanner.h:208:17: warning: type of 'libconfig_yy_scan_string' does not match ori                                                                                        ginal declaration [-Wlto-type-mismatch]
scanner.c:1964:17: note: 'libconfig_yy_scan_string' was previously declared here
scanner.c:1964:17: note: code may be misoptimized unless -fno-strict-aliasing is                                                                                         used
scanner.h:202:6: warning: type of 'libconfig_yy_delete_buffer' does not match or                                                                                        iginal declaration [-Wlto-type-mismatch]
scanner.c:1743:10: note: 'libconfig_yy_delete_buffer' was previously declared he                                                                                        re
scanner.c:1743:10: note: code may be misoptimized unless -fno-strict-aliasing is                                                                                         used
`

And tried to execute, still gives me Segmentation fault:
https://pastebin.com/aYqEEB7Y

**Comment by aleos89** [comment]
Those libconfig warnings are fine.

What happens if you pass the CFLAGS `-static-libgcc -static-libstdc++` during configure?

**Comment by Edduaardo** [comment]
Like this?

`./configure CFLAGS='-static-libgcc -static-libstdc++' CC=/usr/local/bin/gcc8 CXX=/usr/local/bin/g++8`

`configure: CFLAGS= -flto -fuse-linker-plugin -static-libgcc -static-libstdc++ -pipe -ffast-math -Wall -Wempty-body -Wno-switch -Wno-missing-field-initializers -Wno-maybe-uninitialized -Wno-clobbered -Wshadow`

Same problem:
https://pastebin.com/8gHVHSij

I am testing on a FreeBSD Google Cloud image, to make sure it was not the image's fault I downloaded a image from FreeBSD site and tested using a VM on my computer, nothing changed.

**Comment by aleos89** [comment]
I don't have a FreeBSD environment to test this out, but it seems like something between FreeBSD and GCC, which hopefully has been resolved in the past year. If you still have issues feel free to comment back here or open a new issue.
