### ISSUE TITLE
help me with this error

### ISSUE THREAD

**Issue by denischoo88** [rathena/rathena#497]
Module Name: C:\Users\Denis\Desktop\RO\RO\Ragnarocks.exe
Time Stamp: 0x4c341251 - Wed Jul 07 13:36:17 2010

Exception Type: 0xc0000005

0x00402564	Ragnarocks.exe
0x0040190e	Ragnarocks.exe
0x0042ac51	Ragnarocks.exe
0x00547b92	Ragnarocks.exe
0x00525c5b	Ragnarocks.exe
0x0059f0ce	Ragnarocks.exe
0x00530ca4	Ragnarocks.exe
0x006ff17a	Ragnarocks.exe
0x007136ad	Ragnarocks.exe
0x76cd33ca	kernel32.dll
0x77a19ed2	ntdll.dll
0x77a19ea5	ntdll.dll

eax: 0x48ed0034	ebx: 0x19ace6cc
ecx: 0x00000005	edx: 0x00000016
esi: 0x48ed0034	edi: 0x00000014
ebp: 0x0018f4e0	esp: 0x0018f4d8

stack 0018f4d8 - 0018f8d8
0018F4D8 : 20 00 ED 52 14 00 00 00 24 F5 18 00 0E 19 40 00 
0018F4E8 : 14 00 00 00 34 00 ED 48 30 F5 18 00 50 38 88 0E 
0018F4F8 : 50 38 88 0E 01 00 00 FF 01 00 00 00 00 00 00 00 
0018F508 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01 
0018F518 : 4F 62 6A 65 00 00 80 00 34 00 ED 48 24 F7 18 00 
0018F528 : 51 AC 42 00 EC F5 18 00 62 F8 18 00 A0 00 00 00 
0018F538 : 40 DA AC 19 63 68 75 72 63 68 6C 61 6D 70 5F 30 
0018F548 : 31 00 00 00 88 14 68 19 68 1E 86 19 E0 FB 24 19 
0018F558 : F8 3B 00 00 00 00 96 00 F8 3B 00 00 28 13 68 19 
0018F568 : 58 F6 18 00 9E 38 A1 77 38 01 96 00 7A 38 A1 77 
0018F578 : FB 23 5D 77 00 00 00 00 00 00 00 00 00 00 00 00 
0018F588 : 00 00 00 00 00 00 00 00 17 00 00 00 00 00 00 00 
0018F598 : 00 00 00 00 00 00 00 00 00 00 00 00 9C E9 18 00 
0018F5A8 : C2 10 8B 64 94 02 00 00 C4 E9 18 00 04 00 00 00 
0018F5B8 : 20 00 D4 02 00 00 80 3F 00 00 00 80 00 00 00 00 
0018F5C8 : 00 00 00 00 00 00 00 80 00 00 80 3F 00 00 00 00 

Launch Info 
0000 0000 0000 0000 0000 0000 0000 0000 
0000 0000 0000 0000 0000 0000 0000 0000 
0000 0000 0000 0000 0000 0000 0000 0000 
0000 0000 0000 0000 0000 0000 0000 0000 

Job : Glt. Cross

**Comment by nanakiwurtz** [comment]
This is for "Server" bug reports, not for client support.
For asking assistance, please go to the forum.
