### ISSUE TITLE
*/battlechat bug!

### ISSUE THREAD

**Issue by voyfmyuh** [rathena/rathena#4973]
* rAthena Hash: https://github.com/rathena/rathena/commit/7004fe3d95610a8311628a53e84201dd8f6f8863

* Client Date: 20180621

* Server Mode: Renewal

* Description of Issue: 
As in the case of the picture, I can't see the message, but the teammates will see the repeated message
![1589741703160](https://user-images.githubusercontent.com/54499336/82157307-3e4ca600-98b3-11ea-8d4e-302afa280eea.jpg)

**Comment by Daegaladh** [comment]
This will be fixed on #4725

**Comment by aleos89** [comment]
Fixed in 14c388b.
