### ISSUE TITLE
Vip system is no longer working

### ISSUE THREAD

**Issue by tmav94** [rathena/rathena#498]
The server sends the message to the user but does not record the change of category in the database.

Only a message appears in the server logs

[DEBUG]: Source at NPC: ...

Not working:
vip_time;
atcommand "@vip";

**Comment by reunite-ro** [comment]
yes. beware. if players using vip before, then the storage will become default back. many items gone from VIP acounts before if reach default storage

**Comment by julia40124009** [comment]
confirm this

**Comment by reunite-ro** [comment]
sure confirm.. if people using VIP storage before.. its going to save default storage only... beware

**Comment by sammeepay** [comment]
Fix Bug Vip System

fix scr files 'scr/char/char_mapif.c'

Find or Go To Line '737'
'		if (operation == 2) {
			timediff = RFIFOL(fd, 32);
			val1 = RFIFOL(fd, 36);
		} else if (operation == 7)
			sex = RFIFOB(fd, 32);
		RFIFOSKIP(fd,44);
'
Replace
'		if (operation == 2) {
			timediff = RFIFOL(fd, 32);
			val1 = RFIFOL(fd, 36);
		} else if (operation == 6){
			timediff = RFIFOL(fd, 32);
			val1 = RFIFOL(fd, 36);
		} else if (operation == 7)
			sex = RFIFOB(fd, 32);
		RFIFOSKIP(fd,44);
'

Save and recompile

Fix VIP System is Working!!

**Comment by reunite-ro** [comment]
ya its work as @sammeepay tell us. already tested. Thanks

**Comment by aleos89** [comment]
Fixed in 89c9b7b. Forgot to add symbol to commit message to make the link.
