### ISSUE TITLE
Some problems on Mechanic

### ISSUE THREAD

**Issue by LordWhiplash** [rathena/rathena#4980]
* **rAthena Hash**: d9f5331

* **Client Date**: 20180621

* **Server Mode**: Renewal

* **Description of Issue**: MC_CHANGECART is not working on Mado, and MC_CARTDECORATE is giving the cart (not sure if this is the official behavior)

  * Result: 
![image](https://user-images.githubusercontent.com/62680611/82267221-18221700-9942-11ea-8301-2132f48c2ad8.png)
(Result of Using MC_CHANGECART on Mado - Translation is something like "Cannot be used on Mado Gear")

![image](https://user-images.githubusercontent.com/62680611/82266903-5834ca00-9941-11ea-8b41-393fe881e942.png)
(Using MC_CARTDECORATE without a cart)

![image](https://user-images.githubusercontent.com/62680611/82266924-6682e600-9941-11ea-9e2c-58d8368e8cb0.png)
(When selecting the cart model, it gives me the cart even if i don't have cart)

  * Expected Result:

1. Mado should now be able to use MC_CHANGECART 
2. Should MC_CARTDECORATE give the user a cart? or just change the style of the users cart?

  * How to Reproduce: Just test the skills ingame 
  * Official Information: http://ro.gnjoy.com/news/notice/View.asp?BBSMode=10001&seq=7033 (some skills now can be used on Mado_ 
  

* **Modifications that may affect results**: As far as i know, none

**Comment by admkakaroto** [comment]
Use search tab: https://github.com/rathena/rathena/pull/3782

**Comment by LordWhiplash** [comment]
I've used, and found nothing about it...
This issue is not associated with statuses.
Even with flag AllowOnMado: true, MC_CHANGECART do not work on mado. And MC_CARTDECORATE should it really be usable without a cart?

**Comment by qwerty7vp** [comment]
> I've used, and found nothing about it...
> This issue is not associated with statuses.
> Even with flag AllowOnMado: true, MC_CHANGECART do not work on mado. And MC_CARTDECORATE should it really be usable without a cart?

That's normal behavior of this skill (Cart Decoration)
you can use it without a cart

**Comment by aleos89** [comment]
I didn't look too deep, but I think MC_CHANGECART's restriction is limited to the client itself. The difference between this skill and MC_CARTDECORATE is that MC_CARTDECORATE sends out a ZC_ packet while MC_CHANGECART doesn't. You'd have to try with a 2019+ client and see if there's a difference.

**Comment by qwerty7vp** [comment]
like @aleos89 said
I tried with 2020 Client
MC_CHANGECART can be use on Mado Gear

**Comment by aleos89** [comment]
I was able to confirm that you can't cast MC_CARTDECORATE without a cart.
