### ISSUE TITLE
Can not add Super Novice three new skills in the game

### ISSUE THREAD

**Issue by Surefirer** [rathena/rathena#4986]
* **rAthena Hash**: 

5d4fd1d3b

* **Client Date**: 
2018-08-31

* **Server Mode**:  Re

* **Description of Issue**:  not able to add three new skills, but the skill point still consumed. please see video: https://youtu.be/wZzwyPaldcM
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:  NO MODS, use kro client

**Comment by qwerty7vp** [comment]
duplicate of #4918

**Comment by Surefirer** [comment]
thanks, noted. I will close this issue.
