### ISSUE TITLE
pc_soulball_timer: timer not found

### ISSUE THREAD

**Issue by ecdarreola** [rathena/rathena#4992]
* **rAthena Hash**: 0fba10c

* **Client Date**: 20180621

* **Server Mode**: Renewal

* **Description of Issue**: Keeps appearing on console log
![image](https://user-images.githubusercontent.com/48939874/82519960-91de1e80-9b55-11ea-96e8-5311b01d7f0c.png)

  * Result: Lot of error messages with regards to pc_soulball_timer
  * Expected Result: Should not have
  * How to Reproduce: Use the skill that calls the pc_soulball_timer
  * Official Information:
  

* **Modifications that may affect results**: Serveral PR but it doesn't affect the code for it and particularly, this diff is applied. https://github.com/rathena/rathena/commit/6570489a84c554e2fba289de325d48a35d586996

**Comment by reunite-ro** [comment]
is it related with this https://github.com/rathena/rathena/issues/4907
