### ISSUE TITLE
NPC_DARKBREATH is not working

### ISSUE THREAD

**Issue by qwerty7vp** [rathena/rathena#4997]
* **rAthena Hash**: 46aa15a

* **Client Date**: 20180621RagexeRE, 20180919Ragexe

* **Server Mode**: Renewal

* **Description of Issue**: 
Im not sure if it because of #4982 or not
but I noticed today when I grinded at Big Bell. 
Normally I often see "9999" damage numbers (Dark Breath effect) when I'm grinding here but today I cant even see once. 
So I tested with mob that I edited it to have like 4 Lv.5 Dark Breath skills and I cant see the damage or effect of this skill

Testing Video : https://www.youtube.com/watch?v=zZ7hTpjeTkI

  * Result: Skill NPC_DARKBREATH is not working
  * Expected Result: Skill should work normally
  * How to Reproduce: `@monster` that has NPC_DARKBREATH skill and leave it attacking you (ex. 2621 2910 1198 1390 etc. )
  * Official Information:
  

* **Modifications that may affect results**: Nothing

**Comment by qwerty7vp** [comment]
I tried to revert back #4982 
and the skill working again

![image](https://user-images.githubusercontent.com/64515036/82662893-df8f7f80-9c58-11ea-99ba-b56846dfcc44.png)

so I think the problem came with #4982

**Comment by Daegaladh** [comment]
The skill has a 50% chance of damaging the character.
I just tested it and works as it should.

**Comment by qwerty7vp** [comment]
hmm is it normal that I stand there for almost 2 mins and take no damage from the skill ?
those mobs in my video have 4x of Dark Breath but I didnt take damage even once

**Comment by Daegaladh** [comment]
Sorry, you were right, there's a small bug that makes the chance 33,3% instead of 50%, I'll fix right now.

**Comment by aleos89** [comment]
The 9999 damage cap was removed. mrj didn't specify anything about a cap so I ended up removing it.

**Comment by qwerty7vp** [comment]
doesn't the "9999" is just a skill's effect ?
it has .act and .spr in data folder

![image](https://user-images.githubusercontent.com/64515036/82667470-233ab700-9c62-11ea-9886-86efe5d33386.png)

**Comment by Daegaladh** [comment]
Yeah, is just an effect, it has nothing to do with the real damage the skill does

**Comment by qwerty7vp** [comment]
so that's mean if the skill casted to player the 9999 effect should appear right?
I'm testing like 20 mins in total now 
I cant even see the "damage % of current hp" and "9999 effect" once


but when I revert commit 98f16b6 back from latest rA
Dark Breath real damage and 9999 effect appear in first 30 seconds

**Comment by qwerty7vp** [comment]
with Clean Latest rA :
https://youtu.be/A3n-6FBNBmk

with Clean Latest rA + revert back 98f16b6 :
https://youtu.be/mVmrIS_v3Qc

Both Renewal mode
Used same mobs : 2621
