### ISSUE TITLE
some Head gear Upper Equip with Head gear lower , Head Gear Lower disappear

### ISSUE THREAD

**Issue by Pringle012** [rathena/rathena#5001]
* **rAthena Hash**: Lastest

* **Client Date**: 2018-06-20

* **Server Mode**: Pre-Renewal

* **Description of Issue**: some Head gear Upper Equip with Head gear Lower , Head Gear Lower disappear
  * Result: 
![image](https://user-images.githubusercontent.com/50212919/82735799-a5080e80-9d4e-11ea-9161-bc34928bf241.png)
- In photo 2, the hat named Mob Scarf is added to the Caniv Star Hat2 hat and the Mob Scarf sprite disappears.
- But C Hat Can Aniv Star Hat2 can be paired with other hats. Example picture 4 5 6 7
  * Expected Result: I want to fix the Head Gear Lower Sprite display  Thx A lot

**Comment by qwerty7vp** [comment]
Properly your client-side problem

![image](https://user-images.githubusercontent.com/64515036/83395171-08b3cb00-a424-11ea-8f96-44dedcfa91be.png)

**Comment by aleos89** [comment]
`C_Aniv_Star_Hat2` is classified as an Upper Headgear - Costume while `Mob_Scarf` is a Lower Headgear. These don't have conflicting item locations so make sure your item_db is properly configured and your client data is valid.

You state you're using pre-renewal but these items don't exist in pre-renewal.
