### ISSUE TITLE
MVP Slave not aggro if MVP is not chassing you

### ISSUE THREAD

**Issue by poporing** [rathena/rathena#5003]
* **rAthena Hash**: d9f533165ea731a3b624d87b8bf95aa671b140fb

* **Client Date**:  2018-06-21aRagexeRE

* **Server Mode**:  pre-renewal & renewal

* **Description of Issue**:  Slave not aggro you if MVP is not chassing you
  * Expected Result: Slaves should chasse the player even if the mvp didn't
  * How to Reproduce: Just try to aggro the slave without the mvp
  * Official Information: in aegis 11.3 and 15.1 the slave direct chase you even if the mvp not
  

* **Modifications that may affect results**: no modification

**Comment by Michieru** [comment]
I confirm this in aegis 14.2

**Comment by Dalton-Jr** [comment]
Same issue on my side

**Comment by z0nx** [comment]
Same problem, Slaves are useless

**Comment by poporing** [comment]
this is how it works on official:
https://s7.gifyu.com/images/official.gif

how it's works on rathena
https://s7.gifyu.com/images/rathena.gif

has you can see slave not chassing if mvp not chassing in rathena, and in official slave can stay block and not tp back to mvp even if they didn't see you.

**Comment by Daegaladh** [comment]
I can confirm this, but not sure why it happens.
My `slaves_inherit_mode` is 4, so they should always have slave mode and act on their own.
However, they seem to freeze when their master cannot target you, they just stand there doing nothing, and don't attack or move.

**Comment by Daegaladh** [comment]
Seems to be the official behaviour :/
https://imgur.com/bayL8cw
