### ISSUE TITLE
Whikebain's Black Tail Curse Effect

### ISSUE THREAD

**Issue by reunite-ro** [rathena/rathena#5005]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/e6bffc11fe15f676873f4e4621e109a061732a17

* **Client Date**: Not related

* **Server Mode**: Renewal

* **Description of Issue**: Theres no information regarding curse effect, but in itemdb theres bonus script for it.
  * Result: Curse effect will occur since its included in the bonus script for 
  * Expected Result: I dont have much information about this, but from ratemyserver and from divine-pride theres nothing information regarding curse. But some databases given from divine-pride have information about transformation to Wild Rose.
  * How to Reproduce: use the item and try physical damage, etc.
  * Official Information:
https://rotool.gungho.jp/monster/item.php?item=2855
https://www.divine-pride.net/database/item/2855/whikebains-black-tail

  

* **Modifications that may affect results**: None

**Comment by LordWhiplash** [comment]
Hi, the Wild Rose transformation is from combo with "Nekomimi Beret" (https://www.divine-pride.net/database/item/18939/1)
But about the curse effect, I've found no info about that, so i believe It is not supposed to be in script
