### ISSUE TITLE
@pvpon something wrong

### ISSUE THREAD

**Issue by idk-whoami** [rathena/rathena#5007]
* **rAthena Hash**: e6bffc11fe15f676873f4e4621e109a061732a17

* **Client Date**: 20180919

* **Server Mode**: re

* **Description of Issue**: Use the @pvpon command and use the @reloadscript command. Causes to disable cammand @pvpon.
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by mazvi** [comment]
Its not bug i think.. if you want permanent pvp please use mapflag

**Comment by aleos89** [comment]
As @mazvi stated, `@reloadscript` recalculates mapflags. Any atcommand that adjusts a mapflag is temporary as the NPC define is treated as the default.
