### ISSUE TITLE
Bard & Dancer Skill AOE not showing

### ISSUE THREAD

**Issue by Ceelin** [rathena/rathena#5008]
* **rAthena Hash**: 

e6bffc11f

* **Client Date**: 
20180620

* **Server Mode**: 
RENEWAL

* **Description of Issue**: 
  * Result: Bard and Dancer Effects not showing. Data, .tga are all ok.(E.g Apples for Idun and Music Notes for Bragi)
  * Expected Result: Bragi and Dancer Effects should be visible upon casting until the duration is finished
  * How to Reproduce: 
  * Official Information:Client Files used was 20200420, updated via krolitepatcher. No modification, Client Exe Diff was all "Recommended", Data.Grf is ok.
  

* **Modifications that may affect results**: 
  
I downloaded as well a new copy and make it PRE_RENEWAL and everything is ok. Only in Renewal.
  
No modifications made. Its a new Download. Only the Connections Config has been edited.

**Comment by qwerty7vp** [comment]
in Renewal, Bard/Dancer skill has been update
its AoE became 31x31 and take out an old effect
and use these effect instead

![image](https://user-images.githubusercontent.com/64515036/82763156-c987e780-9e2f-11ea-893a-9d21a2b13f7f.png)

![image](https://user-images.githubusercontent.com/64515036/82763162-d3114f80-9e2f-11ea-9fa0-4170b3e46eb5.png)

btw you need to use newer hexed clients (2019+) to see these effect

**Comment by aleos89** [comment]
As @qwerty7vp stated, the skills have changed recently and the new effects require a 2019 or newer client.

**Comment by Ceelin** [comment]
Thank you for this Clarification. But rAthena strongly suggest to use the 2018-06-20 clients and below. Using 2019+ clients will result in "Unknown packet 0xacf" since the packet is not yet hardcoded. What will be the workaround for this one?

**Comment by attackjom** [comment]
https://github.com/rathena/rathena/pull/4944

2020 support is in progress.

**Comment by Ceelin** [comment]
Thank you again. Last question, if the 2020 support is in progress, is there a way we could use the old effects until such time the new effects are avaiable using the 2020 clients?

**Comment by aleos89** [comment]
You can use the old effects through just displaying them with `clif_specialeffect(bl, id of effect, AREA)`. But keep in mind this will not stick around if players leave and come back into the area.
