### ISSUE TITLE
Reverberation

### ISSUE THREAD

**Issue by juanfus** [rathena/rathena#501]
according to irowiki :
The sound wave can be attacked and destroyed by ranged or magic attacks and an unlimited number of Reverberations can be set on the ground at any one time.

currently only allowed to use 3 at same time.

**Comment by MrAntares** [comment]
Well even irowiki itself stated the 3 limit before. I wonder if this is an official change..

**Comment by juanfus** [comment]
here is a video made by ziu in kro about this

https://www.youtube.com/watch?v=OWIuYPoCOL4&feature=youtu.be
