### ISSUE TITLE
The killcount of achievements are not sharing among the party members

### ISSUE THREAD

**Issue by MccloudBR** [rathena/rathena#5018]
* **rAthena Hash**: 0e42b738c59be3330395e8c79c51500d534fcf55

* **Client Date**: 20180621

* **Server Mode**: Pré-Renewal

* **Description of Issue**: Killcount problem for Achievement Group "AG_BATTLE".
  * Result:  Regardless of being in a group, the killcount only goes to the one who gave the final blow.
  * Expected Result:  The killcount should be shared among the members of the group that are nearby ("AREA_SIZE")
  * How to Reproduce:  Create a group with another player, kill a monster that is on the list of achievements (eg: Naght Sieger), and you will see that the achievementupdate works only to the player who gave the final blow.
  * Official Information: N/A
  

* **Modifications that may affect results**: 
   None

**Comment by aleos89** [comment]
Do you have official information that party members help the kill count?

**Comment by MccloudBR** [comment]
I tried to find the information, but I believe it is not something that would not be explicit somewhere ...
Logically looking at the achievements of killing bosses in instances, which depend on a party to kill, it would be impossible for support players to be able to complete this group of achievement (AG_BATTLE).

I think the problem is in mob.cpp, in this line: 
"achievement_update_objective (sd, AG_BATTLE, 1, md-> mob_id);"

**Comment by MccloudBR** [comment]
It worked perfectly, congratulations for the work!
