### ISSUE TITLE
Repair weapon bug with Eggs.

### ISSUE THREAD

**Issue by DANILOFR1** [rathena/rathena#5024]
* **rAthena Hash**: 

* **Client Date**: 

 mostrar reccent

* **Server Mode**: 

 pre renewal

* **Description of Issue**: 
  * Result: 

using repair skill weapon of the blacksmith on someone with a pet is cloning the pet's egg of the person who had the item repaired. 

Lash version rathena on #general
  * Expected Result: 
  * How to Reproduce:  use repair weapon And select a Egg of other player instead a weapon. The egg Will clone.
  * Official Information: kro most recent
  

* **Modifications that may affect results**:

**Comment by LordWhiplash** [comment]
Hi, please, provide some info when you open an issue, this is the way to find out sollutions...
I've made some tests, and i could not reproduce this specific duplicating bug, but there's bugs around this Repair Weapon and pet interaction...
Hash: 0e42b73
Client Date: 20180621
Server Mode: Renewal

On my tests, some strange behaviours appeared, but could not clone eggs...
The bugs occours not only when repairing other caracters weapon, when using Weapon Repair on yourself too.
Strange Behaviors:
1 - Egg is appearing at repair list.
 ![image](https://user-images.githubusercontent.com/62680611/83223100-77f19c80-a150-11ea-86fa-b55104eb62d7.png)
(Weapon Repair on no weapon broken)

![image](https://user-images.githubusercontent.com/62680611/83223238-c56e0980-a150-11ea-80c9-64aed76deb76.png)
(Weapon Repair on character with broken weapon)

2 - Fixing the egg consume material, nothing happens with the pet itself and the weapon get not repaired, but the egg no more appears on list til re-summoned.
![image](https://user-images.githubusercontent.com/62680611/83223256-cdc64480-a150-11ea-8b40-0c7b20e8644a.png)
(Weapon Repair after repairing the egg)

**Comment by DANILOFR1** [comment]
> Hi, please, provide some info when you open an issue, this is the way to find out sollutions...
> I've made some tests, and i could not reproduce this specific duplicating bug, but there's bugs around this Repair Weapon and pet interaction...
> Hash: [0e42b73](https://github.com/rathena/rathena/commit/0e42b738c59be3330395e8c79c51500d534fcf55)
> Client Date: 20180621
> Server Mode: Renewal
> 
> On my tests, some strange behaviours appeared, but could not clone eggs...
> The bugs occours not only when repairing other caracters weapon, when using Weapon Repair on yourself too.
> Strange Behaviors:
> 1 - Egg is appearing at repair list.
> ![image](https://user-images.githubusercontent.com/62680611/83223100-77f19c80-a150-11ea-86fa-b55104eb62d7.png)
> (Weapon Repair on no weapon broken)
> 
> ![image](https://user-images.githubusercontent.com/62680611/83223238-c56e0980-a150-11ea-80c9-64aed76deb76.png)
> (Weapon Repair on character with broken weapon)
> 
> 2 - Fixing the egg consume material, nothing happens with the pet itself and the weapon get not repaired, but the egg no more appears on list til re-summoned.
> ![image](https://user-images.githubusercontent.com/62680611/83223256-cdc64480-a150-11ea-8b40-0c7b20e8644a.png)
> (Weapon Repair after repairing the egg)


235/5000
I forgot to mention that the cloning of the egg was taking place when all the characters were partying and with itern split enabled (the cloned egg went to anyone in the group, while the original owner continued with his pet)

**Comment by LordWhiplash** [comment]
Made some more tests, and even trying all combinations i've thought of (in party, each take/party share, individual/shared, with no party), and I could not reproduce the multiplication itself, what i've noticed is that if you try to Repair the egg, the egg appears on owner inventory, but do not duplicate, because if you get your pet back to egg, the pet just desappears, it do not generate another egg... About the translation of the client, you can look for bRO's archieves on data.grf and lua files

**Comment by DANILOFR1** [comment]
> Made some more tests, and even trying all combinations i've thought of (in party, each take/party share, individual/shared, with no party), and I could not reproduce the multiplication itself, what i've noticed is that if you try to Repair the egg, the egg appears on owner inventory, but do not duplicate, because if you get your pet back to egg, the pet just desappears, it do not generate another egg... About the translation of the client, you can look for bRO's archieves on data.grf and lua files

Thanks. what happens is that in a party, when you use repair the egg and the egg ends up going to the inventory of the eighth player with dropshare. egg doubles. The pet must be active, be repaired and the duplicate egg go to another party.

Ptbr- precisa estar em party, com dropshare e com o pet ativado. Aí usa reparar arma no egg do pet do outro jogador(pet esse que está ativo). O jogador continua com seu pet sumonado e um ovo pode ir clonado para o inventário de outra pessoa da party como se alguém tivesse pego no chão e fosse pro inventário de outro (dropshare)
