### ISSUE TITLE
Lux Anima Rune Effect dispellable?

### ISSUE THREAD

**Issue by Masao87** [rathena/rathena#5026]
* **rAthena Hash**: 

* **Client Date**: 20180621

* **Server Mode**: Renewal

* **Description of Issue**: I was wondering if there's any official information around the new Lux Anima Rune effect and if it's actually dispellable because currently it can get dispelled on the latest rA hash but since all other Runes can't be dispelled I was just wondering if Lux Anima is an exception or got forgotten?
  * Result: When using Lux Anima rune and oyu get dispelled by a mob or player all effects are being lost.
  * Expected Result: Should Lux Anima not be dispellable since all other Rune effects aren't either?
  * How to Reproduce: Use Lux Anima Rune and get dispelled.
  * Official Information: None found.
  

* **Modifications that may affect results**: None

**Comment by aleos89** [comment]
Getting 3 Gold is annoying on kRO, and that's if I succeed the first time. I guess if I find time to play a bit and grind to determine I can test this out.

**Comment by flamefury** [comment]
> Getting 3 Gold is annoying on kRO, and that's if I succeed the first time. I guess if I find time to play a bit and grind to determine I can test this out.

I haven't checked personally, but they should've implemented this guy in the bank of Lighthalzen:
https://ro.gnjoy.com/news/devnote/View.asp?seq=3981072

Which you can purchase Gold. You can get Zeny quickly in Sakray too and it's also possible that the necessary Rune Materials are sold by the many item merchants on Sakray.

**Comment by aleos89** [comment]
Confirmed that Lux Anima is not able to be Dispelled.
