### ISSUE TITLE
End script function

### ISSUE THREAD

**Issue by lelouch22** [rathena/rathena#503]
Im returning the old tracker issue posted by Emistry
https://rathena.org/board/tracker/issue-8012-player-in-shop-state-npc-script-able-to-move-and-execute-other-npc-script/

A little experiment....
the original src of end was this

BUILDIN_FUNC(end)
{
	TBL_PC* sd;

	sd = map_id2sd(st->rid);

	st->state = END;

	if( st->mes_active )
		st->mes_active = 0;

	if( sd )
		clif_scriptclose(sd, st->oid); // If a menu/select/prompt is active, close it.

	return SCRIPT_CMD_SUCCESS;
}

but i still can talk to other npcs when using callshop func so i did was try the old end func from eA...

BUILDIN_FUNC(end)
{
	st->state = END;
	return 0;
}

and voila!! its fixed :P well thats was a test. But you can look for a better solution for this issue besides i dont have enough knowledge about src -_-. Thank you :3.

**Comment by aleos89** [comment]
I'm thinking of adding a script command which can be ran at the start of the script to disable the SECURE_NPCTIMEOUT for that given script.

**Comment by anacondaqq** [comment]
Hi @aleos89, can you explain how this custom command should work?
Because i'm testing right now on rAthena with closeshop, and can't block players to move.

**Comment by anacondaqq** [comment]
okay, i was manually fix it. The problem about callshop related only for "end" script command.
For fast fix, we need to add a very stupid 
> sleep 1; 
before 
> end;
and all will works fine.

**Comment by icxbb-xx** [comment]
Try check in https://github.com/rathena/rathena/commit/8b3b32e0007255bd7cde1a936bd006cc7e66f7b7
