### ISSUE TITLE
Bard & Dancer Skills AOE effects not working

### ISSUE THREAD

**Issue by darking12345** [rathena/rathena#5030]
* **rAthena Hash**: 7507065

* **Client Date**: 2015-11-04aRagexe

* **Server Mode**: Pre-Renewal

* **Description of Issue**: whistle,assassin cross sunset,bragi,apple of Idun AOE support skills of Bard / Dancer does not work. As an example the Apple of Idun which should increase the max HP of players in the area. I already tried with and without a party. 
Caster stats are all 255.
  * Result: No changes on HP
  * Expected Result:  should increase the max HP of players in the area.
  * How to Reproduce: Try to cast whistle,assassin cross sunset,bragi,apple of Idun AOE supportive skill on the players near you
  * Official Information:
  
![image](https://user-images.githubusercontent.com/63349534/83350202-1e19ee00-a36d-11ea-9d0f-311d52676b1f.png)

* **Modifications that may affect results**: No src modification made

**Comment by hnomkeng** [comment]
How to fix ?

**Comment by mundussan** [comment]
> How to fix ?

Diff ur client exe to got that behaviour back.

**Comment by hnomkeng** [comment]
what patch no nemo ?

**Comment by mundussan** [comment]
> what patch no nemo ?

Restore Song Effects diff.

**Comment by hnomkeng** [comment]
Have effect and no status skill no work
