### ISSUE TITLE
Missing percentheal Rockridge Inn NPC.

### ISSUE THREAD

**Issue by Masao87** [rathena/rathena#5031]
* **rAthena Hash**: 

* **Client Date**: 

* **Server Mode**: Renewal

* **Description of Issue**: Rockridge Inn NPC is missing percentheal script command in the file npc\re\quests\quests_rockridge.txt line 5890 add percentheal 100,100; . I wish I had push privileges so I wouldn't need to file a bug report for such small things.
  * Result: When you use the Rockridge Inn NPC you pay the 5k zeny but won't get healed.
  * Expected Result: Get healed after using Inn NPC in Rockridge.
  * How to Reproduce: Use the Inn NPC in Rockridge to get healed.
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by llchrisll** [comment]
>  I wish I had push privileges so I wouldn't need to file a bug report for such small things.
Well if everybody had push privilges then who knows what happens to the emulator, like idiots pushing code destroying everything, I know you can revert stuff like that, but less work. Also every kind of info needs official confirmation.
But I guess the devs are happy if there are many who reports for such details even the smallest ones. That's my opinion tho. :)

**Comment by Lemongrass3110** [comment]
@Masao87 this is what pull requests are for.
You can submit it and we only have to check it and click a button so it can be merged into master. :-)

**Comment by Masao87** [comment]
> 
> 
> > I wish I had push privileges so I wouldn't need to file a bug report for such small things.
> 
> Well if everybody had push privilges then who knows what happens to the emulator, like idiots pushing code destroying everything, I know you can revert stuff like that, but less work. Also every kind of info needs official confirmation.
> But I guess the devs are happy if there are many who reports for such details even the smallest ones. That's my opinion tho. :)

Yeah I get that, ofc not everyone shuld jsut be able to push things into the master branch for obvious reasons. I meant more like I wish there was a way to apply for the priviliges to get them granted ;)

I have no issues reporting stuff, I just think it's a bit ridiculous for such minor things.

**Comment by Masao87** [comment]
> 
> 
> @Masao87 this is what pull requests are for.
> You can submit it and we only have to check it and click a button so it can be merged into master. :-)

Didn't think about that, thanks, I guess next time I'll just do that then, should work fine / the same way in the end ^^
