### ISSUE TITLE
Reverberation logic problem

### ISSUE THREAD

**Issue by LotusRO** [rathena/rathena#5037]
* **rAthena Hash**: 

* **Client Date**: 
20180621

* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result: 
Reverberation skill appears to be dividing its damage over 10 hits due to Skill_db.yml has it set to Multi_hit with -10, which i assume is a logic issue
  * Expected Result: 
Reverberation should hit 10 times for its damage, not 10 times for 10% of its damage each.
  * How to Reproduce: 
Just use Reverberation with the latest rAthena build.
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by attackjom** [comment]
Where did you get info ?

**Comment by LotusRO** [comment]
from kRO.

**Comment by qwerty7vp** [comment]
kRO Reverb's description at lv 5  : 마법 공격력 2200% 효과 범위 7x7셀
I dont think it's gonna be 2200% mATK per hit
Tested with hitcount: 10, Lv 175 Job 60 All stats 1, damage doesnt make sense

![qbevas](https://user-images.githubusercontent.com/64515036/83626042-16ea1e80-a5bf-11ea-9e60-aced0a4c9c2a.gif)

**Comment by LotusRO** [comment]
Damage makes no sense now either though, hence my  reporting of this but if you're sure theres no issue by all means close it, it just seems very strange right now.

**Comment by attackjom** [comment]
Test in KRO sakray level 1 : Reverberation 1000%matk split to 10 hit

![image](https://user-images.githubusercontent.com/35770095/83626453-a394dc80-a5bf-11ea-9f20-fe3adf96ca78.png)

**Comment by attackjom** [comment]
another pic

![image](https://user-images.githubusercontent.com/35770095/83626564-cd4e0380-a5bf-11ea-8319-f617f131f111.png)

**Comment by LotusRO** [comment]
its just people on our server were seeing their damage dropped by like 90% after this change, hence i drew the conclusion that it was wrong, i also briefly tested it on sakray but maybe i was wearing gear without thinking about it.

**Comment by attackjom** [comment]
Sure people in every server will complain this because this correction make theris DPS drop around 90%.

**Comment by LotusRO** [comment]
Well if its accurate and you're sure ill close the topic, thank you for the assist
