### ISSUE TITLE
Therapist

### ISSUE THREAD

**Issue by zeffen** [rathena/rathena#5043]
* **rAthena Hash**: afaee2f01ded99e37a277e59e520f24f5ebdd23c

* **Client Date**: 2018-11-07

* **Server Mode**: RE

* **Description of Issue**: When Doram talks to the Therapist and chooses the option to learn the First Aid skill, he receives EXP every time the dialogue takes place.
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Please report issues in English.

**Comment by aleos89** [comment]
This is because Doram can't learn First Aid, so the check for if the skill is learned fails resulting in the player being able to continually attempt to learn the skill.

If my memory serves me right, this whole area had a revamp again.
