### ISSUE TITLE
map_cache academy

### ISSUE THREAD

**Issue by zeffen** [rathena/rathena#5045]
* **rAthena Hash**: afaee2f01ded99e37a277e59e520f24f5ebdd23c

* **Client Date**: 2018-11-07

* **Server Mode**: RE

* **Description of Issue**: The map_cache of iz_ac01 and iz_ac02 needs to be updated according to kRO
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Please report issues in English.
