### ISSUE TITLE
Quick Draw Shot Cannot Be Used When ASPD 193

### ISSUE THREAD

**Issue by reunite-ro** [rathena/rathena#5046]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/d87ac219862dcacc7c5ade32e752cd401a6ea5d5

* **Client Date**: 20180620

* **Server Mode**: Renewal

* **Description of Issue**: Rebellion cannot use Quick Draw Shot when ASPD is 193 (In my case, 193 = max ASPD) even after Eternal Chain used.
  * Result: I have tried using ASPD 192 and Quick Draw Shot can be used, but when trying it with ASPD 193, Quick Draw Shot cannot be used anymore.
  * Expected Result: Quick Draw Shot can be used too except this is the official behaviour. 
  * How to Reproduce: Try to use Quick Draw Shot after Eternal Chain used during aspd 193 and also below 193.

**Comment by aleos89** [comment]
Intended behavior added in #4809. It was changed in kRO a couple years ago to block it: http://ro.gnjoy.com/news/notice/View.asp?BBSMode=10001&seq=6686&curpage=14

**Comment by flamefury** [comment]
Please re-open, the relevant line is being mistranslated:
- 스킬 "퀵 드로우 샷" 이 공격속도가 193 일때 발동되지 않던 현상이 수정됩니다.

Which translated means:
"Fixed an issue where the skill "Quick Draw Shot" did not activate at 193 APSD."

**Comment by reunite-ro** [comment]
Yeah I read it in Google Translate :

Skill "Quick Draw Shot" When the attack speed is 193, the phenomenon that was not activated will be corrected.

I think the patch corrected 'not activated' issue ?
