### ISSUE TITLE
Issue Countitem With Rentitem

### ISSUE THREAD

**Issue by reunite-ro** [rathena/rathena#5047]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/929c30c4143dc78cb85bc70d022113e75f62d0cc

* **Client Date**: 20180620

* **Server Mode**: Renewal

* **Description of Issue**: 
![image](https://user-images.githubusercontent.com/11705163/83821767-d3e49400-a701-11ea-865f-6301d249d405.png)

  * Result: Characters are having Seagod's Protection but NPC said it doesnt
  * Expected Result: NPC could check the items required and allow doors to be opened.
  * How to Reproduce:  I tried to use atcommand item 6436 and I can enter. So I cant reproduce this issue. The expiration date isnt end yet and items are still there in this issue (in picture).
`if (countitem(6436) == 0) {
		mes "[Missing, the Cleaner]";
		mes "You don't look like you have Seagod Protection. I can't open door at the moment!";
		close;
	}`

**Comment by reunite-ro** [comment]
I think it because of countitem for rentitem.

I didnt read it throughly yet, but from commit i think its from https://github.com/rathena/rathena/commit/7cc59c670822695833e9ac812cd5b46c9146eff2 or https://github.com/rathena/rathena/commit/b8ee97b6a15d453c6473bf898429ead14bb0a887

**Comment by aleos89** [comment]
Yes, this was a change to the countitem script command recently. Seems we need to add a new script command to count rental items for specific scripts.
