### ISSUE TITLE
Platinum Alter (rebellion)

### ISSUE THREAD

**Issue by juanfus** [rathena/rathena#505]
when Platinum Alter is active you cant active madness canceller(gunslinger skill) or heat barrel(rebellion skill)

**Comment by nanakiwurtz** [comment]
Are you sure you have enough Coins?

**Comment by juanfus** [comment]
yes

**Comment by aleos89** [comment]
Those skills aren't castable with each other. Ziu stated this here (http://forums.irowiki.org/showpost.php?p=1388802&postcount=981) but it doesn't say whether it produces a skill fail message or just cancels the status. Or it could be that this doesn't even happen anymore. If you have any newer info we can go off that.
