### ISSUE TITLE
Rolling Cutter not reseting when moving with Cross Impact

### ISSUE THREAD

**Issue by LordWhiplash** [rathena/rathena#5052]
* **rAthena Hash**: afaee2f

* **Client Date**: 20200401

* **Server Mode**: Renewal

* **Description of Issue**: Rolling Cutter counter is not reseting when moving with Cross Impact gap close.
  * Result: Rolling Cutter counter is not reseting when moving with Cross Impact gap close.
  * Expected Result: Reset Rolling Cutter counter when changing character position
  * How to Reproduce: Stack Rolling Cutter, use Cross Impact on nearby target, see the stacks are still there
  * Official Information: https://ro.gnjoy.com/news/devnote/View.asp?category=1&seq=3976053&curpage=1
  

![bandicam-2020-06-06-01-17-16-837](https://user-images.githubusercontent.com/62680611/83935874-0b9c1c00-a794-11ea-8635-cd932b517ce8.gif)

* **Modifications that may affect results**: None, afaik

**Comment by armpik1234** [comment]
can do this ? 
Should this skill miss, the Spin Count will remain

**Comment by armpik1234** [comment]
and this skill can do this ?  [ [Cross Ripper Slasher ] 
Should this skill miss, the Spin Count will remain.
how to do plz T_T
