### ISSUE TITLE
Grenade Launcher using Bullets instead of Grenade

### ISSUE THREAD

**Issue by qwerty7vp** [rathena/rathena#5054]
* **rAthena Hash**: d87ac21

* **Client Date**: 20200401

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Weapon type: Grenade Launcher can using Bullets to attacking but cant using Grenade ammo attacking
  * Expected Result: Not sure if my knowledge outdated or not but I think Grenade Launcher should can use only Grenade Bullets as ammo ?
  * How to Reproduce: 
- Equip Grenade Launcher (ID : 13162) with Bullets (ID : 13200) Then SHOOT!!
- Edit some of Grenade Bullets to be can equipping (by default item_db they cant be equipping)
- Equip Grenade Launcher with Grenade Bullets (ID : 13223) Then SHOOT!!

![bqeqq](https://user-images.githubusercontent.com/64515036/83943061-3bdecb80-a823-11ea-9af7-d2e026b4606f.gif)

  * Official Information:
  

* **Modifications that may affect results**: Edit some of Grenade Bullets to be can equipping (by default item_db they cant be equipping)
`13223,Flare_Sphere_,Flare Sphere,10,15,,5,50,,,,0x41000000,63,2,32768,,,,5,{ bonus bAtkEle,Ele_Fire; },{},{}`

**Comment by attackjom** [comment]
In KRO They are reworked ammo behavior by removing use of grenade bullet from shop.
now all gun just need bullet to shoot and old sphere are  us

These change is in commits.
https://github.com/rathena/rathena/commit/87032fc95a4cf82ef87d488f35e7af247cfe16ec

**Comment by qwerty7vp** [comment]
> In KRO They are reworked ammo behavior by removing use of grenade bullet and remove its from shop.
> now all gun just need bullet to shoot.
> 
> These change is in commits.
> [87032fc](https://github.com/rathena/rathena/commit/87032fc95a4cf82ef87d488f35e7af247cfe16ec)

Oh okay, thank you very much for info :)
