### ISSUE TITLE
delete_timer error : function mismatch 00E251C0

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#5058]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/8efd61f9b27dd5163d8f71f55f2025470f1254b3
* **Client Date**: 20200401
* **Server Mode**: RE
* **Description of Issue**: If you die while using the 'Rolling Cuter' skill, this error message is displayed on the map_server.
  * How to Reproduce: Whenever you die using the 'Rolling Cuter' skill, this message will appear on the map_server.

```
[Error]: delete_timer error : function mismatch 00E251C0(unknown timer function) != 00E8CE00(unknown timer function)
[Error]: delete_timer error : function mismatch 00E251C0(unknown timer function) != 00E8CE00(unknown timer function)
[Error]: delete_timer error : function mismatch 00E251C0(unknown timer function) != 00E8CE00(unknown timer function)
[Error]: delete_timer error : function mismatch 00E251C0(unknown timer function) != 00E8CE00(unknown timer function)
[Error]: delete_timer error : function mismatch 00EE6CD0(unit_walktoxy_timer) != 00E8CE00(unknown timer function)
[Error]: delete_timer error : function mismatch 00DAC6C0(npc_timerevent) != 00E8CE00(unknown timer function)
[Error]: delete_timer error : function mismatch 00EE6CD0(unit_walktoxy_timer) != 00E8CE00(unknown timer function)
[Error]: delete_timer error : function mismatch 00E251C0(unknown timer function) != 00E8CE00(unknown timer function)
```

**Comment by aleos89** [comment]
I'm unable to reproduce this. Are there any extra steps? Maybe a video would help.

**Comment by admkakaroto** [comment]
> I'm unable to reproduce this. Are there any extra steps? Maybe a video would help.

go to any map that has monsters or even pvp, put the 'Rolling Cross' skill on the hotkey, hold the hotkey button and wait for some monsters to kill you while you are using the skill.

**Comment by admkakaroto** [comment]
Here, test video: https://www.youtube.com/watch?v=SMBY-I7p-To

**Comment by qwerty7vp** [comment]
![asdqf](https://user-images.githubusercontent.com/64515036/84459469-baa78e80-ac91-11ea-964f-a473b583da60.gif)

I'm unable to reproduce this too

**Comment by admkakaroto** [comment]
This have no sense, i will redownload and test using a clean rA, just a min.

**Comment by admkakaroto** [comment]
Sorry guys, apparently the problem is here. I downloaded the rA clean, tested it 2 times and the problem didn't happen again, I apologize for the inconvenience.

**Comment by admkakaroto** [comment]
Look, I'm going to reopen the issue, I managed to make the problem appear in the RA clean, totally clean. After dying, use @alive and go to the top of the mvp again, hold the hotkey and keep turning until you die, the problem will happen.

**Comment by qwerty7vp** [comment]
![image](https://user-images.githubusercontent.com/64515036/84503146-d63b8500-ace3-11ea-9bd4-49492248368e.png)

now I can reproduce this
after few tried I found that
• it will happen only when "HOLD" Rolling Cutter hotkey "SPAM" it wont have an error
• need to "RELEASE" the holding hotkey while deadbody still turning

**Comment by blipblopblip** [comment]
I am still getting this error even I have #5206 in my git hash faadc800423fdde8720de3d9f176d76b11c31024

![image](https://user-images.githubusercontent.com/63345357/89123496-6044e480-d502-11ea-9dec-5925fc6531f0.png)

**Comment by admkakaroto** [comment]
It happens if you are holding the Hotkey after running out of SP, I already commented on PR about it.

**Comment by blipblopblip** [comment]
@admkakaroto did they come up with a fix?
