### ISSUE TITLE
Pet Egg Becomes RED when HATCHING

### ISSUE THREAD

**Issue by kekok435** [rathena/rathena#5059]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/ce42168b0d2d25f66ab8a5fc5e2ef24d988274ae

* **Client Date**: 20151104

* **Server Mode**:  PRE-RE

* **Description of Issue**: 
  * Result: Custom pets are successfully summoned via ``` `@hatch` ```/Pet Incubator but leave a broken pet egg in the inventory. Once you return your pet to egg, the egg will be back to normal. Meanwhile, official pets are working properly.
  * Expected Result: The custom pet's egg will be removed properly in the inventory once summoned.
  * How to Reproduce: I just summon the egg using ``` `@makegg/taming` ``` item and hatch it using ``` `@hatch` ```/pet incubator and it will leave a broken egg in the inventory.

  * Official Information: Officially, eggs should be removed in the inventory once the pet is summoned.

* **Modifications that may affect results**: We did not have any customization on pets

* **Additional Info**:  https://rathena.org/board/topic/122800-pet-egg-becomes-red-when-hatching/?do=findComment&comment=379883

**Item DB**
`64018,P_Woodie_Egg,Woodie Egg,7,20,,0,,,,,,,,,,,,,{},{},{}
64019,Woodie_Cookie,Woodie Cookie,0,20,,40,,,,,0xFFFFFFFF,7,2,,,,,,{ itemheal rand(25,35),0; },{},{}
64020,Woodie_Candy,Woodie Candy,2,2500,,50,,,,,0xFFFFFFFF,7,2,,,,,,{ pet 3556; },{},{}`

**Pet DB**
` - Mob: WOODIE
    TameItem: Woodie_Candy
    EggItem: P_Woodie_Egg
    FoodItem: Woodie_Cookie
    Fullness: 3
    IntimacyFed: 10
    CaptureRate: 2000
    SpecialPerformance: false
    AllowAutoFeed: true`

**Screenshot in-game:**
![image](https://user-images.githubusercontent.com/12641055/83971576-a4ef3d80-a90e-11ea-83ea-c100bb75bbf9.png)

**Additional notes:**

- Original pets does not have any problem, their eggs disappears every time I hatch them
- I used @makegg and @hatch command when summoning the pets
- I transferred the item ID to much lower number such such as 4000-6000 but no avail

**Comment by Daegaladh** [comment]
Have you tried using an ID in the range of 9000? I'm pretty sure the client only hides the eggs in that range.

**Comment by kekok435** [comment]
> Have you tried using an ID in the range of 9000? I'm pretty sure the client only hides the eggs in that range.

Yes! I tried also using the 9000 range, I even added the egg right after the last egg ID.

I also tried using the ID of one of the official eggs(isis egg to be exact), and it works perfectly.

**Comment by Lemongrass3110** [comment]
This happens when creating pets outside of the „official“ pet range. Client has hardcoded behavior.
