### ISSUE TITLE
Magnetic Field

### ISSUE THREAD

**Issue by limitro** [rathena/rathena#506]
![image](https://cloud.githubusercontent.com/assets/9300961/8602939/6698dc10-2675-11e5-9d69-53fb7f3ba2b2.png)

Hi. 
Tried this skill ingame, with a player in PvP room.
But, it does not do what the skill description says.

Any idea?

**Comment by anacondaqq** [comment]
rAthena Revision? 
What aren't the same? 
How does it work for you?

**Comment by limitro** [comment]
Hi there.
I use the latest rA rev.
The skill doesnt work.
It doesnt make the player which is inside mado to stop movement.... :(

**Comment by lelouch22** [comment]
I also got a latest rA github and its working fine.

**Comment by limitro** [comment]
Hi there.
Is this skill depending on enemies stats?

Because, I tried level 3, and it only lasted for like 2sec...
But, sometimes it works and sometimes it lasts only for 2 sec...

After the update.

Any idea?

**Comment by Playtester** [comment]
The skill lasts for 2+2*level seconds by default. There are some ending conditions for it however. For example if someone runs out of SP, if someone is hit by earth magic or is affected by Quagmire or if the person has Hover.
