### ISSUE TITLE
RoDEX 'Retriev all' function not working propertly

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#5061]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/8efd61f9b27dd5163d8f71f55f2025470f1254b3
* **Client Date**: 20200401
* **Server Mode**: RE
* **Description of Issue**: It is not possible to retrieve all items present in the rodex using the 'retrieve all' button.
  * How to Reproduce: Accumulate various rewards on the rodex, click on the 'retrieve all' button, you will not receive any items.

![123](https://user-images.githubusercontent.com/6227618/83977225-23c78480-a8d5-11ea-9e24-47bf25398995.png)

Now, relog in the game, open the rodex and press 'retrieve all' again, you will crash the game.
But when you login again the items will be in your inventory.

'Delete all' button its working!

**Comment by Balferian** [comment]
I have the same problem.

**Comment by voyfmyuh** [comment]
How to solve this problem? Or how to disable it?
