### ISSUE TITLE
Expanded Barter Shop

### ISSUE THREAD

**Issue by RagnaWay** [rathena/rathena#5062]
* **rAthena Hash**: 

https://github.com/rathena/rathena/commit/35c3301dda0f4f0c4628166faff24b072e0912e1

* **Client Date**: 

2020-06-03aRagexe

* **Server Mode**: 

Pre-Renewal / Renewal

* **Description of Issue**: 
Implement the new shop function for newer clients.

![image](https://user-images.githubusercontent.com/53480357/83983680-dcf28280-a906-11ea-8ebc-ec8af1dfec2c.png)
![image](https://user-images.githubusercontent.com/53480357/83983685-e24fcd00-a906-11ea-8d9b-43ddbea6a53b.png)

**Comment by Dieby** [comment]
Is there more information on how to implement this system?

**Comment by Dieby** [comment]
update please

**Comment by airei** [comment]
any update on this feature?

**Comment by JosueWu** [comment]
Hercules has this system.  rAthena is an outdated emulator with poor content.

**Comment by zdurexz** [comment]
any update on this feature?

**Comment by Benq28021997** [comment]
@Lemongrass3110 & @Atemo please Update
