### ISSUE TITLE
Monster spawn effecting instances

### ISSUE THREAD

**Issue by LotusRO** [rathena/rathena#5067]
* **rAthena Hash**: 

* **Client Date**: 

20180621

* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result: Increasing monster's per map in the conf file also effects Instances that uses certain commands to spawn monsters
  * Expected Result: Instances to be untouched by monster spawn settings for the server.
  * How to Reproduce: Increase Monster spawn and then go to ET / Old Glast Heim.
  * Official Information:
  

* **Modifications that may affect results**:  None as far as i know, we use standard ET and standard Old glast heim scripts from the rAthena package.

**Comment by Stingor** [comment]
hi you better check your scripts because their is no relation between mob_one_spawn dans mob_count_rate as far as i know

**Comment by aleos89** [comment]
As @Stingor stated, the `mob_count_rate` config does not affect temporary spawns, only permanently spawned monsters.

**Comment by LotusRO** [comment]
We're using the basic scripts from rAthena for Endless tower and Old Glast heim and upon setting Monster rate at 200 instead of 100, floors double spawn and become cluttered.

**Comment by qwerty7vp** [comment]
which rA Hash you're using ?
I tried `mob_count_rate: 200` 

![vasvq](https://user-images.githubusercontent.com/64515036/84049806-172b5500-a9d7-11ea-83c1-3f2c2844543d.gif)

as you can see in picture that `Hill Wind` became 260 instead of 130
then I started to kill 1 mob in 1st floor which has 36 -> 35
I killed them all the amount is correct and it's not doubled at all

**Comment by LotusRO** [comment]
Very strange, well thank you for checking this, ill close this now then, if the command itself is fine and the instances are fine..then i really have no idea why ours is acting that way, well thank you anyway :)
