### ISSUE TITLE
item_second_get_time are not working propertly

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#5074]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/8efd61f9b27dd5163d8f71f55f2025470f1254b3
* **Client Date**: 20200401
* **Server Mode**: RE
* **Description of Issue**: The sitting time in this setting is counting only 1 second.

Configs efecteds:
```
item_second_get_time
item_third_get_time
```
I haven't tested it in other configurations, but if you increase the time it works in small seconds.

**Comment by aleos89** [comment]
Could you explain the issue a little more in detail? So if you make the configuration 10 seconds, it doesn't work?

**Comment by admkakaroto** [comment]
Sorry just now I realized that the default time is set to 1 second in milliseconds. Which is very little, I think maybe the time will be much longer than that, but I will research it beforehand and then open a PR to solve it.

I will close the issue because I tested it with different time settings and it worked, I apologize for the inconvenience.
