### ISSUE TITLE
Homunculus HP/SP on Alt+R

### ISSUE THREAD

**Issue by LordWhiplash** [rathena/rathena#5078]
* **rAthena Hash**: 39fb658

* **Client Date**: 20200401

* **Server Mode**: Renewal

* **Description of Issue**: Wrong Homunculus HP/SP on Alt+R
  * Result: Alt+R shows an absurd HP/SP
  * Expected Result: Alt+R show the current/total HP/SP correctly
  * How to Reproduce: Create an homunculus (either by command or skill), check HP/SP on Alt+R

![image](https://user-images.githubusercontent.com/62680611/84342386-ce60d100-ab7b-11ea-94c3-ac44776abff8.png)

I've just noticed that the HP/SP of homunculus on interface is not showing correctly.
The HP/SP itselt seems calculated correctly, because in tests, the hp bar under the homunculus changed with low damage been recieved... I'm not sure if this strange error is happening with someone else, or even if it is related to the the emulator itself or to clientside, but found no info about that and decided to make this issue.

**Comment by LordWhiplash** [comment]
The things just became more strange, the actual value of HP/SP are changing each time I open Alt+R
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/62680611/84519508-95724a80-aca8-11ea-8c15-e1d29ca12b4a.gif)
i'm doing some tests on my clientside and will test on server backups to see when this error appeared...

**Comment by LordWhiplash** [comment]
Just downloaded clean rathena, and it is showing the same error, anyone else experiencing this? Thanks

**Comment by qwerty7vp** [comment]
I confirmed this
and it's happening with 20200401 client

![bqev](https://user-images.githubusercontent.com/64515036/84524543-583ba600-ad04-11ea-8191-e4927d58681a.gif)

20180919 client working fine

![image](https://user-images.githubusercontent.com/64515036/84524552-5bcf2d00-ad04-11ea-8f44-bb08cebd7321.png)

**Comment by Lemongrass3110** [comment]
This is a client side bug.
I just tested it with various clients and for me it was working on 2020-05-20bRagexe again. Did not try everything between 2020-04-20 and that one though.

**Comment by Dieby** [comment]
update please
