### ISSUE TITLE
HT_ANKLESNARE serious bug on Gvg mode

### ISSUE THREAD

**Issue by hnomkeng** [rathena/rathena#508]
watch : https://youtu.be/8LnVvk2NUl8
no stop on trap

**Comment by hnomkeng** [comment]
ex : https://rathena.org/board/tracker/issue-4832-hunter-ht-anklesnare-serious-bug/

**Comment by Zeloss** [comment]
Skill.conf "skill_trap_type", change it to 1 or 3. 

// Skill Trap Type
// On official servers if a unit is completely immune to knockback, it will still walk to the last target tile before
// stopping when inflicted by a stopping status effect (including traps like Ankle Snare and Spiderweb). All traps on
// the way will be activated.
// This does NOT include being immune to knock back from equip. This bonus only helps against knockback skills.
// 0: (official)
// 1: Stop effects in GvG/WoE make units stop immediately.
// 2: Stop effects make monsters immune to knockback / bosses stop immediately.
// 3: 1+2
skill_trap_type: 0
