### ISSUE TITLE
Can't open cash shop  [2020-01-08aRegexe]

### ISSUE THREAD

**Issue by Surefirer** [rathena/rathena#5086]
* **rAthena Hash**: 1932a8a95f7a195eb3f252ac5b2243c4a8e5eaa6

* **Client Date**: 2020-01-08aRegexe

* **Server Mode**:  Re

* **Description of Issue**: Can not open cash shop -> the icon on the top right
  * Result: 
  * Expected Result: 
  * How to Reproduce: diff a 2020-01-08aRagexe, then try to open cash shop
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Akkarinage** [comment]
Without further information I'm closing this as it's likely to be client-related and nothing to do with server code.
