### ISSUE TITLE
how to can't walk on npc callshop

### ISSUE THREAD

**Issue by idk-whoami** [rathena/rathena#5087]
* **rAthena Hash**: 5d1edeb80b4d966b4d7b22ab214e1473c85765f3

* **Client Date**: 20200401

* **Server Mode**: re

* **Description of Issue**: npc Tool Merchant#doram05t
https://github.com/rathena/rathena/blob/master/npc/re/custom/lasagna/lasagna_npcs.txt#L876-L993
callshop open shop to buy items. how to setting or fixed can't click walk
![บันทึก_2020_06_12_21_19_14_172](https://user-images.githubusercontent.com/60462533/84512614-700a2e80-acf2-11ea-9b8f-8880e69eac9e.gif)

  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment]
```
*pcblockmove <id>,<option>;
*unitblockmove <id>,<option>;

Prevents the given GID from moving when the option is 1, and enables the ID to
move again when the option is 0. This command will run for the attached unit
if the given GID is zero.

Examples:
	// Prevents the current char from moving away.
	pcblockmove getcharid(3),1;

	// Enables the current char to move again.
	pcblockmove getcharid(3),0;
```

**Comment by admkakaroto** [comment]
Lemon, there are some problems with this scriptcommand:

1st If you open a store like: itemshop, do not buy any item by clicking cancel, you are still blocked, there is no way to add the command script to release the character's movement.

2nd Even using pcblockmove, you can still click on several other npc's around you, you can even open kafra or any other interaction with another npc nearby or who can walk to it.
