### ISSUE TITLE
Shadow Chaser Shadow Form Isnt Cancelled With Detecting Skills

### ISSUE THREAD

**Issue by reunite-ro** [rathena/rathena#5089]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/45cd5808b7cb90f4549141d2f36fa1b20102dccf

* **Client Date**: 20180620

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Shadow Chaser Shadow Form Isnt Cancelled With Detecting Skills
  * Expected Result: Detecting Skills should cancelled Shadow Chaser Shadow Form. I didnt recheck yet if its shouldnt be cancelled anymore after rebalance/improvement patch.
  * How to Reproduce: Try to use Ruwatch or Sight, or any detecting skills.
  * Official Information: https://irowiki.org/wiki/Shadow_Formation or https://www.divine-pride.net/database/skill/2287/shadow-formation

**Comment by aleos89** [comment]
How were you testing? The comments for Shadow Form state it checks every 2 seconds.

**Comment by aleos89** [comment]
Just tested on a7d7e72 and it worked as it should.

**Comment by b055es** [comment]
Hi @aleos89 , [a7d7e72](https://github.com/rathena/rathena/commit/a7d7e72aa93ed12d070759409a318b108e975739) is for paramk mapflag?

**Comment by aleos89** [comment]
No, I was stating that version because it was "master" at the time of my testing.
