### ISSUE TITLE
Survivor's Circlet Item Database

### ISSUE THREAD

**Issue by reunite-ro** [rathena/rathena#5090]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/45cd5808b7cb90f4549141d2f36fa1b20102dccf

* **Client Date**: 20180620

* **Server Mode**: Renewal

* **Description of Issue**: I saw theres 2 Survivor's Circlet in Divine Pride, both have slot there but : 
 1. Item ID 19020 shown as 1 slot but 0 in rAthena itemdb.
 2. Item ID 19266 isnt exist in rAthena itemdb.
  * Result: ItemID 19020 didnt have slot=0 in rAthena itemdb and ItemID 19266 are not exist in rAthena itemdb.
  * Expected Result: ItemID 19020 should have slot and itemID 19266 should exist in itemdb if it should be. I didnt check throughly the item script fully since I didnt know which official information that should we prefer at high priority.
  * How to Reproduce: Try to slot 19020 and atcommand item 19266.
  * Official Information:
1. https://www.divine-pride.net/database/item/19020/survivors-circlet-1
2. https://www.divine-pride.net/database/item/19266/survivors-circlet-1

**Comment by LordWhiplash** [comment]
Taking a look at Divine Pride, i've noticed that 19020 is actualy a Japanese Version of Survivors Circlet, and 19266 is the Korean one... both effects are diferent, and combos too... and looking in the rAthena DB, the effect is currently a mix of both... to be more clear:


Japanese Survivor's Circlet [1] (19020)

Int + 3
Matk + 4%
If the user's base level is 99 or lower, additional Int + 1 per 2 upgrade levels of the item.
If the user's base level is 100 or higher, additional Int + 1 per 1 upgrade level of the item.

Combos:
Survivor's Rod
Matk + 10 per upgrade level of Survivor's Rod.
If Survivor's Rod upgrade level is +10 or higher,
Adds a chance of buffing the user for 5 seconds when performing a magical attack; Reduces the variable casting time of skills by 50%.

Survivor's Orb
Vit + 4
Reduces damage taken from Demi-Human race enemies by 4%.
Reduces the variable casting time of skills by 6%.
Increases the damage of Earth and Wind property magical attacks on targets by 20%.
If Survivor's Circlet [1] upgrade level is +7 or higher,
Additional Vit + 4
Reduces damage taken from Demi-Human race enemies by an additional 4%.
Reduces the variable casting time of skills by an additional 6%.
If Survivor's Circlet [1] upgrade level is +9 or higher,
Additional Vit + 4
Reduces damage taken from Demi-Human race enemies by an additional 4%.
Reduces the variable casting time of skills by an additional 6%.

Survivor's Shoes
Matk + 10%
If Survivor's Circlet [1] upgrade level is +7 or higher,
Increases the damage of Earth and Wind property magical attacks on targets by 10%.
If Survivor's Circlet [1] upgrade level is +9 or higher,
Increases the damage of Earth and Wind property magical attacks on targets by an additional 10%.

-----------------------------------------------------------------------------------

Korean Survivor's Circlet [1] (19020)

Int + 3.
Matk + 10 per 2 refine rate.
If refine rate is 10 or higher,Matk + 5%.
If base level is 130 or higher, Matk + 50. 

Combos:
Survivor's Rod
Matk + 10 per upgrade level of Survivor's Rod.

Survivor's Orb
Reduce aftercast delay as percent equal to refine rate of Survivor's Circlet.

Survivor's Manteau
Reduce variable casting time by 5% per 2 refine rate of garment.

-----------------------------------------------------------------------------------

rAthena Survivor's Circlet [0] (19020 - Same ID as Japanese)
Int + 3.
Matk + 4%.
Int + 1 per 2 upgrade levels of the item.
If the user's base level is 130 or higher, additional Int + 1 per 1 upgrade level of the item.

Combos:
Survivor's Rod
Matk + 1 per upgrade level of Survivor's Rod.
If Survivor's Rod upgrade level is +10 or higher,
Adds a chance of buffing the user for 5 seconds when performing a magical attack; Reduces the variable casting time of skills by 50%.

Survivor's Orb
Vit + 4
Reduces damage taken from Demi-Human race enemies by 4%.
Reduces the variable casting time of skills by 6%.
Increases the damage of Earth and Wind property magical attacks on targets by 20%.
If Survivor's Circlet [1] upgrade level is +7 or higher,
Additional Vit + 4
Reduces damage taken from Demi-Human race enemies by an additional 4%.
Reduces the variable casting time of skills by an additional 6%.
If Survivor's Circlet [1] upgrade level is +9 or higher,
Additional Vit + 4
Reduces damage taken from Demi-Human race enemies by an additional 4%.
Reduces the variable casting time of skills by an additional 6%.

Survivor's Shoes
Increases the damage of Earth and Wind property magical attacks on targets by 10%.
If Survivor's Circlet [1] upgrade level is +7 or higher,
Increases the damage of Earth and Wind property magical attacks on targets by an additional 10%.
If Survivor's Circlet [1] upgrade level is +9 or higher,
Increases the damage of Earth and Wind property magical attacks on targets by an additional 10%.

**Comment by reunite-ro** [comment]
yeah, so we're following which one ya ?

If im not mistaken, our priority in rAthena

kRO -> jRO -> and others right ?

**Comment by LordWhiplash** [comment]
i'll open a PR to fix the one we have and add the missing one on database, they do not share id, so, i think it is ok
