### ISSUE TITLE
KO_JYUMONJIKIRI 's AfterCastActDelay 500 was removed from KRO ?

### ISSUE THREAD

**Issue by Angelic234** [rathena/rathena#5092]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/5647c875d62bdf5be5429e43252e27a7c91b047f

* **Client Date**: 2020-04-01

* **Server Mode**: RE

* **Description of Issue**: 
  * Result: KO_JYUMONJIKIRI 's AfterCastActDelay  500 was removed from KRO ?
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  
According to http://www.inven.co.kr/board/ro/1950/4473 , can someone check it ?
* **Modifications that may affect results**:

**Comment by flamefury** [comment]
Did a quick check since I was in the midst of Ninja research anyway, and yes it's gone on kRO Sakray:
https://streamable.com/ax3lpw

I also did a confirmation of the cool downs via replay packet parsing.
