### ISSUE TITLE
Sarah Irene not considered MVP

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#5098]
* **rAthena Hash**: 9389b7d

* **Client Date**: 2018-02-21bRagexeRE

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: On the part where you need to take down Sarah (where Fenrir casts White Imprison on Sarah), it seems that Sarah becomes susceptible to skills that shouldn't affect her like Cursed Circle and Guillotine Cross Poison (particularly Leech End).
  * Expected Result: She should be considered MVP, despite the fact of handing out 0 MVP experience points.
  * How to Reproduce: Cast Poison Smoke with Leech End on top of Sarah. Cursed Circle was triggered by casting the spell beside Sarah.
  * Official Information: According to divine-pride (kRO) and iRO, she's considered a MVP.

* **Modifications that may affect results**:  none

**Comment by aleos89** [comment]
Maybe @Atemo can shed some light. I'm not familiar with much of the new content related to NPC.

**Comment by Atemo** [comment]
There is a mistake, the mob should be MD_MVP (immune to SC_COMA).
However, while doing the walkthrough on IRO, I noted it wasn't immune to some status (like leech end) so the mob didn't have MD_STATUS_IMMUNE. I can't tell if it was a mistake.
