### ISSUE TITLE
Greed Skill - Not picking up items

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#5099]
* **rAthena Hash**: 9389b7d

* **Client Date**: 2018-02-21bRagexeRE

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Using Greed doesn't pick up any items.
  * Expected Result: Should pick up items.
  * How to Reproduce: Use Greed while items are on the ground in close proximity.
  * Official Information: Picks up items.

* **Modifications that may affect results**:  none

**Comment by qwerty7vp** [comment]
look from your hash
you should update your rAthena
Im using 5647c87 and Greed working fine

**Comment by aleos89** [comment]
Tested on 5647c875d62bdf5be5429e43252e27a7c91b047f and I was unable to reproduce as well.

**Comment by Lemongrass3110** [comment]
Works perfectly fine, make sure you did not try it inside a town.
This is disabled in skill_nocast_db.txt by default.
You should get an appropriate failure message in this case though.
