### ISSUE TITLE
Crash: 553 Color Palette with client 2014-10-22 & feeding Poring Pet

### ISSUE THREAD

**Issue by OscarScorp** [rathena/rathena#510]
Forgive me if this isn't the right place to post this issue.

I have encountered 2 crash issues after using the new client 2014-10-22.

1.- Crash when changing color to the new Palettes, but this only happens on some classes such as Kagerou, Rebellion and when a Crusader changes its color while riding a Peco. Without a Peco there is no issue. ¿Does this means the Client does not supports some colors on the Palette? I am unable to select the 'Ignore Missing Palette Error' (Ignore Missing Palette Error: Failed in part 1). Using NEMO.
Crash happens to everyone looking at the user changing to that palette as well.

2.- When a user tries to feed a Poring pet, there's no problem. But if the Poring has a cute pet armor equipped (Backpack), the user's Client crashes.

I am thinking these issues only happen with the new Client, please correct me if I'm wrong.

Thanks in advance.

**Comment by nanakiwurtz** [comment]
For your question #1, please post it here --> https://github.com/MStr3am/NEMO/issues

Did you get any error message when your client crashed?
I don't know if newer clientside crash issues are related to incomplete packets on serverside or not.
:banana:

**Comment by OscarScorp** [comment]
No error message, just the Client crashes with the same ol' Windows pop-up message: 
"Ragnarok has stopped working"

**Comment by OscarScorp** [comment]
I'm sorry I meant that error happens with the Pet, but got fixed in another post which I lost the link... solution was to edit a line of text in come config.

The palette error is the following (korean characters won't let me paste it here since I can't find some of the characters): http://gyazo.com/4868981d25428562882e84a56d4dd680

I think I can solve the issue if I duplicate the folder inside palette/ , but I need to find the character which looks like an upwards arrow.

**Comment by aleos89** [comment]
Palette issues are client sided, not related to rA.
The pet issue you seemed to have fixed is also client sided if there's an issue with the msgstringtable file. I think you are referring to line 2579:
```Feeding the pet. %d '%s' remaining#```
Needs to be:
```Feeding the pet. '%s' (%d) remaining#```
