### ISSUE TITLE
Map server crash when mob cast SR_FLASHCOMBO

### ISSUE THREAD

**Issue by Hope8888** [rathena/rathena#5110]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/60d03a1978c2c2d8ebf5810582bfab69cb3392df

* **Client Date**: 20200401

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Map server crash when mob cast SR_FLASHCOMBO
  * Expected Result: No crash
  * How to Reproduce: 

1. **mob_skill_db.txt** added
`1015,Zombie@SR_FLASHCOMBO,any,5009,5,10000,0,5000,no,target,always,0,,,,,,,`

1. `@monster 1015`

1. Kill the mob before final combo

1. Map server crash.
![crash](https://user-images.githubusercontent.com/19237837/84732512-7dfbd000-afce-11ea-8a8a-da74f95bae94.png)

  * Official Information:

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
![image](https://user-images.githubusercontent.com/3521753/84773616-a5d93c80-afaa-11ea-948e-457e07c278b0.png)
I was unable to reproduce a crash.

Can you provide more details from the crash? Like the callstack and anything else to help.

**Comment by Hope8888** [comment]
[Flash Combo](https://irowiki.org/wiki/Flash_Combo)
1. Dragon Combo
--------------------> Crash when mob dead
2. Fallen Empire
--------------------> Crash when mob dead
3. Tiger Cannon
--------------------> Crash when mob dead
4. Sky Blow

![mapserver](https://user-images.githubusercontent.com/19237837/84781740-c391ba80-b019-11ea-9783-92cf7a0042a8.gif)

**Comment by sader1992** [comment]
My map-server does not crash , but I get an error in the map-server
![image](https://user-images.githubusercontent.com/5981261/84784679-e789d780-afea-11ea-8cd9-6eeefa6f63de.png)

**Comment by Hope8888** [comment]
@sader1992
Yeah, debug and release mode result is different.

**Debug** mode:
```
--- nullpo info --------------------------------------------
src\map\skill.cpp:4183: in func `skill_timerskill'
```
**Release** mode:
Map crash.

**Comment by aleos89** [comment]
This is because `src` is a nullptr. It's then attempting to assign `ud->skilltimerskill` to `skl` which is accessing a nullptr.

**Comment by mazvi** [comment]
I think my server freeze every day because this.. map server not crash but all char on map will freeze
