### ISSUE TITLE
KN_BOWLINGBASH no Damage

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#5113]
* **rAthena Hash**: 
* **Client Date**: 20200401
* **Server Mode**: RE
* **Description of Issue**: At times KN_BOWLINGBASH skill does no damage, but it pushes the monsters.
  * Result: KN_BOWLINGBASH Does not cause damage.
  * How to Reproduce: Well, just attack several monsters in different places, unfortunately I don't know exactly how to reproduce the problem, but you can check the video below as it happens.
  * Video: https://www.youtube.com/watch?v=7ewkcletVwE&feature=youtu.be

**Comment by qwerty7vp** [comment]
gutter line system ?
check skill.conf
look for `bowling_bash_area:`

**Comment by admkakaroto** [comment]
Well, i using official:

```
// Area of Bowling Bash chain reaction
// 0: Use official gutter line system
// 1: Gutter line system without demi gutter bug
// 2-20: Area around caster (2 = 5x5, 3 = 7x7, 4 = 9x9, ..., 20 = 41x41)
// Note: If you knock the target out of the area it will only be hit once and won't do splash damage
bowling_bash_area: 0
```

**Comment by qwerty7vp** [comment]
then it's normal that sometime
`KN_BOWLINGBASH skill does no damage, but it pushes the monsters.`
we called it gutter line system (you can google for info)
if you dont like it then change from 0 to other value

**Comment by admkakaroto** [comment]
yes I know, but I was very close to the monster, but that's okay, if it's correct, no problem.  thank you.
