### ISSUE TITLE
Can't set guild emblem

### ISSUE THREAD

**Issue by Masao87** [rathena/rathena#5114]
* **rAthena Hash**: Newest

* **Client Date**: 20200401

* **Server Mode**: Renewal

* **Description of Issue**: When I try to choose a guild emblem it will show the list of available emblems but when I click on them they won't load / show.
  * Result: When choosing a guild emblem they won't be loaded.
  * Expected Result: Choose a guild emblem from the list clicking the edit button in the guild window and show it ingame next to the character name.
  * How to Reproduce: Create a emblem folder, insert any standard emblem 24x24 256 colors .bmp
  * Official Information: https://write.ratemyserver.net/ragnoark-online-how-to/guild-emblem/ 
![screenLotusRO016](https://user-images.githubusercontent.com/4514182/84832127-fa250080-b02c-11ea-8121-64c8b952952f.jpg)
![screenLotusRO017](https://user-images.githubusercontent.com/4514182/84832128-fabd9700-b02c-11ea-8b70-84496de3fb1c.jpg)

  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
This isn’t dependent on rAthena anymore. It requires an external web service: https://github.com/rathena/rathena/pull/4944#issuecomment-628689633

**Comment by Masao87** [comment]
> 
> 
> This isn’t dependent on rAthena anymore. It requires an external web service: [#4944 (comment)](https://github.com/rathena/rathena/pull/4944#issuecomment-628689633)

Alright, thanks for the info 👍

**Comment by gravity-ro** [comment]
Can it be adjusted backward or not?
I mean before use web service.
