### ISSUE TITLE
[Issue] Rentitem not count in script Octopus Cave instance

### ISSUE THREAD

**Issue by edwardlucian** [rathena/rathena#5116]
* **rAthena Hash**: 

* **Client Date**: 20200304

* **Server Mode**: Renewal

* **Description of Issue**: 
   * Rentitem Octopus Hunting Skewer (6442) not count in script
 
[https://github.com/rathena/rathena/blob/master/npc/re/instances/OctopusCave.txt](https://github.com/rathena/rathena/blob/master/npc/re/instances/OctopusCave.txt)

![screenTweedy - RO009](https://user-images.githubusercontent.com/27148622/84859311-13fb2d80-b097-11ea-88da-4fca96fad6f7.jpg)

![screenTweedy - RO010](https://user-images.githubusercontent.com/27148622/84859317-165d8780-b097-11ea-88bd-ff2aa964595c.jpg)

* **Modifications that may affect results**:

**Comment by qwerty7vp** [comment]
#5080

**Comment by edwardlucian** [comment]
Thx
