### ISSUE TITLE
autoskill should work on skill issue?

### ISSUE THREAD

**Issue by reigneil** [rathena/rathena#512]
i dont know if someone notice this RE behavior but autoskill now works with skill.
best example would be Provoke Skill+Owl Baron Card Accesories=Lex Aeterna or
Double Strafe+Auto Blitz?=Blitz Beat

**Comment by aleos89** [comment]
I remember @cydh confirming something with this on AEGIS, but I can't remember where he posted it, or if he just told me in person.

**Comment by cydh** [comment]
I did for addeff is triggered by skill

**Comment by MrAntares** [comment]
So?

**Comment by Lemongrass3110** [comment]
I think this is already supported as of now(cf4e6495fe401d20ebe8e02fb94e4a48c2c67143):
```
bonus4 bAutoSpellOnSkill,sk,x,y,n;  	Adds a n/10% chance to autospell skill x at level y when using skill sk
bonus5 bAutoSpellOnSkill,sk,x,y,n,i;	Adds a n/10% chance to autospell skill x at level y when using skill sk
                                    	i provides additional options (bitfield):
                                    	  &1 = forces the skill to be casted on self, rather than on the target of skill sk
                                    	  &2 = random skill level in [1..y] is chosen
```

**Comment by reigneil** [comment]
@Lemongrass3110 
but what about those skill that is also trigger by using skills?
i.e http://irowiki.org/wiki/Gentle_Touch-Energy_Gain
