### ISSUE TITLE
Compilation show error ( make server )

### ISSUE THREAD

**Issue by gmchatterboy** [rathena/rathena#5121]
* **rAthena Hash**: dbe27fe510791e1082691415f0d13c065bb742ea

* **Client Date**: 20180620

* **Server Mode**: PRE-RE

* **Description of Issue**:  Problem occur after the GIT PULL
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**: No modification
  
  

`
[Info]: Start checking DB integrity
[SQL]: DB error - Unknown column 'hotkey_rowshift2' in 'field list'
[Debug]: at char.cpp:2304 - SELECT `char_id`,`account_id`,`char_num`,`name`,`class`,`base_level`,`job_level`,`base_exp`,`job_exp`,`zeny`,`str`,`agi`,`vit`,`int`,`dex`,`luk`,`max_hp`,`hp`,`max_sp`,`sp`,`status_point`,`skill_point`,`option`,`karma`,`manner`,`party_id`,`guild_id`,`pet_id`,`homun_id`,`elemental_id`,`hair`,`hair_color`,`clothes_color`,`weapon`,`shield`,`head_top`,`head_mid`,`head_bottom`,`robe`,`last_map`,`last_x`,`last_y`,`save_map`,`save_x`,`save_y`,`partner_id`,`online`,`father`,`mother`,`child`,`fame`,`rename`,`delete_date`,`moves`,`unban_time`,`font`,`sex`,`hotkey_rowshift`,`clan_id`,`last_login`,`title_id`,`show_equip`,`hotkey_rowshift2` FROM `char` LIMIT 1;
[Fatal Error]: char : A tables is missing in sql-server, please fix it, see (sql-files main.sql for structure)

make[1]: Entering directory '/home/broadmin/rathena/src/char'
        MKDIR   obj
        CXX     char_clif.cpp
char_clif.cpp: In function ‘int chclif_parse_charselect(int, char_session_data*, uint32)’:
char_clif.cpp:827:10: warning: ‘void* memcpy(void*, const void*, size_t)’ reading 20 bytes from a region of size 2 [-Wstringop-overflow=]
  827 |    memcpy(WFIFOP(fd, 4), "0", 20); // we can't send it empty (otherwise the list will pop up)
      |    ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
        CXX     char_cnslif.cpp
`

**Comment by Lemongrass3110** [comment]
This is not a support section.
Please try the forum or the discord channel.
