### ISSUE TITLE
Shape Shift Skill

### ISSUE THREAD

**Issue by ecdarreola** [rathena/rathena#5124]
* **rAthena Hash**: bac53cf

* **Client Date**: 20180621

* **Server Mode**: Renewal

* **Description of Issue**: Skill requirement always consumes Indigo_Pts no matter what the level is.
  * Result: Should only consume the proper requirement
  * Expected Result: Should only consume 3 pc of enchanted stone.
  * How to Reproduce: Use any level of shape shifter skill, notice it will require indigo item whatever level it is.
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by qwerty7vp** [comment]
+ it does not consume `Magic_Gear_Fuel`
