### ISSUE TITLE
Quest DB didn't count monster kill from custom monster

### ISSUE THREAD

**Issue by laziem** [rathena/rathena#5125]
* **rAthena Hash**:  80b7361
* **Client Date**: 2020
* **Server Mode**: RE
* **Description of Issue**: Quest db to kill monster didn't work with custom monster
  * Result: When do quest to kill monster (custom monster with mob_avail), the quest always refer to original monster
  * Expected Result: It should count the custom monster count instead the original monster
  * How to Reproduce: 

> Quest DB
  - Id: 100001
    Title: Kill 10 Custom Poring
    Targets:
      - Mob: JT_CUSTOM_PORING
        Count: 10

> MOB AVAIL
 - Mob: JT_CUSTOM_PORING
   Sprite: PORING

    * create custom quest db to kill custom monster (use the same sprite as PORING as example to mob_avail db)
    * When kill the custom monster, it didn't count. It only count when killing the original PORING
  * Official Information: -

* **Modifications that may affect results**: -

**Comment by aleos89** [comment]
This is coincidentally the same thing reported in #4434.
