### ISSUE TITLE
Fire Pillar Pre-re bug?

### ISSUE THREAD

**Issue by DANILOFR1** [rathena/rathena#5126]
* **rAthena Hash**: 

* **Client Date**: 
2018 06 20

* **Server Mode**: 
pre-re rathena

* **Description of Issue**: 
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**: 
  
  
![image](https://user-images.githubusercontent.com/41811741/85209420-2cc14880-b30e-11ea-8bfc-b08ecc409b61.png)

The player can use several in the same cell. This does not seem correct. How to fix? I think it has to do with sight blaster too.

**Comment by Kreustoo** [comment]
I checked and as I supposed it works as intended
![image](https://user-images.githubusercontent.com/14162419/85756656-4ea43c00-b70f-11ea-91d7-1a0635606958.png)
You surely made some modifications, try what Start_ says here:
https://rathena.org/board/topic/115694-make-fire-pillar-stack-on-1-cell-when-cast/
