### ISSUE TITLE
Can't relogin/login after last update

### ISSUE THREAD

**Issue by laziem** [rathena/rathena#5149]
* **rAthena Hash**: 940c22a6e
* **Client Date**: 20200318
* **Server Mode**: RE
* **Description of Issue**: 
  * Result: Failed to relogin and login
  * Expected Result: able to login and relogin
  * How to Reproduce: login a char, play few sec, then log out. Relogin with the same ID it will stuck (or try with many ID).
 Message on console
  `[Info]: Closed connection from 'xxx.xxx.xxx.xxx'`
 Sometimes able to go to Char selection, but after selecting the char, always `"Please wait"` until `"Failed to connect to server"` appear

  * Official Information: -

* **Modifications that may affect results**: -

**Comment by Lemongrass3110** [comment]
I am unable to reproduce this.

**Comment by laziem** [comment]
I just try again with fresh rAthena, and I can still trigger it. I try again by creating 2 char, then login them back and fort.

Sometimes it just show `"please wait"` after typing id/pass or select service/selecting char, sometimes when relogin shows`"server still recognize..."`

**Comment by qwerty7vp** [comment]
I cant reproduce this too

**Comment by laziem** [comment]
Sorry guys, looks like the problem are my internet connection. After I try with different ISP, all working normal.
