### ISSUE TITLE
WOE Controller Reward Issue

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#5155]
* **rAthena Hash**: 005a2c4

* **Client Date**: 20180620

* **Server Mode**: RENEWAL

* **Description of Issue**: 

use option 1 | 2 | 8 

  * Result:  Offline players also get prizes,
  * Expected Result:  offline players shouldn't get prizes, and duplicate IP players only get 1.
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Atemo** [comment]
```
//  [2] Mail all rewards.
//      - If not set, players receive items in their inventory.
//      - Only ONE item can be sent via mail for PACKETVER < 20150513 while later clients are limited to MAIL_MAX_ITEM (5).
//      - Note that offline players do NOT receive rewards.
```
The last line should be read
```
//      - If not set, note that offline players do NOT receive rewards.
```

>and duplicate IP players only get 1

It's not the behaviour ? `Members in a guild with the same IP address are not rewarded` = 1 reward per IP

**Comment by mazvi** [comment]
@Atemo sorry i wrong to write issue 

this is the issue and i was edit my post

  * Result:  Offline players also get prizes,
  * Expected Result:  offline players shouldn't get prizes, and duplicate IP players only get 1.

**Comment by Atemo** [comment]
`Offline players also get prizes` it was expected.
However I will suggest an new option

**Comment by mazvi** [comment]
This is new issue on latest woe update. If using option 1 2 8 16 if online player on teleport or warp loading screen this player not get reward
