### ISSUE TITLE
Random Char-Server Crash/Segmentation Fault

### ISSUE THREAD

**Issue by blipblopblip** [rathena/rathena#5156]
* **rAthena Hash**:  https://github.com/rathena/rathena/commit/ce42168b0d2d25f66ab8a5fc5e2ef24d988274ae

* **Client Date**: 20151104aRagexe

* **Server Mode**: Pre-Renewal

* **Description of Issue**: 
  * Result:  Segmentation Fault in Char-Server
  * Expected Result:  None
  * How to Reproduce:  Have no idea as well how did it happened
  * Official Information: None
  

* **Modifications that may affect results**: 
  
  
As far as I remember I didn't edited any stuff related to my char-server

See the crash dump generated from my GDB [here](https://pastebin.com/xSuipkNN)

**Comment by aleos89** [comment]
I can tell you have some sort of BG Mod installed from the data being dumped. You will need to convene with the developer of that mod and present them with this data.

**Comment by blipblopblip** [comment]
The sad part is, the developer of this isn't responding anymore </3
