### ISSUE TITLE
Setunitdata only work partially

### ISSUE THREAD

**Issue by nanakiwurtz** [rathena/rathena#516]
Git Commit: fcf7a939
Client Date: 2013-08-07, Renewal

Hi, I made a simple script to test the setunitdata command.
```
prontera,153,153,3	script	setunitdata	62,{
	monster("prontera", 153, 153, "My Mob", 1031, 1, strnpcinfo(1)+"::OnUnit");
	.@gid = $@mobid[0];
	getunitdata .@gid,.@before;
	
	setunitdata .@gid,0,2;		// Size
	setunitdata .@gid,1,11;		// Level
	setunitdata .@gid,2,12;		// HP
	setunitdata .@gid,3,513;	// Max HP
	setunitdata .@gid,8,123;	// Speed
	setunitdata .@gid,24,11;	// Agi
	setunitdata .@gid,25,22;	// Vit
	setunitdata .@gid,26,33;	// Int
	setunitdata .@gid,27,44;	// Dex
	
	getunitdata .@gid,.@after;
	dispbottom "Before: "+.@before[0]+","+.@before[1]+","+.@before[2]+","+.@before[3]+","+.@before[8]+","+.@before[24]+","+.@before[25]+","+.@before[26]+","+.@before[27];
	dispbottom "After: "+.@after[0]+","+.@after[1]+","+.@after[2]+","+.@after[3]+","+.@after[8]+","+.@after[24]+","+.@after[25]+","+.@after[26]+","+.@after[27];
	sleep2 5000;
	unitkill .@gid;
	end;
}
```
I noticed 2 problems:
1. Not all data are updated.
2. Setunitdata type 3 doesn't accept value <= 512, it will just kill the monster and returns 0 on all value in the above script. If you use value > 512, it will be fine. It will show the following messages on mapserv:
Debug]: Source (NPC): setunitdata at prontera (153,153)
[Warning]: buildin_getunitdata: Error in finding object with given game ID xxxxxx!
[Error]: Memory manager: freed-data is changed. (freed in (folder path)\src\map\map.c line 214)
Thanks! :banana:

**Comment by pengc2010** [comment]
I have the same problem in mob part, the reason is "status_calc_bl" function will extract the base status from mobdb an calculate everything based on the base_status.
To temporarily solve this, you can just call the calc functions (e.g., status_calc_misc for hit flee and other things), and use &md->status as the input.

**Comment by cydh** [comment]
I know this will happen when on implementation

**Comment by julia40124009** [comment]
confirm ..

**Comment by cydh** [comment]
I was planning to move setunitdata param to an array. so calculation can be one once.
````
.@data = callfunc("F_InitUnitData"); // Init unit data, actually I want uninit value as NULL, but since 'NULL' is not a value in scripting, so the function will set all data as -1.
.@data[UD_STR] = 120;
.@data[UD_AGI] = 180;
.@data[UD_VIT] = 80;
.@data[UD_INT] = 10;
.@data[UD_DEX] = 200;
.@data[UD_LUK] = 140;
setunitdata <GID>,.@data;
````

**Comment by aleos89** [comment]
The reason the stats don't stick is because of the status_calc_bl() call. It removes the stat we changed because it's pulling from base_status.
The call was originally there to update the ATK, MATK, etc for the BL objects.

I'll go back and try to clean this up more.
