### ISSUE TITLE
Guild Emblem

### ISSUE THREAD

**Issue by ecdarreola** [rathena/rathena#5161]
* **rAthena Hash**: d38d2b6

* **Client Date**: 2020-04-01Ragexe

* **Server Mode**: Renewal

* **Description of Issue**: Emblem doesn't appear
  * Result: Via wireshark, POST download is OK/successful however it is not appearing on client.
  * Expected Result: Should appear.
  * How to Reproduce: 
1. Install this https://github.com/secretdataz/athena-web-service
2. Configure
3. Upload Emblem
4. Problem is shown
  * Official Information: None
  

* **Modifications that may affect results**: None
  
  

**Other information**:
- Using RE client such as "**2020-03-04aRagexeRE**", the emblem appears. So I assume it will work on RE clients only (or maybe not) since I haven't tried all client.

**Comment by cahya1992** [comment]
confirm this issue the emblem not showing but webservice said its succed
![Screenshot_449](https://user-images.githubusercontent.com/8091082/87208618-5a137c00-c339-11ea-9b6d-82ca29548bc5.png)

**Comment by secretdataz** [comment]
I tested the emblem implementation using the information I collected from kRO Sakray in June. So we need to capture packets from kRO main.

**Comment by admkakaroto** [comment]
@ecdarreola can other players see the guild emblem? for me only the guild leader can see the emblem of his guild, other players cannot.
![unknown](https://user-images.githubusercontent.com/6227618/88493403-472eb780-cf87-11ea-994e-7bf96081cf8c.png)

**Comment by attackjom** [comment]
Try this.

app -> http -> middle -> ragnarokauthmiddleware.php

`//if (!AuthTokenVerifier::verify($aid, $token, $gid)) {
      //      return response(config('athena.error_response'), 401);
      //  } else {
            $request->account_id = $aid;
            $request->guild_id = $gid;
            $request->auth_token = $token;
            $request->world_name = $world;
            return $next($request);
      //}`

**Comment by admkakaroto** [comment]
> AuthTokenVerifier


> Try this.
> 
> app -> http -> middle -> ragnarokauthmiddleware.php
> 
> //if (!AuthTokenVerifier::verify($aid, $token, $gid)) {
> // return response(config('athena.error_response'), 401);
> // } else {
> $request->account_id = $aid;
> $request->guild_id = $gid;
> $request->auth_token = $token;
> $request->world_name = $world;
> return $next($request);
> //}

wow, now worked.

**Comment by Lemongrass3110** [comment]
This was not really an rAthena issue - as expected.

Nevertheless it was fixed in secretdataz/athena-web-service@b2e5b96
