### ISSUE TITLE
Add quest objectives (race / size / element / min~max levels)

### ISSUE THREAD

**Issue by Balferian** [rathena/rathena#5162]
* **rAthena Hash**: fb00561
* **Client Date**: 2015-05-13+
* **Server Mode**: -

* **Description of Issue**: 
  * Result: Some new quests in episodes use hunting quests to (race / size / element / min~max levels) monster.
For example 16.1:
https://github.com/rathena/rathena/blob/fb00561fc16f216ceea26b99cc0af618bc58bc77/npc/re/quests/quests_16_1.txt#L8561
  * Expected Result: add new objectives for quest_db like (race / size / element / min~max levels) for hunting quests.
iDathena: https://github.com/idathena/trunk/commit/b67c688e791d303a1dfe949bf0bd2b00b7b332ad#diff-f3653b71c45029581a98314726e4d8f5
  * How to Reproduce: 

* **Modifications that may affect results**:

**Comment by Latiosu** [comment]
@Balferian Do you know if there are scenarios where multiple of type race/element/size are used in a quest?
For example, a quest that requires 50 monsters of either race "Demon" or race "Demi-Human".

**Comment by Atemo** [comment]
Fixed in https://github.com/rathena/rathena/commit/5ba29be2a31a4a60c7be61aba3a6050119eb4b14
