### ISSUE TITLE
When langtype is set to 4, user_pass will be recorded as garbled!

### ISSUE THREAD

**Issue by voyfmyuh** [rathena/rathena#5163]
* rAthena Hash: https://github.com/rathena/rathena/commit/fb00561fc16f216ceea26b99cc0af618bc58bc77

* Client Date: 20200401

* Server Mode: Renewal

* Description of Issue: 
When langtype is set to 4 and M F is used to create an account, user_pass record is garbled

![82272308-cbbff100-99ac-11ea-8625-1e1ecb049806](https://user-images.githubusercontent.com/54499336/86203885-aff95e80-bb98-11ea-82d1-7a10da4a2a50.png)

![82272296-c498e300-99ac-11ea-9713-2b20c4c43030](https://user-images.githubusercontent.com/54499336/86168112-45213680-bb4a-11ea-9a3d-b3bc863e7a7e.png)

**Comment by bgamez23** [comment]
try to add on your clientinfo.xml
<passwordencrypt> or <passwordencrypt2 />?

**Comment by Lemongrass3110** [comment]
This is what the client sends - not a server side problem.

**Comment by wildskyf** [comment]
@voyfmyuh I face the same problem as you did, do you solve it?
