### ISSUE TITLE
itemshop not work related item_trade_db

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#5168]
* **rAthena Hash**: 9d70b7c35fc2737b44d6494741c8e67577e480d7

* **Client Date**: 20180620

* **Server Mode**: RENEWAL

* **Description of Issue**: itemshop not work related item_trade_db
  * Result:  use the itemcash in item_trade as an example, 64214,475,100 so it can't be used. only items not listed in item_trade can be used.
  * Expected Result:  The item should be used as an itemcash even if it is listed on item_trade
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by secretdataz** [comment]
Use allow_bound_sell battle config

**Comment by mazvi** [comment]
Ahaha thx very much
