### ISSUE TITLE
Hotkey Bar

### ISSUE THREAD

**Issue by ecdarreola** [rathena/rathena#5169]
* **rAthena Hash**: 9d70b7c

* **Client Date**: 2020-04-01 or 2020-03-04

* **Server Mode**: Renewal

* **Description of Issue**: Skill generated from items (e.g. Greed Clip) remains even if you removed it from your equipment. 
  * Result: The skill will not be usable but the skill icon still there.
  * Expected Result: Based from the old clients, if the skill icon on hotkey bar will disappear if you unequip the item that has it.
  * How to Reproduce: @item 2829 (greed_clip) -> equip item -> move skill to hotkey bar -> remove item.
  * Official Information: N/A
  

* **Modifications that may affect results**:  None

**Comment by admkakaroto** [comment]
To summarize, the skill bar is not being refreshed,

**Comment by secretdataz** [comment]
The same happens on iRO. Could be a client issue.

**Comment by ecdarreola** [comment]
> The same happens on iRO. Could be a client issue.
> https://youtu.be/lwe-iLMmZzg

Oh nice. So this could be invalid then.
