### ISSUE TITLE
Weapon Damage behaviour

### ISSUE THREAD

**Issue by LotusRO** [rathena/rathena#5170]
* **rAthena Hash**: 

* **Client Date**: 

18/06/21

* **Server Mode**: 

Renewal

* **Description of Issue**: 

Basically since the last update from rAthena, it seems weapon damage formulas for crimson weapons are acting very strange, their damage is either calculated wrongly or something else is going on, it seems to be basically only crimson weapons though.

* **Modifications that may affect results**: 
None that comes to mind since this happend from the last pull we did ( we pull once every week / two weeks )

**Comment by aleos89** [comment]
Possibly related to 5112f8e2d8a6eca1df88d1700de61f07e93de6f2?

**Comment by LotusRO** [comment]
> 
> 
> Possibly related to [5112f8e](https://github.com/rathena/rathena/commit/5112f8e2d8a6eca1df88d1700de61f07e93de6f2)?

so does this mean it was wrong before or is it wrong now?, because crimson weapons feel incredibly bad at this point, we ran some tests and something is very wrong in terms of upgraded ones.

**Comment by aleos89** [comment]
You could try reverting that change and let me know. I don't recall how Crimson weapons work without diving back into that code.

**Comment by SeravySensei** [comment]
https://github.com/rathena/rathena/commit/5112f8e2d8a6eca1df88d1700de61f07e93de6f2 affects damage calculation of skills deal a constant damage that doesn't depend on atk - only those 6 skills are affected.

Looked at the script on crimson weapons and it's basically no different from an Andre card, it's just a simple base atk bonus.

**Comment by Atemo** [comment]
Please update your revision to https://github.com/rathena/rathena/commit/b2afc2ea6e90579d963a8245e754ee6ab3802cd5
