### ISSUE TITLE
Specific Accessory Card Cannot Equipped

### ISSUE THREAD

**Issue by reunite-ro** [rathena/rathena#5174]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/2a37f687d334615d451c48ed2efc2a996fd4cd08

* **Client Date**: 20180620

* **Server Mode**: Renewal

* **Description of Issue**: Specific Accessory Card Cannot Equipped. 
  * Result: For example Gigantes Card [Accessory]   Item ID# 27183 (Gigantes_Card) cannot being equipped.  
  * Expected Result: Gigantes Card [Accessory]   Item ID# 27183 (Gigantes_Card) can be equipped.
  * How to Reproduce: Try to equip Gigantes Card

* **Modifications that may affect results**: I think its from previous commit for card accessory insertion.

**Comment by LotusRO** [comment]
This happend to us as well, we solved this by basically just turning it into Accessory slot for equipment instead of a specific slot, i guess they removed this by now or its a bug

**Comment by Haydrich** [comment]
it works only with item have the same Position "Accessory (Left)" , like @i`tem 28565

**Comment by reunite-ro** [comment]
> it works only with item have the same Position "Accessory (Left)" , like @i`tem 28565

Ive tried using 28565 and yes it works. 

Is it should be work right this from now on/officially ?

**Comment by Haydrich** [comment]
> > it works only with item have the same Position "Accessory (Left)" , like @i`tem 28565
> 
> Ive tried using 28565 and yes it works.
> 
> Is it should be work right this from now on/officially ?

i dont have more info about this.

**Comment by attackjom** [comment]
Yes this is official behavior in Kro 

You can’t insert specific-acc card to normal acc.

**Comment by Lemongrass3110** [comment]
Working as intended.
