### ISSUE TITLE
Latest rAthena crash signal map-server (With GDB)

### ISSUE THREAD

**Issue by MuzTank** [rathena/rathena#5179]
* **rAthena Hash**: 7d3064c

* **Client Date**: 20180620

* **Server Mode**: Pre-Renewal

* **Description of Issue**: 
  * Result: 
  * Expected Result: 
  * How to Reproduce:  Don't know how to reproduce
  * Official Information:
  

* **Modifications that may affect results**: 
  
  
Program received signal SIGSEGV, Segmentation fault.
0x0000000000657bcb in safestrncpy(char*, char const*, unsigned long) [clone .part.5] ()
Missing separate debuginfos, use: debuginfo-install MariaDB-shared-10.1.44-1.el7.centos.x86_64 glibc-2.17-292.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-19.el7.x86_64 libcom_err-1.42.9-12.el7_5.x86_64 libgcc-4.8.5-28.el7_5.1.x86_64 libselinux-2.5-12.el7.x86_64 libstdc++-4.8.5-28.el7_5.1.x86_64 openssl-libs-1.0.2k-12.el7.x86_64 pcre-8.32-17.el7.x86_64 zlib-1.2.7-18.el7.x86_64
(gdb) bt full
#0  0x0000000000657bcb in safestrncpy(char*, char const*, unsigned long) [clone .part.5] ()
No symbol table info available.
#1  0x000000000066733e in safestrncpy(char*, char const*, unsigned long) ()
No symbol table info available.
#2  0x000000000049c188 in clif_name (src=src@entry=0x6b1e090, bl=bl@entry=0x6b1e090, target=target@entry=AREA) at clif.cpp:9709
        packet = {packet_id = 2608, gid = 2001102, name = "Mbuh", '\000' <repeats 19 times>, party_name = '\000' <repeats 23 times>, guild_name = '\000' <repeats 23 times>, position_name = '\000' <repeats 23 times>, title_id = 0}
        sd = 0x6b1e090
        p = 0x256d8
#3  0x0000000000509d90 in party_member_withdraw (party_id=<optimized out>, account_id=<optimized out>, char_id=153304, name=0x60cdfae "Mbuh", type=PARTY_MEMBER_WITHDRAW_LEAVE) at party.cpp:674
        idxlist = {1, 0, -8648, 32767, 0, 0, 0, 0, 0, 0, 48, 48, -8424, 32767, -8624, 32767, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5292787, 0, 0, 4, 1, 167, 13040656, 0, 344, 6, 0, 1, 5, 163, 164, 165, 166, 167, 75, 0, 5051013, 0, 0, 0, 0, 0,
          0, 0, 5049509, 0, 0, 0, 12, 44, -297673604, 32767, 44, -256, 65537, -1, 0, 0, 44, 33, 37, 297, 4852496, 0, 16777216, 343, 629, 0, 0, 0, 0, 0, 629, 0, 0, 0, 0, 0, 0, 0, -467306380, 32767, 86697048, 0, 6690725, 0, -467306348,
          32767, -467306380, 32767}
        i = <optimized out>
        sd = 0x6b1e090
        p = 0x7fffe4916ffc
#4  0x00000000004c2220 in intif_parse_PartyMemberWithdraw (fd=11) at intif.cpp:1603
No locals.
#5  0x00000000004c6c62 in intif_parse (fd=fd@entry=11) at intif.cpp:3767
        packet_len = 39
        cmd = <optimized out>
#6  0x000000000046aa6f in chrif_parse (fd=11) at chrif.cpp:1789
        r = <optimized out>
        cmd = 14372
        packet_len = <optimized out>
#7  0x000000000040d3c5 in main ()
No symbol table info available.

**Comment by MuzTank** [comment]
anyone know what's with that?

**Comment by MuzTank** [comment]
I temporarily fixed by turned off these lines
![image](https://user-images.githubusercontent.com/8184152/86506359-e208fb80-bdf8-11ea-87a0-2fe8c767e749.png)

**Comment by mazvi** [comment]
Yes i also have crash issue on renewal

i update from 9d70b7c until 7d3064c

[Error]: Server received crash signal! Attempting to save all online characters!

i dont know where error come from

but crashes occur when map-servers load autotrade vending.

**Comment by ecdarreola** [comment]
Unable to reproduce.

How many autotrade vending were you loading?
Does the autotrader have a guild and party?

**Comment by MuzTank** [comment]
7 autotraders, it was happened when maintenance time. So not other online players. When I kicked the player or clicked the vending balloon, it crashed. However if using @kickall, it doesnt error.
For the guild or party, that particular vendor doesnt have it, or maybe didnt show due to /showname

**Comment by ecdarreola** [comment]
> 7 autotraders, it was happened when maintenance time. So not other online players. When I kicked the player or clicked the vending balloon, it crashed. However if using @kickall, it doesnt error.
> For the guild or party, that particular vendor doesnt have it, or maybe didnt show due to /showname

Still unable to reproduce. I used both /showname and use @kick player or click vending balloon no crash generated.

**Comment by MuzTank** [comment]
That's why I wrote dont know how to reproduce... because I dont know yet how to 100% reproduce it
