### ISSUE TITLE
Player normal attack non-elemental/neutral?

### ISSUE THREAD

**Issue by Zeloss** [rathena/rathena#518]
When a player attacks using a normal attack with any element the attack use the first line from attr_fix.txt when calculates the damage.

How reproduce: Use an elemental weapon and an element enchant card and fight, the attack will ignore the element. (example: undead katar 1260 vs 4141 undead property), if you modify the first line at attr_fix.txt from 100 to 0 at Undead Column/Neutral Row will grant the inmunity to undead vs undead and neutral vs undead.

-Latest Revision (Renewal)
-Client: 20130807
-Git: 4fdcb2ea6111aef88e44706460a85837902894ca

**Comment by Playtester** [comment]
You mean all attacks are always neutral regardless of weapon? I'd imagine there would be more complaints if elements didn't work at all in Renewal. Is there something needed for this to happen? What kind of weapon and card did you use?

**Comment by Zeloss** [comment]
This continues happening
Equipment used it's undead katar 1260 vs 4141 undead property

Same problem:
https://rathena.org/board/topic/100313-element-of-armor-doesnt-work
https://rathena.org/board/topic/101115-propety-element-error

**Comment by Zeloss** [comment]
This isn't solved yet.
Updated with git hash.
