### ISSUE TITLE
charserv.bat  table is missing 

### ISSUE THREAD

**Issue by normally-00** [rathena/rathena#5180]
![Untitled](https://user-images.githubusercontent.com/67834920/86516189-ac8bfe80-be48-11ea-9e47-4abc0278e22b.png)
I have problem which I don't know about cause.
I 'm not programmer.   I'm just normal gamer.
rathena update latest version and I recreate run server file by use microsoft visual studio
but before update rathena and recreate server file   I can run and play rathena normally
I run in renewal version

please tell me about cause and solution

thank you very much

**Comment by Daegaladh** [comment]
You need to apply upgrade_20200603.sql. You're probably missing some other recent updates too.

**Comment by normally-00** [comment]
Thank you very much again
my problem  resolved now
I come to rathena recently after service provider in my country run out of
contract with gravity and close server in april 2020
Before I install server rathena by read tutorial even though I can't
understand function of server program all
