### ISSUE TITLE
Map Crash When Login, Variable 'p'  is being used without being initialized.

### ISSUE THREAD

**Issue by reunite-ro** [rathena/rathena#5181]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/7d3064c667035db8e7d1714429cf4602886b412d

* **Client Date**: 20200401

* **Server Mode**: Renewal

* **Description of Issue**: Map Crash after character login.
  * Result: After character successfully login, character not even moved yet, then map server crash.
![screenrAthena000](https://user-images.githubusercontent.com/11705163/86517024-2677b400-be58-11ea-9ae6-a2c7185f5cb6.jpg)
![image](https://user-images.githubusercontent.com/11705163/86517043-4c9d5400-be58-11ea-8922-8fde945153f7.png)
Variable 'p' is being used without being initialized.

  * Expected Result: Can login as usual.
  * How to Reproduce: Download latest rathena hash stated above, and directly recompile/build, and try login. I didnt change any setting except for inter-athena.conf settings.

**Comment by aleos89** [comment]
Duplicate to #5179.
