### ISSUE TITLE
The buttons on the login screen do not work

### ISSUE THREAD

**Issue by voyfmyuh** [rathena/rathena#5183]
* rAthena Hash: https://github.com/rathena/rathena/commit/ff38cf70d2e6c73523f5809cbdc8fc8f71292383

* Client Date: 20200401

* Server Mode: Renewal

* Description of Issue: 
Clicking Opening and Sing Up does not work, does anyone know why?

![註解 2020-07-05 044648](https://user-images.githubusercontent.com/54499336/86520822-3a80dd00-be7b-11ea-846e-a20c8cef6251.png)

**Comment by mazvi** [comment]
I think is client side, not server side

**Comment by secretdataz** [comment]
not related to rAthena
