### ISSUE TITLE
warning compile Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by idk-whoami** [rathena/rathena#5185]
* **rAthena Hash**: ff38cf70d2e6c73523f5809cbdc8fc8f71292383

* **Client Date**: 20200401

* **Server Mode**: re

* **Description of Issue**:  https://pastebin.com/zLC4Kv9q
![Capture](https://user-images.githubusercontent.com/60462533/86578628-4cab6a00-bfa6-11ea-9c49-98b4feae069b.PNG)

  * Result: https://pastebin.com/zLC4Kv9q
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by mazvi** [comment]
What version of your GCC?

**Comment by idk-whoami** [comment]
gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu2)

**Comment by mazvi** [comment]
Recomended use GCC 7

**Comment by idk-whoami** [comment]
Ubuntu 20.04 LTS  switch use gcc 7   rAthena Hash: faadc800423fdde8720de3d9f176d76b11c31024

![Capture](https://user-images.githubusercontent.com/60462533/88462883-ffe9ed80-ced8-11ea-9c37-8e31d2f271d0.PNG)

`CXX     unit.cpp`
`CXX     vending.cpp`
`LD      map-server`
`scanner.h:208:17: warning: type of ‘libconfig_yy_scan_string’ does not match original declaration [-Wlto-type-mismatch]`
`scanner.c:1964:17: note: ‘libconfig_yy_scan_string’ was previously declared here`
`scanner.c:1964:17: note: code may be misoptimized unless -fno-strict-aliasing is used`
`scanner.h:202:6: warning: type of ‘libconfig_yy_delete_buffer’ does not match original declaration [-Wlto-type-mismatch]`
`scanner.c:1743:10: note: ‘libconfig_yy_delete_buffer’ was previously declared here`
`scanner.c:1743:10: note: code may be misoptimized unless -fno-strict-aliasing is used`

**Comment by mazvi** [comment]
@idk-whoami its only warning.. not issue
