### ISSUE TITLE
Visual error with skill effects 2019

### ISSUE THREAD

**Issue by Escanor-10** [rathena/rathena#5187]
* **rAthena Hash**:  https://github.com/rathena/rathena/pull/4944

* **Client Date**: 2019-04-17

* **Server Mode**:  Renewal

* **Description of Issue**: 
  * Result: 
Exception Type: 0xc0000005

0x00a3b321 D:\juegos\ro2020\Test-RO.exe
0x009f27d6 D:\juegos\ro2020\Test-RO.exe
0x009c812f D:\juegos\ro2020\Test-RO.exe
0x009c809a D:\juegos\ro2020\Test-RO.exe
0x00aceb9b D:\juegos\ro2020\Test-RO.exe
0x00ad10a6 D:\juegos\ro2020\Test-RO.exe
0x772e6359 C:\WINDOWS\System32\KERNEL32.DLL
0x77717c24 C:\WINDOWS\SYSTEM32\ntdll.dll
0x77717bf4 C:\WINDOWS\SYSTEM32\ntdll.dll
0x77721eec C:\WINDOWS\SYSTEM32\ntdll.dll

eax: 0x16c99390 ebx: 0x14d50110
ecx: 0x00cf2858 edx: 0x1a2bc930
esi: 0x00000000 edi: 0x010624a8
ebp: 0x00000000 esp: 0x001a00c4

stack 001a00c4 - 001a04c4
001A00C4 : 00 00 00 00 00 00 00 00 00 00 00 00 46 02 00 00
001A00D4 : 00 00 00 00 00 00 80 00 00 00 00 00 00 00 00 00
001A00E4 : 00 00 00 00 4C 24 2F 01 00 00 00 00 01 00 00 00
001A00F4 : 00 00 00 00 1B 10 1B 00 00 00 00 00 7F 02 00 00
001A0104 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
001A0114 : 00 00 00 00 80 1F 00 00 FF FF 00 00 00 00 00 00
001A0124 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
001A0134 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
001A0144 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
001A0154 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
001A0164 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
001A0174 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
001A0184 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
001A0194 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
001A01A4 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
001A01B4 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

Launch Info
02B1 00A4 00A4 00A4 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000

Job : Rune Knight

1@new.rsw 95 352
  * Expected Result: 
  * How to Reproduce: 
When using a skill outside the range of a player, it generates the following error
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by reunite-ro** [comment]
I think this is client side ? Such as homunculus range skill ? But if it is, it should give lua files error.

Are you using this client files ? https://github.com/llchrisll/ROenglishRE

**Comment by Escanor-10** [comment]
> I think this is client side ? Such as homunculus range skill ? But if it is, it should give lua files error.
> 
> Are you using this client files ? https://github.com/llchrisll/ROenglishRE

Yes, I am using all the files, and it marks that error, that is, if the character is out of sight and uses a skill, it generates that error, with the 2020 exe ​​it does not generate it, but with the 2019 if

**Comment by aleos89** [comment]
This looks like the client's EXE crash data. Is there any reason you're using that specific client date? Have you tried going to the 2020 client? It could be a bug in that specific client.

**Comment by 24msz6eo** [comment]
> * **rAthena Hash**:  #4944
> 
> * **Client Date**: 2019-04-17
> 
> * **Server Mode**:  Renewal
> 
> * **Description of Issue**:
>   
>   * Result: 
>     Exception Type: 0xc0000005
> 
> 0x00a3b321 D:\juegos\ro2020\Test-RO.exe
> 0x009f27d6 D:\juegos\ro2020\Test-RO.exe
> 0x009c812f D:\juegos\ro2020\Test-RO.exe
> 0x009c809a D:\juegos\ro2020\Test-RO.exe
> 0x00aceb9b D:\juegos\ro2020\Test-RO.exe
> 0x00ad10a6 D:\juegos\ro2020\Test-RO.exe
> 0x772e6359 C:\WINDOWS\System32\KERNEL32.DLL
> 0x77717c24 C:\WINDOWS\SYSTEM32\ntdll.dll
> 0x77717bf4 C:\WINDOWS\SYSTEM32\ntdll.dll
> 0x77721eec C:\WINDOWS\SYSTEM32\ntdll.dll
> 
> eax: 0x16c99390 ebx: 0x14d50110
> ecx: 0x00cf2858 edx: 0x1a2bc930
> esi: 0x00000000 edi: 0x010624a8
> ebp: 0x00000000 esp: 0x001a00c4
> 
> stack 001a00c4 - 001a04c4
> 001A00C4 : 00 00 00 00 00 00 00 00 00 00 00 00 46 02 00 00
> 001A00D4 : 00 00 00 00 00 00 80 00 00 00 00 00 00 00 00 00
> 001A00E4 : 00 00 00 00 4C 24 2F 01 00 00 00 00 01 00 00 00
> 001A00F4 : 00 00 00 00 1B 10 1B 00 00 00 00 00 7F 02 00 00
> 001A0104 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> 001A0114 : 00 00 00 00 80 1F 00 00 FF FF 00 00 00 00 00 00
> 001A0124 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> 001A0134 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> 001A0144 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> 001A0154 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> 001A0164 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> 001A0174 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> 001A0184 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> 001A0194 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> 001A01A4 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> 001A01B4 : 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
> 
> Launch Info
> 02B1 00A4 00A4 00A4 0000 0000 0000 0000
> 0000 0000 0000 0000 0000 0000 0000 0000
> 0000 0000 0000 0000 0000 0000 0000 0000
> 0000 0000 0000 0000 0000 0000 0000 0000
> 
> Job : Rune Knight
> 
> [1@new.rsw](mailto:1@new.rsw) 95 352
> 
> * Expected Result:
> * How to Reproduce: 
>   When using a skill outside the range of a player, it generates the following error
> * Official Information:
> 
> * **Modifications that may affect results**:

Is the 2019-04-17 client you use the RE version?
