### ISSUE TITLE
MySQL function SHA2 does not exist

### ISSUE THREAD

**Issue by bgamez23** [rathena/rathena#5189]
* **rAthena Hash**: ff38cf70d2e6c73523f5809cbdc8fc8f71292383

* **Client Date**: 

* **Server Mode**: Pre-Renewal

* **Description of Issue**: i got this error [SQL]: DB error - FUNCTION ragnarok.SHA2 does not exist on centos but does not exist in windows server.
  * Result: [SQL]: DB error - FUNCTION ragnarok.SHA2 does not exist
[Debug]: at account.cpp:664 - UPDATE `login` SET `web_auth_token` = LEFT( SHA2( CONCAT( UUID(), RAND() ), 256 ), 16 ), `web_auth_token_enabled` = '1' WHERE `account_id` = '2000000'. it also happens on another account who login the game.

  * Expected Result: 
  * How to Reproduce: i don't know how to produce since it only appears when i login my character.
  * Official Information:
  

* **Modifications that may affect results**: pre-renewal setup server and vip enabled

**Comment by secretdataz** [comment]
What's your CentOS version?

**Comment by bgamez23** [comment]
Cent0S release 6.10 (Final)

**Comment by bgamez23** [comment]
![image](https://user-images.githubusercontent.com/1854368/86787138-5b257e80-c097-11ea-8ee2-9c2d6eec2ddd.png)

**Comment by aleos89** [comment]
What SQL product are you using and it's version?

**Comment by bgamez23** [comment]
![image](https://user-images.githubusercontent.com/1854368/86928176-ca1dd880-c166-11ea-96ed-6edff02f1f78.png)

**Comment by aleos89** [comment]
You need to update to 5.5.6 or later.

**Comment by LiamKarlMitchell** [comment]
What about doing the crypt in code rather than the DB.
I've been curious to implement bcrypt

**Comment by Lemongrass3110** [comment]
> What about doing the crypt in code rather than the DB.
> I've been curious to implement bcrypt

@LiamKarlMitchell he can simply leave out the hashing or change the sql command. It was just added because there were security concerns for only using UUID. Basically doing it in code would drag some big dependencies into rAthena, which we want to prevent if we can.

**Comment by Badarosk0** [comment]
> * **rAthena Hash**: [ff38cf7](https://github.com/rathena/rathena/commit/ff38cf70d2e6c73523f5809cbdc8fc8f71292383)
> 
> * **Client Date**:
> 
> * **Server Mode**: Pre-Renewal
> 
> * **Description of Issue**: i got this error [SQL]: DB error - FUNCTION ragnarok.SHA2 does not exist on centos but does not exist in windows server.
>   
>   * Result: [SQL]: DB error - FUNCTION ragnarok.SHA2 does not exist
>     [Debug]: at account.cpp:664 - UPDATE `login` SET `web_auth_token` = LEFT( SHA2( CONCAT( UUID(), RAND() ), 256 ), 16 ), `web_auth_token_enabled` = '1' WHERE `account_id` = '2000000'. it also happens on another account who login the game.
>   * Expected Result:
>   * How to Reproduce: i don't know how to produce since it only appears when i login my character.
>   * Official Information:
> * **Modifications that may affect results**: pre-renewal setup server and vip enabled

I also have this same problem.

I use MD5 encoding, can that be?

**Comment by bgamez23** [comment]
> > * **rAthena Hash**: [ff38cf7](https://github.com/rathena/rathena/commit/ff38cf70d2e6c73523f5809cbdc8fc8f71292383)
> > * **Client Date**:
> > * **Server Mode**: Pre-Renewal
> > * **Description of Issue**: i got this error [SQL]: DB error - FUNCTION ragnarok.SHA2 does not exist on centos but does not exist in windows server.
> >   
> >   * Result: [SQL]: DB error - FUNCTION ragnarok.SHA2 does not exist
> >     [Debug]: at account.cpp:664 - UPDATE `login` SET `web_auth_token` = LEFT( SHA2( CONCAT( UUID(), RAND() ), 256 ), 16 ), `web_auth_token_enabled` = '1' WHERE `account_id` = '2000000'. it also happens on another account who login the game.
> >   * Expected Result:
> >   * How to Reproduce: i don't know how to produce since it only appears when i login my character.
> >   * Official Information:
> > * **Modifications that may affect results**: pre-renewal setup server and vip enabled
> 
> I also have this same problem.
> 
> I use MD5 encoding, can that be?
> 
> I use Cent0S release 6.10 (Final). Do I need to update?

might be compatible problem for mysql that installed on your centos.i haven't tried to update mine since it was work fine before the web_auth_token implementation.

**Comment by Badarosk0** [comment]
I will update my mysql and check if it will resolve.

**Comment by phaeloliveira** [comment]
I have the same error , I can log in the game but I can't cast skills, can someone help.
