### ISSUE TITLE
UserKeys.lua not saving after log out

### ISSUE THREAD

**Issue by Surefirer** [rathena/rathena#5190]
* **rAthena Hash**: 

* **Client Date**: 20200318

* **Server Mode**: Re

* **Description of Issue**: 
  * Result: after you have done the hotkeys setting, <userkeys.lua> does not save the setting after log out. You need to reset every time you log in.
  * Expected Result: the setting should be saved in the <userkeys.lua>
  * How to Reproduce: setting the key, then log out, exit the game, then log in.
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Daegaladh** [comment]
This is a client problem, nothing to do with rAthena.

**Comment by Badarosk0** [comment]
Could you reopen this issue? This problem is on the emulator side. Need an update on the emulator side for new clients.
@Daegaladh
