### ISSUE TITLE
Missing: Jobs improvement project. March 3, 2019

### ISSUE THREAD

**Issue by Masao87** [rathena/rathena#5195]
* **rAthena Hash**: 

* **Client Date**: 20200401

* **Server Mode**: Renewal

* **Description of Issue**: rAthena seems to still be missing all the updates from this skill balance: https://www.divine-pride.net/forum/index.php?/topic/3723-kro-jobs-improvement-project/page/7/&tab=comments#comment-7644
  * Result: Some skills aren't fully up-to-date with kRO.
  * Expected Result: Update the missing skills according to the balance patch notes.
  * How to Reproduce: 
  * Official Information: https://www.divine-pride.net/forum/index.php?/topic/3723-kro-jobs-improvement-project/page/7/&tab=comments#comment-7644
  

* **Modifications that may affect results**:

**Comment by llchrisll** [comment]
As far as I know it's only the Warlock which isn't yet done, but it requires the support for the higher Item ID's which is currently WIP,  to support the new Spellbooks, afterwards are the Quest Skills, but that's a different Rebalance.

**Comment by ecdarreola** [comment]
This patch are not yet applied to the servers. I think these are just dev-notes.

**Comment by Masao87** [comment]
> 
> 
> As far as I know it's only the Warlock which isn't yet done, but it requires the support for the higher Item ID's which is currently WIP, to support the new Spellbooks, afterwards are the Quest Skills, but that's a different Rebalance.

These changes were made after the initial release of the main patch of balance changes for spell book and the other skills, all these changes still need to be made.

**Comment by OptimusM** [comment]
As @ecdarreola said, those patch notes are for future updates, i have been looking on kRO and my mechanic has not the damage increased yet.

Some reports and notes say that these patches will be applied until september, so, currently are just "future updates" until they decided migrated to Sakray and then, to the main servers.

**Comment by Masao87** [comment]
I see, my bad then :) Thanks for the info and sorry for the wrong report.
