### ISSUE TITLE
Clan System - Crashes

### ISSUE THREAD

**Issue by ecdarreola** [rathena/rathena#5196]
* **rAthena Hash**: 7457e32

* **Client Date**: 20200401 or 20200304

* **Server Mode**: Renewal

* **Description of Issue**: when I use clan chat it appears twice on the chat.
  * Result: see image below.
![image](https://user-images.githubusercontent.com/48939874/87055228-a629c800-c236-11ea-9d17-cbd1364b2638.png)

  * Expected Result: only one line of the message should appear.
  * How to Reproduce: Join clan -> use /cl <message> -> observe chat box/log.
As for the random crash, I'm not able to fully reproduce it but here's how I crashed the server using windows debug.
Created a new character -> spam /cl test -> crash server.
  * Official Information: Not sure but afaik message should only appear once.
  

* **Modifications that may affect results**: #5192 #5141 #3640 
  
  

Not sure if this is related to my other report #5194

**Comment by ecdarreola** [comment]
Additional findings, if you enter a map thru portal the clan line message adds + 1. (see image below)

![image](https://user-images.githubusercontent.com/48939874/87055762-58618f80-c237-11ea-9b9d-759e19fafdf3.png)

**Comment by Badarosk0** [comment]
Have you made any changes to the src? It looks like it's normal for me.
![screenRock Beta000](https://user-images.githubusercontent.com/13624462/87067424-663cf380-c1ea-11ea-81e6-ab9a853eab09.jpg)

**Comment by ecdarreola** [comment]
@Badarosk0 no changes done to the source except for the PR mentioned above.

**Comment by Haydrich** [comment]
i can confirm it
How to Reproduce :
1- @warp prt_in 41 112
2- join any clan
3- 
![image](https://user-images.githubusercontent.com/54556365/87074767-a36fa880-c21f-11ea-8cf0-8c15e41382ab.png)
allow clan message appear in the chat
4- /cl HI
![image](https://user-images.githubusercontent.com/54556365/87074798-ad91a700-c21f-11ea-8cbd-8cc2b419db6e.png)

**Comment by ecdarreola** [comment]
Additional findings: Clan basic info -> number of members keeps increasing upon changing map.
