### ISSUE TITLE
Finger Offensive Bug on Prenewal 

### ISSUE THREAD

**Issue by cahya1992** [rathena/rathena#5209]
* **rAthena Hash**: 

157392cd1

* **Client Date**: 20180621

* **Server Mode**:  Pre renewal

* **Description of Issue**:  When champ have only 1 spirit ball can use finger offensive lv 5 its should need 5 spirit if you use pre renewal server
  * Result: 
  * Expected Result: shold consum 5 spirit ball to use finger offensive lv 5
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Daegaladh** [comment]
That's actually the official behaviour for both pre-renewal and renewal, the number of hits depends on the number of spheres used, but the ATK modifier and cast time depends on the level of the skill
