### ISSUE TITLE
Client Crash - coin_exchange.txt

### ISSUE THREAD

**Issue by ecdarreola** [rathena/rathena#5211]
* **rAthena Hash**: 07fd129

* **Client Date**: 20200304 and 20200401

* **Server Mode**: Renewal

* **Description of Issue**: Client crashes when talking to NPC Replication Expert Paltu (npc/re/merchants/coin_exchange.txt)
  * Result: Client crash without any errors in server
  * Expected Result: No crash.
  * How to Reproduce: Talk to the NPC and choose option 2 where is says "Replication?" and complete until you need to replicate the item.

However, if you use option 3 "I know you got lots up your sleeve!", it doesn't crash and you are able to complete the dialog of the npc.

Rough guess is that the crash point is at line 1124 onwards. (No console errors on map-server)
  * Official Information: None
  

* **Modifications that may affect results**: #2381

**Comment by aleos89** [comment]
I went back to test this again on 1e43c6c and I'm unable to reproduce a crash.

**Comment by ecdarreola** [comment]
Try creating a script that uses progress bar without any text. Somehow crash usually happens on that line. Sample line below.
```
prontera,150,150,4 script Taste 194,{
mes "[Taste]";
mes "That's right! right! Oh, what should I do? What to do, what to do? guard? Oh yeah. I called the guard.";
donpcevent strnpcinfo(0) + "::OnBar"; //Process Bar
sleep2 2000;
next;
mes "[Taste]";
mes "what!! It's bad! When did it break down?? Oh, what to do";
close;

OnBar:
    progressbar_npc "000000",2;
    end;
}```

**Comment by laziem** [comment]
Having this issue as well. Replacing progressbar with sleep2 will do the trick for now

**Comment by Badarosk0** [comment]
I confirm this problem. It also happens to me. 
This seems to be random, the error sometimes occurs.

**Comment by OptimusM** [comment]
Random crashes on progressbar are also encountered on kRo, i had almost 13 crash on the same NPC doing 17.1 (one in the library) so, i dont think is some rAthena related, but as laziem said, adding a sleep2 will solve the problem.

**Comment by Balferian** [comment]
Also i see problem with progressbar crash in malangdo quests.
https://github.com/rathena/rathena/blob/master/npc/re/quests/quests_malangdo.txt#L6243

**Comment by Akkarinage** [comment]
For all of you that are "confirming" the bug still exists, can you provide your rA git hash, please.

**Comment by Lemongrass3110** [comment]
This seems to be a Ragexe problem. It does not occur on RagexeRE.

Ragexe does not seem to like open message windows. So make sure to close all open message windows before triggering a progressbar.
RagexeRE seems to be able to handle this just fine.

Gravity being Gravity again it seems... Really strange because they even use open message windows in official scripts...
Maybe one of their developers will read this and look into the code differences between the two executables - hopefully.
Or maybe @4144 can provide a diff that fixes whatever the difference between the two clients is.

**Comment by Balferian** [comment]
@Lemongrass3110  yesterday i was test it with ragexe 2020-04-01 and it`s always crash client
and then test it with ragexe 2020-09-02b all works fine.
Looks like this is client related problem.
