### ISSUE TITLE
20200401 Client Issue but related server

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#5215]
* **rAthena Hash**: Latest

* **Client Date**: 20200401

* **Server Mode**: RENEWAL

* **Description of Issue**: 20200401 Exit to Windows Issue
it we click exit to windows the client show disconnect from server: https://cdn.discordapp.com/attachments/570540644737613838/732326591857819789/unknown.png
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by admkakaroto** [comment]
Thia are not in client side?

**Comment by mazvi** [comment]
I think is not.. its like if we lag then disconnect.. i think this is like we click exit to windows then client send packet exit to server then server send kick out packet to our char..

**Comment by Lemongrass3110** [comment]
I know that @4144 claims that there is a difference in packets between rAthena and Hercules on his Nemo repository, but Hercules has the same code on 0x18a/0x18b as we do. So I do not think that this is related to the server side or both emulators have a wrong packet nowadays.

**Comment by attackjom** [comment]
comment at set_eof(fd);  at clif_parse_QuitGame  (clif.cpp) will solve this.

**Comment by voyfmyuh** [comment]
> 評論set_eof（fd）; 在clif_parse_QuitGame（clif.cpp）上將解決此問題。

This method really solves this problem. I don't know if this modification will cause any impact?

**Comment by mazvi** [comment]
how about according @attackjom statement? so this is client side or server side?

**Comment by mazvi** [comment]
i think the problem of set_eof is if we use custom PACKET_OBFUSCATION? 

@voyfmyuh are you using PACKET_OBFUSCATION?

**Comment by Masao87** [comment]
Any progress on this? I'm having the same issue and this causes the hotkeys to not be saved as well except, thanks in advance!
