### ISSUE TITLE
expand possession limit does not work!

### ISSUE THREAD

**Issue by voyfmyuh** [rathena/rathena#5218]
* rAthena Hash: https://github.com/rathena/rathena/commit/43ea987ba74133c9bef2150acfc24785e2c76e48

* Client Date: 20200401

* Server Mode: Renewal

* Description of Issue: 
expand possession limit does not work!

![1594763394390](https://user-images.githubusercontent.com/54499336/87480145-4af53c80-c65f-11ea-83ed-da36a53e88b0.jpg)

**Comment by Balferian** [comment]
it is not implanted yet in rA

**Comment by Sardineee** [comment]
#refine MAX_INVENTORY and hexing client is working so far. Limit is 255.

**Comment by voyfmyuh** [comment]
How can I change the value displayed in /100 on the 20200410 client?
![87480145-4af53c80-c65f-11ea-83ed-da36a53e88b0](https://user-images.githubusercontent.com/54499336/87745416-69566600-c820-11ea-8c36-caae8e825629.jpg)

**Comment by Balferian** [comment]
@Sardineee he mean an official feature.
When you click this icon, open dialog that increase max inventory size +10 slots (max 200 slots).
It requare 1 ![image](https://user-images.githubusercontent.com/16213511/87780816-243e2e00-c838-11ea-9cf7-65c24acf4844.png) [[이벤트]인벤토리 확장 쿠폰](https://www.divine-pride.net/database/item/25791)

**Comment by Sardineee** [comment]
@Balferian yeah you're right. it hasn't been implemented yet.

**Comment by dimasshotta** [comment]
![screenrAthena193](https://user-images.githubusercontent.com/74591268/117919183-c030ad00-b316-11eb-990d-2a3147da1b6b.jpg)
![screenrAthena194](https://user-images.githubusercontent.com/74591268/117919192-c2930700-b316-11eb-9578-c193c6200a91.jpg)
if someone could help with the packet in cliff.c..
