### ISSUE TITLE
Genetic: Change Material bug

### ISSUE THREAD

**Issue by raynra** [rathena/rathena#522]
On latest GIT, referencing: http://irowiki.org/wiki/Change_Material

There are two ways to create Witch Starsand:
10 Insect Feeler + 15 Chung Jah
or
100 Moth Dust + 100 Scell

However, the code for CHANGEMATERIAL only allows for 1 method per item ID. As a result, you cannot make Witch Starsand using 100 Moth Dust + 100 Scell (even though they are both in produce_db.txt)

This is the only item that can be made in multiple ways using Change Material.

**Comment by cydh** [comment]
oh finally someone report this. xD I notice this months ago, I just keep it quite :P

**Comment by raynra** [comment]
Yeah... pretty low-priority :)
Let's just leave this here for a rainy day.
