### ISSUE TITLE
Sphere Mine not moving, issue with NPC_RUN

### ISSUE THREAD

**Issue by Indigo000** [rathena/rathena#5220]
* **rAthena Hash**: c52b3b784a7f958050e4f3186b001382151bd648 (not the latest, but at least parts of the code are still part of the latest revision code as well)

* **Client Date**: 2018-06-21

* **Server Mode**: Pre-Renewal

* **Description of Issue**: 
  * Result:  Sphere Mine does not move upon being hit. It simply stays in its current position, shouts /hlp and explodes.
  * Expected Result:  When hitting the Sphere Mine, it should start moving in the direction at which you hit it, for the amount of cells equal to the skill level used.
  * How to Reproduce: 

Spawn a Sphere Mine, hit it and see. There are a couple of reasons for this that we found through debugging.
NPC_RUN calls `unit_escape` which calls `unit_walktoxy(bl, bl->x + dist*dirx[dir], bl->y + dist*diry[dir], 0)`. This means the Flag in unit_walktoxy is set to 0 while it should be set to 2 for `&2: Force walking (override can_move)`. This was done since commit 81ca299d913305da56be82bbe49a02a0c12c273d.

In addition, according to commit 6ef71063cbc98b61fcae8eb05cd9a22e6b87be9c it should walk the amount of cells that's equal to the skill level of NPC_RUN used, not some random amount of cells like called in `unit_escape`. Not entirely sure about this, but most sources seem to point this way. Herc also does it based on skill level: https://github.com/HerculesWS/Hercules/blob/stable/src/map/skill.c#L8464

A few other notes: when we set the flag to 2 properly and when your ASPD is high the moment you hit the Sphere Mine, it starts to walk the moment you start the attack, but when your attack lands, the walking of the Sphere Mine stops. When your ASPD is low however, even when you hit the Sphere Mine, it will continue walking as intended.
Additionally, when it explodes, the drops of the Sphere Mine appear on the original spawn location, not on the location at which it exploded.

Some of this could also be related to issue https://github.com/rathena/rathena/issues/3622

  * Official Information: Pretty much every resource about the skill, as well as the in-game skill description.
  

* **Modifications that may affect results**:  Quite a lot, but none relevant to this part of the code.

**Comment by Daegaladh** [comment]
I tried to fix this some time ago but encounter some problems and the sphere kept stopping even when I was forcing unit_walktoxy.
I'd check this again and hope we can fix it.
