### ISSUE TITLE
NC_NEUTRALBARRIER and NC_STEALTHFIELD need to be equipped with specific props to activate

### ISSUE THREAD

**Issue by voyfmyuh** [rathena/rathena#5222]
* rAthena Hash: https://github.com/rathena/rathena/commit/43ea987ba74133c9bef2150acfc24785e2c76e48

* Client Date: 20200401

* Server Mode: Renewal

* Description of Issue: 
NC_NEUTRALBARRIER and NC_STEALTHFIELD need to be equipped with Barrier Builder and Camouflage Generator to launch, but the current settings only need to be carried without equipment

**Comment by qwerty7vp** [comment]
where did you get the info from that Mechanic has to equip items to use those 2 skills ?

**Comment by voyfmyuh** [comment]
> 您從哪裡獲得機械師必須裝備這些2種技能的信息？

I need to confirm again Thank you

**Comment by voyfmyuh** [comment]
New problems are needed now, and teaching new clients, such as 20200401, will display Unknown Item
![註解 2020-07-16 122351](https://user-images.githubusercontent.com/54499336/87626691-90009800-c75f-11ea-9f0e-b49b8634acae.png)

**Comment by aleos89** [comment]
![image](https://user-images.githubusercontent.com/3521753/87702977-1e791780-c768-11ea-9462-4ce4a3cabb42.png)
It's not required to be equipped in order to use the skill.

**Comment by voyfmyuh** [comment]
> ![image](https://user-images.githubusercontent.com/3521753/87702977-1e791780-c768-11ea-9462-4ce4a3cabb42.png)
> It's not required to be equipped in order to use the skill.

Sorry, I made a mistake myself

Then please ask

Encountered a problem again, on newer clients, such as 20200401, Unknown Item will be displayed

![87626691-90009800-c75f-11ea-9f0e-b49b8634acae](https://user-images.githubusercontent.com/54499336/87704624-451e6900-c7cf-11ea-8c48-79ec112343de.png)

**Comment by aleos89** [comment]
And it displayed correctly on 2018 and earlier?

**Comment by voyfmyuh** [comment]
> And it displayed correctly on 2018 and earlier?

Yes, I displayed it correctly on the client 20180621
