### ISSUE TITLE
Several Rock Ridge mob drops have 0z sell price

### ISSUE THREAD

**Issue by Latiosu** [rathena/rathena#5223]
* **rAthena Hash**: `1595efc35`

* **Client Date**: 2018-06-20

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Attempting to sell following items to NPC will net the player 0z: `25277;25280;25281;25282;25284;25285;`
  * Expected Result: Sell price to match price listed on divine-pride.net
  * How to Reproduce: Attempt to sell any of the above items to an NPC.
  * Official Information: Sell prices prices listed on divine-pride.net (kRO server) list a different value, e.g. https://www.divine-pride.net/database/item/25280

* **Modifications that may affect results**: None

**Screenshot:**
![rockridge-drops](https://user-images.githubusercontent.com/7020503/87728332-343d1a00-c806-11ea-93d1-b520b88c541c.jpg)

**Comment by Atemo** [comment]
Fixed in https://github.com/rathena/rathena/commit/2cd46b9425d33fd3f27a7aaca528bee3557c8fe3
