### ISSUE TITLE
about skill Round Trip & Flaming Petals and some item wrong script

### ISSUE THREAD

**Issue by Angelic234** [rathena/rathena#5227]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/9000948c3c524c98f472da716164ac3d5954706f

* **Client Date**: 20200401

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: 
1. Round trip not affected by Long range modifiers
2. When used Fire Charm , the Flaming Petals only increased 10% damage.
3. item 1384 script bonus4 bAutoSpellOnSkill,"BS_HAMMERFALL",50,3,"SM_MAGNUM"; to bonus4 bAutoSpellOnSkill,"BS_HAMMERFALL","SM_MAGNUM",50,3;
4. item comdo
(1) 28910:20800 and 20800:4045 miss job limited (Guillotine_Cross) https://www.divine-pride.net/database/item/20800/ (JRO item description)
(2) 19204:29353 and 19204:29354 change WS_CARTBOOST to GN_CARTBOOST because WS_CARTBOOST max skill level is 1.
  * Expected Result: 
  * How to Reproduce: 
1. Round trip :
(1) @item 28241 x2 and 4633 x2
(2) Add card to one weapon (longatkrate+10% x2)
(3) Tested with two weapon and there is no any damage increased.
2. Flaming Petals 
According to https://github.com/rathena/rathena/pull/4425 and https://www.divine-pride.net/forum/index.php?/topic/3674-note-update-schedule-in-the-first-quarter-of-2019/&tab=comments#comment-6599
Thers is no any info changed skill damage ratio from 20% to 10%?
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by lututui** [comment]
> (2) 19204:29353 and 19204:29354 change WS_CARTBOOST to GN_CARTBOOST because WS_CARTBOOST max skill level is 1.

This. Here's video evidence of GN_CARTBOOST being used:

https://youtu.be/poo9tQABNeg?t=96
https://youtu.be/RNp3fnOdBXw?t=4

**Comment by aleos89** [comment]
Fixed in 5ec7373.

**Comment by Angelic234** [comment]
how about the other Issue ?

**Comment by aleos89** [comment]
For future reports, please keep issues separated into their own reports, makes tracking a lot easier.

**Comment by aleos89** [comment]
Round Trip is considered short range. Is there somewhere that details it being long ranged?

For Blaze Shield (Crimson Fire Formation), the bonus is [already 20% per fire charm](https://github.com/rathena/rathena/blob/master/src/map/battle.cpp#L6330).

**Comment by Angelic234** [comment]
Round Trip https://github.com/rathena/rathena/issues/2301 or https://www.limitro.com/forums/reportcenter/sourcebugs/rebellion-round-trip-round-trip-is-a-range-skill-in-official-r765/ 
I think about Flaming Petals not Blaze Shield , because the bonus for Flaming Petals is only 10% per fire charm. Rathena changed https://github.com/rathena/rathena/pull/4425 but I can't find any infomation .

**Comment by aleos89** [comment]
Seems like I added the 20% bonus to Wind Blade (NJ_HUUJIN) when it shouldn't have been. That's the only differences I [can see](https://www.divine-pride.net/forum/index.php?/topic/4175-kro-expanded-classes-skill-balance/).

**Comment by Angelic234** [comment]
Sorry It's my fault that I don't know how to express in English.
I mean Flaming Petals(NJ_KOUENKA) the bonus is should be 20% instead of 10% per fire charm 
`					case NJ_KOUENKA:`
`						skillratio -= 10;`
`						if(sd && sd->spiritcharm_type == CHARM_TYPE_FIRE && sd->spiritcharm > 0)`
`							skillratio += 10 * sd->spiritcharm;` <- this line
`						break;`
According to https://irowiki.org/wiki/Fire-Charm I dont understand why you change 20% -> 10% in #4425 
There is no need change Wind Blade and Wind Charm bonus #5257
I am sorry for any inconvenience this has caused you

**Comment by aleos89** [comment]
I understand what you're saying. You're saying that both NJ_KOUENKA and NJ_KAENSIN should have the 20% bonus, but the kRO changelog I linked to above only states that NJ_KAENSIN (Blaze Shield) received that bonus.

While looking over the other skills I noticed I accidentally gave NJ_HUUJIN the 20% bonus when the description doesn't state it was increased. This is why I made #5257, to revert it.
