### ISSUE TITLE
Packet Ver Error

### ISSUE THREAD

**Issue by ijped27** [rathena/rathena#523]
![1234](https://cloud.githubusercontent.com/assets/13431749/8809936/5bbe6628-2fa0-11e5-9c55-10e5216b9ac4.png)
even i change clientinfo packet_ver packet_db even on clif.h no luck

**Comment by nanakiwurtz** [comment]
1. What git commit hash?
2. Which client date?
3. Pre-re/Re?
4. Are you using Packet Obfuscation? If yes, have you used the correct packet keys?
5. And why clif.h?
This sounds like a support question rather than bug report... :sweat:

**Comment by ijped27** [comment]
1. sorry i dnt know where will i look that hash
2. 2013-8-07 / 2013-12-23cRagexe
3. pre-re
4. Nope but i already try i use shako 2013-08-07 and themon 2013-12-23c
5. i just try to change the max packet ver just to see if there an error
for that settings this is fresh git and i just modified 1st the
char_athena inter_athena map_athena this is the 1st time i encounter about
the disconnection

**Comment by anacondaqq** [comment]
ahhhhhhhhhhhh
i know why you have this problem:

comment this line, and check again: https://github.com/rathena/rathena/blob/master/src/config/core.h#L100

**Comment by ijped27** [comment]
i just enable it and find encryption key so my problem done
