### ISSUE TITLE
Loop Bijou Instance

### ISSUE THREAD

**Issue by idk-whoami** [rathena/rathena#5230]
* **rAthena Hash**: 5cc391b2eab7a3884938e3525ba77631456bab2c

* **Client Date**: 20200401

* **Server Mode**: re

* **Description of Issue**: https://youtu.be/wvOjYC3AaQs
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Atemo** [comment]
"Official mechanism". The instance can be repeated on aegis, but I will suggest a correction in a PR soon
