### ISSUE TITLE
Guild window does not open even with guild created

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#5232]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/f9974170c96653e5bcc98e3c71c70dc125c8ed52

* **Client Date**: 20200401

* **Server Mode**: RE

* **Description of Issue**: 
  * Result: Guild window does not open even with guild created. Apparently this problem starts after applying a crash issue fix. The problem starts after this:(https://github.com/rathena/rathena/commit/f9974170c96653e5bcc98e3c71c70dc125c8ed52)
![image](https://user-images.githubusercontent.com/13624462/87977828-bdbe4780-caa5-11ea-840b-27430b032fff.png)

  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment]
This is because you use #5204
