### ISSUE TITLE
Memory Leaks

### ISSUE THREAD

**Issue by PhillyThomas** [rathena/rathena#5234]
* **bdd63022a**: 

* **2018-06-20*: 

* **Renewal**: 

* **Memory leaks found in map.cpp, causing restarts to fail and potentially random server crashes**: 
  * Result: 
> 0001 : map.cpp line 2519 size 16 address 0x0x7fa98ac2965c
> 0002 : map.cpp line 2519 size 16 address 0x0x7fa98ac2974c
> 0003 : map.cpp line 2519 size 16 address 0x0x7fa989516b64
> 0004 : map.cpp line 2519 size 16 address 0x0x7fa9895188d4
> 0005 : map.cpp line 2519 size 16 address 0x0x7fa98951cad4
> 0006 : map.cpp line 3589 size 120000 address 0x0x557f383140a0
> 0007 : map.cpp line 3589 size 120000 address 0x0x557f382f6ba0
> 0008 : map.cpp line 3589 size 120000 address 0x0x557f382d96a0

These lines point to the following:
> 2519:
> CREATE(mapit, struct s_mapiterator, 1);

> 3589:
> CREATE(m->cell, struct mapcell, size);

* **Modifications that may affect results**: 
Haven't added any map related source modifications, other than changing pathfinding to the old formula.

**Comment by aleos89** [comment]
So you have any way to reproduce this?

**Comment by maqubeks** [comment]
Memory manager: Memory leaks found at 2020/07/26 01h52m32s (Unknown version).
0001 : script.cpp line 2507 size 512 address 0x0x7fdef6390694
0002 : script.cpp line 2507 size 512 address 0x0x7fdef63908b4
0003 : script.cpp line 2507 size 512 address 0x0x7fdef6390ad4
0004 : script.cpp line 2507 size 512 address 0x0x7fdef6390cf4
0005 : script.cpp line 2507 size 512 address 0x0x7fdef6390f14
0006 : script.cpp line 2507 size 512 address 0x0x7fdef6391134
0007 : script.cpp line 2507 size 512 address 0x0x7fdef6391354
0008 : script.cpp line 2507 size 512 address 0x0x7fdef6391574
0009 : script.cpp line 2507 size 512 address 0x0x7fdef6391794
0010 : script.cpp line 2507 size 512 address 0x0x7fdef63919b4
0011 : script.cpp line 2507 size 512 address 0x0x7fdef6391bd4
0012 : script.cpp line 2507 size 512 address 0x0x7fdef6391df4
0013 : script.cpp line 2507 size 512 address 0x0x7fdef6392014
0014 : script.cpp line 2507 size 512 address 0x0x7fdef6392234
0015 : script.cpp line 2507 size 512 address 0x0x7fdef6392454
0016 : script.cpp line 2507 size 512 address 0x0x7fdef6392674
0017 : script.cpp line 2507 size 512 address 0x0x7fdef6392894
0018 : script.cpp line 2507 size 512 address 0x0x7fdef6392ab4
0019 : script.cpp line 2507 size 512 address 0x0x7fdef6392cd4
0020 : script.cpp line 2507 size 512 address 0x0x7fdef6392ef4
0021 : script.cpp line 2507 size 512 address 0x0x7fdef6393114
0022 : script.cpp line 2507 size 512 address 0x0x7fdef6393334
0023 : script.cpp line 2507 size 512 address 0x0x7fdef6393554
0024 : script.cpp line 2507 size 512 address 0x0x7fdef6393774
0025 : script.cpp line 2507 size 512 address 0x0x7fdef6393994
0026 : script.cpp line 2507 size 512 address 0x0x7fdef6393bb4
0027 : script.cpp line 2507 size 512 address 0x0x7fdef6393dd4
0028 : script.cpp line 2507 size 512 address 0x0x7fdef6393ff4
0029 : script.cpp line 2507 size 512 address 0x0x7fdef6394214
0030 : script.cpp line 2507 size 512 address 0x0x7fdef6394434
0031 : script.cpp line 2507 size 512 address 0x0x7fdef6394654
0032 : script.cpp line 2507 size 512 address 0x0x7fdef6394874
0033 : script.cpp line 2507 size 512 address 0x0x7fdef6394a94
0034 : script.cpp line 2507 size 512 address 0x0x7fdef6394cb4
0035 : script.cpp line 2507 size 512 address 0x0x7fdef6394ed4
0036 : script.cpp line 2507 size 512 address 0x0x7fdef63950f4
0037 : script.cpp line 2507 size 512 address 0x0x7fdef6395314
0038 : script.cpp line 2507 size 512 address 0x0x7fdef6395534
0039 : script.cpp line 2507 size 512 address 0x0x7fdef6395754
0040 : script.cpp line 2507 size 512 address 0x0x7fdef6395974
0041 : script.cpp line 2507 size 512 address 0x0x7fdef6395b94
0042 : script.cpp line 2507 size 512 address 0x0x7fdef6395db4
0043 : script.cpp line 2671 size 40 address 0x0x7fdef63a34f4
0044 : script.cpp line 2671 size 40 address 0x0x7fdef63a3544
0045 : script.cpp line 2671 size 40 address 0x0x7fdef63a3594
0046 : script.cpp line 2671 size 40 address 0x0x7fdef63a35e4
0047 : script.cpp line 2671 size 40 address 0x0x7fdef63a3634
0048 : script.cpp line 2671 size 40 address 0x0x7fdef63a3684
0049 : script.cpp line 2671 size 40 address 0x0x7fdef63a36d4
0050 : script.cpp line 2671 size 40 address 0x0x7fdef63a3724
0051 : script.cpp line 2671 size 40 address 0x0x7fdef63a3774
0052 : script.cpp line 2671 size 40 address 0x0x7fdef63a37c4
0053 : script.cpp line 2671 size 40 address 0x0x7fdef63a3814
0054 : script.cpp line 2671 size 40 address 0x0x7fdef63a3864
0055 : script.cpp line 2671 size 40 address 0x0x7fdef63a38b4
0056 : script.cpp line 2671 size 40 address 0x0x7fdef63a3904
0057 : script.cpp line 2671 size 40 address 0x0x7fdef63a3954
0058 : script.cpp line 2671 size 40 address 0x0x7fdef63a39a4
0059 : script.cpp line 2671 size 40 address 0x0x7fdef63a39f4
0060 : script.cpp line 2671 size 40 address 0x0x7fdef63a3a44
0061 : script.cpp line 2671 size 40 address 0x0x7fdef63a3a94
0062 : script.cpp line 2671 size 40 address 0x0x7fdef63a3ae4
0063 : script.cpp line 2671 size 40 address 0x0x7fdef63a3b34
0064 : script.cpp line 2671 size 40 address 0x0x7fdef63a3b84
0065 : script.cpp line 2671 size 40 address 0x0x7fdef63a3bd4
0066 : script.cpp line 2671 size 40 address 0x0x7fdef63a3c24
0067 : script.cpp line 2671 size 40 address 0x0x7fdef63a3c74
0068 : script.cpp line 2671 size 40 address 0x0x7fdef63a3cc4
0069 : script.cpp line 2671 size 40 address 0x0x7fdef63a3d14
0070 : script.cpp line 2671 size 40 address 0x0x7fdef63a3d64
0071 : script.cpp line 2671 size 40 address 0x0x7fdef63a3db4
0072 : script.cpp line 2671 size 40 address 0x0x7fdef63a3e04
0073 : script.cpp line 2671 size 40 address 0x0x7fdef63a3e54
0074 : script.cpp line 2671 size 40 address 0x0x7fdef63a3ea4
0075 : script.cpp line 2671 size 40 address 0x0x7fdef63a3ef4
0076 : script.cpp line 2671 size 40 address 0x0x7fdef63a3f44
0077 : script.cpp line 2671 size 40 address 0x0x7fdef63a3f94
0078 : script.cpp line 2671 size 40 address 0x0x7fdef63a3fe4
0079 : script.cpp line 2671 size 40 address 0x0x7fdef63a4034
0080 : script.cpp line 2671 size 40 address 0x0x7fdef63a4084
0081 : script.cpp line 2671 size 40 address 0x0x7fdef63a40d4
0082 : script.cpp line 2671 size 40 address 0x0x7fdef63a4124
0083 : script.cpp line 2671 size 40 address 0x0x7fdef63a4174
0084 : script.cpp line 2671 size 40 address 0x0x7fdef63a41c4
0085 : script.cpp line 2671 size 40 address 0x0x7fdef63a4214
0086 : script.cpp line 2671 size 40 address 0x0x7fdef63a4264
0087 : script.cpp line 2671 size 40 address 0x0x7fdef63a42b4
0088 : script.cpp line 2507 size 512 address 0x0x7fdef61faa74
0089 : script.cpp line 2507 size 512 address 0x0x7fdef61fac94
0090 : script.cpp line 2507 size 512 address 0x0x7fdef61faeb4
[Warning]: Memory manager: Memory leaks found and fixed.


me too when I stop the server it will display this

**Comment by mplaten** [comment]
Did you change anything at /db/import/pet_db.yml?

I'll open a issue, but before, is better check this.

I have import a pet to overwrite the original, and this cause memory leaks (kkkk) - @aleos89 - Should i open a new issue for that?

**Comment by Lemongrass3110** [comment]
> 
> 
> Did you change anything at /db/import/pet_db.yml?
> 
> I'll open a issue, but before, is better check this.
> 
> I have import a pet to overwrite the original, and this cause memory leaks (kkkk) - @aleos89 - Should i open a new issue for that?

@mplaten please open another issue, because you can actually provide the root cause for your problem. :-)
And I already see where it comes from.

**Comment by Lemongrass3110** [comment]
No further input from user.
