### ISSUE TITLE
npc_scriptcont: is not unknown NPC

### ISSUE THREAD

**Issue by blipblopblip** [rathena/rathena#5235]
* **rAthena Hash**: ce42168b0d2d25f66ab8a5fc5e2ef24d988274ae

* **Client Date**: 20151104

* **Server Mode**: Pre-Renewal

* **Description of Issue**: 
  * Result:  some function isn't working properly. More importantly is the [@security](https://rathena.org/board/files/file/3510-new-security-system-for-item-and-zeny-protection-no-src-mod-required/) which @Daegaladh made.
`npc_scriptcont: atcmd_security (sd->npc_id=110005792) is not 'Unknown NPC' (id=0).`
`npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Center Warper#1 (id=110005384).`
`npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Hollgrehenn (id=110000232).`
`npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Kafra Employee (id=110000169).`
`npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not npcname (id=110005119).`
  * Expected Result: Scripts are working properly before, then suddenly it went like this..
  * How to Reproduce: I can drop my npc scripts here if it needed
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Daegaladh** [comment]
Please tell us the version of rAthena you're using, and any source modification you may have
I don't think my security script is related, since the same thing happens with official scripts.

**Comment by Daegaladh** [comment]
Have you tried updating your server to the lastest revision?

**Comment by blipblopblip** [comment]
I edited the rAthena hash, sorry I forgot to add it earlier. I don't think I modified anything related to the `npc_scriptcont`

**Comment by Daegaladh** [comment]
I've encountered this bug from time to time in lastest revisions, but only with a few npcs, so I think we can confirm it.
```
[ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Kafra Employee (id=110001561).
[ Debug ] : npc_scriptcont: 'Unknown NPC' (sd->npc_id=0) is not Alfredo#aldeg_cas01 (id=110054531).
```

**Comment by blipblopblip** [comment]
@Daegaladh can I message you in discord as well? I kinda have more information about something wrong in your @security as well..

**Comment by Daegaladh** [comment]
I have my PMs blocked, tag me on rA's server so I can add you

**Comment by Daegaladh** [comment]
haha found how to reproduce it!
open a kafra, wait in the menu until the secure timeout kicks in, then instead of click on close, click on cancel on the menu

**Comment by blipblopblip** [comment]
Cool!!! Do you know what could be the possible fix for this? 🤔

**Comment by blipblopblip** [comment]
I'm still getting these errors, and yet when you are talking to a specific NPC, you're character will be stuck and you will need to character select in order to move again.

Errors that still showing
`npc_scriptcont: Kafra Employee (sd->npc_id=110000171) is not 'Unknown NPC' (id=0).`
`npc_scriptcont: atcmd_security (sd->npc_id=110005794) is not 'Unknown NPC' (id=0).`

**Comment by Lemongrass3110** [comment]
@blipblopblip please try #5260

**Comment by blipblopblip** [comment]
@Lemongrass3110 I'm still getting these even though I tried #5260 

`npc_scriptcont: monster_safari_core (sd->npc_id=110006662) is not Monser Safari (id=110006660).`
`npc_scriptcont: Kafra Employee (sd->npc_id=110000684) is not Warper#31-1 (id=110006410).`

**Comment by Lemongrass3110** [comment]
Any custom modifications? ;-)

**Comment by blipblopblip** [comment]
> Any custom modifications? ;-)

That could relate to this? None.
