### ISSUE TITLE
Battleground queue @reloadscript duplicate entry on join

### ISSUE THREAD

**Issue by marky291** [rathena/rathena#5241]
Writing this on mobile.

When you enter a battleground from the queue but a @reloadacript is used, the battleground script has no way of unbooking(script) the map queue(src) and the players will now have duplicate entry to the queue, in a permanent state where they can no longer enter or leave.

**Comment by aleos89** [comment]
If you could fill out the report using the template it will help with tracking. Thanks.

**Comment by Daegaladh** [comment]
@marky291 could you test our fix and confirm it solved the problem? thanks!

**Comment by marky291** [comment]
OnReset (the proposal) does not work on custom BG script, the label is never hit?

I wrote into @reloadscript an auto kick from every battleground map with message to player, then clearing any queue that’s in progress (Which worked as needed).

I just write issue here for others to notice, Thanks!

**Comment by Daegaladh** [comment]
> OnReset (the proposal) does not work on custom BG script, the label is never hit?
> 
> I wrote into @reloadscript an auto kick from every battleground map with message to player, then clearing any queue that’s in progress (Which worked as needed).
> 
> I just write issue here for others to notice, Thanks!

I ended up not using OnReset at all, have you checked my last changes? #5255

**Comment by marky291** [comment]
@Daegaladh This fixes the issue raised on this ticket, Thank you.

**Comment by aleos89** [comment]
Fixed in 0e4b36d.
