### ISSUE TITLE
Platinum Alter (RL_P_ALTER) no Coins requirement

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#5243]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/2a37f687d334615d451c48ed2efc2a996fd4cd08

* **Client Date**: 20200401

* **Server Mode**: RE

* **Description of Issue**: The Platinum After skill can be used without the need for Coins.
  * Result: 
  * Expected Result: It must consume all Coins.
  * How to Reproduce: 
  * Official Information:
  
```
[SKID.RL_P_ALTER] = {
		"플래티넘 알터 (백금 제단)",
		"MAX Lv : 5",
		"^777777습득조건 : 리치스 코인 1^000000",
		"계열 : ^777777보조^000000",
		"내용 : ^777777자신이 사용하는 탄환이 성속성 일 때만 발동한다.^000000",
		"^777777스킬 발동 시, 가지고 있는 코인을 전부 소모하며, 스킬 레벨 및 스킬 사용에 소모한 코인의 갯수에 따라, 공격력이 상승한다.^000000",
		"^777777또한 지속시간 동안 배리어가 생성되며 스킬 레벨별로 배리어가 막아줄 수 있는 공격 횟수 한도 수치가 정해져 있다. 단, 홀리 라이트에 맞을 경우 일격에 배리어가 풀리게 된다.^000000",
		"^777777지속시간이 끝나기 전에 무기나 탄환을 교체하는 경우, 플래티넘 알터의 효과는 사라진다.(배리어는 유지된다.)^000000",
		"^777777이 스킬은 [매드니스 캔슬러] 및 [히트 배럴] 과 함께 사용 할 수 없다.^000000",
		"[Level 1] : ^777777MAXHP 5%의 배리어, 4회방어, 지속시간 30 초^000000",
		"[Level 2] : ^777777MAXHP 10%의 배리어, 5회방어, 지속시간 45 초^000000",
		"[Level 3] : ^777777MAXHP 15%의 배리어, 6회방어, 지속시간 60 초^000000",
		"[Level 4] : ^777777MAXHP 20%의 배리어, 7회방어, 지속시간 75 초^000000",
		"[Level 5] : ^777777MAXHP 25%의 배리어, 8회방어, 지속시간 90 초^000000"
	},
```
* **Modifications that may affect results**:

**Comment by qwerty7vp** [comment]
It will consume all coins if you're having coins
More coins = more bonus atk
Skill Requirement is just Silver Bullet

**Comment by Badarosk0** [comment]
> It will consume all coins if you're having coins
> More coins = more bonus atk
> Skill Requirement is just Silver Bullet

Thank you for confirming this information.
