### ISSUE TITLE
Cash Shop Account Only (ID) Section Issue

### ISSUE THREAD

**Issue by reunite-ro** [rathena/rathena#5244]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/a7d7e72aa93ed12d070759409a318b108e975739

* **Client Date**: 20200304

* **Server Mode**: Renewal

* **Description of Issue**: Cash Shop Account Only (ID) Section cannot be used.
  * Result: Cash Shop Account Only (ID) Section wont appear even added for Type 8 (before this for type: SALE)
  * Expected Result: Can add Account Only (ID) Section type in cash shop database.
  * How to Reproduce: Try to add cash shop database in item_cash_db.txt.

**Comment by Balferian** [comment]
the same issue https://github.com/rathena/rathena/issues/5146
