### ISSUE TITLE
SR_KNUCKLEARROW does not consume Bullets from lv 6

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#5245]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/2a37f687d334615d451c48ed2efc2a996fd4cd08

* **Client Date**: 20200401

* **Server Mode**: RE

* **Description of Issue**: SR_KNUCKLEARROW must not consume Bullets starting at lv 6 and is consuming.
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  
https://www.divine-pride.net/database/skill/2336
```
수라신탄(修羅身彈)
MAX Lv : 10
습득조건 : 섬전보 1
계열 : 액티브 / 데미지
내용 : 순간적으로 적에게 거리를 좁히며 뛰어들어, 목표를 강타하여 원거리 물리 데미지와 함께 넉 백 시킨다. 대상이 넉 백 될 때 벽이나 장애물 등에 부딫히면 추가적인 데미지를 입는다.
시전자의 베이스 레벨에 따라 데미지가 증가되며, 넉 백으로 인한 추가 데미지는 대상의 소지량에 따라 증가되고 넉 백이 되지 않는 보스형 몬스터에게는 스킬 데미지가 증가된다.
스킬 사용시 기 구체 1 개가 소모되며, 6레벨부터는 기 구체가 소모되지 않는다.
[Level 1] : 공격력 600%/넉백 데미지 150%/보스형 공격력 700%
[Level 2] : 공격력 700%/넉백 데미지 300%/보스형 공격력 900%
[Level 3] : 공격력 800%/넉백 데미지 450%/보스형 공격력1100%
[Level 4] : 공격력 900%/넉백 데미지 600%/보스형 공격력1300%
[Level 5] : 공격력1000%/넉백 데미지 750%/보스형 공격력1500%
[Level 6] : 공격력1100%/넉백 데미지 900%/보스형 공격력1700%
[Level 7] : 공격력1200%/넉백 데미지 1050%/보스형 공격력1900%
[Level 8] : 공격력1300%/넉백 데미지 1200%/보스형 공격력2100%
[Level 9] : 공격력1400%/넉백 데미지 1350%/보스형 공격력2300%
[Level10] : 공격력1500%/넉백 데미지 1500%/보스형 공격력2500%
```
* **Modifications that may affect results**: 
  
  
```
        - Level: 6
          Amount: 0
        - Level: 7
          Amount: 0
        - Level: 8
          Amount: 0
        - Level: 9
          Amount: 0
        - Level: 10
          Amount: 0
```
need to add this modification to skill_db and it will be resolved

**Comment by aleos89** [comment]
Did this change on a later date? The [Sura Update](https://www.divine-pride.net/forum/index.php?/topic/3824-kro-changelog-april-17-2019/) didn't specify any changes to this skill's description.
