### ISSUE TITLE
Jewelry Ring - ID 28332

### ISSUE THREAD

**Issue by llchrisll** [rathena/rathena#5248]
* **rAthena Hash**: Latest
* **Client Date**:  Doesn't matter.
* **Server Mode**: Renewal

* **Description of Issue**: kRO: no effect
iRo: Gives no LUK, but gives additionally Variable Casting Time reduction of 30% in the buff's duration. Also it's event based script, but I don't know which event it's from so...
  * Expected Result: Either match kRO description or make it 100% iRO
  * Official Information: [Divine-Pride.net](https://www.divine-pride.net/database/item/28332)

As I was checking the Item Description of the item, I noticed this and checked the item db entry, now I'm wondering what to do with it :I, match kRo, item db or iRO description.
I would match it with kRO description tho...

**Comment by Everade** [comment]
kRO also features an effect, it's just not specificaly stated in the description.
Since rAthena emulates kRO, kRO is always the way to go.

It was officialy featured in a Valentine's Day event back in 2014:
https://ro.gnjoy.com/news/event/View.asp?Seq=571

**Comment by llchrisll** [comment]
K thanks for the info, but that would mean it's still missing the Variable Cast Time reduction of 30%. :I

**Comment by aleos89** [comment]
```
item  Jewel_Ring		
	event OnStartEquip:	
		SetAutoAttacked Jewel_Ring 50 5
		SetAutoMAttacked Jewel_Ring 50 5
	return	
	event OnFinishEquip:	
		ResetAutoAttacked Jewel_Ring 50 5
		ResetAutoMAttacked Jewel_Ring 50 5
	return	
	event OnActiveArmor:	
		ShowEffect "" EF_ENHANCE
		AddExtParam User VAR_PLUSASPD 2
		SubSpellCastTime 30
	return	
	event OnDeactiveArmor:	
		SubExtParam User VAR_PLUSASPD 2
		AddSpellCastTime 30
	return	
	event OnActiveMArmor:	
		ShowEffect "" EF_ENHANCE
		AddExtParam User VAR_PLUSASPD 2
		SubSpellCastTime 30
	return	
	event OnDeactiveMArmor:	
		SubExtParam User VAR_PLUSASPD 2
		AddSpellCastTime 30
	return	
```
Looks like the LUK bonus is not there and we are missing the Variable Cast reduction.
