### ISSUE TITLE
Items Looted from Pet will be gone when Player changed Map.

### ISSUE THREAD

**Issue by Nxsmaddog** [rathena/rathena#5249]
* **rAthena Hash**: Latest

* **Client Date**: 20150513

* **Server Mode**: 255/120 Pre-Renewal

* **Description of Issue**: 
![123123](https://user-images.githubusercontent.com/68797294/88469602-dc995f80-cf25-11ea-9bcc-153736569210.PNG)

  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
I was unable to reproduce this on faadc80.
![image](https://user-images.githubusercontent.com/3521753/88552605-4848fe80-cff2-11ea-8064-cef8cfff93b5.png)
I killed some mobs south of Prontera and went back to Prontera. My pet had the items still.
