### ISSUE TITLE
Reverberation locks stauses and stats

### ISSUE THREAD

**Issue by Daedren** [rathena/rathena#525]
I've tried to buff myself as a Wanderer with various normal buffs, doesn't matter which ones, and after using Reverberation on an enemy, everything related to your character is locked until you relog.

By locked I mean it is completely immutable. This includes:
- Any buffs you may have end up staying permenantly
- Stats, even if you remove equipment, the gear's stats remain.
- Movement Speed (Well, this counts as buffs/debuffs too)
- Statuses, you may not acquire new status effects.

**Comment by aleos89** [comment]
I wasn't able to reproduce this issue.

**Comment by RagnarokNova** [comment]
I was able to reproduce this in a clean freshly installed rA. Do note that the buffs will show a status icon, but there is no change in movement speed or status points. Only after relogging do I get the status bonuses and movespeed increase.

**Comment by RagnarokNova** [comment]
Clean character:
http://i.imgur.com/K3HTJM5.png
Use Reverb on monster:
http://i.imgur.com/zswzK8O.png
Attention Concentrate (Any buff works):
http://i.imgur.com/RiSeikP.png (Notice same status)
After Relogging:
http://i.imgur.com/UMQeBvn.png

Death and map changing doesn't clear the bug either, so far I can say relogging is the only fix.

**Comment by aleos89** [comment]
Ah, I see why. I'm going to blame it on this b71ed05.

**Comment by aleos89** [comment]
Should be fine as of d95f5d2.
