### ISSUE TITLE
hold shift attack duel system

### ISSUE THREAD

**Issue by roSBK** [rathena/rathena#5256]
Well I was having trouble attacking without hold shift key on the duel system, I thought it was more because of the hexed problem but I came across another problem in the source:

https://www.youtube.com/watch?v=NULVfJfZq2s

I compared with other emulators the function 'clif_map_property' different from them is checking mapflags instead of sending the requested property right away, this causes all this embarrassment.

I even created a test function and it worked:
```
void clif_map_property_pvp(struct block_list *bl, enum send_target t)
{
#if PACKETVER >= 20121010
	short cmd = 0x99b;
	unsigned char buf[8];
#else
	short cmd = 0x199;
	unsigned char buf[4];
#endif
	
	WBUFW(buf,0)=cmd;
	WBUFW(buf,2)=MAPPROPERTY_FREEPVPZONE;

#if PACKETVER >= 20121010
	struct map_data *mapdata = map_getmapdata(bl->m);

	WBUFL(buf,4) = 1;
#endif
	
	clif_send(buf,packet_len(cmd),bl,t);
}
```

it is up to the rathena team to reassess the function, if it is meeting the needs of all systems installed in the source.

**Comment by aleos89** [comment]
Could you please follow the issue template when creating reports? Thanks.

**Comment by roSBK** [comment]
I will look for more on how to do this, sorry.

**Comment by reunite-ro** [comment]
I found out that when attacking mob using client 2020, the mob name are not shown continously like 20180620 client before.
Its only shown when right clicking the mob.

Is it intended as it should be ?
