### ISSUE TITLE
Crystallization taking bonus VIT into account

### ISSUE THREAD

**Issue by Daedren** [rathena/rathena#526]
Crystallization's duration is supposed to be reduced by the target's base VIT, and that's what the source code seems to imply as well, there's no problem there. But in-game, both base VIT and bonus VIT are affecting the duration.

**Comment by aleos89** [comment]
I wasn't able to reproduce this.

**Comment by Daedren** [comment]
I tested this with a clean rAthena just now. I now tried an extreme case just to make sure:
A person with 1+0 VIT hit by Crystallization gets stuck for approximately 20 seconds.
A person with 1+120 VIT hit by Crystallization gets stuck for approximately 8 seconds.

I got the 120 VIT by making a couple of normal equipments with VIT+10 enchants through @item2, just for testing's sake.

**Comment by Playtester** [comment]
Usually status changes take the bonus stats into account, don't they? Is this special for Crystallization? Also what source do you base this information on? Is there any discussion that would confirm this?

**Comment by Daedren** [comment]
It really depends on the status. But yeah, Crystallization and Arrullo's durations both depend on base stats. I haven't tested Arrullo, but this same issue might be happening to that one as well.

Here's one source: https://docs.google.com/document/pub?id=1I2byIqDij02jwl6Tn4ekgHff0E501JP16iwYLc9vhDE
that comes from this thread: http://forums.warpportal.com/index.php?/topic/55686-iro-post-balance-formulas/

About discussing this, the source code already has:
```c
tick_def2 = b_status->vit*100;
```

which should be base status, so someone was already convinced that it's true, but I don't see it happening in-game.

**Comment by Playtester** [comment]
I guess that would explain why aleos can't reproduce it, it's already coded to use base vit. How did you test it?

**Comment by Daedren** [comment]
I tested it by using Diamond Dust Lv5 on a naked character with 1 VIT, timing the crystallization duration. Then a 2nd time on the same character but with equipment that grants VIT through either cards, the description itself and enchants (Obsidian Card, Faceworm Skin, Brisingamen, Amistr Hat, Fabre Cards)

The times always match the formula. (Assuming it'd take total VIT rather than base)

An easy (but fairly extreme) example to set up without making a lot of gear is to wear an Obsidian Card on an armor, and add @dex +1440
This will give you 1+80 VIT

With a Sorcerer you can Diamond Dust and the crystallization will in the end last 10.3 seconds instead of about 19.

**Comment by RagnarokNova** [comment]
Bump for this one, as it's a pretty huge deal. I'll be scanning the code shortly too.

**Comment by RagnarokNova** [comment]
http://i.imgur.com/fTnQdo2.png
http://i.imgur.com/EIQgEAY.png
http://i.imgur.com/iygNBT2.png

So b_status is not just reading base.
