### ISSUE TITLE
To often stuck after talk into npc

### ISSUE THREAD

**Issue by hendra814** [rathena/rathena#5275]
* **rAthena Hash**: lastest

* **Client Date**: 20180621

* **Server Mode**: Renewal

* **Description of Issue**: Talk to any NPC (custom and Official) after talk to the NPC the character can't walk or talk again to NPC like in the picture.
No error appear at map server, 
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**: 
  
  
![screenrAthena043](https://user-images.githubusercontent.com/9587609/89105536-22858480-d44c-11ea-92d4-c74c6c821260.jpg)

**Comment by aleos89** [comment]
Have you applied #5260?

**Comment by hendra814** [comment]
> Have you applied #5260?

Not yet, i will try it

**Comment by CairoLee** [comment]
I have same issue when the character talk with `prontera,160,133` - `YuPi`.
After applied #5260, the problem seems to be solved. thanks for @aleos89 to point out.

**Comment by hendra814** [comment]
Ok, problem solve.
Thanks for the support and information
