### ISSUE TITLE
Duplicate friend_id

### ISSUE THREAD

**Issue by blipblopblip** [rathena/rathena#5277]
* **rAthena Hash**:  faadc800423fdde8720de3d9f176d76b11c31024

* **Client Date**: 20151104a Ragexe

* **Server Mode**: Pre-Renewal

* **Description of Issue**: 
  * Result: Duplicating Entry of friend_id
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**: There's no modifications that could affect this.
  
  

Error code
`(08/02/2020 19:41:40) [ Debug ] : at char.cpp:483 - INSERT INTO `friends` (`char_id`, `friend_id`) VALUES ('151979','152570'),('151979','152570')`
`(08/02/2020 19:41:45) [ SQL Error ] : DB error - Duplicate entry '151942-152086' for key 'PRIMARY'`
`(08/02/2020 19:41:45) [ Debug ] : at char.cpp:483 - INSERT INTO `friends` (`char_id`, `friend_id`) VALUES ('151942','150203'),('151942','150504'),('151942','150694'),('151942','151577'),('151942','151421'),('151942','150230'),('151942','150081'),('151942','151613'),('151942','152086'),('151942','152086'),('151942','150432')`
`(08/02/2020 19:42:22) [ SQL Error ] : DB error - Duplicate entry '151951-151618' for key 'PRIMARY'`
`(08/02/2020 19:42:22) [ Debug ] : at char.cpp:483 - INSERT INTO `friends` (`char_id`, `friend_id`) VALUES ('151951','150237'),('151951','151618'),('151951','151618')`

**Comment by Lemongrass3110** [comment]
Any steps on how to reproduce this?

**Comment by blipblopblip** [comment]
@Daegaladh is experiencing this as well. I have no idea how to reproduce this as well.

**Comment by Daegaladh** [comment]
I used to get these a lot, but haven't happened in months anymore, maybe you missed a commit?
