### ISSUE TITLE
Memory Leaks

### ISSUE THREAD

**Issue by mplaten** [rathena/rathena#5279]
* **rAthena Hash**: 

* **Client Date**: 
Not aplicable

* **Server Mode**: 
Not aplicable

* **Description of Issue**: When you import a pet with /db/import/pet_db.yml to overwrite the original, this cause memory leaks
  * Result:  Memory leaks
  * Expected Result:  Import a pet without cause memory leaks
  * How to Reproduce:  Try to overwrite an existing pet.

ex.: use this /db/import/pet_db.yml - 
[pet_db.txt](https://github.com/rathena/rathena/files/5016069/pet_db.txt)

  * Official Information: Not aplicable
  

* **Modifications that may affect results**:

**Comment by mplaten** [comment]
Thanks :)

**Comment by mplaten** [comment]
@Lemongrass3110, I keep getting memory leaks, even after 'fix'...

Did you too?

**Comment by Lemongrass3110** [comment]
Sorry my fault. Fixed in 1d04920
