### ISSUE TITLE
bonus2 bAddRace,r,x; BUG

### ISSUE THREAD

**Issue by tmav94** [rathena/rathena#528]
According with this data [bonus2 bAddRace,r,x;  +x% physical damage against race r]
This item [18600,Cat_Ear_Beret,Cat Ear Beret,4,20,,100,,5,,1,0xFFFFFFFF,63,2,256,,0,1,761,{ if (getrefine() >= 5) {bonus2 bAddRace,RC_DemiHuman,(2*(getrefine()-5)); bonus2 bSubRace,RC_DemiHuman,(2*(getrefine()-5));} },{},{}] will grants to user 2% of damage against demi human as resistence.

I tested it many time in DemiHuman monsters but nothing happen to the output damage. Its a bug?

Request Assistence.

**Comment by nanakiwurtz** [comment]
What's your current git commit hash?
You are using outdated data, as of commit ae6b8f26  =
```
18600,Cat_Ear_Beret,Cat Ear Beret,4,20,,100,,5,,1,0xFFFFFFFF,63,2,256,,0,1,761,{ bonus bAtkRate,5; .@r = getrefine(); if(.@r < 5) .@r = 5; bonus2 bSubRace,RC_DemiHuman,(.@r - 5); bonus2 bAddRace,RC_DemiHuman,(.@r - 5); },{},{}
```
