### ISSUE TITLE
Removes waitingroom check for Maya Purple hackfix

### ISSUE THREAD

**Issue by Forte22** [rathena/rathena#5288]
* **rAthena Hash**:  9991b09

* **Client Date**: 2018

* **Server Mode**: renewal

* **Description of Issue**: Job quest Waiting rooms are gone
![grafik](https://user-images.githubusercontent.com/66630784/89332911-77b3d700-d694-11ea-8be1-625f58f1af8c.png)

  * Result: while doing job quests, the waiting room above NPCs are gone and players cant progress during the job change quest
  * Expected Result: waiting room should be there
  * How to Reproduce: do knight or assassin job quest

i believe its related to this https://github.com/rathena/rathena/commit/1c6270f96ac3c56fa0e41349977f73a40a229a39

**Comment by aleos89** [comment]
I'll blame this partly on Gravity. It doesn't make sense as to why they made 2 NPC stacked on one another for something like this.

Technically the `disablenpc` events aren't needed but just in case to keep NPC visual stacking issues from happening I'll change them to `hideonnpc` which keeps the waiting rooms from disappearing.
