### ISSUE TITLE
Axe Boomerang Visual Effect

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#5291]
* **rAthena Hash**: 
* **Client Date**: 2020-03-04aRagexeRE
* **Server Mode**: RE
* **Description of Issue**: after you use the skill several times, the visual effect of the skill is frozen on the screen.
* **Modifications that may affect results**: https://github.com/rathena/rathena/pull/5081
* **Print**: 
![axe_visual_bug](https://user-images.githubusercontent.com/6227618/89353048-f9533700-d68b-11ea-8f6a-486c81f51736.png)

I do not know if the PR mentioned above is at fault. But it is the only modification present in the emulator.

**Comment by aleos89** [comment]
It’s a client animation bug. I encountered it on kRO when testing.
