### ISSUE TITLE
Brandish Spear Update, Not as expected

### ISSUE THREAD

**Issue by PipeDeveloper** [rathena/rathena#5294]
* **rAthena Hash**: 
Latest (05/08/2020)

* **Client Date**: 
Not aplicable

* **Server Mode**: 
RENEWALL

**Description of Issue**: 

  * Result: Brandish spear at level 10 hits in a 5 x 2 area monster in front away from 3 cells doesnt get damaged. You may able to hit away from 3 cells but monsters/players doesnt get damaged. This is the rAthena Latest revision.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/35433329/89455421-50124c80-d730-11ea-8179-6fba94be02dd.gif)

This is how brandish is in rAthena: ( O = knight position looking north, X = cells that applies damage)

X X X X X
X X X X X
X X O X X

  * Expected Result:  Brandish spear at level 10 hits in a 5 x 5 area, Also if you cast it 3 cells away monsters monster gets damaged.

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/35433329/89455701-b7300100-d730-11ea-8802-77fae10080e1.gif)

This is how brandish should be: ( O = knight position looking north, X = cells that applies damage, N = cells that should not apply damage)

N X X X N
X X X X X
X X X X X
X X X X X
X X O X X

  * How to Reproduce: Just create a knight and start doing test. Short videos are the evidence

  * Official Information: At iRO Transendence and iRO Chaos
https://irowiki.org/wiki/Brandish_Spear

**Modifications that may affect results**: 
Pretty sure we can start from here
https://github.com/rathena/rathena/commit/4021c61d8d83d77e81620bb4822199409b8604c0

**Comment by PipeDeveloper** [comment]
Im 90% sure that here is defined splash area of brandish spear at src/map/skill.cpp

```
#ifdef RENEWAL
	case KN_BRANDISHSPEAR:
		map_foreachindir(skill_area_sub, src->m, src->x, src->y, bl->x, bl->y,
			skill_get_splash(skill_id, skill_lv), skill_get_maxcount(skill_id, skill_lv), 0, splash_target(src),
			src, skill_id, skill_lv, tick, flag | BCT_ENEMY | 0,
			skill_castend_damage_id);
		break;
#else
	case KN_BRANDISHSPEAR:
#endif
	case ML_BRANDISH:
		skill_area_temp[1] = bl->id;

		if(skill_lv >= 10)
			map_foreachindir(skill_area_sub, src->m, src->x, src->y, bl->x, bl->y,
				skill_get_splash(skill_id, skill_lv), 1, skill_get_maxcount(skill_id, skill_lv)-1, splash_target(src),
				src, skill_id, skill_lv, tick, flag | BCT_ENEMY | (sd?3:0),
				skill_castend_damage_id);
		if(skill_lv >= 7)
			map_foreachindir(skill_area_sub, src->m, src->x, src->y, bl->x, bl->y,
				skill_get_splash(skill_id, skill_lv), 1, skill_get_maxcount(skill_id, skill_lv)-2, splash_target(src),
				src, skill_id, skill_lv, tick, flag | BCT_ENEMY | (sd?2:0),
				skill_castend_damage_id);
		if(skill_lv >= 4)
			map_foreachindir(skill_area_sub, src->m, src->x, src->y, bl->x, bl->y,
				skill_get_splash(skill_id, skill_lv), 1, skill_get_maxcount(skill_id, skill_lv)-3, splash_target(src),
				src, skill_id, skill_lv, tick, flag | BCT_ENEMY | (sd?1:0),
				skill_castend_damage_id);
		map_foreachindir(skill_area_sub, src->m, src->x, src->y, bl->x, bl->y,
			skill_get_splash(skill_id, skill_lv), skill_get_maxcount(skill_id, skill_lv)-3, 0, splash_target(src),
			src, skill_id, skill_lv, tick, flag | BCT_ENEMY | 0,
			skill_castend_damage_id);
		break;

```

**Comment by aleos89** [comment]
The current LUA from kRO has a max range of 2:
```lua
	[SKID.KN_BRANDISHSPEAR] = {
		"KN_BRANDISHSPEAR",
		SkillName = "Brandish Spear",
		MaxLv = 10,
		SpAmount = { 24, 24, 24, 24, 24, 24, 24, 24, 24, 24 },
		bSeperateLv = false,
		AttackRange = { 2, 2, 2, 2, 2, 2, 2, 2, 2, 2 },
		_NeedSkillList = {
			{ SKID.KN_RIDING, 1 },
			{ SKID.KN_SPEARSTAB, 3 }
		}
	},
```

**Comment by PipeDeveloper** [comment]
> I was unable to reproduce this on [84223d5](https://github.com/rathena/rathena/commit/84223d5e2232c037eb71aac6aa0cb4bcfa1b15c3). I would get pulled into the monster as I should within 2 cells.

to reproduce i suggest to stand 3 cells away (leaving 2 cells between you and the monster) just like the first animation. Stand between, then leaving one cell, then leaving two cells (here is the issue).

If you're unable to reproduce in that way, you can simulate by summon static monsters in line. The results are at lvl 10, brandish should hit a 5x5 area in fron the knight, not 2x5 as actually it does.

Thank you very much and i really apreciate you handle this case

**Comment by PipeDeveloper** [comment]
This is what im talking about.

Brandish in rAthena:
![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/35433329/89812373-0483e800-db0e-11ea-9dcd-26c05a2b341e.gif)

2 cells far from knight facing the mob.

Expected Brandish in original server:
![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/35433329/89812439-27ae9780-db0e-11ea-9614-873fe48fbc0c.gif)

5cells far from knight facing the mob. Like it should be.

No matter you cast the skill from 1, 2 or 3 cells, area is counting from the caster. As you see in rAthena there are 3 cells that are not doing damage.

**Comment by PipeDeveloper** [comment]
This is the summary of everything. More simple.
Green cells means that when you cast the skill on the front of the caster, that is the area that the skills affects.

![Sin título2](https://user-images.githubusercontent.com/35433329/89814025-89700100-db10-11ea-968c-a6bc65327898.png)

![Sin título1](https://user-images.githubusercontent.com/35433329/89814110-aa385680-db10-11ea-9c3b-b8c7f35aa8af.png)
