### ISSUE TITLE
Skills ignoring requirements

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#5295]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/0cc12c813e5ca2a3fa84972ec88325632060af73
* **Client Date**: 2020-03-04aRagexeRE
* **Server Mode**: RE
* **Description of Issue**: For some strange reason the skill RL_HEAT_BARREL is ignoring the requirement for spheres to be used, if you use it without spheres the skill will appear with the buff icon but does not give the bonus. In any case, if you have the spheres and activate the skill you receive the bonus.
* **PR Used**: https://github.com/rathena/rathena/pull/5081
  * How to Reproduce: Just cast the RL_HEAT_BARREL skill without any spheres.

**Comment by admkakaroto** [comment]
This problem is happening with several other jobs in the game, mechanic also among other classes that need special requirements to use skills.

**Comment by qwerty7vp** [comment]
It's normal behavior that you can use RL_HEAT_BARREL without coins
since the skill itself will "Consume All Coins" (if you having them)
the more coins = more bonus ( fct, atk )
no coins = you'll just get aspd with decreasing hit

**Comment by admkakaroto** [comment]
@qwerty7vp I didn't know that, sorry for the Issue. Thanks bro.
