### ISSUE TITLE
all_commands with Disable Commands

### ISSUE THREAD

**Issue by croxinuz** [rathena/rathena#530]
![untitled-2](https://cloud.githubusercontent.com/assets/13469673/8853140/8955aa4e-3183-11e5-88d5-af19701e7398.jpg)

i'm Group_id 10 with all commands permission,but i'm disable @item only and no effect, it's bug ?

**Comment by aleos89** [comment]
```
if (pc_group_has_permission(group_id, PC_PERM_USE_ALL_COMMANDS))
		return true;
```
This check comes before the specific 'commands' check, thus any additions or denials in the 'commands' section is ignored. I would assume with the creation of the group system this was intended since the point of "all_commands" is to give all commands, no exceptions.
