### ISSUE TITLE
2020 client + Refine UI not working anymore

### ISSUE THREAD

**Issue by LotusRO** [rathena/rathena#5300]
* **rAthena Hash**: 

* **Client Date**: 

 20200401

* **Server Mode**: 

 Renewal

* **Description of Issue**: 
  * Result:  Refine UI no longer seems to function as it only shows an apple instead of eluniums etc
  * Expected Result:  with 20180621 it works fine, our refine UI has been full functioning for a year give or take
  * How to Reproduce:  put in the PR of Refine UI into your server, use 2020 client and try to refine
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment]
Comment on the respective pull request instead as this is not officially supported yet.
