### ISSUE TITLE
Battle Ground Doc?

### ISSUE THREAD

**Issue by felipemartins210** [rathena/rathena#5305]
"Battle Ground Doc?"

Guys i'm looking for it, there is not.

Let's create it?

**Comment by aleos89** [comment]
The [battleground NPC](https://github.com/rathena/rathena/tree/master/npc/battleground) already exist so you can take reference to those. You can also view the [script command documentation](https://github.com/rathena/rathena/blob/master/doc/script_commands.txt) for specific script command usage.
