### ISSUE TITLE
Crash when @reloadmobdb

### ISSUE THREAD

**Issue by cahya1992** [rathena/rathena#5309]
* **rAthena Hash**: 

157392cd1

* **Client Date**: 20180919

* **Server Mode**:  Pre-Re

* **Description of Issue**:  Crash when reloadmobdb 
see this GDB result https://hastebin.com/ayulocidib.pl
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment]
Hastebin link is dead

**Comment by aleos89** [comment]
Closing for now. Can reopen when the dump is produced again.

Tip: just add a code block of the dump rather than hosting it on third party sites so we don’t lose artifacts.
