### ISSUE TITLE
Getgroupitem Eating Items.

### ISSUE THREAD

**Issue by dragonis1701** [rathena/rathena#531]
There is an issue with getgroupitem where it does not place the item on the floor but consumes the item used. 

For example, a player has 100/100 items in their inventory and then getgroupitem is used, the item will not be given. Instead, the item will just be eaten by the command.

With Old Blue Box with getrandgroupitem, if a player has 100/100 items in their inventory and then getrandgroupitem is used, the item will be placed on the floor.

This occurs with weight, as well. If the new item weighs too much for the player to hold, getgroupitem will eat the item and getrandgroupitem will place the item on the floor.

If an item is used with getgroupitem, the item will be consumed even if the item is eaten by the command. Taking away two items from the player.

**Comment by aleos89** [comment]
Need to confirm with @cydh on the proper way this works since he's the one who implemented it.

**Comment by dragonis1701** [comment]
Anyway to figure out how it works without cydh's input?

**Comment by cydh** [comment]
should be fixed now since e1b658e46284d63b3c9d7b81833f2696d1a1dbd3
