### ISSUE TITLE
New Special Pharmacy Potions are missing in the item_db_re.sql

### ISSUE THREAD

**Issue by CyberDevil75** [rathena/rathena#5311]
* **rAthena Hash**: 7c6a9751b44d7340be9d29982c68fcfc870385c3

* **Client Date**: null

* **Server Mode**: Renewal

* **Description of Issue**: The new Special Pharmacy Potions are missing in the item_db_re.sql file... they are only in db/re/item_db.txt updated!
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**: update rathena to last version!
![error](https://user-images.githubusercontent.com/19527283/89796012-669e1680-db29-11ea-97b6-bb7e09773659.png)

**Comment by mazvi** [comment]
If my server item db using txt.. for produce this potion need sql or not?

**Comment by aleos89** [comment]
No. If your server uses TXT you don't need any SQL databases (item, mob, mob_skill).
