### ISSUE TITLE
unique_id & item_check & getequipuniqueid bugs. (:1:)

### ISSUE THREAD

**Issue by anacondaqq** [rathena/rathena#532]
Problem: 
=======
1. unique_id generation for items with unique_id 0 do not work with item_check options. (unique_id generation working fine for new items, but for old items without unique_id generation do not work)
2. item_check options: 1, 2, 4 do not work (3,5,7 too)
3. getequipuniqueid damaged. (check map-server output when you using this script function)

How reproduce:
=============
1. Create any item with @item command for example 5170
2. logout, go to your inventory table, and check unique_id row, you will see generated unique_id.
3. Close your login, char, map servers.
4. update unique_id row to 0
5. set item_check to any number: (1 or 2, or 4, or 3, or 5 or 7)
6. Start login, char, map server
7. The unique_id will not be updated.

I was check sources, and found this function. I hope, example below.

#### Function

```
/*==========================================
 * Checks for unavailable items and removes them.
 *------------------------------------------*/
void pc_check_available_item(struct map_session_data *sd) {
	int i, it;
	char output[256];

	nullpo_retv(sd);

	if( battle_config.item_check&1 ) { // Check for invalid(ated) items in inventory.
		for( i = 0; i < MAX_INVENTORY; i++ ) {
			it = sd->status.inventory[i].nameid;
			
			if (!it)
				continue;
			if (!itemdb_available(it)) {
				sprintf(output, msg_txt(sd, 709), it); // Item %hu has been removed from your inventory.
				clif_displaymessage(sd->fd, output);
				ShowWarning("Removed invalid/disabled item id %hu from inventory (amount=%d, char_id=%d).\n", it, sd->status.inventory[i].amount, sd->status.char_id);
				pc_delitem(sd, i, sd->status.inventory[i].amount, 0, 0, LOG_TYPE_OTHER);
				continue;
			}
			if (!sd->status.inventory[i].unique_id && !itemdb_isstackable(it))
				sd->status.inventory[i].unique_id = pc_generate_unique_id(sd);
		}
	}

	if( battle_config.item_check&2 ) { // Check for invalid(ated) items in cart.
		for( i = 0; i < MAX_CART; i++ ) {
			it = sd->status.cart[i].nameid;
			
			if (!it)
				continue;
			if (!itemdb_available(it)) {
				sprintf(output, msg_txt(sd, 710), it); // Item %hu has been removed from your cart.
				clif_displaymessage(sd->fd, output);
				ShowWarning("Removed invalid/disabled item id %hu from cart (amount=%d, char_id=%d).\n", it, sd->status.cart[i].amount, sd->status.char_id);
				pc_cart_delitem(sd, i, sd->status.cart[i].amount, 0, LOG_TYPE_OTHER);
				continue;
			}
			if (!sd->status.cart[i].unique_id && !itemdb_isstackable(it))
				sd->status.cart[i].unique_id = pc_generate_unique_id(sd);
		}
	}

	if( battle_config.item_check&4 ) { // Check for invalid(ated) items in storage.
		for( i = 0; i < sd->storage_size; i++ ) {
			it = sd->status.storage.items[i].nameid;
			
			if (!it)
				continue;
			if (!itemdb_available(it)) {
				sprintf(output, msg_txt(sd, 711), it); // Item %hu has been removed from your storage.
				clif_displaymessage(sd->fd, output);
				ShowWarning("Removed invalid/disabled item id %hu from storage (amount=%d, char_id=%d).\n", it, sd->status.storage.items[i].amount, sd->status.char_id);
				storage_delitem(sd, i, sd->status.storage.items[i].amount);
				continue;
			}
			if (!sd->status.storage.items[i].unique_id && !itemdb_isstackable(it))
				sd->status.storage.items[i].unique_id = pc_generate_unique_id(sd);
 		}
	}
}
```

### Technical Information
Latest (25.07.2015) rAthena
Mechanic do not matter: all
Packet version do not matter: all
related to: https://github.com/rathena/rathena/issues/479
commit: https://github.com/rathena/rathena/commit/7295bdc925ebe898a3b4f736e538bb8e9ebe165b

Dear developers. Please, take a look, and fix it :1: 
Thank you for your attention. 

P.S. this is critical for live servers with latest updates from rAthena. Because for now after update (51f6465709117dae25c97b0944ada875da667a3f) unique_id start to work again, but only for new items, and we need to generate unique_id for old items without unique_id.

**Comment by aleos89** [comment]
I'll clean this up a bit.

**Comment by anacondaqq** [comment]
Thank you very much, i will wait for this. :watch:
