### ISSUE TITLE
Inter_Athena MYSQL Password Setting Characters Limited

### ISSUE THREAD

**Issue by reunite-ro** [rathena/rathena#5324]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/78676d8a6f5280b858da6cda67b1b0ffeb6beb69

* **Client Date**: 20180620

* **Server Mode**: Renewal

* **Description of Issue**: Cannot use password more than 31 characters in inter_athena.
  * Result: Password that read by emulator limited to 31 characters.
  * Expected Result: If its intended with this maximum limit, then let me know, ill close this issue.
  * How to Reproduce: Try to start emulator and you can see the remaining characters are not included in the error.

**Comment by aleos89** [comment]
That's because that's how big the array is:
```cpp
char char_server_pw[32] = "";
```

@cydh has a PR open from years ago to utilize StrBuf, but now that we support C++ I was wanting to use std::string.
