### ISSUE TITLE
Iteminfo New Potion Issue

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#5328]
* **rAthena Hash**: 3060865

* **Client Date**: 20180620

* **Server Mode**: RENEWAL

* **Description of Issue**: 
  * Result:  Item: 'Ref_T_Potion'/'Golden X'[0] (34695)
  * Expected Result:  Item ID Must be: 100231
  * How to Reproduce:  using command @iteminfo golden x
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by llchrisll** [comment]
I'm not sure why, but the item is for me correct
`100231,Ref_T_Potion,Golden X,0,10,,30,,,,,0xFFFFFFFF,63,2,,,,,,{ sc_start SC_REF_T_POTION,30000,0; },{},{}
`
It even shows it correctly ingame.

**Comment by mazvi** [comment]
yes on my item db is 100231 but if use @iteminfo on game golde x will be show as 34695

**Comment by llchrisll** [comment]
I didn't for me, it showed the correct value tho :I.

**Comment by mazvi** [comment]
Are you using 20180620 or not?

**Comment by aleos89** [comment]
Did you properly apply 3776bfb? Sounds like you are getting an overflow.

**Comment by mazvi** [comment]
solved for msg thanks @aleos89 but why my player cannot produce golden x? this is skill not supported on client 20180620?

**Comment by vstumpf** [comment]
that client does not support 32bit item ids
 PACKETVER_MAIN_NUM >= 20181121 || PACKETVER_RE_NUM >= 20180704 || PACKETVER_ZERO_NUM >= 20181114

**Comment by aleos89** [comment]
As @vstumpf showed, the client you are trying to use doesn't support the new item ID range. You need to update your client or lower all these items below 65k.
