### ISSUE TITLE
Skill: Ground Drift Bug.

### ISSUE THREAD

**Issue by zXemnas** [rathena/rathena#533]
Hello !, I have a problem with this skill mentioned in the header.

Ground Drift element does not change. Besides wanting to modify its damage does not change, chances are it's a common error rathena.

I hope you can help me!.

Video: https://www.youtube.com/watch?v=aWsRNH84Gco

**Comment by cydh** [comment]
`misc` type skill doesn't call `battle_get_weapon_element` that there's ele adjustment there.

**Comment by Playtester** [comment]
The skill is a bit complicated. It should have a "weapon attack" part which is basically doing the same damage as a normal attack would (100% damage, taking element into account). There is also a fixed damage part which is 50*level that is DEF-ignoring and always neutral.

See report here: https://github.com/rathena/rathena/issues/212

**Comment by cydh** [comment]
well, I can figure it.
