### ISSUE TITLE
Cannot Release Spellbook

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#5333]
* **rAthena Hash**: 3060865

* **Client Date**: 20180620

* **Server Mode**: RENEWAL

* **Description of Issue**: 
  * Result: The Spellbook cannot be released
  * Expected Result: Spellbook can release
  * How to Reproduce:  I created a custom item with an id below 64k to make it appear. Initially it worked but after I made a rental (so that items are not lost when used.) now it can't be released at all player, is it possible for someone to spam so that mindslot becomes an error?. My assumption is that because there are stuck in a mindslot, how do you reset a mindslot or clear all saved mindslot?

> 63001,WL_MB_SG,Spell Book (Storm Gust),11,0,,0,,,,,0xFFFFFFFF,63,2,,,,,,{ itemskill "WL_READING_SB_READING",1; },{},{}
> 63002,WL_MB_LOV,Spell Book (Lord of Vermilion),11,0,,0,,,,,0xFFFFFFFF,63,2,,,,,,{ itemskill "WL_READING_SB_READING",2; },{},{}
> 63003,WL_MB_MS,Spell Book (Meteor Storm),11,0,,0,,,,,0xFFFFFFFF,63,2,,,,,,{ itemskill "WL_READING_SB_READING",3; },{},{}
> 63004,WL_MB_DL,Spell Book (Drain Life),11,0,,0,,,,,0xFFFFFFFF,63,2,,,,,,{ itemskill "WL_READING_SB_READING",4; },{},{}
> 63005,WL_MB_JF,Spell Book (Jack Frost),11,0,,0,,,,,0xFFFFFFFF,63,2,,,,,,{ itemskill "WL_READING_SB_READING",5; },{},{}
> 63006,WL_MB_ES,Spell Book (Earth Strain),11,0,,0,,,,,0xFFFFFFFF,63,2,,,,,,{ itemskill "WL_READING_SB_READING",6; },{},{}
> 63007,WL_MB_CR,Spell Book (Crimson Rock),11,0,,0,,,,,0xFFFFFFFF,63,2,,,,,,{ itemskill "WL_READING_SB_READING",7; },{},{}
> 63008,WL_MB_CL,Spell Book (Chain Lightning),11,0,,0,,,,,0xFFFFFFFF,63,2,,,,,,{ itemskill "WL_READING_SB_READING",8; },{},{}
> 63009,WL_MB_CM,Spell Book (Comet),11,0,,0,,,,,0xFFFFFFFF,63,2,,,,,,{ itemskill "WL_READING_SB_READING",9; },{},{}
> 63010,WL_MB_TV,Spell Book (Tetra Vortex),11,0,,0,,,,,0xFFFFFFFF,63,2,,,,,,{ itemskill "WL_READING_SB_READING",10; },{},{}

before this issue happen i also use @reloadskilldb? maybe from this command make the issue?

  * Official Information:
  

* **Modifications that may affect results**: 

import/produce_db.txt

> //-- Golden X <-- GN_S_PHARMACY Lvl, 10 Empty Testtube, 10 Yggdrasilberry, 5 Gold
> 264,63011,29,2497,1,1092,10,607,10,969,5
> //-- Red Herb Activator <-- GN_S_PHARMACY Lvl, 10 Empty Testtube, 45 Red Herb, 5 Yggdrasil Seed
> 265,63012,29,2497,1,1092,10,507,45,608,5
> //-- Blue Herb Activator <-- GN_S_PHARMACY Lvl, 10 Empty Testtube, 15 Blue Herb, 5 Yggdrasil Seed
> 266,63013,29,2497,1,1092,10,510,15,608,5
> //-- Concentrated Red Syrup Potion <-- GN_S_PHARMACY Lvl, 10 Empty Testtube, 10 Empty Potion Bottle, 15 Red Syrup
> 267,63014,29,2497,1,1092,10,1093,10,11621,15
> //-- Concentrated Blue Syrup Potion <-- GN_S_PHARMACY Lvl, 10 Empty Testtube, 10 Empty Potion Bottle, 15 Blue Syrup
> 268,63015,29,2497,1,1092,10,1093,10,11624,15
> //-- Concentrated Golden Syrup Potion <-- GN_S_PHARMACY Lvl, 10 Empty Testtube, 10 Empty Potion Bottle, 15 White Syrup, 10 Yellow Syrup
> 269,63016,29,2497,1,1092,10,1093,10,11623,15,11622,10

import/item_db.txt
> 63011,Ref_T_Potion,Golden X,0,10,,30,,,,,0xFFFFFFFF,63,2,,,,,,{ sc_start SC_REF_T_POTION,30000,0; },{},{}
> 63012,Add_Atk_Potion,Red Herb Activator,0,10,,30,,,,,0xFFFFFFFF,63,2,,,,,,{ sc_start SC_ADD_ATK_DAMAGE,500000,15; },{},{}
> 63013,Add_Matk_Potion,Blue Herb Activator,0,10,,30,,,,,0xFFFFFFFF,63,2,,,,,,{ sc_start SC_ADD_MATK_DAMAGE,500000,15; },{},{}
> 63014,Concentrated_R_P,Concentrated Red Potion,0,10,,2,,,,,0xFFFFFFFF,63,2,,,120,,,{ itemheal rand(655,675),0; },{},{}
> 63015,Concentrated_B_P,Concentrated Blue Potion,0,10,,2,,,,,0xFFFFFFFF,63,2,,,120,,,{ itemheal 0,rand(340,360); },{},{}
> 63016,Concentrated_G_P,Concentrated Gold Potion,0,10,,2,,,,,0xFFFFFFFF,63,2,,,180,,,{ itemheal rand(2730,2750),0; },{},{}

  
  

Update:

i thnk the problem is come from

https://github.com/rathena/rathena/blob/master/src/map/skill.cpp
skill_spellbook(sd, ITEMID_WL_MB_SG + skill_lv - 1);

need configuration maybe on battle conf? for edited number ITEMID_WL_MB_SG so user rAthena if use older client no need modification src

**Comment by aleos89** [comment]
I don't think adding a battle config option here is good. This would mean we have to add this support for all future items that are beyond 65k to support older clients, which will just become a mess. It's 1 line you have to adjust in the enum so even if you get a conflict it's very minimal.

**Comment by mazvi** [comment]
Do you mean enum is on scr/map/itemdb.hpp ?

**Comment by poporing** [comment]
You need to change the id in sources:
search in itemdb.hpp this line
ITEMID_WL_MB_SG						= 100065,
and replace the id by 63001then recompile.

**Comment by mazvi** [comment]
Yes @poporing i have been use this method.. and solved. I just wondered if it was possible to change this num without editing src example like on src config, but no problem . looks like we really have to leave the old client. I hope rAthena also develops a webservice for the guild emblem.
