### ISSUE TITLE
Pain Killer duration is cut short

### ISSUE THREAD

**Issue by LotusRO** [rathena/rathena#5334]
* **rAthena Hash**: 

* **Client Date**: 

 20200401

* **Server Mode**: 

 Renewal

* **Description of Issue**: 
  * Result:  pain killer is set to 120 seconds in the server and has been working fine however after swapping to the 2020 client ( or some rAthena update that this point  but our server still states 120 seconds duration in the skill_db ) the buff icon is at 70 seconds and gets removed after the duration is over obviously meaning it loses 50 seconds extra it should have
  * Expected Result:  the skill should last for 120 seconds and the skill effect icon should show this and be shown this long as well
  * How to Reproduce:  try using pain killer with 20200401 client version and rAthena latest hash.
  * Official Information:
  

* **Modifications that may affect results**: 
   None

**Comment by aleos89** [comment]
I was unable to reproduce this on 0e4b36d. The status icon timer ticked down from 2 minutes just fine.
