### ISSUE TITLE
update item_flag.txt for items New Warlock Spell Books

### ISSUE THREAD

**Issue by idk-whoami** [rathena/rathena#5338]
* **rAthena Hash**: 3060865aa05225882dc55be8414111617adbc69a

* **Client Date**: 20200401

* **Server Mode**: re

* **Description of Issue**: item_flag.txt remove comment for items New Warlock Spell Books
https://github.com/rathena/rathena/blob/master/db/re/item_flag.txt#L1788-L1797

https://ro.gnjoy.com/news/update/View.asp?seq=239&curpage=1

![122404_MT8EN1Lp](https://user-images.githubusercontent.com/60462533/90433746-879cd380-e0f6-11ea-9521-33a8ca7e04e9.gif)

  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by mazvi** [comment]
This mean after double click item not deleted?

**Comment by idk-whoami** [comment]
yes
