### ISSUE TITLE
Freed-data is changed

### ISSUE THREAD

**Issue by blipblopblip** [rathena/rathena#5348]
* **rAthena Hash**: faadc800423fdde8720de3d9f176d76b11c31024

* **Client Date**: 20151104

* **Server Mode**: Pre-Renewal

 

* **Description of Issue**: 
  * Result:  please check the error here https://hastebin.com/ikarajosej.coffeescript
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: The server doesn't have a crash dump file because it didn't crash, the server only got disconnected. 
  

* **Modifications that may affect results**: @vykimo's Battleground, he said that it's not related to the BG so I have to post it here to ask for help.

**Comment by aleos89** [comment]
I would lead to believe this is coming from the mod as no other reports of this nature have come in.

**Comment by Lemongrass3110** [comment]
Probably caused by modifications, since it has been decreased to only the only one remaining in #5448
