### ISSUE TITLE
Izlude Academy NPC

### ISSUE THREAD

**Issue by zeffen** [rathena/rathena#5349]
* **rAthena Hash**: d242c40 

* **Client Date**: 2020-08-19

* **Server Mode**: RE

* **Description of Issue**: The Izlude Academy cache has been updated, but the warps, boards and npc locations have not been updated.
  * Result: Location fixes and missing npc addition.
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by mazvi** [comment]
Yes i think on academy cache must revert back.. because npc not ready
