### ISSUE TITLE
Orc Memory Dungeon

### ISSUE THREAD

**Issue by zeffen** [rathena/rathena#5350]
* **rAthena Hash**: 88b506a

* **Client Date**: 2020-08-19

* **Server Mode**: RE

* **Description of Issue**: Orc Memory Dungeon needs to be upgraded to the new form.
  * Result: https://ro.gnjoy.com/news/event/View.asp?Seq=758
  * Expected Result: https://www.youtube.com/watch?v=JdiMoGjJ5ZI
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Atemo** [comment]
Duplicate https://github.com/rathena/rathena/issues/6459
