### ISSUE TITLE
number of skills that new magic book can read and save

### ISSUE THREAD

**Issue by Surefirer** [rathena/rathena#5356]
* **rAthena Hash**:  latest

* **Client Date**: 

* **Server Mode**: re

* **Description of Issue**: the old magic book can read and save 10 skills, the new magic book can only read and save 7 skills. is this the official change? Both the official update link did not mention this.
https://ro.gnjoy.com/news/update/View.asp?seq=239&curpage=1
https://ro.gnjoy.com/news/notice/View.asp?BBSMode=10001&seq=7140
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by mazvi** [comment]
this isn't a lot of saving skill. but books have different slot capacities.

**Comment by aleos89** [comment]
I don't recall adjusting the memory slots for the spell books. The reason I didn't change it is because I saw no mention of any differences after the update.

I think I also remember testing on kRO and getting pretty much the same numbers as already defined.

**Comment by Surefirer** [comment]
@aleos89 thank you for your explanation.
