### ISSUE TITLE
Mechanic Neutral Barrier issue makes Long Ranged attack miss regardless if they are outside barrier

### ISSUE THREAD

**Issue by Paoly28** [rathena/rathena#536]
Neutral barrier can never cancel attack that never miss IE; Arms Cannon, Cart Cannon, Dragon's Breath , Acid Demonstration.

currently makes all skills miss regardless if they bypass flee/never miss

i also found that this only happens of target is also inside the barrier, if its outside then all incoming attacks from ranged barrier to your target ( if outside barrier) should not miss ! this makes mechanic very weak offensively.

http://irowiki.org/wiki/Neutral_Barrier

https://www.youtube.com/watch?v=90DQ5iO94IE

Good PvP video from bRO

**Comment by cydh** [comment]
> All players/monsters inside Neutral Barrier will also have all their own ranged physical/magical attacks miss on targets **unless the attack cannot miss**. (i.e. magic skills, Acid Bomb, Cart Cannon, etc.)

we'll check this
