### ISSUE TITLE
Vending Bug 2

### ISSUE THREAD

**Issue by blipblopblip** [rathena/rathena#5363]
* **rAthena Hash**: ce42168b0d2d25f66ab8a5fc5e2ef24d988274ae

* **Client Date**: 20151104

* **Server Mode**: Pre-Renewal 

* **Description of Issue**: 
  * Result: Incorrect items and zeny prices that are being vend check the image [here](https://imgur.com/a/r90eIbB)
  * Expected Result: Usually if this is the case, your vend will push through which should be fixed in #4778 apparently, this one pushed through
  * How to Reproduce: When you put up an item for vending after logging in, price it with more than 10m zeny and you will see " Unknown Item" in the notification message, or maybe this one is random. 
  * Official Information:
  

* **Modifications that may affect results**: #4778 70fb039e78de1c953acf332e8824ef5843587f8e

**Comment by aleos89** [comment]
![image](https://user-images.githubusercontent.com/3521753/91867163-53222f00-ec41-11ea-8e2b-1fdc7d774847.png)
![image](https://user-images.githubusercontent.com/3521753/91867322-882e8180-ec41-11ea-907b-9d6277a8a5fc.png)
I had no problems on 1e43c6c using the 20200401 client.

**Comment by AsuraPlop** [comment]
Will you have any modifications outside of rAthenaGitHub? Some vending mod or something? I cannot reproduce the problem to help you.

**Comment by blipblopblip** [comment]
I wasn't able to reproduce this again and no, there's no modifications that could relate to this one. I will be closing this one again until I received a new report. Thank you!
