### ISSUE TITLE
Vending Skill bug

### ISSUE THREAD

**Issue by AsuraPlop** [rathena/rathena#5364]
* **rAthena Hash**: [#129812d](https://github.com/rathena/rathena/commit/129812d6a56b6dd765afd966668b4f986bf0c3b7)

* **Client Date**: 2015-11-04

* **Server Mode**: Pre-Renewal

* **Description of Issue**: 
  * Result: You can place "street stall" on top of another. The first store completely covered.
  * Expected Result: It shouldn't be able to open or place "street stall" on top of another. 
  * How to Reproduce: Simply exit the player visual, walk to the cell, and open a shop.
https://www.youtube.com/watch?v=nWp2CzGgG44

**Comment by aleos89** [comment]
What are your config values for `official_cell_stack_limit` and `custom_cell_stack_limit`?

**Comment by AsuraPlop** [comment]
> What are your config values for `official_cell_stack_limit` and `custom_cell_stack_limit`?

official_cell_stack_limit: 0
custom_cell_stack_limit: 1

**Comment by aleos89** [comment]
Did you also uncomment `#define CELL_NOSTACK` in src/config/core.hpp since you disabled `official_cell_stack_limit`?

**Comment by AsuraPlop** [comment]
> Did you also uncomment `#define CELL_NOSTACK` in src/config/core.hpp since you disabled `official_cell_stack_limit`?

#define OFFICIAL_WALKPATH
//#define CELL_NOSTACK

I do not use the custom, I only had it in 1 by default.
The officer I have it in 0 since, Ex; Assassin with grimtooh does not work, the monsters leave the same cell and it is chaos, also when you want to pick up an item that is on the floor and is next to or behind an npc, it is not picked up if you do not turn around.

**Comment by aleos89** [comment]
This is the reason your players are stacking though, because you set `official_cell_stack_limit` to 0 and you didn't uncomment `CELL_NOSTACK`.

**Comment by AsuraPlop** [comment]
My problem is not that they stack each other, the problem is the Vending skill that runs on top of another vending skill.

**Comment by aleos89** [comment]
That's what I'm explaining. Officially, players aren't supposed to stack and you've disabled the stacking count based on your config change. This results in players doing things like this. You will either need to uncomment that macro if you want to use the custom stack config or put 1 back into the official stack config. Other than that, what's happening is intended.
