### ISSUE TITLE
Other character's disguises fail to update on @refresh

### ISSUE THREAD

**Issue by vstumpf** [rathena/rathena#5365]
* **rAthena Hash**: 998a99fe7

* **Client Date**: 20180620

* **Server Mode**: Pre-re (doesn't matter)

* **Description of Issue**: 
 * Take two players, PlayerA and PlayerB
 * If A uses `@disguise poring`, they show up on B's client as a poring.
 * If B uses `@refresh`, PlayerA still looks like a poring, but when B hovers over A, no info is shown.
![image](https://user-images.githubusercontent.com/6844975/91645232-3e9f2600-e9f8-11ea-9aaf-50d5f85b6e1c.png)

 * If A moves, B will not see them move.
 * If A uses `@refresh`, the B can now see the poring normally.

* **Modifications that may affect results**: 
None

**Comment by Lemongrass3110** [comment]
Somehow this was not closed.

This was fixed by merging #5366 in d158603
