### ISSUE TITLE
Mechanic Arms Cannon target type is wrong ; wrong type of animation and female char gets stuck.

### ISSUE THREAD

**Issue by Paoly28** [rathena/rathena#537]
Mechanic Arms Cannon target type is supposed to be single unit target not ground target and is using a horrible attack animation and should also use the caster's swing rate currently makes the character stuck specially if caster is female making the skill slow even if caster has 100% reduced cast delay and 193 aspd.

Full test from tRO

https://www.youtube.com/watch?v=gN-f2OZJ9_A

**Comment by reigneil** [comment]
http://irowiki.org/wiki/Arm_Cannon
Target: Ground

last week i saw someone in iRO cast this on ground... which is true then?

**Comment by Paoly28** [comment]
it isn't

https://www.youtube.com/watch?v=OBNu8zM6xeE

Cast animation should be similar to Hell's Plant  , No cast = no animation.
