### ISSUE TITLE
Clan System crashing on PRE-RE 

### ISSUE THREAD

**Issue by M45T3Ryu** [rathena/rathena#5376]
* **rAthena Hash**: 36c629e
 

* **Client Date**:  2020-03-04 RagexeRE 

* **Server Mode**:  PRE-RENEWAL

* **Description of Issue**: 
  * Result: No warnings, just crashes when leaving a clan
  * Expected Result: Not crashing?
  * How to Reproduce: I haven't reproduced this but It apparently happens when you leave your clan somehow, I got a picture of the problem right here.
 

* Picture of the problem: 
![118801357_1356796781177132_8631858363599084194_n](https://user-images.githubusercontent.com/2993425/92256316-6ecb4680-ee88-11ea-9655-fc0c8ab278e0.png)

* **Modifications that may affect results**: 
  No source modifications, just Gepard 3.0

**Comment by blipblopblip** [comment]
Hi, your crash report seems incomplete. Reproduce the crash and type `bt full` in GDB.

**Comment by Balferian** [comment]
same problem
![image](https://user-images.githubusercontent.com/16213511/92331251-1a89b780-f07e-11ea-80eb-934842779afa.png)

**Comment by admkakaroto** [comment]
maybe, some problem? https://github.com/rathena/rathena/issues/5390

**Comment by Balferian** [comment]
I think it maybe happen when server kick inactive chars from clan after 14 days. (clan_remove_inactive_days)
When I try to reproduce it and left from clan by myself server don`t crashed.

**Comment by M45T3Ryu** [comment]
> maybe, some problem? #5390

Yeah, same problem.

Players are abusing this to respawn MVP's and reset timers on some stuff, its apparently confirmed now by 3 people

**Comment by admkakaroto** [comment]
@M45T3Ryu any solution man?

**Comment by Balferian** [comment]
@admkakaroto you can disable clans for a time while this crash will be fixed.
Kick players from clans: **UPDATE `char` SET `clan_id` = 0;**
and disbable clan npc **npc/re/other/clans.txt**.

**Comment by reunite-ro** [comment]
I have a few crashing issues a few times daily.

I think related to this issue.

**Comment by Badarosk0** [comment]
I can confirm this crash. I ended up creating another issue and found this one. Would this be only in PRE or RE? I use RE and this crash also occurs with me.
https://github.com/rathena/rathena/issues/5407

Does this PR solve the problem?
https://github.com/rathena/rathena/pull/5204/files

**Comment by mazvi** [comment]
Also crash on Renewal #5828

**Comment by mazvi** [comment]
> @admkakaroto you can disable clans for a time while this crash will be fixed.
> Kick players from clans:
> ![image](https://user-images.githubusercontent.com/16213511/93000031-3c77b400-f52e-11ea-84a5-8c01653858ca.png)
> and disbable clan npc **npc/re/other/clans.txt**.

How about end all SC_CLAN? Because if only removed from clan the SC_CLAN still active
