### ISSUE TITLE
NPC Disappearing

### ISSUE THREAD

**Issue by blipblopblip** [rathena/rathena#5379]
* **rAthena Hash**: faadc800423fdde8720de3d9f176d76b11c31024

* **Client Date**: 20151104a

* **Server Mode**: Pre-Renewal

* **Description of Issue**: 
  * Result: Refer to this video [here](https://youtu.be/ZlINY8IwYY4)
  * Expected Result: 
  * How to Reproduce: It seems like it is related to the `attachrid`, once it is attached successfully, after the script, you will just have to click to a Healer NPC and it will be gone.
```
-	script	ajsdbnajkxdbn	-1,{
OnTest:
	mes "Enter aid.";
	next;
	input .@aid;
	if ( !.@aid || !isloggedin(.@aid) ) {
		mes "Not found or offline.";
		close;
	}
	mes "Attaching..";
	close2;
	attachrid(.@aid);
	dispbottom "You have been attached..";
	end;
 
OnInit:
	bindatcmd "test", strnpcinfo(0)+"::OnTest";
}
```

  * Official Information:
  

* **Modifications that may affect results**: None

**Comment by Patotron** [comment]
I used the script that you propose and the healer that rAthena has in the npc/custom folder. The result is that the NPC never disappears if you only use one account, when you add another account and use the attachrid with the new one, the NPC does disappear when the character that has used the attachrid script (the one proposed in the issue) clicks on the NPC. When using @refresh it reappears so it's just a visual glitch. 

If the character that only receives the attachrid clicks on the NPC, nothing happens, it only happens with the other one.

[Video with one account](https://gyazo.com/7fa4856e867d7d7211b0fbfb736d8109)
[Video with two accounts](https://gyazo.com/0655e8ff19186cf0d2413262307f33bf)

Reproduced with:
rAthena version: e8fcf01
Server Mode: RE and PRE-RE
