### ISSUE TITLE
Old Prontera Npc caused crash server

### ISSUE THREAD

**Issue by Skystar18** [rathena/rathena#5383]
* **rAthena Hash**:  f4003d9e9

* **Client Date**:  2020-04-14aRagexe

* **Server Mode**:  Renewal

* **Description of Issue**: Character was frozen and unable to move then got disconnected.

  * Result: Some times map crashes
  * Expected Result: Map crashes 
  * How to Reproduce:   I'm doing Banquet of Heroes quest. After finishing Room of Consciousness and unlock Invaded Prontera, I went to invaded Pronta map. Near the brigde there is a group of Soldiers who will give me warning when my character gets close them. Then my character got frozen and was unable to move and then got disconnected.

![old prontera](https://user-images.githubusercontent.com/70919453/92419413-f89e3c80-f132-11ea-9b7c-f157d55846dc.PNG)

Sometimes, it causes map server crash. When checking rathena console, I saw the these warning.

![Capture](https://user-images.githubusercontent.com/70919453/92419499-80844680-f133-11ea-8321-4eb2c4374748.PNG)

  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Surefirer** [comment]
it seems like I have the same issue. below is my log:

(09/08/2020 16:30:31) [ Error ] : npc_click: npc_id != 0
(09/08/2020 16:36:32) [ Error ] : npc_click: npc_id != 0
(09/08/2020 16:48:36) [ Error ] : npc_click: npc_id != 0
(09/08/2020 16:49:57) [ Error ] : npc_click: npc_id != 0
(09/08/2020 17:05:54) [ Error ] : npc_click: npc_id != 0
(09/08/2020 17:08:35) [ Error ] : npc_click: npc_id != 0
(09/08/2020 17:08:36) [ Error ] : npc_click: npc_id != 0
(09/08/2020 17:37:54) [ Error ] : intif_parse_Mail_delete: char not found 154235
(09/08/2020 19:07:54) [ Error ] : intif_parse_Mail_delete: char not found 154286
(09/08/2020 21:02:54) [ Error ] : intif_parse_Mail_delete: char not found 154235
(09/08/2020 21:11:52) [ Error ] : Server received crash signal! Attempting to save all online characters!

**Comment by Atemo** [comment]
`npc_click` prevents the player to trigger 2 npcs scripts with dialog at the same time, the crash is likely not from that

**Comment by Skystar18** [comment]
Problem solved with the new update. Thank you.
