### ISSUE TITLE
Doram max aspd

### ISSUE THREAD

**Issue by Angelic234** [rathena/rathena#5384]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/bd90763ffeeca3d3c34bfd9d373f4320e8149d83

* **Client Date**: 

* **Server Mode**: RE

* **Description of Issue**: 
  * Result:  In rathena , Doram/Summoner max aspd is 190, but it can be 192 in KRO's video .
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  
https://www.youtube.com/watch?v=XXTUzKRbj3M
* **Modifications that may affect results**:

**Comment by aleos89** [comment]
It's likely been expanded to 193 at some point.

**Comment by Lemongrass3110** [comment]
Fixed in 12cfe31
