### ISSUE TITLE
Death Penalty EXP Configuration

### ISSUE THREAD

**Issue by reunite-ro** [rathena/rathena#5392]
* **rAthena Hash**: 

* **Client Date**: 20180620

* **Server Mode**: Pre-Renewal

* **Description of Issue**: Does EXP Penalty worked for almost current hash ?
![image](https://user-images.githubusercontent.com/11705163/93016047-d738c700-f5f0-11ea-889c-0b6ec051caed.png)
Ive tried changed to 500 for 5% and still no death penalty.

  * Result: Tried using Novice level 2~3 and no EXP dropped.
  * Expected Result: EXP droppped when death because of EXP Penalty.
  * How to Reproduce: summon or go to any field, let poring kill the character. Check EXP before and after died.
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
```cpp
	if(battle_config.death_penalty_type
		&& (sd->class_&MAPID_UPPERMASK) != MAPID_NOVICE	// only novices will receive no penalty
		&& !sd->sc.data[SC_BABY] && !sd->sc.data[SC_LIFEINSURANCE]
		&& !mapdata->flag[MF_NOEXPPENALTY] && !mapdata_flag_gvg2(mapdata))
```
According to this, Novices don't get an EXP penalty on death.
