### ISSUE TITLE
Map server crash with callstack info

### ISSUE THREAD

**Issue by Surefirer** [rathena/rathena#5394]
* **rAthena Hash**: 634e1b399

* **Client Date**: 20200318

* **Server Mode**: re

* **Description of Issue**: 
  * Result: random map server crash daily
  * Expected Result: 
  * How to Reproduce: I am not able to find a way to reproduce the crash, but my live server crashes once or twice daily. 
  * Official Information:
  

* **Modifications that may affect results**: 
  1. Gepard Shield
  2. Enabled VIP

Call Stack

![1](https://user-images.githubusercontent.com/46170182/93025516-7ccd4580-f5b3-11ea-8414-4549411bea77.JPG)
![2](https://user-images.githubusercontent.com/46170182/93025517-7dfe7280-f5b3-11ea-8a40-81d6acef6c9f.JPG)
![3](https://user-images.githubusercontent.com/46170182/93025518-7f2f9f80-f5b3-11ea-9b88-c575f8a47b15.JPG)
![4](https://user-images.githubusercontent.com/46170182/93025520-80f96300-f5b3-11ea-9117-5adafe0ce1b3.JPG)
![5](https://user-images.githubusercontent.com/46170182/93025522-822a9000-f5b3-11ea-95f1-5d0f76723183.JPG)
![6](https://user-images.githubusercontent.com/46170182/93025524-82c32680-f5b3-11ea-84e1-9ae449736c17.JPG)

**Comment by reunite-ro** [comment]
Might be related to this https://github.com/rathena/rathena/issues/5376
