### ISSUE TITLE
crashfix: adding non-existing map to maps_athena 

### ISSUE THREAD

**Issue by nubspixel** [rathena/rathena#5396]
* **rAthena Hash**: 4bac43435

* **Client Date**:  irrelevant

* **Server Mode**: irrelevant

* **Description of Issue**: 
map-server crash when you add non-existing map (in cache) into name in maps_athena.conf
map-server crash with the error: 
`Exception thrown: read access violation.
info was 0x3CCFFF6. occurred`
map.cpp:3565
```c++
p += sizeof(struct map_cache_map_info) + info->len;
```

* **How to Reproduce**: 
Add random map name in conf/maps_athena.conf
Please do not add map that already exists in map_cache.dat

* **Modifications that may affect results**: 
This may be a small thing, but it would be best if there is a "check" to see if the map name actually exists in the map_cache.dat
Removing the non-existing map name could solve the issue, but the crash does not make any sense for most people.

My work around is to add a check for "empty map name"
find map.cpp:3558
``
```c++
for(i = 0; i < header->map_count; i++) {
		info = (struct map_cache_map_info *)p;

		if( strcmp(m->name, info->name) == 0 )
			break; // Map found

		// Jump to next entry..
		p += sizeof(struct map_cache_map_info) + info->len;
	}
```
replace map.cpp:3558
```c++
for(i = 0; i < header->map_count; i++) {
		info = (struct map_cache_map_info *)p;

		// name exists in maps_athena.conf but not in map_cache.dat -> crash
		if (info->name != NULL && info->name[0] == '\0')
			continue;

		if( strcmp(m->name, info->name) == 0 )
			break; // Map found

		// Jump to next entry..
		p += sizeof(struct map_cache_map_info) + info->len;
	}
```

**Comment by aleos89** [comment]
I haven't delved through the map code, but if you add an index to a map that doesn't exist in the dat won't this allow players to warp to that map and subsequently crash their client?

**Comment by nubspixel** [comment]
Actually, no. the main purpose is to stop it from crashing during map-server start up. not the client itself. Map-server is also smart enough to disable none existing map. 

The reason to do it is just to stop it from crashing during start up. At least this is what I found.

case 1: 
start map-server with default parameters
map-server starts normally

case 2: 
start map-server with non existing map in the map_cache.dat (added only to maps_athena,conf)
map-server crash with the read access error

case3:
start map-server with non existing map in the map_cache.dat (added only to map_index.txt)
map-server starts normally, removing the non-existing map from list (expected behavior)

case4:
start map-server with non existing map in the map_cache.dat (added to both maps_athena.conf and map_index.txt)
map-server crash with the read access error
