### ISSUE TITLE
Ran Homunculus is kept called

### ISSUE THREAD

**Issue by amharfm** [rathena/rathena#5397]
* **rAthena Hash**: 4cd6366134501cf35c744330fde1e86c3cfffe47

* **Client Date**: 20200401

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Failed to execute AM_CALLHOMUN after Homunculus ran (due to 0 intimacy)
  * Expected Result: When embryo is placed in inventory list, AM_CALLHOMUN should work
  * How to Reproduce: Try making Homun runaway, produce another basic embryo, then execute AM_CALLHOMUN for a new one
  * Official Information: -
  

* **Modifications that may affect results**: Maybe some extra SQL line needed on int_homun.cpp to set the Homun's owner hom_id back to 0

**Comment by aleos89** [comment]
I was unable to reproduce this issue. Made a homun, got the intimacy to 0 and it ran. Created another embryo and was able to use Call Homunculus to make a new one.

Tested on 4bac434.

**Comment by amharfm** [comment]
Hmm okay so it's on my edits. Thanks & have a nice day!
