### ISSUE TITLE
Mechanic - Madogear Skills Issues.

### ISSUE THREAD

**Issue by LotusRO** [rathena/rathena#5401]
* **rAthena Hash**: 

* **Client Date**: 

 20200304

* **Server Mode**: 

 renewal

* **Description of Issue**: 
  * Result:  Mechanics skill [Magnetic field] does NOT snare anyone or anything at all but it does lock you in place and drains your SP heavily., Mechanics Skill [Hovering] only avoids traps (excluding Thorn trap for some reason but ankle snare is fine ) but it doesnt avoid any other ground base skills, tested with Pillar of fire, heavens drive and a few others. and it only works if the item catalyst is EQUIPPED, which is wrong, it should only have to be in the inventory.
  * Expected Result:  Magnetic field should snare anyone not in hover state in a 5x5 area around the caster, Hover skill should avoid traps and all other ground based skills while in hover state., also the  catalyst item for Hover skill has to be equipped and not just in your inventory, which is wrong.
  * How to Reproduce:  Download latest rA server, make a mechanic, equip madogear, give yourself all skills and items and test and you'll get the same results as pointed outa bove.
  * Official Information: https://www.divine-pride.net/database/skill/2263 , https://irowiki.org/wiki/Hover, https://www.divine-pride.net/database/skill/2272/magnetic-field, , https://irowiki.org/wiki/Magnetic_Field
  

* **Modifications that may affect results**: 
   None
   None

**Comment by HenryAlvarez12** [comment]
This class is beyond crippled on my server. People literally dont play it because it's that buggy. Sadly my SRC skills aren't good enough. Hope this class gets some love at some point.

**Comment by aleos89** [comment]
For Hover, the description of the skill is very vague. The skill doesn’t block all ground skills. If you have a verifiable source that lists what are blocked then we can add those flags.

The kRO skill description also states the item must be equipped to use the skill.

**Comment by LotusRO** [comment]
@aleos89 "Description : Make Madogear hover over the ground to escape traps and any other magic attacks. "

List of affected skills

    Anklesnare
    Blast Mine
    Claymore Trap
    Deluge
    Electric Walk
    Extreme Vacuum
    Fire Walk
    Flasher
    Freezing Trap
    Gravitational Field
    Land Mine
    Moonslasher
    Quagmire
    Sandman
    Shockwave Trap
    Skid Trap
    Volcano
    Watery Evasion
    Whirlwind
    Windmill

taken from irowiki that i did post a link to in the original post.

**Comment by aleos89** [comment]
Those skills are already set to ignore hovering in rAthena. Just look for `IgnoreHovering` in the skill_db.
