### ISSUE TITLE
Regular Players can't change guild emblem

### ISSUE THREAD

**Issue by Skystar18** [rathena/rathena#5402]
* **rAthena Hash**: f4003d9e9

* **Client Date**: 2020-03-04aRagexe

* **Server Mode**: Renewal

* **Description of Issue**: Regular player can't change guild Emblem
  * Result: After installing Athena Web Service, I tried to change the guild emblem but it only worked with Game Master account. This resulted in regular players can't change the guild emblem for their guilds 

  * Expected Result:  Guild Master can change guild Emblem
  * How to Reproduce: Install Athena Web Service: https://github.com/secretdataz/athena-web-service. Then log in the game with the Game Master account (Group ID = 99)and test the guild emblem. Then log into a regular player account who is Guild Master (Group ID = 0) and test the the emblem. It looks like group ID under 10 can't change the guild emblem for some reasons. They kept getting the below message.

![image](https://user-images.githubusercontent.com/70919453/93287750-eca02380-f79f-11ea-9227-3a7462d57a13.png)

  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Normal members have never been able to change the guild emblem. Any guild related tasks/skills/settings can only be adjusted by the guild master.

**Comment by LotusRO** [comment]
We had the same issue, we fixed this by setting all player accounts to level 10 and removed all priviledges from level 10 ( essentially turning it into a normal player account level ) and that works fine, i'd suggest this if you're not able to solve it in other ways @Skystar18

**Comment by Skystar18** [comment]
@aleos89 Sorry my report wasn't clear enough. I just edited it to make it clearer to the reader.  I logged in as a Game Master account (Group = 99) and I could change the emblem. However, when I logged in as a normal player who is a Guild Master (Group ID = 0), I was unable to change the guild emblem. What setting I need to change to fix this?

@LotusRO Thank you for the tip. I can apply this as a temperately fix :+1:

**Comment by EbilPanda** [comment]
from my investigation what i found out:

the server of secret is so far working out like it should from my perspective:
appaerently the `web_auth_token` in the `login` - table is not updated for normal users on login correctly (it is updated but appaerently its not the one which is then reportet by the client to the server) - for admins this is done in the right way (?!?) 
this is the reason why its working for gms and not for player -> I checked code on the web-service-side and If I disable token check its working... If I'm print out the token and check them on the db -> admin is matching, player not... (both have ofc. `web_auth_token_enabled` -> true) -> somethign is up to the web_token on player accounts :(

does someboday may have the ability to check this? I found this whole thing little bit confusing on this side (I'm not familiar with C syntax)

**Comment by cahya1992** [comment]
someone already solved this issue?

**Comment by aleos89** [comment]
The issue was resolved in @vstumpf's local version (#5731).
