### ISSUE TITLE
Bonus Combo item does not work

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#5404]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/36c629e84141a54a27dbdab69bd2daaac554b043

* **Client Date**: 2020-04-01

* **Server Mode**: RE

* **Description of Issue**: 
  * Result: item bonus combo does not work.
```
25303:25304:25305:25060,{ bonus bCritical,10; }
```

item_db
```
25303,Critical Stone (Garment),Critical Stone (Garment),3,10,,100,,,,,,,,,,,,,{ bonus bCritAtkRate,20; },{},{}
25304,Critical Stone (Upper),Critical Stone (Upper),3,10,,100,,,,,,,,,,,,,{ bonus bCritAtkRate,3; },{},{}
25305,Critical Stone (Lower),Critical Stone (Lower),3,10,,100,,,,,,,,,,,,,{ bonus bCritAtkRate,3; },{},{}
25060,Critical Stone(Middle),Critical Stone(Middle),3,10,,100,,,,,,,,,,,,,{ bonus bCritAtkRate,3; },{},{}
```

  * Expected Result: 
  * How to Reproduce: Use the command: ```@item2 5402 1 1 1 0 25303 25304 25305 25060```
Critical bonus will not be added.

  * Official Information:
  
https://www.divine-pride.net/database/item/25303
* **Modifications that may affect results**:

**Comment by Atemo** [comment]
You are using ETC items (intended?) however the combos only work for equippable items/cards (check from here https://github.com/rathena/rathena/blob/868bdead9e5b33224c1faf03b6d1f63fd25a4255/src/map/pc.cpp#L10263)

**Comment by Atemo** [comment]
I'm closing this, as the combo system has not been designed to handle the item script for etc items.
