### ISSUE TITLE
Char server error when consume mutiple items that have bonus_script 

### ISSUE THREAD

**Issue by Surefirer** [rathena/rathena#5405]
* **rAthena Hash**: cac6121f0

* **Client Date**: 20200318

* **Server Mode**: Re

* **Description of Issue**: The char server will throw an error after you consuming multiple items that have bonus_script in it.
  * Result: 
  * Expected Result: 
  * How to Reproduce: make 3 items as shown below, consume them one by one, then wait 5 mins, char server will throw an SQL error.
1. 23475,Extreme_Potion,Extrem Potion,2,10,,10,,,,0,0xFFFFFFFF,63,2,,,,,,{ specialeffect2 EF_POTION_BERSERK; bonus_script "{ bonus bMaxHPrate,5; bonus bMaxSPrate,5; bonus bCritAtkRate,5; bonus bLongAtkRate,5; bonus bMatkRate,5; bonus bNoCastCancel,0; }",1800,1,1,EFST_INFINITY_DRINK; },{},{}
2. 14886,Limited_Phy_Power_Booster,Power Booster,2,10,,10,,,,0,0xFFFFFFFF,63,2,,,,,,{ specialeffect2 EF_POTION_BERSERK; bonus_script "{ bonus bAtk,30; bonus bMatk,30; bonus bAllStats,10; }",1800,1,1,EFST_FULL_THROTTLE; },{},{}
3. 14766,Limited_Power_Booster,Limited Power Booster,18,10,,10,,,,0,0xFFFFFFFF,63,2,,,,,,{ bonus_script "{ bonus bBaseAtk,30; bonus bMatk,30; bonus2 bAddClass,Class_All,1; bonus bMatkRate,1; bonus bHit,30; bonus bFlee,30; bonus bAspd,1; bonus bUseSPrate,-5; bonus bFixedCastrate,-30; }",1800,1,1; },{},{}
  * Official Information:
  

* **Modifications that may affect results**:  Gepard Shield
  
  
![error](https://user-images.githubusercontent.com/46170182/93545109-7f61cf00-f914-11ea-9f9d-0e97b8f9640e.JPG)

**Comment by Patotron** [comment]
As the objects 23475 and 14886 seem to be custom since I could not find them, for the test I used the objects **14766** (this one appears), **22658** and **22659**.

After using first the object 14766 and then the other two, in the SQL bonus_script table appears only the buff of the first one (14766), and actually after some time in charserver there is an error.

![8b3131791e4d4274e35f66e0af4b899b](https://user-images.githubusercontent.com/73896963/98052888-9f534080-1e37-11eb-9450-710f3927fbd9.png)

Reproduced with:
**rAthena version**: e8fcf01ff
**Server Mode**: RE

**Comment by gen1x8** [comment]
i guess that error related to database table structure. Default table is not to allow duplicate Primary key for ID.
you can try to remove the primary key, duplicate key will be allow to insert data to the table.

edit table structure, or simply run query on your db. it will drop bonus_script table and recreate the table.
`DROP TABLE IF EXISTS `bonus_script`;
CREATE TABLE IF NOT EXISTS `bonus_script` (
  `char_id` int(11) unsigned NOT NULL,
  `script` text NOT NULL,
  `tick` bigint(20) NOT NULL DEFAULT '0',
  `flag` smallint(5) unsigned NOT NULL DEFAULT '0',
  `type` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `icon` smallint(3) NOT NULL DEFAULT '-1',
  KEY `Index` (`char_id`)
) ENGINE=InnoDB;`


And see how it goes.
