### ISSUE TITLE
@autotraders not displaying headgears when server resets

### ISSUE THREAD

**Issue by gidzdlcrz** [rathena/rathena#5408]
* **rAthena Hash**:  Latest

* **Client Date**:  20151104

* **Server Mode**:  Both

* **Description of Issue**: 
  * Result: 
  * Expected Result: Im not really sure if this is a bug. But this is about @autotrade command. When you are on autotrade command and you restart your server, the vendors will not display headgears. Thats upper lower and middle. And also it doesnt display costume. That includes the garment.

  * How to Reproduce: to reproduce. Simply put 1 character to @autotrade. The character should have headgears. Then close your login, char and map server. Re open it again and wait for the autotraders to load back in. Once the trunk loaded the vendors it will not display the headgears.

  * Official Information: well i thought theres something wrong with my trunk. Turns out that the latest pull from git does have the same problem.

* **Modifications that may affect results**:  Nope. Im using latest git.

**Comment by aleos89** [comment]
To my knowledge, I don't think we ever loaded the headgears in with this feature. This would be another addition to the autotrade feature.

**Comment by gidzdlcrz** [comment]
I see @aleos89. Thanks for reproducing tho. :)
