### ISSUE TITLE
SC_DIMENSION1 & 2 doesn't block damage 

### ISSUE THREAD

**Issue by molavian053** [rathena/rathena#5409]
* **rAthena Hash**: cac6121

* **Client Date**: 2020401

* **Server Mode**: Renewal

* **Description of Issue**: Upon creation of 2 spheres (via the skill Advent of Star Emperor)  for damage absorb based on maxSP, damage doesn't get blocked. Also, spheres are not deleted upon receiving damage. It just disappear after a certain time (possibly the sc timer).
  * Result: Spheres unable to block damage based on MaxSP.
  * Expected Result: Should be able to block sphere
  * How to Reproduce: Use the skill in PvP Area and do damage to SJ
  * Official Information: https://ro.gnjoy.com/guide/runemidgarts/skillview.asp?skillid=2586
  

* **Modifications that may affect results**: None

**Comment by synkaito** [comment]
to support your report i asked Sigma on DP forum for the same problem too and these are his replies
![image](https://user-images.githubusercontent.com/71688833/93848483-9faed680-fce4-11ea-95ff-ad154d442e55.png)
![image](https://user-images.githubusercontent.com/71688833/93848510-b8b78780-fce4-11ea-8aea-247026e62015.png)
