### ISSUE TITLE
Rune Knight : Ignition Break Missing Lvl Scaling Bonus

### ISSUE THREAD

**Issue by Paoly28** [rathena/rathena#541]
I've tested Ignition Break's damage at lvl 175 ( 1500% * ( 1+[(blvl-100/100])) = 2625% and should do almost  just as much as stormblast at lvl10 rune mastery  and 136 int ( total of 2600% stormblast damage ) but im just doing 1500% at lvl5 Ignition Break at lvl 175.

*i used Stormblast as a means to measure how much modifier IB has*

here's my test
blvl175 135 total str and 136 total int ( 2600% stormblast modifier )
![screenextaliaro014](https://cloud.githubusercontent.com/assets/8035101/9017317/cd4171da-3808-11e5-9952-b4a170dfd367.jpg)
![screenextaliaro016](https://cloud.githubusercontent.com/assets/8035101/9017318/ce7a5e54-3808-11e5-97d3-dfd76756e8a4.jpg)

and here's my other test
blvl175 135 total str 50 total int ( 1500% stormblast modifier )
![screenextaliaro017](https://cloud.githubusercontent.com/assets/8035101/9017319/d0584bb4-3808-11e5-8208-7c2e0c2c73b3.jpg)
![screenextaliaro018](https://cloud.githubusercontent.com/assets/8035101/9017322/d3ecbbb6-3808-11e5-81c5-c9623b8f3193.jpg)

*my Ignition break test are all tested within the 3x3 radius*
*i used Stormblast as a means to measure how much modifier IB has*

**Comment by reigneil** [comment]
i have a doubt on how it is written in battle.c
celldamage = (skill_lv * celldamage) * (1 + (status_get_lv(src) - 100) / 100);

parenthesis disaster i think.

**Comment by Paoly28** [comment]
missing open parenthesis.

**Comment by Paoly28** [comment]
i think it should be  (skill_lv * celldamage) * (1 + ((status_get_lv(src) - 100) / 100));

**Comment by Paoly28** [comment]
with the formulae above it actually gets reduce considerable lmao .76% multiplier instead of 175%
