### ISSUE TITLE
4th Jobs

### ISSUE THREAD

**Issue by kyurejl** [rathena/rathena#5414]
* **rAthena Hash**: N/A

* **Client Date**: N/A

* **Server Mode**: Renewal

* **Description of Issue**: 4th Jobs: https://www.divine-pride.net/forum/index.php?/topic/4672-kro-fourth-class-jobs-skills-info-and-related-items-updated-16092020/

* **Modifications that may affect results**: N/A

**Comment by LotusRO** [comment]
Considering how rA is at like 16.X, and barely that, i doubt you'll see 4th jobs here within the next year or two xD

**Comment by tuxico** [comment]
i will made it, can you help me?

**Comment by tuxico** [comment]
![Uploading 4thjobs.png…]()

**Comment by MINARA-STUDIO** [comment]
tuxico you pre-code ? haha

**Comment by kyurejl** [comment]
It makes no sense for him to ask for help while being in pre-code yet.

**Comment by tuxico** [comment]
Ok, we will wait for rAthena's Staff.

**Comment by LotusRO** [comment]
Would it not make more sense to work on the truckload of missing things between 4th jobs and current state of rAthena instead? just saying.

**Comment by kyurejl** [comment]
How was there a truckload of lost things between Soul Reaper/Star Emperor and current state of rAthena when they did?

**Comment by tuxico** [comment]
![ss1](https://user-images.githubusercontent.com/5794122/94383190-b5bdfc00-0115-11eb-9619-93c1dd5c3735.png)
Actually i working hard in this skill fix, because 3rds and 2nds jobs had "masks" for inherit skills

**Comment by llchrisll** [comment]
In my opinion, 4th Jobs can still wait until rAthena catches up to the proper patch when they got released,
but as getting official information and implementing takes a while, it's gonna take some time.
So +1 to LotusRO.

**Comment by kyurejl** [comment]
Why are you discussing whether or not to put this on? This discussion is useless, they will do whatever they want regardless of your opinion.

**Comment by tuxico** [comment]
I tthink about create a branch for 4th jobs initial commits...
I stopped in masks bug.

**Comment by darhylism** [comment]
where can i get sprites for the 4th job and skill icons to use for development?
