### ISSUE TITLE
Items bonus bug

### ISSUE THREAD

**Issue by AsuraPlop** [rathena/rathena#5415]
* **rAthena Hash**: [#129812d](https://github.com/rathena/rathena/commit/129812d6a56b6dd765afd966668b4f986bf0c3b7)

* **Client Date**: 2015-11-04

* **Server Mode**: Pre-Renewal

* **Description of Issue**: 
  * Result: Items: 5203, 5664 and 5548 bad bonus. 
  * Expected Result: 5664 and 5548 its a low and middle hat item, they should not be refined, and they are refined. 
5203 bad bonus item according to "pre-renewal item description" It gives 25 more speed and should give 5

* **Modifications that may affect results**: 

5203,Tongue_Mask,Smiling Mask,4,20,,200,,2,,0,0xFFFFFFFF,7,2,513,,0,0,253,{ bonus bSpeedRate,**5**; },{},{}
5664,Filir_Wing,Filir's Pinions,4,20,,100,,1,,0,0xFFFFFFFF,7,2,512,,70,**0**,595,{ bonus bAspdRate,2; bonus bCastRate,-2; },{},{}
5548,Scarlet_Rose,Scarlet Rose,4,20,,100,,0,,0,0xFFFFFFFF,7,2,1,,50,**0**,534,{ bonus bLuk,1; },{},{}

**Comment by aleos89** [comment]
The `Condition EFFECTHaste 9999 100` for Tongue_Mask is the same as `bonus bSpeedRate,25;`

**Comment by AsuraPlop** [comment]
> The `Condition EFFECTHaste 9999 100` for Tongue_Mask is the same as `bonus bSpeedRate,25;`

thanks for the comment!

**Comment by AsuraPlop** [comment]
@aleos89 I think the "Scarlet Rose" too
https://github.com/rathena/rathena/blob/master/db/pre-re/item_db.txt#L2731
