### ISSUE TITLE
Tomb of Honor: Monster skills don't exist.

### ISSUE THREAD

**Issue by saya9200** [rathena/rathena#5416]
* **rAthena Hash**: cac6121f0406e8f25faf333bc8cedcb4c9e81db6

* **Client Date**: 2020

* **Server Mode**: re 

  * Official Information:
  I sadly don't know the names of the skills they use but they use a loooooooooooooot of skills on kRO videos that they dont use at all over here. They are looking like 3rd job skills.

An example would be ignition break from seyren. We dont have that skill in our skill database. or any of them.
I feel like we got a very "easy" version of tomb of honor compared to kRO

**Comment by aleos89** [comment]
Fixed in [424e05d](https://github.com/rathena/rathena/commit/424e05d8f748ebbf88b7a0c5bf167bffb52bac5b).
