### ISSUE TITLE
Suffragium does not reduce variable cast time.

### ISSUE THREAD

**Issue by Zer0Human** [rathena/rathena#5418]
* **rAthena Hash**:  0da05e29c

* **Client Date**:  2020-04-01

* **Server Mode**:  Renewal

* **Description of Issue**: 
  * Result: Suffragium reduces neither fix nor variable cast time
  * Expected Result: Suffragium should reduce the variable cast time by 45%.

**Comment by kyurejl** [comment]
45% is a old value, now is 20% btw.

**Comment by aleos89** [comment]
As @kyurejl stated, it was changed in the [mass skill update for 1st, 2nd, and transcendent classes](ro.gnjoy.com/news/notice/View.asp?BBSMode=10001&seq=7033&curpage=21).
