### ISSUE TITLE
Need update item 16033, 21011, 28101

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#5420]
* **rAthena Hash**: latest

* **Client Date**: not related

* **Server Mode**: renewal

* **Description of Issue**: need update item according to item info divine pride item id 16033, 21011, 28101
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by kyurejl** [comment]
that part in specific: 
Usable By: Mechanic
to
Usable By: Rune Knight, Mechanic, Arch Bishop, Royal Guard, Geneticist, Sura
