### ISSUE TITLE
4th Jobs

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#5427]
* **rAthena Hash**: Irrelevant
* **Client Date**: 2020-09+++
* **Server Mode**: RE
* **Description of Issue**: Implementation of the 4th classes.
* **Divine-Pride**: https://www.divine-pride.net/forum/index.php?/topic/4672-kro-fourth-class-jobs-skills-info-and-related-items-updated-16092020/

- [ ] Implement new jobs.
- [ ] Update item_db.
- [ ] Update Exp Table.
- [ ] New Level Base 250.
- [ ] New AP System.
- [ ] New Status System.

New Exp Table:
![2142369127_EXPtable png 2bf40aa0861958a2501a4ca3a1b95f8c](https://user-images.githubusercontent.com/6227618/94877129-0f813780-0430-11eb-8722-90c57b2a3f1a.png)

**Comment by Lemongrass3110** [comment]
Fixed in 7556453
