### ISSUE TITLE
Changes the Adoramus skill property to Neutral if user consumer Ancilla.

### ISSUE THREAD

**Issue by tumemmac** [rathena/rathena#5430]
rAthena Hash: https://github.com/rathena/rathena
Client Date: 2020-04-01
Server Mode: Renewal
Description of Issue:
If user consumes Ancilla, changes the "Adoramus" skill property to neutral for the Ancilla duration.

Result:
Official Information:
https://ro.gnjoy.com/guide/runemidgarts/skillview.asp?lineseq=6&skillid=2040

**Comment by aleos89** [comment]
Looks like this was part of the balancing in the new [skill bundle](https://www.divine-pride.net/forum/index.php?/topic/3723-kro-jobs-improvement-project/page/7/&tab=comments#comment-7644).

**Comment by tumemmac** [comment]
Yep.
