### ISSUE TITLE
item bonus bAspdRate not working

### ISSUE THREAD

**Issue by Ichitux** [rathena/rathena#5434]
* **rAthena Hash**: 0b8d80ba63afa5484c606466987107dc4e5b0b0e
* **Client Date**:  2020-03-04RagexeRE
* **Server Mode**:  Renewal
* **Description of Issue**:  Every item in item_db_re with expected Bonus Aspd Rate (%) not working and only giving 1 aspd.
  * Result: When I try to set an aspd rate % the server only gives you 1 single point instead of calculate the correct one.
  * Expected Result: For example, if you have 180 aspd, 10% is 18 of aspd.
  * How to Reproduce: Tested in last GitHub repo and pull.
  * Official Information: N/C

* **Modifications that may affect results**: 
* Renewal + VIP System.

**Comment by Balferian** [comment]
There are no error.
Aspd formula: 
aspd = 156 + floor(sqrt((1^2/2) + (1^2/5))/4 + (0*1/200) + 0)
Bonus formula:
aspd = 156 + round((190 - 156) * (**ASPD Bonus modificator**/100))

**Comment by Ichitux** [comment]
I see... so then it's all good, if it's the official kRO Aspd formula, nothing more to add. Closed then
