### ISSUE TITLE
[BUG] SR_GENTLETOUCH_CURE & SC_SHADOWFORM [BUG]

### ISSUE THREAD

**Issue by tmav94** [rathena/rathena#544]
These skills "Gentletouch_cure" and "Shadow Form" are bugged.

The first skill can heal Emperium HP and the second aren't disabling with AL_RUWACH and MER_SIGHT.

**Comment by Paoly28** [comment]
tmav all form of detection cancels shadow form but isn't 100% chance.

**Comment by aleos89** [comment]
There is no documentation on GT - Cure not healing Emperiums.
Ruwatch and Sight have a chance of cancelling Shadow Formation, as @Paoly28 stated.
