### ISSUE TITLE
ItemID 525,526

### ISSUE THREAD

**Issue by kyurejl** [rathena/rathena#5444]
* **rAthena Hash**: N/A

* **Client Date**: N/A

* **Server Mode**: Renewal

* **Description of Issue**:

* **Modifications that may affect results**:

**Comment by Atemo** [comment]
Sources?
The values on rAthena for theses items are the same in our aegis data, and KRO description seems to give similar values.
For example the value given by the description for ID 501, `HP 를 45 가량 회복 시켜 준다` (Recover about 45 HP) is similar to our item script `itemheal rand(45,65),0;`.
