### ISSUE TITLE
Memory-freed error when using GDB

### ISSUE THREAD

**Issue by blipblopblip** [rathena/rathena#5448]
* **rAthena Hash**: faadc800423fdde8720de3d9f176d76b11c31024

* **Client Date**: 20151104

* **Server Mode**: Pre-Re

* **Description of Issue**: 
  * Result: Memory Freed is showing in first @reloadscript when using GDB in `./configure`
![image](https://user-images.githubusercontent.com/63345357/95755481-0e28f800-0cd7-11eb-97da-0d4c6f67c398.png)

  * Expected Result: 
  * How to Reproduce: Configure the server with GDB, the first @reloadscript will show the memory freed error and the second one onwards will not show the memory freed error. 
  * Official Information:  I tried wiping all the scripts in custom_scripts.conf and it doesn't show the error but when I put back all my npc/scripts, it will show. Is it possible for npc/scripts to affect this? Or something is not right aside from npc/script? 
  

* **Modifications that may affect results**:

**Comment by sgsilva** [comment]
Here have same problem!

**Comment by blipblopblip** [comment]
> Here have same problem!

Really? Can you show it here as well?

**Comment by aleos89** [comment]
If you can determine which of your scripts is doing this it would help. This doesn't really provide enough info into the cause.

**Comment by blipblopblip** [comment]
> If you can determine which of your scripts is doing this it would help. This doesn't really provide enough info into the cause.

Here's the script that's causing it [link ](https://pastebin.com/KcgcH6yR)

Maybe there's a modification in my src that could affect this which is weird because the script is really a basic one and I don't remember any src modifications that could affect it.

**Comment by zdurexz** [comment]
@aleos89 The wisdom found often comes up as @reloadscript

**Comment by Patotron** [comment]
I tried the above mentioned script, used @reloadscript many times and never received the same error. Have you tried an unmodified version of rAthena to see if you get the same error?

**Comment by aleos89** [comment]
```
next;
mes "[ Freebies ]";
mes "I will now warp you to your next destination.";
getitem 61200,1;
getitem 61201,1;
getitem 61202,1;
getitem 61203,1;
getitem 61204,1;
getitem 61205,1;
getitem 569,200;
getitem 13041,1;
getitem 1639,1;
getitem 1381,1;
getitem 1742,1;
warp "new_2-3",95,27;
savepoint "new_2-3",95,27;
end;
```
The fault might be at this point. You wrap the player in the middle of a mes and also attempt to assign a save point. I didn’t test but usually a call go warp should be one of the last things you’d do. So it would looks like:
```
next;
mes "[ Freebies ]";
mes "I will now warp you to your next destination.";
getitem 61200,1;
getitem 61201,1;
getitem 61202,1;
getitem 61203,1;
getitem 61204,1;
getitem 61205,1;
getitem 569,200;
getitem 13041,1;
getitem 1639,1;
getitem 1381,1;
getitem 1742,1;
savepoint "new_2-3",95,27;
close2;
warp "new_2-3",95,27
end;
```
This way the script can properly close and then just warp the player and end. It won’t try to attempt to do anything after a player is warped which usually makes a player lose attachment to a NPC. I think you had another warp case like this also.

**Comment by Lemongrass3110** [comment]
Unable to reproduce with the given script and information.
Most likely caused by a custom source modification or a script that has not been shared.
