### ISSUE TITLE
Overbrand attack formula got rollback to do much damage?

### ISSUE THREAD

**Issue by reigneil** [rathena/rathena#545]
i checked the file battle.c and i found out that the formula for Overbrand is goes back to its glory days.
is this intended? or do i miss something important here...
http://irowiki.org/wiki/Overbrand
at level 5 it deals only 1000% pierce and 500% swing.
while in our formula this does not reflect to it:
		case LG_OVERBRAND:
			skillratio += -100 + 400 * skill_lv + ((sd) ? pc_checkskill(sd,CR_SPEARQUICKEN) * 50 : 0);
			RE_LVL_DMOD(100);
			break;
		case LG_OVERBRAND_BRANDISH:
			skillratio += -100 + 300 * skill_lv + status_get_str(src) + status_get_dex(src);
			RE_LVL_DMOD(100);
			break;
		case LG_OVERBRAND_PLUSATK: // Only Piercing and Swing damage get RE_LVL_DMOD bonus damage
			skillratio += -100 + 200 * skill_lv + rnd()%90 + 10;
			break;

**Comment by Paoly28** [comment]
at level 5 it deals (1000% pierce + ( 50* skill level of spear quicken ) and additional 75% at lvl 175 for 2625% modifier

**Comment by cydh** [comment]
yes, u're missing skill Rebalancing

**Comment by reigneil** [comment]
@cydh
since you said post-balance here's the list of royal guard skill after post-balance:
https://docs.google.com/document/pub?id=1zRSj5xLn9tZHxFDnXrPrTbbiYTlTU_yowFbzEh5n3I4
Overbrand
Variable Cast Time: 0.5 second
Global Skill Delay: 2 seconds
Knockback: (2 + 1 * Skill Level) cells
Deals Pierce Damage to targets up to 7 cells infront of the Caster.
= ATK [{(Skill Level x 200) + (Spear Quicken Skill Level x 50)} x Caster’s Base Level / 100] %
Deals Swing Damage to targets in 5x2 cell infront of the Caster.
= ATK [{(Skill Level x 100) + (Caster’s STR + DEX)} x Caster’s Base Level / 100] %
Deals additional knockback damage.
= ATK [(Skill Level x 100) + Random number between (10 ~ 100)] %

here's the topic about the nerf:
http://forums.irowiki.org/showthread.php?t=76535&highlight=overbrand&page=10
Huge Overbrand Nerf (I wonder why this wasn't in the patch notes)
From 2000% - 1500%
Down to 1000% - 500%
credit: Frost

skill description change from 2000% down to 1000% default kRO description of skilldescript.lub

**Comment by Paoly28** [comment]
yeah it's 1000% + level scaling and SQ10 bonus >.> i dunno where you get that OB's 1st hit is flat 1000%

**Comment by aleos89** [comment]
Seems this information is incorrect, as per Rytech:

> +Updated the damage formula's to THE REAL OFFICIAL formula.
> -2011 balance document lies about the formula.
> -I fully tested out the formula I extracted and it matches exactly with
> -what I saw on iRO's official test server. The only thing not confirmed
> -official is the random added damage on LG_OVERBRAND_PLUSATK's formula.
> -Will confirm that part later.

So this is working as it should.
