### ISSUE TITLE
Severe Rainstorm skill damage explosion when equip instruments/whips

### ISSUE THREAD

**Issue by Surefirer** [rathena/rathena#5450]
* **rAthena Hash**: 8385162fd

* **Client Date**: 20200401

* **Server Mode**: RE

* **Description of Issue**: Use Improve Concentration skill right after use Severe Rainstorm skill, the severe rainstorm damage will explosion if you use element arrow or the same element arrow as the monster.

![skillbug](https://user-images.githubusercontent.com/46170182/96046936-2741be00-0e29-11eb-9a02-b31f18e5fdb1.gif)

  * Result: 
  * Expected Result: the damage should remain the same if you cast improve concentration after you cast severe rainstorm skill.

![skillbugNor](https://user-images.githubusercontent.com/46170182/96047351-cd8dc380-0e29-11eb-99c7-9cbc10752bc1.gif)

  * How to Reproduce: equip arrow of shadow (item#1767), then `@monster 1719`. use improve concentration after you cast severe rainstorm skill, the damage increases a lot. I tried different element arrow, they all affect. You can see in the video below. If you equip steel arrow(item#1753), then the damage does not affect by improve concentration skill.
  * Official Information:
  

* **Modifications that may affect results**: no mod. I use clean Ra to test.
  
  

Video: https://www.youtube.com/watch?v=SN5vf8yakfY

**Comment by aleos89** [comment]
What are the stats of your player? Because Improve Concentration increases AGI and DEX, both being the stats that Severe Rainstorm uses for it's damage calculation. I was doing like 3k-5k damage to Detale with all stats (130) at base level 200.

**Comment by Surefirer** [comment]
> What are the stats of your player? Because Improve Concentration increases AGI and DEX, both being the stats that Severe Rainstorm uses for it's damage calculation. I was doing like 3k-5k damage to Detale with all stats (130) at base level 200.

Hello, please see the stats below.

![stats](https://user-images.githubusercontent.com/46170182/96168238-56ae0480-0ed5-11eb-85a2-ac09c0ad95f9.JPG)

**Comment by aleos89** [comment]
I still can't reproduce the jump in stats.
![image](https://user-images.githubusercontent.com/3521753/96170682-e5c91580-0ef1-11eb-80cc-c3b2c64c7164.png)

Something is wrong that you're getting such high +stat (to the right). But those would explain why your damage is so high.

**Comment by Surefirer** [comment]
> I still can't reproduce the jump in stats.
> ![image](https://user-images.githubusercontent.com/3521753/96170682-e5c91580-0ef1-11eb-80cc-c3b2c64c7164.png)
> 
> Something is wrong that you're getting such high +stat (to the right). But those would explain why your damage is so high.

Please see the video below:

https://www.youtube.com/watch?v=kqCSz5pK1Q4&feature=youtu.be

when you use element arrow, the damage will be increased differently, but when you use normal arrow like steel arrow, the damage does not increase.

**Comment by Surefirer** [comment]
ok, I just tested when you use bow, it is normal. but when you use guitar, it will reproduce the issue, I will post video in 10 mins.

**Comment by Surefirer** [comment]
> I still can't reproduce the jump in stats.
> ![image](https://user-images.githubusercontent.com/3521753/96170682-e5c91580-0ef1-11eb-80cc-c3b2c64c7164.png)
> 
> Something is wrong that you're getting such high +stat (to the right). But those would explain why your damage is so high.

Hello, Please see the video below, it shows both using bow and guitar. when use bow, the damage did not change, but when use guitar, the dam increase. you need to increase your atk in order to see the difference. If you use all stats (130) with no equipment, the dam will only increase a little bit, but you can still tell it's increasing.

https://www.youtube.com/watch?v=L46fVhOSFgw&feature=youtu.be

**Comment by Surefirer** [comment]
Please see another video below which can help you to reproduce the issue easily. equip stone arrow( because monster Amon Ra is ground element. the '@monster 1511'. then try bow and guitar.

https://youtu.be/D9VHvxd0GzA

**Comment by aleos89** [comment]
This looks like something custom you have. You equipped those unknown items and I'm sure one of those has some bonus in it that's affecting the overall damage of the player. Unless I'm missing something, I still can't reproduce any behavior like that (without those custom equipment).

**Comment by Surefirer** [comment]
> This looks like something custom you have. You equipped those unknown items and I'm sure one of those has some bonus in it that's affecting the overall damage of the player. Unless I'm missing something, I still can't reproduce any behavior like that (without those custom equipment).

https://www.youtube.com/watch?reload=9&v=4d78sCNXxMw&feature=youtu.be

**Comment by Surefirer** [comment]
Can someone confirm this bug? Please.

**Comment by Surefirer** [comment]
This video shows use bow, guitar and Ahura Mazdah(#item 2199) only, no custom items. Use Stone Arrow. Clean RA no mod. If you make your atk higher to do 1m damage, the damage will explode to over 5m when you cast Improve Concentration after cast Severe Rainstorm. I don't know what you equip to make atk higher besides customs items for the test purpose.

Video link: https://youtu.be/kKcxmdTb2L4

**Comment by airei** [comment]
I can't reproduce the any result, was using fresh rAthena.
did You customized your server?

![image](https://user-images.githubusercontent.com/25481955/96208438-b0770300-0f97-11eb-861b-19f941e94948.png)

**Comment by Surefirer** [comment]
> I can't reproduce the any result, was using fresh rAthena.
> did You customized your server?
> 
> ![image](https://user-images.githubusercontent.com/25481955/96208438-b0770300-0f97-11eb-861b-19f941e94948.png)

Use mvp, don't use dummy. Try what I showed in the video.

**Comment by airei** [comment]
tried different mob, first one detale (large/shadow) got no significance difference with dummy (large/normal).

**Comment by airei** [comment]
![image](https://user-images.githubusercontent.com/25481955/96210185-98a17e00-0f9b-11eb-982a-1f69952af5e4.png)

**Comment by Surefirer** [comment]
1. item: bow(#1701), Guitar(#1908), stone arrow(#1756)

2. Use item #1599 Angra Manyu script into bow(#1701) and guitar(#1908).

`1701,Bow,Bow,5,1000,,500,15,,5,3,0x000A0848,63,2,34,1,4,1,11,{ bonus bAllStats,50; bonus bBaseAtk,3300; bonus bMatkRate,200; bonus2 bHPDrainRate,1000,100; bonus2 bSPDrainRate,1000,20; bonus bHealPower,200; bonus2 bAddClass,Class_All,100; skill "WZ_STORMGUST",10; Skill "WZ_METEOR",10; Skill "WZ_VERMILION",10; skill "GM_SANDMAN",1; bonus bVariableCastrate,-100; bonus bFixedCastrate,-100; },{},{}`

`1908,Guitar_,Guitar,5,47000,,900,142,,1,1,0x00080000,63,1,2,3,27,1,13,{ bonus bAllStats,50; bonus bBaseAtk,3300; bonus bMatkRate,200; bonus2 bHPDrainRate,1000,100; bonus2 bSPDrainRate,1000,20; bonus bHealPower,200; bonus2 bAddClass,Class_All,100; skill "WZ_STORMGUST",10; Skill "WZ_METEOR",10; Skill "WZ_VERMILION",10; skill "GM_SANDMAN",1; bonus bVariableCastrate,-100; bonus bFixedCastrate,-100; },{},{}`

3. Equip Guitar(#1908) and stone arrow(#1756), then `@monster 1511`, cast Severe Rainstorm first, then quickly cast Improve Concentration, do this couple of times. 
![2](https://user-images.githubusercontent.com/46170182/96216906-4a0dc880-0f36-11eb-8488-ae1d3f94086b.JPG)

4. Equip bow(#1701) and  stone arrow(#1756), then `@monster 1511`, cast Severe Rainstorm first, then quickly cast Improve Concentration, do this couple of times. 
![1](https://user-images.githubusercontent.com/46170182/96217066-b4bf0400-0f36-11eb-9be1-4358ae0e08f6.JPG)

Video Link: https://youtu.be/Kvy0uNQp8v0

**Comment by Surefirer** [comment]
same set up above but using an arrow of shadow. then `@monster 1876` LORD_OF_DEATH.

![1](https://user-images.githubusercontent.com/46170182/96218989-b7235d00-0f3a-11eb-83fc-72d75292b108.JPG)

Video: https://youtu.be/SUN2-Ug3_-4

**Comment by airei** [comment]
> 1. item: bow(`#1701`), Guitar(`#1908`), stone arrow(`#1756`)
> 2. Use item `#1599` Angra Manyu script into bow(`#1701`) and guitar(`#1908`).
> 
> `1701,Bow,Bow,5,1000,,500,15,,5,3,0x000A0848,63,2,34,1,4,1,11,{ bonus bAllStats,50; bonus bBaseAtk,3300; bonus bMatkRate,200; bonus2 bHPDrainRate,1000,100; bonus2 bSPDrainRate,1000,20; bonus bHealPower,200; bonus2 bAddClass,Class_All,100; skill "WZ_STORMGUST",10; Skill "WZ_METEOR",10; Skill "WZ_VERMILION",10; skill "GM_SANDMAN",1; bonus bVariableCastrate,-100; bonus bFixedCastrate,-100; },{},{}`
> 
> `1908,Guitar_,Guitar,5,47000,,900,142,,1,1,0x00080000,63,1,2,3,27,1,13,{ bonus bAllStats,50; bonus bBaseAtk,3300; bonus bMatkRate,200; bonus2 bHPDrainRate,1000,100; bonus2 bSPDrainRate,1000,20; bonus bHealPower,200; bonus2 bAddClass,Class_All,100; skill "WZ_STORMGUST",10; Skill "WZ_METEOR",10; Skill "WZ_VERMILION",10; skill "GM_SANDMAN",1; bonus bVariableCastrate,-100; bonus bFixedCastrate,-100; },{},{}`
> 
> 1. Equip Guitar(`#1908`) and stone arrow(`#1756`), then `@monster 1511`, cast Severe Rainstorm first, then quickly cast Improve Concentration, do this couple of times.
>    ![2](https://user-images.githubusercontent.com/46170182/96216906-4a0dc880-0f36-11eb-8488-ae1d3f94086b.JPG)
> 2. Equip bow(`#1701`) and  stone arrow(`#1756`), then `@monster 1511`, cast Severe Rainstorm first, then quickly cast Improve Concentration, do this couple of times.
>    ![1](https://user-images.githubusercontent.com/46170182/96217066-b4bf0400-0f36-11eb-9be1-4358ae0e08f6.JPG)
> 
> Video Link: https://youtu.be/Kvy0uNQp8v0
> 
> CLEAN RA, NO MODS.

I think it's because you put angra manyu on it
literaly it's not because the bow/violin and or the arrow...
also that item unobtainable...

**Comment by Surefirer** [comment]
> > 1. item: bow(`#1701`), Guitar(`#1908`), stone arrow(`#1756`)
> > 2. Use item `#1599` Angra Manyu script into bow(`#1701`) and guitar(`#1908`).
> > 
> > `1701,Bow,Bow,5,1000,,500,15,,5,3,0x000A0848,63,2,34,1,4,1,11,{ bonus bAllStats,50; bonus bBaseAtk,3300; bonus bMatkRate,200; bonus2 bHPDrainRate,1000,100; bonus2 bSPDrainRate,1000,20; bonus bHealPower,200; bonus2 bAddClass,Class_All,100; skill "WZ_STORMGUST",10; Skill "WZ_METEOR",10; Skill "WZ_VERMILION",10; skill "GM_SANDMAN",1; bonus bVariableCastrate,-100; bonus bFixedCastrate,-100; },{},{}`
> > `1908,Guitar_,Guitar,5,47000,,900,142,,1,1,0x00080000,63,1,2,3,27,1,13,{ bonus bAllStats,50; bonus bBaseAtk,3300; bonus bMatkRate,200; bonus2 bHPDrainRate,1000,100; bonus2 bSPDrainRate,1000,20; bonus bHealPower,200; bonus2 bAddClass,Class_All,100; skill "WZ_STORMGUST",10; Skill "WZ_METEOR",10; Skill "WZ_VERMILION",10; skill "GM_SANDMAN",1; bonus bVariableCastrate,-100; bonus bFixedCastrate,-100; },{},{}`
> > 
> > 1. Equip Guitar(`#1908`) and stone arrow(`#1756`), then `@monster 1511`, cast Severe Rainstorm first, then quickly cast Improve Concentration, do this couple of times.
> >    ![2](https://user-images.githubusercontent.com/46170182/96216906-4a0dc880-0f36-11eb-8488-ae1d3f94086b.JPG)
> > 2. Equip bow(`#1701`) and  stone arrow(`#1756`), then `@monster 1511`, cast Severe Rainstorm first, then quickly cast Improve Concentration, do this couple of times.
> >    ![1](https://user-images.githubusercontent.com/46170182/96217066-b4bf0400-0f36-11eb-9be1-4358ae0e08f6.JPG)
> > 
> > Video Link: https://youtu.be/Kvy0uNQp8v0
> > CLEAN RA, NO MODS.
> 
> I think it's because you put angra manyu on it
> literaly it's not because the bow/violin and or the arrow...
> also that item unobtainable by official mean. aside gm creation...

If it's because angra manyu, please explain why two weapon with the same bouns, but different type, the bow did not increase the damage but the guitar/violin does.

**Comment by HenryAlvarez12** [comment]
How about you dont use angra manyu for testing purposes?! Thats like the first time I see someone here trying to prove a point using angra manyu lol

**Comment by Surefirer** [comment]
> How about you dont use angra manyu for testing purposes?! Thats like the first time I see someone here trying to prove a point using angra manyu lol

I have already did, and provide video above.

**Comment by Surefirer** [comment]
no customs items, no gm weapon, and shield. All types of equipment for testing are official items and obtainable in the game.
![1](https://user-images.githubusercontent.com/46170182/96292679-70674e80-0f9e-11eb-8842-09043ff991f3.JPG)
![2](https://user-images.githubusercontent.com/46170182/96292683-72311200-0f9e-11eb-97c4-4a8c69a96c6f.JPG)
![3](https://user-images.githubusercontent.com/46170182/96292687-73623f00-0f9e-11eb-8f8d-394eb7714eb8.JPG)
![4](https://user-images.githubusercontent.com/46170182/96292692-74936c00-0f9e-11eb-83c7-e6a3ca698395.JPG)

https://youtu.be/vZc-sTAy9M0

**Comment by aleos89** [comment]
`bonus bAllStats,50; bonus bBaseAtk,3300; bonus bMatkRate,200; bonus2 bAddClass,Class_All,100;`
These bonuses from Angra Manyu increase your overall attack. The video you linked to (titled "Bug report 05") has a vast difference in ATK between the Bow and the Crimson Violin.

```cpp
		case WM_SEVERE_RAINSTORM_MELEE:
			//ATK [{(Caster DEX + AGI) x (Skill Level / 5)} x Caster Base Level / 100] %
			skillratio = (status_get_dex(src) + status_get_agi(src)) * skill_lv / 5;
			if (wd->miscflag&4) // Whip/Instrument equipped
				skillratio += 100; // !TODO: What's the weapon bonus?
			RE_LVL_DMOD(100);
			break;
```
Keep in mind there is a small bonus for using a Whip/Instrument with Severe Rainstorm, although the official value is unconfirmed. The increase you're experiencing seems highly exaggerated for a `+100%` bonus. Are you sure you have no other modifications source side that are affecting your status calculations?

**Comment by Surefirer** [comment]
> `bonus bAllStats,50; bonus bBaseAtk,3300; bonus bMatkRate,200; bonus2 bAddClass,Class_All,100;`
> These bonuses from Angra Manyu increase your overall attack. The video you linked to (titled "Bug report 05") has a vast difference in ATK between the Bow and the Crimson Violin.
> 
> ```c++
> 		case WM_SEVERE_RAINSTORM_MELEE:
> 			//ATK [{(Caster DEX + AGI) x (Skill Level / 5)} x Caster Base Level / 100] %
> 			skillratio = (status_get_dex(src) + status_get_agi(src)) * skill_lv / 5;
> 			if (wd->miscflag&4) // Whip/Instrument equipped
> 				skillratio += 100; // !TODO: What's the weapon bonus?
> 			RE_LVL_DMOD(100);
> 			break;
> ```
> 
> Keep in mind there is a small bonus for using a Whip/Instrument with Severe Rainstorm, although the official value is unconfirmed. The increase you're experiencing seems highly exaggerated for a `+100%` bonus. Are you sure you have no other modifications source side that are affecting your status calculations?

Please see my last post.

**Comment by HenryAlvarez12** [comment]
https://youtu.be/vZc-sTAy9M0?t=134
that indeed looks very weird. 

If you use Improve Concentration while WM_SEVERE_RAINSTORM_MELEE its damage gets quadrupled. Does it also happen with ONLY a bow equipped? for example with 1701 and nothing else?

**Comment by Surefirer** [comment]
This video shows using different element arrows on both bow and instrument. 

When equipping a bow, all elements arrow behave normally.

When equipping an instrument, only the Neutral arrow behaves normal, all other elements arrows will increase damage when fist cast Severe Rainstorm skill, then quickly cast  Improve Concentration skill. But the element == monster's element has the most increased damage.

Be patient，watch the video, and test, you will see what I mean.

https://youtu.be/sy2NxDzyXGM

**Comment by Surefirer** [comment]
> https://youtu.be/vZc-sTAy9M0?t=134
> that indeed looks very weird.
> 
> If you use Improve Concentration while WM_SEVERE_RAINSTORM_MELEE its damage gets quadrupled. Does it also happen with ONLY a cheap ass violin equipped? for example with 1901 and nothing else?

It affects all Whip/Instruments. Again, I am using clean rathena that cloned from git, no mods. I am crying.
