### ISSUE TITLE
Spell Fist damage will gradually decrease

### ISSUE THREAD

**Issue by OriginRO** [rathena/rathena#5451]
* **rAthena Hash**: be3aee7f7

* **Client Date**: 2020-03-04

* **Server Mode**: RENEWAL

* **Description of Issue**: Spell Fist(skillid:2445) damage will gradually decrease
  * Result: 
![1602624616484](https://user-images.githubusercontent.com/46036150/95919299-eec9c200-0ddf-11eb-9401-f8f3669cce81.gif)
  * Expected Result: 
![1602624767324](https://user-images.githubusercontent.com/46036150/95919294-ecfffe80-0ddf-11eb-8466-3b6d8b6a1be7.gif)

  * How to Reproduce: Use Skill: Spell Fist
  * Official Information: No

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
I was unable to reproduce any issue testing on 3115a1d. The damage dropped once my SP ran out.
