### ISSUE TITLE
If map-serv load before char-server, char-server crash.

### ISSUE THREAD

**Issue by lukasrmattos** [rathena/rathena#5456]
* **rAthena Hash**:  8385162

* **Client Date**:  2018-06-21

* **Server Mode**:  Renewall

* **Description of Issue**: 
  * Result:  When I clean all my db files and map-cache to use rAthena without nothing, the map-server load before char-server and char-server.
  * Expected Result:  No crash.

* **Modifications that may affect results**: 
Clear all database to make map-server load very fast.

I fixed changing this:

`void chlogif_on_ready(void)
{
	int i;

	chlogif_check_shutdown();

	//Send online accounts to login server.
	chlogif_send_acc_tologin(INVALID_TIMER, gettick(), 0, 0);

	// if no map-server already connected, display a message...
	ARR_FIND( 0, ARRAYLENGTH(map_server), i, map_server[i].fd > 0 && map_server[i].map[0] );
	if( i == ARRAYLENGTH(map_server) )
		ShowStatus("Awaiting maps from map-server.\n");
}`

To

`void chlogif_on_ready(void)
{
	int i;

	chlogif_check_shutdown();

	//Send online accounts to login server.
	chlogif_send_acc_tologin(INVALID_TIMER, gettick(), 0, 0);

	if (map_server[0].map.size() == 0)
		return;

	// if no map-server already connected, display a message...
	ARR_FIND( 0, ARRAYLENGTH(map_server), i, map_server[i].fd > 0 && map_server[i].map[0] );
	if( i == ARRAYLENGTH(map_server) )
		ShowStatus("Awaiting maps from map-server.\n");
}`

But maybe there is a better approach.

**Comment by Daegaladh** [comment]
This was already fixed in bd90763ffeeca3d3c34bfd9d373f4320e8149d83
