### ISSUE TITLE
Madogear not visible to other players

### ISSUE THREAD

**Issue by LotusRO** [rathena/rathena#5457]
* **rAthena Hash**: 

* **Client Date**: 

 20200304

* **Server Mode**: 

 Renewal

* **Description of Issue**: 
  * Result:  we've noticed that ( we re a small population server and even less players who play mechanic and use madogear ) that it seems taht madogear is no longer shown for other players when worn by someone, the player itself will see the madogear suit but nobody else
  * Expected Result: 
  * How to Reproduce:  latest rAthena, make a mechanic, slap on madogear suit, login with another account and see if you can see it, we can not
  * Official Information: it should be displayed as far as  we know ( as this would change gameplay in woe for example etc )
  

* **Modifications that may affect results**: 
   we're very low on edits as we're trying to be close to official server so nothing that comes to mind.

**Comment by RO-GM06** [comment]
![grafik](https://user-images.githubusercontent.com/72987269/96276678-9e1aba80-0fd3-11eb-931e-0a77a986350f.png)

**Comment by aleos89** [comment]
This is because the newer clients don't use an option anymore, but a status change (see #5081).
