### ISSUE TITLE
atcommand doesn't read spaces or "two-word commands"

### ISSUE THREAD

**Issue by HenryAlvarez12** [rathena/rathena#5466]
* **rAthena Hash**: 323db7e6618b53d4c2c2f0ddfe9b4b5709becf7b

* **Client Date**: 20200403

* **Server Mode**:  RE

* **Description of Issue**: atcommand doesn't read spaces.

```
prontera,155,181,5	script	Sample	4_F_KAFRA1,{
	doevent "channel_setting_main::OnTalk";
}

-	script	channel_setting_main	-1,{
	
	OnInit:
		setarray .channel_list_name$, "#main", "#support";
		setarray .channel_list$, "#main", "#support";
		
		.channel_size = getarraysize(.channel_list$);
		end;
	
	OnTalk:
		mes "Hello "+strcharinfo(0);
		mes "Select the Chat Channel you wish to be in.";
		for (.@i = 0; .@i < .channel_size; .@i++)
			.@menu$ = .@menu$ + .channel_list_name$[.@i] + (#CHANNEL_SETTINGS & (1 << .@i) ? "[On]":"[Off]")  + (1 >> .@i) + ":";
		.@i = select(.@menu$) - 1;
		if (#CHANNEL_SETTINGS & (1 << .@i)) 
			#CHANNEL_SETTINGS -= (1 << .@i);
		else 
			#CHANNEL_SETTINGS |= (1 << .@i);
		mes "Setting updated.";
		close;
	
	OnPCLoginEvent:
		// sleep2 1000;
		while (.@i < .channel_size) {
			if (#CHANNEL_SETTINGS & (1 >> .@i))
				atcommand "@channel leave "+.channel_list$[.@i];
			.@i++;
		}
		end;

}
```

`atcommand "@channel leave "+.channel_list$[.@i];`

`@channel leave `
is not being executed because there is a space between channel and leave.

**Comment by Lemongrass3110** [comment]
Please dont use @ outside of code quotes. You tag possible users with this.

**Comment by HenryAlvarez12** [comment]
My bad, changed it. 
@ channel leave "+.channel$[.@i];

works perfectly fine on hercules. No idea why it doesn't work here.

**Comment by Lemongrass3110** [comment]
I do not see where you set `.@size2`. So basically the script can never go into that for loop.
If that would work on Hercules I would rather create an issue over there, because that is certainly not intended.

**Comment by HenryAlvarez12** [comment]
> 
> 
> I do not see where you set `.@size2` and/or `.@i`. So basically the script can never go into that for loop.
> If that would work on Hercules I would rather create an issue over there, because that is certainly not intended.

my bad once again, i added the wrong script.


```
prontera,155,181,5	script	Sample	4_F_KAFRA1,{
	doevent "channel_setting_main::OnTalk";
}

-	script	channel_setting_main	-1,{
	
	OnInit:
		setarray .channel_list_name$, "#main", "#support";
		setarray .channel_list$, "#main", "#support";
		
		.channel_size = getarraysize(.channel_list$);
		end;
	
	OnTalk:
		mes "Hello "+strcharinfo(0);
		mes "Select the Chat Channel you wish to be in.";
		for (.@i = 0; .@i < .channel_size; .@i++)
			.@menu$ = .@menu$ + .channel_list_name$[.@i] + (#CHANNEL_SETTINGS & (1 << .@i) ? "[On]":"[Off]")  + (1 >> .@i) + ":";
		.@i = select(.@menu$) - 1;
		if (#CHANNEL_SETTINGS & (1 << .@i)) 
			#CHANNEL_SETTINGS -= (1 << .@i);
		else 
			#CHANNEL_SETTINGS |= (1 << .@i);
		mes "Setting updated.";
		close;
	
	OnPCLoginEvent:
		// sleep2 1000;
		while (.@i < .channel_size) {
			if (#CHANNEL_SETTINGS & (1 >> .@i))
				atcommand "@channel leave "+.channel_list$[.@i];
			.@i++;
		}
		end;

}
```

**Comment by rye305** [comment]
After seeing this, I also wanted to add Channel Control (login settings)

Can confirm that he wont leave #global or in this case #main.

**Comment by Lemongrass3110** [comment]
```
-	script	test1234	-1,{

OnPCLoginEvent:
	sleep2 1500;
	atcommand "@channel leave " + #main;
	end;
}
```

This is a wrong script again. You used the # outside of the string.
This means you will use the (numeric) account variable `#main`.
Since you probably will not have set that to any value the resulting command will be `@channel leave 0`.

**Comment by rye305** [comment]
> 
> 
> ```
> -	script	test1234	-1,{
> 
> OnPCLoginEvent:
> 	sleep2 1500;
> 	atcommand "@channel leave " + #main;
> 	end;
> }
> ```
> 
> This is a wrong script again. You used the # outside of the string.
> This means you will use the (numeric) account variable `#main`.
> Since you probably will not have set that to any value the resulting command will be `@channel leave 0`.

Would you mind explaining how to make this work? It looks like this script used to work 2 years ago according to an rathena post by emistry.

https://pastebin.com/RCqBbTc1

**Comment by Lemongrass3110** [comment]
```
-	script	test1234	-1,{

OnPCLoginEvent:
	sleep2 1500;
	atcommand "@channel leave #main";
	end;
}
```

**Comment by HenryAlvarez12** [comment]
Sorry homie. exactly there is the problem. It does not work and he does not leave #main. 

here https://pastebin.com/JdkWDu4z
Apply this to your channels.conf

and use the script you provided 
```
-	script	test1234	-1,{

OnPCLoginEvent:
	sleep2 1500;
	atcommand "@channel leave #main";
	end;
}
```

**Comment by rye305** [comment]
does not work

**Comment by Lemongrass3110** [comment]
Working as intended.

Taken from atcommand.cpp:
`ACMD_DEFR(channel,ATCMD_NOSCRIPT),`

This means that this command is not usable inside scripts.

See the related issue that caused us blocking it #1342

**Comment by sader1992** [comment]
@HenryAlvarez12
you can use this, I made it a while ago(not sure if it would work on the latest rathena) , maybe it's a good idea to allow existing functionality in atcommand to the script commands later, but for now you can use this

```cpp
BUILDIN_FUNC(join_channel)
{
	TBL_PC *sd;
	if (!script_charid2sd(3, sd)) {
		st->state = END;
		return SCRIPT_CMD_FAILURE;
	}
	char pass[64];
	pass[0] = '\0';
	const char* channel = script_getstr(st,2);
	return channel_pcjoin(sd, (char*)channel,pass);
}
BUILDIN_FUNC(leave_channel)
{
	TBL_PC *sd;
	if (!script_charid2sd(3, sd)) {
		st->state = END;
		return SCRIPT_CMD_FAILURE;
	}
	const char* channel = script_getstr(st,2);
	return channel_pcleave(sd, (char*)channel);
}
```

```cpp
BUILDIN_DEF(join_channel,"s?"),
BUILDIN_DEF(leave_channel,"s?"),
```

**Comment by rye305** [comment]
> 
> 
> @HenryAlvarez12
> you can use this, I made it a while ago(not sure if it would work on the latest rathena) , maybe it's a good idea to allow existing functionality in atcommand to the script commands later, but for now you can use this
> 
> ```c++
> BUILDIN_FUNC(join_channel)
> {
> 	TBL_PC *sd;
> 	if (!script_charid2sd(3, sd)) {
> 		st->state = END;
> 		return SCRIPT_CMD_FAILURE;
> 	}
> 	char pass[64];
> 	pass[0] = '\0';
> 	const char* channel = script_getstr(st,2);
> 	return channel_pcjoin(sd, (char*)channel,pass);
> }
> BUILDIN_FUNC(leave_channel)
> {
> 	TBL_PC *sd;
> 	if (!script_charid2sd(3, sd)) {
> 		st->state = END;
> 		return SCRIPT_CMD_FAILURE;
> 	}
> 	const char* channel = script_getstr(st,2);
> 	return channel_pcleave(sd, (char*)channel);
> }
> ```
> 
> ```c++
> BUILDIN_DEF(join_channel,"s?"),
> BUILDIN_DEF(leave_channel,"s?"),
> ```

I've added it, but how to proceed? I don't know what to do with it. The script remains the same, it does not work after adding this.

**Comment by sader1992** [comment]
```cs
-	script	CHLEAVE	-1,{
OnCommand:
	if(!.@atcmd_numparameters)
		callsub L_Help;

	.@c1$ = strtolower(.@atcmd_parameters$[0]);
	.@c2$ = strtolower(.@atcmd_parameters$[1]);

	if(inarray(.a$,.@c1$) == -1){
		callsub L_Help;
	}
	
	if((.@ndx = inarray(.chan$,.@c2$)) != -1){
		.@c$ = "#" + .@c2$;
		if(.@c1$  == "join"){
			CHANNELSMANAGAR[.@ndx] = false;
			join_channel(.@c$);
			message strcharinfo(0),"[Channel Manager]: You have Joined " + .@c2$ + " Channel.";
		}else if(.@c1$  == "leave"){
			CHANNELSMANAGAR[.@ndx] = true;
			leave_channel(.@c$);
			message strcharinfo(0),"[Channel Manager]: You have Left " + .@c2$ + " Channel.";
		}else{
			callsub L_Help;
		}
	}else{
		message strcharinfo(0),"[Channel Manager]: Invalid channel name.";
		callsub L_Help;
	}
	end;

L_Help:
	for(.@i =0;.@i<getarraysize(.chan$);.@i++){
		if(CHANNELSMANAGAR[.@i]){
			message strcharinfo(0),"[Channel Manager]: You are not in " + .chan$[.@i] + " Channel!";
		}
	}
	
	message strcharinfo(0),"[Channel Manager]: @c join <channel name>";
	message strcharinfo(0),"[Channel Manager]: @c leave <channel name>";
	message strcharinfo(0),"[Channel Manager]: Channels: 'global' 'support' 'trade' 'ally' 'map'";
	message strcharinfo(0),"[Channel Manager]: Example: @c leave trade";
end;

OnPCLoginEvent:
	for(.@i =0;.@i<getarraysize(.chan$);.@i++){
		if(CHANNELSMANAGAR[.@i]){
			.@c$ = "#" + .chan$[.@i];
			leave_channel(.@c$);
		}
	}
end;


OnInit:
	setarray .chan$,"global","support","trade","ally","map";
	setarray .a$,"join","leave";
	bindatcmd("c",strnpcinfo(3)+"::OnCommand",0,99);
end;
}
```

**Comment by rye305** [comment]
> 
> 
> ```cs
> -	script	CHLEAVE	-1,{
> OnCommand:
> 	if(!.@atcmd_numparameters)
> 		callsub L_Help;
> 
> 	.@c1$ = strtolower(.@atcmd_parameters$[0]);
> 	.@c2$ = strtolower(.@atcmd_parameters$[1]);
> 
> 	if(inarray(.a$,.@c1$) == -1){
> 		callsub L_Help;
> 	}
> 	
> 	if((.@ndx = inarray(.chan$,.@c2$)) != -1){
> 		.@c$ = "#" + .@c2$;
> 		if(.@c1$  == "join"){
> 			CHANNELSMANAGAR[.@ndx] = false;
> 			join_channel(.@c$);
> 			message strcharinfo(0),"[Channel Manager]: You have Joined " + .@c2$ + " Channel.";
> 		}else if(.@c1$  == "leave"){
> 			CHANNELSMANAGAR[.@ndx] = true;
> 			leave_channel(.@c$);
> 			message strcharinfo(0),"[Channel Manager]: You have Left " + .@c2$ + " Channel.";
> 		}else{
> 			callsub L_Help;
> 		}
> 	}else{
> 		message strcharinfo(0),"[Channel Manager]: Invalid channel name.";
> 		callsub L_Help;
> 	}
> 	end;
> 
> L_Help:
> 	for(.@i =0;.@i<getarraysize(.chan$);.@i++){
> 		if(CHANNELSMANAGAR[.@i]){
> 			message strcharinfo(0),"[Channel Manager]: You are not in " + .chan$[.@i] + " Channel!";
> 		}
> 	}
> 	
> 	message strcharinfo(0),"[Channel Manager]: @c join <channel name>";
> 	message strcharinfo(0),"[Channel Manager]: @c leave <channel name>";
> 	message strcharinfo(0),"[Channel Manager]: Channels: 'global' 'support' 'trade' 'ally' 'map'";
> 	message strcharinfo(0),"[Channel Manager]: Example: @c leave trade";
> end;
> 
> OnPCLoginEvent:
> 	for(.@i =0;.@i<getarraysize(.chan$);.@i++){
> 		if(CHANNELSMANAGAR[.@i]){
> 			.@c$ = "#" + .chan$[.@i];
> 			leave_channel(.@c$);
> 		}
> 	}
> end;
> 
> 
> OnInit:
> 	setarray .chan$,"global","support","trade","ally","map";
> 	setarray .a$,"join","leave";
> 	bindatcmd("c",strnpcinfo(3)+"::OnCommand",0,99);
> end;
> }
> ```

perfect, thank you!

**Comment by HenryAlvarez12** [comment]
working! thanks sader
