### ISSUE TITLE
Blacksmith Platinum Skill Greed Vanishes due to gear that gives same skill

### ISSUE THREAD

**Issue by WindsorGaming** [rathena/rathena#5468]
* **rAthena Hash**: 

* **Client Date**:  20200304

* **Server Mode**: Renewal

 

* **Description of Issue**: 
  * Result:  Basically, if you have dnoe the Blacksmith platinum quest for Greed and equip a bravery bag, then unequip it, the skill turns gray as if you've never done the platinum quest at all, it only comes back when you re-equip the bag
  * Expected Result:  The skill would still be there even upon removing the bravery bag if the quest has been completed by said character.
  * How to Reproduce:  make a whitesmith / blacksmith, do the platinum skill, equip bbag, remove bbag, skill is gone from the SKILL TREE.
  * Official Information:
  

* **Modifications that may affect results**: 
   None
   None

**Comment by Akkarinage** [comment]
Can you please update your issue text to follow the template.

Can you also provide these settings from your conf/import/battle_conf.txt (or conf/battle/player.conf):
```
quest_skill_learn: no
quest_skill_reset: no
```

I'm sure they probably have no effect on your issue, but worth ruling them out for testing purposes.

**Comment by aleos89** [comment]
I'm unable to reproduce this on 55ca799.
