### ISSUE TITLE
getguildname OnInit resulting null

### ISSUE THREAD

**Issue by javirst** [rathena/rathena#5469]
* **rAthena Hash**: 323db7e6618b53d4c2c2f0ddfe9b4b5709becf7b

* **Client Date**: any

* **Server Mode**: pre-re (any)

* **Description of Issue**: 
  * Result:  getguildname OnInit resulting null when Server start
  * Expected Result: getguildname return the guild name
  * How to Reproduce:  make Script OnInit event getguildname
  * Official Information: -

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment]
The guild data is not loaded yet when OnInit is called.

Delay your OnInit script by using sleep and combine it with:
```
*requestguildinfo <guild id>{,"<event label>"};

This command requests the guild data from the char server and merrily continues
with the execution. Whenever the guild information becomes available (which
happens instantly if the guild information is already in memory, or later, if it
isn't and the map server has to wait for the char server to reply) it will run
the specified event as in a 'donpcevent' call.
```
