### ISSUE TITLE
Server received Crash Signal

### ISSUE THREAD

**Issue by saya9200** [rathena/rathena#5476]
* **rAthena Hash**: f28019a7986321fd8fa537af6864d48d9e4c092e

* **Client Date**: 20200304

* **Server Mode**: re

* **Description of Issue**: 
Logging in on this "player" character causes this. This started happening after I updated to the latest version of rAthena. Cant explain it. The server then crashes after logging in one more time with the message "Server Recieved Crash Signal" **This only happens when logging in 1 character -> the Char: "Player"**
![grafik](https://user-images.githubusercontent.com/70844554/97066646-3eb24100-15b7-11eb-859d-3174d2a5af5a.png)

this is script.cpp
![grafik](https://user-images.githubusercontent.com/70844554/97066715-e92a6400-15b7-11eb-90a3-7fbc93323910.png)

* **Modifications that may affect results**: 
Lapine UI
Refine UI cydh

another modification was 
https://github.com/rathena/rathena/issues/5466#issuecomment-713081757
I used it, but removed it after I received this error but the error kept showing up even after removing all related to this.

**Comment by saya9200** [comment]
![grafik](https://user-images.githubusercontent.com/70844554/97067116-ba61bd00-15ba-11eb-90b2-817048b121b2.png)
now this. everything was fine before I updated. I really cant explain whats going on.

**Comment by saya9200** [comment]
edit:

**Comment by 2Bnier** [comment]
These issues that you posted are the exact issues that's happening on my server as well. 20180620, Pre-re. Seems like the combo db effects is the root of all these errors, Let's wait for the devs to get this fixed.

**Comment by saya9200** [comment]
![grafik](https://user-images.githubusercontent.com/70844554/97068159-601a2980-15c5-11eb-8e8f-f1dfd69560a6.png)
![grafik](https://user-images.githubusercontent.com/70844554/97068162-6d371880-15c5-11eb-8fb6-0b2b828cc898.png)

**Comment by HenryAlvarez12** [comment]
Happening over here aswell. Good that you found the root of the issue @saya9200 as I was freaking out for the past 4 hours. I Couldnt figure out what it was.

**Comment by saya9200** [comment]
credits to @ro-gm06 
I was desperate and asked him for help.. he found the issue.

**Comment by ganonDX** [comment]
This is currently happening on my server. I have no way to apply a previous update as I cloned a fresh copy of rA and then applied all my stuff from scratch. This is one of those high-priority issues, but still didn't get love after all this time :/ I currently have around 40 active players and it crashes the moment the server goes up and people start to log in and out.. They're really mad xD

**Comment by 2Bnier** [comment]
Cloned latest hash f28019a and tried on localhost just to make sure there's really a problem. Equipped card Combos Rideword and Waste Stove. Map server really crashes. Temporary workaround to prevent server crash on your live server is to comment all combos in item_combo_db.txt until devs fixes it.
![image](https://user-images.githubusercontent.com/73376486/97082213-a362af80-163a-11eb-83ac-470c2d4362eb.png)

**Comment by vstumpf** [comment]
This also happens when unequipping combos.
