### ISSUE TITLE
Map Server Crashes

### ISSUE THREAD

**Issue by pooher3** [rathena/rathena#5477]
* **rAthena Hash**: 

* **Client Date**: 2018-06-20

* **Server Mode**:  Renewal

* **Description of Issue**:  Map Server crashes when starting server in the new Rathena master build both windows and linux
  * Result: 
  * Expected Result: Server should load map if we use **yes** user_sql_db of inter_athena_config file.
  * How to Reproduce: This issue occurs when we change the below line to "yes", in inter_athena_config file inside config folder  // Use SQL item_db, mob_db and mob_skill_db for the map server? (yes/no)   use_sql_db: yes. If  we change it to **no** the server is loading. 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment]
Has already been addressed in #5477 by @aleos89

**Comment by pooher3** [comment]
@Lemongrass3110  @aleos89 ,What actually should I do in my code to fix this error?
