### ISSUE TITLE
RK_DRAGONBREATH/RK_DRAGONBREATH_WATER issue.

### ISSUE THREAD

**Issue by reigneil** [rathena/rathena#548]
does this new formula for Dragon Breath change to work with % damage card?
http://irowiki.org/wiki/Dragon_Breath
what i've read about it is only range card "archer skel card" works with it and not % damage card "hydra card".
so this must be...
//    0x08 - Skill ignores caster's % damage cards (misc type always ignores)

**Comment by Paoly28** [comment]
http://irowiki.org/wiki/Dragon_Breath

RK Dragon breath at wiki is updated after the 175/60 update the wiki for DB is reliable

Notes :
The damage is affected by Demi Human, Ranged, or Elemental/Property reduction/addition items (this is after level 175 update)

(taken from irowiki)

**Comment by RagnarokNova** [comment]
Ziu disagrees with it. When asked about it recently, he said the behavior on his most recent DB video is still up to date in kRO.

**Comment by reigneil** [comment]
@Paoly28 
i think you miss this info noted by irowiki...
Notes

    The damage is affected by Demi Human, Ranged, or Elemental/Property reduction/addition items (this is after level 175 update)
    Example with new damage formula:

        Current HP: 50000
        Max SP: 2000
        Dragon Breath Skill level: 10
        Base level: 150
        Dragon Training level: 5
        Ranged Damage Modifiers: 71% (4x Archer Skeleton carded weapon gives 40%, 120 DEX with Temporal Dex Boots gives 5%, Fallen Angel Wings enchanted with EA3 EA3 EA4 gives 20%, and Fallen Angel Wings give 6% ranged damage bonus for having 120 DEX). If the target has ranged reduction modifiers, it would be part of this calculation.
        Elemental Modifier: 125% vs. Undead 1 Property (target). If the target has Fire property reduction modifiers, it would be part of this calculation.
        Racial Modifiers: 30% Demi-Human reduction from target wearing Thara Frog-carded shield

Damage = [(50000 ÷ 50) + (2000 ÷ 4)] × (10 × 150 ÷ 150) × (95 + 5 × 5)% × (100 + 71)% x (125)% x (100 - 30)% = 26,932.50

what irowiki mentioned is Racial modifier are for reduction only. see the formula.

**Comment by Paoly28** [comment]
Also i noticed something, Should Dragon's Breath be affected by Def ? from my test it is affected and brocca/icepick bypasses it.

**Comment by Paoly28** [comment]
https://m.youtube.com/watch?v=fM5HSYgaEk8 Full test from hayroh, stated here that it does indeed get affected by modifiers as such , but it does not benefit from hydra , glorious or skeleton worker as it does not have weapon or equip atk in it's formula. Read vid description.

**Comment by MrAntares** [comment]
Connecting issue
https://github.com/rathena/rathena/issues/834

**Comment by secretdataz** [comment]
No longer valid.
