### ISSUE TITLE
Issue with SQL files.

### ISSUE THREAD

**Issue by ganonDX** [rathena/rathena#5485]
* **rAthena Hash**: 99e75b07bca299123be4fd8b2ac5f22849993252

* **Server Mode**: re

* **Description of Issue**: 
I was wondering if the SQL tables are working as intended? I've added these to my SQL (fresh SQL starting from scratch)
![grafik](https://user-images.githubusercontent.com/73390762/97115368-b33fc980-16f6-11eb-8dd7-edafa2d875ed.png)
First of all, flux wouldn't display any of the items (while it was working just fine for years using the old itemSQL files.) 
Second: The structure looks really messy to me in MySQL 

![grafik](https://user-images.githubusercontent.com/73390762/97115477-40831e00-16f7-11eb-9f4f-a7666eb6817e.png)
Item_db has some usables inside it.
item_db_re has equips
item_db2 is a mix of every type of item
item_db2_re is the exact same as item_db2 but has more columns.

I really don't understand these new SQL tables or how to make them work.

Edit:
Deleted all item related tables -> Added item_db2_re.sql -> then added item_db_re_usable.sql -> then added item_db_re_etc.sql -> then added item_db_re_equip.sql

and at the end there is only equip inside the table item_db_re

Edit2:
Looks like everytime I run one of the 3 SQL tables, the other one gets overwritten and deleted. Basically, applied equip table -> then applied useable table = deletes equip entries and adds useable item entries.

Edit3: Monster tables work just fine (the normal old ones) also being displayed in flux.

**Comment by Lemongrass3110** [comment]
The problem you describe is because the table gets deleted and recreated with every file.
This is solved in #5478.

For flux you need to use the files in sql-files/compatibility/*

**Comment by ganonDX** [comment]
> 
> 
> The problem you describe is because the table gets deleted and recreated with every file.
> This is solved in #5478.
> 
> For flux you need to use the files in sql-files/compatibility/*

thanks a lot, I havent noticed the pullrequest yet. I'll be waiting for it to merge then.

I also have not used any of the files inside compatibility and upgrades.

is it necessary to apply all of the files within the folders compatibility and upgrades to my SQL?

**Comment by Lemongrass3110** [comment]
If you check out this link https://github.com/rathena/rathena/tree/master/sql-files you will see the README at the bottom, or just open the README.md file on your local clone of the repository.

Basically what you need to do is use the new SQL tables and create a view with the compatability script so that it will show up in the old table format, so that the control panel can read it. All you have to change is to let your control panel read from item_db_re_compat instead of item_db_re. And I think that should be a manageable task.

**Comment by ganonDX** [comment]
> 
> 
> If you check out this link https://github.com/rathena/rathena/tree/master/sql-files you will see the README at the bottom, or just open the README.md file on your local clone of the repository.
> 
> Basically what you need to do is use the new SQL tables and create a view with the compatability script so that it will show up in the old table format, so that the control panel can read it. All you have to change is to let your control panel read from item_db_re_compat instead of item_db_re. And I think that should be a manageable task.

thanks a lot for your time and answer. I already knew that part. I was just wondering if it is necessary to apply all the files from the folder sql-files/upgrades/

**Comment by aleos89** [comment]
Not every update requires a SQL change, but most of the time you should get a warning at the start of the server stating a SQL discrepancy. We are working on an automatic SQL upgrade in #4916.
