### ISSUE TITLE
Renewal Variable/Fixed Casting Issue

### ISSUE THREAD

**Issue by reigneil** [rathena/rathena#549]
it seems like there is something wrong about our renewal casting.
1. even if you don't have dex and/or int variable casting has been reduce for about 12%.
2. reducing fixed casting by skills and/or equipments also reduce variable casting.
3. over reduction of casting by skills and/or equipments will result to have casting time. (overflow)

how to test this issue...
1. need 3rd party program. (bot)
2. prepare skills and equipments that reduce fixed or variable casting
3. use any skill with pure variable or pure fixed or combination of variable/fixed casting and monitor your casting using bot program. with buffs and equipment on/off

**Comment by cydh** [comment]
1. Depends, u say no dex or int, Job Level 1 Warlock has 1 Desc and 2 Int, makes the varcast only 91%
2. yeah found this, minimum fixed cast should be 0, cannot be negative.
3. what the **normal** skill/item that can make this overflow?

**Comment by reigneil** [comment]
1. based on what you describe it is intended to reduced for about 9% if you have 1 dex and 2 int?
2. thanks for the fixed.
3. it looks like it is cause by this item ID: 18593
calling @nanakiwurtz

**Comment by nanakiwurtz** [comment]
@reigneil About the item 18593: If you have updated your repo, it can't be negative anymore just like what @cydh said earlier.

**Comment by reigneil** [comment]
but i do have updated repo and still...
18593,Fancy_Mini_Crown,Fancy Mini Crown,4,20,,100,,2,,1,0xFFFFFFFF,63,2,256,,30,1,707,{ bonus bInt,1; bonus bMdef,5; bonus bVariableCast,-3000; bonus bMatkRate,3; bonus bHealPower,4; bonus bSkillUseSP,-3; .@r = getrefine(); bonus bMatkRate,(.@r>6)?(3):((.@r>4)?(1):(0)); },{},{}

-3000 thats huge decrease casting time.

**Comment by nanakiwurtz** [comment]
@reigneil My source said that the cast time was reduced by 3 seconds, that's why I used 'bonus bVariableCast' which use miliseconds as value instead of percentage, and that is where the 3000 come from. Well I guess I'll update the code :banana:

**Comment by cydh** [comment]
@aleos89 was committing something about cast time. maybe it 'fixed' the issue (case 1)
