### ISSUE TITLE
Missing quest type.

### ISSUE THREAD

**Issue by rye305** [rathena/rathena#5490]
https://hazyforest.com/illusion_investigation

Kill any monster of map X counts into quest progression.

example:

10 fabre 10 poring on map prt_fild08

quest objective = kill 100 monsters on map prt_fild08

killing 10 fabres and 10 porings =
 
quest progression = 20/100

**Comment by Balferian** [comment]
Approve, it`s a new quest type.
For example quest **18079**.
It requare to kill 80 any mobs without mob types on location **gl_prison** 
(or like @rye305 said with types or mobid in other quests).
I don't know if there is a function in client to display map name like 
**"gl_prison"** => **"글래스트헤임 지하 감옥 1층"**.
![image](https://user-images.githubusercontent.com/16213511/97286915-0465cf80-1855-11eb-881b-d2304fd01ace.png)
![image](https://user-images.githubusercontent.com/16213511/97286943-0cbe0a80-1855-11eb-94af-9fdd7308db4e.png)

**Comment by Balferian** [comment]
Example of quest:
>  - Id: 18079
    Title: GlastHeim hunt
    Targets:
      - Id: 1
        Count: 80
        Location: gl_prison
        MapName: Glastheim Underground Prison B1
