### ISSUE TITLE
Item that SHOULD NOT disappear after it's used

### ISSUE THREAD

**Issue by cydh** [rathena/rathena#550]
I just noticed that we should implement something to flag that usable item won't removed after using it.
Like Boarding_Halter (12622), but it's fun, it does not disappear because it's using type 11 and not using 'itemskill' script.
We need the flag for Boarding_Halter (12622), C_Wing_Of_Fly (12887), and Para_Team_Mark_ (22508).
C_Wing_Of_Fly (12887) may is not removed on usage, because it's gained normally as rental item.

**Comment by Lemongrass3110** [comment]
Do you know how this works on the officials or do we need someone to gather the info about it?
From what I have seen on euRO it is deleted and readded to the inventory afterwards. But from your description it should not be deleted in the first place, right?

**Comment by Akaineko-astasi** [comment]
If I remember this clearly, I used Boarding_Halter and it wasn't deleted then added on rus RO.

**Comment by cydh** [comment]
@Lemongrass3110 gonna check it. maybe the 2nd schema. xD
if consider their habit, when u try move items from inventory to cart that full, the moved item should be 'moved/deleted' first then re-add to the inventory (but we didn't, we check for the slots first).
but yeah, going to check (how? lol).
