### ISSUE TITLE
About itemI_db.yml Name: translation.

### ISSUE THREAD

**Issue by 24msz6eo** [rathena/rathena#5512]
rAthena Hash: https://github.com/rathena/rathena/commit/868bdead9e5b33224c1faf03b6d1f63fd25a4255

Client Date: 2020-03-04
Server Mode: RE
Description of Issue:
After changing to yml, my old mass translation program is no longer available. Is there any way to translate the name of Name:? The translation is based on idnum2itemdisplaynametable.txt

**Comment by aleos89** [comment]
The author of the tool will need to update the tool to support the new YAML table.
