### ISSUE TITLE
Found Error on Character CMD

### ISSUE THREAD

**Issue by joven15** [rathena/rathena#5514]
[Warning]: Found unknown gender 'F' for character 'Joven15' (CID: 150000, AID: 0), returning account gender...

Im actually using a latest rathena emulator downloaded from here. then i use a 2014-04-16aRagexe client. heres the error if i login i saw the warning from charserv.bat. from selection character 4 warning then plus 1 when i already in the map.

btw i use packet_obfuscation.

[Info]: Loading Char Data (2000000)
[Warning]: Found unknown gender 'F' for character 'Joven15' (CID: 150000, AID: 0), returning account gender...
[Warning]: Found unknown gender 'F' for character 'Joven15' (CID: 150000, AID: 0), returning account gender...
[Warning]: Found unknown gender 'F' for character 'Joven15' (CID: 150000, AID: 0), returning account gender...
[Warning]: Found unknown gender 'F' for character 'Joven15' (CID: 150000, AID: 0), returning account gender...
[Warning]: Found unknown gender 'F' for character 'Joven15' (CID: 150000, AID: 0), returning account gender...
[Info]: Char load request (150000)
[Warning]: Found unknown gender 'F' for character 'Joven15' (CID: 150000, AID: 2000000), returning account gender...
[Info]: Loaded char (150000 - Joven15):  status memo 0 skills friends hotkeys mercenary
[Info]: Selected char: (Account 2000000: 1 - Joven15)
[Info]: Subnet check [127.0.0.1]: Matches 127.0.0.0/255.0.0.0

* **rAthena Hash**: 

* **Client Date**: 

* **Server Mode**: 

* **Description of Issue**: 
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Daegaladh** [comment]
Did you updated your rAthena? This was already fixed in b1b7d065599c02e51cdacd0ec2fa26e384f8b175

**Comment by joven15** [comment]
yes im using a updated rathena emulator came from github.

**Comment by joven15** [comment]
![image](https://user-images.githubusercontent.com/73867685/97963406-0d751480-1df2-11eb-87d7-c521ebdd228f.png)

as you can see the patch already there and i already compile it. but still has the error.
