### ISSUE TITLE
Reverberation/Trap damage issue

### ISSUE THREAD

**Issue by reigneil** [rathena/rathena#552]
Reverberation damage must split among targets.
so the more monster it hits the lesser damage they take.

and also this is also applies to other traps like Claymore, Blast Mine etc. 
a nerf/re-balance patch

more info:
http://irowiki.org/wiki/Reverberation
If an enemy touches the cell, it will explode, splitting the damage it causes across all enemies in a 3 x 3 area.
http://irowiki.org/wiki/Hunter#Builds
Because Claymore Trap and Blast Mine will split damage across several monsters, using Land Mine is more preferred as it will always one-shot one monster.

**Comment by MrAntares** [comment]
I hope this is some kind of iRo joke, and not kRo official...
