### ISSUE TITLE
Katar Type critical display issue

### ISSUE THREAD

**Issue by reigneil** [rathena/rathena#553]
if you have enough critical and wearing a katar type weapon your critical display at status window(Alt+A or Alt+Q) is double. while on official server equipping a katar do not display its double critical but rather hidden.

**Comment by Playtester** [comment]
I think this was an intentional design decision. The same in how we show the real DEF (+0.7 per refine) rather than the fake DEF (+1 per refine).

**Comment by joelolopez** [comment]
i confirrm this one! is it natural? critical rate is doubled using katars? if it's not then we need someone to fix this.. i thought that katar type weapons is naturally doubled your katar while axe type weapons are unbreakable.. i've tested this before but i didnt report this issue cause im not kinda sure if its valid

**Comment by Playtester** [comment]
Critical rate is doubled for katars on official servers too, it's just that it doesn't display in the status window on official servers.

**Comment by MrAntares** [comment]
working as intended
