### ISSUE TITLE
refine_db.yml is not being read properly

### ISSUE THREAD

**Issue by rye305** [rathena/rathena#5534]
* **rAthena Hash**: d01b718cc06d91db60336b562b7076299eee1ae4

* **Client Date**: 20200304

* **Server Mode**: RE

From one day to another my refine UI is being SUPER weird. It seems like my refine_db.yml is not being read properly. Did something change? 

Even reverting to a date (23.10.2020) where the refine UI was working 100% on my server flawlessy, it does not work anymore.

Could SQL affect this?

![grafik](https://user-images.githubusercontent.com/33780589/98668288-f71a0c00-234f-11eb-826d-01f5dc6c819f.png)
No matter what equipment I use, it will ask for elunium and enriched elunium until refine level +10. 
at +10 and higher, it asks for HD carnium and carnium. No matter what equipment type, armor, shadow,  weapon / lv 1 / 2 / 3 / 4 
it always asks for these materials.

The only way I can change the materials is, if I replace the materiel in refine_db.yml. But then again the same story, just with a different material. 

Even a knife [1] level 1 weapon asks for elunium and enriched elunium from refine level 1-10.

I tried everything, super desperate rn. cant explain this behaviour at all. 

refine_db.yml
https://upaste.me/978e535019763c193

* **Modifications that may affect results**: 
  
  
cydh refine UI

**Comment by Lemongrass3110** [comment]
Refine UI from cydh is not supported here.

**Comment by ganonDX** [comment]
How I wish that the rAthena refine UI gets merged to master :/ Every week, cydh's refine ui gets more busted and busted. Currently have the same issue T_T
