### ISSUE TITLE
RE: Weapon attack bonus from Strength/Dexterity Display Issue

### ISSUE THREAD

**Issue by reigneil** [rathena/rathena#554]
this is also similar to Critical Display wearing a Katar Weapon but this time it is Weapon Attack bonus from stats that must be hidden from Status Window (Alt+A or Alt+Q)

note:
to reproduce you must wear weapon to display additional weapon attack.

**Comment by Paoly28** [comment]
yes this should be hidden, another bug is Str/Dex bonus from buffs/foods/runes etc. are not giving their proper weapon atk bonus.
