### ISSUE TITLE
Almost all new items have the wrong aegis name.

### ISSUE THREAD

**Issue by rye305** [rathena/rathena#5540]
* **rAthena Hash**: e287d8ce54e6a389fb71a21f94f54ecb441caa96

* **Server Mode**: RE

Most aegies names such as "aegis_xxxxx" are wrong and not official. Some of those aegis names sadly don't work with the lapine system in lapineddukddakbox.lub and LapineUpgradeBox.lub, which require the items to have the correct aegis names.

**Comment by ecdarreola** [comment]
I believe it's only a placeholder, you can open a pull request using the .lub files to fix it.

**Comment by aleos89** [comment]
We decided on this nomenclature for Aegis names we are unsure of after moving to yaml. There are many items where we just made up a name and it doesn’t help us to know that we “need official data” on that item.
