### ISSUE TITLE
Duplicate NPCs do not initiate OnInit event after @reloadpcfile.

### ISSUE THREAD

**Issue by Triedge** [rathena/rathena#5541]
* **Server Mode**: pre-renewal

* **Description of Issue**: When you start the map-server the original NPC and the duplicates with the OnInit event, they work correctly. But if you use @reloadnpcfile the duplicates stop working, forcing you to restart the map-server to get them working correctly again.
  * Result: https://cdn.discordapp.com/attachments/352836475982839808/776884526621786112/unknown.png 
  * How to Reproduce: 
1.- **Start** the Map-server. You will see that all NPCs (original **and duplicates**) start the OnInit.
2.- Then you use the **@reloadnpcfile** command and **only the original** starts its OnInit event, but the duplicates **don't** and stop working.
```
prontera,1,1,4	script	Treasure#0	10005,{
OnTimer10000:
	stopnpctimer;
	debugmes "Work:"+strnpcinfo(0);
	initnpctimer;
	end;
OnInit:
	debugmes "Work:"+strnpcinfo(0);
	initnpctimer;
	end;
}

prontera,1,1,4	duplicate(Treasure#0)	Treasure#1	10005
prontera,1,1,4	duplicate(Treasure#0)	Treasure#2	10005
```

**Comment by LiamKarlMitchell** [comment]
npc_parse_duplicate has no onInit.
Should a second argument of runOnInit be added to npc_parse_duplicate as is in npc_parsesrcfile?

```cpp
else if( (i=0, sscanf(w2,"duplicate%n",&i), (i > 0 && w2[i] == '(')) && count > 3 )
			p = npc_parse_duplicate(w1,w2,w3,w4, p, buffer, filepath, true);
```

Like how it works from npc_parse_script?
```cpp
	if( runOnInit ) {
		char evname[EVENT_NAME_LENGTH];
		struct event_data *ev;

		snprintf(evname, ARRAYLENGTH(evname), "%s::%s", nd->exname, script_config.init_event_name);

		if( ( ev = (struct event_data*)strdb_get(ev_db, evname) ) ) {

			//Execute OnInit
			run_script(nd->u.scr.script,ev->pos,0,nd->bl.id);

		}
	}
```

Would this cause OnInit to be executed twice on server start however?
Additionally on Server startup it triggers a lot of attempting to hide non-existing NPC errors/warnings same with @reloadscript

Something also with chat_createnpcchat already has a chatroom, cannot create a new one!

But it does trigger the script this way.
After reloadnpcfile (or loadnpcfile) with that edit I see the script debug messages from all of them.
```
[Debug]: script debug : 0 110015579 : Work:Treasure#0
[Debug]: script debug : 0 110015580 : Work:Treasure#1
[Debug]: script debug : 0 110015581 : Work:Treasure#2
```
