### ISSUE TITLE
update items Flags: DropEffect

### ISSUE THREAD

**Issue by idk-whoami** [rathena/rathena#5547]
* **rAthena Hash**: 9348ea441d0adae38ca2b4b10aa53db63ff915dd

* **Client Date**: 20200401

* **Server Mode**: re

* **Description of Issue**: 
rdata.grf 6 color
rAthena 5 color
![Capture](https://user-images.githubusercontent.com/60462533/99214789-aef16280-2803-11eb-9a15-76ede128e87e.PNG)

![บันทึก_2020_11_16_11_53_13_135](https://user-images.githubusercontent.com/60462533/99214395-9e8cb800-2802-11eb-890a-5eb92bf78fba.gif)

![บันทึก_2020_11_16_11_53_33_767](https://user-images.githubusercontent.com/60462533/99214464-c9770c00-2802-11eb-9211-299b32cd2907.gif)

![บันทึก_2020_11_16_11_54_05_823](https://user-images.githubusercontent.com/60462533/99214528-f3c8c980-2802-11eb-950e-a3987f36c29d.gif)

setting
`  - Id: 501
    AegisName: Red_Potion
    Name: Red Potion
    Type: Healing
    Buy: 10
    Weight: 70
    Flags:
      DropEffect: WHITE_PILLAR
    Script: |
      itemheal rand(45,65),0;
  - Id: 502
    AegisName: Orange_Potion
    Name: Orange Potion
    Type: Healing
    Buy: 50
    Weight: 100
    Flags:
      DropEffect: BLUE_PILLAR
    Script: |
      itemheal rand(105,145),0;
  - Id: 503
    AegisName: Yellow_Potion
    Name: Yellow Potion
    Type: Healing
    Buy: 180
    Weight: 130
    Flags:
      DropEffect: YELLOW_PILLAR
    Script: |
      itemheal rand(175,235),0;
  - Id: 504
    AegisName: White_Potion
    Name: White Potion
    Type: Healing
    Buy: 1200
    Weight: 150
    Flags:
      DropEffect: PURPLE_PILLAR
    Script: |
      itemheal rand(325,405),0;
  - Id: 505
    AegisName: Blue_Potion
    Name: Blue Potion
    Type: Healing
    Buy: 5000
    Weight: 150
    Flags:
      DropEffect: ORANGE_PILLAR
    Script: |
      itemheal 0,rand(40,60);
  - Id: 506
    AegisName: Green_Potion
    Name: Green Potion
    Type: Healing
    Buy: 40
    Weight: 70
    Flags:
      DropEffect: CLIENT
      BuyingStore: true
    Script: |
      sc_end SC_POISON; sc_end SC_SILENCE; sc_end SC_BLIND; sc_end SC_CONFUSION; sc_end SC_HALLUCINATION;`

https://github.com/rathena/rathena/blob/master/src/map/itemdb.hpp#L754-L764
/// Enum for item drop effects
enum e_item_drop_effect : uint16 {
	DROPEFFECT_NONE = 0,
	DROPEFFECT_CLIENT,
	DROPEFFECT_WHITE_PILLAR,
	DROPEFFECT_BLUE_PILLAR,
	DROPEFFECT_YELLOW_PILLAR,
	DROPEFFECT_PURPLE_PILLAR,
	DROPEFFECT_ORANGE_PILLAR,
	DROPEFFECT_MAX
};

  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by Triedge** [comment]
this work with 2018 client?

**Comment by idk-whoami** [comment]
i don't know with 2018 client

**Comment by Balferian** [comment]
Pink droplight supported in iteminfo for all MVP cards.
> 	[27109] = {
		unidentifiedDisplayName = "지터벅 카드",
		unidentifiedResourceName = "이름없는카드",
		unidentifiedDescriptionName = { "감정되지 않음. [돋보기] 를 사용하여 감정할 수 있다." },
		identifiedDisplayName = "지터벅 카드",
		identifiedResourceName = "이름없는카드",
		identifiedDescriptionName = {
			"무속성 적에게 받는 물리, 마법 데미지 10% 감소.",
			"MaxHP +500.",
			"노래하는 페르, 연주하는 페르 카드와 함께 장착시, 물리, 마법 공격시 일정 확률로 6초 동안 각성한 페르로 변신.",
			"각성한 페르로 변신시, HP를 2000만큼 회복하고 무속성 적에게 주는 물리, 마법 데미지 200% 증가.",
			"계열 : ^777777카드^000000",
			"장착 : ^777777투구^000000",
			"무게 : ^7777771^000000",
			"^B7B7B7[ID: 27109]^000000"
		},
		slotCount = 0,
		ClassNum = 0,
		costume = false,
		**EffectID = 1186**
	},
