### ISSUE TITLE
Map Server Crash During @reloaditemdb

### ISSUE THREAD

**Issue by reunite-ro** [rathena/rathena#5548]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/f0f1acef2250773485040aa914540a53dae4de50

* **Client Date**: 20200304

* **Server Mode**: Renewal

* **Description of Issue**: Map Server Crash During reloaditemdb
  * Result: Map Crash Signal.
  * Expected Result: reloaditemdb success
  * How to Reproduce: Edit .yml and reloaditemdb.

Ill provide any logs/error soon using GDB if needed.

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment]
> Ill provide any logs/error soon using GDB if needed.
How do you think we should even look at this without having it?

**Comment by Triedge** [comment]
The crash occurs when the server does not find an item in mob_db and creates a "dummy item". And this ends up causing a crash right after applying the @reloaditemdb. It can be fixed temporarily by simply removing the item from the mob_db or making sure it is correctly implemented in the item_db.yml
