### ISSUE TITLE
Champion Mobs do not give off their effects

### ISSUE THREAD

**Issue by dragonis1701** [rathena/rathena#555]
Ringleader should glow blue, similar to Link.
Furious should glow red, similar to berserk.
I don't know what the others effects are. I believe Solid pulses a color, similar to endow, but I'm not 100% sure on it.

**Comment by nanakiwurtz** [comment]
Do you have a screenshot of it?

**Comment by dragonis1701** [comment]
Of them giving off the effects on officials or of not giving off the effects on rAthena?

**Comment by dragonis1701** [comment]
Found proof of it on official iRO:
Furious, Looks just like Berserk: 
[URL=http://s207.photobucket.com/user/Evensean021502/media/screenChaos048_zpskcdcuzya.jpg.html][IMG]http://i207.photobucket.com/albums/bb64/Evensean021502/screenChaos048_zpskcdcuzya.jpg[/IMG][/URL]

Swift, Looks like what used to be the level 160 aura. It's like a black hole-vortex type of movement.
[URL=http://s207.photobucket.com/user/Evensean021502/media/screenChaos050_zpsrrzxr3ca.jpg.html][IMG]http://i207.photobucket.com/albums/bb64/Evensean021502/screenChaos050_zpsrrzxr3ca.jpg[/IMG][/URL]

Elusive, It's a pulsing purple:
[URL=http://s207.photobucket.com/user/Evensean021502/media/screenChaos052_zpsd4pzpoco.jpg.html][IMG]http://i207.photobucket.com/albums/bb64/Evensean021502/screenChaos052_zpsd4pzpoco.jpg[/IMG][/URL]

Solid, It's a solid green light with the most light circling around.
[URL=http://s207.photobucket.com/user/Evensean021502/media/screenChaos055_zps49kmxvjv.jpg.html][IMG]http://i207.photobucket.com/albums/bb64/Evensean021502/screenChaos055_zps49kmxvjv.jpg[/IMG][/URL]

Ringleader, looks like a player who is linked:
[URL=http://s207.photobucket.com/user/Evensean021502/media/screenChaos047_zpsugrssd0f.jpg.html][IMG]http://i207.photobucket.com/albums/bb64/Evensean021502/screenChaos047_zpsugrssd0f.jpg[/IMG][/URL]

**Comment by RagnarokNova** [comment]
It's a client issue. They display fine on newer (2015) clients.

**Comment by dragonis1701** [comment]
Mmm... 2013 is not high enough? And is it confirmed that it's merely a client issue? Seems a bit odd.

**Comment by RagnarokNova** [comment]
http://herc.ws/board/topic/5457-how-to-enable-mobs-effect-ef-bluelightbody/
