### ISSUE TITLE
Random Option Rates

### ISSUE THREAD

**Issue by Vincentore** [rathena/rathena#5551]
Hello,

my first time posting here.
The new random option code to apply the random part of the option ist somewhat not true to the statement that the chance is 1/10000.

Because the code stops looking for an random option at the first option which becomes true.

```
		// Apply Random options (if available)
		if (group->max_random > 0) {
			for (size_t i = 0; i < min(group->max_random, MAX_ITEM_RDM_OPT); i++) {
				// If item already has an option in this slot, skip it
				if (dropping->option[i].id > 0)
					continue;

				std::shared_ptr<s_random_opt_group_entry> option = util::vector_random(group->random_options);

				if (rnd() % 10000 < option->chance)
					getitem_setitem_option(dropping->option[i], option);
			}
		}
```

This makes the chance for all options in the bottom of the list less.

Lets say there are 10 options with an 500 rate.
The first one will be rolled out first. If it is true the code will stop here.
So in reality the chance for all other options behind that one is 500/10500 not 500/10000.

For the third option it is 500 in 11000 because the othe options obove would "steal" the chance bevore this option even get a chance to roll the dice. The 10th option will be 500 in 15000... so the chance would be 50% less to ever get that option. Which was not intended by the rates I guess.

**Comment by Atemo** [comment]
It's true that some values are strange but it seems to be like that on aegis, each possibility in %00 not rate/sum rates.
