### ISSUE TITLE
Bugs in the skills of Wanderer and Ministrel:

### ISSUE THREAD

**Issue by tmav94** [rathena/rathena#556]
ALL Choirs:
Great Echo
Dances with Wargs
Song of Mana
Lerad's Dew
Saturday Night Fever
Warcry from Beyond
Sinking Melody
Destruction Song
Infinite Humming

1) effect of the skills area:
Apparently, Thurin managed to fix the bug skill area. (OK!)

2) The Choirs are being treated by the game as if they were Duets (requires a musician is on the other side to be used), but in fact it is necessary that only the musicians are in the same pt and visible on the screen.
"Chorus skills are 3rd class Maestro and Wanderer que skills can only be used with multiple Performers are in the party and on the same screen at the same team. This is an advantage over 2nd class Ensemble Skills where the requirement was que the two performers had to be of opposite gender and standing in adjacent cells. In addition, you can combine chorus skills with 2nd class ensembles and solo skills. "
http://irowiki.org/wiki/Chorus_Skill

3) The Singing Mermaid / Voice of Siren / Siren's Voice.
Even if you argue with me saying that skill're right, she's not.
If used for a 175 level player against an enemy 175, it must be in status "seduction", showing the emote / love for at least 3 seconds (tested on other servers)
But here it lasts for 1 second or less.
I believe the server is with the skill of the formula for level 150, as with other skills of other characters.

**Comment by ssabri** [comment]
I'm with the same issues with the chorus and siren's voice.
It's necessary be exactly next to the other performer to play the chorus.
And siren's voice is acting with the 150's formula, i think

**Comment by Thurin** [comment]
Oh, I'm have the same issues too.

**Comment by ssabri** [comment]
Can anyone fix those bugs please? :c
