### ISSUE TITLE
Unable to use variables to dynamically construct itemshop

### ISSUE THREAD

**Issue by Akkarinage** [rathena/rathena#5571]
* **rAthena Hash**: f97dd6e85fc611aafa856d1d788255ec518388e5

* **Client Date**: 2018-06-20

* **Server Mode**: Pre-Renewal

* **Description of Issue**: 
  * Result: 
```
[Error]: npc_parse_shop: Invalid item cost definition in file 'npc/event_script.txt', line '209'. Ignoring the rest of the line...
 * w1=-
 * w2=itemshop
 * w3=event_shop#shop
 * w4=-1,$EVENT_ITEM,$EVENT_ITEM_BUY:1
```
  * Expected Result: A working itemshop.
  * How to Reproduce: 
```
-	script	#eventstuff	-1, {
	$EVENT_ITEM = 501;
	$EVENT_ITEM_BUY = 502;
	end;	
}
-	itemshop	event_shop#shop	-1,$EVENT_ITEM,$EVENT_ITEM_BUY:1
```
  * Official Information: None.

* **Modifications that may affect results**: None.

**Comment by secretdataz** [comment]
Itemshop definition only accepts numbers in format of `%u:%11d`. Looks like intended behavior to me.

**Comment by Lemongrass3110** [comment]
Working as intended
