### ISSUE TITLE
script .i=0; min(.i,200); will return 200

### ISSUE THREAD

**Issue by javirst** [rathena/rathena#5573]
* **rAthena Hash**: 

* **Client Date**: 
Any

* **Server Mode**: 
Any

* **Description of Issue**: 
  * Result: 
`.i = 0;
debugmes ""+min(.i,200);`
this will return 200
`debugmes ""+min(0,200);`
but this will return 0
  * Expected Result: 
both will return 0 value
  * How to Reproduce: 
```c
-	script	HMM	-1,{
OnInit:
	.i = 0;
	debugmes ""+min(.i,200);
	debugmes ""+min(0,200);
}
```
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by sader1992** [comment]
I can confirm this in 53e7f59f484dce641e1fc75539d8b47272a22128
