### ISSUE TITLE
RODEX cannot read mail

### ISSUE THREAD

**Issue by 24msz6eo** [rathena/rathena#5575]
rAthena Hash: https://github.com/rathena/rathena/commit/629c7b50f34d82d6dfd39b09d0cfe9792ad85d33

Client Date: 2020-07-29 RE

Server Mode: Renewal

Description of Issue:
RODEX cannot read mail，
![1606449083604](https://user-images.githubusercontent.com/68574321/100409494-f2bb5600-30a6-11eb-9322-7497f6fa91d1.jpg)

**Comment by Balferian** [comment]
@24msz6eo The error was fixed in this pull:
https://github.com/rathena/rathena/pull/5445
Please check it.
