### ISSUE TITLE
WE_CALLPARTNER fails if Child is autotrading

### ISSUE THREAD

**Issue by Radio-Gagaa** [rathena/rathena#5576]
* **rAthena Hash**: b143241222470419e26f47ba919226ca8c19b007

* **Client Date**: 2018-06-21

* **Server Mode**: Pre-Renewal

* **Description of Issue**: 
  * Result:  When you are married and have both a spouse and a child and try to use WE_CALLPARTNER to call your spouse while your child is autotrading, the skill will fail. Looks like this was introduced in 7a9aa7fbcfe40080c1b743137fc68aebb596e632 due to it falling through into skill code it should not fall through to.
  * Expected Result:  Whether the child is online, autotrading or whatever should not have any impact on the usage of WE_CALLPARTNER.
  * How to Reproduce:  Be married and have a child. Put child in autotrade. Try to use WE_CALLPARTNER. It will fail.
  * Official Information:  None.
  

* **Modifications that may affect results**:

**Comment by lighta** [comment]
This is due to some missing break in `int skill_castend_id(int tid, unsigned int tick, int id, intptr_t data)`
