### ISSUE TITLE
AS_GRIMTOOTH cast delay

### ISSUE THREAD

**Issue by mrboob** [rathena/rathena#5580]
* **rAthena Hash**: fatal: not a git repository (or any of the parent directories): .git (Last Updated: 04/12/2018)

* **Client Date**: 2015-09-16aRagexe

* **Server Mode**: Pre-Renewal

* **Description of Issue**: 
  * Result: Delay occurs after two uses of the Grimtooth Skill, even with max aspd
  * Expected Result: So that there is no delay after using the skill
  * How to Reproduce: Please see [this video](https://www.youtube.com/watch?v=egaOvxfktd8)
  * Official Information: [The skill should not work with a delay at max ASPD](https://irowiki.org/wiki/Grimtooth)
  

* **Modifications that may affect results**: the adelays mod has been installed on the server and the default settings are used

How to fix this?

**Comment by lighta** [comment]
What is this ?
"rAthena Hash: fatal: not a git repository (or any of the parent directories): .git (Last Updated: 04/12/2018)"
Have you installed rathena via an archive ?

**Comment by mrboob** [comment]
> Have you installed rathena via an archive ?

Yes, i download last rathena (date: 04/12/2018) ZIP archive from [github](https://github.com/rathena/rathena)

**Comment by mrboob** [comment]
The problem was related to the adelays settings. Closed.

**Comment by alpsicho** [comment]
How can I fix this? I have the same problem. Can I just delete the Skill line from `adelay_skill_delays.txt` or adjust it?
