### ISSUE TITLE
Reclect Damage Bug

### ISSUE THREAD

**Issue by DANILOFR1** [rathena/rathena#5584]
* **Client Date**: 
20180621

* **Server Mode**: 
Renewal

* **Description of Issue**: 
I discovered the bug when testing the Orc lord card, even with 30% in the script, the 30 was referring to 100% of the reflected damage as if 30 were 100%. When changing to 15, the reflected damage was 50%.

4135,Orc_Load_Card,Orc Lord Card,6,20,,10,,,,,,,,16,,,,,{ bonus bShortWeaponDamageReturn,30; },{},{}

reflect 100%

4135,Orc_Load_Card,Orc Lord Card,6,20,,10,,,,,,,,16,,,,,{ bonus bShortWeaponDamageReturn,15; },{},{}

Reflect 50%

Apparently the calculation of reflect has the same problem in all items that use bShortWeaponDamageReturn

I tried to recompile with the most current src battle, but it didn't work.

**Comment by aleos89** [comment]
What is your git hash?

I tested on 4957690.
![image](https://user-images.githubusercontent.com/3521753/101048806-f17ba480-3550-11eb-9fcb-d1ce1cb8c52a.png)

299 * 0.3 = 89.7 which seems correct to me.

**Comment by Lemongrass3110** [comment]
No answer for over a month.

**Comment by ppardo23** [comment]
Hello, i have the same problem.
Ítems that use bShortWeaponDamageReturn (vm, orc lord card, etc), reflect more than what the bonus number indicates

**Comment by Playtester** [comment]
Is there a way to reproduce it? Is it only against a certain skill or monster? Does it display more damage or is just the actual damage being higher?
