### ISSUE TITLE
Can item_db.yml and item_db.txt coexist?

### ISSUE THREAD

**Issue by 24msz6eo** [rathena/rathena#5585]
Can item_db.yml and item_db.txt coexist?
Because yml loading really takes time! ><"

**Comment by Lemongrass3110** [comment]
I guess you are using Visual Studio. Change it from "Debug" to "Release" mode and you will be fast again.
This is because of the debug code being generated by MSVC.

And no - they can not.

**Comment by lighta** [comment]
The fastest is having it as itemdb.sql I suppose.
Suggestion are usually put on forum : https://rathena.org/board/forum/104-source-discussion/
You're free to propose a PR which make the process faster tough
