### ISSUE TITLE
Some General Issues

### ISSUE THREAD

**Issue by tmav94** [rathena/rathena#559]
> Choirs need the pair is just the same screen, not next, here requires the char stay glued to each other.

> The ability Cross Impact of ninja must leave a priate additional damage brand hits the target, similar to Dark Crow sicarios.

> The ability "Last Stand" does not work properly, and you use it simply does nothing.

**Comment by aleos89** [comment]
1) Your choir issue was reported in #556.
2) I'm sorry but I don't understand what you're saying about Cross Impact.
3) By simply "does nothing" can you please describe this in more detail? Does the ATK not work? Does the ASPD not work? It's not cancelling Adjustment? Do you have Heat Barrel or Platinum Alter active? If either HB/PA are active, then Madness Cancel does not work.

**Comment by Thurin** [comment]
I believe it has been a problem for the Heat barrel was active.
Thanks.

**Comment by tmav94** [comment]
Fixed on latest git.
