### ISSUE TITLE
Error Compile at branch Fiture Lapineui

### ISSUE THREAD

**Issue by IDKas** [rathena/rathena#5593]
* **rAthena Hash**: 

* **Client Date**: 2018-06-21

* **Server Mode**: RENEWAL

* **Description of Issue**: Error when compile emulator (https://github.com/rathena/rathena/tree/feature/lapine_synthesis_and_upgrade)
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by Daegaladh** [comment]
You can't expect an unfinished pull request to work
