### ISSUE TITLE
2014-04-22 Client

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#560]
When you type the command @go, and not the map name, the client takes crash and closes.

**Comment by anacondaqq** [comment]
I saw the same issue opened here.
Hmm, can you edit this file: https://github.com/rathena/rathena/blob/master/conf/help.txt#L39
(remove all lines, or replace them wth shorter tabs)

But i do not remember about what i seen (is it closed & fixed, or not)
Please, search at issue tracker and last month commits.

**Comment by admkakaroto** [comment]
Nice man, thx!!!

**Comment by aleos89** [comment]
This should be resolved in 88cfff0.
