### ISSUE TITLE
The feat of the achievement system don't work

### ISSUE THREAD

**Issue by OriginRO** [rathena/rathena#5600]
* **rAthena Hash**: 495769036
* **Client Date**: 2020-03-04
* **Server Mode**: RENEWAL
* **Description of Issue**: The feat of the achievement system don't work
  * Result: 
![1](https://user-images.githubusercontent.com/46036150/101119525-7ab0db00-3626-11eb-9680-bd776075e24a.jpg)
  * Expected Result:
![2](https://user-images.githubusercontent.com/46036150/101119530-7e446200-3626-11eb-9a07-5f229ede9a73.jpg)

  * How to Reproduce: use command  ``` `@lvup 99` ```,  then open the achievement system.
  * Official Information: no

* **Modifications that may affect results**: no

**Comment by aleos89** [comment]
The feats listed there aren't base level, your translation is wrong in this part.

![image](https://user-images.githubusercontent.com/3521753/101178759-60233580-3617-11eb-974c-71297d91451f.png)
It's your "achievement level".

**Comment by OriginRO** [comment]
> The feats listed there aren't base level, your translation is wrong in this part.
> 
> ![image](https://user-images.githubusercontent.com/3521753/101178759-60233580-3617-11eb-974c-71297d91451f.png)
> It's your "achievement level".
Unable to get achievement level rewards
