### ISSUE TITLE
White wing set Bonus effects

### ISSUE THREAD

**Issue by AsurielRO** [rathena/rathena#5606]
* **rAthena Hash**: 

* **Client Date**:  20200304

* **Server Mode**:  Renewal

* **Description of Issue**: 
  * Result:  Bonus effects of white wing suit is not working. It seems like missing table on item_combo_db.txt
  * Expected Result:  
  * How to Reproduce:  Try to equip all white wing suits ( 15042, 2580, 2479 and 2890 ) and use Arrow Storm, Based on my test 40k damage with/without set.
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by idk-whoami** [comment]
i think item_combo_db bug

test on **rAthena Hash**: dade413935cfbd65935730ef78386f5a68742317  not working

**Comment by idk-whoami** [comment]
> i think item_combo_db bug
> 
> test on **rAthena Hash**: [dade413](https://github.com/rathena/rathena/commit/dade413935cfbd65935730ef78386f5a68742317) not working


`default`
![Capture](https://user-images.githubusercontent.com/60462533/101593473-86374400-3a22-11eb-89a1-e0898297d72a.PNG)

`if item combo <= 2 is working`
``````
2359:2654,{ bonus bUseSPrate,-20; bonus bMaxHP,300; }
``````
https://github.com/rathena/rathena/blob/master/db/re/item_combo_db.txt#L190
![Capture](https://user-images.githubusercontent.com/60462533/101593651-ddd5af80-3a22-11eb-9121-2be215cdc3ca.PNG)

`if item combo >= 3 not working`
``````
2353:2417:2516,{ bonus bAgi,3; bonus bMaxHPrate,5; bonus bMaxSPrate,5; }
``````
https://github.com/rathena/rathena/blob/master/db/re/item_combo_db.txt#L183
![Capture](https://user-images.githubusercontent.com/60462533/101593770-17a6b600-3a23-11eb-9eab-bf7263e7076a.PNG)

`if item combo >= 3 not working`
``````
2357:2421:2524:5171,{ bonus bAllStats,1; }
``````
https://github.com/rathena/rathena/blob/master/db/re/item_combo_db.txt#L188
![Capture](https://user-images.githubusercontent.com/60462533/101593874-4b81db80-3a23-11eb-950d-e47fcf0629e4.PNG)

**Comment by Atemo** [comment]
https://github.com/rathena/rathena/pull/5561

**Comment by idk-whoami** [comment]
> #5561

thanks to @Atemo it works
