### ISSUE TITLE
Tiger Cannon bug

### ISSUE THREAD

**Issue by limitro** [rathena/rathena#561]
Hi.
After using the Tiger Cannon ingame, the HP did not reduce...

Using latest rA

![tiger](https://cloud.githubusercontent.com/assets/9300961/9101629/96721f62-3be9-11e5-9fb6-d3d1a09c3c30.png)

**Comment by firecroll** [comment]
Thats rare, working correcly on my server.

http://1.1m.yt/yHZCEPcko.png

http://2.1m.yt/oEjM12RH.png

**Comment by reunite-ro** [comment]
ive experienced not reduce too

**Comment by limitro** [comment]
@firecroll have you tried in PvP? With other players?

**Comment by firecroll** [comment]
Here are the SS:

http://3.1m.yt/6bw8_hwhu.png

http://2.1m.yt/JrLqmAf4C.png

TC caster without combo or FC, just TC, for any doubt you might have as how i did used the skill.

But seems aleos confirmed the bug, maybe he was able to reproduce it.
Dont know why i cant.
