### ISSUE TITLE
Boss cute pet must have Boss mark beside their name

### ISSUE THREAD

**Issue by eppc0330** [rathena/rathena#5622]
- Client Date : 20200603

- Server Mode : Renewal

- Description of issue :

![mvpetmark](https://user-images.githubusercontent.com/47050704/101991244-b9155c80-3cee-11eb-8de6-d0164d2834ef.png)
Pet still doesn't have MVP mark on 2020 client.

In official KRo Boss PET has Boss mark like this:
![moonlightpet](https://user-images.githubusercontent.com/47050704/101991282-f24dcc80-3cee-11eb-878a-0501b6cc6dd1.jpg)![캣오나인](https://user-images.githubusercontent.com/47050704/102696307-bb3c6580-4270-11eb-80c1-5379fee5d8c9.png)
THESE TWO ARE ALL PETS, NOT MONSTERS.

I want to know how to change it.

P.S. this is not about boss name, cute pet name. Pet must also have BOSS mark on their name, like a BOSS monster

**Comment by randell1993** [comment]
It works on 20200902

![image](https://user-images.githubusercontent.com/28072522/102014193-c6365800-3d8f-11eb-9824-9aeab24fc707.png)

**Comment by eppc0330** [comment]
Can you tell me how to do it? If it works on it, it must does on 20200603 too, because boss pet was updated several years ago.

Is there something boss pet setting in db?

**Comment by eppc0330** [comment]
> It works on 20200902
> 
> ![image](https://user-images.githubusercontent.com/28072522/102014193-c6365800-3d8f-11eb-9824-9aeab24fc707.png)

Maybe its about lua..? I have tried 20200902 but there's still no Boss mark. How to do it...? Teach me please.

**Comment by aleos89** [comment]
![image](https://user-images.githubusercontent.com/3521753/102260596-a95c6a80-3ede-11eb-8aca-43af8a874e55.png)

Works fine for me with d065de4.

**Comment by eppc0330** [comment]
> ![image](https://user-images.githubusercontent.com/3521753/102260596-a95c6a80-3ede-11eb-8aca-43af8a874e55.png)
> 
> Works fine for me with [d065de4](https://github.com/rathena/rathena/commit/d065de4ba0e0d71c0231343c647d0118bced4ba2).

Maybe about mob_db.... are your server using mob_db.yml? Cause mine is txt

**Comment by eppc0330** [comment]
> ![image](https://user-images.githubusercontent.com/3521753/102260596-a95c6a80-3ede-11eb-8aca-43af8a874e55.png)
> 
> Works fine for me with [d065de4](https://github.com/rathena/rathena/commit/d065de4ba0e0d71c0231343c647d0118bced4ba2).

On second thouhgt I think your screenshot seems like monster MOONLIGHT. Is that your MOONLIGHT pet..?
Please check if that is your pet and tell me.

**Comment by aleos89** [comment]
Yes, the hash I'm using is the latest as of yesterday so it contains mob_db as YAML. And no, the monster is not my pet, you can tell because I'm hidden from her attacking me and she has slave monsters.

You didn't provide a hash in your initial report, but I think you're missing this: #5559

**Comment by eppc0330** [comment]
> Yes, the hash I'm using is the latest as of yesterday so it contains mob_db as YAML. And no, the monster is not my pet, you can tell because I'm hidden from her attacking me and she has slave monsters.
> 
> You didn't provide a hash in your initial report, but I think you're missing this: #5559

Thanks for reply. First #5559 is applied already on my server.

Sorry for initial report..? I don't know well about rule of this site yet...

Anyway  I cant catch the point because Im talking about pet name, not monster name.

Boss monster has MVP mark, but my MVP pet doesn't... 

![월야](https://user-images.githubusercontent.com/47050704/102366219-bc189180-3ffb-11eb-8a27-020c6c660749.jpg)
This screenshot is pet: MOONLIGHT2 from official KRO server and pet also has same MVP mark as MVP monster. 
I thought now rathena also has applied that pet MVP mark. 

Am I missunderstanding...? Sorry my bad English.
