### ISSUE TITLE
Dragon Breath in Landprotector

### ISSUE THREAD

**Issue by gidzdlcrz** [rathena/rathena#5626]
* **rAthena Hash**:  Latest

* **Client Date**:  2018/2020

* **Server Mode**:  Both

* **Description of Issue**:  Well. This is about Dragon Breath / Water and Landprotector. Im not really sure if it is bug or what. the      **flag: IgnoreLandProtector: false** doesnt work. By default it can bypass the LP. Im trying to set it as false to not ignore the landpro.

  * Result:     tried doing  IgnoreLandProtector: false didnt work
  * Expected Result:  It should work because thats FLAG.
  * How to Reproduce:  UseDragon Breath to someone  with LP in it
  * Official Information:  im pretty sure kRO does patch it before and decided to revert back.
  

* **Modifications that may affect results**:  none

**Comment by aleos89** [comment]
That's because Dragon Breath isn't a unit skill. The `IgnoreLandProtector` flag is meant for unit type skills. If the behavior of Dragon Breath has changed, can you show me a kRO changelog or recent video of the behavior and I can make the changes.

**Comment by aleos89** [comment]
Current behavior matches kRO.

**Comment by Styx1592** [comment]
i see in wiki
(Level 200/70 Update)
Skill are now blocked by [Magnetic Earth]

someone can help to update ?
