### ISSUE TITLE
Pet talking unallowed in lately client?

### ISSUE THREAD

**Issue by eppc0330** [rathena/rathena#5627]
- Client Date : 20200603

- Server Mode : Renewal

- Description of issue 

I have upgraded rathena version from 2018 to 2020 and I found there's no option about "pet_convert_class" in pet_db.yml

Is it disabled on lately client? I really like pet talking system... Is it possible to make them talk again?

**Comment by aleos89** [comment]
I'm assuming you meant `talk_convert_class`? This was dropped in our YAML conversion because it was no longer properly working. It was a hackish attempt to replace the pet's mob ID with another. If you are wanting more pets to talk it would be best to expand your client `data\pettalktable.xml` with any custom pets.

**Comment by eppc0330** [comment]
> I'm assuming you meant `talk_convert_class`? This was dropped in our YAML conversion because it was no longer properly working. It was a hackish attempt to replace the pet's mob ID with another. If you are wanting more pets to talk it would be best to expand your client `data\pettalktable.xml` with any custom pets.

Okay I understood it's impossible... another question okay? 

I know have applied 20200902 ver client.
![101991244-b9155c80-3cee-11eb-8de6-d0164d2834ef](https://user-images.githubusercontent.com/47050704/102258621-743d3000-3f51-11eb-9a90-d23a4151bdd2.png)
But my pet still doesnt have MVP mark on their name. 

Other said it works well on 20200902 but mine is not...
![제목 없음](https://user-images.githubusercontent.com/47050704/102258749-946cef00-3f51-11eb-92c9-4676a3c47dd1.png)

Can you teach me where can I fix this? I have expecting and waiting  this for over 2 years..

**Comment by aleos89** [comment]
We can discuss this in your other issue since this one isn't related.

**Comment by eppc0330** [comment]
> I'm assuming you meant `talk_convert_class`? This was dropped in our YAML conversion because it was no longer properly working. It was a hackish attempt to replace the pet's mob ID with another. If you are wanting more pets to talk it would be best to expand your client `data\pettalktable.xml` with any custom pets.

Wait, did you mean just `talk_convert_class` is disabled, and pets are still talking? My pets are not talking at all even their intimacy is MAX.

**Comment by aleos89** [comment]
Yes, that config option in the pet_db no longer exists. My understanding of it is that you would give the mob ID of another pet that can talk so it can mimic the text. The text is pulled from the XML file I detailed in my previous post. Just make sure your XML contains the pet you want to talk unless Gravity removed pet talking completely in the new clients (I haven't tested this in years).

**Comment by eppc0330** [comment]
> Yes, that config option in the pet_db no longer exists. My understanding of it is that you would give the mob ID of another pet that can talk so it can mimic the text. The text is pulled from the XML file I detailed in my previous post. Just make sure your XML contains the pet you want to talk unless Gravity removed pet talking completely in the new clients (I haven't tested this in years).

What if entire pets don't talk...? I have tested all in pet_db.yml list but none of them talk.
