### ISSUE TITLE
Mechanic Infrared Scan should also cancel shadow form

### ISSUE THREAD

**Issue by Paoly28** [rathena/rathena#563]
https://www.youtube.com/watch?v=90DQ5iO94IE

around 1:18 SC casts Shadow Formation , mechanic cast infrared scan and cancels it.

tried it alot of times and IS never canceled SF.

**Comment by Paoly28** [comment]
i think this also should be the case with other detection skills such as , Sura : Earthshaker , GC : Phantom Manace, Hunter : detect, Ranger : Sensitive Keen ,

**Comment by MrAntares** [comment]
As I remember, every detection skill should cancel shadow form

**Comment by Paoly28** [comment]
yeah problem is only ruwach and sight cancels it currently.

**Comment by aleos89** [comment]
It would be nice to have a full list of this laid out so we know specifically which detection skills work with this or not. The only reason we are only detecting with Sight and Ruwatch is because those are the only two skill listed in the description from the 2011 post balance:
```
Detecting skills such as Ruwach and Sight have a chance of removing Shadow Form. Higher level of Shadow Form have a chance of resisting detecting skills. Shadow Form removal success chance is calculated once every 2 seconds.
```

**Comment by RagnarokNova** [comment]
Testing all detect skills I can think of. So far Ranger's Sensitive Keen does remove it.
http://i.imgur.com/4JXTjmm.png Will be updating this comment.
