### ISSUE TITLE
Card Combo more than 2 Bug Stats

### ISSUE THREAD

**Issue by starragnarok2020** [rathena/rathena#5632]
* **rAthena Hash**:  d158603

* **Client Date**:  20180621

* **Server Mode**:  pre-renewal

* **Description of Issue**:  https://github.com/rathena/rathena/blob/master/db/pre-re/item_combo_db.txt
  * Result: When we equip card like cruiser,dragontail,merman,aligator,anolian card got stats
![x](https://user-images.githubusercontent.com/73898279/102362557-1eb36280-3fe7-11eb-98f3-fac319aacbb8.PNG)
and unequip and equip again stats not added
![xx](https://user-images.githubusercontent.com/73898279/102362625-312d9c00-3fe7-11eb-908d-8a15403b4264.PNG)

just realized the combo set more than 2 items happens like this
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Can you apply #5561 and see if that resolves your issue.
