### ISSUE TITLE
Backtrack Issue

### ISSUE THREAD

**Issue by DevNoName** [rathena/rathena#5637]
* **rAthena Hash**:  fatal: Needed a single revision

* **Client Date**: 
First: 2018-06-21aRagexeRE
2nd: 2018-06-20eRagexeRE

* **Server Mode**: 
Pre-Renewal

* **Description of Issue**: 
  * Result: Backtrack Issue
  * Expected Result: 
  * How to Reproduce: Restart the server or start the server and after a few hours (10 hours or more) players will experienced 
   backtrack issue kindly check the video.  

   1st video:
  https://drive.google.com/file/d/1bS3hCwnP4zsZFh7XsmTVBq3l8bZ35F1U/view?usp=sharing

  2nd video:
  https://drive.google.com/file/d/1mvCBnZDUXR_hHv_CiiMjVCzomSOIXsOR/view?usp=sharing

  * Official Information: 

* **Modifications that may affect results**: 
  i only added few custom npc and 1 map only.

**Comment by DevNoName** [comment]
![current](https://user-images.githubusercontent.com/76208477/102624242-b303fd80-417e-11eb-9e87-86946c2ec414.png)

this is my current ram usage when the backtrack issue happen in my server

**Comment by Lemongrass3110** [comment]
As discussed in Discord:
This is not an rAthena issue.
You have it working with a different client (android) and there it works perfectly well.
So this is most likely a client problem.

**Comment by DevNoName** [comment]
> As discussed in Discord:
> This is not an rAthena issue.
> You have it working with a different client (android) and there it works perfectly well.
> So this is most likely a client problem.

i have a test server with same server files/client even if the server uptime is 10+ hrs no backtrack issue.
