### ISSUE TITLE
attachrid not binding the player

### ISSUE THREAD

**Issue by shis218** [rathena/rathena#5638]
* **rAthena Hash**: 1828d20

* **Client Date**: 2020-04-01bRagexe_patched

* **Server Mode**: Renewal

  
  Description of the issue:
 Result: In a function script[called via callfunc] Using attachrid with a valid getcharid isn't working, proofs of it: playerattached() returning 0 and error [Error]: buildin_dispbottom: fatal error ! player not attached! / on console also not being able to get that player local variables
 ;
 Expected Result: It should bind the rid to set and get the variables,not even attaching anything
 
  Minimun code that is able that is able to reproduce this error [testing on moc_para01 /edengrou, teleporting on the same floor]:
  
//glitch show, first click on iniciaTeste, then to tester1, return on first room and click on tester1 again, it will call the function to bring all players that talked to him
```
-	script	iniciaTeste	-1,{
	 //Number of players that clicked on it
	$v2=0;
	$startgame=0;
	setarray $JogadorNames$[0],"","","","","","","","","","";
	end;
}

-	script	Ateste	-1,{
	$v2++;			//Increase the number of players 
	$JogadorNames$[$v2]=strcharinfo(0); //Bindplayername
	atcommand "#warp "+$JogadorNames$[$v2]+" moc_para01 165 35"; //Sends the player to another room, proof that his name still on that array
	.@`minjogadores`=2;
	set playervarAB,rand(1,800);  //Set a local player var to get recovered later, one of the problems that I want to use rid later to recover, since access those variables are interesting
	if(($v2>=.`@minjogadores`)&&$startgame==0){ //If there is at least .@`minjogadores` and the game not started, start a timer to start the game, when timer ends, check if the conditions still true
		sleep 3000;
		mapannounce "moc_para01","Starts in 3s",0;
		sleep 3000;
		callfunc "Ateste3";
}
end;
}
-	script	Ateste2	-1,{
	mapannounce "moc_para01","Start was forced",0;
	callfunc "Ateste3"; //This npc force the start game even if there is no timer
	end;
}
function	script	Ateste3	{
	$startgame=1;
	mapannounce "moc_para01","Começando",0; 	
	sleep 1000;
	for( .`@i `= 1; .@i <= $v2; .`@i++` ){ 
				atcommand "#warp "+$JogadorNames$[.`@i`]+" moc_para01 176 +"+(30+.`@i`);  //Respawn em linha reta
				.@g=getcharid(0, $JogadorNames$[.`@i`]);
				sleep 5000;
				mapannounce "moc_para01","Jogador "+$JogadorNames$[.`@i`]+" ",0;
				mapannounce "moc_para01","Jogador "+.`@g`+" ",0;   //This expect result the player id, that got by getcharid and normally works fine
				detachrid;  
				attachrid(.`@g`);   //Even tried to put the brute value using the result of last broadcast
				sleep 1000;
				mapannounce "moc_para01","Jogador "+playerattached()+" ",0;  //Returning 0 showing the attach wasnt possible
				dispbottom "Teste de impostor";  //Returning error on console
				if(playervarAB>0){  //Check the playervar    //If dispbottom code not here, it results in another error about not able to get this var
					mapannounce "moc_para01","Variavel do jogador: "+playervarAB+" ",0;
				}
	}
	end;
}
moc_para01,22,27,5	duplicate(iniciaTeste)	IniciaTeste#eden	555	
moc_para01,22,25,5	duplicate(Ateste)	Tester1#eden	555	
moc_para01,176,37,5	duplicate(Ateste2)	Tester2#eden	555	
```

**Comment by Atemo** [comment]
```

*sleep {<milliseconds>};
*sleep2 {<milliseconds>};
*awake "<NPC name>";

These commands are used to control the pause of a NPC.
sleep and sleep2 will pause the script for the given amount of milliseconds.
Awake is used to cancel a sleep. When awake is called on a NPC it will run as
if the sleep timer ran out, and thus making the script continue. Sleep and sleep2
basically do the same, but the main difference is that sleep will not keep the rid,
while sleep2 does. Also sleep2 will stop the script if there is no unit attached.
```
__sleep will not keep the rid__
Invalid !

**Comment by shis218** [comment]
> 
> 
> ```
> 
> *sleep {<milliseconds>};
> *sleep2 {<milliseconds>};
> *awake "<NPC name>";
> 
> These commands are used to control the pause of a NPC.
> sleep and sleep2 will pause the script for the given amount of milliseconds.
> Awake is used to cancel a sleep. When awake is called on a NPC it will run as
> if the sleep timer ran out, and thus making the script continue. Sleep and sleep2
> basically do the same, but the main difference is that sleep will not keep the rid,
> while sleep2 does. Also sleep2 will stop the script if there is no unit attached.
> ```
> 
> **sleep will not keep the rid**
> Invalid !

[Error]: buildin_dispbottom: fatal error ! player not attached!
[Debug]: Function: dispbottom (1 parameter):

Removed every sleep, still giving the same error [and this time dont even put on broadcast the texts]
