### ISSUE TITLE
hotkey doesn't be saved on 20200902

### ISSUE THREAD

**Issue by eppc0330** [rathena/rathena#5639]
* **rAthena Hash**: 

* **Client Date**: 20200902

* **Server Mode**: Renewal

* **Description of Issue**: 
 Hotkey reset everytime I launch client 20200902, while 20200603 client saves hotkey very well.
Im using official KRO hotkey.lub.

**Comment by Lemongrass3110** [comment]
You need to set up the HTTP REST services.

**Comment by eppc0330** [comment]
> You need to set up the HTTP REST services.

Sorry what is HTTP REST services..?

**Comment by Lemongrass3110** [comment]
https://github.com/secretdataz/athena-web-service/
