### ISSUE TITLE
Got Stuck Skid Trap

### ISSUE THREAD

**Issue by croxinuz** [rathena/rathena#564]
hi, I'm Using Git Version 29/07/2015
on my server,you was got stuck 1-2 seconds when you crossing Skid Trap.

Video Link :
https://youtu.be/1BtEXnlZEY0

:+1:

**Comment by Playtester** [comment]
Skid Trap stops you for 3 seconds, it's an official effect.

See here: https://github.com/rathena/rathena/commit/902c920b734cdaa0a13650528a6075937edfb95c
