### ISSUE TITLE
View of garment & character sprite problem on specific angle & zoom in

### ISSUE THREAD

**Issue by eppc0330** [rathena/rathena#5643]
* **rAthena Hash**: 

* **Client Date**: 20200902

* **Server Mode**: Renewal

* **Description of Issue**: 

Some map enforce player's screen with the lowest angle(ex. e_tower) and on that angle garment comes up on character.

https://user-images.githubusercontent.com/47050704/102709479-70f9c980-42ee-11eb-8722-86121e7cc9cd.mp4
garment comes up

https://user-images.githubusercontent.com/47050704/102709482-7525e700-42ee-11eb-89ac-20612ce17a3e.mp4
zoom in

https://user-images.githubusercontent.com/47050704/102709486-7820d780-42ee-11eb-9566-0c0c3e11a4fb.mp4
zoom in 2

**Comment by Balferian** [comment]
this is client problem, not server.

**Comment by eppc0330** [comment]
> this is client problem, not server.

You mean lua & lub?

**Comment by RagnaWay** [comment]
Cliente Hexed, Use NEMO.

**Comment by eppc0330** [comment]
> Cliente Hexed, Use NEMO.
FIX CAMERA ANGLES(RECOMMENDED)
This one? Actually this is already checked.

**Comment by aleos89** [comment]
As other stated this is related to the client or modifications done to the client. You can report the issues to the creator of the client mod or get more support in the forums.
