### ISSUE TITLE
Item dummy crash map-server

### ISSUE THREAD

**Issue by mplaten** [rathena/rathena#5646]
* **rAthena Hash**: 

 dfa1df7

* **Client Date**: 

 20200401

* **Server Mode**: 

 boths

* **Description of Issue**: 
  * Result:  
Item dummy data crash map-server 

GDB message:

![image](https://user-images.githubusercontent.com/10901983/103159544-7ac97400-47a9-11eb-8b8c-15fc4306172a.png)

  * Expected Result:  
  * How to Reproduce: 
 First: Create a NPC to mount dinamic shops using npcshopitem and npcshopadditem with an no existing item at db.
 Second: Try callshop.
  * Official Information: 
  

* **Modifications that may affect results**: 
  
  
Use sql itens

**Comment by gidzdlcrz** [comment]
I believe this was already fixed. Try here https://github.com/rathena/rathena/pull/5552

**Comment by mplaten** [comment]
@gidzdlcrz

I test with #5552, but still crashing...

**Comment by Lemongrass3110** [comment]
Could you tell us what you are doing?
And the GIT hash that you stated does not exist, so please tell us the correct one.

**Comment by mplaten** [comment]
> Could you tell us what you are doing?
> And the GIT hash that you stated does not exist, so please tell us the correct one.

Sorry, i update the first post with all informations and correct hash

**Comment by Lemongrass3110** [comment]
Can you provide gdb bt full please.

**Comment by mplaten** [comment]
> Can you provide gdb bt full please.

![image](https://user-images.githubusercontent.com/10901983/103161246-abb3a400-47bd-11eb-8601-465a65d3f548.png)

**Comment by Lemongrass3110** [comment]
Can you provide us your script please?

**Comment by mplaten** [comment]
> Can you provide us your script please?

Yes, i can provide. But i still testing and after read, i think de dummy item is not loaded.

The map-servers crashs too when use this command: @item2 1599 1 1 0 0 18400 0 0 0; where '18400' can be any inexistent item.
gdb bt full:

![image](https://user-images.githubusercontent.com/10901983/103491327-babfd500-4e01-11eb-80f6-1af81ff99714.png)
![image](https://user-images.githubusercontent.com/10901983/103491334-d0cd9580-4e01-11eb-8f91-c9f3a4db42ed.png)
![image](https://user-images.githubusercontent.com/10901983/103491342-e0e57500-4e01-11eb-9147-9af9ab768d5a.png)

I'll make more tests

**Comment by mplaten** [comment]
Yeah, after read more, i think the dummy item is not loaded when use sql itens
