### ISSUE TITLE
Card Location Left_Accessory not working

### ISSUE THREAD

**Issue by AsurielRO** [rathena/rathena#5652]
* **rAthena Hash**:  dfa1df7

* **Client Date**:  20200304

* **Server Mode**:  Renewal

* **Description of Issue**:  
  * Result:  Like what the tittle said the item cannot be compounded using Left_Accessory for card, But when you try to use Both_Accessory its working.
  * Expected Result: 
  * How to Reproduce:  Use any left accessories and try to insert it on sloted accessories 
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by Atemo** [comment]
Card with specific Left_Accessory can only be inserted in Left_Accessory equipment https://github.com/rathena/rathena/issues/4977
