### ISSUE TITLE
Missing Woodie Card (ID 4558)

### ISSUE THREAD

**Issue by RagnaWay** [rathena/rathena#5653]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/dfa1df7de65906f3e70ec6cccc20d6a508bb5ea4

* **Client Date**: 

2020-09-02

* **Server Mode**: 

Renewal

* **Description of Issue**: 
Missing Woodie Card on Item DB.

* **Modifications that may affect results**: 

> - Id: 4558
>     AegisName: Woodie_Card
>     Name: Woodie Card
>     Type: Card
>     Buy: 20
>     Weight: 10
>     Locations:
>       Garment: true
>     Flags:
>       BuyingStore: true
>     Script: |
>       bonus2 bSubEle,Ele_Earth,20;
>       bonus3 bAutoSpellWhenHit,"PR_KYRIE",2,20;

**Comment by Atemo** [comment]
If you are wondering, I wouldn't mind if you opened a pull request!
