### ISSUE TITLE
Bug MVP Bonus EXP with @mi command

### ISSUE THREAD

**Issue by Skystar18** [rathena/rathena#5656]
* **rAthena Hash**: 1dd767bf4

* **Client Date**: 2018-06-21

* **Server Mode**:  Pre-Renewal

* **Description of Issue**: MVP Bonus EXP doesn't appear correctly after updating rathena
  * Result: MVP Bonus EXP shows a weird long number.  Please see below picture 
  * Expected Result: Correct MVP Bonus EXP. 
  * How to Reproduce: update rathena to the latest and use @mi command on any MVP mob. In my case i use mob ID 1086

**Before updating rathena**
![image](https://user-images.githubusercontent.com/70919453/103317410-bace6800-49f0-11eb-9643-ba35adf7181c.png)

**After updating rathena**
![image](https://user-images.githubusercontent.com/70919453/103317002-d9802f00-49ef-11eb-97af-db5a55bf27c5.png)

**Comment by akiyamamio16** [comment]
Does it give that huge MVP Bonus EXP when you killed it?

**Comment by Skystar18** [comment]
It doesn't give a huge MVP Bonus EXP. It gives the right bonus but the Displayed Info from @mi is incorrect.
