### ISSUE TITLE
Manhole + Hells Plant.

### ISSUE THREAD

**Issue by limitro** [rathena/rathena#566]
Hi there.

When you place Manhole, and someone goes into the manhole...
then all your Hell Plants that you try to place around the manhole will be sucked into the manhole...

Is this normal?

If there are nobody inside the manhole...then the Hell Plants that you place around the manhole will not dissapear....

**Comment by aleos89** [comment]
Hell Plant should not be pulled into Manhole, just the player.

When you say the Hell Plant doesn't disappear, you mean after the duration has passed for Hell Plant they still sit around?

**Comment by limitro** [comment]
Hi.
What I mean is that, the hell plant got pulled into the manhole together with the player.

Example, 
1. if you use Manhole and hell plant = everything is fine.
2. If a player walks into that Manhole surrounded with hellplant, then all hell plants will dissapear as well.

**Comment by cydh** [comment]
it's bug then, Manhole should only suck BL_CHAR.
