### ISSUE TITLE
Is it possible making pet talking script?

### ISSUE THREAD

**Issue by eppc0330** [rathena/rathena#5660]
**Is your request related to a missing feature?**  no

**Describe the solution you'd like**  

After convert pet_db.txt to pet_db.yml, all pets, including official pets, don't talk. So I have tried script atcommand "pettalk blabla"; on pet bonus and it works.
Then, is it possible to make pet talking by questscript on npc/ folder? I finally want to restore all pet talks in all situations like talkings on feeding, on performances, on dead, etc. 

**Describe alternatives you've considered**

**Additional context**

**Comment by Daegaladh** [comment]
You could use the unittalk script command

**Comment by eppc0330** [comment]
> You could use the unittalk script command

How to make pet talk on specific timing?
Like on performance. I dont know script command about get performance timing or attacking timing, etc.

**Comment by Daegaladh** [comment]
You would need to add custom triggers/labels in the src and combine those with unittalk and getpetinfo.
