### ISSUE TITLE
Server wont Log Public Chat

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#5661]
* **rAthena Hash**: dfa1df7

* **Client Date**: 20200401

* **Server Mode**: RENEWAL

* **Description of Issue**: First using log_chat: 63, then server wont save log chat, only whisper chat will saved.
  * Result: 
  * Expected Result: 
  * How to Reproduce: 

Create new logs database on localhost database using https://github.com/rathena/rathena/commits/master/sql-files/logs.sql

Use NULL test script. it encountered the following error.

INSERT DELAYED INTO chatlog (time, type, type_id, src_charid, src_accountid, src_map, src_map_x, src_map_y, dst_charname, message) VALUES (NOW(), 'O', '0', '150468', '2000021', 'amatsu', '198', '84', NULL, 'testmessage')

![gambar](https://user-images.githubusercontent.com/8316103/103981057-996d3900-51b3-11eb-86b2-534cdfc83d1b.png)

But when I compile the map server with Visual Studio, the map server can perform input queries and successfully log chat.

So I think when rathena is compiled with visual studio, it doesn't use NULL but ''. So that the query can be entered in sql without error.

but when compiled using GCC version 7.3.1 the map server will use NULL in sending queries to SQL. because there is the word NULL, the query cannot enter SQL.

  * Official Information: 
  

![gambar](https://user-images.githubusercontent.com/8316103/103412899-f1031780-4ba9-11eb-80b2-661f2fa0545a.png)

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment]
Seems like you have a wrong definition of your chatlog table.
See sql-files/logs.sql:
```
CREATE TABLE IF NOT EXISTS `chatlog` (
  `id` bigint(20) NOT NULL auto_increment,
  `time` datetime NOT NULL,
  `type` enum('O','W','P','G','M','C') NOT NULL default 'O',
  `type_id` int(11) NOT NULL default '0',
  `src_charid` int(11) NOT NULL default '0',
  `src_accountid` int(11) NOT NULL default '0',
  `src_map` varchar(11) NOT NULL default '',
  `src_map_x` smallint(4) NOT NULL default '0',
  `src_map_y` smallint(4) NOT NULL default '0',
  `dst_charname` varchar(25) NOT NULL default '',
  `message` varchar(150) NOT NULL default '',
  PRIMARY KEY  (`id`),
  INDEX (`src_accountid`),
  INDEX (`src_charid`)
) ENGINE=MyISAM AUTO_INCREMENT=1;
```
As you can see the dst_charname column has a not null definition with a default value. So your error message is telling us that you created this table wrong.

I have also just tried it and it works perfectly fine.
![grafik](https://user-images.githubusercontent.com/3517879/103489595-fbc1e480-4e15-11eb-8794-760b08176e27.png)
![grafik](https://user-images.githubusercontent.com/3517879/103489602-041a1f80-4e16-11eb-8f5b-4d716473ad23.png)

**Comment by mazvi** [comment]
I didn't experience this before on 323db7e, I gitpulled it up to dfa1df7.

Nothing I changed in the log database, suddenly the server does not log.

i am using centos and mariadb operating systems, i don't know if it's an operating system problem or what?

**Comment by mazvi** [comment]
I will explain what happened at this time. On the local server I use the test script you provide. it encountered the following error.

INSERT DELAYED INTO chatlog (time, type, type_id, src_charid, src_accountid, src_map, src_map_x, src_map_y, dst_charname, message) VALUES (NOW(), 'O', '0', '150468', '2000021', 'amatsu', '198', '84', NULL, 'testmessage')

![gambar](https://user-images.githubusercontent.com/8316103/103862509-d2dd7000-50f1-11eb-84a9-af11b8479cd8.png)

But when I compile the map server with Visual Studio, the map server can perform input queries and successfully log chat.

So I think when rathena is compiled with visual studio, it doesn't use NULL but ''.

but when compiled using GCC version 7.3.1 the map server will use null in sending queries to SQL.
