### ISSUE TITLE
MVP EXP BUG

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#5662]
* **rAthena Hash**: dfa1df7

* **Client Date**: 20200401

* **Server Mode**: RENEWAL

* **Description of Issue**: 
  * Result: 
  * Expected Result: 
  * How to Reproduce: 

Use config bellow:

// Rate at which exp. is given. (Note 2)
base_exp_rate: 10000

// Rate at which job exp. is given. (Note 2)
job_exp_rate: 10000

// MVP bonus exp rate. (Note 2)
mvp_exp_rate: 2000

then test to baphomet
https://ratemyserver.net/index.php?mob_name=baphomet&page=re_mob_db&f=1&mob_search=Search

the original exp:
Base Experience | 396525
Job Experience | 334106
MVP Experience | 198262

but after i test on server i got battle message bellow:
'3965250' Base Experience acquired. (its only 10x)
'3341060' Job Experience acquired. (its only 10x)
'3965240' Base Experience acquired. (its true 20x)

base exp and job exp must be 100x related that configuration not 10x

  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by qwerty7vp** [comment]
exp penalty from lv different ??
diff > 31 Lv = 10%

**Comment by mazvi** [comment]
yes, now MVP also got a penalty exp?

**Comment by Lemongrass3110** [comment]
Yes they always had. It was just wrong.
See #5463 and 81e7d8e.
