### ISSUE TITLE
Oboro Cannot Using Kunai

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#5663]
* **rAthena Hash**: dfa1df7

* **Client Date**: 20200401

* **Server Mode**: RENEWAL

* **Description of Issue**: Oboro Cannot Using Kunai, using normal player (not GM)
Set alll skill on this player, then use try insert Fell Poison Kunai to equip Window

than will be ERROR:
Can't equip this item because you don't meet the requirements.

below item must be can used by oboro

Shuriken: 13250
Nimbus Shuriken: 13251
Flash Shuriken: 13252
Sharp Leaf Shuriken: 13253
Thorn Needle Shuriken: 13254
Fell Poison Kunai: 13259
Explosive Kunai: 13294

  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by randell1993** [comment]
- Id: 13294
    AegisName: Explosive_Kunai
    Name: Explosive Kunai
    Type: Ammo
    SubType: Kunai
    Buy: 100
    Weight: 1
    Attack: 50
    Jobs:
      Ninja: true
      **KagerouOboro: true** <--- ADD THIS ON ALL OF THE KUNAIS i guess it was missed or maybe the inheritance 
    Locations:
      Ammo: true
    EquipLevelMin: 100
    Script: |
      bonus bAtkEle,Ele_Neutral;
