### ISSUE TITLE
Updating Server is not working because SQL structure was changed without upgrade script

### ISSUE THREAD

**Issue by EbilPanda** [rathena/rathena#5677]
* **rAthena Hash**:  7336477f874ea66fcc800d6985b0c397ddf71e84
* ** rAthena old hash**: be3aee7f74c13b0a12a994658a0eea81afcc528f

* **Client Date**:  not relevant

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: After updating the server and running all recent sql upgrade scripts the server is not starting properly as it cannot read the item database (e.g. `item_db2_re` or `item_db_re`). After investigating the issue, it seems the item dbs sql structure was modified in the big yml-update. This change of the database is however not reflected in the upgrade scripts / combability scripts / tools / wherever
  * Expected Result: having a working upgrade script to update sql to work!
  * How to Reproduce: install a server from before the yml update with SQL -> update the server to yml/later and upgrade database with the scripts -> see whether its working or not (it will not!)
  * Official Information: ... not needed
 
* **Modifications that may affect results**: items (adjusted, or custom items) put in to the database (e.g. `item_db2_re` or `item_db_re` ) -> which ofc need an update to match the new structure (like mapping the old numeric values to the new boolean field values)

**Comment by mazvi** [comment]
Now database item rAthena using YAML i think

**Comment by EbilPanda** [comment]
if rAthena would not support SQL anymore - why is it then still reading the database if the flag is active? and why are there compatibility views to use with e.g. FluxCP made and shipped with it?
If there was such a thing made -> where is the upgrade script for existing item databases to update? -> missing update component -> bug or however you want to name it :)

**Comment by Atemo** [comment]
There is no tool to convert your old SQL to the new format.
But you can easily convert your old SQL to old item_db.txt https://rathena.org/board/topic/112154-sql-item-database-to-txt/?do=findComment&comment=330236
then use the tool csv2yaml to convert the txt to yaml and yaml2sql to convert the yaml to SQL (3 replaces and 2 clicks).
