### ISSUE TITLE
Please check these Two issues!!!

### ISSUE THREAD

**Issue by tmav94** [rathena/rathena#568]
Please guys, check this two issues!

* [ ] Shura (GENTLETOUCH) are cure Emperium At WoE
* [ ] Shadow Chaser (Mask / Strip) working at players with Full Chemical Protection At WoE
* [ ] Players getting levels when kill other inside the Castles in WoE

**Comment by nanakiwurtz** [comment]
git commit? re/pre-re? client date?

**Comment by tmav94** [comment]
Latest Git

Renewal

#ifndef PACKETVER
	#define PACKETVER 20130807

**Comment by cydh** [comment]
> Players getting levels when kill other inside the Castles in WoE

tbh, I laughed. xD  something like this in my mind: "congratulations! u unlock new feature!"
can u give screen shots, we will check it and other issues.

**Comment by tmav94** [comment]
The next woe in my server is tomorrow! I'll send all screenshots... Thx for watching

**Comment by tmav94** [comment]
About the Gentletouch at Emperium

![screenragnatrek057](https://cloud.githubusercontent.com/assets/8236218/9263454/85b5d5f0-41f3-11e5-8923-2d9f34ac9ae0.jpg)
![screenragnatrek055](https://cloud.githubusercontent.com/assets/8236218/9263456/85b9327c-41f3-11e5-8911-ae9543c26777.jpg)
![screenragnatrek056](https://cloud.githubusercontent.com/assets/8236218/9263455/85b91094-41f3-11e5-9e1f-041689c09be0.jpg)

**Comment by aleos89** [comment]
1) Need some more info, I'm not sure about this.
2) Masquerade - Weakness bypasses FCP.
3) That's not related to anything in rA by default. You must have something that is doing that.

**Comment by cydh** [comment]
for Gentletouch (Cure), I can confirm it by looking the source, there's `status_heal()` in skill_castend_nodamage.
btw, ur pics are in descending order. it's something. xD
