### ISSUE TITLE
NPC_MAXPAIN skill mechanism errors

### ISSUE THREAD

**Issue by eppc0330** [rathena/rathena#5684]
* **rAthena Hash**: #5656

* **Client Date**: 20200902

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: 
  
     1. Maxpain deals reflect damage to only attacker.

     2. Damage displayed as ALL MISS with Maxpain status.

     3. Maxpain does not reflect magic damage.

  * Expected Result: 
  
     1. -> Maxpain damage should be splashed, so could deal all character in a screen.

     2. -> Basically monster still gets damage on Maxpain status. 
              Several instance bosses ignore damage durinng Maxpain's on (ex. Celine Kimi in Horror Factory, Amdaraise in Old Glast 
              Heim Challenge Mode).

     3. -> Maxpain should reflect magic damage too, not only weapon damage.

  * How to Reproduce: 
  * Official Information: 
     https://youtu.be/VUIgb8kDgNg
     See **3:35**. This is a video from official KRo, playing with Warlock character, dealing with WL_CHAINLIGHTNING, which is 
     magic skill.

     Add : 
https://youtu.be/nwu3eEdOrDg
     See **6:16**. 
![전사자맥페](https://user-images.githubusercontent.com/47050704/105350166-11b11100-5c2e-11eb-93b3-1c0cedcaeccc.gif)
     Monster, from Tomb of the Dead, gets damage during Maxpain.

  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Fixed in 2896ae2.
