### ISSUE TITLE
Items in Overseas Care Packages are missing

### ISSUE THREAD

**Issue by Latiosu** [rathena/rathena#5688]
* **rAthena Hash**: 51b6695c

* **Client Date**: 2020-04-01b

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Numerous items found in Overseas Care Package are missing from item_db
  * Expected Result: Items are present in item_db
  * How to Reproduce: Item ids are not present in item_db_*.yml files
  * Official Information: https://irowiki.org/wiki/Kafra_Shop_Box_Archives

* **Modifications that may affect results**: None

**List of Missing Items**
- [Bunker Shield](https://www.divine-pride.net/database/item/2184)
- [Solomon's Key](https://www.divine-pride.net/database/item/2191)
- [Miracle Blue Rose](https://www.divine-pride.net/database/item/5878)
- [Exorcist Glasses](https://www.divine-pride.net/database/item/5916)
- [Monster Fish Gills](https://www.divine-pride.net/database/item/5921)
- [Dragon Knight Eye Patch](https://www.divine-pride.net/database/item/5924)
- [Zealotus Doll](https://www.divine-pride.net/database/item/5975)
- [Antonio's Coat](https://www.divine-pride.net/database/item/15249)
- [Ixion Wing](https://www.divine-pride.net/database/item/18129)
- [Magical Booster](https://www.divine-pride.net/database/item/18720)
- [Old Pink Poo Hat](https://www.divine-pride.net/database/item/18959)
- [Catherina Von Blood](https://www.divine-pride.net/database/item/19163)
- [Guardian Processor](https://www.divine-pride.net/database/item/19170)
- [Black Veil](https://www.divine-pride.net/database/item/19460)
- [Diabolus Wing](https://www.divine-pride.net/database/item/19495)
- [Gardener Shoes](https://www.divine-pride.net/database/item/22050)
- [Gravekeeper Shoes](https://www.divine-pride.net/database/item/22052)
- [Dragon Trainer Shoes](https://www.divine-pride.net/database/item/22058)
- [Hunter Shoes](https://www.divine-pride.net/database/item/22060)
- [Mechanic's Shoes](https://www.divine-pride.net/database/item/22062)
- [Fisherman's Shoes](https://www.divine-pride.net/database/item/22091)
- [Exorcist's Shoes](https://www.divine-pride.net/database/item/22093)
- [Gardener Shoes](https://www.divine-pride.net/database/item/22094)
- [Fallen Angel Shoes](https://www.divine-pride.net/database/item/22096)
- [Dragon Trainer Shoes](https://www.divine-pride.net/database/item/22097)
- [Mechanic Shoes](https://www.divine-pride.net/database/item/22099)
- [Spirit King's Ring](https://www.divine-pride.net/database/item/28394)
- [Yin Yang Talisman](https://www.divine-pride.net/database/item/28560)
- [Rose Bundle A](https://www.divine-pride.net/database/item/23251)
- [Orleans's Bundle A](https://www.divine-pride.net/database/item/23252)
- [Black Shiba Inu Bundle A](https://www.divine-pride.net/database/item/23253)
- [Kardui Bundle A](https://www.divine-pride.net/database/item/23255)
- [Etran Bundle A](https://www.divine-pride.net/database/item/23266)
- [Pororoca Shoes Bundle A](https://www.divine-pride.net/database/item/23294)

**Comment by aleos89** [comment]
Fixed in e4a9a2e.
