### ISSUE TITLE
Forum

### ISSUE THREAD

**Issue by flda1013** [rathena/rathena#569]
Sry that i must write this here but i think your SMPT do not work at the moment.
I want to confirm my Account "Yggdrasill" on the Forum but i do not get any Coformatio Email Adress! Can Somone Help me with this Problem?!

**Comment by cydh** [comment]
the forum itself.. I can't get a touch. xD

**Comment by MrAntares** [comment]
@  Antares	:	(11 August 2015 - 02:51 PM)1.3 M Traffic just by opening the main page.... Surely this is not ok...
@  Antares	:	(11 August 2015 - 02:50 PM)BTW: RUFKM??? the page loads 72 scripts?? Half of them is AD?! Seriously?
@  Antares	:	(11 August 2015 - 02:49 PM)ADMINS: Pz check rathena.org/board... it shows many errors and warnings in the browser console. There are some scripts as well that can't load properly....

**Comment by julia40124009** [comment]
IE can enter forum
but
firefox can't

**Comment by cydh** [comment]
someone need to tell people the trick.
hmmm wait rAthena's FB & Twitter no followers. xDD
