### ISSUE TITLE
Modified Boots need Update

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#5690]
* **rAthena Hash**: 48fca09

* **Client Date**: Not Relevant

* **Server Mode**: RENEWAL

* **Description of Issue**: 22107 need update to match divine pride and need check all modified boots
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by Atemo** [comment]
Duplicate https://github.com/rathena/rathena/issues/4734
