### ISSUE TITLE
@summon, @slaveclone & Bio Cannibalize Map Crash

### ISSUE THREAD

**Issue by starragnarok2020** [rathena/rathena#5695]
* **rAthena Hash**: 

 a33887b

* **Client Date**: 20180620

* **Server Mode**:  pre renewal

* **Description of Issue**:  im not moddify anything and this ting happen to crash my map server when i do @summon or @salveclone commands and even Bio Cannibalize skills. 
![screenStarRO008](https://user-images.githubusercontent.com/73898279/104831539-9a415180-58bc-11eb-9cfc-86f7fdc38562.jpg)

  * Result: when using bio skills like marin sphree , bio cannibalize map server will crash
  *  [Error]: Server received crash signal! Attempting to save all online characters!
[Status]: Map-server #0 has disconnected.
[Status]: set users RO : 0
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by akiyamamio16** [comment]
Tested on https://github.com/rathena/rathena/commit/6ea30897b4b2c71363f1180f5e2ebb20f56b50b4
same pre-renewal and 20180620 client no modifications
result is working.
![image](https://user-images.githubusercontent.com/29175107/104842961-3130fc80-5903-11eb-8cf5-164d8e771f12.png)

**Comment by Lemongrass3110** [comment]
Unable to reproduce as well.
