### ISSUE TITLE
Biolab Enchants: Ancient Golden Ornament

### ISSUE THREAD

**Issue by raynra** [rathena/rathena#570]
http://irowiki.org/wiki/Biolab_Enchants
Ancient Golden Ornament (18570) is supposed to be enchantable, however, NPC Pudding (lhz_cube,233,24 Sorcerer#Bio4Reward) is only checking EQI_HEAD_LOW. Ancient Golden Ornament is a top headgear.

Bug?

**Comment by cydh** [comment]
oh u rite
