### ISSUE TITLE
Horror Toy Factory can't be generated

### ISSUE THREAD

**Issue by AsurielRO** [rathena/rathena#5706]
* **rAthena Hash**:  701bdd3

* **Client Date**:  20200304

* **Server Mode**:  Renewal

* **Description of Issue**: 
  * Result:  After updating my files from latest commit now i can't generate horror toy factory instance, it keep on saying "Wait, please wait until I am prepared. I can guide you when I am ready."
- [x] Check different based level and job level.
- [x] Check with different class.
- [x] Check cooldown and scripts (it seems like the script and ids are fine).

  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by Atemo** [comment]
I can't reproduce, the npc gives me the quest. The instance can be generated after.
```
		mes "[Catherine Jet Johnson]";
		mes "Wait, please wait until I am prepared. I can guide you when I am ready.";
		setquest 12330;// Skull-faced Girl
		close;
```

**Comment by AsurielRO** [comment]
Weird, i'm using latest rathena version but it seems like it doesn't generating on my end, maybe someone can confirm this too.
I test everything in-game to reproduce where does the problem came from.

**Comment by AsurielRO** [comment]
> I can't reproduce on this hash, the npc gives me the quest. The instance can be generated after.
> 
> ```
> 		mes "[Catherine Jet Johnson]";
> 		mes "Wait, please wait until I am prepared. I can guide you when I am ready.";
> 		setquest 12330;// Skull-faced Girl
> 		close;
> ```

Yes we have the same line, I also check the script.

**Comment by Lemongrass3110** [comment]
Any errors in your map server?
Also during loading?

**Comment by AsurielRO** [comment]
Confirming that my quest_db is reverted back to version 1 that's why the instance doesn't working.
