### ISSUE TITLE
Issue in IG_Enchant_Stone_Box

### ISSUE THREAD

**Issue by Melk3000** [rathena/rathena#5710]
* **rAthena Hash**: 

* **Client Date**: 
20200401

* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result:  Al usar  - Id: 23174
    AegisName: Enchant_Stone_Box11, deberia de obtener el item del grupo, pero no da nada porque están diferentes los nombres del grupo en item_db_usable que en item_misc, 
     Script: |
      getgroupitem(IG_Costume_Enchant_Stone_Box11);
      
      // Enchant_Stone_Box11
IG_Enchant_Stone_Box11,25067,2	// CastingStone_Robe
  
 
  * Expected Result:  Obtener una piedra: IG_Enchant_Stone_Box7,6964,85	// SPdrainStone_Robe
  * How to Reproduce:  Abre una el item #23299
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment]
English please.
