### ISSUE TITLE
Overweight drop error

### ISSUE THREAD

**Issue by eppc0330** [rathena/rathena#5727]
* **rAthena Hash**: master

* **Client Date**: 20200902

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: 
     
     
    ![image](https://user-images.githubusercontent.com/47050704/106379792-c2b76880-63f1-11eb-9452-61bfbe6d5de5.png)
    When using item box (ex. enchant stone box) and overweighted, item is dropped strangely. I can't pick up that dropped bug items.   

     Add: I used item 23058 : Enchant Stone Box 9.
     

  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by mazvi** [comment]
Please clean your inventory first before pick item

**Comment by eppc0330** [comment]
> Please clean your inventory first before pick item

I don't think that's the problem.... can you see the screenshot? It says the number of dropped item is '0'. It's definitely an error.
