### ISSUE TITLE
Script Command to get current channel options

### ISSUE THREAD

**Issue by Akkarinage** [rathena/rathena#5728]
**Is your request related to a missing feature?** No

**Describe the solution you'd like**
Ideally, i'd like to be able to use something like channel_getopt to fetch values that have previously been set by channel_setopt.

**Describe alternatives you've considered**
None

**Additional context**
Use case:
When AgitStart runs, public channels are turned off via script (`channel_setopt("#main",CHAN_OPT_CAN_CHAT,0);`),  then turned back on after AgitEnd is called. I'd like to be able to query the status of the channels at any time with something like `channel_getopt("#main",CHAN_OPT_CAN_CHAT);` and for it to return the value so I can consider whether or not to renable the channel manually in an NPC.

😄

**Comment by marky291** [comment]
This looks like a great addition 👍

**Comment by Mamb0w** [comment]
Sounds very useful! Would love to have a feature like that
