### ISSUE TITLE
Bug Riding skill (for Knight & Sader)

### ISSUE THREAD

**Issue by Skystar18** [rathena/rathena#5732]
* **rAthena Hash**:  58febee05

* **Client Date**:  2018-06-21

* **Server Mode**:  Pre-renewal

* **Description of Issue**:  Problem with Skill Riding for Knight or Crusader
  * Result:  Losing 7 skill points to learn Riding skill if player doesn't learn skill Endure before that.
  * Expected Result:  Force player to Learn Skill Endure first and won't allow them to learn Riding.
  * How to Reproduce:  Create a new character and change job to Knight or Crusader. Add some skill point for the character then start learning skill Riding.

Before learning Riding = still has 49 skill points
 
![image](https://user-images.githubusercontent.com/70919453/107160720-98b7f600-695d-11eb-904d-b5e74740d887.png)

After learning the skill, the skill point went down to 42
![image](https://user-images.githubusercontent.com/70919453/107160736-b1281080-695d-11eb-803a-6720cd78a2c0.png)

 
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by Balferian** [comment]
@Skystar18 Can you add screenshot with swordsman skill?

**Comment by Tydus1** [comment]
It's needed Endure Lv 1 to learn Riding and also Provoke Lv 5 to learn Endure. Doing the math, you have 7 skill points. ( 5 from provoke Lv 5, 1 from Endure Lv 1 and 1 from Riding Lv 1 ).

**Comment by secretdataz** [comment]
![image](https://user-images.githubusercontent.com/2021243/107219775-23732080-6a44-11eb-8243-ba4c4c89ad99.png)
the math checks out
