### ISSUE TITLE
How to make pet's name color like monster's?

### ISSUE THREAD

**Issue by eppc0330** [rathena/rathena#5736]
* **rAthena Hash**: master

* **Client Date**: 20200902

* **Server Mode**: Renewal

* **Description of Issue**:  In official KRO, pet's name color is related to player's level, like monster.
  * Result:  Pet name color is always pink.
  * Expected Result:  Color alters depends on player's level.
  * How to Reproduce: 
  * Official Information: 
    Pet's name color -> grey when player's level higher than pet's.
                                    pink when similar.
                                    red when player's level lower than pet's.
  

* **Modifications that may affect results**:

**Comment by admkakaroto** [comment]
Print or something like this? Official link info?

**Comment by eppc0330** [comment]
I have solved it by change clif.cpp

```static int clif_setlevel(struct block_list* bl) {
	int lv = status_get_lv(bl);
	if( battle_config.client_limit_unit_lv&bl->type )
		return clif_setlevel_sub(lv);
	switch( bl->type ) {
		case BL_NPC:
		case BL_PET:
			// npcs and pets do not have level
			return 0;
	}
	return lv;
}
```

I have erased ```case BL_PET:```
