### ISSUE TITLE
mobdb_searchname MobID Limit

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#5741]
* **rAthena Hash**:
 9389b7d

* **Client Date**:
 Irrelevant

* **Server Mode**:
 Renewal

* **Description of Issue**: 
  * Result:
   Both script commands `makepet 31553;` as well as `if (getpetinfo(PETINFO_ID) ==31553)` do fail if a monster ID with a high mobID range is being used as given in this example. Although monsters with IDs around 30k are supported otherwise, both these script commands will fail. The main culprit on the makepet command is the `mobdb_searchname`, which is limited in the mobID range.

Possible workarounds are currently:
Using the atcommand counterpart instead works just fine. For example:
`atcommand "@makeegg 64008";` 

And to get the petinfo, you can also use instead `if (getpetinfo(PETINFO_EGGID) == 64008)` as a workaround.

  * Expected Result:
   These script commands should at least support the full mobID range that is currently available to us.

  * How to Reproduce: 
   I'm not aware about the current limitations, so i've been testing with a custom monster db entry instead.
   Create a custom mobDB entry, for example:
   `31553,SOLACE_C,Solace,Lady Solace,123,24729,0,21000,25110,2,762,267,96,96,12,65,61,42,82,72,10,12,1,8,66,0x6203295,180,576,420,360,0,0,0,0,0,0,0,7441,200,2621,1,12040,50,718,1000,1910,50,1909,100,7442,50,0,0,0,0,4394,1
`
   Add an itemDB entry for the custom egg:
   `64008,Lady_Solace_Egg,Lady Solace Egg,7,20,,0,,,,,,,,,,,,,{},{},{}
`
   Add a respective custom pet_db.yml entry such as:
   `  - Mob: SOLACE_C
    EggItem: Lady_Solace_Egg
    FoodItem: Grape_Juice
    Fullness: 3
    IntimacyFed: 10
    CaptureRate: 500
    SpecialPerformance: false
    AllowAutoFeed: true
    Script: >
        bonus bSpeedAddRate,5;
`

  * Official Information: 
   Not aware about the official script commands behavior.

* **Modifications that may affect results**: 
  As given in the example above.

**Comment by Atemo** [comment]
I'm unable to reproduce now on https://github.com/rathena/rathena/commit/3f9b051ebce505c8aa6ab8745076ab578f95d59f

The command `makepet 31553;` give me `Lady_Solace_Egg` 64008
