### ISSUE TITLE
Preview in cash shop

### ISSUE THREAD

**Issue by RagnaWay** [rathena/rathena#5744]
This is a new function used on 2020~2021 clients so it is absolutely necessary to have it

![image](https://user-images.githubusercontent.com/53480357/111171802-04583900-8584-11eb-827c-56e44368017f.png)

https://gitlab.com/4144/Nemo/-/issues/174

https://github.com/HerculesWS/Hercules/commit/260eced9de7e704e5aff38dfdf612177f056087f

**Comment by Lemongrass3110** [comment]
This is not a official feature, but a custom diff provided by @4144
We can merge these changes once the diff is stable.

**Comment by RagnaWay** [comment]
> This is not a official feature, but a custom diff provided by @4144
> We can merge these changes once the diff is stable.

The diff is functional for 2021 clients, but you will need these functions on src as mentioned. http://nemo.herc.ws/patches/ExtendCashShopPreview/

**Comment by Lemongrass3110** [comment]
Thank you for reading my comment.
If it was not clear before: I know how to add it and know what steps are necessary to add support for it.

As you might have seen there have been reports of the diff breaking client functionality. So I do not see a reason to provide this yet and you report this on rAthena as "not working" then. Once it is stable enough it is a good enhancement that we can gladly add support for.

For now: Add it on your own risk by yourself.
