### ISSUE TITLE
DropEffect Error

### ISSUE THREAD

**Issue by JinYuichi** [rathena/rathena#5745]
* **rAthena Hash**: 

* **Client Date**: 2020-03-01

* **Server Mode**: RE/Pre

* **Description of Issue**: I am using current rathena. as of today, and I have a problem with white pillar and orange pillar, they all work fine for me. 

    WHITE_PILLAR = does not work
    GREEN_PILLAR = if it works
    BLUE_PILLAR = if it works
    YELLOW_PILLAR = if it works
    ORANGE_PILLAR = does not work
    PURPLE_PILLAR = if it works
    RED_PILLAR = if it works
![Screenshot_4](https://user-images.githubusercontent.com/74037616/108188735-8a907500-70d5-11eb-9501-dde8bec301f6.png)

  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by AsurielRO** [comment]
As far as I know you should only  use `DropEffect: CLIENT` because the color effect is based on your client date not on the database.

**Comment by JinYuichi** [comment]
Well, what I've been changing works correctly, the other effects only those two give me error, here I leave a screenshots of the effects that work correctly, only the white and orange ones give me error.
![FB_IMG_1613563304248](https://user-images.githubusercontent.com/74037616/108201891-fc70ba80-70e5-11eb-835d-83f1aa578c93.jpg)

**Comment by aleos89** [comment]
From March 2020 clients and newer: white pillar was removed and orange pillar was changed to green. The content was updated in #5563.
