### ISSUE TITLE
Arrow Vulcan casttime?

### ISSUE THREAD

**Issue by MrAntares** [rathena/rathena#575]
Hi!

I have found this:
http://forums.irowiki.org/showthread.php?t=79467

"Previously
Cast Time: (1.8 + (Skill Level*0.2)) seconds Cast Delay: 2.8 seconds 
which makes it 1.8 +10*0.2 = 3.8 seconds cast time. 

Now
Arrow Vulcan 
New: Variable cast time reduced to .44s + .06s per skill level.
which makes it .44+ 10*0.06 = .44+ 0.6 =1.04 seconds ? /omg "

Maybe we are using the old casttime for AV?

**Comment by aleos89** [comment]
AEGIS 2013 data:

SkillCastStatDelay
```
CG_ARROWVULCAN	1600	1760	1920	2080	2240	2400	2560	2720	2880	3040
```
SkillCastFixedDelay
```
CG_ARROWVULCAN	400	440	480	520	560	600	640	680	720	760
```

**Comment by MrAntares** [comment]
nvm then...
