### ISSUE TITLE
ASPD of Ancient Stone Shooter Card

### ISSUE THREAD

**Issue by Melk3000** [rathena/rathena#5750]
https://github.com/rathena/rathena/blob/1a1005435fde963124ba2704424f740b016c3392/db/re/item_db_etc.yml#L38370

Increases critical damage by 1% and increases attack speed (reduces delay after attack by 1%) for every 10 base Luk.

it should not be?

     bonus bAspdRate,@crit;

**Comment by idk-whoami** [comment]
![Capture](https://user-images.githubusercontent.com/60462533/109418436-f5f21500-79fa-11eb-924b-ab048a6cf0e9.PNG)

I think only bonus critical attack for every 10 base Luk.

**Comment by Atemo** [comment]
I think it should be critical damage and attack speed according to the english description
