### ISSUE TITLE
Meteor Storm Spam + Land Protector BUG

### ISSUE THREAD

**Issue by DevNoName** [rathena/rathena#5751]
* **rAthena Hash**: latest git / file 

* **Client Date**: 2015-11-04aRagexe and 2018-06-21aRagexeRE

* **Server Mode**: Pre-re

* **Description of Issue**: 
  * Result: check this video - https://drive.google.com/file/d/1s6VxpdbOVAe3u49ZVpadl2wjxH8NJvI4/view?usp=sharing
  * Expected Result: it must be same on storm gust nothing happen on land protector.
  * How to Reproduce: spam meteor storm outside of land protector or just check the video

* **Modifications that may affect results**: 
  i just download latest file on - https://github.com/rathena/rathena
  no modification on src or script as in fresh file except max lvl and max stats.

**Comment by vstumpf** [comment]
I don't understand the bug? A player can only have (by default) 50 skill units at a time, each meteor storm has 7 units, so once you cast 8 meteor storms, the LP goes away.

If you have two characters, one for LP and one for meteor storm, the LP does not go away.

**Comment by DevNoName** [comment]
> I don't understand the bug? A player can only have (by default) 50 skill units at a time, each meteor storm has 7 units, so once you cast 8 meteor storms, the LP goes away.
> 
> If you have two characters, one for LP and one for meteor storm, the LP does not go away.

**Comment by DevNoName** [comment]
*misclick. if this is default much better if there's an option to enable it or disable it because in high rate server, it's normal to spam skills like that.

**Comment by Daegaladh** [comment]
> *misclick. if this is default much better if there's an option to enable it or disable it because in high rate server, it's normal to spam skills like that.

Just change the value of MAX_SKILLUNITGROUP

**Comment by aleos89** [comment]
As the others have said, it's a limit which can be adjusted from `MAX_SKILLUNITGROUP`.
