### ISSUE TITLE
Skill Fatal Menace skill_nocast_db restrictions

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#5758]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/36c629e84141a54a27dbdab69bd2daaac554b043

* **Client Date**: 2020-05-20

* **Server Mode**: RE

* **Description of Issue**: 
  * Result: 
The Fatal Menace skill ID: 2284 has changed in rAthena over the days. But restrictions on use on maps have been maintained. I believe that there were restrictions due to the use of teleport in the skill. However, the skill now has no teleport effect. I don't know if this behavior is appropriate. But it does not seem to make any more sense to maintain this usage restriction.
```

```

  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
https://www.youtube.com/watch?v=1c_3y8o5K-4
