### ISSUE TITLE
Royal Guard Overbrand, Earth Dive, Exceed Break, Moonslasher has fix castimer

### ISSUE THREAD

**Issue by Paoly28** [rathena/rathena#576]
OB,ED,EB,MS should all have full variable casting time. even with 100% cast reduction or 530 of total value from ( dex*2+int ) i still cannot instacast any of the skill above.

http://irowiki.org/wiki/Overbrand : .5 seconds 
http://irowiki.org/wiki/Exceed_Break : 4.5 + (0.5 * SkillLvl) seconds
http://irowiki.org/wiki/Earth_Drive : 1 second
http://irowiki.org/wiki/Earth_Drive : 1 second

**Comment by MrAntares** [comment]
Well... I'm not sure. I noticed that there is some kind of logic behind how the casttime is defined:
- Casttime:X = Has X casttime of which 20% is fixed and 80% is variable
- Variable Casttime:X, Fixed casttime:Y = Has some variable and some fixed casttime
- Variable Casttime:X = Has only variable casttime
- Fixed cast:X = Has only fixed casttime

**Comment by cydh** [comment]
some Royal Guard skills shouldn't have fixed cast time.
