### ISSUE TITLE
Error /debug message for warp.

### ISSUE THREAD

**Issue by limitro** [rathena/rathena#5764]
* **rAthena Hash**:  26632604f4d35dd523a5dd411b4339b01434fb38
* **Server Mode**:  Renewal

* **Description of Issue**: 
If a map has mapflag NoTeleport

and you uses an item that triggers:
warp "Random",0,0;

this error will appear:

![image](https://user-images.githubusercontent.com/9300961/109476937-ba496080-7a77-11eb-98c5-c257bb101f08.png)

Example scripts that has this:
![image](https://user-images.githubusercontent.com/9300961/109477149-fc72a200-7a77-11eb-95c7-9c3359b9b61c.png)

**Comment by Lemongrass3110** [comment]
You talk about items, but you show official NPCs.

What would be the expected behavior?
For me this sounds like you forgot to add a usage restriction for certain items on your map.

Follow the issue template in the future or we are going to close reports without looking at it.

**Comment by limitro** [comment]
Let's say,

npc/other/CashShop_Functions.txt

// Giant Fly Wing
//============================================================ 
// - Warp party leader to random spot on the map.
// - Summon Party members on party leader map to a 3x3 location around the leader.
// - No arguments.
function	script	F_CashPartyCall	{
	warp "Random",0,0;
	if (is_party_leader() == true)
		warpparty "Leader", 0, 0, getcharid(1), strcharinfo(3), 3, 3;
	return;
}

Attached to item ID:
  - Id: 12212
    AegisName: Giant_Fly_Wing
    Name: Giant Fly Wing
    Type: Usable
    Buy: 2
    Weight: 10
    Trade:
      Override: 100
      NoDrop: true
      NoTrade: true
      NoSell: true
      NoCart: true
      NoGuildStorage: true
      NoMail: true
      NoAuction: true
    Script: |
      callfunc "F_CashPartyCall";


And by rAthena default, you can click it on example a PvP map, and that error will pop up.

This doesn't really break anything, it's just that Error message on the server side.

**Comment by Atemo** [comment]
Confirmed with
item 23016 https://github.com/rathena/rathena/blob/master/npc/re/merchants/nightmare_biolab.txt#L107
or npc
```
paramk,97,17,0	script	test	56,{// paramk have mapflag noteleport
	warp "Random",0,0;
	end;
}
```
because of
https://github.com/rathena/rathena/blob/master/src/map/pc.cpp#L6258
https://github.com/rathena/rathena/blob/master/src/map/script.cpp#L5586
