### ISSUE TITLE
KN_BOWLINGBASH/CR_GRANDCROSS/KN_BRANDISHSPEAR status timings are incorrect

### ISSUE THREAD

**Issue by mrjnumber1** [rathena/rathena#5768]
* **rAthena Hash**: latest
* **Client Date**: x
* **Server Mode**: both 
* **Description of Issue**: 
  * Result: The times (and availability) from all of these skills are wrong
  * Expected Result: 
     - KN_BOWLINGBASH -> does not set EFST_NOEQUIPWEAPON on pre-re or renewal, **_Remove causing SC_STRIPWEAPON for KN_BOWLINGBASH**_
     - KN_BRANDISHSPEAR must cause EFST_NOEQUIPWEAPON for 1000ms val1=1. _**Add Duration1 entry to KN_BRANDISHSPEAR entry in pre-RE and RE skill db!**_
     - CR_GRANDCROSS (player only) EFST_NOEQUIPSHIELD for 950ms val1=1 and also EFST_ANKLESNARE for 1000ms (we use AfterCastWalkDelay). _**CR_GRANDCROSS Duration1 should be fixed to 950 and AfterCastWalkDelay set to 1000**_
     - Mob casted CR_GRANDCROSS and NPC_GRANDDARKNESS self-inflicts EFST_NOACTION for 1000ms only.  _**Ensure the SC_STRIPSHIELD is only applied to players**_

  * How to Reproduce: cast and watch the skills
  * Official Information: 
    - Using Brandish Spear and Bowling Bash https://streamable.com/rcx9c2 showing the strip weapon effect on brandish but not bowling
    - Using Grand Cross https://streamable.com/dkj5g1 showing the strip effect (yeah, good luck comparing the 50ms timing. but I recorded it anyways)

* **Modifications that may affect results**: x

**Comment by vstumpf** [comment]
> KN_BRANDISHSPEAR must cause EFST_NOEQUIPWEAPON for 1000ms val1=1. there is no Duration1 entry for the skill on our skill DB!
Is this for both prere and renwal?

> Mob casted CR_GRANDCROSS and NPC_GRANDDARKNESS must cause EFST_NOACTION for 1000ms, no gear change or stripping possible (not that any people were doing so lol)
Does this mean if a player is hit with these mob-casted skills, they can't change gear?

**Comment by mrjnumber1** [comment]
> > KN_BRANDISHSPEAR must cause EFST_NOEQUIPWEAPON for 1000ms val1=1. there is no Duration1 entry for the skill on our skill DB!
> 
> Is this for both prere and renwal?
>
yes 
> > Mob casted CR_GRANDCROSS and NPC_GRANDDARKNESS must cause EFST_NOACTION for 1000ms, no gear change or stripping possible (not that any people were doing so lol)
> 
> Does this mean if a player is hit with these mob-casted skills, they can't change gear?
sorry. i meant the mob itself gets EFST_NOACTION. players can attempt to strip shield from them and succeed in that time. but this is not true for a crusader player casting it.

i will reword the post for clarification :)
