### ISSUE TITLE
Failed to compile using MSVC2013 .. 

### ISSUE THREAD

**Issue by emistry** [rathena/rathena#577]
Doesn't seem like able to compile using MSVC2013.

Clean rAthena which I checkout 10 minutes ago.
![Image of latest rAthena compile with MSVC2013](http://i.imgur.com/BrB62jm.png)

Could it be caused by lack of MSVC2012 libraries? since I didnt install MSVC2012.

not sure if it would work with MSVC2015, it doesn't work in my current MSVC2013 ... I dont think it could work for MSVC2015 too.

**Comment by emistry** [comment]
This would shown in case I didnt upgrade the solution files to compile.

![img](http://i.imgur.com/aUOJL0O.png)

Do I really need to install the libraries of 2012 ?? seem like redundant and unnecessary.

**Comment by aleos89** [comment]
I just installed MSVC2013 the other day on a new computer and it works just fine.

Are you using MSVC2015? If you are then the 2013 project won't work with it. We have to rebuild a new one for 2015.

**Comment by emistry** [comment]
nope i am currently using MSVC 2013 ... I realize that MSVC 2015 doesnt work to compile either rAthena/Hercules so it's not installed in my laptop.

**Comment by ijped27** [comment]
u should install 2012 or 2013 if your are using 2015

**Comment by aleos89** [comment]
I just looked back at your picture, you're using rAthena-12 but you have MSVC2013 installed. You're using the wrong project/solution file.
