### ISSUE TITLE
Unknown Packet session #10

### ISSUE THREAD

**Issue by AsurielRO** [rathena/rathena#5770]
* **rAthena Hash**:  a02ffee

* **Client Date**:  20200304

* **Server Mode**:  Renewal

* **Description of Issue**: 
  * Result:  First of all apologize if i post this here but i have a strong feeling that this is related to mob_db.txt to mob_db.yml format update, After i update my emulator into this new commit my server got a unknown packet warning, I double check all of source code and i believed all are fine and the compilation works perfectly.

After using `athena-start start` the server reads nicely, but when i try to login and try to move ingame or type on the chat box the console said unknown packet warning and suddenly i got disconnected.

Anyway i have gepard too.

Packet also disabled both on client and server side.

```#if PACKETVER >= 20110817
    /// Comment to disable the official packet obfuscation support.
    /// This requires PACKETVER 2011-08-17 or newer.
    #ifndef PACKET_OBFUSCATION
        //#define PACKET_OBFUSCATION

        // Define these inside src/custom/defines_pre.hpp or src/custom/defines_post.hpp
        #define PACKET_OBFUSCATION_KEY1 0x7726674A
        #define PACKET_OBFUSCATION_KEY2 0x4F0DD979
        #define PACKET_OBFUSCATION_KEY3 0x1771D059
```
![image](https://user-images.githubusercontent.com/29746866/109909019-570e3700-7ce0-11eb-9525-54d2c5a24711.png)

https://imgur.com/WAlv0fp

![image](https://user-images.githubusercontent.com/29746866/109909069-6db48e00-7ce0-11eb-99e3-8e876e284781.png)

* **Modifications that may affect results**:

**Comment by llchrisll** [comment]
What did you compile your server to? Default is 2020-04-01, I even compiled mine to 2021-01-07 (to check that client) and I have no issues even with 2020-03-04.

**Comment by reunite-ro** [comment]
seems like clientdate in packets.h are not same with client date of client that you're using ?

**Comment by Lemongrass3110** [comment]
This shows that your client is using packet encryption (gepard does not do this usually).
Are you sure that you or your player is really using YOUR client and that gepard is on?

**Comment by AsurielRO** [comment]
we are using gepard shield but the packet obfuscation and packets encryption are disabled

**Comment by AsurielRO** [comment]
> What did you compile your server to? Default is 2020-04-01, I even compiled mine to 2021-01-07 (to check that client) and I have no issues even with 2020-03-04.

I compiled it using 20200304 version

**Comment by AsurielRO** [comment]
> This shows that your client is using packet encryption (gepard does not do this usually).
> Are you sure that you or your player is really using YOUR client and that gepard is on?

Yes i'm pretty sure that gepard is on and the client is correct, this works perfectly before i merge to mob_db yml format.

**Comment by Lemongrass3110** [comment]
This is not related to mob db at all.
No packet related changes in there.
