### ISSUE TITLE
Costume item Bonus effect can i have the patch to have the costume item bonus will work

### ISSUE THREAD

**Issue by ijped27** [rathena/rathena#5772]
**Is your request related to a missing feature?**

Costume item Bonus effect can i have the patch to have the costume item bonus will work

can i have an solution to work the item script in costume item

some of the server or players want costume item have an item bonuses if it's possible to have an toggle to on off the costume item bonuses to be work

**Comment by Atemo** [comment]
Please uses the forum for custom requests or if it's an issue on the emulator, put more effort to describe it.
