### ISSUE TITLE
Bug Report Intance.ccp

### ISSUE THREAD

**Issue by ijped27** [rathena/rathena#5773]
* **rAthena Hash**: a02ffee Latest
* **Client Date**:  2018-05-30
* **Server Mode**: Renewal Pre-Renewal
* **Description of Issue**: When compiling in Windows having warning message about the instance patch 
  * Expected Result: No Error's or Warnings 
  *ScreenShots: https://prnt.sc/10f2d2a
                         https://prnt.sc/10gt9v8
                         https://prnt.sc/10int1e
* **Modifications that may affect results**: Nothing Clean Compiling

**Comment by Lemongrass3110** [comment]
It would have helped if you did not cut off the line numbers. ;-)

**Comment by ijped27** [comment]
> It would have helped if you did not cut off the line numbers. ;-)

Here's the updated screen shot 03-09-2021 Clean  Git
https://prnt.sc/10gt9v8

**Comment by ijped27** [comment]
bump for this

**Comment by Lemongrass3110** [comment]
These are only warnings. This has no priority.
