### ISSUE TITLE
Cross Impact not work on WOE

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#5775]
* **rAthena Hash**: a02ffee

* **Client Date**: 20200401

* **Server Mode**: RE

* **OS**: centos-release-7-9.2009.1.el7.centos.x86_64

* **Compiler**: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)

* **Description of Issue**: Cross Impact not work on WOE maybe related: https://github.com/rathena/rathena/commit/0e9308cba6e688f45907cabf1f0034c0b4b7d6b4
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by Badarosk0** [comment]
I can confirm this issue.
![screenrAthena005](https://user-images.githubusercontent.com/13624462/113385118-dafa2400-935d-11eb-9fe2-c40c416214f7.jpg)

**Comment by mazvi** [comment]
Additional info if this related compiler:

* **OS**: centos-release-7-9.2009.1.el7.centos.x86_64

* **Compiler**: gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)

**Comment by Balferian** [comment]
There are problem in skill_check_unit_movepos, it return false on gvg/pvp maps.
Need to change this check.
