### ISSUE TITLE
Compiling rathena issue

### ISSUE THREAD

**Issue by jhayecool** [rathena/rathena#5776]
OS = Centos 7
Devsettools = 9

Error:

        CXX     int_quest.cpp
        CXX     int_storage.cpp
        LD      char-server
make[1]: Leaving directory '/home/centos/rathena/src/char'
make[1]: Entering directory '/home/centos/rathena/src/map'
        MKDIR   obj
        CXX     achievement.cpp
g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[1]: *** [Makefile:84: obj/achievement.o] Error 1
make[1]: Leaving directory '/home/centos/rathena/src/map'
make: *** [Makefile:50: map] Error 2

**Comment by vstumpf** [comment]
This is not an rathena problem, it's a g++ problem. You can Google the error code, I found this: https://stackoverflow.com/questions/30887143/make-j-8-g-internal-compiler-error-killed-program-cc1plus
Might be a memory problem?

**Comment by jhayecool** [comment]
Thank you!
