### ISSUE TITLE
RODEX cannot read mail

### ISSUE THREAD

**Issue by kawisin** [rathena/rathena#5778]
Client Date: 2020-20-12 RE

Server Mode: Renewal

Description of Issue:
![100409494-f2bb5600-30a6-11eb-9322-7497f6fa91d1](https://user-images.githubusercontent.com/70370489/110728932-6cd7ab00-8250-11eb-865a-caeb30e3fee1.jpg)

RODEX cannot read mail，

**Comment by Lemongrass3110** [comment]
Follow the issue template.
Which hash do you use?
This should have been fixed already (enchantgrade support was already added).

**Comment by admkakaroto** [comment]
I'm using 2020 client and are working fine, can't reproduce this

**Comment by RagnaWay** [comment]
It's working perfectly with me, I tested it with client 2021-01-07
![image](https://user-images.githubusercontent.com/53480357/111029937-4cd5f200-83de-11eb-8de9-207c98a73d13.png)

**Comment by Lemongrass3110** [comment]
Probably related to #5445 and therefore has been fixed already in d01b718.

Please update your emulator.
