### ISSUE TITLE
Kagerou - Shadow Trampling Skill

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#5786]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/95237bc134c5a5538de8338d25128c859adb8971

* **Client Date**: 2020-06-20

* **Server Mode**: RE

* **Description of Issue**: 
* This skill must immobilize the target and prohibit the use of the skill and currently neither happens.
  * Result: 
  * 

그림자 밟기
MAX Lv : 5
습득조건 : 환술 - 잔상 1
내용 : 특정 은신 스킬을 사용하고 있는 대상의 움직임을 일시적으로 멈추게 하며, 해당 스킬을 강제로 해제시킨다. 몬스터에게는 적용되지 않는다.
[LV 1] 효과 범위 5 x 5 셀
[LV 2] 효과 범위 7 x 7 셀
[LV 3] 효과 범위 9 x 9 셀
[LV 4] 효과 범위 11 x 11 셀
[LV 5] 효과 범위 13 x 13 셀
  * Expected Result: 
  
  https://divine-pride.net/database/skill/3023
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
The skills that are blocked are those from the `IgnoreKagehumi` flag in the skill_db and are managed by the `SC_KAGEHUMI` status.
