### ISSUE TITLE
Can't use skills after I cast the first one.

### ISSUE THREAD

**Issue by phaeloliveira** [rathena/rathena#5787]
* **rAthena Hash**:  I'm sorry I don't know how to check that because my other friend uploaded another emulator and other sql tables 

* **Client Date**: 5.0

* **Server Mode**: 

 Pre-Renewal 

* **Description of Issue**: after I cast the first skill on any char or any job it won't cast anything ever again until I log off and back in
  * Result: I cast a skill, and it works fine, after that all the other skills in my char don't work.
  * Expected Result: that all skills work just fine. 
  * How to Reproduce: I don't know how, it started after I went to bed with everything working just fine.

   @aleos89 @Lemongrass3110

* **Modifications that may affect results**: 
  
   I modified SRC and    skill_db. -->

**Comment by aleos89** [comment]
This sounds more like a support question. Please use the forums for any support related concerns. Thanks!
