### ISSUE TITLE
SC_MANA_PLUS

### ISSUE THREAD

**Issue by Felleonel** [rathena/rathena#5788]
* **rAthena Hash**:  Last

* **Client Date**: 20200401

* **Server Mode**: RE

* **Description of Issue**:  The SC_MANA_PLUS bonus isn't increasing the MATK when using items.
  * How to Reproduce: Just try to use item 12419 and look at ALT+A
  * https://divine-pride.net/database/item/12419/pocao-do-furor-magico

**Comment by aleos89** [comment]
Can you confirm it's not increasing the actual damage first? There is a known MATK display issue but everything should still be working in terms of the actual damage.

**Comment by Felleonel** [comment]
Real, the damage has increased, it just doesn't display.

**Comment by aleos89** [comment]
I'll close this out then. The visual part will be resolved in a future fix.
