### ISSUE TITLE
RE:Acid Demonstration physical portion is ignoring Defense

### ISSUE THREAD

**Issue by Paoly28** [rathena/rathena#579]
Acid Demonstration physical portion should get affected by Defense due to it becoming partially physical at renewal.

**Comment by MrAntares** [comment]
Confirmed here as well!

**Comment by Paoly28** [comment]
i dunno but AD's magic portion is also affected by racial that should also only affect weapon atk making it outrageously overpowered , yes like getting 1 shot at 100 vit using WoE Set and standard cranial beret/poo.

**Comment by aleos89** [comment]
Related to the list created in #803.
