### ISSUE TITLE
warlock'skill reading spellbook is passive

### ISSUE THREAD

**Issue by normally-00** [rathena/rathena#5790]
Hello when I will use this skill for seal skill to use with release I can't use this skill
This skill type is passive not active (mean I can't cast this skill)

**Comment by normally-00** [comment]
evidence pic of this skill I don't know 
Is this bug? 
https://ibb.co/VLC1JyD

**Comment by Balferian** [comment]
this is not a bug.
skill changed, now it is passive and you need to read a books from inventory.
