### ISSUE TITLE
New formula - Cart Cannon

### ISSUE THREAD

**Issue by Felleonel** [rathena/rathena#5795]
* **rAthena Hash**: Lastest

* **Client Date**: 20200401

* **Server Mode**: RE

* **Description of Issue**: According to Sigma in Divine Pride the current Cart Cannon formula is:
((250 x skill level) + ((20 x skill level) x (Cart Remodeling skill level))) + (2*Int/(6 - Cart Remodeling skill level))
https://www.divine-pride.net/forum/index.php?/topic/3723-kro-jobs-improvement-project/page/10/
       Are the current formula from rAthena according to the new formula?

**Comment by aleos89** [comment]
Part of #5517.
