### ISSUE TITLE
Sorcerer's skill Vacuum Extreme (SO_VACUUM_EXTREME) is not working! 

### ISSUE THREAD

**Issue by Rayvakarian** [rathena/rathena#5798]
* **rAthena Hash**: c8567f3

* **Client Date**: 2018-06-20

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Vacuum Extreme doesn't stop enemies.
  * Expected Result: This skill should stop enemies.
  * How to Reproduce:

**Comment by admkakaroto** [comment]
It works for me, I can't reproduce it, I advise you to fill in the report template correctly, put the test done, video demonstrating how you tested it, how to reproduce the problem.

**Comment by Balferian** [comment]
> It works for me, I can't reproduce it, I advise you to fill in the report template correctly, put the test done, video demonstrating how you tested it, how to reproduce the problem.

(I test it on last clean rA)
Try to summon @monster 1100 and cast Vacuum to him when he chasing to you.
It`s work perfect if mob not chasing.
I tested the skill at kRo and it also should works when monster chasing you.
![image](https://user-images.githubusercontent.com/16213511/112512609-97734900-8da4-11eb-9fee-e2eddf7f50d3.png)

@admkakaroto can you confirm it?

**Comment by aleos89** [comment]
Thanks for the kRO test, if you could try it against a player too, I would appreciate it!

The case at point is here in our code:
```cpp
if (unit_bl2ud(bl)->walktimer == INVALID_TIMER) // Apply effect and suck non-walking targets one-by-one each n seconds
```
Years ago only players who were "in the area and standing still" were sucked in while those who were continuously walking could avoid it. Maybe things changed or we were wrong all along from translations!

**Comment by Balferian** [comment]
@aleos89 it's working for mobs and don't work for players

https://user-images.githubusercontent.com/16213511/112632328-099d6980-8e49-11eb-81bf-11a5a13f6459.mp4

**Comment by Balferian** [comment]
Rebellion with 1 str
https://user-images.githubusercontent.com/16213511/112637599-613ed380-8e4f-11eb-88fe-7fcf1943e0d4.mp4
