### ISSUE TITLE
Can't up stat after 400

### ISSUE THREAD

**Issue by hnomkeng** [rathena/rathena#5799]
* **rAthena Hash**: c8567f3
* **Client Date**: 2019-04-18a
* **Server Mode**: Renewal
* **Description of Issue**:  I can't up stat after 400
* **Modifications that may affect results**: 
max_parameter: 800
max_trans_parameter: 800
max_third_parameter: 800
max_third_trans_parameter: 800
max_baby_parameter: 800
max_baby_third_parameter: 800
max_extended_parameter: 800
max_summoner_parameter: 800

**Comment by aleos89** [comment]
![image](https://user-images.githubusercontent.com/3521753/113579825-d5693c00-95f2-11eb-9c8a-07741ec1d221.png)

Works just fine for me in a clean clone. Did you set a cap in db/(pre)re/job_param_db.txt?

**Comment by hnomkeng** [comment]
> ![image](https://user-images.githubusercontent.com/3521753/113579825-d5693c00-95f2-11eb-9c8a-07741ec1d221.png)
> 
> Works just fine for me in a clean clone. Did you set a cap in db/(pre)re/job_param_db.txt?

Thank you, I will test again.
