### ISSUE TITLE
Issue with reloadmobdb and reloaditemdb

### ISSUE THREAD

**Issue by Loki784** [rathena/rathena#5800]
* **rAthena Hash**: c8567f31e

* **Client Date**: 2020-04-01

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Everytime when i use `@reloadmobdb` or `@reloaditemdb`, the game freezes and all accounts are disconnected a while later, the emulator takes about 5 minutes to load all .yaml information and i am able to log in again
  * How to Reproduce: Compiling and running using Windows 10, then typing the command ingame

**Comment by Daegaladh** [comment]
Cannot reproduce it, pretty sure you're probably compiling in debug mode, please compile in release mode.
