### ISSUE TITLE
Cart Items Bug when in using @disguise command?

### ISSUE THREAD

**Issue by RadianFord** [rathena/rathena#5802]
* **rAthena Hash**: c5cf2f6e42b1cb88d501e0b3e7c56e870b928209

* **Client Date**: 2018 06 20 RagexeRE

* **Server Mode**: Pre-renewal

* **Description of Issue**: When disguise the cart item amount is being doubled.
  * Result: Its not working as intended, I assume.
  * Expected Result: Must not run like this people might take advantage of this.
  * How to Reproduce:
  * 1 -> Change to whitesmith class
  * 2 -> Grab your platinum skills and then get a cart.
  * 3 -> Place some armors, shoes or garments inside the cart.
  * 4 -> Use command `@disguise kraben` then `@size 1` now check your card alt + w
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
I was unable to reproduce this on a clean clone. Are you sure you don't have any modifications that may affect this?

**Comment by RadianFord** [comment]
@aleos89 i forgot on the last part use @ refresh command

**Comment by Tydus1** [comment]
I also was unable to reproduce this issue on a clean rAthena clone, even using @refresh at the end.

**Comment by RadianFord** [comment]
Nothing serious about this, it might be a cause of client or might be a source mod.
