### ISSUE TITLE
Deletepset Cannot be used now

### ISSUE THREAD

**Issue by reunite-ro** [rathena/rathena#581]
https://github.com/rathena/rathena/blob/master/npc/custom/events/disguise.txt

this npc using deletepset but error in latest revision

this is deletepset from wiki 

https://rathena.org/wiki/Deletepset

**Comment by aleos89** [comment]
Just making sure, but did you make sure to enable PCRE when configuring your build?

**Comment by reunite-ro** [comment]
ahh.. because of enable pcre ? okay ill try :)
