### ISSUE TITLE
MVP DamageTaken improvement

### ISSUE THREAD

**Issue by hederod** [rathena/rathena#5814]
could be added to the conf file, a trigger to disable or edit this 10% damage value received by mvps, for people who don't want to use this function or even for some type of event (I know it's an official update, but bad in the eyes of many players).
as all mvps have the line Class: Boss, the trigger could be created through it but I don't have enough knowledge to do it.
I apologize if this type of configuration already exists but I haven't found it.

**Comment by hederod** [comment]
https://github.com/rathena/rathena/pull/5749

**Comment by aleos89** [comment]
Just use the import/mob_db.yml. All you have to do is override the flag with 0.
IE:
```yaml
  - Id: 1038
    DamageTaken: 0
```

**Comment by hederod** [comment]
I know how to do that, I just suggested something more practical that doesn't need to be redone every time the file is updated, your solution is a workaround

**Comment by humanwizzard** [comment]
src\map\battle.cpp
`-			damage = i64max(damage * md->db->damagetaken / 100, 1);`
`+			damage = i64max(damage * 100 / 100, 1);`
100 = full damage

**Comment by aleos89** [comment]
It doesn't need to be redone when the file is updated. The import file is what you make of it for your server.

This is one of the reasons for the import system, it's not just a work around.

**Comment by aleos89** [comment]
> @humanwizzard humanwizzard i fond this code
> 
> if (bl->type == BL_MOB) { // Reduces damage received for Green Aura MVP
> mob_data *md = BL_CAST(BL_MOB, bl);
> 
> ```
> 	if (md && md->db->damagetaken != 100)
> 		damage = i64max(damage * md->db->damagetaken / 100, 1);
> ```
> 
> however I am not sure what value I should change to cancel the damage penalty on mvps

You can just comment this whole statement out if you want to disable this.

While I do understand having a config makes it easy to toggle, it also defeats the purpose of the database settings. This is also the reason we got rid of the item gender config, because it just didn’t work well when changing values in the database.
