### ISSUE TITLE
Script Overflow Limit

### ISSUE THREAD

**Issue by nanakiwurtz** [rathena/rathena#582]
Current rAthena scripting engine caps the calculation at INT_MAX, usually this is not an issue on normal circumstances because the limit is high enough.
But if it's involving time calculation (especially if using the tick timer), the limit is not high enough...

Thanks~

**Comment by lighta** [comment]
I don't see the direct cause but idk if increasing to long would be a good fix.
I wonder if we couldn't just say in wich unit we want to work like for instance. 5s, 5m etc..

**Comment by Lemongrass3110** [comment]
Fixed in f97adc5
