### ISSUE TITLE
Land Protector BUG or Request

### ISSUE THREAD

**Issue by NyxLucid** [rathena/rathena#5830]
* **rAthena Hash**: f10de84ea

* **Client Date**: 2015

* **Server Mode**: Pre-Re

* **Description of Issue**: After casting Storm Gust while Land Protector is placed on the ground and another Land protector is cast (burning the first Land protector) or Even using skill Ganbantien . How to make the Storm Gust will do damage
  * Result: Storm Gust it’s not doing any damage. 
  * Expected Result: the Storm gust should do damage after the second Land Protector is placed, or remove the Land Protector using Ganbantien
  * How to Reproduce: Please check the video https://bit.ly/3fAP8XU 
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by secretdataz** [comment]
intended behavior.
