### ISSUE TITLE
TK_POWER shouldn't count actual player

### ISSUE THREAD

**Issue by Indigo000** [rathena/rathena#5836]
* **rAthena Hash**: fc8e63a2af306de18b9bd0c749429a39f49a7ea9

* **Client Date**: 2018-06-21

* **Server Mode**: Both

* **Description of Issue**: TK_POWER currently includes the current player in the count while it shouldn't. There has been a check that was intended to prevent this (e7219585edc70153f8d029a67fc53ec42cb15a43) but all this does is prevent a solo party from being included. If there's more than one player in a party, then all of them get included.
  * Result:  In a party of more than 1, all members are included in TK_POWER/Kihop. It should include the Kihop user.
  * Expected Result:  A party of 2 members should give only a 10% ATK boost instead of the current 20%.
  * How to Reproduce:  Get a party of more than 1 and check the damage.
  * Official Information:  Not a great source https://irowiki.org/classic/Kihop but also commit e7219585edc70153f8d029a67fc53ec42cb15a43 which seems to indicate that the user should not be included.
  

* **Modifications that may affect results**:

**Comment by Tydus1** [comment]
Just reminding to close this issue since a fix commit is already pushed into master branch.

**Comment by Daegaladh** [comment]
Fixed in #5838
