### ISSUE TITLE
Skills getting canceled upon gear switch

### ISSUE THREAD

**Issue by Indigo000** [rathena/rathena#5837]
* **rAthena Hash**: fc8e63a2af306de18b9bd0c749429a39f49a7ea9

* **Client Date**: 2018-06-21

* **Server Mode**: Pre-Renewal (and Renewal?)

* **Description of Issue**: On d3d8f3c5a7459ef1f76ae379e9d6013dc489bc1a some code was overhauled to ensure ammo gets unequipped when you switch weapon types. This also, likely unintentionally, affected other skills such as Auto Guard from being ended when switching to a different shield.
  * Result:  Skill bonuses being canceled upon gear switch, even to the same gear type.
  * Expected Result:  Skill bonuses stay when you switch to a gear of the same type.
  * How to Reproduce:  Seems to be caused by the commit mentioned above. In **pc_equipitem** it calls **pc_unequipitem** with flags 2 and 4. At the end of pc_equipitem it properly calls for **pc_checkallowskill** to ensure the proper skills should be removed. pc_checkallowskill is **also** called in **pc_unequipitem_sub**. However, previously before the _sub was added, **pc_unequipitem** had a check for **flag&1** to make sure pc_checkallowskill does not unintentionally get called. With the redesign, that flag check was removed. When adding back the flag&1 check within pc_unequipitem_sub, it properly works. When switching from Shield to Shield, skills like Auto Guard stay, but when unequipping the Shield or changing to a Bow, it gets properly removed.
  * Official Information:  None at this time. However this was introduced in a commit that had nothing to do with these skills and was focused on ammo only. So it's likely a bug introduced there.
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
This was actually cleaned up in #4525 and #4806.

**Comment by Indigo000** [comment]
> 
> 
> This was actually cleaned up in #4525 and #4806.

Urgh, must have been a mistaken in merging rA updates. Sorry for wasting your time.
