### ISSUE TITLE
Genetic Sling Item : Banana force sit rate and missing luk reduction

### ISSUE THREAD

**Issue by Paoly28** [rathena/rathena#584]
Genetic Sling item :Banana bomb force sit chance should be reduceable by agi/vit and reduce luk by 20 seconds for the duration. Force sit should act like status effect so it should still inflict sit regardless if Sling item misses, 2nd hit should also cancel Banana bomb's force sit status instead of reapplying it.

**Comment by aleos89** [comment]
I see that it's reducing LUK by 20% instead of a static 20.

Can you please provide a source of where you got your information from about the sitting part? Thanks.

**Comment by Paoly28** [comment]
https://www.youtube.com/watch?v=oVWivL-3Lsc

genetic guy is spamming sling and although he hits SC doesnt sit at 100% chance, gene player said resistance is based on str i think this is agi and vit though i dont know the exact value, force sit chance is also low according to a genetic group from pRO

https://www.facebook.com/rophgenetics/posts/392981497478523

there's also a good info on ro.wikia 
http://ragnarok.wikia.com/wiki/Sling_Item

**Comment by aleos89** [comment]
I found some other issues with this and will fix them. Thanks.
