### ISSUE TITLE
Clan Window cannot Open

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#5840]
* **rAthena Hash**: c14be67

* **Client Date**: 20200401

* **Server Mode**: RENEWAL

* **Description of Issue**: 
  * Result:  Clan window cannot open using Alt+G
  * Expected Result:  Clan window can open using Alt+G after join clan. check on clan window on this link https://irowiki.org/wiki/Clan_System
  * How to Reproduce:  Join clan then press Alt_G
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Are you able to test with another 2020 client? rAthena doesn’t manage these types of commands as they are specifically client related.

**Comment by mazvi** [comment]
Alt + G is guild window.. but if join clan it must be open clan window..

**Comment by ecdarreola** [comment]
ctrl + g is for the clan window if i'm not mistaken.

**Comment by yumiharuka21** [comment]
Your link says..
![image](https://user-images.githubusercontent.com/80681226/113979535-f42c3480-9877-11eb-97b7-16edd3e456e7.png)

**Comment by mazvi** [comment]
aaah nice :D 

this is my fault, sorry, this issue closed :)
