### ISSUE TITLE
Configure Using GDB resulting to Error

### ISSUE THREAD

**Issue by ecdarreola** [rathena/rathena#5844]
* **rAthena Hash**: d33ea18

* **Client Date**: Any Client (e.g. 20200304)

* **Server Mode**:  Renewal

* **Description of Issue**: Unable to compile using GDB
  * Result: csv2yaml Error as shown below (Screenshot)
  * Expected Result: Should compile normally
  * How to Reproduce: Get **latest rAthena**, compile server using `./configure --enable-debug=gdb --enable-packetver=20200304` 
  * Official Information: N/A
  

* **Modifications that may affect results**: N/A
  
  

Screenshot
![image](https://user-images.githubusercontent.com/48939874/114129009-46c92780-9930-11eb-800c-48f59a9626de.png)

P.S. When compiling latest rA without using GDB it works fine.

**Comment by biali** [comment]
Dont mean to be rude or anything but do you guys think you could give a look into this matter? thank you very much in advance!
