### ISSUE TITLE
Conflicting quest id usage in Lighthalzen "Cube Room Quest" and "Rekenber Job Quest"

### ISSUE THREAD

**Issue by KrokusPokus** [rathena/rathena#5848]
Concerning "npc\quests\quests_lighthalzen.txt"

There are 2 independent quests in this script that both make use of the same quest info ID 12014:
- The Cube Room Quest
- The Rekenber Job Quest (aka Shadow Quest)

The present english translation in OngoingQuestInfoList and questid2display contains information relevant to the Rekenber Job Quest:

```
	[12014] = {
		Title = "More missions",
		Description = { "Lyozien says that his brother Kazien may have another job for you." },
		Summary = "Kazien"
	},

	12014#More missions#SG_FEEL#QUE_NOIMAGE#
	Lyozien says that his brother Kazien may have another job for you.#
	Kazien#
```

The kro source file from 2020-12-04 on the other hand contains descriptions that relates to the Cube Room Quest of the Fishburn NPC:
```
	[12014] = {
		Title = "생체연구소 잠입",
		Description = { "생체연구소에 잠입해야 합니다. 임무에 대한 지시사항은 피시번에게 받으십시오." },
		Summary = "(진행중)"
	},

	Google Translated:
	[12014] = {
	Title = "Infiltrate the Bioresearch Institute"
	Description = {"You must infiltrate the Biomedical Lab. Get instructions on the mission from Fishburn." },
	Summary = "(in progress)"
	},
```

Since both Quests (Cube Room and Rekenber Job) activate this quest info, it will be out of place either for one or the other.

2 solutions exist:

- Cheap way: completely remove usage of questinfo id 12014 bei Cube Room Quest.
Possibly outdated english questinfo could stay the same.
Only 2 lines in script would have to be commented out.

- Perfectionist/correct way: Completely remove usage of questinfo id 12014 bei Rekenber Job Quest
(For maintainers of translation projects: The english questinfo for 12014 would need to be updated.)
(For maintainers of translation projects: The english questinfo for 12007-12013 would need to be checked against the kro one - some of the remaining descriptions seem to have shifted up a position.)
Script "npc\quests\quests_lighthalzen.txt"'s  present usage of questinfo 12007-12013 would need to be reviewed to make sure it fits with the possibly shifted korean questinfo.

**Comment by Atemo** [comment]
Fixes in https://github.com/rathena/rathena/commit/ba690450ffa87dd438bc717876e2a444538aa3e5
