### ISSUE TITLE
Genetic Sling Item : Mysterious Powder Missing -15% MHP

### ISSUE THREAD

**Issue by Paoly28** [rathena/rathena#585]
Currently Sling item using Mysterious powder doesn't do anything , it's supposed to reduce target's MHP by 15% for 15 seconds.

**Comment by aleos89** [comment]
Can you please provide where you got this information from? Thanks.

**Comment by Paoly28** [comment]
http://db.irowiki.org/db/item-info/13268/

**Comment by aleos89** [comment]
From various sources (not including iRO) it's only supposed to reduce MaxHP by 2% for 10 seconds. iRO Wiki Database is out of date with a lot of stuff and sometimes has custom data in it that other official servers don't have.
