### ISSUE TITLE
Sura skill Hell Gate

### ISSUE THREAD

**Issue by Rododark** [rathena/rathena#5852]
Client Date: 2020-06-03
Server Mode: RE

Hello I have a problem with the damage of the skill **Hell Gate**, the damage reduction in skill_damage_db is not applied and I have it configured in this way and the same damage continues **SR_HELLGATE,1,6,-1000**

**Comment by Melk3000** [comment]
Skill Hell Gate, is taking Element Converter Scroll.

**Comment by Rododark** [comment]
as well I do not understand well????

**Comment by Melk3000** [comment]
Skill should be Neutral, but can be elemental with Elemental Converter.

**Comment by Rododark** [comment]
Oh I know but the problem is that the damage is not reduced with skill_damage_db and with other skills if only this one fails me.

**Comment by aleos89** [comment]
You're using the wrong skill. SR_HELLGATE is disabled and has no effect.
