### ISSUE TITLE
ATK / DEF refine bonus error

### ISSUE THREAD

**Issue by eppc0330** [rathena/rathena#5853]
* **rAthena Hash**: #2494

* **Client Date**: 20210107

* **Server Mode**: Renewal

* **Description of Issue**: 

1: ATK / DEF bonus gets reset with +20 refine.

no refine
![image](https://user-images.githubusercontent.com/47050704/114423631-55466600-9bf2-11eb-833c-360227faa91a.png) ![image](https://user-images.githubusercontent.com/47050704/114424779-69d72e00-9bf3-11eb-8eff-079dfaad15f8.png)
+10
![image](https://user-images.githubusercontent.com/47050704/114423844-8a52b880-9bf2-11eb-9198-acc450110bca.png) ![image](https://user-images.githubusercontent.com/47050704/114424870-7c516780-9bf3-11eb-98fa-2c6afeb4392a.png)
+19
![image](https://user-images.githubusercontent.com/47050704/114423943-a2c2d300-9bf2-11eb-89af-f792b6276be1.png) ![image](https://user-images.githubusercontent.com/47050704/114424966-925f2800-9bf3-11eb-9fce-bee077a60c5e.png)
+20
![image](https://user-images.githubusercontent.com/47050704/114424101-c554ec00-9bf2-11eb-8a3e-d94efee23dd6.png) ![image](https://user-images.githubusercontent.com/47050704/114425149-c5a1b700-9bf3-11eb-8dd2-3df96465704b.png)

2: Refine bonus value also is wrong, I guess.

Before patch
![image](https://user-images.githubusercontent.com/47050704/114427507-1a463180-9bf6-11eb-94ad-df375d7b407a.png)

After patch
![image](https://user-images.githubusercontent.com/47050704/114427755-5c6f7300-9bf6-11eb-9df6-eb6d8f8dd3dd.png)

**Comment by Lemongrass3110** [comment]
Did you manually merge this because you stated #2494 as your hash?

**Comment by eppc0330** [comment]
> Did you manually merge this because you stated #2494 as your hash?

Yes I did. Thanks
