### ISSUE TITLE
Equipping Title not working

### ISSUE THREAD

**Issue by Brizyous** [rathena/rathena#5855]
* **rAthena Hash**: d33ea1819384e1d5f6b6c987d722d40996db38ed

* **Client Date**: 2020-04-01b

* **Server Mode**: RE

* **Description of Issue**: Equipping title does not change title_id on sql database
  * Result: Double clicking a title does nothing
  * Expected Result: Double clicking should equip/change a title
  * How to Reproduce: complete achievement and try equip a title

* **Modifications that may affect results**: Installed ExtendedBG by grenat50 with no errors

**Comment by Lemongrass3110** [comment]
This is a known bug of this client.
