### ISSUE TITLE
Issues in Latest GIT update

### ISSUE THREAD

**Issue by tmav94** [rathena/rathena#586]
clif.c: In function ‘clif_broadcast_obtain_special_item’:
clif.c:18198: warning: unused variable ‘pos’

status.c: In function ‘status_change_timer’:
status.c:11961: warning: suggest explicit braces to avoid ambiguous ‘else’

**Comment by cydh** [comment]
can u show me what's ur `status.c:11961` content?

**Comment by tmav94** [comment]
11954 to 11966

	case SC_LEECHESEND:
		if( --(sce->val4) >= 0 ) {
			int damage = status->vit * (sce->val1 - 3) + status->max_hp / 100; // {Target VIT x (New Poison Research Skill Level - 3)} + (Target HP/100)

			map_freeblock_lock();
			status_damage(bl, bl, damage, 0, clif_damage(bl,bl,tick,status_get_amotion(bl),status_get_dmotion(bl)+500,damage,1,DMG_NORMAL,0), 0);
			unit_skillcastcancel(bl, 2);
			if (sc->data[type])
				sc_timer_next(1000 + tick, status_change_timer, bl->id, data );
			map_freeblock_unlock();
			return 0;
		}
		break;
