### ISSUE TITLE
Kyrie Eleison Bug

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#5867]
* **rAthena Hash**: 04d1f1f

* **Client Date**: 20200401

* **Server Mode**: RENEWAL

* **Description of Issue**: 
  * Result:  Kyrie Eleison unlimited hit not disapear
  * Expected Result: Kyrie Eleison 10 hit must disapear
  * How to Reproduce:  Used sc_start SC_KYRIE,360000,10;
  * Official Information: 
  

* **Modifications that may affect results**: 
* Maybe this is related other skill? because my healer using this:
percentheal 100,100;
skilleffect 34,0; sc_start SC_BLESSING,360000,10;
skilleffect 29,0; sc_start SC_INCREASEAGI,360000,10;
skilleffect 66,0; sc_start SC_IMPOSITIO,360000,5;
skilleffect 67,0; sc_start SC_SUFFRAGIUM,360000,3;
sc_start SC_KYRIE,360000,10;
skilleffect 74,0; sc_start SC_MAGNIFICAT,360000,5;
skilleffect 75,0; sc_start SC_GLORIA,360000,5;
skilleffect 33,0; sc_start SC_ANGELUS,360000,10;

**Comment by aleos89** [comment]
Your script looks fine and the skill works just fine for me. The barrier effect will display even if the monster "misses" a target. The monster you are testing against vs the character is probably too low which makes it look like Kyrie is blocking all of the hits.
