### ISSUE TITLE
Character stuck if @go/warp after @refineui without closing/cancel

### ISSUE THREAD

**Issue by reunite-ro** [rathena/rathena#5869]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/7a1ea09eb1a69512651431a672c339991c7af226

* **Client Date**: 20180620

* **Server Mode**: Pre-Renewal

* **Description of Issue**: 
  * Result: Character stuck if `@go` after `@refineui` without closing/cancel it.
  * Expected Result: Maybe we can make it like `@storage` ? Auto cancel/close if ``` `@go` ``` or ``` `@warp` ```.  
  * How to Reproduce: `@refineui`, then `@go` anywhere. Character will stucked because client assume refineui is still open.
  * Official Information: I didnt have any information, but maybe we can make this feature autoclose such as ``` `@storage` ``` ?
  

* **Modifications that may affect results**: None
  
  

Also, maybe updating the information in docs atcommand.txt which still using information refine_db.txt in reloadstatusdb section.

**Comment by RadianFord** [comment]
I can confirm this one and when trying to run the refineui server is saying that its already opened.
