### ISSUE TITLE
maybe in homum, any fix with this sir?

### ISSUE THREAD

**Issue by anjuts** [rathena/rathena#587]
(gdb) bt full
#0  0x081b75bc in hom_checkskill (hd=0xa45cc02c, flag_evolve=0)
    at homunculus.c:271
No locals.
#1  hom_calc_skilltree (hd=0xa45cc02c, flag_evolve=0) at homunculus.c:250
        i = <value optimized out>
        id = 8006
        j = <value optimized out>
        f = <value optimized out>
        c = <value optimized out>
#2  0x080bbfb5 in status_calc_homunculus_ (hd=0xa45cc02c, first=1 '\001')
    at status.c:3706
        status = 0xa45cc218
        hom = 0xa45cd2cc
        skill = <value optimized out>
        amotion = <value optimized out>
#3  0x080bc763 in status_calc_bl_ (bl=0xa45cc02c, flag=SCB_ALL, first=1 '\001')
    at status.c:4599
        b_status = {hp = 0, sp = 0, max_hp = 0, max_sp = 0, str = 0, agi = 0,
          vit = 0, int_ = 0, dex = 0, luk = 0, batk = 0, matk_min = 0,
          matk_max = 0, speed = 0, amotion = 0, adelay = 0, dmotion = 0,
          mode = 0, hit = 0, flee = 0, cri = 0, flee2 = 0, def2 = 0,
          mdef2 = 0, aspd_rate = 0, def = 0 '\000', mdef = 0 '\000',
          def_ele = 0 '\000', ele_lv = 0 '\000', size = 0 '\000',
---Type <return> to continue, or q <return> to quit---^Crace = 0 '\000Quit

**Comment by aleos89** [comment]
Which hash/version are you on?

**Comment by anjuts** [comment]
http://www.mediafire.com/download/qaeexc507gq3w97/homun.rar

**Comment by anjuts** [comment]
sir any fix here?

**Comment by daniefkd** [comment]
My crash on humunculus continues even after applying the patches.
