### ISSUE TITLE
Vacuum Xtreme crash map server

### ISSUE THREAD

**Issue by Melk3000** [rathena/rathena#5876]
* **rAthena Hash**: 
3b1d0a1

* **Client Date**: 
20200401

* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result: 
  * Skill Vacuum Xtreme crash map server when used
  * Expected Result: 
  * How to Reproduce: 
  Use Vacuum Xtreme in pvp or WoE and will crash map server
  
map-msg_log show:
[ Debug ] : status_change_timer: Null pointer id:
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment]
Missing the most important thing: your rAthena hash.

Additionally this does not crash the map-server, but prevent the map-server from crashing. So your real crash is coming from another reason.

Please provide your hash and a crashdump.

**Comment by Melk3000** [comment]
Rathena hash 3b1d0a1, Crash is when other player enter in vacuum .

**Comment by Lemongrass3110** [comment]
Update your emulator then. This was already fixed.
