### ISSUE TITLE
HD Refine Not Work if not bring the Blacksmith Blessings 

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#5879]
* **rAthena Hash**: a38501f

* **Client Date**: 20200401

* **Server Mode**: RENEWAL

* **Description of Issue**: 
  * Result:  HD Refine Not Work if not bring the Blacksmith Blessings 
  * Expected Result:  WORK if not have Blacksmith Blessings 
  * How to Reproduce:  DISABLE refine ui, then test using Mighty Hammer but you must not have Blacksmith Blessing, only you have HD stone and zeny without Blacksmith Blessing
  * Official Information: 
  

* **Modifications that may affect results**: i remove group shadow armor and shadow weapon

**Comment by Lemongrass3110** [comment]
Sorry I linked the wrong issue in my pull request yesterday.
@Atemo can you check the new script logic that was added?
