### ISSUE TITLE
copyskill_restrict

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#588]
The rogue class is copying multiple skills out instead of just 2.

I searched but did not find more configuration limits the number of copies that the class can do.

/conf/battle/skill.conf

// Can Rogues plagiarize advanced job skills
// 0 = no restriction
// 1 = only stalker may plagiarize advanced skills
// 2 = advanced skills cannot be plagiarized by anyone
// Official servers setting: 2
copyskill_restrict: 2

**Comment by admkakaroto** [comment]
print: http://i.imgur.com/uczud2x.png

**Comment by cydh** [comment]
just `clif_deleteskill` placement issue. my bad

**Comment by cydh** [comment]
first, that config has been removed for long ago. for now, please see https://github.com/rathena/rathena/blob/master/db/skill_copyable_db.txt.
and ur image, just `clif_deleteskill` placement issue in skill.c::`skill_do_copy`. my bad

**Comment by admkakaroto** [comment]
Any solution?

**Comment by admkakaroto** [comment]
I think it is still the same thing in the last revision of git

**Comment by aleos89** [comment]
Fixed in 04d2ab7. I didn't realize @cydh had fixed it in a previous commit.
