### ISSUE TITLE
reloadstatusdb has no effect on refining UI

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#5884]
* **rAthena Hash**: 6ee2539

* **Client Date**: 20200401

* **Server Mode**: RENEWAL

* **Description of Issue**: 
  * Result: reloadstatusdb has no effect on refining UI.
  * Expected Result: reloadstatusdb reloads refine.yml and affects refine UI. 
  * How to Reproduce: when server running edit refine.yml example put a # sign on blacksmithblessingamount then command at reloadstatusdb, refine.yml will reload but if you using refine UI there is using old yml like no reloading changes .
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by reunite-ro** [comment]
I didnt tried on Renewal yet, but for pre-renewal ive test it around last week by changing the percentage and it works.

How do i check : by checking the percentage of success.

https://www.youtube.com/watch?v=gCA0aiwLx2o

**Comment by mazvi** [comment]
Okay, that means it works for rate changes, but it doesn't work for us to delete blacksmithblessingamount by giving a # sign, but this doesn't matter because just restart the server after deleting blacksmithblessingamount with a sign #, I think I will temporarily close this issue.

**Comment by mazvi** [comment]
I think i will open again this issue

**Comment by Lemongrass3110** [comment]
Sorry I linked the wrong issue in 7052b8a. But this is fixed already.
