### ISSUE TITLE
Correct 'View' Headgear

### ISSUE THREAD

**Issue by lChyztl** [rathena/rathena#5889]
* **rAthena Hash**: 

* **Client Date**: 2018-06-21a

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**: 
  
  

  - Id: 20236
    AegisName: C_Hellomother_Hat
    Name: Costume Arc Angeling Hat
    Type: Armor
    Locations:
      Costume_Head_Top: true
    EquipLevelMin: 1
    View: 241 ----- > **341**
    
  - Id: 31710
    AegisName: Costume_Lucky_Hat
    Name: C Lucky Hat
    Type: Armor
    Locations:
      Costume_Head_Top: true
    EquipLevelMin: 1
    View: 31710 ---- > **740**

**Comment by reunite-ro** [comment]
Hello, where did you found the information about viewid for 31710 ? I think you wrongly paste it ?

From Chris Translation and I double check from https://www.divine-pride.net/database/item/31710 it is 740.

`	[31710] = {
		unidentifiedDisplayName = "Unidentified Hat",
		unidentifiedResourceName = "ĸ",
		unidentifiedDescriptionName = { "Can be identified by using a ^990099Magnifier^000000." },
		identifiedDisplayName = "Costume Lace Flower Crown",
		identifiedResourceName = "����Ǹ���",
		identifiedDescriptionName = {
			"A lace crown decorated with flowers. Wearing this brings good luck.",
			"________________________",
			"^0000CCType:^000000 Costume",
			"^0000CCPosition:^000000 Upper",
			"^0000CCWeight:^000000 0",
			"________________________",
			"^0000CCRequirement:^000000 None"
		},
		slotCount = 0,
		ClassNum = 740`

**Comment by lChyztl** [comment]
ahh, yes
sorry, I forget about 3170
