### ISSUE TITLE
Curse and Blessing

### ISSUE THREAD

**Issue by Atemo** [rathena/rathena#589]
Our current implementation of blessing remove the curse status and (re)buff a target in one go. From my test on iro/fro and according to iro http://irowiki.org/wiki/Blessing
> When used on a target to remove Curse status, they will not receive the stat boosts.

Officially Blessing must be used twice to (re)buff (I mean give the buff or update the buff timer) a target with curse effect.

**Comment by reigneil** [comment]
yeah thats how it is officially... i remember back then i used level 1 blessing for my bot when cursed to conserve sp.

**Comment by Playtester** [comment]
Really? I've never noticed that even though I'm playing an Acolyte on iRO classic. Well, it's pretty easy to test anyway.

**Comment by reigneil** [comment]
i tested this on iRO renewal if there are changes but nothing change still can't receive buff when cursed or if blessing is active it didn't refresh its timer.
