### ISSUE TITLE
Changing monsters name does not work.

### ISSUE THREAD

**Issue by RadianFord** [rathena/rathena#5898]
* **rAthena Hash**: 2c0283d0e07e3887d677758994f294cc4d9fd58d

* **Client Date**: 2018-06-20eRagexeRE

* **Server Mode**: Pre-renewal

* **Description of Issue**: Changing the `Name in English.` in pre/mob_db.yml into import/mob_db.yml.
  * Result: It didnt change/update its name.
  * Expected Result: 
  * How to Reproduce:

Pre mob_db
```
  - Id: 1806
    AegisName: B_EREMES_
    Name: Assassin Cross Eremes
```
import mob_db
```
  - Id: 1806
    Name: Radian
```

**Comment by mikkotandoc** [comment]
You deleted the AegiesName? Try. AegiesName is callout to which sprite to look for.

  - Id: 1806
    AegisName: B_EREMES_
    Name: Radian

**Comment by Lemongrass3110** [comment]
Any errors on the map-server console?

Are you talking about spawned monsters? Those usually have hardcoded names in the NPC scripts.

**Comment by RadianFord** [comment]
> You deleted the AegiesName? Try. AegiesName is callout to which sprite to look for.
> 
> * Id: 1806
>   AegisName: B_EREMES_
>   Name: Radian

Only the things that i changed was added on the import files.

**Comment by RadianFord** [comment]
> Any errors on the map-server console?
> 
> Are you talking about spawned monsters? Those usually have hardcoded names in the NPC scripts.

No errors, this mob is added on a mob_avail.yml to spawn like a player but the name does not change, I checked the client side if the name is right there.

**Comment by Atemo** [comment]
We keep the 2 fields for the monster name - "english name" and "japanese name" - from the txt version. Don't ask me why but some features are using the japanese and some the english name.
In your import you only changed the english name, to do it properly change the 2 fields `Name` and `JapaneseName`
```
#   Name                    Name in English.
#   JapaneseName            Name in Japanese. (Default: 'Name' value)
```

**Comment by RadianFord** [comment]
> We keep the 2 fields for the monster name - "english name" and "japanese name" - from the txt version. Don't ask me why but some features are using the japanese and some the english name.
> In your import you only changed the english name, to do it properly change the 2 fields `Name` and `JapaneseName`
> 
> ```
> #   Name                    Name in English.
> #   JapaneseName            Name in Japanese. (Default: 'Name' value)
> ```

Now its working, thank you for this.
