### ISSUE TITLE
Marionett Control Should NOT be casted on Quagmired/Cursed targets

### ISSUE THREAD

**Issue by Tydus1** [rathena/rathena#5908]
* **rAthena Hash**: Latest

* **Client Date**: 20200401

* **Server Mode**: Pre-Renewal (not sure if Renewal had its behavior as well so...)

* **Description of Issue**: 
  * Result: Players are able to cast Marionett Control on Quagmired/Cursed targets;
  * Expected Result: Marionett Control should NOT be able to be casted on Quagmired/Cursed targets;
  * How to Reproduce: Just cast quagmire on another player and then cast marionett control. Same for curse status (You will need  to be in the same party to cast marionett control)
  * Official Information:  The profs provided here were obtained from a discursion on OriginRO discord (Thanks to Xellie). The images below are a supposedly test on Aegis. (Would be nice if anyone with Aegis access could confirm)
  

* **Modifications that may affect results**: None

https://user-images.githubusercontent.com/16859064/116488845-cb410300-a869-11eb-98b4-667013552081.mp4

Sorry the bad quality. Had to lower its quality to fit it into this issue;

**Comment by Xelliekins** [comment]
Can also confirm it worked this way on iRO classic ( I ran Aegis testing recently to check my memory)
