### ISSUE TITLE
Skull dont drop after kill a player in all situations. (battle/player.conf)

### ISSUE THREAD

**Issue by tmav94** [rathena/rathena#591]
My server is setted to 2 and skull dont drop.

Server RE
20130807

// Players' will drop a 'Skull' when killed?
// 0 = Disabled
// 1 = Dropped only in PvP maps
// 2 = Dropped in all situations
bone_drop: 2

**Comment by Thurin** [comment]
I have the same problem. 
:/

**Comment by nanakiwurtz** [comment]
Which git hash are you on?

**Comment by tmav94** [comment]
How can i see? I'm in the latest update.

**Comment by icxbb-xx** [comment]
please check
db/re/item_trade.txt

remove this line
7420,499,100	// Skull_
