### ISSUE TITLE
Green Potion should NOT remove Confusion/Chaos negative status

### ISSUE THREAD

**Issue by Tydus1** [rathena/rathena#5910]
* **rAthena Hash**: Latest

* **Client Date**: 20200401

* **Server Mode**: Pre-Renewal (not sure if Renewal had its behavior as well so...)

* **Description of Issue**: 
  * Result: Green Potion (ID: 506) is actually removing Confusion/Chaos negative status;
  * Expected Result: Green Potion should NOT remove Confusion/Chaos negative status;
  * How to Reproduce: Cause Confusion/Chaos on a characters and then use Green Potion.
  * Official Information: The profs provided here were obtained from a discursion on OriginRO discord (Thanks to Xellie). The information presented is a supposedly test on Aegis. (Would be nice if anyone with Aegis access could confirm)
  

* **Modifications that may affect results**: None

**Comment by llchrisll** [comment]
I'm not sure if it's still possible to check for pre-renewal behaviour, but renewal version:
`초록허브를 잘 갈아 만든 치료제 독과 침묵과 암흑과 혼란, 환각을 치료해준다.`
translates to:
`A remedy made by grinding green herbs, it cures poison, silence, darkness, confusion, and hallucinations.`
https://divine-pride.net/database/item/506

**Comment by Daegaladh** [comment]
I confirm this, in pre-renewal it removes Poison, Silence and Blindness only

**Comment by Daegaladh** [comment]
Fixed in 80e2e5221a34a1c4645487ef64a2d13884f1210c
