### ISSUE TITLE
Black inu hat make map crash

### ISSUE THREAD

**Issue by AsurielRO** [rathena/rathena#5915]
* **rAthena Hash**:  latest

* **Client Date**:  20200304

* **Server Mode**:  renewal

* **Description of Issue**: 
  * Result:  Moment Black Shiba Inu autocast proc'd server ded, "When equipped with Fidelity Necklace:
When dealing or receiving physical attacks, has a low chance to transform into Atroce.
While in transformed state, ATK +30 and drains 5 SP per second.
Refine rate of the headgear increases the chance of transform activation."
Moment the transformation proc'd, server crash
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by laziem** [comment]
I can't confirm this, works on my 60b1b514d

![image](https://user-images.githubusercontent.com/31171415/116868235-9c93a580-ac38-11eb-88f9-78ee489b6e4f.png)

**Comment by aleos89** [comment]
Can you provide the crash log?

**Comment by Atemo** [comment]
No information from the user has been provided.
