### ISSUE TITLE
Spirit Ball Error

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#5916]
* **rAthena Hash**: 60b1b51

* **Client Date**: 20200401

* **Server Mode**: RENEWAL

* **Description of Issue**: [Error]: delete_timer error : function mismatch 0x540730(pc_spiritball_timer) != 0x5e6330(skill_keep_using)
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Did you check out #5354?
