### ISSUE TITLE
GTB card should not block status changes from self skills on self even if they are magic

### ISSUE THREAD

**Issue by Playtester** [rathena/rathena#5918]
* **rAthena Hash**: 60b1b51

* **Client Date**: -

* **Server Mode**: Pre-Renewal (but probably applies to both)

* **Description of Issue**: 

I saw reports that skills like Ruwach and Sight are blocked by GTB since our last change but they shouldn't. Originally I thought we might have incorrectly defined these as "magic", but when testing Magnificat and Gloria on Aegis I noticed that these skills apply status change on self, but are still blocked by GTB on all other targets (so if all in the party wear GTB only caster gets the buff).

Which made me think that maybe for self skills there's a special rule that makes GTB not block status changes. So we actually went and tested all the self-skills that are defined as "magic" in rAthena and all of them applied their status changes to the caster.

Target skills should get blocked even when cast on self.

Self skills should get blocked on all targets except self.

Here's a list of skills that work on self even with GTB on (giving the status change to self but not any other targets with GTB):
Ruwach
Sight
Angelus
Magnificat
Gloria
Energy Coat
Cast Cancel
Magic Rod
Hindsight
Hocus Pocus
Basilica
Mystical Amplification
Indulge
Foresight
Star Gladiator Feel / Comfort Skills
Double Casting
Mirror Image

Note that Grand Cross still doesn't work on self. The whole skill actually fails to cast if you wear GTB.

**Comment by jimjimi09** [comment]
Hi, I have tried to add IgnoreGtb: true on Flags on my skill_db.yml unfortunatelly upon @reloadskilldb it doesn't work with GTB. also tried compiling and restarting the server
