### ISSUE TITLE
Cannot use flywing item after using a skill with cooldown/delay

### ISSUE THREAD

**Issue by sapiro1403** [rathena/rathena#5919]
* **rAthena Hash**: a59864438

* **Client Date**: 2013-08-07aRagexe

* **Server Mode**: Pre-Renewal

* **Description of Issue**: Cannot use Flywing item after casting any skill that has cooldown/delay
  * Result: After casting a skill you need to wait for the cooldown/delay before you can use Flywing
  * Expected Result:  Player should be able to use Flywing after casting a skill regardless of if skill has cooldown/delay
  * How to Reproduce: 
  * Official Information:  Tested on ROMSP, flywing can be used after a skill is casted
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Quick guess is because Fly Wing invokes the AL_TELEPORT skill, so if a skill has an AfterCastActDelay then it will most likely fail here.

**Comment by sapiro1403** [comment]
- Id: 26
    Name: AL_TELEPORT
    Description: Teleport
    MaxLevel: 2
    Type: Magic
    TargetType: Self
    DamageFlags:
      NoDamage: true
    Flags:
      IgnoreKagehumi: true
      AllowOnMado: true
    Hit: Single
    HitCount: 1
    CastCancel: true
    Requires:
      SpCost:
        - Level: 1
          Amount: 10
        - Level: 2
          Amount: 9

Here is the skill AL_TELEPORT from skill_db.yml

**Comment by maxtorohell** [comment]
I'd say it's the same as #4254 
https://github.com/rathena/rathena/issues/4254

**Comment by aleos89** [comment]
Teleport doesn't have the delay. It would be another skill used before consuming a Fly Wing that has an AfterCastActDelay.

**Comment by sapiro1403** [comment]
* **Client Date**:  2013-08-07aRagexe
* **rAthena Hash**:  0d8b5c706

Tested same client exe on rathena hash above.
Can use flywing even if skill ha AfterCastActDelay
