### ISSUE TITLE
Sorcerer Call Ventus fixed cast time

### ISSUE THREAD

**Issue by sssssilver** [rathena/rathena#592]
https://youtu.be/wDC8Z2yyhSc

[(0:20)](https://youtu.be/wDC8Z2yyhSc?t=20s) Spirit Control Invalid after Sacrament

iRO wiki

Call Ventus | Sacrament
------------ | -------------
The Ventus summon allows the sorcerer to reduce their fixed cast time by 1 sec. This is a huge boost considering most of sorcerers skills has a 1 sec fixed cast time on them, so using ventus means you can get rid of the fixed cast time part on some of your skills. Note that level 1 to 3 Ventus gives the same amount of fixed cast time reduction  | For 60~180 seconds, target ally has -10~50% fixed cast time. 

Cannot be superimposed with the skills?

**Comment by Daedren** [comment]
Those skills (DD at Lv5) don't even have fixed cast time to begin with. It's all variable. Neither Sacrament nor Ventus should be affecting them.

See https://github.com/rathena/rathena/issues/549

**Comment by nanakiwurtz** [comment]
Which git hash are you on?
(I've asked this question over and over again on multiple issues, and "Latest version" is not a valid answer)

**Comment by sssssilver** [comment]
my git hash version is 02b31b9dfc4ebbc6f88119f20c19f0d443414d29
Still have this problem 
client date : 20140305
