### ISSUE TITLE
Preview Feature on quest_shop.txt is bug. No change to default after finish use npc.

### ISSUE THREAD

**Issue by playpsro** [rathena/rathena#5923]
Hello want to report bug on NPC quest_shop.txt 
When player use preview there is have a bug view headgear is not changed back to real headgear used.
I provide the video link to description and clear information.

[https://youtu.be/B3SJYuAOklU](url)

**Comment by Atemo** [comment]
Unable to reproduce on https://github.com/rathena/rathena/commit/21a81980411a4790d3a60b91e5ea08fe00cf6739

**Comment by pigati23** [comment]
> I think its not source bug but a script?

It must definitely be a script bug, but maybe from some old version of quest shop.

**Comment by Atemo** [comment]
I'm still unable to reproduce.
