### ISSUE TITLE
Need Correction Item Combo 4036:4186:4233:4281:4343

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#5924]
* **rAthena Hash**: 16b4cbf

* **Client Date**: 20200401

* **Server Mode**: RENEWAL

* **Description of Issue**: Need Correction Item Combo 4036:4186:4233:4281:4343
  * Result:  No Drop Glistening Coat only Stem
  * Expected Result: A low chance of obtaining Glistening Coat and/or Stem when defeating monsters.
  * **This is not only and but also or, maybe need script rand case? case1 only stem, case2 only Glistening coat, case2 stem and glistening coat?**
  * How to Reproduce: check https://github.com/rathena/rathena/blob/master/db/re/item_combo_db.txt
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by Playtester** [comment]
bonus2 bAddMonsterDropItem,7139,3; bonus2 bAddMonsterDropItem,905,10;

  - Id: 7139
    AegisName: Coating_Bottle
    Name: Glistening Coat
    Type: Etc
    Buy: 200
    Weight: 10

Looks correct to me?

**Comment by Atemo** [comment]
There is no issue on https://github.com/rathena/rathena/commit/21a81980411a4790d3a60b91e5ea08fe00cf6739 
The rate of Glistening Coat in the combo is just lower but the item is dropped.
