### ISSUE TITLE
Frost Nova Bug (Pre-Re)

### ISSUE THREAD

**Issue by Miraakol** [rathena/rathena#5926]
* **rAthena Hash**: 21a81980411a4790d3a60b91e5ea08fe00cf6739

* **Client Date**: 2018-06-20eRagexe.exe

* **Server Mode**: Pre-Renewal

* **Description of Issue**:
  * Result: Frost Nova works on Land Protector/Magnetic Field
  * Expected Result: Frost Nova does not work on Land Protector/Magnetic Field
  * How to Reproduce: Use Frost Nova on Land Protector/Magnetic Field
  * Official Information:  please see this link for reference https://irowiki.org/classic/Frost_Nova
  

* **Modifications that may affect results**: 
  no modification im using clean and latest rev
  N/A

**Comment by Playtester** [comment]
Can confirm this. Comet should also behave like that by the way (but that's renewal only).

**Comment by Miraakol** [comment]
here's also the official behavior in official server :)

https://www.youtube.com/watch?v=u_9GRoVF4jA

**Comment by aleos89** [comment]
Your video is gone. Does the skill just not damage targets on LP, or does the skill fail completely?
