### ISSUE TITLE
Error color palette clothing (not NEMO issue)

### ISSUE THREAD

**Issue by OscarScorp** [rathena/rathena#593]
Note: I am using Client 2014-10-22bRagexe_patched.exe

This is the issue that pops up:
 https://embed.gyazo.com/4868981d25428562882e84a56d4dd680.png

I don't understand why is this happening and I don't want my users to get the error every time they try to change clothes color.
Issue occurs when:
- Changing colors while mounting Peco (tested with Crusader class)
- Changing colors above #4 palette with Kagerou / Rebellion
 
What I did first was downloaded this 553/251 Old Dyes / Palette pack from KamiShi: https://rathena.org/board/topic/75214-palette-553251-old-dyes-palettes-working-all-classes/
 
But the issue mentioned above started to happen.
 
Then I tried manually duplicating the Kagerou #4 palette all up until #553 (max). Which is a "solution", but all palettes are the same. I thought KamiShi's pack would have all Kagerou/Oboro and Rebellion color support.
 
Not sure what I'm doing wrong, or if it's the new Client which can't show or locate Crusader+Peco, Kagerou/Oboro and Rebellion color palettes.
It may be a problem with how every file and folder are named? ("¸Ó¸®" or "머리").
Is there any way to actually find the real issue? :(  Should I be posting somewhere else?
 
Sorry and thanks for the help, I really appreciate it.

**Comment by aleos89** [comment]
Sorry, but those warnings are issues with the client, not rAthena. You either have a typo in your palette file name or possibly an issue with the patch for the client. I suggest you post in the client support section of the forum.
