### ISSUE TITLE
Wrong Card resist calculation

### ISSUE THREAD

**Issue by laziem** [rathena/rathena#5932]
* **rAthena Hash**: c44fdaf76

* **Client Date**: 20200401

* **Server Mode**: RE

* **Description of Issue**: 
  * Result: At 30% Player reduction, damage received almost the same amount of 50% reduction. And at 90% reduction, damage received only 0.01%
  * Expected Result: 
  * How to Reproduce: 
    * Trying with Thara Frog Card, play with percentage to check the damage reduction
    * Damage received : 1,119,608 ( Guard[1] )
    * Damage received : 548,568 ( Guard[Thara Frog] - 30% )
    * Damage received : 11,179 ( Guard[Thara Frog] - 90% )
    * It may affect other resistance (Race, Size, Class, Element)
    * Might be related to #5267
  * Official Information: -

* **Modifications that may affect results**: -

![rathenaresist](https://user-images.githubusercontent.com/31171415/117797927-c6714b80-b27a-11eb-9b08-d9e989b664e1.png)

**Comment by MrAntares** [comment]
Please re-try the experiment on a lvl 1 novice with allstat 1. Since bonus percentage reduction comes first and then the reduction calculated from stats (it has both a percentage reduction and fixed value part that is coming only from base stats), having allstat 130 can cause a lot of interference with experiments like this.

**Comment by cinq0demayonaise2** [comment]
i've tested this too already and can replicate the issue.

**Comment by Felleonel** [comment]
I tested and confirmed this issue.

**Comment by feltenc** [comment]
This is annoying problem, i can confirm.

**Comment by Felleonel** [comment]
@aleos89 why this issue is not a high priority?

**Comment by phit666** [comment]
[battle.zip](https://github.com/rathena/rathena/files/6917100/battle.zip)
Im getting the expected values, try the attached battle.cpp and watch your map server console, it will show debug of before and after damage with the actual bonus you are getting.

**Comment by Felleonel** [comment]
I tested it again and noticed that the problem is related with Renewal, not Pre Renewal. At Pre Renewal it's ok.

**Comment by feltenc** [comment]
I think this topic should me a high priority issue due its influence on the gameplay and core systems like PVP/WOE/PVM.

Sir @aleos89 could you recheck this priority?
