### ISSUE TITLE
Fire Expansion Acid formula

### ISSUE THREAD

**Issue by Felleonel** [rathena/rathena#5939]
* **rAthena Hash**:  58f2d21

* **Client Date**: 20200401

* **Server Mode**:  RE

* **Description of Issue**:  In rAthena the current formula for Fire Expansion Acid is similar to the Acid Demonstration. Previously, the skill was magic, ignoring Pneuma and etc. Is the current formula correct? I did some research and no found any information about changes.

**Comment by aleos89** [comment]
This skill changed some in #4072.

```
8.1 Bomb
- Increases the chance to destroy target's weapon.
- Changes damage type from special melee physical damage to normal melee physical damage.
- Changes damage formula.
- Deals additional damage depends on skill level of Potion Research. 
```

**Comment by Felleonel** [comment]
But in this rebalance, nothing was change in Acid Demonstration and Fire Expansion Acid. Fire Expansion is a 3rd Class skill, does not make sense. I read and found nothing about it. @aleos89 

https://www.divine-pride.net/forum/index.php?/topic/3453-kro-mass-skills-balance-1st-2nd-and-transcendent-classes-skills/#comments

**Comment by aleos89** [comment]
Sorry, check out #3284 and #4813.

**Comment by Felleonel** [comment]
Ok @aleos89, but I asked Sigma from Divine Pride if there really was changed and he said no. That the skill remains magic.

![image](https://user-images.githubusercontent.com/19696140/118706223-7dc41000-b7ef-11eb-8b6e-f9f916788522.png)

In the links below, nothing is said about Fire Expansion Acid:
https://ro.gnjoy.com/news/update/View.asp?seq=246&curpage=1
https://www.divine-pride.net/forum/index.php?/topic/3723-kro-jobs-improvement-project/
https://www.divine-pride.net/forum/index.php?/topic/4242-kro-changelog-december-04-2019/
https://www.divine-pride.net/forum/index.php?/topic/4212-kro-changelog-november-20-2019/
https://ro.gnjoy.com/news/devnote/View.asp?category=1&seq=3987555&curpage=1

Do you have another reference?

**Comment by aleos89** [comment]
https://www.divine-pride.net/forum/index.php?/topic/3723-kro-jobs-improvement-project/page/2/&tab=comments#comment-6399

```
 20. Acid Bomb
- Changes skill type.
Before : physical/magical hybrid special long ranged physical damage.
After : Normal long ranged physical damage.
- The skill will no longer ignore hit/flee and hard defense calculation.
- Changes damage formula. New damage formula : (200 x skill level))%Atk.
- Damage is increased depends on user's Int and target's Vit.
- Changes skill property from forced neutral property to depends on weapon property instead.
- Increases SP consumption to 50, adds 0.15 seconds cooldown. 
```

**Comment by Felleonel** [comment]
Fire Expansion Acid does not work like Acid Demonstration  @aleos89 

https://www.divine-pride.net/forum/index.php?/topic/3723-kro-jobs-improvement-project/&do=findComment&comment=9506

![image](https://user-images.githubusercontent.com/19696140/119316943-f4c53280-bc4d-11eb-9fbd-716dfe5030c2.png)
