### ISSUE TITLE
Magma Eruption

### ISSUE THREAD

**Issue by MeliodasGaming** [rathena/rathena#594]
Magma Eruption (Mechanic Skill) isn't in the rAthena server. Why?

**Comment by nanakiwurtz** [comment]
5006,1,6,2,3,0x2,3,5,1,no,0,0,3,misc,0,0x0, NC_MAGMA_ERUPTION,Magma Eruption

**Comment by aleos89** [comment]
It's there. Just make sure you have the latest pull and have correct data files.
