### ISSUE TITLE
Commit from 2021-01-16 / Error in item 4231 script

### ISSUE THREAD

**Issue by KrokusPokus** [rathena/rathena#5940]
* **rAthena Hash**: 58f2d2173

* **Server Mode**: Both

This concerns commit from 2021-01-16 by Aleos:
```
SHA-1: 7992e0891bc05fd92a9ea4c474548d3d7d72e880
* Converts the mob database to YAML (#5435)
* Combines mob_race2 and mob_drop databases into one.
* General cleanups and optimizations.
* Includes CSV2YAML conversion tool.
Thanks to @vstumpf, @lukasrmattos, and @Lemongrass3110!
```
This commit changed the item script of item ID 4231 in the file "item_db_etc.yml" (both pre-renewal and renewal) in a way that it does not match the usual english descriptions anymore.

ID: 4231 (Mi Gao Card)
Item Description:
"Receive 50% less damage from Guardians during War of Emperium hours."
"Decreases damage taken from Guardian by 50% during War of Emperium hours."

Script old:
```
bonus2 bSubRace2,RC2_Guardian,50;

//bonus2 bSubRace2,mr,x;
//(x% damage reduction against monster race mr)
```

Script new: 
```
bonus2 bAddDamageClass,1285,-50;
bonus2 bAddDamageClass,1286,-50;
bonus2 bAddDamageClass,1287,-50;
bonus2 bAddDamageClass,1899,-50;
bonus2 bAddDamageClass,1900,-50; 

//bonus2 bAddDamageClass,mid,x;
//(+x% physical damage against monster mid)
```

The the present item script would cause players to do 50% less damage on the specified MobIDs (woe guardians) for each card.

**Comment by KrokusPokus** [comment]
Looking through the source i noticed the comment
`RC2_GUARDIAN, // Deprecated to CLASS_GUARDIAN`

I guess this was the reason why item 4231 (Mi Gao Card) and item 4251 (Elder Card) were changed in a way that would remove the usage of RC2_GUARDIAN. I'm not sure why the choice was made to switch to bAddDamageClass bonus instead of bSubClass/bAddClass with CLASS_GUARDIAN:

**4231 (Mi Gao Card)**
Script before 2021-01-16 (deprecated variable RC2_Guardian):
`bonus2 bSubRace2,RC2_Guardian,50;`

Script after 2021-01-16:
`bonus2 bAddDamageClass,1285,-50;\nbonus2 bAddDamageClass,1286,-50;\nbonus2 bAddDamageClass,1287,-50;\nbonus2 bAddDamageClass,1899,-50;\nbonus2 bAddDamageClass,1900,-50;`

Script suggestion:
`bonus2 bSubClass,CLASS_GUARDIAN,50;`


**4251 (Elder Card)**
Script before 2021-01-16 (deprecated variable RC2_Guardian):
`bonus2 bAddRace2,RC2_Guardian,40;`

Script after 2021-01-16:
`bonus2 bAddDamageClass,1285,40;\nbonus2 bAddDamageClass,1286,40;\nbonus2 bAddDamageClass,1287,40;\nbonus2 bAddDamageClass,1899,40;\nbonus2 bAddDamageClass,1900,40;`

Script suggestion:
`bonus2 bAddClass,CLASS_GUARDIAN,40;`

**Comment by aleos89** [comment]
Yes, the initial reason is because we deprecated that race value. When I looked up the Aegis define for these cards I implemented like I saw it. Although now looking back at it after you made this report I see that I missed that it defines "User" as the value and not "Target" which is how I have it now. I will fix this up.
