### ISSUE TITLE
Empty Castle with spawns

### ISSUE THREAD

**Issue by RadianFord** [rathena/rathena#5946]
* **rAthena Hash**: 58f2d2173f604296f0f72d2eb92afda879c3cfa1

* **Client Date**: 2018-06-20eRagexeRE

* **Server Mode**: Pre-renewal

* **Description of Issue**: Player queue is full. (I know editing the MAX_EVENTQUEUE) will fix this but is that kinda weird? or its just me thinking this is not right?
  * Result: After killing/breaking the `EMPERIUM` on the castle monsters got killed and triggers this.
```[Warning]: npc_event: player's event queue is full, can't add event 'BKTriggers::OnNPCKillEvent' !
[Warning]: npc_event: player's event queue is full, can't add event 'MvP Ranking::OnNPCKillEvent' !
[Warning]: npc_event: player's event queue is full, can't add event 'Reincarnation::OnNPCKillEvent' !
[Warning]: npc_event: player's event queue is full, can't add event 'Monster Hunting::OnNPCKillEvent' !
[Warning]: npc_event: player's event queue is full, can't add event 'BKTriggers::OnNPCKillEvent' !
```

**Comment by aleos89** [comment]
That's the only fix for this. Sounds like you just have a lot of scripts attached to players at the same time which is why you're seeing this.

**Comment by RadianFord** [comment]
> That's the only fix for this. Sounds like you just have a lot of scripts attached to players at the same time which is why you're seeing this.

Thank you for your answer.
