### ISSUE TITLE
Comet/Earth Strain and Maya Card

### ISSUE THREAD

**Issue by Felleonel** [rathena/rathena#5951]
* **rAthena Hash**: c44fdaf

* **Client Date**:  20200401

* **Server Mode**: RE

* **Description of Issue**: 
  * Result: 1 - Maya Card is reflecting the damage of the Comet. 
                2 - Maya Card is not reflecting the damage of the Earth Strain used by Release. 
  
* Expected Result: 1 - Maya Card does not work on Comet. Comet is a ground skill (13x13 cells), Maya only reflect single target magic skill. 
  2 - Release is a single target magic skill, so should be reflected by Maya Card. 
  
* How to Reproduce: Use Comet/Release (Earth Strain) in another player that has a shield with Maya Card. 
  * Official Information: https://divine-pride.net/database/item/4146/maya-card

**Comment by feltenc** [comment]
Confirmed the issue on rAthena Hash: c44fdaf.

**Comment by Playtester** [comment]
The first one is related to the issue that Comet should be a unit skill, but isn't.

**Comment by feltenc** [comment]
> The first one is related to the issue that Comet should be a unit skill, but isn't.

So is this correct? Should she reflect with the maya card?

**Comment by feltenc** [comment]
@Playtester can you confirm?

**Comment by MrAntares** [comment]
Release won't make ground skills targeted. It only passes a position to ground skills, but the skill itself is still ground targeted. So I think neither should be reflected.
