### ISSUE TITLE
Lightning Walk x Magic skills

### ISSUE THREAD

**Issue by Felleonel** [rathena/rathena#5953]
* **rAthena Hash**: c44fdaf

* **Client Date**: 20200401

* **Server Mode**: RE

* **Description of Issue**: 
  * Result: Lightning Walk is working against magic skills.
  * Expected Result: Lightning Walk should only work against long ranged skills.
  * How to Reproduce: Just use the skill and receive some magic attack.
  * Official Information: https://divine-pride.net/database/skill/2335/salto-relampago
  
  
![image](https://user-images.githubusercontent.com/19696140/118899164-93ffc800-b8e4-11eb-9cd2-c307e5d6e638.png)

**Comment by feltenc** [comment]
I can confirm this report on https://github.com/rathena/rathena/commit/c44fdaf76e3c6acbb1b7048e17e0d5757799cbf4.

**Comment by MrAntares** [comment]
The link provided is not "official"
Here is the official:
https://ro.gnjoy.com/guide/runemidgarts/skillview.asp?skillid=2335

I can only google translate it, but it already anough to see that indeed only long range physical attack should trigger it:
![image](https://user-images.githubusercontent.com/5745362/120993715-1cef7e00-c784-11eb-8dc7-8febd6e6204b.png)
