### ISSUE TITLE
@time make server crash?

### ISSUE THREAD

**Issue by cahya1992** [rathena/rathena#5956]
* **rAthena Hash**: 

26632604f

* **Client Date**: 

20180919

* **Server Mode**: 
Pre renewal

* **Description of Issue**: https://pastebin.com/vY4iizCb << GDB REPORT
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Sounds like this is related to #4989?

**Comment by cahya1992** [comment]
> Sounds like this is related to #4989?

yeah maybe the crash still exist
