### ISSUE TITLE
npc keep refreshing after changing the look to player class

### ISSUE THREAD

**Issue by ragnarokmutate** [rathena/rathena#5957]
**rAthena Hash:** 202f37c2

**Client Date:** 20180620

**Server Mode:** Pre-Renewal

**Description of Issue:**
npc keep refreshing after changing the look to player class

this keeps on refreshing 
setnpcdisplay(strnpcinfo(3), "myname" ,4010);

while below is not 
setnpcdisplay(strnpcinfo(3), "myname" ,445);

**Result:**
`prontera,156,152,0	script	change_look_test	444,{
    end;
OnInit:
    .test = 2;
    if(.test == 1){
        setnpcdisplay(strnpcinfo(3), "myname" ,4010);
    }else{
        setunitdata(getnpcid(0,strnpcinfo(3)), UNPC_CLASS,4010);
    }
end;
}`

**Modifications that may affect results:**
None

**Comment by aleos89** [comment]
![image](https://user-images.githubusercontent.com/3521753/129365658-a9f5ff4d-dc7a-4be6-9cb8-05b9f241b077.png)
Looks like your script works for me. I'm using a 2020 client.
