### ISSUE TITLE
item problem 24005

### ISSUE THREAD

**Issue by hendra814** [rathena/rathena#596]
shadow item "24005" can't be equip by AB

**Comment by tmav94** [comment]
Are you sure? Here work's fine...use this code in your "import/item_db.txt"

24004,T_VIT1_Earrings_Shadow(R),T VIT1 Earrings Shadow(R),12,10,,0,,,,0,0xFFFFFFFF,63,2,1048576,,1,,,{ bonus bVit,1; },{},{}

**Comment by nanakiwurtz** [comment]
@hendra814 Can you please try to equip these items: 24011, 24020, 24125

**Comment by hendra814** [comment]
sorry i put wrong item code, it must 24011
the screen shoot
 http://s22.postimg.org/oqrjj3gqp/screen_APEL_RO001.jpg
http://s18.postimg.org/v2qm58295/screen_APEL_RO002.jpg

**Comment by nanakiwurtz** [comment]
@hendra814 Try to equip: 24017, 24020, 24023.

**Comment by hendra814** [comment]
@nanakiwurtz item 24017, 24020, 24023.can equip by my char (AB job)

**Comment by nanakiwurtz** [comment]
Minimum level to equip that item is 150, yours is only 147.

**Comment by hendra814** [comment]
ok, Thanks, i understand now.
