### ISSUE TITLE
Missing line marker on a warning

### ISSUE THREAD

**Issue by M45T3Ryu** [rathena/rathena#5979]
**Is your request related to a missing feature?**

Yes, I dont get heads up on where actually is this warning located

**Describe the solution you'd like**

Please add the warning line number on the "warning" so I can find them without searching through all my files

**Additional context**

![image](https://user-images.githubusercontent.com/2993425/120135108-62102080-c184-11eb-8d09-404bd64e6e5b.png)

**Comment by vstumpf** [comment]
I think this is a quick edit to use the warning macro, I'll test it out

**Comment by vstumpf** [comment]
Alternatively, you can grep for the deprecated constants, it does at least tell you which one is deprecated.

**Comment by M45T3Ryu** [comment]
> Alternatively, you can grep for the deprecated constants, it does at least tell you which one is deprecated.

yeah thats what I did I actually searched for E_GASP but the warning parses the emotion ID's too as a string.. since the emotion was set to:

emotion EMOTIONNUMBER;

And the warning told me that It was called "E_GASP" I was having problems finding it
