### ISSUE TITLE
Map Server Crash: Clone + AB_PRAEFATIO

### ISSUE THREAD

**Issue by AbuGosok** [rathena/rathena#599]
>	map-server.exe!skill_castend_nodamage_id(block_list * src, block_list * bl, unsigned short skill_id, unsigned short skill_lv, unsigned int tick, int flag) Line 8777	C
 	map-server.exe!skill_castend_id(int tid, unsigned int tick, int id, int data) Line 10775	C
 	map-server.exe!do_timer(unsigned int tick) Line 369	C
 	map-server.exe!main(int argc, char * * argv) Line 363	C

Died at this line:
>	case AB_PRAEFATIO:
 	 	if( sd == NULL || sd->status.party_id == 0 || flag&1 )
 	 	 	clif_skill_nodamage(bl, bl, skill_id, skill_lv, sc_start4(src, bl, type, 100, skill_lv, 0, 0, ( sd->status.party_id ? party_foreachsamemap(party_sub_count, sd, 0) : 1 ), skill_get_time(skill_id, skill_lv)));

Data view reveals that sd is null because it's a clone. To test, just @clone and @evilclone yourself as AB many times and when they fight each other they will randomly cast a skill. There are many other skill besides AB_PRAEFATIO that will also trigger map server crash.

**Comment by cydh** [comment]
should be
````
( sd && sd->status.party_id ? party_foreachsamemap(party_sub_count, sd, 0) : 1 )
````

> There are many other skill besides AB_PRAEFATIO that will also trigger map server crash.

help us to spot them, maybe? we got random old report 'clone makes server crash' with no hint.
