### ISSUE TITLE
Some Wrong Commit about roulette

### ISSUE THREAD

**Issue by dastgir** [rathena/rathena#600]
https://github.com/rathena/rathena/commit/53868d5850d0bde4394689f6e48420a1304f2b6a
The Packet 0xa01 isn't for roulette opening but for shortcut window rotations..
http://i.imgur.com/jH1hyWW.png (translations have that string from long ago)...

**Comment by icxbb-xx** [comment]
oh, i'am fail for this 
roulette  , rotate

thank you for report @_@
