### ISSUE TITLE
MVP should not reduce damage on green aura for pre-re

### ISSUE THREAD

**Issue by nicoaravena** [rathena/rathena#6007]
* **rAthena Hash**:  acbebc4

* **Client Date**: 20180621

* **Server Mode**: pre

* **Description of Issue**: Green aura of MVP should not affect damage on Pre renewal.
  * Result: Damage reduced when attacking MVPs.
  * Expected Result: Damage shoud go without reduction on MVP with green aura.
  * How to Reproduce: Some MVPs when respawn will have damage reduced. Tested on GTB and Morocc (last receive only 90k from Asura attack).
  * Official Information: Green aura damage reduction only exist since renewal.
  

* **Modifications that may affect results**:  Posible fix
```diff
diff --git a/src/map/battle.cpp b/src/map/battle.cpp
index 15ce0d154..fbd65eb64 100644
--- a/src/map/battle.cpp
+++ b/src/map/battle.cpp
@@ -1810,13 +1810,14 @@ int64 battle_calc_damage(struct block_list *src,struct block_list *bl,struct Dam
                        element = rnd()%ELE_ALL;
                pc_overheat(tsd, (element == ELE_FIRE ? 3 : 1));
        }
-
+#ifdef RENEWAL
        if (bl->type == BL_MOB) { // Reduces damage received for Green Aura MVP
                mob_data *md = BL_CAST(BL_MOB, bl);
 
                if (md && md->db->damagetaken != 100)
                        damage = i64max(damage * md->db->damagetaken / 100, 1);
        }
+#endif
 
        return damage;
 }
```

**Comment by Lemongrass3110** [comment]
The feature is not limited to the green aura. It is applied whenever you put the DamageTaken node into the mob database.
And by default the rAthena pre-renewal database does not have this node. So it has to be some custom change on your end.

**Comment by nicoaravena** [comment]
@Lemongrass3110  The problem is, **some** MVP respawns will reduce damage deal to them even if you don't configure DamageTaken and this is the only thing I found that touch this kind of behavior. And I say some, because is not on all MVPs respawn.

So if this kind of things is not the problem then as a possible solution doesn't help, but the problem exists.
