### ISSUE TITLE
Crush Strike and Exceed Break

### ISSUE THREAD

**Issue by Felleonel** [rathena/rathena#6008]
* **rAthena Hash**: acbebc4cd8cef940def083c21586a546adcbc24e

* **Client Date**: 20200401

* **Server Mode**: RE

* **Description of Issue**: 
  * Result: Crush Strike and Exceed Break does not working with bonus2 bSkillAtk and skill_damage_db file.
  * How to Reproduce: Just use a item with bonus2 bSkillAtk or modify skill_damage_db to increase both skills damage.

**Comment by feltenc** [comment]
I can confirm on https://github.com/rathena/rathena/commit/acbebc4cd8cef940def083c21586a546adcbc24e

**Comment by aleos89** [comment]
Please check out #3868.
