### ISSUE TITLE
2186 Encyclopedia_Revision missing MATK Bonus

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#6016]
* **rAthena Hash**: 
e8385d812ba327f1019d1f59987233684a6e378d

* **Client Date**: 
Not relevant

* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result: Item 2186 Encyclopedia_Revision is missing MATK +5 (without refinement) basic script bonus
  * Expected Result: Add `bonus bMatk,5;` as base bonus.
  * How to Reproduce: Compare rAthena item script with Divine-Pride info.
  * Official Information: https://www.divine-pride.net/database/item/2186

* **Modifications that may affect results**: 
None

**Comment by idk-whoami** [comment]
The matk is already written in the MagicAttack field

**Comment by Atemo** [comment]
Correct
```
  - Id: 2186
    AegisName: Encyclopedia_Revision
    Name: Great Encyclopedia Revision
    Type: Armor
    Buy: 10
    Weight: 200
    MagicAttack: 5
```

**Comment by Everade** [comment]
Didn't realise that's still a thing.
Made to miss.
