### ISSUE TITLE
1530 Mjolnir - Must be indestructible

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#6017]
* **rAthena Hash**: 
e8385d812ba327f1019d1f59987233684a6e378d

* **Client Date**: 
Not relevant

* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result: Item id 1530 Mjolnir is missing the indestructible
  * Expected Result: Add `bonus bUnbreakableWeapon;`
  * How to Reproduce: Check rAthena item script.
  * Official Information: 
     **파괴불가.**
     https://www.divine-pride.net/database/item/1530

* **Modifications that may affect results**: 
None

**Comment by secretdataz** [comment]
Mace type weapons are already unbreakable, no?

**Comment by Atemo** [comment]
You're right https://github.com/rathena/rathena/blob/e8385d812ba327f1019d1f59987233684a6e378d/src/map/skill.cpp#L2597
