### ISSUE TITLE
Guild Aura skills make Basilica fail

### ISSUE THREAD

**Issue by Indigo000** [rathena/rathena#6019]
* **rAthena Hash**: de9f667

* **Client Date**: 2018-06-21

* **Server Mode**: Pre-Renewal

* **Description of Issue**: A guild leader with guild auras active such as Wounds of Glory cannot ever use Basilica.
  * Result:  See above.
  * Expected Result: Can use Basilica with guild auras active.
  * How to Reproduce:  This only applies to the guild leader. Try to cast Basilica without any of the guild aura skills and it works fine. The moment you put a skill point in any of the aura skills, Basilica will always fail. It's caused by the `skill_count_wos` function. Likely related to commit 01b8e76e231381f67ae1015ffdc1065e662a2b71 where the check was changed from BL_MOB|BL_PC to BL_ALL making it fail on anything in the area, be it skills, items on the floor, etc.
  * Official Information:  None, but seems rather weird that guild leaders are unable to use Basilica.
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Since our old bug tracker is gone, I can't look up the exact reason why Akinari changed it to that. I'll go ahead and revert the behavior of the bl types.
