### ISSUE TITLE
maintenance mode

### ISSUE THREAD

**Issue by ernestfegarido** [rathena/rathena#602]
i change my server to maintenance mode. i noticed that all group id is bypassing the server type. im using latest rev and my client is 2014-10-22bRagexe. please check thank you :)

**Comment by nanakiwurtz** [comment]
Have you restarted your server?

**Comment by ernestfegarido** [comment]
@nanakiwurtz  yes sir! :)

**Comment by aleos89** [comment]
As the configuration states, there is no functional effect of "char_maintenance". It is just to display the message at the server select screen. If you want to disable players from logging in, then you have to change the "min_group_id_to_connect" in the login_athena.conf file.
