### ISSUE TITLE
(another) Lighthalzen Rekenber Quest bug + fix

### ISSUE THREAD

**Issue by KrokusPokus** [rathena/rathena#6020]
* **rAthena Hash**: e8385d812

* **Server Mode**: both

* **Description of Issue**: 
A character will get stuck (can't walk/do anything, need to relog) at 2 specific points during the Rekenber Job quest. At these points, the map-server will give a "npc_scriptcont: failed npc_checknear test." warning.

For this to occur, the character needs to have quest variable (lhz_rekenber == 12) or (lhz_rekenber == 18). After talking to "airplane_01,96,48,3	script	Man#Lyozien", a mob of 2 or 3 of mobID 1592 will spawn. After these are killed, a message box opens for the character. Closing the message box will leave the character stuck until relog.

This happens because the hidden NPCs "#bully1 and "#bully2" in "quests_lighthalzen.txt" are not defined to be floating but given a specific position in the corner of the map:

airplane_01,1,1,1	script	#bully1	HIDDEN_NPC,{...}
airplane_01,2,2,1	script	#bully2	HIDDEN_NPC,{...}

When the hidden NPCs open a message box to the character, a distance check is performed in npc_checknear() versus AREA_SIZE, which will necessarily fail since the character will be somewhere close to the NPC "airplane_01,96,48,3	script	Man#Lyozien" when this happens.

The proposed fix changes the two hidden NPCs to be floating, in which case no distance check will be performed by the server.

* **Fix diff**: 
```
diff --git "a/C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\TortoiseGit\\quests_lighthalzen-e8385d8.000.txt" "b/D:\\Coding\\Ragnarok\\GIT_rAthena\\npc\\quests\\quests_lighthalzen.txt"
index 303914609..e0f0590c0 100644
--- "a/C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\TortoiseGit\\quests_lighthalzen-e8385d8.000.txt"
+++ "b/D:\\Coding\\Ragnarok\\GIT_rAthena\\npc\\quests\\quests_lighthalzen.txt"
@@ -11762,7 +11762,7 @@ OnStop:
 	close;
 }
 
-airplane_01,1,1,1	script	#bully1	HIDDEN_NPC,{
+-	script	#bully1	HIDDEN_NPC,{
 
 OnInit:
 	disablenpc "#bully1";
@@ -11805,7 +11805,7 @@ OnTimer120000:
 	end;
 }
 
-airplane_01,2,2,1	script	#bully2	HIDDEN_NPC,{
+-	script	#bully2	HIDDEN_NPC,{
 
 OnInit:
 	disablenpc "#bully2";

```

**Comment by Atemo** [comment]
Thanks!
