### ISSUE TITLE
Support setting Enable cashshop preview by use ./configure  --enable-cashshop-preview=yes

### ISSUE THREAD

**Issue by cahya1992** [rathena/rathena#6033]
**Is your request related to a missing feature?**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Lemongrass3110** [comment]
I dont see any need to add every possible option as configure option.
Why do you think we need to have it? Or just because Hercules also has it.

**Comment by RagnaWay** [comment]
> I dont see any need to add every possible option as configure option.
> Why do you think we need to have it? Or just because Hercules also has it.

I totally agree, how difficult is it to go to the file https://github.com/rathena/rathena/blob/master/src/config/core.hpp#L85 and remove the // to enable?

**Comment by Lemongrass3110** [comment]
> 
> 
> > I dont see any need to add every possible option as configure option.
> > Why do you think we need to have it? Or just because Hercules also has it.
> 
> I totally agree, how difficult is it to go to the file https://github.com/rathena/rathena/blob/master/src/config/core.hpp#L85 and remove the // to enable?

@RagnaWay Basically best way is usually to use src/custom/defines_pre.hpp for this to prevent conflicts.
But yeah your way also works and this is what I am talking about. I do not see any benefit of adding 100 different configure options.

**Comment by cahya1992** [comment]
just make easier in first step i build server
if i can setting via ./configure I didn't need to change any file on src file
like we enable VIP, packetver its so easy if can setting in 1 Line via ./configure

**Comment by Lemongrass3110** [comment]
If this is the only thing you can do this via echo and >> in linux too.
