### ISSUE TITLE
Map Server Crashes after Adding Mob

### ISSUE THREAD

**Issue by Zarbony** [rathena/rathena#6035]
* **rAthena Hash**:  4bc3a2c51

 

* **Client Date**:  2020-06-03

* **Server Mode**:  Pre-renewal

* **Description of Issue**: 
  * Result:   After adding a Monster and put in an Item under Drops without -item and rate, the Server crashes upon loading this mob.
  * Expected Result:  Server shows Error and Skipping this Mob or the Drops from this Mob until the missing -item and Rate is adding.
  * How to Reproduce:  Add a new Mob, use an Item under Drop and forget to use -item and Rate and reloadmobdb, open up the log folder and there is the hint:  [ Error ] : Missing node "Item"., the Server Crashes immediately
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by Balferian** [comment]
The same crashes when you add wrong item in skill_db

**Comment by vstumpf** [comment]
Can you post examples of your yaml files?

**Comment by Zarbony** [comment]
> Can you post examples of your yaml files?

Just like that:

  - Id: 42000
    AegisName: Custom_Mob
    Name: Custom Mob
    HP: 12000
    Modes:
       CanMove: true
       CanAttack: true
       Looter: true
    Drops:
       apple

i missed to use - Item and Rate under Drops:
Like that: 
  - Id: 42000
    AegisName: Custom_Mob
    Name: Custom Mob
    HP: 12000
    Modes:
       CanMove: true
       CanAttack: true
       Looter: true
    Drops:
       - Item: apple
          Rate: 50

**Comment by Lemongrass3110** [comment]
Your hash is invalid and I am unable to reproduce the crash.
This is the import mob db that I used:
```
Header:
  Type: MOB_DB
  Version: 2

Body:
  - Id: 30000
    AegisName: Custom_Mob
    Name: Custom Mob
    HP: 12000
    Modes:
       CanMove: true
       CanAttack: true
       Looter: true
    Drops:
       apple
```
