### ISSUE TITLE
Meteor Storm Stack Limit

### ISSUE THREAD

**Issue by izecold** [rathena/rathena#6049]
* **rAthena Hash**:  7bb74f0fd

* **Client Date**: 2018-06-20

* **Server Mode**: Pre-Renewal

* **Description of Issue**: 
* Meteor Storm: It's only stacking 4 skills at the time. I made some test's and if i cast Meteor storm very fast in a short time they just cut the previously cast's.
* Example: If i cast 4 meteor storm it will be fine, they will stack and deal damage but if i cast the fifth meteor storm, the first cast get cut off. So when i spam it very fast.. the cast's start cutting each other and the skill not even deal any damage, players walk into the Meteor Storm without getting any damage.

**Comment by aleos89** [comment]
I think this is a duplicate of #2217.
