### ISSUE TITLE
when uploading mob_skill_db_re.sql

### ISSUE THREAD

**Issue by ernestfegarido** [rathena/rathena#605]
![tangina](https://cloud.githubusercontent.com/assets/4651777/9573831/3c25f36c-4ff3-11e5-9f82-0a1cb4298ba0.PNG)

**Comment by nanakiwurtz** [comment]
It works for me, maybe it comes from incomplete git pull.
Can you please do git pull and retry again?

**Comment by aleos89** [comment]
Worked fine for me using df35f33:
```/* 9,846 rows affected, 0 rows found. Duration for 9849 queries: 5.253 sec. */```

Make sure you don't have any typos and have a good pull of it.

**Comment by cydh** [comment]
common issue because of of your PHP execution is timed-out.
