### ISSUE TITLE
Missing Doram equipment drops

### ISSUE THREAD

**Issue by plsfixrito** [rathena/rathena#6050]
* **rAthena Hash**:  https://github.com/rathena/rathena/commit/7bb74f0fd4ba693950c3622aeeb04b54b7d4e77f

* **Client Date**: any

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Doram item drops are missing from mobs 
  * Expected Result: Doram item drops to drop for their mobs 
  * How to Reproduce: 
  * Official Information: 
   Marvelous Foxtail Staff https://divine-pride.net/database/item/1690
   Wondrous Foxtail Staff https://divine-pride.net/database/item/1691
   Magic Foxtail Staff https://divine-pride.net/database/item/1692
   Magic Yellow Foxtail Staff https://divine-pride.net/database/item/1693
   Foxtail Replica https://divine-pride.net/database/item/1694
   Fine Foxtail Replica https://divine-pride.net/database/item/1695
   Elaborate Foxtail Replica https://divine-pride.net/database/item/1696
   Elaborate Yellow Foxtail Replica https://divine-pride.net/database/item/1697
   Doram Suit https://divine-pride.net/database/item/15126
   Luxurious Doram Suit https://divine-pride.net/database/item/15129
   White Shirt https://divine-pride.net/database/item/15150
   White Eco Shirt https://divine-pride.net/database/item/15151
   Elegant Doram Suit https://divine-pride.net/database/item/15156
   Doram Manteau https://divine-pride.net/database/item/20788
   Luxurious Doram Manteau https://divine-pride.net/database/item/20789
   Elegant Doram Manteau https://divine-pride.net/database/item/20790
   Wooden Slippers https://divine-pride.net/database/item/22076
   Red Eco Boots https://divine-pride.net/database/item/22077
   Doram Shoes https://divine-pride.net/database/item/22083
   Luxurious Doram Shoes https://divine-pride.net/database/item/22084
   Elegant Doram Shoes https://divine-pride.net/database/item/22085
   Fresh Grass Necklace https://divine-pride.net/database/item/28380
   Cute Grass Necklace https://divine-pride.net/database/item/28381
   Charming Grass Necklace https://divine-pride.net/database/item/28382
    
  

* **Modifications that may affect results**:

**Comment by Atemo** [comment]
Fixed in https://github.com/rathena/rathena/commit/dea08407853d72b89c4599d618c687c47a15857f
