### ISSUE TITLE
Mob skill NPC:MAX PAIN not working propely.

### ISSUE THREAD

**Issue by mundussan** [rathena/rathena#6057]
* **rAthena Hash**: 

7bb74f0fd4ba693950c3622aeeb04b54b7d4e77f

* **Client Date**: 
2021-01-07

* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result: 
  * Negate magic source damage (not tested with physical damage).
  * Expected Result: 
 
  * Reflect all kind of damage in the screen, at wide range.
  * How to Reproduce: 
  * Spawn a V_EREMES (the mob which occured the issue) and use a magic type skill (in the issue was used Reverberation)
  
![screenrAthena069](https://user-images.githubusercontent.com/33139683/123502551-aed00580-d623-11eb-8b5f-d85af66dce88.jpg)
![screenrAthena070](https://user-images.githubusercontent.com/33139683/123502589-f8b8eb80-d623-11eb-990e-efcf1c77e847.jpg)

  * Official Information: 
  
Don't have any.

* **Modifications that may affect results**: 
  
  
None.

**Comment by Lemongrass3110** [comment]
Is this a duplicate of #5684?

**Comment by mundussan** [comment]
> Is this a duplicate of #5684?

oh... I think so... I didnt found anything about it when I searched first time... Thanks anyways.

**Comment by eppc0330** [comment]
Check #5820.
