### ISSUE TITLE
Missing packet of enchantgrade 

### ISSUE THREAD

**Issue by idk-whoami** [rathena/rathena#6059]
* **rAthena Hash**: a3d19ae2c30d981dc580dca26028ee4bfc83e4c7

* **Client Date**: 2020-08-19aRagexeRE

* **Server Mode**: re

* **Description of Issue**: 

**Missing class icon enchantgrade when equipped top headgear, mid headgear, costume top headgear and costume  mid headgear position.**

https://user-images.githubusercontent.com/60462533/123523061-8d3a5100-d6eb-11eb-89f8-151f9c66c8d9.mp4

  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment]
This is a clientside bug. Headgears do not seem to show enchantgrade in this special case.

**Comment by idk-whoami** [comment]
Thanks

**Comment by Qubeks** [comment]
Hello sorry if I'm in the wrong section but I can't get a definite answer in the forums. How did you set it to accept low-level items like hoods, shoes, and weapons? I tried editing Level 5 for the weapon Level for the armor on enchantgrade.yml but it still not accepting other items. Thanks
