### ISSUE TITLE
Homunculus After Cast Delay and Cooldown Issue

### ISSUE THREAD

**Issue by reigneil** [rathena/rathena#606]
i think cooldown was first introduce in RO for homunculus skill to prevent skill spamming. correct me if im wrong...
the issue here is after cast delay should be cooldown for homunculus skill. i.e Amistr Bulwark, BloodLust etc.
http://irowiki.org/wiki/Homunculus_System

this is based on what i recall... can anyone confirm this issue?

**Comment by RagnarokNova** [comment]
Super hard to understand what you're trying to say, but thankfully I encountered the same issue!

Currently the biggest issue is that Homunculus Cooldowns/Aftercast Delays are being reset on relog in rAthena.
I tested this today in iRO, and Homunculus Skill cooldowns persist through logging in and out.

**Comment by cydh** [comment]
How about mercenary?
Interested to fix this

**Comment by Playtester** [comment]
When Homunculus were implemented, their delays reset in many different situations like teleporting and respawning. Maybe they fixed it eventually. But in pre-renewal servers I usually see the opposite complaints. That delays should reset but don't.
