### ISSUE TITLE
@cash and @points command bug

### ISSUE THREAD

**Issue by ijped27** [rathena/rathena#6060]
* **rAthena Hash**: Latest Git
* **Client Date**: 20151104 / 20180621
* **Server Mode**: Pre-renewal
* **Description of Issue**: after using @cash or @points 
  * Result:my character stack up and cant use any command and even i kill or restart the server or reboot the vps the client still not receiving Disconnected notice. 
  * Expected Result:  it should be indicated cashpoints or kafranpoints you generated in the character
  * How to Reproduce:
  * Official Information: ``` `@cash` `@points` ```
  

* **Modifications that may affect results**: no modification only changing the server mode
[https://pastebin.com/raw/Ldafu3sR](https://pastebin.com/raw/Ldafu3sR) dnt know if i supply gdb logs correctly

**Comment by ijped27** [comment]
Hope someone will check this using latest git centos 7 gcc 7

**Comment by Gardosen** [comment]
i think there needs to be a more detailed explenation from @ijped27 about what exactly is happening for him on the client.

i have tested the commands with a 20210107RE client and the latest rathena, and i face no issues. the server is running inside an ubuntu 21.04 docker instance.
what he describes is not reproducable for me.

**Comment by ijped27** [comment]
@Gardosen im running it on centos 7 with gcc 7 
i did try clean install the server clean client clean Server files
when i use on clean install server and run the server within 2days after i restart the vps and start the server then using 99 gmlvl
the Server will crash the character will stack and cant command then i try to login another account it will stuck at map Server when i try to shut off the server it will spam map-server kill process

**Comment by gidzdlcrz** [comment]
Ive been reading this lately on rA's discord server. Well i am unable to reproduce it as well. Using fresh git pull from rathena and 2020 client. Also tried with the client you are using. Howerver i cant test it on centos 7 with gcc 7. No VPS at the moment.

**Comment by ijped27** [comment]
Still no one can check the error im using now latest git and 20210107 client pre-re still getting this bug

**Comment by aleos89** [comment]
Same as #5885. Sounds like you didn't properly import your log tables or are directing it to the wrong schema.
