### ISSUE TITLE
Card Drop Rate isnt Increased

### ISSUE THREAD

**Issue by Zarbony** [rathena/rathena#6062]
* **rAthena Hash**:  4bca2c51

* **Client Date**: 2021-04-01

* **Server Mode**:  Pre- Renewal

* **Description of Issue**: The Drop Rate for the Cards wont go any Higher if you increase the Rate for it.
  * Result:  If you Higher the Drop Rate for Cards, the Card will stop at 1%. if you push the min value then the drop rate will go higher.
  * Expected Result:  Adjustable Card Drop rate like the other ones
  * How to Reproduce:  Open up the drop.conf in conf/battle/ then adjust the card drop rate and check the Ingame rate with the new Adjustet Rate.
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
![image](https://user-images.githubusercontent.com/3521753/129566822-3626cf70-94b8-4688-b29f-e82578245174.png)
I'm unable to reproduce. Tested on the current master (b119c04).
