### ISSUE TITLE
Global Temporary Variables

### ISSUE THREAD

**Issue by nanakiwurtz** [rathena/rathena#607]
Hi, on current rAthena script command, there are several commands which returns it's value into global temporary variable, those commands are: getpartymember + getguildmember + getmobdrops + warpwaitingpc + party_create (and maybe there're more).

Why it's being saved as global? We will need to use 'copyarray' before we can use another commands, because the value will be overwritten.

**Comment by cydh** [comment]
the options are,
[  ] force the returned array as `.@`
[  ] add the 3rd param for returned array variable. eg `getpartymember 1,0,.@PartyMemberNameWillBeHere$;`

**Comment by nanakiwurtz** [comment]
I prefer the second option, so user can specify their own variable name, but don't know with everyone else?

**Comment by aleos89** [comment]
I think the second option works nicely. If we change the variable now it breaks legacy stuff. Do we care about legacy for script command usage like this?

**Comment by cydh** [comment]
hmm, pull request or direct push.. well, direct push. xD
