### ISSUE TITLE
Sharp Shooting Bug

### ISSUE THREAD

**Issue by f4kiez** [rathena/rathena#6072]
* **rAthena Hash**: 0828ff00c

* **Client Date**: 
20180919

* **Server Mode**: 
Pre-RE

* **Description of Issue**: 
* my skill.conf : 
skill_eightpath_algorithm: yes
skill_eightpath_same_cell: yes
from this vid > https://www.youtube.com/watch?v=JtYh_kpTtc0
when i step on high priest 1cell from lord knight then i try to sharp shooting on high priest and stepback til my distance between lordknight and sniper is 6 cells
case 1: 
![problem1](https://user-images.githubusercontent.com/79768199/124368556-60a6ac00-dc8c-11eb-85fe-967278c6da97.png)

case 2:
![problem2](https://user-images.githubusercontent.com/79768199/124368560-6dc39b00-dc8c-11eb-88f6-f3f5a0ec29be.png)

This bug will begin see at vid : https://youtu.be/JtYh_kpTtc0?t=32
now sniper no animation for use skill and i use sharpshooting to high priest but dmg just deal on lord knight not at high priest also.

This problem should be give an animation on sniper(now nodelay is active) and deal dmg to high priest not lord knight.

edit* change focus arrow to sharp shooting

**Comment by aleos89** [comment]
@Playtester shows the exact pathing for Sharp Shooting [here](https://github.com/rathena/rathena/issues/658#issuecomment-177505424). Based on your video and images it looks right.
