### ISSUE TITLE
Missing bonus increases SP recovered by % rates

### ISSUE THREAD

**Issue by idk-whoami** [rathena/rathena#6076]
* **rAthena Hash**: 110c0a623ece326a0a584338333d989bda709729

* **Client Date**: 20200401

* **Server Mode**: re

* **Description of Issue**: 

https://www.divine-pride.net/database/item/18684

`bonus2 bAddItemHealRate,505,50;`

item IDs 505 restores 50% more SP not working

  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment]
You mean the "Blue_Potion restores 50% more SP"?
This is often bugged on divine-pride. Maybe @dia can comment on this.

**Comment by idk-whoami** [comment]
This combo [Magicstone_Of_Grace](https://www.divine-pride.net/database/item/19106) and [Mistress_Card](https://www.divine-pride.net/database/item/4132) too.

**Comment by Lemongrass3110** [comment]
The other two examples you gave are wrong.
The increase required SP for skills and this is already implemented via bUseSPrate.
Do you have an example that really has a bonus like this?

**Comment by idk-whoami** [comment]
I don't really have a sample with bonus. I used data from divine-pride description.

For [Showy_High_Cap ](https://www.divine-pride.net/database/item/18684) I think this is bugged by divine-pride.

But [Magicstone_Of_Grace](https://www.divine-pride.net/database/item/19106) and [Mistress_Card](https://www.divine-pride.net/database/item/4132) combo has a divine-pride description. Select a description from the kRo server, but display a description from the jRo server.

I'm sorry if ignored the description from the jRo server.
