### ISSUE TITLE
max_walk_path

### ISSUE THREAD

**Issue by MrAntares** [rathena/rathena#608]
The max_walk_path value set in import/battle.conf is not used since a few weeks.. No matter what I set it uses always 17(default).

**Comment by Playtester** [comment]
{ "max_walk_path",                      &battle_config.max_walk_path,                   17,     1,      MAX_WALKPATH,   },

Hmm can't find an error? MAX_WALKPATH is 32 it seems so you could be able to set anything between 1 and 32, 17 is only the default when it's not set. Wrong configuration name? Not reading from conf file?

	if ((wpd.path_len > battle_config.max_walk_path) && (bl->type != BL_NPC))
		return 0;

Seems to be used in unit.c too.

**Comment by MrAntares** [comment]
Well, I have a file in conf/import named battle_conf.txt. In the txt:
max_walk_path: 50
Yet the max path is still 17. 

I even tried to set in conf/battle/client.conf
max_walk_path: 50
Still the max is 17.

Maybe I'm doing something wrong?

**Comment by Desground** [comment]
"max_walk_path" change in  rathena/src/map/battle.c
in battle_conf.txt don't work.

**Comment by Lemongrass3110** [comment]
I think the problem could be that you set it to 50. 50 is higher than the defined MAX_WALK_PATH 32 and then the default value is used.

**Comment by MrAntares** [comment]
And how do I change MAX_WALK_PATH 32?

I'm fed up with the unresponsive movement... What I want is where I click I go there, unless it's a half way around the map route to get there. 

Thank you :)

**Comment by Lemongrass3110** [comment]
I think you should just set it to 32 because I think that this is the client side limit.

**Comment by piotrhalaczkiewicz** [comment]
I can confirm there is a client-side limit on how far away you can click to walk. It is possible to patch this out, but you need to ask someone good at hex-editing to tell you how exactly.

**Comment by Playtester** [comment]
I'm not sure if you can actually patch it properly because it's also a memory issue when calculating the walkpath. A longer, very complex walkpath might actually crash the client because of out of memory error.
