### ISSUE TITLE
Attacking a specific monster will cause map server error.

### ISSUE THREAD

**Issue by Jefferycheng** [rathena/rathena#6082]
* **rAthena Hash**: 
43fd6043c

* **Client Date**: 

2021-01-07 , 2019-06-05
* **Server Mode**: 

Renewal
* **Description of Issue**: 
 
I generate monster id 1951 with GM command `@monster 1951`.

When I attacked the monster, I will get an error log in the map server.

`
WFIFOSET: Maximum write buffer size for client connection 3 exceeded, most likely caused by packet 0x08c8 (len=34, ip=127.0.0.1).
`

And the character will lose the connection.

**Comment by Gardosen** [comment]
i do not think this has something todo with the monster. i tested this and the only thing which is weird on this monster same as on others of this kind, is the fact that you can not do anything anymore, as soon as it attacks you because of its 999dex attack speed.

the issue you get which causes the disconnect must come from something else

**Comment by mundussan** [comment]
I had the same issue, I just set the attack speed of this monster and all of this kind of mob to the same of a Poring (ID 1002).

**Comment by Jefferycheng** [comment]
@Gardosen Thanks for your test result.

I tested more cases and found it is unrelated to its dex 999.

The problem is the AttackDelay property of the monster is not be set in mob_db.yml.

So the default AttakDelay is zero...

Indicate the attack speed of the monster is infinite.

**Comment by Gardosen** [comment]
i never said it might be related to the dex999, this was just an example but yeah i agree, the missing AttackDelay might be a serious issue.

this should probably be added and at least set to a specific default value whch is similiar to 193aspd?

**Comment by Jefferycheng** [comment]
I think the solution is to add a condition judgment in the code.

If there is assigned a default value in mod_db.yml, that is just a workaround.

**Comment by Lemongrass3110** [comment]
The solution will be blaming how it was before .yml and if we accidently removed something during conversion, we can add it back.
But I rather think it should be slow by default and not insanely fast.
I was able to reproduce your issue btw. Although my server did not crash, but that monster instant killed me.
