### ISSUE TITLE
I want to confirm something please.

### ISSUE THREAD

**Issue by AskingForProofs** [rathena/rathena#6084]
What are the skills that can be blocked by Goldenthief Bug Card?
I'm on a private server that is asking for some proof of the skills that can be blocked by GTB and I can't find a reliable list on the internet about this. I would like this to be answered by someone reliable or maybe from the developers themselves, so I won't be debunked in our private server's forums.

Thank you so much.

**Comment by secretdataz** [comment]
Please ask this kind of question on the forums.

**Comment by AskingForProofs** [comment]
> Please ask this kind of question on the forums.

I'm sorry but I'm really new here. I just created this account for this purpose. Would you be so kind to link me the forums of rAthena?
