### ISSUE TITLE
Drop rate "Ghost Chill" id : 6471

### ISSUE THREAD

**Issue by killerdark16** [rathena/rathena#6087]
i want ask related update monster mob db drop #6074

after this update drop rate "Ghost Chill" id : 6471 only 0.01% from monster "Chen" id : 2224 (Monster from Bio Lab Level 4)
thats drop rate same like card

how it possible for user to making quest headger Ancient Gold Deco ? it cost 400pcs Ghost Chill X-X
and how it possible for user to "play" enchant weapon bio lab gear ( cost 10 Ghost Chill for reset 1 slot )

please check ,
and if this drop rate is true, please changes terms of bio lab gear

thanks a lot :)

**Comment by Atemo** [comment]
(Unfortunately) the drop rate seems correct.
We don't have the data to update the nightmare biolab enchant, but you can edit the file as you wish.
