### ISSUE TITLE
Corruption Root Card wrong effect

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#6096]
* **rAthena Hash**: 
4b339f7f6ebb01d50c7b956a8146551ad379b468

* **Client Date**: 
Not relevant

* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result: 
  Corruption Root Card current effect uses BF_WEAPON, although the item description clearly states that its effect only applies to short-ranged physical attacks.

  * Expected Result:
  BF_WEAPON should be changed to BF_SHORT on all 3 skill triggers.
  
  * How to Reproduce: 
  Check item db and compare to official item description/effect.

  * Official Information: 
  https://www.divine-pride.net/database/item/4603
  근접 물리 공격 시, 높은 확률로 시전자 주변 5*5셀 내 모든 적에게 석화, 수면, 저주를 건다.

* **Modifications that may affect results**: 
  None

**Comment by idk-whoami** [comment]
Can I include the fix in #6094?

**Comment by Atemo** [comment]
You can ;)

**Comment by Everade** [comment]
> Can I include the fix in #6094?

Always.
Means i don't have to open a pull later :D

**Comment by Atemo** [comment]
Actually aegis is using `SetAutoSpell2`
```
item  CorruptionRoot_Card
	event OnStartEquip:
		AddExtParam User VAR_ATTPOWER 20		
		SetAutoSpell2 User NPC_WIDESTONE 1 50		
		SetAutoSpell2 User NPC_WIDECURSE 1 50		
		SetAutoSpell2 User NPC_WIDESLEEP 1 50		
	return
```
Unless our aegis script is outdated the bonus should actually use BF_WEAPON, otherwise it's a typo in the KRO decription

**Comment by Everade** [comment]
Aren't all available Aegis leaks oudated in the first place?

Otherwise that would be a very long-standing kro typo.
