### ISSUE TITLE
Impositio Manus

### ISSUE THREAD

**Issue by Atemo** [rathena/rathena#610]
http://irowiki.org/wiki/Impositio_Manus
> Lower levels of Impositio Manus will overwrite higher levels. For example, someone with level 5 IM activated will have +25 ATK from the skill, but if level 1 IM were used on them their ATK would drop to only +5. Therefore, this skill can be used offensively.

Confirmed on aegis.

**Comment by cydh** [comment]
then our skill target is wrong too. currently is set as `friend`, so it must be `enemy + self + friend`
