### ISSUE TITLE
Read a lot for a long time(map-server.exe)

### ISSUE THREAD

**Issue by xvn5002036** [rathena/rathena#6107]
Open map-server.exe after compilation, it takes a long time to read
Hope there is a quick way to read

**Comment by Gardosen** [comment]
beside the fact that this is nothing which should be posted here, 
how fast the emulator reads the content depends heavily on your system.
if your system sucks, it takes obviously long.

my server needs 15-20 seconds to spawn the map server which is not much for the amount of data which has to be read.

**Comment by aleos89** [comment]
You can compile in release mode for faster parse times. We are currently in testing for increasing the YAML parse times already.
