### ISSUE TITLE
B.S Sacramenti

### ISSUE THREAD

**Issue by Atemo** [rathena/rathena#611]
~~http://irowiki.org/wiki/B.S_Sacramenti~~

> ~~Unequipping armor doesn't cancel this skill, so elemental armor is rendered useless when under the skill's effects.~~

Others notes (tested on aegis) : 
- B.S Sacramenti ends when the affected player logs out.
- B.S Sacramenti fails (and deal damage on pvp map) on people with undead elemental armor.

**Comment by aleos89** [comment]
So the two issues are the bullet points you listed?

**Comment by Atemo** [comment]
Yes I made a mistake about the unequip part. The issue are in the list.

**Comment by Playtester** [comment]
The actual question should be "Did you list what's wrong or how it should be?"

**Comment by Atemo** [comment]
- B.S Sacramenti **should** ends when the affected player logs out **(currently not the case)**.
- B.S Sacramenti **should** fails (and deal damage on pvp map) on people with undead elemental armor **(currently not the case)**.
