### ISSUE TITLE
Re-open an unfixed issue.

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#6112]
* **rAthena Hash**: 
4b339f7f6ebb01d50c7b956a8146551ad379b468

* **Client Date**: 
not relevant

* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result: 
https://github.com/rathena/rathena/issues/203
This is still a thing and has never been fixed. At least not that i'm aware of.

  * Expected Result:
Re-open the old issue.

  * Official Information: 
  Not related to Aegis.

* **Modifications that may affect results**: 
  None

**Comment by Lemongrass3110** [comment]
Mind explaining how you think this should be fixed?

The file is still loaded, so if the full file will be loaded again you will run into issues (duplicates etc.).
You only bypass this check by adding more path separators, but the problems that come with it are still there.

**Comment by Everade** [comment]
**Practical Example:**
Let's say, you're fixing a script issue or update a certain script/npc.
1.) Use @unloadnpc "npc_name" to unload the old version of a NPC.
2.) Use @loadnpc npc/script.txt

Now, for whatever reason, you need to unload and load this script again. (You made a mistake, or you've made another update, whatever)
3.) Use @unloadnpc "npc_name" to unload the old version of a NPC.
4.) Use @loadnpc npc/script.txt  **(Doesn't work)**

Why would you prevent that?

@loadnpc is an **admin** command, here for **devs** to make changes on a live/test environment.
I see absolute no reason, why you would want to prevent that.

It's the responsibility of the user, to make sure that you're not loading in duplicates.

rAthena, even triggers debug messages if there's ever the case that you've loaded the same NPC name twice, and will create a random name to prevent issues.

It was always possible back in eAthena times. And i also remember that this never was an issue in rAthena either.
But suddenly this popped up, and i figured it's obviously a bug. But i'm getting vibes that this was implemented by purpose.

**Comment by Lemongrass3110** [comment]
Such a wall of text but not explanation how you want it to be solved.

I understand that you want it to be fixed, but the question is how...? ;-)

**Comment by Everade** [comment]
**Do not prevent reloading**, under any circumstance. ^^

**Comment by yumiharuka21** [comment]
have you tried @reloadnpcfile?

**Comment by Everade** [comment]
When i'm trying to unload the entire content of the script, sure.
Although that's a very rare scenario.

I'm talking about:
Loading in new content, or replacing 1 single NPC.
(preloaded empty script files for loading in new content on the fly)

The baby-sitter mode will try to prevent it.
It's simply annoying, nothing more, nothing less.

**Comment by lukasrmattos** [comment]
Babysitters are important in open-source projects with a non-developer audience.

If you're in a controlled dev environment, wouldn't it just take all the default npcs out of the emulator and use @reloadscript while developing?

**Comment by Lemongrass3110** [comment]
> 
> 
> When i'm trying to unload the entire content of the script, sure.
> Although that's a very rare scenario.
> 
> I'm talking about:
> Loading in new content, or replacing 1 single NPC.
> (preloaded empty script files for loading in new content on the fly)
> 
> The baby-sitter mode will try to prevent it.
> It's simply annoying, nothing more, nothing less.

@Everade 
I think your solution with an "empty" script is pretty useless since you can always load a new file during runtime if it is needed.

A solution that I could imagine or think it would be useful for everyone - not only for your specific use case:
If the same file gets loaded again all NPCs that are still loaded get unloaded first and then the file gets loaded.

**Comment by Everade** [comment]
I'll fix this command breaking feature myself.

Thanks.
