### ISSUE TITLE
Certain skills trigger a warning GvG maps.

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#6114]
* **rAthena Hash**: 
4b339f7f6ebb01d50c7b956a8146551ad379b468

* **Client Date**: 
not relevant

* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result: 
Using certain skills on WoE maps trigger the following warning, despite their existance.
They're not listed on the skill_nocast_db either.
```
[Warning]: skill_castend_nodamage_id:  Unknown skill used:488
[Warning]: skill_castend_nodamage_id:  Unknown skill used:339
```

  * Expected Result:
Do not trigger a warning claiming that the skill is unknown, if it actualy exists in the skill database.

  * Official Information: 
  Unrelated to official.

* **Modifications that may affect results**: 
  None

**Comment by Lemongrass3110** [comment]
```
  - Id: 339
    Name: NPC_GRANDDARKNESS
    Description: Grand cross of Darkness
  - Id: 488
    Name: CG_HERMODE
    Description: Wand of Hermode
```
