### ISSUE TITLE
The loading speed of yaml is much slower than that of txt, how can we improve it?

### ISSUE THREAD

**Issue by voyfmyuh** [rathena/rathena#6125]
The loading speed of yaml is much slower than that of txt, how can we improve it?

**Comment by pigati23** [comment]
https://github.com/rathena/rathena/pull/5997

**Comment by aleos89** [comment]
When compiling on Windows, build it in Release mode vs Debug mode for now if you want. We are currently migrating from yaml-cpp to ryaml as @pigati23 linked.
