### ISSUE TITLE
Filir S.B.R.44 - cannot cast?

### ISSUE THREAD

**Issue by raynra** [rathena/rathena#613]
Perhaps I'm doing something obviously wrong, but it appears as if Filir's S.B.R.44 skill cannot be cast?
Tested on rAthena test server, latest GIT, max hom level, max intimacy.

**Comment by cydh** [comment]
just tested. it casted. just... missed. @_@ because of number of hit is 0. --a
> 8012,1,6,1,0,0,0,3,**0**,no,0,0,0,none,0,0x0,		HFLI_SBR44,S.B.R.44
