### ISSUE TITLE
Accessories (L)/(R) do not work!

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#6134]
* **rAthena Hash**: 
4b339f7f6ebb01d50c7b956a8146551ad379b468

* **Client Date**: 
Not relevant

* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result: 
  Card should increase my Physical DMG vs Neutral by 20%
  Accessories should increase my ATK by +3%
  These item scripts are fine, however the actual damage bonuses are never applied.
Card effect:
`bonus2 bAddEle,Ele_Neutral,20;`
Gear effect:
```
      if (readparam(bStr) > 89)
         bonus2 bAddClass,Class_All,3;
```
**Without Gear** 441-617DMG:
![image](https://user-images.githubusercontent.com/12261601/126866769-1eab8dee-3a5e-4353-8565-4de4e2d50874.png)

**With Gear** 441-617DMG:
![image](https://user-images.githubusercontent.com/12261601/126866757-f299b57b-dbd5-433d-befd-700c64c5d48a.png)

  * Expected Result:
  Accessories (L) and Accessories (R) shall apply all their bonuses and stats as expected.
  
  * How to Reproduce: 
  Test (L) or (R) exclusive Accessories.
  I've been testing with:
  28495
  28496
  27107

  * Official Information: 
  Not required

* **Modifications that may affect results**: 
  None

**Comment by Atemo** [comment]
`AddClass` / `AddEle` are applied on `right_weapon / left_weapon / arrow`.
https://github.com/rathena/rathena/blob/3115a1d39ce16428b74cef681089fb39a6bcfada/src/map/pc.cpp#L3805
 Did you test with a weapon equipped ?

**Comment by Everade** [comment]
So not even the ATK+3% is applied without a weapon?
In that case, this report is invalid.

Thanks for the info.
