### ISSUE TITLE
Battleground KVM do not start

### ISSUE THREAD

**Issue by raynra** [rathena/rathena#614]
The waiting rooms are:
waitingroom "Battle Station 5 Players",6,"KvM01_BG::OnGuillaumeJoin",1;
waitingroom "Battle Station 5 Players",6,"KvM01_BG::OnCroixJoin",1;

However, OnGuillaumeJoin and OnCroixJoin are in
-       script  KvM01_BG_Out    -1,{

Moving them to  
-       script  KvM01_BG        -1,{

resolves the issue.

**Comment by Atemo** [comment]
My mistake sorry :<
