### ISSUE TITLE
yaml2sql extended

### ISSUE THREAD

**Issue by ecdarreola** [rathena/rathena#6140]
**Is your request related to a missing feature?** No

**Describe the solution you'd like**: Accept other .yml file as long as it is defined in the db/re/mob_db.yml or db/re/item_db.yml

**Describe alternatives you've considered**: None

**Additional context**: 

Currently costumes are included in the item_db_equip.yml.
But for some pretty format or being OC, I use item_db_costume and define all costume there and other items such as item_db_suffix so in the long run it will be like below...

item_db_usable.yml
item_db_etc.yml
item_db_equip.yml
item_db_costume.yml
item_db_shadow.yml

**Comment by Lemongrass3110** [comment]
You can do in your import file if you like to.
For the files provided by us we decided to mimic the inventory tabs for the time being so that the files are not too big and that there are not too many files. The logic should be easy to understand for the users as well.
