### ISSUE TITLE
Tool csv2yaml dont convert item_package.txt

### ISSUE THREAD

**Issue by tungbach1990** [rathena/rathena#6142]
* **rAthena Hash**: 6f4fc83

* **Client Date**: 

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: 
  * Expected Result: 
  * How to Reproduce: Build csv2yaml tool dont convert item_package.txt, just read
  * 
![image](https://user-images.githubusercontent.com/31162328/127079737-7d048d0e-99f1-4aa1-ab5f-54c65998c776.png)

  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by Atemo** [comment]
It has been done like that for now. Some files are just read, it requires item_group_db.txt to start the conversion
