### ISSUE TITLE
Sorcerer's Elemental Control / Spirit Control: Passive Mode not working

### ISSUE THREAD

**Issue by micosanityyy** [rathena/rathena#6144]
Mode: Renewal

Skill: Sorcerer's Elemental Control / Spirit Control

Issue: Passive Mode buffs for players doesn't work

How to Reproduce: Use any Level 1-3 Spirit and use Level 1 Elemental Control, buffs should apply to players example Level 3 Summon Tera and Use Level 1 Elemental Control for Upheaval (+15% HP) but hp bonus not working

**Comment by Everade** [comment]
I've had players reporting this too, but when i switched through the modes several times, bonuses applied eventualy.
Not sure if there's an issue with the initial mode swapping though.

Would be great to have an expert on this.
I figured i was just too stupid changing the modes properly.
