### ISSUE TITLE
CSV2YAML doesn't convert all item_trade entries.

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#6145]
* **rAthena Hash**: 
efd66000f616b40abd4bdc6b73ca4ac580ca9696

* **Client Date**: 
Not relevant

* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result: After a successful conversion, many of my custom import/item_trade.txt restrictions have not been converted. **Specificaly those entries, which do not have an additional custom item_db.txt entry.**
  
  * Expected Result:
    Convert all
    
  * How to Reproduce:
  1. Set a custom item restriction for an _official item_, for example:
     `7769,499,100	//Egg Yolk`
  2. Run CSV2YAML conversion
  3. It has not generated an item_db.yml entry for this restriction.
     As such your custom restriction got lost in the process.

  * Official Information: 
Not relevant

* **Modifications that may affect results**: 
Various import/item_trade.txt entries.

**Comment by mazvi** [comment]
See this https://github.com/rathena/rathena/issues/5658
