### ISSUE TITLE
ETC tab of skill tree keeps skills and are usable

### ISSUE THREAD

**Issue by Brizyous** [rathena/rathena#6148]
* **rAthena Hash**:  d33ea18

* **Client Date**:  2020-05-06aRagexe

* **Server Mode**: Renewal

* **Description of Issue**: 
1- Skills keep acumulating at etc tab of skill tree whenever i change jobs using @job, relogging does not fix it. 
2- Skills enabled by items get greyed out when unequipping, fixed at relogging.
  * Result: skills from other job stuck and usable at etc tab
  * Expected Result: skills of previous job dissapear when changing jobs
  * How to Reproduce: use @job 
  * Official Information: 
  

* **Modifications that may affect results**: I used this modification https://github.com/rathena/rathena/pull/5178/commits/351f0db1914532924cdf678010c6aa3b209ca311
  
  
![screenrAthena011](https://user-images.githubusercontent.com/48534857/127431380-01e8b0d8-9e3c-4bca-997e-28b239e5aa4f.jpg)

**Comment by aleos89** [comment]
I would assume your situation is a mix of #5382 along with GM level settings (all skills, no pre-reqs, etc).

**Comment by Brizyous** [comment]
> I would assume your situation is a mix of #5382 along with GM level settings (all skills, no pre-reqs, etc).

Thanks, fixed with https://github.com/rathena/rathena/commit/c3f1ff91d95962766ee036b1f039b19ae26540ff.
