### ISSUE TITLE
Can't create name alphabet ญ in thai language

### ISSUE THREAD

**Issue by zdurexz** [rathena/rathena#6157]
* **Client Date**: 20180620

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Can't create name alphabet ญ on thai language
  * Expected Result: i want create name alphabet ญ on thai language
 
* **Modifications that may affect results**: 
  
  
Test:
![image](https://user-images.githubusercontent.com/59825922/128343428-5d70f8b4-ac59-409d-bac4-0eb683e74af2.png)
Result : 
![image](https://user-images.githubusercontent.com/59825922/128343477-31b05e93-f41d-41c7-b712-2d3101903f92.png)

**Comment by Lemongrass3110** [comment]
conf/char_athena.conf::char_name_letters

**Comment by zdurexz** [comment]
> conf/char_athena.conf::char_name_letters

Yes , I already did that, but it didn't.

![image](https://user-images.githubusercontent.com/59825922/128730624-9c022ff2-7a3e-409a-8a90-e1a81ef728b1.png)
