### ISSUE TITLE
gx poisons are not your damage

### ISSUE THREAD

**Issue by MrAntares** [rathena/rathena#616]
GX poisons that do damage are not considered your damage, and you don't get exp for it, but you should get exp after any status dealt damage. Refer to the ages old report:
https://rathena.org/board/tracker/issue-1551-coma-not-considered-as-your-dmg/

**Comment by MrAntares** [comment]
I have just tested, and the same happens with the once already fixed poison, coma, bleeding, deadly poison statuses, and presumably all other damaging statuses... Now they reduce the exp you can get from the mob, but this was already confirmed to be wrong on officials and got a fix 3 years ago. T.T

**Comment by aleos89** [comment]
Linking to previous fixes in: c48133c and d8d5489.

**Comment by aleos89** [comment]
So for GX Poisons, this would include: Leech End, Venom Bleed (Does max HP decrease count as damage?), Magic Mushroom, and Toxin.

Are these correct? Are there other statuses that should be doing this? Bleeding? Burning? Crystallization? Heat? Stone Curse? Those are the ones I can think of that you lose HP.

**Comment by MrAntares** [comment]
Max hp reduce is not damage.

Status effects:
bleeding, burning, coma, crystallization, deadly poison, heat, leech end, magic mushroom, toxin, poison, stone curse.

These are not statuses, but maybe we should re-check them as well if they should provide exp or not:
tarot card (fixed damage cards)
white imprison fixed damage
marine sphere
self destruct (homunculi & mech)
feint bomb.

**Comment by aleos89** [comment]
- Crystallization doesn't work on mobs.
- Magic Mushroom can't kill the target.
- Stone Curse can't kill the target since it only does damage if the target has more than 25% HP.

**Comment by aleos89** [comment]
- Crystallization doesn't work against monsters.
- Went through the rest of the effects and updated the ones that were missing.
