### ISSUE TITLE
Giant Fly Wing bug 

### ISSUE THREAD

**Issue by sinju92** [rathena/rathena#6160]
* **rAthena Hash**: 

e8385d812

* **Client Date**: 20180919

* **Server Mode**:  Pre-re

* **Description of Issue**:  when party leader use giant fly wing he doesnt get teleport and all rest party member get recall around him, and another issue if party leader use GFW and he have skill Teleport he can't use that skill until hi use fly wing(601) 
  * Result: https://i.gyazo.com/b2daee964c84ba56d00d0af1e92e4952.gif
  * Expected Result: Party Leader should get teleport
  * How to Reproduce:  
  * Official Information: 
  

* **Modifications that may affect results**: 
  
  
Maybe something related after this update
https://github.com/rathena/rathena/commit/195b21d4a8d1ef70fca14103c7b343bd51b9f9d1

**Comment by violent01** [comment]
yeah that "itemskill "AL_TELEPORT",1;" is the culprit.

**Comment by zdurexz** [comment]
same too
