### ISSUE TITLE
Sell Price not halfed

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#6163]
* **rAthena Hash**: 
666311099e00c5ad4365a5f6f3bf97bab0a3902a

* **Client Date**: 
not relevant

* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result: 
  Items that have a new "Buy" price set in the import folder do no longer automatically half the buy price to generate the sell price. Despite being no sell price defined in the original entry either. This issue exists since the item_db yaml conversion took place.

  * Expected Result:
 Automatically half the buy price to generate the sell price, as described in the item_db.yml description which states:
 `#   Sell                    Selling price. When not specified, becomes half the buy price. (Default: 0)`
 
  
  * How to Reproduce: 
  Add a custom price for an item that doesn't have any sell price set in its original entry. In this example, we use item id 6770.
  ```
    - Id: 6770
    Buy: 300
  ```
  The sell price is still 0 zeny.

  * Official Information: 
  Not relevant.

* **Modifications that may affect results**: 
  None

**Comment by Atemo** [comment]
https://github.com/rathena/rathena/pull/5604
