### ISSUE TITLE
Biolo can't evolve Homu to Homu S (quest script)

### ISSUE THREAD

**Issue by Fraterna** [rathena/rathena#6166]
with more n more upcoming renewal-servers adding 4th jobs, some scripts seem to be outdated. 
one of them: 
"npc/re/quests/homun_s.txt"

several lines that start/advance through the homunculus advancement quest check only for genetic/genetic T/baby genetic, but not for biolo jobs.

* **rAthena Hash**:  current

* **Client Date**:  current

* **Server Mode**:  renewal

* **Description of Issue**: 
  * Result: NPC gives no quest 
  * Expected Result: NPC should give options to evolve Homunculus to Homu S
  * How to Reproduce: just run up to viorel as Biolo with a normal evolved Homu
  * Official Information: none

* **Modifications that may affect results**:  none

**Comment by Lemongrass3110** [comment]
Maybe you should think about reporting problems like this to wherever you bought 4th classes support :-)

**Comment by Fraterna** [comment]
read my 1st sentence again. 
i'm neither a server-owner, admin or gm nor payed someone for 4th classes. stay on topic instead of fishing for likes like some attentio- eh nvm. it will come up sooner or later anyway, feel free to debug it or ignore it like the outdated rapid smiting formula.

**Comment by aleos89** [comment]
The issue at hand is that our base doesn't have 4th classes defined yet since we are working on some other pieces to go in place first. But yes this is a common occurrence when new jobs are introduced and many scripts will need adjustments to support the newly added jobs.

**Comment by Atemo** [comment]
Well it's a bit.. peculiar.. to open an issue to support 4th job in script when they aren't implemented source side yet - unless you already have them.
