### ISSUE TITLE
Wrong Card Orc Baby Card

### ISSUE THREAD

**Issue by zdurexz** [rathena/rathena#6169]
* **rAthena Hash**: 

* **Client Date**: 2020920

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Orc_Baby_Card_Card on item_db_etc and mob_db
  * Expected Result: should be Orc_Baby_Card on item_db_etc and mob_db

* **Modifications that may affect results**: 
  
  
on item_db_etc
![image](https://user-images.githubusercontent.com/59825922/128731699-a21bfada-d613-49a2-968d-b937f949419c.png)
on mob_db
![image](https://user-images.githubusercontent.com/59825922/128731770-b2bf8d40-cc3c-46aa-90ee-51177d6368b2.png)

**Comment by Lemongrass3110** [comment]
https://www.divine-pride.net/database/item/4375 its the official name like this.
Gravity has more typing mistakes than just this one.
