### ISSUE TITLE
Rogue job alway reset skill with unknow reason

### ISSUE THREAD

**Issue by zdurexz** [rathena/rathena#6171]
* **rAthena Hash**: 

* **Client Date**: 20200920

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Rogue job alway reset skill with unknow reason.
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by zdurexz** [comment]
> Can you provide the git hash of the server version you are on?
> 
> What causes the skills to disappear? Map change, relog, dying, switching equipment, doing your taxes? The more details you provide to us the better.

when mapcrash or destroyer instance sometimes. skill job Rogue reset

**Comment by lucasdonida** [comment]
Maybe related to this?


`				if( p->skill[i].flag != SKILL_FLAG_PERMANENT && p->skill[i].flag != SKILL_FLAG_PERM_GRANTED && (p->skill[i].flag - SKILL_FLAG_REPLACED_LV_0) == 0 )`

new one:
`				if( p->skill[i].flag != SKILL_FLAG_PERMANENT && p->skill[i].flag != SKILL_FLAG_PERM_GRANTED && (p->skill[i].flag - SKILL_FLAG_REPLACED_LV_0) <= 0 )
`
