### ISSUE TITLE
Skill Issues and Vellum Weapon. 

### ISSUE THREAD

**Issue by Thurin-zz** [rathena/rathena#618]
Hello, i found some issues in my server.
- [ ] Ninja /  Kagerou
  NJ_ISSEN using STR base formule ( 40 \* sstatus->str + sstatus->hp \* 8 \* skill_lv / 100  ), not ATK based.  ( (ATK_40) + (HP_80%) )
  and Ranged modifier cards (like Skel Archer)Is not working with that.
- [ ] KO_JYUMONJIKIRI mark not dealing aditional damage. 
  http://i.imgur.com/UwxT0uH.jpg  (9943 dmg per hit.)
  http://i.imgur.com/3x8zuGV.jpg   ( 9023 dmg per hit. )
- [ ] Makibishi not dealing CC.
- [x] Genetic
  Poison Spore not dealing damage (Show the dmg numbers, but the monster HP Is not reduced. )
- [x] Mechanic
  Pile Bunker Skill not work with others types of Pile Bunkers (Id; 16030,16031,16032)
- [x] Sorcerer Spell Fist Cannot be affected by critical atk modifiers.
- [x] Royal Guard
  LG_EXEEDBREAK 
  Can you guys review Exceed Break Formula? The damage Is too low compared with other servers and official iRO.  dealing only 500% dmg, ( 750% its the correct )
- [x] Ranger 
  RA_AIMEDBOLT dont work as well, (The cast keep too high when the target its imobillized)
- [ ] Taekwon
  Tumbling has over 20 % chance of activation.
- [x] Some defensive skills can be "avoided" using hpvanish of Vellun Katzbalger (It's ignoring Magic Shield,  and other land defensive skills. ) and, Hpvanish is being applied on skills too.

**Comment by Thurin** [comment]
Some defensive skills can be "avoided" using hpvanish of Vellun Katzbalger. (It's ignoring Magic Shield,  end other land defensive skills. )

**Comment by Turqueren** [comment]
Up, but i love the server.

**Comment by Jokkker** [comment]
Yes, I have the saYes, I have the same problems on my server , I would like these fixesme problems on my server , I would like these fixes

**Comment by Jokkker** [comment]
Yes, I have the same problems on my server , I would like these fixes.

**Comment by milenatk** [comment]
Well, most of these bugs happen on my server , I await the correction

**Comment by cydh** [comment]
somehow, I don't like read batch report in 1 issue.

>Mechanic
>Pile Bunker Skill not work with others types of Pile Bunkers (Id; 16030,16031,16032)

some need to test it on official server

**Comment by Thurin** [comment]
@cydh 
https://rathena.org/board/topic/101392-4082015-maintenance/

**Comment by Paoly28** [comment]
Royal Guard Exceed break is working as intended. ( EB fan here pre-2013 rwc rekt from chakri /gawi )

Aimed Bolt is also working as intended.

can confirm Pile Bunkers on rathena but the 3 PBs are hard to come by so i can't test this on official =(

hpvanish can't be avoided , yes it is horrible but it should not interact with skills ( martyr's reckoning )
