### ISSUE TITLE
Emergencycall re cooldown skill every change map/warp

### ISSUE THREAD

**Issue by hnomkeng** [rathena/rathena#6182]
* **rAthena Hash**: 9d48c5a
* **Client Date**: 2020-05-20b
* **Server Mode**: Pre-renewal
* **Description of Issue**: emergencycall re cooldown(guild_skill_relog_delay) skill every change map/warp(same map)

Example : 
 1. alde_gld -> aldeg_cas01 (change map)
 2. aldeg_cas01,122,62 -> aldeg_cas01,62,191 (change warp)

**Comment by aleos89** [comment]
Duplicate of #5278.
