### ISSUE TITLE
Sale Client 2015.

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#619]
Hello, when you open shop with the client 2015-05-13 and puts more than 2 items for sale, items are as unknown and a very large amount.
http://i.imgur.com/0ZqhH9y.png

**Comment by cydh** [comment]
we don't support 2015 client yet

**Comment by Desground** [comment]
try to put (Load custom lua file instead of iteminfo.lub) in NEMO.
It helped me!

**Comment by icxbb-xx** [comment]
Fixed in https://github.com/rathena/rathena/commit/d2d1fd21d3d4187f04b66744bf249c08947aefcf
