### ISSUE TITLE
Hiding on ride bug clear skilltree

### ISSUE THREAD

**Issue by hnomkeng** [rathena/rathena#6192]
* **rAthena Hash**: cde111a
* **Client Date**: 2020-05-20b
* **Server Mode**: Pre-renewal / Renewal
* **Description of Issue**:  
VDO :  https://youtu.be/tZp5SVKIAPs

**Comment by hnomkeng** [comment]
I comment https://github.com/rathena/rathena/blob/master/src/map/status.cpp#L14028 fixed issue.

**Comment by Lelouzh** [comment]
confrim, it happen when you using pecopeo with swap and temp skill while using it. i think it because state of option?

![screenSakray067](https://user-images.githubusercontent.com/16756766/133921786-08c22fa4-bc0d-462e-b8e0-b57d98b3adfa.jpg)

**Comment by Lelouzh** [comment]
7 years bug like our government
