### ISSUE TITLE
Items sold by NPC's were cut by half.

### ISSUE THREAD

**Issue by violent01** [rathena/rathena#6194]
* **rAthena Hash**: cde111a

* **Client Date**: Irrelevant

* **Server Mode**: Both

* **Description of Issue**: The selling price of items on NPC's were cut by half after this commit by sir aleos89, b119c04
  * Expected Result:  Selling price should not be cut by half.
  * How to Reproduce: download the latest rAthena and test it.
  * Official Information: None
  

* **Modifications that may affect results**:

**Comment by Atemo** [comment]
![screenrAthena002](https://user-images.githubusercontent.com/5231893/129569319-f8e67c33-56e3-4236-a570-5d0e15c55a64.jpg)
```
  - Id: 504
    AegisName: White_Potion
    Name: White Potion
    Type: Healing
    Buy: 1200
```
I'm unable to reproduce from https://github.com/rathena/rathena/commit/b119c04f3e71596d3822f5b7852fdb6548a15918

**Comment by violent01** [comment]
That's weird but maybe I'm just hallucinating, Am going to close this now since it is unreproducible
