### ISSUE TITLE
Player chase movement

### ISSUE THREAD

**Issue by MrAntares** [rathena/rathena#620]
When a player attacks a unit with basic attack that is moving, the player tries to intercept the unit at it's target coordinate and not at it's actual coordinate, and sometimes this results in erratic movement, especially when the target is aggro and changes direction to intercept the player. Usually monsters will be able to hit players instanty as they pass by, but the player just tries to figure out the enemy movement's target cell while the enemy is able to land multiple hits in the meantime.
This is pretty annoying.

I think player attack should work just like mob attack. When the target is in range the player should hit it instantly without yoyoing back and forth, just like mobs can hit the player instantly when it passes by.

Same in this old report item 4) and 5) in the list:
https://rathena.org/board/tracker/issue-5688-player-movement-issue/

**Comment by Playtester** [comment]
That is a client-related issue. Unlike monsters, we have no control over exact player movement and that's handed via requests send by the client and action send back to the client. If the client doesn't send "attack now" packets, there's can't be any attacks.

**Comment by MrAntares** [comment]
The type of the chase pattern is handled on the server, am I right? Even changing that from lead thace to tail chase would help a lot..

**Comment by Playtester** [comment]
No, movement is handled completely client-sided for players. The client even decides when the monster is close enough to send an attack request. It doesn't ask the server where the monster is, it uses what it currently knows. The server can only send "Attack ok" or "Target to far, please move closer to it" to the client.
