### ISSUE TITLE
Use SQL item_db, mob_db and mob_skill_db for the map server Warnings and errors

### ISSUE THREAD

**Issue by bgamez23** [rathena/rathena#6202]
* **rAthena Hash**: 19ef916f6e3fa15f590d768f65f0550e94192482

* **Client Date**: 2020-04-01

* **Server Mode**: Renewal

* **Description of Issue**: Use SQL item_db, mob_db and mob_skill_db for the map server Warnings and errors appear.
* 
![image](https://user-images.githubusercontent.com/1854368/129943130-c2b8b8dd-561a-4fe1-9cb7-ea97e174e760.png)

  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**: Use SQL item_db, mob_db and mob_skill_db for the map server.

**Comment by bgamez23** [comment]
![image](https://user-images.githubusercontent.com/1854368/129943426-4bdf97f0-9156-426b-81d5-786882a8dcb7.png)

**Comment by Lemongrass3110** [comment]
I found the issue, but I guess you want to delete the default entries in the db2 ;-)

**Comment by bgamez23** [comment]
the bug still exist for
 [Info]: Git Hash: 'f4fbfb32993457dc64d371b1bf8fd55e599bbe91'

**Comment by bgamez23** [comment]
![image](https://user-images.githubusercontent.com/1854368/133279162-5b5ceca1-e992-404e-b6d9-79d47ee08a08.png)

**Comment by Lemongrass3110** [comment]
The pull request was not merged yet...

**Comment by bgamez23** [comment]
> The pull request was not merged yet...

oh okay thanks.
