### ISSUE TITLE
bonus bDefEle not working properly

### ISSUE THREAD

**Issue by sonniez** [rathena/rathena#6205]
* **rAthena Hash**: 

https://github.com/rathena/rathena/commit/19ef916f6e3fa15f590d768f65f0550e94192482

* **Server Mode**: 

Renewal

* **Description of Issue**: 
  * Result: I was use Angeling Card (bonus bDefEle,Ele_Holy;) to armor and it's not immune Holy attacker element (such as Adoramus skill)
  * Expected Result: It should immune Holy Attacker as before ? I think it might happen when Converted Elemental Attribute Damage Adjustment Tables to YAML.

**Comment by zdurexz** [comment]
Yes , since update Converted Elemental Attribute Damage Adjustment Tables to YAML

**Comment by attackjom** [comment]
I confirm too. it happen after https://github.com/rathena/rathena/commit/4d2c5b02d38bfb99e3afc4b6dfebeea2c85dbc5f
