### ISSUE TITLE
Homunc gone after 30 minutes

### ISSUE THREAD

**Issue by AsurielRO** [rathena/rathena#6211]
* **rAthena Hash**:  Latest commit

* **Client Date**: 

 20200418

* **Server Mode**: 

 Renewal

* **Description of Issue**: 
  * Result:  I'm not sure if someone encountered this also, but when i use latest rA commit the homunc gone after 30 minutes and they need to be called out again. It's not hungy too i keep on testing it out but maybe someone can confirm this if true or not.
  
  An icon with the name Homunculus called appears on the side for 30 minutes,you leave the homunculus for the night,and he will run away somewhere in half an hour.
  * Expected Result: 
  * How to Reproduce:  Summon homunc then wait for 30 minutes.
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by mundussan** [comment]
This is an official change from kRO, from 3rd jobs improvement patch.
Just search at Divine Pride that you will be able to read that.
That's not a bug.

**Comment by Daegaladh** [comment]
This was changed in 3d4021bfc61be0319aed26e5b496b80faa0e5f88
