### ISSUE TITLE
AS_GRIMTOOTH should cause SC_QUAGMIRE to Normal mobs for 1second

### ISSUE THREAD

**Issue by mrjnumber1** [rathena/rathena#6213]
* **rAthena Hash**: doesnt matter
* **Client Date**: x
* **Server Mode**: both
* **Description of Issue**: 
  * Result: Grimtooth doesn't slow normal mobs
  * Expected Result:  for normal mobs to be slowed
  * How to Reproduce: grimtooht a monster and watch em walk fast on athena
  * Official Information: same code is in ep 8 zone, ep 13.2 zone, and 14.2 zone
```
	case SKID_AS_GRIMTOOTH:
		if ( target->GetType() != NPC_MOB_TYPE )
			goto L_dontcare;
		
		target->GetParameterValue(VAR_CLASS, &class);
		if (class == NPC_CLASS_BOSS || class == NPC_CLASS_GUARDIAN)
			goto L_dontcare;
		
		g_characterMgr->SendMsg(target, CM_SETEFFECTIVE, EFST_QUAGMIRE, 1000. -50, nullptr);
```

* **Modifications that may affect results**: x

**Comment by Daegaladh** [comment]
Does it work 100% of times or it has a chance? I'm not sure what those values mean, I assume the 1000 means 1000ms, but no idea about CM_SETEFFECTIVE or -50

**Comment by mrjnumber1** [comment]
Sorry for not being more clear. It simply means that it calls CNPC::SetEffective with index=EFST_QUAGMIRE, tm=1000 ms and val1=-50.

**Comment by Daegaladh** [comment]
Thanks! It does apply any stat drop? or just the movement slowdown?

**Comment by mrjnumber1** [comment]
Nope, Quag seems to only set movement speed slow on monsters, both from Quag and Grimtooth
