### ISSUE TITLE
Smashing Detected

### ISSUE THREAD

**Issue by AsurielRO** [rathena/rathena#6227]
* **rAthena Hash**:  21cb9e8

* **Client Date**: 

* **Server Mode**:  renewal

* **Description of Issue**: 
  * Result:  After merging new commit smashing detected on the console and suddenly map crash, not sure where this came from and i forgot to get a screenshot maybe someone can confirm this.
  * Expected Result: 
  * How to Reproduce:  Recompile the server then after restart login in-game and crash will happen
  
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by AsurielRO** [comment]
Not sure if related into this but after latest commit when you login 2 accounts map crash will happen, hopefully this will help too.

**Comment by AsurielRO** [comment]
Just to add additional information here, After reaching 10 - 14 character in-game and try to login a new one map crash will trigger and information on the console will appear saying that ** Stack smashing detected ** 
![image](https://user-images.githubusercontent.com/29746866/132447352-381f8471-0972-4dbc-8327-eecaaeebe2f7.png)

**Comment by Lemongrass3110** [comment]
Please provide the GDB stack trace:
https://stackoverflow.com/a/51897264

**Comment by AsurielRO** [comment]
Closing this, after several test we just figure out that the problem was on my connection size. After adjustment map crash doesn't happen anymore.

**Comment by AsurielRO** [comment]
Hi @Lemongrass3110 Sorry it was my mistake again, i thought it was on my connection size, but i still got the problem **Stack smashing detected** and map crash happen. Here's the gdb details.
![image](https://user-images.githubusercontent.com/29746866/133197843-e23dc14a-a3b1-4289-bb23-95ea0a89b27a.png)

Also program received SIGABRT .
![image](https://user-images.githubusercontent.com/29746866/133197905-875dc369-1198-42ea-99e6-b52569dcbdb0.png)

**Comment by Lemongrass3110** [comment]
Maybe @gepard-me can help you with this one.
This does not seem rAthena related.
