### ISSUE TITLE
Sage skill cause map crash

### ISSUE THREAD

**Issue by AsurielRO** [rathena/rathena#6228]
* **rAthena Hash**:  fe7cb5a

* **Client Date**:  

* **Server Mode**:  Renewal

* **Description of Issue**: 
  * Result:  Cast violet gale will be fine on the first cast but after 2nd cast map crash will happen, Same with other skills.
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by kaninhot004** [comment]
I thought they are already fix the problems, please wait for merge. https://github.com/rathena/rathena/pull/6226

**Comment by Miraakol** [comment]
same. i can confirm this.

**Comment by Daegaladh** [comment]
Have you tested this on PR #6226?

**Comment by AsurielRO** [comment]
Not yet but i will try now thank you.

**Comment by AsurielRO** [comment]
Fixed using this commit thank you. #6226

**Comment by Daegaladh** [comment]
Duplicate of #6224
