### ISSUE TITLE
Map crash SIGINT

### ISSUE THREAD

**Issue by AsurielRO** [rathena/rathena#6235]
* **rAthena Hash**:  cb83cb8

* **Client Date**: 

* **Server Mode**:  Renewal

* **Description of Issue**: 
  * Result: 
![image](https://user-images.githubusercontent.com/29746866/132082587-166bcec8-5e30-4c76-9118-eef5da7c9232.png)

  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by Tokeiburu** [comment]
As far as I know, there is only one possible reason for this error (SIGINT) and it is from interrupting the process with Ctrl-C. This is not an issue at all.
