### ISSUE TITLE
Temporal boots enchant

### ISSUE THREAD

**Issue by AsurielRO** [rathena/rathena#6246]
* **rAthena Hash**:  870e3d9

* **Client Date**: 

* **Server Mode**:  Renewal

* **Description of Issue**: 
  * Result:  After you make a temporal boots (not slotted) upgrade it to +12 and get enchant. after that try to slot the +12 enchanted temporal boots and the npc will said that this is not the right item for this enchant.
  * Expected Result:  AFAIK enchant and refine should remain on the item even though it is slotted or not, I think the npc script has missing item id for slotted temporal boots and a function that will keep the enchant and refine of the item. For reference or this is a custom behavior?
![image](https://user-images.githubusercontent.com/29746866/132469816-3d873e9d-1d70-4222-8959-dc0141504288.png)
 
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by AsurielRO** [comment]
Thanks for enlightened me, That's what I'm thinking too maybe they customized the npc to prevent the enchant and refine.

The screenshot that I've send is came from novaro

**Comment by Atemo** [comment]
Then, I'm closing this.
