### ISSUE TITLE
Redemptio not killing skill user.

### ISSUE THREAD

**Issue by jasonch35** [rathena/rathena#6258]
* **rAthena Hash**: 21cb9e87a

* **Client Date**: 20180620

* **Server Mode**: Pre-re

* **Description of Issue**: 
  * Result: Priest stays alive at 1 hp when Redemptio used
  * Expected Result and Official Information: User should die.

* **Modifications that may affect results**: 
 maybe:
			--status_set_hp(src, 1, 0);
			--status_set_sp(src, 0, 0);
  			++status_percent_damage(NULL, &sd->bl, -100, -100, true);
under PR_REDEMPTIO in skill.cpp

**Comment by aleos89** [comment]
```
SP 800을 소모, HP가 1만 남게되며 화면 내의 파티원 전원을 되살려낸다. 되살아난 플레이어들은 50%만큼 HP를 회복한다.
```
The skill behavior has changed from the several class skill balance patches.

**Comment by jasonch35** [comment]
I see. Then maybe needs update on exp lost then or use #ifndef RENEWAL. I could but don't know how to pull request haha. Thanks btw.

**Comment by jasonch35** [comment]
> ```
> SP 800을 소모, HP가 1만 남게되며 화면 내의 파티원 전원을 되살려낸다. 되살아난 플레이어들은 50%만큼 HP를 회복한다.
> ```
> 
> The skill behavior has changed from the several class skill balance patches.

I see. Then maybe needs update on exp lost then or use #ifndef RENEWAL. I could but don't know how to pull request haha. Thanks btw.

**Comment by aleos89** [comment]
After looking back, this skill hasn't been touched in years and has always been setting the Priest's HP to 1.
