### ISSUE TITLE
NPC Manbok#fod01 sells a wrong item

### ISSUE THREAD

**Issue by Skystar18** [rathena/rathena#6260]
* **rAthena Hash**: 0fd2616de

* **Client Date**: 2020-04-16

* **Server Mode**: Renewal

* **Description of Issue**: NPC Manbok at paramk 87 101 sells item ID 22569 (New Year Gift)
  * Result:  Wrong Item ID
  * Expected Result: Correct item ID = 22659 (Steamed Pork Ribs)
  * How to Reproduce: go to NPC Manbok at paramk 87 101 and speak with the npc
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by Everade** [comment]
Confirmed.
22659 is a cash shop item.
