### ISSUE TITLE
bMagicAtkEle and bMagicAddRace Miss the target using Holy

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#6272]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/3d4021bfc61be0319aed26e5b496b80faa0e5f88

* **Client Date**: 2020-09-02

* **Server Mode**: RE

* **Description of Issue**: 
  * Result: 
 There is unusual behavior for elemental damage for a specific range of tested values. With these values the target will not take any damage. 

  
  * Expected Result: 
Increased damage taken to the target.

  
  * How to Reproduce: 
Create this item:
```
 - Id: 2310101
    AegisName: Coat__
    Name: Coat
    Type: Armor
    Buy: 22000
    Weight: 1200
    Defense: 42
    Slots: 1
    Jobs:
      All: true
      Novice: false
      SuperNovice: false
    Classes:
      All_Third: true
      Normal: true
      Upper: true
      Baby: true
      All_Baby: true
    Locations:
      Armor: true
    Refineable: true
    Script: |
      bonus2 bMagicAddRace,RC_Demon,100; 
      bonus2 bMagicAtkEle,Ele_Holy,200;
      bonus2 bMagicAddEle,Ele_Dark,500;
```
```
Use @monster 3254
```
Use skill Adoramus
The monster will not take any damage. Miss

  * Official Information: 
  
  

* **Modifications that may affect results**:

**Comment by kaninhot004** [comment]
Can I knew you damage before equipped these equipments?

**Comment by Badarosk0** [comment]
> Can I knew you damage before equipped these equipments?

Yes, without this item damage is normal. Damage is also normal if you reduce the values in these bonuses. This was the limit range I found that starts the bug.

**Comment by kaninhot004** [comment]
My way is go to '\src\map\battle.cpp'

Change to variable type to int.

![image](https://user-images.githubusercontent.com/9493525/135572708-23b7417a-acb6-4c37-9e59-82f199414b6a.png)

But it's not corrected ways to fix I think.

**Comment by Badarosk0** [comment]
> My way is go to '\src\map\battle.cpp'
> 
> Change to variable type to int.
> 
> ![image](https://user-images.githubusercontent.com/9493525/135572708-23b7417a-acb6-4c37-9e59-82f199414b6a.png)
> 
> But it's not corrected ways to fix I think.

ohh That solved the problem, no more miss.
