### ISSUE TITLE
Vip System Hard Issues

### ISSUE THREAD

**Issue by tmav94** [rathena/rathena#628]
Hi guys, i try everyting i know but nothings work...

Let me explain...

I want a server with 21 characters slots...
3 For normal players, 18 for VIP players.

[Looks the change on mmo.h]
#define MAX_CHARS 21

[Looks the change on core.h]
	#define MIN_STORAGE 300 // Default number of storage slots.
	#define MIN_CHARS 3 // Default number of characters per account.
	#define MAX_CHAR_VIP 18 // This must be less than MAX_CHARS
	#define MAX_CHAR_BILLING 0 // This must be less than MAX_CHARS

[Looks the change on login.conf]
// How many characters are allowed per account?
// You cannot exceed the limit of MAX_CHARS slots, defined in mmo.h, or chars_per_account
// will default to MAX_CHARS.
// 0 will default to the value of MIN_CHARS. (default)
chars_per_account: 0

// Max character limit increase for VIP accounts (0 to disable)
// Increase the value of MAX_CHARS if you want to increase vip_char_increase.
// Note: The amount of VIP characters = MAX_CHARS - chars_per_account.
// Note 2: This setting must be set after chars_per_account.
// Default: 6
vip_char_increase: 18

Recompile the server, and...Appers 39 slots and many of them are "Billing Service"... What'a Hell is this?

**Comment by nanakiwurtz** [comment]
Like always: "What's your client date, git hash?"

**Comment by cydh** [comment]
seems after certain commit (idk which one) that related with 'show the slots to the client', that issue appears. You'll get many many billing service slots.
just as info, for default config when I set `VIP_ENABLE`, (max slots = 9, normal = 3, VIP = 6), I got 6 billing slots.
it's hard for me to solve this, since `char-server <-> client` and `login-server <-> client` packet struct lack of documentation.

**Comment by tmav94** [comment]
@nanakiwurtz Sorry for everytime i forget to show the client data...

My client data is 20141022 and my git is up to https://github.com/rathena/rathena/commit/43068e1777d4b75baa3f36e1c5ff13ca5289e0f4

**Comment by tmav94** [comment]
@cydh ,i agree with you...Use this "report" only for knowledge...I thought you did not know this was happening.

Thx for watching...

**Comment by cydh** [comment]
I'll try for some test and adjust for this issue.
