### ISSUE TITLE
duplicate code

### ISSUE THREAD

**Issue by anacondaqq** [rathena/rathena#629]
### 1. 
> clif.c > https://github.com/rathena/rathena/blob/master/src/map/clif.c#L10593

### 2.
Any anybode can explain this? 

```C

/**
* Add log to player's dmglog
* @param sd
* @param id Monster's GID
**/
void pc_damage_log_add(struct map_session_data *sd, int id)
{
	uint8 i = 0;

	if (!sd)
		return;

	//Only store new data, don't need to renew the old one with same id
	for (i = 0; i < DAMAGELOG_SIZE_PC; i++) {
		if (sd->dmglog[i] == id)
			return;
		sd->dmglog[i] = id;
		return;
	}
}
```
why we have return inside the loop? O_O

**Comment by Lemongrass3110** [comment]
1st is duplicate code that is correct.
@aleos89 @cydh 

2nd is ok, as the comment above the loop says. You only need to add a new entry if there isn't one yet. If there was none yet, you can cancel the loop afterwards.

**Comment by theultramage** [comment]
Um, please use your head. That loop doesn't make any sense and does not agree with the comment. It does not search for an empty slot, it always clobbers dmglog[0] and stops. Look at https://github.com/rathena/rathena/commit/12007fef7e1800ade26c78f7fa45d1c782c38e6d#diff-08420bab8271f3965304fee42cf4b865R10284, here Cydh's brain melted from making this pointlessly big commit and he broke what was originally a scan for an empty slot (or a slot with the same id). So for 2 years the sd->dmglog tracking was broken... I can't tell from looking at the code what impact it has ingame.

**Comment by cydh** [comment]
oh yeah, that should be wrong, but it doesn't make huge impact for damage log.
it just list of MVP that u attacked, when u logout, the list is used to clear the dmglog from 'still' alive MVP.

if it's returned in first loop, that means I just revert what I did (LOL, and dmglog in MVP when you logout is still exists, just like before my that changes /swt)
OK, somehow, as u said maybe, my brain melted then move the 'last' return into the loop.
