### ISSUE TITLE
Adding macro detection features

### ISSUE THREAD

**Issue by Shaktohh** [rathena/rathena#6297]
Macro features coming with clients 2016+

https://github.com/HerculesWS/Hercules/pull/3051/commits/03c54ee9ac1fc6f9fa4e3425a92ccf16df229d33

**Comment by sader1992** [comment]
the interesting thing for me is
```
I intend on adding support for loading images directly from the server and/or having them saved on the server but to keep it simple I will do it in a follow-up PR.
```
it would be a nice thing to have

**Comment by Pokye** [comment]
Wow, it would be great if they added it, I was seeing it here on Herc, and they also added the Captcha part
https://github.com/HerculesWS/Hercules/commit/e8b978711444ff0eff15c8a22a80029e356dc405

**Comment by sgsilva** [comment]
Now is private this feature.
