### ISSUE TITLE
Cart Problem (Latest Rev)

### ISSUE THREAD

**Issue by ernestfegarido** [rathena/rathena#630]
when i rent a cart, cart is not showing. im using latest rev and my client date is 20130807.
PACKET_OBFUSCATION enabled

**Comment by nanakiwurtz** [comment]
Any missing sprite error message?

**Comment by ernestfegarido** [comment]
none :) @nanakiwurtz

**Comment by renniw** [comment]
confirm cart problem  when i update to lasted revision
