### ISSUE TITLE
NPC Refine Master is not working

### ISSUE THREAD

**Issue by Skystar18** [rathena/rathena#6306]
* **rAthena Hash**: c7efcf86a

* **Client Date**: 2020-04-16

* **Server Mode**: Renewal 

* **Description of Issue**: NPC Refine Master (ticket_refiner.txt) is not loading
  * Result: Missing argument "ITEMINFO_TYPE" for line 82 
  * Expected Result: NPC loaded 
  * How to Reproduce: Update to the latest Rathena and run map server
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by Atemo** [comment]
Fixed in https://github.com/rathena/rathena/commit/e0c27fed034d2ec8711d793080fcbc3000732114
