### ISSUE TITLE
Gender Restriction SQL Codes Creates Null Data

### ISSUE THREAD

**Issue by reunite-ro** [rathena/rathena#6315]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/d6a1c03b390a0b40c2657d26429ac85056ce8cd7

* **Client Date**: Not related.

* **Server Mode**: Pre Renewal/Renewal.

* **Description of Issue**: 
  * Result: SQL will create null data since people are running item_db2 or item_db2_re first because its where the create table query are.
   
   This line create this issue since the data are not created yet, it will generate null data.
  * `# Gender restrictions that were removed on official servers
#=============================================================
REPLACE INTO `item_db2` (`id`,`gender`) VALUES (2206,'Female');
REPLACE INTO `item_db2` (`id`,`gender`) VALUES (2208,'Female');
REPLACE INTO `item_db2` (`id`,`gender`) VALUES (2209,'Female');
REPLACE INTO `item_db2` (`id`,`gender`) VALUES (2234,'Female');
REPLACE INTO `item_db2` (`id`,`gender`) VALUES (2235,'Male');
REPLACE INTO `item_db2` (`id`,`gender`) VALUES (2407,'Female');
REPLACE INTO `item_db2` (`id`,`gender`) VALUES (2415,'Female');
REPLACE INTO `item_db2` (`id`,`gender`) VALUES (5143,'Male');
REPLACE INTO `item_db2` (`id`,`gender`) VALUES (5164,'Female');
REPLACE INTO `item_db2` (`id`,`gender`) VALUES (5165,'Male');
REPLACE INTO `item_db2` (`id`,`gender`) VALUES (5191,'Female');
REPLACE INTO `item_db2` (`id`,`gender`) VALUES (5192,'Female');
REPLACE INTO `item_db2` (`id`,`gender`) VALUES (5193,'Female');
REPLACE INTO `item_db2` (`id`,`gender`) VALUES (5194,'Female');
REPLACE INTO `item_db2` (`id`,`gender`) VALUES (5195,'Female');
REPLACE INTO `item_db2` (`id`,`gender`) VALUES (5196,'Female');
REPLACE INTO `item_db2` (`id`,`gender`) VALUES (5197,'Female');
REPLACE INTO `item_db2` (`id`,`gender`) VALUES (5221,'Female');
REPLACE INTO `item_db2` (`id`,`gender`) VALUES (5354,'Male');
REPLACE INTO `item_db2` (`id`,`gender`) VALUES (5355,'Female');
REPLACE INTO `item_db2` (`id`,`gender`) VALUES (5400,'Female');
REPLACE INTO `item_db2` (`id`,`gender`) VALUES (5681,'Female');
`
  
![image](https://user-images.githubusercontent.com/11705163/137447288-0f4b2bfa-b03a-4f40-bb62-3ea85cfb8ca8.png)
 
  * Expected Result: The data should be inserted correctly or our fluxcp will have issue reading it.
  * How to Reproduce: run SQL query for item_db2 or item_db2_re
  * Official Information: Not related.
  

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment]
This is intended. Also just as you stated this is a fluxcp issue.
I already gave out a fix to @Balferian that he can put into a PR if he wants.
