### ISSUE TITLE
lots of [Warning]: Item is an armor, but does not have an armor level. Consider adding it. Defaulting to 1.

### ISSUE THREAD

**Issue by bgamez23** [rathena/rathena#6323]
* **rAthena Hash**: d7b6f39655da0663e60ecfecaed19ff1c2f8f71e

* **Client Date**: 

* **Server Mode**: Renewal

* **Description of Issue**: you will get lots of warning
  * Result: [Warning]: Item is an armor, but does not have an armor level. Consider adding it. Defaulting to 1.

* **Modifications that may affect results**: // Use SQL item_db, mob_db and mob_skill_db for the map server? (yes/no)
use_sql_db: yes
  
  
![image](https://user-images.githubusercontent.com/1854368/137764220-7b14a5c3-e233-4e74-a6e2-9f1655cd2dd0.png)

**Comment by bgamez23** [comment]
> You should be using item_db_re, mob_db_re for renewal

im using both of them but in sql.

**Comment by tungbach1990** [comment]
Maybe because new commit have new column but not alter table yet, you can add ArmorLevel Column then set default to 1 or insert value 1

**Comment by Lemongrass3110** [comment]
Although your screenshots prove that you use outdated data, there is a real issue too.
