### ISSUE TITLE
s_storage size  is too big to be transmitted "MAX_STORAGE"

### ISSUE THREAD

**Issue by AsuraPlop** [rathena/rathena#6329]
* **rAthena Hash**:  Last To day

* **Client Date**: 2018-06-20e

* **Server Mode**: Pre-Renewal

* **Description of Issue**: increasing the max_storage from 500 to a higher value causes an error.

`[Error]: s_storage size = 69324 is too big to be transmitted. (must be below 0xFFFF)`

VIP Enable
Random Options active

* **Modifications that may affect results**: no more 700 max_storage.

**Comment by sader1992** [comment]
so I just tested it with "rAthena Hash: Last To day" 487c27833b9a0a680a562f25484231f7036a7348

Default (600)
![image](https://user-images.githubusercontent.com/5981261/138535050-7ba607b1-f4b8-4319-a0ee-9a0823ec997d.png)


increase to (850)
![image](https://user-images.githubusercontent.com/5981261/138535015-aadc8a57-8a4e-4a18-b75a-a509d931ad5f.png)


You should be able to increase it up to 850
what is your `MAX_STORAGE` value ?
