### ISSUE TITLE
autospell

### ISSUE THREAD

**Issue by renniw** [rathena/rathena#6337]
* **rAthena Hash**: latested revision

* **Client Date**: 20210107

* **Server Mode**: renewal

* **Description of Issue**: 
  * Result: testing with item 21038 and refine it +20. Attacking the eeg (monster#2411). Some damage of sonic wave will be back to owner. i do not  custom item or skill
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by mazvi** [comment]
Yes like on equip +20 iam using `@refine` 0 20. I dont know why

maybe it won't take me long to try 

I only test before you pull yet another auto spell fix..

**Comment by mazvi** [comment]
Confirm on fulbuk card, maybe need merge yet another fix
