### ISSUE TITLE
Skill require with level dependant don't consume required item

### ISSUE THREAD

**Issue by attackjom** [rathena/rathena#6348]
* **rAthena Hash**: 22c7f3988dd0b8f0b8089acb2f1e2cd11ca008ee

* **Client Date**: all

* **Server Mode**: Both

* **Description of Issue**: 
Miss some code that apply dependant-item requirement to skill_get_requirement (in skill.cpp)

  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Fixed in 3b47defa350a416389d5c7248daf0f01c3619e5e.
