### ISSUE TITLE
instance destroyed

### ISSUE THREAD

**Issue by julia40124009** [rathena/rathena#635]
use skill SO_SUMMON_AGNI / SO_SUMMON_AQUA / SO_SUMMON_VENTUS / SO_SUMMON_TERA

enter instance

after destroy instance 

<core>[Error]: map_addblock: out-of-bounds coordinates ("",236,58), map is 0x0</core>

version: https://github.com/rathena/rathena/commit/d301d1ecb354cfcdd92e2f8bddb20358ab15c1c6

**Comment by julia40124009** [comment]
I test it but still show error map_addblock: out-of-bounds coordinates ("",236,58), map is 0x0
version : https://github.com/rathena/rathena/commit/cef2f9ea63aabd45bc5dda294a37fe2f96821275

**Comment by cydh** [comment]
@julia40124009 can u test this please? https://gist.github.com/cydh/1b56996a0dd6de10a274

**Comment by julia40124009** [comment]
work fine for me 
thank you
