### ISSUE TITLE
set/get instance variable commands

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#6353]
**Is your request related to a missing feature?**
Yes, we're lacking a command that allows us to set an instance variable from outside an instance.
For example if you want to pass over instance settings from the instance entry npc into the instance upon creation.

**Describe the solution you'd like**
```
setinstancevar <instance_id>,<variable>,<expression>;
setinstancearray <instance_id>,<array name>[<first value>],<value>{,<value>...<value>};
```

Additionaly rename our current **get** command to reflect other getvar commands:
rename from getvariableofinstance
to getinstancevar

**Describe alternatives you've considered**
Or even better, incorporate it into all the set, setarray, getvar and getarray commands rather than creating new ones.
End goal being, that we can get and set instance variables of any kind from outside ;)

**Comment by Atemo** [comment]
>Or even better, incorporate it into all the set, setarray, getvar and getarray commands rather than creating new ones.

A player can have several instances running at the same time (type guild, party..), meaning an instance ID is required to change the value of a specific instance. In my opinion adding an extra argument (the instance ID) in the `set` etc.. commands seems worse than creating a new command - so I would rather not.

https://github.com/rathena/rathena/blob/7dcc75d82e0521e920f6bcac23e2f36f79fc3e35/doc/script_commands.txt#L9405

The instance variable of a player outside the instance can be changed via
```
	// This will set the 'var variable of the specific instance ID to 1.
	set getvariableofinstance('var, instance_id(IM_GUILD)), 1;
```
It's the same system as when you want to change the npc variable from another npc, I agree it's not user friendly

**Comment by Everade** [comment]
In my opinion it's worse having 5 different commands that do basically the same, rather than incoorporating them into a single one. We've been stacking up on new commands over the years like crazy, and while many of them are same by design, in a lot of cases the naming scheme doesn't help in any way either.
So it's usualy impossible to actualy remember them without jumping back and forth into the documentation unless you script 24/7.

Good example is the one i've given above:
```
getvariableofinstance   <----- Really weird one
```
And let's be real, the txt documentation doesn't really do a good job in helping you find something either.
But that's a different story.

I'm just happy when i can realise my projects in one way or another.
So thanks for letting me know that there's actualy a way to set an instance variable from outside 👍🏻

**Comment by Lemongrass3110** [comment]
I also share @Atemo's opinion and dont think that combining it all into one command would be a good thing.
But I totally agree that commands could be added if currently only very strange workarounds make things possible.

**Comment by Everade** [comment]
Sounds good to me 👍🏻
