### ISSUE TITLE
Duplicate npc variables, intended ?

### ISSUE THREAD

**Issue by sader1992** [rathena/rathena#6354]
* **rAthena Hash**: 2910148b85ef475923f9902b48add277a80250b2
* **Client Date**: 20200401
* **Server Mode**: renewal

* **Description of Issue**: 
  * Result: editing a duplicate npc's variables edits the source npc's variables too
  * Expected Result: not sure if this is intended ,but duplicates should have their own variables
  * How to Reproduce: 
 the npc in the `doc/sample` folder
Or
```cs
prontera,150,175,4	script	Test1::DuplicateTest_refrence	909,{
	mes "Click Count: " + ++.click;
	mes ".test Variable:" + .test;
	close;
}

prontera,155,175,4	duplicate(DuplicateTest_refrence)	Test2	909
prontera,160,175,4	duplicate(DuplicateTest_refrence)	Test3	909


prontera,150,170,4	script	Duplicate Test Control	444,{
	mes "Change .test variable in the original npc to ?";
	input .@n;
	set getvariableofnpc(.test,"DuplicateTest_refrence"), .@n;
	clear;
	mes "Done";
	close;
}
```

* **Modifications that may affect results**:  Nothing, I used clean rAthena to test this

**Comment by Atemo** [comment]
As far as I know the duplicates and original npc have always shared the same npc variables, so the npc variable change whatever the source (duplicate or not).
Did I misunderstand the issue?

**Comment by sader1992** [comment]
> As far as I know the duplicates and original npc have always shared the same npc variables, the npc variable change whatever the source (duplicate or not) and the change apply to all the npc and duplicates. Did I misunderstand the issue?

From what I understand the npcs point to the same variable , they don't each have unique variable
if that is the case then there is no issue here
Thank you.

**Comment by Lemongrass3110** [comment]
Well it is legacy behavior.
Personally I do not really understand why they share it after duplication and it could be changed (at least with a config).

**Comment by Everade** [comment]
I think it would make more sense that they're **not** shared.
Because you could achieve this specific behavior by using global variables instead.

**Comment by Everade** [comment]
Any reason that this has been closed?
I just ran into an issue due to this specific behavior.

Would be great if we could change it accordingly, it really doesn't make much sense.

A duplicate NPC should be considered as an individual unit which has its own variables.

**Comment by Atemo** [comment]
I agree it would make more sense, we could add a battle conf eventually.
However this specificity exists since eAthena, if on it would require to update all the official scripts (and a lot of them are using this specificity) + it would break hundred/thousand custom scripts. GL with that.
It would make more sense but it can stay like that.

**Comment by secretdataz** [comment]
I encountered this issue back in 2016. Ended up doing what I did with this [punching bag script](https://rathena.org/board/files/file/3445-punching-bag-with-dps-counter/).
