### ISSUE TITLE
Another Problem with bAutoSpellWhenHit (?)

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#6365]
* **rAthena Hash**: ae666be

* **Client Date**: 20200401

* **Server Mode**: RE

* **Description of Issue**: 
  * Result:  Attack to myself (check video)
  * Expected Result:  Attack to monster/enemy
  * How to Reproduce:  Using equip Item Id: 2000 then refine it to +20
  * Official Information: 
  

* **Modifications that may affect results**: 
  
  

https://user-images.githubusercontent.com/8316103/142765930-418fa220-ef15-464c-b2de-9f916641e1f3.mp4

**Comment by Anjuts** [comment]
Confirmed. Here is the fix, in pc.cpp:

Change this:
`pc_bonus_autospell(sd->autospell2, type2, type3, val, BF_NORMAL|BF_SKILL, current_equip_card_id, target ? AUTOSPELL_FORCE_SELF : AUTOSPELL_FORCE_TARGET);`

to this:
`pc_bonus_autospell(sd->autospell2, type2, type3, val, BF_NORMAL|BF_SKILL, current_equip_card_id, target ? AUTOSPELL_FORCE_TARGET : AUTOSPELL_FORCE_SELF);`

**Comment by imaqtdan** [comment]
@Anjuts another problem, when using autospellwhenhit and its a self buff like amon ra card, the enemy has receiving the buff not the character.

**Comment by mazvi** [comment]
Or may be need adjust on yaml? @idk-whoami ? 

cc: @aleos89
