### ISSUE TITLE
Songs effects doesn't disappears on dead

### ISSUE THREAD

**Issue by Shaktohh** [rathena/rathena#6368]
* **rAthena Hash**: 
5f92aae35fac4f7c3c52174c9d45e004b153b36a

* **Client Date**: 
20200401

* **Server Mode**: 
Pre-Renewal

* **Description of Issue**: 
Use the Slow Grace skill on a player on PVP or WOE, kill the player.
On dead he still have the slow effect of the skill.

**Comment by Daraen1** [comment]
confirmed with lasted version of rAthena, i use 20180418 Packetver and pre-renewal version

**Comment by Shaktohh** [comment]
I believe there is a effect for songs needed to be remove in pc_bonus_script_clear as it's called on this pc_dead

**Comment by Shaktohh** [comment]
NVM it's intended
https://github.com/rathena/rathena/issues/724

**Comment by Daraen1** [comment]
Ok thanks !
