### ISSUE TITLE
Camouflage effect

### ISSUE THREAD

**Issue by julia40124009** [rathena/rathena#637]
http://irowiki.org/wiki/Camouflage

<core> Camouflaged players cannot be targeted by normal attacks from players (Skills can still be used on the Ranger) and is revealed on hit. </core>

but rathena can't skill  be used on the Ranger

**Comment by reigneil** [comment]
kRO won't let you targeted by skill. working as intended

**Comment by julia40124009** [comment]
invalid ? iro wiki ?
