### ISSUE TITLE
Cannot see the contents of the email sent by other players

### ISSUE THREAD

**Issue by Kuroes** [rathena/rathena#6370]
* **rAthena Hash**: 424e05d

* **Client Date**: 20200902

* **Server Mode**: Pre-Renewal

* **Description of Issue**: Cannot open the mail sent by other players
  * Result: When clicking the mail that I received from a different player. The open does not open 
  * Expected Result: Should be able to open the mail and see its contents 
  * How to Reproduce: Use a diff char and send a mail to another user
  

* **Modifications that may affect results**: 
  
  

https://user-images.githubusercontent.com/48022078/143006922-2df4c5c2-4e00-43e2-a591-99d47806f4eb.mp4

**Comment by Lemongrass3110** [comment]
You need to configure your packetversion correctly.
Open src/custom/defines_pre.hpp and put this inside:
```
#define PACKETVER 20200902
#define PACKETVER_RE
```

**Comment by Kuroes** [comment]
![image](https://user-images.githubusercontent.com/48022078/143009032-524508b3-91c2-4806-bb51-31a3fbc5fee8.png)
The packetver in config/packets.hpp is already on 20200902.

**Comment by Lemongrass3110** [comment]
The important line is the second one.
And this is not where I told you to edit it. :-)

**Comment by Kuroes** [comment]
> The important line is the second one. And this is not where I told you to edit it. :-)

Did what you instructed to do. All is okay now. Thank you!
