### ISSUE TITLE
Problem with DC_WINKCHARM behavior

### ISSUE THREAD

**Issue by Daraen1** [rathena/rathena#6371]
* **rAthena Hash**: 
[ae1135d](https://github.com/rathena/rathena/commit/ae1135dd2b554fa8564e01c6da1866c7c9eee94d)

* **Client Date**: 

20180418

* **Server Mode**: 

I used Pre-Renewal

* **Description of Issue**: 
When I cast "Charming Wink" skill, the monster follow me at my cell. If i move in another cell, the monster don't follow me while he is still under the spell.
When the effect of skill if ended, the monster don't move and don't attack.
If i recast the skill, the monster don't move.
You can see the behavior with this link. 

[Charming Wink behavior](https://www.youtube.com/watch?v=FoH0lq_yw58)

* **Modifications that may affect results**: 
i dunno, i can just say, in Hercules, the skill work correctly

**Comment by Daraen1** [comment]
I think the correct behavior for the Charming Wink skill should be the one you see at this link: [Good Behavior for Charming Wink Skill](https://www.youtube.com/watch?v=v99JaqIDKu4)

Still awaiting bug confirmation status, I sincerely think the skill is currently broken

**Comment by Tydus1** [comment]
I can confirm it on hash a205287307acd96edf76e77eb0976a71c7fffbb1 (latest so far).

After a quick investigation, seems like unit_walktoxy_sub in unit.cpp is looping itself when charmed monster reach player, causing the mob to getting stuck on same cell. 

Test example: Summon a High Orc and wink charm it with some distance. If you keep running from it everything will be good. But if the high orc reach you and then you start moving away, it will be stuck on same cell.

I've made another test adding the code below on unit.cpp line 85 just to keep mobs "moving" in case they get in a to_x  and to_y to the same cell they are:

if (bl->x == ud->to_x && bl->y == ud->to_y)
{
ud->to_x = ud->to_x;
ud->to_y = ud->to_y;
}

It solved the problem of mobs getting stuck but it's not the correct solution.

**Comment by Daraen1** [comment]
The problem described by @Tydus1 is exactly the one I demonstrate in the video on the first link. The good behavior of the skill is on the second link :)
Thanks for confirming the bug, I thought I was the only one going crazy lmao

**Comment by Tydus1** [comment]
Analysing unit_walktoxy_timer in unit.cpp i've found a weird behavior: 

Seems like ud->walkpath.path[ud->walkpath.path_pos] line 361 (unit.cpp) is always DIR_CENTER (-1). I'm not sure if it's supposed to be like that but maybe there's something wrong with that attribute. 

enum directions dir = ud->walkpath.path[ud->walkpath.path_pos];

variable dir is always being equal to DIR_CENTER when you wink charm mobs and then 

int dx = dirx[dir]; 
int dy = diry[dir];

dirx[dir] always get a dump value, but diry[dir] does not... i'm not sure why (yet)

**Comment by Tydus1** [comment]
@Daraen1 Pull requested a fix for this issue. I appreciate if you can confirm the (possible) solution.

**Comment by Daraen1** [comment]
I just tried your pull request and it looks like the skill is working fine now, video proof! 
[Charming Wink Fix](https://www.youtube.com/watch?v=o5eW2dfaVz4)
good job @Tydus1
