### ISSUE TITLE
Autospell Supportive Skill Bug

### ISSUE THREAD

**Issue by imaqtdan** [rathena/rathena#6383]
Client Date: 20200401
Server Mode: Pre-re
Description of Issue: All auto supportive skill are casting on enemy instead self.

Result: Attack to myself (check video)
Expected Result: when attack the enemy with the amon ra card auto cast the Kyrie on him self, but the attacker has receiving the Kyrie
How to Reproduce: Using equip Item Amon ra card then hit the user.
Official Information:
Modifications that may affect results:
https://user-images.githubusercontent.com/69942447/144222194-b247ba94-f072-4a06-ab71-813eefcdfd68.mp4

**Comment by imaqtdan** [comment]
cc: @aleos89

**Comment by mazvi** [comment]
Please inform your rAthena hash

**Comment by imaqtdan** [comment]
![image](https://user-images.githubusercontent.com/69942447/145405180-c31d094e-70f7-4e05-9d3a-91a2296f8132.png)
@Lemongrass3110

**Comment by imaqtdan** [comment]
238af67994cce154995c462b458v30453a886cf1

**Comment by imaqtdan** [comment]
the non aoe skills like single target firebolt when it uses to autospellwhenhit it will be back to the user but if meteor storm like darklordcard it will damage to enemies.
