### ISSUE TITLE
Diamond Dust skill Can Overlap

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#6387]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/3d4021bfc61be0319aed26e5b496b80faa0e5f88

* **Client Date**: 2020-09-02

* **Server Mode**: RE

* **Description of Issue**: 
  * Result: 
The Diamond Dust skill has a NoOverlap mapflag.

  
  * Expected Result: 
The Diamond Dust skill can overlap.

  
  * How to Reproduce: 

  * Official Information: 
  
  
kRO video
https://youtu.be/bwIqfOeecw4?t=54

* **Modifications that may affect results**:

**Comment by laziem** [comment]
Maybe Comet can overlap too?

**Comment by Badarosk0** [comment]
> Maybe Comet can overlap too?

Comet I don't know yet

**Comment by attackjom** [comment]
I confirm from playing archmage in kro , comet can overlap too.
