### ISSUE TITLE
Outdated Enchant Check Function

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#6389]
* **rAthena Hash**: 
4cd2ef747d8c1d38ee257800701c258fe3af621b

* **Client Date**: 
Not relevant

* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result: The function "F_IsCharm" is only checking for the old original enchants despite the new additions that took place over the years.
  * Expected Result: Add all missing enchant ids
  * How to Reproduce: Use any NPC that utilizes the function while using any of the new enchants on your equipment. The check will fail.
  * Official Information: No idea how official servers check for enchants. The fact that we consider them as actual cards still bugs me since their initial implementation...

* **Modifications that may affect results**: 
None

**Comment by Atemo** [comment]
>No idea how official servers check for enchants. The fact that we consider them as actual cards still bugs me since their initial implementation...

(For info) On aegis the item data has a field to differentiate a normal card from enchant card, our item_db doesn't have that (not yet)

**Comment by aleos89** [comment]
I was going to suggest we could use SubType and add Card support to it.
