### ISSUE TITLE
tick_def2 not always adjusted by pc_sc_def_rate

### ISSUE THREAD

**Issue by theultramage** [rathena/rathena#639]
When tick_def2 (numeric status duration reduction) was implemented into the existing code in https://github.com/rathena/rathena/commit/a3dc2d9cf45e0bd89259b77bfa5adae08f1b5ea0, a coding mistake was made in two places in skill_castend_nodamage_id():
```
		if (tick_def > 0 && battle_config.pc_sc_def_rate != 100) {
			tick_def = tick_def*battle_config.pc_sc_def_rate/100;
			tick_def2 = tick_def2*battle_config.pc_sc_def_rate/100;
```
```
		if (tick_def > 0 && battle_config.mob_sc_def_rate != 100) {
			tick_def = tick_def*battle_config.mob_sc_def_rate/100;
			tick_def2 = tick_def2*battle_config.mob_sc_def_rate/100;
```

The if condition is checking tick_def only. If the server happens to be using non-default status def rates, statuses which only have a tick_def2 resistance will not get their rates adjusted.

The solution is to either break them up into separate checks, or, remove the 'tick_def > 0' check entirely since it's not needed and doesn't really save much cpu time, and adds complexity. If you look at surrounding code, it has dropped the nonzero checks, and even the '!= 100' check in some cases.

**Comment by Playtester** [comment]
rAthena doesn't support custom code modifications.

There is probably a good reason why I put the check there, even though I can't remember it anymore, so I wouldn't remove it.

**Comment by theultramage** [comment]
There are no custom modifications here, but the problem only arises when *_sc_def_rate is not 100.
And no you did not put any checks in, read the commit diff. The checks were already there, but only for tick_def. You shoved additional code (for tick_def2) inside tick_def-only checks.
