### ISSUE TITLE
Baby classes HP problems

### ISSUE THREAD

**Issue by kaninhot004** [rathena/rathena#6393]
* **rAthena Hash**: 4a778815a344a5555209dc79fa80b8fff11fbad9

* **Client Date**: 20200401

* **Server Mode**: Renewal

* **Screenshot**: 

![Capture](https://user-images.githubusercontent.com/9493525/144962364-f4639f92-0439-4c59-9173-67cd8a24f49e.JPG)

* **Description of Issue**: 
  * Result: Job ID 4222 till 4229, HP went up to million.
  * Expected Result: HP calculate correctly.
  * How to Reproduce: @ job 4222 and @ lvup 99
  * Official Information: -

* **Modifications that may affect results**: -

**Comment by aleos89** [comment]
I'm assuming you're not using the HP/SP tables?

**Comment by kaninhot004** [comment]
https://user-images.githubusercontent.com/9493525/145136422-0331f50b-3bbb-4352-8506-1a0786e2c3c9.mp4

This is test from latest commits.
I compared changes between my local branch and master then see in game hp.

**Comment by idk-whoami** [comment]
confirmed. latest commit 4a778815a344a5555209dc79fa80b8fff11fbad9
missing expanded baby class
e.g.
https://github.com/rathena/rathena/blob/master/db/re/job_basepoints.yml#L7285-L7286
```
  - Jobs:
      Gunslinger: true
      Baby_Gunslinger: true
