### ISSUE TITLE
Pet Capture Rate always 100%

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#6395]
* **rAthena Hash**: 
4a778815a344a5555209dc79fa80b8fff11fbad9

* **Client Date**: 
Not relevant

* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result: Pet Capture rate is extremely off. (always 100%)
  * Expected Result: Pet Database to set pet capture rate accordingly as given in the doc. (10000 = 100%)
  * How to Reproduce: Try to tame any pet that has a very low capture rate.
  To test this even further, i've set the battle configuration pet_catch_rate: 10 down, yet it still seems to be at 100% instead of 0.05%.
  Only with pet_catch_rate: 1 i started to actualy fail sometimes, but the chance was still somewhere inbetween 10~50% instead of 0.005% for Hydra.
  * Official Information: Obviously wrong.

* **Modifications that may affect results**: 
reduced pet_catch_rate:  battle config for further rate reduction.

**Comment by Lemongrass3110** [comment]
```
	pet_catch_rate = (pet->capture + (sd->status.base_level - md->level)*30 + sd->battle_status.luk*20)*(200 - get_percentage(md->status.hp, md->status.max_hp))/100;

	if(pet_catch_rate < 1)
		pet_catch_rate = 1;

	if(battle_config.pet_catch_rate != 100)
		pet_catch_rate = (pet_catch_rate*battle_config.pet_catch_rate)/100;
```

**Comment by Everade** [comment]
Silly me, i had 15k luk from previous tests.
Thanks for the info.

**Comment by Lemongrass3110** [comment]
Confirmed that our current formula is wrong.
Thanks to @mrjnumber1 for the official formula:
```
bool CPC::IsCaptureSuccess(CNPC* pTarget, int item)
{
    auto info = g_petDefaultValue->GetDefaultValue(pTarget->m_characterInfo.job);
    if (!info) return false;
    
    auto percent = info->iCapturePercent;
    int hp=0, maxhp=0;
    pTarget->GetParameterValue(VAR_HP, &hp);
    pTarget->GetParameterValue(VAR_MAXHP, &maxhp);
    percent += (1.0 - hp / maxhp) * percent;
    return (GetServerRandom(0, 20000)%100 < (int)percent);
}
```
