### ISSUE TITLE
Bio Explosion skill supposed to reduce intimacy at 1, its not the case.

### ISSUE THREAD

**Issue by Daraen1** [rathena/rathena#6396]
* **rAthena Hash**: 
 
    Lasted version (version of 08 december 2021)

* **Client Date**: 

     2018 04 18

* **Server Mode**: 

     Pre-renewal

* **Description of Issue**: 
  I think the Bio Explosion skill has a problem. According to several databases, after using the skill, the privacy should be reduced to 1.
  This is currently not the case
 https://www.youtube.com/watch?v=QrFR1Oid-T0
 
Note: I don't really know if this is a bug, after asking the question about the rAthena discord several times, I didn't get an answer, so I took the initiative to post it as a problem.
If a staff member can add the label "need more information" that would be nice.

**Comment by aleos89** [comment]
Fixed in [eff452f](https://github.com/rathena/rathena/commit/eff452fa3526250e9c64da55bb260b274add67d3).
