### ISSUE TITLE
pre-re/item_noequip.txt

### ISSUE THREAD

**Issue by zaido78** [rathena/rathena#640]
Hello..item_noequip.txt not working i try to put any item disble for GVG but the item still work on GVG i try to use the official item on item_noequip like 

//----------------------------------------------------------------------------
// GVG
//----------------------------------------------------------------------------
12218,4	//Assumptio_5_Scroll
14529,4	//Greed_Scroll
14590,4	//Pty_Assumptio_Scroll

but still working on GVG

**Comment by nanakiwurtz** [comment]
Which Git Hash are you on?
Are you using Renewal/Pre-Re?

**Comment by zaido78** [comment]
the latest one i download rathena now then i try item_noequip is not working.. im using Pre-RE

**Comment by cydh** [comment]
have you read these before? https://github.com/rathena/rathena/blob/master/conf/battle/items.conf#L81-L90
````
// Allow the consumption of usable items that are disabled by item_noequip.txt? (Note 1)
// no = can't be consumed
// yes = consumed with no effect
allow_consume_restricted_item: yes

// Allow equipping items that are disabled by item_noequip.txt? (Note 1)
// no = can't be equipped and will be unequipped when entering the map
// yes = can be equipped but gives no effect
// If the equip is compounded with restricted card(s), it ignores this check but still gives no effect.
allow_equip_restricted_item: yes
````

I think on this file, we need put a note "Please read config 'allow_consume_restricted_item' and 'allow_equip_restricted_item' in conf/battle/items.conf" /hmm

**Comment by zaido78** [comment]
ohh i forgot this method sorry
