### ISSUE TITLE
Screenshot saving as .png

### ISSUE THREAD

**Issue by BardBun** [rathena/rathena#6403]
After so many years of Ragnarok existing, the game still saves screenshots as .jpg in super low quality.

Nearing 2022, would it be possible to change the rAthena client to take screenshots in lossless .png quality?

**Comment by Daraen1** [comment]
it's a good idea indeed.
But in the meantime I can offer you an alternative solution, it is called: selective screenshot.
To do this, simply press the windows + shift + s button quickly.
select the part on screen, then open Paint and do ctrl + v and you can save it in .png

**Comment by sader1992** [comment]
this is from the client side , not the server side.

**Comment by llchrisll** [comment]
I personally use Lightshot, super easy tool, as well as ShareX.
