### ISSUE TITLE
Missing support for unequip all button

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#6415]
New clients have a new small feature that allows you to remove all items equipped on the character by clicking a button, on Hercules it has this packet, but on RA not yet, I would like to request the addition here too.

Client date: 2021-11-17_Ragexe

Packet: CZ_REQ_TAKEOFF_EQUIP_ALL, 0x0bad

Window:
![a111](https://user-images.githubusercontent.com/6227618/146679763-dad64c11-37d4-4d37-8c86-68b0e34db2e3.png)

Warning:
`clif_parse: Received unsupported packet (packet 0x0bad, 2 bytes received), disconnecting session #3.
`
Result:
Disconect from the game.

**Comment by Balferian** [comment]
It should unequip items only from first tab, without shadow equip / decor.
Tested on kRo.
![image](https://user-images.githubusercontent.com/16213511/146689707-3d6b832c-3624-4867-bba5-54e26465c80f.png)

**Comment by Lemongrass3110** [comment]
This client is not officially supported yet ;-)

**Comment by RagnaWay** [comment]
`pUnequipAllItems`
https://github.com/HerculesWS/Hercules/commit/01bbe6b5b3846275d094cea4dd7e1a0e868d3490#diff-754b8ca8fe2af31705c40781ffe8bc82f1c3f830670a0b571cb0d674faf58226R2022
