### ISSUE TITLE
Global Map Navi Crashes Client

### ISSUE THREAD

**Issue by NordGate** [rathena/rathena#6417]
* **rAthena Hash**: 

* **Client Date**:  2018-06-20e

* **Server Mode**: Renewal

* **Description of Issue**: When you're in Juno with your character and set the navi to Sphinx 5th, the client crashes.
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment]
Navigation is client side.
