### ISSUE TITLE
Episode upgrade?

### ISSUE THREAD

**Issue by joelolopez** [rathena/rathena#642]
guys can we implement this hero trails part 2 and theres a lot of episode included here too like devil tower etc, update, it includes new monsters, here are some information about the update that i proposed.. http://ro.vrc7.net/?page_id=1557 i hope that this infos are enough to implement this update

**Comment by dastgir** [comment]
There's lots of npc that can't be predicted by those descriptions

**Comment by Jeybla** [comment]
Maybe we should create Issues for each episode with clear task lists, sources and so on?
This issue is not very useful.

**Comment by secretdataz** [comment]
@Jeybla I'm going to take the list from Hercules and revise them one by one.

**Comment by secretdataz** [comment]
Moved to #1301. I'm closing this.
