### ISSUE TITLE
Eternal Cast

### ISSUE THREAD

**Issue by xponzy** [rathena/rathena#6421]
rAthena Hash:

Lasted version (version of 21 december 2021)

Client Date:

2018 06 20

Server Mode:

Pre-renewal

Description of Issue:
Kye election, increase agi skills cast very slow, I am using the latest version of rAthena in Pre-renewal mode.

![Screenshot_8](https://user-images.githubusercontent.com/94275985/147185222-fe7c3ac4-a156-4391-b8bd-9a1194a40829.png)

**Comment by Shaktohh** [comment]
Pre renewal ? Renewal ?
What are your stats ?
