### ISSUE TITLE
Diamond Dust and others Sorcerer's skills has wrong formulas

### ISSUE THREAD

**Issue by Rayvakarian** [rathena/rathena#6425]
* **rAthena Hash**: 

153a83d

* **Client Date**: 

2021-11-17

* **Server Mode**: 

Renewal

* **Description of Issue**: 
I compared damage of Sorcerer's skills inside rAthena and at Sakray, damage was different with the same stats
(1st screenshot - rAthena, 2nd - Sakray) 
![image](https://user-images.githubusercontent.com/65616872/147615806-b3543e30-2031-494d-b56b-be06cfd6296f.png)
![image](https://user-images.githubusercontent.com/65616872/147615814-c9ee6a9d-bf80-4588-9cb4-ee292faf33f3.png)

**Comment by Akkarinage** [comment]
A single screenshot from each doesn't make for a good average comparison. Can you record video evidence of 10 attacks on each server? That might actually help with formula guesswork.

**Comment by Rayvakarian** [comment]
> A single screenshot from each doesn't make for a good average comparison. Can you record video evidence of 10 attacks on each server? That might actually help with formula guesswork.

I'm sorry, but this screenshot I've got from my friend who tested Sorcerer at Sakray. He said Sorcerer's skills have wrong formulas and gave this screenshot.

**Comment by Everade** [comment]
I can confirm that the current rAthena **Diamond Dust** damage doesn't even come close to kRO.
4th class footage:
https://www.youtube.com/watch?v=YPlr2G-gwCQ

3rd class base lvl 170:
https://www.youtube.com/watch?v=AWH6YPj4p30

I've tried to mimic the gear set as close as possible from the older 3rd class video:
![image](https://user-images.githubusercontent.com/12261601/151171587-502af256-c317-4c2c-88f0-486813c89093.png)
![image](https://user-images.githubusercontent.com/12261601/151171712-c410a13f-934f-4a27-a68b-bfa540259870.png)

A test with all gear refined to +20 to get as much matk as possible and still not reaching the kRO damage.
![image](https://user-images.githubusercontent.com/12261601/151172070-17bc7e54-a512-4d84-a638-c4b261f99c59.png)
![image](https://user-images.githubusercontent.com/12261601/151172410-e7b35293-9705-45f4-b441-ac5755e79846.png)

25k on average each hit on kRO
7k on avergage with very similiar gear /stats setup on rA

Unless i've missed an extremely strong shadow gear effect that i wasn't able to find, i would say we need some adjustments.

**Comment by Rayvakarian** [comment]
> I can confirm that the current rAthena **Diamond Dust** damage doesn't even come close to kRO. 4th class footage: https://www.youtube.com/watch?v=YPlr2G-gwCQ
> 
> 3rd class base lvl 170: https://www.youtube.com/watch?v=AWH6YPj4p30
> 
> I've tried to mimic the gear set as close as possible from the older 3rd class video: ![image](https://user-images.githubusercontent.com/12261601/151171587-502af256-c317-4c2c-88f0-486813c89093.png) ![image](https://user-images.githubusercontent.com/12261601/151171712-c410a13f-934f-4a27-a68b-bfa540259870.png)
> 
> A test with all gear refined to +20 to get as much matk as possible (and a lot of diamond dust specific gear set bonuses) and still not reaching the kRO damage. ![image](https://user-images.githubusercontent.com/12261601/151172070-17bc7e54-a512-4d84-a638-c4b261f99c59.png) ![image](https://user-images.githubusercontent.com/12261601/151172410-e7b35293-9705-45f4-b441-ac5755e79846.png)
> 
> 25k on average each hit on kRO 7k on avergage with very similiar gear /stats setup on rA
> 
> Unless i've missed an extremely strong shadow gear effect that i wasn't able to find, or all the gear has no effects :P, i would say we need some adjustments.

Can you confirm others Sorcerer's skills, please? I remember the same was with Varetyre Spear.

**Comment by Balferian** [comment]
When we test it on kRo (~2020.03.20) we calculated the following formulas:
![image](https://user-images.githubusercontent.com/16213511/151173786-ed257e49-9f18-4945-8bd7-ff00695fee4f.png)
![image](https://user-images.githubusercontent.com/16213511/151173815-69e1c397-a8f1-4ba7-b89a-545367a40d12.png)
![image](https://user-images.githubusercontent.com/16213511/151174206-9a4da99a-161d-435e-878c-0716adb16f99.png)
![image](https://user-images.githubusercontent.com/16213511/151173894-89758e26-6fba-4e16-8967-e3bff3fd4ee7.png)

> case SO_DIAMONDDUST:
   skillratio += -100 + 2 * sstatus->int_ + 300 * ((sd) ? pc_checkskill(sd, SA_FROSTWEAPON) : 0) + sstatus->int_ * skill_lv;

The same for EarthGrave:
>  case SO_EARTHGRAVE:
   skillratio += -100 + 2 * sstatus -> int_ + 300 * ((sd) ? pc_checkskill(sd, SA_SEISMICWEAPON) : 0) + sstatus -> int_ * skill_lv;
   
Thanks for this Winterfall#2579.
