### ISSUE TITLE
callshop "name",2; Is this issue ?

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#6426]
* **rAthena Hash**: 745731b

* **Client Date**: 20200401

* **Server Mode**: RENEWAL

* **Description of Issue**: 

On this script https://github.com/rathena/rathena/blob/master/npc/re/merchants/eden_market.txt

There was script like this:
```
		case 2:
			mes "[Aurora]";
			mes "We will buy at a reasonable price.";
			close2;
			callshop "para_jew10",2;
			end;
```

  * Result:  Open buy Window
  * Expected Result:  Open sell Window
  * How to Reproduce:  Go to paramarket and select sell item on aurora
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by Atemo** [comment]
Please fill the template
```
Result:
Expected Result: 
```
I see see any issue at first and I don't understand what are you expecting

**Comment by mazvi** [comment]
> Please fill the template
> 
> ```
> Result:
> Expected Result: 
> ```
> 
> I see see any issue at first and I don't understand what are you expecting

:D Edited sir
