### ISSUE TITLE
i dont know what happened

### ISSUE THREAD

**Issue by ernestfegarido** [rathena/rathena#643]
when i updated my trunk to latest rev. map server wont finish loading all files.

map server only load files until here then when i try to connect always rejected from the server.

[Status]: Awaiting maps from map-server.
[Status]: Done reading '3512' entries in 'db/re/item_package.txt'.
[Status]: Done reading '0' entries in 'db/re/item_group_db.txt'.
[Status]: Done reading '461' entries in 'db/re/item_combo_db.txt'.
[Status]: Done reading '50' entries in 'db/re/item_noequip.txt'.
[Status]: Done reading '3176' entries in 'db/re/item_trade.txt'.
[Status]: Done reading '31' entries in 'db/re/item_delay.txt'.
[Status]: Done reading '1189' entries in 'db/re/item_buyingstore.txt'.
[Status]: Done reading '1679' entries in 'db/re/item_flag.txt'.
[Status]: Done reading '0' entries in 'db/import/item_avail.txt'.
[Status]: Done reading '0' entries in 'db/import/item_stack.txt'.
[Status]: Done reading '0' entries in 'db/import/item_nouse.txt'.
[Status]: Done reading '0' entries in 'db/import/item_group_db.txt'.
[Status]: Done reading '0' entries in 'db/import/item_combo_db.txt'.
[Status]: Done reading '73' entries in 'db/import/item_noequip.txt'.
[Status]: Done reading '0' entries in 'db/import/item_trade.txt'.
[Status]: Done reading '0' entries in 'db/import/item_delay.txt'.
[Status]: Done reading '0' entries in 'db/import/item_buyingstore.txt'.
[Status]: Done reading '0' entries in 'db/import/item_flag.txt'.
[Status]: Done reading '0' entries in 'db/re/item_cash_db.txt'.
[Status]: Done reading '0' entries in 'db/import/item_cash_db.txt'.
[Status]: Done reading '1109' entries in 'db/re/skill_db.txt'.
[Status]: Done reading '865' entries in 'db/re/skill_require_db.txt'.
[Status]: Done reading '815' entries in 'db/re/skill_cast_db.txt'.
[Status]: Done reading '53' entries in 'db/re/skill_castnodex_db.txt'.
[Status]: Done reading '145' entries in 'db/re/skill_unit_db.txt'.
[Status]: Done reading '110' entries in 'db/re/skill_nocast_db.txt'.
[Status]: Done reading '264' entries in 'db/re/produce_db.txt'.
[Status]: Done reading '136' entries in 'db/create_arrow_db.txt'.
[Status]: Done reading '155' entries in 'db/abra_db.txt'.
[Status]: Done reading '17' entries in 'db/spellbook_db.txt'.
[Status]: Done reading '23' entries in 'db/magicmushroom_db.txt'.
[Status]: Done reading '144' entries in 'db/skill_copyable_db.txt'.
[Status]: Done reading '16' entries in 'db/skill_improvise_db.txt'.
[Status]: Done reading '74' entries in 'db/skill_changematerial_db.txt'.
[Status]: Done reading '2' entries in 'db/skill_nonearnpc_db.txt'.
[Status]: Done reading '0' entries in 'db/import/skill_db.txt'.
[Status]: Done reading '0' entries in 'db/import/skill_require_db.txt'.
[Status]: Done reading '0' entries in 'db/import/skill_cast_db.txt'.
[Status]: Done reading '0' entries in 'db/import/skill_castnodex_db.txt'.
[Status]: Done reading '0' entries in 'db/import/skill_unit_db.txt'.
[Status]: Done reading '0' entries in 'db/import/skill_nocast_db.txt'.
[Status]: Done reading '0' entries in 'db/import/produce_db.txt'.
[Status]: Done reading '0' entries in 'db/import/create_arrow_db.txt'.
[Status]: Done reading '0' entries in 'db/import/abra_db.txt'.
[Status]: Done reading '0' entries in 'db/import/spellbook_db.txt'.
[Status]: Done reading '0' entries in 'db/import/magicmushroom_db.txt'.
[Status]: Done reading '0' entries in 'db/import/skill_copyable_db.txt'.
[Status]: Done reading '0' entries in 'db/import/skill_improvise_db.txt'.
[Status]: Done reading '0' entries in 'db/import/skill_changematerial_db.txt'.
[Status]: Done reading '0' entries in 'db/import/skill_nonearnpc_db.txt'.
[Status]: Done reading '1666' entries in 'db/re/mob_db.txt'.
[Status]: Done reading '9846' entries in 'db/re/mob_skill_db.txt'.
[Status]: Done reading '0' entries in 'db/mob_avail.txt'.
[Status]: Done reading '6' entries in 'db/re/mob_race2_db.txt'.
[Status]: Done reading '0' entries in 'db/mob_item_ratio.txt'.
[Status]: Done reading '40' entries in 'db/mob_chat_db.txt'.
[Status]: Done reading '480' entries in 'db/re/mob_branch.txt'.
[Status]: Done reading '14' entries in 'db/re/mob_poring.txt'.
[Status]: Done reading '47' entries in 'db/re/mob_boss.txt'.
[Status]: Done reading '331' entries in 'db/mob_pouch.txt'.
[Status]: Done reading '25' entries in 'db/mob_classchange.txt'.
[Status]: Done reading '0' entries in 'db/re/mob_random_db.txt'.
[Status]: Done reading '0' entries in 'db/import/mob_db.txt'.
[Status]: Done reading '0' entries in 'db/import/mob_skill_db.txt'.
[Status]: Done reading '0' entries in 'db/import/mob_avail.txt'.
[Status]: Done reading '0' entries in 'db/import/mob_race2_db.txt'.
[Status]: Done reading '0' entries in 'db/import/mob_item_ratio.txt'.
[Status]: Done reading '0' entries in 'db/import/mob_chat_db.txt'.
[Status]: Done reading '0' entries in 'db/import/mob_random_db.txt'.
[Status]: Done reading '5316' entries in 'db/re/skill_tree.txt'.
[Status]: Done reading '0' entries in 'db/import/skill_tree.txt'.
[Status]: Done reading '37' entries in 'db/re/level_penalty.txt'.
[Status]: Done reading '0' entries in 'db/import/level_penalty.txt'.
[Status]: Done reading '175' entries in 'db/re/statpoint.txt'.
[Status]: Done reading '134' entries in 'db/re/job_db1.txt'.
[Status]: Done reading '133' entries in 'db/job_db2.txt'.
[Status]: Done reading '17' entries in 'db/re/job_exp.txt'.
[Status]: Done reading '83' entries in 'db/re/job_basehpsp_db.txt'.
[Status]: Done reading '0' entries in 'db/re/job_param_db.txt'.
[Status]: Done reading '0' entries in 'db/import/statpoint.txt'.
[Status]: Done reading '0' entries in 'db/import/job_db1.txt'.
[Status]: Done reading '0' entries in 'db/import/job_db2.txt'.
[Status]: Done reading '0' entries in 'db/import/job_exp.txt'.
[Status]: Done reading '0' entries in 'db/import/job_basehpsp_db.txt'.
[Status]: Done reading '0' entries in 'db/import/job_param_db.txt'.
[Status]: Done reading '1' entries in 'conf/motd.txt'.
[Status]: Done reading '8' groups in 'conf/groups.conf'.
[Status]: Done reading '4' entries in 'db/re/attr_fix.txt'.
[Status]: Done reading '3' entries in 'db/size_fix.txt'.
[Status]: Done reading '5' entries in 'db/re/refine_db.txt'.
[Status]: Done reading '0' entries in 'db/import/attr_fix.txt'.
[Status]: Done reading '0' entries in 'db/import/size_fix.txt'.
[Status]: Done reading '0' entries in 'db/import/refine_db.txt'.
[Status]: Done reading '34' entries in 'db/castle_db.txt'.
[Status]: Done reading '15' entries in 'db/guild_skill_tree.txt'.
[Status]: Done reading '0' entries in 'db/import/castle_db.txt'.
[Status]: Done reading '0' entries in 'db/import/guild_skill_tree.txt'.
[Status]: Done reading '63' pets in 'db/re/pet_db.txt'.
[Status]: Done reading '0' pets in 'db/import/pet_db.txt'.
[Status]: Done reading '13' entries in 'db/re/homunculus_db.txt'.
[Status]: Done reading '0' entries in 'db/import/homunculus_db.txt'.
[Status]: Done reading '150' levels in 'db/re/exp_homun.txt'.
[Status]: Done reading '0' levels in 'db/import/exp_homun.txt'.
[Status]: Done reading '82' entries in 'db/homun_skill_tree.txt'.
[Status]: Done reading '0' entries in 'db/import/homun_skill_tree.txt'.
[Status]: Done reading '61' entries in 'db/mercenary_db.txt'.
[Status]: Done reading '0' entries in 'db/import/mercenary_db.txt'.
[Status]: Done reading '153' entries in 'db/mercenary_skill_db.txt'.
[Status]: Done reading '0' entries in 'db/import/mercenary_skill_db.txt'.
[Status]: Done reading '12' entries in 'db/elemental_db.txt'.
[Status]: Done reading '0' entries in 'db/import/elemental_db.txt'.
[Status]: Done reading '36' entries in 'db/elemental_skill_db.txt'.
[Status]: Done reading '0' entries in 'db/import/elemental_skill_db.txt'.
[root@AsynjurRO trunk]#

**Comment by Dark8008** [comment]
Same with you, follow -> https://rathena.org/board/topic/103153-rathena-newest-version-map-server-has-crashed/#entry290012
