### ISSUE TITLE
Pre-re map server crash when changing to 4th job

### ISSUE THREAD

**Issue by Shaktohh** [rathena/rathena#6434]
* **rAthena Hash**: 7556453dfcd21180566ab56a891f628caa75e3db

* **Client Date**: 20200401

* **Server Mode**: Pre-Renewal

* **Description of Issue**: Change job in game to a 4th job and the map server crash

[Error]: Server received crash signal! Attempting to save all online characters!

**Comment by mundussan** [comment]
Hmmmm, are you trying to use 4th jobs in pre renewal mode? Or you mean after merging 4th jobs, your pre renewal got buggy?

**Comment by kaninhot004** [comment]
> Hmmmm, are you trying to use 4th jobs in pre renewal mode? Or you mean after merging 4th jobs, your pre renewal got buggy?

As I read, he want to use class 4 on pre-renewal.

**Comment by Shaktohh** [comment]
> Hmmmm, are you trying to use 4th jobs in pre renewal mode? Or you mean after merging 4th jobs, your pre renewal got buggy?

Yes i changed to a 4th jobs.
I guess if it shouldn't be allowed, there should be a safeguard.

**Comment by mundussan** [comment]
Well, afaik you can only use 3rd and 4rth jobs in pre renewal using the atcommand `@job`
But i never got an server map crash, my job only got recognized as novice 99.

**Comment by Shaktohh** [comment]
Here the full bt 
`Thread 1 "map-server" received signal SIGSEGV, Segmentation fault.
0x00005555557c6037 in pc_calc_skilltree_normalize_job (sd=0x555559b8a120) at /usr/include/c++/8/bits/shared_ptr_base.h:1018
1018          _M_get() const noexcept
bt full
#0  0x00005555557c6037 in pc_calc_skilltree_normalize_job (sd=0x555559b8a120) at /usr/include/c++/8/bits/shared_ptr_base.h:1018
        skill_point = 217
        novice_skills = 9
        c = 53508
        novice_job = std::shared_ptr<s_job_info> (use count 2, weak count 0) = {get() = <optimized out>}
#1  0x00005555557c6649 in pc_calc_skilltree (sd=sd@entry=0x555559b8a120) at /home/debian/rAthena/src/map/pc.cpp:2195
        job = <optimized out>
        class_ = <optimized out>
        job_id = <optimized out>
        __FUNCTION__ = "pc_calc_skilltree"
        flag = <optimized out>
        tree = <optimized out>
#2  0x0000555555906029 in status_calc_pc_sub (sd=0x555559b8a120, opt=SCO_NONE) at /home/debian/rAthena/src/map/status.cpp:4759
        calculating = 1
        base_status = <optimized out>
        sc = 0x555559b8a688
        b_skill = {{id = 0, lv = 0 '\000', flag = 0 '\000'}, {id = 1, lv = 9 '\t', flag = 0 '\000'}, {id = 0, lv = 0 '\000',
            flag = 0 '\000'}, {id = 0, lv = 0 '\000', flag = 0 '\000'}, {id = 0, lv = 0 '\000', flag = 0 '\000'}, {id = 0,
            lv = 0 '\000', flag = 0 '\000'}, {id = 0, lv = 0 '\000', flag = 0 '\000'}, {id = 0, lv = 0 '\000', flag = 0 '\000'}, {
            id = 0, lv = 0 '\000', flag = 0 '\000'}, {id = 9, lv = 10 '\n', flag = 0 '\000'}, {id = 0, lv = 0 '\000',
            flag = 0 '\000'}, {id = 0, lv = 0 '\000', flag = 0 '\000'}, {id = 12, lv = 10 '\n', flag = 0 '\000'}, {id = 0,
            lv = 0 '\000', flag = 0 '\000'}, {id = 0, lv = 0 '\000', flag = 0 '\000'}, {id = 0, lv = 0 '\000', flag = 0 '\000'}, {
            id = 0, lv = 0 '\000', flag = 0 '\000'}, {id = 0, lv = 0 '\000', flag = 0 '\000'}, {id = 0, lv = 0 '\000',
            flag = 0 '\000'}, {id = 0, lv = 0 '\000', flag = 0 '\000'}, {id = 0, lv = 0 '\000', flag = 0 '\000'}, {id = 0,
            lv = 0 '\000', flag = 0 '\000'}, {id = 22, lv = 10 '\n', flag = 0 '\000'}, {id = 23, lv = 10 '\n', flag = 0 '\000'}, {
            id = 24, lv = 1 '\001', flag = 0 '\000'}, {id = 25, lv = 1 '\001', flag = 0 '\000'}, {id = 26, lv = 2 '\002',
            flag = 0 '\000'}, {id = 27, lv = 4 '\004', flag = 0 '\000'}, {id = 28, lv = 10 '\n', flag = 0 '\000'}, {id = 29,
            lv = 10 '\n', flag = 0 '\000'}, {id = 30, lv = 10 '\n', flag = 0 '\000'}, {id = 31, lv = 1 '\001', flag = 0 '\000'}, {
            id = 32, lv = 10 '\n', flag = 0 '\000'}, {id = 33, lv = 10 '\n', flag = 0 '\000'}, {id = 34, lv = 10 '\n',
            flag = 0 '\000'}, {id = 35, lv = 1 '\001', flag = 0 '\000'}, {id = 0, lv = 0 '\000', flag = 0 '\000'} <repeats 18 times>,
          {id = 54, lv = 4 '\004', flag = 0 '\000'}, {id = 0, lv = 0 '\000', flag = 0 '\000'}, {id = 0, lv = 0 '\000',
            flag = 0 '\000'}, {id = 0, lv = 0 '\000', flag = 0 '\000'}, {id = 0, lv = 0 '\000', flag = 0 '\000'}, {id = 0,
            lv = 0 '\000', flag = 0 '\000'}, {id = 0, lv = 0 '\000', flag = 0 '\000'}, {id = 0, lv = 0 '\000', flag = 0 '\000'}, {
            id = 0, lv = 0 '\000', flag = 0 '\000'}, {id = 0, lv = 0 '\000', flag = 0 '\000'}, {id = 0, lv = 0 '\000',
 flag = 0 '\000'}, {id = 65, lv = 10 '\n', flag = 0 '\000'}, {id = 66, lv = 5 '\005', flag = 0 '\000'}, {id = 67,
            lv = 3 '\003', flag = 0 '\000'}, {id = 68, lv = 5 '\005', flag = 0 '\000'}, {id = 69, lv = 5 '\005', flag = 0 '\000'}, {
            id = 70, lv = 10 '\n', flag = 0 '\000'}, {id = 71, lv = 4 '\004', flag = 0 '\000'}, {id = 72, lv = 1 '\001',
            flag = 0 '\000'}, {id = 73, lv = 10 '\n', flag = 0 '\000'}, {id = 74, lv = 5 '\005', flag = 0 '\000'}, {id = 75,
            lv = 5 '\005', flag = 0 '\000'}, {id = 76, lv = 10 '\n', flag = 0 '\000'}, {id = 77, lv = 10 '\n', flag = 0 '\000'}, {
            id = 78, lv = 1 '\001', flag = 0 '\000'}, {id = 79, lv = 10 '\n', flag = 0 '\000'}, {id = 0, lv = 0 '\000',
            flag = 0 '\000'} <repeats 1370 times>}
        i = <optimized out>
        skill = <optimized out>
        refinedef = 0
        index = -1
        right_weapon = <optimized out>
        left_weapon = <optimized out>
        job_info = <optimized out>
#3  0x0000555555909c22 in status_calc_pc_ (sd=sd@entry=0x555559b8a120, opt=opt@entry=SCO_NONE)
    at /home/debian/rAthena/src/map/status.cpp:5936
        previous_st = 0x0
        ret = <optimized out>
#4  0x000055555590197a in status_calc_bl_ (bl=bl@entry=0x555559b8a120, flag=flag@entry=SCB_ALL, opt=opt@entry=SCO_NONE)
    at /home/debian/rAthena/src/map/status.cpp:7116
        b_status = {hp = 8678, sp = 1636, ap = 0, max_hp = 8678, max_sp = 1636, max_ap = 0, str = 104, agi = 103, vit = 104,
          int_ = 104, dex = 253, luk = 106, pow = 0, sta = 0, wis = 0, spl = 0, con = 0, crt = 0, eatk = 0, batk = 275,
          matk_min = 300, matk_max = 504, speed = 150, amotion = 134, adelay = 268, dmotion = 400, mode = 47103, hit = 352,
          flee = 202, cri = 363, flee2 = 116, def2 = 104, mdef2 = 156, aspd_rate = 1000, patk = 0, smatk = 0, res = 0, mres = 0,
          hplus = 0, crate = 0, def = 0 '\000', mdef = 0 '\000', def_ele = 0 '\000', ele_lv = 1 '\001', size = 1 '\001',
          race = 10 '\n', class_ = 0 '\000', rhw = {atk = 0, atk2 = 0, range = 1, ele = 0 '\000'}, lhw = {atk = 0, atk2 = 0,
            range = 1, ele = 0 '\000'}}
        status = 0x555559b8a610
#5  0x00005555557c07dd in pc_resetstate (sd=sd@entry=0x555559b8a120) at /home/debian/rAthena/src/map/pc.cpp:8734
No locals.
#6  0x00005555557d1365 in pc_jobchange (sd=sd@entry=0x555559b8a120, job=4256, upper=<optimized out>)
    at /home/debian/rAthena/src/map/pc.cpp:10264
        i = <optimized out>
        fame_flag = 0
        b_class = 53508
        previous_class = 260
#7  0x00005555556aa199 in atcommand_jobchange (fd=13, sd=0x555559b8a120, command=0x7fffffffdb60 "@job", message=0x7fffffffdc60 "4256")
    at /home/debian/rAthena/src/map/atcommand.cpp:1201
        job = 4256
        upper = 0
        text = <optimized out>
#8  0x00005555556a6f4d in is_atcommand (fd=fd@entry=13, sd=sd@entry=0x555559b8a120, message=message@entry=0x7fffffffe140 "@job 4256",
    type=type@entry=1) at /home/debian/rAthena/src/map/atcommand.cpp:12663
        command = "@job", '\000' <repeats 251 times>
        params = "4256", '\000' <repeats 251 times>
        output = "@job failed.", '\000' <repeats 84 times>, "\330\003\020[UU\000\000\210\031VWUU\000\000\370\003\020[UU\000\000\n&\233UUU\000\000 %\233UUU\000\000\000\337\377\377\377\177\000\000 \241\270YUU\000\000=\305vUUU\000\000\064\355\377\342\377\177\000\000\244WkUUU\000\000 \241\270YUU\000\000\220\251kUUU\000\000\030\000\000\000\000\000\000\000"...
        atcmd_msg = "@job 4256\000\377\377\377\177\000\000\270k\201\332\377\177\000\000\n\000\000\000\000\000\000\000@\342\377\377\377\177\000\000!\263%\367\377\177\000\000\001\200\255\373\377\177\000\000@\342\377\377\377\177\000\000@\342\377\377\377\177\000\000@\342\377\377\377\177\000\000@\342\377\377\377\177\000\000R\342\377\377\377\177\000\000\377\377\377\377\377\377\377\377@\342\377\377\377\177\000\000\377\377\377\377\377\377\377\377", '\000' <repeats 44 times>, "\200\000\000\000%\257vUUU\000\000\000\000\377\377\377\177\000\000\000\000\000\000\000\000\000\000(\340\377\377\063\060\071\063"...
        ssd = 0x555559b8a120
        info = <optimized out>
        is_atcommand = <optimized out>
#9  0x00005555556e430c in clif_process_message (sd=sd@entry=0x555559b8a120, whisperFormat=whisperFormat@entry=false,
    out_name=out_name@entry=0x7fffffffe120 "CharName", out_message=out_message@entry=0x7fffffffe140 "@job 4256",
    out_full_message=out_full_message@entry=0x7fffffffe240 "CharName : @job 4256") at /home/debian/rAthena/src/map/clif.cpp:10743
        seperator = 0x555555a6838b " : "
        fd = 13
        info = <optimized out>
        packetLength = <optimized out>
        inputLength = <optimized out>
        input = <optimized out>
        name = <optimized out>
        message = 0x7fffda816bc1 "@job 425", <incomplete sequence \360>
        nameLength = <optimized out>
        messageLength = <optimized out>
#10 0x000055555570ec39 in clif_parse_GlobalMessage (fd=13, sd=0x555559b8a120) at /home/debian/rAthena/src/map/clif.cpp:11676
        name = "CharName", '\000' <repeats 17 times>
        message = "@job 4256\000\000\000\000\000\000\000\000\000\242UUU\000\000\000\000\000\000\000\000\000\000\377\377\377\377\377\177\000\000\016\000\000\000\000\000\000\000\377\377\377\377\377\377\377\377`\023:\367\377\177", '\000' <repeats 11 times>, "\001", '\000' <repeats 14 times>, "\350\222vUUU\000\000%\000\000\000UU\000\000[L\004\354\377\177\000\000 \241\270YUU\000\000\020b\033\000\000\000\000\000 \000\000\000\r\000\000\000$\000\000\000\377\177\000\000\020\000\000\000\060\000\000\000\260\342\377\377\000\000\000\000\060\300xUUU\000\000h\342\377\377\377\177\000\000G\001\000\000\000\000\000\000\002\000\000\000\t\000\000\000\316\342\377\377\377\177\000\000"...
        output = "CharName : @job 4256\000\000\000\000\000\000\063\225vUUU\000\000\300\342\377\377\377\177\000\000 \000\000\000\060\000\000\000@\343\377\377\377\177\000\000\200\342\377\377\377\177\000\000\214\375g\332\377\177\000\000P\200\242\364\377\177\000\000\300\342\377\377\377\177\000\000\366\377.\367\377\177\000\000\360I\002\000\000\000\000\000^\235\030\231\002\000\000\000\322\342\377\377\377\177\000\000\324\342\377\377\377\177\000\000[L\004\354\377\177", '\000' <repeats 14 times>, "\001\000\000\000X\320\017[UU\000\000 \343\377\377\377\177\000\000\020=\375\367\377\177\000\000P\343\377\377\377\177\000\000\344ŐU\002\000\000\000\001\000\000\000\000\000\000\000`"...
        length = <optimized out>
        __FUNCTION__ = "clif_parse_GlobalMessage"
#11 0x00005555556e91ce in clif_parse (fd=13) at /home/debian/rAthena/src/map/clif.cpp:22610
        cmd = <optimized out>
        packet_len = 22
        sd = <optimized out>
        pnum = 0
        cmd = <optimized out>
        packet_len = <optimized out>
        sd = <optimized out>
        pnum = <optimized out>
#12 clif_parse (fd=13) at /home/debian/rAthena/src/map/clif.cpp:22471
        cmd = <optimized out>
        packet_len = <optimized out>
        sd = <optimized out>
#13 0x00005555559bc625 in do_sockets (next=<optimized out>) at /home/debian/rAthena/src/common/socket.cpp:1422
        rfd = {fds_bits = {8192, 0 <repeats 15 times>}}
        timeout = {tv_sec = 0, tv_usec = 8896}
        ret = <optimized out>
        i = 13
#14 0x000055555567b54a in main (argc=1, argv=0x7fffffffe5c8) at /home/debian/rAthena/src/common/core.cpp:383
        next = <optimized out>
`

**Comment by mundussan** [comment]
Maybe they can do a verify for it, but at that debug u sent the atcommand job is already throwing an error...

**Comment by Shaktohh** [comment]
That's not how a stacktrace is working, please let the thread clear to let ppl fix it

**Comment by Anjuts** [comment]
4th job is not yet supported.

**Comment by Lemongrass3110** [comment]
"not yet" is the wrong phrasing. It will never be supported in pre-renewal.
I will add some additional safeguards to prevent changing to them though.
