### ISSUE TITLE
ResetSkill command cause have exceed skill points.

### ISSUE THREAD

**Issue by sonniez** [rathena/rathena#6436]
* **rAthena Hash**: 

bdf568979dd53702494d3a6b3b9d35054c44594a

* **Client Date**: 20200902

* **Server Mode**: Renewal

* **Description of Issue**: When Reset Skill at the NPC (npc/custom/resetnpc.txt), there will have exceed skill point (300++ points).
  * Result: 
  * Expected Result: It have to get skill point as normal.
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by secretdataz** [comment]
I got some reports that this issue occurs after 7556453dfcd21180566ab56a891f628caa75e3db (4CrAm merge).

**Comment by Lemongrass3110** [comment]
Can you tell us which jobs are affected?
Normal?
Rebirth?
Third?
Fourth?

**Comment by randell1993** [comment]
I can confirm this, It happens to all classes as some of my players are having issues that they cannot change job cause they are getting alot of skills points when resetting. I think this affects all jobs (I first noticed it in 4CrAM) cannot replicate it myself but it does happen. sometimes on stats too.

**Comment by sonniez** [comment]
Sorry, I just found it recently that how it work. If you're leveling normally, it's fine to resetskill. but if you are use @allskill command they will be exceed skill point when resetskill(skill point reclaimed equal every skill point used). I'm quite sure that before 4CrAm merge there's not have a problem with @allskill command and resetskill.

Here's a sample that what I mean (Magician Class have to use 121 skill point to reach max level of every skill)
![image](https://user-images.githubusercontent.com/55048965/147880710-60ebd01b-90c1-4618-8759-609901e7e843.png)

**Comment by Lemongrass3110** [comment]
Does this happen without `@allskills` and/or `@skpoint` usage as well?

I can only confirm that it works "as intended" if you abuse your GM powers.

**Comment by randell1993** [comment]
Yes it is happening with without the usage of those commands above.

**Comment by Lemongrass3110** [comment]
@randell1993 mind giving us the steps to reproduce this?

**Comment by randell1993** [comment]
Hmmm it is completely random, I myself cannot reproduce this issue but players who use the reset npc (resetskill) command, sometimes will get those extra skill points and since they have those extra points already, even with resetskill they would be stuck with that amount.

It was reported by the player base due to some players can't change job because of the amount of skills points they have.

**Comment by Lemongrass3110** [comment]
And i guess you did not check which jobs are involved?

**Comment by randell1993** [comment]
Hmmm so far these jobs usually, well maybe it is the most used job but for the sake it was seen on Rune knight, Guillotine Cross and sometimes their 4th job counterpart I believe there are also some other jobs. but mostly those yeah.

**Comment by sonniez** [comment]
> Does this happen without `@allskills` and/or `@skpoint` usage as well?
> 
> I can only confirm that it works "as intended" if you abuse your GM powers.

It doesn't happen without @allskills or @skpoint. Player can use "resetskill" script command totally fine unless you're gaining extra skill point or exceed skill up. I have tested it yesterday.

**Comment by laziem** [comment]
Just happen on mine.
Job: Rune Knight. When reset skill, he got lot of skill point. Increased all skill and still have 116 skill point left.
I don't know how to reproduce also.

**Comment by Lemongrass3110** [comment]
No reports for over a year.
