### ISSUE TITLE
effect of Solar Sword not stack with hunter fly card x4 cards (Guillotine Cross)

### ISSUE THREAD

**Issue by normally-00** [rathena/rathena#6444]
Rathena Hash : 09dcb2c
Mode : renewal
Date : 6-Jan-2022
Client : update 6-Jan-2022 from normal patch update
I use guillotine cross and when I will absorb HP from phys damage by use effect of solar sword with hunter fly card 4cards
I can't use two effect stack (solar sword with hunter fly card)
I both use normal attack and Cross Impact skill but it absorb Hp 1% only (effect of solar sword working only and hunter fly effect not stack)

I find this but I 'm not sure
Is it bug? or have update about two effect stack 
(It old effect combo that effect of hunter fly will increase amount  HP absorb rate from solar sword when equip together)
thank you very much
![screenrAthena025](https://user-images.githubusercontent.com/67834920/148341288-55089889-7d87-4853-a67a-782943808c12.jpg)
![screenrAthena030](https://user-images.githubusercontent.com/67834920/148341292-59a9c7f8-f6ab-4451-92f7-52dfb1abc438.jpg)
![screenrAthena031](https://user-images.githubusercontent.com/67834920/148341294-c3eb0714-9aae-449c-828c-56b3ebc24260.jpg)

**Comment by attackjom** [comment]
I think that's not bug because in official server solar sword won't stack with other lifesteal item too.
