### ISSUE TITLE
LG_OVERBRAND bSkillcooldown - milliseconds Doesnt work

### ISSUE THREAD

**Issue by randell1993** [rathena/rathena#6445]
* **rAthena Hash**: 6b71441

* **Client Date**: 20210107

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: For some reason LG_OVERBRAND skill doesn't accept negative bSkillcooldown but does increase Cooldown when positive
  * Expected Result: Negative Value should decrease the cooldown
  * How to Reproduce: Wear an item with bonus2 bSkillCooldown,"LG_OVERBRAND",-2000; <- this doesn't work
  bonus2 bSkillCooldown,"LG_OVERBRAND",2000; <- this adds 2 seconds

Tested on other skills like  bonus2 bSkillCooldown,"LG_CANNONSPEAR",-2000; It works here and only Overbrand doesn't accept the cooldown reduction.

**Comment by laziem** [comment]
Unlike jRO, kRO Overbrand doesn't have any cooldown.

**Comment by randell1993** [comment]
https://github.com/rathena/rathena/blob/master/db/re/skill_db.yml

and that doesn't change the issue where there is a skill i.e. Overbrand that cannot have a decrease in cooldown am I right?

**Comment by randell1993** [comment]
> Unlike jRO, kRO Overbrand doesn't have any cooldown.

Okay I am dumb I tried fixing this all day and reviewing the skill database showed that Overbrand has ACD rather than CD.
