### ISSUE TITLE
Episode 15.2 : Infinite Space

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#6448]
**Missing Official Content**
2014.10.28 - Infinite Space								https://ro.gnjoy.com/news/update/View.asp?seq=159&curpage=5

- [x] Instance / NPCs
- [x] Monsters / Skills
- [x] Items

**Comment by hannicaldummy** [comment]
- [ ] Monsters
- [ x ] Items
- [ ] Monsters Skills
- [ ] Instance NPCs

**Comment by hannicaldummy** [comment]
Monsters PR https://github.com/rathena/rathena/pull/6491

**Comment by Balferian** [comment]
Maybe add this update too in list?
2015.07.01 - Infinite Space: Update https://ro.gnjoy.com/news/update/View.asp?seq=170

**Comment by Everade** [comment]
Fixed in https://github.com/rathena/rathena/pull/6554
