### ISSUE TITLE
Episode 17.1 : Illusion

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#6463]
**Missing Official Content**
- [x] 2018.07.18 - Episode 17.1								https://ro.gnjoy.com/news/update/View.asp?seq=224&curpage=2

**Comment by Dieby** [comment]
https://github.com/crazy-arashi/Rathena-Script-Collection/tree/master/Episode%2017.1%20-%20Illusion

**Comment by rakhool** [comment]
![rathena17 1error](https://user-images.githubusercontent.com/100949409/163233457-0c100b2d-8946-49dd-bcdb-82db4d4cac31.jpg)
map server crash using the npc for weapon mods.
