### ISSUE TITLE
Readparam doesn't read variables

### ISSUE THREAD

**Issue by llchrisll** [rathena/rathena#647]
readparam doesn't read variables like BaseLevel, only numbers set in db/const.txt

**Comment by llchrisll** [comment]
@Off-Topic: screw that enter button xD
Title: readparam
Description: readparam doesn't read variables like BaseLevel, only numbers set in db/const.txt

**Comment by dastgir** [comment]
readparam(BaseLevel)
No quotes....
It should work.

**Comment by llchrisll** [comment]
Well I have to add that my revision is from june I think, if it was fixed already, I'm sorry. 
Well it prints with the variable a 0 and with the id the level

**Comment by nanakiwurtz** [comment]
@llchrisll So you're saying that it's working for you then?

**Comment by llchrisll** [comment]
It does work, but not with the variables like the one mentioned above.

**Comment by cydh** [comment]
'variable' that u meant is defined as a param, doesn't need `readparam` to get the value.
````
StatusPoint	9	1
BaseLevel	11	1
SkillPoint	12	1
Class	19	1
Upper	56	1
Zeny	20	1
Sex	21	1
Weight	24	1
MaxWeight	25	1
JobLevel	55	1
BaseExp	1	1
JobExp	2	1
Karma	3	1
Manner	4	1
NextBaseExp	22	1
NextJobExp	23	1
Hp	5	1
MaxHp	6	1
Sp	7	1
MaxSp	8	1
BaseJob	119	1
BaseClass	120	1
killerrid	121 1
killedrid	122 1
Sitting	123	1
CharMoves	124	1
CharRename	125	1
Font		126	1
BankVault	127	1
RouletteBronze	128	1
RouletteSilver	129	1
RouletteGold	130	1
````

if you do that because of the doc said, let's say, we have been fooled. xD because of this part.
>Some example parameters:
>
>StatusPoint, BaseLevel, SkillPoint, Class, Upper, Zeny, Sex, Weight, MaxWeight,
>JobLevel, BaseExp, JobExp, NextBaseExp, NextJobExp, Hp, MaxHp, Sp, MaxSp,
>BaseJob, Karma, Manner, bVit, bDex, bAgi, bStr, bInt, bLuk

**Comment by llchrisll** [comment]
Well, I just wanted to know if it's an misunderstanding on my part or an bug.
Because a bit below at the examples, the param was used (bVit). Since I'm aware of it now, I will be using the id's from now on.

**Comment by cydh** [comment]
no no, it's not misunderstanding, it's an annoyance!
