### ISSUE TITLE
Episode 17.2 : Refine/Enchant Update

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#6473]
**Missing Official Content**
- [x] 2020.09.09 - Refinement System Update
- [x] 2020.09.09 - Enchant UI

**Official Source**
https://ro.gnjoy.com/event/2020/09/0909_ro1_4thOccupation_final/

**Comment by Lemongrass3110** [comment]
Refine information was added in 04d9e33
Enchant(grade) UI was added in 001981c
