### ISSUE TITLE
Episode 17.2 : 5 New Dungeons

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#6474]
**Missing Official Content**
- [x] 2020.09.16 - 5 New Dungeons								https://ro.gnjoy.com/news/update/View.asp?seq=249&curpage=1

**Comment by Rayvakarian** [comment]
I heard that RO offline pack has 16.2 - 17.2 episodes content (mobs, drop, quests, isntances, etc). You can use it as a source

**Comment by Everade** [comment]
> I heard that RO offline pack has 16.2 - 17.2 episodes content (mobs, drop, quests, isntances, etc). You can use it as a source

Feel free to help us.

**Comment by Atemo** [comment]
Implemented (read the references above)
