### ISSUE TITLE
Episode 18 : Direction of Prayer

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#6479]
**Missing Official Content**
- [x] 2021.02.01 - Episode 18 - Direction of Prayer				https://ro.gnjoy.com/news/update/View.asp?seq=259&curpage=1

**Comment by rainer8989** [comment]
Have any 18 episode scripts already?

**Comment by AbsoluteXeroEX** [comment]
> 

Some servers appear to have them. Not sure if they're here in the repo, though.
