### ISSUE TITLE
callsub variables value cannot be inherited

### ISSUE THREAD

**Issue by CairoLee** [rathena/rathena#648]
step 1: /origanize TestTeam
step 2: talk with this npc
```
prontera,119,75,4	script	TestCallSub	123,{
	set .@party_id,getcharid(1);
	set .@p_name$,getpartyname(.@party_id);

	mes "[TestCallSub]";
	mes "Party ID: " + .@party_id;
	mes "Party Name: " + .@p_name$;
	next;
	callsub L_Enter;
	close;
L_Enter:
	mes "[TestCallSub]";
	mes "Try to read .@p_name$ again:";
	mes "Party ID: " + .@party_id;  // return 0, it's error
	mes "Party Name: " + .@p_name$;    // return empty,need to be TestTeam
	close;
}
```

**Comment by CairoLee** [comment]
npc\instances\EndlessTower.txt has the same problem

**Comment by dastgir** [comment]
Of course ,.@ are scope variables, they act this way only

**Comment by CairoLee** [comment]
i think so.
it's not they act before 0696125 commit.

these instance all have same problem in they L_Enter label:

npc\instances\EndlessTower.txt  -- L_Enter
```mapannounce "e_tower", strcharinfo(0)+" of the party, "+*.@p_name$*+", is entering the dungeon, Endless Tower.",bc_map,"0x00ff99",FW_NORMAL,12;```

npc\instances\OrcsMemory.txt
```mapannounce "gef_fild10",*.@p_name$*+" party's member "+strcharinfo(0)+" has entered the Orc's Memory.",bc_map,"0x00ff99";```

npc\re\instances\MalangdoCulvert.txt
```mapannounce "mal_in01", strcharinfo(0)+" of the party "+getpartyname(*.@party_id*)+" is entering the Culvert.",bc_map,"0x00ff99";```

**Comment by dastgir** [comment]
I guess that instance were not working from start or scope variables were wrong before it.

**Comment by anacondaqq** [comment]
```
".@"     - A scope variable.
           They are unique to the instance and scope. Each instance has its 
           own scope that ends when the script ends. Calling a function with 
           callsub/callfunc starts a new scope, returning from the function 
           ends it. When a scope ends, its variables are converted to values 
           ('return .@var;' returns a value, not a reference).
```
sorry for offtop, but this is interesting... Anyone, can explain?

**Comment by dastgir** [comment]
When we call callsub, it creates new instance of script.
But we can pass value by 
.@a = callsub(OnAnyLabel,.@var1,.@var2);
And use it in OnAnyLabel by
getarg(0) and so on....
And you can pass from OnAnyLabel by
return .@AnyVariable;
And it will be stored in .@a.


That's how it used to work and that is how it is working now...

**Comment by CairoLee** [comment]
i know this, thanyou @dastgir .
but i still think, if the script engine was upgraded, then all of the old script need to update. 
if don't update the old script, then old script may using the wrong way for .@ variables. 

bad english....sorry

```
before 0696125b8269dd87fcb9f7c483064e578e338c60 commit
the test script is work.

after 0696125b8269dd87fcb9f7c483064e578e338c60 commit
the test script is not work.

and we have a lot of the script, like npc\instances\EndlessTower.txt, they still using the old way to control .@ variables.

i think the old script need to be update, or the script engine need support the .@ , let them can be inherited. 
```

**Comment by CairoLee** [comment]
i run more test.
i think the script engine is work fine.

but some instances script need to update.

**Comment by aleos89** [comment]
An issue with using scopes is all.

**Comment by Atemo** [comment]
It should be fixed for the instance part <3
