### ISSUE TITLE
macOS error: MySQL not found or incompatible

### ISSUE THREAD

**Issue by pderiy** [rathena/rathena#6489]
Describe the bug
I have mysql on my Mac. Using latest macOS (Monterey 12.1).
And trying to run project following readme installation guide.

To Reproduce
- pull this repo
- run './configure'

Expected behavior
configure should pass
Screenshots
![image](https://user-images.githubusercontent.com/9549383/148692170-dd4b730a-7fc5-4972-be25-11dd29598cd5.png)
![image](https://user-images.githubusercontent.com/9549383/148692177-32dfa256-13f9-4ec4-ae37-e898713619cf.png)

**Comment by Lemongrass3110** [comment]
Github should not be used for support.
Please use the forums or discord for this.

As for your problem:
On mac OS you need to run configure with the "--with_mysql <path>" parameter.

**Comment by pderiy** [comment]
@Lemongrass3110 
tried with './configure --with-mysql=/usr/local/bin/mysql_config'
It looks like without that prefix it also find mysql_config.

I think maybe something wrong with configure script. And it would be nice to have Mac OS installation guide
