### ISSUE TITLE
Add AP in percentheal

### ISSUE THREAD

**Issue by RagnaWay** [rathena/rathena#6492]
**Describe the solution you'd like**

With the official command you can restore HP and SP, so it would be very interesting to add AP in the same role.

Example: `percentheal HP,SP,AP;` =  `percentheal 100,100,100;`

thank you **Maple** for the idea.

**Comment by aleos89** [comment]
While this will eventually need to be added, the only problem with utilizing the current commands (IE: percentheal, heal, etc) is that the final optional argument on these is the character ID. This means we'd most likely end up having to do percentheal2, heal2, etc. which is not a very elegant solution.

**Comment by Atemo** [comment]
How about breaking the rule saying the char id should be the last argument and update the command to make it uglier?
`percentheal <hp>,<sp>{,<char_id>,<ap>};`

**Comment by aleos89** [comment]
The -100~100 checks for percent heal work good for checking the character ID but the other heal functions that heal a specific value won't work well in this case for anything over that starting character value.

**Comment by Lemongrass3110** [comment]
Oh well true. I was only thinking about percentheal now.
Since Rytech added a new atcommand for apheal as well and it is not included with the normal "heal", should we create additional script commands too?

**Comment by aleos89** [comment]
Yeah, I was thinking then the only other solution aside from “2” would be just “apheal” or “healap”.
