### ISSUE TITLE
Friends list will disappear when re-login to the game

### ISSUE THREAD

**Issue by voyfmyuh** [rathena/rathena#6494]
rAthena Hash:
https://github.com/rathena/rathena/commit/dcd01a0fa52a8bfcab8d810401ee87b927796d3c

Client Date:
20211103

Server Mode:
Renawal

Description of Issue:
The friend list will disappear when you log back into the game and the value of friend_id will be changed to 131072

![螢幕擷取畫面 2022-01-11 062852](https://user-images.githubusercontent.com/54499336/148849192-710ea9fe-3439-49f6-b81a-97d4d76143af.png)

**Comment by CairoLee** [comment]
When we add a lot of the skills of the 4th-jobs, the original maximum number of skills becomes 1453, while the MAX_SKILL is still limited to 1450. This causes the program to incorrectly reset the `sd->status.friends` data in `pc_calc_skilltree`.

Please adjust `MAX_SKILL` in mmo.hpp to 1460 and try again.
