### ISSUE TITLE
Level 2 Shields are not recognized by skills as shield

### ISSUE THREAD

**Issue by Relliksuriv** [rathena/rathena#6497]
* **rAthena Hash**: dcd01a0

* **Client Date**: 20211103

* **Server Mode**: Renewal

* **Description of Issue**: Level 2 Shields are not seen as shield by skills that require shield e.g reflect shield, auto guard and all other skills
  * Result: 
  * Expected Result: Wearing Level 2 shields should enable you to cast this skills 
  * How to Reproduce: Wear any Level 2 shields e.g Penitentia Aegis, Mad Bunny LT
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by laziem** [comment]
looks the item missing their View field. Try add `View: 1`
