### ISSUE TITLE
View other player equipment cause map server crash

### ISSUE THREAD

**Issue by kaninhot004** [rathena/rathena#6509]
* **rAthena Hash**: 

0d8118ced

* **Client Date**: 

2021-11-03

* **Server Mode**: 

Renewal

* **Description of Issue**: 
  * Result: Right-click on other players -> View equipment -> Map Server crash
  * Expected Result: View equipment work fine.

*There are no crash logs from me yet, I will try find it when available.

**Comment by sonniez** [comment]
Confirmed.

**Comment by Anjuts** [comment]
Confirmed
