### ISSUE TITLE
Warnings after updating to Git Hash: '0b568eba7e1570c4dc7711ee2d79b26aa8232fa5'

### ISSUE THREAD

**Issue by lordganja** [rathena/rathena#651]
I'm having these warnings after I updated to Git Hash: '0b568eba7e1570c4dc7711ee2d79b26aa8232fa5'
 
i'm using pre-renewal.

[Warning]: quest_read_txtdb: Invalid monster as objective '2197' in line 60.
[Warning]: quest_read_txtdb: Invalid item reward '6520' (mob 2314, optional) in line 68.
[Warning]: quest_read_txtdb: Invalid item reward '6520' (mob 2314, optional) in line 69.
[Warning]: quest_read_txtdb: Invalid item reward '6520' (mob 2314, optional) in line 70.
[Warning]: quest_read_txtdb: Invalid item reward '6520' (mob 2314, optional) in line 71.
[Warning]: quest_read_txtdb: Invalid monster as objective '2313' in line 74.
[Warning]: quest_read_txtdb: Invalid item reward '6522' (mob 2364, optional) in line 108.
[Warning]: quest_read_txtdb: Invalid monster as objective '2367' in line 117.
[Warning]: quest_read_txtdb: Invalid item reward '6522' (mob 2364, optional) in line 119.
[Warning]: quest_read_txtdb: Invalid monster as objective '2319' in line 328.
[Warning]: quest_read_txtdb: Invalid monster as objective '2355' in line 331.
[Warning]: quest_read_txtdb: Invalid monster as objective '2360' in line 334.
[Warning]: quest_read_txtdb: Invalid monster as objective '2363' in line 627.
[Warning]: quest_read_txtdb: Invalid item reward '6498' (mob 2316, optional) in line 1215.
[Warning]: quest_read_txtdb: Invalid monster as objective '2314' in line 1217.
[Warning]: quest_read_txtdb: Invalid monster as objective '2311' in line 1217.
[Warning]: quest_read_txtdb: Invalid item reward '6510' (mob 2310, optional) in line 1221.
[Warning]: quest_read_txtdb: Invalid item reward '6510' (mob 2310, optional) in line 1226.
[Warning]: quest_read_txtdb: Invalid monster as objective '2316' in line 1228.
[Warning]: quest_read_txtdb: Invalid item reward '6507' (mob 2309, optional) in line 1230.
[Warning]: quest_read_txtdb: Invalid item reward '6507' (mob 2313, optional) in line 1230.
[Warning]: quest_read_txtdb: Invalid item reward '6507' (mob 2314, optional) in line 1230.
[Warning]: quest_read_txtdb: Invalid monster as objective '2309' in line 1233.
[Warning]: quest_read_txtdb: Invalid monster as objective '2363' in line 1258.
[Warning]: quest_read_txtdb: Invalid monster as objective '2364' in line 1258.
[Warning]: quest_read_txtdb: Invalid monster as objective '2327' in line 1629.
[Warning]: quest_read_txtdb: Invalid monster as objective '2363' in line 1667.
[Warning]: quest_read_txtdb: Invalid monster as objective '2364' in line 1667.
[Warning]: quest_read_txtdb: Invalid monster as objective '2327' in line 2068.
[Warning]: quest_read_txtdb: Invalid monster as objective '2132' in line 2314.
[Warning]: quest_read_txtdb: Invalid monster as objective '2133' in line 2315.
[Warning]: quest_read_txtdb: Invalid monster as objective '2134' in line 2316.
[Warning]: quest_read_txtdb: Invalid monster as objective '2136' in line 2317.
[Warning]: quest_read_txtdb: Invalid monster as objective '2137' in line 2318.
[Warning]: quest_read_txtdb: Invalid monster as objective '2176' in line 2348.
[Warning]: quest_read_txtdb: Invalid monster as objective '2175' in line 2349.
[Warning]: quest_read_txtdb: Invalid monster as objective '2174' in line 2350.
[Warning]: quest_read_txtdb: Invalid monster as objective '2178' in line 2351.
[Warning]: quest_read_txtdb: Invalid monster as objective '2179' in line 2352.
[Warning]: quest_read_txtdb: Invalid monster as objective '2177' in line 2353.
[Warning]: quest_read_txtdb: Invalid monster as objective '2182' in line 2354.
[Warning]: quest_read_txtdb: Invalid monster as objective '2181' in line 2355.
[Warning]: quest_read_txtdb: Invalid monster as objective '2180' in line 2356.
[Warning]: quest_read_txtdb: Invalid monster as objective '2183' in line 2357.
[Warning]: quest_read_txtdb: Invalid monster as objective '2184' in line 2358.
[Warning]: quest_read_txtdb: Invalid monster as objective '2185' in line 2359.
[Warning]: quest_read_txtdb: Invalid monster as objective '2188' in line 2360.
[Warning]: quest_read_txtdb: Invalid monster as objective '2187' in line 2361.
[Warning]: quest_read_txtdb: Invalid monster as objective '2190' in line 2362.
[Warning]: quest_read_txtdb: Invalid monster as objective '2189' in line 2363.
[Warning]: quest_read_txtdb: Invalid monster as objective '2322' in line 2370.
[Warning]: quest_read_txtdb: Invalid monster as objective '2475' in line 2397.
[Warning]: quest_read_txtdb: Invalid monster as objective '2476' in line 2398.
[Warning]: quest_read_txtdb: Invalid monster as objective '2365' in line 2455.
[Warning]: quest_read_txtdb: Invalid monster as objective '2083' in line 2553.
[Warning]: quest_read_txtdb: Invalid monster as objective '2084' in line 2555.
[Warning]: quest_read_txtdb: Invalid monster as objective '2085' in line 2557.
[Warning]: quest_read_txtdb: Invalid monster as objective '2086' in line 2559.

**Comment by aleos89** [comment]
That's because those mobs/items don't exist in the pre-renewal database.
