### ISSUE TITLE
Vending cannot show correct item and price

### ISSUE THREAD

**Issue by kaninhot004** [rathena/rathena#6510]
![image](https://user-images.githubusercontent.com/9493525/149271855-b14f44f3-9d78-4305-8ac0-fe2c95260859.png)

* **rAthena Hash**: 

0d8118ced

* **Client Date**: 

2021-11-03

* **Server Mode**: 

Renewal

* **Description of Issue**: 
  * Result: Use vending skill -> Put an item to sell and set item price -> Check item and price.
  * Expected Result: Vending can be use and show correct item and price.

**Comment by sonniez** [comment]
Confirmed.

**Comment by RagnaWay** [comment]
True 
![image](https://user-images.githubusercontent.com/53480357/149384263-699c4fb3-d6b3-4d8e-81ff-e36994456359.png)

**Comment by Anjuts** [comment]
yes

**Comment by Benq28021997** [comment]
![grafik](https://user-images.githubusercontent.com/88672648/149407353-2f38ebc0-08cd-47bd-b638-0c7c37fbd62d.png)

Npc same

**Comment by pigati23** [comment]
> > ![grafik](https://user-images.githubusercontent.com/88672648/149407353-2f38ebc0-08cd-47bd-b638-0c7c37fbd62d.png) Npc same
> > 
> > I think it is because of the 2021 support
> > 
> > live server without 2021 no problem
> > 
> > test server with 2021 problem
> 
> npc working for me
> Buy:
> ![image](https://user-images.githubusercontent.com/53480357/149408952-df0a2ec9-5579-4dd0-88bf-3be4fe88444a.png)
> Sell:
> ![image](https://user-images.githubusercontent.com/53480357/149409329-aaa56057-d179-4302-9519-26980a9ca930.png)
> 
> 

Vending Skill.

**Comment by Lemongrass3110** [comment]
> ![grafik](https://user-images.githubusercontent.com/88672648/149407353-2f38ebc0-08cd-47bd-b638-0c7c37fbd62d.png) Npc same
> 
> I think it is because of the 2021 support
> 
> live server without 2021 no problem
> 
> test server with 2021 problem

I think you use wrong packet version here. It works correctly for me.
