### ISSUE TITLE
NPC: callshop "shop_name",1; end; -> freewalk, can talk to another npc, etc bugs.

### ISSUE THREAD

**Issue by anacondaqq** [rathena/rathena#652]
### Related to: https://github.com/rathena/rathena/issues/503
**This bug not fixed.** 

### Let me Explain a bug:
![](http://i.imgur.com/nRAAQ9D.gif)

**END;** command after any "callshop" in scripts will open this bug.

### How reproduce
```
/*
 * 1. Callshop Bugs 
 * ANY shops opened via callshop, and what have at the end "end", these shops will have this bug described
 * on the screenshot (freewalking, clicking another npc, do anything)
 */


prontera,155,180,5	script	CallShopBug	89,{
	
	switch(select("Open Shop", "Something", "Something2 "))
	{
		case 1:
			callshop "someshop",1;	// open shomeshop with buy list
			break;
		case 2:
			mes "doesnot matter what";
			break;
		case 3:
			mes "dummy data";
			break;
	}
	end;

}

-	shop	someshop	89,505:10000,506:6000,507:7000
```

## OR 

try to use any script based shops ([Euphy's Quest](https://github.com/rathena/rathena/blob/master/npc/custom/quests/quest_shop.txt) Shop for example)

## Refference
1. https://rathena.org/board/topic/96389-callshop-bug/
2. https://rathena.org/board/tracker/issue-8012-player-in-shop-state-npc-script-able-to-move-and-execute-other-npc-script/
3. https://www.youtube.com/watch?v=wn7XztJCHgg
#### 1. 
Regarding to this: https://github.com/rathena/rathena/issues/503
@aleos89 suggest to use ignoretimeout, but sorry, this is not working.
I can use 
> ignoretimeout 1; 

or
 
> ignoretimeout 0;

at any part of the script (i have enabled by default SECURE_TIMEOUT in sources)

and nothing will be happened, this will not help against this bug.

#### 2.
i was try totally to disable SECURE_TIMEOUT -> the bug still exist

#### 3.
i was try to add "sleep 1;" between callshop "something",1; and end; and it's works, but not on all scripts. + i found another funny bug.

#### Funny Bug related to **3.**

How reproduce:
1. Load Euphy Quest Shop
2. Find these lines
```
	dispbottom "Select one item at a time.";
	callshop "qshop"+@shop_index,1;
	npcshopattach "qshop"+@shop_index;
	end;
```
3. Replace to these lines:
```
	dispbottom "Select one item at a time.";
	callshop "qshop"+@shop_index,1;
	npcshopattach "qshop"+@shop_index;
	sleep 1;
	end;
```
4. You will see this bug (on gif) (you can't walk while you in shop, or you can't talk to NPC, and after closing shop, and again clicking on NPC, npc will hide, and after @refresh we will see it again)
![](http://i.imgur.com/sNbcWbq.gif)

## Technical Information
1. **Client Date**: 2012-04-10
2. **Rathena revision**: https://github.com/rathena/rathena/commit/230811c8abab0b1162b4409e3e6936dd75bdc8e5
3. **Mechanic**: Pre-re
4. Packet_ver: 30
5. without source modifications or client modifications

**Comment by aleos89** [comment]
The 'ignoretimeout' script command is meant to stop a NPC from using the timer to automatically close the script which is related to another issue. Seems I mixed the two up. I'll look into this again.

**Comment by cydh** [comment]
we just need more check for `sd->npc_shopid`

**Comment by CairoLee** [comment]
i using the same client(2015-05-13), 3ceam is fine(r788).
here is them svn address:
http://svn.code.sf.net/p/v1-3ceam/code/trunk

------------

in 3ceam, when use the callshop, then player can't move in the game.
is anybody can find out the reason?

------------

@icxbb-xx @cydh @aleos89

**Comment by CairoLee** [comment]
last commit is https://github.com/rathena/rathena/commit/0212d44bb4cac01a4fb1dc8e7e21443eadee13f3

please reopen this isuse @cydh

**Comment by icxbb-xx** [comment]
Try check in https://github.com/rathena/rathena/commit/8b3b32e0007255bd7cde1a936bd006cc7e66f7b7

**Comment by CairoLee** [comment]
@icxbb-xx  thankyou.
now when using the callshop to open a shop, then player can't move now.

buy has an new problem, npcshopattach not work now.....

```
prontera,155,180,5	script	CallShopBug	89,{
    switch(select("Open Shop", "Something", "Something2 "))
    {
        case 1:
            callshop "someshop",1;  // open shomeshop with buy list
            npcshopattach "someshop";
            break;
        case 2:
            mes "doesnot matter what";
            break;
        case 3:
            mes "dummy data";
            break;
    }
    end;
OnBuyItem:
	@cost = 0;
	for (.@i = 0; .@i < getarraysize(@bought_nameid); .@i++)
	{
		dispbottom "OnBuyItem: " + @bought_nameid[.@i] + " x " + @bought_quantity[.@i];
	}
	end;
}

-	shop	someshop	89,505:10000,506:6000,507:7000
```

**Comment by CairoLee** [comment]
@icxbb-xx Can you find out why 3ceam is work fine please?

**Comment by icxbb-xx** [comment]
@CairoLee , I think script you wrong

change to this
```
        case 1:
            callshop "someshop",1;  // open shomeshop with buy list
            npcshopattach "someshop";
            break;
```
to
```
        case 1:
            npcshopattach "someshop";
            callshop "someshop",1;  // open shomeshop with buy list
            break;
```

**Comment by CairoLee** [comment]
@icxbb-xx i think this is no my mistake, because they has the same usage

npc\custom\quests\hunting_missions.txt
line: 143

```
	case 5:
		mes "[Hunting Missions]";
		mes "You have ^0055FF" + #Mission_Points + "^000000 Mission Points.";
		mes "Use them well!";
		callshop "mission_shop",1;
		npcshopattach "mission_shop";
		end;
```

npc\custom\quests\quest_shop.txt
line: 107

```
	dispbottom "Select one item at a time.";
	callshop "qshop"+@shop_index,1;
	npcshopattach "qshop"+@shop_index;
	end;
```

**Comment by icxbb-xx** [comment]
@CairoLee  oh, i have test in game but why it normal in script you post

![screenrathena test002](https://cloud.githubusercontent.com/assets/3500355/11611530/aa14e2e4-9c05-11e5-9d6a-19cef5bee2c8.jpg)

show detail in chat
![screenrathena test003](https://cloud.githubusercontent.com/assets/3500355/11611531/ad358712-9c05-11e5-98ec-4225725940d4.jpg)

...
        case 1:
            callshop "someshop",1;  // open shomeshop with buy list
            npcshopattach "someshop";
            break;
...

**Comment by CairoLee** [comment]
@icxbb-xx that's very strange... i still can reproduce this.

![qq20151206-1](https://cloud.githubusercontent.com/assets/4458917/11611563/5e2b3b30-9c0f-11e5-8aea-5973d1aad227.png)

**Comment by CairoLee** [comment]
I have a date with my wife , now I must leaving.  When I go home, I will test it again. 

thankyou @icxbb-xx

**Comment by CairoLee** [comment]
@icxbb-xx Hi, I'm back.

rAthena Githash:  https://github.com/rathena/rathena/commit/8b3b32e0007255bd7cde1a936bd006cc7e66f7b7
Client Version: 2015-05-13 and 2013-08-07
PACKET_OBFUSCATION: Enabled

npc\scripts_custom.conf add new line:
npc: npc/test.txt

put the script in npc/test.txt:
```
prontera,155,180,5	script	CallShopBug	89,{
    switch(select("Open Shop", "Something", "Something2 "))
    {
        case 1:
            callshop "someshop",1;  // open shomeshop with buy list
			npcshopattach "someshop";
            break;
        case 2:
            mes "doesnot matter what";
            break;
        case 3:
            mes "dummy data";
            break;
    }
    end;
OnBuyItem:
	@cost = 0;
	for (.@i = 0; .@i < getarraysize(@bought_nameid); .@i++)
	{
		dispbottom "OnBuyItem: " + @bought_nameid[.@i] + " x " + @bought_quantity[.@i];
	}
	end;
}

-	shop	someshop	89,505:10000,506:6000,507:7000
```

Run the test, buy something, still not showing "OnBuyItem: 506 x 1" in the chat windows.

**Comment by Lemongrass3110** [comment]
Looks like this doesnt fire any on buy events anymore @aleos89, another report here #818

**Comment by CairoLee** [comment]
https://github.com/rathena/rathena/pull/832
@anacondaqq @aleos89 @icxbb-xx Please check this.

**Comment by anacondaqq** [comment]
@aleos89 @Lemongrass3110 
The error appeared again. Tested on clean rA: da23d877d1e2d646a727cca7d12bd75cebb40a7a

pre-re / re. The same steps to reproduce (call cashhop).
packet_ver: 55, packet obf: disabled. Client: 2015-11-04aRagexe.

**Comment by aleos89** [comment]
I can't reproduce this on 800f22b. I used your original script above. When the shop is open I can't move or click other NPC. When I close the shop I can do everything normally.

**Comment by anacondaqq** [comment]
hi, i will test it tomorrow and will post results on the latest clean rA and will provide test case. thx for your time.

**Comment by Litro** [comment]
Necromancing cold cases this is happening again now, can anyone else verify it?
