### ISSUE TITLE
Sorcerer's skills Electic Walk (so_electicwalk) and Fire Walk (so_firewalk) don't work!

### ISSUE THREAD

**Issue by Rayvakarian** [rathena/rathena#6521]
* **rAthena Hash**:  
* c08c7c0

* **Client Date**:  
2021-11-17
* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result: After I use this skill, the cast passes, but there is no any effect/damage while character's moving 
!
[image](https://user-images.githubusercontent.com/65616872/149628160-d8f3ccb3-833e-47d4-b6db-a51878b4bf7a.png)

**Comment by dimasshotta** [comment]
![image](https://user-images.githubusercontent.com/74591268/149629505-a41c7e4b-c2ba-471b-8100-644c5de6317d.png)
is it supposed to be like this?

**Comment by Rayvakarian** [comment]
> ![image](https://user-images.githubusercontent.com/74591268/149629505-a41c7e4b-c2ba-471b-8100-644c5de6317d.png) is it supposed to be like this?

Yes, idk why these skills don't work

**Comment by Rayvakarian** [comment]
I found out that these skills stop working after I dress shield with Golden Thief Bug card
![image](https://user-images.githubusercontent.com/65616872/149635893-788c03c9-2c3c-4a46-af85-cb641d6fbff9.png)

**Comment by aleos89** [comment]
Related to #5918.
