### ISSUE TITLE
Some skills are not accurate

### ISSUE THREAD

**Issue by Akaineko-astasi** [rathena/rathena#6524]
* **rAthena Hash**: 
6a25a39

* **Client Date**: 
2020-09-02

* **Server Mode**: 
Renewal

* **Description of Issue**: 
Noticed there are some inaccuracies in skills, based on my kRO experience.
  * MO_FINGEROFFENSIVE
    * Should always deal 5 hits on all levels. 
    * Damage should not be multiplying by hits number.
    * Sould be no dependance on remaining sphere count. 
  * SR_TIGERCANNON
    * Only HP/SP bonus damage should ignore Flee

* **Modifications that may affect results**: 
none

**Comment by Akaineko-astasi** [comment]
What info is needed besides the client date?

**Comment by Daegaladh** [comment]
I tested MO_FINGEROFFENSIVE myself on Aegis and fixed it on #4866, so unless Gravity changed it that's how it should work.
The number of hits depends on the spheres the player has, but the max number of hits is the same as the skill level.

Could you provide any proof or info about this change?

**Comment by Akaineko-astasi** [comment]
https://cdn.discordapp.com/attachments/357879122204033024/927534310515421234/krom-MO_FINGEROFFENSIVE.rrf

If that doesn't work, I'd figure out some mirror...
