### ISSUE TITLE
kagerou/oboro animation

### ISSUE THREAD

**Issue by joelolopez** [rathena/rathena#653]
im using the latest stable client, and a fresh rathena..  this report concerns with the kagero/oboro job... if you will notice when using dual daggers or huuma shuriken the animation that was playing is index 10 or  attacking2 (no weapon) in GRF Editor..supposedly index 10 is for dual daggers and  index 11 is for huuma shurikens type weapons.. and when throwing kunais or shurikens the animation index should be index 5..

**Comment by cydh** [comment]
is that really have relation with rAthena's source codes? /swt

**Comment by philg666** [comment]
there is this place where you can post all your client-side related problems:
https://rathena.org/board/forum/19-client-side-support/
