### ISSUE TITLE
Frost_Crystal is not a consumable

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#6536]
* **rAthena Hash**: 
9d324ba077aa5453e0f47894ca72b951588adc53

* **Client Date**: 
Not relevant

* **Server Mode**: 
Renewal

* **Description of Issue**: 
  * Result: Item ID 22566,Frost_Crystal missing item script.
  * Expected Result: Implementation of the consumable effect.
  * How to Reproduce: Frost_Crystal is currently not a consumable.
  * Official Information:
  Item description states: "화상 상태 이상 해제."
  Rewarded from Squad_Prize from the Temple of Demon God instance.
  https://www.divine-pride.net/database/item/22566

* **Modifications that may affect results**: 
none

**Comment by Atemo** [comment]
`SetBuff "EFST_CHILL" 10000 1` from aegis for reference
