### ISSUE TITLE
Can't compile the map server after updating to the latest commit.

### ISSUE THREAD

**Issue by lelouch22** [rathena/rathena#6545]
* **rAthena Hash**: 8064766f181ce82a6f63785eb91c43d2887b0516

* **Client Date**: 2019-03-22

* **Server Mode**: Pre-Renewal

* **Description of Issue**:
  * Result: 
```
clif.cpp: In function ‘void clif_parse_barter_buy(int, map_session_data*)’:
clif.cpp:22804:93: error: invalid application of ‘sizeof’ to incomplete type ‘clif_parse_barter_buy(int, map_session_data*)::PACKET_CZ_NPC_EXPANDED_BARTER_PURCHASE’
22804 | ngth - sizeof( struct PACKET_CZ_NPC_EXPANDED_BARTER_PURCHASE ) ) / sizeof( struct PACKET_CZ_NPC_EXPANDED_BARTER_PURCHASE_sub );
      |                                                              ^

clif.cpp:22804:157: error: invalid application of ‘sizeof’ to incomplete type ‘clif_parse_barter_buy(int, map_session_data*)::PACKET_CZ_NPC_EXPANDED_BARTER_PURCHASE_sub’
22804 |  / sizeof( struct PACKET_CZ_NPC_EXPANDED_BARTER_PURCHASE_sub );
      |                                                              ^
```

**Comment by aleos89** [comment]
Can you please detail your OS, GCC, etc.

**Comment by lelouch22** [comment]
> Can you please detail your OS, GCC, etc.

OS: Debian 9.13 (Also tried this on Ubuntu and Windows but it has the same results.)
GCC: gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)

Note: One thing I noticed is if I removed my packet_ver entry in the src/custom/defines_pre.hpp everything is fine but once i added my packet_ver entry again that error shows up.

This is my packet_ver entry...
`#define PACKETVER 20190322`
