### ISSUE TITLE
Map server crashes on loading the new quest_db.txt

### ISSUE THREAD

**Issue by jezznar** [rathena/rathena#655]
Map server crashes when loading the new quest_db.txt

workaround: delete the quest_db.txt

**Comment by aleos89** [comment]
Did you apply the fixes in 2bb69a3?

**Comment by aleos89** [comment]
Showing that Travis and personal tests reveal it works fine, I'll assume you're not at the latest version of rAthena or have some merge conflict.

**Comment by jezznar** [comment]
Tested. Fixed. Thank you.
