### ISSUE TITLE
Mado Gear Armorer NPC missing changes

### ISSUE THREAD

**Issue by Haydrich** [rathena/rathena#6551]
rAthena Hash: #6549
Client Date: 20211103
Server Mode: RE
Description of Issue:
Meister job can't speak with Mado Gear Armorer NPC
![image](https://user-images.githubusercontent.com/54556365/150747064-dc82c503-87f6-47f2-8290-e7a28b8cd87c.png)
same issue with RK and RG with Riding Creature Master
![image](https://user-images.githubusercontent.com/54556365/150748067-7818919c-bad2-49d9-bc4b-e0197262cbc2.png)

Result:
Expected Result: 
How to Reproduce:
Modifications that may affect results:

**Comment by Atemo** [comment]
https://github.com/rathena/rathena/commit/a2a614198af43288c57a3c76276c460950fa8843
