### ISSUE TITLE
Missed items

### ISSUE THREAD

**Issue by Balferian** [rathena/rathena#6557]
* **rAthena Hash**: 0fc05ce
* **Client Date**: -
* **Server Mode**: Renewal
* **Description of Issue**: 
  * Result:
     Missed items: 22529, 22816, 22817, 22818, 22820, 22973, 22974, 22975, 22976, 22977, 22978, 23150, 100007, 100008, 100316, 100317, 100006, 23817, 100075, 100076, 100077, 100078
     Wrong item price: 25377
     No jobs restriction: 2032, 21038, 26151, 620010
  * Expected Result: add missed items to database.
  * How to Reproduce:
  * Official Information:

* **Modifications that may affect results**:

**Comment by mazvi** [comment]
@idk-whoami :D
