### ISSUE TITLE
Suggest to [Debug] upgrade

### ISSUE THREAD

**Issue by tmav94** [rathena/rathena#656]
Hi, Masters!
I'm comming here to ask to you about a upgrade on [Debug] 'Notices'...
Look this:

[Debug]: script debug : 0 110015469 : Quest requirement #5 invalid (skipped).
[Debug]: script debug : 0 110015469 : Quest reward #0 invalid (skipped).
[Debug]: script debug : 0 110015469 : Quest reward #0 invalid (skipped).
[Debug]: script debug : 0 110015469 : Quest reward #0 invalid (skipped).
[Debug]: script debug : 0 110015469 : Quest reward #0 invalid (skipped).
[Debug]: script debug : 0 110015469 : Quest reward #0 invalid (skipped).
[Debug]: script debug : 0 110015469 : Quest reward #0 invalid (skipped).
[Debug]: script debug : 0 110015469 : Quest reward #0 invalid (skipped).
[Debug]: script debug : 0 110015469 : Quest reward #0 invalid (skipped).
[Debug]: script debug : 0 110015469 : Quest reward #0 invalid (skipped).

I Have a Script, that have more than 80 quests using "Euphy's Quest Shop".
So...when i type something wrong, i cant found it because the debug dont show where's the error...Can someone update this?

**Comment by Atemo** [comment]
Well the title should be "Suggest to [Debug] upgrade in Euphy's Quest Shop" something like that.. need thought of @euphyy

**Comment by tmav94** [comment]
I don't think so...sometimes when you make some mistakes...a [debug] appers but you dont know where they come from...

I Believe that is for all

**Comment by cydh** [comment]
blame the `debugmes` on that script, make it more clear.
blame people who make `debugmes` without clear info.

if the debug is from source, it'll tell you the NPC name and coordinates (if not floating NPC)

**Comment by aleos89** [comment]
[Debug]: script debug : 0 110015469 : Quest reward #0 invalid (skipped).
                                RID  | OID            | String

The first two values are useless for you most of the time unless you specifically need them.

The string is what is defined for the script command 'debugmes' to print. In your case:
```
debugmes "Quest reward #"+getarg(1)+" invalid (skipped).";
```
and
```
debugmes "Quest requirement #"+getarg(.@i)+" invalid (skipped).";
```
Essentially you're passing a bad item ID. That's something you're going to have to manually check since Euphy's script already tries to check for this.
