### ISSUE TITLE
Swapping equipment/cards with combo leads to incorrect HP/SP

### ISSUE THREAD

**Issue by kutsuru** [rathena/rathena#6564]
* **rAthena Hash**: b13bc7402

* **Client Date**: 2018-04-18b

* **Server Mode**: Pre-Renewal

* **Description of Issue**: 
  - Result: HP/SP are not properly set when swapping equipment/cards involving combo
![image](https://user-images.githubusercontent.com/1560828/151291093-5695ace5-8869-41a1-93d6-5cbd0581c8ae.png)  
![image](https://user-images.githubusercontent.com/1560828/151291075-d29ce70f-5d5e-432a-b0ce-f55938d48ed4.png)

  - Expected Result: HP/SP should remain the same value as MaxHP/MaxSP
  * How to Reproduce: Issue can be reproduced with the Fricco's Shoes[0]-2417, Odin's Blessing[1]-2353 and Falcon Muffler[0]-2516 for equipment and the Dark Illusion-4169+ Dark Lord-4168 combo for cards. By simply swapping the same equipment, MaxHP and MaxSP will remain the same, but HP and SP will not and be set to the value without the combo. 
  * Official Information: N/A
  

* **Modifications that may affect results**: 
  * This is mainly due to the fact that during unequip, if a combo is removed it will force update the status even in the context of swapping equipment.
  * https://github.com/rathena/rathena/blob/master/src/map/pc.cpp#L11597 for equipment
  * https://github.com/rathena/rathena/blob/master/src/map/pc.cpp#L11611 for cards
  * Most probably above statements should take into consideration the passed flag (_&& flag & 1_)

**Comment by aleos89** [comment]
Are you able to reproduce this after #6162? Your hash is several years old now.

**Comment by Atemo** [comment]
I can't reproduce on https://github.com/rathena/rathena/commit/c092c8711beef4630c8c9894a3763c7176960b03

**Comment by kutsuru** [comment]
I could reproduce on #701c6f6

**Comment by kutsuru** [comment]
I could reproduce on 701c6f6239faff10a8719a3b0578b6ec0e805bbb

**Comment by kutsuru** [comment]
> I can't reproduce on [c092c87](https://github.com/rathena/rathena/commit/c092c8711beef4630c8c9894a3763c7176960b03)

What did you test ? I've just tested on up to date repo, still reproducible.

**Comment by kutsuru** [comment]
Exactly same as in the initial picture, I replace the Fricco's with another Fricco's and HP drops, and it should not.

**Comment by Daraen1** [comment]
I can reproduce too, i use 2018-04-18b client date and my source is up to date.
I use Pre-renewal.
![bug frico 1](https://user-images.githubusercontent.com/75265726/154415891-a33285cc-c7ed-4041-a7d6-07c0c718cfd5.png)
![bug frico 2](https://user-images.githubusercontent.com/75265726/154415899-5d4c0f04-06e2-4d17-8a8f-0e17ee7b525b.png)

**Comment by aleos89** [comment]
The reason your HP/SP drops is because you're effectively unequipping the first item -> status update applied to HP/SP lowering the max and current since bonus is gone -> equipping second item -> status update applied to HP/SP increasing max but current stays at current value since bonus is active.

Can you prove on kRO that a players HP/SP doesn't change when switching with the same item? What happens if the same item has cards or enchants that adjusts HP/SP?

**Comment by kutsuru** [comment]
Sorry @aleos89 I have no way to prove the behaviour on kRO, but you would expect the same behaviour as when no combos are involved
![image](https://user-images.githubusercontent.com/1560828/159216629-4332ca57-db05-4898-ad27-699be151b7ea.png)
Naked => 4311 HP
![image](https://user-images.githubusercontent.com/1560828/159216681-ea863fd2-e5a5-4096-a0a2-b17a1dda2692.png)
Diablos Boots => 5301 HP
![image](https://user-images.githubusercontent.com/1560828/159216720-0268bc51-2704-4be4-b4fd-e99aceec3f7b.png)
Swapping to Sleipnir[0] => 5173 HP

Swapping to Sleipnir[0] did not reset HP to base HP

**Comment by kutsuru** [comment]
Hello @aleos89, would not it make more sense to have the same behaviour for both scenario ?

**Comment by Playtester** [comment]
Tested on official servers: If you change your equip, it will first unequip an item, this will reduce your HP/SP, then on equipping the new item, your current HP/SP remain the same.

So yes, you get effectively damaged by changing equip, even if you change to the same type of equip.

I would say this is working as intended.

**Comment by kutsuru** [comment]
Thanks for the investigation/fix, well that was not the expected result but the purpose is to match official behaviour, I guess :)
