### ISSUE TITLE
BUG bVariableCastrate

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#657]
Any item used that has reduced cast has a problem . When there bVariableCastrate -10 e.g. , the value is not affecting the reduction . I found a spell on the fallen archangel wing and edited for bVariableCastrate -100 to become instant cast , but not worked. I was still carrying cast .

**Comment by cydh** [comment]
try to cast skill that **doesn't have fixed cast time**

**Comment by Badarosk0** [comment]
I tried. Check habilida wave psípica socerer . Edit the status reduction in cast in -150 % , will be ready stant cast . What I mean is that the 100% non ESA 100 %. The 10 % is not 10%. Yes smaller than that.

**Comment by nanakiwurtz** [comment]
Maybe you mean 'Psychic Wave' (SO_PSYCHIC_WAVE) ?

**Comment by aleos89** [comment]
Psychic Wave has a fixed cast:
```
2449,8000:9000:10000:11000:12000,1000,0,1200:1700:2200:2700:3200,0,5000,1000:900:800:700:600
```

**Comment by MrAntares** [comment]
It is working fine for me ¬.¬
