### ISSUE TITLE
Skill Item cost perlevel doesn't work properly

### ISSUE THREAD

**Issue by dimasshotta** [rathena/rathena#6573]
rAthena Hash: 3fb8268
Client Date: 2021-11-17
Server Mode: Re
Description of Issue: The skill that needs item perlevel is not working. It doesn't read the itemcost per level. But the itemcost working if there is no level requirement in the itemcost.

Result:
Expected Result: Supposedly the skilldb reads the itemcost per skill level
![image](https://user-images.githubusercontent.com/74591268/151537317-fd2570ba-2d5b-4ba3-a4f2-5f74000ddc44.png)
here i dont have gemstone as the requirement to cast lv 10 fire pillar.
but its still working without the blue gemstn.
![image](https://user-images.githubusercontent.com/74591268/151537614-d31a7096-e65d-41d9-bdba-deb5459e2545.png)
Please help

**Comment by mazvi** [comment]
Please provide rAthena Hash

**Comment by Sinnerseiei** [comment]
comfirm

**Comment by Daraen1** [comment]
I can confirm the behavior.
Is there a fix planned in the coming days?
If not, I'll take a look at it when I have a bit more time.

**Comment by CairoLee** [comment]
Tomorrow I will submit a PR to fix it

**Comment by Daraen1** [comment]
Allright! Waiting for your PR ;)
