### ISSUE TITLE
bAddSize isn't working

### ISSUE THREAD

**Issue by le0shadow** [rathena/rathena#6584]
* **rAthena Hash**: 61d9cb136

* **Client Date**: 2021-11-03

* **Server Mode**: Renewal

* **Description of Issue**: bAddSize isn't working
  * Result:  it's not applying physical damage modification to any size
  * How to Reproduce: Use bAddSize in any script and notice that damage does not change at all.

**Comment by kaninhot004** [comment]
It's same issue https://github.com/rathena/rathena/issues/6579

Please wait for https://github.com/rathena/rathena/pull/6582 merged.
