### ISSUE TITLE
2014-10-22b Quest Issues

### ISSUE THREAD

**Issue by tmav94** [rathena/rathena#659]
When you have more than 1 active quest, you cant relog...If you Relog your character you will get Gravity Error

**Comment by Desground** [comment]
I confirm not only happens on Hercules.

**Comment by renniw** [comment]
i confirm  i use 2014-10-22  client that has same problem

**Comment by Thurin** [comment]
i confirm

**Comment by Desground** [comment]
Hmm interested. I use 2014-10-22b and 2015-05-13a but Gravity Error there is no. Although more than one active quests.

**Comment by roFenrir** [comment]
On older exe errors do not. 2014-10-22b error is present.

**Comment by icxbb-xx** [comment]
Fixed in https://github.com/rathena/rathena/commit/79ef03e6563bb2d7647e15c006313624a7e10e15
