### ISSUE TITLE
Missing negative price checks in dynamic shops

### ISSUE THREAD

**Issue by Lemongrass3110** [rathena/rathena#6594]
* **rAthena Hash**: 3da8426

* **Client Date**: -

* **Server Mode**: Both

* **Description of Issue**: 
  * Result: npcshopitem, npcshopadditem and npcshopupdate do not check for negative prices or support -1 for default price usage.
  * Expected Result: Check for negative inputs and add support for default price references.
  * How to Reproduce: See samples in comments of #6571
  * Official Information: -

* **Modifications that may affect results**: 
None

**Comment by idk-whoami** [comment]
I fixed it by removing unsigned at amount variable.
