### ISSUE TITLE
Error HP on Expanded Job after Base Level 175+

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#6596]
* **rAthena Hash**: e7f58b1

* **Client Date**: 20211103

* **Server Mode**: RENEWAL

![gambar](https://user-images.githubusercontent.com/8316103/152697288-7af7c7a0-f276-4d03-ade6-f171f87061b1.png)

![gambar](https://user-images.githubusercontent.com/8316103/152697473-570460f3-1a9c-4994-aa6b-162d6d87f833.png)

![gambar](https://user-images.githubusercontent.com/8316103/152697530-f69e2aaa-078b-45c7-a2ad-8ef73cc59af4.png)

* **Description of Issue**: 
  * Result:  HP ERROR After Base Level 175+
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by ryukazuna** [comment]
Missing HP Tables. Summoner,Soul Reaper and Star Emperor still have unknown base points for 176 and higher.

**Comment by mazvi** [comment]
> Missing HP Tables. Summoner,Soul Reaper and Star Emperor still have unknown base points for 176 and higher.

So why are there levels above 175 enabled for this job? At least there should be a dummy for this.

**Comment by Pokye** [comment]
> Missing HP Tables. Summoner,Soul Reaper and Star Emperor still have unknown base points for 176 and higher.

I found this, but I don't know if it's official from kRO, but for now I think rA should follow.
https://github.com/PandasWS/Pandas/commit/9ec9a9aa6eb033efb6a9fa416acf0407c5ae9b61

**Comment by mazvi** [comment]
> > Missing HP Tables. Summoner,Soul Reaper and Star Emperor still have unknown base points for 176 and higher.
> 
> I found this, but I don't know if it's official from kRO, but for now I think rA should follow. [PandasWS/Pandas@9ec9a9a](https://github.com/PandasWS/Pandas/commit/9ec9a9aa6eb033efb6a9fa416acf0407c5ae9b61)

so true. because the level can rise above 175. and has exp/stat above 175 there should be a temporary dummy level until it is known that the actual base hp sp from kro.

**Comment by ryomahostingph** [comment]
https://raw.githubusercontent.com/PandasWS/Pandas/9ec9a9aa6eb033efb6a9fa416acf0407c5ae9b61/db/re/job_basepoints.yml
Tested this and i think its good now 
![image](https://user-images.githubusercontent.com/77398623/152977174-10c24dac-1fa4-48a8-904d-9d0b1d0c681a.png)

**Comment by mazvi** [comment]
> https://raw.githubusercontent.com/PandasWS/Pandas/9ec9a9aa6eb033efb6a9fa416acf0407c5ae9b61/db/re/job_basepoints.yml Tested this and i think its good now ![image](https://user-images.githubusercontent.com/77398623/152977174-10c24dac-1fa4-48a8-904d-9d0b1d0c681a.png)

yes i have made a pull for it. hopefully it can be applied for a while #6600 until the real kRO data is known

**Comment by Lemongrass3110** [comment]
Fixed in 883518b.
Was not linked correctly it seems.
