### ISSUE TITLE
Cook point save only last cook point

### ISSUE THREAD

**Issue by Shaktohh** [rathena/rathena#6602]
* **rAthena Hash**:  a1b7fab19ba263bb29eb4d10e55fe81868b4850c

* **Client Date**: 20200401

* **Server Mode**:  Pre-renewal

* **Description of Issue**: Cook 10 recipes
  * Result: You only got the points from last cooked recipe when you log off.
  * Expected Result: Points should be calculated and stored in sd->cook_mastery at each cooking

Possible resolution :

/src/map/chrif.cpp
Function : int chrif_save(struct map_session_data *sd, int flag)
after chrif_bsdata_save(sd, ((flag&CSAVE_QUITTING) && !(flag&CSAVE_AUTOTRADE)));
add
pc_setglobalreg(sd, add_str(COOKMASTERY_VAR), sd->cook_mastery);

src/map/skill.cpp
Function : bool skill_produce_mix(struct map_session_data *sd, uint16 skill_id, t_itemid na
Replace
pc_setglobalreg(sd, add_str(COOKMASTERY_VAR), sd->cook_mastery + ( 1 << ( (skill_produce_db[idx].itemlv - 11) / 2 ) ) * 5);
by
sd->cook_mastery = sd->cook_mastery + (( 1 << ( (skill_produce_db[idx].itemlv - 11) / 2 ) ) * 5);

Replace
pc_setglobalreg(sd, add_str(COOKMASTERY_VAR), sd->cook_mastery - ( 1 << ((skill_produce_db[idx].itemlv - 11) / 2) ) - ( ( ( 1 << ((skill_produce_db[idx].itemlv - 11) / 2) ) >> 1 ) * 3 ));
by
sd->cook_mastery = sd->cook_mastery - ( 1 << ((skill_produce_db[idx].itemlv - 11) / 2) ) - ( ( ( 1 << ((skill_produce_db[idx].itemlv - 11) / 2) ) >> 1 ) * 3 );

**Comment by aleos89** [comment]
Do you happen to have any videos from kRO or aegis showing that this happens?

**Comment by Shaktohh** [comment]
As you can't see your cooking point on Kro the answer is no.
 But I really doubt it works like it is actually., why only on the last cooking, it would save the point ? it's not working like this for alchemist and blacksmith points.

Just having this line say what it says
pc_setglobalreg(sd, add_str(COOKMASTERY_VAR), sd->cook_mastery + ( 1 << ( (skill_produce_db[idx].itemlv - 11) / 2 ) ) * 5);
by
You replace the registry variable each time you cook without taking it back the next time you cook except on reloading the char.
