### ISSUE TITLE
Using #itemlist or @itemlist will crash the map server

### ISSUE THREAD

**Issue by TesLA-Git** [rathena/rathena#6606]
* **rAthena Hash**: [645ff85](https://github.com/rathena/rathena/commit/645ff8591a101836be97a961c82e83b4d691e9eb)

* **Client Date**: 20221103

* **Server Mode**: re

* **Description of Issue**: Using #itemlist or @itemlist will crash the map server
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Can you please post the crash dump associated to this?

**Comment by Lemongrass3110** [comment]
No input for more than 14 days.
