### ISSUE TITLE
Malangdo costume enchant bug

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#6609]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/c429747f73bc21f98d5febe53ce109a033e478fe
* **Client Date**: Irrelevant
* **Server Mode**: RE
* **Description of Issue**: If you equip the character with multiple costumes that are on the list of items that can be enchanted, the npc will only read the UPPER position, does not have the option to choose which equipped costume you wants to enchant.
  * How to Reproduce: Just equip the character with costumes that are on the enchantable list, and try to enchant one that is not UPPER position, bug ocorroung in npc "Aver De Dosh".

other problem:

`buildin_select: NPC Menu too long! (source:Aver De Dosh#cos_ect / length:2575)`

**Comment by Atemo** [comment]
> If you equip the character with multiple costumes that are on the list of items that can be enchanted, the npc will only read the UPPER position, does not have the option to choose which equipped costume you wants to enchant.

The official script is designed like you wrote.

**Comment by admkakaroto** [comment]
Oh, ok.
