### ISSUE TITLE
Monk/Champ/Sura Spirit Spheres dont give Holy Damage Bonus

### ISSUE THREAD

**Issue by Inzanity99** [rathena/rathena#662]
Hello,

Ever since pre-Renewal (and there has be no word of a change towards this), Spheres from the Monk class have the following traits:
"Floating balls of light summoned by the Summon Spirit Sphere skill. Spirit Spheres grant 3 Holy ATK each that always hit."

Currently spirit spheres seem to give the ATK bonus when auto attacking, but they not add the always hit bonus, at all. Seems to be undefined in the source.

**Comment by MrAntares** [comment]
They removed this effect in renewal. Same happened with occult impact, and some other skills.

**Comment by aleos89** [comment]
As stated by @MrAntares, spheres no longer give "flee bypassing" damage.
