### ISSUE TITLE
Player can't target/hit other player on WOE Area

### ISSUE THREAD

**Issue by laziem** [rathena/rathena#6620]
* **rAthena Hash**: c454443a0
* **Client Date**: 20211103
* **Server Mode**: RE
* **Description of Issue**: 
  * Result: Player can't target the other player on WOE area, but AoE skill can damage other player
  * Expected Result: Can target other player
  * How to Reproduce: Enable WOE, then try to hit other player
  * Official Information: -

* **Modifications that may affect results**: - (test on fresh rAthena)

   ![canthit](https://user-images.githubusercontent.com/31171415/154187934-4498a2e6-f1eb-49c8-b868-1a5a1b881d84.png)

   Normal attack / target skill not working to other player. But, skill with AoE can damage other player.

**Comment by Daraen1** [comment]
Maybe a video will help to better understand your problem, after that it may be that the language barrier does not allow me to understand your problem 100%.

**Comment by lukkta2111** [comment]
Remove fix homunc attack from diff hexed

**Comment by laziem** [comment]
Thank you. Remove the homun attack fixed the problem.
