### ISSUE TITLE
Elemental Converter issues

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#6627]
* **rAthena Hash**: 
61d9cb1360305eae697d63bd2839957937ca3109

* **Client Date**: 
Not relevant

* **Server Mode**: 
Pre-Renewal, Renewal

* **Description of Issue**: 
  * Result:
   Elemental Converter's applied effect does not wear off, when un-equipping or swapping weapons
  * Expected Result:
    Elemental Converters effect should wear off when switching or taking off weapons.
  * How to Reproduce: 
    Swap weapons with an active elemental weapon buff (item ids: 12114, 12115, 12116, 12117, 12020)
  * Official Information:
    No official source

* **Modifications that may affect results**: 
None

**Comment by Daraen1** [comment]
I can confirm the same behavior on pre-renewal mode.
we can use an elemental converter even if no weapon is equipped.
If my hands are enchanted with an elemental converter and I equip a Knife, the element is kept on my weapon.
if I unequipped my knife, the effect of the converter fades.
If I use two fire elemental converters, I also get the message: Weapon has change back to normal.
But the effect is not dissipated

**Comment by Toshiro90** [comment]
Just tested this on official (kRO) and got the following results:
- Elemental Converters can be used without any weapon equipped
- Effect stays active when equipping a weapon if no weapon was equipped before
- Effect ends when changing weapons
- Using an other Elemental Converter while the effect is still active, indeed shows that the effect ended (effectively removing and instantly reapplying `EFST_WEAPONPROPERTY`, but this is necessary to remove the status icon in case a different element is used or it would show multiple icons with different elements)

**Comment by jofvgaming** [comment]
have fixed for this ??
