### ISSUE TITLE
Reset Girl (Custom)

### ISSUE THREAD

**Issue by ernestfegarido** [rathena/rathena#663]
when i am resetting my skills and my stats. My Battle Manual (12208) disappear.

**Comment by lordganja** [comment]
Do you mean the status(SC_EXPBOOST) of battle manual disappear?
maybe because of 'sc_end SC_ALL;' inside the resetnpc.txt.. just remove it or comment it if you don't want status to be removed.

**Comment by aleos89** [comment]
As @lordganja said, it ends all statuses, good or bad. If you want to disable just comment it out.
