### ISSUE TITLE
Portals going inside TE Castles are affected when disabling npc: npc/re/guild3/agit_start_te.txt

### ISSUE THREAD

**Issue by micosanityyy** [rathena/rathena#6630]
* **rAthena Hash**: 

* **Client Date**: 2020-04-01

* **Server Mode**: Renewal

* **Description of Issue**: Portals going inside TE Castles are affected when disabling npc: npc/re/guild3/agit_start_te.txt
  * Result: Tried entering and exiting TE castle while agit_start_te.txt was enabled and worked fine, disabled and restarted server then now cannot enter TE castle, tried starting TE Woe using euphy's woe_controller same result (i'm using Assassin Cross Job for testing, warning for 3rd job works)
  * Expected Result: Should be able to go in and out TE castle with the right job even when default TE start script is disabled
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**: Not sure, disabled all FE, SE and TE default start scripts since I'm using custom woe_controller in rA custom folder

**Comment by aleos89** [comment]
Sorry, but I don't see anything in that script related to enabling or disabling warp portals.
