### ISSUE TITLE
Location: <map> to kill monster count doesn't work if it's not a permanent monster

### ISSUE THREAD

**Issue by dimasshotta** [rathena/rathena#6631]
rAthena Hash: https://github.com/rathena/rathena/commit/6a25a392c21ec118e9a2512102f485453ee2083f
Client Date: 20211103
Server Mode: RE
Description of Issue:
I'm trying to make Illusion Dungeon Investigation quest that kills 100 mob in certain map so I use this kind of questdb:

  - Id: 3462
    Title: Illusion of Luanda 100 Kills
    Targets:
      - Id: 1
        Count: 100
        Location: com_d02_i
        MapName: Illusion of Luanda

But it doesnt count if we kill monsters that is spawned by script command like this
 
	monster $map$,0,0,"--ja--",20274,.mob,strnpcinfo(0)+"::OnWootanKilled";
	for (.@i = 0; .@i < .mob; .@i++) {
		.GID10 = $@mobid[.@i];
		getunitdata .GID10,.@mob2;
		setunitdata .GID10,UMOB_GROUP_ID,4;
	}

Result: 
- Killing the monster doesn't count  if I add Location only.

Expected Result: Counting must occur even the mobs are spawned by script command, because I believe some Illusion Dungeon script using script command to spawn the mob.

How to Reproduce:

Official Information:

https://youtu.be/EcSmiC0XRo4

Modifications that may affect results:

**Comment by aleos89** [comment]
Could have sworn this was worked on before and we have this: #6392. Do you have this applied to your server?

**Comment by dimasshotta** [comment]
@aleos yes I have applied it to my server. yes Illusion of Luanda is a normal dungeon, but illusion luanda has some kind of mechanism that needs monsters to change tribe like this information in nova RO https://www.novaragnarok.com/wiki/Illusion_of_Luanda and I'm sure the mob spawn mechanism is the same like official KRO. Is there any other way to spawn monsters permanently and add monster group id? if the quest on location is not counted from this script command "monster $map$,0,0,"--ja--",20274,.mob,strnpcinfo(0)+"::OnWootanKilled";" I guess we cannot apply Illusion Investigation quest for Illusion of Luanda.

**Comment by Haydrich** [comment]
> Could have sworn this was worked on before and we have this: #6392. Do you have this applied to your server? Also, Illusion of Luanda is not a memorial dungeon, it's a normal dungeon.

Illusion Luanda have 2 clans of monsters
![Illu_lua_rotate](https://user-images.githubusercontent.com/54556365/156192157-04311ed8-0b4c-4fe2-97d0-f4103e16f2f5.png)
 when you kill 1500 monster from the first clan the mvp of this clan appears
and after killing the mvp the other clan monsters appears
so after applying the quest
```Id: 3462
Title: Illusion of Luanda 100 Kills
Targets:
Id: 1
Count: 100
Location: com_d02_i
MapName: Illusion of Luanda```
the monsters that spawn by script command not counting

**Comment by aleos89** [comment]
Ok thanks for the information (I haven't really looked into these new dungeons and scripts so I wasn't aware of how they worked). So the issue is because you're using the `monster` script command. This calls the `mob_once_spawn` function in the source which doesn't attach a respawn timer to the monster, thus your script isn't working based on this check:
```cpp
				if (qi->objectives[j]->mapid < 0 || (qi->objectives[j]->mapid == sd->bl.m && md->spawn != nullptr))
					objective_check++;
```

**Comment by Haydrich** [comment]
> Ok thanks for the information (I haven't really looked into these new dungeons and scripts so I wasn't aware of how they worked). So the issue is because you're using the `monster` script command. This calls the `mob_once_spawn` function in the source which doesn't attach a respawn timer to the monster, thus your script isn't working based on this check:
> 
> ```c++
> 				if (qi->objectives[j]->mapid < 0 || (qi->objectives[j]->mapid == sd->bl.m && md->spawn != nullptr))
> 					objective_check++;
> ```

Yep, That's right

**Comment by dimasshotta** [comment]
Here I will attach a sample of the script that I have done so far for Illusion of Luanda. I hope it helps for checking.
[Illusion_luanda.txt](https://github.com/rathena/rathena/files/8162713/Illusion_luanda.txt)

**Comment by aleos89** [comment]
So I guess the solution here is to have the mobs permanently spawn and use a combination of getmapunits or getareaunits with getunitdata and compare the UMOB_CLASS with other values to get the exact mob you want and swap them around that way.

Quest mob targets can only be permanently spawned mobs on normal maps. When @Atemo or @Everade get around to this script we can maybe come up with a better solution.
