### ISSUE TITLE
Save Point Problem

### ISSUE THREAD

**Issue by Xypr0** [rathena/rathena#6632]
* **rAthena Hash**: latest git file

* **Client Date**: 
any client version

* **Server Mode**: 
Both Happen in pre-re and renewal

* **Description of Issue**: 
  * Result: when the map is disabled or not existing at all. for example payon town. when you save on that town and you disabled it and restart the server, once you die you will respawn in your current position when you click return to savepoint.
  * Expected Result: its good if the map of your savepoint is not existing there will be default map x and y can teleport your character and show a dispbottom message about "your savepoint is not exist.".
  * How to Reproduce: go save in any map and then disabled it and restart the server and do not forget to move your character first in existing map.
  * Official Information: *i cant test this in official kro

* **Modifications that may affect results**: 
  i didnt change anything. you can use any file even in latest git file.

**Comment by aleos89** [comment]
Is it even a normal scenario that a map is removed from a server? If you're "disabling" maps by not using them anymore, it might be best to just add a NoSave mapflag to it to force players out and possibly having a hidden NPC resetting the save point to a specific map if their save point matches the map you are "disabling".

Gravity doesn't remove maps from their cache, they just disable warps and stuff getting to those maps. The practice can easily be done the same for us especially with the minimal amount of kilobytes a map uses up in rAthena.

**Comment by Toshiro90** [comment]
On official servers (just experienced on the newly launched MY/SG/PH server), when the SavePoint map is not available (e.g. map-server down) it just displays "Unable to move the applied area" and wont resurrect you at all.

**Comment by DevNoName** [comment]
> Is it even a normal scenario that a map is removed from a server? If you're "disabling" maps by not using them anymore, it might be best to just add a NoSave mapflag to it to force players out and possibly having a hidden NPC resetting the save point to a specific map if their save point matches the map you are "disabling".
> 
> Gravity doesn't remove maps from their cache, they just disable warps and stuff getting to those maps. The practice can easily be done the same for us especially with the minimal amount of kilobytes a map uses up in rAthena.

if your server is running episode and you start in lower episode you can experience what i said above.

**Comment by DevNoName** [comment]
> 

this is what im talking about. because its kinda weird if you click return to save point, it will revive you at your current position. for me it's a bug that need to fix.

**Comment by DevNoName** [comment]
> On official servers (just experienced on the newly launched MY/SG/PH server), when the SavePoint map is not available (e.g. map-server down) it just displays "Unable to move the applied area" and wont resurrect you at all. ![grafik](https://user-images.githubusercontent.com/5203899/155385553-1824cf8a-25aa-49dd-ab69-5db2c460cfb5.png)
> 
> After restarting the client and trying to login, the server asks you to select an available alternative map to login at. ![grafik](https://user-images.githubusercontent.com/5203899/155384884-f120b469-4ee3-401b-b919-9c4c7e946c56.png)

this is what im talking about. because its kinda weird if you click return to save point, it will revive you at your current position. for me it's a bug that need to fix.

**Comment by alisonrag** [comment]
this is related to packets `0x840` and `0x841`, also seems the escape map list is configurable.
list in bRO:
![image](https://user-images.githubusercontent.com/10372732/170515077-d780071e-6054-4ed7-8dee-7bdb023e4cf6.png)
