### ISSUE TITLE
Automatic Leg armor can be enchant with 2 Legendary Modules.

### ISSUE THREAD

**Issue by Enigma040125** [rathena/rathena#6635]
Please see the video below in kro:
https://www.youtube.com/watch?v=-37i_Jdw8xA

It shows in 01:56 of the video. As per 유랑별Wandering star its not a bug and its proc at the same time.

**Comment by admkakaroto** [comment]
This are 17.2 content, rA dont have this yet.

**Comment by admkakaroto** [comment]
This are content from episode 17.2, rA don't have it yet.
