### ISSUE TITLE
Monk quest log not updating after Talking to Sensei Moohae

### ISSUE THREAD

**Issue by xZee0523** [rathena/rathena#6638]
* **Server Mode**: Pre-renewal

* **Description of Issue**: Quest log still shows Talk with Sensei Moohae even after completing the proceeding steps and have changed to Monk.

![welp](https://user-images.githubusercontent.com/100657535/156096599-31c8b16b-cdb7-472b-a9ef-f0066927bc2a.PNG)

**Comment by Daraen1** [comment]
cannot confirm this issue

![monk](https://user-images.githubusercontent.com/75265726/156209921-2e2478f4-5928-4ddf-90f8-752cff6726db.png)

![monk2](https://user-images.githubusercontent.com/75265726/156210913-81ee9aea-82cc-43ce-9d5a-beb571eebc5b.png)


I had "talk with Sensei Moohae" after having managed to get out of Tomoon's invisible labyrinth.
After that, I went back to Sensei Moonhae, I had to drink the green potion so I drank it, I answered Mr. Moonhae's question, after that, I was successfully promoted to Monk and the message " talk with Sensei Moohae" had disappeared and is no longer present in my quest board
