### ISSUE TITLE
Suggestion : HelpmeShorty

### ISSUE THREAD

**Issue by eppc0330** [rathena/rathena#6640]
**Is your request related to a missing feature?** Yes

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

![2](https://user-images.githubusercontent.com/47050704/156101805-d5bcdeaa-f0de-4f3c-b448-c5bbefcace21.jpg)

![3](https://user-images.githubusercontent.com/47050704/156101845-6426e6cf-c45a-466c-ab3a-94601b4447d3.jpg)

This is an item from official KRO, that can call NPC SHORTY.
Shorty is not fixed placed NPC. When I call Shorty with item, the NPC appears NEAR THE CHARACTER.
I have no idea how to summon NPC on specifc place.

**Comment by Everade** [comment]
**Note:**
**NPC is only visible for the player who called it** and is handed out in the Novice Academy quest line.

**Comment by eppc0330** [comment]
This is basically same feature with Kachua Key.

Both NPCs are summoned near user who uses item and

visible only for them. Both of items above will be available

after some kind of instant duplicating NPC script 

command implemented.

**Comment by Atemo** [comment]
Fixed in https://github.com/rathena/rathena/commit/5d8e034868df3be37993e660ec78fd9b9f8cd676
