### ISSUE TITLE
HP Pre-Renewal ERROR

### ISSUE THREAD

**Issue by EduardoBeh21** [rathena/rathena#6644]
* **rAthena Hash**: 
47e515888c969bbbe21d275d4ac61feb67d82d4e

* **Client Date**: 
20180620

* **Server Mode**: 
Pre-Renewal

* **Description of Issue**: 
After lv 100, in any class, the HP automatically goes to MAX, and when increasing the LVMAX of the server the problem gets worse!
Apparently something is wrong with the job_basepoints.yml.

**Comment by secretdataz** [comment]
Nothing is wrong with job_basepoints.yml. Levels above 99 do not exist officially on pre-renewal, and we do not provide custom values for custom levels. To fix this issue you'd have to add base HP value for those levels above 99 yourself.

**Comment by aleos89** [comment]
Notably, you can view db/import/job_stats.yml for custom values that are commented out.
