### ISSUE TITLE
Rathena failed to msbuild with error MSB4126 with MSVC on windows arm64

### ISSUE THREAD

**Issue by spacelg** [rathena/rathena#6645]
Hi All,

Environment:
VS 2019 + Windows Server 2019

Rathena failed to msbuild with error MSB4126: The specified solution configuration "Release|arm64" is invalid with MSVC on windows arm64. It looks like there is no Release|arm64 configuration in rAthena.sln. Does Rathena support windows arm64? Could you please help look at this issue?

Repro steps:
1. git clone https://github.com/rathena/rathena F:\rathena\rathena
2. "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=arm64
3. msbuild /m /p:Platform=arm64 /p:Configuration=Release rAthena.sln /t:Rebuild

Errors:
Build started 3/4/2022 1:14:17 AM.
     1>Project "F:\rathena\rathena\rAthena.sln" on node 1 (Rebuild target(s)).
     1>F:\rathena\rathena\rAthena.sln.metaproj : error MSB4126: The specified solution configuration "Release|arm64" is
        invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.g. MS
       Build.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the
       default solution configuration. [F:\rathena\rathena\rAthena.sln]
     1>Done Building Project "F:\rathena\rathena\rAthena.sln" (Rebuild target(s)) -- FAILED.

Build FAILED.
       "F:\rathena\rathena\rAthena.sln" (Rebuild target) (1) ->
       (ValidateSolutionConfiguration target) ->
         F:\rathena\rathena\rAthena.sln.metaproj : error MSB4126: The specified solution configuration "Release|arm64"
       is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.g.
       MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use th
       e default solution configuration. [F:\rathena\rathena\rAthena.sln]

    0 Warning(s)
    1 Error(s)

**Comment by vstumpf** [comment]
I think if you want to run on arm, you have to generate a new solution (or at least a new configuration). Unfortunately, I don't think anyone on the dev team has an arm windows machine, so you'll have to do it yourself. 

In theory rathena should be fine with arm, but again, we don't have a way to test.

**Comment by spacelg** [comment]
@vstumpf , thanks for your reply and info. In fact, we are currently only compiling the project targeting arm64 on a machine with an AMD cpu, not a real windows arm64 machine. So we set the target of the vs compiler to arm64. 

We try to use the following cmake command to generate sln targeting arm64:

cmake -G "Visual Studio 16 2019" -A **arm64** -DCMAKE_SYSTEM_VERSION=10.0.18362.0 ..

**But the error is as follows:**

F:\rathena\rathena\build_arm64>cmake -G "Visual Studio 16 2019" -A arm64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 ..
-- The C compiler identification is MSVC 19.32.31303.96
-- The CXX compiler identification is MSVC 19.32.31303.96
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/arm64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/arm64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting git
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.35.1.windows.2")
-- Found git : C:/Program Files/Git/cmd/git.exe version (2.35.1.windows.2)
-- git Version: 27c0586d797ac7bf284eb0c82728e9dcec676719, 27c0586d797ac7bf284eb0c82728e9dcec676719
-- Detecting threads library
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Detecting threads library - done
-- Check if supporting Thread local storage (TLS)
-- Performing Test HAVE_TLS
-- Performing Test HAVE_TLS - Failed
-- Check for TLS - no
-- Check for monotonic clock
-- Performing Test HAVE_MONOTONIC_CLOCK
-- Performing Test HAVE_MONOTONIC_CLOCK - Failed
-- Check for monotonic clock - no
-- Looking for setrlimit
-- Looking for setrlimit - not found
-- Looking for strnlen
-- Looking for strnlen - found
-- Looking for getpid
-- Looking for getpid - found
-- Looking for gettid
-- Looking for gettid - not found
-- Detecting local MYSQL
-- Found MYSQL: F:/rathena/rathena/3rdparty/mysql/lib/x64/libmysql.lib (found version 5.7.16)
-- Detecting local MYSQL - done
-- Detecting system MYSQL
-- Could NOT find MYSQL (missing: MYSQL_LIBRARIES MYSQL_INCLUDE_DIRS)
-- Detecting system MYSQL - done
-- Configuring for local MYSQL
-- Configuring for local MYSQL - done
-- Detecting local PCRE
-- Found PCRE: F:/rathena/rathena/3rdparty/pcre/lib/x64/pcre8.lib (found version 8.33)
-- Detecting local PCRE - done
-- Detecting system PCRE
-- Could NOT find PCRE (missing: PCRE_LIBRARY PCRE_INCLUDE_DIR)
-- Detecting system PCRE - done
-- Configuring for local PCRE
-- Configuring for local PCRE - done
-- Detecting local ZLIB
-- Found local ZLIB: F:/rathena/rathena/3rdparty/zlib/lib/x64/zlib.lib (found version 1.2.8)
-- Detecting local ZLIB - done
-- Detecting system ZLIB
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY) (found version "1.2.11")
-- Detecting system ZLIB - done
-- Configuring for local ZLIB
-- Configuring for local ZLIB - done
CMake Deprecation Warning at 3rdparty/yaml-cpp/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Creating version.hpp
-- Creating version.hpp - done
-- Creating target common_base
-- Creating target common_base - done
-- Creating target common
-- Creating target common - done
-- Creating target login-server
-- Creating target login-server - done
-- Creating target char-server
-- Creating target char-server - done
-- Creating target map-server
-- Enabled PCRE code
-- Creating target map-server - done
-- Creating target mapcache
-- Creating target mapcache - done
-- Available targets:
--      common_base
--      common
--      login-server
--      char-server
--      map-server
--      mapcache
-- Configuring done
CMake Error at src/common/CMakeLists.txt:147 (add_library):
  Cannot find source file:

    //winapi.hpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc


CMake Error at src/login/CMakeLists.txt:23 (add_executable):
  Cannot find source file:

    //winapi.hpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc


CMake Error at src/char/CMakeLists.txt:26 (add_executable):
  Cannot find source file:

    //winapi.hpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc


CMake Error at src/map/CMakeLists.txt:32 (add_executable):
  Cannot find source file:

    //winapi.hpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc


CMake Error at src/tool/CMakeLists.txt:33 (add_executable):
  Cannot find source file:

    //winapi.hpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc


CMake Error at src/common/CMakeLists.txt:147 (add_library):
  No SOURCES given to target: common_base


CMake Error at src/login/CMakeLists.txt:23 (add_executable):
  No SOURCES given to target: login-server


CMake Error at src/char/CMakeLists.txt:26 (add_executable):
  No SOURCES given to target: char-server


CMake Error at src/map/CMakeLists.txt:32 (add_executable):
  No SOURCES given to target: map-server


CMake Error at src/tool/CMakeLists.txt:33 (add_executable):
  No SOURCES given to target: mapcache


CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by Lemongrass3110** [comment]
Why do you try to create a Visual Studio file with CMake if you are on ARM?
You can simply use ./configure and everything should work from what I remember.
As @vstumpf pointed out though our current Visual Studio solution file only contains normal Windows x86/x64 platform targets.

**Comment by Lemongrass3110** [comment]
No further input for over half a year.
