### ISSUE TITLE
Limited Sale Window not opening

### ISSUE THREAD

**Issue by bgamez23** [rathena/rathena#6649]
* **rAthena Hash**: 27c0586d797ac7bf284eb0c82728e9dcec676719

* **Client Date**: 2021-11-17_Ragexe_1637052357

* **Server Mode**: Renewal

* **Description of Issue**: /limitedsale doesn't open the window. there is no invalid command showing if that command is not working.
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by Balferian** [comment]
This ui was removed from new clients.

**Comment by Lemongrass3110** [comment]
Duplicate of #5146
