### ISSUE TITLE
map-server crash (SG skills)

### ISSUE THREAD

**Issue by anacondaqq** [rathena/rathena#665]
# Problem

Map-server crash because of skill_id 429 while you die on the map marked as **Place of the Moon**
And by monster which marked as **Target of the Moon**.

Linux GDB tell me about this line: 

```
++count < SKILLUNITTIMER_INTERVAL/sg->interval && !status_isdead(bl) );
```

Map-server crashed because of sg->interval start to be a null, when you died.

Visual Studio Debug said to me when i was debug this shit about next:
```
First-chance exception at 0x00832598 in map-server.exe: 0xC0000094: Integer division by zero.
Unhandled exception at 0x00832598 in map-server.exe: 0xC0000094: Integer division by zero.
```

I was check sg->interval, and it was have 0 inside when i got crashed.

I do not know how to use Visual Studio to debug data, but linux GDB do not show full trace of the error, it's show only 1 string related to the problem.

## How reproduce

1. Mark with Feeling (2) the moc_fild22 the **Place of the Moon**
2. Mark the Ghost (Incasation of Morroc (ID 1921) as **Target of the Moon**
3. Get Link (Star Gladiator Spirit)
4. @spawn 1921
5. Use **Warmth of the Moon**
6. Monster must attack you, and you must run away from him.
7. When you will die -> the server will be crashed.

The chance to trigger this issue ~ 50 / 50

## Technical Information:
rathena hash: 64d2463e25429ea3b4c41fdedddde2e2fb2c60b0
pre-re, 2012-04-10, w/0 source modifications.

## Extra Screenshots

![](http://i.imgur.com/2M3ymZe.png)
![](http://i.imgur.com/QQe11Ye.png) (the last screenshot before crash)

## How i was fix it (it's stupid & weird)

Replace 
while part condition with example below
```
while( !status_isdead(bl) && x == bl->x && y == bl->y &&
						++count < SKILLUNITTIMER_INTERVAL / ((sg->interval)?sg->interval:SKILLUNITTIMER_INTERVAL) );
```

There i was add extra checks to make impossible zero value for divisions.

**Comment by anacondaqq** [comment]
Okay, i got complete stack with Visual Studio Debug, now i will provide there a details about how reproduce crash & debug info

**Comment by anacondaqq** [comment]
Okay, i'm going to upgrade rAthena to the latest one, and i will try to reproduce it again, maybe this issue with interval already fixed in the latest revision.

**Comment by anacondaqq** [comment]
# Finally.

100% Steps how reproduce this bug

1. Mark with Feeling (2) the moc_fild22 the **Place of the Moon**
2. Mark the Ghost (Incasation of Morroc (ID 1921) as **Target of the Moon**
3. Get Link
4. @spawn 1921
5. Use **Warmth of the Moon**
6. Monster must attack you, and you must run away from him.
7. When you will die -> the server will be crashed.

The chance to trigger this issue ~ 50 / 50

**Comment by Playtester** [comment]
The interval being set to 0 on dead is pretty bad itself, why it that even done?

**Comment by cydh** [comment]
Don't blame sg->interval can becomes 0. The interval itself can be set 0 in db.
Of course, when caster is dead (and the config is set) the skill unit will be cleared.

put `sg->interval > 0 &&` in first `while` condition, will fix that.
well, some code line with `UNT_FIREWALL` & `UNT_KAEN`.

**Comment by theultramage** [comment]
Aww, what timing. Thank you for describing the reproduction case for this other crash.
Devs, I'd like to point you to my analysis of this problem at [eathena #5144](https://eathena.ws/forum/tracker/issue-5144-firewall-triggering-land-protector-autocast-causes-read-of-freed-memory/) and https://github.com/HerculesWS/Hercules/issues/698. The ```sg->interval``` being 0 is just a side-effect of your ers code zeroing freed pages, the real issue is reading freed memory, because the skill unit dies inside of the loop. You should not be touching 'sg' at all, use src->alive instead which a lesser evil.

**Comment by cydh** [comment]
u can make SG clones, using `@evilcone` and `@clone` is enough to crash ur server.
