### ISSUE TITLE
Zeny disappear

### ISSUE THREAD

**Issue by panko11** [rathena/rathena#666]
I have a problem, when someone uses some good skill that costs zenny randomly or even the person zenny disappears. At first I thought it was only with classes and skills that had cost zenny (Mammonite, Cart Termination) the player uses the skill and reconnects and all its zennys disappear.
But now it happened to the Shura class that has no skill to use Zeny

**Comment by aleos89** [comment]
Please provide the hash you are on so we can properly help you.

**Comment by panko11** [comment]
I'm using the latest rev of the Emulator

**Comment by cydh** [comment]
well, hard to understand ur explanation.
try show us some screenshots, are u sure the char isn't under Masquerade Unlucky effect?
and, please don't say **latest**

**Comment by panko11** [comment]
basically if I get items in and out for a while back when the zenny is 0

**Comment by nanakiwurtz** [comment]
@panko11 https://rathena.org/board/blog/47/entry-82-bug-report/ thanks :+1:
