### ISSUE TITLE
Item 22540 doesn't work after update

### ISSUE THREAD

**Issue by Surefirer** [rathena/rathena#6664]
* **rAthena Hash**: 

3be73773f

* **Client Date**: 20211103

* **Server Mode**: Re

* **Description of Issue**: Runstone_Lux doesn't work after update
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**: None

**Comment by kaninhot004** [comment]
Confirmed.

https://user-images.githubusercontent.com/9493525/158044448-d69b65a7-e4cd-4337-9d4b-1b0d68131818.mp4

**Comment by cydh** [comment]
try add `Status: Luxanima` for `RK_LUXANIMA` on skill_db.yml
```diff
index 3a78835a1..9d74b3253 100644
--- a/db/re/skill_db.yml
+++ b/db/re/skill_db.yml
@@ -32613,6 +32613,7 @@ Body:
     Duration1: 900000
     Requires:
       SpCost: 1
+    Status: Luxanima
   - Id: 5006
     Name: NC_MAGMA_ERUPTION
     Description: Magma Eruption
     
```

**Comment by idk-whoami** [comment]
a032cd1f74448f676db7a22dfbcb8cf1bbe0ddd8
before fixed
map-server
![Capture](https://user-images.githubusercontent.com/60462533/158241512-fd58a344-578e-4de8-9946-c16cd20e2247.PNG)
```
[Error]: status_change_start: Unknown SC 744
[Error]: status_change_start: Invalid status change (-1)!
```

after fixed
> try add `Status: Luxanima` for `RK_LUXANIMA` on skill_db.yml
> 
> ```diff
> index 3a78835a1..9d74b3253 100644
> --- a/db/re/skill_db.yml
> +++ b/db/re/skill_db.yml
> @@ -32613,6 +32613,7 @@ Body:
>      Duration1: 900000
>      Requires:
>        SpCost: 1
> +    Status: Luxanima
>    - Id: 5006
>      Name: NC_MAGMA_ERUPTION
>      Description: Magma Eruption
>      
> ```
map-server
![Capture](https://user-images.githubusercontent.com/60462533/158241878-64408bf4-ce58-4c74-a287-e46b1f55a80e.PNG)
```
[Error]: status_change_start: Unknown SC 744
```
