### ISSUE TITLE
bonus3 bStateNoRecoverRace,r,x,t; not working properly

### ISSUE THREAD

**Issue by micosanityyy** [rathena/rathena#6665]
* **rAthena Hash**: Latest rAthena

* **Client Date**: 

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Item 16021 (Vellum Flail) uses bonus3 bStateNoRecoverRace,r,x,t; but not working properly, effect is not lasting 10 seconds. Disappears in less than a second.
  * Expected Result: In the item script, it should last 10 seconds
  * How to Reproduce: Try item 16021 to confirm
  * Official Information: 
  

* **Modifications that may affect results**: none

**Comment by aleos89** [comment]
Unable to reproduce on bf3b12b.
![image](https://user-images.githubusercontent.com/3521753/158877966-ffebf6b0-404d-4f6d-b093-c4a16e2e0c24.png)
