### ISSUE TITLE
RE: Mechanic Arms cannon no AoE-effect

### ISSUE THREAD

**Issue by Fraterna** [rathena/rathena#667]
well, suddenly Mechanic's Arms cannon does only singletarget damage, no AoE-effect no matter wich lvl i use 
image: i casted lvl 1 Arms cannon into the center of the ant eggs, only the one i targeted was hit, the surrounding not.
![screenno-mercy odin009](https://cloud.githubusercontent.com/assets/12772676/10337722/fa9d8488-6d01-11e5-9ecf-73c7d7b3535a.jpg)

**Comment by cydh** [comment]
confirmed.. just based on d95f5d2db75c10435421fe396dc86e7be9654be5
> * Fixes #537 - Arms Cannon is now a single unit target skill.

but, there was misunderstand there, should be 'single target with area effect'.
