### ISSUE TITLE
Vending Table store wrong coordinate if merchant warped during vending state.

### ISSUE THREAD

**Issue by Emistry** [rathena/rathena#6671]
* **rAthena Hash**: 
https://github.com/rathena/rathena/commit/73a8d1365e84252e37185f8c579a8825abd925c4

* **Client Date**: 
2018-06-20

* **Server Mode**: 
RE

* **Description of Issue**: 
  * Result: 
![image](https://user-images.githubusercontent.com/1075099/158066581-96a03595-c1be-402d-b41e-a54150ece349.png)

  * Expected Result: 
      -  If vending shop is active, shouldn't allow warp.
      - or database should reflect latest warp location (or at least re-update upon used `@autotrade`?)
      - or remove vending shop upon warped.
     
  * How to Reproduce: 
  
      - Create a merchant with vending skill, add an item to vending shop (but I was testing using a lv99 GM merchant).
      - Open the shop (locationed stored to db i guess), then type `@warp` or `@jump` with vending shop still active.
      - After warped, vending shop still remain active, but actual location changed from `(256, 143)` to ` (104,316)`, but db remained as `(256, 143)`.
      - Type `@autotrade`
      - Login another user to check the location, using `@whomap3` it actually reflect the correct location which is ` (104,316)` and search for the vendor, but db storing the old location `(256, 143)` (before merchant used `@warp`).
  
  * Official Information: 
  

* **Modifications that may affect results**: 
None

**Comment by aleos89** [comment]
A quick glance shows that the only time a vending store is closed is if the player changes maps to where vending is disabled, the player is warped to a cell that vending is disabled, or the player changes map servers. I didn't see anything else offhand that would stop the x/y coordinates from being updated.

**Comment by aleos89** [comment]
Sorry I thought you had your char table open instead of the vending table. Cydh pointed that out to me and the problem is because we don't have a function which sends an update to the vending table if something about the player changes once the shop is open.
