### ISSUE TITLE
Aftercast cooldown counter not showing

### ISSUE THREAD

**Issue by jofvgaming** [rathena/rathena#6675]
rAthena Hash: Latest

Client Date: 20180621
Server Mode: Both
Description of Issue:
After using skill aftercast delay counter cooldown on casted skill not showing on the screen/ skill hotkey, not using maxASPD and Reduce Aftercast Delay items/cards.

**Comment by Lemongrass3110** [comment]
![grafik](https://user-images.githubusercontent.com/3517879/158178038-e6d12cde-f8c1-4886-9ed1-79d516e65c36.png)

Shows perfectly fine for me?
