### ISSUE TITLE
issue main.sql table skill type column lv

### ISSUE THREAD

**Issue by zdurexz** [rathena/rathena#6681]
* **rAthena Hash**: 

* **Client Date**: 20211117

* **Server Mode**: Both

* **Description of Issue**: 
  * Result:  
![image](https://user-images.githubusercontent.com/59825922/158214609-a7050c17-0ba4-4a6c-846e-410990917a2f.png)

  * Expected Result: type tinyint(4) to int(11)
  * How to Reproduce: type tinyint(4) to int(11)
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by zdurexz** [comment]
Rogue's use skill snatch

**Comment by Lemongrass3110** [comment]
Yeah but then increasing from tinyint to int does not help.
The problem is the signedness.
But I always thought that those rogue skills were stored in player variables.

**Comment by Lemongrass3110** [comment]
@zdurexz did you find the problem?

**Comment by zdurexz** [comment]
@Lemongrass3110 sql error skill lost
