### ISSUE TITLE
MapServer error using item 22540

### ISSUE THREAD

**Issue by idk-whoami** [rathena/rathena#6685]
* **rAthena Hash**: 213406013d9724bfecf4c89db9436603f022b22f

* **Client Date**: 20211103

* **Server Mode**: re

* **Description of Issue**: Ubuntu 21.04

https://user-images.githubusercontent.com/60462533/158319180-08934a15-3c5d-48b8-9de0-9a117c130574.mp4
```
[Error]: status_change_start: Unknown SC 744
```
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by eppc0330** [comment]
Confirm. Same issue on my server too.

**Comment by eppc0330** [comment]
Try add ```Icon: EFST_REUSE_LIMIT_LUXANIMA #PC official``` for ```- Status: Reuse_Limit_Luxanima``` on status_db.yml

**Comment by idk-whoami** [comment]
> Try add `Icon: EFST_REUSE_LIMIT_LUXANIMA` for `- Status: Reuse_Limit_Luxanima` on status_db.yml

Thanks! it works
