### ISSUE TITLE
Skill 'Reflect Damage Reduction' does damage to caster

### ISSUE THREAD

**Issue by kaninhot004** [rathena/rathena#6693]
* **rAthena Hash**: 79d978e01

* **Client Date**: 20211103

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Skill `Reflect Damage Reduction` does damage to caster when cast Lv.5 `Cannon Spear` (Only happen on my live server: Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-104-generic x86_64), If tested on my PC it not bug.)
  * Expected Result: Skill `Reflect Damage Reduction` should not damage to caster when cast Lv.5 `Cannon Spear`
  * How to Reproduce: `@job 4258
@lvup 999
@joblvup 999
@statsall 30000
@traitall
@item 530019
@item shield
@item 2105
@item 24289
@item 24578
@refine 0 99`
then had buff `Reflect Damage Reduction` and cast Lv.5 `Cannon Spear` to enemy. (Lv. <= 4 not bug)
  * Official Information: -

* **Modifications that may affect results**: -

*Checked `git diff` on live server, no changes between my PC and live server about db, src folders.

https://user-images.githubusercontent.com/9493525/158746980-e0d5b3e4-5fc6-43e3-ad87-a291d1e22048.mp4

**Comment by eppc0330** [comment]
I can't check issue in my server. Is the eggs in your video using reflecting skill or any other special situation?

**Comment by kaninhot004** [comment]
I see.
Please try equip 24289 and 24578

**Comment by eppc0330** [comment]
> I see. Please try equip 24289 and 24578
> 
> and also use `@statsall 30000`
> 
> It seem happen when damage very high.

![CR_RDR](https://user-images.githubusercontent.com/47050704/158567149-841f40d5-339d-40d5-91bb-cbb2ae30efeb.gif)

Sry still no effect

**Comment by kaninhot004** [comment]
Thanks! I will try re-compile my server.

If it won't happen again. I will close this issue.

**Comment by kaninhot004** [comment]
It's only happened on live server not sure why.
System information: Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-104-generic x86_64)

When I tested on my PC it won't happened.

Also if use Lv.1 Cannon Spear it's not bug. (Because range 3x3)

I will re-open this issue and give more information later.

**Comment by kaninhot004** [comment]
More information

Please use `@traitall`

Confirm only happen on linux.

**Comment by aleos89** [comment]
Was this something that popped up after the SC YAML commit? Just trying to null out pieces.

**Comment by kaninhot004** [comment]
@idk-whoami  said he test on e74bbfd37 still had issue.

**Comment by aleos89** [comment]
By looking back at your gear and the stat command you're running, I would assume there's an overflow in the damage calculation, which just happens to be enough difference in the level 4 -> 5 bonus.

If you don't increase your stats to 30k, does it behave normally?
