### ISSUE TITLE
Lux Anima

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#670]
The rune lux Anima is giving crash in mapserver.

Topic: https://rathena.org/board/topic/103381-rune-knight-skill-lux-anima-rune-item/

**Comment by aleos89** [comment]
Just a guess by taking a quick look is it's failing when sd is null:
```if( !sd->status.party_id || flag&1 ) {```
Should add a check:
```if( !sd || !sd->status.party_id || flag&1 ) {```
