### ISSUE TITLE
Reading Spell Book and Comet not working properly

### ISSUE THREAD

**Issue by Relliksuriv** [rathena/rathena#6705]
* **rAthena Hash**: 

* **Client Date**:  20210107

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result:  Reading Spell Book sometimes cannot be casted and or cannot use any book for that matter especially above 3 spells. 
  Additional: Comet For some reason doesn't use the Magic Poison Status effect even if it is indicated on Status DB and was instead using burn.
  * Expected Result:  You can do the things above
  * How to Reproduce:  Use reading spell book Issue started after the Status Change DB update
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
I'm only able to confirm the Magic Poison issue. Reading the Spell Book items works just fine for me testing on 00be4ee.

Keep in mind you must use Release each time for every skill you've preserved, unless this behavior has changed on kRO.

**Comment by Relliksuriv** [comment]
The reading spell book and release seems to be having an issue.

here is one:
https://drive.google.com/file/d/1jck8JjpZ6zIfV4J1yjVtqIJGnVn_6qTH/view?usp=sharing

and if I am not mistaken when player casts the Comet Skill they can Immediately use RELEASE of another Comet skill but you enter a skill cooldown.

**Comment by Relliksuriv** [comment]
Here is how the Issue can be replicated.

Read spell book until full slot -> Die -> Respawn -> Can't read anymore -> Can't release skill

So basically i think dying still retains the save slot but the release skill can't access it and using reading just says not enough save point.

This issue can be cleared by resetting skill then dying then resetting again which is annoying.
