### ISSUE TITLE
Reflecting skills damage type

### ISSUE THREAD

**Issue by eppc0330** [rathena/rathena#6709]
* **rAthena Hash**: master

* **Client Date**: 20211117

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Reflecting damage type is not weapon.
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: According to official KRo behavior, damage type of reflected magic skill is special short weapon damage.
  Corresponding skills: NPC_MAGICMIRROR. (```bonus bMagicDamageReturn,n;``` still reflects as magic type damage. Just for NPC_MAGICMIRROR)
So in official KRo I can activate weapon triggered autospell by NPC_MAGICMIRROR. 
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Fixed in 2896ae2.

**Comment by Daegaladh** [comment]
There's still some skills to be fixed

**Comment by aleos89** [comment]
Fixed in [c979ed7](https://github.com/rathena/rathena/commit/c979ed74722d62a64c5883579d0c203105ea4639).
