### ISSUE TITLE
bug laphine synthesis

### ISSUE THREAD

**Issue by bruxo99** [rathena/rathena#6710]
* **rAthena Hash**: 5193fd6c92bac2d2db3cb88e128e5c404389980d

* **Client Date**: 20211103

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: When using equipment items in the requirement in laphine synthesis.yml generates a bug when doing the combination
  * How to Reproduce: 
  * rathena\db\re\laphine_synthesis.yml
  *
  - Item: Bs_Item_M_S_2
    RewardGroup: BS_ITEM_M_S_2
    RequiredRequirementsCount: 2
    Requirements:
      - Item: Knife
        Amount: 1
      - Item: Cotton_Shirt
        Amount: 1

  * data\luafiles514\lua files\datainfo\lapineddukddakbox.lub
  
		["Bs_Item_M_S_2"] = {
			ItemID = 23818,
			NeedCount = 2,
			NeedRefineMin = 0,
			NeedRefineMax = 20, 
			SourceItems = {
				{ "Knife [3]", 1, 1201},
				{ "Cotton Shirt", 1, 2301}
			},
			NeedSource_String = "Knife [3], Cotton Shirt"
		},

  * in-game `@item 23818` then `@item 1201 2`
now you can make the combination without needing the other item

**Comment by Lemongrass3110** [comment]
I dont think that this is bug.
It rather is intended like this.

**Comment by Atemo** [comment]
Upon testing on official server the combination requires NeedCount items (here 2) using different inventory slots, regardless of the item. In your example 2 `Knife [3]` or 2 `Cotton Shirt` or 1 `Cotton Shirt` + 1 `Knife [3]` are valids.

In the case of stackable items using 2 inventory slots, for example with
```
Bs_Item_M_S_2 = {
	ItemID = 23818, NeedCount = 2, NeedRefineMin = 0, NeedRefineMax = 20, 
	SourceItems = {
		{"Zelunium", 10, 25731}, 
		{"Token_of_OrcGeneral", 150, 25508}
	}
```
`Zelunium` + `Token_of_OrcGeneral` is the only valid combinaison
