### ISSUE TITLE
Stuck on Guardian of Rock Ridge (Hard)

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#6712]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/5193fd6c92bac2d2db3cb88e128e5c404389980d

* **Client Date**: 20211103

* **Server Mode**: RENEWAL

* **Description of Issue**: 
  * Result:  
  
Stuck on Steel Vigilante#2 4_M_ACROSS after talk with Steel Vigilante#1 4_M_MASKMAN

Steel Vigilante#2 4_M_ACROSS always stuck on 

https://github.com/rathena/rathena/blob/bf3b12bc3d7b2edd9aafdd0f26296c384b2a5d5a/npc/re/quests/quests_rockridge.txt#L3677
  
```
  	if (isbegin_quest(12389) == 2) {
		mes "[Steel Vigilante]";
		mes "Mm? You're not one of us. If you need a job, then you should look elsewhere.";
		close;
	}
```
  
  * Expected Result: 
  
This NPC should work
  
  * How to Reproduce: 
  
First talk to Steel Vigilante#1 4_M_MASKMAN then talk to Steel Vigilante#2 4_M_ACROSS

Maybe related this script on Steel Vigilante#1 4_M_MASKMAN

https://github.com/rathena/rathena/blob/bf3b12bc3d7b2edd9aafdd0f26296c384b2a5d5a/npc/re/quests/quests_rockridge.txt#L3527

```
		mes "[Steel Vigilante]";
		mes "How about I show you the list of things you could do for us? If you're interested, come back later. I promise I'll pay you generously.";
		setquest 12389;// Guardian of Rock Ridge
		completequest 12389;// Guardian of Rock Ridge
```

  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by dimasshotta** [comment]
is it supposed to be this way?

	if (isbegin_quest(12389) < 2) {
		mes "[Steel Vigilante]";
		mes "Mm? You're not one of us. If you need a job, then you should look elsewhere.";
		close;
	}

**Comment by mazvi** [comment]
> is it supposed to be this way?
> 
> ```
> if (isbegin_quest(12389) < 2) {
> 	mes "[Steel Vigilante]";
> 	mes "Mm? You're not one of us. If you need a job, then you should look elsewhere.";
> 	close;
> }
> ```

Maybe? Waiting for @Atemo
