### ISSUE TITLE
malangdo costume NPC Menu too long Warning

### ISSUE THREAD

**Issue by Surefirer** [rathena/rathena#6721]
* **rAthena Hash**: 
Latest

* **Client Date**: 20211103

* **Server Mode**: Re

![error](https://user-images.githubusercontent.com/46170182/159131687-73a3bcc0-dff5-44fa-b57b-1374069d538a.png)

* **Description of Issue**: malangdo costume NPC Menu too long Warning
* 
  * Result: 
  * Expected Result: 
  * How to Reproduce: Click Aver De Dosh, when click to the stone selection menu, check console
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by Pokye** [comment]
Duplicate https://github.com/rathena/rathena/issues/6609

**Comment by Surefirer** [comment]
The menu only show like 56ish stones, does not show the rest.
