### ISSUE TITLE
Star Gladiator Clone Causes map-crash

### ISSUE THREAD

**Issue by lordganja** [rathena/rathena#673]
I'm using Git Hash: '34c19edf774da39cd5af70638e38c7ef484df41b'

I can't actually point out what exactly causes the map-crash. But it only crashes when the clone of a group that has 'skill_unconditional: true' start to attack.

I can reproduce this by using @evilclone and @clone, when the two clones started to fight each other the map-server crash.

It actually doesn't make too much sense since only the group with skill_unconditional:true causes the mapcrash, which is usually admins/gm's. But maybe it would still be helpful if this will be fixed.

**Comment by cydh** [comment]
Interesting.
u know there were many people say "clone" makes server crash, but no of them gave any clue. I'll try this.

**Comment by lordganja** [comment]
Alright. Thanks @cydh :+1:

**Comment by cydh** [comment]
well, I just found the TK_COUNTER that cause this crash.
````
 		case TK_COUNTER: {	//bonus from SG_FRIEND [Komurka]
 			int level;
-			if( sd->status.party_id>0 && (level = pc_checkskill(sd,SG_FRIEND)) )
+			if( sd && sd->status.party_id > 0 && (level = pc_checkskill(sd,SG_FRIEND)) )
 				party_skill_check(sd, sd->status.party_id, TK_COUNTER,level);
 			}
 			break;
````

**Comment by evilclone** [comment]
Why am I getting these emails and what is it about



Sent from my Verizon Wireless 4G LTE smartphone


-------- Original message --------

**Comment by nanakiwurtz** [comment]
(OOT) @evilclone: Unsubscribe from GitHub notification to stop getting emails like these
