### ISSUE TITLE
Dragon Breath does no work the way it's intended

### ISSUE THREAD

**Issue by victorrlo** [rathena/rathena#6734]
* **rAthena Hash**: 

* **Client Date**: 2021

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result:  
   Dragon Breath Skills both act as if Hard DEF is Hard DEF.

  * Expected Result:  
  Dragon Breath Skills both should calculate damage just like Cart Cannon and Arms Cannon, treating Hard DEF as Soft DEF (or kind of "ignoring DEF").

  * How to Reproduce: 
  Testing damage, after you use some kind of ignore DEF equipment, the damage is hugely different compared to the same when testing with Cart Cannon that works the same way.

  * Official Information: 
  Many sources from kRO and even Sigma(from Divine-Pride) states himself that Dragon Breath treats Hard DEF just like Cart Cannon: as Soft DEF. You can see it here: https://www.divine-pride.net/forum/index.php?/topic/3723-kro-jobs-improvement-project/page/13/#comment-11057

  

* **Modifications that may affect results**:

**Comment by victorrlo** [comment]
https://www.divine-pride.net/forum/index.php?/topic/4233-note-additional-genetic-improvements/
![image](https://user-images.githubusercontent.com/42052096/159595729-a99611c6-c8bd-4d0d-b2ab-da39490cf138.png)

**Comment by Lemongrass3110** [comment]
https://github.com/rathena/rathena/issues?q=is%3Aissue+is%3Aopen+dragon+breath
