### ISSUE TITLE
Trample is not removing this active Trap Electric Shock

### ISSUE THREAD

**Issue by panko11** [rathena/rathena#674]
http://irowiki.org/wiki/Trample
http://irowiki.org/wiki/Electric_Shock

She's removing usually you're not under the influence of trap. Now if you are under the effect it removes the trap however you keep missing and imprisoned SP

**Comment by MrAntares** [comment]
Since trample's area is 5X5 and Electric shocker's area is also 5X5, you will always detonate the trap before havin a chance to cast the skill to destroy it, thus you will always receive the effect.
