### ISSUE TITLE
SC_STONE not ending on damage + getting overriden by other opt1 status change

### ISSUE THREAD

**Issue by Singe-Horizontal** [rathena/rathena#6748]
* **rAthena Hash**: 
Latest

* **Client Date**: 
Any

* **Server Mode**: 
Both

* **Description of Issues**: 
- SC_STONE is not ending on damage received due to a missing flag in  status.yml
- It's also getting overriden by other opt1 based status change such as freeze, stun due to a missing line in status.yml
- It gets overriden when receiving any buff while transforming from StoneWait

**Comment by mazvi** [comment]
may need to be added too. when the stone curse occurs players can still perform skills, is it really like this? because at rathena at this time when the stone curse occurs players can perform skills. shouldn't it be?

**Comment by Playtester** [comment]
On pre-renewal you definitely shouldn't be able to use skills when stone cursed, just move. Probably got bugged too then.

**Comment by Playtester** [comment]
Hint: I tested this in pre-renewal and the only issue I could reproduce is that stone isn't broken on damage although it should.
I could not use any skills while in stone curse and it didn't look like I could be frozen either (I tested with Frost Diver). Waiting out the duration ended the SC properly. No need to relog as other reports stated.

**Comment by mazvi** [comment]
> 

stuck if it occurs when the stone curse occurs when you die, or the monster dies. try when hit by the stone curse and then you die, after returning to the save point you will be stuck
