### ISSUE TITLE
Custom Quest

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#675]
Hello good afternoon, I am having trouble custons add quests, the emulator reads the quests, but does not recognize.

see pictures:

http://i.imgur.com/AmxpxPJ.png

**Comment by icxbb-xx** [comment]
please check you quest custom add to

db/pre-re/quest_db.txt  or db/re/quest_db.txt

make sure

**Comment by admkakaroto** [comment]
Already added

http://i.imgur.com/JZeS601.png

**Comment by Lemongrass3110** [comment]
Could you please add your custom quests to "db/import/quest_db.txt" and post another screenshot like 
http://i.imgur.com/AmxpxPJ.png where we can see if it really loaded without errors.

Thank you.

**Comment by cydh** [comment]
yo, don't use Quest ID beyond 65535. Thank you.
