### ISSUE TITLE
unable to save monster_ai settings to 0x800

### ISSUE THREAD

**Issue by xZee0523** [rathena/rathena#6751]
* **rAthena Hash**: d282682

* **Client Date**: 2020-04-10

* **Server Mode**: pre-renewal

* **Description of Issue**: unable to set monster AI to 0x800 -- When set, monsters that are provoked will always change target to the provoking person, even if they would usually not change target on attack.
  * Result: getting a warning that the value for the setting is invalid, defaulting to 0
![help](https://user-images.githubusercontent.com/100657535/160314794-73653d21-fb01-43cb-9070-4f8ff8c208de.PNG)

  * How to Reproduce: set 0x800 on monster_ai and @reloadbattleconf

**Comment by xZee0523** [comment]
bump, any clarification to this?

**Comment by aleos89** [comment]
Looks like the max is set to 0x77f for some reason, which is why it's not letting you set it to 0x800.
