### ISSUE TITLE
1 damage  255 to 500vit using 2dagger thanaphree2hydra 2hydra2tg then use GR DEVILING  then 300vit there will be 1 damage ...Pre-Re Player Soft (VIT)DEF Formula #6648 

### ISSUE THREAD

**Issue by zhakyvea** [rathena/rathena#6752]
1 damage with high def 255vit to 500vit using 2hand dagger thanatosphreeoni2hydra 2hydra2turtlegeneralcard
armor gr card
manteau deviling card
with +10items 

try the vit 300 then use 2hand dagger using thanaphreeoni2hydra 2hydra2tg
then use armor GR and Deviling Card

this is issue please fix this 1 damage 255vit to 500vit +10items

**Comment by zhakyvea** [comment]
Pre-Re Player Soft (VIT)DEF Formula #6648

related on this

**Comment by Atemo** [comment]
The description of your problem is incomprehensible. Can you reformulate it please?

**Comment by zhakyvea** [comment]
Job Asassin Cross The Dual Weild 2Handed Dagger Using ThanatosPhreeoni2Hydra Left Right 2Hydra2TurtleGeneral 
Then Ur Vit Is 300 Then Ur Items Is +10 So We Have 90+300 Damage Will Have 1 Damage

**Comment by zhakyvea** [comment]
1Handed Will No 1 Damage Even Vit Is 300 to 999 Using Thanatos Card In Left Hand No Weapon In Right Hand 

2Handed Dagger Have 1 Damage 300 to 999vit Using Thanatos In Left Hand And  2Hydra2TG Right Handed 
Asassin Cross <----- Dual Weilding But The Problem Is The Thanatos Card <<<<<

**Comment by Everade** [comment]
Follow the bug report template by filling all the information the template is asking for. Please also try to write in complete and comprehensible sentences. It is crucial that devs have all the required information and understand your report in order for them to reproduce and possibly fix it.

Thank you for your understanding.
