### ISSUE TITLE
Monsters drops with different rates

### ISSUE THREAD

**Issue by hannicaldummy** [rathena/rathena#6756]
* **rAthena Hash**: d2826827dfa3e5e880f64f3cce1be53a60af4867

* **Client Date**: 2021 11 17

* **Server Mode**: Both(Pre and RE)

* **Description of Issue**: With a clean copy of master just by compiling and open when I use  ``` `@mi` ```  <ID> all monsters shows different drop rates, for exemplo Poring Card drops at 0,01% but Pupa Card drops at 0,08% without change anything, if I try to change the drop rate from 100 to 1000 for example the Poring Card start to drop at 0,80% and Pupa Cart at 1,01%(wtf)
  * Result: Each monster has a % drop different, we can use the Card drop who should be always 0,01% in a clean master copy 
  * Expected Result: All monster cards should be 0,01 or at least the same rate as we set in conf/battle/drops.conf 
  * How to Reproduce: JJust compile, open and use ``` `@mi` ``` 1002 / 1008
  * Official Information: Same drop rate for all cards
  

* **Modifications that may affect results**:

**Comment by Playtester** [comment]
On current revision pre-renewal it works fine for me.

**Comment by gen1x9** [comment]
it's because rate mob-db drop database renewal different from pre-renewal. open mob_db.yml renewal, you can see that poring card has drop rate 20 (0.2%).

**Comment by Playtester** [comment]
Maybe his example is wrong then, because he reported Pupa Card drop rate to be higher than Poring Card drop rate. Everything else you can explain with the higher drop rate of Poring Card and potentially drop penalty due to level difference.

**Comment by Vaans** [comment]
I'm using a commented version of renewal drops but with renewal system, and seems that didn't take effect. Still having renewal drops.

to recompile this option, only need to ./compile&&make clean&&make server right?.

**Comment by Lemongrass3110** [comment]
Please use discord for support questions.

**Comment by aleos89** [comment]
Yes, anything changed in src/ needs to be re-compiled.

As for the original report issue, renewal has penalties based on the player and mob level. Please see db/re/level_penalty.yml for more information.
