### ISSUE TITLE
Stone Curse Bug Unable to move after death need to relog to be able to move

### ISSUE THREAD

**Issue by ryomahostingph** [rathena/rathena#6762]
* **rAthena Hash**: 

* **Client Date**: 2021-11-17_Ragexe_1637052357.exe

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result:  Cannot Move and Remove Stone Curse even in Death, you need to Relog or Character Select to remove the Status of Stone Curse
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by Daraen1** [comment]
related to the #6749 ?

**Comment by ryomahostingph** [comment]
>

**Comment by aleos89** [comment]
Yes, it should be related to the link pull request.

**Comment by ryomahostingph** [comment]
Uploading 2022-03-30 04-35-24 (online-video-cutter.com).mp4…

here sample video

**Comment by Daraen1** [comment]
we can't see anything, can you reupload video here?
