### ISSUE TITLE
missing status for 4th job

### ISSUE THREAD

**Issue by dimasshotta** [rathena/rathena#6763]
rAthena Hash: https://github.com/rathena/rathena/commit/f28d20727446b2807c411d6f92de6afa949de849
Client Date: 2021 11 17
Server Mode: Both(Pre and RE)
Description of Issue: status skill for 4th job is not added. (e.g servant_wepon,climax,etc)
Result: missing status in the skill_db and status.yml making the skill doesn't work.
Expected Result: add the status for 4th job skill
Official Information: -

**Comment by aleos89** [comment]
Update to a more recent version (preferably to today if you can). We've made several follow up fixes to the status.yml implementation.
