### ISSUE TITLE
Segmentation fault (core dump)s from 'item_db' on latest commit

### ISSUE THREAD

**Issue by dralucon87** [rathena/rathena#6768]
* **rAthena Hash**: 80b133c08fc36257bfb974648218ba36b9721bf3

* **Client Date**: 

* **Server Mode**: Pre-renewal

* **Description of Issue**:
  * Result: 
  * Expected Result: 
  * How to Reproduce:  Run server in SQL mode
  Download the patch file to the rathena repo 

run git apply patch3.30.2022.txt
this will set the packetver to 20200902, set the server mode to pre-re, and enable sql db

start up rathena, tester used docker by following readme in /tools/docker
namely: 'docker-compose up -d', 'docker-compose run builder bash'

in docker bash the tester ran 'make clean server', The build ran then in docker bash 'exit'.
in terminal 'docker-compose down', 'docker-compose up -d'

After a moment the map-server exited non-zero while loading 'item_db'

[message (2).txt](https://github.com/rathena/rathena/files/8385237/message.2.txt)
[patch3.30.2022.txt](https://github.com/rathena/rathena/files/8385238/patch3.30.2022.txt)

**Comment by Lemongrass3110** [comment]
Please provide a crash dump.
Otherwise we cant help or look into the issue.

**Comment by dralucon87** [comment]
[log.txt](https://github.com/rathena/rathena/files/8393665/log.txt)
Hope this is the file you're looking for.
