### ISSUE TITLE
Magnetic Earth dont remove Thorn Trap and effect

### ISSUE THREAD

**Issue by panko11** [rathena/rathena#677]
http://irowiki.org/wiki/Thorn_Trap
http://irowiki.org/wiki/Magnetic_Earth

Is not removing the traps from the ground and not removing its effect after using Magnetic Earth

**Comment by MrAntares** [comment]
"Examples of skills that work on Magnetic Earth (that seemingly target the ground)
Fiber Lock, Ankle Snare, Land Mine, Shockwave Trap, etc
All Dancer/Bard non-ensemble dances/songs"

-.-

**Comment by panko11** [comment]
oh I'm sorry, and I'm the player bRO and its wiki is currently offline so I'm having to turn around with my bad English and using iro wiki

**Comment by MrAntares** [comment]
Uhm, bRo is not considdered "official", neither iRo. We follow kRo. Only in case of lack of information we use other sources, but even in that case, we prefer jRo, iRo, and the orhers in this order.
