### ISSUE TITLE
Stone curse bug again

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#6774]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/9bc1c53db443d1ceb78d74ef2c9f24d677123072

* **Client Date**: 20211103

* **Server Mode**: RE

* **Description of Issue**: 
  * Result: stuck after dead and return to savepoint
  * Expected Result: player can walk after dead/revive
  * How to Reproduce: Stone curse player A, and kill player A, then player A dead when stone curse active, player A return to savepoint, and will be stuck until end of the world (re-login is temp solution)

other than the above. if the player is hit by the stone curse from a monster then the monster dies, the stone curse remains on the player forever. please try on infinite space instance. 

  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by ryomahostingph** [comment]
same, this was fixed in here https://github.com/rathena/rathena/pull/6749

**Comment by aleos89** [comment]
Duplicate to #6748.
