### ISSUE TITLE
src/c4/yml/tree.cpp:1583: check failed: ( is map(node)) error on latest commit

### ISSUE THREAD

**Issue by L4M3573R** [rathena/rathena#6787]
* **rAthena Hash**:  b3343df2ab31cc3ea331fdbce6d26e8133d14daf

* **Server Mode**:  pre-re but most likely renewal aswell

* **Description of Issue**: map-server crash using SQL mode on Ubuntu 21.10
  * How to Reproduce: on Ubuntu 21.10 put server into SQL mode, compile and upon startup it crashes map-server. crash dump is attached.
[crash dump.txt](https://github.com/rathena/rathena/files/8403406/crash.dump.txt)

**Comment by Lemongrass3110** [comment]
This should have been fixed in 163f8c2 from @aleos89.
Are you sure that you are on the hash that you said?

**Comment by dralucon87** [comment]
Before the problem was with item_db(which is fixed now), now it's mob_db.
