### ISSUE TITLE
(26652B):ERROR: ': ' is not a valid token in plain flow (unquoted) scalers

### ISSUE THREAD

**Issue by L4M3573R** [rathena/rathena#6788]
* **Server Mode**:  prere but probably affecting renewal aswell

* **Description of Issue**: using import/mob_db.yml makes map-server crash
  * How to Reproduce: compile server on ubuntu 21.10 in yaml mode using import/mob_db.yml and it gives errors when using : in the yml database type.
  crash dump and photo to show.
![import mob_db entry in question](https://user-images.githubusercontent.com/87735573/161403020-51b00e6f-1c67-4214-8ac4-6ee5e695f92f.PNG)
![Capture](https://user-images.githubusercontent.com/87735573/161403021-19fbce37-dfd8-4efe-b79b-53863a1a4dd2.PNG)
[crash dump.txt](https://github.com/rathena/rathena/files/8403446/crash.dump.txt)

**Comment by Lemongrass3110** [comment]
Can you please post your YML file that causes the crash?

**Comment by dralucon87** [comment]
[mob_db.zip](https://github.com/rathena/rathena/files/8403540/mob_db.zip)
If import/mob_db.yml is cleared it works fine. If mob is in import/mob_db.yml it gives error.

**Comment by aleos89** [comment]
I can't see from your screen shot and can't view your zip from my current device, but make sure you have `Body:` defined in the import file as well!

**Comment by L4M3573R** [comment]
@aleos89 OMG I feel dumb, thanks for that.
