### ISSUE TITLE
Different items list in tool dealers

### ISSUE THREAD

**Issue by Takiusu** [rathena/rathena#6791]
* **rAthena Hash**: latest

* **Client Date**: 2021-11-17

* **Server Mode**: Renewal

* **Description of Issue**: Tool Dealers have wrong item list
  * Result: 
  * Expected Result: Their items list should be the same as screenshots
  * How to Reproduce: Change items list according to the screenshots
  * Official Information: Screenshots from kRO

* **Modifications that may affect results**: 
  
  
![unknown-1](https://user-images.githubusercontent.com/65616872/161545042-f7755eb7-c421-4606-9742-a7c8a16d07fc.png)
![unknown-2](https://user-images.githubusercontent.com/65616872/161545063-f62c7ea5-e457-44e0-8db6-cb14042ca10b.png)
![unknown-3](https://user-images.githubusercontent.com/65616872/161545077-273dd003-16fb-4f27-a088-aa41401f51c1.png)

**Comment by Pokye** [comment]
Have you checked with that? https://github.com/rathena/rathena/commit/50d7c4052fbc248faa25cf4b336e2063dc5dd2a6 ( npc/re/merchants/Dealer_Update.txt ) Because JohnnyPlayy has updated many stores too.
