### ISSUE TITLE
Acid Bomb 

### ISSUE THREAD

**Issue by panko11** [rathena/rathena#680]
http://irowiki.org/wiki/Acid_Bomb

This taking direct element and is not as neutral as it is the correct

--

Correction:
db/re/skill_db.txt
Change:
490,9,8,1,-1,0x60,0,10,1:2:3:4:5:6:7:8:9:10,yes,0,0,0,misc,0,0x0,	CR_ACIDDEMONSTRATION,Acid Demonstration

for:
490,9,8,1,0,0x60,0,10,1:2:3:4:5:6:7:8:9:10,yes,0,0,0,misc,0,0x0,	CR_ACIDDEMONSTRATION,Acid Demonstration

**Comment by MrAntares** [comment]
Read:
http://irowiki.org/wiki/Acid_Bomb#Notes

This is working as intended.
