### ISSUE TITLE
C4244 warning : conversion from 'double' to 'uint16', possible loss of data

### ISSUE THREAD

**Issue by eppc0330** [rathena/rathena#6801]
* **rAthena Hash**: #6764 

* **Client Date**: 20211117

* **Server Mode**: Renewal

* **Description of Issue**: 
  status.cpp(8733,18) C4244 warning on this part :
  ```uint16 levelAdv = (pow(max(0, status_get_lv(src) - status_get_lv(bl)), 2) / 5) * 100;```

  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by Daegaladh** [comment]
This will be fixed in #6794
