### ISSUE TITLE
Log Laphine system not Work

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#6808]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/cee161e677df4d61a9c76be7d789d68f1524bc0d

* **Client Date**: 20211103

* **Server Mode**: RE

* **Description of Issue**: 
  * Result: Log Laphine system not Work
  * Expected Result: Log Laphine system Work
  * How to Reproduce:  Use item 23676 select 13441 then check log
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment]
This was already fixed in 2172bb8 so that it works by default again.
Make sure your log settings are correct and that your log tables have the correct enum values defined.

![grafik](https://user-images.githubusercontent.com/3517879/162614371-20b9a27f-c06d-4855-86e1-8416b531c58b.png)

**Comment by mazvi** [comment]
I've checked on all SQL Upgrades that there is no added W in the upgrade log.

https://github.com/rathena/rathena/blob/master/sql-files/upgrades/upgrade_20220222_logs.sql
