### ISSUE TITLE
Hover is not working against pitfalls of 3rd and magic attacks.

### ISSUE THREAD

**Issue by panko11** [rathena/rathena#681]
http://irowiki.org/wiki/Hover

Hover is not working against traps of 3rd and magic attacks.

**Comment by aleos89** [comment]
Keep in mind, iRO is not the best source of information.

This is the last bit of specific information we have. I'd have to do more testing to confirm if it blocks 3rd class traps or other skills, but it most likely hasn't changed since.

**Comment by panko11** [comment]
Well, I'm not finding any source, wiki bRO and own server some skills were also blocked as the trap 3rd and a few more wizard skills, but it seems that is not working anymore did all tests and this right the skill, I sorry about that invalid report

**Comment by Paoly28** [comment]
i also noticed this, should block several ground aoe such as storm gust, earth dive , earth strain , earth spike, heaven's drive , all 3rd job traps and hell's plant but it currently ignores most 2nd job skills and thorn trap ( will test later )
