### ISSUE TITLE
make tools fatal error

### ISSUE THREAD

**Issue by ecdarreola** [rathena/rathena#6811]
* **rAthena Hash**: 4592ae6

* **Client Date**: 20211103

* **Server Mode**: Both

* **Description of Issue**: Unable to make tools via CentOS7
  * Result: 
![image](https://user-images.githubusercontent.com/48939874/162581970-c64f4f41-f08d-4230-a7c1-d4869a4f3bd0.png)

  * Expected Result: Should be able to compile
  * How to Reproduce: ./configure -> make all -> make tools
  * Official Information: 
  

* **Modifications that may affect results**: None

**Comment by vstumpf** [comment]
I can confirm this, but in the mean time, you can `make common && make tools` and it should work.

**Comment by ecdarreola** [comment]
I still have the error. Unable to compile using CentOS7
