### ISSUE TITLE
In reference to Issue #6811 - make tools fatal error

### ISSUE THREAD

**Issue by ecdarreola** [rathena/rathena#6824]
* **rAthena Hash**:  f4410fb

* **Client Date**: 20211103

* **Server Mode**: Both

* **Description of Issue**: Unable to compile tools after the fix was brought up.
  * Result: Fatal error ryml_std.hpp not found
  * Expected Result: Compile tools successfully
  * How to Reproduce: ./configure -> make all -> make tools | ./configure -> make common -> make tools
  * Official Information: None
  

* **Modifications that may affect results**: None

**Comment by aleos89** [comment]
I'm unable to reproduce this on 6e5461a. I can `./configure` and then `make tools` just fine on Centos 7.
