### ISSUE TITLE
compile use VS 2015 debug/release it's same

### ISSUE THREAD

**Issue by slammer86** [rathena/rathena#6825]
compile use VS 2015 debug/release it's same. i got this code

E:\Project RO\rathena-master\3rdparty\rapidyaml\ext\c4core\src\c4/ext/fast_float_all.h(2584): warning C4800: 'uint64_t': forcing value to bool 'true' or 'false' (performance warning)

**Comment by Playtester** [comment]
You need Windows 10 SDK to compile the new yaml library. I installed VS 2022 together with it to get it to work (my VS2015 installation was older than Windows 10 so it didn't include it).

**Comment by slammer86** [comment]
i ready install SDK 10 for VS 2015 but still warning.

**Comment by slammer86** [comment]
> You need Windows 10 SDK to compile the new yaml library. I installed VS 2022 together with it to get it to work (my VS2015 installation was older than Windows 10 so it didn't include it).

maybe VS 2015 is too old like you say. thx for the advice moving to VS 2022
