### ISSUE TITLE
Laphine Upgrade Not Work

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#6827]
* **rAthena Hash**: 4592ae6

* **Client Date**: 20211103

* **Server Mode**: RE

* **Description of Issue**: 
  * Result:  Not Work
  * Expected Result:  Work
  * How to Reproduce:  Create item Imperial_Rifine_Ticket and Imperial_Knight_Armor then double click Imperial_Rifine_Ticket
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by Atemo** [comment]
Imperial_Knight_Armor is successfully refined to +9 using Imperial_Rifine_Ticket on https://github.com/rathena/rathena/commit/8bc43091c92b5afc2f16b34d2243d0f8af28672e

**Comment by mazvi** [comment]
are you using client 20211103?

**Comment by Atemo** [comment]
Indeed, but I don't see what the client has to do with the issue.?

**Comment by mazvi** [comment]
SOLVED must level 120 :D i dont know why
