### ISSUE TITLE
17.1 Enchanter Crashes Server

### ISSUE THREAD

**Issue by Megelith** [rathena/rathena#6838]
* **rAthena Hash**: 51ddc63

* **Client Date**: 20211117

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: When using the 17.1 enchanter I get this and then the server crashes
  
![Screenshot 2022-04-15 195117](https://user-images.githubusercontent.com/33073742/163655672-af9095f2-e243-4124-922b-18890ad501dc.png)

  * Expected Result: 
  * How to Reproduce: Just click through the enchanter dialogue
  * Official Information: 
  

* **Modifications that may affect results**: I have the 17.2 pull request merged into my server but I don't believe that changed the enchanter script in any way.

**Comment by mazvi** [comment]
please provide gdb

**Comment by Megelith** [comment]
I don't really know for sure what I'm doing so I'm sorry if this is too much or too little information. 
![error1](https://user-images.githubusercontent.com/33073742/163676668-2352d181-62c6-4355-a16e-4eeefaec17f2.png)
![error 2](https://user-images.githubusercontent.com/33073742/163676669-106d551b-db53-4b62-939e-da11d17f6a0b.png)
![error 3](https://user-images.githubusercontent.com/33073742/163676672-ee854d1c-b94f-4f18-a86e-1667a30449d9.png)
![error4](https://user-images.githubusercontent.com/33073742/163676678-f8611f4f-8dc2-4bf2-b181-969e586b8b6b.png)
![error5](https://user-images.githubusercontent.com/33073742/163676686-f6628a5f-80ba-4253-b7a7-2106093fca31.png)
![error6](https://user-images.githubusercontent.com/33073742/163676689-b112b8e4-888f-45ce-bcc0-24c103c57906.png)
![error7](https://user-images.githubusercontent.com/33073742/163676690-2719c1d2-2465-4c2e-ae8b-0b5589bee2c3.png)
![error8](https://user-images.githubusercontent.com/33073742/163676693-de6a3a04-8fea-46ee-ba14-165b518fea38.png)
