### ISSUE TITLE
bRes/bMres not working after this commit Fixes mobs res/mres always 0 (#6760)

### ISSUE THREAD

**Issue by Relliksuriv** [rathena/rathena#6841]
* **rAthena Hash**: 

* **Client Date**: 

* **Server Mode**: renewal

* **Description of Issue**: 
  * Result:  bRes bMres not applying bonus properly.
  * Expected Result: 
  * How to Reproduce:  Use bRes / bMres on any item and wear it.

I am not sure but i think this line just makes it always 0
`		if (bl->type != BL_MOB)	// BL_MOB has values set when loading mob_db
			status->res = status->mres = 0;`

  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by dimasshotta** [comment]
if (bl->type != BL_PC && bl->type != BL_MOB)
		status->res = status->mres = 0;

I gues it supposed to be this way..

**Comment by Playtester** [comment]
Yes, that fixes it, but going by indentation I assume the code was supposed to be:

```    if( bl->type != BL_PC ) {
        status->batk =
        status->hit = status->flee =
        status->def2 = status->mdef2 =
        status->cri = status->flee2 =
        status->patk = status->smatk =
        status->hplus = status->crate = 0;
        
        if (bl->type != BL_MOB)    // BL_MOB has values set when loading mob_db
            status->res = status->mres = 0;
    }```
