### ISSUE TITLE
BUG On quests_17_1.txt

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#6847]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/d7e114179d592bfa904e4389689e8383dceb5699

* **Client Date**: 20211103

* **Server Mode**: RE

* **Description of Issue**: getbaseexp_ratio not work and why many duplicate line getexp 0,400000;?

https://github.com/rathena/rathena/blob/d7e114179d592bfa904e4389689e8383dceb5699/npc/re/quests/quests_17_1.txt#L6897
https://github.com/rathena/rathena/blob/d7e114179d592bfa904e4389689e8383dceb5699/npc/re/quests/quests_17_1.txt#L6898
https://github.com/rathena/rathena/blob/d7e114179d592bfa904e4389689e8383dceb5699/npc/re/quests/quests_17_1.txt#L6899
https://github.com/rathena/rathena/blob/d7e114179d592bfa904e4389689e8383dceb5699/npc/re/quests/quests_17_1.txt#L6900

  * Result: 
  * Expected Result: 
  * How to Reproduce: 

Make Sample NPC

```
new_5-1,176,81,5	script	RatioTest	122,{
getbaseexp_ratio 10,110;
end;
}
```

  * Official Information: 
  

* **Modifications that may affect results**:  VIP Enabled VIP has 1.5x exp

**Comment by aleos89** [comment]
The multiple lines of getexp is official. It's Gravity's way of properly giving experience to players who may level up while receiving experience (on official servers you don't level up multiple times).

**Comment by mazvi** [comment]
thanks for information, so only this for now not work: getbaseexp_ratio 10,110;

**Comment by Lemongrass3110** [comment]
Any messages in your map server?

**Comment by mazvi** [comment]
![gambar](https://user-images.githubusercontent.com/8316103/163799484-8bc97f8b-7500-4995-a030-8b5776b7f583.png)

```
new_5-1,176,81,5	script	RatioTest	122,{
getbaseexp_ratio 10,110;
getexp 0,300000;
getexp 0,300000;
getexp 0,250000;
end;
}
```

No base increase, only job

No error on my map server

Modifications that may affect results: my server have VIP Enabled feature

**Comment by Daegaladh** [comment]
getbaseexp_ratio doesn't give exp per-se, just returns a value based on the parameters provided, so all getbaseexp_ratio instances in the script must be fixed

**Comment by mazvi** [comment]
> getbaseexp_ratio doesn't give exp per-se, just returns a value based on the parameters provided, so all getbaseexp_ratio instances in the script must be fixed

what do you mean? so the way i did the test is wrong?

**Comment by Daegaladh** [comment]
> > getbaseexp_ratio doesn't give exp per-se, just returns a value based on the parameters provided, so all getbaseexp_ratio instances in the script must be fixed
> 
> what do you mean? so the way i did the test is wrong?

It returns the amount of exp based on the parameters, but you still need a getexp command in order to make the character receive the exp
E.g. `getexp getbaseexp_ratio(10,110),0;`

**Comment by mazvi** [comment]
ah i see maybe also need update the doc https://github.com/rathena/rathena/blob/master/doc/script_commands.txt

**Comment by Daegaladh** [comment]
I think the description is accurate, it doesn't say it gives exp to the player, just that returns the exp value.
