### ISSUE TITLE
Roulette BUG Coins

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#685]
The Roulette should spend 1 bronze coin for each Start and should spend Silver Coins in the middle and gold coin on top. It is currently using only a bronze coin and only one currency. Today with a coin is coming on top of Roulette . What is a problem.
IDs: 675,673,671

Perhaps we can take advantage of what was done in Hercules , there works well.

**Comment by tmav94** [comment]
I Agree

**Comment by aleos89** [comment]
I don't have this issue. If I have a Bronze Coin Point I start at the bottom. If I have 10 Silver Coin Points I start in the middle, and if I have 10 Gold Coin Points I start near the top.

Just tested with a clean repo and it worked as it should. Keep in mind, the coins are usable. You must "consume" the coin to get the point.

**Comment by karlseven** [comment]
This problem still happens on client 2015-11-04aRagexe and using the latest repo as of 8/20/2017
using bronze coin you can go all the way up.

**Comment by anacondaqq** [comment]
@karlseven but the question is about next: Do roulette system must be presented in 20151104 exe? I though it died in 2014 exes.

**Comment by Questune09** [comment]
i want to open this again because its also give me a bug like this anyone know how to fix this?

also when you click start the lucky roulette give silver roulette coin even your not starting on spinning

**Comment by playpsro** [comment]
Silver Roulette will start if you have 10 coin.
Maybe you want to ask, where the file or where the place to edit requirement item to start the Lucky Roulette.

Because i want know too about that
