### ISSUE TITLE
Call Spirits not full amount of spirit spheres

### ISSUE THREAD

**Issue by Kimikimis** [rathena/rathena#6858]
* **rAthena Hash**: 
  * 3641dcf42

* **Client Date**: 
  * 2020-04-01b

* **Server Mode**:
  *  Pre-Renewal

* **Description of Issue**: 
  * Result: 
  Using Call Spirits as Monk or Champion, the maximum amount of spirit spheres I can call is always one less than the Call Spirits skill level, except when the skill level is 1. Dangerous Soul Collect works as expected. 

  * Expected Result: 
  The amount of spirit spheres I can call is equal to the Call Spirits skill level. 

  * How to Reproduce: 
  Clone git, uncomment "#define PRERE" in src/config/renewal.hpp, add "#define PACKETVER 20200401" to src/custom/defines_pre.hpp, configure and compile, set up SQL databases, set up conf/import/*.txt-files to get a working server, connect with hexed 2020-04-01b client. 

  * Official Information: 
  Can't find a kRO source that explicitly says how many spirit spheres should be available per level. I think it's commonly accepted as fact that the maximum amount should be equal to the skill level, as according to iRO Wiki: https://irowiki.org/wiki/Summon_Spirit_Sphere. 
  

* **Modifications that may affect results**: 
  * SQL databases in use where natively available as an alternative
  * Uncommented "#define PRERE" in src/config/renewal.hpp
  * Added "#define PACKETVER 20200401" to src/custom/defines_pre.hpp
  * FluxCP SQL tables installed in the same SQL database as the rAthena server uses
  * MD5 Passwords in use
  * Debian 10 (buster) in use, mariadb version 10.3.34

**Comment by Kimikimis** [comment]
I do get a "Skill has failed" message, forgot to include that, sorry.

**Comment by Playtester** [comment]
Can you put a breakpoint at the code I quoted above and debug it? I'd be curious why sd->spiritball >= skill_lv is true for you if you have less spirits than the level.

Only thing I could imagine is that for some reason the game thinks you have SC_RAISINGDRAGON with val1 being -1. Should be able to see that on debug.

**Comment by Kimikimis** [comment]
I understand C/C++ reading it, but I can't imagine what's going wrong either :D I've also never properly made anything in those languages, what exactly should I write and on which line?

**Comment by Playtester** [comment]
If you're using Visual Studio then just find the line 
```if(sd->spiritball >= skill_lv) {```
And on the left you can click on the bar to set a breakpoint (red dot). Make sure you set map-server as start project (right click on it) and mode to "Debug". Start login and char server via the EXE, then select "Run" in Visual Studio. It should start the map server in debug mode now. Then you test it and whenever you cast the skill it should stop there. You can "Hover" over skill_lv to see what it's current value is.

**Comment by Kimikimis** [comment]
Hmm, I'm not using Visual Studio, the server is in a Linux environment. I could set up Visual Studio in a Windows environment and install rAthena in it but it'd take a while because I don't really have time to sit down and focus on that for the next few days. If you can tell me how to do it in Linux it'd be done much sooner.

**Comment by Playtester** [comment]
I don't use Linux and don't know if there is any good debugger for this OS. I recommend always running a copy of your server data locally so you can debug these issues.

I also just tested again on the most-up-to-date master pre-renewal and it works perfectly fine. With Level 5 Summon Spirit Sphere I can summon up to 5 Spheres. It's working as expected.

**Comment by Kimikimis** [comment]
Well, I did this: 

map/skill.cpp
```
        case MO_CALLSPIRITS:
                if(sd) {
                        char output[254]; <====
                        int limit = skill_lv;
                        sprintf(output, "spirit sphere limit: %d\n", limit); <====
                        clif_displaymessage(sd->fd, output); <====
                        if( sd->sc.data[SC_RAISINGDRAGON] )
                                limit += sd->sc.data[SC_RAISINGDRAGON]->val1;
                        sprintf(output, "spirit sphere limit now: %d", limit); <====
                        clif_displaymessage(sd->fd, output); <====
                        clif_skill_nodamage(src,bl,skill_id,skill_lv,1);
                        pc_addspiritball(sd,skill_get_time(skill_id,skill_lv),limit);
                }
                break;
```

map/pc.cpp
```
void pc_addspiritball(struct map_session_data *sd,int interval,int max)
{
        int tid;
        uint8 i;
        char output[254]; <====

        nullpo_retv(sd);

        if(max > MAX_SPIRITBALL)
                max = MAX_SPIRITBALL;
        if(sd->spiritball < 0)
                sd->spiritball = 0;

        sprintf(output, "Spirit balls: %d out of %d\n", sd->spiritball, max); <====
        clif_displaymessage(sd->fd, output); <====

        if( sd->spiritball && sd->spiritball >= max )
        {
                if(sd->spirit_timer[0] != INVALID_TIMER)
                        delete_timer(sd->spirit_timer[0],pc_spiritball_timer);
                sd->spiritball--;
                if( sd->spiritball != 0 )
                        memmove(sd->spirit_timer+0, sd->spirit_timer+1, (sd->spiritball)*sizeof(int));
                sd->spirit_timer[sd->spiritball] = INVALID_TIMER;
        }

        tid = add_timer(gettick()+interval, pc_spiritball_timer, sd->bl.id, 0);
        ARR_FIND(0, sd->spiritball, i, sd->spirit_timer[i] == INVALID_TIMER || DIFF_TICK(get_timer(tid)->tick, get_timer(sd->spirit_timer[i])->tick) < 0);
        if( i != sd->spiritball )
                memmove(sd->spirit_timer+i+1, sd->spirit_timer+i, (sd->spiritball-i)*sizeof(int));
        sd->spirit_timer[i] = tid;
        sd->spiritball++;
        if( (sd->class_&MAPID_THIRDMASK) == MAPID_ROYAL_GUARD )
                clif_millenniumshield(&sd->bl,sd->spiritball);
        else
                clif_spiritball(&sd->bl);
        sprintf(output, "Spirit balls now: %d out of %d\n", sd->spiritball, max); <====
        clif_displaymessage(sd->fd, output); <====
}
```

And when I use the skill I get messages like these: 

> spirit sphere limit: 4
> spirit sphere limit now: 4
> Spirit balls: 0 out of 4
> Spirit balls now: 1 out of 4

![image](https://user-images.githubusercontent.com/17796740/164568137-a13ee6a5-1cd5-4553-ad05-b6edb1944eca.png)

I checked the 'skill' table of the SQL database, and the character I tested with had skill ID 261 (Call Spirits) level 5. 

In your test, were you using SQL? Before this I (and another person) discovered a bug with rAthena's SQL implementation that made everyone unable to use or equip any kind of item.

**Comment by Playtester** [comment]
Going by your log results you are using skill on level 4 in the first place, hence you only get 4 spirit spheres. I assume the client modification results in always sending one skill level lower than it should.

**Comment by Kimikimis** [comment]
Yep, it was that patch. Sorry for the trouble.
