### ISSUE TITLE
2014-10-22b Kagerou @dye collors

### ISSUE THREAD

**Issue by tmav94** [rathena/rathena#686]
Hi, guys!
Yesterday using my 2013-08-07 client with 553 Old Dye Pack, i see my cothles color...After update do 2014-10-22b the dye of Kagerou/Oborou stuck at 3...if you try to pass it, u collor will become dark/black.

Any ideia?

**Comment by aleos89** [comment]
Sorry, but this is client related, not server related. You'll need to open a topic in the client support section of the forum.

And I believe I've seen somewhere that Kagerou have their own palette files, so you might be missing those.
