### ISSUE TITLE
Earth Strain not Stripping Any Equipments

### ISSUE THREAD

**Issue by ryomahostingph** [rathena/rathena#6862]
* **rAthena Hash**: 

* **Client Date**: 2020-09-02bRagexeRE.exe

* **Server Mode**: Renewal

* **Description of Issue**: Earth Strain Strip Effect not Working
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**: 
  
  
![image](https://user-images.githubusercontent.com/77398623/164069047-5446c4d3-da6b-4df5-b8f1-01d9561d7ae6.png)

**Comment by aleos89** [comment]
Working as intended per the [Warlock Update](https://ro.gnjoy.com/news/update/View.asp?seq=239&curpage=1).
