### ISSUE TITLE
Homunculus EXP Bug

### ISSUE THREAD

**Issue by tmav94** [rathena/rathena#687]
the exp is not splited from master to homunculus. It's means that if you get level 175 you will not get more than 1 EXP for your homunculus, because you reached the max level of the caracters.

The exp that homunculus receive is based on player EXP. i believe thats is not a oficial behavior

**Comment by aleos89** [comment]
Which is the correct way it behaves on kRO? Does the master still get EXP from the homunculus once they are max level?

**Comment by panko11** [comment]
From what I know when the player reaches maximum level, but still he gets EXP however does not evolve.

**Comment by aleos89** [comment]
Confirmed. Homunculus still gain EXP even if the master is max level.
