### ISSUE TITLE
WoE can't hit player in Castle [ last rAthena ]

### ISSUE THREAD

**Issue by Gyakushinn** [rathena/rathena#6872]
* **rAthena Hash**: 3c36814c1fd0aa555c5031b0a60714e714a775a8

* **Client Date**: 2021-01-07aRagexeRE

* **Server Mode**: Pre-Renewal & Renewal

* **Description of Issue**: 
  * Result: **when entering the guild war Players cannot attack each other. but can attack the Emperium normally, TEST ON COLOCATION LINUX CENTOS & PC OFFLINE WINDOWS**
  * 
![278781749_1009920399920358_171540477432350496_n](https://user-images.githubusercontent.com/40000876/164865945-cccf3f82-64fc-466e-aee2-2f3804e8d46b.png)

  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by admkakaroto** [comment]
Do you have been started the war of emperium? or only entered on castle map?

![reporte_burro_funcionando](https://user-images.githubusercontent.com/6227618/164947559-6e299a69-440b-4a9e-8d08-6ca67140ec94.png)


its all working!

**Comment by Juliando2020** [comment]
disable diff from hexed fiz attack homunculos

**Comment by Gyakushinn** [comment]
> Do you have been started the war of emperium? or only entered on castle map?
> 
> ![reporte_burro_funcionando](https://user-images.githubusercontent.com/6227618/164947559-6e299a69-440b-4a9e-8d08-6ca67140ec94.png)
> 
> its all working!

yes i'm start WoE before enter in castle

**Comment by Gyakushinn** [comment]
> disable diff from hexed fiz attack homunculos

I will try to do as you suggested. Thank you for recommending

**Comment by Gyakushinn** [comment]
> disable diff from hexed fiz attack homunculos

I have tried doing what you suggested. The results were as you suggested.
problem caused by Fix Homunculus attack AI

**Comment by Gyakushinn** [comment]
resolved problem caused by diff client Fix Homunculus attack AI
