### ISSUE TITLE
Item Sling

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#688]
Hello good evening, the effect of skill Item Sling when using Banana Bomb, is incorrect, causing the player to sit for 20s when it should be only for 3s, made some changes and solve as follows, but do not know if is fully correct:

case ITEMID_BANANA_BOMB:
sc_start(src,bl, SC_BANANA_BOMB_SITDOWN, status_get_lv(src) + sd->status.job_level + sstatus->dex / 6 - status_get_lv(bl) - tstatus->agi / 4 - tstatus->luk / 5, skill_lv, 3000 - sd->status.job_level / 4);
sc_start(src,bl, SC_BANANA_BOMB, 100, skill_lv, 60000);
break;

time reference: http://irowiki.org/wiki/Item_Sling

**Comment by RagnarokNova** [comment]
Commented on this here:
https://github.com/rathena/rathena/commit/3fbac9c8e40256ea213ac689a59d8d72e6105603#commitcomment-13727659

**Comment by aleos89** [comment]
> In official their's a duration but the formula for it is found to be OP. Formula is 1000ms * Thrower's Job LV / 4.
The formula we are using is from Rytech's data. It is official from what he states.

**Comment by Paoly28** [comment]
i think that duration is for the STR/LUK reduction. sit duration is fixed.

**Comment by Paoly28** [comment]
and it's not 20 seconds it's around 3 or 4.

that's why banana bomb isn't actually used as much as it's supposed to chance is low and sit duration isn't long.

**Comment by aleos89** [comment]
Confirmed Rytech's formula. Timed for 13~ seconds with target's job level being 50.

**Comment by Everade** [comment]
@aleos89 
I would bet on RagnarokNova
I wonder how you guys confirmed this... ?!

>17 seconds sitting.
That's far beyond retarded, i will never believe that's official.
Not even the asians can be this stupid to break the game like this.

On my server, players are currently sitting >30 seconds due joblvl 120
But >17seconds even on official servers.

That's not hilarious, it's seriously retarded.

**Comment by secretdataz** [comment]
It is not and never was our job to create a balanced game. If you feels something is unbalanced you can always edit it to w/e you think is balanced.

> 17 seconds sitting.
That's far beyond retarded, i will never believe that's official.
Not even the asians can be this stupid to break the game like this.

No racist comment please.

**Comment by aleos89** [comment]
If the formula wasn't updated by kRO, then what can we do? It would be up to kRO to balance the formula, not us.

**Comment by Paoly28** [comment]
balancing will be up to the respective developers/owners, after all you have access to your own server files :v:

**Comment by Everade** [comment]
I repeat
**I will never believe that's official, no one can be this retarded.**

And no one ever confirmed if it has been tested on kRO live server.
aleos confirmed it, but based on what information? an old aegis version?
No offense, i just want to help.

And yes i do balances myself (and i've balanced this already myself).
That doesn't mean that i'm not here trying to help the community getting rid of bullshit.

@secretdataz 
And i'm expecting something from asians because they're known to be genious when it comes to math.
I'm over this racist crap since over a decade, it's just you thinking that way.
meh...

**Comment by secretdataz** [comment]
@Everade There is no need in swearing. This issue will be locked, and this is your first warning.
