### ISSUE TITLE
recompile error pls help client 20211103

### ISSUE THREAD

**Issue by shieldro** [rathena/rathena#6881]
make[1]: Leaving directory '/root/server/src/char'
make[1]: Entering directory '/root/server/src/map'
        MKDIR   obj
        CXX     achievement.cpp
        CXX     atcommand.cpp
        CXX     battle.cpp
        CXX     battleground.cpp
        CXX     buyingstore.cpp
        CXX     cashshop.cpp
        CXX     channel.cpp
        CXX     chat.cpp
        CXX     chrif.cpp
        CXX     clan.cpp
        CXX     clif.cpp
        CXX     date.cpp
        CXX     duel.cpp
        CXX     elemental.cpp
        CXX     guild.cpp
        CXX     homunculus.cpp
        CXX     instance.cpp
        CXX     intif.cpp
        CXX     itemdb.cpp
itemdb.cpp: In member function ‘virtual uint64 RandomOptionGroupDatabase::parseBodyNode(const c4::yml::NodeRef&)’:
itemdb.cpp:3368:33: error: use of ‘randomNode’ before deduction of ‘auto’
   for (const auto& randomNode : randomNode) {
                                 ^
Makefile:83: recipe for target 'obj/itemdb.o' failed
make[1]: *** [obj/itemdb.o] Error 1
make[1]: Leaving directory '/root/server/src/map'
Makefile:50: recipe for target 'map' failed
make: *** [map] Error 2

**Comment by aleos89** [comment]
Please use the forums for support on issues like this.
