### ISSUE TITLE
Cash Shop bug i don't know why.

### ISSUE THREAD

**Issue by gravity-ro** [rathena/rathena#6882]
How to get your GitHub Hash:
1. I update sever to ep17.2
2. Before update it's works.

* **Client Date**: 

23-04-22

* **Server Mode**: 

Renewal

Thank you advance.

![Screenshot_1](https://user-images.githubusercontent.com/80197766/164981801-ceabca21-2dee-40cc-b142-f0243b73409d.png)

**Comment by Pokye** [comment]
Enable Cash Shop Preview
https://github.com/rathena/rathena/blob/master/src/config/core.hpp#L85

**Comment by gravity-ro** [comment]
> Enable Cash Shop Preview https://github.com/rathena/rathena/blob/master/src/config/core.hpp#L85

[Solved]
Thank you Pokye.
