### ISSUE TITLE
Market Shop Can't buy items.

### ISSUE THREAD

**Issue by gravity-ro** [rathena/rathena#6883]
How to get your GitHub Hash:

1. I update sever to ep17.2
2. Before update it's works.
3. If exchange works.

Client Date:
23-04-22

Server Mode:
Renewal

Thank you advance.

![Screenshot_2](https://user-images.githubusercontent.com/80197766/164982094-17631f7d-a8bb-4a5f-9986-840c50c28725.png)
.

**Comment by gravity-ro** [comment]
It say Out of stock!

**Comment by lttipholLive** [comment]
> It say Out of stock!

Hi pcm No.1 Server Fuck U

**Comment by gravity-ro** [comment]
I use last update server from mr.Lemongrass3110 
original compile no modify
before update i use it fine

what your problem fuck you bad guy!

**Comment by lttipholLive** [comment]
> I use last update server from mr.Lemongrass3110 original compile no modify before update i use it fine
> 
> what your problem fuck you bad guy!

บ่นควยอะไรอึลูกแถ เชิฟหัวควยแบบนี่หลอกแดกเด็กใหม่ สร้างเฟสปลอมเยอะ บอกเชิฟมิงเจ่งดี เจ่งควยเหอไอสัด

**Comment by lttipholLive** [comment]
![1650814152895](https://user-images.githubusercontent.com/104314045/164984152-838d7a15-5441-4b53-b51b-1f378de13e2b.jpg)
 เชิฟหัวควยNo.1ทีชอบช่อนไฟล์ หลอกแดกเงินเด็กใหม่ บอกเชิฟตัวเองเจ่งดี บัคก็เยอะ แกัครั้งละ300บาท เด็กใหม่ก็เสียเงินไห้มิงเยอะละ

**Comment by lttipholLive** [comment]
@gravity-ro สำหรับเงินทีมิงไปหลอกแดกเด็กใหม่ๆโดยทีเค้าไม่รู้เรืองเชิฟเกม เอาไว้ยัดใส่ปากลูกกับเมียมิงนะ จะได้จำไว้ 
![Uploading 1650814152895.jpg…]()

**Comment by gravity-ro** [comment]
I don't know this bad guy. Why would this place allow such bad people to degrade this kind of knowledge place? Bad people like this please shut him down.

And he also brought other people's information to damage again. absolutely shouldn't

**Comment by gravity-ro** [comment]
[Solved]

Thank you [aleos89

![Screenshot_7](https://user-images.githubusercontent.com/80197766/165168444-88c8b68a-0116-4183-a3c9-69bcec9b0a83.png)
]
