### ISSUE TITLE
I not sure this is bug or not laphine synthesis Craft item it's not present.

### ISSUE THREAD

**Issue by gravity-ro** [rathena/rathena#6893]
1. Server supports up to '4096'
2. Patch EP17.2
3. 20211103
-->

* **Client Date**: 

25-04-22

* **Server Mode**: 
 Renewal

* **Description of Issue**: 
I not sure this is bug or not laphine synthesis Craft item it's not present.
Ex. Use item ID 23818

* **Screenshot**: 

![Screenshot_8](https://user-images.githubusercontent.com/80197766/165259337-22d006ed-e07f-4616-a7d9-138fe411fb91.png)

**Comment by idk-whoami** [comment]
ef6a682ca8464713dd988d99d2305a0412536eaa  It's no problem.

![บันทึก_2022_04_27_14_31_08_126](https://user-images.githubusercontent.com/60462533/165470496-ea570e6e-288f-4b21-9094-e13f49eedab6.gif)

**Comment by gravity-ro** [comment]
> [ef6a682](https://github.com/rathena/rathena/commit/ef6a682ca8464713dd988d99d2305a0412536eaa) It's no problem.
> 
> ![บันทึก_2022_04_27_14_31_08_126](https://user-images.githubusercontent.com/60462533/165470496-ea570e6e-288f-4b21-9094-e13f49eedab6.gif)

Please ask for more information
In my server, it's a new one, fixed as suggested already.
But still can't see the item to create.

I don't know if there are any other files related to the use of this section.
thanks in advance

translate by google

**Comment by Atemo** [comment]
The feature works fine on a fresh copy. As such, your issue is invalid. Please use the forum or discord to get help solving your issue.
