### ISSUE TITLE
Suggestion: Defaulting drop effect to DROPEFFECT_CLIENT.

### ISSUE THREAD

**Issue by eppc0330** [rathena/rathena#6894]
**Is your request related to a missing feature?** No.

**Describe the solution you'd like**

Because recent client, supporting dropeffect, already defines all items' dropeffect, I think it is inefficient to work DB again for dropeffect. 
So isn't it better to default dropeffect to DROPEFFECT_CLIENT, instead of DROPEFFECT_NONE?
Then we will just need to touch dropeffect only when we find something special item needed special dropeffect.

**Describe alternatives you've considered**

**Additional context**

**Comment by Balferian** [comment]
If set droplight effect = 'CLIENT' for all items by default then users can highlight any items by modify iteminfo.
Players can control the highlight by themselves and gain an advantage for example in events.
I think it's better to make this feature optional or make a parser for itemdb that set dropeffect_client based on received data from iteminfo ("EffectID").
