### ISSUE TITLE
HPFactor default is too high

### ISSUE THREAD

**Issue by jofvgaming** [rathena/rathena#6908]
* **rAthena Hash**: Latest

* **Client Date**: 
20180621

* **Server Mode**: Both

* **Description of Issue**: 
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
  

Increasing/editing for a certain job HPFactor, HPMultiplicator from https://github.com/rathena/rathena/blob/master/db/pre-re/job_stats.yml, takes no effect.

* **Modifications that may affect results**: 
  
  

using Pre-re, Max Level 255 and Job Level 120

**Comment by Playtester** [comment]
By default it uses the HP/SP tables here:
https://github.com/rathena/rathena/blob/master/db/pre-re/job_basepoints.yml

If you want to define HP/SP via multiplicator setting from job_stats.yml then you need to comment this define in core.hpp:
`/// Comment to disable the job base HP/SP/AP table (job_basepoints.yml)
#define HP_SP_TABLES`

**Comment by jofvgaming** [comment]
i try comment this line, then it happens all jobs get MaxHP 1100000 ithink

**Comment by Pokye** [comment]
Maybe you can set the max hp value you want here.
https://github.com/rathena/rathena/blob/master/conf/battle/player.conf#L89

**Comment by Playtester** [comment]
The actual bug here is that it defaults HPFactor to 20000. It's a bit confusing in general because the words "HPFactor" and "HPMultiplicator" are kind of exchanged. Might make sense to to exchange those words once and for all.

**Comment by Playtester** [comment]
Either wait for my linked PR (see above) or if you want to apply a temporary fix, just go to pc.cpp and change:

```job->hp_factor = 20000;```

To:

```job->hp_factor = 0;```

I need to wait before finishing the PR as I also renamed some fields. That means I might need to increase the YAML version and update the converter, so it still can take a bit.
