### ISSUE TITLE
Item 14538 [Bug]

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#691]
Item: 14538, are giving totally huge status, leaving the player full aspd, and almost instant cast ... following images.

Before using the item:
http://i.imgur.com/nWweNur.png

After using the item:
http://i.imgur.com/Yt8sL3b.png

**Comment by aleos89** [comment]
There's a small typo in status_calc_flee2():
```if(sc->data[SC_INCFLEE2])
		flee2 += sc->data[SC_INCFLEE2]->val1;```
Should be:
```if(sc->data[SC_INCFLEE2])
		flee2 += sc->data[SC_INCFLEE2]->val2;```

**Comment by admkakaroto** [comment]
Tested, not worked.

**Comment by admkakaroto** [comment]
the problem seems coming from the ID, I copied the script item but with another ID and it worked perfectly.

**Comment by nanakiwurtz** [comment]
Are you sure you don't have the same Item ID on your import folder?

**Comment by admkakaroto** [comment]
nop

**Comment by cydh** [comment]
> Item: 14538, are giving totally huge status, leaving the player full aspd, and almost instant cast ... 

It only gives +20 Perfect Dodge. Nothing to do with ASPD & Instacast
