### ISSUE TITLE
Steel Body should be removed on logout

### ISSUE THREAD

**Issue by Playtester** [rathena/rathena#6910]
* **rAthena Hash**: 5ec5f48

* **Client Date**: 2022-11-03

* **Server Mode**: Pre-Renewal (maybe also Renewal but not confirmed)

* **Description of Issue**: Steel Body should be removed when logging out.
  * Result: Steel Body is not removed on logout.
  * Expected Result: Steel Body is removed on logout.
  * How to Reproduce: Cast Steel Body (Mental Strength) and then logout and login again.
  * Official Information: Verified by test on official server (pre-renewal 13.2).

**Comment by aleos89** [comment]
Confirmed on renewal, it is lost on log out.

**Comment by Playtester** [comment]
It should only be "NoSave" as changing the map does not remove it.
