### ISSUE TITLE
Map-wide damage reduction is missing

### ISSUE THREAD

**Issue by Takiusu** [rathena/rathena#6922]
* **rAthena Hash**: latest

* **Client Date**: 2021-11-17

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: 
  * Expected Result: Map-wide damage reduction (approximately 90%). This is not  Relieve On nor Green Aura from MVP Bosses.
  * Official Information: https://www.youtube.com/watch?v=EmsdhRjwDoA
  

* **Modifications that may affect results**:

**Comment by Balferian** [comment]
@Takiusu Why do you think that it is damage reduction mapflag and not "DamageTaken" mobs setting?

**Comment by Takiusu** [comment]
> @Takiusu Why do you think that it is damage reduction mapflag and not "DamageTaken" mobs setting? It's not logical.

Thank you!
