### ISSUE TITLE
RODEX system map server crash

### ISSUE THREAD

**Issue by voyfmyuh** [rathena/rathena#6924]
rAthena Hash: https://github.com/rathena/rathena/commit/6d0eef0a20811b6c60252689e5544f201039b349
Client Date: 2021-11-17
Server Mode: Renewal
Description of Issue: RODEX system map server crash

![1651823130331](https://user-images.githubusercontent.com/54499336/167089543-d65062ef-85d0-4e36-ac9b-8de456f3a743.jpg)

**Comment by aleos89** [comment]
Can you give steps on how to reproduce the crash? It looks like you have an invalid mail item.

**Comment by vstumpf** [comment]
It's valid, we assume items are in all Mail Slots, when it should only be the ones that have an amount.
