### ISSUE TITLE
Pre-Renewal ASPD Bug

### ISSUE THREAD

**Issue by bgamez23** [rathena/rathena#6925]
* **rAthena Hash**: 94c80a910864a84dc516536762b892b90ea0f3a4

* **Client Date**: 20211117

* **Server Mode**: Renewal

* **Description of Issue**: Renewal mode with disabled RENEWAL_ASPD bug
  * Result: Max aspd
  * Expected Result: Max aspd to all class even without adding stats.
  * How to Reproduce: Renewal mode with disabled RENEWAL_ASPD
  * Official Information: You won't reach max aspd without stats and cards
  

* **Modifications that may affect results**: //#define RENEWAL_ASPD

**Comment by aleos89** [comment]
Duplicate of #6900.
