### ISSUE TITLE
Roulette Behaviour

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#6931]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/9acb50006a7f00d55a7373143fde52933df2ffdf

* **Client Date**: 20211103

* **Server Mode**: RE

* **Description of Issue**: 
  * Result:  Player can move, can click another npc, when Roulette window opened
  * Expected Result: player cannot move, cannot click another NPC, maybe cannot using item, like Cashshop opened, or Refine UI Opened
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by mazvi** [comment]
Unfortunately I don't have that information, only saw Behavior on the cash shop, refine ui. which may be relevant.

**Comment by aleos89** [comment]
Ziu was able to confirm that it behaves like the other UI, where interaction is lost outside the UI.
