### ISSUE TITLE
Reset/Remove All Quest on Character

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#6932]
**Is your request related to a missing feature?** No

**Describe the solution you'd like** Script command and atcommand for reset all quest (remove all quest) in a safe way on single character

**Describe alternatives you've considered**

**Additional context** This is needed when a character quest is stuck, without having to create a new character.

**Comment by Atemo** [comment]
There is enough tool to do that (sql, erasequest script and atcommand). Maybe create your own command via the script command "bindatcmd"?

**Comment by Lemongrass3110** [comment]
Or just use SQL...
For me this is considered basic knowledge you should have when you run a server.
```
delete from `quest` where `char_id` = ?;
```
This is all you need and the same applies to quest variables that you have to erase, in case you need it...
