### ISSUE TITLE
@autotrade monsterignore persistency

### ISSUE THREAD

**Issue by gidzdlcrz** [rathena/rathena#6935]
* **rAthena Hash**: Latest

* **Client Date**:  2013 2015 2018 & 2020

* **Server Mode**: Both

* **Description of Issue**: Autotrader persistency (sd->state.block_action |= PCBLOCK_IMMUNE;)
  * Result: the monsterignore will be removed from the autotraders when the server restarts
  * Expected Result: autotraders should retain their @monsterignore status when they auto log in when the server restarts
  * How to Reproduce:  If you use atautotrade. The autotrader will have @monsterignore status. But when you restart the server and the autotrader persistency kicks in. The @monsterignore state to the vendor will be removed.
  * Official Information: Nope. This is more on a feature request.
  

* **Modifications that may affect results**: Nothing.

**Comment by Lemongrass3110** [comment]
conf/battle/misc.conf:
```
// Makes player cannot be attacked when autotrade? (turns player's state.monster_ignore) (Note 1)
at_monsterignore: no
```

**Comment by gidzdlcrz** [comment]
Sorry i didn't find this in misc.conf

`// Makes player cannot be attacked when autotrade? (turns player's state.monster_ignore) (Note 1)
at_monsterignore: no`
