### ISSUE TITLE
Script command "callshop" with "close" error

### ISSUE THREAD

**Issue by eppc0330** [rathena/rathena#6937]
**Is your request related to a missing feature?** No

**Describe the solution you'd like**

 I know we use ```close2;```  when we make shop NPC, but I found NPC calling shop without closing dialog window.
Check this NPC, from official KRo :
![Shop](https://user-images.githubusercontent.com/47050704/167897986-3e8517ff-8f8c-4c9e-b1b1-777948166a43.gif)

I've tried to copy this NPC and script like this:
```
Callshop "";
close;
end;
```

No problem with calling shop, but server shows error when I click cancel or buy button of the shop before click close button of dialog window:
```[Debug]: npc_scriptcont: 신비한 과자집 (sd->npc_id=110143955) is not 'Unknown NPC' (id=0).```
and character stuck until relogin.

I think I can't solve this without source code changed. If it's not, sorry I'll close this issue.

**Describe alternatives you've considered**

**Additional context**

**Comment by kaninhot004** [comment]
I had solved by call close2 before callshop.
```
close2;
callshop " ";
end;
```

**Comment by eppc0330** [comment]
> I had solved by call close2 before callshop.
> 
> ```
> close2;
> callshop " ";
> end;
> ```

Thank you! But this will call shop after close dialog window.
If you check my screenshot you will find that dialog window still exists after shop opened. I also asked other and they answered that new script command would be needed.

**Comment by eppc0330** [comment]
@kaninhot004 Solved by other's script.
``` 
    mes "";
    addtimer 1, strnpcinfo(3) + "::OnShop";
    end;
OnShop:
    callshop    "";
    end;
```

Works right order what I intended. Thank you.

I close this issue.
