### ISSUE TITLE
Looter AI breaks if wall on its walkpath

### ISSUE THREAD

**Issue by Playtester** [rathena/rathena#6939]
* **rAthena Hash**: b0b5bfd

* **Client Date**: 2021-11-03

* **Server Mode**: Both

* **Description of Issue**: 

![grafik](https://user-images.githubusercontent.com/3785983/168145127-ac39e0ca-6d2b-43cf-af68-aaaf48b28e7c.png)

If an item is in line of sight to a looter monsters, but a wall is on its normal walkpath to it, then the Looter AI breaks. The monster will go into an endless loop, it won't randomly walk or use skills anymore.

Need to test what happens on official servers in this situation, but a potential fix is to not use the easy walkpath for looting.

**Comment by Playtester** [comment]
Tested on kRO: Looters just use line of sight to find items to chase. Once they found an item, they use complex pathing.

**Comment by gidzdlcrz** [comment]
Is this related to what i reported? https://github.com/rathena/rathena/issues/6941

**Comment by Playtester** [comment]
No didn't see such a behavior before. In this case, the monster will simple stand still and never do anything anymore.

**Comment by hnomkeng** [comment]
https://youtu.be/FR_JI1OtczU

can't loot

**Comment by Daegaladh** [comment]
> Client Date: 2021-11-17
> 
> https://youtu.be/FR_JI1OtczU can't loot

This has nothing to do with this issue, this is about looter monsters, not players
