### ISSUE TITLE
Weird monster movement / asura strike pass through the walls.

### ISSUE THREAD

**Issue by gidzdlcrz** [rathena/rathena#6941]
* **rAthena Hash**:  323db7e

* **Client Date**: 2018

* **Server Mode**: PRE RE

* **Description of Issue**: I have this weird monster walk glitch when there are walls. They somehow walk fast or they bypassing the wall
  * Result:  Here's a video presentation of the bug https://www.youtube.com/watch?v=ty7Jc63kUME
  * Expected Result:  They should not behave like that. I have much older trunk. No problem at all.
  * How to Reproduce:  Go to lots of walls or houses then summon any mobs
  * Official Information: 
  
  
  P.S. Also. When there is monster on a wall. Let's say its a house. I tried to asura strike it i will pass through a wall. Then the character will be stuck there forever.

* **Modifications that may affect results**:  N/A

**Comment by Playtester** [comment]
If they walk fast it's usually due to position lag (real location of monster is somewhere else).

Looking at the video that looks really strange. Would be nice to know if you applied any changes such as disabling OFFICIAL_WALKPATH.

Maybe someone else knows if they fixed something in the meantime (since your rAthena is still based on 2020).

**Comment by gidzdlcrz** [comment]
> If they walk fast it's usually due to position lag (real location of monster is somewhere else).
> 
> Looking at the video that looks really strange. Would be nice to know if you applied any changes such as disabling OFFICIAL_WALKPATH.
> 
> Maybe someone else knows if they fixed something in the meantime (since your rAthena is still based on 2020).

I have much older trunk than that. I believe its may 2020 with selected PR up to november 2020. I tried to back read the commits to do some reverts but no to avail.

and no i didn't messed witch OFFICIAL_WALKPATH. This is fresh trunk before item yaml implementation.

**Comment by gidzdlcrz** [comment]
This is my other trunk that dont have problem. (manually selected commits up until november 20200 https://github.com/rathena/rathena/tree/ca56c060cf3d4c11b0f6da9c5d5b2d8e8e5c3d7e

This one doesnt have that problem. Can you give me which files to compare when it comes to the bug im experiencing right now @Playtester? Thanks!

**Comment by Playtester** [comment]
@gidzdlcrz I'm always using a fresh rAthena checkout with no changes, you can just do a fresh checkout and just set up your IPs and then check if you still encounter the problem.

**Comment by gidzdlcrz** [comment]
I have recorded another video. Hope to find some light regarding my concern. https://youtu.be/ZZed_VdX0T4

**Comment by Playtester** [comment]
Ah seems the display issue comes from the monster being inside a wall.

This is not a problem with the emulator, but instead your mapcache does not fit to the map on the client. If you use a custom map for prontera you also need to add the .gat file to the mapcache.

**Comment by gidzdlcrz** [comment]
YES APPARENTLY thats causing the bug. Because this was prontera 2. I am trying to different map. Im so dumb!

**Comment by gidzdlcrz** [comment]
Yes confirmed. Im so stupid to forgot the most basic stuff. Please disregard. Thanks @Playtester! By the time you mention about the GAT's i was already testing it. Hehehe!
