### ISSUE TITLE
Skill doesn't remove

### ISSUE THREAD

**Issue by imaqtdan** [rathena/rathena#6974]
![image](https://user-images.githubusercontent.com/69942447/169712423-c6817ae7-e0f1-4929-a6c1-83c2c713170a.png)
20211103 Client
even after patching the hotfix on this bug still the skill doesn't remove.
https://github.com/rathena/rathena/compare/master...hotfix/issue5382_v2

**Comment by Pokye** [comment]
Duplicate: https://github.com/rathena/rathena/issues/5382

Fix: https://github.com/rathena/rathena/pull/6529
