### ISSUE TITLE
issue C_ARG not found.

### ISSUE THREAD

**Issue by hnomkeng** [rathena/rathena#6976]
* **rAthena Hash**: 26ec100
* **Client Date**: 2021-11-17
* **Server Mode**: Pre-renewal
* **Description of Issue**: C_ARG not found with item id 1466

![image](https://user-images.githubusercontent.com/9112684/169777531-e576c5db-c4c0-4405-a963-15af94481d44.png)

**Comment by aleos89** [comment]
I see nothing wrong with the bonus, visually. Are you sure you haven't made a customization to the item?

**Comment by aleos89** [comment]
I'm unable to reproduce this on [9bf78ee](https://github.com/rathena/rathena/commit/9bf78ee5a35a2f7833aaffb883fc83af671f3c2f).
