### ISSUE TITLE
Class4 Expanded Skill?

### ISSUE THREAD

**Issue by gravity-ro** [rathena/rathena#6977]
Client Date: 20211117
Server Mode: RE
Description of Issue:
๐ Class4 Expanded (All works)
๐ But Can't Use Skill All Class4 Expanded Can't Double Click On Skill
============================================

I'm not sure these class Can use the skill or not?
Just ask question i don't know this bug or not update.

![Screenshot_1](https://user-images.githubusercontent.com/80197766/169828159-3044804e-687d-49ed-8303-efe81ff0d5b9.png)

**Comment by Atemo** [comment]
Some skills are not implemented. Please use forum/discord/google first for simple questions

**Comment by gravity-ro** [comment]
Thank you Atemo.
I want to make sure because someone tell me Class4 Expanded Skill is ready to use.
