### ISSUE TITLE
Are these really `else if` ?

### ISSUE THREAD

**Issue by cydh** [rathena/rathena#698]
in `status.c::status_change_start`
https://github.com/rathena/rathena/blob/b758f39/src/map/status.c#L7729-L7790
````
	if( sc->data[SC_REFRESH] ) {
		//...
	}
	else if( sc->data[SC_INSPIRATION] ) {
		//...
	}
	else if( sc->data[SC_KINGS_GRACE] ) {
		//...
	}
````
That `else if`, why they are not `if`? :P

**Comment by Playtester** [comment]
It should also be called "ailment" and not "ailement".
