### ISSUE TITLE
Wear item id 1466 map server crash

### ISSUE THREAD

**Issue by hnomkeng** [rathena/rathena#6989]
* **rAthena Hash**: 26ec100
* **Client Date**: 2021-11-16
* **Server Mode**: Pre-renewal
* **Description of Issue**: 
![image](https://user-images.githubusercontent.com/9112684/170811148-28dd1f7b-fc60-4ac7-8aad-36414b7ded7d.png)

**Comment by Playtester** [comment]
Item ID 1466 is Crescent Scythe and wearing it doesn't crash the map server for me.

**Comment by Daegaladh** [comment]
Maybe somehow st->script->instances went null or something, and it should be <= instead of != anyways
