### ISSUE TITLE
Npc's close after open for some players.

### ISSUE THREAD

**Issue by tmav94** [rathena/rathena#699]
As you can see, the npc Warper (for this example), close after player try to use it.

Vídeo: http://www.ragnatrek.org/download/video-1444852140.mp4.mp4
Git Ver: https://github.com/rathena/rathena/commit/e0b24fc670a3f2a056117746f79b7f90a999dd40

**Comment by RagnarokNova** [comment]
I saw this video being posted in both rAthena as well as in Hercules. Which emulator are you running? Also please fill this out,

Git Hash/Date: 
Client Date: 
Server Mode: Pre-RE/Renewal
Source/Script Mods: 
Descriptions:
How To Replicate:

**Comment by anacondaqq** [comment]
Is it clear warper? Can you show the code? I can't reproduce...

**Comment by aleos89** [comment]
I'm unable to reproduce this with the same script.
