### ISSUE TITLE
Table 'rathena.item_db' doesn't exist

### ISSUE THREAD

**Issue by cedricwaltercson** [rathena/rathena#6992]
Hi,

i have an issue following the guide based on Ubuntu Guide at the very last line:

'cat ./sql-files/*.sql | mysql -u rathena -p rathena'

I get this error : **ERROR 1146 (42S02) at line 431: Table 'rathena.item_db' doesn't exist**

Can you please assist me with this error message.

**Comment by Daegaladh** [comment]
Probably has something to do with file order.
Just load them manually one by one.

**Comment by admkakaroto** [comment]
For support, please use: https://rathena.org/board/

**Comment by cedricwaltercson** [comment]
This is the proper order that works:
cat ./sql-files/item_cash_db.sql | mysql -u rathena -p rathena
cat ./sql-files/item_cash_db2.sql | mysql -u rathena -p rathena
cat ./sql-files/item_db.sql | mysql -u rathena -p rathena
cat ./sql-files/item_db_equip.sql | mysql -u rathena -p rathena
cat ./sql-files/item_db_etc.sql | mysql -u rathena -p rathena
cat ./sql-files/item_db2.sql | mysql -u rathena -p rathena
cat ./sql-files/item_db_re.sql | mysql -u rathena -p rathena
cat ./sql-files/item_db_re_equip.sql | mysql -u rathena -p rathena
cat ./sql-files/item_db_re_etc.sql | mysql -u rathena -p rathena
cat ./sql-files/item_db_re_usable.sql | mysql -u rathena -p rathena
cat ./sql-files/item_db_usable.sql | mysql -u rathena -p rathena
cat ./sql-files/item_db2_re.sql | mysql -u rathena -p rathena
cat ./sql-files/mob_db.sql | mysql -u rathena -p rathena
cat ./sql-files/mob_db2.sql | mysql -u rathena -p rathena
cat ./sql-files/mob_db_re.sql | mysql -u rathena -p rathena
cat ./sql-files/mob_db2_re.sql | mysql -u rathena -p rathena
cat ./sql-files/mob_skill_db.sql | mysql -u rathena -p rathena
cat ./sql-files/mob_skill_db2.sql | mysql -u rathena -p rathena
cat ./sql-files/mob_skill_db_re.sql | mysql -u rathena -p rathena
cat ./sql-files/mob_skill_db2_re.sql | mysql -u rathena -p rathena
cat ./sql-files/main.sql | mysql -u rathena -p rathena
cat ./sql-files/logs.sql | mysql -u rathena -p rathena
cat ./sql-files/roulette_default_data.sql | mysql -u rathena -p rathena

Instead of 'cat ./sql-files/*.sql | mysql -u rathena -p rathena'
Please update on the wiki for other people.
