### ISSUE TITLE
Arrays probably is not supporting "Latin" Characters (iso-8859-1 or UTF-8)

### ISSUE THREAD

**Issue by tmav94** [rathena/rathena#700]
setarray .Shops$[1],"Cabeca Topo", 		// 1
	"Cabeca Meio",					// 2
	"Cabeca Baixo",					// 3
	"Vestimentas / Armaduras",			// 4
	"Armamentos",					// 5
	"Escudos",					// 6
	"Calcados",					// 7
	"Acessorios",					// 8
	"Mantos / Capas / Asas",			// 9
	"Cabeca Topo Visual",				// 10
	"Cabeca Meio Visual",				// 11
	"Cabeca Baixo Visual",				// 12
	"Vestimentas / Armadaduras Visuais",		// 13
	"Armamentos Visuais",				// 14
	"Escudos Visuais",				// 15
	"Calcados Visuais",				// 16
	"Acessorios Visuais",				// 17
	"Mantos / Capas Visuais",			// 18
	"Outros",					// 19
	"Multiposicao";					// 20

if you try it, for a "mes", you will get stranges characters in "Cabe@?$a Topo";
Can you check this?

Client 2014-10-04
Git Ver: https://github.com/rathena/rathena/commit/e0b24fc670a3f2a056117746f79b7f90a999dd40
Client ver: 51
LangType: 12
Server: Renewal Based
note: others npcs thats use normal "mes" to show messagens, works fine. Only Array's based npcs are causing some trouble.

**Comment by anacondaqq** [comment]
How do you check? Maybe it's client part do not support this encoding?

**Comment by tmav94** [comment]
Issue closed beacause i found a mismatch configuration in Server's Host
