### ISSUE TITLE
Item combo missing because AegisName was changed

### ISSUE THREAD

**Issue by kaninhot004** [rathena/rathena#7003]
* **rAthena Hash**: 86c8950e7

* **Client Date**: 20211103

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Item combo cannot find item that had AegisName changed in latest commit.
  * Expected Result: Item combo can find item
  * How to Reproduce: List of items
```
aegis_400098
aegis_400061
aegis_400119
aegis_400094
aegis_400118
aegis_400059
aegis_400022
aegis_400044
aegis_400099
aegis_400118
aegis_400120
aegis_400116
aegis_400117
aegis_20991
aegis_400078
aegis_400095
aegis_400021
aegis_400121
aegis_400079
aegis_400023
aegis_480136
aegis_400023
```

  * Official Information: -

* **Modifications that may affect results**: -

**Comment by Pokye** [comment]
*Invalid* https://github.com/rathena/rathena/pull/6859
Update your rA correctly as it was changed correctly in item_combo and item_db
![image](https://user-images.githubusercontent.com/98105181/171685237-813e9772-581a-4eed-aa7f-ab12f59139e5.png)
![image](https://user-images.githubusercontent.com/98105181/171685307-039ec822-77c2-483f-a170-580016dd39d2.png)

**Comment by kaninhot004** [comment]
Thanks. It was my false.
