### ISSUE TITLE
[Error]: quest_add: quest 12316 not found in DB.

### ISSUE THREAD

**Issue by tmav94** [rathena/rathena#701]
I receive that Error in server's emulator. I cant found where they come.

**Comment by cydh** [comment]
OK, open Notepad++, try find the '12316' in folder and all sub-folder on your server.
https://rathena.org/board/blog/47/entry-82-bug-report/
Thank you.

**Comment by aleos89** [comment]
Like @cydh said, can you search your directories and tell us where it's being pulled from for you.

It could be just a typo in an NPC you have. I'm getting no results for that anywhere in rAthena.

**Comment by Akkarinage** [comment]
Quest 12316 is used in http://pastebin.com/sfxVq8LY which is posted on Hercules' forums http://herc.ws/board/topic/9940-complete-old-glast-hein-instance/

Referenced in #493

**Comment by Akkarinage** [comment]
This isn't a bug, it isn't even an NPC that rA provides. It's more of a "suggestion" to add more content and should just be closed :stuck_out_tongue:

**Comment by aleos89** [comment]
It's parts of the NPC that's actually missing, which is why we considered it a bug rather than a suggestion.

**Comment by cydh** [comment]
then, it's not a bug 'yet' since we don't implement it.
