### ISSUE TITLE
Custom Skill (Import Folder) got reset after @ reloadskilldb

### ISSUE THREAD

**Issue by kaninhot004** [rathena/rathena#7011]
* **rAthena Hash**: 479954af3

* **Client Date**: 20211103

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Skills got reseted when @ reloadskilldb with custom skill (Import Folder).
  * Expected Result: Skill should stay at their current level.
  * How to Reproduce: Made a simple custom skill also put it on import folder.
  * Official Information: -

* **Modifications that may affect results**: Custom skill db, custom skill enum

https://user-images.githubusercontent.com/9493525/172034389-0a6e04ce-b56f-4c48-a705-1c19a057f75d.mp4

**Comment by Lemongrass3110** [comment]
Provide sample entries to and give proper reproduction steps (your video shows different things than your report).
Also does your character server or map server have any messages?

**Comment by kaninhot004** [comment]
Got it, I will provide more info soon.

**Comment by kaninhot004** [comment]
Problem solved.

Define MAX_SKILL should increased when adding new skills.
