### ISSUE TITLE
Royal Guard 'Inspiration' & 'Shield Spell' not applying bonus MATK

### ISSUE THREAD

**Issue by ArkknightX** [rathena/rathena#7017]
rAthena Hash: Latest Master

Client Date: 2021-11-17

Server Mode: Renewal

Description of Issue: Royal Guard's Skill 'Inspiration' and 'Shield Spell' does not apply bonus MATK. Skill description states that at max level, Inspiration adds +200 MATK, Shield Spell adds +150 MATK.

Result: Skill description states Inspiration adds +200 MATK, Shield Spell adds +150 MATK. However at the moment only ATK is correctly applied.

Expected Result: Inspiration should add +200 MATK, Shield Spell should add +150 MATK

How to Reproduce: N/A

Modifications that may affect results: None

Base Stats with no Buffs:
![MATK Base-No Buff](https://user-images.githubusercontent.com/93835310/172548750-b9c88c56-7984-4679-ad52-08c6524480a7.jpg)

Inspiration active:
![Inspiration-MATK After](https://user-images.githubusercontent.com/93835310/172548761-15f2bd32-d414-4adf-9480-8b3602236798.jpg)

Shield Spell active:
![ShieldSpell-MATK After](https://user-images.githubusercontent.com/93835310/172548768-5d0e520e-1564-447d-a712-29cc046d4a44.jpg)

**Comment by datawulf** [comment]
The skills are fine, it's just the status window that doesn't display MATK from buffs.

**Comment by aleos89** [comment]
As @datawulf said, it's hidden behind the status window.
