### ISSUE TITLE
Character Codification Issues (Latin Text are Wrong (Você -> VocÃ³)

### ISSUE THREAD

**Issue by tmav94** [rathena/rathena#702]
Hi guys, do you make some changes on character support?

Some days ago, i can type it whitout any problem...

[Você tem 5 minutos até o início da partida:]

Now i have it

[VocÃ³s tem 5 minutos atÃ(c) o inÃ-cio da partida]

How can i proceed? My Host Enterprise says that nothings change in the last 30 days.

**Comment by philg666** [comment]
try encoding your txt files in utf-8

**Comment by theultramage** [comment]
I recommend that you clarify what file you're editing and what text editor you're using.

**Comment by anacondaqq** [comment]
Try this decoder: https://www.artlebedev.ru/tools/decoder/advanced/

**Comment by aleos89** [comment]
As others have stated, make sure your encoding is correct.
