### ISSUE TITLE
Summoner / Spirit Handler mount display

### ISSUE THREAD

**Issue by Rushtic** [rathena/rathena#7023]
* **rAthena Hash**:  038c1778e18aa52dfd62d57a49d06f1055422e04

* **Client Date**: 20211117

* **Server Mode**: Renewal

* **Description of Issue**: Using Reins Of Mount (12622) only show riding icon without mount
*  Video Link: https://drive.google.com/file/d/1mpX3BnwIF5YmfEa21U4lhSpBdFHbz6R2/view?usp=sharing
  * Result: Must be display if using 12622
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by Pokye** [comment]
Confirmed!
![image](https://user-images.githubusercontent.com/98105181/173240508-b33fb77b-627e-4ddc-a75f-1c2967605e93.png)

**Comment by kaninhot004** [comment]
- Try 20211103
- Try update kRO to latest updates
- Try install Chris data & Chris sprite data again

**Comment by kaninhot004** [comment]
![image](https://user-images.githubusercontent.com/9493525/173267522-e0ca5b95-1651-4f0e-83f9-3eb3f606a0c5.png)

![image](https://user-images.githubusercontent.com/9493525/173267560-737612f5-a634-4618-9a22-7df5d016d1af.png)

Work fine on my end.

**Comment by Pokye** [comment]
> ![image](https://user-images.githubusercontent.com/9493525/173267522-e0ca5b95-1651-4f0e-83f9-3eb3f606a0c5.png)
> 
> ![image](https://user-images.githubusercontent.com/9493525/173267560-737612f5-a634-4618-9a22-7df5d016d1af.png)
> 
> Work fine on my end. (I used 20211103)

I found the problem, it's the Custom Jobs patch in WARP, when I disabled it, it appeared normally.
![image](https://user-images.githubusercontent.com/98105181/173270791-404f64c8-a89a-4e12-8c74-674f0e727fc1.png)

**Comment by Rushtic** [comment]
Ah okay thanks!
