### ISSUE TITLE
Enchant Grade UI force close

### ISSUE THREAD

**Issue by Rushtic** [rathena/rathena#7025]
* **rAthena Hash**: 756f9a73a7908915af971b271608578a2164c347

* **Client Date**: 20211117

* **Server Mode**: Renewal

* **Description of Issue**: Try using @enchantgradeui and drag the item (830011) Vivatus_F_Gatling then force closed
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by Rushtic** [comment]
> No problems found, works normally
> 
> ![Screenshot_9](https://user-images.githubusercontent.com/80197766/173527498-447c8296-a28c-418c-a962-be9ce9266012.png)
> 
> ![Screenshot_11](https://user-images.githubusercontent.com/80197766/173527544-ea0e4f33-b492-4180-afc1-1289c0776fdb.png)
> 
> ![Screenshot_10](https://user-images.githubusercontent.com/80197766/173527573-b72ef033-67a6-4399-90b5-0ebd9d4b17b0.png)
> 
> ![Screenshot_12](https://user-images.githubusercontent.com/80197766/173527609-942f28a3-d6fc-4486-a507-8880e2707d22.png)
> 
> .

Hi! what client you use? Thank you

**Comment by gravity-ro** [comment]
> * **Client Date**: 20211117
> 
> * **Server Mode**: Renewal

Client Date: 20211117
Server Mode: Renewal

**Comment by Rushtic** [comment]
> > * **Client Date**: 20211117
> > * **Server Mode**: Renewal
> 
> Client Date: 20211117 Server Mode: Renewal

Can i know what patch do you use on client 20211117? i already try select recommended but still got force close

**Comment by gravity-ro** [comment]
> > > * **Client Date**: 20211117
> > > * **Server Mode**: Renewal
> > 
> > 
> > Client Date: 20211117 Server Mode: Renewal
> 
> Can i know what patch do you use on client 20211117? i already try select recommended but still got force close

I used KRO Client.

**Comment by aleos89** [comment]
I'm unable to reproduce a crash as well. If you need further support, please post a topic on the forum.

**Comment by hangovernice** [comment]
dddd

**Comment by TBlazeWarriorT** [comment]
Also having this issue on my server. A few players reported the bug, and indeed I get the silent crash when I put any vivatus on it. Still a relevant issue, it seems

**Comment by badillabem** [comment]
mine too, I reproduce the crash by dragging an item to enchant grade ui
