### ISSUE TITLE
bone_drop not working

### ISSUE THREAD

**Issue by jmsngls** [rathena/rathena#7026]
* **rAthena Hash**: 756f9a73a7908915af971b271608578a2164c347

* **Client Date**: 2018-06-21a

* **Server Mode**: Pre-renewal

* **Description of Issue**: bone/pvp skull is not dropping when died in pvp map, even using option 2 which all modes is not dropping skulls.
  * Result: not dropping skull tried option 1 and 2
  * Expected Result: it should drop pvp skull
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by SapitoSucio** [comment]
I can confirm it doesn't drop skulls, im on renewal mode tho

**Comment by Playtester** [comment]
I assume you forgot to remove the trade restriction on the item as the comment on that config says.

```  - Id: 7420
    AegisName: Skull_
    Name: Skull
    Type: Etc
    Trade:
      NoTrade: true <--- remove this
      NoCart: true
      NoStorage: true
      NoGuildStorage: true
      NoMail: true
      NoAuction: true```

Once I removed that, the feature is working fine for me.

**Comment by Playtester** [comment]
I'm improving the comment on the config a bit in the linked PR above, so it's easier to understand what to do.
