### ISSUE TITLE
[Error]: npc_parse_mapflag: unrecognized mapflag 'nopvp' 

### ISSUE THREAD

**Issue by tmav94** [rathena/rathena#703]
quiz_02 <tab> mapflag <tab> nopvp

What's wrong?

**Comment by philg666** [comment]
are those spaces or tabulations?

**Comment by cydh** [comment]
we don't have this mapflag btw.
use
````
mapname	mapflag	pvp	0
removemapflag("mapname",mf_pvp);
pvpoff "mapname"
```

**Comment by tmav94** [comment]
https://rathena.org/wiki/Mapflag#nopvp

**Comment by aleos89** [comment]
That description is wrong. Whoever wrote that was probably just looking at the file names rather than the actual flag name inside the file.

The 'nopvp' section should be removed and added to the 'pvp' section. It's supposed to be:
```map<tab>mapflag<tab>pvp<tab>on```
or
```map<tab>mapflag<tab>pvp<tab>off```
