### ISSUE TITLE
Orc Warrior's (mob ID 1023) smoking is missing! 

### ISSUE THREAD

**Issue by Takiusu** [rathena/rathena#7030]
* **rAthena Hash**: latest

* **Client Date**: latest

* **Server Mode**: renewal

* **Description of Issue**: sometimes Orc Warrior just sits, starts to smoking and get some damage, but this thing doesn't exist in rAthena. 
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:

**Comment by Balferian** [comment]
> * **rAthena Hash**: latest
> 
> * **Client Date**: latest
> 
> * **Server Mode**: renewal
> 
> * **Description of Issue**: sometimes Orc Warrior just sits, starts to smoking and get some damage, but this thing doesn't exist in rAthena.
>   
>   * Result:
>   * Expected Result:
>   * How to Reproduce:
>   * Official Information:

Have you tested this with different client "servicetype" / "langtype" options?
Maybe this is client side problem, not sure.
With different servicetypes/langtypes, some functions in client may work differently.

**Comment by Playtester** [comment]
But the skills should be there, I see them in rAthena both pre-re and renewal. Are they not working?

**Comment by aleos89** [comment]
https://user-images.githubusercontent.com/3521753/174099254-10df65f3-8a73-4298-a559-01aec3984105.mp4

As @Balferian stated, this requires langtype 0 (most likely a regional lock for the rating of the game). Maybe someone can create a client patch to allow it to work in other langtype's if it's really something wanted by many.
