### ISSUE TITLE
After update SRC Grade Enchant : Script [ atcommand "@..........."; ] can't use

### ISSUE THREAD

**Issue by gravity-ro** [rathena/rathena#7032]
rAthena Hash: Latest
Client Date: Latest
Server Mode: Renewal

Description of Issue: 
After update SRC Grade Enchant 

Result:
In script command [ atcommand "@..........."; ] can't use if use this command Map Server is close no error code.
I mean some script error Ex. 
..........................................................
atcommand "@monster "+ .@xxxx +" "+ .xxxxxx +" Monster";
..
Before update command is can use fine.

Thank you advance.

**Comment by secretdataz** [comment]
You most likely screwed up your merges somehow. 
![image](https://user-images.githubusercontent.com/2021243/173932047-74711ae7-d247-40f3-87b3-ae093e681ea0.png)

**Comment by gravity-ro** [comment]
> You most likely screwed up your merges somehow. ![image](https://user-images.githubusercontent.com/2021243/173932047-74711ae7-d247-40f3-87b3-ae093e681ea0.png)

![xxxxx](https://user-images.githubusercontent.com/80197766/173941946-3285a5cc-ed69-4c98-973c-ef2ed1096a49.png)
