### ISSUE TITLE
Report Staff Team 

### ISSUE THREAD

**Issue by gravity-ro** [rathena/rathena#7033]
I don't know this person but this person keeps scolding Why is there such a bad team?

KUY in Thailand word it's spell Cock!

![Screenshot_3](https://user-images.githubusercontent.com/80197766/173949062-6a2397e4-f3d3-44bc-9afd-97ebfb22d781.png)

**Comment by Atemo** [comment]
We're not here to police a random word used without any meaning.

**Comment by Takiusu** [comment]
I would like to say this word remains me some russian word with the same meaning 🤣

**Comment by admkakaroto** [comment]
![hqdefault](https://user-images.githubusercontent.com/6227618/173964166-a0c7970c-bc80-4c0e-a846-4a1a34630742.jpg)
