### ISSUE TITLE
Spirit Handler not able to use Summoner Items

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#7034]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/2992879ee3e6b43a150dcecbd2c3ad384d380023
* **Client Date**: Irrelevant
* **Server Mode**: Renewal
* **Description of Issue**: Items that can be equipped by the Summoner job are not being equipped by the later Spirit Handler class.
  * Result: 
  * How to Reproduce: Try to equip any summoner item in Spirit Handler Class.

**Comment by Atemo** [comment]
`MAPID_SPIRIT_HANDLER = JOBL_FOURTH|JOBL_THIRD|JOBL_UPPER|JOBL_2_1|MAPID_SUMMONER,`
Shouldn't the item be equippable by SPIRIT_HANDLER, `Classes` from item_db being `All` by default ?

**Comment by Atemo** [comment]
Ha I see, spirit handler is 2-1 so it should have it own "field"
