### ISSUE TITLE
Autobonus on Pet_db.yml Effect don't work

### ISSUE THREAD

**Issue by EditorFc** [rathena/rathena#7038]
* **rAthena Hash**: Latest

* **Client Date**: 2021-11-17

* **Server Mode**: Renewal

* **Description of Issue**: autobonus on pet_db.yml effect don't work
  * Result: autobonus on pet bonus script didn't work.
  * Expected Result: autobonus on pet bonus script should work.
  * How to Reproduce: try to use pet MARIONETTE (Marionette_Egg ID : 9043) then change
  * `autobonus "{ bonus2 bSubEle,Ele_Neutral,2; heal 100,0; }",100,5000,BF_SHORT|BF_NORMAL;`
  * to
  * `autobonus "{ bonus bDex,1000; }",1000,5000,BF_SHORT|BF_NORMAL;`
  * type command `@petfriendly 1000` and yes change **pet.conf** `pet_status_support: yes`
  * Official Information: 
  

* **Modifications that may affect results**: try to attack dummy but effect autobonus don't work

![pet png 64daa6f1049d5bb9032de36534345843](https://user-images.githubusercontent.com/41179802/174235245-7690400a-1ebc-4d3e-be60-1e1fdc1ef5bb.png)

**Comment by null6385** [comment]
Yes, I confirm it's a bug.
![image](https://user-images.githubusercontent.com/59070443/174277598-36913a23-a80a-4d01-908b-a77d1639728b.png)
![image](https://user-images.githubusercontent.com/59070443/174277633-6e33bf80-67de-4927-b3ef-b6ec05316313.png)
