### ISSUE TITLE
Auction Crash

### ISSUE THREAD

**Issue by joelolopez** [rathena/rathena#704]
im using the most stable client, and a clean version of rathena.. i dont have any source mod applied.. at the sell tab in auction, when the close or cancel button is clicked even without any "buyers" the client crashes. i hope that someone can fix this.. make some conditions that if theres no buyers the close or cancel button will not function. because it causes the client to crash or hang

**Comment by aleos89** [comment]
What is "most stable client"? Can you please provide a date.

**Comment by joelolopez** [comment]
2013-08-07aRagexe sir aleos

**Comment by aleos89** [comment]
Closed in c75cc2a.
