### ISSUE TITLE
Cannot downgrade Climax buff

### ISSUE THREAD

**Issue by XanKriegor1** [rathena/rathena#7043]
* **rAthena Hash**: Latest + using the expanded 4th job PR

* **Client Date**: 211117

* **Server Mode**: Renewal 4th jobs

* **Description of Issue**: Arch Mages are unable to downgrade their Climax level. You can go from 1 to 2, 2 to 3, etc. But you cannot go from 5 to 4, or 4 to 3.
  * Result: No error or message is given but the climax level is not changed
  * Expected Result: They should be able to downgrade to lower levels of Climax
  * How to Reproduce: Try testing with levels 4 and 5. Full Bloom and Destructive Hurricane do support effects at Lv4 and damage at Lv5. Once you use Lv5, it doesn't let you downgrade to Lv4.

**Comment by Lemongrass3110** [comment]
Please report problems of a pull request by commenting on it.
