### ISSUE TITLE
[EP17.1]SP Cor quest wrong target mob?

### ISSUE THREAD

**Issue by PassakornBuadee** [rathena/rathena#7048]
* **rAthena Hash**:  Latest (master) https://github.com/rathena/rathena/blob/08edcb5b6bb1e2a8f592c4159fd59b25e91cd22f/db/re/quest_db.yml#L10126-L10130

* **Client Date**: 2021-01-07

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Wrong target mob? 
  * Expected Result: should be MD_EL_A17T instead of MD_E_EA1L? or none?
  * How to Reproduce: Receive attached quest above
  * Official Information: https://www.divine-pride.net/database/quest/16363
  

* **Modifications that may affect results**: -

**Comment by Akkarinage** [comment]
There is no mob with an internal name of `MD_E_EA1T`, only `MD_E_EA1L`.
