### ISSUE TITLE
red eruma item bonus and bonus5 bAddEffOnSkill

### ISSUE THREAD

**Issue by joelolopez** [rathena/rathena#705]
bonus5 bAddEffOnSkill is not working properly.. the status effects is instantly canceled when you heard the curse, stun, and other sound effects.. seems working but the status ailment wont last longer that it should be.. there are some cases that it only last longer or work properly if the target is immobilized e.g frozen , stun

red eruma card
in my description it causes curse effect when dealing magic attacks but the script on the database is 
bonus3 bAddEff,Eff_Curse,100,ATF_SKILL; <-- triggers when using a skill?

but that "ATF_SKILL" still works as  ATF_MAGIC, it means ATF_SKILL still triggers when using magic spells.  the only problem is it calls ATF_SKILL instead of ATF_MAGIC

i hope that someone can fix this and double check the other item_bonus in  Status-related Bonuses

**Comment by nanakiwurtz** [comment]
Ok, I'll recheck them
