### ISSUE TITLE
[EP17.2] Hidden Garden + Security Area 1&2 Bugs (dbs+npcs)

### ISSUE THREAD

**Issue by PassakornBuadee** [rathena/rathena#7051]
* **rAthena Hash**:  bd8bf89dfb62ae373e2ed930ed5b73d0604e7c7a (branch script/episode_17_2 latest as 22-06-22)

* **Client Date**:  - (Any)

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Player will unable to complete side quest and daily quests
  * Expected Result: Player can complete Hidden Garden and Security Area 1/2
  * How to Reproduce: Just play this instance
  * Official Information: https://www.divine-pride.net/database/npc/54738/hidden
  
https://github.com/rathena/rathena/blob/bd8bf89dfb62ae373e2ed930ed5b73d0604e7c7a/npc/re/instances/HiddenGarden.txt#L16
  
You use " 'map$ " all the rest of script just add "$"
  
  https://github.com/rathena/rathena/blob/bd8bf89dfb62ae373e2ed930ed5b73d0604e7c7a/npc/re/quests/quests_17_2.txt#L10522-L10561
  
Either change ".@md_name$ = " or 

https://github.com/rathena/rathena/blob/bd8bf89dfb62ae373e2ed930ed5b73d0604e7c7a/db/re/instance_db.yml#L389-L399

for matching Instance name. otherwise you cannot create/enter instance.

And from the above instance_db.yaml, change spawn location of Area 2 (Hard Mode) to match hidden npc for hard mode

https://github.com/rathena/rathena/blob/bd8bf89dfb62ae373e2ed930ed5b73d0604e7c7a/npc/re/instances/HiddenGarden.txt#L1347

X:59 Y:214 instead of  X: 45 Y: 208 in 2nd Area

https://github.com/rathena/rathena/blob/bd8bf89dfb62ae373e2ed930ed5b73d0604e7c7a/npc/re/instances/HiddenGarden.txt#L1520-L1521

switch these two lines otherwise it will not match with npc name (will out of bound)

https://github.com/rathena/rathena/blob/bd8bf89dfb62ae373e2ed930ed5b73d0604e7c7a/npc/re/instances/HiddenGarden.txt#L1342

comment or delete this = ='

https://github.com/rathena/rathena/blob/bd8bf89dfb62ae373e2ed930ed5b73d0604e7c7a/npc/re/instances/HiddenGarden.txt#L1362-L1363

add `enablenpc instance_npcname("#172_sec_lambda");` between these two lines

It should be working fine now after update according to these changes. I tested on all 3 modes (Story, Sec1, Sec2) with only these changes.

**Comment by Akkarinage** [comment]
This is probably the best-written Issue I've seen for a long time!

However, these comments should really be in the actual Pull Request instead. If you hit the "Review Changes" button on #6799 
 Files tab, then you'll be able to add all these changes as "code suggestions" which will allow us to simply "Merge Suggestion" straight into the Pull Request.

10 Points to Gryffindor.
