### ISSUE TITLE
Heat Barrel (Rebelion)

### ISSUE THREAD

**Issue by FrFrMako** [rathena/rathena#7054]
* **rAthena Hash**:  Last

* **Client Date**: Any

* **Server Mode**: Renewal

* **Description of Issue**: Heat Barrel ([Hit barrel )](https://www.divine-pride.net/database/skill/2568) increases the damage of all skills
  * Result: 
  * Expected Result: Do not increase skill damage
  * How to Reproduce:  Use Heat Barrel then any damage skill
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by attackjom** [comment]
From playing in Kro, it increase flat damage like Power thrust buff that show more effcient in normal attack than skill attack.

**Comment by FrFrMako** [comment]
But here you can triple your damage with all skills, I see replays from Kro and there the change are minimum, they don't even bother using the buff

**Comment by datawulf** [comment]
Are there any % values known as in how much the increase is? Or something like autoattack before / after buff?

**Comment by FrFrMako** [comment]
at 4:11 you can see the hit like 1400k~2200k with auto fire bombs, then at 4:35 his using heat barrel and do almost the same damage
https://www.youtube.com/watch?v=3ugtVS9Tqww
And yes his basic attack increased a lot
