### ISSUE TITLE
Missing maps from map_cache.dat

### ISSUE THREAD

**Issue by Pokye** [rathena/rathena#7057]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/c93ba77c0cb1652ea4db07aecf36588921c72f68

* **Client Date**:  Irrelevant

* **Server Mode**: both

* **Description of Issue**: Gone almost all maps from map_chache.dat from PRE and RE. the files only have 28kb of both folders

![image](https://user-images.githubusercontent.com/98105181/175350646-f54a2296-e99b-4f71-83c6-0c26dea859b1.png)

**Comment by Pokye** [comment]
> This is intended after #6984. We are working on another refactor though.

Ahhhh! thanks. Do I close the issue?

**Comment by aleos89** [comment]
Yeah, we will create a PR soon with a more modernized solution.
