### ISSUE TITLE
doc/item_bonus.txt confusion

### ISSUE THREAD

**Issue by joelolopez** [rathena/rathena#706]
as you can see item_bonus.txt mention some of these terms

* Trigger criteria (bf)
	BF_SHORT: Trigger on melee attacks
	BF_LONG: Trigger on ranged attacks
	(Default: BF_SHORT+BF_LONG)
   
	BF_WEAPON: Trigger on weapon skills 
	BF_MAGIC: Trigger on magic skills 
	BF_MISC: Trigger on misc skills
	(Default: BF_WEAPON)
   
	BF_NORMAL: Trigger on normal attacks
	BF_SKILL: Trigger on skills

but none of this terms are used in the listed item_bonuses

the item_bonus.txt uses this terms instead of the terms above

                              		y is the trigger criteria:
                              		 Effect target: (Default: Attacked target)
                              		  ATF_SELF   = trigger effect on self
                              		  ATF_TARGET = trigger effect on target
                              		 Attack range criteria: (Default: All attacks)
                              		  ATF_SHORT  = trigger on melee attacks
                              		  ATF_LONG   = trigger on ranged attacks
                              		 Skill/attack type criteria: (Default: Physical/weapon)
                              		  ATF_WEAPON = trigger on weapon skill / physical attacks
                              		  ATF_MAGIC  = trigger on magic skills
                              		  ATF_MISC   = trigger on misc skills

but BF_ terms are still used in the item_dbs

e.g 
4564,Stalker_Gertie_Card,Stalker Gertie Card,6,20,,10,,,,,,,,16,,,,,{ bonus bHit,(readparam(bLuk)>=110)?40:20; bonus5 bAutoSpellWhenHit,"ST_FULLSTRIP",1,70,BF_WEAPON,1; },{},{} 

whats the purpose of ATF_ terms if the databases uses BF_ terms?now im confused

**Comment by nanakiwurtz** [comment]
They are used accordingly to each bonus type, in this case, the `bonus5 bAutoSpellWhenHit` use the following format: `bonus5 bAutoSpellWhenHit,sk,y,n,bf,i;` <-- y in this case is the skill level, not trigger criteria.

Currently ATF_ only used on `bonus4 bAddEffWhenHit` and `bonus5 bAddEffOnSkill`
I hope this clears your confusion
