### ISSUE TITLE
Ammo not consumed

### ISSUE THREAD

**Issue by LolyAll** [rathena/rathena#7066]
* **rAthena Hash**: https://github.com/rathena/rathena/commit/17d6381901197c4687ec0fb3eb420a429d2cda45
* **Client Date**: 
* **Server Mode**: renwwal
* **Description of Issue**: If you use some skills that consume items you are not consuming, others are, but test with : AC_DOUBLE, RA_ARROWSTORM and others, are not working.

But using: AC_SHOWER its working...

You can try any ammo item, ammo requirement not working in some cases.
![001](https://user-images.githubusercontent.com/38357266/175827288-41144b70-a628-4e5e-a896-fc9a5cb7eaed.png)

![002](https://user-images.githubusercontent.com/38357266/175827292-c786c2d5-c496-4324-a1bf-edac54833443.png)

```
// Are arrows/ammo consumed when used on a bow/gun?
// 0 = No
// 1 = Yes
// 2 = Yes even for skills that do not specify arrow consumption when said 
//     skill is weapon-based and used with ranged weapons (auto-guesses which 
//     skills should consume ammo when it's acquired via a card or plagiarize)
arrow_decrement: 1
```

**Comment by aleos89** [comment]
I'm unable to reproduce this on 394dab1. If you're using the PR you linked, then you might need to report the bug there.
