### ISSUE TITLE
Neutral Barrier and Stealth Field 

### ISSUE THREAD

**Issue by panko11** [rathena/rathena#707]
Bug on rathena: https://www.youtube.com/watch?v=RmDUWX2F6wc
Confirmation 1 : https://youtu.be/kvRIYnaqXNE?t=207
Confirmation 2: https://youtu.be/kvRIYnaqXNE?t=615
Confirmation 3: https://youtu.be/NT4KDcrJRO8?t=3416

**Comment by cydh** [comment]
# [Please read this when open new issue. Also for other you-started issues. Thank you very much.](https://rathena.org/board/blog/47/entry-82-bug-report/) #

**Comment by panko11** [comment]
Git Ver: https://github.com/rathena/rathena/commit/e0b24fc670a3f2a056117746f79b7f90a999dd40

Would it be this?

**Comment by aleos89** [comment]
Fixed in a7b8fd4.
