### ISSUE TITLE
[ Skill ] Arrow Vulcan .

### ISSUE THREAD

**Issue by StarGmes** [rathena/rathena#7080]
* **rAthena Hash**: Current

* **Client Date**: 2021-11-03

* **Server Mode**: Re/Pre

* **Description of Issue**: 

has no hit animation with the "Arrow Vulcan" ability.

![noanimation1](https://user-images.githubusercontent.com/50535033/176788851-6b015ad5-6cc9-4517-86c6-a5a879af955c.gif)

![noanimation2](https://user-images.githubusercontent.com/50535033/176788872-051c0b58-5974-4d09-9ad4-98dc9d061e2b.gif)

![noanimation3](https://user-images.githubusercontent.com/50535033/176788887-7c697bcd-8937-4f8b-a431-59d03f376fbf.gif)

**Comment by Haydrich** [comment]
Its related to your client date, newer clients Arrow Vulcan/Sonic Below/Cross Impact has no hit animation, older clients like 2018-6-20 has hit animation

**Comment by StarGmes** [comment]
> Its related to your client date, newer clients Arrow Vulcan/Sonic Below/Cross Impact has no hit animation, older clients like 2018-6-20 has hit animation

If it seems the same thing happens with those skills, I had not noticed and if it is indeed happening in all the new exe
