### ISSUE TITLE
Using @whodrops will cause the entire server lag

### ISSUE THREAD

**Issue by voyfmyuh** [rathena/rathena#7081]
rAthena Hash: [Current](https://github.com/rathena/rathena/commit/15a5bcb2cf6ef30d9322d04ee7c30d96c5eca7a3)
Client Date: 2021-11-03
Server Mode: Re
Description of Issue:
Using @whodrops will cause the entire server lag
It may be due to the time of reading, but this is not the case in previous versions!
e.g. @whodrops 111

**Comment by aleos89** [comment]
Can you try the fix in #7064 and let me know if it helps you out any?
