### ISSUE TITLE
RK_Speardynamo ATK Issue.

### ISSUE THREAD

**Issue by LadyNanuia** [rathena/rathena#7082]
* **rAthena Hash**: 

* **Client Date**: 

 2020/09/04

* **Server Mode**: 

 Renewal

* **Description of Issue**: 
  * Result:  When using "Spear dynamo/Concentration" on Rune knights, its supposed to give +% Physical attack but skills trhat scale off of Physical attack see no difference in damage and its 15% which should at the very least show some difference, meaning that the +% ATK portion is not working properly.
  * Expected Result:  items / skills / buffs that adds +% physical attack should improve the damage of skills that scale off of Physical attack.
  * How to Reproduce:  Use a skill a few times that scales off of Physical damage, then use level 5 Spear dynamo / concentration and the skills will still do the same damage as before even with the buff on from Concentration/Spear Dynamo
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by datawulf** [comment]
Concentration has a minimal effect on skills as it adds onto the base ratio of the skill. The difference may be lost within damage variance. You will feel this more for auto attacks.

**Comment by LadyNanuia** [comment]
> Concentration has a minimal effect on skills as it adds onto the base ratio of the skill. The difference may be lost within damage variance. You will feel this more for auto attacks.

That sounds really bad, are you sure this is intended? it really makes the skill buff kinda meh

**Comment by Playtester** [comment]
> > Concentration has a minimal effect on skills as it adds onto the base ratio of the skill. The difference may be lost within damage variance. You will feel this more for auto attacks.
> 
> That sounds really bad, are you sure this is intended? it really makes the skill buff kinda meh

This is how it works in Renewal. So a 500% damage skill becomes a 515% damage skill.

In Pre-Renewal it works differently. There the damage is multiplied with 1.15x.

Both is already working as intended.
