### ISSUE TITLE
Leak Card effect

### ISSUE THREAD

**Issue by XanKriegor1** [rathena/rathena#7086]
* **rAthena Hash**: 

* **Server Mode**:  Renewal

* **Description of Issue**: 
  * Result: Leak Card's description says it is triggered when dealing attacks. The script, on the other hand, activates only when the player is hit(bAddEffWhenHit). Which one is correct, the description or the script?

**Comment by Atemo** [comment]
The description is `When receiving physical or magical attacks...`, so both the escription and the script are corrects.

**Comment by XanKriegor1** [comment]
The item description on ratemyserver and on llchrisll's translation say explicitly "When dealing physical or magical damage", not receiving.

**Comment by Atemo** [comment]
Read the Korean description (which we use) `물리, 마법 공격을 받을 시 높은 확률로 적에게 혼란, 공포를 건다.`
https://www.divine-pride.net/database/item/4520/leak-card

**Comment by Daegaladh** [comment]
I can confirm it activates when receiving damage on official servers.

**Comment by llchrisll** [comment]
> 

Many of those items might not be correct or even got changed, as I took over zackdreaver's project. So if you notice any kind of issues like that, please pm me directly or join my discord for the project and report it there^^. Will update it accordingly.
