### ISSUE TITLE
Kaite and AoE Magical Skills

### ISSUE THREAD

**Issue by XanKriegor1** [rathena/rathena#7087]
* **rAthena Hash**: Latest

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: I remember that in Pre-Renewal, Soul Linker's Kaite was capable of reflecting AoE spells such as Storm Gust. It seems this isn't the case anymore. Is this intended? I also noticed that Arch Mage's Deadly Projection seems to nullify reflect effects, not just Kaite but also things like Maya Card. Again, is this intended behavior?
  * Expected Result: Kaite should reflect AoE spells, such as Storm Gust(worked like this before at least)
  * How to Reproduce: Tested in a PK Scenario using Storm Gust.

**Comment by Playtester** [comment]
Please see: https://github.com/rathena/rathena/issues/2409

Do you have any official information that shows otherwise?

**Comment by XanKriegor1** [comment]
> Please see: #2409
> 
> Do you have any official information that shows otherwise?

No, I simply brought this up since I remember Kaite reflecting AoE magic on old eA and rA servers.

**Comment by Playtester** [comment]
Ok, then I'll be closing this as the other report tested it on Aegis.
