### ISSUE TITLE
Monk Absorb Spirit Sphere Bugged

### ISSUE THREAD

**Issue by LadyNanuia** [rathena/rathena#7089]
* **rAthena Hash**: 

* **Client Date**: 

 2020/09/04

* **Server Mode**: 

 Renewal

* **Description of Issue**: 
  * Result:  Monk Absorb spirit sphere is supposed to have a 10% chance to drain SP equal to target level 2x, however all it does is fail against monsters
  * Expected Result:  using MO_ABSORBSPIRITS you should have a 10% chance to regen SP equal to target level 2x when using it against Monsters.
  * How to Reproduce:  use latest rA , make a monk, use "Absorb Spirit Sphere" on a monster.
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
```cpp

} else if (dstmd && !status_has_mode(tstatus,MD_STATUSIMMUNE) && rnd() % 100 < 20) { // check if target is a monster and not status immune, for the 20% chance to absorb 2 SP per monster's level [Reddozen]
			i = 2 * dstmd->level;
			mob_target(dstmd,src,0);
		}
```
It's there, just limited to monsters. I don't know much about the Monk class but maybe someone else has more info.

**Comment by Daraen1** [comment]
what monster did you try on?
![absorb spirit](https://user-images.githubusercontent.com/75265726/177056709-cd241d91-8e24-40b7-ad0a-6bc1783c3cd9.png)

**Comment by LadyNanuia** [comment]
Nevermind this issue, we figured it out, it requires you to hold down shift like when you're heal bombing, closing the issue, thanks for your responses though!
