### ISSUE TITLE
Soul Explosion and Nova Explosion

### ISSUE THREAD

**Issue by XanKriegor1** [rathena/rathena#7096]
* **rAthena Hash**: Latest

* **Server Mode**: Renewal

* **Description of Issue**: Nova Explosion(Star Emperor) and Soul Explosion(Soul Reaper) are not affected by Global PK damage reductions(misc.conf) in PK areas, but are affected by the WoE damage reductions(guild.conf). I set my PK damage and WoE damage values to the same values, and as such I expect all skills to do the same damage in PK and in WoE. It behaves that way for all skills except those two.

  * Result: These two skills are not affected by PK damage settings(misc.conf) but are from WoE damage settings(guild.conf)
  * Expected Result: Either it's affected by both, or not affected by both.
  * How to Reproduce: Set PK mode to ON, assign the exact same values for PK and WoE damage(for my test I set everything to 5). You can easily test this by going in and out of castles. Inside is governed by guild.conf and the areas outside are governed by misc.conf. Remember to use agitstart.

**Comment by aleos89** [comment]
Quickly looking, these two skills as well as Pressure and Gravitation (in pre-renewal) are set to do fixed damage so they break out before reaching the PK damage adjustment.

**Comment by XanKriegor1** [comment]
> Quickly looking, these two skills as well as Pressure and Gravitation (in pre-renewal) are set to do fixed damage so they break out before reaching the PK damage adjustment.

Suggestion: Fix these four skills so that they don't break out before the final damage calculation.
Then, create a skill_db flag that allows us to bypass PK and/or WoE reductions. This would give us total control over this behavior.
