### ISSUE TITLE
SHC_ENCHANTING_SHADOW official behavior

### ISSUE THREAD

**Issue by eppc0330** [rathena/rathena#7104]
* **rAthena Hash**: master

* **Client Date**: 20211117

* **Server Mode**: Renewal

* **Description of Issue**:  SHC_ENCHANTING_SHADOW from rA has different behavior with one from KRo.
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
    First difference, we need to know that Enchanting Shadow is not only triggered on normal attack.
    It also can be triggered by the skill. 

    Second, amount of increased damage per stack and limit of stack info is lacking. So I have tested it.
    ![status](https://user-images.githubusercontent.com/47050704/178981183-47c68e0c-5f60-4f9e-be99-ed07eb79ac8a.png)
    Tested with character above, with critical normal attack.
    Starts with 9973 damage. Below is a damage log.
    ![Damage log](https://user-images.githubusercontent.com/47050704/178985120-f6edb271-9857-474d-9f1e-f366a6d75af5.png)

    9973
    10274
    10575
    10876
    11177
    11480
    11781
    12082
    12383
    and so no....

    Each stack adds about 3% damage more.
    Something interesting is that I couldn't find a limit of the stack. 
    The damage is continuously increased as the stack added.
    However it's not easy to stack more than 8 because triggering stack does not reset duration of the stack.
    New stack will not affect previous stacks' duration. Check below:
    ![Stack ends](https://user-images.githubusercontent.com/47050704/178986732-3e1794cc-13c0-44ea-baad-166854036db4.gif)
    We can see that as durations of some stacks are ended, the damage bonus is not reset as 0%.
    Instead, 3% damage has been decreased as each stack ended.

    Finally, as we see in screenshot when triggering stack, skill shows scratching effect on target's head. 
    The number of this scratching effect is 677.

  

* **Modifications that may affect results**:

**Comment by Atemo** [comment]
Do you mind testing (critical damage) without damage modifier (no item to increase critical, racial, class damage..) to check the final dmg and if the status is affected?

**Comment by eppc0330** [comment]
@Atemo 
![No gear status](https://user-images.githubusercontent.com/47050704/178999756-9a7fe101-8add-4a5a-ac1b-099559f8a452.png)
Tested with char no gear in main equipment.
This shadows are booster shadow. Have no damage modifier option.
Below is the damage log. Starts with 1800 critical normal damage, with no weapon.

1800
1856
1912
1968
2024
2080
2136
2192

56 damage is added on every stack.
It seems like 3%, but actually 3% of 1800 is 54.
