### ISSUE TITLE
Gvg mapflag can't damage to target.

### ISSUE THREAD

**Issue by hnomkeng** [rathena/rathena#7112]
* **rAthena Hash**: bb16e43
* **Client Date**: 2021-11-17
* **Server Mode**: Pre-renewal
* **Description of Issue**:  Gvg mapflag can't damage to target.

![image](https://user-images.githubusercontent.com/9112684/179261021-a391700e-43b9-4b5a-a5ec-b0651164ae75.png)

VDO : https://streamable.com/e/ktqogm

**Comment by hnomkeng** [comment]
> I tested on the same hash as you, warped to `guild_vs1` and was able to attack as normal.

![image](https://user-images.githubusercontent.com/9112684/179270309-f13bbf4f-b022-4b8a-9cf5-44f8b052c3ea.png)

**Comment by LolyAll** [comment]
here all working too, you have custom changes on exed or in emulator.

**Comment by hnomkeng** [comment]
> here all working too, you have custom changes on exed or in emulator.

emulator original code, will check client again 😑

**Comment by hnomkeng** [comment]
![image](https://user-images.githubusercontent.com/9112684/179337367-70458e21-16f4-4e1d-9202-58313b88946a.png)
Fixed. :D
