### ISSUE TITLE
Status timer wrong after relogin to map

### ISSUE THREAD

**Issue by kaninhot004** [rathena/rathena#7123]
* **rAthena Hash**: 78b4f4420

* **Client Date**: 20211103

* **Server Mode**: Both

* **Description of Issue**: 
  * Result: Some status timer show 1 second after relogin to map.
  * Expected Result: Status timer show current time left after relogin to map.
  * How to Reproduce:
  Use `@item 12459` -> Eat it -> Exit to character selection -> Enter game
  Use Shield Spell -> Exit to character selection -> Enter game
  * Official Information: -

* **Modifications that may affect results**: -

**Comment by idk-whoami** [comment]
i confirmed

![บันทึก_2022_07_20_21_35_16_662](https://user-images.githubusercontent.com/60462533/180009818-87571cac-6da8-4cec-8886-188cf0cf9c0b.gif)

**Comment by idk-whoami** [comment]
Shield Spell too

![บันทึก_2022_07_20_21_40_02_437](https://user-images.githubusercontent.com/60462533/180011279-33746f43-3784-41a3-a43d-136215bf3819.gif)
