### ISSUE TITLE
Server Crash after install Improvement 4th

### ISSUE THREAD

**Issue by hakurag** [rathena/rathena#7128]
[New LWP 23558]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `./map-server'.
Program terminated with signal 11, Segmentation fault.
#0  0x0000000000634474 in run_script_main (st=0x2a75a1b4) at script.cpp:4395
4395                    enum c_op c = get_com(st->script->script_buf,&st->pos);
(gdb) bt  full
#0  0x0000000000634474 in run_script_main (st=0x2a75a1b4) at script.cpp:4395
        cmdcount = 655329
        gotocount = 2048
        sd = <optimized out>
        stack = 0x3353a374
#1  0x00000000005815d9 in npc_event_sub (sd=0x2b9e1940, ev=0x1a23ddbc, eventname=0x28d0f28c "dup_2257_110017492::OnMobDead") at npc.cpp:1755
        ontouch_event_name = "dup_2257_110017492::OnTouch_\000\000\000\000@-\202\000\000\000\000\000O\005\\\000\000\000\000\000ݯ\000\000\000\000\000\000\064\313\320(\000\000\000\000\270}\241\003\000\000\000\000X?\201\t"
        ontouch2_event_name = "dup_2257_110017492::OnTouch\000\000\000\000\000_\002\000\000\000\000\000\000@\031\236+", '\000' <repeats 12 times>, "#\314S", '\000' <repeats 13 times>, " \000\000\000\060"
#2  0x0000000000581777 in npc_event (sd=0x2b9e1940, eventname=0x28d0f28c "dup_2257_110017492::OnMobDead", ontouch=0) at npc.cpp:1789
        ev = 0x1a23ddbc
        nd = 0x31022e94
        __FUNCTION__ = "npc_event"
#3  0x000000000055d97c in mob_dead (md=md@entry=0x28d0cb34, src=src@entry=0x2b9e1940, type=type@entry=0) at mob.cpp:3170
        status = 0x28d0cf90
        sd = <optimized out>
        tmpsd = {0x2b9e1940, 0x0 <repeats 29 times>}
        mvp_sd = 0x2b9e1940
        second_sd = 0x2b9e1940
        third_sd = 0x0
        pt = {{p = 0x20b4758c, id = 0, zeny = 0, base_exp = 0, job_exp = 0}, {p = 0x0, id = 0, zeny = 0, base_exp = 0, job_exp = 0} <repeats 29 times>}
        i = <optimized out>
        temp = <optimized out>
        count = <optimized out>
        m = <optimized out>
        dmgbltypes = <optimized out>
        mvp_damage = <optimized out>
        tick = 1482799177
        rebirth = false
        homkillonly = <optimized out>
        merckillonly = false
#4  0x00000000006fdb72 in status_damage (src=src@entry=0x2b9e1940, target=target@entry=0x28d0cb34, dhp=dhp@entry=7952398, dsp=dsp@entry=0, dap=dap@entry=0, walkdelay=walkdelay@entry=720, flag=0, skill_id=2554) at status.cpp:1438
        status = <optimized out>
        hp = <optimized out>
        sp = <optimized out>
        ap = <optimized out>
        __FUNCTION__ = "status_damage"
#5  0x0000000000457f12 in status_damage (skill_id=2554, flag=0, walkdelay=720, dsp=0, dhp=7952398, target=0x28d0cb34, src=0x2b9e1940) at status.hpp:3230
No locals.
#6  status_fix_damage (skill_id=2554, walkdelay=720, hp=7952398, target=0x28d0cb34, src=0x2b9e1940) at status.hpp:3234
No locals.
#7  battle_damage (src=src@entry=0x2b9e1940, target=target@entry=0x28d0cb34, damage=7952398, delay=720, skill_lv=<optimized out>, skill_id=<optimized out>, dmg_lv=ATK_DEF, attack_type=321, additional_effects=true, tick=1482799173,
    isspdamage=false) at battle.cpp:271
No locals.
#8  0x0000000000458154 in battle_delay_damage_sub (tid=<optimized out>, tick=1482799173, id=<optimized out>, data=129146552) at battle.cpp:322
        src = 0x2b9e1940
        target = 0x28d0cb34
        sd = <optimized out>
        dat = 0x7b29eb8
#9  0x000000000073bab0 in do_timer (tick=<optimized out>) at timer.cpp:374
        tid = 247464
        diff = -4
        __FUNCTION__ = "do_timer"
#10 0x000000000040d98e in main (argc=1, argv=0x7ffe6a2761d8) at core.cpp:380
        next = <optimized out>
(gdb)

**Comment by aleos89** [comment]
Yes, please report to the specific PR since it's still open.
