### ISSUE TITLE
Opening EQ window when entering portal = Crash

### ISSUE THREAD

**Issue by LadyNanuia** [rathena/rathena#7131]
* **rAthena Hash**: 

* **Client Date**:
 2020/09/04

* **Server Mode**: 
 Renewal

* **Description of Issue**: 
  * Result:  If you open your EQ window while entering an instance, the game crashes
  * Expected Result:  It should not crash, it should rather prevent you from trying to open the EQ window until youre on the other side
  * How to Reproduce:  Run into a portal and hit Alt+Q as you enter a portal
  * Official Information: 
  

* **Modifications that may affect results**:  None

**Comment by vstumpf** [comment]
This seems like a client issue, not a server issue.

**Comment by aleos89** [comment]
Agreed, this would be an issue related to the client date/version.
