### ISSUE TITLE
Monster consume item does not work properly it seems

### ISSUE THREAD

**Issue by LadyNanuia** [rathena/rathena#7132]
* **rAthena Hash**: 

* **Client Date**:  Latest rAthena hash.

* **Server Mode**:  Renewal

* **Description of Issue**: 
* setting
* // Looting monster actions.
// 0 = Monster will consume the item.
// 1 = Monster will not consume the item.
monster_loot_type: 0
  * Result:  when set to 0, the monster will continue to eat items and then drop all of them even despite it being set to "consume the item" if you put it to 1, it will stop once its full
  * Expected Result:  if you set it to 0, any item it loots should vanish  as far as i understand it
  * How to Reproduce:  set it to 0, spawn a poring, drop shit on the ground and let it eat them ( costumes etc ) and then kill the poring, it will drop all the items you gave it.
  * Official Information: 
  

* **Modifications that may affect results**:  None

**Comment by Daegaladh** [comment]
That's not how it works, when set to 0 looter monster will consume the items (completely deleted) when they eat more than 10 items, when they loot the 11th, the first item they looted disappears forever. The other 10 will drop when the mob is killed

If you wanna make the items instantly disappear you need to set both monster_loot_type and LOOTITEM_SIZE to 0
