### ISSUE TITLE
Song skill force end skill duo can't walk.

### ISSUE THREAD

**Issue by hnomkeng** [rathena/rathena#7134]
* **rAthena Hash**: 322709f
* **Client Date**: 2022-11-16
* **Server Mode**: Pre-renewal
* **Description of Issue**: Song skill force end skill duo can't walk.

**Comment by hnomkeng** [comment]
> Can you detail a little more please. Is this only related to specific songs or all songs?

force end song skill with switch weapon. (duo skill only)

**Comment by hnomkeng** [comment]
vdo : https://youtu.be/vN4sLUcxqKQ

**Comment by aleos89** [comment]
I'm testing on a clean build of [a0bc2c0](https://github.com/rathena/rathena/commit/a0bc2c0c3d85afb311607c42b11216fababd80d6) and I can't reproduce this. The duo-song casts and I can't move like normal. I use Adaptation and then it shows me cast the skill and both the Bard and Dancer can move after using it.

**Comment by hnomkeng** [comment]
@aleos89  maybe issue on Into the Abyss (skill id : 312)

**Comment by hnomkeng** [comment]
@aleos89  thank you bro. f6d9484 work
