### ISSUE TITLE
Warning command /call

### ISSUE THREAD

**Issue by idk-whoami** [rathena/rathena#7139]
* **rAthena Hash**: 84d295e78431815fd823687c897ec0f180542085

* **Client Date**: 20211103

* **Server Mode**: re

**Is your request related to a missing feature?**

![Capture](https://user-images.githubusercontent.com/60462533/181066885-6b3a9d1b-63a5-4f6b-b425-b280dd751a38.PNG)

        [Warning]: clif_parse_configuration: received unknown configuration type '1'...  

**Describe the solution you'd like** 

       when use command /call  disable  recall from  party leader skill AB_CONVENIO

**Describe alternatives you've considered**

**Additional context**

**Comment by Akkarinage** [comment]
![putty_aFqFSkPAVR](https://user-images.githubusercontent.com/4101952/187513821-d5c1e5e3-83c5-4e54-a0db-46dcd61645f8.png)

Hash: a2ce09fd5632cd77a76ea444aa98b71038091602
Mode: Pre-Renewal
Client: 20211103
