### ISSUE TITLE
mob skill condition closedattacked/longrangeattacked do not trigger on ground targeted skills

### ISSUE THREAD

**Issue by datawulf** [rathena/rathena#7141]
* **rAthena Hash**:  [84d295e](https://github.com/rathena/rathena/commit/84d295e78431815fd823687c897ec0f180542085)
* **Client Date**: 20220602
* **Server Mode**:  Renewal (both)
* **Description of Issue**: 
  * Result: mob with longrangeattacked skill condition doesn't trigger skill when attacked by ground targeting skills like Fire Rain / Crazy Weed
  * Expected Result: mob with longrangeattacked skill condition should use skill when attacked by ground targeting skills like Fire Rain / Crazy Weed
  * How to Reproduce:
  * set mob skill condition to longrangeattacked 
  * attack with long range ground targeted skill like Fire Rain / Crazy Weed
  * Official Information: verified behaviour on aegis

**Comment by aleos89** [comment]
I've found it was broken with #5264. AoE type skills don't trigger `battle_delay_damage` which is resulting in these types of skills not activating mobs with `MSC_CLOSEDATTACKED` and `MSC_LONGRANGEATTACKED` skill conditions.
