### ISSUE TITLE
Missing script command open_navigation_ui

### ISSUE THREAD

**Issue by Haydrich** [rathena/rathena#7142]
• rAthena Hash: https://github.com/rathena/rathena/commit/84d295e78431815fd823687c897ec0f180542085
• Client Date: 20211117
• Server Mode: re
• Description of the Issue:
           a missing script command to force open the navigation UI for the attached player.
• **Modifications that may affect results:**
![Honeycam 2022-07-27 19-35-43](https://user-images.githubusercontent.com/54556365/181313191-5972311e-b0b5-4e57-8a5b-37ee22e868e2.gif)

**Comment by aleos89** [comment]
Isn't this just `*navigateto("<map>"{,<x>,<y>,<flag>,<hide_window>,<monster_id>,<char_id>});`?

**Comment by Haydrich** [comment]
> Isn't this just `*navigateto("<map>"{,<x>,<y>,<flag>,<hide_window>,<monster_id>,<char_id>});`?

Yea you are right, my bad.
