### ISSUE TITLE
Set Bonus (WoE Set) - Is not given the correct bonus.

### ISSUE THREAD

**Issue by tmav94** [rathena/rathena#715]
Check this, please...

Set bonus with WoE Greave [1], WoE Plate [1]:
Vit +5
Reduces damage from players by an additional 15%
nao ta dando os vit+5

Server: Renewal

**Comment by officialronode** [comment]
WoE Greave + WoE Plate + WoE Manteau 

This should work fine. Already tried. Please note that the stats will work on WOE / PVP maps

**Comment by nanakiwurtz** [comment]
Item ID?

**Comment by officialronode** [comment]
Item ID's
2483 = Siege Greaves
2586 = Siege Manteau
15046 = Siege Plate

**Comment by aleos89** [comment]
As @officialronode stated, items flagged in item_noequip will no longer remove items. As per official, you can still wear the equipment, it just won't give the item bonus (if it has any). Siege Equip is restricted on normal maps, thus you need to be in a GvG or PvP map to see the stat bonuses.
