### ISSUE TITLE
Bard/Dancer After Song Effect Bug

### ISSUE THREAD

**Issue by AmnaeL1995** [rathena/rathena#7163]
I have problem with Big Red Ball Aura after use any songs... In Old rathena's no problem, But in last Rathena i have this bug
![photo_2022-08-02_23-42-36](https://user-images.githubusercontent.com/110550586/182640741-01d4b0ea-dc06-4102-9343-f0ca69bf6390.jpg)
How i can fix it, Or disable, Or Delete... I can't find where is this aura / effect ... 
![photo_2022-08-02_23-42-36](https://user-images.githubusercontent.com/110550586/182640913-3f9d8149-5543-4e77-a950-3b0f497ba951.jpg)

**Comment by Melk3000** [comment]
Same problem. How i can fix it, or disable, or Delete?
