### ISSUE TITLE
Group_db.yml change

### ISSUE THREAD

**Issue by LadyNanuia** [rathena/rathena#7167]
**Is your request related to a missing feature?** No

**Describe the solution you'd like** Make it so you can use ID's as well as  Item names in Group_Db.yml

 Example
instead of
          - Item: Bottle_To_Throw
            Rate: 1
youd be able to write as well
          - Item: 6297 (the ID)
            Rate: 1

**Describe alternatives you've considered**

**Additional context**

**Comment by Lemongrass3110** [comment]
I am not really a friend of this as this is what we decided to use for all YAML files.

**Comment by Balferian** [comment]
As the suggestion:
I was add function to my server
> bool is_digits(const std::string &str) {
	return str.find_first_not_of("0123456789") == std::string::npos;
}

and read both variants (aegis name or id) from db
before:
> std::shared_ptr<item_data> id = item_db.search_aegisname( name.c_str() );

after:
> std::shared_ptr<item_data> id = is_digits(name.c_str()) ? item_db.find(atoi(name.c_str())) : item_db.search_aegisname(name.c_str());

**Comment by LadyNanuia** [comment]
> I am not really a friend of this as this is what we decided to use for all YAML files.

well i mean i know that you guys make the "rules" but i figured id throw in the suggestion as it would make life easier, at least for myself and a few other people i know but its a no its a no, i just figured asking doesnt hurt :)

**Comment by LadyNanuia** [comment]
> As the suggestion: I was add function to my server
> 
> > bool is_digits(const std::string &str) {
> > return str.find_first_not_of("0123456789") == std::string::npos;
> > }
> 
> and read both variants (aegis name or id) from db before:
> 
> > std::shared_ptr<item_data> id = item_db.search_aegisname( name.c_str() );
> 
> after:
> 
> > std::shared_ptr<item_data> id = is_digits(name.c_str()) ? item_db.find(atoi(name.c_str())) : item_db.search_aegisname(name.c_str());
> 
> The same i use for mobs. Of course better to read aegis name, but for me more useful to use id, because aegis names can be changed.

i will try yours, thank you!
