### ISSUE TITLE
Bad error message when parsing files

### ISSUE THREAD

**Issue by anelson-86** [rathena/rathena#7171]
* **rAthena Hash**: df3d7d4bd10bcb0a8e14b3c9a66dd8233c00e082

* **Client Date**: N/A
* **Server Mode**: Renewal

* **Description of Issue**: A single quote in the YML file for `/conf/groups.yml` causes the server to crash with an unspecified open quote error.
  * Result: Server crashes with the following error when a Quote is introduced

` [Status]: Done reading '250' entries in 'db/re/statpoint.yml'`
` [Status]: Done reading '1' entries in 'conf/motd.txt'.`
` [Status]: Done reading '0' entries in 'db/re/attendance.yml'`
`   terminate called after throwing an instance of 'std::runtime_error'`
`   what():  ERROR: reached end of file looking for closing quote`
` `
`:       0002`
`State:  R (running)`
`Tgid:   19770`
`Ngid:   0`
`Pid:    19770`
`PPid:   1`
`TracerPid:      0`
`Uid:    1000    1000    1000    1000`
`Gid:    1000    1000    1000    1000`
`FDSize: 256`
`Groups: 1000`
`NStgid: 19770`
`NSpid:  19770`
`NSpgid: 19764`
`NSsid:  7737`
`VmPeak:   397548 kB`
`VmSize:   376172 kB`
`VmLck:         0 kB`
`VmPin:         0 kB`
`VmHWM:    353132 kB`
`VmRSS:    332188 kB`
`RssAnon:          322300 kB`
`RssFile:            9888 kB`
`RssShmem:              0 kB`
`VmData:   337072 kB`
`VmStk:       272 kB`
`VmExe:      4540 kB`
`VmLib:      9400 kB`
`VmPTE:       748 kB`
`VmSwap:        0 kB`
`HugetlbPages:          0 kB`
`CoreDumping:    0`
`Threads:        1`
`SigQ:   0/14422`
`SigPnd: 0000000000000000`
`ShdPnd: 0000000000000000`
`SigBlk: 0000000000000000`
`SigIgn: 0000000000001004`
`SigCgt: 0000000181004482`
`CapInh: 0000000000000000`
`CapPrm: 0000000000000000`
`CapEff: 0000000000000000`
`CapBnd: 0000003fffffffff`
` `
`CapAmb: 0000000000000000`
`NoNewPrivs:     0`
`Seccomp:        0`
`Speculation_Store_Bypass:       vulnerable`
`Cpus_allowed:   ff`
`Cpus_allowed_list:      0-7`
`Mems_allowed:   00000000,00000000,00000000,00000000,0000000`

  * Expected Result: the status message showing the file it is parsing before stating done such as the following:

`[Status]: Opening 'db/re/statpoint.yml'`
`[Status]: Done reading '250' entries in 'db/re/statpoint.yml'`
`[Status]: Opening 'conf/motd.txt'`
`[Status]: Done reading '1' entries in 'conf/motd.txt'.`
`[Status]: Opening 'db/re/attendance.yml'`
`[Status]: Done reading '0' entries in 'db/re/attendance.yml'`

  * How to Reproduce: Toss a single quote into the Groups.yml file This may affect other files

**Comment by aleos89** [comment]
This is a partial limitation to the ryml parser.
