### ISSUE TITLE
Incorrect Max. Inventory Size Displayed

### ISSUE THREAD

**Issue by ChingChuan-Chen** [rathena/rathena#7173]
* **rAthena Hash**: 
365439943a76f23a450ec4649b8d0f333973c9ff

* **Client Date**: 
`* 2020-04-01

* **Server Mode**: 
* Renewal

* **Description of Issue**: 
  * Result: 

I am trying to add the value of `INVENTORY_BASE_SIZE`, but I found out that it will cause some abnormal displaying problem in the game.

* When I set 200, the max inventory in the game will become 0.
* When I set 250, the max inventory in the game will become -50.
* When I set a value exceeding 250, I can't enter the game. Limitation is 255, right?

  * Expected Result: 

* The max inventory in the game should be the same value when no expansion.

  * How to Reproduce: 

Just set `INVENTORY_BASE_SIZE` as a non-100 value, and you will see the abnormal displaying.

  * Official Information: 
  

* **Modifications that may affect results**: 
  
  

I thought we may import a new variable called `INVENTORY_FIXED_SIZE` with value 100.
And change the function, `clif_inventory_expansion_info` as the following:

~~`p.expansionSize = sd->status.inventory_slots - INVENTORY_BASE_SIZE;`~~
`p.expansionSize = sd->status.inventory_slots - INVENTORY_FIXED_SIZE;`

I thought that this is caused by the default RO processing on displaying the max inventory.

Plus, I also did another experiment. When I changed the code as described above. 
When I set `INVENTORY_BASE_SIZE` as 250, it still couldn't show 250 as the max inventory, it would show 100 instead. It seems to be a displaying limitation to `200`.

**Comment by ChingChuan-Chen** [comment]
I noticed that there is an option in the client that is able to change the inventory size. Is this related to this setting?

**Comment by null6385** [comment]
Yes, I tested it a long time ago, it can only do 255 inventory slots.

**Comment by vstumpf** [comment]
I think you need to keep INVENTORY_BASE_SIZE to 100, but you can change the default of `char`.`inventory_slots` to 200 https://github.com/rathena/rathena/blob/ae74eb840480d358c8250d35bd9d28c097794e28/sql-files/main.sql#L284

This way, the server thinks the base inventory is still 100, but because everyone has 200 slots, the extra 100 slots are due to the expanded inventory.

**Comment by null6385** [comment]
> I think you need to keep INVENTORY_BASE_SIZE to 100, but you can change the default of `char`.`inventory_slots` to 200
> 
> https://github.com/rathena/rathena/blob/ae74eb840480d358c8250d35bd9d28c097794e28/sql-files/main.sql#L284
> 
> This way, the server thinks the base inventory is still 100, but because everyone has 200 slots, the extra 100 slots are due to the expanded inventory.

Thanks, I'll just do a new test.

**Comment by aleos89** [comment]
So as @vstumpf stated, you can't adjust the base size as it's limited to 100 by the client. You need to adjust the SQL `char` table "inventory_slots".
