### ISSUE TITLE
Inconsistent delay between auto-attack target changes

### ISSUE THREAD

**Issue by MiYanni** [rathena/rathena#7178]
### Info:
- **rAthena Hash**: N/A
- **Client Date**: N/A
- **Server Mode**: N/A
- **Description of Issue**: 
  - Result: Inconsistent beginning of auto-attack when attacking one mob to the next.
  - Expected Result: Consistent rate of attacking when changing targets while auto-attacking.
  - How to Reproduce: I'm using a Rebellion with >180 ASPD and tried both pistols and gatling guns.
  - Official Information: N/A
- **Modifications that may affect results**: 
  - Unlocked FPS (> 60)

### Description
I'm playing on a server that (I believe) is rAthena-based. It is NovaRO. The long and short of it is, sometimes, I will almost insta-attack the next target when using an AA build for Gunslinger/Rebellion. It seems the game is designed that there is an intended delay when switching between targets. Otherwise, you could kill the entire screen with a ranged character by simply clicking on each enemy using a high damage, high ASPD build. It seems this delay is independent of ASPD. I don't know if this is some kind of anti-botting prevention but it seems to be quite a long delay in my testing.

On the server I'm playing on, I have between 75-80ms with the server. It doesn't seem to be a latency issue. What happens is clicking between different targets will randomly kill the first and the next without the normal delay when target switching. I just wanted to make this issue to see if this is something others have experienced using rAthena or if this is something potentially built into the server/client of NovaRO. Thanks!

Additionally, is this delay between targets something that can be adjusted? Just wondering from a developer standpoint.

**Comment by Playtester** [comment]
Pretty sure this delay is client-sided. On server-side there's just ASPD delay. It's just that the client doesn't even bother sending attack commands while busy auto attacking. Not sure what effects it, but usually moving a cell allows you to switch targets.

**Comment by MiYanni** [comment]
@Playtester I think you're right about it being client-sided. Over the weekend, I tested some things. Switching targets felt more responsive when each target required many attacks to kill. However, if I 1-shot a target, it seems to introduce a delay between 'leaving off' the dead target and auto-attacking a new target. But even that isn't consistent; sometimes it would 'insta-switch' to the new target as soon as the new target is selected, almost like I hit some kind of update tick at the right frame, so the client instantly sends the new target to the server. If this can be figured out, auto-attacking in the game would feel significantly more responsive as you could start/stop attacking targets without such delays.
