### ISSUE TITLE
bAddRace bug?

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#718]
Hello good evening, I was doing some tests, and I believe the bonus damage to humanoids is with the incorrect formula, see the sample using an item with the following script:

bonus2 bAddRace, RC_DemiHuman, 20; bonus2 bAddRace, RC_Player, 20;

Without armor: http://i.imgur.com/n0XduND.png

With armor: http://i.imgur.com/iEjgDPv.png

I believe it is a bit wrong ...

**Comment by Barigas** [comment]
How much is the atk of the weapon that you are using? Because status atk is not affected by cards in renewal, only equip one. Post your stats screen info plz.

**Comment by admkakaroto** [comment]
Look:

Without card with damage script humanoids
http://i.imgur.com/gaREAXq.jpg

With the equipped card
http://i.imgur.com/rssskIO.jpg

As you can see, the difference is very little to be 20%.

**Comment by Barigas** [comment]
Everything is correct. Read my post and this again: http://irowiki.org/wiki/Atk
In renewal, all race/size and other % cards affect only the equipment part of atk. So, in your case it is 17 equip atk(pluss some % bonus from str), 1.7*1.2=3damage that is what you see on your. Status atk(which comes from str, base lvl and so on) is not affected by any cards. So, your 195 status atk is not affected by it.

**Comment by aleos89** [comment]
As @Barigas stated, this was actually tested recently again. It is confirmed that this is intended behavior of the `bonus bAddRace` / `bonus bAddClass`.
