### ISSUE TITLE
Tools for @item2 generation?

### ISSUE THREAD

**Issue by Takiusu** [rathena/rathena#7182]
I think it would be a good idea to make tool that can help you to generate commands for item creating from zero instead of writing long command @item2 with a lot of options such as item ID, quanity, refine, card1, card2, card3 and etc. For example, in this tool you can choose any item, his refine, cards and enchants from the list and according to this you will get ready-made command @item2.

**Comment by Atemo** [comment]
The idea is good, but I'm closing this issue since there is no concrete suggestion. Do not hesitate to re-post if you have concrete and realistic ideas.
