### ISSUE TITLE
**Client used:** 2021-01-07aRagexeRE

### ISSUE THREAD

**Issue by gravity-ro** [rathena/rathena#7188]
**Client used:** 2021-01-07aRagexeRE
Missing MerchantStore information when triggering the "IMPORT" button on the vending interface. This is supposed to restore your last vending store items and prices.
`[Info]: *.*.*.* [POST /MerchantStore/load] 404`
![image](https://user-images.githubusercontent.com/12261601/120490019-5ad15880-c3b8-11eb-8708-e9e06476d1ea.png)

Missing Adventurer's Agency List information when opening the Adventurer's Agency Interface.
Triggering the Search button also looks for the search folder.
`[Info]: *.*.*.* [POST /party/list] 404`
`[Info]: *.*.*.* [POST /party/search] 404`
![image](https://user-images.githubusercontent.com/12261601/120492000-fdd6a200-c3b9-11eb-8b9d-88014260f24b.png)

_Originally posted by @Everade in https://github.com/rathena/rathena/issues/5731#issuecomment-853043746_

It's still error
http://image.free.in.th/v/2013/iw/220816084418.png

**Comment by Pokye** [comment]
Merchant Store has already been implemented in Web Services. it's functional. https://github.com/rathena/rathena/pull/5731/commits/e46c6c5d08c684d270168f40d8ccc1a130425da6
Adventure Agency has not yet been implemented in rA, so disregard this.
