### ISSUE TITLE
whats going on with the halter lead item?

### ISSUE THREAD

**Issue by joelolopez** [rathena/rathena#719]
im using 2013-08-07aRagexe , and clean rathena, no midifications applied. the problem is when i use the halter lead item it shows a message in my public log says content has been saved in [SaveData_ExMacro2] this will show 8 times as you try to unride your mount beast and then after that the mount is off. why am i receiving this messages? its suppose to say "NOTICE: if you crash with mount your LUA is outdated". @mount2 is working properly but the halter lead item is not.

**Comment by zackdreaver** [comment]
You need the right msgstringtable.txt for your client date

**Comment by joelolopez** [comment]
yeah your right dude, issue must be close , ignore this report
