### ISSUE TITLE
Marketshop not reloaded after server restart

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#7191]
* **rAthena Hash**: 9759909f82c94d66b9f273cd0593e12088df7c99

* **Client Date**: 20211103

* **Server Mode**: RE

* **Description of Issue**: 
  * Result: marketshop not reloaded after server restart, so we need reloadnpcfile to reloaded the marketshop
  * Expected Result: marketshop must reloaded after server restart wihtout reloadnpcfile
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Is this related to #6889? Can you give an example of which shops you are trying to test this against?

**Comment by mazvi** [comment]
Before this update https://github.com/rathena/rathena/commit/798e09e8c99f67070810d6edf7d636272afc83d1

You can try buy item, then restart server

then check item again

the number of items does not reload, when the server is restarted

even when you change the price it doesn't change, unless you reloadnpcfile.

Marketshop should also be reloaded when restarting the server.

**Comment by Atemo** [comment]
Maybe you mean the marketshop in rockridge should be updated on server restart? Or are you talking about the whole marketshop system? Because the shop is only updated when we set it, the shop in rockridge is only supplied on Sundays at 00:00

**Comment by mazvi** [comment]
> Maybe you mean the marketshop in rockridge should be updated on server restart? Or are you talking about the whole marketshop system? Because the shop is only updated when we set it, the shop in rockridge is only supplied on Sundays at 00:00

whole.. it just example enchan_rockridge.txt..

marketshop must be reloaded after server restart. like reload NPC after server restart.

**Comment by mazvi** [comment]
I have another example.

When the price of your item changes in item_db

then the price on the marketshop does not change when the server is restarted.

you have to reloadnpcfile to change the price

the price in the marketshop should automatically adjust to item_db when the server restarts
