### ISSUE TITLE
Suggestions for webservice database split configuration

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#7192]
**Is your request related to a missing feature?** NO

**Describe the solution you'd like**
This is just a suggestion, considering the emblems are stored in the database. Splitting the database can suppress the main database from storing many BLOB files.

Like logs, databases can be separate from the main database.

I hope the webservice can use a separate database from the main database, so that the main database is more efficient.

**Describe alternatives you've considered**

**Additional context**

**Comment by Lemongrass3110** [comment]
Not an emulator problem. MySQL has enough options to set it up accordingly.

**Comment by mazvi** [comment]
yes this is not issue, the type this is enhancement only suggestion
