### ISSUE TITLE
show debug message every time login game

### ISSUE THREAD

**Issue by idk-whoami** [rathena/rathena#7194]
* **rAthena Hash**: ae74eb840480d358c8250d35bd9d28c097794e28

* **Client Date**: 20211103

* **Server Mode**: re

* **Description of Issue**: 
```
every time login game
show debug message
```

![บันทึก_2022_08_19_22_16_50_504](https://user-images.githubusercontent.com/60462533/185652743-bdc0af56-e45d-41dd-9030-e42516d7cad8.gif)

```
[Debug]: [AccountID: 2000001, CharID: 150001, World: "rAthena"] Not found in table, sending new info.
```
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by mazvi** [comment]
Are you runing web-server or not? related webservice? 

https://github.com/rathena/rathena/commit/0ac52d0bb49e858f7ff7774685bb0d18af6d1cf7

**Comment by idk-whoami** [comment]
how to run web-server 0ac52d0bb49e858f7ff7774685bb0d18af6d1cf7

**Comment by idk-whoami** [comment]
forgot to add description

run server on Ubuntu 21.04 machine

**Comment by idk-whoami** [comment]
guild emblems works normally


![บันทึก_2022_08_20_21_43_38_485](https://user-images.githubusercontent.com/60462533/185752193-f24897fc-6858-440f-ad9c-22e44d15b989.gif)

```
[Debug]: [AccountID: 2000000, CharID: 150000, World: "rAthena"] Not found in table, sending new info.

**Comment by Akkarinage** [comment]
I'm unsure on why it does this, as I get it to.

As a temporary measure, you can use the `console_silent: ` option to hide the debug messages.

*config/import/web_conf.txt*
```
console_silent: 32
```

**Comment by aleos89** [comment]
Maybe @vstumpf can provide some insight since it's his baby.

**Comment by vstumpf** [comment]
I guess we can remove the log message.
For some reason the client isn't sending a save request when the client closes, so nothing ever gets added to the db
