### ISSUE TITLE
"spawn_direction = yes" is not applied when logging in

### ISSUE THREAD

**Issue by SapitoSucio** [rathena/rathena#7195]
* **rAthena Hash**: 
Latest
* **Client Date**: 

20211103

* **Server Mode**: 

Renewal

* **Description of Issue**: 
  * Result: "spawn_direction =yes" is not respected when logging in
  * Expected Result: Character's last facing direction should be respected when  a player teleports, changes maps, or **logs in**
  * How to Reproduce: Set "spawn_direction: yes", reloadbattleconf, try facing south, disconnecting and reconnecting.
  * Official Information: 
  

* **Modifications that may affect results**: 
  
  

https://user-images.githubusercontent.com/7357354/185729757-4ed642c4-ab10-4f25-bb7e-9c65aba0f4c9.mp4

**Comment by aleos89** [comment]
The reason behind this is because when the player logs in, the view direction data is empty/0 which is North. From what I can see we don't save the view direction of players.
