### ISSUE TITLE
Official MaxHP and SP

### ISSUE THREAD

**Issue by eppc0330** [rathena/rathena#7196]
* **rAthena Hash**: master

* **Client Date**: 20211117

* **Server Mode**: Renewal

* **Description of Issue**: 
  * Result: Character's base MaxHP and SP are different from ones of official KRo. 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information: 
   This is Shadow cross' max HP and SP at 244Lv from KRo
   ![KRo](https://user-images.githubusercontent.com/47050704/185763394-03101a77-dd90-4701-8df9-d4ba7fd7a118.png)

    And this is from rA
    ![rA](https://user-images.githubusercontent.com/47050704/185763436-18de1ae2-f7d6-45d7-baf9-fcf956cc2dbd.png)

    It shows quite big difference. 
    According to one of my Korean friend, rA's HP & SP are different after level 170 with irregular intervals.
  
  

* **Modifications that may affect results**:

**Comment by Balferian** [comment]
The same issue: https://github.com/rathena/rathena/issues/6427

**Comment by eppc0330** [comment]
@Balferian Sorry
