### ISSUE TITLE
Trap Behavior mod on linux based OS (Compiler Issue)

### ISSUE THREAD

**Issue by gidzdlcrz** [rathena/rathena#7197]
* **rAthena Hash**: Latest

* **Client Date**: 2015, 2018 & 2020

* **Server Mode**: PRE RE

* **Description of Issue**:  My trap mod behavior using windows doesnt have problems. But on my VPS running Debian 10 it does have problem. I have other ways to make it work but i prefer editing the skill.c instead.
  * Result:  Skill will fail always
  * Expected Result:  It should work as my local does
  * How to Reproduce:  On your skill.cpp. You will add some restriction to some skills when affected by Ankle Snare, Close Confine, Spider Web and etc etc. By doing the FF:
```
   		case WM_SATURDAY_NIGHT_FEVER:
			if( !mapdata_flag_vs(mapdata) ) {
				clif_skill_teleportmessage(sd,2); // This skill uses this msg instead of skill fails.
				return true;
			}
			break;
+		// Trap No Escape [Gidz]
+		case MO_BODYRELOCATION:
+		case NJ_SHADOWJUMP:
+		case TF_BACKSLIDING:
+			if( sd && ( sd->sc.data[RG_CLOSECONFINE] || sd->sc.data[SC_ANKLE] || sd->sc.data[SC_SPIDERWEB] || sd->sc.data[SC_THORNSTRAP] || sd->sc.data[SC_VACUUM_EXTREME] ) ) { 
+				clif_skill_fail(sd,skill_id,USESKILL_FAIL_LEVEL,0);
+				return true;
+			}
+			break;
```
 By doing this. Your declared skill will fail. MO_BODYRELOCATION, NJ_SHADOWJUMP and TF_BACKSLIDING works. But when i add like KN_CHARGEATK, TK_HIGHJUMP and etc etc it will not work.
 * Official Information:  Nah. This is modded  behavior. Its just compiler issue.
  

* **Modifications that may affect results**:  N/A. This is like my other report regarding compiling issue. https://github.com/rathena/rathena/issues/4909.

**Comment by vstumpf** [comment]
Are you sure your `skill_trap_type` is set the same on both?
https://github.com/rathena/rathena/blob/798e09e8c99f67070810d6edf7d636272afc83d1/conf/battle/skill.conf#L302-L311

this doesn't seem like a compiler issue at all

**Comment by gidzdlcrz** [comment]
> Are you sure your `skill_trap_type` is set the same on both?
> 
> https://github.com/rathena/rathena/blob/798e09e8c99f67070810d6edf7d636272afc83d1/conf/battle/skill.conf#L302-L311
> 
> this doesn't seem like a compiler issue at all

I think this has nothing to do with that. The mod will simply restrict the selected skills when you are on anklesnare, spider web etc etc.


Lets add KN_CHARGEATK to this mod.
```
   	case WM_SATURDAY_NIGHT_FEVER:
		if( !mapdata_flag_vs(mapdata) ) {
			clif_skill_teleportmessage(sd,2); // This skill uses this msg instead of skill fails.
			return true;
		}
		break;
+		// Trap No Escape [Gidz]
+		// Trap No Escape [Gidz]
+		case KN_CHARGEATK:
+			if( sd && ( sd->sc.data[RG_CLOSECONFINE] || sd->sc.data[SC_ANKLE] || sd->sc.data[SC_SPIDERWEB] || sd->sc.data[SC_THORNSTRAP] || sd->sc.data[SC_VACUUM_EXTREME] ) ) { 
+				clif_skill_fail(sd,skill_id,USESKILL_FAIL_LEVEL,0);
+				return true;
+			}
```
On my local it works. On my VPS the skill always fail.

**Comment by vstumpf** [comment]
you're checking `sd->sc.data[RG_CLOSECONFINE]`, which is not correct. RG_CLOSECONFINE is 1005, which causes an out-of-bounds access on the sc.data array, so who knows what you're accessing.

You probably want to check `sd->sc.data[SC_CLOSECONFINE2]`

**Comment by gidzdlcrz** [comment]
> you're checking `sd->sc.data[RG_CLOSECONFINE]`, which is not correct. RG_CLOSECONFINE is 1005, which causes an out-of-bounds access on the sc.data array, so who knows what you're accessing.
> 
> You probably want to check `sd->sc.data[SC_CLOSECONFINE2]`

Omg. I think it works now. Will conduct more tests for now. Thank you so so much @vstumpf! But its really weird since in my local it works. No compile error for both windows and linux.

Will add additional info later.

**Comment by gidzdlcrz** [comment]
Yep! I think it works now. Thank you so so much @vstumpf !
