### ISSUE TITLE
Alchemist Demonstration skill and Garm card

### ISSUE THREAD

**Issue by joelolopez** [rathena/rathena#720]
my character freeze when im get hit by my own demonstration on the ground. it seems that the status ailment effect that garm card posses causes my character to freeze. (no other equipments but garm card in the jacket) is it behaving normally? if not , someone should fix this, it causes a big trouble in pvp especially for the caster of the skill xp

**Comment by aleos89** [comment]
Garm gives the bonus of causing a chance to freeze at 50% from physical attacks. In renewal, Acid Demonstration is a physical attack, thus causing you to freeze.

**Comment by joelolopez** [comment]
sir aleos demonstration only (skill that only uses bottle grenade), not acid demonstration. when i get hit by my own demonstration the garm effect that im wearing causes my character to freeze

how to produce:

-wear jacket with garm card
-use demonstration on the ground
-walk on to the demonstration's flame
-your character will get freeze

is it suppose to be like this? if not , please fix this

**Comment by MrAntares** [comment]
If you can damage yourself with the skill, yes it is intended.

**Comment by RagnarokNova** [comment]
Confirmed unintended. 
http://i.imgur.com/vHq0Uxh.png

Tested the same Garm Card against monsters in the same map and they froze immediately, I stood and took about 20+ hits from my own Demonstration and never froze.
