### ISSUE TITLE
Endows aren't removed when unequipping weapon and stay when dead

### ISSUE THREAD

**Issue by Singe-Horizontal** [rathena/rathena#7215]
* **rAthena Hash**: 
N/A

* **Client Date**: 
N/A

* **Server Mode**: 
Both

* **Description of Issue**: 
Endows stay when dead and aren't removed when switching weapon

**Comment by Akkarinage** [comment]
Ensure the Issue template is filled out correctly, whether the Issue applies to a specific client or not.

**Comment by Singe-Horizontal** [comment]
I mistakenly wrote Latest instead of N/A
