### ISSUE TITLE
SQL Itens - map-server received signal SIGABRT, Aborted

### ISSUE THREAD

**Issue by mplaten** [rathena/rathena#7229]
* **rAthena Hash**: 

6cb5b5bac

* **Client Date**: 

No
* **Server Mode**: 

Boths
* **Description of Issue**:  map-server can't read sql itens
gdb bt full:

terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi

Program received signal SIGABRT, Aborted.
__pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
44      ./nptl/pthread_kill.c: No such file or directory.
(gdb) bt full
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
        tid = <optimized out>
        ret = 0
        pd = <optimized out>
        old_mask = {__val = {5104530931433711337, 936214231047856378, 1, 13979173243358019584, 579005069656919567, 283686952306183,        
            7462441432916684163, 53, 0, 0, 1, 13979173243358019584, 579005069656919567, 283686952306183, 2, 9223372036854775814}}
        ret = <optimized out>
#1  0x00007ffff740389f in __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
No locals.
#2  0x00007ffff73b7a52 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
        ret = <optimized out>
--Type <RET> for more, q to quit, c to continue without paging--c
#3  0x00007ffff73a2469 in __GI_abort () at ./stdlib/abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0xd68, sa_sigaction = 0xd68}, sa_mask = {__val = {140737341524790, 140737343051392, 140737341527957, 140737343051392, 140737343051392, 140737343051523, 140737343034848, 3432, 140737341524790, 11, 1, 140737343051392, 93825056723056, 10, 0, 140737341275504}}, sa_flags = -146823191, sa_restorer = 0x55555748f3f8}
        sigs = {__val = {32, 0, 0, 0, 2, 9223372036854775814, 21, 116, 140737344844736, 140737341527957, 0, 140737341527957, 140737345824711, 140737343051392, 93825024979960, 140737343034848}}
#4  0x00007ffff7715909 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#5  0x00007ffff7720f2a in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#6  0x00007ffff7720f95 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#7  0x00007ffff77211e8 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#8  0x00007ffff771818a in std::__throw_invalid_argument(char const*) () from /lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#9  0x000055555567f055 in __gnu_cxx::__stoa<long, int, char, int> (__convf=0x7ffff73bbd70 <__strtol>, __name=__name@entry=0x5555558f21e9 "stoi", __str=0x5555592fe1a0 "percentheal 10,10;", __idx=__idx@entry=0x0) at /usr/include/c++/12/ext/string_conversions.h:83
        __ret = <optimized out>
        __endptr = 0x5555592fe1a0 "percentheal 10,10;"
        __save_errno = <optimized out>
        __tmp = <optimized out>
#10 0x000055555566d60c in std::__cxx11::stoi (__base=10, __idx=0x0, __str=...) at /usr/include/c++/12/bits/basic_string.h:3971
No locals.
#11 itemdb_read_sqldb_sub (str=std::vector of length 111, capacity 111 = {...}) at itemdb.cpp:3195
        tree = {m_buf = 0x5555593325f0, m_cap = 16, m_size = 14, m_free_head = 14, m_free_tail = 15, m_arena = {str = 0x55555932ff90 "500Choko_GangjeongChoko GangjeongHealing10", len = 64}, m_arena_pos = 42, m_callbacks = {m_user_data = 0x0, m_allocate = 0x5555558ac2e0 <c4::yml::allocate_impl(unsigned long, void*, void*)>, m_free = 0x5555558ac1a0 <c4::yml::free_impl(void*, unsigned long, void*)>, m_error = 0x555555585fec <on_yaml_error(char const*, unsigned long, c4::yml::Location, void*)>}, m_tag_directives = {{handle = {str = 0x0, len = 0}, prefix 
= {str = 0x0, len = 0}, next_node_id = 511101108348}, {handle = {str = 0x0, len = 0}, prefix = {str = 0x0, len = 0}, next_node_id = 0}, {handle = {str = 0x0, len = 0}, prefix = {str = 0x0, len = 0}, next_node_id = 3552}, {handle = {str = 0x0, len = 0}, prefix = {str = 0x0, len 
= 0}, next_node_id = 140737344837276}}}
        rootNode = {m_tree = 0x7fffffffdec0, m_id = 0, m_seed = {str = 0x0, len = 18446744073709551615}}
        index = 98
        jobs = {m_tree = 0x7fffffffdec0, m_id = 6, m_seed = {str = 0x0, len = 18446744073709551615}}
        classes = {m_tree = 0x7fffffffdec0, m_id = 7, m_seed = {str = 0x0, len = 18446744073709551615}}
        locations = {m_tree = 0x7fffffffdec0, m_id = 8, m_seed = {str = 0x0, len = 18446744073709551615}}
        flags = {m_tree = 0x7fffffffdec0, m_id = 9, m_seed = {str = 0x0, len = 18446744073709551615}}
        delay = {m_tree = 0x7fffffffdec0, m_id = 10, m_seed = {str = 0x0, len = 18446744073709551615}}
        stack = {m_tree = 0x7fffffffdec0, m_id = 11, m_seed = {str = 0x0, len = 18446744073709551615}}
        nouse = {m_tree = 0x7fffffffdec0, m_id = 12, m_seed = {str = 0x0, len = 18446744073709551615}}
        trade = {m_tree = 0x7fffffffdec0, m_id = 13, m_seed = {str = 0x0, len = 18446744073709551615}}
#12 0x00005555556707d7 in itemdb_read_sqldb () at itemdb.cpp:3308
        data = std::vector of length 111, capacity 128 = {"500", "Choko_Gangjeong", "Choko Gangjeong", "Healing", "", "", "", "10", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "percentheal 10,10;", "", "", "", "", "", "", "", "", "", "", "", ""}
        total_columns = <optimized out>
        total_rows = <optimized out>
        rows = <optimized out>
        count = <optimized out>
        fi = <optimized out>
        item_db_name = {0x5555559e6880 <item_table> "item_db_re", 0x5555559e6860 <item2_table> "item_db2_re"}
        item_db_name = <optimized out>
        fi = <optimized out>
        total_columns = <optimized out>
        total_rows = <optimized out>
        rows = <optimized out>
        count = <optimized out>
        data = <optimized out>
        i = <optimized out>
        str = <optimized out>
#13 itemdb_read () at itemdb.cpp:3746
        i = <optimized out>
        dbsubpath = {0x55555594ba8e "", 0x5555558ea1e2 "/import"}
        __FUNCTION__ = "itemdb_read"
#14 0x0000555555699238 in do_init (argc=argc@entry=1, argv=argv@entry=0x7fffffffe258) at map.cpp:5215
        __FUNCTION__ = "do_init"
#15 0x000055555558e132 in main (argc=1, argv=0x7fffffffe258) at core.cpp:377
No locals.
(gdb)

  * Result: 
  * Expected Result:  Shoul'd be able to start...
  * How to Reproduce:  just set 'use_sql_itens' and start server
  * Official Information: 
  

* **Modifications that may affect results**: 
  
  
No one; clean rathena

**Comment by secretdataz** [comment]
Cannot reproduce on 6cb5b5b.
