### ISSUE TITLE
Spear Mastery 

### ISSUE THREAD

**Issue by zaido78** [rathena/rathena#723]
Hello i just want to report Spear master is not working.. 

Description: Increase damage with Spears
dpende on the Level of skill but when i equip spear nothing happen

**Comment by anacondaqq** [comment]
@zaido78 
Please, provide extra info

1.) Your current revision of rAthena
2.) Do you have source mods, or nope?
3.) What mechanic of your emulator? (pre-re / renewal)?
4.) Client date?
5.) Packet version.
6.) How reproduce this bug step by step + screenshots or video? 


All of this information make developers & testers life much easier. rAthena is free emulator, and nobody will do extra move. So Dear Zaido, provide more information.

**Comment by MrAntares** [comment]
I tested it, it is working fine. I can clearly see the bonus in both basic and skill attacks.
