### ISSUE TITLE
Royal Guard Robe 2 missing

### ISSUE THREAD

**Issue by kaninhot004** [rathena/rathena#7234]
* **rAthena Hash**: 6542df071

* **Server Mode**: Renewal

* **Description of Issue**: 

![Robe](https://user-images.githubusercontent.com/9493525/188270467-3f4ff343-a421-4703-9a4f-1a442cfdd2da.JPG)

  * Result: 1 Item missing from item_combo
  * Expected Result: Add 1 missing item
  * How to Reproduce: -
  * Official Information: -

* **Modifications that may affect results**: -

**Comment by Atemo** [comment]
`Royalguard_Robe2` is an enchant (card) search in etc
