### ISSUE TITLE
SC_POEMBRAGI The state is not lost after death

### ISSUE THREAD

**Issue by cold-hr** [rathena/rathena#724]
When pressed skill A Poem of bragi give to the party.
And the party has died down, but the state bragi not lost.

**Comment by anacondaqq** [comment]
i can confirm that. And not only this spell, all Clowns / Gypsy spells have the same.
This is old bug (maybe ~ 2 years, or more).
This bug related for all revisions up to current (https://github.com/rathena/rathena/commit/ea497b2938e51a526438f78aa6fc4de43af5cc23).

How reproduce:
1. You need somehow to make possible to see "status" from dance songs (visual icons, or i dunno(i'm using extended status icons at my server, and i see it)
2. Cast spells, recieve status
3. Die
4. -> Status will be on you even if yo dead or resurected again.

**Comment by cold-hr** [comment]
Now, I know that, then fine. But I know how to adjust.

clear_skills_on_death:

**Comment by aleos89** [comment]
To my knowledge, these statuses are not removed on death. Has it changed recently?

**Comment by anacondaqq** [comment]
Dear @aleos89 how can i reproduce it except playing on official server? Is there are any offline versions of for example Aegis? Where we can reduce dev's job with testing?

**Comment by aleos89** [comment]
That's what we need. We need to find out the behavior of the skill on official servers. I'll see what I can dig up later.

**Comment by RagnarokNova** [comment]
Confirmed intended behavior. Tested on Aegis.
I'll post a gif shortly. Bragi (Magic Strings) is supposed to persist through death.

**Comment by aleos89** [comment]
Thanks for clearing that up!
