### ISSUE TITLE
Offertorium & Magnificat

### ISSUE THREAD

**Issue by LadyNanuia** [rathena/rathena#7241]
* **rAthena Hash**:  0d2c3b8a179c826635b02918709e195664026960

* **Client Date**: 2020/09/04

* **Server Mode**:  Renewal

* **Description of Issue**: 
  * Result:  When casting Arch Bishop skill [Offertorium] during magnificat, the skill name pops up over the head but nothing happens
  * Expected Result:  its supposed to cancel out magnificat and apply Offertorium buff
  * How to Reproduce:  Make an arch bishop, get magnificat, cast it, while its up, cast Offertorium skill.
  * Official Information:  Casting offertorium should cancel out magnificat and vice versa
  

* **Modifications that may affect results**:  None as far as i know

**Comment by Akkarinage** [comment]
"Latest" is not a git hash.

**Comment by LadyNanuia** [comment]
> "Latest" is not a git hash.

i apologise, ive put in the hash now.

**Comment by LadyNanuia** [comment]
How exactly do you need more info / user input? its all there.

**Comment by Akkarinage** [comment]
The `status:need more info` label is there because there are no sources cited to explain that this is how the skill works.

I forgot to the remove the `status:need user input` label at the same time as the `missing:revision` label.

**Comment by aleos89** [comment]
I was able to confirm that Offertorium overwrites Magnificat and vice versa.

**Comment by aleos89** [comment]
I added pre-renewal to this, but technically I'm just removing the Fail check from Magnificat and not adding it as End (since we have stopped supporting renewal pieces in pre-renewal databases).
