### ISSUE TITLE
Remove old SQL Upgrade files

### ISSUE THREAD

**Issue by Akkarinage** [rathena/rathena#7244]
I'm aware that in reality someone is going to curse me for this, but there's no legitimate reason for not updating and applying upgrade files as and when they are available.

Perhaps removal of old files that exist in the repo prior to 2022 is reasonable?

**Comment by vstumpf** [comment]
Personally, I'm not a fan of this. Sometimes my (test) servers go months without updating rathena, I'm sure I'm not the only one. 

While we can and should encourage people to update often, I don't think this is a friendly way of doing so.

**Comment by secretdataz** [comment]
IMO, we can do this once. However, moving forward, there should be an automated database upgrade system in place that this should not have to be done again.

**Comment by Akkarinage** [comment]
Users aren't needing files to upgrade anything if they're not updating their files. If files are needed they're still available through previous revisions. Having an automated process would be great, but that doesn't remove old files from the repo.

I think I'm the only person to have deleted upgrade files in the last 10 years... that's a very long time 😂  https://github.com/rathena/rathena/pulls?q=is%3Apr+author%3Aakkarinage+is%3Aclosed+sql+upgrade unsure how we handled them back on svn days. I vaguely recall a document somewhere that one of the devs typed up about a one year retention, but that was never adhered to and the files just continued to sit there doing nothing. I have no desire to trawl back through the commit log for 10yr+ data. 

In the past I kept files for longer (2 years) and another occasion only 6 months of files were kept. Personally, I see no reason to keep them longer than 6 months.

**Comment by secretdataz** [comment]
> Having an automated process would be great, but that doesn't remove old files from the repo.

I don't think removing old files will be required anymore if we were to implement such automated db upgrade system.
But for tidiness' sake, we could move them into a separate folder from automatable upgrades and leave them alone.

**Comment by aleos89** [comment]
I agree with the others opinions. Maybe finalizing an automated SQL patcher will resolve this for us.

**Comment by Akkarinage** [comment]
I'll close this off, as the above linked PR is for an automated system for *applying* the upgrades, not *removing* old ones.
