### ISSUE TITLE
Fox Ears Bell Ribbon client crash when autobonus effect triggers

### ISSUE THREAD

**Issue by jmsngls** [rathena/rathena#7247]
* **rAthena Hash**: 04066e30144bb6f215b25ed1b79e5377

* **Client Date**: 2018-06-21aRE

* **Server Mode**: Pre-Renewal

* **Description of Issue**: Item Id: 18934, Fox Ears Bell Ribbon getting error/client crash when the auto bonus triggers, I recently use this item on my pre renewal server but now I have latest rathena I'm getting this client crash
  * Result: Client Crash without any error showing
  * Expected Result: Working effect Fox Ears Bell Ribbon transform to Moonlight and its bonus effect
  * How to Reproduce: Just wear it and normal attack a dummy/mobs and wait to trigger the autobonus (transforming to moonlight and critical.
  * Official Information: https://ratemyserver.net/index.php?page=re_item_db&item_id=18934
  

* **Modifications that may affect results**:

**Comment by Akkarinage** [comment]
RMS is not a source of information; they use our databases.

Can you provide the error?

If you're using a Renewal Item in Pre-Renewal mode, I assume you copied the db entry properly?

**Comment by jmsngls** [comment]
I already made a new client which not ignore errors but still not showing in chat window or crash log.

Yes I copied the entry from re/item_db_equip to my import/item_db

I tried running my old rathena server and its working well

No error showing:
https://user-images.githubusercontent.com/25322697/188444658-808daf11-854e-4b07-9e5e-59670ca8460c.mp4

Working in my old rathena:
https://user-images.githubusercontent.com/25322697/188446147-67d3d745-958c-4f66-b3a2-cd5b8c146a11.mp4

**Comment by OptimusM** [comment]
@jmsngls any console errors? players around him suffer the crash aswell?
Are u using the same data files for pre re and renewal server? that seems like sprite issue on active transformation, could you try to change the monster id to something like 1002 (poring) and test again? if that works, try using monster id 1814 (event moonlight) in case the last id dont crash.

**Comment by jmsngls** [comment]
@OptimusM none. Yes they crash aswell.
-Yes I use same data files, I tried changing it to poring and crash still occur.
I change the duration of transformation longer and after I crashed and re login my character is still transformed to moonlight and I'm not crashing but if I hit again and the effect triggers it crash.

**Comment by Litro** [comment]
it was *transform and *active_transform script command that cause the crash, I happened chanced upon this few days ago.

**Comment by jmsngls** [comment]
> it was *transform and *active_transform script command that cause the crash, I happened chanced upon this few days ago.

Yes it was the transform, i tried removing it and the effect of item occurs without error.

**Comment by iraciz** [comment]
thank you!
I'm using an emulator from 2022, I was importing some items to pre-re and got this same issue!
but solved thabnks to this report!

![QYDJjn8](https://user-images.githubusercontent.com/15825408/226206055-c5dc0be6-0981-4fb0-b947-f457bd9cb6d6.png)
