### ISSUE TITLE
Adding skills on skill_damage_db.txt are making skills reflect 1 damage

### ISSUE THREAD

**Issue by dev1-juan** [rathena/rathena#7248]
* **rAthena Hash**: 8629c6445a12059e6b96cf07a3e99e4a37e4bbde

* **Client Date**: 2018-06-20eRagexeRE

* **Server Mode**: Pre-Renewal

* **Description of Issue**: 
Adding skills on skill_damage_db.txt are making skills added there reflect 1 damage

  * Result: all skills added on skill_damage_db.txt are reflecting 1 damage
  * Expected Result: it should not have reflect 1 damage when there is no reflect items on the enemy
  * How to Reproduce: add skills on skill_damage_db.txt then hit any enemy. you will receive 1 damage regardless if the enemy have reflect or not
  
* **Modifications that may affect results**: Nothing

* **Solution**: 
Changing rdamage = i64max(rdamage, 1); to rdamage = i64max(rdamage, 0); fixes this issue

https://github.com/rathena/rathena/blob/8629c6445a12059e6b96cf07a3e99e4a37e4bbde/src/map/battle.cpp#L8494

**Comment by aleos89** [comment]
Changing the return value to 0 isn't the correct fix because reflected damage is guaranteed to be at least 1 after all reductions. We need to come up with another solution since this feature is custom.
