### ISSUE TITLE
Flash Combo + Tiger Cannon (nodelay)

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#725]
Currently does not exist in the rA delay after the tiger combo cannon .
By using the Tiger cannon combo and use Flash Combo shura should not see the Tiger in Flash.
Reference: http://irowiki.org/wiki/Flash_Combo

* The first 3 skills are instantly casted one after the other with no known delay, but there is around a 1 second delay between Tiger Cannon and Sky Blow. Even though the first 3 skills autocasted are in the order of a actual combo, the damage of Tiger Cannon will be that of a non-comboed use and this also applies to Sky Blow.

**Comment by anacondaqq** [comment]
Please, provide much more information as you can

1.) revision?
2.) client-date?
3.) pre-re / renewal?
4.) steps how reproduce?

**Comment by playpsro** [comment]
@anacondaqq  i have try last revision, client date 2013-08-07 , renewal full, 

just use skill flash combo . its different from last revision i'm use.
in revision of january, flash combo have a delay for produce the skill.
