### ISSUE TITLE
switch item no refresh skill tree.

### ISSUE THREAD

**Issue by hnomkeng** [rathena/rathena#7255]
* **rAthena Hash**: 4a43856
* **Client Date**: 2021-11-16
* **Server Mode**: Pre-renewal
* **Description of Issue**: 

![image](https://user-images.githubusercontent.com/9112684/188918355-b62f2af8-e23a-4263-a130-1b45febe7164.png)

**Comment by admkakaroto** [comment]
Why not try this first?
https://github.com/rathena/rathena/pull/6529

**Comment by hnomkeng** [comment]
> Why not try this first? #6529
> 
> and why not uses search buttom: #5382

pull can't fix

**Comment by hnomkeng** [comment]
ok, fixed.

#5931 + #6529

**Comment by secretdataz** [comment]
duplicate of #5382

**Comment by raphazen** [comment]
still error until this time
