### ISSUE TITLE
Guild Skills Timer Bug

### ISSUE THREAD

**Issue by Xypr0** [rathena/rathena#7256]
* **rAthena Hash**: 

 Git Hash: '84d295e78431815fd823687c897ec0f180542085'

* **Client Date**: 20151104

* **Server Mode**:  Pre-Renewal

* **Description of Issue**: 
  * Result:  guild skills timer is 5 minutes by default. when you character select then log in again. if you check the time is not resetting. if your guilld skills time is 2:50 minutes before you can use it and when you character select and log in and the timer is still the same or its around 2:40
  * Expected Result: When player character select and log in again. the guild skill timer should reset to original/set time in the settings
  * How to Reproduce: guild skills timer is 5 minutes by default. when you character select then log in again. if you check the time is not resetting. if your the guilld skills time is 2:50 minutes before you can use it and when you character select and log in and the timer is still the same or its around 2:40
  * Official Information:  in official behavior and tested in latest git in rathena. the guild skills timer should reset when you character select. 
  

* **Modifications that may affect results**: 
   I do have modification in my src but i tested it in clean file of this git hash version and still i can re-produce this bug.

**Comment by Xypr0** [comment]
![current time](https://user-images.githubusercontent.com/76208477/189000177-5cb15264-a4d0-4541-bae2-575a555da062.png)
this is the current time of guild skills before i character select.

![v2](https://user-images.githubusercontent.com/76208477/189000224-0bd09be7-0e6b-442f-b399-183a3d6fe76c.png)
this is the current guild skills when i log in again.

**Comment by aleos89** [comment]
What server are you getting the behavior of this from? I can't really find anything that suggests kRO follows this behavior.

**Comment by Xypr0** [comment]
> I guess it still running even you logout.

yes that's what happen.

**Comment by Xypr0** [comment]
> What server are you getting the behavior of this from? I can't really find anything that suggests kRO follows this behavior.

this is the sample video of the bug.
https://www.mediafire.com/file/jpese1kkvykt7z4/Guilld_Skills_CD_Time_BUG.wmv/file

**Comment by Xypr0** [comment]
@aleos89 thank you sir. its working perfectly now.
