### ISSUE TITLE
WOE sliding

### ISSUE THREAD

**Issue by MrAntares** [rathena/rathena#726]
Looks like backslide (normal and feint bomb), back side slide and front side slide is enabled on woe. 
https://youtu.be/MG1J6-63EqE?t=2m17s

"
@  Antares  :   (27 October 2015 - 08:11 PM)What's with the back sliding on woe?! https://youtu.be/MG1J6-63EqE?t=2m17s It is now enabled? :o
@  Nova :   (27 October 2015 - 10:29 PM)I figured it got enabled a long time ago seeing as how there's Mechanic Front/Backslide. iRO's had it enabled since a looong time ago but I never checked kRO.
"

Should be checked on kRo.

Other knock-back effects should be re-checked as well.

**Comment by Paoly28** [comment]
i think only mechanic back/front slide and feint bomb works at woe. since backslide is specially enabled only at iRO.

**Comment by Paoly28** [comment]
also Knuckle Arrow is supposed to have no snap effect during WoE. tested this

**Comment by aleos89** [comment]
Would like to get a kRO confirmation on this. :+1:

**Comment by MrAntares** [comment]
Client: 2012-04-10

Revision: 14739
Last Changed Author: cydh.ramdh
Last Changed Rev: 14739
Last Changed Date: 2015-10-29 06:16:10 +0100 (Thu, 29 Oct 2015)

Mode: RENEWAL

**Comment by Lemongrass3110** [comment]
SVN-Revision 14739 corresponds to GIT-Hash: ae98019

Thanks for providing the missing information @MrAntares

**Comment by MrAntares** [comment]
Can we fix this?
"mechanic back/front slide and feint bomb works at woe"

**Comment by Playtester** [comment]
Still needs kRO info and if you want it for your server, it can easily be changed via config files, can't it?

**Comment by RagnarokNova** [comment]
Thief's Backslide is still disabled in both WoE FE and SE maps on kRO. Do not have the characters to test the other skills.

**Comment by aleos89** [comment]
Confirmed that Feint Bomb and Mechanic Front/Back Slide work on WoE maps.

**Comment by aleos89** [comment]
Just tested on 923199d and this is working as intended.
