### ISSUE TITLE
Icon status when logout all status disappear..

### ISSUE THREAD

**Issue by gravity-ro** [rathena/rathena#7261]
๐ Client Date: 20211117
๐ Server Mode: Renewal
๐ Description of Issue:

Icon/status/VIP when logout all status and VIP disappear..
I update from here everyday "Code" "Pull requests"
I think the problem is after update "C4 Expanded"
But i don't know where.

Thank you advance.

![11](https://user-images.githubusercontent.com/80197766/189684507-7854518b-3315-45db-a341-2823c9856af9.png)

**Comment by Akkarinage** [comment]
Why did you not follow the Issue Template?

If you don't know what you've changed, it's very difficult to pinpoint where something is going wrong. Without some information for reproduction or an error code to look at, I'll close this.

It can be re-opened with more information.

**Comment by gravity-ro** [comment]
> Why did you not follow the Issue Template?
> 
> If you don't know what you've changed, it's very difficult to pinpoint where something is going wrong. Without some information for reproduction or an error code to look at, I'll close this.
> 
> It can be re-opened with more information.

Compile no error.
========== Build: 14 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

In Char/Login/Map/Web it's not error too.

It's happen on player login game all about status disappear.

I Think before update.

Commits on Dec 19, 2021
[Added basic support for 4th and 4th-ex class (](https://github.com/rathena/rathena/commit/6ddb09cbbd61a8e250a63a4683eeb8fc8262b726)https://github.com/rathena/rathena/pull/6412[)](https://github.com/rathena/rathena/commit/6ddb09cbbd61a8e250a63a4683eeb8fc8262b726)

Server it's works fine after continue UpToDate last update today.

**Comment by zdurexz** [comment]
> > Why did you not follow the Issue Template?
> > If you don't know what you've changed, it's very difficult to pinpoint where something is going wrong. Without some information for reproduction or an error code to look at, I'll close this.
> > It can be re-opened with more information.
> 
> Compile no error. ========== Build: 14 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
> 
> In Char/Login/Map/Web it's not error too.
> 
> It's happen on player login game all about status disappear.
> 
> I Think before update.
> 
> Commits on Dec 19, 2021 [Added basic support for 4th and 4th-ex class (](https://github.com/rathena/rathena/commit/6ddb09cbbd61a8e250a63a4683eeb8fc8262b726)[https://github.com/rathena/rathena/pull/6412[)](https://github.com/rathena/rathena/commit/6ddb09cbbd61a8e250a63a4683eeb8fc8262b726](https://github.com/rathena/rathena/pull/6412%5B)%5D(https://github.com/rathena/rathena/commit/6ddb09cbbd61a8e250a63a4683eeb8fc8262b726))
> 
> Server it's works fine after continue UpToDate last update today.

why you say becuase commit https://github.com/rathena/rathena/commit/6ddb09cbbd61a8e250a63a4683eeb8fc8262b726 The above code has nothing to do with VIP. Please check your errors carefully.

**Comment by gravity-ro** [comment]
> > > Why did you not follow the Issue Template?
> > > If you don't know what you've changed, it's very difficult to pinpoint where something is going wrong. Without some information for reproduction or an error code to look at, I'll close this.
> > > It can be re-opened with more information.
> > 
> > 
> > Compile no error. ========== Build: 14 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
> > In Char/Login/Map/Web it's not error too.
> > It's happen on player login game all about status disappear.
> > I Think before update.
> > Commits on Dec 19, 2021 [Added basic support for 4th and 4th-ex class (](https://github.com/rathena/rathena/commit/6ddb09cbbd61a8e250a63a4683eeb8fc8262b726)[https://github.com/[/pull/6412](https://github.com/rathena/rathena/pull/6412)[)](https://github.com/rathena/rathena/commit/6ddb09cbbd61a8e250a63a4683eeb8fc8262b726%5D(https://github.com/rathena/rathena/pull/6412%5B)%5D(https://github.com/rathena/rathena/commit/6ddb09cbbd61a8e250a63a4683eeb8fc8262b726))
> > Server it's works fine after continue UpToDate last update today.
> 
> why you say becuase commit [6ddb09c](https://github.com/rathena/rathena/commit/6ddb09cbbd61a8e250a63a4683eeb8fc8262b726) The above code has nothing to do with VIP. Please check your errors carefully.

Thank you.
It's no error all clean in VB and Char/Login/Map/Web i can't find the problem.
looking for a solution for a long time really can't fix.

**Comment by gravity-ro** [comment]
Look like this case.
https://rathena.org/board/topic/130992-status-wont-disappear-even-when-you-character-select/

**Comment by Akkarinage** [comment]
That case clearly has no relevance.

You have not yet provided any useful information to state that this isn't user-error, which in this case, it is. You cannot merge incomplete code from different sources and expect everything to work perfectly.

**Comment by gravity-ro** [comment]
> That case clearly has no relevance.
> 
> You have not yet provided any useful information to state that this isn't user-error, which in this case, it is. You cannot merge incomplete code from different sources and expect everything to work perfectly.


I've found the cause. It's from the file Conf Battle.
In this file I never adjust. This file is from constant updates.
The default is 0, but in the updated file is 3.

// Will certain skill status-changes be removed on logout?
// 0 = (Default) Only remove status that has the SCF_NO_SAVE flag.
// 1 = Remove negative buffs (status that are flagged as debuff)
// 2 = Remove positive buffs.
// 3 = Remove all.
debuff_on_logout: 0 <-----

**Comment by Akkarinage** [comment]
As I said, User-Error.

Have a temporary ban for having no common-sense.
