### ISSUE TITLE
Unable to spawn clone.

### ISSUE THREAD

**Issue by jmsngls** [rathena/rathena#7268]
## Required Basic Information

**rAthena Hash**: 97b5f3b4ac63bb920a673043af02518784c386f5

**Client Date**: 2018-06-21a

**Server Mode**: Pre-Renewal

 

## Required Detailed Information

**Result**: Unable to spawn Clone even Evilclone using ``` `@clone/@evilclone` ```

**Expected Result**: should spawn friendly clone in ``` `@clone` ``` / enemy like clone ``` `@evilclone` ```

**How to Reproduce**: just use the command to self ``` `@clone/@evilclone` ```

**Official Information**: 

**Modifications that may affect results**: I tried clean, not working

**Comment by mazvi** [comment]
Are you test with charname?

[At]clone charname

**Comment by jmsngls** [comment]
Yes, tried it with char id too and still not working

**Comment by Akkarinage** [comment]
When you say `Unable to spawn` do you mean nothing happens at all?
Any error message on map-server? 
Any messages in client chat window?

**Comment by jmsngls** [comment]
Yes nothing happens,
No error message in map-server.
It just says "Unable to spawn clone."

**Comment by Lemongrass3110** [comment]
Do you have manner.txt enabled? If you have it enabled and the player name contains a bad word it will come to the server censored.
I also faced this problem last time, because Lemongrass contains "ass" and then it comes to the server as "Lemongr***".

**Comment by jmsngls** [comment]
No, my manner.txt is also empty.

**Comment by bgamez23** [comment]
disconnected on the server when i summon clone.
![image](https://user-images.githubusercontent.com/1854368/191873634-c824ff95-92bb-40e1-9fda-ab2954c53047.png)
```
[Warning]: clif_parse: Received unsupported packet (packet 0x0bb0, 9 bytes received), disconnecting session #3.
[Info]: Character 'Brynner' logged off.
```

**Comment by Lemongrass3110** [comment]
> disconnected on the server when i summon clone. ![image](https://user-images.githubusercontent.com/1854368/191873634-c824ff95-92bb-40e1-9fda-ab2954c53047.png)
> 
> ```
> [Warning]: clif_parse: Received unsupported packet (packet 0x0bb0, 9 bytes received), disconnecting session #3.
> [Info]: Character 'Brynner' logged off.
> ```

@bgamez23 Update your server. fa4666d
