### ISSUE TITLE
Guild Emblem is not showing even though its already saved in the SQL.

### ISSUE THREAD

**Issue by lelouch22** [rathena/rathena#7269]
## Required Basic Information

**rAthena Hash**: ee5ba2d8899653bb1362ad1edebd586f4a198070

**Client Date**: 2020-04-01

**Server Mode**: Pre-Renewal

 

## Required Detailed Information

**Result**: 
![emblem](https://user-images.githubusercontent.com/4976551/190491460-0c150ce9-55f5-48a6-9a1e-8ee0f2a8cff5.png)
![screenMidgard Mayhem001](https://user-images.githubusercontent.com/4976551/190490215-e98dd096-1be5-4dd6-a5ce-bac15a4571d3.jpg)
![screenMidgard Mayhem002](https://user-images.githubusercontent.com/4976551/190490231-e221ede8-6e07-4b2e-9300-4b2b12bf3acf.jpg)
![screenMidgard Mayhem003](https://user-images.githubusercontent.com/4976551/190490803-57e37919-daab-41e6-ab1d-a686e6fade92.jpg)

**Expected Result**: The emblem should be shown.

**Comment by OptimusM** [comment]
did u add your IP on the client settings?

**Comment by lelouch22** [comment]
> did u add your IP on the client settings?
Yeah, I already did that beforehand.

**Comment by Gyakushinn** [comment]
Have you changed the IP address in the server_korea folder ?

**Comment by null6385** [comment]
your game folder  Are there any special characters? It's not readable.

**Comment by lelouch22** [comment]
Ok solved. I already figured out what's the problem. I haven't added the "Fix HTTP emblem in client" patch on the client. Anyways thank you everyone for your replies.
