### ISSUE TITLE
Endure

### ISSUE THREAD

**Issue by MrAntares** [rathena/rathena#727]
Multi hit magical skills bypass endure.

For example life drain, fireball don't cause flintch, while dark soul strike, meteor storm does. This is clearly wrong.

**Comment by Playtester** [comment]
Has something to do with a renewal client update. I remember I tried to send the endure packet and the client still displayed flinch on multi-hit.

**Comment by MrAntares** [comment]
Client: 2012-04-10

Revision: 14739
Last Changed Author: cydh.ramdh
Last Changed Rev: 14739
Last Changed Date: 2015-10-29 06:16:10 +0100 (Thu, 29 Oct 2015)

Mode: RENEWAL

**Comment by Lemongrass3110** [comment]
SVN-Revision 14739 corresponds to GIT-Hash: ae98019

Thanks for providing the missing information @MrAntares

**Comment by MrAntares** [comment]
Do we have the correct packets yet?

**Comment by Lemongrass3110** [comment]
Not yet. But if you happen to have a replay or WPE file which contains it, we could try to grab it from there.

**Comment by RagnarokNova** [comment]
Just got some from kRO Sakray for you guys:
[Endure-Standing.txt](https://github.com/rathena/rathena/files/216496/Endure-Standing.txt)
[Endure-Walking.txt](https://github.com/rathena/rathena/files/216495/Endure-Walking.txt)

Hope you can find what you're looking for here. It's me as a low level swordsman versus a Little Poring.

**Comment by RagnarokNova** [comment]
Intended behavior:
http://a.pomf.cat/msmbsa.mp4

http://a.pomf.cat/eryobs.mp4

Recorded on an Aegis server.
