### ISSUE TITLE
Feint bomb

### ISSUE THREAD

**Issue by MrAntares** [rathena/rathena#728]
https://youtu.be/NZ8U2toR2r0
Long story short... They shouldn't follow.

Longer version
Feint bomb goes like: Back slide, mobs follow, hide, no bang (mobs moved out of the copycat's explosion range)....
Mobs should stay targeted on the copycat before it explodes and absolutely not follow the player.

**Comment by MrAntares** [comment]
Client: 2012-04-10

Revision: 14739
Last Changed Author: cydh.ramdh
Last Changed Rev: 14739
Last Changed Date: 2015-10-29 06:16:10 +0100 (Thu, 29 Oct 2015)

Mode: RENEWAL

**Comment by Lemongrass3110** [comment]
SVN-Revision 14739 corresponds to GIT-Hash: ae98019

Thanks for providing the missing information @MrAntares

**Comment by aleos89** [comment]
Confirmed. Monsters should not follow the player. The player casts (spins), immediately hides, monster will stay where the player hid --> player backslides, bomb goes off.

Another note: When using another skill such as Hide after backsliding through Feint Bomb, it **will** cancel Feint Bomb.

**Comment by geeroo1221** [comment]
Please Help 

http://youtube.com/watch?v=joPlDl62edo

Got some bug

**Comment by jezznar** [comment]
Tried and tested with the latest rA git. Works correctly. Looking at the video. Your character has less than job level 1. If you put that in to the skill ratio damage formula you'll get a damage less than 1. 

`skillratio += -100 + (skill_lv + 1) * status_get_dex(src) / 2 * ((sd) ? sd->status.job_level / 10 : 1);`

**Comment by MrAntares** [comment]
Pz fix?

**Comment by Playtester** [comment]
I think @aleos89 already fixed that, can you please check?

**Comment by MrAntares** [comment]
I just updated, it is still broken :(

**Comment by MrAntares** [comment]
@Playtester I updated like 5 minutes ago, and it is still broken :(
The mobs still follow me and the explosion don't happen because they move out of range.

**Comment by MrAntares** [comment]
To fix it swap the hide and the blow functions:

`	case SC_FEINTBOMB:
		skill_unitsetting(src,skill_id,skill_lv,x,y,0); // Set bomb on current Position
		clif_skill_nodamage(src,src,skill_id,skill_lv,sc_start(src,src,type,100,skill_lv,skill_get_time2(skill_id,skill_lv)));
		skill_blown(src,src,skill_get_blewcount(skill_id, skill_lv),unit_getdir(src),BLOWN_NONE);
		break;`
