### ISSUE TITLE
[BUG] Homunculos Eira - Silent Breeze 

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#729]
The ability of the Homunculus Eira does not. It should cause mute on target.Does not work. Clicking nothing happens .

rAthena bug: https://youtu.be/5MiCdb2dEMQ

Correct: https://www.youtube.com/watch?v=HHdC4WQl4h4

Revision: 29/10/15 rA (no work)

**Comment by lighta** [comment]
MVP are usually immune to status.
Since it doesn't display you a thing to target it seem the check fail on skill_isNotOk, so that usually mapflag or something like that.
Now for you're video you're in a city which have a mapflag that disable skill most of the time.

**Comment by Badarosk0** [comment]
The ability was tested outside the city and common monsters too. Does not work.

**Comment by philg666** [comment]
tested it, the skill doesnt work like its disabled or something.

**Comment by lighta** [comment]
Idk who did that, (will have to check blame) but check skill_db.txt and change inf value from 6 to 16 or 1 that should fix it.
(1 or 16 ) should only change the default target. Think it should probably 16.

**Comment by lighta** [comment]
seem to have been change here : https://github.com/rathena/rathena/commit/89ef8686
@aleos, you remenber why from 16 to 6 ? imo it was a typo since 6 is invalide type for inf.
You can't target someone and the ground in the sametime..

**Comment by julia40124009** [comment]
https://rathena.org/board/tracker/issue-9206-valid-field-inf-silent-breeze/

**Comment by cydh** [comment]
afaik, even the `inf` value is like bitmask value, but it never can be combined, just a client issue, it makes skill cannot be used.
then,
1st, it must be `inf = 1`.
````SkillType				TOCHARACTER````
2nd, (instead Silence) the inflicted status should be (with) EFST_SILENT_BREEZE
````-- 사일런트 브리즈 SKID_MH_SILENT_BREEZE
EFST_SILENT_BREEZE = {
	ResetDead = true;	
	Save = true;
	Send = true;
	SendMultiCast = true;
};````

**Comment by aleos89** [comment]
Yeah that's definitely a typo.

**Comment by cydh** [comment]
err 16.
