### ISSUE TITLE
Web Server | Merchant Sql duplicate error.

### ISSUE THREAD

**Issue by Tolimatoi** [rathena/rathena#7290]
### rAthena Hash

ee5ba2d8899653bb1362ad1edebd586f4a198070

### Client Date

2021-11-17

### Server Mode

Renewal

### Result

When opening two types of stores, the Web Server must save the information of the two types of stores.

Sorry for my english, i'm using translator.

### Expected Result

N/A

### How to Reproduce

When opening and closing a Shop with a character (Sale or Buy), it will save correctly only for that Shop Type.

![image](https://user-images.githubusercontent.com/47765684/192919013-e2d68423-04e9-4972-b0c3-3707220bef52.png)

When trying to open and close another type of store, it will send an error:
[SQL]: DB error - Duplicate entry 'x' for key 'merchant_configs.PRIMARY'

![image](https://user-images.githubusercontent.com/47765684/192919705-f2e0bee2-d110-4667-b2f7-2ba0535494b5.png)

### Official Information

N/A

**Comment by Akkarinage** [comment]
Are you trying to open two stores with the same character? I'm pretty sure it's not possible to do that, so the error is correct and everything is working as intended.

Or am I not understanding?

**Comment by Tolimatoi** [comment]
No, first use the 'Vending' skill, close the store and use the 'Buying Store' skill.
