### ISSUE TITLE
Sever it's can't use sql in map server error a lot

### ISSUE THREAD

**Issue by XXXlistenXXX** [rathena/rathena#7296]
### rAthena Hash

https://github.com/rathena/rathena

### Client Date

20220406

### Server Mode

Renewal

### Result

1. Compile server from this link : https://github.com/rathena/rathena
2. Config server to use sql
3. Sever it's can't use sql in map server error a lot

### Relevant Log Output

```Shell
-
```

### Expected Result

-

### How to Reproduce

-

### Official Information

-

### Modifications that may affect results

-

**Comment by Daegaladh** [comment]
You need to configure your SQL permissions properly.
If you have any problems feel free to ask in our forums or discord.
Please, keep Github for proper bugs only.

**Comment by XXXlistenXXX** [comment]
> You need to configure your SQL permissions properly. If you have any problems feel free to ask in our forums or discord. Please, keep Github for proper bugs only.

Thank you, because I don't have a tutorial on how to use sql anywhere, so I'm asking here. Can you advise me where to find out how to do it? or tell me here? thanks in advance.

**Comment by XXXlistenXXX** [comment]
Thank you very much
This latest server is still not able to use sql database system.

![Screenshot_2](https://user-images.githubusercontent.com/101814774/193268697-d6aa9ff1-a75e-4bb7-a104-cb89eb4186dc.png)

**Comment by Daegaladh** [comment]
Again, use the forums or discord for support.
