### ISSUE TITLE
script issue

### ISSUE THREAD

**Issue by hendra814** [rathena/rathena#730]
tuturial instructror quest at eden 2nd floor. after bring mercenary, he will ask you to buy windows Shopper Catalogue from Catalogue Wizard.at sout prontera (like IRO)
but i can't find the npc at south prontera, i found the npc at eden first floor.

A script from rathena about catalogue wizard detail location
</quote>mes "[Tutorial Instructor]";
				mes "The ^006400Universal Silver Catalog^000000";
				mes "can be obtained from";
				mes "the ^0000FFCatalogue Wizard^000000";
				mes "that is located in South Prontera.";
				next;
				mes "[Tutorial Instructor]";
				mes "Now, go and obtain";
				mes "a ^006400Universal Silver Catalog^000000";
				mes "then come back and talk to me.";
				completequest 9168;
				setquest 9169;
				close;
	</quote>

**Comment by Lemongrass3110** [comment]
Newer and more detailed report of this issue: #742
