### ISSUE TITLE
User input to yaml2sql is not showing

### ISSUE THREAD

**Issue by emmamarshall451** [rathena/rathena#7302]
### rAthena Hash

47c9a362156b27fca484fd70e7990ceb1cc79d32

### Client Date

2002-09-25

### Server Mode

Pre-Renewal, Renewal

### Result

**Environment: ** Windows 7 Ultimate SP1 64bit

**Trigger Event:** 
1. Run yaml2sql.bat and press "Y" or "N"
2. User input not showing on command prompt

I already tried Run as administrator and also directly running yaml2sql.exe  and spam "Y" and "Enter" key but it really does not show my input also tried Rebuild Solution and Clean Solution

### Expected Result

Keep asking for user input repeatedly for each  .yaml  file found and  that user indeed want to convert it as .sql while showing the User Input selection ( Y/N ) on screen ...

### How to Reproduce

Run yaml2sql.bat and press "Y" or "N" user input is not showing

### Official Information

None

### Modifications that may affect results

None

**Comment by Lemongrass3110** [comment]
This is intended behavior. As soon as you press a key on the keyboard it will either process the file or not.
As this is more a support request than a bug report, please use our forum or discord and ask for help there.
Thank you!
