### ISSUE TITLE
Status Recovery not working in Frozen player when receives other buffs

### ISSUE THREAD

**Issue by jmsngls** [rathena/rathena#7314]
### rAthena Hash

97b5f3b4ac63bb920a673043af02518784c386f5

### Client Date

2018-06-21

### Server Mode

Pre-Renewal

### Result

GVG, PVP when player is frozen once it receives other buffs such blessing.

### Expected Result

After status recovery, player must remove frost

### How to Reproduce

Frost player first, then add blessing to frozen player then status recovery, no effect.

### Official Information

Cures a single target from the following status effects: [Frozen](https://irowiki.org/wiki/Status_Effects#Frozen), [Stone](https://irowiki.org/wiki/Status_Effects#Stone) and [Stun](https://irowiki.org/wiki/Status_Effects#Stun).

**Comment by hnomkeng** [comment]
update to : https://github.com/rathena/rathena/commit/5f4fd5c98bb5841aba048326e2f0ca6e6f76c45c

**Comment by jmsngls** [comment]
This one is frozen status bug, when you cast blessing skill on a frozen player, you cannot break the freeze using status recovery.
