### ISSUE TITLE
Party packet error when relog to select char

### ISSUE THREAD

**Issue by Sarayut-Y** [rathena/rathena#7324]
### rAthena Hash

19fe27932f31066e8b6b025f8348cf7dc7f4deb2

### Client Date

2019-06-05fRagexe

### Server Mode

Pre-Renewal

### Result

When char has party and relog to char select in console warning packet, if don't have party member online this warning message not showing

<img width="1691" alt="packet_error_when_relog" src="https://user-images.githubusercontent.com/6380878/193835358-47c86801-d832-4861-a487-2ecca2246c09.png">

### Expected Result

- Warning message not show when relog to select character.

### How to Reproduce

- Join party member and relog character this warning message is show.

### Official Information

-

**Comment by hnomkeng** [comment]
confirm, using client date 20211116.

**Comment by namuHoreZ** [comment]
I talked about this before in discord. Though I am the only one who got this error messages.
I'm using client date = 20211103. Test it on debian 11 and windows.
Serverlogs are spammed with this messages.

**Comment by 24msz6eo** [comment]
How to solve this problem?
Is this just a warning? Will it affect the game?

**Comment by 24msz6eo** [comment]
Seems like no one cares about this @@"

**Comment by imaqtdan** [comment]
confirm, using client date 20220330
