### ISSUE TITLE
MVP exp message

### ISSUE THREAD

**Issue by MrAntares** [rathena/rathena#733]
After defeating an mvp the game says:

"Congratulations! You are the MVP! Your reward EXP Points are -1!!"

I have checked the luas and msgstringtable, but I couldn't find anything wrong. Maybe the server is not sending properli the value?

In the battle log, I saw getting the MVP exp, only the message is wrong.

**Comment by philg666** [comment]
this is weird, i'm testing it right now. i'll be back with more infos on this.

**Comment by aleos89** [comment]
What client date are you using?

**Comment by MrAntares** [comment]
Client: 2012-04-10

Revision: 14739
Last Changed Author: cydh.ramdh
Last Changed Rev: 14739
Last Changed Date: 2015-10-29 06:16:10 +0100 (Thu, 29 Oct 2015)

Mode: RENEWAL

**Comment by Lemongrass3110** [comment]
SVN-Revision 14739 corresponds to GIT-Hash: ae98019

Thanks for providing the missing information @MrAntares

**Comment by Lemongrass3110** [comment]
![mvp_exp](https://cloud.githubusercontent.com/assets/3517879/11049982/8fdb9f76-8742-11e5-99ad-12e58bb7fe59.PNG)

Sorry but I cannot reproduce this issue. Could it be your msgstringtable or something like that?
Is it for all mobs or only some?

I tested with turtle general.

**Comment by MrAntares** [comment]
AFAIK All mobs. I have the msgstringtable correctly. I tried to change the text and I could see it changing, so I found the one, but the value wasn't there. I was thinking about the lua files, but I'm not sure which one is responsible for these messages.

**Comment by hendra814** [comment]
using client 2015-05-13 show the same issue
![screenapel ro001](https://cloud.githubusercontent.com/assets/9587609/11801746/9064b460-a31b-11e5-9f3a-3cbd915ca489.jpg)

**Comment by Lemongrass3110** [comment]
@hendra814 this issue is related to the 2015 client. Not this issue. Please create a new issue for this.
Thank you!
