### ISSUE TITLE
Soul Breaker

### ISSUE THREAD

**Issue by MrAntares** [rathena/rathena#734]
The magical part misses on ghosts, while it should be non-elemental and thus hit ghost element.

http://irowiki.org/wiki/Soul_Breaker
"Magic portion
- Is Non-elemental. Meaning it is 100% unaffected by property of the target. This means that it will do 100% to Ghost property."

**Comment by MrAntares** [comment]
Revision: 14739
Last Changed Author: cydh.ramdh
Last Changed Rev: 14739
Last Changed Date: 2015-10-29 06:16:10 +0100 (Thu, 29 Oct 2015)

RENEWAL

**Comment by Lemongrass3110** [comment]
SVN-Revision 14739 corresponds to GIT-Hash: ae98019

Thanks for providing the missing information @MrAntares

**Comment by MrAntares** [comment]
Bump?

**Comment by Playtester** [comment]
Is this a special renewal thing?

**Comment by MrAntares** [comment]
It was the same in pre-re and the re version inherited this behav. I could confirm this on iRo (even with my 2000ping  T_T) , but I haven't found any kRo description, so it should probably be checked to make it sure.


The only thing I found is some player also stating that this is bugged:

> However, the MATK portion is still bugged and missing on ghost 3/4 when it has always been "Element-less" damage, meaning it is unaffected by any element interaction and does 100% to everything, including ghost 3/4. This part is still not working. It is never supposed to miss either, I haven't tested that here yet.
http://leika-ro.net/forum/index.php?/tracker/issue-351-soul-breaker-being-forced-neutral/
