### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by StarGmes** [rathena/rathena#7343]
### rAthena Hash

https://github.com/rathena/rathena/commit/6bb29c0743f9d554001d3fa1d5a5843f0c04d47a

### Client Date

20220330

### Server Mode

Pre-Renewal, Renewal

### Result

I am using debian 
this didn't happen to me I just updated and I got this error
windows does not give this error 

![error](https://user-images.githubusercontent.com/50535033/194814267-31e80995-9131-4b46-80b2-85e3f7e7bfff.png)

**Comment by vstumpf** [comment]
You need to reconfigure
