### ISSUE TITLE
Use party channel to speak Jump warning

### ISSUE THREAD

**Issue by 24msz6eo** [rathena/rathena#7344]
### rAthena Hash

https://github.com/rathena/rathena/commit/43f5094620a9bd094cc014954db7697e4c83d8f1

### Client Date

2021-11-17

### Server Mode

Renewal

### Result

Use party channel to speak Jump warning

![螢幕擷取畫面 2022-10-10 004445](https://user-images.githubusercontent.com/68574321/194815365-89a9d69b-ae35-4a8a-bd96-d5d45ddcafc4.png)

### Expected Result

??

### How to Reproduce

??

### Official Information

??

**Comment by Daegaladh** [comment]
Please fill all questions in the issue template and better explain the issue.

**Comment by saizaisai** [comment]
using party chat triggers the warning
