### ISSUE TITLE
Self Destruction to Devotion Target Behavior

### ISSUE THREAD

**Issue by xerinne12** [rathena/rathena#7345]
### rAthena Hash

32525ba

### Client Date

2018-06-20

### Server Mode

Renewal

### Result

Hi everyone, please kindly help me with this one.

I've an issue with self destruction behavior in my server.

How to reproduce:
1. ROYAL GUARD A cast devotion to 5 Players (P1, P2, P3, P4, P5)
2. MECHANIC B cast self destruct on those devoted 5 players (P1, P2, P3, P4, P5)

Current behavior : ROYAL GUARD A, P2, P3, P4, P5 die and P1 alive.

### Expected Result

Expected official behavior : Only ROYAL GUARD A dies.

### How to Reproduce

1. Use an RG and devo 5 Target
2. Use Mechanic and use skill Self Destruction to those 5 Targets but not the RG.

### Official Information

In Official RO, only RG dies.

**Comment by raziq-bosses** [comment]
Yes, I have the same issue with you. 

I have record the video and upload on YouTube.

https://youtu.be/y-OPbDiKT5o

**Comment by GoneWild420** [comment]
Did you fix this already?

**Comment by b055es** [comment]
No it's still bugged for me. But I don't know why @xerinne12 closed this as completed.  I need to open new issue? cc @aleos89

**Comment by GoneWild420** [comment]
Yes bro. Can you open another issue? With video
