### ISSUE TITLE
SC_EXTREMITYFIST2 and statuses

### ISSUE THREAD

**Issue by Tokeiburu** [rathena/rathena#7346]
### Is your request related to a missing official feature?

No

### Describe the solution you'd like

When adding a custom status, you always want to add it before SC_MAX to avoid shifting all the entries that follow. Yet, the comment after SC_EXTREMITYFIST2 tells you explicitly not to do that.
```
#ifdef RENEWAL
	SC_EXTREMITYFIST2, //! NOTE: This SC should be right before SC_MAX, so it doesn't disturb if RENEWAL is disabled
#endif
```
Originally this request was meant towards custom statuses, but it appears rAthena also follows this comment when adding new official statuses. Yet, I believe this should be avoided. Here's an example:

- A player logs out while having the SC_EXTREMITYFIST2 status (let's pretend the value is 1500), and SC_MAX is 1501.
- You do an update, you add statuses, SC_PORK_RIB_STEW is now above SC_EXTREMITYFIST2.
- Their new IDs will now become SC_PORK_RIB_STEW = 1500, and SC_EXTREMITYFIST2 = 1501, and SC_MAX is 1502.
- When the player logs back in, instead of having SC_EXTREMITYFIST2, he will now have SC_PORK_RIB_STEW as his status.

Granted this won't last for long, since SC_EXTREMITYFIST2 usually has a short duration, it can create weird situations or straight up potential bug/crash for the player having a status they shouldn't have.

### Describe alternatives you've considered

I would consider simply removing the #ifdef before SC_EXTREMITYFIST2 and remove the comment next to it. As far as I could tell, it is the only status defined in such a way. Meanwhile, there are numerous renewal only statuses defined even for pre-renewal, so it doesn't make much sense to do an exception for this one.

**Comment by aleos89** [comment]
This has been discussed before to drop the ifdef since we already have several SC in renewal and not pre-renewal. Seems we forgot about it!
