### ISSUE TITLE
Useless VIP settings, 

### ISSUE THREAD

**Issue by Fraterna** [rathena/rathena#735]
hi there.

no idea if it's "work as intended", but the current VIP settings make no real sense:
"vip_drop_increase: 100" adds a plain 1% on any dropped item.
cards 0.01% -> 1.01%
jellopy: 90% -> 91%

no idea if this is really intended, but maybe you wanna consider to revise that. example:
let's assume some server's rates is 10x
"vip_drop_increase: 100" // adds a 100% boost on the server's droprate setting
cards 0.1% -> 0.2%
something: 40% -> 80%
etc. a plain +x/100 boost on ANY drop is useless. (revise it would make it less confusing to non-programmer-admins)

same to "vip_base_exp_increase: 50" -> just adds 50% of the ground-exp, completely ignoring the server's setting. at some 25x rates that would boost the exp to 25.5x rates.
would be more useful to revise it to follow the server's setting in exp.conf

**Comment by aleos89** [comment]
This sounds more like a suggestion, rather than a bug. But! your suggestion has already been in the works. I just sorta dropped it as other pressing things took place but I will definitely pick it back up and finalize it!
