### ISSUE TITLE
Monster Bug Some Skill 

### ISSUE THREAD

**Issue by JasonKery** [rathena/rathena#7351]
### rAthena Hash

https://github.com/rathena/rathena

### Client Date

20220406

### Server Mode

Renewal

### Result

Monster Bug Some Skill 

@AL_HEAL
@NPC_COMBOATTACK

When monster use this skill Map Server is disconnect and close.

Thank you advanced.

### Relevant Log Output

```Shell
Monster Bug Some Skill
```

### Expected Result

Monster Bug Some Skill 

### How to Reproduce

Monster Bug Some Skill 

### Official Information

Monster Bug Some Skill 

### Modifications that may affect results

Monster Bug Some Skill

**Comment by secretdataz** [comment]
![image](https://user-images.githubusercontent.com/2021243/195363528-3efe272f-5616-4e6c-98df-8d06b5f3553c.png)
Not reproducible. Also, how about you spend a minute to read what we need you to fill into the issue report form instead of mashing Ctrl+V button?
