### ISSUE TITLE
NPC_COMET spamming skill on use

### ISSUE THREAD

**Issue by sonniez** [rathena/rathena#7355]
### rAthena Hash

f6633b5e7df07b2f72f97ca0378d7a6a36e00bea

### Client Date

2022-07-20

### Server Mode

Renewal

### Result

1. When monster use NPC_COMET, it's spamming this skill around 10-15 secs.
2. tested on mob id 2564 (Geffen Fenrir)

### Expected Result

NPC_COMET should only be used once when monsters use this skill.

### How to Reproduce

wait till monster use this skill and just walk around.

### Official Information

No idea.

**Comment by aleos89** [comment]
Worked just fine for me on master as of 4836e09.

There's a 30 second delay for the skill:
`2564,Geffen Fenrir@NPC_COMET,attack,708,5,2000,5000,30000`

**Comment by OptimusM** [comment]
"Official information": *No Idea*
Epic.

Jokes aside, fenrir has that CD thal aleos mentioned on kRo.
rAthena use kRo information.

**Comment by sonniez** [comment]
sorry to not mention it clearly. so I've recorded the video to explain how to reproduce this weird bug(or not)? (No modification on src and db)

https://youtu.be/g7V9tmpjCuM

**Comment by OptimusM** [comment]
Actually, someone whit fat fingers let +0 on the duration of the skill, so, change from 18000 to 1800 on skill_db.yml (re) and it will be ok.

@aleos89 im helping, give my medal <3

But yeah, it is a bug on the Duration on current rA.
