### ISSUE TITLE
Secrament(AB_SECRAMENT) BUG, no have effect skill.

### ISSUE THREAD

**Issue by hnomkeng** [rathena/rathena#736]
see vdo test (Pre-rewenal) : https://youtu.be/9mtvzbSCAg4

Level	Description
1	Fixed Casting Time Decrease 10%
2	Fixed Casting Time Decrease 20%
3	Fixed Casting Time Decrease 30%
4	Fixed Casting Time Decrease 40%
5	Fixed Casting Time Decrease 50%

**Comment by aleos89** [comment]
You're using pre-renewal? There is no fixed cast time in pre-renewal, so that skill is completely useless.

**Comment by hnomkeng** [comment]
yes. i using pre-renewal and wait fixed.

**Comment by hnomkeng** [comment]
yes pre-rewenal.

**Comment by Lemongrass3110** [comment]
Skills and items that are designed for renewal might have no effect on pre-renewal.
If you want to change that please do so yourself.

Closing this because it is working as intended.

**Comment by hnomkeng** [comment]
@Lemongrass3110  Issues such as renewal.
