### ISSUE TITLE
changebase shows skills in skilltree

### ISSUE THREAD

**Issue by iMillenium** [rathena/rathena#7364]
### rAthena Hash

Latest

### Client Date

2022-03-04

### Server Mode

Pre-Renewal, Renewal

### Result

I'm trying to make an item give the player the "skin" of another class
however when changing the character's skin, the skill tree of the changed class appears for the player! in a 2019 version of rathena the function behaves as desired.
Changes appearance, but does not change skilltree
![image](https://user-images.githubusercontent.com/7401604/196015698-c9445e79-f8ba-4f5a-bfab-1cecffd884af.png)

![image](https://user-images.githubusercontent.com/7401604/196015668-e306028e-85ee-446f-8a75-cc0e42eeb9b4.png)

### Expected Result

The character's appearance must change, without modifying the skilltree

### How to Reproduce

1. Create an item or npc to use the function;
```
    Script: |
      changebase JOB_MAGE;
    UnEquipScript: |
      changebase Class;d
```
2. Activate the function;;
3. check the skill tree

### Official Information

none

**Comment by secretdataz** [comment]
It has been working this way since it was first coded.
When I experimented with changebase back in 2015-2016 it also affects the skill tree. It works this way because the server has to send the fake changebased job id to trick the client into changing the player's sprite.
