### ISSUE TITLE
Macro Detection Action

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#7365]
### Is your request related to a missing official feature?

No

### Describe the solution you'd like

Related: https://github.com/rathena/rathena/commit/d7bf5ebb589404cf580434cc5e8e490bdbce881c

Please add config action for Macro Detection if failed/wrong answer.

The option for config is:
1. Parmanent Ban
2. **Temporary Ban with Config Time**
3. Permanent Jail
4. **Temporary Jail with Config Time**

Also please add feature log if player banned from macro detection captcha

**Comment by aleos89** [comment]
I had started working on a config to adjust the time but ended up thinking of a player were to fail 3 times then something is up. Usually you don't want to let a bot back on the server after X time.

**Comment by mazvi** [comment]
> I had started working on a config to adjust the time but ended up thinking if a player were to fail 3 times then something is up. Usually you don't want to let a bot back on the server after X time.

but I think it's necessary. such as giving a warning with a temporary jail / ban before doing a permanent jail / ban which will be done manually.

**Comment by bgamez23** [comment]
> warning with a temporary jail / ban befo

maybe on official server does not work in that way.it should be automatically since GM's can't monitor everyone on the but server can do it automatically. so if you got jailed many times. you already get a warning unless you are a bot who doesn't care about those warnings.
