### ISSUE TITLE
Item ID: 28141 should be Two-Handed

### ISSUE THREAD

**Issue by kaninhot004** [rathena/rathena#7366]
### rAthena Hash

43036926c

### Client Date

2022-04-06

### Server Mode

Renewal

### Result

Item ID: 28141 wrong sub-type

### Expected Result

db/re/item_db_equip find 28141

Change: 1hAxe to 2hAxe

### How to Reproduce

-

### Official Information

Two-Handed

**Comment by Takiusu** [comment]
Confirmed: https://www.divine-pride.net/database/item/28141/guardian-knight-battle-axe-2
