### ISSUE TITLE
Skill Flag ShowScale not working

### ISSUE THREAD

**Issue by violent01** [rathena/rathena#7370]
### rAthena Hash

b568f2fb1

### Client Date

2022-04-06

### Server Mode

Pre-Renewal, Renewal

### Result

Skill Show Scale is not showing even tho the skill NPC Earthquake in DB is set to ShowScale = true. See the video below

https://user-images.githubusercontent.com/30449376/196788976-60a59ee1-861f-4646-8ee4-669a5474ea6a.mp4

### Expected Result

The scale of the skill should show in red small squares.

### How to Reproduce

Run your rAthena server, set earthquake skill flag to ShowScale: = true, check in game

### Official Information

https://www.youtube.com/watch?v=kwDGm2lcZ44

### Modifications that may affect results

none

**Comment by vstumpf** [comment]
Do you have the client-side files set up for the skill? iirc there's a client file that controls the size

**Comment by violent01** [comment]
> Do you have the client-side files set up for the skill? iirc there's a client file that controls the size

What is the file that controls those things? Last time I remember I didn't touch anything in the grf or system files and just run it as a default renewal settings and I can see the red AoE. But maybe I forgot something to add.

**Comment by aleos89** [comment]
![image](https://user-images.githubusercontent.com/3521753/197545508-5ff7309e-edb5-4428-ae14-05b7fe3b632d.png)

![image](https://user-images.githubusercontent.com/3521753/197547832-84b7e3db-ca1d-4569-b08e-497d0a27bb6e.png)

Tried a few different skills and they worked for me.

**Comment by violent01** [comment]
I've confirmed this is a client version related issue. Closing this issue now.
