### ISSUE TITLE
Try to send Macro Preview twice client crashed

### ISSUE THREAD

**Issue by kaninhot004** [rathena/rathena#7379]
### rAthena Hash

9bf012d29

### Client Date

2022-04-06

### Server Mode

Renewal

### Result

Enter game -> /macro_preview 1 -> Repeat it until client crashed.

4 servers no red error.

### Expected Result

Client won't crash if repeat preview macro

### How to Reproduce

https://user-images.githubusercontent.com/9493525/197375944-ad885b12-ae65-4a18-95f4-d07647460d12.mp4

**Comment by Lemongrass3110** [comment]
You miss the diff to fix the BMP size. Without the diff the result will be random.
