### ISSUE TITLE
Harmonize(MI_HARMONIZE) BUG, effect status is minus.

### ISSUE THREAD

**Issue by hnomkeng** [rathena/rathena#738]
see vdo test (renewal) : https://youtu.be/uiI2Z_eIxks

effect status is minus.

**Comment by Lemongrass3110** [comment]
Please try to give us as many details as possible.
Thank you!

**Comment by hnomkeng** [comment]
You see effect skill to status character.

**Comment by hnomkeng** [comment]
correct : https://youtu.be/t5oX_IQzcDA
