### ISSUE TITLE
About hell plant (genetic)

### ISSUE THREAD

**Issue by ernestfegarido** [rathena/rathena#739]
try all stats are 1 then try cast it to a player or a mob there is a chance not hitting them. is it normal? im using latest and clean version of rathena. thank you! :)

**Comment by RagnarokNova** [comment]
I'd like to see the test done in rA. I've casted Hell's Plant 10 times in a row on Aegis on a character who isn't moving (Genetic who was casting having all 1 stats) and it didn't miss a single time. Were you trying to hit static or moving targets?

**Comment by aleos89** [comment]
I was unable to confirm this using cb52138.
