### ISSUE TITLE
Can not get reward for reaching 100 base lvl

### ISSUE THREAD

**Issue by Takiusu** [rathena/rathena#7406]
### rAthena Hash

Latest

### Client Date

2021-11-17

### Server Mode

Renewal

### Result

My character reached 3rd job an 100 lvl, but for unknown reason I can't get this reward. Button is not avaiable.
![image](https://user-images.githubusercontent.com/65616872/200126387-27d6cb89-17da-445c-8f22-8b523bd68403.png)

### Expected Result

After getting 100 lvl base, character should get this reward

### How to Reproduce

Idk

### Official Information

I don't have any

**Comment by Balferian** [comment]
@Takiusu I think you can`t get it because reward item is commented.
>   - Id: 200032
    Group: Goal_Level
    Name: The start of another adventure!
    Condition: " BaseLevel == 100 "
    #Rewards:
    #  Item: Rebeginer_Box_100
    Score: 10
