### ISSUE TITLE
List Bug in last revision (2days ago)

### ISSUE THREAD

**Issue by playpsro** [rathena/rathena#741]
revision = lastest clean
client date = 20130807
packet = 45 default

1. Tiger Cannon still drain the enemy sp .
in http://irowiki.org/wiki/Tiger_Cannon , them said "Strikes a single/current target with a self straining blow that will inflict damage to all enemies within the Area of Effect and drain the target's SP."

2. Trap have bug, some player use trap, and i'm move to other side until close display him trap, and i'm back to him, trap is NOT DISPLAYING but TRAP STILL EXIST .

![bugtrap1](https://cloud.githubusercontent.com/assets/15665450/10960836/8fe607e4-83ba-11e5-9cec-234a93a29f4a.jpg)
![bugtrap2](https://cloud.githubusercontent.com/assets/15665450/10960837/8fe74906-83ba-11e5-8545-4aa27b36b7e7.jpg)

3. Spirit Control skill of Sorcerer is different from old rev, i'm try to use wind spirit lvl 2 and spirit control level 1 .
in old rev : your variable cast is reduce ... second (use diamond dust you will be no cast)
in this rev : have a chance to activate cast reduce

4. Dish +20 
- http://ratemyserver.net/index.php?page=re_item_db&item_id=12429
- http://ratemyserver.net/index.php?page=re_item_db&item_id=12430
- http://ratemyserver.net/index.php?page=re_item_db&item_id=12431
- http://ratemyserver.net/index.php?page=re_item_db&item_id=12432
- http://ratemyserver.net/index.php?page=re_item_db&item_id=12433
- http://ratemyserver.net/index.php?page=re_item_db&item_id=12434

Have Bug, if character use this dish die, effect from dish not gone.
in official, if character use dish die, the effect is gone, but if dispel, not gone 
so this is my report, i hope you will give solution to fix it all :)

**Comment by aleos89** [comment]
1. The whole Sura combo skills need to be cleaned up a bit.

2. This is official behavior:
```
// Hunter's traps visibility setting:
// 1: (Official) Many of Hunter's traps are invisible at all times.
//    But any player who see the Hunter laying the trap will be able to see the trap until they move out of sight of it.
//    Although, invisible traps can be revealed through Hunter's Detecting skill.
traps_setting: 1
```

3. I'm not sure what you're talking about with "have a chance to activate cast reduce". It will remove a solid 1 second from fixed cast as long as the skill is active.

4. There are checks already so that those foods/bonuses are not removed from Dispell.

-----
The only valid issue here would be the Tiger Cannon clean up.

**Comment by playpsro** [comment]
foods +20 , in official if character dead , buff is removed. 
but now if character dead, buff not removed. maybe you can check it @aleos89

**Comment by aleos89** [comment]
Can you provide some recent proof? I remember adjusting this before so that they weren't removed in 083cf5d. Rayn had found a video from kRO and a player was in WoE and died and the food was still active.

**Comment by playpsro** [comment]
ah, its update from KRO?
because in idRO (indonesia ragnarok online) its still remove after death but not remove if dispelled

**Comment by nanakiwurtz** [comment]
Beware that the skills from idRO is often different with kRO, for example the Magnificat:
kRO = Double the SP regen, on idRO = Double the HP & SP regen.

**Comment by Historica** [comment]
Its official TC behavior. Read the underlined parts on irowiki page you quote , its clearly said "10% of damage inflicted" which TC inflict AOE damage so every target gets SP removed.

And here is backing proof of that TC did those SP drain on all target.
 http://forums.irowiki.org/showthread.php?t=76650.

"TC lv.1-5 deals dmg in 3*3 but lv.6-10 deals 5*5 area dmg. This skill also drains everyone sp in area as well as hp too (unlike the description or wiki said) so I recommended at lv.6 if you wanna use it for drain enemy sp, forget about dmg in WOE unless you have Meg or TK armor."

**Comment by playpsro** [comment]
okay i will test it again .
thanks for @nanakiwurtz  for your explain, so this is official KRO update dish +20 not remove buff if death/dispell 

and thanks for @Historica  for your explain about tiger cannon too.

and then can i ask about aspd? i have test yesterday.

i'm use http://ratemyserver.net/index.php?iname=18657&page=re_item_db&quick=1&isearch=Search pegasus wing ear.

this item have a script increase aspd 3% . but i have test from agi 1 until agi 200 this item only give 1 ASPD . so anyone here can explain about aspd?

**Comment by Historica** [comment]
iRO and idRO have different aspd formula than kRO. rAthena use kRO aspd formula

Pegasus wing ears are fine while FAW script and DAA enchant script are wrong.
FAW script does not have bonus aspd per 20 base agi.
DAA enchant script all level listed as 4% aspd , -4% delay which are questionable.
