### ISSUE TITLE
setlook shows skills tree

### ISSUE THREAD

**Issue by iMillenium** [rathena/rathena#7411]
### rAthena Hash

Latest

### Client Date

2022-03-04

### Server Mode

Renewal

### Result

When using the setlook command ` setlook LOOK_BASE,JOB_THIEF;` the character obtains the appearance and skill tree of the class;
It is not possible to use skill or put points in skills;
The same action occurs in all jobs

![image](https://user-images.githubusercontent.com/7401604/200246060-1a314512-0fd1-4bc8-a50b-0a4bc85c9531.png)
![image](https://user-images.githubusercontent.com/7401604/200246124-e5aed89f-5281-4501-8066-50ebdb39cea6.png)
![image](https://user-images.githubusercontent.com/7401604/200246188-296c1d8a-0dd8-4595-86ba-3d43c9963edd.png)

### Expected Result

Appearance should change without affecting skill tree.

### How to Reproduce

Put in some script the command `setlook LOOK_BASE (any job)`. 
Activate the function and check skill tree

### Official Information

none

**Comment by secretdataz** [comment]
This is a client limitation.
