### ISSUE TITLE
SO_VARETYR_SPEAR wrong formula!

### ISSUE THREAD

**Issue by Takiusu** [rathena/rathena#7412]
### rAthena Hash

Latest

### Client Date

2021-11-17

### Server Mode

Renewal

### Result

I checked damage of Varetyre Spear on rAthena  and compared that with scrennshotes from kRO sakray
![image](https://user-images.githubusercontent.com/65616872/200264732-da3ad531-2d9c-4632-a904-7a0f5479fb04.png)
![image](https://user-images.githubusercontent.com/65616872/200264749-5db8f8b4-b523-414b-a884-8b12b12c4d36.png)

### Expected Result

Damage from SO_VARETYR_SPEAR should be the same as kRO

### How to Reproduce

Check the formula
case SO_VARETYR_SPEAR:
skillratio += -100 + (2 * sstatus -> int_ + 150 * ((sd ? pc_checkskill(sd, SO_STRIKING) : 0) + (sd ? pc_checkskill(sd, SA_LIGHTNINGLOADER) : 0)) + sstatus -> int_ * skill_lv / 2) / 3;

### Official Information

Screenshotes from Sakray

**Comment by Takiusu** [comment]
I checked the formula again, everything is correct. Problem probably is related to post-processing of damage.

**Comment by Balferian** [comment]
Can`t confirm it.
There small differents with stats, but all work correct.
Rathena
![image](https://user-images.githubusercontent.com/16213511/200316558-6fb20e81-3f09-4a10-bb94-ed1c99fd2685.png)
![image](https://user-images.githubusercontent.com/16213511/200316659-3e4a7cb3-79da-41c7-85ae-a5158d0a7115.png)
kRo
![image](https://user-images.githubusercontent.com/16213511/200317402-585c0f1c-266e-4bfe-b3e0-bf0dfa40c32a.png)

**Comment by LadyNanuia** [comment]
Did you max out the synergy? you need lightning loader iirc to increase teh damage of Varetyr spear.

**Comment by aleos89** [comment]
Fixed in #7425.
