### ISSUE TITLE
Expand hideonnpc/hideoffnpc

### ISSUE THREAD

**Issue by violent01** [rathena/rathena#7418]
### Is your request related to a missing official feature?

No

### Describe the solution you'd like

*hideonnpc/hideoffnpc should be expanded just like *cloakonnpcself/cloakoffnpcself script commands. The reason for this is if you're using cloakonnpcself/cloakoffnpcself and someone wants to make some script in which the triggering character is the only one who can see the NPC and at the same time uses *npcwalkto, the NPC is in the status of invisibility when moving to the coordinates. So basically, the NPC is invisible during movement even tho it is there while hideonnpc/hideoffnpc works fine and you can see the actual NPC during movement but the problem is other players in the area can also see the said NPC.

**Comment by Atemo** [comment]
Post an example NPC script please

**Comment by violent01** [comment]
@Atemo okay let me write a quick example and record a video also.

**Comment by violent01** [comment]
@Atemo 
This is for the hideonnpc script:

prontera,109,159,0	script	#dummy test	HIDDEN_WARP_NPC,3,3,{
	end;

OnTouch:
	hideoffnpc("test#test1");
	donpcevent "test#test1::OnWalk";
	end;

prontera,109,159,4	script	test#test1	10516,{

OnWalk:
	npcwalkto 119,159;
	end;

OnInit:
	hideonnpc();
	end;
}

and this is for the cloaknpcself script:

prontera,109,159,0	script	#dummy test	HIDDEN_WARP_NPC,3,3,{
	end;

OnTouch:
	cloakoffnpcself("test#test1");
	donpcevent "test#test1::OnWalk";
	end;
}

prontera,109,159,4	script	test#test1	10515,{

OnWalk:
	npcwalkto 119,159;
	end;

OnInit:
	cloakonnpc();
	end;
}

This is for hideonnpc sample video:
https://user-images.githubusercontent.com/30449376/200636288-9a4cc877-58a9-4ae5-901b-48fa378eaf03.mp4

This is for cloakonnpcself sample video:

https://user-images.githubusercontent.com/30449376/200636493-e28fc2f4-f804-42aa-ab8a-4a13829c2272.mp4

**Comment by Atemo** [comment]
Closing this. The behavior you want can be achieved using existing commands afaik. Please use the forum!
