### ISSUE TITLE
Issue Related Dynamic NPC 

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#7419]
### rAthena Hash

3515285f4360239fbb1d31393ea2a0ac53a4dc59

### Client Date

2021-11-03

### Server Mode

Renewal

### Result

Map Server Show This Error

```
(11/09/2022 06:24:38) [ Error ] : delete_timer error : function mismatch 0x7248d0(connect_check_clear) != 0x57bfd6(npc_dynamicnpc_removal_timer)
(11/09/2022 06:24:39) [ Error ] : delete_timer error : function mismatch 0x7248d0(connect_check_clear) != 0x57bfd6(npc_dynamicnpc_removal_timer)
```

### Expected Result

No Error

### How to Reproduce

Just using Dynamic NPC 2 times until NPC disapear, then use @mapexit

### Official Information

N/A

### Modifications that may affect results

This is my NPC

```
prontera,154,187,4	script	Information#prt	756,{
callfunc "F_Information";
OnInit:
	waitingroom "Information",0;
end;
}

function	script	F_Information	{
mes "Test";
end;
}

-	script	InformationCommand	-1,{
OnAtInformation:
duplicate_dynamic "Information#prt";
end;

OnInit:
	bindatcmd "information",strnpcinfo(3)+"::OnAtInformation";
	bindatcmd "info",strnpcinfo(3)+"::OnAtInformation";
end;
}
```

then i call using command

first call dynamic NPC until NPC disapear, then

call again dynamic NPC until NPC disapear,

then

use @mapexit

**Comment by Lemongrass3110** [comment]
```
Modifications that may affect results

No response
```
I dont trust this answer.

**Comment by mazvi** [comment]
sure no modification

Just using Dynamic NPC 2 times:

first call dynamic NPC until NPC disapear, then 

call again dynamic NPC until NPC disapear, 

then 

use @mapexit

**Comment by Lemongrass3110** [comment]
```
[Info]: Character 'test' logged off.
[Status]: Terminating...
[Status]: Cleaned up 1148 maps.
[Status]: Close Map DB Connection....
[Status]: Close Log DB Connection....
[Status]: Finished.
[Info]: Memory manager: No memory leaks found.

Map-Server has shutdown successfully.
Restarting in 15 seconds, press Ctrl+C to cancel.
```

**Comment by mazvi** [comment]
Can you test with my script?

```
prontera,154,187,4	script	Information#prt	756,{
callfunc "F_Information";
OnInit:
	waitingroom "Information",0;
end;
}

function	script	F_Information	{
mes "Test";
end;
}

-	script	InformationCommand	-1,{
OnAtInformation:
duplicate_dynamic "Information#prt";
end;

OnInit:
	bindatcmd "information",strnpcinfo(3)+"::OnAtInformation";
	bindatcmd "info",strnpcinfo(3)+"::OnAtInformation";
end;
}
```

**Comment by Lemongrass3110** [comment]
```
[Status]: Shutting down...
[Info]: Character 'test' logged off.
[Status]: Terminating...
[Status]: Cleaned up 1148 maps.
[Status]: Close Map DB Connection....
[Status]: Close Log DB Connection....
[Status]: Finished.
[Info]: Memory manager: No memory leaks found.

Map-Server has shutdown successfully.
Restarting in 15 seconds, press Ctrl+C to cancel.
```

I only modified the sprite of your NPC, as i dont seem to have the other one.
![grafik](https://user-images.githubusercontent.com/3517879/201181419-1ff566c6-91cd-4049-8b97-725039c7bfbb.png)

Closing this now. Fix your customizations.

**Comment by mazvi** [comment]
i never modified src. i just remembered i also logged out when dynamyc npc was still there. 

100% I never modified the src. but maybe related to other npc scripts. Unfortunately I don't have a clue.

**Comment by violent01** [comment]
I also tested your issue and your script and there is no error. Try to do it on a fresh rA; if it does not exist, then your source has the problem.

**Comment by mazvi** [comment]
Are you using linux? because on linux there is an error when compiling related to dynamic npc, I think this is relevant

https://github.com/rathena/rathena/issues/7417
