### ISSUE TITLE
Eden: Catalogue Wizard

### ISSUE THREAD

**Issue by cydh** [rathena/rathena#742]
Someone sent me PM about this.
About Eden 2nd floor, Tutorial Instructor. When asked to buy Window Shopper Catalogue (12850?) in quest window (this is related with translation, iRO?), the NPC is located in South Prontera, iRO: https://forums.warpportal.com/index.php?/topic/149733-r-eden-tutorial-quest-2nd-floor/

Our script NPC, says so
````
				mes "[Tutorial Instructor]";
				mes "The ^006400Universal Silver Catalog^000000";
				mes "can be obtained from";
				mes "the ^0000FFCatalogue Wizard^000000";
				mes "that is located in South Prontera.";
				next;
````
````
			mes "[Tutorial Instructor]";
			mes "You can get the";
			mes "^006400Universal Silver Catalog^000000";
			mes "from the ^0000FFCatalogue Wizard^000000";
			mes "who is located in Prontera.";
			next;
````

But, in our script, the NPC location is in 2nd floor in Eden group, not in South Prontera.
````
moc_para01,22,16,5	script	Catalog Magician#catal01	704,{
//...
		mes "Ok, here you go.";
		set Zeny, Zeny - .@sell;
		getitem 12580,.@input; //Vending_Search_Scroll
		close;
//...
}
````

So, which one do we follow?
If originally (kRO) is in Eden group, then change the what NPC says.
If follow the iRO, change the Catalgoue NPC location.

**Comment by cydh** [comment]
@euphyy @Atemo

**Comment by exneval** [comment]
kRO is in eden group :
http://www.divine-pride.net/database/npc/24640/catalog-magician

**Comment by Atemo** [comment]
Note: I used the lua navigation as ref
