### ISSUE TITLE
Some items are missing

### ISSUE THREAD

**Issue by Takiusu** [rathena/rathena#7426]
### rAthena Hash

Latest

### Client Date

2021-11-17

### Server Mode

Renewal

### Result

![image](https://user-images.githubusercontent.com/65616872/201090114-f5b35fb7-6a7d-424b-a5e9-2866e8607b73.png)

### Expected Result

Getting this items from reward box

### How to Reproduce

Add these items

### Official Information

https://www.divine-pride.net/database/item/11614
https://www.divine-pride.net/database/item/23485
https://www.divine-pride.net/database/item/23505
https://www.divine-pride.net/database/item/23506

**Comment by Balferian** [comment]
It`s a part of https://github.com/rathena/rathena/pull/7414.
