### ISSUE TITLE
Defender Paladin

### ISSUE THREAD

**Issue by ernestfegarido** [rathena/rathena#743]
why is that acid bomb is not affected by the damage reduction of Defender? im using latest and clean rev. running on renewal mode.

**Comment by anacondaqq** [comment]
Dear @ernestfegarido before posting like that read official description of skills, for example not bad example: http://irowiki.org/wiki/Acid_Bomb

You do not provide any extra information what can help devs to understand you, and maybe help you to fix it.

When you will report about the bug at next time, please try to get maximum as you can information, like:

1. your current rAthena hash (exactly, i'm talking about hash, not like "this is last revision bla bla bla")
2. Tell how it must be, and how it is
3. make some extra proofs & screenshots.


WHY?
1. if you will tell many information -> it's more better, then tell nothing
2. more info -> people will understand what is wrong and how it must be
3. bugs will be resolved much quicker
4. nobody will do your job

**Comment by Badarosk0** [comment]
Confirmed in the latest version of the emulator . Unfortunately I do not have a source of kRO to confirm.

**Comment by MrAntares** [comment]
anacondaqq already posted the answer under the link:
"Bypasses:
Defending Aura"

**Comment by aleos89** [comment]
http://imgur.com/a/fOSEj

My test show that the damage is the same for Acid Bomb when Defending Aura is active, and not active.
