### ISSUE TITLE
VIP char are still accessible after expiry.

### ISSUE THREAD

**Issue by ecdarreola** [rathena/rathena#7431]
### rAthena Hash

3f7155bf8

### Client Date

2020-03-04

### Server Mode

Pre-Renewal

### Result

VIP char is still accessible even if status is already expired.

### Expected Result

VIP char should be locked and cannot be used once VIP is expired.

### How to Reproduce

1. Compiled the server in pre-renewal.
2. Create account and activate VIP
3. Create character on VIP slot (locked slot)
4. Wait VIP to expire
5. Access VIP char

![Uploading image.png…]()

### Official Information

VIP system

### Modifications that may affect results

N/A

**Comment by ecdarreola** [comment]
I don't know what happened to the attached pic but it is not showing. Please see below.

![image](https://user-images.githubusercontent.com/48939874/201478148-d05ad8d2-fe5d-4e74-91bf-ab3703a86eaf.png)

**Comment by violent01** [comment]
Isn't that how official VIP system works? When you buy VIP membership, it unlocks the locked character slots and when it expires it just locks it down but the character you created there is still usable.

**Comment by ecdarreola** [comment]
> Isn't that how official VIP system works? When you buy VIP membership, it unlocks the locked character slots and when it expires it just locks it down but the character you created there is still usable.

Oh is it? Maybe I recalled wrong. What I can remember is that when your VIP expires those character is inaccessible unless you are VIP again. Apologies if I misunderstood the current official behavior. My memories don't serve me right. Thanks!
