### ISSUE TITLE
Bug Skills, Skill doesnt want to end when deadactive, even the effect of the skills is turned on again.

### ISSUE THREAD

**Issue by alton1** [rathena/rathena#744]
I got problem with my server.
when job use their self support skills the effect doesnt want to end, event it was actived again.

Example : 
-when sniper use true sight. aspd from 164 become 165, but at the time true sight deadactive the aspd wouldnt back to normal, instead became increase to 170.

-assX use cloacking. Luk from 28 become 56, but at the time cloacking deadactive the luk still on 56 value, and the worse is movement speed become faster.

it's kindda the skills effect wont to end, although the skills were deadactive, and even the skills turned on again to twice. these bug will end when the player got warp or tele or use the same skills again.

anyone have a solution to me ?

**Comment by alton1** [comment]
@euphyy @Atemo

**Comment by nanakiwurtz** [comment]
Which git hash are you on? Pre-RE/RE? Client date? Source mods?
We can't help you if you don't even provide such information.

**Comment by alton1** [comment]
i using pre-re , my client date 2012 04 10, using rathena git version with rev code 11427. @nanakiwurtz

**Comment by Lemongrass3110** [comment]
@aleos89 could this be related to your recent commits?

**Comment by alton1** [comment]
@Lemongrass3110 nope, i hv just builded my server, and i guess i didnt compile my server yet. i though it caused by src?

**Comment by aleos89** [comment]
Just tested with a clean clone of rAthena. Tested both renewal and pre-renewal. Used various skills that give buffs. My stats were increase for the duration of the status, and were removed once the status ended. Sounds like something on your end.
