### ISSUE TITLE
itemlink not working some exe

### ISSUE THREAD

**Issue by zdurexz** [rathena/rathena#7441]
### rAthena Hash

-

### Client Date

20200304

### Server Mode

Pre-Renewal, Renewal

### Result

itemlink not working on before 20200724
@mobinfo 1002
![image](https://user-images.githubusercontent.com/59825922/202196144-1c8a3e02-f753-4a16-b9c6-c7a4b7b164dc.png)

@iteminfo 1201
![image](https://user-images.githubusercontent.com/59825922/202196498-04ffac91-6316-4192-8c9a-f734e19f8c1b.png)

### Expected Result

@mobinfo
![image](https://user-images.githubusercontent.com/59825922/202196707-b8c9d628-d162-44e6-839c-759564bde242.png)

@iteminfo
![image](https://user-images.githubusercontent.com/59825922/202196763-35cfee91-8ced-4685-afdb-145787fdccb9.png)

### How to Reproduce

-

### Official Information

-

### Modifications that may affect results

Before 
```
#if PACKETVER_MAIN_NUM >= 20200916 || PACKETVER_RE_NUM >= 20200724
	const std::string start_tag = "<ITEML>";
	const std::string closing_tag = "</ITEML>";
#else // PACKETVER >= 20100000
	const std::string start_tag = "<ITEMLINK>";
	const std::string closing_tag = "</ITEMLINK>";
```
to
```
#if PACKETVER_MAIN_NUM >= 20200916 || PACKETVER_RE_NUM >= 20200724
	const std::string start_tag = "<ITEML>";
	const std::string closing_tag = "</ITEML>";
#elif PACKETVER >= 20151104
	const std::string start_tag = "<ITEML>";
	const std::string closing_tag = "</ITEML>";
#else // PACKETVER >= 20100000
	const std::string start_tag = "<ITEMLINK>";
	const std::string closing_tag = "</ITEMLINK>";
#endif
```

**Comment by zdurexz** [comment]
> Working for me @mobinfo 1011, client 2022-04-06 ![image](https://user-images.githubusercontent.com/98105181/202208445-d6a690f4-f5ef-479f-9c38-076184d82fee.png)

client less than 20200724 can't working

**Comment by Aruar** [comment]
i managed to solve it, i don't know if it will solve there too:

change:

#if PACKETVER_MAIN_NUM >= 20200916 || PACKETVER_RE_NUM >= 20200724
    const std::string start_tag = "<ITEML>";
    const std::string closing_tag = "</ITEML>";
#else // PACKETVER >= 20100000
    const std::string start_tag = "<ITEMLINK>";
    const std::string closing_tag = "</ITEMLINK>";
#endif

to:

#if PACKETVER_MAIN_NUM >= 20200916 || PACKETVER_RE_NUM >= 20200724
    const std::string start_tag = "<ITEMLINK>";
    const std::string closing_tag = "</ITEMLINK>";
#else // PACKETVER >= 20100000
    const std::string start_tag = "<ITEML>";
    const std::string closing_tag = "</ITEML>";
#endif

**Comment by GMNoob** [comment]
> ### rAthena Hash
> 
> ### Client Date
> 20200304
> 
> ### Server Mode
> Pre-Renewal, Renewal
> 
> ### Result
> itemlink not working on before 20200724 @mobinfo 1002 ![image](https://user-images.githubusercontent.com/59825922/202196144-1c8a3e02-f753-4a16-b9c6-c7a4b7b164dc.png)
> 
> @iteminfo 1201 ![image](https://user-images.githubusercontent.com/59825922/202196498-04ffac91-6316-4192-8c9a-f734e19f8c1b.png)
> 
> ### Relevant Log Output
> _No response_
> 
> ### Expected Result
> @mobinfo ![image](https://user-images.githubusercontent.com/59825922/202196707-b8c9d628-d162-44e6-839c-759564bde242.png)
> 
> @iteminfo ![image](https://user-images.githubusercontent.com/59825922/202196763-35cfee91-8ced-4685-afdb-145787fdccb9.png)
> 
> ### How to Reproduce
> 
> ### Official Information
> 
> ### Modifications that may affect results
> Before
> 
> ```
> #if PACKETVER_MAIN_NUM >= 20200916 || PACKETVER_RE_NUM >= 20200724
> 	const std::string start_tag = "<ITEML>";
> 	const std::string closing_tag = "</ITEML>";
> #else // PACKETVER >= 20100000
> 	const std::string start_tag = "<ITEMLINK>";
> 	const std::string closing_tag = "</ITEMLINK>";
> ```
> 
> to
> 
> ```
> #if PACKETVER_MAIN_NUM >= 20200916 || PACKETVER_RE_NUM >= 20200724
> 	const std::string start_tag = "<ITEML>";
> 	const std::string closing_tag = "</ITEML>";
> #elif PACKETVER >= 20151104
> 	const std::string start_tag = "<ITEML>";
> 	const std::string closing_tag = "</ITEML>";
> #else // PACKETVER >= 20100000
> 	const std::string start_tag = "<ITEMLINK>";
> 	const std::string closing_tag = "</ITEMLINK>";
> #endif
> ```

which file was modified for this?

**Comment by dynamitejustice** [comment]
For what it's worth, Ive tried both on client 20151104 and neither are working.  I can attach screenshots before and after changes if it helps.

**Comment by Leemonn** [comment]
Hello, copying what I wrote on my issue #7529.

Client 20151104 uses `<ITEM></ITEM>`. I will make a PR later today. Will need more info on what client versions use this tag.

**Comment by Lemongrass3110** [comment]
When testing please make sure to test WITH card info etc.
From what I remember the <ITEM> one was only intended to be used in NPCs, so inside the "mes" command.

**Comment by JnmVirtue** [comment]
> Hello, copying what I wrote on my issue #7529.
> 
> Client 20151104 uses `<ITEM></ITEM>`. I will make a PR later today. Will need more info on what client versions use this tag.

Using that still won't work for 20151104, I tried it. Afaik, that client date has a buggy itemlink feature. When you use it on mes, it's messed up. Only works properly when you shift+click an item.

**Comment by dynamitejustice** [comment]
Yup just added an extra elif to use <ITEM></ITEM> if the PACKETVER is exactly 20151104 and that doesnt work either.  Was this client just at a weird time when this feature was implemented?

**Comment by Leemonn** [comment]
I was able to make it work but I don't remember what format I used for the items. I was able to link items manually in the chat by writing using the tags `<ITEM></ITEM>` but I'm not sure what format I used for the item. I thought I copied what I got from `@ii` but it seems that I did something different. Sadly I didn't have chat logs enabled, I will investigate today to see if I can replicate this

**Comment by Leemonn** [comment]
I found it! How exciting hahah.

Right now the itemlink function uses `(00` for the cards. The 20151104 client uses `'00` instead.

So for example this is what rAthena outputs (including the elif change from above to use <item> instead of <iteml>):
`<ITEM>000000h9(00(00(00(00</ITEM>` This doesn't work.

And this is how it should be:
`<ITEM>000000h9'00'00'00'00</ITEM>` This works

**Comment by JnmVirtue** [comment]
> 

so what did you change? maybe the whole itemlink script function could work with the 20151104 client with that. I'm interested.

**Comment by Leemonn** [comment]
I didn't change anything yet, only wrote manually on the chat. But to fix it you would need to edit the `ItemDatabase::create_item_link` function. (I will try to do a PR later once I'm 100% it works)
For 20151104:
Card separator = `'`
Refine separator = `%`

Not sure about the option separators yet

**Comment by JnmVirtue** [comment]
> I didn't change anything yet, only wrote manually on the chat. But to fix it you would need to edit the `ItemDatabase::create_item_link` function. (I will try to do a PR later once I'm 100% it works) For 20151104: Card separator = `'` Refine separator = `%`
> 
> Not sure about the option separators yet

did you still use this:
`#elif PACKETVER >= 20151104
	const std::string start_tag = "<ITEM>";
	const std::string closing_tag = "</ITEM>";`

**Comment by dynamitejustice** [comment]
I made a quick change and recompiling now just to do some testing as well.  Was able to get a successful link to manually appear thanks to @Leemonn 's note of `'` instead of `(`.  Yup @JnmVirtue I added another elif section of:
`#elif PACKETVER == 20151104 const std::string start_tag = "<ITEM>"; const std::string closing_tag = "</ITEM>";`
but Im sure there will be a much more elegant solution for all of this as I'm not versed in C++.

**Comment by Leemonn** [comment]
A few more changes that need to be made:
`optval_sep = +`
`optid_sep = )`
`optpar_sep = *`

Will make a PR in a few minutes, need to make a clean branch

**Comment by Leemonn** [comment]
Done! you can test it in the meantime by copying the changes made in the PR. That will help find bugs (if any).

**Comment by JnmVirtue** [comment]
> Done! you can test it in the meantime by copying the changes made in the PR. That will help find bugs (if any).

thanks, will check on it in a bit.

**Comment by Daraen1** [comment]
![image](https://user-images.githubusercontent.com/75265726/210869334-231e652e-2abe-4d90-b2e3-2fcf6f008eb7.png)
Not working on 20180620 Packetver

**Comment by dynamitejustice** [comment]
> Done! you can test it in the meantime by copying the changes made in the PR. That will help find bugs (if any).

Im recompiling with your changes now!  Thank you and I'll letcha know what I find as well.

> ![image](https://user-images.githubusercontent.com/75265726/210869334-231e652e-2abe-4d90-b2e3-2fcf6f008eb7.png) Not working on 20180620 Packetver

@Leemonn 's PR just addresses 20151104 clients having issues with itemlink as the solutions at the beginning of the thread didnt take this client into account.  Did the earlier solutions not work for you?

**Comment by Leemonn** [comment]
> ![image](https://user-images.githubusercontent.com/75265726/210869334-231e652e-2abe-4d90-b2e3-2fcf6f008eb7.png) Not working on 20180620 Packetver

@Daraen1 My PR only addresses issues with 20151104

Please do this so that I can fix it for your client version:

1. Enable chat logging
2. do `@item2 1734 1 1 5 0 4004 4004 4004 4004`
3. `shift+click` the item to link it in the chat
4. Go to your database and send me the message logged in the `chatlog` table

**Comment by Daraen1** [comment]
@Leemonn 
![image](https://user-images.githubusercontent.com/75265726/210872497-d3922b6e-441c-4f14-9158-b87342597617.png)
![image](https://user-images.githubusercontent.com/75265726/210872527-fabc66b2-3732-4a74-b122-4cabdd2f90ac.png)

**Comment by Leemonn** [comment]
> @Leemonn ![image](https://user-images.githubusercontent.com/75265726/210872497-d3922b6e-441c-4f14-9158-b87342597617.png) ![image](https://user-images.githubusercontent.com/75265726/210872527-fabc66b2-3732-4a74-b122-4cabdd2f90ac.png)
> 
> EDIT: Wait i didn't test with item2
> 
> EDIT2:
> 
> 0000y1rY%05&00(12A(12A(12A(12A
> 
> ![image](https://user-images.githubusercontent.com/75265726/210872841-64670ecc-fcf5-45c7-bdd1-337c42198d36.png)

@Daraen1 please try with this change on `itemdb.cpp`

Replace: `#if PACKETVER_MAIN_NUM >= 20200916 || PACKETVER_RE_NUM >= 20200724`
With: `#if PACKETVER_MAIN_NUM >= 20200916 || PACKETVER_RE_NUM >= 20200724 || PACKETVER_MAIN_NUM  == 20180620 || PACKETVER_RE_NUM == 20180620`

Recompile and try using `@mi` and `@ii` again.

(I know it's horrible, it's only for testing purposes)

**Comment by dynamitejustice** [comment]
It looks like the fix is almost there.  There's double up slot info text (like in your <Knife[4]>[4] but this is already substantially better!

**Comment by Leemonn** [comment]
> @Leemonn ![image](https://user-images.githubusercontent.com/75265726/210874171-0370650c-7939-4556-be46-8304d03fdebf.png) it works!

@Daraen1  Nice, thank you for helping. I will add this on my PR



> It looks like the fix is almost there. There's double up slot info text (like in your <Knife[4]>[4] but this is already substantially better!

@dynamitejustice  Can you post a screenshot?

> Worked for the most part for me, here's what I've got. ![image](https://user-images.githubusercontent.com/115641903/210874425-a30a48da-84fb-44b0-9926-b42e322e6f35.png)

@JnmVirtue Are you using 20151104? If you are then I think you missed 1 change from my PR. This one 
![image](https://user-images.githubusercontent.com/47922762/210874781-04a791ec-233c-42b2-bc6b-cc184b555471.png)

**Comment by dynamitejustice** [comment]
@Leemonn I was just referring to your screenshot where it shows the linked <Knife[4]> but also shows [4] after that.  In comparing that to the top of the thread's screenshots, it shows <Gemmed Sallet[1]> without a second [1] after.

**Comment by JnmVirtue** [comment]
> 

![image](https://user-images.githubusercontent.com/115641903/210875321-08479c38-89e9-4463-8d3e-b882a76d1f18.png)
it's there. double checked it.

**Comment by Daraen1** [comment]
same issue @dynamitejustice 

![image](https://user-images.githubusercontent.com/75265726/210875543-f07b3fb4-165c-4ff8-a91d-fd85eecd8209.png)

**Comment by Leemonn** [comment]
> @Leemonn I was just referring to your screenshot where it shows the linked <Knife[4]> but also shows [4] after that. In comparing that to the top of the thread's screenshots, it shows <Gemmed Sallet[1]> without a second [1] after.

> same issue @dynamitejustice
> 
> ![image](https://user-images.githubusercontent.com/75265726/210875543-f07b3fb4-165c-4ff8-a91d-fd85eecd8209.png)

@dynamitejustice @Daraen1  That bug is not related to itemlink. It's an issue with `@ii` and `@mi`. I can do a PR to fix it after the current one gets approved.

@JnmVirtue Are you using renewal version? if you are then try doing this:
Replace `#if PACKETVER_MAIN_NUM != 20151104` with `#if PACKETVER_MAIN_NUM != 20151104 && PACKETVER_RE_NUM != 20151104` and try again

**Comment by JnmVirtue** [comment]
> 

2015-11-04aRagexe.exe is what I've got.

It kinda works when I used below as a test.
`dispbottom "+10 Knife [3] : "+itemlink(1201,10)+"";` 
![image](https://user-images.githubusercontent.com/115641903/210876276-28c4abc9-353e-468b-aba6-2f1d964cc641.png)

![image](https://user-images.githubusercontent.com/115641903/210876800-a234afa6-7287-4496-98b5-b34b9416ebbf.png)

<ITEM>000021jn'00'00'00</ITEM>
<ITEM>000021jn%0a'135'135'135'00</ITEM>

**Comment by Leemonn** [comment]
> > 
> 
> 2015-11-04aRagexe.exe is what I've got.
> 
> It kinda works when I used below as a test. `dispbottom "+10 Knife [3] : "+itemlink(1201,10)+"";` ![image](https://user-images.githubusercontent.com/115641903/210876276-28c4abc9-353e-468b-aba6-2f1d964cc641.png)
> 
> ![image](https://user-images.githubusercontent.com/115641903/210876800-a234afa6-7287-4496-98b5-b34b9416ebbf.png)
> 
> `<ITEM>000021jn'00'00'00</ITEM>` `<ITEM>000021jn%0a'135'135'135'00</ITEM>`

@JnmVirtue Nice! it works now :D

**Comment by Leemonn** [comment]
> > 
> 
> still doesn't. But, I didn't add the && PACKETVER_RE_NUM != 20151104 part yet since I'm not using a RagRe exe ![image](https://user-images.githubusercontent.com/115641903/210879156-f9756c27-7db7-4234-b94d-e494ead9d85b.png) But I think I found the issue on my side
> 
> Fixed my own issue lol. Got the same as the others.
> 
> ![image](https://user-images.githubusercontent.com/115641903/210880214-b48443ba-20b7-4288-9691-784fe879a83d.png)
> 
> ![image](https://user-images.githubusercontent.com/115641903/210881793-fc83cd5e-8594-4f3e-a8f9-8585741f2880.png)

@JnmVirtue Nice!

**Comment by Daraen1** [comment]
i find for @mi in atcommand.cpp (mobinfo) :

`if (id->slots) {
				if (battle_config.feature_itemlink == 1)
					sprintf(atcmd_output2, " - %s  %02.02f%%", item_db.create_item_link(id->nameid).c_str(), (float)droprate / 100);
				else
					sprintf(atcmd_output2, " - %s[%d]  %02.02f%%", item_db.create_item_link(id->nameid).c_str(), id->slots, (float)droprate / 100);
			}
			else
				sprintf(atcmd_output2, " - %s  %02.02f%%", item_db.create_item_link(id->nameid).c_str(), (float)droprate / 100);`

![image](https://user-images.githubusercontent.com/75265726/210899774-4145d0ef-863a-41a7-b3dd-22ac19dbc5e5.png)

**Comment by Leemonn** [comment]
> i find for @mi in `atcommand.cpp` (mobinfo) :
> 
> ```
> if (id->slots) {
>     if (battle_config.feature_itemlink == 1)
>            sprintf(atcmd_output2, " - %s  %02.02f%%", item_db.create_item_link(id->nameid).c_str(), (float)droprate / 100);
>     else
> 	   sprintf(atcmd_output2, " - %s[%d]  %02.02f%%", item_db.create_item_link(id->nameid).c_str(), id->slots, (float)droprate / 100);
> }
> else
>      sprintf(atcmd_output2, " - %s  %02.02f%%", item_db.create_item_link(id->nameid).c_str(), (float)droprate / 100);
> ```
> 
> ![image](https://user-images.githubusercontent.com/75265726/210899774-4145d0ef-863a-41a7-b3dd-22ac19dbc5e5.png)

@Daraen1 I'm working on a PR to fix that and other parts of code that use item linking as well. 

Also will:
- Implement some changes like appending `[0]` when the item has no slot (so you can easily differentiate equipment with no slots from other items), but I'm not sure if that part will be approved.
- Add formatting for when itemlink is disabled, like this: `+<refine> <item_name> [<slots>]`. For example: `+9 Sword [3]`. But again, I'm not sure if that will be approved.
- Improve the performance, not sure if it will be noticeable but still, it removes some redundant calls that happened everytime `create_item_link` was called.

I didn't check other client versions, does any of the other clients append `[0]` to the itemlink name for equipment with no slots?

**Comment by JnmVirtue** [comment]
so to update, made some changes with @mobinfo, @iteminfo and @whodrops got it to this
![image](https://user-images.githubusercontent.com/115641903/210935835-1c4746de-27bc-404d-823b-7af7f72e1c4d.png)

![image](https://user-images.githubusercontent.com/115641903/210936125-bff9c31c-6d6a-4f52-b2c3-914f438ef024.png)


@mobinfo:
```
/*==========================================
 * Show Monster DB Info   v 1.0
 * originally by [Lupus]
 *------------------------------------------*/
ACMD_FUNC(mobinfo)
if (id->slots)
				sprintf(atcmd_output2, " - %s  %02.02f%%", item_db.create_item_link( id->nameid ).c_str(), (float)droprate / 100);
			else
				sprintf(atcmd_output2, " - %s  %02.02f%%", item_db.create_item_link( id->nameid ).c_str(), (float)droprate / 100);
```

@iteminfo:
```
/*==========================================
 * Show Items DB Info   v 1.0
 * originally by [Lupus]
 *------------------------------------------*/
ACMD_FUNC(iteminfo)
sprintf(atcmd_output, msg_txt(sd,1277), // Item: '%s'/'%s'[%d] (%u) Type: %s | Extra Effect: %s
item_data->name.c_str(), item_db.create_item_link( item_data->nameid ).c_str(),item_data->nameid,
```

@whodrops:
```
/*==========================================
 * Show who drops the item.
 *------------------------------------------*/
ACMD_FUNC(whodrops)
printf(atcmd_output, msg_txt(sd,1285), item_db.create_item_link( id->nameid ).c_str(), id->nameid); // Item: '%s'[%d] (ID:%u)
```

All of this still on 20151104

**Comment by Daraen1** [comment]
So add a check of battle_config is purely useless here ?
Waiting for a PR in any case. I don't want to surcharge the topic.

**Comment by JnmVirtue** [comment]
> > So add a check of battle_config is purely useless here ? Waiting for a PR in any case. I don't want to surcharge the topic.
> 
> I'm fixing that in my PR as well, just waiting for more input from users to let me know if their ITEMLINK is working or not. Will probably make the final commit tomorrow. It's in draft mode right now #7532

I was wondering if the itemlink could be applied to itemdrop announce and box announces too. is it possible?

**Comment by Lemongrass3110** [comment]
I will close the conversation in this issue now.
Please stay on topic.
