### ISSUE TITLE
Critical not show as yellow text

### ISSUE THREAD

**Issue by kaninhot004** [rathena/rathena#7445]
### rAthena Hash

cc5770eda

### Client Date

2022-04-06

### Server Mode

Renewal

### Result

https://user-images.githubusercontent.com/9493525/202463194-6f62be8b-c117-46fe-ae1a-d0e96d3f366b.mp4

See in video when luk was high it was always critical but show in incorrected way.

### Expected Result

Critical show in yellow text like normal.

### How to Reproduce

Try any character with luk 30000 you can see critical was white text display.

### Official Information

Yellow text when critical

**Comment by bgamez23** [comment]
are  you using custom damage font?

**Comment by eppc0330** [comment]
Check #6639.
I guess there's two situations this bug appears.

1. Check if mob has DAMAGEMOTION line in mob_db.yml.
If not, add it in. Then will be solved.

2. Check if you have used command @reloadmobdb. All mobs in map will lose ```damagemotion``` right after @reloadmobdb.
In this case you should kill mobs. After respawn this will be fixed.
