### ISSUE TITLE
Some random option appear invisible on item

### ISSUE THREAD

**Issue by Abszoluto** [rathena/rathena#7447]
### rAthena Hash

https://github.com/rathena/rathena/tree/master

### Client Date

2021-11-03 

### Server Mode

Pre-Renewal, Renewal

### Result

When I use random options randomly dropping the amount of options, some options are in random slots.
This bug happens when slots are filled with space between them.
Example:
Item:
- Random option in slot 0
- Random option in slot 2

The random option in slot 2 will be invisible. The item will say it has 2 random options but the random option in slot 2 will be invisible.

Image:

![image](https://user-images.githubusercontent.com/45849310/202864485-0f8d5f44-7be0-4b70-aea4-f7dda2f991e9.png)
![image](https://user-images.githubusercontent.com/45849310/202864494-e6527dbe-b27c-4d94-93b0-e3c507ec96e8.png)

### Expected Result

N/A

### How to Reproduce

At the item_randomopt_group.yml, use the following configuration on a group (to get the number of options random, instead of item always drop with 3 options):
![image](https://user-images.githubusercontent.com/45849310/202864632-e3af74bf-9b1f-44f2-bc7e-aad1b950d1b2.png)

### Official Information

N/A

### Modifications that may affect results

Make random options appear in consecutive slots, for example:
1 random option: On slot 0
2 random options: On slot 0 and slot 1
3 random options: On slot 0, slot 1 and slot 2
... etc

**Comment by LadyNanuia** [comment]
This is also controlled client side, you need to make sure the LUA files matches in the client or it'll be bugged, not sure if this is what youre running into.

**Comment by Abszoluto** [comment]
All my client files and server files are fine. I talked to Lemongrass and Stolao on discord and we found out that the issue is that the options need to be on consecutive slots.
In the image, i changed on sql and put a random option on the slot missing and the 3 options appeared normally

**Comment by LadyNanuia** [comment]
> All my client files and server files are fine. I talked to Lemongrass and Stolao on discord and we found out that the issue is that the options need to be on consecutive slots. In the image, i changed on sql and put a random option on the slot missing and the 3 options appeared normally

oh i see, im sorry then i was just trying to help, i had this issue with my server with client side so i thought it might be similiar but nvm then ^^

**Comment by Abszoluto** [comment]
> > All my client files and server files are fine. I talked to Lemongrass and Stolao on discord and we found out that the issue is that the options need to be on consecutive slots. In the image, i changed on sql and put a random option on the slot missing and the 3 options appeared normally
> 
> oh i see, im sorry then i was just trying to help, i had this issue with my server with client side so i thought it might be similiar but nvm then ^^

no, i really understand, i didnt wanna seem rude or anything like that. I am really thankfull for your comment

**Comment by admkakaroto** [comment]
This are not server side rellated, uses rathena forums for this kind of support.

**Comment by Lemongrass3110** [comment]
> This are not server side rellated, use rathena forums for this kind of support.

Sadly it is. We already talked in the support channels on Discord.
