### ISSUE TITLE
Broken Instance Script Commands

### ISSUE THREAD

**Issue by violent01** [rathena/rathena#7452]
### rAthena Hash

3024d08a392ff65bf749b208681d85f0eb090368

### Client Date

2022-04-06

### Server Mode

Pre-Renewal, Renewal

### Result

```instance_create``` and ```instance_enter``` using instance mode ```IM_CHAR``` is broken. It will work the first time around you generate a solo instance but when you create another character on the same account or in another account and you try to generate the same instance, it will always say ```Time's crack is not created yet```. I've attached a sample script so the rA devs can confirm it.

```
prt_fild05,145,235,5	script	Quest Area#quest_area	4_GEFFEN_03,{

.@md_name$ = "Poring Village";
.@menu$[0] = "Create the entrance";
if (instance_live_info(ILI_NAME, instance_id(IM_CHAR)) == .@md_name$)
.@menu$[1] = "Enter the dungeon";

	mes "[System]";
	mes "Would you like to enter the Quest Grounds?";
	next;
	switch( select( .@menu$[0], .@menu$[1], "Cancel" ) ) {
		case 1:
			mes "[System]";
			mes "You only have 30 minutes to complete the quest. Once the timer reaches 0, you will be warped out.";
			instance_create(.@md_name$, IM_CHAR, getcharid(0));
			close;
		case 2:
			switch(instance_enter(.@md_name$, -1,-1, getcharid(0), IM_CHAR)){
				case IE_OTHER:
					mes "An unknown error occurred.";
					close;
				case IE_NOINSTANCE:
					mes "^ff0000Time's crack is not created yet.^000000";
					close;
				case IE_NOMEMBER:
					end;
				case IE_OK:
					mapannounce "prt_fild05", " " + strcharinfo(0) + " enters " + .@md_name$ + ".", bc_map,0xFF9900;
					end;
				}
				end;
		case 3:
			end;
		}
		end;
}
```

### Expected Result

Since there is no checker on the sample script I've provided, the instance should be working with other characters you made.

### How to Reproduce

test the sample script i provided.

### Official Information

N/A

### Modifications that may affect results

N/A

**Comment by Atemo** [comment]
I will check tomorrow, but there is a typo in the script you provide, `IM_CHAR` should be `instance_id(IM_CHAR)` in instance_enter

**Comment by violent01** [comment]
oh, okay, will try to test it now, maybe that will fix my problem and if it fixes it I will close this issue asap.

**Comment by violent01** [comment]
> I will check tomorrow, but there is a typo in the script you provide, `IM_CHAR` should be `instance_id(IM_CHAR)` in instance_enter

confirmed. The reason is only the missing ```instance_id```
