### ISSUE TITLE
NPC Kafra can't close store.

### ISSUE THREAD

**Issue by UpToYouSuck** [rathena/rathena#7454]
### rAthena Hash

https://github.com/rathena/rathena

### Client Date

20220406

### Server Mode

Renewal

### Result

NPC Kafra can't close store.
[Close button]

### Relevant Log Output

```Shell
No output on Mapserver just can't close Kafra store.
```

### Expected Result

Hope to find out what caused it.

### How to Reproduce

I have been updating from here on every topic. Before it was still working normally. and don't know when is the problem After constant updates Just came to try using Kafra store, so I encountered a problem.

### Official Information

Kro

### Modifications that may affect results

I have been updating from here on every topic.

**Comment by UpToYouSuck** [comment]
Last update  it's works fine.

![code](https://user-images.githubusercontent.com/117981474/203516857-86cbbe65-bc9c-4d29-8ca1-4bd1d71f6488.png)

![pull requests](https://user-images.githubusercontent.com/117981474/203516883-c7e8cd96-802a-41ce-95fb-9aa5a23288ed.png)

After in the picture, I updated everything to the latest today. Causing to not know what the problem is caused by the update

**Comment by UpToYouSuck** [comment]
I keep each update period. I have tried to use each of them, concluded that all of them cannot colse the button.

![Screenshot_3](https://user-images.githubusercontent.com/117981474/203529791-083c96d1-9aa3-4c54-837f-7a1b0a89623e.png)

**Comment by UpToYouSuck** [comment]
I'll try to catch up Each update period whether there are updates to other related files as well or not.

**Comment by UpToYouSuck** [comment]
https://user-images.githubusercontent.com/117981474/203533030-663ed495-97cd-4f1e-bcb7-878bb1d8e6e0.mp4

**Comment by Lemongrass3110** [comment]
Blocked you again. Have fun creating yet another user.
