### ISSUE TITLE
dynamic npc doesnt work if another dynamic npc (with different npc id) is being called.

### ISSUE THREAD

**Issue by dimasshotta** [rathena/rathena#7473]
### rAthena Hash

a763ad06294f1478343b3e765064e4bcdcb993c0

### Client Date

any

### Server Mode

Pre-Renewal, Renewal

### Result

I believe dynamic NPC can be called once for one npc id, but i guess it could be called twice or more if the source of the npc is different.

### Relevant Log Output

```Shell
struct npc_data* npc_duplicate_npc_for_player( struct npc_data& nd, struct map_session_data& sd ){
	
	if( sd.npc_id_dynamic != 0 ){
		clif_msg_color( &sd, C_DYNAMICNPC_TWICE, color_table[COLOR_LIGHT_YELLOW] );
		return nullptr;
	}
```

### Expected Result

this line above needs to be changed I guess. probablly try to change to npc dynamic name? dynamic npc can't be called if the same npc name is still appear.

dynamic npc works if the source id of the npc is different.

### How to Reproduce

play KRO

### Official Information

here working for the other dynamic npcs
![image](https://user-images.githubusercontent.com/74591268/205474336-dc9875fd-2a01-4d10-9030-73df4dc778d0.png)

**Comment by eppc0330** [comment]
Also dynamic npc should be removed on logout

**Comment by eppc0330** [comment]
@Atemo Ah I misremembered my test.

I got some more infos about dynamic NPC.

First I can confirm this issue, tested on KRo right now.
![dynamic02](https://user-images.githubusercontent.com/47050704/205721518-23b024cb-eddf-4a32-a638-91f0aedab216.gif)

Second dynamic NPC should be removed on map change, too.
![dynamic01](https://user-images.githubusercontent.com/47050704/205721598-1adb97a2-1fc9-49bd-a2d9-a59d03fe66ea.gif)
![dynamic03](https://user-images.githubusercontent.com/47050704/205721621-84b14fc0-7136-482d-ae84-fbf5374264f2.gif)

In this case I think I have seen some case not removing on mapchange and need more info.
However in most of situation as I tested dynamic NPC gets removed on map change.

**Comment by eppc0330** [comment]
Add) Timer issue also exist.
When dynamic NPC goes in idle status, ```dynamicnpc.removal_tid``` should be reset as 60sec, not remaining time before click the NPC.

**Comment by Atemo** [comment]
> Second dynamic NPC should be removed on map change, too.

Like certains skills (for example Wind Walk) the npc is not removed when staying in the same zone, and removed on zone change on official server

**Comment by eppc0330** [comment]
> > Second dynamic NPC should be removed on map change, too.
> 
> Like certains skills (for example Wind Walk) the npc is not removed when staying in the same zone, and removed on zone change on official server

I don't know if rathena's dynamic NPC is intended to be removed on zone change but I have never seen dynamic NPC removing on any map change in rA.

For example I summoned the NPC in Izlude and warp to Prontera, but the NPC still existed in Izlude.

**Comment by Lemongrass3110** [comment]
Because in rAthena you usually only have one zone (=map-server). In AEGIS you always have multiple zones and if you switch zones by warping the NPC is removed. The same would happen in rAthena if you switch map-server, as you "log out" on map-server A and "log in" on map-server B. Therefore the normal "log out" procedure removing the dynamic NPC would be triggered.

**Comment by eppc0330** [comment]
@Lemongrass3110 I got it. Thanks!

**Comment by Atemo** [comment]
The issue remains open until we check the timer problem
