### ISSUE TITLE
WE_CALLPARTNER has an invalid condition check

### ISSUE THREAD

**Issue by Tokeiburu** [rathena/rathena#7475]
### rAthena Hash

7bfae25c7

### Client Date

any

### Server Mode

Renewal

### Result

Attempting to use WE_CALLPARTNER while your child is on autotrade will fail the skill because WE_CALLPARTNER is also applying the WE_CALLBABY checks. This appears to be the only issue with the switch branching, the other scenarios/conditions can't mix:
```
		switch (ud->skill_id) {
			case WE_CALLPARTNER:
				if (sd)
					clif_callpartner(sd);
			case WE_CALLPARENT:
				if (sd) {
					struct map_session_data *f_sd = pc_get_father(sd);
					struct map_session_data *m_sd = pc_get_mother(sd);
					if ((f_sd && f_sd->state.autotrade) || (m_sd && m_sd->state.autotrade)) {
						fail = true;
						break;
					}
				}
			case WE_CALLBABY:
				if (sd) {
					struct map_session_data *c_sd = pc_get_child(sd);
					if (c_sd && c_sd->state.autotrade) {
						fail = true;
						break;
					}
				}
```

### Expected Result

I expect to be able to call a partner regardless of the vending status of the child.

### How to Reproduce

- Have two married characters.
- Adopt a child.
- Put the child character on autotrade.
- Try to use WE_CALLPARTNER on either one of the parents

### Official Information

Well, considering autotrade is a custom feature, that restriction/condition shouldn't technically exist.

**Comment by aleos89** [comment]
This is fixed in #5579.
