### ISSUE TITLE
NPC_AGIUP should be dispellable 

### ISSUE THREAD

**Issue by Singe-Horizontal** [rathena/rathena#7478]
### rAthena Hash

aa2bbaa31

### Client Date

N/A

### Server Mode

Pre-Renewal, Renewal

### Result

Mobs under NPC_AGIUP ( Ktullanux, Randgris, Cecil Damon, etc) should have this status removed by sage's dispell.

### Expected Result

Dispell should remove NPC_AGIUP

### How to Reproduce

N/A

### Official Information

https://irowiki.org/wiki/NPC_AGIUP

**Comment by aleos89** [comment]
Are you able to confirm this behavior on kRO too? iRO has a fair bit of skill modifications so we can't always directly rely on iRO Wiki unfortunately.

**Comment by secretdataz** [comment]
Confirmed on kRO.
