### ISSUE TITLE
npcwalkto: npc invisible while walking

### ISSUE THREAD

**Issue by adaral** [rathena/rathena#7483]
### rAthena Hash

https://github.com/rathena/rathena/commit/c6c6bc131eff2d4cd1fb22dc3192f057217c7d89

### Client Date

2020-04-01

### Server Mode

Pre-Renewal

### Result

When using `npcwalkto`, while the NPC moves it becomes invisible (can only see the shadow) and unclickable. It's an official sprite that moves just fine on older rAthena versions.
![error](https://user-images.githubusercontent.com/8409570/206925709-eaf1e651-672c-4b92-b2cf-5b4d321deeee.png)

### Expected Result

While moving, the NPC should be visible and clickable.

### How to Reproduce

Make an NPC using `npcwalkto`

### Official Information

-

**Comment by Lemongrass3110** [comment]
Please provide a sample script.

**Comment by adaral** [comment]
@Lemongrass3110 
`prontera,155,180,5	script	Moving	90,{

    npcspeed 600;

    OnTimer2000:
    npcwalkto 149,169;
    end;

    OnTimer21000:
    npcwalkto 162,169;
    end;

    OnTimer35000:
    npcwalkto 155,80;
    end;

    OnInit:
    initnpctimer;
    end;

}
`

**Comment by Haydrich** [comment]
> 

as i remember while working on ep 18.1, it's related to npc sprite? you should choose an npc that have walking position in sprite?

**Comment by adaral** [comment]
> > 
> 
> as i remember while working on ep 18.1, it's related to npc sprite, you should choose an npc that have walking position in sprite

Not really. I have used some sprites in older versions of rAthena that are not working now

**Comment by Pienne** [comment]
For anyone else finding this issue, I've tested this a bit prior and it's because the NPC sprite data doesn't have animation/sprite data for walking.

You'll find that if you find an NPC with valid walking sprites they will walk and be clickable. You can find one using a grf editor, I found some kafra NPCs that have valid walking sprites and they walk around just fine.
