### ISSUE TITLE
VS2022 compiler error

### ISSUE THREAD

**Issue by Masao87** [rathena/rathena#7492]
### rAthena Hash

https://github.com/rathena/rathena/commit/1f4c068c390f8908871cc67ac91969f314540814

### Client Date

2021-11-03

### Server Mode

Renewal

### Result

Hello everyone,

After the update to the "Refactor status change entries" my Visual Studio 2022 started to give me a bunch of warning / error messages.

4. See error:

10>src\map\mob.hpp(322,25): warning C4099: "status_change": Enter the name seen first using "class" and now using "struct" (source file will be compiled vending.cpp )
10>src\map\status.hpp(3136,7): message : See declaration of "status_change" (source file is compiled vending.cpp)
10>src\map\unit.cpp(2122,26): warning C4099: "map_session_data": Enter the name first seen using "class" and now using "struct".
10>src\map\trade.hpp(7,8): message : See declaration of "map_session_data"

Kind regards
Masao

### Relevant Log Output

```Shell
10>src\map\mob.hpp(322,25): warning C4099: "status_change": Enter the name seen first using "class" and now using "struct" (source file will be compiled vending.cpp )
10>src\map\status.hpp(3136,7): message : See declaration of "status_change" (source file is compiled vending.cpp)
10>src\map\unit.cpp(2122,26): warning C4099: "map_session_data": Enter the name first seen using "class" and now using "struct".
10>src\map\trade.hpp(7,8): message : See declaration of "map_session_data"
```

### Expected Result

Show no warning / error messages when compiling with VS2022

### How to Reproduce

Download a clean copy of the server and compile it with VS2022.

### Official Information

None.

### Modifications that may affect results

None.

**Comment by eppc0330** [comment]
Check #7490
