### ISSUE TITLE
Bug after update - prerenewal

### ISSUE THREAD

**Issue by Dark8008** [rathena/rathena#750]
![untitled](https://cloud.githubusercontent.com/assets/14345362/11085184/02b1ad18-8876-11e5-8951-d878fcf85d91.png)

**Comment by Playtester** [comment]
Why does the pre-renewal skill_require_db.txt have all the 3rd classes included?

**Comment by aleos89** [comment]
I was talking to Lemongrass about this before. I feel like we should remove third class from all pre-renewal databases.

As a result though, people have been accustomed to the classes being in pre-renewal for so long that I'm sure people will complain/make bug reports, so we were thinking of giving out a final import of the class info so people could throw them into their import folder.

**Comment by cydh** [comment]
@aleos89, at first place, on ur https://github.com/rathena/rathena/commit/a7b8fd4a5d33de75ae61796f21ccb11f14b9a19d for Pile Bunker, you shouldn't add the items for pre-re.

**Comment by Lemongrass3110** [comment]
Unable to reproduce on 27858bd
Guess you have a merge conflict.

**Comment by aleos89** [comment]
I realized now I shouldn't have added it. I was discussing the removal of 3rd class from pre-re databases around the time I committed this because of these issues.
