### ISSUE TITLE
[SKILL] Land Protector

### ISSUE THREAD

**Issue by antoniohauren** [rathena/rathena#7503]
### rAthena Hash

de7d91388

### Client Date

2021-11-17

### Server Mode

Renewal

### Result

rAthena mentions this but the behavior doesn't seems to be right.

`config/battle/skill.conf`
```
// Land Protector behavior (Note 1)
// On official servers, players standing on the border (outer cell) of the Land Protector can still be affected/hit
// by AoE skills (if the skill has a splash effect, such as Storm Gust). The Athena behavior ignores AoE affects/hits
// while players are standing on the border.
// Official: 0
// Legacy Athena: 1
land_protector_behavior: 0
```

`WZ_STORMGUST` with the `land_protector_behavior` set as 0, sounds right the description matches with the behavior

https://user-images.githubusercontent.com/101012531/208549443-5b2d1283-d6c5-43de-81c5-f8eb00adfc3c.mp4

`SO_PSYCHIC_WAVE` with `land_protector_behavior` also set as 0, even from far away the skill still damage inside

https://user-images.githubusercontent.com/101012531/208549455-b96dc76a-04f8-4370-8222-3e40f16f9eef.mp4

`SO_PSYCHIC_WAVE` with  `land_protector_behavior` set as 1, works like the description as well.

https://user-images.githubusercontent.com/101012531/208549459-323d69f0-2bea-47e1-b08c-7b7992675854.mp4

### Expected Result

I don't know if this is intended but in my opnion the behavior should be the same for both skills, 1 outer cell = damage anything but that should protect

### How to Reproduce

1. use land protector
2. take a 3rd or 4th job skill from outside
3. die

### Official Information

No idea just feels strange

### Modifications that may affect results

none

**Comment by Playtester** [comment]
I strongly depends on the skill. It depends on if the skill places a single unit that has a range or if it places a unit with no range on each cell.

Storm Gust is actually a quite special case as it both places multiple units AND all the units have a range of 1 (3x3).

You can adjust the behavior to your liking by editing the skill_db.yml. SplashArea determines the range of each cell (which can splash into Land Protector).
