### ISSUE TITLE
Try to compile from master found many bug!!

### ISSUE THREAD

**Issue by TheyAreShoddy** [rathena/rathena#7510]
### rAthena Hash

https://github.com/rathena/rathena

### Client Date

20220406

### Server Mode

Renewal

### Result

Try to compile from master found many bug!!
Informed and went to see it. embarrassed to be guilty but suspended the posting of informants many times

Previously everything was playing normally.
1 - [Roulette] Can only play in the bottom row.
2 - Class4 / Calss4 Expanded some skill stutus not show icon.
3 - Calss4 Expanded can't not use skill.
4 - item_enchant not work.

Look in clip finish.
https://youtu.be/yC-pDtFGgCs
.
.

### Relevant Log Output

```Shell
Look in clip finish.
https://youtu.be/yC-pDtFGgCs
```

### Expected Result

Look in clip finish.
https://youtu.be/yC-pDtFGgCs

### How to Reproduce

Look in clip finish.
https://youtu.be/yC-pDtFGgCs

### Official Information

Everyone who comes to read it.
The admins here always delete my messages. Is to cover up the mistakes that they made lightly no recheck It's been like this many times. therefore choosing a way that ends up flattening my usage
In spite of the fact that I always come to inform about the problem, there are some mistakes, some right But I keep checking. and can solve some problems But I can't tell because I'm banned from ID all the time

You guys thought that Who works more precisely? Envy of our fame So they chose to exclude us.

We give credit to thank you every time. You can see it in the full promotional clip.

### Modifications that may affect results

Update all from here.
https://github.com/rathena/rathena

**Comment by zdurexz** [comment]
WoW new account

**Comment by iberryRO** [comment]
> WoW new account

![image](https://user-images.githubusercontent.com/59070443/209434731-c14469af-d183-43cd-9d61-3537d2b4754e.png)

**Comment by fab10Carvalho** [comment]
1. duplicate #7506
2. and 3. rAthena did not implement expanded class skill yet, but they have pull request

![5555](https://user-images.githubusercontent.com/112716645/209443531-55245bf0-5e59-4df9-9808-35232b43f46e.png)

4. Enchant system using works!!

![0000111](https://user-images.githubusercontent.com/112716645/209443608-74401d19-2711-4081-b21e-4711d96a13de.png)

5. Important!!! use your brain 💯

**Comment by TheyAreShoddy** [comment]
> 1. duplicate [Start button roulette issue #7506](https://github.com/rathena/rathena/issues/7506)
> 2. and 3. rAthena did not implement expanded class skill yet, but they have pull request
> 
> ![5555](https://user-images.githubusercontent.com/112716645/209443531-55245bf0-5e59-4df9-9808-35232b43f46e.png)
> 
> 4. Enchant system using works!!
> 
> ![0000111](https://user-images.githubusercontent.com/112716645/209443608-74401d19-2711-4081-b21e-4711d96a13de.png)
> 
> 5. Important!!! use your brain 💯

================================================
I think you brain has a problem sure.
I told you before update server play normal after update (in video) many bug
File download from master you see that! in the video what that mean!!!
==================================================

**Comment by TheyAreShoddy** [comment]
> > WoW new account
> 
> ![image](https://user-images.githubusercontent.com/59070443/209434731-c14469af-d183-43cd-9d61-3537d2b4754e.png) ![image](https://user-images.githubusercontent.com/59070443/209434803-a1b14ef4-6b3f-40f7-921b-27fc401c4de1.png) I heard that it's far away from abroad. You should be able to fix the problem yourself.

What do you mean? I'm not hiding anything I've been using that name for a long time.
www.facebook.com/Pcmedias
www.facebook.com/Pcmedias.ROS
??????????????????????????????????????????

**Comment by TheyAreShoddy** [comment]
Look at The End credit special thanks.

https://youtu.be/m6E57O3RcL4
