### ISSUE TITLE
RODex zeny logs being "abused" by RMTers

### ISSUE THREAD

**Issue by Tokeiburu** [rathena/rathena#7519]
### Is your request related to a missing official feature?

No

### Describe the solution you'd like

When sending a RODex mail with zeny, the zenylog entry doesn't show the destination character (it shows the same ID as the source character). Receiving the zeny has the same behavior. RMTers believe that this method can hide their trades because it's much harder to know who received the zeny since there is no link between the sender and the receiver, and they are correct.

I changed this behavior on our server years ago and I didn't think too much about it, but seeing a recent trend with our RMTers that use RODex made me question why they'd do something so stupid since a RODex zeny trade lights up like a christmas tree in the logs; until I remembered the default behavior on rAthena.

I understand that technically speaking, sending the RODex and showing the src_id as the receiver isn't accurate either because the receiver may or may not have grabbed the zeny in the mail at all. You have no way to know for sure unless you check if the character has actually received the zeny from RODex or not.

However, I believe that this is a small price to pay as it makes tracking cases much easier and other server owners could greatly benefit from this change. Currently, you have to divide the sender's amount of zeny by the RODex tax, then you have to look through the logs searching for that specific value with a date close to the sender's. Hopefully, there is a match and you have the receiver, but you can never be sure it is the actual receiver since anyone can open a mail at random times. Also, if the sender added an item, it turns everything into a real headache as you have to substract each item sent (via the picklog) by the fee added for adding an item, making this tracking task near impossible.

### Describe alternatives you've considered

Change the src_id value with the receiver when sending a RODex mail.
Change the src_id value with the sender when receiving a RODex mail.

To make this work, I added a "LOG_TYPE_NONE" type, to prevent pc_payzeny from logging anything. Then I called log_zeny directly in the RODex functions after pc_payzeny for the actual logging to happen. I changed the function interface from "map_session_data* src_sd" to "int src_id" as well since it didn't make much sense anymore. But whatever solution works just as well.

**Comment by Lemongrass3110** [comment]
Fixed in 7dd6eb5
