### ISSUE TITLE
Itemdrop overflow

### ISSUE THREAD

**Issue by Fraterna** [rathena/rathena#752]
hi there,

found something weird when some char wears a lot of equips that adds items with 
"Bonus2 bAddMonsterDropItem,"

how to reproduce: 
Class: Genetic
equips:
- Alchemist card set (+ stem, + Glistering Coat), Holden card in Upper headgear
- Myst Case Card (+ Giftbox), in middle headgear
- Scalpel + Green Operation Coat (+ Immortal Heart, + Alcohol when killing brutes/demihumans)
- Spare Card (+ Cookie Bag, + Santa's Bag, +Blank Card, +Old Purple Box)

when wearing all those, the myst case card gets ignored. (tested on 5000x rates, so it should alsways drop everything at 100% chance)

guess the drop-list gets some overflow or such, so not every item that should be dropped actually drops. no idea if this follows official behavior, wasn't able to afford that lot +drop equips on offi xD

rev doesn't matter, it's like this for at least half a year now, even with updating the server every few weeks. (too lazy to report it =P)

**Comment by aleos89** [comment]
Keep in mind there is a limit of 10 by default:
```
#define MAX_PC_BONUS 10 /// Max bonus, usually used by item bonus
```

Also, are you getting a warning on the mapserver?
```
	ARR_FIND(0,max,i,!&drop[i] || (drop[i].nameid == 0 && drop[i].group == 0));
	if (i >= max) {
		ShowWarning("pc_bonus_item_drop: Reached max (%d) number of added drops per character! (nameid:%hu group:%d class_:%d race:%d rate:%d)\n",max,nameid,group,class_,race,rate);
		return;
	}
```

**Comment by cydh** [comment]
need to test instead reply something like that @aleos89. beside, if u count the items, are only 9.

**Comment by aleos89** [comment]
I didn't have a test environment at the time to confirm the issue. I realized he only listed 9 items, which is why I said to "just keep in mind".

**Comment by secretdataz** [comment]
Tested killing 10 Orc Ladies on commit 9b48263 with `item_rate_adddrop: 500000`.
All drops mentioned are dropping just fine.
![image](https://cloud.githubusercontent.com/assets/2021243/12189624/02dd0126-b5f2-11e5-8bfc-7ad653ccc867.png)
