### ISSUE TITLE
Request @reloadbarterdb

### ISSUE THREAD

**Issue by attackjom** [rathena/rathena#7520]
### Is your request related to a missing official feature?

No

### Describe the solution you'd like

for now, the way to reload barter db & bartershop npc is @reloadscript that affect many script in server (ex. Instance dungeon) and need a bit of time to reload in addition it's reload permanent mob spawn that abusing with MVP hunting.

so I think it should be good if we have @reloadbarterdb command to reload only barter yml and bartershop npc.

**Comment by mazvi** [comment]
Duplicated https://github.com/rathena/rathena/issues/6559
