### ISSUE TITLE
Missing NPC "Illusion Enchanter"

### ISSUE THREAD

**Issue by Pokye** [rathena/rathena#7522]
### rAthena Hash

https://github.com/rathena/rathena/commit/64228cd18f66ebaf05bf8b16b0a0bdc51308916f

### Client Date

2022-04-06

### Server Mode

Renewal

### Result

Missing an npc in Prontera, responsible for enchanting the equipment with the Illusion Stones.

### Expected Result

?

### How to Reproduce

?

### Official Information

![image](https://user-images.githubusercontent.com/98105181/210264315-48aa03f4-a10d-4d6a-86b9-b8934092e911.png)

https://github.com/rathena/rathena/blob/master/npc/re/merchants/enchan_illusion_16_2.txt#L502

**Comment by Atemo** [comment]
https://github.com/rathena/rathena/pull/7464 includes the enhance merchant but not the laphine merchant
