### ISSUE TITLE
Compilation error using latest rathena on CentOS 7

### ISSUE THREAD

**Issue by rupertbulquerin** [rathena/rathena#7527]
### rAthena Hash

ea3464598dda4203eb7171b8a9f7b5c020762c39

### Client Date

NA

### Server Mode

Pre-Renewal

### Result

![Screen Shot 2023-01-05 at 2 27 40 AM](https://user-images.githubusercontent.com/37164890/210624256-ba997bd4-f896-47fa-9f76-e63619e378a0.png)

### Expected Result

NA

### How to Reproduce

Compile latest rathena in CentOS 7

### Official Information

NA

**Comment by aleos89** [comment]
CentOS comes with gcc 4.8 by default. You need to update. Please see our [wiki](https://github.com/rathena/rathena/wiki/Install-on-Centos#install-prerequisites).
