### ISSUE TITLE
I wanted to see this Bonus.

### ISSUE THREAD

**Issue by cold-hr** [rathena/rathena#753]
bonus2 bWeaponAtk,w,n;
bonus2 bWeaponAtkRate,w,n;

I wanted to see this Bonus.

bonus2 bWeaponAtkDef,w,n;
bonus2 bWeaponAtkDefRate,w,n;

**Comment by nanakiwurtz** [comment]
Hello @cold-hr , this GitHub Issue is intended for Bug Reports only.
Please post your suggestion/request on the forum instead --> https://rathena.org/board/forum/36-source-requests/
And add a descriptive text too, thanks!

**Comment by cold-hr** [comment]
sorry  
and thank
