### ISSUE TITLE
User logged in already, cannot log in

### ISSUE THREAD

**Issue by MaouDaiou** [rathena/rathena#7538]
### rAthena Hash

User logged in already cannot log in

### Client Date

2023-01-09

### Server Mode

Renewal

### Result

User logged in already, cannot log in.
https://media.discordapp.net/attachments/727532828727836743/1061932414475186227/image.png

### Expected Result

I hope you fix it soon.

### How to Reproduce

I have no advice

### Official Information

kRo

### Modifications that may affect results

i'm not modify.

**Comment by zdurexz** [comment]
I confirm that I am unable to log in again.

**Comment by MaouDaiou** [comment]
https://youtu.be/HkHdPzzUvlQ
how to fix T^T

**Comment by MaouDaiou** [comment]
thank you very mush

**Comment by mazvi** [comment]
Another problem is user autotrade cannot login.
