### ISSUE TITLE
Critical Issue pointshop

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#7548]
### rAthena Hash

5044776

### Client Date

2021-11-03

### Server Mode

Renewal

### Result

The player can buy items that cost more than he has points.

### Expected Result

The player cannot buy items that cost more than he has points.

### How to Reproduce

Frist make sure you have `#CASHPOINTS` 150000

Using `@cash 150000`

And you must have item on cashshop top right example apple with price 100000

Make NPC Like This

`-	pointshop	shop_petegg01	FAKE_NPC,#CASHPOINTS,9055:100000,9056:100000`

Then call it using `callshop "shop_petegg01",1;`

buy 1 egg with price 100000

after that open cashshop on top right window

And see your cash is not reduced at all you still have 150000, you can still buy anything for 100000 at the top right cashshop

so with 150000 you can buy item with price 200000

### Official Information

NA

**Comment by idk-whoami** [comment]
confirm

**Comment by Lemongrass3110** [comment]
Can also confirm it and already know why it happens.
Will look into it after work.
