### ISSUE TITLE
Abrasive (14536)

### ISSUE THREAD

**Issue by ernestfegarido** [rathena/rathena#755]
An abrasive gives crit +30 for 5 min. when im using it it only gives +3 crit but the duration is correct.

source: http://db.irowiki.org/db/item-info/14536/

**Comment by nanakiwurtz** [comment]
Current item script is already correct:
> 14536,Abrasive,Abrasive,2,0,,10,,,,,0xFFFFFFFF,63,2,,,,,,{ specialeffect2 EF_MAGICALATTHIT; sc_start SC_INCCRI,300000,30; },{},{}

Maybe it's source side?

**Comment by lighta** [comment]
if @aleos89 or @Cydh could confirm this with Aegis data.
Here the typo, (we use val1 instead val2 in the proper calc function)

diff --git a/src/map/status.c b/src/map/status.c
index ee08985..1c7988c 100644
--- a/src/map/status.c
+++ b/src/map/status.c
@@ -5622,7 +5622,7 @@ static signed short status_calc_critical(struct block_list *bl, struct status_ch
                return cap_value(critical,10,SHRT_MAX);
 
        if (sc->data[SC_INCCRI])
-               critical += sc->data[SC_INCCRI]->val1;
+               critical += sc->data[SC_INCCRI]->val2;
        if (sc->data[SC_CRIFOOD])
                critical += sc->data[SC_CRIFOOD]->val1;
        if (sc->data[SC_EXPLOSIONSPIRITS])

**Comment by Playtester** [comment]
I'm playing on iRO and Abrasive gives Crit+30 for sure there. It's a very popular cash shop item for Assassins.

However, critical is measured in tenth on Aegis. So 1 = 0.1%. That means critical should be increased by 300 and not 30.

**Comment by lighta** [comment]
The val2 is already val1*10. And val1 is 30 here so that would be 300 accordingly.
see : https://github.com/rathena/rathena/blob/master/src/map/status.c#L9454
You can put 300 as a tmp fix to not recompile in the meantime but it's more a src typo.

**Comment by aleos89** [comment]
It's just a typo. As @lighta put, it should be val2 instead of val1. I had already started a diff with fixes.
