### ISSUE TITLE
Autotrade Cannot Login

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#7550]
### rAthena Hash

https://github.com/rathena/rathena/commit/65ebbdc992edaee87e53e1b285e5518c91ddd1d4

### Client Date

2021-11-03

### Server Mode

Renewal

### Result

Autotrade player cannot login again

Like this issue https://github.com/rathena/rathena/issues/7538

### Expected Result

Player can login

### How to Reproduce

Using `@autotrade`

Then login again with that char

### Official Information

NA

**Comment by Lemongrass3110** [comment]
Works perfectly fine.

**Comment by Lemongrass3110** [comment]
@Atemo is also unable to reproduce this.

**Comment by mazvi** [comment]
Please reopen my issue this happend real! https://github.com/rathena/rathena/issues/7556

I have additional info, after autotrade restart the server. I presume this is caused due to autotrade on the web service?

**Comment by Lemongrass3110** [comment]
You can comment in the new (more detailed) issue.
There is no reason to reopen yours.

**Comment by MaouDaiou** [comment]
conf/battle/feature.conf
feature.autotrade: off
change from "off" to "on"

**Comment by MaouDaiou** [comment]
or logged in already autotrade
src/char/char.cpp
search `character = std::make_shared<struct online_char_data>( account_id );`
add `char_get_onlinedb()[account_id] = character;`
There are 2 of them that can be added to the bottom of the 2.
