### ISSUE TITLE
Autotrade-Vendor cannot login after server restart

### ISSUE THREAD

**Issue by datawulf** [rathena/rathena#7556]
### rAthena Hash

65ebbdc992edaee87e53e1b285e5518c91ddd1d4

### Client Date

2022-12-21

### Server Mode

Renewal

### Result

Autotrade player cannot login again, merchant in autotrade stays online.

Might have been related to this: https://github.com/rathena/rathena/issues/7550

### Expected Result

On first login attempt, autotrader gets logged of.
On second login attempt, player can login.

### How to Reproduce

Setup Vending store. Use @autotrade. Restart Server. Try to login account again.

### Official Information

N/A

**Comment by mazvi** [comment]
please give rathena hash properly.

**Comment by datawulf** [comment]
> please give rathena hash properly.

my bad.

**Comment by mazvi** [comment]
I have additional info, after autotrade restart the server. I presume this is caused due to autotrade on the web service?

**Comment by datawulf** [comment]
My take would be it's simply missing https://github.com/rathena/rathena/blob/master/src/char/char.cpp#L101 at https://github.com/rathena/rathena/blob/master/src/char/char.cpp#L141

**Comment by mazvi** [comment]
additional info on my battle conf

```
// Allow autotrade only in maps with autotrade flag?
// Set this to "no" to allow autotrade where no "autotrade" mapflag is set.
// Set this to "yes" to only allow autotrade on maps with "autotrade" mapflag.
at_mapflag: yes

// Set this to the amount of minutes autotrade chars will be kicked from the server.
// 1440      1 day
// 86400    60 day
// 259200  180 day
at_timeout: 259200
```

**Comment by attackjom** [comment]
confirm. It occur after restart server once like @datawulf  said.

**Comment by zdurexz** [comment]
Hmm i confrim , now if account use autotrade close cmd run server , The first time will not be able to access the account that uses autotrade. You need to restart again to be able to login to your account.

**Comment by mazvi** [comment]
is your server linux? @datawulf @attackjom @zdurexz

**Comment by zdurexz** [comment]
> is your server linux? @datawulf @attackjom @zdurexz

My windows server
