### ISSUE TITLE
Mini Map no sync member party

### ISSUE THREAD

**Issue by hnomkeng** [rathena/rathena#7558]
### rAthena Hash

513a4db

### Client Date

2021-11-16

### Server Mode

Pre-Renewal/Renewal

### Result

location mini map no sync

![image](https://user-images.githubusercontent.com/9112684/213443193-00adedd3-f73c-471b-a77a-332e280df519.png)

### Expected Result

-

### How to Reproduce

-

### Official Information

-

### Modifications that may affect results

-

**Comment by Lemongrass3110** [comment]
![grafik](https://user-images.githubusercontent.com/3517879/213592739-f849d027-edff-4453-85eb-abef301c7ecd.png)

Works perfectly fine for me.

Your hash does not exist. Are you sure this is not a local hash of your own fork? Did you change anything?

**Comment by hnomkeng** [comment]
fixed, i'm loss code

thank u bro.

https://github.com/rathena/rathena/commit/5044776eb72dfc2e330682ab70b0845a29c25730#diff-31cb459fb1c669a9a031d3f74518dfacac9d72d8d796ae8733e27a96b1c0b253R1085

**Comment by Daraen1** [comment]
![image](https://user-images.githubusercontent.com/75265726/213874199-92a464e3-823a-41b0-9e46-d160e829ad59.png)
I also had this bug but it wasn't present all the time, I'll take a look at the code and give you feedback.
