### ISSUE TITLE
I got this after update ( all script have map )

### ISSUE THREAD

**Issue by Dark8008** [rathena/rathena#756]
![image](https://cloud.githubusercontent.com/assets/14345362/11181365/1bd5ed6e-8c94-11e5-9c49-86b9c4153404.png)

I use pre-renewal ( got this after update, before that normal ), all script relate to map show that !

**Comment by julia40124009** [comment]
confirm 
I use renewal
version : https://github.com/rathena/rathena/commit/fca42f68b5f3e5ab0dc9951e18cb8646b016d959

**Comment by cydh** [comment]
still impressed, he didn't test to run the server before pushing the commit. xD
