### ISSUE TITLE
VIP System

### ISSUE THREAD

**Issue by Miraakol** [rathena/rathena#7570]
### rAthena Hash

d93d414

### Client Date

2021-11-03

### Server Mode

Pre-Renewal

### Result

error message shows up in map server console.
![Screenshot 2023-01-28 205252](https://user-images.githubusercontent.com/4651777/215267388-530b5626-3f18-4500-be26-f5318c001895.png)

### Relevant Log Output

```Shell
[Error]: Account '2000001' `character_slots` column is higher than supported MAX_CHARS (21), update MAX_CHARS in mmo.hpp! capping to MAX_CHARS...
```

### Expected Result

no error in map server

### How to Reproduce

1. enable VIP system
2. recompile src
3. start rathena
4. create an account
5. create character
6. set character to VIP
7. relogin account then check map server console error will appear

### Official Information

NA

### Modifications that may affect results

no modification applied.

**Comment by mazvi** [comment]
DUPLICATED: https://github.com/rathena/rathena/issues/7363
