### ISSUE TITLE
NPC_SECURE_TIMEOUT

### ISSUE THREAD

**Issue by Pokye** [rathena/rathena#7577]
### rAthena Hash

https://github.com/rathena/rathena/commit/96f0f77d42af93494042ab4a332754f744dffa6a

### Client Date

2022-04-06

### Server Mode

Pre-Renewal, Renewal

### Result

I noticed this a while ago, but I forgot to report it! The NPC protection system is not working properly, by default it wasn't supposed to disappear the npc's speeches in the 60 second period set in "**#define NPC_SECURE_TIMEOUT_NEXT 60**".

My current configuration:
```c
#define NPC_SECURE_TIMEOUT_INPUT 300

/**
 * Number of seconds after a 'menu' is displayed before invoking an idle timeout.
 * Default: 60
 **/
#define NPC_SECURE_TIMEOUT_MENU 60

/**
 * Number of seconds after a 'next' button is displayed before invoking an idle timeout.
 * Default: 60
 **/
#define NPC_SECURE_TIMEOUT_NEXT 60
```

### Expected Result

No response

### How to Reproduce

No response

### Official Information

bRO ( Server Brazil )

https://user-images.githubusercontent.com/98105181/216754725-f376316c-8318-4003-8a9b-0ea5bef6c700.mp4

rA ( Lasted Commit )

https://user-images.githubusercontent.com/98105181/216754740-e001a06e-4367-485d-98f7-72d9d4e63b5a.mp4

**Comment by vstumpf** [comment]
Seems like a simple fix, we just have to not call `clif_scriptclear()` in `pc_close_npc`.
We only use `pc_close_npc` when we reload scripts and on this timeout

**Comment by bgamez23** [comment]
i think this is related to this issue. this issue occurred for a very long time which already forgotten.
https://github.com/rathena/rathena/issues/2177

**Comment by mazvi** [comment]
wouldn't it be better to disappear like that for safety?

**Comment by eppc0330** [comment]
Dialog not disappearing on 60sec in KRO either.
To follow official behavior we better fix this.

**Comment by mazvi** [comment]
maybe it can be configured on conf. because the timeout is 60 seconds I think it can be for security or better performance

**Comment by Pokye** [comment]
With me it resolved by removing it.
```
clif_scriptclear( *sd, sd->npc_id ); // [Ind/Hercules]
```
https://github.com/rathena/rathena/blob/b56f11207c3cb5337dca07bb910ba85316c84939/src/map/pc.cpp#L9475

**Comment by aleos89** [comment]
@eppc0330 has the behavior changed in kRO? Could you list out all the timeout types and the associated times with them? Thanks!

**Comment by eppc0330** [comment]
@aleos89 sorry I have no idea if it has been changed, but since I notice this the behavior always does like what I explained above. Times are same, just dialogs are keep appearing even after TIMEOUT set.

**Comment by mazvi** [comment]
> @aleos89 sorry I have no idea if it has been changed, but since I notice this the behavior always does like what I explained above. Times are same, just dialogs are keep appearing even after TIMEOUT set.

I think it would be strange on the player side if the dialog menu is still there but the NPC has timed out. when the menu is selected it will produce nothing and players will think it's a bug.

**Comment by eppc0330** [comment]
@mazvi I'm just talking about official behavior, but if you are asking my opinion, I can say for me the opposite. I have noticed this difference quite long time ago, but I was already familiar with official server's behavior at this moment. So I thought rA's behavior was rather very strange when I noticed this.

**Comment by Atemo** [comment]
For reference : https://github.com/rathena/rathena/commit/54dfc6792556f886a326cdb002abcb08441b1475
