### ISSUE TITLE
Marriage Breaks Upon Rebirth

### ISSUE THREAD

**Issue by LadyNanuia** [rathena/rathena#7578]
### rAthena Hash

1bfdca48e15155a72a082931662ef8723372c477

### Client Date

2020-09-02

### Server Mode

Renewal

### Result

When 2 characters are married and one of them rebirths, Marriage breaks and sharing experience is no longer possible

### Expected Result

Sharing should be possible

### How to Reproduce

You should be able to still share as you're married

### Official Information

Officially you should be able to share as far as i know

### Modifications that may affect results

None

**Comment by LadyNanuia** [comment]
To clarify, this also involves the baby but im refering to when the parents rebirth

**Comment by vstumpf** [comment]
The parents have to be at least level 70 for the family party to share.

See `party_check_family_share`
https://github.com/rathena/rathena/blob/96f0f77d42af93494042ab4a332754f744dffa6a/src/char/int_party.cpp#L301-L338

**Comment by LadyNanuia** [comment]
is this really official behaviour? i always thought you could share no matter level if you were a family

**Comment by vstumpf** [comment]
irowiki isn't the greatest source of info, but here it does say that the parents have to be 70+
https://irowiki.org/wiki/Adoption_System#Benefits_of_being_Adopted

if you have evidence to the contrary, we can reopen this issue.

**Comment by LadyNanuia** [comment]
Just tested this with level 70 parents as well after rebirthing, still doesnt work to share
