### ISSUE TITLE
Hp displayed when dead

### ISSUE THREAD

**Issue by Atemo** [rathena/rathena#758]
Hash : e27697072317820cab4ef1e551ec50de46fc73a7

On iro/euro the client display 1 hp when you have died (on rathena -> 0 hp).

Image on left, with rathena ; offi on right
![comparaision](https://cloud.githubusercontent.com/assets/5231893/11194170/e65eacea-8caa-11e5-9678-8e678d28873c.png)

**Comment by Lemongrass3110** [comment]
@RagnarokNova could you confirm this?

**Comment by RagnarokNova** [comment]
http://i.imgur.com/RHCp2U6.png
Confirmed on iRO, checking kRO now.

**Comment by lordganja** [comment]
due to this update. is there any work around to check if the player is dead?

**Comment by Atemo** [comment]
This update only affected the hp displayed by the client. Inside server the HP of dead player is still 0.

I will update the docs but I think it will be a bit confusing, specially for those who don't read the docs.. :p We may implement a new command script or use a const to check if the player is dead Just an idea~.

**Comment by lordganja** [comment]
Ohh. Alright. Didn't know that XD. So if we check the hp using a script, it will show 0 hp while we see it as 1?

And yeah a new command script to check if player is dead will really be helpful.

**Comment by kyeme** [comment]
Novice too :D

![image](https://cloud.githubusercontent.com/assets/4656578/11374284/3977a542-9310-11e5-8c9a-8b759aecaa02.png)

**Comment by Atemo** [comment]
Hmm yes :p

**Comment by icxbb-xx** [comment]
@kyeme , you can post screen shot for  high novice and super novice when die
thank you

**Comment by icxbb-xx** [comment]
Fixed in https://github.com/rathena/rathena/commit/54136ddfca421546a6cb84298d212995061829bd
Try check again , Thank you
