### ISSUE TITLE
Can't disable itemlink feature

### ISSUE THREAD

**Issue by AsuraPlop** [rathena/rathena#7584]
### rAthena Hash

7e62670

### Client Date

20180620

### Server Mode

Pre-Renewal

### Result

Can't disable itemlink feature in the feature.conf file

### Expected Result

Disable itemlink in chat (shift + click on item)

### How to Reproduce

 feature.itemlink: off
 @reloadbattleconf or  ./athena-start restart

### Official Information

Emply

**Comment by vstumpf** [comment]
This is not what that feature switch is for.
`feature.itemlink` is for the server-side commands like `@idsearch` or `@iteminfo`

It does not prevent users from sending itemlinks. If you want that, you'll have to add a customization to `clif_process_message` to find and block itemlinks.
