### ISSUE TITLE
Confirm Homunculus skill cooldowns

### ISSUE THREAD

**Issue by Lemongrass3110** [rathena/rathena#7605]
### rAthena Hash

9d2bcc7

### Client Date

2023-01-05

### Server Mode

Pre-Renewal, Renewal

### Result

During review of https://github.com/rathena/rathena/pull/7586 it was reported that the Homunculus should use Cooldown rather than AfterCastActDelay.

### Expected Result

Unknown

### How to Reproduce

Unknown

### Official Information

I do not have any sources.
Feel free to comment some.

**Comment by Daegaladh** [comment]
From my tests o officials I can confirm on Renewal they have Cooldown.
Neither the effect or the cooldown goes away on changing maps, teleport or vaporize, but the effect goes away on relog (the cooldown doesn't)

On Pre-re on the other hand, it was AfterCastActDelay, and both the effect and the delay go away on changing maps, teleport, vaporize and relog.
