### ISSUE TITLE
Skill: Fire Pillar ( ID:80 WZ_FIREPILLAR ) Blue Gemstone will also be consumed in VIP or wearing Mistress Card

### ISSUE THREAD

**Issue by Oysica** [rathena/rathena#7619]
### rAthena Hash

198566204

### Client Date

20220602

### Server Mode

Renewal

### Result

Skill: Fire Pillar ( ID:80 WZ_FIREPILLAR ) Blue Gemstone will also be consumed in VIP or wearing Mistress Card
1. Change Job to Wizard.
2. Get blue gemstone
3. Use Fire Pillar above lv6
4. Check whether the blue gemstone is consumed

### Relevant Log Output

```Shell
no
```

### Expected Result

Blue gemstone is not consumed

### How to Reproduce

Skill: Fire Pillar ( ID:80 WZ_FIREPILLAR ) Blue Gemstone will also be consumed in VIP or wearing Mistress Card
1. Change Job to Wizard.
2. Get blue gemstone
3. Use Fire Pillar above lv6
4. Check whether the blue gemstone is consumed

### Official Information

no

**Comment by aleos89** [comment]
Fixed in bb8c4a0.
