### ISSUE TITLE
ITEM_ENCHANTARMS status icon

### ISSUE THREAD

**Issue by MrAntares** [rathena/rathena#7631]
### rAthena Hash

bb8c4a03c8d3d9559637ab537babdd0733ecc041

### Client Date

All

### Server Mode

Pre-Renewal, Renewal

### Result

Using elemental converters & cursed water (skill ITEM_ENCHANTARMS) doesn't display the status icon and doesn't have an sc_start in Skill.cpp Line 7612, so it doesn't send the packet to show the icon. This has been an issue for a long time. On official servers this was fixed quite a while ago, but not sure when.

### Expected Result

It should display the status icon according to the received weapon element buff

### How to Reproduce

Use elemental converter or cursed water.

### Official Information

IdRo example showing the use of converter:
https://youtu.be/wAjAVtjAvuw?t=13

iRO Chaos example of using cursed water (green sword icon appearing):
https://youtu.be/U5K4uQ7auXU?t=96

**Comment by MrAntares** [comment]
On a sidenote: NPC_PROVOCATION skill also doesn't show the provoke status icon

**Comment by Daraen1** [comment]
You can make that easily by yourself in client side in  **stateiconinfo.lub**.
example for **Cursed Water**. 

 ```
 StateIconList[EFST_IDs.EFST_ATTACK_PROPERTY_DARKNESS] = {
	haveTimeLimit = 1,
	posTimeLimitStr = 2,
	descript = {
		{ "Grants weapon with Shadow property", COLOR_TITLE_BUFF },
		{ "%s", COLOR_TIME }
	}
}
```
**stateiconimginfo.lub**
```
[EFST_IDs.EFST_ATTACK_PROPERTY_DARKNESS] = "weapon_property_shadow.tga",
````


**I don't remember if we need to modify the server side**

![image](https://user-images.githubusercontent.com/75265726/223737054-e76cf74c-e749-415e-83c3-8a7d5cb85b04.png)

![image](https://user-images.githubusercontent.com/75265726/223735032-3e3d6613-a5b0-4859-95b9-176c389086b5.png)
![image](https://user-images.githubusercontent.com/75265726/223735132-7c69c784-218e-47cb-a8aa-ebf667f4ce0d.png)

**Comment by MrAntares** [comment]
Ok, nevermind. My server was old version and didnt send the state change. On newer server I do get the packet.
