### ISSUE TITLE
Battle Log (client side i think)

### ISSUE THREAD

**Issue by ernestfegarido** [rathena/rathena#764]
im using 2013-08-07 rag exe the damage in battle log is not working on a player but working fine in monster. i already turn on the options but still not working on the player.

**Comment by ernestfegarido** [comment]
mode: renewal
git hash: not familiar

**Comment by nanakiwurtz** [comment]
Hello @ernestfegarido , thanks for your bug report.
To see your git hash, please refer to this post --> https://rathena.org/board/blog/47/entry-82-bug-report/
Thank you :)

**Comment by aleos89** [comment]
http://imgur.com/huxhEHZ

Tested with 2013-08-07 on ad3a74b. Worked fine for me.
