### ISSUE TITLE
Received unsupported packet

### ISSUE THREAD

**Issue by hnomkeng** [rathena/rathena#7647]
### rAthena Hash

22abdf8

### Client Date

2021-11-16

### Server Mode

Pre-Renewal

### Result

```
(03/15/2023 01:42:27) [ Warning ] : clif_parse: Received unsupported packet (packet 0x0003, 44 bytes received), disconnecting session #8.
(03/15/2023 01:42:27) [ Warning ] : clif_parse: Received unsupported packet (packet 0x0003, 44 bytes received), disconnecting session #8. 
```

### Expected Result

maybe random spoof packet from hacker tools.

### How to Reproduce

-

### Official Information

-

**Comment by Lemongrass3110** [comment]
Not an issue.

Most likely someone is scanning your server for open ports.
