### ISSUE TITLE
Tiger Cannon (Sura)

### ISSUE THREAD

**Issue by RagnarokNova** [rathena/rathena#765]
Quite a few things wrong with the skill currently.

First and foremost, equal builds showed extremely differences in damage.

Aegis (No weapon) -> 12k
rA (No weapon)  -> 40k
Aegis (Carga Mace) -> 15.8k
rA  (Carga Mace) -> 42k

I did further in-depth testing to check the behavior of the skills and here are the numbers I got.

High Vit Build
19k/18.7k on naked target (Neutral Weapon)
11k on Ghostring target (Neutral Weapon)
11k on Ghostring target (Fire Weapon)
18.5k on naked (Fire Weapon)
18k on Fire armor (Fire Weapon)
18.1k on Earth armor (Fire Weapon)

High STR / No Vit
Neutral (Carga) on Earth (Sandman)
18.4k~18.7k
Earth (Carga with Enchant Scroll) on Wind (Dokebi)
18.9k~21k

Results: Pseudo Elemental. Damage affected by HP is not affected by elements, but damage from Attack is.
The damage formula itself is also extremely wrong and will require further testing.

**Comment by cydh** [comment]
if u're using Aegus test server which before post balance, it'll be different problem.
This is post balance formula for Tiger Cannon
````ATK [((Caster’s consumed HP + SP) / 4) x Caster’s Base Level / 100] %
+ (Tiger Cannon skill level x 240) + (Target’s Base Level x 40)
If used as a combo skill after Fallen Empire,
ATK [((Caster’s consumed HP + SP) / 2) x Caster’s Base Level / 100] %
+ (Tiger Cannon skill level x 500) + (Target’s Base Level x 40)````

**Comment by aleos89** [comment]
There's a typo in the HP/SP damage calculation which is resulting in the large damage (introduced here: 1ea4655).
```
		case SR_TIGERCANNON:
		case SR_FLASHCOMBO_ATK_STEP3:
			{
				int hp = sstatus->max_hp * (10 + 2 * skill_lv) / 100, // skill_get_hp_rate(SR_TIGERCANNON, skill_lv)
					sp = sstatus->max_sp * (5 + 1 * skill_lv) / 100; // skill_get_sp_rate(SR_TIGERCANNON, skill_lv)
				if( sc && sc->data[SC_COMBO] && sc->data[SC_COMBO]->val1 == SR_FALLENEMPIRE )
					// Base_Damage = [((Caster consumed HP + SP) / 2) x Caster Base Level / 100] %
					skillratio += ((hp+sp) / 2);
				else
					// Base_Damage = [((Caster consumed HP + SP) / 4) x Caster Base Level / 100] %
					skillratio += ((hp+sp) / 4);
				RE_LVL_DMOD(100);
			}
			break;
```
You forgot to adjust for the -100 when you changed the operator from '=' to '+='.

**Comment by Barigas** [comment]
It is worth adding that this skill shoud deal equal splash damage to all targets(mentioned here http://irowiki.org/wiki/Tiger_Cannon). So, if you hit the main target with 50k damage, the other targets should receive the same 50k damage, no matter what equip they have.
As I also recall, Tiger Cannon on ruRO and iRO does not deal 2x damage if used by Flash Combo (source here also http://irowiki.org/wiki/Flash_Combo).

**Comment by idamonli** [comment]
change sth to 
skillratio += -100 + (hp+sp) / 2;

**Comment by cydh** [comment]
Tiger Cannon and Skynet Blow then. thx, sorry for the delay, I thought aloes will do this :P

**Comment by aleos89** [comment]
I have a sizable cleanup for this. Just needs testing still.

**Comment by cydh** [comment]
the typo, nothing significant D: except u want me become a culprit here >_>
