### ISSUE TITLE
Weapon Card equipped on Left Hand slot

### ISSUE THREAD

**Issue by mmo4th** [rathena/rathena#7659]
### rAthena Hash

da73084df50670337a8ecb9a7aa80bacbf87ccad

### Client Date

2023-01-05

### Server Mode

Renewal

### Result

Example Card:
`  - Id: 27361
    AegisName: Polluted_W_Man_Card
    Name: Contaminated Wanderer Card
    Type: Card
    Buy: 20
    Weight: 10
    Locations:
      Right_Hand: true
    Flags:
      BuyingStore: true
      DropEffect: CLIENT
    Script: |
      bonus2 bAddSize,Size_Large,30;
      bonus2 bAddSize,Size_Medium,30;`

When equipping a weapon with card on left hand slot, it does not give the weapon bonus.

![image](https://user-images.githubusercontent.com/105444810/226892372-ea2006cd-21e2-452d-975c-e916595ed460.png)

### Expected Result

Expect the item bonus to count even equipped on Left Hand with weapon card bonus.

### How to Reproduce

1. Equip 4x Card 27361 on a Knife vs no card Knife
2. Equip it on Left Hand Slot on Ninja class
3. Hit on Medium size monster barricade in training round
4. The result is same the item Bonus is not counted

### Official Information

Sample picture taken from iRO wiki "Cards from left hand (and right) are factored in.
![image](https://user-images.githubusercontent.com/105444810/226891492-54c9cbb4-0e70-45df-9dac-bb5e95e9ac7c.png)

**Comment by mmo4th** [comment]
> 

Here is 2nd result with both Knifes equipped as you can see the damage differs.

![image](https://user-images.githubusercontent.com/105444810/226958432-1ce05ded-6203-475d-94c7-38c839d95750.png)

**Comment by secretdataz** [comment]
When testing damage% bonuses, remember that they only apply to equipment portion of the ATK. So, testing with an equipment with ATK as low as a Knife[4] won't really make sense since the damage increase will be negligible. Even worse with bare right hand because we are multiplying with 0 here.

Tested with Maximize Power buff.
![image](https://user-images.githubusercontent.com/2021243/227078665-337e1095-e9db-47a9-bbfc-0793eba55cdf.png)
![image](https://user-images.githubusercontent.com/2021243/227078732-1d22d790-9280-4361-875b-c8dfffb82dc8.png)

**Comment by utoropia** [comment]
Can you test left hand with ninja class

**Comment by secretdataz** [comment]
Same result. There is no Assassin-exclusive dual wield code as far as I know.

![image](https://user-images.githubusercontent.com/2021243/227110910-4189e8cd-2c3a-47c9-8001-37d74fe6c5d6.png)
![image](https://user-images.githubusercontent.com/2021243/227110942-96f848b3-5ed2-4983-b692-7917c848539d.png)

**Comment by utoropia** [comment]
ขอดูเทียบก่อนหลังใส่การ์ดด้วยได้ไหมครับ

**Comment by secretdataz** [comment]
I think you can reproduce my tests easily with items and stats I've shown above if you want to test in additional scenarios. 😅

**Comment by utoropia** [comment]
อ้อ ผมสงสัยเจ้าของโพสต์เค้าบอกว่าผลการ์ดมือซ้ายมันไม่ทำงานอะครับ เลยอยากรู้ว่าถ้าเทียบแบบใส่การ์ดกับไม่ใส่ผลมันจะเหมือนกันมั้ย

**Comment by mmo4th** [comment]
Isn't the first picture with 4 scenarios enough to prove this?

Right hand with cards = 418 dmg
Left hand with cards = 394 dmg
Right hand without cards = 394 dmg
Left hand without cards = 394 dmg

?

**Comment by secretdataz** [comment]
> Isn't the first picture with 4 scenarios enough to prove this?
> 
> 
> 
> Right hand with cards = 418 dmg
> 
> Left hand with cards = 394 dmg
> 
> Right hand without cards = 394 dmg
> 
> Left hand without cards = 394 dmg
> 
> 
> 
> ?

Did you not read my comments...?
