### ISSUE TITLE
[Error]: status_change_start: Invalid status change (-1)! when mercenary uses Berserk

### ISSUE THREAD

**Issue by Leemonn** [rathena/rathena#7663]
### rAthena Hash

6673e1a7864002dfb303f89e2033e60d8cc2e065

### Client Date

2015-11-04

### Server Mode

Pre-Renewal

### Result

Error is thrown when the mercenary uses the skill Berserk

### Expected Result

No error should be thrown.

### How to Reproduce

1. Do `@item 12172`
2. Use the item
3. Use your mercernary's Berserk skill
4. Check Map Server

### Official Information

-

**Comment by mplaten** [comment]
status is not declared at db/pre-re/skill_db.yml

same problem with MS_REFLECTSHIELD and others

need to declare status in skill ids 8202, 8204, 8205 and 8206:

  - Id: 8202
    Name: MS_MAGNUM
    Description: Magnum_Break
    MaxLevel: 10
    Type: Weapon
    TargetType: Self
    DamageFlags:
      Splash: true
    Flags:
      TargetTrap: true
    Hit: Single
    HitCount: 1
    Element: Fire
    SplashArea: 2
    Knockback: 2
    AfterCastWalkDelay: 2000
    Duration1: 2000
    Duration2: 10000
    Requires:
      HpCost:
        - Level: 1
          Amount: 20
        - Level: 2
          Amount: 20
        - Level: 3
          Amount: 19
        - Level: 4
          Amount: 19
        - Level: 5
          Amount: 18
        - Level: 6
          Amount: 18
        - Level: 7
          Amount: 17
        - Level: 8
          Amount: 17
        - Level: 9
          Amount: 16
        - Level: 10
          Amount: 16
      SpCost: 30
    Status: Sub_Weaponproperty      
  - Id: 8204
    Name: MS_PARRYING
    Description: Parry
    MaxLevel: 10
    Type: Weapon
    TargetType: Self
    DamageFlags:
      NoDamage: true
    Hit: Single
    HitCount: 1
    Duration1:
      - Level: 1
        Time: 15000
      - Level: 2
        Time: 20000
      - Level: 3
        Time: 25000
      - Level: 4
        Time: 30000
      - Level: 5
        Time: 35000
      - Level: 6
        Time: 40000
      - Level: 7
        Time: 45000
      - Level: 8
        Time: 50000
      - Level: 9
        Time: 55000
      - Level: 10
        Time: 60000
    Requires:
      SpCost: 50
    Status: Parrying
  - Id: 8205
    Name: MS_REFLECTSHIELD
    Description: Shield_Reflect
    MaxLevel: 10
    Type: Weapon
    TargetType: Self
    DamageFlags:
      NoDamage: true
    Hit: Single
    HitCount: 1
    Duration1: 300000
    Requires:
      SpCost:
        - Level: 1
          Amount: 35
        - Level: 2
          Amount: 40
        - Level: 3
          Amount: 45
        - Level: 4
          Amount: 50
        - Level: 5
          Amount: 55
        - Level: 6
          Amount: 60
        - Level: 7
          Amount: 65
        - Level: 8
          Amount: 70
        - Level: 9
          Amount: 75
        - Level: 10
          Amount: 80
    Status: ReflectShield
  - Id: 8206
    Name: MS_BERSERK
    Description: Frenzy
    MaxLevel: 1
    Type: Weapon
    TargetType: Self
    DamageFlags:
      NoDamage: true
    Hit: Single
    HitCount: 1
    Duration1: 300000
    Duration2: 15000
    Requires:
      SpCost: 100
    Status: Berserk

**Comment by Playtester** [comment]
Berserk seems to be fixed already, even though it still works a bit different from official servers. For example it should have 200 SP cost.

**Comment by Playtester** [comment]
Magnum - should not cost HP (but still check for it) and does not give ATK bonus when used by Mercenary

**Comment by Playtester** [comment]
Got confirmation that it also should be 10 seconds in renewal. Will do a follow-up to fix that.
