### ISSUE TITLE
@clone command Fatal Error Received a crash signal

### ISSUE THREAD

**Issue by jofvgaming** [rathena/rathena#7664]
### rAthena Hash

370ee1e

### Client Date

2018-06-21

### Server Mode

Pre-Renewal

### Result

[Fatal Error]: Received a crash signal, trying to handle it as good as possible!
[Error]: Server received crash signal! Attempting to save all online characters!

### Expected Result

Expectedly clone the the character

### How to Reproduce

Fresh clone, configure and compile. launch client, use @clone playername then server crashed

### Official Information

@clone <player name/ID>

Spawns a clone of the specified player.

### Modifications that may affect results

No modification made, only uncomment PRE-RE

**Comment by aleos89** [comment]
As @mplaten asked, can you please provide a dump of the crash? Thanks.

**Comment by jofvgaming** [comment]
UPDATE!! rAthena Hash : 370ee1e


Program received signal SIGSEGV, Segmentation fault.
0x00000000004b89f0 in __exchange_and_add (__val=-1, __mem=0x69)
    at /opt/rh/devtoolset-7/root/usr/include/c++/7/ext/atomicity.h:49
49        { return __atomic_fetch_add(__mem, __val, __ATOMIC_ACQ_REL); }
Missing separate debuginfos, use: debuginfo-install glibc-2.17-326.el7_9.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-55.el7_9.x86_64 libcom_err-1.42.9-19.el7.x86_64 libgcc-4.8.5-44.el7.x86_64 libselinux-2.5-15.el7.x86_64 libstdc++-4.8.5-44.el7.x86_64 mariadb-libs-5.5.68-1.el7.x86_64 openssl-libs-1.0.2k-25.el7_9.x86_64 pcre-8.32-17.el7.x86_64 zlib-1.2.7-20.el7_9.x86_64
(gdb) bt full
#0  0x00000000004b89f0 in __exchange_and_add (__val=-1, __mem=0x69)
    at /opt/rh/devtoolset-7/root/usr/include/c++/7/ext/atomicity.h:49
No locals.
#1  __exchange_and_add_dispatch (__val=-1, __mem=0x69)
    at /opt/rh/devtoolset-7/root/usr/include/c++/7/ext/atomicity.h:82
        __val = -1
        __mem = 0x69
#2  _M_release (this=0x61)
    at /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/shared_ptr_base.h:151
No locals.
#3  std::__shared_count<(__gnu_cxx::_Lock_policy)2>::operator= (
    this=0x4e760f8, __r=...)
    at /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/shared_ptr_base.h:703
        __tmp = 0x97e5260
#4  0x0000000000556716 in operator= (this=<optimized out>)
    at /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/shared_ptr_base.h:1034
No locals.
#5  operator= (this=<optimized out>)
    at /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/shared_ptr.h:93
No locals.
#6  put (ptr=..., key=3999, this=0x22de340 <mob_db>)
    at ../common/database.hpp:228
        ptr = <error reading variable ptr (access outside bounds of object refer---Type <return> to continue, or q <return> to quit---
enced via synthetic pointer)>
        key = 3999
        this = 0x22de340 <mob_db>
#7  mob_clone_spawn (sd=sd@entry=0x974cc60, m=<optimized out>, x=x@entry=156,
    y=y@entry=178, event=event@entry=0x80b3d8 "", master_id=master_id@entry=0,
    mode=<optimized out>, flag=<optimized out>, duration=<optimized out>)
    at mob.cpp:4036
        mob_id = 3999
        inf = <optimized out>
        fd = <optimized out>
        md = <optimized out>
        status = <optimized out>
        db = std::shared_ptr (count 4, weak 0) 0x97e5270
        tree = <optimized out>
        __FUNCTION__ = "mob_clone_spawn"
#8  0x0000000000433848 in atcommand_clone (fd=12, sd=0x974cc60,
    command=<optimized out>, message=<optimized out>) at atcommand.cpp:9072
        message = <optimized out>
        command = <optimized out>
        sd = 0x974cc60
        fd = 12
#9  0x000000000043456d in is_atcommand (fd=fd@entry=12, sd=sd@entry=0x974cc60,
    message=message@entry=0x7fffffffdd50 "@clone WHYY", type=type@entry=1)
---Type <return> to continue, or q <return> to quit---
    at atcommand.cpp:11416
        command = "@clone", '\000' <repeats 249 times>
        params = "WHYY", '\000' <repeats 251 times>
        output = "\001\000\000\000\000\000\000\000\354>\326\t\000\000\000\000\002\000\000\000\000\000\000\000\002\000\000\000\000\000\000\000\354>\326\t\000\000\000\000\017\000\000\000\000\000\000\000t\313\371\017\000\000\000\000\303\064R\000\000\000\000\000\001\000\000\000\000\000\000\000\330\331\377\377\377\177\000\000\000\000\000\000\000\000\000\000\232\062R\000\000\000\000\000\020\001\377\377\026\001\000\000\026\000\000\000\060\000\000\000\037\002\000\000#\000\000\000\026\000\000\000\026\000\000\000\060\000\000\000\000\000\000\000\"\000\000\000\000\000\000\000\260\064-\000\000\000\000\000\037\002\000\000\000\000\000\000\223EV", '\000' <repeats 25 times>, "\"", '\000' <repeats 15 times>...
        atcmd_msg = "@clone WHYY\000\000\000\000\000\211)z\000\000\000\000\000\330\333\377\377\377\177\000\000\000\000\000\000\000\000\000\000\270\212\025\f\000\000\000\000P\336\377\377\377\177\000\000\313\024\337\365\377\177\000\000\001\200\255\373\000\000\000\000P\336\377\377\377\177\000\000P\336\377\377\377\177\000\000P\336\377\377\377\177\000\000P\336\377\377\377\177\000\000b\336\377\377\377\177\000\000\377\377\377\377\377\377\377\377P\336\377\377\377\177\000\000\377\377\377\377\377\377\377\377", '\000' <repeats 40 times>, "\b\000\000\000\000\000\000\000\004\000\000\000\000\000\000\000\000\000|", '\000' <repeats 13 times>...
        ssd = 0x974cc60
        info = <optimized out>
        is_atcommand = <optimized out>
---Type <return> to continue, or q <return> to quit---
#10 0x000000000047a4ae in clif_process_message (sd=sd@entry=0x974cc60,
    whisperFormat=whisperFormat@entry=false,
    out_name=out_name@entry=0x7fffffffdd30 "WHYY",
    out_message=out_message@entry=0x7fffffffdd50 "@clone WHYY",
    out_full_message=out_full_message@entry=0x7fffffffde50 "WHYY : @clone WHYY") at clif.cpp:10656
        seperator = 0x8043a0 " : "
        fd = 12
        info = <optimized out>
        packetLength = <optimized out>
        inputLength = <optimized out>
        input = <optimized out>
        message = <optimized out>
        nameLength = <optimized out>
        messageLength = <optimized out>
#11 0x00000000004a39f2 in clif_parse_GlobalMessage (fd=12, sd=0x974cc60)
    at clif.cpp:11585
        name = "WHYY", '\000' <repeats 12 times>, "H\035\222\347\377\177\000"
        message = "@clone WHYY\000\000\000\000\000(\314^\006\000\000\000\000\b\216F\002\000\000\000\000\377\377\377\377\000\000\000\000(\000\000\000\060", '\000' <repeats 11 times>, "\302+R", '\000' <repeats 13 times>, "\276\000\247\000\021\000\000\000`\314t\t\000\000\000\000\262\000\000\000\027\000\000\000p<\016\000\000\000\000\000\025\000\000\000\000\000\000\000$\240.\f\000\000\000\000\253\000\0---Type <return> to continue, or q <return> to quit---
00\000\000\000\000\000\300*T\000\000\000\000\000X\336\377\377\377\177\000\000\002\000\000\000\000\000\000\000\004\000\000\000\023\000\000\000\b\000\000\000\000\000\000\000\004\000\000\000\000\000\000\000h\005|\000\000\000\000\000\202\065\335\365\377\177\000\000\370x\264\005\000\000\000\000"...
        output = "WHYY : @clone WHYY\000\377\377\177\000\000p\336\377\377\377\177\000\000\000\375\000\000\000\000\000\000\337\326\037\006\000\000\000\000\003\000\000\000\000\000\000\000\244\201\000\000\000\000\000\000\363I\002\000\000\000\000\000\177n\024\000\000\000\000\000\317\r\000\000\000\000\000\000\000\020\000\000\000\000\000\000\b\000\000\000\000\000\000\000\213\257\060d", '\000' <repeats 20 times>, "\260-i\000\000\000\000\000uks\000\000\000\000\000\000\200\024\366\377\177\000\000X\346F\002", '\000' <repeats 36 times>, "\224\310|\345\377\177\000\000\000\000\000\000\000\000\000\000"...
        length = <optimized out>
        __FUNCTION__ = "clif_parse_GlobalMessage"
#12 0x000000000047f94b in clif_parse (fd=12) at clif.cpp:25281
        cmd = <optimized out>
        packet_len = 22
        sd = 0x974cc60
        pnum = 0
        cmd2 = -7057
#13 0x00000000007339a5 in do_sockets (next=<optimized out>) at socket.cpp:1024
        rfd = {fds_bits = {4096, 0 <repeats 15 times>}}
        timeout = {tv_sec = 0, tv_usec = 48253}
---Type <return> to continue, or q <return> to quit---
        ret = <optimized out>
        i = 12
#14 0x00000000007312b0 in handle_main (next=<optimized out>,
    this=0x7fffffffe0d0) at core.cpp:431
No locals.
#15 rathena::server_core::Core::start (this=this@entry=0x7fffffffe0d0, argc=1,
    argv=0x7fffffffe1d8) at core.cpp:390
        next = <optimized out>
#16 0x000000000040abca in main_core<rathena::server_map::MapServer> (
    argv=<optimized out>, argc=<optimized out>) at ../common/core.hpp:102
        server = {<rathena::server_core::Core> = {
            _vptr.Core = 0x7afa70 <vtable for rathena::server_map::MapServer+16>, m_status = rathena::server_core::RUNNING,
            m_type = rathena::server_core::MAP, m_run_once = false,
            m_crashed = false}, <No data fields>}
#17 main (argc=<optimized out>, argv=<optimized out>) at map.cpp:5276
No locals.

**Comment by jofvgaming** [comment]
@vstumpf  i try to apply your fix, and it works now !! Thank you for your contribution
