### ISSUE TITLE
@clone Recieved Only 1 Damage

### ISSUE THREAD

**Issue by krispaul27** [rathena/rathena#7667]
### rAthena Hash

198566204

### Client Date

20151104

### Server Mode

Pre-Renewal

### Result

clone Recieved Only 1 Damage From Player by Normal Attacks And Skills

### Expected Result

To Fix Clone Damage Recieved

### How to Reproduce

To Fix Clone Damage Recieved

### Official Information

To Fix Clone Damage Recieved

**Comment by aleos89** [comment]
Duplicate of #7579.
