### ISSUE TITLE
Undeclared HEADER_ZC_SEARCH_STORE_INFO_ACK 2010-08-03

### ISSUE THREAD

**Issue by Akkarinage** [rathena/rathena#7678]
### rAthena Hash

07660d17a

### Client Date

2010-08-03aRagexeRE

### Server Mode

Pre-Renewal

### Result

Compiling server for `#define PACKETVER 20100803` results in build errors.

### Relevant Log Output

```Shell
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2065	'HEADER_ZC_SEARCH_STORE_INFO_ACK': undeclared identifier (compiling source file clif.cpp)	map-server	C:\Server\src\map\clif_packetdb.hpp	1690
```

### Expected Result

No errors.

### How to Reproduce

Compile with the above packetver.

### Official Information

None.

### Modifications that may affect results

None.

**Comment by Lemongrass3110** [comment]
Fixed in d2e972c
