### ISSUE TITLE
2014-10-22 client bugs

### ISSUE THREAD

**Issue by sader1992** [rathena/rathena#768]
feeding pet make the exe stop working
 
roulette system showing the item that not Official in kro as Unknown item
 
can't diff the exe without SSO Login Packet cuz it will crash on login
 
and
 
adoption not work
 
^^^^^^^^
 
those all the errors in 22-10-2014

**Comment by julia40124009** [comment]
feeding pet work fine for me

**Comment by sader1992** [comment]
on 2014-10-22 ?

**Comment by aleos89** [comment]
1. Please read my comment in #510 for your issue with pets.
2. That's an issue with your iteminfo.lua being out of date or incorrect.
3. If the client is crashing from the SSO diff then that's related to the diff patcher you are using, not rAthena.
4. I believe I've seen a topic or bug somewhere about adoption not showing up.

I'll confirm this for adoption, the rest aren't issues with rAthena.

**Comment by sader1992** [comment]
thanks for #510 the pet feeding now work sorry
the iteminfo not the problem cuz i made the items and use it normal but when i put it in the roulette it's show as unknown item i use item_db.txt i tried to put the items in the sql too but still unknown item
for the sso login it's not work (without) it maybe from the client but maybe from the packet too i didn't so mush (Herculesan) players have this problem ,so if it work Hercules without sso then the problem from the packet of rathena not from the client
the adoption not work in any client +2014 so i think it must make issues for any client alone to know where it work and where not

**Comment by icxbb-xx** [comment]
adoption not working after 2013-08-xx comfirm

**Comment by aleos89** [comment]
@sader1992 keep in mind that if you are using pre-renewal then you will get unknown item issues too since Roulette doesn't exist in pre-renewal. It's setup so you can change to whatever items you want so it's not really an issue.

**Comment by sader1992** [comment]
i edit the renewal item_db and still unknown items 
i will search for solution any way
cuz it's the same in 2015 05 13

**Comment by Akkarinage** [comment]
The last outstanding matter in this issue was the adoption problem. Gravity has either removed the rightclick feature or broken it completely and is the topic of discussion on other official RO servers. IT's an issue with the client, and not something we can fix. @aleos89 implemented script commands in 0f5b6db to help with this removal.
