### ISSUE TITLE
Compile issue with Visual Studio 2015

### ISSUE THREAD

**Issue by secretdataz** [rathena/rathena#769]
Compiling rAthena with VS2015 will pop the error below for most files in rA source code and result in compile failure.

```
#error:  Macro definition of snprintf conflicts with Standard Library function declaration (compiling source file ..\src\common\conf.c)	char-server	c:\program files (x86)\windows kits\10\include\10.0.10150.0\ucrt\stdio.h	1927
```

Using commit : ad3a74b

**Comment by lighta** [comment]
Well we not supporting the build with vc140 atm. So that invalide per se but it a good feature request and it will be done.
In the meantime select all project in solution -> right click on propriety -> configuration -> toolset, change to v120, or v110. (yes that imply you have those sdk installed).

**Comment by Lemongrass3110** [comment]
Fixed in 86d6113.

**Comment by ranggo** [comment]
Hi,

I'm having this issue, trying to find as per lighta ;

project in solution -> right click on propriety -> configuration -> toolset, change to v120, or v110.

But I couldn't find this, it would be great if screenshot provided or a video. Any alternative?

Sorry, I'm zero to programming.

**Comment by Lemongrass3110** [comment]
We already have added support for VS2015. Just use rathena-14 solution.
