### ISSUE TITLE
Blast Mine

### ISSUE THREAD

**Issue by XanKriegor1** [rathena/rathena#7696]
### rAthena Hash

Latest

### Client Date

2022-04-06

### Server Mode

Pre-Renewal

### Result

According to iROwiki, the skill Blast Mine should do more damage based on the number of enemies that activate the trap.

### Expected Result

Skill Level * (50 + [DEX / 2]) * {1 + (INT / 100)} * Number of stacked monster

### How to Reproduce

However, I was unable to get the skill to do more damage by stacking more monsters into a tile.
My method of testing was spawning a large group of goblins(up to 10), gathering them in a single cell, placing the trap next to them and pushing the trap underneath the group. The drap does splash damage kills every goblin, but the damage to each of them is the same. Trying to get them to walk into the trap did not produce the results either.

### Official Information

https://irowiki.org/classic/Blast_Mine

**Comment by aleos89** [comment]
Unfortunately iRO Wiki isn't always a reliable source since iRO is known to modify skills. Maybe @Playtester has some insight here.

**Comment by XanKriegor1** [comment]
While you're checking this, please try and figure out what additional levels of Flasher trap do. Right now, as far as I can tell, they only reduce the duration of traps. The chance of inflicting Blind, and its duration, seem to be the same on all level.

**Comment by Playtester** [comment]
Multi-triggering of traps was removed with the Veins episode (11.2). As rAthena pre-re is based on the last episode of pre-renewal (13.2), there was no multi-triggering of traps in that episode.

If you want to enable multi-trigger of traps on your server, please check the forums for suggestions.
