### ISSUE TITLE
Wrong ViewID for Costume Archangel's Wings (20765)

### ISSUE THREAD

**Issue by llchrisll** [rathena/rathena#7697]
### rAthena Hash

22abdf8db

### Client Date

2022-04-06

### Server Mode

Renewal

### Result

According to the kRO itemInfo it should have ViewID 1, just like item 20500.
![image](https://user-images.githubusercontent.com/5730576/231475433-c9ae91fe-5998-421f-8d95-22ebb6c7d7ff.png)
But in the database it's 49.
![image](https://user-images.githubusercontent.com/5730576/231475094-45866978-c5e0-44f3-afeb-e645977bfc24.png)
Because of the that it tries to look for files, which were never added or even removed, ending up in an error.
`data/sprite/·Îºê/archangel_wing/`
![image](https://user-images.githubusercontent.com/5730576/231475974-1c9f3882-80b2-467b-ae50-ee15663df3f8.png)

### Expected Result

Using the same ViewID as stated in kRO itemInfo.

### How to Reproduce

1. Go ingame (without ignoring resource errors patch)
2. `@item 20765`
3. Switch to Costume tab
4. Get errored :O (or not if your client doesn't support it to begin with)

Note: I don't know which client exactly is required, so this Robe would be displayed.

### Official Information

See my decoded kRO iteminfo - look for ID 20765.
https://raw.githubusercontent.com/llchrisll/ROResourceCollection/master/kRO/System/itemInfo_true.lua

Also thanks to Ahmed Shawky on discord for making me check it. :)

**Comment by admkakaroto** [comment]
item 20765 and 20500 are diferent. 20765 have an animated sprite.

```
ROBE_WINGS = 1,
ROBE_Archangel_Wing = 49,
```

**Comment by llchrisll** [comment]
That folder doesn't exist, not in kRO nor any other server I have downloaded.
![image](https://user-images.githubusercontent.com/5730576/231483299-f2e36c66-2d7a-41f3-b4e3-c242a6ff3005.png)
So it causes resource error.

**Comment by admkakaroto** [comment]
i'm at work, i will check in a few hours.

**Comment by admkakaroto** [comment]
> The folder `data/sprite/·Îºê/archangel_wing/` doesn't exist, not in kRO nor any other server I have downloaded.

sorry I made a mistake, in fact I have the "Archangel_Wing" folder but it is not official, it has animated sprites however it is a copy of the "wing_of_angel_move" folder. You can disregard my previous comment.
