### ISSUE TITLE
Gate of Hell bonus part should ignore race/range/garment reductions.

### ISSUE THREAD

**Issue by Barigas** [rathena/rathena#771]
The HP/SP part(meaning everything else except 50_baselvl/100_atk) should only be reduced by Energy Coat, WoE reductions, Ghostring Card and Defender(if goh is lvl 5-10). Source: partially here in post number 7 https://forums.warpportal.com/index.php?/topic/98935-best-defense-against-gates-of-hell/#entry1109713 and here post number 4 http://forums.irowiki.org/showthread.php?t=90875. This part of damage should also ignore flee.
In addition, maybe due to some bug, on officials the atk part ignores ranged reductions from cards and items. This part should not ignore flee.

**Comment by Barigas** [comment]
Please, someone from officials post some screens. RussianRO has been closed a week ago, so I can't give any screens. Just use low hp GoH lvl1 against fully geared target, and you'll notice that the damage dealt is always higher than your lost hp.

**Comment by Lemongrass3110** [comment]
All good: "status:needs official info" only means that one of us has to confirm this on kRO, since irowiki isn't that reliable as a source all of the time. It is so that our developers with kRO accounts can filter out the open issues that need kRO confirmation easier.

**Comment by Paoly28** [comment]
rA test


it is also 
![screenjamro094](https://cloud.githubusercontent.com/assets/8035101/11389203/eaa1ee8c-9378-11e5-8a84-2725fdda9507.jpg)
![screenjamro095](https://cloud.githubusercontent.com/assets/8035101/11389204/eadf6f6e-9378-11e5-957a-4663e4c6b01d.jpg)

bugged when interacting with Neutral Barrier as both the atk portion and hp portion ignore flee whereas only the hp portion should hit.

![screenjamro093](https://cloud.githubusercontent.com/assets/8035101/11389149/35baf504-9378-11e5-92f3-f70b5b4090a0.jpg)
![screenjamro089](https://cloud.githubusercontent.com/assets/8035101/11389150/3611b088-9378-11e5-8af3-6f01aa0d9604.jpg)
![screenjamro090](https://cloud.githubusercontent.com/assets/8035101/11389151/36146a12-9378-11e5-939f-fa4e2e5ec09b.jpg)
![screenjamro091](https://cloud.githubusercontent.com/assets/8035101/11389152/361ae982-9378-11e5-8a0c-d21bc31f1037.jpg)
![screenjamro092](https://cloud.githubusercontent.com/assets/8035101/11389153/361fb9d0-9378-11e5-9cd3-d9a9b8c81ca8.jpg)


can confirm it is bugged in rathena as target has ahura mazdah and my hp portion should deal around an extra 30k+

**Comment by Barigas** [comment]
Things worth addinge here are(you can confirm it by tests on kRO):
1)Archer Skeleton card should not affect damage of GoH(not hp, not atk part) at all, no matter what skill lvl, even though lvl5-10 counts as ranged, it should not be increased by range atk mods nor decreased by ranged reductions(noxious, alligator...)
2)Neuteral Barrier of mechanic should totally block damage from GoH 5-10lvl. In addition, if Sura stands in Neuteral Barrier and casts GoH on target outside it, the whole damage should hit(so it works just like Dragon Breath with Neuteral Barrier).

**Comment by Paoly28** [comment]
1. Archer Skeleton Card does increase it. end game shura mvp'ing is using GoH with Erde ( it's partially mentioned on the thread in which you posted ).

2. Neutral Barrier partially blocks it, this is due to the fact that GoHs atk portion doesn't ignore flee. Neutral Barrier doesn't work like pneuma since NB only provides 100% perfect flee from ranged attacks hence why Acid Bomb igores NB ( and +25% def/mdef "this is missing from NB imma file other report for this" )

3. The Skill is psuedo elemental , it doesn't bypass element although it gains advantage from element it is still neutral and ghost reduces it regardless.

**Comment by Barigas** [comment]
1. No. it does not after the rebalance patch(where formulae went from pure 100-200*atk to the current one, very very long ago, there were no changes to GoH at 175/60 update). He maybe MvPing with whatever. Here is confirmation: https://forums.warpportal.com/index.php?/topic/161937-gates-of-hell-and-archer-skeleton-card/
2. No. It does not partially block. I know, that it makes all hit dependant atks miss from the barrier, but Gate of Hell is an exclusion in this case, maybe due to bug on officials. By some reason, on officials both atk and bonus part hit from the barrier, even though only the bonus part should. I've tested it.
3.That was exactly what I meant.

**Comment by Paoly28** [comment]
i actually agreed on you on 1 and 2 i just don't know how to put it lol. tried to shorten what you explained, i actually deleted part of my comment on 1 since yeah i asked a friend to test it and necro'ed old topics and confirmed that you are right.

and NB is really way to buggy on rA
