### ISSUE TITLE
Fourth & Expanded class jobs rebalance (2nd)

### ISSUE THREAD

**Issue by Pokye** [rathena/rathena#7716]
### rAthena Hash

https://github.com/rathena/rathena/commit/635add84d7372d4eea507afb587b485b7fdcd037

### Client Date

2023-03-04

### Server Mode

Renewal

### Result

The changes of rebalance the Fourth and Expanded class jobs rebalance (2nd) have not been implemented

### Expected Result

Updated skill behavior

### How to Reproduce

Use the skills and compare them with the patch notes

### Official Information

https://www.divine-pride.net/forum/index.php?/topic/3723-kro-jobs-improvement-project/&do=findComment&comment=12421
https://ro.gnjoy.com/news/devnote/View.asp?category=1&seq=4157430&curpage=1
https://ro.gnjoy.com/news/devnote/View.asp?category=1&seq=4159311&curpage=1
https://ro.gnjoy.com/news/notice/View.asp?BBSMode=10001&seq=7670&curpage=1

**Comment by eppc0330** [comment]
These webpage links you uploaded are about 3rd balance patch.

https://github.com/rathena/rathena/pull/7024

Detawulf's pull is including 2nd balance patch.

**Comment by codelia00822** [comment]
> These webpage links you uploaded are about 3rd balance patch.
> 
> #7024
> 
> Detawulf's pull is including 2nd balance patch.

I have checked battle.cpp which the skill damage formula have not been aligned to the damage multipler reference to the balance patch(2nd) and (3rd).

**Comment by Nicapone1** [comment]
??
