### ISSUE TITLE
mob_avail option not showing cart

### ISSUE THREAD

**Issue by lordganja** [rathena/rathena#772]
Git Hash: 'a47af467f3241c6e2227c4dcc89570c7644eb712'
Pre-renewal
2013-12-23 client

I tried to create a new mob based from a class and try to put a cart in the option. but all the carts isn't appearing. can anyone confirm this if this is also happen to yours? or is it just me? thanks.

mob_avail.txt
```
3129,4019,1,0,0,0,0,0,0,0,8,387
3130,4019,1,0,0,0,0,0,0,0,128,387
3131,4019,1,0,0,0,0,0,0,0,256,387
3132,4019,1,0,0,0,0,0,0,0,512,387
3133,4019,1,0,0,0,0,0,0,0,1024,387
```

**Comment by Lemongrass3110** [comment]
Dont forget that carts use status changes nowadays.
So it is not working like that anymore.

Maybe we should add a warning/documentation for that @aleos89? Would say this one is working as intended.

**Comment by lordganja** [comment]
@Lemongrass3110 
what do you mean by carts use status changes? anyway I tried the peco-peco and the falcon and it's working fine.

so I can't really add a cart on job based mobs? or do I have to do something first for the carts to appear?

**Comment by icxbb-xx** [comment]
new cart & new client >= 20120207

use status SC_PUSH_CART not use option OPTION_CART

**Comment by aleos89** [comment]
Yeah, since we don't control SC through mob_avail then this won't work. You can use the 'setunitdata' command now to change the SC and add the cart if you wish. Probably should update the documentation to state the changes.
