### ISSUE TITLE
@autoloot not working sometimes

### ISSUE THREAD

**Issue by amm0nition** [rathena/rathena#7725]
### rAthena Hash

7853e926c29fb8e91e32f893ebd2b97f1257ebb5

### Client Date

2022-03-28

### Server Mode

Renewal

### Result

1. I turned on `@autoloot`
2. I kill mobs
3. Sometimes I autolooted, sometimes I don't.
4. I didn't do any src modifications.

Here's a video showing the bug:
https://youtu.be/wbKKYLPvGio

Just turn on `@autoloot` and start mass-killing mobs (preferably with high-droprate items) then some items will randomly dropped instead of autolooted

**Comment by vstumpf** [comment]
Are these all monster drops? Or mapdrops? I don't have this dungeon or these mobs in my db.

**Comment by amm0nition** [comment]
> Are these all monster drops? Or mapdrops? I don't have this dungeon or these mobs in my db.

These are monster drops. It's a custom addition in mine, but these bug occurs with all mobs, doesn't have to be this specifically.

**Comment by vstumpf** [comment]
I've killed a bunch of mobs in mag_dun02 and autolooted everything, nothing was left on the ground.

**Comment by amm0nition** [comment]
I think I found the weird thing causing it. I tried remaking a fresh server with the same hash, but I didn't change anything in the conf files. 1x EXP rates, 1x Drop rates. All fine.
Then, I copied the `exp.conf` from my current server into this fresh server. Now the EXP rate is 100x, when I start killing mobs, the bug shows up.

**Comment by amm0nition** [comment]
Alright, I figured that it was my end's fault. I somehow played around with `idle_no_autoloot` in `battle/player.conf` not knowing that it does and making its value from default 0 to 1. I changed it back to 0 and now autoloot works as intended again.
I'll close this issue. You can label it as invalid.
