### ISSUE TITLE
Assassin Cross of Sunset's base values

### ISSUE THREAD

**Issue by XanKriegor1** [rathena/rathena#7726]
### rAthena Hash

latest

### Client Date

2022-04-06

### Server Mode

Pre-Renewal

### Result

I'm going through the process of reviewing skill descriptions, comparing it between sources and the actual values in rAthena.
While going through Assassin Cross of Sunset, I found a few discrepancies.
llChrisII's translation says that the base ASPD% increase ranges from 11~20%.
iROwiki Classic has the same values.
Ratemyserver's description is the same as well.

However, once I looked at the code, I found:

`case BA_ASSASSINCROSS:
		if (sd)
			val1 = pc_checkskill(sd, BA_MUSICALLESSON) / 2;
		val1 += 5 + skill_lv + (status->agi / 20);
		val1 *= 10; // ASPD works with 1000 as 100%
		break;`
The values for pre-renewal on rA right now are 5+1*skill level, which causes the skill to range from 6~15% ASPD. You only get
20% if you add the bonus from Musical Lesson. However, iROwiki lists the Musical Lesson bonus as being separate from the base levels.
So either rAthena's implementation is wrong, or every description for this skill is wrong.

### Expected Result

Descriptions and implementation should be the same.

### How to Reproduce

To make sure the code was indeed wrong, I tested using it with a Lord Knight.
MaxLevel Sunset with MaxLevel Musical lesson gives 20% ASPD. I then boosted the Clown's AGI to 200, in order to improve the effect by 10%.
Using Two-Hand Quicken on a Lord Knight with no stats(base 99 job 1) and a Katana increased ASPD from 145 to 161.
I then removed the self buff and used the Clown to buff the Lord Knight, and obtained the same value(145->161).
Since we know 2HQ gives 30% aspd and Sunset is giving me the same, I concluded my interpretation of the code was correct.

### Official Information

I checked iROwiki classic and ratemyserver, also the translations by llChrisll.

**Comment by aleos89** [comment]
Check out #1808 for more information on song effects.

**Comment by aleos89** [comment]
My assumption would be that there was no change between the pre-transcendent and post-transcendent patch. Maybe @Playtester could fill in if I'm mixing this up.

**Comment by Playtester** [comment]
The linked thread shows both post-trans and pre-trans values:

Post-trans:
case BA_ASSASSINCROSS: // yes even on pre-re its agi/20- even back to pretrans it does this way
	aspd = status->agi / 20 + skill_lv+5 + pc_checkskill(sd,BA_MUSICALLESSON)/2

Pre-trans:
riff
	(so only every 20 agi = 1% aspd)
	aspd +=  MusicLessonsLv()/2 + GetAgiValue()/20+ (skLevel+5)

As you can see, there is no difference.

And it also matches with the implementation in rAthena.
