### ISSUE TITLE
item db issue

### ISSUE THREAD

**Issue by hendra814** [rathena/rathena#773]
item "5592" Sigrun's Wings
desc got from 
http://www.divine-pride.net/database/item/5592/sigruns-wings
http://db.irowiki.org/db/item-info/5592/
Ear adornments that symbolize rebirth. They have the ability to change its effects depending on the job of the wearer. 
If worn by a Swordman, Merchant, Thief or Taekwon Classes, Str +1. 
If worn by a Mage, Acolyte, Ninja or Soul Linker Classes, Int +1. 
If worn by Archer or Gunslinger Classes, Dex +1. 
If worn by Novice Class, MaxHP +80, MaxSP +30. 

but the effect at item db look same like this for item effect
http://ratemyserver.net/index.php?iname=5592&page=re_item_db&quick=1&isearch=Search
If worn by a Swordman, Merchant, Thief or Taekwon Classes, aspd +1. 
If worn by a Mage, Acolyte, Ninja or Soul Linker Classes, matk +5 dan heal power +2%. 
If worn by Archer or Gunslinger Classes, long attack  +2%. 
If worn by Novice Class, MaxHP +120, MaxSP +60. 

and for item "18657" Pegasus Wing Ears
the item effect not apply in character,

**Comment by nanakiwurtz** [comment]
@hendra814 For item 18657, have you tried to test with a char on Base Level more or equal to 50 / 100 / 150?

**Comment by zackdreaver** [comment]
@hendra814 
ra's '5592' item script following kRO desc

**Comment by hendra814** [comment]
@nanakiwurtz , already try at 150 and under 150.
@zackdreaver , Thanks for the info

**Comment by cydh** [comment]
How if let's say it's RENEWAL Aspd bonus modifier works. The `bonus bAspdRate` doesn't give 'absolute' modifier value. If u say 3% of current ASPD, that 4% is still recalculated (weird way of RENEWAL :P).
````
amotion -= ( amotion - max_aspd ) * (status_calc_aspd(bl, sc, 2) + status->aspd_rate2) / 100;
````
http://irowiki.org/wiki/ASPD
you can help us to checkover if maybe we implemented it wrong
````			amotion = status_base_amotion_pc(sd,status);
#ifndef RENEWAL_ASPD
			status->aspd_rate = status_calc_aspd_rate(bl, sc, b_status->aspd_rate);

			if(status->aspd_rate != 1000)
				amotion = amotion*status->aspd_rate/1000;
#else
			/// aspd = baseaspd + floor(sqrt((agi^2/2) + (dex^2/5))/4 + (potskillbonus*agi/200))
			amotion -= (int)(sqrt( (pow(status->agi, 2) / 2) + (pow(status->dex, 2) / 5) ) / 4 + (status_calc_aspd(bl, sc, 1) * status->agi / 200)) * 10;

			if( (status_calc_aspd(bl, sc, 2) + status->aspd_rate2) != 0 ) // RE ASPD percertage modifier
				amotion -= ( amotion - pc_maxaspd(sd) ) * (status_calc_aspd(bl, sc, 2) + status->aspd_rate2) / 100;

			if(status->aspd_rate != 1000) // Absolute percentage modifier
				amotion = ( 200 - (200-amotion/10) * status->aspd_rate / 1000 ) * 10;
#endif
			amotion = status_calc_fix_aspd(bl, sc, amotion);
			status->amotion = cap_value(amotion,pc_maxaspd(sd),2000);

			status->adelay = 2*status->amotion;
````.


Then, the interesting case for me now, to 'revive' the absolute AspdRate bonus modifier as item bonus for Renewal.
````
			if(status->aspd_rate != 1000) // Absolute percentage modifier
				amotion = ( 200 - (200-amotion/10) * status->aspd_rate / 1000 ) * 10;
````

**Comment by nanakiwurtz** [comment]
So this is now a core bug isn't it?
If yes, maybe we should change the label from 'Bug: Database' into 'Bug: Core'

**Comment by cydh** [comment]
well, finally I can say that this is working as intended. Easier to say, ASPD rate bonus in Renewal is nerfed. U will never get clean ASPD bonus as rate mentioned.
This is the practice experience I can tell u.
When u wear gear that adds ASPD rate when ur ASPD is low at first place (eg. below 185), the gear's effect will be useless.
Another sample, I consumed Popping Candy (ASPD rate +25%) on Sniper with ASPD 180, I only get 4 ASPD addition.
That's about renewal ASPD that I can tell.
For the rest items,
## Please don't mix iRO's effect and RateMyServer (RMS grab script from emulator)


anyway, it's worth to make mod such `bonus bAspdRate2,n;` xD
