### ISSUE TITLE
Item ID 12341

### ISSUE THREAD

**Issue by mazvi** [rathena/rathena#7741]
### rAthena Hash

65200eba503fee3f8c492f241ed673c3b97b7ad7

### Client Date

2021-11-03

### Server Mode

Renewal

### Result

Item ID 12341
Script: getitem 7940,100;

### Expected Result

Item ID 12341
Script: getitem 7940,500;

### How to Reproduce

`@item 12341`
Then open it

### Official Information

https://www.divine-pride.net/database/item/12341/special-alloy-trap-box

**Comment by Pokye** [comment]
Solved! Please close this issue!

**Comment by Lemongrass3110** [comment]
Fixed in 2ba2473489b58cf7cd9cfedd445e50d00bd38711
