### ISSUE TITLE
sc->cant.attack being checked when sc = NULL is executed on a previous line

### ISSUE THREAD

**Issue by Leemonn** [rathena/rathena#7743]
### rAthena Hash

84bf6b87f1946f28055e90bf713cedd4f401c685

### Client Date

2015-11-04

### Server Mode

Pre-Renewal, Renewal

### Result

This method `status_check_skilluse` of `status.cpp` (line 1923) has the following coding:
```c++
bool status_check_skilluse(struct block_list *src, struct block_list *target, uint16 skill_id, int flag) {
	struct status_data *status;
	status_change *sc = NULL, *tsc;
	int hide_flag;

	status = src ? status_get_status_data(src) : &dummy_status;

	if (src && src->type != BL_PC && status_isdead(src))
		return false;

	if (!skill_id) { // Normal attack checks.
		if (sc && sc->cant.attack)
			return false;
```

But as you can see it makes no sense to check for `sc && sc->cant.attack`, because `sc` will always be `NULL`.

### Expected Result

-

### How to Reproduce

-

### Official Information

-

**Comment by Singe-Horizontal** [comment]
Indeed I noticed cases where you can use skills/items while being stunned for instance.
