### ISSUE TITLE
can't continue the quest

### ISSUE THREAD

**Issue by hendra814** [rathena/rathena#7744]
### rAthena Hash

lastest

### Client Date

2011-11-03

### Server Mode

Renewal

### Result

subjugation veins field 3 quest  with complete status when the server restarted because some issue when reenter the game
the quest can't continue.
here the screen shoot in game
https://i.postimg.cc/qqHGCjm0/screenr-Athena016.jpg

https://i.postimg.cc/65gpVgrd/screenr-Athena017.jpg

### Expected Result

can continue the quest

### How to Reproduce

complete the quest and then restart map server or do reloadscript command.

### Official Information

don't know

**Comment by Atemo** [comment]
According to your screenshot, you are trying to get the reward by having a lower level than the required level (95).
