### ISSUE TITLE
Slow Grace/Please Don't Forget Me discrepancies

### ISSUE THREAD

**Issue by XanKriegor1** [rathena/rathena#7747]
### rAthena Hash

Latest

### Client Date

2022-04-06

### Server Mode

Pre-Renewal

### Result

While going over skill descriptions and the code, I found another issue.
Both iROwiki, ratemyserver and the translated skill description state that this song gives -3% aspd and -2% movement speed per skill level.
However, on rAthena's code, I've found this instead:

```C++
        case DC_DONTFORGETME:
#ifdef RENEWAL
		val1 = 3 * skill_lv + status->dex / 15; // ASPD decrease
		val2 = 2 * skill_lv + status->agi / 20; // Movement speed adjustment.
#else
		val1 = 5 + 3 * skill_lv + status->dex / 10; // ASPD decrease
		val2 = 5 + 3 * skill_lv + status->agi / 10; // Movement speed adjustment.
#endif		
		if (sd) {
			val1 += pc_checkskill(sd, DC_DANCINGLESSON);
#ifdef RENEWAL
			val2 += pc_checkskill(sd, DC_DANCINGLESSON) / 2;
#else
			val2 += pc_checkskill(sd, DC_DANCINGLESSON);
#endif
		}
		val1 *= 10; //Because 10 is actually 1% aspd
		break;
```

The scaling on the skill on rAthena seems to be 5+3*SkillLv for both. Furthermore, the dancing lesson scaling doesn't match what's presented on iROwiki either.

So, which is correct? rAthena's implementation? Or is every skill description wrong?

### Expected Result

The descriptions should match the effect;

### How to Reproduce

.

### Official Information

I checkec iROwiki classic, rms and llchrisll's translation for pre-renewal.

**Comment by Playtester** [comment]
Please don't rely on descriptions, they are often wrong. iROwiki is mostly guess work and RMS is just based on how the original emulator implementation was unless yC gets around to update it after we fixed things.

If you search on Github for related issues instead, you would have found this: https://github.com/rathena/rathena/issues/1808

Related commit: https://github.com/rathena/rathena/commit/182557311b6691e3fe7bae3c627a4229af797128
