### ISSUE TITLE
Lady Luck/Fortune's Kiss discrepancies

### ISSUE THREAD

**Issue by XanKriegor1** [rathena/rathena#7748]
### rAthena Hash

latest

### Client Date

2022-04-06

### Server Mode

Pre-Renewal

### Result

While going over descriptions and checking the code, I found that this skill's implementation does not match any of the descriptions I found.
iROwiki, ratemyserver and the translated skill tip all state that you should gain +1% crit rate per skill level.
However, the rAthena implementation has:
`val1 = 10 + skill_lv + (status->luk / 10); // Critical increase`
As you can see, the skill currently gives 10 + 1*skill level.

So, once again, either our implementation is wrong, or every description of this skill is wrong.

### Expected Result

Descriptions should match implementation

### How to Reproduce

Using a dancer and any other character, just use the skill and watch the CRIT value on the skill window.

### Official Information

I checked ratemyserver, iROwiki and llchrisII's translation for descriptions

**Comment by Playtester** [comment]
Please don't rely on descriptions, they are often wrong. iROwiki is mostly guess work and RMS is just based on how the original emulator implementation was unless yC gets around to update it after we fixed things.

If you search on Github for related issues instead, you would have found this: https://github.com/rathena/rathena/issues/1808

Related commit: https://github.com/rathena/rathena/commit/182557311b6691e3fe7bae3c627a4229af797128
