### ISSUE TITLE
Shield Chain discrepancies

### ISSUE THREAD

**Issue by XanKriegor1** [rathena/rathena#7750]
### rAthena Hash

latest

### Client Date

2022-04-06

### Server Mode

Pre-Renewal

### Result

I was comparing rAthena's implementation of Shield Chain against iROwiki's article. That website states:
"ONLY stat-derived ATK contributes to damage. [STR](https://irowiki.org/classic/STR) greatly affects damage; [DEX](https://irowiki.org/classic/DEX) and [LUK](https://irowiki.org/classic/LUK) have a minor effect."
"Any other [ATK](https://irowiki.org/classic/ATK) - weapon ATK, weapon refinement, ATK-increasing cards or items - have NO effect on the damage."
While I was able to confirm by in-game testing that Weapon ATK is indeed ignored by the skill, when I tried using other +ATK sources such as Hillslion Card and Giant Whisper, those increased damage.
"The attack bonus gained from [Provoke](https://irowiki.org/classic/Provoke) or [Berserk](https://irowiki.org/classic/Berserk) does not affect the damage."
This was another discrepancy. I tried Shield Chain before and after having Lv10 Provoke cast upon myself and damage increased.

Of course, iROwiki is full of mistakes but I figured I'd post this bug report to see if perhaps this skill isn't working wrong.

### Expected Result

iROwiki article should match implementation

### How to Reproduce

Tested in PvP against players only.

### Official Information

https://irowiki.org/classic/Rapid_Smiting

**Comment by Playtester** [comment]
Almost fixed this already.
There are two fixes still missing:
- Shield Chain / Rapid Smiting actually gives a flat 20% base success chance, meaning it always should hit to 25% at least (min + 20%)
- When Shield Chain / Rapid Smiting misses, then it deals no damage at all (currently the weight / refine bonus is still applied)
