### ISSUE TITLE
status effects on skills missing local variable declaration

### ISSUE THREAD

**Issue by grimexile** [rathena/rathena#7759]
### rAthena Hash

latest <dfa7e5e08>

### Client Date

2021-11-03

### Server Mode

Renewal

### Result

rate is being used for status change but it wasn't declared in that instance. Located at Line 1327. Causes mapserver crash.

### Expected Result

Mapserver crash

### How to Reproduce

some instances of status change.

### Official Information

na

### Modifications that may affect results

declaring the rate local variable in the instance:

rate = it.rate;

**Comment by Atemo** [comment]
Please rephrase in a more understandable way

**Comment by grimexile** [comment]
Alright, my apologies.

If you open skill.cpp in map and jump to line 1327, you'll find the following code:

			// Trigger status effects on skills
			for (const auto &it : sd->addeff_onskill) {
				if (skill_id != it.skill_id || !it.rate)
					continue;

				if (it.target&ATF_TARGET)
					status_change_start(src, bl, it.sc, rate, 7, 0, 0, 0, it.duration, SCSTART_NONE, 100);
				if (it.target&ATF_SELF)
					status_change_start(src, src, it.sc, rate, 7, 0, 0, 0, it.duration, SCSTART_NONE, 100);
			}
			
This code is calling for the rate variable without declaring it. This causes map crashes, at least it does in my server.

It should be like this:


			// Trigger status effects on skills
			for (const auto &it : sd->addeff_onskill) {
				rate = it.rate;
				if (skill_id != it.skill_id || !it.rate)
					continue;

				if (it.target&ATF_TARGET)
					status_change_start(src, bl, it.sc, rate, 7, 0, 0, 0, it.duration, SCSTART_NONE, 100);
				if (it.target&ATF_SELF)
					status_change_start(src, src, it.sc, rate, 7, 0, 0, 0, it.duration, SCSTART_NONE, 100);
			}
			
Please let me know if this isn't clear enough and I apologize for before.
