### ISSUE TITLE
@reloadnpcfile causing scripts to unload, disappear or duplicate

### ISSUE THREAD

**Issue by Kiranetix** [rathena/rathena#7766]
### rAthena Hash

5443d566a787da87b3341fe4e07232ee1ee65177

### Client Date

2018-08-08

### Server Mode

Pre-Renewal

### Result

When using @reloadnpcfile, when reloading 2 different script files, the latest script reloaded will unload the previously reloaded script. Further reloads will cause the other reloaded scripts to unload, disappear or duplicate. This also causes dynamic NPC menu, like quest shop, to disappear.

### Expected Result

Scripts will not unload/disappear or duplicate

### How to Reproduce

1. Normally load /npc/custom/quests/quest_shop.txt
2. Normally load /npc/custom/healer.txt
3. use @reloadnpcfile to reload quest_shop.txt (@reloadnpcfile npc/custom/quests/quest_shop.txt)
4. use @reloadnpcfile to reload healer.txt (@reloadnpcfile npc/custom/healer.txt)
5. use @reloadnpcfile to reload quest_shop.txt (@reloadnpcfile npc/custom/quests/quest_shop.txt)

This will cause the healer npc to disappear.

...furthermore use @reloadnpcfile twice on the script that disappeared, console will throw duplicate npc warning

To fix the issue use @reloadscript. But the next time @reloadnpcfile is used on 2 or more different scripts, the same issue will occur.

### Official Information

N/A

### Modifications that may affect results

NONE, I'm using fresh rAthena.

**Comment by Melk3000** [comment]
Confirmed.

**Comment by Triedge** [comment]
Confirm :(

**Comment by sinju92** [comment]
Confirm 1000%
