### ISSUE TITLE
Crash Signal and warnings (WFIFOSET)

### ISSUE THREAD

**Issue by Zeloss** [rathena/rathena#777]
Using: d46cf4b35ee66910df1f9582abada8bef7c54c30
Renewal
Client: 2013-08-07

When someone log in the server crash, sometimes didn't crash but the NPCs are invisible and it shows warnings:
[ Warning ] : WFIFOSET: Attempted to send zero-length packet, most likely 0x6172 (please report this).
[ Warning ] : WFIFOSET: Attempted to send zero-length packet, most likely 0x0000 (please report this)
[ Warning ] : WFIFOSET: Attempted to send zero-length packet, most likely 0x007f (please report this).
[ Warning ] : WFIFOSET: Attempted to send zero-length packet, most likely 0xffff (please report this).
[ Warning ] : WFIFOSET: Attempted to send zero-length packet, most likely 0xb732 (please report this).
[ Warning ] : WFIFOSET: Attempted to send zero-length packet, most likely 0x05c4 (please report this).

**Comment by icxbb-xx** [comment]
please , post Crash log by GDB when you server crashing
thank you

**Comment by Lemongrass3110** [comment]
Do you have any scripts that spam effects or something like this on login? We had some similar reports in the last time and they were all related to custom scripts flooding the packet buffers of the session.

**Comment by Lemongrass3110** [comment]
If you cant give us anymore input on this issue, we have to close it.
It have been 14 days now, so we will give you 16 days until we close it(in total: 30days).
