### ISSUE TITLE
bonus2 bSkillCooldown not working properly

### ISSUE THREAD

**Issue by sonniez** [rathena/rathena#7770]
### rAthena Hash

ccd7e5c14a432469b68f0bd731712887deb1224e

### Client Date

2022-07-20

### Server Mode

Renewal

### Result

Such as "WL_TELEKINESIS_INTENSE" that have cooldown 300 sec, when wearing ItemID ( 410129 + 19272(with 4365) + 490079 + 490079 ) to reduce cooldown of "WL_TELEKINESIS_INTENSE" skill to 350 sec. But when using "WL_TELEKINESIS_INTENSE" skill, it still have a cooldown.

### Expected Result

bonus2 bSkillCooldown should remove cooldown of skills when their bonus reach skills cooldown.

### How to Reproduce

wearing itemID 410129 + 19272(with 4365) + 490079 + 490079 to reduce cooldown of "WL_TELEKINESIS_INTENSE"

### Official Information

-

**Comment by MrBzai** [comment]
same issue happens to WL_COMET with   item ID: 5966 (KarduiEar) ,item ID: 2198 (Lapine_Shield) combo equipped.
