### ISSUE TITLE
Player can leave jail after relogin

### ISSUE THREAD

**Issue by fab10Carvalho** [rathena/rathena#7771]
### rAthena Hash

ccd7e5c14a432469b68f0bd731712887deb1224e

### Client Date

20220406

### Server Mode

Renewal

### Result

Player can leave jail after relogin

### Expected Result

Players must not be able to leave jail by relogin

### How to Reproduce

1. gm type @jailfor 5mn Playername
2. Player relogin
3. After this player will leave jail and return last savepoint

### Official Information

.

**Comment by iberryRO** [comment]
I confirm
have tried according to it and it is true
In addition, players are put in prison. will not be able to move to another map

**Comment by grimexile** [comment]
Happened to me, it made me disable the macro_detector functions for my server because players kept bugging out.

**Comment by Chaoszinho** [comment]
Happen to me too , see this @Lemongrass3110  plx

**Comment by Chaoszinho** [comment]
happen to me too
