### ISSUE TITLE
Client can login with server (S) type account

### ISSUE THREAD

**Issue by Litro** [rathena/rathena#7772]
### rAthena Hash

ccd7e5c14

### Client Date

2021-11-03

### Server Mode

Pre-Renewal

### Result

Client can login with server (S) type account

### Relevant Log Output

```Shell
[Debug]: Sending the client (1 127.0.0.1) to char-server rAthena with ip 127.0.0.1 and port 6121
```

### Expected Result

Client shouldn't be able to login with server account credential

### How to Reproduce

Just try login with server account username and password

### Official Information

I don't know

**Comment by mazvi** [comment]
whose character comes after that?

**Comment by Litro** [comment]
it come to char select with 0 character created

**Comment by reunite-ro** [comment]
just curious, does this will make the server dc ? since its already online when someone trying to access.
