### ISSUE TITLE
Elemental Reistance Potions

### ISSUE THREAD

**Issue by dragonis1701** [rathena/rathena#779]
So... The Elemental Resistance Potions do not take effect until the player changes their armor; whether the player simply just unequips or changes their armor to a different one. I changed their variables in the itemdb to better reflect card values, by changing 12118 to -50, 0, 75, 0, with their respective values being: Cold Resistance, Earth Resistance, Fire Resistance, and Wind Resistance just to see more easily if they were working. 

Test 1, without changing armor and with fireproof potion buff active (I also added buff icons so I could see them when they were in effect), Kasa dealt 4k fire ball and 26k fire breath. 

Test 2, with already changed armor and with fireproof potion buff active, kasa dealt 1k fire ball and 5k fire breath.

Test  3, without changing armor and with fireproof potion buff no longer active, kasa dealt 1k fire ball and 5k fire breath.

Test 4, with already changed armor and with fireproof potion buff no longer active, kasa deals 4k fire ball and 26k fire breath.

Test  5, without changing armor and with fireproof potion buff active again, kasa deals 4k fire ball and 26k fire breath.

These five tests were done in the order as they are mentioned to better show what I mean. I can also provide video if necessary.

**Comment by cydh** [comment]
I can confirm it by source reading.
Indeed, the resist calculation is done on pc status' calculation.

**Comment by cydh** [comment]
@dragonis1701 says
>The fix of elemental resistance potions by converting all elemental changes to a new section called:
void status_calc_def_ele_pc(struct map_session_data *sd, struct status_change *sc) {

Elemental resistance potions do not lose their effect. Whether the player is dispelled, dies or the timer runs out. The effect never stops until the player changes armor, changes map or logins out after the effect has ended. It's pretty much the same as #779 except the effect now starts when the player uses the item but the effect does not end. 

Oddly enough, this does not apply to Providence. This does apply to the Undead Element Scroll and Sorcerer's Summons Defensive abilities. SC_ARMOR_ELEMENT, SC_ARMOR_RESIST, SC_FIRE_CLOAK, SC_WATER_DROP, SC_WIND_CURTAIN and SC_STONE_SHIELD.
