### ISSUE TITLE
Waring complie Rathena last github.

### ISSUE THREAD

**Issue by hnomkeng** [rathena/rathena#780]
![screenshot_2015-11-27-14-28-38-260](https://cloud.githubusercontent.com/assets/9112684/11436088/c81e70be-9513-11e5-92e2-bbaebfd34766.jpeg)

Rathena. version last github. (27-11-15)
OS. Centos 6.6
gcc. 4.4.7

@aleos89 @icxbb-xx

**Comment by icxbb-xx** [comment]
Try check

https://github.com/rathena/rathena/commit/25cb15161f00e636a1cd4091f7784c1877143e78

**Comment by hnomkeng** [comment]
@icxbb-xx  "clif.c:2419: warning: ‘clif_add_random_options’ defined but not used"

**Comment by hnomkeng** [comment]
![untitled-3](https://cloud.githubusercontent.com/assets/9112684/11441130/8d4b6ed8-953b-11e5-8aaf-f249341ab0ee.jpg)

**Comment by icxbb-xx** [comment]
static void clif_add_random_options(unsigned char* buf, struct item* item)

เป็น

void clif_add_random_options(unsigned char* buf, struct item* item)

**Comment by hnomkeng** [comment]
what เป็น ?

**Comment by icxbb-xx** [comment]
Fixed in https://github.com/rathena/rathena/commit/c7d73711fdacc9cad9860aff9241ca1ec5e86050

Thank you for report
