### ISSUE TITLE
Helm Of Abyss (5363)

### ISSUE THREAD

**Issue by ernestfegarido** [rathena/rathena#781]
i think the item script is wrong
5363,Helm_Of_Abyss,Helm Of Abyss,4,20,,1000,,2,,1,0x000654E2,63,2,256,,70,1,371,{ bonus2 bSubRace,RC_DemiHuman,-10; bonus2 bSubRace,RC_Player,-10; bonus2 bSubClass,Class_Boss,10; },{},{}

must use "bonus2 bAddRace" because the item description say that this item gives tolerance to demi human and boss monster right?

reference: http://db.irowiki.org/db/item-info/5137/
![abyss](https://cloud.githubusercontent.com/assets/4651777/11442036/a488dcf0-954c-11e5-93ae-830ba43ef010.JPG)

**Comment by nanakiwurtz** [comment]
@ernestfegarido "Add tolerance" means 'to reduce damage from' right?

**Comment by Atemo** [comment]
Increase tolerance mean reduce damage.

According to http://ro.gnjoy.com/guide/runemidgarts/itemview.asp?itemSeq=2&ID=5363 the damage received should be 5% and it should only apply on monster

**Comment by ernestfegarido** [comment]
so why is that alice doll is giving more reduction than abyss helm. so i guess alice doll has a wrong script. try to compare both :)

**Comment by Historica** [comment]
Please do not confuse iRO item desc table with kRO effect.

iRO : All job , reduce 10% damage taken from demi human and boss'
kRO : Swordman/Merchant/Thief class , reduce 10% damage taken from boss and increase 5% damage taken from non-boss
jRO : All job , Reduce 10% damage taken from boss and increase 10% damage taken from non-boss
idRO : Swordman/Merchant/Thief , Reduce 10% damage taken from boss and increase 10% damage taken from non-boss

bSub(Race/Class) = damage reduction from target race/class
bAdd(Race/Class) = damage boost to target race/class

**Comment by nanakiwurtz** [comment]
@Historica Is it really only affect Swordman/Merchant/Thief class ?
I read on gnjoy that it doesn't have any class restriction

**Comment by ernestfegarido** [comment]
here's the replay file watch it :)

https://mega.nz/#!nocDEJiY!FANmO7i09uBQo4SJSKTmc5ZdCmkYROtzyZMxC7rIEmQ

**Comment by Historica** [comment]
Did you read the link listed on 3rd post ?

장착 : 검사 / 상인 / 도둑 계열
Configuration: Prosecutor/merchant/burglar system

직업계열 검사 계열, 도둑 계열, 상인 계열
Occupational system prosecutor system, burglar system and merchant system

**Comment by cydh** [comment]
@Historica idk from which source u said that effect of idRO ver. This is idRO effect mostly works
>5363#
>Helm yang dipakai oleh Abysmal Knight dengan kelebihan dan kekurangannya.
>Meningkatkan ketahanan sebesar 10% dari Boss monster ketika terkena serangan fisik.
>**Increase 10% resistance of physical damage from Boss monster (Reduce 10% damage received from Boss monster)**
>Mengurangi ketahanan sebesar 10% dari monster Demihuman ketika terkena serangan fisik.
>**Reduce 10% resistance of physical damage from Demihuman (Increase 10% damage received from Demihuman)**
>Jenis : ^777777Headgear^000000 Tk Def : ^7777779^000000
>Dikenakan di: ^777777Atas^000000 Berat: ^777777100^000000
>Level Persyaratan : ^77777770^000000
>Profesi: ^777777Swordman, Merchant, Thief^000000
>**Class: Swordman, Merchant, Thief**
>#

The kRO effect are
> Increase 5% damage received from 'Normal'
> Reduce 10% damage from 'Boss'

So it must be
````
bonus2 bSubClass,Class_Normal,-5;
bonus2 bSubClass,Class_Boss,10;
````

The jobs mentioned isn't script exception, it's equip restirction.

**Comment by nanakiwurtz** [comment]
Well now I'm confused of which source should I use.... -_-'

**Comment by nanakiwurtz** [comment]
Current kRO effect is:
> 심연의 기사가 쓰는 투구. 강한 공격에 대한 내성은 강하나 오히려 약한 공격에 취약한 면을 보인다.
보스형 몬스터로부터 받는 공격에 대한 내성 10% 증가
일반형 몬스터로부터 받는 공격에 대한 내성 5% 감소
계열 : 투구 방어 : 9
위치 : 상단 무게 : 100
요구레벨 : 70
장착 : 검사 / 상인 / 도둑 계열
