### ISSUE TITLE
error "skill _require_db" for pre-renewal mode.

### ISSUE THREAD

**Issue by hnomkeng** [rathena/rathena#782]
![untitled-2](https://cloud.githubusercontent.com/assets/9112684/11445042/8b4507c8-955b-11e5-960b-b550629aaea8.jpg)

[Error]: skill_parse_row_requiredb: Invalid item (in EQUIP_REQUIRE list)  1549 for skill 2257.
[Error]: sv_readdb: Could not process contents of line 683 of "db/pre-re/skill_require_db.txt".
[Error]: skill_parse_row_requiredb: Invalid item (in EQUIP_REQUIRE list)  2801 for skill 2263.
[Error]: sv_readdb: Could not process contents of line 689 of "db/pre-re/skill_require_db.txt".

Rathena version : 15182  (pre-renewal)

@Lemongrass3110 , Thank you for fixed.

**Comment by Dark8008** [comment]
I have the same problem !

**Comment by hnomkeng** [comment]
@Dark8008 copy item number for re to pre-re to fix.
