### ISSUE TITLE
2015-05-13aRagexe

### ISSUE THREAD

**Issue by ernestfegarido** [rathena/rathena#783]
client crash when feeding sohee pet.

mode: renewal
client: 2015-05-13aRagexe

**Comment by icxbb-xx** [comment]
aleos89 commented 7 days ago
Please read my comment in #510 for your issue with pets.
That's an issue with your iteminfo.lua being out of date or incorrect.
If the client is crashing from the SSO diff then that's related to the diff patcher you are using, not rAthena.
I believe I've seen a topic or bug somewhere about adoption not showing up.
I'll confirm this for adoption, the rest aren't issues with rAthena.
