### ISSUE TITLE
memmgr_alloc failed

### ISSUE THREAD

**Issue by Angelic234** [rathena/rathena#7831]
### rAthena Hash

https://github.com/rathena/rathena/commit/2ba2473489b58cf7cd9cfedd445e50d00bd38711

### Client Date

2022-06-20

### Server Mode

Renewal

### Result

[Fatal Error]: Memory manager::memmgr_alloc failed (allocating 28+269950976 bytes at H:\rathena - 20190128\src\common\timer.cpp:233).

### Expected Result

map crash

### How to Reproduce

I make an item，If player click item and not move in  1 min, he will get an item.
`freeloop(1);
while(1){
	getmapxy(.@mapname$, .@mapx, .@mapy, BL_PC);
	for (.@k = 0;.@k<=10;.@k++){
		sleep2 5000+rand(1500);
		if ((.@mapname1$!=.@mapname1$)||(.@mapx1!=.@mapx)||(.@mapy1!=.@mapy)){
			showscript "You'are not AFK",getcharid(3),SELF;
			end;
		}
	}
	getitem 512,1;
}`

 When many player afk and execute item script , after 1 or 2 days ago , server crash and show the message.

### Official Information

N/A

**Comment by Lemongrass3110** [comment]
This is a problem of your script in addition with running out of RAM.
