### ISSUE TITLE
bonus2 bAddClass,c,x not working as intended.

### ISSUE THREAD

**Issue by Varyss** [rathena/rathena#784]
bonus2 bAddClass,Class_All,100 only adds ~20% damage. none at all without weapon.

why did they always use that instead of bonus bAtkRate when the description clearly says +x% ATK, anyway?

**Comment by Barigas** [comment]
Once again, read this plz http://irowiki.org/wiki/Atk ... In renewal, all %add damage bonuses(agains race, element, size, % atk bonus and so on) affect only equip atk. So, if you have 200status+50equip atk, then your +100% damage will affect only 50 atk, so 200+50*2=300, here is your ~20% damage.
Working as intended, I guess.

**Comment by Varyss** [comment]
whoops. I didn't know that, sorry.
still that means that there are lots of misleading descriptions on equipments.
