### ISSUE TITLE
Implement the Level 260/55

### ISSUE THREAD

**Issue by Pokye** [rathena/rathena#7842]
### Is your request related to a missing official feature?

Yes

### Describe the solution you'd like

In the fourth quarter of 2022, KRO updated the level to 260/55. So it would need Base/Job EXP and HP/SP and Stats as well.
![image](https://github.com/rathena/rathena/assets/98105181/f248e8f9-2a73-423a-9e55-3064428d99eb)

https://ro.gnjoy.com/news/devnote/View.asp?category=1&seq=4157430&curpage=1
https://ro.gnjoy.com/news/notice/View.asp?BBSMode=10001&seq=7670

**Comment by eppc0330** [comment]
For reference.
HP/SP db in rA over Lv 175 is all wrong, compared with official KRo.
Overall, HP/SP in official KRo is much higher than the ones in rA.
So to implement max level we need to figure out this problem.
