### ISSUE TITLE
Pre Renewall SPIRALPIERCE

### ISSUE THREAD

**Issue by brenobaroni** [rathena/rathena#7846]
### rAthena Hash

fe4234cd3

### Client Date

2018-08-19

### Server Mode

Pre-Renewal

### Result

When SPIRALPIERCE 397 / LK_SPIRALPIERCE is casted on monster that isnt agressive by 1 cell range the monster becomes aggressive, if cast SPIRALPIERCE 397 / LK_SPIRALPIERCE by 1cell+ the mosnter not becomes aggressive.

### Expected Result

After cast the monster must become agressive 
regardless of the distance.

### How to Reproduce

In all the maps, class LK using SPIRALPIERCE  on mobs that isn`t agressive.

### Official Information

After cast the monster must become agressive 
regardless of the distance.

**Comment by Playtester** [comment]
Can confirm this but it's not easy to fix.

It seems that monsters only unlock the target on official servers if they are stopped for long enough. Stopping for just 1 second will not unlock the target, but stopping for longer will.

**Comment by Playtester** [comment]
Actually there is a quick fix for it, changing:
`	if (md->target_id) {
		md->target_id=0;
		md->ud.target_to = 0;
		unit_set_target(&md->ud, 0);
	}`
To:
`	if (md->target_id && DIFF_TICK(tick, md->ud.canmove_tick) > 1000) {
		md->target_id=0;
		md->ud.target_to = 0;
		unit_set_target(&md->ud, 0);
	}`
But I'm not sure if this has any side effects.

**Comment by Playtester** [comment]
Here are some more related issues I found while testing this:

- Spiral Pierce should have a range of 4 and not 5
- Monsters do indeed switch to idle mode without dropping target (they can use up to 2 idle skills and still keep aggro)
- Monsters drop target when no player is left on the map (in rAthena there's a bug that they will keep their target forever here - this is easy to fix we need to set mob_active_time and boss_active_time to 1000ms in monster.conf)
