### ISSUE TITLE
When character die, cannot use @raisemap if all_permission = true

### ISSUE THREAD

**Issue by reunite-ro** [rathena/rathena#7848]
### rAthena Hash

https://github.com/rathena/rathena/commit/fe4234cd39e341985b1006a371acf9119a3ae248

### Client Date

20210304

### Server Mode

Renewal

### Result

If all_permission from groups.yml groupid 99 enabled, if the character dies, we cannot use @raisemap

### Expected Result

If all_permission is not enabled, we can use @die and @raisemap without any issue.
Only happens when all_permission is enabled.

'You can't use commands while dead'.

### How to Reproduce

Test with disable all_permission as default.
`@die` and `@raisemap`
No problem for this one.

Then try with enable all_permission.
`@die` and `@raisemap`
'You can't use commands while dead'.

### Official Information

None

**Comment by vstumpf** [comment]
This is because with `all_permission: true`, `disable_commands_when_dead` gets set to true.
You would have to disable this permission after enabling all permissions

```yaml
  all_permission: true
  disable_commands_when_dead: false
```

**Comment by CairoLee** [comment]
> This is because with `all_permission: true`, `disable_commands_when_dead` gets set to true.
> 
> You would have to disable this permission after enabling all permissions
> 
> 
> 
> ```yaml
> 
>   all_permission: true
> 
>   disable_commands_when_dead: false
> 
> ```

Who designed this permission... normally getting permission should give you more freedom than not having it. This option should be changed to "allow_commands_when_death" to make more sense!

😂

**Comment by reunite-ro** [comment]
> This is because with `all_permission: true`, `disable_commands_when_dead` gets set to true. You would have to disable this permission after enabling all permissions
> 
> ```yaml
>   all_permission: true
>   disable_commands_when_dead: false
> ```

To be honest its a little bit weird because without all_permission, they can use commands while dead, but with all_permission we need to add disable_commands_when_dead. Its more restricting for all_permission for this part.

Which means, without all_permission, they shouldnt get to use the commands while dead too.

**Comment by vstumpf** [comment]
> This option should be changed to "allow_commands_when_death" to make more sense!

I agree. This perm has been in the code forever.

> Its more restricting for all_permission for this part.

Unfortunately, this specific permission reversed; when enabled it effectively remove capabilities, as opposed to all the others that add capabilities.

It might be possible to change it in the future to change the permission, but I don't think we should change the behavior of all_permission; it should turn all permissions on.

If you want to change it yourself in src, you can just turn off this permission in all_permission
