### ISSUE TITLE
Error display HP of Monsters

### ISSUE THREAD

**Issue by Dark8008** [rathena/rathena#785]
![untitled](https://cloud.githubusercontent.com/assets/14345362/11456407/43cd0444-96ba-11e5-910c-000d26790a0e.png)

**Comment by Baalberith6** [comment]
You need to adjust show_mob_info preference in conf/monster.conf to show HP instead of %

**Comment by icxbb-xx** [comment]
Yes we, discuss for big hp bar boss, mvp , miniboss
in new client 2015

**Comment by Dark8008** [comment]
I use 2014 client @@

**Comment by icxbb-xx** [comment]
@Dark8008 , this problem 2013-12-23 or high
kro use new packet for this

**Comment by anacondaqq** [comment]
offtop.
WOW! Big HP Bards for Miniboss & MVP boss monsters.
Awesome!

**Comment by zackdreaver** [comment]
@aleos89 @Playtester 
Any official info regarding big HP bar for MVP in kRO?

**Comment by aleos89** [comment]
We should already have this support for newer clients.

**Comment by zackdreaver** [comment]
@aleos89 

What I mean is,
because the comment of commit state that he don't know if this the official behavior or not.
In recent 2016 kRO player's replay file, I only see normal mob that have HP bar, but not with MVP/Boss.

Tested with 2016-02-03aRagexeRE.

**Comment by aleos89** [comment]
It seems it's an iRO thing where MVP don't have their big bars, but on kRO they show.

**Comment by zackdreaver** [comment]
Alright, thanks for the confirmation

**Comment by zackdreaver** [comment]
@aleos89 
is it possoble to create config for MVP and Mini Boss HP bar on monster.conf?
So only normal monsters' HP bar are showed.

**Comment by aleos89** [comment]
It is possible, but are MVP/Miniboss really not displayed anymore? I thought we confirmed this before.

**Comment by zackdreaver** [comment]
that "iro thing" you mention about, still official though
https://forums.warpportal.com/index.php?/topic/208378-mvp-hp-bar/
