### ISSUE TITLE
Spirit Spheres and Critical Explosion Status

### ISSUE THREAD

**Issue by Haydrich** [rathena/rathena#7852]
### rAthena Hash

master

### Client Date

20221207

### Server Mode

Renewal

### Result

Depending on KRO, Spirit Spheres and Critical Explosion Status must be reset on map change

https://github.com/rathena/rathena/assets/54556365/86fce601-dea3-4783-99ef-99ffd5b14afb

### Expected Result

Spirit Spheres and Critical Explosion Status must be reset

### How to Reproduce

Monk class, use Dangerous Soul Collect / Critical Explosion then change your map

### Official Information

Depending on KRO, Spirit Spheres and Critical Explosion Status must be reset on map change

**Comment by Lemongrass3110** [comment]
I think what you show here is a zone-server switch.

**Comment by aleos89** [comment]
Agreed, another test would be to go between a few fields and see if the spirits get removed in those cases or not.

**Comment by secretdataz** [comment]
From my kRO experience, this is indeed a zone switch behavior.
