### ISSUE TITLE
error skill " Sight Blaster "  skill.c:219::skill_chk

### ISSUE THREAD

**Issue by hnomkeng** [rathena/rathena#788]
![untitled-2](https://cloud.githubusercontent.com/assets/9112684/11456917/13eca772-96cc-11e5-9326-bdec875f48e2.jpg)

skill attack to monster have error " skill.c:219::skill_chk "

rathena version 15182 (pre-renewal)

@aleos89 @Lemongrass3110  thank you for fixed.

**Comment by gusjungsza** [comment]
video : https://github.com/rathena/rathena/issues/517

**Comment by Lemongrass3110** [comment]
SVN revision 15182 corresponds to git hash: c7d7371

**Comment by hnomkeng** [comment]
How can fix it?

**Comment by Playtester** [comment]
Well there are no skills 771 an 1028 in rAthena. You'll need to find what calls these skills. If you are saying it's when you are using Sight Blaster which is ID 1006:

1006,0,6,4,3,0,1,1,1,yes,0,0x40001,0,magic,3,0x20,	WZ_SIGHTBLASTER,Sight Blaster

You have to find where it calls skill_chk with ID 771 / 1028 instead.

**Comment by cold-hr** [comment]
Now . I use last git

![untitled](https://cloud.githubusercontent.com/assets/13975637/11514157/aaa3fbb4-98a9-11e5-8d46-b9cf76e29ba8.png)

**Comment by Playtester** [comment]
This error shows up every time you use Sight Blaster or what triggers it?

**Comment by cold-hr** [comment]
@Playtester 

yes.

**Comment by Playtester** [comment]
Does the error appear at cast or when the spell hits something?

My first idea would be to debug what the client sends in "clif_parse_UseSkillToId" (I assume self skills go there).

Like before the last two lines, put something like:

ShowDebug("Client requests to use skill '%d'", skill_id);

Then check which messages comes first and what skill_id it returns. This is assuming the error occurs on cast.
