### ISSUE TITLE
Same Sex Marriage Doesnt work

### ISSUE THREAD

**Issue by LadyNanuia** [rathena/rathena#7899]
### rAthena Hash

3455b4bal

### Client Date

2021-11-03

### Server Mode

Renewal

### Result

Same sex marriage not possible despite set to allowed in the config (master/npc/custom/etc/marriage.txt) #L20 

OnInit:
	set $@wed_allow, 1;	//If 1, allows same sex marriages.
	set $@wed_veil, 0;	//Set to 0 to disable veil check on the bride

### Relevant Log Output

```Shell
None
```

### Expected Result

Being able to marry 2 characters of the same sex

### How to Reproduce

Make 2 characters of the same gender and try to marry with this variable set to 1, if you swap one characters gender to the other one, it works perfectly so its def the same sex thing thats not working.

### Official Information

Ive actually not tried this officially but theres a setting for it in our config that should allow it so..

### Modifications that may affect results

None

**Comment by Pokye** [comment]
Same-sex marriage and races, is in the Lasagna npc, but has not yet been implemented in rA. https://github.com/rathena/rathena/issues/5872
