### ISSUE TITLE
Dragonic Breath skill (6001) Is missing from the Source & Yaml

### ISSUE THREAD

**Issue by LadyNanuia** [rathena/rathena#7900]
### rAthena Hash

3455b4ba1

### Client Date

2021-11-03

### Server Mode

Renewal

### Result

The skill DK_DRAGONIC_BREATH (Id 6001) Does not exist on rAthena
Not in Source
Not in Skill_tree.yml
Not in Skill_db.yml

### Relevant Log Output

```Shell
None
```

### Expected Result

For the SKill DK_DRAGONIC_BREATH (6001) To exist.

### How to Reproduce

Make a dragon knight and you will not be able to skill DK_DRAGONIC_BREATH (6001) because it does not exist

### Official Information

The skill exists

https://www.divine-pride.net/database/skill/6001

### Modifications that may affect results

None

**Comment by Haydrich** [comment]
Its a part of #7024 and it requires 202206 or higher clients

**Comment by LadyNanuia** [comment]
> Its a part of #7024 and it requires 202206 or higher clients

Well if my client is missing the files thats my own issue but the report is about the skill not being in rA at all though.

**Comment by LadyNanuia** [comment]
> > > Its a part of #7024 and it requires 202206 or higher clients
> > 
> > 
> > Well if my client is missing the files thats my own issue but the report is about the skill not being in rA at all though.
> 
> Actually i was giving some info about it, and it's already implemented in the above-mentioned pull.

Sorry i didnt mean to come across as a bitch or anything ,i just meant that if the class is in, shouldnt all skills for it be in? since i know 4th expanded are not in and thats fine but this just struck me as odd as Dragon knight is

**Comment by InFiNiTe90X** [comment]
Do you guys know about where to find that new client? i'm lost...

**Comment by akbare** [comment]
for hexed Client Date can it use 2022-04-06_Ragexe_1648707856

**Comment by InFiNiTe90X** [comment]
> for hexed Client Date can it use 2022-04-06_Ragexe_1648707856
I have the same question... I have the same client... but it seems is not working...

**Comment by InFiNiTe90X** [comment]
> for hexed Client Date can it use 2022-04-06_Ragexe_1648707856

I have the same question... I have the same client... but it seems is not working...

**Comment by llchrisll** [comment]
> > for hexed Client Date can it use 2022-04-06_Ragexe_1648707856
> 
> I have the same question... I have the same client... but it seems is not working...

You need at least 2022-06+ client as stated in the title. You get it by purchasing it from 4144 or other sources, don’t ask me if there is any.

**Comment by aleos89** [comment]
This skill was implemented in #7985.
