### ISSUE TITLE
Ignore gtb doesn't work

### ISSUE THREAD

**Issue by dimasshotta** [rathena/rathena#7901]
### rAthena Hash

Whatever

### Client Date

2022-04-06

### Server Mode

Pre-Renewal, Renewal

### Result

Deadly projection has no effect on player even though the player has gtb card on the shield

### Expected Result

Deadly projection should ignore gtb card

### How to Reproduce

Try use skill deadly projection on player that has gtb card applied on any shield

### Official Information

Nothing

**Comment by Atemo** [comment]
Unable to reproduce on https://github.com/rathena/rathena/commit/fffad654800420bbd64ef1e3e18482800e33e053
