### ISSUE TITLE
Marine Sphere movement is not working properly

### ISSUE THREAD

**Issue by Leemonn** [rathena/rathena#7904]
### rAthena Hash

eadfa053f6db830e0e769b7241aab5b8df651c92

### Client Date

2015-11-04

### Server Mode

Pre-Renewal

### Result

Tested in latest hash without modifications.

![project_resurrection_Jx3rfHGcpA](https://github.com/rathena/rathena/assets/47922762/af9ce385-0863-4931-b933-8d23e4c689e0)

As you can see in the video everytime you hit a Marine Sphere it starts moving but it randomly stops after moving between 0 and 7 cells.
It happens in any direction and with any type of attack.

### Expected Result

1. Hit Marine Sphere any number of times
2. Marine Spheres moves 7 cells away from attacker

### How to Reproduce

1. Hit Marine Sphere any number of times
2. Marine Spheres moves between 0 and 7 cells away from attacker and stops

### Official Information

.

**Comment by Singe-Horizontal** [comment]
I traced the bug up to TIMER_FUNC(unit_walktoxy_timer), where `!(ud->walk_count%WALK_SKILL_INTERVAL)` often equals false which prevents `clif_move(ud);`.
