### ISSUE TITLE
Sound Blend Effect gets Removed on Skill usage

### ISSUE THREAD

**Issue by LadyNanuia** [rathena/rathena#7906]
### rAthena Hash

3455b4ba1

### Client Date

2021-11-03

### Server Mode

Renewal

### Result

Basically, Sound brand effect (SC_SOUNDBLEND) gets removed when attacking the monster with any of your skills, this is not intended 

### Relevant Log Output

```Shell
None specifically
```

### Expected Result

Soundblend is not supposed to be removed from the target even when hit by a skill, it should last its duration depending on the level on targets

### How to Reproduce

Make a Trouvere / Troubadour, Sound brand a target then use one of your offensive skills, mark will be removed.

### Official Information

![image](https://github.com/rathena/rathena/assets/54687998/97ed02fd-6750-4284-9fb4-3a247b96e454)
![image](https://github.com/rathena/rathena/assets/54687998/9786c85e-e2ee-4e9a-a9c6-ee90c33f3afa)
![image](https://github.com/rathena/rathena/assets/54687998/d458153d-fe81-4040-bb43-8063a80bd9d1)
![image](https://github.com/rathena/rathena/assets/54687998/976a7f2a-c9bc-4d63-a4e4-f6110e6340a3)

taken from Divine pride's post about 4th jobs being updated and i assume it was missed by the person who made it, 
same goes for Metallic Sound and Reverb

### Modifications that may affect results

None

**Comment by aleos89** [comment]
Looks like this comes from the latest patch: [Fourth class jobs and second high expanded class jobs skills rebalance (2nd) on 260/55 level expansion patch](https://www.divine-pride.net/forum/index.php?/topic/3723-kro-jobs-improvement-project/&do=findComment&comment=12421)

**Comment by Lemongrass3110** [comment]
Will be handled in #8018
