### ISSUE TITLE
ALL_WEWISH (bogus or bug? no idea)

### ISSUE THREAD

**Issue by Fraterna** [rathena/rathena#791]
yo!

i started the 2013 xmas-event, where players can get the item "Christmas Music Box (ID: 2784)"
- it actually GIVES the skill  "We Wish... (ID: 698, ALL_WEWISH)"
- the skill itself displays "We Wish..." and an angelus-skillanimation
- the effect of some random xmas-music does NOT work.

my questions:
does it work as intended or do i miss something here?
do i need to patch some songs into the client? if yes, wich mp3-names?

rev: 17726
client: 2015-05-13 ragEXE, most recent data/rdata grf's

**Comment by sader1992** [comment]
it's not server side ب_ب
and it work without errors
just update your grf
i have (data.grf) 6/2015
and don't use multi grf and it work fine

**Comment by Fraterna** [comment]
ARGH... can be closed:
- forgot to update 2nd client for my testserver.
- works as intended. (sorry, wanted to ask that in forums, but it's not availiable atm)
