### ISSUE TITLE
Q> rathena website

### ISSUE THREAD

**Issue by ernestfegarido** [rathena/rathena#792]
sorry for posting in the wrong section. but why is that rathena website is down for almost 3 days?

**Comment by Playtester** [comment]
Domain needs to be renewed. Don't know how long it'll take.

**Comment by dastgir** [comment]
Quote from Akkarin 3 days ago:
<Akkarin> The domain was renewed today as it was expired, it's just taking a while to sort itself out. Chill out -_-

**Comment by aleos89** [comment]
You can find info on our Facebook page: https://www.facebook.com/rAthena.org/
