### ISSUE TITLE
MO_EXTREMITYFIST stops Natural Recovery of SP until relogg

### ISSUE THREAD

**Issue by LadyNanuia** [rathena/rathena#7924]
### rAthena Hash

3455b4ba1

### Client Date

2021-11-03

### Server Mode

Renewal

### Result

After using Asura strike, you gain the debuff that prevents SP recovery for 3 seconds which is fine and stops natural SP recovery as well, however even AFTER the debuff is gone, natural recovery is disabled until you relogg, Recovery from Spiritual Recovery works however but not natural

### Expected Result

For Natural SP recovery to resume after the debuff wears off without having to relogg

### How to Reproduce

latest rAthena without mods, use MO_EXTREMITYFIST on a monster and watch as your Natural SP recovery wont return until you relogg

### Official Information

As far as i know, It should only prevent Item and Natural recovery for the duration of the debuff and then return them after.

### Modifications that may affect results

None

**Comment by LadyNanuia** [comment]
but it comes back if you relogg though, so somethings not adding up

**Comment by aleos89** [comment]
SC_EXTREMITYFIST has the NoSave flag, so it makes sense a relog will remove it.

**Comment by LadyNanuia** [comment]
Oh i see, i will investigate this and report back if this is intended behaviour , thank you @aleos89

**Comment by Playtester** [comment]
This may sound weird but it's actually working as intended. Same effect as Frenzy has. You don't recover SP for 5 minutes or until you relog.
You can read it up on Kokotewa too: https://ro.kokotewa.com/db/skl_info?id=MO_EXTREMITYFIST
