### ISSUE TITLE
Why is the price of selling items always 0?

### ISSUE THREAD

**Issue by 24msz6eo** [rathena/rathena#7934]
### rAthena Hash

https://github.com/rathena/rathena/commit/fffad654800420bbd64ef1e3e18482800e33e053

### Client Date

2022-04-06

### Server Mode

Renewal

### Result

Why is the price of selling items always 0?

### Expected Result

Why is the price of selling items always 0?

### How to Reproduce

Why is the price of selling items always 0?

### Official Information

Why is the price of selling items always 0?

### Modifications that may affect results

Why is the price of selling items always 0?

**Comment by Atemo** [comment]
No effort made. Issue not understandable.
