### ISSUE TITLE
warning npc_market

### ISSUE THREAD

**Issue by hendra814** [rathena/rathena#7936]
### rAthena Hash

lastest rathene

### Client Date

2021-11-03

### Server Mode

Renewal

### Result

when start rathena server it's show warning at map server

![image](https://github.com/rathena/rathena/assets/9587609/79e12dc2-b3d5-47f6-981f-af1dcbc521bb)

### Expected Result

not showing the warning

### How to Reproduce

run runserver.bat

### Official Information

don't know

**Comment by aleos89** [comment]
It's intended. It means you have a market shop in SQL that has an item that can be purchased for discount less than it can be sold for with overcharge. Simply update the SQL value and you're fine.

**Comment by hendra814** [comment]
sorry, are you mean shop in flux control panel?

**Comment by aleos89** [comment]
No, check your RO schema for the `market` table and either remove the items from there or adjust the prices to what the server is telling you they should be.

**Comment by hendra814** [comment]
ok found it, last question.
From which file this item import in the market schema?
is it related to all item sql files?
Because i already run yaml2sql.bat and reimport into my database, but the issue still happen.

**Comment by hendra814** [comment]
ok found it, last question.
From which file this item import in the market schema?
is it related to all item sql files?
Because i already run yaml2sql.bat and reimport into my database, but the issue still happen.

**Comment by aleos89** [comment]
It happens because whenever the marketshops were implemented years ago, it was thought the content from the shops were saved, but it's been confirmed that the shops never saved, they just reset after each maintenance on kRO. We just haven't adjusted this behavior yet.
