### ISSUE TITLE
socket timeout options on WinAPI use DWORD, not struct timeval

### ISSUE THREAD

**Issue by theultramage** [rathena/rathena#794]
In https://github.com/rathena/rathena/commit/f67f82c472585bb5fdb4860deedf32cccb508f98 a cascade of 'timeout' parameters was added, eventually ending at setsocketopts:

```
    if(delay_timeout){
        struct timeval timeout;
        timeout.tv_sec = delay_timeout;
        timeout.tv_usec = 0;

        if (sSetsockopt (fd, SOL_SOCKET, SO_RCVTIMEO, (char *)&timeout,sizeof(timeout)) < 0)
            ShowError("setsocketopts: Unable to set SO_RCVTIMEO timeout for connection #%d!\n");
        if (sSetsockopt (fd, SOL_SOCKET, SO_SNDTIMEO, (char *)&timeout,sizeof(timeout)) < 0)
            ShowError("setsocketopts: Unable to set SO_SNDTIMEO timeout for connection #%d!\n");
    }
```

According to MSDN docs:

```
SO_RCVTIMEO DWORD   Sets the timeout, in milliseconds, for blocking receive calls. 
SO_SNDTIMEO DWORD   The timeout, in milliseconds, for blocking send calls. 
```

So there is a platform incompatibility, which results in a parameter type mismatch. This is the cause why in https://github.com/rathena/rathena/issues/793 I saw a 21-second delay.

**Comment by Lemongrass3110** [comment]
Could you test if the issue still persists on the referenced commit?

**Comment by theultramage** [comment]
The timeout on windows is in miliseconds, so multiply by 1000 please. Or better yet, change the meaning of the delay_timeout parameter to mean miliseconds - for sub-second precision. Depends on what the purpose is.

**Comment by Lemongrass3110** [comment]
Thanks for clearing that up. I missed that part. Fixed it with a follow up abd1ad2.

I think since unix only allows seconds, it's a good deal to stay with seconds.
Don't you think so?

Wouldn't hurt to add some documentation on the socket part though... :/

**Comment by theultramage** [comment]
>  I think since unix only allows seconds

```
timeout.tv_sec = delay_timeout;
timeout.tv_usec = 0; <---- microseconds field
```

**Comment by Lemongrass3110** [comment]
Sorry I adjusted my comment. Seems like that was too late.

Was thinking of removing the scope braces totally first, since it is not that big of a function that this would create any major benefit.

**Comment by theultramage** [comment]
Oh boy, here's a an additional headache. With WinAPI, the send/recv timeout options do not apply to connect(), Even with the above fix, the connect operation still takes 20 seconds to time out. Not sure if it's different on linux/bsd.

The proper, portable way of controlling the timeout of a blocking connect is to:
1) set socket to nonblocking mode
2) call connect()
3) call select(), looking for write completion (timeout parameter goes here)
4) set socket back to blocking mode

Again, the blocking make_connection() function was not intended for periodic outgoing connections to third-party hosts like this. Even its use for connections between servers is problematic. I could imagine it being rewritten in asynchronous mode, although the only dumb idea that comes to my mind right now is starting a periodic 1-second timer function that does select() with an instant timeout, and keeps checking until the operation completes or aborts.

**Comment by Lemongrass3110** [comment]
Yeah seems like we do it wrong in general. But it also differs for linux and windows and has to be treated differently.
If you agree I would leave the ```setsocketopts``` function at seconds and leave that function be as it is of abd1ad2 for now, since that adresses the wrong usage of the socket options.
I will push another commit today or in the next days, that adresses the problems in ```make_connection```.

Sources:
http://stackoverflow.com/a/2597774
http://developerweb.net/viewtopic.php?id=3196

**Comment by Lemongrass3110** [comment]
Sorry it took a little longer.
Could you review 227dd85 and test if it behaves like you/we would want it to?
My tests looked good.
