### ISSUE TITLE
NPC_RUN is broken

### ISSUE THREAD

**Issue by Leemonn** [rathena/rathena#7941]
### rAthena Hash

1bc9748755bc5073f0b521a7b9827a091d3d834f

### Client Date

2015-11-04

### Server Mode

Pre-Renewal, Renewal

### Result

I mentioned this in https://github.com/rathena/rathena/issues/7916 but the issue was already closed.

Tested on vanilla up to date master.

Hell Poodle doesn't run. It keeps cancelling the run skill and attacking the player.
![project_resurrection_NXzkvBAYvC](https://github.com/rathena/rathena/assets/47922762/1fc6fc88-3590-4d7f-b021-6001a3015c46)

Zombie with this skill:
`-2,all@NPC_RANDOMMOVE,any,331,1,10000,0,30000,yes,self,myhpltmaxrate,30,,,,,,26,`
![project_resurrection_9zphYYDmvZ](https://github.com/rathena/rathena/assets/47922762/9fabd897-fa63-48ce-894f-ece894523cfc)

Zombie with this skill:
`-2,all@NPC_RUN,any,354,1,10000,0,30000,yes,self,myhpltmaxrate,30,,,,,,26,`
![project_resurrection_OvuVkxzKYs](https://github.com/rathena/rathena/assets/47922762/2bbbf178-c009-4091-afc4-bf3da01eb803)

I'm currently working on something else so I don't have time to check the code, but my guess is that we are missing some flag that disables any other action while the mob has NPC_RUN or NPC_RANDOMWALK active.
Maybe we can have 2 modes for those 2 skills, one that applies a SC that disables every other action until reaching the destination, and 1 that doesn't.

**Comment by Playtester** [comment]
On official servers NPC_RUN calculates a distance of 7 to move away. Then disables the mob AI for the expected movement time once the "move" command was successful.

**Comment by Playtester** [comment]
I can technically fix this server-side by changing the code like this:
```
	case NPC_RUN:
		if (md) {
			block_list* tbl = map_id2bl(md->target_id);

			if (tbl) {
				short dist = skill_lv > 1 ? skill_lv : 7; // Send distance in skill level > 1
				md->state.can_escape = 1;
				mob_unlocktarget(md, tick);
				if (unit_escape(src, tbl, dist, 2)) 
					md->last_thinktime = tick + (dist * md->status.speed);
			}
		}
		break;
```
However, the client seems to ignore the move commands it sends when the monster uses it on chase. Can't figure that one out.

**Comment by Playtester** [comment]
Seems setting its state to MSS_WALK fixes the issue.

NPC_RANDOMMOVE is in my opinion a completely different topic as that's a skill specifically coded to by used by Marine Spheres. I'll move that into a separate topic.

**Comment by Playtester** [comment]
NPC_RANDOMMOVE is now documented in another requirement: https://github.com/rathena/rathena/issues/8301

**Comment by Playtester** [comment]
If movement is diagonal, the time should be multiplied with sqrt(2).
