### ISSUE TITLE
Callfunc doesn't work when called by achievement.db

### ISSUE THREAD

**Issue by AnonRagnadev** [rathena/rathena#7944]
### rAthena Hash

Latest

### Client Date

2022-04-06

### Server Mode

Pre-Renewal

### Result

I can't figure out what's wrong so I can only imagine it's a bug.
I'm trying to do some fancy things with the achievement system. One of those things involves calling a function each time an achievement reward is claimed.

`    Rewards:
      Script: " getitem 330923,1; getitem 330364,1; callfunc("F_Customchievos",1); "`

So here's two things: The reason why I'm using getitem here instead of just rewarding items is because the achievement system does not allow more than 1 item to be given this way.
But the serious issue here is that callfunc doesn't work when used on the script field for achievements. I get this error:

[Error]:
script error on db/pre-re/achievement_db.yml line 52
    parse_simpleexpr: unexpected character
*   52 :  getitem 330923,1; getitem 330364,1; callfunc(

I know the function syntax is correct because, when I move it to a NPC it works perfectly fine. I can only imagine the achievement system itself doesn't support it.

### Expected Result

For the function call to work.

### How to Reproduce

Attempt to callfunc from any achievement that has a Script type reward.

### Official Information

n/a

**Comment by aleos89** [comment]
You need to escape the double quote to parse the function.
