### ISSUE TITLE
Grimtooth misses on Stunned enemies

### ISSUE THREAD

**Issue by AnonRagnadev** [rathena/rathena#7949]
### rAthena Hash

Latest

### Client Date

2022-04-06

### Server Mode

Pre-Renewal

### Result

Stunned enemies should not have any evasion. However, attacks done with Grimtooth can still miss against Stunned enemies.

### Expected Result

Stunned enemies should not be able to evase any attacks but Grimtooth misses on them.

### How to Reproduce

Try doing grimtooth with a stun arrow, or with cards that cause stun. You will proc the effect but still miss attacks on enemies(if they have higher flee).

### Official Information

.

**Comment by Kuyaraikub** [comment]
Grimtooth it's not stun just Sonic Blow

**Comment by Playtester** [comment]
I can confirm from official tests that Stunned enemies cannot dodge with flee. I tried using Magic Study Vol 1 to stun Anopheles attacking me and I can only hit it when stunned on official servers.

Same goes for Freeze and probably other OPT1 status changes.

The code looks correct to me in battle.cpp:
`	else if (tsc && tsc->opt1 && tsc->opt1 != OPT1_STONEWAIT && tsc->opt1 != OPT1_BURNING)
		return true;`

**Comment by Playtester** [comment]
I tested it and it works correctly.

When an enemy is stunned, Grimtooth hits to 100%.

**Comment by Singe-Horizontal** [comment]
f85f990 fixes this
