### ISSUE TITLE
Achievements not counting while in party

### ISSUE THREAD

**Issue by AnonRagnadev** [rathena/rathena#7952]
### rAthena Hash

Latest

### Client Date

2022-04-06

### Server Mode

Pre-Renewal

### Result

I've been unable to determine the exact situation that causes the problem, but it seems like that some players in my server are unable to gain progress towards achievements of the AG_BATTLE type.
My server has achievement_mob_share enabled, on monster.conf, so these should be party-wide.

What will happen is that some of the party members don't get score/progress while the others do for unexplainable reasons. When this happens, I tell them to destroy the party and remake and that will usually fix the problem.
Clearly there's some logical error in how this function is implemented, I'm just unable to find out how.

### Expected Result

With the setting on, all players in a party should get score towards kill achievements.

### How to Reproduce

.

### Official Information

.

**Comment by Lemongrass3110** [comment]
It is not party wide. It is only for all players within an area of "area_size" (battle/client.conf), usually 14x14 cells, of the killing player.

Are you sure that the players were close to the killer?

**Comment by AnonRagnadev** [comment]
Yes I'm 100% sure, people on screen. They don't even get kills for monsters they kill on their own, which is why I think it's a logical problem with how the conf setting works.

**Comment by aleos89** [comment]
I just tested this and my kills went through just fine. Is there some specific scenario that you are able to reproduce? Can you provide those steps please.
