### ISSUE TITLE
@auction

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#796]
Hello .. good evening.

The auction system also is not working, you use the command @auction, but nothing happens.

Client: 2015-05-13
Renewal, last version.

**Comment by Lemongrass3110** [comment]
@icxbb-xx was auction readded? I think that was dropped on the officials?

**Comment by icxbb-xx** [comment]
@Lemongrass3110  yes, maybe gravity dropped packets for this

**Comment by Lemongrass3110** [comment]
we should find the packet version where it was dropped and ifdef the support for auction out after that. So it's not really a 2015 client target.

**Comment by aleos89** [comment]
This is a duplicate of #704.

**Comment by Lemongrass3110** [comment]
@aleos89 not a duplicate I guess. @icxbb-xx and I think it was removed when RODEX was added in.
