### ISSUE TITLE
Mercenary skills error - not working

### ISSUE THREAD

**Issue by jamesandrewww** [rathena/rathena#7968]
### rAthena Hash

673ef066fb261985b7be4526b444e8b735e7ed95

### Client Date

2022-04-06

### Server Mode

Pre-Renewal

### Result

Item: Spearman Scroll 4 (12176)
Skill: Defender (8219)
Error Code: [Error]: status_change_start: Invalid status change (-1)!

-Item: Spearman Scroll 5 (12177)
Skill: Guard (8220)
Error Code: [Error]: status_change_start: Invalid status change (-1)!

-Item: Spearman Scroll 9 (12181)
Skill: Auto Guard (8220) & Defender (8219)
Error Code: [Error]: status_change_start: Invalid status change (-1)!

-Item: Spearman Scroll 10 (12182)
Skill: Auto Guard (8220), Defendef (8219) & Devotion (8221)
Error Code: [Error]: status_change_start: Invalid status change (-1)!

-Item: Fencer Scroll 8 (12170)
Skill: Parry (8204)
Error Code: [Error]: status_change_start: Invalid status change (-1)!

-Item: Fencer Scroll 9 (12171)
Skill: Reflect Shield (8205)
Error Code: [Error]: status_change_start: Invalid status change (-1)!

-Item: Fencer Scroll 10 (12172)
Skill: Berserk (8206 or 8233)
Error Code: [Error]: status_change_start: Invalid status change (-1)!

-Item: Spearman Scroll 3 (12175)
Skill: Devotion (8221)
Error Code: None, skill is not working

-Item: Bowman Scroll 7 (12159)
Skill: Mental Cure (8230)
Error Code: None, skill is not working

-Item: Spearman Scroll 1 (12173)
Skill: Regain (8226)
Lua Error Code: [string "buf"]:262: attempt to index field 'AttackRange' (a nil value)

### Expected Result

Fix all broken skills

### How to Reproduce

@item respective scrolls
use mercenary skills

### Official Information

none

### Modifications that may affect results

none

**Comment by Kuyaraikub** [comment]
https://github.com/rathena/rathena/assets/147054311/de29b208-093f-49f8-910e-380025e7200f
