### ISSUE TITLE
Bug Npc Soul

### ISSUE THREAD

**Issue by Dark8008** [rathena/rathena#799]
i use this script

switch ( basejob ) {
  case Job_Alchemist:	set .@spirit, 445; break;
  case Job_Monk:	 set .@spirit, 447; break;
  case Job_Star_Gladiator:  set .@spirit, 448; break;
  case Job_Sage:	 set .@spirit, 449; break;
  case Job_Crusader:	set .@spirit, 450; break;
  case Job_SuperNovice:   set .@spirit, 451; break;
  case Job_Knight:	set .@spirit, 452; break;
  case Job_Wizard:	set .@spirit, 453; break;
  case Job_Priest:	set .@spirit, 454; break;
  case Job_Bard: case Job_Dancer: set .@spirit, 455; break;
  case Job_Rogue:	 set .@spirit, 456; break;
  case Job_Assassin:	set .@spirit, 457; break;
  case Job_Blacksmith:   set .@spirit, 458; break;
  case Job_Hunter:	set .@spirit, 460; break;
  case Job_Soul_Linker:   set .@spirit, 461; break;
  default:
   if ( upper == 1 && baselevel < 70 )
	set .@spirit, 494;
}
if ( .@spirit ) {
  sc_start4 sc_spirit, 360000, 5, .@spirit,0,0;
  skilleffect .@spirit, 5;
}

After soul, the WhiteSmish Job not display "Full Adrenaline Rush" skill and The Clown Job not display skill of Gyps too -> so can't use these skill, please help !

**Comment by icxbb-xx** [comment]
It worked fine for me.
![screenrathena test000](https://cloud.githubusercontent.com/assets/3500355/11530667/222d30d6-9929-11e5-9288-325fd19a0571.jpg)
