### ISSUE TITLE
Add option for Cash Shop with SQL table or remove Cash Shop to YAML Conversion

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#7999]
### Is your request related to a missing official feature?

No

### Describe the solution you'd like

Cash Shop has been converted to YAML which is very good, however this is impacting some flexibility issues for the servers.

In the previous system without YAML conversion it was possible to choose between txt (similar idea to the current YAML server-side configuration for adding items) and the SQL model.

Example:
cashshop.cpp
```
	//if( db_use_sqldbs ){
		cashshop_read_db_sql();
	//} else {
	//	cashshop_read_db_txt();
	//}
```

The current model configuration is completely manual through the yml file, unlike the old model that when used in SQL configuration it was possible to change values directly in the table using a script directly in the emulator. For example, private could use a script to rotate cash shop items once a week in an automated way, simply feeding a configuration array into a script that changes the ID in the SQL table and then uses the item_db reload. Very practical for servers that want to perform this automated rotation.

Now this would be impossible and the modification would be completely manual again, which creates a flexibility problem for the current conversion.

### Describe alternatives you've considered

Adding a SQL option for cash shop items makes script-automated item rotation very flexible, making life easier for servers.

### Additional context

Here is the conversion link:

https://github.com/rathena/rathena/pull/6299/files#

Here was an alternative to modifying SRC when using SQL table, which has currently been removed:

https://rathena.org/board/topic/121094-about-cash-shop-from-sql/

**Comment by vstumpf** [comment]
You would have to do something similar with itemdb: parse the rows from the sql db, convert it into yaml nodes, then call cashdb->parseBodyNode on each node.

It would be nice if the yaml loading logic was separate from the in-memory db; then people could choose different "db loaders", yaml, sql, json, etc. But that would require a lot changes that not everyone wants to do :c

**Comment by Badarosk0** [comment]
It would be great if using SQL for cash shop was an option in rAthena, as it has been for years. 

yml is without a doubt an excellent change. But there will always be the limitation of manual changes as I said and we will not be able to make automated updates. Well, did anyone else do this or was it just me? hehehe 

I think it would be very flexible if it were also possible to have SQL.

**Comment by Lemongrass3110** [comment]
The decision of the team was to go for only a single database engine and only maintain support for this one.

You can generate your YAML files via shell/batch script as well and reload the database accordingly to automate your rotation.
