### ISSUE TITLE
classchange script command - still broken or outdated documentation?

### ISSUE THREAD

**Issue by Akkarinage** [rathena/rathena#800]
Git Hash: 1f1160300b8ce903f8cfe19adac0888ae0dc11eb

doc/script_commands:

```
*classchange <view id>,<type>;

...

As a result it is currently impossible to call this command with a valid view 
id. It will do nothing whatsoever if the view ID is below 4047. Getting it to 
run will actually just crash the client.

It could be a real gem if it can be gotten to actually do what it's supposed to 
do, but this will only happen in a later SVN revision.
```

https://github.com/rathena/rathena/blob/master/npc/re/jobs/novice/academy.txt#L11787

```
classchange "Lumin#"+strnpcinfo(2), 4_M_THIEF_RUMIN;
```

**Comment by Atemo** [comment]
It was a script mistake. Thanks :)

**Comment by Akkarinage** [comment]
You're still using classchange where the documentation says that command doesn't work.

**Comment by Atemo** [comment]
From my test this command is working with sprite below 4000. But it seems officially they used a command similiar to setnpcdisplay. Thanks :)
