### ISSUE TITLE
Macro detection System generates random client crash

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#8010]
### rAthena Hash

https://github.com/rathena/rathena/commit/cdf377e071318f8f4f0be02b42ba35cecbba706d

### Client Date

20211117

### Server Mode

Renewal

### Result

When calling the UI using the script example, it generates a random crash client, unfairly banning or jailing the player.

```
geffen,129,64,3	script	Macro Tester	67,{
	macro_detector(strcharinfo(0));
end;
}
```

https://github.com/rathena/rathena/assets/13624462/773a9ea0-b0cf-4741-8d9c-7094f9a1e8ca

### Expected Result

No random crash occurs.

### How to Reproduce

Use the indicated script and start clicking on the NPC and typing the password a few times. In some attempts, a crash will occur.

### Official Information

NA

**Comment by aleos89** [comment]
Does the issue only appear in rapid succession or if this is on a timer across several minutes/hours it still happens? I'm thinking this could be an issue related to the client and not something we can fix.

**Comment by Badarosk0** [comment]
> Does the issue only appear in rapid succession or if this is on a timer across several minutes/hours it still happens? I'm thinking this could be an issue related to the client and not something we can fix.

Totally random. Sometimes I need to type several times for the error to occur. There is no standard.

**Comment by aleos89** [comment]
That's why I'm wondering if it's a memory error with the client. If there's a way for you to try a few clients that are months (or year[s]) apart from the current one you are testing now. That could help narrow down to see if it's a bug with the client itself.

**Comment by Badarosk0** [comment]
> That's why I'm wondering if it's a memory error with the client. If there's a way for you to try a few clients that are months (or year[s]) apart from the current one you are testing now. That could help narrow down to see if it's a bug with the client itself.

Well, I'll test it soon with a new 2023 client, so we'll know for sure.

**Comment by Badarosk0** [comment]
> That's why I'm wondering if it's a memory error with the client. If there's a way for you to try a few clients that are months (or year[s]) apart from the current one you are testing now. That could help narrow down to see if it's a bug with the client itself.

I confirmed, the problem continues on new clients. In version 2023 the same problem occurs.

**Comment by Lemongrass3110** [comment]
Seeing the rendering problems in your video simply tells me that you forgot to add one of the client side diffs.
Therefore it is just a matter of time until your client crashes because you use the wrong BMP format.

![grafik](https://github.com/rathena/rathena/assets/3517879/8b340546-99a8-4bb5-a607-e8dc076f6dd7)
