### ISSUE TITLE
Can't make more slim in one time

### ISSUE THREAD

**Issue by Dark8008** [rathena/rathena#802]
I just can make slim one by one, can't make more one time like 50 - 100 ... please help !

**Comment by aleos89** [comment]
Are you talking about Alchemy II?

**Comment by Dark8008** [comment]
Not sir, skill make slim of Bio Job !

**Comment by philg666** [comment]
did you tried with alchemist spirit (skill from soul linker) ?

**Comment by Dark8008** [comment]
Yes !

**Comment by Dark8008** [comment]
Any fix ?

**Comment by Lemongrass3110** [comment]
Sorry but please provide more info about your configuration instead of bumping this.
We still need: Client date, Git hash, Renewal/Pre-Renewal and the steps how to reproduce this.

Thanks for your patience.

**Comment by Dark8008** [comment]
I use pre-renewal, after Bio get soul from linker, they still can't make more slim ( like 300 ) in one time, they just can make one by one so their finger will break out soon !

**Comment by Lemongrass3110** [comment]
![screenrathena000](https://cloud.githubusercontent.com/assets/3517879/11637545/4f15dfba-9d22-11e5-971f-18f8aa78a918.jpg)
Works fine. Maybe you use the wrong skill.
