### ISSUE TITLE
rAthena client 2010/2015 without visual errors

### ISSUE THREAD

**Issue by crisgplj** [rathena/rathena#8023]
### Is your request related to a missing official feature?

Yes

### Describe the solution you'd like

I know this is not the most appropriate place to ask this but in the official forum the GMs do not give me access after registering.

My question is, does anyone have a 2010/2015 client that works without visual bugs?

I try to play locally with a group of friends from high school and we can't find any version that doesn't produce crashes.

I think it must be due to the graphics card drivers.

**Comment by Lemongrass3110** [comment]
As you pointed out yourself this is the wrong place to ask something like this.
Please use Discord or the Forums.
