### ISSUE TITLE
Map server crashed when monster attacked if compile in pre-renewal

### ISSUE THREAD

**Issue by Lelouzh** [rathena/rathena#8048]
### rAthena Hash

ac85d441978bffc35d77345155272c6118eade7f

### Client Date

2020-04-01 upper

### Server Mode

Pre-Renewal

### Result

I trying to use lastest rAthena with pre-renewal compiled, everything fine but we you has an attacked from mob, if damage done, map server crash and can't even read core dump. i trying to re-compile in renewal, everything good with no crash

### Relevant Log Output

```Shell
no log
```

### Expected Result

![image](https://github.com/rathena/rathena/assets/16756766/60d6bd2a-18d0-4436-91ae-a3a77064e23d)

### How to Reproduce

compile in pre-renewal and summon monster to hit you

### Official Information

-

**Comment by vstumpf** [comment]
Latest is not a git hash 
Are you on this commit
https://github.com/rathena/rathena/commit/6750837854d8e0701ca7a112e6631fc10889b245

**Comment by Lelouzh** [comment]
> Latest is not a git hash Are you on this commit [6750837](https://github.com/rathena/rathena/commit/6750837854d8e0701ca7a112e6631fc10889b245)

I just push yesterday.  so that your update is a fix?

**Comment by Lelouzh** [comment]
(gdb) bt full
#0  0x000000000045bf89 in std::uniform_int_distribution<int>::param_type::param_type (__b=-1, __a=0, this=0x7ffe0a171ff8) at /usr/include/c++/11/bits/uniform_int_dist.h:93
No locals.
#1  std::uniform_int_distribution<int>::operator()<std::mersenne_twister_engine<unsigned long, 32ul, 624ul, 397ul, 31ul, 2567483615ul, 11ul, 4294967295ul, 7ul, 2636928640ul, 15ul, 4022730752ul, 18ul, 1812433253ul> > (__urng=..., __param=..., this=<optimized out>)
    at /usr/include/c++/11/bits/uniform_int_dist.h:352
        __uerngrange = 4294967296
        __tmp = <optimized out>
        __urngmin = 0
        __urngmax = 4294967295
        __urngrange = 4294967295
        __urange = 18446744073709551615
        __ret = <optimized out>
#2  0x000000000045bf93 in std::uniform_int_distribution<int>::operator()<std::mersenne_twister_engine<unsigned long, 32ul, 624ul, 397ul, 31ul, 2567483615ul, 11ul, 4294967295ul, 7ul, 2636928640ul, 15ul, 4022730752ul, 18ul, 1812433253ul> > (__urng=..., __param=...,
    this=<optimized out>) at /usr/include/c++/11/bits/uniform_int_dist.h:97
        __uerngrange = 4294967296
        __tmp = <optimized out>
        __urngmin = 0
        __urngmax = 4294967295
        __urngrange = 4294967295
        __urange = 18446744073709551615
        __ret = <optimized out>
#3  0x000000000045bf93 in std::uniform_int_distribution<int>::operator()<std::mersenne_twister_engine<unsigned long, 32ul, 624ul, 397ul, 31ul, 2567483615ul, 11ul, 4294967295ul, 7ul, 2636928640ul, 15ul, 4022730752ul, 18ul, 1812433253ul> > (__urng=..., __param=...,
    this=<optimized out>) at /usr/include/c++/11/bits/uniform_int_dist.h:97
        __uerngrange = 4294967296
        __tmp = <optimized out>
        __urngmin = 0
        __urngmax = 4294967295
        __urngrange = 4294967295
        __urange = 18446744073709551615
        __ret = <optimized out>
#4  0x000000000045bf93 in std::uniform_int_distribution<int>::operator()<std::mersenne_twister_engine<unsigned long, 32ul, 624ul, 397ul, 31ul, 2567483615ul, 11ul, 4294967295ul, 7ul, 2636928640ul, 15ul, 4022730752ul, 18ul, 1812433253ul> > (__urng=..., __param=...,
    this=<optimized out>) at /usr/include/c++/11/bits/uniform_int_dist.h:97
        __uerngrange = 4294967296
        __tmp = <optimized out>
        __urngmin = 0
        __urngmax = 4294967295
        __urngrange = 4294967295
        __urange = 18446744073709551615
        __ret = <optimized out>
#5  0x000000000045bf93 in std::uniform_int_distribution<int>::operator()<std::mersenne_twister_engine<unsigned long, 32ul, 624ul, 397ul, 31ul, 2567483615ul, 11ul, 4294967295ul, 7ul, 2636928640ul, 15ul, 4022730752ul, 18ul, 1812433253ul> > (__urng=..., __param=...,
    this=<optimized out>) at /usr/include/c++/11/bits/uniform_int_dist.h:97
        __uerngrange = 4294967296
        __tmp = <optimized out>
        __urngmin = 0
        __urngmax = 4294967295
        __urngrange = 4294967295
        __urange = 18446744073709551615
        __ret = <optimized out>
#6  0x000000000045bf93 in std::uniform_int_distribution<int>::operator()<std::mersenne_twister_engine<unsigned long, 32ul, 624ul, 397ul, 31ul, 2567483615ul, 11ul, 4294967295ul, 7ul, 2636928640ul, 15ul, 4022730752ul, 18ul, 1812433253ul> > (__urng=..., __param=...,
    this=<optimized out>) at /usr/include/c++/11/bits/uniform_int_dist.h:97
        __uerngrange = 4294967296
        __tmp = <optimized out>
        __urngmin = 0
        __urngmax = 4294967295
        __urngrange = 4294967295
        __urange = 18446744073709551615
        __ret = <optimized out>
#7  0x000000000045bf93 in std::uniform_int_distribution<int>::operator()<std::mersenne_twister_engine<unsigned long, 32ul, 624ul, 397ul, 31ul, 2567483615ul, 11ul, 4294967295ul, 7ul, 2636928640ul, 15ul, 4022730752ul, 18ul, 1812433253ul> > (__urng=..., __param=...,
    this=<optimized out>) at /usr/include/c++/11/bits/uniform_int_dist.h:97
        __uerngrange = 4294967296
        __tmp = <optimized out>
        __urngmin = 0
        __urngmax = 4294967295
        __urngrange = 4294967295
        __urange = 18446744073709551615
        __ret = <optimized out>
#8  0x000000000045bf93 in std::uniform_int_distribution<int>::operator()<std::mersenne_twister_engine<unsigned long, 32ul, 624ul, 397ul, 31ul, 2567483615ul, 11ul, 4294967295ul, 7ul, 2636928640ul, 15ul, 4022730752ul, 18ul, 1812433253ul> > (__urng=..., __param=...,
    this=<optimized out>) at /usr/include/c++/11/bits/uniform_int_dist.h:97
        __uerngrange = 4294967296
        __tmp = <optimized out>
        __urngmin = 0
        __urngmax = 4294967295


core is something unrelated

**Comment by vstumpf** [comment]
Yes, it's a fix

**Comment by Lelouzh** [comment]
> Yes, it's a fix

Thanks it worked!
