### ISSUE TITLE
Server Startpoint

### ISSUE THREAD

**Issue by Jedzkie** [rathena/rathena#805]
Hi, in official server, re and pre-re. The start point is shuffled, reference http://herc.ws/board/tracker/issue-7750-official-server-startpoint/

**Comment by cydh** [comment]
Confirmed, I knew it.
I just think, the 'random' new maps (only when char first login, talk with Sprakki, enter first building for talking Brade) are related their multi map-server policy.
iirc, when I made new chars then connected to different maps, I got different map IP and port. But in the end, when on map to kill monsters, connected in same map server depends on the monster level (say, Poring/Drops/Lunatic/Fabre on map A server A, Picky/Condor/Roda Frog on map B server B, then Rocker/Spore/.. on map C server C).
That's what I experienced on idRO. :P

**Comment by aleos89** [comment]
As @cydh stated, if this is a multi-map type thing, are we going to force support for this since most servers don't even us multi-map?

**Comment by Jedzkie** [comment]
@aleos89 Hello, in novice.txt, it has duplicate from new_1-1 to 5-1. even there's no private servers uses a multi-map, but this is a official feature.

**Comment by aleos89** [comment]
Right, but I'm assuming the issue is for load-balancing for new players if the official server is using it as a multi-map server feature.

It wouldn't be hard to implement on our end, it just wouldn't be multi-map server-esk.

**Comment by cydh** [comment]
we will just put optional param then, use `:` as delimiter, when char created, the start point will be selected randomly if there are more than 1 start point defined.

**Comment by Jedzkie** [comment]
@cydh correct.

**Comment by cydh** [comment]
as I mentioned above, I'm willing to put `:` as delimiter, if no one against it, I'll assign myself for this.

**Comment by aleos89** [comment]
Simply adding a delimiter should be fine in my opinion. If the official server uses map counts or various things to split players up, I see no need for it as I said before for a private server. We aren't pushing thousands of players so there's no need for us to have any special checks for load balancing.

**Comment by cydh** [comment]
@Jedzkie, like or not it was declined (not by me :P)

**Comment by aleos89** [comment]
Why was this closed? I thought you were going to work on this.
