### ISSUE TITLE
not show mob

### ISSUE THREAD

**Issue by cold-hr** [rathena/rathena#807]
hi I Using last git
and i use command @monster
Like in the picture

Monster was not visible.
But still hit damage
![untitled](https://cloud.githubusercontent.com/assets/13975637/11589032/bd5352f4-9ab7-11e5-8154-bf057de2f013.png)

**Comment by icxbb-xx** [comment]
What you client date?

**Comment by hnomkeng** [comment]
confirm, not show monster and player 

rathena version 15247
client 2012-04-10
