### ISSUE TITLE
Sorcerer Skills Bugs - Call Ventus & 4 elemental Analysis

### ISSUE THREAD

**Issue by Vaans** [rathena/rathena#808]
Skill: Call Ventus

Git Hash/Date:  SVN Revision 12253
Client Date: 2015-05-13a
Server Mode: Renewal
Source/Script Mods: none
Descriptions: None
How To Replicate:
Description of the skill:

Summon the Spirit of Wind, Ventus, to assist the player. As long as the Elemental Spirit is active, it will drain SP every 10 seconds. 

Gust
    Boost ASPD by 5 and shorten Cast Time (Fixed) by 1 second.[1]

Refer info: http://irowiki.org/wiki/Call_Ventus

Bug;
Ventus don't give the shorten Cast Time ( 1 second).
 

Skill: 4 elemental analysis

Git Hash/Date:  SVN Revision 12253
Client Date: 2015-05-13a
Server Mode: Renewal
Source/Script Mods: none
Descriptions: None
How To Replicate:
Description of the skill:

Synthesize elemental stones into kinds needed for summoning Elemental Spirits. 

Refer: http://irowiki.org/wiki/Analyze_Element

Bug:
When i use this skills, the character gets stuck and can't use kills.

http://prntscr.com/9aiet6

**Comment by Paoly28** [comment]
tested this , it is working. try using 100% var cast reductions to test it.

**Comment by Vaans** [comment]
With the 4 Elemental Analysis (LvL 1 or 2)  when i put the requeriments, and click on trade nothing happens and then the character cant use any skills.

**Comment by Paoly28** [comment]
to some extent i think this is related to call shop bug ??

**Comment by Vaans** [comment]
I don't have problem with the shops :/

**Comment by Lemongrass3110** [comment]
Dear @Vaans,
as of 3f8055d we are at SVN revision 15302. Are you sure you stated the correct SVN version? Also please consider to switch over to GIT or at least tell us the correct GIT hash.
I'm closing this until we have enough valid info from you.
Thanks for understanding.
