### ISSUE TITLE
Effects of some visual items do not appear.

### ISSUE THREAD

**Issue by Pokye** [rathena/rathena#8087]
### rAthena Hash

https://github.com/rathena/rathena/commit/ff90feaf8562fca73ca1d0c9092c8638acee8429

### Client Date

2023-09-06

### Server Mode

Renewal

### Result

All visual items from ID 20549 to 20569 do not appear with the effect.

https://github.com/rathena/rathena/assets/98105181/98862538-6dd0-4a29-bc55-33a5937029ba

### Expected Result

.

### How to Reproduce

.

### Official Information

.

**Comment by Lemongrass3110** [comment]
Everything is working correct on the server side.
Please make sure the client supports this hateffect.
