### ISSUE TITLE
Bug Sell and Buy from NPC Shop

### ISSUE THREAD

**Issue by Dark8008** [rathena/rathena#809]
After upgrade and compile, my server can't sell and buy from NPC Shop, please help !

**Comment by julia40124009** [comment]
confirm
version : https://github.com/rathena/rathena/commit/4b7301ac89893cf3b652580e8c76a2db4303fff1
model : renewal
client : 20141022

**Comment by Dark8008** [comment]
I use same client, please fix quickly !!!

**Comment by Dark8008** [comment]
I use pre-renewal

**Comment by ernestfegarido** [comment]
i confirm this too im using rathena in renewal mode no mods clean rathena and latest :)
