### ISSUE TITLE
RE: Magnum Break Affecting non-watk/eqatk skills.

### ISSUE THREAD

**Issue by Paoly28** [rathena/rathena#810]
How to reproduce,

Cast magnum break ( Marine Sphere or SM_Magnumbreak )

Use Skill Dragon's Breath or Martyr's Reckoning.

Also affects HP portion of gates of hell and Tiger Cannon.

**Comment by Paoly28** [comment]
i badly named it, should be affecting non-atk type of skills sorry about that.

**Comment by MrAntares** [comment]
Well, the description says:
This skill also adds 20% Fire property damage to all attacks for 10 seconds. 

It doesen't say anything about being a weapon atk buff only. It very well can be a final damage bonus of +20%, like racial and elemental cards, but I don't know what is the truth. If you can, please provide an official source for your report, or some official test results, thanks :)

**Comment by secretdataz** [comment]
Fixed in e3cb3fa01f4637fe6acad34c166dad7c75e27079.
