### ISSUE TITLE
script commands: getitembound and getitembound2 do not work as intended when using Bound_Char and Bound_Account

### ISSUE THREAD

**Issue by jezznar** [rathena/rathena#811]
getitembound and getitembound2:
Bound_Char does not bound items to character properly
Bound_Account item can be dropped
![report](https://cloud.githubusercontent.com/assets/13676977/11608460/c165205a-9ba4-11e5-91c6-3570c94a5f3a.png)

**Comment by cydh** [comment]
Tell me if your group doesn't have permission to trade bound items. Thank you :D

**Comment by Atemo** [comment]
I can't reproduce on https://github.com/rathena/rathena/commit/114bebac68df32e3d9eda3452abff1cd2b75500a using character without permission to trade bound items.
