### ISSUE TITLE
CPU of VPS get max when use rathena FluxCP

### ISSUE THREAD

**Issue by Dark8008** [rathena/rathena#812]
![untitled](https://cloud.githubusercontent.com/assets/14345362/11608991/03f31178-9bac-11e5-9a9f-ca46ad6b4d6f.png)
Please help !

**Comment by cydh** [comment]
I close this because u know what the reason.

**Comment by Dark8008** [comment]
hmm, but how to resolve it sir, i use latest fluxcp of rathena @@

**Comment by dastgir** [comment]
If this is specially for FluxCP , this issue should go into FluxCP repo instead of here.
