### ISSUE TITLE
Missing hateffect

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#8121]
### rAthena Hash

https://github.com/rathena/rathena/commit/c43f7b369e797e8f765fef89d082eed1a3eb1b24

### Client Date

Irrelevant

### Server Mode

Pre-Renewal, Renewal

### Result

Hateffects must be updated.

### Expected Result

Irrelevant

### How to Reproduce

Irrelevant

### Official Information

Irrelevant

**Comment by Lemongrass3110** [comment]
Fixed in 9305da4
