### ISSUE TITLE
Skill Bug Vending.

### ISSUE THREAD

**Issue by Vaans** [rathena/rathena#813]
Git Hash/Date: SVN 15255
Client Date: 2015-05-13a
Server Mode: Renewal
Source/Script Mods: None
Descriptions: No warning, no debug, no errors in the console.
How To Replicate:

Info: Opens a custom shop from which items can be sold to other players. Only items stored in the Pushcart can be sold through this skill. 

Bug:
When i put items in the shop, the items disappears.
SS :http://prntscr.com/9aowu8

When i try to buy something with another character.

SS: http://prntscr.com/9aovt0

**Comment by icxbb-xx** [comment]
I have test but normal, make sure try check packets version for 2015-05-13

packet_db_ver: 52
packet_keys_use: 52

![screenrathena test005](https://cloud.githubusercontent.com/assets/3500355/11609559/86995dde-9bbc-11e5-9a90-31be36b62ae1.jpg)

![screenrathena test004](https://cloud.githubusercontent.com/assets/3500355/11609561/8b5236e8-9bbc-11e5-83f4-edf057baddbd.jpg)

**Comment by Vaans** [comment]
Confirmed, was my mistake.
