### ISSUE TITLE
kRO Max HP Limit

### ISSUE THREAD

**Issue by Jedzkie** [rathena/rathena#814]
Hi! in kRO, the max HP limit is set by specific level (Renewal only), reference:

https://github.com/HerculesWS/Hercules/issues/243

**Comment by cydh** [comment]
I saw there is kRO's update/mt notice that say so.

**Comment by Akkarinage** [comment]
Does anyone have any links to info on this?

**Comment by Atemo** [comment]
http://ro.gnjoy.com/news/notice/View.asp?BBSMode=10001&seq=6322&curpage=51
