### ISSUE TITLE
VS2022 Warning Messages

### ISSUE THREAD

**Issue by Masao87** [rathena/rathena#8141]
### rAthena Hash

9305da45dc6e5271e53518617003c3b29fae687c

### Client Date

-

### Server Mode

Renewal

### Result

Fresh & Clean download, just basic changes nothing fancy, receiving a bunch of VS2022 warning messages when compiling.

### Expected Result

No warning messages.

### How to Reproduce

Compile latest Hash with VS2022.

### Official Information

-
![Unbenannt](https://github.com/rathena/rathena/assets/4514182/b026b491-ca6e-4ae2-84c1-a207e036caf8)

**Comment by Pokye** [comment]
Compile in mode **Release x32**
![image](https://github.com/rathena/rathena/assets/98105181/5498e463-cbdd-452a-b82f-f373084c6717)

**Comment by Masao87** [comment]
> Compile in mode **Release x32** ![image](https://private-user-images.githubusercontent.com/98105181/305668548-5498e463-cbdd-452a-b82f-f373084c6717.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMDQ1NDIsIm5iZiI6MTcwODIwNDI0MiwicGF0aCI6Ii85ODEwNTE4MS8zMDU2Njg1NDgtNTQ5OGU0NjMtY2JkZC00NTJhLWI4MmYtZjM3MzA4NGM2NzE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDIxMTA0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlOTQ0Y2NmMGQwN2I1YWEyYWIzNjFjMTA5MTNjZDZiYzc0MjA1NDQyZWFlMzMxNTU2MmFhYzU3NTQ2YjUwYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0J7DXpi4bbyvvuoP1byN35JgOwPN4lHWp9_lZWo1VNo)

![Unbenannt](https://github.com/rathena/rathena/assets/4514182/4f82551c-e026-4102-92e9-e7bc991f3c58)
Getting this error message then when I try that.

**Comment by Pokye** [comment]
**Clean the Solution** first and **Compile**.

https://github.com/rathena/rathena/assets/98105181/0a7ea212-67e4-475b-ab91-17df504ba377
