### ISSUE TITLE
Howling Mine SC returns nullptr and crashes server

### ISSUE THREAD

**Issue by LadyNanuia** [rathena/rathena#8146]
### rAthena Hash

b7da245d6

### Client Date

2023-11-10

### Server Mode

Renewal

### Result

Using Howling Mine (Rebellion) Grenade launcher skill on a bunch of monsters then using flicker will lead to a server crash due to it being returned as nullptr
![fgdfgdfgf](https://github.com/rathena/rathena/assets/54687998/4b616e17-7a2b-4549-8e0b-efaf5d53fa2d)

### Relevant Log Output

```Shell
Posted image above
```

### Expected Result

For it to not crash the server 

### How to Reproduce

Spam Howling mine & Flicker on monsters repeatedly

### Official Information

should..not crash the server?

### Modifications that may affect results

None

**Comment by HarithMichael** [comment]
> also it leads to this ![image](https://private-user-images.githubusercontent.com/54687998/307324089-69df3db0-b067-4ee4-a191-c3315b919155.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDk0OTQsIm5iZiI6MTcwOTU0OTE5NCwicGF0aCI6Ii81NDY4Nzk5OC8zMDczMjQwODktNjlkZjNkYjAtYjA2Ny00ZWU0LWExOTEtYzMzMTViOTE5MTU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDEwNDYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlMDYyMjc4YzY5N2JlZmQwODMwMzg5MTBmNzY0M2NmNTY2NDI1ZTYxNjQyMTBiY2Y4YTAxZjVhYThmZDNhOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XPyk56vs6UXh-TheYfwL4uKrzoQM-dFz5As-RoKJNPI)

I'm also getting this Server Crash

**Comment by LadyNanuia** [comment]
> > also it leads to this ![image](https://private-user-images.githubusercontent.com/54687998/307324089-69df3db0-b067-4ee4-a191-c3315b919155.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDk0OTQsIm5iZiI6MTcwOTU0OTE5NCwicGF0aCI6Ii81NDY4Nzk5OC8zMDczMjQwODktNjlkZjNkYjAtYjA2Ny00ZWU0LWExOTEtYzMzMTViOTE5MTU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDEwNDYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlMDYyMjc4YzY5N2JlZmQwODMwMzg5MTBmNzY0M2NmNTY2NDI1ZTYxNjQyMTBiY2Y4YTAxZjVhYThmZDNhOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XPyk56vs6UXh-TheYfwL4uKrzoQM-dFz5As-RoKJNPI)
> 
> I'm also getting this Server Crash
> 
> Here is mine: https://i.imgur.com/5B1ZXKA.png

i literally just posted that image above xD
