### ISSUE TITLE
Disabled Costume's Sprite on certain map

### ISSUE THREAD

**Issue by cydh** [rathena/rathena#815]
Info from idRO, I wear headgear costumes, on certain maps, say it's TE Guild Dungeon and TE Castles itself, the costume's sprites are disappeared.

I was messing around on `src/map/clif.c::clif_maptypeproperty2`, there's fun note there.
````
		((map[bl->m].flag.noitemconsumption?1:0)<<8)| // DISABLE_COSTUMEITEM - Unknown - (Prevents wearing of costume items?)
````
The comment says **Prevents wearing of costume items** but, consumption wth that `noitemconsumption` flag? xDD

Here's my SS,
* **Outside TE Castle (te_prt_gld)**
![screenfree thor gratis 1349](https://cloud.githubusercontent.com/assets/4016864/11611647/bdabd20e-9c0a-11e5-83a2-35422e4ab75b.jpg)
* **Inside TE Castle (te_prtcas01)**
![screenfree thor gratis 1350](https://cloud.githubusercontent.com/assets/4016864/11611648/c38a3954-9c0a-11e5-93b2-a31f043f280b.jpg)
* **Inside TE Guild Dungeon (teg_dun01)**
![screenfree thor gratis 1352](https://cloud.githubusercontent.com/assets/4016864/11611658/4b42cc4e-9c0b-11e5-9c52-5711fa033757.jpg)

For Valkyrie/Prontera Castles, Costume sprite is still remains.

**Comment by julia40124009** [comment]
useful 
thanks cydh
