### ISSUE TITLE
SC_M_DEFSCROLL [Error]: status_change_start: Invalid status change (890)!

### ISSUE THREAD

**Issue by victorsantosdevops** [rathena/rathena#8160]
### rAthena Hash

28 feb release

### Client Date

2022-04-06

### Server Mode

Pre-Renewal

### Result

Every time i used this item

  - Id: 23204
    AegisName: M_DEFScroll
    Name: Shining Defense Scroll
    Type: Usable
    Weight: 10
    NoUse:
      Sitting: true
    Trade:
      NoDrop: true
      NoTrade: true
      NoSell: true
      NoCart: true
      NoGuildStorage: true
      NoMail: true
      NoAuction: true
    Script: |
      specialeffect2 EF_HEAL3;
      sc_start2 SC_M_DEFSCROLL,600000,500,200;
      
      I got error [Error]: status_change_start: Invalid status change (890)!
      
      I tried increasing max_def to see if this is the error, but the error continues.
      

### Relevant Log Output

```Shell
[Error]: status_change_start: Invalid status change (890)!
```

### Expected Result

The character receives the bonus declared in the effect script in MDEF and DEF

### How to Reproduce

Pre-renew server
Use item 23204

### Official Information

No

**Comment by Atemo** [comment]
`Shining Defense Scroll` is a renewal item. Import `SC_M_DEFSCROLL` from `re/status.yml` to use it on pre-renewal.
