### ISSUE TITLE
Gates of Hell  Damage 

### ISSUE THREAD

**Issue by julia40124009** [rathena/rathena#817]
Gates of Hell

rAthena  support bonus bLongAtkRate

http://irowiki.org/wiki/Hell_Gate

It seems to be no support in iro ?

Twro not support bonus bLongAtkRate damage

version : https://github.com/rathena/rathena/commit/8b3b32e0007255bd7cde1a936bd006cc7e66f7b7
client : 20141022
model : renewal

**Comment by Barigas** [comment]
There is alread topic about this skill https://github.com/rathena/rathena/issues/771 so it basically has wrong formulae now. And you are right, this skill should not be affected by % ranged damage cards, both defensive and offensive.
