### ISSUE TITLE
Jobmaster cannot change to Night Watch and Hyper Novice

### ISSUE THREAD

**Issue by gmragnarok** [rathena/rathena#8176]
### rAthena Hash

5ebfd541639a98793a9c57b66ffef2fde09aa288

### Client Date

2022-04-06

### Server Mode

Renewal

### Result

Jobmaster cannot change to Night Watch and Hyper Novice

### Expected Result

Jobmaster can change job to Night Watch and Hyper Novice

### How to Reproduce

Just enable https://github.com/rathena/rathena/blob/master/npc/custom/jobmaster.txt
And use it

### Official Information

N/A

**Comment by LadyNanuia** [comment]
I reported this a long time ago and they told me since it was not in rA at the time, but since it is now i guess it should be added to the job master.

**Comment by gmragnarok** [comment]
That's right because rAthena has implemented Hyper Novice and Night Watch

**Comment by Atemo** [comment]
Fixed in https://github.com/rathena/rathena/commit/73b878db377b62b5c8485fc63c6d08c36def3d34
