### ISSUE TITLE
The 2024 version of the problem where every job seems to be a Novice!!!

### ISSUE THREAD

**Issue by hiphop9** [rathena/rathena#8188]
### rAthena Hash

803a485e6

### Client Date

20240117

### Server Mode

Renewal

### Result

Every job looks like a 2024 version of Novice
![스크린샷 2024-03-26 224732](https://github.com/rathena/rathena/assets/145139842/e677ac8f-6e97-4890-a1bc-5706bd8775fe)

### Expected Result

After the 4th job change, you can change to the 3rd and 2nd costume (the 2nd top expansion job is the 1st top expansion)!

### How to Reproduce

![스크린샷 2024-03-26 225049](https://github.com/rathena/rathena/assets/145139842/d6555d28-239f-419b-a91b-38115271abe5)

### Official Information

https://www.inven.co.kr/board/ro/1952/330123

**Comment by Pokye** [comment]
You will need a mod for this.

https://github.com/rathena/rathena/assets/98105181/0a39cdc5-384f-4e5f-b704-e92a40f7cf6b

**Comment by LolyAll** [comment]
how can get this client ver?
