### ISSUE TITLE
Tiger Cannon bug？

### ISSUE THREAD

**Issue by idamonli** [rathena/rathena#819]
I used Tiger Cannon without reduce any HP when my character's HP > 110k.(This is a Bug)
If my character's HP less than 110k Tiger Cannon can normal reduce HP.
How can I solve this problem?

**Comment by Paoly28** [comment]
Confirmed this as well.

**Comment by CairoLee** [comment]
to fix this, please open the skill.h

find:

```
/// Single skill requirement. !TODO: Cleanup the variable types
struct skill_condition {
	int16 hp;								 ///< HP cost
	int16 mhp;								 ///< Max HP to trigger
	int16 sp;								 /// SP cost
```

to 

```
/// Single skill requirement. !TODO: Cleanup the variable types
struct skill_condition {
	uint32 hp;								 ///< HP cost
	uint32 mhp;								 ///< Max HP to trigger
	uint32 sp;								 /// SP cost
```

and recompile the server. enjoy it.
i don't have permission to push my code, any one can do this?

**Comment by idamonli** [comment]
thanks cairolee～

**Comment by CairoLee** [comment]
@idamonli you are welcome XD
