### ISSUE TITLE
roulette system 

### ISSUE THREAD

**Issue by julia40124009** [rathena/rathena#820]
look at video 

video state should start two layer road
but I get Silver_Coin
what's wrong....?
https://youtu.be/PsgtdsxXJ9c

version:https://github.com/rathena/rathena/commit/5fc3cbf5b0abbf540f60852c5d9cd9d8d73791b7
client : 20141022
model : renewal
feature.roulette: on
enable PACKET_OBFUSCATION

**Comment by reigneil** [comment]
i think if you get coins that is considered failure and you will be force to start all over again. although there is no animation of roulette pointing to it...

**Comment by Lemongrass3110** [comment]
Sorry the answer took so long.
The problem is that there is no special animation when you fail(hit a coin). You just directly get the prize without any further information, but that's how you know you failed.
This is working as intended.

**Comment by kazegawaajit** [comment]
the one i cant fix it just after we have the lost item (marking as 1 on db_roulette), we cant click start button again and need to reopen roulette window. how to fix it guys?
