### ISSUE TITLE
Critical Hits on Focused Arrow Strike and Gunslingers have incorrect damage

### ISSUE THREAD

**Issue by Playtester** [rathena/rathena#8200]
### rAthena Hash

7d9a23d

### Client Date

2021-11-03

### Server Mode

Pre-Renewal

### Result

When Focused Arrow Strike crits, it always deals max damage.
Bullet attack is included in criticals.
Chain Action can do criticals.

### Expected Result

When Focused Arrow Strike crits, there is damage variance.
Bullet attack is not included in criticals (arrow ATK is!).
Chain Action cannot do critical hits.

### How to Reproduce

Get high crit chance on a sniper, use Focused Arrow Strike, check damage.
Get high crit chance on a gunslinger, equip bullet, check damage. Equip blood shell, check damage.
Get Chain Action, check if there are critical double hits.

### Official Information

Test results:

Focused Arrow Strike (Job 69, 99 DEX, Bow) vs. Ant Egg:
// Sharpshooting
DMG - 985-1100
DMG Crit - 1260-1336
// True Sight 10
DMG - 1225-1346
DMG Crit - 1528-1657 

Gunslinger (Job 70, 99 LUK, Crimson Bolt) vs. Verit:
Crit With Bullet - 78
Crit With Blood Shell - 78
Crit With Silver Bullet - 117
vs. Golem
Crit With Bullet - 78
Crit With Blood Shell - 78
Crit With Silver Bullet - 78

Grenade Launcher + Lighting Sphere:
Crit vs. Verit - 253
Crit vs. Golem - 253

Sniper (Job 69, 99 LUK, Bow) vs. Verit:
Crit with Arrow - 91
Crit with Oridecon Arrow - 116
vs. Golem
Crit with Arrow - 81
Crit with Oridecon Arrow - 99

**Comment by Playtester** [comment]
Checked with 4x Paper Card: Damage of Focused Arrow Strike crit remains the same.

It still does not seem to miss on crits though.

**Comment by Playtester** [comment]
Proof that criticals with guns actually use melee critical formula (need a test where DEX is > weapon damage):

Gunslinger 70 Job, 99 DEX, 90 LUK (Crimson Bolt):
vs. Verit
Crit Bullet - 273
Crit Blood Shell - 273
Crit Silver Bullet - 409
vs. Golem
Crit Bullet - 273
Crit Blood Shell - 273
Crit Silver Bullet - 273

Countertest with Destroyer + Lightning Sphere
vs. Verit - 448
vs. Golem - 448

**Comment by yozzyurubuza** [comment]
May I know the reason or reference on why "Increase Critical Damage" buffs should not work on Focused Arrow Strike?

**Comment by Playtester** [comment]
> May I know the reason or reference on why "Increase Critical Damage" buffs should not work on Focused Arrow Strike?

As noted two posts above yours, I tested with 4x Paper Card and the crit damage of FAS remained the same as without the cards.
