### ISSUE TITLE
Throw Skills Incorrect Damage Formula

### ISSUE THREAD

**Issue by Playtester** [rathena/rathena#8206]
### rAthena Hash

8a10907

### Client Date

2021-11-03

### Server Mode

Pre-Renewal

### Result

When using Throw Shuriken 10 with Mastery 10 (Shuriken 10 ATK equipped), the damage is increased by less than 80 and has a randomness to it even if a normal melee attack has no damage variance.

### Expected Result

Throw Shuriken 10 with Mastery 10 always deals exactly 80 more damage than the normal attack (10 from Ammo + 30 from Mastery + 40 from Skill Level). This bonus has no variance and is not reduced by DEF and even ignores FLEE.

### How to Reproduce

Do a normal attack with a Ninja, then use Throw Shuriken 10 with Mastery 10 while a Shuriken is equipped.

### Official Information

https://ro.kokotewa.com/db/skl_info?id=NJ_SYURIKEN

**Comment by Playtester** [comment]
Ninja 94/70, Dagger Mastery 10, 9 STR, 99 DEX, Shuriken:

Unarmed Normal - 25
Main Gauche+5 Normal - 69
Cursed Unarmed Normal - 18
Cursed Main Gauche+5 Normal - 53

Unarmed Throw Shuriken 10 - 105
Main Gauche+5 Throw Shuriken 10 - 149
Cursed Unarmed Throw Shuriken 10 - 98
Cursed Main Gauche+5 Throw Shuriken 10 - 133

**Comment by Playtester** [comment]
**Important note:** Please also consider the HT_FREEZINGTRAP (and similar skills) calculation here. It is an arrow attack as long as bows+arrows are equipped, but if you equip a knife, it no longer uses the arrow attack min damage calculation.

If we remove the BDMG_THROW flag we need to make sure all those skills are also no longer consider arrow attacks when no bow is equipped. Maybe just removing BDMG_ARROW would also do the trick, but requires further testing.

**Comment by Playtester** [comment]
Since there isn't only some special case for throw skills but also for critical hits with bow, I also want to have some data to cross check for that:

Sniper 94/69 - 99 DEX, 95 LUK vs Golem

4x Paper Card Bow + Arrow:
Critical - 572
True Sight 10 + Critical - 702

+5 Bow + Arrow:
Critical - 328
True Sight 10 + Critical - 400

+5 Bow + Oridecon Arrow:
Critical - 346
True Sight 10 + Critical - 421

Sniper 94/69 - 1 DEX, 95 LUK vs Golem

+5 Bow + Arrow:
Critical - 90
True Sight 10 + Critical - 120

+5 Bow + Oridecon Arrow:
Critical - 108
True Sight 10 + Critical - 142

**Comment by Playtester** [comment]
Ninja 94/70, Dagger Mastery 10, 9 STR, 99 DEX vs Mandragora:

Kindle Dagger - 76
+ Shuriken 10 - 156
+ Fire Kunai 5 - 166x3

+5 Main Gauche - 51
+ Shuriken 10 - 131
+ Fire Kunai 5 - 192x3

**Comment by Playtester** [comment]
Missing:
Shuriken - 80
Kunai 5 - 3x90

**Comment by Playtester** [comment]
Tested also with Magnum Bonus:
Throw Shuriken is not affected by Magnum Bonus.
Throw Kunai is not affected by Magnum Bonus.

**Comment by Playtester** [comment]
Ninja 94/70, Dagger Mastery 10, 9 STR, 99 DEX vs Mandragora:

Kindle Dagger - 25
KindleD + Shuriken 10 - 26
KindleD + Fire Kunai 5 - 28x3

+5 Main Gauche  - 9
MainG + Shuriken 10 - 22
MainG + Fire Kunai 5 - 32x3

**Comment by Melk3000** [comment]
In this page https://ro.kokotewa.com/db/skl_info?id=NJ_ZENYNAGE say NJ_ZENYNAGE Skill have 7 Cells Range, is correct? Thx

**Comment by Playtester** [comment]
Could confirm that. Should be 7 range.
