### ISSUE TITLE
Odin Relic (same bug Old card album issue #8224)

### ISSUE THREAD

**Issue by dzurrahman** [rathena/rathena#8229]
### rAthena Hash

66f9318e3

### Client Date

2023-08-17

### Server Mode

Renewal

### Result

same bug like old card album, not give result anyitem

### Relevant Log Output

```Shell
[Error]: get_random_entry: Invalid group id 1599.
[Warning]: Script command 'getrandgroupitem' returned failure.
```

### Expected Result

should give item from group ODIN_ITEMBOX

### How to Reproduce

-

### Official Information

-

### Modifications that may affect results

-

**Comment by dzurrahman** [comment]
@Atemo

**Comment by Atemo** [comment]
Fixed in https://github.com/rathena/rathena/commit/c546e679952ff06b4125cad5e2e958b97304dae9
