### ISSUE TITLE
Follow up to #779

### ISSUE THREAD

**Issue by dragonis1701** [rathena/rathena#823]
The fix of elemental resistance potions by converting all elemental changes to a new section called:
void status_calc_def_ele_pc(struct map_session_data *sd, struct status_change *sc) {

Elemental resistance potions do not lose their effect. Whether the player is dispelled, dies or the timer runs out. The effect never stops until the player changes armor, changes map or logins out after the effect has ended. It's pretty much the same as #779 except the effect now starts when the player uses the item but the effect does not end. 

Oddly enough, this does not apply to Providence. This does apply to the Undead Element Scroll and Sorcerer's Summons Defensive abilities. SC_ARMOR_ELEMENT, SC_ARMOR_RESIST, SC_FIRE_CLOAK, SC_WATER_DROP, SC_WIND_CURTAIN and SC_STONE_SHIELD.

**Comment by cydh** [comment]
u're liking to make a joke, right? #779 isn't even fixed nor closed, the branch is still flaw (that's why I don't merge it yet) and now u open new issue here. /hmm
