### ISSUE TITLE
RK DragonBreath Fire/Water affected by modifiers.

### ISSUE THREAD

**Issue by Paoly28** [rathena/rathena#827]
Currently Dragon's Breath Fire/Water receives bonuses from size/race/atk in which it shouldn't since it has no weapon and equip atk however it should also get reductions.

here's the official info

Full test iRO from hayroh
https://www.youtube.com/watch?v=fM5HSYgaEk8

Full test kRO from Ziu
https://www.youtube.com/watch?v=LRWv0wtg2qE

to confirm report #548

**Comment by idamonli** [comment]
skill_db
0x42 to 0x4A

**Comment by MrAntares** [comment]
Connecting issue
https://github.com/rathena/rathena/issues/834

**Comment by reigneil** [comment]
@idamonli yeah change this to 0x4A much like official behavior to me.

**Comment by Paoly28** [comment]
currently DB isn't ignoring def.

however can we check whether the formula is multiplicative or additive/subtractive. since if target is wearing 100% ranged reduction and if RK is wearing 4 Archer Skel should the dmg get reduced by 60% or should the reduction still set at 100%

**Comment by Darkelfen** [comment]
I was checking the vids but on both size modifiers weren't tested. 
Only elemental / ranged / race. Do we have any intel on how size affects Dragon Breath in officials?

Test made at 33f397c against "Mobster" (Neutral - Demihuman - Medium Sized):
Knife [4] without cards: DMG 16203.
Knife [4] with 3x White Knight Card (+20% damage on Medium/Large): DMG 25953.

**Comment by Paoly28** [comment]
size doesn't work, size,atk,element and race modifier only affects weapon atk and dragon's breath doesn't calculate it. also upon testing Dragon's Breath interacts just like Cart Cannon when it comes defense it's like this, total damage - (status def + equip def) making def not so important although it does affect it.

**Comment by Darkelfen** [comment]
Questionn is how we make DB ignore size mods in rA.

**Comment by SusanoSprites** [comment]
@Darkelfen 0x42 to 0x4A db/re/skil_db.txt

RK_DRAGONBREATH_WATER,Dragon Breath - Water
RK_DRAGONBREATH,Dragon Breath

**Comment by Darkelfen** [comment]
@SusanoSprites but didn't 0x08 bit make the skill also ignore long range modificators, which indeed play a part in the damage output?

**Comment by secretdataz** [comment]
No longer valid.
