### ISSUE TITLE
BG Queue map crash

### ISSUE THREAD

**Issue by thanna** [rathena/rathena#8276]
### rAthena Hash

Old and Latest git with BG Queue enabled

### Client Date

2018-06-21a

### Server Mode

Pre-Renewal, Renewal

### Result

The error resulted to a map crash.

### Relevant Log Output

```Shell
Exception thrown: read access violation.
std::shared_ptr<s_battleground_queue>::operator-><s_battleground_queue,0>(...)->**map** was nullptr.
```

### Expected Result

Shouldn't crash the server but should continue the queue. 

### How to Reproduce

1. Player 1 & Player 2 join the BG queue.
2. when the the clif_parse_bg_queue_lobby_reply shows and one of the players char select or logout and the other player accepts the notification the server will crash.

### Official Information

  N/A

### Modifications that may affect results

  N/A

**Comment by aleos89** [comment]
Is this a 1v1 BG or something?

**Comment by thanna** [comment]
not really but I tested it with a minimum of 1 player per team.

**Comment by aleos89** [comment]
I'm unable to reproduce this.
1. Have 2 players.
2. Player 1 joins KVM 80+ queue as individual.
3. Player 2 joins KVM 80+ queue as individual.
4. 20 second timer is presented to players in queue.
5. Player 1 logs out.
6. Player 2 accepts the 20 second timer.
7. Message is displayed on the bottom stating "Waiting for the opponents."
8. After a few seconds a window pops up stating "Queuing has finished."

No crash was presented in this repeat of what you stated.

**Comment by admkakaroto** [comment]
Are you using a custom bg ?

**Comment by thanna** [comment]
seems that it happen because a small source that I added on the battlegrounds.cpp which I applied to on a latest git copy that I have. sorry to waste your time on this report.
