### ISSUE TITLE
Several monster stats are 1 when they should be 0

### ISSUE THREAD

**Issue by Playtester** [rathena/rathena#8277]
### rAthena Hash

7c44390

### Client Date

2021-11-03

### Server Mode

Pre-Renewal

### Result

All monsters have their stats min capped to 1. For example Golem has 1 INT.
There is a strange hardcoded +1 MATK to all magic damage instead.
The random part of VIT_DEF can go negative in a certain VIT range.

### Expected Result

Monsters can also have 0 for stats. For example Golem has 0 INT.
MATK is as displayed on the status screen, without a secret +1 in damage.
The random part of VIT_DEF is 0 at minimum.

### How to Reproduce

Have 14 INT total, cast Holy Light (or any another magic spell) on Golem.
Then run the same test on a monster with more than 0 INT.
Test against a player with low INT/VIT and slowly increase the values.

### Official Information

Tested (see value in expected result above). Also verified with bolt spells and ice spear - all 100% spells would be deal 6 damage per hit on Golem (18 - 25/12 - 0).
If you test 18 MATK against a naked player, the damage will always be 18 - VIT/2 - INT.

Paladin 94/68, 99 DEX

Normal Attack:
Naked vs. 8 VIT player - 26
Naked vs. 10 VIT player - 24
Naked vs. 13 VIT player - 23
Naked vs. 20 VIT player - 16

Normal Attack vs. Asprika
Naked vs. 8 VIT player - 17
Naked vs. 9 VIT player - 17
Naked vs. 10 VIT player - 16
Naked vs. 11 VIT player - 16
Naked vs. 12 VIT player - 15
Naked vs. 13 VIT player - 15
Naked vs. 14 VIT player - 14
Naked vs. 15 VIT player - 14
Naked vs. 20 VIT player - 10

**Comment by Lemongrass3110** [comment]
Please dont forget to link the commit 05a17d8, which actually introduced that issue.

**Comment by Playtester** [comment]
Testing on a monster with more that 0 INT as counter test (all with 14 INT / 18 MATK):

Lightning Bolt on Picky - 12
Holy Light on Picky - 16
Holy Light on Kukre - 6
Holy Light on Golem - 10
