### ISSUE TITLE
Warlock Stasis not working on enemy

### ISSUE THREAD

**Issue by Paoly28** [rathena/rathena#830]
WL_STASIS is not working on enemies regardless if on a  pvp map or during woe. Affects only the caster and his/her party instead and works outside siege/pvp.

**Comment by aleos89** [comment]
```
(map_flag_vs(src->m)?BCT_ALL:BCT_ENEMY|BCT_SELF)
```
From this it should affect everyone on VS type maps and only affect enemies/self on any other map type.
VS map types:
```
#define map_flag_vs(m) (map[m].flag.pvp || map[m].flag.gvg_dungeon || map[m].flag.gvg || ((agit_flag || agit2_flag) && map[m].flag.gvg_castle) || map[m].flag.battleground)
```

**Comment by Lemongrass3110** [comment]
@Paoly28 could it be that you are experiencing the same problems as described in #918?
