### ISSUE TITLE
Skill Bug when changing jobs

### ISSUE THREAD

**Issue by Iceyz23** [rathena/rathena#8313]
### rAthena Hash

a44d954

### Client Date

2022-04-06

### Server Mode

Pre-Renewal

### Result

1. I've been trying to switch jobs in-game and if you have unlocked skills on the previous job you changed then it will still be unlocked.
2. The skill shortcut is bugged as well because the icon of the skill is still there even if the class is already changed.

I have tried different client date and older hash going back january 2024 and the problem still persists.

### Expected Result

- Skills should not be unlocked when changing class
- Skill shortcuts should be removed once you change class

### How to Reproduce

https://youtu.be/bvXMycV2CNk

### Official Information

NA

**Comment by Playtester** [comment]
Isn't it intended behavior to keep your skills when changing jobs? If I go from 1st job to 2nd job I also keep my skills from 1st job.
So at least official behavior is to keep the skills.

**Comment by aleos89** [comment]
I would also add that if you give players direct access to the `@jobchange` command you've already given them access to `@allskills` or `@skreset`. You can't normally change to different "branches" of classes outside of the base 1-1 jobs.
