### ISSUE TITLE
menu function on callfunc from item will dc caster.

### ISSUE THREAD

**Issue by kaninhot004** [rathena/rathena#8321]
### rAthena Hash

04386a8ebcb0885dd81fce0a166d286e0f07c119

### Client Date

20220602

### Server Mode

Renewal

### Result

Try create function that start with menu "Hey",-,"Hello",L_Hello;

Add it to Red Potion then use Red Potion

A person will dc after used Red Potion.

(Also it create random resource name error)
![image](https://github.com/rathena/rathena/assets/9493525/eb5a2948-750f-4c04-8a5a-0bf79492283d)

### Expected Result

menu can call normally.

### How to Reproduce

None

### Official Information

None

**Comment by datawulf** [comment]
There's an error with clif_sendfakenpc in the change - I can't tell what exactly is wrong as I just reverted just clif_sendfakenpc to fix my issue. Maybe it's something simple ~

It's also happened if you ran into OnTouch of an NPC you didn't see yet (touch radius bigger than view range)
