### ISSUE TITLE
Zeny Abuse for roDEX

### ISSUE THREAD

**Issue by gidzdlcrz** [rathena/rathena#8326]
### rAthena Hash

323db7e66

### Client Date

2018

### Server Mode

Pre-Renewal

### Result

I am not sure if latest rA have this problem. But when sending zeny like 1.5b+ thru roDEX with the default settings. The fee's are not calculated properly. 

### Relevant Log Output

```Shell
N/A
```

### Expected Result

The fees should be properly calculated.

### How to Reproduce

Give your character 1.5b then mail 1.4 to your self. Open the mail and get your zeny. Viola! Free 14m instantly.

### Official Information

N/A

### Modifications that may affect results

N/A

**Comment by Daraen1** [comment]
check this please [398bae5](https://github.com/rathena/rathena/commit/398bae57a8fafe1bdbcdfb589d80620e789fc57bl)

**Comment by mazvi** [comment]
:D your rA not update since 2020?
