### ISSUE TITLE
`switch` script command not working when used in event labels

### ISSUE THREAD

**Issue by jasonch35** [rathena/rathena#8328]
### rAthena Hash

https://github.com/rathena/rathena/commit/f85ca8106695fa7001710059132d42fbb14d8088

### Client Date

2021-11-03

### Server Mode

Pre-Renewal

### Result

I updated rAthena from [hash](https://github.com/rathena/rathena/commit/81894eeba6ee613d5c40bedeb48455303f703ccc) to above version, now `switch` commands not working when used with labels. I also tested with this script in clean fresh install of rAthena, `mes "test";` window appears then nothing else. All 3 event labels are not working.

```
-	script	SwitchTest	FAKE_NPC,{
OnCommand:
OnPCLoginEvent:
OnNPCKillEvent:
	mes "test";
	switch(select("A:B:C")) {
	case 1:
		mes "1";
		break;
	case 2:
		mes "2";
		break;
	case 3:
		mes "3";
		break;
	}
	close;

OnInit:
	bindatcmd "test",strnpcinfo(0)+"::OnCommand";
	end;
}
```

I've only tested `switch`. Maybe there are other commands not working as well, not sure. Reverting back to [hash](https://github.com/rathena/rathena/commit/81894eeba6ee613d5c40bedeb48455303f703ccc) makes it work again.

### Relevant Log Output

No output, just character stuck (unable to walk, chat, anything) for eternity until he/she disconnects.

### Expected Result

script commands working flawlessly.

### How to Reproduce

Use labels on `switch` script command.

### Official Information

N/A

**Comment by Lemongrass3110** [comment]
I think your issue is also related to #8321.

Could you please test the changes of #8330 and see if this fixes your issue?

**Comment by jasonch35** [comment]
Yes, it did fix the issue! Thank you @Lemongrass3110
