### ISSUE TITLE
NPC Guide Brasilis bug 

### ISSUE THREAD

**Issue by Dark8008** [rathena/rathena#833]
![image](https://cloud.githubusercontent.com/assets/14345362/11761177/5b1d1366-a0ea-11e5-9f04-3570ef707827.png)

**Comment by Atemo** [comment]
I just tested it in our last version 27e90f8f455c849ba919f85d9521f1126e6af29a and I can't reproduce. 

Maybe update your emu or just add F_Navi function from https://github.com/rathena/rathena/blob/master/npc/re/guides/navigation.txt
