### ISSUE TITLE
Merchants do not earn money from Vending

### ISSUE THREAD

**Issue by gmragnarok** [rathena/rathena#8339]
### rAthena Hash

aa62b2fa80043db0be831b30ab71a9a521133445

### Client Date

2022-04-06

### Server Mode

Renewal

### Result

Merchants do not earn money from Vending

if Merchant have 2,147,483,647 Zeny (Max Zeny)

Merchants will do not earn money from Vending

![image](https://github.com/rathena/rathena/assets/163844770/a8ed1d6c-cb33-40c3-89e3-329b027c929d)

### Expected Result

In Official players cannot buy from merchants whose Zeny is full.

### How to Reproduce

1. create item Poring Egg on Merchant
2. Make zeny to maximum on merchant 2,147,483,647
3. vending the poring egg with price 1.000.000
4. using `@autotrade`
5. buy it using another account

### Official Information

In Official players cannot buy from merchants whose Zeny is full.

**Comment by jamesandrewww** [comment]
vending_over_max: no

**Comment by Daegaladh** [comment]
Actually in official servers you can't use Vending if the total amount exceeds max zeny

**Comment by Pokye** [comment]
An (unofficial) suggestion
When enabling the **vending_over_max option: yes**
The exceeded zeny value should be sent via Rodex to be redeemed later.

**Comment by gmragnarok** [comment]
> Actually in official servers you can't use Vending if the total amount exceeds max zeny

Thanks for the correction

**Comment by Daegaladh** [comment]
Thanks to @secretdataz I've learned that in kRO (and probably others) it allows you to put the items on the shop, but other players cannot buy them if you'll exceed max zeny.
But some servers like twRO throw a pop-up message if the total amount of the zeny in the shop plus your current zeny exceeds max zeny, so I changed vending_over_max to emulate that behavior.
