### ISSUE TITLE
Item drop location when killing a monster

### ISSUE THREAD

**Issue by Playtester** [rathena/rathena#8345]
### rAthena Hash

c83f41a

### Client Date

2021-11-03

### Server Mode

Pre-Renewal

### Result

When killing a monster its loot drops on random cell in a 3x3 area around it.

### Expected Result

When killing a monster, its first regular drop will always drop at the exact cell the monster was on. It even drops there when the monster is inside Icewall.
After that each following drop drops in the following pattern: SE -> W -> N -> SE (it repeats, but never returns to center)
If those cells are occupied by walls (including Icewall), the item will drop in a 3x3 around that target cell instead (e.g. SE can become 2S).

### How to Reproduce

Kill a monster that often drops items e.g CRYSTAL_1 (1395) or EVENT_RICECAKE (1815).
Try again with walls being near it. 
Try again by blocking all target cells with Icewall.

### Official Information

Can easily be verified through tests.

**Comment by idk-whoami** [comment]
Is it possible to add the mob_loot do not show effect when drop into #8347

**Comment by Playtester** [comment]
> Is it possible to add the mob_loot do not show effect when drop into #8347

Currently no good way to differentiate between looted items and normal drops. That's why I reduced this issue also to normal drop behavior only and applied it to all. (In reality looted items actually start north.)

**Comment by Playtester** [comment]
Will check if the following things could be handled it one go or if a separate issue for them would be better:
- Aegis has two item lists: Looted items and all other items (regular drops + item/skill granted drops)
- Non-looted items drop item/skill granted drops first and the regular drops in their order from first to eight slot, the first item drops center
- Looted items drop in the order they were looted, the first item drops north
- Items never drop on walls, icewalls and also not on PC-occupied cells, if occupied, they search a free area in a 3x3 around them
- If you drop an item manually it will drop on a free cell (same rules as above) in a 5x5 area around the player (random cell)
