### ISSUE TITLE
Cash Shop Sale Limited

### ISSUE THREAD

**Issue by Pokye** [rathena/rathena#8348]
### Is your request related to a missing official feature?

Yes

### Describe the solution you'd like

Implement in rAthena the Cash Shop Sale Limited for Clients 2019-07-24 above.

**Comment by aleos89** [comment]
Might need @Lemongrass3110's input, but I think this was due to removal in newer clients.

**Comment by datawulf** [comment]
iirc the ui/date-format had a little update last year

**Comment by Lemongrass3110** [comment]
Duplicate of #7512
