### ISSUE TITLE
Special PopUp

### ISSUE THREAD

**Issue by Pokye** [rathena/rathena#8350]
### Is your request related to a missing official feature?

Yes

### Describe the solution you'd like

Implement Special PopUp in rAthena, a system already being used in kRO (system/spopup.lub). Herc has already implemented (https://github.com/HerculesWS/Hercules/pull/3174)

**Comment by eppc0330** [comment]
https://github.com/eppc0330/rathena/pull/4

Converted code for rA

**Comment by Lemongrass3110** [comment]
> [eppc0330#4](https://github.com/eppc0330/rathena/pull/4)
> 
> Converted code for rA

Can you make it a PR to rathena/master?
