### ISSUE TITLE
Booster Pack item issue

### ISSUE THREAD

**Issue by hendra814** [rathena/rathena#8355]
### rAthena Hash

lastest rathena

### Client Date

2021-11-03

### Server Mode

Renewal

### Result

when open item Booster_Pack_100 (item ID 100036 )
Not receive item Booster Armor Upgrade Package (item ID100043 )
and when try open item Booster Armor Box (item ID 101423) it not show the armor set box option
![image](https://github.com/rathena/rathena/assets/9587609/e9ac05fd-69df-47a3-9e06-e71becc533c4)

### Relevant Log Output

```Shell
i'm not sure because never play at KRO server and maybe the event already ended.
only check in this link https://www.divine-pride.net/database/item/100036/100 for item detail.
```

### Expected Result

Give  item Booster Armor Upgrade Package (item ID100043 )
and can select the package from item Booster Armor Box (item ID 101423)

### How to Reproduce

Try open item Booster_Pack_100 (item ID 100036 )

### Official Information

https://www.divine-pride.net/database/item/100036/100 for item detail.

**Comment by Atemo** [comment]
- The "booster pack 100" (Id 100036) does not contain "Booster Armor Upgrade Package" (Id 100043) according to the Korean item description.

- The package "Booster Armor Box" (Id 101423) already exists in rAthena DB (item DB and item package DB) https://github.com/rathena/rathena/blob/master/db/re/item_packages.yml#L425
