### ISSUE TITLE
Ashura Strike Over Damage output

### ISSUE THREAD

**Issue by saggys23** [rathena/rathena#8358]
### rAthena Hash

361530a1b65d95e91e3fcffd2dae5f6a8459f925

### Client Date

2021-11-03

### Server Mode

Renewal

### Result

Ashura Damage have dieffrent Damage, with same code source / skill related between 2 emu version.
Old left one arround  2020-2021 ra ver, and right side is latest.

Ashura Strike latest version over damage.
Latest :
![image](https://github.com/rathena/rathena/assets/26936542/d750d872-1f4d-4871-8901-216eee9973e0)

Old :
![image](https://github.com/rathena/rathena/assets/26936542/c1baa008-31f6-4447-9aa3-6be23fca95c2)

### Expected Result

The damage result of Ashura Strike should be the same, as there is no difference in the source/skill code between them.
and the damage output should be identical to the old version.

### How to Reproduce

Just use fresh Latest Rathena, and fresh Rathena version arround 2020-2021..

### Official Information

It can be tested on the latest official clients.

### Modifications that may affect results

No modification. use fresh.

**Comment by Haydrich** [comment]
Is Asura Strike not reducing by Neutral cards? like raydrix and others?
