### ISSUE TITLE
BUG 16th_Night Skill Kagerou

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#836]
The ability is increasing cast of some kagerou skills.

Correct video in 1:59.
Link (iRO reference): https://www.youtube.com/watch?v=WBCQ1DSOxbo

Correct video in 3:22.
Link (kRO reference): https://www.youtube.com/watch?v=O1x0ICFSUfg 

In both videos the operation is correct , but is bug in Ar.

http://irowiki.org/wiki/16th_Night

**Comment by aleos89** [comment]
You're using an outdated rAthena then. This was fixed a while ago in af60b28.
