### ISSUE TITLE
Guillotine Fist Damage Issue

### ISSUE THREAD

**Issue by Haydrich** [rathena/rathena#8363]
### rAthena Hash

master

### Client Date

20230905

### Server Mode

Renewal

### Result

The damage of the skill depending on kRO / rA
I tried without Raising Dragon skill first to know the damage with 5 sphere spirit only

https://github.com/rathena/rathena/assets/54556365/3de1c3aa-6aec-4b68-bdaa-61748a7f0c37

https://github.com/rathena/rathena/assets/54556365/e97c089b-b271-4eaf-a5b7-ac25f911db07

kRO result was 766k but rA 1.2m
Then tried with Raising Dragon to get the final result of 15 sphere spirit

https://github.com/rathena/rathena/assets/54556365/77c45a11-eb54-4ea9-8684-32bdb936bb44

https://github.com/rathena/rathena/assets/54556365/673095ce-9a08-4dd0-84be-eba65013fc8a

kRO result was 1.7m but rA 2.6m

Notes: 
1. Noticed that my HP/SP in rA when i used Raising Dragon not same as kRO
2. In rA Guillotine Fist not reduced by Neutral reduction cards, EX: Raydric Card/ Deviling Card or any relative cards

### Expected Result

N/A

### How to Reproduce

Try Guillotine Fist

### Official Information

N/A

**Comment by Playtester** [comment]
Can you add which monster ID this Barricade has?

**Comment by Haydrich** [comment]
Barricade ID is 21065 and the location in kRO tra_fild 116 159

**Comment by Playtester** [comment]
@Haydrich  Can you also get the damage of a few normal attacks from kRO? Just to make sure the base damage isn't off already.

**Comment by Haydrich** [comment]
> @Haydrich Can you also get the damage of a few normal attacks from kRO? Just to make sure the base damage isn't off already.

Can you dm me in Discord for more information?
`haydrich`

**Comment by Playtester** [comment]
Test results:
Trans Sura with the following stats
![grafik](https://github.com/rathena/rathena/assets/3785983/3ae62671-f6b9-49db-b4ca-c0b8199b48f9)
BaseLevel 174
JobLevel 59
SP 1877

Iron Hand 10
Guillotine Fist 5

vs. Barricade 21065: 73322

vs. Cardinal
![grafik](https://github.com/rathena/rathena/assets/3785983/d3251d37-b92d-41f4-9184-2afea811732b)
Ungeared - 73195
With Mantle - 73158

vs. Merchant 59/47, all base stats 1
Ungeared - 73340
15% Neutral Resist Hood - 73336

Mace equipped:
Ungeared - 84684
15% Neutral Resist Hood - 83311

Conclusions:
- The fixed +1000 damage bonus should be applied after the ratio and now before it
- Guillotine Fist does not IgnoreDEF in renewal but it uses the simple HardDEF+SoftDEF reduction formula like Dragon Breath, Cannon skills and Grand Cross
- Guillotine Fist does ignore Res

This also shows that neutral damage reduction only applies to weapon damage but not to status damage, but that part is already working in rAthena.

**Comment by Playtester** [comment]
Also ran tests on Counter Slash which is affected by this fix:
![grafik](https://github.com/rathena/rathena/assets/3785983/537b3262-d1cc-45d6-b981-c281a5e9a279)
Shadow Cross 245/51

Counter Slash vs. Zombie:
Level 10 - 92437-92478
Level 10 +12 Agi - 92968-93010
Level 1 - 31424-31438

Conclusion:
- Each Agi increases skill ratio by 2%
- Job level adds 280% (70*4%) to skill ratio if you are 4th job, regardless of your 4th job level
- There no bonus to base damage, neither before nor after skillratio

**Comment by Playtester** [comment]
Shield Press is also affected by this change.

vs. Dummy 21064:

![grafik](https://github.com/rathena/rathena/assets/3785983/a4ea40ee-c73e-4c40-a182-66d1bbd4288b)
![grafik](https://github.com/rathena/rathena/assets/3785983/a747f1e5-76f7-47fd-acab-8961c0311791)
![grafik](https://github.com/rathena/rathena/assets/3785983/678a3726-7858-477e-95c7-8381801a0dfb)
![grafik](https://github.com/rathena/rathena/assets/3785983/ecf77ffc-d2df-4d0c-99d8-7d4a032f1df3)
