### ISSUE TITLE
Illusion of under water daily quest not working

### ISSUE THREAD

**Issue by BotGigo** [rathena/rathena#8364]
### rAthena Hash

7ee7a25887dce884a66cb82cd4202a8f8f4bb913

### Client Date

2022-04-06

### Server Mode

Renewal

### Result

The players are reporting that they can´t take the daily quest fo said dungeon, the script is just letting complete the main quest, but don´t let players take the daily quest.

### Expected Result

Jerimon is supposed to give you the option to repeat the hunting mission inside the dungeon, but this is not happening.

### How to Reproduce

Complete the main quest of the Illusion Of Under Water dungeon, then try to take the daily quest. it will not work.

### Official Information

"Entrance to Illusion of Underwater is open now. Daily Quests are avalable at Jerimon NPC inside now."

This is taken from the step 11 of the main quest from iRo. [https://irowiki.org/wiki/Illusion_of_Underwater#Daily_Quests](url)

**Comment by Atemo** [comment]
I didn't find any issues while testing.
Do you have the correct hash? A cooldown has been fixed in commit https://github.com/rathena/rathena/commit/fbd0478864990369111960e9b6c620160c1b7107

**Comment by BotGigo** [comment]
Yes Sr, the has is correct, and yes, that fix is already in my emulator. ill post 

this is the msg that is giving me.
![imagen](https://github.com/rathena/rathena/assets/59173632/d835f801-9af6-4c2c-986e-7080116027af)

my impresion is that for some reason the script is not erasing the cool down quests, and is stuck since it needs to clear both quest in order to re take them.

**Comment by BotGigo** [comment]
![imagen](https://github.com/rathena/rathena/assets/59173632/3528fd1f-7b22-465f-9c6f-d4a59eacfd0a)
this is the db status for both quests in the sql db

**Comment by BotGigo** [comment]
[quests_illusion_dungeons.txt](https://github.com/rathena/rathena/files/15462045/quests_illusion_dungeons.txt)

i think the problem is in line 9598 and 9645 for quest 3414 and 3416. The state 1 in the quest leads to a dead end in the script.

**Comment by BotGigo** [comment]
I found the solution. ill make a pull request and quot this issue.

**Comment by gmragnarok** [comment]
Don't close this issue, leave it open until the pull request is merged. This is so that it becomes a common concern if this is an issue.

**Comment by BotGigo** [comment]
> Don't close this issue, leave it open until the pull request is merged. This is so that it becomes a common concern if this is an issue.

understood

**Comment by Atemo** [comment]
Fixed in https://github.com/rathena/rathena/commit/4e77ada89578c89fea23b1fc8f04a77c71eb8888
