### ISSUE TITLE
[Problem] Change/Connect to the server.

### ISSUE THREAD

**Issue by Vaans** [rathena/rathena#837]
Git Hash/Date: 2f8699b
Client Date: 2015-05-13e
Server Mode: Renewal
Source/Script Mods: 
Descriptions: [Status]: Connection of the account 'test' accepted.
[Info]: Closed connection from 'xxx.xxx.xxx.xxx'.
[Info]: request connect - account_id:2000000/login_id1:147871202/login_id2:1860969778
[Info]: sd->version = 52
[Info]: Loading Char Data (2000000)
[Info]: Loading Char Data (2000000)

How To Replicate: 
 After the update, when i try to connect or change character the server disconect the player and need to try many times until the server accept the conection.

http://prntscr.com/9dwt7i

**Comment by Lemongrass3110** [comment]
Are you sure you are using 2015-05-13e?
I can't find any client like that. I only found 2015-05-13aRagexe and 2015-05-13aRagexeRE.

**Comment by lighta** [comment]
Not sure is server:map, that screen is usually from char.
Is it when he select a perso back or ? yes need more info

**Comment by Lemongrass3110** [comment]
No further user input for over a month.
Closing this.
