### ISSUE TITLE
Error Packet_Zc_response_enchant

### ISSUE THREAD

**Issue by Beginerxx** [rathena/rathena#8373]
### rAthena Hash

https://github.com/rathena/rathena/commit/05ced985e33823201e592c198a52d9f3ec8feea6

### Client Date

2023-09-05

### Server Mode

Renewal

### Result

Hi ..
I found error on - src/map/clif.cpp

![Screenshot 2024-05-27 090318](https://github.com/rathena/rathena/assets/169546524/cdcf4921-d935-4b6a-8421-4f7411216dad)

![Screenshot 2024-05-27 090359](https://github.com/rathena/rathena/assets/169546524/68766352-8524-4a14-9b27-eec4f304d8b7)

### Relevant Log Output

```Shell
none
```

### Expected Result

none

### How to Reproduce

none

### Official Information

none

### Modifications that may affect results

none

**Comment by Daegaladh** [comment]
You haven't properly updated your emulator, it seems you missed b6f17692e9b5f8137694c9cd75e1d3a48e84ca61
