### ISSUE TITLE
VIP MAX CHAR

### ISSUE THREAD

**Issue by Gyakushinn** [rathena/rathena#8375]
### rAthena Hash

d05e11aecd76e8f57848851a06ee2995e37a0800

### Client Date

2021-11-17

### Server Mode

Pre-Renewal

### Result

command vip +1d character name
get vip in character and relog to select character

console: [Error]: Account '2000002' `character_slots` column is higher than supported MAX_CHARS (21), update MAX_CHARS in mmo.hpp! capping to MAX_CHARS...

### Expected Result

N/A

### How to Reproduce

N/A

### Official Information

N/A

**Comment by Akkarinage** [comment]
The error looks like it's telling you that you can't have more than 21 char slots and that you should look in mmo.hpp to change that.

This is not a bug.
