### ISSUE TITLE
Bug on script @at @afk when send DM

### ISSUE THREAD

**Issue by Beginerxx** [rathena/rathena#8387]
### rAthena Hash

None

### Client Date

2023-09-06

### Server Mode

Renewal

### Result

Hi i found some Bug on script @at @afk when send DM 
Map Server Disconnect.

### Relevant Log Output

```Shell
None
```

### Expected Result

None

### How to Reproduce

None

### Official Information

None

### Modifications that may affect results

None

**Comment by Gyakushinn** [comment]
https://github.com/rathena/rathena/commit/023263df7d2292f66942d264445f3dc4141e8edb

**Comment by Beginerxx** [comment]
> [023263d](https://github.com/rathena/rathena/commit/023263df7d2292f66942d264445f3dc4141e8edb)

Thank you.
