### ISSUE TITLE
warning C4018: '<': signed/unsigned mismatch

### ISSUE THREAD

**Issue by hezekkeiz** [rathena/rathena#8389]
### rAthena Hash

Illusion of underwater cooldown (#8383)

### Client Date

2024-05-30

### Server Mode

Pre-Renewal, Renewal

### Result

8>C:\New Ragnarok\rathena-master\src\tool\csv2yaml.cpp(2336,14): warning C4018: '<': signed/unsigned mismatch
8>C:\New Ragnarok\rathena-master\src\tool\csv2yaml.cpp(2475,21): warning C4018: '<': signed/unsigned mismatch
8>C:\New Ragnarok\rathena-master\src\tool\csv2yaml.cpp(3113,27): warning C4018: '<': signed/unsigned mismatch
8>C:\New Ragnarok\rathena-master\src\tool\csv2yaml.cpp(3879,25): warning C4018: '<': signed/unsigned mismatch
8>C:\New Ragnarok\rathena-master\src\tool\csv2yaml.cpp(4135,21): warning C4018: '<': signed/unsigned mismatch
8>C:\New Ragnarok\rathena-master\src\tool\csv2yaml.cpp(4254,20): warning C4018: '<': signed/unsigned mismatch

### Relevant Log Output

```Shell
8>C:\New Ragnarok\rathena-master\src\tool\csv2yaml.cpp(2336,14): warning C4018: '<': signed/unsigned mismatch
8>C:\New Ragnarok\rathena-master\src\tool\csv2yaml.cpp(2475,21): warning C4018: '<': signed/unsigned mismatch
8>C:\New Ragnarok\rathena-master\src\tool\csv2yaml.cpp(3113,27): warning C4018: '<': signed/unsigned mismatch
8>C:\New Ragnarok\rathena-master\src\tool\csv2yaml.cpp(3879,25): warning C4018: '<': signed/unsigned mismatch
8>C:\New Ragnarok\rathena-master\src\tool\csv2yaml.cpp(4135,21): warning C4018: '<': signed/unsigned mismatch
8>C:\New Ragnarok\rathena-master\src\tool\csv2yaml.cpp(4254,20): warning C4018: '<': signed/unsigned mismatch
```

### Expected Result

8>C:\New Ragnarok\rathena-master\src\tool\csv2yaml.cpp(2336,14): warning C4018: '<': signed/unsigned mismatch
8>C:\New Ragnarok\rathena-master\src\tool\csv2yaml.cpp(2475,21): warning C4018: '<': signed/unsigned mismatch
8>C:\New Ragnarok\rathena-master\src\tool\csv2yaml.cpp(3113,27): warning C4018: '<': signed/unsigned mismatch
8>C:\New Ragnarok\rathena-master\src\tool\csv2yaml.cpp(3879,25): warning C4018: '<': signed/unsigned mismatch
8>C:\New Ragnarok\rathena-master\src\tool\csv2yaml.cpp(4135,21): warning C4018: '<': signed/unsigned mismatch
8>C:\New Ragnarok\rathena-master\src\tool\csv2yaml.cpp(4254,20): warning C4018: '<': signed/unsigned mismatch

### How to Reproduce

8>C:\New Ragnarok\rathena-master\src\tool\csv2yaml.cpp(2336,14): warning C4018: '<': signed/unsigned mismatch
8>C:\New Ragnarok\rathena-master\src\tool\csv2yaml.cpp(2475,21): warning C4018: '<': signed/unsigned mismatch
8>C:\New Ragnarok\rathena-master\src\tool\csv2yaml.cpp(3113,27): warning C4018: '<': signed/unsigned mismatch
8>C:\New Ragnarok\rathena-master\src\tool\csv2yaml.cpp(3879,25): warning C4018: '<': signed/unsigned mismatch
8>C:\New Ragnarok\rathena-master\src\tool\csv2yaml.cpp(4135,21): warning C4018: '<': signed/unsigned mismatch
8>C:\New Ragnarok\rathena-master\src\tool\csv2yaml.cpp(4254,20): warning C4018: '<': signed/unsigned mismatch

### Official Information

8>C:\New Ragnarok\rathena-master\src\tool\csv2yaml.cpp(2336,14): warning C4018: '<': signed/unsigned mismatch
8>C:\New Ragnarok\rathena-master\src\tool\csv2yaml.cpp(2475,21): warning C4018: '<': signed/unsigned mismatch
8>C:\New Ragnarok\rathena-master\src\tool\csv2yaml.cpp(3113,27): warning C4018: '<': signed/unsigned mismatch
8>C:\New Ragnarok\rathena-master\src\tool\csv2yaml.cpp(3879,25): warning C4018: '<': signed/unsigned mismatch
8>C:\New Ragnarok\rathena-master\src\tool\csv2yaml.cpp(4135,21): warning C4018: '<': signed/unsigned mismatch
8>C:\New Ragnarok\rathena-master\src\tool\csv2yaml.cpp(4254,20): warning C4018: '<': signed/unsigned mismatch

### Modifications that may affect results

8>C:\New Ragnarok\rathena-master\src\tool\csv2yaml.cpp(2336,14): warning C4018: '<': signed/unsigned mismatch
8>C:\New Ragnarok\rathena-master\src\tool\csv2yaml.cpp(2475,21): warning C4018: '<': signed/unsigned mismatch
8>C:\New Ragnarok\rathena-master\src\tool\csv2yaml.cpp(3113,27): warning C4018: '<': signed/unsigned mismatch
8>C:\New Ragnarok\rathena-master\src\tool\csv2yaml.cpp(3879,25): warning C4018: '<': signed/unsigned mismatch
8>C:\New Ragnarok\rathena-master\src\tool\csv2yaml.cpp(4135,21): warning C4018: '<': signed/unsigned mismatch
8>C:\New Ragnarok\rathena-master\src\tool\csv2yaml.cpp(4254,20): warning C4018: '<': signed/unsigned mismatch

**Comment by Introvert-RO** [comment]
I have same this warning too.

**Comment by hezekkeiz** [comment]
yes its warning need to fix

**Comment by Introvert-RO** [comment]
When I compile rA on VS (using Windows 10/11), I've been receiving this warning for a while, I don't know when this issue will be resolved either. But I hope it will be resolved by the rA team as soon as possible, because they are working very hard right now to fix any issues.

**Comment by aleos89** [comment]
The format of this report has me laughing.

These are simply warnings, as stated. Also these are part of the CSV2YAML conversion tool, so it's not going to affect game play in any way.

**Comment by Introvert-RO** [comment]
> The format of this report has me laughing.
> 
> These are simply warnings, as stated. Also these are part of the CSV2YAML conversion tool, so it's not going to affect game play in any way.

Hmm. As you said, this is just a warning on the part of the CSV2YAML converter.

It doesn't affect the gameplay, that's true.

But is it better? If there aren't any warnings when compiling rA for use?

Because before these warnings There is no warning about this CSV2YAML converter.

Or do you think this report It's just a laughing matter. Don't bother fixing these warnings?

**Comment by aleos89** [comment]
These warnings have been there for quite some time and even if you were to use the CSV2YAML tool, would pose no concern to runtime. They will be fixed, they just aren't of the highest priority because these are almost informational warnings.

I'm simply laughing that little effort was used in the report generation. All the fields are copy-pasted without reading what each field is used for.

**Comment by reunite-ro** [comment]
> > The format of this report has me laughing.
> > These are simply warnings, as stated. Also these are part of the CSV2YAML conversion tool, so it's not going to affect game play in any way.
> 
> Hmm. As you said, this is just a warning on the part of the CSV2YAML converter.
> 
> It doesn't affect the gameplay, that's true.
> 
> But is it better? If there aren't any warnings when compiling rA for use?
> 
> Because before these warnings There is no warning about this CSV2YAML converter.
> 
> Or do you think this report It's just a laughing matter. Don't bother fixing these warnings?

if u read up there, its because of the format.

all the relevant output, expected format is the same thing.

I know as long as the 'input' is understands well, no issue to fix it but..

Imagine all of the issues here are full with this.

Well, just wait for someone to create a PR or merge it in rathena then.

**Comment by Introvert-RO** [comment]
> These warnings have been there for quite some time and even if you were to use the CSV2YAML tool, would pose no concern to runtime. They will be fixed, they just aren't of the highest priority because these are almost informational warnings.
> 
> I'm simply laughing that little effort was used in the report generation. All the fields are copy-pasted without reading what each field is used for.

I think these warnings, it might create anxiety for him. That's why this report was created. Because otherwise, I don't think he would have created this report.

Even though the warnings were not the most important, but he will still try to report these things so they can be fixed.

He probably expected that it might be fixed quickly.

This is my personal opinion. I hope you don't mind.

**Comment by Introvert-RO** [comment]
> > > The format of this report has me laughing.
> > > These are simply warnings, as stated. Also these are part of the CSV2YAML conversion tool, so it's not going to affect game play in any way.
> > 
> > 
> > Hmm. As you said, this is just a warning on the part of the CSV2YAML converter.
> > It doesn't affect the gameplay, that's true.
> > But is it better? If there aren't any warnings when compiling rA for use?
> > Because before these warnings There is no warning about this CSV2YAML converter.
> > Or do you think this report It's just a laughing matter. Don't bother fixing these warnings?
> 
> if u read up there, its because of the format.
> 
> all the relevant output, expected format is the same thing.
> 
> I know as long as the 'input' is understands well, no issue to fix it but..
> 
> Imagine all of the issues here are full with this.
> 
> Well, just wait for someone to create a PR or merge it in rathena then.

It's going to take a while. I think someone will create a PR to fix this like you said.

But I personally I just saw this warning. Just like him. But it has no effect on me. Because it doesn't affect anything in the game.

**Comment by Playtester** [comment]
> The format of this report has me laughing.

Not gonna lie, I was tempted to reply with "Hmm, looks like the result is already matches the expected result, so no problem."
