### ISSUE TITLE
hat_effects maybe bug

### ISSUE THREAD

**Issue by Beginerxx** [rathena/rathena#8392]
### rAthena Hash

https://github.com/rathena/rathena/commit/1b9e46b247701c95d877b5bd875df1f314fd9cf9

### Client Date

2023-09-06

### Server Mode

Renewal

### Result

Hi i found maybe bug after update
https://github.com/rathena/rathena/commit/1b9e46b247701c95d877b5bd875df1f314fd9cf9

look at to clip Thank you.

https://github.com/rathena/rathena/assets/169546524/a0991093-1d40-427d-94e5-5a1d201a8e0e

### Relevant Log Output

```Shell
none
```

### Expected Result

none

### How to Reproduce

none

### Official Information

none

### Modifications that may affect results

none

**Comment by Beginerxx** [comment]
Before update.

https://github.com/rathena/rathena/assets/169546524/1b6a748d-31ff-49b2-9e1d-2e1a28aa048a

**Comment by Akkarinage** [comment]
This looks client related, and we don't provide support for clients after 2021 yet.

Provide your code for testing.

**Comment by Beginerxx** [comment]
Item ID
420242
480298
410127

**Comment by Beginerxx** [comment]
Thank you [Lemongrass3110](https://github.com/Lemongrass3110) now works fine.
