### ISSUE TITLE
Clone damagetaken too much?

### ISSUE THREAD

**Issue by cliffordx3** [rathena/rathena#8395]
My clone damage on was about 900+

https://github.com/rathena/rathena/assets/60565340/86eb644a-bcd0-47c2-9409-ce9df90c3098

And The clone damagetaken was 8500 / 6500

https://github.com/rathena/rathena/assets/60565340/5d0e1b98-6e15-4797-afe4-fbb7144f1dfb

### rAthena Hash

2012

### Client Date

20151104

### Server Mode

Pre-Renewal

### Result

Clone damagetaken is too much.

### Relevant Log Output

```Shell
Clone damagetaken is too much.
```

### Expected Result

Clone damagetaken is too much.

### How to Reproduce

Clone damagetaken is too much.

### Official Information

Clone damagetaken is too much.

### Modifications that may affect results

Clone damagetaken is too much.

**Comment by Akkarinage** [comment]
If you're going to fill out a bug report you need to fill out the form correctly.
- 2012 is not a git hash.
- Repeating the same sentence over and over without providing any more detail is a hinderance.
- Fighting clones of yourself is not official behaviour, so for further assistance with your script you'd need to post for help in our Discord server.

**Comment by cliffordx3** [comment]
how to post for help? what is your discord?
