### ISSUE TITLE
Sapha's Visit Quest Bug

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#840]
script file: trunk/npc/re/quests/quests_dicastes.txt
Revision: all / latest

Player variable:
ep13_3_invite = 4

Since case 4 is missing, you're running into an exception as shown below in the screenshot.
I'm not 100% sure, but my guess would be:

line 359
	if (ep13_3_invite < 4) {

should be
	if (ep13_3_invite < 5) {

But maybe there's more or something else messed up in the script.

![fo6vzzy](https://cloud.githubusercontent.com/assets/12261601/11789712/3fba0a98-a298-11e5-9a3c-4cea000912f0.jpg)

**Comment by Lemongrass3110** [comment]
This is because we followed the script in the aegis leak without thinking. In our current leak it is also like that.

**Comment by Atemo** [comment]
Thanks :)
