### ISSUE TITLE
Map Crash Macro Detector also Client Crashed

### ISSUE THREAD

**Issue by lunamoonf** [rathena/rathena#8406]
### rAthena Hash

e8f1c7f

### Client Date

2022-0406

### Server Mode

Pre-Renewal

### Result

Getting map crash / error automatic closed client when hitting mobs if the detector pops out.

already add this 'Fix Captcha Decompression buffer size' on client.

### Relevant Log Output

```Shell
none
```

### Expected Result

should be not map crash or automatic closed client

### How to Reproduce

Hit Mob then when macro pop  out automatic crash

### Official Information

none

### Modifications that may affect results

i used 220 x 90 bmp 24 bit added almost 20 images.

**Comment by gmragnarok** [comment]
i have same issue, The macro detector make crash client (close without error), if macro detector popup at the same time the player attacks the monster. I have a script that can produce this problem.

```
-	script	AntiBotMacro	-1,{
OnNPCKillEvent:
set @KillBot,@KillBot+1;
if(@KillBot >= rand(10,20)) goto Check;
end;

Check:
macro_detector();
end;
}
```

**Comment by aleos89** [comment]
I'm unable to reproduce this. You could try adding a `sleep2 500;` before the `macro_detector()` call to see if that helps your case.

**Comment by lunamoonf** [comment]
Sorry for this wrong info posting about this macro detector
i found my problem because of my script
closing this.
