### ISSUE TITLE
Crit Animation Display

### ISSUE THREAD

**Issue by dragonis1701** [rathena/rathena#842]
I downloaded the most recent rathena and started it up and it turns out that the Critical Animation display I thought I caused is actually a bug rathena has. So... Yeah. Mobs take extra damage from critical hits but it does not show the damage with a red background.

**Comment by Lemongrass3110** [comment]
![screenrathena003](https://cloud.githubusercontent.com/assets/3517879/11815825/e5b2c376-a34d-11e5-837d-0e1a2f7c476f.jpg)

Works fine on d6343fb with 2015-05-13.

**Comment by Playtester** [comment]
Additional info: This was caused by dragonis sending the endure package to prevent position lag but the client doesn't support a package that is both critical and endure.
