### ISSUE TITLE
But / misconfiguration with npc_itemshop, npc_pointshop

### ISSUE THREAD

**Issue by mgksrt8** [rathena/rathena#843]
Statement:
You can make simple shop using this available shop types. They working as in idle shops fine.
Problem:
You can't buy items in this type of shops for POINTS or ITEMS if you parameter ZENY lower than shop price.
Reproduce:
Make simple shop with POINTS or ITEMS as a currency for example with value 10 price. Make in your inventory 10 currency POINTS or ITEMS. Set your ZENY lower than 10. You can't buy items.

P.S. I think it's checking before or in the same function with npc_zeny (regular) shop type.
Can this be fixed? Thank you for your attention.

**Comment by anacondaqq** [comment]
I can confirm this. This is very old bug, and i'm not sure, is it bug, or client-related stuff.
Related to all revisions.

**Comment by mgksrt8** [comment]
I'm checking with another emulator (hercules) with same exe, they have different source code and with them it works fine. I worrying about our respectful rAthena :)

**Comment by cydh** [comment]
Even so, this is related to client, it just because client read the Zeny. Like or not, we have to "replace" the zeny value to client -when player oen the shop- with the value of shop currency.

**Comment by aleos89** [comment]
The only fix I can think of is to adjust `pointshop` and `itemshop` to follow the `cashshop` method to avoid the Zeny warning.

**Comment by mgksrt8** [comment]
It will be great I think.
