### ISSUE TITLE
EAJL 4th jobs.

### ISSUE THREAD

**Issue by Pokye** [rathena/rathena#8431]
### Is your request related to a missing official feature?

Yes

### Describe the solution you'd like

Currently there is only checking up to the 3rd jobs. It would be very useful to have a check on the 4th jobs as well.

```c
EAJL_FOURTH:
	Checks if a class is a fourth job.
	if(@eac&EAJL_FOURTH)
		mes "Wow, you've really grown!";
```

**Comment by Lemongrass3110** [comment]
For which scripts?

**Comment by Pokye** [comment]
Forgiveness! I just saw that it already exists. https://github.com/rathena/rathena/blob/master/src/map/script_constants.hpp#L268
I was looking at docs/ea_job_system.txt and I didn't have the EAJL_FOURTH information and I thought it hadn't been implemented yet.
