### ISSUE TITLE
Connection to selected server change after disconnect or re-login

### ISSUE THREAD

**Issue by playmro** [rathena/rathena#8433]
### rAthena Hash

449e006

### Client Date

2018/06/20

### Server Mode

Pre-Renewal

### Result

My server use 1 full client to connect to 2 server.

![cmro](https://github.com/rathena/rathena/assets/169693214/69efb1d2-9740-47ed-91ef-71f1db60691f)

When I choose the second line connection (means connect to the 2nd server with different port). It okay without any problem to choose either the mid-rate or the classic.

For this issue; I choose the **classic server** and connect into the game.

The problem is when I disconnect from the server or going back to login screen without closing my client; the server auto detecting the first line (mid-rate) and not the classic that I'm choosing to play before. When I login, it direct connect to mid-rate server.

### Expected Result

Supposedly when disconnect or re-login without close the client, it will stick with the previous server/connection we choose and not change to other server OR the first line server automatically. 

### How to Reproduce

When choose the server 1, it should go to server 1 after disconnect to re-login.
When choose the server 2, it should go to server 2 after disconnect to re-login.

OR it should return to the _select server_ screen again. 

### Official Information

I'm not sure.

**Comment by mazvi** [comment]
This is related client side, not rAthena

**Comment by Lemongrass3110** [comment]
As @mazvi pointed out correctly, this is a client side issue.

**Comment by playmro** [comment]
> As @mazvi pointed out correctly, this is a client side issue.

Alright. Thank you.
