### ISSUE TITLE
Bug Script cashshop NPC.

### ISSUE THREAD

**Issue by Beginerxx** [rathena/rathena#8434]
### rAthena Hash

None

### Client Date

20230906

### Server Mode

Renewal

### Result

Hi.
Please inquire.
I've been updating from here continuously. Until recently, I just saw that the Cash Shop sales NPC had a problem with everyone who used the Cash Shop sales script. The products would become apple-shaped and the prices were distorted.

Did I make any mistakes? Thank you in advance.

-	cashshop	cos1	,19529:129, 19528:129, 19527:129, 19526:129, 19525:129;

![Screenshot 2024-06-16 233207](https://github.com/rathena/rathena/assets/169546524/d938bf53-94f8-43f7-84f6-2c531cfc2412)

### Relevant Log Output

```Shell
None
```

### Expected Result

None

### How to Reproduce

None

### Official Information

None

### Modifications that may affect results

None

**Comment by reunite-ro** [comment]
most probably because of the client/rathena diffed with enable cash shop preview ? didnt know much since I didnt use this cash shop npc because we already have cash shop button.

**Comment by Beginerxx** [comment]
> most probably because of the client/rathena diffed with enable cash shop preview ? didnt know much since I didnt use this cash shop npc because we already have cash shop button.
> 
> if its enable at client side, try to enable at src too. or disable both.

Thank you.
Your script is works fine or not?

**Comment by Beginerxx** [comment]
Because there will be some NPCs like in Eden group 2F use Cash shop it's not work too and custom shop it's not work too.
