### ISSUE TITLE
 item Booster Armor Box (item ID 101423) and item Metal Weapon Box (item ID 101454) Issue

### ISSUE THREAD

**Issue by hendra814** [rathena/rathena#8436]
### rAthena Hash

lastest

### Client Date

2011-11-03

### Server Mode

Renewal

### Result

when try to open item ID 101423 and 101454, it's giving the item like in the items description

### Expected Result

for item Booster Armor Box (item ID 101423)
give selected set equipment

item Metal Weapon Box (item ID 101454)
give selected weapon with refine upgrade +7

### How to Reproduce

create itemID 101423 and 101454
and then try to open it.

### Official Information

![image](https://github.com/rathena/rathena/assets/9587609/5334d3af-61ad-4f46-ad1b-fbfa0dbe614f)
![image](https://github.com/rathena/rathena/assets/9587609/2b54008f-3d64-44a4-af8c-2c78e9c3e76d)

**Comment by Pokye** [comment]
These items use the **Item Package Selection** (https://github.com/rathena/rathena/pull/7239/), client 2022-02-16 or higher is required. In your client version informed in the issue, it will not work.

**Comment by Atemo** [comment]
^like Pokye said.

**Comment by hendra814** [comment]
thanks @Pokye for the information.
