### ISSUE TITLE
Rodex Logs

### ISSUE THREAD

**Issue by Pokye** [rathena/rathena#8446]
### Is your request related to a missing official feature?

Yes

### Describe the solution you'd like

It would be very useful to have an option to select whether or not to activate Rodex logs in the confs, so that we can control the items and zenys that were sent.

**Comment by Daegaladh** [comment]
Isn't already logged as E type transactions?

**Comment by Pokye** [comment]
> Isn't already logged as E type transactions?

oh... true.
```
// 0x00002000 - (E) Log mail system transactions.
