### ISSUE TITLE
Follow up to #842

### ISSUE THREAD

**Issue by dragonis1701** [rathena/rathena#845]
I figured it out. The issue that is causing critical animation display is in the monster.conf file. If the setting below is set to 0 or no, monsters will not display the critical animation when they are hit with a critical attack. 

// Monster damage delay rate (Note 1)
// Setting to no/0 is like they always have endure.
monster_damage_delay_rate:

**Comment by Lemongrass3110** [comment]
This is just as the comment above the setting describes.
If you set this to no or 0 it will be as if the monsters have endure. Endure => no critical hits displayed.

Thanks for your understanding.
