### ISSUE TITLE
Shopping Boards

### ISSUE THREAD

**Issue by Pokye** [rathena/rathena#8452]
### Is your request related to a missing official feature?

Yes

### Describe the solution you'd like

![image](https://github.com/rathena/rathena/assets/98105181/5a66a64a-42f4-409e-b6a8-92dfd464f72d)

[iRO] https://irowiki.org/wiki/Commerce#Shopping_Boards

**This feature is exclusive to iRO, it is not available in kRO.**

**Comment by Daegaladh** [comment]
Added in fa5e642d4dd8328b8061bf08f7157af32c047316
