### ISSUE TITLE
ID: 14538 bug MAX ASPD

### ISSUE THREAD

**Issue by Dark8008** [rathena/rathena#846]
I tried with novice base/job lv 1, use item id: 14538 and my ASPD up to 190 ( max ), please help !

![image](https://cloud.githubusercontent.com/assets/14345362/11900453/902c5222-a5d8-11e5-9bb0-8e409df18b8c.png)

**Comment by philg666** [comment]
what git are you using?
are you on pre-renewal or renewal?

**Comment by Dark8008** [comment]
Latest version, pre-renewal, 2014-10-22 client sir !

**Comment by philg666** [comment]
okay, im going to test this
