### ISSUE TITLE
Boarding_Halter_Box (Item ID: 16682) this should be a rental.

### ISSUE THREAD

**Issue by gmragnarok** [rathena/rathena#8461]
### rAthena Hash

566ac20

### Client Date

2022-04-06

### Server Mode

Renewal

### Result

Boarding_Halter_Box (Item ID: 16682)

Just open this box, 

You will get a permanent item, this should be a rental item. Need to check all rental ig_boxes.

### Expected Result

Boarding_Halter_Box (Item ID: 16682) this should be a rental. Need to check all rental ig_boxes.

### How to Reproduce

Boarding_Halter_Box (Item ID: 16682)

Just open this box, 

You will get a permanent item, this should be a rental item. Need to check all rental ig_boxes.

### Official Information

RENTAL ITEM BOX

**Comment by Pokye** [comment]
The item is correct, I tested it here and it is opening permanently!
This item is permanent and not rental. The description on iRO is for a 1 week rental. However, we follow kRO and not iRO.

**Comment by Beginerxx** [comment]
It's not correct.
    Script: |
      getgroupitem(IG_Boarding_Halter_Box);

Should be :
    Script: |
      getgroupitem(IG_BOARDING_HALTER_BOX7);
OR : 
    Script: |
      rentitem 12622,xxxxxxx;

**Comment by Pokye** [comment]
> It's not correct. Script: | getgroupitem(IG_Boarding_Halter_Box);
> 
> Should be : Script: | getgroupitem(IG_BOARDING_HALTER_BOX7); OR : Script: | rentitem 12622,xxxxxxx;

As I mentioned, item **16682** is correct, it is permanent!
The 7-day ones are **9991** and **17162**.

**Comment by Daegaladh** [comment]
I can confirm 16682 is also 7 days rental, the difference with the others is that you can't put this one in the storage.

**Comment by Atemo** [comment]
In fact, the box gives a permanent item. Please read the Korean description.
