### ISSUE TITLE
Error , buildin_rand: range (0) is too small. No randomness possible.

### ISSUE THREAD

**Issue by Beginerxx** [rathena/rathena#8466]
### rAthena Hash

None

### Client Date

20230906

### Server Mode

Renewal

### Result

Hello, I have a problem when using the random Script. Will encounter problems sometimes Not every time Please help check.
Thank you in advance.

```
if (rand(100) < 5) setarray .@i[0],4001;
else setarray .@i[0],501,502,503,504;
.@itemt = .@i[rand(getarraysize(.@i))];
getitem .@itemt,1;
delitem .@itemn1,.@num1;
```
Error
```
[Error]: buildin_rand: range (0) is too small. No randomness possible.
[Warning]: Script command 'rand' returned failure.
```

### Relevant Log Output

```Shell
None
```

### Expected Result

None

### How to Reproduce

None

### Official Information

None

### Modifications that may affect results

None

**Comment by Daegaladh** [comment]
That's not a bug, you're literally doing rand(0) there `.@i[rand(getarraysize(.@i))];`

Just do this instead:
```
if (rand(100) < 5) .@itemt = 4001;
else .@itemt = rand(501, 504);
getitem .@itemt,1;
delitem .@itemn1,.@num1;
```

**Comment by Beginerxx** [comment]
> That's not a bug, you're literally doing rand(0) there `.@i[rand(getarraysize(.@i))];`
> 
> Just do this instead:
> 
> ```
> if (rand(100) < 5) .@itemt = 4001;
> else .@itemt = rand(501, 504);
> getitem .@itemt,1;
> delitem .@itemn1,.@num1;
> ```

Thank you [Daegaladh](https://github.com/Daegaladh) I'll try.

**Comment by Beginerxx** [comment]
Error
   161 : if (rand(100) < 5) .@itemt = 4001, 4002, 4003;
*  162 : else .@itemt = rand(501,502**','**503,504);
   163 : getitem .@itemt ,1;
   164 : delitem .@item1,.@num1;

**Comment by Atemo** [comment]
Please use the forum/discord for help with your custom issue.
