### ISSUE TITLE
Illusion Investigation of Illusion of Teddy Bear Not Work

### ISSUE THREAD

**Issue by gmragnarok** [rathena/rathena#8475]
### rAthena Hash

995a5d0f60af276ba6869e480bd786799e45e892

### Client Date

2022-04-06

### Server Mode

Renewal

### Result

Illusion Investigation of Illusion of Teddy Bear not trigger the quest.

### Expected Result

Illusion Investigation of Illusion of Teddy Bear trigger the quest.

### How to Reproduce

Just test this NPC ein_d02_i,161,180,5	script	Machoko#machoco	8_F_GIRL

### Official Information

N/A

**Comment by Atemo** [comment]
Fixed in https://github.com/rathena/rathena/commit/1d8dec4b7228873add12f48b7ca742efb1fc667c
