### ISSUE TITLE
It also dropped the line or not.

### ISSUE THREAD

**Issue by cold-hr** [rathena/rathena#848]
clif.c

void
clif_parse_GuildInvite2(int fd, struct map_session_data *sd) {
	struct map_session_data *t_sd = map_nick2sd((char *)RFIFOP(fd, packet_db[sd->packet_ver][RFIFOW(fd,0)].pos[0]));

	if (clif_sub_guild_invite(fd, sd, t_sd))
		return;
}

**Comment by Lemongrass3110** [comment]
Sorry I don't really understand what you try to say.
