### ISSUE TITLE
searchstores bug

### ISSUE THREAD

**Issue by Pokye** [rathena/rathena#8489]
### rAthena Hash

https://github.com/rathena/rathena/commit/25b91266444c3b82f80ee1b3e2f7cd390196d46f

### Client Date

2024-07-03

### Server Mode

Renewal

### Result

Currently, searchstores has a sinister bug, when you try to perform a search, it consumes 2 results at once. and when you try to change the search, it consumes infinitely, leaving a negative value.

https://github.com/rathena/rathena/assets/98105181/3c0a9525-5437-4285-abee-c2428ad17c01

I've already tested it with clients 2022-04-06 / 2023-09-13 / 2024. And it's showing the same problem with everyone.

I had spoken to **Daegaladh** about this, and he still didn't find a solution. So I'll leave this issue open.

### Expected Result

.

### How to Reproduce

.

### Official Information

.

**Comment by Daegaladh** [comment]
For what I've tested it seems newer clients do the calculations on their own and don't take into account the value on the packet.
So we probably need to adapt the code for them to sync with the server.
