### ISSUE TITLE
pet loot issue

### ISSUE THREAD

**Issue by julia40124009** [rathena/rathena#849]
pet_db
<core> 1002,PORING,Poring,619,9001,10013,531,80,60,50,100,250,20,2000,150,1,0,350,400,800,{ petloot 10; },{ bonus bLuk,2; bonus bCritical,1; }
 </core>

pet not loot item

PACKET_OBFUSCATION enable
client  : 20141022
model : renewal
version : https://github.com/rathena/rathena/commit/eec88365e1b02e0cb1972d7000e03677b0e6ae99

**Comment by Lemongrass3110** [comment]
This comes from https://github.com/rathena/rathena/blob/master/src/map/pet.c#L461
Since it has been there since 2012 it might be intended. Need to wait for input from others.

For the meantime you can fix it by setting https://github.com/rathena/rathena/blob/master/conf/battle/pet.conf#L48 to yes.

**Comment by aleos89** [comment]
This is working as normal. You need to adjust your battle config to properly support this like @Lemongrass3110 stated. You'll need to adjust `pet_status_support` to yes. For the attack type skills, just as the config says:
```
// When the master attacks a monster, whether or not the pet will also attack. (Note 1)
pet_attack_support: yes

// When the master receives damage from the monster, whether or not the pet attacks back. (Note 1)
pet_damage_support: yes
```
Need to be adjusted to yes as well. Also make sure you have the pet equip on if you have that config set to yes as well.

Another note, you need to adjust this config for their support skills to be used:
```
// Minimum intimacy necessary for a pet to support their master. Default is 900 
// (intimacy goes from 0 to 1000). At this minimum, support rate is 50% of pet's normal value.
// At max (1000) support rate is 150%.
pet_support_min_friendly: 900
```
