### ISSUE TITLE
Import char_athena.conf does not affect start_items

### ISSUE THREAD

**Issue by gekigengar** [rathena/rathena#8490]
### rAthena Hash

c8935ef18a5e980e931720a0a8cbb122fa01ee24

### Client Date

2022-04-06

### Server Mode

Renewal

### Result

1. Add these to imports/char_conf.txt
```
start_items: 1201,1,2:2301,1,16:12221,1
start_items_pre: 1201,1,2:2301,1,16:12221,1
start_items_doram: 1681,1,2:2301,1,16:12221,1
```
2. Start Server
3. Make new character
4. Alt + E (Open Inventory)
5. Check if 12221 is there (Megaphone)
6. No Megaphone is there.

### Expected Result

Megaphone (12221) will be in inventory

### How to Reproduce

1. Add these to imports/char_conf.txt
```
start_items: 1201,1,2:2301,1,16:12221,1
start_items_pre: 1201,1,2:2301,1,16:12221,1
start_items_doram: 1681,1,2:2301,1,16:12221,1
```
2. Start Server
3. Make new character
4. Alt + E (Open Inventory)
5. Check if 12221 is there (Megaphone)
6. No Megaphone is there.

### Official Information

N/A

**Comment by Lemongrass3110** [comment]
```
[Debug]: start_items_pre: not enough arguments for 12221! Skipping...
[Debug]: start_items_doram: not enough arguments for 12221! Skipping...
```

**Comment by gekigengar** [comment]
My bad, I thought it defaults to 0, thanks!
