### ISSUE TITLE
A way to remove start_item from imports/char_conf.txt

### ISSUE THREAD

**Issue by gekigengar** [rathena/rathena#8492]
### Is your request related to a missing official feature?

No

### Describe the solution you'd like

Right now, there is no way to remove the potion box item.
```
start_items: 1201,1,2:2301,1,16:23484,0,0 // Setting it to 0 does not work
start_items_pre: 1201,1,2:2301,1,16
start_items_doram: 1681,1,2:2301,1,16
```
```
start_items: 1201,1,2:2301,1,16 // Removing it also does not work
start_items_pre: 1201,1,2:2301,1,16
start_items_doram: 1681,1,2:2301,1,16
```
What's the right way to remove potion box item?

### Additional context

![image](https://github.com/rathena/rathena/assets/11358524/c575cd62-f125-4044-8a5c-65cff3872f6d)

**Comment by Lemongrass3110** [comment]
I would say you give our Discord server - especially the support channels - a visit instead of asking questions here on github.

**Comment by gekigengar** [comment]
But you can't remove items using imports/char_conf.txt, which is a missing feature. Thus an issue is it not?

**Comment by Daegaladh** [comment]
I've just tested it and it's true it doesn't work

**Comment by Pokye** [comment]
Please read carefully!
You have set amount **0**
```
Format: <id>,<amount>,<position>
```
```
23484,0,0

**Comment by Daegaladh** [comment]
> Please read carefully! You have set amount **0**
> 
> ```
> Format: <id>,<amount>,<position>
> ```
> 
> ```
> 23484,0,0
> ```

That doesn't work either, for some reason start_items is not overwriting with the changes in the import file

**Comment by ivanlhd** [comment]
On the screenshot it shows amount 0 though 0 ea.

**Comment by Daegaladh** [comment]
> On the screenshot it shows amount 0 though 0 ea.

Yeah I could reproduce that too, it seems the data is overwritten, but not cleared
