### ISSUE TITLE
exp not updating

### ISSUE THREAD

**Issue by Miraakol** [rathena/rathena#8494]
### rAthena Hash

fccf328a5

### Client Date

2015-10-29

### Server Mode

Pre-Renewal

### Result

my character doesn't gain any EXP when killing a monster.

you may refer on this link for reference: https://youtu.be/-dwG0UkbtQg

### Relevant Log Output

```Shell
NA
```

### Expected Result

gain EXP when killing a monster

### How to Reproduce

- use latest rathena trunk
- use default settings (PRE)
- use 2015-10-29a-ragexe (i used latest WARP to patch the client)
- use llchrisll client files (PRE)
- login and create a character
- kill any monster

### Official Information

NA

### Modifications that may affect results

set to pre renewal mode by commenting the renewal lines.

**Comment by Mysame** [comment]
I've stumbled across the same, packetver 20220406 with master checked out.

**Comment by Lemongrass3110** [comment]
Duplicate of #8529

Fixed via #8530 in 612bf70

Please update your emulator.
