### ISSUE TITLE
MVP exp message issue at client 2015

### ISSUE THREAD

**Issue by hendra814** [rathena/rathena#850]
![screenapel ro001](https://cloud.githubusercontent.com/assets/9587609/11921405/ffcec4dc-a7ba-11e5-9a49-4a5a983b6de8.jpg)

After defeating an mvp the game says:
"Congratulations! You are the MVP! Your reward EXP Points are!!"

using client 2015-05-13

**Comment by zackdreaver** [comment]
@icxbb-xx 
so it's a server side problem?
it's happen with 2013+ too as i remember.

**Comment by MrAntares** [comment]
I had a similar in 2012 client
https://github.com/rathena/rathena/issues/733

**Comment by icxbb-xx** [comment]
I confirm 2013-12-23 or newer
May be this packet issue, I try check again

**Comment by joelolopez** [comment]
i confirm this 20150916

**Comment by LiamKarlMitchell** [comment]
Packet ver 20120410 with the client "2012-04-10aRagexeRE" appears to be showing the EXP points correctly.

But if I remember right, when I had a very high exp rate it was just showing me 0.
