### ISSUE TITLE
SpiritHandler Healing Skills Fail

### ISSUE THREAD

**Issue by JairJunior26** [rathena/rathena#8514]
### rAthena Hash

76d7234

### Client Date

2024-01-03

### Server Mode

Renewal

### Result

Good evening, when using any SpiritHandler healing skill, with equipment that provides Healing Effectiveness, it is not affected.

I checked files like skill.conf, skill.cpp, battle.cpp and didn't find anything.

![image](https://github.com/user-attachments/assets/5f45914b-5e07-4269-a67b-078d94833f88)
![image](https://github.com/user-attachments/assets/f2d90af1-902c-4e49-ac2d-fb93ff9e5a1d)
![image](https://github.com/user-attachments/assets/1aefd20c-5b7c-4bdd-b30d-f52c76c69f28)

### Expected Result

Ao utilizar o item https://www.divine-pride.net/database/item/400077 , o resultado esperado é que a cura aumentasse, pois o item é proprio da classe.

### How to Reproduce

Create a SpiritHandler.
Use the Kisul Water Spraying skill
(5439) SH_KI_SUL_WATER_SPRAYING
Equip item 400077 Cat_Shampoo_Hat and check if healing increases

### Official Information

https://www.divine-pride.net/database/item/400077

**Comment by JairJunior26** [comment]
@Atemo Do you have anything regarding this subject?

**Comment by Atemo** [comment]
The issue may or may not be valid, if someone can confirm that the skill is affected by heal modifier.
Please comment directly on the pending pull request (or associated issue, if any) if you have another issue.

**Comment by JairJunior26** [comment]
Right.
The problem is that it occurs in all of the Spirit Handler's healing skills, even the equipment belonging to the class.

**Comment by datawulf** [comment]
> The issue may or may not be valid, if someone can confirm or not that the skill is affected by heal modifier on official server. Please comment directly on the pending pull request (or associated issue, if any) if you have another issue.

SH_KI_SUL_WATER_SPRAYING is affected by Blv, Slv, Mystical Creature Mastery, Commune with Kisul, Int, Crt, StatusMatk, WeaponMatk only.

**Comment by JairJunior26** [comment]
@datawulf 
Thanks also for the help. But in the case of Splash Cat Hat, it applies healing effectiveness, shouldn't it apply to Doram's skills?

Script: |
      bonus bUnbreakableHelm;
      .@r = getrefine();
      bonus bMdef,15;
      bonus bMaxHPrate,20;
      bonus bMaxSPrate,20;
      if (getskilllv("SU_SPIRITOFSEA") >= 1)
         skill "AL_PNEUMA",1;
      if (getskilllv("SU_SHRIMPARTY") >= 5) {
         bonus bMaxHPrate,30;
         bonus bMaxSPrate,30;
      }
      if (getskilllv("SU_GROOMING") >= 5) {
         bonus2 bResEff,Eff_Confusion,10000;
         bonus2 bResEff,Eff_Silence,10000;
      }
      bonus bHealPower,20*getskilllv("SU_PURRING");
      bonus bDef,50*.@r;
      if (.@r >= 7) {
         bonus bDelayrate,-10;
         bonus2 bVariableCastrate,"SU_STOOP",-50;
         bonus2 bVariableCastrate,"SU_LOPE",-50;
         bonus2 bSubClass,Class_Boss,10;
      }
      if (.@r >= 9) {
         bonus bDelayrate,-10;
         bonus2 bVariableCastrate,"SU_STOOP",-50;
         bonus2 bVariableCastrate,"SU_LOPE",-50;
         bonus2 bSubClass,Class_Boss,10;
      }
      if (.@r >= 10)
         autobonus3 "{ bonus bFlee2,100; }",1000,3000,"SU_TUNAPARTY";

**Comment by Atemo** [comment]
> > The issue may or may not be valid, if someone can confirm or not that the skill is affected by heal modifier on official server. Please comment directly on the pending pull request (or associated issue, if any) if you have another issue.
> 
> SH_KI_SUL_WATER_SPRAYING is affected by Blv, Slv, Mystical Creature Mastery, Commune with Kisul, Int, Crt, StatusMatk, WeaponMatk only.

Thanks! Then this issue is closed.
