### ISSUE TITLE
Ground Drift using Freeze Sphere

### ISSUE THREAD

**Issue by XanKriegor1** [rathena/rathena#8516]
### rAthena Hash

c5eaa15

### Client Date

2022-04-06

### Server Mode

Pre-Renewal

### Result

Ground Drift has a special property where, depending on the type of Sphere you have equipped, it has a 50% chance of inflicting certain status effect. This is scripted on skill.cpp line 20465:
`		case UNT_GROUNDDRIFT_WIND:
			if(skill_attack(skill_get_type(sg->skill_id),ss,src,bl,sg->skill_id,sg->skill_lv,tick,sg->val1))
				sc_start(ss,bl,SC_STUN,50,sg->skill_lv,skill_get_time2(sg->skill_id, 1));
			break;
		case UNT_GROUNDDRIFT_DARK:
			if(skill_attack(skill_get_type(sg->skill_id),ss,src,bl,sg->skill_id,sg->skill_lv,tick,sg->val1))
				sc_start(ss,bl,SC_BLIND,50,sg->skill_lv,skill_get_time2(sg->skill_id, 2));
			break;
		case UNT_GROUNDDRIFT_POISON:
			if(skill_attack(skill_get_type(sg->skill_id),ss,src,bl,sg->skill_id,sg->skill_lv,tick,sg->val1))
				sc_start2(ss,bl,SC_POISON,50,sg->skill_lv,ss->id,skill_get_time2(sg->skill_id, 3));
			break;
		case UNT_GROUNDDRIFT_WATER:
			if(skill_attack(skill_get_type(sg->skill_id),ss,src,bl,sg->skill_id,sg->skill_lv,tick,sg->val1))
				sc_start(ss,bl,SC_FREEZE,50,sg->skill_lv,skill_get_time2(sg->skill_id, 4));
			break;
		case UNT_GROUNDDRIFT_FIRE:
			if(skill_attack(skill_get_type(sg->skill_id),ss,src,bl,sg->skill_id,sg->skill_lv,tick,sg->val1))
				skill_blown(src,bl,skill_get_blewcount(sg->skill_id,sg->skill_lv),-1,BLOWN_NONE);
			break;
`
It reads the duration of status effects from the Duration2 line in the skill database. However, for Freezing Sphere, the duration that should be 12000 seconds isn't working. The freeze effect simply ends instantly.

### Expected Result

Duration should match the value on Duration2.

### How to Reproduce

Equip Freezing Sphere and use Ground Drift.

### Official Information

You can view this on the rAthena code directly.

**Comment by Playtester** [comment]
Can confirm this issue.

I introduced the issue in: https://github.com/rathena/rathena/commit/e7150ee936fb788f3a1f8c045262c335d10ffd6c

It seems that my renewal tests shows that freeze is indeed broken immediately: https://github.com/rathena/rathena/issues/998

But I couldn't test pre-renewal back then. It seems in pre-renewal this is not the case. So I will confirm for pre-renewal.

**Comment by Playtester** [comment]
In latest renewal you can't even use Cryo Spheres anymore.

Using Ice Bullet removes the delay again. So I need to revert my change, it no longer applies for neither pre-re nor renewal.
