### ISSUE TITLE
script path

### ISSUE THREAD

**Issue by julia40124009** [rathena/rathena#852]
write wrong script path  in scripts_******.conf

no error no warning message ..

maybe should need show message(error or warning)

I don't know if this is wrong or suggest...?

client : 20141022
version : https://github.com/rathena/rathena/commit/01adc9c3ff3c1c6f0f69f6f9f2db77eba20071d4
model : renewal

**Comment by Lemongrass3110** [comment]
Now you get an error message. Although you have to look for it at the complete top, because the npc source files are parsed right at the beginning.
![error_message](https://cloud.githubusercontent.com/assets/3517879/12059461/c12b5b02-af5b-11e5-856d-4eab5556f85b.PNG)

**Comment by lighta** [comment]
path from basedir/ or basedir/npc/ ?
That remind me of my SO_cleanup branch : https://github.com/lighta/rathena/commit/006a0f11068ca0d766870a4a11eefed5b8c5e7d2

**Comment by Lemongrass3110** [comment]
It's relative to basedir! ;-)
