### ISSUE TITLE
buildin_rand: range (0) is too small. No randomess possible.

### ISSUE THREAD

**Issue by Beginerxx** [rathena/rathena#8521]
### rAthena Hash

https://github.com/rathena/rathena/commit/7c153416bc2b69bbb515c0a3e7a90bcb216d5e4a

### Client Date

20230906

### Server Mode

Renewal

### Result

Hi my friend.
I have reported the problem once about the error as shown in the picture. At first, I thought it was a problem with the script that I wrote again.

But in fact, the problem occurred with other scripts that were previously working normally. If any script worked with rand, it would immediately give the error as shown in the picture. Before the update, all the old scripts were working normally.

For example, this game
https://rathena.org/board/files/file/4158-ambernite-game/

After the update, the game will give the same error as shown in the picture even though no script was edited.

Please check again.
Sorry for my English.

![Screenshot 2024-07-27 203119](https://github.com/user-attachments/assets/94089f5b-bd5f-40cb-ae35-fcc454a446d5)

### Relevant Log Output

```Shell
None
```

### Expected Result

None

### How to Reproduce

None

### Official Information

None

### Modifications that may affect results

None

**Comment by Daegaladh** [comment]
That's a problem with the script itself, not the command or the emulator

And once again, please follow the issue structure.
