### ISSUE TITLE
Bonus and sc_start formula

### ISSUE THREAD

**Issue by ChiaraCWB** [rathena/rathena#8523]
### rAthena Hash

N/A

### Client Date

2024-01-06

### Server Mode

Renewal

### Result

During testing and configuration, I identified that the items, item_combos and effects that use bonus, bonus2, bonus3, bonus4 and sc_start,sc_start2,sc_start3,sc_start4 are not being applied correctly.

1- Swordsman equipping a knife without a card, presents the following damage
![image](https://github.com/user-attachments/assets/3ec21d6d-2fca-40f4-99cd-b8a70bafdeef)

2- When equipping the Turtle General card on the knife, in which the description states that physical damage should increase by 20%, the damage presented is less than the percentage of the card.
![image](https://github.com/user-attachments/assets/b083df2c-33d7-4834-8b64-0622d65b9718)
![image](https://github.com/user-attachments/assets/69d2a17f-f6b1-4b68-8b87-1e33f80eeb3a)

### Expected Result

The expected result is that the damage would increase by 20% according to the card's script. Increasing damage from 231 to approximately 277.

### How to Reproduce

1. Create a character, equip the knife on it and test the damage.
2. Equip the General Turtle card on the knife and test the damage presented again.

### Official Information

In bRO (Brasil Ragnarok Online) and kRO the card description says increase 20%, and the script shows the numeral 20.

**Comment by JairJunior26** [comment]
Up.

I just tested your problem, and the bonus is not applying here either. If you change from 20 to 200 it works correctly. However, it is not the solution, since in item_bonus it is %/100, so you should multiply or perform the calculation in which the result is 20.

**Comment by Atemo** [comment]
For reference https://github.com/rathena/rathena/issues/718#issuecomment-152495018
