### ISSUE TITLE
Duplicate AegisName in item_db

### ISSUE THREAD

**Issue by secretdataz** [rathena/rathena#853]
I noticed that there are some items with duplicate AegisName in rAthena item database.
Most of them are new items and costumes. For example, Costume Puppy hat (19842) and Costume Husky hat (20227) which both have C_Puppy_Hat as their AegisName or Rope (1950, Weapon) and Rope (6687, ETC) or even White Potion (504) and the new untradable White Potion (15565).  
Would these duplicate entries cause any problem?
I've checked Hercules' item database and they don't have any duplicate AegisName entry.

*poke @nanakiwurtz*

**Comment by Lemongrass3110** [comment]
Currently there are 105 duplicate entries for RE and only 3 for PRE.

Here's the SQL script to filter them out(for PRE just remove _re):
```
SELECT
	id,
	name_english
FROM item_db_re
where name_english in(
	SELECT
	name_english
	FROM
	item_db_re
	group by name_english
	having count(*) > 1
)
order by name_english asc;
```

After the cleanup we should add this to both tables to prevent future issues like that:
```
ALTER TABLE `item_db_re`
ADD UNIQUE INDEX `UniqueAegisName` (`name_english`) ;
```

Here are all current entries for RE:

Item ID | Aegis Name
------------ | -------------
22672 | April_Gift_Box
22853	|	April_Gift_Box
17050	|	Aries_Scroll
17117	|	Aries_Scroll
22756	|	August_Gift_Box
22857	|	August_Gift_Box
656	|	Awakening_Potion
22544	|	Awakening_Potion
657	|	Berserk_Potion
22543	|	Berserk_Potion
6672	|	Black_As_Night_Piece
22516	|	Black_As_Night_Piece
13206	|	Blind_Sphere
13226	|	Blind_Sphere
16734	|	Blue_Drooping_Cat_Box
16735	|	Blue_Drooping_Cat_Box
505	|	Blue_Potion
11572	|	Blue_Potion
529	|	Candy
11580	|	Candy
16565	|	Capricorn_Crown_Box
16566	|	Capricorn_Crown_Box
558	|	Chocolate
11587	|	Chocolate
573	|	Chocolate_Drink
11583	|	Chocolate_Drink
16693	|	Crescent_Helm_Box
16694	|	Crescent_Helm_Box
20206	|	C_Chicken_Hat
20210	|	C_Chicken_Hat
20211	|	C_Chicken_Hat
20162	|	C_Fleece_Hat
20163	|	C_Fleece_Hat
20139	|	C_Horse_Hairpin
20140	|	C_Horse_Hairpin
19842	|	C_Puppy_Hat
20227	|	C_Puppy_Hat
22861	|	December_Gift_Box
22886	|	December_Gift_Box
16695	|	Dragon_Skull_Box
16696	|	Dragon_Skull_Box
16697	|	Drooping_Bunny_Box
16698	|	Drooping_Bunny_Box
16603	|	Drooping_Votto_Box
16604	|	Drooping_Votto_Box
17244	|	Event_Almighty_Box
17331	|	Event_Almighty_Box
17567	|	Event_Almighty_Box
17332	|	Event_Almighty_Box(100)
17568	|	Event_Almighty_Box(100)
16699	|	Evolved_Blue_Fish_Box
16670	|	Evolved_Blue_Fish_Box
16701	|	Evolved_Pair_of_Red_Ribbon_Box
16702	|	Evolved_Pair_of_Red_Ribbon_Box
16703	|	Evolved_Pipe_Box
16704	|	Evolved_Pipe_Box
13505	|	Executioner_Box
16424	|	Executioner_Box
16736	|	Fantastic_Wig_Box
16737	|	Fantastic_Wig_Box
22627	|	February_Gift_Box
22851	|	February_Gift_Box
13203	|	Flare_Sphere
13223	|	Flare_Sphere
13207	|	Freezing_Sphere
13227	|	Freezing_Sphere
20717	|	Gigant_Snake_Skin
20718	|	Gigant_Snake_Skin
7856	|	Girl_Bunch_Of_Flower
11701	|	Girl_Bunch_Of_Flower
12841	|	Golden_Treasure_Box
14623	|	Golden_Treasure_Box
16732	|	Gray_Deviruchi_Hat_Box
16733	|	Gray_Deviruchi_Hat_Box
506	|	Green_Potion
11571	|	Green_Potion
16730	|	Green_Ribbon_Box
16731	|	Green_Ribbon_Box
16705	|	Hibiscus_Box
16706	|	Hibiscus_Box
6532	|	Honey_Songpyun
22657	|	Honey_Songpyun
12885	|	Infinite_Awakening_Potion
17227	|	Infinite_Awakening_Potion
12886	|	Infinite_Berserk_Potion
17228	|	Infinite_Berserk_Potion
12884	|	Infinite_Concentration_Potion
17226	|	Infinite_Concentration_Potion
22626	|	January_Gift_Box
22850	|	January_Gift_Box
22736	|	July_Gift_Box
22856	|	July_Gift_Box
16707	|	Jumping_Poring_Box
16708	|	Jumping_Poring_Box
22674	|	June_Gift_Box
22855	|	June_Gift_Box
16709	|	Kettle_Hat_Box
16710	|	Kettle_Hat_Box
16664	|	Leo_Scroll
17140	|	Leo_Scroll
12809	|	Level_Up_Box
22521	|	Level_Up_Box
16436	|	Libra_Crown_Box
16437	|	Libra_Crown_Box
16438	|	Libra_Diadem_Box
16439	|	Libra_Diadem_Box
570	|	Lucky_Candy
11579	|	Lucky_Candy
572	|	Lucky_Cookie
11575	|	Lucky_Cookie
13503	|	Magestic_Goat_Box
16422	|	Magestic_Goat_Box
16711	|	Magic_Eyes_Box
16712	|	Magic_Eyes_Box
22671	|	March_Gift_Box
22852	|	March_Gift_Box
22673	|	May_Gift_Box
22854	|	May_Gift_Box
16713	|	Mini_Propeller_Box
16714	|	Mini_Propeller_Box
22860	|	November_Gift_Box
22885	|	November_Gift_Box
569	|	Novice_Potion
11567	|	Novice_Potion
22859	|	October_Gift_Box
22884	|	October_Gift_Box
502	|	Orange_Potion
11569	|	Orange_Potion
539	|	Piece_Of_Cake
11581	|	Piece_of_Cake
16728	|	Pink_Beanie_Hat_Box
16729	|	Pink_Beanie_Hat_Box
14497	|	Pisces_Diadem_Box
17029	|	Pisces_Diadem_Box
2971	|	Pocket_Watch
7513	|	Pocket_Watch
678	|	Poison_Bottle
22549	|	Poison_Bottle
13205	|	Poison_Sphere
13225	|	Poison_Sphere
12941	|	Pole_Axe_Box
16431	|	Pole_Axe_Box
16715	|	Puppy_Hat_Box
16716	|	Puppy_Hat_Box
1527	|	Quadrille
16024	|	Quadrille
501	|	Red_Potion
11570	|	Red_Potion
545	|	Red_Slim_Potion
11568	|	Red_Slim_Potion
564	|	Rice_Ball
11577	|	Rice_Ball
5208	|	Rideword_Hat
18752	|	Rideword_Hat
1950	|	Rope
6687	|	Rope
1126	|	Saber
13450	|	Saber
16548	|	Sagittarius_Crown_Box
16550	|	Sagittarius_Crown_Box
16549	|	Sagittarius_Diadem_Box
16551	|	Sagittarius_Diadem_Box
16447	|	Scorpio_Crown_Box
16449	|	Scorpio_Crown_Box
4483	|	Sealed_Dracula_Card
22846	|	Sealed_Dracula_Card
22858	|	September_Gift_Box
22883	|	September_Gift_Box
16717	|	Sheep_Hat_Box
16718	|	Sheep_Hat_Box
13201	|	Silver_Bullet
13221	|	Silver_Bullet
13510	|	Solar_Sword_Box
16428	|	Solar_Sword_Box
5672	|	Southern_Cross
28201	|	Southern_Cross
16028	|	Tanos_Axe
28100	|	Tanos_Axe
16588	|	Thoughtful_Hat_Box
16589	|	Thoughtful_Hat_Box
16590	|	Thoughtful_Hat_Box
13991	|	Tiger_Mask_Box
16719	|	Tiger_Mask_Box
16720	|	Tiger_Mask_Box
13507	|	Tomahawk_Box
16429	|	Tomahawk_Box
16677	|	Universal_Catalog_Gold_Box10
16679	|	Universal_Catalog_Gold_Box10
16776	|	Universal_Catalog_Gold_Box10
16678	|	Universal_Catalog_Gold_Box50
16680	|	Universal_Catalog_Gold_Box50
16777	|	Universal_Catalog_Gold_Box50
16722	|	Vane_Hairpin_Box
16723	|	Vane_Hairpin_Box
16724	|	Vanilmirth_Hat_Box
16725	|	Vanilmirth_Hat_Box
16368	|	Virgo_Crown_Box
16398	|	Virgo_Crown_Box
16397	|	Virgo_Diadem_Box
16399	|	Virgo_Diadem_Box
16726	|	Water_Lily_Crown_Box
16727	|	Water_Lily_Crown_Box
561	|	White_Chocolate
11584	|	White_Chocolate
504	|	White_Potion
11565	|	White_Potion
547	|	White_Slim_Potion
11573	|	White_Slim_Potion
6008	|	Wood
6688	|	Wood
16738	|	Yellow_Mage_Hat_Box
16739	|	Yellow_Mage_Hat_Box
503	|	Yellow_Potion
11566	|	Yellow_Potion
546	|	Yellow_Slim_Potion
11574	|	Yellow_Slim_Potion

**Comment by cydh** [comment]
I noticed this issue (an as always, people ignore me :D)
and I was checking for those conflicted names, checked on Aegis, some items are conflicted even on Aegis. The rest, conflicted because they are "temporary" customs (we only can fix this).

So, make it 'unique' as in SQL table, must not be done for short-term problem solving. :D

**Comment by nanakiwurtz** [comment]
Currently I'm checking if there's another file which uses AegisName too, because it may break the entries. I will push a commit after I finished checking...
I'm suggesting for Devs to avoid using AegisName in the future and use ItemID as entries from now on.
