### ISSUE TITLE
addhomintimacy returns failure when no homunculus is found

### ISSUE THREAD

**Issue by jamesandrewww** [rathena/rathena#8534]
### rAthena Hash

673ef066fb261985b7be4526b444e8b735e7ed95

### Client Date

2022-04-06

### Server Mode

Pre-Renewal, Renewal

### Result

[Warning]: Script command 'addhomintimacy' returned failure.
[Debug]: Source (NPC): FAKE_NPC (invisible/not on a map)
[Debug]: Source (NPC): FAKE_NPC is located in: (null)

### Relevant Log Output

```Shell
-
```

### Expected Result

addhomintimacy should check for a homunculus in the database and proceed if one is found. It should return without logging a warning if no homunculus is found.

### How to Reproduce

1. Summon a Homunculus and then delete it if you have one
2. Use @item 100371
3. Use the item, Homun_F_Tablet

### Official Information

-

### Modifications that may affect results

-

**Comment by Daegaladh** [comment]
This is intended, except for the way we currently manage SCRIPT_CMD_FAILURE, which is already in the works.
