### ISSUE TITLE
Error PACKET_ZC_SPECIALPOPUP

### ISSUE THREAD

**Issue by Beginerxx** [rathena/rathena#8535]
### rAthena Hash

https://github.com/rathena/rathena/commit/54dc915661bdb63e52eb399cfc8b5cb15c3ad15f

### Client Date

20230906

### Server Mode

Renewal

### Result

Hi... i found some error after compile 
[PACKET_ZC_SPECIALPOPUP](https://github.com/rathena/rathena/commit/54dc915661bdb63e52eb399cfc8b5cb15c3ad15f)

![Screenshot 2024-08-03 194928](https://github.com/user-attachments/assets/781637f2-954f-4165-afcc-454e1459ebf5)

Have you guys encountered this problem?

### Relevant Log Output

```Shell
None
```

### Expected Result

None

### How to Reproduce

None

### Official Information

None

### Modifications that may affect results

None

**Comment by Daegaladh** [comment]
Cannot reproduce this, PACKET_ZC_SPECIALPOPUP is defined in packets_struct.hpp. Try using a clean rAthena.

**Comment by Beginerxx** [comment]
> Cannot reproduce this, PACKET_ZC_SPECIALPOPUP is defined in packets_struct.hpp. Try using a clean rAthena.

Thank you. [Daegaladh](https://github.com/Daegaladh)

**Comment by Beginerxx** [comment]
Yes i miss in packets_struct.hpp

```
#if PACKETVER_MAIN_NUM >= 20221005
struct PACKET_ZC_SPECIALPOPUP {
	int16 PacketType;
	int32 ppId;
} __attribute__((packed));
DEFINE_PACKET_HEADER(ZC_SPECIALPOPUP, 0x0bbe);
#endif  // PACKETVER_MAIN_NUM >= 20221005
```

I have inserted the code, still facing the same problem.
Sorry to bother you.

**Comment by Beginerxx** [comment]
I just update everything in posted. Rarely do I run into problems. When I do, I report them.

I don't know if the problem is mine or the script, but when it does, I report it. It might be a mistake.

But if I run into my own problems, I'd like to get advice on how to fix them and guidance.

Thank you for helping.
Sorry, my English is not good.

**Comment by Daegaladh** [comment]
Please use our Discord server for support
