### ISSUE TITLE
SC_STARTMARK bonus2 returned failure

### ISSUE THREAD

**Issue by AsurielRO** [rathena/rathena#8543]
### rAthena Hash

5928ad7

### Client Date

20220406

### Server Mode

Renewal

### Result

Not sure where this came from but as far as I can see this was also implemented to latest commit

ID came from: Id: 450296

```
[Error]: buildin_bonus: Invalid skill name SC_STARTMARK passed to item bonus. Skipping.
[Warning]: Script command 'bonus2' returned failure.
```

### Expected Result

--

### How to Reproduce

--

### Official Information

--

**Comment by Daegaladh** [comment]
No idea where that skill name came from, but should be SC_FATALMENACE instead
