### ISSUE TITLE
New Base and Job level 275/60

### ISSUE THREAD

**Issue by Pokye** [rathena/rathena#8545]
### Is your request related to a missing official feature?

Yes

### Describe the solution you'd like

kRO has updated its Base and Job level to 275/60, the information is in the official kRO lub.

```lua
MaxLevelTable = {
	BaseLevel = 99,
	BaseLevel3rd = 200,
	BaseLevel4th = 275,
	BaseLevelExtend2 = 200,
	BaseLevelUpperJob = 200,
	BaseLevelHomun = 275,
	BaseLevelDoram = 200,
	JobLevelNovice = 10,
	JobLevelSuperNovice = 99,
	JobLevelBase = 50,
	JobLevel2nd = 70,
	JobLevel3rd = 70,
	JobLevel4th = 60,
	JobLevelExtend2 = 70,
	JobLevelUpperJob = 70,
	JobLevelDoram = 60
}
```

**Comment by hiphop9** [comment]
![image](https://github.com/user-attachments/assets/c5dd9fe5-4662-4aa9-af5d-f734ecafae51)

**Comment by Pokye** [comment]
> ![image](https://private-user-images.githubusercontent.com/145139842/356071262-c5dd9fe5-4662-4aa9-af5d-f734ecafae51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMDMxMTksIm5iZiI6MTcyMzEwMjgxOSwicGF0aCI6Ii8xNDUxMzk4NDIvMzU2MDcxMjYyLWM1ZGQ5ZmU1LTQ2NjItNGFhOS1hZjVkLWY3MzRlY2FmYWU1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOFQwNzQwMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZTVlMGNhY2U2MzM2OGJjODM0NWQ5YTVjZjBhMDYyZGNjMDU2NmNmNTdjOWU1M2JjYmRiNmQzNThmNDBhMzk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.y00JR3gcErY665RaAT4v9_qHtt3DHggPQOeM8jcDCEo)

Please provide the official link. (it is not possible to open this image)

**Comment by hiphop9** [comment]
https://ro.gnjoy.com/news/update/View.asp?seq=288&curpage=1
![image](https://github.com/user-attachments/assets/8b54b43f-3ebc-4a95-8959-d55699c46800)
https://ro.gnjoy.com/news/update/View.asp?seq=289&curpage=1#none
![image](https://github.com/user-attachments/assets/d8c9bd0a-825a-4fc0-92ce-a2109fa1abc9)
