### ISSUE TITLE
red eruma card still not working properly

### ISSUE THREAD

**Issue by joelolopez** [rathena/rathena#855]
i already report this issue, but the effect of red eruma when using magic spells still were off so fast, you can hear a little curse sound effect then its gone in an instant, its like nothing happens..

using 20150916 client and fresh rathena

**Comment by Playtester** [comment]
Are you sure the target didn't just have high VIT?

**Comment by joelolopez** [comment]
il double check this one

**Comment by joelolopez** [comment]
my bad, its just that i tested red eruma on bradium golem thats why its ineeffective xp, working as intended <3 sorry
