### ISSUE TITLE
Allow OnInit: on function script

### ISSUE THREAD

**Issue by gidzdlcrz** [rathena/rathena#8550]
### Is your request related to a missing official feature?

No

### Describe the solution you'd like

I have been playing with my NPC scripts and i noticed that the OnInit: doesnt work on functions.

function	script	TestSystem	{
	SCRIPT HERE.

Oninit:
	/* Classes */
	.Class$[CLASS_NORMAL] = "Normal";
	.Class$[CLASS_BOSS] = "Boss";
	.Class$[CLASS_GUARDIAN] = "Guardian";
	.Class$[CLASS_BATTLEFIELD] = "Battlefield";
	.Class$[CLASS_ALL] = "All";
	end;
}

This should work.

### Describe alternatives you've considered

Well the only way i can make it possible was to use doevent which I want to avoid.

function	script	TestSystem	{
	doevent "Test#System::OnTalk";
	end;
}

-	script	Test#System	-1,{

OnTalk:
	SCRIPT HERE.

Oninit:
	/* Classes */
	.Class$[CLASS_NORMAL] = "Normal";
	.Class$[CLASS_BOSS] = "Boss";
	.Class$[CLASS_GUARDIAN] = "Guardian";
	.Class$[CLASS_BATTLEFIELD] = "Battlefield";
	.Class$[CLASS_ALL] = "All";
	end;
}

**Comment by Daegaladh** [comment]
How would you trigger a NPC event that is not attached to any NPC, that doesn't make any sense

**Comment by Atemo** [comment]
Additional Information
https://github.com/rathena/rathena/blob/master/doc/script_commands.txt#L393
```
function%TAB%script%TAB%<function name>%TAB%{<code>}

...
It's not possible to call the code in this object by
anything other than the 'callfunc' script command.
```
