### ISSUE TITLE
RG_CLOSECONFINE should not work against Boss monsters

### ISSUE THREAD

**Issue by jamesandrewww** [rathena/rathena#8555]
### rAthena Hash

673ef066fb261985b7be4526b444e8b735e7ed95

### Client Date

2022-04-06

### Server Mode

Pre-Renewal, Renewal

### Result

RG_CLOSECONFINE currently works on Boss monsters which is unintended

### Expected Result

	case RG_CLOSECONFINE:
		if (dstmd && !status_has_mode(tstatus, MD_STATUSIMMUNE)) {
			clif_skill_nodamage(src, bl, skill_id, skill_lv,
				sc_start4(src, bl, type, 100, skill_lv, src->id, 0, 0, skill_get_time(skill_id, skill_lv)));
		}
		break;

### How to Reproduce

Use the RG_CLOSECONFINE skill on an MVP or Boss monster

### Official Information

https://ro.gnjoy.com/guide/runemidgarts/skillview.asp?lineSeq=5&skillid=1005
https://www.divine-pride.net/database/skill/1005/close-confine

**Comment by aleos89** [comment]
Which monsters are you testing this again? All MVP/Boss monsters should have the MD_STATUS_IMMUNE mode applied to them.

**Comment by jamesandrewww** [comment]
Eddga

https://github.com/user-attachments/assets/ad40cabf-58b6-48fa-9a86-8487b49cd8a2

**Comment by aleos89** [comment]
Ah, sorry I totally misread your initial report. I thought you were stating the MD_STATUS_IMMUNE check wasn't working!
