### ISSUE TITLE
@diguise and @hide

### ISSUE THREAD

**Issue by joelolopez** [rathena/rathena#856]
how to produce
-disguise as poring
-`@hide`
-take a walk 
-`@hide` to unhide
-result poring sprite remains at the same spot before you take a walk

<img  src='https://z-1-scontent-hkg3-1.xx.fbcdn.net/hphotos-xap1/v/t34.0-12/12459727_10204224928663326_1553106418_n.jpg?oh=a0fb6ed48be88876fcd06629b41b8abe&oe=5684E5A8' height=480 width=640>

**Comment by anacondaqq** [comment]
Can't confirm on 2012-04-10 exe, packet_ver: 30. Packet obfusication on.
Hash: 118fa28ae9ac832e89968ce214c27b17d780027d

It's seems related only to latest game clients.

**Comment by joelolopez** [comment]
tested in 2014,2015, same issue

**Comment by RagnarokNova** [comment]
Confirmed with 2013-12-23, but the visual bug is fixed by walking a single cell or using @refresh.
