### ISSUE TITLE
2 Gray_W_Robe exist in quests_18.yml

### ISSUE THREAD

**Issue by reunite-ro** [rathena/rathena#8561]
### rAthena Hash

https://github.com/rathena/rathena/commit/a9e51c09cc28cd087fa423242f05bc7e5498c8a4

### Client Date

20220406

### Server Mode

Renewal

### Result

Item: Gray_W_Robe

https://github.com/rathena/rathena/blob/a9e51c09cc28cd087fa423242f05bc7e5498c8a4/npc/re/merchants/barters/quests_18.yml#L58C9-L58C26

and

https://github.com/rathena/rathena/blob/a9e51c09cc28cd087fa423242f05bc7e5498c8a4/npc/re/merchants/barters/quests_18.yml#L94

### Expected Result

I dont know if its should be just one but maybe someone can check it.

### How to Reproduce

Run the server renewal and access the NPC barter

### Official Information

I dont have any info about this, maybe someone can check it in kRO

**Comment by Beginerxx** [comment]
I think it might be a repeat of Index: 7

**Comment by llchrisll** [comment]
kRo at some point made it possible to use "duplicate" entries, which was not the case when they implemented that Enchant UI, later on they change it, which causes issues for older clients.
In my project files there 2 version of it, one without "AddItem_Duplicate" (function used by newer clients) and one with.
[Old Version](https://github.com/llchrisll/ROenglishRE/blob/master/Translation/Compatibility/2021-10-28/data/luafiles514/lua%20files/Enchant/EnchantList.lub)
[New Version](https://github.com/llchrisll/ROenglishRE/blob/master/Translation/Compatibility/2023-09-20/data/luafiles514/lua%20files/Enchant/EnchantList.lub)

The new version breaks ofc for older clients the UI completely.

**Comment by Beginerxx** [comment]
```
#      - Index: 7
#        Item: Gray_W_Robe
#        RequiredItems:
#          - Index: 0
#            Item: Ep18_Amethyst_Fragment
#            Amount: 350
```

![Screenshot 2024-08-17 003644](https://github.com/user-attachments/assets/45a44774-c993-4ad0-a444-2a3d43c6424a)

**Comment by reunite-ro** [comment]
By the way, the scripts also seems need some correction. such as this case 2.

		switch( select( "Armor", "Coat", "Shoes", "Right(R) Accessory", "Left(L) Accessory" ) ) {
		case 1:
			mes "[Emmet]";
			mes "You're enchanting the armor, I see.";
			close2;
			item_enchant(1);
			end;
		case 2:
			mes "[Emmet]";
			mes "You're enchanting the footwear, I see.";
			close2;
			item_enchant(2);
			end;

Selection is 'Coat' but the mes is about footwear.

**Comment by monbazko** [comment]
Also Gray_W_Necklace is missing. was prolly a typo error before converting into yml.
entry 6 Pendant
7 Ring
8 Earring
9 Necklace
