### ISSUE TITLE
Rolling Cutter skill [Glt. Cross] Cycle break

### ISSUE THREAD

**Issue by Brotherhoodb** [rathena/rathena#8576]
### rAthena Hash

f3c8c70c810788f774ec39bf1cd8570488182742

### Client Date

2022-04-06

### Server Mode

Renewal

### Result

Rolling Cutter skill should continue until the user releases the skill button or SP runs out, but the cycle breaks after the first iteration.

### Expected Result

What a skill continued while press the button

### How to Reproduce

.

### Official Information

.

**Comment by Brotherhoodb** [comment]
Any one can help with this issue?

**Comment by LadyNanuia** [comment]
You need a client edit for this, but even if you get one, the whole thing is broken in rA, i got it working on my server after a lot of changes and a custom client diff (tried posting a gif of it here but yea)

so the rA "implement" is broken.

**Comment by Brotherhoodb** [comment]
> You need a client edit for this, but even if you get one, the whole thing is broken in rA, i got it working on my server after a lot of changes and a custom client diff (tried posting a gif of it here but yea)
> 
> so the rA "implement" is broken.

Nope its not true. 
Just minimal replace strings in skill.cpp :

clif_parse_skill_toid(sd, sd->skill_keep_using.skill_id, sd->skill_keep_using.level, sd->skill_keep_using.target);
sd->skill_keep_using.tid = INVALID_TIMER;

to

sd->skill_keep_using.tid = INVALID_TIMER;
clif_parse_skill_toid(sd, sd->skill_keep_using.skill_id, sd->skill_keep_using.level, sd->skill_keep_using.target);

**Comment by LadyNanuia** [comment]
> > You need a client edit for this, but even if you get one, the whole thing is broken in rA, i got it working on my server after a lot of changes and a custom client diff (tried posting a gif of it here but yea)
> > so the rA "implement" is broken.
> 
> Nope its not true. Just minimal replace strings in skill.cpp :
> 
> clif_parse_skill_toid(sd, sd->skill_keep_using.skill_id, sd->skill_keep_using.level, sd->skill_keep_using.target); sd->skill_keep_using.tid = INVALID_TIMER;
> 
> to
> 
> sd->skill_keep_using.tid = INVALID_TIMER; clif_parse_skill_toid(sd, sd->skill_keep_using.skill_id, sd->skill_keep_using.level, sd->skill_keep_using.target);

You're correct, i remember now that this solution was needed to use this feature on more skills than Rolling cutter, my mistake
