### ISSUE TITLE
Can't find source file novice_skill

### ISSUE THREAD

**Issue by Dark8008** [rathena/rathena#858]
![image](https://cloud.githubusercontent.com/assets/14345362/12060885/5943f300-afab-11e5-8135-1522ae613a63.png)

I use:
pre-renewal
rathena latest version
2014-10-22 client !

**Comment by Lemongrass3110** [comment]
@Atemo did you intend to move the whole npc file? If yes, please do a follow up.

**Comment by Atemo** [comment]
I still found the NPC of this file on iRo renewal and on divine pride but I can't find them on kRo lua navi.. I will let them enable for renewal too until we get more info.
