### ISSUE TITLE
Super Novice Spirit Bug

### ISSUE THREAD

**Issue by Melk3000** [rathena/rathena#8604]
### rAthena Hash

lastest

### Client Date

20220406

### Server Mode

Renewal

### Result

Super Novice Spirit skill doesn't allow user to wear equipment higher than their base level, Super novice sould be able to equip all Headgears and all level 4 daggers, One Handed sword, axe, mace and staff regardless of base level requirements.

### Expected Result

With Spirit Super novice should be able to equip all Headgears and all level 4 daggers, One Handed sword, axe, mace and staff regardless of base level requirements.

### How to Reproduce

Use Skill Spirit Super Novice and Try wear headger or weapon with level requirement higher than 99.

### Official Information

https://www.divine-pride.net/database/skill/451

**Comment by Beginerxx** [comment]
Found here watch to till the end.

https://www.youtube.com/watch?v=Q-tIuaFDoeg

**Comment by Playtester** [comment]
What base level were you when you tested this?

**Comment by Melk3000** [comment]
Level 99 with As-nail [0]   [One Hand]   Item ID# 13069

**Comment by Playtester** [comment]
Can confirm this issue.

There is also another bug. You should be able to equip helmet from level 90 onwards (currently 91) and level 4 weapons from 96 onwards (currently 97).

**Comment by Playtester** [comment]
Some more things we found:

1. Link also overrides all other checks (for example can equip weapon/helm while stripped)

2. The level check still happens before the strip checks (get level too low message on renewal).

In other words the check order needs to be:
Spirit Pass -> Level Fail -> Other Fail

**Comment by Beginerxx** [comment]
```
Super Novices at Base Level 90
and above can any headgear regardless of
location, and at Base Level 96 and above, they
can equip certain Level 4 Weapons, 
```
It does not mean that you can equip higher level equipment. 
You must equip equipment at the level that your character level can equip.

**Comment by Daegaladh** [comment]
> ```
> Super Novices at Base Level 90
> and above can any headgear regardless of
> location, and at Base Level 96 and above, they
> can equip certain Level 4 Weapons, 
> ```
> 
> It does not mean that you can equip higher level equipment. You must equip equipment at the level that your character level can equip.
> 
> If base level 96 and weapon requirement level 100 you can't equip it.

Yes with link they can, even broken weapons and weapons for other classes.

**Comment by Beginerxxx** [comment]
> ```
> Super Novices at Base Level 90
> and above can any headgear regardless of
> location, and at Base Level 96 and above, they
> can equip certain Level 4 Weapons, 
> ```
> 
> It does not mean that you can equip higher level equipment. You must equip equipment at the level that your character level can equip.
> 
> If base level 96 and weapon requirement level 100 you can't equip it.

That is!!!!!!!!!!!!!!!!!!!!!
