### ISSUE TITLE
Latest repo does not compile

### ISSUE THREAD

**Issue by latheesan-k** [rathena/rathena#861]
I get the following error:

	{standard input}: Assembler messages:
	{standard input}:104078: Warning: end of file not at end of a line; newline inserted
	{standard input}:106108: Error: number of operands mismatch for `jmp'
	{standard input}: Error: open CFI at the end of file; missing .cfi_endproc directive
	gcc: internal compiler error: Killed (program cc1)
	Please submit a full bug report,
	with preprocessed source if appropriate.
	See <http://bugzilla.redhat.com/bugzilla> for instructions.
	make[1]: *** [obj/skill.o] Error 4
	make[1]: Leaving directory `/home/host/rAthena/src/map'
	make: *** [map] Error 2

OS: CentOS 7 x64

Using: MariaDB 10.1 with this configure flags : 
`./configure --enable-64bit --with-MYSQL_LIBS=/usr/lib64/libmysqlclient.so;`

**Comment by anacondaqq** [comment]
Sorry, but there is not enough information. It's seems you have broken libraries / compiller, then problems with the server. Can you please show full output, and add extra information about compiller.
Some time ago i've used mariadb, but did't found any good part of it at live server, only few headcache issues with libraries.

**Comment by latheesan-k** [comment]
Yea it turned out to be a server issue. I rebooted the machine and the error went away. Closing this...
