### ISSUE TITLE
657 Berserk Potion usable by Sorcerer?

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#862]
Item ID 657 Berserk Potion

Maybe it's just the item description which is wrong.
But shouldn't Berserk Potion be usable by Sorcerer?

**Comment by nanakiwurtz** [comment]
Sorcerer is from Wizard?

**Comment by Playtester** [comment]
I think from Sage.

Wizard goes Warlock.

**Comment by nanakiwurtz** [comment]
Original kRO description:
> 온몸의 피를 끓게하여 광전사의 상태로 만드는 대단한 물약. 복용하면 공격속도가 상승한다. 85레벨 이상의 캐릭터만 사용할 수 있으며 검사계열 / 로그 / 마법사 / 위저드 / 상인계열 / 태권 / 권성 / 소울링커 / 건너 / 리벨리온만이 사용가능하다.
무게 : 20

It only works for Wizards, not Sage. So this report is invalid.
