### ISSUE TITLE
guild name is not loaded on login and the guild leader is offline

### ISSUE THREAD

**Issue by AoShinRO** [rathena/rathena#8643]
### rAthena Hash

d280915

### Client Date

20221116

### Server Mode

Renewal

### Result

guild name is not loaded if you login and the guild leader is offline
anyone can confirm other clients?

https://github.com/user-attachments/assets/72e09821-f16c-4ee3-b5af-582c8599f252

HD video -> https://youtu.be/PesqTLpa9Gw

### Expected Result

guildname need to be showed

### How to Reproduce

just login with an guild member account without online guild leader

### Official Information

This probably shouldn't depend on the online leader

**Comment by AoShinRO** [comment]
this did not happen in the 2023 emulator

**Comment by Toshiro90** [comment]
Had this behaviour for more than 3 years on my local test server with various client versions.
I was able to reproduce this problem and it is happening in the special case when the map server did not receive (nor requested) the guild data yet and you're logging in with any guild member (excluding the leader) for the first time after server restart. Upon receiving the guild data intends to send the names (char/party/guild/rank) of any guild member (with`clif_name_area`), however only the guild leader's map_session_data is updated with the guild reference _before_ sending.
