### ISSUE TITLE
Guild Position List is broken showing other things

### ISSUE THREAD

**Issue by thanna** [rathena/rathena#8648]
### rAthena Hash

f3d1541

### Client Date

2022-04-06

### Server Mode

Pre-Renewal, Renewal

### Result

I checked map and char server for error but no error shows. I also check my guild position table and it seems fine.

More Info: Tested this before the f3d1541 commit and its working fine

![guildposition](https://github.com/user-attachments/assets/313e5197-01c6-4455-bae0-9e6e15f84fed)

### Expected Result

Just guild positions from Guild Master to Position 19

### How to Reproduce

Just create a guild or if you have a existing guild just open Guild Window

### Official Information

NA

**Comment by laziem** [comment]
![image](https://github.com/user-attachments/assets/05581f0f-26b4-49b2-967f-848dd5d6679b)
confirm..

**Comment by skstrife** [comment]
The problem exists, I confirm. @AoShinRO

**Comment by AoShinRO** [comment]
but the https://github.com/rathena/rathena/commit/f3d1541e44bfabc3604f3b9388063bcf24bfcfe2 is not  related  to  guildposition oO, packet from guild position is in PR yet, i'll check

**Comment by skstrife** [comment]
@AoShinRO It could be related to "Converted ZC_POSITION_INFO to struct (#8629)"

**Comment by AoShinRO** [comment]
yep, i'll commit packed working again :/

**Comment by skstrife** [comment]
@AoShinRO Thanks!

**Comment by thanna** [comment]
@AoShinRO thank you.
