### ISSUE TITLE
skill_require_db

### ISSUE THREAD

**Issue by bgamez23** [rathena/rathena#865]
using pre-re i got this issue.
[Error]: sv_readdb: Insufficient columns in line 886 of "db/pre-re/skill_require_db.txt" (found 33, need at least 34).

before it was change the previous version of this is 

//2544,0,0,1,0,0,0,99,0,0,none,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0	

but not 
2544,0,0,40,0,0,0,99,0,0,none,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0	

the ,0 has been deleted

**Comment by admkakaroto** [comment]
https://github.com/rathena/rathena/pull/864
