### ISSUE TITLE
WL_CHAINLIGHTNING animation bug

### ISSUE THREAD

**Issue by panko11** [rathena/rathena#866]
Animation bug.
Rathena vs bRO = https://www.youtube.com/watch?v=JgMefiTQY_s
iRO = https://www.youtube.com/watch?v=WCXx_JbjFXI

Version: 22a9a74d0c97e8ef7b4e98807275405ffc3b0318
Client : 20130807
model : renewal

**Comment by Lemongrass3110** [comment]
From what I've observed it might be related to this:
https://github.com/rathena/rathena/blob/master/src/map/clif.c#L5485
Judging from the user's report it might have been even before 20131223. Also I could not fix the issue by adjusting the damage type to any known value. We might even be sending an outdated packet.

**Comment by Lemongrass3110** [comment]
Added "status:needs official info", because we might need a packet capture from kRO for this one.

**Comment by panko11** [comment]
kRO capture: https://www.youtube.com/watch?v=V7o5jYw2LA4

**Comment by Lemongrass3110** [comment]
@panko11 thanks for the video, but we need a packet capture(which packets get sent from the server to the client).

**Comment by panko11** [comment]
The .rec in the case?

**Comment by panko11** [comment]
what do you need? A recording tool for rec play?

**Comment by anacondaqq** [comment]
@panko11 no, they need a raw packet between official server and the game-client where all information. With this packet our dear dev.s can make something good with rAthena (make some official client features avaiable)

**Comment by MrAntares** [comment]
Same issue with Severe Rainstorm.

**Comment by cydh** [comment]
well well, it just because this code guys. /swt
````
		case WL_CHAINLIGHTNING_ATK:
			dmg.dmotion = clif_skill_damage(src,bl,tick,dmg.amotion,dmg.dmotion,damage,1,WL_CHAINLIGHTNING,-2,6);
			break;
````
the chain damage is forced to use `WL_CHAINLIGHTNING`'s -put your hands up!- effect. It must be `WL_CHAINLIGHTNING_ATK`.

**Comment by cydh** [comment]
well well, it just because this code guys. /swt
````
		case WL_CHAINLIGHTNING_ATK:
			dmg.dmotion = clif_skill_damage(src,bl,tick,dmg.amotion,dmg.dmotion,damage,1,WL_CHAINLIGHTNING,-2,6);
			break;
````
the chain damage is forced to use `WL_CHAINLIGHTNING`'s -put your hands up!- effect. It must be `WL_CHAINLIGHTNING_ATK`.

**Comment by Lemongrass3110** [comment]
@cydh What about the others @MrAntares stated?

**Comment by Playtester** [comment]
My memory might failing me, but I thought I tested Waterball thoroughly and already implemented it to work as official. I certainly couldn't move properly while casting and had lots of position lag on aegis.

**Comment by MrAntares** [comment]
I'd call for a toggleable "unofficial fix" :)

**Comment by Playtester** [comment]
Note that there is no attack animation for waterball either. But the waterball effect itself gives a walk delay (kinda like Sonic Blow).

Also quite likely that the renewal skills have a better implementation.
