### ISSUE TITLE
Finger Offensive damage formula

### ISSUE THREAD

**Issue by Haydrich** [rathena/rathena#8667]
### rAthena Hash

master

### Client Date

20240904

### Server Mode

Renewal

### Result

I've tested the damage of the skill in kRO and rA
Sura Lv 178/61
Skills:
![image](https://github.com/user-attachments/assets/4e020f72-e8a1-4ca7-bbbc-2741d306f0bc)
![image](https://github.com/user-attachments/assets/00b53396-6715-4a36-b94c-912456c39b57)
![image](https://github.com/user-attachments/assets/f3779525-c988-42a0-b2c8-48203ccaa405)
Status:
![image](https://github.com/user-attachments/assets/91cc232b-0e3b-4dbe-b5fa-2ffaeacda077)

Damage in kRO (Full Gears)
![image](https://github.com/user-attachments/assets/daff02e0-2511-47be-9ed5-502d1ade5347)
Damage in rA (Full Gears)
![image](https://github.com/user-attachments/assets/7a162ee6-d7a5-4922-a19c-f4ba4335f7fd)

________________________________________________________________________

Damage in kRO (Bare Hands)
![image](https://github.com/user-attachments/assets/c5b669bd-6986-400b-b03a-9e3102f55946)
Damage in rA (Bare Hands)
![image](https://github.com/user-attachments/assets/968e8a74-a20e-420e-ad01-45821cbafad5)

### Expected Result

Skill should deals lower than this damage

### How to Reproduce

Test Finger Offensive inside rA

### Official Information

Provided

**Comment by Playtester** [comment]
Changing number of hits from 5 to -5 seems to result in the correct damage, if we also add the +9 STR bonus for job level 61.

But it creates a new question: What is the damage and number of hits if you use it with less than 5 Spirit Spheres?

We also need the job bonus for level 61-70 for 3rd jobs still.

**Comment by Playtester** [comment]
On kRO it hits plants, so it can't be -5 hits, hmm.

**Comment by Playtester** [comment]
kRO vs Barricade (medium)

5 Sphere > 1330x5
4 Sphere > 1321x5
3 Sphere > 1311x5
2 Sphere > 1302x5
1 Sphere > 1292x5

I think the skills works like Triple Attack where it multiplies damage only on plant mode.

Also the sphere that is used still is added to the damage.
