### ISSUE TITLE
Wrong info script id item: 13414

### ISSUE THREAD

**Issue by Dark8008** [rathena/rathena#867]
Iro offical:
http://db.irowiki.org/db/item-info/13414/

ratemyserver:
http://ratemyserver.net/index.php?iname=Elemental+Sword&page=item_db&quick=1&isearch=Search

Script now follow ratemyserver, please check sir !

version: latest
client : 20141022
model : pre-renewal

**Comment by Playtester** [comment]
What exactly is wrong on it?

Only thing I noticed is that those 10000 should actually be 1000, but it should still work the same.

**Comment by nanakiwurtz** [comment]
@Dark8008 : Never ever compare item script to RMS :)

**Comment by Dark8008** [comment]
Thank you,
VuaRok!

**Comment by Dark8008** [comment]
Please fix for Pre-renewal too sir !
