### ISSUE TITLE
Renewal calculation order of magic attack is incorrect

### ISSUE THREAD

**Issue by Atemo** [rathena/rathena#8689]
### rAthena Hash

https://github.com/rathena/rathena/commit/2688ed26e27d50b986b0cbb52954442369510045

### Client Date

2022-03-30

### Server Mode

Renewal

### Result

The test is performed using a character with the following stats :

**BaseLevel** 262
**INT** 130+15
**DEX** 1+8
**LUK** 100+4
**SPL** 110+14
**S.MATK** 42

On the following target :

**Dummy (Water Lv1)**	ID: [21078](https://www.divine-pride.net/database/monster/21078)
**Level** 100
**INT** 0
**Hard Mdef** = 0
Target Soft Mdef (**Mdef2**) = `(float)(status->int_ + level) / 4` = 25

From our formula the Matk minimum of the character is
```
status_base_matk_min : status->int_ + (status->int_ / 2) + (status->dex / 5) + (status->luk / 3) + (level / 4) + 5 * status->spl;
status_base_matk_min : 937
```

The skill used is AG_SOUL_VC_STRIKE, which we can deduce the `skillratio`
```
AG_SOUL_VC_STRIKE level 5: skillratio = (300 * skill_lv + 3 * sstatus->spl) * BaseLevel / 100;
AG_SOUL_VC_STRIKE level 5: skillratio = 4904
```

That being said, in our example the damage calculation used on rAthena is in this order :
```
damage = status_base_matk_min;
damage = damage + damage * sstatus->smatk / 100;
damage = damage * skillratio / 100;
damage = damage + damage * item_script_bonus / 100;		(simplified formula for single bonus)
damage = damage - Mdef2;
```

However due to rounding in each formula the order is important. The damage value is currently different from the official value when equipping an item with a simple bonus.

### Expected Result

Same damage on rAthena and official server.

### How to Reproduce

See below.

### Official Information

```
Equip                           Official server         RA
None                            65198                   65198	
Grace ring (490020)             71671                   71720       (Increases magical damage dealt to All property monsters by 10%)
Grace manteau+9 (480019)        71671                   71720       (Increases All property magical damage by 10%)
Costume set (29516+311356)      74957                   74981       (Increases All property magical damage by 15%)
```

Damage from calcul
No equipment :
```
damage = status_base_matk_min = 937
damage = damage + damage * sstatus->smatk / 100 = 937 + 937 * 42 / 100 = 1330
damage = damage * skillratio / 100 = 1330 * 4904 / 100 = 65223
damage = damage - Mdef2 = 65223 - 25 = 65198
```
Grace ring (490020) :
```
damage = status_base_matk_min = 937
damage = damage + damage * sstatus->smatk / 100 = 937 + 937 * 42 / 100 = 1330
damage = damage * skillratio / 100 = 1330 * 4904 / 100 = 65223
damage = damage + damage * item_script_bonus / 100 = 65223 + 65223 * 10 / 100 = 71745
damage = damage - Mdef2 = 71745 - 25 = 71720
```
etc..

By changing the order of the formula for Grace ring (490020) we find the official values :
```
damage = status_base_matk_min = 937
damage = damage + damage * item_script_bonus / 100 = 937 + 937 * 10 / 100 = 1030
damage = damage + damage * sstatus->smatk / 100 = 1030 + 1030 * 42 / 100 = 1462
damage = damage * skillratio / 100 = 1462 * 4904 / 100 = 71696
damage = damage - Mdef2 = 71696 - 25 = 71671
```
and for "Costume set"
```
damage = status_base_matk_min = 937
damage = damage + damage * item_script_bonus / 100 = 937 + 937 * 15 / 100 = 1077
damage = damage + damage * sstatus->smatk / 100 = 1077 + 1077 * 42 / 100 = 1529
damage = damage * skillratio / 100 = 1529 * 4904 / 100 = 74982
damage = damage - Mdef2 = 74982 - 25 = 74957
```

**Comment by Playtester** [comment]
Related: https://github.com/rathena/rathena/issues/8381 https://github.com/rathena/rathena/commit/98eaf85a905d50ba9a29c9ab35383953e83c8668#diff-e9da83c5add2e830d737c917e5a40115323bdd83189435c7bbc32534a7717213R8736
