### ISSUE TITLE
WL_WHITEIMPRISON

### ISSUE THREAD

**Issue by panko11** [rathena/rathena#869]
The skill is canceling the cast of buff skills. And that was not to be.

Example

I'm cast AB_CLEMENTIA and in the middle of casting I'm stuck in WL_WHITEIMPRISON at the end of the casting AB_CLEMENTIA it is to give the normally buff.
But in rAthena to suffer it the skill to cast is canceled and has no effect

In the Brazilian server is the skill to buff it finishes casting normally now if the skill is damage it has no effect

Version: 22a9a74
Client : 20130807
model : renewal

**Comment by aleos89** [comment]
It would be nice to confirm the effect on kRO too.

**Comment by aleos89** [comment]
Traced this down to:
```
		if (skill_id != RK_REFRESH && sc->opt1 && !(sc->opt1 == OPT1_CRYSTALIZE && src->type == BL_MOB) && sc->opt1 != OPT1_BURNING && skill_id != SR_GENTLETOUCH_CURE) { // Stuned/Frozen/etc
			if (flag != 1) // Can't cast, casted stuff can't damage.
				return false;
			if (!(skill_get_inf(skill_id)&INF_GROUND_SKILL)) 
				return false; // Targetted spells can't come off.
		}
```
Essentially it's failing if this skill isn't a ground-target skill. Need to test official effect of OPT1 stuff.

**Comment by Playtester** [comment]
All OPT1 status changes work like this:
1. Casting is NOT cancelled when they activate (but damage stops casting)
2. When you have a damage skill going and you suffer an OPT1 status change, the skill won't deal damage.
3. When the OPT1 status change ends and the damage skill is still going, it will start doing damage.
4. You can still heal/buff when an OPT1 status change is active. Only damage is blocked. It is independent of skill, e.g. Sanctuary can heal players even if the caster suffers an OPT1 status change but if cannot hurt Undead standing in it. It's exactly the same behavior that Gravitational Field has for the caster.
