### ISSUE TITLE
Invalid group id for item 618 Worn Out Scroll

### ISSUE THREAD

**Issue by anacondaqq** [rathena/rathena#870]
revision: 9632d2a217794bddc25bd81dd358192b1905466c
mode: pre-re
packet_ver: 30
client date: 2012-04-10

Bug:
====

```
itemdb_get_randgroupitem: Invalid group id 5
```

The problem related to: IG_ScrollBox

How reproduce:
=============
1. Create item @item 618
2. Use this item
3. You will get in console this error.

**Comment by Playtester** [comment]
Where does that even come from? All the sources I could find just say that Worn_Out_Scroll does nothing.

**Comment by anacondaqq** [comment]
@Playtester i don't know. At Official servers this item do nothing. But usable.

**Comment by Playtester** [comment]
So basically the script should just be removed from the item.

618,Worn_Out_Scroll,Worn Out Scroll,2,50,,20,,,,,0xFFFFFFFF,7,2,,,,,,{ getrandgroupitem(IG_ScrollBox),1; },{},{}

Change to:

618,Worn_Out_Scroll,Worn Out Scroll,2,50,,20,,,,,0xFFFFFFFF,7,2,,,,,,{},{},{}

**Comment by nanakiwurtz** [comment]
Fixed in 4c6cf46

**Comment by Playtester** [comment]
Wrong issue link, you put the item ID instead of the issue number. XD
