### ISSUE TITLE
Rekenber Job Quest quest bugs. (lighthalzen quests)

### ISSUE THREAD

**Issue by anacondaqq** [rathena/rathena#871]
1. [Error]: quest_change: Character 150000 already has quest 12010.
I have this error, when i back from (einbroch 54 52). Laboratory Guard to Young Man (Kazien) (lhz_in01 174 258)

2. Then, in the same quest, when you come to Scamp you will get error:
> [Error]: quest_change: Character 150000 doesn't have quest 12012.

3. Then, when you back to Kazien, you will get next error:
> [Error]: quest_change: quest 5006 not found in DB.

4. Then, in step, after killing 3 mobsters, and when you need back to Young Man, after receiving experience you will get error:
> [05/Jan 05:21][Error]: quest_update_status: Character 150000 doesn't have quest
12013.

So finally, how reproduce:
====================
Do this quest step by step and check map-server errors, and you will be surpriced of many different errors described here above:)

http://irowiki.org/wiki/Shadow_Quest_(Rekenber_Job_Quest)

Revision: 1abb02c840cdeb6987a5b1bb1ca8e88a46cfb63b
mode: pre-re

**Comment by Lemongrass3110** [comment]
I fixed the first error by changing this line:
https://github.com/rathena/rathena/blob/master/npc/quests/quests_lighthalzen.txt#L10798
To
```
changequest 12010,12009;
```

Could you please also try this and see if you still receive the other errors? They could be errors caused by the other one.

Regarding the issue for missing quest 5006, this one is really missing in quest_db but we use it in scripts. You also should get other errors for example 5005, which is also missing.

@Atemo could you help me out on this one?

**Comment by Lemongrass3110** [comment]
Seems like those errors existed since 0202126 from @euphyy back in august 2013.
He added quest support to lighthalzen and many other cities back then, but the quest_db entries for 5005, 5006 etc were also missing back then.

**Comment by Atemo** [comment]
I will push a fix about this issue. I wonder if aegis force to give the quest even if the player doesn't have the prerequis with changequest since there are a lot of mistake with that, like
> changequest 12001,12002;// player get 12002 even if he doesn't have 12001

**Comment by Atemo** [comment]
>the quest_db entries for 5005, 5006 etc were also missing back then.

I just disabled the chanquest line on the script from now

**Comment by Lemongrass3110** [comment]
Great job @Atemo! :)

@anacondaqq if you have any more issues like that, please consider upgrading to 72fe7f9 to make it easier for us to find out whats wrong. Sample output after that commit:
```
[Error]: quest_change: Character 150000 already has quest 12011.
[Debug]: Source (NPC): Young Man#reken at lhz_in01 (174,258)
[Debug]: Function: changequest (2 parameters):
[Debug]: Data: number value=12008
[Debug]: Data: number value=12011
```

**Comment by anacondaqq** [comment]
awesome job @Lemongrass3110 thank you very much, your fix will give a lot of transparenty about errors with quets)
