### ISSUE TITLE
Emergency Call Bug

### ISSUE THREAD

**Issue by lunamoonf** [rathena/rathena#8736]
### rAthena Hash

Latest Git

### Client Date

20220406

### Server Mode

Pre-Renewal

### Result

After Using Emergency call the player will summon or being called after that auto disconnect from the server
![image](https://github.com/user-attachments/assets/9e302627-ebec-4c1b-af0f-f0dd77e1173d)

### Relevant Log Output

```Shell
After Using Emergency call the player will summon or being called after that auto disconnect from the server
```

### Expected Result

Shout not be Disconnected

### How to Reproduce

Use Emergency Call

### Official Information

N/A

### Modifications that may affect results

N/A

**Comment by reunite-ro** [comment]
This most probably related to https://github.com/rathena/rathena/issues/8676

**Comment by Lemongrass3110** [comment]
As @Toshiro90 mentioned correctly, you use the wrong PACKETVER.
