### ISSUE TITLE
@mute & @unmute bug when gm and player is near

### ISSUE THREAD

**Issue by thanna** [rathena/rathena#8739]
### rAthena Hash

a37f443

### Client Date

2022-04-06

### Server Mode

Pre-Renewal, Renewal

### Result

When using @mute & @unmute command and the target character is on screen, the GM screen will freeze and will get disconnected after a few seconds. the muted/unmuted player is not affected by this.

This problem dont happen if the player is not within the GM accounts screen or if both is on different maps

Edit:
Tested it with the right click functionality for GM account. same results. it does freeze and then gets disconnected.

### Relevant Log Output

```Shell
no error output on the servers.
```

### Expected Result

screen should not freeze or get disconnected

### How to Reproduce

1. get a gm account and a dummy account, be sure that both close together (sharing screen)
2. use @mute 5 <character name> or if muted use @unmute <character name>

### Official Information

NA

**Comment by elanosilveira** [comment]
I tested with client 2024, and indeed it disconnects the GM who used the mute command. Confirmed.

**Comment by GustavoMarra** [comment]
There is also an error in the refine UI system when you use da crash with "gepard" error and the problem is in this function of the package
![image](https://github.com/user-attachments/assets/2997f8f5-2790-4173-a5de-b96726f79a6e)
