### ISSUE TITLE
skill_unit_move_sub: Reached limit of unit objects per cell! (skill_id: 10009) (guild skills)

### ISSUE THREAD

**Issue by anacondaqq** [rathena/rathena#874]
Problem:
------------
i've noticed some errors in map-server log.
I do not know how reproduce them.
I do not have custom source mods, and i have latest pre-re revision.

Errors:
=====
```
skill_unit_move_sub: Reached limit of unit objects per cell! (skill_id: 10009)
	skill_unit_move_sub: Reached limit of unit objects per cell! (skill_id: 10008)
	skill_unit_move_sub: Reached limit of unit objects per cell! (skill_id: 10007)
	skill_unit_move_sub: Reached limit of unit objects per cell! (skill_id: 10006)
	skill_unit_move_sub: Reached limit of unit objects per cell! (skill_id: 10009)
	skill_unit_move_sub: Reached limit of unit objects per cell! (skill_id: 10008)
	skill_unit_move_sub: Reached limit of unit objects per cell! (skill_id: 10007)
	skill_unit_move_sub: Reached limit of unit objects per cell! (skill_id: 10006)
	skill_unit_move_sub: Reached limit of unit objects per cell! (skill_id: 10006)
	skill_unit_move_sub: Reached limit of unit objects per cell! (skill_id: 10009)
	skill_unit_move_sub: Reached limit of unit objects per cell! (skill_id: 10009)
	skill_unit_move_sub: Reached limit of unit objects per cell! (skill_id: 10009)
	skill_unit_move_sub: Reached limit of unit objects per cell! (skill_id: 10009)
```

Technical details:
==============
revision: 1abb02c840cdeb6987a5b1bb1ca8e88a46cfb63b
mode: pre-re
packet_ver: 30
client date: 2012-04-10

Extra information:
==============
core.h
>> /// #define OFFICIAL_WALKPATH
>> #define PACKET_OBFUSCATION
>> /// #define CELL_NOSTACK

**Comment by lighta** [comment]
hmm so skill_unit_temp is full, I wonder if it cleared enough. (like we have missed to clear him before call him back). But that seem not the case or you'll have way more errors. (worth checking anyway).
Assuming all is correct that would mean you have 20 different skill_unit that want to be performed. Could be idk that would be quite a lot of buff. Perhaps if you display what in the tab when the error occur and perhaps target->id could help also.

**Comment by Playtester** [comment]
Those are guild skills:
10006,0,0,0,0,0,2,1,0,no,0,0x10,0,none,0,0x0,	GD_LEADERSHIP,Great Leadership
10007,0,0,0,0,0,2,1,0,no,0,0x10,0,none,0,0x0,	GD_GLORYWOUNDS,Glorious Wounds
10008,0,0,0,0,0,2,1,0,no,0,0x10,0,none,0,0x0,	GD_SOULCOLD,Cold Heart
10009,0,0,0,0,0,2,1,0,no,0,0x10,0,none,0,0x0,	GD_HAWKEYES,Sharp Gaze

Was it during WoE?

**Comment by anacondaqq** [comment]
> Wouldn't this happen when you have many guild leaders standing next to each other?
This is possible. I will test. (i have some NPC which can change guild leader position to another member)

**Comment by anacondaqq** [comment]
Closed. Since january this error not exist in DB, but if i will see it again, then i will try to get maximum info about the problem.
