### ISSUE TITLE
getequipuniqueid

### ISSUE THREAD

**Issue by julia40124009** [rathena/rathena#878]
<core>
prontera,155,185,5	script	testuniqueid	1_F_MARIA,{
	mes ""+getequipuniqueid(EQI_HAND_R);
	close;
}
</core>

http://i.imgur.com/AYbF1qi.png

version : https://github.com/rathena/rathena/commit/1352b460fc4115faed09e2b5bc2c24eeeaada7a7
client : 20141022
model : renewal

**Comment by nanakiwurtz** [comment]
Have you set your langtype into Chinese?
If I'm not mistaken, it should be 3.

**Comment by Lemongrass3110** [comment]
Confirmed this issue. It also gave me this error on my mapserver console:
```
[Error]: Memory manager: args of aFree 0x0018B578 is invalid pointer ...\rathena\src\map\script.c line 3583
```
