### ISSUE TITLE
mapflag	pvp_nightmaredrop It's not working

### ISSUE THREAD

**Issue by iberryRO** [rathena/rathena#8804]
### rAthena Hash

6e3d20413c34def6f72aa377b4338d542b7a38f6

### Client Date

20220602

### Server Mode

Renewal

### Result

I have designated that
```
prt_fild08	mapflag	pvp
//prt_fild08	mapflag	pvp_nocalcrank
prt_fild08	mapflag	pvp_nightmaredrop	random,equip,10000
```

Then, after engaging in PvP until death, the result is that no items drop from the player at all, even with the highest drop rate set.

### Expected Result

The item drops according to the conditions of the mapflag pvp_nightmaredrop.

### How to Reproduce

No response

### Official Information

No response

**Comment by iberryRO** [comment]
Thanks @Lemongrass3110

**Comment by Atemo** [comment]
Please don't close the issue until it's fixed on master.
