### ISSUE TITLE
Incorrect Chung_E pet

### ISSUE THREAD

**Issue by jamesandrewww** [rathena/rathena#8815]
### rAthena Hash

673ef066fb261985b7be4526b444e8b735e7ed95

### Client Date

2022-04-6

### Server Mode

Pre-Renewal

### Result

Chung_E (1519) only spawns in Endless Tower, so players won't be able to tame CHUNG_E_ (1631) in lou_dun03.
```
  - Id: 12395
    AegisName: Tantanmen
    Name: Tantan Noodle
    Type: Usable
    Buy: 20
    Weight: 50
    Flags:
      BuyingStore: true
    Script: |
      pet 1519;


  - Mob: CHUNG_E
    TameItem: Tantanmen
    EggItem: Chung_E_Egg
    FoodItem: Bun_
    Fullness: 3
    IntimacyFed: 50
    CaptureRate: 2000
    SpecialPerformance: false
    Script: >
      .@i = getpetinfo(PETINFO_INTIMATE);
      
      if( .@i >= PET_INTIMATE_LOYAL ){
        bonus bDef,1;
        bonus2 bSubRace,RC_DemiHuman,1;
        bonus2 bSubRace,RC_Player_Human,1;
      }
```

### Expected Result

```
  - Id: 12395
    AegisName: Tantanmen
    Name: Tantan Noodle
    Type: Usable
    Buy: 20
    Weight: 50
    Flags:
      BuyingStore: true
    Script: |
      pet 1631;


  - Mob: CHUNG_E_
    TameItem: Tantanmen
    EggItem: Chung_E_Egg
    FoodItem: Bun_
    Fullness: 3
    IntimacyFed: 50
    CaptureRate: 2000
    SpecialPerformance: false
    Script: >
      .@i = getpetinfo(PETINFO_INTIMATE);
      
      if( .@i >= PET_INTIMATE_LOYAL ){
        bonus bDef,1;
        bonus2 bSubRace,RC_DemiHuman,1;
        bonus2 bSubRace,RC_Player_Human,1;
      }
```

### How to Reproduce

1. @item Tantanmen
2. Try taming CHUNG_E_ (1631) in lou_dun03

### Official Information

If we use this as the official reference https://rathena.org/board/topic/91277-ragnarok-online-rathena-another-dimension/
Louyang was added in Episode 8, while Endless Tower was added in the later Episode 12.

**Comment by Daegaladh** [comment]
It's actually Chung_E (1519) on official servers, so not a bug.

**Comment by jamesandrewww** [comment]
> It's actually Chung_E (1519) on official servers, so not a bug.
So you have to run the Endless Tower just to tame it? That's very inconvenient.

BTW, it's CHUNG_E_ (1631) for renewal 
https://github.com/rathena/rathena/blob/master/db/re/pet_db.yml#L798

**Comment by Daegaladh** [comment]
You can get them spawn from dead branches too, and about renewal, as far as I know it should be 1519 too
I'll check it just to be sure.

**Comment by skyleo** [comment]
It's the MVP slaves of White Lady / Bascojin.

You can tame those.

**Comment by crazy-arashi** [comment]
![image](https://github.com/user-attachments/assets/2e4fcb36-fb8f-4c15-a3b3-52e1fe64579c)

Caught in lou_dun03 and the ID is 1631 on the parsed replay from kRO.
