### ISSUE TITLE
Slave Clone move back and forth

### ISSUE THREAD

**Issue by kaninhot004** [rathena/rathena#8816]
### rAthena Hash

e90e60f2fc8614a5d205ecfe4eab71a01465e1b8

### Client Date

20220602

### Server Mode

Renewal

### Result

https://github.com/user-attachments/assets/a8c7f31e-d375-4cbc-96eb-3e7a5d4b1135

### Expected Result

Slave Clone move normally.

### How to Reproduce

Use @ slaveclone character_name

### Official Information

Nothing.

**Comment by thanna** [comment]
I think this is the default behavior unless you edit the monster view range which will affect all monsters.

**Comment by kaninhot004** [comment]
> I think this is the default behavior unless you edit the monster view range which will affect all monsters.

I see, thank you so much!
