### ISSUE TITLE
SC_MAXIMIZEPOWER and RecognizedSpell

### ISSUE THREAD

**Issue by JairJunior26** [rathena/rathena#8819]
### rAthena Hash

-

### Client Date

2024-01-06

### Server Mode

Renewal

### Result

1. Use any weapon from the class that has the Power Amplify and Arcane Mastery skills, along with a staff or axe.
2. Hit a monster without the respective bonus.
3. Equip the axe or staff and hit the monster again.
4. Activate the skills.
5. Refine the weapon to +8 or higher.

Result: The damage variation should not occur, but it is happening. According to the official skill description, when the skill is active, the character's damage should reach the maximum and remain fixed

Vídeo 1: https://youtu.be/cFLw58jrgU8

Vídeo 2: https://youtu.be/KheSpLpra38

### Expected Result

Result: The damage variation should not occur, but it is happening. According to the official skill description, when the skill is active, the character's damage should reach the maximum and remain fixed

### How to Reproduce

1. Use any weapon from the class that has the Power Amplify and Arcane Mastery skills, along with a staff or axe.
2. Hit a monster without the respective bonus.
3. Equip the axe or staff and hit the monster again.
4. Activate the skills.
5. Refine the weapon to +8 or higher.

### Official Information

https://divine-pride.net/database/skill/2206/maestria-arcana

https://divine-pride.net/database/skill/114/amplificar-poder

**Comment by monbazko** [comment]
> q

You are not factoring weapon level and overupgrades.
Power Maximize is working as intended.
If a weapon has overupgrades variance would occur.

**Comment by JairJunior26** [comment]
Hello @monbazko , how are you?  
Thank you for your help. I have a question: up until now, there shouldn't be any variation in any way, even with the weapon's level and refinement. Do you know if there was a change in the logic at some point in a kRO update?

**Comment by monbazko** [comment]
> Hello @monbazko , how are you? Thank you for your help. I have a question: up until now, there shouldn't be any variation in any way, even with the weapon's level and refinement. Do you know if there was a change in the logic at some point in a kRO update?

It's a Renewal mechanic. Been that way since renewal.
https://hazyforest.com/equipment:refine#weapons
https://irowiki.org/wiki/Refinement_System#Effects_Gained

Power Maximize and Recognize Spell affects the variance from weapon damage formula but not ATK/MATK bonus from over refine on Lv1~4 weapons. 
Try on Lv5 weapons it has no over refine variance.

**Comment by JairJunior26** [comment]
> > Hello @monbazko , how are you? Thank you for your help. I have a question: up until now, there shouldn't be any variation in any way, even with the weapon's level and refinement. Do you know if there was a change in the logic at some point in a kRO update?
> 
> It's a Renewal mechanic. Been that way since renewal. https://hazyforest.com/equipment:refine#weapons https://irowiki.org/wiki/Refinement_System#Effects_Gained
> 
> Power Maximize and Recognize Spell affects the variance from weapon damage formula but not ATK/MATK bonus from over refine on Lv1~4 weapons. Try on Lv5 weapons it has no over refine variance.

Perfect.
Thanks for the explanations

**Comment by JairJunior26** [comment]
@monbazko sorry, 
Do you happen to know where I can find the formula to ensure there’s no variation in weapons from levels 1 to 4 with refinement?

**Comment by Lemongrass3110** [comment]
> @monbazko sorry, Do you happen to know where I can find the formula to ensure there’s no variation in weapons from levels 1 to 4 with refinement?

Please use our discord server for support questions.
