### ISSUE TITLE
Potential crash in pf_soulchange?

### ISSUE THREAD

**Issue by stmarier** [rathena/rathena#882]
Howdy, we ran into a possible issue here, looking for some insight.

In 89a33a7 [skill.c](src/map/skill.c), lines 8113 and 8114 we have

```c
#endif
				if (tsc->data[SC_NORECOVER_STATE])
					sp1 = tstatus->sp;
```

This appears to be missing a null check similar to other tsc comparisons in this function?  ```if (tsc && tsc->data)``` and so on.

I could submit a PR but I'm not sure if this is justified or not.  Thanks!

**Comment by mrjnumber1** [comment]
It's PF_SOULCHANGE

but indeed, tsc is never checked before that line. The tabbing is even incorrect, as if it was meant to be in the #ifdef just before it.

**Comment by aleos89** [comment]
We check for tsc here: https://github.com/rathena/rathena/commit/89a33a77ad47da523828d1156c2f68d1d2e561ee#diff-a62a8cdf5ca5dce3e8091f667d78f417R7391

The tabbing is just for the visual aspect. White space has no effect in C. :)

**Comment by mrjnumber1** [comment]
you didnt even look at the right lines in the OP

**Comment by aleos89** [comment]
You're right, thanks. Grabbed the wrong line while searching in the commit.
