### ISSUE TITLE
Giant Fly Wing Bug

### ISSUE THREAD

**Issue by Miraakol** [rathena/rathena#8839]
### Client Date

2022-04-06

### Server Mode

Pre-Renewal

### Result

There are instances when using the Giant Fly Wing causes some party members to be teleported to different locations.

https://youtu.be/UGizBAW14Os

### Relevant Log Output

```Shell
N/A
```

### Expected Result

Party members should always be recalled to the same location where the party leader is teleported.

### How to Reproduce

- Create a party.
- Invite another player to join the party.
- Enter a dungeon together.
- Continuously spam the Giant Fly Wing, as shown in the video provided.

### Official Information

N/A

### Modifications that may affect results

- Added goldpc (from rathena branch)
- Added VIP fix char limit creation (also from rathena branch)

**Comment by Daegaladh** [comment]
Not sure what might be causing it but I'll check it

**Comment by Miraakol** [comment]
> Not sure what might be causing it but I'll check it Where did the other player go? Does it any error on the console?

Hello, @Daegaladh! There's no error on the console. However, both players were randomly teleported, which seems unusual.
