### ISSUE TITLE
Cart direction should be sync with spawn_direction

### ISSUE THREAD

**Issue by gidzdlcrz** [rathena/rathena#8851]
### Is your request related to a missing official feature?

No

### Describe the solution you'd like

I don't know if this is doable but the cart is always facing north when a player teleports, changes maps, or logs in. It will be awesome if the carts are sync to spawn_direction too. Or a a new conf? like cart_spawn_direction?

### Describe alternatives you've considered

N/A

**Comment by Lemongrass3110** [comment]
We have no possibility to tell the client the direction of the cart.
