### ISSUE TITLE
atcommand stockall feature doesnt properly count the items.

### ISSUE THREAD

**Issue by gidzdlcrz** [rathena/rathena#8858]
### rAthena Hash

latest

### Client Date

2018 ~ 2024

### Server Mode

Pre-Renewal, Renewal

### Result

When you use at stockall it works but it doesnt properly count the items nor the item flags

### Relevant Log Output

```Shell
Not Applicable
```

### Expected Result

It should count the items like whats on at dropall command

### How to Reproduce

put items in your carts. then use at stockall command. You will notice that it doesnt count the items properly.

### Official Information

Not Applicable

### Modifications that may affect results

Not Applicable

**Comment by Lemongrass3110** [comment]
Could you show us an example with screenshots?

Note: If you transfer stackable items, it will count each of it. So if you transfer 500 Apples and 500 Red Potions, you will see: "1000 items are transferred (0 skipped)!"

**Comment by gidzdlcrz** [comment]
> Note: If you transfer stackable items, it will count each of it. So if you transfer 500 Apples and 500 Red Potions, you will see: "1000 items are transferred (0 skipped)!"

Yes. This part doesnt work. It always says "0 items are transferred (0 skipped)!"
