### ISSUE TITLE
I think I found an issue with the monsters using skills.

### ISSUE THREAD

**Issue by Beginerxxxxx** [rathena/rathena#8861]
### rAthena Hash

https://github.com/rathena/rathena/commits/master

### Client Date

2023-09-06

### Server Mode

Renewal

### Result

Hello, how are you?

My server has been updated from master continuously without any issues.

Players have reported to me that when monsters use skills on players, the map server stops working completely. I have tested this with several monsters, and the problem persists.

Whether there are many monsters attacking at once or just a few, sometimes even a single boss using a skill causes the same problem.

Could you please test if you're encountering the same issue?

Thank you for taking the time.

Sorry my English.

Video Here
https://www.youtube.com/watch?v=ZCUPqZQxj2Y
.

### Relevant Log Output

```Shell
None.
```

### Expected Result

None.

### How to Reproduce

None.

### Official Information

None.

### Modifications that may affect results

None.

**Comment by Beginerxxxxx** [comment]
It seems to be related to status effect skills, such as Stun, Freeze, Petrify, etc. The map server shuts down by itself when these skills are used as well. This is what my players have reported.

**Comment by Beginerxxxxx** [comment]
Skill Freeze.

https://github.com/user-attachments/assets/9166da84-611b-4f54-b5ce-9da5149d6e1d

**Comment by Beginerxxxxx** [comment]
Boss.

![Screenshot 2024-12-01 182421](https://github.com/user-attachments/assets/29a203b9-bbbd-4454-b508-ab3ddf0257af)

**Comment by Beginerxxxxx** [comment]
Monster Skill Grand Cross.

![Screenshot 2024-12-01 184047](https://github.com/user-attachments/assets/1649f67b-e6d6-4157-ac5b-057fb9b0e206)

**Comment by Daegaladh** [comment]
SO and compiler? Please provide gdb or debug information

**Comment by Beginerxxxxx** [comment]
> SO and compiler? Please provide gdb or debug information

There is no error information during compilation.
And while playing, when the issue occurs, the Map Server shuts down by itself.

**Comment by thanna** [comment]
Hi I tested it but on pre-renewal, map server didnt crash when stunned. let me try on renewal settings
https://jmp.sh/s/UFArdVaD0T53h7ynxiN0

**Comment by Beginerxxxxx** [comment]
> Hi I tested it but on pre-renewal, map server didnt crash when stunned. let me try on renewal settings https://jmp.sh/s/UFArdVaD0T53h7ynxiN0

Thank you for re test.

I tried rolling back SRC to a previous commit, and it works fine

![Screenshot 2024-12-01 191857](https://github.com/user-attachments/assets/cb7d1ad5-b720-4104-b650-312e56dba6bb)

**Comment by Beginerxxxxx** [comment]
I tried rolling back SRC 17/11 to a previous commit, and it works fine

![Screenshot 2024-12-01 192717](https://github.com/user-attachments/assets/920d69e5-040a-4bd7-841e-2ae040f45397)

![Screenshot 2024-12-01 192643](https://github.com/user-attachments/assets/711ef0d5-ab85-4145-80b5-fde999cd0185)

**Comment by OptimusM** [comment]
> > SO and compiler? Please provide gdb or debug information
> 
> There is no error information during compilation. And while playing, when the issue occurs, the Map Server shuts down by itself.

https://github.com/rathena/rathena/wiki/GDB
You're welcome.
Now please provide gdb log so people can help you out in case this is a rA related problem.

**Comment by Beginerxxxxx** [comment]
> > > SO and compiler? Please provide gdb or debug information
> > 
> > 
> > There is no error information during compilation. And while playing, when the issue occurs, the Map Server shuts down by itself.
> 
> https://github.com/rathena/rathena/wiki/GDB You're welcome. Now please provide gdb log so people can help you out in case this is a rA related problem.

Thank you very much. I don't know what 'GDB' is or how to use it. I apologize for the confusion

**Comment by Daegaladh** [comment]
https://github.com/rathena/rathena/wiki/GDB

**Comment by Beginerxxxxx** [comment]
I have been going through the code, fixing and compiling it one by one, then testing each change. When I reached this piece of code, I reverted it to the original value, and it worked without any issues.
Could you please check if this part of the code is the one causing the problem, or if I might have made a mistake in the sequence?

https://github.com/rathena/rathena/commit/df580b475ce39283db4f6c44c33480fd248067b6#diff-e9da83c5add2e830d737c917e5a40115323bdd83189435c7bbc32534a7717213

**Comment by Beginerxxxxx** [comment]
I tried not reverting this file to its original value, and the issue occurred as mentioned. I suspect that the problem might be with this file.

[src/map/status.cpp](https://github.com/rathena/rathena/commit/df580b475ce39283db4f6c44c33480fd248067b6#diff-16a6f317c581ce365a41a9846cf48dc45c8d6ac0256a7c45849e6e1b37100ecd)

**Comment by Lemongrass3110** [comment]
Please stop guessing around and please follow the recommendations you get.
@Daegaladh already linked you to a guide on how to use GDB.
Once you gave us a GDB crash dump we can investigate it.

**Comment by Beginerxxxxx** [comment]
I've found the source of the problem. I'm not sure where this line was updated from, but when I removed it, the game works fine.

[src/map/status.cpp](https://github.com/rathena/rathena/commit/df580b475ce39283db4f6c44c33480fd248067b6#diff-16a6f317c581ce365a41a9846cf48dc45c8d6ac0256a7c45849e6e1b37100ecd)

`rate -= rate*sd->sc.getSCE(SC_COMMONSC_RESIST)->val1/100;`

`	// When tick def not set, reduction is the same for both.
	if(tick_def == -1)
		tick_def = sc_def;

	// Natural resistance
	if (!(flag&SCSTART_NORATEDEF)) {
		rate -= rate*sc_def/10000;
		rate -= sc_def2;

		// Item resistance (only applies to rate%)
		if (sd) {
			for (const auto &it : sd->reseff) {
				if (it.id == type)
					rate -= rate * it.val / 10000;
			}
				rate -= rate*sd->sc.getSCE(SC_COMMONSC_RESIST)->val1/100; <------- Here
		}`

After the fix, it should be

`	// When tick def not set, reduction is the same for both.
	if(tick_def == -1)
		tick_def = sc_def;

	// Natural resistance
	if (!(flag&SCSTART_NORATEDEF)) {
		rate -= rate*sc_def/10000;
		rate -= sc_def2;

		// Item resistance (only applies to rate%)
		if (sd) {
			for (const auto &it : sd->reseff) {
				if (it.id == type)
					rate -= rate * it.val / 10000;
			}
		}`

Thank you very much to everyone for your help and support.

**Comment by Beginerxxxxx** [comment]
Hello i have new report from player.
Monster use skill AL_DECAGI status Map-Server is close again.
Please test again Thank you.

**Comment by Beginerxxxxx** [comment]
I don't know why i use status.cpp before update
https://github.com/rathena/rathena/commit/df580b475ce39283db4f6c44c33480fd248067b6#diff-16a6f317c581ce365a41a9846cf48dc45c8d6ac0256a7c45849e6e1b37100ecd

It's works fine.
