### ISSUE TITLE
No Mob CHUNG_E In mob_db

### ISSUE THREAD

**Issue by Beginerxxxxx** [rathena/rathena#8869]
### rAthena Hash

https://github.com/rathena/rathena/commit/76f9dfbe91b1dc46121e91d597707058f5c03910

### Client Date

2023-09-06

### Server Mode

Renewal

### Result

Hi how are you.
I update can't not create PET name CHUNG_E it's just have
- Id: 1631
    AegisName: CHUNG_E_
    Name: Green Maiden
    JapaneseName: Chung E

PET is link data to mob_db from mob name.

`  - Mob: CHUNG_E
    TameItem: Tantanmen
    EggItem: Chung_E_Egg
    FoodItem: Bun_
    Fullness: 3
    IntimacyFed: 50
    CaptureRate: 2000
    SpecialPerformance: false
    Script: >
      .@i = getpetinfo(PETINFO_INTIMATE);
      if (.@i >= PET_INTIMATE_LOYAL) {
         bonus2 bSubRace,RC_DemiHuman,2;
         bonus2 bSubRace,RC_Player_Human,2;
         bonus bDef,2;
      }
      else if (.@i >= PET_INTIMATE_CORDIAL) {
         bonus2 bSubRace,RC_DemiHuman,1;
         bonus2 bSubRace,RC_Player_Human,1;
         bonus bDef,1;
      }`

Thank you.

### Relevant Log Output

```Shell
none.
```

### Expected Result

none.

### How to Reproduce

none.

### Official Information

none.

### Modifications that may affect results

none.

**Comment by hiphop9** [comment]
Mob: The CHUNG_E part is incorrect

**Comment by Beginerxxxxx** [comment]
> Mob: The CHUNG_E part is incorrect

Thank you.

**Comment by Daegaladh** [comment]
What do you mean? There's both CHUNG_E and CHUNG_E_ on both pre-re and renewal mob_db databases

**Comment by Beginerxxxxx** [comment]
> What do you mean? There's both CHUNG_E and CHUNG_E_ on both pre-re and renewal mob_db databases

Sorry i can't find in database.
