### ISSUE TITLE
open box bug

### ISSUE THREAD

**Issue by Miraakol** [rathena/rathena#8872]
### rAthena Hash

3e14940ee1a837984c19f2e8698cdd7b3e5cec23

### Client Date

2022-04-06

### Server Mode

Pre-Renewal

### Result

- The character's maximum weight is 2660, and the current weight is 1315, which is well below the maximum weight limit.

- The character attempted to open a Blue Potion Box that should contain 100 Blue Potions. However, upon opening, the expected 100 Blue Potions were not received, and the box disappeared from the inventory.

- Each time the box is opened, the character's current weight decreases by 1, as shown in the video, even though no items are 
added to the inventory.

- Additionally, an error appears in the terminal whenever the box is opened, as shown in the attached file. This may indicate a script or system issue that is causing the behavior.

Additional Info:

Box Weight is 1
Blue Potion weight is 15

https://github.com/user-attachments/assets/ef761557-cdb5-45b9-907f-946db686e636

### Relevant Log Output

```Shell
[Error]: buildin_getitem: Failed to add the item to player.
[Warning]: Script command 'getitem' returned failure.
[Debug]: Source (NPC): FAKE_NPC (invisible/not on a map)
[Debug]: Source (NPC): FAKE_NPC is located in: (null)
[Info]: Saved Inventory (0) data to table inventory for char_id: 150020
[Info]: Saved Cart (0) data to table cart_inventory for char_id: 150020
[Info]: Saved Inventory (0) data to table inventory for char_id: 150021
[Info]: Saved Cart (0) data to table cart_inventory for char_id: 150021
[Error]: buildin_getitem: Failed to add the item to player.
[Warning]: Script command 'getitem' returned failure.
[Debug]: Source (NPC): FAKE_NPC (invisible/not on a map)
[Debug]: Source (NPC): FAKE_NPC is located in: (null)
[Error]: buildin_getitem: Failed to add the item to player.
[Warning]: Script command 'getitem' returned failure.
[Debug]: Source (NPC): FAKE_NPC (invisible/not on a map)
[Debug]: Source (NPC): FAKE_NPC is located in: (null)
```

### Expected Result

Expected Result:

- When opening the Blue Potion Box, the character should receive 100 Blue Potions in their inventory, and the box should be removed after successful item transfer.

- The character's current weight should increase accordingly based on the weight of the received Blue Potions.

- No weight deductions or anomalies should occur if the character has enough weight capacity to accommodate the items.

- No errors should appear in the terminal or game logs during this process.

### How to Reproduce

you may refer to the video attached

### Official Information

NA

### Modifications that may affect results

added goldpc feature (from rathena branch)
added gepard 3.0

**Comment by Daegaladh** [comment]
100 Blue potions weight 1500, plus the current 1315 exceeds the max 2660

**Comment by Daegaladh** [comment]
The error shows because you used getitem in your item box script, and since the items cannot be created because you'll get overweight, you get the script error (that would be managed in a future PR) and you won't get the items.

That's a custom item, but official items work the same. You could also use getgroupitem intead.

**Comment by Daegaladh** [comment]
The error shows because you used getitem in your item box script, and since the items cannot be created because you'll get overweight, you get the script error (that would be managed in a future PR) and you won't get the items.

That's a custom item, but official items work the same. You could also use getgroupitem intead.
