### ISSUE TITLE
Emperium Not Consumed After Guild Creation

### ISSUE THREAD

**Issue by Miraakol** [rathena/rathena#8881]
### rAthena Hash

f4f60a3e915881c4f0b3bee8189bd1d2ce116ef2

### Client Date

2022-04-06

### Server Mode

Pre-Renewal

### Result

When creating a guild using an Emperium, the item is not consumed from the inventory as expected. This allows players to repeatedly create guilds without requiring additional Emperium.

### Relevant Log Output

```Shell
NA
```

### Expected Result

Expected Behavior

The Emperium should be consumed upon successful guild creation.

### How to Reproduce

Steps to Reproduce

- Im using group level 99 account
- Obtain an Emperium.
- Use the /guild command or manually create a guild through the required interface.
- Observe that the guild is created successfully, but the Emperium remains in the inventory.

### Official Information

I know it should be consumed after guild creation.

### Modifications that may affect results

- Gepard src
- Goldpc Feature from rA branches

**Comment by Daegaladh** [comment]
Have you disabled guild_emperium_check on guild.conf?

**Comment by Miraakol** [comment]
> Have you disabled guild_emperium_check on guild.conf? (It should be enabled by default)

Yes, the guild_emperium_check is enabled in guild.conf. However, the issue still persists despite this setting.

**Comment by Playtester** [comment]
Cannot confirm this. Latest rAthena, Pre-Renewal with no changes and even with an admin account, the Emperium is consumed.

**Comment by Miraakol** [comment]
![image](https://github.com/user-attachments/assets/eaef7c14-c6b4-4b42-a0e8-94bf88ddb3e4)

Thanks for the clarification. By 'manually creating a guild through the required interface,' I was referring to the in-game UI shown (screenshot attached). It's the 'Create Guild' window accessed via the alt+g. Anyway, really appreciate your help! @Playtester @Daegaladh

**Comment by Daegaladh** [comment]
Both /guild and the UI check for the emperium by default as intended, `@guild` on the other hand ignores this configuration. Please check your conf files and import.
