### ISSUE TITLE
Missing Map Drops of Horror Toy Factory

### ISSUE THREAD

**Issue by Pokye** [rathena/rathena#8887]
### rAthena Hash

fdf3efe1d3c8aafdd8a7f8dbea7f79c18fca7897

### Client Date

2024-09-19

### Server Mode

Renewal

### Result

All monsters now drop Blood Coin ( https://www.divine-pride.net/database/item/7642 ). The monster Antonio now drops Christmas Guardian Tree (https://www.divine-pride.net/database/item/20955), other monsters drop Noble Cross ( https://www.divine-pride.net/database/item/16029 ), Heart Accessories ( https://www.divine-pride.net/database/item/2977 / https://www.divine-pride.net/database/item/2978 ), and Celine drops Celine's Brooch Type K ( https://www.divine-pride.net/database/item/32237 ), Celine Dress ( https://www.divine-pride.net/database/item/450179 ), Celine's Ribbon ( https://www.divine-pride.net/database/item/18849 ) and Evil Spirit Glove (https://www.divine-pride.net/database/item/2980 ).

### Relevant Log Output

```Shell
.
```

### Expected Result

![image](https://github.com/user-attachments/assets/4a4cc25b-74cc-4cf8-8f71-be9bfd0ceda0)

### How to Reproduce

.

### Official Information

https://www.facebook.com/ROWiki/posts/atualiza%C3%A7%C3%A3o-na-ordem-dos-exploradorescom-a-nova-edi%C3%A7%C3%A3o-da-ordem-dos-exploradores/962244855918724/

https://www.divine-pride.net/database/monster/2996/celine-kimi

**Comment by Atemo** [comment]
Fixed in https://github.com/rathena/rathena/commit/0a68e9889ee4867874d459548b0981f8519e29f6
