### ISSUE TITLE
getequiprefinerycnt get error values

### ISSUE THREAD

**Issue by julia40124009** [rathena/rathena#890]
test script 
<pre><code>
prontera,45,166,4	script	test!!!	1_F_MARIA,{
	mes "EQI_HEAD_TOP: "+getequiprefinerycnt(EQI_HEAD_TOP);
	mes "EQI_HEAD_MID: "+getequiprefinerycnt(EQI_HEAD_MID);
	mes "EQI_HEAD_LOW: "+getequiprefinerycnt(EQI_HEAD_LOW);
	mes "EQI_ARMOR: "+getequiprefinerycnt(EQI_ARMOR);
	mes "EQI_HAND_L: "+getequiprefinerycnt(EQI_HAND_L);
	mes "EQI_HAND_R: "+getequiprefinerycnt(EQI_HAND_R);
	mes "EQI_GARMENT: "+getequiprefinerycnt(EQI_GARMENT);	
	mes "EQI_SHOES: "+getequiprefinerycnt(EQI_SHOES);	
	mes "EQI_ACC_L: "+getequiprefinerycnt(EQI_ACC_L);	
	mes "EQI_ACC_R: "+getequiprefinerycnt(EQI_ACC_R);	
	close;
}
</code></pre>

and picture
http://imgur.com/a/ZN1Gw
http://imgur.com/FVCx4Ly

all values not correct 

version : https://github.com/rathena/rathena/commit/96432305218f2e01470be73b5a32c993a30be864
client : 20141022
model : renewal

**Comment by julia40124009** [comment]
maybe because 
script.c

static unsigned int equip[] = {
	EQP_SHOES,
	EQP_ARMOR,
	EQP_HAND_L,
	EQP_HAND_R,
	EQP_GARMENT,
	EQP_HEAD_TOP,
	EQP_ACC_L,
	EQP_ACC_R,
	EQP_HEAD_MID,
	EQP_HEAD_LOW,
	EQP_COSTUME_HEAD_LOW,
	EQP_COSTUME_HEAD_MID,
	EQP_COSTUME_HEAD_TOP,
	EQP_COSTUME_GARMENT,
	EQP_AMMO,
	EQP_SHADOW_ARMOR,
	EQP_SHADOW_WEAPON,
	EQP_SHADOW_SHIELD,
	EQP_SHADOW_SHOES,
	EQP_SHADOW_ACC_R,
	EQP_SHADOW_ACC_L
};

**Comment by cydh** [comment]
indeed, must be EQP. I was mentioned this before on old bug tracker.

**Comment by julia40124009** [comment]
if change EQP order can solve it ?

**Comment by cydh** [comment]
yes, it should. re-order `static unsigned int equip[]` follow the `pc.h::enum equip_index`'s order.
afaik before the `script_constants.h` merge, the `EQI_` values are not match between the entries in const.h and pc.h

**Comment by julia40124009** [comment]
script.c
http://i.imgur.com/S0OmaKk.png
but . still get error values

**Comment by julia40124009** [comment]
I edit getequiprefinerycnt command
if (num >= 0 && num <= ARRAYLENGTH(equip))
i=pc_checkequip(sd,equip[num]);

can get correct values .. but i think
a lot of command must be edit ...

not good mode
