### ISSUE TITLE
Doubting Trap Visible Behavior

### ISSUE THREAD

**Issue by cydh** [rathena/rathena#892]
I'm doubting current rAthena trap 'visible' conditions. Currently, doesn't matter the condition for the trapper also for other player, when the trap is in outsight then trapper or other players come to trap location, the traps are always invisible. After the traps are revealed by skills (Sight, Detect), it can be invisible again.

### 'Always Visible' X 'Invisible' Trap type,
- [ ] There are some kind of traps that visible and are not. **Always Visible**: Claymore and Blast Mine. **Invisible**: Skid Trap, Land Mine, Anklesnare, Shockwave Trap, Sandman, Flasher, Freezing Trap, and Talkie Box

### 'Always Visible' means,
- [ ] The trap, when it's placed always be visible for the trapper and other players.

### 'Invisible' means,
- [ ] When the trap is placed, the trap is visible for the trapper and all players that in same screen with the trapper.
- [ ] The trap **always** be visible for the trapper.
- [ ] When other players move to the outsight of trap location, then the players come back the trap is **invisible**.
- [ ] The trap is visible (revealed) if someone step on it.
- [ ] When the invisible traps are "forced to visible" by using skill (such Sight and Detect), the trap always be visible, although the other players move to outsight area then come back again.

Notes:
* Idk if this behavior only for renewal only or not, but by looking to the packet (also the old packets) there's bit for `<visible>.B`

**Comment by Playtester** [comment]
I want to note that the trap visibility behavior on Aegis and official servers may differentiate, so it's better to test this on official servers rather than on an Aegis test server.

**Comment by cydh** [comment]
config
````
// Default trap's visibility for all maps (bitmask of):
// 0: Hidden trap only be invisible when players move out of sight from trap location when trap is placed.
// 1: Hidden trap always be invisible after it's placed.
// 2: Revealed trap (by INF3_REVEAL_TRAP) is lasting until trap is expired.
// NOTE:
// - This config or trap-specific-setting can be override on certain by 'traps_setting' mapflag see doc/mapflags.txt.
// - 'Hidden trap' refers to unit's flags on db/[pre-]re/skill_unit_db.txt UF_HIDDEN_TRAP_SELF and UF_HIDDEN_TRAP_OTHER.
//    To makes all traps are always visible just remove UF_HIDDEN_TRAP_SELF and UF_HIDDEN_TRAP_OTHER flags.
traps_setting: 3
````

mapflag
````
---------------------------------------

*traps_setting	<type>
*traps_setting	<skill_name>,<flag>

Override 'traps_setting' config for this map. Type values are same with traps_setting's values.

For the seconds structure will be applied for specific trap skill, this mapflag will override
flags on skill_unit_db.txt.
Available 'flag' values are (bitmask):
	 0: Always visible.
	 1: Set as hidden trap.
	 2: Immediate hide.
	 4: Hide for self.
	 8: Hide for others.
	16: Always visible on revealed.

---------------------------------------
````

**Comment by Playtester** [comment]
The general setting should include "Traps always visible by default".

Normally you will want them to always be visible except on PVP maps, don't you?

**Comment by aleos89** [comment]
Was there a reason this was closed?

**Comment by Playtester** [comment]
I wondered the same...

I saw a bug report about it on a private server lately:

> traps are not appearing on the screen, like never. if you ends up on a trap and @refresh it, the trap you are in disappear. can you imagine how catastrophic it is for the real game?
