### ISSUE TITLE
Bug skill job gyps: tarot

### ISSUE THREAD

**Issue by Dark8008** [rathena/rathena#893]
When use tarot and get coma card, if normal, the players will get lost hp and hp. But the source now is not !

Source: Pre-renewal
Version: Latest rathena
Client: 2014-10-22

**Comment by cydh** [comment]
it was changed since https://github.com/rathena/rathena/commit/b385fd048a6872b0fbd2562f619c51bf75f47599#diff-a62a8cdf5ca5dce3e8091f667d78f417R8217 by @aleos89 to fix something. and maybe he forgot while changing the `sc_start` to `status_change_start`, the rate is still remain 100 not 10000.
