### ISSUE TITLE
ID: 13414 has bug

### ISSUE THREAD

**Issue by Dark8008** [rathena/rathena#894]
Although all effect bonus just 10%, but when i try to cast COLDBOLT it nearly 100%, cast 10 times result 10 times use all skill !

Source: pre-renewal
Latest version
2014-10-22 client !

**Comment by cydh** [comment]
the script makes it 100% D:
````
bonus4 bAutoSpellOnSkill,"MG_COLDBOLT","MG_FIREBOLT",3,1000;
````

> bonus4 bAutoSpellOnSkill,sk,x,y,n;  	Adds a n/10% chance to autospell skill x at level y when using skill sk

@nanakiwurtz please?

**Comment by Playtester** [comment]
1000=100%

That's also how it officially is, if you cast COLDBOLT, you will also cast FIREBOLT and LIGHTNINGBOLT to 100%.

Already correct.

**Comment by Dark8008** [comment]
I already post this before: https://github.com/rathena/rathena/issues/867
Real effect just 10% sir @@

**Comment by Playtester** [comment]
The bug was that it was 1000% and was fixed to be 100%. Not 100% to 10%.

The current data we have also says 100%, I checked. Got any evidence that says otherwise?
