### ISSUE TITLE
ID: 12319 has bug

### ISSUE THREAD

**Issue by Dark8008** [rathena/rathena#895]
From IRO: http://db.irowiki.org/db/item-info/12319/
Gives Atk +5 and Matk +5 for 10 minutes

But Latest Rathena version now is both of them are 5%

I use: pre-renewal !

**Comment by Playtester** [comment]
Confirmed.

All items with Aegis effect "EFFECTPlus" should be using SC_ATKPOTION or SC_MATKPOTION, like for example already done with Durian:

684,Durian,Durian,2,15000,,300,,,,,0xFFFFFFFF,7,2,,,,,,{ sc_start SC_ATKPOTION,60000,10; sc_start SC_MATKPOTION,60000,10; },{},{}

**Comment by nanakiwurtz** [comment]
This might be true on Renewal, but I don't know with Pre-RE though...

**Comment by Playtester** [comment]
True, we only got renewal special.sc I guess?
