### ISSUE TITLE
Driller NPC item check issue

### ISSUE THREAD

**Issue by lelouch22** [rathena/rathena#897]
![screenrathena011](https://cloud.githubusercontent.com/assets/4976551/12261612/1dffe630-b95d-11e5-82aa-68217cd20657.jpg)
![screenrathena012](https://cloud.githubusercontent.com/assets/4976551/12261617/24e96ae8-b95d-11e5-93e9-02e8029733e7.jpg)
![screenrathena013](https://cloud.githubusercontent.com/assets/4976551/12261618/29ba332c-b95d-11e5-8848-4d64a89b3b3a.jpg)
![screenrathena014](https://cloud.githubusercontent.com/assets/4976551/12261619/2cf54ea0-b95d-11e5-8443-b52726fa4877.jpg)

**Comment by Atemo** [comment]
Related to issue #890
