### ISSUE TITLE
Casttime Bug (instant casttime with memorize / poems of bragi (stackable)) on pre-re.

### ISSUE THREAD

**Issue by anacondaqq** [rathena/rathena#899]
Hello Dear rAthena developers.

### Problem

I think, there are happened mistake *bug*, which must be tested again or re-added old-style way for functions below in skill.conf (to have a choise to select which type of casttime to select):

- skill_castfix_sc
- skill_castfix

I'm talking about bug, which was happened after this commit: 05cb1607c5be89df27de6431dbaa03076ab78986
I'm talking about instant cast with 1 dex with 2 imp cards + memorize or bragi. 

They now is working at another way.
For example Fire Bolt lvl 10 have casttime 1000 ms with 1 dex without items. (just for example)
**So with 2x imp cards + Memorize, final casttime must be 0.25 second, and not instant.** 
(so it worked a few years before the recent changes.)

#### Why?

1000ms / 500 from imp cards = 500ms
500ms - (500ms * 50% from memorize) = 250ms.

#### Now
How it start to work after this commit: 05cb1607c5be89df27de6431dbaa03076ab78986
50x from cars / items bonuses is STACKABLE with MEMORIZE or Bragi in pre-re.

What does it means? You can do instant casttime with 1 dex without any problems.
Totally destroyed private server mechanic since 2008 year (almost last 8 years of mechanics is totally killed).

#### My suggestions:
Please, revert back the changes for MEMORIZE & Poems of Bragi, or add extra option in skill.conf where people can switch (select), by they-self about which type of mechanic they will use with that spell. This is very import.

Here is some screen-shots which describe what i'm talking about: 

# Current Problem
(as you see, instant casttime with 2x imps 1 dex + memorize (stackable)).
The same issue with poem bragi.
![](http://i.imgur.com/PZ8E8OL.gif)

# Here is gifs how it was (old style)
(not stackable, how it was for years.)
![](http://i.imgur.com/5W1jlbU.gif)

### Technical Details:
Mode: pre-re
Packet_ver: 30 / 2012-04-10
hash: 3a8aac4fb0d4ce56b6057facd35ba3579b78ed7a

### Extra arguments
* http://forums.irowiki.org/showthread.php?t=2301
* https://forums.warpportal.com/index.php?/topic/172997-fixed-cast-time-gear/page-2
* http://forums.irowiki.org/showthread.php?t=100052
* https://forums.warpportal.com/index.php?/topic/39491-mystical-amp-vs-foresight-double-bolt/
* https://rathena.org/board/topic/62312-new-skill-cast-times-system/

+ I did't found any information related to pre-re in internet about this behavioir (even in iROwiki)

**Comment by cydh** [comment]
Imp Card -25% Cast time of Fire Bolt, 2x = 50%.
Memorize reduce 50%. It becomes 100%. xD

**Comment by anacondaqq** [comment]
Dear @cydh sorry please, that's why i was create issue about that. I'm not sure about this. Because as i remember at eathena (i was play very very long ago), and i don't remember this befavior with imp cards. As i remember (again, i'm not talking about official server), imp cards + memorize must work by next way:

Example:
========
Firebolt without any cards / statuses normal casttime 1second (for example)

With memorize we must have 0.5 seconds
With 2 imp cards we must have 50% of rest casttime

So, finally we must have something like:
===============================
1 second normal firebolt casttime
- 50% from memorize = 0.5 second cast time
- 50% from imp cards = 0.5% - (0.5 / 100 * 50)
So, finally casttime must be 0.25 seconds.

Please correct me someone if i'm wrong, and i will close this issue.
Sorry please if i misunderstood something, but i need to check (what i'll do right now)

**Comment by anacondaqq** [comment]
Okay, i can confirm (tested on several servers).
This is a bug, how it must be on pre-re:
![](http://i.imgur.com/sA8mrML.gif)

**Comment by anacondaqq** [comment]
Okay, i've tested this issue on several emulators from different years & rAthena.
I can confirim (sorry if i repeat). This is a bug at rAthena. 

Here is the same result at gif like at any server without this bug.
How it must work decribed below on the gift (not rAthena emulator)
![](http://i.imgur.com/oSguQIF.gif)

**Comment by Playtester** [comment]
I'm a bit confused right now, because I saw a similar report that was exactly the opposite. It was about POEMBRAGI, though.

"Over 50% cast time reduction bragi + isilla effect did not grant instant cast.
I am pretty sure i had instant cast with that on euro/fro and i tested it again on iro classic."

and

"50% strings + 50% from isilla should result in instant cast.

This is iRO behavior."

And the commit you linked is also weird because the code comment says exactly the opposite of what it does?

**Comment by anacondaqq** [comment]
@Playtester Okay, i got you.
But i think this is bug. And i will fix it by myself.

**Comment by anacondaqq** [comment]
I've tried, but failed. Please return or add extra option to this befavior (switchable for example at skill.conf). Be sure, destroyed RO classic mechanic (for pre-re servers on eA / rA / herc) will make a lot of issues same as mine after some time, when GM's will apply this patches to their servers and will try it at live one. Anyway, i did't found any information (like you said) about how it work at official server. I do not have any character (high level) at official servers, so i can't test.

**Comment by Playtester** [comment]
Okay, I cleared up the confusion. The server on which I read the report on had a customization to make all cast time stack multiplicative.

But in realize some should stack linear and some multiplicative.

I **think** it's like this:

Group A: Unspecific Casttime + Bragi
Group B: Specific Casttime
Group C: Suffragium
Group D: Memorize

Within a group the bonus is linear, but the result for each group stack multiplicative.

This needs to be tested on Aegis first, though!

**Comment by anacondaqq** [comment]
Yes, i can, what i should to do? @Playtester

**Comment by Playtester** [comment]
Actually nevermind, I was thinking you tested on official servers, but you just posted a video of how it was earlier on private servers.

Though the links only talk about Specific Casttime cards not lineary stacking. Hmm.

**Comment by anacondaqq** [comment]
It would be nice to have a battle.conf setting to turn on/off the display of all those hidden bonuses instead of just following the official implementation, which can be quite impractical and confusing.

**Comment by Playtester** [comment]
What do you mean with display?

**Comment by anacondaqq** [comment]
Thank you very much, i will try to contact with some players which playing at official servers to get more information about this behavior.
