### ISSUE TITLE
Bug after update - prerenewal

### ISSUE THREAD

**Issue by Dark8008** [rathena/rathena#902]
![untitled](https://cloud.githubusercontent.com/assets/14345362/12284122/d4bd7478-b9df-11e5-8274-fbc94291dfd9.png)
Before update i run server normal, but after update get this error !

When i run and log to server and login account, all character gone T_T

**Comment by CairoLee** [comment]
you forget to import sql-files\upgrades\upgrade_20160112.sql

**Comment by Dark8008** [comment]
I think there will be auto upgrade, my god @@

**Comment by Dark8008** [comment]
Done, thank you !
