### ISSUE TITLE
Mystical Amplification Cast Time Reduction

### ISSUE THREAD

**Issue by Playtester** [rathena/rathena#903]
Officially the only thing that can reduce the cast time of Mystical Amplification is Staff of Destruction. Other items that change cast time (included Isilla Card) should not reduce the cast time.

There are two things that need to be changed here. 
First in the database:
https://github.com/rathena/rathena/blob/master/db/pre-re/skill_castnodex_db.txt
366,3 //HW_MAGICPOWER
Should be:
366,7 //HW_MAGICPOWER

This will prevent normal items and Isilla Card from affecting Mystical Amplification, but also breaks Staff of Destruction.

This is because the code for spell-specific cast time reductions checks for flag 4. Obviously if you put a bonus to reduce the cast time of one specific spell, then you want to ignore any flags and Aegis does that too.

To fix for pre-renewal, in skill.c, find skill_castfix:
```c
		// calculate cast time reduced by item/card bonuses
		if (!(flag&4) && sd) {
			int i;

			if (sd->castrate != 100)
				reduce_cast_rate += 100 - sd->castrate;
			for(i = 0; i < ARRAYLENGTH(sd->skillcastrate) && sd->skillcastrate[i].id; i++) {
				if (sd->skillcastrate[i].id == skill_id) {
					reduce_cast_rate -= sd->skillcastrate[i].val;
					break;
				}
			}
		}
```

Now there are multiple ways to restructure the code here, but one solution would be to just move the flag check down like this:
```c
		// calculate cast time reduced by item/card bonuses
		if (sd) {
			int i;

			if (!(flag&4) && sd->castrate != 100)
				reduce_cast_rate += 100 - sd->castrate;
			for(i = 0; i < ARRAYLENGTH(sd->skillcastrate) && sd->skillcastrate[i].id; i++) {
				if (sd->skillcastrate[i].id == skill_id) {
					reduce_cast_rate -= sd->skillcastrate[i].val;
					break;
				}
			}
		}
```

The same should be done for renewal in function skill_vfcastfix.

I confirmed this with various players from official servers, both pre-renewal an renewal.

**Comment by reigneil** [comment]
for renewal HW_MAGICPOWER is pure fixed cast. the problem here are the staff itself. although i tested it in iRO not kRO

it should be reduce fixed cast of HW_MAGICPOWER by 50% making it cast time reduce to 350ms

**Comment by Playtester** [comment]
Doesn't that work already? Casttime reductions from items also reduce fixed cast, don't they?

**Comment by reigneil** [comment]
but the codings of the item are for variable casting only not the whole cast nor fixed cast.

**Comment by Playtester** [comment]
I didn't test it, but the renewal code certainly already has a feature to adjust fixed cast rate:

```c
	if (sd && !(flag&4)) {
		if (sd->bonus.varcastrate != 0)
			reduce_cast_rate += sd->bonus.varcastrate; // bonus bVariableCastrate
		if (sd->bonus.fixcastrate != 0)
			fixcast_r -= sd->bonus.fixcastrate; // bonus bFixedCastrate
		if (sd->bonus.add_varcast != 0)
			time += sd->bonus.add_varcast; // bonus bVariableCast
		if (sd->bonus.add_fixcast != 0)
			fixed += sd->bonus.add_fixcast; // bonus bFixedCast
		for (i = 0; i < ARRAYLENGTH(sd->skillfixcast) && sd->skillfixcast[i].id; i++) {
			if (sd->skillfixcast[i].id == skill_id) { // bonus2 bSkillFixedCast
				fixed += sd->skillfixcast[i].val;
				break;
			}
		}
		for (i = 0; i < ARRAYLENGTH(sd->skillvarcast) && sd->skillvarcast[i].id; i++) {
			if (sd->skillvarcast[i].id == skill_id) { // bonus2 bSkillVariableCast
				time += sd->skillvarcast[i].val;
				break;
			}
		}
		for (i = 0; i < ARRAYLENGTH(sd->skillcastrate) && sd->skillcastrate[i].id; i++) {
			if (sd->skillcastrate[i].id == skill_id) { // bonus2 bVariableCastrate
				reduce_cast_rate += sd->skillcastrate[i].val;
				break;
			}
		}
		for (i = 0; i < ARRAYLENGTH(sd->skillfixcastrate) && sd->skillfixcastrate[i].id; i++) {
			if (sd->skillfixcastrate[i].id == skill_id) { // bonus2 bFixedCastrate
				fixcast_r = max(fixcast_r, sd->skillfixcastrate[i].val);
				break;
			}
		}
	}
```

**Comment by reigneil** [comment]
i know there is a feature... what im after is the Database re/item_db.txt
2000,Destruction_Rod,Staff of Destruction,5,20,,2500,130:280,,1,1,0x00000200,18,2,34,4,80,1,23,{ .@r = getrefine; bonus bMatkRate,.@r/2; bonus bInt,3; bonus bAgi,10; bonus bUseSPrate,(.@r*2); bonus3 bAutoSpellWhenHit,"WZ_JUPITEL",5,(.@r*20); bonus2 bVariableCastrate,"HW_MAGICPOWER",-50; },{},{}

look at this it only reduce variable cast although there is no presence of variable at re/skill_cast_db.txt
//-- HW_MAGICPOWER
366,0,0,0,30000,0,0,700

**Comment by Playtester** [comment]
True, but that's also easy to fix, either make the cast time variable (it doesn't matter because skill_castnodex_db.txt makes it fixed anyway) or change the bonus to affect fixed cast time instead.

**Comment by reigneil** [comment]
this staff is useful in WOE TE because of Sacrament do not work. and im sure it is Fixed cast because i am always accompanied by Bragi/Magic String for spamming SG with Mystic Amplify

**Comment by Playtester** [comment]
Well the point is:
No staff - Always 700ms cast time no matter what
Staff -  350ms cast time

**Comment by reigneil** [comment]
not always sacrament works with it.

**Comment by aleos89** [comment]
I checked the Aegis data and it seems HW_MAGICPOWER is not defined in the fixed cast file. So it's safe to assume it uses variable cast time but is fixed in the skill_castnodex_db, how @Playtester said.

**Comment by Playtester** [comment]
Also, while we're at it: Spells that are not affected by Suffragium still should use it up when cast afaik.

**Comment by aleos89** [comment]
```
// ID: 2003
item Destruction_Rod_M
	event OnStartEquip:
		SubSpecificSpellCastTime HW_MAGICPOWER 50
		var temp = GetRefineLevel [LOCATION_RARM]
		AddExtParam User VAR_MAGICATKPERCENT temp/2
		AddSPconsumption temp*2
		SetAutoSpell_MLEATKED Target WZ_JUPITEL 5 temp*20
	return
	event OnFinishEquip:
		AddSpecificSpellCastTime HW_MAGICPOWER 50
		var temp = GetRefineLevel [LOCATION_RARM]
		SubExtParam User VAR_MAGICATKPERCENT temp/2
		SubSPconsumption temp*2
		SetAutoSpell_MLEATKED Target WZ_JUPITEL 0 0
	return
```
Looks like HW_MAGICPOWER should be Variable cast, not fixed cast.

**Comment by Playtester** [comment]
HW_MAGICPOWER is hardcoded that its cast time isn't reduced. It was like that in pre-renewal already, when there was no fixed cast time in the first place. You can make it variable cast, but don't forget to change skillcastnodex_db. Both solutions work.

**Comment by reigneil** [comment]
i see, now that explained why it is broken in the first place.
before it is set to no cast then change to variable then change it to fixed cast... but in reality renewal wont let it reducible by any mean other than that staff and it wasnt change since pre-renewal. geezz

**Comment by Playtester** [comment]
I think I'll get around to fixing this one a bit later.

**Comment by Playtester** [comment]
One more thing: The count of Memorize is also reduced on officials when casting Mystical Amplification.

**Comment by Playtester** [comment]
Note: I'll fix this only for pre-renewal for now because the renewal code is completely different for casttimes and I'm not sure it should actually function exactly the same.
