### ISSUE TITLE
Quagmire vs NPC_AGIUP

### ISSUE THREAD

**Issue by Playtester** [rathena/rathena#904]
On official servers, Quagmire works against NPC_AGIUP. It does not dispell it, but it reduces flee and speed (see here: http://forums.irowiki.org/showthread.php?p=301145#post301145).

In rAthena there is a problem that NPC_AGIUP uses SC_SPEEDUP1 which is also used for Speed Potion. Speed Potion effect is actually the only effect that can NOT be reduced officially. This was also implemented, but the problem is that this affected NPC_AGIUP too.

``` c
    // Check for immunities / sc fails
    switch (type) {
    case SC_DECREASEAGI:
    case SC_QUAGMIRE:
    case SC_DONTFORGETME:
    case SC_ADORAMUS:
        if(sc->data[SC_SPEEDUP1])
            return 0;
        break;
```

Also note the FIXME comment here:

``` c
        if( sc->data[SC_SPEEDUP1] ) // !FIXME: used both by NPC_AGIUP and Speed Potion script
            val = max( val, sc->data[SC_SPEEDUP1]->val1 );
```

So, either we do as the comment says and make a status change for NPC_AGIUP or make it use SC_SPEEDUP0 instead (MVPs can't use items so there shouldn't be a conflict).

Like this:

``` c
    case NPC_AGIUP:
        sc_start(src,bl,SC_SPEEDUP0,100,50,skill_get_time(skill_id, skill_lv));
```

**Comment by reigneil** [comment]
which npc agi up are you referring to the one that increase flee or the one that is increase walking speed?

**Comment by Playtester** [comment]
That's the same skill.

350,0,6,4,0,0x1,0,10,0,no,0,0x2,0,none,0,0x0, NPC_AGIUP,Agility UP

**Comment by reigneil** [comment]
opss i was thinking of agi up of Orc Lady. /sry

**Comment by cydh** [comment]
is it really SC_SPEED0?

**Comment by Playtester** [comment]
The difference between SC_SPEED0 and SC_SPEED1 in our implementation is that SC_SPEED1 cannot be reduced. As the speed buff from NPC_AGIUP CAN be reduced, we need to use SC_SPEED0 or create a new status change for it.

We can't use the other status changes because they get debuffed by Quagmire. SC_SPEED0 is the only available status change that seems to fit.

**Comment by cydh** [comment]
that's why I asked is it really NPC_AGIUP is using SC_SPEED0 or not.

**Comment by Playtester** [comment]
I don't really understand the question? Do you mean right now on rAthena? Then no, it's using SC_SPEED1 right now, that's why it's bugged.
If you mean whether using SC_SPEED0 fixes the issue? I didn't test, but I think it does by looking at the code.
If you mean on Aegis? Why does it matter?

Fact:
1. NPC_AGIUP cannot be dispelled by Quagmire
2. If a monster with NPC_AGIUP moves over Quagmire, it will move at 100% speed (instead of 200% speed).

**Comment by Playtester** [comment]
Important: Before we update this we need to check if NPC_AGIUP (or part of it) can be dispelled.

I saw that SC_SPEED1 is commented out so that it can be dispelled:
/*case SC_SPEEDUP1:*/
But SC_SPEED0 is not:
case SC_SPEEDUP0:

Maybe warrants a full test on Speed Potions and NPC_AGIUP vs. Dispell.

**Comment by Lemongrass3110** [comment]
Why not simply add a BL-type check?
Like ```if( bl->type != BL_MOB && sc->data[SC_SPEEDUP1] )```. That would assume that no other BL-type than mob uses NPC_AGIUP though.

**Comment by Playtester** [comment]
Testing NPC_AGIUP

- Quagmire slows down the monster, but does not remove the status change
- It seems to remove Decrease Agility when cast, but you can still cast Decrease Agility afterwards (it will have both SCs then and be a bit faster than normal)
