### ISSUE TITLE
Soul Destroyer Range

### ISSUE THREAD

**Issue by Playtester** [rathena/rathena#905]
Apparently on rAthena Soul Destroyer range was reduced to 7, but someone brought up some doubts that the range should only be 7 in renewal.

I tested on pre-renewal Aegis and the range is actually 9.

379,7,6,1,-1,0x8,0,10,1,yes,0,0,0,weapon,0,0x0, ASC_BREAKER,Soul Destroyer

Should be:
379,9,6,1,-1,0x8,0,10,1,yes,0,0,0,weapon,0,0x0, ASC_BREAKER,Soul Destroyer

Confirmed for pre-renewal.

You might want to test it for renewal as well just in case.
(Hint: 9 range means you can do a standing cast with 9 cells in between you and the monster.)

**Comment by reigneil** [comment]
lets see what skillinfolist have...
	[SKID.ASC_BREAKER] = {
		"ASC_BREAKER",
		SkillName = "±â°øÆ÷",
		MaxLv = 10,
		SpAmount = { 20, 20, 20, 20, 20, 30, 30, 30, 30, 30 },
		bSeperateLv = true,
		AttackRange = { 9, 9, 9, 9, 9, 9, 9, 9, 9, 9 },
		_NeedSkillList = {
			{ SKID.TF_DOUBLE, 5 },
			{ SKID.TF_POISON, 5 },
			{ SKID.AS_CLOAKING, 3 },
			{ SKID.AS_ENCHANTPOISON, 6 }
		}
	},

looks like your right...

**Comment by Playtester** [comment]
Ah, so in renewal it's 9 too?

**Comment by cydh** [comment]
it's from client's skillinfoz lua, it says 9, so must 9 range (for renewal)
