### ISSUE TITLE
alternative 3rd job sprite palette

### ISSUE THREAD

**Issue by joelolopez** [rathena/rathena#906]
20150916 client, latest rathena, when im using GX's alt sprite and i use the cloth color white, the color of the palette is different from whats displaying in character selection

for example
-i use official white palette for GX' alt sprite
-when i go to character selection , instead of white, the palette color is gold (color palette gold of the old GX sprite )

**Comment by icxbb-xx** [comment]
I think this problem the client issues, i have test but normal
official palette support 1-4 color only

![easycapture1](https://cloud.githubusercontent.com/assets/3500355/12347984/cb33abd6-bb95-11e5-9010-625467308d05.jpg)
![screenrathena test001](https://cloud.githubusercontent.com/assets/3500355/12347997/de4c45c0-
![screenrathena test003](https://cloud.githubusercontent.com/assets/3500355/12348004/ede0dca8-bb95-11e5-979a-32d9b0d980e7.jpg)
![screenrathena test005](https://cloud.githubusercontent.com/assets/3500355/12348006/ede96d46-bb95-11e5-8b6b-82d8fad86319.jpg)
![screenrathena test006](https://cloud.githubusercontent.com/assets/3500355/12348005/ede7a132-bb95-11e5-8013-e6a5d1f30bc6.jpg)
![screenrathena test007](https://cloud.githubusercontent.com/assets/3500355/12348007/ede9af18-bb95-11e5-9c3b-1857ab4e5be0.jpg)



bb95-11e5-87b4-f0cf194c1c1e.jpg)
![screenrathena test002](https://cloud.githubusercontent.com/assets/3500355/12347998/de7b43f2-bb95-11e5-9efd-cebd9c67974c.jpg)
