### ISSUE TITLE
Waterball / Jupitel Thunder double cast

### ISSUE THREAD

**Issue by Playtester** [rathena/rathena#907]
Waterball and Jupitel Thunder allow players to cast a second spell before they actually trigger and apply canact delay. I already have that implemented for Waterball, but it still doesn't work because we send a damage packet to the client right away which makes the client queue all skill packets until after the cast. To fix this, skill_attack should no longer be called at "castend" but instead only in the skilltimer.

Jupitel Thunder actually behaves the same way. It's damage and knockback comes a bit delayed so you can actually cast a spell before the target gets knocked back, allowing you to cast a second skill at increased range. It behaves almost exactly like Waterball. I conclude from that, that Jupitel is actually a timerskill like Waterball, not an instant skill.

Here is also a video from iRO that shows this behavior:
https://www.youtube.com/watch?v=nDO1KKxT3ig
1. Stone Curse only has a range of 1, yet it can be cast after Jupitel Thunder.
2. If you double cast Jupitel Thunder you can knock the enemy out of the screen.

Working on this at the moment.

**Comment by reigneil** [comment]
yeah on official server you can chain jupitel thunder by just spamming hotkeys and then hands off on your computer keyboard and see jupitel thunder trigger on its own. although not sure if there is a limit to this...

**Comment by Playtester** [comment]
Waterball double cast so we have that on video too: https://www.youtube.com/watch?v=VmDsFSMTk7o

**Comment by Playtester** [comment]
On official servers when casting waterball, actually waterball ground cells are deployed (they replace the deluge/suiton cells). These are then used up to form waterballs. This is the real reason why for example waterball doesn't work on Land Protector.

We need to simulate this behavior if you want to allow double cast, because double cast shouldn't actually mean double the hits, it should just recreate the already used up waterball cells and double the timer.

It also has other interesting aspects like being able to cancel waterball with Ganbantein and Land Protector. I wonder if it's possible to confirm this being possible somehow. Like Waterball starts -> cast LP -> waterball ends.

**Comment by Playtester** [comment]
Need to apply two more fixes after testing it thoroughly:
- Waterball cells can stack with themselves
- Waterball and Jupitel can shoot through icewalls
