### ISSUE TITLE
Incorrect weapon Attack

### ISSUE THREAD

**Issue by panko11** [rathena/rathena#909]
I did a test on bRO and rAthena  and noticed a bug in weapon attack follows the image
16005,P_Mace2,Eden Mace II,5,0,,0,163,,1,0,0x0004C5B2,63,2,2,2,40,0,8,{},{},{}
The script is correct 163 attack but to equip note the difference
BRO:
![bro bug](https://cloud.githubusercontent.com/assets/10385169/12375467/a00681f2-bcaa-11e5-90e3-3755ee586f75.png)
Rathena:
![rathena](https://cloud.githubusercontent.com/assets/10385169/12375468/a007c666-bcaa-11e5-9370-b6034b54fe8b.png)

Version: 22a9a74
Client : 20130807
model : renewal

**Comment by julia40124009** [comment]
maybe str add attack

**Comment by panko11** [comment]
if you need I do testing with other jobs

**Comment by cydh** [comment]
I mentioned this on dev chat, and @aleos89 is working for this issue already.
that difference because on our Renewal phase, the calculated weapon attack & equipment attack is showed in that window, that's shouldn't.

**Comment by esu1214** [comment]
This screen also showed that aspd is different?

**Comment by esu1214** [comment]
If only it is a status pannel problem, I have fixed it.
In status.h
[code]
#ifdef RENEWAL
+		clif_watk,
+		clif_watk2,
		watk,
		watk2,
		eatk,
#endif
...
#else
	unsigned int status_weapon_atk(struct weapon_atk wa, struct status_data *status);
+	unsigned int status_weapon_atk4clif(struct weapon_atk wa);
	unsigned short status_base_matk(struct block_list *bl, const struct status_data* status, int level);
#endif
[/code]

In pc.h
[code]
-	#define pc_rightside_atk(sd) ((sd)->battle_status.watk + (sd)->battle_status.watk2 + (sd)->battle_status.eatk)
+	#define pc_rightside_atk(sd) ((sd)->battle_status.clif_watk + (sd)->battle_status.clif_watk2 + (sd)->battle_status.eatk)
[/code]

In status.c
[code]
#else
+	base_status->clif_watk = status_weapon_atk4clif(base_status->rhw);
+	base_status->clif_watk2 = status_weapon_atk4clif(base_status->lhw);
	base_status->watk = status_weapon_atk(base_status->rhw, base_status);
	base_status->watk2 = status_weapon_atk(base_status->lhw, base_status);
	base_status->eatk = max(sd->bonus.eatk,0);
#endif
...
unsigned int status_weapon_atk(struct weapon_atk wa, struct status_data *status)
{
	float str = status->str;
	if (wa.range > 3)
		str = status->dex;
	// wa.at2 = refinement, wa.atk = base equip atk, wa.atk*str/200 = bonus str
	return wa.atk + wa.atk2 + (int)(wa.atk * (str/200));
}
+unsigned int status_weapon_atk4clif(struct weapon_atk wa)
+{
+	return wa.atk + wa.atk2;
+}
#endif
[/code]

**Comment by aleos89** [comment]
Related to #2126.
