### ISSUE TITLE
13.2 quests: getitem vs player overweight 

### ISSUE THREAD

**Issue by Akaineko-astasi** [rathena/rathena#910]
In the npc/quests/quests_13_2.txt we have some `getitem`s for items that weigh > 0 like `getitem 2782,1; //Ring_Of_Wise_King` and `getitem 7574+.@num,1;` at `jewel_13_2` function. But we do also need a player's current weight check there. When a player has no free weight (especially if he was overweighted during the dialog) and is to receive a quest item, an item isn't received and the quest continues, leaving a player no opportunity to attempt to get that item again. 

Latest commit: 6a62aab 
Mode: Renewal AND Pre-Renewal

**Comment by anacondaqq** [comment]
checkweight? checkweight2?

**Comment by Akaineko-astasi** [comment]
I think `checkweight(ItemID,1) || MaxWeight - Weight` checks  would be enough as in case of the Eden quests, wouldn't it? 

Though I don't know if this is so on officials or not.

**Comment by Playtester** [comment]
Why not just make global weight check in the core rather than putting it into every script that gives an item with weight, though?

Official servers had some really weird handling but unfortunately I can't remember it anymore. It was either the item dropping on the ground or going into the inventory anyway. Also there was a difference between maxweight reached and 100 different items reached.

**Comment by Akaineko-astasi** [comment]
Is that nessesary to copy any official behaviour in this case? 
Implementing the global weight check should be quite more handy I think, though I don't really know how this may be done >_<

**Comment by jezznar** [comment]
I certainly agree with @Playtester it take off the need to do additional weightchecks in scripts.

**Comment by Jeybla** [comment]
From script.c getitem:
```
			if ((flag = pc_additem(sd, &it, get_count, LOG_TYPE_SCRIPT)))
			{
				clif_additem(sd, 0, 0, flag);
				if( pc_candrop(sd,&it) )
					map_addflooritem(&it,get_count,sd->bl.m,sd->bl.x,sd->bl.y,0,0,0,0,0);
			}
```
There is already a global solutions. Items get dropped if the player has overweight. But items which shouldn't be able to drop are ignored. That's imo the best solution for now. We should stick to it and implement clean checks in our scripts :/

**Comment by spinzaku** [comment]
just encountered this problem in my server with the "Ring of the Wise King" quest

**Comment by Jeybla** [comment]
```getitem 7574+.@num,1;```
All jewel got weight 0.

For the Ring of the Wise King i'll create a pull request.
