### ISSUE TITLE
Bug: over thurst of whitesmith

### ISSUE THREAD

**Issue by Dark8008** [rathena/rathena#912]
I use Over Thurst but no effect !

Pre-renewal latest version
2014-10-22 client

**Comment by Playtester** [comment]
I can't confirm this:

No buff:
Normal Attack - 100 damage
Mammonite - 780 damage

Overthrust:
Normal Attack - 135 damage
Mammonite - 815 damage

Max Overthrust:
Normal Attack - 240 damage
Mammonite - 920 damage

Works as intended.

Though I noticed that Overthrust gives the same damage boost to party members than to self, is that working as intended? iROwiki says something else, though that's a really unreliable source.

**Comment by Playtester** [comment]
The bonus on party member is definitely bugged.

Tested on officials:

Player 1 / Player 2 both with Axe deal 128 damage on enemy.

P1 uses Power Thrust Level 1:

P1 - 135 damage
P2 - 135 damage

P1 uses Power Thrust Level 5:

P1 - 160 damage
P2 - 135 damage

Conclusion: Party members always only receive a 5% bonus regardless of level. The duration however is the same for all.

**Comment by Playtester** [comment]
Power-Thrust - Works only on characters with (any) weapon equipped
Power Maximize - Always works
Adrenaline Rush - Only works on characters with Mace or Axe, gets removed on unequip
