### ISSUE TITLE
Magic Rod display

### ISSUE THREAD

**Issue by Playtester** [rathena/rathena#914]
I don't think Magic Rod should display when you cast it, but instead, display when it activates, like Auto Counter.

Couldn't really find info on it other than on iROwiki (too bad search doesn't work on our bug tracker anymore):
http://irowiki.org/classic/Magic_Rod

"Magic Rod functions much like the Knight skill Counter Attack. You must use Magic Rod when you expect the incoming spell to hit you. **There is no cast bar to show you the duration of Magic Rod, but you will know that you succeeded when you receive no damage and gain SP instead.** The difference to Counter Attack is, that you can absorb multiple spells during the duration, instead of a single one."

When there was an animation, the bold sentence wouldn't written like that.

Edit: Actually thinking about it if there was an animation when it activates it also wouldn't be written like that. Hmm, maybe already working as intended

Maybe someone can confirm?

**Comment by Atemo** [comment]
On renewal it display the magic rod skill name and the animation every time you cast it, "Magic Rod !!". When the skill is activated it displays the sp number you get in blue above the head if you're not full sp.
Tested on iRo.

**Comment by Playtester** [comment]
Thanks for testing @Atemo.
