### ISSUE TITLE
Statis not working

### ISSUE THREAD

**Issue by playpsro** [rathena/rathena#918]
I'm use git version in 3 November 2015

I have test, use warlock, pvp mode, and versus 1 enemy, in area 19x19
after i'm using statis, enemy still can casting the skill.
because in irowiki said, have fix 5 second duration of effect this skill.
how to fix it??

source : http://irowiki.org/wiki/Stasis

**Comment by aleos89** [comment]
Our current implementation is only setup to block specific skills. It would be nice to test this on kRO again.

**Comment by playpsro** [comment]
what skill blocked by statis? yesterday i test using Gate of hell sura skill

**Comment by Playtester** [comment]
There's a typo in the skill_db, but it's a setting there:

//    0x00020 - skill blocked by statis

2343,1:2:3:3:4:4:5:5:6:7,8,1,-1,0,0,10,-7,yes,0,0,0,weapon,0,**0x0**,	SR_GATEOFHELL,Gate of Hell

Gate of Hell is currently defined to not be blocked by Stasis.

**Comment by playpsro** [comment]
ok thx sir :D
