### ISSUE TITLE
Marsh of Abyss Bug

### ISSUE THREAD

**Issue by playpsro** [rathena/rathena#919]
I'm use git version in 3 November 2015

I Have test marsh of abyss skill from warlock its not full working.
this skill only reduce movement speed but not remove speed boosting skill (ex. cart boost, inc.agi) when used

source : http://irowiki.org/wiki/Marsh_of_Abyss

**Comment by aleos89** [comment]
It currently removes Increase Agi, Wind Walk, and ASPD potions. Would be nice to know all the other statuses it removes.

**Comment by playpsro** [comment]
![screenprivateserv003](https://cloud.githubusercontent.com/assets/15665450/12499284/c3431358-c0db-11e5-9e1f-7934655bbec7.jpg)


this is you mean??

	case SC_MARSHOFABYSS:
		status_change_end(bl, SC_INCAGI, INVALID_TIMER);
		status_change_end(bl, SC_WINDWALK, INVALID_TIMER);
		status_change_end(bl, SC_ASPDPOTION0, INVALID_TIMER);
		status_change_end(bl, SC_ASPDPOTION1, INVALID_TIMER);
		status_change_end(bl, SC_ASPDPOTION2, INVALID_TIMER);
		status_change_end(bl, SC_ASPDPOTION3, INVALID_TIMER);
		break;

source : src/map/status.c/line_8361 ?

but look my SS, still have inc agi and blessing effect
