### ISSUE TITLE
Spirit Control of Sorcerer Not Full Working

### ISSUE THREAD

**Issue by playpsro** [rathena/rathena#922]
Spirit Control Skill were reset every time Sorcerer's change a map, while it should be only happened when you disconnected .

How to fix it/ change to reset if only player disconnected ?

**Comment by secretdataz** [comment]
I believe this bug has been fixed some time ago.
Are you sure you are running the latest rAthena?

**Comment by aleos89** [comment]
This was fixed in feb885c.
