### ISSUE TITLE
Pre-renewal zero damage on elemental armor

### ISSUE THREAD

**Issue by Playtester** [rathena/rathena#924]
In official pre-renewal it is possible to reduce damage to 0 with elemental armor, even if the resist is not 100%.

For example if you have high MDEF/INT and Ice Titan casts Frost Diver on you, you take only 1 damage. But if you now equip a water armor which makes you take only 25% water damage, the damage gets reduced to 0 (displays as "MISS" on the client).

This does not work on rAthena. Damage remains 1 at the moment.

**Comment by Playtester** [comment]
On the other hand racial reductions and size reductions do not push 1 damage to 0 on official servers, but that works on rAthena.
So it's exactly the wrong way around.

**Comment by Playtester** [comment]
@aleos89 
I noticed you changed this from:
```c
return (int64)damage*ratio/100;
```
To:
```c
	if (ratio < 100)
		damage = damage - (damage * (100 - ratio) / 100);
	else
		damage = damage + (damage * (ratio - 100) / 100);
```
Was there any reason for that? Because this way it rounds down the reduction...

**Comment by aleos89** [comment]
I can't remember now off the top of my head. I'd have to go back and check.

**Comment by Playtester** [comment]
Testing on renewal - it doesn't work there, damage is always at least 1.

So this is only a bug in pre-re.
