### ISSUE TITLE
Several Errors on Izlude Quest & Armors

### ISSUE THREAD

**Issue by lyleham** [rathena/rathena#925]
[errorquest.txt](https://github.com/rathena/rathena/files/101710/errorquest.txt)

**Comment by secretdataz** [comment]
Invalid issue. Update your database.

**Comment by lyleham** [comment]
Hi secret dataz, how do I do it? Thanks!

**Comment by secretdataz** [comment]
Did you use git or svn to download rAthena? If so, use command `git pull` or `svn update` to update your rAthena.
Otherwise, replace your db with latest rAthena's db.
