### ISSUE TITLE
[Client BUG] Change Material + Analyze Element (Genetic/Socerer)

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#929]
The ability is not working. When used nothing happens. If you try to use again the ability is locked . Stop unlock need to relog the character. If used will be missed again. 

No message is returned on error. I noticed that this problem also occurs with Elemental Analysis of Socerer , which when used bug skill and nothing happens more.

I realized that it seems is linked with exchange of items , which is what the two skills do.

I use version of rAthena this week and 2015-05-13aRagexe .

List of items to test IDs:
http://irowiki.org/wiki/Change_Material
http://irowiki.org/wiki/Analyze_Element

**Comment by cydh** [comment]
Client related maybe

**Comment by Badarosk0** [comment]
Something missing from customer maybe? Can it be something in the diff ?

**Comment by Lemongrass3110** [comment]
Seems to be a setup problem.
Try setting your packet version in packet_db manually:
```
packet_db_ver: 52
packet_keys_use: 52
```

![screenrathena018](https://cloud.githubusercontent.com/assets/3517879/12576807/9102a69a-c416-11e5-8408-3aeeafd0e4f5.jpg)

**Comment by Badarosk0** [comment]
No, I configured this way and is not working. Test your skill completely. Try to create the item you will see that is rather buggy . The bug continues and is not functional . It will only be observed if performing the exchange.

**Comment by Sweet520** [comment]
Yes, I have the same problem.

When I use the skills called Four Spirit Analysis(SO_EL_ANALYSIS), after the selected items, press "Ok" or "Cancel" are unable to get items, and people will not be able to use the skills and items, until the relogin.

I am using the 2015-09-16 client, when I change 2014-10-22 client, the skills work properly.

**Comment by Lemongrass3110** [comment]
Sorry @Badarosk0 I misunderstood your description. I thought you were saying, that it was not working at all first and just tested the beginning of the skill.
It should be fixed now!
