### ISSUE TITLE
can not buy cashshop

### ISSUE THREAD

**Issue by cold-hr** [rathena/rathena#931]
i'm using last git and use exe 2012-04-10

not found NPC ,Buy failure

this script
payon,171,142,4	cashshop	Kafra Shop Employee	116,12900:1000,12901:200,12902:1000,12909:100,12910:100,12911:1500,12922:150,7619:100,7620:100,12916:150,12917:150,12915:100,12918:100,12913:125,12914:125,13553:50,12903:100,12904:100,12905:100,12906:100,12907:100,12908:100,7776:50

**Comment by hnomkeng** [comment]
What rathena version ?

**Comment by cold-hr** [comment]
last git   15541

**Comment by hnomkeng** [comment]
Reverted https://github.com/rathena/rathena/commit/11f42f27ab4b9eb54c6b12e95b4ff8ec077fa157

**Comment by cydh** [comment]
Confirmed, I suspect my old changes. :P
To temporary fix this, u can put 1 item in item_cash_db.txt

**Comment by cold-hr** [comment]
ok thank  @cydh  and @hnomkeng
