### ISSUE TITLE
Zero damage on cardfix

### ISSUE THREAD

**Issue by Playtester** [rathena/rathena#935]
Split from: #924 

On official servers, both pre-renewal and renewal (already tested and confirmed on both), resistances from cards are unable to reduce damage to 0 unless they are 100%.

On rAthena however, the moment you get even just 1% resistance, it makes 1 damage drop to 0, making all attacks miss.

This is because on rAthena we round down the damage while on official servers I assume the reduction is actually rounded down.

I also noticed that our reductions are based on "1/1000" whereas Herc made an update to bases them on "1/100". That would also be interesting to test.
A way to test this: Get Krieger Suit and Berdysz and test damage in PVP. Because it's 7% reduction and 13% reduction, the rAthena version would get a cardfix value of 809, where the Herc version would get a cardfix value of 80. That's 19.1% reduction on rA and 20% reduction on Herc. That gives a difference big enough to test which one fits to the damage on official servers.

**Comment by Playtester** [comment]
Err, my tests on renewal had some really weird result.

It seems that Berdysz reduces the WeaponATK by 13% whereas reductions vs. Demi Human like from Poo Poo Hat, also affected StatusATK!

When I have 100 StatusATK, Poo Poo Hat reduces it to 90.
When I have 102 StatusATK, Poo Poo Hat reduces it to 92.
Berdysz has no effect, 102 damage stays 102 damage if I'm unarmed.

But once you add a weapon the damage doesn't make any sense... I used counter dagger to prevent variance and result is.
ATK: 50+140(+1)
DEF: 55+0

Damage no gear: 246
Damage vs. Berdysz (13% size): 222
Damage vs. Poo Poo Hat (10% race): 214
Damage vs. Both: 193

Since race affect StatusATK and I have 100, it will be reduced to 90. So we need to add 10...

Damage vs. Poo Poo Hat (10% race): 224
Damage vs. Both: 203

Means 13% reduction reduces weaponATK by 24 and 10% reduction reduces weaponATK by 22.
13% + 10% = 43

It doesn't really fit together. =/

**Comment by cydh** [comment]
people on idRO said it clearly already.
http://irowiki.org/wiki/ATK

once u said confirm it, u don't need to test any further (it'll waste your time).
indirect test, I self, feel there are many damage differences while 'playing' on Aegis + idRO against current rAthena.
u can make new branch for this "big" change.

**Comment by Playtester** [comment]
Well you can never trust what others you don't know say, always have to test yourself to make sure. Also iROwiki is very often wrong. You shouldn't rely on that.

I also checked idAthena and the part I'm currently investigating is the same as here, so it must be wrong too (I already confirmed that reduction needs to be rounded down and not the damage). I don't wanna do big changes, I just want to find out how Gravity applies the cardfix values. I'll try to get someone I trust to test on pre-renewal because the formula is much easier there.

**Comment by Playtester** [comment]
Okay after thorough testing, I finally found out the formula that Aegis uses for cardfix.

It is: damage = damage - (int)((damage * (1000 - cardfix)) / 1000);

Proof:
Fixed Damage = 521
Equip: 10% range resist + 5% ele resist
Resulting Damage = 446

The only way this fits if:
- We use an exact value for cardfix (not rounded to next %)
- The reduction gets rounded down and not the damage
