### ISSUE TITLE
Neutral Barrier bug？

### ISSUE THREAD

**Issue by idamonli** [rathena/rathena#939]
Now I find that if player A who is outside the scope attacks player B,player B will get hurt.
But if player A who is inside the scope attacks player B, player B will not get hurt. Is that a bug?

**Comment by stealth62** [comment]
Please provide as much information such as screenshots git hash, renewal/prerenewal mode, client version so they can help you in your problem. In your stated above we cant determine if its long range normal attack or skill attack.

**Comment by aleos89** [comment]
Yes, this is official behavior. All damage is nullified, unless the damage can never miss.
