### ISSUE TITLE
HP/SP Fully Restores After Relogging or Going to Character Select

### ISSUE THREAD

**Issue by demonican** [rathena/rathena#941]
HP/SP Fully Restores After Relogging or Going to Character Select

**Comment by Lemongrass3110** [comment]
Please consider reading our guidelines for bug reports here:
https://rathena.org/board/topic/104361-github-issues-and-rathena-bug-reporting/

Also please provide a little more information how we can test and reproduce your issue.
Thank you.

**Comment by aleos89** [comment]
Been playing around all weekend and this never happened to me (using version a6811c7).
