### ISSUE TITLE
EXP On Max Level

### ISSUE THREAD

**Issue by cydh** [rathena/rathena#942]
Refer to https://github.com/HerculesWS/Hercules/pull/1097
Instead just sending 'simple' 99,999,999 to client, there are some points why 'they' --Official RO-- does that.

Another points from me...

1. Player on max level, still can obtained EXP (both for Base & Job) until they're 100% (99,999,999/99,999,999).
2. Why still can they get EXP on max level? Even only ONE reason (afaik), this is a good quality reason. LG_INSPIRATION needs 1% EXP cost, and yes my friend (on idRO told me) loss ~1,000,000 EXP on 175 each cast skill.
3. When it reach 100% (99,999,999/99,999,999), it really sends 0 EXP to client.
4. When player on max level, the EXP log on client feature is really tells you that obtained 0 Base EXP and 0 Job EXP, but (again) in OpenKore u will see the 'real' EXP gained, just like u aren't max level player just killed a mob.

**99/50 with 100% Base EXP**
![screenshot_26](https://cloud.githubusercontent.com/assets/4016864/12745079/28fb47aa-c9ca-11e5-93ef-6b2adf61a136.png)
![screenshot_27](https://cloud.githubusercontent.com/assets/4016864/12745082/2b96bf08-c9ca-11e5-8a45-64f4bbb15091.png)
![screenshot_28](https://cloud.githubusercontent.com/assets/4016864/12745085/2d7c7240-c9ca-11e5-8b1e-e61d920fdeb1.png)
![screenshot_33](https://cloud.githubusercontent.com/assets/4016864/12745768/a30a9ca0-c9cd-11e5-8c9b-db1ae01d68e3.png)
![screenshot_35](https://cloud.githubusercontent.com/assets/4016864/12745770/a8181c68-c9cd-11e5-9be2-75b47e746a5f.png)
![screenshot_36](https://cloud.githubusercontent.com/assets/4016864/12745771/a959c392-c9cd-11e5-9ca5-cb2d1d4a7ca4.png)

**99/50 with < 100% Base EXP, ongoing**
![screenshot_29](https://cloud.githubusercontent.com/assets/4016864/12745110/366d9f96-c9ca-11e5-80bd-41d78e225ff3.png)
![screenshot_30](https://cloud.githubusercontent.com/assets/4016864/12745112/37ccb2f0-c9ca-11e5-9e73-b7987ee92860.png)
![screenshot_31](https://cloud.githubusercontent.com/assets/4016864/12745114/39b7ffac-c9ca-11e5-8558-dca606ec3a78.png)

**NOTE**
99,999,999 for Base EXP
999,999,999 for Job EXP

**Comment by Playtester** [comment]
Are you sure about the 99,999,999 thing? I thought it only goes to 99,999,998. At least that's what I remember the client displayed for my max level characters on the login screen?

**Comment by cydh** [comment]
Don't worry, I don't need you to believe me.
I added the OpenKore SSs btw.

**Comment by Playtester** [comment]
Plant damage is still 2. It sends 0*2 to the client but does 1 damage.

But ok I stand corrected, so 99,999,999 can be displayed. Btw if that open kore SS is correct then max for Job Exp is 10 times higher (999,999,999).

Yes, I agree we need to keep track for Base Exp after max level. I think it's also needed for some Super Novice thingy?

**Comment by cydh** [comment]
>But ok I stand corrected, so 99,999,999 can be displayed. Btw if that open kore SS is correct then max for Job Exp is 10 times higher (999,999,999).

Yes it is. as u can see on SS, I still get Job EXP, and if it's only 99,999,999, it should be 100% long time before the Base EXP went 100%


------------
http://irowiki.org/wiki/Super_Novice#Life_After_Level_99
## Life After Level 99
* Upon reaching Base Level 99, a Super Novice has a few new tricks up its sleeves.
* At the moment of reaching Level 99, a Super Novice gains +2000 Max HP permanently. This bonus is affected by cards, but not by VIT.
The two Super Novice Secrets which depend on your current % of Base EXP can still be used, but you must continue leveling to gain the EXP required.
  * To Fury, you must gain n × 10.0x million EXP (where n = 1,2,3,...).
  * In order to use Mental Strength you must gain an additional 99 million EXP or more after obtaining Level 99 or 150.
  * Upon attaining 99,999,999 EXP (as shown on the character Select screen), you will be able to use both the novice chant Fury and Mental Strength upon 0 HP.
  * In order to go beyond Level 99, you have to complete a Quest.

**Comment by cydh** [comment]
Just a little correction from me, `0x07f6` always sends 0 EXP if player reach max level.
