### ISSUE TITLE
Biolab Gear Exchange

### ISSUE THREAD

**Issue by vakhet** [rathena/rathena#949]
Description of quest and its script doesn't match
http://irowiki.org/wiki/Biolab_Gear_Exchange
npc/re/scripts_athena.conf
According to description, item Assassin Handcuffs (id 2892) should be exchanged with 100/50/35, but in script its price is 300/300/400
Likewise, item Salvage Cape (id 2582) should be exchanged with 300/300/400, but in script its price is 100/50/35

**Comment by secretdataz** [comment]
Confirmation from tRO site.
http://ragnarok.playpark.com/th/QuestLibraryContent/12662

**Comment by cydh** [comment]
calling @Atemo to confirm and follow up this

**Comment by Atemo** [comment]
@Atemo (can I get a notification from myself?) confirm this
