### ISSUE TITLE
Freeze, Stun, Sleep and Stone

### ISSUE THREAD

**Issue by Playtester** [rathena/rathena#950]
When fixing #948 I noticed several things that have been coded to happen when a status change starts. This includes standing up, cancelling the current spell, ending dancing, stop moving and stop attacking. I started testing this on Aegis and noticed that some of these things don't happen at all.

Freeze Normal: Only stops attacking.
Freeze Dancing: Stops movement (not displayed) and dancing.

Stun Normal: Only stops attacking.
Stun Dancing: Stops movement (not displayed) and dancing.

Sleep Normal: Only stops attacking (displays you stopping but you keep moving server-sided)
Sleep Dancing: Displays you stopping, but you will still move and you can actually see the dance area moving.

Stone Phase 1 Normal: Only stops attacking.
Stone Phase 1 Dancing: Does nothing (can't attack).

Stone Phase 2 Normal: Does nothing (can't attack).
Stone Phase 2 Dancing: Stops movement (not displayed) and dancing.

* - Interesting to note is that while these don't cancel any spellcasting, the spells themselves won't deal damage for as long as these status changes are active.

* - None of these make me stand up at all! Wonder why that was coded?

**Comment by Barigas** [comment]
Same is with other Snare effects(like Hunter's Ankle Snare trap) and Sura's Cursed Circle: on Aegis it does not stop target from moving, making it not very imba skill on officials.
All these statuses just don't allow you move anymore(it is like server just ignores your commands to move), though the character will continue moving to the cell. In most of the cases you actually need to receive damage in order to be stopped. It is one of the key aspects in WoE.

**Comment by Playtester** [comment]
For Ankle Snare it's not fully true. It does have a "Knockback into trap center" effect that makes you stop. However if you are immune to knockback (boss, WoE), you won't be stopped.

It's already correctly implemented for Ankle Snare.

For the status changes, this happens even in PVM, though! e.g. Scream / Frost Joke while normal non-boss monsters are moving = continue moving to target cell and also in PVP without knockback immune = continue walking.

And yes, getting hit makes you stop and even stand up!

**Comment by Barigas** [comment]
Nice! :) Two key things worth implementing(I don't have an opportunity to test rAthena now) are:
1)Implement "continue walking" for Cursed Circle.
2)Vacuum Extreme(Sorcerer) does not affect targets which are (portal immune? like when you enter a portal in WoE and can not receive damage some seconds), so if you change portal in WoE, there is a Vacuum Extreme standing there, you will still be able to "continue walking"(unless you are hit) and stop in the end(until Vacuum debuff on you expires). Just like with Ankle Snare in WoE.

**Comment by Playtester** [comment]
I'm not familiar with renewal so I'm hesitant about changing anything renewal related (plus after I got this fixed I'm afraid I'll first have to look the monster skills, they are completely bugged at the moment..). Maybe make a separate bug report for those?
