### ISSUE TITLE
Players spawn on "Random" maps when newly created.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [rathena/rathena#955]
I only wanted 1 spawn spot, players ended up spawning on random maps that were not even defined in the start_point_pre.

Interestingly enough, dungeon maps mostly where they get killed ASAP from agro monsters....
It came as a bit of a shock to everyone involved.

charserv_config.start_point_count is 142 after all configs are loaded.
So understandably the code when creating character goes to an overflowed/garbage data area and brings back who knows what.

start_point_idx = rand() % charserv_config.start_point_count;
mapindex_id2name(charserv_config.start_point[start_point_idx].map)

I have specified start_point_pre in my import char conf like so

```
start_point_pre: new_1-1,53,111
```

It was also specified in the char_athena.conf.

```
start_point_pre: new_1-1,53,111:new_2-1,53,111:new_3-1,53,111:new_4-1,53,111:new_5-1,53,111
```

And I put in some debug code to output the value `charserv_config.start_point_count`.

In char.h I define MAX_STARTPOINT to 1.
```
#define MAX_STARTPOINT 1
```

My packet ver is #define PACKETVER 20120410

This is the output following adding the following line into the function char_config_split_startpoint.
```
charserv_config.start_point_count = 0;
```

char_config_split_startpoint code "Modified".
```
/**
 * Split start_point configuration values.
 * @param w2_value: Value from w2
 */
static void char_config_split_startpoint(char *w2_value)
{
	char *lineitem, **fields, config_name[20];
	int i = 0, fields_length = 3 + 1;

	charserv_config.start_point_count = 0;

	memset(config_name, 0, sizeof(config_name));

#ifdef RENEWAL
	strcat(config_name, "start_point");
#else
	strcat(config_name, "start_point_pre");
#endif

	fields = (char **)aMalloc(fields_length * sizeof(char *));
	if (fields == NULL)
		return; // Failed to allocate memory.
	lineitem = strtok(w2_value, ":");

	while (lineitem != NULL) {
		int n = sv_split(lineitem, strlen(lineitem), 0, ',', fields, fields_length, SV_NOESCAPE_NOTERMINATE);

		if (n + 1 < fields_length) {
			ShowDebug("%s: not enough arguments for %s! Skipping...\n", config_name, lineitem);
			lineitem = strtok(NULL, ":"); //next lineitem
			continue;
		}
		if (i > MAX_STARTPOINT) {
			ShowDebug("%s: too many start points, only %d are allowed! Ignoring parameter %s...\n", config_name, MAX_STARTPOINT, lineitem);
		} else {
			charserv_config.start_point[i].map = mapindex_name2id(fields[1]);
			ShowDebug("%s: Start point %i set to '%s'\n", config_name, i, lineitem);
			if (!charserv_config.start_point[i].map) {
				ShowError("Start point %s not found in map-index cache. Setting to default location.\n", charserv_config.start_point[i].map);
				charserv_config.start_point[i].map = mapindex_name2id(MAP_DEFAULT_NAME);
				charserv_config.start_point[i].x = MAP_DEFAULT_X;
				charserv_config.start_point[i].y = MAP_DEFAULT_Y;
			} else {
				charserv_config.start_point[i].x = max(0, atoi(fields[2]));
				charserv_config.start_point[i].y = max(0, atoi(fields[3]));
			}
			charserv_config.start_point_count++;
		}
		ShowDebug("Iteration %i\n", i);
		lineitem = strtok(NULL, ":"); //next lineitem
		i++;
	}

	ShowDebug("%s: Start point count %hi\n", config_name, charserv_config.start_point_count);
	aFree(fields);
}
```

My Debug output of the count.

> [Debug]: start_point_pre: Start point 0 set to 'new_1-1'
> [Debug]: Iteration 0
> [Debug]: start_point_pre: Start point 1 set to 'new_2-1'
> [Debug]: Iteration 1
> [Debug]: start_point_pre: too many start points, only 1 are allowed! Ignoring parameter new_3-1...
> [Debug]: Iteration 2
> [Debug]: start_point_pre: too many start points, only 1 are allowed! Ignoring parameter new_4-1...
> [Debug]: Iteration 3
> [Debug]: start_point_pre: too many start points, only 1 are allowed! Ignoring parameter new_5-1...
> [Debug]: Iteration 4
> [Debug]: start_point_pre: Start point count 141
> [Status]: Character server IP address : 121.99.217.11 -> 121.99.217.11
> [Debug]: start_point_pre: Start point 0 set to 'new_1-1'
> [Debug]: Iteration 0
> [Debug]: start_point_pre: Start point count 1

This does not answer the question, why is it 141 from the get go......
Maybe something else is overflowing into charserv_config.start_point_count.

Sorry but, I can't debug with breakpoints right now.
But I will leave this here so I can try debugging another day.

**Comment by aleos89** [comment]
I have a cleanup which is sort of tied in with another commit!

**Comment by LiamKarlMitchell** [comment]
Ah cool, thanks for the reply, i'm new to rAthena but used to tinker around with eAthena years ago.

**Comment by joelolopez** [comment]
confirmed... my character spawned in the area full of orc archers  ahahah! clock tower if im not mistaken hahahaha! but sometimes my character spawned in the right place "intro"
