### ISSUE TITLE
Map server crash on GM evil clone

### ISSUE THREAD

**Issue by Spenon** [rathena/rathena#958]
I have this error provided by the GDB please click the link for the image.

and the quoted one is my mob.c and i commented the line specifying the error

[CLICK THIS LINK FOR THE GDB IMAGE](http://i66.tinypic.com/f058g.jpg)

> 		//Skill used. Post-setups...
		if ( ms[ i ].msg_id ){ //Display color message [SnakeDrak]
			struct mob_chat *mc = mob_chat(ms[i].msg_id);
			char temp[CHAT_SIZE_MAX];
 			char name[NAME_LENGTH];
 			snprintf(name, sizeof name,"%s", md->name);
 			strtok(name, "#"); // discard extra name identifier if present [Daegaladh]
 			snprintf(temp, sizeof temp,"%s : %s", name, mc->msg); //THIS IS LINE 3448 in mob.c
			clif_messagecolor(&md->bl, mc->color, temp);
		}
		if(!(battle_config.mob_ai&0x200)) { //pass on delay to same skill.
			for (j = 0; j < md->db->maxskill; j++)
				if (md->db->skill[j].skill_id == ms[i].skill_id)
					md->skilldelay[j]=tick;
		} else
			md->skilldelay[i]=tick;
		map_freeblock_unlock();
		return 1;
	}
	//No skill was used.
	md->skill_idx = -1;
	return 0;
}

i'm having map server crash regarding this. i provided the gdb. can someone help me regarding the cause of the map crash?

**Comment by Playtester** [comment]
Sorry, accidentally linked to wrong issue. Reopened.

**Comment by Spenon** [comment]
@Playtester hi sir, okay. but do you any fix regarding this issue?

**Comment by Playtester** [comment]
Not really working this one, no.

Not sure what's wrong, seems like it fails at retrieving the chat it should send to the client? Did you change something about mob chat? If you don't need it you could just comment out that part.

**Comment by Spenon** [comment]
@Playtester do you know where i can find that? as far as i know i did not change anything on the mob chat but i could double check. and if i commented that out, that's just the line i'll comment out right? anyway, it seems most bugs from the latest are from evilclone. i also encounter assassin cross and stalkers making the person being hit "hide".

**Comment by Playtester** [comment]
Unfortunately I don't really know how mob chat works, but if you comment it out, you should comment out the whole if():
```    if ( ms[ i ].msg_id ){ //Display color message [SnakeDrak]
        struct mob_chat *mc = mob_chat(ms[i].msg_id);
        char temp[CHAT_SIZE_MAX];
        char name[NAME_LENGTH];
        snprintf(name, sizeof name,"%s", md->name);
        strtok(name, "#"); // discard extra name identifier if present [Daegaladh]
        snprintf(temp, sizeof temp,"%s : %s", name, mc->msg); //THIS IS LINE 3448 in mob.c
        clif_messagecolor(&md->bl, mc->color, temp);
    }```

**Comment by aleos89** [comment]
Did you happen to change anything in db/mob_chat_db?

**Comment by aleos89** [comment]
No response for 2 months. GM evil clone doesn't even have any relation to the mob chat system. I also couldn't get the server to crash from monsters that have defines in the mob_chat_db already.
