### ISSUE TITLE
Please confirm Mistress Card 's effect in PRE-RE mode

### ISSUE THREAD

**Issue by CairoLee** [rathena/rathena#962]
Hi Everyone.

In ```db\pre-re\item_db.txt``` We can see "Mistress Card" [ID: 4132] script like this:
```bonus bNoGemStone,0; bonus bUseSPrate,25;```

Please confirm in pre-re mode ```bonus bNoGemStone,0; ``` Should be changed to ```bonus bNoGemStone,1; ```?

**Comment by Atemo** [comment]
According to the docs the number is meaningless
[https://github.com/rathena/rathena/blob/master/doc/item_bonus.txt#L434](url)
