### ISSUE TITLE
[pre-re] [Do not work] bonus2 bAddEle,e,x; +x% physical damage against element e

### ISSUE THREAD

**Issue by anacondaqq** [rathena/rathena#964]
Hello:
> bonus2 bAddEle,e,x;       		+x% physical damage against element e
not working anymore.

pre-re
rev: 7c5bda2978f0833915ab3eb8f9f66b1608f3f9c8
packet_ver; 30 / 2012-04-10
no source mods.

How reproduce
--------------------
* Item kaho card 2pcs
* @ spawn 1194 1

try with and without cards, you will see no difference (i was test it from assasin cross)

**Comment by anacondaqq** [comment]
related to 

```
#define APPLY_CARDFIX(damage, fix) { (damage) = (damage) - (int64)(((damage) * (1000 - (fix))) / 1000); }
```

Card bonus works fine for Bows, but do not working for weapons.

**Comment by Playtester** [comment]
Hmm strange, I thought I had tested with Hydra card which goes through the same code as elemental damage increase. o.o

I'll look into it when I'm at home. Can't see any error in the code by just looking at it...

**Comment by Playtester** [comment]
This bug doesn't have anything to do with my update.

It was added through this update: https://github.com/rathena/rathena/commit/c4fe3be0a13b6dfa993a9d07029735c4f4c16164

+	memset(sd->magic_addele, 0, sizeof(sd->magic_addele));
+	memset(sd->right_weapon.addele, 0, sizeof(sd->right_weapon.addele));
+	memset(sd->left_weapon.addele, 0, sizeof(sd->left_weapon.addele));

This resets all the bonuses from pc_bonus...
