### ISSUE TITLE
GN_CARTCANNON element calculate * 2

### ISSUE THREAD

**Issue by julia40124009** [rathena/rathena#965]
https://github.com/rathena/rathena/blob/master/src/map/battle.c#L5427
and
https://github.com/rathena/rathena/blob/master/src/map/battle.c#L2776

target mobId : 1768 (ghost Lv 3)
Holy element damage 100%
ghost element damage 175%

Real damage output
1.Holy element damage : 251027
2.ghost element damage : 769118

251027 \* 1.75 \* 1.75 = 768770
but should 
251027*1.75 = 439297

version : https://github.com/rathena/rathena/commit/7c5bda2978f0833915ab3eb8f9f66b1608f3f9c8
client : 20130807
model : renewal

**Comment by RagnarokNova** [comment]
Confirmed.

Aegis: http://i.imgur.com/zl9R6hW.png

rA: http://i.imgur.com/SSJ2BO5.png

**Comment by Playtester** [comment]
Because battle_attr_fix is called everywhere. XD

1.
```c
			//Forced to its element
			wd.damage = battle_attr_fix(src, target, wd.damage, right_element, tstatus->def_ele, tstatus->ele_lv);
```

2.
```c
				case GN_CARTCANNON:
				case KO_HAPPOKUNAI:
					//Forced to ammo's element
					wd.damage = battle_attr_fix(src, target, wd.damage, (sd && sd->bonus.arrow_ele) ? sd->bonus.arrow_ele : ELE_NEUTRAL, tstatus->def_ele, tstatus->ele_lv);
					break;
```

3.
```c
		case GN_CARTCANNON: // Cart Cannon gets forced to element of cannon ball (neutral or holy/shadow/ghost)
			wd.damage = battle_attr_fix(src, target, wd.damage, (sd && sd->bonus.arrow_ele) ? sd->bonus.arrow_ele : ELE_NEUTRAL, tstatus->def_ele, tstatus->ele_lv);
			break;
```

Though the comment mode indicate that it is intentional? o.o
```#ifdef RENEWAL
	// forced to neutral skills [helvetica]
	// skills forced to neutral gain benefits from weapon element
	// but final damage is considered "neutral" and resistances are applied again```
It says "again".

**Comment by julia40124009** [comment]
delete this code can correct damage
but I think it is not a good way
```
case GN_CARTCANNON: // Cart Cannon gets forced to element of cannon ball (neutral or holy/shadow/ghost)
            wd.damage = battle_attr_fix(src, target, wd.damage, (sd && sd->bonus.arrow_ele) ? sd->bonus.arrow_ele : ELE_NEUTRAL, tstatus->def_ele, tstatus->ele_lv);
            break;
```

**Comment by Vomaito** [comment]
also this is for Acid Demostration. Ghost reduction is like 75% when in tables is only 25%.
Same code.

> Because battle_attr_fix is called everywhere.

**Comment by spinzaku** [comment]
Any updates on this ? or any temporary fix?

**Comment by slyx88** [comment]
This will force the SC_ENCHANTARMS status to revert to cannon ball's property. does not  look clean but work for me
under battle.cpp find this:

`	switch( skill_id ) {
		case GS_GROUNDDRIFT:
			element = wd->miscflag; //element comes in flag.
			break;
		case LK_SPIRALPIERCE:
			if (!sd)
				element = ELE_NEUTRAL; //forced neutral for monsters
			break;
		case LG_HESPERUSLIT:
			if (sc && sc->data[SC_BANDING] && sc->data[SC_BANDING]->val2 > 4)
				element = ELE_HOLY;
			break;
		case RL_H_MINE:
			if (sd && sd->flicker) //Force RL_H_MINE deals fire damage if activated by RL_FLICKER
				element = ELE_FIRE;
			break;`

add this:
`		case GN_CARTCANNON:
                case NC_ARMSCANNON:
			if(sc && sc->data[SC_ENCHANTARMS])
				element = sd->bonus.arrow_ele;`

**Comment by teededung** [comment]
Please fix this bug. After rebalancing https://github.com/rathena/rathena/pull/3284 they get more stronger...
