### ISSUE TITLE
Cannot progress with the Eclage quests

### ISSUE THREAD

**Issue by Tokeiburu** [rathena/rathena#966]
In npc\re\quests\quests_eclage.txt, the functions WeightBigQuest, CheckBurglary, PranksterDiag, Wallnotes and EclageinEntrance do not have a return statement, which gets the script stuck and prevents you from progressing.

**Comment by Atemo** [comment]
I don't know if it was before or after the script engine update or if I didn't test this possibility..
anyway note :

````
function	script	F_test1	{
	// stop the script
}

izlude,99,99,5	script	function test1	56,{
	F_test1;
	mes "You CAN'T see this message.";
	close;
}
````

````
izlude,99,101,5	script	function test2	56,{
function F_test2;
	F_test2;
	mes "You CAN see this message.";
	close;

function F_test2 {
	// don't stop the script
}
}
````
