### ISSUE TITLE
unitalk not work on mob

### ISSUE THREAD

**Issue by esu1214** [rathena/rathena#967]
Yeah, I've tested and find a bug.

	.@BossID = monster("prontera",156,114,"--ja--",1002,1,"shop#ddro::OnKick");
	unittalk .@BossID, "123456789！";

The poring will never say anything.
I have debugged and found that map_id2bl will return NULL in unittalk script function.

**Comment by esu1214** [comment]
.@BossID = monster("prontera",156,114,"--ja--",1002,1,"shop#ddro::OnKick");
Seemed not support this type.

**Comment by aleos89** [comment]
It's not a bug. You're using that script command incorrectly. If you check out doc/script_commands.txt you will see this line under `*monster`:
```
Returned value is an array with the game ID of the spawned monster(s) depending
on the amount spawned. Array is stored in $@mobid[].
```
