### ISSUE TITLE
show matk in equip window

### ISSUE THREAD

**Issue by julia40124009** [rathena/rathena#976]
status_calc_ematk function  (status.c)

status_calc_ematk inside sc status not display in equip window

in twro , it show in equip window

[no ALL_ODINS_POWER status](http://truth.bahamut.com.tw/s01/201203/f269fe6c0b30916872b3ee7f1ec95e0e.JPG)
matk : 224+56

[ALL_ODINS_POWER status](http://truth.bahamut.com.tw/s01/201203/bb52356a7ee0c29fdd7eb7e4fa5e404c.JPG)
matk : 224+156

version : https://github.com/rathena/rathena/commit/de08a3677e43442b8b03be591731bf19252b8dc1
mode : renewal

**Comment by aleos89** [comment]
Pretty much related to #554. It's a known issue that the status display window needs to be update.

**Comment by julia40124009** [comment]
hmm .. maybe it can be show
https://github.com/rathena/rathena/blob/master/src/map/status.c#L4699
above add 
`sd->bonus.ematk = status_calc_ematk(bl, sc, sd->bonus.ematk);`

but still bug , after odins sc status end , not refresh ematk in equip window

**Comment by aleos89** [comment]
Fixed in a75133e.
