### ISSUE TITLE
[BUG] Exp Super Novice e Super Novice HP 99+

### ISSUE THREAD

**Issue by Badarosk0** [rathena/rathena#979]
- Currently the Super Novice and Exp . Super Novice when they are at level 99 receive 2000 HP . But if the level was changed to 100+ HP 2000 are lost .

- It is also delivered HP +2000 to reach level 150.

Although the script show something similar to lv 99+ , is down to higher levels .

status.c

#ifndef HP_SP_TABLES
			if ((sd->class_&MAPID_UPPERMASK) == MAPID_SUPER_NOVICE && sd->status.base_level >= 99)
				bonus += 2000; // Supernovice lvl99 hp bonus.
#endif

http://irowiki.org/wiki/Super_Novice

**Comment by cydh** [comment]
Well,
Somehow I believe (Exp.) Super Novice, *should be* on **MAX LEVEL**, receives MHP +2000.
We know, official max level for (Exp.) Sunov is 99, that's why they say "level 99" or "level 160". But on our ends, it must be **MAX LEVEL**.

**Comment by Badarosk0** [comment]
Well, if you notice , our **MAX_LEVEL** today is 175 , so it would not be the problem .

#define **MAX_LEVEL** 175

**Comment by Playtester** [comment]
I intentionally did it like that (if you use the official max HP/SP tables) because that's how it works on official servers, so this is working as intended.

Official servers just do it via HP/SP tables and adjust them whenever the max level is increased. We should do that too, at least when the define HP_SP_TABLES is set. When we start supporting a higher max level by default, we should also update the HP/SP tables accordingly.

**Comment by Playtester** [comment]
Edit: Actually it seems that on some official servers SN get +2000 HP on level 99+ and additional +2000 HP at max level. =o

I can't confirm it but people from bRO showed me screenshots.

**Comment by Playtester** [comment]
Update: It seems that when they raised the max level from 150 to 160, they removed the +2000 HP from the base HP table again. Probably was hardcoded in the end.

**Comment by Playtester** [comment]
As we don't have any means to test it on a server with max level above 150 and I'm updating the HP/SP values anyway, I'll fix this at the same time. For now it'll be solved via HP/SP tables if available and otherwise there will be a fixed hardcoded bonus.
