### ISSUE TITLE
Meteor Storm

### ISSUE THREAD

**Issue by Playtester** [rathena/rathena#983]
On official servers, Meteor Storm places all Meteor Storm units at castend. You can remove them at any time until the Meteor starts falling. If removed, the meteor no longer starts falling and won't deal damage.

So on level 10, it will actually place 7 1x1 units on random positions in a 7x7 area around cast center a castend. Each cell has a different delay (from 0ms to 6000ms). After the delay a meteor starts following when the unit was not removed in the meantime. One second later, the damage is applied and the unit is removed.

**Comment by stealth62** [comment]
thank you sir
