### ISSUE TITLE
Error on clones/disguise

### ISSUE THREAD

**Issue by Spenon** [rathena/rathena#989]
[Error Picture Click here](http://tinypic.com/r/2yyum4z/9)

i just want to ask what seems to be the problem regarding this error?

most errors on my revision is about mobs/evilclones etc.

**Comment by Playtester** [comment]
Probably because "vd" is null. Should probably check it first.

**Comment by Lemongrass3110** [comment]
Please provide more information on this issue(git hash and prerenewal/renewal mode).
Also if you have a more detailed stack trace it would be nice if you could post it here.

Thank you.

**Comment by Lemongrass3110** [comment]
No additional information for almost a month now. Closing this.
