### ISSUE TITLE
Client 2015-10-29

### ISSUE THREAD

**Issue by admkakaroto** [rathena/rathena#992]
The words or phrases entered by a player are not completely seen by another player. Independent player put a whole phrase or just one word, the last letter is always cut.

Player says:
http://i.imgur.com/Tb47Fgr.jpg

Another Player see:
http://i.imgur.com/0NngPoC.jpg

I thank you very much!

**Comment by aleos89** [comment]
Do you have this line (https://github.com/rathena/rathena/blob/master/src/map/clif.c#L9805) in your source?

I tested on a clean rA (4ff4fe4) and couldn't reproduce this.

**Comment by admkakaroto** [comment]
Yes: http://i.imgur.com/CLBpAuX.png

**Comment by admkakaroto** [comment]
I've been doing some tests, I do not know if you have some kind of connection, but to use the Frost ability Joke texts are not displayed and a message appears on map_server, see:

IMG: http://i.imgur.com/9NHj2r7.png

**Comment by Darkelfen** [comment]
I've got a very similar issue but on the party chat instead. 
The last letter in every message written through partychat is dropped. 
Also I've updated to lastest and I'm also receiving the malformed package from <player name>.
