### ISSUE TITLE
Immunity To Burning Bugged

### ISSUE THREAD

**Issue by Everade** [rathena/rathena#996]
Immunity to burning using the following item script does not work:
`bonus2 bResEff,Eff_Burning,10000;`

Such as officialy used on the Bijou Card and Enhanced Amdarais Card combo bonus.
`4635:4636,{ bonus2 bResEff,Eff_Burning,10000; }`

You still get the burning effect and the damage inflicted by it still takes place.

**Comment by Everade** [comment]
I guess it's related to this?!

> [Error]: pc_bonus2: SP_RESEFF: 310 is invalid effect.

**Comment by aleos89** [comment]
Looks like ResEff is ignoring anything outside of this range:
```
	SC_STONE = 0,
	SC_COMMON_MIN = 0, // begin
	SC_FREEZE,
	SC_STUN,
	SC_SLEEP,
	SC_POISON,
	SC_CURSE,
	SC_SILENCE,
	SC_CONFUSION,
	SC_BLIND,
	SC_BLEEDING,
	SC_DPOISON, //10
	SC_COMMON_MAX = 10, // end
```

**Comment by Everade** [comment]
On a sidenote, i'm using this effect on a custom MVP cards since quite a while already.
**So it worked in the past,** but it has been bugged since quite a longer time span as of now.

**Comment by Playtester** [comment]
There are many things not properly implemented regarding the new common status changes. I noticed when testing burning from Flame Launcher that it expires before it even deals damage for example.

With renewal a few more common ailments where added, but they are currently not defined as common, but instead defined further down the list.

New "Common" status ailments on official servers are the following:
IMPRISON: Resist = STR, Duration = 18000+2000(fixed)
FEAR: Resist = INT, Duration = 18000+2000(fixed)
BURNING: Resist = AGI, Duration = 18000+2000(fixed)

Resist% from stats = ResistStat/5 + Level/5 + Luk/10

Resist% from items is applied after that. So for example if level and all stats are 100 and you have a 50% resist item and the base chance is 100%, it would be:

**100%** ---(20+20+10=50% stat resist)---> **50%** ---(50% resist item)---> **25%**

**Comment by Everade** [comment]
By the way:
If DURATION is NOT shown , instead it shows **%s**
on the **BURNING status icon ** on mouse over
Is this rAthena related? Because client side it seems to be fine...

**Comment by Darkelfen** [comment]
Flame Launcher issue is because it reads duration2 instead of duration1, changed that on skill_db and worked.

**Comment by Playtester** [comment]
```
	if(!(flag&SCSTART_NOICON) && !(flag&SCSTART_LOADED && StatusDisplayType[type]))
		clif_status_change(bl,StatusIconChangeTable[type],1,tick,(val_flag&1)?val1:1,(val_flag&2)?val2:0,(val_flag&4)?val3:0);
```
Well we do send "tick" to the client for all status changes. Burning didn't have an icon though. Does it really say "%s" or does it maybe say "% s"? Could be a client bug that placeholder has a typo.

**Comment by Everade** [comment]
{ "%s", COLOR_TIME },

It says %s
also ingame
![burnicon](https://cloud.githubusercontent.com/assets/12261601/14190366/a23aaffc-f792-11e5-9642-0d0d3603c756.png)

**Comment by Playtester** [comment]
Does it say %s also for status changes that work?

**Comment by Everade** [comment]
No Frost Misty for example works just fine.
However i have to admit that i'm not able to find this text inside the 
**stateiconinfo.lub**

Kinda confused right now.

**Comment by Playtester** [comment]
Can you post the entry for Frost Misty then? I want to compare.

**Comment by Everade** [comment]
`StateIconList[EFST_IDs.EFST_FROSTMISTY] = {
	haveTimeLimit = 1,
	posTimeLimitStr = 2,
	descript = {
		{ "Frost Misty", COLOR_TITLE_DEBUFF },
		{ "%s", COLOR_TIME },
		{ "Decreases DEF, ASPD, Movement Speed" },
		{ "Increases fixed cast time" }
	}
}
`

**Comment by Everade** [comment]
Any updates on the topic or the issue mentioned above?

**Comment by Playtester** [comment]
I couldn't fix it, I don't see anything different between the status change that works and the one that doesn't work, though, I have a new client now so maybe I could check if it works with that client, hmmm...

**Comment by Everade** [comment]
I'm more interested into a fix of the topic itself.
The timer issue would be a great addition though ^ _^

**Comment by Everade** [comment]
bump

**Comment by Everade** [comment]
@Playtester 
@aleos89 
bump

**Comment by aleos89** [comment]
As for the icon issue, I think it is possibly due to that kRO changed to the newer versions, so that may be why the timer isn't showing anymore.

As for the item bonus, I'll start working on a fix.

**Comment by Everade** [comment]
@aleos89 
looking forward to it, thank you .

**Comment by Everade** [comment]
@aleos89 
any update on this?

**Comment by aleos89** [comment]
I'm going to re-open this for now. We have another fix for this that I'd rather apply than a hotfix.

**Comment by Everade** [comment]
Any news on this?

**Comment by Jeybla** [comment]
Why do you close all these issues? Could we keep them open? I know we're behind with some stuff, but mostly because we were changing some base functionality of rathena. Thanks for your understanding.

**Comment by Everade** [comment]
Jeybla has been inactive for several months.
Is there any other developer who's going to take care his assigned bugs instead?

New bugs are being fixed all the time, but the old ones are simply abbandoned and we're not allowed to bump them.

**Comment by aleos89** [comment]
I just worked on a fix for this last night. Once I’ve finished testing I’ll open a PR.
