### ISSUE TITLE
Jack Frost and status trap base chance

### ISSUE THREAD

**Issue by Playtester** [rathena/rathena#997]
Tested Jack Frost base chance:
Same Level vs 0 Mdef = 100% success
Same Level vs 50 Mdef = 100% success
Same Level vs 80 Mdef = 40% success

Conclusion: The base chance should be 200%.

**Comment by AnisotropicDefixation** [comment]
Why would this skill disregard resistances?

**Comment by Playtester** [comment]
Might as well fix the following trap base chances at the same time:

Flasher Level 1 vs 0% resist = 100% success
Flasher Level 1 vs 55% resist = 45% success
Flasher Level 5 vs 0% resist = 100% success
Flasher Level 5 vs 55% resist = 45% success

Freezing Trap Level 1 vs 0% resist = 100% success
Freezing Trap Level 1 vs 55% resist = 45% success
Freezing Trap Level 5 vs 0% resist = 100% success
Freezing Trap Level 5 vs 55% resist = 45% success

Conclusion: Both Flasher and Freezing Trap have a base chance of 100% on all levels. Same result for pre-renewal!

Land Mine Level 1 vs 0% resist = 12/200 success
Land Mine Level 5 vs 0% resist = 23/200 success

Inconclusive, need larger test array. TODO.

**Comment by Playtester** [comment]
Some additional fixes:
Sandman Sleep and Throw Stone Blind duration is 30s in pre-renewal and 20s in renewal.

**Comment by aleos89** [comment]
Adding a comment here, that it's been confirmed that the Trap skills for Mercenaries also match those durations from Hunters.
