### ISSUE TITLE
Gunslinger Mine / Ground Drift

### ISSUE THREAD

**Issue by Playtester** [rathena/rathena#998]
There are still many things wrong with the skill:
- Knockback (fire sphere) should be 3 tiles
- Stun duration should be 5s
- Blind / Silence duration should be 30s (pre-re) or 20s (re)
- Freeze duration defined is 12s (pre-re) or 30s (re), but Freeze ends after 1 second (see below)
- The status change happens immediately when the monsters steps on the mine, but the damage and stop effect is applied after aMotion, making Freeze fairly useless as the damage breaks it
- The base chance that a status effect happens should be 50% on all levels
- Damage formula in pre-renewal is normal damage + level*50 fixed neutral damage, Cydh has applied a fix but the damage is still too low (level 1 actually does less damage than my normal attack)
- Damage formula in renewal should be 200%+20%*level damage, there is no longer fixed neutral damage, if enemy has 100% resist to element, gunslinger mine will now miss too
- The mine should disappear immediately after activating (in rAthena the effect stays for about 1500ms?)
- Trap does not activate on allies in PVP

Fully confirmed for renewal. Pre-renewal is from information on wikis and forums.

**Comment by Playtester** [comment]
More tests on renewal: Damage&% increase cards work, reduction cards work too.

**Comment by stealth62** [comment]
Great work sir :+1:
